### ISSUE TITLE
singularity freezes when I run docker container

### ISSUE THREAD

**Issue by antonkulaga** [apptainer/singularity#1000]
## Version of Singularity:

Master

### Expected behavior
When I run:
```
singularity run docker://quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa
```
it should run the container

### Actual behavior

It freezes with:
```
Docker image path: quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa
Cache folder set to /home/antonkulaga/.singularity/docker
[1/14] ||----------------------------------|   0.0% 
```

### Steps to reproduce behavior
```
singularity run docker://quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa
```
on Ubuntu-based Linux (in my case I use Linux Mint)

**Comment by vsoch** [comment]
It's likely just downloading huge layers. Could you test with a smaller image? eg ubuntu

**Comment by GodloveD** [comment]
1000!!!

**Comment by vsoch** [comment]
omg. Can we give @antonkulaga a prize?

**Comment by vsoch** [comment]
:100: + 0

**Comment by vsoch** [comment]
Oh, also please still try this command with a smaller image. Even if it wasn't an issue you should still get a prize!!

**Comment by gmkurtzer** [comment]
I just tested it, and while it did take a bit to get it going it worked for me.

BTW, WAHOOOOO!!! 1000+!

**Comment by gmkurtzer** [comment]
Oh, but apparently the package is broken. Not sure if this is the same upstream, but permissions are wrong:
```
$ singularity run docker://quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa
Docker image path: quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa
Cache folder set to /home/gmk/.singularity/docker
[14/14] |===================================| 100.0% 
Creating container runtime...
chmod: changing permissions of ‘/tmp/.singularity-runtime.ckkbCZGs/quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa/etc/alternatives/lzmore’: Operation not permitted
/opt/FastQC/wrapper.sh: line 13: /opt/FastQC/fastqc: Permission denied
```

When I shell into the container and look at that file:
```
$ singularity exec docker://quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa ls -l /opt/FastQC/fastqc
Docker image path: quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa
Cache folder set to /home/gmk/.singularity/docker
Creating container runtime...
-rw-r--r-- 1 gmk gmk 13775 Nov 20  2015 /opt/FastQC/fastqc
```

Can someone confirm that this is the same if we run this via Docker?

Thanks!

**Comment by vsoch** [comment]
```
docker run --entrypoint /bin/sh -it quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa
# ls -l /opt/FastQC/fastqc
-rwxr-xr-x 1 root root 13775 Nov 20  2015 /opt/FastQC/fastqc
```

**Comment by gmkurtzer** [comment]
Uh-oh... We may have an issue then @vsoch. Any idea what could be causing the permissions to be wrong via the Singularity side? Maybe we should splat out the tarballs for this container and see what is going on.

**Comment by gmkurtzer** [comment]
YAY, this looks great now, thank you @vsoch!
```
$ singularity exec docker://quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa ls -l /opt/FastQC/fastqc
Docker image path: quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa
Cache folder set to /home/gmk/.singularity/docker
Creating container runtime...
-rwxr-xr-x 1 gmk gmk 13775 Nov 20  2015 /opt/FastQC/fastqc
```

**Comment by vsoch** [comment]
yeah, this was a tough one! Getting back different orderings depending on the schema version. I sure as heck hope to not see this one again... possibly famous last words... 

Going to close issue. @antonkulaga I still want to point out you were number #1000 and you sort of need a prize. If you want one :)

**Comment by bauerm97** [comment]
@vsoch We might be able to send out a little Singularity swag package if @antonkulaga is interested :) @gmkurtzer

**Comment by gmkurtzer** [comment]
Great idea @bauerm97! @antonkulaga Are you going to be at SC?

**Comment by antonkulaga** [comment]
Hi. Wow, did not expect to open an issue and get a prize! ;) What is required from my side?

> Are you going to be at SC?

probably not. When/where is it going to be?

**Comment by gmkurtzer** [comment]
Heya @antonkulaga, Supercomputing is in Denver mid November.

**Comment by antonkulaga** [comment]
No, I will not be there. I am located in Europe and Supercomputing is not my area of expertise

**Comment by gmkurtzer** [comment]
@antonkulaga If you send me your mailing address (via email direct gmkurtzer@gmail) I will get some stickers and stuff sent to you! WAHOO, you won! lol
