### ISSUE TITLE
Moderate warning messages

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#1006]
## Version of Singularity:

2.3.9-development.gf44e68d

### Expected behavior

Warnings in `build` explain the situation to the user without causing alarm.

### Actual behavior

Warnings are too scary. 

If you `build` as an unprivileged user (from docker, shub, local image, or tarball) tar is used to copy files to staging area.  If files in the original container are root owned and non-readable by user they will not be copied to new image.  But this is actually not as big of a deal as you may think.  

If you can't read a file then you also can't execute it.  So it is basically useless to you.  In a non-suid environment you will never be able to do anything useful with these files.  So if their absence breaks your container your container is already broken because you can't access them anyway. 

### Steps to reproduce behavior

`build` from shub and watch the warnings.

**Comment by bauerm97** [comment]
I'm going to assume that this issue is no longer relevant since #1007 was merged, and as such I'll go ahead and close it

**Comment by GodloveD** [comment]
Ahh.  Thanks @bauerm97.
