### ISSUE TITLE
2.4 (Development) singularity apps --help not well formed

### ISSUE THREAD

**Issue by victorsndvg** [apptainer/singularity#1014]
## Version of Singularity:

2.4 (Development) - e92fc6a

### Expected behavior

well formed help

### Actual behavior

$ singularity apps --help
...
    SINGULARITY_APPNAME     the name of the application
    SINGULARITY_APPROOT     the application base
    SINGULARITY_APPMETA     the application metadata folder
    SINGULARITY_DATA        the base of scif defined data (/scif/data
    SINGULARITY_APPDATA     the data base folder, with subfolders for:
    SINGULARITY_APPINPUT    the expected input folder for the application
    SINGULARITY_APPOUTPUT   the output data folder of the application
...

### Steps to reproduce behavior

$ singularity apps --help

**Comment by vsoch** [comment]
Do you mean to say we just need to clean up the language a bit? The entire help when you ask for help for apps, akin to to any command (run, exec, shell, etc.) isn't going to be in json or anything like that. Here is the section in entirety:

```
singularity apps --help
USAGE: singularity [...] apps <container path>
List applications (apps) installed in a container, located at
    /scif/apps. See http://containers-ftw.org/SCI-F/

EXAMPLES:
    
    $ singularity apps ubuntu.img
    total 8.0K
    4.0 bar
    4.0 foo


To access apps, use shell, exec, run with --app <appname>

With all of the above, the following environment variables are available
to you when called from the shell inside the container:

    SINGULARITY_APPNAME     the name of the application
    SINGULARITY_APPROOT     the application base
    SINGULARITY_APPMETA     the application metadata folder
    SINGULARITY_DATA        the base of scif defined data (/scif/data
    SINGULARITY_APPDATA     the data base folder, with subfolders for:
    SINGULARITY_APPINPUT    the expected input folder for the application
    SINGULARITY_APPOUTPUT   the output data folder of the application
    
For additional help, please visit our public documentation pages which are
found at:

    http://singularity.lbl.gov/


```
Could you be specific about what kind of details you'd like to see? I can definitely improve upon it- but probably not tonight / this morning, I'm pooped.

**Comment by victorsndvg** [comment]
Ok, nothing really important ... 

* I see open, but not closed, parentheses  in the `SINGULARITY_DATA` explanation.
* `SINGULARITY_APPDATA` help ends with a colon. After 3 reads, I'm not very clever, I understood that  `SINGULARITY_APPDATA`  is the root for `SINGULARITY_APPINPUT` and  `SINGULARITY_APPOUTPUT` directories. I'm right? If yes, I would like to read something like "the data base folder for `SINGULARITY_APPINPUT` and  `SINGULARITY_APPOUTPUT`"

Hope it helps!

**Comment by vsoch** [comment]
okay here is a new go!

https://github.com/singularityware/singularity/pull/1013/files#diff-4a4539d8668c3900e18d70edbf6fa4c5

**Comment by vsoch** [comment]
```
USAGE: singularity [...] apps <container path>
List applications (apps) installed in a container, located at
    /scif/apps. See http://containers-ftw.org/SCI-F/

EXAMPLES:
    
    $ singularity apps ubuntu.img
     bar
     foo

To access apps, use shell, exec, run, inspect with --app <appname>

With all of the above, the following environment variables are available
to you when called from the shell inside the container. The top variables
are relevant to the active app (--app <app>) and the bottom available
for all apps regardless of the active:


ACTIVE APP ENVIRONMENT:

    SINGULARITY_APPNAME     the name of the application
    SINGULARITY_APPROOT     the application base (/scif/apps/<app>)
    SINGULARITY_APPMETA     the application metadata folder
    SINGULARITY_APPDATA     the data base folder for active app
        SINGULARITY_APPINPUT    expected input folder within data base folder
        SINGULARITY_APPOUTPUT   the output data folder within data base folder


GLOBAL APP ENVIRONMENT:
    
    SINGULARITY_DATA        scif defined data base for all apps (/scif/data)
    SINGULARITY_APPS        scif defined install bases for all apps (/scif/apps)
    APPROOT_<app>           root for application <app>
    APPDATA_<app>           data root for application <app>


For additional help, please visit our public documentation pages which are
found at:

    http://singularity.lbl.gov/

```

**Comment by victorsndvg** [comment]
It sounds perfect for me! Thanks! :+1:
