### ISSUE TITLE
singularity bootstrap fails

### ISSUE THREAD

**Issue by ahmedhany93** [apptainer/singularity#1015]
## Version of Singularity:

2.3.2-dist

### Expected behavior

successful bootstrap operation.

### Actual behavior

ERROR: Could not locate /bin/sh inside the container

### Steps to reproduce behavior

Everything was fine before updating to v 2.3.2.
After updating these are the steps i have done
`sudo singularity create image.img `
`sudo singularity -vvv bootstrap image.img deb.def`

**Comment by vsoch** [comment]
What's in your definition file?

**Comment by ahmedhany93** [comment]
DistType "debian"
MirrorURL "http://free.hands.com/debian/"
OSVersion "stretch"

Setup
Bootstrap

export DEBIAN_FRONTEND=noninteractive

InstallPkgs git redmine php-zip php-curl php-mbstring php-xml php7.0 apache2 libapache2-mod-php7.0
InstallPkgs libterm-readline-gnu-perl



Cleanup

**Comment by vsoch** [comment]
I think we switched from "debian" as the base to "debootstrap" You can try that, or just do away with the host issues and try:

```
From: ubuntu:stretch
Boostrap: docker
```

**Comment by GodloveD** [comment]
It also looks like you are using a very old syntax for your recipe file.  This syntax was deprecated in 2.2 I think?  Anyway try this instead:
```
Bootstrap: debootstrap
OSVersion: stretch
MirrorURL: http://ftp.us.debian.org/debian/

%environment
    export DEBIAN_FRONTEND=noninteractive

%post
    export DEBIAN_FRONTEND=noninteractive
    apt-get -y update
    apt-get -y install git redmine php-zip php-curl php-mbstring php-xml php7.0 \
                    apache2 libapache2-mod-php7.0 libterm-readline-gnu-perl
```

**Comment by ahmedhany93** [comment]
i am always gettin the same error after changing the def file.
`sudo singularity --debug bootstrap container.img new.def
Enabling debugging
Ending argument loop
Singularity version: 2.3.2-dist
Exec'ing: /usr/local/libexec/singularity/cli/bootstrap.exec
VERBOSE [U=0,P=4242]       message_init()                            Set messagelevel to: 5
VERBOSE [U=0,P=4242]       singularity_config_parse()                Initialize configuration file: /usr/local/etc/singularity/singularity.conf
DEBUG   [U=0,P=4242]       singularity_config_parse()                Starting parse of configuration file /usr/local/etc/singularity/singularity.conf
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key allow setuid = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key max loop devices = '256'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key allow pid ns = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key config passwd = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key config group = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key config resolv_conf = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key mount proc = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key mount sys = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key mount dev = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key mount home = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key mount tmp = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key mount hostfs = 'no'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key bind path = '/etc/localtime'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key bind path = '/etc/hosts'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key user bind control = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key enable overlay = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key mount slave = 'yes'
VERBOSE [U=0,P=4242]       singularity_config_parse()                Got config key sessiondir max size = '16'
DEBUG   [U=0,P=4242]       singularity_config_parse()                Finished parsing configuration file '/usr/local/etc/singularity/singularity.conf'
VERBOSE [U=0,P=4242]       singularity_registry_init()               Initializing Singularity Registry
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'COMMAND' = 'bootstrap'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(COMMAND, bootstrap) = 0
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'SYSCONFDIR' = '/usr/local/etc'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(sysconfdir, /usr/local/etc) = 0
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'BUILDDEF' = 'new.def'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(BUILDDEF, new.def) = 0
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'WRITABLE' = '1'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(WRITABLE, 1) = 0
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'VERSION' = '2.3.2-dist'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(version, 2.3.2-dist) = 0
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'IMAGE' = 'container.img'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(IMAGE, container.img) = 0
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'MESSAGELEVEL' = '5'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(MESSAGELEVEL, 5) = 0
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'BINDIR' = '/usr/local/bin'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(bindir, /usr/local/bin) = 0
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'LOCALSTATEDIR' = '/usr/local/var'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(localstatedir, /usr/local/var) = 0
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'LIBEXECDIR' = '/usr/local/libexec'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(libexecdir, /usr/local/libexec) = 0
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning NULL on 'HOME'
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning NULL on 'TARGET_UID'
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning NULL on 'TARGET_GID'
DEBUG   [U=0,P=4242]       singularity_priv_init()                   Initializing user info
DEBUG   [U=0,P=4242]       singularity_priv_init()                   Set the calling user's username to: root
DEBUG   [U=0,P=4242]       singularity_priv_init()                   Marking uinfo structure as ready
DEBUG   [U=0,P=4242]       singularity_priv_init()                   Obtaining home directory
VERBOSE [U=0,P=4242]       singularity_priv_init()                   Set home (via getpwuid()) to: /root
INFO    [U=0,P=4242]       main()                                    Sanitizing environment
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SINGULARITY_COMMAND
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: LS_COLORS
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SINGULARITY_sysconfdir
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SINGULARITY_BUILDDEF
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: LANG
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: DISPLAY
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SUDO_GID
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: COLORTERM
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: USERNAME
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SUDO_COMMAND
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SINGULARITY_WRITABLE
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: USER
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SINGULARITY_version
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: PWD
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: HOME
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SUDO_USER
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SINGULARITY_IMAGE
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SUDO_UID
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: MAIL
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: TERM
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SHELL
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SINGULARITY_MESSAGELEVEL
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SHLVL
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SINGULARITY_bindir
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: LOGNAME
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: XAUTHORITY
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: PATH
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SINGULARITY_localstatedir
DEBUG   [U=0,P=4242]       envclean()                                Unsetting environment variable: SINGULARITY_libexecdir
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'WRITABLE' = '1'
VERBOSE [U=0,P=4242]       singularity_registry_set()                Found prior value for 'WRITABLE', overriding with '1'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(WRITABLE, 1) = 0
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning value from registry: 'IMAGE' = 'container.img'
DEBUG   [U=0,P=4242]       singularity_config_get_value_impl()       No configuration entry found for 'limit container owners'; returning default value 'NULL'
DEBUG   [U=0,P=4242]       singularity_config_get_value_impl()       No configuration entry found for 'limit container paths'; returning default value 'NULL'
DEBUG   [U=0,P=4242]       singularity_image_open()                  Opening file descriptor to image: container.img
DEBUG   [U=0,P=4242]       singularity_suid_enabled()                Executable is not SUID
VERBOSE [U=0,P=4242]       singularity_image_check()                 Checking what kind of image we are mounting
VERBOSE [U=0,P=4242]       singularity_image_check_image()           Checking that file pointer is a Singularity image
DEBUG   [U=0,P=4242]       singularity_image_check_image()           First line of image(fd=4): #!/usr/bin/env run-singularity

DEBUG   [U=0,P=4242]       singularity_image_check_image()           Checking if first line matches key
VERBOSE [U=0,P=4242]       singularity_image_check_image()           File is a valid Singularity image
DEBUG   [U=0,P=4242]       singularity_runtime_ns()                  Calling: _singularity_runtime_ns_mnt()
DEBUG   [U=0,P=4242]       singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(mount slave, yes)
DEBUG   [U=0,P=4242]       singularity_config_get_value_impl()       Returning configuration value mount slave='yes'
DEBUG   [U=0,P=4242]       singularity_config_get_bool_char_impl()   Return singularity_config_get_bool(mount slave, yes) = 1
DEBUG   [U=0,P=4242]       singularity_priv_escalate()               Running as root, not changing privileges
DEBUG   [U=0,P=4242]       singularity_runtime_ns_mnt()              Virtualizing FS namespace
DEBUG   [U=0,P=4242]       singularity_runtime_ns_mnt()              Virtualizing mount namespace
DEBUG   [U=0,P=4242]       singularity_runtime_ns_mnt()              Making mounts slave
DEBUG   [U=0,P=4242]       singularity_priv_drop()                   Running as root, not changing privileges
DEBUG   [U=0,P=4242]       singularity_config_get_value_impl()       Returning configuration value max loop devices='256'
DEBUG   [U=0,P=4242]       singularity_image_bind()                  Entered singularity_image_bind()
DEBUG   [U=0,P=4242]       singularity_image_bind()                  Converting max_loop_devs_string to int: '256'
DEBUG   [U=0,P=4242]       singularity_image_bind()                  Converted max_loop_devs_string to int: '256' -> 256
DEBUG   [U=0,P=4242]       singularity_image_bind()                  Checking if this image has been properly opened
DEBUG   [U=0,P=4242]       singularity_image_bind()                  Checking if image is valid file
DEBUG   [U=0,P=4242]       singularity_image_bind()                  Checking if image is already bound to a loop device
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning value from registry: 'WRITABLE' = '1'
DEBUG   [U=0,P=4242]       singularity_image_bind()                  Setting loopdev open to: O_RDWR
DEBUG   [U=0,P=4242]       singularity_image_bind()                  Setting LO_FLAGS_AUTOCLEAR
DEBUG   [U=0,P=4242]       singularity_image_bind()                  Calculating image offset
VERBOSE [U=0,P=4242]       singularity_image_offset()                Calculating image offset
VERBOSE [U=0,P=4242]       singularity_image_offset()                Found image at an offset of 31 bytes
DEBUG   [U=0,P=4242]       singularity_image_offset()                Returning image_offset(image_fp) = 31
DEBUG   [U=0,P=4242]       singularity_priv_escalate()               Running as root, not changing privileges
DEBUG   [U=0,P=4242]       singularity_image_bind()                  Finding next available loop device...
VERBOSE [U=0,P=4242]       singularity_image_bind()                  Found available loop device: /dev/loop0
DEBUG   [U=0,P=4242]       singularity_image_bind()                  Setting loop device flags
DEBUG   [U=0,P=4242]       singularity_priv_drop()                   Running as root, not changing privileges
VERBOSE [U=0,P=4242]       singularity_image_bind()                  Using loop device: /dev/loop0
VERBOSE [U=0,P=4242]       singularity_runtime_rootfs()              Set container directory to: /usr/local/var/singularity/mnt/container
DEBUG   [U=0,P=4242]       singularity_runtime_rootfs()              Checking for container directory
DEBUG   [U=0,P=4242]       singularity_runtime_rootfs()              Returning container_directory: /usr/local/var/singularity/mnt/container
DEBUG   [U=0,P=4242]       chk_mode()                                Checking exact mode (40755) on: /usr/local/var/singularity/mnt/container
DEBUG   [U=0,P=4242]       chk_mode()                                Found appropriate mode on file: /usr/local/var/singularity/mnt/container
VERBOSE [U=0,P=4242]       singularity_image_mount()                 Checking what kind of image we are mounting
VERBOSE [U=0,P=4242]       singularity_image_mount()                 Attempting to mount as singularity image
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning value from registry: 'WRITABLE' = '1'
DEBUG   [U=0,P=4242]       singularity_priv_escalate()               Running as root, not changing privileges
VERBOSE [U=0,P=4242]       singularity_image_mount_image_mount()     Mounting /dev/loop0 in read/write to: /usr/local/var/singularity/mnt/container
DEBUG   [U=0,P=4242]       singularity_priv_drop()                   Running as root, not changing privileges
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'PATH' = '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'
DEBUG   [U=0,P=4242]       singularity_runtime_rootfs()              Returning container_directory: /usr/local/var/singularity/mnt/container
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'SINGULARITY_ROOTFS' = '/usr/local/var/singularity/mnt/container'
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning value from registry: 'LIBEXECDIR' = '/usr/local/libexec'
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'SINGULARITY_libexecdir' = '/usr/local/libexec'
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning value from registry: 'IMAGE' = 'container.img'
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'SINGULARITY_IMAGE' = 'container.img'
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning value from registry: 'BUILDDEF' = 'new.def'
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'SINGULARITY_BUILDDEF' = 'new.def'
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning value from registry: 'MESSAGELEVEL' = '5'
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'SINGULARITY_MESSAGELEVEL' = '5'
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning NULL on 'NOTEST'
DEBUG   [U=0,P=4242]       envar_set()                               Unsetting environment variable: SINGULARITY_NOTEST
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning NULL on 'BUILDSECTION'
DEBUG   [U=0,P=4242]       envar_set()                               Unsetting environment variable: SINGULARITY_BUILDSECTION
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning NULL on 'BUILDNOBASE'
DEBUG   [U=0,P=4242]       envar_set()                               Unsetting environment variable: SINGULARITY_BUILDNOBASE
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning NULL on 'CACHEDIR'
DEBUG   [U=0,P=4242]       envar_set()                               Unsetting environment variable: SINGULARITY_CACHEDIR
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning value from registry: 'VERSION' = '2.3.2-dist'
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'SINGULARITY_version' = '2.3.2-dist'
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'HOME' = '/root'
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'LANG' = 'C'
DEBUG   [U=0,P=4242]       singularity_registry_get()                Returning value from registry: 'BUILDDEF' = 'new.def'
INFO    [U=0,P=4242]       bootstrap_init()                          Building from bootstrap definition recipe
VERBOSE [U=0,P=4242]       bootstrap_keyval_parse()                  Got bootstrap definition key/val 'Bootstrap' = 'debootstrap'
VERBOSE [U=0,P=4242]       singularity_registry_set()                Adding value to registry: 'DRIVER' = 'debootstrap'
DEBUG   [U=0,P=4242]       singularity_registry_set()                Returning singularity_registry_set(DRIVER, debootstrap) = 0
DEBUG   [U=0,P=4242]       uppercase()                               Transformed to uppercase: 'Bootstrap' -> 'BOOTSTRAP'
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'BOOTSTRAP' = 'debootstrap'
VERBOSE [U=0,P=4242]       bootstrap_keyval_parse()                  Got bootstrap definition key/val 'OSVersion' = 'stretch'
DEBUG   [U=0,P=4242]       uppercase()                               Transformed to uppercase: 'OSVersion' -> 'OSVERSION'
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'OSVERSION' = 'stretch'
VERBOSE [U=0,P=4242]       bootstrap_keyval_parse()                  Got bootstrap definition key/val 'MirrorURL' = 'http://ftp.us.debian.org/debian/'
DEBUG   [U=0,P=4242]       uppercase()                               Transformed to uppercase: 'MirrorURL' -> 'MIRRORURL'
DEBUG   [U=0,P=4242]       envar_set()                               Setting environment variable: 'MIRRORURL' = 'http://ftp.us.debian.org/debian/'
VERBOSE [U=0,P=4258]       message_init()                            Set messagelevel to: 5
DEBUG   [U=0,P=4258]       main()                                    Iterating through file looking for sections matching: %pre
Adding base Singularity environment to container
I: Retrieving InRelease 
I: Retrieving Release 
E: Failed getting release file http://ftp.us.debian.org/debian/dists/stretch/Release
ABORT: Aborting with RETVAL=255

`

**Comment by vsoch** [comment]
Did you try the Docker base?

**Comment by ahmedhany93** [comment]
yup, i did  with ubuntu and it completed successfully. But i need Debian on my image.

**Comment by vsoch** [comment]
they have that one too :) https://hub.docker.com/_/debian/

**Comment by ahmedhany93** [comment]
Thank you very much, this fixed my issue
