### ISSUE TITLE
Singularity occasionally doesn't execute RUN/EXEC, and seems to return 0 exit code

### ISSUE THREAD

**Issue by lordzappo** [apptainer/singularity#1016]
## Version of Singularity:

2.2.9 
### Expected behavior

We have "bwa" bioinformatics tool dockered, bootstrap to singularity.  We use that all the time! works well.  We have another tool "bcftools" prepared in same fashion.

On both AMI/AWS and LSF/HPC, we occasionally get into a condition where both these images fail to execute, and fail to return help text for underlying exec/run with no arguments.   

 It's relatively rare, for example we launched 1700 bwa+singularity jobs this weekend and 5 had this issue.  The five were all on the same node, and they ran within a minute of each other, but didn't start simultaneously or overlap afaict from logs.   While the 5 broken "bwa" jobs were launching/returning nothing within a few seconds of launch and not computing as desired, we had 3 other singularities running successfully on the same node, so it doesn't seem to be a node specific singularity issue.  And as I said, we see it on AWS/AMI implementation of the same pipeline/singularity images as well, so not hardware, linux version, or filesystem specific.

### Steps to reproduce behavior

We can't yet reproduce it. We attempted to by setting large amounts of threads to call the bwa image with no arguments on a node, but they always return help in our test (the expected behavior). , I am writing in to ask if anyone else has reported this, it's hard to even describe, and searching the issues didn't seem to yield a result.

In the attached image of the cacti cluster monitor software, the top 5 bwa jobs should run for about 20minutes, but instead singularity returns nothing/0 and they run for 2seconds.  You can see other singularized code running below those five in this screenshot, and other bwa jobs launched on the node before and after. 

![image](https://user-images.githubusercontent.com/1440762/31178353-cadb42c6-a8e6-11e7-9675-ca360212b4ac.png)

This is a showstopper for our HPC using singularity, unfortunately. 

Specifically we first call the image with  
bwa_help = subprocess.Popen(bwa_cmd,stderr=subprocess.PIPE,shell=True).communicate()[1]

Any advice or insights would help. 

This also happens with bcftools container, but I dont have a good snapshot of the cluster to show you for that yet.

One commonality between both non-deterministic images is that they use htslib.  I can't see how this might affect or cause this bug, but I mention it for completeness.   
https://github.com/samtools/htslib

**Comment by gmkurtzer** [comment]
Can you run all of your jobs with the `--debug` Singularity option, and if you see the error again, collect that log, and send it in? I'd be happy to look to see if there is something Singularity is doing wrong which might cause this, or maybe we got a system error and didn't return error properly.

Also, the version you are testing seems to say 2.2.9. Can you verify that? Typically the x.y.9 releases are alpha or beta prereleases. For example, right now we have 2.3.9 in our development branch and that is our beta for the 2.4 release.

Thanks!

**Comment by lordzappo** [comment]
Thanks @gmkurtzer.  We will attempt to gather this and reply to this ticket with more information. 

Edit: 2.2.0 was broken at release for us, so we went to 2.2.9.  We can upgrade cluster or AMI to 2.3.0 eventually, but it introduced a breaking change in how we build images, so not yet, that issue is here: https://github.com/singularityware/singularity/issues/920

**Comment by gmkurtzer** [comment]
Oh, thanks for the version explanation, gotcha. There were some fixes that we also introduced in 2.3.1 and 2.3.2 which might have solved that issue, as well it would be interesting to test against our 2.4 beta (release will be hopefully right around the corner).

Greg

**Comment by bauerm97** [comment]
@lordzappo As @gmkurtzer said, it would be incredibly helpful to get the debug output from the jobs that are exiting. Now just as a random thought, maybe it has something to do with number of loopback devices available. I know that we've had some problems before with a race condition where starting large numbers of jobs simultaneously on one node could cause certain jobs to fail

**Comment by lordzappo** [comment]
@bauerm97 Thanks for the additional information.  At the time of this writing, we have enabled --debug on the AMI/AWS, and hopefully the condition will recur there as we test and develop the cloud variant.   We will enable --debug and resume using singularity on the HPC cluster after we process some critical data and can be more fault tolerant.  

I will probably not be able to get you these files for at least a few days, depending on when it recurs and how much data we are running in cloud tests.   But I do intend to get you them.  I will investigate the number of loopback devices on both environments as well, and possibly set them higher.

**Comment by lordzappo** [comment]
@bauerm97 it seems the default for Centos 6 /RHEL loopback devices available might be 8, so your scenario is more  towards probable than possible, as our nodes have 32 to 64 slots apiece.

**Comment by bauerm97** [comment]
@lordzappo Awesome, that would make both of our lives easier if that turns out to be the case. Keep us informed and let us know if that fixes your issues or if you keep experiencing issues. Thanks :)

**Comment by gmkurtzer** [comment]
I've tested RHEL6 (and compats), and even though the default is 8, that is only for automatic creation of loop devices. singularity triggers the creation of the loop device automatically, and I've tested upwards of 256, so I don't think that is the root cause. Hopefully the --debug will either confirm or deny that idea.

Thanks!

**Comment by lordzappo** [comment]
@bauerm97 @gmkurtzer is there any undocumented way to get the debug output to go to a file.  Several of the steps in the pipeline use pipes to save on disk writes.  debug on all of them is impossible, as the pipeline is written now.

**Comment by gmkurtzer** [comment]
Nope, good idea, but the feature doesn't exist.

**Comment by dtrudg** [comment]
Closing this as there has been no update / further information. Note that newer versions of Singularity 3.x include various fixes around loop device handling. Please feel free to open an issue if you are still affected.
