### ISSUE TITLE
2.4 (Development) singularity check-h behaviour

### ISSUE THREAD

**Issue by victorsndvg** [apptainer/singularity#1022]
## Version of Singularity:

2.4 (Development) - e92fc6a

### Expected behavior

```
$ singularity check -h 
```
is a valid option (as it appear in help)

### Actual behavior

running the following command
```
$ singularity check -h $IMAGE 
```
return the check help message.

### Steps to reproduce behavior

```
$ singularity check -h $IMAGE
```

**Comment by vsoch** [comment]
Good catch, we should remove the -h as it conflicts with the help command.

**Comment by victorsndvg** [comment]
Thanks! 

closing ...
