### ISSUE TITLE
Uninitialized config when using --user within docker container

### ISSUE THREAD

**Issue by johanneskoester** [apptainer/singularity#1035]
## Version of Singularity:

2.3.1

### Expected behavior

I tried to run `singularity shell` from within an unpriviledged docker container with `--cap-add=SYS_ADMIN`. A default singularity config (unmodified) is present and I hoped it to work.

### Actual behavior

Singularity fails with
```
Progress |===================================| 100.0% 
Singularity: action (U=0,P=20)> Called singularity_config_get_value on uninitialized config subsystem

ERROR  : Called singularity_config_get_value on uninitialized config subsystem
Singularity: action (U=0,P=20)> Retval = 255

ABORT  : Retval = 25
```

### Steps to reproduce behavior

* Install singularity into a docker container or use `quay.io/snakemake/snakemake`.
* Execute with `sudo docker run -i -t --cap-add SYS_ADMIN quay.io/snakemake/snakemake /bin/bash`.
* singularity shell -u shub://vsoch/hello-world

**Comment by GodloveD** [comment]
When you say that the docker container is unprivileged does that mean that users cannot escalate privs?  Singularity does things (like mount to loop devices) that require escalated privs.  This is accomplished via suid bit.  If suid does not work in the docker environment neither will Singularity.  

Is `ping` installed in your Docker container?  Are you able to use it like so:

```
ping 8.8.8.8
```
If so, so suid is working as expected.  

If this works can you complete your command with the global `--debug` option enabled and paste the output?

**Comment by johanneskoester** [comment]
Yes, the ping command works fine (after installing ping). THis is the output with --debug:
```
$ singularity --debug run -u shub://vsoch/hello-world

Enabling debugging
Ending argument loop
Singularity version: 2.3.2-dist
Exec'ing: /usr/lib/x86_64-linux-gnu/singularity/cli/run.exec
Evaluating args: '-u shub://vsoch/hello-world'
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /root/.singularity
VERBOSE2 SINGULARITY_ENVIRONMENT found as None/.singularity.d/env/90-environment.sh
VERBOSE2 SINGULARITY_RUNSCRIPT found as None/singularity
VERBOSE2 SINGULARITY_TESTFILE found as None/.singularity.d/test
VERBOSE2 SINGULARITY_DEFFILE found as None/.singularity.d/Singularity
VERBOSE2 SINGULARITY_HELPFILE found as None/.singularity.d/runscript.help
VERBOSE2 SINGULARITY_ENVBASE found as None/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as None/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_NOHTTPS found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as .
VERBOSE2 SHUB_NAMEBYHASH not defined (None)
VERBOSE2 SHUB_NAMEBYCOMMIT not defined (None)
VERBOSE2 SHUB_CONTAINERNAME not defined (None)
VERBOSE2 SINGULARITY_CONTENTS found as /tmp/.singularity-layerfile.0UMzEW
VERBOSE2 SINGULARITY_PYTHREADS found as 9
DEBUG 
*** STARTING SINGULARITY PYTHON PULL ****
VERBOSE2 SINGULARITY_CONTAINER found as shub://vsoch/hello-world
VERBOSE2 SINGULARITY_PULLFOLDER found as .
DEBUG Found uri shub://
DEBUG Found uri shub://
DEBUG Headers found: Content-Type,Accept
DEBUG GET https://singularity-hub.org/api/container/vsoch/hello-world:latest
DEBUG GET (stream) https://www.googleapis.com/download/storage/v1/b/singularity-hub-regional/o/singularity-hub-regional%2Fgithub.com%2Fvsoch%2Fhello-world%2Ff9cd90a7b030a9c794bfe76c123da5a518ad9962%2Fabba5a1f91b2e98ebe125fc7a5151b33.img.gz?generation=1506018782576457&alt=media
Progress |===================================| 100.0% 
VERBOSE2 Running command gzip -d -f ./vsoch-hello-world-master.img.gz with subprocess
DEBUG Writing Singularity Hub image path to /tmp/.singularity-layerfile.0UMzEW
VERBOSE2 Writing file /tmp/.singularity-layerfile.0UMzEW with mode w.
VERBOSE [U=0,P=23]         message_init()                            Set messagelevel to: 5
VERBOSE [U=0,P=23]         singularity_config_parse()                Initialize configuration file: /etc/singularity/singularity.conf
DEBUG   [U=0,P=23]         singularity_config_parse()                Starting parse of configuration file /etc/singularity/singularity.conf
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key allow setuid = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key max loop devices = '256'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key allow pid ns = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key config passwd = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key config group = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key config resolv_conf = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key mount proc = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key mount sys = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key mount dev = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key mount home = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key mount tmp = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key mount hostfs = 'no'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key bind path = '/etc/localtime'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key bind path = '/etc/hosts'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key user bind control = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key enable overlay = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key mount slave = 'yes'
VERBOSE [U=0,P=23]         singularity_config_parse()                Got config key sessiondir max size = '16'
DEBUG   [U=0,P=23]         singularity_config_parse()                Finished parsing configuration file '/etc/singularity/singularity.conf'
VERBOSE [U=0,P=23]         singularity_registry_init()               Initializing Singularity Registry
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'COMMAND' = 'run'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(COMMAND, run) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'SYSCONFDIR' = '/etc'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(sysconfdir, /etc) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'PULLFOLDER' = '.'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(PULLFOLDER, .) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'CONTAINER' = 'shub://vsoch/hello-world'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(CONTAINER, shub://vsoch/hello-world) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'VERSION' = '2.3.2-dist'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(version, 2.3.2-dist) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'IMAGE' = './vsoch-hello-world-master.img'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(IMAGE, ./vsoch-hello-world-master.img) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'MESSAGELEVEL' = '5'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(MESSAGELEVEL, 5) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'CONTENTS' = '/tmp/.singularity-layerfile.0UMzEW'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(CONTENTS, /tmp/.singularity-layerfile.0UMzEW) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'BINDIR' = '/usr/bin'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(bindir, /usr/bin) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'VERSION' = '2.3.2'
VERBOSE [U=0,P=23]         singularity_registry_set()                Found prior value for 'VERSION', overriding with '2.3.2'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(VERSION, 2.3.2) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'NOSUID' = '1'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(NOSUID, 1) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'LOCALSTATEDIR' = '/var/lib'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(localstatedir, /var/lib) = 0
VERBOSE [U=0,P=23]         singularity_registry_set()                Adding value to registry: 'LIBEXECDIR' = '/usr/lib/x86_64-linux-gnu'
DEBUG   [U=0,P=23]         singularity_registry_set()                Returning singularity_registry_set(libexecdir, /usr/lib/x86_64-linux-gnu) = 0
DEBUG   [U=0,P=23]         singularity_registry_get()                Returning NULL on 'HOME'
DEBUG   [U=0,P=23]         singularity_registry_get()                Returning NULL on 'TARGET_UID'
DEBUG   [U=0,P=23]         singularity_registry_get()                Returning NULL on 'TARGET_GID'
DEBUG   [U=0,P=23]         singularity_priv_init()                   Initializing user info
DEBUG   [U=0,P=23]         singularity_priv_init()                   Set the calling user's username to: root
DEBUG   [U=0,P=23]         singularity_priv_init()                   Marking uinfo structure as ready
DEBUG   [U=0,P=23]         singularity_priv_init()                   Obtaining home directory
VERBOSE [U=0,P=23]         singularity_priv_init()                   Set home (via getpwuid()) to: /root
VERBOSE [U=0,P=23]         singularity_suid_init()                   Running NON-SUID program workflow
DEBUG   [U=0,P=23]         singularity_suid_init()                   Checking program has appropriate permissions
VERBOSE [U=0,P=23]         singularity_priv_userns()                 Invoking the user namespace
DEBUG   [U=0,P=23]         singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(allow user ns, yes)
DEBUG   [U=0,P=23]         singularity_config_get_value_impl()       No configuration entry found for 'allow user ns'; returning default value 'yes'
DEBUG   [U=0,P=23]         singularity_config_get_bool_char_impl()   Return singularity_config_get_bool(allow user ns, yes) = 1
VERBOSE [U=0,P=23]         singularity_priv_userns()                 Not virtualizing USER namespace: running as root
DEBUG   [U=0,P=23]         singularity_priv_userns()                 Returning singularity_priv_init(void)
DEBUG   [U=0,P=23]         singularity_priv_drop()                   Running as root, not changing privileges
DEBUG   [U=0,P=23]         singularity_registry_get()                Returning NULL on 'CLEANUPDIR'
DEBUG   [U=0,P=23]         singularity_registry_get()                Returning NULL on 'NOSESSIONCLEANUP'
DEBUG   [U=0,P=23]         singularity_registry_get()                Returning NULL on 'NOCLEANUP'
DEBUG   [U=0,P=23]         singularity_cleanupd()                    Not running a cleanup thread, no 'SINGULARITY_CLEANUPDIR' defined
DEBUG   [U=0,P=23]         singularity_runtime_ns()                  Calling: _singularity_runtime_ns_pid()
DEBUG   [U=0,P=23]         singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(allow pid ns, yes)
Singularity: action (U=0,P=23)> Called singularity_config_get_value on uninitialized config subsystem

ERROR   [U=0,P=23]         singularity_config_get_value_impl()       Called singularity_config_get_value on uninitialized config subsystem
Singularity: action (U=0,P=23)> Retval = 255

ABORT   [U=0,P=23]         singularity_config_get_value_impl()       Retval = 255
```

**Comment by bgagl** [comment]
Hi there, is there a solution to this problem? 
encountered a very similar one (see below).

Best wishes, 
Ben



singularity --debug run -u shub://vsoch/hello-world
Enabling debugging
Ending argument loop
Singularity version: 2.4.2-dist
Exec'ing: /usr/lib/x86_64-linux-gnu/singularity/cli/run.exec
Evaluating args: '-u shub://vsoch/hello-world'
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /data/home1/bgagl/.singularity
VERBOSE2 REGISTRY not defined (None)
VERBOSE2 NAMESPACE not defined (None)
VERBOSE2 SINGULARITY_DOCKER_ARCHITECTURE found as amd64
VERBOSE2 SINGULARITY_DOCKER_OS found as linux
VERBOSE2 SINGULARITY_ENVIRONMENT found as None/.singularity.d/env/90-environment.sh
VERBOSE2 SINGULARITY_RUNSCRIPT found as None/singularity
VERBOSE2 SINGULARITY_TESTFILE found as None/.singularity.d/test
VERBOSE2 SINGULARITY_DEFFILE found as None/.singularity.d/Singularity
VERBOSE2 SINGULARITY_HELPFILE found as None/.singularity.d/runscript.help
VERBOSE2 SINGULARITY_ENVBASE found as None/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as None/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_NOHTTPS found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as .
VERBOSE2 SHUB_NAMEBYHASH not defined (None)
VERBOSE2 SHUB_NAMEBYCOMMIT not defined (None)
VERBOSE2 SHUB_CONTAINERNAME not defined (None)
VERBOSE2 SINGULARITY_CONTENTS found as /scratch/.singularity-layerfile.IY5098
VERBOSE2 SINGULARITY_PYTHREADS found as 9
DEBUG
*** STARTING SINGULARITY PYTHON PULL ****
VERBOSE2 SINGULARITY_CONTAINER found as shub://vsoch/hello-world
VERBOSE2 SINGULARITY_PULLFOLDER found as .
DEBUG Found uri shub://
DEBUG Headers found: Content-Type,Accept
DEBUG GET https://www.singularity-hub.org/api/container/vsoch/hello-world:latest
DEBUG Pull folder set to /data/home1/bgagl
DEBUG Pulling to /data/home1/bgagl/vsoch-hello-world-master-latest
DEBUG GET (stream) https://www.googleapis.com/download/storage/v1/b/singularityhub/o/singularityhub%2Fgithub.com%2Fvsoch%2Fhello-world%2Fe279432e6d3962777bb7b5e8d54f30f4347d867e%2Fed9755a0871f04db3e14971bec56a33f%2Fed9755a0871f04db3e14971bec56a33f.simg?generation=1508072025589820&alt=media
Progress |===================================| 100.0%
ERROR  : Called singularity_config_get_value on uninitialized config subsystem
ABORT  : Retval = 255
DEBUG Found None image
DEBUG Writing Singularity Hub image path to /scratch/.singularity-layerfile.IY5098
VERBOSE2 Writing file /scratch/.singularity-layerfile.IY5098 with mode w.
VERBOSE [U=2447,P=52102]   message_init()                            Set messagelevel to: 5
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Initialize configuration file: /etc/singularity/singularity.conf
DEBUG   [U=2447,P=52102]   singularity_config_parse()                Starting parse of configuration file /etc/singularity/singularity.conf
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key allow setuid = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key max loop devices = '64'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key allow pid ns = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key config passwd = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key config group = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key config resolv_conf = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key mount proc = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key mount sys = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key mount dev = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key mount devpts = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key mount home = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key mount tmp = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key mount hostfs = 'no'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key bind path = '/etc/localtime'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key bind path = '/etc/hosts'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key user bind control = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key enable overlay = 'no'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key mount slave = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key sessiondir max size = '16'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key allow container squashfs = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key allow container extfs = 'yes'
VERBOSE [U=2447,P=52102]   singularity_config_parse()                Got config key allow container dir = 'yes'
DEBUG   [U=2447,P=52102]   singularity_config_parse()                Finished parsing configuration file '/etc/singularity/singularity.conf'
VERBOSE [U=2447,P=52102]   singularity_registry_init()               Initializing Singularity Registry
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'COMMAND' = 'run'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(COMMAND, run) = 0
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'SYSCONFDIR' = '/etc'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(sysconfdir, /etc) = 0
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'PULLFOLDER' = '.'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(PULLFOLDER, .) = 0
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'CONTAINER' = 'shub://vsoch/hello-world'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(CONTAINER, shub://vsoch/hello-world) = 0
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'VERSION' = '2.4.2-dist'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(version, 2.4.2-dist) = 0
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'IMAGE' = '/data/home1/bgagl/vsoch-hello-world-master-latest.simg'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(IMAGE, /data/home1/bgagl/vsoch-hello-world-master-latest.simg) = 0
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'MESSAGELEVEL' = '5'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(MESSAGELEVEL, 5) = 0
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'CONTENTS' = '/scratch/.singularity-layerfile.IY5098'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(CONTENTS, /scratch/.singularity-layerfile.IY5098) = 0
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'BINDIR' = '/usr/bin'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(bindir, /usr/bin) = 0
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'NOSUID' = '1'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(NOSUID, 1) = 0
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'LOCALSTATEDIR' = '/var/lib'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(localstatedir, /var/lib) = 0
VERBOSE [U=2447,P=52102]   singularity_registry_set()                Adding value to registry: 'LIBEXECDIR' = '/usr/lib/x86_64-linux-gnu'
DEBUG   [U=2447,P=52102]   singularity_registry_set()                Returning singularity_registry_set(libexecdir, /usr/lib/x86_64-linux-gnu) = 0
DEBUG   [U=2447,P=52102]   singularity_registry_get()                Returning NULL on 'HOME'
DEBUG   [U=2447,P=52102]   singularity_registry_get()                Returning NULL on 'TARGET_UID'
DEBUG   [U=2447,P=52102]   singularity_registry_get()                Returning NULL on 'TARGET_GID'
DEBUG   [U=2447,P=52102]   singularity_priv_init()                   Initializing user info
DEBUG   [U=2447,P=52102]   singularity_priv_init()                   Set the calling user's username to: bgagl
DEBUG   [U=2447,P=52102]   singularity_priv_init()                   Marking uinfo structure as ready
DEBUG   [U=2447,P=52102]   singularity_priv_init()                   Obtaining home directory
VERBOSE [U=2447,P=52102]   singularity_priv_init()                   Set home (via getpwuid()) to: /data/home1/bgagl
VERBOSE [U=2447,P=52102]   singularity_suid_init()                   Running NON-SUID program workflow
DEBUG   [U=2447,P=52102]   singularity_suid_init()                   Checking program has appropriate permissions
VERBOSE [U=2447,P=52102]   singularity_priv_userns()                 Invoking the user namespace
DEBUG   [U=2447,P=52102]   singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(allow user ns, yes)
DEBUG   [U=2447,P=52102]   singularity_config_get_value_impl()       No configuration entry found for 'allow user ns'; returning default value 'yes'
DEBUG   [U=2447,P=52102]   singularity_config_get_bool_char_impl()   Return singularity_config_get_bool(allow user ns, yes) = 1
DEBUG   [U=2447,P=52102]   singularity_priv_userns()                 Attempting to virtualize the USER namespace
DEBUG   [U=65534,P=52102]  singularity_priv_userns()                 Enabled user namespaces
DEBUG   [U=65534,P=52102]  singularity_priv_userns()                 Setting setgroups to: 'deny'
DEBUG   [U=65534,P=52102]  singularity_priv_userns()                 Updating setgroups: /proc/52102/setgroups
DEBUG   [U=65534,P=52102]  singularity_priv_userns()                 Setting GID map to: '2447 2447 1'
DEBUG   [U=65534,P=52102]  singularity_priv_userns()                 Updating the parent gid_map: /proc/52102/gid_map
DEBUG   [U=65534,P=52102]  singularity_priv_userns()                 Setting UID map to: '2447 2447 1'
DEBUG   [U=65534,P=52102]  singularity_priv_userns()                 Updating the parent uid_map: /proc/52102/uid_map
DEBUG   [U=2447,P=52102]   singularity_priv_userns()                 Returning singularity_priv_init(void)
DEBUG   [U=2447,P=52102]   singularity_priv_drop()                   Not dropping privileges, user namespace enabled
ERROR   [U=2447,P=52102]   singularity_config_get_value_multi_impl() Called singularity_config_get_value on uninitialized config subsystem
ABORT   [U=2447,P=52102]   singularity_config_get_value_multi_impl() Retval = 255
`

**Comment by dtrudg** [comment]
Closing this issue as the reports are against 2.3 and 2.4 which are not longer supported. In 3.x there has been a complete rewrite and much change around user namespace support etc. If you experience issues on 3.x please open a new issue. Many thanks!
