### ISSUE TITLE
Allow users to select the default shell for the shebang in %runscript

### ISSUE THREAD

**Issue by ghost** [apptainer/singularity#1038]
The `/singularity` script that is created from the %runscript section in the definition file has a default `#!/bin/sh` shebang instruction. It would be good to be able to select other shells, like the Bourne shell, maybe through a parameter in the definition file.
My use case, in particular, is the need to activate a conda environment inside the container by running
`source activate <env_name>`
The activate script from conda only supports bash. The workaround, at the moment, is to write something like:
```
%runscript
/bin/bash <<EOF
    source activate <env_name>
    echo "some code here"
EOF 
```
But having the possibility of selecting the default shell would simplify and streamline the entry point script.

**Comment by GodloveD** [comment]
I think this is a good idea.  Maybe we could parse the runscript for the presence of a `#!` in the first line and column.  If it's there, we use that line as shebang.  If it's not there we default to `#!/bin/sh`.  Thoughts?

**Comment by ghost** [comment]
Hi, any chance that this feature will be considered for inclusion? It should be pretty easy to implement, I guess :)

**Comment by ghost** [comment]
Actually, I would be happy to contribute to the project implementing the feature myself.

For that I would welcome some hints of where I should look inside the code... I tried to figure it out myself but I think it's a bit involved... 😅

**Comment by GodloveD** [comment]
Cool!  We can always use the help.  I would look [here](https://github.com/singularityware/singularity/blob/development/libexec/bootstrap-scripts/deffile-sections.sh#L184-L187) and [here](https://github.com/singularityware/singularity/blob/e480d9640f5e76a51af7a9f43e87b77f008f6652/libexec/bootstrap-scripts/functions#L52-L68)

**Comment by GodloveD** [comment]
Whoops!  The link I sent you above is actually for the startscript (new feature in 2.4).  But whatever we do for the runscript (very next section) we should also do for the startscript.  (Please also change the comment above the startscript section when you submit this PR.)  Thank you!

**Comment by GodloveD** [comment]
Heya @robmosca!  Did you still want to work on this?  I actually have [something](https://github.com/GodloveD/singularity/tree/custom-shebang) coded up, but I've been holding off on pull request in case you still want to take a stab at it.
