### ISSUE TITLE
Signal catching during singularity build

### ISSUE THREAD

**Issue by justbennet** [apptainer/singularity#1040]
Per suggestion of V on Slack, I submit this issue.

## Version of Singularity

2.3.9-development.g9fabbd8

### Expected behavior

Upon receving a Ctrl-C, SIGTERM, or SIGKILL, singularity would attempt to clean up temporary files in /tmp/.singularity-build*.

I think singularity should print a message that large amounts of data may be left in the currently defined /tmp/.singularity-build* directory if it terminates because of a signal, and it would be a courtesy to remind the user that there may be a large amount of data cached in another hidden directory /root/.singularity/[docker|*].

The same message would be a useful reminder at the end of successful completion, too, for all that.

I also wonder somewhat about the wisdom of making those hidden directories, as it was probably harder to find them than it needs to be.  Why not make them visible directories?

### Actual behavior

Downloaded installation data is left in /tmp/.singularity-build*
Downloaded files are left in /root/.singularity

### Steps to reproduce behavior

Run

$ sudo singularity build test.simg test.def

When it is done exploding layers, Ctrl-C to abort.

Run

$ sudo du -sh /tmp/.singularity-build*

Mine is a large image, and I get these.

4.6G        .singularity-build.XeLHCk/
1.7G        /root/.singularity/docker

**Comment by cclerget** [comment]
@justbennet problem with /tmp/.singularity-build* has been fixed in 2.4: https://github.com/singularityware/singularity/pull/1031

Just a thought, maybe a command to view/delete cache could be helpful ?

**Comment by justbennet** [comment]
Yes, I think that would be quite helpful.

A reminder that there is a cache for both the user and the sudo user would be quite helpful as well!

If you can think of an appropriate place to put it in the documentation, I think it would be fabulous to document what files/folders will be created by Singularity during a build/run, where they would be put, what their names will look like, and what their contents would be for both regular users and for the privileged user.

I'm happy to provide a rough draft if the basic data is given to me.  Also more than happy to cast an editorial eye over anything already (or subsequently) done.

Thanks!

**Comment by vsoch** [comment]
@justbennet I had started this page http://singularity.lbl.gov/build-environment but it could probably use some work! It's mostly focused on the user facing variables and doesn't comment on some of the singularity internal bits (eg, runtime and cache not revealed to the user)

**Comment by justbennet** [comment]
@vsoch That's a great start!  Thanks!

I don't know how the rest of the world goes about doing this.  I suspect, though, that are quite a few people like me who are administrators of a 'target' system -- one where the container will be run -- and we're building many of these in lieu of installing the software stack.  If that is the case, then I think that know where the cache files and temp files are is part of the 'normal course of operations'.

Would you consider pulling just the section about the cache location out of the build-environment page and putting it onto the http://singularity.lbl.gov/docs-build-container page under 'More Build Topics' as a note to service administrators and maybe adding a note about temp files?

That would then be a natural lead-in to the line to customizing the cache for real, which I suspect  will be mostly used by service administrators, anyway.  It would also make this potentially important information more visible by being one-level less deep.  That's particularly useful for people who don't know what to search for to get the answer they need but who might well recognize the answer if the see it.

In looking at this, I found myself distinguishing, in my own mind, between 'Build environment' and 'Container Environment and Metadata'.  One of the more common issues we have at out site is that the environment of the user building software often differs from that of the user of the software, which leads to some avoidable situations of missing libraries or path entries.

Do you think there is any merit in considering, specifically, a note about that somewhere in the documentation?  Also, possibly, renaming the section in the main menu under Getting Started -> 'Environment and Metadata' to 'Container Environment and Metadata'?  It follows the section 'Container Checks', so adding the qualifier shouldn't be too jarring.

**Comment by WestleyK** [comment]
Looks like the issue (Signal catching during singularity build) was fixed by https://github.com/sylabs/singularity/pull/1031. (also not a issue in master v3.X). Closing. Reopen if needed.

**Comment by vsoch** [comment]
Thanks @WestleyK I just tried it out and I don't see any remaining build folders in /tmp. @justbennet can comment if he has further run into the issue.

@justbennet have your suggestions / comments been addressed with respect to fixes to the documentation?
