### ISSUE TITLE
"bind path" config option set up differently than all others

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#1043]
I just noticed the following looking through the commits changing the configuration file to find any new / change / removed config option (release nots sadly don't list that, but it's needed to adapt our puppet module...). 

Since:
https://github.com/singularityware/singularity/commit/ae36ecb4ef0eb939416ac35589950ba51e30deb2
the configuration option "bind path" is handled differently from all others:

1. The configuration option name is now hardcoded. Since the macro is still used in https://github.com/singularityware/singularity/blob/e480d9640f5e76a51af7a9f43e87b77f008f6652/src/lib/runtime/mounts/binds/binds.c#L55 , this will lead to a hidden bug once either is changed. 
2. The macro `BIND_PATH_DEFAULT` is not used anymore. 

Since this change is likely to lead to a bug in the future (and is non-obvious), I thought I'd best report that.

**Comment by olifre** [comment]
Same is true for `autofs bug path` option. For parsing, macro is used, but not for config file generation. 

https://github.com/singularityware/singularity/commit/445152390173becaa7a1b3ccaaf76bcad7a69bff

**Comment by olifre** [comment]
The first issue also mean the statement:
```
DEFAULT: Undefined
```
given in the config file is plainly wrong.

**Comment by dtrudg** [comment]
I believe this is now not relevant on current 3.x. Please reopen if there is an issue.
