### ISSUE TITLE
OverlayFS default option value broken

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#1044]
Since: 
https://github.com/singularityware/singularity/blob/e480d9640f5e76a51af7a9f43e87b77f008f6652/configure.ac#L257
the configure-macro uses some obscure "autodetection" on the build machine to deduce whether overlayfs is available on the execute machine. Since in any reasonable production setup (not talking about development here!), the build and execute machines do not coincide, this is a broken idea. 

Apart from the fact that this is something all distributions downstream have to patch out again (build environments are by rule kept clean from stuff not needed for build!), this detection is also broken. For example, I have OverlayFS built into my kernel, which makes this arcane algorithm fail. 

This is of course something ok for the testing environments, but not for the actual build. Actual build should do as common practice:
Add a config option like `--enable-overlayfs` / `--disable-overlayfs`. 

To let you know, we are building Singularity on Open Build Service in clean VM environments, and running then on several distributions in production. 

Edit: Since for my system that means overlayFS is now off by default, I added the `[Regression]` flag.

**Comment by DrDaveD** [comment]
@olifre What version are you looking at?  The just-released singularity-2.4 tries to avoid that problem by adding a 'try' config option to let it try overlay at run time if it can't determine the issue at build time.  See pr #912.  If you select "Blame" at the link you gave, you can see that the line you link to has been there a year.

**Comment by olifre** [comment]
@DrDaveD You are fully correct, it's not a regression, but actually appears to be broken since long. Sorry for misidentifying that. 

The "try" technique does not help with that at all. First of, the idea of detecting something at build time on a build machine and assuming that will be valid on the execute machine is broken by design. Build machines are minimal systems to ensure no dependencies are accidentally automagically included and hence forgotten. Heck, they may even run a different kernel. 
Execute nodes will be substantially different. 

Secondly, it will fail if overlayfs is built into the kernel. On my 4.13 kernel with overlayfs built-in, I get:
```
checking for overlayfs... no                                                                                                                                                                                                                 
```
The reason is:
I do have `modules.dep`, but there is no string matching `overlayfs.ko` in it. 

So yes, you are right, it's not a regression (and not introduced by the PR you linked), it's broken since very long time.

**Comment by DrDaveD** [comment]
@olifre Are you talking about a build environment that you control, or is it the case that 4.13 kernels normally do not have overlayfs.ko?  If the former, maybe you can change the build environment to not have modules.dep?  That's what koji (an rpm build an environment) does. Or if the latter, is there another module that singularity configure can look for in its place?

Alternatively perhaps the default for singularity should just always be 'try', at least in place of 'no'. Maybe it could still default to 'yes' if the module is found.

**Comment by olifre** [comment]
@DrDaveD: 

For the case at hand, I am talking about my Gentoo system - these usually have self-built kernels. In my case, I have overlayFS compiled into the kernel, not as module. So the kernel supports overlayFS, but there is no module to be found. Please don't add more logic (such as parsing the kernel config or stuff like that)... 

I think the current detection code is broken in two ways:
- It assumes the build environment matches the runtime environment. Actually, yes, most build environments (Koji, Open Build Service) will indeed not have a `module.dep`, but I would not derive from that that the current detection code is "correct" (just since absence of `modules.dep` triggers the `try` fallback). If my build environment would have `modules.dep` and `overlayfs.ko` listed inside that, and then I would not install it on my runtime host (say, the distribution would overlayfs in a separate package), then `yes` is for sure a bad value to set as default. 
- If overlayfs is built into the kernel, the code will fail and default to `no` if `modules.dep` exists, even if support is actually present. That's pretty common for Gentoo, LFS and likely Slackware. 

> Alternatively perhaps the default for singularity should just always be 'try', at least in place of 'no'. Maybe it could still default to 'yes' if the module is found.

That's a good idea, I think. I'd say `try` is a nice solution if nothing is specified. 

Still, I think it would be wise to remove the detection code altogether, since deducing run-time environment from build-time environment is a bad idea. 

Secondly, I'd propose to add something like `-enable-overlayfs-default` and `-disable-overlayfs-default` to `configure`. This will allow distributors to change that default in the build recipe on Koji / OBS / whatever they use if they are sure their distro ships overlayfs support (be it as module or in-kernel).

**Comment by DrDaveD** [comment]
Having configure options is not much different than editing the generated singularity.conf after running configure, so I don't see a lot of value in that.  

I'm not sure that deducing run-time environment from build-time environment is in general a bad thing; isn't that what configure does for everything?  I guess the difference in this case is that it is trying to determine something from the kernel configuration, which is not so good.

Although I was the last one to touch this part of the code, I don't feel any ownership of it and the current version is working for systems that I support, so I suggest you submit a pull request for the change you'd like to see.

**Comment by olifre** [comment]
> Having configure options is not much different than editing the generated singularity.conf after running configure, so I don't see a lot of value in that.

Yes and no: Editing the configuration file means changing the result from the build (and deeper knowledge of the package), while having a configure option explicitly states that this is something the person who packages singularity for a distribution should check out. 
So yes, I agree, the end result will be the same. It's more about the usual convention, and clearly communicating that this is something that downstream distributions should ideally care about to define the correct default setting. 


> I'm not sure that deducing run-time environment from build-time environment is in general a bad thing; isn't that what configure does for everything?

Not really - "autodetection" in `configure` or `cmake` is indeed used very often, but is the major source of work for package maintainers. Let's use "root" as example. It has many autodetections and enables / disables features depending on which packages are installed and detected on the machine it is compiled on. 
That means if you want to package it for a distribution, it will be extremely hard just to find all (optional) dependencies which are needed to enable all functionality. Luckily, modern "root" versions offer CMake switches to enable / disable features so maintainers can explicitly state which features the package should have, and then `cmake` will fail if the dependencies are not met, thus explicitly enforcing the dependency instead of "magically" falling back to disabling the feature. . 

Still, as you will find when checking distributions repositories: Root was kicked out from Debian and Ubuntu, the maintenance effort was just too large, especially in times of `configure`. 
The same is true for official RPMs, there has been some effort for Fedora, but the maintainer there needed to spend various weeks of his life on this project. 
Gentoo is currently in a limbo, but luckily a maintainer is picking it up again. 

So yes, autodetection of things is common, but very much frowned upon downstream, since it often creates automagic dependencies. The best solution usually is to also offer a switch in `configure` / `cmake` to express everything that may affect the build result, and allow downstream maintainers to do their thing. 

If you are interested in some more details, here is an effort of packaging ROOT 5 for RPM-based distros:
https://build.opensuse.org/package/view_file/science/root/root.spec?expand=1
Just look at the length - additionally, there are many extra patches and files needed ( https://build.opensuse.org/package/show/science/root ). 
For Gentoo, you can see a recipe for an old v6 release here:
https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-physics/root/root-6.04.06.ebuild
The full range of ugliness required in the `src_prepare` section and the lengthy `src_configure` section are especially interesting. 

> I guess the difference in this case is that it is trying to determine something from the kernel configuration, which is not so good.

Exactly, and additionally, the default even fails on my system ;-). 


> Although I was the last one to touch this part of the code, I don't feel any ownership of it and the current version is working for systems that I support, so I suggest you submit a pull request for the change you'd like to see.

I'll do that as soon as a time slot pops up, and many thanks for the interesting discussion! :)

**Comment by olifre** [comment]
@DrDaveD And I should add, looking at the exact change you did, that indeed you have significantly improved the situation with your change 👍 . Thinking more about it, maybe the best solution would indeed be to use `try` always - the overhead at runtime is incredibly low, and it removes any need for a compile-time decision.

**Comment by olifre** [comment]
Since the fix has been merged, I think we can close this ;-).
