### ISSUE TITLE
image created with default "build" is not executable

### ISSUE THREAD

**Issue by dominik-handler** [apptainer/singularity#1046]
## Version of Singularity: 

2.4-master.g81bf030

### Expected behavior

When container is executed directly runscript should get executed.
Container works when started up with "singularity run xy.img"

### Actual behavior

Since the update to 2.4 I get this error with containers that previously worked:
-bash: ./xy.img: cannot execute binary file: Exec format error

### Steps to reproduce behavior

sudo singularity build xy.img xy_Singularity.txt
./xy.img

**Comment by bauerm97** [comment]
Hi @dominik-handler,

Sorry that this isn't working right. Would you mind sharing with me a recipe file that can reproduce this? Thanks!

I'm unable to reproduce this with a basic container, you can see what I did here:

```
mibauer@ubuntu:~/singularity/test$ ls
Singularity
mibauer@ubuntu:~/singularity/test$ cat Singularity 
Bootstrap: docker
From: centos
IncludeCmd: no

%runscript
	echo "hi"
mibauer@ubuntu:~/singularity/test$ sudo singularity build test.img Singularity 
Using container recipe deffile: Singularity
Sanitizing environment
Adding base Singularity environment to container
Docker image path: index.docker.io/library/centos:latest
Cache folder set to /root/.singularity/docker
Exploding layer: sha256:d9aaf4d82f249dc101a6638ff5177fe926cdebfa6c42d874dfa5029533da0e72.tar.gz
Exploding layer: sha256:53ee036c793c94bbd5b7061c45c6fa375522042e624577f232fda1d88778f242.tar.gz
User defined %runscript found! Taking priority.
Adding runscript
Finalizing Singularity container
Calculating final size for metadata...
Skipping checks
Building Singularity image...
Singularity container built: test.img
Cleaning up...
mibauer@ubuntu:~/singularity/test$ ./test.img 
hi
mibauer@ubuntu:~/singularity/test$ 
```

**Comment by GodloveD** [comment]
I wonder the old version of Singularity was completely uninstalled.  I have a hunch that when you run the container using the `./some.simg` syntax, it is finding the wrong version of Singularity or some leftover parts from the old install.  

Can you verify that you followed the steps outlined [here](http://singularity.lbl.gov/docs-installation#remove-an-old-version) to completely remove the old version of Singularity before updating?

**Comment by dominik-handler** [comment]
Hi, thanks for your replies. 

after your comments I destroyed and rebuilt my VM again (although I did the same before installing 2.4). Now it is working without any issues .

Thank you, 
Dominik

**Comment by GodloveD** [comment]
That's good news!  If you run into any more trouble feel free to re-open or open a new issue.
