### ISSUE TITLE
Release notes do not mention backwards-incompatible changes

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#1051]
The release notes (or separate upgrade hints, maybe) should provide a list of backwards-incompatible changes. 
Otherwise, users using singularity CLI are lost. 

One recent example for that is the change from:
```singularity export```
to
```singularity image.export```
which I did not find stated in the release notes at:
https://github.com/singularityware/singularity/releases

**Comment by GodloveD** [comment]
Hi @olifre, (and @amacbride and @dctrud).  Sorry for the oversight.  Would you mind making a list of the errors you find in the documentation and I will be happy to update?  I appreciate it.

**Comment by olifre** [comment]
Hi @GodloveD , I am not really mentioning errors in the documentation here, but a lack of a crucial part of the release notes. 

While the version numbering scheme of Singularity might indicate differently, the project is still young and new versions are expected to break backwards compatibility. For all users, it is crucial to know what has changed - and I am not talking about new features here. 

It is critical to know:
- renamed commands
- deprecated / removed commands
- changed defaults
- backward incompatible changes (recipe file format? image file format?)
- migration guidance (how to convert images?)
- changed behaviour (recipe sections work differently)

In short, anything which may affect an existing usecase. 
For example, as you can see from the reference provided by @dctrud , a project using Singularity broke. In my case, I had to adapt our build scripts to change to the new syntax for `build` which formerly was called `bootstrap`. Also, several sections behave differently, bootstrapping now uses some cache directories which means build machines need to be provisioned differently etc. 

To keep your userbase for the project and encourage quick updating to new releases, such a list of changes is of critical importance. 
I would expect to find that in the release notes, or, if it is too much of a "wall of text" to put there, at least linked to from the release notes. 

I can try to list the points I stumbled upon, most of which I could only work out by rereading all documentation changes, and parts of the source code. This is not something the average user should be expected to do, and is a huge time investment...

**Comment by dtrudg** [comment]
See also change to -n flag: https://github.com/singularityware/singularity/issues/1105

**Comment by olifre** [comment]
> See also change to -n flag: #1105

Good catch!

Let me also say that I fully underline your statement:

> This is the type of thing that will, unfortunately, hinder adoption of Singularity for our HPC users who have no experience of Linux troubleshooting.

And I should add this will also hinder us cluster admins from upgrading in a decent time scale, since with a missing changelog / effectively broken release notes, it's fully unclear which things will break and what may keep working without re-testing *everything* from scratch and / or reading the source code. 

It is crucial Singularity becomes more friendly to their userbase in this regard, if stability is already claimed (by having a >=1.0 version).

**Comment by vsoch** [comment]
@olifre I completely agree... on behalf of everyone we are so apologetic about this, and hope we can fix it up asap! I can't speak for the other developers, but I'm very green as an open source developer, over all, and a lot of these "check triggers" just haven't been properly set yet. It's really very appreciated to get feedback / issues for these things. :O)

**Comment by dtrudg** [comment]
I think this type of stuff generally gets caught well by the community before stable release, as long as testing dev/rc versions is easy. This essentially relies on:

- Direct access to the documentation for the dev/rc version during the testing phase.
- A changelog that is modified continuously, minimally covering breaking changes.

Hindsight is biased, but given these 2 things I almost certainly would have tested 2.4-dev and I definitely would have caught this one. (-n / --nv ).

Breaking changes in release notes is absolutely critical.

**Comment by GodloveD** [comment]
I agree totally with this as well.  Moving forward I think we should carefully consider changes to the user interface before they are made and try to document them.  We do announce when we are going to release a new version, we freeze the development branch, and we encourage users to begin testing.  The testing phase usually lasts a few weeks.  We usually get 2 or 3 users who do testing and raise issues before release.  @dctrud I'm looking forward to seeing you on that list when we release 3.0.  Thanks!  

I also do think that we need to add a changelog to the project and need to edit it as we develop.  

Sorry for this change in the cli.  We'll try to do better.

**Comment by dtrudg** [comment]
@GodloveD - sounds good. I will definitely be testing future releases. Singularity is a big part of our strategy for giving our users what they want/need, and I do want to contribute (admittedly a v small amount) back through testing.

**Comment by vsoch** [comment]
here is a first go at our changelog! https://github.com/singularityware/singularity/pull/1109. If we can get a reasonable base added, we can go back and retrospectively add some of things we missed. I've already added some of the missing mentioned for this issue.

**Comment by dtrudg** [comment]
Closing this - a change log is now in operation. Thanks!
