### ISSUE TITLE
instance.stop-all does not stop anycontainer

### ISSUE THREAD

**Issue by jorgesece** [apptainer/singularity#1055]
## Version of Singularity: 2.4

singularity instance.stop-all does not stop any container

### Expected behavior

Stop all the containers

### Actual behavior

Does not stop any container

### Steps to reproduce behavior

```
$ sudo singularity instance.list
DAEMON NAME      PID      CONTAINER IMAGE
nginxd_14daa879  20340    /tmp/singularity-nginx
nginxd_1f77a994  20310    /tmp/singularity-nginx
$ sudo singularity instance.stop-all
$ sudo singularity instance.list
DAEMON NAME      PID      CONTAINER IMAGE
nginxd_14daa879  20340    /tmp/singularity-nginx
nginxd_1f77a994  20310    /tmp/singularity-nginx
```

**Comment by GodloveD** [comment]
Hi @jorgesece!  Sorry for the confusion.  We had a `instance.stop-all` command for a while when we were still in development, but we ended up removing it before the 2.4 release.  The syntax is now on of these:
```
singularity instance.stop \*
```
or 
```
singularity instance.stop --all
```
[These docs](http://singularity.lbl.gov/docs-instance-stop) should have up-to-date usage.
