### ISSUE TITLE
Trying to build a 2.4 Debian package from source currently generates one labeled 2.3.2:

### ISSUE THREAD

**Issue by amacbride** [apptainer/singularity#1057]
## Version of Singularity:

2.4

### Expected behavior

Generates a Debian package for version 2.4

### Actual behavior

Generates a package labelled 2.3.2

### Steps to reproduce behavior

```% wget https://github.com/singularityware/singularity/releases/download/2.4/singularity-2.4.tar.gz
% tar xvf singularity-2.4.tar.gz
% cd singularity-2.4
% ./configure --prefix=/usr/local
% sudo apt-get install help2man
% fakeroot dpkg-buildpackage -b -us -uc
```

The build product is: `../singularity-container_2.3.2-1_amd64.deb` (so I'm not sure what's actually in it.)

**Comment by olifre** [comment]
The reason appears to be that during release, somebody forgot to update the changelog here:
https://github.com/singularityware/singularity/blob/master/debian/changelog
Debian packaging pulls the version out of the changelog ( see https://github.com/singularityware/singularity/blob/master/debian/rules ). 

Since @gmkurtzer did the tag and release, giving him a friendly ping here ;-).

**Comment by gmkurtzer** [comment]
Yeah, that was totally my fault. We should probably change it such that it uses the autoconf @VERSION@ string rather then a hard coded tag. Thanks for the ping!

**Comment by gmkurtzer** [comment]
Actually, I take that back. I am looking at how Debian does their building, and the only thing I've found for how it ascertains it's version number is from the changelog. Is that accurate?

**Comment by olifre** [comment]
Yes, indeed, I think the version information is pulled from the Changeling only. AFAIK this is a common technique for Debian, and they also uses this to ensure that a downstream change which enters the Changelog can trigger a new downstream version (such as 2.4-2).

**Comment by smoe** [comment]
Hello. I am developer for Debian and confirm that this are humans who look at the package and kind of read from the changelog or the tarball's filename what the version may be. If in doubt, they ask. As correctly described by @olifre, the number after the "-" starts with 1 for every new upstream version and is increased with every attempt by Debian folks to improve the packaging. 

There is package for Singularity shipping with Debian described at https://tracker.debian.org/pkg/singularity-container . I am not involved with its packaging but typically the maintainers are more than pleased to communicate with/help upstream with whatever issue. Just contact them.

**Comment by dtrudg** [comment]
Closing this as I believe we are now confident on release numbering procedure. Thanks @smoe for this information!
