### ISSUE TITLE
Singularity Hub naming convention updated for Shub 2.0

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#1058]
The new version of singularity hub has support for multiple builds (tags) per repo, along with a branch, so the current download convention would produce two equivalently named images:

```
singularity pull shub://vsoch/hello-world
singularity pull shub://vsoch/hello-world:tag
```
for both:

```
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/vsoch-hello-world-master.simg
```
given they are both on master. In the meantime we can suggest for users to ask for the `--hash` but we ultimately want the default to be:

```
shub://vsoch/hello-world -- > vsoch-hello-world-master-latest.simg
shub://vsoch/hello-world:tag -- > vsoch-hello-world-master-tag.simg
```

**Comment by HenrikBengtsson** [comment]
To me a git tag doesn't really belong to a branch but rather refers to a unique commit in the git graph. May I instead suggest:
```
shub://vsoch/hello-world -- > vsoch-hello-world-master.simg
shub://vsoch/hello-world:develop -- > vsoch-hello-world-develop.simg
shub://vsoch/hello-world:tag -- > vsoch-hello-world-tag.simg
```
When using tags for versioning, then you naturally gets:
```
shub://vsoch/hello-world:1.2 -- > vsoch-hello-world-1.2.simg
```

PS. I'd also argue for dropping the branch annotation for the default git branch, i.e. don't append `-master`. The downside is that `foo-develop` then could mean two things.

**Comment by vsoch** [comment]
Hmm, so the actual git "tag" as in when you tag a repository isn't represented here. The "tag" derived for Singularity Hub is a tag that the user defines based on the extension of the Singularity file. For the naming +1 on dropping the addition of master.

**Comment by HenrikBengtsson** [comment]
Oh. My bad. Sorry for the noice.

**Comment by vsoch** [comment]
No I'm glad you poked! I had forgotten entirely about this issue. In fact I think it might be resolved, because it still is important to maintain both tag **and** branch. For example, when I pull this image now:

```
singularity pull shub://vsoch/hello-world
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/vsoch-hello-world-master-latest.simg
/home/vanessa/vsoch-hello-world-master-latest.simg
```
and I think that is what we would want - because I could have the same tag on different branches, or the same branch with different tags. Do you think this is good? I'm good with this, and am ready to close the issue if you agree! :)

**Comment by dtrudg** [comment]
Closing this, as the above looks good to me and .@vsoch , and there hasn't been another comment. If anyone has other thoughts, please add them here. Thanks!

**Comment by vsoch** [comment]
Yes this is good! At some future point if there is a global standard for image APIs (e.g., it's decided to adopt Docker) we will modify for that, but no issues as of now.
