### ISSUE TITLE
Singularity `--nv` option creates temporary file in current directory

### ISSUE THREAD

**Issue by oschulz** [apptainer/singularity#1062]
## Version of Singularity:

v2.4

### Desired behavior

Singularity option `--nv` should create it's temporary file "singularity-nvliblist.XXXXXXXX" in `$TMPDIR` instead of the current directory.

We should use

    SINGULARITY_NVLIBLIST=$(mktemp -t singularity-nvliblist.XXXXXXXX)

(or similar) instead of

    SINGULARITY_NVLIBLIST=$(mktemp singularity-nvliblist.XXXXXXXX)

in action_argparser.sh.

### Actual behavior

Singularity with `--nv` fails if the user doesn't have write permissions in the current directory:

    mktemp: failed to create file via template ‘singularity-nvliblist.XXXXXXXX’: Permission denied

### Steps to reproduce behavior

Run ```cd / && singularity shell --nv /some/container.sqsh```

**Comment by GodloveD** [comment]
Well that is definitely a bug.  Thank you.  I will look into it ASAP.

**Comment by oschulz** [comment]
Thanks, @GodloveD !

**Comment by GodloveD** [comment]
Hey @oschulz sorry for the delay.  Can you have a look at https://github.com/singularityware/singularity/pull/1069 and see if it fixes your issue when you get a chance?

**Comment by GodloveD** [comment]
OK.  That is merged into development now.  I'm going to close this, but feel free to re-open if you have any other problems.

**Comment by oschulz** [comment]
Thanks for fixing this!

I still think the unquoted `${TMPDIR:-/tmp}` is a bit dangerous, though. ;-)
