### ISSUE TITLE
Docker cleanup error (opened FD)

### ISSUE THREAD

**Issue by hra0031** [apptainer/singularity#1063]
## Version of Singularity: 2.4 on Centos 6.9

Any docker image can't be cleaned, because of the opened file descriptor:
```
Singularity centos-ssh:~> exit
exit
VERBOSE [U=4573,P=20377]   main()                                    Cleaning directory: /tmp/.singularity-runtime.RT2kXME2
DEBUG   [U=4573,P=20377]   s_rmdir()                                 Removing directory: /tmp/.singularity-runtime.RT2kXME2
WARNING [U=4573,P=20377]   writable()                                Failed changing permission of file: /tmp/.singularity-runtime.RT2kXME2/jdeathe/centos-ssh/home/hra0031
WARNING [U=4573,P=20377]   unlink()                                  Failed removing file: /tmp/.singularity-runtime.RT2kXME2/jdeathe/centos-ssh/sys
ERROR   [U=4573,P=20377]   main()                                    Could not remove directory /tmp/.singularity-runtime.RT2kXME2: Device or resource busy
ABORT   [U=4573,P=20377]   main()                                    Retval = 255
```

In `lsof` I can see, that main and cleanup process have opened runtime folder:
```
$ lsof
cleanupd  10147      hra0031    5r      REG              259,2        0       1163 /tmp/.singularity-cleanuptrigger.3esVcFhQ
cleanupd  10147      hra0031    7r      DIR              259,2     4096    4063235 /tmp/.singularity-runtime.UUkw33V7/jdeathe/centos-ssh
bash      30288      hra0031    7r      DIR              259,2     4096    4063235 /tmp/.singularity-runtime.UUkw33V7/jdeathe/centos-ssh
bash      30288      hra0031    8wW     REG              259,2        0       1163 /tmp/.singularity-cleanuptrigger.3esVcFhQ
```

The problem is in changes in 2.4 version. In file action.c on line 70 https://github.com/singularityware/singularity/blob/81bf030a28aa1afe517ea1a83145d6fefe9a1a59/src/action.c#L70 the file descriptor to image runtime directory is opened. Then on line 81 https://github.com/singularityware/singularity/blob/81bf030a28aa1afe517ea1a83145d6fefe9a1a59/src/action.c#L81 the file descriptor is copied to cleanup process but isn't closed so the runtime directory can't be deleted.
I've tried to add some code to close the file descriptor and the cleanup process is working OK.

Problem is, that the descriptor is only in image.fd variable and I'm not really sure how to pass this information to cleanup process. As a parameter? Through registry? I don't have a complex knowledge of the code and I can break something else, so I can't make a simple patch.

### Steps to reproduce behavior

Run any docker image.

**Comment by cclerget** [comment]
@hra0031 setting CLOEXEC flag is missing on image file descriptor, an oversight of image code refactoring.
Thank you for report !

**Comment by hra0031** [comment]
@cclerget Thank you for the quick response. I see the CLOEXEC flag first time, nice solution!

**Comment by dtrudg** [comment]
Closing this as PR #1064 was merged. Let us know if any further issues. Thanks!
