### ISSUE TITLE
Error with using "tee" and "apt-get update" in definition file 

### ISSUE THREAD

**Issue by nl384** [apptainer/singularity#107]
I am trying to install TensorFlow from source in a definition file. One of the programs necessary to do this is called Bazel, a program that is supposed to help build Tensorflow. Unfortunately Bazel has a very convoluted way of getting installed on Ubuntu (http://www.bazel.io/docs/install.html#install-on-ubuntu). It is necessary to add the Bazel distribution URI as a package source. The three steps in particular are:

```
$ echo "deb http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
$ curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
$ sudo apt-get update && sudo apt-get install bazel
```

Unfortunately this does not seem to work, as the error that is received is:
`E: Type '+' is not known on line 1 in source list /etc/apt/sources.list.d/bazel.list
`

I'm pretty sure this has to do with the fact that Bootstrap Singularity keywords seem to have this + that appears in front of them sometimes while bootstrapping is going on (e.g. `+ apt-get -y --force-yes install python-numpy`). While it seemed to me that the + was just a visual key for the user, it seemed that the program was actually interpreting the + in this case and trying to use it as part of the argument. Also my theory is that the + isn't actually present on line 1 because the code in terminal seems to suggest that the this that is written into tee is lacking a + (as you can see, the second line below lacks a +)

```
+ echo deb http://storage.googleapis.com/bazel-apt stable jdk1.8
deb http://storage.googleapis.com/bazel-apt stable jdk1.8
```

So perhaps the thing that is actually creating and reading the + is when "apt-get update" is called?

In the end I went around this problem by creating a shell script with these three steps, and then installing and running this script onto the container during bootstrapping. This seemed to work, perhaps because there were no errant +.

**Comment by gmkurtzer** [comment]
Hi Nathan,

Can you show me the definition file that you were using? I am assuming you
were using the RunCmd for that?

Thanks!

On Thu, Jun 30, 2016 at 1:13 PM, Nathan Lin notifications@github.com
wrote:

> I am trying to install TensorFlow from source in a definition file. One of
> the programs necessary to do this is called Bazel, a program that is
> supposed to help build Tensorflow. Unfortunately Bazel has a very
> convoluted way of getting installed on Ubuntu (
> http://www.bazel.io/docs/install.html#install-on-ubuntu). It is necessary
> to add the Bazel distribution URI as a package source. The three steps in
> particular are:
> 
> $ echo "deb http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
> $ curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
> $ sudo apt-get update && sudo apt-get install bazel
> 
> Unfortunately this does not seem to work, as the error that is received is:
> E: Type '+' is not known on line 1 in source list
> /etc/apt/sources.list.d/bazel.list
> 
> I'm pretty sure this has to do with the fact that Bootstrap Singularity
> keywords seem to have this + that appears in front of them sometimes while
> bootstrapping is going on (e.g. + apt-get -y --force-yes install
> python-numpy). While it seemed to me that the + was just a visual key for
> the user, it seemed that the program was actually interpreting the + in
> this case and trying to use it as part of the argument. Also my theory is
> that the + isn't actually present on line 1 because the code in terminal
> seems to suggest that the this that is written into tee is lacking a + (as
> you can see, the second line below lacks a +)
> - echo deb http://storage.googleapis.com/bazel-apt stable jdk1.8
>   deb http://storage.googleapis.com/bazel-apt stable jdk1.8
> 
> So perhaps the thing that is actually creating and reading the + is when
> "apt-get update" is called?
> 
> In the end I went around this problem by creating a shell script with
> these three steps, and then installing and running this script onto the
> container during bootstrapping. This seemed to work, perhaps because there
> were no errant +.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/gmkurtzer/singularity/issues/107, or mute the thread
> https://github.com/notifications/unsubscribe/ANVkxZsvbFiOseGShaWTXKOG3DYk9EREks5qRCNUgaJpZM4JCjEw
> .

## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by nl384** [comment]
Ok. Here is my definition file (I apologize beforehand for the bad style). And my "fix" is below. The relevant parts are separated out. 

```
DistType "debian"
MirrorURL "http://us.archive.ubuntu.com/ubuntu/"
OSVersion "trusty"

Setup
Bootstrap

InstallPkgs python
InstallPkgs python-numpy
InstallPkgs swig
InstallPkgs python-dev
InstallPkgs git
InstallPkgs curl
InstallPkgs apt-get
InstallPkgs vim
InstallPkgs wget
InstallPkgs software-properties-common
RunCmd add-apt-repository ppa:webupd8team/java
RunCmd apt-get update
RunCmd apt-get -y install oracle-java7-installer


RunCmd echo "deb http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
RunCmd curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | apt-key add -
RunCmd apt-get update
RunCmd sudo apt-get update && sudo apt-get install bazel


RunCmd sudo apt-get upgrade bazel

Cleanup
```

"fix":

```
DistType "debian"
MirrorURL "http://us.archive.ubuntu.com/ubuntu/"
OSVersion "trusty"

Setup
Bootstrap

InstallPkgs python
InstallPkgs python-numpy
InstallPkgs swig
InstallPkgs python-dev
InstallPkgs git
InstallPkgs curl
InstallPkgs apt-get
InstallPkgs vim
InstallPkgs wget
InstallPkgs software-properties-common
RunCmd add-apt-repository ppa:webupd8team/java
RunCmd apt-get update
RunCmd apt-get -y install oracle-java7-installer


InstallFile ./echocurl.sh
RunCmd sh echocurl.sh



RunCmd sudo apt-get upgrade bazel



Cleanup
```

echocurl.sh:

```
echo "deb http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | apt-key add -
apt-get update && sudo apt-get install bazel
```

**Comment by nl384** [comment]
Also here is more of the error:

```
E: Type '+' is not known on line 1 in source list /etc/apt/sources.list.d/bazel.list
E: The list of sources could not be read.
E: The package lists or status file could not be parsed or opened.
+ apt-get upgrade bazel
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
E: Unable to locate package bazel
ERROR: Aborting...
```

**Comment by nl384** [comment]
Also apologies for errant sudos, I actually have since discarded my previous version, so I'm trying to recreate the definition file and such 

EDIT:

Here is the sudo-less version (also I had an extra get-apt in the previous file):

```
DistType "debian"
MirrorURL "http://us.archive.ubuntu.com/ubuntu/"
OSVersion "trusty"

Setup
Bootstrap

InstallPkgs python
InstallPkgs python-numpy
InstallPkgs swig
InstallPkgs python-dev
InstallPkgs git
InstallPkgs curl
InstallPkgs apt-get
InstallPkgs vim
InstallPkgs wget
InstallPkgs software-properties-common
RunCmd add-apt-repository ppa:webupd8team/java
RunCmd apt-get update
RunCmd apt-get -y install oracle-java7-installer
RunCmd echo "deb http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
RunCmd curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | apt-key add -
RunCmd apt-get update && apt-get install bazel
RunCmd apt-get upgrade bazel

Cleanup
```

**Comment by nl384** [comment]
Also, it might be important that I had to disable the debian-archive-keyring requirement in the source code in order to get Ubuntu images to be built.

**Comment by gmkurtzer** [comment]
Hi Nathan,

If you update to the latest git master branch, I think I have some things
that will help ya.

First I fixed the debian-archive-keyring (I think), it won't be included by
default anymore.

Next, there is some trickyness with RunCmd and pipes... This is because the
definition file is actually based in shell. So RunCmd is actually a
function on the backend and when the definition file gets run, it executes
that function. That means that all arguments to the function are basically
the same as shell commands. So chances are 'tee' wrote a file
/etc/apt/sources.list.d/bazel.list on your host file system... Not in the
container!

Luckily there is a workaround, and it is very useful for people that have a
lot of RunCmd's as well:

RunCmd /bin/sh <<EOF
echo "deb http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee
/etc/apt/sources.list.d/bazel.list
curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | apt-key
add -
apt-get update && sudo apt-get install bazel
EOF

What that will do is run /bin/sh within the container, and then pipe into
it all of the data to the EOF. In shell terms this is called a Here
Document and it works exactly the same from a definition file.

I think that answers all of your questions, but if I missed something or if
you have any other questions, comments or thoughts let me know.

Thanks!

On Thu, Jun 30, 2016 at 2:13 PM, Nathan Lin notifications@github.com
wrote:

> Also, it might be important that I had to disable the
> debian-archive-keyring requirement in the source code in order to get
> Ubuntu images to be built.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/gmkurtzer/singularity/issues/107#issuecomment-229790723,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANVkxcovFOx0GXRfdsnb1mzgTfnSkQKKks5qRDGLgaJpZM4JCjEw
> .

## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720
