### ISSUE TITLE
Opensuse 42.3: WARNING: Could not create bind point file in container /etc/localtime: No such file or directory

### ISSUE THREAD

**Issue by wandadars** [apptainer/singularity#1074]
## Version of Singularity:

2.3.1

### Expected behavior

Run a Docker image converted to a Singularity image

### Actual behavior

singularity run locistream_stream_v206_opensuse423_stream_v206-2017-08-15-d02bd8f254d5.img 
WARNING: Could not create bind point file in container /etc/localtime: No such file or directory

**NOTE: The /etc/localtime path is symbolic both in the Docker image and on my machine(both are OpenSuse 42.3).

### Steps to reproduce behavior
My Dockerfile:
FROM opensuse:42.3

RUN zypper update -y &&   \
    zypper install -y     \
    sudo                  \
    vim                   \
    vim-data              \
    gcc-fortran           \
    infinipath-psm-devel  \
    openmpi               \
    openmpi-devel         \
    openmpi-libs          \
    hdf5-openmpi          \
    blas-devel            \
    blas-devel-static     \
    lapack-devel          \
    iproute2              \
    curl                  \
    tar                   \
    which

USER root
RUN echo "root:codeuser_2017" | chpasswd      && \
    groupadd -g 1000 codeuser                 && \
    useradd -u 1000 -m -s /bin/bash codeuser  && \
    passwd -d codeuser

RUN mkdir -p -m0755       \
    /opt/MyDir/lib         \

USER codeuser:codeuser

I ran:
docker build -t codebase/code_v203_opensuse423:code_v203

Then I ran:
docker run                                                          \
            -v /var/run/docker.sock:/var/run/docker.sock            \
            -v /home/user/source/temp/docker:/output    \
            --privileged -t --rm                                   \
            singularityware/docker2singularity                      \
            codebase/code_v203_opensuse423:code_v203

Then I ran:
singularity run   <generated.img>

### System Info

uname -r
4.4.79-19-default

lsb_release -a
LSB Version:	n/a
Distributor ID:	openSUSE project
Description:	openSUSE Leap 42.3
Release:	42.3
Codename:	n/a

**Comment by wandadars** [comment]
Seems that the Singularity container boots up when I used:

singularity exec -H /home2/MyUser/ locistream_stream_v206_opensuse423_stream_v206-2017-10-17-ea4f8c62ccf0.img /bin/bash

So the 'run' command doesn't drop me into the container. I noticed a similar behavior when running a Docker container on Linux.

**Comment by GodloveD** [comment]
Hey @wandadars! Nice to hear that you are trying Singularity.   

Did you try using the `shell` command instead of the `run` command?  The `shell` command should drop you into `/bin/bash` (or `/bin/sh` if bash doesn't exist).  The run command will execute the runscript.  That is CMD or ENTRYPOINT in Docker speak.  I don't see either of those things in you Docker file so I wonder if the Singularity container has a runscript.  

Can you check by executing this command?

```
singularity exec test cat /.singularity.d/runscript
```
If you are still having trouble are you able to push your Docker container to Docker Hub so that I can build it easily?

**Comment by c-ney** [comment]
I can easily reproduce this on Tumbleweed.

Edit: singularity version is `2.4.1-development.gf4210ff1`.

```
% singularity shell docker://opensuse:42.3
Docker image path: index.docker.io/library/opensuse:42.3
Cache folder set to /home/user/.singularity/docker
Creating container runtime...
WARNING: Could not create bind point file in container /etc/localtime: No such file or directory
Singularity: Invoking an interactive shell within container...
```

As @wandadars mentioned, `/etc/localtime` is a symbolic link on opensuse distributions that is provided by the `timezone` package. The container `docker://opensuse:42.3` does not include that package by default.

Building the container from a bootstrap file, explicitly installing the package, doesn't produce the warning.

```
Bootstrap: docker
From: opensuse:42.3

%post
    zypper ref
    zypper up -y
    zypper in -y timezone
```

**Comment by dtrudg** [comment]
I believe from my tests with OpenSUSE this is fixed on Singularity 3.x - please feel free to reopen if you have issues with the current version of Singularity. Thanks.
