### ISSUE TITLE
Singularity installed in non-standard location cannot start containers (no /bin/sh)

### ISSUE THREAD

**Issue by intentions** [apptainer/singularity#1088]
## Version of Singularity:

2.4

### Expected behavior

When compiling and installing singularity 2.4 in a nonstandard location (using ./configure --prefix=<new location>) it should produce a ./singularity executable that will run containers.

### Actual behavior

Containers run from the non-standard location fail with:
~> which singularity
/usr/local/singularity/singularity-2.4/bin/singularity

~> singularity shell imgs/intentions-Singularitytest-master.img 
ERROR  : No valid /bin/sh in container
ABORT  : Retval = 255

### Steps to reproduce behavior

Install in a non-standard location:

./configure --prefix=/usr/local/singularity/singularity-2.4
make
make install
/usr/local/singularity/singularity-2.4/bin/singularity shell imgs/intentions-Singularitytest-master.img
ERROR  : No valid /bin/sh in container
ABORT  : Retval = 255

Installing to a non-standard location works under 2.3.2

Problem exists on Centos 7.2

**Comment by intentions** [comment]
it was some stale information... a make clean cleared it

**Comment by GodloveD** [comment]
Great!  Thanks for letting us know.
