### ISSUE TITLE
Support Singularity on Mac?

### ISSUE THREAD

**Issue by gmkurtzer** [apptainer/singularity#109]
Is this possible?

https://github.com/mist64/xhyve

**Comment by nl384** [comment]
Are you still interested in this? I got xhyve working on my mac, and singularity seems to work fine on it too.

**Comment by aculich** [comment]
@nl384 +1

**Comment by gmkurtzer** [comment]
Whaaaaahhhhh? Ok, yes. Very interested! Do you have an idea on how to incorporate Xhyve directly into Singularity?

**Comment by nl384** [comment]
Well I ran an Ubuntu image on my mac using Xhyve by following the instructions I found here : http://www.pagetable.com/?p=831 . And then I installed Singularity. I was able to create, bootstrap and shell into an Ubuntu image, so it seems to work fine. However, I'm still not very familiar with Xhyve and not exactly sure on how it would be directly incorporated.

**Comment by gmkurtzer** [comment]
@nl384 We should circle back on this when you have time and see if we can spin out a SingularityWare project based on Xhyve and native Mac support.

**Comment by fmorency** [comment]
+1!! Would love to see Singularity on xhyve for macOS and BSD.

**Comment by EricEisaman** [comment]
Will Singularity Desktop for MacOS require root access for users running Docker containers after the desktop application has already been installed on the system?  If so, I would love to use Singularity Desktop with students on school issued laptops.

**Comment by jmstover** [comment]
@EricEisaman ... No it will not require root access. The initial root requirement is currently because we're installing to /usr/local, and the `singularity.conf` file needs to be root owned (that core check isn't modified).

**Comment by EricEisaman** [comment]
@jmstover Thank you.
