### ISSUE TITLE
Missing lists of runtime and build-time dependencies

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#1090]
## Version of Singularity:

Any.

I just learnt from the mailing list that `squashfs-tools' is an explicit runtime requirement of Singularity 2.4. 
Checking around, I found several issues: 
- The Debian packaging has not been adapted in-tree. Only RPM got a fix: https://github.com/singularityware/singularity/commit/78af5f54b814466fe88d362688b78e016ba4c618#diff-b3fb1fb02c192e0be6fee00045236e40
- The release notes do not mention this new requirement. 

As a consequence, packaging in downstream distributions is broken. 
For example, Gentoo (which is already shipping 2.4 as of now) did not take this new dependency into account. 
That's totally expected: How should downstream maintainers, or users, know about this? 

This issue strongly interplays with https://github.com/singularityware/singularity/issues/1051 .

**Comment by olifre** [comment]
Here's the downstream Gentoo bug caused by this issue:
https://bugs.gentoo.org/635342

**Comment by olifre** [comment]
@dexter2cz Also the downstream official Debian package is broken in this regard:
https://packages.debian.org/experimental/singularity-container
Since I am not familiar with Debian bug reporting, it might be best if somebody else took care of that...

**Comment by dtrudg** [comment]
Closing this as a PR was merged as a fix. Please don't hesitate to reopen if there is any outstanding issue.
