### ISSUE TITLE
Singularity attempts to create `overlay_final` directory even if unused

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#1096]
Code snippet:
```
int _singularity_runtime_overlayfs(void) {

    singularity_priv_escalate();
    singularity_message(DEBUG, "Creating overlay_final directory: %s\n", CONTAINER_FINALDIR);
    if ( s_mkpath(CONTAINER_FINALDIR, 0755) < 0 ) {
        singularity_message(ERROR, "Failed creating overlay_final directory %s: %s\n", CONTAINER_FINALDIR, strerror(errno));
        ABORT(255);
    }
    singularity_priv_drop();

    singularity_message(DEBUG, "Checking if overlayfs should be used\n");
```
This has been introduced here:
https://github.com/singularityware/singularity/commit/b8638584c71e6a86971eb3c89f5b8a22a9f3d97a#diff-3f429c558d4b747e60377055ebbbd7d7R50
=> pinging @gmkurtzer 

So in short, it may attempted to create a directory, requiring priviileges, even if it will never be used (since it's done before the "should overlayfs be used?"-test). 

This is observed in the wild as a consequence of the issue adressed by: 
https://github.com/singularityware/singularity/pull/1093
Otherwise, this bug would be hidden...

**Comment by jscook2345** [comment]
@GodloveD 

It looks like maybe a fix for this was merged and this issue not closed. Can you take a look?

**Comment by GodloveD** [comment]
That's what it looks like to me.
