### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by bneron** [apptainer/singularity#1097]
## Version of Singularity:

Write here.

When the section %test is name %test**s** by mistake. 
The error message is not really helpful:

`/bin/sh: 0: Can't open s`

### Expected behavior

invalid section 'tests'

### Actual behavior

```sudo singularity build foo.img Singularity
    Using container recipe deffile: Singularity
    Sanitizing environment
    Adding base Singularity environment to container
    Docker image path: index.docker.io/library/ubuntu:zesty
    Cache folder set to /root/.singularity/docker
    Exploding layer: sha256:8b23367590c32dbb6954ab3cc9b6c451b9763556c72a893538efe88583f6a5dc.tar.gz
    Exploding layer: sha256:c7feb578947e4b86e0a0cff64b42489dc1305bbacdb3ed36d0afe95a19ebf845.tar.gz
    Exploding layer: sha256:ac836f06379c8d7356e0d2e7dbb3e9f3924616527fa51b95545fb455eec31f08.tar.gz
    Exploding layer: sha256:be286dc472df31f16953d34151f836d0186fddeea6cd56dcefd2a6d46a992500.tar.gz
    Exploding layer: sha256:5533df5f353d9fbcbd081e9dd653fe7d8ddebed958d1f0e56fa4a87b216f13c1.tar.gz
    Exploding layer: sha256:f6be9f4f6905406c1e7fd6031ee3104d25ad6a31d10d5e9192e7abf7a21e519a.tar.gz
    User defined %runscript found! Taking priority.
    Running post scriptlet
    Adding deffile section labels to container
    Adding runscript
    Adding runscript help
    Running test scriptlet
    /bin/sh: 0: Can't open s
    ABORT: Aborting with RETVAL=255
    Cleaning up...
```

### Steps to reproduce behavior

sudo singularity build foo.img Singularity.txt

[Singularity.txt](https://github.com/singularityware/singularity/files/1418598/Singularity.txt)

**Comment by vsoch** [comment]
thanks @bneron ! This is also a larger function of having some kind of linter / parser to assure correctness of build recipes. For some sections (if incorrect) they might be completely ignored. Test (since it is included with the `%tests` that you specified) happened to spit out a non informative error. It would have been useful to @bneron from the getgo to know that the section was incorrectly specified (and not have to wait for the whole build). Thoughts?

**Comment by vsoch** [comment]
@bneron I'll give a go at this - but I'm going to try for a more robust "linter" for the recipes before we build anything. That way, you would get a warning before it fails at the end.

**Comment by jscook2345** [comment]
@bneron @vsoch It appears in 3.0 that '%tests' is now silently ignored. I'm not sure that is a great behavior (I will open another bug) but the problematic error message no longer exists, so I'm going to close this up.
