### ISSUE TITLE
Singularity ignores http_proxy environment variable

### ISSUE THREAD

**Issue by angelbejarano** [apptainer/singularity#1098]
## Version of Singularity:
2.3.2 and 2.4
### Expected behavior
Yum and Debootstrap should make use of the http_proxy environment variable

### Actual behavior
Yum and Debootstrap ignore proxy settings

### Steps to reproduce behavior
Set a system-wide http_proxy environment variable (i.e. in /etc/environment )

Try to bootstrap a container with `sudo singularity bootstrap image.img definition.def`

It won't use the proxy setting for Yum or Debootstrap (others not tested)

**Comment by vsoch** [comment]
hey @angelbejarano have you tested adding this to `%environment`, possibly `%setup`,  or at runtime by exporting  `SINGULARITY_HTTP_PROXY` for the value you want?

**Comment by angelbejarano** [comment]
hi @vsoch all fo the options are ignored

**Comment by vsoch** [comment]
ah ok, was worth a shot! I'll have others ping in on this one because I'm not super privy to debootstrap or yum builds. I've only seen they have the most issues, haha. If all else fails, could you bootstrap a Docker version of the OS?

**Comment by angelbejarano** [comment]
well, dockerized bootstrap also doesn't work with any proxy settings :(

**Comment by DirkdeDraak** [comment]
It would be great if a proxy could be added to the conf file (or something similar).
In our corporate environment linux systems - by default - have no proxies set to access the internet. They can be set. Though while Singularity also requires sudo - and that user does not have it set either - it would be much appreciated if Singularity would have a setting of it's own so it can go out and fetch files from the internet.

For now I've patched 4x files and added proxy settings:
* bootstrap-scripts/functions
* bootstrap-scripts/deffile-driver-yum.sh
* python/base.py
* functions
Not sure if it really is required or that I doubled something, but it seems to work (for me at least).

**Comment by vsoch** [comment]
hey @DirkdeDraak do you want to share the revisions, and I can look into a PR? or just open one up for discussion?

**Comment by dtrudg** [comment]
Hi - I reported this sometime before. See also https://github.com/singularityware/singularity/issues/764

**Comment by gmkurtzer** [comment]
@DirkdeDraak Sorry if I missed it, do you have a PR submitted?

@angelbejarano, can you test with the 'development' branch please?

**Comment by angelbejarano** [comment]
@gmkurtzer it works! I've found a collateral effect on the development branch regarding my definition files. If there's a blank line between header and sections, **singularity build** will complain:

```
Building into existing container: img2.img
Using container recipe deffile: debian.def
Sanitizing environment
ERROR  : Duplicate bootstrap definition key found: ''
ABORT  : Retval = 255
Cleaning up...

```

Attached is the definition file that triggered that error.

Regards
[debian.def.txt](https://github.com/singularityware/singularity/files/1445959/debian.def.txt)

**Comment by angelbejarano** [comment]
@gmkurtzer sorry to say that bootstrapping from docker still downloads ignoring http_proxy setting

**Comment by vsoch** [comment]
hey @angelbejarano and @DirkdeDraak we would like to get this into 2.4.1 - could you submit a PR for the work that you did to get this up and running? Thanks!

**Comment by dtrudg** [comment]
Closing this as PR#1151 addressing this was merged. Let us know if any other issues. Thanks.
