### ISSUE TITLE
Duplicate bootstrap definition key found: '#UpdateURL'

### ISSUE THREAD

**Issue by DirkdeDraak** [apptainer/singularity#1103]
## Version of Singularity:

2.4

### Expected behavior

Line starts with a '#', so I would think it should be seen as a comment.

### Actual behavior

It shows this error:
Duplicate bootstrap definition key found: '#UpdateURL'

### Steps to reproduce behavior

Have a definition file with 2x #UpdateURL: lines
```
BootStrap: yum
OSVersion: 7
#MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
MirrorURL: http://mirror.centos.org/centos-7/7.4.1708/os/x86_64/
Include: yum

#UpdateURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/updates/$basearch/
#UpdateURL: http://mirror.centos.org/centos-7/7.4.1708/updates/x86_64/
```
Having one commented out and the other not, it works fine.
Having both uncommented also gives the 'duplicate key found' error, which is correct.

**Comment by ilmagico** [comment]
This one looks easy enough, I'll take a look at it.
