### ISSUE TITLE
issue installing singularity 2.4 on mac using vagrant

### ISSUE THREAD

**Issue by cokelaer** [apptainer/singularity#1104]
## Version of Singularity:

2.4

### Expected behavior

installation on version 2.4 via vagrant with success 

### Actual behavior

requested url not found

reason: version 2.4 may not be available ?

### Steps to reproduce behavior

![vagran_max_2_4](https://user-images.githubusercontent.com/778821/32108494-26d5a1fe-bb32-11e7-83d1-85ef6079591d.png)

This is for a colleague of mine on a mac. Version 2.3.1 was installed with success but 2.4 does not seem to work ? thanks for any help

**Comment by vsoch** [comment]
This is unfortunately expected, because afaik @alaindomissy hasn't had the chance to create the Vagrant box for 2.4. @alaindomissy any updates on this?

**Comment by alaindomissy** [comment]
I uploaded a singularity-2.4 vagrant box ( as well as a 2.3.2) here: https://app.vagrantup.com/singularityware
I made a PR for updating the mac and the windows installation doc here: 
https://github.com/singularityware/singularityware.github.io/pull/145

**Comment by vsoch** [comment]
Thanks @alaindomissy ! @cokelaer would you like to test and if it looks good we can close the issue?

**Comment by cokelaer** [comment]
Brilliant. We ll have a go  tomorrow and let you know the outcome

**Comment by vsoch** [comment]
thanks @cokelaer, enjoy your Sunday!

**Comment by cokelaer** [comment]
@vsoch @alaindomissy FYI and book keeping, I naively followed the instructions to install the version 2.4
but I had installed a previous VM (singularity 2.3). Without reading carefully all the messages, I entered in the VM using vagrant ssh and singularity version was still 2.3 ; I realised that I had to either create a new directory or "destroy" the previous VM. On your documentation page, this may be useful to add this information: "if you had installed a previous vm , create a new directory e.g. singularity-vm-2.4 or destroy the previous VM using ..."

After deleting the previous VM I could successfully pull the container and use it. Thank a lot. You can close this issue.

**Comment by vsoch** [comment]
okay just added the note about destroying, thanks @alaindomissy and @cokelaer and closing issue!

**Comment by alaindomissy** [comment]
I had come across the same problem, At some point I Think I had suggested this change to the instructions:
'''
mkdir` singularity-2.4
cd singularity-2.4
'''
instead of this:
'''
mkdir singularity-vm
cd singularity-vm
'''
Would this help being a little more clear and explicit ?
Thanks

**Comment by vsoch** [comment]
@alaindomissy I added a note about destroy vs. creating a new folder, so we are good! Thanks!
