### ISSUE TITLE
Project needs a proper change log

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#1107]
Every PR is required to add to the change log, given any significant change in function or user interface. Second, PRs that have changed, updated, or new features are required to write a documentation snippet, either included with the PR or as an approved PR to the docs 3.0 branch. When the release time comes, most of the documentation should essentially be done and a more (well written) release notes written from it.

**Comment by olifre** [comment]
Very much entangled with this is the `debian/changelog`, which needs to be updated at release time. Easiest is to use the same well-written release notes text there. I've added #1112 in this regard to prevent #1057 from happening again ;-).

**Comment by gmkurtzer** [comment]
I think this is an excellent idea! @GodloveD briefed me earlier, apologies I've been so overwhelmed I've missed some conversations, but great thinking everyone! Thanks!

**Comment by vsoch** [comment]
woohoo! Long live [CHANGELOG.md](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md)

**Comment by vsoch** [comment]
Thanks again everyone! Forgot to close this.
