### ISSUE TITLE
MPI_Init() hangs with --contain

### ISSUE THREAD

**Issue by kenneth59715** [apptainer/singularity#1110]
## Version of Singularity:

2.3.2

### Expected behavior

mpirun -ppn 8 singularity exec --contain -H /home/user /home/user/hello
should execute MPI_Init() and run parallel.

(if --contain is omitted, no hang, MPI_Init() succeeds, parallel run proceeds.)

### Actual behavior

hello hangs in MPI_Init()

### Steps to reproduce behavior

create hello.c:
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <mpi.h>
int main(int argc, char **argv) {
    int numprocs, my_id;

    printf("before MPI_Init\n");
    MPI_Init(&argc, &argv);
    printf("after MPI_Init\n");
    MPI_Comm_size(MPI_COMM_WORLD, &numprocs);
    printf("after MPI_Comm_size\n");
    MPI_Comm_rank(MPI_COMM_WORLD, &my_id);
    printf("after MPI_Comm_rank\n");
    printf("I amd %d of %d\n", my_id, numprocs);
    if (my_id == 0){
        printf("%d: MPI_Comm_size (%d)\n", my_id, numprocs);
    }
    MPI_Finalize();
    exit(0);
}

mpicc -o hello hello.c

mpirun -ppn 8 singularity exec --contain -H /home/user /home/user/hello

mpirun -ppn 8 singularity exec -H /home/user /home/user/hello

Kenneth

**Comment by dtrudg** [comment]
Hi @kenneth59715 - are you able to confirm if you see this behaviour with the current version of Singularity? Thanks!

**Comment by dtrudg** [comment]
Closing this issue as it is against deprecated 2.3.x and no report on current version. Please don't hesitate to reopen / open a new issue if you experience this on current Singularity.
