### ISSUE TITLE
Additional tests for consideration

### ISSUE THREAD

**Issue by justbennet** [apptainer/singularity#1111]
## Version of Singularity: post 2.4 development

I encountered several times errors because a) curl was not installed (seems not to be default in some Ubuntus), b) the install path was not in the sudo secure path, and c) I chose a path on a volume mounted with 'nosuid' option.

### Expected behavior

Those are, I think, fairly easy to detect early in the game.

I'll try to gin up some tests and put them into a PR.

### Actual behavior

Errors occur at various places.

### Steps to reproduce behavior

Uninstall curl; install to partition with 'nosuid' mount option; run `make test`

**Comment by dtrudg** [comment]
These installation issues should be addressed in 3.x to my knowledege. If they aren't we'd be happy to look at an issue against the current 3.x supported release.
