### ISSUE TITLE
Permission error when creating Singularity image based on a Docker image that needs root access. (like apt-get install....)

### ISSUE THREAD

**Issue by titansmc** [apptainer/singularity#1117]
## Version of Singularity:

2.4-master builded from Git

### Expected behavior

Build docker image

### Actual behavior

andres@5441c0017ac8:~$ sudo singularity build ubuntu docker://imimsri/cloud9
Docker image path: index.docker.io/imimsri/cloud9:latest
Cache folder set to /root/.singularity/docker
[36/36] |===================================| 100.0% 
Importing: base Singularity environment
Importing: /root/.singularity/docker/sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913.tar.gz
Importing: /root/.singularity/docker/sha256:5ad56d5fc14905886c560200ab69f905b5c5287eaf12f8f761a7ab54f7a61c1b.tar.gz
Importing: /root/.singularity/docker/sha256:170e558760e8b2e484a022b7d7272cf284fc4e1936ba7a0a671fc586440ad272.tar.gz
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-en: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_i18n_Translation-en: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_InRelease: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_main_i18n_Translation-en: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_restricted_i18n_Translation-en: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.lock: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.partial: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_InRelease: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_main_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_main_i18n_Translation-en: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_restricted_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_restricted_i18n_Translation-en: Cannot open: Operation not permitted
tar: Exiting with failure status due to previous errors
Cleaning up...

### Steps to reproduce behavior

 sudo singularity build ubuntu docker://imimsri/cloud9

or

 singularity build ubuntu docker://imimsri/cloud9

**Comment by GodloveD** [comment]
Hi @titansmc!  Thanks for the issue.  I think this is the same error as #1060 and is resolved by https://github.com/singularityware/singularity/pull/1061.  Can you confirm please?

**Comment by titansmc** [comment]
Hi @GodloveD , thanks a lot, just compiled the development branch and, so far so good. Do you have any idea on when this change could be merged on the master branch?

Thanks.

**Comment by GodloveD** [comment]
I don't know for sure @titansmc, but we are planning on releasing a 2.4.1 version with some bug fixes.  I'll make sure this makes it in.
