### ISSUE TITLE
undefined FROM in functions

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#1118]
We have our first users using an "shub" bootstrap and the builds end with the following error:

```
Finalizing Singularity container
Calculating final size for metadata...
/usr/local/libexec/singularity/functions: line 356: FROM: unbound variable
Cleaning up...
```

It comes down to exactly that, `FROM` is not defined here:

```
cat /usr/local/libexec/singularity/functions | grep FROM
        message 1 "The environment of ${SINGULARITY_IMAGE} may differ from the environment of ${FROM}\n"
        message 1 "${FROM} sha1 sum of environment is ${SINGULARITY_STARTING_ENVSHA1}\n"
        message 1 "Variables unique to original image (${FROM})\n"
```

see here https://github.com/singularityhub/singularityhub.github.io/issues/81#issuecomment-340440361

@GodloveD I think you worked on these lines - how is it intended to work (when where is FROM defined?) This one would be good to get a quick fix because nobody can build with shub base. Let's ping @cclerget on this one too so he can update the secure build image, and then I'll update the builders. Thanks all!

**Comment by GodloveD** [comment]
@vsoch `FROM` should be defined in `src/builddef.c`.    Sounds like there is no `FROM` keyword in the recipe?  How can I reproduce?

**Comment by jekriske** [comment]
I have an example 
https://www.singularity-hub.org/containers/615/log
From is defined https://github.com/jekriske/rstudio/blob/master/Singularity#L2
Works locally for me 2.4-master.g3e338d7

**Comment by GodloveD** [comment]
Hi @jekriske!  Thanks for the info.

Do I understand you correctly that this works when you issue the build command on a local machine, but then fails when you try to build it on shub?  

@vsoch is shub doing anything that would cause it to lose env vars?

**Comment by jekriske** [comment]
@GodloveD yes, that's correct.

**Comment by vsoch** [comment]
@GodloveD it's a secure build with @cclerget secure build branch - I just brought up a builder (with that version installed) and confirmed the error reproduces, there is no `FROM` If you want to reproduce, then install the branch:

```
# Install Singularity from Github
cd /tmp && git clone -b feature-squashbuild-secbuild https://github.com/cclerget/singularity.git &&
cd /tmp/singularity && ./autogen.sh && ./configure --prefix=/usr/local && make && sudo make install && sudo make secbuildimg
```
Thank you!

**Comment by GodloveD** [comment]
OK. Thanks for the info and sorry for the delay.  I'm able to replicate the error now so I'll look into it and get back asap.

**Comment by cclerget** [comment]
@vsoch @GodloveD For security reasons, I removed in builddef.c possibility to turn every definition file keywords into direct upper environment variable name, so From keyword doesn't set FROM environment variable but SINGULARITY_DEFFILE_FROM. Fixed in commit https://github.com/cclerget/singularity/commit/852115fce816c32b14c9dbcea2f96b9265a095fe

**Comment by GodloveD** [comment]
I had just determined that `SINGULARITY_DEFFILE_FROM ` was the answer and I was about to send you a PR.  Thanks very much for fixing it @cclerget !  😺

**Comment by GodloveD** [comment]
So, this actually isn't a problem with either master or development and as far as I can tell it is now fixed in @cclerget 's branch.  Right?  So I'll close this and we can reopen if necessary (or if we want to take a trip down memory lane).  lol

**Comment by vsoch** [comment]
Thanks for the help guys! @jekriske I should be able to update the builder sometime this week.

**Comment by vsoch** [comment]
@jekriske I think we are expecting a security release sooner than later, so I'm going to hold off updating the builder until then. In the meantime, don't use the SHUB bootstrap, or as a workaround, add those environment variables (`SINGULARITY_DEFFILE_FROM`) to your `%post`.
