### ISSUE TITLE
singularity inside docker (CentOS) inside virtualbox (Ubuntu) freezes VM

### ISSUE THREAD

**Issue by ilmagico** [apptainer/singularity#1119]
I created a vagrant VM (virtualbox backend) using the ubuntu/xenial64 box, git clone singularity inside, then run the travis script as
```
sudo OS_TYPE=centos OS_VERSION=7 .travis/script
```
in an effort of running and debugging the tests on CentOS. Host system is Linux (Manjaro).

## Version of Singularity:

development branch.

### Expected behavior

The script runs and completes, successfully or not.

### Actual behavior

The whole virtual machine hangs as soon as the test
```
+ singularity exec /tmp/stest.5V2pG9/container true
```
is executed (part of `20-build.sh`)

I noticed that the travis script starts a privileged CentOS docker container to run the tests in, and the tests freeze as soon as singularity is used inside docker to start its own test container.

Because of this, I have no way of running the tests on CentOS.

### Steps to reproduce behavior

1. Create a ubuntu/xenial64 vagrant box
2. `vagrant up && vagrant ssh`
3. Clone singularity from git, development branch
4. `sudo OS_TYPE=centos OS_VERSION=7 .travis/script`

**Comment by vsoch** [comment]
hey @ilmagico, I think the tests are using Docker - the [centos_run](https://github.com/singularityware/singularity/blob/master/.travis/centos_run) script runs not only a docker container, but in privileged, which always (at least on my computer) causes things to go wonky. Do you have another environment where you could test? I've never tried in a VM or docker locally but I could give it a go if you are not able to move forward without tests. A good place to start might be mimicking the configuration that Travis has set up. I do know that the tests for centos 6 aren't active, but afaik the centos 7 should be.

**Comment by ilmagico** [comment]
@vsoch The tests are not using docker -- not yet at least. I added a test that runs docker in my PR and it's failing on CentOS ... but I cannot debug it. The tests are running singularity though, which is kinda like docker, and that's why it needs the --privileged flag, I believe. Edit: `make tests` does not run docker (yet) but centos_run definitely does, with --privileged like you say, and I'm sure that's part of the problem!
I haven't tried to run this on my native system, but I'm afraid it might freeze my whole physical machine.

**Comment by vsoch** [comment]
I'm confused - the script `.travis/script` calls `.travis/centos_run` which has many lines to run docker. Could you share what you are doing then?

And yes - I've had docker freeze my entire machine and it's the worst!

**Comment by cclerget** [comment]
@ilmagico @vsoch It appears AUFS used as default storage driver with docker cause kernel panic (docker don't recommend it), change storage driver to overlay doesn't freeze anymore : https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

**Comment by vsoch** [comment]
ah this is very good to know, it's happened to me several times. Thanks @cclerget. @ilmagico this might help get the tests working!

**Comment by DrDaveD** [comment]
@ilmagico The configuration of the host system is very significant, especially the kernel and its configuration, because that is shared by all containers.  You said it was "Linux (Manjaro)" but that's not very definitive.  What's the kernel version, and is docker using overlay?

When you run vagrant and then .travis/script, you're running singularity inside of docker inside of vagrant on your host.  That's one more level of containers than is done in Travis, which runs on a recent version of Ubuntu as the base OS.   I don't know how things might break down in that scenario.

**Comment by ilmagico** [comment]
@cclerget Than you so much for the suggestion, I'll try it ASAP, fingers crossed! 

@vsoch Yes, `.travis/centos_run` calls docker to start a CentOS container, which then builds singularity and calls `make test`. It's inside this container that singularity freezes, and it's also inside this container that I added a test that calls docker, so it's almost a "docker-in-docker", except it isn't, because I export the `/var/run/docker.sock` from the "host" (the ubuntu VM host in my case) so that the container connects to the docker daemon outside, as explained [here](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/).

@DrDaveD Look at my "steps to reproduce" above: there are two "hosts". One is my Manjaro linux running on bare metal, then there's the vagrant Ubuntu VM (kernel 4.4.0), and inside this VM I run `.travis/script`. The kernel that matters here is the one in the Ubuntu VM, that's where docker runs and where the CentOS container is started, while my bare metal host's kernel is not shared by anyone (if it still matters, it's 4.9.52). I mentioned my bare metal host just in case it was playing a role, but it probably doesn't matter.

Yes, I can understand how running software in so many virtualization and containerization layers can be pretty confusing ...

**Comment by ilmagico** [comment]
YES! Thank you @cclerget again! Now the system doesn't freeze anymore. Of course my test fails, but now I can debug it.

**Comment by vsoch** [comment]
woohoo! I can attest that @cclerget is amazing.

**Comment by DrDaveD** [comment]
@ilmagico  sorry, I forgot that vagrant started a VM instead of a container.  You're right, then the bare metal probably doesn't matter.
