### ISSUE TITLE
singularity pull image error

### ISSUE THREAD

**Issue by yangyang-zhang** [apptainer/singularity#1126]
## Version of Singularity:

[root@c031 yangyang]# singularity --version
2.3.2-dist

### Actual behavior

[root@c031 yangyang]# singularity  pull docker://bvlc/caffe:intel
Initializing Singularity image subsystem
Opening image file: caffe-intel.img
Creating 2939MiB image
Binding image to loop
Creating file system within image
Image is done: caffe-intel.img
Docker image path: index.docker.io/bvlc/caffe:intel
Cache folder set to /root/.singularity/docker
Importing: base Singularity environment
Importing: /root/.singularity/docker/sha256:866e3aeb7838123ac5d5f60bdbffd875cd123d6acbda34820b5eb52298177439.tar.gz
Importing: /root/.singularity/docker/sha256:b405bcbeb382939cd4c5a46d8f68c4abb88f36169ef11a9718e8d546a35afcef.tar.gz
Importing: /root/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Importing: /root/.singularity/docker/sha256:42cdeb47426e141aa4e90c69412d75331ef2549f48cdd884e7d1f5fa8c6dbb82.tar.gz
Importing: /root/.singularity/docker/sha256:cccf302e5bc1c04f4b1df2baba24712c2305cc172bae8454a5fe0fc09e21b0f3.tar.gz
Importing: /root/.singularity/docker/sha256:65642200ad9a711fe27d4e0ced2f7e670764df84efbe09ff31aca92d86282dd2.tar.gz
Importing: /root/.singularity/docker/sha256:b0de1abb17d6e07bcf1b68dc5c75acf0386405905ed735efe65a5235f29e756d.tar.gz
Importing: /root/.singularity/docker/sha256:8d43e5f5d27feb983909350fa3a008ebfb66436e172337cd543db358f5a01f1c.tar.gz
Importing: /root/.singularity/docker/sha256:da4e69f33106a3131ce07d9ed4403593a7698be6dabd6cabd2c9c228599c8ce0.tar.gz
Importing: /root/.singularity/docker/sha256:29ede3c02ff200fff7454ce59e1c3bb62f538847cefd5b8541e088ad22c42879.tar.gz
Importing: /root/.singularity/docker/sha256:bae382666908fd87a3a3646d7eb7176fa42226027d3256cac38ee0b79bdb0491.tar.gz
Importing: /root/.singularity/metadata/sha256:fad90e2952a3fba3fd30679b6628d61b6f68eb38e4320b9b478b041b51315d8a.tar.gz
Done. Container is at: caffe-intel.img
[root@c031 yangyang]# ls
caffe-intel.img
[root@c031 yangyang]# singularity shell -w caffe-intel.img 
ERROR  : No valid /bin/sh in container
ABORT  : Retval = 255

I don't know why, please give help

**Comment by jekriske** [comment]
Works for me in 2.3.2 and 2.4. However, my docker layers are different than yours, a testament to  how pulling from Docker does not produce repeatable results. Perhaps try again, or give 2.4 a try. 
2.3.2:
```
root@vagrant:~# singularity --version
2.3.2-dist
root@vagrant:~# singularity pull docker://bvlc/caffe:intel
Initializing Singularity image subsystem
Opening image file: caffe-intel.img
Creating 3014MiB image
Binding image to loop
Creating file system within image
Image is done: caffe-intel.img
Docker image path: index.docker.io/bvlc/caffe:intel
Cache folder set to /root/.singularity/docker
Importing: base Singularity environment
Importing: /root/.singularity/docker/sha256:7394848ce2610f92ed106d2d00ad6e89768916d8d866f393948e229c0f75a3be.tar.gz
Importing: /root/.singularity/docker/sha256:cce433c251eabd2568d09b30222e4db8ba8e17e5ceb831dae2cadcfc263de0b9.tar.gz
Importing: /root/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Importing: /root/.singularity/docker/sha256:645147aa4a2c0060d950c94b3d999792d0bad712fbcac0e76b90edd125d1b366.tar.gz
Importing: /root/.singularity/docker/sha256:db51d5a6e846aacdb4d97e0cf6721b286bc8875109c0d386400d18af19dc9a76.tar.gz
Importing: /root/.singularity/docker/sha256:f7bb5efaed5a1ff67d071262317c210643a07534b1ec2e2e1c55d629abd3ee5c.tar.gz
Importing: /root/.singularity/docker/sha256:b0de1abb17d6e07bcf1b68dc5c75acf0386405905ed735efe65a5235f29e756d.tar.gz
Importing: /root/.singularity/docker/sha256:8d43e5f5d27feb983909350fa3a008ebfb66436e172337cd543db358f5a01f1c.tar.gz
Importing: /root/.singularity/docker/sha256:da4e69f33106a3131ce07d9ed4403593a7698be6dabd6cabd2c9c228599c8ce0.tar.gz
Importing: /root/.singularity/docker/sha256:29ede3c02ff200fff7454ce59e1c3bb62f538847cefd5b8541e088ad22c42879.tar.gz
Importing: /root/.singularity/docker/sha256:bae382666908fd87a3a3646d7eb7176fa42226027d3256cac38ee0b79bdb0491.tar.gz
Importing: /root/.singularity/metadata/sha256:fad90e2952a3fba3fd30679b6628d61b6f68eb38e4320b9b478b041b51315d8a.tar.gz
Done. Container is at: caffe-intel.img
root@vagrant:~# singularity shell -w caffe-intel.img
Singularity: Invoking an interactive shell within container...

Singularity caffe-intel.img:~>
```
2.4 using build and the sandbox option
```
vagrant@vagrant:~/singularity$ singularity --version
2.4-development.gf1481c2
vagrant@vagrant:~/singularity$ sudo singularity build -s caffe-intel docker://bvlc/caffe:intel
Docker image path: index.docker.io/bvlc/caffe:intel
Cache folder set to /root/.singularity/docker
Importing: base Singularity environment
Importing: /root/.singularity/docker/sha256:bae382666908fd87a3a3646d7eb7176fa42226027d3256cac38ee0b79bdb0491.tar.gz
Importing: /root/.singularity/docker/sha256:29ede3c02ff200fff7454ce59e1c3bb62f538847cefd5b8541e088ad22c42879.tar.gz
Importing: /root/.singularity/docker/sha256:da4e69f33106a3131ce07d9ed4403593a7698be6dabd6cabd2c9c228599c8ce0.tar.gz
Importing: /root/.singularity/docker/sha256:8d43e5f5d27feb983909350fa3a008ebfb66436e172337cd543db358f5a01f1c.tar.gz
Importing: /root/.singularity/docker/sha256:b0de1abb17d6e07bcf1b68dc5c75acf0386405905ed735efe65a5235f29e756d.tar.gz
Importing: /root/.singularity/docker/sha256:f7bb5efaed5a1ff67d071262317c210643a07534b1ec2e2e1c55d629abd3ee5c.tar.gz
Importing: /root/.singularity/docker/sha256:db51d5a6e846aacdb4d97e0cf6721b286bc8875109c0d386400d18af19dc9a76.tar.gz
Importing: /root/.singularity/docker/sha256:645147aa4a2c0060d950c94b3d999792d0bad712fbcac0e76b90edd125d1b366.tar.gz
Importing: /root/.singularity/docker/sha256:cce433c251eabd2568d09b30222e4db8ba8e17e5ceb831dae2cadcfc263de0b9.tar.gz
Importing: /root/.singularity/docker/sha256:7394848ce2610f92ed106d2d00ad6e89768916d8d866f393948e229c0f75a3be.tar.gz
Importing: /root/.singularity/metadata/sha256:4db78399d2ecbd6d4383c9c5c43bcd9ebd6b68f5bdcdf16812a9d31c518c2c0a.tar.gz
Singularity container built: caffe-intel
Cleaning up...
vagrant@vagrant:~/singularity$ sudo singularity shell -w caffe-intel
Singularity: Invoking an interactive shell within container...

Singularity caffe-intel:~>
```

**Comment by ArangoGutierrez** [comment]
@yangyang-zhang is this still an issue for you, with the current dist?

**Comment by dtrudg** [comment]
Closing this - a lot of changes to docker layer handling have been merged, which we believe fix remaining issues. Please let us know if you still have any issues with this. Thanks!
