### ISSUE TITLE
singularity exec error

### ISSUE THREAD

**Issue by yangyang-zhang** [apptainer/singularity#1128]
## Version of Singularity:
[root@c031 container]# singularity --version
2.3.2-dist

## mistake
[root@c031 container]# ls -l  intel-caffe.image
-rwxr-xr-x 1 root root 3081764896 Nov  2 15:19 intel-caffe.image

[root@c031 container]# singularity  exec intel-caffe.image ls
ERROR  : Failed to mount image in (read only): Invalid argument
ABORT  : Retval = 255
[root@c031 container]# singularity  shell  intel-caffe.image 
ERROR  : Failed to mount image in (read only): Invalid argument
ABORT  : Retval = 255
[root@c031 container]# singularity shell -w intel-caffe.image
Singularity: Invoking an interactive shell within container...
Singularity intel-caffe.image:~> 

The mirror image is normal,but sometimes there is such a mistake, and no other process is in use,I don't know why, I've found this mistake many times, Can you explain why? thanks

**Comment by dtrudg** [comment]
@yangyang-zhang - are you able to reproduce this error on the Singularity 2.4.x series? If so can you provide a bit more information about the host you are running on. Thanks!

**Comment by dtrudg** [comment]
Closing this issue as it is against deprecated 2.3.x and no report on current version. Please don't hesitate to reopen / open a new issue if you experience this on current Singularity.
