### ISSUE TITLE
 When the implementation of the mirror will be more than one mount

### ISSUE THREAD

**Issue by yangyang-zhang** [apptainer/singularity#1129]
## Version of Singularity:

[root@c031 container]# singularity --version
2.3.2-dist

##  The problem that appears

[root@c031 container]# singularity exec intel-caffe.image ls
caffe-cpu.image   intel-caffe.image    tensorflow.image

[root@c031 container]# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root  100G   91G  9.9G  91% /
devtmpfs                 126G     0  126G   0% /dev
tmpfs                    126G  304K  126G   1% /dev/shm
tmpfs                    126G  548M  126G   1% /run
tmpfs                    126G     0  126G   0% /sys/fs/cgroup
/dev/sda1                240M  144M   85M  64% /boot
/dev/mapper/centos-data  361G  225M  361G   1% /data
tmpfs                     26G   72K   26G   1% /run/user/0
tmpfs                     26G     0   26G   0% /run/user/2015
10.1.0.1:/export/home    3.1T  2.0T  989G  67% /home
10.1.0.1:/export         3.1T  2.0T  989G  67% /share
tmpfs                     16M     0   16M   0% /usr/local/var/singularity/mnt/session
/dev/dm-3                 10G  258M  9.8G   3% /var/lib/docker/devicemapper/mnt/2fc9485d593a74d21d1a52e14bcd774a5e7b25ae1eb9d2e15b6a961a97494669
shm                       64M   16K   64M   1% /var/lib/docker/containers/9714bc5ace913529e903680586deb24213bae8b9beb3fe7b926a812683bc67f8/shm
/dev/loop0               2.8G  1.9G  804M  71% /run/media/root/810ea883-b46d-4a4b-a55a-8597a1fce6f7
/dev/loop1               2.8G  1.9G  804M  71% /run/media/root/810ea883-b46d-4a4b-a55a-8597a1fce6f71

/dev/loop0  and /dev/loop1 is a new mount，Execute a mount once， I don‘t why， help， thanks

**Comment by jscook2345** [comment]
@yangyang-zhang 

Are you asking why `singularity` uses two loop device mounts instead of one when you `exec`?

**Comment by yangyang-zhang** [comment]
The problem has been solved.Thank you！
