### ISSUE TITLE
--overlay pretends to work when overlayfs is not supported/enabled

### ISSUE THREAD

**Issue by 0xaf1f** [apptainer/singularity#1131]
## Version of Singularity:

2.4

### Expected behavior

If overlayfs is not enabled or supported, passing the `--overlay` option still lets you through, giving the user the illusion of it supposed to be working. While the comment in singularity.conf indicates that there will be no warning, this makes more sense when overlayfs is used behind the scenes in bind mounts. Even in that case, if you try to bind mount a directory that doesn't exist in the container and overlayfs doesn't work, the user gets an error about a nonexistent mount point.

Since the `--overlay` option absolutely requires overlayfs, it's misleading to make it appear as though it worked when there's no way it could have.

```
$ grep overlay $SINGULARITY_HOME/etc/singularity/singularity.conf
# overlayfs will be tried but if it is unavailable it will be silently ignored.
enable overlay = no
$ singularity shell --overlay my-overlay.img main.simg
ERROR: overlay is not enabled/supported on this system
$
```
### Actual behavior

```
$ grep overlay $SINGULARITY_HOME/etc/singularity/singularity.conf
# overlayfs will be tried but if it is unavailable it will be silently ignored.
enable overlay = no
$ singularity shell --overlay my-overlay.img main.simg
Singularity: Invoking an interactive shell within container...

Singularity main.simg:~> 
```

### Steps to reproduce behavior
see above.

**Comment by cclerget** [comment]
Closing the issue as `wontfix` because we don't support 2.x anymore. Please upgrade to latest version 3 of Singularity.

**Comment by 0xaf1f** [comment]
yeah...3.x didn't exist back in 2017. I haven't checked whether this is still an issue.
