### ISSUE TITLE
Return code of prepend in prepheader.c is ignored

### ISSUE THREAD

**Issue by FlorianPommerening** [apptainer/singularity#1135]
## Version of Singularity:

2.4

### Expected behavior

When prepending the `LAUNCH_STRING` in prepheader fails, building should fail with the message `Failed to prepend singularity header`.

### Actual behavior

prepheader always returns `0` (the method `prepend` returns a non-zero code on failure, but the return value is ignored in `main`). Building completes with `Singularity container built: [...]`but the image has no `LAUNCH_STRING`.

### Steps to reproduce behavior

There are probably easier ways to reproduce this, but I did the following:
Build a singularity image in a synchronized folder of a vagrant VM based on `singularityware/singularity-2.4`. Vagrant doesn't support `mmap` across the synchronization, so prepend will fail with the message `Error mapping file: Invalid argument`.

**Comment by dtrudg** [comment]
2.x is no longer maintained.
