### ISSUE TITLE
build-size label is incorrect and inconsistent across build environments

### ISSUE THREAD

**Issue by jekriske** [apptainer/singularity#1136]
## Version of Singularity:

2.4 current and dev

### Expected behavior

One would think the build-size label should be disk usage of either the sandbox or the squashfs image (preferably squashfs image). It should also be somewhat consistent.

### Actual behavior

The build size is off by a large margin and changes depending on where it's being built.

Squashfs image
```
vagrant@vagrant:~/tmp$ du  test.simg
3488	test.simg
vagrant@vagrant:~/tmp$ du -h  test.simg
3.5M	test.simg
vagrant@vagrant:~/tmp$ du --apparent-size -sm test.simg
4	test.simg
```
Sandbox directory
```
vagrant@vagrant:~/tmp$ sudo singularity build -s test test.simg
Building from local image: test.simg
Singularity container built: test
Cleaning up...
vagrant@vagrant:~/tmp$ du -s test
5732	test
vagrant@vagrant:~/tmp$ du -hs test
5.6M	test
vagrant@vagrant:~/tmp$ du --apparent-size -sm test
6	test
```
Label:
```
vagrant@vagrant:~/tmp$ singularity inspect -l test.simg | grep size
    "org.label-schema.build-size": "78MB",
```
The same build on Singularity-hub reports it as 187 MB
https://www.singularity-hub.org/containers/700

78 MB and 187 MB are very different than 3.5 MB or even 5.6 MB. If I'm downloading or transferring the image then I really only care about the squashfs file size, but even the sandbox size would be ok.

### Steps to reproduce behavior

Create a singularity image (or sandbox), check the size, then check the label.
During label creation in post.sh if this is switched to du -hs then it does report 5.6 MB as one would normally expect for this particular build if calculating against a sandbox.

**Comment by jscook2345** [comment]
@ikaneshiro 

I'm not seeing `build-size` as a label in the `inspect` output anymore. Was this removed or something missed during the 3.X port?

**Comment by dtrudg** [comment]
This is not in 3.x - `build-size` is inherently ill-defined given we are building a container that will be compressed into a SIF. Have will built something of `build-size` pre-compression, or `build-size` of the SIF file. The sandbox concern is also valid r.e. apparent size on different FS, if there are sparse files etc. If we want to add back size labels in future we need to express with their names what exactly that size is.
