### ISSUE TITLE
Writing to folder inside container?

### ISSUE THREAD

**Issue by justinblaber** [apptainer/singularity#1141]
I have a folder called `/extra` in one of my containers. There's a process inside the container that writes to this folder. The problem is, is there's no "space" left inside the container:

Singularity Multi_Atlas_v2_1_0.img:/> df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       1.0M  1.0M     0 100% /
tmpfs            16G   34M   16G   1% /dev/shm

So the process fails. Is there a way to create a folder and allocate some space, or even just allocate space to `/`? It would be useful to have my process write inside this container so that these files aren't accessible outside the container. 

Sorry if this is in the docs, I checked and couldn't find anything. Also, these are originally docker images (which work fine) and are being converted to singularity images with:

`singularity import Multi_Atlas_v2_1_0.img docker://vuiiscci/vuiiscci:Multi_Atlas_v2_1_0`

So if this can be done with the `import` tool that would be especially useful...

**Comment by vsoch** [comment]
hey @jucestain ! Are you not able to just bind a folder on the host to the container? Eg:

```
singularity exec --bind /host/folder:/extra myscript.py
```
If you need additional data to live *inside* the container then you should add it at build time. If you have a container now that you need to go back in time and add to (and cannot rebuild) then you can:

 - export image to a sandbox
 - make changes
 - create production images

eg

```
sudo singularity build --sandbox [multi-atlas-box] Multi_Atlas_v2_1.0.img
# make changes
sudo singularity build production.simg [multi-atlas-box]
```

What you can't do is write inside the container, as a user, at runtime. That's just no go.

**Comment by justinblaber** [comment]
Ok, good to know about writing stuff at runtime and the sandbox feature. 

For now I'm going to tweak some things so that they're written to a temporary binded folder. Thanks for the help again!!

**Comment by vsoch** [comment]
Good idea! Please ping if you run into trouble.
