### ISSUE TITLE
Cannot use singularity containers over sshfs

### ISSUE THREAD

**Issue by akhanf** [apptainer/singularity#1149]
## Version of Singularity:
2.4-dist

### Expected behavior

I am trying to use a Singularity container (shell, exec, run etc..) where the .img file is on a sshfs mount

### Actual behavior

ERROR  : Image path doesn't exists
ABORT  : Retval = 255

### Steps to reproduce behavior

copy singularity img to a sshfs mounted folder, singularity shell <img>

(apologies if this is related to an existing issue, tried to search but couldn't find the same error)

Ali

**Comment by cclerget** [comment]
@akhanf when using fuse you must specify `-o allow_root` or use user namespace (singularity option -u, note this option accept only directory, no image). However I strongly discourage to mount image over FUSE filesystems, there is too many context switch and cache involved with this kind of setup

**Comment by dtrudg** [comment]
Closing this issue, as .@cclerget provided a solution / explanation. Please let us know if you have any further issues. Thanks!
