### ISSUE TITLE
Problem with binding paths

### ISSUE THREAD

**Issue by elstak** [apptainer/singularity#115]
I copied the example /etc/singularity/singularity.conf and added a few more custom bind paths to the list:
bind path = /etc/nsswitch.conf
bind path = /etc/resolv.conf
bind path = /etc/hosts
bind path = /dev
bind path = /tmp
bind path = /var/tmp
bind path = /scratch
bind path = /glb/apps
bind path = /glb/home

Some of binds like /etc/hosts, /etc/dev, /tmp and /var/tmp work regardless they are or not in the singularity.conf file. The rest are omitted for some reason. Target directories exist inside the image and I get the same behavior starting a session as root or as myself either in R/O or R/W mode.

Any suggestion?

**Comment by elstak** [comment]
My previous test was using the 2.0 tarball. It appears the problem was solved in version 2.1 coming from the git repo. Please, disregard this issue.

**Comment by gmkurtzer** [comment]
Ahh, fantastic! Let us know if you have any other issues!

Greg

## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by rwtaylor** [comment]
I'm having the same problem as elstak with Singularity 2.2 from the github repo.

The only changes I have made to the `singularity.conf` file is to add another bind path.
```
# BIND PATH: [STRING]
# DEFAULT: Undefined
# Define a list of files/directories that should be made available from within
# the container. The file or directory must exist within the container on
# which to attach to. you can specify a different source and destination
# path (respectively) with a colon; otherwise source and dest are the same.
#bind path = /etc/singularity/default-nsswitch.conf:/etc/nsswitch.conf
#bind path = /opt
#bind path = /scratch
bind path = /etc/hosts
bind path = /zstor
```

The directory `/zstor` exists in the container. When I run singularity I can cd into the `/zstor` directory, but it is empty.

**Comment by gmkurtzer** [comment]
@rwtaylor Can you confirm that this issue is in the current 2.2.1 release? Can you also test to see if this is apparent in the "development" github branch?

If it is still present in either/both, can you please attach the --debug output?

Thank you!

**Comment by gmkurtzer** [comment]
Closing ancient ticket. I believe this is fixed in the 'development' branch. Let me know if it is not.
