### ISSUE TITLE
No valid /bin/sh in container

### ISSUE THREAD

**Issue by msieb1** [apptainer/singularity#1150]
## Version of Singularity:

2.3.1

### Expected behavior

I am trying to set up a ubuntu image to run on a cluster. However, once I try to work within the created image, I get the below listed errors. I tried different ways of reproducing the error and in all ends up with complaining in some way about that /bin/sh is missing...

### Actual behavior

> ERROR  : No valid /bin/sh in container
> ABORT  : Retval = 255

### Steps to reproduce behavior

> sudo singularity create -s 4000 im.img
> sudo singularity import ubuntu-xenial-core-cloudimg-amd64-root.tar.gz im.img
> sudo singularity exec --writable im.img apt update

**Comment by ArangoGutierrez** [comment]
@msieb1 is this still and issue for you with the current dist?

**Comment by markeganfuller** [comment]
Maybe related to #835 which was fixed in #858

**Comment by dtrudg** [comment]
Closing as there was no follow-up here.
