### ISSUE TITLE
Legacy %test behavior is broken on 2.4

### ISSUE THREAD

**Issue by isaac-rstor** [apptainer/singularity#1153]
## Version of Singularity:

2.4

### Expected behavior

contents of %test should be executed when the `singularity test <container>` incantantation is invoked

### Actual behavior

`"No singularity tests for contained app:"` is displayed.

### Steps to reproduce behavior

Build a container with a basic test file:
``` 
   Bootstrap:docker
    From:alpine:latest
    %test
        echo "hello"
```

`sudo singularity build test.simg <testfile>`

correctly executes the test.

`singularity test test.simg`

does not.

Error seems to be in file `/.singularity.d/actions/test` conditional in line 10 is triggered even if an app is not specified, the legacy execution path (line 18) should be supported but is never reached.

**Comment by jekriske-lilly** [comment]
This also affects 2.4.2
Here are some more details
```
Bootstrap: docker
From: centos:latest

%post
  echo "Hi There"

%test
  echo "main test"

%apprun app1
  echo "ran app1"

%apptest app1
  echo "test for app1"

%apprun app2
  echo "ran app2"

%apptest app2
  echo "test for app2"

%runscript
  echo "main runscript"
```
executing `singularity test test.simg` results in the error previously posted
executing `singularity test --app app1 test.simg` results in the main test getting executed. This is not expected per http://singularity.lbl.gov/docs-scif-apps 

In addition, the scif app directories do not actually contain the test scripts as searched by `/.singularity.d/actions/test` mentioned previously.

https://github.com/singularityware/singularity/blob/master/libexec/bootstrap-scripts/environment/test#L10 
`if test -z "${SINGULARITY_APPNAME:-}"; then`
says if SINGULARITY_APPNAME is of zero length then go ahead and look for a scif app....
perhaps it was supposed to read:
`if ! test -z "${SINGULARITY_APPNAME:-}"; then`
@gmkurtzer

**Comment by dtrudg** [comment]
This is working in current versions:

```
04:19 PM $ singularity test test.sif 
hello
```
