### ISSUE TITLE
Pull error en some docker images

### ISSUE THREAD

**Issue by jorgesece** [apptainer/singularity#1158]
## Version of Singularity:

2.4

### Expected behavior
Pull image properly:
singularity pull  image.img docker://gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7

### Actual behavior
Pull fails
singularity pull docker://gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7
ERROR MANIFEST_UNKNOWN: Manifest with tag '1.14.7' has media type 'application/vnd.docker.distribution.manifest.v2+json', but client accepts 'application/json'.
Cleaning up...

### Steps to reproduce behavior

Write here.

singularity pull docker://gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7

**Comment by dtrudg** [comment]
GCR is only serving version 2 manifests, but Singularity still depends on a v1 being available (alone or alongside a v2) for runscript and metadata extraction.

https://cloud.google.com/container-registry/docs/support/deprecation-notices

Dockerhub is doing on-the-fly extraction of manifests in schema v1 where images were pushed using the newer v2.

https://docs.docker.com/registry/compatibility/

**Comment by vsoch** [comment]
+1. We would need the version 1 to get metadata about the image, so as a fallback this step could be skipped (and then just obtaining and dumping the list of layers).

**Comment by kcgthb** [comment]
We're seeing some growing interest for this here. Would love to see this implemented.

**Comment by vsoch** [comment]
hey @kcgthb and @dctrud and @jorgesece ! I just updated the sregistry client to handle gcr.io authentication. See the notes here:

https://singularityhub.github.io/sregistry-cli/client-gcr

@kcgthb - for sherlock, sregistry is a python module, so the user would want to load singularity, and then pip install this to their own library (e.g., --user). Here is an example for the image given:

```
 sregistry pull docker://gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7
[client|docker] [database|sqlite:////home/vanessa/.singularity/sregistry.db]
Progress |===================================| 100.0% 
Progress |===================================| 100.0% 
[2/2] |===================================| 100.0% 
WARNING No metadata will be included.
Exploding /usr/local/libexec/singularity/bootstrap-scripts/environment.tar
Exploding /home/vanessa/.singularity/docker/sha256:280aca6ddce2bc2b0904fb525b14e119111c11ca06c3c4d9e4258723da52aecd.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:7007640b33be507b481446c146de3280ab3f12de3a4505ff460eca53546bbc85.tar.gz
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building FS image from sandbox: /tmp/tmp7kje_9t5
Building Singularity FS image...
Building Singularity SIF container image...
Singularity container built: /home/vanessa/.singularity/shub/google_containers-k8s-dns-kube-dns-amd64:1.14.7.simg
Cleaning up...

[container][new] google_containers/k8s-dns-kube-dns-amd64:1.14.7
Success! /home/vanessa/.singularity/shub/google_containers-k8s-dns-kube-dns-amd64:1.14.7.simg
```

The thing about gcr is that (most) of the containers don't have version 1 manifests, so we are currently unable to get metadata like runscript (CMD and ENTRYPOINT) and environment and labels. This is a huge deal, but what a user can do is define it with a bootstrap file. I think we will be able to figure this out, I just haven't looked into it yet. Minimally, this should provide the image "shell." without it's soul, lol.

**Comment by dtrudg** [comment]
Closing this as it's been a long time without follow up - plus the report is against Singularity 2.4 - In 3.x upstream libraries are being used to interact with registries, and I've not seen this to be an issue. Feel free to reopen if anything additional.
