### ISSUE TITLE
example debootstrap-based images don't clear the package cache

### ISSUE THREAD

**Issue by 0xaf1f** [apptainer/singularity#1161]
## Version of Singularity:

all (but matters most for 2.4 since the image size is fitted to the container contents)

### Expected behavior

use `apt-get clean` after calls to `apt-get install` when using debootstrap-based images in order to clear the cache of downloaded packages.

### Actual behavior

The difference in image size after using `apt-get clean` is actually quite significant:

```
-rwxr-xr-x 1 root        root         63M Nov 10 15:47 ubuntu-clean.simg
-rwxr-xr-x 1 root        root        117M Nov 10 15:52 ubuntu-noclean.simg
```

### Steps to reproduce behavior

build image using debootstrap as the agent, with and without using `apt-get clean` after installing a package in `%post`.

**Comment by 0xaf1f** [comment]
This isn't a problem with Debian/Ubuntu images bootstrapped from docker since the docker images have apt configurations that include a hook for deleting downloaded packages (among other things).

```
$ ls /etc/apt/apt.conf.d
01-vendor-ubuntu  01autoremove-kernels	docker-autoremove-suggests  docker-gzip-indexes
01autoremove	  70debconf		docker-clean		    docker-no-languages
$ cat /etc/apt/apt.conf.d/docker-clean
DPkg::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; };
APT::Update::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; };
Dir::Cache::pkgcache ""; Dir::Cache::srcpkgcache "";
```

**Comment by dtrudg** [comment]
This has been merged into development-2.x for a 2.5 release. Thanks!

**Comment by 0xaf1f** [comment]
The issue should be closed automatically when the commit hits master since there is a closure directive in the commit message. I don't think it makes sense to close issues while they still exist in the latest release, especially when it'd be handled automatically for you otherwise.
