### ISSUE TITLE
ERROR  : No valid /bin/sh in container

### ISSUE THREAD

**Issue by dinesh121991** [apptainer/singularity#1164]
## Version of Singularity:

2.3.1

### Expected behavior

bootsrap to create image

### Actual behavior

got error: ERROR  : No valid /bin/sh in container

### Steps to reproduce behavior

I followed tutorial - http://singularity.lbl.gov/building-ubuntu-rhel-host

Debug Deatils:

ncreasing verbosity level (5)
Ending argument loop
Singularity version: 2.3.1-dist
Exec'ing: /home/rajagopald/Install/libexec/singularity/cli/bootstrap.exec
VERBOSE [U=0,P=30314]      message_init()                            Set messagelevel to: 5
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Initialize configuration file: /home/rajagopald/Install/etc/singularity/singularity.conf
ESC[0mDEBUG   [U=0,P=30314]      singularity_config_parse()                Starting parse of configuration file /home/rajagopald/Install/etc/singularity/singularity.conf
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key allow setuid = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key max loop devices = '256'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key allow pid ns = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key config passwd = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key config group = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key config resolv_conf = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key mount proc = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key mount sys = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key mount dev = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key mount home = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key mount tmp = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key mount hostfs = 'no'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key bind path = '/etc/localtime'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key bind path = '/etc/hosts'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key user bind control = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key enable overlay = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key mount slave = 'yes'
ESC[0mVERBOSE [U=0,P=30314]      singularity_config_parse()                Got config key sessiondir max size = '16'
ESC[0mDEBUG   [U=0,P=30314]      singularity_config_parse()                Finished parsing configuration file '/home/rajagopald/Install/etc/singularity/singularity.conf'
ESC[0mVERBOSE [U=0,P=30314]      singularity_registry_init()               Initializing Singularity Registry
ESC[0mVERBOSE [U=0,P=30314]      singularity_registry_set()                Adding value to registry: 'WRITABLE' = '1'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_set()                Returning singularity_registry_set(WRITABLE, 1) = 0
ESC[0mVERBOSE [U=0,P=30314]      singularity_registry_set()                Adding value to registry: 'LIBEXECDIR' = '/home/rajagopald/Install/libexec'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_set()                Returning singularity_registry_set(libexecdir, /home/rajagopald/Install/libexec) = 0
ESC[0mVERBOSE [U=0,P=30314]      singularity_registry_set()                Adding value to registry: 'COMMAND' = 'bootstrap'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_set()                Returning singularity_registry_set(COMMAND, bootstrap) = 0
ESC[0mVERBOSE [U=0,P=30314]      singularity_registry_set()                Adding value to registry: 'MESSAGELEVEL' = '5'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_set()                Returning singularity_registry_set(MESSAGELEVEL, 5) = 0
ESC[0mVERBOSE [U=0,P=30314]      singularity_registry_set()                Adding value to registry: 'VERSION' = '2.3.1-dist'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_set()                Returning singularity_registry_set(version, 2.3.1-dist) = 0
SC[0mDEBUG   [U=0,P=30314]      singularity_registry_set()                Returning singularity_registry_set(version, 2.3.1-dist) = 0
ESC[0mVERBOSE [U=0,P=30314]      singularity_registry_set()                Adding value to registry: 'LOCALSTATEDIR' = '/home/rajagopald/Install/var'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_set()                Returning singularity_registry_set(localstatedir, /home/rajagopald/Install/var) = 0
ESC[0mVERBOSE [U=0,P=30314]      singularity_registry_set()                Adding value to registry: 'SYSCONFDIR' = '/home/rajagopald/Install/etc'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_set()                Returning singularity_registry_set(sysconfdir, /home/rajagopald/Install/etc) = 0
ESC[0mVERBOSE [U=0,P=30314]      singularity_registry_set()                Adding value to registry: 'BINDIR' = '/home/rajagopald/Install/bin'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_set()                Returning singularity_registry_set(bindir, /home/rajagopald/Install/bin) = 0
ESC[0mVERBOSE [U=0,P=30314]      singularity_registry_set()                Adding value to registry: 'BUILDDEF' = 'ubuntu-basic.def'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_set()                Returning singularity_registry_set(BUILDDEF, ubuntu-basic.def) = 0
ESC[0mVERBOSE [U=0,P=30314]      singularity_registry_set()                Adding value to registry: 'IMAGE' = 'ubuntu.img'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_set()                Returning singularity_registry_set(IMAGE, ubuntu.img) = 0
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning NULL on 'HOME'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning NULL on 'TARGET_UID'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning NULL on 'TARGET_GID'
ESC[0mDEBUG   [U=0,P=30314]      singularity_priv_init()                   Initializing user info
ESC[0mDEBUG   [U=0,P=30314]      singularity_priv_init()                   Set the calling user's username to: root
ESC[0mDEBUG   [U=0,P=30314]      singularity_priv_init()                   Marking uinfo structure as ready
ESC[0mDEBUG   [U=0,P=30314]      singularity_priv_init()                   Obtaining home directory
ESC[0mVERBOSE [U=0,P=30314]      singularity_priv_init()                   Set home (via getpwuid()) to: /root
ESC[0mINFO    [U=0,P=30314]      main()                                    Sanitizing environment
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: MANPATH
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: XDG_SESSION_ID
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: HOSTNAME
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: SINGULARITY_WRITABLE
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: TERM
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: SHELL
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: SCTL_NFS_ROOT
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: HISTSIZE
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: SSH_CLIENT
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: PERL5LIB
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: SCTL_NFS_SERVER_IP
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: SSH_TTY
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: SINGULARITY_libexecdir
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: SINGULARITY_COMMAND
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: USER
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: SINGULARITY_MESSAGELEVEL
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: LD_LIBRARY_PATH
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: LS_COLORS
ESC[0mDEBUG   [U=0,P=30314]      envclean()                                Unsetting environment variable: TERMCAP
ESC[0mDEBUG   [U=0,P=30314]      singularity_priv_drop()                   Running as root, not changing privileges
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Setting environment variable: 'PATH' = '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'
ESC[0mDEBUG   [U=0,P=30314]      singularity_runtime_rootfs()              Returning container_directory: /home/rajagopald/Install/var/singularity/mnt/container
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Setting environment variable: 'SINGULARITY_ROOTFS' = '/home/rajagopald/Install/var/singularity/mnt/container'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning value from registry: 'LIBEXECDIR' = '/home/rajagopald/Install/libexec'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Setting environment variable: 'SINGULARITY_libexecdir' = '/home/rajagopald/Install/libexec'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning value from registry: 'IMAGE' = 'ubuntu.img'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Setting environment variable: 'SINGULARITY_IMAGE' = 'ubuntu.img'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning value from registry: 'BUILDDEF' = 'ubuntu-basic.def'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Setting environment variable: 'SINGULARITY_BUILDDEF' = 'ubuntu-basic.def'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning value from registry: 'MESSAGELEVEL' = '5'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Setting environment variable: 'SINGULARITY_MESSAGELEVEL' = '5'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning NULL on 'NOTEST'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Unsetting environment variable: SINGULARITY_NOTEST
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning NULL on 'BUILDSECTION'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Unsetting environment variable: SINGULARITY_BUILDSECTION
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning NULL on 'BUILDNOBASE'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Unsetting environment variable: SINGULARITY_BUILDNOBASE
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning NULL on 'CACHEDIR'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Unsetting environment variable: SINGULARITY_CACHEDIR
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning value from registry: 'VERSION' = '2.3.1-dist'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Setting environment variable: 'SINGULARITY_version' = '2.3.1-dist'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Setting environment variable: 'HOME' = '/root'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Setting environment variable: 'LANG' = 'C'
ESC[0mDEBUG   [U=0,P=30314]      singularity_registry_get()                Returning value from registry: 'BUILDDEF' = 'ubuntu-basic.def'
ESC[0mINFO    [U=0,P=30314]      bootstrap_init()                          Building from bootstrap definition recipe
ESC[0mVERBOSE [U=0,P=30314]      bootstrap_keyval_parse()                  Got bootstrap definition key/val 'MirrorURL "http' = '//us.archive.ubuntu.com/ubuntu/"'
ESC[0mDEBUG   [U=0,P=30314]      uppercase()                               Transformed to uppercase: 'MirrorURL "http' -> 'MIRRORURL "HTTP'
ESC[0mDEBUG   [U=0,P=30314]      envar_set()                               Setting environment variable: 'MIRRORURL "HTTP' = '//us.archive.ubuntu.com/ubuntu/"'
ESC[0mVERBOSE [U=0,P=30333]      message_init()                            Set messagelevel to: 5
ESC[0mDEBUG   [U=0,P=30333]      main()                                    Iterating through file looking for sections matching: %pre
ESC[0mAdding base Singularity environment to container
VERBOSE [U=0,P=30340]      message_init()                            Set messagelevel to: 5
ESC[0mDEBUG   [U=0,P=30340]      main()                                    Iterating through file looking for sections matching: %runscript
ESC[0mESC[31m**ERROR: Could not locate /bin/sh inside the container**

**Comment by cclerget** [comment]
@dinesh121991 You read an old documentation link for outdated 2.1.2 version, if you use 2.3 you can take a look at  http://singularity.lbl.gov/archive/docs/v2-3/bootstrap-image to bootstrap container
