### ISSUE TITLE
ERROR: Failed squashing image, left template directory at: /tmp/.singularity-build.v55FSe

### ISSUE THREAD

**Issue by imimsri** [apptainer/singularity#1166]
## Version of Singularity:
Specific PR 1106

jandres@666be565c8c9:~$ singularity --version
2.4-PR1106.g1f68a97

### Expected behavior

When building some images, it does work well:
jandres@666be565c8c9:~$ singularity build kk.img docker://machalen/star
Docker image path: index.docker.io/machalen/star:latest
Cache folder set to /home/jandres/.singularity/docker
Importing: base Singularity environment
Importing: /home/jandres/.singularity/docker/sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:5ad56d5fc14905886c560200ab69f905b5c5287eaf12f8f761a7ab54f7a61c1b.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:170e558760e8b2e484a022b7d7272cf284fc4e1936ba7a0a671fc586440ad272.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:395460e233f5bdcd910d618a3b615e0d881e09ad27d58f3065eef53ecae6a808.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:6f01dc62e444044e3ce494269837ef0aedb80fef69c679416137f17812d2eb9c.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:28ad454b954b3a32e462e61f0481834abda625b7473f8eb41655ed9b9e99e7af.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:86993c1a18bcc5a4e710f5b5f32d44bb75c2e43ce9ce71473b154cffb2d0ba29.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:b4d1006a4577ac2afe2b642b11ac369034ead98fba3ef410eabb0ec89ddee59a.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:bc28774e7633f3c592bdc032347217c948449dd4353963a2b4a0c16a3b6148ca.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:fae1e7451cfe5abd856a5e714b0e28006a0f807ecc18b1b3f05d1601c65ac873.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:3f29f6ae7cef2f582750f8d8cc305b9861fca356224e82601f3e3b4217f686ed.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:53b886de8f96642d99af37031aea3d69bd5976aead725b9bc7fe3bd9af18ecf8.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:cdf5f9d7010ae5c3e45513ae473eaef249e7418fa091f659ba1cb69879e9a778.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:86702f8c15532abd55f5a194ae6bb78ee19b4790c8d63062e29e17f5205f55f7.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:19a9f7c72e060bf4eaf8817359b8b493fce081e6e0f74e6fe2b9796fddd50cc5.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:df1eb1387e4d2ca774eea427023a0de529a3b3ac8a4be0f1eb67e6f581611877.tar.gz
Importing: /home/jandres/.singularity/metadata/sha256:f4c82a5a736189d9a2fe399aca40fc4870d7e723416618d6a059248dd06165cb.tar.gz
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building Singularity image...
Singularity container built: kk.img
Cleaning up...

### Actual behavior

But for some others, it doesn't:
jandres@666be565c8c9:~$ singularity build r_ewas6.img docker://csoriano/r_ewas6
Docker image path: index.docker.io/csoriano/r_ewas6:latest
Cache folder set to /home/jandres/.singularity/docker
[1/13] |==|--------------------------------|   7.7% 

[13/13] |===================================| 100.0% 
Importing: base Singularity environment
Importing: /home/jandres/.singularity/docker/sha256:11b6b7643aadccaefe5f3b6535fc4621f8ea80f50fe3299af61f174f5ab2d3b9.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:29784196629923bcaa89767b17fb9baa0e49400252e8fd9d54685a3fd37b8bf2.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:6f1a5cc5fce04cecbf2072c6807354f09ec3d7a41779b4fd376fe2b44fef53be.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:866562a2f3d4457f8368e33322d173b7f88884c09a2190d70d5e069e74d0b4c8.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:a3e279b678a6950edc80accd87ac5dff746a2c9038016df5bc25119137b093ab.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:d95c11fad2478f50009d5c7de8a114ec1f26b0d8b9b309b3bfa147c1d694d967.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:bd7be1c77cc1e62357adea00af229824b9459ae9058ac2b685a90232b19c93c4.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:ec50117cfb31cd688100479115e3cb7b4aefe0b54bf6dccf3a4c5945fa9365b6.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:40cc9c64f823bc1bf4ddf2f211226698d7478079f961516b67f74c6a66bc38b7.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:b5897a6e692a75e9ca4948213905fa990602dfb99a0e556398fc8f41c1d1384f.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:a4e630cbebf7687a5e32a2da327bf7d070be6ae6c75d0a0f2155ed5705e8204a.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:627d910ee7b7a0c375de9d3ec007b4d77e4c6ff84b119b4fd13c4f035fcbf8a0.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:9c01e0633733b8efac2ca8af12d70c508a1473821548d4ae09f404a921b9dcb2.tar.gz
Importing: /home/jandres/.singularity/metadata/sha256:7a107bb2a6a4e252d2b79930b22c5992d4d79fef9ba0fe477e0e282e4e7565ed.tar.gz
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building Singularity image...
/usr/local/libexec/singularity/cli/build.exec: line 408:  6446 Killed                  mksquashfs "$SINGULARITY_ROOTFS/" "$SINGULARITY_CONTAINER_OUTPUT" -noappend $OPTS > /dev/null
ERROR: Failed squashing image, left template directory at: /tmp/.singularity-build.v55FSe
Cleaning up...

### Steps to reproduce behavior

building image

singularity build r_ewas6.img docker://csoriano/r_ewas6

**Comment by dtrudg** [comment]
@imimsri - to confirm, does this failure only happen with PR #1106, or does it happen with the release version of Singularity too? I'll take a look at some point this weekend. Thanks,

**Comment by imimsri** [comment]
I've just tested it with my workstation compiling from source(master branch) and I have no problem at all:

`
dep@dep:~/singularity$ singularity build r_ewas.img docker://csoriano/r_ewas6
Docker image path: index.docker.io/csoriano/r_ewas6:latest
Cache folder set to /home/dep/.singularity/docker
[13/13] |===================================| 100.0%
Importing: base Singularity environment
Importing: /home/dep/.singularity/docker/sha256:11b6b7643aadccaefe5f3b6535fc4621f8ea80f50fe3299af61f174f5ab2d3b9.tar.gz
Importing: /home/dep/.singularity/docker/sha256:29784196629923bcaa89767b17fb9baa0e49400252e8fd9d54685a3fd37b8bf2.tar.gz
Importing: /home/dep/.singularity/docker/sha256:6f1a5cc5fce04cecbf2072c6807354f09ec3d7a41779b4fd376fe2b44fef53be.tar.gz
Importing: /home/dep/.singularity/docker/sha256:866562a2f3d4457f8368e33322d173b7f88884c09a2190d70d5e069e74d0b4c8.tar.gz
Importing: /home/dep/.singularity/docker/sha256:a3e279b678a6950edc80accd87ac5dff746a2c9038016df5bc25119137b093ab.tar.gz
Importing: /home/dep/.singularity/docker/sha256:d95c11fad2478f50009d5c7de8a114ec1f26b0d8b9b309b3bfa147c1d694d967.tar.gz
Importing: /home/dep/.singularity/docker/sha256:bd7be1c77cc1e62357adea00af229824b9459ae9058ac2b685a90232b19c93c4.tar.gz
Importing: /home/dep/.singularity/docker/sha256:ec50117cfb31cd688100479115e3cb7b4aefe0b54bf6dccf3a4c5945fa9365b6.tar.gz
Importing: /home/dep/.singularity/docker/sha256:40cc9c64f823bc1bf4ddf2f211226698d7478079f961516b67f74c6a66bc38b7.tar.gz
Importing: /home/dep/.singularity/docker/sha256:b5897a6e692a75e9ca4948213905fa990602dfb99a0e556398fc8f41c1d1384f.tar.gz
Importing: /home/dep/.singularity/docker/sha256:a4e630cbebf7687a5e32a2da327bf7d070be6ae6c75d0a0f2155ed5705e8204a.tar.gz
Importing: /home/dep/.singularity/docker/sha256:627d910ee7b7a0c375de9d3ec007b4d77e4c6ff84b119b4fd13c4f035fcbf8a0.tar.gz
Importing: /home/dep/.singularity/docker/sha256:9c01e0633733b8efac2ca8af12d70c508a1473821548d4ae09f404a921b9dcb2.tar.gz
Importing: /home/dep/.singularity/metadata/sha256:7a107bb2a6a4e252d2b79930b22c5992d4d79fef9ba0fe477e0e282e4e7565ed.tar.gz
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building Singularity image...
Singularity container built: r_ewas.img
Cleaning up...
`


But it doesn't work when compiling the lates master in a docker container:


`jandres@slurmd_5:~$ singularity build r_ewas6.img docker://csoriano/r_ewas6
Docker image path: index.docker.io/csoriano/r_ewas6:latest
Cache folder set to /home/jandres/.singularity/docker
Importing: base Singularity environment
Importing: /home/jandres/.singularity/docker/sha256:11b6b7643aadccaefe5f3b6535fc4621f8ea80f50fe3299af61f174f5ab2d3b9.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:29784196629923bcaa89767b17fb9baa0e49400252e8fd9d54685a3fd37b8bf2.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:6f1a5cc5fce04cecbf2072c6807354f09ec3d7a41779b4fd376fe2b44fef53be.tar.gz
tar: var/lib/apt/lists/.wh.partial: Cannot open: Operation not permitted
tar: Exiting with failure status due to previous errors
Cleaning up...
`

I have also noticed that when caching the image it gets stacked at 7.7%

`
singularity build r_ewas6.img docker://csoriano/r_ewas6
Docker image path: index.docker.io/csoriano/r_ewas6:latest
Cache folder set to /root/.singularity/docker
[1/13] |==|--------------------------------|   7.7%
`

**Comment by dtrudg** [comment]
The stuck at 7.7% for a while is because there is a huuuuge multi GB layer it is dealing with.

The PR #1106 should fix the second issue when you were building in a docker container, but I suspect it may fail later then due to an out of space issue. I tried it out on a physical machine and did see an issue with the extraction or squash step failing when I had a machine that had /tmp in tmpfs with limited space not sufficient for this large container.

Can you confirm how much /tmp there was when you had a failure with PR #1106 - and post output you get running with the '-d' debug option.

**Comment by titansmc** [comment]
Sorry for the delay, here is the output running in debug mode within a docker container:


`
jandres@cdd40703dbcb:~$ singularity --debug  build r_ewas6.img docker://csoriano/r_ewas6
Enabling debugging
Ending argument loop
Singularity version: 2.4-PR1106.g1f68a97
Exec'ing: /usr/local/libexec/singularity/cli/build.exec
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS found as /tmp/.singularity-build.0yrz1n
VERBOSE2 SINGULARITY_METADATA_FOLDER found as /tmp/.singularity-build.0yrz1n/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /home/jandres/.singularity
VERBOSE2 REGISTRY not defined (None)
VERBOSE2 NAMESPACE not defined (None)
VERBOSE2 SINGULARITY_DOCKER_ARCHITECTURE found as amd64
VERBOSE2 SINGULARITY_DOCKER_OS found as linux
VERBOSE2 SINGULARITY_ENVIRONMENT found as /tmp/.singularity-build.0yrz1n/.singularity.d/env/90-environment.sh
VERBOSE2 SINGULARITY_RUNSCRIPT found as /tmp/.singularity-build.0yrz1n/singularity
VERBOSE2 SINGULARITY_TESTFILE found as /tmp/.singularity-build.0yrz1n/.singularity.d/test
VERBOSE2 SINGULARITY_DEFFILE found as /tmp/.singularity-build.0yrz1n/.singularity.d/Singularity
VERBOSE2 SINGULARITY_HELPFILE found as /tmp/.singularity-build.0yrz1n/.singularity.d/runscript.help
VERBOSE2 SINGULARITY_ENVBASE found as /tmp/.singularity-build.0yrz1n/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as /tmp/.singularity-build.0yrz1n/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_NOHTTPS found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as /home/jandres
VERBOSE2 SHUB_NAMEBYHASH not defined (None)
VERBOSE2 SHUB_NAMEBYCOMMIT not defined (None)
VERBOSE2 SHUB_CONTAINERNAME not defined (None)
VERBOSE2 SINGULARITY_CONTENTS found as /tmp/.singularity-layers.eYIXMn8h
VERBOSE2 SINGULARITY_PYTHREADS found as 9
VERBOSE2 SINGULARITY_CONTAINER found as docker://csoriano/r_ewas6
DEBUG Found uri docker://
DEBUG
*** STARTING DOCKER IMPORT PYTHON  ****
DEBUG Docker layers and metadata will be written to: /tmp/.singularity-layers.eYIXMn8h
VERBOSE2 SINGULARITY_DOCKER_USERNAME not defined (None)
DEBUG Starting Docker IMPORT, includes env, runscript, and metadata.
VERBOSE Docker image: csoriano/r_ewas6
VERBOSE2 Specified Docker ENTRYPOINT as %runscript.
DEBUG Headers found: Content-Type,Accept
VERBOSE Registry: index.docker.io
VERBOSE Namespace: csoriano
VERBOSE Repo Name: r_ewas6
VERBOSE Repo Tag: latest
VERBOSE Version: None
VERBOSE Obtaining tags: https://index.docker.io/v2/csoriano/r_ewas6/tags/list
DEBUG GET https://index.docker.io/v2/csoriano/r_ewas6/tags/list
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?service=registry.docker.io&expires_in=9000&scope=repository:csoriano/r_ewas6:pull
DEBUG Headers found: Content-Type,Authorization,Accept
VERBOSE3 Response on obtaining token is None.
Docker image path: index.docker.io/csoriano/r_ewas6:latest
DEBUG Updating manifests.
DEBUG MANIFEST (Primary): not found, making initial call.
VERBOSE Obtaining manifest: https://index.docker.io/v2/csoriano/r_ewas6/manifests/latest
DEBUG GET https://index.docker.io/v2/csoriano/r_ewas6/manifests/latest
DEBUG MANIFEST (Metadata): not found, making initial call.
VERBOSE Obtaining manifest: https://index.docker.io/v2/csoriano/r_ewas6/manifests/latest
DEBUG GET https://index.docker.io/v2/csoriano/r_ewas6/manifests/latest
DEBUG Image manifest version 2.2 found.
DEBUG Adding digest sha256:11b6b7643aadccaefe5f3b6535fc4621f8ea80f50fe3299af61f174f5ab2d3b9
DEBUG Adding digest sha256:29784196629923bcaa89767b17fb9baa0e49400252e8fd9d54685a3fd37b8bf2
DEBUG Adding digest sha256:6f1a5cc5fce04cecbf2072c6807354f09ec3d7a41779b4fd376fe2b44fef53be
DEBUG Adding digest sha256:866562a2f3d4457f8368e33322d173b7f88884c09a2190d70d5e069e74d0b4c8
DEBUG Adding digest sha256:a3e279b678a6950edc80accd87ac5dff746a2c9038016df5bc25119137b093ab
DEBUG Adding digest sha256:d95c11fad2478f50009d5c7de8a114ec1f26b0d8b9b309b3bfa147c1d694d967
DEBUG Adding digest sha256:bd7be1c77cc1e62357adea00af229824b9459ae9058ac2b685a90232b19c93c4
DEBUG Adding digest sha256:ec50117cfb31cd688100479115e3cb7b4aefe0b54bf6dccf3a4c5945fa9365b6
DEBUG Adding digest sha256:40cc9c64f823bc1bf4ddf2f211226698d7478079f961516b67f74c6a66bc38b7
DEBUG Adding digest sha256:b5897a6e692a75e9ca4948213905fa990602dfb99a0e556398fc8f41c1d1384f
DEBUG Adding digest sha256:a4e630cbebf7687a5e32a2da327bf7d070be6ae6c75d0a0f2155ed5705e8204a
DEBUG Adding digest sha256:627d910ee7b7a0c375de9d3ec007b4d77e4c6ff84b119b4fd13c4f035fcbf8a0
DEBUG Adding digest sha256:9c01e0633733b8efac2ca8af12d70c508a1473821548d4ae09f404a921b9dcb2
Cache folder set to /home/jandres/.singularity/docker
DEBUG Using 9 workers for multiprocess.
VERBOSE3 Found Docker command (Entrypoint) None
VERBOSE3 Found Docker command (Cmd) [u'R']
VERBOSE3 Adding Docker CMD as Singularity runscript...
VERBOSE3 Found Docker command (Env) [u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', u'LC_ALL=en_US.UTF-8', u'LANG=en_US.UTF-8', u'R_BASE_VERSION=3.4.0']
VERBOSE3 Found Docker container environment!
VERBOSE3 Adding Docker environment to metadata tar
DEBUG Found template for tarinfo
VERBOSE3 Found Docker command (Labels) {}
VERBOSE3 Adding Docker labels to metadata tar
DEBUG Found template for tarinfo
VERBOSE3 Adding Docker runscript to metadata tar
DEBUG Found template for tarinfo
DEBUG metadata file /home/jandres/.singularity/metadata/sha256:7a107bb2a6a4e252d2b79930b22c5992d4d79fef9ba0fe477e0e282e4e7565ed.tar.gz already exists will over-write.
VERBOSE2 Tar file with Docker env and labels: /home/jandres/.singularity/metadata/sha256:7a107bb2a6a4e252d2b79930b22c5992d4d79fef9ba0fe477e0e282e4e7565ed.tar.gz
VERBOSE3 Writing Docker layers files to /tmp/.singularity-layers.eYIXMn8h
VERBOSE2 Writing file /tmp/.singularity-layers.eYIXMn8h with mode w.
VERBOSE2 Writing file /tmp/.singularity-layers.eYIXMn8h with mode a.
DEBUG *** FINISHING DOCKER IMPORT PYTHON PORTION ****
Importing: base Singularity environment
Importing: /home/jandres/.singularity/docker/sha256:11b6b7643aadccaefe5f3b6535fc4621f8ea80f50fe3299af61f174f5ab2d3b9.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:29784196629923bcaa89767b17fb9baa0e49400252e8fd9d54685a3fd37b8bf2.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:6f1a5cc5fce04cecbf2072c6807354f09ec3d7a41779b4fd376fe2b44fef53be.tar.gz
Removing whiteout-ed file/dir var/lib/apt/lists/partial
Importing: /home/jandres/.singularity/docker/sha256:866562a2f3d4457f8368e33322d173b7f88884c09a2190d70d5e069e74d0b4c8.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:a3e279b678a6950edc80accd87ac5dff746a2c9038016df5bc25119137b093ab.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:d95c11fad2478f50009d5c7de8a114ec1f26b0d8b9b309b3bfa147c1d694d967.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:bd7be1c77cc1e62357adea00af229824b9459ae9058ac2b685a90232b19c93c4.tar.gz
Removing whiteout-ed file/dir usr/lib/x86_64-linux-gnu/gio
Removing whiteout-ed file/dir usr/lib/x86_64-linux-gnu/libcairo.so.2.11400.8
Removing whiteout-ed file/dir usr/lib/x86_64-linux-gnu/libexpat.so.1.6.2
Removing whiteout-ed file/dir usr/lib/x86_64-linux-gnu/libexpatw.so.1.6.2
Removing whiteout-ed file/dir usr/lib/x86_64-linux-gnu/libfontconfig.so.1.8.0
Removing whiteout-ed file/dir usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.3
Removing whiteout-ed file/dir usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.5000.3
Removing whiteout-ed file/dir usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5000.3
Removing whiteout-ed file/dir usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.5000.3
Removing whiteout-ed file/dir usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5000.3
Removing whiteout-ed file/dir usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.5000.3
Removing whiteout-ed file/dir usr/share/doc/libfontconfig1/changelog.Debian.amd64.gz
Removing whiteout-ed file/dir usr/share/doc/libglib2.0-0/AUTHORS
Removing whiteout-ed file/dir usr/share/lintian/overrides/libfreetype6
Removing whiteout-ed file/dir var/lib/dpkg/info/libxau6:amd64.postinst
Removing whiteout-ed file/dir var/lib/dpkg/info/libxau6:amd64.postrm
Importing: /home/jandres/.singularity/docker/sha256:ec50117cfb31cd688100479115e3cb7b4aefe0b54bf6dccf3a4c5945fa9365b6.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:40cc9c64f823bc1bf4ddf2f211226698d7478079f961516b67f74c6a66bc38b7.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:b5897a6e692a75e9ca4948213905fa990602dfb99a0e556398fc8f41c1d1384f.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:a4e630cbebf7687a5e32a2da327bf7d070be6ae6c75d0a0f2155ed5705e8204a.tar.gz
Importing: /home/jandres/.singularity/docker/sha256:627d910ee7b7a0c375de9d3ec007b4d77e4c6ff84b119b4fd13c4f035fcbf8a0.tar.gz
Making usr/local/lib/R/site-library/AnnotationDbi opaque
Making usr/local/lib/R/site-library/Biobase opaque
Making usr/local/lib/R/site-library/FDb.InfiniumMethylation.hg19 opaque
Making usr/local/lib/R/site-library/GenomicRanges opaque
Making usr/local/lib/R/site-library/IRanges opaque
Making usr/local/lib/R/site-library/RnBeads opaque
Making usr/local/lib/R/site-library/RnBeads.hg19 opaque
Making usr/local/lib/R/site-library/gdata opaque
Making usr/local/lib/R/site-library/ggplot2 opaque
Making usr/local/lib/R/site-library/illuminaio opaque
Making usr/local/lib/R/site-library/limma opaque
Making usr/local/lib/R/site-library/methylumi opaque
Importing: /home/jandres/.singularity/docker/sha256:9c01e0633733b8efac2ca8af12d70c508a1473821548d4ae09f404a921b9dcb2.tar.gz
Making usr/local/lib/R/site-library/Hmisc opaque
Making usr/local/lib/R/site-library/MASS opaque
Making usr/local/lib/R/site-library/doParallel opaque
Making usr/local/lib/R/site-library/dplyr opaque
Making usr/local/lib/R/site-library/ggplot2 opaque
Making usr/local/lib/R/site-library/glmnet opaque
Making usr/local/lib/R/site-library/gplots opaque
Making usr/local/lib/R/site-library/knitr opaque
Making usr/local/lib/R/site-library/lmtest opaque
Making usr/local/lib/R/site-library/markdown opaque
Making usr/local/lib/R/site-library/matrixStats opaque
Making usr/local/lib/R/site-library/plyr opaque
Making usr/local/lib/R/site-library/sandwich opaque
Importing: /home/jandres/.singularity/metadata/sha256:7a107bb2a6a4e252d2b79930b22c5992d4d79fef9ba0fe477e0e282e4e7565ed.tar.gz
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building Singularity image...
/usr/local/libexec/singularity/cli/build.exec: line 408:   931 Killed                  mksquashfs "$SINGULARITY_ROOTFS/" "$SINGULARITY_CONTAINER_OUTPUT" -noappend $OPTS > /dev/null
ERROR: Failed squashing image, left template directory at: /tmp/.singularity-build.0yrz1n
Cleaning up...
`

The /tmp filesystem was totally fine, not over 93% occupation. Can I specify somehow an alternative directory to place temp files for building the image inside docker?

This was before building image:


Filesystem                                                                       1K-blocks        Used  Available Use% Mounted on

none                                                                             444076160   389451676   32043596  93% /
tmpfs                                                                                65536           0      65536   0% /dev
tmpfs                                                                             66010020           0   66010020   0% /sys/fs/cgroup
tmpfs                                                                             13202008      440276   12761732   4% /run/docker.sock


This was almost at the end of the building image process.:


jandres@cdd40703dbcb:~$ df -h

Filesystem                                                                      Size  Used Avail Use% Mounted on
none                                                                            424G  362G   41G  90% /
tmpfs                                                                            64M     0   64M   0% /dev
tmpfs                                                                            63G     0   63G   0% /sys/fs/cgroup
tmpfs                                                                            13G  430M   13G   4% /run/docker.sock

**Comment by dtrudg** [comment]
Hi @titansmc - sorry for the slow reply here. If you are still seeing this, would you be able to try with the `release-2.4` branch, which has merged all of the docker extraction fixes. Also, if you see an error still - could you try to set the temp location used by singularity to somewhere else e.g.  `SINGULARITY_TMPDIR=/scratch/tmp` just to make certain we aren't hitting any space issue on this large container? I did manage to hit the same error trying to extract it on a Fedora machine which had a small tmpfs `/tmp`

**Comment by titansmc** [comment]
Hi @dctrud , I feel sorry, but I just moved to a different institution and I no longer have access to the cluster, however I will forward this issue to my previous colleges.

Thanks for your help.

**Comment by dtrudg** [comment]
Closing this as it is believed fixed in the 2.5.0 extraction fixes. If any further issues are experienced please feel free to reopen the issue.
