### ISSUE TITLE
Home directory specification (--home) clashes with bindmounting

### ISSUE THREAD

**Issue by graffaele** [apptainer/singularity#1167]
## Version of Singularity:
2.4

### Expected behavior
mkdir /tmp/newhome
singularity exec -H /tmp/newhome myimage.simg /bin/bash
ls /tmp
adir afile anotherdir anotherfile newhome this that

### Actual behavior
ls /tmp
newhome

The home directory specification (--home) clashes with the bindmounting of upper directories, in the sense that within the container, the directory tree above the home dir is not visible, but the branch leading to the home dir.

### Steps to reproduce behavior
As described above. I get the issue on Debian nodes (kernel 3.16.0, debian_version 8.9). I don't get the issue, running the same commands and the same Singularity image, on my PC (kernel 4.4.0, Ubuntu 16.04).

### My questions
* Does the issue arise from the specific kernel version only or does Singularity and its interaction with the host play a role too? Have you already seen this? Can you suggest something to effectively narrow it down?
* I need to access from within the container a file in the host's /tmp/ and at the same time to set the container home dir to point to somewhere on the host's /tmp. Can I circumvent the issue to get the wanted result? For example I tried the *-c* together with the *-W* options (*singularity exec -c -W /tmp -H /tmp/newhome myimage.simg /bin/bash*) without success. If I understand correctly, these options do not help since *-c* excludes the mounting of /tmp (among others) and the option *-W* just says where in the container empty dirs for /tmp, /var/tmp and $HOME should be mounted. So this is not a way to have the host's /tmp visible inside the container, right?

Thanks, best,
      Raffaele

**Comment by graffaele** [comment]
I tentatively answer myself my two questions:
* The cause of the issue is that Singularity 2.4, contrary to 2.2 for example, uses OverlayFS functionality for pointing the container internal $HOME to a host target directory and this makes all the branch containing this target directory invisible but for the target directory path itself in case the host has an old kernel, not handling (correctly) OverlayFS.
* A possible workaround (the one we are about to confirm on our cluster) is to use *-c* and */var/tmp* as target $HOME, as it is the only other "tmp-like" directory, but /tmp itself. So we use:
`singularity exec -c -B xxx -B /tmp/:/tmp/ -B /var/tmp/:/var/tmp/ -H /var/tmp/newhome myimage.simg

Does it sound good?

**Comment by cclerget** [comment]
@graffaele and if you run like this ? :

`singularity exec -H /tmp/newhome:$HOME myimage.simg ls /tmp`

**Comment by graffaele** [comment]
@cclerget indeed that's different from `-H /tmp/newhome` alone and doesn't trigger the issue:
```
$ singularity exec -H /tmp/newhome:$HOME myimage.simg ls /tmp
adir  afile  anotherdir  newhome this that
$ singularity exec -H /tmp/newhome myimage.simg ls /tmp
newhome
```
Why? According to the documentation:
> dest overrides the home directory within the container

so I expected the two syntaxes (`-H /tmp/newhome` and `-H /tmp/newhome:$HOME`) to be equivalent.

**Comment by jmstover** [comment]
@graffaele 
Is this still an issue for you? I was testing on a current'ish build of the development branch and:
`singularity exec -H /tmp/newhome myimage.simg ls /tmp`
gives the full output of `/tmp` ... not just the home directory

**Comment by graffaele** [comment]
@jmstover  Thanks for the information! I'll keep an eye on new installations of Singularity on our cluster to check myself. However the issue was not a problem any more, since I could already get the intended behavior (seeing from within the container the content of the host /tmp and mapping the container's home to a tmp-like dir) either by means of the workaround in my previous comment or by explicitly specifying to '-H' the destination home too, as suggested by cclerget.

**Comment by dtrudg** [comment]
This is working in current versions. Doing an `ls` after `singularity exec -H /tmp/newhome test.sif /bin/bash` gives a full view of `/tmp`
