### ISSUE TITLE
process.cpp:956] Failed to accept socket: future discarded

### ISSUE THREAD

**Issue by jl98800** [apptainer/singularity#1169]
## Version of Singularity: 0.16.2

Why am I seeing this in the log for my singularity job?

### Expected behavior

Expected the job to run. 

### Actual behavior

Job fails with process.cpp:956] Failed to accept socket: future discarded

### Steps to reproduce behavior

Reschedule app.

**Comment by gmkurtzer** [comment]
Singularity does not have a `process.cpp` source file (or any C++ code). A quick google check seems to point at Mesos, but we will need more information to help.

**Comment by jl98800** [comment]
Opening this issue with Mesos. Thanks.

**Comment by bauerm97** [comment]
@jl98800 I'm going to close this issue. Hopefully you've found a solution. Thanks!

**Comment by jl98800** [comment]
Thanks. Sorry I didn’t update/close

Thanks,

John
