### ISSUE TITLE
Contentious legalese in web Contributing section

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#117]
After eventually reading the Contributing section on the web site, I'm afraid I've stopped contributing.

It seems to require accepting an unusual legal theory about "patches" and derivative works (in US terms?) generally -- i.e. that contributors don't have any copyright in changes even if they are copyright-significant according to, say, the FSF's legal advice.  Without accepting that, the only way to make what would normally be considered copyrightable contributions seems to be to disclaim or assign copyright.  If I wanted to do so I'd need agreement from my employer to the extent it has a copyright interest.  (I don't understand the term "assert copyright", since copyright is automatic, even in the US now.)

I think the text at least needs to make clear what its status is as legal advice/opinion since it appears to disagree with what I've seen and been told.  Also this information should be distributed with the software, as it implies that the "separate written license agreement" mentioned in the licence could be void, depending on LBL's  determination of something as a "patch".

The section also suggests that the licence is the standard "BSD3", but it's actually a distinct one called "LBNL BSD" in Fedora https://fedoraproject.org/wiki/Licensing/LBNLBSD or "BSD-3-Clause-LBNL" in SPDX, as used by Debian https://spdx.org/licenses/BSD-3-Clause-LBNL.html#licenseText.  (I missed that initially, as did the automated licence check.)  It is a potential trap for people publishing changes who may not realize about the all-permissive default licence, especially if the licence is described as simply BSD3.

**Comment by rhc54** [comment]
I’m honestly rather surprised by all the angst expressed by a couple of folks on the list regarding the license. There is nothing specifically onerous about it, and I’ve seen this language in the combination of license + contributor agreement rather frequently. The split between what appears in the license itself vs the contributor agreement varies, but the overall content is the same.

You cannot “own” copyright in something you contribute to a 3-clause BSD project. Once you contribute it, the project must remain free to distribute it without asking your permission. Likewise, anyone who uses it must be free to do so without fear of subsequent demands for royalties.

The “LBNL” clause to which you refer is also pretty standard, though mostly seen in the contributor agreement. Basically, it simply states that you cannot hold LBNL liable if you contribute a code, and then later decide you shouldn’t have done so. I see this in most projects to which I contribute.

You should certainly have the approval of your employer before contributing to any open source project, regardless of license or agreement. Employers are pretty fussy about that, in my experience.

**Comment by loveshack** [comment]
rhc54 notifications@github.com writes:

> I’m honestly rather surprised by all the angst expressed by a couple
> of folks on the list regarding the license.

The problem is not the licence per se, but mis-representing it and, as I
see it, copyright law.  It seemed appropriate to treat that as a bug.

> There is nothing
> specifically onerous about it, and I’ve seen this language in the
> combination of license + contributor agreement rather frequently. The
> split between what appears in the license itself vs the contributor
> agreement varies, but the overall content is the same.

Maybe, but that seems legally confused to me as a layman who has had to
deal with such things.

> You cannot “own” copyright in something you contribute to a 3-clause
> BSD project.

Please quote an actual legal opinion in support of that, at least in
respect of US or UK law.  (I have actually read the UK Act and
amendments for my sins.)  If it's true, why are there all those
copyright notices in Open MPI?

I'm particularly objecting to these apparent statements of legal fact
which fly in the face of the legislation that affects me and actual
legal advice (like the FSF's).

> Once you contribute it, the project must remain free to
> distribute it without asking your permission. Likewise, anyone who
> uses it must be free to do so without fear of subsequent demands for
> royalties.

Yes, I can provide that licence iff I hold the copyright (or,
presumably, act for someone who does).

> The “LBNL” clause to which you refer is also pretty standard,

I've not seen it in any other licence, though I haven't gone through the
Fedora list, for instance.

> though
> mostly seen in the contributor agreement. Basically, it simply states
> that you cannot hold LBNL liable if you contribute a code,

It doesn't say so that I can see.  It says "make ... available", not
necessarily directly to LBNL, and doesn't seem to have any other
disclaimer.

> and then
> later decide you shouldn’t have done so. I see this in most projects
> to which I contribute.

Either you had a right to grant the licence, and presumably can't
rescind it -- per US court cases -- or you didn't.  I think you're less
likely to be able to grant a licence that allows removal of notices, for
instance, and definitely less so to a project that has this
interpretation of copyright.

> You should certainly have the approval of your employer before
> contributing to any open source project, regardless of license or
> agreement. Employers are pretty fussy about that, in my experience.

Amongst other things, the UK Act makes a distinction between work in the
course of employment and work whilst employed (or wording to that
effect).

**Comment by rhc54** [comment]
I've said this repeatedly, and frankly am getting a little tired of repeating it. Nobody in these conversations is a lawyer nor has any legal standing in this discussion. So let's quit the pointless argument. If you want to contribute and are concerned about the license language, then take it to an appropriate lawyer (your employer or otherwise) and get an opinion.

Quit beating up on Greg and the rest of us about it. As you stated in the email thread, enough!

**Comment by loveshack** [comment]
rhc54 notifications@github.com writes:

> I've said this repeatedly, and frankly am getting a little tired of
> repeating it. Nobody in these conversations is a lawyer nor has any
> legal standing in this discussion.

Which is why it's a concern when they make unsupported
definitive-looking statements about copyright law that contradict actual
legal opinion and imply that it's not legitimate to refer to it.

> So let's quit the pointless
> argument. If you want to contribute and are concerned about the
> license language, then take it to an appropriate lawyer (your employer
> or otherwise) and get an opinion.

It's not even worth making bug reports if they're closed without even
addressing the subject.

This issue was not about the licence, though LBNL legal are reported to
have said the web page misrepresents it, as originally raised.  Also I'm
seeking distribution legal opinion out of concern for a potential trap
for contributors, but that's only concern for the distribution, not the
subject of this.

It should be clear I want to contribute, but after the fact I find that
contributions are apparently treated contrary to copyright legislation
and legal opinion with which I'm familiar or actually has.  [BSD
licensing even has a certain historical significance.]  That stops me
contributing (not just to Singularity) and I'd guess it will stop others
who are aware of it and specific or general legal advice to FOSS
maintainers.  It may also mislead, which bothers me.  I thought that
would be a concern, and I hoped it was a misunderstanding which could be
corrected; obviously not.

To record a published reference, here's an example from the Software
Freedom Law Center addressing software copyright in the US and EU
https://softwarefreedom.org/resources/2007/originality-requirements.html.

> Quit beating up on Greg and the rest of us about it. As you stated in
> the email thread, enough!

I am not "beating up" on anyone, and apologize if I've said anything
personal in a negative way.  However, I could claim at least to be
tricked as a contributor -- perhaps not in a way that matters, though it
could.  I don't know where I said "enough", but unfortunately that is
enough as far as contributing.

**Comment by gmkurtzer** [comment]
@loveshack "Which is why it's a concern when they make unsupported definitive-looking statements about copyright law that contradict actual legal opinion and imply that it's not legitimate to refer to it."

The "they" you are referring to is me. If you feel that I am in error pertaining to copyright law in some way then please reference it specifically so it can be corrected. If I have already corrected it, then there is no point in further discussions of the matter.

Thank you.

**Comment by yarikoptic** [comment]
and was fixed with bba0fff93b7f27f2d5cd6bda08cefdcdadcf4a7c awhile back ;-)
