### ISSUE TITLE
singularity pull --name replaces extension with simg whatever extension we request

### ISSUE THREAD

**Issue by cokelaer** [apptainer/singularity#1171]
## Version of Singularity:

2.4

### Expected behavior

When using the *pull* command we can provide the --name argument so as to ename the container with a filename and an extension.

### Actual behavior

The extension is always renaming the file with the *simg* extension

### Steps to reproduce behavior
```
singularity pull --name container.image  shub://whatever
```
the download file is named container.simg

**Comment by vsoch** [comment]
Hey @cokelaer ! Could you check that you aren't possibly using old python files / installation? This was definitely fixed with a previous PR: https://github.com/singularityware/singularity/pull/1101. Could you try from development? I just installed and did a wacky image name:

```
singularity pull --name whaa.img.gz docker://ubuntu
```
and it came out ok :)

```
Building Singularity FS image...
Building Singularity SIF container image...
Singularity container built: ./whaa.img.gz
Cleaning up...
Done. Container is at: ./whaa.img.gz
```

**Comment by vsoch** [comment]
and the equivalent for singularity hub

```
singularity pull --name whaa.image shub://vsoch/hello-world
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/Documents/Dropbox/Code/singularity/singularity/whaa.image
```

**Comment by GodloveD** [comment]
Hey @cokelaer and @vsoch I think this is fixed right?  Are we able to close?

**Comment by vsoch** [comment]
I tested above and thought was fixed, and was waiting for @cokelaer to re-test (and possibly make sure not old files being used) before closing.

**Comment by cokelaer** [comment]
@vsoch okay this works for me. It ,was working on my system but not on our cluster because the version was indeed too old, which has been updated now and gives the expected output. 

I'm closing this issue. thanks.

**Comment by vsoch** [comment]
Very welcome! :O)
