### ISSUE TITLE
Singularity Image Permission Chenage

### ISSUE THREAD

**Issue by dinesh121991** [apptainer/singularity#1172]
## Version of Singularity: 2.2

2.2

### Expected behavior

It should atleast in readonly access to all the users..

### Actual behavior

1) Singularity image is not created and bootstrap by no-priviledged users
rajagopald@rd-admin 2.2]$ /home/rajagopald/Install/bin/singularity bootstrap user-test.img centos-7-cuda.def
ERROR  : User namespace not supported, and program not running privileged.
ABORT  : Retval = 255
[rajagopald@rd-admin 2.2]$

2) Singularity image is created & bootstrapped in the “root” user, and it is accessible afterwards by root only, How can I make that access by all members. I am using 2.2 version.

[dineshkr@ns54 ~]$ singularity run /home_nfs/home_dineshkr/CloverLeafMpi/centos-7-clover-leaf-mpi.img
ERROR  : Singularity must be executed in privileged mode to use images
ABORT  : Retval = 255
[dineshkr@ns54 ~]$ singularity shell --writable /home_nfs/home_dineshkr/CloverLeafMpi/centos-7-clover-leaf-mpi.img
ERROR  : Singularity must be executed in privileged mode to use images
ABORT  : Retval = 255
[dineshkr@ns54 ~]$ singularity shell /home_nfs/home_dineshkr/CloverLeafMpi/centos-7-clover-leaf-mpi.img
ERROR  : Singularity must be executed in privileged mode to use images
ABORT  : Retval = 255
[dineshkr@ns54 ~]$ ls CloverLeafMpi/
centos-7-clover-leaf-mpi.img  clover.in.tmp  clover_leaf_openmpi
clover.in                     clover_leaf    clover.out
[dineshkr@ns54 ~]$ ls CloverLeafMpi/ -al
total 2836352
drwxrwxrwx.  2 dineshkr bull       4096 Nov 23 15:31 .
drwxr-xr-x. 26 dineshkr bull       4096 Nov 23 15:38 ..
-rwxrwxrwx.  1 dineshkr bull 2902458400 Nov 23 15:39 centos-7-clover-leaf-mpi.img
-rwxrwxrwx.  1 dineshkr bull        348 Nov 23 15:31 clover.in

**Comment by gmkurtzer** [comment]
Singularity itself was not installed correctly, or it is installed to a shared file system that has the `nosuid` mount option enforced.

Try to install Singularity to the host's operating system directly using RPM or Deb packages.

**Comment by gmkurtzer** [comment]
Note: you can also run `singularity selftest` to verify your installation, but this will not identify if you are running Singularity on an shared file system with `nosuid` enforced.

**Comment by bauerm97** [comment]
Hey @dinesh121991, I'm going to assume that your issue has been fixed since we haven't heard from you in a while. If you still need some more help, please feel free to re-open the issue and mention one of us and we'll look into it further. Thanks!
