### ISSUE TITLE
RHEL6 kernel too old for singularity-2.4.1

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#1174]
## Version of Singularity:

2.4.1 on RHEL6

### Expected behavior

singularity exec or run will start up with default configuration.  I compiled the 'release-2.4' branch and tested it on November 22 as requested, but the [code that breaks](../commit/f2d7795d04bad5af371c3a4a0a6f372ba07ff810) was added on November 23, the day of the release.    Isn't that a bit ridiculous?

### Actual behavior

ERROR   [U=3382,P=22233]   singularity_daemon_init()                 Instance feature is disabled, your kernel is too old
ABORT   [U=3382,P=22233]   singularity_daemon_init()                 Retval = 255

### Steps to reproduce behavior

Build an rpm on rhel6 or install the [version built for OSG](https://koji.chtc.wisc.edu/koji/buildinfo?buildID=11349), and try to use the exec or run command with any unpacked image.  From that link you can also click on "build logs" and "build.log" to see the output of the configure and build process.

**Comment by DrDaveD** [comment]
No wait I mis-interpreted things, sorry.  November 22 was the release date, and that was the timestamp I was looking at.  The November 23 commit appears to be a fix for the problem, I am closing this while I investigate.  There does not appear to be another issue or pull request about this problem, not that I've been able to find.

**Comment by DrDaveD** [comment]
For the record, I found the discussion in the [google group](https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/qhci5p_syMM).

@gmkurtzer Please use pull requests for all your own changes!  That will do better travis checking and make it easier for someone to discover why changes were made.

**Comment by DrDaveD** [comment]
For the record, this is the actual [commit that caused the failure](../commit/2fca87581a123463b3d91648d06a60d9187e51a0) and it was slipped in on the day of the release and everybody was not asked to re-test.  The one person that was asked to re-test did not reply before the release was cut.  Not good quality control!

**Comment by olifre** [comment]
I fully agree, and maybe to add on this: It would also be nice if the CentOS 6 test in travis actually *did something* (at least run singularity with a minimal container) instead of only trying to compile it.
Looking at:
https://travis-ci.org/singularityware/singularity/jobs/305994038
I find:
```
the test suite has not yet been ported to centos6 python, skipping.
```
That basically means the only thing which is tested for CentOS 6 (which is the main platform for which Singularity is interesting, since for more modern environments, more full-grown container solutions exist) is basic compilation.
