### ISSUE TITLE
Run container in background

### ISSUE THREAD

**Issue by supermanhuyu** [apptainer/singularity#1175]
## Version of Singularity: 

2.3 or 2.4

### Expected behavior

Write here.

### Actual behavior

Write here.

### Steps to reproduce behavior

how can i run singularity container in background like docker's  -d/--detach
 thanks

**Comment by cclerget** [comment]
@supermanhuyu Singularity 2.4 add instance support which should respond to your needs, you can take a look at the documentation: http://singularity.lbl.gov/docs-instances

**Comment by bauerm97** [comment]
Hi @supermanhuyu, this functionality should already exist in Singularity. I'm going to go ahead and close this issue as @cclerget has posted where you can find the documentation on it. If you need further help, feel free to open a new issue or re-open this one. Thanks!
