### ISSUE TITLE
Can't -w the image: --overlay isn't recognized, Unable to open squashfs image in read-write mode: Read-only file system

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#1179]
## Version of Singularity:
2.4.1-dist  (from Debian experimental)

### Actual behavior

Did `sudo singularity pull docker://neurodebian:artful` to get the image (needed sudo as it was reported in another issue, since otherwise singularity would claim to be unable to find /bin/sh)

Now I need to apt-get update etc it.

```shell
$> singularity run  ./neurodebian-artful.simg       

#1 !2681 [0].....................................:Wed Nov 29 13:59:44:.
hopa(neurodebian-artful.simg):~
$> exit  # runs ok
2 10271.....................................:Wed 29 Nov 2017 08:59:45 AM EST:.
hopa:/srv/singularity
$> sudo singularity run -w ./neurodebian-artful.simg       
ERROR  : Unable to open squashfs image in read-write mode: Read-only file system
ABORT  : Retval = 255
2 10272 ->255.....................................:Wed 29 Nov 2017 08:59:57 AM EST:.
hopa:/srv/singularity
$> sudo singularity run -w --overlay ./neurodebian-artful.simg 
USAGE: singularity [...] run [run options...] <container path> [...]
...
    -o|--overlay        Use a persistent overlayFS via a writable image
...
```

could well be a user error, but `--overlay` seems to be listed and not requiring any value, why all the --help output?

**Comment by bauerm97** [comment]
Ahh I think this is a documentation error. As I understand `--overlay`, the syntax should be 
`--overlay <overlay directory>`. In your case (assuming you create a directory in your current directory named `overlaydir`), you could run the command as follows:

`sudo singularity run -w --overlay ./overlaydir ./neurodebian-artful.simg`

Let me know if that works. I'll go and update the documentation to make sure it accurately reflects the use case.

**Comment by yarikoptic** [comment]
yeap -- re --overlay, documentation issue:
```
$> sudo singularity run -w --overlay ./overlay_dir ./neurodebian-artful.simg 
ERROR  : Unable to open squashfs image in read-write mode: Read-only file system
ABORT  : Retval = 255
```

**Comment by bauerm97** [comment]
Again, we appear to have lapsed in our documentation of both the `--overlay` and `--writable` option. We will be putting out a 2.4.2 update soon and I will make sure that we clarify the use cases in the documentation. To explain it to you here:

The `--writable` option is intended to mount the base container image (in this case `neurodebian-artful.simg`) in read write mode. The `--overlay` option is intended to allow changes to a read-only filesystem by persisting those changes into the specified directory. The reason your command is failing is because you are providing `-w` to a read-only image. In my previous comment, I didn't notice this and just blankly copied and pasted your command (sorry!!).

Anyway, try this command:

`sudo singularity run --overlay ./overlaydir ./neurodebian-artful.simg`

Using *that* command, you should be able to make any changes which will be persisted in your overlaydir.

**Comment by yarikoptic** [comment]
Thank you @bauerm97 -- it is all very lovely! I see myself already adding various overlays on top of core image this way.
For completeness -- is there a way to convert this R/O image into R/W image so I could extend/tune it itself without relying on overlays?

**Comment by yarikoptic** [comment]
oh, right after my high appraisal, a show stopper ;):
```shell
$> singularity run --overlay ./overlay_dir ./neurodebian-artful.simg     
ERROR  : Only root can use directory based overlays
ABORT  : Retval = 255
```
so I guess I have to modify the image itself -- the idea is not to need root

**Comment by GodloveD** [comment]
Hey @yarikoptic what about using image based overlays?  You can use the `image.create` command to create an ext3 file system in an image and then use that as your overlay.  I don't think you need to be root to do that.

**Comment by yarikoptic** [comment]
@GodloveD thanks -- overlay file worked.
the question remains though -- is there a way to convert ready-only image obtained from import from docker to something I could modify as I could do with previous versions?
I see only
```
IMAGE GROUP COMMANDS:

    image.create    Create an image
    image.import    Import data into an image
    image.expand    Expand an image
    image.export    Export the contents of an image
```
so nothing like `image.convert`...?

**Comment by GodloveD** [comment]
Hi @yarikoptic.  Sorry for the delay.  When building the image from Docker Hub or Singularity Hub you could pass the `--sandbox` option.  Something like this:
```
singularity build --sandbox lolcow docker://godlovedc/lolcow
``` 
Or if you have already built the image from Docker or Singularity Hub and it is sitting on a local disk, you can use the `build` command to convert it from one format type to another.  Like this:
```
singularity build --sandbox new old.simg
``` 
Check the [build page](http://singularity.lbl.gov/docs-build-container) for more examples.

**Comment by yarikoptic** [comment]
super, thanks @GodloveD, will check it all out!

**Comment by roastercode** [comment]
That does not correct the trouble that -w does not works
