### ISSUE TITLE
bindpoint 

### ISSUE THREAD

**Issue by blythed** [apptainer/singularity#1182]
## Version of Singularity:

2.4-dist

### Expected behavior

nvidia-smi works as expected

### Actual behavior

$ singularity shell --nv --bind torch.img

WARNING: Skipping user bind, non existent bind point (file) in container: '/usr/bin/nvidia-smi'
Singularity: Invoking an interactive shell within container...

Singularity torch.img:~> nvidia-smi
bash: nvidia-smi: command not found

### Steps to reproduce behavior

Thu Nov 30 10:54:17 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.51                 Driver Version: 375.51                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |

Bootstrap: docker
From: docker://tensorflow/tensorflow:latest-gpu

%post
	pip install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp27-cp27mu-manylinux1_x86_64.whl 
	pip install torchvision

**Comment by dtrudg** [comment]
What is OS of the host machine? Warning suggests perhaps it is a machine without overlayfs available?

**Comment by blythed** [comment]
Linux zdc-lxslurm11 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by GodloveD** [comment]
Heya @blythed it looks like you are not using legal syntax.  The `--bind` option requires an argument.  Could this be causing your issue?

**Comment by zhcf** [comment]
I aslo meet this problem(centos 7.3). the workaround is to add one empty nvidia-smi file under /bin in the container. Then you can use it.
Hope it will work for you.

**Comment by dtrudg** [comment]
Hi @zhcf - that's a bit unusual to see on CentOS 7.3 - if you have to create the bind point `nvidia-smi` in the container it suggests overlayfs is either not available to you, or disabled. Do you happen to know if this is the case?

**Comment by negrinho** [comment]
I'm facing the same problem. I will try the solution mentioned above. Running 
`singularity shell --nv darch-py27-gpu.img` yields `WARNING: Skipping user bind, non existent bind point (file) in container: '/usr/bin/nvidia-smi'`.

Operating system on the server:
```
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.9 (Final)
Release:	6.9
Codename:	Final
```
Is using `--nv` flag the correct way of getting GPU support for the container or are there alternatives?

**Comment by dtrudg** [comment]
Hi @negrinho - as CentOS 6.x doesn't support overlayfs you would have to add a stub (empty file) into the container at '/usr/bin/nvidia-smi' for `nvidia-smi` to be mounted in successfully.

However - this message is just a warning. In most cases the libraries are bound in correctly, and you do have GPU support. `--nv` is the correct option and GPU programs should work fine even if you see this warning.

**Comment by negrinho** [comment]
Thanks for the quick reply. I was getting `bash: nvidia-smi: command not found` in this case though. Will adding the stub make it work in both cases, i.e., with and without overlays?

**Comment by jscook2345** [comment]
@blythed @negrinho @zhcf 

With the 3.0 rewrite, this feature should be working. I'd be interested in hearing if you still have the issue with the 3.0 release. Please let me know!

**Comment by zhcf** [comment]
no issue, it works in 3.0

**Comment by jscook2345** [comment]
@zhcf 

I appreciate the update. I'm going to close this issue for now, but if you (or anyone else) have other questions please comment here or open another issue. Thanks!
