### ISSUE TITLE
pull images from ngc.nvidia.com

### ISSUE THREAD

**Issue by shahzebsiddiqui** [apptainer/singularity#1183]
## Version of Singularity:
2.4

### Expected behavior
Should be able to pull container via singularity pull

Write here.

### Actual behavior
```
[siddis14@amrndhl1157 ~]$ singularity pull docker://nvcr.io/nvidia/caffe:17.11
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
ERROR Unrecognized authentication challenge, exiting.
Cleaning up...
```

Setting environment variables with API key as password

```
[siddis14@amrndhl1157 ~]$ env | grep SINGULARITY
SINGULARITY_DOCKER_PASSWORD=anF0cjBmaXZkZTNvdWVlYTN0NGZhcGhxYWg6MDg1YjQxNmItYTY0ZC00NjYyLThjMzAtYmFjMmNiZWU4YmEz
SINGULARITY_DOCKER_USERNAME=shahzeb.siddiqui@pfizer.com

[siddis14@amrndhl1157 ~]$ singularity pull docker://nvcr.io/nvidia/caffe:17.11
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
ERROR Unrecognized authentication challenge, exiting.
Cleaning up...

```

I am not sure what needs to be done when creating a token, the documentation needs more explanation

```
CREDENTIAL=$(echo -n vanessa:[password] | base64)
TOKEN=$(http 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:vanessa/code-samples:pull' Authorization:"Basic $CREDENTIAL" | jq -r '.token')
```
### Steps to reproduce behavior

Please register at ngc.nvidia.com and follow instructions accordingly.

**Comment by vsoch** [comment]
We've been working on this already and @jtriley has a PR solution. The Nvidia cloud flow is completely different than standard docker so the answer is not just in generating a token.

**Comment by jtriley** [comment]
Yep I'm submitting a PR as we speak. Would love some testing once it's up. @shahzebsiddiqui I would recommend regenerating your API token if that value above is real :smile:

**Comment by jtriley** [comment]
@shahzebsiddiqui PR is open if you'd like to test ^^

**Comment by nouiz** [comment]
We tried this PR and it didn't work. Was someone able to make it work? We would really like this to be working.

**Comment by vsoch** [comment]
hey @shahzebsiddiqui if you'd like to try this with the sregistry client:

```
sregistry pull nvidia://nvidia/caffe:17.11
```
And install from development. Thanks!

**Comment by shahzebsiddiqui** [comment]
@vsoch this works you can close this issue

**Comment by vsoch** [comment]
woohoo! Closing!
