### ISSUE TITLE
Is it possible to set a $PATH for images from within the image?

### ISSUE THREAD

**Issue by cjprybol** [apptainer/singularity#119]
It seems that the $PATH for images is set from within the `singularity/etc/init` file, rather than from within the image itself, and thus is dependent on the host system rather than being portable with the image.

``` bash
vagrant@jessie:~$ sudo singularity --debug shell -w --contain test.img
enabling debugging
ending argument loop
+ '[' -f /usr/local/etc/singularity/init ']'
+ . /usr/local/etc/singularity/init
++ unset module
++ PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

entering into the shell in the image and editing /etc/profile, ~/.profile, and ~/.bashrc all had no (permanent) effect on the $PATH. I can source them from within the shell session, but it doesn't seem that the /bin/sh dash that is invoked makes any calls to those configuration files upon launching the shell. The easy workaround for this is to just symlink everything to /usr/bin that isn't installed there by default, or call the full path, but is there a way to set a unique $PATH for additional software installation locations within the image itself?

Two examples of things I would like to package into images, and where this becomes a problem, are the anaconda distribution of Python and linuxbrew. Both have their own independent /bin folders, and symlinking the executables to the system /bin folders may not be possible due to version conflicts and duplicates between the system /bin folders and the software /bin folders

an example of what I'm trying to get to work is

``` bash
sudo singularity shell -w --contain test.img
cd $HOME
apt-get update
apt-get install -y wget build-essential
wget http://repo.continuum.io/archive/Anaconda3-4.1.0-Linux-x86_64.sh
bash Anaconda3-4.1.0-Linux-x86_64.sh -b -p $HOME/anaconda3
## modify $PATH to include $HOME/anaconda3/bin
exit
## using full path works
sudo singularity exec -C test.img /root/anaconda3/bin/python
## trying to get this to work
sudo singularity exec -C test.img python
```

**Comment by gmkurtzer** [comment]
Ahh, this is an interesting thing indeed and was wondering when someone would notice! lol

At present, when you invoke 'shell' and if '/bin/bash' exists, it passes the arguments --norc and --noprofile. This is necessary because typically the user's home directory is mounted which means if we source their dotfiles, then things that work outside the container may fail when entering inside the container (e.g. environment modules). 

We need a way of injecting some environment and other necessary bits into the container. Perhaps something like a script called /entry or /env(ironment) that can include these sorts of things?

Thoughts?

**Comment by cjprybol** [comment]
I can see how that can get tricky very quickly. I'm still mind blown that the containers and the local system can interact at all!

I noticed that when I tried to run that same final python invocation without the `-C` option, the command failed because it was looking for the executable on the host system at `/root/anaconda3/bin/python` rather than in the container at that path.

```
vagrant@jessie:~$ sudo singularity exec test.img /root/anaconda3/bin/python
ERROR  : execvp of '/root/anaconda3/bin/python' failed: No such file or directory
vagrant@jessie:~$ sudo singularity exec -C test.img /root/anaconda3/bin/python
Python 3.5.1 |Anaconda 4.1.0 (64-bit)| (default, Jun 15 2016, 15:32:45)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

I haven't the slightest clue where to start on this, but I think what I'm envisioning is the ability to regulate the $PATH for executables and the $PATH for disk IO separately. A quicker solution might be to make a restricted keyword, like $CONTAINERHOME to distinguish host $HOME from container $HOME. Maybe adding a 3rd option to the `singularity exec` command

```
EXEC OPTIONS:
    -w/--writable   By default all Singularity containers are available as
                    read only. This option makes the file system accessible
                    as read/write.
    -C/--contain    This option disables the automatic sharing of writable
                    filesystems on your host (e.g. $HOME and /tmp).
    -I/--isolate_executables  This option will replace the $PATH of host with the
                    $PATH of the image when looking for executables to run. If the
                    executable is not found within the container, the program will fall back
                    to the host system, and will throw a warning, but will proceed if found
                    on host
```

**Comment by gmkurtzer** [comment]
Yes, that is a technical complexity about installing anything into a contained home directory. While /root maybe different because it is a standard user and a standard location, I would caution against ever installing into a home directory. Think of the container as a compute node or another system mounting various directories from a network file system.

I agree that there should be a method for adding or manipulating PATHs from the container.. I noticed something that might work for /bin/bash and I will test... Bash has an --init-file argument which I can specify to be the container's /etc/bashrc, this way all of the appropriate shell environment bits will be automatically read and included in the container's shell.

Lastly, I'm not sure how I can isolate executables or rather differentiate executables between container and host except for PATH. And if done correctly, there shouldn't be any host executables available in any of the container's default PATH directories... But let me check into that.

Thanks!

**Comment by cjprybol** [comment]
> I would caution against ever installing into a home directory. Think of the container as a compute node or another system mounting various directories from a network file system.

Could you clarify that? Rather than don't install things into the home directory of the container, do you mean don't treat the home directory of the container like an isolated $HOME? As containers are essentially an extension of the local system, I can see how trying to use variables like $HOME to represent the `/root` directory in the container is a bad (terrible) idea. It's unresolveable which $HOME is meant in that case. But if I shouldn't install things to the `/root` directory of the image, then what location is the best for where to install software into the container?

Also, the following is working beautifully, which is what I was trying to do.

``` bash
vagrant@jessie:~$ singularity exec -C test.img /root/anaconda3/bin/python
Python 3.5.1 |Anaconda 4.1.0 (64-bit)| (default, Jun 15 2016, 15:32:45)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```

I'll now continue working on an example of using singularity to run a reproducable analysis (documentation of a use case)!

But back to the topic of the issue.

I was interested in the use of the container's dash shell located at `/bin/sh` rather than the more full featured bash shell. Reading up on it, I saw that dash is the default shell on Debian and Ubuntu [source](https://wiki.ubuntu.com/DashAsBinSh) [although, if you ran a terminal on Debian or Ubuntu, you'd still get served up a bash shell]. Being a subset of the capabilities of bash, it's also faster to load, which I assume was an intentional design choice? That would ensure that singularity has as little overhead as possible when jobs are launched.

So, with that in mind,  when you say

> I noticed something that might work for /bin/bash and I will test... Bash has an --init-file argument which I can specify to be the container's /etc/bashrc, this way all of the appropriate shell environment bits will be automatically read and included in the container's shell.

Would the transition to bash rather than dash incur an overhead that you are worried about? If it's a negligable difference on startup times, and extends the capabilties of how singularity can call and interact with the container to make things much easier, then I'm all for it (and happy to try and test a few things to try and get it working!). But if you'd like to keep the dash shell, could you just drop the `--noprofile` call and enable loading the `/etc/profile` and `~/.profile`? Or do you specifically want to use the functionality of `--init-file` in bash, which would remove the worry about what may be in the `/etc/profile` or `~/.profile` files by default? Making a new file called by singularity such as `/etc/singularity.profile` and instructing users to put all extensions to the `$PATH` into that would eliminate any worries about what may be the default `/etc/profile` or `~/.profile` on different OSes that may be bootstrapped into containers. For example, the `~/.profile` on debian may end up loading the `~/.bashrc` anyway, even if you pass the `--norc` option because it's in the `~/.profile` script

``` bash
Singularity/test.img> cat ~/.profile
# ~/.profile: executed by Bourne-compatible login shells.

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

mesg n
```

**Comment by gmkurtzer** [comment]
On Thu, Jul 7, 2016 at 1:57 PM, Cameron Prybol notifications@github.com
wrote:

> I would caution against ever installing into a home directory. Think of
> the container as a compute node or another system mounting various
> directories from a network file system.
> 
> Could you clarify that? Rather than don't install things into the home
> directory of the container, do you mean don't treat the home directory of
> the container like an isolated $HOME? As containers are essentially an
> extension of the local system, I can see how trying to use variables like
> $HOME to represent the /root directory in the container is a bad
> (terrible) idea. It's unresolveable which $HOME is meant in that case. But
> if I shouldn't install things to the /root directory of the image, then
> what location is the best for where to install software into the container?

I would generally recommend installing packages into the operating system
directories (/usr/bin, /usr/local/bin, etc..). For example, typically /root
is unreadable by non-root users, so installing files there defies some of
the standard conventions. I would treat a container like a small
mini-stand-alone system. Also, keep in mind (as you've noticed) one good
general practice is that the user's home (or root's), maybe unknown and
variable depending on who is using the container, and directories (e.g.
$HOME) may get "overmounted" when/if used by other users and thus may
require the use of --contain. If you installed to /usr/local, --contain
would not be necessary.

> Also, the following is working beautifully, which is what I was trying to
> do.
> 
> vagrant@jessie:~$ singularity exec -C test.img /root/anaconda3/bin/python
> Python 3.5.1 |Anaconda 4.1.0 (64-bit)| (default, Jun 15 2016, 15:32:45)
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
> Type "help", "copyright", "credits" or "license" for more information.>>> exit()
> 
> I'll now continue working on an example of using singularity to run a
> reproducable analysis (documentation of a use case)!

Oh fantastic! The more the use-cases, the better!!!

> But back to the topic of the issue.
> 
> I was interested in the use of the container's dash shell located at
> /bin/sh rather than the more full featured bash shell. Reading up on it,
> I saw that dash is the default shell on Debian and Ubuntu source
> https://wiki.ubuntu.com/DashAsBinSh [although, if you ran a terminal on
> Debian or Ubuntu, you'd still get served up a bash shell]. Being a subset
> of the capabilities of bash, it's also faster to load, which I assume was
> an intentional design choice? That would ensure that singularity has as
> little overhead as possible when jobs are launched.
> 
> So, with that in mind, when you say
> 
> I noticed something that might work for /bin/bash and I will test... Bash
> has an --init-file argument which I can specify to be the container's
> /etc/bashrc, this way all of the appropriate shell environment bits will be
> automatically read and included in the container's shell.
> 
> Would the transition to bash rather than dash incur an overhead that you
> are worried about? If it's a negligable difference on startup times, and
> extends the capabilties of how singularity can call and interact with the
> container to make things much easier, then I'm all for it (and happy to try
> and test a few things to try and get it working!). But if you'd like to
> keep the dash shell, could you just drop the --noprofile call and enable
> loading the /etc/profile and ~/.profile? Or do you specifically want to
> use the functionality of --init-file in bash, which would remove the
> worry about what may be in the /etc/profile or ~/.profile files by
> default? Making a new file called by singularity such as
> /etc/singularity.profile and instructing users to put all extensions to
> the $PATH into that would eliminate any worries about what may be the
> default /etc/profile or ~/.profile on different OSes that may be
> bootstrapped into containers. For example, the ~/.profile on debian may
> end up loading the ~/.bashrc anyway, even if you pass the --norc option
> because it's in the ~/.profile script
> 
> Singularity/test.img> cat ~/.profile# ~/.profile: executed by Bourne-compatible login shells.
> if [ "$BASH" ]; then
>   if [ -f ~/.bashrc ]; then
>     . ~/.bashrc
>   fifi
> 
> I think I'm following what you are saying here, and I think the best
> solution would be to define an "entry point" for a particular container. I
> can do this either via a command line argument to the 'shell' command or
> via a container specific configuration (neither available at present). At
> the moment, what happens is that Singularity checks the container for
> /bin/bash, if it does not exist it uses /bin/sh. In either case we still
> have the issue of dotfiles specific on the host not being compatible in the
> container. For example... the default ~/.profile does redirect to
> ~/.bashrc, and ~/.bashrc loads /etc/profile.d/*.sh. But... if the first two
> dotfiles also have host specific info in them (e.g. loads environment
> module commands), then it errors out within a container context.

I think having an entry point configuration will alleviate this, and it can
very easily be set via an environment variable as well as a 'shell'
argument.

Hopefully all of this makes sense! LOL

**Comment by cjprybol** [comment]
Yes! That does all make sense. Thank you for the explanation!

**Comment by gmkurtzer** [comment]
RFE: Add entrypoint command argument and envar for shell invocation.

**Comment by gmkurtzer** [comment]
I was thinking about this (after I mostly implemented it), that adding an option to define the entrypoint is basically the same thing as just using the 'exec' subcommand.

For example:

$ singularity shell --entry=/usr/bin/python container.img --version

Is functionally the same as:

$ singularity exec container.img /usr/bin/python --version

But more convoluted. Is there something I am missing, or do you concur that this RFE is redundant?

Thanks!

**Comment by cjprybol** [comment]
I think our discussion may have sidetracked us away from the original intent I had for this issue. What I was hoping for was the ability to modify the $PATH from within the container. Going back to my first post, I led with this:

```
vagrant@jessie:~$ sudo singularity --debug shell -w --contain test.img
enabling debugging
ending argument loop
+ '[' -f /usr/local/etc/singularity/init ']'
+ . /usr/local/etc/singularity/init
++ unset module
++ PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

and pointed out that the PATH is being set by the singularity init file on the host system. What I would like to be able to do is have some sort of .profile file inside of the container that would be able to update the PATH using the usual syntax of

```
PATH="/path/to/nonstandard/install/location:$PATH"
export $PATH
```

The particular problem that I'm having is the redundancy of executables and the out of date nature of many libraries available via apt-get. For example, the python 2 and python 3 versions available via apt-get are 2.7.6 and 3.4.0. The current versions for those are 2.7.11 and 3.5.2. Same goes for other things such as Ruby, R, and the list goes on. `/bin` & `/usr/bin` are set before `/usr/local/bin` in the default singularity path, so even installing more current versions to `/usr/local/bin` won't enable me to call the current versions of executables by name alone. I would need to specify the full path to them. Which 100% makes this issue a convenience and enhancement request. The alternative would be to replace the libraries in `/bin` and `/usr/bin`, although I presume that would cause subtle breakage on things that expect the apt-get version of the libraries to be in those system directories.

I could also bypass this by editing the singularity init script to change the PATH, but then the calls wouldn't be replicable when the container is run on other clusters.

Given that you can't account for the default /etc/profile, ~/.profile, ~/.bashrc etc. contents on all systems that users may want to bootstrap into a singularity image (for example, I don't know if the /etc/profile file is the same on centOS as it is on Debian), I was thinking that reserving a namespace for the file would be a reasonable thing. `singularity run your_image.img` looks for a file in the container in the root folder called `/singularity`, and I was wondering if it would be possible to extend that concept to include something like `/singularity.profile` whereby a user could add things like aliases and PATH updates that they may be used to having on their own system

**Comment by gmkurtzer** [comment]
Thank you for coming back to this. Let me think of how to get this working and implement something before I make the 2.1 alpha release. 

Thanks again!!

**Comment by cjprybol** [comment]
I think you've got it backwards. I'm supposed to be the one thanking you! This is really great work you're doing. Very much looking forward to this feature, and I greatly appreciate your efforts to implement it!

**Comment by gmkurtzer** [comment]
This is getting complicated... Because what I want to do is invoke /bin/sh|bash with --rcfile or --init-file and point it somewhere like /.env. But, that will only be called when using the 'shell' subcommand because I am not spawning a shell otherwise. So I am investigating abstracting a bit such that when someone runs 'exec', 'run' or 'shell', it is actually calling the wrapper scripts /.exec, /.run, or /.shell respectively. Those scripts we can then have source /.env, which will work fine and give the expected results, but I don't like the convolution... With that said, I can't think of another way of doing it.

Thoughts?

**Comment by cjprybol** [comment]
That actually sounds great, but I don't understand the current inner-workings of singularity well enough to see the convolution. Would those /.exec, /.run, and /.shell scripts now have to be bundled in with the container, rather than existing with the singularity installation on the host?

I'm generally pro what will work, but if you think that fix would create more problems downstream than it fixes, feel free to close this issue for the time being and see if any other ideas come to mind in the future that would be more robust

**Comment by gmkurtzer** [comment]
So in the 2.1 testing release I have this implemented as I described above. Now if you want to define a custom environment for your container (a freshly built one) you simply edit the file /environment. 

Under the hood, there are launching wrapper scripts at /.shell, /.exec and /.run which will all source the /environment file. Hopefully that makes sense.

At your next opportunity if you can test it and make sure it works as you would expect it to and let me know that would be fantastic.

Thanks!

**Comment by cjprybol** [comment]
Bravo, this is great! Works exactly as I was imagining. Thank you!

I'm unsure why this is happening, but with the debian and ubuntu images it's claiming an unexpected operator

```
vagrant@jessie:~$ sudo singularity shell -w --contain test.img
/.shell: 3: test: /bin/bash: unexpected operator
```

I bootstrapped each from the defintion files at singularity/examples/[ubuntu|debian].def

and in the /environment file, this line

```
PS1="Singularity.$SINGULARITY_CONTAINER> PS1"
```

will result in a PS1 pileup

```
root@jessie:(unreachable)/home/vagrant# source /environment
Singularity.test.img> root@jessie:(unreachable)/home/vagrant# source /environment
Singularity.test.img> Singularity.test.img> root@jessie:(unreachable)/home/vagrant# source /environment
Singularity.test.img> Singularity.test.img> Singularity.test.img> root@jessie:(unreachable)/home/vagrant#
```

changing it to this may have the intended result?

```
PS1="Singularity.$SINGULARITY_CONTAINER> "
```

```
Singularity.test.img> Singularity.test.img> Singularity.test.img> root@jessie:(unreachable)/home/vagrant# source /environment
Singularity.test.img>
```

both seem to be only cosmetic, haven't found any breakage yet, and the new functionality is definitely there. Investigating the `/.shell: 3: test: /bin/bash: unexpected operator` error now

**Comment by gmkurtzer** [comment]
@cjprybol Once you are inside your container, can you send me the output of:

> sh -x /.shell

I am not sure the best way of handling the PS1 buildup... @yarikoptic, you have some awesome PS1-fu, do you have any ideas?

**Comment by cjprybol** [comment]
```
vagrant@jessie:~$ sudo singularity shell -w --contain test.img
/.shell: 3: test: /bin/bash: unexpected operator
root@jessie:(unreachable)/home/vagrant# sh -x /.shell
+ . /environment
+ PATH=.:/bin:/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin:/sbin
+ PS1=Singularity.test.img>
+ export PATH PS1
+ test -n /bin/bash -a /bin/bash == /bin/bash
/.shell: 3: test: /bin/bash: unexpected operator
+ test -n /bin/bash -a -x /bin/bash
+ exec /bin/bash
```

**Comment by gmkurtzer** [comment]
Oh, does it not like the double =?

Can you enter the container with --writable as root, and remove one of the '='s and see if that fixes it?

Thanks!

**Comment by cjprybol** [comment]
Yes, that seems to be it!

```
vagrant@jessie:~$ sudo singularity shell -w --contain test.img
Singularity.test.img> sh -x /.shell
+ . /environment
+ PATH=.:/bin:/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin:/sbin
+ PS1=Singularity.test.img>
+ export PATH PS1
+ test -n /bin/bash -a /bin/bash = /bin/bash
+ exec /bin/bash --norc --noprofile
```

**Comment by gmkurtzer** [comment]
Fantastic, I will commit that. Thanks!

**Comment by cjprybol** [comment]
changing the PS1 line in /environment works on ubuntu debian and centos. They all start with the right PS1 as you enter via the shell command regardless, but any time you source the /environment again, it'll continue to grow.

old

```
PS1="Singularity.$SINGULARITY_CONTAINER> $PS1"
```

proposed new

```
PS1="Singularity.$SINGULARITY_CONTAINER> "
```

```
[vagrant@localhost ~]$ sudo env "PATH=$PATH" singularity shell -w --contain test.img
Singularity.test.img> cat /environment
# Define any environment init code here
#

PATH=.:/bin:/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin:/bin:/sbin
PS1="Singularity.$SINGULARITY_CONTAINER> $PS1"
export PATH PS1
Singularity.test.img> source /environment
Singularity.test.img> Singularity.test.img> vi /environment

# remove $PS1

Singularity.test.img> Singularity.test.img> source /environment
Singularity.test.img> exit
exit
[vagrant@localhost ~]$ sudo env "PATH=$PATH" singularity shell -w --contain test.img
Singularity.test.img> source /environment
Singularity.test.img> cat /environment
# Define any environment init code here
#

PATH=.:/bin:/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin:/bin:/sbin
PS1="Singularity.$SINGULARITY_CONTAINER> "
export PATH PS1
```

and once a decision is made on that between you and @yarikoptic, I'm happy to close this!

**Comment by yarikoptic** [comment]
I am ok with anything @gmkurtzer decides with for his baby ;)  another possibility to avoid growth could possibly be something along the lines of

``` bash
if ! echo ${PS1:-} | grep -q Singularity; then
  PS1="Sing...
fi
```

?

**Comment by gmkurtzer** [comment]
@yarikoptic haha, thanks!

I actually do think I've got an interesting way to solve it; by using a toggle. It will pollute the environment a tad (but setting an envar), but then I can conditionally not reset PS1 over and over. I realize we are talking about thousandths of a second, but I was actually a bit grumpy about incurring an extra 3-5 thousandths by using these wrappers. Granted, the additional functionality achieved is well worth it! And of course Debian will be better because they don't use bash for /bin/sh, but it is still necessary invocation noise.

I'll give you something to test shortly @cjprybol!

**Comment by gmkurtzer** [comment]
@cjprybol Check out [master f42a920] and see if that stops the proliferation of PS1s!

Thanks!

**Comment by cjprybol** [comment]
It's working great!

**Comment by gmkurtzer** [comment]
Excellent, thanks @cjprybol!

**Comment by chrisgorgo** [comment]
Is there some documentation of this feature? I've tried adding /environment
to one of my containers, but it did not seem to be sourced.

**Comment by gmkurtzer** [comment]
Hi @chrisfilo, I haven't even had a chance to document it yet! Lol

In the most recent 2.1 prerelease, if you create a new container (bootstrap) it will include the appropriate wrappers and a template /environment file. 

Hope that helps and let me know if you have any issues with it. 

Thanks!

**Comment by chrisgorgo** [comment]
I'm trying this with containers converted from Docker. Do I need to include
some wrappers in addition to the /environment file?

**Comment by gmkurtzer** [comment]
Oh, that is an interesting point. This would be a feature of a Singularity Bootstrapped image, but we can easily add this step to the conversation from Docker to Singularity. Are you using Vanessa's conversion?

**Comment by chrisgorgo** [comment]
Yes I am!

**Comment by gmkurtzer** [comment]
I can also add a feature to include those files when doing an import. But, that won't make it into 2.1 at this point as it is locked for feature additions. It will however be put into master soon!

**Comment by chrisgorgo** [comment]
I fully understand! Deliveringa stable mature release is paramount for the
success of the project.

But maybe there is another way. How complex those wrappers are? Would it be
hard to add them to the docker2singularity.sh script?

**Comment by gmkurtzer** [comment]
It would be very easy for those scripts to simply do a post import bootstrap which can always be used to update an image or add functionality to an existing image. For example, just don't call Bootstrap in the definition file.
