### ISSUE TITLE
"Unknown image format/type" error when trying to boot non-singularity generated .img file

### ISSUE THREAD

**Issue by max-mapper** [apptainer/singularity#1192]
## Version of Singularity:

2.4.1-dist

### Expected behavior

I am trying to boot a `.img` that was created by a third party workflow (not generating using singularity). I was hoping I could use `singularity shell` to boot my `.img` file. I am using `systemd-nspawn` to boot my `.img` files, but I'd like to support singularity as a runtime as well. I saw singularity uses plain disk images with filesystems installed, and am wondering if I can make an image bootable in both `nspawn` and singularity.

### Actual behavior

```
$ sudo singularity shell container.img 
ERROR  : Unknown image format/type: container.img
ABORT  : Retval = 255
```

### Steps to reproduce behavior

Here's the process I used to create the `.img` files (I am using a tool called `mkcontainer` but it uses this approach):

``` sh
# make a ~1gb image
fallocate my-image.img -l 1000000000
# to simply make a single partition, follow this
fdisk my-image.img
n<enter>
<enter>
<enter>
<enter>
w<enter>
# note the Start sector
fdisk -l my-image.img
# change 2048 to the Start sector (usually 2048)
mkfs.ext4 -F -E offset=$((2048 * 512)) my-image.img
```

When using `mkcontainer` (https://github.com/mafintosh/mkcontainer/) it debootstraps a distro into the mounted .img file. You can then boot the image using `systemd-nspawn`. But when booting the .img with `singularity` you get the above error.

**Comment by gmkurtzer** [comment]
Singularity doesn't expect the partition table, and may also have a problem with ext4. We can easily support ext4 (granted, we never used ext4 internally because we have seen inconsistencies with not all distributions creating/supporting compatible ext4s) but supporting the partition table will take a bit more work.

**Comment by max-mapper** [comment]
@gmkurtzer ok thanks, should I open a separate issue for that? also, if I wanted to implement a workaround where I generated singularity-compatible images without partition tables, do you think that would be possible?

**Comment by gmkurtzer** [comment]
Hi @maxogden,

We can leave this issue open as an RFE. @yhcote, what is your take on this?

Yes, if you create singularity-compatible images without partition tables, I think that would work just fine. But I will mention as well that with the upcoming SIF format, you may want to call Singularity directly to create the image.

Hope that helps!

Greg

**Comment by yhcote** [comment]
Hi maxogden,

The problem with partitions in an image file is that the partprobe feature
of loopback devices in the kernel is fairly recent and would not work on
older kernels. Those offsets could be passed either via a command line
option or envvars, which should not be too much of a problem to implement.
I don't know what is a RFE, but if requested as a new feature, we would get
to it as soon as possible.

SIF in singularity 3.0 would allow you to have different system partitions
to use and mount but this would be different from the current format you
use.

Cheers,

 - Yannick

**Comment by max-mapper** [comment]
@yhcote Oh I see thank you, so singularity is going to move to it's own image format? I guess in the long term compatibly with disk images (and therefore nspawn/qemu) is off the table?

**edit** If possible can someone link me to the SIF on-disk specification so I can see if it's possible to write a third party client?

**edit2** nevermind, found it here: https://github.com/yhcote/singularity/blob/a4bf48dd0dbf6e12a876e6fa59c30b5e5f6f8871/src/lib/sif/sif.h

**Comment by yhcote** [comment]
I would not say off the table necessarily. The Singularity Image Format
(SIF) has a lot of advantage over simple partition tables and can carry a
lot more features and container data. That being said in theory it would
not be too difficult to let singularity mount disk images, especially if we
only support newer kernels (~3.1 and up).

We'll keep your request,

Thanks !

- Yannick
