### ISSUE TITLE
Define runtime mounts and --nv during bootstrap

### ISSUE THREAD

**Issue by Saford91** [apptainer/singularity#1197]
Can I specify a a bind mount in a container definition file that is then mounted when a container is executed? Can I do something similar with the --nv option?

Something like this:

```
Bootstrap: docker
From: tensorflow/tensorflow:latest-gpu
NvidiaLibs: yes

%bind
/foo/var /foo/bar

%runscript
exec python $@
```

**Comment by vsoch** [comment]
hey @Saford91 ! This is currently not possible, and if it were done, do you see any issue / danger when an unexpecting user would run the container and have it bind without knowing in advance? I would say a reasonable approach to try might be to have a runscript that does a check, and if the content that is expected is there, move forward. If not, instruct the user how to run it properly. Some method that would "pre-define" a bind point could also come from an executable wrapper around the image ( to hide the binding from the user ). If/when we get around to doing some kind of orchestration tool, this might be reasonable to add, and that would be akin to the wrapper around it.

**Comment by Saford91** [comment]
If a user ran a container that binds a directory unexpectedly, the container may access data that the user doesn't intend it to access. This is along the lines of "don't run software you don't trust". That said, the bind points are done with a SUID binary, so allowing images to freely bind directories has the potential to reach further than your typical user running untrusted software.

I was able to get the desired behavior by using an executable wrapper as you suggested. The advantage I see with allowing image defined bind mounts instead of using wrapper scripts is preserving flexibility in how that image is invoked e.g. run, exec, shell, etc. Perhaps this and other features can be allowed for only trusted or signed containers as a way to prevent abuse?

**Comment by dtrudg** [comment]
The `nv` option for build is a milestone item for 3.8. Binds in def files have been discussed several times, and haven't been implemented as it makes containers more system-specific.
