### ISSUE TITLE
using singularity shell and strace: ERROR: Singularity container is not installed

### ISSUE THREAD

**Issue by kforner** [apptainer/singularity#12]
Seems to do the same thing for all SAPPs I produced:

`%singularity run blastn.sapp -h`
=> works OK

but 

```
%singularity shell blastn.sapp
ERROR: Singularity container is not installed: blastn.sapp

%singularity shell $(pwd)/blastn.sapp
ERROR: Singularity container is not installed: blastn.sapp

%singularity shell $./blastn.sapp
ERROR: Singularity container is not installed: blastn.sapp

%singularity strace ./blastn.sapp 
ERROR: Singularity container is not installed: ./blastn.sapp
```

Did I miss something ?!

**Comment by gmkurtzer** [comment]
You have to first install the container into the environment:

$ singularity install name.sapp
$ singularity strace name
$ singularity shell name

Or it will automatically get installed into the container once you have run the container via:

$ singularity run name.sapp

Or

$ ./name.sapp

Hope that helps!

**Comment by kforner** [comment]
Sorry, but that does not work:

```
%singularity install ./blastn.sapp 
Singularity container is already installed: blastn (e8b733e0-91f4-4b8e-bafd-2d7420bf0450)
%singularity strace blastn.sapp 
ERROR: Singularity container is not installed: blastn.sapp
```

**Comment by gmkurtzer** [comment]
> Sorry, but that does not work:
> 
> %singularity install ./blastn.sapp 
> Singularity container is already installed: blastn (e8b733e0-91f4-4b8e-bafd-2d7420bf0450)
> %singularity strace blastn.sapp 
> ERROR: Singularity container is not installed: blastn.sapp
> 
> Nope, but this will:

% singularity strace blastn 

So will this:

% singularity strace e8b733e0-91f4-4b8e-bafd-2d7420bf0450

In my previous examples I removed the .sapp suffix when referring to the installed SAPP (with a single exception); the "run" command can take a .sapp file as well as a SAPP name or UUID because it has the dual logic of installing and running it on demand. 

Hope that helps!

**Comment by kforner** [comment]
oh right, my bad.
