### ISSUE TITLE
non docker hub pull of docker images

### ISSUE THREAD

**Issue by HelenCousins** [apptainer/singularity#1200]
## Version of Singularity:

2.3.2-dist

### Expected behavior

I want to be able to pull docker images from places other than the docker hub, notable quay.io and our local docker registry.

### Actual behavior

Does not appear to be possible

### Steps to reproduce behavior

I tried
singularity pull my-registry/my/image
and got
ERROR: pull is only supported for docker and shub URIs

**Comment by bauerm97** [comment]
Hi @HelenCousins this should be possible. I'm not sure if there is a perfect way to do this in one command using `singularity pull`, but we definitely support it from within a bootstrap definition file. @vsoch Can you comment on how one can do this directly from the CLI?

If you want to bootstrap a container from a custom registry, there are instructions for how to do that here: http://singularity.lbl.gov/archive/docs/v2-3/docs-bootstrap#docker

**Comment by vsoch** [comment]
Quay.io (and your own registry) are still docker registries, so you would need to add the docker uri:

```
singularity pull docker://quay.io/container
```
If there are bugs beyond that with regard to the manifests that the servers produce, we will need to look into that further!

**Comment by dtrudg** [comment]
Hi @HelenCousins - Im going to close this issue as pull from private registries is working as mentioned above, specifying the hostname:port on command line or building from a def file. Here is the example of creating a docker image, pushing to a local registry, then importing into singularity. Let us know if any further issues. Thanks!

```
# Start a docker registry
$ docker run -d -p 5000:5000 --restart=always --name registry registry:2
# Push local docker container to it
$ docker tag alpine localhost:5000/alpine
$ docker push localhost:5000/alpine
# Create def file for singularity like this..
# (add your modifications)
Bootstrap: docker
Registry: http://localhost:5000
Namespace:
From: alpine:latest
# Build singularity container
$ sudo SINGULARITY_NOHTTPS=1 singularity build alpine.simg def
```
