### ISSUE TITLE
Missing dependencies on libuuid-devel, openssl-devel

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#1203]
## Version of Singularity:

2.4.2

### Expected behavior

It compile using rpmbuild / debuild. 

### Actual behavior

Things break, dependencies are incomplete. 

### Steps to reproduce behavior

Use rpmbuild / debuild.

Apparently, https://github.com/singularityware/singularity/pull/1143 did not see any review at all - it adds dependencies on openssl-devel and libuuid-devel, but updates neither the spec-file nor the debian packaging. 
As a result, both are broken in all subsequent releases. 

Maybe a basic review procedure (as other projects have) and basic testing of the packaging code is due, or the fully unmaintained packaging code should be dropped from this repo.

**Comment by jtriley** [comment]
Already being addressed: https://github.com/singularityware/singularity/pull/1198

**Comment by olifre** [comment]
@jtriley Thanks for pointing that out!
Maybe there should also be something added to the release procedure (i.e. "test package building in clean environment before release) and travis tests for the packaging code being added? 
Otherwise, since this has now happened numerous times, I fear it will happen again and again. 

In any case, a basic review before merging things would also have prevented that.

**Comment by olifre** [comment]
Also, even after fixing that, I still get:
```
Error building RPM:
    File not found: /root/rpmbuild/BUILDROOT/singularity-2.4.2-1.el7.cern.x86_64/usr/libexec/singularity/bin/prepheader
    File not found: /root/rpmbuild/BUILDROOT/singularity-2.4.2-1.el7.cern.x86_64/usr/libexec/singularity/bin/mount-suid
```

**Comment by olifre** [comment]
Pinging @gmkurtzer as project leader since I am asking for:
- a change to PR merge policy (add basic review procedure)
- adding basic packaging tests
- potentially extending the release checklist (re-check packages can actually be build in a clean environment). 

Would be nice to see this discussed ;-).

**Comment by GodloveD** [comment]
Hey @olifre I'm a little bit confused.  You are saying this is a problem with 2.4.2?   2.4.2 has nothing to do with #1143.  That is a SIF feature and should only be in development at this point in time.

**Comment by olifre** [comment]
@GodloveD You are right! Yes, I tried to build from the development branch. 
So unlike the previous packaging issues which actually made it into releases, at least this has not happened (yet) for this one.

**Comment by GodloveD** [comment]
@olifre ok, this makes more sense.  Thank you for pointing out the packaging oversights.  I was just talking with @yhcote offline and it would probably be good if we integrated package builds into our travis tests to avoid problems like this.  😄

**Comment by olifre** [comment]
@GodloveD For CentOS 6 and 7, there already is a package build inside the travis tests.
It was just broken, since the dependency check performed by rpmbuild was made useless by manually installing the effective dependencies beforehand. 
I have fixed that in #1204 (which expectedly fails now ;-) ), but there is still no real test for Debian-based OS.

**Comment by olifre** [comment]
I've also added tests for Debian. 
They are not fully tested through, since they fail due to several reasons:

- The already mentioned dependency issues.
- `make distclean` is broken. 

I also added a test for `make distclean` in the linked PR.

**Comment by DrDaveD** [comment]
#1198 was merged and addresses the original issue here, so shouldn't this be closed?  @olifre maybe you should make a separate issue for your suggested process changes.

**Comment by olifre** [comment]
@DrDaveD Right, let's close this. 
Yes, the packaging tests I already did myself, but of course the other points still stand. I'll open a new issue soonish.
