### ISSUE TITLE
Unable to bind directories on NFS filesystem, "permission denied" error even though I have permission

### ISSUE THREAD

**Issue by carolynlawrence** [apptainer/singularity#1205]
## Version of Singularity:
2.4.2

### Expected behavior

ability to bind the directories on our nfs (v4) server that user has permissions on:
user1>> singularity --debug shell -B /nfs/test1 -B /nfs/test2 /localfs/images/myimage.simg

permissions on directories are as below:
drwxrwsr-x.  user1:group1 /nfs/test1
drwxrwxr-x.  user1:user1   /nfs/test2

(neither directory will bind, even though user1 has correct permissions and can access both directories)

### Actual behavior

Unable to shell into image, fails on the bind (not UID is masked):

DEBUG   [U=0,P=77916]      singularity_priv_drop()                   Dropping privileges to UID=1111, GID=2000713378 (11 supplementary GIDs)
DEBUG   [U=0,P=77916]      singularity_priv_drop()                   Restoring supplementary groups
DEBUG   [U=1111,P=77916] singularity_priv_drop()               Confirming we have correct UID/GID
DEBUG   [U=1111,P=77916] singularity_priv_escalate()           Temporarily escalating privileges (U=1111)
DEBUG   [U=0,P=77916]      singularity_priv_escalate()               Clearing supplementary GIDs.
VERBOSE [U=0,P=77916]      singularity_runtime_mount_userbinds()     Binding '/nfs/test1' to '/opt/singularity/singularity2.4.2/var/singularity/mnt/final//nfs/test1'
ERROR   [U=0,P=77916]      singularity_runtime_mount_userbinds()     There was an error binding the path /nfs/test1: Permission denied
ABORT   [U=0,P=77916]      singularity_runtime_mount_userbinds()     Retval = 255

### Steps to reproduce behavior

See above, and reproduces if I try different users who are members of the same group. Note that the image works as expected if I leave the binds out, and I can bind directories with the same privileges set if they are on the local filesystem.

I'm not sure if this is related to Issue #1068, as with our setup users belong to many different groups.

**Comment by cclerget** [comment]
@carolynlawrence the following output debug line is weird ` singularity_priv_drop() Dropping privileges to UID=2000713378, GID=2000713378 (11 supplementary GIDs)`, but your UID seems to be 1111: `singularity_priv_escalate() Temporarily escalating privileges (U=1111)`.

Singularity source has been modified on your system ? the only way to have different UIDs as shown in your debug log is to set SINGULARITY_TARGET_UID / SINGULARITY_TARGET_GID environment variables, so I'm confused because only root can do that

**Comment by carolynlawrence** [comment]
@cclerget Sorry about that - I had tried to mask out my UID out of an over-abundance of caution - but missed that first line. I will edit the posting.

**Comment by carolynlawrence** [comment]
With playing around with this more, I'm wondering if it is more related to issue #1100 and/or the fix for that issue, which it looks like may have been included in 2.4.1 (but correct me if I'm wrong about that) 

Basically, If I use 2.4.0, I can bind the /nfs directory itself, but cannot bind at the /nfs/test1 or /nfs/test2 level (though I can get INTO /nfs/test1 and /nfs/test2 from my image if I bind /nfs)

permissions on directories are as below:
drwxrwsr-x. user1:group1 /nfs/test1
drwxrwxr-x. user1:user1 /nfs/test2
drwxrws---. nobody:group1 /nfs  (where "nobody" is really the root on the filesystem)

But if I use 2.4.2 or 2.4.1 I can't bind any of these directories.

**Comment by cclerget** [comment]
Did you have access to NFS server export options for this mountpoint ?

**Comment by carolynlawrence** [comment]
I got this info from a team member related to the NFS server, let me know if it is what you are looking for and/or if you need more information:

We’re running a version of the userland NFS server Ganesha.
 
The NFS server is Ganesha version nfs-ganesha-2.3.2-0.ibm32_2.el7.x86_64 , which is an IBM modified build shipped with Spectrum Scale.
 
The default export options being inherited by the share are:
 
Export Defaults
==========================
ACCESS_TYPE: NONE   (overridden by share’s RW)
PROTOCOLS: 3,4
TRANSPORTS: TCP
ANONYMOUS_UID: -2
ANONYMOUS_GID: -2
SECTYPE: SYS
PRIVILEGEDPORT: FALSE
MANAGE_GIDS: FALSE
SQUASH: ROOT_SQUASH
NFS_COMMIT: FALSE
 
 
The only non-default export settings set on this share are Access_Type=RW,Squash=root_squash
 
Share is mounted nfs v4.

**Comment by cclerget** [comment]
Perfect thanks, I will try to reproduce

**Comment by cclerget** [comment]
To resume:

- with 2.4.0 you can bind a directory owned by "nobody" since root is mapped to "nobody" on server side
- with 2.4.0 you can't bind directories owned by you since singularity FS UID 0 (mapped to nobody on server side) try to access to this directory
- with 2.4.{1|2} you can't bind directories owned by you with singularity FS UID 1111 (mapped to 1111 on server side ???)

So some stupid questions come to mind :
- Can you write into these shared directories or just access them ?
- Is all_squash is set on server side ?

I will submit a fix to get user's supplementary groups and set FS GID accordingly to group directory owner being mounted. If it doesn't work, I think there is something enforced/buggy on your side

**Comment by cclerget** [comment]
@carolynlawrence I wrote a fix in the following 2.4.2 branch (https://github.com/cclerget/singularity/tree/master-1205-issue-fix-attempt) including above fix. Could you test it please ?

**Comment by carolynlawrence** [comment]
I will test the fix now and let you know - thanks!
To answer your questions from above:
    Can you write into these shared directories or just access them ? _I can write to them as well_
    Is all_squash is set on server side ? _No, verified by team member who manages the NFS server_

**Comment by carolynlawrence** [comment]
@cclerget 
Well, this change did not allow me to do the binds, but I get a slightly different error:
using 2.4.2 the error is: 
ERROR   [U=0,P=10221]      singularity_runtime_mount_userbinds()     There was an error binding the path /nfs: Permission denied
using 2.4.2a (your fix) the error is:
ERROR   [U=0,P=10254]      singularity_mount()                       Can't stat /nfs directory: Permission 
denied

Does that give any more clues as to what I should look at?

More details below:

/opt/singularity/singularity2.4.2/bin/singularity --debug shell -B /nfs myimage.simg


DEBUG   [U=1111,P=10221] singularity_runtime_mount_userbinds() Checking for environment variable 'SINGULARITY_BINDPATH'
DEBUG   [U=1111,P=10221] singularity_registry_get()            Returning value from registry: 'BINDPATH' = ',/nfs'
DEBUG   [U=1111,P=10221] singularity_runtime_mount_userbinds() Checking for 'user bind control' in config
DEBUG   [U=1111,P=10221] singularity_config_get_bool_char_impl() Called singularity_config_get_bool(user bind control, yes)
DEBUG   [U=1111,P=10221] singularity_config_get_value_impl()   Returning configuration value user bind control='yes'
DEBUG   [U=1111,P=10221] singularity_config_get_bool_char_impl() Return singularity_config_get_bool(user bind control, yes) = 1
DEBUG   [U=1111,P=10221] singularity_runtime_mount_userbinds() Parsing SINGULARITY_BINDPATH for user-specified bind mounts.
DEBUG   [U=1111,P=10221] singularity_runtime_mount_userbinds() Found bind: /nfs -> container:/nfs
DEBUG   [U=1111,P=10221] singularity_runtime_mount_userbinds() Checking if bind point is already mounted: /nfs
DEBUG   [U=1111,P=10221] check_mounted()                       Opening /proc/mounts
DEBUG   [U=1111,P=10221] check_mounted()                       Iterating through /proc/mounts
DEBUG   [U=1111,P=10221] singularity_priv_escalate()           Temporarily escalating privileges (U=1111)
DEBUG   [U=0,P=10221]      singularity_priv_escalate()               Clearing supplementary GIDs.
VERBOSE [U=0,P=10221]      singularity_runtime_mount_userbinds()     Binding '/nfs' to '/opt/singularity/singularity2.4.2/var/singularity/mnt/final//nfs'
ERROR   [U=0,P=10221]      singularity_runtime_mount_userbinds()     There was an error binding the path /nfs: Permission denied
ABORT   [U=0,P=10221]      singularity_runtime_mount_userbinds()     Retval = 255


/opt/singularity/singularity2.4.2a/bin/singularity --debug shell -B /nfs myimage.simg

DEBUG   [U=1111,P=10254] singularity_registry_get()            Returning value from registry: 'BINDPATH' = ',/nfs'
DEBUG   [U=1111,P=10254] singularity_runtime_mount_userbinds() Checking for 'user bind control' in config
DEBUG   [U=1111,P=10254] singularity_config_get_bool_char_impl() Called singularity_config_get_bool(user bind control, yes)
DEBUG   [U=1111,P=10254] singularity_config_get_value_impl()   Returning configuration value user bind control='yes'
DEBUG   [U=1111,P=10254] singularity_config_get_bool_char_impl() Return singularity_config_get_bool(user bind control, yes) = 1
DEBUG   [U=1111,P=10254] singularity_runtime_mount_userbinds() Parsing SINGULARITY_BINDPATH for user-specified bind mounts.
DEBUG   [U=1111,P=10254] singularity_runtime_mount_userbinds() Found bind: /nfs -> container:/nfs
DEBUG   [U=1111,P=10254] singularity_runtime_mount_userbinds() Checking if bind point is already mounted: /nfs
DEBUG   [U=1111,P=10254] check_mounted()                       Opening /proc/mounts
DEBUG   [U=1111,P=10254] check_mounted()                       Iterating through /proc/mounts
DEBUG   [U=1111,P=10254] singularity_priv_escalate()           Temporarily escalating privileges (U=1111)
DEBUG   [U=0,P=10254]      singularity_priv_escalate()               Clearing supplementary GIDs.
VERBOSE [U=0,P=10254]      singularity_runtime_mount_userbinds()     Binding '/nfs' to '/opt/singularity/singularity2.4.2a/var/singularity/mnt/final//nfs'
ERROR   [U=0,P=10254]      singularity_mount()                       Can't stat /nfs directory: Permission denied
ABORT   [U=0,P=10254]      singularity_mount()                       Retval = 255

**Comment by cclerget** [comment]
@carolynlawrence I just modified the fix to make privilege escalation only for mount operation, so stat should run as current user. If you get a permission denied with new fix maybe there is a security mechanism like selinux, you could check with `getfattr -n security.selinux /nfs`

**Comment by carolynlawrence** [comment]
@cclerget  Many thanks! That second fix seems to have done the trick. I tested as two different users (both with permissions on the directories in question), and verified that I can bind both at the /nfs level and at the level of subdirectories (/nfs/test) etc.

**Comment by carolynlawrence** [comment]
Also, as a newbie here, I was wondering if I am supposed to "close" this issue at this point?

**Comment by cclerget** [comment]
Glad it works and yes you can close the issue, I will submit a PR to merge fix into next release
