### ISSUE TITLE
singularity pull from docker doesn't

### ISSUE THREAD

**Issue by HelenCousins** [apptainer/singularity#1210]
## Version of Singularity:

2.4.1-dist

### Expected behavior

singularity pull docker://godlovedc/lolcow

should pull the image

### Actual behavior

When run as root it pulls it.  When run as me it doesn't, instead:

Docker image path: index.docker.io/godlovedc/lolcow:latest
Cache folder set to /nfs/users/nfs_h/hc7/.singularity/docker
[1/6] ||----------------------------------|   0.0% ERROR [Errno 13] Permission denied
Importing: base Singularity environment
Importing: /nfs/users/nfs_h/hc7/.singularity/docker/sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118.tar.gz
gzip: /nfs/users/nfs_h/hc7/.singularity/docker/sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118.tar.gz: No such file or directory
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Cleaning up...
ERROR: pulling container failed!

(that's my home directory, and the .singularity directory is universally writable)

### Steps to reproduce behavior

install singularity
singularity pull docker://godlovedc/lolcow

**Comment by HelenCousins** [comment]
I straced it

open("/dev/shm/sem.k6pkcS", O_RDWR|O_CREAT|O_EXCL, 0600) = -1 EACCES (Permission denied)


well, no, you don't have permission for that.  Why is it even trying?

**Comment by bauerm97** [comment]
@HelenCousins Would you be able to post the entire debug log reproducing the error?

`singularity -d pull docker://godlovedc/lolcow`

**Comment by HelenCousins** [comment]
singularity -d pull  docker://godlovedc/lolcow

Enabling debugging
Ending argument loop
Singularity version: 2.4.1-dist
Exec'ing: /usr/libexec/singularity/cli/pull.exec
Singularity Image: ./lolcow.simgWARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/godlovedc/lolcow:latest
Cache folder set to /nfs/users/nfs_h/hc7/.singularity/docker
[1/6] ||----------------------------------|   0.0% ERROR [Errno 13] Permission denied
Importing: base Singularity environment
Importing: /nfs/users/nfs_h/hc7/.singularity/docker/sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118.tar.gz
gzip: /nfs/users/nfs_h/hc7/.singularity/docker/sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118.tar.gz: No such file or directory
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Cleaning up...
ERROR: pulling container failed!


/nfs/users/nfs_h/hc7/ is my home directory

**Comment by bauerm97** [comment]
@HelenCousins Can you also post the entirety of the strace so I can look at what's going on? This is really weird, because where it seems like you're failing is in downloading the image from the docker registry. Somehow you don't have permission to download the docker tar archives. Could you also double check the ownership and permissions of the `/nfs/users/nfs_h/hc7/.singularity/docker` directory?

**Comment by HelenCousins** [comment]
[output.txt](https://github.com/singularityware/singularity/files/1558737/output.txt)

attachei (I hope) the output of
strace -eopen,access -o output.txt -f singularity pull docker://godlovedc/lolcow

drwxrwsrwx 2 hc7 ssg 4096 Dec  8 09:29 .singularity/docker/

This is all with singularity 2.4.1-dist on RHEL7.4  I have tried 2.4.2-dist but get different errors when I try to pull anything (shub or docker) as me (works as root).   Things seem to be working on Ubuntu, but we need it to work on RHEL.

(different error:
 singularity pull shub://vsoch/hello-world
Traceback (most recent call last):
  File "/usr/libexec/singularity/python/pull.py", line 74, in <module>
    main()
  File "/usr/libexec/singularity/python/pull.py", line 66, in main
    layerfile=LAYERFILE)
  File "/usr/libexec/singularity/python/shub/main.py", line 77, in PULL
    manifest = client.get_manifest()
  File "/usr/libexec/singularity/python/shub/api.py", line 113, in get_manifest
    response = self.get(base, return_response=True)
  File "/usr/libexec/singularity/python/base.py", line 262, in get
    return_response=return_response)
  File "/usr/libexec/singularity/python/base.py", line 278, in submit_request
    response = urlopen(request)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
)

**Comment by HelenCousins** [comment]
Hi, we have 'solved' prloblem 1 by changing permissions on /dev/shm and problem 2 is clearlsy our network.  RHEL7.3 has 755 but RHEL7.4 has 777 for /dev/shm and this appears to be a RH issue.

**Comment by dtrudg** [comment]
Closing this now - It was acknowledged as a Red Hat specific issue, setting wrong permissions on /dev/shm during an upgrade. This causes the failure above as the multi-threaded python code downloading layers uses /dev/shm

Bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1406254

KB workaround: https://access.redhat.com/solutions/2759321

Bug fix advisory: https://access.redhat.com/errata/RHBA-2017:2286
