### ISSUE TITLE
ERROR  : Failed to mount squashfs image in (read only): No such device

### ISSUE THREAD

**Issue by stevekm** [apptainer/singularity#1213]
## Version of Singularity:

2.4

Also,  Docker version 17.09.0-ce, build afdb6d4

### Expected behavior

Run a Singularity container

### Actual behavior

Error:

```
Singularity: action-suid (U=0,P=596)> Failed to mount squashfs image in (read only): No such device

ERROR  : Failed to mount squashfs image in (read only): No such device
Singularity: action-suid (U=0,P=596)> Retval = 255

ABORT  : Retval = 255
```

### Steps to reproduce behavior

I have a Docker container setup [here](https://github.com/stevekm/docker-singularity/tree/8cfb151eb5166ec38906104f26a310520968801d) which installs Singularity 2.4 inside of a Docker container running Debian Jessie. After running & entering the Docker container, I can create a Singularity container inside of it. 

However, when I [try to run the container](https://github.com/stevekm/docker-singularity/blob/8cfb151eb5166ec38906104f26a310520968801d/test.sh) with `singularity exec`, I get the error described here. Any ideas on how to fix this? It appears to be similar to #471 but the message is not entirely the same.

**Comment by yangyang-zhang** [comment]
when you docker run or exec , Add --privileged  parameters

**Comment by stevekm** [comment]
yes, that is how I am running it, and how I got the errors listed

**Comment by cclerget** [comment]
@stevekm Looks like squashfs is compiled as a kernel module and not "autoloaded" when requesting squashfs mount. From your host can you give outputs of :
- `cat /proc/filesystems|grep squashfs`
- `cat /boot/config-$(uname -r)|grep SQUASHFS`

And inside privileged docker :
- `mount -o loop,offset=31 image.img /mnt`

**Comment by stevekm** [comment]
My host system here is a MacBook with macOS. Here is the output of those commands:

```
$ cat /proc/filesystems|grep squashfs
cat: /proc/filesystems: No such file or directory

$ cat /boot/config-$(uname -r)|grep SQUASHFS
cat: /boot/config-15.6.0: No such file or directory

```

dont think I have `squashfs` installed locally; should I? 


inside the Docker container:

```
root@aefbb8fc53af:/singularity-samtools-demo# cat /proc/filesystems|grep squashfs

root@aefbb8fc53af:/singularity-samtools-demo# cat /boot/config-$(uname -r)|grep SQUASHFS
cat: /boot/config-4.9.8-moby: No such file or directory

root@6af5fba0a0fe:/singularity-samtools-demo# mount -o loop,offset=31 singularity-container-samtools /mnt
mount: unknown filesystem type 'squashfs'
```

**Comment by stevekm** [comment]
Is a way to create the Singluarity image in a format that does not use squashfs? Maybe that would solve this problem? 

on a side note, this seems similar to #108 which I just found.

**Comment by GodloveD** [comment]
Hi @stevekm.  You can build your container with the `--sandbox` to create your container in a directory, or you can pass the `--writable` flag to create an uncompressed ext3 based image.  Hope that helps you debug the issue.

**Comment by ortizem** [comment]
Hi @stevekm,

Were you able to solve the squashfs issue? I am also trying to run a singularity image inside docker using centos7. Please let me know.

Thank you,
Milo

**Comment by lemccarthy** [comment]
I am having the same problem, no matter what I try, I can't seem to get squashfs in the "filesystems" of any docker container.

**Comment by jscook2345** [comment]
@ortizem 

What issue are you having? We regularly use singularity inside a CentOS7 Docker container. Maybe open a new issue so we can help you investigate?

@lemccarthy 

Can you be more specific on the issue you're having? This issue is for a much earlier version of singularity. Can you create a new issue so I can help you work through the problem?

**Comment by lemccarthy** [comment]
@jscook2345 

It turned out to be an issue with the way I was using it. I was trying to run it on a VM that had Container OS installed, which did not have the squashfs filesystem. Once I switched to an Ubuntu based VM it worked as expected.

**Comment by waynezw0618** [comment]
@lemccarthy I am using Ubuntu VM in virtualbox and the host is MacOS, still there is such problem

**Comment by jscook2345** [comment]
@waynezw0618 Can you open your problem in a new issue so we can evaluate what is wrong with your environment? If you could include the errors and some debugging output using `singularity -d ...` that would also be helpful. Thanks!

**Comment by lemccarthy** [comment]
@waynezw0618 I don't know that my solution will work for you. You need to check if the OSX machine has squashfs support.
