### ISSUE TITLE
Caching for Singularity images stopped working

### ISSUE THREAD

**Issue by votavap** [apptainer/singularity#1223]
## Version of Singularity:

2.4.2

### Expected behavior

Once the image is pulled and cached from the Singularity Hub, it will not be downloaded again

### Actual behavior

The image is downloaded every time

### Steps to reproduce behavior

```
$ singularity pull shub://vsoch/hello-world

and one more time

$ singularity pull shub://vsoch/hello-world
```

This works in 2.4, but not in 2.4.2

I think I can see the potential issue in  `libexec/python/shub/main.py`
Under the PULL() function, the `image_name = get_image_name(manifest)` call strips or never adds the extension on the image_name, but that is used later on in:
```
...
image_file = "%s/%s" % (cache_base, image_name)
...
if not os.path.exists(image_file):
    image_file = client.download_image()
...
```

If the image originally had any extension (such as .simg), this will always fail and image will be re-downloaded. Under 2.4, there was a default simg extension in the `get_image_name()` which made things work in that case. I am sure this was changed for a good reason, but seemed to modify the caching behavior.

**Comment by magland** [comment]
I am encountering this issue as well in singularity 2.5.2-dist on Ubuntu 16.04.

For example, the following downloads the image and runs the command as expected.
```
singularity exec --contain shub://magland/ml_ephys ml-list-processors
```

if I run the same command again, I would expect it to use the cached version and not need to re-download. However, it does indeed re-download.

This is a critical issue for my workflow. Thanks!

Edit:
AND, I can confirm that @votavap is correct in his diagnosis. I manually removed the .simg from the downloaded image, and it found it on subsequent run.

**Comment by WestleyK** [comment]
Closing. Shub caching has been re-introduced in v3.3.0, and finalized in v3.4.0.
