### ISSUE TITLE
Sandbox always writable under certain conditions.

### ISSUE THREAD

**Issue by jekriske-lilly** [apptainer/singularity#1225]
## Version of Singularity:

Tested with 2.4.x+

### Expected behavior

The sandbox should not be writable without passing the -w flag

### Actual behavior

Sandbox is writable both with and without using -w

### Steps to reproduce behavior

Create a Vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
$script = <<SCRIPT
SINGULARITY_VERSION=2.4.2
FILE=/usr/local/bin/singularity
if [ ! -f $FILE ]; then
sudo apt-get update
sudo apt-get install -y squashfs-tools
sudo apt-get install -y  gcc build-essential python libtool autoconf automake
wget https://github.com/singularityware/singularity/releases/download/$SINGULARITY_VERSION/singularity-$SINGULARITY_VERSION.tar.gz
tar xvf singularity-$SINGULARITY_VERSION.tar.gz
cd singularity-$SINGULARITY_VERSION
./configure --prefix=/usr/local --sysconfdir=/etc
make
sudo make install
fi
SCRIPT
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision 'second',  type:'shell', inline: $script, preserve_order:true
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
```

Enter the VM
`vagrant ssh`

Build a sandbox
`sudo singularity build -s sandbox shub://jekriske/lolcow:lowfat`
(any sandbox should work)

Write a test file
`sudo singularity exec sandbox touch /var/somefile`

List contents
`sudo singularity exec sandbox ls -l /var`
```
total 12
-rw-r--r--    1 root     root             0 Dec 20 00:41 somefile
drwxr-xr-x    3 root     root          4096 Nov  1 22:58 spool
drwxrwxrwt    2 root     root          4096 Dec  5 20:44 tmp
drwxr-xr-x    2 www-data www-data      4096 Nov  1 22:58 www
```

Curiously, if you change the Vagrantfile to use the newer xenial64 instead of trusty64 it'll work as expected. There's some set of conditions in Ubuntu 14.04 which make Singularity exhibit this issue.

**Comment by cclerget** [comment]
@jekriske-lilly I think the following snippet in dev branch fix the issue by remounting directory in read-only when -w is not set : https://github.com/singularityware/singularity/blob/08dc27ab8e4e8b66b03d8903bce54eaa73f5e192/src/lib/image/dir/mount.c#L73-L81

If you can confirm it works for this issue ?
And if this bug is really annoying, maybe integrate fix for 2.4.3 release rather than waiting next major release ?

**Comment by jekriske-lilly** [comment]
@cclerget that's certainly one way to solve the issue, but it actually causes the filesystem to not even be writable in a temporary manner

```
Singularity> touch /var/somefile
touch: /var/somefile: Read-only file system
```

One would expect this to create the file without complaint, but, if I didn't launch the container as writable, it shouldn't be there when I shell into the container again. 

That said... I've just tested in Ubuntu 16.04 (with Singularity 2.4.2) and when overlay is set to 'no' in the config it exhibits the same behavior as seen in Ubuntu 14.04, the sandbox is always writable. Was this always the behavior if overlay isn't enabled?

**Comment by dtrudg** [comment]
We have a different situation now in current versions with `--writable-tmpfs` etc. Closing - if there's a concern in 3.5 please open a new issue.
