### ISSUE TITLE
Point to LICENSE file instead of asking to contact IPO@lbl.gov

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#123]
Currently all (?) the headers have such a statement

```
# Copyright (c) 2015-2016, Gregory M. Kurtzer. All rights reserved.
# 
# “Singularity” Copyright (c) 2016, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
# 
# If you have questions about your rights to use or distribute this software,
# please contact Berkeley Lab's Innovation & Partnerships Office at
# IPO@lbl.gov.
```

which alone suggests that this software is not redistributable etc (all rights reserved).  It would be great if it was adjusted to something like

```
# Copyright (c) 2015-2016, Gregory M. Kurtzer. All rights reserved.
# 
# “Singularity” Copyright (c) 2016, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
# 
# It is released under a customized BSD-3 license.  Please consult LICENSE 
# file distributed with the sources of this project about your rights to use or 
# distribute this software.
```

if it is indeed released under the license stated in LICENSE ;)

**Comment by gmkurtzer** [comment]
I have to run all license changes through Berkeley lab legals. I see your concern but I can reiterate that singularity is just as distributable (and "free") as any other BSD based code.

**Comment by yarikoptic** [comment]
Well, I am not asking to change the license, just to point to the license in each header. If they mandated the wording of the header, I guess indeed ask them, since to my understanding it simply conflicts with the license itself which doesn't require users to contact Berkeley lab legals

**Comment by gmkurtzer** [comment]
Yes very fair point. Indeed they gave me both the COPYRIGHT file as well as the source file headers so I will check with them.

Thanks!

**Comment by gmkurtzer** [comment]
Spoke with legals, waiting for formal response.

**Comment by gmkurtzer** [comment]
This has been done. Thanks!

**Comment by yarikoptic** [comment]
Awesome, thanks!

**Comment by gmkurtzer** [comment]
the legal hats ended up changing the wording a bit, but I think it satisfies what you were hoping to have changed. Sorry for the latency, and let me know if you see anything else!

Thanks again!
