### ISSUE TITLE
How to install the SLURM plugin

### ISSUE THREAD

**Issue by jmdf** [apptainer/singularity#1231]
## Version of Singularity:

2.4.2

### Expected behavior

Run ./configure --with-slurm without any errors.

### Actual behavior

`ERROR: Slurm support is no longer maintained in Singularity proper and will`
       `be maintained as a subproject on GitHub.`

Is this subproject already available or is there a way to install the plugin regardless? I can't find any information online and the plugin seems to be exactly what I need. Thanks!

**Comment by ps-account** [comment]
*bump*

**Comment by MrBr-github** [comment]
@gmkurtzer 
I'm having the same issue, any updates?
Did you created the subproject as mentioned in this [comment ](https://github.com/singularityware/singularity/pull/895#issuecomment-330375523)

**Comment by takeharukato** [comment]
Hi. 

I'm having the same issue.
And I also got  a message "Slurm support is no longer maintained in Singularity proper and will be maintained as a subproject on GitHub.".
And then,  I looked into Singularity plugin source.
As results, I think that it is needed to add following three functions into libsingularity-runtime:

* singularity_cleanupd
* singularity_sessiondir
* action_ready

It makes Slurm plugin separated from Singularity main source tree at least.

I wrote this patch and put it on "https://github.com/takeharukato/singularity/tree/devel-tkato-slurm-plugin-base". Does it help your sepation task?

Dispite the most part of Singularitty plugin and action command  are same, but singularity slurm plugin implements the way to create container by own codes.
I think that this is core problem of this from maintainability point of view.

Ideally, it will be preferable to move container creation part in libexec/singularity/bin/action to  libsingularity-runtime. However, it might be a little difficult.

Anyway, I  made the plugin work with my patch.
It can also  be obtained from https://github.com/takeharukato/singularity/tree/devel-tkato-slurm-plugin ,  if someone are interested in the plugin.  
Would you please, free to use it for the moment.

Regards,

**Comment by dtrudg** [comment]
Closing - there is no slurm plugin for 3.x.
