### ISSUE TITLE
Error when pulling private imaged from SRegistry not managed

### ISSUE THREAD

**Issue by victorsndvg** [apptainer/singularity#1234]
## Version of Singularity:

2.4.2

### Expected behavior

If I use Singularity to pull a public image from our own SRegistry it works like a rocket. This is the "manifest" you get from the api:

```
HTTP 200 OK
Allow: GET, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "id": 2,
    "name": "example",
    "image": "https://myregistry/containers/2/download/453b5bef-aa3d-4ad0-9027-ade0e578eb69",
    "tag": "latest",
    "add_date": "2017-12-27T04:53:46.463742-06:00",
    "metrics": {},
    "version": null,
    "frozen": false,
    "metadata": {
        "runscript": "#!/bin/sh \n\n    fortune | cowsay | lolcat\n",
        "size_mb": 87,
        "environment": "...",
        "test": null,
        "deffile": "..."
    },
    "collection": "mso4sc"
```

If someone try to use Singularity to pull a private image from their own SRegistry, I think it should manage the error and show a generic message like "image not found".
This is the "manifest" you get from the api:

```
HTTP 200 OK
Allow: GET, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

400
```
### Actual behavior

If someone try to use Singularity to pull a private image from their own SRegistry,

```
$ singularity pull shub://myregistry/mycollection/example:latest
DEBUG 
*** STARTING SINGULARITY PYTHON PULL ****
VERBOSE2 SINGULARITY_CONTAINER found as shub://myregistry/mycollection/example:latest
VERBOSE2 SINGULARITY_PULLFOLDER found as .
DEBUG Found uri shub://
DEBUG Headers found: Content-Type,Accept
DEBUG GET https://sregistry.srv.cesga.es/api/container/mso4sc/example:latest
DEBUG Pull folder set to /mnt/netapp2/Home_FT2/home/cesga/vsande
Traceback (most recent call last):
  File "/opt/cesga/singularity/2.4.2/libexec/singularity/python/pull.py", line 74, in <module>
    main()
  File "/opt/cesga/singularity/2.4.2/libexec/singularity/python/pull.py", line 66, in main
    layerfile=LAYERFILE)
  File "/mnt/EMC/Optcesga_FT2/opt/cesga/singularity/2.4.2/libexec/singularity/python/shub/main.py", line 87, in PULL
    image_name = get_image_name(manifest)
  File "/mnt/EMC/Optcesga_FT2/opt/cesga/singularity/2.4.2/libexec/singularity/python/shub/api.py", line 242, in get_image_name
    return get_default_name(manifest)
  File "/mnt/EMC/Optcesga_FT2/opt/cesga/singularity/2.4.2/libexec/singularity/python/shub/api.py", line 252, in get_default_name
    if "tag" in manifest and "branch" in manifest:
TypeError: argument of type 'int' is not iterable
```

### Steps to reproduce behavior

1. Use SRegistry.
2. Push a new image.
3. Make the collection private.
4. Pull the image using singularity.

Thanks for your help!

**Comment by vsoch** [comment]
hey @victorsndvg ! Despite the lack of grace in handling the second response, if a user tries to pull a private image that he/'she does not have permissions for, the response expected would be 400. Some APIs choose to give less information and return 404 (not found) but 400 in this case is more proper to indicate "yes, found, but you don't have permissions for" (Bad Request). As for the ugly error handling, that is simply the functions coughing because they are expecting a dictionary and got an int instead.

The library should likely be able to handle a return status that isn't a dictionary without such as error. As for the client, I would recommend waiting a little bit for the production client of sregistry, which can use more modern python methods to issue and parse these requests, and I can more easily update and make sure this bug is handled. Thanks!

**Comment by vsoch** [comment]
hey @victorsndvg ! Here is a quick preview of what you can expect when it's ready to go - the expected response of 400 is parsed and returned to you is a more meaningful message.

https://asciinema.org/a/154519?speed=3

I promise to have this all ready to go latest first week of the new year! Lol... (says the kid that just woke up in the middle of the night super excited to debug this...) :P  Going back to sleep now!

**Comment by victorsndvg** [comment]
` vanessa/tacolicious:gobacktosleep` ?? really ??? :rofl: 

Wow the tool is evolving super fast! it looks completely amazing!

Congrats, great work!

**Comment by victorsndvg** [comment]
By the way, is it possible to `pull` private SRegistry images with any of your tools? and how?

**Comment by vsoch** [comment]
oh definitely. What I didn't show in the above is that I could have my credential file exported in the environment under `SREGISTY_CLIENT_SECRETS` and then the api would have added a header based on the body of the request that gets encrypted on the client (and then the server uses the same secret to de-crypt) and if it matches, you get approved. If not, then you get a different error, 403, Unauthorized.

**Comment by victorsndvg** [comment]
Thanks, I'm aware of this environment variable and file containing the token. No issues while pushing.

Is this secret maintained on the server side after changing the privacy of a collection?

What is happening is that I'm changing the privacy of a collection to try pull it when it's private or public.

When it's private `pull` it's not working for me.

**Comment by vsoch** [comment]
To be honest I haven't tested this particular use case - what should happen is that the same authentication flow is issued as with is for a push, and I haven't tested in a while! Let's look at this more carefully when the client is ready, as we will need to test this particular use case anyway. I'm having a bit of a busy start to the new year but I think we can definitely get this done within the next few weeks.

**Comment by victorsndvg** [comment]
Ok, no rush :wink: 

I have a workflow ready for "public images". I think is enough at this moment for the pilot.

Let me know any advance on this.

Happy new year!

**Comment by vsoch** [comment]
Will do!! Lol, I totally forgot about that new year thing. I'm glad I didn't miss it this time :P Happy one to you too!

**Comment by dtrudg** [comment]
Hi @vsoch - can you advise if this issue is addressed now? Thanks!

**Comment by vsoch** [comment]
Yep thanks for checking @dctrud , we fixed this up here https://github.com/singularityhub/sregistry/pull/77 Closing!
