### ISSUE TITLE
Support for Singularity compliance with the OCI runtime

### ISSUE THREAD

**Issue by ps-account** [apptainer/singularity#1235]
This is a regularly asked question, but I couldn't find a corresponding issue, maybe I searched incorrectly, but otherwise, here you go! 

https://twitter.com/search?q=OCI%20singularity&src=typd

https://twitter.com/mr_openstack/status/887685486432714752

https://twitter.com/biocrusoe/status/947420025002086400

There doesn seem to be any technical reason not to do it, it mostly seems to be a time / human resource issue that prevents this from being implemented. Maybe this is a nice subject for any upcoming hackathon.

**Comment by GodloveD** [comment]
Hiya @pimpim!  I wholeheartedly agree!  OCI compliance is a major part of our extended roadmap. 
 We are very loosely planning on having a hackathon in the third week of Feb in the Berkley area.  Are you interested in attending?

**Comment by ps-account** [comment]
Interested yes, but not practically able to attend! Maybe there is some sort of remote participation possible?

**Comment by ArangoGutierrez** [comment]
+1
Hey @GodloveD can you pls tag me as "Assignees" on this issue. ;)

**Comment by ArangoGutierrez** [comment]
@bauerm97

**Comment by ps-account** [comment]
This document might be of interest, eg in the context of singularity registry https://docs.google.com/document/d/15y0SBrrDFIEM7pnU-Oe3Y6pq-eTZfo0mk-k33cS2hR4/edit#heading=h.kmkpd9i5mwli

**Comment by bauerm97** [comment]
Hey @rdwrt sorry for the late response, we've been super busy getting the SyLabs org set up and churning. Onto the topic of OCI compliance, the issue has exclusively been we haven't had enough manpower to think about OCI. However now that SyLabs the company is set up, we have the resources to go forward with OCI. 

With Singularity 3.0 out on the horizon, we're rewriting our front end/CLI in Golang. Doing this will allow us to be much more flexible with supporting alternative runtime/image specifications, including OCI. This means that with version 3.0, Singularity will integrate directly and seamlessly into any tool that expects an OCI runtime.

**Comment by vsoch** [comment]
woohoo! hey @bauerm97 long time no see! You should be a part of the discussion here too: https://github.com/opencontainers/tob/pull/35 and I have some (pretty silly) plans for continuing to learn Go, haha. :)

**Comment by GodloveD** [comment]
It seems like this issue is pretty much finished now that 3.1 is out.  I'll close.  Feel free to ask if it needs to be re-opened.

**Comment by vsoch** [comment]
Great job guys!
