### ISSUE TITLE
[SCIF] re-naming of environment variables

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#1236]
To better support a general filesystem format, it should be the case that SCIF (what we are now called the Scientific Filesystem) is not entirely Singularity specific. Toward this goal:

 - variables should be renamed to be more general (e.g., `SINGULARITY_APPS` --> `SCIF_APPS` 
 - documentation should be updated to reflect these things

Likely there will be more necessary changes that I will update this issue. I will start a PR with revisions that can be reviewed fully after some additional thinking and testing.

**Comment by dtrudg** [comment]
Closing this as the PR has now been merged. Thanks!

**Comment by vsoch** [comment]
woohoo thanks @dctrud ! Much appreciated.
