### ISSUE TITLE
Compiling with CLANG fails on instance.start

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#1244]
## Version of Singularity:

Development branch

### Expected behavior

An instance starts up...

### Actual behavior

Container fails to start

```
DEBUG   [U=1000,P=1]       singularity_registry_get()                Returning value from registry: 'CLEANUPD_FD' = '-1'
DEBUG   [U=1000,P=1]       singularity_registry_get()                Returning NULL on 'INSTANCE_BOOT'
DEBUG   [U=1000,P=1]       singularity_install_signal_handler()      Creating signal handler
DEBUG   [U=1000,P=10519]   singularity_wait_for_go_ahead()           Received go-ahead signal: -1
ERROR   [U=1000,P=10519]   singularity_fork_daemonize()              Daemon failed to start
ABORT   [U=1000,P=10519]   singularity_fork_daemonize()              Retval = -1
```

### Steps to reproduce behavior

Check out the development branch, and configure with:

`CC=clang ./configure --prefix=/some/path/here`

In `src/util/fork.c` ~line 146 in `singularity_wait_for_go_ahead()` you have the loop:
```
// Block until other process indicates it is OK to proceed.
while ( (-1 == (retval = read(coordination_pipe[0], &code, 1))) && errno == EINTR) {}
```

CLANG optimizes this empty loop out. If you change it to be:
```
while ( (-1 == (retval = read(coordination_pipe[0], &code, 1))) && errno == EINTR) {sigularity_message(DEBUG,"Blocking...");}
```

And configure with:
`CC=clang CFLAGS="-O0" ./configure /some/path/here`

It works as expected.

**Comment by jmstover** [comment]
Actually, from more playing... I think this error is just the produced symptom and not the actual problem. Even wrapping the while loop in clang pragma's to disable optimization, it still fails unless all of Singularity is built with `-O0`

**Comment by dtrudg** [comment]
@jmstover - believe this is r.e. 2.x ? If not please feel free to reopen.

**Comment by jmstover** [comment]
Yes it was 2.x specific. There _may_ be some CGO stuff that happens to trigger something similar, but...
