### ISSUE TITLE
Hardcoded path /usr/local/libexec/singularity/bin/cleanupd

### ISSUE THREAD

**Issue by stolpeo** [apptainer/singularity#1247]
## Version of Singularity:

2.4.1

### Expected behavior

`cleanupd` must be searched in the path provided by `prefix` during configuration.

### Actual behavior

I compiled Singularity into my home directory using `prefix` to point to somewhere into my homedir. Apparently there is some hardcoded path that does not adapt to the `prefix` setting:

```
$ ./singularity run docker://ubuntu:latest
Docker image path: index.docker.io/library/ubuntu:latest
Cache folder set to /home/$USER/.singularity/docker
Creating container runtime...
ERROR  : Exec of cleanupd process failed /usr/local/libexec/singularity/bin/cleanupd: No such file or directory
ABORT  : Retval = 255
```

### Steps to reproduce behavior

```
$ wget https://github.com/singularityware/singularity/releases/download/2.4.1/singularity-2.4.1.tar.gz
$ tar xzvf singularity-2.4.1.tar.gz
$ cd singularity-2.4.1
$ ./configure prefix=/home/$USER/singularity
$ make
$ make install
$ cd /home/$USER/singularity/bin
$ ./singularity run docker://ubuntu:latest
```

**Comment by DrDaveD** [comment]
@stolpeo You missed a build step.  You should do ./autogen.sh before configure.  Still, I don't see how that would cause this problem.

Even without that autogen.sh, I wasn't able to reproduce your problem on a RHEL7 system (with unprivileged singularity enabled) that has no /usr/local/libexec/singularity.  What O.S. are you running on?
