### ISSUE TITLE
java.lang.IllegalStateException: Timed out waiting response

### ISSUE THREAD

**Issue by jl98800** [apptainer/singularity#1248]
## Version of Singularity:
Singularity 0.16.2 and 0.14.1

### Expected behavior

The expected behavior is for singularity to not time out and restart - which restarts all running tasks.

### Actual behavior

java.lang.IllegalStateException: Timed out waiting response - singularity restarts, and restarts all running tasks (bad for business). 

### Steps to reproduce behavior

Introduce a heavy load (lots active requests/tasks - like 10,000 active requests and over 50 active tasks.

Other helpful info and things we've tried to do.  Please provide specifics to using a DB to manage history (for purging).

Found this in the logs - this happens consistently every thirty minutes:

java.lang.IllegalStateException: Timed out waiting response for objects from /tasks/history, waited 5000 millis

This can be caused by a large amount of request or task history, a heavy task load in singularity, or problems with zookeeper.

Updating singularity.yaml in a custom docker image can help (Audience Modeling is doing this).  There are several parameters to consider here:  https://github.com/HubSpot/Singularity/blob/master/Docs/reference/configuration.md#history-purging

Or this configuration in singularity.yaml:

historyPurging:
  enabled: true
  deleteTaskHistoryAfterDays: 7

Other parameters to consider besides deleteTaskHistoryAfterDays:

    deleteTaskHistoryAfterTasksPerRequest  (by record count)
    checkTaskHistoryEveryHours

The other option is to spread out the load/requests in Singularity.

Lastly, cleaning up the singularity state/app/scheduled tasks is another option (manually through the zookeeper UI (aka exhibitor).  Though in my experience this has limited success with this sort of issue.

stderr shows `! java.lang.IllegalStateException: Timed out waiting response for objects from /racks, waited 5000 millis`

it was happening because they were submitting lots of simultaneous tasks and each of them had lots of task history which singularity fetches

AMD team should try to throttle task scheduling from their end because there is no 'fix' for singularity other than deleting all task history.  There are parameters we can put into singularity.yaml to clear history at a certain threshold.

AMD team are running tasks allocated 280+GB of memory

i think part of the issue here is that they have 8055 'requests' marked 'active' every time a new 'task' runs, singularity queries all of that history.

Tried to manage this with the following entry in singularity.yaml:

historyPurging:
  enabled: true
  deleteTaskHistoryAfterDays: 7
and
deleteTaskHistoryAfterTasksPerRequest: 2000

Do these parameters require the use of a DB to be effective???

**Comment by GodloveD** [comment]
Hi @jl98800.  Since none of Singularity is written in java, I can't see how it would be throwing this error.  Singularity also does not have any mechanism to "timeout and restart".  Could it be that you have the Singularity container solution confused with another similarly named github project?

**Comment by jl98800** [comment]
Sorry, I should have explained it further.  

We are running singularity in a docker container in a Mesos/Marathon cluster configuration.  I'm not familiar with the tasks that are running.  The gist of this issue is we have bursty times where we have A LOT of singularity tasks kick off to the point it where it overwhelms singularity.  If this is not the right project then please close this.

**Comment by GodloveD** [comment]
Is there any way that you can run these tasks in Docker containers or outside of Singularity on bare metal for debugging?  I'll bet you see the same errors when you have alot of tasks running.  In other words, I'm assuming this error is not related to Singularity but some other aspect of your software/hardware stack.

**Comment by dtrudg** [comment]
Seems to be the wrong singularity - this question is likely about https://github.com/HubSpot/Singularity

**Comment by GodloveD** [comment]
Good call @dctrud .  That Singularity is actually written in java.  😸 

I'm going to close this.  If you are convinced that you are really running Singularity containers, then type the following at the command prompt, post the output, and reopen the issue.  Thanks!
```
singularity exec shub://GodloveD/lolcow cowsay "It's really Singularity!"
```
