### ISSUE TITLE
Failed to mount image in (read only): Invalid argument

### ISSUE THREAD

**Issue by arpit15** [apptainer/singularity#1256]
## Version of Singularity:
2.3.2-master.gb449aee
I created a singularity read only image from sandbox image using singularity 2.4.2-master.g91881f7. 
`sudo singularity build final2.img myubu/`
When I try to run this image in clusters which has singularity 2.3.2-master.gb449aee using `singularity shell --nv final2.img` I get the errors.
### Expected behavior
`singularity shell --nv final2.img`
Singularity final2.img:~>
### Actual behavior
`singularity shell --nv final2.img`
ERROR  : Failed to mount image in (read/write): Invalid argument
ABORT  : Retval = 255

### Steps to reproduce behavior
Using singularity 2.4.2-master.g91881f7
`sudo singularity build final2.img myubu/`
Using singularity 2.3.2-master.gb449aee
`singularity shell --nv final2.img`

The behavior is not consistent. I was able to create and use an image using the same commands and same singularity versions before making a couple of changes to my sandbox image. 
The output of `singularity -vvv shell --nv final2.img ` is [here](https://gist.github.com/arpit15/d93f40a1cfff129e8c474d20c229b646). 
The output of `singularity -vvv -debug shell --nv final2.img ` is [here](https://gist.github.com/arpit15/a117976a0c11c0252567dd79e11870d1)
The sandbox image is available [here](https://drive.google.com/drive/folders/16Jb3XKB7202KAfrlF6tgerrjpaO-zpod?usp=sharing).
The singularity squashfs format is available [here](https://drive.google.com/file/d/1lwMIsp7OLOo7mD68hrTCy_iX8-7NybEh/view?usp=sharing).

**Comment by GodloveD** [comment]
Hi @arpit15.  We actually don't support building Singularity images with a newer version of Singularity and running them in an older version.  We support the opposite (building with an older version and running with a newer version) but there is really no good way for us to support building with newer and running with older.

**Comment by arpit15** [comment]
@GodloveD I understand your comment. Thank you for the support. Fortunately for me, admin updated the singularity version to 2.4.2-dist and everything works.
