### ISSUE TITLE
[wishlist] inherit and prefix (not override) PS1 for shell

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#126]
not sure if that could be an option, since probably it is unsafe in general to leave original PS1 which might have all kinds of custom wizardy which might not be available within the container's shell  BUT it would be cool if I could enter containers shell and still feel "home", but with a visible marker that I am in that particular cingularity container.

UX example could e.g. be the Python virtualenv:

``` shell
2 8008 [2].....................................:Fri 08 Jul 2016 02:09:09 PM EDT:.
hopa:~datalad/datalad
$> echo "shell outside"
shell outside
2 8009 [2].....................................:Fri 08 Jul 2016 02:09:14 PM EDT:.
hopa:~datalad/datalad
$> source venv-tests/bin/activate
(venv-tests) 2 8010 [2].....................................:Fri 08 Jul 2016 02:09:18 PM EDT:.
hopa:~datalad/datalad
$> echo "you can see that PS1 got (venv-tests) prefix now"
you can see that PS1 got (venv-tests) prefix now
```

and I also configured it similarly although I believe a bit adhoc for schroot sessions (here original one is bash, above example had it zsh)

``` shell
(git)/home/yoh/proj/datalad/datalad:[rf-create-test-outsideoftests]
#1 !1132 [0].....................................:Fri Jul 08 14:10:53:.
hopa:~/proj/datalad/datalad
*$> schroot -c jessie-i386
(git)/home/yoh/proj/datalad/datalad:[rf-create-test-outsideoftests]
#1 !1132 [0].....................................:Fri Jul 08 18:11:30:.
hopa(jessie-i386):~/proj/datalad/datalad
$> 
```

both examples above lack lovely colors I use to accent on the fact that look and feel persists, but I get those additional markers signaling that I am in some different environment.  So it might be nice if PS1 (if present in environ as it should), should just get prefixed with `[Singularity/IMAGE]`

**Comment by gmkurtzer** [comment]
Something like this?:

[gmk@centos7-x64 demo]$ singularity shell /tmp/Demo-1.img 
(Singularity/Demo-1.img)[gmk@centos7-x64 demo]$ exit
[gmk@centos7-x64 demo]$ 

Which will basically just do the shell equivalent of:

PS1="(Singularity/$IMAGE)$PS1"

You have a fairly complicated multiline PS1, will prefixing work as you describe, or does it need more logic to prefix the last line?

I am kinda curious, what does your PS1 envar look like..

**Comment by yarikoptic** [comment]
yeap -- something like that ;)

my config is http://git.onerussian.com/?p=etc/bash.git;a=blob;f=.bash/bashrc/01_prompt;h=60367e189f621d9f6763363601821dd7dc1ed0e3;hb=HEAD#l14   for bash    and I guess http://git.onerussian.com/?p=etc/zsh.git;a=blob;f=.zsh/zshrc/85_prompt;h=2b035cca9946c7809dfbd5da4f7cb1e9331bfd2c;hb=HEAD  for zsh

**Comment by gmkurtzer** [comment]
Added in [master e27614b]... Can you check to see if it does what you were hoping for?

Thanks!

**Comment by yarikoptic** [comment]
On Tue, 12 Jul 2016, Gregory M. Kurtzer wrote:

>    Added in [master e27614b]... Can you check to see if it does what you were
>    hoping for?

great!  I will check it all out tomorrow.

## Cheers!

Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by gmkurtzer** [comment]
I am not sure I like how it overloads the prompt when using the RH standard PS1... But let me know what you think!

**Comment by gmkurtzer** [comment]
I changed how PS1 is getting set. Please confirm that it is still working as you like. If not, the code is now inside newly bootstrapped containers at `/environment` and gets generated by `libexec/mods/linux_build.smod`.

There is still PS1 code in the C code for legacy purposes, but that probably won't stay there forever.

**Comment by yarikoptic** [comment]
I guess base shell PS1 is not really passed inside ATM..

 may be my bashrc too screwed up but it just forces itself over (see below)... for zsh and dash -- singularity one just manages to duplicate itself twice:

```
$> singularity exec /tmp/debian.img cat /environment
# Define any environment init code here
# 

PATH=.:/bin:/sbin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin:/home/yoh/.mutt/soft:/bin:/sbin
PS1="Singularity.$SINGULARITY_CONTAINER> $PS1"
export PATH PS1
2 10760 [2].....................................:Thu 14 Jul 2016 02:34:04 PM EDT:.
(git)hopa:~/deb/perspect/singularity[enh-debian]
$> singularity exec /tmp/debian.img /bin/zsh        
Singularity.debian.img> Singularity.debian.img> 
2 10761 [2].....................................:Thu 14 Jul 2016 02:34:17 PM EDT:.
(git)hopa:~/deb/perspect/singularity[enh-debian]
$> echo $PS1
%{%}%{%£%L%(1 . /% /.) %␤%(0?.. $πPR R█←£->%?$πPR Y█LLOW£)%(1┘. $πPR ↓LU█£[%┘]$πPR Y█LLOW£.).....................................%π%}:%D{%c}:.%{%}
%(5v.%{%}(%5v).)%{%}%B%m%b:%1v%(2v.[%B%2v%b].)%(3v.%3v.)%{%}
$> 
2 10762 [2].....................................:Thu 14 Jul 2016 02:34:20 PM EDT:.
(git)hopa:~/deb/perspect/singularity[enh-debian]
$> singularity exec /tmp/debian.img /bin/bash
(git)/home/yoh/deb/perspect/singularity:[enh-debian]
#1 !1371 [0].....................................:Thu Jul 14 18:34:34:.
hopa:~/deb/perspect/singularity
$> exit
$> singularity exec /tmp/debian.img /bin/dash
Singularity.debian.img> Singularity.debian.img> 
/bin/dash: 0: Cannot set tty process group (No such process)
```

**Comment by gmkurtzer** [comment]
I am having a hard time replicating this. I commented out what I think might be causing redundant Singularity PS1 entries from sexec.c. Can you do a pull and test it when you get a chance?

Thanks!

**Comment by yarikoptic** [comment]
yeap, now we are back where we started seems to me ;)

**Comment by gmkurtzer** [comment]
YAY! Should we call this issue done, or is there additional logic that can make it even better that you are thinking of?

Thanks!

**Comment by yarikoptic** [comment]
well, from my user perspective, nothing was done ;)  i.e. we are still in singularity specific PS1, and without inheriting original PS1 anyhow... but it seems (on my simple trials) that PS1 is not exported to the child processes, so we are out of luck in such an approach.  And since you do define SINGULARITY_ variables I can just tune up my bashrc to reflect them for now

**Comment by yarikoptic** [comment]
here is how it looks now  http://www.onerussian.com/tmp/gkrellShoot_07-14-16_155406.png
eventually I will figure out why zsh doesn't pick up custom PS1'ing... may be because it is coming from that /environment

**Comment by gmkurtzer** [comment]
Your prompt looks very cool! If you have any ideas on fixing up the Singularity one, I'd welcome it. At present, there is not much there but it gets the point across simply.

Thanks!
