### ISSUE TITLE
Clean environment LANG=C causing tar extraction errors - docker forces UTF8

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#1260]
## Version of Singularity:

Development

### Expected behavior

`singularity pull docker://brainlife/freesurfer:latest` completes without errors or warnings

### Actual behavior

Spits out multiple:

`WARNING: Warning reading tar header: Linkname in pax header can't be converted to current locale.`

... from libarchive code. Container still runs despite warnings.

### Steps to reproduce behavior

Use development branch, run `singularity singularity pull docker://brainlife/freesurfer:latest`

----

This seems to be because when environment is sanitized, singularity is setting `LANG=C` in `src/lib/runtime/environment/environment.c`

Docker layer tar.gz files generally need to be extracted with a UTF8 $LANG set to avoid error. This was an issue previously observed for the docker/moby code base and fixed by forcing `LANG=en_US.UTF-8` when dockerd is started. See:

https://github.com/moby/moby/issues/355
https://github.com/moby/moby/commit/521ce07859ad09032268793b71e1e5f007e203b5

I can make a PR here - but is the preferred approach to either:

- Handle in the docker-extract.c code
- Change default sanitized $LANG to en_US.UTF-8

Not sure what the impact of not using C as the default may be?

Apologies for not catching this during the PR for the docker-extraction code. Came up almost as soon as that had been merge :cry:

**Comment by dtrudg** [comment]
Ahh - on the moby issue they did some digging - when LANG is C

>bsdtar cannot convert to UTF-8 (when packing) or from UTF-8 (when unpacking) it will disregard the UTF-8 name contained in the pax header, and use the raw name (and it will work fine), but it will display a warning

Also later they moved the forced dockerd environment to a force for bsdtar calls only

https://github.com/moby/moby/commit/078a19d7255a7f9f50c4071a6b0811f4a996bd3e

We are using libarchive here, which is what bsdtar is based on.

**Comment by GodloveD** [comment]
Does this just result in warnings or does it actually change something about the container?

I am also not sure about the consequences of changing LANG from C to en_US.UTF-8.  Why don't you try handling it in the docker-extract.c code and see if that works as expected.

**Comment by dtrudg** [comment]
It seems to just be warnings - everything is extracted as far as I can see - and from what the docker folks found:

>if bsdtar cannot convert to UTF-8 (when packing) or from UTF-8 (when unpacking) it will disregard the UTF-8 name contained in the pax header, and use the raw name (and it will work fine), but it will display a warning

I'll try and modify the docker-extract code this weekend if I get the chance, otherwise next week.

**Comment by GodloveD** [comment]
If the warnings are just warnings and everything is doing the right thing do we want to just send the warnings to `/dev/null` and call it a day?

**Comment by dtrudg** [comment]
I'd rather not - in case there are other warnings that might impact stuff. E.g. there have been reports of people seeing timestamp warnings with the old extraction method - and it's feasible that erroneous timestamps could affect a container working properly.

**Comment by GodloveD** [comment]
Fair enough.

**Comment by dtrudg** [comment]
Closing - PR #1261 was merged

**Comment by GodloveD** [comment]
Thanks!
