### ISSUE TITLE
DOCS: --prefix can cause troubles with /var and clusters, should mention --localstatedir

### ISSUE THREAD

**Issue by draeath** [apptainer/singularity#1264]
Found with tags/2.4.2

When --prefix is specified in ./configure, the following variables are populated in the Makefile:

```
CONTAINER_FINALDIR = ${prefix}/var/singularity/mnt/final
CONTAINER_MOUNTDIR = ${prefix}/var/singularity/mnt/container
CONTAINER_OVERLAY = ${prefix}/var/singularity/mnt/overlay
```

If the specified `${prefix}` directory is on a network share, permissions issues may cause bind mounts to fail. It also may be an issues when running Singularity in a cluster environment, where nodes might share the same backing storage `${prefix}`.

The build docs should mention these caveats, and suggest specifying `--localstatedir=/var` or another appropriate _local_ path. This overrides the three variables above, putting `singularity/mnt` inside the specified directory.

We ran into these issues, and it was not obvious what might be going on until I deep-dived the Makefile.

**Comment by vsoch** [comment]
This is a great suggestion! The docs are actually in another repo, do you want to PR here --> https://github.com/singularityware/singularityware.github.io so others don't run into the issue, and spend inordinate amounts of time debugging as you did, sorry about that!

**Comment by draeath** [comment]
I can do that. I'd also note that INSTALL.md lives in this repo and suggest adding a link to the github.io docs while we're on the topic :)

**Comment by vsoch** [comment]
I think the install.md is here so that if the internet exploded and someone found a repository, they would still have the information. Definitely +1 to add a link to the docs to it!

**Comment by vsoch** [comment]
Note to self: have backup plan for getting avocados if the internet does explode.

**Comment by dtrudg** [comment]
This is now mentioned in the docs, so closing.
