### ISSUE TITLE
Adding extra directories to bin/singularity PATH

### ISSUE THREAD

**Issue by init-js** [apptainer/singularity#1269]
## Version of Singularity:

2.4.2-dist

### Expected behavior

```
singularity pull docker://myuser/repo:version
...
Cleaning up...
Done. Container is at: ./repo-version.simg
```
### Actual behavior

```
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
/usr/bin/env: ‘python’: No such file or directory
Cleaning up...
ERROR: pulling container failed!
```

### Steps to reproduce behavior

My python distribution is installed via conda, under a subfolder of my home directory. Python is not installed under the usual /usr/local/bin or /usr/bin/ directories.

The singularity main script overwrites `PATH`:

https://github.com/singularityware/singularity/blob/5acfa9c7084814358e98b23f17b38413240a9780/bin/singularity.in#L40

When it executes one of the scripts for the subcommands (e.g. ` singularity/libexec/python/import.py`), the `#!/usr/bin/env python` fails to execute due to the missing executable.

I'm adding the custom directory to the hardcoded list in the singularity main script, as a workaround.

Is this a packaging bug -- should I file this with the bioconda singularity package? Or should "$(dirname "$(which python)")" be added to the list inside the bash script?

**Comment by vsoch** [comment]
Are you able to link the python installation to any of those locations? I think this is done intentionally for security, so only a system installed python (or link to other) could be used.

**Comment by init-js** [comment]
Thank you,

I figured. That's too bad, because everything else runs and installs without superuser permissions. In a way, that's not really different than the bash executable that the singularity script depends on -- It needs the system-wide bash. I'm not sure why there was no default python installed on that box I was running on.

I haven't tried to symlink to /usr/local. Hopefully there aren't too many other python dependencies required to run singularity.

**Comment by dtrudg** [comment]
This is no longer relevant on 3.x as we don't have python code here. Closing.
