### ISSUE TITLE
implausibly old time stamp -9223372036854775808

### ISSUE THREAD

**Issue by soichih** [apptainer/singularity#1271]
When I run any docker container with singularity (2.4.1-dist), I see following output before the container startup (successfuly, I believe..)

```
$ singularity --version
2.4.1-dist
$ singularity exec docker://busybox whoami
Docker image path: index.docker.io/library/busybox:latest
Cache folder set to /home/hayashis/.singularity/docker
Creating container runtime...
tar: ./.exec: implausibly old time stamp -9223372036854775808
tar: ./.run: implausibly old time stamp -9223372036854775808
tar: ./.shell: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/exec: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/run: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/shell: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/start: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/test: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/01-base.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/90-environment.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/95-apps.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/99-base.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/libs: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/runscript: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/startscript: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d: implausibly old time stamp -9223372036854775808
tar: ./.test: implausibly old time stamp -9223372036854775808
tar: ./dev: implausibly old time stamp -9223372036854775808
tar: ./environment: implausibly old time stamp -9223372036854775808
tar: ./etc/hosts: implausibly old time stamp -9223372036854775808
tar: ./etc/resolv.conf: implausibly old time stamp -9223372036854775808
tar: ./etc: implausibly old time stamp -9223372036854775808
tar: ./home: implausibly old time stamp -9223372036854775808
tar: ./proc: implausibly old time stamp -9223372036854775808
tar: ./root: implausibly old time stamp -9223372036854775808
tar: ./singularity: implausibly old time stamp -9223372036854775808
tar: ./sys: implausibly old time stamp -9223372036854775808
tar: ./tmp: implausibly old time stamp -9223372036854775808
tar: ./var/tmp: implausibly old time stamp -9223372036854775808
tar: ./var: implausibly old time stamp -9223372036854775808
tar: .: implausibly old time stamp -9223372036854775808
hayashis
```

This happens on Ubuntu 16.04 hosts, and I've installed singularity via neurodebian repo.

**Comment by tpdownes** [comment]
I have seen this as well with 2.4.2 from debian.org on Deb8 and Deb9. In fact, the timestamp really is implausibly old:
```
lrwxrwxrwx  1 thomas.downes uwmlsc   36 -9223372036854775808 environment -> .singularity.d/env/90-environment.sh
```

**Comment by bhuntley** [comment]
I'm also seeing this in 2.5.2 on Ubuntu 16.04.4 when following the [Singularity exec python example](http://singularity.lbl.gov/docs-exec):

```
$ singularity --version
2.5.2-dist
```
```
$ singularity exec docker://python:latest /usr/local/bin/python hello.py
Docker image path: index.docker.io/library/python:latest
Cache folder set to /home/bhuntley/.singularity/docker
Creating container runtime...
tar: ./.exec: implausibly old time stamp -9223372036854775808
tar: ./.run: implausibly old time stamp -9223372036854775808
tar: ./.shell: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/exec: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/run: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/shell: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/start: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/test: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/01-base.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/90-environment.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/95-apps.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/99-base.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/99-runtimevars.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/libs: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/runscript: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/startscript: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d: implausibly old time stamp -9223372036854775808
tar: ./.test: implausibly old time stamp -9223372036854775808
tar: ./dev: implausibly old time stamp -9223372036854775808
tar: ./environment: implausibly old time stamp -9223372036854775808
tar: ./etc/hosts: implausibly old time stamp -9223372036854775808
tar: ./etc/resolv.conf: implausibly old time stamp -9223372036854775808
tar: ./etc: implausibly old time stamp -9223372036854775808
tar: ./home: implausibly old time stamp -9223372036854775808
tar: ./proc: implausibly old time stamp -9223372036854775808
tar: ./root: implausibly old time stamp -9223372036854775808
tar: ./singularity: implausibly old time stamp -9223372036854775808
tar: ./sys: implausibly old time stamp -9223372036854775808
tar: ./tmp: implausibly old time stamp -9223372036854775808
tar: ./var/tmp: implausibly old time stamp -9223372036854775808
tar: ./var: implausibly old time stamp -9223372036854775808
tar: .: implausibly old time stamp -9223372036854775808
Exploding layer: sha256:55cbf04beb7001d222c71bfdeae780bda19d5cb37b8dbd65ff0d3e6a0b9b74e6.tar.gz
Exploding layer: sha256:1607093a898cc241de8712e4361dcd907898fff35b945adca42db3963f3827b3.tar.gz
Exploding layer: sha256:9a8ea045c9261c180a34df19cfc9bb3c3f28f29b279bf964ee801536e8244f2f.tar.gz
Exploding layer: sha256:d4eee24d4dacb41c21411e0477a741655303cdc48b18a948632c31f0f3a70bb8.tar.gz
Exploding layer: sha256:b59856e9f0abefedc34fcefc3f57c4955cc384785663745532ddc31a89641c83.tar.gz
Exploding layer: sha256:b023afffd10b07f646968c0f1405ac7b611feca6da6fbc2bb8c55f2492bdde07.tar.gz
Exploding layer: sha256:13e2e806d7c88f357958d798c097b4fc0cd6e3aea888ad7e584fba5a0e7d3ec9.tar.gz
Exploding layer: sha256:e90bc178f0458c231d8e355756f9f0f51e22a4e6c5ff8c9c6cb8e48d2c158000.tar.gz
Exploding layer: sha256:b381a7ef2d268da7e0fee1c43a469c13e93c948e550bf9e1dc68102f39138b15.tar.gz
Exploding layer: sha256:d1829188d780a3a1f2e73a75acc5268ed87b414ea9881bc132cf1bf1d42d5719.tar.gz
Hello World: The Python version is 3.7.0
```

Please let me know if I can provide any additional debugging info

**Comment by jakirkham** [comment]
Also seeing this issue with Singularity 2.5.2 on Ubuntu 16.04. Would it be possible for someone to look at this and help us debug it?

**Comment by dtrudg** [comment]
@jakirkham @bhuntley - are you also using debian / neurodebian packages of Singularity?

@soichih @tpdownes - it'd be great to know if you can replicate this with an install of Singularity from source, if that's possible for you to do.

**Comment by bhuntley** [comment]
@dctrud I was using the neurodebian package install.

**Comment by tpdownes** [comment]
@dctrud Just back from vacation and digging out from underneath. I will try to find the time - do you want me to go straight to a 2.6 build from source or pick [the same version I'm using](https://packages.debian.org/stretch-backports/singularity-container)?

**Comment by dtrudg** [comment]
@tpdownes - 2.6. from source is okay - there hasn't been anything changed that would affect the error being present or not across recent-ish versions.

**Comment by colindaven** [comment]
Same here, also using the neurodebian packages of Singularity on Ubuntu 1604

singularity --version
2.6.1-dist

**Comment by jscook2345** [comment]
@colindaven 

Do you see the same issue when building from source with 2.6.1 or 3.0.X?

**Comment by GodloveD** [comment]
This should be fixed in 3.0.x right?  Because we are now using the same tools that Docker uses to download layers from registries rather than rolling our own?  Can someone confirm plz?

**Comment by jscook2345** [comment]
This looks to be fixed in 3.X.

[vagrant@localhost ~]$ singularity version
3.0.2-91.g2f30625

[vagrant@localhost ~]$ singularity exec docker://python:latest /usr/local/bin/python --version
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:cd8eada9c7bb496eb685fc6d2198c33db7cb05daf0fde42e4cf5bf0127cbdf38
 43.22 MiB / 43.22 MiB [====================================================] 9s
Copying blob sha256:c2677faec825930a8844845f55454ee0495ceb5bea9fc904d5b3125de863dc1d
 10.28 MiB / 10.28 MiB [====================================================] 2s
Copying blob sha256:fcce419a96b1219a265bf7a933d66b585a6f8d73448533f3833c73ad49fb5e88
 4.14 MiB / 4.14 MiB [======================================================] 1s
Copying blob sha256:045b51e26e750443c84216071a1367a7aae0b76245800629dc04934628b4b1ea
 47.74 MiB / 47.74 MiB [===================================================] 10s
Copying blob sha256:3b969ad6f1474525a12e57e0f9fad719fa0899131fe190ce876b8bd4d998cbbf
 204.35 MiB / 204.35 MiB [=================================================] 41s
Copying blob sha256:2d18bcd81c3712dbc63e5317e5e7afaf8fb84721c87c85957693d922f01c92e7
 5.56 MiB / 5.56 MiB [======================================================] 1s
Copying blob sha256:8719ec5c24c94206ef4ac0423158651f472fa7b78be7e28d83a5d29057dccecb
 21.39 MiB / 21.39 MiB [====================================================] 4s
Copying blob sha256:6b29038f9369a06125228846b028cd7a16e3dc6dc4472c0c3a8c9e058ed7b876
 239 B / 239 B [============================================================] 0s
Copying blob sha256:239fef4b4f5c92a7446e9ebf85c982359a08ddc7ac5049053d95b9d26278fe09
 1.70 MiB / 1.70 MiB [======================================================] 0s
Copying config sha256:ad4bc4bc5bbc58b1634eeb8d7378ab38220cfffd6198eb3722bbd11fe034376d
 6.16 KiB / 6.16 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: /home/vagrant/.singularity/cache/oci-tmp/47fd3cafa3d01a4358e304bcb2a851076b32c5470d7199b98d4e6ab694ba4052/python_latest.sif
INFO:    Image cached as SIF at /home/vagrant/.singularity/cache/oci-tmp/47fd3cafa3d01a4358e304bcb2a851076b32c5470d7199b98d4e6ab694ba4052/python_latest.sif
Python 3.7.2

**Comment by dtrudg** [comment]
@jscook2345 - 3.x doesn't extract the /.singularity.d contents into the container from a tar file, right? So this error shouldn't be possible on 3.x

It was something to do with builds of 2.x under debian (and the debian reproducible build efforts there) creating a tar for the /singularity.d content with invalid timestamps when singularity is built into a deb package.

**Comment by tpdownes** [comment]
I never had any opportunity to try to build from source. The easiest solutions for me was to build this [really simple docker image](https://github.com/lscsoft/singularity) and run docker inside Debian.

`docker run -v /sandbox:/output --rm ligo/singularity:latest image_to_convert uid gid`

It's not clear to me if you're intending to support `docker2singularity` or not, but I found it to have a fair no. of issues.

**Comment by 0xaf1f** [comment]
@dctrud is right. I filed https://bugs.debian.org/919026 to document it there, but perhaps it's too late to bother with it.

**Comment by 0xaf1f** [comment]
for what it's worth, I fixed it in stretch-backports.

@yarikoptic, if you want to fix this in neurodebian, the patch is here: https://salsa.debian.org/hpc-team/singularity-container/commit/7651056095c1fdae41a8fbb4ba73d3fcf89f3239

**Comment by yarikoptic** [comment]
@0xaf1f Thanks for the buzz!!! why do you think it would be too late for debian proper migration?  it is not even a soft freeze yet, and the patch is tiny.  If we upload -2 to debian proper with that fix, I would just rebuild neurodebian packages from that version and be done ;)

**Comment by 0xaf1f** [comment]
I didn't say it was too late for that, though the security team had us block singularity from Testing (not sure if you've been following debian-hpc or the singularity google group). Anyway, I said it was probably too late to bother (this ticket is a year old) since we should just get the package for 3 out.

**Comment by 0xaf1f** [comment]
I'll upload a -2 to debian if it helps you, though.

**Comment by 0xaf1f** [comment]
> I'll upload a -2 to debian if it helps you, though.

@yarikoptic, I did this two days ago, so you're all clear to update neurodebian to fix this.

**Comment by yarikoptic** [comment]
THANK YOU @0xaf1f  !  Will do.  two days feels like weeks ago to me for some reason ATM ;)

**Comment by 0xaf1f** [comment]
This can be closed now. @yarikoptic seems to have updated neurodebian with the fixed version (2.6.1-2) already: http://neuro.debian.net/pkgs/singularity-container.html

**Comment by 0xaf1f** [comment]
@GodloveD, can you do the honors?

**Comment by GodloveD** [comment]
Thanks @0xaf1f and @yarikoptic !
