### ISSUE TITLE
Signing code should use stable GPGME API, not command-line parsing.

### ISSUE THREAD

**Issue by taltman** [apptainer/singularity#1273]
## Version of Singularity:

Dev

### Expected behavior

Crypto routines should be using the official GPG API using GPGME:
https://www.gnupg.org/documentation/manuals/gpgme/

### Actual behavior

Crypto routines are interacting via the gpg command, which relies on brittle string parsing.

### Steps to reproduce behavior

N/A

**Comment by vsoch** [comment]
Thanks @nl384 ! @yhcote I think you are the master of SIF and would want to be pinged here.

**Comment by jmstover** [comment]
Linking to GPGME cannot be done because of the license, as it is not released under the LGPL.

So the licensing is a full stop there. Other options are being explored.
