### ISSUE TITLE
Singularity container created out of docker image behaves differently than docker container.

### ISSUE THREAD

**Issue by ghost** [apptainer/singularity#1274]
## Version of Singularity:

2.4.1-dist

### Expected behavior

One binary is packaged inside docker image , when we run it as docker container it gives all the options of binary, in short command works fine . Same thing is expected when we run **singularity run docker://image_name** , but it is giving only partial options. Seems like something is getting messed up while creation of singularity container 

### Actual behavior
 Only few options of binary are present inside container.

### Steps to reproduce behavior.
Take any docker image and create a singularity container  with custom binary in it.

**Comment by ArangoGutierrez** [comment]
Hi @Sneha676 can you show the workflow you are implementing, or the docker image you are trying to use, in order to try to reproduce the bug?

Thanks ;)

**Comment by jscook2345** [comment]
@Sneha676 could you share which docker image you're trying to run so we can investigate the issue? This is something that should work without problems.

**Comment by dtrudg** [comment]
Closing as no follow-up r.e. docker container to reproduce this.
