### ISSUE TITLE
update documentation on website for every release for lazy container people like me

### ISSUE THREAD

**Issue by ps-account** [apptainer/singularity#1276]
## Version of Singularity:

e.g. 2.4.2

### Expected behavior

e.g. 2.4.2. is the latest release
I go to  http://singularity.lbl.gov/install-linux
I can copy-paste the lines that install 2.4.2  

### Actual behavior

e.g. 2.4.2. is the latest release
I go to  http://singularity.lbl.gov/install-linux
I can copy-paste the lines that install 2.3.1.  

### Steps to reproduce behavior

not applicable
Maybe make it part of the release automation to update the online documentation.

**Comment by vsoch** [comment]
Thanks @rdwrt this is fixed now! http://singularity.lbl.gov/install-linux
