### ISSUE TITLE
[Hackathon] TODO list

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#1281]
This issue is intended to be a list of [ideas]/[features request] to get hammered at the Hackaton.
The event :
> The Singularity team is planning a hackathon and you are invited! On Feb 22 and 23 the Sylabs team is going to reserve a conference room at Berkeley Marina Double Tree and write a bunch of code together. And you're all welcome to join us! Although the agenda is flexible, we will likely focus efforts on migrating the existing code base from python and shell to golang, and on issues related to OCI compliance. But if there is a special Singularity-related project you would like to work on, bring that too!
> If you're interested in attending, please join the #hackathon channel on the Singularity slack workspace.  If you have not already joined the Singularity slack, just respond to this email and we'll be happy to send you an invitation. We'll be asking for a final head count on slack soon for planning purposes.  
>Hope to see you in Berkeley! 

Proposal methods:
 - Link an existing issue you wish to solve at the event.
 - Label an existing issue with the label [hackathon]
 - Link an existing PR you wish to get merged at the event.
 - Label an existing PR with the label [hackathon]
 - Propose a new idea/feature in a comment on this issue

**Comment by vsoch** [comment]
I think the label is missing an h?

**Comment by ArangoGutierrez** [comment]
Done!

**Comment by DrDaveD** [comment]
I'd like to include issue #1207 but it appears that it requires git repo commit privileges to apply a label.

**Comment by ArangoGutierrez** [comment]
@DrDaveD consider it done

**Comment by ArangoGutierrez** [comment]
Hackathon is over, closing issue

**Comment by vsoch** [comment]
Woohoo thanks for leading this @ArangoGutierrez !
