### ISSUE TITLE
Docker-Singularity squashfs Error

### ISSUE THREAD

**Issue by ortizem** [apptainer/singularity#1288]
## Version of Singularity:

2.4.2-master.g09fb002

### Expected behavior

Singularity exec

### Actual behavior
Singularity: action-suid (U=0,P=18)> Failed to mount squashfs image in (read only): No such device

ERROR  : Failed to mount squashfs image in (read only): No such device
Singularity: action-suid (U=0,P=18)> Retval = 255

ABORT  : Retval = 255

### Steps to reproduce behavior

Docker command: docker run -it --privileged --rm singularitytest

**Comment by vsoch** [comment]
How can we help you today, @ortizem ?

**Comment by ortizem** [comment]
Hi @vsoch, I am trying to run a singularity image inside a Docker container. However, I am getting the following error:
Singularity: action-suid (U=0,P=18)> Failed to mount squashfs image in (read only): No such device

ERROR : Failed to mount squashfs image in (read only): No such device
 Singularity: action-suid (U=0,P=18)> Retval = 255

ABORT : Retval = 255

Please advice.

**Comment by vsoch** [comment]
Afaik this is no longer possible, I ran into the same issue and there was no resolution.

**Comment by ortizem** [comment]
what would you recommend? @vsoch

**Comment by vsoch** [comment]
Follow the example here with volumes:

https://github.com/singularityware/docker2singularity

Note that the containers provided have an older version of Singularity, it might still work with the 2.4 branch but I'm not sure. When I was testing for the singularity global client, installing singularity in singularity, I couldn't get it working. Another option is to try the secure build (--isolated) option. I can help more if you share what you are working on!

**Comment by dtrudg** [comment]
No update here for a while, so closing it.
