### ISSUE TITLE
Support for multicontainer scenario

### ISSUE THREAD

**Issue by raimonbosch** [apptainer/singularity#129]
As we discussed in https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/0sywDDHdi0Y there are some cases where a Singularity scenario with more than one container fails.

In my case I have executed nas/mpi benchmark with 4 different containers:

> mpirun -n 1 singularity exec /mnt/glusterfs/singularity/nasmpi-1.img /trace.sh /NPB/NPB3.3-MPI/bin/bt.C.4 : -n 1 singularity exec /mnt/glusterfs/singularity/nasmpi-2.img /trace.sh /NPB/NPB3.3-MPI/bin/bt.C.4 : -n 1 singularity exec /mnt/glusterfs/singularity/nasmpi-3.img /trace.sh /NPB/NPB3.3-MPI/bin/bt.C.4 : -n 1 singularity exec /mnt/glusterfs/singularity/nasmpi-4.img /trace.sh /NPB/NPB3.3-MPI/bin/bt.C.4

Here you can check the output produced:
https://11149710926098113527.googlegroups.com/attach/86312016e51d0/out.log?part=0.1&view=1&vt=ANaJVrF8CyC7t70BT1aDXj2ErUYboQMEDoOPxCKvmjIRMfX-2zugJLfOtKoJszxchWkn5sR1z4blw1T5C69WMLMRMfj66aSCbrc6i9wX2MvXskTrPA8BUQQ

I always end up with the same error: 

> ERROR: Failed to associate image to loop: Device or resource busy

This experiment worked fine on my local instance with Ubuntu 14.04 and failed on Debian Jessie, so maybe it is a problem affecting only to certain environments.

Thanks in advance,

**Comment by gmkurtzer** [comment]
I think I have this worked out. Can you retest with the current master branch and see if it is indeed fixed?

Thank you!

**Comment by raimonbosch** [comment]
Seems to work fine. Thanks for the fix!

**Comment by gmkurtzer** [comment]
Excellent! Sorry it took so long to ascertain what the problem was!
