### ISSUE TITLE
Building singularity images inside docker

### ISSUE THREAD

**Issue by DeepHorizons** [apptainer/singularity#1291]
## Version of Singularity:

2.4.2-dist

### Expected behavior

`singularity build test.simg docker://ubuntu:16.04`
Some success message

### Actual behavior

```Docker image path: index.docker.io/library/ubuntu:16.04
Cache folder set to /root/.singularity/docker
Importing: base Singularity environment
Importing: /root/.singularity/docker/sha256:1be7f2b886e89a58e59c4e685fcc5905a26ddef3201f290b96f1eff7d778e122.tar.gz
Importing: /root/.singularity/docker/sha256:6fbc4a21b806838b63b774b338c6ad19d696a9e655f50b4e358cc4006c3baa79.tar.gz
Importing: /root/.singularity/docker/sha256:c71a6f8e13782fed125f2247931c3eb20cc0e6428a5d79edb546f1f1405f0e49.tar.gz
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-en: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_i18n_Translation-en: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_InRelease: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_main_i18n_Translation-en: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_restricted_i18n_Translation-en: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.lock: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.partial: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_InRelease: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_main_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_main_i18n_Translation-en: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_restricted_binary-amd64_Packages: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_restricted_i18n_Translation-en: Cannot open: Operation not permitted
tar: Exiting with failure status due to previous errors
Cleaning up...
```
### Steps to reproduce behavior

1. `docker run -it --privileged ubuntu:16.04`
2. Install deps, build and install singularity
3. ``singularity build test.simg docker://ubuntu:16.04`

I have a build server that builds singularity images within docker containers. When experimenting with a new setup I found that I could no longer build the images. I though that something on my system changed when I came across #1288. Is there really no workaround? What is causing it?

**Comment by vsoch** [comment]
I ran into the same troubles! There was some discussion here: https://github.com/singularityware/singularity/issues/1245 I think the "user space" inside the priviledged container won't work, but at least from the discussion there, you could try using sudo. But that might defeat the purpose.

**Comment by vsoch** [comment]
But the whiteout file issue should be fixed, if you are able to install from development.

**Comment by DeepHorizons** [comment]
It looks like you can build singularity images inside of docker on the development branch. Interestingly enough, it looks like you no longer need to add `--privileged` to the docker container!

For posterity, here is what I found.
* Running as root did not help
* I could not use any 2.4 release to build an image in Docker on linux, regardless of the kernel version
* It all works in Docker for Windows
* It looks like you cannot use an image made by the current development branch on 2.4.0, getting a ` Unknown image format/type:`. It thinks its an ext3 image and it doesn't look like I can force it to the squashfs format.

Closing this for now and I'll do some more testing when the next release comes out

**Comment by vsoch** [comment]
woohoo! I guess Windows fit the bill, and who knows if that is a feature or a bug :) The underlying assume might also be the case so Singularity wouldn't work in Singularity, but we'd have a hard time testing that in Windows. Thanks for the update, and glad that your issue is resolved.

**Comment by DeepHorizons** [comment]
As an update to this, it seems to work in 2.4.3 but not 2.4.4, so it looks like we need the `docker-extract` functionality.

**Comment by dtrudg** [comment]
@DeepHorizons - yes, there is an interaction between extracting these .wh. files and the aufs setup that docker is actually using. The docker-extract code ensures they never reach the filesystem in the docker container, so it works. There will be a 2.5 available with the docker-extract functionality added back in very soon.

**Comment by dtrudg** [comment]
Here's the PR in the works... #1371

**Comment by dtrudg** [comment]
Closing as 2.5.0 includes fixes to handle whiteout file `.wh.' files so they are not extracted, and will not interact with aufs in the environment. Please feel free to reopen if you experience any further issues with this.
