### ISSUE TITLE
Building with --disable-suid still requires root for some things

### ISSUE THREAD

**Issue by jakirkham** [apptainer/singularity#1297]
After building with the `--disable-suid` option passed to `./configure` and without `sudo`, am finding that `singularity` still needs `root` for some things. In particular, running the following generates the error seen below. Maybe I'm not understanding what `--disable-suid` means. 😕

```
$ singularity pull docker://jakirkham/centos_conda
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
ERROR  : Specified configuration file /groups/dudman/home/kirkhamj/miniconda/envs/test/etc/singularity/singularity.conf is not owned by root
ERROR  : Called singularity_config_get_value on uninitialized config subsystem
ABORT  : Retval = 255
ERROR: pulling container failed!
```

**Comment by dtrudg** [comment]
Hi @jakirkham - this looks like a bug, and I'm looking further at it now.

**Comment by jakirkham** [comment]
Oh ok. Thanks for confirming @dctrud. Wasn't sure if I made a mistake somewhere.

**Comment by jakirkham** [comment]
To make sure I understand correctly, with `--disable-suid` it should not be necessary to do `sudo make install`, right? Or is that still needed for some reason?

**Comment by jmstover** [comment]
@jakirkham 
That's correct. There was a check that was specifically looking to see if the `singularity.conf` file was owned by root. That was in there prior to the ability to run without SUID being added... and was overlooked.

PR #1299 should fix it.

**Comment by jakirkham** [comment]
Ah ok. Great thanks! Still learning this stuff. :)

**Comment by jmstover** [comment]
Just committed #1299 to the development branch, so going forward this should be taken care of.

Thanks.

**Comment by jakirkham** [comment]
Thank you both.
