### ISSUE TITLE
/proc should not be bind mounted

### ISSUE THREAD

**Issue by jjohnson42** [apptainer/singularity#13]
should mount new  proc.  The container running in a new pid namespace would see inaccurate content in /proc for all the processes that "don't exist".

mount a new proc.  This would give the same data, except for things like processes, which would be tailored to the container environment rather than reflect the parent system.

There may be similar considerations for /sys, but I'm not 100% sure.  Might err on the side of doing new mount for sys if I had to choose personally.

**Comment by jjohnson42** [comment]
sorry, didn't look more carefully...

**Comment by gmkurtzer** [comment]
You raise an interesting question for /sys. That deserves some research!

**Comment by jjohnson42** [comment]
Yeah, I can't think of anything concretely, but I was just doing it as a new mount 'just because' sys didn't have any complexity and seemed to double mount fine, and erred on the side of caution.  There might be no good reason, but it didn't seem harmful either.

**Comment by gmkurtzer** [comment]
Can you do a cursory check to see if there are any obvious differences between the two sysfs file systems? Thanks!

**Comment by jjohnson42** [comment]
I didn't see anything, unless I unshare the network namespace...  For singularity that wouldn't matter because an unshared network is precisely the PITA that singularity would avoid...

It does show that sysfs is at least somehow sensitive to namespaces in some way, but at the moment, I didn't see anything concrete relevant to singularity use case.

**Comment by gmkurtzer** [comment]
I think on principal, I will mount sysfs properly and let the kernel deal with any namespace specifics that maybe necessary (or not).

Thanks again for pointing this out Jarrod!
