### ISSUE TITLE
CUDA containers are failing when exec with -c --nv

### ISSUE THREAD

**Issue by paulo7777** [apptainer/singularity#1306]
## Version of Singularity:

2.4.2

### Expected behavior

Expect to expose the CUDA driver and correct run the container.

### Actual behavior

CUDA error with Chainer and Detectron containers.
`/dev/nvidia*` files are missing when add `-c`

### Steps to reproduce behavior

Just try to run any CUDA container with `singularity exec -c --nv`

**Comment by GodloveD** [comment]
@paulo7777 please check to see if https://github.com/singularityware/singularity/pull/1358 fixes this issue.  Thanks!

**Comment by dtrudg** [comment]
Closing this issues as it was fixed with #1358 which has been merged. Feel free to reopen if any further issue. Thanks.
