### ISSUE TITLE
Error parsing /etc/singularity.conf with trailing spaces

### ISSUE THREAD

**Issue by paulo7777** [apptainer/singularity#1309]
## Version of Singularity:

2.4.1

### Expected behavior

Parse  /etc/singularity.conf with trailing spaces.

### Actual behavior

In /etc/singularity.conf if you do something like
"config group no " (note the trailing space)
singularity will complain about not being able to parse it.

### Steps to reproduce behavior

Add trailing spaces to etc/singularity.conf

**Comment by jscook2345** [comment]
This seems to be fixed at least in 3.X. Thanks for the report @paulo7777 !
