### ISSUE TITLE
minor: please use git annotated (or better signed) tags

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#131]
``` shell
$> git describe 
fatal: No annotated tags can describe 'e27614b6abbc53e54d0bc03053086435db89e47d'.
However, there were unannotated tags: try --tags.

$> git describe --tags
2.0-216-ge27614b
```

let me know if I should elaborate why annotated tags

**Comment by gmkurtzer** [comment]
I am still getting used to Git, I will google before asking. Lol

Thanks for the suggestion!

**Comment by gmkurtzer** [comment]
It seems like there is some discrepancy between GitHub releases and Git repository tagging. While creating an annotated release in Git is straight forward, are you aware of how to also do a full GitHub release while annotating the Git tag (e.g. can I annotate a GitHub tag after the fact)?

Thanks!

**Comment by yarikoptic** [comment]
Yes
I usually make annotated tag, and then make a release out of it on github. I think it copies your tag text (or if don't, just copy paste yourself 😃)

**Comment by gmkurtzer** [comment]
Very cool, I will do that on the next release. Thanks!

BTW: Shortly I will be updating the 2.x branch and doing a GitHub pre-release for 2.1. YAY!

**Comment by yarikoptic** [comment]
congrats! just please be consistent ;)

``` shell
$> git tag
1.0
2.0
v2.1-testing
```

2.1-testing is indeed compliant with http://semver.org but may be you would have preferred more "conventional" `-alpha0` ? ;)

**Comment by gmkurtzer** [comment]
Yeah, I was reading up on "standardized" nomenclature. I wonder if I can rename it? Lol

**Comment by rhc54** [comment]
you _can_, but it not recommended. Note that we never tag release candidates, but only actual releases - but you can do as you wish! 😄

**Comment by gmkurtzer** [comment]
It is my intention to delete the testing tag once the formal release has been made. Some of this is me trying to learn the "GitHub" way of doing things.

**Comment by yarikoptic** [comment]
Well, technically speaking there is no need to delete any tag, alpha release our what not... just stay uniform.
It is somewhat of a git cons, that tags are viral. Even though you remove it, I already have it, and would need to remove it manually too . So if you have intent to remove or rename it, do it ASAP before more ppl fetched it in their repos

**Comment by gmkurtzer** [comment]
Is it better practice to remove the v in the current prerelease, or just leave it there and be more consistent for future releaseS?

**Comment by rhc54** [comment]
Definitely better to not edit existing tags. Just move forward with whatever standard you decide upon

**Comment by gmkurtzer** [comment]
Will do, thanks!

**Comment by gmkurtzer** [comment]
I believe I did this correctly this time. :)
