### ISSUE TITLE
build.exec builds in /tmp, ignoring TMPDIR

### ISSUE THREAD

**Issue by cruegge** [apptainer/singularity#1310]
The reason appears to be this line, where `SINGULARITY_TMPDIR` (which is undefined) is used instead of `TMPDIR`:

https://github.com/singularityware/singularity/blob/f2d7795d04bad5af371c3a4a0a6f372ba07ff810/libexec/cli/build.exec#L224

This can be a problem when `/tmp` is a small tmpfs. If the behaviour is intended, the variable should probably be mentioned somewhere.

**Comment by dtrudg** [comment]
Hi @cruegge please see the docs at: http://singularity.lbl.gov/build-environment which mention the SINGULARITY_TMPDIR variable. Thanks!

**Comment by cruegge** [comment]
Right, I should have searched more thoroughly. Thanks for help!
