### ISSUE TITLE
run command does not default to /bin/bash

### ISSUE THREAD

**Issue by max-mapper** [apptainer/singularity#1312]
## Version of Singularity:

2.4.2-dist

### Expected behavior

According to these docs http://singularity.lbl.gov/docs-run  "If the user has not deifned a runscript, and there is no ENTRYPOINT or CMD (or we aren’t importing Docker at all) then we default to /bin/bash"

### Actual behavior

I created a singularity image from a `systemd-nspawn` .img w/ ubuntu installed in it. When I run `singularity run singularity.img` I receive this error:

```
$ singularity run singularity.img
ERROR  : No run driver found inside container
ABORT  : Retval = 255
```

### Steps to reproduce behavior

First start a with a regular bootable linux disk image (not a singularity 'special' disk image)

```
#!/usr/bin/bash
set -e
mkdir mnt
sudo losetup -Pf ubuntu.img
sudo mount /dev/loop0p1 mnt
sudo singularity build --writable singularity.img mnt
sudo umount mnt
```

**Comment by jmstover** [comment]
Hi,

  I'm not 100% sure if it's going to run correctly that way... Can you try:

    singularity exec singularity.img /bin/ls -a /

  I'm thinking the entire /.singularity.d structure isn't there (or /.run,
/.exec, etc...). So, the hooks that it uses to spawn off in into the image
isn't there. Calling exec should try spawning off the requested program
directly without the helper script if it can't find it.

-J

**Comment by max-mapper** [comment]
Yes that command works. So in order for `singularity run` to work, you have to put singularity specific files inside your disk image?

**Comment by vsoch** [comment]
Exactly - there is a metadata folder `.singularity.d` that has various actions (also in that folder in a subdirectory) that will handle things like sourcing the environment, check for a runscript, and then (if not found) default to the shell. Older versions of singularity have the same deal, but without the metadata folder and with flat files on the base level (e.g., /environment, /singularity). So if you don't have either of those, the run command won't work. But you can use exec that tells singularity the command that you want, and that would work!

**Comment by max-mapper** [comment]
@vsoch Thank you. Does any documentation exist for what should get written to `.singularity.d` to make `singularity run` work? Do I just need to write `/.singularity.d/runscript` into my container (from the example here http://singularity.lbl.gov/docs-run)?

**Comment by vsoch** [comment]
You shouldn't need to write anything like that - the snippet that you write in the `%runscript` section of the file will be written there.

**Comment by vsoch** [comment]
I don't know what `systemd-nspawn` is, but if you have to get this working, if you dump the environment.tar in there, it should find the driver and let you shell in and look around.

**Comment by vsoch** [comment]
this dude --> https://github.com/singularityware/singularity/blob/master/libexec/bootstrap-scripts/environment/Makefile.am or here is the logic for finding it on your system https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/docker/api.py#L414 and a fallback: https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/docker/environment.tar

Still kind of a hack, but if you must get something working...

**Comment by max-mapper** [comment]
@vsoch Thanks, `systemd-nspawn` is the container runtime that is built into systemd (Ubuntu, Arch etc). I'm trying to make images compatible with both singularity and system-nspawn, as they each offer unique features. When I create images from a sandbox my resulting singularity images do not contain a `/.singularity.d` folder, presumably because I'm not building from a singularity recipe, so I am needing to implement these files myself in order to make the commands like `singularity run` work (and also to kill warnings like `WARNING: Container does not have an exec helper script`)

**Comment by vsoch** [comment]
ah ok! Then you should be able to try extracting that environment.tar (ideally the one built on your host) into the container and giving it a go :)

**Comment by vsoch** [comment]
the "helper" scripts are the ones named appropriately for each action. You can poke around the folder and the Makefile to see how it works. Granted there will eventually be more of a proper header in the image format, this is how it is for now.

**Comment by max-mapper** [comment]
@vsoch yay thank you for the tar file, I grabbed these files from it and put them into my container and `singularity run` works as expected now:

```
/.exec -> .singularity.d/actions/exec
/.run -> .singularity.d/actions/run
/.shell -> .singularity.d/actions/shell
/.test -> .singularity.d/actions/test
/.singularity.d
/singularity -> .singularity.d/runscript
```

It would be nice if these files were installed when building from a sandbox, but closing this issue for now.
