### ISSUE TITLE
List available containers on CLI 

### ISSUE THREAD

**Issue by apeltzer** [apptainer/singularity#1327]
Maybe this is something for Singularity Hub, but I'd love to see something like 

```
singularity list shub://path/to/singularity/hub/image 
```
and then get a list of available versions maybe?

**Comment by vsoch** [comment]
You can do this with singularity global client! https://singularityhub.github.io/sregistry-cli/client-hub#search

**Comment by apeltzer** [comment]
Good point - I was so into my `singularity <toolname>` command and totally forgot about it. Will close this, thanks again @vsoch !

**Comment by vsoch** [comment]
Here you go @apeltzer ! 

[![asciicast](https://asciinema.org/a/164767.png)](https://asciinema.org/a/164767?speed=3)
