### ISSUE TITLE
password for new user not working

### ISSUE THREAD

**Issue by ponomarevsy** [apptainer/singularity#1328]
## Version of Singularity:

singularity/2.2.1-GCC-4.8.4

### Expected behavior

I've created a Centos 7 singularity container for a LifeScope application (since I could not find a Centos 5 repository for singularity that LifeScope supports). I, then, created a new user and gave that user a password. I would expect that if I login into the container as myself and then do "su - newuser" I should be able to become him after entering the new password.

### Actual behavior

I am unable to "su - newuser" because the new password is not working. I've tried changing the newuser's password to smth else, but, again, it does not let me become the new user after I login as myself (not root) with the "su - newuser" command. I get "su: Authentication failure" 

### Steps to reproduce behavior

Create a Centos 7 singularity image (as root)
Add a new user with useradd command, set the new password for that user with passwd newuser (as root)
Start the singularity image (as myself)
Use "su - newuser" command to become the new user (as myself)

The password assigned to the user is not working. Does singularity support "su" command?

**Comment by jmstover** [comment]
Hi @ponomarevsy,

  No you can't use the `su` command in a container started as a normal user. The reason is that privilege escalation is blocked by Singularity... but the `su` command is set uid. So it cannot cannot change privileges.

-J

**Comment by ponomarevsy** [comment]
Gotcha! Thank you very much.
