### ISSUE TITLE
failure to create image using dd versions without 'none' in status option

### ISSUE THREAD

**Issue by bafonso** [apptainer/singularity#1333]
## Version of Singularity:
current git version, 2.4.2-master.g09fb002

### Expected behavior

image.create would create an image.

### Actual behavior

no image is created because it fails to run the dd command.
```
bruno@bruno-VirtualBox:~/singularity-vm$ sudo singularity image.create --size 1000 yep.img
Creating empty 1000MiB image file: yep.img
dd: invalid status flag: 'none'
Try 'dd --help' for more information.
ERROR: Failed creating image!
```

### Steps to reproduce behavior

download xubuntu 12.04(xubuntu-12.04.4-desktop-amd64.iso) and issue singularity image.create

**Comment by dtrudg** [comment]
Also reported by hwleong in slack for...

hwleong [10:17 AM]
ah... using 2.5.1, and SLES 11.3

**Comment by jmstover** [comment]
I think we need to do a check in `image.create.exec`/`image.expand.exec` for the OS ... or on the binary.

```
$ dd --version
dd (coreutils) 8.12
  [...]
$ dd --help | grep 'status'
  status=noxfer    suppress transfer statistics
```

Compared to one where I can set `status=none`
```
$ dd --version
dd (coreutils) 8.25
  [...]
$ dd --help | grep 'status'
  status=LEVEL    The LEVEL of information to print to stderr;
```
