### ISSUE TITLE
In container home directories

### ISSUE THREAD

**Issue by beojan** [apptainer/singularity#1334]
The sanitized home option (-H) enables mounting a custom directory as the home directory.

Would it be possible to do the same, but using a home directory that exists within the container already instead of mounting one?

**Comment by dtrudg** [comment]
Hi @beojan - could you give a little more background on the situation you'd like to do this in?

I can think of some situations where it'd be useful... e.g. some large neuroscience containers based on neurodebian, where there is a `/home/neuro` with things that need to be sourced or accessed when the container is run. Under docker you'd run as user neuro in the container... but this is not possible with Singularity's model. The concern for just setting a home directory path that's in the container is permissions - if the directory is 700 in the container and not owned by the host user, then at runtime they might not be able to get to it. It needs to be considered how to handle this type of thing.

Thanks!

**Comment by beojan** [comment]
It's pretty similar to what you describe, I'm trying to use an ATLAS docker image that needs to run the .bashrc in /home/atlas. When I tried it, the files in that directory seemed to be owned by the host user.

**Comment by dtrudg** [comment]
@beojan - is it a public docker container? If so, would you mind sharing the location?

**Comment by beojan** [comment]
I don't know if it's supposed to be public, but it is. See https://github.com/UCATLAS/xAODAnaHelpers/issues/1168 (last few comments)

**Comment by jscook2345** [comment]
@beojan 

It appears I cannot access that registry. When I try to get at it I get 403's or a CERN sign-in page. Do they also use dockerhub?

**Comment by beojan** [comment]
Try this one: https://hub.docker.com/r/atlas/analysisbase/

**Comment by afortiorama** [comment]
> if the directory is 700 in the container and not owned by the host user, then at runtime they might not be able to get to it. 

I had this problem with atlas images and got this answer https://github.com/sylabs/singularity/issues/1132#issuecomment-407104957

In ATLAS users are going to use both docker and singularity depending on where they run their image and the fact that /home/atlas is inaccessible in singularity means that users have to change what they do. If /home/atlas access could be preserved it would solve the problem of forcing the users not to use /home for anything in case they have to use singularity.

**Comment by jscook2345** [comment]
@beojan 

I tend to concur with the comment @dctrud left in #1132. It would be best to create a simple definition file and change the ownership of `/home/atlas`. Than you could run each of the scripts you need.

The file would likely look something like the following depending on what files you need to run / need access to.

<pre>
bootstrap: docker
from: atlas/analysisbase

%post
  chmod -R 755 /home/atlas
</pre>

**Comment by afortiorama** [comment]
We use singularity exec on the WNs. We don't build the images.

**Comment by jscook2345** [comment]
@afortiorama 

Without building an image where you have some control over the end result, the only thing you can do is put in a request upstream to the 'atlas/analysisbase' maintainer, and see if they will open the permissions on the /home/atlas directory. Otherwise, with our permission model, it isn't going to work as is.

**Comment by jscook2345** [comment]
Closing for now. Please comment here if you have any follow-ups. Thanks!
