### ISSUE TITLE
consider making wrapper scripts fail "early" and upon any "undefined variable" via adding `set -eu`

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#134]
singularity ships a number of shell scripts, but unfortunately none of them is "paranoid enough" to enforce that they exit as soon as error occurs (in a pipe or a compound command) or some undefined variable is used.  Not sure which are invoked/used while running root-suided sexec, but I think it could be a good "stability" and possibly "security" measure if behavior of those scripts would become more "deterministic" in some sense, by forcing the assumptions that all errored executions are failures (unless specifically handled) and that all variables must be defined after some point in their execution life.

**Comment by gmkurtzer** [comment]
I'm not sure I exactly follow... Is this something you could help with or give me some specific examples to help me see exactly what you are thinking of?

Thanks!

**Comment by yarikoptic** [comment]
Oh sure... will do later today
Cheers

**Comment by gmkurtzer** [comment]
I think this is pretty much done at this point. I have set -u in functions, and set -e in bootstrap'ing (and fixed the bugs associated with doing that). Do you feel there is more I should do here, or am I clear to close this issue?

Thanks!

**Comment by yarikoptic** [comment]
since indeed set-ings get inherited and now present in main functions, I guess set -u would do its role in other scripts.  But you think it is not worthwhile of similar `-e`  "protection" all throughout the scripts?

**Comment by gmkurtzer** [comment]
Implementing -e across the board had a lot of unintended consequences, for example I am currently trying to catch errors and print a decent notification. With -e set, it would just stop because the controlling shell would exit before it could print a notification/error/warning.

I figured though that some things like the bootstrapping should indeed quit on error. Thoughts?

**Comment by yarikoptic** [comment]
could you point me to specific lines?  it is just a matter I guess again of explicit statements/assessment of result of execution of the line in question, e.g.

``` shell
$> bash /tmp/1.sh   
/bin/ls: cannot access 'alskjdf': No such file or directory
ls failed. too bad

$> cat /tmp/1.sh
#!/bin/bash

set -e
set -u

if ! /bin/ls alskjdf; then
   echo "ls failed. too bad"
   exit 1
fi

echo "the end"
```

**Comment by gmkurtzer** [comment]
I found that the test.sh was just stop at random places when -e was set, and it made debugging very difficult. If you want to see for yourself add 'set -e' right above where it sources the functions, and then run test.sh. Here is my output:

```
 + singularity mount -h                                         (retval=0) OK
 + singularity mount --help                                     (retval=0) OK
 + singularity help bogus                                       [gmk@centos7-x64 singularity]$ 
```

**Comment by gmkurtzer** [comment]
I am currently using set -u and set -e in various places in the shell code so I'm gonna close this. If for any reason it needs to be reopened, comment on it and I'll reopen.

Thanks!
