### ISSUE TITLE
Automatic build on Singularity hub: no space left

### ISSUE THREAD

**Issue by ShaopengLiu1** [apptainer/singularity#1341]
## Version of Singularity:

Singularity hub website

### Expected behavior

Build "zhanglab/atac-seq:full" image success

More on the issue:
1, I have 2 containers to build, atac-seq:mm10 (5GB) is smaller, and atac-seq:full (20GB) is larger.
2, both works locally in server.
3, the larger one had error when I use singularity hub to build the container, the smaller one is done.

### Actual behavior

Failed with error "No space left on device"

Start Time: Tue Feb 27 08:12:00 UTC 2018.
Cloning into '/tmp/tmp96tut8zb'...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
ERROR Return Code 1: b"Using container recipe deffile: /tmp/tmp96tut8zb/shub/Singularity.full
Building into existing container: /root/build
Using container recipe deffile: Singularity.full
Sanitizing environment
\x1b[0mAdding base Singularity environment to container
Docker image path: index.docker.io/zhanglab/atac-seq:full
Cache folder set to /root/.singularity/docker
[1/18] ||----------------------------------| 0.0% 
[1/18] |=|---------------------------------| 5.6% 
[2/18] |===|-------------------------------| 11.1% 
[3/18] |=====|-----------------------------| 16.7% 
[4/18] |=======|---------------------------| 22.2% 
[5/18] |=========|-------------------------| 27.8% 
[6/18] |===========|-----------------------| 33.3% 
[7/18] |=============|---------------------| 38.9% 
[8/18] |===============|-------------------| 44.4% 
[9/18] |=================|-----------------| 50.0% 
[10/18] |===================|---------------| 55.6% 
[11/18] |=====================|-------------| 61.1% 
[12/18] |=======================|-----------| 66.7% 
[13/18] |=========================|---------| 72.2% 
[14/18] |===========================|-------| 77.8% 
[15/18] |=============================|-----| 83.3% 
[16/18] |===============================|---| 88.9% 
[17/18] |=================================|-| 94.4% 
[18/18] |===================================| 100.0% 
Exploding layer: sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913.tar.gz
Exploding layer: sha256:c59d01a7e4caf1aba785eb33192fec3f96e4ab01975962bcec10f4989a6edcc6.tar.gz
Exploding layer: sha256:41ba73a9054d231e1f555c40a74762276900cc6487f5c6cf13b89c7606635c67.tar.gz
Exploding layer: sha256:f1bbfd495cc1112b503350686641ee4fa2cea8ccd13fb8a8a302c81dae61d418.tar.gz
Exploding layer: sha256:0c346f7223e24b517358f52c4a3f5f9af1c86e5ddeaee5659c8889846e46d1e2.tar.gz
Exploding layer: sha256:41af47d162e80394e516303fb010690e4c40f18683ccbde30828920280feaff8.tar.gz
Exploding layer: sha256:5ea4c246f5182726f48e26901f5fabb9a025668744ed077733f259d3c81d16ff.tar.gz
Exploding layer: sha256:f37efea17ef1d4d7bd54b185cb85bfb77e048b3743aa0b4c6e0910a041de889b.tar.gz
Exploding layer: sha256:ca5f4e61341fae6370b1ba8a19beae974f1e864f60e5494454d65e62864eede4.tar.gz
Exploding layer: sha256:cd3a1cfb6d53a4862ba8f5104374cf688633c635d6482c151d2a9fa78dec6bf5.tar.gz
Exploding layer: sha256:089e066d68dd1a4a9e7e135380bf11f016525a7b01c533f5c1aef699e798ea5c.tar.gz
Exploding layer: sha256:bfb949df8a44fa8f403ad5ad80d54493f19df9fbce7cc677cd6b1a27079a9522.tar.gz
Exploding layer: sha256:b89bcdda908a55770e5c2766a9ef9da64e4e2cad3e80058b4566e521750bcc01.tar.gz
Exploding layer: sha256:ca4bf2049833c71b3c9a033fb67adf30785bcfb6f2faafedf53a71818d079020.tar.gz
Exploding layer: sha256:6bf7d2a7af71b33c064b8c9f6c7b73a087a8489b23ebc63ea269386c48932479.tar.gz
Exploding layer: sha256:6ad072b938c2045fc5dbc727cb24d8329f2dd88cf7eef1dce175312d33c3854e.tar.gz
Exploding layer: sha256:3b0045be80b0d0febba765abf3adf5b98f3f23df495766dfad7980e35d157165.tar.gz
Exploding layer: sha256:3a87537e0ea447d3b6e9d5e9a221c647c5b88c956322383040050bc2c5b7d7d7.tar.gz
tar: atac_seq/Resource/Genome/mm10/bwa_index_mm10/mm10.fa.bwt: Wrote only 1536 of 10240 bytes
tar: atac_seq/Resource/Genome/mm10/bwa_index_mm10/mm10.fa.pac: Cannot write: No space left on device
tar: atac_seq/Resource/Genome/mm10/bwa_index_mm10/mm10.fa.sa: Cannot write: No space left on device

### Steps to reproduce behavior
https://github.com/Wustl-Zhanglab/ATAC-seq_QC_analysis/tree/master/shub

**Comment by vsoch** [comment]
Did you try the larger builder as I mentioned on your first post to the list?

**Comment by ShaopengLiu1** [comment]
Thanks for your reply @vsoch !

I have tried but it still doesn't work.
There are 3 builders:
1, singularity-builder-2-4-1-50gb
2, singularity-builder-2-4-1-jan-2018 (default)
3, singularity-builder-2-4-50gb

I didn't find the 100GB builder, all of the 3 failed. My container is 20GB in total, based on the build description, 20*2 < 50, why the 50gb builder doesn't work?

By the way, how can I manually set the file size parameter for singularity hub?

Thanks very much!
Best,
Shaopeng

**Comment by vsoch** [comment]
hey @ShaopengLiu1 ! We will update the builders with the (soon I believe)  release of 2.4.3, and at that time I'll remake the 100GB builder. The 100GB builder was deprecated as a security measure given the issues found in the past. For the meantime, you can use the smaller of your builders, or try something that downloads needed data at runtime. 

You shouldn't need to set the file size - we are building squashfs that calculates that during build, and the final image is sized as needed.

**Comment by ShaopengLiu1** [comment]
Thanks very much! 

By the way, is there anyway to push my local container into the Singularity hub like Docker does?

**Comment by vsoch** [comment]
Not for Singularity Hub, but if you or your institution deploys a Singularity Registry (the open source version of Singularity Hub but not with builders yet) you can push to your heart's content! Check out the tools here: https://singularityhub.github.io/

Any feedback about builders or plugins you might want would be appreciated, and contributions too!

**Comment by ShaopengLiu1** [comment]
Thanks very much! I really appreciate your kind help!

**Comment by vsoch** [comment]
And I appreciate your kindness :hugs:
