### ISSUE TITLE
Singularity integration with Jenkins IO

### ISSUE THREAD

**Issue by henrykironde** [apptainer/singularity#1342]
Am trying to work with https://jenkins.io/ and singularity. If anyone has a builds environment using singularity and Jenkins  I could use some help

**Comment by bilke** [comment]
@henrykironde See [this repo](https://github.com/bilke/singularity-recipes). You just need a node with Singularity installed. A build then looks [like this](https://jenkins.opengeosys.org/blue/organizations/jenkins/User%2Fbilke2%2Fsingularity-recipes/detail/master/10/pipeline). I am pushing here to my own registry.

**Comment by dtrudg** [comment]
Hi @henrykironde - was the example from  .@bilke enough for you to get started with Jenkins? I have touched on this in Jenkins but moved on to GitLab CI. Let us know if there's anything that comes up.

**Comment by henrykironde** [comment]
Thanks @bilke, I am going to have a look at them over the weekend and the coming week. I may need your help if I do not get to understand the workflow's organization. And may be we could put up a doc for doing such integration. 

@dctrud, I would be interested in comparing GitLab CI with Jenkins. Let me know what you think of these two CIs.
`The main goal is to be able to run tests that take a really long time on my server and can not be handled by Travis CI or Apveyor CI and etc..`

**Comment by dtrudg** [comment]
@henrykironde - GitLab CI is heavily integrated with the other offerings of the GitLab service. I think it is quite a neat solution, simple to use - but only warranted if you use GitLab for your code hosting. Jenkins is very powerful but the setup is more involved. I'm personally using drone for things at home now.

**Comment by dtrudg** [comment]
Closing as no follow-up since 2018.
