### ISSUE TITLE
is there an actual need to bind mount real /tmp within image during bootstrap?

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#1349]
## Version of Singularity:

2.4.2

### Expected behavior

image has an independent /tmp (throw away overlay? actual image file system?) during build.  That should benefit reproducible/reliable build IMHO so bootstrapping doesn't have possible side-effect from consuming something under /tmp

### Actual behavior

I had cleanup call (`rm -rf /tmp/*`) within `%post`... and later was wondering who the hell removed all my `ssh-agent` socket files?!

This is just a notice, feel free to close if that is just "by design" and RTFM ;)

**Comment by DrDaveD** [comment]
That's by design.  Have you tried --contain?

**Comment by yarikoptic** [comment]
ok, just good to know.
re `--contain` -- not sure what contain we are talking about:
```shell
$> singularity build --help| grep -e --contain
$> singularity  --help| grep -e --contain  
```

**Comment by DrDaveD** [comment]
Sorry, I was thinking about run/exec time, not build.
