### ISSUE TITLE
SINGULARITYENV_PATH doesn't appear to be propagated into the runtime container environment

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#1352]
## Version of Singularity:

 2.4.2

### Expected behavior

It should be possible to execute programs located in the path set via SINGULARITYENV_PATH variable.

### Actual behavior

Debug log shows the SINGULARITYENV_PATH is being processed into PATH, but the resulting PATH doesn't appear to apply. jms replicated the issue.

### Steps to reproduce behavior

Put a static binary into a sandbox container, say /opt/foo/myprog

Export SINGULARITYENV_PATH=/opt/foo before executing the container with 'myprog'.

The following error is shown:

/.singularity.d/actions/exec: 9: exec: prog: not found

If the correct PATH is exported from /.singularity.d/env/90-environment.sh 'prog' will be found and executed.

**Comment by dtrudg** [comment]
Closing this as it was addressed by #1430 which is included in Singularity 2.5.0. Please feel free to reopen if you have any further issues related to this.
