### ISSUE TITLE
please enable travis for the repository

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#136]
I came to realization that apparently travis is still not turned on for this repo... and i believe ./test.sh is failing since awhile with 

```
 + sudo singularity create -s 15 container.img                  (retval=1) ERROR
Creating a sparse image with a maximum size of 15MiB...
Using given image size of 15
ERROR  : Will not overwrite existing file: container.img
/tmp/singularity-test.o58KBg/libexec/singularity/cli/create.exec: line 114: messsage: command not found
Full output in: /tmp/tmp.l5dIKIy0Bj
```

and I guess since recommended by the wise me set -e -u doesn't run much and fails as well:

``` shell
$> ./test.sh 
Gaining/checking sudo access...
Building/Installing Singularity to temporary directory
Reinvoking in a clean shell
Gaining/checking sudo access...
./libexec/functions: line 234: DEBUG: unbound variable

$> echo $?
1

```

**Comment by yarikoptic** [comment]
to enable travis just go to travis-ci.org, login via github, and toggle the switch for this repository among your repositories... let me know if you need more guidance.

**Comment by yarikoptic** [comment]
I don't know.. may be I could just blame gyn&tonic I had but now ./test.sh fails even on older point, which I think it was working (e.g. e987e239291fbf1fd01087bbf871ad8eec62e935) and moreover fails to run properly if I remove system wide installation of singularity, adjust /etc/sudoers to not env_reset or secure_env but still getting this error:

```
$> bash ./test.sh
Gaining/checking sudo access...
Building/Installing Singularity to temporary directory
Reinvoking in a clean shell
Gaining/checking sudo access...
 + sh ./autogen.sh --prefix=/tmp/singularity-test.vTyet1        (retval=0) OK
 + make                                                         (retval=0) OK
 + sudo make install                                            (retval=0) OK

SINGULARITY_CACHEDIR=/tmp/singularity-test.vTyet1
PATH=/tmp/singularity-test.vTyet1/bin:/bin:/usr/bin:/sbin:/usr/sbin

 temp working space at: /tmp/singularity-test.vTyet1
 + mkdir -p /tmp/singularity-test.vTyet1                        (retval=0) OK
 + pushd /tmp/singularity-test.vTyet1                           (retval=0) OK

Running base tests...

 + singularity                                                  (retval=127) ERROR
./libexec/functions: line 139: singularity: command not found
Full output in: /tmp/tmp.EGgth3IkPt
bash ./test.sh  11.26s user 0.68s system 73% cpu 16.172 total
```

so I will get back to the beast tomorrow unless someone just points me to my sin(s) ;)

**Comment by gmkurtzer** [comment]
If you are testing directly from master right now, I am changing a bunch of things. The effects of set -u -e are far and wide! lol... I am dealing with the repercussions. I think I should have taken your advice, and not put it in functions as I may have to change that now.

Standby, working on it now.

**Comment by gmkurtzer** [comment]
Hrmm, it also doesn't help that busybox.net has been having various problems lately! Can you download?

https://www.busybox.net/downloads/binaries/busybox-x86_64

**Comment by yarikoptic** [comment]
My indispensable piece of advice is to use feature branches instead of avalanche of changes in the same master branch, send them as pull requests and merge when ready. Then master is always top notch

**Comment by gmkurtzer** [comment]
I am still in the mode of CVS/SVN work I guess... Where master == trunk, and all current and broken stuff goes in there and it filters out to the branches as it stabilizes.

Feature branches? Like from a fork of my own repo, or just work in a local branch and merge when ready?

**Comment by yarikoptic** [comment]
On the phone doesn't work :-/  the entire site seems to be down

**Comment by gmkurtzer** [comment]
Yeah, it wasn't working for me either... When I can get back to it, I'll download the busybox static binary and keep it local. Right now I have to test with a debian base image, and bootstrap it every time via test.sh. Not fun.

Thanks!

**Comment by yarikoptic** [comment]
If it is a matter of time, you might speed things up inside if you install first eatmydata and run installation calls under it... I might find/test instructions later on

**Comment by yarikoptic** [comment]
so what about enabling travis? ;)

**Comment by gmkurtzer** [comment]
Yep, I will look into how to do it at my first opportunity.

Thanks!

**Comment by gmkurtzer** [comment]
Done. Thank you for the great idea and help implementing it!
