### ISSUE TITLE
Set mac address of singularity container?

### ISSUE THREAD

**Issue by justinblaber** [apptainer/singularity#1360]
Is there a way to set the mac address for a singularity container (like in docker, where you can set it with the `--mac-address` flag)? In my experience it *appears* the container just takes on the host machines ip and mac address.

Thanks,

-Justin

**Comment by dtrudg** [comment]
Hi @justinblaber . At present, Singularity does not offer the same kind of granularity as Docker, in which each container has its own network namespace. Singularity containers are using host networking directly - the container processes are not really taking on the host ip and mac - they are using the host networking directly.

There is an option to create a separate network namespace for a container (--net) but as currently implemented the container will then only have access to the loopback network, which is not generally useful for real-world work.

We would be interested in what scenario you'd like to support here.

**Comment by justinblaber** [comment]
Basically some software inside one of the docker containers we're using depends on the mac address, and we're able to set it with docker so it works fine. We'd like to port this container over to singularity but we can't set the mac address.

**Comment by lrtorres** [comment]
Hello,

I'd also be interested to know if this feature would eventually be implemented.  My case scenario is that I have a flexlm license manager running on a dying host and we'd like to containerize it, the idea is that in Docker, one can create a container with the same MAC as the flexlm host (as flexlm requires a hostID which is essentially the hosting server's MAC address).

**Comment by dstndstn** [comment]
Almost exactly the same situation here!  We have a flexlm license tied to a MAC address, and we're containerizing the app and want to run it at a supercomputing center where Docker is not available.

**Comment by dtrudg** [comment]
Hello all. Given that, generally, the expectation is that moving flexlm MAC locked licenses requires a conversation with the vendor, and consideration of license terms I don't want to comment specifically on that use-case here.

More generally, Singularity 3.x supports networking configurations using CNI, where the container has a network namespace configured and used. There is some (admittedly )brief documentation here: https://sylabs.io/guides/3.5/user-guide/networking.html?highlight=cni

**Comment by dstndstn** [comment]
Easier than prying the network card out of one machine and moving it to another! :)

It would be super-helpful to say where the possible "--network-args" are defined -- eg, https://github.com/containernetworking/plugins/tree/master/plugins/main/host-device

Too bad this requires root!

**Comment by dtrudg** [comment]
> It would be super-helpful to say where the possible "--network-args" are defined -- eg, https://github.com/containernetworking/plugins/tree/master/plugins/main/host-device

Yes - something should be added to docs. Probably with the updates to the admin docs that will come now 3.5.0 is out we'll look at this.

> Too bad this requires root!

Not really any way to avoid this sensibly, as it is doing various host stuff to get things setup for the container to use. Docker is doing this on your behalf,  even if you run docker commands as a normal user.

**Comment by cclerget** [comment]
@dstndstn If root is a blocker and your kernel is recent enough to support user namespace you can give a try with fakeroot feature (https://sylabs.io/guides/3.5/user-guide/fakeroot.html).
So basically you could have a definition file to build the image like

```
bootstrap: ...
from: ...

%post
   # whatever you need to install and run flexlm

%runscript
    ifconfig eth0 hw ether XX:XX:XX:XX:XX:XX
    flexlm
```

The important section is `runscript`.
Once build you could run it like (depending of flexlm licence port in this example saying 27000)

```
singularity run --fakeroot --net --network-args="27000:27000/tcp" flexlm.sif
```

**Comment by dstndstn** [comment]
the supercomputing center we're working at doesn't have /etc/sub{uid,gid}, so if I'm understanding correctly, we can't use --fakeroot.
(and when I try to test, it fails in building the sandbox)
