### ISSUE TITLE
singularity compile not finding mksquashfs

### ISSUE THREAD

**Issue by satra** [apptainer/singularity#1361]
source code version: 2.4.2-138-gbcc45a2 (i.e release-2.4)
os: CentOS Linux release 7.2.1511 (Core) 

```
# ./configure --prefix=/someprefix --with-userns
# make
...
******
  mksquashfs from squash-tools is required for full functionality
******

make[1]: Leaving directory `/somepath'

# which mksquashfs
/usr/sbin/mksquashfs
```

**Comment by satra** [comment]
nevermind - that's just a message not a make error.

**Comment by ps-account** [comment]
still, kinda confusing! couldn't it just be a warning in case mksquashfs is NOT installed?

**Comment by GodloveD** [comment]
I agree.  And I think we've heard from enough users at this point in time that this deserves to be re-opened.

**Comment by dtrudg** [comment]
We've had a lot of queries about this now... so #1374 is my thought on addressing.

**Comment by dtrudg** [comment]
Hi @satra - the fix for this has been merged into development-2.x for an upcoming 2.5 release.
