### ISSUE TITLE
add --create option to bootstrap?

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#138]
as such now, it requires two steps to bootstrap a container where the first one will always be create.  so why not to make it as an option to bootstrap (to just follow default settings of create)?

**Comment by gmkurtzer** [comment]
Yep, we are thinking along the same lines. I actually have a big plan here to change how the bootstraps are currently working as some limitations in their current design have been quite problematic. It will change the structure of the definition, but I will leave the current code in place for backwards compatibility and offer the new recipe moving forward.

**Comment by GodloveD** [comment]
I think this should be taken care of by the new `build` command.  If you have not seen what is happening in the development branch recently, we are replacing the `bootstrap` command with `build`.  `build` uses a directory as a staging area and then creates and bootstraps an image that is the perfect size.

Does this address the issue?  Should we close it?

**Comment by gmkurtzer** [comment]
I concur. As you mentioned, the new `singularity build` command no longer requires an existing image of a given size.
