### ISSUE TITLE
if create/bootstrapped under restrictive umask 077, exec doesn't work :-/

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#139]
``` shell
$> singularity exec /tmp/debian.img /bin/bash
/.exec: 2: .: Can't open /environment
```

redid with umask 022 -- worked fine, so some permissions somewhere I guess.  Would be worthwhile adding a test for this imho

**Comment by gmkurtzer** [comment]
I am really glad you run such a restrictive umask! Great find!! OK, this should be fixed in [master fb9a43f].

Thanks again!
