### ISSUE TITLE
nested directory creation error

### ISSUE THREAD

**Issue by maflister** [apptainer/singularity#1400]
## Version of Singularity:

2.4.2

### Expected behavior

Creating multiple nested directories in post section using mkdir. Expect it to follow standard bash syntax.
`mkdir -p /my/nested/{dir1,dir2}`
`ls /my/nested`
`dir1 dir2`
### Actual behavior

`mkdir -p /my/nested/{dir1,dir2}`
`ls /my/nested`
`{dir1, dir2}`

### Steps to reproduce behavior

Run mkdir command with nested directories in the %post section.

**Comment by guma44** [comment]
What is your base image? Recently when working with Ubuntu I had to do the shell change in the beginning of the %post to get it work:
```
# CHANGE DASH TO BASH
rm /bin/sh
ln -sf /bin/bash /bin/sh
```

Apparently, Singularity uses sh as a base shell and sh is linked to dash in eg. Ubuntu.

**Comment by dtrudg** [comment]
> Apparently, Singularity uses sh as a base shell and sh is linked to dash in eg. Ubuntu.

This is the cause of this. Because we need to support thin containers that may not have `bash` we are unable to force its use.
