### ISSUE TITLE
2.4.5 RPM build failure on RHEL 7.4 (includes solution)

### ISSUE THREAD

**Issue by tseemann** [apptainer/singularity#1421]
## Version of Singularity:

2.4.5

### Expected behavior

RPM created.

### Actual behavior

```
*** ERROR: No build ID note found in /home/user/rpmbuild/BUILDROOT/singularity-2.4.5-1.el7.x86_64/usr/lib64/singularity/libsingularity-image.so.1.0.0
error: Bad exit status from /var/tmp/rpm-tmp.Ey8y69 (%install)
```

### Steps to reproduce behavior

Standard RPM creation instructions.

### How I fixed it

Add `%undefine _missing_build_ids_terminate_build` to the `.spec` file.

**Comment by jmstover** [comment]
I just built this on CentOS 7.9 from the 2.4.5 git tag with no error.  Can you do a manual `make` like:

`./configure --prefix=/usr/local/singularity-2.4.5; make | tee ~/build.log` and then run:

`grep 'libsingularity-image.so.1.0.0' ~/build.log`

There should be 10 or so lines grabbed from `make` output.

**Comment by dtrudg** [comment]
Closing as this is related to a deprecated 2.x version of Singularity.
