### ISSUE TITLE
tempfile::filename is too short

### ISSUE THREAD

**Issue by jvansanten** [apptainer/singularity#1427]
Creating the singularity-debug logfile when starting an instance fails with "Label string too long" if the basename of the image file and the instance label are longer than 32 characters. This happens because the rest of the template string already take up 32 of the available 64 characters:
https://github.com/singularityware/singularity/blob/d6b58455b6dff5c98c8cd49fc009ddd8d01d97ec/src/util/util.c#L413

For example, an instance called `ampel.archivedb` from an image called `postgres-10.3` will fail when it tries to create a tempfile named `/tmp/postgres-10.3.simg.ampel.archivedb.singularity-debug.0Fm3PC`. These are not unreasonably long names.

A more robust solution would be to declare `filename` as `char filename[PATH_MAX];` (using `PATH_MAX` from limits.h)

**Comment by jtfrey** [comment]
Is there a reason to have the 'filename' field be a static character array?  The 'tempfile' struct is never statically allocated on the stack and is always created/initialized via function calls that malloc() it; so why not calculate the 'filename' length and include that in the malloc() of the 'tempfile' pseudo-object, point 'filename' to the extra bytes after the struct proper?

**Comment by dtrudg** [comment]
Closing - this issue is specific to the deprecated 2.x codebase
