### ISSUE TITLE
cannot find .conf file

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#143]
I'm getting this error with a simple `singularity run [image]`:

```
  $ singularity run ubuntu\:latest-2016-04-06.img 
  ERROR  : Configuration file not found: /usr/bin/etc/singularity/singularity.conf
```

**Comment by gmkurtzer** [comment]
Hi Vanessa,

How did you install Singularity?

The config file is hard coded into the binary based on the -D$(sysconfdir) during compilation (so the user's can't change it at runtime). But it does mean that it is very dependent on the build and a proper install.

**Comment by vsoch** [comment]
Same as always:

```
  cd singularity
  git pull origin master
  ./autogen.sh
  ./configure --prefix=/usr/local
  make
  sudo make install
```

Could it be some kind of version conflict? What I didn't do is make any effort to uninstall first!

**Comment by gmkurtzer** [comment]
Shouldn't be a version conflict... Unless, it is installed in another location and picking the other installdir first?

If not, can you send me the build output?

**Comment by vsoch** [comment]
[buildoutput.txt](https://github.com/gmkurtzer/singularity/files/364950/buildoutput.txt)

**Comment by vsoch** [comment]
:boom:

**Comment by gmkurtzer** [comment]
Can you do a make clean, then do it again? It didn't rebuild any of the sources. hehe.. Thanks!

**Comment by vsoch** [comment]
fixed!! boum!

**Comment by gmkurtzer** [comment]
WAHOO! :)
