### ISSUE TITLE
Bug if run.sh in same folder

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#1435]
## Version of Singularity:

```
2.4.5-master.g0b17e18
```

I'm not sure how this happens, but I so happened to have a run.sh in my present working directory during a few builds. I notice this at the end:

```
Singularity container built: rstudio
Cleaning up...
cat run.sh >run 
chmod a+x run
```
I don't have anything regarding a run.sh in my recipe or otherwise (I was just being lazy and saved something temporarily as run.sh). 

When I rename the file to something else and build again, there is no strange-ness:

```
Skipping checks
Building Singularity image...
Singularity container built: rstudio
Cleaning up...
```

### Steps to reproduce behavior

Create a run.sh file and do a build.

**Comment by dtrudg** [comment]
Please could you provide a little more detail... I'm not able to reproduce this yet just having a `run.sh` present in the working directory.

  - What is the content of the definition file?
  - What is the exact build command you are running?
  - What is the exact content of the current working directory that leads to this?

Thanks.

**Comment by dtrudg** [comment]
Hi @vsoch -  I had another quick go at reproducing but can't. Do you still observe this? If so can you post a detailed reproducer? Thanks.

**Comment by vsoch** [comment]
I can't either! This was a pretty funky image. I'll close and reopen if I'm able to reproduce with updated Singularity. Thanks @dctrud !
