### ISSUE TITLE
Version number not updated everywhere in 2.4.6-rc1

### ISSUE THREAD

**Issue by zao** [apptainer/singularity#1440]
## Version of Singularity:

2.4.6-rc1

### Expected behavior

I'd expect a package for `2.4.6~rc1-1`. Note the tilde to make it compare less than `2.4.6-1` when it releases.
I'd expect `singularity --version` to not say `2.4.5-dist`.

### Actual behavior

Debian package build ends up with a `2.4.5-1` version as that's the newest one in the changelog. Additionally, the previous version is missing the author line.
Also, `configure.ac` says `2.4.5` and that propagates into the build.

### Steps to reproduce behavior

Follow debian package build instructions or run `singularity --version`.

**Comment by dtrudg** [comment]
Closing this as we are now at 2.5.0 and have a numbering scheme in place to avoid in future. Thanks.
