### ISSUE TITLE
instances don't output startscript echo / log to the termal

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#1442]
I'm working on a general container wrapper for a web server to secure "some webby thing" with a token, and the configuration and starting of nginx should ideally happen as an instance startscript. I need to echo the temporary ports and directories that are used back to the user, but when I start the instance this doesn't happen. Is there any reason?

**Comment by vsoch** [comment]
Also, where do (or would) arguments go? I can't test this, but after the instance name?

```
singularity instance.start --bind /tmp/logs:/var/log/nginx sh_container web [args?}
```
Thanks!

**Comment by dtrudg** [comment]
We should transfer this to a docs issue to point out where the logs go more clearly.
