### ISSUE TITLE
--userns: need way to detect if feature is supported, or to downgrade error to be non-fatal

### ISSUE THREAD

**Issue by mr-c** [apptainer/singularity#1445]
## Version of Singularity:

2.4.4-dist

### Expected behavior

Use of `--userns` results in a non-fatal error

### Actual behavior

```
ERROR  : Failed invoking the NEWUSER namespace runtime: Operation not permitted
ABORT  : Retval = 255
```

### Steps to reproduce behavior

Use `singularity exec --userns docker://alpine env` on an unsupported system

---

This is in the context of running singularity from other codebases, so an acceptable solution would be a command that quickly tests to see if this feature is supported.

**Comment by cclerget** [comment]
@mr-c I think you can take a different path, it exists a trivial and almost reliable check to verify user namespaces are supported or not on systems by looking at `/proc/self/ns/user` presence

**Comment by mr-c** [comment]
@cclerget Hmm.. that doesn't seem to be enough
``` bash
michael@laptop:~$ test -a /proc/self/ns/user; echo $?
0
michael@laptop:~$ singularity exec --userns shub://GodloveD/lolcow
Progress |===================================| 100.0% 
ERROR  : Failed invoking the NEWUSER namespace runtime: Operation not permitted
ABORT  : Retval = 255
```

**Comment by mr-c** [comment]
Looking at the code, it will take some refactoring to allow `--userns` to be non-fatal, so how about a test command?

Here's a mockup:
```
$ singularity exec --test --userns shub://GodloveD/lolcow; echo $?
ERROR  : Failed invoking the NEWUSER namespace runtime: Operation not permitted
255 
$ sudo singularity exec --test --userns shub://GodloveD/lolcow; echo $?
0
```

**Comment by cclerget** [comment]
@mr-c Ok you run command on a kernel which support user namespaces but requires root privileges to use them, a case which is not handled by Singularity, use of user namespaces are necessary non-privileged. A non-fatal error isn't useful and logic since the code will fail later during mount operations, so fatal error is really expected here.

Sorry if I'm not understand but I don't see where is the problem, that remains the same with or without `--test`, right ?

```
$ singularity exec --userns shub://GodloveD/lolcow true; echo $?
ERROR  : Failed invoking the NEWUSER namespace runtime: Operation not permitted
255
```

or

```
$ singularity exec --test --userns shub://GodloveD/lolcow true; echo $?
ERROR  : Failed invoking the NEWUSER namespace runtime: Operation not permitted
255
```

**Comment by mr-c** [comment]
@cclerget The context is that I'm calling `singularity` from another tool ([the reference CWL runner](https://github.com/common-workflow-language/cwltool)) and I want to use the highest level of isolation available without requiring manual configuration.

`--test` is a proposed feature that would test for the permissions needed but not actually run or download anything.

Another useful outcome would be if Singularity would automatically enable the highest available level of isolation with a single CLI option (or without any parameter at all)

**Comment by cclerget** [comment]
@mr-c A dirty hack to check user namespace support without downloading and running command inside container :

```
singularity exec --userns /etc true 2>&1 | grep "No valid /bin/sh"
if [ $? != 0 ]; then
    echo "user namespace not supported"
fi
```

This option could be integrated in 3.X release, but not as default when no parameters are given because that could break user or application workflows

**Comment by mr-c** [comment]
@cclerget Thanks! I'll use that workaround for now
