### ISSUE TITLE
Bootstrapping without a definition file should be possible

### ISSUE THREAD

**Issue by chrisgorgo** [apptainer/singularity#145]
In theory bootstrapping an image without provided definition should be possible. It's optional in this script:
https://github.com/gmkurtzer/singularity/blob/master/libexec/bootstrap.sh#L53

However, the `bootstrap.exec` script which calls `bootstrap.sh` requires user to provide a bootstrap definition file:
https://github.com/gmkurtzer/singularity/blob/master/libexec/cli/bootstrap.exec#L84

Bootstrapping without a definition file (without having to specify the linux distribution flavor) would be very useful for sanitizing images imported from docker (see #119).

**Comment by gmkurtzer** [comment]
This was pretty easy modification actually, good thinking! Please see [master 7e9aaa2].

Thanks!

**Comment by chrisgorgo** [comment]
Works like a charm - thanks for a quick fix.

**Comment by gmkurtzer** [comment]
Fantastic! I was just adding some test code for this too! Thank you!
