### ISSUE TITLE
Cannot mount nvidia support files without umask 002

### ISSUE THREAD

**Issue by slefrancois** [apptainer/singularity#1460]
## Version of Singularity:

2.4.6-dist

### Expected behavior

Pulling containers as normal user should allow to enter container using `singularity shell --nv`.

### Actual behavior

With release 2.4.6 and umask 027 on Debian 9, I get an error regarding nvidia-smi files:
```
$ singularity shell --nv ubuntu-latest.simg
ERROR  : Target /var/lib/singularity/mnt/final/usr/bin/nvidia-smi doesn't exist
ABORT  : Retval = 255
```
This is solved if umask is set to 002.

However, pulling and running containers with nvidia support worked with umask 002 in version 2.4.2. Has something changed in the way support files are mounted on container startup?

### Steps to reproduce behavior

```
$ (umask 002; singularity pull --force docker://ubuntu:latest)
$ singularity shell --nv ubuntu-latest.simg
ERROR  : Target /var/lib/singularity/mnt/final/usr/bin/nvidia-smi doesn't exist
ABORT  : Retval = 255
$ (umask 002; singularity shell --nv ubuntu-latest.simg)
Singularity: Invoking an interactive shell within container...
Singularity ubuntu-latest.simg:~>
$ singularity --version
2.4.6-dist
$ umask
0027
```

The same procedure worked when pulling and running as user on 2.4.2 + PR #1184 (for nvcr.io support, appears unrelated here).
```
$ (umask 002; singularity pull --force docker://ubuntu:latest)
$ singularity shell --nv ubuntu-latest.simg
Singularity: Invoking an interactive shell within container...
Singularity ubuntu-latest.simg:~>
$ singularity --version
2.4.2-dist
$ umask
0027
```

**Comment by dtrudg** [comment]
Closing as a umask fix was included in 2.5.0. Please feel to reopen if you experience further issues.
