### ISSUE TITLE
Do not exit/abort in case of overlapping directory binds

### ISSUE THREAD

**Issue by zichner** [apptainer/singularity#1469]
## Version of Singularity:
2.4.6

### Expected behavior

If two directory binds are overlapping (e.g. `singularity shell -B /data -B /data/test ...`) it would be nice to just get a warning instead of an error. 
(This was the behavior before commit 7ecb26f6f6a8dc3e2d21f0e0fadcbffdf3bcceb9)

Alternatively, it would be nice if the user could decide whether a warning or an error should be raised.

The reason for this "wish" is that some pipelining frame works / tools automatically generate Singularity commands based on some input, where it can happen that multiple directory binds are overlapping.

### Actual behavior

In the current version, overlapping directory binds lead to an error and abort:
`ERROR  : Not mounting requested bind point (already mounted in container)`

### Steps to reproduce behavior

`singularity shell -B /data -B /data/test image.simg`

Thank you very much!

**Comment by gkiar** [comment]
Hey @vsoch @dctrud I have the same request -- also in the case that the path I'm binding happens to be specified in `singularity.conf`, though I generally wouldn't know if this is true or not across systems. Is there any way to avoid this error?

**Comment by vsoch** [comment]
This seems like an easy bug to fix, @dctrud is there any reason we would need to exit? There should be two cases:
 
 - bind does not exist and not possible to make, exit
 - bind not possible to make because already mounted, warning.

**Comment by dtrudg** [comment]
Hi - I am not the best person to look at this. @cclerget might be able to provide some better thoughts here.

**Comment by DrDaveD** [comment]
I think it would have to be optional and not default.  2.4.6 changed the behavior for security reasons, and I think it would be bad to change the behavior and not make sure that people notice.  That would likely happen if it skipped the extra bind mounts and just printed a warning that most users will ignore.

Having said that, adding an option for turning just this type of fatal error into a warning seems like quite a lot to ask.  How many such options might be needed in the future?  Can't the pipelining framework/tools be modified to not attempt redundant binds?   Open Science Grid users modified a number of scripts that were doing this (mosty because of misunderstandings in how singularity worked) in order to work with 2.4.6.

**Comment by cclerget** [comment]
Hi @zichner, is 2.5.0 release fix the issue you encountered ?

**Comment by DrDaveD** [comment]
I would say that 2.5.0 did do what @zichner asked, and more.  It even allows nested mounts as long as the mountpoint already exists.

**Comment by zichner** [comment]
Version 2.5.0 indeed fixed the issue. Thank you very very much!! Keep up the great work!
(and sorry for my late reply, I was traveling).

**Comment by rsuchecki** [comment]
I have a special case of the above where binding fails

```
singularity shell -B /data -B /data image.img 
FATAL:   container creation failed: unabled to /data to mount list: destination /data is already in the mount point list
```

I guess this could simply be ignored or perhaps a warning would suffice?

**Comment by DrDaveD** [comment]
Now you're talking about some 3.x version, right?  Which one?  In any case that error message has bad English!

**Comment by vsoch** [comment]
I tried to data this morning, I was terribly bad at it! I think the error wants us to data all the things?

**Comment by DrDaveD** [comment]
I'm unabled to data too

**Comment by rsuchecki** [comment]
3.0.3

**Comment by vsoch** [comment]
I found him :point_right: https://github.com/sylabs/singularity/blob/5b60630c411b1062bfad803733e24541785c8197/internal/pkg/runtime/engines/singularity/container.go#L1392

He knows how to data.

**Comment by rsuchecki** [comment]
No that is no longer unabled, is there any reason why a repeated `-B /path` instruction could not just be ignored, possibly with a warning message?

**Comment by vsoch** [comment]
Just curious, why would this ever happen other than a user error (typo?) I suppose it's reasonable, but if that happens it means the user has a script somewhere defining a bind twice - if I were that user I'd want my script to do it once, and Singularity could point me to that.

In terms of why, I am not totally sure, but I would bet it has something to do with security, and binding a directory twice. The workaround would be keeping more of a dictionary, but again it seems like the user shouldn't ask for a bind twice in the first place. Others thoughts?

**Comment by rsuchecki** [comment]
This are really good points @vsoch. In my case the singularity command is built by a workflow manager and a number of  directories with various inputs need to be bound. Some of this is done explicitly e.g. `-B path/to/some/data` but there is also a deferred `-B $PWD`  which gets resolved at run time as it is not known upfront. Given a certain combination of settings used, `$PWD` may be the same as the previously added `-B path/to/some/data`. 

> if I were that user I'd want my script to do it once, and Singularity could point me to that.

:100: but perhaps a warning should suffice?

**Comment by vsoch** [comment]
Does your cluster have it configured to not automatically bind the present working directory? By default, it should be bound (so you wouldn't need that mysterious and unknown path!)

**Comment by jscook2345** [comment]
@cclerget 

Could this be done as a warning?

**Comment by vsoch** [comment]
hey @rsuchecki we fixed this up! Via install from master branch, repeated binds should just issue a warning. Give it a try and let us know if it works!

**Comment by rsuchecki** [comment]
I missed the original notification, but 3.1.1 is now operational on our cluster, works great, the intelligible warning is a bonus 😉

**Comment by vsoch** [comment]
Woot! Glad you like it :)
