### ISSUE TITLE
Pulling from Dockerhub non-deterministically fails on Travis CI

### ISSUE THREAD

**Issue by gkiar** [apptainer/singularity#1472]
## Version of Singularity:
`2.4.6`

### Expected behaviour
When pulling from Docker hub, i.e. `singularity pull docker://bids/example`, on my Linux machine the pull works as expected every time. I expect this to be consistent on Travis CI.

### Actual behaviour
However, when doing this on Travis, I get non-deterministic failures in which the following error message is provided.

```
gzip: /root/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Cleaning up...
ERROR: pulling container failed!
```

This error pops up at different points in the download (sometimes after 1 blob, other times after 8, etc.) each time, and occasionally it'll get through to finishing.

Example failure: https://travis-ci.org/gkiar/singularity-travis/builds/368325759#L2795
Example success: https://travis-ci.org/gkiar/singularity-travis/builds/368323653#L2811

### Steps to reproduce behaviour
This issue is present in [this Travis CI script](https://github.com/gkiar/singularity-travis/blob/414ace48a7c828cd494816675d41775d63f0f207/.travis.yml).

Any suggestions on how I could get more consistent pulls from Docker hub in Travis CI? Thanks!

**Comment by dtrudg** [comment]
Hi @gkiar - we have had issues today with the CI of Singularity itself in Travis, which does a lot of pulls from Docker. Over the past few days we've seen some general instability with network operations from Travis - evidenced by failures not just in docker pulls, but apt-get update and some general python network tests. It appears there's also something else going on now though, which is being discussed on #1091 and PR #1470.

It looks like there is some kind of cloudflare rate limiting / temporary banning that is being triggered without a clear pattern by Singularity pulls from DockerHub. I've tidied up some of Singularity's behavior interacting with docker hub in PR #1470. This also checksums downloads to raise issues earlier, and more properly.

I'm going to be looking into this further - right now I need to contact docker support to ask about changes in their rate limiting etc.

**Comment by gkiar** [comment]
Hi @dctrud thanks for the prompt reply! I've noticed similar issues when doing apt-get update myself, so interesting to hear this is potentially part of a wider problem. Thanks for the hard work! Cheers.

**Comment by dtrudg** [comment]
Hi @gkiar - if you are able to try #1470 out too that would be useful. Setting a User-Agent (last commit there) has fixed it in our CI run.

**Comment by dtrudg** [comment]
@gkiar - Docker support kindly responded very quickly to our inquiry. They are testing out Cloudflare and a particular filtering feature that causes the issue has been turned off now, until they can tune it. Let us know if you have any remaining issues.

**Comment by vsoch** [comment]
This was a lot of fun to figure out :) Solid work @dctrud !

**Comment by gkiar** [comment]
@dctrud @vsoch Thanks for all the help! Great that Docker support has responded so quickly. Should I try out your PR now, or wait until it's merged, since Docker filtering now shouldn't be an issue? Thanks!

**Comment by vsoch** [comment]
If you want the feature now, then it wouldn't hurt to just clone and use the branch, it would technically be the same as the merged version, given that some other feature doesn't get in first! I've been trying it off an on over the evening and have not had any issue. If you feel better for some reason about having the merge into 2.x, then likely it will be done sooner than later, and you can also wait. :)

**Comment by gkiar** [comment]
Fantastic! I just built successfully, but if I have an issue will adopt the branch in #1470 :) I'm trying to keep myself a clean install/test setup that can emulate my deployment environment as closely as possible, so will keep a note of this just in case but hopefully shouldn't have to worry any more 😄 Thanks again @vsoch and @dctrud !!!
