### ISSUE TITLE
Cant add files after/during 'post'

### ISSUE THREAD

**Issue by stevekm** [apptainer/singularity#1475]
## Version of Singularity:

2.4

### Expected behavior

Able to add files after running commands in `%post`

### Actual behavior

You can't add files after running commands in `%post` ([docs here](http://singularity.lbl.gov/docs-recipes#files))

### Steps to reproduce behavior

I have a Singularity file like this:

```
BootStrap: debootstrap
OSVersion: xenial
MirrorURL: http://us.archive.ubuntu.com/ubuntu/

%post
    # location for misc scripts
    mkdir -p /opt/bin

    # location for misc data
    mkdir /data

    # mount point
    mkdir /ifs

    apt-get update && \
    apt-get install -y wget

    cd /opt/ && \
    wget http://www.openbioinformatics.org/annovar/download/xxxxxxxx/annovar.revision150617.tar.gz && \
    tar -vzxf annovar.revision150617.tar.gz && \
    rm -f annovar.revision150617.tar.gz

    # location to mount reference database dir:
    mkdir /opt/annovar/db

%files
    # easy script for annotating:
    annotate_vcf.sh /opt/annovar/annotate_vcf.sh

%environment
    export PATH="/opt/bin:${PATH}"
    export PATH="/opt:${PATH}"
    export PATH="/opt/annovar:${PATH}"
```

I need to add my local file `annotate_vcf.sh` to the location `/opt/annovar/` inside the container. This location is created after unpacking the tar-ball that gets downloaded during `%post`. It is impossible to add the script this way because the `%files` section is getting executed first, before `/opt/annovar/` is created. But creating `/opt/annovar/` first will likely lead to conflicts (if not in this case, in future cases) and overwriting of output. 

How are you supposed to add files to locations that are created during `%post` like this?

**Comment by GodloveD** [comment]
Hi Stephen,

What about copying the file to /tmp during %setup so that they are "inside"
the container during %post, and then moving them to their final directory
during %post after the final directory has been created within the
container?  Haven't tried myself, but seems like it would work?

Dave

**Comment by stevekm** [comment]
Thanks I tried that and it did work.

**Comment by GodloveD** [comment]
word.
