### ISSUE TITLE
Allow container-specific IPC

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#148]
Unix IPC primitives are a bit nasty in a shared environment: by default, they are system-wide, a scarce resource, and not automatically cleaned up when the invoking process exits.

If available, utilize the `CLONE_NEWIPC` flag so containers don't leak Unix IPC usage.

**Comment by gmkurtzer** [comment]
I used to have this enabled, but I think I disabled it due to it breaking some MPI communication pathways. I will have to go back and see why I disabled and retest now that we know MPI is working properly.

**Comment by bbockelm** [comment]
I would imagine this has the potential to break MPI (well, and Postgres servers - let's hope that's not a problem!) - but, OTOH, it's tiring and painful to clean up IPC after poorly written jobs.

It should be possible to `unshare` the MPI process into the same IPC namespace as the container.

**Comment by gmkurtzer** [comment]
This should also be easily setup to be a configurable option as the PID namespace is.

I am not sure about joining the orted/MPI IPC namespace, but that is an interesting idea. With the Open MPI modular architecture, it should be pretty easy to inject some code to make sure we join the PPID's namespace (using setns()). This might prove to be temperamental but would be very interesting to implement.

**Comment by gmkurtzer** [comment]
CLONE_NEWIPC is now in [master 140ff41]. Thanks!
