### ISSUE TITLE
build help not displayed if squashfs-tools not installed

### ISSUE THREAD

**Issue by spco** [apptainer/singularity#1483]
## Version of Singularity:

2.4.1

### Expected behavior

When running on a machine without squash-fs tools, running 
`singularity build help`
should display the help for build command.

### Actual behavior

`singularity build help`
displays 
```
ERROR: You must install squashfs-tools to build images
ABORT: Aborting with RETVAL=255
```
This is evidently because the check for squashfs-tools at https://github.com/singularityware/singularity/blob/0afcf204e9cc0a1fc9cae5e936c46060330929f8/libexec/cli/build.exec#L41 is before the check for help https://github.com/singularityware/singularity/blob/0afcf204e9cc0a1fc9cae5e936c46060330929f8/libexec/cli/build.exec#L72

### Steps to reproduce behavior

`singularity build help` on a system without squashfs-tools installed.

**Comment by jscook2345** [comment]
This seems to be fixed in the 3.X versions. Thanks for the report!
