### ISSUE TITLE
Internal container folder (not shared with host filesystem) only has 1Mb of free space but has 16Gb of free space when running with sudo

### ISSUE THREAD

**Issue by GerardBCN** [apptainer/singularity#1485]
## Version of Singularity:

2.4.5-dist

### Expected behavior

Be able to download files to a folder owned by the container (not shared with the host).

### Actual behavior

When I run a singularity container, I try to download some files to a folder called /logic inside the container (not shared with the host) but because there's only 1 Mb of free space, I cannot do the download. 

```
$ singularity run OutOfSpace.img 

Filesystem      Size  Used Avail Use% Mounted on
singularity     1.0M    0  1.0M   0% /
--2018-04-26 14:36:41--  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.16.18.10, 104.16.19.10, 2400:cb00:2048:1::6810:130a, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.16.18.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58304693 (56M) [application/x-sh]
Saving to: ‘Miniconda3-latest-Linux-x86_64.sh’

 1% [==>                                                                                                                                                                       ] 1,047,386   --.-K/s   in 0.1s    


Cannot write to ‘Miniconda3-latest-Linux-x86_64.sh’ (Success).
```
Note the free space:

**singularity     1.0M    0  1.0M   0% /**

 However when I run with sudo I have no problem because 16Gb become available.

```
$ sudo singularity run OutOfSpace.img 
Filesystem      Size  Used Avail Use% Mounted on
singularity      16G     0   16G   0% /
--2018-04-26 14:37:15--  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.16.19.10, 104.16.18.10, 2400:cb00:2048:1::6810:130a, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.16.19.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58304693 (56M) [application/x-sh]
Saving to: ‘Miniconda3-latest-Linux-x86_64.sh’

100%[=========================================================================================================================================================================>] 58,304,693  7.24MB/s   in 6.8s   

2018-04-26 14:37:22 (8.16 MB/s) - ‘Miniconda3-latest-Linux-x86_64.sh’ saved [58304693/58304693]

```

Now the free space is:
**singularity      16G     0   16G   0% /**

### Steps to reproduce behavior

Here the Singularity file to create the container

```
Bootstrap: docker
From: centos:latest


%setup
  # Runs on host. The path to the image is $SINGULARITY_ROOTFS
  mkdir ${SINGULARITY_ROOTFS}/logic

%post
  # Post setup, runs inside the image
  yum install wget -y
  chmod 777 /logic

%runscript
  # Executes when the "singularity run" command is used
  cd /logic
  df -h
  wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

%environment
  # environment vars
```
and the command to create the container:

`sudo singularity build OuOfSpace.img Singularity`

**Comment by GerardBCN** [comment]
For anyone following this issue, the way I understand it works "by design" is this:

Folders created inside the container which are not shared with the host filesystem get an allocated space of 1Mb by default (which makes sense, otherwise images would increase their size arbitrarily). 

## The solution  

The way we found to workaround this is by binding some folder of the host filesystem to the container folder. In my example above would be something like:

`singularity run -B /tmp:/logic OutOfSpace.img`

This way, our container /logic folder has plenty of space to write.

**Comment by GodloveD** [comment]
Sorry nobody got back to you on this @GerardBCN.  If you really don't want to save that data to the host, another thing you could is making a persistent overlay.  

http://singularity.lbl.gov/docs-overlay
