### ISSUE TITLE
Check for /bin/sh in container image unduly rejects absolute symlinks

### ISSUE THREAD

**Issue by civodul** [apptainer/singularity#1487]
## Version of Singularity:

2.4.5

### Expected behavior

When `/bin/sh` in a container image is an absolute symlink, that symlink should be resolved relative to the container image's root.

### Actual behavior

The symlink is resolved relative to the "real" root file system.

### Steps to reproduce behavior

With GNU Guix, you can create an image that contains Bash and where `/bin/sh` is a symlink to `/gnu/store/…-bash-4.4.12/bin/sh`:

```
guix pack -f docker -S /bin=bin bash
```
`/gnu/store/…` is a valid symlink _within_ the container, but it's likely invalid outside the container.

It would be nice if `action_ready` in `src/action-lib/ready.c` would suitably resolve symlinks.  Alternately, the check for `/bin/sh` should be performed from within the container. (I'm also looking at ways to have `guix pack` use relative file names for symlink targets, but this use case may still be worth fixing nonetheless.)

**Comment by GodloveD** [comment]
Hi @civodul.  Is this still an issue in 2.5.1?

**Comment by civodul** [comment]
Hi @GodloveD,

Yes, the offending code is still present in 2.5.1:

```c
    if ( is_exec(joinpath(CONTAINER_MOUNTDIR, "/bin/sh")) != 0 && is_link(joinpath(CONTAINER_MOUNTDIR, "/bin/sh")) != 0 ) {
        singularity_message(ERROR, "No valid /bin/sh in container\n");
        ABORT(255);
    }
```

**Comment by civodul** [comment]
The code above is still in 2.6.1.  I know 3.0 gets most of the attention but since 2.x is still widely deployed, it would be nice to have a bug-fix release (`base_environment.go` in current `master` checks for `/bin/sh` but apparently does not insist on it being a regular file.)

**Comment by dtrudg** [comment]
I'm afraid that 2.x is not receiving any bug fixes. If the issue occurs in 3.5 please let us know.
