### ISSUE TITLE
Code protection (execution-only) for licensed software

### ISSUE THREAD

**Issue by GerardBCN** [apptainer/singularity#1492]
Dear singularity community, we are interested in using singularity for HPC deployment of applications but we are concerned about the transparency of singularity containers, which allows any user by default to inspect the code contained within. I read that a protected mode exists, allowing only a group of users to execute the containers but, if I am not wrong, this does not avoid the administrator with sudo rights to inspect the files. Is there any way to ship containers that are execution-only, even for the sys admin of the HPC cluster? Thanks and advance and cheers for such a good project!

**Comment by jekriske-lilly** [comment]
This might make a good topic for discussion on the [Singularity google group ](https://groups.google.com/a/lbl.gov/d/forum/singularity)

I'd be interested in how you accomplish this now and why you feel the same method might not be possible with a container.

To directly answer your question, singularity 2.x containers themselves are not executable binaries, they are executable shell scripts with the first line calling a singularity executable and the rest of the file is a squashfs image. You cannot execute this without being able to read the file. That said, what's in the container might be execute only for the user. You still have the same typical issues with visibility on compiled vs interpreted code etc.

With the upcoming Singularity 3.x features you might be able to do some really cool stuff
https://www.sylabs.io/2018/03/sif-containing-your-containers/

**Comment by dtrudg** [comment]
Unfortunately it's not really technically possible to hide the content of the container from a sysadmin, as it most be accessible on the host to run.

The encryption support in Singularity 3.4 and above offers more options for protecting a container in-transit, at-rest, and from other users at runtime - but a sysadmin would be able to manipulate binds, and access things while an encrypted container is mounted and running.
