### ISSUE TITLE
Ubuntu packages for 2.5.1

### ISSUE THREAD

**Issue by jakirkham** [apptainer/singularity#1508]
Would it be possible to get `apt-get` packages for `singularity` 2.5.1 for Ubuntu (particularly 16.04)?

**Comment by jmstover** [comment]
Hi,

  There's already a `debian/` directory in the source tree. In theory, what you would need to do is:

```
$ cd singularity-2.5.1/
$ cp -r debian/* .
$ debuild -b -us -uc -i -I
```

Make sure you have all the following installed for the build:
`apt-get install build-essential squashfs-tools git libtool`
`apt-get install autoconf devscripts dpkg-dev dh-autoreconf help2man`

That _should_, maybe ... possibly ... hopefully, get you a `.deb` you can install.

**Comment by jakirkham** [comment]
Thanks @jmstover. So we are building a package for `singularity` for `conda` currently, which works. That said, it would be nice to have the binary available via `apt-get`. Is there an ETA, any known blockers, etc.?

**Comment by zao** [comment]
Please note that the changelog in that directory isn't used in the correct debian/ubuntu way.
The changes in it should be from the package maintainer, and not describe the actual changes in the software.

@jakirkham You'll need to at a minimum ensure that the version and distro in the `debian/changelog` file is accurate for your system, and ensure that the `control` file lists the packages needed to build it.

**Comment by dexter2cz** [comment]
@jakirkham You can install package from debian stretch-backports repository.

**Comment by jakirkham** [comment]
Thanks all. Works great. Going to close this out. :)
