### ISSUE TITLE
Allow user-provided chroot as root directory

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#151]
Right now, we maintain a chroot directory structure inside CVMFS (`/cvmfs/cernvm-prod.cern.ch/cvm3/`).  I'd like to have the option of using this instead of a raw disk image.

This might need to be combined with #149 in order to prevent issues with maliciously-formatted `chroot`s.

**Comment by gmkurtzer** [comment]
That is a very interesting idea. Obviously the chroot directory (if standard permissions will apply) will need to be owned and written (and modified) by root which also lowers the risk factor considerably.

The implementation could have some complexities but should be fairly straight forward (and I see you are taking a stab at it, fantastic!).

Great idea!

**Comment by bbockelm** [comment]
Fixed with PR #153
