### ISSUE TITLE
Support for Slurm Singularity plugin

### ISSUE THREAD

**Issue by mperryatos** [apptainer/singularity#1510]
## Version of Singularity:

2.5.1

### Expected behavior

configure using --with-slurm completes successfully

### Actual behavior

configure using --with-slurm aborts with the error message:

ERROR: Slurm support is no longer maintained in Singularity proper and will
be maintained as a subproject on GitHub.

### Steps to reproduce behavior

See above.
I have not been able to find a subproject for the Slurm plugin. The plugin source code is still included in the Singularity project, under src/slurm, but attempting to build it using the --with-slurm option on the configure produces the error shown above. Is there a subproject for the Slurm plugin?  I notice that other developers reported this problem on the Singularity Google group last year, but there was no response.
 
Thanks,
Martin Perry
Atos, Inc.

**Comment by ivegotausername** [comment]
I'm also very interested to know how the SLURM plugin can be built. I've tried without success to build it myself from the latest code.

Ian Shore
King Abdullah University of Science and Technology

**Comment by dtrudg** [comment]
The slurm plugin is no longer a part of Singularity, and does not exist in the 3.x codebase. If there are features you need that you believe a plugin is required for, please let us know.
