### ISSUE TITLE
Generate redundant  file "=8.0" or "=9.0" after enter into corresponding image

### ISSUE THREAD

**Issue by liangshuang1993** [apptainer/singularity#1516]
## Version of Singularity:

2.4

### Expected behavior

Should not create other files.

### Actual behavior

Generate redundant  file "=8.0" or "=9.0" after enter into corresponding image

### Steps to reproduce behavior

I created an cuda-8.0-cudnn6-devel-ubuntu16.04 image from docker hub(https://hub.docker.com/r/nvidia/cuda).
But after I enter into this image, it will generate a file named "=8.0".

I think the reason is that line 42 in this dockerfile is "ENV NVIDIA_REQUIRE_CUDA "cuda>=8.0"", but in singularity image, it is converted to "export NVIDIA_REQUIRE_CUDA=cuda>="8.0"" in file /.singularity.d/env/10-docker.sh.

Then every time I enter into this image, it will run "export NVIDIA_REQUIRE_CUDA=cuda>="8.0"" to create a file named =8.0.

**Comment by GodloveD** [comment]
Heya @liangshuang1993 can you try this with 2.5.1 and report if it's still an issue?

**Comment by liangshuang1993** [comment]
hi @GodloveD , this bug seems to be fixed in 2.4.1:

https://github.com/singularityware/singularity/releases said,
Bug Fixes
Adjusting environment parsing regular expression for Docker to allow for "=" sign in variable

**Comment by GodloveD** [comment]
Fantastic.  Feel free to re-open or open another issue if you find anything else.
