### ISSUE TITLE
Can't use systemctl in Ubuntu 16.04

### ISSUE THREAD

**Issue by max-mapper** [apptainer/singularity#1521]
## Version of Singularity:

2.4.2

### Expected behavior

I am running a Ubuntu 16.04 container with `singularity shell` and trying to get the Slurm workflow manager working so researchers can submit jobs to a university cluster I'm working on that is upgrading from SGE to Slurm soon. Slurm requires a service called `munge` to be running, which is managed by systemctl (systemd), and is supposed to start during init.

### Actual behavior

In the container the munge service is not running and trying to run any systemctl commands results in the following error:

```
> systemctl
Failed to connect to bus: No such file or directory
```

From googling around this seems to be related to how systemd's init system is not initialized in some container runtimes. Is it possible to start a systemctl managed service in singularity (in my case `systemctl start munge.service`)? 

### Steps to reproduce behavior

Run any ubuntu 16.04 container and try to run `systemctl` in a singularity shell.

**Comment by cclerget** [comment]
@maxogden If I understand correctly, you have installed Slurm inside a container and want to start it from container, right ?

**Comment by max-mapper** [comment]
@cclerget Yes I am trying to run slurm (specifically its dependency `munge` in a container), but can't use systemctl. If munge isn't running, slurm errors out with this output:

```
sbatch: error: If munged is up, restart with --num-threads=10
sbatch: error: Munge encode failed: Failed to access "/var/run/munge/munge.socket.2": No such file or directory
sbatch: error: authentication: Socket communication error
```

**edit** To clarify, I'm trying to run the slurm binary that lives on the host machine (a CentOS based research cluster). This approached worked great in the past for SGE which has no service dependencies, but slurm (the apt-get version) requires systemctl based services to run as far as I can tell which I'm not sure is possible with Singularity.

**Comment by cclerget** [comment]
@maxogden Did you give a try with supervisord, that's a good alternative to systemd to start service in container, this link could help : https://github.com/giovtorres/docker-centos7-slurm/blob/master/supervisord.conf

**Comment by max-mapper** [comment]
@cclerget Thank you. I think due to the complexity of running slurm/munged inside a singularity container I'm going to instead use a RPC service to let the container instances use the host systems working slurm daemon to schedule new jobs. It would be nice if there was a well documented way to get slurm to "just work" with singularity in the future.

**Comment by max-mapper** [comment]
Just an update for posterity. I was able to solve my issue. I abandoned trying to get slurm running inside singularity (libmunge service and systemd was too complicated). Instead I found the elegant solution of simply doing this inside the container:

```
$ singularity shell test.img
Singularity: Invoking an interactive shell within container...
Singularity test.img:~> ssh $HOSTNAME
```

Basically you can ssh into the host OS from inside a singularity container by default without having to configure anything thanks to how singularity shares your ~/.ssh folder for you (maybe not the best security model i've seen but convenient in this case).

So to run a container from inside a container, you just have to do `ssh $HOSTNAME 'singularity exec foo.img'` or something similar.
