### ISSUE TITLE
Provide an option at build time to specify the location of mksquashfs

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#1523]
As discussed here (https://github.com/easybuilders/easybuild-easyconfigs/pull/6287), it would be useful if Singularity provided a way to configure the location of the `mksquashfs` binary at build time.

**Comment by bauerm97** [comment]
Seems like a sensible option to provide, but I'm not sure how we can mangle that with autotools. Any suggestions @boegel or @GodloveD ?

**Comment by jmstover** [comment]
`--with-mksquashfs`
Something like ... 
```
AC_MSG_CHECKING([--with-mksquashfs])
AC_ARG_WITH([mksquashfs],
        AS_HELP_STRING([--with-mksquashfs], [Root location of mksquashfs install]))
AS_IF([test "x$with_mksquashfs" != "xno"]),
    [
      AC_CHECK_PROG(MKSQUASHFS_CHECK,mksquashfs,yes,no,$with_mksquashfs/bin)
      AS_IF([test "x$MKSQUASHFS_CHECK" == "xyes"],
          [
             AC_SUBST(MKSQUASHFS_PATH,$with_mksquashfs/bin)
          ])
    ])
```

That is totally probably not 100% right, but should be close. Then should be able to do something like:

`./configure --with-mksquashfs=/path/to/mksquashfs/verA.B.C`

Where `/path/to/mksquashfs/verA.B.C` is the `--prefix` where mksquashfs was installed. i.e. it has a `bin` directory, etc...

**Comment by GodloveD** [comment]
Want to take a crack at it @jmstover?

**Comment by jmstover** [comment]
Here's a start... 
https://github.com/jmstover/singularity/blob/mksquashfs_path/configure.ac#L269

When `./configure` is ran like:
`./configure --with-mksquashfs=/usr/local/mksquashfs` 
you get output like:
```
checking --with-mksquashfs... checking for mksquashfs... yes
using /usr/local/mksquashfs/bin
```
When I get the changes to where `mksquashfs` is being called in, I'll put up a PR

**Comment by jmstover** [comment]
Option in 2.6.0
