### ISSUE TITLE
Unprivileged Execution / no setuid

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#154]
I believe the mainline kernel version of user namespaces supports unprivileged user chroots, PID namespaces, remount of `/proc` and bind mounts.  Not sure about unprivileged loopback devices: that sounds sketchy to me.

Taken together, this means a good chunk of the functionality of Singularity could be done without `setuid` on future platforms.  It would be an interesting investigation to try to
- Drop the `setuid` bits on these platforms completely, OR
- Shrink the `setuid` executable to only contain the loopback manipulation - invoking this only when necessary, OR
- Produce a `setuid` and a not-`setuid` package, allowing admins to pick what level of functionality they want to provide at what level of risk.

(Ok, I'm not 100% sure this is in mainline: it's sometimes difficult to pick apart what's in mainline and what's Ubuntu-specific: the one thing I do know is RHEL7 does _not_ have the necessary backported patches for unprivileged bind mounts.)

**Comment by gmkurtzer** [comment]
The last time I looked at the linux user namespace I did not see it was possible to implement without a mapping of user IDs and on a large system it didn't seem maintainable.

Additionally, the points you bring up are worth further investigation (e.g. bind mounts) but it will preclude use of images as loop devices are host/system consumables and will require root access for the foreseeable future.

**Comment by bbockelm** [comment]
Indeed - from some informal discussions, I'm fairly pessimistic that this could be done in RHEL7: in terms of RedHat-derivatives, the timeframe is really RHEL8!  It might be "now" in terms Ubuntu.

(Again, this is all excluding the loopback)

I think this can be done by only mapping one or two IDs: we wouldn't need to map all the system users.

I have some code that does most of this on a modern Fedora - I was going to try to see how difficult it is to embed inside the Singularity codebase.

**Comment by gmkurtzer** [comment]
I'd love to see what you have running on Fedora for that.

If it is indeed possible to do all of the namespacing, setup and teardown, without requiring SUID, then anything left over could in theory be broken out into separate binaries that do single things and only called upon when necessary... So in theory, if not operating on an image, and no reason to hit the SUID code, do it all from unprivileged space.

**Comment by bbockelm** [comment]
Initial version works for my use case.  Closing for now.
