### ISSUE TITLE
Feature request: compose images, aka multi-image workflow

### ISSUE THREAD

**Issue by matpen** [apptainer/singularity#1543]
Following the [discussion](https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/PCDq55szaDI) with Vanessa, I decided to open this issue to discuss the possibility of implement a feature similar to [Docker Compose](https://docs.docker.com/compose/overview/).

The idea is to be able to combine two or more images that provide separate services (as explained [here](https://docs.docker.com/get-started/part3/#about-services) and [here](https://docs.docker.com/get-started/part5/). This way, images could be used as "building blocks" to prepare complex workflows directly in production, without the need to rebuild a new image ad-hoc.

Use case: my first experiment was with an image containing a simulation with OpenFOAM. The final size after following [this procedure](https://openfoam.org/download/5-0-ubuntu/) amounts to 500 MB. If the dependencies of the app change, the image needs to be rebuilt and redeployed. For example:

1. Prepare a Singularity image with OpenFOAM, and the simulation driver;
2. Upload the image to the production cluster (this is pain if the uplink is slow);
3. Run the image and get the first results;
4. Decide to change something in the app, and as a consequence, add further dependencies (say [SU2](https://su2code.github.io/));
5. Re-build and re-upload the image (this is pain) and re-iterate.

With the "compose" feature in place, the workflow would look like this:

1. Prepare a Singularity image with OpenFOAM, and deploy (needs to be done only once);
2. Prepare another image with the simulation driver, and deploy;
3. Combine the deployed images, and run the resulting container;
4. Add SU2 to the mix by simply building a new SU2 image, and deploy (needs to be done only once);
5. Change the simulation driver as often as desired (the image is small) and re-iterate.

Although I am unfamiliar with the code of Singularity, and a new user too, I hope the idea will raise some interest. In terms of implementation, the [overlays](https://singularity.lbl.gov/docs-overlay) sound similar to me, although only used at build time.

**Comment by sapetnioc** [comment]
That would be a great feature. Especially if it does not require to be root. I'm looking for a way to provide users with a set of components based on a common Singularity image. We can do something similar by distributing the base Singularity image and components as directories that will be binded at runtime. But it gets too complicated if the components have to add files in different places in the system.

**Comment by GodloveD** [comment]
Would making Singularity compatible with Kubernetes enable this?  

https://www.sylabs.io/2018/11/towards-native-integration-between-singularity-containers-and-kubernetes-announcing-an-open-source-project/

Or what about using HashiCorp's Nomad?

https://github.com/hashicorp/nomad

There is a rumor that it will include support for orchestrating Singularity containers soon?  Maybe v0.9?  @ArangoGutierrez might have more info on that front.

**Comment by bauerm97** [comment]
@matpen @sapetnioc @ArangoGutierrez @GodloveD Let's circle back to this. Singularity now supports Kubernetes orchestration as well as Hashicorp's Nomand (pending release from work done by @ArangoGutierrez ).

I don't think those newly supported integrations are quite what this is looking for, so I propose we brainstorm here and propose an orchestration-like feature native to Singularity if we decide it's necessary.

**Comment by dtrudg** [comment]
@vsoch has been taking this on at https://vsoch.github.io/2019/singularity-compose-alpha/ - I'm going to close it here, as I don't think we are looking to add a native compose as part of the distributed version of SIngularity, and there's that external project ongoing.

**Comment by vsoch** [comment]
http://singularityhub.github.io/singularity-compose
