### ISSUE TITLE
This host does not support the NO_NEW_PRIVS prctl functions!

### ISSUE THREAD

**Issue by igory1999** [apptainer/singularity#1547]
## Version of Singularity: 

2.5.1

### Expected behavior

./configure should work

### Actual behavior

When running configure, I am getting this error

checking for feature: NO_NEW_PRIVS... no
ERROR!!!!!!
This host does not support the NO_NEW_PRIVS prctl functions!
The kernel must be updated to support Singularity securely.

### Steps to reproduce behavior

cat /etc/issue
Ubuntu 16.04.4 LTS

uname -a
Linux ivy2-XPS-15 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

What kernel version under Ubuntu do I need for "NO_NEW_PRIVS prctl" to behave?
I did not have such problem on Sclentific Linux 6 or 7 with much older kernels.

**Comment by jmstover** [comment]
@igory1999 
Can you show me the output of:
`grep 'NO_NEW_PRIVS' /usr/include/linux/prctl.h`

Another test would be to try building from the `release-2.5` branch. We're doing checks in different ways between 2.5.1 and the `release-2.5` branch.

*Edit:*
But I would expect it to work just fine if you have all the headers. I ran configure on Debian 8 (3.16.0-4-amd64), and it didn't error out.

**Comment by igory1999** [comment]
$ grep 'NO_NEW_PRIVS' /usr/include/linux/prctl.h
#define PR_SET_NO_NEW_PRIVS     38
#define PR_GET_NO_NEW_PRIVS     39

By release-2.5 you mean 2.5.0 release version?

**Comment by igory1999** [comment]
2.5.0 complains the same way.
Notice I am installing from release tar.gz files. 
Should I do it from git?

**Comment by igory1999** [comment]
Latest git version has the same problem.

$ dpkg -S /usr/include/linux/prctl.h
linux-libc-dev:amd64: /usr/include/linux/prctl.h

$ dpkg -l | grep linux-libc-dev
ii  linux-libc-dev:amd64                                        4.4.0-124.148                                            amd64        Linux Kernel Headers for development

**Comment by jmstover** [comment]
> By release-2.5 you mean 2.5.0 release version?

No, there is a git branch named `release-2.5`. 

```
git clone https://github.com/singularityware/singularity singularity
cd singularity/
git checkout release-2.5
./autogen.sh
./configure --prefix=/usr/local/singularity/rel-2.5
make
sudo make install
```

**Comment by jmstover** [comment]
```
$ grep 'NO_NEW_PRIVS' /usr/include/linux/prctl.h
#define PR_SET_NO_NEW_PRIVS 38
#define PR_GET_NO_NEW_PRIVS 39
```

And this is what I'd expect to see here if it is supported, at least from user space. The `release-2.5` branch is defining those ourselves, if it isn't set in `linux/prctl.h`. 

What it _looks_ like, is the Kernel supports it, but there's something that's causing the call to fail. There was an old issue (#813), where Ubuntu 16.04.2 was throwing the error:

`WARNING: Not mounting current directory: host does not support PR_SET_NO_NEW_PRIVS`

But we recently made the decision to not even run/build on hosts where `NO_NEW_PRIVS` is not supported.

**Comment by igory1999** [comment]
Now I am running at a different problem (with release-2.5 branch):

...
checking for archive.h... no
configure: error: Unable to find the libarchive headers, need package libarchive-devel (libarchive-dev on Debian/Ubuntu)


$ dpkg -l | grep libarchive
ii  libarchive-dev:amd64                                        3.1.2-11ubuntu0.16.04.3                                  amd64        Multi-format archive and compression library (development files)
ii  libarchive-zip-perl                                         1.56-2                                                   all          Perl module for manipulation of ZIP archives
ii  libarchive13:amd64                                          3.1.2-11ubuntu0.16.04.3                                  amd64        Multi-format archive and compression library (shared library)
ii  python3-libarchive-c                                        2.1-3                                                    all          Python3 interface to libarchive

$dpkg -L libarchive-dev
...
/usr/include/archive.h
...


I do have libarchive-dev, what's the problem? Wrong version?

**Comment by GodloveD** [comment]
Hi @igory1999.  The 2.5+ versions of Singularity add an external dependency called `libarchive-dev`.  You need to install it using:

```
sudo apt-get install libarchive-dev
```

**Comment by igory1999** [comment]
But I already have it:
$ sudo apt-get install libarchive-dev
[sudo] password for igor: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libarchive-dev is already the newest version (3.1.2-11ubuntu0.16.04.3).
libarchive-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

**Comment by GodloveD** [comment]
Hi @igory1999 I think there is definitely something weird going on with you system.  I can't replicate your original error with a fresh Ubuntu 16.04 VM.  

```
vagrant@ubuntu-xenial:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

vagrant@ubuntu-xenial:~$ uname -a
Linux ubuntu-xenial 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

vagrant@ubuntu-xenial:~$ curl -s https://www.sylabs.io/privtest/no_new_privs.sh | bash
Good news! This kernel supports the PR_SET_NO_NEW_PRIVS feature!
```

**Comment by caot** [comment]
singularity-2.6.0 and Linux 2.6.32-**431**.23.3.el6.x86_64 had the same issue

```
checking for feature: NO_NEW_PRIVS... no

ERROR!!!!!!

This host does not support the NO_NEW_PRIVS prctl functions!
The kernel must be updated to support Singularity securely.
```

However it's built in Linux 2.6.32-**573**.el6.x86_64

**Comment by zhouanbo** [comment]
@igory1999 Probably your gcc version is wrong, do you have linuxbrew or something else overwrote your gcc path? You can remove those from ~/.bashrc and try agian.

**Comment by RicardoDominguez** [comment]
At the end of ~/.bashrc I had a few lines added by Anaconda. Removing these solved the issue.

**Comment by dtrudg** [comment]
Closing. A resolution was reported by one user, and no other follow-up.
