### ISSUE TITLE
--nv option not working

### ISSUE THREAD

**Issue by efajardo** [apptainer/singularity#1548]
## Version of Singularity:

2.5.0-dist

### Actual behavior

singularity shell --nv /cvmfs/singularity.opensciencegrid.org/opensciencegrid/tensorflow-gpu:latest
WARNING: Skipping user bind, non existent bind point (file) in container: '/bin/nvidia-smi'
WARNING: Library bind directory not present in container, update container
WARNING: Trying to create directory .singularity.d outside of container in /var/singularity/mnt/final
ERROR  : Failed creating directory /var/singularity/mnt/final/.singularity.d/libs :No such file or directory
ABORT  : Retval = 255

### Steps to reproduce behavior

singularity shell --nv /cvmfs/singularity.opensciencegrid.org/opensciencegrid/tensorflow-gpu:latest
WARNING: Skipping user bind, non existent bind point (file) in container: '/bin/nvidia-smi'
WARNING: Library bind directory not present in container, update container
WARNING: Trying to create directory .singularity.d outside of container in /var/singularity/mnt/final
ERROR  : Failed creating directory /var/singularity/mnt/final/.singularity.d/libs :No such file or directory
ABORT  : Retval = 255

The new "experimental" option ``-nv`` does not work. I wonder if `.singularity.d` or .singularity.d./libs` need to be created inside the singulairty image.

**Comment by GodloveD** [comment]
Heya @efajardo I think several other people have already reported this error and @cclerget has written a patch.  Can you test this?  https://github.com/singularityware/singularity/pull/1525

**Comment by efajardo** [comment]
Hi @GodloveD, So if I understand correctly this did not make it to 2.5.1 release?

**Comment by GodloveD** [comment]
No.  It's slated for the next release.

**Comment by efajardo** [comment]
What is the timeline for the next release? We are just releasing 2.5.1 on OSG, so I can decide if I create a patch against 2.5.1 and rerelease or wait for 2.5.2?

**Comment by GodloveD** [comment]
@efajardo Releases are historically dictated by need, but we are trying to get into a 2 month release cadence.  That would put the next release at about 6 weeks.

**Comment by DrDaveD** [comment]
I note that Igor Yakushin said on the singularity users mailing list that --nv works for him with exec but not shell.

**Comment by efajardo** [comment]
Nop @DrDaveD, same error

```
ABORT  : Retval = 255
[1526] efajardo@uaf-1 ~$ singularity exec --nv /cvmfs/singularity.opensciencegrid.org/opensciencegrid/tensorflow-gpu:latest echo "Hello world"
WARNING: Skipping user bind, non existent bind point (file) in container: '/usr/bin/nvidia-smi'
WARNING: Library bind directory not present in container, update container
WARNING: Trying to create directory .singularity.d outside of container in /var/singularity/mnt/final
ERROR  : Failed creating directory /var/singularity/mnt/final/.singularity.d/libs :No such file or directory
ABORT  : Retval = 255
```

**Comment by DrDaveD** [comment]
I worked with @efajardo on this, and his main problem was that overlay was disabled.  Pr #1525 does not appear to make a difference so far.

**Comment by GodloveD** [comment]
The `--nv` option should work regardless of whether overlayfs is available/configured. 🤔 

So, just to be clear @DrDaveD are you saying that this error goes away when overlay is enabled, but that #1525 does not fix the error?

**Comment by DrDaveD** [comment]
That's correct.  The errors go away when overlay is enabled, and #1525 has no effect.  There's a new error
```
ERROR  : Could not write to /var/singularity/mnt/final/bin/nvidia-smi: Operation not supported
```
and that is because it is on top of cvmfs which has the problem reported in #943.  One of the warnings is still there
```
WARNING: Library bind directory not present in container, update containe
```
because the image doesn't have /.singularity.d and /.singularity.d/libs.

Regardless of how the --nv option should work, it does not do any creating of mountpoints, so it assumes they're either already there in the image or overlayfs is enabled.  Edgar is planning to get that image updated to have those mountpoints.

**Comment by GodloveD** [comment]
Oh you know what?  I should have looked more closely at the errors and warnings in the original post.

```
WARNING: Library bind directory not present in container, update container
```
This is at least part of the problem.  

Many versions ago @gmkurtzer added the `/.singularity.d` directory to containers.  That warning is essentially telling you that your container is so old that it doesn't have the place where Singularity is supposed to keep metadata.  That is necessary for the --nv option to work.

**Comment by efajardo** [comment]
Good catch. Well I will have to update all the images then.

**Comment by DrDaveD** [comment]
Right.  --nv also assumes that there's either overlayfs or a /bin/nvidia-smi mountpoint.

**Comment by GodloveD** [comment]
@DrDaveD  Where?  It shouldn't. Maybe I'm wrong though. Wouldn't be the first time.

**Comment by GodloveD** [comment]
Oh no.  I think you are right @DrDaveD. 

https://github.com/singularityware/singularity/blob/master/libexec/cli/action_argparser.sh#L146-L153
We are just being lazy and adding it to the bindpath var.

I will state though that it is not really necessary for `nvidia-smi` to be inside the container for the user to be able to use the graphics card.  `nvidia-smi` is really just a convenience.  Early versions of the `--nv` option did not even attempt to bind mount it into the container, and things like cuda should work just fine without it.  

So as long as recent changes don't cause Singularity to error out if it cannot bind mount `nvidia-smi` then the `--nv` option technically still works without overlay.  It's just not as full-featured I guess.

**Comment by efajardo** [comment]
Woho bingo, It looks like it works:

```[0741] cuser1@cgpu-1 ~$ singularity exec --contain --ipc --pid --home $PWD:/srv --nv /cvmfs/singularity.opensciencegrid.org/opensciencegrid/tensorflow-gpu:latest nvidia-smi
Fri Jun  1 14:42:03 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
| 23%   43C    P0    61W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 23%   41C    P0    61W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:08:00.0 Off |                  N/A |
| 23%   40C    P0    60W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
| 23%   39C    P0    60W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  Off  | 00000000:84:00.0 Off |                  N/A |
| 23%   41C    P0    61W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  Off  | 00000000:85:00.0 Off |                  N/A |
| 23%   38C    P0    61W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  Off  | 00000000:88:00.0 Off |                  N/A |
| 23%   35C    P0    60W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  Off  | 00000000:89:00.0 Off |                  N/A |
| 23%   36C    P0    61W / 250W |      0MiB / 11178MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+```

**Comment by GodloveD** [comment]
Yay!

**Comment by GodloveD** [comment]
I'm going to go ahead and close this for now.  But feel free to re-open if you hit any other roadblocks.

**Comment by efajardo** [comment]
@GodloveD should the documentation be updated to signal somewhere that in the future it is recommended that containers have `/singularity.d` inside (or as part of the help with the nv option)

**Comment by GodloveD** [comment]
Yeah that would probably be a good idea.

**Comment by shengdie** [comment]
I found that, `--nv` worked for normal image, but did not work for instance. Any idea?
