### ISSUE TITLE
Create parent directories for files added in %file section

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#1549]
Filed on behalf of @fdawg4l

## Version of Singularity:

2.5.1

### Expected behavior

The `%files` section should create the parent directory tree for a file if it doesn't already exist. 

### Actual behavior

I have to copy my binary to a tmp location then move it in `%post`.

### Steps to reproduce behavior

If you want to copy a file to a directory structure that does not yet exist before the `%post` section you must do something like this:

```
Bootstrap: docker
From: busybox

%files
    ./foo /foo

%post
    mkdir -p /my/file/location
    mv /foo /my/file/location/foo
```

It would be much nicer if one could just do this:

```
Bootstrap: docker
From: busybox

%files
    ./foo /my/file/location/foo
```

**Comment by mathiaswagner** [comment]
This would be great. Or a way to create some directories explicitly in the files section before copying data.
Installation packages could then also be copied to a dir obtained with `mktemp`

**Comment by donkirkby** [comment]
The workaround of copying files to root and then moving them in the `%post` section works, but it's a pain when you have a lot of files. Here's another workaround that creates the directory in the `%setup` section and then copies the files to the correct place in the `%files` section.

    Bootstrap: docker
    From: busybox
    
    %setup
        mkdir -p ${SINGULARITY_ROOTFS}/my/file/location
    
    %files
        ./foo /my/file/location/foo
