### ISSUE TITLE
Temporary files cause build error in `%files

### ISSUE THREAD

**Issue by rprechelt** [apptainer/singularity#1587]
## Version of Singularity:

2.5.1-master.gba7cf79

### Actual behavior

When copying files in the `%files` section, the presence of a file that matches the pattern `.#*` causes a build error to print to the screen. 

```
/bin/cp: cannot stat '.#example.h': No such file or directory
ERROR: Failed copying file(s) into container
```
The file does exist and can be `stat'd` from the shell but requires an escape i.e. `stat .\#example.h`

### Expected behavior

I think that this should be handled cleanly. I don't have a preference whether the files are copied or are not copied into the build (as they tend to be editor backups), but reporting an error seems excessive when the file does actually exist (especially since these are occasionally hidden in deep directories inside our users code). 

### Steps to reproduce behavior

Create a `.#example.h` file and attempt to transfer it into the container during `%files`.

**Comment by dtrudg** [comment]
No longer an issue in 3.5

```
10:24 AM $ cat testcp.def 
Bootstrap: docker
From: alpine

%files
    .#example.h

dave@piran:~

10:24 AM $ sudo singularity build test.sif testcp.def 
[sudo] password for dave: 
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob c9b1b535fdd9 [--------------------------------------] 0.0b / 0.0b
Copying config 0d716090a9 done  
Writing manifest to image destination
Storing signatures
2020/02/05 10:25:02  info unpack layer: sha256:c9b1b535fdd91a9855fb7f82348177e5f019329a58c53c47272962dd60f71fc9
INFO:    Copying .#example.h to /tmp/rootfs-0e2974b2-4834-11ea-a568-e0d55e6c2d0d/.#example.h
INFO:    Creating SIF file...
INFO:    Build complete: test.sif

10:25 AM $ singularity exec test.sif ls -lah /
total 10K    
drwxr-xr-x    1 dave     docker        80 Feb  5 10:25 .
-rw-r--r--    1 root     root           0 Feb  5 10:25 .#example.h
drwxr-xr-x    1 dave     docker        80 Feb  5 10:25 ..
...
