### ISSUE TITLE
Production image can be modify

### ISSUE THREAD

**Issue by mhebrard** [apptainer/singularity#1590]
## Version of Singularity:

v2.4-dist
on Windows 7
using Vagrant, VirtualBox and Ubuntu 
(following installation documentation)

### Expected behavior

I created a prod image from a recipe
`sudo singularity build container.simg Singularity`

I enter the image in sudo mode
`sudo singularity shell container.simg`

Form here I can navigate in the image file system and read files
`cat /myfile.txt`

But I should not be able to write in the file or remove the file
as the image is "read-only"

### Actual behavior

created a prod image from a recipe
`sudo singularity build container.simg Singularity`

enter the image in sudo mode
`sudo singularity shell container.simg`

write in a file
`echo "I modify the file" > /myfile.txt`

delete a file
`rm /myfile.txt`

Note: when I exit the image, the modification do not persist and my image is restored.
But if I read the documentation well, I should not be able to write in the prof image at all

### Steps to reproduce behavior

follow the commands above

**Comment by GodloveD** [comment]
Hey @mhebrard.  Sorry, this seems to be a failure of documentation.  A small overlay file system is created when you run Singularity that allows you to make ephemeral changes to your container.
