### ISSUE TITLE
Fix signal handling

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#160]
The signal handling isn't quite there yet...

Singularity namespace / exec processes already sit around with effective mode equal to the unprivileged user.  We should use the "standard" pipe tricks (i.e., it's valid to write a single byte to a pipe from a signal handler) to propagate signals sent to the namespace process down to the exec & payload processes.

This should help the batch system to gracefully kill the container without having to resort to `SIGKILL`.

**Comment by gmkurtzer** [comment]
I agree that there are still some issues with the signal handling. I would love to see (or hear more about) what you are thinking about using a pipe to propagate the signal.

Thanks!

**Comment by bbockelm** [comment]
Ok, I'm close to getting a pull request setup for this.

Actually, this breaks down nicely into two requests:
1.  Setup signal handlers in the monitor processes (namespace and exec).  The signal handler for SIGINT, SIGQUIT, SIGKILL, and SIGCHLD simply writes to a pipe the signal number.  The process - instead of blocking on `waitpid()` - blocks on `poll`.  Once the read side of the pipe has data ready (i.e., the signal handler fired and wrote to it), it will either return immediately (for SIGCHLD) or invoke `kill(child_pid, SIGWHATEVER)` (passing the signal to the child).  The parent process then calls `waitpid(child_pid)`.
   - The idea here being that we forward signals from parent to child, then return with whatever the appropriate exit status is from the child.  We _do not_ escalate immediately to SIGKILL as in the current code as this may change semantics.
2.  Setup a read/write pipe that's passed between the namespace process and the exec process such that the write end is only opened in the namespace process and the read end is only open in the exec process.  The read end is also added to the above `poll` invocation.  If `poll` ever triggers on this file descriptor, it means the namespace process has died via `SIGKILL`.  In _this_ case, the exec process should immediately `SIGKILL` the child process.

If both the namespace and exec process are immediately killed - well, hope that PID namespaces are used and the kernel does its job.

So, while it's somewhat subtle semantics, this is all fairly bog-standard POSIX process handling.

**Comment by gmkurtzer** [comment]
Very cool, I look forward to seeing the implementation! Thanks!

**Comment by bbockelm** [comment]
Ok, implementation of both mentioned above is in #171 .

_However_, there's an additional issue I had forgotten: there are special rules for signal handling for PID 1 in a PID namespace.  All signals that normally cause the process to terminate (`SIGQUIT`, `SIGTERM`, etc) will instead be ignored.

So, we can send as many `SIGTERM` as we want and `bash` will happily ignore it.

This will get ... complicated.  To solve this elsewhere, we had to write a shim executable to serve as PID1 that did the rest of the .  Of course, in that case we didn't have a fresh chroot to contend with!

Will think on it.

**Comment by bbockelm** [comment]
Oh, duh!

If we move the exec daemon into the PID namespace, then _it_ becomes PID 1 and the user payload (`/bin/sh` or whatnot) becomes PID 2.  Then, when we pass signals to `sh`, it behaves "as expected".

**Comment by bbockelm** [comment]
Ok, I think I'm happy with #171 - but needs careful review.

**Comment by bbockelm** [comment]
This was merged awhile back.  Closing.

**Comment by gmkurtzer** [comment]
I never closed it because I wanted to get it integrated into the devel branch. But with that said, it is fine to close it now as it is on my "list" LOL. Thanks!
