### ISSUE TITLE
Exec fails with unkown GID

### ISSUE THREAD

**Issue by SichongP** [apptainer/singularity#1603]
## Version of Singularity:

2.5.1-dist

### Expected behavior

Fetch docker container, run command and exit

### Actual behavior

Exit on error:
```ERROR   [U=20921,P=19921]  singularity_runtime_files_group()         Failed to lookup GID 1098694761 group entry: Invalid argument```

### Steps to reproduce behavior

Run command on an HPC node:
```singularity --debug exec --bind /home/pengsc/dahak/taco-read-filtering/data/:/data/ docker://quay.io/biocontainers/fastqc:0.11.7--pl5.22.0_2 fastqc```

This gid is a supplementary gid that does not have a name. I asked my sysadmin about it and here is his reply:

It's not really a gid, it's part of the way Linux impliments PAGs (process
authentication groups).  They are randomly generated when you log in and
used to track your credentials to access the fileservers.  Because they are
different each time you log in, there is no way to map them to a name.

It is possible to remove yourself from a PAG and create a new one (and thus
get a different randomly assigned "gid") but I am not sure if it is
possible to remove yourself and not create a new one.

Honestly, it seems like a bug in singularity that might be worth following
up with the developers about.

**Comment by cclerget** [comment]
@SichongP You're right, Singularity could just display a warning instead of an error since it should work fine without a name mapped to GID. The workaround is to set configuration directive `config group = no` in `singularity.conf`. A fix will be submitted to address the issue.

**Comment by dtrudg** [comment]
The reference fix was submitted in the 2.6 cycle.
