### ISSUE TITLE
Docker fails to build Singularity image bootstrapped off another image

### ISSUE THREAD

**Issue by brooklynbagel** [apptainer/singularity#1606]
## Version of Singularity:

2.5.1-dist

### Expected behavior

I am trying to run a container on Docker with Singularity to build a Singularity image. This is supposed to be a two-step process with one image built on top of another as seen in the included Makefile.

```
make myapp.img
docker run --rm \
  --privileged \
  -v /Users/Michael/myapp:/builddir \
  -w /builddir \
  --name singularity-build \
  brooklynbagel/singularity:2.5.1 \
  singularity build myapp.img Singularity
Using container recipe deffile: Singularity
...
Building Singularity image...
Singularity container built: myapp.img
```

### Actual behavior

The build of the first image (shiny.img) succeeds, however Singularity fails to extract the contents of this intermediate image before building the next one.

```
make myapp.img
docker run --rm \
  --privileged \
  -v /Users/Michael/myapp:/builddir \
  -w /builddir \
  --name singularity-build \
  brooklynbagel/singularity:2.5.1 \
  singularity build myapp.img Singularity
Using container recipe deffile: Singularity
Sanitizing environment
Adding base Singularity environment to container
Exporting contents of shiny.img to /tmp/.singularity-build.o7e9bL
tar: ./usr/local/bin: Directory renamed before its status could be extracted
tar: ./usr/lib/x86_64-linux-gnu/pkgconfig: Directory renamed before its status could be extracted
...
tar: ./bin: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
ERROR: Failed to export contents of shiny.img to /usr/local/var/singularity/mnt/container
ABORT: Aborting with RETVAL=255
Cleaning up...
make: *** [myapp.img] Error 255
```

### Steps to reproduce behavior

Unzip [repex.zip](https://github.com/singularityware/singularity/files/2041294/repex.zip) and change into the directory and run the following:

```
docker pull brooklynbagel/singularity:2.5.1
make myapp.img
```

The Dockerfile used to create the image containing Singularity is included as well as a test app for my example.

Contents of the Makefile:

```
myapp.img: Singularity shiny.img
	docker run --rm \
		--privileged \
		-v ${PWD}:/builddir \
		-w /builddir \
		--name singularity-build \
		brooklynbagel/singularity:2.5.1 \
		singularity build $@ $<

shiny.img: shiny.def
	docker run --rm \
		--privileged \
		-v ${PWD}:/builddir \
		-w /builddir \
		--name singularity-build \
		brooklynbagel/singularity:2.5.1 \
		singularity build $@ $<
```

and Dockerfile:

```
FROM debian:stretch-slim

LABEL maintainer="Michael Beigelmacher <mbeigelmacher@landeranalytics.com>"

ENV SINGULARITY_VERSION=2.5.1

# Update and install dependencies
RUN apt-get update && \
  apt-get install --no-install-recommends -y \
  python \
  dh-autoreconf \
  build-essential \
  libarchive-dev \
  debootstrap \
  squashfs-tools \
  ca-certificates \
  curl && \
  # Download and install Singularity
  wget https://github.com/singularityware/singularity/releases/download/${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz && \
  tar xf singularity-${SINGULARITY_VERSION}.tar.gz && \
  cd singularity-${SINGULARITY_VERSION} && \
  ./configure --prefix=/usr/local --sysconfdir=/etc && \
  make && \
  make install && \
  # Clean up
  rm -rf \
  /singularity* \
  /var/lib/apt/lists/*

CMD ["/usr/local/bin/singularity", "selftest"]
```

The [make-log.log](https://github.com/singularityware/singularity/files/2041302/make-log.log) is included as well.

**Comment by cclerget** [comment]
@brooklynbagel the error `Directory renamed before its status could be extracted` seems to be related to docker+overlayfs driver and tar command rather than singularity. Here a rather elegant and simple workaround https://github.com/docker/hub-feedback/issues/727#issuecomment-299533372 to add in your Dockerfile

**Comment by dtrudg** [comment]
Hi @brooklynbagel - there's some discussion on #1570 as well for this. As I mentioned there:

> I don't think we'd want to change anything in Singularity here tbh. The underlying issue is a kernel bug in overlayfs that causes a problem when tar is used within a docker environment where docker is using the overlayfs storage driver. Apparently kernels >=4.13 fix this issue. Though bsdtar sounds like it is a workaround I don't think we'd want the extra dependency, and it'd definitely not come in a point release.
