### ISSUE TITLE
lack of parity with Docker for overlapping binds

### ISSUE THREAD

**Issue by mr-c** [apptainer/singularity#1607]
## Version of Singularity:
2.5.1
### Expected behavior
Be able to bind mount an external directory read-write into the container and also bind mount a file into that directory read-only; just like Docker can
### Actual behavior
> WARNING: Ignored, try to create file /var/lib/singularity/mnt/final/var/spool/cwl/input.txt outside of container /var/lib/singularity/mnt/final/var/spool/cwl
### Steps to reproduce behavior
```
git clone https://github.com/common-workflow-language/common-workflow-language.git
pip install cwltool
cwltool --cache cache --debug --singularity 'v1.0/search.cwl#main' v1.0/search-job.json
```
`cwltool` will invoke `singularity` like this:
```
singularity     exec \
     --contain \
     --pid \
     --ipc \
     --bind \
     common-workflow-language-master/v1.0/cache/17989a049edd696744704b7255ebd187:/var/spool/cwl:rw \
     --bind \
     /tmp/:/tmp:rw \
     --bind \
     common-workflow-language-master/v1.0/v1.0/hello.txt:/var/lib/cwl/stge2d87f16-1adf-435f-9a84-ba3d654a9aa7/hello.txt:ro \
     --bind \
     common-workflow-language-master/v1.0/v1.0/index.py:/var/lib/cwl/stg82c8433e-389d-4b51-b38f-e16219091acb/index.py:ro \
     --bind \
     common-workflow-language-master/v1.0/v1.0/whale.txt:/var/spool/cwl/input.txt:ro \
     --pwd \
     /var/spool/cwl \
     common-workflow-language-master/v1.0/python-2-slim.img \
     python \
     /var/lib/cwl/stg82c8433e-389d-4b51-b38f-e16219091acb/index.py \
     input.txt
```

The equivalent and functional `docker` invocation:
```
docker \
    run \
    -i \
    --volume=common-workflow-language-master/v1.0/cache/17989a049edd696744704b7255ebd187:/var/spool/cwl:rw \
    --volume=/tmp:/tmp:rw \
    --volume=common-workflow-language-master/v1.0/v1.0/hello.txt:/var/lib/cwl/stgc5a82d64-41e0-448b-90f8-e4f0b8c27df2/hello.txt:ro \
    --volume=common-workflow-language-master/v1.0/v1.0/index.py:/var/lib/cwl/stg76bdd371-e341-4a33-ab20-fe78776a14d5/index.py:ro \
    --volume=common-workflow-language-master/v1.0/v1.0/whale.txt:/var/spool/cwl/input.txt:ro \
    --workdir=/var/spool/cwl \
    --read-only=true \
    --user=1002:1002 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/var/spool/cwl \
    python:2-slim \
    python \
    /var/lib/cwl/stg76bdd371-e341-4a33-ab20-fe78776a14d5/index.py \
    input.txt
```

**Comment by cclerget** [comment]
@mr-c For security reasons singularity don't create files/directories outside of its managed directories which are container overlay and session directory. You encounter this error because you are using nested binds, so following your example if `common-workflow-language-master/v1.0/cache/17989a049edd696744704b7255ebd187/input.txt` doesn't exist, singularity won't create file for you, you will need to create an empty `common-workflow-language-master/v1.0/cache/17989a049edd696744704b7255ebd187/input.txt` file and that will work

**Comment by tomjonandy** [comment]
Hi, I have just tripped over pretty much this exact problem. Forgive me if I am misunderstanding, but shouldn't overlayfs enable this to work without having to create any files outside of the singularity managed directories?

**Comment by cclerget** [comment]
Hi @tomjonandy , overlayfs can create file only on top of directory it managed, if you need to bind by example `/data` into container root filesystem, overlay will create `data` automatically but once host `/data` is mounted, it's not part of overlayfs anymore but a binded directory of your host filesystem and Singularity won't create files/directories in this directory.

**Comment by mr-c** [comment]
Why was this closed @dtrudg ?

**Comment by dtrudg** [comment]
Hi @mr-c - It was closed as there hasn't been any update since Jun 2018, and I read @cclerget 's reply as a 'wontfix'.

@cclerget - is this something possible to address at some point? If so we can keep it open. If not I'd rather close it as something that will not be addressed.

**Comment by cclerget** [comment]
@dtrudg Nested bindings are supported since 3.4 or 3.5, I don't remember exactly, so it can stay closed as this is related to v2 and  recent v3 versions are supporting this
