### ISSUE TITLE
singularity error on  perl

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [apptainer/singularity#1608]
## Version of Singularity:
I use this version of singularity singularity  --version
2.5.1-release-2.5.g9170f65
from docker image ("docker://mauriziobioinfo/oktagon)
Write here.
`singularity exec --home /home/maurizio/Desktop/TEST_VCF_MAF  /home/maurizio/Desktop/TEST_VCF_MAF/.snakemake/singularity/28834db900da97fe8216533394636f36.simg bash`
If I use the docker version I have this reults:
erl vcf2maf.pl -h
Usage:
     perl vcf2maf.pl --help
     perl vcf2maf.pl --input-

but in the singularity machine after use exec I have this:

```
maurizio@localhost:~$ perl vcf2maf.pl  --help
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Can't locate strict.pm:   Permission denied at vcf2maf.pl line 5.
BEGIN failed--compilation aborted at vcf2maf.pl line 5.
```

**Comment by dtrudg** [comment]
Hi @bioinfo-dirty-jobs - how are you building the container? Is it possible you don't have locales generated inside the container for en_GB.UTF-8?

If you want en_GB.UTF-8 for this container you can try adding this to the docker recipe (assuming it is a deibian/ubuntu base)

```
RUN locale-gen en_GB.UTF-8  
ENV LANG en_GB.UTF-8  
ENV LANGUAGE en_GB:en  
ENV LC_ALL en_GB.UTF-8  
```

**Comment by bioinfo-dirty-jobs** [comment]
thanks so much @dctrud  IPrepare singularity strting from docker image.
This is (link)[https://github.com/bioinfo-dirty-jobs/OKTAGON/blob/master/Dockerfile]
 On docker  only work but not in singularity. I suppose because singularity can use root user
