### ISSUE TITLE
facing issue while running multiple dependent executable 

### ISSUE THREAD

**Issue by rajaajar87** [apptainer/singularity#1617]
Version of Singularity: : 2.4.2-dist

##### help wanted #########

We are trying to package the NAMD application into an container. 
While we running the application in single node it is running fine. But facing some issue while running it across multinode using charm

The command to using to run it on multi node 

**singularity exec  --bind /home/NAMD/input/stmv/:/tmp/ --pwd /tmp/ test6.simg  /NAMD/NAMD_2.12_Source/Linux-x86_64-icc/charmrun ++p 70 ++ppn 35 /NAMD/NAMD_2.12_Source/Linux-x86_64-icc/namd2 stmv.namd** 

Issue while running the command 

**Charmrun> scalable start enabled.
Charmrun> IBVERBS version of charmrun
Charmrun remote shell(node01.35)> **Cannot locate this node-program**: /NAMD/NAMD_2.12_Source/Linux-x86_64-icc/namd2
Charmrun remote shell(node01.35)> Exiting with error code 1
Charmrun remote shell(singularity.0)> **Cannot locate this node-program: /NAMD/NAMD_2.12_Source/Linux-x86_64-icc/namd2**
Charmrun remote shell(singularity.0)> Exiting with error code 1
Charmrun> Error 1 returned from remote shell (singularity:0)**

######### question #########################
Is there any way to run 2 executable simultaneously where one is calling the other one ?
here Charmrun is calling the namd2 executable where both are in the same container 

#######################################

**Comment by jscook2345** [comment]
@jmstover Do you know of anyone trying to use `charm` with `singularity`?
