### ISSUE TITLE
feature: allow for more than one docker layer cache directory (use-case: store popular base layers on /cvmfs)

### ISSUE THREAD

**Issue by lukasheinrich** [apptainer/singularity#1619]
At CERN we use singularity together with images stored on docker registries. Users typically build the images on top of official base images provided by the experiment. e.g. 

https://hub.docker.com/r/atlas/analysisbase/ or  https://hub.docker.com/r/atlas/athanalysis/

they then build new images using `Dockerfiles` and store them in a private Docker registry (run by the GitLab instance at CERN) and then use `singularity` to run containers based on those images on the shared interactive cluster.

e.g. an image build by GitLab CI via 

```
FROM atlas/analysisbase
ADD . /myanalysiscode
RUN cd myanalysiscode && make
```

might get used via

`singularity exec docker://gitlab-registry.cern.ch/myanalysis:latest /bin/bash`

Currently users can set `SINGULARITY_CACHEDIR` in order to cache images layers. Now, the bulk of the image size comes from the base layers, which many of the user images use. So it would be nice if we could utilize the our read-only filesystem CVMFS in order to cache those layers and use a separate user-writable cache for the user-specific layers.

This will also help deploying user-defined images on the WLCG grid via singularity.

cc'ing @bbockelm as he might also be interested in this

**Comment by DrDaveD** [comment]
Normally docker layers are stored as tarballs, and the cvmfs infrastructure is [not very well optimized for distributing tarballs](https://cvmfs.readthedocs.io/en/latest/cpt-repo.html?highlight=limitations#tarballs-zip-files-and-other-archive-files).   I would think that if this is implemented the tarballs should also be unpacked.  Perhaps @jblomer is interested as well.

**Comment by lukasheinrich** [comment]
yes, ideally we'd be able to have unpacked layers. This idea is closely related to the idea of the cvmfs graph driver that @jblomer et al have developed. I need to familiarize myself with the details of containerd snapshotters, but it would be nice if the snapshotter could construct a rootfs based on multiple sources (such as cvmfs, as well as local layer storage).

**Comment by jblomer** [comment]
@lukasheinrich Having the option of building the container root file system from multiple different sources would be ideal, and it is what we ideally want to see in containerd as well. We wouldn't even need a "cvmfs source", just a generic "file system source" is sufficient for a start. The containerd developers seem to be open to that and @rochaporto is interested in that, too.

**Comment by lukasheinrich** [comment]
Hi @jblomer,

excellent, I discussed this with @rochaporto as well. I tried describing the issue here https://github.com/containerd/containerd/issues/2391 but not sure I explained well, maybe you can take a look?

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by lukasheinrich** [comment]
as far as I know this has not been addressed yet. It would still be useful.

**Comment by pedroalvesbatista** [comment]
@lukasheinrich We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Pending issues from the old repo are copied to the new repo (https://github.com/apptainer/apptainer/issues/1389) and cleaned from the old, retired repo.
