### ISSUE TITLE
Unable to download docker image from Azure registry using OAuth2 authentication

### ISSUE THREAD

**Issue by hakonenger** [apptainer/singularity#1622]
## Version of Singularity:

2.5.1

### Expected behavior

Singularity should be able to download a docker image from an Azure registry.

### Actual behavior

Singularity is unable to log in, failing with the message

```
ERROR Error getting token for repository ***, please check your credentials.
'token'
Cleaning up...
```

I have attached the complete debug output here: 
[azure-registry-problem.txt](https://github.com/singularityware/singularity/files/2076221/azure-registry-problem.txt)

### Steps to reproduce behavior

`sudo singularity -d build test.simg docker://***.azurecr.io/***:latest`

**Comment by hakonenger** [comment]
I found that the reason for the issue seems to be that the docker registry uses OAuth2 authentication and returns the access token with the key "access_token" instead of "token", which Singularity expects. This is supported by Docker "for compatibility with OAuth2", see https://docs.docker.com/registry/spec/auth/token/#token-response-fields

Here is a patch that fixes the issue: [oauth2-token-patch.txt](https://github.com/singularityware/singularity/files/2076307/oauth2-token-patch.txt)

**Comment by hmeiland** [comment]
patch works great; should we make a pull request to get this into mainstream source?
thanks!

**Comment by hmeiland** [comment]
I've made a small change to the patch to not use depricated has_key and committed a PR...

**Comment by jakirkham** [comment]
Should this now be closed?

**Comment by jmstover** [comment]
This was merged into 2.6.0 as well

**Comment by JonShelley** [comment]
I just tried to do this and I am getting the same error. Not sure if I am doing something wrong or this is still not fixed.

Here is the error that I am seeing when I run the command
singularity -d build test.simg docker://***.azurecr.io/***/***:v1.3

DEBUG GET https://***.azurecr.io/v2/***/***/tags/list
DEBUG Http Error with code 401
DEBUG Requesting token from docker registry API
DEBUG GET https://***.azurecr.io/oauth2/token?scope=repository:***/***:pull&expires_in=300&service=***.azurecr.io
DEBUG Http Error with code 401
ERROR Error getting token for repository ***/***, please check your credentials.
No JSON object could be decoded
Cleaning up...

singularity --version
2.6.0-dist

**Comment by JonShelley** [comment]
I finally got it to work. For those that are interested I did

export SINGULARITY_DOCKER_USERNAME=\<username\>
export SINGULARITY_DOCKER_PASSWORD=\<password\>
singularity -d build test.simg docker://***.azurecr.io/***/***:v1.3

To get the value for \<username\> I did 
az acr credential show -n myACR --query username

To get the value for \<password\> I did
az acr credential show -n myACR --query passwords[0].value
