### ISSUE TITLE
List already mounted paths when issuing warning: `already mounted in container`

### ISSUE THREAD

**Issue by scalavision** [apptainer/singularity#1629]
I did use the -H and -B parameter with the same root path. I had some trouble finding that to be the cause of this warning. Think I would have seen it at once, if the already mounted path would be listed in the warning. Don't know how easy it is to add this though ...

https://github.com/singularityware/singularity/blob/d6e815477f1ce75389ea79dfc590390513c7102d/src/lib/runtime/mounts/userbinds/userbinds.c#L94

**Comment by dtrudg** [comment]
This is not a warning any more (mixing -H and -B)

`0:19 AM $ singularity run -H /data -B /data docker://alpine
Singularity> 
`

If you force it, the error now shows the destination:

```
10:21 AM $ singularity run -B /data -B /data:/data docker://alpine
WARNING: destination /data already in mount list: destination is already in the mount point list
Singularity> 
```
