### ISSUE TITLE
Restrict network access of a container

### ISSUE THREAD

**Issue by shengdie** [apptainer/singularity#1634]
I am running an untrusted app inside a container, I don't want it has network access. So I am wondering if there is a way to restrict the network access of a container and keep only localhost accessible? Thank you.

**Comment by jmstover** [comment]
Currently, if you run with network namespace (`-n`/`--net`), that should leave you with only the loopback device in the container.

**Comment by luator** [comment]
For future readers:  The full arguments that were needed for me to run a container without network access are

    --net --network none

**Comment by axel-h** [comment]
For further reference: Using `--network none` seems enough, it just prints a message then that says "`INFO:    Setting --net (required by --network)`"
