### ISSUE TITLE
Quoting from Docker image is broken

### ISSUE THREAD

**Issue by remram44** [apptainer/singularity#1640]
## Version of Singularity:

2.5.1-master.gd6e81547

### Expected behavior

Importing a Docker image gets you a runscript that runs `ENTRYPOINT`/`CMD`.

### Actual behavior

Invalidly quoted runscript.

### Steps to reproduce behavior

My Dockerfile:
```dockerfile
FROM ubuntu:16.04

ENTRYPOINT ["sh", "-c", "echo EP && \"$0\" \"$@\""]
CMD ["echo", "C"]
```

The generated `runscript`:
```sh
exec "sh" "-c" "echo EP && "$0" "$@"" "$@"
```

As you can see the quotes are not escaped. I can probably even get Singularity to generated a runscript with an odd number of quotes.

The correct `runscript` would be, if you take both into account (default to `CMD`):
```sh
exec "sh" "-c" "echo EP && \"\$0\" \"\$@\"" "echo" "C"
#    |------------ entrypoint ------------| | cmd |
```

If you mean to only take `entrypoint` into account (default to empty command):
```sh
exec "sh" "-c" "echo EP && \"\$0\" \"\$@\"" "$@"
#    |------------ entrypoint ------------| | cmd |
```

Related?
* #1020

**Comment by jscook2345** [comment]
@ikaneshiro 

I'm not sure we're fixing bugs for or doing updates for 2.5.1, but could you look into this and see what the fix would entail? If you're busy, please reassign to someone else who could take a look. Thanks!

**Comment by dtrudg** [comment]
I'm afraid that bug fixes aren't being developed for 2.x - if an issue occurs on current 3.x please open a new issue and we'd be glad to look into it.
