### ISSUE TITLE
'--nv' not working when running an instance 

### ISSUE THREAD

**Issue by shengdie** [apptainer/singularity#1644]
## Version of Singularity:
2.5.1

### Expected behavior
`--nv` should work on a instance like on an image.

### Actual behavior
gives error.

### Steps to reproduce behavior
Run an GUI app requires GPU, installed VirtualGL inside the image, the image contains a centos7. 
The 'runscript' is `vglrun [GUI app requires gpu]`.
Error 1.
run
```
singularity instance.start xxx.simg instance1
singularity run --nv instacne://instance1
```
gives
```
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
[VGL] ERROR: in glXGetConfig-
```
Error 2.
run
```
singularity instance.start --nv xxx.simg instance1
singularity run instance://instance1
```
gives
```
/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /.singularity.d/libs/libGLU.so.1)
/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /.singularity.d/libs/libGLU.so.1)
```
works fine if `run --nv xxx.simg` directly.

**Comment by cclerget** [comment]
Hi @shengdie , looks like a problem with environment variable LD_LIBRARY_PATH, you can try with :
```
singularity instance.start --nv xxx.simg instance1
SINGULARITYENV_LD_LIBRARY_PATH=/.singularity.d/libs singularity run instance://instance1

**Comment by shengdie** [comment]
Thanks @cclerget , but this does not work, also gives error2.

**Comment by dtrudg** [comment]
If similar issues occur with 3.x note that it's useful to use the NVIDIA OpenGL containers to ensure consistent OpenGL libraries are available.  https://hub.docker.com/r/nvidia/opengl/
