### ISSUE TITLE
Whiteout marker Error on Docker bootstrap

### ISSUE THREAD

**Issue by Wentzell** [apptainer/singularity#1649]
I am trying to build a Singularity Image from the [Docker Image](https://hub.docker.com/r/flatironinstitute/triqs/) of our scientific application.
It fails with `ERROR  : Error applying whiteout marker from docker layer.`.

Which part in the [Dockerfile](https://hub.docker.com/r/flatironinstitute/triqs/~/dockerfile/) leads to this Error?

## Version of Singularity: 
Singularity Version 2.5.1 @ CentOs7

### Expected behavior
Create Singularity Image from Docker Image

### Actual behavior
`ERROR  : Error applying whiteout marker from docker layer.`

### Steps to reproduce behavior
`singularity pull docker://flatironinstitute/triqs:unstable`

**Comment by dtrudg** [comment]
Hi @Wentzell - the link to the Dockerfile isn't working for me - can you paste it in or provide an alternative link? Thanks.

**Comment by Wentzell** [comment]
Hi @dctrud - The Dockerfile dan also be found [here](https://github.com/TRIQS/docker/blob/unstable/Dockerfile)

**Comment by dtrudg** [comment]
Hi @Wentzell - testing this with the 2.5.2-rc I wasn't able to trigger the error. Would you be able to try also? There was a patch that went in there to address a whiteout issue where the whiteout target is an absolute symlink.

Thanks!

**Comment by Wentzell** [comment]
Hi @dctrud This issue is indeed resolved in version 2.5.2

Thanks!
