### ISSUE TITLE
Building a singularity image from local docker image

### ISSUE THREAD

**Issue by ghost** [apptainer/singularity#1652]
I have a docker image which I haven't pushed to dockerhub. Whats the best way to convert it to a singularity container? The documentation seems to just reference using something like:

`singularity build lolcow.simg docker://godlovedc/lolcow`

Which requires pushing the image to docker hub first.

**Comment by cclerget** [comment]
Hi @vuiiscci , you can try this script https://github.com/singularityware/docker2singularity/blob/master/docker2singularity.sh to convert docker image to singularity image.

**Comment by ghost** [comment]
Great! Thank you!
