### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by doctorbird** [apptainer/singularity#1660]
## Version of Singularity:

2.3.2

### Expected behavior

Is there an easy way to tell which bootstrap file was used on an image once connected?

### Actual behavior

Write here.

### Steps to reproduce behavior

Write here.

**Comment by GodloveD** [comment]
Heya @doctorbird.  If you are outside of the container you can use the `inspect` command with the `--deffile` flag like so:
```
$ singularity inspect --deffile <container>
```
If you are inside the container the deffile is saved in metadata at the following location.
```
/.singularity.d/Singularity
```
If the container was built using multiple deffiles then the older ones will appear in order in the following directory:
```
/.singularity.d/bootstrap_history/
```
