### ISSUE TITLE
pull from a collection working but not whentrying to build using the same recipe file

### ISSUE THREAD

**Issue by laurentfournier** [apptainer/singularity#1665]
## Version of Singularity:

2.4.4

### Expected behavior

I need to modify https://singularity-hub.org/containers/2771 before building my image in order to have some fine tunings related to our infrastructure.

### Actual behavior

laurent@GigaStation:~$ singularity pull shub://eilon-s/centos6_vep
Progress |===================================| 100.0% 
Done. Container is at: /home/laurent/eilon-s-centos6_vep-master-latest.simg

It works. But if i grab the recipe file (even without modifying it)

laurent@GigaStation:~$ sudo singularity build --writable atWork/Singularity/vep.img vep.latest 
Using container recipe deffile: vep.latest
Sanitizing environment
Adding base Singularity environment to container
Docker image path: index.docker.io/willmclaren/ensembl-vep:latest
Cache folder set to /root/.singularity/docker
Exploding layer: sha256:b234f539f7a1d65eabae1617e63c81ac01768abffd48b5cbbf7166efca6a3429.tar.gz
Exploding layer: sha256:55172d420b43cf03feeec11bcc917c7ddfc192036102e065ab57aa9abb95311e.tar.gz
Exploding layer: sha256:5ba5bbeb6b91e2676c98255c6babc66d7b05cac40185eeba4b3773199c701da0.tar.gz
Exploding layer: sha256:43ae2841ad7a7fd1aeae30028105cac7f6ee0ec955e5229e52b3333fea3c17b5.tar.gz
Exploding layer: sha256:f6c9c6de41905e9a66f2bc2c4a19858c8dc5b0a94f01e03eafc719afe25888aa.tar.gz
Exploding layer: sha256:f8afebd4f3fbb47df59209f656cba29e2deca95eeb9894d7a9d559cc7c717017.tar.gz

gzip: /root/.singularity/docker/sha256:f8afebd4f3fbb47df59209f656cba29e2deca95eeb9894d7a9d559cc7c717017.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Cleaning up...

Any ideas ?

**Comment by jscook2345** [comment]
I think this is fixed in the 2.5.X release. If you're still interested please try out either the latest release or at least a 2.5.X release. I'd be happy to help you debug any further issues. Please reopen if there are issues.
