### ISSUE TITLE
handle docker image with reading tar warning

### ISSUE THREAD

**Issue by cavanwang** [apptainer/singularity#1669]
## Version of Singularity:
2.5.1-master.gd6e8154

### Expected behavior

normal build image using docker as a bootstrap

### Actual behavior

Succeed with "WARNING: Warning reading tar header: Ignoring malformed pax extended attribute"

### Steps to reproduce behavior

git clone the master branch. and then "autogen.sh && configure && make && sudo make install"

[root@n15 gaussbatch]# sl build tmp_slbuild.img slbuild
Using container recipe deffile: slbuild
Sanitizing environment
Adding base Singularity environment to container
Docker image path: 192.168.0.15:5000/centos:7
Cache folder set to /root/.singularity/docker
Exploding layer: sha256:697841bfe295d2795d453ecc515162d7b5a2e3a338c8bf626505629591321402.tar.gz
WARNING: Warning reading tar header: Ignoring malformed pax extended attribute
WARNING: Warning reading tar header: Ignoring malformed pax extended attribute
WARNING: Warning reading tar header: Ignoring malformed pax extended attribute
Exploding layer: sha256:558600d55482e5fd0a12cdd238614259008e5888b4fa17b6a723796694ba11f3.tar.gz
Finalizing Singularity container
Calculating final size for metadata...
Skipping checks
Building Singularity image...
Singularity container built: tmp_slbuild.img
Cleaning up...
[root@n15 gaussbatch]# which sl
alias sl='singularity'
	/usr/local/bin/singularity
[root@n15 gaussbatch]# sl --version
2.5.1-master.gd6e8154 
[root@n15 gaussbatch]# cd singularity.dev/ && git branch
  development-2.x
* master

**Comment by dtrudg** [comment]
Hi @cavanwang - these warnings don't affect the output, in terms of producing a working CentOS7 container.

The library we are using to do the extraction has an issue open that explains why these warnings are seen: https://github.com/libarchive/libarchive/issues/752

The warnings, should, in fact be fixed if you are running with a very recent libarchive on your system - but most HPC systems will not.

**Comment by cavanwang** [comment]
Thanks for your quick response!
