### ISSUE TITLE
 ABORT: Container working directory has wrong ownership

### ISSUE THREAD

**Issue by kenneth59715** [apptainer/singularity#168]
I'm trying to start up a container as a non-root user with the --contain option but get an error:
 ABORT: Container working directory has wrong ownership

It looks like there is a a check is_owner that wants the sessiondir to be owned by uid 0?
Is there a way for a non-root user to start up a container with --contain?

@rpwagner

Kenneth

**Comment by gmkurtzer** [comment]
Hi Kenneth,

What version of singularity are you using?

Thanks!

**Comment by kenneth59715** [comment]
Greg,

Looks like 2.0:
/opt/singularity/bin/singularity --version
2.0

Kenneth

**Comment by gmkurtzer** [comment]
I will confirm that this isn't still an issue with the pending 2.1 release. Thanks!

**Comment by kenneth59715** [comment]
Thanks, Greg.  In the meantime, should I download the current code or should I wait
for the 2.1 release?

Kenneth

**Comment by rpwagner** [comment]
@kenneth59715, we can upgrade the system deployment quickly if needed

**Comment by gmkurtzer** [comment]
Confirmed that this is working on the 2.1 pre-release.

**Comment by kenneth59715** [comment]
Awesome!  Thanks, Greg.  @rpwagner, can we try out the testing release or do you
want to wait until official 2.1 release?
https://github.com/gmkurtzer/singularity/releases/tag/v2.1-testing

**Comment by gmkurtzer** [comment]
Woops, that tag isn't supposed to be there! It references an older 2.1 testing that has been superseded. I deleted it. Sorry for the confusion!

If you want to test the pre-release, please grab it from the 2.x branch.

Thanks!!

**Comment by kenneth59715** [comment]
@rpwagner it looks like the 2.1 release is available!
https://github.com/gmkurtzer/singularity/releases

**Comment by rpwagner** [comment]
Yep. @kenneth59715, I've already asked the team to push it out to Comet & Gordon and then notify you.

**Comment by gmkurtzer** [comment]
I am closing this issue as I believe it is resolved. Please comment on the issue if I am mistaken and I will reopen it.

Thank you!
