### ISSUE TITLE
Three files are left in /tmp after every instance.start and instance.stop

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#1690]
## Version of Singularity:

Three files are left in /tmp every time a singularity instance is started and stopped.  The code introducing these files was pr #1039 by @bauerm97.  The files names are of the form
`/tmp/*.{stdout,stderr,singularity-debug}.XXXXXX`
where XXXXXX is a random string of characters.
 
### Expected behavior

/tmp is left clean after a singularity instance is stopped.

### Actual behavior

Files are left behind.

### Steps to reproduce behavior

start an instance and stop it, then look in /tmp for recently modified files.

**Comment by vsoch** [comment]
I would like to +1, and hereby join this issue party! It would be great to have a clean tmp, here is the current aftermath (I posted this on slack)

![image](https://user-images.githubusercontent.com/814322/42130894-b118b48c-7ca7-11e8-83d7-19e1203635ba.png)

instance files should definitely not be having that much fun in my /tmp directory.

**Comment by dtrudg** [comment]
In current singularity you should find that `.out` and `.err` files _only_ are left in your `.singularity/instances` path, e.g.

```
dtrudg@fedora-dev~> find .singularity/instances/ -type f
.singularity/instances/logs/fedora-dev.local/dtrudg/bob.out
.singularity/instances/logs/fedora-dev.local/dtrudg/bob.err
```

**Comment by vsoch** [comment]
Yes this is so much better! Thanks @dctrud.
