### ISSUE TITLE
Allow root-specified privs

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#170]
When running the `sexec_nosuid` binary and launched as root, we should allow the root user to control what UID privileges are dropped to.

For reasonable protections:
- Root should not be able to specify a UID/GID less than 500.
- This particular piece of code should be compiled out of `sexec`.

**Comment by bbockelm** [comment]
Implemented in #172

**Comment by gmkurtzer** [comment]
This has been merged, can it be closed?

Thank you!

**Comment by bbockelm** [comment]
Yup!  Closing!
