### ISSUE TITLE
instance.list returns error code 1

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#1706]
## Version of Singularity:

`2.5.0-feature-squashbuild-secbuild-2.5.0.gabe9005`
(this is @cclerget branch, I believe with 2.5 release and secure build added)

### Expected behavior
Listing instances, even if there aren't any, returns an error code of 0.

```
vanessa@vanessa-ThinkPad-T460s:~$ singularity instance.list
DAEMON NAME      PID      CONTAINER IMAGE
vanessa@vanessa-ThinkPad-T460s:~$ echo $?
0
```

### Actual behavior
It returns an error code of 1

```bash
vanessa@vanessa-ThinkPad-T460s:~$ singularity instance.list
DAEMON NAME      PID      CONTAINER IMAGE
vanessa@vanessa-ThinkPad-T460s:~$ echo $?
1
```

### Steps to reproduce behavior

```bash
singularity instance.list
```
If return code 1 is a [catchall for general errors](http://tldp.org/LDP/abs/html/exitcodes.html) does this mean that listing instances, when there are none, is an error?

**Comment by jmstover** [comment]
Hi @vsoch ,

  I think this was done for scripting... So, in a script you can do:  `singularity instance.list` ... and if there are no running containers, you have a return of 1.  So, you can do: 

```
if [ $(singularity -q instance.list) ]; then
   [ do stuff with running instances ]
fi
```

So, when there is *no* running containers, you exit with a non-zero return code.

**Comment by vsoch** [comment]
Ah, understood. It doesn't seem intuitive to me though, because I'd expect the exit code to indicate if the command succeeded or not (0 for yes, 1 for no). I'm creating a client (wrapper) and it threw me off to have a non-zero return code given that the command ran successfully. Intuitively if I wanted to check for instances running I would do something that directly states (via the code) that I am listing, and counting the list, like:

```
# First line is header, one line indicates no instances
if [ "$(singularity instance.list | wc -l)" -gt "1" ]; then
       echo "We have instances";
fi
```

Is there a way to untangle these two things? I would like to be able to list instances and have certainty that the exit code reflects the command running successful (or not), a separate thing from if there are instances or not. Thank you!

**Comment by jmstover** [comment]
In your fork, you can just remove/comment out the last 3 lines of:
`$prefix/libexec/singularity/cli/instance.list.exec`

That will change it so it's going to always exit with a 0, unless there's an actual runtime error.

**Comment by vsoch** [comment]
I don't understand, you want me to change a single instance (my local install) to address this issue? This only fixes it for a small amount of time when I'm developing with that exact fie, and would mean the error propagate for all future installs, or anyone that uses the tool I'm making. The point for discussion is that Running a command that exits without an error should not return an error.

**Comment by jmstover** [comment]
No... a 1 isn't an error. It's the output of the command. The return code values on this are:

```
Return Code  --   Reason
0 -- Instances Found
1 -- No Instances, libexecdir value not found, functions file not found
255 -- Couldn't get UID
```
It's easier in your code if you do:
```
if $(singularity -q instance.list); then
       echo "We have instances";
fi
```

That will do the same thing you're trying to do, and fail if there aren't any running. No changes needed.

**Comment by vsoch** [comment]
Ah I see, so you are saying that Singularity error codes don't coincide with bash / linux error codes?

**Comment by jmstover** [comment]
They do in a way. They're used to give information. Think of it this way especially when looking at scripting:

`singularity instance.list` -- with no running instances having the same exit code as if there _were_ running instances (i.e. exiting with 0), wouldn't be useful when scripting. There's no way do differentiate just on the _execution_ without looking at the _output_ of the command.

So, if there aren't any instances, it isn't an "error," but it exits in a way that we can use that exit code as a conditional branch check, and ignore blocks of code if there's no reason to go into them w/o needing to parse output.

**Comment by vsoch** [comment]
Yeah that makes total sense! Okey doke, if this is consistent I can just adjust my client to expect these codes (and I've added them to the function header too, for when some future developer might wonder).

```python
> from spython.main import Client
> Client.instances()
No instances found.
```

Thank you for the explanation @jmstover ! Closing issue.

**Comment by vsoch** [comment]
hey, sorry re-opening with more testing! I'm creating instances, and finding that the exit code returns 0 (success) and I see the mount done (this is what happens on ubuntu with containers mounting):

![image](https://user-images.githubusercontent.com/814322/42113889-d8ab9b1a-7ba1-11e8-88fa-d6fb5bc065ea.png)

```bash
$ singularity instance.start spython/ubuntu.simg creamy-pastry-0748

# command started instance successfully
$ echo $?
0

# I should see it exists now, but I'm not sure what this indicates.
$ singularity instance.list
DAEMON NAME      PID      CONTAINER IMAGE
WARNING: Removing stale daemon file: /home/vanessa/.singularity/daemon/vanessa-ThinkPad-T460s/creamy-pastry-0748
```

It seems to do like:

 - create instance is successful, so the return code is 0, and I see the mount created
 - asking to list the instances removes a "stale" file and then returns 1 (no instances)
 - but the mounts are still there, and (I think?) I have instances?

What I'm trying to do is:

 1. create an instance
 2. list and see that it exists

With a little testing, I think this might be an issue of not putting the name in quotes? The name I used above has `-` and for example, doing a name without any works ok:

```bash
$ singularity instance.start spython/ubuntu.simg creamy
$ singularity instance.list
DAEMON NAME      PID      CONTAINER IMAGE
creamy           30859    /home/vanessa/Documents/Dropbox/Code/sregistry/singularity-cli/spython/ubuntu.simg
```
Houston, we have creamy! But I really wanted creamy-pastry-0748 :)

Again, for my client I can expect this and add additional wrapping to the command, but likely someone will run into this on the command line.

Thanks for the pointers again!

**Comment by dtrudg** [comment]
See https://github.com/singularityware/singularity/issues/1289 - can you hop on that issue, and we'll close this one, as 1289 is more specific? Cheers.

**Comment by vsoch** [comment]
you got it! Closing.
