### ISSUE TITLE
singularity --contain without --net stops sharing /etc/hosts

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#1707]
## Version of Singularity:

2.5.1

### Expected behavior

Without using --net, I expect /etc/hosts to be mapped into the container because the network is shared with the host.

### Actual behavior

Since /etc/hosts is only listed as a bind path in singularity.conf, and those are ignored with --contain (#1212), then /etc/hosts is not bind mounted into the container when --contain is used.

### Steps to reproduce behavior

Start singularity with --contain and look at /etc/hosts.

A workaround is to set the environment variable SINGULARITY_BINDPATH=/etc/hosts, but that shouldn't be necessary.

**Comment by jscook2345** [comment]
@DrDaveD 

This still looks like it is an issue. How would you like to proceed on this?

**Comment by DrDaveD** [comment]
Yes in fact I had forgotten about it but just ran into another case this week where it caused a problem.  We're changing our default invocation scripts to always add binding /etc/hosts and /etc/localtime, the two that are configured by default in /etc/singularity.conf and disabled by the --contain option.

I think it's probably too late to change the behavior of ignoring the bind paths in /etc/singularity/singularity.conf with --contain.  On the other hand I now see that #1212, which documented this behavior, did not get ported forward to singularity-3.  Still, I think it would be best to go ahead and document it in singularity-3, and to change the default behavior to always add in bindings of /etc/hosts, /etc/localtime, and probably /etc/nsswitch.conf, as long as nothing else has requested binding to those points (including --net).  What do you think?  The default behavior already brings in other system-related files such as /etc/resolv.conf.

**Comment by jscook2345** [comment]
Ping @cclerget @ikaneshiro @bauerm97

**Comment by robermorales** [comment]
Hey all,

Setting that ENV vars causes singularity to output a warning.

Do we know the exact versions of singularity that needs the workaround? So we can put the env var if (and only if) the singularity version executed is affected by the bug?

Thanks in advance!!

**Comment by DrDaveD** [comment]
@robermorales What warning, and with what singularity version and combination of command line options?  I don't see a warning.

**Comment by robermorales** [comment]
@DrDaveD , including the ENV var in singularity versions that are not affected by the bug outputs

```WARNING: Not mounting requested bind point (already mounted in container): /etc/hosts```

I couldn't get that warning including ```-B /etc/hosts``` so it is not important anymore.

Thanks anyway.
