### ISSUE TITLE
instance.list output json

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#1708]
It would be a good feature (and consistent with other inspection commands) to allow for the user to ask for json output with instance.list, in the case that the call is being done from another language or webby place (and it's not intended for just casual viewing on the command line). If this isn't ideal for instances.list, then another suggestion would be to create an equivalent inspection command for instances. For example, I'm parsing the output to get this functionality:

```python
self._parse_table(instances[0], header=['daemon_name','pid','container_image'])
[{'container_image': '/home/vanessa/Documents/Dropbox/Code/sregistry/singularity-cli/spython/ubuntu.simg',
  'daemon_name': 'creamy',
  'pid': '30859'},
 {'container_image': '/home/vanessa/Documents/Dropbox/Code/sregistry/singularity-cli/spython/ubuntu.simg',
  'daemon_name': 'tart_hippo_4068',
  'pid': '1743'}]
```

But maybe the user might want to do something like:

```bash
singularity instance.list --json > instances.json
```
What do you think?

**Comment by GodloveD** [comment]
I agree.  This sounds like a very reasonable option to add.

**Comment by vsoch** [comment]
Many thanks!

**Comment by dtrudg** [comment]
Closing this - it is present and documented:

https://sylabs.io/guides/3.4/user-guide/cli/singularity_instance_list.html
