### ISSUE TITLE
instance.start return code

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#1709]
In spirit of the case that `instance.list` returns a 1 to be programatically accessible to scripts (and does not reflect the successful return of the command) I would expect the `singularity instance.start` command to also return a value that is meaningful for a script. My first expectation was returning the pid.  Currently, the return value is 0:

```bash
$ singularity instance.start ubuntu.simg hakuna_matata
$ echo $?
0
```
And the script would then have to iterate through the listing of containers, parse the text output, and figure out the pid based on a matching name. Is there a better / any easy way to do this? Just curious, why is the standard different between the two? As a suggestion, why not do like a bunch of programs do, and at least print the pid of the started container to the stdout? That way, we could use the return code of 0 to say "successfully started!" and then easily have a handle to the beastie thing we have unleahsed. Let me know what you would suggest as a workaround, in the meantime!

**Comment by jscook2345** [comment]
@vsoch 

This is the current behavior:

```
[vagrant@localhost ~]$ singularity instance start c7.sif c
INFO:    instance started successfully
[vagrant@localhost ~]$ echo $?
0
```

Which seems to still be at odds with your suggestion. How would you like to proceed?

**Comment by vsoch** [comment]
I think I stated clearly the issue - if the user is starting instances, the return value doesn't provide a handle to control the pid. I could do:

```bash
$ singularity instance start busybox_latest.sif henry
INFO:    instance started successfully
$ echo $!
32606
```
But if there are several things being created at once, who knows if I'll grab the right pid quickly enough. There needs to be some way to accurately grab the process id for the instances. For example, when I open up my editor (detached) it doesn't tell me 0 for success, but rather the pid:

```bash
$ gedit &
[2] 10084
```
This is the issue that I am expressing.

**Comment by vsoch** [comment]
Here is another way to think about it. If we cannot get the pid easily after creation, there also isn't an easy programmatic way to request a pid based on an instance name that doesn't require a lot of painful parsing. For example, here I can list instances:

```
$ singularity instance list
INSTANCE NAME    PID      IMAGE
henry            9975     /tmp/busybox_latest.sif
marta            10200    /tmp/busybox_latest.sif
```

But I can't ask for any one, special:

```bash
$ singularity instance list marta
INSTANCE NAME    PID      IMAGE
henry            9975     /tmp/busybox_latest.sif
marta            10200    /tmp/busybox_latest.sif
```
I could try grabbing the json, but then I'd have to parse over the list (with some client) looking for "marta"

```bash
$ singularity instance list --json
{
	"instances": [
		{
			"instance": "henry",
			"pid": 9975,
			"img": "/tmp/busybox_latest.sif"
		},
		{
			"instance": "marta",
			"pid": 10200,
			"img": "/tmp/busybox_latest.sif"
		}
	]
}
```
If I use jq, I can get the pids of all instances (but I still don't know who is marta!)
```bash
$ singularity instance list --json | jq --raw-output .instances[].pid
9975
10200
```
So - there needs to be some way to either:
  - get the pid directly after creation as a return value, akin to gedit example or
  - allow for asking for a specific instance by name with the list command, and filter down to a variable of interest.

**Comment by jscook2345** [comment]
@bauerm97 @GodloveD 

Would this be something to add for 3.3? Please reassign / relabel as needed!

**Comment by vsoch** [comment]
That would be awesome! I’m happy to help test as needed.

**Comment by GodloveD** [comment]
Just looking over some older issues and I saw this.  The following works right?

```
$ singularity instance list | grep -w blah | awk '{print $2}'
```

I'm not sure how portable it is since it relies on `awk` being installed and maybe some non-posixness in `grep`.  How would it be if there were an option to `instance start`?  Maybe something like this?
```
$ singularity instance start --show-pid foo bar
INFO:    instance started successfully
123
 ```

**Comment by vsoch** [comment]
It would be intuitive to allow the user to add an instance name to the "list" command, akin to how an api endpoint can add a /<number> and then get a particular instance. For example, here is a pretend api endpoint:

```
# list all containers
localhost:4000/containers

# List container with id 12
localhost:4000/containers/12
```
Since the user will know the instance name, it would make sense to provide metadata with something like:

```
$ singularity instance list marta
marta            10200    /tmp/busybox_latest.sif
```
That would probably suffice for most users, and then for programs, you could add json (as shown above)

```
$ singularity instance list marta --json
{
	"instances": [
		{
			"instance": "marta",
			"pid": 10200,
			"img": "/tmp/busybox_latest.sif"
		}
	]
}
```
But the above (adding a name to list) isn't super optimal, because the interaction that I'd want to have is to inspect (and leave list as is):

```
$ singularity instance inspect marta --json
{
	"instance": "marta",
	"pid": 10200,
	"img": "/tmp/busybox_latest.sif"
}
```
```
$ singularity instance inspect marta
marta            10200    /tmp/busybox_latest.sif
```

The format / structure of the metadata can be up to you, along with if you would allow the user to select some specific value to get (because using jq is hard)

```
$ singularity instance inspect marta pid
10200
```
I'll leave the details up to you guys! But strong support from me for either a specific listing, or a customized inspect for an instance. The criteria for goodness are how intuitive it is to use / figure out, and how clean / modular it is to develop the functionality into the current structure (optimizing for potential future changes / extensions). Thanks @GodloveD !

**Comment by sashayakovtseva** [comment]
Will add an optional `name` argument to `singularity instance list`.

**Comment by vsoch** [comment]
Great! Ping me if you’d like someone to test when it’s ready.
