### ISSUE TITLE
change the location of the value `/.singularity.d/libs/`  in  LD_LIBRARY_PATH  

### ISSUE THREAD

**Issue by supermanhuyu** [apptainer/singularity#1714]
## Version of Singularity: 

Singularity version: 2.4.2-dist

### Expected behavior

```
~> nvidia-smi 
Mon Jul  2 16:04:37 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:85:00.0 Off |                  N/A |
| 29%   24C    P8    14W / 250W |  10657MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     14916      C   /usr/bin/python3                           10647MiB |
+-----------------------------------------------------------------------------+

```

### Actual behavior

```
~> nvidia-smi
Failed to initialize NVML: Driver/library version mismatch
```

### Steps to reproduce behavior

Write here.

i have install nvidia-driver (the same version with my system nvidia driver )in my old singularity image, and i do not want to change my image after change my system nvidia driver version . so i use option `--nv `
but i get the Driver/library version mismatch.
and if i change my `PATH`  and  `LD_LIBRARY_PATH`  to delete my old nvidia driver path , it works .
so i hope someone developer can add the value  `/.singularity.d/libs/`  to the first location 
of LD_LIBRARY_PATH in the file `/.singularity.d/env/99-base.sh`  instead of in the end .
thank you

**Comment by mbarbry** [comment]
Hi,

I'm getting the same issue with version `2.4.5-master.gde77554`. I build a new container with cuda

    apt-get install linux-headers-$(uname -r)
    wget developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.1.85-1_amd64.deb -P /opt
    dpkg -i /opt/cuda-repo-ubuntu1604_9.1.85-1_amd64.deb
    apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
    apt-get update && apt-get -y install nvidia-modprobe cuda

Then
    
    ~>  nvidia-smi
    Failed to initialize NVML: Driver/library version mismatch

Could you describe wit more details the process that you did to overcome this issue?
Do I need to change the `PATH` from the host or the container?

Thanks

**Comment by supermanhuyu** [comment]
@mbarbry 
you need to change `PATH` and `LD_LIBRARY_PATH`  in the container . because it contains the path of your old nvidia .
like this 
```
~> env
LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/NVIDIA-Linux-x86_64-375.39::/.singularity.d/libs
PATH=/usr/local/NVIDIA-Linux-x86_64-375.39:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
```
change it to 
```
LD_LIBRARY_PATH=/usr/local/cuda/lib64:/.singularity.d/libs
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
```
and you have to change it everytime when you run you container.

so the best way is change your image's environment and rebuild it .
