### ISSUE TITLE
Update Travis-CI tests to cover new features:

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#173]
- [x] Chroot to directory instead of an image.
- [x] No-setuid / unprivileged mode.
- [ ] Updated signal handling.
- [ ] Exit statuses on external signals.
- [x] Target mode (once merged).
- [x] Scratch directories.
- [x] User bind mounts.
- [ ] Slave mounts.
- [x] No new privs.
- [x] Disable `setuid` binary via configuration file.

**Comment by gmkurtzer** [comment]
Can we close this? I think (even the unchecked) items are mostly in there, granted they may not be in the test.sh... I'm not sure if they all can be (e.g. slaves)?

**Comment by bbockelm** [comment]
Yup - I think we can reopen for the next set of tests.

**Comment by gmkurtzer** [comment]
Thanks!
