### ISSUE TITLE
Arch Linux bootstrap support broken

### ISSUE THREAD

**Issue by mherzberg** [apptainer/singularity#1731]
## Version of Singularity:

2.5.1

### Expected behavior

A simple deffile using the Arch Linux bootstrap builds without problems.

### Actual behavior

A simple deffile using the Arch Linux bootstrap fails with a 404 Error when trying to download the following file: [https://git.archlinux.org/svntogit/packages.git/plain/trunk/pacman.conf.x86_64?h=packages/pacman](https://git.archlinux.org/svntogit/packages.git/plain/trunk/pacman.conf.x86_64?h=packages/pacman)

### Steps to reproduce behavior

Execute `sudo singularity build test.img test.def`, where `test.def` contains just `Bootstrap: arch`.

It seems Arch Linux renamed the file and dropped the architecture suffix: [https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/pacman&id=441f836137ce8666bf42ad2e554a89362a8054e6](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/pacman&id=441f836137ce8666bf42ad2e554a89362a8054e6). Therefore, the fix seems simple; change the used URL to [https://git.archlinux.org/svntogit/packages.git/plain/trunk/pacman.conf?h=packages/pacman](https://git.archlinux.org/svntogit/packages.git/plain/trunk/pacman.conf?h=packages/pacman)

**Comment by GodloveD** [comment]
I'm able to replicate this.  Do you want to base a PR on development-2.x?
