### ISSUE TITLE
More informative error when the path doesn't point to a valid image

### ISSUE THREAD

**Issue by Shotgunosine** [apptainer/singularity#1734]
## Version of Singularity:

2.5.2-master.b258b65

### Expected behavior

This is a boneheaded mistake on my part, I had written down my singularity command in a text editor window and was copy pasting in the new image name as I iterated through changes and build new containers with docker2singularity. Well on one of my copy pasts a space snuck in to the path to the singularity image thus rendering the path I was trying to run invalid. I spent longer than I'd like to admit debugging my image before I realized the path was the issue. It would be nice if the error message in this case included the path that you tried to run, or warned you that you had specified a directory instead of an image something like this:
```
ERROR  : No image found at path provided, /home/nielsond/
ABORT  : Retval = 255
```

### Actual behavior

When you try to singularity run an invalid path you get the message:

```
ERROR  : No valid /bin/sh in container
ABORT  : Retval = 255
```

Googling for that error takes you to lots of threads about umasks and outdated versions of singularity, but none of them mentions that you might just have a bad path. Again, I know this is my own stupidity, but tweaking this error message could help save other people who make a similar stupid mistake.

### Steps to reproduce behavior
```
singularity pull shub://GodloveD/lolcow
singularity run ~/ GodloveD-lolcow-master-latest.simg
ERROR  : No valid /bin/sh in container
ABORT  : Retval = 255
```

**Comment by ChrisDowning** [comment]
Just observed a similar issue (using 2.5.1-dist); when using a mis-typed definition file, eg:
```
ootstrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum
```
(note the missing "b" in bootstrap on the first line)

Trying to generate this starting image using
```
sudo env "PATH=$PATH" singularity build centos.simg centos.def
```

returns the same misleading error as the original post, i.e: 
```
ERROR: Could not locate /bin/sh inside the container
Cleaning up...
```

**Comment by dtrudg** [comment]
At this point (3.7) an image doesn't even have to have a shell, and can be as little as a directory containing a runscript and a static binary. The error when pointing to an empty directory will be:

```
11:44 AM $ singularity run abc/
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
ERROR:   No runscript and no /bin/sh executable found in container, aborting
```

Given the large variety of what an image can be, and that people can construct minimal directories that contain just a runscript, I'm not sure we should adjust this. If we say "No image found" that does not hint at the ultimate cause for people constructing minimal containers.
