### ISSUE TITLE
Citing Singularity

### ISSUE THREAD

**Issue by efajardo** [apptainer/singularity#1739]
Dear Singularity Developers:

At CHEP there was a nice [talk](https://indico.cern.ch/event/587955/contributions/3012261/attachments/1683270/2706352/Katz_2018.07.09_software_citations_CHEP.pdf) following another one at ACAT about software citation. 

Long story short is that the “recommended” way to do software citation is no longer just citing the software paper but with DOI. Since people will start writing CHEP proceedings really soon and they will be LOTS of people trying to cite Singularity,

What are your thoughts on getting a DOI on the short term?

**Comment by GodloveD** [comment]
This sounds great.  Just trying to figure out how to do it.  In particular is it possible to get DOI numbers on already issued releases?

**Comment by efajardo** [comment]
Yes, I think so since according to [this](https://guides.github.com/activities/citable-code/) you get the DOI for the repository and then people cite versions. It would be great if at some moment also a Journal of Open Source Software submission could be done.

**Comment by GodloveD** [comment]
Looks like @dctrud set it all up!  Thanks @dctrud and thanks @efajardo for pointing this out. 

https://doi.org/10.5281/zenodo.1308868

**Comment by dtrudg** [comment]
Hi @efajardo - our README.md has a DOI link in toward the bottom, but it's a bit old. I've just created one for the latest 2.5.2 release, and setup Zenodo to created them for new releases automatically.

https://doi.org/10.5281/zenodo.1308868

**Comment by efajardo** [comment]
Awesome those are great news. Let me know if at some moment you think about submitting a paper to http://joss.theoj.org/

**Comment by efajardo** [comment]
@GodloveD only one thing missing would be to create a CITATION file to tell people how to cite.

**Comment by GodloveD** [comment]
That's a great idea. Would you care to take a stab and create a PR?

**Comment by efajardo** [comment]
@GodloveD here it is [PR-71](https://github.com/singularityware/singularity/pull/1771). Sorry it took a while with all the traveling

**Comment by dtrudg** [comment]
We didn't have anything further on PR-71 - but I've submitted #1739 to get the zenodo link to the 'all versions' DOI.
