### ISSUE TITLE
"No such file or directory, returning None" upon pull due to missing  /var/tmp/singularity/libexec/bin/image-type

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#1741]
## Version of Singularity:

2.5.2, from Debian

### Expected behavior

no error messages

### Actual behavior

```shell
$> singularity --debug pull shub://truatpasteurdotfr/singularity-alpine     
...
DEBUG Pulling to /home/yoh/truatpasteurdotfr-singularity-alpine-master-latest
DEBUG GET (stream) https://www.googleapis.com/download/storage/v1/b/singularityhub/o/singularityhub%2Fgithub.com%2Ftruatpasteurdotfr%2Fsingularity-alpine%2F12c84e093194d895ff2dbf4fb9257e2926bbf1d7%2Fbc6bb8a73d483b47ea07c94081e40d49%2Fbc6bb8a73d483b47ea07c94081e40d49.simg?generation=1510516653761593&alt=media
Progress |===================================| 100.0% 
ERROR Error with subprocess: [Errno 2] No such file or directory, returning None
DEBUG Found None image
DEBUG Writing Singularity Hub image path to /home/yoh/.tmp/.singularity-layerfile.B3xpdz
VERBOSE2 Writing file /home/yoh/.tmp/.singularity-layerfile.B3xpdz with mode w.
Done. Container is at: /home/yoh/truatpasteurdotfr-singularity-alpine-master-latest.simg
```

strace helped to identify it (I hope correctly, since "Error with subprocess" error msg doesn't provide any context):

```
4794  execve("/var/tmp/singularity/libexec/bin/image-type", ["/var/tmp/singularity/libexec/bin/image-type", "/home/yoh/truatpasteurdotfr-singularity-alpine-master-latest"], 0x55bdff2a4710 /* 109 vars */) = -1 ENOENT (No such file or directory)
```
and I have no `/var/tmp/singularity/libexec/bin/` whatsoever:
```shell
$> tree /var/tmp/singularity/libexec/
/var/tmp/singularity/libexec/
├── bootstrap-scripts
├── cli
├── helpers
└── python
    ├── base.py
    ├── base.pyc
    ├── defaults.py
    ├── defaults.pyc
    ├── docker
    │   ├── api.py
    │   ├── __init__.py
    │   ├── main.py
    │   └── tasks.py
    ├── helpers
    │   ├── __init__.py
...
```

**Comment by jmstover** [comment]
@yarikoptic 
Hrmm....  It looks like when built that `--libexecdir=/var/tmp` was used. Do you have anything under: `/usr/lib/x86_64-linux-gnu/singularity`

*Edit:*
No... that's wrong. The only way I think you could have got this to happen is by setting `--exec-prefix=/var/tmp/singularity/`

By *default* we in the `singularity` script set `SINGULARITY_libexecdir=${exec_prefix}/libexec` ... and `${exec_prefix}` defaults to `${prefix}` ... which is usually `/usr`, or similar.

*But*, you _can_ specify a `exec-prefix` *and* `libexecdir` ... which is going to short circuit this. I'm actually not sure how you got an install the way you did... The Makefile's should be installing to:  `$(libexecdir)/singularity/` ... which would not match the path you have.

**Comment by yarikoptic** [comment]
sure thing:
```
$> ls /usr/lib/x86_64-linux-gnu/singularity
bin/                helpers/                  libsingularity-image.so.1@     libsingularity-runtime.so.1@
bootstrap-scripts/  image-handler.sh*         libsingularity-image.so.1.0.0  libsingularity-runtime.so.1.0.0
cli/                libsingularity-image.a    libsingularity-runtime.a       python@
functions*          libsingularity-image.la   libsingularity-runtime.la      python_/
handlers/           libsingularity-image.so@  libsingularity-runtime.so@
```
I do not see any explicit reference to var/tmp in https://buildd.debian.org/status/fetch.php?pkg=singularity-container&arch=amd64&ver=2.5.2-1&stamp=1530733247&raw=0

**Comment by jmstover** [comment]
@yarikoptic 
Can you look in the `singularity` (`which singularity`) script and tell me what the values for the variables at the top are? i.e.  `prefix` through `SINGULARITY_bindir`

**Comment by yarikoptic** [comment]
Seems to be all kosher there:
```
$> grep -B15 SINGULARITY_bindir= /usr/bin/singularity 
# Relax restrictive umasks that can cause several problems
umask 0022

prefix="/usr"
exec_prefix="${prefix}"
libexecdir="${prefix}/lib/x86_64-linux-gnu"
sysconfdir="/etc"
localstatedir="/var/lib"
bindir="${exec_prefix}/bin"
home=`dirname  "$0"`

SINGULARITY_version="2.5.2-dist"
SINGULARITY_libexecdir="$libexecdir"
SINGULARITY_sysconfdir="$sysconfdir"
SINGULARITY_localstatedir="$localstatedir"
SINGULARITY_bindir="$bindir"
```

**Comment by jmstover** [comment]
Yeah... that all looks sane. So with that `singularity` file the error you should have gotten would have had the path:

`/usr/lib/x86_64-linux-gnu/singularity/bin/image-type`

It appears as if that specific error comes from the python code. Do you have `PYTHONPATH` set, or another environment variable that's pointing at the `/var/tmp` location?  The python code is doing:

```
here = os.path.abspath(os.path.dirname(__file__))
sbin = here.replace("python", "bin/image-type")
[...]
```

So, the `os.path.abspath()` is getting the `/var/tmp/singularity/libexec/python` directory. Then with `here.replace()` that's changing it to `/var/tmp/singularity/libexec/bin/image-type` ... which doesn't exist.

**Comment by yarikoptic** [comment]
eh, we (python folks) always scream that `__file__` is evil and then keep using it since there is nothing better ;-)  clearly it is something about my system -- I didn't reproduce it in a clean docker env, but it is not PYTHONPATH or tainted python execution - all kosher there... ok - let's "debug":

```shell
$> singularity pull shub://truatpasteurdotfr/singularity-alpine       
Progress |===================================| 100.0% 
> /var/tmp/singularity/libexec/python/sutils.py(252)get_image_format()
-> sbin = here.replace("python", "bin/image-type")
(Pdb) p here
'/var/tmp/singularity/libexec/python'
*(Pdb) print os.environ['PATH']
/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
(Pdb) print sys.executable
/usr/bin/python
(Pdb) os.getcwd()
'/tmp'
```
```
> diff /usr/lib/x86_64-linux-gnu/singularity/python/sutils.py /var/tmp/singularity/libexec/python/sutils.py
$> ls -ld /usr/lib/x86_64-linux-gnu/singularity/python*
lrwxrwxrwx 1 root root   35 Apr 30 15:04 /usr/lib/x86_64-linux-gnu/singularity/python -> /var/tmp/singularity/libexec/python/
drwxr-xr-x 5 root root 4096 Apr 30 14:52 /usr/lib/x86_64-linux-gnu/singularity/python_/

```
arghm!!!! I wonder if I was troubleshooting something at some point in the past and then did this!

Very much sorry for troubling you and thanks for tolerating my whining @jmstover . 
I've wiped, reinstalled -- no error message

**Comment by jmstover** [comment]
Sounds good. If there was any symlinks was going to be by next ask if nothing showed up. ;)
