### ISSUE TITLE
Minimum system privileges for building singularity recipes?

### ISSUE THREAD

**Issue by csbrown** [apptainer/singularity#1749]
## Version of Singularity: latest

[The docs](http://singularity.lbl.gov/faq#do-you-need-administrator-privileges-to-use-singularity) claim that it is necessary for a user to have admin access in order to build a container from a recipe.  However, the user need not be able to, as an off-the-cuff example, write to arbitrary users' home folders.  As a work-around to the root-privileges thing, one might put a user in sudoers for just the one command.  For example, I could make a shell script `sbuild.sh` that does `singularity build`, and add a line:

```
username ALL = NOPASSWD : /usr/bin/sbuild.sh
```

To the sudoers file.  However, I am not sure what the implications of this would be.  By building a container as sudo, could a user somehow manage to `setuid` root?  Would it be possible to go one further and simply give a user read/write on certain filesystem artifacts to get them to a level where they can build a recipe?

**Comment by dtrudg** [comment]
Hi @csbrown - one reason you probably *don't* want to allow users to `build` an arbitrary recipe file (with root priv) is that there are sections in a recipe file that can affect the host - and would do so as root:

>Commands in the %setup section are executed on the host system outside of the container after the base OS has been installed. 

https://www.sylabs.io/guides/2.5.1/user-guide/container_recipes.html#sections

**Comment by dtrudg** [comment]
Closing this issue. The situation has now changed quite a bit due to the introduction of the `--fakeroot` option where the requirement is that unprivileged creation of user namespaces is enabled, and subuid/subgid mappings are configured.

There is documentation at: https://sylabs.io/guides/3.4/user-guide/fakeroot.html
