### ISSUE TITLE
source a script using exec?

### ISSUE THREAD

**Issue by Xingyu-Lin** [apptainer/singularity#1758]
## Version of Singularity:

2.5.1

### Expected behavior

I try to first activate a conda environment and then run some scripts
singularity exec ubuntu-16.04-lts-rl.img . activate env && python somescripts.py

### Actual behavior

It gives me error at the first command:
/.singularity.d/actions/exec: 9: exec: .: Permission denied

Why does this happend and what is the correct way to do this? I would prefer a way that does not require constructing a new singularity image.

Thanks!

**Comment by Xingyu-Lin** [comment]
Hi, 

One solution I get is to run a bash inside the container and then execute my command, by
```
singularity exec ubuntu-16.04-lts-rl.img /bin/bash '. activate env && python somescripts.py'
```

I wonder if this is the correct way and what is the reason?

**Comment by dtrudg** [comment]
In the `exec` script that is called in the container, singularity does a literal `exec ...` of the command you passed. if you try `exec . myenv` you'll see the same thing.

Using bash as you are is fine for this, but if it's something you do repeatedly you may wish to write a runscript that does the source-ing, and will then run python with a provided argument as the python file to run.
