### ISSUE TITLE
Add ability to specify inode limit in persistent overlay image

### ISSUE THREAD

**Issue by bbarker** [apptainer/singularity#1759]
### Expected behavior

Allow user to specify inode limits with `singularity image.create`, or provide higher default.

### Actual behavior

Currently there is no way to specify inode limits according to `--help`:

```
$ singularity image.create --help
USAGE: singularity [...] image.create [create options...] <container path>
Create a new Singularity formatted blank image.

CREATE OPTIONS:
    -s|--size   Specify a size for an operation in MiB, i.e. 1024*1024B
                (default 768MiB)
    -F|--force  Overwrite an image file if it exists
```

Even though my host OS is only using 14% of the available inodes configured, I'm running out of inodes in my overlay image in Singularity:

```
Singularity> df -i
Filesystem              Inodes      Used Available Use% Mounted on
OverlayFS                49152     49149         3 100% /
OverlayFS                49152     49149         3 100% /
tmpfs                  4107507        46   4107461   0% /dev
````
### Steps to reproduce behavior

Create 50,000 files in a persistent overlay image

### Comments

Is this possible given our knowledge of OverlayFS? So far I haven't been able to find anything.

**Comment by bbarker** [comment]
I believe I can just add an `-N` parameter to the `mkfs.ext3` call at `https://raw.githubusercontent.com/singularityware/singularity/master/libexec/cli/image.create.exec`, and have this passed in if given as an arg to `image.create`.

**Comment by jmstover** [comment]
How... large is that image? A 4G sparse image (193MB usage) that I created has 262144 inodes.

**Comment by bbarker** [comment]
@jmstover It ran out of inodes around 600mb; I just used the default size from `image.create` (no `-s`  parameter given). Here's the output from within the container:

```
Singularity> df -h
Filesystem                Size      Used Available Use% Mounted on
OverlayFS               739.9M    602.9M     98.7M  86% /
OverlayFS               739.9M    602.9M     98.7M  86% /
```

**Comment by jmstover** [comment]
That looks like the right number of inodes based on mke2fs defaults... 

```
$ perl -le 'print 768*1024*1024;'
805306368
$ perl -le 'print 805306368/16384;'
49152
```

mke2fs makes 1 inode/16K ...  Are you storing a bunch of smaller files to where it makes sense to change the bytes-per-inode option? So, instead use something like:  `-i 8192`

Change it so it's 1 inode per 8K?

*Edit:*
You should be able to find your system defaults under:  `/etc/mke2fs.conf`

**Comment by jmstover** [comment]
IMO ... passing the `bytes-per-inode` for the algo is a better fit, than passing a raw: This is how many inodes to make

**Comment by jmstover** [comment]
@bbarker 
Does this look good to you?  If so I'll put up a PR on it and try to get it in the 2.6.0 release  (@GodloveD)

Using a `-i` option to specify the Inode size
```
$ /usr/local/singularity/devtest/bin/singularity image.create -i 8192 test.img
Creating empty 768MiB image file: test.img
Formatting image with ext3 file system
Image is done: test.img
$ sudo mount -oloop test.img /mnt
$ df -i /dev/loop0
Filesystem     Inodes IUsed IFree IUse% Mounted on
/dev/loop0      98304    11 98293    1% /mnt
```

And with just the defaults:
```
$ /usr/local/singularity/devtest/bin/singularity image.create test2.img
Creating empty 768MiB image file: test2.img
Formatting image with ext3 file system
Image is done: test2.img
$ sudo mount -oloop test2.img /mnt
$ df -i /dev/loop0
Filesystem     Inodes IUsed IFree IUse% Mounted on
/dev/loop0      49152    11 49141    1% /mnt
```

**Comment by bbarker** [comment]
@jmstover wow, sorry I didn't reply to this earlier, though maybe I did on slack indirectly. I've been getting the updates on the PR, so hopefully that means I'm not too late. But yes (to reiterate formally), this sounds good to me.
