### ISSUE TITLE
singularity cannot mount container rw for copy over /dev/loop2

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#176]
$ sudo singularity copy src/test_binary images/test-1.2.img /usr/bin/
ERROR  : Failed to mount (rw) '/dev/loop2' at '/usr/local/var/singularity/mnt': Invalid argument

**Comment by gmkurtzer** [comment]
That error typically means the container is corrupt. Can you try another image to see if another one works?

Thank you!

**Comment by moskalenko** [comment]
It looks like a HDD was going bad. Sorry for trouble.

**Comment by gmkurtzer** [comment]
No trouble, thanks for letting me know! Whew!! Lol
