### ISSUE TITLE
guide for 2.5.2 and/or instruction to run ./autogen.sh missing in manual 

### ISSUE THREAD

**Issue by ps-account** [apptainer/singularity#1763]
# issue

When installing 2.5.2, it appears there is no install guide for 2.5.2

When running the " install a specific release" section for 2.5.1 https://www.sylabs.io/guides/2.5.1/user-guide/installation.html#install-a-specific-release

install script misses ./autogen.sh before ./configure

# suggestion

suggestion for install-a-specific release for 2.5.2

```
VER=2.5.2

wget https://github.com/singularityware/singularity/releases/download/$VER/singularity-$VER.tar.gz

tar xvf singularity-$VER.tar.gz

cd singularity-$VER

./autogen.sh

./configure --prefix=/usr/local --sysconfdir=/etc

make

 sudo make install

```
BTW if possible, please remove the $-signs in the code parts!  for easier copy-pasting :D

**Comment by jscook2345** [comment]
I opened https://github.com/sylabs/singularity-userdocs/issues/135 to address this issue.

As far as removing `$` from commands, I don't think that we will able to do that. I discussed it previously for just the reason you mentioned and it had a negative response. If you'd like to follow-up please open a new issue for this and add some points of discussion.

Thanks for the report!
