### ISSUE TITLE
Container execution not dealing with environment modules bash functions

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#177]
Executing singularity containers in an environment set up with an environment modules system (Lmod: https://github.com/TACC/Lmod). results in errors. For example, starting 'R' (https://cran.r-project.org/) from a singularity container after loading paths to singularity and to the image directory via environment modules results in the following errors:

/bin/sh: BASH_FUNC_histgrep(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_histgrep(): line 0:`BASH_FUNC_histgrep() () {  grep --color=auto -r "$@" ~/.history;'
/bin/sh: error importing function definition for `BASH_FUNC_histgrep'
/bin/sh: BASH_FUNC_clearMT(): line 0: syntax error near unexpected token`)'
/bin/sh: BASH_FUNC_clearMT(): line 0: `BASH_FUNC_clearMT() () {  eval $($LMOD_DIR/clearMT_cmd bash)'
/bin/sh: error importing function definition for`BASH_FUNC_clearMT'
/bin/sh: BASH_FUNC_ml(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_ml(): line 0:`BASH_FUNC_ml() () {  eval $($LMOD_DIR/ml_cmd "$@")'
/bin/sh: error importing function definition for `BASH_FUNC_ml'
/bin/bash: BASH_FUNC_ml(): line 0: syntax error near unexpected token`)'
/bin/bash: BASH_FUNC_ml(): line 0: `BASH_FUNC_ml() () {  eval $($LMOD_DIR/ml_cmd "$@")'
/bin/bash: error importing function definition for`BASH_FUNC_ml'
/bin/bash: BASH_FUNC_histgrep(): line 0: syntax error near unexpected token `)'
/bin/bash: BASH_FUNC_histgrep(): line 0:`BASH_FUNC_histgrep() () {  grep --color=auto -r "$@" ~/.history;'
/bin/bash: error importing function definition for `BASH_FUNC_histgrep'
/bin/bash: BASH_FUNC_clearMT(): line 0: syntax error near unexpected token`)'
/bin/bash: BASH_FUNC_clearMT(): line 0: `BASH_FUNC_clearMT() () {  eval $($LMOD_DIR/clearMT_cmd bash)'
/bin/bash: error importing function definition for`BASH_FUNC_clearMT'

All of the above errors seem to be due to an issue with bash functions exported by Lmod EMS. Outside of the container the functions are set up by sourcing a system-wide /etc/profies.d/modules.sh script and the subsequently called code.

**Comment by gmkurtzer** [comment]
What is the command you used? (singularity shell.., or is this with exec, and run as well)? What version of Singularity is this?

Lastly, can you send me the singularity --debug output of this command as well.

Thank you!

**Comment by moskalenko** [comment]
Hi,

This was an exec command. Singularity-2.1. The only application inside the ubuntu image is R (r-base) with a few custom packages.

**Comment by gmkurtzer** [comment]
Do you have lmod installed on the host or in the container?

**Comment by moskalenko** [comment]
On the host

**Comment by moskalenko** [comment]
Outside of a container:

declare -F
declare -f _ml
declare -f _module
declare -f _module_avail
declare -f _module_loaded_modules
declare -f _module_loaded_modules_negated
declare -f _module_long_arg_list
declare -f _module_not_yet_loaded
declare -f _module_savelist
declare -f _module_spider
declare -f clearMT
declare -f ml
declare -fx module

Inside a container declare doesn't show any items.

**Comment by gmkurtzer** [comment]
What happens if you delete the module, ml and possibly some of the other functions "unset -f ..." in the /etc/singularity/init file?

**Comment by gmkurtzer** [comment]
(BTW, I put this as an enhancement instead of a bug because it isn't specifically a Singularity bug, it has to do with incompatibilities with the host and container environments)

**Comment by moskalenko** [comment]
I've unset them, but it didn't help. From what I could determine the bash version in Ubuntu is newer and is using a different function definition format from older bash, which is what Lmod conforms to. This is a larger problem because I'd prefer to have a 'hybrid' approach i.e. say rstudio is run from a container, but user R from a share install we have in a directory I bind-mount with singularity, so we wouldn't have to reinstall all the R packages we already installed on the cluster.

**Comment by gmkurtzer** [comment]
Oh, I am concerned if it is an issue between bash versions and how it handles exported functions.

In theory I understand what you are getting at with regards to the shared directory on the host, but... I caution against this for reasons of binary compatibility between host and container.

**Comment by moskalenko** [comment]
Unsetting all offending bash functions in the user's environment before the singularity exec command is run removes the warnings. We have use cases when it would be advantageous to piggy-back on the applications already installed in our shared environment. In that case those environment modules functions would be useful to have. We can close this as 'later' I guess.

**Comment by gmkurtzer** [comment]
I like the idea of closing this as "later", but for when it does come up again, I'm not sure how to deal with it programmatically from Singularity. This may need to end up as a wrapper or something else that is environment/container specific.

Thanks!
