### ISSUE TITLE
How to reverse the direction of binding? --> Bind a directory in the container to host

### ISSUE THREAD

**Issue by Amir-Arsalan** [apptainer/singularity#1789]
Based on the documentation, it seems that it is only possible to bind a directory on host to a directory in the container. I wonder, is the reverse possible as well? If so, can someone explain how I can do that?

For example, I want to install some dependencies in my container and I want to run an application on my laptop (VS Code) to read the list of packages/dependencies from that directory (which is mounted to the host) instead/in addition to the dependencies on my laptop.

**Comment by cclerget** [comment]
Hi @Amir-Arsalan , that's not possible. A possible way to do what you want is to run `singularity mount yourimage`, then you will have a shell where you could run VS Code and access packages/dependencies in `/usr/local/var/singularity/mnt/final/`, this path may be different depending of your Singularity install, when executing `singularity mount` you will see a line `yourimage is mounted at: ...`, follow this path to access packages and dependencies
