### ISSUE TITLE
Change to /environment broke the path

### ISSUE THREAD

**Issue by nl384** [apptainer/singularity#179]
Hi Greg,

When you changed the location of the /environment file to earlier in the code, I think it ended up having the unintended consequence of actually messing up the PATH variable. Now when the /environment file is created in the new image, instead of the file saying "PATH=$PATH:/bin:/sbin", the file instead says "PATH=/bin:/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/bin:/sbin" . I think something weird is happening with the $PATH, but it is a bit strange because it seemed like you simply copy and pasted. 

Best,
Nathan

**Comment by gmkurtzer** [comment]
Can you double check? This is what I'm getting...

```
Singularity.Test1.img> cat /environment 
# Define any environment init code here
# 

if test -z "$SINGULARITY_INIT"; then
    PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    PS1="Singularity.$SINGULARITY_CONTAINER> $PS1"
    SINGULARITY_INIT=1
    export PATH PS1 SINGULARITY_INIT
fi
```

Thanks!

**Comment by nl384** [comment]
I created two images, and got similar results. I'll check again right now though.

**Comment by gmkurtzer** [comment]
Can you show me your entire /environment file in a newly created/bootstrapped container?

Thanks!

**Comment by nl384** [comment]
Well I'm currently building it again, but I'll definitely post it when it finishes in 5-10 minutes!

**Comment by gmkurtzer** [comment]
as a shortcut, you could remove /environment from an existing container and then run bootstrap against it with no definition file:

```
$ sudo singularity exec -w container.img rm -f /environment
$ sudo singularity bootstrap container.img
```

**Comment by nl384** [comment]
Sorry for taking so long, I accidentally messed up your instructions for speeding up the process. Anyways, here is the /environment file for my newly created test container:

```
$ singularity exec ubuntu.img cat /environment
'# Define any environment init code here
# 

if test -z "$SINGULARITY_INIT"; then
    PATH=/bin:/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/bin:/sbin
    PS1="Singularity.$SINGULARITY_CONTAINER> $PS1"
    SINGULARITY_INIT=1
    export PATH PS1 SINGULARITY_INIT
fi
```

**Comment by gmkurtzer** [comment]
No worries... Hrmm.. That is really odd. Can you show me what is in the linux_build.smod:

```
$ grep PATH /usr/libexec/singularity/mods/linux_build.smod
```

(or where ever it was installed to)

**Comment by nl384** [comment]
```
$ grep PATH /usr/libexec/singularity/mods/linux_build.smod
        echo "    PATH=$PATH:/bin:/sbin" >> "$SINGULARITY_BUILD_ROOT/environment"
        echo '    export PATH PS1 SINGULARITY_INIT' >> "$SINGULARITY_BUILD_ROOT/environment"
    chroot "$SINGULARITY_BUILD_ROOT" /usr/bin/env -i PATH="$PATH" "$CMD" "$@"

```

**Comment by nl384** [comment]
I did alot of yum removes and yum installs today. Could that have maybe been the issue?

**Comment by gmkurtzer** [comment]
What branch are you running?

**Comment by nl384** [comment]
How can I tell? I just downloaded the master branch, an hour and a half ago.

**Comment by gmkurtzer** [comment]
Ahhh,... I was fixing it in 2.x, not master! Haha... ok, do another pull now please and let me know!

Thanks!

**Comment by nl384** [comment]
From the master or 2.x branch?

**Comment by nl384** [comment]
Seems to have been fixed. Thanks, Greg!

**Comment by gmkurtzer** [comment]
Perfect, thanks!
