### ISSUE TITLE
how can I create a writable image without the sudo privilege and squashfs?

### ISSUE THREAD

**Issue by Zhang-Wenwen** [apptainer/singularity#1790]
## Version of Singularity:

2.4-dist
i
### Expected behavior
successfully go into the container 

### Actual behavior

ERROR  : No valid /bin/sh in container
ABORT  : Retval = 255

### Steps to reproduce behavior

singularity build caffe2_v1.simg ubuntu-16.04-cuda8.0.44-devel-cudnn7-nccl2-mofed4212-openmpi2-caffe2.simg 
 singularity image.create caffe2-overlay.img
singularity run  caffe2-overlay.img 

and I can't install squashfs in Ubuntu . And I can't acquire sudo privilege either. What can I do to create a writable image? It drives me crazy already.

**Comment by GodloveD** [comment]
Heya @zhangwewenwen.  I'm not completely sure what you are trying to do, but I can give you some suggestions. 

If you want to create a writable container (sandbox) from a local image, you can do so like this:
```
$ singularity build --sandbox new.simg local.simg
```
and then to enter the image as writable, you would do this:

```
$ singularity shell --writable new.simg/
```
If you are trying to use an image with an overlay, you would do this:
```
$ singularity image.create my_overlay.ext3

$ singularity shell --overlay my_overlay.ext3 local.simg
```
Does that help?

**Comment by dtrudg** [comment]
Closing - no follow up. Please let us know if you have further comment or questions.
