### ISSUE TITLE
The overlay option uses an invalid upper filesystem

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#1797]
## Version of Singularity:

As noted in in #943, if the lower filesystem has extended attributes, singularity cannot create bind mount points on top of existing subdirectories.  This is because the upper overlay filesystem is tmpfs which does not support extended attributes, and according to the [kernel documentation on overlay](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt), this is not acceptable:
```
The upper filesystem will normally be writable and if it
is it must support the creation of trusted.* extended attributes, and
must provide valid d_type in readdir responses, so NFS is not suitable.
```
In fact RHEL7 requires that it be ext3, ext4, or xfs with ftype=1.

Here is an idea on how to fix this: a new ext3 filesystem could be created in a sparse file in a tmpfs filesystem, mounted with loopback, and then used as the upper filesystem for overlay.

### Expected behavior

Overlay can create a bind mount point anywhere.

### Actual behavior

When creating a bind mount point on top of a directory that already has extended attributes, singularity gets a "Operation not supported" error.

### Steps to reproduce behavior

On a system with overlay enabled and a lower layer filesystem with extended attributes, try to --bind to a new subdirectory on top of an existing directory.

**Comment by cclerget** [comment]
Hi @DrDaveD , in v3 the problem you describe is solved differently, all happens in a tmpfs session directory, where an overlay lower layer is created, then all directories/files are created in this directory before any mount by parsing a mount point list and overlay is mounted with following options :
`lowerdir=/session/overlay-lowerdir:/session/rootfs,upperdir=/session/overlay-upperdir,workdir=/session/overlay-workdir`. With that workflow there is no need to create bind directories in upper layer.

`/session/overlay-upperdir` resides in session directory too, but don't store bind points anymore like it was done in v2, just here to store some files/directories eventually touched during run, for persistent storage, you to pass an ext3 image via `-o` option which solve the problem.

To apply the same workflow in v2, that would require what you have done with underlay to manage mount point list and then create necessary directories/files in a tmpfs overlay lower layer like described above but as you know, for the time being all efforts are focused on v3.

Between it would be greatly helpful/appreciated if you could give feedbacks on v3 which integrate your underlay idea ;), that could help us a lot.

**Comment by DrDaveD** [comment]
So @cclerget you are saying that in v3 the parts of the image that are not overridden by other bind points are also bound into the lower layer?  So the lower layer is exactly like my v2 underlay (and was it implemented independently of my PR, or was my algorithm borrowed)?  And overlay is only used for writable images, for what singularity calls persistent storage?  Hopefully for read-only cases only the lower layer is used and overlayfs isn't even attempted, that will be great.

If that is all correct, I think v3 still probably has the problem that is the subject of this issue, just not for bind mounts, but for writable images.  If the user tries to add something on top of an image directory that has extended attributes, the upper layer has to have it too.  It sounds like the v3 overlay implementation still does not follow the overlayfs rule that the upper layer filesystem has to support extended attributes.

By the way I am not suggesting that this get fixed in v2.  The underlay option is sufficient for us to get by until v3.

**Comment by cclerget** [comment]
@DrDaveD v3 is not affected by this issue for bind mounts, since every directories/files (not present in container root filesystem) are created in a lower layer, then this lower layer is merged with the container root filesystem with overlay mount, that was implemented independently of your PR and it's not the same as underlay v2 since there is no need to recreate the container root filesystem tree, only directories/files not present in container root filesystem.

For writable images users can only specified ext3 images for both v2 and v3, which solve the issue. It remains the tmpfs upper layer case, in v3 this tmpfs upper layer would be only used if `--writable` is specified and if user doesn't provide `--overlay` flag (and only with squashfs and SIF images, ext3/sandbox images would be directly writable without overlay) or if a SIF image is used without overlay partition in the image. Otherwise without `--writable` container image will be mounted in read-only mode.

**Comment by DrDaveD** [comment]
Ok I understand the first paragraph now, that for bind mounts (at least in the read only case) v3 is using the image as the upper layer and tmpfs with extra directories as the lower layer, so there's not a problem there.  I'm a bit surprised that works (it seems to not be the way overlay is intended to be used) but ok, it apparently does work.

I am still confused about your second paragraph, however.  There's too many combinations for me to follow, and I don't necessarily need to understand them all at this point (I will probably learn them later as I get more familiar with v3).  It does sound however like there is still a tmpfs upper layer case in combination with --writable, is that true?  If so, why would it not be subject to the restriction that I posted in the description of this issue?  (Maybe it is because the lower layer then could only be squashfs, and it also does not have extended attributes?)

**Comment by DrDaveD** [comment]
I have now started to test v3, and adding bind directories works even on RHEL6 where there is no overlayfs so it must be using an algorithm very similar to my underlay PR, binding the portions of the container image that are not overridden by user bindpoints into the same layer.

**Comment by DrDaveD** [comment]
This is no longer a problem in v3.
