### ISSUE TITLE
certificate verification fails

### ISSUE THREAD

**Issue by satra** [apptainer/singularity#1798]
## Version of Singularity:

2.5.2-dist

### Expected behavior

should run without error

### Actual behavior

```
# singularity --debug shell shub://GodloveD/lolcow
Enabling debugging
Ending argument loop
Singularity version: 2.5.2-dist
Exec'ing: /usr/lib/x86_64-linux-gnu/singularity/cli/shell.exec
Evaluating args: 'shub://GodloveD/lolcow'
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /root/.singularity
VERBOSE2 REGISTRY not defined (None)
VERBOSE2 NAMESPACE not defined (None)
VERBOSE2 SINGULARITY_DOCKER_ARCHITECTURE found as amd64
VERBOSE2 SINGULARITY_DOCKER_OS found as linux
VERBOSE2 SINGULARITY_ENVIRONMENT found as None/.singularity.d/env/90-environment.sh
VERBOSE2 SINGULARITY_RUNSCRIPT found as None/singularity
VERBOSE2 SINGULARITY_TESTFILE found as None/.singularity.d/test
VERBOSE2 SINGULARITY_DEFFILE found as None/.singularity.d/Singularity
VERBOSE2 SINGULARITY_HELPFILE found as None/.singularity.d/runscript.help
VERBOSE2 SINGULARITY_ENVBASE found as None/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as None/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_NOHTTPS found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as .
VERBOSE2 SHUB_NAMEBYHASH not defined (None)
VERBOSE2 SHUB_NAMEBYCOMMIT not defined (None)
VERBOSE2 SHUB_CONTAINERNAME not defined (None)
VERBOSE2 SINGULARITY_CONTENTS found as /tmp/.singularity-layerfile.lrNFcz
VERBOSE2 SINGULARITY_PYTHREADS found as 9
DEBUG 
*** STARTING SINGULARITY PYTHON PULL ****
VERBOSE2 SINGULARITY_CONTAINER found as shub://GodloveD/lolcow
VERBOSE2 SINGULARITY_PULLFOLDER found as .
DEBUG Found uri shub://
DEBUG Headers found: Content-Type,Accept
DEBUG GET https://www.singularity-hub.org/api/container/GodloveD/lolcow:latest
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/singularity/python/pull.py", line 74, in <module>
    main()
  File "/usr/lib/x86_64-linux-gnu/singularity/python/pull.py", line 66, in main
    layerfile=LAYERFILE)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/shub/main.py", line 77, in PULL
    manifest = client.get_manifest()
  File "/usr/lib/x86_64-linux-gnu/singularity/python/shub/api.py", line 113, in get_manifest
    response = self.get(base, return_response=True)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/base.py", line 291, in get
    updating_token=updating_token)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/base.py", line 310, in submit_request
    response = safe_urlopen(request)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/base.py", line 152, in safe_urlopen
    return opener.open(url, data=data)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
ABORT: Aborting with RETVAL=255
```

### Steps to reproduce behavior

```bash
 $ docker run -it --rm neurodebian:latest
 # apt-get update 
 # apt-get install singularity-container
 # singularity --debug shell shub://GodloveD/lolcow
```

reissue of #1628

**Comment by dtrudg** [comment]
Hi @satra - this is not likely a recurrence of #1628 as that was an issue interacting with the google docker registry, and not shub.

The error here isn't to do with singularity per se. The urllib2 installation in your site python doesn't have the CA certificate required to validate the certificate that SingularityHub is using.

This appears to be due to missing deps for the `singularity-container` package. If you do this...

```
apt-get install python-certifi
```

.. the download from shub should work, as this will make certain ca certs are available etc.

**Comment by satra** [comment]
thank @dctrud - i will try to upstream the dependency.

**Comment by jon-nowacki** [comment]
@dctrud I tried that fix and still have the same issue

root@ubuntuZ800:/data/SINGULARITY# **apt-get install python-certifi**
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-certifi is already the newest version (2018.1.18-2).
The following packages were automatically installed and are no longer required:
  libcurl4 libsdl-ttf2.0-0
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 114 not upgraded.
root@ubuntuZ800:/data/SINGULARITY# **singularity pull --name hello.simg shub://vsoch/hello-world**
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/singularity/python/pull.py", line 74, in <module>
    main()
  File "/usr/lib/x86_64-linux-gnu/singularity/python/pull.py", line 66, in main
    layerfile=LAYERFILE)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/shub/main.py", line 77, in PULL
    manifest = client.get_manifest()
  File "/usr/lib/x86_64-linux-gnu/singularity/python/shub/api.py", line 113, in get_manifest
    response = self.get(base, return_response=True)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/base.py", line 291, in get
    updating_token=updating_token)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/base.py", line 310, in submit_request
    response = safe_urlopen(request)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/base.py", line 152, in safe_urlopen
    return opener.open(url, data=data)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>

**Comment by jon-nowacki** [comment]
At the same time docker pull works fine.  So it seems specific to the singularity database

**singularity pull docker://godlovedc/lolcow**
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/godlovedc/lolcow:latest
Cache folder set to /home/jnowacki/.singularity/docker
[6/6] |===================================| 100.0%
Importing: base Singularity environment
Exploding layer: sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118.tar.gz
Exploding layer: sha256:3b61febd4aefe982e0cb9c696d415137384d1a01052b50a85aae46439e15e49a.tar.gz
Exploding layer: sha256:9d99b9777eb02b8943c0e72d7a7baec5c782f8fd976825c9d3fb48b3101aacc2.tar.gz
Exploding layer: sha256:d010c8cf75d7eb5d2504d5ffa0d19696e8d745a457dd8d28ec6dd41d3763617e.tar.gz
Exploding layer: sha256:7fac07fb303e0589b9c23e6f49d5dc1ff9d6f3c8c88cabe768b430bdb47f03a9.tar.gz
Exploding layer: sha256:8e860504ff1ee5dc7953672d128ce1e4aa4d8e3716eb39fe710b849c64b20945.tar.gz
Exploding layer: sha256:736a219344fbca3099ce5bd1d2dbfea74b22b830bac0e85ecca812c2983390cd.tar.gz
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building Singularity image...
Singularity container built: ./lolcow.simg
Cleaning up...
Done. Container is at: ./lolcow.simg

**Comment by jon-nowacki** [comment]
If I set:
**export PYTHONHTTPSVERIFY=0**

I can download from singularity.

As soon as I set

**export PYTHONHTTPSVERIFY=1**

It's broken again.

**Comment by jmstover** [comment]
@JonN17 
I just looked at the Singularity-Hub cert, and it's signed by Let's Encrypt Authority X3... 

If you do:

```
wget https://singularity-hub.org
```

Do you get a Cert error? It doesn't appear as if you have the Let's Encrypt CA's in your SSL certs ... On Ubuntu 18.04 you need `ca-certificates`, of 20180409 (that I know of... maybe earlier, but I know that version has the root cert). 

```
$ ls -l /etc/ssl/certs/* | grep 'DST'
lrwxrwxrwx 1 root root     18 Jul 29 16:19 /etc/ssl/certs/2e5ac55d.0 -> DST_Root_CA_X3.pem
lrwxrwxrwx 1 root root     53 Jul 29 16:19 /etc/ssl/certs/DST_Root_CA_X3.pem -> /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt
```

**Comment by dtrudg** [comment]
@jmstover @JonN17 - the python requests module doesn't always use the system certificates installed by the `ca-certificates` package. On Fedora and newer RHEL `requests` is patched to do that, but on Debian / Ubuntu I don't think that it is - so it uses what's provided by the python `certifi` package, and not the system `/etc/ssl/...` content.

You can do this...

```
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
```

... to tell python to use the system CA certs instead of the certifi content.

Otherwise, if the version of `python-certifi` in this Ubuntu isn't new enough, try a `pip install certifi` to get a newer one.

What version of Ubuntu is this?

**Comment by jmstover** [comment]
> the python requests module doesn't always use the system certificates installed

Wait... They use the system openssl doen't they? And that uses the /etc/ssl/certs structure... or are they changing the cert location on Python calls?

And if they're doing that... WTF are they doing?????

*Edit:*
Quick search ... they seem to be using the list from:
https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt

Which again, is where ca-certificates comes from... so WTF are they doing duplicating the trusted certs? What if you have an explicit cert you add into `/etc/ssl/certs` for a internal cert... is it trusted, or not? It's trusted by OpenSSL ... and Python should be using OpenSSL ... :/

**Comment by dtrudg** [comment]
@jmstover - this is not `python` doing this per se... it's the `requests` package for python that uses `certifi` for its CA bundle.

https://pypi.org/project/certifi/

It is indeed the mozilla bundle.

If you look in RHEL/Fedora at `/usr/lib64/pythonXXX/dist-packages/certifi` then you'll find code modified to point at the system `/etc/ssl/certs`

Debian / Ubuntu don't modify the upstream `certifi` package, and have a `/usr/lib/python3/dist-packages/certifi/cacert.pem` file that will be used.

**Comment by jmstover** [comment]
Right, but that doesn't answer my question... if you add a certificate under /etc/ssl/ ... will python ignore it? I mean... if you have an internal root CA cert for internal servers, you add that certificate under /etc/ssl ... is python going to see the certificte as valid or no?

i.e. ... 
```
ln -sf LocalRootCA.pem /etc/ssl/certs/`openssl x509 -hash -noout -in LocalRootCA.pem`.0
```

OpenSSL will see it as valid... but is the `certifi` package ignoring the normal OpenSSL processing and only using the provided bundle?

**Comment by dtrudg** [comment]
Python in general, and the `requests` module are 2 different things. If a python package is using calls out to OpenSSL directly then it should work. However, Singularity uses `requests` to make HTTP calls, and requests needs it to be accessible through `certifi` so you need to add to the certifi bundle.

Here's a nice link about it: https://incognitjoe.github.io/adding-certs-to-requests.html

**Comment by dtrudg** [comment]
_off topic_

@jmstover  - this is not relevant here, but for python stuff using the `ssl` package (which requests does not directly) then you get what you would expect... e.g. on my Mac it is looking at:

```
python -c "import ssl; print(ssl.get_default_verify_paths())"

DefaultVerifyPaths(cafile='/private/etc/ssl/cert.pem', capath='/private/etc/ssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/private/etc/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/private/etc/ssl/certs')
```

**Comment by jmstover** [comment]
How is requests not using OpenSSL to handle SSL handshakes? Pretty sure python in linked to OpenSSL... 

We used to need to update the system certs to get python to work right with Singularity and SSL... Not a separate package, or specifically code in a specific bundle. But maybe that was for something else? 

*Edit:*
And sorry for the off-topicness... just trying to figure out WTF the python modules are doing, and what is so important that you need to duplicate the certs in your own package instead of using the system certs... :/

**Comment by dctrud** [comment]
If you were previously updating the system certs on a RHEL / Fedora distro that would have worked, as `certifi` is patched there to point at system certs / bundles AFAIK. Perhaps, also, Singularity migrated to `requests` from a lower level client at some point?

Here is the code in `requests` that handles ssl verification:

https://github.com/psf/requests/blob/67a7b2e8336951d527e223429672354989384197/requests/adapters.py#L203

It is working on `connection` which is a `urllib3.Connection`, and you can dig into that if you want to see what it is doing..

https://github.com/urllib3/urllib3/blob/master/src/urllib3/util/ssl_.py

**Comment by dtrudg** [comment]
﻿﻿﻿Ughh - apologies @jmstover - I have misread something above. We are using either `urllib` or `urllib2` here, not `requests`.

This means exact behavior is dependent on whether we get `urllib` or `urllib2` - which depends on python version, so distro. I'll need to look into this more.

@JonN17 - what's the exact version of Singularity you are using, and which version of Ubuntu? Then I can go back and replicate this.
