### ISSUE TITLE
Using system libs at runtime

### ISSUE THREAD

**Issue by zyndagj** [apptainer/singularity#1815]
## Version of Singularity: 2.5.2

Singularity used to have a `SINGULARITY_CONTAINLIBS` variable for using system libraries inside the container. That does not seem to exist any longer. Other than `--nv` is there a way make system libraries available in `/.singularity.d/libs` when running a container?

**Comment by GodloveD** [comment]
Hi @zyndagj 

Singularity still has `SINGULARITY_CONTAINLIBS`.  The variable has just been moved to `libexec/functions`.  If you try it, you should still be able to bind mount what you need.

**Comment by zyndagj** [comment]
Found it.

https://github.com/singularityware/singularity/blob/2.6.0/libexec/functions#L500

I was originally searching on the master branch when I couldn't find it. Does that mean this feature will disappear with 3.0? If so, do you have a way forward for support Cray Aries MPI libraries?

**Comment by GodloveD** [comment]
The --nv option will be instantiated in 3.0 (new master). Didn't realize anybody was using the env var. I guess we can make sure to instantiate that too.

**Comment by dtrudg** [comment]
Noting that env vars are now listed in the docs here, including the ones referenced above: https://sylabs.io/guides/3.4/user-guide/appendix.html
