### ISSUE TITLE
Custom mksquashfs location for RPM build

### ISSUE THREAD

**Issue by omenos** [apptainer/singularity#1820]
Hello,

With the release of 2.6.0 the ability to specify a custom location for mksquashfs has been added to the build process (#1662). However, for our cluster I'm trying to build RPM's to deploy to the nodes and I'm not sure this functionality is supported.

I have a custom build script that contains some fixes for CentOS 6 (as well as our custom environment), but the following is where the real building is defined:

```bash
./configure --with-mksquashfs=/apps2/squashfs/4.3/bin/mksquashfs
make -j8 dist
rpmbuild -ta \
--define="_prefix $INSPREFIX" \
--define="_sysconfdir $INSPREFIX/etc" \
--define="_defaultdocdir $INSPREFIX/share" \
singularity-*.tar.gz
```
After installing, though, I still get the normal squashfs-tools error:

```bash
ERROR: You must install squashfs-tools to build images
ABORT: Aborting with RETVAL=255
```
Is this feature only for standard installs, not RPM distribution builds? We only have a few nodes where users could build images, but not having to copy mksquashfs to them would be a nice touch :)

Cheers,
Mike

**Comment by jmstover** [comment]
@omento 

I _think_ you add the extra option in at the end like:

```
rpmbuild -ta \
--define="_prefix $INSPREFIX" \
--define="_sysconfdir $INSPREFIX/etc" \
--define="_defaultdocdir $INSPREFIX/share" \
singularity-*.tar.gz \
--with-mksquashfs=/apps2/squashfs/4.3/bin/mksquashfs
```

**Comment by omenos** [comment]
Alright, I'll try moving it from `configure` to `rpmbuild` and see what happens. If that fails I'll try with both (fingers crossed).

Cheers,
Mike

**Comment by omenos** [comment]
Nope, `rpmbuild` does not see it as a valid option.

Cheers,
Mike

**Comment by jmstover** [comment]
Hrmm.... okay... The RPM spec has a `%configure` call... It seems that it's pretty stupid, and bases it just on things like `_prefix`, `_localstatedir`, etc... 

So...  it looks like the only way we may be able to do this is something like:
```
%bcond_with mksquashfs

%configure \
  %{?with_mksquashfs:--with-mksquashfs=%{_mksquashfs}}
```

And then you run the `rpmbuild` with:
```
rpmbuilt -ta [...] --define '_mksquashfs /path/to/mksquashfs' singularity-*.tar.gz --with mksquashfs
```

That appears like it may be the only way.... the initial "configure" is just to build the Makefiles, so you can do a `make dist`. That tarball is a separate entity.

**Comment by omenos** [comment]
Alright, thanks I'll give that a shot.

For clarification:

* Is the `%{with_mksquashfs` line missing an `}`?
* Is `--with mksquashfs` in the `rpmbuild` line supposed to have a space?
* I need to switch `-ta` to `tb` 

Just trying to get all my ducks in a row.

Cheers,
Mike

**Comment by jmstover** [comment]
Edited...  Yea, I missed a closing `}` there, and swapped the example to be `-ta` ... that should be irrelevant for the most part. Habit for me to build with `-tb` instead of `-ta`.

The `--with mksquashfs` is correct

**Comment by omenos** [comment]
Based on the output of `configure`, it doesn't seem --with-mksquashfs is being picked up:
```bash
checking --with-mksquashfs... no
```

Relevent sections:
```bash
# Generated Spec files
%bcond_with mksquashfs
%configure
%{?with_mksquashfs:--with-mksquashfs=%{_mksquashfs}}
```

```bash
# Build script
rpmbuild -ta \
--define="_prefix $INSPREFIX" \
--define="_sysconfdir $INSPREFIX/etc" \
--define="_defaultdocdir $INSPREFIX/share" \
--define="_mksquashfs /apps2/squashfs/4.3/bin/mksquashfs" \
singularity-*.tar.gz --with mksquashfs
```

Cheers,
Mike

PS: I do appreciate the rapid response times, I wasn't expecting that!

**Comment by jmstover** [comment]
Hrmm.... damn. I was hoping it'd work. I'm basing all this off of:

http://rpm.org/user_doc/conditional_builds.html

I've been trying different ways to get that to work, and so far haven't got it to. :/

**Comment by omenos** [comment]
Like I said before, it's not a huge priority or issue to copy `mksquasfs` and `unsquashfs` to the local nodes. This was just something I noticed during the build process.

Cheers,
Mike

**Comment by jmstover** [comment]
So, I was talking with Greg here and I was over complicating it. Change the `.spec` or `.spec.in` to be:

```
%configure \
    %{?_mksquashfs:--with-mksquashfs=%{_mksquashfs}}
```

Then when you `--define` the location of mksquashfs to `_mksquashfs`, it will append the `--with-mksquashfs` binary. You could just add that option and path to the spec file like:

```
%configure \
  --with-mksquashfs=/apps2/squashfs/4.3/bin/mksquashfs
```

But that will be a hard coded always in that spec file instead of being configurable. Depends on how your usage.

**Comment by omenos** [comment]
I just realized I never got the `\` added to the configure line. I use `sed` to modify the scripts and never escaped that character...

But for some reason when building I still get the line during the configuration stage that there is no mksquashfs... Can you check your build logs and see what yours is reporting?

Cheers,
Mike

**Comment by omenos** [comment]
It works! I think this can be closed now. Thanks for the help Jason, I really appreciate it!

Cheers,
Mike
