### ISSUE TITLE
How to make --nv flag work?

### ISSUE THREAD

**Issue by renganxu** [apptainer/singularity#1829]
## Version of Singularity:

2.6.0

### Expected behavior
The following command should give the correct output
$ singularity exec --nv test.img nvidia-smi

### Actual behavior
$ singularity exec --nv test.img nvidia-smi
/.singularity.d/actions/exec: line 9: exec: nvidia-smi: not found

### Steps to reproduce behavior
1. Install singularity 2.6.0 to /cm/shared/apps/singularity/2.6.0
2. edit /cm/shared/apps/singularity/2.6.0/etc/singularity/nvliblist.conf by putting the GPU driver binaries path
\# put binaries here
\# In shared environments you should ensure that permissions on these files
\# exclude writing by non-privileged users.
/cm/local/apps/cuda/libs/current/bin/nvidia-smi
/cm/local/apps/cuda/libs/current/bin/nvidia-debugdump
/cm/local/apps/cuda/libs/current/bin/nvidia-persistenced
/cm/local/apps/cuda/libs/current/bin/nvidia-cuda-mps-control
/cm/local/apps/cuda/libs/current/bin/nvidia-cuda-mps-server
\# put libs here (must end in .so)
libcuda.so
libEGL_installertest.so
libEGL_nvidia.so
libEGL.so
...

3. create singularity container image
singularity build --writable test.img centos7.def

4. run the command
 $ singularity exec --nv test.img nvidia-smi
/.singularity.d/actions/exec: line 9: exec: nvidia-smi: not found

My question is how does Singularity use the nvliblist.conf file and how to make --nv flag work? The PATH and LD_LIBRARY_PATH environment variables didn't include the GPU driver binaries and libraries automatically. And Singularity didn't bind the GPU driver path /cm/local/apps/cuda/libs/current automatically. 

And should we include the full path of those GPU driver libraries? Otherwise how will Singularity know the paths of those libraries.

Of course the user can include GPU driver paths in PATH and LD_LIBRARY_PATHS, and bind those paths manually. But I think that is not the purpose of --nv flag. My understanding is that --nv can do all of these work automatically.

**Comment by GodloveD** [comment]
Libraries will work on any system but binaries rely on overlays being enabled on the system. I'll bet overlays are not available on your system. This is a bug.

**Comment by ink1** [comment]
It took me a while to find out about the ```--nv``` option. I'm on the latest release 2.6.0 now but prior to that used docker2singularity conversion. I figured I needed to use a newer image format (simg) since Nvidia requires 2.5+. I managed to run ```nvidia/cuda:latest``` docker image in the end. Pushed it into the local docker repo and then run ```singularity build``` to create the image. With all that ```singularity exec --nv myimage.simg nvidia-smi``` worked (with the usual awk: warning of course).

 A bit confusingly ```singularity build``` help does say there is ```--nv``` option too but when executed complains that ```ERROR: Unknown option: --nv```

**Comment by jmstover** [comment]
@ink1 ... What does `singularity --version` give you? My copy of 2.6.0 built from the git tag doesn't have the `--nv` option in the `build` help.

**Comment by ink1** [comment]
@jmstover  Sorry, my bad. I must have confused it with some other help output because the build help is relatively short. Yes, I'm on 2.6.0 pulled from github.

**Comment by jmstover** [comment]
@ink1 :+1: ... no problem. I was just hoping we didn't have a version floating out there with the wrong help output. ;)

**Comment by dtrudg** [comment]
Closing this - have confirmed the help output on 3.x is correct
