### ISSUE TITLE
Singularity within a Singularity container

### ISSUE THREAD

**Issue by tjhendrickson** [apptainer/singularity#1831]
## Version of Singularity:

Write here. 2.5.2-dist

### Expected behavior

Write here. singularity pull shub://vsoch/hello-world should pull singularity image vsoch/hello-world

### Actual behavior

Write here. 
singularity pull shub://vsoch/hello-world
WARNING [U=0,P=26925]      sylabsToken()  Authentication token file not found : Only pulls of public images will succeed
FATAL   [U=0,P=26925]      PullImage()  Not a valid library reference: shub://vsoch/hello-world

### Steps to reproduce behavior

Write here.  

git clone   https://github.com/tjhendrickson/bids-app-host.git
cd bid-app-host
singularity build path/and/name/of/image Singularity
singularity exec path/and/name/of/image singularity pull shub://vsoch/hello-world

**Comment by bauerm97** [comment]
@tjhendrickson Are you positive that you're running on `2.5.2-dist`? It appears that you're running a build of Singularity version 3. Can you run `singularity version` for me?

Currently in the 3.0 tree [branch: `master`], this behavior is expected as `singularity pull` does not yet understand the `shub` URI.

**Comment by tjhendrickson** [comment]
I installed singularity from the git repository master branch, so I likely install version 3.0. I'll reinstall with version 2.5.1.

Thanks!

**Comment by bauerm97** [comment]
@tjhendrickson closing this issue for now :) If you need something else, feel free to re-open and ping me or simply submit a new issue. Cheers!
