### ISSUE TITLE
Failed to execv() /.singularity.d/actions/shell, continuing to /bin/sh: Exec format error

### ISSUE THREAD

**Issue by denisovlev** [apptainer/singularity#1836]
## Version of Singularity:

2.5.1-dist

### Expected behavior

`singularity shell` works on any machine

### Actual behavior

When I build singularity image on one machine and copy it to another `singularity shell` does not work

### Steps to reproduce behavior

```
sudo singularity build --writable horovod.img docker://uber/horovod:0.13.11-tf1.10.0-torch0.4.0-py2.7

singularity shell --nv ./horovod.img
```

It works on one machine but when I copy the image file to another machine it does not work: 

```
$ singularity --debug shell --nv ./horovod.img
INFO    [U=2353,P=103091]  action_shell()                            Singularity: Invoking an interactive shell within container...

DEBUG   [U=2353,P=103091]  action_shell()                            Exec'ing /.singularity.d/actions/shell
ERROR   [U=2353,P=103091]  action_shell()                            Failed to execv() /.singularity.d/actions/shell, continuing to /bin/sh: Exec format error
VERBOSE [U=2353,P=103091]  action_shell()                            Invoking the container's /bin/sh
DEBUG   [U=2353,P=103091]  action_shell()                            Exec'ing /bin/sh
ERROR   [U=2353,P=103091]  action_shell()                            Failed to execv() /bin/sh: Exec format error
ABORT   [U=2353,P=103091]  action_shell()                            Retval = 255
```

I cannot build the image on the same machine I run it because it does not have internet and I do not have sudo rights there.

Seems like it is related to https://github.com/singularityware/singularity/issues/1079

### Environment

Build: 

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

Execution (HPC cluster): 

```
$ lsb_release -a
LSB Version:	:core-4.1-noarch:core-4.1-ppc64le
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.4 (Maipo)
Release:	7.4
Codename:	Maipo

```

Both are real physical machines

**Comment by cclerget** [comment]
Hi @denisovlev , with `Exec format error` as error, it looks like you build image on a machine (x86_64) and run image on cluster with a different architecture (ppc64le). With internet access on cluster, you could build image on cluster with `--sandbox` option without sudo like : `singularity build --sandbox dirimage docker://...`. If you can't have internet access on cluster, except build images on a VM with ppc64le architecture, I'm afraid there is no other way to build image for your cluster.

**Comment by denisovlev** [comment]
It seems that not having internet in the cluster is a common practice in HPC. There should be an option to build from docker container that is pre-downloaded and put in the cluster.

**Comment by mxmlnkn** [comment]
@denisovlev you can use singularity pull to download a docker image and then use the localimage bootstrap to use the downloaded image directly. You'll have to use specify the architecture if you pull on a different system:

    export SINGULARITY_DOCKER_ARCHITECTURE=ppc64le
    singularity pull docker://debian:9
