### ISSUE TITLE
Trouble binding host directories to container

### ISSUE THREAD

**Issue by dlevitas** [apptainer/singularity#1839]
## Version of Singularity:

2.5.2

### Expected behavior

Be able to bind directories from the host server to the container to run fmriprep.

### Actual behavior

When I try running the following:
```
singularity run -B $data_dir:/ $HOME/fmriprep_1.1.4.img \
$data_dir $output_dir \
participant \
--participant-label $subj 
```

I get this:
```
WARNING: Non existent bind point (directory) in container: '/N/home'
WARNING: Non existent bind point (directory) in container: '/N/u'
WARNING: Non existent bind point (directory) in container: '/N/dc2'
WARNING: Non existent bind point (directory) in container: '/N/soft'
WARNING: Not mounting requested bind point (already mounted in container): /
WARNING: Could not chdir to home: /N/u/dlevitas/Karst
```

### Steps to reproduce behavior

Write here.

```
singularity run -B $data_dir:/ $HOME/fmriprep_1.1.4.img \
$data_dir $output_dir \
participant \
--participant-label $subj 
```

I'm relatively new to Singularity and how to bind directories, so I've been getting lost when reading the documentation. My goal has been to bind the `$data_dir` to the container, but I can't seem to get it to work, which causes fmriprep to quit.

Thank you for the help.

**Comment by DrDaveD** [comment]
What is the host operating system/kernel?  By default only kernels that support overlayfs can add bind mount points that don't exist in the image.  There is a [PR](#1817) that adds an option to do it without overlay but it is not in the base 2.6.0 release.

**Comment by dlevitas** [comment]
My OS is Red Hat Linux 6.10 (Santiago), and the kernel information is 2.6.32-754.2.1.e16.x86_64 so I don't believe overlayfs is on this system. Do I need to explicitly add a path in the image or would there be a different way I could do this?

**Comment by DrDaveD** [comment]
You could use the singularity-2.6.0 rpm now in epel-testing and which be in epel this week.  It includes pr #1817, because I wrote the PR and I support the epel distribution of singularity.  Set 'enable underlay = yes' in singularity.conf.  The singularity project doesn't support it, so if you have any problems with it make an [epel ticket](https://apps.fedoraproject.org/packages/singularity/bugs/).

**Comment by dlevitas** [comment]
I was actually able to resolve my issue by place my container in the same directory as the data. 

Thanks again.
