### ISSUE TITLE
Enhancement: Create an 'install check' script

### ISSUE THREAD

**Issue by robertlugg** [apptainer/singularity#1840]
## Version of Singularity:
2.6.0
### Expected behavior

I installed incorrectly.  However, it was hard to figure out what I did incorrect.  The request is to make a script that could be run that would give good errors and warnings which would be useful for debugging.

First, my error:  When I run .../libexec/singularity/bin/mount-suid, I get the following errors:
ERROR   [U=1001,P=21166]   singularity_suid_init()                   Installation error, run the following commands as root to fix:
ERROR   [U=1001,P=21166]   singularity_suid_init()                       sudo chown root:root /home/rlugg/libexec/singularity/bin/mount-suid
ERROR   [U=1001,P=21166]   singularity_suid_init()                       sudo chmod 4755 /home/rlugg/libexec/singularity/bin/mount-suid
ABORT   [U=1001,P=21166]   singularity_suid_init()                   Retval = 255

No complaints at all with that message; it tells me what I did wrong.  However, I just got lucky and ran that program randomly.  When I run 'singularity', I don't get the same useful message.

### Actual behavior

./cleanupd:  Environment is not properly setup
./start and 'singularity': Failed invoking the NEWUSER namespace runtime: Invalid argument

**Comment by dtrudg** [comment]
Hi @robertlugg - have you come across `singularity selftest`? I think this may indicate the issue you observed:

```
$ singularity selftest
 + sh -c test -f /usr/local/etc/singularity/singularity.conf                           (retval=0) OK
 + test -u /usr/local/libexec/singularity/bin/action-suid                              (retval=0) OK
 + test -u /usr/local/libexec/singularity/bin/mount-suid                               (retval=0) OK
 + test -u /usr/local/libexec/singularity/bin/start-suid                               (retval=0) OK
```
