### ISSUE TITLE
Singularity pull with --hash or --commit downloads image even if latest version

### ISSUE THREAD

**Issue by mwiens91** [apptainer/singularity#1841]
## Version of Singularity:

2.4.2-dist

### Expected behavior

When pulling an image with `--hash` or `--commit`, Singularity re-downloads an image even if the latest version is already downloaded and available. I would expect that Singularity would be smart enough to recognize it already has the latest version of the image and not re-download the image.

### Steps to reproduce behavior

```
singularity pull --commit shub://vsoch/hello-world
singularity pull --commit shub://vsoch/hello-world
````

The second pull will re-download the image even though the latest version is already available. Same thing happens with `--hash`.

**Comment by jmstover** [comment]
It doesn't look like the shub pull handler `$libexecdir/singularity/python/pull.py` does any checking on if the file exists already.

If you look at `$libexecdir/singularity/cli/pull.exec` you can see some logic for on a docker:// URI it does a simple check on if `$SINGULARITY_IMAGE` exists, and if the `-F` flag was specified. But there's none of that for the `shub://` handling.

**Comment by dtrudg** [comment]
Closing as `--commit` and `--hash` are not implemented in 3.x
