### ISSUE TITLE
Fix HTTPS on the Singularity website

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#185]
We're a security tool, we shouldn't be causing HTTPS warnings...

**Comment by gmkurtzer** [comment]
Hrmm, I wonder how to fix that.. the site is hosted on GitHub Pages.

@bernardl, any ideas?

**Comment by bernardl** [comment]
@bbockelm According to GitHub's documentation, "HTTPS is not supported for GitHub Pages using custom domains":

https://help.github.com/articles/securing-your-github-pages-site-with-https/

If you have other suggestions we can try it out.

Thanks!

**Comment by gmkurtzer** [comment]
Thanks Bernard! I'm closing the ticket because there doesn't appear to be anything we can do to fix (but if I'm mistaken, let me/us know and I'll reopen the ticket).

Thanks!
