### ISSUE TITLE
3.0: '/' is writable by the user in the container

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#1857]
## Version of Singularity:

master branch

### Expected behavior

The user is not able to modify the root directory

### Actual behavior

The root directory is owned by the user and writable by the user inside the container, both with and without the -u option.

### Steps to reproduce behavior

/usr/local/bin/singularity exec favoriteimage.img bash
touch /file

To fix this, the under layer should be mounted read-only as it is in my [2.6 underlay PR](#1817).  When running setuid, I also make the directories in the under layer owned by root so they look like they're owned by an expected user.  That's not an option when running as an unprivileged user.

**Comment by jakirkham** [comment]
Is this intended to be a 3.0.0 release blocker?

**Comment by DrDaveD** [comment]
I believe it is a serious issue, yes.  If it were in an actual release (not just an alpha) I would consider it something to be handled through security processes, and I wouldn't have made it a public issue.

**Comment by bauerm97** [comment]
@DrDaveD thanks for catching this, will look into the easiest solution. Currently I believe we always use either `-u` or `-o` [`underlay`/`overlay`] whenever running the container by default. I think the best solution is just disable that unless explicitly given that option, right?

**Comment by DrDaveD** [comment]
I think the best solution is the one I put in the description: have the working space (where the mount point directories are created) be at a different path than the place that is finally mounted as '/', and then read-only bind-mount that working space to the final '/' path.  Then no matter which option is used, '/' will not be writable by the user inside the container.  This is what I do in the 2.6 underlay implementation.  The bind mounts then go on top of the final '/' path, not on the working space.
