### ISSUE TITLE
sudo must be owned by uid 0 and have the setuid bit set

### ISSUE THREAD

**Issue by suujia** [apptainer/singularity#1858]
## Version of Singularity: 
Singularity hub
Error build: https://www.singularity-hub.org/containers/3992/log
A successful build: https://www.singularity-hub.org/containers/3905 

### Expected behavior

We are building a singularity image that contains a few hundred bioinformatic/science tools installed with brew. It is for users to log into our servers and shell into their own overlay image on top of this build, and work interactively. I am wondering if I am doing it correctly. 
1. For users to be in their overlay and do brew install additional tools on their own, is this the correct command: `chmod -R 777 /home/linuxbrew/.linuxbrew` for all the tools to be downloaded there? 
I just want to confirm that no sudo access is required for a writable overlay right? (eg. user calls brew install) In the documentation's example seem to call it with sudo, however some issues say there isn't a need. Would appreciate any help :) 

### Actual behaviour

2. Why is it that this error occurs with the installation of certain tools by brew install, they are building fine on dockerhub. I am installing as user `su -c 'brew install ___ 'linuxbrew `
```
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

### Steps to reproduce behavior
```
Bootstrap: docker
From: linuxbrew/linuxbrew


%post
    chown -R linuxbrew: /home/linuxbrew/.linuxbrew
    PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH
    echo 'PATH='$PATH >> /etc/environment

    su -c brew install cpanm linuxbrew
```
Just one of the tools that prints out this message. 
Thanks again, I am quite new to this! And we are thinking of transitioning fully from docker to singularity for our users. :)

**Comment by dtrudg** [comment]
Hi @suujia - do you have this issue if you are building these containers locally - i.e. not on singularityhub? If you do get the issue locally as well as with singularityhub when exactly does this issue come up? When you are building a container as root `singularity build xxxxx` or when you are trying to add to an existing container?

R.E. question 1. - when a user runs a Singularity container they are the same user inside the container as outside, and they cannot `su` or use `sudo`. I'm afraid this means that if a `su` to the `linuxbrew` user is necessary to install new tools then that would not be possible even if permissions on `/home/linuxbrew` are opened up. The user entering the container cannot become the `linuxbrew` user.

**Comment by suujia** [comment]
Hi @dctrud, I actually was able to make a complete build just ignoring those suid warnings, and the image ends up working so I'm ok with that. Yeah we figured out the permissions, just decided to give 777 to the file system users are writing to. 

I just had one more question, my complete build actually has been building for about a week. I've mostly been testing the permissions and general workflow with subsections of our complete container, and they have executed fine. Is there perhaps a limit to singularity? I read that your only limit seems to be a max of 5 build queues in a collection.
https://www.singularity-hub.org/collections/1209 
latest (singularity)

Should I be splitting this big, 20gb image into perhaps two? And reference one in the other like a docker multistage build? Our whole build on dockerhub takes 10 hours. Thanks again for your help!!

**Comment by dtrudg** [comment]
Hi @suujia - sorry there was not reply for ages on this. I went to work elsewhere, but am now back working with Sylabs. Regarding the singularity-hub build - this is a service from Stanford that's not managed by Sylabs. If there's still an issue I'd recommend asking .@vsoch - I'm not aware what the limits are.

**Comment by vsoch** [comment]
hey @suujia ! I was just looking at your collection this morning! The build fails because a file that you are trying to download is not found. You can take a look at the end of the log [here](https://www.singularity-hub.org/containers/3403/log) to see it:

```
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
DownloadError: Failed to download resource "jdk"
Download failed: http://ftp.osuosl.org/pub/funtoo/distfiles/oracle-java/jdk-9.0.4_linux-x64_bin.tar.gz
```

**Comment by dtrudg** [comment]
Closing as no follow-up. Please re-open if you have further issues / questions.

**Comment by suujia** [comment]
Hi sorry for my late reply as well. My internship had ended. Thanks for your efforts!
