### ISSUE TITLE
could test.sh operate in unprivileged mode?

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#186]
since https://github.com/gmkurtzer/singularity/pull/159 is merged, I thought it would be nice to avoid sudoing while testing for various reasons ;)

**Comment by bbockelm** [comment]
I suspect we'd need a separate `test.sh` to avoid using `sudo`.

One problem we have is any use of raw disk images will require a `setuid` binary for the next year or so: you can only use `chroot` directories.

**Comment by gmkurtzer** [comment]
Not all of test.sh uses sudo, I'd suggest we just have a set of tests that are not calling sudo and operate on a directory in which the test image would be exported to.

A year? hehe, you are optimistic! I wonder if the loop devices would ever be namespaced. Have you heard anything on this?

Thanks!

**Comment by bbockelm** [comment]
I think that, once FUSE mounts are available to unprivileged users, then `libguestfs` would provide the ability to read/write the filesystem (alternately, `fuseext` may work).  Based on current progress, it seems reasonable to guess this would be available to mainline kernels within a year.  That would mean RHEL8 or so?

Looks like loopback device support would be feasible, but perhaps further out.

**Comment by gmkurtzer** [comment]
I am going to close this because I don't think there is much that can be done (at least not at present and/or for a while). Fuze integration does potentially offer a really good option if loop devices can not be made namespace-able. Feel free to comment to the thread if you feel I should re-open it.

Thanks!
