### ISSUE TITLE
Compatibility of host<->container OMPI when built with different compilers.

### ISSUE THREAD

**Issue by LiamBindle** [apptainer/singularity#1863]
Hi,

This is a question about the compatibility of a container on a host whose MPI library was built with a different compiler.

Specifically, our cluster is running Open MPI 2.1.1 which I believe was built with Intel compilers (`mpirun` is linking in `libintlc.so`). I would like to build Open MPI in my container with GCC because the GNU compilers are easy to install into a Singularity container.

If my container's OMPI was built with GCC, will it be compatible with a host whose OMPI was built with Intel?

Thanks in advance,

Liam

## Version of Singularity:

2.5

### Expected behavior

n/a

### Actual behavior

n/a

### Steps to reproduce behavior

n/a

**Comment by cclerget** [comment]
Hi @LiamBindle , never tested, but I believe if you have an OMPI version in container above or similar to host version (starting from 2.x), that should work. The main concern with MPI is when you want to use Infiniband fabric, actually it requires to install Infiniband userspace libraries of your fabric in container

**Comment by Amjadhpc** [comment]
Hi @LiamBindle  
I have tested the above using singularity 2.6.0. I compiled openmpi -3.1.2 on host using intel C compiler . Mpirun that i run from host is linked with intel . The program inside the container is compiled by gcc . I tested it with mpi_ring.c example found in openmpi examples.
It is working without any issues.
Have not tested with  infiniband yet

**Comment by LiamBindle** [comment]
Thanks for your response. @Amjadhpc, thanks for running that test--that answers my question.

I will close this issue.
