### ISSUE TITLE
How to prove a job is running in Singularity container...?

### ISSUE THREAD

**Issue by caot** [apptainer/singularity#1866]
This is not about any errors, however I would like to understand how to prove a job is running not in `OS kernel` but in `Singularity container...`?

```
[user@node1001 pkgs]$ singularity shell hello-world.simg
Singularity: Invoking an interactive shell within container...

Singularity hello-world.simg:~/pkgs> 
```

**Comment by geonmo** [comment]
@caot How about to use "echo $SINGULARITY_CONTAINER"?
```bash
Singularity 58ddbfb2781734c7b469f5e93372c1f184dea1933aabf09d9628644a6dddc0:~> echo $SINGULARITY_CONTAINER
58ddbfb2781734c7b469f5e93372c1f184dea1933aabf09d9628644a6dddc0
```

**Comment by jmstover** [comment]
The easiest way is to look at the namespace you're running in. For example, look at:  `ls -l /proc/self/ns/` ; and compare that to `ls -l /proc/1/ns/`. Basically, the mount (mnt) namespace should be different under normal usage.

You can also run with the `-p` option to run in a new pid namespace. If you want to go all out, run with `--containall`. That will drop you into new namespaces for ipc, mnt, and pid.

**Comment by caot** [comment]
@geonmo No, `echo $SINGULARITY_CONTAINER` only shows up the current container name.

**Comment by ArangoGutierrez** [comment]
You could take a look to this example:
https://github.com/ArangoGutierrez/Singularity-tutorial.github.io#using-shell-to-explore-and-modify-containers 

Remember is not a different `Host kernel` but a different `Host OS`, that's the magic of containers you can swap up the OS with the same kernel underneath, which allows you to leverage all the host hardware.

**Comment by caot** [comment]
@ArangoGutierrez Thanks, that helps.

**Comment by ArangoGutierrez** [comment]
@caot feel free to close this issue if that solves your question ;)
