### ISSUE TITLE
3.0: cannot shell into a container from docker hub

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#1868]
## Version of Singularity:
```
$ singularity --version
singularity version 1040d6a9
```
### Expected behavior
```
$ singularity shell docker://ubuntu
Docker image path: index.docker.io/library/ubuntu:latest
Cache folder set to /home/vagrant/.singularity/docker
Creating container runtime...
Exploding layer: sha256:c64513b741452f95d8a147b69c30f403f6289542dd7b2b51dd8ba0cb35d0e08b.tar.gz
Exploding layer: sha256:01b8b12bad90b51d9f15dd4b63103ea6221b339ac3b3e75807c963e678f28624.tar.gz
Exploding layer: sha256:c5d85cf7a05fec99bb829db84dc5a21cc0aca569253f45d1ea10ca9e8a03fa9a.tar.gz
Exploding layer: sha256:b6b268720157210d21bbe49f6112f815774e6d2a6144b14911749fadfdb034f0.tar.gz
Exploding layer: sha256:e12192999ff18f01315563c63333d7c1059cd8e64dffe75fffe504b95eeb093c.tar.gz
Exploding layer: sha256:c6a9ef4b9995d615851d7786fbc2fe72f72321bee1a87d66919b881a0336525a.tar.gz
Singularity: Invoking an interactive shell within container...

Singularity ubuntu:~>
```
### Actual behavior
```
$ singularity shell docker://ubuntu
FATAL:   container creation failed: stat /home/david/docker:/ubuntu: no such file or directory
```
### Steps to reproduce behavior
```
$ singularity shell docker://ubuntu
```

**Comment by GodloveD** [comment]
Same goes for other action commands.

**Comment by lfaino** [comment]
Hi,
I have the same problem. I`m not able to download a docker image that is working fine on v2.6.0

Cheers
Luigi

**Comment by gmkurtzer** [comment]
As we re-add this feature into 3.0, I'd like to see it implemented as follows:

If the docker container has not already been cached, we build it into a SIF file automatically, and then all subsequent calls to any actions (shell, exec, run, test, etc..) will be able to reference that SIF file. We do still need to figure out the caching mechanism and logic around converting a `docker://....` into a locally cached SIF file in `~/.singularity/...`.

**Comment by GodloveD** [comment]
It seems that this is not really fixed yet.  I'm going to re-open until it the fix is more stable.
