### ISSUE TITLE
Failure to write to /dev/null or read from /dev/urandom during container build process

### ISSUE THREAD

**Issue by McGlaargle** [apptainer/singularity#1875]
## Version of Singularity:

2.5.2

### Expected behavior

During a build of a new container, I expect things like /dev/null and /dev/urandom to be accessible / available for their specified function.

### Actual behavior

During a build of a new container, I get a lot of permission denied errors with processes when installing a variety of packages from yum that want to access /dev/null or /dev/urandom (sometimes other devices)

Also, I need to deploy some software written in nodejs inside of the container.  npm expects to be able to open /dev/urandom in O_RDONLY|O_NOCTTY|O_NONBLOCK mode.  Failure to open /dev/urandom results in npm hanging forever.  This makes it impossible to deploy nodejs into a singularity container using the normal mechanism.

npm stack trace info:
open("/dev/urandom", O_RDONLY|O_NOCTTY|O_NONBLOCK) = -1 EACCES (Permission denied)
open("/dev/random", O_RDONLY|O_NOCTTY|O_NONBLOCK) = -1 EACCES (Permission denied)

I see a lot of these when installing things with yum:
/var/tmp/rpm-tmp.yOMaN1: line 5: /dev/null: Permission denied
/var/tmp/rpm-tmp.yOMaN1: line 6: /dev/null: Permission denied
/var/tmp/rpm-tmp.yOMaN1: line 7: /dev/null: Permission denied
/var/tmp/rpm-tmp.VccZ6d: line 1: /dev/null: Permission denied

### Steps to reproduce behavior

During container build, in the %post section, run the following commands:
yum -y install nodejs
npm i -g npm

The singularity build will now hang forever with npm trying to read from /dev/urandom

During container build, yum install some random package that calls /dev/null (cvs or glibc-devel for example)

**Comment by jmstover** [comment]
Hi @McGlaargle ,

  Here's what I get ... Needed to modify it a bit to do so:
```
yum -y install epel-release
yum -y install nodejs
npm i -g npm
```

But this is my error output from that:
```
17691 verbose stack Error: EEXIST: file already exists, mkdir '/usr/lib/node_modules/npm/node_modules/fs-write-stream-atomic'
17691 verbose stack     at Error (native)
```
Running:
```
$ /usr/local/singularity/2.5.2/bin/singularity --version
2.5.2-HEAD.b258b65
```

I used docker `centos:latest` as the base... I don't know what you were using.

**Comment by McGlaargle** [comment]
I'm using a centos 6 singularity container to bootstrap this container from a Fedora host.  So, maybe it is the fact that I have a container in a container that is causing the problem. Let me try running it on a native host.

**Comment by McGlaargle** [comment]
Confirmed.  The whole thing falls apart when bootstrapping a new container from inside of an existing container.  How very inconvenient for me...

**Comment by jmstover** [comment]
Yeah ... This doesn't surprise me because of how the containers operate and restrictions they put in place.
