### ISSUE TITLE
installation impossible using current instructions (autogen.sh not included in master branch)

### ISSUE THREAD

**Issue by kadepettie** [apptainer/singularity#1876]
Installation instructions need to be updated since they don't work as currently written (autogen.sh not in singularity directory)
https://www.sylabs.io/guides/2.6/user-guide/quick_start.html#installation

## Version of Singularity:

2.6.0

### Expected behavior

autogen.sh to be included since it is part of every installation method

### Actual behavior

autogen.sh does not exist and therefore can't be executed

### Steps to reproduce behavior

$ git clone https://github.com/singularityware/singularity.git

$ cd singularity

$ ./autogen.sh
-bash: ./autogen.sh: No such file or directory

**Comment by jmstover** [comment]
Hi @kadepettie ,

Argh... I missed the quickstart when we made change. See:

https://github.com/singularityware/singularity-userdocs/blob/master/installation.rst#install-from-a-tag

-J

**Comment by kadepettie** [comment]
Thanks for the quick reply! Would helpful to have these instructions on the quick install page as well since those don't work as written.

After proceeding just FYI, I'm running into the issue described here: 

https://github.com/singularityware/singularity/issues/1401

but the workaround doesn't work for me.

**Comment by bauerm97** [comment]
@kadepettie Are you attempting to install a `2.x` series release then? Looking at that issue you posted, you could maybe try to use this instead:

`export CFLAGS="$(pkg-config --cflags libarchive-devel) $(pkg-config --libs-only-L libarchive-devel) $CFLAGS "`

*Or `libarchive-dev` on ubuntu/debian based systems
