### ISSUE TITLE
Bind flags to environment variables

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#1882]
## Version of Singularity:

```
$ singularity --version
singularity version 3.0.0-alpha.1-117-gc297513f
```

### Expected behavior

Most if not all of the flags in Singularity can also be controlled via environment variables.  For instance, the `SINGULARITY_BINDPATH` variable allows me to do this.
```
$ ls /data
foo

$ export SINGULARITY_BINDPATH=/data:/mnt

$ singularity exec my_container ls /mnt
foo
```

### Actual behavior

```
$ export SINGULARITY_BINDPATH=/data:/mnt

$ singularity exec my_container ls /mnt
```

### Steps to reproduce behavior

Try using environment variables to control flags.

**Comment by bauerm97** [comment]
Also just worth noting is that we need to consider which environment variables that were "supported" in 2.x we want to carry through to 3.0. In 2.x these environment variables effected the behavior as a side-effect of the way we dealt with flags being set (we set the value of the flags in env variables always). This meant we didn't always intend for a user to be able to set the value of the flag with that particular environment variable

**Comment by DrDaveD** [comment]
SINGULARITY_BINDPATH is an especially important one.  I know that many grid projects depend on it.  Please make that one a priority.
