### ISSUE TITLE
platform restrictions not documented

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#19]
I couldn't see it noted anywhere that singularity is (currently?) x86_64-specific, as I realized when trying to build a range of Fedora packages.

Also it might be useful to have information on the versions of Linux that will/won't support it for common distributions.  Specifically RHEL5's isn't good enough -- we still have such a cluster... -- but I don't know about the oldest supported Debian and SuSE.

**Comment by gmkurtzer** [comment]
Hi Dave,

Very good points. I've been testing and developing on x86_64 only but I would assume that x86 should also work but you are right about other arches. I will document that and put the exclusive arches in the specfile. 

Lastly, I believe it should work on most Linux distributions. I have a work around a in place that _should_ make it work on older distributions (like RHEL5) but my testing ability here is somewhat limited, specifically for non RH distributions. But I do know that others have tested it on Mint, Ubuntu, Lubuntu, Debian proper, and even Slackware. 

What have you found as far as build / runtime compatibility?

Thanks!

Sent from my iPhone

**Comment by loveshack** [comment]
"Gregory M. Kurtzer" notifications@github.com writes:

> Hi Dave,
> 
> Very good points. I've been testing and developing on x86_64 only but
> I would assume that x86 should also work

It fails on register names.  There's a build log from an older packaging:
https://copr-be.cloud.fedoraproject.org/results/loveshack/livhpc/epel-6-i386/00175787-singularity/build.log.gz

> but you are right about other
> arches. I will document that and put the exclusive arches in the
> specfile.

For what it's worth, I have a modified spec that should pass review for
Fedora, which I could submit for review.

> Lastly, I believe it should work on most Linux distributions. I have a
> work around a in place that _should_ make it work on older
> distributions (like RHEL5) but my testing ability here is somewhat
> limited, specifically for non RH distributions.

I can test on x86_64 RH5, if it helps, though it's not terribly
important.

> But I do know that
> others have tested it on Mint, Ubuntu, Lubuntu, Debian proper, and
> even Slackware.
> 
> What have you found as far as build / runtime compatibility?

Someone with a brain would have suggested a configure change like this
to test the architecture and the failure he found on RH5...

**Comment by gmkurtzer** [comment]
Sent from my iPhone

> On Apr 16, 2016, at 10:25 AM, Dave Love notifications@github.com 
> It fails on register names. There's a build log from an older packaging:
> https://copr-be.cloud.fedoraproject.org/results/loveshack/livhpc/epel-6-i386/00175787-singularity/build.log.gz

Ohhhh, I know exactly what that is! Sheesh I coded up the Singularity ftrace a few months ago and I forgot that I did code it explicitly for x86_64. Ptrace is not the easiest to code against due to the sparse documentation especially for multiarch support.... But I'll get a fix in there for Singularity 1.1!

> > but you are right about other
> > arches. I will document that and put the exclusive arches in the
> > specfile.
> 
> For what it's worth, I have a modified spec that should pass review for
> Fedora, which I could submit for review.

Yes please!

> > Lastly, I believe it should work on most Linux distributions. I have a
> > work around a in place that _should_ make it work on older
> > distributions (like RHEL5) but my testing ability here is somewhat
> > limited, specifically for non RH distributions.
> 
> I can test on x86_64 RH5, if it helps, though it's not terribly
> important.

I believe Tru (from the Centos team) ran it on x64 Centos 5 successfully. That was why I was confused in that it should work. So quickly I've forgotten about 32 bit. Lol

> > But I do know that
> > others have tested it on Mint, Ubuntu, Lubuntu, Debian proper, and
> > even Slackware.
> > 
> > What have you found as far as build / runtime compatibility?
> 
> Someone with a brain would have suggested a configure change like this
> to test the architecture and the failure he found on RH5...

Haha, someone with a brain wouldn't have coded just for 64bit. Oops!!

I agree that a configure test and some defines would be best for fixing this. I'll get on that shortly (right after I build up a 32 bit VM lol).

Thanks again!

**Comment by loveshack** [comment]
The rubbish tracker dropped the patch from the mail, grr.

```
index 58ea383..8c422ec 100644
--- a/configure.ac
+++ b/configure.ac
@@ -9,6 +9,12 @@ if test -z "$prefix" -o "$prefix" = "NONE" ; then
 fi
 AC_SUBST(PREFIX, $prefix)

+AC_CANONICAL_TARGET
+case $target_cpu in
+  x86_64) : ;;
+  *) AC_MSG_ERROR([Architecture $target_cpu not supported]) ;;
+esac
+
 AC_PROG_INSTALL
 AM_INIT_AUTOMAKE
 AC_PROG_LIBTOOL
@@ -96,6 +102,9 @@ AC_COMPILE_IFELSE([AC_LANG_PROGRAM([[#define _GNU_SOURCE
                       ]
                   )

+AC_CHECK_DECLS([MS_PRIVATE,MS_REC], [],
+               [AC_MSG_ERROR([Required mount(2) flags not available])],
+               [[#include <sys/mount.h>]])

 AC_SUBST(NAMESPACE_DEFINES)

```

(I'm surprised LD_PRELOAD isn't robust enough ; perhaps it's worth recording why it needs ptrace?)

**Comment by gmkurtzer** [comment]
This should work fine on 32 bit once I get the correct registers defined for ftrace. Can you do me a favor, I don't have a 32 bit system handy. Can you tell me what the value of $(target_cpu) and/or $(build_cpu) is in the produced Makefile? Hopefully it is something simple like i386 instead of i?x86! LOL

Thanks!

**Comment by gmkurtzer** [comment]
I didn't follow your comment about LD_PRELOAD... Are you suggesting to preload a library to monitor for calls to open() instead of using ptrace?

Hrmm... If so, that is an interesting idea. It would solve a few problems as I have them now with regards to applications forking and not knowing how to follow them easily with ptrace.

**Comment by loveshack** [comment]
You wrote: 

> This should work fine on 32 bit once I get the correct registers
> defined for ftrace.

Sure, and presumably ia32 would normally only be relevant to run old
stuff without 32-bit libraries installed.

> Can you do me a favor, I don't have a 32 bit
> system handy. Can you tell me what the value of $(target_cpu) and/or
> $(build_cpu) is in the produced Makefile? Hopefully it is something
> simple like i386 instead of i?x86! LOL

The glob-style match is "i?86":

$ linux32 ./config.guess 
i686-pc-linux-gnu

**Comment by loveshack** [comment]
You wrote: 

> I didn't follow your comment about LD_PRELOAD... Are you suggesting to
> preload a library to monitor for calls to open() instead of using
> ptrace?

Yes, as normal for i/o profiling or faking userland filesystems.  I
assumed ptrace was preferable somehow, like finessing scripts clobbering
LD_PRELOAD, which I've never got round to trying to subvert.

> Hrmm... If so, that is an interesting idea. It would solve a few
> problems as I have them now with regards to applications forking and
> not knowing how to follow them easily with ptrace.

Is whatever "strace -f -e open" does not reliable?

**Comment by gmkurtzer** [comment]
Sent from my iPhone

> On Apr 18, 2016, at 6:12 AM, Dave Love notifications@github.com wrote:
> 
> You wrote: 
> 
> > I didn't follow your comment about LD_PRELOAD... Are you suggesting to
> > preload a library to monitor for calls to open() instead of using
> > ptrace?
> 
> Yes, as normal for i/o profiling or faking userland filesystems. I
> assumed ptrace was preferable somehow, like finessing scripts clobbering
> LD_PRELOAD, which I've never got round to trying to subvert.

Have you come across many run scripts that clobber LD_PRELOAD in practice?

> > Hrmm... If so, that is an interesting idea. It would solve a few
> > problems as I have them now with regards to applications forking and
> > not knowing how to follow them easily with ptrace.
> 
> Is whatever "strace -f -e open" does not reliable? 

The first implementation I wrote used strace from the host system but it was almost impossible to parse from system to system. I had it working on a couple of different OSes and then would find a different version of Ubuntu or slack that my parser would not support. 

This was actually why I ended up using ptrace instead of preloading a library as I was emulating strace. 

The documentation is lacking for ptrace so the idea of using a straight forward LD_PRELOAD is an interesting one. I'm concerned about the point you bring up but wondering how often that would come up. Also considering the limitations of what I'm doing now and balancing the pros and cons against preloading. 

Thoughts?

**Comment by gmkurtzer** [comment]
Sent from my iPhone

> On Apr 18, 2016, at 6:11 AM, Dave Love notifications@github.com 
> 
> > Can you do me a favor, I don't have a 32 bit
> > system handy. Can you tell me what the value of $(target_cpu) and/or
> > $(build_cpu) is in the produced Makefile? Hopefully it is something
> > simple like i386 instead of i?x86! LOL
> 
> The glob-style match is "i?86":
> 
> $ linux32 ./config.guess 
> i686-pc-linux-gnu

Ahh ok. I'll glob it in the configure script and export a define down to the C code then.

Thanks!

**Comment by gmkurtzer** [comment]
So, I wrote a quick library that masks the open() and dlopen() system calls and prints the associated file names. It is working generally as expected except your surmise about programs interfering with the environment and disabling LD_PRELOAD was accurate and leading to reliability issues.

Ftrace should be fixed now to work on 32 bit and as long as we get it working for forks, it should be more reliable then the preload method. If you can test this from master, and confirm that 32 bit is working and close the ticket, that would be appreciated.

Thanks for the great idea, and pointing out the limitation on 32bit which I overlooked!

Greg

**Comment by loveshack** [comment]
You wrote: 

> Ahh ok. I'll glob it in the configure script and export a define down
> to the C code then.

Just use

  #if **x86_64**
  ...
  #elif **i386**
  ...

**i386** is pre-defined for -m32 by any vaguely-recent gcc.

**Comment by loveshack** [comment]
You wrote: 

> > Is whatever "strace -f -e open" does not reliable? 
> 
> The first implementation I wrote used strace from the host system but
> it was almost impossible to parse from system to system. I had it
> working on a couple of different OSes and then would find a different
> version of Ubuntu or slack that my parser would not support.

I meant specifically the fork-following.  I'm surprised at the
variation, though.  On everything I have from RHEL5 through to Debian
testing/Fedora rawhide VMs, the only variation I see is whether or not
there's a prefix after a fork.  But I haven't slack-ed for a very long
time.

> This was actually why I ended up using ptrace instead of preloading a
> library as I was emulating strace.

I assumed there was a good reason.  You could always bundle a specific
(cut down?) strace if necessary, preferably making it easy to unbundle
in distribution packages.

> The documentation is lacking for ptrace so the idea of using a
> straight forward LD_PRELOAD is an interesting one. I'm concerned about
> the point you bring up but wondering how often that would come
> up.

I can't really say, as people here basically don't do things like
profiling.  However, clobbering LD_PRELOAD at least wouldn't be relevant
for tracing perl/python module loading, and if specgen doesn't work
properly, I guess it's not the end of the world.  It seems relatively
unlikely a script would trash the variable unless it was set up for a
filesystem like cruise or pvfs, in which case it won't be portable
anyway.  "Just don't do that"?

> Also considering the limitations of what I'm doing now and
> balancing the pros and cons against preloading.
> 
> Thoughts?

**Comment by gmkurtzer** [comment]
On Mon, Apr 18, 2016 at 11:00 AM, Dave Love notifications@github.com
wrote:

> You wrote:
> 
> > Ahh ok. I'll glob it in the configure script and export a define down
> > to the C code then.
> 
> Just use
> 
> #if **x86_64**
> ...
> #elif **i386**
> ...
> 
> **i386** is pre-defined for -m32 by any vaguely-recent gcc.
> 
> Ahhh, that would make it light years easier! But considering I just coded
> it up in configure.ac and tossing those defines into ftrace.c, I wonder if
> there is any advantage using the predefines?

(BTW, it seems that Github striped out the #if's)

## 

Gregory M. Kurtzer
Technical Lead and HPC Systems Architect
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by gmkurtzer** [comment]
On Mon, Apr 18, 2016 at 11:02 AM, Dave Love notifications@github.com
wrote:

> You wrote:
> 
> > > Is whatever "strace -f -e open" does not reliable?
> > 
> > The first implementation I wrote used strace from the host system but
> > it was almost impossible to parse from system to system. I had it
> > working on a couple of different OSes and then would find a different
> > version of Ubuntu or slack that my parser would not support.
> 
> I meant specifically the fork-following. I'm surprised at the
> variation, though. On everything I have from RHEL5 through to Debian
> testing/Fedora rawhide VMs, the only variation I see is whether or not
> there's a prefix after a fork. But I haven't slack-ed for a very long
> time.

I don't recall exactly what the differences were, but I ended up just
deciding to code exactly what I needed with ptrace. So far (with the
exception of my 32 bit blunder), it has worked very reliably and I have a
big TODO on figuring out how to track forks.

> > This was actually why I ended up using ptrace instead of preloading a
> > library as I was emulating strace.
> 
> I assumed there was a good reason. You could always bundle a specific
> (cut down?) strace if necessary, preferably making it easy to unbundle
> in distribution packages.
> 
> > The documentation is lacking for ptrace so the idea of using a
> > straight forward LD_PRELOAD is an interesting one. I'm concerned about
> > the point you bring up but wondering how often that would come
> > up.
> 
> I can't really say, as people here basically don't do things like
> profiling. However, clobbering LD_PRELOAD at least wouldn't be relevant
> for tracing perl/python module loading, and if specgen doesn't work
> properly, I guess it's not the end of the world. It seems relatively
> unlikely a script would trash the variable unless it was set up for a
> filesystem like cruise or pvfs, in which case it won't be portable
> anyway. "Just don't do that"?

In just my 30 minutes of testing this, I found that there were several
use-cases that completely just didn't work. Also, it wouldn't catch
libraries that are dlopen'ed consistently. I'm not sure, and perhaps if I
spent more time with it I'll figure it out but... Considering the
environment is so easy to manipulate by a script or program I'm tempted not
to want to rely on LD_PRELOAD especially when ftrace seems to work so
reliably.

Again, great ideas! Thank you!

## 

Gregory M. Kurtzer
Technical Lead and HPC Systems Architect
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by loveshack** [comment]
You wrote: 

> I don't recall exactly what the differences were, but I ended up just
> deciding to code exactly what I needed with ptrace. So far (with the
> exception of my 32 bit blunder), it has worked very reliably and I have a
> big TODO on figuring out how to track forks.

Apart from strace, fakeroot-ng is another program I know does that and
may be a simpler example, as well as for architecture support.

> In just my 30 minutes of testing this, I found that there were several
> use-cases that completely just didn't work.

I'd be interested to know which, as they'll break various things, but I
guess this isn't the place to discuss it...  I'd have expected not
following forks to be more of a problem.

> Also, it wouldn't catch
> libraries that are dlopen'ed consistently. I'm not sure, and perhaps if I
> spent more time with it I'll figure it out but... Considering the
> environment is so easy to manipulate by a script or program I'm tempted not
> to want to rely on LD_PRELOAD especially when ftrace seems to work so
> reliably.

**Comment by gmkurtzer** [comment]
Singularity ftrace now follows clones, forks, and threads. WAHOOOOOO!

The changes are not horribly bad, but without proper documentation for ptrace plus it being a somewhat moving target made it frustrating. But... it seems to be working properly now. Feel free to test on both 32 and 64 bit.

Closing ticket, but if you find any issues please don't hesitate to reopen.

Thanks!
