### ISSUE TITLE
Make rpmbuild create rpm with Version matching release tag

### ISSUE THREAD

**Issue by tcooper** [apptainer/singularity#190]
## Summary

Related to #131 and ultimately the choice of tag format please consider modifying inputs to the RPM build process so that the Version and/or Release of the generated RPM increment appropriately.

Currently all 2.x tagged releases produce an RPM with same Version and Release which prevents a simple update.
### singularity-2.1

```
[tcooper@dev singularity-2.1]$ rpm -q --queryformat %{NAME}-%{VERSION}-%{RELEASE}.%{ARCH} -p /home/tcooper/rpmbuild/RPMS/x86_64/singularity-2.1-0.1.el6.x86_64.rpm
singularity-2.1-0.1.el6.x86_64
```
### singularity-2.1.1

```
[tcooper@dev singularity-2.1.1]$ rpm -q --queryformat %{NAME}-%{VERSION}-%{RELEASE}.%{ARCH} -p /home/tcooper/rpmbuild/RPMS/x86_64/singularity-2.1-0.1.el6.x86_64.rpm
singularity-2.1-0.1.el6.x86_64
```
### singularity-2.1.2

```
 [tcooper@dev singularity-2.1.2]$ rpm -q --queryformat %{NAME}-%{VERSION}-%{RELEASE}.%{ARCH} -p /home/tcooper/rpmbuild/RPMS/x86_64/singularity-2.1-0.1.el6.x86_64.rpm
singularity-2.1-0.1.el6.x86_64
```

A minimal change (assuming the git tag _is_ the Version you want to use) that produces an RPM with an updated Version is...

```
[tcooper@dev singularity-2.1.2]$ diff -Naur configure.ac.orig configure.ac
--- configure.ac.orig   2016-08-10 11:40:18.031028845 -0700
+++ configure.ac    2016-08-10 11:30:27.362370439 -0700
@@ -1,5 +1,5 @@
AC_PREREQ(2.59)
-AC_INIT([singularity],[2.1],[gmkurtzer@lbl.gov])
+AC_INIT([singularity],[2.1.2],[gmkurtzer@lbl.gov])


 if test -z "$prefix" -o "$prefix" = "NONE" ; then
```

Followed by...

```
[tcooper@dev singularity-2.1.2]$ autoconf configure.ac > configure
```

This will update the `singularity.spec` file appropriately...

```
$ egrep "Version:|Release:" singularity.spec
Version: 2.1.2
Release: %{_rel}%{?dist}
```

...and generate an RPM with an updated Version following your documented RPM build sequence...

```
[tcooper@dev singularity-2.1.2]$ rpm -q --queryformat %{NAME}-%{VERSION}-%{RELEASE}.%{ARCH} -p /home/tcooper/rpmbuild/RPMS/x86_64/singularity-2.1.2-0.1.el6.x86_64.rpm
singularity-2.1.2-0.1.el6.x86_64
```

It's really your choice whether you want the Version or Release value to change but one of them needs to increase if the RPM is expected to be updated instead of reinstalled on the target host.

I don't know much about `.deb` creation for Debian but a similar change may also be needed there if/when you choose to add support for creating Debian packages from the Singularity source.

**Comment by gmkurtzer** [comment]
Yes, very good catch! I have not been bumping the autotools release to reflect the tagged releases. I will do that for future releases! Apologies, and thanks for the reminder!
