### ISSUE TITLE
Option to bind full /dev with contain

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#1907]
With 3.0 have an option to skip the minimal dev if `--contain`/`--containall` is used.

For example:

  `singularity exec --bind-dev -c [...]` 

Will do the normal `/dev` bind mounting instead of the minimal `/dev`. This _should not_ override the configuration setting of:  `mount dev = minimal`

**Comment by gmkurtzer** [comment]
This is what I would like to see happen:
```
singularity exec -c -B /dev/ container.sif true
```

**Comment by GodloveD** [comment]
So, the reason for this change is that some people (@paulo7777 ) need to use `--contain` in production but also need infiniband to work and infiniband breaks if the proper `/dev` is not mounted. 

The problem with @gmkurtzer's solution is that an admin can set either of the following in the `singularity.conf` file and then the user is out of luck:

```
mount dev = minimal

user bind control = no
```

So the question that needs answered @paulo7777 is if this would be OK.  What do the conf files look like in the various environments where you run, and is this change going to work for you?

**Comment by DrDaveD** [comment]
What if only '/dev/infiniband' is wanted with --contain and not all of '/dev'?  Wouldn't it be better to allow just binding individual devices under '/dev'?

**Comment by GodloveD** [comment]
I agree that would be better @DrDaveD.  In general I think it would be nice if individual files can be bind mounted.  @cclerget what do you think about allowing users to bind individual files instead of directories?

**Comment by cclerget** [comment]
@GodloveD @DrDaveD #1927 updated to bind devices individually

**Comment by paulo7777** [comment]
@DrDaveD  `-c -B /dev` works for me.
I don't see `mount dev = minimal` in the various environments where I run, because they need IB working inside the container. Also they are not using `user bind control = no` in the various environments where I run.
