### ISSUE TITLE
ERROR Authentication error when pulling image from local docker registry

### ISSUE THREAD

**Issue by zhcf** [apptainer/singularity#1910]
## Version of Singularity:

2.5.1-dist

### Expected behavior

SINGULARITY_NOHTTPS=true singularity pull docker://localhost:5000/localtf:latest
This command should pull the docker image from local registry to create a new singularity image.
### Actual behavior

SINGULARITY_NOHTTPS=true singularity pull docker://localhost:5000/localtf:latest 
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
ERROR Authentication error, exiting.
Cleaning up...
ERROR: pulling container failed!

### Steps to reproduce behavior

Write here.

**Comment by zhcf** [comment]
SINGULARITY_NOHTTPS=true singularity pull docker://localhost:5000/localtf:latest
But this is worked in singularity 2.4.5

**Comment by zhcf** [comment]
sorry, forget to push the image to docker local registry when using singularity pull. will close it

**Comment by GodloveD** [comment]
Sorry nobody got back to you about this @zhcf.  Thanks for letting everyone know what the problem was.
