### ISSUE TITLE
Manipulating Unbound Directories Within Container

### ISSUE THREAD

**Issue by tjhendrickson** [apptainer/singularity#1911]
## Version of Singularity:
2.5.1

### Expected behavior

A script within my singularity container attempts to write a file into a software distribution directory within the /opt directory. I've set privileges as 777.

### Actual behavior

The script cannot write the file, and an error message is pushed "this is a read only system".

**Comment by GodloveD** [comment]
Heya @tjhendrickson.  squashfs, default container file format for 2.4 and great iirc, is a read only file format.  You will need to build your container into a sandbox and mount it with the `--writable` flag I think if you want to be able to write to it.
