### ISSUE TITLE
Perl library not working properly for images pulled from DockerHub using Singularity v2.5.1

### ISSUE THREAD

**Issue by zhouyangyu** [apptainer/singularity#1913]
## Version of Singularity:

2.5.1

### Expected behavior
`umask 22`
`/path/to/singularity-2.5.1/bin/singularity pull docker://leukgen/click_mergevcfs:v0.3.2`
`singularity exec click_mergevcfs-v0.3.2.simg bash`
`perl -e 'use Bio::DB::HTS'`
Output:
*nothing*

### Actual behavior
`umask22`
`/path/to/singularity-2.5.1/bin/singularity pull docker://leukgen/click_mergevcfs:v0.3.2`
`singularity exec click_mergevcfs-v0.3.2.simg bash`
`perl -e 'use Bio::DB::HTS'`
Output:
`Can't load '/usr/local/lib/perl/5.18.2/auto/Bio/DB/HTS/HTS.so' for module Bio::DB::HTS: libhts.so.2: cannot open shared object file: No such file or directory at /usr/lib/perl/5.18/DynaLoader.pm line 184.
 at -e line 1.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.`

However, if you pull the docker image using singularity version 2.4.2, the actual behavior matches the expected behavior:
`umask 22`
`/path/to/singularity-2.4.2/bin/singularity pull docker://leukgen/click_mergevcfs:v0.3.2`
`singularity exec click_mergevcfs-v0.3.2.simg bash`
`perl -e 'use Bio::DB::HTS'`
Output:
*nothing*

### Comments
There seems to be something wrong with singularity-2.5.1 converting docker images to singularity images.

**Comment by jmstover** [comment]
I just pulled that image... There's

`/usr/local/lib/libhts.so.2` which is a symlink to `libhts.so.1.8` in that same directory. `libhts.so.1.8` doesn't exist.

So in /usr/local/lib there is:
```
libhts.so -> libhts.so.1.8
libhts.so.2 -> libhts.so.1.8
```
`/usr/local/lib/perl/5.18.2/auto/Bio/DB/HTS/HTS.so` links against `libhts.so.2` which is a symlink to a non-existent file.
