### ISSUE TITLE
awk waring with [--nv] arg for commads [shell, run]

### ISSUE THREAD

**Issue by al3x609** [apptainer/singularity#1916]
## Version of Singularity:

2.6.0-HEAD.579c415

### Expected behavior

```
$singularity --nv s.img
This is what happens when you run the container...
```

### Actual behavior

```
singularity  run --nv s.simg
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
awk: warning: escape sequence `\.' treated as plain `.'
This is what happens when you run the container...
```

### Steps to reproduce behavior

when run without [--nv] arg

`$singularity run s.img`
This is what happens when you run the container...

but with [--nv]
for all Singularity recipes show `awk: warning: escape sequence `\.' treated as plain `.'`

___
my Singularity recipe

```
BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum

# If you want the updates (available at the bootstrap date) to be installed
# inside the container during the bootstrap instead of the General Availability
# point release (7.x) then uncomment the following line
#UpdateURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/updates/$basearch/


%runscript
    echo "This is what happens when you run the container..."


%post
    echo "Hello from inside the container"
    yum -y install vim-minimal
```

**Comment by al3x609** [comment]
running shell-debug:

`$singularity -x run --nv s.img`

line [176] and others ...
```
++ for i in '`echo "$SINGULARITY_NV_FILES" | grep -E "\.so"`'
++ basename /usr/lib64/libnvidia-ml.so.367.128
++ awk -F '\.so' '{print $1 ".so"}'
awk: warning: escape sequence `\.' treated as plain `.'
```
___
distro centos 7
`Linux yaje 4.16.11-1.el7.elrepo.x86_64 #1 SMP Tue May 22 15:34:16 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux`
[full log file](https://gist.github.com/al3x609/4df2dbd6255fd95b4bb17b4761dcc756)

**Comment by al3x609** [comment]
https://github.com/al3x609/singularity/blob/579c41508b4eb824c9f00e77a1fbf2b45fb7c637/libexec/functions#L484

You can avoid the warning if remove the backslash with the same result.

` awk -F '.so' '{print $1 ".so"}'`

This isn't a fix; but, I would like to hear your opinion

**Comment by al3x609** [comment]
Im sorry, 
The warning still exists, the solution is remove backslash.
`awk -F '\\.so' '{print $1 ".so"}'`

**Comment by GodloveD** [comment]
Sorry that we've not gotten back to you @al3x609.  This is indeed a problem.  Most of the code is being refactored in Go right now, but I'd like to keep this open to make sure that we don't run into a similar issue.  Thank you.

**Comment by dtrudg** [comment]
This issue is not present with the Go rewrite for 3.x
