### ISSUE TITLE
Missing link in 2.5 & 2.6 user documentation

### ISSUE THREAD

**Issue by jack-morrison** [apptainer/singularity#1919]
## Version of Singularity:

2.5 & 2.6,  User Documentation (PDF & readthedocs)

### Expected behavior
User guide reads smoothly.

### Actual behavior
Looks like there's a missing link or a sentence was partially removed at the 2nd paragraph.
https://www.sylabs.io/guides/2.6/user-guide/introduction.html#the-singularity-usage-workflow

> If you are using OS X or Windows on your laptop, it is recommended to setup Vagrant, and run Singularity from there (there are recipes for this which can be **_found at Once you_** have Singularity installed on your endpoint of choice, this is where you will do the bulk of your container development.

**Comment by jscook2345** [comment]
Jack,

Thanks so much for the report! I fixed these in the singularity-userdocs repo.

https://github.com/singularityware/singularity-userdocs/pull/9
https://github.com/singularityware/singularity-userdocs/pull/10
https://github.com/singularityware/singularity-userdocs/pull/11

**Comment by jchavezlavalle** [comment]
@jack-morrison @jscook2345  thank you so much!

**Comment by jack-morrison** [comment]
Whoops! Sorry for opening this in the wrong repo. I saw the Documentation label here and didn't think twice. Thanks for the fix.
