### ISSUE TITLE
Squashfs support

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#192]
Squashfs is a useful mechanism for creating a space efficient (compressed) file system image.  This is particularly useful for gigantic runtime environments.  This is common for HEP experiments: I recently measured CMS and found that we have 350GB of _active_ releases (inactive releases, I stopped counting around 1TB).  With squashfs, I was able to get the runtime environment to 70GB.

I'd like it if Singularity had the ability to mount these images.

**Comment by gmkurtzer** [comment]
Initial SquashFS support done. As of [master 41fa987]:

```
$ file /tmp/test.sqsh 
/tmp/test.sqsh: Squashfs filesystem, little endian, version 4.0, 51347935 bytes, 4867 inodes, blocksize: 131072 bytes, created: Sat Sep 10 07:53:09 2016
$ singularity shell /tmp/test.sqsh 
Singularity: Invoking an interactive shell within container...

Singularity.test.sqsh> 
```

**Comment by weidendo** [comment]
Not sure this is the right place, as this issue is closed...

I see that "singularity mount x.img mksqashfs ..." is possible to script the conversion
of an image to squashfs. Is this expected to be a stable feature?

**Comment by gmkurtzer** [comment]
Singularity has no means to create a squashfs file system because that requires the `mksquashfs` external command (which is not a requirement). But as long as we have reasonable checks in place to account for that, this could be done.

**Comment by weidendo** [comment]
Ah, the question was not about "mksquashfs", but about being able to put a command after "singularity mount x.img" with the command being executed within the container without dropping me into an interactive shell.
I did not see that behavior mentioned anywhere in the documentation, and just tried by luck (I mentioned "mksquashfs" only because that was my use-case).

**Comment by gmkurtzer** [comment]
Ahh, do you mean like:
```
$ singularity mount /tmp/centos.img env | grep SINGULARITY_MOUNTPOINT
SINGULARITY_MOUNTPOINT=/usr/local/var/singularity/mnt/container
```

;-)

**Comment by weidendo** [comment]
Yes!
Can I put somethink like in my scripts and expect it to be working also for future singularity releases?

**Comment by gmkurtzer** [comment]
Yep! We use that feature of of the backend mount code to do things like `inspect` and `import` and `export`, so this feature will always be supported from 2.3* on. :)

**Comment by weidendo** [comment]
Perfect, thanks!

**Comment by bilke** [comment]
As squashfs is the default format now this should be listed as a requirement (on a Centos 7 host I had to `yum install squashfs-tools`).

**Comment by GodloveD** [comment]
Hi @bilke!  Thanks for the heads up.  Yes we merged a [PR](https://github.com/singularityware/singularity/pull/1246) that @jmstover created a little while back to address this issue.  It's currently in the development branch and will make it's way into a release as development matures.
