### ISSUE TITLE
.autogen.sh and .configure files missing from the directory

### ISSUE THREAD

**Issue by ghltshubh** [apptainer/singularity#1925]
git clone https://github.com/singularityware/singularity.git

cd singularity

git fetch --all

git checkout 2.6.0

./autogen.sh

./configure --prefix=/usr/local

make

sudo make install

Can't install singularity using these steps mentioned in the [documentation](https://www.sylabs.io/guides/2.5/user-guide/quick_start.html#installation).

**Comment by ArangoGutierrez** [comment]
Heya @ghltshubh , sorry for the inconvenient, those steps are for 2.X releases

Here the Updated [INSTALL](https://github.com/singularityware/singularity/blob/master/INSTALL.md) document for the 3.0 version, which is currently on [ALPHA](https://github.com/singularityware/singularity/releases/tag/v3.0.0-alpha.1), so is very unstable. 

if you want a specific release you can do 
```
$ git checkout tags/${version} -b ${version}
```

let me know if this was helpful.

cheers

**Comment by ghltshubh** [comment]
But its mentioned in the documentation of singularity v2.5.x? I guess it wasn't updated.

**Comment by ArangoGutierrez** [comment]
could you point me to the documentation you are reading so we can rise an issue for a fix update.

thanks

**Comment by ghltshubh** [comment]
https://www.sylabs.io/guides/2.5/user-guide/quick_start.html#installation

**Comment by ArangoGutierrez** [comment]
Umm I just ran those lines and worked, could you show me your command line output?

**Comment by ghltshubh** [comment]
I am hitting this error: https://github.com/singularityware/singularity/issues/1401

But when I try the workaround I get 

```
Package libarchive was not found in the pkg-config search path.
Perhaps you should add the directory containing `libarchive.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libarchive' found
Package libarchive was not found in the pkg-config search path.
Perhaps you should add the directory containing `libarchive.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libarchive' found
```

**Comment by ArangoGutierrez** [comment]
I'll PING someone that will probably came out with a fix for this. 
PING -> @jmstover

**Comment by ghltshubh** [comment]
I think I messed up with the requirements. Do you need python 2 or 3 for building from source?

**Comment by GodloveD** [comment]
Heya @ghltshubh.  Sorry, it doesn't look like the quick start version of the documentation is covering the dependancies that must be installed.  Try [these instructions](https://www.sylabs.io/guides/2.5/user-guide/installation.html) instead and see if they are more useful.

**Comment by ghltshubh** [comment]
I think there must be a warning in the quick start section that you need to have these tools installed before going for a quick start. Also documentation for both v2.5 and v2.6 point to the same documentation.

**Comment by GodloveD** [comment]
@devprincess ^^

**Comment by jchavezlavalle** [comment]
Hey @ghltshubh you can find documentation for v2.5 here https://www.sylabs.io/guides/2.5/user-guide/ and for v2.6 here -> https://www.sylabs.io/guides/2.6/user-guide/  of course both versions differ, as on 2.6 you can see new added sections on the left side bar (e.g. Frequently Asked questions and Contributing on v.2.6) Also, I highly suggest reading the warning on "Before you begin" which states you need to install some dependencies before installing a specific version (that is why the libarchive warning there) Check it here: https://www.sylabs.io/guides/2.6/user-guide/installation.html#before-you-begin , Thank you!
