### ISSUE TITLE
GUI apps need web browser

### ISSUE THREAD

**Issue by shengdie** [apptainer/singularity#1926]
## Version of Singularity: 2.6.0
I am using a scientific app whose documentation is html, it needs a web browser to open the docs.
### Expected behavior

Apps can call the web browser of host system.

### Actual behavior

Apps cannot find browser.

### Steps to reproduce behavior

Install any GUI app, use the functions need web browser.

**Comment by GodloveD** [comment]
imho this is not something Singularity should support.  Just like any other apps, the web browser should be installed inside of the container.   This will also require the installation of X11 inside the container.  But as long as all of the pieces are there it should work just fine.
