### ISSUE TITLE
Supporting both CMD and ENTRYPOINT for converted Docker images

### ISSUE THREAD

**Issue by jakirkham** [apptainer/singularity#1929]
Would be nice if Singularity supported both `CMD` and `ENTRYPOINT` of converted Docker images. This can be useful if there are some steps that always should be run at container startup (e.g. in the `ENTRYPOINT`) and default steps than can be optionally replaced (e.g. `CMD`).

As an example from personal experience, it can be quite handy to run all activation scripts in `ENTRYPOINT` and then drop users into a shell set by `CMD`. Though users may want to do different things, than just get a shell (e.g. start a web server). It's handy to ensure the activation scripts still get run so that things behave how the user expects. Otherwise users are stuck hunting through `Dockerfile`s looking for what the `ENTRYPOINT` did (assuming they are able to do even that).

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jakirkham Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Old Singularity repo issues are now closed. If this is still critical please open a new issue in Apptainer repo.

**Comment by jakirkham** [comment]
Do you have a blogpost entry (link) about this change?

**Comment by DrDaveD** [comment]
> Do you have a blogpost entry (link) about this change?

No, it has not been changed.  If you still think it's important, please create an issue in the current repo referring back to this one.

**Comment by jakirkham** [comment]
Sorry maybe that was too vague. My question was about this larger overhaul. Think the blogpost (below) may answer that, but it is possible that I'm still missing things (please feel free to guide me to better resources if so :)

https://apptainer.org/news/community-announcement-20211130/

**Comment by DrDaveD** [comment]
Oh, right.  Yes that's the best explanation of the switch from Singularity to Apptainer.

**Comment by DrDaveD** [comment]
There's also this [documentation in the admin guide](https://apptainer.org/docs/admin/main/singularity_migration.html) that explains the migrating from Singularity to Apptainer and that links to the [user guide discussion on compatibility](https://apptainer.org/docs/user/main/singularity_compatibility.html) between the two.

**Comment by jakirkham** [comment]
Thanks that's very helpful 🙏

Maybe those links are worth including in that blogpost?

**Comment by DrDaveD** [comment]
I don't think we should revise that historical announcement because those guides weren't there at the time, but there should be a news announcement about the 1.0.0 release and the links included there.
