### ISSUE TITLE
Image-based bind mounts

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#193]
I would like to use one image for a the operating system environment (say, CentOS) and another image for a bind mount (say, a HEP-specific runtime).

Why not simply combine the two into a single image?  The HEP runtime can be quite large (a test squashfs for CMS is 77GB): it's really expensive in CPU and disk quota to make a merged version.  If I have two slightly different OS versions, I don't want to keep two copies of the runtime.

**Comment by gmkurtzer** [comment]
Is it possible to throw it into a local directory and make it a bind mount?

**Comment by bbockelm** [comment]
Yeah - that's the other issue: there's a huge number of files, causing inode exhaustion (or at least stress on the metadata server!).  Unfortunately, unprivileged users also cannot mount it into the local directory.

**Comment by gmkurtzer** [comment]
I am thinking the implementation would be a list of image files and a bind point location inside the container (either envar or configuration file). Would that meet your desire?

Is this an urgent need? If so I can push to get it into the 2.2 release.

**Comment by gmkurtzer** [comment]
This wasn't brought into 2.2, nor will it be part of 2.3. I am hoping we can get it in 2.4. LOL

**Comment by GodloveD** [comment]
@bbockelm and @gmkurtzer does the `--overlay` option in development do what you need?  Should we close this issue?

**Comment by GodloveD** [comment]
@bbockelm This should be implemented now correct? 

http://singularity.lbl.gov/docs-overlay

I'm going to close this, but feel free to re-open if you were actually asking for something different.
