### ISSUE TITLE
Problems when running some singularity commands in a directory with a non-ASCII character in its name

### ISSUE THREAD

**Issue by lckarssen** [apptainer/singularity#1938]
## Version of Singularity:
2.4, 2.5, probably 2.6
Tested on Ubuntu 18.04.

### Expected behavior
Running `singularity run shub://vsoch/hello-world` should print `RaawwWWWWWRRRR!!`

### Actual behavior
Instead, this is printed:
```
traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/singularity/python/pull.py", line 74, in <module>
    main()
  File "/usr/lib/x86_64-linux-gnu/singularity/python/pull.py", line 66, in main
    layerfile=LAYERFILE)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/shub/main.py", line 95, in PULL
    image_file = "%s/%s" % (cache_base, image_name)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 40: ordinal not in range(128)
ABORT: Aborting with RETVAL=255
```
### Steps to reproduce behavior
Create a directory with a non-ascii character like è in its name and run the aforementioned command. Running the same command in a directory consisting of pure ASCII characters works fine. The same problem appears when running `singularity pull` as it traverses the same code path.

The problem lies in a couple of functions that don't encode and decode strings to UTF8. 
I managed to get it working by adding a couple of `.encode('utf-8')`s and `.decode('utf-8')`s here and there in `python/pull.py`, `python/shub/main.py` and `python/sutils.py` and could submit a patch if you are interested. I had a quick look at the master branch and the python files don't seem to be present there anymore, so this issue may or may not be solved there.

**Comment by GodloveD** [comment]
Heya @lckarssen thanks for reporting this.  Will be a good thing for us to check in 3.0.

**Comment by dtrudg** [comment]
This should be working properly on Singularity 3.x - tested:

```
dave@piran~/℥ℑℌ♜♛> singularity build ubuntu.sif docker://ubuntu
INFO:    Starting build...
Getting image source signatures
Copying blob 7ddbc47eeb70 skipped: already exists
Copying blob c1bbdc448b72 skipped: already exists
Copying blob 8c3b70e39044 skipped: already exists
Copying blob 45d437916d57 skipped: already exists
Copying config 910b24073d done
Writing manifest to image destination
Storing signatures
2019/11/06 17:07:36  info unpack layer: sha256:7ddbc47eeb70dc7f08e410a6667948b87ff3883024eb41478b44ef9a81bf400c
2019/11/06 17:07:37  info unpack layer: sha256:c1bbdc448b7263673926b8fe2e88491e5083a8b4b06ddfabf311f2fc5f27e2ff
2019/11/06 17:07:37  info unpack layer: sha256:8c3b70e3904492c753652606df4726430426f42ea56e06ea924d6fea7ae162a1
2019/11/06 17:07:37  info unpack layer: sha256:45d437916d5781043432f2d72608049dcf74ddbd27daa01a25fa63c8f1b9adc4
INFO:    Creating SIF file...
INFO:    Build complete: ubuntu.sif
dave@piran~/℥ℑℌ♜♛> cd ..
dave@piran~> singularity run ℥ℑℌ♜♛/ubuntu.sif
Singularity>
```
