### ISSUE TITLE
Getting No valid /bin/sh in container error 

### ISSUE THREAD

**Issue by abushoy** [apptainer/singularity#1939]
## Version of Singularity:

2.6.0-HEAD.579c415
### Expected behavior

start higalss server

### Actual behavior
Getting an error
ERROR  : No valid /bin/sh in container
ABORT  : Retval = 255

### Steps to reproduce behavior

singularity build --sandbox higlass docker://gehlenborglab/higlass
singularity exec higlass  python higlass-server/manage.py

Write here.
I am running sigularity on Vagrant vm operating systems ubuntu 16.04

**Comment by dtrudg** [comment]
Hi @abushoy - that is a very large container!

Could you post the output of `singularity -d build --sandbox higlass docker://gehlenborglab/higlass` ? The `-d` option will give debug output.

There are some weird things that can occur in vagrant VMs, especially if you are using the VirtualBox provider and shared filesystems. Some info about your VM may be useful here also.

**Comment by abushoy** [comment]
@dctrud Thank you for a quick response.

I am running Vagrant on my mac with https://app.vagrantup.com/ubuntu/boxes/xenial64
Also, I ran as a sudo and not. Getting the same error 
Please see below the errors I am getting with debug option on. 
DEBUG   [U=0,P=7125]       main()                                    Extracting docker tar file /root/.singularity/metadata/sha256:cd9064f38c53e0014a8b56d1e183dc62a396d02372bd4ef76c112e22753cc994.tar.gz
ERROR   [U=0,P=7125]       copy_data()                               tar extraction error: Write failed
WARNING [U=0,P=7125]       extract_tar()                             Warning handling tar header: Write failed
ERROR   [U=0,P=7125]       copy_data()                               tar extraction error: Write failed
WARNING [U=0,P=7125]       extract_tar()                             Warning handling tar header: Write failed

**Comment by dtrudg** [comment]
2 most likely things from my experience with Singularity inside vagrant...

(1) you are going out of space in your VM - the conatiner extracts to 2.5G and you'll need temp space for layers and so on also....

```
02:54 PM $ du -sh higlass/
2.5G	higlass/
```
... or (2) you are trying to extract into a directory that was mounted in from your host to the VM. With VirtualBox there are can be issues with symlink creation etc. using the default shared folder provider. If this is the issue, try building into a location that's on the VM image, *not* shared into the VM from the host.

**Comment by abushoy** [comment]
Hi @dctrud, 
I 've built the container on AWS server( Ubuntu 16.04). 
No errors on the build command.

On exec  comand same error:
singularity exec higlass python higlass-server/manage.py
DEBUG   [U=0,P=10745]      action_ready()                            Checking if container is valid at: /usr/local/var/singularity/mnt/container
ERROR   [U=0,P=10745]      action_ready()                            No valid /bin/sh in container
ABORT   [U=0,P=10745]      action_ready()                            Retval = 255
ubuntu@ip-:~/project/higlass/home$ which mksquashfs
/usr/bin/mksquashfs
 
Any other suggestions what I can check on?

**Comment by dtrudg** [comment]
Hi @abushoy - I'm thinking there should be a specific error message if there is a space issue - but could you show the output of `df -h`? There would be usage of `/tmp` during the build, as well as for the final destination of the container.

**Comment by stevekm** [comment]
I have been getting these types of errors a lot; things in PATH not existing, input/output errors trying to use `ls` or similar, `sh` not found, things like `python` not found in Ubuntu, squashfs errors when trying to build or load containers, etc.

I suspect the issue indeed relates to lack of space in the Vagrant VM; in lieu of a real permanent fix, I have started simply deleting the '.vagrant' directory used for the Vagrant VM, and re-building the Vagrant. This seems to fix the errors. Eventually, you will probably have to clear out the old Vagrant VM entries in your VirtualBox as well.

**Comment by abushoy** [comment]
Thank you  @dctrud and @stevekm, 
This time I am running AWS  instance and getting the same error 
udev            488M     0  488M   0% /dev
udev            488M     0  488M   0% /dev
tmpfs           100M  5.8M   94M   6% /run
/dev/xvda1       30G  7.5G   22G  26% /
tmpfs           496M     0  496M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           496M     0  496M   0% /sys/fs/cgroup

**Comment by dtrudg** [comment]
could you paste in the debug output of the `singularity -d build ....` and then a `singularity -d exec .....` on this AWS instance? Sorry this is taking a long time to pin down. I'm afraid the error message is pretty non-specific.

Ubuntu 16.04 official AMI for your AWS instance? Cheers.

**Comment by abushoy** [comment]
Hi @dctrud, 
Thank you for looking into this.  My AWS instance is official  Ubuntu 16.04 AMI 
Attached  log files 

[build.log](https://github.com/singularityware/singularity/files/2372041/build.log)
[exec.log](https://github.com/singularityware/singularity/files/2372025/exec.log)

**Comment by DoaneAS** [comment]
Hi,

Using singularity version 2.6 on CentOS7, I was able to pull the docker container and shell into the container:

```
singularity pull docker://gehlenborglab/higlass:latest
```   

Builds container...

then:
```
singualrity shell $HOME/.singularity/higlass-latest.simg
cd /home/higlass/projects/higlass-server

Singularity higlass-latest.simg:/home/higlass/projects/higlass-server> ./test.sh
rm: cannot remove ‘db_test.sqlite3’: No such file or directory
--2018-09-21 20:35:39--  https://s3.amazonaws.com/pkerp/public/dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.66.3
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.66.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7581760 (7.2M) [binary/octet-stream]
data: Permission denieddata/dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool: No such file or directory

Cannot write to ‘data/dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool’ (No such file or directory).
```

I'm not familiar with higlass, so that's as far as I got.
