### ISSUE TITLE
Remote Build Test Coverage

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#1940]
The acceptance tests in `src/cmd/singularity/build_test.go` don't currently have coverage for the remote build functionality in 3.0. It would be nice to do a basic remote build, something like:

```
singularity build --remote busybox.sif docker://busybox
```
One challenge is the REST endpoints are authenticated with a JWT, so we'd need to figure out how to handle that during testing.

**Comment by dtrudg** [comment]
This will be handled outside of the Singularity code base e2e due to the challenges of dealing with an authentication-required service.
