### ISSUE TITLE
test failure checking for singularity version

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#1943]
The following test fails because `singularity --version` or `singularity version` no longer matches what the behavior was in 2.6.

--- FAIL: TestSingularityVersion (0.00s)
    agent_test.go:16: user agent did not match regexp

Before I can fix the test we should agree on what the contents should be for the version.

**Comment by bauerm97** [comment]
`singularity --version`/`singularity version` should follow [semantic version](https://semver.org/#semantic-versioning-specification-semver) format. There's probably an accepted regexp to check for this somewhere

**Comment by jscook2345** [comment]
This looks like it was fixed
