### ISSUE TITLE
Vagrant for singularityware/singularity-2.5 ?

### ISSUE THREAD

**Issue by stevekm** [apptainer/singularity#1951]
## Version of Singularity:

2.5

### Expected behavior

Create a Vagrant box for Singularity 2.5

### Actual behavior

Cannot create a Vagrant box for Singularity 2.5

### Steps to reproduce behavior

There does not seem to be a Vagrant box available for Singularity version 2.5. 
```
$ vagrant init singularityware/singularity-2.5
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'singularityware/singularity-2.5' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'singularityware/singularity-2.5' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/singularityware/singularity-2.5"]
Error: The requested URL returned error: 404 Not Found
```

Are there any plans for this to be supported? Right now, I am using the Singularity 2.4 Vagrant box, but my HPC cluster is running 2.5, and will be keeping up to date with the latest Singularity versions, so I would like to keep my Vagrant up to date as well when building. Are there plans to keep Vagrant for Singularity up to date with the latest Singularity versions?

**Comment by ygrange** [comment]
Would be great :) 

A workaround is to use the Vagrant file over here (I forked and changed the legacy vagrant repo):
https://github.com/ygrange/singularity-vagrant

You may want to change the version in the line the line `git checkout tags/2.6.0` (to 2.5.0 or  2.5.2).

I realise this is all legacy and therefore unsupported (not sure if version 2.4 is anyhow supported either; since there is not documentation for it on the main page anymore), but it works for me now :).

**Comment by dtrudg** [comment]
Up to date vagrant boxes can be found at https://app.vagrantup.com/sylabs. The historical 2.5 release is present there. Closing.
