### ISSUE TITLE
how to build from bootstrap file using local docker registry

### ISSUE THREAD

**Issue by zhcf** [apptainer/singularity#1955]
This is worked:
SINGULARITY_NOHTTPS=true singularity pull docker://localhost:5000 

The below is failed:

a.bootstrap:
Bootstrap: docker
From: vnc
Registry: localhost:5000

singularity build a.simg a.bootstrap
it will show the urllib2.URLError: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:765)>

How to add SINGULARITY_NOHTTPS in the bootstrap file?

**Comment by dtrudg** [comment]
Hi @zhcf - I'm afraid there is no way to specify using HTTP in the definition file. You will need to set the environment variable for the pull.

**Comment by zhcf** [comment]
After I add the Namespace in the bootstrap file, it is worked.
a.bootstrap:
Bootstrap: docker
From: vnc
Registry: localhost:5000
Namespace:

SINGULARITY_NOHTTPS=true singularity build a.simg a.bootstrap
