### ISSUE TITLE
singularity help my_container.sif should display help for container if available

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#1959]
## Version of Singularity:

```
$ singularity --version
singularity version 19b22932
```

### Expected behavior

```
$ cat my_container.def
Bootstrap: docker
From: busybox

%help
    Some help for this container

$ sudo singularity build my_container.sif my_container.def
Using container recipe deffile: my_container.def
[...snip...]
Cleaning up...

$ singularity help my_container.sif


    Some help for this container
```
### Actual behavior

```
$ singularity help my_container.sif 
Unknown help topic [`my_container.sif`]
Usage:
  singularity [global options...] <command>

Available Commands:
  build       Build a new Singularity container
  capability  Manage Linux capabilities on containers
  exec        Execute a command within container
  instance    Manage containers running in the background
  keys        Manage OpenPGP key stores
  pull        Pull a container from a URI
  push        Push a container to a Library URI
  run         Launch a runscript within container
  shell       Run a Bourne shell within container
  sign        Attach cryptographic signatures to container
  verify      Verify cryptographic signatures on container
  version     Show application version
```

### Steps to reproduce behavior

Try building a container using a def file with a `%help` section and then running the help command.

**Comment by bauerm97** [comment]
@ArangoGutierrez If you want to work on this, for 3.0 it's enough for you to simply use the singularity engine the same way as `src/cmd/singularity/cli/actions.go` calls the starter, but simply executing a different command (something to print out the container help file inside the container). 

Moving forward to 3.1, we should implement an Engine which only mounts the container filesystem and prints out the help.

**Comment by ArangoGutierrez** [comment]
@bauerm97  Agree on the first part. ;) 

for the next move, I think the `%help` section could be stored on a SIF data objet, so we don't have to mount the entire image to print a help message.
