### ISSUE TITLE
3.0: Instance issues

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#1963]
## Version of Singularity:

3.0.0-alpha.1-217-g41c253f

### Expected behavior

Instance `startscript` runs
Instance doesn't hang

### Actual behavior

The `startscript` isn't ran on:  `singularity instance start image.sif myname`

When doing something like:
```
singularity instance start -B httpd:/usr/local/apache2/htdocs -B httpd.logs:/usr/local/apache2/logs httpd.sif httpd
```
hangs.  The process `Singularity instance: jason [httpd]` exists ... but the CLI never returns. In the `httpd.err` log file, there is:

```
DEBUG   [U=1000,P=31220]    mountGeneric()    Skipping mount, host source /httpd doesn't exist
  [ ... ]
ERROR    [U=1000,P=31220]    SMaster()    container cleanup failed: no instance found with name httpd
FATAL    [U=1000,P=31220]    SMaster()     container creation failed: mount error: can't remount /usr/local/apache2/htdocs: invalid argument
```

*Without* the Bind mounts:
```
singularity instance start httpd.sif httpd
```

The instance starts up perfectly fine.

Or running:
```
singularity shell -B httpd:/usr/local/apache2/htdocs -B httpd.logs:/usr/local/apache2/logs httpd.sif
```
the container starts as expected.

**Comment by cclerget** [comment]
Fixed by #1984 and #1996
