### ISSUE TITLE
How to send args to an scpript- instance in %startscript ?

### ISSUE THREAD

**Issue by al3x609** [apptainer/singularity#1966]
## Version of Singularity:

latest

### Expected behavior

with %runscript i do:
```
BootStrap: xxx

From: xxx

...
%runscript
`exec setup.sh "${@}" `
...
```
then start with:
`$ singularity run image.simg [arg1] [arg2] ...`

`$ ps aux | grep setup`

`root     30986  0.0  0.0  13004  3096 pts/1    S    03:19   0:00 /usr/bin/bash /mnt/setup.sh 6080 localhost:5901 2018-09-12T00:00:00`
___

with %startscript
```
BootStrap: xxx

From: xxx

...
%startscript
`exec setup.sh "${@}" `
...
```
then start with:
`$ singularity instance.start   image.img  test [arg1] [arg2] ...`
**_maybe_**
`$ singularity instance.list`

```
INSTANCE NAME    PID      CONTAINER IMAGE         ARGS

test             790      /home/alex/test.simg   [arg1] [arg2] ...
```

### Actual behavior

`$ singularity instance.list`

```
INSTANCE NAME    PID      CONTAINER IMAGE

test              790      /home/alex/test.simg 
```

### **does not take into account the arguments**

___

I know that one option is to deploy the instance and then launch the run command on the instance to pass the parameters; but if what I want to instantiate is a shell script and not an executable as such ... how can I do this. ?

**Comment by kotfic** [comment]
@al3x609 I have a similar question.  If you don't mind, how was this resolved?

**Comment by cclerget** [comment]
@al3x609 @kotfic That should be resolved with PR #2512

**Comment by al3x609** [comment]
Hi @cclerget,   many thanks, this is very useful, because until now I had to export variables and read them when instantiating the image; which I think is not the most elegant way to do it.
```
...
%startscript
  exec /opt/entrypoint.sh ${SINGULARITYENV_APP} ${SINGULARITYENV_ENDTIME} ${SINGULARITYENV_DISP} &
```

**Comment by kotfic** [comment]
@cclerget that's great,  unfortunately i'm stuck on 2.6.1,  I can just use @al3x609 workaround for now
