### ISSUE TITLE
ERROR  : Error handling tar header: (null) when building from Docker hub

### ISSUE THREAD

**Issue by anthonypj** [apptainer/singularity#1967]
## Version of Singularity:

2.6.0-dist on CentOS Linux release 7.5.1804 (Core) 

### Expected behavior

Image builds from Docker Hub

### Actual behavior

Build fails: last few lines of output as follows:
[...]
VERBOSE: Set messagelevel to: 2
VERBOSE: Initializing Singularity Registry
Exploding layer: sha256:9175ad2a59a502100a167cf1019f2526808194256cfa4a80441d333b14c61844.tar.gz
VERBOSE: Set messagelevel to: 2
VERBOSE: Initializing Singularity Registry
WARNING: Warning handling tar header: (null)
ERROR  : Error handling tar header: (null)
ABORT  : Retval = 255
Cleaning up...

### Steps to reproduce behavior

singularity -v build mindboggle.simg docker://nipy/mindboggle

Taking a copy of sha256:9175ad2a59a502100a167cf1019f2526808194256cfa4a80441d333b14c61844.tar.gz from the local docker cache and expanding it with "tar zxvf" succeeds.

**Comment by dtrudg** [comment]
Hi @anthonypj - singularity is using libarchive for extraction, so I can use `bsdtar` to double check extraction of this file (it's based on libarchive)

On CentOS 7 with libarchive 3.1.2 I see an error:

```
09:14 AM $ bsdtar -tf .singularity/docker/sha256:9175ad2a59a502100a167cf1019f2526808194256cfa4a80441d333b14c61844.tar.gz
opt/
opt/data/
<snip>
opt/data/__MACOSX/OASIS-30_Atropos_template/Priors2/._priors6.nii.gz
bsdtar: Truncated input file (needed 512 bytes, only 0 available)
bsdtar: Error exit delayed from previous errors.
```

On Ubuntu 18.04 with libarchive 3.2.2 I do not get this error - so this may be a libarchive bug, hit by this particular docker layer. I'm afraid the solution, if that's the case, would be to install a newer version of libarchive, and build Singularity against this new version.

**Comment by anthonypj** [comment]
Confirm this was an issue which was fixed in the Mindboggle Docker image:

https://github.com/nipy/mindboggle/pull/159

Thanks for the help
