### ISSUE TITLE
Docker tests failing with JSON errors on openSuSE

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#1969]
## Version of Singularity:

singularity version 3.0.0-alpha.1-217-g41c253f6-dirty

### Expected behavior

Docker tests pass.

### Actual behavior

All the tests that use `singularity --build docker://` seem to fail on openSuSE. They pass without issue on CentOS.

=== RUN   TestDockerPermissions
--- FAIL: TestDockerPermissions (0.01s)
    docker_test.go:96: ^[[33mWARNING:^[[0m Authentication token file not found : Only pulls of public images will succeed
        2018/09/12 06:18:38 Error initializing source docker://dctrud/docker-singularity-userperms:latest: error getting username and password: error reading JSON file "/root/.docker/config.json": error unmarshaling JSON at "/root/.docker/config.json": unexpected end of JSON input

docker_test.go:97: unexpected failure: exit status 1

---

=== RUN   TestDockerWhiteoutSymlink
--- FAIL: TestDockerWhiteoutSymlink (0.01s)
    docker_test.go:148: ^[[33mWARNING:^[[0m Authentication token file not found : Only pulls of public images will succeed
        2018/09/12 06:39:44 Error initializing source docker://dctrud/docker-singularity-linkwh:latest: error getting username and password: error reading JSON file "/root/.docker/config.json": error unmarshaling JSON at "/root/.docker/config.json": unexpected end of JSON input

docker_test.go:149: unexpected failure: exit status 1

---

=== RUN   TestSandboxAssemblerDocker
^[[0mDEBUG   ^[[0m[U=1000,P=20289]   NewBundle()                   Created temporary directory for bundle /tmp/sbuild-oci-011090937
2018/09/12 06:44:44 Error initializing source docker://alpine:latest: error getting username and password: error reading JSON file "/root/.docker/config.json": error unmarshaling JSON at "/root/.docker/config.json": unexpected end of JSON input
FAIL    github.com/singularityware/singularity/src/pkg/build/assemblers 0.038s

---

=== RUN   TestOCIConveyorDocker
^[[0mDEBUG   ^[[0m[U=1000,P=20318]   NewBundle()                   Created temporary directory for bundle /tmp/sbuild-oci-390489775
2018/09/12 06:44:48 Error initializing source docker://alpine:latest: error getting username and password: error reading JSON file "/root/.docker/config.json": error unmarshaling JSON at "/root/.docker/config.json": unexpected end of JSON input
FAIL    github.com/singularityware/singularity/src/pkg/build/sources    1.859s

---

### Steps to reproduce behavior

Run `make test` after building on openSuSE. Probably has the same issues on SLE, but did not verify.

**Comment by jscook2345** [comment]
@tri-adam discussed my current workaround (to set home in each test requiring it) and decided it may be a better idea to do so when dropping privs and then resetting upon completion of the test.

I will work on a pull request for this and have @tri-adam review it soon.

**Comment by sashayakovtseva** [comment]
Was able to build with sudo
