### ISSUE TITLE
link to latest version of docs

### ISSUE THREAD

**Issue by tombradford** [apptainer/singularity#1973]
Could you please create a link on https://www.sylabs.io to point to the latest version of docs in addition to the version specific links?

For example with version 2.6:
https://www.sylabs.io/guides/latest/user-guide/
https://www.sylabs.io/guides/2.6/user-guide/

https://www.sylabs.io/guides/latest/admin-guide/
https://www.sylabs.io/guides/2.6/admin-guide/

**Comment by GodloveD** [comment]
@jmstover @devprincess is that something that could be done pretty easily?

**Comment by jmstover** [comment]
Hi @tombradford.

I through a symlink in place pointing to 2.6. So your `/guides/latest/user-guide` URL will go the the 2.6 user-guide

**Comment by tombradford** [comment]
That's brilliant, thank you

**Comment by GodloveD** [comment]
Hey @jmstover would it also be possible to add a link on the https://www.sylabs.io/docs/ page.  I think it would be useful to do the following:

- Collapse that useless box that is open by default when you first hit the page.
- Change the title of the box to something more useful (like ***Documentation for specific versions** or something.
- Stick a link to the latest version of the docs above the collapsed box and name the link something useful (like **Latest documentation** or something)

How does that sound?
