### ISSUE TITLE
Discuss how best to handle the caching of os/user.Current

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#1976]
## Version of Singularity:

master

### Expected behavior

os/user.Current should not cache it's responses.

### Actual behavior

os/user.Current does cache it's responses.

### Steps to reproduce behavior

@dctrud provided the following example

11:53 AM $ cat main.go 
package main

import "runtime"
import "syscall"
import "os"
import "os/user"
import "log"
import "fmt"

func main() {

	runtime.LockOSThread()

	u, _ := user.Current()
	fmt.Printf("user.Current before priv drop: %v\n", u.Name)

	if os.Getuid() == 0 {
		if err := syscall.Setresuid(1000, 1000, 0); err != nil {
			log.Fatalf("failed to set user identity: %v", err)
		}

		u, _ = user.Current()
		fmt.Printf("user.Current after priv drop: %v\n", u.Name)

	}
}
dave@piran:~/currentuser_test.go
11:53 AM $ sudo go run main.go 
user.Current before priv drop: root
user.Current after priv drop: root

**Comment by dtrudg** [comment]
currently used here: https://github.com/singularityware/singularity/blob/b2255f45c06049ba740742dad155668df57a4751/src/cmd/singularity/cli/singularity.go#L53
and here:
https://github.com/singularityware/singularity/blob/464f40d239041872cddf3c060d994d40590d99fa/src/pkg/client/cache/dir.go#L55

Both of these are outside of any priv drop / uid manipulation in normal use, so should be safe. The issue with using this in the test code (where the are priv drops) has been addressed by PR #1978

**Comment by dtrudg** [comment]
I believe this is no longer an issue due to https://github.com/sylabs/singularity/pull/4406 - could you confirm please @sashayakovtseva ?

**Comment by sashayakovtseva** [comment]
@dctrud Right, there is no cache now.
