### ISSUE TITLE
singularity help create: supported filesystems confusion

### ISSUE THREAD

**Issue by czka** [apptainer/singularity#199]
`-f/--fs     Supported File systems: ext3/ext4 (ext[2/3]: default ext3)`

There's some typo here it seems.

Do I understand that ext2, 3 and 4 are all supported?

That's v 2.1.2.

**Comment by gmkurtzer** [comment]
Oh, good find. No, only ext3/4 are supported in 2.1. And that may change in 2.2 to only ext3 (not all versions of ext4 are in fact compatible).

**Comment by gmkurtzer** [comment]
Fixed in [2.x a75d8ca].

Thanks again!
