### ISSUE TITLE
singularity exec docker:// fails thinking the docker url is a file it should open

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#1994]
## Version of Singularity:

singularity version 3.0.0-alpha.1-394-gc8be8355-dirty

### Expected behavior

Print the environment for the container bootstrapped from docker hub

### Actual behavior

FATAL   [U=1000,P=14733]   SContainer()                  failed to retrieved path for /home/vagrant/go/src/github.com/singularityware/singularity/docker:/godlove/lolcow: lstat /home/vagrant/go/src/github.com/singularityware/singularity/docker:: no such file or directory

### Steps to reproduce behavior

singularity exec docker://busybox env

Failed with docker://dgodlove/lolcow as well.

**Comment by jscook2345** [comment]
This is blocking the porting of 25-environment.sh since it uses exec only. If you'd like I can change to pull than exec instead but the plain exec is a bit cleaner.

**Comment by GodloveD** [comment]
I think that is the point of these tests.  To find errors like this.  So I would just leave as is for now.  If you need to comment out the appropriate tests to make progress or something that is understandable.
