### ISSUE TITLE
3.0: Bind mount options carrying to others

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#1997]
## Version of Singularity:
3.0.0-alpha.1-407-g7cc0b5c

### Expected behavior
When you specify multiple `-B` mounts, options from a prior mount do not carry to other mounts

### Actual behavior
Options carry to other mounts... For example:

```
$ singularity instance start -B web/htdocs:/usr/local/apache2/htdocs:ro -B web/logs:/usr/local/apache2/logs httpd.sif httpd

$ singularity exec instance://httpd touch /usr/local/apache2/logs/lala
touch: cannot touch '/usr/local/apache2/logs/lala': Read-only file system
```

### Steps to reproduce behavior

Try to bind mount more than one location, and add an option to a prior mount point.

```
singularity exec -B web/htdocs:/srv/web:ro -B web/logs:/var/log/web alpine.sif touch /var/log/web/lala
touch: /var/log/web/lala: Read-only file system
```

**Comment by cclerget** [comment]
Fixed by #1998
