### ISSUE TITLE
Could not escalate privledges

### ISSUE THREAD

**Issue by remyd1** [apptainer/singularity#2]
Hi,

Firstly, your project sounds really interesting.

However, I am not able to generate any sapp execution file. If I try to generate one while I am root, I get:
"ERROR: Do not run singularities as root!"

But if I try to do the same as a simple user I get:
"ERROR: Could not escalate privledges!"

About documentation:

By the way, you shoud update your documentation (README file), because apparently you changed the way spec files should be written:

name echo -> Name: echo
program /bin/echo -> Exec: /bin/echo

PS: please do not write `<sapp specfile>` in your README, because it could also lead to some misunderstanding in your file definition (you could use 3*backquote to escape your text (markdown)).

Best,
Remy

**Comment by remyd1** [comment]
chmod 4755 /usr/local/libexec/singularity/sexec

...And it works! Need to fix the Makefile.

**Comment by gmkurtzer** [comment]
Hello,

I fixed the install error you were having and added a Make feature (make install-perms) should fix it and updated the docs on the website.

I also took the lazy way out of the README by pointing things to the website which I am trying to keep more current.

Thanks!
