### ISSUE TITLE
`RunCmd echo string > /path/to/file' in a definition file writes to host's filesystem

### ISSUE THREAD

**Issue by czka** [apptainer/singularity#200]
v 2.1.2

`RunCmd ln -s /usr/share/zoneinfo/UTC /etc/localtime` stays within the image's filestystem, as expected. 

But `RunCmd echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen` has overwriten my host's file. Prefixing the path with `"$SINGULARITY_BUILD_ROOT"` fixes it, but that's not an acceptable solution.

**Comment by gmkurtzer** [comment]
Yes, this is a known issue. The Bootstrap definition gets parsed as a shell script, so a redirect would put it on the host unless it is quoted and/or escaped properly.

This is one of the big limitations/issues with the current bootstrap model and one of the reasons that I am going to be changing it in the next week or so (which is the correct fix to this I think).

**Comment by gmkurtzer** [comment]
The new bootstrap definition format has been implemented, and it solves this issue.

Thanks!
