### ISSUE TITLE
default permissions for /root and /var/tmp are questionable

### ISSUE THREAD

**Issue by czka** [apptainer/singularity#201]
In 2.1.2, bootstrap creates /root and /var/tmp with 755 permissions.

World-readable /root is not a good idea normally. 750 should be fine.

System-wide tmp dir should normally be writeable for all and have a sticky bit - 1777.

Re-reporting the issue here as agreed in #197.

**Comment by gmkurtzer** [comment]
Fixed in [master 0721d4e]
