### ISSUE TITLE
singularity instance start does not work, provides no error

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2014]
## Version of Singularity:

$ singularity --version
singularity version 3.0.0-alpha.1-468-gb034a40-dirty

### Expected behavior

$ singularity instance start Default.sif www
$ echo $?
0
$ singularity instance list
INSTANCE NAME    PID      IMAGE
<instance info shown here>

### Actual behavior

$ singularity instance start Default.sif www
$ echo $?
1
$ singularity instance list
INSTANCE NAME    PID      IMAGE
$ singularity --verbose instance start Default.sif www
$ echo $?
1

### Steps to reproduce behavior

$ sudo singularity build Default.sif examples/busybox/Singularity
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
INFO:    Running post scriptlet
+ echo Hello from inside the container
Hello from inside the container
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete!
$ singularity instance start Default.sif www
$ echo $?
1
$ singularity instance list
INSTANCE NAME    PID      IMAGE
$ singularity --verbose instance start Default.sif www
$ echo $?
1

**Comment by jmstover** [comment]
In 2.6.0 there is:
`1 jason      0:00 {sinit} singularity-instance: jason [test]`

when doing `instance.start` on an image without a startscript. So there's a process within that PID namespace keeping it alive. It _appears_ that 3.0 is looking only for `/.singularity.d/startscript` and if it doesn't exist bailing.

Should a `%startscript` be required when running an instance, or should _any_ image be able to be used for the base of an instance...  i.e. 

```
singularity instance start tf.sif tf
singularity exec instance://tf python blah.py
```
So a tensoflow image is started as the base instance, without a startscript, and then you're using it with a `instance://` URI

**Comment by GodloveD** [comment]
Is there a regression test in place for this?

**Comment by jscook2345** [comment]
#2081
