### ISSUE TITLE
docker provisioner - use dynamic architecture

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2023]
Currently we have "amd64" as a hard-coded architecture for docker image provision. As a first step toward multiple architecture support, ensure we are dynamically using the architecture observed on the host at run time.

Consider the possibility of wanting to do cross-architecture builds in future - don't implement now, but don't make it more difficult.

**Comment by GodloveD** [comment]
See line of code here: https://github.com/singularityware/singularity/blob/8eea5c3ca1549d4ab8f245060bda94774348a72b/src/pkg/build/sources/conveyorPacker_oci.go#L254

**Comment by dtrudg** [comment]
hey @GodloveD - as @bauerm97 moved this off of 3.0 I've unassigned myself here.

**Comment by dtrudg** [comment]
In current code this is handled appropriately by umoci on Linux. `amd64` is hard coded for image-tools extraction on Mac - where `amd64` is all that is supported.
