### ISSUE TITLE
inheritting host's vs having own configuration

### ISSUE THREAD

**Issue by czka** [apptainer/singularity#203]
In #197 we discussed inheritting the host's vs having own configuration files in the image. Networking files (/etc/hosts, /etc/resolv.conf), localization (/etc/locale.gen, /etc/locale.def), time zone (/etc/localtime) were mentioned.

I think that a maintainable, consistent approach might be as follows:
1. The user is assumed to populate his image's configuration files at image bootstrapping time, eg. using `RunCmd echo something > /some/path`, `InstallFile /path/on/host /path/on/image` (something like what I'm doing in examples/arch.def). Document this clearly.
2. Have a well-documented list of files (eg. in a default "PathInheritIncludeDefault" keyword), typically common across different GNU/Linux distros, for which it often makes sense to be inheritted from the host. Eg. those paths mentioned above, /etc/nsswitch.conf etc.
3. Provide definition file keywords "PathInheritExclude" and "PathInheritInclude" for the user to ignore some default includes, and to add his own. Eg. some users may want to inherit most of the default paths but not /etc/locale.def, Arch Linux users might want to additionally inherit host's /etc/pacman.d/mirrorlist etc.
4. If a user prefers not to inherit any host files in his image, he would set "PathInheritIncludeDefault = ''" in his definition file. Document this clearly.
5. `singularity run/start/shell/exec --inherit` will honor "PathInheritIncludeDefault", "PathInheritExclude", "PathInheritInclude" as specified in a definition file at image creation time. Without `--inherit` the image will honor only "PathInheritIncludeDefault".
6. Additional 2 switches for run/start/shell/exec could be added (eg. `--inherit-include`, `--inherit-exclude`) for the user to specify any add-hoc extra paths for a single container run.

This should provide for both sane defaults and flexibility. I'm trying to keep in mind that Singularity images are supposed to be highly mobile thus ready for all sorts of weird host setups where one can't really hope for sane, compatible or even existing host configarution files, in which case a Singularity image should bring its own. Another scenario is when one boostraps a foreign distro image (e.g Debian on Arch - done that), while the format or location of some configuration on the host and image distro are different. That's why maximum flexibility is required.

If you asked me, I would not mix `--contain` with this. It's best left for (not) sharing of writable host filesystems, which is not a directly related feature. One may one want to (not) share those filesystems and have arbitrary host configuration files inheritted or not, at the same time.

One problem might be running a `--writable` container as root with any host configuration files inheritted, which might lead to their (un)expected modification. But that's already the situation with `--writable` in general, no?

Let's discuss how this proposition looks to you.

**Comment by gmkurtzer** [comment]
I need some time to really grok all of this, but if I am understanding what you are proposing correctly, couldn't the same be achieved using a model of: bind these files if they already exist within the image, or bind if they have a particular string in them?

If not, can you explain the use-case you are thinking of to help me wrap my head around this?

It might also be helpful if you explain how (in pseudo code/example) you would imagine implementing this (e.g. is the `PathInheritInclude` a list in the container's root directory?). Maybe a JSON config?

Great thinking and thanks!

**Comment by gmkurtzer** [comment]
Can you give me some example files or use-cases that this would solve? I have some ideas on the implementation, but not sure it meets the needs of what you are thinking.

**Comment by czka** [comment]
I don't have much to add. No real-lfe use cases to show either, but those I made up seem rather realistic to me. If time allows, I might come up with some Python code that emulates the behavior I'm describing, but I don't think this will happen in the coming weeks. Sorry I'm not too helpful.

**Comment by gmkurtzer** [comment]
Before you think of implementing the idea, if you can come up with a few cases to describe the need so I can wrap my head around it. I'm asking this because for every case I've come up with, there is a module that already supports that (e.g. passwd, group, resolvconf, modules that are already in the code base). And if there is only one or two other files that we need to support it, then perhaps the best case is to just write a specific module for that file/feature.

I like your brainstorming and ideas on this, so keep them coming! :)

**Comment by gmkurtzer** [comment]
I am closing this issue for now. Feel free to comment if/when it should be reopened.
