### ISSUE TITLE
singularity with secure build

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#2034]
Awesome work guys!

When the release comes out, could we add a note to the maintainers to do list to update the secure build so I can re-build the Singularity Hub builders with it? It's important to the many academic users to be able to use the latest and greatest, and I'm happy to do this work to provide that to them. Thank you!

**Comment by ArangoGutierrez** [comment]
PING @vsoch 
v3.0.0 is out 
https://github.com/sylabs/singularity/releases/tag/v3.0.0

**Comment by vsoch** [comment]
Could you please point me to the secure build branch? Normally @cclerget does some tweaking and releases it alongside. Thanks!

**Comment by cclerget** [comment]
Hi @vsoch, there is no secure build for v3 and I can't say if/when this will be supported, the only branch available is for v2 here : https://github.com/cclerget/singularity/tree/feature-squashbuild-secbuild-2.5.0 and I believe you already updated with changes applied in this branch.

However there is a point to consider here :
- v3 build support only new SIF image format and sandbox image as output meaning v3 generated SIF images won't be compatible with v2 supporting old SIF image format.

Actually singularity hub generates image compatible both with v2 and v3, by updating builder to v3 you will break v2 compatibility.

EDIT: both v2/v3 support shub images

**Comment by vsoch** [comment]
This is what I'm afraid of! Did you see @gmkurtzer mention here of some kind of section argument --> https://twitter.com/gmkurtzer/status/1049498307205128193 could you tell me what that means and how it relates to secure build (and addresses the issue or not?) Thanks @cclerget !

**Comment by cclerget** [comment]
Just read it and unfortunately no, `--section` won't help to reproduce `--isolated` option. But @vsoch I don't think this is an issue for singularity hub and I totally concur with @gmkurtzer suggestion to give you API access, that would avoid duplication of effort.

**Comment by vsoch** [comment]
Yes that would be fantastic! It would be very easy to plug in the Sylabs Builder API as an option for Singularity Registry Server and the Global Client. Looking forward to learning more about the API.

**Comment by vsoch** [comment]
ping - we could use secure build for updated versions of Singularity. It needs to be install-able on a host that  shub communicates with, akin to how it was done before. Thanks muchly!

**Comment by dtrudg** [comment]
I believe the documented `--fakeroot` functionality should alleviate the need for something like the old securebuild branch. @cclerget - is this your understanding, can we close this?

**Comment by vsoch** [comment]
No it's not the same. I have been asking about this for years (since 2.5.1) and was forced to figure this out on my own, because it doesn't seem like something that Sylabs wanted to help with. ¯\_(ツ)_/¯
