### ISSUE TITLE
sing Run/Exec - Failed to find loop device: operation not permitted

### ISSUE THREAD

**Issue by josbake** [apptainer/singularity#2049]
## Version of Singularity:
singularity version v3.0.0-alpha.1-601-g9bf6aee0

### Expected behavior
Running 'sudo singularity shell IMAGE_NAME' or 'sudo singularity run IMAGE_NAME' spins up a container based on the image.

### Actual behavior
Exception occurs:
FATAL:   container creation failed: mount error: can't mount image /proc/self/fd/9: failed to find loop device: operation not permitted

### Steps to reproduce behavior
1. Build image from Singularity file
2. 'sudo singularity shell/run IMAGE_NAME'

**Comment by ArangoGutierrez** [comment]
Could you give it a try with the latest master and let me know
thanks

**Comment by cclerget** [comment]
Hi @josbake , what linux distribution you use ? and additionally can you give your kernel version ? Thanks !

**Comment by josbake** [comment]
I am using Ubuntu 18, kernel version 4.15.0-34-generic. @cclerget 
Due to issues with my company's proxy, I have to use a pre-built version sent to me from another Ubuntu machine, so I will try to get that for the latest master. @ArangoGutierrez

**Comment by josbake** [comment]
Updated to latest version, and the problem persists.

**Comment by cclerget** [comment]
@josbake can you paste full debug output with `sudo singularity -d shell IMAGE_NAME` please ?

**Comment by josbake** [comment]
VERBOSE [U=0,P=988]        execStarter()                 starter-suid not found, using user namespace
VERBOSE [U=0,P=988]        singularity_message_level()               Set messagelevel to: 5
DEBUG   [U=0,P=988]        init()                                    PIPE_EXEC_FD value: 7
VERBOSE [U=0,P=988]        init()                                    Container runtime
VERBOSE [U=0,P=988]        is_suid()                                 Check if we are running as setuid
DEBUG   [U=0,P=988]        init()                                    Overlay seems supported by kernel
DEBUG   [U=0,P=988]        init()                                    Read json configuration from pipe
DEBUG   [U=0,P=988]        init()                                    Set child signal mask
DEBUG   [U=0,P=988]        init()                                    Create socketpair for smaster communication channel
DEBUG   [U=0,P=988]        init()                                    Wait C and JSON runtime configuration from scontainer stage 1
DEBUG   [U=0,P=1001]       set_parent_death_signal()                 Set parent death signal to 9
VERBOSE [U=0,P=1001]       init()                                    Spawn scontainer stage 1
VERBOSE [U=0,P=1001]       startup()                     Execute scontainer stage 1
DEBUG   [U=0,P=1001]       SContainer()                  Entering scontainer stage 1
DEBUG   [U=0,P=1001]       prepareRootCaps()             Root full capabilities
DEBUG   [U=0,P=1001]       Init()                        Entering image format intializer
DEBUG   [U=0,P=1001]       Init()                        Check for image format sif
DEBUG   [U=0,P=1001]       Init()                        sif format initializer returns: SIF magic not found
DEBUG   [U=0,P=1001]       Init()                        Check for image format sandbox
DEBUG   [U=0,P=1001]       Init()                        sandbox format initializer returns: not a directory image
DEBUG   [U=0,P=1001]       Init()                        Check for image format squashfs
DEBUG   [U=0,P=988]        init()                                    Receiving configuration from scontainer stage 1
DEBUG   [U=0,P=988]        init()                                    Wait completion of scontainer stage1
VERBOSE [U=0,P=988]        setup_userns()                            Create user namespace
DEBUG   [U=65534,P=988]    setup_userns()                            Write deny to set group file
DEBUG   [U=65534,P=988]    setup_userns()                            Write to GID map
DEBUG   [U=65534,P=988]    setup_userns()                            Write line '0 0 1' to gid_map
DEBUG   [U=65534,P=988]    setup_userns()                            Write to UID map
VERBOSE [U=0,P=988]        create_namespace()                        Create mount namespace
DEBUG   [U=0,P=988]        init()                                    Create RPC socketpair for communication between scontainer and RPC server
VERBOSE [U=0,P=988]        init()                                    Spawn smaster process
DEBUG   [U=0,P=1008]       set_parent_death_signal()                 Set parent death signal to 9
VERBOSE [U=0,P=1008]       init()                                    Spawn scontainer stage 2
VERBOSE [U=0,P=1008]       create_namespace()                        Create mount namespace
VERBOSE [U=0,P=1008]       init()                                    Spawn RPC server
VERBOSE [U=0,P=988]        startup()                     Execute smaster process
VERBOSE [U=0,P=1008]       startup()                     Serve RPC requests
DEBUG   [U=0,P=988]        setupSessionLayout()          Attempting to use underlay (enable underlay = yes)
DEBUG   [U=0,P=988]        setupUnderlayLayout()         Creating underlay SESSIONDIR layout
DEBUG   [U=0,P=988]        addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=0,P=988]        addRootfsMount()              Mounting block [squashfs] image: /home/josbake/go/src/github.com/sylabs/singularity/builddir/hello-world_latest.sif
DEBUG   [U=0,P=988]        addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=0,P=988]        addKernelMount()              Adding proc to mount list
DEBUG   [U=0,P=988]        addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=0,P=988]        addKernelMount()              Adding sysfs to mount list
DEBUG   [U=0,P=988]        addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=0,P=988]        addDevMount()                 Adding dev to mount list
DEBUG   [U=0,P=988]        addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=0,P=988]        addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=0,P=988]        addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=0,P=988]        addHomeStagingDir()           Staging home directory (/root) at /usr/local/var/singularity/mnt/session/root
DEBUG   [U=0,P=988]        addHomeMount()                Adding home directory mount [/usr/local/var/singularity/mnt/session/root:/root] to list using layer: underlay
DEBUG   [U=0,P=988]        isLayerEnabled()              Using Layer system: underlay
DEBUG   [U=0,P=988]        addTmpMount()                 Checking for 'mount tmp' in configuration file
DEBUG   [U=0,P=988]        addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=0,P=988]        addResolvConfMount()          Adding /etc/resolv.conf to mount list
DEBUG   [U=0,P=988]        addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=0,P=988]        create()                      Mount all
DEBUG   [U=0,P=988]        mountGeneric()                Mounting tmpfs to /usr/local/var/singularity/mnt/session
DEBUG   [U=0,P=988]        CleanupContainer()            Cleanup container
FATAL   [U=0,P=988]        SMaster()                     container creation failed: mount error: can't mount image /proc/self/fd/9: failed to find loop device: operation not permitted

**Comment by cclerget** [comment]
@josbake Oh ! you use user namespace : `execStarter() starter-suid not found, using user namespace`, that means setuid binary is not present on your system, loop device are usable only with setuid workflow and are not compatible with user namespace since it requires privileges. There is a problem with your installation, did you install it by doing `sudo make -C builddir install` ?

**Comment by josbake** [comment]
Got it. Something in my file permissions didn't work right when I installed directly after copying from the prebuilt version I had. Ran install again and it's working.
Thanks!
