### ISSUE TITLE
PATH environment variable is being clobbered in environment tests

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2053]
## Version of Singularity:

singularity version v3.0.0-alpha.2-58-g25cf9068-dirty

### Expected behavior

Like the following, but in a test.

$ singularity exec docker://alpine:3.8 env
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde
Copying config sha256:dd0dea60eb1382cc70219ae4dc4771b5fc2cc0b2a0de1c6575051f98b76bf035
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    PATH = '/home/vagrant/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/go/bin:/home/vagrant/go/bin'
INFO:    Build complete!
INFO:    Image cached as SIF at /home/vagrant/.singularity/cache/oci-tmp/621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528/alpine_3.8.sif

### Actual behavior

--- FAIL: TestSingularityEnv (76.55s)
    --- FAIL: TestSingularityEnv/DefaultPath (4.77s)
        env_test.go:60: args: 'exec docker://alpine:3.8 env'
        env_test.go:61: env: ''
        env_test.go:62: ^[[34mINFO:   ^[[0m Converting OCI blobs to SIF format
            ^[[34mINFO:   ^[[0m Starting build...
            Getting image source signatures
            Copying blob sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde
            ^M 0 B / 2.10 MiB [--------------------------------------------------------------]^M 846.76 KiB / 2.10 MiB [=====================>---------------------------------]^M 1.87 MiB / 2.10 MiB [==================================================>------]^M 2.10 MiB / 2.10 MiB [======================================================] 0s
            Copying config sha256:dd0dea60eb1382cc70219ae4dc4771b5fc2cc0b2a0de1c6575051f98b76bf035
            ^M 0 B / 585 B [-----------------------------------------------------------------]^M 585 B / 585 B [============================================================] 0s
            Writing manifest to image destination
            Storing signatures
            ^[[34mINFO:   ^[[0m Creating SIF file...
            ^[[34mINFO:   ^[[0m PATH = ''
            ^[[31mERROR:  ^[[0m mksquashfs is not installed on this system
            ^[[31mFATAL:  ^[[0m Unable to build: exec: "mksquashfs": executable file not found in $PATH

### Steps to reproduce behavior

Blocks #2004. My tests in the PR are failing with the above and I've been unable to determine the reason why PATH is being reset. A regular command not in the test harness works as expected. It also works if the image is cached, though that is a false positive.

**Comment by jscook2345** [comment]
I think I found the issue with this. Once my env tests are merged I will open a new PR to fix.

**Comment by GodloveD** [comment]
Glad you figured that out.  I had no idea.  😸
