### ISSUE TITLE
Caching causing false positives in test results

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2054]
## Version of Singularity:

A failing test is showing up as passed occasionally due to caching being used during testing.

### Expected behavior

    --- FAIL: TestSingularityEnv/DefaultPath (4.61s)
        env_test.go:60: args: 'exec docker://alpine:3.8 env'
        env_test.go:61: env: ''
        env_test.go:62: ^[[34mINFO:   ^[[0m Converting OCI blobs to SIF format
            ^[[34mINFO:   ^[[0m Starting build...
            Getting image source signatures
            Copying blob sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde
            ^M 0 B / 2.10 MiB [--------------------------------------------------------------]^M 862.76 KiB / 2.10 MiB [======================>--------------------------------]^M 1.86 MiB / 2.10 MiB [==================================================>------]^M 2.10 MiB / 2.10 MiB [======================================================] 0s
            Copying config sha256:dd0dea60eb1382cc70219ae4dc4771b5fc2cc0b2a0de1c6575051f98b76bf035
            ^M 0 B / 585 B [-----------------------------------------------------------------]^M 585 B / 585 B [============================================================] 0s
            Writing manifest to image destination
            Storing signatures
            ^[[34mINFO:   ^[[0m Creating SIF file...
            ^[[34mINFO:   ^[[0m PATH = ''
            ^[[31mERROR:  ^[[0m mksquashfs is not installed on this system
            ^[[31mFATAL:  ^[[0m Unable to build: exec: "mksquashfs": executable file not found in $PATH

### Actual behavior

    --- PASS: TestSingularityEnv/DefaultPath (1.09s)
        env_test.go:60: args: 'exec docker://alpine:3.8 env'
        env_test.go:61: env: ''
        env_test.go:62: SHLVL=1
            LD_LIBRARY_PATH=/.singularity.d/libs
            HOME=/home/vagrant
            PS1=Singularity>
            PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            SINGULARITY_CONTAINER=/home/vagrant/.singularity/cache/oci-tmp/621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528/alpine_3.8.sif
            PWD=/home/vagrant/go/src/github.com/sylabs/singularity/src/cmd/singularity
            SINGULARITY_NAME=alpine_3.8.sif

### Steps to reproduce behavior

Images existing in the cache caused this test failure to come through as a false positive. Perhaps caching should be disabled during testing.

**Comment by dtrudg** [comment]
Don't think there's a great way out of this. If we don't use caching the tests will take a huge time. The indicated error of missing mksquashfs should possibly be checked at startup of the test suite.
