### ISSUE TITLE
In INSTALL.md, remove '$' shell markers so you can copy and paste install instructions

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2079]
It may be useful to remove the '$' shell markers so that install instructions can be copy and pasted to ease installation.

**Comment by GodloveD** [comment]
I don't like this idea.  This is a markdown file and should conform to the rest of our documentation imho.  Also, most of the steps here are carried out once when someone first sets up a go environment and are not repeated upon successive installations of Singularity.

**Comment by jscook2345** [comment]
Closing!
