### ISSUE TITLE
`go test -race` option does not work on alpine due to musl

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2084]
go test -race does not work on alpine due to musl. This will need to be disabled when `make test` is done in an alpine OS instance.

https://github.com/golang/go/issues/14481

**Comment by luisdavim** [comment]
this is a duplicate of https://github.com/golang/go/issues/14481

**Comment by dtrudg** [comment]
Should work in Go 1.15: https://github.com/golang/go/issues/14481#issuecomment-613985186
