### ISSUE TITLE
3.0: --writable causes --nv to be ignored

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#2088]
## Version of Singularity:
v3.0.0-alpha.2-272-g5fb1529

### Expected behavior
$ sudo singularity shell --nv --writable ../sbox/
> ls -l /.singularity.d/libs/ | wc -l
46

### Actual behavior
$ sudo singularity shell --nv --writable ../sbox/
> ls -l /.singularity.d/libs/
total 0

**Comment by cclerget** [comment]
@jmstover Yeah that's how v3 behave now, it doesn't write anything in container image, since writable flag disable overlay/underlay nothing is written in image by Singularity. nv flag should be handled separately of bind path to address the issue. Ping @ctmadison

**Comment by jmstover** [comment]
This is a *massive* behavior change. In 2.6.0 ... 

```
$ singularity exec --nv --writable ../arnold/ ls -l /.singularity.d/libs/ | wc -l
WARNING: Skipping user bind, non existent bind point (file) in container: '/usr/bin/nvidia-smi'
WARNING: Skipping user bind, non existent bind point (file) in container: '/usr/bin/nvidia-debugdump'
WARNING: Skipping user bind, non existent bind point (file) in container: '/usr/bin/nvidia-persistenced'
WARNING: Skipping user bind, non existent bind point (file) in container: '/usr/bin/nvidia-cuda-mps-control'
WARNING: Skipping user bind, non existent bind point (file) in container: '/usr/bin/nvidia-cuda-mps-server'
46
```

The binaries not being mounted in with `--nv --writable` in 2.6.0 are generally minor, but the libs not being there are not.

**Comment by GodloveD** [comment]
This will end up causing us another headache too.  We were going to get rid of the `$SINGULARITY_CONTAINLIBS` env var because we were under the impression that with underlay a user would be able to do the same thing simply by using the `$SINGULARITY_BINDPATH` env var (and `$SINGULARITY_CONTAINLIBS` was never really meant to be exposed to the user anyway).

But now, this means we may have to reintroduce `$SINGULARITY_CONTAINLIBS` because the simple `$SINGULARITY_BINDPATHS` env var will not work in combination with the `--writable` flag.  

I'm pretty sure I already know the answer to this @cclerget.  But is there any way at all that this could be made to work the the `--writable` flag?  

🙏 
🙇

**Comment by cclerget** [comment]
@GodloveD `$SINGULARITY_CONTAINLIBS` can be completely ignored, not a problem. Sure this issue can be fixed, just need to mimic the same behaviour as v2 by using session directory and even without using `$SINGULARITY_CONTAINLIBS`, in fact the `nvidiautils.GetNvidiaBindPath` could be splitted into a `nvidiautils.GetLibs()` (to store that in variable BindLibsPath) and `nvidiautils.GetBin()` (to store array in variable BindBinPath) and those functions could be moved directly into stage 1 of runtime engine, like that libs are binded into `/session/libs`, binaries are binded into `/session/libs/bin`, then bind `/session/libs` to container `/.singularity.d/libs` and set PATH and LD_LIBRARY_PATH accordingly

**Comment by jmstover** [comment]
@cclerget ... And this is my argument. It _should not_ be the responsibility of the NV code to handle the mounting right, but of the mounting code itself.

The Bind mount code should go ... "Oh, we're running --writable, so we'll attempt to bind into the /session directory instead of /rootfs." This should be the same for all cases, not just the NV use case.

**Comment by GodloveD** [comment]
This goes further than the `--nv` option.  It also means that the `--writable` option is incompatible with the `--bind` option.
```
$ singularity shell --bind /data my_container/
Singularity> ls -l /data
total 0
-rw-r--r--    1 david    david            0 Aug 27 22:22 foo
Singularity> exit

$ singularity shell --writable --bind /data my_container/
Singularity> ls -l /data
ls: /data: No such file or directory
``` 
But then it seems like this was the way it was in 2.x too.  I just never really knew that:
```
$ singularity shell --bind /data my_container/
Singularity> ls -l /data
total 0
-rw-r--r--    1 david    david            0 Aug 27 22:22 foo
Singularity> exit

$ singularity shell --writable --bind /data my_container/
Singularity> ls -l /data
ls: /data: No such file or directory
```
It would be great if this _did_ work.  Should we just funnel the entire bind path through the `/session` directory?
