### ISSUE TITLE
multistage build test failures

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2092]
## Version of Singularity:

singularity version v3.0.0-alpha.2-272-g5fb15299, current master.

### Failing tests

Failing when running `make test` on opensuse leap 15.0. Seems to be failing during sif-related multi-stage builds.

        --- FAIL: TestBuildMultiStage/SIFToSIF/SIF (0.02s)
            build_test.go:200: ^[[33mWARNING:^[[0m Authentication token file not found : Only pulls of public images will succeed
                panic: runtime error: index out of range

                goroutine 1 [running]:
                github.com/sylabs/singularity/src/pkg/build/types/parser.doHeader(0xc0003d2000, 0x8074, 0xc0004b6f78, 0x948f, 0xc0003d2000)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/types/parser/deffile.go:290 +0x3fc
                github.com/sylabs/singularity/src/pkg/build/types/parser.canGetHeader(0x120b900, 0xc00000e010, 0xc00000e010, 0x0, 0x0)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/types/parser/deffile.go:340 +0x3a8
                github.com/sylabs/singularity/src/pkg/build/types/parser.IsValidDefinition(0x7ffdb125a8c8, 0x1f, 0x0, 0x0, 0x0)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/types/parser/deffile.go:428 +0xa4
                github.com/sylabs/singularity/src/pkg/build.makeDef(0x7ffdb125a8c8, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/build.go:391 +0xb5
                github.com/sylabs/singularity/src/pkg/build.NewBuild(0x7ffdb125a8c8, 0x1f, 0x7ffdb125a8a8, 0x1f, 0x110efb6, 0x3, 0x1150000, 0xc000481070, 0x1, 0x1, ...)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/build.go:67 +0x72
                github.com/sylabs/singularity/src/cmd/singularity/cli.glob..func5(0x19baac0, 0xc0004de080, 0x2, 0x2)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli/build.go:125 +0x446
                github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).execute(0x19baac0, 0xc0000300e0, 0x2, 0x2, 0x19baac0, 0xc0000300e0)
                        /home/vagrant/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
                github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19bdca0, 0x0, 0xfd9940, 0x1202dd0)
                        /home/vagrant/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
                github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).Execute(0x19bdca0, 0x4, 0x1142402)
                        /home/vagrant/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:800 +0x2b
                github.com/sylabs/singularity/src/cmd/singularity/cli.ExecuteSingularity()
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli/singularity.go:107 +0x5b
                main.main()
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli.go:16 +0x20

            build_test.go:201: unexpected failure: exit status 2

### 

       --- FAIL: TestBuildMultiStage/WritableToSIF/SIF (0.02s)
            build_test.go:200: ^[[33mWARNING:^[[0m Authentication token file not found : Only pulls of public images will succeed
                panic: runtime error: index out of range

                goroutine 1 [running]:
                github.com/sylabs/singularity/src/pkg/build/types/parser.doHeader(0xc0003da000, 0x8074, 0xc0004b6f78, 0x94e3, 0xc0003da000)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/types/parser/deffile.go:290 +0x3fc
                github.com/sylabs/singularity/src/pkg/build/types/parser.canGetHeader(0x120b900, 0xc00000e010, 0xc00000e010, 0x0, 0x0)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/types/parser/deffile.go:340 +0x3a8
                github.com/sylabs/singularity/src/pkg/build/types/parser.IsValidDefinition(0x7ffe343268c8, 0x1f, 0x0, 0x0, 0x0)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/types/parser/deffile.go:428 +0xa4
                github.com/sylabs/singularity/src/pkg/build.makeDef(0x7ffe343268c8, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/build.go:391 +0xb5
                github.com/sylabs/singularity/src/pkg/build.NewBuild(0x7ffe343268c8, 0x1f, 0x7ffe343268a8, 0x1f, 0x110efb6, 0x3, 0x1150000, 0xc000485070, 0x1, 0x1, ...)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/build.go:67 +0x72
                github.com/sylabs/singularity/src/cmd/singularity/cli.glob..func5(0x19baac0, 0xc0004dc0e0, 0x2, 0x2)
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli/build.go:125 +0x446
                github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).execute(0x19baac0, 0xc0000300e0, 0x2, 0x2, 0x19baac0, 0xc0000300e0)
                        /home/vagrant/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
                github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19bdca0, 0x0, 0xfd9940, 0x1202dd0)
                        /home/vagrant/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
                github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).Execute(0x19bdca0, 0x4, 0x1142402)
                        /home/vagrant/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:800 +0x2b
                github.com/sylabs/singularity/src/cmd/singularity/cli.ExecuteSingularity()
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli/singularity.go:107 +0x5b
                main.main()
                        /home/vagrant/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli.go:16 +0x20

            build_test.go:201: unexpected failure: exit status 2

**Comment by ArangoGutierrez** [comment]
Same behavior on RHEL7
```bash
[eduardo@rhel7 singularity]$ make -C builddir/ test
make: Entering directory `/home/eduardo/go/src/github.com/sylabs/singularity/builddir'
 TEST sudo go test
?   	github.com/sylabs/singularity/etc/bash_completion.d	[no test files]
ok  	github.com/sylabs/singularity/etc/conf	1.056s	coverage: 27.3% of statements
--- FAIL: TestBuildMultiStage (49.24s)
    --- FAIL: TestBuildMultiStage/WritableToSIF (2.07s)
        --- FAIL: TestBuildMultiStage/WritableToSIF/SIF (0.01s)
            build_test.go:200: WARNING: Authentication token file not found : Only pulls of public images will succeed
                panic: runtime error: index out of range
                
                goroutine 1 [running]:
                github.com/sylabs/singularity/src/pkg/build/types/parser.doHeader(0xc00045e000, 0x8074, 0xc0004f4f78, 0x100e7, 0xc00045e000)
                	/home/eduardo/go/src/github.com/sylabs/singularity/src/pkg/build/types/parser/deffile.go:290 +0x3fc
                github.com/sylabs/singularity/src/pkg/build/types/parser.canGetHeader(0x11b43a0, 0xc000138130, 0xc000138130, 0x0, 0x0)
                	/home/eduardo/go/src/github.com/sylabs/singularity/src/pkg/build/types/parser/deffile.go:340 +0x3a8
                github.com/sylabs/singularity/src/pkg/build/types/parser.IsValidDefinition(0x7fff756ea13d, 0x1f, 0x0, 0x0, 0x0)
                	/home/eduardo/go/src/github.com/sylabs/singularity/src/pkg/build/types/parser/deffile.go:428 +0xa4
                github.com/sylabs/singularity/src/pkg/build.makeDef(0x7fff756ea13d, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                	/home/eduardo/go/src/github.com/sylabs/singularity/src/pkg/build/build.go:391 +0xb5
                github.com/sylabs/singularity/src/pkg/build.NewBuild(0x7fff756ea13d, 0x1f, 0x7fff756ea11d, 0x1f, 0x10b7a56, 0x3, 0x1100000, 0xc0000813f0, 0x1, 0x1, ...)
                	/home/eduardo/go/src/github.com/sylabs/singularity/src/pkg/build/build.go:67 +0x72
                github.com/sylabs/singularity/src/cmd/singularity/cli.glob..func5(0x1963ac0, 0xc00000c8e0, 0x2, 0x2)
                	/home/eduardo/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli/build.go:125 +0x446
                github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).execute(0x1963ac0, 0xc000030120, 0x2, 0x2, 0x1963ac0, 0xc000030120)
                	/home/eduardo/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
                github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1966ca0, 0x0, 0xf823e0, 0x11ab870)
                	/home/eduardo/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
                github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).Execute(0x1966ca0, 0x4, 0x10eae9f)
                	/home/eduardo/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:800 +0x2b
                github.com/sylabs/singularity/src/cmd/singularity/cli.ExecuteSingularity()
                	/home/eduardo/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli/singularity.go:107 +0x5b
                main.main()
                	/home/eduardo/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli.go:16 +0x20
                
            build_test.go:201: unexpected failure: exit status 2
FAIL
coverage: 50.0% of statements
```
