### ISSUE TITLE
3.0: Behavior change from 2.x

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#2099]
## Version of Singularity:
v3.0.0-beta.1-8-gccc859d

### Expected behavior
`TMPDIR` in the container is cleared, or set to the value of `SINGULARITY_TMPDIR`

### Actual behavior
`TMPDIR` is passed through

### Steps to reproduce behavior
Using `alpine_test.def`:
```
Bootstrap: docker
From: alpine:latest

%post
    echo "TMPDIR: $TMPDIR"
```

Build an image file with 3.0 and 2.6.0 ... Check output during build ... 
`sudo TMPDIR=~/tmp singularity build alpine_test.{img,sif} alpine_test.def`

2.6.0:
```
+ echo 'TMPDIR: '
TMPDIR: 
```
3.0.0:
```
INFO:    Running post scriptlet
+ echo 'TMPDIR: /home/jason/tmp'
TMPDIR: /home/jason/tmp
```

*Edit:* I suck... didn't put the version originally

**Comment by GodloveD** [comment]
I just checked this with 3.3.0 and it seems to be fixed.  I'll close for now.  Feel free to reopen if I made an error.  Thanks @jmstover
