### ISSUE TITLE
pymods.dep copies too much

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#21]
Resolving python files ends up copying the whole site-packages directory which appears in the ftrace output, which isn't "most minimal"... Using  install_single_file, instead of install_file fixes that.  Then it still seems to copy too much, which I haven't checked, but is much more reasonable.  (Also, it does too much work recursively checking the copied files, and it might be nice to avoid installing .py if there's a corresponding current .pyc.)

I guess the perl version should be changed similarly, but I don't know if it will make a difference.

**Comment by gmkurtzer** [comment]
Interesting, I am getting very different output when testing on RHEL6 based distributions Vs. RHEL7. Investigating the dependency trail ends up with this:

$ /usr/libexec/singularity/ftrace /usr/bin/python -c "import  copy_reg"
...
/usr/lib/python2.6/site-packages
...

which is what is triggering the entire inclusion and thus dependency resolution of site-packages. Adding a quick check to the python mods to skip confirms that it then works as expected. (I also noticed that the shell is reforking itself too often for the python dependency resolution making ctrl-c's not responsive... Will work on that too!)

I think what I'll do is add the logic to ftrace such that it does a stat() and then checks instead of trusting the return of the calling program's open() (gathered from ptrace'ing it).

Will try and get this stuff done today before the weekend is over, but more likely it will happen tomorrow.

Thanks for the testing and great bug finds!

Greg

**Comment by gmkurtzer** [comment]
This is working for me now in master. If you have the time to test and it doesn't work for you please reopen the issue.

Thanks!

**Comment by loveshack** [comment]
I think it's gone backwards to some extent.  It no longer checks the
script type before running text resolvers rs on it, and ends up
installing a load of perl stuff for a trivial python script (as well as
unnecessary python, I think).

It's rather saner if I check the interpreter appropriately.  I matched
against what ftype extracts in install.smod and had ftrace actually run
that; otherwise it's wrong if the interpreter is, say, "python27".

**Comment by gmkurtzer** [comment]
So ftype does only a very cursory test to see if it is a binary, script or data. In the case of scripts, it looks for the interpreter line at the top (and spits that back out). Perl and Python modules/libraries don't have to have interpreter lines, so ftrace will only see them as non-binary.

Hrmm.. I reopened the issue and will give it some more thought (sorry, I thought others could reopen issues in GitHub).

**Comment by loveshack** [comment]
"Gregory M. Kurtzer" notifications@github.com writes:

> So ftype does only a very cursory test to see if it is a binary,
> script or data. In the case of scripts, it looks for the interpreter
> line at the top (and spits that back out).

Sure, but I think you should use what it spits out.

> Perl and Python
> modules/libraries don't have to have interpreter lines, so ftrace will
> only see them as non-binary.

Indeed, which seems like a reason not to recurse on what ftrace finds.

> Hrmm.. I reopened the issue and will give it some more thought (sorry,
> I thought others could reopen issues in GitHub).

[I've done it previously/elsewhere on github, but I don't see anything
in the interface for singularity (currently).]

**Comment by gmkurtzer** [comment]
Sent from my iPhone

> On Apr 25, 2016, at 7:09 AM, Dave Love notifications@github.com wrote:
> 
> "Gregory M. Kurtzer" notifications@github.com writes:
> 
> > So ftype does only a very cursory test to see if it is a binary,
> > script or data. In the case of scripts, it looks for the interpreter
> > line at the top (and spits that back out).
> 
> Sure, but I think you should use what it spits out.

That's fair, I'll look into feeding the output back into the solver. Should be pretty straight forward. 

Also I added a grep check to help identify if a script is Perl or Python (or potentially any language). Of course it can't be 100% accurate but it does help a lot. 

> > Perl and Python
> > modules/libraries don't have to have interpreter lines, so ftrace will
> > only see them as non-binary.
> 
> Indeed, which seems like a reason not to recurse on what ftrace finds.

I wonder if that will work reliably.... Worth testing!

> > Hrmm.. I reopened the issue and will give it some more thought (sorry,
> > I thought others could reopen issues in GitHub).
> 
> [I've done it previously/elsewhere on github, but I don't see anything
> in the interface for singularity (currently).]

I will look to see if it is a setting I've missed. 

Thanks!

**Comment by loveshack** [comment]
You wrote: 

> That's fair, I'll look into feeding the output back into the
> solver. Should be pretty straight forward.

I did this along with the following:

```
index e8f38f0..3d4e51e 100644
--- a/libexec/mods/install.smod
+++ b/libexec/mods/install.smod
@@ -53,7 +53,10 @@ dep_resolver() {
                         eval $i "$1"
                     done
                 ;;
-                *ascii*)
+                exe-ascii*)
+           unset resolver_interp
+                    [[ $FILE =~ exe-ascii\ (.+) ]] &&
+                      resolver_interp=${BASH_REMATCH[1]}
                     for i in $TXT_RESOLVERS; do
                         message 3 "calling txt_resolvers on: $1 : $i\n"
                         eval $i "$1"
```

> Also I added a grep check to help identify if a script is Perl or
> Python (or potentially any language). Of course it can't be 100%
> accurate but it does help a lot.
> 
> > > Perl and Python
> > > modules/libraries don't have to have interpreter lines, so ftrace will
> > > only see them as non-binary.
> > 
> > Indeed, which seems like a reason not to recurse on what ftrace finds.
> 
> I wonder if that will work reliably.... Worth testing!

You can obviously hide imports, but the current code misses some anyhow,
and I don't think it's worth even trying to figure out the maximal set
of possible imports behind conditionals that may not be relevant.
Avoiding the recursion worked OK in the cases I tried.

For what it's worth, this is what I have for python (along with the diff
above).  It avoids more false positives, catches more imports, and seems
the most trouble it's worth going to short of a proper python parse.
perlmods obviously uses resolver_interp similarly.

```
pymods_resolver() {
    for file in $@; do
        # resolver_interp (from ftype) should be bound in the caller
        # e.g. "/usr/bin/perl5.12", "/bin/env perl"
        [[ $resolver_interp =~ [/[:space:]]python ]] || continue
        # Generate a ;-separated list of import statements from lines like
        #   from <x> import ...
        #   import <x>[, <y>...]
        # Will lose with multiple statements per line and in some
        # other cases.  Look at ast tools (possibly
        # http://bitbucket.org/blais/snakefood) which should work on
        # compiled files too.
        imports=$(awk '
$1=="from" && $3=="import" {list = list "import " $2 ";"}
$1=="import" {list = list "import "
              for (i=2; i<=NF; i++) {
                  if ($i ~ "^#") next
                  list = list $i
                  if ($i ~ /;$/) next}
              list = list ";"}
END {print list}' "$file")
        "$libexecdir/singularity/ftrace" $resolver_interp -c "$imports" 2>&1 >/dev/null |
        while read FILE; do
            if [ ! -f "$INSTALLDIR/c/$FILE" ]; then
                install_file "$FILE"
            fi
        done
    done
}
```

**Comment by gmkurtzer** [comment]
On Mon, Apr 25, 2016 at 9:06 AM, Dave Love notifications@github.com wrote:

> You wrote:
> 
> > That's fair, I'll look into feeding the output back into the
> > solver. Should be pretty straight forward.
> 
> I did this along with the following:
> 
> ```
> index e8f38f0..3d4e51e 100644
> --- a/libexec/mods/install.smod
> +++ b/libexec/mods/install.smod
> @@ -53,7 +53,10 @@ dep_resolver() {
> eval $i "$1"
> done
> ;;
> - *ascii*)
> + exe-ascii*)
> + unset resolver_interp
> + [[ $FILE =~ exe-ascii\ (.+) ]] &&
> + resolver_interp=${BASH_REMATCH[1]}
> for i in $TXT_RESOLVERS; do
> message 3 "calling txt_resolvers on: $1 : $i\n"
> eval $i "$1"
> ```

Ahh, ok. I've been thinking about this, and instead of making a global
variable (which in theory could get overwritten and misappropriated by any
level of recursion) we pass the resolver_interp->BASH_REMATCH[1], directly
into the resolver function. This will of course take some rework of the
resolver functions because at present they assume a list of arguments are
all files to resolve on. Considering they are never called in that manner,
it would be better to formalize their API such that the argument list is as
follows:

resolver_function_name [path to file] [type of file returned by ftype]
[future options if necessary...]

> > Also I added a grep check to help identify if a script is Perl or
> > Python (or potentially any language). Of course it can't be 100%
> > accurate but it does help a lot.
> > 
> > > > Perl and Python
> > > > modules/libraries don't have to have interpreter lines, so ftrace will
> > > > only see them as non-binary.
> > > 
> > > Indeed, which seems like a reason not to recurse on what ftrace finds.
> > 
> > I wonder if that will work reliably.... Worth testing!
> 
> You can obviously hide imports, but the current code misses some anyhow,
> and I don't think it's worth even trying to figure out the maximal set
> of possible imports behind conditionals that may not be relevant.
> Avoiding the recursion worked OK in the cases I tried.
> 
> For what it's worth, this is what I have for python (along with the diff
> above). It avoids more false positives, catches more imports, and seems
> the most trouble it's worth going to short of a proper python parse.
> perlmods obviously uses resolver_interp similarly.
> 
> ```
> pymods_resolver() {
> for file in $@; do
> # resolver_interp (from ftype) should be bound in the caller
> # e.g. "/usr/bin/perl5.12", "/bin/env perl"
> [[ $resolver_interp =~ [/[:space:]]python ]] || continue
> # Generate a ;-separated list of import statements from lines like
> # from <x> import ...
> # import <x>[, <y>...]
> # Will lose with multiple statements per line and in some
> # other cases. Look at ast tools (possibly
> # http://bitbucket.org/blais/snakefood) which should work on
> # compiled files too.
> imports=$(awk '
> $1=="from" && $3=="import" {list = list "import " $2 ";"}
> $1=="import" {list = list "import "
> for (i=2; i<=NF; i++) {
> if ($i ~ "^#") next
> list = list $i
> if ($i ~ /;$/) next}
> list = list ";"}
> END {print list}' "$file")
> "$libexecdir/singularity/ftrace" $resolver_interp -c "$imports" 2>&1
> >/dev/null |
> while read FILE; do
> if [ ! -f "$INSTALLDIR/c/$FILE" ]; then
> install_file "$FILE"
> fi
> done
> done
> }
> ```

Your bash and awk fu is impressive! Do you want to take a stab at the above
proposal (changing the API for resolver functions)? Just to make sure
nothing gets messed up in the copy/pasting and reformatting, are you open
to forking and sending me a pull request? I am also happy adding you as a
contributor if you want to commit directly.

## 

Gregory M. Kurtzer
Technical Lead and HPC Systems Architect
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by gmkurtzer** [comment]
I forget about timezones... So I ended up implementing this in some shape/form. Check it out and let me know if it includes what you were thinking.

Thanks!

**Comment by loveshack** [comment]
"Gregory M. Kurtzer" notifications@github.com writes:

> > index e8f38f0..3d4e51e 100644
> > --- a/libexec/mods/install.smod
> > +++ b/libexec/mods/install.smod
> > @@ -53,7 +53,10 @@ dep_resolver() {
> > eval $i "$1"
> > done
> > ;;
> > - _ascii_)
> > - exe-ascii*)
> > - unset resolver_interp
> > - [[ $FILE =~ exe-ascii\ (.+) ]] &&
> > - resolver_interp=${BASH_REMATCH[1]}
> >   for i in $TXT_RESOLVERS; do
> >   message 3 "calling txt_resolvers on: $1 : $i\n"
> >   eval $i "$1"
> > 
> > ```
> > ```

Sorry, I thought patches would survive email with the backtick markup.
I think the version of the awk script in the Rep could do with
reinstating some indentation of the clauses.  (By the way, I'm assuming
awk is always in the base system, per GNU standards and the RHEL and
Debian base requirements.)

> Ahh, ok. I've been thinking about this, and instead of making a global
> variable (which in theory could get overwritten and misappropriated by any
> level of recursion) we pass the resolver_interp->BASH_REMATCH[1], directly
> into the resolver function. This will of course take some rework of the
> resolver functions because at present they assume a list of arguments are
> all files to resolve on.

Right.  I'd had made the variable local, but none of the other variables
are local.

> Your bash and awk fu is impressive! Do you want to take a stab at the above
> proposal (changing the API for resolver functions)? Just to make sure
> nothing gets messed up in the copy/pasting and reformatting, are you open
> to forking and sending me a pull request? I am also happy adding you as a
> contributor if you want to commit directly.

I'm not sure about "fu", but I guess that's not relevant now.  (I do
dislike generally having to engage with git(hub) to get things fixed and
not being able to mail a simple patch in this day and age.)

**Comment by gmkurtzer** [comment]
Sent from my iPhone

> On Apr 26, 2016, at 8:18 AM, Dave Love notifications@github.com wrote:
> 
> Sorry, I thought patches would survive email with the backtick markup.
> I think the version of the awk script in the Rep could do with
> reinstating some indentation of the clauses. (By the way, I'm assuming
> awk is always in the base system, per GNU standards and the RHEL and
> Debian base requirements.)

Your assumption about using ask I completely agree with, I'm just not as familiar with it. If you want to send me a patch directly that would be fine too: gmk@lbl.gov

> > Ahh, ok. I've been thinking about this, and instead of making a global
> > variable (which in theory could get overwritten and misappropriated by any
> > level of recursion) we pass the resolver_interp->BASH_REMATCH[1], directly
> > into the resolver function. This will of course take some rework of the
> > resolver functions because at present they assume a list of arguments are
> > all files to resolve on.
> 
> Right. I'd had made the variable local, but none of the other variables
> are local.

The one I was worried about in particular was the interpreter that frype discovered. That I believe was handed down using a global variable. 

> > Your bash and awk fu is impressive! Do you want to take a stab at the above
> > proposal (changing the API for resolver functions)? Just to make sure
> > nothing gets messed up in the copy/pasting and reformatting, are you open
> > to forking and sending me a pull request? I am also happy adding you as a
> > contributor if you want to commit directly.
> 
> I'm not sure about "fu", but I guess that's not relevant now. (I do
> dislike generally having to engage with git(hub) to get things fixed and
> not being able to mail a simple patch in this day and age.)

I agree about email'ing patches. Feel free to email them directly to me or to the Google group for the project.

Thanks!

**Comment by gmkurtzer** [comment]
I'm closing this as I think we fixed this issue... We are copying much less now in 1.x, but in 2.x we will be including much more. Not sure that makes things better, but I think this ticket can be closed at this point.

Thanks!
