### ISSUE TITLE
3.0: Double "/" in SESSIONDIR breaks running containers

### ISSUE THREAD

**Issue by c-ney** [apptainer/singularity#2104]
## Version of Singularity:

3.0.0-beta.1

### Expected behavior

Every path should be "cleaned" at some point with `filepath.Clean` [1].

### Actual behavior

It looks like the "raw" `SESSIONDIR` string is passed through `layout/NewSession` to `mount/AddFS` to `mount/add`. This potentially breaks the `!strings.HasPrefix(mnt.Destination, sessionPath)` check in `singularity/mountGeneric`.

### Steps to reproduce behavior

```bash
./mconfig -p '//usr/local'
cd builddir
make
sudo make install
/usr/local/bin/singularity build -s alpine.sandbox docker://alpine
/usr/local/bin/singularity -d run --userns alpine.sandbox/
...
DEBUG   [U=1011000001,P=6315]mountGeneric()                Skipping mount, /usr/local/var/lib/singularity/mnt/session/final//usr/local/var/lib/singularity/mnt/session doesn't exist in container
...
FATAL   [U=1011000001,P=6315]SMaster()                     container creation failed: hook function for tag sessiondir returns error: failed to create /usr/local/var/lib/singularity/mnt/session/rootfs directory:
mkdir /usr/local/var/lib/singularity/mnt/session/rootfs: permission denied
```

[1] https://golang.org/pkg/path/filepath/#Clean

**Comment by bauerm97** [comment]
Great catch, thanks. I think an easy solution to this (from the Go side at least), is to sanitize the paths which get passed through `src/pkg/buildcfg/gen/gen.go`?

**Comment by GodloveD** [comment]
Just going through some old issues and it seems like this got fixed at some point.   Please request a re-opening if this is still a problem.
