### ISSUE TITLE
--bind /dev is not working with the --contain option (again)

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2108]
## Version of Singularity:

current master
```
$ singularity --version
singularity version b244e688
```
### Description

As per #1907 we must be able to bind `/dev` when the `--contain` or `--containall` flags are used.  This was supposed to be fixed with #1927.  But it looks like it is no longer working in the current version of the code.  Because this is a regression, it seems like we really ought to have some CI testing in place for this as well.  

### Expected behavior
```
$ singularity exec my_container.sif ls -l /dev | wc -l
208

$ singularity exec --contain my_container.sif ls -l /dev | wc -l
13

$ singularity exec --contain --bind /dev my_container.sif ls -l /dev | wc -l
208
```

### Actual behavior

```
$ singularity exec my_container.sif ls -l /dev | wc -l
208

$ singularity exec --contain my_container.sif ls -l /dev | wc -l
13

$ singularity exec --contain --bind /dev my_container.sif ls -l /dev | wc -l
WARNING: Skipping /dev bind mount: failed to add /dev session dir: /dev already exists in layout
13
```

### Steps to reproduce behavior

Try using the `--contain` option along with `--bind /dev`.

**Comment by cclerget** [comment]
@GodloveD I think there is confusion, it works when you provide a full path to a block device like `singularity exec --contain ---bind /dev/infiniband container.sif ls -la /dev/infiniband`, with current version you can't specify `/dev`, `/dev/mqueue/<file>` and `/dev/shm/<file>`, otherwise you can specify any path in `/dev/...`. I will write a fix to allow `/dev` too.

**Comment by GodloveD** [comment]
Thank you for the clarification @cclerget.  Yes @paulo7777 and I were both confused by this.  If you have time it would be useful to have the option to just bind all of `/dev` in case the developer does not know exact devices to bind imho.  Thank you!

**Comment by cclerget** [comment]
Fixed by #2117

**Comment by qhaas** [comment]
Not sure if related, but the `--nv` flag seems to impact this ability, for example:
```
singularity --version
singularity version 3.0.2-87.ga94f0469

grep VERSION= /etc/os-release 
VERSION="18.04.2 LTS (Bionic Beaver)"

# works with only /dev and --nv
singularity exec --nv --contain --bind /dev centos_latest.sif ls -l /dev | wc -l
285

# works with specific file and no --nv
singularity exec --contain --bind /dev/nvidia0:/dev/nvidia0 centos_latest.sif ls -l /dev | wc -l
15

# specific file and --nv a warning
singularity exec --nv --contain --bind /dev/nvidia0:/dev/nvidia0 centos_latest.sif ls -l /dev | wc -l
WARNING: Skipping /dev/nvidia0 bind mount: failed to add /dev/nvidia0 session file: /dev/nvidia0 already exists in layout
48
```

**Comment by DrDaveD** [comment]
@qhaas Does --nv already bind /dev/nvidia0?  If so you're asking it to repeat that and that's what it is complaining about.  It doesn't have to do with this ticket.

**Comment by qhaas** [comment]
From examining the `-d` (debug), it does, you are correct @DrDaveD , it is working as expected then, disregard my comment
