### ISSUE TITLE
3.0: Cannot easily build PIE binaries

### ISSUE THREAD

**Issue by c-ney** [apptainer/singularity#2109]
## Version of Singularity:

3.0.0-beta.1

### Expected behavior

I can easily pass `-buildmode=pie` to `go build` for the singularity binaries. This was possible for singularity prior to 3.0 via the CFLAGS and LDFLAGS variables.

### Actual behavior

You have to manually edit `mlocal/frags/Makefile.stub` to switch the mode, e.g.

```sh
sed -i 's/go build/go build -buildmode=pie/g' mlocal/frags/Makefile.stub
```

### Steps to reproduce behavior

Write here.

**Comment by bauerm97** [comment]
Hey @c-ney, thanks for popping in. Would you mind elaborating a bit on why we would potentially want `-buildmode=pie` option to `go build`? I'm doing a bit of research into this option right now since I wasn't aware of its existence before now. Cheers

**Comment by c-ney** [comment]
I'm currently trying to package singularity for opensuse and they require native binaries to be PIE (as do some other distributions AFAIK, e.g. fedora). From my little knowledge of golang, I believe it's not a "real" issue to not do it. [1] has some discussion (scroll all the way down, Dec 2016).

[1] https://groups.google.com/forum/#!topic/golang-nuts/Jd9tlNc6jUE

**Comment by bauerm97** [comment]
@c-ney Yea, I've been reading through that thread as well. It seems that there's no inherent reason we *can't* introduce a way to compile with `-buildmode=pie`. I'll defer to @yhcote's here since the build system is mostly his creation. Maybe we can allow a flag on `mconfig` to set the go `buildmode` option. Perhaps: `./mconfig -p [...] -buildmode=*`?

**Comment by yhcote** [comment]
@c-ney : Singularity 2 was a C project whereas Singularity 3.0 is a Go project with some C startup files. You can still configure CFLAGS and LDFLAGS like autoconf by editing mlocal/frags/common_opts.mk. This is not going to do what you want though.

I am not a big fan of passing configuration arguments on the command line though unless it's necessary. The best way forward would be to include a golang configuration file where one can tweak and manage the go tools behavior. A bit like mlocal/frags/common_opts.mk that we have for C.

In that way, a user can change defaults by editing that file before running ./mconfig to configure his build.

**Comment by dtrudg** [comment]
I'm going to close this, as the ask was in order to package for SUSE, and Singularity is now packaged in SUSE repos, so I assume the issue is solved. Please reopen if it's not.
