### ISSUE TITLE
Missing packages on ubuntu image

### ISSUE THREAD

**Issue by vladfi1** [apptainer/singularity#212]
I'm creating an ubuntu image with

```
DistType "debian"
MirrorURL "http://us.archive.ubuntu.com/ubuntu/"
OSVersion "xenial"

Setup 
Bootstrap

InstallPkgs git python3-dbg python3-pip python3-zmq g++

Cleanup
```

At the end I see

```
E: Unable to locate package python3-pip
E: Unable to locate package python3-zmq
```

I think these should be available through apt-get.

On a related note, should I be able to install stuff after the bootstrap is finished (inside of a shell with --writable)? I have tried apt-get inside of a shell but it hasn't worked.

**Comment by gmkurtzer** [comment]
What version of Singularity are you using?

What is the error you got when you ran apt-get inside a shell in the container?

**Comment by vladfi1** [comment]
I'm using a recent commit from the master branch (87977f4c26ffb189f286666349bce5c8e979249e).

I can't run apt-get inside the container because I don't have root access, and I'm not sure how to gain it.

**Comment by gmkurtzer** [comment]
Ahh, to get root, try this:

```
$ sudo singularity shell --writable /path/to/container
```

**Comment by vladfi1** [comment]
Resolved by adding `universe` to `/etc/apt/sources.list`.
