### ISSUE TITLE
version command and --version flag are not working in tag

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2120]
## Version of Singularity:

Installed from the [3.0 beta tarball.](https://github.com/sylabs/singularity/archive/v3.0.0-beta.1.tar.gz)

### Expected behavior

`singularity --version` and/or `singularity version` should give you the version number.

### Actual behavior

```
$ singularity version

$ singularity --version
Error: unknown flag: --version
Usage:
  singularity [global options...] <command>

Available Commands:
  build       Build a new Singularity container
  capability  Manage Linux capabilities on containers
  exec        Execute a command within container
  inspect     Display metadata for container if available
  instance    Manage containers running in the background
  keys        Manage OpenPGP key stores
  pull        Pull a container from a URI
  push        Push a container to a Library URI
  run         Launch a runscript within container
  run-help    Display help for container if available
  search      Search the library
  shell       Run a Bourne shell within container
  sign        Attach cryptographic signatures to container
  test        Run defined tests for this particular container
  verify      Verify cryptographic signatures on container
  version     Show application version
```

**Comment by bauerm97** [comment]
So, it looks like the issue is that the source code tarballs that GitHub includes in the release don't include the `.git` directory, meaning there is no git repository present. I think these tarballs are mostly for archival purposes, so I don't think this is an issue. When you do `git checkout v3.0.0-beta.1`, this is the behavior that happens and I'm okay with that:

```
mibauer@bauer-desktop:~$ singularity version
v3.0.0-beta.1
mibauer@bauer-desktop:~$ singularity --version
singularity version v3.0.0-beta.1
```

**Comment by GodloveD** [comment]
Well it's an issue because we are going to have a bunch of users installing from the tarballs in git b/c that is what we've encouraged users to do forever and then they will be reporting errors and we will have no way to tell what version they are running.

**Comment by jscook2345** [comment]
Most apps (in C) have a header file with the version hard coded into it. Just before tagging you usually would run a script to bump the version (in various areas) to the correct one.
