### ISSUE TITLE
`singularity inspect` outputs json by default

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2148]
## Version of Singularity:

singularity version v3.0.0-alpha.2-382-g64b948a6-dirty

### Expected behavior

Only output JSON when `--json` option is used

### Actual behavior

$ singularity inspect Default.sif
{
	"org.label-schema.build-date": "Monday_1_October_2018_23:20:11_CEST",
	"org.label-schema.schema-version": "1.0",
	"org.label-schema.usage.singularity.deffile.bootstrap": "busybox",
	"org.label-schema.usage.singularity.deffile.mirrorurl": "https://www.busybox.net/downloads/binaries/1.26.1-defconfig-multiarch/busybox-x86_64",
	"org.label-schema.usage.singularity.version": "v3.0.0-alpha.2-382-g64b948a6-dirty"
}

$ singularity inspect --json Default.sif
{
	"attributes": {
		"labels": "{\n\t\"org.label-schema.build-date\": \"Monday_1_October_2018_23:20:11_CEST\",\n\t\"org.label-schema.schema-version\": \"1.0\",\n\t\"org.label-schema.usage.singularity.deffile.bootstrap\": \"busybox\",\n\t\"org.label-schema.usage.singularity.deffile.mirrorurl\": \"https://www.busybox.net/downloads/binaries/1.26.1-defconfig-multiarch/busybox-x86_64\",\n\t\"org.label-schema.usage.singularity.version\": \"v3.0.0-alpha.2-382-g64b948a6-dirty\"\n}"
	},
	"type": "container"
}

**Comment by ciarant** [comment]
That appears to be in line with the [behaviour described in the docs](https://www.sylabs.io/guides/2.6/user-guide/appendix.html#inspect-flags)?

**Comment by phpHavok** [comment]
@jscook2345 You can assign this to me if you want. I've noticed a couple of other unusual things about `singularity inspect` that I'd like to clean up as well.

**Comment by jscook2345** [comment]
@phpHavok Go for it!
