### ISSUE TITLE
help_test.go is not really testing anything

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2171]
## Version of Singularity:

$ singularity version
55ab47ee

### Expected behavior

[help_test.go](https://github.com/sylabs/singularity/blob/master/src/cmd/singularity/help_test.go) should test the std out of each test and see if it matches the expectation.  

### Actual behavior

help_test.go only tests error codes from conda.  This sort of made sense in the 2.x series because a command like `singularity blah` and `singularity --bogus` would return an error.  But now those commands return help docs in std out and exit with an error code of 0.
 
### Steps to reproduce behavior

```
$ singularity blah
$ echo $?
0
```

**Comment by phpHavok** [comment]
Related Issue #2146 
Related PR #2419
