### ISSUE TITLE
Need to test build command options

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2173]
## Version of Singularity:

```
$ singularity version
55ab47ee
```

### Expected behavior
We should have a suite of tests to test all `build` command options (and also some plausible combinations of build flags).

### Actual behavior

We are not testing flags.

**Comment by GodloveD** [comment]
Just to be more specific this is the `singularity build` command and associated flags.

**Comment by dtrudg** [comment]
See #4079
