### ISSUE TITLE
shell command must be tested

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2174]
Feel free to close if this issue is already being tracked elsewhere

## Version of Singularity:

```
$ singularity version
55ab47ee
```

### Expected behavior

We **must** have tests for the `shell` command.

### Actual behavior

No tests of the shell command are being done.

**Comment by ArangoGutierrez** [comment]
on PR:
 - https://github.com/sylabs/singularity/pull/2155

we are introducing some basic shell test (via STDIN pipe)
https://github.com/sylabs/singularity/blob/b70edf36fbc4dce7ef6c8da47640405f1510e606/src/cmd/singularity/actions_test.go#L155

https://github.com/sylabs/singularity/blob/b70edf36fbc4dce7ef6c8da47640405f1510e606/src/cmd/singularity/actions_test.go#L156

https://github.com/sylabs/singularity/blob/b70edf36fbc4dce7ef6c8da47640405f1510e606/src/cmd/singularity/actions_test.go#L157
