### ISSUE TITLE
Need to test env var binding to flags

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2196]
## Version of Singularity:

current master

### Expected behavior

Have some tests that set env vars (like `$SINGULARITY_CLEANENV`) and then test to see that they so the appropriate thing.

### Actual behavior

There are no such tests.

**Comment by GodloveD** [comment]
https://github.com/sylabs/singularity-userdocs/blob/c62f73a945ab7a739a2aee62743f17d9f9cc8b29/appendix.rst

**Comment by GodloveD** [comment]
`SINGULARITY_ENV*`, `SINGULARITY_LIB*`, and any others that are not binded to flags.

And then bool, string, and stringNslice (or whatever the various types are) . 1 of each.

**Comment by GodloveD** [comment]
Here are the env vars that I think need to be tested to cover most of the main functionality and the corner cases.  If these env vars are working properly there is a high probability that other env vars are working properly as well (as long as the actual options are tested in the e2e framework.  

`SINGULARITY_BIND` <- This one is special because the contents of an environment variable should be combined with any command line args. (It's the only example of a envAppend var)
`SINGULARITYENV_*` (just 1 or 2 examples should suffice)
`SINGULARITY_IMAGE`
`SINGULARITY_NOCLEANUP` <- envBool
`SINGULARITY_TMPDIR` <- envStringNSlice
`SINGULARITY_CACHEDIR`
`SINGULARITY_CONTAINLIBS`

Note that any command line arguments should render the env vars null and void with the one exception of the `SINGULARITY_BIND` variable listed above.

**Comment by dtrudg** [comment]
Tested in e2e....

- SINGULARITY_BIND
- SINGULARITYENV_*
- SINGULARITY_TMPDIR
- SINGULARITY_CACHEDIR

Not tested at present...

- SINGULARITY_IMAGE
- SINGULARITY_CONTAINLIBS

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@GodloveD Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
