### ISSUE TITLE
No module named site error for a python-based package

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#22]
Tried building a singularity container of a python-based GUI application (xpra) from xpra.org from an rpm package installed under RHEL-7.0 from the upstream repository. Singularity built xpra.sapp without errors, but when I try running the container on the same system I built it on I get the following error

$ singularity run xpra
ImportError: No module named site

Here's the spec file:

$ cat spec/xpra
Name: xpra
Maintainer: local
Exec: /usr/bin/xpra

%packages
xpra

It looks like a few python-related fixes went into singularity recently, so this build could either be triggering another bug or I'm just not doing it right.

**Comment by moskalenko** [comment]
It doesn't look like PYTHONPATH within the sapp container contains a path to the sapp equivalent of the original /usr/lib64/python2.7/site-packages/xpra/ directory

/usr/bin/xpra script contains

#!/usr/bin/python2

from xpra.platform import init, set_default_name
set_default_name("Xpra")
init()

import sys
from xpra.scripts.main import main
sys.exit(main(sys.argv[0], sys.argv))

**Comment by gmkurtzer** [comment]
Ahhh, you are using python2! I didn't account for that when I figure out the PYTHONHOME environment variable.

You should be able to quickly fix it by using '#!/usr/bin/python' as your interpreter, or pulling from the latest master branch and reinstalling.

**Comment by loveshack** [comment]
I guess this will also be affected by using the wrong interpreter to derive the module requirements, as in #21 (which I can't re-open).

The changes for that allow me to use python27 from the RHEL6 SCL without this change (as long as I build with the SCL enabled, to get LD_LIBRARY_PATH), but if PYTHONHOME is necessary, shouldn't it be inherited from the environment?

**Comment by gmkurtzer** [comment]
Are you thinking of inheriting it from the build or execution host? if you are thinking from the build host, I totally agree! ... But... Where does python usually get the PYTHONHOME from? it isn't in the default environment.

With that said, I just removed PYTHONHOME from the singularity environment and it seems to be working. I wonder if the updates to ftrace are now catching the proper configuration files for python to determine it's own PYTHONHOME?

**Comment by moskalenko** [comment]
Thanks, I changed the shebang line and am rebuilding the sapp container. It's only been a few hours since the build started. The builds take a while it seems and appear to be i/o bound as cpu use by singularity is under 30% of a single core.

As far as using python from the execution host's environment there are some caveats there, too.

**Comment by gmkurtzer** [comment]
Oh, that is weird... Something else is broke, it shouldn't take more then a few minutes.

Are you testing with the master branch? if so, can you re-pull it and try again?

**Comment by loveshack** [comment]
"Gregory M. Kurtzer" notifications@github.com writes:

> Are you thinking of inheriting it from the build or execution host?

Build, if anywhere, since that's whence you copy the libraries.

> if
> you are thinking from the build host, I totally agree!
> ... But... Where does python usually get the PYTHONHOME from? it isn't
> in the default environment.

I think it usually doesn't, as you observe.  It has built-in search
path(s).

> With that said, I just removed PYTHONHOME from the singularity
> environment and it seems to be working. I wonder if the updates to
> ftrace are now catching the proper configuration files for python to
> determine it's own PYTHONHOME?

pymods.dep is still using `which python` to run the interpreter, even if
that's python 2 and the scripts has something like #!/usr/bin/python3.
That can't be right, but as far as I can tell, it DTRT if you use the
interpreter line that ftype prints (in testing with an RHEL python SCL).

**Comment by gmkurtzer** [comment]
Hi @moskalenko 

Can you please the master branch test again and let me know how it works for you now? Xpra should now work just fine without modification of the interpreter line.

Thanks!

**Comment by moskalenko** [comment]
Thanks for the fix. I built the container, but there's now an issue with running xpra as it needs to create files in ~/.xpra and then parse them to show the list of instances. However, running under singularity this is not happening.

**Comment by gmkurtzer** [comment]
Hrmm... if you run it through "singularity strace ..." can you get any details as to why it is failing? Maybe attach the strace output and I'm happy to look through it.

Singularity containers automatically have access to your home directory unless you specify the -C run flag.

**Comment by moskalenko** [comment]
I opened a shell inside singularity and here's the error that xpra is encountering when singularity starts it:

xpra main error:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/scripts/main.py", line 124, in main
    return run_mode(script_file, err, options, args, mode, defaults)
  File "/usr/lib64/python2.7/site-packages/xpra/scripts/main.py", line 922, in run_mode
    return run_server(error_cb, options, mode, script_file, args)
  File "/usr/lib64/python2.7/site-packages/xpra/scripts/server.py", line 885, in run_server
    xvfb, display_name = start_Xvfb(opts.xvfb, display_name)
  File "/usr/lib64/python2.7/site-packages/xpra/scripts/server.py", line 654, in start_Xvfb
    stdin=subprocess.PIPE, preexec_fn=setsid)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1326, in _execute_child
    child_exception = pickle.loads(data)
  File "/usr/lib64/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib64/python2.7/pickle.py", line 971, in load_string
    self.append(rep.decode("string-escape"))
LookupError: unknown encoding: string-escape

**Comment by gmkurtzer** [comment]
The error you are getting is something that I've fixed by including the string_escape.py\* Python modules into my specfile.

Additionally, you are one of many people that have been having issues with packaging so I've been working towards a different model for Singularity images such that we can very easily (and quickly) incorporate a larger amount of code into the container without adversely affecting invocation performance. Now you can include all of Python, and all of the Python modules you want into the image.

If you have an opportunity, I'd love it if you can test the master branch. Documentation is still sparse (with the exception of the README.md file), but if you have any questions ask the Google Group or send me email directly.

Thanks!

**Comment by moskalenko** [comment]
Thank you, I most definitely will test the master branch since this is the main application I need the singularity-level portability for on the cluster asap.

**Comment by gmkurtzer** [comment]
Since there isn't much documentation I can help you with some of this possibly in real time early next week. Send me an email and we can organize a time. In exchange id appreciate some help with documentation. :)

Thanks!

Sent from my iPhone

**Comment by moskalenko** [comment]
Hi Gregory,

I took some time off and just came back to work. I built singularity
from the master and noticed that a lot has changed. You're moving at a
speed of light. I see, for example, that there's no longer a
'singularity build' command. Is there any documentation on app container
building?

Thanks,

Alex

**Comment by gmkurtzer** [comment]
Hi!

Yes, things have been moving very fast. Unfortunately the only documentation so far is the README.md file, but it should hopefully have enough pointers to get started. 

In a nutshell, SAPPS are now sparse images and you can build a mini version of the distribution focused specifically in what you need. For example, build an image specifically for Python. 

Give it a shot and let me know what you find. Documentation is on its way!!

Greg

Sent from my iPhone
