### ISSUE TITLE
bootstrap issue under corp network proxy

### ISSUE THREAD

**Issue by jdongca2003** [apptainer/singularity#220]
The machine is under corp network proxy. The OS in that machine is CentOS Linux release 7.2.1511.

In host /etc/yum.conf, I can perform 'yum install' via set 'proxy=...'.

sudo singularity create demo-1.img
sudo singularity bootstrap demo-1.img centos.def 
## centos.def

RELEASE=7

DistType "redhat"
MirrorURL "http://mirror.centos.org/centos-${RELEASE}/${RELEASE}/os/\$basearch/"

Setup
Bootstrap

InstallPkgs yum vim-minimal python procps-ng

Cleanup
# 

error message from bootstrap command:
Found YUM at: /bin/yum
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:fad0:3404:1::10: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:fad0:3404:1::10: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:fad0:3404:1::10: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:fad0:3404:1::10: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:fad0:3404:1::10: Network is unreachable"

I tried the above command on other machine without corp network proxy. It worked.

**Comment by gmkurtzer** [comment]
I don't recall... Does YUM use the "http_proxy" environment variable, or a different envar? A proxy config shouldn't go in the bootstrap as it is target host specific, so I would prefer to make it an environment variable. Would be easiest if YUM does the same, but if I have to grab from the environment, and then write the yum.conf accordingly, I can do that too.

**Comment by jdongca2003** [comment]
Hi, Greg
thank for your quick reply.  My .bash_profile has already contained http_proxy envs.
"
CORP_PROXY="http://.."
export HTTP_PROXY=$CORP_PROXY
export HTTPS_PROXY=$CORP_PROXY
export http_proxy=$CORP_PROXY
export https_proxy=$CORP_PROXY
"
Behind the proxy, I can directly download  'http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml' via wget.  Yum can also use 'http_proxy' env for a single user (https://www.centos.org/docs/5/html/yum/sn-yum-proxy-server.html)

I used 2.1.2 release (singularity-2.1.2.tar.gz https://github.com/gmkurtzer/singularity/releases)

Probably the corp proxy server disables some site access. 

Thanks

Jianxiong

**Comment by gmkurtzer** [comment]
Hi Jianxiong,

So it wouldn't be so difficult to read in from those variables and set the right configuration in the yum.conf that get's bootstrapped.

I will implement this in the soon to be released 2.2 code and using the new specfile format (check master:examples/\* for syntax). I will let you know when it is implemented so you can test. :)

Thanks!
Greg

**Comment by gmkurtzer** [comment]
ok, can you test [master 2d3ca7c]? .. It will read in from your $http_proxy variable.

**Comment by jdongca2003** [comment]
No luck. The issue still exists.  I checked out code from master branch and then followed install instructions from http://singularity.lbl.gov/#install (Section: Build an RPM from source)
I found your fix there 
$ git log
....

> commit c7490d41fd83a5313897bb363256ab75930ba3fa
> Author: Gregory M. Kurtzer gmkurtzer@lbl.gov
> Date:   Fri Sep 23 11:03:41 2016 -0700

```
Disable overlayfs by default (causing kernel panic on RHEL7)
```

commit 2d3ca7cfe348a7db372c4f402246838a2b9c5940
Author: Gregory M. Kurtzer gmkurtzer@lbl.gov
Date:   Fri Sep 23 11:03:28 2016 -0700

```
Potential fix for proxy
```

> singularity --version
> 2.2

## centos.def

$ more centos.def 
RELEASE=7

DistType "redhat"
MirrorURL "http://mirror.centos.org/centos-${RELEASE}/${RELEASE}/os/\$basearch/"

Setup
Bootstrap

InstallPkgs yum vim-minimal python procps-ng

## Cleanup

---

$sudo singularity create demo-1.img
Creating a new image with a maximum size of 768MiB...
Executing image create helper
Formatting image with ext3 file system
Done.
$ sudo singularity bootstrap demo-1.img centos.def 

Found YUM at: /bin/yum
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2604:1580:fe00:4::10: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2604:1580:fe00:4::10: Network is unreachable"
Trying other mirror.

 One of the configured repositories failed (Linux $releasever - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

```
 1. Contact the upstream for the repository and get them to fix the problem.

 2. Reconfigure the baseurl/etc. for the repository, to point to a working
    upstream. This is most often useful if you are using a newer
    distribution release than is supported by the repository (and the
    packages for the previous distribution release still work).

 3. Disable the repository, so yum won't use it by default. Yum will then
    just ignore the repository until you permanently enable it again or use
    --enablerepo for temporary usage:

        yum-config-manager --disable repo-0

 4. Configure the failing repository to be skipped, if it is unavailable.
    Note that yum will try to contact the repo. when it runs most commands,
    so will have to try and fail each time (and thus. yum will be be much
    slower). If it is a very temporary problem though, this is often a nice
    compromise:

        yum-config-manager --save --setopt=repo-0.skip_if_unavailable=true
```

failure: repodata/repomd.xml from repo-0: [Errno 256] No more mirrors to try.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:4d00:1:100:213:72ff:fefc:622e: Network is unreachable"
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2604:1580:fe00:4::10: Network is unreachable"
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2604:1580:fe00:4::10: Network is unreachable"

**Comment by gmkurtzer** [comment]
Hi, you need to test with the new bootstrap format as they take different paths in the code. Please check the examples/ directory to see the new syntax and please try again. 

Thank you.

**Comment by jdongca2003** [comment]
I tried 'centos.def ' here (https://github.com/gmkurtzer/singularity/blob/master/examples/centos.def). I still got the similar error message:

"$ sudo singularity bootstrap demo-1.img centos.def 
Bootstrap initialization
Checking bootstrap definition
Executing Prebootstrap module
Executing Setup module
Executing Bootstrap 'redhat' module
Found YUM at: /bin/yum
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:fad0:3404:1::10: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:fad0:3404:1::10: Network is unreachable"
Trying other mirror.
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:fad0:3404:1::10: Network is unreachable"
Trying other mirror.
"

**Comment by gmkurtzer** [comment]
Can you mount the image and confirm that the proxy statement occurs correctly in the container's `/etc/bootstrap-yum.conf`?

Thanks!

**Comment by jdongca2003** [comment]
It seemed that http_proxy was not in bootstrap-yum.conf. Inside the image, I found that proxy was in /etc/yum.conf.  $http_proxy was not defined. 

Inside the image, after I exported the following envs. and I can download contents from internet.

export http_proxy=http://proxy_ip:port
export https_proxy=http://proxy_ip:port
export HTTP_PROXY=http://proxy_ip:port
export HTTPS_PROXY=http://proxy_ip:port

wget yahoo.com

---

sudo singularity mount ./demo-1.img /extra/image

Mounted image './demo-1.img' into '/var/singularity/mnt/final'

Starting /bin/sh... To unmount, exit this shell.

./demo-1.img:/var/singularity/mnt/final> cd /var/singularity/mnt/final/
./demo-1.img:/var/singularity/mnt/final> ls
dev  environment  etc  lost+found  var
./demo-1.img:/var/singularity/mnt/final> cd etc
./demo-1.img:/var/singularity/mnt/final> ls
bootstrap-yum.conf
./demo-1.img:/var/singularity/mnt/final> more bootstrap-yum.conf 
[main]
cachedir=/var/cache/yum-bootstrap
keepcache=0
debuglevel=2
logfile=/var/log/yum.log
syslog_device=/dev/null
exactarch=1
obsoletes=1
gpgcheck=0
plugins=1
reposdir=0

[base]
name=Linux $releasever - $basearch
baseurl=http://mirror.centos.org/centos-7/7/os/$basearch/
enabled=1
gpgcheck=0

./demo-1.img:/var/singularity/mnt/final> echo $http_proxy

./demo-1.img:/var/singularity/mnt/final> cd /etc/
./demo-1.img:/var/singularity/mnt/final> more yum.conf
[main]
cachedir=/var/cache/yum/$basearch/$releasever
keepcache=0
debuglevel=2
logfile=/var/log/yum.log
exactarch=1
obsoletes=1
gpgcheck=1
plugins=1
installonly_limit=5
bugtracker_url=http://bugs.centos.org/set_project.php?project_id=23&ref=http://bugs.centos.org/bug_report_page.php?
category=yum
distroverpkg=centos-release
proxy=http://ip:port

**Comment by gmkurtzer** [comment]
I just added a minor change, but this is what I'm getting:

```
$ sudo http_proxy=http://proxy_ip:port singularity bootstrap /tmp/foo examples/centos.def 
Bootstrap initialization
Checking bootstrap definition
Executing Prebootstrap module
Executing Setup module
Executing Bootstrap 'redhat' module
Found YUM at: /usr/bin/yum
http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 5 - "Could not resolve proxy: proxy_ip"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
ERROR: Bootstrap failed... exiting
ERROR: Aborting with RETVAL=255
```

Can you retest with current master?

Thanks!

**Comment by jdongca2003** [comment]
I checked out master branch and re-installed it. It worked well if i followed your command (
sudo http_proxy=http://proxy_ip:port singularity bootstrap demo-1.img centos.def).

If I just run "sudo singularity bootstrap demo-1.img centos.def", it will not work.  The same error message as before.  The environment variable "http_proxy" has been already exported in .bash_profile. I am curious why it did not work

---

sudo http_proxy=http://proxy_ip:port singularity bootstrap demo-1.img centos.def

Bootstrap initialization
Checking bootstrap definition
Executing Prebootstrap module
Executing Setup module
Executing Bootstrap 'redhat' module
Found YUM at: /bin/yum
base                                                                                                                               | 3.6 kB  00:00:00  
(1/2): base/x86_64/group_gz                                                                                                        | 155 kB  00:00:00  
(2/2): base/x86_64/primary_db                                                                                                      | 5.3 MB  00:00:04  
Resolving Dependencies
--> Running transaction check
---> Package centos-release.x86_64 0:7-2.1511.el7.centos.2.10 will be installed
---> Package coreutils.x86_64 0:8.22-15.el7 will be installed
--> Processing Dependency: rtld(GNU_HASH) for package: coreutils-8.22-15.el7.x86_64
--> Processing Dependency: ncurses for package: coreutils-8.22-15.el7.x86_64
...
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 2:vim-minimal-7.4.160-1.el7.x86_64                                                                                                     1/1 
  Verifying  : 2:vim-minimal-7.4.160-1.el7.x86_64                                                                                                     1/1 

Installed:
  vim-minimal.x86_64 2:7.4.160-1.el7                                                                                                                      

Complete!

## Done.

**Comment by gmkurtzer** [comment]
Who's .bash_profile did you export the variable?

sudo will sanitize the environment and thus you won't see all variables. For instance, is it present when you run 'sudo env'? 

In any case, that is great news, thanks for the help debugging!

**Comment by jdongca2003** [comment]
Hi, Greg,
    Thank for great help.  My user account is in sudoer list.

I ran 'sudo singularity in my account where .bash_profile exports http_proxy.

But in root user, http_proxy env was not exported. When i ran 'sudo
env', http_proxy was not there.

This may explain that I need to use your command.

Jianxiong
