### ISSUE TITLE
Comments before "Bootstrap" in definition file not supported in 3.0

### ISSUE THREAD

**Issue by TormodLandet** [apptainer/singularity#2211]
Previously an image definition file could start with a comment describing the file (multiple lines starting with #). In the 3.0 version this gives a cryptic error:

```
FATAL:   Unable to create build: unable to get conveyorpacker: invalid build source
```

Removing the initial comment such that `Bootstrap:` are the first characters in the file makes the error go away. I would suggest skipping commented lines such that a brief description of the file can be included on the top as is normal in many programming languages etc

**Comment by bauerm97** [comment]
Oh yikes, good catch. A bit embarrassing that we didn't catch this. We'll correct this behavior going forward. Cheers
