### ISSUE TITLE
A user could influence the syslog strings by symlinking the starter-suid

### ISSUE THREAD

**Issue by eriksjolund** [apptainer/singularity#2212]
## Version of Singularity:

3.0.0 (running on Ubuntu 18.04.1)

### Expected behavior

The user should not be able to influence the log message in /var/log/syslog in this way.

### Steps to reproduce behavior

As a normal user run

    ubuntu@laptop:~$ export SINGULARITY_MESSAGELEVEL=1
    ubuntu@laptop:~$ ln -s /usr/local/libexec/singularity/bin/starter-suid foobar
    ubuntu@laptop:~$ ./foobar 
    ERROR  : SRUNTIME environment variable isn't set
    ubuntu@laptop:~$ 

As root run this command

    root@laptop:~# grep foobar /var/log/syslog
    Oct 10 14:09:27 laptop Singularity: foobar (U=0,P=17206)> SRUNTIME environment variable isn't set
    root@laptop:~# 

The relevant source code seems to be:

    ubuntu@laptop:~/go/src/github.com/sylabs/singularity$ grep syslog_st ./src/runtime/c/lib/util/message.c |grep snprintf
            if (snprintf(syslog_string, 540, "%s (U=%d,P=%d)> %s", __progname, geteuid(), getpid(), message) >= 540) {
    ubuntu@laptop:~/go/src/github.com/sylabs/singularity$ 

Note, Unix filenames are not just limited to alphanumeric characters. If I remember correctly everything but the character slash is permitted.

**Comment by cclerget** [comment]
Thanks @eriksjolund ! Indeed this is an oversight from v2 C code and logging to syslog must be removed to be aligned with Go sylog package.
