### ISSUE TITLE
very minor update to 3.0.0 release notes

### ISSUE THREAD

**Issue by kaczmarj** [apptainer/singularity#2213]
Hello, congratulations on the 3.0.0 release! In the release notes,

```
$(GOPATH)/src/github.com/sylabs/singularity
``` 

should be 

```
${GOPATH}/src/github.com/sylabs/singularity
```

This is very minor but might be helpful to some users.

**Comment by ArangoGutierrez** [comment]
good catch @kaczmarj !!!
