### ISSUE TITLE
3.0.0 singularity pull no long accepts --name, but this is not mentioned in the changelog

### ISSUE THREAD

**Issue by mr-c** [apptainer/singularity#2214]
Hello and congratulations on the new Singularity release! 

## Version of Singularity:

3.0.0

### Expected behavior

Conventional command line invocations that worked in v2.[56].x continue to work in v3.0.0, except as documented at https://github.com/sylabs/singularity/blob/master/CHANGELOG.md

Example from the CWL reference runner, `cwltool`

```
['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']
```
(Singularity downloads the docker container and saves it as a Singularity image using the value of `--name`)

### Actual behavior

`--name` is not listed on the v3.0.0 changelog

```
['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']
Error: unknown flag: --name
Usage:
singularity [global options...] pull [pull options...]
```

### Steps to reproduce behavior
Install Singularity v3.0.0
```
singularity pull --force --name kernsuite-prefactor.img docker://kernsuite/prefactor
```

**Comment by bauerm97** [comment]
Hi @mr-c , thanks for pointing this out. The syntax to preform this action is now `singularity pull <name> <uri>`. In your example, `singularity pull kernsuite-prefactor.img docker://kernsuite/prefactor` will work as expected. Sorry for the confusion

**Comment by mr-c** [comment]
Can you accept the old syntax?

**Comment by pditommaso** [comment]
+1 for having `--name` option as alternative syntax as @mr-c is suggesting. Application invoking singularity tool programmatically are not aware of the underling version therefore cannot switch to the new syntax without breaking existing applications.

**Comment by pditommaso** [comment]
it works like a charm. Well done folks!
