### ISSUE TITLE
"vault" release for 2.6?

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#2216]
Heyo! Is (or should there be?) a vault-2.6 branch for Singularity 2.6, or is the `release-2.6` the equivalent? Just curious, what is the difference between a "release-X" branch and a "vault-X" branch? Thanks!

**Comment by GodloveD** [comment]
Thanks for the catch @vsoch!  Yes, release-2.6 should be "vaulted".

**Comment by GodloveD** [comment]
Just made the change.  Thanks again!  😸

**Comment by vsoch** [comment]
Awesome, thanks @GodLoveD.
