### ISSUE TITLE
Singularity pull --name option 

### ISSUE THREAD

**Issue by pditommaso** [apptainer/singularity#2217]
## Version of Singularity:

3.0.0

### Expected behavior

Prior to version 3.0 `singularity pull --name <file name> <URL>` allowed pull a container image and store it with the specified name.

### Actual behavior

The pull command does not provide any more the `--name` option. This break existing application relaying in that option. 

### Steps to reproduce behavior

```
$ singularity pull --name foo.img  docker://nextflow/rnaseq-nf
Error: unknown flag: --name
```

**Comment by ArangoGutierrez** [comment]
#2214

**Comment by pditommaso** [comment]
Thanks for pointing it out. Closing in favour of #2214.
