### ISSUE TITLE
Should be able to build images from URIs with no root permission

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2227]
## Version of Singularity:

```
$ singularity version
v3.0.0-9-g53abdf90
```

### Expected behavior

In Singularity 2.6
```
$ singularity build bb shub://GodloveD/busybox
Cache folder set to /home/vagrant/.singularity/shub
Progress |===================================| 100.0%
Building from local image: /home/vagrant/.singularity/shub/GodloveD-busybox-master-latest.simg
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building Singularity image...
Singularity container built: bb
Cleaning up...
```
### Actual behavior

In 3.0
```
$ singularity build bb library://busybox
INFO:    Starting build...
 728.00 KiB / 728.00 KiB [================================================] 100.00% 3.36 MiB/s 0s
ERROR:   unpackSIF Failed: While copying partition data to bundle: permission denied
FATAL:   While performing build: packer failed to pack: While copying partition data to bundle: permission denied
```

Strangely enough, the same thing from Docker Hub works in 3.0.

```
$ singularity build bb docker://busybox
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:90e01955edcd85dac7985b72a8374545eac617ccdddcc992b732e43cd42534af
Copying config sha256:d98834fba17e4121dc21f65d6ddf2f648da119c86d72ffea8145e496bda621fd
 574 B / 574 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: bb
```

### More info

This is what we want in 3.0 too (minus the ext3 which is no longer supported of course).  Green means you can build without root while red requires root.  So basically everything except for building from a def file should be permitted without root privs. 

![build_input_output](https://user-images.githubusercontent.com/7672924/46877476-f62fec80-ce0e-11e8-86f1-f0a1053a36eb.png)

**Comment by bauerm97** [comment]
Well, I'm not sure this is possible without some really weird workaround. `singularity build ...` is actually taking the container image (which from library is SIF), extracting it ( <- problem here ), and then packing it back into a SIF.  We can't extract the squashfs from SIF without root, since in order to do so we have to mount the image via a `loopback` device which requires root to do.

An easy way to get this functionality is `singularity pull bb library://busybox` instead.

**Comment by GodloveD** [comment]
That explains why it works for Docker Hub but not for library or shub.  @ikaneshiro what do you think?

**Comment by ikaneshiro** [comment]
@GodloveD I think this is fine moving forwards as long as `pull` is documented as the typical way to fetch a container. If you want something from a container library you should `pull` it, if you want to use something from a library as a base for a new build you `build` it with `sudo` just like you would if it was used in a deffile.

**Comment by wfang** [comment]
The document here: https://www.sylabs.io/guides/3.0/user-guide/build_a_container.html still refers to the **build**:
**sudo singularity build lolcow.simg library://sylabs-jms/testing/lolcow**
 which will fail and **pull** will fix it.

**Comment by GodloveD** [comment]
Heya @wfang I will raise an issue on the user guide repo.  If you would like to submit a PR to update the docs it would be very welcome!  Thank you. 

https://github.com/sylabs/singularity-userdocs/issues/66
