### ISSUE TITLE
environment not reliably loaded for 2.2-style ext3-format container

### ISSUE THREAD

**Issue by 0xaf1f** [apptainer/singularity#2233]
## Version of Singularity:

3.0.0

### Expected behavior

For an ext3 container image built with Singularity 2.2, I expected that its environment file should be loaded when using it in Singularity 3.0. I'm breaking this down into 3 cases:

1. exec
2. shell
3. shell + `--writable`

### Actual behavior

The environment is only loaded when using `--writable` (case 3).

### Steps to reproduce behavior

With `container` defined as an ext3-format container created by Singularity 2.2 (when `/environment` was still a thing), basically check to see whether the `/environment` file is getting loaded by looking up a variable that gets defined there:

```console
$ singularity exec $container cat /environment
...
...
export DEBUG_ENVLOADED=1
```

#### case 1
```console
$ singularity exec $container env | grep '^DEBUG'
```

#### case 2
```console
$ singularity shell $container
Singularity > env | grep '^DEBUG'
```

#### case 3
```console
$ singularity shell --writable $container
Singularity > env | grep '^DEBUG'
```

**Comment by moskalenko** [comment]
Singularity-3.0.0 ignoring /environment for exec appears to be the bug that's breaking workflows using older ext3 containers in production on our system.

**Comment by cclerget** [comment]
@0xaf1f It works with `--writable` because `/.singularity.d/actions` is not mounted as this directory doesn't exist in old ext3 container, so the container process fallback to `/.exec` or `/.shell`. Work on the fix

**Comment by 0xaf1f** [comment]
I can confirm this is also working now in 3.0.1.

**Comment by jscook2345** [comment]
@0xaf1f Excellent! Thanks for letting us know!
