### ISSUE TITLE
Add "passphrase confirm" feature

### ISSUE THREAD

**Issue by yhcote** [apptainer/singularity#2238]
## Version of Singularity:

v3.0.0

### Expected behavior

singularity keys newpair should ask to confirm key encryption passphrase

### Actual behavior

It doesn't

### Steps to reproduce behavior

singularity keys newpair

**Comment by jscook2345** [comment]
@WestleyK This looks like it got lost and I was about to report it as an issue. Can you take this on since you're already working on keys features?

Thanks!

**Comment by WestleyK** [comment]
@jscook2345, On it!
