### ISSUE TITLE
Allow users to specify their own shebangs in runscript and startscript

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#2260]
## Version of Singularity:

3.0.0

### Expected behavior

Singularity should parse the first line of a `runscript` or `startscript` to see if the first non-whitespace characters are `#!`. If this is the case, it should use that line as the shebang and not the default `#!/bin/sh`.

### Actual behavior

The default shebang, `#!/bin/sh`, is always prepended to the `runscript` or `startscript`.
```
ian@T440s:test$ singularity inspect -r test.sif

#!/bin/sh

#!/usr/bin/env python
print("Uh-oh, there's a snake in my container")
```

### Steps to reproduce behavior

Build a container with a definiton that has a runscript with a shebang like the example below.

```
ian@T440s:test$ cat shebang.def 
Bootstrap: docker
From: python:latest

%runscript
#!/usr/bin/env python
print("Uh-oh, there's a snake in my container")
```

**Comment by GodloveD** [comment]
My name is @GodloveD and I endorse this issue.
