### ISSUE TITLE
Singularity 3.0.0 no longer logs actions

### ISSUE THREAD

**Issue by treydock** [apptainer/singularity#2267]
## Version of Singularity:

3.0.0

### Expected behavior

I'd expect setuid actions executed by Singularity to be logged.  This is what I would see in 2.6.0 for example:

```
Oct 16 11:36:35 o0115 Singularity: action-suid (U=20821,P=126376)> USER=tdockendorf, IMAGE='vsoch-hello-world-master-latest.simg', COMMAND='run'
```

### Actual behavior

Singularity writes nothing to syslog when commands are executed.

### Steps to reproduce behavior

```
$ singularity exec docker://centos:7 cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core)
```

Check /var/log/messages and nothing is written except kernel messages about squashfs.

**Comment by bne86** [comment]
Are there any news regarding this topic? We would be interested in exactly this functionality.

**Comment by dtrudg** [comment]
relevant discussion with resolution via an example plugin is now at #4992
