### ISSUE TITLE
Depending on git tags for the version number is problematic

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2268]
## Version of Singularity:

master branch

I think that depending on the git tag for mconfig to find a version number is more trouble than it is worth.  First, it doesn't work when there is no git.  Even with git, tags are not normally synchronized when people do git fetch or git pull, you have to explicitly do 'git fetch upstream --tags'.  I was testing travis in my own repository and it failed in obscure ways until I realized that I had never done 'git push origin --tags'.  This will continue to be a pain for people because people are not used to it.

I think it would be better to just check in a VERSION file into git and manually update the version as part of the release process.  That would also significantly simplify the make-dist.sh script and probably other things as well.  The default version set by mconfig can still add in the git describe info if it is available.

**Comment by 0xaf1f** [comment]
> Even with git, tags are not normally synchronized when people do git fetch or git pull, you have to explicitly do 'git fetch upstream --tags'

That's not been my experience. The man page also says so:

> By default, any tag that points into the histories being fetched is also fetched; the effect is to fetch tags that point at branches that you are interested in. This default behavior can be changed by using the --tags or --no-tags options or by configuring remote.<name>.tagOpt. By using a refspec that fetches tags explicitly, you can fetch tags that do not point into branches you are interested in as well.

Tags aren't *pushed* by default though, which explains what you experienced here:

> I was testing travis in my own repository and it failed in obscure ways until I realized that I had never done 'git push origin --tags'.

**Comment by DrDaveD** [comment]
That's interesting, I wasn't aware of that.  When I look at git fetch --help on el6 and el7 gits they both say essentially the same thing but in different ways that are easier to understand, for example on el6 the explanation of --tags says:

> Most of the tags are fetched automatically as branch heads are
> downloaded, but tags that do not point at objects reachable from
> the branch heads that are being tracked will not be fetched by this
> mechanism. This flag lets all tags and their associated objects be
> downloaded.

So say for example that there becomes a release v3.0.1 which is tagged on the release-3.0 branch, and somebody is only tracking the master branch, they will not see get the v3.0.1 tag.  That's still going to trip people up.

**Comment by DrDaveD** [comment]
Also I have been in the habit lately of doing "git pull upstream master" to both fetch and merge in one step, and that does not fetch the tags from upstream.  This is not obvious from "git pull --help", but that's been my experience, and it is reproducible.  On master branch do:
```
$ git tag -d v3.0.0
$ git pull upstream master
$ git fetch upstream
```
Only the fetch recreates the missing tag.

**Comment by 0xaf1f** [comment]
I always set the tracking branches appropriately so I can just do `git pull`, which does restore the tag. I hardly ever specify more than that. Though since, according to the manpage, `git pull origin master` is supposed to be equivalent to `git fetch origin && git merge origin/next`, I'd expect to get the tag back doing it that way. :man_shrugging:

**Comment by DrDaveD** [comment]
> according to the manpage, git pull origin next is supposed to be equivalent to git fetch origin && git merge origin/next

No I don't think it says that.  The examples section says that you can achieve the same effect as the first command with the second two, but it doesn't rule out that the second two commands do more than the first.  The man page does say that git pull first runs git fetch with the given parameters, and then calls git merge.  So doing "git pull origin next" is actually equivalent to "git fetch origin next" && "git merge origin/next".   "git fetch --help" says that when a refspec (that is, a branch) is given, then it will pull down tags that point at that branch but it doesn't fetch all tags.
