### ISSUE TITLE
make dist creates non-standard tarball

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2269]
## Version of Singularity:

Current master branch

### Expected behavior

Expect make dist to create a tar.gz file where paths begin "singularity-3.0.0/" or whatever the current version number is.

### Actual behavior

Paths in the tar file begin "singularity/"

This is a problem because people and programs (e.g. rpmbuild) normally expect source tarballs to begin with package-version.  The github archive command creates source tarballs that way from tagged versions, and that is expected to be sufficient for passing directly to the rpmbuild command.

### Steps to reproduce behavior

make dist
tar tf singularity-*.tar.gz|head

**Comment by yhcote** [comment]
We went back and forth with that one. The trade off is that when you untar singularity-3.0.0 in the GOPATH location. Going through the build process will fail. The expected folder is singularity/.

I don't have strong opinions but we should at least document one way or the other, depending on what pathname we choose to create.

**Comment by DrDaveD** [comment]
I think that's a relatively minor consideration.  It's easy enough to put in a script to mv the directory from singularity-* to singularity.

**Comment by DrDaveD** [comment]
I made a branch with this change, which is easy to do, but I am coming now to think that it's maybe not as important as I thought to have the version number in the top level.  We still wouldn't be able to use the github archive url because the VERSION and singularity.spec files are missing.   Instead, having a tarball made by `make -C builddir dist` in the github release area with each release will work better, and for that it doesn't matter what the path is inside.  With either path an `rpmbuild -ta singularity-3.X.Y.tar.gz` will work nice and easy.  And as @yhcote said it is slightly more convenient for compiling from go source to not have the version number.  So I don't know whether or not it is worth it to add the version just to look more standard.

**Comment by zao** [comment]
As an end-user that downloads and extracts tarballs, it's extremely surprising to have a tarbomb that doesn't contain a version-dependent directory name.

It's quite possible that the build procedure for Go programs is different from anything else, but it's still _very_ surprising to a sysape that just wants to extract and see how to build it.

There's no mention of how to install from a release tarball in the instructions, it only talks about online builds where GitHub is available.

**Comment by zao** [comment]
I would at least have a mention on the releases page that the tarball is not intended for normal use - that it needs to be extracted into some `GOPATH` or whatever.

Please think of the normal sysadmins that have been using 2.x series and never ever have touched Go.
I've personally postponed doing anything with 3.0 because of the installation situation.

**Comment by GodloveD** [comment]
Heya @zao are you able to install from an RPM?  I think the RPM installation instructions are actually somewhat easier than it used to be. 

Your point is well taken.  Should probably document the method of building from source using release tarball too.

**Comment by zao** [comment]
Both me and my HPC site are running Ubuntu, so RPM packages are sadly not an option.

At home I build from tarballs and install into /opt/singularity-x.y.z, which was achievable once I read the last line of the installation instructions that mentioned `./mconfig -p` and cleaned up the mess in `/usr/local` from earlier attempts 😁 

At work, we lift the `debian.tar.gz` build files from [Debian unstable](https://packages.debian.org/sid/singularity-container) and build deb files for our local repository. Sometimes they are lagging behind and we have to adapt to changes in Singularity which takes time, particularly if an dependency has been added or the set of files change.

**Comment by dtrudg** [comment]
This looks like a dup of #2215 and that has a possible way forward there as we now use a Go version where we don't need to build from $GOPATH so the name of the extracted dir doesn't need to be `singularity`

**Comment by DrDaveD** [comment]
This is not a dup of #2215, but it's OK to close it anyway as something that's not going to change.  This is about the name of the top level directory inside the tarball, not the name of the tarball itself.

**Comment by dtrudg** [comment]
@DrDaveD  - I think #2215 is about the directory in the tarball too? ...

![Screen Shot 2019-11-07 at 10 00 40 AM](https://user-images.githubusercontent.com/4522799/68405306-7bd2b880-0145-11ea-9e41-e317eebcf167.png)

**Comment by DrDaveD** [comment]
You're right, I'm sorry, I didn't look at it closely enough.  Nevermind.
