### ISSUE TITLE
Make sure INSTALL.md has instructions for both 3.0 and 3.0.X 

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2277]
It is likely that a user will look at the INSTALL.md that just exists in master rather than in the source checked out (say for release-3.0). So we should have install instructions for all the 3.0.X releases since they differ greatly due to various issues (rpm, vendor folder commit, etc)

**Comment by dtrudg** [comment]
We have install instructions relevant for 3.5 - I don't think we need to have for more than one version, as the procedure is stable now for some time.
