### ISSUE TITLE
home mount causes parent directory in-container to be replaced with a tmpfs

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2278]
From @draeath in #727

I've observed that the home mount (the default in /home or user-specified with -H) causes the parent directory in-container to be replaced with a tmpfs. This masks any content that might already exist there.

Is there some reason the home module mounts behave differently than the additional bind mounts requested at runtime with -B?

You can work around this problem by pre-creating a unique parent directory for home to go under, inside the container, but this may require editing/extending an existing (eg, docker) image.

This is especially irritating when working with docker images that assume /home will be left alone, and that have important content there (eg, the biobakery project's docker images use the linuxbrew docker image as a base, so everything of importance is in /home/linuxbrew/.linuxbrew - which is inaccessible unless one puts home somewhere else with -H - of which there are no good directories to do this with in said image.)

**Comment by cclerget** [comment]
@jscook2345 `--no-home` is there to address this issue and left home intact in container image

**Comment by jscook2345** [comment]
I was able to get things to work OK with the following using version the master branch:

singularity shell -B /home:/home test.sif

@draeath feel free to test this and let me know if you have further issues.
