### ISSUE TITLE
master branch: singularity exec failing on rhel6 in setfsuid

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2283]
## Version of Singularity:

Current master branch

### Expected behavior

singularity exec works

### Actual behavior

Doing a singularity exec on rhel6 prints a non-fatal error "ERROR  : Previous filesystem UID is not equal to 0" and then fatal error "FATAL:    container creation failed: mount error: can't mount tmpfs filesystem to /var/singularity/mnt/session: read unix @->@: read: connection reset by peer".  With a debugging print statement I found that the invocation of setfsuid(uid) returns -1 instead of 0.  I am sure singularity exec used to work on rhel6 on a previous 3.x master branch but I'm not sure how long ago I tried it.

### Steps to reproduce behavior

Run `singularity exec centos-6.simg bash` or any image on a rhel6 or centos6 virtual machine, not docker container.

**Comment by DrDaveD** [comment]
It was commit 0df98b2b180ff62bd2d94ecd972403495a8e0a39 9 days ago that did it.

**Comment by cclerget** [comment]
@DrDaveD I need to look closer at what happens there
