### ISSUE TITLE
Using cgo is painful, can we avoid it

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2285]
## Version of Singularity:

master branch

### Expected behavior

Changing src/runtime/starter/c/starter.c affects the build

### Actual behavior

Changing starter.c has no effect on a development build output unless smaster.go is also edited or `go clean -cache` is run.  This is a [documented go bug](https://golang.org/cmd/go/#hdr-Build_and_test_caching) which I guess makes it a feature. 

### Steps to reproduce behavior

Build singularity, change starter.c, and build singularity again.

Can we avoid using the cgo feature?   I was frustrated for a couple of hours last night trying to figure out why changing starter.c had no effect.

**Comment by cclerget** [comment]
@DrDaveD During development I recommend to set environment variable `GOCACHE=off`. I will submit a patch to force compilation of `starter` when `starter.c` is modified

**Comment by DrDaveD** [comment]
Closed via #2288.
