### ISSUE TITLE
ubuntu build fails on centos host

### ISSUE THREAD

**Issue by widyono-cets** [apptainer/singularity#2287]
## Version of Singularity:
3.0.0-218.g093d5f6

### Expected behavior
build succeeds

### Actual behavior
build fails with
ERROR  : Failed to set ambient capability: Invalid argument
FATAL:   While performing build: while running engine: exit status 1

### Steps to reproduce behavior (executed on 20181023)
centos 7.2 virtualbox built via vagrant from bento/centos7.2 and configured thusly after logging in:

sudo yum -y groupinstall 'Development Tools'
sudo yum -y install openssl-devel git libuuid-devel golang squashfs-tools
echo 'export GOPATH=${HOME}/go' >> ~/.bashrc
echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc
source ~/.bashrc
mkdir -p $GOPATH/src/github.com/sylabs
cd $GOPATH/src/github.com/sylabs
git clone https://github.com/sylabs/singularity.git
cd singularity
go get -u -v github.com/golang/dep/cmd/dep
./mconfig
make -C builddir
sudo make -C builddir install

# created testing.def:
[vagrant@localhost ~]$ cat testing.def
BootStrap: library
From: ubuntu:16.04

%post
    apt-get -y update
    apt-get -y install fortune cowsay lolcat

%environment
    export LC_ALL=C
    export PATH=/usr/games:$PATH

%runscript
    fortune | cowsay | lolcat

%labels
    Author GodloveD

# attempted build
[vagrant@localhost ~]$ sudo /usr/local/bin/singularity build testing.sif testing.def
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
 35.32 MiB / 35.32 MiB [================================================================================] 100.00% 10.65 MiB/s 3s
ERROR  : Failed to set ambient capability: Invalid argument
FATAL:   While performing build: while running engine: exit status 1

**Comment by cclerget** [comment]
@widyono-cets Can you give output of `./mconfig` please ?

**Comment by widyono-cets** [comment]
[vagrant@localhost singularity]$ ./mconfig
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host `ar' path... ar
 checking: host `ld' path... ld
 checking: host `ranlib' path... ranlib
 checking: host `objcopy' path... objcopy
 checking: target C compiler... cc
 checking: target C++ compiler... c++
 checking: target `ar' path... ar
 checking: target `ld' path... ld
 checking: target `ranlib' path... ranlib
 checking: target `objcopy' path... objcopy
 checking: host compiles static binaries... no
 checking: target compiles static binaries... no
 checking: host os type... unix
 checking: host architecture... x86_64
 checking: target architecture... x86_64
 checking: host architecture word size... 64
 checking: target architecture word size... 64
=> running project specific checks ...
 checking: namespace: CLONE_NEWPID... yes
 checking: namespace: CLONE_FS... yes
 checking: namespace: CLONE_NEWNS... yes
 checking: namespace: CLONE_NEWUSER... yes
 checking: namespace: CLONE_NEWIPC... yes
 checking: namespace: CLONE_NEWNET... yes
 checking: namespace: CLONE_NEWUTS... yes
 checking: namespace: CLONE_NEWCGROUP... no
 checking: feature: NO_NEW_PRIVS... yes
 checking: feature: MS_SLAVE... yes
 checking: feature: MS_REC... yes
 checking: feature: MS_PRIVATE... yes
 checking: user capabilities... yes
 checking: header linux/securebits.h... yes
 checking: header linux/capability.h... yes
 checking: function setns... no
 checking: libssl+headers... yes
 checking: libuuid+headers... yes
 checking: libseccomp+headers... no
INFO: userns and disable_suid are disabled. (mlocal/checks/basechecks.chk)
=> generating fragments ...
 found build modules:
   +-> src/runtime/c/lib/util/util.mconf
=> building Makefile ...
=> generating dist/rpm/singularity.spec ...
=> project setup with :
    - target arch: x86_64
    - target compiler: cc
    - target wordsize: 64-bit
    - host arch: x86_64
    - host wordsize: 64-bit
    - host system: unix
    - config profile: release
    - verbose: no
=> builddir/Makefile ready, try:
   $ cd builddir
   $ make

**Comment by cclerget** [comment]
Thanks @widyono-cets ! Ok `sys/prctl.h` header lies and claims the kernel support ambient capabilities while this is not the case. Will fix that in the build process.

**Comment by widyono-cets** [comment]
Confirmed, commented out PR_CAP_AMBIENT #defines in
/usr/include/linux/prctl.h and rebuilt singularity, works fine now. Thanks!

Dan W.
