### ISSUE TITLE
When should plugins be loaded?

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2289]
When should we `Open()` plugins? There are some complexities here:

1. How do we handle the `starter` binary? The `go runtime` does not actually begin until after the C constructor function returns, meaning we have to load each plugin `n` times, where `n` is the number of total procs
2. Do we provide the ability to only load specific installed plugins via `--plugin` flag?
3. Do we only load plugins when a section of code might reference the plugins?
4. Do we load all plugins at the start of the binary, and maintain a list of loaded plugins?

**Comment by GodloveD** [comment]
What about plugins being added to Singularity during compilation?  I'm sure that is a bad idea, but why?

**Comment by bauerm97** [comment]
Dave, a plug-in which is loaded during compilation is not a plug-in, it's source code

**Comment by GodloveD** [comment]
Lol.  OK then.

**Comment by bauerm97** [comment]
We can explore implementing some form of Activation Events, where a plugin is only fully loaded into memory when some specific event is triggered.

Example: A plugin could say it only needs to be loaded when an action command is run (`run`, `exec`, `shell`). This information could be packed into the plugin SIF distribution format
