### ISSUE TITLE
How do we facilitate the proper environment for developing/compiling plugins?

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2296]
We need to make it as easy as possible for a third party to develop plugins. This means we need to have a well-defined plugin development environment. We need to ensure that plugins are always built in the proper format, with any necessary flags (if any), etc... How should developers set up their development environment, etc... This is both a documentation need and design constraint.

**Comment by bauerm97** [comment]
Singularity could provide a `singularity plugin compile` command, which functions to run the appropriate build and packaging commands when run within the plugin source code. We can define a standardized plugin source code layout and this will make it trivial for developers to compile their plugins. This goes hand in hand with @yhcote work on `makeit`, and he will be helping with this work along the way

**Comment by jscook2345** [comment]
`homebrew` has something in formulas that describe how things are installed. Perhaps that could be a starting point to model plug-in development after? They have things like project template creation, linting, etc.

**Comment by al3x609** [comment]
What do you think about an API instead plugin?
