### ISSUE TITLE
Determine what features of singularity make sense to move into plugins

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2298]
We would like to move some portions of Singularity which are partially orthogonal to the main Singularity codebase into plugins. This will allow sites to enable/disable these features if they desire. We need to assemble a complete list of these features which we can pull out, and develop them into plugins. Currently there are two features on this list:

1. `--nv` option
2. `apps` support

The features we turn into plugins will also serve as example plugin code for plugin developers to reference.

**Comment by GodloveD** [comment]
See also #2303 for a partial list of ideas.

**Comment by bauerm97** [comment]
- `--ib`/`--ofed` flag as a plugin
- `--nv` flag as a plugin
