### ISSUE TITLE
Define Plugin Hooks

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2303]
Probably one of the largest chunks of work will be to define the plugin hooks. Suggestions welcomed for what functionality is useful, and for things which would make interesting plugin case studies.

**Comment by GodloveD** [comment]
One way to approach this is to just think, what can singularity do?  It can: 

- setup namespaces
- mount file systems
- bind files into the container (both by using the `--bind` code and also writing directly to the session directory the way that the `--nv` option does with libraries).  
- set environment variables
- perform networking via cni
- limit resources via cgroups
- execute commands such as `cat` within container (to use `inspect` command for instance)
- interact with the library, shub, and docker hub via APIs
- set values in and read values from the configuration
- read an image and determine its format
- can parse def files
- can edit passwd and group files at runtime (and other files if necessary such as /etc/resolv.conf)
- can chroot into file systems

and a bunch of other stuff too.

But if we create hooks for every single thing Singularity can do it will be a very long process and we will likely create a lot of hooks that will never be used. 

Another approach is to just look at the use cases we already have and try to brainstorm things that already exist in Singularity that could be broken out into plugins.

We know we want to make the following plugins:
- `app` option 
- `--nv` option

There may be other good candidates for breaking out existing functionality into Singularity plugins.

- `inspect` command?
- `run-help` command?
- `keys` command group?
- `push` and `pull`?
- `search`?
- `sign` and `verify`?
- `--cleanenv`?
- `--no-home`?
- `--pwd`?
- `--scratch`?
- `--workdir`?

Some of these are probably bad ideas.  But some might be good ideas for being implemented as plugins.  And the more that can be implemented as plugins, the more hooks will be developed.

It might be good to start by selecting a set from among these commands and options, and working to implement them as plugins.  If a good set is selected, a broad range of hooks may be developed to support them.  This would give us a good starting point for an initial stab at a plugin framework for 3.1.  More hooks could then be added as needed to accommodate 3rd parties as they approach us with ideas, or as we come up with ideas ourselves.
