### ISSUE TITLE
singularity plugin command for administration of plugins

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2317]
In order to provide an easy way for system administrators to manage the plugins installed on their system, a `singularity plugin` command will be implemented. This command will contain several subcommands related to plugin management:

- `enable`/`disable`
- `install`/`uninistall`
- `configure`
- `list`
- `info`

etc...

**Comment by ArangoGutierrez** [comment]
Plugging sub command should be hidden, not shown on `singularity --help` .

**Comment by bauerm97** [comment]
Not really sure I agree with that. Why would we not want the `singularity plugin` command to appear in `snigularity --help`? @ArangoGutierrez

**Comment by ArangoGutierrez** [comment]
This will be a system admin only command (Root access).
info/help about this sub command should go into Admin-Docs.

**Comment by bauerm97** [comment]
So two things on that:


1. There is precedence in root only commands/flags still being visible in `singularity --help`. For example, `singularity capability` command is a similar administrative tool and still appears in `singularity --help`
2. There may be reason for non-root users to use `singularity plugin`. I imagine it may be useful for users to be able to run `singularity plugin list` to see all the plguins installed on the system.

**Comment by ArangoGutierrez** [comment]
Well if there's a precedence, then I agree with you, ignore my comment.
CLI need to be persistent across CMD's
