### ISSUE TITLE
bootstrap should remove argument comments

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#232]
eg, if my spec file has:

Build: python:latest # 3.5

it doesn't get removed as a comment, and messes up:

```
  IncludeCmd: yes
  usage: cli.py [-h] [--docker DOCKER] [--rootfs ROOTFS] [--cmd]
 cli.py: error: unrecognized arguments: # 3.5
 usage: cli.py [-h] [--docker DOCKER] [--rootfs ROOTFS] [--cmd]
  ....
  Executing Postbootstrap module
  ERROR: Container does not contain the valid minimum requirement of /bin/sh
```

so args should possibly be split for the comment character, and then have the comment removed. If comments aren't supported, they probably should be so the user can add some documentation to the definition files!

**Comment by gmkurtzer** [comment]
Fixed in [master 648b60a]. Good catch!
