### ISSUE TITLE
Singularity Vagrant Boxes

### ISSUE THREAD

**Issue by kzap** [apptainer/singularity#2329]
Instead of having only a CentOS base box which installs singularity it would be good to have prebuilt Singularity boxes with different base OS's in them so one can build images or use those in whatever architecture they have.

Like https://github.com/dctrud/vagrant-devboxes/

but built using Packer and uploaded to Vagrant Cloud

We could utilize CircleCI for building these boxes and uploading them to Vagrant Cloud

**Comment by GodloveD** [comment]
I'm on it!

**Comment by ArangoGutierrez** [comment]
@GodloveD effort to close this issue 
 - https://github.com/sylabs/packer-ubuntu-singularity
