### ISSUE TITLE
Investigate need for rpm macros in zypper bootstrapping

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#2343]
Check if various distributions have zypper use a non-standard `_dbpath`. If this is the case, then the use of macros is unnecessary for zypper bootstraps and can be removed.

**Comment by dtrudg** [comment]
Egbert Eich from SUSE looks to have addressed this in

commit 9d16f8303d689c24890dac05d5b0b685b10959d7
Author: Egbert Eich <eich@suse.com>
Date:   Mon May 13 14:29:25 2019 +0200

    zypper install: Fix dbpath for newer versions of SUSE Linux
    
    Signed-off-by: Egbert Eich <eich@suse.com>

We have 2 paths possible and we need to consider the `_dbpath` still.
