### ISSUE TITLE
behavior difference between 2.6.0 and 3.0.1-42.g46f91b2

### ISSUE THREAD

**Issue by lfaino** [apptainer/singularity#2345]
## Version of Singularity:
2.6.0
3.0.1-42.g46f91b2

### Expected behavior
in 2.6.0 version the content of this folder is:

lfaino@LabReverberi_PT /usr/local/RepeatMasker/Libraries $ ll
total 1587444
drwxrwxrwx 2 lfaino lfaino       4096 Nov  6 11:38 ./
drwxrwxrwx 5 lfaino lfaino       4096 Nov  6 11:39 ../
-rwxrwxrwx 1 lfaino lfaino 1510837557 Sep 24  2015 Dfam.hmm*
-rwxrwxrwx 1 lfaino lfaino     212876 Jan 29  2017 DfamConsensus.embl*
-rwxrwxrwx 1 lfaino lfaino        214 Jan 29  2017 README.meta*
-rwxrwxrwx 1 lfaino lfaino   17204287 Jan 29  2017 RMRBMeta.embl*
-rwxrwxrwx 1 lfaino lfaino   22475384 Aug  7  2015 RepeatAnnotationData.pm*
-rwxrwxrwx 1 lfaino lfaino   10325957 Jan 31  2014 RepeatPeps.lib*
-rwxrwxrwx 1 lfaino lfaino       4401 May 28  2009 RepeatPeps.readme*
-rwxrwxrwx 1 lfaino lfaino   64450715 Aug 29  2016 taxonomy.dat*

which is the expected behavior

### Actual behavior

in 3.0.1 the folder content looks like:

lfaino@LabReverberi_PT /usr/local/RepeatMasker/Libraries $ ll
total 1587416
drwxr-xr-x 2 root root        207 Feb  1  2017 ./
drwxr-xr-x 5 root root       1097 Oct 24 07:48 ../
-rwxrwxr-x 1 root root 1510837557 Nov  6 10:28 Dfam.hmm*
-rwxrwxr-x 1 root root     212876 Nov  6 10:28 DfamConsensus.embl*
-rwxrwxr-x 1 root root        214 Nov  6 10:28 README.meta*
-rwxrwxr-x 1 root root   17204287 Nov  6 10:28 RMRBMeta.embl*
-rwxrwxr-x 1 root root   22475384 Nov  6 10:28 RepeatAnnotationData.pm*
-rwxrwxr-x 1 root root   10325957 Nov  6 10:28 RepeatPeps.lib*
-rwxrwxr-x 1 root root       4401 Nov  6 10:28 RepeatPeps.readme*
-rwxrwxr-x 1 root root   64450715 Nov  6 10:28 taxonomy.dat*

### Steps to reproduce behavior

Can you restore the 2.6.0 version behavior in the 3.0.1 version? why do i have these differences?

Cheers
Luigi

**Comment by bauerm97** [comment]
Hey @lfaino, thanks for reporting this to us. I *believe* the difference here is caused due to a new feature in Singularity v3.0.0 called "underlay", which allows us to emulate the behavior of `overlayfs` without using `overlayfs`. Can you do two things which will help me solve this:

1. Run the same command again with debug flag: `singularity -d shell ...` and paste the entirety of the output here.
2. Paste the contents of the singularity config file here, which should be located at `$(PREFIX)/etc/singularity/singularity.conf`. If you built singularity using the default values of `./mconfig`, `$(PREFIX)` will be `/usr/local`

Once you send those two things over I'll be able to give a better answer. Cheers!

**Comment by lfaino** [comment]
for which of the 2 version do you need these infos?

3.0.1 or 2.6.0

**Comment by bauerm97** [comment]
@lfaino just for v3.0.1 should be fine

**Comment by lfaino** [comment]
Here the conf file:
[singularity.conf.txt](https://github.com/sylabs/singularity/files/2554533/singularity.conf.txt)

here the log of the shell command
[singularity.log.txt](https://github.com/sylabs/singularity/files/2554607/singularity.log.txt)


cheers
Luigi

**Comment by bauerm97** [comment]
Hey @lfaino , thanks for getting back with that. So, I'm not seeing anything in this log that would cause this behavior. Can you run the exact command you were running before to replicate this behavior (with `--debug` flag added for debug output), and then send me that log. Or is this log already from the exact command? And if it is the same command, is it possible that the configuration file has changed from when you previously were running this command?

**Comment by lfaino** [comment]
DEBUG   [U=1001,P=28648]   parseURI()                    Parsing docker://lfaino/lorean into reference
DEBUG   [U=1001,P=28648]   initCacheDir()                Creating cache directory: /home/lfaino/.singularity/cache
DEBUG   [U=1001,P=28648]   initCacheDir()                Creating cache directory: /home/lfaino/.singularity/cache/oci-tmp/a09d1f30bd148d04cdbd13bb3bdec842a4c9e2c2765b9dd48f329e1cddd35764
DEBUG   [U=1001,P=28648]   updateCacheSubdir()           Caching directory set to /home/lfaino/.singularity/cache/oci-tmp/a09d1f30bd148d04cdbd13bb3bdec842a4c9e2c2765b9dd48f329e1cddd35764
DEBUG   [U=1001,P=28648]   updateCacheSubdir()           Caching directory set to /home/lfaino/.singularity/cache/oci-tmp
DEBUG   [U=1001,P=28648]   updateCacheSubdir()           Caching directory set to /home/lfaino/.singularity/cache/oci-tmp/a09d1f30bd148d04cdbd13bb3bdec842a4c9e2c2765b9dd48f329e1cddd35764
DEBUG   [U=1001,P=28648]   updateCacheSubdir()           Caching directory set to /home/lfaino/.singularity/cache/oci-tmp
INFO    [U=1001,P=28648]   handleOCI()                   Converting OCI blobs to SIF format
DEBUG   [U=1001,P=28648]   NewBundle()                   Created temporary directory for bundle /tmp/sbuild-222260542
INFO    [U=1001,P=28648]   Full()                        Starting build...
DEBUG   [U=1001,P=28648]   Get()                         Reference: lfaino/lorean
DEBUG   [U=1001,P=28648]   initCacheDir()                Creating cache directory: /home/lfaino/.singularity/cache/oci
DEBUG   [U=1001,P=28648]   updateCacheSubdir()           Caching directory set to /home/lfaino/.singularity/cache/oci
Getting image source signatures
Copying blob sha256:18d680d616571900d78ee1c8fff0310f2a2afe39c6ed0ba2651ff667af406c3e
 41.34 MiB / 41.34 MiB [====================================================] 6s
Copying blob sha256:0addb6fece630456e0ab187b0aa4304d0851ba60576e7f6f9042a97ee908a796
 851 B / 851 B [============================================================] 0s
Copying blob sha256:78e58219b215b359fe002f0ca1f416617b75ca9b36cb274c98d7a5f808711179
 620 B / 620 B [============================================================] 0s
Copying blob sha256:eb6959a66df2ea26a26452ba11f84fb64bb45af90204374862ec71ee59f795e7
 169 B / 169 B [============================================================] 0s
Copying blob sha256:62c13576309c6076c843f3c71d707e268e1050aba308f76f73f663432f86358a
 635.80 MiB / 635.80 MiB [===============================================] 1m30s
Copying blob sha256:b08dbbc2edf7ba8d1eccea5f193260f6771044e7ec95e8cffc7c20a01550b6e3
 372.59 KiB / 372.59 KiB [==================================================] 0s
Copying blob sha256:1b66efa01467187cf615ff957bea1e29b756051eecbfdb361e1b59effc4c4cf9
 372.73 KiB / 372.73 KiB [==================================================] 0s
Copying blob sha256:3624c45e67a9efa827509e0618d46d72d6eeb337494379653a381e3230c06ec1
 54.22 MiB / 54.22 MiB [====================================================] 7s
Copying blob sha256:10471c317374fd05adbb8215bc0471b13237056940353538b5291d41f7a15e9e
 180.99 MiB / 180.99 MiB [=================================================] 25s
Copying blob sha256:49afa2f11b9aa4205e94bdc66758e1f20eb5e94f9d90afa7bf42a09faed0d086
 328.89 MiB / 328.89 MiB [=================================================] 45s
Copying blob sha256:137ef7542193faee811c435421a06a681835c526123c1429b20257e03bbdf76b
 1.67 MiB / 1.67 MiB [======================================================] 0s
Copying blob sha256:0c6a00e223970ac3a6ffade09d23de4bafe9ee912f658e679cc20e3b1fede124
 898.71 KiB / 898.71 KiB [==================================================] 0s
Copying blob sha256:1b0c02c695e25cd9b1e64c952d0981d324d81294dd4f0c7f302b8498f4d53c81
 14.92 MiB / 14.92 MiB [====================================================] 2s
Copying blob sha256:61ed38b251537b520362f8dd6bd389e49a788e5baeb93b2fbc88d67958da8fa6
 11.73 MiB / 11.73 MiB [====================================================] 1s
Copying blob sha256:f063a94c6ea40ec0e7c393bd5358bbd36f2582006fd08a16b574886fb6f1f786
 23.73 MiB / 23.73 MiB [====================================================] 3s
Copying blob sha256:5b1eb6a7e93bdd7fe56837ced7b9dc4351f1415d11aec8a00c49f4426a3ab3fd
 24.04 MiB / 24.04 MiB [====================================================] 3s
Copying blob sha256:79bc1f08b186e08d8fc374d6299289185455014bf0fb7d4e3c5e639f31134339
 3.60 MiB / 3.60 MiB [======================================================] 0s
Copying blob sha256:6242df567c66da7940aec50267d162eb3f8f22019eab710edf9e245893ae4146
 85.00 MiB / 85.00 MiB [===================================================] 12s
Copying blob sha256:4667915021f7ed627690b2efcbf6382e9571185494a5537772af7b5d258eae43
 4.58 MiB / 4.58 MiB [======================================================] 0s
Copying blob sha256:677d5a32ad60da218c3fde9310e39f2672f6ed8ba57ba573a78035b0ed4c66b9
 548.13 MiB / 548.13 MiB [===============================================] 1m16s
Copying blob sha256:f70089ba6bb7abf582f5769686cf4251e2f1144f6da64b2a88e71f49fa89622b
 25.63 MiB / 25.63 MiB [====================================================] 3s
Copying blob sha256:d7238814f37283ff888daa9ef66aff045c502a62204f00322aee744ad277c245
 82.86 MiB / 82.86 MiB [===================================================] 12s
Copying blob sha256:c110eec0f47b31ad61def46923fa5ee688c45cd794bf26b94e3ea830b8d44843
 2.74 MiB / 2.74 MiB [======================================================] 0s
Copying blob sha256:30b7216cf23fb3cf447010da636e33c3b2aca2733f62e274437171040816227b
 320.75 MiB / 320.75 MiB [=================================================] 45s
Copying blob sha256:28cafcf4988944908121fe0c810c6569511f7bac8e6f232255f3c6cf0800d6df
 11.19 MiB / 11.19 MiB [====================================================] 1s
Copying blob sha256:cec6cbffff2622c00e70feabb86693cb951e5f7faa69c600c134d6f8571d7691
 12.67 MiB / 12.67 MiB [====================================================] 1s
Copying blob sha256:0ecc90409e9c3272d52f377537a1e876de39df71b38ff33fccbf28d6e2033a4d
 4.09 MiB / 4.09 MiB [======================================================] 0s
Copying blob sha256:05df87e781637605e6c52ffbcbdc8a5610b0109dd02880c0bf8b3dc79e392e44
 124.73 MiB / 124.73 MiB [=================================================] 19s
Copying blob sha256:2454c8dd56eeb409a8d4140c3738df2ac8fb41d5e204c157c403a497a291d361
 1.21 MiB / 1.21 MiB [======================================================] 0s
Copying blob sha256:ad478dc776753735e84d1c64a943d6e4d3dd3749001d992fb02a8e8df2baba59
 2.73 MiB / 2.73 MiB [======================================================] 0s
Copying blob sha256:b8bad6e17064a2003696779b31ad1d0969c5565f3071451f89955cb228ac6dfa
 96.95 MiB / 96.95 MiB [===================================================] 14s
Copying blob sha256:b9d3250fe4585ed012ea6278d8d92c64cf350b96497862308b796f1ac8c44a75
 3.87 MiB / 3.87 MiB [======================================================] 0s
Copying blob sha256:500ab7f209721dfe4f24ca54f4b114a96f632f54cfcf141f0fb31b9e2885c0ad
 3.70 MiB / 3.70 MiB [======================================================] 0s
Copying blob sha256:95238b2398ca362391f81a2f68e793c1fad344b89c299b7620572647166a78d9
 15.27 MiB / 15.27 MiB [====================================================] 2s
Copying blob sha256:3f270ccb60138799047e367f087892abc508730b2089eeb203f85cd92f24ad0d
 2.16 MiB / 2.16 MiB [======================================================] 0s
Copying blob sha256:4b7b37530150516a62d8c2f4537c4bae970b819791698828e91863c816a85710
 12.68 MiB / 12.68 MiB [====================================================] 1s
Copying blob sha256:d8b2bf3d85b2ecf721450324f726052a6153a0f941c95ed7d8fb13557eca9498
 69.09 MiB / 69.09 MiB [===================================================] 10s
Copying blob sha256:3694cf9965c2894b76bfd4dec37819f9e8184175d34a90d5fff1deed34a45693
 1.12 KiB / 1.12 KiB [======================================================] 0s
Copying blob sha256:d122e659252c155fb80baafce860577e03617967f2b4b65613bfa236a6754576
 313 B / 313 B [============================================================] 0s
Copying blob sha256:1e4713345332e1cd373c8ec3bf4a010452430516b0b00ef4222b1d764988e9fe
 129.64 KiB / 129.64 KiB [==================================================] 0s
Copying blob sha256:0d950847f9a7c14a83cf2442bd66caa7bdc16bbfeaa6dea258d6ee6af5b11691
 5.63 GiB / 5.63 GiB [===================================================] 13m3s
Copying blob sha256:3c153b24aa160b4998dc359efc5fb946e00e68c92db95ec333b16111d398c9b7
 5.66 GiB / 5.66 GiB [===================================================] 13m7s
Copying blob sha256:da7ce5fd91c3025247915ea7b72f59b7536fd7907610da72a8be8d0612f855d9
 272 B / 272 B [============================================================] 0s
Copying blob sha256:f55953dfb21932aea2424cf0512322ff90530577323bcafe99cb89fa3c74e173
 222.80 MiB / 222.80 MiB [=================================================] 32s
Copying blob sha256:7dda1a0a160a5878d36d4eb94ebb1d0769d668e23f8eefddcece2e45f0363be7
 460.35 MiB / 460.35 MiB [================================================] 1m4s
Copying blob sha256:c0263bee136e06111f3eadd3d578de4668c7821f8b4791b5999f7aef127c89ca
 7.29 MiB / 7.29 MiB [======================================================] 1s
Copying blob sha256:746d425b608e0e19d2267ac4758b5640fc8ea1013de35441fff311b785dd2e77
 6.95 MiB / 6.95 MiB [======================================================] 1s
Copying blob sha256:95bfdb1e790d7f2bfc287a16e4237d37a05be42719ba1c8d359ccf5615eb9131
 9.42 KiB / 9.42 KiB [======================================================] 0s
Copying blob sha256:4c0b8f03112ba839b21eb547b6008fc25c008b7f9893945a6bd2cea9171307c2
 135 B / 135 B [============================================================] 0s
Copying blob sha256:5d2a8569b51cd384b2c4259e53251a095ac7bf32831b501e12282e9cad677d50
 1.11 MiB / 1.11 MiB [======================================================] 0s
Copying blob sha256:98ab89e8676fcb09dbcf84f5cf4356462c5df61c91237046b0adf960877d3d6b
 1.51 MiB / 1.51 MiB [======================================================] 0s
Copying blob sha256:4ef15f1ad04c8d8259f1524f15d0a12df2c3981c4a128b7228bd3546cc3c786e
 4.24 KiB / 4.24 KiB [======================================================] 0s
Copying blob sha256:d5e5dd1832ade91bd320fba37fea637443d42e6d7193076869827f2c39a4522c
 4.97 KiB / 4.97 KiB [======================================================] 0s
Copying blob sha256:97d33ac065506bbc3724935b54ef63c45cedc428a0d43aa3897cb2f19117148f
 46.52 KiB / 46.52 KiB [====================================================] 0s
Copying blob sha256:5df75b68403c17f56b92d5e3755c561e87674d26a88aa19a0331e31efb26daef
 197.31 KiB / 197.31 KiB [==================================================] 0s
Copying blob sha256:a76e53026e198b7516488bccd0d3c1e9ea0250c5920d8e995d2c19724cfba448
 2.64 MiB / 2.64 MiB [======================================================] 0s
Copying blob sha256:f4822a7d7585204e029897cdb24475825fdd483f4f1c5f68fe5ef6b3c5c72a53
 2.63 MiB / 2.63 MiB [======================================================] 0s
Copying blob sha256:0c70988aa845b983872b83e40f39e390f6ee06b87baabb1b8e4dfff1de79fd25
 8.35 MiB / 8.35 MiB [======================================================] 1s
Copying blob sha256:3c5ff755fe4a44619d36aa8b5bd817ad76dfb1882c1cddaa7f9373cdccbd59da
 218.58 MiB / 218.58 MiB [=================================================] 32s
Copying blob sha256:5d16f9487b058dcd290c933670e10c8869abf0c1da2a5d9f891cfb400f0c645b
 145.51 KiB / 145.51 KiB [==================================================] 0s
Copying blob sha256:cb244c181dbe6eef44800c83e19f512c3f05ec916930bb5f3ba5667083cea954
 250.35 MiB / 250.35 MiB [=================================================] 35s
Copying blob sha256:217c3378fda7247b61c0a8723401a8d3d3f540cbba18d6cb4e95d9bb63bc1fce
 245.61 MiB / 245.61 MiB [=================================================] 36s
Copying blob sha256:3d53179f88fb56eef0780eb984843a88f79effdb7a00a8c083b97159e2a36a98
 151.05 KiB / 151.05 KiB [==================================================] 0s
Copying blob sha256:1c95ed0f0135960db68a5245f6f0617fc1a6d8d3864ecf3ddba671f57ac647cf
 245.60 MiB / 245.60 MiB [=================================================] 36s
Copying blob sha256:05c9aa69793e0f0e4c221a83bfb8e663dbfe2e7d7264665bb96460f87faafd95
 6.40 MiB / 6.40 MiB [======================================================] 0s
Copying blob sha256:322ee9c9f9f1352c6d8065dad8aa1056b6437ac06218fd9e5119247d8f9e6d2c
 92 B / 92 B [==============================================================] 0s
Copying blob sha256:bb511c74cb227760ea5b6cdc3cadddfdf346a850edd0b751900d521dc3ce8e04
 127 B / 127 B [============================================================] 0s
Copying config sha256:26548ba2f6f2edcf0dee914b19b0da93351ed6c03436662a2b47639eeda5d3dd
 21.20 KiB / 21.20 KiB [====================================================] 0s
Writing manifest to image destination
Storing signatures
DEBUG   [U=1001,P=28648]   Full()                        Inserting Metadata
DEBUG   [U=1001,P=28648]   Full()                        Calling assembler
INFO    [U=1001,P=28648]   Assemble()                    Creating SIF file...
INFO    [U=1001,P=28648]   Full()                        Build complete: /home/lfaino/.singularity/cache/oci-tmp/a09d1f30bd148d04cdbd13bb3bdec842a4c9e2c2765b9dd48f329e1cddd35764/lorean_latest.sif
INFO    [U=1001,P=28648]   handleOCI()                   Image cached as SIF at /home/lfaino/.singularity/cache/oci-tmp/a09d1f30bd148d04cdbd13bb3bdec842a4c9e2c2765b9dd48f329e1cddd35764/lorean_latest.sif
VERBOSE [U=0,P=28648]      print()                       Set messagelevel to: 5
DEBUG   [U=0,P=28648]      init()                        PIPE_EXEC_FD value: 7
VERBOSE [U=0,P=28648]      init()                        Container runtime
VERBOSE [U=0,P=28648]      is_suid()                     Check if we are running as setuid
DEBUG   [U=0,P=28648]      init()                        Overlay seems supported by kernel
DEBUG   [U=0,P=28648]      init()                        Drop privileges
DEBUG   [U=1001,P=28648]   init()                        Read json configuration from pipe
DEBUG   [U=1001,P=28648]   init()                        Set child signal mask
DEBUG   [U=1001,P=28648]   init()                        Create socketpair for smaster communication channel
DEBUG   [U=1001,P=28648]   init()                        Wait C and JSON runtime configuration from scontainer stage 1
DEBUG   [U=1001,P=32544]   set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1001,P=32544]   init()                        Spawn scontainer stage 1
VERBOSE [U=1001,P=32544]   priv_escalate()               Get root privileges
DEBUG   [U=0,P=32544]      set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=32544]      prepare_scontainer_stage()    Entering in scontainer stage 1
DEBUG   [U=1001,P=32544]   set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1001,P=32544]   startup()                     Execute scontainer stage 1
DEBUG   [U=1001,P=32544]   Stage()                       Entering scontainer stage 1
DEBUG   [U=1001,P=32544]   prepareFd()                   Open file descriptor for /home/lfaino/mysql/run/mysqld
DEBUG   [U=1001,P=32544]   Init()                        Entering image format intializer
DEBUG   [U=1001,P=32544]   Init()                        Check for image format sif
DEBUG   [U=1001,P=28648]   init()                        Receiving configuration from scontainer stage 1
DEBUG   [U=1001,P=28648]   init()                        Wait completion of scontainer stage1
VERBOSE [U=1001,P=28648]   priv_escalate()               Get root privileges
VERBOSE [U=0,P=28648]      create_namespace()            Create mount namespace
DEBUG   [U=0,P=28648]      init()                        Create RPC socketpair for communication between scontainer and RPC server
VERBOSE [U=0,P=28648]      init()                        Spawn smaster process
DEBUG   [U=0,P=32552]      set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=32552]      init()                        Spawn scontainer stage 2
VERBOSE [U=0,P=32552]      create_namespace()            Create mount namespace
VERBOSE [U=0,P=32553]      init()                        Spawn RPC server
VERBOSE [U=1001,P=28648]   startup()                     Execute smaster process
VERBOSE [U=0,P=32553]      startup()                     Serve RPC requests
DEBUG   [U=1001,P=28648]   setupSessionLayout()          Attempting to use overlayfs (enable overlay = try)
DEBUG   [U=1001,P=28648]   setupOverlayLayout()          Creating overlay SESSIONDIR layout
DEBUG   [U=1001,P=28648]   addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=1001,P=28648]   addRootfsMount()              Mounting block [squashfs] image: /home/lfaino/.singularity/cache/oci-tmp/a09d1f30bd148d04cdbd13bb3bdec842a4c9e2c2765b9dd48f329e1cddd35764/lorean_latest.sif
DEBUG   [U=1001,P=28648]   addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=1001,P=28648]   addKernelMount()              Adding proc to mount list
DEBUG   [U=1001,P=28648]   addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=1001,P=28648]   addKernelMount()              Adding sysfs to mount list
DEBUG   [U=1001,P=28648]   addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=1001,P=28648]   addDevMount()                 Adding dev to mount list
DEBUG   [U=1001,P=28648]   addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=1001,P=28648]   addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=1001,P=28648]   addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=1001,P=28648]   addHomeStagingDir()           Staging home directory (/home/lfaino) at /usr/local/var/singularity/mnt/session/home/lfaino
DEBUG   [U=1001,P=28648]   addHomeMount()                Adding home directory mount [/usr/local/var/singularity/mnt/session/home/lfaino:/home/lfaino] to list using layer: overlay
DEBUG   [U=1001,P=28648]   isLayerEnabled()              Using Layer system: overlay
DEBUG   [U=1001,P=28648]   addUserbindsMount()           Adding /home/lfaino/mysql/run/mysqld to mount list
DEBUG   [U=1001,P=28648]   addUserbindsMount()           Checking for 'user bind control' in configuration file
DEBUG   [U=1001,P=28648]   addTmpMount()                 Checking for 'mount tmp' in configuration file
DEBUG   [U=1001,P=28648]   addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=1001,P=28648]   addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=1001,P=28648]   addResolvConfMount()          Adding /etc/resolv.conf to mount list
DEBUG   [U=1001,P=28648]   addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=1001,P=28648]   create()                      Mount all
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting tmpfs to /usr/local/var/singularity/mnt/session
DEBUG   [U=1001,P=28648]   mountImage()                  Mounting loop device /dev/loop1 to /usr/local/var/singularity/mnt/session/rootfs
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting overlay to /usr/local/var/singularity/mnt/session/final
DEBUG   [U=1001,P=28648]   setSlaveMount()               Set RPC mount propagation flag to SLAVE
VERBOSE [U=1001,P=28648]   Passwd()                      Checking for template passwd file: /usr/local/var/singularity/mnt/session/rootfs/etc/passwd
VERBOSE [U=1001,P=28648]   Passwd()                      Creating passwd content
VERBOSE [U=1001,P=28648]   Passwd()                      Creating template passwd file and appending user data: /usr/local/var/singularity/mnt/session/rootfs/etc/passwd
DEBUG   [U=1001,P=28648]   addIdentityMount()            Adding /etc/passwd to mount list
VERBOSE [U=1001,P=28648]   Group()                       Checking for template group file: /usr/local/var/singularity/mnt/session/rootfs/etc/group
VERBOSE [U=1001,P=28648]   Group()                       Creating group content
DEBUG   [U=1001,P=28648]   addIdentityMount()            Adding /etc/group to mount list
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /dev to /usr/local/var/singularity/mnt/session/final/dev
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /etc/localtime to /usr/local/var/singularity/mnt/session/final/etc/localtime
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /etc/hosts to /usr/local/var/singularity/mnt/session/final/etc/hosts
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /usr/local/etc/singularity/actions to /usr/local/var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=1001,P=28648]   mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /proc to /usr/local/var/singularity/mnt/session/final/proc
DEBUG   [U=1001,P=28648]   mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/proc
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting sysfs to /usr/local/var/singularity/mnt/session/final/sys
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /home/lfaino to /usr/local/var/singularity/mnt/session/home/lfaino
DEBUG   [U=1001,P=28648]   mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/home/lfaino
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /usr/local/var/singularity/mnt/session/home/lfaino to /usr/local/var/singularity/mnt/session/final/home/lfaino
DEBUG   [U=1001,P=28648]   mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/home/lfaino
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /home/lfaino/mysql/run/mysqld to /usr/local/var/singularity/mnt/session/final/run/mysqld
DEBUG   [U=1001,P=28648]   mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/run/mysqld
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /tmp to /usr/local/var/singularity/mnt/session/final/tmp
DEBUG   [U=1001,P=28648]   mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/tmp
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /var/tmp to /usr/local/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=1001,P=28648]   mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=1001,P=28648]   mountGeneric()                Skipping mount /usr/local/var/singularity/mnt/session/final/home/lfaino, /usr/local/var/singularity/mnt/session/final/home/lfaino already mounted
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /usr/local/var/singularity/mnt/session/etc/resolv.conf to /usr/local/var/singularity/mnt/session/final/etc/resolv.conf
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /usr/local/var/singularity/mnt/session/etc/passwd to /usr/local/var/singularity/mnt/session/final/etc/passwd
DEBUG   [U=1001,P=28648]   mountGeneric()                Mounting /usr/local/var/singularity/mnt/session/etc/group to /usr/local/var/singularity/mnt/session/final/etc/group
DEBUG   [U=1001,P=28648]   create()                      Chroot into /usr/local/var/singularity/mnt/session/final
DEBUG   [U=0,P=32553]      Chroot()                      Change current directory to /usr/local/var/singularity/mnt/session/final
DEBUG   [U=0,P=32553]      Chroot()                      Hold reference to host / directory
DEBUG   [U=0,P=32553]      Chroot()                      Called pivot_root on /usr/local/var/singularity/mnt/session/final
DEBUG   [U=0,P=32553]      Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=32553]      Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=32553]      Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=32553]      Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=1001,P=28648]   create()                      Chdir into / to avoid errors
DEBUG   [U=0,P=32552]      set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=32552]      prepare_scontainer_stage()    Entering in scontainer stage 2
DEBUG   [U=1001,P=32552]   set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1001,P=32552]   startup()                     Execute scontainer stage 2
DEBUG   [U=1001,P=28648]   PostStartProcess()            Post start process

**Comment by cclerget** [comment]
@lfaino You observe a difference because with v2 the cached image was stored as a sandbox directory, in v3 the caching method changed and temporary images are stored in a SIF image, SIF image contains as primary partition a squashfs filesystem, with squashfs all files are `root:root` owned by default. Is it blocking for you workflow ?

**Comment by lfaino** [comment]
Yes, it blocks one application in an image. Is it possible to have the same behavior as in 2.6.0?

**Comment by lfaino** [comment]
Hi @jscook2345 ,
did you change the code to solve the issue that i had on Singularity 3.0?

Cheers
Luigi

**Comment by DrDaveD** [comment]
@bauerm97 underlay can actually introduce the opposite effect, where it looks like system directories are owned by the individual user.

@lfaino you could probably get behavior in the image similar to 2.6 by explicitly creating a sandbox with singularity build -s and running that, if that helps.

@cclerget, this new default also introduces a new requirement for root privilege in order to mount the SIF image.  I suggest adding a -s sandbox option to the shell/run/exec commands to get the old behavior, and default to it when running unprivileged.

**Comment by bauerm97** [comment]
I think this is solved now from #2838
