### ISSUE TITLE
Only last %post section is processed when building an image

### ISSUE THREAD

**Issue by samcmill** [apptainer/singularity#2349]
## Version of Singularity:

3.0.0

### Expected behavior

Given the following def file, successfully create an image file.  Note that the def files has multiple `%post` sections.

```
From: centos:7
Bootstrap: docker
%post
    . /.singularity.d/env/10-docker.sh

# GNU compiler
%post
    yum install -y \
        gcc \
        gcc-c++
    rm -rf /var/cache/yum/*

%files
    sources/hello.c /var/tmp/hello.c

%post
    cd /
    gcc -o /var/tmp/hello /var/tmp/hello.c
```

### Actual behavior

```
$ sudo singularity build hello.simg Singularity.def
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:   Starting build...
Getting image source signatures
Copying blob sha256:aeb7866da422acc7e93dcf7323f38d7646f6269af33bcdb6647f2094fc4b3bf7
71.24 MiB / 71.24 MiB [====================================================] 7s
Copying config sha256:1e8ad5e15a62dea6c1a650a7ff14da420854aaac4f3b2b5e5da9f70fc6c22ec6
1.05 KiB / 1.05 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:   Copying sources/hello.c to /var/tmp/hello.c
INFO:   Running post scriptlet
+ cd /
+ gcc -o /var/tmp/hello /var/tmp/hello.c
/bin/sh: line 1: gcc: command not found
FATAL:   post proc: exit status 127
FATAL:   While performing build: while running engine: exit status 255\n",
FATAL:   failed to retrieved path for hello.simg: lstat hello.simg: no such file or directory
ERROR  : Child exit with status 255
```

Note that only the final `%post` section is actually evaluated.

### Steps to reproduce behavior

See above.

The image builds correctly with 2.5.2 and 2.6.0.

**Comment by samcmill** [comment]
I've also observed that the behavior is not deterministic.  Sometimes it evaluates the GNU compiler install `%post` block and skips the other `%post` blocks.

**Comment by samcmill** [comment]
This diff resolves the issue, but I have not explored the full implications of the change.

```
diff --git a/src/pkg/build/types/parser/deffile.go b/src/pkg/build/types/parser/deffile.go
index 2b7d67f..609d9cd 100644
--- a/src/pkg/build/types/parser/deffile.go
+++ b/src/pkg/build/types/parser/deffile.go
@@ -147,7 +147,7 @@ func parseTokenSection(tok string, sections map[string]string) {
 	}
 
 	sectionsMutex.Lock()
-	sections[key] = strings.TrimRightFunc(split[1], unicode.IsSpace)
+	sections[key] += strings.TrimRightFunc(split[1], unicode.IsSpace) + "\n"
 	sectionsMutex.Unlock()
 }
```

**Comment by jscook2345** [comment]
@samcmill 

I believe there is a PR that will resolve the issue, but it is likely going to be redone due to a reorg of the files in the repo. I will have the dev make sure to reference this bug.

**Comment by samcmill** [comment]
Related to #1719

**Comment by GodloveD** [comment]
One question.  Is it expected that the sections are going to run in order above?  AFAIK, that is not the case in any version of Singularity.  `%files` will run before any `%post` sections and the `%post` sections will just be appended to one another.  Is that the desired behavior here?  Seems like not, but I don't really know what we would do about it.  `%files` should always run before `%post` or we will be changing a very basic aspect of def file parsing that might break a lot of people's workflows.

**Comment by al3x609** [comment]
Hi, 
As a user, I think that multiple %post confuses the installation flow.

this should be like...

```
 %appinstall foo

   touch foo.exec
```

**Comment by samcmill** [comment]
The issue request is simply to re-allow multiple instances of the same section as permitted in version 2.  No expectation to change the inter-section ordering semantics.  In the above example, the `%files` section would execute first, followed by the 3 `%post` sections in the order they appear.
