### ISSUE TITLE
Singularity RPM spec file hard codes amd64 arch for go

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#2350]
## Version of Singularity:
3.0.1

### Actual behavior
The singularity.spec file hard codes `amd64` for the architecture when downloading Go. We should have a way that the architecture can be changed when doing the build of the RPM. For example:

```
rpmbuild --define '_goarch ppc64le' [...]
```

`%{_arch}` cannot be used as that returns x86_64 and not amd64.

**Comment by jmstover** [comment]
@DrDaveD ... What do you think of adding something like:
```
%{!?_goarch:amd64}
```

If I remember my syntax right, if `_goarch` isn't set, it gets defined to `amd64`. Then we'd do:
```
GOTAR=go%{goversion}.linux-%{_goarch}.tar.gz
```

And if you want to change it when building, you can do as mentioned in the issue.

**Comment by DrDaveD** [comment]
We should be able to better than that, we should be able to automate it.  If there's not already an rpm variable defining the architecture, we could run /bin/arch and map that to the architectures that go supports.

**Comment by jmstover** [comment]
That's what I was trying to not do... Have a large mapping that we'd need to maintain.

**Comment by DrDaveD** [comment]
Well you could keep it a small mapping by only including the architectures that people ask for in an rpm.

**Comment by DrDaveD** [comment]
I have been googling to see what people have done before and from [this spec file](https://github.com/kovyrin/rpmbuild/blob/master/golang/SPECS/golang.spec) and [this fedora mailing list post](https://lists.fedoraproject.org/pipermail/devel/2015-July/212117.html) it appears that for rpm people mostly care about x86 and arm, 32 bit and 64 bit.

**Comment by AEI-SteffenG** [comment]
While that should cover most users (if armhf is included for Raspbian), there's Power 8 and 9 out there, and one future user just rises his hand ;) A generic solution would be preferred - why not list go as a versioned build dependency? (This would have the side effect of not requiring internet access for the build.)

**Comment by DrDaveD** [comment]
Do you mean you want to list a go version in Requires, an rpm?  Where's that going to come from?

**Comment by DrDaveD** [comment]
Oh, I am surprised to see golang-1.11.1-1 in EPEL.  Yeah, that should work well.

**Comment by DrDaveD** [comment]
Oh but no, it is in EPEL6, but not EPEL7.  There is an older version (1.9.4) in the base operating system yum repository and they apparently do not want to override it in EPEL.

**Comment by DrDaveD** [comment]
I suppose we could at least require a golang rpm of any version, and then if the version isn't new enough we could use "go env GOARCH" to find the architecture.

**Comment by DrDaveD** [comment]
I am attempting to build singularity on fedora/epel and this architecture issue is quite a problem because they build for multiple platforms.  On epel7 it even has an architecture that has no go binary download, ppc64 (it also has ppc64le which does have a download).   In addition, the fedora/epel koji build system does not allow network downloads.  So I'm wondering if the golang 1.9.4 rpm is new enough.  It's not extremely old.  3.0.1 does compile.  There's a problem with at least the go fmt I know, but maybe we could ignore that if the go version is too old.  Worst case we could include the go1.11 source tarball and compile it with the older golang if the installed version is too old.  I will do some experimenting.

**Comment by DrDaveD** [comment]
I learned through testing that the current centos:7 in docker is now centos 7.6, and that it no longer contains golang at all.  Instead, according to [this thread](https://www.centos.org/forums/viewtopic.php?t=68990&p=289683), version 1.11.2 is now in epel-testing and will soon be in epel.  That will simplify things for me a lot!  It can also be be installed via Red Hat's devtoolset system.  I am familiar with that; it's a bit more complicated to use, but a nice thing about it is that you can choose your language version.

**Comment by jmstover** [comment]
Cool. I say once it hits EPEL proper, we remove the section that downloads Go completly and make it a build prerequisite instead.

Will still need to go the GOPATH at rpm build time, but that's minor in comparison.

**Comment by DrDaveD** [comment]
Just to clarify something I said yesterday:

> I learned through testing that the current centos:7 in docker is now centos 7.6

Actually /etc/redhat-release still says 7.5, but every yum install comes from 7.6.

**Comment by DrDaveD** [comment]
golang-1.11.2 is now in the regular epel repository.  I have worked on a pull request for changing to use it, and it is failing some of the 'make test' tests in travis.  I'm not sure if it is just the language version change or something else related to the change to an rpm.  I'll keep looking into it.
