### ISSUE TITLE
unsquashfs not found

### ISSUE THREAD

**Issue by jeffcbecker** [apptainer/singularity#2352]
## Version of Singularity:

3.0 (top of tree as of 11/5)

### Expected behavior

successful sandbox build from singularity image

### Actual behavior

FATAL:   While performing build: packer failed to pack: exec: "unsquashfs": executable file not found in $PATH

Note that when I do $ which unsquashfs, I get the version in my $PATH - it's in the same directory as mksquashfs, which is specified at the end of the singularity.conf file.

### Steps to reproduce behavior

singularity build -s my-sandbox-dir my-singularity-image.simg

**Comment by jscook2345** [comment]
@jeffcbecker 

There's a few things that *could* be at play here. So if you could answer a few questions that would be helpful!

1. What is the output of `which unsquashfs` ?

2. Are you running your build command as `sudo`?

3. What is the output of `sudo which unsquashfs` ?

**Comment by jeffcbecker** [comment]
$ which unsquashfs
/nobackupnfs2/jcbecker/pkgsrc/bin/unsquashfs

Note from singularity.conf:

# MKSQUASHFS PATH: [STRING]
# DEFAULT: Undefined
# This allows the administrator to specify the location for mksquashfs if it is not
# installed in a standard system location
mksquashfs path = /nobackupnfs2/jcbecker/pkgsrc/bin/mksquashfs

Not sure if the path is supposed to include the executable (last component) or not.

I am not running as sudo.

**Comment by jscook2345** [comment]
@jeffcbecker 

If you're not running as `sudo`, are you running as root? You need to be a root-like user to create a container from a definition file.

What I'm trying to determine is if the `$PATH` environment variable for the user you're building your container as has the `unsquashfs` executable in it.

**Comment by jeffcbecker** [comment]
I'm trying to build a sandbox directory from a singularity image. I don't think I need elevated privilege to do that correct?

$ file /nobackupp12/lpan/ariamh_singularity//*.simg
/nobackupp12/lpan/ariamh_singularity//hysds_ariamh-2018-09-17-5fd66fd1b37e.simg: a /usr/bin/env run-singularity script executable (binary data)
$ singularity build -s sandbox /nobackupp12/lpan/ariamh_singularity//hysds_ariamh-2018-09-17-5fd66fd1b37e.simg
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
ERROR:   unsquashfs Failed: exec: "unsquashfs": executable file not found in $PATH
ERROR:   unpackSquashfs Failed: exec: "unsquashfs": executable file not found in $PATH
FATAL:   While performing build: packer failed to pack: exec: "unsquashfs": executable file not found in $PATH

**Comment by jscook2345** [comment]
Can you try building the sandbox using the `-d` flag?

    singularity -d build -s sandbox img

**Comment by jeffcbecker** [comment]
Results below

$ singularity -d build -s sandbox /nobackupp12/lpan/ariamh_singularity/hysds_ariamh-2018-09-17-5fd66fd1b37e.simg 
WARNING [U=4828,P=62412]   sylabsToken()                 Authentication token file not found : Only pulls of public images will succeed
DEBUG   [U=4828,P=62412]   func1()                       Registering plugin as type BuildPlugin
DEBUG   [U=4828,P=62412]   Init()                        Entering image format intializer
DEBUG   [U=4828,P=62412]   Init()                        Check for image format sif
DEBUG   [U=4828,P=62412]   Init()                        Opening /nobackupp12/lpan/ariamh_singularity/hysds_ariamh-2018-09-17-5fd66fd1b37e.simg in read-only mode: no write permissions
DEBUG   [U=4828,P=62412]   Init()                        sif format initializer returns: SIF magic not found
DEBUG   [U=4828,P=62412]   Init()                        Check for image format sandbox
DEBUG   [U=4828,P=62412]   Init()                        sandbox format initializer returns: not a directory image
DEBUG   [U=4828,P=62412]   Init()                        Check for image format squashfs
DEBUG   [U=4828,P=62412]   NewBundle()                   Created temporary directory for bundle /tmp/sbuild-165625955
INFO    [U=4828,P=62412]   Full()                        Starting build...
DEBUG   [U=4828,P=62412]   Init()                        Entering image format intializer
DEBUG   [U=4828,P=62412]   Init()                        Check for image format sif
DEBUG   [U=4828,P=62412]   Init()                        Opening /nobackupp12/lpan/ariamh_singularity/hysds_ariamh-2018-09-17-5fd66fd1b37e.simg in read-only mode: no write permissions
DEBUG   [U=4828,P=62412]   Init()                        sif format initializer returns: SIF magic not found
DEBUG   [U=4828,P=62412]   Init()                        Check for image format sandbox
DEBUG   [U=4828,P=62412]   Init()                        sandbox format initializer returns: not a directory image
DEBUG   [U=4828,P=62412]   Init()                        Check for image format squashfs
DEBUG   [U=4828,P=62412]   GetLocalPacker()              Packing from Squashfs
DEBUG   [U=4828,P=62412]   unpackSquashfs()              Creating copy of /nobackupp12/lpan/ariamh_singularity/hysds_ariamh-2018-09-17-5fd66fd1b37e.simg without header at /tmp/sbuild-165625955/trim.squashfs569888870
DEBUG   [U=4828,P=62412]   unpackSquashfs()              Unsquashing /tmp/sbuild-165625955/trim.squashfs569888870 to /tmp/sbuild-165625955/fs in Bundle
ERROR   [U=4828,P=62412]   unpackSquashfs()              unsquashfs Failed: exec: "unsquashfs": executable file not found in $PATH
ERROR   [U=4828,P=62412]   Pack()                        unpackSquashfs Failed: exec: "unsquashfs": executable file not found in $PATH
FATAL   [U=4828,P=62412]   run()                         While performing build: packer failed to pack: exec: "unsquashfs": executable file not found in $PATH

**Comment by jeffcbecker** [comment]
Additional info...

$ which unsquashfs
/nobackupnfs2/jcbecker/pkgsrc/bin/unsquashfs
$ which mksquashfs
/nobackupnfs2/jcbecker/pkgsrc/bin/mksquashfs
$ tail /nasa/singularity/3.0/etc/singularity/singularity.conf 
#cni plugin path =



# MKSQUASHFS PATH: [STRING]
# DEFAULT: Undefined
# This allows the administrator to specify the location for mksquashfs if it is not
# installed in a standard system location
mksquashfs path = /nobackupnfs2/jcbecker/pkgsrc/bin/mksquashfs

**Comment by jscook2345** [comment]
Can you do an `ls` so we can verify the permissions for the squashfs programs?

    ls -al /nobackupnfs2/jcbecker/pkgsrc/bin/*squashfs

**Comment by jmstover** [comment]
This is somewhat related:  #2385 

The `mksquashfs path` setting, changes the path for _only_ the `mksquashfs` call... The issue has been brought up and a fix will be in the works to also catch the `unsquashfs` call.

As a note, the `unsquashfs` call is new to 3.0. Previously, at this point, we mounted the image (as root), and now we're using unsquashfs to extract the contents, instead of mounting.

**Comment by jeffcbecker** [comment]
@jscook2345 

$ ls -al /nobackupnfs2/jcbecker/pkgsrc/bin/*squashfs
-rwxr-xr-x 1 jcbecker css 161768 Nov  5 08:46 /nobackupnfs2/jcbecker/pkgsrc/bin/mksquashfs
-rwxr-xr-x 1 jcbecker css  86568 Nov  5 08:46 /nobackupnfs2/jcbecker/pkgsrc/bin/unsquashfs

**Comment by jscook2345** [comment]
@jeffcbecker I believe @jmstover is working on a fix for this.

**Comment by al3x609** [comment]
I have same fail version 3.0.1-194.g02e5c07  -12/12 - Centos 7 kernel 4.19 - user root

**Comment by al3x609** [comment]
Update: the fix for me, re install squashfs-tools(centos) in a standard location.  `/sbin`
lol , My fault, bro.

**Comment by illusional** [comment]
We've had some issues with a similar error message, our problem is related to `mksquashfs` not being found, but as mentioned earlier, we feel the error is misleading: 
```
Failed: exec: "mksquashfs": executable file not found in $PATH
```

But it seems Singularity is only looking in the following places (https://github.com/sylabs/singularity/issues/2385#issuecomment-440518839 and hinted at before by use of "standard location" in this thread):
* `/bin/mksquashfs`
* `/usr/bin/mksquashfs`
* `/sbin/mksquashfs`
* `/usr/sbin/mksquashfs`
* `/usr/local/bin/mksquashfs`
* `/usr/local/sbin/mksquashfs`

Obviously, the workaround for us is to just install `squashfs-tools` in one of these search locations, but it would be great to adjust this error to give more information to inform the user that:
- It's not found in one of `/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin`, rather than mentioning the $PATH.
- They can override the the `mksquashfs` location with a .conf file (https://github.com/sylabs/singularity/pull/2157)
- Add some information into the documentation about the search locations and ability to override.

**Comment by jscook2345** [comment]
@sushma-98 @syl-ilumb @devprincess @jmstover 

Please consider @illusional 's comments for documentation. Thanks!
