### ISSUE TITLE
rpmbuild fails in SLES 12, possibly due to `%debug_package` 

### ISSUE THREAD

**Issue by fearful-symmetry** [apptainer/singularity#2362]
## Version of Singularity:
singularity version 3.0.1
RPM version 4.11.2

### Expected behavior
the RPM build instructions in `INSTALL.md` just work:

```bash

$ ./mconfig
$ make -C builddir rpm

```

### Actual behavior

The build fails as such:

```
+ /usr/lib/rpm/find-debuginfo.sh /home/alexk/rpmbuild/BUILD/
extracting debug info from /home/alexk/rpmbuild/BUILDROOT/singularity-3.0.1-52.ga33e9ff8.dirty.x86_64/usr/bin/singularity
extracting debug info from /home/alexk/rpmbuild/BUILDROOT/singularity-3.0.1-52.ga33e9ff8.dirty.x86_64/usr/lib/singularity/bin/starter
extracting debug info from /home/alexk/rpmbuild/BUILDROOT/singularity-3.0.1-52.ga33e9ff8.dirty.x86_64/usr/lib/singularity/bin/starter-suid
objcopy: '/home/alexk/rpmbuild/BUILDROOT/singularity-3.0.1-52.ga33e9ff8.dirty.x86_64/lus/iota-fs0/home/alexk/rpmbuild/BUILDROOT/singularity-3.0.1-52.ga33e9ff8.dirty.x86_64/usr/lib/singularity/bin/starter': No such file
*** ERROR: same build ID in nonidentical files!
        /usr/lib/singularity/bin/starter-suid
   and  /lus/iota-fs0/home/alexk/rpmbuild/BUILDROOT/singularity-3.0.1-52.ga33e9ff8.dirty.x86_64/usr/lib/singularity/bin/starter
error: Bad exit status from /var/tmp/rpm-tmp.HNNS1g (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.HNNS1g (%install)
Makefile:433: recipe for target 'rpm' failed
make: *** [rpm] Error 1
```

After some experimentation, it appears the breakage was caused by cdcbc92fd77e0faf257b7056ba2ebaf5a5c82dff , and removing the following line from `singularity.spec.in` magically fixes it:

```
%debug_package
```

After removing that line, rpm building seems to work on all subsequent releases.

(Also note that simply commenting out the line doesn't fix it, there seems to be some oddball bug with specfiles and commented out macros, I think related to this: https://github.com/rpm-software-management/rpm/issues/158

### Steps to reproduce behavior

Write here.

check out any commit past cdcbc92fd77e0faf257b7056ba2ebaf5a5c82dff , on a SLES 12 SP 3 machine (or, it's probably as simple as this particular RPM version), and try to build. Remove the above line and try again.

**Comment by fearful-symmetry** [comment]
I'm filing this bug as I'm not quite sure what the actual underling issue is, other than "the `%debug_package` macro breaks it." It could be an a singularity bug, or a rpm/sles bug, or some issue with our local config. Not sure.

**Comment by jmstover** [comment]
Hrmm... I just built on a SLES 12 sp3 VM without error from the Dist tarball. `debuginfo` did spit out some warnings, but it didn't throw an error.

Can you try this:
```
make -c builddir/ dist
rpmbuild -tb singularity-3.0.1.tar.gz
```

The `rpm` target _should_ be doing those same steps ... 

Or building from the release tarball with:  `rpmbuild -tb singularity-3.0.1.tar.gz`

**Comment by fearful-symmetry** [comment]
Nope, same result building from the release tarball and running `rpmbuild` manually.

This a Cray XC40 box, I wonder if it's either some compiler/toolchain issue, or if Cray is doing a terrible job at backporting various things from vanilla SLES 12 sp3.

**Comment by jmstover** [comment]
Okay ... looks like this worked for me to not build the debug version:

```
%if "%{_target_vendor}" != "suse"
%debug_package
%endif
```

Does this build for you? If so, I'll see about coming up with a way to make the debug package build controllable from a `--define` setting.

**Comment by fearful-symmetry** [comment]
Yep, that works! In this case, I'm a little more lost on what exactly the root cause is...

**Comment by jmstover** [comment]
It looks specifically like the RPM debuginfo stuff is throwing an error on the Build-ID. *Why* I don't know.

I know in my VM it's throwing a warning normally when processing the `singularity-debuginfo` package, so they may have decided that it was worthy of being an error. 

Anyway, can you test this change for me please:
```
%if ! 0%{_debug}
%debug_package
%endif
```

And build with:
`rpmbuild -ba --define '_debug 1' singularity-3.0.1.tar.gz`

We're still *defaulting* to having the debug, but you can remove that if needed.

Thanks.

**Comment by fearful-symmetry** [comment]
So it sounds like whatever this is could be the rpmbuild equivalent of `-Werror` ?

And yep, looks like that particular macro seems to work.

**Comment by jscook2345** [comment]
We should document this in the docs where RPMs are being built.

**Comment by jscook2345** [comment]
@jmstover Is this still an issue, and if so, should we document it?

**Comment by jmstover** [comment]
Shouldn't be.
