### ISSUE TITLE
singularity can't execute local bash script

### ISSUE THREAD

**Issue by GeoMicroSoares** [apptainer/singularity#2367]
## Version of Singularity:

2.5.0-HEAD.g50d254d

### Expected behavior

Trying to execute a bash script with a singularity image I built and is working properly. Idea is to have the image execute the file which in turn processes files in the folder I'm executing the command from.

Executing singularity as such: ```singularity exec $HOME/folder/singularity/singularity.img /bin/sh $HOME/scripts/script.sh```. I'd expect to see the outputs of my bash script as things are running.

All permissions have been given to the script and folder.

### Actual behavior

Am getting a ```/bin/sh: 0: Can't open script.sh```.

### Steps to reproduce behavior

Singularity file is a very simple one based on ```docker``` and ```ubuntu:18.04``` though I think it may not be that kind of issue.

Thanks!

**Comment by jmstover** [comment]
@GeoMicroSoares 
Can you run with the `-d` option and add the output? I can't replicate this:
```
$ /usr/local/singularity/2.5.0/bin/singularity --version
2.5.0-HEAD.g50d254d
$ sudo /usr/local/singularity/2.5.0/bin/singularity build ~/tmp/ubuntu_18.img docker://ubuntu:18.04      
Docker image path: index.docker.io/library/ubuntu:18.04
  [ ... ]
$ /usr/local/singularity/2.5.0/bin/singularity exec ~/tmp/ubuntu_18.img /bin/sh $HOME/scripts/script.sh
Hi from /home/jason/scripts/script.sh
$ cat $HOME/scripts/script.sh
#!/bin/sh

echo "Hi from $0"
```

Thanks.

*Edit:* I also changed my run to use `$HOME` instead of `~` on the image path and no change in output.

**Comment by dtrudg** [comment]
Hi @GeoMicroSoares - do you have this issue with a recent version of Singularity? It wasn't able to be reproduced, and the 3.x series is a complete rewrite so it might not be reproducible for you either now?
