### ISSUE TITLE
Missing documentation for the syntax of definition files

### ISSUE THREAD

**Issue by chenzhekl** [apptainer/singularity#2371]
## Version of Singularity:

Singularity 3.0

### Expected behavior

There is a section describing the syntax of definition files in the documentation.

### Actual behavior

Just some fragments touching the definition file which spreads across the documentation.

**Comment by kav2k** [comment]
This should probably be filed against https://github.com/sylabs/singularity-userdocs and/or https://github.com/sylabs/singularity-admindocs

**Comment by chenzhekl** [comment]
Sorry, I overlooked that repo. I will file an issue there.
