### ISSUE TITLE
Possible to build on Alpine Linux?

### ISSUE THREAD

**Issue by stela5** [apptainer/singularity#2373]
Is it possible to build Singularity on Alpine Linux?

I installed the following packages:

`apk add go libc-dev linux-headers libressl-dev libuuid util-linux-dev libseccomp-dev`

Then I followed https://www.sylabs.io/guides/3.0/user-guide/quick_start.html#quick-installation-steps but when I run *./mconfig* I get:

```
INFO: userns and disable_suid are disabled. (mlocal/checks/basechecks.chk)
=> generating fragments ...
 found build modules:
   +-> internal/pkg/runtime/c/lib/util/util.mconf
error: n is not a keyword
```

p.s. https://pkgs.alpinelinux.org/packages?name=singularity&branch=edge lists a pre-built Singularity package but only for the s390x architecture (I need x86_64)

**Comment by yhcote** [comment]
Yes. You need to install gawk. Busybox AWK is not compatible with GNU AWK, New AWK, or any standard AWK really. We actually test all builds on Alpine linux as well through our CI. So we actively support building and running singularity v3 on Alpine Linux.

You may need to install a few other dependencies by the way. But in the end it should work.

Hope this helps.

**Comment by truatpasteurdotfr** [comment]
@stela5 could you try with this https://github.com/truatpasteurdotfr/singularity/blob/master/dist/alpinelinux/singularity-3.0.1/APKBUILD file ?

**Comment by stela5** [comment]
Thank you both. gawk got me past the original error but I ran into more errors which may be specific to my build machine so I'll close this for now.

**Comment by stela5** [comment]
Okay, I figured out my sudo issues so I'm back.  @truatpasteurdotfr, when I run your APKBUILD I get:

```
checking: feature: NO_NEW_PRIVS... ERROR: Kernel does not support NO_NEW_PRIVS. Updated Kernel is required.
>>> ERROR: singularity: all failed
```

I verified with:

```
curl -s https://www.sylabs.io/privtest/no_new_privs.sh | bash
ERROR: PR_SET_NO_NEW_PRIVS not working.
You must upgrade your kernel to use Singularity securely.
```

But my kernel is 4.4 and this feature was added to 3.5

```
uname -a
Linux 91e8f6cf-8c5e-68ef-ba25-b1e4ef5f9a50 4.4 BrandZ virtual linux x86_64 Linux
```

Thoughts?

**Comment by yhcote** [comment]
This check has issues since it tries to run a test program from /tmp. Your /tmp is most likely set with noexec.

This is already fixed in the master branch. Have you tried to build current?

**Comment by truatpasteurdotfr** [comment]
`BrandZ virtual linux x86_64 Linux` is that some kind of VPS? not really runnning on bare metal?

**Comment by stela5** [comment]
It's a Joyent Triton infrastructure container running on bare metal and upgraded to the latest version of Alpine Linux

```
cat /proc/version 
Linux version 4.4 (gcc version 4.4.4) BrandZ virtual linux
```

```
cat /etc/alpine-release 
3.8.1
```
I changed the test to run in /root but still got the same result

`pwd`

> /root

```
#!/bin/sh

cat > NO_NEW_PRIVS_test.c <<"EOF"
#include <sys/prctl.h>
#include <stdio.h>

int main(int argc, char **argv) {

    if ( prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) != 0 ) {
        printf("ERROR: PR_SET_NO_NEW_PRIVS not working.\n");
        printf("You must upgrade your kernel to use Singularity securely.\n");
        return 1;
    }

    if ( prctl(PR_GET_NO_NEW_PRIVS, 0, 0, 0, 0) != 1 ) {
        printf("ERROR: PR_GET_NO_NEW_PRIVS not working.\n");
        printf("You must upgrade your kernel to use Singularity securely.\n");
        return 1;
    }

    printf("Good news! This kernel supports the PR_SET_NO_NEW_PRIVS feature!\n");
    return 0;
}
EOF

cc NO_NEW_PRIVS_test.c -o NO_NEW_PRIVS_test
./NO_NEW_PRIVS_test
```

> ERROR: PR_SET_NO_NEW_PRIVS not working.
> You must upgrade your kernel to use Singularity securely.

I then tried to build directly from git

```
apk add go libc-dev linux-headers libressl-dev libuuid util-linux-dev libseccomp-dev gawk alpine-sdk squashfs-tools

echo 'export GOPATH=${HOME}/go' >> ~/.bashrc
echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc
source ~/.bashrc

mkdir -p $GOPATH/src/github.com/sylabs
cd $GOPATH/src/github.com/sylabs
git clone https://github.com/sylabs/singularity.git
cd singularity

go get -u -v github.com/golang/dep/cmd/dep

cd $GOPATH/src/github.com/sylabs/singularity
./mconfig
```

>  checking: feature: NO_NEW_PRIVS... ERROR: Kernel does not support NO_NEW_PRIVS. Updated Kernel is required.

Looks like I might need a true bare metal install of Alpine Linux to get this to work...

**Comment by stela5** [comment]
Update: I discovered the Alpine Linux team has [marked this package as unmaintained](https://bugs.alpinelinux.org/issues/8072) so I'll rethink my infrastructure strategy.  Thanks to you both for your help!

**Comment by vsoch** [comment]
hey everyone! Try this:

```bash
FROM iron/go:dev

# alpine image with the go tools

RUN apk update && \
    apk add --virtual automake build-base linux-headers libffi-dev
RUN apk add --no-cache bash git openssh gcc squashfs-tools sudo libtool gawk
RUN apk add --no-cache linux-headers build-base openssl-dev util-linux util-linux-dev

LABEL Maintainer vsochat@stanford.edu
RUN mkdir -p /usr/local/var/singularity/mnt && \
    mkdir -p $GOPATH/src/github.com/sylabs && \
    cd $GOPATH/src/github.com/sylabs && \
    git clone -b release-3.0 https://github.com/sylabs/singularity.git && \
    cd singularity && \
    go get -u -v github.com/golang/dep/cmd/dep && \
    ./mconfig -p /usr/local && \
    make -C builddir && \
    make -C builddir install

RUN apk del automake libtool m4 autoconf alpine-sdk linux-headers

ENTRYPOINT ["/usr/local/bin/singularity"]
```
Definitely could be tidied up a bit, but seems to do the trick. Thanks for the note about gawk, I was running into the "n is not a keyword"  and search led me here! Adding the package was the fix that finished the build. Note that I haven't tested all functionality, please post here if there are issues (I suspect there might be with containers in containers!)
