### ISSUE TITLE
provide a `make uninstall` target

### ISSUE THREAD

**Issue by truatpasteurdotfr** [apptainer/singularity#2374]
## Version of Singularity: 

3.0.1 release

### Expected behavior

sudo `make uninstall` would be a nice feature to revert the `make install` step

### Actual behavior

non existent

### Steps to reproduce behavior

installing from source, one might want to have a procedure to remove after testing.

**Comment by truatpasteurdotfr** [comment]
```
alpine:~/go/src/github.com/sylabs/singularity/builddir$ sudo make install
 INSTALL /usr/local/bin/singularity
 INSTALL /usr/local/libexec/singularity/bin/starter
 INSTALL SUID /usr/local/libexec/singularity/bin/starter-suid
 INSTALL /usr/local/var/singularity/mnt/session
 INSTALL /usr/local/etc/singularity/singularity.conf
 INSTALL /usr/local/bin/run-singularity
 INSTALL /usr/local/etc/singularity/capability.json
 INSTALL /usr/local/etc/singularity/ecl.toml
 INSTALL /usr/local/etc/bash_completion.d/singularity
 INSTALL /usr/local/etc/singularity/actions
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/bandwidth
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/bridge
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/dhcp
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/flannel
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/host-device
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/host-local
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/ipvlan
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/macvlan
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/portmap
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/ptp
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/static
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/tuning
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/vlan
 INSTALL CNI CONFIGURATION FILES
 INSTALL /usr/local/etc/singularity/seccomp-profiles/default.json
 INSTALL /usr/local/etc/singularity/nvliblist.conf
 INSTALL /usr/local/etc/singularity/cgroups/cgroups.toml
 DONE
```

**Comment by GodloveD** [comment]
Good idea @truatpasteurdotfr !  (Also good to see you around!)

**Comment by yhcote** [comment]
I think "make uninstall" may be difficult to get right because there's no
way to make sure what you delete has been created by the current build
system instance. I think we should let package managers removing files.

For development another way to deal with transient builds is by setting
--prefix=/some/tmp/location and install in a directory that can easily be
removed entirely.

Cheers,

 - Yannick

**Comment by truatpasteurdotfr** [comment]
> there's no way to make sure what you delete has been created by the current build system instance.

right, that the task of a package manager.
The use case is `make uninstall` would only remove the list of files that `make install` pushed (as `install` could also have overwritten files that were already in place).

**Comment by dtrudg** [comment]
With plugins etc. and the variety of config files this is quite difficult to address. Only removing what `make install` installs could leave partially installed plugins etc. Package manager uninstall definitely preferred.
