### ISSUE TITLE
Handle Docker Username and Password Env Vars

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#2384]
## Version of Singularity:

singularity --version
singularity version 3.0.1-52.ga33e9ff8

### Expected behavior

Use `SINGULARITY_DOCKER_USERNAME` and `SINGULARITY_DOCKER_PASSWORD` for docker authentication when present.

### Actual behavior

Singularity ignores these variables.

### Steps to reproduce behavior

Set `SINGULARITY_DOCKER_USERNAME` and `SINGULARITY_DOCKER_PASSWORD` and try to pull from a private docker registry that requires authentication.

**Comment by tamasgal** [comment]
This is directly related to https://github.com/sylabs/singularity/issues/2377
