### ISSUE TITLE
Singularity relies on fixed paths for system executables

### ISSUE THREAD

**Issue by bbarker** [apptainer/singularity#2385]
## Version of Singularity:

2.6.0

### Expected behavior

Singularity to resolve system binaries based on PATH, not fixed locations.

### Actual behavior

Opposite of above, e.g:
```
singularity pull shub:// ...
/usr/bin/env: ‘python’: No such file or directory
```

But `which python` does return a valid python interpreter, just not at /bin/python`

Other errors for binaries, e.g. `mktemp`:

```
/home/ccrs/.local/libexec/singularity/cli/pull.exec: line 100: mktemp: command not found  
```

### Steps to reproduce behavior

Admittedly you have to use a fairly non-standard setup but it seems also a bit non-standard to use fixed paths for binaries, in general. Take for instance the module system, which might load different executables into your environment

**Comment by jmstover** [comment]
When Singularity is executed, a restrictive PATH is set...  This is a path similar to:
`/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin`

So we are reverting to a pure system PATH layout.

**Comment by bbarker** [comment]
It isn't necessarily pure in the following sense: a user with installation access could still modify the version of executables found on the system paths. But I assume this is to prevent possible security issues related to users using their own deviant executables found in local locations on PATH?

**Comment by jmstover** [comment]
Correct. As a limitation, we restrict the search path to system paths for what Singularity searches for when it needs an application.

**Comment by bbarker** [comment]
OK, fair enough!
