### ISSUE TITLE
cgroups documentation fix

### ISSUE THREAD

**Issue by hearnsj** [apptainer/singularity#2387]
## Version of Singularity:

3.0.1-1.fc29

### Expected behavior
Documentation.  At page https://syslabs.io/guides/3.0/user-guide/cgroups.html the example TOML file is said to be at location /usr/local/etc/singularity/cgroups/cgroups.toml

### Actual behavior

On a Fedora 29 system the file is /etc/singularity/cgroups/cgroups.tomp

**Comment by kav2k** [comment]
You may want to file this bug against https://github.com/sylabs/singularity-userdocs

**Comment by jscook2345** [comment]
This issue was re-created in sylabs/singularity-userdocs#32
