### ISSUE TITLE
Feature Request: building single application 'exec only' containers for nonroot users

### ISSUE THREAD

**Issue by rgiannico** [apptainer/singularity#2389]
Version of Singularity: 3.0.1
Feature Request: building 'exec only' containers for nonroot users

### References
I noticed something similar has already been asked here #1492  but never really answered. 
Something somehow similar has also been discussed here #302 and closed with a fork of Singularity v2.1.2 but I do not think this solves my question either. 

### Details
I'd like to create a container where:
- root has full access and full control as always
- non-root users can only "execute" the container as a single application without permission to look inside (to see and edit sourcecode). This means for example no "shell" permission, and no "exec /bin/bash" permission. This probably (but not necessarily) means giving non-root users permission to only execute one and only specific script. 

This will make possible to distribute a container as a safe single application. 

### Ideas
Maybe this could be done by giving nonroot users, permission to only execute the %runscript and nothing else. But I'm still far from finding how to do that

**Comment by GodloveD** [comment]
Thank you for the feature request @rgiannico!

>This will make possible to distribute a container as a safe single application.

Can you please elaborate a bit on why this method will be _safer_ than distributing containers that users can shell into?

**Comment by rgiannico** [comment]
Thank you for the question @GodloveD  :) 
You are right, "safe" is not the best word but I couldn't find a better one. Maybe "protected" is better. 
Singularity is great today to distribute free opensource applications, but I think this new feature will also help to easily distribute and share applications that are free to use but not opensource. 

For example: 
- Let's say a company sells an instrument connected to a computer/server. The instrument collects data and the computer/server run some analysis and produce some results. The company could use Singularity to wrap the analysis application inside the computer/server. Users can use it (run the analysis) but not look inside (the app is not opensource). The company can remotely connect with root credentials to check and maybe upgrade the app when needed. 
- Let's say 3 scientists from 3 different companies want to cooperate, but their companies do not agree to make their applications completely open (maybe trivially because they have not been published yet). The scientist could create a "common ground" and use eachother's tools without access to the sourcecode.

**Comment by GodloveD** [comment]
Makes perfect sense.  Thanks for your patience @rgiannico!

**Comment by bauerm97** [comment]
@rgiannico I just want to chime in here a bit and see if it's possible to already solve your 

>to easily distribute and share applications that are free to use but not opensource.

Consider this definition file:

```
bootstrap: docker
from: golang:1.11-alpine

%post
    go get github.com/bauerm97/some_private_software
    cd $GOPATH/src/github.com/bauerm97/some_private_software
    go build ./...
    cp $BINARY_ARTIFCAT $SOME_PLACE_IN_PATH
    rm -rf $GOPATH/src/github.com/bauerm97

%runscript
    $BINARY_ARTIFACT
```

I wonder if this suits your need. This allows you to distribute your application binary, but anybody who does a `singularity exec container` will not have access to the source code. Let me know what you think about this idea!

Cheers

**Comment by rgiannico** [comment]
@bauerm97  thanks for your answer :) 
Unfortunately (if I understand it well) your solution only works with compiled languages like GO or C++, but (with some exceptions) most of the labs' scientific tools are typically written in languages like Python, Perl, Ruby or even R. No binaries here!

Am I right? Or you think your solution could somehow work with interpreted languages too? 

Thanks!

**Comment by dtrudg** [comment]
This isn't really possible for Singularity to address easily, as for a user to run something in a container they have to be able to access what's in the container. Obfuscation has to be done when building the container, and can't be handled by Singularity here. Even if we restricted using `shell` and `exec` on a container, the user could extract the container squashfs to access the content, or similar.

Encryption support from 3.4.x protects content from people without a key, but those with the key necessary to use the container could still extract the content.
