### ISSUE TITLE
Non-root users can no longer use --net for isolation

### ISSUE THREAD

**Issue by kav2k** [apptainer/singularity#2390]
## Semantics of `--net` flag have changed for Singularity 3.x.

Previously, in 2.x:

```
    -n|--net            Run container in a new network namespace (loopback is
                        only network device active)
```

And it was usable by non-root. Now in 3.x:

```
  -n, --net                    run container in a new network namespace
                               (sets up a bridge network interface by default)
      --network string         specify desired network type separated by
                               commas, each network will bring up a
                               dedicated interface inside container
                               (default "bridge")
      --network-args strings   specify network arguments to pass to CNI plugins
```

However, there's no way to specify "nothing but localhost" by default (presumably, possible by creating a custom SNI config) and no way to invoke that as non-root.

### Version of Singularity:

v.3.0.1

### Expected behavior

Ability to create a new network namespace as non-root.

```
$ singularity exec --net docker://alpine wget --spider -S example.com
wget: bad address 'example.com'
```

### Actual behavior

There's no way to unbundle the new CNI functionality.

```
$ singularity exec --net docker://alpine wget --spider -S example.com
FATAL:   container creation failed: Network requires root permissions
```

### Steps to reproduce behavior

Use `--net` with Singularity 3.x as non-root

### Thoughts on fix

This is a clear behavior change from 2.x; probably the best would be to _not_ try to create networks by default (require explicit `--network` for this) and thus allow isolation use as before by non-root users.

If that's not acceptable, a new flag is needed that reproduces 2.x `--net` functionality (`--no-net` was [proposed on Slack](https://singularity-container.slack.com/archives/C0YKGK6D6/p1542215268404300)). I _personally_ don't like this approach as it makes the flag for `--net` differ in semantics, in a non-obvious way, from `--pid` / `--ipc` / `--userns` / `--uts`.

**Comment by HenrikBengtsson** [comment]
This issue deserves a ['behavior change'](https://github.com/sylabs/singularity/labels/behavior%20change) label

**Comment by cclerget** [comment]
@kav2k Another solution would be, as regular user `--net` just set loopback interface and runtime clear any other network argument. When requested by root, the behaviour remains as the actual. Like that there is no behaviour change.

**Comment by kav2k** [comment]
It's even more _magic_ and inconsistency, and it's still a behaviour change for root.

What's so bad about requiring `--network` explicitly from root?

**Comment by cclerget** [comment]
@kav2k Trying to keep a behaviour of a not fully implemented feature in v2 is a bit weird, since network feature is fully implemented with v3, priority should be given to v3 behaviour. The idea is to avoid to specify `--network` as root to simplify command line usage. Instead of forcing root user to specify network I would go for an alternative by forcing a regular user to specify something like `--net --network=none` instead. If a user specify `--net` without `--network=none` that will generate an error message `Network requires root permissions or --network=none as regular user`

**Comment by GodloveD** [comment]
I actually liked your original proposal more @cclerget.  Nothing wrong with a little magic imho.  And the end result is identical without the added CLI complexity.

**Comment by cclerget** [comment]
@GodloveD In fact it may be good to explicitly specify the `--network=none` (even for root) if network container setup is handled by a third party tool, and `--network=none` for user is rather a corner use case.
