### ISSUE TITLE
Difference between Milestone '3.1.0 Release' vs Label 'Release 3.1.0'?

### ISSUE THREAD

**Issue by HenrikBengtsson** [apptainer/singularity#2391]
Trying to track this repos and what's on the Singularity roadmap.  What's the difference between:

* Milestone: [3.1.0 Release](https://github.com/sylabs/singularity/milestone/13)
* Label: [Release 3.1.0](https://github.com/sylabs/singularity/labels/Release%203.1.0)

?

**Comment by GodloveD** [comment]
Label just gives you a convenient way to scan the issues visually and see which ones are pertinent for the release.  While tagging the milestone allows you to look here and get a progress bar.  

https://github.com/sylabs/singularity/milestone/13

Really nothing much too it other than that.  😄

**Comment by HenrikBengtsson** [comment]
Hmm... I'm still confused. Are you just saying you like:
![screenshot from 2018-11-28 22-06-50](https://user-images.githubusercontent.com/1616850/49202604-fef66680-f359-11e8-8f9d-ad157a72daef.png)
better than:
![screenshot from 2018-11-28 22-06-35](https://user-images.githubusercontent.com/1616850/49202626-09186500-f35a-11e8-9ee7-d35e927ef2d3.png)
simply because the former is easier to spot?  But it's a bit the flavor of the day which is used and they're both indicate that the issues are aimed for the 3.1.0 release? And we have to look at the _union_ of the issues labeled "Release 3.1.0" and the one added to milestone "3.1.0 Release" gives us what's up for 3.1.0?

**Comment by GodloveD** [comment]
I think you might be overthinking things a bit.  These tools are not strictly used to indicate what is going into 3.1.0.  They are just used as a convenience to make it easier to spot and track PRs.  But it is a loose convention.

**Comment by HenrikBengtsson** [comment]
Still not sure I understand how they're used. Anyway, it sounds like there's no easy way to see what's on the short-term roadmap. Oh well...

**Comment by buckstephenh** [comment]
> Still not sure I understand how they're used. Anyway, it sounds like there's no easy way to see what's on the short-term roadmap. Oh well...

Projects...
