### ISSUE TITLE
ERROR: X is not configured correctly to support the C locale.

### ISSUE THREAD

**Issue by npiskun** [apptainer/singularity#2394]
## Version of Singularity:
3.0.1 

### Expected behavior
 Run Motif GUI  
### Actual behavior
GUI program crashed with 
ERROR: X is not configured correctly to support the C locale. 
### Steps to reproduce behavior
 I am using ubuntu 16.04 to both create and run container.

**Comment by jscook2345** [comment]
@npiskun 

Can you share the definition file you are building from or the image you are running?

**Comment by npiskun** [comment]
I am building from sandbox file. Basically I install graphical debugegr and copied missing shared libraries. 
Then did 
singularity build 
command

**Comment by jscook2345** [comment]
Have you tried generating a locale and then setting that?

Something like

    sudo locale-gen en_US.UTF-8

and than setting

    LC_ALL="en_GB.utf8"

in

    /etc/environment

**Comment by npiskun** [comment]
Sorry, this is probably sily question, but where shoul I execute this command? Inside sandbox container? If I try: 
singularity shell my_sandbox 
 locale-gen en_US.UTF-8 
I get bash: locale-gen: command not found

**Comment by jscook2345** [comment]
@npiskun 

Yes, you would do it in the container. You can also set it in the definition when building the image as well.

If `locale-gen` is not installed you should be able to install it using `apt` or `apt-get` on Ubuntu.

**Comment by npiskun** [comment]
Thanks, I tried recipe file with "apt install -y libxmu6" and it fixed it
