### ISSUE TITLE
Build instructions for singularity 3 - cannot obtain a version of Go

### ISSUE THREAD

**Issue by serbinsh** [apptainer/singularity#2402]
## Version of Singularity:

3
https://www.sylabs.io/guides/3.0/user-guide/

Apologies if this is addressed in: https://github.com/sylabs/singularity/issues/2232

### Expected behavior

According to the build instructions I need to obtain a version of Go but I have tried to access https://golang.org for three days without any success

### Actual behavior

Cannot load https://golang.org to obtain source code

### Steps to reproduce behavior

Visit https://golang.org or https://golang.org/dl/

**Comment by serbinsh** [comment]
![screen shot 2018-11-29 at 7 49 43 am](https://user-images.githubusercontent.com/3067369/49222951-5d980080-f3ab-11e8-8738-6a8ef08bf4d7.png)

Is this a user issue (i.e. me?) or a more general problem?

**Comment by serbinsh** [comment]
Strange, seems like the IP is resolving incorrectly for me?

```
$ export VERSION=1.11 OS=linux ARCH=amd64
$ wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz

--2018-11-29 07:54:37--  https://dl.google.com/go/go1.11.linux-amd64.tar.gz
Resolving dl.google.com (dl.google.com)... 127.0.0.10
Connecting to dl.google.com (dl.google.com)|127.0.0.10|:443... failed: Operation timed out.
Retrying.

--2018-11-29 07:55:54--  (try: 2)  https://dl.google.com/go/go1.11.linux-amd64.tar.gz
Connecting to dl.google.com (dl.google.com)|127.0.0.10|:443... failed: Operation timed out.
Retrying.

--2018-11-29 07:57:12--  (try: 3)  https://dl.google.com/go/go1.11.linux-amd64.tar.gz
Connecting to dl.google.com (dl.google.com)|127.0.0.10|:443... failed: Operation timed out.
Retrying.

--2018-11-29 07:58:32--  (try: 4)  https://dl.google.com/go/go1.11.linux-amd64.tar.gz
Connecting to dl.google.com (dl.google.com)|127.0.0.10|:443... failed: Operation timed out.
Retrying.

--2018-11-29 07:59:52--  (try: 5)  https://dl.google.com/go/go1.11.linux-amd64.tar.gz
Connecting to dl.google.com (dl.google.com)|127.0.0.10|:443...```

**Comment by kav2k** [comment]
Seems to be a network problem on your end; for whatever reason the DNS resolvers you're using are not returning the correct address.

Could be a misconfiguration, a sign of something malicious, or a sign of overzealous security interfering with your connection.

```
$ host dl.google.com
dl.google.com is an alias for dl.l.google.com.
dl.l.google.com has address 216.58.215.238
dl.l.google.com has IPv6 address 2a00:1450:400a:800::200e
```

In any case, it's not a bug or something that affects users at large, it's your local problem.

**Comment by serbinsh** [comment]
@kav2k Thanks.  I forwarded this site to our IT department and indeed it was being "blocked" for some reason.  In any event, this is now solved.
