### ISSUE TITLE
Text file busy when running a container multiple times

### ISSUE THREAD

**Issue by SebastianM-C** [apptainer/singularity#2403]
## Version of Singularity:

singularity version 3.0.1-1.el7

### Expected behavior

No error when running a container concurrently multiple times.

### Actual behavior

This error appears when trying to run a container while another (from the same file) is already running.
```
$ ./test.sif
-bash: ./test.sif: /usr/bin/env: bad interpreter: Text file busy
```

### Steps to reproduce behavior

1. Create a definition file `test.def`
```
Bootstrap: docker
From: ubuntu

%runscript
    read -p "waiting for input" a
```

2. `sudo singularity build test.sif test.def`

3. `./test.sif`

4. Now in another terminal try `./test.sif` again (while the other is still running)

I noticed that if I launch the second container with `singularity run test.sif`, it works.

**Comment by kav2k** [comment]
Seems relevant: https://stackoverflow.com/questions/1384398/usr-bin-perl-bad-interpreter-text-file-busy

If that is correct, then running the image directly somehow opens a handle for the file for writing when it shouldn't.

**Comment by phpHavok** [comment]
I checked processes with the file open while `./test.sif` was running:
```
[root@gideon temp]# lsof /home/jacob/temp/test.sif
COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
starter-s 7661 jacob  mem    REG   0,51 27983872 18354744 /home/jacob/temp/test.sif
starter-s 7661 jacob    8u   REG   0,51 27983872 18354744 /home/jacob/temp/test.sif
starter-s 7840 jacob  mem    REG   0,51 27983872 18354744 /home/jacob/temp/test.sif
starter-s 7840 jacob    8u   REG   0,51 27983872 18354744 /home/jacob/temp/test.sif
```
As you can see, two processes have the file open for read and write (that's what the u stands for after 8u, 8 being the file descriptor the file was assigned by the processes). On my system, those two processes were:
```
[root@gideon ~]# ps aux | grep 7661
jacob     7661  0.0  0.0 661168 11104 pts/2    Sl   22:00   0:00 Singularity runtime parent
[root@gideon ~]# ps aux | grep 7840
jacob     7840  0.0  0.0 660912 10992 pts/4    Sl   22:03   0:00 Singularity runtime parent
```
So indeed, the Singularity runtime parent is opening the file for writing.

**Comment by dnk8n** [comment]
Is there a workaround for this?

Its quite a limitation currently.

**Comment by ArangoGutierrez** [comment]
@dnk8n there is an open PR 
Respect a read-only file mode. #2426
Thanks to @phpHavok , so please give it a try and let us know in the PR.  
and if it doesn't work is @phpHavok fault, not mine  😜

**Comment by phpHavok** [comment]
:laughing:  I did break something else, but @cclerget caught it. I just submitted the new changes, so hopefully all is good now.

**Comment by dnk8n** [comment]
I know this is not the place to post this, but if you could direct me... what is the easiest way to upgrade singularity to master version of the source code?

**Comment by phpHavok** [comment]
@dnk8n You'll want to build singularity from source, see: https://www.sylabs.io/guides/3.0/user-guide/installation.html#download-singularity-repo-and-optionally-check-out-a-tag-or-branch

I'd suggest picking a non-standard location like /opt/singularity and installing there (`./mconfig --prefix=/opt/singularity`) and updating your path: `export PATH="/opt/singularity/bin:$PATH"`

EDIT: Also, for questions you can join the mailing list: https://groups.google.com/a/lbl.gov/forum/#!forum/singularity
