### ISSUE TITLE
[scif-apps] Apps features are incomplete on 3.0

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#2407]
## Version of Singularity:

```
[eduardo@rhel7 singularity]$ singularity version
3.0.1-87.gaabae96
```
### missing features

 - [x] retrieve list of `scif-apps` on the image
how to 2.x
```
singularity apps <image.sif>
```
 - [x] Retrieve section `%apphelp` 
how to in 2.x
```
$ singularity help --app foo <image.sif>
This is the help for foo!
```
 - [ ] ability to `inspect` a specific app
how to in 2.x
```
singularity inspect --app foo <image.sif>
```

**Comment by GodloveD** [comment]
Yeah.  Just discovered this too and then went to create an issue and discovered this.  

I suggest that we re-implement this command:

```
singularity apps <image.sif>
```

With something like this:

```
singularity inspect --apps <image.sif>
```

Note the **s** on --apps.  That way we don't need an `apps` command that just does one thing.  

I also suggest that we add a `run-help --app <app name>` option argument pair to the `run-help` command to retrieve the help info.  

But I know that @bauerm97 has implemented all of the app stuff as a plugin and so I don't feel comfortable just changing the `inspect` and `run-help` commands.

@bauerm97 thoughts?

**Comment by ArangoGutierrez** [comment]
More features missing 
 - https://github.com/sylabs/singularity/issues/2599
