### ISSUE TITLE
Incorrect recipe header variable substitution due to case sensitivity

### ISSUE THREAD

**Issue by omenos** [apptainer/singularity#2417]
## Version of Singularity:

3.0.1 (built RPM on CentOS 7.5)

### Expected behavior

When running a build off of a recipe file using `yum` as the `BootStrap`, the `MirrorURL` should substitute the `OSVersion` variable if used in the path. Ex:

```
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVersion}/%{OSVersion}/os/x86_64/
```
`MirrorURL` should become `http://mirror.centos.org/centos-7/7/os/x86_64/` at build time.

### Actual behavior

`%{OSVersion}` actually substitutes in with the (I think) encoding codes for `%{}` rather than the represented variable. Error is as follows:

```
INFO:    Starting build...
INFO:    Skipping GPG Key Import
http://mirror.centos.org/centos-%25%7BOSVersion%7D/%25%7BOSVersion%7D/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.



 One of the configured repositories failed (Linux  - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=base ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable base
        or
            subscription-manager repos --disable=base

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=base.skip_if_unavailable=true

failure: repodata/repomd.xml from base: [Errno 256] No more mirrors to try.
http://mirror.centos.org/centos-%{OSVersion}/%{OSVersion}/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
FATAL:   While performing build: conveyor failed to get: While bootstrapping: exit status 1
```

### Steps to reproduce behavior

Create a recipe file using `yum` and use a variable for `MirrorURL` to substitute that include lower case characters:

```
BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVersion}/%{OSVersion}/os/x86_64/
Include: yum yum-plugin-ovl vi less man which tzdata bash
```

### Steps for fix behavior

Convert variables used in `MirrorURL` to upper case and the build runs fine:

This is taken straight from the `singularity build --help` output: 

```
YUM/RHEL:
          Bootstrap: yum
          OSVersion: 7
          MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/x86_64/
          Include: yum
```

**Comment by jmstover** [comment]
@omento ...
That's a `yum` thing not us. I don't think yum itself accepts variables that are a different case ... since they would technically be different variables.

So, the variable doesn't get substituted, and then passed along as is, and should be URL encoded when the request is made. That gives you the: `%25%7B` == `%{` and `%7D` == `}`

But again, `OSVersion` would be a different variable than `OSVERSION`

**Comment by omenos** [comment]
So does `yum` do the path substitution or Singularity? My expectation was that as this definition method was a Singularity defined metric, the substitution would be executed before passing the expanded path to `yum`.

My understanding of the `yum` and `debootstrap` headers may be misinterpreted, though.

**Comment by jmstover** [comment]
`yum` does it. What you set for `MirrorURL` should be passed directly to `yum` without us modifying it, and then `yum` handles any of the substitutions within the URL.

@ikaneshiro 
We don't do any mangling of the MirrorURL definition entry do we?

**Comment by jscook2345** [comment]
@jmstover @ikaneshiro 

From the code it looks like a `singularity` issue. The issue is in `getBootstrapOptions()` in `internal/pkg/build/sources/conveyorPacker_yum.go`

**Comment by omenos** [comment]
@jscook2345 Specifically here?

```go
// look for an OS version if a mirror specifies it
	c.osversion = ""
	if strings.Contains(c.mirrorurl, `%{OSVERSION}`) || strings.Contains(c.updateurl, `%{OSVERSION}`) {
		c.osversion, ok = c.b.Recipe.Header["osversion"]
		if !ok {
			return fmt.Errorf("Invalid yum header, OSVersion referenced in mirror but no OSVersion specified")
		}
		c.mirrorurl = strings.Replace(c.mirrorurl, `%{OSVERSION}`, c.osversion, -1)
		c.updateurl = strings.Replace(c.updateurl, `%{OSVERSION}`, c.osversion, -1)
}
```

It seems that the uppercase string is hardcoded, rather than using a regex for the characters or using the defined string from the header.

**Comment by jmstover** [comment]
Hnn... Going back to the 2.x I see what they were doing. I don't know *why* he did it this way ... But, if `$OSVERSION` wasn't set, then it looked for `/etc/redhat-release`. Got the version from the RPM that owned that file ... otherwise set `OSVERSION=7` ... would break in all sorts of fun ways if there wasn't a `/etc/redhat-release` file.

So ... When building out the mirror entry in the `yum.conf` used it replaced the `%{[...]}` value. My guess is that running with `--installroot` caused `yum` to mess up on the variable replacement. But that's totally a guess at this point.... 

@ikaneshiro ... Looks like Go doesn't have a case insensitive search ... would something like:
```
strings.Contains(strings.ToLower(c.mirrorurl), strings.ToLower(`%{OSVERSION}`))
```
Work for this?

**Comment by ikaneshiro** [comment]
@jscook2345 @jmstover @omento Sorry for the delayed response!

@jmstover... That string replacement could be made to work, but I think using a regex (as @omento mentioned) is the best way to solve this.

Also, is the behavior of looking for `/etc/redhat-release` and then defaulting to `OSVERSION=7` something you think we should have in 3.x? Currently I throw an error if there's an `OSVersion` in a `mirrorURL` but no `OSVersion` specified in the definition

**Comment by jmstover** [comment]
> Currently I throw an error if there's an OSVersion in a mirrorURL but no 
> OSVersion specified in the definition

I think this is good. I don't think we should make assumptions on what the user wants, or if we do then it should be clearly documented.

I think in 2.x it was done that way as the default would be to base it on what your host is, since that makes the most sense with a yum/rpm bootstrap for the cleanest install.
