### ISSUE TITLE
catch python urllib2 error in api_get

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#242]
see https://github.com/gmkurtzer/singularity/issues/241

@gmkurtzer I can't assign myself, but I'll take care of this.

**Comment by gmkurtzer** [comment]
Weird that you can't assign yourself, but I took care of it. Thanks!!!!

**Comment by vsoch** [comment]
I'm not an owner on your repo, as it should be! This is why we need to move to singularityware _nudge nudge, wink wink_

**Comment by gmkurtzer** [comment]
Closing old tickets.
