### ISSUE TITLE
inspect --environment should display all user-added files

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2431]
## Version of Singularity:

3.0.1

### Expected behavior

I have the following in my `%environment` section:

```
%environment
        export FOO=bar
```

I have the following in my `%post` section:

```
%post
        echo "export THIS=that" >> $SINGULARITY_ENVIRONMENT
```

After building the container I should be able to do this and get the following output:

```
$ singularity inspect --environment my_container.sif

#!/bin/sh

        export FOO=bar

#!/bin/sh

        export THIS=that
```

Or some such thing.

### Actual behavior

All I get is this:

```
$ singularity inspect --environment my_container.sif

#!/bin/sh

        export FOO=bar
```

This is because only ``/.singularity.d/env/90-environment.sh`` is catted out with the above command.  We should also cat out ``/.singularity.d/env/91-environment.sh`` if it exists. (Can probably just cat out ``/.singularity.d/env/9*-environment.sh`` ftw).

**Comment by phpHavok** [comment]
@GodloveD I made that minor change, and it does work. Granted the indentation isn't perfect:
```
[jacob@saturn temp]$ singularity inspect --environment test.sif

#!/bin/sh

        export FOO=bar
export THIS=that
```
I can add a unit test for this case as well. Is the above output acceptable?

**Comment by bauerm97** [comment]
@phpHavok I think that if we're going to output both files, then we actually want to make it output something like this:

```
==90-environment.sh==
#!/bin/sh

        export FOO=bar

==91-environment.sh==
export THIS=that
```

My idea here is just that we should output the files exactly as they appear, but also make it clear which file is which. I'm not sure if the styling of `==91-environment.sh==` is perfect, but it gets my idea across.

**Comment by phpHavok** [comment]
@bauerm97 Got it working! PR incoming.

**Comment by EvanTheB** [comment]
Why not output all the environement scripts? Env vars from a docker build are not displayed. I don't understand the usecase where some but not all environment variables are shown.

It seems like when env is available in the image, these should print the same thing (barring the extra formatting from env):

singularity inspect --environment image 
singularity exec -C image env

**Comment by jscook2345** [comment]
@EvanTheB 

Would you mind opening this in a new issue for a fresh discussion since this one is closed? Thanks!
