### ISSUE TITLE
jobid etc logging

### ISSUE THREAD

**Issue by wpoely86** [apptainer/singularity#2432]
## Version of Singularity:
3.0.1

In version 2.x there was a file `/etc/singularity/init` which was run when a container was started. We had a line in there like:

```
/usr/bin/logger -t singularity -- "user=$USER image=$SINGULARITY_IMAGE jobid=${PBS_JOBID:-} cmd=$SINGULARITY_COMMAND"
```
So we would link singularity usage to jobid. 

This no longer works in version 3. It would be nice if some hook/option/... could be added so we could log jobid of users using singularity.

**Comment by dtrudg** [comment]
The example log plugin can be used as the basis for this in 3.6 - https://github.com/hpcng/singularity/tree/master/examples/plugins/log-plugin
