### ISSUE TITLE
[Question] How I can get image's metadata without singularity command?

### ISSUE THREAD

**Issue by al3x609** [apptainer/singularity#2439]
...

**Comment by jscook2345** [comment]
@al3x609 

What metadata are you trying to get at?

What filetype is the image you're building?

**Comment by al3x609** [comment]
Hi, i.e 
I am developing a web environment to manage containers, in which I wish to consult labels of an image (among others) and store them in a redis database. I want to have an external tool to manage this data, from a remote web client. How could I face this type of consultation? 

Maybe a REST API for singularity, and a endpoint `GET /containers/json `...
and a unix socket listening _unix:///var/run/singularity.sock_ ...

**Comment by yhcote** [comment]
Hi,

are you using Singularity 2.X or 3.X ?

**Comment by al3x609** [comment]
@yhcote  3.*

**Comment by yhcote** [comment]
Take a look at the SIF github repo for the "siftool" command line.

In the README file if you scroll down, you will see the instructions : $ go
get -u github.com/sylabs/sif/cmd/siftool , to download it.

to look at the SIF header of your 3.0 created container file, try :
 - siftool header container.sif

to see all the different data objects stored inside your SIF container file
:
 - siftool list container.sif

to inspect the meta data for a specific data object via its descriptor :
 - siftool info <ID> container.sif    , where <ID> is the ID listed in the
first column of the "siftool list" command.

Hope this helps, let me know if you have any questions.

Cheers,

 - Yannick

**Comment by al3x609** [comment]
@yhcote, thanks, I’ll check this direction out.
