### ISSUE TITLE
Building a container fails

### ISSUE THREAD

**Issue by Peter-Vincent** [apptainer/singularity#2440]
## Version of Singularity:

2.5.2

### Expected behavior

I expect the container to build without throwing any errors

### Actual behavior

I get the following error code

> `ERROR  : Duplicate bootstrap definition key found: '</div>'`
> `ABORT  : Retval = 255`
> 

### Steps to reproduce behavior

I have tried using a different (but very very similar) recipe, and that similarly failed, giving the same error.  The links to the two recipes I have used are given below.

https://github.com/ycrc/singularity-recipes/blob/master/Neurosuite/neurosuite-2.0.0-ubuntu-18.04.def
https://github.com/PeterVincent96/GAERS-Software/blob/master/neurosuite-2.0.0-ubuntu-16.04.def

**Comment by jmstover** [comment]
```
ERROR : Duplicate bootstrap definition key found: '</div>'
```
Ohh... I think you're trying to use the HTML output, not the raw output... 

Grab:
https://raw.githubusercontent.com/ycrc/singularity-recipes/master/Neurosuite/neurosuite-2.0.0-ubuntu-18.04.def
-or-
https://raw.githubusercontent.com/PeterVincent96/GAERS-Software/master/neurosuite-2.0.0-ubuntu-16.04.def

I just built the 18.04 version with 2.5.2 (build from Git tag).

-J

**Comment by Peter-Vincent** [comment]
Yes, thank you so much!

Sorry for my naivety!
