### ISSUE TITLE
Container storage too small to install required dependencies

### ISSUE THREAD

**Issue by Peter-Vincent** [apptainer/singularity#2442]
## Version of Singularity:

```
singularity --version
2.5.2-dist
```

### Expected behavior

I have built a container using Singularity, running Ubuntu 14.04.  I am now trying to install software inside this container (installing the software in the container build failed due to packages and dependencies not being installed).  I expected this to run without a problem - we have done this installation before on a virtual machine.

### Actual behavior

The installation fails because packages and dependencies can not be installed.  This is reportedly because the /var/cache/apt/archives folder is out of space, which can be seen in the snippet below.
```
The following NEW packages will be installed:
  libqtgui4 libqtwebkit4
0 upgraded, 2 newly installed, 0 to remove and 4 not upgraded.
4 not fully installed or removed.
Need to get 12.7 MB of archives.
After this operation, 48.6 MB of additional disk space will be used.
E: You don't have enough free space in /var/cache/apt/archives/.
Singularity neurosuite14.simg:/> df -H /var/cache/apt/archives
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop4      398M  390M     0 100% /
```
Is there a way to force the container to have a certain amount of storage?  The same directory on the host machine (running Ubuntu 16.04) has 344G available storage.

**Comment by jscook2345** [comment]
@PeterVincent96 

Can you provide the definition file and the build command you used so I can try to reproduce the issue?

Thanks!

**Comment by Peter-Vincent** [comment]
@jscook2345 Hi, thanks for helping with this

https://raw.githubusercontent.com/PeterVincent96/GAERS-Software/Alternate_Install2/neurosuite-2.0.0-ubuntu-14.04.def

This provides a link to the .def file.  In this file I have commented out the installation of all the programs I want - ideally these would be installed in the process of buidling the image, but this hasn't been working.  The problem I have discussed above is when I run the above file as written, creating an image with just the OS and some small packages, then I try and install the libklustersshared.

Please let me know what other information you need,

Thanks!

**Comment by dtrudg** [comment]
Hello. As you are likely aware, the newer SIF format containers in 3.x are immutable, so it is not possible to directly install additional software into them after the build. The workaround is to build to a sandbox, perform any interactive work in the sandbox with the `--writable` flag, and then build into a SIF file when done.
