### ISSUE TITLE
Move integration tests to their own package

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2447]
Integration tests should not be part of the 'main' package. They should be a part of a different package so that the namespace isn't polluted with main package code.

Tests
- [ ] cli_test.go
- [ ] deffile_test.go
- [ ] docker_test.go
- [ ] env_test.go
- [ ] help_test.go
- [ ] instance_test.go
- [ ] pull_test.go
- [ ] security_test.go

**Comment by dtrudg** [comment]
Don't believe this is relevant now as we should be moving to drop the integration tests which are now mostly duplicated in e2e... and then tidy up what is left as neccessary.
