### ISSUE TITLE
Move integration tests to their own directory

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2448]
The integration tests should be moved to their own directory under /tests/e2e or something similar so they are not associated directly with unit tests.

Tests
- [ ] cli_test.go
- [ ] deffile_test.go
- [ ] docker_test.go
- [ ] env_test.go
- [ ] help_test.go
- [ ] instance_test.go
- [ ] pull_test.go
- [ ] security_test.go

**Comment by dtrudg** [comment]
Don't believe this is relevant now as we should be moving to drop the integration tests which are now mostly duplicated in e2e... and then tidy up what is left as neccessary.
