### ISSUE TITLE
Add a build tag to all integration tests

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2449]
We are already making use of build tags so it seems like a good idea to add a build tag for our integration tests. It's possible this will not be used if/when tests are moved to a new directory but this seems like an easy first step to separate integration from unit tests.

Tests
- [ ] cli_test.go
- [ ] deffile_test.go
- [ ] docker_test.go
- [ ] env_test.go
- [ ] help_test.go
- [ ] instance_test.go
- [ ] pull_test.go
- [ ] security_test.go

**Comment by dtrudg** [comment]
The build tag is present in the files mentioned.
