### ISSUE TITLE
predefined environment variables cannot be override with SINGULARITYENV_

### ISSUE THREAD

**Issue by thdesy** [apptainer/singularity#2451]
## Version of Singularity:

```
Name        : singularity
Version     : 2.6.0
Release     : 1.1.el7
Architecture: x86_64
Install Date: 2018-11-16T14:41:23 CET
Group       : System Environment/Base
Size        : 649065
License     : BSD and LBNL BSD
Signature   : RSA/SHA256, 2018-08-07T21:01:24 CEST, Key ID 6a2faea2352c64e5
Source RPM  : singularity-2.6.0-1.1.el7.src.rpm
Build Date  : 2018-08-07T20:09:12 CEST
Build Host  : buildvm-11.phx2.fedoraproject.org
```

### Expected behavior

When adding envvars in the %environment section or in %post, these variables are set as presets via .singularity.d/env/9*-environment.sh.
Following
  https://singularity.lbl.gov/docs-environment-metadata
I assumed that such preset envvars can be overridden by exporting
  SINGULARITYENV_${PRESETENVVAR}="something-else"
and be available in the containers environment with their new value.

### Actual behavior

Preset environment variables are staying on their predefined value and are not updated dynamically with the value exported before starting the container.

'New' envvars, which are not predefined in the recipe, appear in the container env as expected with their externally set value.

### Steps to reproduce behavior

I tried both approaches: explicitly setting the envvars in the %environment section as well as in the %post section

[Singularity recipe snippets]
```
%environment
export SPARK_MASTER_URL="foo.baz.org"
export ...

%post
echo 'export SPARK_MASTER_URL=foo.baz.org' >>$SINGULARITY_ENVIRONMENT
```
[Singularity recipe snippets//]

[Exports in the build container] 
```
container.d/.singularity.d/env/90-environment.sh:export
SPARK_MASTER_URL="foo.baz.org"
container.d/.singularity.d/env/91-environment.sh:export
SPARK_MASTER_URL=foo.baz.org
```
[Exports in the build container//]

[Running the container//]
```
> export SINGULARITYENV_SPARK_MASTER_URL="somewhere.else"
> export SINGULARITYENV_NEWENVVAR="shiningnew"
> singularity shell [--contain --cleanenv]  container.d/
Singularity container.d:/> echo $SPARK_MASTER_URL 
foo.baz.org
Singularity spark-worker.d:/> echo $NEWENVVAR
shiningnew
```
[Running the container//]

**Comment by thdesy** [comment]
btw: for the moment I have dodged the issue by adding to the %post section a check if a SET_envvar has been set to override the internally defined envvar


```
%environment
export SPARK_MASTER_URL="foo.baz.org"

%post
...
echo 'export SPARK_MASTER_URL="foo.baz.org"' >>$SINGULARITY_ENVIRONMENT
echo 'export SPARK_MASTER_URL=$(if [ -z "${SET_SPARK_MASTER_URL}" ]; then echo ${SPARK_MASTER_URL}; else echo ${SET_SPARK_MASTER_URL}; fi)' >> $SINGULARITY_ENVIRONMENT
```

so set one can override the envvar from outside
`export SINGULARITYENV_SET_SPARK_MASTER_URL`

it's hard-coded at the moment but probably could be made more dynamic (checking/looping over all SET_ envvars)

**Comment by sveint** [comment]
This affects any converted Docker image using the `ENV` directive, which is quite common. Especially for defining default ports for software. Any such converted image is a pain to use with Singularity.

Is there a simple workaround for this?

**Comment by scalavision** [comment]
I am not sure it works to overload the variable if you use the export keyword:

 `export SPARK_MASTER_URL="foo.baz.org"`

You can see how they dealt with a similar(?) issue here:

https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/jfD57abWHoo

**Comment by sveint** [comment]
Found a solution. While I still think it's a design issue in Singularity and that env set with `SINGULARITYENV_` should be set after sourcing all the files from `.singularity/env/*`, this works as a workaround.

The simple solution is to set the variable in `%environment` like this:

```
%environment
export FOO=${FOO:-mydefault}
```

The reason this works is that envs from SINGULARITYENV_ is set before that file is sourced, so if anything is set beforehand that will be used, otherwise "mydefault" will be set.

#### Using docker
For this to work, you obviously need a Singularity file. So if you're basing off a docker image like in my case, you need to create a Singularity file basing of that image when converting the image.

If the environment variable is set using `ENV` in that image, it will end up in `.singularity.d/env/10-docker.sh`, which is sourced before the settings from `%environment`. But you can modify that file in `%post` like this:

```
%post

# Delete variable from being exported from docker.
# (or you can just delete the whole file and set them yourself in %environment)
sed -i '/MY_VARIABLE/d' /.singularity.d/env/10-docker.sh
```

You should probably make sure that only one variable is set per line from the Dockerfile, so you don't remove anything else.

**Comment by scalavision** [comment]
Nice solution! :-)

**Comment by thdesy** [comment]
ah, thanks - that looks good :)

I will try and see to replace my home-grown fiddly solution!

**Comment by dtrudg** [comment]
This is now the case in Singularity 3.x - the docker environment can be overridden.

In `/.singularity.d/env/10-docker2singularity.sh` things look like this:

```
export DOWNLOAD_DIR=${DOWNLOAD_DIR:-"/downloads"}
export CONDA_URL=${CONDA_URL:-"https://repo.continuum.io/miniconda/Miniconda3-4.3.30-Linux-x86_64.sh"}
export CONDA_MD5=${CONDA_MD5:-"= 0b80a152332a4ce5250f3c09589c7a81"}
export CONDA_PATH=${CONDA_PATH:-"/opt/miniconda"}
```
