### ISSUE TITLE
Challenges building singularity 3.0.0 - project.chk drops compiler/ldflags

### ISSUE THREAD

**Issue by jakirkham** [apptainer/singularity#2454]
## Version of Singularity:

3.0.0

### Expected behavior

C compiler and linker flags would be passed to the C compiler in `project.chk`.

### Actual behavior

These flags appear to be ignored/dropped instead.

### Steps to reproduce behavior

Set C compiler and linker flag environment variables and run the build. Note they are not included when the `project.chk` portion is run.

Please see [this patch]( https://github.com/conda-forge/singularity-feedstock/blob/0d6bcc2ebdd4c64c0823cfde0abf2d52bb2a7b51/recipe/0001-use-c-ldflags-during-mconfig ) for some further insight into the behavior.

**Comment by jakirkham** [comment]
Should add we have seen this issue with the generated `Makefile` as well.

**Comment by yhcote** [comment]
Just a note that the build system in place is not autotools. Makeit helps generating a non-recursive Makefile for the project but it's far from 20K lines of Perl ;-)

Can you give more details of your use case so that I can help you figure out the best way to solve your problem please?

Cheers!

**Comment by jakirkham** [comment]
Yep, we noticed that as well.

We have the environment variables `CFLAGS` and `LDFLAGS` populated with flags for the C compiler and the linker. We would like to use those environment variable directly in the build (e.g. having the generated `Makefile` use them) . If that's not possible, having some way to set the flags it uses for these tools based on these environment variables would also help.

In case you are interested, the build is happening in PR ( https://github.com/conda-forge/singularity-feedstock/pull/14 ).

Please let me know if you have questions.

**Comment by yhcote** [comment]
So, desired CFLAGS, LDFLAGS, etc, should be set in the mlocal/frags/
common_opts.mk. Those flags are added to all C files compiled as part of
the project.

Is this what you need?

Cheers,

 - Yannick

**Comment by jakirkham** [comment]
So do we need to edit that file? That would complicate matters a bit. The build is largely automated so this wouldn't exactly be trivial. We could always use `sed` to this effect if needed, but better suggestions would certainly be welcome. Please feel free to clarify in case I've misunderstood something.

**Comment by yhcote** [comment]
That's right editing the file is how you set up how the project should
build.

**Comment by jakirkham** [comment]
Would it be possible for them to defer to environment variables if they are set?

**Comment by dtrudg** [comment]
Looking at the singularity-feedstock repo it seems that this is being worked around.

I'm going to close this issue as it hasn't been updated for some time, but please feel free to re-open if there is still a strong need.
