### ISSUE TITLE
Shub reference regexp forces users to explicitly specify `shub://`

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#2460]
## Version of Singularity:

Any v3.0+, perhaps 2.0+ too.

### Expected behavior

Both `shub://registry/user-name/container-with-dash` and `registry/user-name/container-with-dash` are considered a valid shub references.

### Actual behavior

Second ref causes an error.

### Steps to reproduce behavior

Call shub.DownloadImage directly.

**Comment by ArangoGutierrez** [comment]
this issue makes reference to the func https://github.com/sylabs/singularity/blob/master/pkg/client/shub/util.go#L16

**Comment by dtrudg** [comment]
There's no real bug here that i can see. it's more tech-debt to handle the `xxx://` prefixes consistently across sources.
