### ISSUE TITLE
Parsing Header Logic

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#2464]
Heyo! 

I'm parsing the sif header [described here](https://github.com/sylabs/sif/blob/master/pkg/sif/sif.go#L27) and I've gotten through the global header:

```
boxes.simg is a SIF file.
Architecture: AMD64 arch code
Found SIF version 01
Found SIF arch 02
Found SIF uuid 0eae46df-1975-e44c-888b-8b9915f87f52
Found SIF ctime 1544537033
Found SIF mtime 1544537033
Found SIF ndescr 46
Found SIF descroff 48
Found SIF descrlen 4096
Found SIF dataoff 28080
Found SIF datalen 32768
```
and I'm wondering about the logic that next should be taken to parse each descriptor. Here are some things I'm trying based on the spec detailed above. I'll formulate these as questions that we can go through one by one:

## How do I find the next (first) descriptor block?
The arrow in the diagram implies that the number for descroff (description offset) should point to the start of the description block, so I might seek that many bytes. But it's also the case that we have:

```golang
DescrStartOffset  = 4096               // where descriptors start after global header
```
Should I start there instead (should these two numbers be the same thing?)

## How is the descriptor structured?
Given that I have seeked to the right spot in the open file, I'm now looking at the (what I think is) the structure for a descriptor. But looking at the picture again, it looks like each descriptor might have a name that comes first?

```
DescrEntityLen    = 256                // len("Joe Bloe <jbloe@gmail.com>...")
DescrNameLen      = 128                // descriptor name (string identifier)
```

So would I want to parse the next 128 bytes (after the offset from the global header) to find this descriptor name? And then the remaining 256 bytes (for a total of 354) is the entire block? Specifically, all of this?

```
// Descriptor represents the SIF descriptor type
type Descriptor struct {
	Datatype Datatype // informs of descriptor type
	Used     bool     // is the descriptor in use
	ID       uint32   // a unique id for this data object
	Groupid  uint32   // object group this data object is related to
	Link     uint32   // special link or relation to an id or group
	Fileoff  int64    // offset from start of image file
	Filelen  int64    // length of data in file
	Storelen int64    // length of data + alignment to store data in file

	Ctime int64                 // image creation time
	Mtime int64                 // last modification time
	UID   int64                 // system user owning the file
	Gid   int64                 // system group owning the file
	Name  [DescrNameLen]byte    // descriptor name (string identifier)
	Extra [DescrMaxPrivLen]byte // big enough for above extra data
}
```
Is there a specification (akin to how there is a variable for the length of the SIF_MAGIC and other header variables) that tell me what to expect for bytes for each, or advice about parsing? This is the first time I've worked directly with bytes (it's fun!) so any pointers would be greatly appreciated! I think once I get the hang of one of the blocks I should be good with the rest. Thanks much!

**Comment by yhcote** [comment]
Tools already exist to do that programmatically (pkg/sif) or on the command line with siftool (cmd/siftool)  at the sylabs/sif repo.

**Comment by vsoch** [comment]
Yeah!  I found the siftools and they are great! However, I want to parse the header without needing to have the user install anything from golang.  It’s quite a heavy extra dependency to need to install when it really isn’t needed it all, technically. Thanks in advance for your wisdom!

**Comment by vsoch** [comment]
Also it looks like Dtotal and Dfree are not shown in the top diagram / example?
```
	Dfree    int64 // # of unused data object descr.
	Dtotal   int64 // # of total available data object descr.
```

**Comment by vsoch** [comment]
Could you please help with the logic, and format string for a descriptor? For example:

 - parse global header
 - seek descoff bytes
 - use format string XXX to unpack

**Comment by bauerm97** [comment]
>However, I want to parse the header without needing to have the user install anything from golang.

So, might I ask what "user" you are talking about here? If you're distributing some package to users and want them to be able to inspect a SIF, you can just distribute a packaged binary of `siftool`. Golang is statically compiled, so no need to have them install Golang

**Comment by vsoch** [comment]
All of the sregistry tools are in python and it’s important to extract metadata.

It’s bad design to have to complicate the software by then trying to distribute a binary that likely will lead to bugs depending on the user OS. In that this is just parsing bytes, it’s perfectly reasonable and better for distribution to not add the extra dependency. I’m wondering why you can’t help me instead of spending time telling me to develop differently?

**Comment by vsoch** [comment]
@al3x609 you might want to weigh in here. It doesn't seem like we are going to get help :(

**Comment by bauerm97** [comment]
>I’m wondering why you can’t help me instead of spending time telling me to develop differently?

Well, the intention of my previous post was to try and better understand your use case so I can try to provide better and more specific help. By better understanding what you were looking to accomplish, I was hoping to be able to better understand why you do not want to use the available Golang tooling or why it does not fit your requirements.

**Comment by vsoch** [comment]
Ah ok! I need to extract header metadata for sregistry, and I need to read it from the header. This is in python. Good practice is not adding extra dependencies, so given that you can parse and unpack bytes in python, it comes down to just knowing the locations and format. The documentation that I'm trying to follow isn't enough information to let me do this, so I was asking for help.

This use case will also be important for general scientific users that can't (or don't want to) use a golang binary - for example they might want to include it in a pipeline (script) in python.

**Comment by al3x609** [comment]
Hello, I use Singularity for my work in HPC, version 3 brings important features to verify the integrity of the images and the developers that sign them, many commands that are sufficient in environments where the user has knowledge of how to deploy containers, execute services that they are inside them etc. But in my opinion with a DevOps / CI-CD perspective for microservices, all these technologies should be able to automate to a greater extent possible, which makes it necessary to use APIs, to deliver a personalized service to users with little knowledge, in this case [Spython](https://github.com/singularityhub/singularity-cli) and the local storage services that can be provided by [Sregistry](https://github.com/singularityhub/sregistry) or Sylabs cloud.

Given the above, there must be a way to integrate Singularity with other tools that allow encapsulating its operation for production environments, not only for programmers, but also for all kinds of researchers or scientists who require it.

and it is redundant, the signature of images is an excellent service for secure environments, and should be extended to several services, languages ​​and APIs. So develop tools on linux container technology. etc.

We do not seek to generate competition for Singularity, we seek to extend the great benefits that this delivery and facilitate life to users. 


We are looking for information for a better documentation of source code, and from this we start in future developments.

**Comment by vsoch** [comment]
Actually, I made good progress this morning without sylabs help, I know you guys are super busy so don’t want to misuse your time. I’ll ping again if I run into trouble. +1 everything said above!

**Comment by vsoch** [comment]
Also it looks like you have a ndescr in the example header --> https://github.com/sylabs/sif/blob/838fcf45c7628a0d057cc218db20b45eefdd33e5/pkg/sif/sif.go#L36

but it's not actually a field that is defined:

```
// Header describes a loaded SIF file
type Header struct {
	Launch [HdrLaunchLen]byte // #! shell execution line

	Magic   [HdrMagicLen]byte   // look for "SIF_MAGIC"
	Version [HdrVersionLen]byte // SIF version
	Arch    [HdrArchLen]byte    // arch the primary partition is built for
	ID      uuid.UUID           // image unique identifier

	Ctime int64 // image creation time
	Mtime int64 // last modification time

	Dfree    int64 // # of unused data object descr.
	Dtotal   int64 // # of total available data object descr.
	Descroff int64 // bytes into file where descs start
	Descrlen int64 // bytes used by all current descriptors
	Dataoff  int64 // bytes into file where data starts
	Datalen  int64 // bytes used by all data objects
}
```
Maybe it started that way, and was changed to Dfree and Dtotal?

**Comment by vsoch** [comment]
hey guys what is the logic to finding the start of the partition or signature block? There aren't any pointers (see diagram at the link above) that give hints. Can you give this dinosaur a hint? :)

**Comment by vsoch** [comment]
Hoo! I think I found it! So I just looked at every format string matching the expected from the start of the description offset to its entire length, and I looked for Datatype that are in the same scale as the first 
iota (I'm not sure what this is but I read that it's used like an incrementing unit, so we add some small unit each time, in this case it is initialized to 0x4001 which is 16385 (use [this thing](https://www.rapidtables.com/convert/number/hex-to-decimal.html))
```
# let's try to find based on iota increments
for o in range(0, self.meta['descrlen'] * 10):
    offset = self.meta['descroff'] + o
    filey.seek(offset)
    values = self.unpack_bytes(filey, self.Deffile.fmt)
    if int(values[0]/1000) == 16:
        print('offset %s, %s' %(offset, values))

```
Then from that I found this, and the second line is the data that I need to find! Specifically the offset in the file is the first number 4681:

```
offset 4096, (16385, True, 1, 4026531841, 0, 32768, 39, 39, 1544537033, 1544537033, 0, 0, 46, 0)
offset 4681, (16388, True, 2, 4026531841, 0, 36864, 196947968, 196952025, 1544537033, 1544537033, 0, 0, 1635086707, 1936091251)
```
So I know I'm looking for this offset, and I figured out that if I parse through the deffile, *before* I jump to the actual deffile content if I add space for the name and (whatever "extra" is) then I look at the file location (with filey.seek()) - it's at 4681! Then I can seek there, read the descriptor format:

```
        filey.seek(self.Partition.start)

        # see sif.header module for the default fields and format strings
        values = self.unpack_bytes(filey, self.Deffile.fmt)
         
        # Update the descriptors dictionary
        for d in range(len(values)):
            partition[self.Partition.fields[d]] = values[d]

        # Important: where are the fstype and partype? content? They are supposed to be here

        # Can we get a name (this seems wrong) !
        name = self.read_and_strip(filey, "%sc" % self.base.DescrNameLen)
        extra = self.read_and_strip(filey, '%sc' % self.base.DescrMaxPrivLen)
```

And that gets me most of what is there

```
{'Ctime': 1544537033,
 'Datatype': 16388,
 'Filelen': 196947968,
 'Fileoff': 36864,
 'Gid': 0,
 'Groupid': 4026531841,
 'ID': 2,
 'Link': 0,
 'Mtime': 1544537033,
 'Storelen': 196952025,
 'UID': 0,
 'Used': True,
 'extra': '\x01\x0202',
 'name': 'squashfs-955608129.img'}
```
 but I'm confused, where are the fields for fstype, partype, and content? See here https://github.com/sylabs/sif/blob/838fcf45c7628a0d057cc218db20b45eefdd33e5/pkg/sif/sif.go#L59 is that part of the Extra (since it doesn't parse nicely above) and it's just not clear in the docs? Should the squashfs that is being parsed into name be part of the fstype?

**Comment by vsoch** [comment]
okay, so I parsed the fstype and partype as part of extra, and then the remainder of extra is just the number of bytes allocated for it minus the bytes for two int 32 (format string 2i). This might be closer?

```
{'Ctime': 1544537033,
 'Datatype': 16388,
 'Filelen': 196947968,
 'Fileoff': 36864,
 'Gid': 0,
 'Groupid': 4026531841,
 'ID': 2,
 'Link': 0,
 'Mtime': 1544537033,
 'Storelen': 196952025,
 'UID': 0,
 'Used': True,
 'extra': '02',
 'fstype': 1,
 'name': 'squashfs-955608129.img',
 'partype': 2}
```
I'm still not sure what content is, or the correct order of operations.

**Comment by dtrudg** [comment]
Hi @vsoch - I'm going to close this as there was nothing added in a year. If you have additional SIF format issues that aren't runtime related, please could you open any follow-up on the SIF repo. Thanks.

**Comment by vsoch** [comment]
Thanks @dctrud ! I actually figured this all out, just forgot to update the issue. https://github.com/singularityhub/sif
