### ISSUE TITLE
failed in ./mconfig This host does not support the CLONE_NEWNS (mount) namespace flag!

### ISSUE THREAD

**Issue by pheman** [apptainer/singularity#2485]
## Version of Singularity:
singularity version 3.0.0-115.g8b3d5c2

### Expected behavior

pass ./mconfig successfully

### Actual behavior

failed with
"This host does not support the CLONE_NEWNS (mount) namespace flag! You
really really really don't want to run Singularity containers without a
Separate mount name namespace!"

### Steps to reproduce behavior

OS: CentOS Linux release 7.2.1511 (Core)  3.10.0-327.el7.x86_64
 and if any more information is needed, please let me know

**Comment by bauerm97** [comment]
Hi, can you paste the entire output of `./mconfig` here so we can take a look? Also, did the singularity `2.x` series compile on your system?

**Comment by dtrudg** [comment]
Closing - there was no followup, and I'm not aware of any issue building current singularity on CentOS 7.

**Comment by kaczmarj** [comment]
For any wanderers into this thread, I ran into the issue

```
=> running post-basechecks project specific checks ...
 checking: namespace: CLONE_NEWPID... no
 checking: namespace: CLONE_FS... no
 checking: namespace: CLONE_NEWNS... no

This host does not support the CLONE_NEWNS (mount) namespace flag! You
really really really don't want to run Singularity containers without a
Separate mount name namespace!
```

when trying to build singularity 3.6.0. I resolved the issue by installing the dependencies as listed in https://sylabs.io/guides/3.6/admin-guide/admin_quickstart.html#install-dependencies.

```
sudo apt-get update && sudo apt-get install -y \
    build-essential \
    uuid-dev \
    libgpgme-dev \
    squashfs-tools \
    libseccomp-dev \
    wget \
    pkg-config \
    git \
    cryptsetup-bin
```
