### ISSUE TITLE
Singularity currently is not supported in Github Actions

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2487]
`Github Actions` is a new method to automate your workflows on Github itself (https://github.com/features/actions).

Currently, there are some issues with included capabilities that block the creation of Singularity containers. See the following twitter thread:

https://twitter.com/vsoch/status/1072588623810322432

As this is a new feature and we are actively working on it we will update this issue.

**Comment by vsoch** [comment]
Here is the workflow that I used that got closest - the repo has a Singularity recipe named Singularity at the root:

```
workflow "Build Only" {
  on = "push"
  resolves = "Build"
}

action "Build" {
  uses = "singularityhub/actions/build@master"
  env = {
    SINGULARITY_RECIPE = "Singularity"
  }
}
```

**Comment by vsoch** [comment]
Containers are built from here --> https://github.com/singularityhub/singularity-docker
Deployed to --> https://hub.docker.com/r/singularityware/singularity

**Comment by dtrudg** [comment]
This has been tackled as a separate project in the community. See above.

**Comment by vsoch** [comment]
This is not entirely correct, the repository exists but there are non-trivial issues that prevented it from working, see this thread. https://twitter.com/vsoch/status/1072588623810322432. I don't think the "community" (cough, me) is empowered to get this working, so although there isn't much Sylabs can do atm, I think the issue should be left open to reflect this state.

**Comment by dtrudg** [comment]
As in twitter thread mentioned by @vsoch above this is not possible as GitHub actions environment is very locked down and doesn't allow capabilities Singularity requires to run containers in a reasonable manner.

Marking wontfix so it's clear to others this isn't being pursued at present.
