### ISSUE TITLE
backward compatibility with singularity 2.4?

### ISSUE THREAD

**Issue by Phylloxera** [apptainer/singularity#2490]
## Version of Singularity:

Image created - version 3.0; Singularity exec run successfully on image - version 3.0; Singularity exec returned  "ERROR: Unknown image format/type:" - version 2.4. Guessing not backward compatible between singularity versions and that I either need to use 2.4 to create my images or ask our sysadmin to upgrade singularity on the server. Is that right?

**Comment by jmstover** [comment]
@ikaneshiro ... I thought the 2.4 format was caught yes? Or was it only the 2.5+ format? Pretty sure it's a squashfs image. Header looks right anyway.

@Phylloxera ... What point version of 2.4 are you using?

**Comment by Phylloxera** [comment]
`singularity --version `gives 2.4-dist. Do I need a different command?

**Comment by jmstover** [comment]
Hrmm... Then that looks to be:  2.4.0

I was able to create an image with 2.4.0 and shell into it, and `run`, with 3.0.0 and 3.0.1. I used `docker://godlovedc/lolcow` as my test.

**Comment by jmstover** [comment]
Oh wait ... I think I read this backwards... Did you create an image with 3.0 and try to run with 2.4? 

If that is the case, that will not work. The image format in 3.0 is different from earlier versions.

**Comment by Phylloxera** [comment]
Yes that is right. Thanks for the info.

**Comment by GodloveD** [comment]
Yeah @Phylloxera, as @jmstover indicates, an image built with a newer version of Singularity will not run on an older version of Singularity.  The reverse is supported (older images on newer versions), but there is really no way to ensure that a newer image will work with an older version unless we freeze development on the image format and never add any new features or improvements.

**Comment by armaneshaghi** [comment]
Would there be a way to create images with new versions to run with previous versions? I understand the reasoning for this change, however, could there with a flag that will force the newer versions to produce older-compatible images?

**Comment by GodloveD** [comment]
I just tested this with 3.2.0 and 2.4.0 and it seems to work.  Basically, you can build using the `--sandbox` flag in a newer version of Singularity and that will run in the older version.  If you really want to you can also build a squashfs or ext3 in the older version of Singularity from the sandbox.  I think this functionality was added in 2.4.  You may be able to run sandboxes in even older versions of Singularity, but I don't think you can convert the sandboxes to images.  

EDIT:
That said, I'm not sure how far that will extend.  For instance the way that metadata and driver scripts were handled in older versions of Singularity was different.  So you might not get the environment you expect and things like `singularity run` might now do the right thing.
