### ISSUE TITLE
Signing package prompts user input while it should not

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#2491]
## Version of Singularity:

3.0

### Expected behavior

Public package should return an error, and CLI wrapper should handle it and ask for user input.

### Actual behavior

Public package asks for input itself.

**Comment by cclerget** [comment]
As discussed @sashayakovtseva that could be easily avoided by adding a parameter in `Verify` : https://github.com/sylabs/singularity/blob/d214553f33592ff998db71e0ed93e94c6c18a1ff/pkg/signing/signing.go#L268, to control if public key should be stored automatically or with user permission via interactive question on CLI
