### ISSUE TITLE
RPM build for 3.0.2 Release Candidate 2 fails

### ISSUE THREAD

**Issue by hearnsj** [apptainer/singularity#2497]
## Version of Singularity:

Write here.

### Expected behavior

Write here.

### Actual behavior

Write here.

### Steps to reproduce behavior

Write here.

**Comment by hearnsj** [comment]
Version of Singularity:
3.0.2

Expected behavior
Build of the RPM on Fedora 29 system creates an RPM

Actual behavior
The build script fails with the output below.
I am not sure if this is a real issue or I am doign something stuid, since the RPM build for previous versions works fine for me.


+ cd /home/hearnsj/rpmbuild/BUILD/singularity-3.0.2/gopath/src/github.com/sylabs/singularity
+ ./mconfig -V 3.0.2-rc2.fc29 --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --libexecdir=/usr/libexec --sysconfdir=/etc --sharedstatedir=/var/lib --localstatedir=/var --libdir=/usr/lib64
/var/tmp/rpm-tmp.XiPrKR: line 45: ./mconfig: No such file or directory
+ cd builddir
/var/tmp/rpm-tmp.XiPrKR: line 50: cd: builddir: No such file or directory
+ make
make: *** No targets specified and no makefile found.  Stop.
+ exit 2

The directory /home/hearnsj/rpmbuild/BUILD/singularity-3.0.2/gopath/src/github.com/sylabs/singularity
contains only 
singularity.spec  VERSION



Steps to reproduce behavior
Write here.

 tar zxvf  ~/Downloads/singularity-3.0.2.tar.gz 
 cd singularity/
 ./mconfig 
 make -C builddir/  rpm

**Comment by jmstover** [comment]
@hearnsj 
Hrmm... What do you get if you run:   `rpmbuild -tb ~/Downloads/singularity-3.0.2.tar.gz` 

I think the reason it's off on yours is that when you run `make -C builddir/ rpm` ... it runs `make dist` ...  The `make-dist.sh` script uses `git ls-files` for the files to include, but the release tar ball is *not* a git structure.

In other words... `make rpm` works if you're in a Git clone, but if you have a release tar ball you're better off running:  `rpmbuild -tb [tar.gz file]`

**Comment by tbugfinder** [comment]
I have the same issue using v3.1.1.

**Comment by tbugfinder** [comment]
```
# rpmbuild -tb ./singularity-3.1.1.tar.gz
error: Failed to read spec file from ./singularity-3.1.1.tar.gz
```

**Comment by tbugfinder** [comment]
Indeed building it from source `git checkout tags/v3.1.1` is ok.

**Comment by dtrudg** [comment]
I don't have an issue with current archives, so closing this. Please let us know if you hit any problems.
