### ISSUE TITLE
envar leaks memory

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#250]
The envar function mallocs some space every time it returns a non-NULL value, and nothing is freeing that memory.

**Comment by gmkurtzer** [comment]
I am assuming it is from the call to malloc here:

```
ret = (char *) malloc(len+1);
```

But I am returning a pointer to that string, so it is kinda necessary to keep that memory allocated.

Perhaps, it is not being properly freed by the calling functions... I will check into that, but if you have more specifics of what you are thinking of please let me know.

Thanks!

**Comment by DrDaveD** [comment]
Yes, that's my point, that I didn't see any calling functions doing a free on that value.  That becomes quite tricky to enforce.

**Comment by DrDaveD** [comment]
The best solution might be to require the calling function to allocate space and pass it in.

**Comment by gmkurtzer** [comment]
I think you are right but I am concerned about changing it in the 2.2 release. I would prefer to wait until 2.2.1 or 2.3 unless you feel strongly that this is critical?

**Comment by DrDaveD** [comment]
No it might not be critical.  There might not be a significant amount of memory leaked.

**Comment by gmkurtzer** [comment]
I would tend to agree, the memory leak is pretty minor and I will do some cleanups within the calling code for now but this should be reworked in later versions.

Thanks!

**Comment by gmkurtzer** [comment]
Memory leaks should be fixed in [master 6f9d0d5] but I am leaving this open for a bigger change; to let the calling function do the malloc and pass pointer to envar*().

**Comment by DrDaveD** [comment]
Another possibility is to actually modify the environment when you sanitize it, rather than sanitizing a copy of it.  You're not changing the length of anything, just the contents, and I don't see the harm.  If you did that you'd have to undo 6f9d0d5.

**Comment by gmkurtzer** [comment]
Added to 2.3 release milestone so it gets attention before releasing.

**Comment by GodloveD** [comment]
@gmkurtzer and @DrDaveD any idea where this stands?

**Comment by gmkurtzer** [comment]
This is some pretty old code being referenced here so gonna close. Thanks @GodloveD!

**Comment by DrDaveD** [comment]
It looks like the comment still applies, but to envar_get() now.  It's not used very often at this point so the leak is probably pretty small.  But who knows if maybe it will be used more in the future (for example if #887 is implemented); it's not a very robust design.
