### ISSUE TITLE
Already mounted issues

### ISSUE THREAD

**Issue by cclerget** [apptainer/singularity#2506]
## Version of Singularity:

V3

### Expected behavior

```
singularity exec -H /tmp/home -B /tmp/testing:/tmp/home/testing image ls -la /tmp/home/testing/file
```

Able to get file as expected

### Actual behavior

```
singularity exec -H /tmp/home -B /tmp/testing:/tmp/home/testing image ls -la /tmp/home/testing/file
```

file is not present because Singularity considers `/tmp/home` as already mounted so bind mount point is ignored.

### Steps to reproduce behavior

```
mkdir -p /tmp/home/testing
mkdir /tmp/testing
touch /tmp/testing/file
singularity exec -H /tmp/home -B /tmp/testing:/tmp/home/testing image ls -la /tmp/home/testing/file
```

**Comment by ghuls** [comment]
@cclerget Does you patch allow the following:
`singularity exec -c -H /fake/home:/real/home -B /real/home/.ssh:/fake/home/.ssh image ls -ls`

**Comment by cclerget** [comment]
@ghuls it should work if `/fake/home/.ssh` exists because Singularity won't create it
