### ISSUE TITLE
build from a locally registered docker container fails

### ISSUE THREAD

**Issue by agilly** [apptainer/singularity#2507]
## Version of Singularity:

3.0.1
3.0.2-rc2

### Expected behavior

Build from local docker registry succeeds as in v. 2.6.1.

### Actual behavior

Attempting to build from a locally registered docker container gives the following:

```
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: Invalid image source: invalid reference format
```

### Steps to reproduce behavior

build docker image and register it locally:

```
touch dockerfile ## ... and write in it
docker build -t test .
docker run -d -p 5000:5000 --restart=always --name registry registry:2
docker tag test localhost:5000/test
docker push localhost:5000/test
```

create def file:

```
Bootstrap: docker
Registry: http://localhost:5000
Namespace:
From: test:latest
```

In 2.6.1 this works:
```
sudo SINGULARITY_NOHTTPS=1 /opt/singularity/bin/singularity build --writable test.simg def
```

In >3.0.0 this fails:

```
sudo SINGULARITY_NOHTTPS=1 /opt/singularity/bin/singularity -v build --sandbox test.simg def
```

I also tried various combinations of arguments such as:

```
sudo /opt/singularity/bin/singularity -v build --nohttps --sandbox test.simg def
```

with the same result.

**Comment by dtrudg** [comment]
Hi @agilly - it looks like the parsing in the libraries now used from Singularity for docker handling expect that the `Registry:` value is given without the `http://` prefix, just `localhost:5000`. Perhaps if it exists it could be stripped off to maintain compatibility with 2.x def files though(?)

Also, the separate `Registry` tag in the def file isn't absolutely needed now. You could have a `From: localhost:5000/test:latest` 

This functionality is tested over here to pull from registries, where the `Registry:` without `http://` prefix is used:

https://github.com/sylabs/singularity/blob/af5b7b2a431ae5880bcfee92cefe5b5db30726a5/cmd/singularity/docker_test.go#L233

**Comment by agilly** [comment]
Thank you for this answer. I agree that it would be better to preserve reverse compatibility with 2.x. I have now downgraded to 2.6 and some users are running containers, but as soon as it clears out I will try reinstalling 3.0 and check if this works.

**Comment by agilly** [comment]
So I tested it today after upgrading to 3.0.3 and it works.
