### ISSUE TITLE
Multistage Builds

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#2518]
This will involve allowing multiple bootstrap headers to exist within a single definition file. Each header and subsequent sections generate a `bundle` with contents that we can copy to a later stage during the build process.

This will require adding information to definitions to identify stages and copy files from them. Currently considering adding:
- `Stage: <stageName>` to identify each stage in its header
- `%files from <stageName>` section to copy files from specific stage to current container

**Comment by dtrudg** [comment]
Can't upvote this enough :+1: :-)

**Comment by ikaneshiro** [comment]
Implemented by #3156
