### ISSUE TITLE
SINGULARITY_DISABLE_CACHE is not a thing in 3.0

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2519]
## Version of Singularity:

3.0.1

### Expected behavior

```
$ export SINGULARITY_DISABLE_CACHE=1
$ singularity build blah.sif docker://busybox
[...snip...]
$ ls -l ~/.singularity/cache/oci/blobs/sha256/
total 0
```
### Actual behavior

```
$ export SINGULARITY_DISABLE_CACHE=1
$ singularity build blah.sif docker://busybox
[...snip...]
$ ls -l ~/.singularity/cache/oci/blobs/sha256/
total 748
-rw-r--r-- 1 vagrant vagrant 755724 Jan  4 18:29 57c14dd66db0390dbf6da578421c077f6de8e88edd0815b4caa94607ba5f4c09
-rw-r--r-- 1 vagrant vagrant    347 Jan  4 18:36 8d7f536d20a5503e6bf967b88c6ea4f2a0a4fac8739f4e88f577531bf5300e66
-rw-r--r-- 1 vagrant vagrant    575 Jan  4 18:36 9bf7f625d0785fbcd9e2d07695e22485360d37a83164fc12832d06b7db27da53
```

This was brought to my attention in DM on Slack by @0xaf1f.

**Comment by 0xaf1f** [comment]
I thought the old docs said it had to be set to yes or True, but that didn't work either when I tried it.

**Comment by GodloveD** [comment]
I grepped the code.  It just doesn't exit in 3.0.  It's an oversight.

**Comment by 0xaf1f** [comment]
Ok, but I was talking about the expected behavior: whether it was expected to work if defined to anything or those two particular strings. I don't know how the older versions behaved.
