### ISSUE TITLE
[docker] watch search api and add to singularity when ready

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#252]
This issue is a migration from singularityware/singularity [to be deleted]

We would want to be able to do a docker shell, and interactively query/search for possible images without needing the Docker daemon. Right now it looks like v2 of the registry doesn't have this fully working, and the v2/_catalog endpoint is usually not available to the user.

**Comment by gmkurtzer** [comment]
This did work for a while, but I don't think it is working anymore in the development branch. Can you take a look @vsoch? Thanks!

**Comment by vsoch** [comment]
I'll check this out again, the last time I looked the endpoint wasn't available (and it never worked in any of our versions). Maybe you are thinking of the bash completion thing?

**Comment by GodloveD** [comment]
@gmkurtzer and @vsoch what's up with this?  Is it still a thing?

**Comment by vsoch** [comment]
good question, let me check it out.

**Comment by vsoch** [comment]
ok, so the catalog is well developed, but permissions to it depend on the registry. I tried docker v2 with my credential, and it doesn't seem to give it to me (so I'm guessing the average user doesn't have it). I don't think we have need to try and extract all docker layers, so I am ok to close this.
