### ISSUE TITLE
isolation network connect to internet

### ISSUE THREAD

**Issue by ryzenX** [apptainer/singularity#2522]
## Version of Singularity:

3.0.2

Hello i'm want to run singularity instance with network isolation (with diffrent ip link that host machine)
In singularity 3.0.2 i can use net option for this.

After this inside my container i have new "network card" and new IP
But i want that my singularity container have access to network host (and internet)

i run singularity instance with this command :
singularity run --containall --net --network bridge alpine.img

i try this ptp,bridge or ipvlan, i have same problem

What changes do I need to make to make it work ?
Or what network should I create in /usr/local/etc/singularity/network ?

thnaks for advance for your help

**Comment by tkuehn1** [comment]
I have the same Problem like you. And there is also a discussion in the Google Group. https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/dtXBzfORF4E

**Comment by kav2k** [comment]
This feature was added in PR https://github.com/sylabs/singularity/pull/2400

```
singularity run --containall --net --network none alpine.img
```

However, since this changes the CLI the devs decided to to include it in 3.0.x releases. It should become available in 3.1.x

Question remains if it's possible to emulate with a CNI config.

**Comment by cclerget** [comment]
Hi @ryzenX, @tkuehn1, @kav2k , since Singularity bind `/etc/resolv.conf` from host into container, if you have dnsmasq or another DNS cache solution, `/etc/resolv.conf` probably point to localhost DNS, that's why once in container all DNS lookup try to reach your localhost DNS cache which isn't reachable from container, in this case you have to specify `--dns=8.8.8.8` on command line or any DNS ip separated by commas

**Comment by tkuehn1** [comment]
that works for me many thanks

**Comment by cclerget** [comment]
Closing issue, feel free to re-open it if needed

**Comment by ryzenX** [comment]
thanks it's work !

**Comment by ryzenX** [comment]
i run container like this :
singularity run --net --dns=8.8.8.8 myimage.img

it's work on my vbox vm but in real pc it's not work, i try to use my real dns :
cat /etc/resolv.conf 

my dns is 192.168.1.1
i try with this :
singularity run --net --dns=192.168.1.1 myimage.img
but it's not work, i have no internet connection
