### ISSUE TITLE
OCI Engine Testing

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2527]
* Discuss and review current test coverage
* Discuss and review OCI run-time test coverage (https://github.com/opencontainers/runtime-tools)
* Discuss and review current CI practice
* Discuss and document changes needed, if any.

**Comment by gvallee** [comment]
I improved the coverage from a unit test point of view. Count me in if we decide to improve the way we do testing for OCI, the situation is far from perfect even if the coverage through unit tests is now fairly good.
