### ISSUE TITLE
MacOS Platform Testing

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2528]
* Discuss and review availability, costs, and work needed to build on MacOS on TravisCI.
* Discuss and review availability, costs, and work needed to build on MacOS on CircleCI.
* Discuss and review test coverage for MacOS features.
* Discuss and document changes needed, if any.

See also: #2279

**Comment by jscook2345** [comment]
This looks to just be a given for both Travis and CircleCI. 
* No cost.
* Available immediately.
* Some work needed on configurations for CI tools.

Travis has a MacOS VM (os: osx) where you can choose the image based on XCode version (osx_image: xcode10.1), which is associated with the MacOS version.

Example:
<pre>
os: osx
osx_image: xcode10.1
</pre>

See also: https://docs.travis-ci.com/user/reference/osx/#macos-version

Circle similarly has a MacOS VM where you can choose the image based on the XCode version, which is associated with the MacOS version.

Example:
<pre>
jobs:
  job_name:
    macos:
      macos: "10.1.0"
    steps:
      ...
</pre>

See also: https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions

I will work on Travis first since it's needed some refactoring based on changes to Travis over time.

**Comment by jscook2345** [comment]
As far as versions tested, I think we'll do something like the last 3 available versions of MacOS.

For now that would include Sierra, High Sierra, and Mojave. From there I will just pick one version of XCode (maybe the latest?) to test with.

@mikegray Agrees with this assessment.

**Comment by ArangoGutierrez** [comment]
https://github.com/sylabs/singularity/pull/2627
