### ISSUE TITLE
[docker] test ways to not need root

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#253]
This issue is a migration from singularityware/singularity [to be deleted]

@chrisfilo had an idea to somehow "tar.gz the entire docker image (and then not need root)" and this could be further thought out, so possibly some day we can create singularity images from docker without needing it - or minimally having a base OS template (created using root) that another image can be bootstrapped into (without root)

**Comment by gmkurtzer** [comment]
Closing old tickets.
