### ISSUE TITLE
Bind mounts in singularity.conf not loading

### ISSUE THREAD

**Issue by omenos** [apptainer/singularity#2530]
## Version of Singularity:

3.0.2

### Expected behavior

Bind mounts specified in `/etc/singularity/singularity.conf` should be bound to specified directories in the container.

### Actual behavior

They are not.

### Steps to reproduce behavior

* Add specific bind points in the `singularity.conf` file like so:

```text
bind path = /etc/localtime
bind path = /etc/hosts
bind path = /scratch
bind path = /shared
```
* Make files/directories exist in container.
* Run the container (`exec` or `shell` for simplicity).
* `ls` the directories that should be bind mounted.

This functionality has been tested and works in 3.0.1. This is a regression in the latest patch release.

**Comment by truatpasteurdotfr** [comment]
confirming the issue on self rebuild 3.0.1 VS 3.0.2 tarball on CentOS-7 host.
```
BootStrap: docker
From: alpine

%post
mkdir -p /c7/shared 
```
```
$ grep c7/shared /etc/singularity/singularity.conf 
bind path = /c7/shared

$ singularity build alpine.simg alpine.def
$ singularity exec alpine.simg df /c7/shared
```
`df` does not show the same output with 3.0.2 than 3.0.1

**Comment by cclerget** [comment]
Hi @omento @truatpasteurdotfr, there is a regression introduced in 3.0.2, fixed by #2531

**Comment by omenos** [comment]
Thanks! Could I build this PR as an RPM by just copying the release spec file into the tar ball and running the build?

**Comment by jmstover** [comment]
@omento -- You should need to do:

```
git clone https://github.com/sylabs/singularity
cd singularity
git fetch --all
git fetch pull/2531/head:PR2531
git checkout PR2531
./mconfig
make -C builddir/ dist
rpmbuild -tb singularity-3.0.2.tar.gz
```

That _should_ build a RPM from the PR source.

**Comment by omenos** [comment]
I'll give that a go. I just tried manually adding the files after doing:

```
git clone git@github.com:sylabs/singularity.git
cd singularity
git checkout release-3.0
... add files ...
... copy spec file ...
cd ..
... tar folder ...
rpmbuild -tb singularity-3.0.2-2.tar.gz
```
And this fix didn't take. I'll report the results of your directions.

**Comment by omenos** [comment]
Can't make the pull.

```
ssh: Could not resolve hostname pull/2531/head: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by truatpasteurdotfr** [comment]
quick and dirty from the original sources and the 2 lines patch
[singularity-2530.patch.txt](https://github.com/sylabs/singularity/files/2741899/singularity-2530.patch.txt) in your SOURCES/ folder
[singularity-2530.spec.txt](https://github.com/sylabs/singularity/files/2741901/singularity-2530.spec.txt) in your SPECS/ folder 
and rpmbuild -ba singularity-2530.spec.txt

**Comment by omenos** [comment]
Seeing your patches right after doing it manually @truatpasteurdotfr :ok_hand: 

Can confirm this PR works against base 3.0.2. Maybe worth releasing a 3.0.3 to rectify what might be considered an administrative feature?
