### ISSUE TITLE
singularity build removes important host files when clearing /tmp

### ISSUE THREAD

**Issue by kaczmarj** [apptainer/singularity#2538]
## Version of Singularity:

singularity version 3.0.2

### Expected behavior

`singularity build` should not delete important host files like `/dev/null` if I execute `rm -rf /tmp/*` in the `%post` section of the Singularity recipe.

### Actual behavior

`singularity build` deletes important host files like `/dev/null` if I execute `rm -rf /tmp/*` in the `%post` section of the Singularity recipe. It seems to attempt to delete other important things in `/dev` of the host.

### Steps to reproduce behavior

Singularity recipe:

```
Bootstrap: docker
From: alpine:3.7
%post
rm -rf /tmp/*
```

```bash
$ sudo singularity build image.sif Singularity
```

I get output like this:

```
sudo singularity build image.sif Singularity
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:407ea412d82cbc18a270f0ae17d5e528e620bcf4661229e757446f6e6443768b
Copying config sha256:61e21b315b8111a738ee452c13866e071d841ba459d99cbe29b0b333eb175af1
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Running post scriptlet
+ rm -rf /tmp/sbuild-369911325 /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-ModemManager.service-ORVQR8 /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-bolt.service-6O6BvL /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-colord.service-R3B1lT /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-fwupd.service-SVNN1o /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-rtkit-daemon.service-k86r8n /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-systemd-timesyncd.service-F7P33T /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-upower.service-7koMvJ /tmp/tracker-extract-files.1000
rm: can't remove '/tmp/sbuild-369911325/fs/tmp': Resource busy
rm: can't remove '/tmp/sbuild-369911325/fs/etc/resolv.conf': Resource busy
rm: can't remove '/tmp/sbuild-369911325/fs/etc/hosts': Resource busy
rm: can't remove '/tmp/sbuild-369911325/fs/etc': Directory not empty
rm: can't remove '/tmp/sbuild-369911325/fs/proc/fb': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/fs/ext4/nvme0n1p8/options': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/fs/ext4/nvme0n1p8/mb_groups': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/fs/ext4/nvme0n1p8/es_shrinker_info': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/fs/ext4/nvme0n1p8': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/fs/ext4': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/fs/jbd2/nvme0n1p8-8/info': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/fs/jbd2/nvme0n1p8-8': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/fs/jbd2': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/fs/nfsd': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/fs': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/bus/pci/00/00.0': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/bus/pci/00/02.0': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/bus/pci/00/04.0': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/bus/pci/00/14.0': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/bus/pci/00/14.2': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/bus/pci/00/15.0': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/bus/pci/00/15.1': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/bus/pci/00/16.0': Operation not permitted
rm: can't remove '/tmp/sbuild-369911325/fs/proc/bus/pci/00/1c.0': Operation not permitted
```

This seems to be the same issue as #2509.

It's apparent that singularity binds some important host directories to `/tmp`. Maybe that default should be changed? I feel like I should be able to clear `/tmp` without affecting my host. Is that a reasonable assumption?

I have to restart my computer after these builds because some shell functions stop working or the display shuts off...

**Comment by kaczmarj** [comment]
If I set `SINGULARITY_TMPDIR` to something not in `/tmp`, then the build succeeds:

```bash
sudo SINGULARITY_TMPDIR=~/tmp singularity build image.sif Singularity
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:407ea412d82cbc18a270f0ae17d5e528e620bcf4661229e757446f6e6443768b
Copying config sha256:61e21b315b8111a738ee452c13866e071d841ba459d99cbe29b0b333eb175af1
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Running post scriptlet
+ rm -rf /tmp/sbuild-369911325 /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-ModemManager.service-ORVQR8 /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-bolt.service-6O6BvL /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-colord.service-R3B1lT /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-fwupd.service-SVNN1o /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-rtkit-daemon.service-k86r8n /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-systemd-timesyncd.service-F7P33T /tmp/systemd-private-143d2876231849bcbcf2956df323dae7-upower.service-7koMvJ /tmp/tracker-extract-files.1000
INFO:    Creating SIF file...
INFO:    Build complete: image.sif
```

**Comment by jmstover** [comment]
Hi @kaczmarj 

  This is actually expected behavior. When you're building from a definition file, the `%post` is going to go through the normal container run behavior, but using the root you're building.

  That includes bringing in the standard bind mounts.

  Since we, by default, build images in `/tmp`, and the host `/tmp` is bind mounted into the container as `/tmp` ... when you do:  `rm -rf /tmp/*` ... you are saying to delete your host `/tmp` and everything in it. In this case that _also_ includes the image build directory where we have bind mounts (which you can see from the container, since you're in that mount namespace).

  So, this is actually doing exactly what you're asking it to. Things like `/dev`, etc... cannot be mounted read-only because you must be able to write to devices to be able to use them.

  Assume that we were able to protect device and everything by making them unusable, you would still be deleting the container structure you've just built. So ... you wouldn't have a valid structure to have a usable container. This is why using `SINGULARITY_TMPDIR` works, you're changing the location of the build, but with the `rm -rf /tmp/*` you are still deleting everything on your Host `/tmp`. You are just not deleting where you are building the image anymore.

  What is it that you're trying to accomplish? There may be a different section that would better fit what it is you're trying to do.

**Comment by kaczmarj** [comment]
Hi @jmstover - thank you for your detailed response. This information is very helpful. I was simply trying to remove unnecessary artifacts in `/tmp`. Instead of using `rm -rf /tmp/*`, I have opted to remove specific files/directories in `/tmp` or to set `TMPDIR` to some new folder within `/tmp` and delete that when I am done. Thank you again!
