### ISSUE TITLE
CFLAGS in mlocal/checks/

### ISSUE THREAD

**Issue by A33a** [apptainer/singularity#2543]
## Version of Singularity:

3.0.2

### Expected behavior

1. Use existing installation of libraries (which are not in default searching path) to compile Singularity.
2. Pass all checks. 

### Actual behavior

Doesn't find `uuid` library in `mlocal/checks/project.chk`. Exits with an error:
```
unable to find the libuuid, need package libuuid-devel (uuid-dev on Debian/Ubuntu)
```

### Steps to reproduce behavior

1. Append CFLAGS at `mlocal/frags/common_opts.mk` with path containing `uuid` libraries and headers.
2. Run `./mconfig`

### Additional information

In some cases additional libraries are not located in the default search paths, in these scenarios it makes sense to compile programs with compiler flags to indicate where additional libraries and include files are. Adding CFLAGS to `mlocal/frags/common_opts.mk` file leads to successful compilation (wich checkers disabled). However, the checkers fail to pass the tests since they don't compile the tests with those flags. 

Maybe I am adding CFLAGS not in a proper place. If it is a case, can you please tell me where I should specify the flags for compilers?

**Comment by cclerget** [comment]
Hi @A33a , what's CFLAGS looks like ? Between CFLAGS is a part of problem (only for check), since most of dependencies are required by Go, you will have to set `CGO_CFLAGS` for compilation

**Comment by A33a** [comment]
Hi @cclerget, thank you for your response. 

We are using CFLAGS to include some libraries, which are not in the default search path, like `e2fsprogs-1.44.5/include` and `e2fsprogs-1.44.5/lib`. So is `CGO_CFLAGS` should be set in `mlocal/frags/common_opts.mk`?

**Comment by jscook2345** [comment]
@A33a @cclerget 

It looks like the checks under `mlocal/checks/project-post.chk` don't use `CFLAGS` when running a check for a library (in this case UUID).

We will discuss how best to address this issue.

**Comment by A33a** [comment]
@jscook2345 
> It looks like the checks under mlocal/checks/project-post.chk don't use CFLAGS when running a check 

Yes, exactly. That problem will not be relevant for us soon, since we will install UUID library as a part of planned software update, but in general, some libraries might be installed in a shared filesystem and in that case compiler and linker flags might be necessary. Thanks!
