### ISSUE TITLE
Incorrect Error with Explicit Token Flag

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#2545]
Issue reported by @renefritze - thank you René!

## Version of Singularity:

3.0.2

### Expected behavior

When an invalid token is specified via `-t <file>`, the reason it is invalid should be reported:

```sh
$ echo "bad token" > ~/token
$ singularity -t ~/token push file.sif sylabs-adam/default/blah
FATAL:   Couldn't push image to library: Token is too short to be valid
```

### Actual behavior

The error reported depends on the contents of `~/.singularity/sylabs-token`. So, for example, if a bad token is specified explicitly, and `~/.singularity/sylabs-token` does not exist:

```sh
$ echo "bad token" > ~/token
$ singularity -t ~/token push test.sif sylabs-adam/default/test
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Couldn't push image to library: Authentication token file not found
```

If the same bad token is placed in `~/.singularity/sylabs-token`, the error is different:

```sh
$ echo "bad token" > ~/.singularity/sylabs-token
$ singularity -t ~/token push test.sif sylabs-adam/default/test
FATAL:   Couldn't push image to library: Token is too short to be valid
```

### Steps to reproduce behavior

As above.

### Discussion

The bug appears to be in [sylabsToken()](https://github.com/sylabs/singularity/blob/v3.0.2/cmd/singularity/cli/singularity.go#L172). When a non-default file path is used, the
`tokenFile != defaultTokenFile` case is hit and `authWarning` is
set to specify the file is too short. The `authToken == ""` case is then hit, and `authWarning` is overwritten with information describing the error reading `~/.singularity/sylabs-token`. This is confusing and misleading.

If a token path is explicitly specified, Singularity should not consider `~/.singularity/sylabs-token`, and report clear error messages regarding the token file at the specified path.

**Comment by tri-adam** [comment]
With `master` (`3.1.0-563.g930a0b9f6` at the time)... this behaviour has changed and now appears to have a different bug.

With no `remote`s configured, and nothing at `~/.singularity/sylabs-token`, the command behaves as expected:

```sh
$ singularity -t ~/token push ~/image.sif sylabs-adam/default/blah
Flag --tokenfile has been deprecated, Use 'singularity remote' to manage remote endpoints and tokens.
WARNING: No default remote in use, falling back to: https://library.sylabs.io
FATAL:   Couldn't push image to library: Authentication token file not found
```

But, with a (good) token in `~/.singularity/sylabs-token`, it appears the file specified with `-t` is ignored, and the token from `~/.singularity/sylabs-token` used instead:

```
$ singularity -t ~/token push ~/image.sif sylabs-adam/default/blah
Flag --tokenfile has been deprecated, Use 'singularity remote' to manage remote endpoints and tokens.
WARNING: sylabs-token files are deprecated. Use 'singularity remote' to manage remote endpoints and tokens.
WARNING: No default remote in use, falling back to: https://library.sylabs.io
INFO:    Image is already present in the library - not uploading.
INFO:    Setting tag latest
WARNING: latest replaces an existing tag
```

**Comment by GodloveD** [comment]
3.2 deprecates the `--token` flag afaik, so this should no longer be an issue.  Reopen if I'm wrong.
