### ISSUE TITLE
stable release instructions are slightly wrong

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#255]
Option 1 on http://singularity.lbl.gov/install-linux has a couple of errors.

First, the directory to cd into is singularity-2.2.
Second, autogen.sh is not in the distribution.   You can just go straight to the configure step.

**Comment by gmkurtzer** [comment]
@vsoch do you have some time to handle this?

Thanks!

**Comment by vsoch** [comment]
Yep, can do later today... running up a mountain now :)

**Comment by vsoch** [comment]
ok @DrDaveD take a look:

http://singularity.lbl.gov/install-linux

Let me know if it looks good.

**Comment by DrDaveD** [comment]
option 1 looks good, but now I see option 2 is missing the call to ./autogen.sh before ./configure

**Comment by vsoch** [comment]
oups, heh. How about now?

**Comment by DrDaveD** [comment]
looks good

**Comment by vsoch** [comment]
Awesome! Thanks for your patience with me :)
