### ISSUE TITLE
Need automated test for --userns

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2553]
I keep running into issues with `--userns` exec/run/shell option and the `allow setuid = no` singularity.conf option in development versions because it isn't getting tested.  There should be at least one automated test for it that runs when user namespaces are enabled in the kernel, and at least one github CI test should make sure that user namespaces are enabled.  This would require a sandbox image.  I checked cmd/singularity/*_test.go and it looks like sandboxes are getting built but not executed.

**Comment by dtrudg** [comment]
We now have e2e profiles for userns and fakeroot setups, so this should be better covered now. Needs a look at how much we have.

**Comment by gvallee** [comment]
I am using that flag with `exec` and containers with MPI and did not see major problems. The `inspect` command on the other hand is giving me a lot of troubles.

**Comment by dtrudg** [comment]
`inspect` is now fixed, and we have various coverage of the options and --userns stuff in the `e2e-test` that I believe covers this issue.
