### ISSUE TITLE
autofs bug fix is still incomplete

### ISSUE THREAD

**Issue by dirkpetersen** [apptainer/singularity#2556]
We use 2.5.2 and 2.6.0 and for us the current auto fs bug fix is not working all that well.

we have multiple storage systems and we use autofs to create a unified folder structure so the end user can be seamlessly migrated to another storage system.

This means we have about 1500 autofs mountpoints for home directories and 250 mountpoints for shared folders and all of those have to be configured in singularity .conf

If I don't have read access to another folder (like most, we are using umask 0007) Singularity sends me a warning for each and every mount point 

```
petersen@rhino3:~$ singularity run ./ubuntu-latest.simg
WARNING: Failed to open directory '/fh/fast/xyz'
WARNING: Failed to open directory '/fh/fast/abc'
WARNING: Failed to open directory '/fh/fast/klm'
WARNING: Failed to open directory '/home/xyz'
WARNING: Failed to open directory '/home/abc'
WARNING: Failed to open directory '/home/klm'
```

The effect is that we only put the folders in there that are absolutely  required which also means that now each user has to notifyc us that they want to use singularity so we can add their folder to the singularity.conf file. This leads us to not want to widely advertise singularity . Can this autofs isssue be addressed ?  It should be easy to detect which root folder is under the rule of auto fs :

```
petersen@rhino3:~$ cat /proc/mounts | grep auto | grep /fh/fast
auto.fast /fh/fast autofs rw,relatime,fd=17,pgrp=6636,timeout=300,minproto=5,maxproto=5,indirect 0 0
```

and then the actual autofs mount point below

```
petersen@rhino3:~$ cat /proc/mounts  | grep /fh/fast/_HDC
silver:/ifs/data/fast/_HDC /fh/fast/_HDC nfs rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=140.107.130.81,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=140.107.130.81 0 0
```

Those could be detected and fixed at runtime when they are used instead of globally trying to acccess all configured mount points at application startup?

**Comment by cclerget** [comment]
Hi @dirkpetersen , did you give a try with v3 without `autofs bug path` directive ? v3 open all bound directories automatically, not a perfect solution, but maybe it could help.

Between thank you for the insights ! We will look how to better fix that for v3.

**Comment by dirkpetersen** [comment]
So I just compiled the latest from master using Ubuntu 14.04

```
petersen@gizmof161:~$ singularity --version
singularity version 3.0.2-299.g2dc58bd
```

before running singularity with the default config I touched /fh/fast/petersen_d (there are about 250 autofs mount points in /fh/fast/) it I was not able to access the folder, I needed to add

```
bind path = /fh/fast
```
after that it just worked fine, but as soon as the autofs timeout was reached I got the same error

```
petersen@ubuntu_latest.sif> ls /fh/fast/petersen_d
ls: cannot open directory '/fh/fast/petersen_d': Too many levels of symbolic links
```
however after touching /fh/fast/petersen_d on the host again I was able to access it in the singularity container.  In the past it could wedge the entire host or at least autofs so this seems to be somewhat an improvement. 
Still I think it just work with autofs since autofs is still used by many many people. Can this be prioritized?

**Comment by dirkpetersen** [comment]
Correction and clarification. So I have 2 file systems mounted via autofs:
 /fh/fast/one and /fh/fast/two

/fh/fast/one is mounted before I run the singularity container. After I launch the singularity container and wait until /fh/fast/one is unmounted from the host after a 300 sec autofs timeout. Then I try to access /fh/fast/one inside the container which is still running and I can access /fh/fast/one just fine. When run the df command on the host while the container is still running /fh/fast/one is not visible which is interesting.

No I try to access /fh/fast/two from inside the container. /fh/fast/two was not mounted when I started  the container. Now I get the "Too many levels of symbolic links" error. What's interesting: When I run df on the host /fh/fast/two shows up as mounted file system. 

So I would state that the current implementation is working OK but still confusing. I think there should  be an option that simply allows us to mount autofs file systems on demand from inside the container, or at the very least an error message like :  "Cannot mount xyz, please make sure that you have touched all file systems you want to use before you launch a container."

Thanks
