### ISSUE TITLE
WARNING: Ignoring user bind request: host does not support PR_SET_NO_NEW_PRIVS

### ISSUE THREAD

**Issue by soichih** [apptainer/singularity#256]
I am using singularity 2.2 on Cray XE6 HPC system. SLES11-SP3 (x86_64). Linux 3.0.101

It has cudatoolkit installed on it and I am trying to use it by binding it from the container.

> singularity shell -B /opt/nvidia/cudatoolkit7.0/7.0.28-1.0502.10742.5.1:/usr/local/cuda soichi.img

I am seeing following warning message, and mounting fails. 
WARNING: Ignoring user bind request: host does not support PR_SET_NO_NEW_PRIVS
WARNING: Not mounting current directory: host does not support PR_SET_NO_NEW_PRIVS
Singularity: Invoking an interactive shell within container...
..

Does this mean I can not do use bind on our system?

Thank you!

**Comment by gmkurtzer** [comment]
According to that yes, it seems that prctl () didn't work at compile time. Can you send me the output of configure and also tell me what version of kernel it is running? I am kind of surprised SLES would fail on that.

Thanks!

**Comment by soichih** [comment]
@gmkurtzer 

```
$ uname -a
Linux login2 3.0.101-0.46-default #1 SMP Wed Dec 17 11:04:10 UTC 2014 (8356111) x86_64 x86_64 x86_64 GNU/Linux
```

I've asked the person who installed it on our cluster for configure output, but I believe it should look similar to following.

```
checking build system type... x86_64-suse-linux-gnu
checking host system type... x86_64-suse-linux-gnu
checking target system type... x86_64-suse-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for style of include used by make... GNU
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/x86_64-suse-linux/bin/ld
checking if the linker (/usr/x86_64-suse-linux/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /opt/cray/cce/8.4.6/cray-binutils/x86_64-unknown-linux-gnu/bin/nm -B
checking the name lister (/opt/cray/cce/8.4.6/cray-binutils/x86_64-unknown-linux-gnu/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 3458764513820540925
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/x86_64-suse-linux/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /opt/cray/cce/8.4.6/cray-binutils/x86_64-unknown-linux-gnu/bin/nm -B output from gcc object... ok
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking dependency style of gcc... (cached) gcc3
checking whether gcc and cc understand -c and -o together... yes
checking for namespace: CLONE_NEWPID... yes
checking for namespace: CLONE_PID... no
checking for namespace: CLONE_FS... yes
checking for namespace: CLONE_NEWNS... yes
checking for namespace: CLONE_NEWUSER... yes
checking for namespace: CLONE_NEWIPC... yes
checking for feature: NO_NEW_PRIVS... no
checking for feature: MS_SLAVE... yes
checking for feature: MS_REC... yes
checking for feature: MS_PRIVATE... yes
checking for setns... no
checking for overlayfs... no
checking if suid should be enabled... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating singularity.spec
config.status: creating test.sh
config.status: creating src/Makefile
config.status: creating src/lib/Makefile
config.status: creating src/lib/ns/Makefile
config.status: creating src/lib/ns/ipc/Makefile
config.status: creating src/lib/ns/mnt/Makefile
config.status: creating src/lib/ns/pid/Makefile
config.status: creating src/lib/ns/user/Makefile
config.status: creating src/lib/rootfs/Makefile
config.status: creating src/lib/rootfs/image/Makefile
config.status: creating src/lib/rootfs/dir/Makefile
config.status: creating src/lib/rootfs/squashfs/Makefile
config.status: creating src/lib/action/Makefile
config.status: creating src/lib/action/exec/Makefile
config.status: creating src/lib/action/shell/Makefile
config.status: creating src/lib/action/start/Makefile
config.status: creating src/lib/action/stop/Makefile
config.status: creating src/lib/action/test/Makefile
config.status: creating src/lib/action/run/Makefile
config.status: creating src/lib/file/Makefile
config.status: creating src/lib/file/group/Makefile
config.status: creating src/lib/file/passwd/Makefile
config.status: creating src/lib/file/resolvconf/Makefile
config.status: creating src/lib/mount/Makefile
config.status: creating src/lib/mount/cwd/Makefile
config.status: creating src/lib/mount/dev/Makefile
config.status: creating src/lib/mount/binds/Makefile
config.status: creating src/lib/mount/home/Makefile
config.status: creating src/lib/mount/hostfs/Makefile
config.status: creating src/lib/mount/kernelfs/Makefile
config.status: creating src/lib/mount/tmp/Makefile
config.status: creating src/lib/mount/userbinds/Makefile
config.status: creating src/lib/mount/scratch/Makefile
config.status: creating src/util/Makefile
config.status: creating etc/Makefile
config.status: creating bin/Makefile
config.status: creating bin/singularity
config.status: creating man/Makefile
config.status: creating libexec/Makefile
config.status: creating libexec/bootstrap/Makefile
config.status: creating libexec/bootstrap/modules-v1/Makefile
config.status: creating libexec/bootstrap/modules-v2/Makefile
config.status: creating libexec/cli/Makefile
config.status: creating libexec/helpers/Makefile
config.status: creating libexec/python/Makefile
config.status: creating libexec/python/docker/Makefile
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing libtool commands

```

**Comment by gmkurtzer** [comment]
This line is the cause:

`checking for feature: NO_NEW_PRIVS... no`

But I don't believe that on that kernel unless Cray has done something funky. I would bet my test is failing during configure. I will research it and let you know. 

I am just curious, are you at a university or lab?

Greg

**Comment by soichih** [comment]
I work at Indiana University - and we manage / support HPC / HTC systems for IU. I used to work for Open Science Grid with @bbockelm :)

**Comment by gmkurtzer** [comment]
Ahhh, small world!

I'm not seeing any documentation about SLES on Cray not properly supporting PR_SET_NO_NEW_PRIVS so I'm wondering if it is failing on PR_GET_NO_NEW_PRIVS instead. I know someone with a Cray (NERSC) so I'll ask around a bit and see if I come up with anything.

In the mean time, can you check the configure.ac and maybe try to remove the PR_GET_NO_NEW_PRIVS, rerun autogen.sh and see if that helps?

Thanks!

**Comment by bbockelm** [comment]
Hi - `PR_SET_NO_NEW_PRIVS` was introduced in Linux 3.5.  Prior to that, there's no secure way to offer the functionality needed by the `-B` flag in general.

That said, the `-B` flag could probably be brought back on older platforms (think CentOS 6) if we allow the admin to whitelist a source of "safe" directories for bind mounting.

**Comment by gmkurtzer** [comment]
@bbockelm Oh, thank you for finding that. I was researching on my ipad as I'm not at my computer yet and that makes sense and clarifies considerably. 

So are you thinking something like "optional bind path = ...."? If so, we may as well just always include them if able and not trouble the user with a -B request.

I am also thinking of directory ownership (make sure root owns bind path location), but it could be maliciously circumvented very easily (e.g. -B /:/tmp/foo). Thoughts on this?

**Comment by bbockelm** [comment]
My idea was to have something like:

```
user bind sources = /opt/ /srv/
user bind destinations = /tmp /usr/local
```

Then, Singularity would check that a user bind request (such as `-B /opt/nvidia/cudatoolkit7.0/7.0.28-1.0502.10742.5.1:/usr/local/cuda` above) is inside one of the listed sources and targets a listed destination.

**Comment by gmkurtzer** [comment]
I like the idea, but not sure if I quite understand the use case/scenerio where we just shouldn't do that by default.. I mean more specifically using your example, why not just do:

```
bind path = /opt/nvidia
```

**Comment by bbockelm** [comment]
Well - I think Soichi's case illustrates it nicely.  It look like he wants a particular cuda version (7.0.28-...) mounted as `/usr/local/cuda`.  I assume that the user wants to pick the available version, not have one selected by the sysadmin.

**Comment by gmkurtzer** [comment]
I maybe wrong on this (so correct me if so), but it seems as though the version selection could also be done via environment paths (e.g. PATH and LD_LIBRARY_PATH). Or are the binaries hard coded to look into /usr/local/cuda for the prefix?

**Comment by soichih** [comment]
So, I am used to be able to do volume mounting on docker, but this is bit more complicated to do with singularity? 

I might be stating the obvious, but I think it's important that user can do bind on any host directory - from containerization point of view. If someone writes a container/app that reads input data from /input, other people can use the identical container as long they can mount their host input/output directory on /input for the container.

Like `singularity exec -B /N/dc2/scratch/myproject/input:/input app.img`

**Comment by gmkurtzer** [comment]
Hi @soichih,

Yes, you are completely right. And the only reason it is easier with Docker is because Docker is not limiting the access you can have within the container. For example, if a user brings their own container to run on our HPC environment, we don't want to allow that user to get root. We have to take additional precautions to ensure that the user can not gain privileges using other means (e.g. bind mounting a directory or file which contains a SUID binary within it).

If I remove the limitation of PR_SET_NO_NEW_PRIVS, it is very easy to escalate privileges inside a container by simply doing `-B /bin/su`... So in a nutshell, because the security paradigms and use cases are different with Docker compared to Singularity, Singularity has to be much more careful about what it allows.

Greg

**Comment by soichih** [comment]
Can singularity simply check to see if user has proper access permission that user is trying to bind? Like.. If I try to bind /root:/tmp/root, it should reject it, right? Or does it still create the root escalation hole?

**Comment by gmkurtzer** [comment]
Yep, but there are more things to be concerned about.. For example, if I do `-B /bin/:/tmp/bin` Then technically `/tmp/bin/su` is present and that file is SUID. Luckily, the bind of a directory seems to take the mount option MS_NOSUID, but when binding a single file it does not.

So maybe, the best solution here is to allow user binds of directories (if config file allows it), and disalow binding files if `PR_SET_NO_NEW_PRIVS` is not supported.

Thoughts @bbockelm?

**Comment by bbockelm** [comment]
Hm,

This still seems pretty dicey.

The problem I would worry about is things like allowing users to overwrite config files that are subsequently read by a setuid binary.

Further, MS_NOSUID seems to have surprising (undocumented?) semantics.  I'm worried about the possibility of an older / patched kernel version that breaks some assumption we are making.

This is why I like the idea of whitelisting directories that the admin knows to be safe.

Alternately, can someone find very good documentation on how MS_NOSUID works?

Brian

**Comment by soichih** [comment]
I am not quite following the technicality of MS_NOSUID / PR_SET_NO_NEW_PRIVS, but if it's too dangerous to do something like docker's -v, I am ok with just mounting /opt/nvidia via the admin configuration file.

By the way, I've noticed that, on CentOS 6.8, PR_SET_NO_NEW_PRIVS is defined in /usr/include/linux/prctl.h, so singularity's configure.ac erroneously(?) thinks that this feature is available.

```
configure:12753: checking for feature: NO_NEW_PRIVS
configure:12779: gcc -c -g -O2  conftest.c >&5
configure:12786: $? = 0
configure:12792: result: yes
```

But, in actuality, as @bbockelm said, this feature is only available on >3.5, so the linux/prctl.h that comes with the CentOS6.8 kernel source doesn't have it defined.

> http://lxr.free-electrons.com/source/include/linux/prctl.h?v=2.6.32

Is it a RHEL/CentOS practice to include definitions that aren't supported on the actual kernel running in order to prevent compiler from breaking? On SLES11, I don't see PR_SET_NO_NEW_PRIVS listed in /usr/include/linux/prctl.h.

**Comment by bauerm97** [comment]
I can see a potential use case for where admins would want to allow set a specific list of allowable mount points:

For instance, an HPC system may have a shared filesystem at /shfs/ directory with sub directories of different versions of some specific software stack /shfs/foo_v1/ and /shfs/foo_v2/. All users of the HPC are instructed to build their software that references foo in location /foo/, but they don't want to need to reference /foo/v1/ or /foo/v2/ (for whatever reason). If the admin doesn't want to give arbitrary bind mount privileges to users, right now he can only bind /shfs/foo_v1/:/foo/ OR /shfs/foo_v2/:/foo/ but not both.

This problem can be solved by including in the config file:

```
user bind sources = /shfs/foo_v1/ /shfs/foo_v2/
user bind destinations = /foo/
```

Now the user can request either foo_v1 with -B /shfs/foo_v1/:/foo/, but other users are still able to grab foo_v2 when they want. If I missed something feel free to correct me

**Comment by DrDaveD** [comment]
> user bind sources = /opt/ /srv/

I understand the need to limit the bind destinations, but why is there a need to limit the bind sources?

**Comment by gmkurtzer** [comment]
Actually, the major issue is on the source, not the destination. This is because the user can bind anywhere within the container, and we don't care... But, if they bind a (host based) destination which includes a SUID binary, then that binary might be able to be used to gain root within the container.

**Comment by pditommaso** [comment]
Same problem at the Barcelona Computing Center (BSC). A workaround would be very useful.

**Comment by soichih** [comment]
@pditommaso The work around is to use bind path on the singularity configuration file

```
bind path = /etc/hosts
bind path = /opt/nvidia
bind path = /opt/cray/nvidia
```

Then you can use -B option to mount those paths, but of course administrator needs to add them to the config file first. There is no fundamental _cure_ to kernel not providing PR_SET_NO_NEW_PRIVS feature. You just have to use the kernel that supports it.

**Comment by gmkurtzer** [comment]
@pditommaso Are you getting the same warning with regards to the user defined bind requests:

```
WARNING: Ignoring user bind request: host does not support PR_SET_NO_NEW_PRIVS
```

**Comment by pditommaso** [comment]
@gmkurtzer If I'm not wrong I was getting that message also for user defined bind paths. However trying now, it says: 

```
WARNING: Not mounting current directory: user bind control is disabled by system administrator
```

I think the sysadmins have changed the singularity configuration.

**Comment by soichih** [comment]
@pditommaso I think you are right. You can look at the singularity.conf to confirm it.

@gmkurtzer You can close this issue now. I think I understand the problem, and for CRAY(SLE11) we just have to ask our administrator to add paths on bind path configuration. There is no plan of IU upgrading OS/kernel for BigRed2 anytime soon, unfortunately.

**Comment by gmkurtzer** [comment]
Gotcha, thanks for the feedback everybody!
