### ISSUE TITLE
error: Failed build dependencies: 	golang is needed by singularity (From RPM)

### ISSUE THREAD

**Issue by titansmc** [apptainer/singularity#2562]
## Version of Singularity:

ingularity-3.0.2-280.g91505f3.el7.x86_64

### Expected behavior

building RPM fine

### Actual behavior

````
[root@haproxy03 singularity]# make -C builddir rpm
make: Entering directory `/root/go/src/github.com/sylabs/singularity/builddir'
 DIST setup VERSION: 3.0.2-280.g91505f3
 DIST create tarball: singularity-3.0.2.tar.gz
 BUILD RPM
error: Failed build dependencies:
	golang is needed by singularity-3.0.2-280.g91505f3.el7.x86_64
make: *** [rpm] Error 1
make: Leaving directory `/root/go/src/github.com/sylabs/singularity/builddir'
````

### Steps to reproduce behavior

Write here.

````
./mconfig
make -C builddir rpm
````

### Workaround 

Comment out from Singularity.spec

````
%if "%{_target_vendor}" == "suse"
BuildRequires: go
%else
BuildRequires: golang
%endif
````

**Comment by jmstover** [comment]
@titansmc 

`yum install epel-release; yum install golang`

The `golang` package is available in EPEL on RHEL based systems. On newer RHEL releases, the Go package package was removed from mainline, and the EPEL version has a new enough version.

So we stopped pulling the Go binary for the build, and preferring the packaged Go version.

**Comment by titansmc** [comment]
I see, so I guess is just a matter of updating the installation
documentation.

**Comment by jmstover** [comment]
Yeah, we have an open issue on our docs to be sure to get that information added in to update the RPM building part.

**Comment by mem** [comment]
Fix already merged.

**Comment by joshuaganger** [comment]
Unless I'm missing something, this does not appear to have been updated in the admin guide: https://sylabs.io/guides/3.2/admin-guide/admin_quickstart.html#download-and-build-the-rpm

The text says 

> Go and all other build dependencies will be downloaded automatically

But it is still necessary to install golang as described by @jmstover

**Comment by jmstover** [comment]
Hi @joshuaganger ,

  The documentation master branch was updated. See:
    https://github.com/sylabs/singularity-admindocs/blob/master/admin_quickstart.rst#install-dependencies

  But a new republish of the documentation hasn't happened yet.

**Comment by joshuaganger** [comment]
@jmstover Thanks for the clarification 👍
