### ISSUE TITLE
Include a disable-suid option for mconfig

### ISSUE THREAD

**Issue by felipeportella** [apptainer/singularity#2570]
For support of non-root installations will be interesting to have a --disable-suid option for mconfig as exists before on versions 2.x with configure script. 

Related to issue #1258 
Created as a separate issue as suggested by:
https://github.com/sylabs/singularity/issues/1258#issuecomment-455614202

**Comment by cclerget** [comment]
@felipeportella It was merged recently in master branch, you can do now :

```
./mconfig --without-suid --prefix=/your/home/softs
make -C builddir
make -C builddir install
```

I will close the issue, feel free to re-open if you have any issues

**Comment by surak** [comment]
It's still not at the documentation, right?

**Comment by dtrudg** [comment]
@surak - this is documented in the recently updated admin guide, and the requirements / limitations of no setuid installs are references in various places in the guides now.

https://sylabs.io/guides/3.5/admin-guide/installation.html#install-nonsetuid
