### ISSUE TITLE
RFE: Support for Ubuntu Snaps

### ISSUE THREAD

**Issue by gmkurtzer** [apptainer/singularity#2572]
### Expected behavior

Ubuntu Snaps are a packaging system using SquashFS encapsulated containers. Shouldn't be too hard for Singularity to support them on any version of Linux that runs Singularity.

### Actual behavior

Currently, we have an issue that `/bin/sh` is a requirement for containers but Snaps do not seem to have them. Also we will probably need to better understand how to launch a snap once the environment is setup.

The history of `/bin/sh` being a requirement of a container came originally from the necessity from the exec()` system call. Is this still a requirement with Go? If so, how do other container systems have non-`/bin/sh` included containers?

### Steps to reproduce behavior

On an Ubuntu system, you can find your Snaps in `/var/lib/snapd/snaps/*.snap` and they should be able to be used like:

`$ singularity run /path/to/ubuntu/program.snap`

**Comment by dtrudg** [comment]
Is this still something you are interested in pursuing @gmkurtzer?

'classic' snaps are probably not that hard. However, the newer confined snaps (which things are moving over to) have defined interfaces for confinement of things:

https://snapcraft.io/docs/supported-interfaces

... to replicate the confinement expectation there would be a large task, and if we just allow running then we will not be providing the same confinement the user of the snap may expect.
