### ISSUE TITLE
Singularity remote build behind corporate proxy

### ISSUE THREAD

**Issue by Amjadhpc** [apptainer/singularity#2573]
## Version of Singularity:
3.0.2

### Expected behavior

singularity build --remote output.sif  library://amjadhpc1/mosaik

Should build without errors

### Actual behavior

EBUG   [U=1003,P=16303]   func1()                       Registering plugin as type BuildPlugin
DEBUG   [U=1003,P=16303]   doBuildRequest()              Sending build request to https://build.sylabs.io/v1/build
DEBUG   [U=1003,P=16303]   doBuildRequest()              Build response - id: 5c445dc4e21266000194b2a4, wsurl: wss://build.production.sycloud.io/v1/build-ws/5c445dc4e21266000194b2a4, libref: amjadhpc1/remote-builds/rb-5c445dc4e21266000194b2a4
DEBUG   [U=1003,P=16303]   streamOutput()                websocket dial err - Forbidden, partial response: <nil>
WARNING [U=1003,P=16303]   Build()                       failed to stream output from remote build service: Forbidden
FATAL   [U=1003,P=16303]   run()                         While performing build: failed to stream output from remote build service: Forbidden

Kindly note that i am currently behind corporate proxy.
Does Golang Websocket support bypassing proxy?
Is there any option in singularity build to put  export proxy parameters?

**Comment by dtrudg** [comment]
@Amjadhpc - if you are getting a 'Forbidden' response it suggests it is trying to connect through the proxy you have setup... and the proxy is issuing that. If it wasn't going through proxy and you don't have a direct route out then the connection would just fail / timeout.

I get a 'Forbidden' from our corporate proxy here... though it is also kind enough to give some HTML explanation that `build.production.sycloud.io` isn't on the whitelist.

If I unset all proxy vars I get timeout, not forbidden.... so the forbidden is definitely from the proxy here.
```
FATAL   [U=128803,P=23855] run()                         While performing build: failed to post request to remote build service: Post https://build.sylabs.io/v1/build: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by Amjadhpc** [comment]
@dctrud - Thank you for your response. I have asked the network team in my corporation to allow access to build.production.sycloud.io  bypassing the corporate proxy.
However they reported that domain is wrong.
DNS server handling your query: localhost
 DNS server's address:	127.0.0.1#53
 
 Non-authoritative answer:
 *** Can't find sycloud.io: No answer

**Comment by tri-adam** [comment]
Hi @Amjadhpc, the hostname for the Build Service specifically is `build.sylabs.io` and `build.production.sycloud.io`. The networking team at your corp _should_ be able to resolve those (let us know if they can't, and we can help troubleshoot.) On my machine, I get:

```sh
$ nslookup build.production.sycloud.io
Server:		192.168.12.1
Address:	192.168.12.1#53

Non-authoritative answer:
Name:	build.production.sycloud.io
Address: 34.193.236.127
```

And I can confirm, I get the same thing you posted for `sylabs.io`:

```sh
$ nslookup sycloud.io
Server:		192.168.12.1
Address:	192.168.12.1#53

Non-authoritative answer:
*** Can't find sycloud.io: No answer
```

Ideally, they should be whitelisting `*.sylabs.io`, and `*.production.sycloud.io`. If they're not comfortable with wildcarding, let us know... we can provide the full list of hostnames if necessary.

**Comment by dtrudg** [comment]
Hi @Amjadhpc - were you able to get this working with firewall rules added? I can confirm that I was able to prior to leaving the org where I was behind a corporate proxy.

**Comment by mem** [comment]
Go's http package supports using proxies. The environment variables HTTP_PROXY and HTTPS_PROXY are supported (and their lowercase versions). Most corporate proxies are either transparent proxies or proxies without authentication, so this should be enough to support this case.

Please reopen the issue if you have additional details.
