### ISSUE TITLE
Possible to load python virtual environment?

### ISSUE THREAD

**Issue by MiBu84** [apptainer/singularity#2587]
## Version of Singularity:
2.5.2-release-2.5

### Expected behavior
I tried to install python, pip and virtual environments in the %post section via

> %post
>         apt-get -y update
>         apt-get -y install build-essential python python-dev git libgmp3-dev libmpfr-dev
>         apt-get -y install autoconf automake libtool
>         apt-get -y install python-pip
>         pip install virtualenv
>         rm -fr /julia && mkdir /julia
>         virtualenv /julia/env2

which seems to work, because afterward, I can open a shell in the container and load the environment via

> . /julia/env2/bin/activate.

Within the build script I actually want to activate the environment with the line above, checkout files from a github project and compile them in this virtual environment env2.

### Actual behavior

> source /julia/env2/bin/activate

 within the %post or the %environment region results in the error that "source" is not found.

> .  /julia/env2/bin/activate

 does not produce an error, but actually the environment is not loaded.

### Steps to reproduce behavior
Use the file

> Bootstrap: shub
> From: singularityhub/ubuntu
> 
> %post
>         apt-get -y update
>         apt-get -y install build-essential python python-dev git libgmp3-dev libmpfr-dev
>         apt-get -y install autoconf automake libtool
>         apt-get -y install python-pip
>         pip install virtualenv
>         rm -fr /julia && mkdir /julia
>         virtualenv /julia/env2
> 
> %environment
>         . /julia/env2/bin/activate
>         export LD_LIBRARY_PATH="$VIRTUAL_ENV/lib":$LD_LIBRARY_PATH

to build the .sif file with 

> sudo singularity build testbuntu.sif testbuntu.def

and open the shell 

> singularity shell testbuntu.sif

You will see:

> Singularity testbuntu.sif:

But I would expect (and require):

> (env2) Singularity testbuntu3.sif

which is only entered after:

> . /julia/env2/bin/activate

**Comment by jscook2345** [comment]
@MiBu84 

> Within the build script I actually want to activate the environment with the line above, checkout files > from a github project and compile them in this virtual environment env2.

I can think of a few ways to do this, but I think I need more information from you.

Can you share the script for the above so I can understand how you're trying to use your container to build your app? Thanks!

**Comment by MiBu84** [comment]
Thanks for your reply!
If I install a fresh Ubutnu, I execute the following commands, which should be prepared in the container:


> # Install an Ubuntu 18.04
> 
> # install all required packages
> apt-get install -y build-essential libgmp3-dev libmpfr-dev vim git
> apt-get install -y autoconf automake libtool
> apt-get install -y python-dev python-pip
> 
> #install virtual environments for python
> pip install virtualenv
> 
> #create the virtual environment, we will work in
> virtualenv env
> 
> #open the virtual environment by sourcing
> . env/bin/activate
> #now we see that we are in the virtual environment because shell shows:
> #"(env) username@machine" instead of "username@machine"
> 
> #checkout the library we want to use
> git clone --recursive https://github.com/fplll/strategizer.git
> 
> #Go to directory
> cd strategizer
> 
> #Call the automic setup script, which only works within load
> #Virtual environment
> ./setup.py
> 
> #Set the environment such that the compiled library is found
> #by the executables
> export LD_LIBRARY_PATH="$VIRTUAL_ENV/lib"
> 
> #That is all which should be prepared within the container...
> 
> #Now I want to open a shell on various systems and call the
> #executables compiled above. They write log-files in their
> #directoy
> python ./set_mdc.py

It tried several ways to split the commands in sections like %environments.
However, . /env/bin/activate never load the required virutal environment and setup fails.

**Comment by QwertyJack** [comment]
Try this

```bash
$ cat venv.def
BootStrap: docker
From: python:2-alpine

%post
    pip install virtualenv
    cd /opt
    virtualenv venv
    . /opt/venv/bin/activate
    pip install ipython\<6

    echo '. /opt/venv/bin/activate' >> $SINGULARITY_ENVIRONMENT

%labels
    Maintainer QwertyJack

$ sudo singularity build venv.sif venv.def
...

$ ./venv.sif ipython -V
5.8.0

**Comment by QwertyJack** [comment]
The venv prompt (venv) may not show up but it does work.

**Comment by MiBu84** [comment]
Hi,
sorry for the missing response. I lost this project out of focus because of many other things to do :(

Thank you very much for your suggestion, but if I try it the way you propose and call the setup.sh which must be called within a virtual environment I receive:

./setup.sh
Please enable a virtual environment
http://docs.python-guide.org/en/latest/dev/virtualenvs/
FATAL:   failed to execute %post proc: exit status 1
FATAL:   While performing build: while running engine: exit status 255

So the enivronment (even if it runs) is not recognised.

**Comment by cclerget** [comment]
Singularity v2 doesn't receive support anymore, but this an issue fixed with latest version (https://github.com/sylabs/singularity/releases/tag/v3.5.3-rc.2) where you can specify argument to `%post` section like this `%post -c /bin/bash` allowing to execute the entire post section with bash instead of default `/bin/sh`, so you could source virtualenv script, here a working example:

```
bootstrap: docker
from: ubuntu

%post -c /bin/bash
    apt-get -y update
    apt-get -y install build-essential python python-dev git libgmp3-dev libmpfr-dev
    apt-get -y install autoconf automake libtool
    apt-get -y install python-pip
    pip install virtualenv

    mkdir /venv
    virtualenv /venv/testing
    source /venv/testing/bin/activate
```

I'm closing the issue as fixed.
