### ISSUE TITLE
Running an image from docker in 3.0.x compared to 2.6.1: non-suid

### ISSUE THREAD

**Issue by afortiorama** [apptainer/singularity#2588]
## Version of Singularity

3.0.x
### Expected behavior

With singularity <3.0.x it was possible to exec an image from docker using without setuid using userNS both with overlay and with underlay it was also possible to use directories non existing in the image. For example using a standard alpine image and binding $PWD:/minnie where $PWD ≠ $HOME I can run a Hello World! script from the host node using overlay allegedly using a NON-SETUID workflow

-bash-4.2$ singularity --version
**2.6.1-dist**
-bash-4.2$ cd /pippo/aforti
-bash-4.2$ cat /proc/sys/user/max_user_namespaces 
15000
-bash-4.2$  egrep 'setuid|lay ' /etc/singularity/singularity.conf|grep -v '#'
**allow setuid = no
enable overlay = yes**
enable underlay = yes
-bash-4.2$ lsb_release -r
Release:	7.6.1810
-bash-4.2$ uname -r
3.10.0-957.1.3.el7.x86_64
-bash-4.2$  singularity --verbose exec -C -B $PWD:/minnie docker://alpine cat /minnie/pluto
Increasing verbosity level (2)
Singularity version: 2.6.1-dist
Exec'ing: /usr/libexec/singularity/cli/exec.exec
Evaluating args: '-C -B /pippo/aforti:/minnie docker://alpine cat /minnie/pluto'
VERBOSE: Set messagelevel to: 2
VERBOSE: Initialize configuration file: /etc/singularity/singularity.conf
VERBOSE Docker image: alpine
VERBOSE Registry: index.docker.io
VERBOSE Namespace: library
VERBOSE Repo Name: alpine
VERBOSE Repo Tag: latest
VERBOSE Version: None
VERBOSE Obtaining tags: https://index.docker.io/v2/library/alpine/tags/list
Docker image path: index.docker.io/library/alpine:latest
VERBOSE Obtaining manifest: https://index.docker.io/v2/library/alpine/manifests/latest
VERBOSE Obtaining manifest: https://index.docker.io/v2/library/alpine/manifests/latest
VERBOSE Obtaining manifest: https://index.docker.io/v2/library/alpine/manifests/sha256:3d2e482b82608d153a374df3357c0291589a61cc194ec4a9ca2381073a17f58e
Cache folder set to /home/aforti/.singularity/docker
Creating container runtime...
Importing: base Singularity environment
Exploding layer: sha256:cd784148e3483c2c86c50a48e535302ab0288bebd587accf40b714fffd0646b3.tar.gz
VERBOSE: Set messagelevel to: 2
VERBOSE: Initializing Singularity Registry
Exploding layer: sha256:1f6d219d0077f6af480398f264117d2e74c03ec5f12d09b7b29b1eefbba872eb.tar.gz
VERBOSE: Set messagelevel to: 2
VERBOSE: Initializing Singularity Registry
VERBOSE: Set messagelevel to: 2
VERBOSE: Initialize configuration file: /etc/singularity/singularity.conf
VERBOSE: Initializing Singularity Registry
VERBOSE: Invoking non-SUID program flow: /usr/libexec/singularity/bin/action
VERBOSE: Set messagelevel to: 2
VERBOSE: Initialize configuration file: /etc/singularity/singularity.conf
VERBOSE: Initializing Singularity Registry
**VERBOSE: Running NON-SUID program workflow**
VERBOSE: Invoking the user namespace
VERBOSE: No autofs bug path in configuration, skipping
VERBOSE: Exec'ing cleanupd thread: /usr/libexec/singularity/bin/cleanupd
VERBOSE: Set messagelevel to: 2
VERBOSE: Daemonizing cleandir cleanup process
VERBOSE: Using session directory: /var/singularity/mnt/session
VERBOSE: Mounting overlay with options: lowerdir=/var/singularity/mnt/container,upperdir=/var/singularity/mnt/overlay/upper,workdir=/var/singularity/mnt/overlay/work
VERBOSE: Singularity overlay mount did not work (Operation not permitted), continuing without it
VERBOSE: Running all mount components
VERBOSE: Couldn't mount devpts filesystem, continuing with PTY functionality disabled.
VERBOSE: Queuing mount of new procfs
VERBOSE: Queuing bind mount of /sys
VERBOSE: Using sessiondir for home directory
VERBOSE: Queuing bind mount of staged home directory to container: /var/singularity/mnt/session//home/aforti -> /home/aforti
VERBOSE: Queuing bind mount of '/pippo/aforti' to '/minnie'
VERBOSE: Queuing bind mount of /tmp
VERBOSE: Queuing bind mount of /var/tmp
VERBOSE: Not mounting current directory: contain was requested
VERBOSE: Mounting '/var/singularity/mnt/session/dev' at '/var/singularity/mnt/final/dev'
VERBOSE: Mounting 'proc' at '/var/singularity/mnt/final/proc'
VERBOSE: Mounting '/sys' at '/var/singularity/mnt/final/sys'
VERBOSE: Mounting '/var/singularity/mnt/session/home/aforti' at '/var/singularity/mnt/final/home/aforti'
VERBOSE: Mounting '/pippo/aforti' at '/var/singularity/mnt/final/minnie'
VERBOSE: Mounting '/var/singularity/mnt/session/tmp' at '/var/singularity/mnt/final/tmp'
VERBOSE: Mounting '/var/singularity/mnt/session/var_tmp' at '/var/singularity/mnt/final/var/tmp'
VERBOSE: Running file components
VERBOSE: Creating template passwd file and appending user data: /var/singularity/mnt/session/passwd
VERBOSE: Binding file '/var/singularity/mnt/session/passwd' to '/var/singularity/mnt/final/etc/passwd'
VERBOSE: Updating group file with user info
VERBOSE: Binding file '/var/singularity/mnt/session/group' to '/var/singularity/mnt/final/etc/group'
VERBOSE: Binding file '/etc/resolv.conf' to '/var/singularity/mnt/final/etc/resolv.conf'
VERBOSE: Containing all rootfs components
VERBOSE: Entering container file system root: /var/singularity/mnt/final
LOG    : USER=aforti, IMAGE='alpine', COMMAND='exec'
VERBOSE: Exec'ing /.singularity.d/actions/exec
**Hello World!**
VERBOSE: Cleaning directory: /tmp/.singularity-runtime.19KgOs0H

### Actual behavior
If I use singularity 3.0.3 instead. With the same setup it fails

-bash-4.2$ singularity --version
**singularity version 3.0.3-rc2.el7**
-bash-4.2$ cd /pippo/aforti
-bash-4.2$ cat /proc/sys/user/max_user_namespaces 
15000
-bash-4.2$ egrep 'setuid|lay ' /etc/singularity/singularity.conf|grep -v '#'
allow setuid = no
enable overlay = yes
enable underlay = yes
-bash-4.2$ lsb_release -r
Release:	7.6.1810
-bash-4.2$ uname -r
3.10.0-957.1.3.el7.x86_64
-bash-4.2$ singularity --verbose exec -C -B $PWD:/minnie docker://alpine cat /minnie/pluto
VERBOSE: Set messagelevel to: 4
VERBOSE: Container runtime
VERBOSE: Check if we are running as setuid
VERBOSE: Spawn scontainer stage 1
VERBOSE: Execute scontainer stage 1
**VERBOSE: Create user namespace**
VERBOSE: Create mount namespace
VERBOSE: Create pid namespace
VERBOSE: Spawn smaster process
VERBOSE: Spawn scontainer stage 2
VERBOSE: Create ipc namespace
VERBOSE: Create mount namespace
VERBOSE: Spawn RPC server
VERBOSE: Execute smaster process
VERBOSE: Serve RPC requests
VERBOSE: Not mounting current directory: container was requested
**FATAL:   container creation failed: mount error: can't mount image /proc/self/fd/9: failed to find loop device: could not attach image file too loop device: permission denied**

Note that this is not only a overlay issue. Underlay doesn't work either

### Steps to reproduce behavior

steps above.

Is this expected? or is it a bug in 3.0.x. Running user images from docker is an important workflow for us (and others). If we cannot run like we do in 2.6.1 we cannot use non-suid mode.

@lukasheinrich

**Comment by DrDaveD** [comment]
This is related to #2345, maybe even a duplicate.  The issue is that singularity 3 converts those docker downloads to SIF images and mounts those, rather than working with a sandbox as the intermediate.  I suggested in #2345 to add a -s option to switch to sandbox mode in that case, and to default to that option when running unprivileged.  @cclerget, what do you think of that?

**Comment by afortiorama** [comment]
Hi,

if it is a duplicate and it is not clear from the first replies I have the same question as the other poster.... Can you restore the original behaviour and ask for the switch only if someone wants explicitely a transient image? 

cheers
alessandra

**Comment by afortiorama** [comment]
sorry I misread... defaulting to sandbox when unprivileged is ok.

**Comment by DrDaveD** [comment]
I chatted with @cclerget about this on slack and he agreed that singularity should use a sandbox for this when running unprivileged, and mentioned that a sandbox is also needed for -w.  When running privileged like in the case of #2345, the -s option is taken for shell, but he could use a different option name for example --sandbox with no shortcut.  The implementation should be pretty simple for docker which has layers downloaded as tarballs, but library:// has SIF images so that would be more complicated.

**Comment by afortiorama** [comment]
It is not clear though why having different behaviours in the two running modes. Might it not lead to inconsitent behaviour? Particularly in a distributed environment like ours I'd rather not find myself having to change the options I run singularity with according to the site setup.

Is there a reason why sandbox was dropped?

**Comment by afortiorama** [comment]
> Particularly in a distributed environment like ours I'd rather not find myself having to change the options I run singularity with according to the site setup.

for example sites that have turned off loop devices but still have setuid enabled will require the extra option.

**Comment by DrDaveD** [comment]
At a minimum I would think that this option should also be the default when there are no loopback devices configured, in addition to when setuid is disabled.  Then those that are running jobs at many differently configured sites shouldn't have to send any options, the default should always work.

**Comment by DrDaveD** [comment]
@cclerget This issue is a high priority for the High Throughtput Computing community.  It is currently the one known issue that is blocking me from putting singularity-3 into EPEL.

**Comment by cclerget** [comment]
@DrDaveD Yes I understand, hope to fix this issue in next days for next minor release

**Comment by afortiorama** [comment]
Hi, 

I've tested the solution to this in 3.1.1 and I expected the sandbox to replace the creation of the image but that is not what is happening, the SIF image is still created and producing it is really expensive in terms of disk space and cpu time, particularly because it uses a /tmp/sbuild-xxxxx directory where the image layers are replicated and the fs is created (this is a lot of replication) before copying the final image and then sandboxing it. So I tried sandboxing myself in the first place, that make things better because we avoid the SIF and we reduce the time and space used but the layers are still downloaded in singularity_cachedir and then replicated in /tmp/sbuild-xxxxx to build the file system before it is then copied to the final destination. Why aren't the layers in singularity_cachedir used directly as it used to be with the sandbox built directly on the target directory? Is the sbuild-xxx stage really needed in this case? (@cclerget)

**Comment by afortiorama** [comment]
Hi,

> Why aren't the layers in singularity_cachedir used directly as it used to be with the sandbox built directly on the target directory? Is the sbuild-xxx stage really needed in this case?

an alternative is that I move to use python bindings which still behave like 2.6.1 when using execute  if there is any guarantuee that this will not change and these bindings will not become obsolete (I see a SIF python so that is a possibility).

https://singularityhub.github.io/singularity-cli/commands-images#execute

**Comment by thdesy** [comment]
Hi,

I just found the ticket looking for disabling setuid with user namespaces enabled and be kind to our users' workflows.
As we can run grid workloads as well as user jobs on our LRMS, we have users with container workflows pulling from remote hubs. While pulling into an intermediate sif-image and when executing converting  on-the-fly the sif into a sandbox works, it might take some extra time for the start-up.
Thus, an option to pull layer tarballs directly into a sandbox would be appreciated especially for larger images to skip the intermediate sif.

Cheers,
  Thomas

**Comment by jscook2345** [comment]
@afortiorama @thdesy 

Could you create a new issue with your requests since this is a closed issue? Please feel free to refer to this issue in the new one. Thanks!
