### ISSUE TITLE
sandbox build from image fails

### ISSUE THREAD

**Issue by LaHaine** [apptainer/singularity#2589]
## Version of Singularity:
3.0.3
### Expected behavior
It should create a sandbox image
### Actual behavior
```
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
FATAL:   Unable to create apps: open /tmp/sbuild-084741232/fs/.singularity.d/env/94-appsbase.sh: no such file or directory

```
### Steps to reproduce behavior
I have an image file mageia-cauldron.img and I was trying to build a sandbox from it with this command: `singularity build -s /tmp/magia /testdata/singularity/mageia-cauldron.img `
The same command runs fine with singularity 2.6.1.

**Comment by tomaslaz** [comment]
Have you tried to execute the command with sudo?

**Comment by LaHaine** [comment]
No, I ran it as root.

**Comment by LaHaine** [comment]
I'd like to add that it is an older container image without the metadata, singularity 2.6.1 can handle it nonetheless:
```
 # singularity inspect mageia-cauldron.img 
ERROR: The Singularity metadata directory does not exist in image
ABORT: Aborting with RETVAL=255
```

**Comment by tomaslaz** [comment]
I think Singularity image files are not backwards or forwards compatible between versions 2 and 3. Version 2 uses squashfs/ext3 formats where as version 3 uses Singularity Image File (SIF) format.

**Comment by jscook2345** [comment]
@LaHaine 

A few questions:

* Can you provide the definition file used to build the container?
* Which version of `singularity` did you use to build the previous container?
* Can you re-run your command with the `-d` option provided to `singularity` for debug output and paste that output in this issue?

**Comment by LaHaine** [comment]
Unfortunately I don't have a definition file for that container, it was converted from a sandbox that was an updated version of an image pulled from docker hub. I guess it was build using singularity 2.6 but I am not sure :-/

Here' the requested debug output:
````
# singularity -d build -s mageia mageia-cauldron.img 
WARNING [U=0,P=7802]       sylabsToken()                 Authentication token file not found : Only pulls of public images will succeed
DEBUG   [U=0,P=7802]       func1()                       Registering plugin as type BuildPlugin
DEBUG   [U=0,P=7802]       Init()                        Entering image format intializer
DEBUG   [U=0,P=7802]       Init()                        Check for image format sif
DEBUG   [U=0,P=7802]       Init()                        sif format initializer returns: SIF magic not found
DEBUG   [U=0,P=7802]       Init()                        Check for image format sandbox
DEBUG   [U=0,P=7802]       Init()                        sandbox format initializer returns: not a directory image
DEBUG   [U=0,P=7802]       Init()                        Check for image format squashfs
DEBUG   [U=0,P=7802]       Init()                        squashfs format initializer returns: not a valid squashfs image
DEBUG   [U=0,P=7802]       Init()                        Check for image format ext3
DEBUG   [U=0,P=7802]       NewBundle()                   Created temporary directory for bundle /tmp/sbuild-167486421
INFO    [U=0,P=7802]       Full()                        Starting build...
DEBUG   [U=0,P=7802]       Init()                        Entering image format intializer
DEBUG   [U=0,P=7802]       Init()                        Check for image format sif
DEBUG   [U=0,P=7802]       Init()                        sif format initializer returns: SIF magic not found
DEBUG   [U=0,P=7802]       Init()                        Check for image format sandbox
DEBUG   [U=0,P=7802]       Init()                        sandbox format initializer returns: not a directory image
DEBUG   [U=0,P=7802]       Init()                        Check for image format squashfs
DEBUG   [U=0,P=7802]       Init()                        squashfs format initializer returns: not a valid squashfs image
DEBUG   [U=0,P=7802]       Init()                        Check for image format ext3
DEBUG   [U=0,P=7802]       GetLocalPacker()              Packing from Ext3
DEBUG   [U=0,P=7802]       unpackExt3()                  Mounting loop device /dev/loop0 to /tmp/sbuild-167486421/mnt064671024
DEBUG   [U=0,P=7802]       unpackExt3()                  Copying filesystem from /tmp/sbuild-167486421/mnt064671024 to /tmp/sbuild-167486421/fs in Bundle
DEBUG   [U=0,P=7802]       func1()                       Running singularity_apps plugin: HandleBundle() hook
FATAL   [U=0,P=7802]       HandleBundle()                Unable to create apps: open /tmp/sbuild-167486421/fs/.singularity.d/env/94-appsbase.sh: no such file or directory

**Comment by jscook2345** [comment]
Sorry I missed this before, but it looks like you're using the apps functionality which is not currently implemented, but is being worked on. Pinging the amazing @ikaneshiro for more feedback!

As far as seeing the definition file, If you use version 2.6.X, you should be able to inspect the container.

https://www.sylabs.io/guides/2.6/user-guide/appendix.html#inspect

<pre>
singularity inspect --deffile <container>
</pre>

Let me know if that works and exposes the definition file.

**Comment by LaHaine** [comment]
No, I am not using the apps functionality. The inspection command doesn't give a result:

```
# singularity inspect --deffile mageia-cauldron.img 
ERROR: The Singularity metadata directory does not exist in image
ABORT: Aborting with RETVAL=255
```
The error is from singularity 2.6.1 but it is the same with 3.0.3.

**Comment by ikaneshiro** [comment]
Hey @LaHaine, it looks like the problem is that part of the build system is banking on having `/.singularity.d/env/` in the container and so its erroring out. This shouldn't be the case and so we'll need to make a fix!

Specifically this line here:
https://github.com/sylabs/singularity/blob/v3.0.3/src/plugins/apps/apps.go#L213

**Comment by jscook2345** [comment]
@LaHaine 

#2741 was merged and should fix this issue. Can you retest and see?

**Comment by LaHaine** [comment]
EDIT: In singularity 3.1.0-273.g2b23e12 the bug is fixed, thank you very much.
