### ISSUE TITLE
Interrupting `Singularity Pull`

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#2596]
## Version of Singularity:

3.0.1

### Expected behavior

Singularity should be able to differentiate between partially downloaded file and completely downloaded file. 

### Actual behavior

FATAL:  image file already exists - will not overwrite
Whereas the file was partially downloaded.

### Steps to reproduce behavior

1. Singularity pull library://alpine
2. While it's downloading the image, interrupt it with Ctrl-C/Ctrl-Z. You will be able to see the file %size of file that has been downloaded. 
3. Rerun the command in step 1. Gives you an error.

**Comment by SDkie** [comment]
@ikaneshiro : For writing interrupt handler, see the listenToSystemSignals function below: 
```
func listenToSystemSignals() {
	signalChan := make(chan os.Signal, 1)
	signal.Notify(signalChan, os.Interrupt, syscall.SIGTERM, syscall.SIGHUP, syscall.SIGQUIT)

	for {
		select {
		case sig := <-signalChan:
			sylog.Fatalf("Received %s Signal", sig)
		}
	}
}
```

I have a query regarding that:
Do we have to write generic signal handler? or only specific to pull command for now?
Generic might need lot of code restructuring. 

Grafana project has written generic signal handler, in that main Goroutine send cancel ctx signal to all the child go routines. 

> https://github.com/grafana/grafana

**Comment by SDkie** [comment]
@ikaneshiro : I checked how signal handlers are implemented in this project and added one handler for pull command. Please review my code when you get time.
