### ISSUE TITLE
%appfiles section is ignored

### ISSUE THREAD

**Issue by LaHaine** [apptainer/singularity#2599]
## Version of Singularity:

3.0.3

### Expected behavior
The files listed in %appfiles should be copied.
### Actual behavior
Nothing happened, the section is ignored.

### Steps to reproduce behavior
I have a definition file that is working fine  with singularity 2.6.1 that contains SCI-F sections for an app called idl. They look like this:

```
%apprun idl
    cat /etc/motd
    exec /opt/idl/8.7/idl/bin/idl

%apprun idlde
    cat /etc/motd
    exec /opt/idl/8.7/idl/bin/idlde

%appfiles idl
/afs/somepath/products/source/idl/8.7/idl87-linux.tar.gz idl.tar.gz

%appinstall idl
    cd /tmp/
    tar xzf /scif/apps/idl/idl.tar.gz
    rm /scif/apps/idl/idl.tar.gz
    mkdir -p /opt/idl/8.7
    echo | ./install.sh -s <<EOF
y 
/opt/idl/8.7
y
n
y
y
y
y
n
EOF
install -m 777 -d /opt/idl/8.7/license/flexera /opt/idl/8.7/license/flexera-sv
echo "http://licence-server-name:7070/fne/bin/capability" > /opt/idl/8.7/license/o_licenseserverurl.txt
```

The build fails at the %appinstall stage, idl.tar.gz isn't there as %appfiles was ignored.

**Comment by ikaneshiro** [comment]
Hey @LaHaine I opened up PR #2630 to address this. If you have a chance to test it out that'd be awesome!

**Comment by LaHaine** [comment]
Thanks, I have tested PR #2630 against the master branch of singularity and my test build is working again.
