### ISSUE TITLE
wrong environment inside notebook if anaconda installed

### ISSUE THREAD

**Issue by ltetrel** [apptainer/singularity#2600]
## Version of Singularity:

2.3.1

### Expected behavior
To load libraries from the singularity container.

In the jupyter notebook :

```
import sys
sys.path
```
return libraries from `/usr/lib` (from the container)

### Actual behavior
Loading the libraries from the server on `/home`

In the jupyter notebook :

```
import sys
sys.path
```
return libraries from `/home/${USER}/.conda` (from the server)

### Steps to reproduce behavior

Using the container from https://hub.docker.com/r/jupyter/datascience-notebook I created a singularity image and run it on a remote sever. On this remote server, I have a conda environment.
When I launch on the server `singularity exec mySimg.simg jupyter notebook --no-browser --allow-root --ip=0.0.0.0` I can't load the libraries from it.

**Comment by ltetrel** [comment]
I found a way to make it work by mounting a fake `/home` and using `--no-home` option.
`singularity exec --no-home -B /path/to/somewhere:/home/$USER mySimg.simg jupyter notebook --no-browser --allow-root --ip=0.0.0.0`

**Comment by mem** [comment]
Hmmm... is this because the user's home is automatically added to the container?

**Comment by dtrudg** [comment]
Yup - if there are things installed with `pip install --user` on the host for the same python version as is in the container, or there is a `PYTHONPATH` referencing home, or active conda / virtualenvs then this will result in loading python packages from the host... it'll actually vary what mix you get between host and container depending on python version and what's in which location.

This is not something we can avoid when mounting `$HOME` by default.

This is common enough we should work out how to call it out in the docs... I wrote a blog post before at one point, and I would call it out in the training I did when I was with UTSW.

**Comment by wohlbier** [comment]
Is there a solution to the `PYTHONPATH` issue? Within a singularity shell if I try to execute a miniconda python script it says that it cannot find my modules. If I start the interpreter within the singularity shell I can load the modules. I can't figure out how to fix this. Thanks.

**Comment by dtrudg** [comment]
@wohlbier - in order to answer the best way to do that we'd need to know how the container is built, and where miniconda is installed within it. What you are describing is likely a slightly different issue to the original report.

In the original report, python modules from $HOME are being found in the container, since $HOME is mounted into the container by default and python will always look there. 

I believe that you have a miniconda installation inside the container, and its modules are not being found?

**Comment by ltetrel** [comment]
I think we could close the issue ? 
The singularity automatically mounts the home but it is a known behaviour. 
But I am not sure why `sys.path` is `/home/${USER}/.conda` and not `/usr/lib` by default

**Comment by wohlbier** [comment]
@dctrud Thanks for the reply.

My current def file can be found here https://github.com/wohlbier/training/blob/master/object_detection/object_detection.def

I tried to use `--no-home` and that did not fix the issue.

To try to work around this I'm trying to create a conda environment within the container, but I'm not having much luck with that.

To see the def file before adding the conda stuff it's at 
https://github.com/wohlbier/training/blob/ec8fb31b9863feb2a6f3b0eda832afdb1eb6eda3/object_detection/object_detection.def

**Comment by wohlbier** [comment]
It appears to be working now. I'm not sure exactly what was going on. Sorry for the noise.
