### ISSUE TITLE
singularity test does not read env PATH correctly

### ISSUE THREAD

**Issue by bulldog20630405** [apptainer/singularity#2602]
## Version of Singularity:
3.0

### Expected behavior

when running singularity test on an instance and echoing the env PATH variable should be the same as if running singularity exec <container> env | grep PATH

### Actual behavior

seems to only echo standard root path

### Steps to reproduce behavior

Write here.
add anything to the PATH in the environment of the def file and build the image.  from within the shell the path will be correct; however, when running test it will not be:

e.g. 

```
%environment
    export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64
    export PATH=$JAVA_HOME/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin

%test
    echo "#################################"
    echo "redhat-release => $(cat /etc/redhat-release)"
    echo "kernel version => $(uname -r)"
    echo "JAVA_HOME      => $JAVA_HOME"
    echo "PATH           => $PATH"
    java -version
    echo ""

```

```
singularity exec centos7_java8.sif env | grep ^PATH
PATH=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

```
singularity test centos7_java8.sif 
#################################
redhat-release => CentOS Linux release 7.6.1810 (Core) 
kernel version => 3.10.0-957.1.3.el7.x86_64
JAVA_HOME      => /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64
PATH           => /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

```

**Comment by jscook2345** [comment]
I was able to reproduce with the following definition file

<pre>
[vagrant@localhost tmp]$ cat centos.def 
BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/x86_64/

%environment
    export PATH=/usr/bin/games:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin

%test
    echo "#################################"
    echo "redhat-release => $(cat /etc/redhat-release)"
    echo "kernel version => $(uname -r)"
    echo "PATH           => $PATH"
    echo ""
</pre>

The `%environment` section is meant to be available at run-time. Since test is a special case it may have been purposely not done there. I'd be curious what 2.6 does.

@ikaneshiro 

What do you think?

**Comment by bulldog20630405** [comment]
okay; if that is what is expected...

i thought the test section was to verify that everything was working
correctly; without the environment read,  it would be hard to verify i
would think?

what is the test section used for?

**Comment by ikaneshiro** [comment]
@bulldog20630405 @jscook2345 This is a bug. The test command should be sourcing the environment in the same way as `exec/shell/run`. The only time it shouldn't do this is when it is being run during image building. I'll investigate this further
