### ISSUE TITLE
Unable to build singularity on ARM64 servers

### ISSUE THREAD

**Issue by abhi18av** [apptainer/singularity#2612]
Hi Team Singularity,

I was curious about using singularity on my `ARM64-v8` server on `Scaleway` and up until the very last step everything went fine when I followed the install instructions from here https://www.sylabs.io/guides/3.0/user-guide/quick_start.html#quick-installation-steps

Here's the error log for your reference 

```
root@cub:~/go/src/github.com/sylabs/singularity# make -C builddir
make: Entering directory '/root/go/src/github.com/sylabs/singularity/builddir'
 GO singularity
    [+] GO_TAGS "containers_image_openpgp apparmor selinux"
# github.com/sylabs/singularity/internal/pkg/runtime/engines/config/starter
In file included from ../internal/pkg/runtime/engines/config/starter/starter.go:13:0:
/root/go/src/github.com/sylabs/singularity/cmd/starter/c/include/starter.h:23:29: error: 'PAGE_SIZE' undeclared here (not in a function); did you mean '_T_SIZE'?
 #define MAX_MAP_SIZE        PAGE_SIZE
                             ^
/root/go/src/github.com/sylabs/singularity/cmd/starter/c/include/starter.h:57:17: note: in expansion of macro 'MAX_MAP_SIZE'
     char uidMap[MAX_MAP_SIZE];
                 ^~~~~~~~~~~~
Makefile:299: recipe for target 'singularity' failed
make: *** [singularity] Error 2
make: Leaving directory '/root/go/src/github.com/sylabs/singularity/builddir'
root@cub:~/go/src/github.com/sylabs/singularity#    

```

Could you please help me figure this out?

**Comment by jmstover** [comment]
Hi @abhi18av ,

`PAGE_SIZE` should be getting defined in the file `/usr/include/sys/user.h` that `starter.h` includes.

What does:  `grep 'PAGE_SIZE' /usr/include/sys/user.h`   --- give you?

**Comment by abhi18av** [comment]
Hi @jmstover ,

Here's the output 

```
root@cub:~# grep 'PAGE_SIZE' /usr/include/sys/user.h
grep: /usr/include/sys/user.h: No such file or directory
```

**Comment by jmstover** [comment]
Okay ... Are you on Debian here then? In that case the file would be under:
  `/usr/include/x86_64-linux-gnu/sys/user.h`

Does it exist there? If not, that comes from the `libc6-dev` package. It _should_ be a default include path...

**Comment by abhi18av** [comment]
Yup, in using `ubuntu-18.04`  on an `AArch64` / `ARM64` architecture 

```
root@cub:~# grep 'PAGE_SIZE' /usr/include/aarch64-linux-gnu/sys/user.h
root@cub:~#   
```

**Comment by abhi18av** [comment]
As for the `libc6-dev`, here's the output when I tried to install 

```
root@cub:~# apt install libc6-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libc6-dev is already the newest version (2.27-3ubuntu1).
libc6-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 83 not upgraded.
```

**Comment by jmstover** [comment]
@abhi18av ... Well, looks like the ARM dev setup is quite a bit different than x86_64 here... :/  I replicated on the 32bit install on a ARM-v7 chip I have here.

@cclerget  ... So, it looks like ARM doesn't define `PAGE_SIZE` in `sys/user.h`... they instead seem to be expecting you to be using:
```
#include <unistd.h>
sysconf(_SC_PAGESIZE)
```

It doesn't look like I can do something like:
```
#include <sys/user.h>
// If not defined above
#ifndef PAGE_SIZE
#include <unistd.h>
#define PAGE_SIZE  sysconf(_SC_PAGESIZE)
#endif
```

That threw an error:
```
error: variably modified 'uidMap' at file scope
error: variably modified 'gidMap' at file scope
```

**Comment by jmstover** [comment]
@abhi18av 

PR #2614 should fix this for you. At least, I was able to build on Raspbian 32-bit, ARM v7 CPU.
