### ISSUE TITLE
Navigating branches on sylabs/singularity... can I git checkout 2.4.0?

### ISSUE THREAD

**Issue by Phylloxera** [apptainer/singularity#2620]
## Version of Singularity:

2.4.0

### Expected behavior

HEAD is now at .... updating files for 2.4.0 release

### Actual behavior

error: pathspec '2.4.0' did not match any file(s) known to git

### Steps to reproduce behavior

```
git clone https://github.com/sylabs/singularity.git
cd singularity
git fetch --all
git checkout 2.4.0
```
### Question:

It appears not all previous releases of singularity are available via git checkout... The following were available (that is they gave expected behavior):
```
git checkout 2.3
git checkout 2.4
git checkout 2.5
git checkout 2.5.0
git checkout 2.6.0
git checkout 2.6.1
```
And presumably many more
I can also get 2.4.2 with
`sudo apt-get install singularity-container`
How should I get 2.4.0?
As an aside, `git branch -a` gave:
* (HEAD detached at 2.3)
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/release-3.0
  remotes/origin/vault/1.x
  remotes/origin/vault/2.x
  remotes/origin/vault/development
  remotes/origin/vault/master-2.x
  remotes/origin/vault/release-2.0.x
  remotes/origin/vault/release-2.1.x
  remotes/origin/vault/release-2.2.x
  remotes/origin/vault/release-2.3.x
  remotes/origin/vault/release-2.4
  remotes/origin/vault/release-2.5
  remotes/origin/vault/release-2.6

This leaves me confused as to how to tell if a branch is or is not available for download.

**Comment by GodloveD** [comment]
Hey there @Phylloxera.  Releases are actually made using tags not branches.  Unfortunately, tags have been created somewhat inconsistently.  For instance, 2.5.0 was accurately tagged as `2.5.0`, but 2.4.0, was tagged as `2.4`.  To see the complete list, cd into the repo and run `git tag` like so:

```
$ git tag
1.0
2.0
2.1
2.1.1
2.1.2
2.2
2.2.1
2.3
2.3.1
2.3.2
2.4
2.4.1
2.4.2
2.4.3
2.4.3-1
2.4.4
2.4.5
2.4.5-rc1
2.4.6
2.4.6-rc1
2.5.0
2.5.0-rc1
2.5.1
2.5.2
2.5.2-rc1
2.5.2-rc2
2.5.2-rc3
2.6.0
2.6.0-rc1
2.6.0-rc2
2.6.1
v3.0.0
v3.0.0-alpha.1
v3.0.0-alpha.2
v3.0.0-beta.1
v3.0.1
v3.0.2
v3.0.2-rc1
v3.0.2-rc2
v3.0.3
v3.0.3-rc1
v3.0.3-rc2
working_daemon_prototype
```
Don't know why there is a tag called `working_daemon_prototype` but I assume it has something to do with `instance` development.  Other than that it should be self-explanatory.
