### ISSUE TITLE
runscript not working when given complex input

### ISSUE THREAD

**Issue by plazonic** [apptainer/singularity#2622]
## Version of Singularity:

3.0.3

### Expected behavior

```
Running command catchsegv 'cactus_setup' '--speciesTree' '((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;' '--cactusDisk' '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="127.0.0.1" port="6328" />\n\t\t</st_kv_database_conf>\n\t' '--logLevel' 'INFO' '--outgroupEvents' 'simHuman_chr6 simDog_chr6 simCow_chr6'
Set log level to INFO
....
```
### Actual behavior

`/.singularity.d/runscript: 1: eval: Syntax error: "(" unexpected
`
### Steps to reproduce behavior

```
singularity pull docker://quay.io/comparative-genomics-toolkit/cactus:dec921fce1a8a7d3dd71a4466ed4565e755d4cdc
singularity --silent run ./cactus_dec921fce1a8a7d3dd71a4466ed4565e755d4cdc.sif cactus_setup --speciesTree '((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;'
```

The difference is in the runscript - with 2.6.1 singularity runscript is a simple:

`exec "bash" "/opt/cactus/wrapper.sh" "$@"
`

which works with above messy args (actual args are even longer and messier) because of how "$@" gets expanded. The way new one is written is not safe for any special symbols and should be rewritten, probably by not trying to set SINGULARITY_OCI_RUN, e.g. (in this case, untested and just the start of it):

```
  #!/bin/sh
  OCI_ENTRYPOINT='"bash" "/opt/cactus/wrapper.sh"'
  OCI_CMD=''
  # ENTRYPOINT only - run entrypoint plus args
  if [ -z "$OCI_CMD" ] && [ -n "$OCI_ENTRYPOINT" ]; then
      exec ${OCI_ENTRYPOINT} "$@"
  fi
  .....
```

Thanks, 
JP

**Comment by cclerget** [comment]
Hi @plazonic , you need to escape this long argument otherwise `((` are evaluated as shell syntax (which is a valid syntax), so if you execute your command :

```
singularity --silent run ./cactus_dec921fce1a8a7d3dd71a4466ed4565e755d4cdc.sif cactus_setup --speciesTree '"((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;"'
```

It should work

**Comment by plazonic** [comment]
Not only is this an incompatible change compared to 2.6.1 (where it works as is, without having to double quote it) but doesn't this go against the idea of singularity run ...? You should be able to run commands within container as you'd do usually, by just prefixing them with singularity run, no?

**Comment by cclerget** [comment]
@plazonic Yes, PR #2624 should fix that, if you can give it a try, once installed you must pull image again to apply the fix located in runscript
