### ISSUE TITLE
`go vet` fails for darwin platform

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2629]
## Version of Singularity:

master

### Expected behavior

`make -C builddir check` passes.

### Actual behavior

`make -C builddir check` fails with:

<pre>
 CHECK go fmt
       PASS
 CHECK go vet
internal/pkg/runtime/engines/oci/process.go:30:2: build constraints exclude all Go files in /Users/justin/go/src/github.com/sylabs/singularity/pkg/util/rlimit
internal/pkg/runtime/engines/oci/create.go:22:2: build constraints exclude all Go files in /Users/justin/go/src/github.com/sylabs/singularity/pkg/util/sysctl
make: *** [check] Error 1
</pre>

### Steps to reproduce behavior

On a MacOS system:

    ./mconfig
    make -C builddir check

**Comment by jscook2345** [comment]
Some notes from Slack

So it looks like the problem is basically that `go vet` is platform aware, but certain parts of our code aren’t specifically identified as `_linux.go`. Those parts are never *compiled* on Darwin, because they are only reachable via `cmd/starter/...` binary which is only built on linux. However, `go vet` is just descending through all trees and hitting everything that’s `_darwin.go` or without a platform suffix

Meaning we’re `go vet`’ing certain code which isn’t compilable on darwin and are not named `_linux.go`, which calls into packages which only have files suffixed with `_linux.go`. That means certain functions are not defined in the eyes of `go vet`

I think the solution is probably to generate a dependency graph of both the CLI and starter binaries, and do a big diff to see which packages are *only* being used in the context of starter. Then we can simply suffix all of those files to `_linux.go` and `go vet` will ignore those on mac

**Comment by bauerm97** [comment]
@jscook2345 @tri-adam @GodloveD I think we need to tackle this before we release 3.2.0, due to the new support for Singularity Desktop

**Comment by jscook2345** [comment]
@bauerm97 

It will take someone a bit of work. General files will need to be moved to `*_linux.go` files and be replaced with the equivalent of our `sylog_dummy.go` file. I don't think that should break anything, but I can't promise that either.

I thought I could maybe use `go list` to find a good way to do this, but I never got it to work out previously.

**Comment by jscook2345** [comment]
@bauerm97 @tri-adam 

I need something for demo day so maybe showing this with a small lesson on cross-building in Go would be good. I will work on this a bit tomorrow for my demo.
