### ISSUE TITLE
VERBOSE: Found avaialble loop device: (null)

### ISSUE THREAD

**Issue by soichih** [apptainer/singularity#263]
I am having an issue running singularity on CRAY(SLE11) ESM (or CCM) execution environment. Although I can run singularity on CRAY login node, I don't have access to the GPU resource and I need to run singularity on the compute node to actually run my application (tensorflow in this case).

As soon as I execute singularity command, it exits out with following error message.

```
$ singularity -v shell \
    -B /opt/nvidia:/opt/nvidia \
    -B /opt/cray/nvidia:/opt/cray/nvidia \
    tensorflow_latest-gpu-2016-09-29-4ca8cbd91fe3.img
increasing verbosity level (2)
Exec'ing: /N/soft/cle5/singularity/2.2/libexec/singularity/cli/shell.exec -BVERBOSE: Set messagelevel to: 2
VERBOSE: Running NON-SUID program workflow
VERBOSE: Opening configuration file: /N/soft/cle5/singularity/2.2/etc/singularity/singularity.conf
VERBOSE: Invoking SUID sexec: /N/soft/cle5/singularity/2.2/libexec/singularity/sexec-suid
VERBOSE: Set messagelevel to: 2
VERBOSE: Opening configuration file: /N/soft/cle5/singularity/2.2/etc/singularity/singularity.conf
VERBOSE: Not virtualizing user namespace: running SUID root
VERBOSE: Calculating image offset
VERBOSE: Could not open loop device /dev/loop0: No such device or address
VERBOSE: Could not open loop device /dev/loop1: No such device or address
VERBOSE: Could not open loop device /dev/loop2: No such device or address
VERBOSE: Could not open loop device /dev/loop3: No such device or address
...
VERBOSE: Could not open loop device /dev/loop122: No such device or address
VERBOSE: Could not open loop device /dev/loop123: No such device or address
VERBOSE: Could not open loop device /dev/loop124: No such device or address
VERBOSE: Could not open loop device /dev/loop125: No such device or address
VERBOSE: Could not open loop device /dev/loop126: No such device or address
VERBOSE: Could not open loop device /dev/loop127: No such device or address
VERBOSE: Found avaialble loop device: (null)
VERBOSE: Cleaning sessiondir: /tmp/.singularity-session-740536.26.260369164
```

Again, this only happens when I try to run singularity on CRAY compute node.

Despite these error messages, I see /dev/loopN where I am executing singularity (although owned by root - with bflag)

```
hayashis@nid00170(br2):~/test/singularity $ ls -la /dev/loop1
brw------- 1 root root 7, 1 Oct 24 08:16 /dev/loop1
hayashis@nid00170(br2):~/test/singularity $ ls -la /dev/loop0
brw------- 1 root root 7, 0 Oct 24 08:16 /dev/loop0
hayashis@nid00170(br2):~/test/singularity $ ls -la /dev/loop127
brw------- 1 root root 7, 127 Oct 24 08:16 /dev/loop127
```

**Comment by gmkurtzer** [comment]
Interesting,... Not sure why that is happening. Can you strace it as root:

$ sudo strace -ff singularity exec -vv tensorflow_latest-gpu-2016-09-29-4ca8cbd91fe3.img uname -a

I do see a different bug about printing the (null).

**Comment by soichih** [comment]
I don't have sudo access on our cluster (although I can ask someone who does to run the command), so for now I've ran strace without sudo. Does it give you useful information?

https://gist.github.com/soichih/8a1151e43d54f6db86787094e36f6ab1

**Comment by bbockelm** [comment]
@gmkurtzer - note that there is definitely a bug here.  If no loopback device is found, there should be an explicit error.  Right now, the `loop_dev` is returned as `NULL` instead of aborting on failure.

**Comment by bbockelm** [comment]
@soichih - maybe this is something special with the Cray kernel?  Is it possible that the `mknod` call is returning prior to loopback device actually being ready?

Does Cray support have any suggestion?  Other than the bug Greg and I noted, the code looks correct from a traditional Linux POV.

**Comment by gmkurtzer** [comment]
@bbockelm Indeed, that was the bug I referenced above.

Also, I should mention, I've asked a Cray engineer for some assistance on this. I will report when I've learned more.

**Comment by gmkurtzer** [comment]
@bbockelm If the mknod() was returning asynchronously, then a followup execution of Singularity should work just fine. I would bet this is a security "feature" of the Cray kernel or other peculiarity specific to Cray.

**Comment by soichih** [comment]
@gmkurtzer @bbockelm I was told to let you guys know that IU can give you guest Bigred2 accounts - if you don't have access to CRAY based systems.

**Comment by gmkurtzer** [comment]
Oooooo, thank you! I'm not sure how useful it will be without root though. I have a request for some help from Cray... Let's see how that goes, but I may take you up on that offer soon! Thanks again!

**Comment by soichih** [comment]
I've noticed that there is no /kernel/drivers/block/loop.ko installed for the kernel used on our compute node (it only exists for our login node). Does this explain why I can only run singularity on our login node?

Shifter uses /dev/loop0 also, so I think it should technically work..

> https://github.com/NERSC/shifter/blob/9d053ec737950e6d6c0854869cfc87f578210d71/src/shifter_core.c#L1209

BTW on above code, Shifter uses stat() instead of fopen(). I don't think it matters in this case, but I first thought maybe singularity's test method had an issue - before noticing the missing kernel module. 

I will ask our sysadmin about why loop.ko isn't available for our compute node.

**Comment by gmkurtzer** [comment]
The last time I looked at Shifter, they were also shelling out to /sbin/losetup and /bin/mount which might take care of some of the dirty work as well.

Let us know what the system-admins say!

Thanks :)

**Comment by gmkurtzer** [comment]
I believe that for CRAY to be supported both loop and ext3 kernel modules need to be available on the host. Closing this issue.

**Comment by soichih** [comment]
Our admin was able to install loop (borrowing some installation script for shifter) and we now have Singularity running on Bigred 2

Btw, Cray's kernel seems to have suid no priv kernel feature back ported, but the kernel header doesn't have it listed (so it appears that it doesn't support it) We tested by locally defining the the missing definitions and it seemed to work.

**Comment by gmkurtzer** [comment]
Ahh, that is very cool on both counts!

Will you send a PR that has the missing defines (for both the configure, and the source) and I will add that in.

Thanks!
