### ISSUE TITLE
Add opensuse RPM tests

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2634]
I'd like to setup some opensuse tests for RPM building in our CI so I don't have to manually test them when we change RPM building :)

**Comment by dtrudg** [comment]
Going to close this. Singularity is being packaged by OpenSUSE and is kept up-to-date here: https://software.opensuse.org/package/singularity - we've had contributions from them where there have been issues.

We had a discussion about reducing CI times, and I think adding OpenSUSE builds at this time, especially given we aren't distributing RPMs, would go against this.
