### ISSUE TITLE
RPM Spec expansion

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#2636]
## Version of Singularity:

3.x

### Expected behavior

`mconfig` has the ability to take the `--mandir`, `--datadir`, etc... options. We should update the RPM spec to make use of these.

**Comment by mem** [comment]
@jmstover 	is the work done in #2621 enough to address this?

**Comment by jmstover** [comment]
Doh... forgot about this. Wasn't specifically that PR, but yeah it isn't an issue anymore. Closing.

Thanks.
