### ISSUE TITLE
Exec failture "Failed to return to current path" if CWD is a SSHFS, otherwise SSHFS works as a target

### ISSUE THREAD

**Issue by Yeahhhh** [apptainer/singularity#2638]
## Version of Singularity:
Centos 7 with mainline kernel
Linux 4.20.4-1.el7.elrepo.x86_64

$yum provides singularity
singularity-2.6.1-1.1.el7.x86_64 : Application and environment virtualization
Repo        : epel

### Expected behavior

"singularity exec" success

### Actual behavior

"Singularity exec" does not work when the current directory is a SSHFS. Otherwise, if change dirtory to $HOME, and use SSHFS directory as the target, it works.

### Steps to reproduce behavior

$ sshfs myhost: ~/mnt                                                                                           # mount SSHFS to ~/mnt
$ cd && singularity exec ~/app/bin/debian9_desktop.img ls ~/mnt/                # works
output_of_ls ....
$ cd ~/mnt && singularity exec ~/app/bin/debian9_desktop.img ls ~/mnt/      # fails
ERROR  : Failed to return to current path /home/user/mnt: Permission denied
ABORT  : Retval = 255
$ cd ~/mnt && singularity exec ~/app/bin/debian9_desktop.img ls                 # fails
ERROR  : Failed to return to current path /home/user/mnt: Permission denied
ABORT  : Retval = 255
$ cd ~/mnt && singularity exec -u ~/app/bin/debian9_desktop.img ls ~/mnt/   # fails
ERROR  : Could not create /dev/loop1: Permission denied
ABORT  : Retval = 255

**Comment by cclerget** [comment]
Hi @Yeahhhh , here an explanation and the solution about your issue : https://unix.stackexchange.com/questions/17402/why-does-root-get-permission-denied-when-accessing-fuse-directory

As Singularity leverage setuid some code is running as root, there is nothing that can be done on our side. You need to to add `user_allow_other` in `/etc/fuse.conf` and specify `-o allow_root` when running an sshfs instance.

**Comment by cclerget** [comment]
@Yeahhhh I will close issue, feel free to re-open it if you have any question
