### ISSUE TITLE
Catch errors properly in run-help

### ISSUE THREAD

**Issue by gmkurtzer** [apptainer/singularity#2648]
## Version of Singularity:

3.0.2

### Expected behavior

A nice warning or error when a file doesn't exist.

### Actual behavior

An uncaught error is produced by `/bin/cat` from within the container.

### Steps to reproduce behavior

```
$ singularity build centos7.sif docker://centos:7
   singularity run-help centos7.sif 
/bin/cat: /.singularity.d/runscript.help: No such file or directory
```

**Comment by SDkie** [comment]
@gmkurtzer : I am not able to reproduce this issue on my Debian system. 
If possible can you share more information?

**Comment by SDkie** [comment]
@gmkurtzer : I was able to reproduce the issue :D Sorry
