### ISSUE TITLE
Pip install : Could not install packages due to an EnvironmentError

### ISSUE THREAD

**Issue by AymericFerreira** [apptainer/singularity#2651]
## Version of Singularity:

3.0.1

### Expected behavior

I would like to install package through pip in the virtual environment (pillow for example but I have an error with all packages)

### Actual behavior

On my local computer I receive this message : 

Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/usr/local/lib/python3.6/site-packages/Pillow-5.4.1.dist-info'

### Steps to reproduce behavior

Install Singularity 3.0.1
```
singularity shell docker://pymesh/pymesh
pip install pillow
```

Same problem with "sudo singularity shell docker://pymesh/pymesh"

I looked for the file : Pillow-5.4.1.dist-info in '/usr/local/lib/python3.6/site-packages/' but there is no file with this name in the folder.

I would like to know if I missed something or did something wrong.
Thank you

**Comment by gmkurtzer** [comment]
The `pip install` command is trying to install into the system directory which is mounted by default as read only. Check out the `--writable-tmpfs` option as I think it will do what you want:

```
$ sudo singularity shell --writable-tmpfs docker://pymesh/pymesh
Singularity pymesh_latest.sif:/home/gmk> pip install pillow
Collecting pillow
  Downloading https://files.pythonhosted.org/packages/85/5e/e91792f198bbc5a0d7d3055ad552bc4062942d27eaf75c3e2783cf64eae5/Pillow-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 4.2MB/s 
Installing collected packages: pillow
Successfully installed pillow-5.4.1
Singularity pymesh_latest.sif:/home/gmk> 
```

**Comment by jon-chuang** [comment]
Hi, I get a permission denied, upon following the proposed solution. 
`ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied`
Suggestions?

**Comment by dtrudg** [comment]
@jon-chuang - please could you open a new issue, giving the version of Singularity you are using, and debug output from `singularity -d` if possible.

This issue was reported against `3.0.1` and a lot has changed since then, so it's better to collect it as a new issue with full detail. Thanks.
