### ISSUE TITLE
change a file of a singularity image without sudo rights

### ISSUE THREAD

**Issue by hariszaf** [apptainer/singularity#2654]
Hi everyone, 

I have built an image for Singularity Version 3 in which there is a file that each time the user run the image, it needs to change it. 

How can such a thing can be done **without sudo rights**??

Thank you all for your time.
Haris

**Comment by GodloveD** [comment]
Can you save the file on the host system and bind mount it into the container at runtime?  Or can you create the container as a sandbox and run it with the `--writable` flag (assuming that it's saved with ownership and permissions that allow the user to write to it.)?

**Comment by hariszaf** [comment]
Hi David!

I was trying the second one but I do not know how I can give  
permission to the user to modify the image!

Do you have any idea about that?

The first solution you suggested was what I was planning to do  
afterwards, but I would really prefer the "--writeable" way.

Thanks a lot




Παραθέτοντας από David Godlove <notifications@github.com>:

**Comment by jmstover** [comment]
Hi @hariszaf 

It takes some prep before you run the image ... but you can use `--writable-tmpfs`.  For example:

```
$ sudo echo "Hi" > ubuntu/somefile
$ sudo chmod 666 ubuntu/somefile
$ /usr/local/singularity/3.0.2/bin/singularity shell --writable-tmpfs ubuntu/
Singularity ubuntu:~> ls -l /somefile 
-rw-rw-rw- 1 root root 3 Feb  6 06:45 /somefile
Singularity ubuntu:~/tmp/sing> cat /somefile
Hi
Singularity ubuntu:~> echo "Bye" > /somefile 
Singularity ubuntu:~> cat /somefile 
Bye
Singularity ubuntu:~> exit
exit
$ cat ubuntu/somefile 
Hi
```

*BUT* ... any user could modify this _outside_ of singularity because the file permissions allow that.

Basically:
*) Setup file in container with permissions that allow users to modify
*) Run singularity with `--writable-tmpfs` option
*) If a file is in the container, but can be modified by the user ... then it can modified for the life of the container

**Comment by hariszaf** [comment]
Dave here is exactly what i need to do:

i am trying to build an image where each user will set a parameter  
file and add its input files in order to execute it.

I cannot use the --writable flag as the users will work on HPC and  
sudo commands will not be allowed.


I am now trying the bind mount way, but as it is my first time with  
this technology, i have not figured out yet if that is possible.






Παραθέτοντας από David Godlove <notifications@github.com>:

**Comment by hariszaf** [comment]
Hi @jmstover 

I might did not explain properly what my problem is. 

What I am trying to do is to create an image, where a file will be allowed to change by the user. 

Also. the user, will somehow, put his data on the image (either by copying them on the image or by mounting them from host). 

However, i do not know the syntax for any of them, if these tasks are possible..

Thank you very much for all your time and help!! (It's my first try on Docker-Singularity images, so sorry for the inconvenience) 

Haris

**Comment by jmstover** [comment]
Hi @hariszaf 

By default, the users home directory should be available unless the configuration denies this.

But say for instance you need to have the data located at:  `/application/data`  -- in the container. Any user should be able to do something like:

`singularity run -B $HOME/job1/data:/application/data myimage.sif`

So, the directory `$HOME/job1/data` ... will be located at `/application/data` when you run the container.

Again, unless the configuration denies it, user binding is available.

The same syntax works with specific files if needed.

**Comment by mem** [comment]
I believe the original question has been addressed.
