### ISSUE TITLE
%post section not run with bash

### ISSUE THREAD

**Issue by mxmlnkn** [apptainer/singularity#2656]
## Version of Singularity:

3.0.2-119.ged79a2e1

### Expected behavior

Run commands under `%post -c /bin/bash` with bash.

### Actual behavior

Commands are run in `/bin/sh`, which is `dash` for Debian, Ubuntu, and possibly others.

### Steps to reproduce behavior

    Bootstrap: library
    From: debian:9

    %post -c /bin/bash
            echo "Running post section"
            echo $0
            dpkg -S $0
            function foo { echo; }
            echo "Bashism function defined"

Then run:

    sudo singularity build testbash.{img,def}

Output:

    INFO:    Starting build...
     40.36 MiB / 40.36 MiB [============================================================================================] 100.00% 14.01 MiB/s 2s
    INFO:    Running post scriptlet
    + echo Running post section
    Running post section
    + echo /bin/sh
    /bin/sh
    + dpkg -S /bin/sh
    diversion by dash from: /bin/sh
    diversion by dash to: /bin/sh.distrib
    dash: /bin/sh
    + function foo { echo
    /bin/sh: 4: function: not found
    FATAL:   post proc: exit status 127
    FATAL:   While performing build: while running engine: exit status 255

I can't change `function foo {` to `foo() {`, it's an external script which needs to be sourced.

### Hacky workaround

```bash
%post
    if test "$0" = "/bin/sh"; then
        echo "Elevating script to bash"
        sed -n -z '$p' "/proc/$$/cmdline" | sed 's/\x00/\n/g' | /bin/bash -ve
        exit $?
    fi

    echo "Running post section"

%runscript
    if test -x /bin/bash && test "$( readlink /proc/$$/exe )" != /bin/bash; then
        sed '1{ /^#!/d }' "$( sed -n -z '$p' "/proc/$$/cmdline" | sed 's/\x00/\n/g' )" | /bin/bash
        exit $?
    fi

    function foo() { local array=( "$@" ); echo ${array[2]}; }
    foo 0 1 2 3 4
```

**Comment by gmkurtzer** [comment]
`%post -c /bin/bash` should work, as it does in v2.x. Ian, can you take a look; I assume we aren't propagating the arguments properly to `/bin/sh`.

**Comment by ikaneshiro** [comment]
We aren't currently. I'll look into a fix

**Comment by ikaneshiro** [comment]
Going to target this issue to 3.2 since this will require enough work on the parser that I don't think we'll be able to get it into 3.1.

**Comment by GodloveD** [comment]
encapsulated in issue #2438

**Comment by GodloveD** [comment]
Added an estimate of 1 to this not because it is easy, but because it is tracked on other issue.
