### ISSUE TITLE
runscript does not pass signals (e.g. SIGINT) to forked processes as it did in version 2

### ISSUE THREAD

**Issue by lparsons** [apptainer/singularity#2663]
## Version of Singularity:

3.0.3

### Expected behavior

Signals (e.g. `SIGINT`) are passed from the `runscript` to the forked process being executed.

### Actual behavior

Signals are not passed to forked processes since the runscript uses `eval` to execute the command. In earlier versions (version 2.x) it used `exec` which meant that signals made it to the new process.

### Steps to reproduce behavior

1. Pull docker container
2. Issue command using `singularity run container.img COMMAND_LISTENING_FOR_SIGINT`
3. Send `SIGINT` to the child process created in 2.

There is an example of this problem documented in https://github.com/ComparativeGenomicsToolkit/cactus/issues/60.

Another somewhat related issues was #2622, although that was regarding quoting of parameters.

**Comment by cclerget** [comment]
Hi @lparsons, current master branch should fix this issue

**Comment by mem** [comment]
The issue is related to this #3696? (I could not find another commit that deals with signals, and given @cclerget 	comment above, I don't think #3696 is the right one given the timestamp).

**Comment by cclerget** [comment]
Closing, fixed by #2552
