### ISSUE TITLE
Command should exist to import layers cached in local docker daemon

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2676]
## Version of Singularity:

3.x+

### Expected behavior

Some command should exist which provides the ability to import the docker image layers cached within a local instance of docker. Or maybe better, the ability to link the two caches together so that any time a docker command downloads a layer, singularity has access to those layers as well.

`singularity cache import`

**Comment by mem** [comment]
@bauerm97 	could you please expand what the desired behavior is? I don't understand it from the provided description.

**Comment by dtrudg** [comment]
We can `singularity build` from a `docker-daemon` source. I don't think that linking caches is too practical, as the docker ones are managed by the root-running daemon, so we have to ask for specific things the daemon can provide.

This hasn't come up as a user question yet, so closing unless it does.
