### ISSUE TITLE
Intermitent errors when creating container instance attached to macvlan network namespace

### ISSUE THREAD

**Issue by j-guitart** [apptainer/singularity#2680]
## Version of Singularity:

3.0.3

### Expected behavior

Some invocations work fine, and create the container instance successfully. In those cases, the debug info is as follows:
...
DEBUG   [U=0,P=45877]      create()                      Chroot into <SINGULARITY-HOME>/singularity/var/singularity/mnt/session/final
DEBUG   [U=0,P=2]          Chroot()                      Change current directory to <SINGULARITY-HOME>/singularity/var/singularity/mnt/session/final
DEBUG   [U=0,P=2]          Chroot()                      Hold reference to host / directory
DEBUG   [U=0,P=2]          Chroot()                      Called pivot_root on <SINGULARITY-HOME>/singularity/var/singularity/mnt/session/final
DEBUG   [U=0,P=2]          Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=2]          Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=2]          Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=2]          Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=0,P=45877]      create()                      Chdir into / to avoid errors
DEBUG   [U=0,P=1]          set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=1]          prepare_scontainer_stage()    Entering in scontainer stage 2
DEBUG   [U=0,P=1]          set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=1]          startup()                     Execute scontainer stage 2
DEBUG   [U=0,P=45877]      PostStartProcess()            Post start process
DEBUG   [U=0,P=1]          StartProcess()                Received signal child exited
DEBUG   [U=0,P=1]          StartProcess()                Received signal continued
VERBOSE [U=0,P=45855]      execStarter()                 you will find instance output here: ...
VERBOSE [U=0,P=45855]      execStarter()                 you will find instance error here: ...
INFO    [U=0,P=45855]      execStarter()                 instance started successfully

### Actual behavior

Other invocations using exactly the same command fail, being the debug info as follows:
...
DEBUG   [U=0,P=46004]      create()                      Chroot into <SINGULARITY-HOME>/singularity/var/singularity/mnt/session/final
DEBUG   [U=0,P=2]          Chroot()                      Change current directory to <SINGULARITY-HOME>/singularity/var/singularity/mnt/session/final
DEBUG   [U=0,P=2]          Chroot()                      Hold reference to host / directory
DEBUG   [U=0,P=2]          Chroot()                      Called pivot_root on <SINGULARITY-HOME>/singularity/var/singularity/mnt/session/final
DEBUG   [U=0,P=2]          Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=2]          Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=2]          Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=2]          Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=0,P=46004]      CleanupContainer()            Cleanup container
ERROR   [U=0,P=46004]      Master()                      container cleanup failed: no instance found with name instance-name
FATAL   [U=0,P=46004]      Master()                      container creation failed: failed to open netns %!!(MISSING)q(<nil>): failed to Statfs "/proc/46004/fd/7": no such file or directory
FATAL   [U=0,P=45982]      execStarter()                 failed to start instance: exit status 1

### Steps to reproduce behavior

I'm using version 3.0.3 to create a Singularity container instance that communicates through a macvlan network namespace. To do that, I invoke the following command:

$ sudo singularity --debug instance start --net --network my-macvlan-net image.sif instance-name

My CNI config file is as follows (due to privacy I obfuscated the IP addresses):
{
"cniVersion": "0.3.1",
"name": "my-macvlan-net",
"type": "macvlan",
"master": "eno1",
"ipam": {
  "type": "host-local",
  "ranges": [ [ {
    "subnet": "XX.XX.0.0/16",
    "rangeStart": "XX.XX.255.2",
    "rangeEnd": "XX.XX.255.254",
    "gateway": "XX.XX.0.1" } ] ],
  "routes": [ {
    "dst": "XX.XX.0.0/16",
    "gw": "XX.XX.0.1" } ]
  }
}

**Comment by cclerget** [comment]
Hi @j-guitart , can you try with latest version from master branch or with 3.1-RC1 ?

**Comment by j-guitart** [comment]
Hi @cclerget,
I've tried with v.3.1.0-rc1 and it seems to work correctly, so I will close the issue.
Thanks!
