### ISSUE TITLE
Sign Should Check PGP Public Key is Current

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#2686]
## Version of Singularity:

3.0.3

### Expected behavior

When `singularity sign` is performed, if the public key used is not in sync with the Key Service, it should offer to push the updated version of the key. In this way, if the key is modified (expiration date changed, signatures added, etc.) the latest version will be available to users performing a `singularity verify`.

### Actual behavior

`singularity sign` commands do not check that the key is up to date.

### Steps to reproduce behavior

Generate a PGP key pair, and push the public key to the Key Service. Modify the key pair. Sign a container with the private key. Observe that `singularity sign` still works, but the public key in the Key Service has not been updated.

**Comment by GodloveD** [comment]
Sounds like we are deciding not to do this after all.
