### ISSUE TITLE
SCS Endpoint Management

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#2687]
Currently, working with an instance of the Singularity Cloud Services (SCS) other than the one at `cloud.sylabs.io` is difficult and tedious. Many of the associated commands require multiple options to be passed in order to set URLs and the associated API token.

For example, to do a build against `build.staging.sylabs.io`:

```sh
$ singularity --tokenfile staging-token build --builder https://build.staging.sylabs.io --library https://library.staging.sylabs.io image.sif recipe.txt
``` 

As a way to simplify this, I propose we introduce a `singularity remote` set of commands. These commands will allow a user to assign a single, human-readable name that maps to a set of API endpoints and an associated API token.

In this way, one could add a new set of SCS endpoints like so:

```sh
$ singularity remote add staging cloud.staging.sylabs.io
```

We should have an easy way of generating the API key (command TBD) something like:

```sh
$ singularity remote login staging
Generate an API Key at https://cloud.staging.sylabs.io/api-key, and paste here:

API Key: <PASTE>

Verifying API Key… OK!
```

It'd be nice to be able to see service and API key information:

```sh
$ singularity remote status staging
Status report for staging (cloud.staging.sylabs.io):
SERVICE            STATUS   VERSION
Auth Service:      OK	   [v1.0.0-alpha.5-0-gefb1e63]
Build Service:     N/A
Container Library: N/A
Key Service:       OK       [v1.3.0-0-gaff1db5]

API Key: valid!
```

Finally, you could have more than one `remote` configured:

```sh
$ singularity remote list
NAME        URI
[cloud]     cloud.sylabs.io
staging     cloud.staging.sylabs.io
```

And switch between them:

```sh
$ singularity remote use staging
$ singularity remote list
NAME        URI
cloud       cloud.sylabs.io
[staging]   cloud.staging.sylabs.io
```

**Comment by GodloveD** [comment]
I like this idea immensely.  I think that @dctrud's original idea is that this functionality should be added with a configuration file.  Would these commands automagically edit a configuration file then?  I think the original intention too was to create conf files that could be maintained by admins.  That would a user of an on-prem SCS would not have to think too much right?  The admin would just set things up for them and things would work with the on prem SCS.

**Comment by jscook2345** [comment]
I second the idea of a config file. I like the idea of something git-like (sections, aliases, etc).

**Comment by tri-adam** [comment]
Yeah, I agree it's a good idea if these commands are backed by a YAML. A portion of this will need to be configurable per user (API tokens and the remote that is currently selected via `use`.) I'd envisioned the `remote`s being configurable by a user _or_ admin.
