### ISSUE TITLE
oci command issues

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2689]
## Version of Singularity:

3.1.0-rc1

### Expected behavior

Help info that will be sufficient to use the system.   Ability to run oci containers as an unprivileged user.

### Actual behavior

The oci mount help is incomplete.  Have not been able to figure out how to run it or oci create as unprivileged user.

### Steps to reproduce behavior

singularity oci mount -h says usage is "singularity oci mount" but as the example shows you have to also pass in a sif file and a directory name for the oci bundle.   It doesn't say anything about running as root, but if you don't there's an error
```
FATAL:   failed to find loop device: failed to attach image /scratch/tmp/singularity/images/centos6.sif: no loop devices available
```

If run as root, then a bundle directory is created, all owned as root of course.  If I sudo chown -R it to my unprivileged account and run singularity oci create like this
```
singularity oci create -b centos6.oci centos6
```
the first error is
```
FATAL:   failed to open centos6.oci/config.json: open centos6.oci/config.json: no such file or directory
```
The file is there, however, but the problem is that you need to have a full path.  Using instead $PWD/centos6.oci gives an error
```
FATAL:   you can't run without root privileges, use user namespace rather
FATAL:   exit status 255
```
Ok it is good to say that root privileges are needed if they are, but what does "use user namespace rather" mean?  There's no -u option to run with user namespaces.  Setting 'allow setuid = no' in /etc/singularity/singularity.conf does not help.

**Comment by DrDaveD** [comment]
I forgot to mention that I was testing on a scientific linux 7 system (which is based on rhel 7).

**Comment by GodloveD** [comment]
Heya @DrDaveD!  Thanks for testing out the rc and for identifying the issue!  I think this is really a documentation issue.  afaik, `singularity oci mount` is not intended to run as a non-root user.

**Comment by DrDaveD** [comment]
How about singularity oci create?  Is there any way to use an oci bundle without root?

**Comment by ArangoGutierrez** [comment]
there's a `create` cmd already 
`singularity oci create ` ->   Create a container from a bundle directory
This is in complicance with OCI CLI spec

**Comment by DrDaveD** [comment]
I see it has to be specified in config.json, according to this [documentation](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwj2zL-ap7TgAhVB2oMKHbzfDf8QFjAAegQICBAB&url=https%3A%2F%2Fgithub.com%2Fopencontainers%2Fruntime-spec%2Fblob%2Fmaster%2Fconfig-linux.md&usg=AOvVaw1nkViA2CDLFA5l1tmcIkm8).

I tried adding this to the "linux"  "namespaces" section and
```
                        {
                                "type": "user"
                        }
```
along with these sections immediately following (in linux)
```
                "uidMappings": [
                        {
                                "containerID": 3382,
                                "hostID": 3382,
                                "size": 1
                        }
                ],
                "gidMappings": [
                        {
                                "containerID": 9996,
                                "hostID": 9996,
                                "size": 1
                        }
                ],
 ```
and then got an error
```
ERROR  : Failed to set effective UID to 0
```

**Comment by DrDaveD** [comment]
Oh this may be because the oci mount command actually bind mounts from the sif image and creates an overlay.  There does not appear to be a way to create an ordinary filesystem oci bundle from an image, and I think that would be quite important.

**Comment by cclerget** [comment]
Hi @DrDaveD , actually all OCI commands requires to be root, to run OCI commands unprivileged it will requires more work. Yes there is no package/feature to unpack filesystem from SIF image in a directory but definitively something to add

**Comment by DrDaveD** [comment]
That's very disappointing.  I think the primary reason for Singularity's popularity is the fact that it enables unprivileged containers (with or without setuid root), so having a new big feature set without that ability greatly lessens its usefulness.  There are other oci command implementations, so what value does a Singularity implementation add?  Please try to be clear about setting expectations in the release announcements and error messages, and I guess I will just wait until the ability to use oci unprivileged becomes available.

**Comment by cclerget** [comment]
Hi @DrDaveD , I will update help/error message to reflect root privilege requirement. Actually rootless mode is not supported, OCI runtime engine is completely separated from Singularity runtime engine, that's why there is no rootless support actually, it was originally developed to tightly work with https://github.com/sylabs/singularity-cri for kubernetes integration, as kubernetes run as root, there was no requirement for rootless support. That's being said, rootless mode will be supported as well as commands to create bundle without root privileges.

**Comment by DrDaveD** [comment]
@cclerget The 'singularity oci mount' Usage after #2715 still does not show that an image and bundle name are required.

**Comment by DrDaveD** [comment]
'singularity oci umount' has a similar problem.  The description on it also doesn't look right, "Umount delete bundle".   Presumably it should be "Unmount bundle".  All the other Usages seem OK.
