### ISSUE TITLE
Cache clean doesn't work

### ISSUE THREAD

**Issue by phpHavok** [apptainer/singularity#2694]
## Version of Singularity:

3.1.0-rc1

### Expected behavior

`singularity cache clean` should clear out `~/.singularity/cache`.

### Actual behavior

It doesn't.

### Steps to reproduce behavior

```
[jacob@saturn .singularity]$ singularity cache
Usage:
  singularity [global options...] cache <subcommand> <command>

Available Commands:
  clean       Clean your local Singularity cache
  list        List your local Singularity cache

[jacob@saturn .singularity]$ singularity cache list
NAME                   DATE CREATED           SIZE             TYPE
ionic_4.10.1.sif       2019-02-11 14:12:00    582.69 Mb        library
[jacob@saturn .singularity]$ singularity cache clean
[jacob@saturn .singularity]$ singularity cache list
NAME                   DATE CREATED           SIZE             TYPE
ionic_4.10.1.sif       2019-02-11 14:12:00    582.69 Mb        library
```

**Comment by WestleyK** [comment]
By default `cache clean` will only clean `blob` cache, try doing:

```
$ singularity cache clean --all
```

<br>

This was sorta a last minute decision to only clean blob cache by default...

**Comment by phpHavok** [comment]
> By default `cache clean` will only clean `blob` cache, try doing:
> 
> ```
> $ singularity cache clean --all
> ```

That worked, thanks! Sorry, I didn't realize the semantics of cache clean.

**Comment by WestleyK** [comment]
No problem! Happens to me too! :+1:
