### ISSUE TITLE
Step missing in singularity 3 quick install instructions

### ISSUE THREAD

**Issue by ps-account** [apptainer/singularity#2695]
## Version of Singularity:
3.0.3

### Expected behavior
On freshly installed system, e.g ubuntu 18.04:

Go to :
https://www.sylabs.io/guides/3.0/user-guide/quick_start.html
follow instructions.
Singularity is installed.

### Actual behavior
go not found at sudo make step in:
https://www.sylabs.io/guides/3.0/user-guide/quick_start.html#compile-the-singularity-binary

$ tail -n2 ~/.bashrc
export GOPATH=${HOME}/go
export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin
$ which go
/usr/local/go/bin/go
$ sudo -E  go
sudo: go: command not found

### Steps to ~~reproduce~~ solve behavior

Please add a line to quick install manual: 
sudo requires to put `/usr/local/go/bin` as secure_path in `/etc/sudoers`, via visudo

If that is done correctly sudo can find go and the installation can be completed.

**Comment by jmstover** [comment]
I'm going to comment, but I'll let others decide on how they want to proceed with this ... 

Upstream sudo ships without `secure_path` in the example `sudoers` file.

So, this is a distribution choice to set when distributing. For example, on the distro I use, `secure_path` isn't set, so the users PATH carries through. No need to add it if you're using the default `sudoers` file.

**Comment by mem** [comment]
From what @jmstover 	says the problem is with this step:

```
$ ./mconfig && \
    make -C builddir && \
    sudo make -C builddir install
```

I might have inadvertently fixed this issue at some point, since now the full path to Go is recorded when mconfig runs:

```
$ grep -F 'GO := ' builddir/Makefile
GO := /home/mem/devel/go/go-1.12/bin/go
```

and I believe everything is using that variable in order to access the Go compiler.

Can someone please verify?

**Comment by dtrudg** [comment]
Fixed for me with a `go` not on `PATH` under sudo..

```
dave@piran/s/S/G/singularity> sudo go
sudo: go: command not found
dave@piran/s/S/G/singularity> sudo make -C builddir install
make: Entering directory '/scratch/Sylabs/Git/singularity/builddir'
 INSTALL /usr/local/bin/singularity
 INSTALL /usr/local/etc/bash_completion.d/singularity
 INSTALL /usr/local/etc/singularity/singularity.conf
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/dhcp
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/host-local
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/static
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/bridge
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/host-device
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/ipvlan
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/loopback
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/macvlan
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/ptp
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/vlan
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/bandwidth
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/firewall
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/flannel
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/portmap
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/tuning
 INSTALL /usr/local/libexec/singularity/bin/starter
 INSTALL SUID /usr/local/libexec/singularity/bin/starter-suid
 DONE
make: Leaving directory '/scratch/Sylabs/Git/singularity/builddir'
```
