### ISSUE TITLE
I cannot make option --apply-cgroups work with instances

### ISSUE THREAD

**Issue by j-guitart** [apptainer/singularity#2696]
## Version of Singularity:

v3.1.0-rc1

### Expected behavior

Instance should be created successfully and with the appropriate resource limits (as specified in the cgroups configuration file)

### Actual behavior

Command fails and debug info is as follows:
...
DEBUG   [U=0,P=2]          Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=2]          Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=2]          Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=2]          Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=0,P=20169]      CleanupContainer()            Cleanup container
ERROR   [U=0,P=20169]      Master()                      container cleanup failed: no instance found with name myinstance
FATAL   [U=0,P=20169]      Master()                      container creation failed: Failed to apply cgroups ressources restriction: open /singularity/20170: no such file or directory

FATAL   [U=0,P=20146]      execStarter()                 failed to start instance: exit status 1

### Steps to reproduce behavior

I'm running the next command. I use the default cgroups configuration file:

sudo singularity --debug instance start --apply-cgroups /singularity/etc/singularity/cgroups image.sif myinstance

I've also tried (with the same result):

sudo singularity --debug instance start --apply-cgroups /singularity/etc/singularity/cgroups/cgroups.toml image.sif myinstance

**Comment by cclerget** [comment]
Hi @j-guitart , fix pushed in #2714 , if you can it a try. Thanks !
