### ISSUE TITLE
Shub Image Caching

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#2697]
## Version of Singularity:

```
$ singularity version
3.0.3-728.g2fb5f20e
```

### Expected behavior

Repeated pull to the same Shub image should use a cached image.

### Actual behavior

Repeated pull to the same Shub image download the same image multiple times.

### Steps to reproduce behavior

run `singularity pull shub://vsoch/singularity-hello-world:master` twice

Since the shub API doesn't give an image hash in its manifest, we can't use that to uniquely identify the image in out cache. So, we need another method know if an image in a shub registry is currently cached.

**Comment by michaelmoore10** [comment]
@ikaneshiro - I've submitted PR #2776 to address Shub caching.  This has been built against this morning's 3.1.0 release and I have tested it with several different pulls from our internal sregistry with great results.  Please let me know if you see any further changes that should be done

-Mike
