### ISSUE TITLE
Cannot run singularity container without root on Centos 6

### ISSUE THREAD

**Issue by isaiahtaylor** [apptainer/singularity#2698]
## Version of Singularity:

```bash
$ singularity --version
singularity version 3.0.3-582.ge13861e
```

```bash
$ uname -a
Linux [domain name redacted] 2.6.32-754.10.1.el6.x86_64 #1 SMP Tue Jan 15 17:07:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ cat /etc/centos-release
CentOS release 6.10 (Final)
```

```conf
$ cat singularity.conf
...
allow setuid = no
...
```

### Expected behavior

I expected to be able to run Singularity in an HPC environment without root.

### Actual behavior

```bash
$ singularity --debug shell alpline-latest.sif
VERBOSE [U=1154,P=24162] print() Set messagelevel to: 5
DEBUG [U=1154,P=24162] init() PIPE_EXEC_FD value: 8
VERBOSE [U=1154,P=24162] init() Container runtime
VERBOSE [U=1154,P=24162] is_suid() Check if we are running as setuid
DEBUG [U=1154,P=24162] init() Read json configuration from pipe
DEBUG [U=1154,P=24162] init() Set child signal mask
DEBUG [U=1154,P=24162] init() Wait completion of stage1
DEBUG [U=1154,P=24174] set_parent_death_signal() Set parent death signal to 9
VERBOSE [U=1154,P=24174] init() Spawn stage 1
VERBOSE [U=1154,P=24174] startup() Execute stage 1 
DEBUG [U=1154,P=24174] Stage() Entering stage 1 
DEBUG [U=1154,P=24174] Init() Entering image format intializer 
DEBUG [U=1154,P=24174] Init() Check for image format sif 
DEBUG [U=1154,P=24162] init() Create socketpair for master communication channel
DEBUG [U=1154,P=24162] cleanup_fd() Check file descriptor /proc/self/fd/3 pointing to /dev/urandom 
DEBUG [U=1154,P=24162] cleanup_fd() Check file descriptor /proc/self/fd/4 pointing to [eventpoll] 
DEBUG [U=1154,P=24162] cleanup_fd() Check file descriptor /proc/self/fd/5 pointing to [redacted]/sing-build/alpine_latest.sif 
VERBOSE [U=1154,P=24162] user_namespace_init() Create user namespace 
ERROR [U=1154,P=24162] user_namespace_init() Failed to create user namespace
```

### Steps to reproduce behavior

* Download and make Singularity on Centos 6
* Attempt to pull and run an image

## Question

Is CentOS 6 not supported? Has anyone had any luck with this?

**Comment by cclerget** [comment]
Hi @iptaylortechnical , it won't work on CentOS 6 rootless feature is only available since CentOS 7

**Comment by isaiahtaylor** [comment]
@cclerget we were able to make it work by using `allow setuid = yes` and setting a sticky bit for `/libexec/bin/starter-suid` so that it always runs as root. Is this is already in the documentation? It might be useful to add that to the main installation page.

**Comment by DrDaveD** [comment]
@iptaylortechnical that's the default installation mode, so there shouldn't be any need to specifically document it.  Something in your local processes must have changed those two things.

**Comment by isaiahtaylor** [comment]
@DrDaveD you're saying `make install` sets that sticky bit? If so, would you have interest in a PR to alert the user that they need to have someone with privileges set that sticky bit if `make install` is not run with sudo? In our particular application, the we installed singularity to an unprivileged install location, and went back later to own `capabilities.json` as root. Thanks.

**Comment by DrDaveD** [comment]
Correct, sudo make install as in the instructions sets the sticky bit.  

I'm not an owner of the package so I can't give you a definitive answer about a PR, but in my opinion that's probably not a good idea because on newer kernels (including on el7) singularity can be run quite effectively without setuid, at the cost of not being able to use a couple of features that are not always needed.

**Comment by isaiahtaylor** [comment]
@cclerget would you be interested in a documentation PR? We've got it working perfectly on CentOS 6 with the sticky bit, but we had to dig around to find that.

**Comment by cclerget** [comment]
Indeed `sudo make -C builddir install` set setuid bit on `starter-suid` binary during installation.

Thanks @iptaylortechnical ! Current documentation covers installation steps which can be found [here](https://github.com/sylabs/singularity/blob/master/INSTALL.md) and [here](https://www.sylabs.io/guides/3.0/user-guide/installation.html).

**Comment by cclerget** [comment]
Closing, feel free to re-open it if needed
