### ISSUE TITLE
Singularity with local installation cannot run because of "FATAL:   while setting user capabilities: capability config file not owned by root"

### ISSUE THREAD

**Issue by alazzaro** [apptainer/singularity#2699]
## Version of Singularity:

Current master, downloaded with `git clone https://github.com/sylabs/singularity.git`

### Expected behavior

It should run the sandbox image with `singularity run myimage`

### Actual behavior

I get the message: `FATAL:   while setting user capabilities: capability config file not owned by root`

### Steps to reproduce behavior

1) download singularity with `git clone https://github.com/sylabs/singularity.git`
2) following the instructions at https://github.com/sylabs/singularity/issues/2570, compile with `./mconfig --without-suid --prefix=singularity ; make -C builddir ; make -C builddir install`

The problem goes away if I do change the owenership of the file `singularity/etc/singularity/capability.json` to be owned by root (of course, I can do that only if I have sudo priviligies...)

**Comment by cclerget** [comment]
Hi @alazzaro , PR #2701 submitted which should fix the issue, if you can give it a try. Thanks !

**Comment by alazzaro** [comment]
Yes, it does. Thanks for the quick fix!

**Comment by alazzaro** [comment]
BTW, would it be possible to build the image without sudo?
I get:

singularity build --sandbox myimg myimg.def
FATAL:   You must be the root user to build from a Singularity recipe file

**Comment by cclerget** [comment]
No unfortunately this is not possible because package managers requires root privileges

**Comment by WestleyK** [comment]
@alazzaro, It is possible to build a container (from a def file) without root access, by using the [remote builder](https://cloud.sylabs.io/builder). But, if you want to build on your host, you need root access.
