### ISSUE TITLE
"singularity" is hard to spell

### ISSUE THREAD

**Issue by soichih** [apptainer/singularity#270]
I really like the name singularity, but I've always thought it's hard to type - especially over and over. 

Can we rename it to something shorter? 
- singul
- sing
- s8y :)

etc..  please close this issue if it's a dumb idea.

(I wouldn't have mentioned this until someone actually installed singularity on a slightly misspelled path and broke our installation by correcting the directory name without recompiling)

**Comment by vsoch** [comment]
Thanks for the suggestion! This is sort of personal preference, so I'll give my 0.02. I think most users will likely use shortcuts to reuse old commands, so typing is trivial. More salient, using the whole term seems important for the singularity brand. It's an open source tool, but it still carries with it an identity. I've noticed tools that try to do a "short and trendy" thing don't carry the same feeling of professionalism, although that's just my opinion!

**Comment by chrisgorgo** [comment]
I vote for
"singularity-but-not-that-ai-thing-that-ray-kurzweil-has-been-rambling-about-for-years".
I admit it's a bit on the longer side, but on the plus side it would be
easy get a .org domain for it ;)

**Comment by gmkurtzer** [comment]
@chrisfilo OMG... I am seriously laughing hysterically over that! Do you know how many times I've asked if Singularity relates to "the singularity"? LOTS! No, Singularity is not the Terminator's Judgement Day. ;)

I actually also tend to typo Singularity even still, but I would count on user prefs creating a wrapper or an alias for it if they really want to. I actually did consider a `srun` command, but @jette beat me to it!
