### ISSUE TITLE
%files is not working

### ISSUE THREAD

**Issue by samcmill** [apptainer/singularity#2707]
### Expected behavior

Specified file is copied into the container image.

### Actual behavior

Specified file is not copied into the container image.

### Steps to reproduce behavior

```
# cat Singularity.def
BootStrap: docker
From: ubuntu:16.04

%files
    hello.c /var/tmp/hello.c

%post
    ls -l /var/tmp/hello.c

# ls -l hello.c
-rw-r--r--. 1 root root 63 Feb 13 22:49 hello.c

# singularity build hello.sif Singularity.def
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:7b722c1070cdf5188f1f9e43b8413157f8dfb2b4fe84db3c03cb492379a42fcc
Skipping fetch of repeat blob sha256:5fbf74db61f1459176d8647ba8f53f8e6cf933a2e56f73f0e8da81213117b7e9
Skipping fetch of repeat blob sha256:ed41cb72e5c918bdbd78e68f02930a3f1cf1d6079402b0a5b19de8508e67b766
Skipping fetch of repeat blob sha256:7ea47a67709ebea8efed59fbda703dbd00a0d2cae7e2808959744bfa30bfc0e9
Copying config sha256:288b5aca25f70512e5874c289a8a216b60808ecc47f687fa502fd848e5c3f875
 2.42 KiB / 2.42 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Copying hello.c to /var/tmp/hello.c
INFO:    Running post scriptlet
+ ls -l /var/tmp/hello.c
ls: cannot access '/var/tmp/hello.c': No such file or directory
FATAL:   post proc: exit status 2
FATAL:   While performing build: while running engine: exit status 255
```

**Comment by jmstover** [comment]
@samcmill 

Can you change the location to somewhere else, like just `/hello.c` ?

In `%post` we're going to act as if we're running the container, so `/tmp`, and `/var/tmp` will be bind mounted from the host.  You can verify this behavior by doing:

On host:
`touch /var/tmp/blahblah`

In `%post` section:
`    ls -l /var/tmp/blahblah`

So, the `/var/tmp/hello.c` you're copying in the `%files` section, is being hidden by the bind mount that happens.

**Comment by samcmill** [comment]
The diagnosis by @jmstover is correct.  However...

This is a behavior change from Singularity 2.x.  In 2.x, only `/tmp` was bind mounted from the host, not `/var/tmp`.  

Further in 2.x, even though `/tmp` was bind mounted from the host, the bind mount occurred before `%files` was evaluated, so files could still be staged in `/tmp`.

**Comment by samcmill** [comment]
By the way, this works as expected in 3.0.2.  So something broke between 3.0.2 and 3.1.0-rc2.

**Comment by cclerget** [comment]
Hi @samcmill , if you can give a try by applying fix in #2713. Thanks !

**Comment by ikaneshiro** [comment]
@samcmill @cclerget Sorry I didn't see this comment before merging, if there's still an issue please reopen the issue.

**Comment by samcmill** [comment]
@ikaneshiro @cclerget Thanks, confirmed #2713 fixes this issue.
