### ISSUE TITLE
How to convert SIF to sandbox?

### ISSUE THREAD

**Issue by renganxu** [apptainer/singularity#2719]
## Version of Singularity:

3.1.0-rc2

This is a question, not an issue of Singularity. I want to write to the Singularity container pulled from Nvidia GPU Cloud Docker image. Since the default image format is SIF which is read-only, I cannot install anything in the image. Here are some possible ways I think to solve this issue:

1. pull the Docker image to writable sandbox directory instead of SIF format. Is this possible. I used the command "sregistry pull mxnet:18.11-py3" to get the SIF format image. Is it possible to get writable sandbox using sregistry and how?

2. convert the SIF to writable sandbox directory. Is this possible? The user guide only introduced how to convert sandbox to SIF but didn't mention how to convert in opposite direction.

If none of the above two solutions work, any other suggestions to solve this problem? Thanks.

**Comment by jmstover** [comment]
Hi @renganxu ,

  To convert a SIF to a sandbox you should just need to do:

```
$ sudo singularity build --sandbox my_sbox my_image.sif
```

  You'll need to use `sudo` (or be root) because we mount the SIF image when converting currently. And need to be root to do that.

**Comment by renganxu** [comment]
Thanks @jmstover for the very quick reply. I just tried and it works. Thanks very much!

**Comment by jmstover** [comment]
:+1: ... Let us know if you have any other questions.
