### ISSUE TITLE
Conditionally include dependent programs with Singularity installation

### ISSUE THREAD

**Issue by gmkurtzer** [apptainer/singularity#2724]
Dependent programs should be optionally installed in a Singularity specific directory ($libexecdir perhaps), so we know what options are available that maybe version specific (e.g. mksquashfs in #2717).

**Comment by GodloveD** [comment]
Need to have a discussion I think about pros and cons of doing this.

**Comment by gmkurtzer** [comment]
The keyword was "optionally". ;-)

I agree that there should be a thread that talks about the outcome of the conditionals and what is default.

**Comment by gmkurtzer** [comment]
#2352 is more reasoning on why this is necessary.

**Comment by GodloveD** [comment]
After discussion, sounds like this is super helpful.  Just need to figure out how to implement.

**Comment by GodloveD** [comment]
After further discussion we've decided to add a check to mconfig to make sure that squashfs-tools is installed **in one of the directories that we expect**.  Will also check the version.  If squashfs-tools is not installed in one of the directories we expect a warning will be printed to user.   If a version of squashfs-tools is installed that needs an additional flag to use gzip, then we will invoke that flag.
