### ISSUE TITLE
Using user namespaces in setuid mode has advantages

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2727]
Currently in the singularity setuid workflow, user namespace mappings are not used.  Every id inside the container is the same outside the container.  The position of the LXC project in [this posting](https://brauner.github.io/2019/02/12/privileged-containers.html) is that mapping root inside a container to root outside constitutes a privileged container and is inherently unsafe.  Singularity gets around this by starting the container with the user's process id and using PR_SET_NO_NEW_PRIVS so the kernel will prevent the container from ever gaining more privileges.

I propose that when user namespaces are available, that singularity by default use them even in the setuid workflow, so all user ids other than the original user are mapped to an unprivileged id outside the container.  This would be an extra layer of security protection.  It also has an advantage of enabling unprivileged use of the nsenter command to attach to an existing namespace, for example with this command when singularity is invoked with -c -i -p
```
eval nsenter -t $1 -U --preserve-credentials -m -i -p -r -w /usr/bin/env -i $(xargs -0 bash -c 'printf "%q\n" "$@"' -- </proc/$1/environ) /bin/bash
```
where $1 is the process id with the namespace that is being joined.

The disadvantage that I can think of is that an ls -l of files will show everything not owned by the user to be owned by the unprivileged id 65534 (nfsnobody on el7, nobody on debian).   I don't think that will bother most cases, but in case it does there could be an option to use the old behavior.

**Comment by cclerget** [comment]
@DrDaveD To be sure I understand correctly, user namespace could also use image file via loop devices ?

**Comment by DrDaveD** [comment]
Yes, certainly.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by DrDaveD** [comment]
Yes I think this should continue to be discussed.

**Comment by pedroalvesbatista** [comment]
@DrDaveD We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by DrDaveD** [comment]
I don't think this is as important now that setuid is becoming less and less necessary.  Closing.
