### ISSUE TITLE
[docker] image-handler.sh: namespace is stripped

### ISSUE THREAD

**Issue by flx42** [apptainer/singularity#273]
https://github.com/singularityware/singularity/blob/58efd108c480e148717d0ffa41531ea38e31ee2e/libexec/image-handler.sh#L53
This is only keeping the image name and tag, stripping everything before. Thus `nvidia/cuda` will actually end up as `library/cuda` by default.

Simple patch would be to do the same as here:
https://github.com/singularityware/singularity/blob/58efd108c480e148717d0ffa41531ea38e31ee2e/libexec/helpers/image-import.sh#L56

``` diff
diff --git a/libexec/image-handler.sh b/libexec/image-handler.sh
index 93eaa06..992e663 100644
--- a/libexec/image-handler.sh
+++ b/libexec/image-handler.sh
@@ -50,7 +50,7 @@ case "$SINGULARITY_IMAGE" in
         fi
     ;;
     docker://*)
-        NAME=`basename "$SINGULARITY_IMAGE"`
+        NAME=`echo "$SINGULARITY_IMAGE" | sed -e 's@^docker://@@'`
         if [ -z "${SINGULARITY_CACHEDIR:-}" ]; then
             SINGULARITY_CACHEDIR="/tmp"
         fi
```

**Comment by gmkurtzer** [comment]
Good catch, added in [master 765522d].

Thanks!
