### ISSUE TITLE
Incorrect help for oci mount and umount

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2735]
## Version of Singularity:

3.1.0-rc3

### Expected behavior

Accurate help messages

### Actual behavior

singularity oci mount -h and singularity oci umount -h do not show the full Usage.  They're missing the parameters.  Also, the description of oci umount  is incorrect, it should probably be "Unmount bundle".   

First mentioned in #2689.

### Steps to reproduce behavior

See above.

**Comment by cclerget** [comment]
@DrDaveD partially fixed in #2733. Regarding "Unmount bundle" message, there is an unmount step but just wanted to highlight that bundle is also deleted. Will update for `Unmount and delete bundle`, need to enhance package a bit
