### ISSUE TITLE
Automatically choose correct architecture for build step

### ISSUE THREAD

**Issue by mxmlnkn** [apptainer/singularity#2744]
## Version of Singularity:

Singularity 3.0.2

### Expected behavior

Should download images for build step with correct architecture automatically.

### Actual behavior

It doesn't ...

### Steps to reproduce behavior

When I do something like `singularity build debian.sif docker://debian:9` on a non `x86_64` architecture, there will be a bad exec error as shown in #1488 and #1836. Ignoring the fact that most singularity hub images don't even seem to offer ppc64le alternatives (not even for debian?), it is necessary to manually specify the architecture with:

    export SINGULARITY_DOCKER_ARCHITECTURE=$( uname -m )
    singularity build debian.sif docker://debian:9

In my opinion this option should also be available for non docker images and it should be set automatically to `uname -m` for the build step as I don't see any case where it would make sense as building a different architecture is not possible and least to #1488. For singularity pull however, specifying a different architecture [can make sense](https://github.com/sylabs/singularity/issues/1836#issuecomment-465488391) and should not be set automatically!

**Comment by dtrudg** [comment]
Singularity `--pull` now has an `--arch` option, and a build will use the host architecture by default.

Closing - please let us know if there is any further issue on the latest version of Singularity.
