### ISSUE TITLE
bash [tab] completion file not updated for  singularity 3.*

### ISSUE THREAD

**Issue by al3x609** [apptainer/singularity#2754]
## Version of Singularity:

singularity --version
singularity version 3.1.0-rc4.dirty

### Expected behavior

[alex@yaje singularity]$ singularity instan

> this should not autocomplete with dot (.) mode,  because we have 3.* version, not 2.* 

### Actual behavior
[tab completion for instances show old config for singularity 2.*]

[alex@yaje singularity]$ singularity instance
instance.list   instance.start  instance.stop   

### Steps to reproduce behavior
e.g
set tab after this for completion
$ singularity instan

**Comment by jmstover** [comment]
@al3x609 

A tab completion file should get installed under $sysconfdir/bash_completion.d/singularity ... So, say you set `--prefix=/usr/local`, then that location would be:  `/usr/local/etc/bash_completion.d/singularity`

**Comment by al3x609** [comment]
thanks, it works.
