### ISSUE TITLE
[Question] What is the default signal send it for  "singularity instance stop" command?

### ISSUE THREAD

**Issue by al3x609** [apptainer/singularity#2758]
## Version of Singularity:

singularity version 3.1.0-rc4.dirty

I have running a startscript in my def file like to:

%startscript
exec runscript.sh &

I need trap a specific signal for a clean up function in the script but i can not trap any signal propagated.

**Comment by cclerget** [comment]
Hi @al3x609 , by default SIGINT is sent, you don't need to add `&`, `exec runscript.sh` is fine unless you want execute another process after

**Comment by al3x609** [comment]
@cclerget  thank you. 👍
