### ISSUE TITLE
mconfig fails when looking for openssl

### ISSUE THREAD

**Issue by toddcreasy** [apptainer/singularity#2766]
## Version of Singularity:

3.0.3 (CentOS 7)

### Expected behavior

Configure singularity fully before running "make"

### Actual behavior

=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host `ar' path... /apps/anaconda3/x86_64-conda_cos6-linux-gnu/bin/ar
 checking: host `ld' path... /apps/anaconda3/x86_64-conda_cos6-linux-gnu/bin/ld
 checking: host `ranlib' path... /apps/anaconda3/x86_64-conda_cos6-linux-gnu/bin/ranlib
 checking: host `objcopy' path... /apps/anaconda3/x86_64-conda_cos6-linux-gnu/bin/objcopy
 checking: target C compiler... cc
 checking: target C++ compiler... c++
 checking: target `ar' path... /apps/anaconda3/x86_64-conda_cos6-linux-gnu/bin/ar
 checking: target `ld' path... /apps/anaconda3/x86_64-conda_cos6-linux-gnu/bin/ld
 checking: target `ranlib' path... /apps/anaconda3/x86_64-conda_cos6-linux-gnu/bin/ranlib
 checking: target `objcopy' path... /apps/anaconda3/x86_64-conda_cos6-linux-gnu/bin/objcopy
 checking: host compiles static binaries... yes
 checking: target compiles static binaries... yes
 checking: host os type... unix
 checking: host architecture... x86_64
 checking: target architecture... x86_64
 checking: host architecture word size... 64
 checking: target architecture word size... 64
=> running project specific checks ...
 checking: namespace: CLONE_NEWPID... yes
 checking: namespace: CLONE_FS... yes
 checking: namespace: CLONE_NEWNS... yes
 checking: namespace: CLONE_NEWUSER... yes
 checking: namespace: CLONE_NEWIPC... yes
 checking: namespace: CLONE_NEWNET... yes
 checking: namespace: CLONE_NEWUTS... yes
 checking: namespace: CLONE_NEWCGROUP... no
 checking: feature: NO_NEW_PRIVS... yes
 checking: feature: MS_SLAVE... yes
 checking: feature: MS_REC... yes
 checking: feature: MS_PRIVATE... yes
 checking: user capabilities... no
 checking: header linux/securebits.h... no
 checking: header linux/capability.h... yes
 checking: function setns... no
 checking: libssl+headers... no

Unable to find the libssl, need package openssl-devel (libssl-dev on Debian/Ubuntu)

However, openssl is installed. I do have a conda installation and openssl is actually installed on the local system AND in my anaconda directories. However, I still get this error.

Looking more closely in the checks project.chk, this is what is failing:

printf "#include <openssl/sha.h>\nint main() { }" | cc -x c -o /dev/null -lcrypto - >/dev/null
<stdin>:1:10: fatal error: openssl/sha.h: No such file or directory
compilation terminated.

ANY idea why it can't find openssl/sha.h. I know it's there. I've searched and searched but can't find a reason why this is happening.

Thanks

**Comment by jscook2345** [comment]
Where is your `openssl/sha.h` header located? The compiler will look for the header file in standard directories or directories provided to it via flags. If none of those have the header file the compiler will not know where to find it and will error out.

**Comment by toddcreasy** [comment]
I actually have it in 2 locations. I don't have root on the box so I'm using anaconda. The compiler cc is under anaconda:

/apps/anaconda3/include/openssl/sha.h
/usr/include/openssl/sha.h

I've also noticed in builddir/config.h, it's pointing to /usr/local/include which is not correct but that might be referencing where it will be installed.

#define INCLUDEDIR "/usr/local/include"
#define OLDINCLUDEDIR "/usr/include"

If I can provide an env variable either through export or manually to mconfig, that's fine but I've tried some things and it's not working.

**Comment by jscook2345** [comment]
@toddcreasy 

Does conda have a way to generate a `CFLAGS` and `LDFLAGS` entry for the libraries it installed?

Is `openssl` library also installed under `/apps/anaconda3/` ?

If so, you can define the `CFLAGS` and/or `LDFLAGS` in `mlocal/frags/common_opts.mk` *before* running `./mconfig` and it should pick them up.

**Comment by jscook2345** [comment]
@toddcreasy 

Any info you can provide on my previous comment?

**Comment by toddcreasy** [comment]
@jscook2345 

Sorry for not responding. I tried and it didn't work. I've moved on from this problem for now. I might pick it up later but I'll close this issue.
