### ISSUE TITLE
e2e testing for multistage builds 

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2769]

**Comment by GodloveD** [comment]
make sure that multistage builds are fully e2e tested, exercised, etc.

**Comment by jscook2345** [comment]
@ikaneshiro Which release are you targetting for multistage builds?

**Comment by ikaneshiro** [comment]
@jscook2345 3.2. Ill update the tags and release

**Comment by jscook2345** [comment]
@ikaneshiro 

Is there a PR associated with this work?

**Comment by ikaneshiro** [comment]
@jscook2345 no this has not been started yet
