### ISSUE TITLE
Rearrange auth-token handling

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2774]
Currently auth-tokens are handled in a `cobra.Cmd` `PreRun` function. This causes auth tokens to always be searched for during any command which could *ever* need an auth token. We should rearrange auth-token management into a package `pkg/auth` (?) so that in `internal/app/singularity` we can grab an auth token at a specific time.

**Comment by bauerm97** [comment]
Related to #2687

**Comment by ikaneshiro** [comment]
A lot of the `authtoken` behavior is tightly coupled with the CLI and changing it would require a CLI change which should be done over the course of a couple minor releases.

I propose the following steps:
	- we integrate the remote endpoint management into the CLI leaving much of the `authtoken` behavior as is
	- Depriciate `tokenfile`, `tokenfile` flag and `SYLABS_TOKEN` in 3.2
	- Remove these flags completely in 3.3 and have remote be the sole manager of endpoints and tokens apart from subcommand specific CLI flags

@tri-adam @bauerm97 Thoughts?

**Comment by tri-adam** [comment]
I like that approach!

**Comment by ikaneshiro** [comment]
After second thought I think leaving `SYLABS_TOKEN` envvar is ok. I can see a case where having it stored in the environment would be easier to work with
