### ISSUE TITLE
Issue with --home and --pwd

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#2778]
## Version of Singularity:

3.1.0-29.ga78434c

### Expected behavior

When using `--home /some/path:/dest/path --pwd /dest/path` ... We change to `/dest/path` without issue... 

```
$ sudo singularity exec -H /home/gmk:/home/test --pwd /home/test test.sif pwd
/home/test
```

### Actual behavior

```
$ sudo singularity exec --pwd /home/test -H /home/gmk:/home/test test.sif pwd
WARNING: Could not set container working directory /home/test: chdir /home/test: no such file or directory
/home/test
```

### Steps to reproduce behavior

Use `--pwd` and `-H` in conjunction with each other.... for example:

```
$ singularity exec --pwd /Users/fooo -H /etc:/Users/fooo test.sif pwd
WARNING: Could not set container working directory /Users/fooo: chdir /Users/fooo: no such file or directory
/Users/fooo
```

**Comment by al3x609** [comment]
this works with 

`$ singularity exec --pwd /Users/fooo -H /etc:/Users/fooo test.sif bash -c 'pwd'`

**Comment by jmstover** [comment]
Not for me from 3.1.0-rc4 

```
$ singularity exec --pwd /Users/fooo -H /etc:/Users/fooo ~/lolcow.sif bash -c 'pwd'
WARNING: cound not set container working directory /Users/fooo: chdir /Users/fooo: no such file or directory
/Users/fooo
```

**Comment by al3x609** [comment]
I have this version.
$ singularity version
3.1.0-29.ga78434c

**Comment by jscook2345** [comment]
Found the same issue with `3.1.0-rc4.dirty`.

**Comment by cclerget** [comment]
@jmstover @jscook2345 It works but the warning message reports a false error

**Comment by gmkurtzer** [comment]
Thanks for moving forward with fixing this invalid warning, it has been bugging me!
