### ISSUE TITLE
INSTALL.md should have steps for installing from release tarball

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2779]
## Version of Singularity:

master branch

In the `INSTALL.md`, we do not document how to install from the release tarball under `https://github.com/sylabs/singularity/releases/latest`.

We should include that and additionally document what all the release assets are and which ones should be used.

**Comment by jscook2345** [comment]
This is mentioned in the admin-docs, but whatever is placed here should also be pushed to an admin-docs issue.

**Comment by mem** [comment]
I think part of the problem here is that build time we hardcode a couple of paths, so the resulting binary can only be installed in a specific location.
