### ISSUE TITLE
Search --library not working with singularity-hub.org or hub.docker.com

### ISSUE THREAD

**Issue by mxmlnkn** [apptainer/singularity#2780]
## Version of Singularity:

3.0.1

### Expected behavior

Would be nice if e.g. `singularity search --library https://singularity-hub.org/ debian` or `singularity search --library https://hub.docker.com/ debian` showed actual results just like:

```
singularity search --library https://library.sylabs.io debian
No users found for 'debian'

Found 1 collections for 'debian'
	library://tru/debian9

Found 2 containers for 'debian'
	library://dtrudg/linux/debian
		Tags: 9 9.4 latest stretch testing unstable
	library://library/default/debian
		Tags: 7 8 9 latest
```

### Actual behavior

Outputs errors like:

```
singularity search --library https://singularity-hub.org debian
    FATAL:   Couldn't search library: error decoding reesults: unexpected end of JSON input
singularity search --library https://hub.docker.com debian
    FATAL:   Couldn't search library: error decoding reesults: invalid character '<' looking for beginning of singularity search --library https://dummy debian
    FATAL:   Couldn't search library: error making request to server:
    Get https://dummy/v1/search?value=debian: dial tcp: lookup dummy: Temporary failure in name resolution
```

Looking at the last output it seems to only work with libraries which have a search request mask matching:  `<uri>/v1/search?value=<searc>`. So, it makes sense that it does not work with docker hub.

Was it ever intended to work with docker hub or singularity-hub.org? If not, what was this option intended to work with and can support for these two be added?

**Comment by jscook2345** [comment]
This is a container library specific feature, so it will only work for our cloud library at the moment.

As for the enhancement, ping @ikaneshiro !

**Comment by tri-adam** [comment]
I'd suggest we would probably want to explicitly declare the protocol if this command is extended to search heterogenous container stores. `library://`, `shub://` etc.

**Comment by mem** [comment]
Something like `singularity search debian library://` (defaults to an internal value for the host name) and `singularity search debian library://library.sylabs.io` (for custom libraries). The same for docker, shub, etc (assuming there's a way to search other libraries). Basically handle this the same way we handle pulls.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@mxmlnkn Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Pending issues from the old repo are moved to the new repo (https://github.com/apptainer/apptainer/issues/1391) and cleaned from the old, retired repo
