### ISSUE TITLE
What commands and flags are we testing? 

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2783]
## singularity
* [ ] `singularity`
* [ ] `singularity --debug (-d)`
* [ ] `singularity --help (-h)`
* [x] `singularity --quiet (-q)`
* [ ] `singularity --silent (-s)`
* [ ] `singularity --tokenfile <string> (-t)`
* [ ] `singularity --verbose (-v)`
* [ ] `singularity --version`

## apps
* [ ] `singularity help apps`
* [ ] `singularity apps`
* [ ] `singularity apps --help (-h)`

## build
* [ ] `singularity help build`
* [ ] `singularity build`
* [x] `singularity build <sif> <definition>`
* [x] `singularity build <sif> <sandbox>`
* [x] `singularity build <sif> <image>`
* [x] `singularity build <sif> <library uri>`
* [x] `singularity build <sif> <docker uri>`
* [x] `singularity build <sif> <shub uri>`
* [ ] `singularity build --help (-h)`
* [ ] `singularity build --builder <string> <sif> <spec>`
* [ ] `singularity build --detatched (-d) --remote (-r) <sif> <spec>`
* [ ] `singularity build --docker-login <sif> <docker uri>`
* [x] `singularity build --force (-F) <sif> <spec>`
* [ ] `singularity build --json <sif> <json definition>`
* [ ] `singularity build --library <string library url> <sif> <library uri>`
* [x] `singularity build --no-cleanup <sif> <spec>`
* [ ] `singularity build --nohttps <sif> <local docker uri>`
* [ ] `singularity build --notest (-T) <sif> <spec>`
* [ ] `singularity build --remote (-r) <sif> <definition>`
* [x] `singularity build --sandbox (-s) <sandbox> <spec>`
* [ ] `singularity build --section <strings> <sif> <spec>`
* [ ] `singularity build --tmpdir <string> <sif> <spec>`
* [ ] `singularity build --update (-u) <sif> <spec>`

## cache
* [ ] `singularity help cache`
* [ ] `singularity cache`
* [ ] `singularity cache --help (-h)`

## cache clean
* [ ] `singularity help cache clean`
* [ ] `singularity cache clean`
* [ ] `singularity cache clean --help (-h)`
* [ ] `singularity cache clean --all (-a)`
* [ ] `singularity cache clean --name <string> (-n)`
* [ ] `singularity cache clean --type <strings> (-T)`
 
## cache list
* [ ] `singularity help cache list`
* [ ] `singularity cache list`
* [ ] `singularity cache list --help (-h)`
* [ ] `singularity cache list --all (-a)`
* [ ] `singularity cache list --type (-T)`

## capability
* [ ] `singularity help capability`
* [ ] `singularity capability`
* [ ] `singularity capability --help (-h)`

## capability add
* [ ] `singularity help capability add`
* [ ] `singularity capability add`
* [ ] `singularity capability add <capabilities>`
* [ ] `singularity capability add --help (-h)`
* [ ] `singularity capability add --desc (-d) <capabilities>`
* [ ] `singularity capability add --group (-g) <string> <capabilities>`
* [ ] `singularity capability add --user (-u) <string> <capabilities>`

## capability drop
* [ ] `singularity help capability drop`
* [ ] `singularity capability drop`
* [ ] `singularity capability drop <capabilities>`
* [ ] `singulairty capability drop --help (-h)`
* [ ] `singularity capability drop --desc (-d) <capabilities>`
* [ ] `singularity capability drop --group (-g) <string> <capabilities>`
* [ ] `singularity capability drop --user (-u) <string> <capabilties>`

## capability list
* [ ] `singuliarty help capability list`
* [ ] `singularity capability list`
* [ ] `singularity capability list --help (-h)`
* [ ] `singularity capability list --all (-a)`
* [ ] `singularity capability list --group (-g) <string>`
* [ ] `singularity capability list --user (-u) <string>`

## exec
* [ ] `singularity help exec`
* [x] `singularity exec`
* [x] `singularity exec <sif> <command>`
* [ ] `singularity exec <sqsh> <command>`
* [ ] `singularity exec <ext3> <command>`
* [ ] `singularity exec <directory> <command>`
* [x] `singularity exec <instance uri> <command>`
* [x] `singularity exec <library uri> <command>`
* [x] `singularity exec <docker uri> <command>`
* [x] `singularity exec <shub uri> <command>`
* [ ] `singularity exec --help (-h)`
* [ ] `singularity exec --add-caps <string> <image spec> <command>`
* [ ] `singularity exec --allow-setuid <image spec> <command>`
* [x] `singularity exec --app <string> <image spec> <command>`
* [ ] `singularity exec --apply-cgroups <string> <image spec> <command>`
* [x] `singularity exec --bind (-B) <strings> <image spec> <command>`
* [ ] `singularity exec --cleanenv (-e) <image spec> <command>`
* [ ] `singularity exec --contain (-c) <image spec> <command>`
* [ ] `singularity exec --containall (-C) <image spec> <command>`
* [ ] `singularity exec --dns <string> <image spec> <command>`
* [ ] `singularity exec --docker-login <string> <docker uri> <command>`
* [x] `singularity exec --drop-caps <string> <image spec> <command>`
* [x] `singularity exec --home (-H) <string> <image spec> <command>`
* [ ] `singularity exec --hostname <string> <image spec> <command>`
* [ ] `singularity exec --ipc (-i) <image spec> <command>`
* [x] `singularity exec --keep-privs <image spec> <command>`
* [ ] `singularity exec --net (-n) <image spec> <command>`
* [ ] `singularity exec --network <string> <image spec> <command>`
* [ ] `singularity exec --network-args <string> <image spec> <command>`
* [x] `singularity exec --no-home <image spec> <command>`
* [ ] `singularity exec --no-init --pid (-p) <image spec> <command>`
* [ ] `singularity exec --no-privs <image spec> <command>`
* [ ] `singularity exec --nohttps <docker uri> <command>`
* [ ] `singularity exec --nv <image spec> <command>`
* [x] `singularity exec --overlay (-o) <strings> <image spec> <command>`
* [ ] `singularity exec --pid (-p) <image spec> <command>`
* [x] `singularity exec --pwd <string> <image spec> <command>`
* [ ] `singularity exec --scratch (-S) <string> <image spec> <command>`
* [x] `singularity exec --security <strings>`
* [ ] `singularity exec --userns <image spec> <command>`
* [ ] `singularity exec --uts <image spec> <command>`
* [x] `singularity exec --workdir (-W) <image spec> <command>`
* [ ] `singularity exec --writable (-w) <image spec> <command>`
* [ ] `singularity exec --writable-tmpfs <image spec> <command>`

## help
* [ ] `singularity help help`
* [ ] `singularity help`
* [ ] `singularity help --help (-h)`

## inspect
* [ ] `singularity help inspect`
* [ ] `singularity inspect`
* [ ] `singularity inspect <image>`
* [ ] `singularity inspect --help (-h)`
* [ ] `singularity inspect --app <string> <image>`
* [ ] `singularity inspect --deffile (-d) <image>`
* [ ] `singularity inspect --environment (-e) <image>`
* [ ] `singularity inspect --helpfile (-H) <image>`
* [ ] `singularity inspect --json (-j) <image>`
* [ ] `singularity inspect --labels (-l) <image>`
* [ ] `singularity inspect --runscript (-r) <image>`
* [ ] `singularity inspect --test (-t) <image>`

## instance
* [ ] `singularity help instance`
* [ ] `singularity instance`
* [ ] `singularity instance --help (-h)`

## instance list
* [ ] `singularity help instance list`
* [x] `singularity instance list`
* [ ] `singularity instance list --help (-h)`
* [x] `singularity instance list --json (-j)`
* [ ] `singularity instance list --user (-u) <string>`

## instance start
* [ ] `singularity help instance start`
* [ ] `singularity instance start`
* [x] `singularity instance start <sif> <instance>`
* [ ] `singularity instance start <sqsh> <instance>`
* [ ] `singularity instance start <ext3> <instance>`
* [ ] `singularity instance start <directory> <instance>`
* [ ] `singularity instance start <instance uri> <instance>`
* [x] `singularity instance start <library uri> <instance>`
* [x] `singularity instance start <docker uri> <instance>`
* [x] `singularity instance start <shub uri> <instance>`
* [ ] `singularity instance start --help (-h)`
* [ ] `singularity instance start --add-caps <string> <image spec> <instance>`
* [ ] `singularity instance start --allow-setuid <image spec> <instance>`
* [ ] `singularity instance start --apply-cgroups <string> <image spec> <instance>`
* [ ] `singularity instance start --bind (-B) <strings> <image spec> <instance>`
* [ ] `singularity instance start --boot <image spec> <instance>`
* [x] `singularity instance start --cleanenv (-e) <image spec> <instance>`
* [x] `singularity instance start --contain (-c) <image spec> <instance>`
* [ ] `singularity instance start --containall (-C) <image spec> <instance>`
* [ ] `singularity instance start --dns <string> <image spec> <instance>`
* [ ] `singularity instance start --docker-login <string> <docker uri> <instance>`
* [ ] `singularity instance start --drop-caps <string> <image spec> <instance>`
* [x] `singularity instance start --home (-H) <string> <image spec> <instance>`
* [x] `singularity instance start --hostname <string> <image spec> <instance>`
* [ ] `singularity instance start --keep-privs <image spec> <instance>`
* [ ] `singularity instance start --net (-n) <image spec> <instance>`
* [ ] `singularity instance start --network <string> <image spec> <instance>`
* [ ] `singularity instance start --network-args <string> <image spec> <instance>`
* [ ] `singularity instance start --no-home <image spec> <instance>`
* [ ] `singularity instance start --no-privs <image spec> <instance>`
* [ ] `singularity instance start --nv <image spec> <instance>`
* [ ] `singularity instance start --overlay (-o) <strings> <image spec> <instance>`
* [ ] `singularity instance start --scratch (-S) <string> <image spec> <instance>`
* [ ] `singularity instance start --security <strings>`
* [ ] `singularity instance start --userns (-u) <image spec> <instance>`
* [ ] `singularity instance start --uts <image spec> <instance>`
* [x] `singularity instance start --workdir (-W) <image spec> <instance>`
* [ ] `singularity instance start --writable (-w) <image spec> <instance>`
* [ ] `singularity instance start --writable-tmpfs <image spec> <instance>`

## instance stop
* [ ] `singularity help instance stop`
* [ ] `singularity instance stop`
* [x] `singularity instance stop <instance>`
* [ ] `singularity instance stop --all (-a)`
* [ ] `singularity instance stop --force (-F)`
* [ ] `singularity instance stop --signal <string>`
* [ ] `singularity instance stop --timeout <number> `
* [ ] `singularity instance stop --user <string>`

## key (keys)
* [ ] `singularity help key`
* [ ] `singularity key`
* [ ] `singularity key --help (-h)`

## key (keys) list
* [ ] `singularity help key list`
* [ ] `singularity key list`
* [ ] `singularity key list --help (-h)`
* [ ] `singularity key list --secret (-s)`

## key (keys) newpair
* [ ] `singularity help key newpair`
* [ ] `singularity key newpair`
* [ ] `singularity key newpair --help (-h)`

## key (keys) pull
* [ ] `singularity help key pull`
* [ ] `singularity key pull`
* [ ] `singularity key pull <fingerprint>`
* [ ] `singularity key pull --help (-h)`
* [ ] `singularity key pull --url (-u) <string> <fingerprint>`

## key (keys) push
* [ ] `singularity help key push`
* [ ] `singularity key push <fingerprint>`
* [ ] `singularity key push --help (-h)`
* [ ] `singularity key push --url (-u) <string> <fingerprint>`

## key (keys) search
* [ ] `singularity help key search`
* [ ] `singularity key search`
* [ ] `singularity key search <search string>`
* [ ] `singularity key search --help (-h)`
* [ ] `singularity key search --url (-u) <string> <search string>`

## oci
* [ ] `singularity help oci`
* [ ] `singularity oci`
* [ ] `singularity oci --help (-h)`

## oci attach
* [ ] `singularity help oci attach`
* [ ] `singularity oci attach`
* [ ] `singularity oci attach <container>`
* [ ] `singularity oci attach --help (-h)`

## oci create
* [ ] `singularity help oci create`
* [ ] `singularity oci create`
* [ ] `singularity oci create <container>`
* [ ] `singularity oci create --help (-h)`
* [ ] `singularity oci create --bundle (-b) <string> <container>`
* [ ] `singularity oci create --empty-process <container>`
* [ ] `singularity oci create --log-format <string> <container>`
* [ ] `singularity oci create --log-path (-l) <string> <container>`
* [ ] `singularity oci create --pid-file <string> <container>`
* [ ] `singularity oci create --sync-socket <string> <container>`

## oci delete
* [ ] `singularity help oci delete`
* [ ] `singularity oci delete`
* [ ] `singularity oci delete <container>`
* [ ] `singularity oci delete --help (-h)`

## oci exec
* [ ] `singularity help oci exec`
* [ ] `singularity oci exec`
* [ ] `singularity oci exec <container> <command>`
* [ ] `singularity oci exec --help (-h)`

## oci kill
* [ ] `singularity help oci kill`
* [ ] `singularity oci kill`
* [ ] `singularity oci kill <container>`
* [ ] `singularity oci kill --help (-h)`
* [ ] `singularity oci kill --signal (-s) <string> <container>`

## oci mount
* [ ] `singularity help oci mount`
* [ ] `singularity oci mount`
* [ ] `singularity oci mount <image> <bundle>`
* [ ] `singularity oci mount --help (-h)`

## oci pause
* [ ] `singularity help oci pause`
* [ ] `singularity oci pause`
* [ ] `singularity oci pause <container>`
* [ ] `singularity oci pause --help (-h)`

## oci resume
* [ ] `singularity help oci resume`
* [ ] `singularity oci resume`
* [ ] `singularity oci resume <container>`
* [ ] `singularity oci resume --help (-h)`

## oci run
* [ ] `singularity help oci run`
* [ ] `singularity oci run`
* [ ] `singularity oci run <container>`
* [ ] `singularity oci run --help (-h)`
* [ ] `singularity oci run --bundle (-b) <string> <container>`
* [ ] `singularity oci run --log-format <string> <container>`
* [ ] `singularity oci run --log-path (-l) <string> <container>`
* [ ] `singularity oci run --pid-file <string> <container>` 

## oci start
* [ ] `singularity help oci start`
* [ ] `singularity oci start`
* [ ] `singularity oci start <container>`
* [ ] `singularity oci --help (-h)`

## oci state
* [ ] `singularity help oci state`
* [ ] `singularity oci state`
* [ ] `singularity oci state <container`
* [ ] `singularity oci state --help (-h)`
* [ ] `singularity oci state --sync-socket (-s) <string> <container>`

## oci umount
* [ ] `singularity help oci umount`
* [ ] `singularity oci umount`
* [ ] `singularity oci umount <bundle>`
* [ ] `singularity oci umount --help (-h)`

## oci update
* [ ] `singularity help oci update`
* [ ] `singularity oci update`
* [ ] `singularity oci update <container>`
* [ ] `singularity oci update --help (-h)`
* [ ] `singularity oci update --from-file (-f) <string> <container>`

## plugin
* [ ] `singularity help plugin`
* [ ] `singularity plugin`
* [ ] `singularity plugin --help (-h)`

## pull
* [ ] `singularity help pull`
* [ ] `singularity pull`
* [x] `singularity pull <image> <uri>`
* [x] `singularity pull <library uri>`
* [x] `singularity pull <docker uri>`
* [x] `singularity pull <shub uri>`
* [ ] `singularity pull --help (-h)`
* [ ] `singularity pull --docker-login <docker uri>`
* [ ] `singularity pull --force (-F) <uri>`
* [ ] `singularity pull --library <string> <uri>`
* [ ] `singularity pull --nohttps <docker uri>`

## push
* [ ] `singularity help push`
* [ ] `singularity push`
* [ ] `singularity push <image> <library uri>`
* [ ] `singularity push --help (-h)`
* [ ] `singularity push --library <string> <image> <library uri>`

## run
* [ ] `singularity help run [args]`
* [x] `singularity run [args]`
* [x] `singularity run <sif> [args]`
* [ ] `singularity run <sqsh> [args]`
* [ ] `singularity run <ext3> [args]`
* [ ] `singularity run <directory> [args]`
* [ ] `singularity run <instance uri> [args]`
* [x] `singularity run <library uri> [args]`
* [x] `singularity run <docker uri> [args]`
* [x] `singularity run <shub uri> [args]`
* [ ] `singularity run --help (-h) [args]`
* [ ] `singularity run --add-caps <string> <image spec> [args]`
* [ ] `singularity run --allow-setuid <image spec> [args]`
* [x] `singularity run --app <string> <image spec> [args]`
* [ ] `singularity run --apply-cgroups <string> <image spec> [args]`
* [ ] `singularity run --bind (-B) <strings> <image spec> [args]`
* [ ] `singularity run --cleanenv (-e) <image spec> [args]`
* [ ] `singularity run --contain (-c) <image spec> [args]`
* [ ] `singularity run --containall (-C) <image spec> [args]`
* [ ] `singularity run --dns <string> <image spec> [args]`
* [ ] `singularity run --docker-login <string> <docker uri> [args]`
* [ ] `singularity run --drop-caps <string> <image spec> [args]`
* [ ] `singularity run --home (-H) <string> <image spec> [args]`
* [ ] `singularity run --hostname <string> <image spec> [args]`
* [ ] `singularity run --ipc (-i) <image spec> [args]`
* [ ] `singularity run --keep-privs <image spec> [args]`
* [ ] `singularity run --net (-n) <image spec> [args]`
* [ ] `singularity run --network <string> <image spec> [args]`
* [ ] `singularity run --network-args <string> <image spec> [args]`
* [ ] `singularity run --no-home <image spec> [args]`
* [ ] `singularity run --no-init --pid (-p) <image spec> [args]`
* [ ] `singularity run --no-privs <image spec> [args]`
* [ ] `singularity run --nohttps <docker uri> [args]`
* [ ] `singularity run --nv <image spec> [args]`
* [ ] `singularity run --overlay (-o) <strings> <image spec> [args]`
* [ ] `singularity run --pid (-p) <image spec> [args]`
* [ ] `singularity run --pwd <string> <image spec> [args]`
* [ ] `singularity run --scratch (-S) <string> <image spec> [args]`
* [ ] `singularity run --security <strings> [args]`
* [ ] `singularity run --userns <image spec> [args]`
* [ ] `singularity run --uts <image spec> [args]`
* [ ] `singularity run --workdir (-W) <image spec> [args]`
* [ ] `singularity run --writable (-w) <image spec> [args]`
* [ ] `singularity run --writable-tmpfs <image spec> [args]`

## run-help
* [ ] `singularity help run-help`
* [ ] `singularity run-help`
* [ ] `singularity run-help --help (-h)`
* [ ] `singularity run-help --app <string> <string image path>`

## search
* [ ] `singularity help search`
* [ ] `singularity search`
* [ ] `singularity search <string search query>`
* [ ] `singularity search --help (-h)`
* [ ] `singularity search --library <string> <string search query>`

## shell
* [ ] `singularity help shell`
* [ ] `singularity shell`
* [ ] `singularity shell <sif>`
* [ ] `singularity shell <sqsh>`
* [ ] `singularity shell <ext3>`
* [ ] `singularity shell <directory>`
* [ ] `singularity shell <instance uri>`
* [x] `singularity shell <library uri>`
* [x] `singularity shell <docker uri>`
* [x] `singularity shell <shub uri>`
* [ ] `singularity shell --help (-h)`
* [ ] `singularity shell --add-caps <string> <image spec>`
* [ ] `singularity shell --allow-setuid <image spec>`
* [ ] `singularity shell --app <string> <image spec>`
* [ ] `singularity shell --apply-cgroups <string> <image spec>`
* [ ] `singularity shell --bind (-B) <strings> <image spec>`
* [ ] `singularity shell --cleanenv (-e) <image spec>`
* [ ] `singularity shell --contain (-c) <image spec>`
* [ ] `singularity shell --containall (-C) <image spec>`
* [ ] `singularity shell --dns <string> <image spec>`
* [ ] `singularity shell --docker-login <string> <docker uri>`
* [ ] `singularity shell --drop-caps <string> <image spec>`
* [ ] `singularity shell --home (-H) <string> <image spec>`
* [ ] `singularity shell --hostname <string> <image spec>`
* [ ] `singularity shell --ipc (-i) <image spec>`
* [ ] `singularity shell --keep-privs <image spec>`
* [ ] `singularity shell --net (-n) <image spec>`
* [ ] `singularity shell --network <string> <image spec>`
* [ ] `singularity shell --network-args <string> <image spec>`
* [ ] `singularity shell --no-home <image spec>`
* [ ] `singularity shell --no-init --pid (-p) <image spec>`
* [ ] `singularity shell --no-privs <image spec>`
* [ ] `singularity shell --nohttps <docker uri>`
* [ ] `singularity shell --nv <image spec>`
* [ ] `singularity shell --overlay (-o) <strings> <image spec>`
* [ ] `singularity shell --pid (-p) <image spec>`
* [ ] `singularity shell --pwd <string> <image spec>`
* [ ] `singularity shell --scratch (-S) <string> <image spec>`
* [ ] `singularity shell --security <strings> <image spec>`
* [ ] `singularity shell --shell (-s) <string> <image spec>`
* [ ] `singularity shell --userns <image spec>`
* [ ] `singularity shell --uts <image spec>`
* [ ] `singularity shell --workdir (-W) <string> <image spec>`
* [ ] `singularity shell --writable (-w) <image spec>`
* [ ] `singularity shell --writable-tmpfs <image spec>`

## sign
* [ ] `singularity help sign`
* [ ] `singularity sign`
* [ ] `singularity sign <image>`
* [ ] `singularity sign --help (-h)`
* [ ] `singularity sign --groupid (-g) <int> <image>`
* [ ] `singularity sign --id (-i) <int> <image>`
* [ ] `singularity sign --keyidx (-k) <int> <image>`
* [ ] `singularity sign --url (-u) <string> <image>`

## test
* [ ] `singularity help test [args]`
* [ ] `singularity test [args]`
* [ ] `singularity test <sif> [args]`
* [ ] `singularity test <sqsh> [args]`
* [ ] `singularity test <ext3> [args]`
* [ ] `singularity test <directory> [args]`
* [ ] `singularity test --help (-h) [args]`
* [ ] `singularity test --add-caps <string> <image spec> [args]`
* [ ] `singularity test --allow-setuid <image spec> [args]`
* [ ] `singularity test --app <string> <image spec> [args]`
* [ ] `singularity test --apply-cgroups <string> <image spec> [args]`
* [ ] `singularity test --bind (-B) <strings> <image spec> [args]`
* [ ] `singularity test --cleanenv (-e) <image spec> [args]`
* [ ] `singularity test --contain (-c) <image spec> [args]`
* [ ] `singularity test --containall (-C) <image spec> [args]`
* [ ] `singularity test --dns <string> <image spec> [args]`
* [ ] `singularity test --docker-login <string> <docker uri> [args]`
* [ ] `singularity test --drop-caps <string> <image spec> [args]`
* [ ] `singularity test --home (-H) <string> <image spec> [args]`
* [ ] `singularity test --hostname <string> <image spec> [args]`
* [ ] `singularity test --ipc (-i) <image spec> [args]`
* [ ] `singularity test --keep-privs <image spec> [args]`
* [ ] `singularity test --net (-n) <image spec> [args]`
* [ ] `singularity test --network <string> <image spec> [args]`
* [ ] `singularity test --network-args <string> <image spec> [args]`
* [ ] `singularity test --no-home <image spec> [args]`
* [ ] `singularity test --no-init --pid (-p) <image spec> [args]`
* [ ] `singularity test --no-privs <image spec> [args]`
* [ ] `singularity test --nohttps <docker uri> [args]`
* [ ] `singularity test --nv <image spec> [args]`
* [ ] `singularity test --overlay (-o) <strings> <image spec> [args]`
* [ ] `singularity test --pid (-p) <image spec> [args]`
* [ ] `singularity test --pwd <string> <image spec> [args]`
* [ ] `singularity test --scratch (-S) <string> <image spec> [args]`
* [ ] `singularity test --security <strings> <image spec> [args]`
* [ ] `singularity test --userns <image spec> [args]`
* [ ] `singularity test --uts <image spec> [args]`
* [ ] `singularity test --workdir (-W) <string> <image spec> [args]`
* [ ] `singularity test --writable (-w) <image spec> [args]`
* [ ] `singularity test --writable-tmpfs <image spec> [args]`

## verify
* [ ] `singularity help verify`
* [ ] `singularity verify`
* [ ] `singularity verify <image>`
* [ ] `singularity verify --help (-h)`
* [ ] `singularity verify --group (-g) <int> <image>`
* [ ] `singularity verify --id (-i) <int> <image>`
* [ ] `singularity verify --url (-u) <string> <image>`

## version
* [ ] `singularity help version`
* [ ] `singularity version`
* [ ] `singularity version --help (-h)`

## end

**Comment by jscook2345** [comment]
I downloaded and refactored the list a little bit, but these are the current numbers:

$ ack --count '[x]' covered_options.md 
90

$ ack --count '[ ]' covered_options.md 
502

So roughly 1/5 of options. This does not count OCI testing as it hasn't been added fully yet.

**Comment by jscook2345** [comment]
A lot of things are covered multiple times and a lot of things that do not show up in that list are covered.

Example: All the sections of a definition file, bootstrap methods (debootstrap, etc), testing with pipes, security options, file permissions, running root vs non-root, making sure errors fail gracefully, amongst a number of other things.

**Comment by GodloveD** [comment]
Do you want to start ticking the boxes of things that are tested?

**Comment by jscook2345** [comment]
@GodloveD I sent you a link in Slack! I'll update here as needed.

**Comment by jscook2345** [comment]
I think this issue can be closed for now. We have both my worksheet and the corp spreadsheet.
