### ISSUE TITLE
SINGULARITY_PULLFOLDER not honored for 3.1

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#2788]
I'm updating tests for Singularity Python client, and strangely the tests fail to pull an image and specify a pull folder, which for versions 2.* worked. I can't seem to find any documentation about it, I'm hoping you can point me to the right direction if the functionality changed, and the docs can reflect that as well. Thank you!

## Version of Singularity:

```bash
$ singularity --version
singularity version 3.1.0-rc2.28.ga72e427
```

### Expected behavior

```bash
$ export SINGULARITY_PULLFOLDER=/tmp
$ singularity pull docker://busybox
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:697743189b6d255069caf6c455be10c7f8cae8076c6f94d224ae15cd41420e87
Copying config sha256:85dcb8c21e86b3e01a3a45fc932b31f5194c174d0a5d8a993381cc1fca749f40
 575 B / 575 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: /tmp/busybox_latest.sif
```

### Actual behavior

```bash
$ export SINGULARITY_PULLFOLDER=/tmp
$ singularity pull docker://busybox
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:697743189b6d255069caf6c455be10c7f8cae8076c6f94d224ae15cd41420e87
Copying config sha256:85dcb8c21e86b3e01a3a45fc932b31f5194c174d0a5d8a993381cc1fca749f40
 575 B / 575 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: busybox_latest.sif
```
Note that image is pulled to present working directory.

### Steps to reproduce behavior

```bash
$ export SINGULARITY_PULLFOLDER=/tmp
$ singularity pull docker://busybox
```

Note that it's not found in 3.0 docs:

![image](https://user-images.githubusercontent.com/814322/53684358-34ed1300-3cda-11e9-9cf5-c4de496b590c.png)

Is found in 2.6.1!

![image](https://user-images.githubusercontent.com/814322/53684365-433b2f00-3cda-11e9-91e1-d99ba6bd3ef4.png)

**Comment by GodloveD** [comment]
Looks like an env var that didn't make it in through the bash -> Go gauntlet.  Maybe it can be added back into 3.3 if people are using it?  Is there another env var that already exists that will do similar?

**Comment by vsoch** [comment]
There was a lot of talk about `SINGULARITY_PULLFOLDER` with `SINGULARITY_CACHEDIR` in the past with @satra, here is a relevant PR if it's helpful :point_right:: https://github.com/sylabs/singularity/pull/855

I would suspect that `SINGULARITY_CACHEDIR` could serve the same purpose, but I do see the two as different. The example is that on our cluster I have `SINGULARITY_CACHEDIR` exported to somewhere on scratch, always, because pulling to home would lead to it filling up and getting locked out. The cache is generally where I want layers, shub images, etc. to be pulled if I want them for later. The pull folder is what I use when I want to set a quick envar to override that and (for some program I'm running) pull containers to somewhere else. I still use it for 2.6.1 and was surprised when it wasn't honored for 3.1. In that it's provided previously, I'm hoping we can get him back :)

**Comment by GodloveD** [comment]
Thanks for all of the additional info @vsoch!  Sounds like it would be a worthy thing to add back in then.

**Comment by vsoch** [comment]
Awesome thanks @GodloveD !

**Comment by vsoch** [comment]
Here is a nice post I just found on r/programming, [A no nonsense guide to environment variables in go](https://endaphelan.me/guides/golang/a-no-nonsense-guide-to-environment-variables-in-go/)

Probably not needed for this PR, but an enjoyable read! :)

**Comment by jscook2345** [comment]
The use of the word `FOLDER` is very non-posix. Could it be like `DIR` or `PATH`?

**Comment by vsoch** [comment]
@jscook2345 this is previous (already implemented) functionality in previous versions of Singularity so it would be messy /confusing to introduce another variable with a different name.

**Comment by vsoch** [comment]
`PATH` is confusing because the user would be inclined to enter a full path to a container (and we want a directory) `DIR` would be better, but it would still be the case that previous functionality wasn't honored.

**Comment by vsoch** [comment]
Just to clarify - there is a change in functionality so that `SINGULARITY_PULLFOLDER` is not honored, but `SINGULARITY_PULLPATH` is?

**Comment by vsoch** [comment]
Is this the direct (full path) to the container, or a folder? And there is no way to specify the folder (but not have preference for the name?)

**Comment by WestleyK** [comment]
> Just to clarify - there is a change in functionality so that `SINGULARITY_PULLFOLDER` is not honored, but `SINGULARITY_PULLPATH` is?

Sorry, the PR title was outdated, it is `SINGULARITY_PULLDIR`, or `SINGULARITY_PULLFOLDER`.

**Comment by vsoch** [comment]
ah okay, thanks! :tada:
