### ISSUE TITLE
Singularity not honoring json specification for inspect

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#2790]
Singularity inspect should honor the json specification [here](https://jsonapi.org/format/), specifically, we have "data" at the top level, and then attributes below it (and the majority of metadata below to attributes). On a high level, it should look like this:

```
$ singularity inspect -e -d -l -r -H -t --json /tmp/tmpkbq7z2nb/busybox:1.30.1.simg
{
       "data": {
   	        "attributes": {
		    "deffile": "bootstrap: docker\nfrom: busybox:1.30.1",
		    "environment": "...",
		    "labels": "...",
   		    "runscript": "..."
               }
	},
	"type": "container"
}
```

However what inspect is returning skips the "data" level, and only returns "attributes"

```
$ singularity inspect -e -d -l -r -H -t --json /tmp/tmpkbq7z2nb/busybox:1.30.1.simg
...
{
	"attributes": {
		"deffile": "bootstrap: docker\nfrom: busybox:1.30.1",
		"environment": "==-z\n==\n#!/bin/sh\n#Custom environment shell code should follow",
		"labels": "{\n\t\"org.label-schema.build-date\": \"Saturday_2_March_2019_14:59:59_EST\",\n\t\"org.label-schema.schema-version\": \"1.0\",\n\t\"org.label-schema.usage.singularity.deffile.bootstrap\": \"docker\",\n\t\"org.label-schema.usage.singularity.deffile.from\": \"busybox:1.30.1\",\n\t\"org.label-schema.usage.singularity.version\": \"3.1.0-rc2.28.ga72e427\"\n}",
		"runscript": "#!/bin/sh\nOCI_ENTRYPOINT=''\nOCI_CMD='\"sh\"'\nCMDLINE_ARGS=\"\"\n# prepare command line arguments for evaluation\nfor arg in \"$@\"; do\n    CMDLINE_ARGS=\"${CMDLINE_ARGS} \\\"$arg\\\"\"\ndone\n\n# ENTRYPOINT only - run entrypoint plus args\nif [ -z \"$OCI_CMD\" ] \u0026\u0026 [ -n \"$OCI_ENTRYPOINT\" ]; then\n    if [ $# -gt 0 ]; then\n        SINGULARITY_OCI_RUN=\"${OCI_ENTRYPOINT} ${CMDLINE_ARGS}\"\n    else\n        SINGULARITY_OCI_RUN=\"${OCI_ENTRYPOINT}\"\n    fi\nfi\n\n# CMD only - run CMD or override with args\nif [ -n \"$OCI_CMD\" ] \u0026\u0026 [ -z \"$OCI_ENTRYPOINT\" ]; then\n    if [ $# -gt 0 ]; then\n        SINGULARITY_OCI_RUN=\"${CMDLINE_ARGS}\"\n    else\n        SINGULARITY_OCI_RUN=\"${OCI_CMD}\"\n    fi\nfi\n\n# ENTRYPOINT and CMD - run ENTRYPOINT with CMD as default args\n# override with user provided args\nif [ $# -gt 0 ]; then\n    SINGULARITY_OCI_RUN=\"${OCI_ENTRYPOINT} ${CMDLINE_ARGS}\"\nelse\n    SINGULARITY_OCI_RUN=\"${OCI_ENTRYPOINT} ${OCI_CMD}\"\nfi\n\n# Evaluate shell expressions first and set arguments accordingly,\n# then execute final command as first container process\neval \"set ${SINGULARITY_OCI_RUN}\"\nexec \"$@\""
	},
	"type": "container"
}
```

## Version of Singularity:

```bash
$ singularity version 3.1.0-rc2.28.ga72e427
```

### Expected behavior

The original inspect was designed to follow the json API, and the updated GoLang version should be consistent with that.

### Actual behavior

Something took a bite out of the result and the "data" label is missing.

### Steps to reproduce behavior

Inspect a container with 3.* family.

**Comment by vsoch** [comment]
Here is an inspect from 2.6.1, notice "data" at the top level!

![image](https://user-images.githubusercontent.com/814322/53687373-e2bfe800-3d01-11e9-9b63-816e8c828b16.png)

**Comment by mem** [comment]
As of 3.4 this is still not fixed.

**Comment by mem** [comment]
What I'm wondering now is what will break if we fix this. And I don't see a good way to support both cases (obviously a flag, but what should the default be in that case?)

**Comment by vsoch** [comment]
It needs to follow the specification, this was originally implemented correctly, I opened this issue promptly to address, and just because it's been slow to respond to fix it doesn't mean it's the right thing to keep now. For reference, here is the specification that is followed: https://jsonapi.org/format/

**Comment by vsoch** [comment]
And also for note, the change of removing data broke Singularity Hub, Singularity Registry Server, and Singularity Registry Client, and I had to do temporary workarounds for all of those. If someone spilled milk on the floor and a second person put up a "Wet Floor" sign, even if it took a week and the milk smelled nasty due to being old, the correct thing to do would be to clean up the milk and remove the sign, not to say that the sign should remain because people were forced to adapt to it. If this weren't following a specification, it could be argued to keep, but this is not the case.

**Comment by mem** [comment]
Ah, sorry. I didn't mean to say that this should not be fixed.

I was actually wondering about the case you describe: if there's a workaround in place, by fixing this, does the code with the workaround break? Or will it just be happy?

**Comment by vsoch** [comment]
It makes my code much cleaner to not have to support a bugged version and a working version.  Both are currently supported, so it would be fine – and I’d really like to delete the temporary workaround because it’s messy.  If the library here is implementing a standard, it is best practice to do that. It Is bad practice to implement a standard and then change it.

**Comment by mem** [comment]
I'm a little confused: reading thru the docs I understand there MUST be an id and a type inside that `data` object. If I add those to conform to the spec, do I break your application?

**Comment by vsoch** [comment]
Just follow the spec! :)
