### ISSUE TITLE
Request for more informative errors when squashfs-tools is not installed

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2791]
https://github.com/sylabs/singularity/issues/2352#issuecomment-468451636

**Comment by mem** [comment]
I just checked with the current version of singularity (3.4) and the message looks like:

```
$ builddir/singularity build --fakeroot --force test.sif test.def
FATAL:   Unable to create build: while searching for mksquashfs: exec: "mksquashfs": executable file not found in $PATH
```

and I verified that singularity is looking for mksquashfs in $PATH, just as the message says (I placed mksquashfs in a non-standard location and modified PATH to include that).

_Maybe_ the use from the point of view of the user is that if you do `sudo singularity ...` $PATH might change, depending on the configuration of sudo.

I would consider this a non-bug.

Feel free to reopen this.

**Comment by jmstover** [comment]
I believe there's a `singularity.conf` key you can use to set a non-standard location for the `mksquashfs` binary.
