### ISSUE TITLE
OCI container should not be created if errors on create

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#2794]
I'm playing around with OCI, I had a failed attempt to create a bundle (didn't use sudo first time):

```bash
$ singularity oci create --bundle /tmp/bundle --log-format kubernetes mycontainer
ERROR  : Failed to set effective UID to 0
FATAL:   exit status 1
```

And then I fussed up one more time, I had an error in my config.json referencing a folder that I forgot to create:

```bash
FATAL:   exit status 1
FATAL:   container creation failed: failed to resolve /tmp/bundle/rootfs path: lstat /tmp/bundle/rootfs: no such file or directory
```

But then doing it the third time (with a fixed config):

```bash
sudo singularity oci create --bundle /tmp/bundle --log-format kubernetes mycontainer
```

I'm alerted that the bundle already exists:

```bash
FATAL:   exit status 1
FATAL:   mycontainer already exists
```

I found the oci directory in roots home (/root/.singularity/cache/oci) and deleted that thinking it was cached there, same error. I also tried removing the same for my user (if the errored creation the first time created it anyway):

```bash
$ rm -rf /home/vanessa/.singularity/cache/oci
```
No luck! Where is `mycontainer` hiding? It doesn't seem to be a thing that I can attach to:

```bash
$ singularity oci attach mycontainer
FATAL:   no instance found with name mycontainer
```

I don't think that I actually created it, at least in the same way that I would run/shell/interact with a container or container instance (on Ubuntu you see it pop up like a mounted drive). It was only when I tried deleting it that I didn't get an error message (when using sudo, which makes sense, since root created it):

```bash
$ singularity oci delete mycontainer
FATAL:   no instance found with name mycontainer
$ singularity oci kill mycontainer
FATAL:   no instance found with name mycontainer
$ sudo singularity oci kill mycontainer
FATAL:   container mycontainer is nor created nor running
$ sudo singularity oci delete mycontainer
```

And then the create command worked! But it still remains - where was the "mycontainer" hiding?

**Comment by vsoch** [comment]
Ah more follow up - it looks like I can use the state command to at least have some record if it exists or not. For example, here is another failed attempt:

```bash
FATAL:   container creation failed: mount error: permission denied
FATAL:   exit status 1
```
And now when I use state, I see the failure

```bash
$ sudo singularity oci state mycontainer
{
	"ociVersion": "1.0.1-dev",
	"id": "mycontainer",
	"status": "stopped",
	"pid": 14431,
	"bundle": "/tmp/bundle",
	"finishedAt": 1551647410702485769,
	"exitCode": 255,
	"exitDesc": "container creation failed: mount error: permission denied"
}
```
I'm seeing a general pattern of whenever I do some failed command, and my expectation is that the bundle isn't turned into an oci image, it actually does create the image (and I get the message above that it already exists.) Is this expected functionality? I think I'd want any kind of create failure to not result in a created container. Thanks!

**Comment by vsoch** [comment]
Whoo I made an Oci Image (instance?) container!

```bash
$ sudo singularity oci state mycontainer
{
	"ociVersion": "1.0.1-dev",
	"id": "mycontainer",
	"status": "created",
	"pid": 17869,
	"bundle": "/tmp/bundle",
	"createdAt": 1551648746754723025,
	"attachSocket": "/var/run/singularity/instances/root/mycontainer/attach.sock",
	"controlSocket": "/var/run/singularity/instances/root/mycontainer/control.sock"
}
```

_proceeds to go on to break it..._

**Comment by cclerget** [comment]
I think there is confusion, create doesn't create a bundle it create a container process from a bundle directory that user filled and provided via `-b`. If you want to create a bundle you can use `singularity oci mount image.sif /tmp/bundle` and adjust OCI configuration in `/tmp/bundle/config.json`

**Comment by vsoch** [comment]
So should the container process be created even if there is an error?

**Comment by cclerget** [comment]
I don't think there is a need to keep the container state around when creation failed, will check at OCI spec and fix it if this is not a requirement

**Comment by vsoch** [comment]
okay fantastic! Here is how to exactly reproduce the issue (I did almost as you suggested, but created a sandbox instead of using mount)

```bash
# Create a sandbox folder with the OS
$ sudo singularity build --sandbox /tmp/tacos docker://ubuntu
```
Then here is the config I whittled together
```bash
{
	"ociVersion": "1.0.0",
	"process": {
		"terminal": true,
		"user": {
			"uid": 0,
			"gid": 0
		},
		"args": [
			"/bin/bash"
		],
		"env": ["PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"TERM=xterm"
		],
		"cwd": "/",
		"capabilities": {
			"bounding": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"effective": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"inheritable": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"permitted": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"ambient": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			]
		},
		"rlimits": [
			{
				"type": "RLIMIT_NOFILE",
				"hard": 1024,
				"soft": 1024
			}
		],
		"noNewPrivileges": true
	},
	"root": {
		"path": ".",
		"readonly": true
	},
	"hostname": "runc",
	"linux": {
		"uidMappings": [
			{
				"hostID": 1000,
				"containerID": 0,
				"size": 1
			}
		],
		"gidMappings": [
			{
				"hostID": 1000,
				"containerID": 0,
				"size": 1
			}
		],
		"namespaces": [
			{
				"type": "pid"
			},
			{
				"type": "ipc"
			},
			{
				"type": "uts"
			},
			{
				"type": "mount"
			},
			{
				"type": "user"
			}
		]
	}
}
```
(open an edit with sudo and write that at the root). Then for the first attempt, just try creation without sudo (it will fail)

```bash
$ singularity oci create -b /tmp/tacos mybundle
ERROR  : Failed to set effective UID to 0
FATAL:   exit status 1
```
There doesn't seem to be any state

```bash
$ singularity oci state  mybundle
FATAL:   no instance found with name mybundle
```
So I would then expect the sudo version to work

```bash
i$ sudo singularity oci create -b /tmp/tacos mybundle
FATAL:   mybundle already exists
```

Where is the record that the container mybundle exists? (just curious! I couldn't find it).

I think users that are new to customizing the configs (myself included) will run into this issue lot - I hit it from several directions (various errors with my config) and then either not know to just do `singularity oci delete <mycontainer>` (it took me a while) or will just be frustrated that the failed attempt wound up creating (a container? a state? a process?) Wherever the record of "mybundle" is hiding, we shouldn't let him hide there!

**Comment by vsoch** [comment]
Oh neat! I just learned that you can do:

```bash
$ runc spec
```
and get a config.json file to work with right there.

**Comment by vsoch** [comment]
If it helps, it looks like (on failed create) the container is created (somewhere, maybe in the singularity folder under var?) and has state stopped:

![image](https://user-images.githubusercontent.com/814322/53767246-30278b00-3ea3-11e9-8d84-1944ccfb06e7.png)

**Comment by cclerget** [comment]
@vsoch Those files resides in `/var/run/singularity/instances/root`
