### ISSUE TITLE
Question: What does the --empty-process flag do?

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#2795]
What is the difference between running create with and without `--empty-process` ? This one:

```bash
      --empty-process        run container without executing container
                             process (eg: for POD container)
```
Thanks!

**Comment by cclerget** [comment]
`--empty-process` is only for a specific use with Kubernetes to create POD container, it won't run a container process but instead spawn an "empty" process just waiting for signals

**Comment by vsoch** [comment]
Ah understood. Thank you @cclerget !
