### ISSUE TITLE
Question: Are there default log / pid file path?

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#2796]
Is there a default log file path, or if not provided, are no logs kept?

```bash
  -l, --log-path string      specify the log file path
```

Same for pid file - is there a default?

```bash
      --pid-file string      specify the pid file
```

**Comment by cclerget** [comment]
Hi @vsoch , if those options are not provided indeed there is no log file or pid file

**Comment by vsoch** [comment]
Ok great thank you! That clarifies it - I’ll add these notes to the docs for the client.
