### ISSUE TITLE
build fails on RHEL 6

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#28]
This is on RHEL 6 with current master source (13ee02909f1c6d80448426bf6f85423d8e9ec210):

```
gcc -DHAVE_CONFIG_H -I.  -DSYSCONFDIR=\"/usr/local/etc\" -DLOCALSTATEDIR=\"/usr/local/var\" -DLIBEXECDIR=\"/usr/local/libexec\" -DNS_CLONE_NEWPID -DNS_CLONE_FS -DNS_CLONE_FILES -DNS_CLONE_NEWNS  -Wall -g -O2 -MT sexec-loop-control.o -MD -MP -MF .deps/sexec-loop-control.Tpo -c -o sexec-loop-control.o `test -f 'loop-control.c' || echo './'`loop-control.c
loop-control.c: In function ‘obtain_loop_dev’:
loop-control.c:55: error: ‘LOOP_CTL_GET_FREE’ undeclared (first use in this function)
loop-control.c:55: error: (Each undeclared identifier is reported only once
loop-control.c:55: error: for each function it appears in.)
make[2]: *** [sexec-loop-control.o] Error 1
make[2]: Leaving directory `/home/dlove/rpmbuild/SOURCES/singularity/src'
```

**Comment by gmkurtzer** [comment]
That is disconcerting. I'll debug shortly.

**Comment by loveshack** [comment]
RHEL 6 apparently just doesn't have loop-control.

**Comment by gmkurtzer** [comment]
I am quite curious how losetup does it on RHEL 6 and will investigate shortly!

Let me know if you come across anything before I do. Thanks!

**Comment by gmkurtzer** [comment]
I rewrote obtain_loop_dev() such that it works the same as systems seem to work without /dev/loop-control... That is, they use brute force and iterate through a given number of loop devices and checking them. Eww, but it works!
