### ISSUE TITLE
Does OCI Image creation require root?

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#2805]
I'm wondering if root is required to create an Oci image from a bundle folder (a filesystem with a config.json). For example:

```bash
# Dump busybox into a folder, not using sudo
$ singularity build --sandbox /tmp/another docker://busybox

# Copy a config.json template there
$ cp bundle/config.json another/config.json

# Create a bundle no sudo
$ singularity oci create -b /tmp/another mybundle
ERROR : Failed to set effective UID to 0
FATAL:  exit status 1
```

I had thought that the OCI command group was just providing fingers to (already existing) Singularity functions (meaning that creating an Oci Image from a bundle was just another way to create an instance that conforms to the specification). Based on being able to create instances without sudo, for example:

```bash
$ singularity instance start docker://ubuntu tacos
INFO:    instance started successfully
```
I figured I would also be able to create bundles without sudo. Is this expected behavior, that instances don't need root, OciImage do?  Are they different? Thanks!

## Version of Singularity:

3.1.0

**Comment by cclerget** [comment]
@vsoch This is expected for now, all OCI commands requires and doesn't use use setuid workflow at all, Singularity commands and OCI commands are two separate things, OCI only use instance code to manage instance files but runtime are completely different (that's why oci containers appears with `instance list`, I will fix that to avoid confusion)

**Comment by vsoch** [comment]
Thanks @cclerget this is good to know - and since you told me where they reside in /var/run/singularity/instances I can clean up the (previously) errored ones.
