### ISSUE TITLE
Unable to delete OCI Container

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#2806]
I'm not able to delete an OCI image that is running no matter what I try:

```bash
i$ sudo singularity oci delete mycontainer
FATAL:   container is not stopped: running
```
Okay, it's running,and I can see that via it's state:

```bash
$ sudo singularity oci state mycontainer
{
	"ociVersion": "1.0.1-dev",
	"id": "mycontainer",
	"status": "running",
	"pid": 9981,
	"bundle": "/tmp/bundleo",
	"createdAt": 1551733595253713479,
	"startedAt": 1551733603560563021,
	"attachSocket": "/var/run/singularity/instances/root/mycontainer/attach.sock",
	"controlSocket": "/var/run/singularity/instances/root/mycontainer/control.sock"
}
```
So I'd try killing it, pausing it, etc.

```bash
$ sudo singularity oci pausel mycontainer
$ sudo singularity oci kill mycontainer
```
There aren't any errors so this means it must have worked! I can try deleting it now:

```bash
$ sudo singularity oci delete mycontainer
FATAL:   container is not stopped: running
```
omg, he's still running!

```bash
$ sudo singularity oci state mycontainer
{
	"ociVersion": "1.0.1-dev",
	"id": "mycontainer",
	"status": "running",
	"pid": 9981,
	"bundle": "/tmp/bundleo",
	"createdAt": 1551733595253713479,
	"startedAt": 1551733603560563021,
	"attachSocket": "/var/run/singularity/instances/root/mycontainer/attach.sock",
	"controlSocket": "/var/run/singularity/instances/root/mycontainer/control.sock"
}
```

How do I stop the container?

## Version of Singularity:

3.1.0

**Comment by vsoch** [comment]
I tried using the instance command group, but it timed out:

```bash
$ sudo singularity instance list
INSTANCE NAME    PID      IMAGE
mybundle         17582    /tmp/tacos
mycontainer      9981     /tmp/bundleo
thiscontainer    17363    /tmp/tacos
```
```bash
$ sudo singularity instance stop mycontainer
Killing mycontainer instance of /tmp/bundleo (PID=9981) (Timeout)
```

**Comment by vsoch** [comment]
Here is the error propagating in another environment:

![image](https://user-images.githubusercontent.com/814322/53769048-b98d8c00-3ea8-11e9-8f49-768d3473b67c.png)

**Comment by cclerget** [comment]
@vsoch This is part of OCI spec, a container in `running` state can't be deleted without killing it first, no need to pause it. Kill depend of container process ran, some process ignore some signals (SIGTERM is sent by default), in this case `singularity oci kill containerID KILL` will kill it for sure

**Comment by vsoch** [comment]
Interesting, if I wanted to kill a container then, would there be any reason to not add the KILL at the end (if it is more certain?)

**Comment by vsoch** [comment]
Or should I treat it as a `--force` sort of argument?

**Comment by cclerget** [comment]
SIGTERM is the gentle way to stop container process, but it may be ignored if the process command line is something like `/bin/sh -c "sleep infinity"`, in this case only KILL work because shell (running as PID 1) will ignore signals. So yes consider KILL as `--force` option, I will add a `--timeout` and a `--force` flag

**Comment by vsoch** [comment]
Thanks for the clarification - I added as it's implemented now (to specify the signal with `--signal`)  and I'll keep a look out for those other options. I think the issue is overall resolved, so closing!
