### ISSUE TITLE
Sandbox container breaks when not using --writable

### ISSUE THREAD

**Issue by Flamefire** [apptainer/singularity#2812]
## Version of Singularity:

3.0.3-1

### Expected behavior

Should work

### Actual behavior

Sandbox container not usable anymore

### Steps to reproduce behavior

- `sudo singularity build --sandbox Sandbox library://library/default/debian:7`
- (Not required just check:) `singularity exec --writable Sandbox/ echo "OK"`
- `singularity exec  Sandbox/ echo "OK"`

The last command hangs indefinitely. Trying to access the files shows that e.g. `Sandbox/bin/dash` cannot be opened for reading (`fopen` hangs). Even just `less Sandbox/bin/dash` does not work anymore and I have to delete the whole folder

**Comment by Flamefire** [comment]
The cause seems to be the ecryptfs used where the sandbox is stored: https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/RINf2QvVO4Y

Confusing is the point that `--writable` works though. On e.g. `/tmp` it does work.

**Comment by cclerget** [comment]
Hi @Flamefire , regarding the issue with ecryptfs and overlay, it works because `--writable` disable overlay to work directly on image

**Comment by cclerget** [comment]
Closing, @Flamefire feel free to re-open it if needed

**Comment by Flamefire** [comment]
So this will never be fixed or cannot be fixed?

**Comment by cclerget** [comment]
@Flamefire It can't be fixed at our level (linux kernel issue), you need to put sandbox images on another filesystem partition which is not ecryptfs or use SIF images
