### ISSUE TITLE
Pulling from non-default shub registry gives "no response recieved" 

### ISSUE THREAD

**Issue by tamasgal** [apptainer/singularity#2819]
I am trying to use the `singularity` client to pull images from our private singularity registry but I get 

```
FATAL:   Failed to get manifest from Shub: No response received from singularity hub
```

## Version of Singularity:

3.1

### Expected behavior

Pulling images should work.

### Actual behavior

Pulling images doesn't work.

### Steps to reproduce behavior

░ tgal@staticbox:~ py-3.7.2
░ 16:11:40 [I] ✘130 ➜ singularity pull shub://singularity.km3net.de/common/jpp:v11.0.0-rc9
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Failed to get manifest from Shub: No response received from singularity hub
Although the image is there and it should be public.

**Comment by vsoch** [comment]
hey @tamasgal ! In the meantime, here is a quick hack for pulling it anyway :)

```bash
$ singularity pull $(curl http://singularity.km3net.de/api/container/common/jpp | jq --raw-output .image)
```
Format is:

```bash
$ singularity pull $(curl <registry>/api/container/<collection>/<container> | jq --raw-output .image)
```
For a particular tag, just add it:

```bash
$ singularity pull $(curl http://singularity.km3net.de/api/container/common/jpp:v11.0.0-rc9 | jq --raw-output .image)
$ singularity pull $(curl <registry>/api/container/<collection>/<container>:<tag> | jq --raw-output .image)
```
and as discussed in the linked issue, you can of course use sregistry client. But definitely it's nice if singularity supports this.

**Comment by tamasgal** [comment]
Haha thanks ;)

**Comment by jscook2345** [comment]
@ikaneshiro 

ping!

**Comment by vsoch** [comment]
ping on this issue - @yarikoptic asked about this just now.

**Comment by vsoch** [comment]
Any updates on this issue?

**Comment by tamasgal** [comment]
I actually don't have any updates as we switched to a simple SFTP server to store the singularity images. Unfortunately we had too many issues and not enough human ressources to maintain the singularity registry, so we now only have Docker+SFTP for the images built and pushed on/from the CI systems.

**Comment by vsoch** [comment]
oh hey @tamasgal I didn't mean from you - I meant from the maintainers here. This issue is 5 months old and the issue still remains, it seems.

**Comment by mem** [comment]
Sorry for editing the title; I had to squint in order to notice that the issue is using a shub registry other than the default one.

**Comment by vsoch** [comment]
No worries! Yes, it is the case that users can deploy a Singularity Registry Server, and then interact with it using the same shub uri. The difference is that the registry base is different, like `singularity pull shub://myregistry.org/collection/container:tag`

**Comment by wonderchoosey** [comment]
When there is credentials for a specific user in a private registry, although the singularity pull does not work as of today. If it was working, how would the login happen with singularity client?

**Comment by vsoch** [comment]
For Singularity Registry Server, it serves the library API so the login with a user token from their profile is the same as it would be with Sylabs Cloud.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by vsoch** [comment]
@tamasgal this is fairly old and sregistry should be able to pull without issue now - is this still an issue?

**Comment by pedroalvesbatista** [comment]
@tamasgal Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Closing this old stale issue from the old singularity repo. If this still an issue please create a new issue in the Apptainer repo. Thanks.
