### ISSUE TITLE
oras:// URI to support OCI registry [e.g. azurecr.io] as SIF storage endpoint

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2831]
According to @vermagit it is possible to push arbitrary artifacts (including SIF files) up to OCI registries using a tool called [oras](https://github.com/deislabs/oras/) like so:

```
$ singularity pull library://verma/default/layer:centos

$ oras push hpccontainers.azurecr.io/singularity:centos ./layer_centos.sif -u hpccontainers -p $PASSWORD
```

oras is written in Go and has an MIT license.  Maybe we could integrate it with Singularity and use it in our push command so that SIF files can be stored on OCI registries.

**Comment by bauerm97** [comment]
Updated the name since we're no longer planning to implement as a plugin
