### ISSUE TITLE
Source .bashrc file of root on singularity container load

### ISSUE THREAD

**Issue by rickstaa** [apptainer/singularity#2833]
## Version of Singularity:
v.3.0.3

## Question
I was wondering if it is possible to automatically source the .bashrc of the root system on container load? In my .bashrc file I have the following code to check whether I am in a singularity container to change my PS1 based on that:
```

## ---- Check singularity shell ----
if [ -n "$SINGULARITY_CONTAINER" ]; then
# Change prompt
PS1=$SINGULARITY_CONTAINER":"$PS1
export PS1="\[\e[0;36m\]$SINGULARITY_CONTAINER\[\e[m\]\[\e[36m\]@\[\e[m\]\[\e[1;32m\]\u\[\e[m\]\[\e[32m\]@\[\e[m\]\[\e[1;32m\]\h\[\e[m\]:\[\e[1;36m\]\w\[\e[m\]\\$ "

```

As a result, I would like to source the .bashrc of the main system when I load a singularity shell.

### Expected behaviour
The bashrc is sourced when the container is started, and the PS1 is updated accordingly.

### Actual behaviour
Now I first have to run `%SHELL` or `bash` to get the PS1 to update.

### Steps to reproduce behavior
- Open a singularity shell container using `singularity shell --nv <image>.simg`

**Comment by jmstover** [comment]
@rickstaa We start the shell with `--norc` to prevent host variables from interfering.

Try running like:
```
SINGULARITY_SHELL=/bin/bash singularity shell --nv <image>.simg
```
And see if that will give you a close behavior. That will run `/bin/bash` as the shell... and not `/bin/bash --norc`

**Comment by rickstaa** [comment]
@jmstover Ah that makes perfect sense! I will resort to a $runscript in most cases and use the call if I want my main bash shell in the image.
