### ISSUE TITLE
Create e2e tests for `singularity key`

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2839]
Create e2e tests for each sub-command and option for the `singularity key` command.

<pre>
[vagrant@localhost ~]$ singularity help keys
Manage OpenPGP key stores

Usage:
  singularity keys [keys options...] <subcommand>

Description:
  The 'key' command allows you to manage local OpenPGP key stores by creating
  a new store and new key pairs. You can also list available keys from the
  default store. Finally, the key command offers subcommands to communicate
  with an HKP key server to fetch and upload public keys.

Options:
  -h, --help   help for keys

Available Commands:
  list        List keys from the default key store
  newpair     Create a new OpenPGP key pair
  pull        Fetch an OpenPGP public key from a key server
  push        Upload an OpenPGP public key to a key server
  search      Search for keys matching string argument

Examples:
  All group commands have their own help output:

  $ singularity help key newpair
  $ singularity key list --help

For additional help or support, please visit https://www.sylabs.io/docs/
</pre>

**Comment by gvallee** [comment]
related to issue #3533 and #4087
