### ISSUE TITLE
Singularity Should be Installed with the Sylabs Admin public key by Default

### ISSUE THREAD

**Issue by WestleyK** [apptainer/singularity#2842]
## Version of Singularity:

```
3.1.0-95.gc8721bf2
```

### Expected behavior

With singularity freshly installed, there should be the `Sylabs Admin` key:

```
$ singularity key list
Public key listing (/home/westleyk/.singularity/sypgp/pgp-public):

0) U: Sylabs Admin () <support@sylabs.io>
   C: 2018-11-01 15:20:02 -0700 PDT
   F: 8883491F4268F173C6E5DC49EDECE4F3F38D871E
   L: 4096
   --------
```

### Actual behavior

No public keys are installed by default:

```bash
$ singularity key list
Public key listing (/home/westleyk/.singularity/sypgp/pgp-public):
# nothing...
```

### Steps to reproduce behavior

With Singularity installed on a fresh system, run:

```
$ singularity key list
```

**Comment by gmkurtzer** [comment]
Is there a global way of dealing with keys today (or planned for the future)?

Meaning, we should install this into a system shared location like `/etc/singularity/keys...`.

**Comment by dtrudg** [comment]
This is not so clear a requirement now that Singularity has moved into HPCng.
