### ISSUE TITLE
[Proposal] Full functionality for non root users

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#285]
Hi guys, I have been chatting with @gmkurtzer the last few days in slack, bouncing ideas off him for a way to completely remove the requirement of root for Singularity. Up until this morning I didn't have anything concrete that I believe could work and is secure, however I think I see a solution now. [Here is a rough sketch of the current bootstrap process for the docker module.](http://i.imgur.com/kd2kb8t.jpg)

You can see at the bottom my first idea: chroot as SUID -> make a user namespace -> proceed with user code execution. I don't think this is very secure for a few reasons, so we scrapped this idea immediately. Drawing from that as inspiration, I think I have now come up with a secure solution, [which we can see here](http://i.imgur.com/gy6bn9t.jpg). This trace starts in the upper right corner with the priv_init() call and roughly traces through the image-mount.c during bootstrap. This image is how I imagine the bootstrap process looking when running as non root.

## How it would work

[image-mount.c: ](http://i.imgur.com/p7FPSRY.jpg)

1. Fork into watchdog process and child process, child process continues at (2)
2. Create user_namespace mapping UID:0 (host:container) where UID refers to calling users UID
3. Call singularity_ns_mnt_unshare() as "root" inside user_namespace
4. Bind mount to loopback device via SUID from host user_namespace (cannot do this inside child user_namespace as "root")
5. Fork into [bootstrap process](http://i.imgur.com/nCBKFdj.jpg)
6. Create new user_namespace (maps 0:0 & UID:0)
7. SUID in host namespace then join user_namespace (now running as real root)
3. install $ROOTFS
4. install $ROOTFS/bin /etc ...
5. mount /proc /dev
6. Exit user_namespace and drop SUID privileges
7. Join user_namespace as UID on host
8.  /bin/sh %setup (Gives "root" access inside $ROOTFS but can't do anything bad on host)
9. chroot $ROOTFS /bin/sh %post (Again gives safe "root" inside $ROOTFS)
10. Exit user_namespace and chroot
11. SUID on host and recursively assign ownership of all files owned by UID in $ROOTFS to root on host
12. Continue with bootstrap as normal, container.img file looks exactly the same as if run with sudo (files inside are actually owned by root)

## Changes we would need to make:

1. Give image-mount.c the ability to SUID. Greg mentioned that we could handle this the same way as we currently handle sexec & sexec-suid, however a better solution might be to refactor the code to allow for more modularity of SUID code.
2. (?) Either add privilege escalation to singularity_rootfs_init() (currently only able to open images owned by calling user, not root) or require that images are owned by calling user (change to singularity create ?)
3. Refactor bootstrap modules into code that can leverage SUID bits and namespaces. We need to be able to control both, and I'm not sure if we would want to do that with the current scripts we are using. Might be better to move bootstrap modules into c code to better interact with the rest of the code base.
4. Implement logic described in the bootstrap process section (mainly handling the SUID parts and namespace parts). We could even keep the current scripts but wrap sections of them inside of c code that can leverage SUID/Namespaces, letting us reuse the current code that works (until we can fully rewrite the bootstrapping modules)

## Security

I believe this proposal introduces no additional vectors of attack for escalating privileges on the host. No user code is ever executed as real root on the computer ever. The %post script which runs in the user_namespace never actually gains real root. All files edited by the code of the %post script will in fact be owned by the original calling user when inspected from outside the user_namespace before the file remapping. After the user code executes, we are safe to remap the files owned by UID into files owned by root on the host, since no more user code is running. The container image will now look identical to as if somebody ran the bootstrap using sudo, meaning it is now a normal singularity container. The remapping of file ownership also preserves portability of the container.

Please scrutinize this proposal, as I might have missed something that will limit us doing this. However from what I can tell this will functionally work, and will be secure as well. That would mean this is safe to implement and would grant users full non-root access. There will of course need to be other work done to port this to other parts of singularity, however this same idea can be applied to other areas of the code and will provide the same result.

**Comment by bbockelm** [comment]
I think this might be overly complicated.  Why not:
1.  `singularity bootstrap ...` creates a temporary directory.
2.  Invoke the `yum` logic (or `apt-get` equivalent) into the temporary directory.
3.  Fork a child process into a new `userns`:
   1.  Utilize `userns` to create a mount NS and  chroot to the temporary directory.
   2.  Mount `/dev`, `/proc` as before with the `userns` code.
   3.  Execute all the bootstrapping inside the temporary directory.
4.  Parent waits for child to exit successfully.
5.  Use `virt-make-fs` to turn temporary directory into a disk image.
6.  Use the `libguestfs` APIs directly to `chown` the files to UID 0 inside the disk image (if desired... is this really required?).

In this setup, no `suid` permissions are required _anywhere_ for kernels with `userns` enabled.

**Comment by bbockelm** [comment]
Note the above proposal ruins the split between `create` and `bootstrap`.  I might actually be OK with that (I don't particularly care for the split myself...).

However, it can be modified to re-introduce `setuid` only for setting up the loopback device.  That would have the secondary advantage of having code that would allow file-based images for `singularity exec` in user-namespace mode (currently we are limited to directories).

In such a case, (1) above would be replaced with a `setuid` binary that creates the FS namespace and mounts the loopback device.  It would then drop privileges permanently and exec the binary for steps (2) - (6).

**Comment by vsoch** [comment]
I'm definitely in support, as long as some of the the higher level bootstrap module (e.g. Docker) can stay in Python, which makes a lot more sense for using to make http requests,  etc.

**Comment by bauerm97** [comment]
@vsoch I think this is definitely possible to do. We could potentially create a bootstrap.c (or equivalent) binary that runs certain aspects of logic, and then calls on the python modules for pulling the docker layers, and leverages certain sections of the current bootstrap modules for code we already have written (such as chroot into the directory and run %post).

**Comment by bauerm97** [comment]
Here is some thought about how we could properly port the current bootstrapping shell scripts into c code.

/src/image-bootstrap.c
/src/lib/bootstrap/bootstrap.c
/src/lib/bootstrap/module-name/module-name.c
/src/lib/bootstrap/pre/prebootstrap.c
/src/lib/bootstrap/post/postbootstrap.c

Something like this structure might work well?

**Comment by bauerm97** [comment]
For anybody interested, I have opened up a branch on my fork where I am working on rebasing the bootstrapping code into C. Feel free to contribute https://github.com/bauerm97/singularity/tree/bootstrap-refactor

**Comment by bbockelm** [comment]
Just a random thought - it's super easy to invoke python from a C function.  Would we be able to move the control structure into C, yet move some of the shell scripts into a higher level language (such as python)?

**Comment by vsoch** [comment]
we already have some python modules for bootstrap

https://github.com/singularityware/singularity/tree/master/libexec/python

is that what you mean? The limitation is that only modules installed on system python, across OS, are allowed ( @gmkurtzer )

**Comment by bauerm97** [comment]
@bbockelm this is what I have been planning on. We will control most of the logic in the C binary, but inside of bootstrap/docker/docker.c we will simply call on the currently existing docker Python code. If we want to write out other sections in Python it's now really easy to implement, we just include a call to the appropriate Python module in the relevant bootstrap/module-name/module-name.c

**Comment by csbrown** [comment]
@bauerm97 whatever happened with this?  Did this become an issue and/or get implemented?
