### ISSUE TITLE
All files in container owned by root

### ISSUE THREAD

**Issue by obreitwi** [apptainer/singularity#2860]
## Version of Singularity:

`3.0.3+ds`

### Expected behavior

When creating an image from a sandbox as root, files inside the container should retain their owner.
This was the case with singularity 2.x.

### Actual behavior

All files in the container are owned by root even though the container was build via root (i.e., `-all-root` does not get set for `mksquashfs`).

### Steps to reproduce behavior

1. Create sandbox from recipe.
```
sudo -E singularity build --sandbox "${TARGET_FOLDER}" "${RECIPE}"
```
2. Create image from sandbox.
```
sudo singularity build "${IMAGE_NAME}" "${TARGET_FOLDER}"
```

### Notes

I noticed that instead of creating the image in-place (as singularity 2.x used to do), the whole sandbox gets (needlessly?) copied to `/tmp/sbuild-XXXXXXXXXX` via `cp -r`. This changes the owner of all files to root (as well as elongating the build process). 
It would be great if this behavior could be toggled-off (to resemble singularity 2.x).

**Comment by Conzar** [comment]
I have this problem doing the following:

docker image --> sif --> singularity container

Note, several of the services running in the container FAIL due to not having the proper owner/groups.  Is there any way to work around this issue?

**Comment by obreitwi** [comment]
> Is there any way to work around this issue?

We have gone back to building image files with singularity 2.6 for the time being.

The fix should be straight forward, though: Replace `cp -r` with  `cp -a` so that permissions are preserved. Much rather, the need to copy all files in the container should be circumvented. For larger containers (several GiBs), this does somewhat increase container build times. Plus, singularity 2.x also does not copy all files prior to creating the squashfs image.

**Comment by jscook2345** [comment]
@Conzar 

Without knowing how you're building or running your container, its difficult to tell. Could you please open a new issue with more specific details? Thanks!

@obreitwi 

I'm not able to reproduce this problem with the `master` version of `singularity`. Could you provide a definition file example so I can try and reproduce the problem?

**Comment by obreitwi** [comment]
> I'm not able to reproduce this problem with the `master` version of `singularity`. Could you provide a definition file example so I can try and reproduce the problem?

The error appears when creating an image from a sandbox, not a recipe. The aforementioned 
[line in question](https://github.com/sylabs/singularity/blob/9c664ea13325cec9d4f3555c4e2e8417762a93b9/internal/pkg/build/sources/packer_sandbox.go#L31) is still present in current master. Just take any sandbox, build it into an image and all files will be owned by root…

**Comment by rherban** [comment]
I spoke with @ikaneshiro about this and he acknowledged it's definitely not working as intended.

**Comment by kadeng** [comment]
Please review my pull request. I just made some minimal changes, and it worked for me. Tested it manually with v3.5.0.
