### ISSUE TITLE
`singularity keys push` overwrites my api token

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2862]
## Version of Singularity:

master

### Expected behavior

`singularity keys push <FINGERPRINT>` works

### Actual behavior

`singularity keys push <FINGERPRINT>` fails with

<pre>
INFO:    Access token is expired or missing. To update or obtain a token:
  1) Go to : https://cloud.sylabs.io/
  2) Click "Sign in to Sylabs" and follow the sign in steps
  3) Click on your login id (same and updated button as the Sign in one)
  4) Select "Access Tokens" from the drop down menu
  5) Click the "Manage my API tokens" button from the "Account Management" page
  6) Click "Create"
  7) Click "Copy token to Clipboard" from the "New API Token" page
  8) Paste the token string to the waiting prompt below and then press "Enter"

WARNING: this may overwrite a previous token if ~/.singularity/sylabs-token exists

Paste Token HERE:
</pre>

I hit enter because I do have a valid token and I don't want it overwritten. However hitting enter is the wrong choice and the token is overwritten. Perhaps the token input is too much here and should either be removed or have an option to not do it?

### Steps to reproduce behavior

Download my token from staging
`singularity keys push <FINGERPRINT>`
<failure>

**Comment by WestleyK** [comment]
Closing, I believe this is not a issue anymore. Please reopen if not.
