### ISSUE TITLE
Consider a `-t|--token` option to `singularity keys` that allows you to specify a path to a token

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2863]
It seems like specifying a path to a token fits within our normal command setup.

**Comment by jscook2345** [comment]
I don't know why I opened this. `singularity -t` does this. Maybe I meant keychain instead of token?

@WestleyK 

Sorry if I'm crazy, but I do not see a way to change the directory your keys are stored in. Should that be configurable?

**Comment by WestleyK** [comment]
Closing as `SINGULARITY_SYPGPDIR` solves this.
