### ISSUE TITLE
Print key information before asking if I want to store a new key

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2869]
## Version of Singularity:

master

### Expected behavior

Verifying image: alpine_latest.sif
INFO:    key missing, searching key server for KeyID: EDECE4F3F38D871E...
INFO:    key retrieved successfully!
<PRINT OUT INFO THAT WOULD NORMALLY BE IN KEY LIST SO I KNOW WHO'S KEY THIS IS>
Store new public key 8883491F4268F173C6E5DC49EDECE4F3F38D871E? [Y/n]
</pre>

### Actual behavior

<pre>
Verifying image: alpine_latest.sif
INFO:    key missing, searching key server for KeyID: EDECE4F3F38D871E...
INFO:    key retrieved successfully!
Store new public key 8883491F4268F173C6E5DC49EDECE4F3F38D871E? [Y/n] n
Data integrity checked, authentic and signed by:
        Sylabs Admin <support@sylabs.io>, KeyID EDECE4F3F38D871E
</pre>

**Comment by WestleyK** [comment]
Originally, #2821 *Would* have fixed this issue. But it has been decided to *never store a public key when verifying a container*.

#2821 should *fix* this issue by removing the cause, instead of the problem :scream_cat:

**Comment by WestleyK** [comment]
This should be resolved. Reopen if needed :+1:
