### ISSUE TITLE
"dev = minimal" without overlay: confusing error message

### ISSUE THREAD

**Issue by flx42** [apptainer/singularity#287]
Fresh singularity install with a single configuration change:
```patch
--- a/etc/singularity.conf
+++ b/etc/singularity.conf
@@ -66,7 +66,7 @@ mount sys = yes
 # Shoudl we automatically bind mount /dev within the container? If you select
 # minimal, and if overlay is enabled, then Singularity will attempt to create
 # the following devices inside the container: null, zero, random, urandom
-mount dev = yes
+mount dev = minimal
```
(There is also a typo: **Shoudl** -> **Should**)

```sh
$ mkdir centos
$ singularity import centos docker://centos:7
$ singularity shell centos 
ERROR  : Unsupported value for configuration boolean key 'mount dev' = 'minimal'
ERROR  : Returning default value: yes
ABORT  : Retval = 255
```

It's because if we have `dev = minimal` and `overlay = no`, this [call](https://github.com/singularityware/singularity/blob/master/src/lib/mount/dev/dev.c#L93) is executed, but `minimal` is not a boolean value. You probably need a `singularity_config_get_value` instead.

It's also rather confusing, you have to increase verbosity to really understand why it's happening:
```
$ singularity -vv shell centos
[...]
VERBOSE: Not enabling 'mount dev = minimal', overlayfs not enabled
```
Bumping the visibility of [this call](https://github.com/singularityware/singularity/blob/master/src/lib/mount/dev/dev.c#L87) might be useful too.

**Comment by gmkurtzer** [comment]
Good catch. The appropriate fix is to properly error out which as you mentioned was not happening. Just committed this [master af45302] which should fix that as follows:

```
$ singularity shell /tmp/Centos-7/
ERROR  : Config option 'mount dev = minimal', requires overlayFS
ABORT  : Retval = 255
```
