### ISSUE TITLE
Should a container be allowed to have multiple signatures?

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2870]
<pre>
[vagrant@localhost singularity]$ singularity verify alpine_latest.sif
Verifying image: alpine_latest.sif
INFO:    key missing, searching key server for KeyID: EDECE4F3F38D871E...
INFO:    key retrieved successfully!
Store new public key 8883491F4268F173C6E5DC49EDECE4F3F38D871E? [Y/n] n
Data integrity checked, authentic and signed by:
        Sylabs Admin <support@sylabs.io>, KeyID EDECE4F3F38D871E
        Justin Cook (test) <jcook@k-lug.org>, KeyID AC2039AB818717E8
</pre>

Should having multiple keys be allowed?

**Comment by WestleyK** [comment]
I think that will be a great feature! :+1:

**Comment by jscook2345** [comment]
@WestleyK 

It already works that way :). I'm just checking to see if that is a valid thing. Should it have more than one?

**Comment by ArangoGutierrez** [comment]
Yes it does, we make use of this via the `ecl.toml` file to whitelist/blacklisting feature
