### ISSUE TITLE
state which keys signed an image before attempting to search for them

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2872]
## Version of Singularity:

master

### Expected behavior

<pre>
[vagrant@localhost singularity]$ singularity verify temp_latest.sif
Verifying image: temp_latest.sif
INFO:    temp_latest.sif signed by <XYZ>
INFO:    temp_latest.sig signed by <ZYX>
INFO:    key missing, searching key server for KeyID: XYZ
...
INFO:    key missing, searching key server for KeyID: ZYX
...   
</pre>

### Actual behavior

<pre>
[vagrant@localhost singularity]$ singularity verify temp_latest.sif
Verifying image: temp_latest.sif
INFO:    key missing, searching key server for KeyID: ...
</pre>

**Comment by WestleyK** [comment]
This seems to be fixed in master:

```
$ singularity verify alpine_latest.sif 
Verifying image: alpine_latest.sif
INFO:    Key with ID EDECE4F3F38D871E not found in local keyring, downloading from keystore...
INFO:    Container is signed
Data integrity checked, authentic and signed by:
	Sylabs Admin <support@sylabs.io>, Fingerprint 8883491F4268F173C6E5DC49EDECE4F3F38D871E
```
