### ISSUE TITLE
Fix help title for verify command

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2876]
## Version of Singularity:

master

### Expected behavior

[vagrant@localhost ~]$ singularity help verify
Verify cryptographic signatures on a container

### Actual behavior

[vagrant@localhost ~]$ singularity help verify
Verify cryptographic signatures on container

Missing the `a` between `on` and `container`.

**Comment by dtrudg** [comment]
Now says:
```
dave@piran~> singularity help verify
Verify cryptographic signatures attached to an image
```
