### ISSUE TITLE
Fix the help title for the sign command

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2877]
## Version of Singularity:

master

### Expected behavior

[vagrant@localhost ~]$ singularity help sign
Attach cryptographic signatures to a container

### Actual behavior

[vagrant@localhost ~]$ singularity help sign
Attach cryptographic signatures to container

Missing `a` between `to` and `container`.

**Comment by dtrudg** [comment]
Now (3.5.0-rc.2) says...

```
dave@piran~> singularity help sign
Attach a cryptographic signature to an image
```
