### ISSUE TITLE
Empty device files with "dev = minimal"

### ISSUE THREAD

**Issue by flx42** [apptainer/singularity#288]
When doing a `singularity import` as non-root, the [following commands](https://github.com/singularityware/singularity/blob/34652e3c65a229654b44996fdbf8ba12b090d81f/libexec/bootstrap/modules-v2/prebootstrap.sh#L45-L48) will fail silently and produce empty files instead of actual devices, why is that so?
```
$ mkdir ubuntu
$ singularity import ubuntu docker://ubuntu
$ ls -l ubuntu/dev/
-rw-rw-r-- 1 fabecassis fabecassis 0 Oct 31 20:22 null
-rw-rw-r-- 1 fabecassis fabecassis 0 Oct 31 20:22 random
-rw-rw-r-- 1 fabecassis fabecassis 0 Oct 31 20:22 urandom
-rw-rw-r-- 1 fabecassis fabecassis 0 Oct 31 20:22 zero
```
Doing that interferes with the option `dev = minimal`:
```
$ singularity -vv shell ubuntu
[...]
VERBOSE: Can not create /dev/null: File exists
VERBOSE: Can not create /dev/null: File exists
VERBOSE: Can not create /dev/random: File exists
VERBOSE: Can not create /dev/urandom: File exists
[...]
```
The empty files will prevent the `mknod` from working, and thus your container can't use the kernel RNG.

**Comment by gmkurtzer** [comment]
I think this is fixed now. Will you retest against master?

Thanks!

**Comment by flx42** [comment]
Seems OK! Thanks!

By the way, there is also a typo: https://github.com/singularityware/singularity/blob/31038ff4244dec97787bc0526b1a26233f332295/src/lib/mount/dev/dev.c#L65
Should be `/dev/zero` here.

**Comment by gmkurtzer** [comment]
Got the typo, thanks! :)
