### ISSUE TITLE
Problems with new unprivileged docker image run

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2880]
## Version of Singularity:

master branch including #2838

### Expected behavior

similar behavior to singularity-2.6, or at least information about what is happening

### Actual behavior

When running unprivileged, docker containers are first converted to sif and then to a "sandbox" unpacked directory.  The step converting to "sandbox" can take quite a long time, and there is no notice this is happening unless debugging is enabled.   Then when the container exits, it takes an additional long time to delete the sandbox, again quietly doing it without any explanation.  One time when I did this while on an NFS home directory and not running any other processes I also got this error message:
```
ERROR:   failed to delete container image /cloud/login/dwd/.singularity/tmp/rootfs-848023522: remove /cloud/login/dwd/.singularity/tmp/rootfs-848023522/.nfs00000000a4960a57000000b1: device or resource busy
```
So it appears that something was holding open a file descriptor into the sandbox area while it was attempting to delete it.  I haven't looked into what yet.

I think at least the sandbox should also be kept in the cache, and an INFO message printed while it is being created.  In singularity-2.6 it didn't create the intermediate sif image, it just created the sandbox and used it, which was considerably faster.  I think it's OK to create the intermediate sif image, even though it will be unlikely to be used when running unprivileged, but only if the sandbox version is also kept in the cache so the next time it will run considerably faster.

### Steps to reproduce behavior

The command I ran which resulted in the above error was:
```
singularity exec -u docker://centos bash
```
and then I exited the bash shell without running anything else.

I think this will be of interest to @afortiorama, @cclerget, and @bauerm97

**Comment by DrDaveD** [comment]
Actually singularity-2.6 also unpacked the docker tar into a temporary directory every time and removed it when finished, but it appears much slower to me because singularity-3 puts the unpacked files under ~/.singularity and singularity-2.6 put it in /tmp.  In my case /tmp is a local disk and ~ is an NFS file server, so it is much slower.  Mileage may vary, but I still think it should at least print INFO files about what it is doing.  Maybe singularity-3 should also use /tmp.

**Comment by DrDaveD** [comment]
I have been getting the failed to delete nfs error just about every time.  I see an open file descriptor (number 3) in the parent of the rootfs-* directory and I think that's what's causing it.  I haven't yet been able to figure out where it is getting opened and where the file descriptor number is stored.

**Comment by DrDaveD** [comment]
I have done a lot more investigation on the nfs issue.  I got the file descriptor to the image closed, but it didn't help.  The file that can't be deleted is the only file in the top-level root directory, which is called anaconda-post.log.  Everything else in the top level is either a symlink or a directory.  There are no file descriptors open to it.  However, there is a bind mount from it to the namespace!  It's a result of the underlay feature.  Now I have an idea how to fix it.

**Comment by DrDaveD** [comment]
@cclerget  I need your input on how to handle this.  I'm not sure that the "Singularity runtime parent" is left with privileges to unmount these bind mounts, do you know?  Is there some way to exit the namespace so everything is automatically unmounted?  I suppose a possibility would be to introduce yet another intermediate process, but I don't think any of us wants to do that.  Another possibility would be to go back to using /tmp for this temporary directory tree, because it can handle completely removing the directory entries of files that are still accessed, and to fully clean up when the process accessing the files exits.  Or treat it like one of the cache types, and use cache clean manually to delete it.  I kind of like that idea the best.

**Comment by DrDaveD** [comment]
@mem can you please reopen this, it is not finished.

**Comment by cclerget** [comment]
@DrDaveD Once in `CleanupContainer` the container is considered stopped at least the first process was killed and catched by `Wait4`, however there is two mount namespaces involved a first one where "Singularity runtime parent" live in, and another nested one where the container process live in. The purpose of first mount namespace is to allow mount ocuring in "parent process" to be propagated to container process (eg: to implement FUSE mount), but the second mount namespace can't propagate mount to the first one for security reasons. Maybe the issue lies in first mount namespace (think of tmpfs mount for underlay shared between two mount namespaces), and yes the parent process should have privileges to unmount things in `CleanupContainer`
