### ISSUE TITLE
Singularity fails silently on macOS

### ISSUE THREAD

**Issue by pditommaso** [apptainer/singularity#2881]
## Version of Singularity:

Singularity 3.1.0 on macOS (10.14.2)
go version go1.11.5 darwin/amd64

### Expected behavior

Run a container

### Actual behavior

Silently fail 

### Steps to reproduce behavior

``` bash
$ ./singularity --version
$ ./singularity pull library://godlovedc/funny/lolcow
$ ./singularity run lolcow_latest.sif hello 
$ echo $?
0
``` 

Tried also with other containers same behaviour

**Comment by jmstover** [comment]
@pditommaso ... Where did you build this from or obtain it? Pulling from current master this is what I get (using singularity from `builddir/`):

```
$ ./singularity --version
singularity version 3.1.0-273.g2b23e12a
$ ./singularity pull library://godlovedc/funny/lolcow
WARNING: No default remote in use, falling back to: https://library.sylabs.io
INFO:      Downloading library image
[...]
$ ./singularity run lolcow_latest.sif hello
FATAL:   Failed to find hypervisor executable at /usr/local/libexec/singularity/vm/xhyve
```

I do need to fix that error message there though.... 

*Edit:*
```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G5019
```

**Comment by pditommaso** [comment]
Downloading it from the release page.

**Comment by jmstover** [comment]
The binary linked off of here then?
https://www.sylabs.io/singularity-desktop-macos/

**Comment by pditommaso** [comment]
Nope, the tar [here](https://github.com/sylabs/singularity/releases/tag/v3.1.0) and compiled it.

**Comment by jmstover** [comment]
I would have expected you to get more output ... but 3.1.0 was released prior to us merging the code for running on a Mac. The alpha tarball there on the page I linked to has everything you need including the hypervisor, and extra bits that's needed.

**Comment by dtrudg** [comment]
Closing - the desktop version is working. If you build from source without the hypervisor etc, it will now say....

```
dtrudg@dt-sylabs~/G/s/builddir> ./singularity run docker://alpine
FATAL:   Filed to Stat() xhyve binary: stat /usr/local/libexec/singularity/vm/xhyve: no such file or directory
```
