### ISSUE TITLE
Makefile Failes on Rhel 7.6

### ISSUE THREAD

**Issue by rangavas** [apptainer/singularity#2910]
## Version of Singularity:

Write here.

### Expected behavior

Write here.

### Actual behavior

Write here.

### Steps to reproduce behavior

Write here.

The Makefile script fails ON RHel 7.6 . I have installed al the components and i get the following error. Please help.

[root@tlvisurya1 builddir]# ./Makefile
./Makefile: line 9: V: command not found
./Makefile: line 12: BUILDDIR: command not found
./Makefile: line 13: BUILDDIR_ABSPATH: command not found
./Makefile: line 14: SOURCEDIR: command not found
./Makefile: line 15: SCRIPTSDIR: command not found
./Makefile: line 16: CONTRIBDIR: command not found
./Makefile: line 17: PREFIX: command not found
./Makefile: line 18: EXECPREFIX: command not found
./Makefile: line 19: BINDIR: command not found
./Makefile: line 20: SBINDIR: command not found
./Makefile: line 21: LIBEXECDIR: command not found
./Makefile: line 22: DATAROOTDIR: command not found
./Makefile: line 23: DATADIR: command not found
./Makefile: line 24: SYSCONFDIR: command not found
./Makefile: line 25: SHAREDSTATEDIR: command not found
./Makefile: line 26: LOCALSTATEDIR: command not found
./Makefile: line 27: RUNSTATEDIR: command not found
./Makefile: line 28: INCLUDEDIR: command not found
./Makefile: line 29: OLDINCLUDEDIR: command not found
./Makefile: line 30: DOCDIR: command not found
./Makefile: line 31: INFODIR: command not found
./Makefile: line 32: HTMLDIR: command not found
./Makefile: line 33: DVIDIR: command not found
./Makefile: line 34: PDFDIR: command not found
./Makefile: line 35: PSDIR: command not found
./Makefile: line 36: LIBDIR: command not found
./Makefile: line 37: LOCALEDIR: command not found
./Makefile: line 38: MANDIR: command not found
./Makefile: line 39: RPMPREFIX:=: command not found
./Makefile: line 41: NAME: command not found
./Makefile: line 42: SHORT_VERSION: command not found
./Makefile: line 43: VERSION: command not found
./Makefile: line 45: HOSTAR: command not found
./Makefile: line 46: HOSTCC: command not found
./Makefile: line 47: HOSTCXX: command not found
./Makefile: line 48: HOSTLD: command not found
./Makefile: line 49: HOSTRANLIB: command not found
./Makefile: line 50: HOSTSIZE: command not found
./Makefile: line 51: HOSTOBJCOPY: command not found
./Makefile: line 53: AR: command not found
./Makefile: line 54: CC: command not found
./Makefile: line 55: CXX: command not found
./Makefile: line 56: LD: command not found
./Makefile: line 57: RANLIB: command not found
./Makefile: line 58: SIZE: command not found
./Makefile: line 59: OBJCOPY: command not found
./Makefile: line 61: ARCH: command not found
./Makefile: line 62: LDFLAGS: command not found
./Makefile: line 65: all:: command not found
./Makefile: line 70: CLEANFILES: command not found
./Makefile: line 73: AFLAGS: command not found
./Makefile: line 75: CFLAGS: command not found
./Makefile: line 76: CFLAGS: command not found
./Makefile: line 77: CFLAGS: command not found
./Makefile: line 78: CFLAGS: command not found
./Makefile: line 79: CFLAGS: command not found
./Makefile: line 80: CFLAGS: command not found
./Makefile: line 81: CFLAGS: command not found
./Makefile: line 82: CFLAGS: command not found
./Makefile: line 84: LDFLAGS: command not found
./Makefile: line 89: GO_TAGS: command not found
./Makefile: line 90: GO_LDFLAGS: command not found
./Makefile: line 91: GO_BUILDMODE: command not found
./Makefile: line 95: GO_TAGS: command not found
./Makefile: line 99: GO_TAGS: command not found
./Makefile: line 106: CFLAGS: command not found
./Makefile: line 107: LDFLAGS: command not found
./Makefile: line 113: GO_LDFLAGS: command not found
./Makefile: line 121: _OBJ: command not found
./Makefile: line 128: all:: command not found
./Makefile: line 130: CLEANFILES: command not found
./Makefile: line 137: SOURCEDIR: command not found
./Makefile: line 137: singularity_build_config: command not found
./Makefile: line 138: singularity_build_config: command not found
./Makefile: line 138: BUILDDIR: command not found
./Makefile: line 139: V: command not found
./Makefile: line 139: singularity_build_config: command not found
./Makefile: line 140: V: command not found
./Makefile: line 140: BUILDDIR_ABSPATH: command not found
./Makefile: line 140: SOURCEDIR: command not found
./Makefile: line 140: cd: /internal/pkg/buildcfg: No such file or directory
./Makefile: line 142: singularity_build_config: command not found
./Makefile: line 142: CLEANFILES: command not found
./Makefile: line 145: SOURCEDIR: command not found
./Makefile: line 145: SOURCEDIR: command not found
./Makefile: line 145: shell: command not found
./Makefile: line 145: singularity_SOURCE: command not found
./Makefile: line 147: BUILDDIR: command not found
ERROR: Unknown command ':='
./Makefile: line 148: singularity_build_config: command not found
./Makefile: line 148: singularity_SOURCE: command not found
./Makefile: line 148: USAGE:: command not found
./Makefile: line 149: @echo: command not found
./Makefile: line 149: GO_TAGS: command not found
    [+] GO_TAGS ""
./Makefile: line 150: V: command not found
./Makefile: line 150: GO_BUILDMODE: command not found
./Makefile: line 150: GO_TAGS: command not found
./Makefile: line 150: GO_LDFLAGS: command not found
./Makefile: line 150: BUILDDIR: command not found
./Makefile: line 150: SOURCEDIR: command not found
./Makefile: line 150: go: command not found
./Makefile: line 152: DESTDIR: command not found
./Makefile: line 152: BINDIR: command not found
./Makefile: line 152: singularity_INSTALL: command not found
./Makefile: line 153: singularity_INSTALL: command not found
./Makefile: line 154: @echo: command not found

**Comment by bauerm97** [comment]
@rangavas Please try running this command from the source directory:

`make -C builddir`

**Comment by bauerm97** [comment]
I'm going to close this as I'm pretty sure this is not an issue on our end. Please re-open if you feel this isn't solved.

**Comment by rangavas** [comment]
I am seeing just one version  getting compiled.  I am not able to get 2 versons installed on the same box. Can you  please help.

________________________________

**Comment by jscook2345** [comment]
@rangavas 

You need to configure each build with a path setting to `mconfig` for multiple installations.

Example:

Download 3.0 source
<pre>
./mconfig -p /usr/local/singularity/3.0
make -C builddir
sudo make -C builddir install
</pre>

Download 3.1 source
<pre>
./mconfig -p /usr/local/singularity/3.1
make -C builddir
sudo make -C builddir install
</pre>

You will still need to set things like 'PATH' post install.

**Comment by rangavas** [comment]
Thanks for all the responses even on Sunday. My salute to the replies and support that is offered. I am new to singularity and it could be me. This is what I get. I am installing into a shared gpfs filesystem so that I can keep multiple versions and I was using ./mconfig --prefix dir path and I now I tried ./mconfig -p Path


make -C builddir
find: â/admin/software/singularity-3.0.2/singularity/cmd/startergithub.com/sylabs/singularity/internal/app/starterâ: No such file or directory
find: â/admin/software/singularity-3.0.2/singularity/cmd/startergithub.com/sylabs/singularity/internal/pkg/runtime/enginesâ: No such file or directory
find: â/admin/software/singularity-3.0.2/singularity/cmd/startergithub.com/sylabs/singularity/internal/pkg/runtime/engines/config/starterâ: No such file or directory
find: â/admin/software/singularity-3.0.2/singularity/cmd/startergithub.com/sylabs/singularity/internal/pkg/sylogâ: No such file or directory
find: â/admin/software/singularity-3.0.2/singularity/cmd/startergithub.com/sylabs/singularity/internal/pkg/util/mainthreadâ: No such file or directory
find: â/admin/software/singularity-3.0.2/singularity/cmd/singularitygithub.com/sylabs/singularity/cmd/singularity/cliâ: No such file or directory
find: â/admin/software/singularity-3.0.2/singularity/cmd/singularitygithub.com/sylabs/singularity/internal/pkg/buildcfgâ: No such file or directory
find: â/admin/software/singularity-3.0.2/singularity/cmd/singularitygithub.com/sylabs/singularity/pkg/util/user-agentâ: No such file or directory
make: Entering directory `/admin/software/singularity-3.0.2/singularity/builddir'
 CSCOPE
 DEPENDS
 GO singularity
../cmd/singularity/cli.go:9:2: cannot find package "github.com/sylabs/singularity/cmd/singularity/cli" in any of:
        /usr/lib/golang/src/github.com/sylabs/singularity/cmd/singularity/cli (from $GOROOT)
        /root/go/src/github.com/sylabs/singularity/cmd/singularity/cli (from $GOPATH)
../cmd/singularity/cli.go:10:2: cannot find package "github.com/sylabs/singularity/internal/pkg/buildcfg" in any of:
        /usr/lib/golang/src/github.com/sylabs/singularity/internal/pkg/buildcfg (from $GOROOT)
        /root/go/src/github.com/sylabs/singularity/internal/pkg/buildcfg (from $GOPATH)
../cmd/singularity/cli.go:11:2: cannot find package "github.com/sylabs/singularity/pkg/util/user-agent" in any of:
        /usr/lib/golang/src/github.com/sylabs/singularity/pkg/util/user-agent (from $GOROOT)
        /root/go/src/github.com/sylabs/singularity/pkg/util/user-agent (from $GOPATH)
make: *** [singularity] Error 1
make: Leaving directory `/admin/software/singularity-3.0.2/singularity/builddir'
[root@plvimphctrl1 singularity]#


________________________________

**Comment by jscook2345** [comment]
@rangavas 

At the moment, go is very particular in where software is built from. Typically you need to download go packages to an appropriate `GOPATH` and build from there.

If you look at our `INSTALL.md` guide, you can see better how to handle the `GOPATH` with an example.

https://github.com/sylabs/singularity/blob/master/INSTALL.md

You can start from the part just after the Go installation, where they set `GOPATH` and `PATH`.

**Comment by mem** [comment]
I just double checked, and the current version of singularity (3.4) can be built by cloning the repo into any directory and without setting any environment variables or anything like that.

I'm not quite sure which exact commit fixed this, but I'm pretty sure I did this around the 3.2 or 3.3 timeframe.

I'll close this issue as I consider it fixed. Please feel free to reopen or file a new one if you find otherwise.
