### ISSUE TITLE
how to handle this error in creating an image from recipe

### ISSUE THREAD

**Issue by youngestuser** [apptainer/singularity#2913]
## Version of Singularity:

singularity-2.4

### Expected behavior

build a image from recipe

### Actual behavior
singularity build env.image tensorflow-1.6-gpu-cuda90
an error occur : ABORT: Aborting with RETVAL=255
Cleaning up...

### Steps to reproduce behavior
Anybody konw how to solve this problem?

**Comment by youngestuser** [comment]
singularity recipe
Bootstrap: docker
From: nvidia/cuda:9.0-cudnn7-runtime-centos7

%post
    # install other needed packages
    yum update
    yum install -y wget  \
         vim
    wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-4.5.1-Linux-x86_64.sh
    bash /home/Miniconda3-4.5.1-Linux-x86_64.sh -b -p /home/miniconda3
    rm /home/Miniconda3-4.5.1-Linux-x86_64.sh
    source /.bashrc
    conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
    conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
    conda config --set show_channel_urls yes
    conda creat -n lwz python=3.6
    conda activate lwz
%environment
    export PATH=/home/miniconda3/bin:$PATH

**Comment by youngestuser** [comment]
look forward to your help ,thank you!

**Comment by jscook2345** [comment]
@youngestuser 

Can you run with the `-d` flag and provide us the debug output from your `build` command?

**Comment by youngestuser** [comment]
@jscook2345  Thank you for your reply ,I have solved it by add some command lines in the recipe,I wonder it may lack "yum -y install epel-release" above.

**Comment by jscook2345** [comment]
@youngestuser 

Glad it worked out!
