### ISSUE TITLE
`--version` option missing for `singularity help`

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2921]
## Version of Singularity:

3.1.0

### Expected behavior

`singularity help` should match `singularity --help`

### Actual behavior

`singularity help` is missing the `--version` option

### Steps to reproduce behavior

`singularity help`

**Comment by bauerm97** [comment]
I think this is actually because `--version` is something that `cobra` and `pflag` are adding automatically and is marked as hidden by default. We *might* be able to do:

`SingularityCmd.Flags().Lookup("version").Hidden = False`

**Comment by GodloveD** [comment]
This seems like it ought to be kindof low on the priority list imho.

**Comment by mem** [comment]
Interesting:

```
$ builddir/singularity --help
...
Options:
  -d, --debug     print debugging information (highest verbosity)
  -h, --help      help for singularity
      --nocolor   print without color output (default False)
  -q, --quiet     suppress normal output
  -s, --silent    only print errors
  -v, --verbose   print additional information
      --version   version for singularity
...

$ builddir/singularity --help
...
Options:
  -d, --debug     print debugging information (highest verbosity)
  -h, --help      help for singularity
      --nocolor   print without color output (default False)
  -q, --quiet     suppress normal output
  -s, --silent    only print errors
  -v, --verbose   print additional information
...
```

and that's the only difference in the output.

**Comment by dtrudg** [comment]
Going to close this as a won't fix. I think its extremely low impact, and not worth the effort of coding around cobra more than we do at present.
