### ISSUE TITLE
`singularity` usage versus help

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2922]
## Version of Singularity:

3.1.0

Running just `singularity` outputs a usage that I'm not sure is as helpful as `singularity help`. Perhaps that should be changed?

**Comment by ArangoGutierrez** [comment]
that's cobra default for no following CMD, but was also a default on 2.X for nil CMD after `singularity`

**Comment by mem** [comment]
I actually find the output of singularity without flags or commands quite helpful, as it's only the list of commands without other info. The output does mention `--help`, too.

**Comment by mem** [comment]
I'm closing this. Please feel free to reopen if you think there's a good reason to make the two outputs match.
