### ISSUE TITLE
`--quiet` and `--silent` do not suppress help output

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2924]
## Version of Singularity

3.1.0

### Expected behavior

`singularity --quiet --help` # No output
`singularity --silent --help` # No output

### Actual behavior

Both of the above commands emit the help output.

**Comment by dtrudg** [comment]
Had some chat with @EmmEff about this, who raised the point that this isn't really a case of making `--quiet` and `--silent` apply here... it's more that they shouldn't be allowed with `--help` as they conflict with the purpose of getting help output.

Looking into it, given that `--help` is something that cobra provides, we'd have to add a hacky handler around it to make it conflict with `--quiet` and `--silent`, I think fixing is more effort that is warranted. We can probably just live with this indefinitely.

If others feel strongly, feel free to reopen.
