### ISSUE TITLE
Capitalize options descriptions

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2925]
## Version of Singularity:

3.1.0

### Expected behavior

Descriptions for each option under `Options:` is capitalized, similar to `Available Commands:` description for each command.

### Actual behavior

The descriptions for each option are not capitalized.

**Comment by bauerm97** [comment]
This is really not clear enough? Where/what are you reading from?

**Comment by jscook2345** [comment]
When options require multiple sentences to describe (such as when the option has options), it can look a little odd (at least to me).

<pre>
      --log-format string    set the format for the log file. The format
                             may be basic, kubernetes or json (default
                             "kubernetes")
</pre>

I know it is a 'go-thing' to use all lower case for errors. Perhaps we should adopt that for docs to? I've seen apps do both (go tools uses all lower case, hub uses upper case).

**Comment by mem** [comment]
Looking at what's already there, there are about 130 cases where the text starts with a lowercase letter and about 10 where it starts with an uppercase letter.

I understand what you mean by a little odd, but it's the most common way. Looking at several programs (man, grep, sed, perl, ls, mksquashfs, ...) it's not unusual. The other way (capital letter starting the sentence) also happens a lot.

I say we go for consistency.
