### ISSUE TITLE
Discuss: URI vs. Repository

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2931]
## Version of Singularity:

3.1.0

When discussing things like `push` and `pull`, we are saying we act on a `URI`, which technically is correct, but perhaps we should be using the `Repository` term instead?

Library, Shub, and Docker Repos are all technically image repos right?

What do you think?

**Comment by dtrudg** [comment]
We can now also pull from bare http etc. which isn't a repository. URI is the superset here, so will close this pending any further thought.
