### ISSUE TITLE
Discuss: Should we list more ways to contact us in `singularity help`

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2934]
## Version of Singularity:

3.1.0

At the end of `singularity help` we have the following:

<pre>
For additional help or support, please visit https://www.sylabs.io/docs/
</pre>

Should we include our github and slack pages here? With info on opening issues or joining us on slack?

**Comment by jscook2345** [comment]
Or maybe specifically link them to: https://www.sylabs.io/guides/3.0/user-guide/contributing.html

Since our contributing section has all that info? Good job user-docs! :)

**Comment by bauerm97** [comment]
I'm on board with adding more contact info, but also don't think it's critical. I'm happy either way.
