### ISSUE TITLE
[Proposal] Refactor of image-X binaries into unified simage binary

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#294]
Hi all, in my never ending quest to remove all root restrictions for Singularity I've come upon a way that I think we could improve the workflow of the application (which will make it easier in the long run to implement new features). Currently the relevant .exec file in `libexec/cli/`calls upon the relevant binary. For instance, all commands that pertain with running the image call upon `sexec`. However, the commands pertaining with image modification all call upon separate binaries to do different work. Some call `image-mount`, others `image-create`, you get the idea.

I propose that we unify the image modifying binaries into one `simage` binary defined in `src/simage.c` and move image-X.c source files into a new `src/img/` directory (perhaps a better location would be in `lib/img/`, therefore giving access to image modification functions to all parts of the program). This directory can then house the code that I have been writing at `src/lib/bootstrap/` containing the bootstrap port to C. The relevant .exec files in `libexec/cli/` will simply change from:

`exec "$SINGULARITY_libexecdir/singularity/image-mount" "$SINGULARITY_libexecdir/singularity/image-bootstrap" "$DEFINITION" "$@"`

to:

`exec "$SINGULARITY_libexecdir/singularity/simage" "mount" "bootstrap" "$DEFINITION" "$@"`
(Or something similar, depending on how we finalize the implementation)

At the start `simage` will simply check argv[1] and then run the appropriate part of the code. However, because we have merged all of the binaries into one unified binary we now have a lot of flexibility in terms of modularity and portability of code. For instance, some of the non-root features require SUID and namespace features going forward. As it stands now, each binary will (likely) at some point need SUID in order for all features to work non-priv, therefore somebody would need to go in and write this code for `image-mount.c`, `image-create.c` etc.. individually. With a unified binary we can make use of the same workflow as sexec.c: write the SUID workflow once and forget about it.

I don't see any particular reasons off the top of my head why this wouldn't work, or why we shouldn't do this, however if you can think of anything I would appreciate it. I am willing to do this since it's basically an idea to help my other ideas easier to implement, but if anybody else wants to tackle this feel free. Please let me know any thoughts.

**Comment by gmkurtzer** [comment]
I like this idea.

I was also thinking about what @vsoch was talking about regarding development workflows in GitHub. I think you should be hosting this in your fork, and we can test and collaborate with you on this in your fork as you are leading this effort within Singularity. Then when it is ready for merging into the main repo, after all the prototyping and testing has occurred, you can submit a single PR.

GitHub has a very different workflow from what I'm used to, but the more I think about it, the more sense it seems to make. Thoughts?

**Comment by vsoch** [comment]
+1! The suggested workflow is to work off of a fork, and then PR to upstream. You can add others' bases easily (and name them whatever you like) in the .git/config. Let me know if you have questions with that - glad to help :0)
