### ISSUE TITLE
remove help for `version` command or refactor text

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2941]
## Version of Singularity:

3.1.0

I don't think we need `singularity help version`. Maybe just say 'No help for version' similar to `git`.

Otherwise to refactor the text.

* `Show application version`

change to: `Show the version for Singularity`

* Get rid of empty description or put something 'useful' in there. Not sure what myself :)

* Lots of white space between end of options and 'additional help message'. Try to clean that up if possible.

**Comment by GodloveD** [comment]
I think both `--help` and `--version` are automatically supplied by cobra.  And what is the point of using cobra if we are going to spend all of our time trying to subvert its normal functions?

**Comment by dtrudg** [comment]
The help message is accurate, so I agree with .@GodloveD here that we don't need to remove this. In 3.5.2 I see the suggested text refactor:

```
Show the version for Singularity
```
