### ISSUE TITLE
internal/pkg/libexec: nuke this package from orbit into oblivion

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2943]
This package has caused me a million headaches (yes, I know I created it in the first place). For instance, take a look at the way we're handling the various URI's that we support in `singularity pull`:

```
	switch transport {
	case LibraryProtocol, "":
		if !force {
			if _, err := os.Stat(name); err == nil {
				sylog.Fatalf("image file already exists - will not overwrite")
			}
		}

		handlePullFlags(cmd)

		libraryImage, err := client.GetImage(PullLibraryURI, authToken, args[i])
		if err != nil {
			sylog.Fatalf("While getting image info: %v", err)
		}

		var imageName string
		if transport == "" {
			imageName = uri.GetName("library://" + args[i])
		} else {
			imageName = uri.GetName(args[i])
		}
		imagePath := cache.LibraryImage(libraryImage.Hash, imageName)
		if exists, err := cache.LibraryImageExists(libraryImage.Hash, imageName); err != nil {
			sylog.Fatalf("unable to check if %v exists: %v", imagePath, err)
		} else if !exists {
			sylog.Infof("Downloading library image")
			if err = client.DownloadImage(imagePath, args[i], PullLibraryURI, true, authToken); err != nil {
				sylog.Fatalf("unable to Download Image: %v", err)
			}

			if cacheFileHash, err := client.ImageHash(imagePath); err != nil {
				sylog.Fatalf("Error getting ImageHash: %v", err)
			} else if cacheFileHash != libraryImage.Hash {
				sylog.Fatalf("Cached File Hash(%s) and Expected Hash(%s) does not match", cacheFileHash, libraryImage.Hash)
			}
		}

		// Perms are 777 *prior* to umask
		dstFile, err := os.OpenFile(name, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0777)
		if err != nil {
			sylog.Fatalf("%v\n", err)
		}
		defer dstFile.Close()

		srcFile, err := os.OpenFile(imagePath, os.O_RDONLY, 0444)
		if err != nil {
			sylog.Fatalf("%v\n", err)
		}
		defer srcFile.Close()

		// Copy SIF from cache
		_, err = io.Copy(dstFile, srcFile)
		if err != nil {
			sylog.Fatalf("%v\n", err)
		}
	case ShubProtocol:
		libexec.PullShubImage(name, args[i], force, noHTTPS)
	case HTTPProtocol, HTTPSProtocol:
		libexec.PullNetImage(name, args[i], force)
	default:
		if !force {
			if _, err := os.Stat(name); err == nil {
				sylog.Fatalf("image file already exists - will not overwrite")
			}
		}

		authConf, err := makeDockerCredentials(cmd)
		if err != nil {
			sylog.Fatalf("While creating Docker credentials: %v", err)
		}

		libexec.PullOciImage(name, args[i], types.Options{
			TmpDir:           tmpDir,
			Force:            force,
			NoHTTPS:          noHTTPS,
			DockerAuthConfig: authConf,
			NoCleanUp:        noCleanUp,
		})
	}
```

As I [pointed out](https://github.com/sylabs/singularity/pull/2940/files/f4a6473f58df0d69bbc3c3039a7a04552ee3e66d#r267087347) in a recent comment on a PR, this code has basically turned into a spaghetti mess full of duplicated and ugly code. Most of the code I've quoted here, as well as code inside of `internal/pkg/libexec` *really* belong in `internal/app/singularity`. Some of this code may belong in helper packages which outsource some functionality, but this is honestly just a mess. I'd like us to fix this mess here 

And for the record, a *lot* of this code was written by me, and I take full responsibility for this making it in.

**Comment by shrshi** [comment]
Hey, I'm unable to pull docker images using singularity 3.0
The pull fails with exit status 1. Here's the debug log that I get - 
> singularity --debug --verbose pull docker://godlovedc/lolcow

WARNING [U=898858,P=25706] sylabsToken()                 Authentication token file not found : Only pulls of public images will succeed
DEBUG [U=898858,P=25706] NewBundle()                   Created temporary directory for bundle /tmp/sbuild-110230597
INFO [U=898858,P=25706] Full()                        Starting build...
DEBUG [U=898858,P=25706] updateCacheSubdir()           Caching directory set to /nethome/.singularity/cache/oci
Getting image source signatures
Skipping fetch of repeat blob sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118
Skipping fetch of repeat blob sha256:3b61febd4aefe982e0cb9c696d415137384d1a01052b50a85aae46439e15e49a
Skipping fetch of repeat blob sha256:9d99b9777eb02b8943c0e72d7a7baec5c782f8fd976825c9d3fb48b3101aacc2
Skipping fetch of repeat blob sha256:d010c8cf75d7eb5d2504d5ffa0d19696e8d745a457dd8d28ec6dd41d3763617e
Skipping fetch of repeat blob sha256:7fac07fb303e0589b9c23e6f49d5dc1ff9d6f3c8c88cabe768b430bdb47f03a9
Skipping fetch of repeat blob sha256:8e860504ff1ee5dc7953672d128ce1e4aa4d8e3716eb39fe710b849c64b20945
Copying config sha256:73d5b1025fbfa138f2cacf45bbf3f61f7de891559fa25b28ab365c7d9c3cbd82

 0 B / 3.33 KiB [------------------------------------------]
 3.33 KiB / 3.33 KiB [==================================] 0s
Writing manifest to image destination
Storing signatures
DEBUG [U=898858,P=25706] Full()                        Inserting Metadata
DEBUG [U=898858,P=25706] Full()                        Calling assembler
INFO [U=898858,P=25706] Assemble()                    Creating SIF file...
FATAL [U=898858,P=25706] PullOciImage()                Unable to pull docker://godlovedc/lolcow: exit status 1

I tried clearing the user cache, but that does not solve the problem. Any help on resolving this will be greatly appreciated!
Thanks

**Comment by bauerm97** [comment]
Hi @shruti1995 , as you mentioned in the email thread where this came up, has this only been happening since the dockerhub maintenance on Saturday? If so, it's possible hat DockerHub tweaked their API and the client library wasn't updated. Or it's potentially the case of DockerHub simply not properly responding to API connections after maintenance

**Comment by GodloveD** [comment]
This seems to have been nuked but the issue was not closed.  🚀 💥
