### ISSUE TITLE
Discuss: Why can you search by user and collection in `singularity search`

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2947]
## Version of Singularity:

3.0.1

I'm not sure that `singularity` can do anything with a user or a collection, so why should it search for them?

Yay, I found Ian Lumb!
<pre>
$ singularity search ilumb
WARNING: Authentication token file not found : Only pulls of public images will succeed
Found 1 users for 'ilumb'
        library://ilumb

No collections found for 'ilumb'

No containers found for 'ilumb'
</pre>

now what?

Maybe if the search showed which containers belonged to a user or container that was found, it would be useful?

**Comment by dtrudg** [comment]
No longer the case after #5677 - we are only reporting on images which are things that can be used in Singularity.
