### ISSUE TITLE
Using singularity on HPC

### ISSUE THREAD

**Issue by soichih** [apptainer/singularity#295]
I am trying to test singularity on our HTC cluster (Indiana University Karst) by running some python script that does some processing on a local input data and write output to the same directory.

I tried following.

```
$ singularity exec docker://python:3.6 test.py
WARNING: Not mounting home directory: bind point does not exist in container: /N
WARNING: Could not chdir to home directory: /N/u/hayashis/Karst
/.exec: line 3: exec: test.py: not found
```

The home directory in our HTC system is something like `/N/u/hayashis/Karst` and obviously there is no `/N` inside the official python container. I think it will be a show stopper if user has to manually edit a public docker container, but for this instance I did following.

1) Used filo/docker2singularity docker container to pull python:3.6 image
2) `sudo singularity shell -w python_3.6-2016-11-01-156ca2b5b15f.img` and created /N directory inside
3) coped the new image to Karst scratch directory (our HTC cluster)

Now, when I run my container, I saw no warnings.
```
$ singularity exec python_3.6-2016-11-01-156ca2b5b15f.img pwd
/N/u/hayashis/Karst
```

So it looks like it was able to mount my home directory inside, but somehow didn't go to my current pwd on host which is `/N/dc2/scratch/hayashis/tmp/python36`. It will never find my test.py there.

-v showed following messages.

```
VERBOSE: Not mounting current directory: overlay is not enabled
VERBOSE: Entering container file system root: /var/singularity/mnt/final
```

I've enabled overlay in the config `enable overlay = yes` but didn't have any effect. How should I go about running test.py which reads a input file from the current working directory and write output file?

**Comment by gmkurtzer** [comment]
With `enable overlay = yes`, can you run it with `--debug` and see if there is any reason why that directory may not be created (or paste the entire output, and I'll check into it).

Thanks!

**Comment by soichih** [comment]
@gmkurtzer Here is the debug output

https://gist.github.com/soichih/051bdec5717ef9e2ba53d5d7fdd02233

**Comment by DrDaveD** [comment]
Hi, Soichi.  This is Dave Dykstra.  I suspect overlayfs isn't working on your system fpr whatever reason (I didn't look carefully at your debug output).  Did you mean HPC or HTC?  Your title says HPC but first comment says HTC.  What operating system is it using?

The good news is that the latest master branch includes a pull request #251 adding the ability to set the home directory inside the container to whatever you want, via a second component to the exec -H option.  You can set it to a path that already exists inside the container where it can bind mount without overlayfs.

**Comment by soichih** [comment]
@DrDaveD Hi Dave! What is "system fpr"? I am having this issue on our HTC cluster (Karst) at Indiana University. It runs on RHEL 6.8 (kernel 2.6.32). Is there a way to diagnose further?

I think it's very important for our users that their current directory as well as all of our scratch / tmp mount points (/N/dc2, /N/dcwan) to be available without the container - without any container manipulations themselves. I believe singularity does all these by default if everything worked properly.

I've seen your commits on #251 I think it's a great feature.  I did run into an issue, though, when I tried something like "-H :/N/home" - hoping that I was able to specify the destination but leave the source home dir to be default (it didn't work). Thank you for adding this capability!

Soichi

**Comment by DrDaveD** [comment]
I meant "system for", not "system fpr".

overlayfs is not supported on RHEL6, that is why 'enable overlay = yes' does nothing for you.  So unless you can get a "/N" directory into your base image, you're going to have to rename the paths inside the container from outside.  If you're wanting only the subdirectories of /N but not all of /N, then those will also have to be inside your base image so you can bind them in with -B options.

**Comment by soichih** [comment]
OK. So I read that overlayfs is still "technology preview" feature for RHEL 7.2. The OS I am testing singularity is running RHEL 6.8. Should I even be using this feature?

I thought that making the current directory automatically available inside the container will significantly improve the usability of singularity, but is this not a common use case? Is there still a way to accomplish something similar with just singularity.conf?

**Comment by DrDaveD** [comment]
It probably is a common use case, but without overlayfs your only option is bind mounts, which require at least the top level directory to be there.  If you have just the top level, you could always bind mount your own scratch directory hierarchy to the top level, then bind mount other directories below that.

**Comment by gmkurtzer** [comment]
Overlay will be enabled by default in the 2.3 release. I am closing this old issue, but if there is a necessity to reopen, comment and let me know.
