### ISSUE TITLE
`--silent` and `--quiet` do not work with `singularity search`

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2951]
## Version of Singularity:

3.0.1

### Expected behavior

Suppressed output when using `--silent` and `--quiet`

### Actual behavior

Same output as not using those options.

`--quiet` does not suppress anything.
<pre>
$ singularity --quiet search 123
WARNING: Authentication token file not found : Only pulls of public images will succeed
Found 1 users for '123'
        library://ross12345

No collections found for '123'

Found 4 containers for '123'
        library://sylabs-adam/default/demo1234
                Tags: 0.1
        library://gmk/default/testing123
                Tags: ubuntu
        library://sylabs-adam/demo/demo1234
                Tags: 0.2
        library://sylabs-adam/default/testing123
                Tags: 1.0
</pre>

`--silent` 'seems' to be partially working. You see it suppresses the warning, and not the fatal. But it still prints normal text. Is that intended? I've included some examples below for context.

<pre>
$ singularity search 12
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Couldn't search library: Bad query '12'. You must search for at least 3 characters
</pre>

<pre>
$ singularity --silent search 12
FATAL:   Couldn't search library: Bad query '12'. You must search for at least 3 characters
</pre>

<pre>
$ singularity search 123
WARNING: Authentication token file not found : Only pulls of public images will succeed
Found 1 users for '123'
        library://ross12345

No collections found for '123'

Found 4 containers for '123'
        library://sylabs-adam/default/demo1234
                Tags: 0.1
        library://gmk/default/testing123
                Tags: ubuntu
        library://sylabs-adam/demo/demo1234
                Tags: 0.2
        library://sylabs-adam/default/testing123
                Tags: 1.0
</pre>

<pre>
[justin@ip-172-31-94-96 search]$ singularity --silent search 123
Found 1 users for '123'
        library://ross12345

No collections found for '123'

Found 4 containers for '123'
        library://sylabs-adam/default/demo1234
                Tags: 0.1
        library://gmk/default/testing123
                Tags: ubuntu
        library://sylabs-adam/demo/demo1234
                Tags: 0.2
        library://sylabs-adam/default/testing123
                Tags: 1.0
</pre>

**Comment by dtrudg** [comment]
As with `cache list` search explicitly asks for output. It doesn't make sense to do a search with no output. `--silent` and `--quiet` are IMHO to suppress log messages, progress bars and information that is not explicitly asked for.
