### ISSUE TITLE
uninformative error when trying to start instance on SLES 11

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2959]
## Version of Singularity:

3.1.0 release

### Expected behavior

It's impossible to create an `instance` on SLES 11 because there is no `pid` namespace.  I would expect to see an error to that effect.

### Actual behavior

```
dave@SLES:~> singularity instance start ubuntu.sif test
ERROR:   container cleanup failed: no instance found with name test
FATAL:   container creation failed: Network requires root permissions or --network=none argument as user

FATAL:   failed to start instance: exit status 1
```

**Comment by ArangoGutierrez** [comment]
this could maybe be handled via go build tags?
