### ISSUE TITLE
net option not working in SLES 11 or on RHEL 6.10 (is it expected to?)

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2971]
## Version of Singularity:

3.1.0 release tarball

### Expected behavior

```
$ sudo singularity shell --net ubuntu.sif
```

### Actual behavior

On RHEL

```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)
$ sudo singularity shell --net ubuntu.sif
FATAL:   container creation failed: failed to make veth pair: operation not supported
```

On SLES

```
$ cat /etc/os-release
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"
$ sudo singularity shell --net ubuntu.sif
FATAL:   container creation failed: failed to setup hairpin mode for veth246bd01b: invalid argument
```

Don't know if this is expected to work or not.  Both distos appear to support network namespaces afaik.

**Comment by cclerget** [comment]
@GodloveD On RHEL for sure only macvlan configuration works, ptp/bridge/ipvlan are simply not included in kernel and report error : `operation not supported`.

For SLES, could you test by adding `"hairpinMode": false` after `ipMasq` line in `/etc/singularity/network/00_bridge.conflist`. Or by using another network config like `--net --network=ptp`

**Comment by GodloveD** [comment]
Those options work!  Thanks @cclerget !
