### ISSUE TITLE
Improve 'apps' Help Output

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#2975]
## Version of Singularity:

`3.1.0`

### Expected behavior

`singularity help apps` and `singularity apps -h` should have useful `Description` and `Examples` sections.

```sh
$ singularity help apps
apps <image path>

Usage:
  S

Description:
  List the Standard Container Integration Format (SCI-F) apps in the supplied container.

Options:
  -h, --help   help for apps


Examples:
  $ singularity apps image.sif


For additional help or support, please visit https://www.sylabs.io/docs/
```

### Actual behavior

The `Usage`, `Description`, and `Examples` sections regurgitate the same content:

```sh
$ singularity help apps
apps <image path>

Usage:
  singularity apps <image path>

Description:apps <image path>

Options:
  -h, --help   help for apps


Examples:apps <image path>


For additional help or support, please visit https://www.sylabs.io/docs/
```

### Steps to reproduce behavior

`singularity help apps` or `singularity apps -h`.

**Comment by dtrudg** [comment]
`singularity apps` is no longer since https://github.com/sylabs/singularity/pull/3390
