### ISSUE TITLE
`singularity` does not conform to the linux command best practice of ordering src dest

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2981]
## Version of Singularity:

3.1.0

A lot of our commands are ordered by <destination file> <source file or URI>. Most linux commands use the reverse, <source> <destination> ordering.

Example of source destination ordering

`cp <source> <destination>`

Example of destination source ordering

`singularity pull alpine.sif docker://alpine:latest`

Do we want to keep doing this or do we want to adopt a more linux-like best practice.

**Comment by GodloveD** [comment]
It's kindof late in the game to go changing the order of our commands just to confirm to an unwritten standard imho.  A CLI change like this would break everyone's scripts and cause all kinds of upheaval.  Further there would be no way to support both methods temporarily while we slowly phase out and deprecate the older syntax.  For better or for worse I think this is the syntax we are stuck with.

**Comment by mem** [comment]
I agree the convention implemented by singularity is awful, particularly with the commands where the optional argument is in the middle (`singularity command [[arg2] arg1]` or `singularity command [arg2] arg1`).

But it's what it is, this has already been established as the user-facing API. There's no reasonable way to change this without breaking a bunch of people's code (either scripts or learned behaviors).

The only thing we can do now is be consistent (or as consistent as we can be within this convention). Please file bug reports if you find inconsistencies.
