### ISSUE TITLE
Discuss: Download vs. Fetch for pull

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2982]
## Version of Singularity:

3.1.0

When you're describing what `pull` does, it is best not to use the word `pull`. What would be the best option here? Git uses fetch, we use download in a few places.

We should be consistent. When describing what `pull` does, use one term. Outside of that, use the term `pull`.

**Comment by dtrudg** [comment]
I think we are doing this. We lead with the 'download or build' and then use 'pull'

```
  The 'pull' command allows you to download or build a container from a given
  URI. Supported URIs include:
```
