### ISSUE TITLE
refactor `singularity help pull` text

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2984]
## Version of Singularity:

3.1.0

Related:
* https://github.com/sylabs/singularity/issues/2983
* https://github.com/sylabs/singularity/issues/2933
* https://github.com/sylabs/singularity/issues/2931
* https://github.com/sylabs/singularity/issues/2929

* `Pull a container from a URI`

change to: `Download an image from a URI`

*
<pre>
Description:
  The 'pull' command allows you to download or build a container from a given
  URI.  Supported URIs include:
</pre>

change to:
<pre>
Description:
  Download (and and sometimes build) an image from a URI.

  Supported URIs:
</pre>

* `library: Pull an image from the currently configured library`

change to: `library: Download an image from a library`

* The syntax shown for `library://` is very difficult to follow, please redo it in another fashion. Perhaps just removing the brackets would be enough.

* `docker: Pull an image from Docker Hub`

change to:`docker: Download and build an image from a Docker Registry`

* The syntax for the docker transport is not 'exactly' correct, because the user is optional for official images (ie, docker://alpine:latest).

* `shub: Pull an image from Singularity Hub to CWD`

change to: `shub: Pull an image from Singularity Hub`

* Each URI should have a link to a page describing what they are. A wiki page? Docs? Anything.

* The examples are pretty good, but I'd like to see them expanded upon to include users, collections, local docker registries, other registries besides Docker Hub, and any other way things could be pulled for all transport URIs. 

* In the examples, I think it would be good if all the containers we're pulling are the same, so the user isn't overwhelmed with comparing containers of different things.

* `From Sylabs cloud library`

change to: `Sylabs Cloud Library`

* `From Docker`

change to: `From Docker Hub`

* `From Shub`

change to: `From Singularity Hub`

**Comment by dtrudg** [comment]
We now have a better description:

```
 Description:
  The 'pull' command allows you to download or build a container from a given
  URI. Supported URIs include:
```

I'm generally against adding much more content to the CLI help message, as I feel it should be a quick reference. Things like the library spec being `library://user/collection/container[:tag]` are consistent with how command line parameters use brackets in help text. We have a link to our docs on the web, where long-form and more examples can be places.

Other opinions very welcome!
