### ISSUE TITLE
refactor `singularity help search` options text

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2987]
## Version of Singularity:

3.1.0

<pre>
      --library string   the library to pull from (default
                         "https://library.sylabs.io")
</pre>

change to: `Download images from the provided library (default is "https://library.sylabs.io")`

Try to keep all on one line

**Comment by dtrudg** [comment]
Now has....

```
Options:
  -h, --help             help for search
      --library string   URI for library to search (default
                         "https://library.sylabs.io")
```
