### ISSUE TITLE
error while loading shared libraries: libsingularity.so.1: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by poquirion** [apptainer/singularity#299]
Hello

I was running singularity 2.1 and all was good. I've updated it to 2.2 is without trying to wipe the old version and got this error while trying to used an image that was previously ok

```
my_machine:~$ singularity shell old-things.img 
/usr/local/lib/singularity/sexec: error while loading shared libraries: libsingularity.so.1: cannot open shared object file: No such file or directory
```

**Comment by poquirion** [comment]
I am doing that on opensuse "13.1 (Bottle)". 

```
opensuse:~/Downloads/singularity> ls /usr/local/lib/
singularity
opensuse:~/Downloads/singularity> ls /usr/local/lib/singularity/
bootstrap     cli      docker-import.sh  get-section  image-bind    image-expand      image-mount  python  sexec-suid
bootstrap.sh  copy.sh  functions         helpers      image-create  image-handler.sh  mods         sexec
```

While there seems to be no problems on my ubuntu machine:

```
ubuntu:~/Downloads/singularity$ ls /usr/local/lib/
libsingularity.a  libsingularity.la  libsingularity.so  libsingularity.so.1 
```

**Comment by poquirion** [comment]
Oh:

all is in /usr/local/lib64/ and it seems that I have to add the link before I use singularity...

```
export LD_LIBRARY_PATH=/usr/local/lib64
opensuse:~$ singularity shell old-things.img 
Singularity: Invoking an interactive shell within container...

$
```

**Comment by poquirion** [comment]
It seems that `/usr/local/lib64/` was not in `/etc/ld.so.conf`, I've added it and ran `sudo ldconfig` now singularity works like a charm without having to export  `LD_LIBRARY_PATH`

**Comment by gmkurtzer** [comment]
Haha, you beat me! Fantastic!

**Comment by bbockelm** [comment]
Hi,

This resolution makes no sense.  `sexec` utilizes `RPATH` and hence should not need to be in `ld.so.conf`.

Did you change `--prefix` between compilation time and install time?

Brian

**Comment by gmkurtzer** [comment]
@bbockelm Good catch. I am not specifying rpath specifically in the LDFLAGS and I am counting on autotools to do it, but in my experience it seems to be correctly working. Is it possible autotools is inconsistent?

@poquirion, ping! Can you do a quick compile test as follows:

```bash
make maintainer-clean
./autogen.sh
./configure --prefix=/tmp/test1234
make
make install
```

and confirm that the ldd output looks like:

```bash
ldd /tmp/test1234/libexec/singularity/sexec
        linux-vdso.so.1 =>  (0x00007ffec41d5000)
        libsingularity.so.1 => /tmp/test1234/lib/libsingularity.so.1 (0x00007f339be92000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f339bac5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f339c2b6000)
```

(notice the link to libsingularity.so.1)

**Comment by poquirion** [comment]
Here is what I get:
```
ldd /tmp/test1234/lib/singularity/sexec
	linux-vdso.so.1 (0x00007ffe29783000)
	libsingularity.so.1 => /tmp/test1234/lib64/singularity/libsingularity.so.1 (0x00007f506ea33000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f506e683000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f506ec53000)
```
note that sexec is in  `lib/`, not in `libexec/` 

That is from the tip of master 'e575e00c7311b34f0bc463961fa52b004e31a307' today, not the 2.2 release.

**Comment by gmkurtzer** [comment]
Weird that sexec is in lib/... What build host operating system is this?

That output looks good to me and it doesn't look like you are able to replicate the original bug with master. Is it still an issue with the GA 2.2 release?

**Comment by poquirion** [comment]
The problem was for opensuse "13.1 (Bottle)".  I can retest it for 2.2, but it will have to wait a bit, we are renovating the server room and all or opensuse server are down until Monday.

**Comment by gmkurtzer** [comment]
Okay, thanks @poquirion!

**Comment by poquirion** [comment]
I installed the 2.x branch tip on my opensuse server and the ldd linkage looks good. I also did the test for the actual 2.2 release and its all good too:
```
ldd /tmp/test1234/lib/singularity/sexec
	linux-vdso.so.1 (0x00007fff9dfe4000)
	libsingularity.so.1 => /tmp/test1234/lib64/libsingularity.so.1 (0x00007f26f2844000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f26f2494000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f26f2a64000)
```
