### ISSUE TITLE
`singularity pull` with no transport defaults to library

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2991]
## Version of Singularity:

3.1.0

### Expected behavior

$ singularity pull alpine:latest
<error, no transport provided.>

### Actual behavior

$ singularity pull alpine:latest
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Downloading library image
 2.59 MiB / 2.59 MiB [=============================================================================================] 100.00% 59.65 MiB/s 0s

This should probably be documented at the very least if it is intended.

**Comment by ikaneshiro** [comment]
@jscook2345 I remember talking to @tri-adam awhile ago about URIs and I'm pretty sure defaulting to library is correct behavior. @tri-adam if not please reopen issue.
