### ISSUE TITLE
improve error message when pulling with a bad shub uri

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2992]
## Version of Singularity:

3.0.1

<pre>
$ singularity pull shub://busybox:latest
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Invalid shub URI
</pre>

This should say 'why' the URI is invalid. This works with library and docker, so you might expect it to work here.

**Comment by dtrudg** [comment]
Given we have an example in the help text, and we now say...

```
09:46 AM $ singularity pull shub://busybox:latest
FATAL:   While pulling shub image: failed to parse shub uri: not a valid Shub reference
```

...I think we are okay. I don't think we should be adding complex code to explain exactly what is / what is not valid about a shub reference in the error message.
