### ISSUE TITLE
be verbose when pulling an image

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2998]
## Version of Singularity:

3.0.1

<pre>
$ singularity pull library://busybox:latest
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Downloading library image
 656.93 KiB / 656.93 KiB [=========================================================================================] 100.00% 62.57 MiB/s 0s
</pre>

I would expect that this would say something like `Saved image to: <filename>` after the download progression. Minimally, I think at least say what the image name is when you say `Downloading library image`.

**Comment by dtrudg** [comment]
This does happen in 3.5.0-rc.2

```
dave@piran~> singularity pull library://busybox:latest
INFO:    Downloading library image
 656.93 KiB / 656.93 KiB [====================================================================] 100.00% 2.57 MiB/s 0s
WARNING: Container might not be trusted; run 'singularity verify busybox_latest.sif' to show who signed it
INFO:    Download complete: busybox_latest.sif
```
