### ISSUE TITLE
Add environment variable to clear cache after every command

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2999]
## Version of Singularity:

3.1.0

For testing purposes at least, it would be useful to have something that clears the cache after every singularity command so I don't have to do so myself. Perhaps a shell function or alias would do here as well.

Still something I think that would require some effort.

**Comment by dtrudg** [comment]
Personal opinion is that shell function or alias in any test environment needing this is the right approach. This type of option in Singularity would open up further race conditions with the cache.
