### ISSUE TITLE
Script files expect bash, but run /bin/sh

### ISSUE THREAD

**Issue by weidendo** [apptainer/singularity#3]
On Ubuntu, /bin/sh actually is "dash", resulting in strange failures.

Further, in your containers, you only copy "/bin/sh".
Better install /bin/bash (in mods/install_files), and create a link "sh -> bash"?

PS: Nice project.

**Comment by gmkurtzer** [comment]
Oh, very interesting... I was attempting to write all portable Bourne code which should be Dash compatible (unless I made mistakes between Bourne and Bash). What were some of the errors you were getting?

Regarding, /bin/sh inside the container that is an interesting point as well, but again shouldn't dash work properly?

Just for kicks, I'd love to see the failures you are getting from /bin/sh to see if I should fix them or move to bash as you suggested.

Thanks!

**Comment by weidendo** [comment]
Ah, cool. I had the impresseion that you expect bash.

Really not much.
In libexec/run.exec, I had to change
  trap true SIGINT SIGKILL
into
  trap true INT KILL

Otherwise I get:

  trap: SIGINT: bad trap

on execution.
If I find other stuff, I will put i here.

**Comment by gmkurtzer** [comment]
Excellent, thank you! I just fixed the traps, and thanks for catching that! Truly Bourne docs are getting harder to find as reference. LOL

I will close this issue for now, but please do let me know if you find something else (either reopen this ticket, or make a new one please).

Thank you again!

**Comment by weidendo** [comment]
Missed a few errors here (my TERM is "xterm-256color").
Now idea how to reopen; I do not see any button for that.

> singularity 
> /usr/local/bin/singularity: 98: shift: can't shift that many
> 
> singularity build find.spec 
> -ne \e[0;39mBuilding: find
> \e[0;39m
> -ne \e[0;39mChecking paths...
> \e[0;39m
> ...
> -ne \e[0;39mBuilding singularity main runscript
> \e[0;39m
> -ne \e[0;39mRunning %test...
> \e[0;39m
> /singularity: 5: [: test: unexpected operator
> /singularity: 12: [: test: unexpected operator
> /singularity: 19: [: test: unexpected operator
> ERROR: Unknown singularity exec command
> -ne \e[0;31mERROR: Module build_test threw an error
> \e[0;39m

**Comment by remyd1** [comment]
I had the same error on Ubuntu. It is a color/encoding problem from term.
Not a big deal...

2015-11-27 11:36 GMT+01:00 weidendo notifications@github.com:

**Comment by weidendo** [comment]
No, it's not about the term. According to
  http://unix.stackexchange.com/questions/88307/escape-sequences-with-echo-e-in-different-shells
the used "echo -e" is not POSIX, and the dash "echo" builtin does not support it.

Instead, it suggests to use "printf '\033 ...."

**Comment by gmkurtzer** [comment]
(Trying to respond via email interface, if this works... Cool!)

Can you confirm that printf works by changing it in message() via the functions file in the libexecdir?

Actually I suppose we could also run /bin/echo directly as well to avoid using the dash built in for testing too. 

Thanks!

**Comment by weidendo** [comment]
Just substituting "echo -ne" with "printf" does not work, as printf handles formatting chars special, e.g. instead of getting "Evaluating: %exec" I get "Evaluating: 0.000000e+00xec"...

But using "/bin/echo" instead of "echo" works fine here.

**Comment by weidendo** [comment]
I just looked at
  /singularity: 5: [: test: unexpected operator

The dash-builtin "test" does not like the operator "==", but "=" is fine.

**Comment by weidendo** [comment]
With changing "==" to "=" in libexec/mods/install_runscripts, I can finally build my "find.sapp", and it works!

**Comment by gmkurtzer** [comment]
Fixed, please let me know if that helped! Thanks!

**Comment by weidendo** [comment]
Looks good!
