### ISSUE TITLE
Singularity assumes existance of coreutils in /bin

### ISSUE THREAD

**Issue by jbedo** [apptainer/singularity#300]
Singularity assumes that coreutils exists at /bin. Here's an example:

    $ singularity create -s 100 -F myimg.img 
    /nix/store/7md6r7n4c89ql6vxjrg7n300sjcadi5n-singularity-2.2/libexec/singularity/cli/create.exec: line 95: /bin/rm: No such file or directory
    Creating a new image with a maximum size of 100MiB...
    ERROR  : Will not overwrite existing file: myimg.img
    ABORT  : Retval = 255
    ERROR: Failed creating image: myimg.img

rm is available in my path, it just doesn't exist in /bin. It would be better if singularity did not assume rm existed at /bin/rm, and even better if it unlinked files using unlink(2) instead of executing another process.

**Comment by gmkurtzer** [comment]
Hi @jbedo,

There is an effort right now converting the shell code to C for creating and bootstrapping images at which point you are completely right, we will use the system call unlink().

I'm just curious,... what distribution does not install coreutils to /bin or does not have a link from /bin to where it was installed (e.g. Fedora and RHEL7 derivatives have a link to /usr/bin)? As far as I recall from the FHS and maybe even POSIX, `rm` should always be available at `/bin/rm` just as `sh` must always be at `/bin/sh` (another assumption that Singularity requires for containers and exec*() system calls to work).

Thanks!

**Comment by jbedo** [comment]
Wonderful! I'm using [NixOS](http://nixos.org) which does break the FHS in it's design as each package is installed into a separate path in the Nix store. I have just packed up singularity for NixOS and am experimenting with it and running imported docker images produced by Nix expressions, which are wonderfully small. I did discover the requirement for /bin/sh in Singularity containers, which by default doesn't exist in a NixOS docker container, but I think it's reasonable to expect this to exist. I haven't found any other issues regarding Singularity on NixOS, it's all worked very smoothly.

**Comment by bauerm97** [comment]
@jbedo @gmkurtzer So the rewrite of the bootstrapping code into C is underway, however it will still require a bit more time for finished the initial implementation and then debugging and polishing it. In the mean time however, would we solve your specific issue if we simply changed `/bin/rm -f "$SINGULARITY_IMAGE"` into `rm -f "$SINGULARITY_IMAGE"` for the time being? The long term solution will, as Greg said, be handled in the C code, but this might be a nice temporary fix to the bug.

**Comment by jbedo** [comment]
Yes, this would fix the bug.

**Comment by gmkurtzer** [comment]
At this point, is this issue resolved thanks to the above mentioned PR?

**Comment by jbedo** [comment]
Yes, retested with current master and the issue is now resolved. Thanks!
