### ISSUE TITLE
`file` identifies a sif file as something else

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3004]
## Version of Singularity:

3.1.0

`$ file docker-goimages_latest.sif`
`docker-goimages_latest.sif: a /usr/bin/env run-singularity script text executable`

I guess I expected something else, like SIF? Can we add some magic to get that?

**Comment by jmstover** [comment]
```
$ file hello.sif
hello.sif: Singularity SIF image
```
On my Slackware box ... 
```
$ cat /etc/file/magic/sif
32      string  SIF_MAGIC Singularity SIF image
```

And recompiling the magic files....  `file --compile` 

*Edit:*
Technically, the original output is correct if you make the image executable and run it.
