### ISSUE TITLE
refactor `singularity help cache list` text

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3008]
## Version of Singularity:

3.0.1

* `List your local Singularity cache`

change to: `Show items in the local Singularity image cache`

* Description

changed to: `Show the blob, library, and / or oci items in the cache`

These are described in the parent help, though showing what options are available here is still valuable.

* `list all cache types`

changed to: Show all items in the cache

*
<pre>
  -T, --type strings   list cache type, choose between: library, oci, and
                       blob (default [library,oci,blobSum])
</pre>

`Show specific items in the cache (Defaults to: blob,library,oci)`

* what is blobSum in the `--type` description?

**Comment by dtrudg** [comment]
Not quite the same as suggested, but it has been clarified:

```
09:58 AM $ singularity help cache list
List your local Singularity cache

Usage:
  singularity cache list [list options...]

Description:
  This will list your local cache (stored at $HOME/.singularity/cache if
  SINGULARITY_CACHEDIR is not set).

Options:
  -h, --help           help for list
  -T, --type strings   a list of cache types to display, possible entries:
                       library, oci, shub, blob(s), all (default [all])
  -v, --verbose        include cache entries in the output


Examples:
  All group commands have their own help output:

  $ singularity help cache list
  $ singularity help cache list --type=library,oci
  $ singularity cache list --help


For additional help or support, please visit https://www.sylabs.io/docs/
```
