### ISSUE TITLE
when a cache is empty, cache list should say so

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3010]
## Version of Singularity:

3.1.0

<pre>
$ singularity cache list --type oci
NAME                   DATE CREATED           SIZE             TYPE
</pre>

I think we could say `oci cache is empty` or something similar.

**Comment by sashayakovtseva** [comment]
Hmmm, this will require lots of changes. Also it is a common practice to display empty list like we do, so I think we should not change this behavior. 

Reopen this issue if you disagree.
