### ISSUE TITLE
remove headers when using blobSum type option with singularity cache list

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3013]
## Version of Singularity:

3.0.1

<pre>
$ singularity cache list --type blobSum
NAME                   DATE CREATED           SIZE             TYPE

There are 3 oci blob file(s) using 2.76 Mb of space. Use: '-T=blob' to list
</pre>

I think the headers can be removed here for a cleaner look.

**Comment by sashayakovtseva** [comment]
Same as in #3010

**Comment by jscook2345** [comment]
Closing as a duplicate. Thanks @sashayakovtseva !
