### ISSUE TITLE
filesize mismatches in several areas

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3014]
## Version of Singularity:

3.0.1

<pre>
$ singularity pull library://busybox:latest
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Downloading library image
 656.93 KiB / 656.93 KiB [=========================================================================================] 100.00% 46.67 MiB/s 0s
$ singularity cache list --type library
NAME                   DATE CREATED           SIZE             TYPE
busybox_latest.sif     2019-03-21 02:00:54    672.70 Kb        library
$ du -h busybox_latest.sif
660K    busybox_latest.sif
$ du -ks busybox_latest.sif
660     busybox_latest.sif
$ du -h ~/.singularity/cache/library/sha256.b80bddda1d84d827ea135eb890f969a83ccba2a7a2152e15567d114857280120/busybox_latest.sif
660K    /home/justin/.singularity/cache/library/sha256.b80bddda1d84d827ea135eb890f969a83ccba2a7a2152e15567d114857280120/busybox_latest.sif
$ du -ks ~/.singularity/cache/library/sha256.b80bddda1d84d827ea135eb890f969a83ccba2a7a2152e15567d114857280120/busybox_latest.sif
660     /home/justin/.singularity/cache/library/sha256.b80bddda1d84d827ea135eb890f969a83ccba2a7a2152e15567d114857280120/busybox_latest.sif
</pre>

`pull`, `cache`, and `df` all say something different. I would expect these would be more or less the same. Reasons why they are different?

**Comment by dtrudg** [comment]
Cache list is buggy here... it is using `1000` instead of `1024` for unit calculations.

The download size may differ slightly, but the cache list value should match du
