### ISSUE TITLE
singularity --silent and --quiet have no effect on cache list

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3015]
## Version of Singularity:

3.1.0

singularity --silent cache list --all
singularity --quiet cache list --all

They print out all the cache info instead of suppressing text output.

**Comment by dtrudg** [comment]
Going to close this. IMHO list is explicitly asking for output... silent and quiet are for suppressing log levels and progress bars so there isn't a bug here. This has sat for a while and nobody has raised it as an issue.
