### ISSUE TITLE
Missing linked library

### ISSUE THREAD

**Issue by andremrsantos** [apptainer/singularity#3027]
## Version of Singularity:

3.1.0-406.gbfbee6c

### Expected behavior

I expect to run the image

```
singularity pull docker://alpine
./alpine_latest.sif
```

### Actual behavior

But when I run, I got the following error:

```
Singularity runtime parent: error while loading shared libraries: libseccomp.so.2: cannot open shared object file: No such file or directory
```

### Steps to reproduce behavior

I have installed the required libraries on a non-default path. When I check the linked libraries to the binary, it finds the libseccomp.so.2. Not sure the source of the error.

```
ldd $(which singularity)
        linux-vdso.so.1 =>  (0x00007ffd836dd000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f50b102f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f50b0e12000)
        libseccomp.so.2 => /conda/lib/libseccomp.so.2 (0x00007f50b0dce000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f50b0a3a000)
        /lib64/ld-linux-x86-64.so.2 (0x0000563897187000)
```

Does anyone know how to solve this issue?

**Comment by cclerget** [comment]
Hi @andremrsantos , Singularity CLI execute a setuid binary, so `LD_LIBRARY_PATH` is ignored by loader for security reasons, that explain why it can't find `libseccomp.so.2` outside of loader cached paths while executing the setuid binary. You can solve that by compiling Singularity like this (not sure about include path but you get the idea ;-) ) :

```
CGO_CFLAGS="-I/conda/include" CGO_LDFLAGS="-L/conda/lib" CFLAGS="-I/conda/include" LDFLAGS="-L/conda/lib" ./mconfig
make -C builddir
sudo make -C builddir install
```

**Comment by andremrsantos** [comment]
Hi @cclerget ,
I tried to use the flags you suggested, but I still got the same issue. Thanks for the help anyway.

**Comment by cclerget** [comment]
@andremrsantos Ok looks like it requires to additionally pass `pkg-config` path during make step, if anaconda has (or provide) pkg-config, you may try with `make PKG_CONFIG_PATH=/conda/path/to/pkg-config -C builddir`
