### ISSUE TITLE
Exporting env vars

### ISSUE THREAD

**Issue by poquirion** [apptainer/singularity#303]
I typically create singularity images from docker images. There, I can set up env vars that are pretty useful to my softwares, but when I export them to singularity, all is lost.

 Would it be possible to implement env var export?

**Comment by chrisgorgo** [comment]
If you are using [docker2singularity ](https://github.com/singularityware/docker2singularity)the env var should be preserved. This is how it's done under the hood: https://github.com/singularityware/docker2singularity/blob/master/docker2singularity.sh#L130

**Comment by poquirion** [comment]
Thanks!
