### ISSUE TITLE
Do we need the --verbose option?

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3034]
## Version of Singularity:

3.0.1

I know our logger has it, so we have it, but are there any / many uses of verbose? I have yet to find any from just testing it out. Just looking through the source I see a handful. Perhaps they should be debug messages or something else?

**Comment by dtrudg** [comment]
Use of Verbose has now picked up, particularly in the core engine code around bind setup. It fits the 'middle ground' where a message is not pure "Debug", i.e. it may be useful to a user without giving them the Debug firehose, but rarely - so we don't always want to show it. It has also been picked up in the encryption stuff, to be verbose about the key / passphrase sources being used.
