### ISSUE TITLE
Could we replace the options with arguments in singularity capability list

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3036]
## Version of Singularity:

3.0.1

`singularity capability list --all` to `singularity capability list all (or singularity capability list)`

`singularity capability list --user nobody` to `singularity capability list nobody`

`--user` or `--group` would not really be needed, you could just print user or group perms if either matched (like user=nobody, group=nobody)

What do you think?

**Comment by cclerget** [comment]
@jscook2345 you mean, if `--user` or `--group` are not set, to list both user and group ? And let those options to ease output filter ?
