### ISSUE TITLE
refactor singularity help inspect text

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3048]
## Version of Singularity:

3.1.0

* `Display metadata for container if available`

change to: `Show metadata for an image`

*
<pre>
  Inspect will show you labels, environment variables, and scripts associated
  with the image determined by the flags you pass.
</pre>

change to:

<pre>
  Show metadata related to an image. You can filter which metadata to see based on the options used.
</pre>

* `inspect a specific app`

Need to somehow tie this into 'apps' as a thing. Otherwise 'app' has a lot of meanings

* `show the Singularity recipe file that was used to generate the image`

change to: `Show the definition file that was used to generate the image`

* `show the environment settings for the image`

change to: `Show the environment script from the image`

* `inspect the runscript helpfile, if it exists`

change to: `Show the help script from the image`

* `print structured json instead of sections`

change to: `Show command output as JSON`

* `show the labels associated with the image (default)`

change to: `Show the labels from the image`

* `show the runscript for the image`

change to: `Show the run script for the image`

* I would add a line of text for each metadata piece to the description. IE, what is a help script and how do I create it?

* Perhaps link to the docs on definition files?

I would add an example with a simple definition file that has some labels and than inspecting some labels as the example.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
