### ISSUE TITLE
Add option to suppress %test after bootstrap

### ISSUE THREAD

**Issue by bwlewis** [apptainer/singularity#305]
Some containers might desire invocation via mpi, or some kind of standard input, or similar external requirement for proper operation. I'd like to write unit tests in %test that reflect that. This is possible using the `singularity test container` approach but not always possible during the bootstrap process.

I suggest adding a flag/option that disables the %test script after bootstrap for these situations.

**Comment by gmkurtzer** [comment]
How about having a different section name for %buildtest Vs. %runtest? And if %test is present, we just assume it means both?

Thoughts?

**Comment by vsoch** [comment]
could you give example use cases for the three (%test, %buildtest, %runtest), and what happens when you  don't specify anything? I'm :confused:

**Comment by bwlewis** [comment]
@vsoch my request came from a desire to test encapsulated mpi applications normally invoked by, for instance, `mpirun ... singularity test image`, whereas `singularity bootstrap ...` is not normally invoked with mpirun (and the test section is invoked after the bootstrap process). Instead, the documentation examples illustrate invoking mpirun internally in the test section code, which might not match arbitrary test cluster conditions.

I'm starting to change my mind on this however to simply close this issue because the current setup is nice and simple. In those circumstances where it is desirable to include an extra externally invoked mpi test, or some other run-time test condition, it's easy enough to manually switch in the test section with a shell script + environment variable for example.

I will make a simple example along these lines.

**Comment by vsoch** [comment]
that sounds great! If you make an example, please send along so we can add to the online docs. Thanks for the update!
