### ISSUE TITLE
improve error message when singularity inspect tries to inspect a bad file

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3050]
## Version of Singularity:

3.1.0

* Inspect a text file
<pre>
[justin@ip-172-31-94-96 inspect]$ singularity inspect ~/2019-03-19/singularity/help/singularity.txt
FATAL:   exit status 255
</pre>

* Inspect a directory
<pre>
[justin@ip-172-31-94-96 inspect]$ singularity inspect ~/2019-03-19/singularity/help
FATAL:   exit status 255
</pre>

Should have some sort of message here

**Comment by WestleyK** [comment]
Closing. This is fixed in master.
