### ISSUE TITLE
singularity inspect --environment has odd looking output

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3054]
## Version of Singularity:

3.1.0

<pre>
[justin@ip-172-31-94-96 inspect]$ singularity inspect -e alpine_latest.sif

==-z
==
#!/bin/sh
#Custom environment shell code should follow
</pre>

What's up with the two lines with `==` on them?

**Comment by phpHavok** [comment]
Ah, this is because alpine's  `basename` command doesn't support the `-z` option that I'm using to generate headers for multiple environments. Investigating a better solution.

**Comment by phpHavok** [comment]
The PR makes alpine's output consistent with other containers:
```
[jacob@gideon temp]$ singularity inspect -e alpine_latest.sif
==environment==
==environment:90-environment.sh==
#!/bin/sh
#Custom environment shell code should follow

```
