### ISSUE TITLE
should the docker and library run-scripts vary so much?

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3055]
## Version of Singularity:

3.1.0

These two (Library vs Docker) vary greatly. I know Docker has to have a default, but wouldn't Library have one to if `%runscript` isn't set?

* Library pull of busybox:latest
<pre>
[justin@ip-172-31-94-96 inspect]$ singularity inspect --runscript busybox_latest.sif

#!/bin/sh

</pre>

* Docker pull of alpine:latest
<pre>
[justin@ip-172-31-94-96 inspect]$ singularity inspect --runscript alpine_latest.sif

#!/bin/sh
OCI_ENTRYPOINT=''
OCI_CMD='"/bin/sh"'
CMDLINE_ARGS=""
# prepare command line arguments for evaluation
for arg in "$@"; do
    CMDLINE_ARGS="${CMDLINE_ARGS} \"$arg\""
done

# ENTRYPOINT only - run entrypoint plus args
if [ -z "$OCI_CMD" ] && [ -n "$OCI_ENTRYPOINT" ]; then
    if [ $# -gt 0 ]; then
        SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} ${CMDLINE_ARGS}"
    else
        SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT}"
    fi
fi

# CMD only - run CMD or override with args
if [ -n "$OCI_CMD" ] && [ -z "$OCI_ENTRYPOINT" ]; then
    if [ $# -gt 0 ]; then
        SINGULARITY_OCI_RUN="${CMDLINE_ARGS}"
    else
        SINGULARITY_OCI_RUN="${OCI_CMD}"
    fi
fi

# ENTRYPOINT and CMD - run ENTRYPOINT with CMD as default args
# override with user provided args
if [ $# -gt 0 ]; then
    SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} ${CMDLINE_ARGS}"
else
    SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} ${OCI_CMD}"
fi

# Evaluate shell expressions first and set arguments accordingly,
# then execute final command as first container process
eval "set ${SINGULARITY_OCI_RUN}"
exec "$@"
</pre>

**Comment by dtrudg** [comment]
In essence, the dockerfile _does_ have a specific runscript as it is setting `CMD ["/bin/sh"]` and then we get down to our runscript driver giving us this...

```
eval "set /bin/sh"
exec "$@"
```

If you created a docker container without any `CMD` or `ENTRYPOINT` then you'd end up with the same effective thing as the empty runscript in the library case.

Really the alpine image in the library should be built with a runscript that results in the equivalent.
