### ISSUE TITLE
Setting an existing tag on the image that already holds it (no-op) gives a warning

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3063]
## Version of Singularity:

3.1.0

<pre>
[justin@ip-172-31-94-96 push]$ singularity push alpine_latest.sif library://jscook2345/alpine/alpine
INFO:    Image is already present in the library - not uploading.
INFO:    Setting tag latest
WARNING: latest replaces an existing tag
</pre>

Not sure why `Image is already present in the library - not uploading.` isn't a regular message and is instead info text.

Why is it setting the latest tag if its not uploading? 

Looking at the debug output confuses me a bit more.

<pre>
[justin@ip-172-31-94-96 push]$ singularity --debug push alpine_latest.sif library://jscook2345/alpine/alpine
DEBUG   [U=503,P=7622]     UploadImage()                 Image hash computed as sha256.1574a2a1bd8f7fa44781508ca706cf44e4014ca2b9eb3f7be5e6b5e28dcfb84e
DEBUG   [U=503,P=7622]     apiGet()                      apiGet calling https://library.sylabs.io/v1/entities/jscook2345
DEBUG   [U=503,P=7622]     apiGet()                      apiGet calling https://library.sylabs.io/v1/collections/jscook2345/alpine
DEBUG   [U=503,P=7622]     apiGet()                      apiGet calling https://library.sylabs.io/v1/containers/jscook2345/alpine/alpine
DEBUG   [U=503,P=7622]     apiGet()                      apiGet calling https://library.sylabs.io/v1/images/jscook2345/alpine/alpine:sha256.1574a2a1bd8f7fa44781508ca706cf44e4014ca2b9eb3f7be5e6b5e28dcfb84e
INFO    [U=503,P=7622]     UploadImage()                 Image is already present in the library - not uploading.
DEBUG   [U=503,P=7622]     UploadImage()                 Setting tags against uploaded image
DEBUG   [U=503,P=7622]     apiGetTags()                  apiGetTags calling https://library.sylabs.io/v1/tags/5c944b7d5cf3490001ca7f9f
INFO    [U=503,P=7622]     setTags()                     Setting tag latest
WARNING [U=503,P=7622]     setTags()                     latest replaces an existing tag
DEBUG   [U=503,P=7622]     apiSetTag()                   apiSetTag calling https://library.sylabs.io/v1/tags/5c944b7d5cf3490001ca7f9f
</pre>

Why all these api calls to entites, than collections, than containers, than images? Shouldn't it be one API call to see if the image exists?

Why are we doing more after we decide not to upload the image?

**Comment by dtrudg** [comment]
> Why is it setting the latest tag if its not uploading?

If I push an image as `library://dtrudg-sylabs/ubuntu:18.04` and forget that I also want to tag it `bionic` then I can push the same image as `library://dtrudg-sylabs/ubuntu:bioinic` and it should add the `bionic` tag, but without uploading the image file again (as it's the same image).

> Why all these api calls to entites, than collections, than containers, than images? Shouldn't it be one API call to see if the image exists?

The code is always working forward through the path in case each of the entity/collection/container don't exist and need to be created.... which would need to be done before the image can be created.

The only odd bit here really is that we warn we are replacing a tag with the same tag, and on the same image.
