### ISSUE TITLE
build --json flag is orphan 

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#3078]
## Version of Singularity:

3.1

### Expected behavior

Been able to build from a definition file parsed as json

### Actual behavior

```
singularity build --json my.sif definition.json
ERR
```
Should we remove this flag ?

**Comment by vsoch** [comment]
If you expect some future where a user would serve definition files as json, from some endpoint, it could be lucrative to support this. But given that a (traditional) build recipe is just a text file, there also isn't any reason that you could wget / curl a standard text file. It's also much harder to write json than text, so the assumption is that the writing of these json files is done by some program / endpoint. My 0.02 - if there is a strong use case, keep and advertise the use case. if not, it's just feature bloat.
