### ISSUE TITLE
home (defined by ~/) during build results in error

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#3092]
## Version of Singularity:

3.1.0-rc2

### Expected behavior

Build a recipe with references to home (~/) and it goes to /root

### Actual behavior

Here is an example command that fails, no matter how you try to interact with ~/ (list, echo) it reports no such file or directory. It should be /root.

```bash
+ wget https://repo.anaconda.com/archive/Anaconda2-2018.12-Linux-x86_64.sh -O ~/anaconda.sh
~/anaconda.sh: No such file or directory
FATAL:   post proc: exit status 1
FATAL:   While performing build: while running engine: exit status 255
```

Here is a mini version to reproduce:

```bash
Bootstrap: docker
From: alpine:latest

%post
    apk update && apk add wget
    echo $HOME
    echo $SHELL
    ls ~/
    wget https://repo.anaconda.com/archive/Anaconda2-2018.12-Linux-x86_64.sh -O ~/anaconda.sh
    ls $HOME
```

I tried both kinds of shells (sh and bash) and this isn't the issue. I also tried (locally) setting different bash options:

```bash

set -e
set -o pipefail

ls $HOME
echo ~/
```
but those worked fine on my local machine! The issue is here https://github.com/mkijowski/container-education/issues/2 and notably, the user has a bunch of recipes that built fine on previous versions of Singularity that now fail, and he was considering rewriting all the files.

### Steps to reproduce behavior

Build the recipe above.

**Comment by vsoch** [comment]
It looks like when I export HOME, the error is resolved:

```
Bootstrap: docker
From: alpine:latest

%post
    apk update && apk add wget
    export HOME=/root
    whoami
    ls ~
...
Executing busybox-1.29.3-r10.trigger
OK: 6 MiB in 15 packages
+ export 'HOME=/root'
+ whoami
root
+ ls /root
INFO:    Creating SIF file...
INFO:    Build complete: container.sif
```
Should HOME be one of the envars included / defined by default?

**Comment by jscook2345** [comment]
@vsoch Were you building with `sudo`? Sometimes that can have an odd effect on the environment.

**Comment by vsoch** [comment]
I’m not aware of another way to build without a recipe? This should not be happening.

**Comment by vsoch** [comment]
with previous versions of Singularity, $HOME was defined by default (to be /root) and I believe that is expected behavior? It seems like the case that a special / custom set of environment variables are being passed, and $HOME is missing.

**Comment by jscook2345** [comment]
Each machine can have a different `sudo` policy, so that is why I ask. Defaults on one system may not be the same as another.

@jmstover @ikaneshiro ping for comment on the problem!

**Comment by vsoch** [comment]
Interesting! FWIW a build (with sudo) worked for me with previous versions of Singularity (and the ~ would correspond to home, and $HOME was defined) and now it doesn't seem to.

**Comment by vsoch** [comment]
Try this:
```bash
$ docker run -it --privileged --entrypoint bash singularityware/singularity:2.6
```
the recipe

```bash
cat Singularity

From: busybox
Bootstrap: docker
%post
echo $HOME && ls ~/
```
build, notice $HOME and ~/ are defined (we are already root user). There are some build errors because of being in Docker but the post still shows the vars defined.
```bash
$ singularity build container.sif Singularity 
Exploding layer: sha256:697743189b6d255069caf6c455be10c7f8cae8076c6f94d224ae15cd41420e87.tar.gz
Exploding layer: sha256:29ade4f96a9909940ce0251b8182993c53f22a7e006a8c7fe868f1e0032d52b5.tar.gz
Running post scriptlet
+ echo /root
/root
+ ls /root/
Finalizing Singularity container
Calculating final size for metadata...
Skipping checks
Building Singularity image...
Singularity container built: container.sif
Cleaning up...
```

Here is the same with Singularity 3.1

```bash
$ docker run -it --privileged --entrypoint sh singularityware/singularity:3.1-slim
/ # apk add vim
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/5) Installing lua5.2-libs (5.2.4-r4)
(2/5) Installing ncurses-terminfo-base (6.0_p20171125-r1)
(3/5) Installing ncurses-terminfo (6.0_p20171125-r1)
(4/5) Installing ncurses-libs (6.0_p20171125-r1)
(5/5) Installing vim (8.0.1359-r0)
Executing busybox-1.27.2-r11.trigger
OK: 40 MiB in 24 packages
/ # vim Singularity
/ # singularity build container.sif Singularity 
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:697743189b6d255069caf6c455be10c7f8cae8076c6f94d224ae15cd41420e87
 738.18 KiB / 738.18 KiB [==================================================] 0s
Copying config sha256:85dcb8c21e86b3e01a3a45fc932b31f5194c174d0a5d8a993381cc1fca749f40
 575 B / 575 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Running post scriptlet
+ echo

+ ls '~/'
ls: ~/: No such file or directory
FATAL:   post proc: exit status 1
FATAL:   While performing build: while running engine: exit status 255
/ # 
```
In case you need to reproduce.

**Comment by vsoch** [comment]
An update from @cyphar on the opencontainers slack:

> in runc we automatically set HOME if it's not part of the runtime configuration -- see https://github.com/opencontainers/runc/blob/master/libcontainer/init_linux.go#L321-L326

This might be what needs to be done for Singularity too.

**Comment by ikaneshiro** [comment]
@vsoch @jscook2345 Having `HOME` seems like something that should be done. I'll look into a fix

**Comment by vsoch** [comment]
Cool thanks @ikaneshiro !

**Comment by jscook2345** [comment]
@ikaneshiro 

Some things to keep in mind while you work on this. Both could either effect your work or be affected by your work.

The privilege package. I believe it is setting `HOME` and potentially some other variables to work around issues like this in testing.

Our `make test` makefile target. We call `go test` with `sudo -E`.
