### ISSUE TITLE
Unable to add capabilities to a user

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3093]
## Version of Singularity:

singularity version 3.1.0

### Expected behavior

The capability should be assigned to the mentioned user and same should reflect in the file capability.json

### Actual behavior

FATAL:   Unable to add capabilities: while setting capabilities for user david: user does not exist

### Steps to reproduce behavior

`$ sudo singularity capability add --user david CAP_FOWNER`

**Comment by sushma-98** [comment]
I am able to add for some users though.

Example: `$ sudo singularity capability add --user eduardo CAP_NET_RAW` works

**Comment by gmkurtzer** [comment]
Is "david" and "eduardo" real user names on that system?

**Comment by sushma-4** [comment]
Eduardo is a user on the VM we are using, David is not. 
But if you use `add —user nobody` It would work even though “nobody” is not a user.

**Comment by cclerget** [comment]
@sushma-98 I think `nobody` is a valid user, you can test with `getent passwd nobody` or `grep nobody /etc/passwd`, this is an expected failure if `david` doesn't exists as `capability add/drop` accept only existing users/groups

**Comment by GodloveD** [comment]
`nobody` is a good alias for `david`.  😜

**Comment by sushma-98** [comment]
> @sushma-98 I think `nobody` is a valid user, you can test with `getent passwd nobody` or `grep nobody /etc/passwd`, this is an expected failure if `david` doesn't exists as `capability add/drop` accept only existing users/groups

Okay, seems like capabilities can only be added to real users, therefore it's an expected error, Thank you
