### ISSUE TITLE
The "-d" flag gives an unrelated error.

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3096]
## Version of Singularity:

3.1

### Expected behavior

The -d flag describes the mentioned Linux capability. 

### Actual behavior

It does give a description of the capability but it also gives:
`FATAL:   Unable to add capabilities: no user or group specified`

### Steps to reproduce behavior

`sudo singularity capability add/drop -d SYSLOG`

**Comment by cclerget** [comment]
@sushma-98 Added reference in #3066 which will fix this one
