### ISSUE TITLE
image-building example fails

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#31]
I'll give up at this point -- I probably should have batched things, apologies.

I tried the image-building example in the readme on centos7.  Those two functions definitely aren't defined anywhere:

```
[vagrant@localhost ~]$ cat centos.def
VERSION=7
PackageRepo "http://mirror.centos.org/centos-${VERSION}/${VERSION}/os/\$basearch/"
Initalize
InstallPkgs centos-release coreutils python strace vim-minimal
Finalize
[vagrant@localhost ~]$ sudo singularity bootstrap /tmp/Centos-7.img centos.def
Checking for yum...
./centos.def: line 2: PackageRepo: command not found
./centos.def: line 3: Initalize: command not found
CRITICAL:yum.cli:Config error: Error accessing file for config file:///mnt//yum.conf
```

I wondered if test.sh would help, but that looks obsolete now.

By the way, on the readme: it says that Red Hat doesn't provide debootstrap.  However it is in EPEL and Fedora https://apps.fedoraproject.org/packages/debootstrap, as yum is in Debian.

**Comment by gmkurtzer** [comment]
Sorry, I stayed up late last night working on it and forgot to update the readme. Check in the examples directory, there should be working templates there. 

Good points about yum on Debian and debootatrap on RH, I'll change that. 

Master is moving very fast now, I'm looking forward to branching 2.x and start stabilizing it but that will wait until I have all features and fixes done that are necessary. 

Greg.

**Comment by loveshack** [comment]
Thanks. I missed the examples.  It worked with that, though it made a 2GB image.

**Comment by gmkurtzer** [comment]
Yes, but it is a 2GB sparse image that can grow. 2GB is maybe too large for default size though. Maybe half or a third of that?

**Comment by gmkurtzer** [comment]
I lowered the image size down to 768 in 211bd09. Hopefully that is what you were eluding to (if not reply again). Thanks!

**Comment by loveshack** [comment]
You wrote: 

> Yes, but it is a 2GB sparse image that can grow. 2GB is maybe too
> large for default size though. Maybe half or a third of that?

Right; that's what expected, but I messed up checking.  It's ~400 MB
real.

**Comment by gmkurtzer** [comment]
Yep, that is only because it is a sparse file. 2GB was max. Now 768 is Max.
But... It is easy to add space to a sparse file, and extend the image (and
file system boundary). So the 400MB that you are seeing is the actual
consumed space plus file system overhead.

On a sparse file system of 768MB, the file system overhead is about 17MB
and on a 2GB image the file system overhead is 66MB. So I really like the
modification to 768MB for default.
