### ISSUE TITLE
oci attach to a created container will hang until the container is started

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3100]
## Version of Singularity:

3.1.0

Perhaps `oci attach` should only be allowed to attach to 'running' oci containers? I'm not sure how K8S influences this. I just wanted to see what you thought.

Example:

terminal A:
`sudo singularity oci create --bundle ./bundle myc`
`sudo singularity oci attach myc`
'hang occurs'

terminal B:
`sudo singularity oci start myc`

terminal A:
'No longer hanging, I'm now in my container shell'

**Comment by sashayakovtseva** [comment]
k8s attaches to a running containers only, see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go#L4140)

**Comment by GodloveD** [comment]
So @sashayakovtseva is this working as expected then?  If so, can we close the issue?

**Comment by sashayakovtseva** [comment]
From CRI perspective - yes
