### ISSUE TITLE
should oci containers show up in instance list?

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3103]
## Version of Singularity:

3.1.0

Should oci containers show up in `instance list`?

<pre>
$ sudo singularity oci create --bundle ./bundle myc
$ sudo singularity oci start myc
$ sudo singularity instance list
INSTANCE NAME    PID      IMAGE
myc              13485    /home/justin/2019-03-24/singularity/oci/run/bundle/rootfs
</pre>

**Comment by cclerget** [comment]
@jscook2345 No, need fix as instance commands have no effect on "OCI instance" and vice versa

**Comment by jscook2345** [comment]
@cclerget Sounds good!

**Comment by cclerget** [comment]
@jscook2345 Lol I forgot commas, I reopen it as it requires fix

**Comment by jscook2345** [comment]
Oops! Sorry! Should of read it closer! Thanks @cclerget !
