### ISSUE TITLE
should oci exec work on a paused oci container?

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3105]
## Version of Singularity:

3.1.0

<pre>
[justin@ip-172-31-94-96 run]$ sudo singularity oci state myc
...running...
[justin@ip-172-31-94-96 run]$ sudo singularity oci pause myc
[justin@ip-172-31-94-96 run]$ sudo singularity oci exec myc uname -a
WARNING: seccomp requested but not enabled
Linux mrsdalloway 2.6.32-754.11.1.el6.x86_64 #1 SMP Tue Jan 22 17:25:23 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
</pre>

**Comment by cclerget** [comment]
It shouldn't, need fix

**Comment by jscook2345** [comment]
@cclerget 

Another exec on bad state issue, I think.

<pre>
$ sudo singularity oci delete myc
$ sudo singularity oci create --bundle ./bundle myc
$ sudo singularity oci start myc
$ sudo singularity oci kill myc KILL
$ sudo singularity oci exec myc id
ERROR  : Failed to enter in pid namespace: No such file or directory
</pre>

**Comment by Flamefire** [comment]
Follow-up question: Should `exec` work on a container in `created` state? It did before

**Comment by jscook2345** [comment]
@Flamefire 

I think the answer is no. `oci exec` is not a part of the OCI spec itself. It was added on as a convenience to query the container. `oci start` is the only part that is required for running a process in the OCI spec, so we wait for that state before allowing `oci exec` commands to query the container.

@cclerget 

Please correct me if I am wrong about any of this. Thanks!
