### ISSUE TITLE
Better help for key pull that talks about trust

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#3116]
## Version of Singularity:

Write here.

### Expected behavior

`singularity help key pull` tells you that pulling a key and adding it to your keyring is an explicit act of trust. 

Write here.

### Actual behavior

`singularity help key pull` doesn't really discuss trust at all.

```
$ singularity help key pull
Fetch an OpenPGP public key from a key server

Usage:
  singularity keys pull [pull options...] <fingerprint>

Description:
  The 'key pull' command allows you to connect to a key server look for and
  download a public key. Key rings are stored into (e.g.,
  $HOME/.singularity/sypgp).

Options:
  -h, --help         help for pull
  -u, --url string   specify the key server URL (default
                     "https://keys.sylabs.io")


Examples:
  $ singularity key pull D87FE3AF5C1F063FCBCC9B02F812842B5EEE5934


For additional help or support, please visit https://www.sylabs.io/docs/
```

**Comment by tri-adam** [comment]
How about:

> Description:
>   The 'key pull' command allows you to retrieve public key material from a remote key server, and add it to your keyring. Note that Singularity consults your keyring when running commands such as 'singularity verify', and thus adding a key to your keyring implies a level of trust. Because of this, it is recommended that you verify the fingerprint of the key with its owner prior to running this command.

**Comment by mem** [comment]
This is related to #3118
