### ISSUE TITLE
add tags or buildcfg entries for features to verify against

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3122]
## Version of Singularity:

3.1.0

Currently `mount` does not work on older kernels and the failure is not very graceful.

It would be nice if we had a `go tag` or a `buildcfg` entry that we could test against so we could fail gracefully and tell the user why we are failing. Something like a 'kernel version' or something like a build check like we do for `seccomp`.

What do you think?

**Comment by dtrudg** [comment]
We've had people bring up that they build in one location, then deploy elsewhere. Also if you have a feature backported with a kernel update you want to be able to make use of it without a recompile.... so I think runtime checks would be heavily preferred here.

We can definitely generally do better with error messages and runtime checks.
