### ISSUE TITLE
linter failure when trying to make the sync-socket options hidden

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3127]
## Version of Singularity:

3.1.0

Both `oci create` and `oci state` have an option called `--sync-socket` that is marked as internal. Perhaps this should be a hidden option?

@cclerget what do you think?

I tried to do this myself by adding some code to `cmd/internal/cli/oci_linux.go`, but the linter failed with the following error and I decided to move on for now.

<pre>
make ...
 CHECK golangci-lint
cmd/internal/cli/oci_linux.go:37: File is not `goimports`-ed (goimports)
        OciCreateCmd.Flags().MarkHidden("sync-socket")
</pre>

Any ideas on the lint error @mem ?

**Comment by cclerget** [comment]
@jscook2345 Well the primary goal of `--sync-socket` was to simplify things for CRI, but may be useful for other tools, I think it's better to remove internal mention instead

**Comment by sashayakovtseva** [comment]
Or simply run goimports as linter suggests

**Comment by sashayakovtseva** [comment]
may be some indents that cause this

**Comment by jscook2345** [comment]
I will go ahead and remove the 'internal only' parts in my Draft PR for oci docs. Thanks @cclerget and @sashayakovtseva !

**Comment by mem** [comment]
> ## Version of Singularity:
> 3.1.0
> 
> Both `oci create` and `oci state` have an option called `--sync-socket` that is marked as internal. Perhaps this should be a hidden option?
> 
> @cclerget what do you think?
> 
> I tried to do this myself by adding some code to `cmd/internal/cli/oci_linux.go`, but the linter failed with the following error and I decided to move on for now.
> 
> make ...
>  CHECK golangci-lint
> cmd/internal/cli/oci_linux.go:37: File is not `goimports`-ed (goimports)
>         OciCreateCmd.Flags().MarkHidden("sync-socket")
> Any ideas on the lint error @mem ?

That error means that either the list of imported packages is not in the order the linter expects it to be, which should match goimports.

Run:

```
goimports -w cmd/internal/cli/oci_linux.go
```

and see what it changes.
