### ISSUE TITLE
oci kill --force option seems redundant, can it be removed?

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3138]
## Version of Singularity:

3.1.0

Can't the same affect be had with either of the follow? Perhaps it could be removed? I don't see it in `runc` or the `runtime-tools` validation. Maybe I missed it?

`sudo singularity oci kill --signal KILL mycontainer`

or

`sudo singularity oci kill mycontainer KILL`

**Comment by cclerget** [comment]
@jscook2345 Just a shortcut, if I remember right it was asked by @vsoch

**Comment by vsoch** [comment]
https://github.com/sylabs/singularity/issues/2806

**Comment by jscook2345** [comment]
Thanks for the info @cclerget @vsoch ! Closing!
