### ISSUE TITLE
 /dev/shm permission issue with python module joblib

### ISSUE THREAD

**Issue by belledon** [apptainer/singularity#315]
I've been trying to use the python module `joblib` from within a singularity container bootstrapped from an ubuntu def. The container seems to work fine and installing `pyhton3-pip` for python3 occurs without a problem. I also do not receive any errors with installing joblib via pip3. After some debugging I found that joblib catches an error when trying to call `mutliprocess.Semaphore()`. I replicated the error below:

```
Singularity.v2_2.img> python3 
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocess as m
>>> m.Semaphore()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/context.py", line 81, in Semaphore
    return Semaphore(value, ctx=self.get_context())
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/synchronize.py", line 127, in __init__
    SemLock.__init__(self, SEMAPHORE, value, SEM_VALUE_MAX, ctx=ctx)
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/synchronize.py", line 60, in __init__
    unlink_now)
FileNotFoundError: [Errno 2] No such file or directory
```

After some searching online, I found that this may be an issue with read-only to `/dev/shm` (found [here](http://stackoverflow.com/questions/6033599/oserror-38-errno-38-with-multiprocessing)). I am not really sure how to proceed. I read one of your previous issues (#147) which I interpreted to mean that it is not necessarily practical to modify `/dev/shm`. However, I do not intend the user's to have access, rather I would like to install this modules globally and then running the container remotely on a cluster. I would appreciate any suggestions you would have to go about this.

**Comment by vsoch** [comment]
Hi @belledon - I think what we want to do is change permissions on the install, which should occur at Bootstrap. Would you be able to share how you are creating your image currently?

**Comment by belledon** [comment]
Hi @vsoch ,

Bellow is the def file I use. I also have to do some configuring in shell (like update locales, for some reason it is never set after bootstrap)

```

BootStrap: debootstrap
OSVersion: xenial
MirrorURL: http://us.archive.ubuntu.com/ubuntu/


%runscript
    echo "SINGULARITY RUNSCRIPT"
    export GRASPIT="/graspit"
    echo "Arguments received: $*"
    exec xvfb-run -a /usr/bin/python3 "$@"


%post
    echo "Hello from inside the container"
    apt-get -y install software-properties-common 
    add-apt-repository ppa:git-core/ppa
    add-apt-repository main
    add-apt-repository universe
    add-apt-repository restricted
    add-apt-repository multiverse
    apt-get update
    apt-get -y install git
    apt-get -y install cmake
    apt-get update
    apt-get -y install libsoqt4-dev 
    apt-get -y install libqt4-dev
    apt-get -y install libblas-dev
    apt-get -y install liblapack-dev
    apt-get -y install libqhull-dev
    apt-get -y install libeigen3-dev
    apt-get -y install libboost-filesystem-dev
    apt-get -y install libboost-system-dev libboost-thread-dev libboost-program-options-dev
    apt-get -y install g++
    apt-get -y install wget
    apt-get -y install vim
    apt-get -y install xvfb
    apt-get -y install locales
    apt-get -y install python3-pip
    python3 -m pip install --upgrade pip
    python3 -m pip install multiprocess
    python3 -m pip install joblib
    python3 -m pip install scipy
    python3 -m pip install numpy
    python3 -m pip install matplotlib

    cd /
    echo "Making graspit related directories"
    if [ -d "//graspitInstall" ]; then 
      rm -r "//graspitInstall" 
    fi

    if [ -d "//graspPlanningInstall" ]; then 
      rm -r "//graspPlanningInstall"
    fi

    mkdir "//graspitInstall"
    mkdir "//graspPlanningInstall"
    echo "Cloning graspit repos"
    if [ -d "//graspit" ]; then 
      rm -r -f "//graspit"
    fi
    if [ -d "//graspit-pkgs" ]; then 
      rm -r -f "//graspit-pkgs" 
    fi

    git clone https://github.com/belledon/graspit.git
    git clone https://github.com/belledon/graspit-pkgs.git

    cd //graspit
    mkdir build && cd build
    cmake -DBUILD_SHARED_LIBS=true -DCMAKE_INSTALL_PREFIX=//graspitInstall ..
    make
    make install

    cd //graspit-pkgs/grasp_planning_graspit
    mkdir build && cd build
    cmake -DBUILD_GRASPIT=false -DCMAKE_PREFIX_PATH=//graspitInstall -DCMAKE_INSTALL_PREFIX=//graspPlanningInstall ..
    make
    make install

    echo "Updating library paths"
    cd /etc/ld.so.conf.d
    echo "/graspitInstall/lib" | cat > graspit.conf
    echo "/graspPlanningInstall/lib" | cat > graspPlanning.conf
    ldconfig

    rm -r /dev/shm
    mkdir /dev/shm
    chmod 777 /dev/shm

```

I think I tried mounting it during the run script section .. but I assume it makes most sense in the postscript section. -Thanks for your quick reply!

**Comment by vsoch** [comment]
Ok, here is a first pass! The good and bad news is that I'm not able to reproduce the error. Here is my bootstrap, using your definition above saved in a file called `Singularity`:

```
  sudo singularity create --size 4000 def.img
  sudo singularity bootstrap def.img Singularity
```

## Using shell as sudo

When I shell into the container using sudo:

```
  sudo singularity shell def.img
  python3
```

I don't see the error with multiprocess:

![image](https://cloud.githubusercontent.com/assets/814322/20425130/0063f04c-ad2e-11e6-8d96-1a6d510c15a8.png)

I only see it when I exit from Python:

```
  >>> quit()
  Error in atexit._run_exitfuncs:
  FileNotFoundError: [Errno 2] No such file or directory
```

but this looks like a [different bug](http://bugs.python.org/issue19891). This is consistent for each time that I start and exit from Python, when running as sudo. 

## Shell into Container (non sudo)

When I shell into the container without sudo:

```
 singularity shell def.img
  python3
  >>> import multiprocess as m
  >>> m.Semaphore()
  <Semaphore(value=1)>
  >>> quit()
  Singularity.def.img>
```

There seems to be no issue at all. The files in the `/dev/shm` seem to be writing ok:

```
  Singularity.def.img> ls /dev/shm
  pulse-shm-639573807
```

## Run Container as Executable

When I run the container as an executable, I also get this working behavior:

```
     ./def.img 
SINGULARITY RUNSCRIPT
Arguments received: 
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocess as m
>>> m.S
m.SUBDEBUG      m.SUBWARNING    m.Semaphore(    m.SimpleQueue(  
>>> m.Semaphore()
<Semaphore(value=1)>
>>> 
```

So - I think to help, I need a bit more information about how you are running this to produce the error?

**Comment by truatpasteurdotfr** [comment]
/dev/shm is not a regular directory, why did you need to delete/recreate it with different permissions?

/etc/fstab on the host:

```
    tmpfs                   /dev/shm                tmpfs   defaults        0 0
```

```
$ grep shm /proc/mounts
tmpfs /dev/shm tmpfs rw,relatime 0 0
$ ls -ld /dev/shm/
drwxrwxrwt 2 root root 100 Nov 10 16:30 /dev/shm/
```

inside the container:

```
> grep shm /proc/mounts
tmpfs /dev/shm tmpfs rw,relatime 0 0
```

**Comment by belledon** [comment]
@vsoch ,
I tried this on another system and it worked just fine after a fresh clone... Not entirely sure what was going on before. Thanks again for your help! It may have to do with the other system running Linux Mint 17.3 rather than ubuntu 16.04? But that would be weird since it is based off ubuntu 14. 

@truatpasteurdotfr ,
Both `multiprocess` and`joblib` write to `/dev/shm` when attempting to instantiate parallel threads. I was never planning on changing those permissions. 

Thanks again!
