### ISSUE TITLE
Unpack SIF system partition without mounting

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#3153]
## Version of Singularity:

3.2

### Expected behavior

Should be able to build or unpack data from a SIF without root.

### Actual behavior

Requires root because it mounts system partition during extraction process.

**Comment by cclerget** [comment]
@ikaneshiro it's already implemented for user namespace run from URI, unpacker is available : https://github.com/sylabs/singularity/blob/master/pkg/image/unpacker/squashfs.go and an example here https://github.com/sylabs/singularity/blob/2019bb9ff20b5ac2e127b1082e4703369193cfaf/cmd/internal/cli/actions_linux.go#L40

**Comment by ikaneshiro** [comment]
Closed this prematurely
