### ISSUE TITLE
Option to not automatically add /scif/apps/.../bin and /scif/apps/.../lib to PATH and LD_LIBRARY_PATH, respectively

### ISSUE THREAD

**Issue by stilley2** [apptainer/singularity#3157]
## Version of Singularity:

2.5.2

## Description

This is more of a question/feature request than a bug. Is it possible to define and app using the %app* sections, but *not* have that's apps bin and lib directories added to PATH and LD_LIBRARY_PATH? This would be useful for at least two reasons

1) some programs (e.g. FSL and freesurfer) have their own environment setup scripts, which can cause duplications in PATH
2) some programs produce shared libraries in lib but do not actually need them, or reference them using RPATH. In this case, having lib in LD_LIBRARY PATH is unnecessary and may cause more issues. For example, app1 and app2 are to be loaded simultaneously. App1 uses shared library X.so.1 and app2 uses X.so.2. If app1 uses RPATH but still adds lib to LD_LIBRARY_PATH, and app2 doesn't use RPATH, app2 may find the wrong version of the library depending on the order in which the apps are loaded

Currently I'm working around this by manually editing LD_LIBRARY_PATH in %appenv, which seems a bit hacky. I'd love to here people's thoughts on this issue.

**Comment by dtrudg** [comment]
I believe adding these locations to the PATH is pretty explicitly needed to say we are implementing SCIF - is that a misunderstanding @vsoch ?

**Comment by vsoch** [comment]
Yes that is correct! a SCIF implementation will add the lib folder to `LD_LIBRARY_PATH` and the bin folder to the `PATH` when the app is active, respectively (the user should not need to manually do this).

**Comment by vsoch** [comment]
Here is what that looks like with the scif Python implementation: https://github.com/vsoch/scif/blob/fd491b2dd26afe38fff5de4508012489c4dd2c79/scif/main/apps.py#L63

**Comment by dtrudg** [comment]
@vsoch - right we are doing this in Singularity, so the ask here in the original post is really to have an option to not support SCIF properly, while running a SCIF app.

https://github.com/sylabs/singularity/blob/d522c874d454221d87163b6458001580e2543a4a/internal/pkg/build/sources/base_environment.go#L181

https://github.com/sylabs/singularity/blob/d522c874d454221d87163b6458001580e2543a4a/internal/pkg/build/sources/base_environment.go#L186

I'm going to close this, noting that disabling LD_LIBRARY_PATH or PATH addiditions for SCIF apps is not something we want to do in Singularity, as it means we aren't really then running a SCIF app as the spec asks.

I think this would be something to consider further up, in the SCIF spec, if you need it supported @stilley2 .

**Comment by vsoch** [comment]
@stilley2 looking at your particular use case, this does seem like a special case, and your workaround seems logical. If you don't use those folders, adding them to the path (essentially empty) wouldn't have any effect, no? Anyway, I agree with @dctrud that this is part of the SCIF spec, and the appropriate fix is a workaround as you've done, or just not using SCIF apps.
