### ISSUE TITLE
Runscript: doesn't seem to be obtained from Docker image

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#316]
need to test this further, it doesn't appear to be working as expected.

**Comment by vsoch** [comment]
ok, it looks like the distinction is between "ENTRYPOINT" and "CMD" - where ENTRYPOINT is an executable for the container, and CMD is something to run. The first is more appropriate for a default bootstrap, so I am going to do a PR to make the default to use ENTRYPOINT, and if the user specifies IncludeCmd then CMD will be used instead.

**Comment by vsoch** [comment]
http://stackoverflow.com/questions/21553353/what-is-the-difference-between-cmd-and-entrypoint-in-a-dockerfile

**Comment by vsoch** [comment]
ok, figured this out. the postbootstrap.sh is actually removing the runscript written from the Docker (python) functions. For example, here the singularity root fs location is printed, followed by the resulting folder structure:

![image](https://cloud.githubusercontent.com/assets/814322/20451193/94fde4e2-adab-11e6-9576-93ed90228a5b.png)

you can see during build (top in white) the file `singularity` is present. At the bottom (the built image, in blue) it is not.

**Comment by bauerm97** [comment]
@vsoch We should discuss handling of this after the C bootstrapping code goes through as well. It would make sense that we remove all of the docker specific logic from the bootstrapping code and let the python docker code do all of the handling of the layers. I'll simply pass a few arguments into the python code and it can take care of everything. Sound good?

**Comment by vsoch** [comment]
+1 :)
