### ISSUE TITLE
Command seems to accept some extra characters

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3171]
## Version of Singularity:

3.1-2

### Expected behavior

The command does not take any additional characters

### Actual behavior

It does not give any error and accepts the command

### Steps to reproduce behavior

`singularity \capability avail >fowner`

or 

`singularity \capability avail chown`

**Comment by cclerget** [comment]
@sushma-98 Both characters are interpreted by shell not by singularity, `\` is an escape character, and `>fowner` will redirect output into file `fowner`. Closing as this is not a bug
