### ISSUE TITLE
Errors when incorrect global flag is used with just one dash

### ISSUE THREAD

**Issue by 15baraniana** [apptainer/singularity#3176]
## Version of Singularity:

3.1-2

### Expected behavior

`sudo singularity -debug build lolcow.sif library://sylabs-jms/testing/lolcow`
Probably should give an error about bad flags

'sudo singularity -star build lolcow.sif library://sylabs-jms/testing/lolcow'
Also should give an error

### Actual behavior

`sudo singularity -debug build lolcow.sif library://sylabs-jms/testing/lolcow`
No error and no actions

`sudo singularity -star build lolcow.sif library://sylabs-jms/testing/lolcow`
Performs the build in silent mode

### Steps to reproduce behavior

Try some misspelled global flags with just 1 dash (`-star,-deb,-de`)

**Comment by gvallee** [comment]
This has been fixed in PR #3230
