### ISSUE TITLE
Wrong URL for keystore

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3182]
## Version of Singularity:

3.1.0

### Expected behavior

The url takes you the singularity keystore - https://cloud.sylabs.io/keystore

### Actual behavior

404 Error - Page not found - https://keys.sylabs.io/

### Steps to reproduce behavior

`singularity verify --help`
Options:
 -g, --groupid uint32   group ID to be verified
  -h, --help             help for verify
  -i, --id uint32        descriptor ID to be verified
  -u, --url string       key server URL (default "https://keys.sylabs.io")

**Comment by GodloveD** [comment]
Seems like this is a difference between the front end and the API.
