### ISSUE TITLE
Non-Existant GID handling

### ISSUE THREAD

**Issue by Nekel-Seyew** [apptainer/singularity#319]
There are cases where users will have GIDs added to their user, but no actual groups will exist in /etc/groups. Singularity errors out at this. It would be handy to have a way to ignore the issue, and just warn the user of skipped GIDs.

**Comment by gmkurtzer** [comment]
Can you copy/paste the error you are getting?

I am also curious what the use case is and how I can replicate this for testing.

Thanks!

**Comment by bbockelm** [comment]
Errors out or just crashes?  What version are you running?

An older version crashed; I agree we can probably work around these groups (if we don't already).

**Comment by Nekel-Seyew** [comment]
2.2, and the error I get is:

ERROR  : Failed to lookup GID 1095201142 group entry: No such file or directory
ABORT  : Retval = 255

but when I run `id` in my shell, I get:
uid=221132(nekel) gid=40(dip) groups=40(dip),1095201142

since that crazy number isn't a group, but is an ID I have.

**Comment by bbockelm** [comment]
Ok, I re-familiarized myself with the code.  Basically, the `getgrgid` call is doing some undocumented behavior.  Here's the snippet from the man page:
```
       0 or ENOENT or ESRCH or EBADF or EPERM or ...
              The given name or gid was not found.
```
I guess you are hitting the "..." case?  If you were hitting one of the documented error codes, we indeed do downgrade to a warning.

Anyhow, can you run it through `strace` and see where things fail out?  I want to figure out what exactly is triggering the problem.  Does `/etc/groups` not exist?

**Comment by Nekel-Seyew** [comment]
UPDATE:

In redhat 7, ENOENT was added as a possible return value if the group isn't in the /etc/group list, and the ENOENT wasn't in the conditions of the src, at least as of last week when I pulled last.

Creating patch.

**Comment by gmkurtzer** [comment]
Did the patch fix it, can we close this issue?

Thanks!
