### ISSUE TITLE
replace the use of secret with private in keys commands

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3201]
## Version of Singularity:

3.1-2

Using both `secret` and `private` to describe keys is a little confusing. I think we should stick with just `private`.

What do you think?

**Comment by jscook2345** [comment]
Looking at the `gpg` man page, perhaps this should be the other way around?

What do you think @WestleyK ?

**Comment by WestleyK** [comment]
> Using both `secret` and `private` to describe keys is a little confusing. I think we should stick with just `private`.

@jscook2345, Well, the flag for exporting a private/secret key is `--secret`, (`--export-secret-keys` for gpg), so maybe sticking to `secret` would make more sense?

**Comment by jmstover** [comment]
I vote for using `secret`

**Comment by jscook2345** [comment]
I think the thing that confused me was if I look at documentation on wikipedia or other places about encryption with public / private keys, they do not use the word `secret`. Only `gpg` seems to.

I do not have a strong feeling (other than I like to side on the public norm) but think that the discussion here is good.

**Comment by jmstover** [comment]
GPG/PGP use `secret` as this is something only _you_ should have access to. It's a secret of yours. "private" works, but doesn't have the same connotation that `secret` does.

From OpenSSL INSTALL file:
```
Availability of cryptographically secure random numbers is required for secret key generation.
```
For what should be known only to yourself, `secret` is used.

**Comment by WestleyK** [comment]
Closing as `secret` is more commonly used, both with gpg, and singularity.
