### ISSUE TITLE
keypair should be differentiated somehow in keys list

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3202]
## Version of Singularity:

3.1-2

Since `keys list` shows both a public and a private part (with the exact same data shown) if you create your own keypair it might be good to show they are part of the same keypair? Otherwise it kinda looks like the same key is in both lists, which I know parts of it are, but I still got confused a little. ;)

```
$ singularity keys list --secret
Private key listing (/home/justin/.singularity/sypgp/pgp-secret):

0) U: Justin Cook (test) <justin@sylabs.io>
   C: 2019-04-03 09:59:08 -0400 EDT
   F: DDAFFF474C3788E23986CB3F7922FD42029A6B27
   L: 4096
   --------

$ singularity keys list
Public key listing (/home/justin/.singularity/sypgp/pgp-public):

0) U: Sylabs Admin () <support@sylabs.io>
   C: 2018-11-01 18:20:02 -0400 EDT
   F: 8883491F4268F173C6E5DC49EDECE4F3F38D871E
   L: 4096
   --------
1) U: Justin Cook (test) <justin@sylabs.io>
   C: 2019-04-03 09:59:08 -0400 EDT
   F: DDAFFF474C3788E23986CB3F7922FD42029A6B27
   L: 4096
   --------
```

**Comment by jchavezlavalle** [comment]
@jscook2345 I think this behavior is correct, when you run the newpair command, the private and public keys are automatically added in the local keystores (both for private and public) and the fingerprint is the same on both keys (private or public).. This behavior is also the same as gpg works: using a `gpg --list-keys` to show public keys and `gpg --list-secret-keys` will show the same keys with the same fingerprints if the keypair was generated with gpg. If the key was explicitly imported into the keystore, then in that case it will be listed only on either the secret or the public keystore.

**Comment by jmstover** [comment]
Correct. If you look at GPG you'll also have:  `$HOME/.gnupg/secring.gpg` and `$HOME/.gnupg/pubring.gpg` for the secret and public keyrings. `list keys` by default will list the public keys in your key ring. You need to explicitly say: Show me the secret keys

**Comment by WestleyK** [comment]
I agree with the above comments. But its worth discussing if others feel like this should be different:

I think this would satisfied @jscook2345 idea:

```
$ singularity key list --secret
Public key listing (/tmp/foo/pgp-public):

0) U: westley (bar) <foo> [PRIVATE]
   C: 2019-09-10 09:54:46 -0700 PDT
   F: 4C3303B43EFDA24A73BB0D9D0FC0B7217DB6DA2A
   L: 4096
   --------
1) U: WestleyK (Sylabs test key) <westleyk@nym.hush.com> [PRIVATE]
   C: 2019-08-13 11:35:31 -0700 PDT
   F: F2033FC8987049FBD73E2902B49434CA0E92D0AC
   L: 1024
   --------
```

_There is a ` [PRIVATE]` after the name/email._

This is just one idea that would fix this issue, although this may be something we dont want to fix, since adding/modifying the key text is probably not ideal.

**Comment by WestleyK** [comment]
Closing as current behavior is correct, and no suggestion/opinion to change it.
