### ISSUE TITLE
Allow admins to restrict usage of --fakeroot option

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#3207]
`--fakeroot` will require suid workflow to map uid gid info within the container.  Because ranges will be mapped from the host system to the container there could be some overlap.  Admins may want to restrict usage, and so there should be a way (in the conf file?) for admins to do this restriction.  

Should think about whether this should be enabled or disabled by default.  

To discuss with @DrDaveD.

**Comment by DrDaveD** [comment]
As I suggested in #2718, I think the best way to handle it is to have in the configuration file a list of users that are allowed to use the feature.  Assign each user 64k user and group ids, subtracting from some high number for each user.  The high number could also be configurable, but give it a default.  The number of ids assigned to each user could also be configurable, but default to 64k.  This would be a slightly less flexible but easier to configure method than the /etc/subuid and /etc/subgid files implemented by the newuidmap and newgidmap tools.

**Comment by cclerget** [comment]
@DrDaveD To avoid error or overlap I think it would be good to add a subcommand managing this in a separate file so we could hide some complexity behind that

**Comment by DrDaveD** [comment]
@cclerget I don't know what you mean, please elaborate.

**Comment by cclerget** [comment]
@DrDaveD Something like :

```
singularity config fakeroot --enable/--disable
singularity config fakeroot --start-uid 65537 (default 65537)
singularity config fakeroot --start-gid 65537 (default 65537)
singularity config fakeroot --add-user [--range (default 65535)] username
singularity config fakeroot --remove-user [--purge] username
```

By default when removing a user the uid/gid allocated range won't be purged to not associate them for another user and would remain associated to the removed user, `--purge` would purge allocated range for reuse

**Comment by DrDaveD** [comment]
I assume you're saying these could only be done by the system admin.  That would work but it seems to be more complicated than necessary.
