### ISSUE TITLE
instance start --cleanenv, what does this do?

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3224]
## Version of Singularity:

3.1-2

### Expected behavior

```
$ singularity instance start --cleanenv ...
$ singularity exec instance:// ... printenv
```

Clean environment!

### Actual behavior

Not clean environment unless I add `--cleanenv` to `singularity exec`

How should the command be behaving? What is the purpose of `--cleanenv` with `instance start`?

**Comment by cclerget** [comment]
@jscook2345 You mean that instance should always start with environment variables cleaned ?

**Comment by GodloveD** [comment]
I think the issue can be simplified to a single question.  What is the purpose of having `--cleanenv` as a flag to `instance start` as in below?
```
$ singularity instance start --cleanenv foo.sif foo
```
^ this does't seem to do anything because the environment seems to be determined when you join the container.  So what is the point?

**Comment by jscook2345** [comment]
@cclerget 

See @GodloveD 's comment. I think that reflects what I was thinking better.

**Comment by cclerget** [comment]
@jscook2345 @GodloveD Ok, here a possible use case:
- run an instance with `--cleanenv` to start an http server
- execute for testing a database server with `DB_HOST=localhost DB_USER=test DB_PASS=test singularity exec instance://httpd db-server`

**Comment by GodloveD** [comment]
Oh wait.  Do you mean that a startscript will respect `instance start --cleanenv`?  I did not check that.

**Comment by cclerget** [comment]
@GodloveD Yes as `instance start` and `shell/exec/run` use the same CLI code

**Comment by jscook2345** [comment]
OK. Thanks for the info @cclerget ! That makes sense to me!
