### ISSUE TITLE
Status stopped when starting an oci container

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3232]
## Version of Singularity:

3.1-2

### Expected behavior

That the status changes to "started" when the `start` command is used.

### Actual behavior

`"status": "stopped"`

### Steps to reproduce behavior

`$ sudo singularity oci start mycontainer` 
`$ sudo singularity oci state mycontainer`
Observe the status variable now

**Comment by cclerget** [comment]
@sushma-98 If you start a basic bundle (by example with `singularity oci mount`) and `config.json` contains :

```
"terminal": false,
"args": [
    "sh"
]
```
shell will exit if it doesn't have a terminal allocated

**Comment by sushma-98** [comment]
Hey @cclerget , So I tried to include "terminal":true in the config file you mentioned, and I still encounter the same issue. Is there any other fix? I'm on Centos7 VM by the way.
