### ISSUE TITLE
Should it say <container_ID>?

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3233]
## Version of Singularity:

3.1-2

### Steps to reproduce behavior

When you do `singularity oci run` :
`Usage:
  singularity [global options...] oci run [run options...] <container_ID>
`
Should it say <Container_ID>? Because we've been just using *name_of_the_container*,
Similar is the case with `singularity help oci create`

**Comment by cclerget** [comment]
@sushma-98 yes it's the terminology
