### ISSUE TITLE
OCI containers do not show up instance list

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3234]
## Version of Singularity:

3.1-2

### Expected behavior

When an OCI container is created - `sudo singularity oci create -b alpine_bundle mycontainer`
it should be listed during the `instance list` command because container instances created in this fashion are still 'known' to Singularity.

### Actual behavior

Does not show up on `instance list`

### Steps to reproduce behavior

`sudo singularity oci create -b alpine_bundle mycontainer`
`sudo singularity instance list`

**Comment by cclerget** [comment]
Well this is expected behaviour and was fixed last week based on Justin's comments in #3103. container created with `singularity instance` commands are not compatible with container `singularity oci` commands and work independently.

**Comment by Flamefire** [comment]
What is the intended command to list oci instances?

**Comment by jscook2345** [comment]
@Flamefire 

The `oci state <container-id>` is meant as a way to list an OCI container. There is no part of the spec for listing all OCI containers.

I have an issue open (https://github.com/sylabs/singularity/issues/3494), but since it is not part of the OCI spec it has not been addressed.

**Comment by Flamefire** [comment]
Agreed, the need is there!

Even if it's not part of the spec, there is no reason not to provide a way to show them in singularity especially as it used to be possible.
