### ISSUE TITLE
Could not "attach" to an OCI container

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3235]
## Version of Singularity:

3.1-2

### Expected behavior

Not sure what exactly is the issue here, but when trying to do `sudo singularity oci attach myoci` after creating and starting the container, it gives `FATAL:   could not attach to myoci: not in running state`. Its unclear how to put an oci container in running state since `oci run` always ends up deleting the container.

### Steps to reproduce behavior

`sudo singularity oci create -b alpine_bundle myoci
`
`sudo singularity oci start myoci
`
`sudo singularity oci attach myoci 
`

**Comment by cclerget** [comment]
I guess it's linked to #3232 probably because container started and exited just after in reference to comment https://github.com/sylabs/singularity/issues/3232#issuecomment-480198302
