### ISSUE TITLE
Building an image with sandbox flag set on root directory

### ISSUE THREAD

**Issue by jchavezlavalle** [apptainer/singularity#3239]
## Version of Singularity:

`SingularityPRO version 3.1-2`

### Actual behavior
Just build a container with the `--sandbox` option set to /:
`$ sudo singularity build --sandbox / library://ubuntu`

### Expected behavior

Open to discussion: Should we prevent this directory from being overlapped? should we ask the user if he wants or not to overlap the whole root directory with this container FS? In any case a message or warning should be expected. As of now, no message is displayed and the container starts to be built over the root directory.

**Comment by GodloveD** [comment]
So there is something screwy going on here.  I just tried to replicate this on Centos7 and I cannot:
```
[dave@ip-172-31-43-187 ~]$ mkdir balh

[dave@ip-172-31-43-187 ~]$ ll
total 0
drwxrwxr-x. 2 dave dave 6 Apr  5 20:42 balh

[dave@ip-172-31-43-187 ~]$ sudo singularity build balh/ bb.def
WARNING: Authentication token file not found : Only pulls of public images will succeed
Build target already exists. Do you want to overwrite? [N/y] n
ERROR:   Stopping build.

[dave@ip-172-31-43-187 ~]$ singularity --version
SingularityPRO version 3.1-2.el7.centos

[dave@ip-172-31-43-187 ~]$ sudo singularity build / bb.def
WARNING: Authentication token file not found : Only pulls of public images will succeed
Build target already exists. Do you want to overwrite? [N/y] n
ERROR:   Stopping build.
```
^ I'm getting a warning telling me to stop, drop, shut em down and open up shop.  Did you see this warning?

**Comment by jchavezlavalle** [comment]
@GodloveD did you try with the `--sandbox` flag? And no I didn't see any warning on RHEL6.7, it started building over everything

**Comment by GodloveD** [comment]
Oh, with sandbox.  Duh.
