### ISSUE TITLE
Fresh --sandbox build contains configuration and files from old container

### ISSUE THREAD

**Issue by iferres** [apptainer/singularity#3240]
Hi, when I try to build a fresh sandbox container I got some strange behaviour:
```
$ su
# singularity build --sandbox foo library://ubuntu
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
INFO:    Creating sandbox directory...
INFO:    Build complete: foo
```
But when I shell into it, some bash errors arise and I find some files from an old build
```
# singularity shell foo/
bash: __vte_prompt_command: command not found
> cd
bash: __vte_prompt_command: command not found
Singularity foo:~> ls
PanDelos  anaconda-ks.cfg
bash: __vte_prompt_command: command not found
```
I think I broke something, but I can't figure out what since I'm pretty new at using Singularity. Some cache from an old build seems to be interacting with the new sandbox build.

```
$ singularity version
3.1.0-1.fc29
```

**Comment by iferres** [comment]
I manage to solve the issue of existing files of old build on new build (`PanDelos` and `anaconda-ks.cfg` in the example above). I had cache both as user and as root, so I had to remove both in order to have a clean build.
I still have a bash problem:
```
# singularity build --sandbox bar library://ubuntu:18.04
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
INFO:    Downloading library image
 26.68 MiB / 26.68 MiB [======================================================] 100.00% 5.86 MiB/s 4s
INFO:    Creating sandbox directory...
INFO:    Build complete: bar
# exit
$ singularity shell --writable bar/
bash: __git_ps1: command not found
Singularity bar:/> ls
bin   dev	   etc	 lib	media  opt   root  sbin		srv  tmp  var
boot  environment  home  lib64	mnt    proc  run   singularity	sys  usr
bash: __git_ps1: command not found
```
but when I add the `--cleanenv` option, it dissapear:
```
$ singularity shell --cleanenv --writable bar/
Singularity bar:/> ls
bin   dev	   etc	 lib	media  opt   root  sbin		srv  tmp  var
boot  environment  home  lib64	mnt    proc  run   singularity	sys  usr
Singularity bar:/>
``` 
I'm not sure if it is the expected behaviour, but it worked for me.

**Comment by ikaneshiro** [comment]
@iferres This looks your `PROMPT_COMMAND` or another bash related envvar is set, telling bash to try to use a `vte` related command. Since your host env is passed to the container, this is causing an issue because `vte` is not installed inside the container.

**Comment by iferres** [comment]
Yes, pretty clear. I wasn't using -`-clearenv` and `--contain` labels when `shell`ing into an image. Thanks anyway.
