### ISSUE TITLE
--writable -> WARNING: no overlay partition found

### ISSUE THREAD

**Issue by alexlenail** [apptainer/singularity#3243]
#### Version of Singularity:
`singularity version 3.1.0-52.g3e3c113`

(The following example is simplified):
```
singularity exec --cleanenv --writable -B /dir image /bin/bash script.sh
```
gives 
```
WARNING: no overlay partition found
/dir/script.sh: No such file or directory
```

I see a [note discouraging using `-B` and `--writable` together in the docs](https://www.sylabs.io/guides/3.1/user-guide/bind_paths_and_mounts.html#a-note-on-using-bind-with-the-writable-flag). 

I'm using `--writable` in the first place, because otherwise, script.sh runs but complains that it can't write (`OSError: [Errno 30] Read-only file system`).  

The [description of `--writable`](https://www.sylabs.io/guides/3.1/user-guide/cli/singularity_exec.html?highlight=writable) is fairly brief. 

```
-w, --writable               by default all Singularity containers are available as read only. This option makes the file system accessible as read/write.
```

What does `--writable` really do, and why am I getting these errors?

**Comment by jmstover** [comment]
A SIF image is a squashfs filesystem which makes it read-only by default.

`--writable` is useful if you have a old ext3 image, or are using a sandbox image. The issue with `--writable` and `-B` comes from the fact that when you use `--writable` we don't use overlayfs to create necessary bind points. In other words if you use `-B /dir`, then `/dir` must exist in the image for the mount point. It won't automatically be created.

If `script.sh` only needs to write a small amount, you can use `--writable-tmpfs` ... this option will create a small writable overlay on top of the image structure. I think it's around 1MB in size.

**Comment by alexlenail** [comment]
@jmstover thanks for the quick response. What if `script.sh` needs to write a lot?

**Comment by jmstover** [comment]
Then generally, you'll want to bind mount in a directory, or use `/tmp`, or a location in `$HOME` (both $HOME and /tmp are bind mounted by default).

So, assuming that `script.sh` writes to `/dir` ... you can do something like:

```
singularity exec --cleanenv -B $HOME/script_out:/dir myimage.sif bash script.sh
```

That would mount `$HOME/script_out` to the `/dir` location in the image, and that location would be writable.

**Comment by alexlenail** [comment]
@jmstover Thanks for fielding these questions. I'm still just slightly confused: Can I do
```
singularity exec --cleanenv -B /dir:/dir myimage.sif bash script.sh
```
(without `/dir` existing in the image beforehand) and have the container write to `/dir` which persists in `/dir` outside the container? That's the behavior I would expect from docker.

**Comment by jmstover** [comment]
As written yes.

If the source/destination is the same you can shorten the bind option to:  `-B /dir`

**Comment by alexlenail** [comment]
Thanks @jmstover . In that case I might just ask the docs be elaborated slightly to shed a little more light on the fact that the container can write to mounted directories without the `--writable` flag.

**Comment by tashrifbillah** [comment]
> --writable-tmpfs ... this option will create a small writable overlay on top of the image structure. I think it's around 1MB in size.

Hi @jmstover , I realized the small size is true for non-root users. However, a root user is able to write many MBs. Do you know the reason behind this difference? Is there a way to adjust that for the former?

(non-root)
```
Singularity> df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                   16M   12K   16M   1% /
tmpfs                     63G     0   63G   0% /dev/shm
...
tmpfs                     16M   12K   16M   1% /etc/group
```
The last line is probably kicking in!

(root)
```
Singularity> df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                   63G  2.3G   61G   4% /
tmpfs                     63G     0   63G   0% /dev/shm
...
tmpfs                     63G  2.3G   61G   4% /etc/resolv.conf

```
