### ISSUE TITLE
Sign flags `-g` and `-i` accepting numbers that doesn't exist in SIF file

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3246]
## Version of Singularity:

3.1-2

### Expected behavior

The flags `-g` and `-i` should give an error when signing an image with IDs not in SIF file. 

### Actual behavior

`-i` accepts any number >=0,
`-g` accepts 0 and the numbers in SIF file

### Steps to reproduce behavior

`$ siftool list alpine_latest.sif`

You will see ID and Group in first two columns, 

Try to sign with numbers not in the column, 
`$ singularity sign -i 9 alpine_latest.sif`

**Comment by WestleyK** [comment]
This seems to be fixed in master, maybe there should be E2E tests to ensure this wont be a issue in the future.

**Comment by WestleyK** [comment]
Closing as this is not a issue anymore.
