### ISSUE TITLE
singularity build <sif> library URI should fail gracefully for non-root use

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3247]
## Version of Singularity:

3.1-2.el7.centos

### Expected behavior

$ singularity build cl.sif library://busybox:latest
WARNING: Authentication token file not found : Only pulls of public images will succeed
<success! the sif file exists>

### Actual behavior

On CentOS7
```
$ singularity build cl.sif library://centos:latest
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
INFO:    Downloading library image
 69.58 MiB / 69.58 MiB [=============================================================================================================================] 100.00% 63.15 MiB/s 1s
ERROR:   unpackSIF Failed: While copying partition data to bundle: no loop devices available
FATAL:   While performing build: packer failed to pack: While copying partition data to bundle: no loop devices available
```

On RHEL6.10
```
$ singularity build cl.sif library://centos
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
INFO:    Downloading library image
 69.58 MiB / 69.58 MiB [=============================================================================================================================] 100.00% 59.69 MiB/s 1s
ERROR:   unpackSIF Failed: While copying partition data to bundle: permission denied
FATAL:   While performing build: packer failed to pack: While copying partition data to bundle: permission denied
```

SLES11.4 also fails similar to CentOS7.

### Steps to reproduce behavior

@ikaneshiro and I discussed this. Currently `root` privileges are required for this operation, but it should fail a bit more gracefully I think.

**Comment by jmstover** [comment]
In my opinion this should *not* fail. It's effectively the same thing as:
```
singularity pull cl.sif library://centos:latest
```
Just because we're using `build` doesn't change the fact that the only thing we need to do with a `library://` URI is download it.

**Comment by ikaneshiro** [comment]
@jmstover we are doing something different than just pulling the image though. We are extracting the file system and updating metadata(e.g. build tags). This should have been implemented in a way that doesn't require priv to mount the image file system, but was not. I recently fixed this so that it doesn't require priv in master now so that will be in 3.2. What we want to do for 3.1.x is up for discussion.

**Comment by jmstover** [comment]
@ikaneshiro ... In what way are you updating metadata? What is the functional difference in the image between:

```
singularity exec library://centos:latest cat /etc/os-release
```
And:
```
singularity build cl.sif library://centos:latest
singularity exec cl.sif cat /etc/os-release
```

From doing this in a Def file, I can understand there being a difference as you're using an image as a _base_, and there's possible differences that will happen between that base and the end result (i.e. the `%post` section).

But referenced from the CLI? There's no metadata to update except going:  "Ohh... well, we'll make a new build time."   Nothing else is different about the image.

**Comment by ikaneshiro** [comment]
@jmstover mainly updating build time and build source tags. If there were updates to the action scripts, then those would be changed too, though they are bound in at run time so it's a moot point. There shouldn't be a functional difference in that example or in any build directly from a SIF image.

**Comment by WestleyK** [comment]
This seems outdated. You are now able to build a sif, from a sif without root privilege.

_Re-open if necessary._
