### ISSUE TITLE
warning: underlay of /usr/bin/nvidia-smi required more than 50 bind mounts

### ISSUE THREAD

**Issue by liuhoward** [apptainer/singularity#3250]
Hi,
I created a singularity image including cuda, tensorflow etc.
but when I run it PBS script or using shell like singularity --nv shell xxx.img
it always show a warning:
warning: underlay of /usr/bin/nvidia-smi required more than 50 bind mounts

I modified tensorflow dockerfile from [tensorflow github](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile), here is my [dockerfile](https://github.com/liuhoward/tensorflow_container/blob/master/gpu.Dockerfile), then I create a [Singularity recipe](https://github.com/liuhoward/tensorflow_container/blob/master/Singularity_tensorflow_gpu_py3) to pull my docker image from hub.docker to Singularity-hub, then I pull down singularity img to my local server using  Singularity 2.6.1-dist

## Version of Singularity:

my local server uses  Singularity 2.6.1-dist to pull img, I am not sure about Singularity version in Singularity-hub.com

### Expected behavior

no such warning

### Actual behavior

it always show a warning:
warning: underlay of /usr/bin/nvidia-smi required more than 50 bind mounts

**Comment by cclerget** [comment]
Hi @liuhoward , the underlay feature for v2 is not maintained by Sylabs but by the original author of this feature @DrDaveD in the version that he maintained on epel. Between you can use `-s` to discard warning message `singularity -s exec`

**Comment by DrDaveD** [comment]
v3 has the same warning, however.

The warning is to alert users that using underlay to replace a small subset of a big directory does have a cost to it.

**Comment by liuhoward** [comment]
Hi @DrDaveD, is it possible to avoid this? I do not understand why nvidia-smi would cause this warning.

**Comment by DrDaveD** [comment]
The reason is that /usr/bin has more than 50 files in it.  By replacing one of the files, underlay creates a scratch directory for the container and has to do a bind mount for all of the other files from the image into the scratch directory.  It's probably nothing to worry about, lots of people have done it.  You could ignore it with the -s option. 

If you want to eliminate the many bind mounts, perhaps nvidia-smi could be put into some other directory like /usr/local/bin, as long as /usr/local/bin is always in the PATH and everything that uses it looks in the PATH and doesn't explicitly try to run /usr/bin/nvidia-smi.

**Comment by liuhoward** [comment]
thank you very much!

**Comment by liuhoward** [comment]
I have two similary singularity images, both have /usr/bin/nvidia-smi, but one has no warning (445 files in /usr/bin/), another one has this warning (440 files in /usr/bin/)

**Comment by DrDaveD** [comment]
Oh, I forgot to mention another way around it is to put in your container a file at /usr/bin/nvidia-smi.  It could even be empty.  Does one of your containers already have that?

**Comment by liuhoward** [comment]
no, both images have real nvidia-smi in /usr/bin/, both are 527K, when I run 'which nvidia-smi', both shows /usr/bin/nvidia-smi

**Comment by liuhoward** [comment]
![2019-04-09_14-40](https://user-images.githubusercontent.com/4758314/55837344-f535fa00-5ad5-11e9-86d1-69ec1137e65e.png)

in tf_1.12_201811.simg, no warning
in tf1.12_201903.img, warning: underlay....

**Comment by DrDaveD** [comment]
I am talking about a file in the container image itself, without doing any bind mounts.  How about if you run it without --nv, is there a /usr/bin/nvidia-smi then?

**Comment by liuhoward** [comment]
you are right, 
tf_1.12_201811.simg with no warning has an empty nvidia-smi
tf1.12_201903.img with warning has no nvidia-smi file
thank you!!

**Comment by liuhoward** [comment]
I've figured it out. please close it. thanks!

**Comment by jscook2345** [comment]
Glad it worked out @liuhoward !
