### ISSUE TITLE
How to run singularity container without root

### ISSUE THREAD

**Issue by renganxu** [apptainer/singularity#3264]
## Version of Singularity:

3.1.0-rc2

### Expected behavior

$ singularity exec test.sif hostname
$ node001

### Actual behavior
$ singularity exec test.sif hostname
$ ERROR  : Failed to set effective UID to 0

$ singularity -d exec test.sif hostname
VERBOSE [U=1025,P=449626]  print()                       Set messagelevel to: 5
DEBUG   [U=1025,P=449626]  init()                        PIPE_EXEC_FD value: 7
VERBOSE [U=1025,P=449626]  init()                        Container runtime
VERBOSE [U=1025,P=449626]  is_suid()                     Check if we are running as setuid
DEBUG   [U=1025,P=449626]  init()                        Read json configuration from pipe
DEBUG   [U=1025,P=449626]  init()                        Set child signal mask
DEBUG   [U=1025,P=449626]  init()                        Wait completion of stage1
DEBUG   [U=1025,P=449638]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1025,P=449638]  init()                        Spawn stage 1
VERBOSE [U=1025,P=449638]  startup()                     Execute stage 1
DEBUG   [U=1025,P=449638]  Stage()                       Entering stage 1
DEBUG   [U=1025,P=449638]  Init()                        Entering image format intializer
DEBUG   [U=1025,P=449638]  Init()                        Check for image format sif
DEBUG   [U=1025,P=449626]  init()                        Create socketpair for master communication channel
DEBUG   [U=1025,P=449626]  cleanup_fd()                  Check file descriptor /proc/self/fd/3 pointing to /home/rengan/test.sif
DEBUG   [U=1025,P=449626]  cleanup_fd()                  Check file descriptor /proc/self/fd/4 pointing to anon_inode:[eventpoll]
DEBUG   [U=1025,P=449626]  cleanup_fd()                  Closing /proc/self/fd/4
VERBOSE [U=1025,P=449626]  priv_escalate()               Get root privileges
ERROR   [U=1025,P=449626]  priv_escalate()               Failed to set effective UID to 0

### Steps to reproduce behavior

I created the image test.sif with root on one cluster, and then move the image to another cluster. But I do not have root access in another cluster, and then I have the above error when running the container. The singularity version is the same on both cluster.

I searched other issues, and found it has something to do with the suid (https://github.com/sylabs/singularity/issues/2911). The singularity.conf file already set " allow setuid = yes". That issue post mentioned "starter-suid must be installed with set-uid bit set. " but didn't say how. 
-rwxr-xr-x 1 root root 14564344 Feb 15 22:40 starter
-rwxr-xr-x 1 root root 14564344 Feb 15 22:40 starter-suid

It seems the permission for starter-suid should be:
-rwsr-xr-x 1 root root 14564344 Feb 15 22:40 starter-suid

Is this the reason and how to solve it? Thanks.

**Comment by jmstover** [comment]
Yes, `starter-suid` needs to have the SUID bit set. `chmod 4755 starter-suid`  ... `starter-suid` should be installed with the correct permissions. Is singularity installed on a NFS share, that is mounted with the `nosuid` option?

**Comment by renganxu** [comment]
Yes singularity was installed on NFS share, but was not mounted with nosuid option. Do we have to add this option?  If yes, I can ask our admin to add it.

**Comment by jmstover** [comment]
No, you cannot have the nosuid mount option. That causes the behavior you're seeing where singularity is installed, but the permissions being seen are wrong.

**Comment by DrDaveD** [comment]
Using a .sif file always requires root access on the machine, or at least an installation of singularity that was done as root so starter-suid is the permissions that you point out.  The make install has to be done as the root user, then the permissions will be correct.

An alternative on CentOS 7 is if the system administrator enables unprivileged user namespaces.  Then you can run with sandboxes (unpacked images), but still not .sif files.

There are instructions for enabling unprivileged user namespaces on CentOS 7 on [this page](https://opensciencegrid.org/docs/worker-node/install-singularity/).

**Comment by renganxu** [comment]
@jmstover @DrDaveD Thanks very much for the suggestions. After the admin ran "chmod 4755 starter-suid", I can run the container successfully now. :)

**Comment by renganxu** [comment]
Hi @jmstover @DrDaveD , I found the solution works for .sif file, but not for sandboxes.
