### ISSUE TITLE
singularity keys remove does not remove private key

### ISSUE THREAD

**Issue by mem** [apptainer/singularity#3277]
## Version of Singularity: 

d95ecd3c41915a988f615e33d2e5fbeeabdb4522

### Expected behavior

`singularity keys remove xxx` removes private keys or there's a `singularity keys remove --secret xxx`

### Actual behavior

`singularity keys remove xxx` removes only the public key.

### Steps to reproduce behavior

```
$ builddir/singularity keys list
Public key listing (/home/mem/.singularity/sypgp/pgp-public):

$ builddir/singularity keys newpair
WARNING: No default remote in use, falling back to: https://keys.sylabs.io
Enter your name (e.g., John Doe) : xxx
Enter your email address (e.g., john.doe@example.com) : marcelo@sylabs.io
Enter optional comment (e.g., development keys) :
Enter a passphrase :
Retype your passphrase :
Generating Entity and OpenPGP Key Pair...done
Would you like to push it to the keystore? [Y,n] : n
Done.

$ builddir/singularity keys list
Public key listing (/home/mem/.singularity/sypgp/pgp-public):

0) U: xxx () <marcelo@sylabs.io>
   C: 2019-04-10 15:37:36 -0600 CST
   F: 35D7D8E9F80DA2FB9EBD6A6D0F2D4830479772E2
   L: 4096
   --------

$ builddir/singularity keys remove 35D7D8E9F80DA2FB9EBD6A6D0F2D4830479772E2

$ builddir/singularity keys list
Public key listing (/home/mem/.singularity/sypgp/pgp-public):

$ builddir/singularity keys list --secret
Private key listing (/home/mem/.singularity/sypgp/pgp-secret):

0) U: xxx () <marcelo@sylabs.io>
   C: 2019-04-10 15:37:36 -0600 CST
   F: 35D7D8E9F80DA2FB9EBD6A6D0F2D4830479772E2
   L: 4096
   --------

$ builddir/singularity keys remove --secret 35D7D8E9F80DA2FB9EBD6A6D0F2D4830479772E2
Invalid flag "--secret" for command "remove".

Options:

  -h, --help   help for remove

Run 'singularity key remove --help' for more detailed usage information.
```

**Comment by WestleyK** [comment]
Yes, I'm aware of this and it is on my todo list. I'm on it! :+1:

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@mem @WestleyK Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Pending issues from the old repo are copied to the new repo (https://github.com/apptainer/apptainer/issues/1388) and cleaned from the old retired repo.
