### ISSUE TITLE
confusing messaging when removing a remote

### ISSUE THREAD

**Issue by mem** [apptainer/singularity#3278]
## Version of Singularity:

d95ecd3c41915a988f615e33d2e5fbeeabdb4522

### Expected behavior

`singularity remote remove xxx` either removes `xxx` or tells me where it's looking for it and why it's not found.

### Actual behavior

`singularity remote remove xxx` listed in the output of `singularity remote list` does not exist.

### Steps to reproduce behavior

```
$ builddir/singularity remote list
NAME           URI              SYS
[SylabsCloud]  cloud.sylabs.io  YES

$ builddir/singularity remote remove SylabsCloud
FATAL:   SylabsCloud is not a remote

$ builddir/singularity remote remove '[SylabsCloud]'
FATAL:   [SylabsCloud] is not a remote
```

Note how it tells me that `SylabsCloud` is not a remote, even if it's present in the output of `list`.

The reason why it's saying it's not a remote is because `SylabsCloud` is found in the system's `remote.yaml` file, not in my own one. If I add `-g` to the command, it does find it.

The error message should at least say that the remote is not found in the user's configuration (vs the global one).

**Comment by dtrudg** [comment]
This ended up fixed via Cedric's recent remote / keyserver etc. work:

```
3fc8612ee9 (Cedric Clerget  2020-08-28 13:00:55 +0200 201)      } else if r.System && !c.system {
3fc8612ee9 (Cedric Clerget  2020-08-28 13:00:55 +0200 202)              return fmt.Errorf("%s is global and can't be removed", name)
```
