### ISSUE TITLE
libsingularity*.so -- public or private?  loose naming

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#328]
While preparing 2.2 package for Debian (thanks Mehdi Dogguy for help), I saw that libsingularity1 provides many functions which bare generic names:
```shell
$> grep -v '^ *_*singularity_' debian/libsingularity1.symbols 
libsingularity.so.1 libsingularity1 #MINVER#
 _unlink@Base 2.2
 action_exec_do@Base 2.2
 action_exec_init@Base 2.2
 action_run_do@Base 2.2
 action_run_init@Base 2.2
 action_shell_do@Base 2.2
...
 init@Base 2.2
 int2str@Base 2.2
 intlen@Base 2.2
 is_blk@Base 2.2
...
```
so I wondered:

- if library is intended to be "public" for use by 3rd-party apps/libraries, then such loose naming might cause problems possibly overloading functionality provided by other/core libraries, and either those acquire also some unique prefix to disambiguate or were not exposed in the library
- if library is for internal use, then should be installed somewhere under e.g. `/usr/lib/singularity/` ie away from the public libraries namespace?

or am I overthinking it? ;)

**Comment by bbockelm** [comment]
:/ I thought that had already been done?

Indeed, this is an internal library with NO public APIs.  `/usr/lib/singularity` sounds good.

**Comment by yarikoptic** [comment]
ah -- probably it was done already initially 2.2-40-ged88b30 (ed88b30945ca4d6375941be2133f86edf4a1d63c) (thus after 2.2, which I was talking about).  
- So I guess for now we will just manually move the library away and chrpath binaries or smth like that 
- are you on a verge of a new release btw? ;)  then may be we could just skip 2.2 altogether

**Comment by bbockelm** [comment]
@gmkurtzer can probably update us on the distance to the new release.  I feel like it's still a month or so out (tons of great refactoring occurring around the image generation).

**Comment by bauerm97** [comment]
I think @gmkurtzer can also speak better for the direction we are wanting to go in regards to public vs. internal library. [Here](https://github.com/singularityware/singularity/commit/ed88b30945ca4d6375941be2133f86edf4a1d63c) was a commit pushed that creates a separate internal and external library file. Currently it looks like they are identical to one another. Maybe Greg can comment on if we want to let external apps access a library from us, and in that case what functions should and should not be outward facing. As it stands, I believe that all functions named singularity_* would fit the bill for functions that we could let 3rd party apps call on, however it's better that Greg decides this.

EDIT: I see you've mentioned this commit, my bad for not reading thoroughly. @bbockelm it looks like this was your implementation, do you know if there are plans to make the two libraries different and actually create a "proper" external library?

**Comment by bbockelm** [comment]
Yeah - that was just for linking tricks so the SLURM plugin could be shipped without relying on singularity itself (meaning no `setuid` pieces shipped along with the SLURM plugin).  In the end, the output of `make install` still should only be the one internal library.

**Comment by gmkurtzer** [comment]
@yarikoptic I just wanted to confirm, is simply moving the library to $(libdir)/singularity a reasonable solution? If so please see [master e7dceef].

**Comment by gmkurtzer** [comment]
This should be done now. Closing old issue.
