### ISSUE TITLE
Cannot pull by commit or image hash with v3

### ISSUE THREAD

**Issue by kyleam** [apptainer/singularity#3287]
With version 2, it was possible to pull an image by the commit or the md5sum of the image file (as described [here]):

```
$ singularity --version
2.6.1-dist
$ singularity pull --name by-commit.simg shub://vsoch/hello-world@42e1f04ed80217895f8c960bdde6bef4d34fab59
Progress |===================================| 100.0% 
Done. Container is at: /tmp/nm-BCiEn3t/by-commit.simg
$ singularity pull --name by-image-hash.simg shub://vsoch/hello-world@ed9755a0871f04db3e14971bec56a33f
Progress |===================================| 100.0% 
Done. Container is at: /tmp/nm-BCiEn3t/by-image-hash.simg
```

When I try the same commands with version 3, it fails:

```
$ singularity --version
singularity version 3.0.3+ds
$ singularity pull --name by-commit.simg shub://vsoch/hello-world@42e1f04ed80217895f8c960bdde6bef4d34fab59
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Failed to get manifest from Shub: The requested manifest was not found in singularity hub
$ singularity pull --name by-image-hash.simg shub://vsoch/hello-world@ed9755a0871f04db3e14971bec56a33f
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Failed to get manifest from Shub: The requested manifest was not found in singularity hub
```

I didn't spot any mention of this change in the CHANGELOG.  Is pulling by a commit or image hash still supported?

Thanks in advance.

[here]: https://github.com/singularityhub/singularityhub.github.io/wiki/Deploy#order-of-operations

**Comment by yarikoptic** [comment]
Some action/feedback would be appreciated!

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@kyleam Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by yarikoptic** [comment]
looking at the logs from what singularity-hub sees, I think `@whatever` is just ignored in 2.6.1 and thus server sees `image:latest` and thus "worked". in 3.x it would send full url with `@whatever` . current singularity server "shim" doesn't handle those with `@` AFAIK and only `:`.

**Comment by kmuriki** [comment]
Old Singularity repo issues are now closed. If this is still a critical issue please open a new one in Apptainer repo.
