### ISSUE TITLE
singularity exec command pipeline to less(1) hangs or is suspended

### ISSUE THREAD

**Issue by mgjf** [apptainer/singularity#3294]
### Version of Singularity:

Present at least in the following V3.x Singularity versions
3.0, 3.1.1, 3.2.0-rc1

### Expected behavior

`singularity exec cmd | less`
should allow you to browse the output of any command `cmd`
This worked fine with all Singularity 2.x versions

### Actual behavior

depending on the amount of output generated by `cmd`, the pipeline is immediately suspended (small amount of output) or hangs completely (large amount of output).

### Steps to reproduce behavior

Install Singularity 3.0, 3.1.1, or 3.2.0-rc1 on host exactly as described in documentation.
For the host OS, I used a pristine Ubuntu 18.04LTS in a Virtualbox VM with all updates installed.
```
 $ singularity build ubuntu.sif docker://ubuntu:latest
```
Then run the container, piping its output to less(1). When output consists just of a few lines, the pipeline is immediately suspended:
```
 $  singularity exec ubuntu.sif ls -l / | less
[1]+  Stopped                 singularity exec ubuntu.sif ls -l / | less  
```
Whereas with more output, the pipeline hangs completely
```
 $ singularity exec ubuntu.sif ls -lR / | less
```
workaround: connect container's stdin do /dev/null
`</dev/null singularity exec ubuntu.sif ls -lR / | less`

**Comment by DrDaveD** [comment]
I see the same behavior on CentOS 7, including the workaround, in 3.2.0-rc1.
