### ISSUE TITLE
bootstrap fails on RHEL

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#33]
Do you want me to try to fix this?  If so, should it always look for the corresponding CentOS?  (I think that won't generally have quite the same package set available, and definitely not the same as SL.)

```
$ sudo singularity bootstrap /tmp/c6.img examples/centos.def 
Loaded plugins: auto-update-debuginfo, changelog, etckeeper, fastestmirror,
              : filter-data, merge-conf, post-transaction-actions, priorities,
              : product-id, protectbase, security, subscription-manager, verify,
              : versionlock
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Setting up Install Process
http://mirror.centos.org/centos-6Server/6Server/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

Error: Cannot retrieve repository metadata (repomd.xml) for repository: os-base. Please verify its path and try again
```

**Comment by gmkurtzer** [comment]
Oh that is very interesting. Are you running this from RHEL proper?

Yes if you can fix that would be fantastic. I don't have access to any RHEL systems. 

Thanks!

**Comment by loveshack** [comment]
You wrote: 

> Oh that is very interesting. Are you running this from RHEL proper?

Yes.

  $ lsb_release -d
  Description:  Red Hat Enterprise Linux Server release 6.7 (Santiago)

but the compute nodes are

  Description:  Scientific Linux release 6.7 (Carbon)

> Yes if you can fix that would be fantastic. I don't have access to any
> RHEL systems.

Probably not necessary, but for what it's worth, you can get a vagrant
box for some version of rhel6 (which presumably isn't updatable as such).

**Comment by loveshack** [comment]
Looking at it, shouldn't there at least be entries for updates, rather than just the base distribution?

Maybe the repos which are enabled in the boostrap environment should be copied, although they might not work elsewhere (especially from RHEL/SLES moved elsewhere).  That suggests being able to specify a list in the configuration somehow.

Examples of things I'd expect to include are EPEL and RH software collections (rebuilt by SL, and possibly CentOS).

**Comment by gmkurtzer** [comment]
What do you mean "entries for updates"? By default, one could point RELEASE at 5, 6 or 7 and always get the current dot release. 

Do you have an idea of how to add the EPEL repo? I wouldn't want to do it automatically, but as long as it can be a install flag (possibly InstallFile /etc/yum.repos.d/\* and copy from the host?)

**Comment by loveshack** [comment]
"Gregory M. Kurtzer" notifications@github.com writes:

> What do you mean "entries for updates"? By default, one could point
> RELEASE at 5, 6 or 7 and always get the current dot release.

The CentOS-Base.repo file I have contains entries for "base" and
"updates".  The compute node sl6x.repo has "sl6x", "sl6x-security", and
"sl6x-fastbugs" enabled.

> Do you have an idea of how to add the EPEL repo? I wouldn't want to do
> it automatically,

Why not?  It's where most of the useful stuff is.

> but as long as it can be a install flag (possibly
> InstallFile /etc/yum.repos.d/\* and copy from the host?)

Yes, maybe.  However, if the host is, say, our RHEL login node, the
result won't be able to use the repos on SL systems like our compute
nodes.

**Comment by gmkurtzer** [comment]
What provides those yum repo files? I figured it was _-release_.rpm and that should be getting installed, if not, that should be fixed.

As far as EPEL, I agree most useful stuff is but I don't think it should be included or enabled by default. Maybe make that as part of the default Centos definition but commented out so we can demonstrate how to do it without making it default.

**Comment by loveshack** [comment]
"Gregory M. Kurtzer" notifications@github.com writes:

> What provides those yum repo files? I figured it was _-release_.rpm
> and that should be getting installed, if not, that should be fixed.

I'm confused what's happening, then, and should update the source to
check.  I was trying to fix the generation of a yum.conf file pointing
to a base repo.

To answer the question, on RHEL:

  # rpm -qf /etc/yum.repos.d/redhat.repo 
  subscription-manager-1.16.8-8.el6.x86_64

and on SL:

  # osrpm -qf /etc/yum.repos.d/sl6x.repo
  yum-conf-sl6x-1-2.noarch

[osrpm runs rpm in the stateless image.]

> As far as EPEL, I agree most useful stuff is but I don't think it
> should be included or enabled by default.

OK, but for what it's worth, it's included in the relevant Fedora build
roots (called, e.g. epel-6-x86_64).

**Comment by gmkurtzer** [comment]
Let me know if there is anything I can answer to help, but right now I'm not sure what has confused you. There is one bit that might help. For the bootstrap, I generate an initial yum.conf in root's home directory this way when yum and release packages drop their own configs, it doesn't conflict or get overridden. This does and up with an issue for subsequent yum calls... Which yum configs do we use? ... That is the question!

**Comment by loveshack** [comment]
I think I misunderstood this, looking too hurriedly.  The bootstrap will
work OK if you amend the centos example, at least, to use a specified
target version rather than one deduced from the host.  That will work
between at least el6/epel7 hosts and targets.

However you end up with distribution base packages in the container,
i.e. without any updates, which I think it should get.

Note that the implementation probably needs to be specialized to use dnf
rather than yum for recent fedora.  I'll look at that, but it presumably
constrains the host.

Also it might be worth noting that debian won't bootstrap in el6/epel7
hosts because they lack apt (which is in fedora) even though they have
debootstrap.  I can look at getting apt into epel.

**Comment by gmkurtzer** [comment]
Can you elaborate on what distribution base packages end up in the container?

As much as I love the idea of dnf (hopefully it will all end up in C) obsoleting YUM, I'm still sentimentally attached to YUM. I worked with Seth early on as I wanted out of the RPM wrapper world (I wrote a simple tool called GRAB back in the day) and he wanted in... and to learn Python.

Apt shouldn't be required on the host. In linux_build_debian.smod I call chroot into the newly created base file system that debootstrap created (and thus it should have apt-get within it, not on the host. On a quick check, I see I'm looking for apt-get on the host even though it is not necessary. I'm removing that now, let me know if works.

Thanks!

**Comment by moskalenko** [comment]
Tried a RHEL7 bootstrap with yesterday's singularity/2.0 snapshot. It almost finished:

...
Complete!
Loaded plugins: langpacks, product-id, rhnplugin, search-disabled-repos, subscription-manager
Cleaning repos: atomic epel google-chrome rhel-x86_64-server-7 rhel-x86_64-server-7-rhscl-1 rhel-x86_64-server-extras-7 rhel-x86_64-server-optional-7
              : rhel-x86_64-server-rh-common-7 virtualbox winswitch
Cleaning up everything
/usr/local/libexec/singularity/mods/linux_build.smod: line 180: echo: write error: Invalid argument

**Comment by moskalenko** [comment]
linux_build.smod line 180:

```
echo "singularity / rootfs rw 0 0" > "$SINGULARITY_BUILD_ROOT/etc/mtab"
```

**Comment by gmkurtzer** [comment]
I was just looking at that... Very weird. What is the build host type you
used?

Can you also show me your bootstrap definition?

**Comment by moskalenko** [comment]
It's an up-to-date RHEL7 server machine

$ cat rhel7.def 

# Use shell lingo to determine version and repository location

RELEASE=`rpm -qf /etc/redhat-release  --qf '%{VERSION}\n'`

DistType "redhat"
MirrorURL "http://mirror.centos.org/centos-${RELEASE}/${RELEASE}/os/\$basearch/"

MirrorURL "http://winswitch.org/dists/CentOS/7Server/x86_64/"

Setup
Bootstrap

InstallPkgs xpra

Cleanup

**Comment by gmkurtzer** [comment]
I am trying to replicate the build now. Are you building it on Centos7?

**Comment by gmkurtzer** [comment]
Oh, interesting.. I am getting an error in that the second MirrorURL you
supplied does not have a full Centos distribution. that is an interesting
feature though, to supply multiple mirrors for packages and have YUM
configure all that are listed (but at present, it only supports one
MirrorURL with the last one taking precedent).

I could fairly easy make it to support such syntax as:

DistType "redhat"
MirrorURL  "
http://mirror.centos.org/centos-${RELEASE}/${RELEASE}/os/\$basearch/"
Setup
Bootstrap
MirrorURL "http://winswitch.org/dists/CentOS/7Server/x86_64/"
InstallPkgs xpra
Cleanup

But at the moment, it won't work...

If you remove the second MirrorURL line, do you still get the echo error? I
can not seem to replicate it.

**Comment by moskalenko** [comment]
Another error when trying to execute a command from the image for the first time:

singularity exec /foo/images/xpra-rhel7.img xpra --version
ERROR: Could not create directory /bar/singularity/20160519/var: Permission denied
ERROR: Could not create directory /bar/singularity/20160519/var/singularity: No such file or directory
ERROR: Could not create directory /bar/singularity/20160519/var/singularity/mnt: No such file or directory
ABORT: Could not create directory /bar/singularity/20160519/var/singularity/mnt: No such file or directory

We have root-squashed shared filesystems all over the place, so suexec won't do anything.

How does this work in a shared environment?

**Comment by gmkurtzer** [comment]
How did you compile and install Singularity? The --prefix path should be pointing to a local directory on the compute node. Hrmm... I might be able to work around that actually if that is not an option.

**Comment by moskalenko** [comment]
That's the problem. Our nodes are diskless, so we have to use networked filesystems. I needed to be able to perhaps 'unpack' or 'install' an image, so hundreds or even thousands of concurrent jobs could run commands from it without any write access to the singularity installation directory tree or the image directory tree. They can use cwd or tempdir for some operations as needed.

**Comment by gmkurtzer** [comment]
We run nodes diskless too, but Singularity only writes a few small text files and uses the localstatedir (/var) for mounting the container. But, with that said, I can move that to the session directory which will always exist in /tmp. Is your /tmp local?

I just committed a change to put the image mount into the session directory. Give the master branch a try and see if that helps. Or you can move the --localstatedir=/var in your ./configure.

Let me know! Thanks!

**Comment by loveshack** [comment]
You wrote: 

> Can you elaborate on what distribution base packages end up in the container?

Ones from the repo you specify.  In the example, that excludes updates
unless you explicitly do an update or dependencies are implicitly
updated if you install other packages.  

> As much as I love the idea of dnf (hopefully it will all end up in C)
> obsoleting YUM, I'm still sentimentally attached to YUM. I worked with
> Seth early on as I wanted out of the RPM wrapper world (I wrote a
> simple tool called GRAB back in the day) and he wanted in... and to
> learn Python.

As I understand it, you should use dnf on fedora, apart from the noise
using yum (but you want to avoid any version installed on centos).  It
apparently can give different results.

> Apt shouldn't be required on the host. In linux_build_debian.smod I
> call chroot into the newly created base file system that debootstrap
> created (and thus it should have apt-get within it, not on the
> host. On a quick check, I see I'm looking for apt-get on the host even
> though it is not necessary. I'm removing that now, let me know if
> works.

OK, I'll test at some stage.

**Comment by gmkurtzer** [comment]
On Sun, May 22, 2016 at 3:13 PM, Dave Love notifications@github.com wrote:

> > Can you elaborate on what distribution base packages end up in the
> > container?
> 
> Ones from the repo you specify. In the example, that excludes updates
> unless you explicitly do an update or dependencies are implicitly
> updated if you install other packages.

Ahh, I see what you mean but I think it is valuable to bootstrap from a
release version, and then upgrade from there if desired. I also agree
though that it would be valuable to be able to bootstrap the most recent
release. Hopefully this won't require multiple Mirrors... But if it does, I
think that should be doable. I'd have to move some of the YUM config code
around so the YUM components get appended with every call to MirrorURL to
include that repo. As I see it, this would then include the update repo as
ell (or any repo of your choosing) during install.

Would that address your desire?

> > As much as I love the idea of dnf (hopefully it will all end up in C)
> > obsoleting YUM, I'm still sentimentally attached to YUM. I worked with
> > Seth early on as I wanted out of the RPM wrapper world (I wrote a
> > simple tool called GRAB back in the day) and he wanted in... and to
> > learn Python.
> 
> As I understand it, you should use dnf on fedora, apart from the noise
> using yum (but you want to avoid any version installed on centos). It
> apparently can give different results.

Different results?! That sounds scary... I wonder which decision would be
the source of truth.

> > Apt shouldn't be required on the host. In linux_build_debian.smod I
> > call chroot into the newly created base file system that debootstrap
> > created (and thus it should have apt-get within it, not on the
> > host. On a quick check, I see I'm looking for apt-get on the host even
> > though it is not necessary. I'm removing that now, let me know if
> > works.
> 
> OK, I'll test at some stage.

Thanks! I will too! Let's race.. ;)

## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by moskalenko** [comment]
$ singularity exec xpra-rhel7.img xpra start 3232 --start-child=beauti
$ singularity execxpra-rhel7.img xpra list
xpra initialization error:
 No xpra sessions found

$ beauti
Picked up _JAVA_OPTIONS: -Xms128m -Xmx1024m
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:181)
        at dr.app.beauti.BeautiApp.main(Unknown Source)

No cookie, yet.

**Comment by gmkurtzer** [comment]
Ahh, this maybe in part a usage error as well. Every time you exec/shell/run it will create a new series of namespaces. This is because there is no state between them (e.g. no runtime daemon). I may end up writing one at some point, but as of this release, it doesn't have the ability to spawn related commands (e.g. start a daemon process and then come back to them).

There is a work around... Either use a runscript, or use the interactive shell which will keep all processes contained that started via the shell. So your command will instead look like this:

$ singularity shell xpra-rhel7.img
Singularity/xpra-rhel7.img> xpra start 3232 --start-child=beauti
Singularity/xpra-rhel7.img> beauti
...

Also, check your DISPLAY environment variable both outside and inside your container. Singularity passes that automatically into the container.

**Comment by gmkurtzer** [comment]
@loveshack Is this still an issue with the latest changes to linux_build_redhat.smod?

Thanks!

**Comment by gmkurtzer** [comment]
Closing stale issue. If it turns out this is still an issue with the latest releases we can come back and reopen or deal with it from there.

Thanks!
