### ISSUE TITLE
Importing keys with ascii armored format

### ISSUE THREAD

**Issue by jchavezlavalle** [apptainer/singularity#3300]
## Version of Singularity:

`3.1.1-902.ge094ee448`

### Expected behavior

Consider a key file with armored ascii format:
```
$ singularity key import ./file
```

The key is automatically detected it is armored and then added to the local keystore.

### Actual behavior

Does not exist yet, there's no support yet for key import on armor format key files.

### Steps to reproduce behavior

```
$ singularity key import  ./file
```

**Comment by WestleyK** [comment]
What do you think about automatically importing a ascii armor key? Without the user using the `--armor` flag. I think this is what gpg does. 

Maybe try to read it as a binary key, if that fails read it as a ascii key, if that fails, then its not a valid key.

**Comment by jchavezlavalle** [comment]
sure that makes sense, I'll go on that way :+1: @WestleyK
