### ISSUE TITLE
Improve test coverage of pkg/signing

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3305]
## Version of Singularity:

Improve test coverage of pkg/signing

### Expected behavior

Get close to 100% coverage.

### Actual behavior

`
$ go test -coverprofile=coverage.out && go tool cover -func=coverage.out
?   	github.com/sylabs/singularity/pkg/signing	[no test files]
total:	(statements)	0.0%
`

### Steps to reproduce behavior

Write here.

**Comment by gvallee** [comment]
I think we should wait for the work on GPG to go through so we can make sure we have all the required API and code to easy write tests dealing with keys and so on (cf. #3304 )

**Comment by dtrudg** [comment]
`pkg/signing` no longer exists. Functionality moved to the well tested integrity code in sif.
