### ISSUE TITLE
Improve test coverage of internal/pkg/build

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3306]
## Version of Singularity:

Improve test coverage of internal/pkg/build

### Expected behavior

Get close to 100% coverage

### Actual behavior

`
$ go test -coverprofile=coverage.out && go tool cover -func=coverage.out
?   	github.com/sylabs/singularity/internal/pkg/build	[no test files]
total:	(statements)	0.0%
`

`
$ go test -coverprofile=coverage.out && go tool cover -func=coverage.out
?   	github.com/sylabs/singularity/internal/pkg/build/apps	[no test files]
total:	(statements)	0.0%
`

### Steps to reproduce behavior

Write here.

**Comment by dtrudg** [comment]
Core functionality here has test coverage. The process of builds is heavily tested in the e2e. Doing much more on sources testing in these unit tests will make them long, as builds inevitably deal with remote sources.

```
?   	github.com/sylabs/singularity/internal/pkg/build	[no test files]
?   	github.com/sylabs/singularity/internal/pkg/build/apps	[no test files]
ok  	github.com/sylabs/singularity/internal/pkg/build/assemblers	9.008s	coverage: 52.0% of statements
ok  	github.com/sylabs/singularity/internal/pkg/build/files	0.053s	coverage: 86.0% of statements
ok  	github.com/sylabs/singularity/internal/pkg/build/oci	0.016s	coverage: 85.4% of statements
ok  	github.com/sylabs/singularity/internal/pkg/build/remotebuilder	0.019s	coverage: 8.3% of statements
ok  	github.com/sylabs/singularity/internal/pkg/build/sources	95.501s	coverage: 31.1% of statements
```
