### ISSUE TITLE
Improve test coverage of pkg/image

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3309]
## Version of Singularity:

Improve test coverage of pkg/image

### Expected behavior

Get close to 100% coverage.

### Actual behavior

`
$ go test -coverprofile=coverage.out && go tool cover -func=coverage.out
PASS
coverage: 38.2% of statements
ok  	github.com/sylabs/singularity/pkg/image	2.706s
github.com/sylabs/singularity/pkg/image/ext3.go:43:		CheckExt3Header		0.0%
github.com/sylabs/singularity/pkg/image/ext3.go:76:		initializer		0.0%
github.com/sylabs/singularity/pkg/image/ext3.go:100:		openMode		0.0%
github.com/sylabs/singularity/pkg/image/image.go:78:		AuthorizedPath		0.0%
github.com/sylabs/singularity/pkg/image/image.go:96:		AuthorizedOwner		0.0%
github.com/sylabs/singularity/pkg/image/image.go:117:		AuthorizedGroup		0.0%
github.com/sylabs/singularity/pkg/image/image.go:138:		HasRootFs		75.0%
github.com/sylabs/singularity/pkg/image/image.go:148:		ResolvePath		71.4%
github.com/sylabs/singularity/pkg/image/image.go:161:		Init			59.4%
github.com/sylabs/singularity/pkg/image/reader.go:16:		Error			0.0%
github.com/sylabs/singularity/pkg/image/reader.go:25:		checkImage		100.0%
github.com/sylabs/singularity/pkg/image/reader.go:35:		getSectionReader	100.0%
github.com/sylabs/singularity/pkg/image/reader.go:39:		commonSectionReader	100.0%
github.com/sylabs/singularity/pkg/image/reader.go:79:		NewPartitionReader	100.0%
github.com/sylabs/singularity/pkg/image/reader.go:87:		NewSectionReader	100.0%
github.com/sylabs/singularity/pkg/image/sandbox.go:15:		initializer		0.0%
github.com/sylabs/singularity/pkg/image/sandbox.go:30:		openMode		0.0%
github.com/sylabs/singularity/pkg/image/sif.go:25:		initializer		60.0%
github.com/sylabs/singularity/pkg/image/sif.go:153:		openMode		66.7%
github.com/sylabs/singularity/pkg/image/squashfs.go:40:		CheckSquashfsHeader	0.0%
github.com/sylabs/singularity/pkg/image/squashfs.go:79:		initializer		0.0%
github.com/sylabs/singularity/pkg/image/squashfs.go:109:	openMode		0.0%
total:								(statements)		38.2%
`

### Steps to reproduce behavior

Write here.

**Comment by jscook2345** [comment]
It looks like this was fixed when #3297 was merged. So I'm closing this up. If I'm incorrect, please re-open.
