### ISSUE TITLE
Improve test coverage of pkg/network

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3310]
## Version of Singularity:

Improve test coverage of pkg/network

### Expected behavior

Get close to 100% coverage.

### Actual behavior

`
$ go test -coverprofile=coverage.out && go tool cover -func=coverage.out
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75a518]

goroutine 1 [running]:
github.com/sylabs/singularity/internal/pkg/test.EnsurePrivilege(0x0)
	/home/gvallee/go/src/github.com/sylabs/singularity/internal/pkg/test/privilege_linux.go:34 +0x78
github.com/sylabs/singularity/pkg/network.TestMain(0xc0000e2380)
	/home/gvallee/go/src/github.com/sylabs/singularity/pkg/network/network_linux_test.go:595 +0x3f
main.main()
	_testmain.go:92 +0x1cb
exit status 2
FAIL	github.com/sylabs/singularity/pkg/network	0.007s
`

### Steps to reproduce behavior

Write here.

**Comment by jscook2345** [comment]
@cclerget 

I looked at the coverage and its close to 85%.

I think this is a great improvement and I think we can close this out!

```
ok  	github.com/sylabs/singularity/pkg/network	1.743s	coverage: 85.7% of statements
```
