### ISSUE TITLE
Improve test coverage of pkg/runtime

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3313]
## Version of Singularity:

Improve test coverage of pkg/runtime

### Expected behavior

Get close to 100% coverage.

### Actual behavior

`
$ go test -coverprofile=coverage.out && go tool cover -func=coverage.out
?   	github.com/sylabs/singularity/pkg/runtime/engines/singularity/config	[no test files]
total:	(statements)	0.0%
`

### Steps to reproduce behavior

Write here.

**Comment by dtrudg** [comment]
With refactoring that has occurred this is really just now structs and getters/setters that aren't particularly important unit test targets. The usage of the config structs is exercised through e2e.
