### ISSUE TITLE
Improve test coverage internal/pkg/instance

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3317]
## Version of Singularity:

Improve test coverage internal/pkg/instance.

### Expected behavior

Get close to 100% coverage.

### Actual behavior

`
$ sudo /usr/local/go/bin/go test -coverprofile=coverage.out && go tool cover -func=coverage.out
PASS
coverage: 76.6% of statements
ok  	github.com/sylabs/singularity/internal/pkg/instance	0.066s
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:64:	ProcName		100.0%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:75:	ExtractName		100.0%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:80:	CheckName		100.0%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:89:	getPath			68.2%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:127:	getDir			83.3%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:140:	GetDirPrivileged	100.0%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:146:	GetDirUnprivileged	100.0%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:151:	Get			87.5%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:167:	Add			91.7%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:186:	List			78.6%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:229:	PrivilegedPath		100.0%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:234:	Delete			83.3%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:248:	Update			70.8%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:289:	MountNamespaces		75.0%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:313:	UpdateNamespacesPath	62.9%
github.com/sylabs/singularity/internal/pkg/instance/instance_linux.go:373:	SetLogFile		69.6%
github.com/sylabs/singularity/internal/pkg/instance/logger.go:33:		kubernetesLogFormatter	100.0%
github.com/sylabs/singularity/internal/pkg/instance/logger.go:37:		jsonLogFormatter	100.0%
github.com/sylabs/singularity/internal/pkg/instance/logger.go:41:		basicLogFormatter	100.0%
github.com/sylabs/singularity/internal/pkg/instance/logger.go:63:		NewLogger		83.3%
github.com/sylabs/singularity/internal/pkg/instance/logger.go:79:		closeFile		0.0%
github.com/sylabs/singularity/internal/pkg/instance/logger.go:83:		openFile		100.0%
github.com/sylabs/singularity/internal/pkg/instance/logger.go:96:		scanOutput		50.0%
github.com/sylabs/singularity/internal/pkg/instance/logger.go:115:		NewWriter		100.0%
github.com/sylabs/singularity/internal/pkg/instance/logger.go:121:		scan			83.3%
github.com/sylabs/singularity/internal/pkg/instance/logger.go:143:		ReOpenFile		100.0%
total:										(statements)		76.6%
`

### Steps to reproduce behavior

Write here.

**Comment by dtrudg** [comment]
77.5% coverage plus code is exercised by e2e. Should direct effort elsewhere.
