### ISSUE TITLE
Improve test coverage of internal/pkg/libexec

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3318]
## Version of Singularity:

Improve test coverage of internal/pkg/libexec.

### Expected behavior

Get close to 100% coverage.

### Actual behavior

`
$ go test -coverprofile=coverage.out && go tool cover -func=coverage.out
?   	github.com/sylabs/singularity/internal/pkg/libexec	[no test files]
total:	(statements)	0.0%
`

### Steps to reproduce behavior

Write here.

**Comment by dtrudg** [comment]
There is no libexec any more
