### ISSUE TITLE
Improve test coverage of internal/pkg/syecl

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3323]
## Version of Singularity:

Improve test coverage of internal/pkg/syecl.

### Expected behavior

Get close to 100%.

### Actual behavior

`
$ go test -coverprofile=coverage.out && go tool cover -func=coverage.out
PASS
coverage: 79.3% of statements
ok  	github.com/sylabs/singularity/internal/pkg/syecl	0.009s
github.com/sylabs/singularity/internal/pkg/syecl/syecl.go:45:	LoadConfig		80.0%
github.com/sylabs/singularity/internal/pkg/syecl/syecl.go:58:	PutConfig		75.0%
github.com/sylabs/singularity/internal/pkg/syecl/syecl.go:69:	ValidateConfig		76.2%
github.com/sylabs/singularity/internal/pkg/syecl/syecl.go:106:	checkWhiteList		80.0%
github.com/sylabs/singularity/internal/pkg/syecl/syecl.go:128:	checkWhiteStrict	92.3%
github.com/sylabs/singularity/internal/pkg/syecl/syecl.go:155:	checkBlackList		75.0%
github.com/sylabs/singularity/internal/pkg/syecl/syecl.go:173:	shouldRun		94.1%
github.com/sylabs/singularity/internal/pkg/syecl/syecl.go:210:	ShouldRun		66.7%
github.com/sylabs/singularity/internal/pkg/syecl/syecl.go:225:	ShouldRunFp		0.0%
total:								(statements)		79.3%
`

### Steps to reproduce behavior

Write here.

**Comment by dtrudg** [comment]
Now 86.3% coverage after signing security changes.
