### ISSUE TITLE
Improve test coverage of internal/pkg/test

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3325]
## Version of Singularity:

Improve test coverage of internal/pkg/test.

### Expected behavior

Get close to 100%.

### Actual behavior

`
$ go test -coverprofile=coverage.out && go tool cover -func=coverage.out
?   	github.com/sylabs/singularity/internal/pkg/test	[no test files]
total:	(statements)	0.0%
`

### Steps to reproduce behavior

Write here.

**Comment by dtrudg** [comment]
Only called by tests. Would be nice in an ideal world to cover these helper functions, but we should direct effort on testing the production code, not testing our tests.
