### ISSUE TITLE
Improve test coverage of internal/pkg/util

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3326]
## Version of Singularity:

Improve test coverage of internal/pkg/util. The package was many components, I am not giving the current coverage results (util/exec has no test for example), the assignee will be responsible for identifying the gaps and addressing them.

### Expected behavior

Get close to 100%.

### Actual behavior

Write here.

### Steps to reproduce behavior

Write here.

**Comment by dtrudg** [comment]
Coverage has improved in this location. Generally >75% except for starter and some trivial config fetchers.
