### ISSUE TITLE
Improve test coverage of cmd/singularity

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3327]
## Version of Singularity:

Improve test coverage of cmd/singularity.

### Expected behavior

Get close to 100% coverage.

### Actual behavior

`
$ sudo /usr/local/go/bin/go test -coverprofile=coverage.out && go tool cover -func=coverage.out
--- FAIL: TestPull (8.63s)
    --- FAIL: TestPull/Pull_Library (0.02s)
        pull_test.go:70: Invalid flag "--allow-unauthenticated" for command "pull".
            
            Options:
            
                  --docker-login     login to a Docker Repository interactively
              -F, --force            overwrite an image file if it exists
              -h, --help             help for pull
                  --library string   download images from the provided library
                                     (default "https://library.sylabs.io")
                  --no-cleanup       do NOT clean up bundle after failed build, can be
                                     helpul for debugging
                  --nohttps          do NOT use HTTPS with the docker:// transport
                                     (useful for local docker registries without a
                                     certificate)
            
            Run 'singularity pull --help' for more detailed usage information.
            
        pull_test.go:71: unexpected failure: exit status 1
    --- FAIL: TestPull/ForceUnauth (1.00s)
        pull_test.go:76: WARNING: No default remote in use, falling back to: https://library.sylabs.io
            INFO:    Downloading library image
 2.08 MiB / 2.08 MiB [=====================================================================================================] 100.00% 5.56 MiB/s 0s
            
        pull_test.go:77: unexpected success: command should have failed
    --- FAIL: TestPull/Force (0.02s)
        pull_test.go:70: Invalid flag "--allow-unauthenticated" for command "pull".
            
            Options:
            
                  --docker-login     login to a Docker Repository interactively
              -F, --force            overwrite an image file if it exists
              -h, --help             help for pull
                  --library string   download images from the provided library
                                     (default "https://library.sylabs.io")
                  --no-cleanup       do NOT clean up bundle after failed build, can be
                                     helpul for debugging
                  --nohttps          do NOT use HTTPS with the docker:// transport
                                     (useful for local docker registries without a
                                     certificate)
            
            Run 'singularity pull --help' for more detailed usage information.
            
        pull_test.go:71: unexpected failure: exit status 1
    --- FAIL: TestPull/Unsigned_image (0.02s)
        pull_test.go:70: Invalid flag "--allow-unauthenticated" for command "pull".
            
            Options:
            
                  --docker-login     login to a Docker Repository interactively
              -F, --force            overwrite an image file if it exists
              -h, --help             help for pull
                  --library string   download images from the provided library
                                     (default "https://library.sylabs.io")
                  --no-cleanup       do NOT clean up bundle after failed build, can be
                                     helpul for debugging
                  --nohttps          do NOT use HTTPS with the docker:// transport
                                     (useful for local docker registries without a
                                     certificate)
            
            Run 'singularity pull --help' for more detailed usage information.
            
        pull_test.go:71: unexpected failure: exit status 1
    --- FAIL: TestPull/Unsigned_image_fail (0.75s)
        pull_test.go:76: WARNING: No default remote in use, falling back to: https://library.sylabs.io
            INFO:    Downloading library image
 660.00 KiB / 660.00 KiB [=================================================================================================] 100.00% 2.60 MiB/s 0s
            
        pull_test.go:77: unexpected success: command should have failed
    --- FAIL: TestPull/PullWithHash (0.03s)
        pull_test.go:70: Invalid flag "--allow-unauthenticated" for command "pull".
            
            Options:
            
                  --docker-login     login to a Docker Repository interactively
              -F, --force            overwrite an image file if it exists
              -h, --help             help for pull
                  --library string   download images from the provided library
                                     (default "https://library.sylabs.io")
                  --no-cleanup       do NOT clean up bundle after failed build, can be
                                     helpul for debugging
                  --nohttps          do NOT use HTTPS with the docker:// transport
                                     (useful for local docker registries without a
                                     certificate)
            
            Run 'singularity pull --help' for more detailed usage information.
            
        pull_test.go:71: unexpected failure: exit status 1
    --- FAIL: TestPull/PullWithoutTransportProtocol (0.01s)
        pull_test.go:70: Invalid flag "--allow-unauthenticated" for command "pull".
            
            Options:
            
                  --docker-login     login to a Docker Repository interactively
              -F, --force            overwrite an image file if it exists
              -h, --help             help for pull
                  --library string   download images from the provided library
                                     (default "https://library.sylabs.io")
                  --no-cleanup       do NOT clean up bundle after failed build, can be
                                     helpul for debugging
                  --nohttps          do NOT use HTTPS with the docker:// transport
                                     (useful for local docker registries without a
                                     certificate)
            
            Run 'singularity pull --help' for more detailed usage information.
            
        pull_test.go:71: unexpected failure: exit status 1
    --- FAIL: TestPull/Pull_Library_Latest (0.01s)
        pull_test.go:70: Invalid flag "--allow-unauthenticated" for command "pull".
            
            Options:
            
                  --docker-login     login to a Docker Repository interactively
              -F, --force            overwrite an image file if it exists
              -h, --help             help for pull
                  --library string   download images from the provided library
                                     (default "https://library.sylabs.io")
                  --no-cleanup       do NOT clean up bundle after failed build, can be
                                     helpul for debugging
                  --nohttps          do NOT use HTTPS with the docker:// transport
                                     (useful for local docker registries without a
                                     certificate)
            
            Run 'singularity pull --help' for more detailed usage information.
            
        pull_test.go:71: unexpected failure: exit status 1
FAIL
coverage: 50.0% of statements
exit status 1
FAIL	github.com/sylabs/singularity/cmd/singularity	354.789s
`

### Steps to reproduce behavior

Write here.

**Comment by dtrudg** [comment]
Cannot reproduce the failure now.
