### ISSUE TITLE
Improve test coverage of etc/conf

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3328]
## Version of Singularity:

Improve test coverage of etc/conf.

### Expected behavior

Get close to 100% coverage.

### Actual behavior

`
$ sudo /usr/local/go/bin/go test -coverprofile=coverage.out && go tool cover -func=coverage.out
PASS
coverage: 36.0% of statements
ok  	github.com/sylabs/singularity/etc/conf	0.065s
github.com/sylabs/singularity/etc/conf/gen.go:17:	main		0.0%
github.com/sylabs/singularity/etc/conf/gen.go:38:	genConf		64.3%
total:							(statements)	36.0%`

### Steps to reproduce behavior

Write here.

**Comment by dtrudg** [comment]
Now improved a bit.
```
10:51 AM $ go test -cover ./...
ok  	github.com/sylabs/singularity/etc/conf	(cached)	coverage: 40.9% of statements
```
