### ISSUE TITLE
Broken links on community page

### ISSUE THREAD

**Issue by keiranmraine** [apptainer/singularity#3330]
This may not be the correct repo, but it wasn't clea where this should go.

On this page: https://www.sylabs.io/singularity/community/

The link for "Issues" is broken: https://www.sylabs.io/singularity/issues/

## Version of Singularity:

N/A

### Expected behavior

Link to issue tracker

### Actual behavior

"Sorry, this page could not be found."

### Steps to reproduce behavior

Follow links above

**Comment by jscook2345** [comment]
@keiranmraine 

This is good enough. Thanks for the report!

**Comment by jscook2345** [comment]
@wobito @jmstover ping!

**Comment by wobito** [comment]
FIXED: Updated the link to the github issues pages.
