### ISSUE TITLE
[python] [docker] refactor get_cache to only do a single os.makedirs

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#334]
As mentioned by @flx42 we should refactor this function to not have the issue of setting the cache_dir as "/" to result in a double "//"

**Comment by flx42** [comment]
In addition, the following pattern is not recommended in Python:
https://github.com/singularityware/singularity/blob/master/libexec/python/utils.py#L222-L223
It's subject to a race condition between the `os.path.exists` and the `os.mkdir`.

So, `os.makedirs` should be called without `os.path.exists`, but before Python 3.2 it's not entirely trivial to implement properly if the path might already exist. This [discussion](http://stackoverflow.com/questions/600268/mkdir-p-functionality-in-python) explains everything.
