### ISSUE TITLE
plugin/hooks: ability to spawn process in container

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#3347]
Add the ability to spawn a process in the container, alongside the payload proc. This will allow the cvmfs helper binary to run on `/dev/fd/$FD` to mount cvmfs as fuse

Updates: #2864

**Comment by dtrudg** [comment]
@DrDaveD - can you advise if this is obsolete now?

**Comment by DrDaveD** [comment]
I don't need it anymore since the --fusemount option does this, but it may still be desired as a plugin feature, I don't know.
