### ISSUE TITLE
Multi-stage file copy and non-existent parent directories

### ISSUE THREAD

**Issue by samcmill** [apptainer/singularity#3348]
## Version of Singularity: 

3.2.0-rc1

### Expected behavior

Image successfully built with file at path `/some/other/path/foo`.

### Actual behavior

```
INFO:    Copying /tmp/sbuild-471116024/fs/path/to/something/foo to /tmp/sbuild-068948471/fs/some/other/path/foo
FATAL:   While performing build: unable to copy files a stage to container fs: while copying /tmp/sbuild-471116024/fs/path/to/something/foo to /tmp/sbuild-068948471/fs/some/other/path/foo: exit status 1: /bin/cp: cannot create regular file '/tmp/sbuild-068948471/fs/some/other/path/foo': No such file or directory
```

### Steps to reproduce behavior

```
# cat foo.def
BootStrap: docker
From: centos:7
Stage: zero

%post
    mkdir -p /path/to/something
    echo "foo" >> /path/to/something/foo

BootStrap: docker
From: centos:7

%files from zero
    /path/to/something/foo /some/other/path/foo

# singularity build foo.sif foo.def
...
```

This is almost certainly the same underling issue as https://github.com/sylabs/singularity/issues/1549.  However, the `%setup` workaround does not work in the second stage of a multi-stage definition file - it looks like `%setup` is completely ignored?

The "copy file to root, then move in %post" trick does work.

IMHO, multi-stage builds add some urgency to fix #1549.  It seems very natural to build something in the first stage, and then want to copy it to another location in the second stage.  More so than copying files from the host into the container, which is the use case of #1549.  

@ikaneshiro

**Comment by ikaneshiro** [comment]
@samcmill Agreed will have a fix for #1549, and thus this issue as well, shortly
