### ISSUE TITLE
[python] plugin for singularity-bot to check python

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#335]
http://docs.sonarqube.org/display/PLUG/Python+Plugin

**Comment by bbockelm** [comment]
I suspect we'll need to figure out how to organize the `sonar-project.properties` file into two modules and have one run python static analysis and the other C.

**Comment by vsoch** [comment]
https://github.com/SonarSource/sonar-custom-rules-examples/issues/1

**Comment by vsoch** [comment]
Actually, I think it might be something simple [like this](https://github.com/SonarSource/sq-com_example_standard-sqscanner-travis/blob/master/sonar-project.properties#L23)

**Comment by bbockelm** [comment]
http://docs.sonarqube.org/display/PLUG/Pylint+Report here's the documentation for configuring the pylint stuff.  If you're not familiar with pylint, you might want to tune a site-custom `pylintrc` (the default is rather picky...)

**Comment by bbockelm** [comment]
ah-ha:  Via StackOverflow, here's a multi-language project: https://github.com/SonarSource/sonar-examples/tree/master/projects/languages/multi-language/multi-language-java-javascript-sonar-runner

Seems that if you don't explicitly state a language, it automatically detects things.
