### ISSUE TITLE
[E2E] port integration test "instance"  to the e2e framework

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#3352]
## E2E Task

Port:
 - https://github.com/sylabs/singularity/blob/master/cmd/singularity/instance_test.go
to the e2e framework
 - https://github.com/sylabs/singularity/tree/master/e2e
under `e2e/instance`

**Comment by ArangoGutierrez** [comment]
@phpHavok Would be nice to have your insight here, given that you wrote the initial implementation of the instance tests

**Comment by phpHavok** [comment]
@ArangoGutierrez: Sure thing; let me get up to speed on the E2E framework and I can go ahead and port the instance tests over.

**Comment by ArangoGutierrez** [comment]
@jscook2345 has some tips on how to also work some enhancements over the instance testing.
