### ISSUE TITLE
[E2E] port integration test "help" to the e2e framwork

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#3353]
## E2E Task

Port:
 - https://github.com/sylabs/singularity/blob/master/cmd/singularity/help_test.go
to the e2e framework
- https://github.com/sylabs/singularity/tree/master/e2e
under `e2e/help`

**Comment by jscook2345** [comment]
I'd like to work on this one as a way to understand the framework. ty!
