### ISSUE TITLE
[E2E] port integration test "environment" to the e2e framework

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#3354]
## E2E Task

Port:
 - https://github.com/sylabs/singularity/blob/master/cmd/singularity/env_test.go
to the e2e framework
 - https://github.com/sylabs/singularity/tree/master/e2e
under `e2e/actions`

**Comment by devprincess** [comment]
Okay, I think I'll start working on this one, in the way to understand the framework, thanks @ArangoGutierrez :+1:
