### ISSUE TITLE
running most make commands has some go module output

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3361]
## Version of Singularity:

master

### Expected behavior

```
make -C builddir integration-test
<no module output>
```

### Actual behavior
```
$ make -C builddir integration-test`
go: finding github.com/opencontainers/image-tools v0.0.0-00010101000000-000000000000
```

Not sure why this is happening when running various `make` commands.

**Comment by mem** [comment]
Aha! Found the pesky call to `go` that's causing modules to be downloaded...

Fixing.

**Comment by mem** [comment]
I believe this one is fixed for good. @jscook2345 could you please verify?

**Comment by jscook2345** [comment]
Verified!
