### ISSUE TITLE
Cherry Picks for 3.2-rc2

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#3371]
#### List of PRs that should be cherry picked for 3.2-rc2:
- #3288 
- #3291 
- #3293 
- #3295 
- #3368 
- #3180 
Additions:
- #3301 
- #3298
- #3281
- #3343
- #3267

Issues merged after rc1 was cut on april 11th

**Comment by WestleyK** [comment]
I think it may be better to not include https://github.com/sylabs/singularity/pull/3281, becuse theres no way to import that ascii key with singularity (as of right now). It may be better to save the ascii armor exporting/importing for 3.3? Unless the "importing ascii armor keys" PR will make it into rc-2/rc-3?

@devprincess ^^^ Feel free to add/correct me :+1:

**Comment by GodloveD** [comment]
rc-2 has been released.
