### ISSUE TITLE
make e2e-test does not indicate everything was skipped if you forget to set the env var

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3374]
## Version of Singularity:

master

It would be good if when running and you forget to set `SINGULARITY_E2E` that `make e2e-test` does not show as all OK.

```
make: Entering directory `/home/vagrant/singularity/builddir'
 TEST sudo go test [e2e]
ok      github.com/sylabs/singularity/e2e       1.007s  coverage: 5.4% of statements
       PASS
make: Leaving directory `/home/vagrant/singularity/builddir'
```

Running verbose, you see it skipped everything.

```
make: Entering directory `/home/vagrant/singularity/builddir'
 TEST sudo go test [e2e]
=== RUN   TestE2E
--- SKIP: TestE2E (0.00s)
    e2e.go:16: Skipping e2e tests, SINGULARITY_E2E not set
PASS
coverage: 5.4% of statements
ok      github.com/sylabs/singularity/e2e       1.007s  coverage: 5.4% of statements
       PASS
```

**Comment by mem** [comment]
The env var was removed; the makefile passes the right command line arguments for the tests to run. (Given the description, I assume the issue is about running the tests from make; there's a script e2e-test that does this).
