### ISSUE TITLE
e2e framework does not operate in same directory as test

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3379]
## Version of Singularity:

master

Normally `go test` would operate in the same directory as the test and therefore grab the `testdata` from that directory.

Because of how the e2e framework is structured that is no longer the case and the `testdata` must all go in the root directory, or the same directory as `e2e_test.go`

**Comment by dtrudg** [comment]
I think we can live with this - and we have some content that is shared between e2e tests which would otherwise be duplicated or need an exception to use a shared location.
