### ISSUE TITLE
Document necessity of custom clone implementation and usage of CLONE_FILES|CLONE_FS

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#3381]
In `cmd/starter/c/starter.c` file, we have a custom `clone()` implementation, as well as calling this with the flags `CLONE_FILES|CLONE_FS`. We do this in order to solve some issues that arose such as the issue with `autofs`. We should add comments to the code which document why we've decided to do this. The relevant portions of `starter.c` are included below. The reference to `fork_ns()` which includes `CLONE_FILES|CLONE_FS` does have a comment explaining why we're using those clone flags, however documentation/justification on the custom `clone()` implementation is lacking.

@cclerget Had the following comment on this providing some insights:

>Yes clearly this is a hack, and there is few considerations, file descriptors are shared with further process, because the stage 1 (frankenstein process) does some sanity checks and open image/bind points, image is open and kept open at this stage to check signature in case of SIF and ensure the same image will be used by RPC server during loop device association and by master process in create container step to read the "right" image and not a rogue one that could have been replaced by another one by playing with symlink or path trick. Also bind points are all open in stage 1 (and kept open) to keep a mount reference outside of any container mount namespace, this is the workaround to deal with bugged autofs, so we can't create a mount namespace before doing that. Stage 1 additionally check capabilities (to add/drop them based on capability management), during join it read instance file and apply engine configuration by doing some sanity checks. Stage 1 finally send back (via a shared memory space) to starter namespaces/capabilities/user namespace mapping requirements that starter will apply in a single-thread context

Line 86,109:
```
typedef struct fork_state_s {
    sigjmp_buf env;
} fork_state_t;

/* copy paste from singularity code */
static int clone_fn(void *data_ptr) {
    fork_state_t *state = (fork_state_t *)data_ptr;
    siglongjmp(state->env, 1);
}

static int fork_ns(unsigned int flags) {
    fork_state_t state;

    if ( sigsetjmp(state.env, 1) ) {
        return 0;
    }

    int stack_size = CLONE_STACK_SIZE;
    char *child_stack_ptr = malloc(stack_size);
    if ( child_stack_ptr == 0 ) {
        errno = ENOMEM;
        return -1;
    }
    child_stack_ptr += stack_size;

    int retval = clone(clone_fn, child_stack_ptr, (SIGCHLD|flags), &state);
    return retval;
}
```

Line 954,979:
```
    /*
     *  use CLONE_FILES to share file descriptors opened during stage 1,
     *  this is a lazy implementation to avoid passing file descriptors
     *  between wrapper and stage 1 over unix socket.
     *  This is required so that all processes works with same files/directories
     *  to minimize race conditions
     */
    stage_pid = fork_ns(CLONE_FILES|CLONE_FS);
    if ( stage_pid == 0 ) {
        /*
         *  stage1 is responsible for singularity configuration file parsing, handle user input,
         *  read capabilities, check what namespaces is required.
         */
        if ( config->container.isSuid ) {
            priv_escalate();
            execute = prepare_stage(STAGE1, config);
        } else {
            set_parent_death_signal(SIGKILL);
            execute = STAGE1;
        }

        verbosef("Spawn stage 1\n");
        return;
    } else if ( stage_pid < 0 ) {
        fatalf("Failed to spawn stage 1\n");
    }
```

cc @cclerget

**Comment by cclerget** [comment]
Done during starter refactoring
