### ISSUE TITLE
thoughts on default use of latest

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3392]
@gmkurtzer thoughts on default use of `latest`, from Slack. Posting per his request.

Heya. Still thinking about our default use of ‘latest’. I’m thinking about it more I’m still of the opinion that the ‘latest’ tag should be always used by default even if other tags are present. This behavior could be stopped if there is an option to disable it.

`—nolatest` for example.

Otherwise I really think all containers pushed should by default overwrite any previous latest tags.

**Comment by jmstover** [comment]
> Otherwise I really think all containers pushed should by default overwrite any previous latest tags.

I have to disagree with @gmkurtzer here. For example, lets say we have a Python image. We push up:
```
python:2.7.14
python:2.7.15
python:3.7.2
python:3.7.3
```
`python:3.7.3` also has the `:latest` tag. 

Now, we push up `python:2.7.16`  ... As described here, `:2.7.16` label would by default now also be `:latest`, even though `:3.7.3` is the actual latest yes? 

How are we considering the classification of the `:latest` tag? By Timestamp (most recent uploaded)? Version (Useful in some cases, not in all)? Just leave it up to the user to decide what is `:latest`, but if a image location doesn't have it, it's automatically applied that first time only?

**Comment by dtrudg** [comment]
Discussed more recently in #4688
