### ISSUE TITLE
Clarify overlay support on RHEL

### ISSUE THREAD

**Issue by flx42** [apptainer/singularity#340]
The following line in [etc/singularity.conf](https://github.com/singularityware/singularity/blob/master/etc/singularity.conf#L27) is a bit scary:
```
# note: currently disabled because RHEL7 kernel crashes with it... :(
```
Would you mind clarifying which version of RHEL you used? Was it 7.2 or 7.1?
Some overlay fixes went into [7.2](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html) so maybe it's fixed with this version.

**Comment by bbockelm** [comment]
It's on RHEL7.2.

The crash is unfortunately 100% reliable... seems to be something with mixing certain FUSE filesystems and Singularity.

**Comment by flx42** [comment]
Ah I see, so that's #228
No repro without FUSE?

**Comment by gmkurtzer** [comment]
It is 100% reliable on the configurations that trigger it. I haven't seen it ever on RHEL/Centos 7.2 with `3.10.0-327.28.2.el7.x86_64` but I am also not using FUSE anywhere. <shrugs>

**Comment by flx42** [comment]
Alright, thanks for the quick response.
Could we have a slightly less scary message then? :)
And maybe a link to #228

**Comment by gmkurtzer** [comment]
Done, closing old issue.
