### ISSUE TITLE
Runscript equivalent for singularity shell command

### ISSUE THREAD

**Issue by rickstaa** [apptainer/singularity#3401]
Dear Developers,

I am trying to source the ros `setup.bash` file and other `setup.bash` files automatically when shelling into a singularity image. I, therefore, added the following line to my singularity recipe file:

```
%environment

    ## Source ros setup file ##
    . /opt/ros/kinetic/setup.sh

```

After building the singularity image this source command ends up in the `*90-enviroments.sh` script, which is then sourced when the singularity shell is opened. Unfortunately, the environmental variables that are supposed to be set when sourcing the `setup.bash file` are not available when I shell into the container using the `singularity shell --nv container.simg` command. For example, when I am trying to use the `roslaunch` command I get the following error: 

`bash: roslaunch: command not found`

I found the following solution on [StackOverflow](https://stackoverflow.com/questions/51037873/bash-script-to-perform-action-in-a-singularity-container-it-opens ) but I was hoping there is something similar to the `runscript` argument that enables me to source files when shelling into a singularity container.

## Version of Singularity:
3.0.3

### Expected behavior
I expected the `/opt/ros/kinetic/setup.bash` file to be sourced when the container is loaded using `shell --nv container.simg `

### Actual behavior

Although the source command ends up in the `*90-enviroments.sh` script none of the enviromental variables that are supposed to be added to my workspace when sourcing the `/opt/ros/kinetic/setup.bash` file are available in my workspace. These commands appear to be available again when I run the `bash` command inside the singularity image. I, therefore, suspect that the singularity image uses a slightly different /bin/bash shell. The `echo $SHELL` command both has `/bin/bash` as an output in both the singularity shell and the bash shell running inside the singularity image.

### Steps to reproduce the behavior

Add one of the following source commands to the `%enviroment` section of the singularity recipe file:

- `. /file_you_you_want_to_source.sh
- `source /file_you_you_want_to_source.sh`
- `bash -c "source /file_you_you_want_to_source.sh"`
- `sh -c "source /file_you_you_want_to_source.sh"`
- `bash -c ". /file_you_you_want_to_source.sh"`
- `sh -c ". /file_you_you_want_to_source.sh"`

**Comment by jmstover** [comment]
Hi @rickstaa ,

We use bash... but bash started with the `--norc` option, so no system profile scripts are read. The error you're getting looks to be that the `roslaunch` program isn't found in the `PATH`.

Try setting `SINGULARITY_SHELL=/bin/bash` ... this will run `/bin/bash` without the `--norc` option. It *will* read your `${HOME}/.bash_profile` (and possibly .bashrc)... so the prompt may not change. To verify you're in a singularity image, look for `SINGULARITY_NAME` ... it will be set to the image if you're in the container. 

That may setup the environment better for your use case.

**Comment by rickstaa** [comment]
Dear @jmstover. Thanks for pointing that out that clarifies things! I also asked the question on the [answers.ros ](https://answers.ros.org/question/321775/automatically-source-ros-devel-folder-when-starting-singularity-image/) forum and the discussion there helped me to get to the following conclusion on what to do in my case:

- Other than the option depicted by the StackOverflow question there is no easy method of directly sourcing files when invoking a container using the shell command.
- I think it is, therefore, a better idea to include a `%runscript` and `%startscript` in my recipe file and following interacting with the created container using the run and start instance commands. This gives me full control over whether I want to use the `ENTRYPOINT` and `CMD` options supplied by the docker file or use my own run/startup commands.

Feel free to correct me if I'm wrong :).

**Comment by jmstover** [comment]
> Other than the option depicted by the StackOverflow question there is 
> no easy method of directly sourcing files when invoking a container using the shell command.

Pretty much correct. You _can_ source files. But if those files define functions you're going to be out of luck as you will see any variables defined, but not the functions themselves.

Using a runscript (or startscript for instance) is the best method. In 3.2.x there will be the ability to specify your own shebang line for `%runscript` ... so you could eventually do something like:

```
# We're assuming tcsh was installed in container =)
%runscript
#!/bin/tcsh
  [ ... ]
```

Which will help out on some of these issues. Not all of them, but some.

**Comment by rickstaa** [comment]
Ah, @jmstover thanks a lot for going into details and pointing me to the 3.2.x shebang line for runscript. That would be a real improvement. I just tried adding a source script to the `runscript` but the sourcing of the ros `setup.bash` still doesn't seem to work when running the shell. Do you maybe have any Idea what I'm doing wrong? I'm using the following versions of the runscript.

```
%runscript
    # setup ros environment  
    exec "$@"	
    bash
    source /opt/ros/kinetic/setup.bash
```

I also tried:

```
%runscript
    # setup ros environment  
    exec "$@"	
    bash
    . /opt/ros/kinetic/setup.bash
```

and

```
%runscript
    # setup ros environment  
    exec "$@"	
    bash
    bash -c :"source /opt/ros/kinetic/setup.bash"
```
It seems to work without the `runscript` because the `ENTRYPOINT` bash script sources the ros `setup.bash` file. Further, as was explained in the documentation, adding a runscript also seems to overrule the original docker `ENTRYPOINT` entry. As my `%runscript` does not seem to work I now suspect my way of sourcing the ros `setup.bash` script adds the ros path to a different shell than the that is evoked when using the `run` command. The reason I'm asking is that I need to source multiple make devel `setup.bash` files. The only way I got it to work is the way you suggested (Adding the source commands in my `.bashrc` or `.bash_profile` and running singularity with the `SINGULARITY_SHELL=/bin/bash` command) and the approach suggested on StackOverflow. My prefered way, however, would be to add the sourcing of the files to the singularity recipe file.
**Full recipe file**
```
# Ros kinetic panda simulation ubuntu xenial singularity container recipe file
Bootstrap: docker
From: osrf/ros:kinetic-desktop-full-xenial

%help
    singularity container with Ros kinetic and Gazebo9 for the dynamic simulation of the Franka Emika Panda robot.

%labels
    Maintainer: Rick Staa
    Github: https://github.com/rickstaa
    Version v1.0

%post
    echo "Setting up ros kinetic emika franka container."

    ## Set user permissions to root ##
    #chmod 755 /root

%runscript

    # setup ros environment  
    exec "$@"	
    . /opt/ros/$ROS_DISTRO/setup.bash

%environment

    ## Change floating point format ##
    LC_NUMERIC="en_US.UTF-8"
```

**Comment by rickstaa** [comment]
**Solution**
Unfortunately, as the singularity `%runscript` uses the `/bin/sh` you need a separate script to source a `setup.bash` file. I, therefore, in the `runscript` now open a `/bin/bash` shell using the `-rcfile` argument. Following in this rcfile called `.singularity_bashrc` I source the `setup.bash` files. In singularity versions >3.2.x you now also have the ability to directly do this from within the `runscript` by using a `shebang` line.

**Steps**

1). Clone your .bashrc_file inside your singularity container.

```
### Clone .singularity_bashrc repository file ##
bash -c "cd / \
    && git clone https://github.com/rickstaa/pandasim_singularity_recipes \
    && cp /pandasim_singularity_recipes/.singularity_bashrc . \
    && rm -rf pandasim_singularity_recipes"
```

Alternatively, you can also add the following code to the `%post` section of your singularity recipe to create the .bashrc file from within your recipe file.

```
## Add extra commands to singularity entrypoint script
touch /.singularity_bashrc.sh
chmod +x /singularity_bashrc.sh
cat <<-EOF >> /singularity_bashrc.sh
    #!/bin/bash
    set -e
     
    # setup ros environment
    source "/opt/ros/\$ROS_DISTRO/setup.bash"
    echo "Ros setup bash file sourced."
        
    # Setup Panda_simulation enviroment (chained to franka_ros and moveit)
    if [ -f "/pandasim_ws/devel/setup.bash" ]; then
        source "/pandasim_ws/devel/setup.bash"
       echo "Panda_simulation setup bash file sourced."
    fi
EOF
```

!!!!Use tabs instead of 4 spaces. More information on heredoc list indenting can be found [here](https://unix.stackexchange.com/questions/76481/cant-indent-heredoc-to-match-nestings-indent) !!!!

2). Add the following code in the `%runscript` section:

```
## Run custom entrypoint BASH script
OCI_ENTRYPOINT='"/custom_entrypoint.sh"'
OCI_CMD='"/bin/bash"'
SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} ${OCI_CMD} '-rcfile' '/.singularity_bashrc'"
eval ${SINGULARITY_OCI_RUN}
```

3). Build the singularity container using the following `build` command:

`sudo singularity build --sandbox singularity_container singularity_recipe.def`

4). Now you can call the singularity container using the singularity `run` command:

`singularity run --nv singularity_container`

**Comment by rickstaa** [comment]
I, unfortunately, run into problems with my solution above. Altough

**Comment by 3rico** [comment]
A much simpler way for me is...

Make a **/path/to/temp.sh** file inside your singularity image with contents:

`source /path/to/setup.bash
`
Make a **singularity** file with contents:


```
Bootstrap: localimage
From: /path/to/singularity/image.simg
%runscript
        echo "This image does source /path/to/setup.bash at the beginning"
        exec /bin/bash --rcfile /path/to/temp.sh "$@"

```

Run:

`sudo singularity build image_new.simg singularity`

**Comment by 3rico** [comment]
This way worked for me...
Make a `/path/to/temp.sh` file with the contents.

`source /path/to/setup.bash`

Then make a `/path/to/singularity` file with the contents

```
Bootstrap: localimage
From: /path/to/image.simg

%runscript
        echo "This image does source /path/to/setup.bash at the begining"
        exec /bin/bash --rcfile /path/to/temp.sh "$@"

```
Optional:

`singularity image.create -s 2000 image_new.simg`

Then run.

`sudo singularity build image_new.simg singularity`

**Comment by naidoo88** [comment]
> %runscript
>         echo "This image does source /path/to/setup.bash at the begining"
>         exec /bin/bash --rcfile /path/to/temp.sh "$@"

Adding these lines directly to my  %runscript section worked for me, without the need to create a new image from a previously created one.
