### ISSUE TITLE
remote login asks for an api key ehen when i have an existing token

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3404]
## Version of Singularity:

3.2.0rc2

`singularity remote login SylabsCloud` asks for an API Key even when I have a sylabs token in my `.singularity` directory. Is that intentional?

**Comment by ikaneshiro** [comment]
Yes login should always be setting a new token. The default login behavior you're looking for is only activated when you have a token in `.singularity` and try to use that default remote right off the bat without logging in. So running a pull, build, etc

**Comment by jscook2345** [comment]
If I am already logged into something should it say that? Or allow me to quit the command without having to try login?

**Comment by ikaneshiro** [comment]
I don't think it needs to for 3.2 but be good to add for 3.3.

**Comment by dtrudg** [comment]
`remote login` is likely to be used in automated flows in CI that embed a secret in an env var etc. Following the pattern of other aws / azure etc. cli tools I don't think we should prompt if something is already setup here. A `ctrl-c` is possible.
