### ISSUE TITLE
confusing output when pushing existing image to library

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3408]
## Version of Singularity:

3.2.0rc2

```
[vagrant@localhost tmp]$ singularity push -U illolcow.sif library://jscook2345-double/default/illolcow.sif
WARNING: Skipping container verifying
INFO:    Image is already present in the library - not uploading.
INFO:    Setting tag latest
WARNING: latest replaces an existing tag
```

A few things:

* I would figure that this would upload the image no matter what, but it appears if the image exists it will not overwrite it.

* There is no `--force` option to overwrite, so perhaps there should be?

* Since the image is not being uploaded, why is there additional output after that message?

* I'm not sure INFO is right for saying 'we are not uploading your image'.  Perhaps just a message than exit?

**Comment by jmstover** [comment]
It's not uploading, but it's setting tags. For example you would do like:

```
singularity push -U illolcow.sif library://jscook2345-double/default/illolcow.sif:1.0
singularity push -U illolcow.sif library://jscook2345-double/default/illolcow.sif:master
```

The 2nd one won't upload, but will set the `master` tag.
