### ISSUE TITLE
[E2E] port "github.com/sylabs/singularity/internal/pkg/test" to the E2E

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#3410]
As @mem states on the PR review https://github.com/sylabs/singularity/pull/3382#discussion_r278195377

```
This is not a problem, but I'm also not so happy about the idea of having code that is only used in tests living in this path. You could move this to e2e/internal/pkg/test (or perhaps a more descriptive name than just test).
```

move the test privileges func to the E2E folder and rename it to a more proper name

**Comment by jscook2345** [comment]
@ArangoGutierrez @mem 

Some of those functions are used by unit tests. I don't think its a good idea to migrate that.
