### ISSUE TITLE
undefined symbol singularity_image_bind

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#342]
I'm getting this error with a a fresh install from the current master:

      vanessa@vanessa-ThinkPad-T450s:~/Desktop$ sudo singularity create arch.img
      Creating a new image with a maximum size of 768MiB...
      Executing image create helper
      /usr/local/libexec/singularity/simage: symbol lookup error: /usr/local/libexec/singularity/simage: undefined symbol: singularity_image_bind

Can anyone reproduce?

**Comment by bauerm97** [comment]
Can you get debug output for me to look into?

**Comment by bauerm97** [comment]
Also I'm questioning how any builds can be passing if you're consistently getting this error. Could it be that the new location of the singularity.la file is causing issues on your specific system? This https://github.com/singularityware/singularity/commit/e7dceef537854d5e5499c03f611d93105480cfa0 patch changed library behavior, so maybe that's the source of your issues?

EDIT: I can confirm that I cannot reproduce this error using a fresh install of the master branch. 

```
mibauer@depc403:~/devel_singularity$ sudo singularity create arch.img
Creating a new image with a maximum size of 768MiB...
Executing image create helper
Formatting image with ext3 file system
Done.
mibauer@depc403:~/devel_singularity$
```

Is it possible that your LD_LIBRARY_PATH doesn't respect the new library location reflected in https://github.com/singularityware/singularity/commit/e7dceef537854d5e5499c03f611d93105480cfa0 ?

**Comment by vsoch** [comment]
Yeah me too - note this is on my older computer (for watching movies and such) that isn't for work, Ubuntu 16.04

sudo singularity --debug create arch.img
	enabling debugging
	ending argument loop
	Exec'ing: /usr/local/libexec/singularity/cli/create.exec arch.img
	Creating a new image with a maximum size of 768MiB...
	VERBOSE [U=0,P=10837]      message.c:52:message_init()                : Set messagelevel to: 5
	DEBUG   [U=0,P=10837]      privilege.c:66:singularity_priv_init()     : Called singularity_priv_init(void)
	VERBOSE [U=0,P=10837]      util/util.c:52:envar()                     : Checking input from environment: 'SINGULARITY_TARGET_UID'
	DEBUG   [U=0,P=10837]      util/util.c:54:envar()                     : Checking environment variable is defined: SINGULARITY_TARGET_UID
	VERBOSE [U=0,P=10837]      util/util.c:56:envar()                     : Environment variable is NULL: SINGULARITY_TARGET_UID
	VERBOSE [U=0,P=10837]      util/util.c:52:envar()                     : Checking input from environment: 'SINGULARITY_TARGET_GID'
	DEBUG   [U=0,P=10837]      util/util.c:54:envar()                     : Checking environment variable is defined: SINGULARITY_TARGET_GID
	VERBOSE [U=0,P=10837]      util/util.c:56:envar()                     : Environment variable is NULL: SINGULARITY_TARGET_GID
	DEBUG   [U=0,P=10837]      privilege.c:131:singularity_priv_init()    : Returning singularity_priv_init(void)
	DEBUG   [U=0,P=10837]      simage.c:61:main()                         : Running /usr/local/libexec/singularity/simage create workflow
	DEBUG   [U=0,P=10837]      privilege.c:147:singularity_priv_escalate(): Running as root, not changing privileges
	VERBOSE [U=0,P=10837]      image-util.c:102:singularity_image_create(): Creating new sparse image at: arch.img
	DEBUG   [U=0,P=10837]      image-util.c:109:singularity_image_create(): Opening image 'w'
	VERBOSE [U=0,P=10837]      image-util.c:115:singularity_image_create(): Writing image header
	VERBOSE [U=0,P=10837]      image-util.c:118:singularity_image_create(): Expanding image to 768MB
	VERBOSE [U=0,P=10837]      image-util.c:126:singularity_image_create(): Making image executable
	DEBUG   [U=0,P=10837]      image-util.c:131:singularity_image_create(): Returning image_create(arch.img, 768) = 0
	Executing image create helper
	VERBOSE [U=0,P=10836]      message.c:52:message_init()                : Set messagelevel to: 5
	DEBUG   [U=0,P=10836]      privilege.c:66:singularity_priv_init()     : Called singularity_priv_init(void)
	VERBOSE [U=0,P=10836]      util/util.c:52:envar()                     : Checking input from environment: 'SINGULARITY_TARGET_UID'
	DEBUG   [U=0,P=10836]      util/util.c:54:envar()                     : Checking environment variable is defined: SINGULARITY_TARGET_UID
	VERBOSE [U=0,P=10836]      util/util.c:56:envar()                     : Environment variable is NULL: SINGULARITY_TARGET_UID
	VERBOSE [U=0,P=10836]      util/util.c:52:envar()                     : Checking input from environment: 'SINGULARITY_TARGET_GID'
	DEBUG   [U=0,P=10836]      util/util.c:54:envar()                     : Checking environment variable is defined: SINGULARITY_TARGET_GID
	VERBOSE [U=0,P=10836]      util/util.c:56:envar()                     : Environment variable is NULL: SINGULARITY_TARGET_GID
	DEBUG   [U=0,P=10836]      privilege.c:131:singularity_priv_init()    : Returning singularity_priv_init(void)
	DEBUG   [U=0,P=10836]      simage.c:61:main()                         : Running /usr/local/libexec/singularity/simage bind workflow
	DEBUG   [U=0,P=10836]      privilege.c:147:singularity_priv_escalate(): Running as root, not changing privileges
	/usr/local/libexec/singularity/simage: symbol lookup error: /usr/local/libexec/singularity/simage: undefined symbol: singularity_image_bind

**Comment by vsoch** [comment]
Where is the new one?

      echo $LD_LIBRARY_PATH
      /usr/lib/fsl/5.0:/lib:/usr/lib:/usr/local/lib

**Comment by vsoch** [comment]
Yep! That was it.

**Comment by vsoch** [comment]
There were old libraries (libsingularity*) that were being used instead of what is in `singularity/` I would imagine others might run into this issue when updating, we should write clear notes (somewhere) if they don't exist.

**Comment by vsoch** [comment]
Thanks for your help @bauerm97 !
