### ISSUE TITLE
Replace use of SINGULARITY_E2E with a go-based option

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3426]
## Version of Singularity:

master

I think it would be good to have a way to skip the e2e tests instead of skipping them by default. Since we already have a second target for e2e tests I think skipping by default does not make sense anymore.

I'd like to suggest using either `build tags` to avoid building e2e tests in the first place or using the `testing.Short()` API call / `go test` flag to determine when to skip. These are both go-based idioms that are common in go-based projects.

I think once we have a good grasp on what the e2e framework looks like `build tags` should be the commonly used option, which `testing.Short()` showing up in some of our longer running unit-tests.

What do you think? @mem @ArangoGutierrez  ?

**Comment by ArangoGutierrez** [comment]
the initial idea for that env var is to in a next sprint be able to set different values that will trigger different subsets of the E2E framework

**Comment by jscook2345** [comment]
Wouldn't that fall under `go test -run ...` or `build tags`? I'm just trying to not reinvent the wheel :)

**Comment by jscook2345** [comment]
Some articles with best practices for discussion:

* https://peter.bourgon.org/go-in-production/#testing-and-validation
* https://scene-si.org/2019/04/15/next-level-go-testing/

**Comment by mem** [comment]
The issue has reported has been fixed by adding build tags.

We could rename those build tags to follow Peter's recommended names, but that's a different issue.
