### ISSUE TITLE
Binding pipes like /var/lib/sss/pipes/nss?

### ISSUE THREAD

**Issue by oschulz** [apptainer/singularity#343]
We use SSSD for passwd and group, so our nsswitch.conf contains

    passwd:  compat sss
    group:   compat sss

For [PRoot](https://github.com/proot-me/PRoot), I just need to bind-mount `/var/lib/sss/pipes/nss` and user/group-id resolution works fine. However, singularity doesn't seem to be able to bind that pipe into a container - I get the error

    WARNING: Non existant 'bind path' source: '/var/lib/sss/pipes/nss'

even though the pipe-file clearly exists on the host system. Would it be possible to support this?

**Comment by bauerm97** [comment]
What appears to be happening is that by specifying the bind mount in your configuration file (which I assume you're doing) instead of as a user bind specification, it's restricting your ability to bind mount a file instead of a folder. Could you try removing the `bind path` line from your config file, and instead specifying the bind mount in your singularity command and see if that works? Also please run in debug mode, your command should look something like this: `singularity -d run -B /var/lib/sss/pipes/nss image.img`

@gmkurtzer is there a reason that we block file mounting when the mount is specified in the config file but not when we mount a file in the command?

**Comment by oschulz** [comment]
I did indeed try to bind via configuration file, but a user bind also doesn't work:

````
$ singularity run -B /var/lib/sss/pipes/nss image.sqsh
ERROR  : There was an error binding the path /var/lib/sss/pipes/nss: No such file or directory
ABORT  : Retval = 255
````

Running in debug mode results in

 ```
[...]
VERBOSE [U=1320,P=3472]    util/util.c:87:envar()                     : Obtained input from environment 'SINGULARITY_BINDPATH' = '/var/lib/sss/pipes/nss,'
DEBUG   [U=1320,P=3472]    userbinds.c:48:singularity_mount_userbinds(): Checking for 'user bind control' in config
DEBUG   [U=1320,P=3472]    config_parser.c:107:singularity_config_get_bool(): Called singularity_config_get_bool(user bind control, 1)
DEBUG   [U=1320,P=3472]    config_parser.c:80:singularity_config_get_value(): Called singularity_config_get_value(user bind control)
DEBUG   [U=1320,P=3472]    config_parser.c:99:singularity_config_get_value(): No configuration file entry found for 'user bind control'
DEBUG   [U=1320,P=3472]    config_parser.c:126:singularity_config_get_bool(): Undefined configuration for 'user bind control', returning default: yes
DEBUG   [U=1320,P=3472]    userbinds.c:59:singularity_mount_userbinds(): Parsing SINGULARITY_BINDPATH for user-specified bind mounts.
DEBUG   [U=1320,P=3472]    userbinds.c:76:singularity_mount_userbinds(): Found bind: /var/lib/sss/pipes/nss -> container:/var/lib/sss/pipes/nss
DEBUG   [U=1320,P=3472]    userbinds.c:78:singularity_mount_userbinds(): Checking if bind point is already mounted: /var/lib/sss/pipes/nss
DEBUG   [U=1320,P=3472]    rootfs.c:64:singularity_rootfs_dir()       : Returning singularity_rootfs_dir: /var/singularity/mnt/final
DEBUG   [U=1320,P=3472]    mount-util.c:42:check_mounted()            : Opening /proc/mounts
DEBUG   [U=1320,P=3472]    mount-util.c:48:check_mounted()            : Iterating through /proc/mounts
DEBUG   [U=1320,P=3472]    privilege.c:152:singularity_priv_escalate(): Temporarily escalating privileges (U=1320)
VERBOSE [U=0,P=3472]       userbinds.c:136:singularity_mount_userbinds(): Binding '/var/lib/sss/pipes/nss' to '/var/singularity/mnt/final//var/lib/sss/pipes/nss'
ERROR   [U=0,P=3472]       userbinds.c:138:singularity_mount_userbinds(): There was an error binding the path /var/lib/sss/pipes/nss: No such file or directory
[...]
```

I just found out that I *can* bind the whole directory `/var/lib/sss/pipes`, though (either via config or via `-B`) - with that, name resolution inside the container does work.

**Comment by gmkurtzer** [comment]
@bauerm97 Can you describe what you mean about block file mounting being done differently?

@oschulz The error message is being thrown by the mount() system call directly. My guess is that the kernel is refusing to mount the non-regular file. Good call on testing the parent directory!

I'm gonna close this as I don't think it is fixable via Singularity.
