### ISSUE TITLE
[[question]] How work the  starter-suid in singularity 3.1?

### ISSUE THREAD

**Issue by al3x609** [apptainer/singularity#3434]
Im running a shell inside a container with:

`singularity shell --nv -e --no-privs base.sif base`
then, I run a script, it works fine, but, Why I have six starter-suid process without child process?
![image](https://user-images.githubusercontent.com/4086644/56872555-efa24480-69ef-11e9-9cf2-a9429c2702e6.png)

My specs:

GPU: ngrid k2, two cores, 
GPU, Xeon, six cores.
singularity version: 3.1

thanks,

**Comment by cclerget** [comment]
Hi @al3x609 , which command display this ? I think it counts the OS threads spawned by Go

Edit: `pstree` report the number of threads, `pstree -T` will show only parent process

**Comment by al3x609** [comment]
hi @cclerget , thanks for your explication, this solve my issue.
