### ISSUE TITLE
enable mksquashfs format compression options  at build time.

### ISSUE THREAD

**Issue by EricDeveaud** [apptainer/singularity#3437]
## Version of Singularity: 3.1.0

related to #1456

one of our user  provided us an image built with singularity-3.1.0 built with squashfs with default mksquasfs compression method xz 

1) will it be possible for him  pass the -comp option to mksquasfh at build time in order to build gzip compressed images instead of xz one ?

rebuild mksquashfs with COMP_DEFAULT=gzip will not be the ideal solution ;-)

as stated on the doc:  https://www.sylabs.io/guides/3.0/user-guide/build_a_container.html
```
Beware that it is possible to build an image on a host and have the 
image not work on a different host. This could be because of the default 
compressor supported by the host. For example, when building an image on 
a host in which the default compressor is |xz| and then trying to run 
that image on a CentOS 6 node, where the only compressor available is 
|gzip|.
```

allowing "containers creator" to choose the compression format for the image will be a nice addition 

regards

Eric

**Comment by ikaneshiro** [comment]
Hey @EricDeveaud, I am actually in the process of creating checks that ensure `mksquasfs` will use `gzip` compression to prevent these types of issues in the future. Since `gzip` is the most widely supported compression type, this should allow images to be as usable between hosts as possible
