### ISSUE TITLE
discussion: opts pattern in e2e testing functions

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3440]
Currently, we setup a detailed struct to handle options for various operations which mimic `singularity` commands.

For example:

```
// ExecOpts define options for singularity actions
type ExecOpts struct {
	Binds     []string
	Security  []string
	Overlay   []string
	DropCaps  string
	Home      string
	Workdir   string
	Pwd       string
	App       string
	KeepPrivs bool
	Contain   bool
	NoHome    bool
	Userns    bool
}
```

I would like to discuss what value these are adding, because I'm having a hard time understanding why they are needed.

I see a few things that are problematic with them, such as the need for maintenance.

I wonder if passing an array of the actual options (`--bind`) instead of a struct of bools that are than converted to the options (opts.Bind = 1) is a better choice here since it will remove a lot of code that we don't need to maintain.

**Comment by gvallee** [comment]
I believe that this is not relevant anymore. Also, I check the code and this is not used anywhere right now.

@jscook2345 I suggest that we just remove it, as well as `ImageExec()`. Instead, we can just continue to use `RunSingularity()`, which is more generic.

**Comment by jscook2345** [comment]
@gvallee 

I agree I think this has aged out.
