### ISSUE TITLE
the failfast go test option runs all packages found even if the first package fails

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3444]
`-failfast flag doesn’t have any effect on ./...`

Do we want to keep running all the packages after one fails or should we stop there?

**Comment by ArangoGutierrez** [comment]
we want to fail fast on the unit tests, and not fail fast on the e2e

**Comment by ivan-ru** [comment]
would love this feature

**Comment by dtrudg** [comment]
We have stopped using the failfast flag at all, as it was causing headaches having incomplete failure reports when tracking down issues,
