### ISSUE TITLE
don't run unit tests when changing documentation

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3445]
Don't run unit tests when updating documentation.

**Comment by ArangoGutierrez** [comment]
we have a lot of issues related to running test depending on the git diff, we should create a big issue around that 
> test only git diff

;)

**Comment by jscook2345** [comment]
Agreed. But this allows us to check off a few items at a time!

**Comment by ArangoGutierrez** [comment]
yup, small batch tasks 
*nods*
