### ISSUE TITLE
--remote flag keeps hanging 

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3448]
## Version of Singularity:

3.2 rc2

### Expected behavior

A SIF should have been created.

### Actual behavior

No output, only the cursor blinking 

### Steps to reproduce behavior

singularity build --remote a.sif lolcow.def

**Comment by jscook2345** [comment]
@sushma-98 Is this still a problem? Could you ping me on slack so we can debug it?

**Comment by sushma-4** [comment]
I just checked and its working fine with SylabsCloud remote
But I have another remote pointing to the StagingCloud
And the issue - command not giving any output is only pertaining to the StagingCloud

**Comment by jscook2345** [comment]
@sushma-4 

What command are you running?

**Comment by jscook2345** [comment]
@GodloveD

**Comment by GodloveD** [comment]
Seems screwed up in production too.

**Comment by sushma-4** [comment]
> @sushma-4
> 
> What command are you running?

Yes, seems like its not working with [SylabsCloud] remote anymore. I was previously able to build using the below command after `remote login SylabsCloud`, but now I see error:

$ singularity build --remote test.sif lolcow.def
FATAL:   While performing build: failed to stream output from remote build service: websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by dtrudg** [comment]
Remote builder issues have been addressed server side, and should be more reliable now.
