### ISSUE TITLE
test-plugin should probably do something when its called

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3451]
## Version of Singularity:

3.2.0rc2

The `test-plugin` in the `examples/plugins` directory should probably do something when it is executed. Even if that something is just to print a message. Right now it just prints a `usage` statement, so I can't tell if its working by looking at the output.

```
$ singularity plugin list
ENABLED  NAME
    yes  sylabs.io/test-plugin
$ singularity test-cmd
Usage:
  singularity [global options...] test-cmd [args ...]

Run 'singularity test-cmd --help' for more detailed usage information.
```

**Comment by sashayakovtseva** [comment]
Will be closed in #4495 as well
