### ISSUE TITLE
improve plugin help 

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3454]
## Version of Singularity:

3.2.0rc2

The help for the `plugin` command group could be improved. I will go ahead and open a PR for this for 3.3.0.

**Comment by sashayakovtseva** [comment]
@jscook2345 Can you elaborate what exactly should be improved? Assuming we are using current master branch.

**Comment by jscook2345** [comment]
A few things.

1. It would be nice if we linked to our docs on plug-ins so users can read more.
2. The `Description` is incomplete.
3. The `Examples` are not very useful.
