### ISSUE TITLE
example plugin outputs during singularity run

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3457]
## Version of Singularity:

3.2.0rc2

I was not expecting the example plugin to have a hook into the `run` command. It did not appear to have that anywhere in the plugin source, but it still seems to output during that command.

```
$ ./ms.sif
Calling back into plugin!
Received flag value: TEST_VALUE_DEFAULT
Hello World!

$ singularity run ms.sif
Calling back into plugin!
Received flag value: TEST_VALUE_DEFAULT
Hello World!
```

**Comment by sashayakovtseva** [comment]
@jscook2345 Plugins where applied to all commands in action group. 
This will be fixed in #4495
