### ISSUE TITLE
Figure out why CircleCI fails with some privileged test cases

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3463]
## Version of Singularity:

Master

### Expected behavior

CircleCi should succeed like all other configurations I tried.

### Actual behavior

CircleCI will fail when uncommenting and executing `TestPrivilegedAuthorizedGroup` and `TestRootAuthorizedOwner` privileged cases
from https://github.com/sylabs/singularity/blob/master/pkg/image/image_test.go

### Steps to reproduce behavior

Uncomment the two cases, commit and push. CircleCI will systematically fail with a cryptic error message. I cannot reproduce the problem with any other configuration.

**Comment by ArangoGutierrez** [comment]
+1
