### ISSUE TITLE
Failed to mount squashfs image in (read only): No such device

### ISSUE THREAD

**Issue by jonathonl** [apptainer/singularity#3465]
## Version of Singularity:

2.6.1-dist

### Expected behavior

I built an image on GCP instance and then copied image to shared cluster in hopes to run exec. Both the build machine and the exec machine are using the same version of singularity.

### Actual behavior

Running `singularity exec <image.sif> ls` produces `ERROR  : Failed to mount squashfs image in (read only): No such device`. The tail of verbose mode looks like:
```
DEBUG   [U=0,P=72054]      singularity_priv_escalate()               Clearing supplementary GIDs.
DEBUG   [U=0,P=72054]      singularity_image_bind()                  Setting loop device flags
DEBUG   [U=0,P=72054]      singularity_priv_drop()                   Dropping privileges to UID=114117593, GID=1007 (6 supplementary GIDs)
DEBUG   [U=0,P=72054]      singularity_priv_drop()                   Restoring supplementary groups
DEBUG   [U=114117593,P=72054] singularity_priv_drop()                Confirming we have correct UID/GID
VERBOSE [U=114117593,P=72054] singularity_image_bind()               Using loop device: /dev/loop0
VERBOSE [U=114117593,P=72054] singularity_image_squashfs_mount()     Mounting squashfs image: /dev/loop0 -> /var/lib/singularity/mnt/container
ERROR   [U=114117593,P=72054] singularity_image_squashfs_mount()     Failed to mount squashfs image in (read only): No such device
ABORT   [U=114117593,P=72054] singularity_image_squashfs_mount()     Retval = 255
``` 
The image works as expected on machine that built it.

This issue is similar to #1213, but I'm not running anything from inside a docker container.

### Steps to reproduce behavior

Build command:
```
sudo /usr/bin/singularity build test.sif test.def
```

Build definition file:
```
Bootstrap: shub
From: singularityhub/ubuntu

%post
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    apt -y update
    apt -y install build-essential \
        git

%environment
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

Exec command:
```
singularity exec test.sif ls
```

**Comment by cclerget** [comment]
Hi @jonathonl , is the image was built with singularity v2 or singularity v3 ? Because images built with v3 can't be used with v2

**Comment by jonathonl** [comment]
Yes, I'm using the same version to build the image as I am to run the image.

**Comment by jonathonl** [comment]
I had the sysadmin of the local cluster install the latest version (3.2.0-rc1.392.g130b832), and I get a similar error message:

```
$ singularity --debug exec library://sylabsed/examples/lolcow cowsay "Fresh from the library" 2>&1 | tail
VERBOSE [U=1007,P=115146]  addCwdMount()                 Not mounting CWD within operating system directory: /
DEBUG   [U=1007,P=115146]  addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=1007,P=115146]  addResolvConfMount()          Adding /etc/resolv.conf to mount list
VERBOSE [U=1007,P=115146]  addResolvConfMount()          Default mount: /etc/resolv.conf:/etc/resolv.conf
DEBUG   [U=1007,P=115146]  addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=1007,P=115146]  create()                      Mount all
DEBUG   [U=1007,P=115146]  mountGeneric()                Mounting tmpfs to /usr/local/var/singularity/mnt/session
DEBUG   [U=1007,P=115146]  mountImage()                  Mounting loop device /dev/loop0 to /usr/local/var/singularity/mnt/session/rootfs
DEBUG   [U=1007,P=115146]  CleanupContainer()            Cleanup container
FATAL   [U=1007,P=115146]  Master()                      container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount squashfs filesystem: no such device
```

It  appears to be choking when `Mounting loop device /dev/loop0 to /usr/local/var/singularity/mnt/session/rootfs`.

**Comment by cclerget** [comment]
@jonathonl what is the output of `cat /proc/filesystems|grep squashfs` ? If it returns `squashfs`, it would mean that the compression format used by squashfs on your build machine is not supported and/or configured by the kernel on cluster. Maybe `dmesg` output can give some pointer too

**Comment by jonathonl** [comment]
Actually, /proc/filesystems does not contain squashfs. I assume squashfs needs to be supported and enabled. I'm running on Ubuntu 16.04.6 LTS. Does this require a kernel patch, or is there an easier way to get squashfs enabled?

**Comment by jonathonl** [comment]
Enabling squashfs solved the problem.

**Comment by tashrifbillah** [comment]
@jonathonl , how did you enable squashfs on Linux?

**Comment by jonathonl** [comment]
I believe it is enabled by default on modern kernels, but the Sys Admin of the environment I was testing on had manually disabled it. I'm not sure what steps are required to reenable.

**Comment by tashrifbillah** [comment]
It came enabled in `sylabs/singularity-3.2-ubuntu-bionic64`, but still I have the issue you faced.

**Comment by jmstover** [comment]
squashfs is a kernel module. An admin can load it with:

```
modprobe squashfs
```

This is assuming that they do not have the module blacklisted, or the kernel module missing.

But squashfs support is something that must exist in the Host kernel.
