### ISSUE TITLE
remote login command should create ~/.singularity if it doesn't exist

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#3472]
## Version of Singularity:

3.2.0-rc1.204.gb50f8b2

### Expected behavior

I've just installed Singularity and this is the first thing I do:

```
[vagrant@localhost ~]$ singularity remote login SylabsCloud
Generate an API Key at https://cloud.sylabs.io/auth/tokens, and paste here:
API Key:
INFO:    API Key Verified!
```

### Actual behavior

I've just installed Singularity and this if the first error I see:

```
[vagrant@localhost singularity]$ singularity remote login SylabsCloud
FATAL:   while opening remote config file: open /home/vagrant/.singularity/remote.yaml: no such file or directory
```

A `mkdir ~/.singularity` seems to correct the issue.

**Comment by jscook2345** [comment]
I think running `singularity` at any point should verify this directory exists, and if not, create it with default contents.
