### ISSUE TITLE
remove container from library via CLI

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#3473]
## Version of Singularity:

3.2.0-rc1.204.gb50f8b2

### Expected behavior
```
$ singularity delete library://some/thing/misguided
Are you sure you want to delete library://some/thing/misguided? [y/N] y
Deleting library://some/thing/misguided... done!

$ singularity delete --force library://some/thing/else
Deleting library://some/thing/else... done!
```
### Actual behavior

Only exists in my fevered imagination.  

### Steps to reproduce behavior

Try it... and you will see... NOTHING!!

**Comment by dtrudg** [comment]
Note - this needs to consider `--arch` as well, now that we can have multiple images (for different architectures) per tag.
