### ISSUE TITLE
instance stop with a glob does not work

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3487]
```
$ singularity instance stop al*
FATAL:   no instance found
$ singularity instance stop alp
Stopping alp instance of /home/justin/instance/alpine_latest.sif (PID=8974)
```

I thought `al*` would match `alp` and stop that instance. Is the glob meant for another feature?

**Comment by cclerget** [comment]
@jscook2345 I think in this case shell glob behaviour is the issue, can you try with `"al*"` instead ?

**Comment by jscook2345** [comment]
@cclerget 

You are correct. I forgot about the shell expansion. Sorry about that!
