### ISSUE TITLE
additional options for building e2e tests

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3500]
It would be good if it were easier to run the e2e tests with some different options.

For example:

debug: `singularity -d` for all commands executed
filter: `go test -run '^Filter'`
verbose: `go test -v`

I imagine there could be more. Not sure where best to add these each yet, but it should be a part of the work we do!

**Comment by mem** [comment]
You can pass `-args` to `go test` and that will be passed to the test program:

```
go test -v -run SomeThing -tags "some tags" -args -this -is -passed -to the program
```
