### ISSUE TITLE
create more tags for different test categoriezation

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3501]
We should create a list of tags that can be used for categorizing our tests. Things similar to what we use for our build would be great (seccomp, overlayfs, user_namespace, etc)!

Additionally, I think things like 'network', 'additional privileges', etc may also be good since they are a resource we may not need to or cannot test.

How the use of the tags are implemented does not really matter at this point.

**Comment by dtrudg** [comment]
Has been approached with the `requires` functions rather than separating into files and tagging
