### ISSUE TITLE
sudo required for building sandbox

### ISSUE THREAD

**Issue by jeffcbecker** [apptainer/singularity#3513]
## Version of Singularity:

3.1.1

### Expected behavior

$ singularity build --sandbox lolcow/ lolcow.sif

works without requiring sudo

### Actual behavior

$ singularity build --sandbox lolcow/ lolcow.sif             
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
ERROR:   unpackSIF Failed: While copying partition data to bundle: permission denied
FATAL:   While performing build: packer failed to pack: While copying partition data to bundle: permission denied

### Steps to reproduce behavior

See above. The question is "why is sudo required to build sandbox images?" The goal for these images is for users to run them using user namespaces without root.

**Comment by jmstover** [comment]
@jeffcbecker You need root when building from a SIF file, as you're doing, as the image needs to be mounted. There was a recent PR that removes this restriction, and I _believe_ that is to be included in the 3.2.0 release.

Can you try this with 3.2.0-rc2 and see if you get the same error?

**Comment by jeffcbecker** [comment]
On Tue, May 7, 2019 at 4:48 PM Jason Stover <notifications@github.com>
wrote:

> @jeffcbecker <https://github.com/jeffcbecker> You need root when building
> from a SIF file, as you're doing, as the image needs to be mounted. There
> was a recent PR that removes this restriction, and I *believe* that is to
> be included in the 3.2.0 release.
>
> Can you try this with 3.2.0-rc2 and see if you get the same error?
>

Downloaded 3.2.0-rc1 tarball, and built singularity. It works. Thanks.

**Comment by jmstover** [comment]
👍
