### ISSUE TITLE
Not valid linux epoch time on createdAt and startedAt fields on oci state of a bundle

### ISSUE THREAD

**Issue by jchavezlavalle** [apptainer/singularity#3515]
## Version of Singularity:

singularity version 3.2.x

### Actual behavior

When checking the state of an oci bundle:

```sh
$ sudo singularity oci state ubu3
{
	"ociVersion": "1.0.1-dev",
	"id": "ubu3",
	"status": "running",
	"pid": 2911,
	"bundle": "/home/joana/ubuntu",
	"createdAt": 1557320397853233476,
	"startedAt": 1557320409600141738,
	"attachSocket": "/root/.singularity/instances/oci/ip-172-31-90-64.ec2.internal/root/ubu3/attach.sock",
	"controlSocket": "/root/.singularity/instances/oci/ip-172-31-90-64.ec2.internal/root/ubu3/control.sock"
}
```

The `createdAt` and `startedAt` fields are not valid times on linux epoch time: 

```sh
$ date -d @1557320397853233476
date: time 1557320397853233476 is out of range
```
To notice that, if considering only the first ten digits of this number, the date is correct.

```sh
$ date -d @1557320397
Wed May  8 12:59:57 UTC 2019
```

### Expected behavior

To have the same state as seen before but with valid epoch times.

**Comment by cclerget** [comment]
@devprincess Time is reported to respect RFC3339Nano, Singularity CRI (K8S behind the scene) requires this format to report nanosecond since 1970/01/01 instead of second. Is it a blocking issue ?

**Comment by jchavezlavalle** [comment]
not a blocking issue, if this is how it is expected to be then feel free to close the issue, thanks @cclerget :+1:
