### ISSUE TITLE
running singularity exec programmatically from a bash script

### ISSUE THREAD

**Issue by alipourm** [apptainer/singularity#3521]
## Version of Singularity: 3.0.1-1.el7
I want to execute a command in various images. I use a simple for bash loop. 
for i in `ls gcc-images/*.sif`
do
    singularity exec $i cat /etc/os-release
done
 
### Expected behavior
I expect the script to print the os-release information for ALL images in that directory.

### Actual behavior
Instead, it prints the information of the first one and it returns the prompt. If I run `fg` command the command in the next image is executed, and so on. For n image, I have to run `fg` command n-1 times. 

Interestingly, if I replace the command with `timeout 10 singularity exec $i cat /etc/os-release`, it would continue but it would not run the command inside the container!

### Steps to reproduce behavior

run the above script on some sif files.

**Comment by cclerget** [comment]
Hi @alipourm , I think this issue was fixed in more recent releases, I would suggest to try with https://github.com/sylabs/singularity/releases/tag/v3.2.0-rc2 release and see if it fixes the issue.

**Comment by alipourm** [comment]
Hi @cclerget, thanks! Is there any work-around for this? I'm using a server, and I am not sure if the admins would want to upgrade the software.

**Comment by cclerget** [comment]
@alipourm No workaround. Between I tested with 3.0.3 and the issue was fixed with this version, but I would not recommend to use early v3 releases in production because they contains issues. If you can convince your admins to at least install more stable release like 3.1.

**Comment by jscook2345** [comment]
@alipourm 

I'm closing this issue for now. If you still have questions please let us know! Thanks!
