### ISSUE TITLE
singularity should either fulfil user requests or fail

### ISSUE THREAD

**Issue by EvanTheB** [apptainer/singularity#3530]
## Version of Singularity:

singularity version 3.0.2-1.el7.centos

### Expected behavior

When a user requests something, singularity should either fulfil the request or fail (exit quickly with an error code). This should apply in general, but specifically I have noticed this is an issue for mounts.

### Actual behavior

Specifically for mounts, some versions print a warning, some versions just silently do not mount. 

### Steps to reproduce behavior

```bash
# should not run ls, should fail with message 'cannot mount /tmp/fake_file'
singularity exec -C --bind /tmp/fake_file docker://debian ls /tmp/fake_file

# If the current empty home mount is the intended behaviour (dubious), should fail with message 'Cannot mount in previously mounted directory'. 
singularity exec -C --bind "$HOME" docker://debian ls "$HOME/.bashrc"
```

**Comment by cclerget** [comment]
Hi @EvanTheB , early version probably didn't display a warning about that, have you try with more recent releases like 3.1.0 or 3.2.0-rc2 ?

**Comment by EvanTheB** [comment]
@cclerget Indeed the latest version does have different behaviour.

singularity version 3.2.0-rc2

Good, now -C and bind $HOME seems to work:
```bash
> singularity exec -C --bind "$HOME" docker://debian ls "$HOME/.bashrc"
/home/evaben/.bashrc
```

Good, when there is an error, it is an error and singularity stops:
```bash
> singularity exec -C --bind "$HOME"/.bashrc docker://debian ls -la
FATAL:   container creation failed: mount ->/home/evaben/.bashrc error: can't remount /home/evaben/.bashrc: no such file or directory
```
Although not clear to me what has failed or why, at least singularity is terminating instead of blindly soldiering on.


This is still broken:
```bash
> singularity exec -C --bind /fake_file docker://debian ls /fake_file
WARNING: skipping mount of /fake_file: no such file or directory
ls: cannot access '/fake_file': No such file or directory
```

**Comment by EvanTheB** [comment]
@cclerget the patch seems like an improvement (not failing silently), but still very strange ux IMO.

```
~/go/src/github.com/sylabs/singularity/builddir/singularity version
3.4.0-246.g5e08a99da

evaben@evaben ~ [255]> cd /
evaben@evaben /> ~/go/src/github.com/sylabs/singularity/builddir/singularity shell -C --bind ~/.ssh/ docker://debian
FATAL:   container creation failed: mount ->/home/evaben/.ssh error: can't remount /home/evaben/.ssh: no such file or directory
```

Files still cannot be mounted in a clean homedir?

EDIT: apologies, I was on the wrong version when I tested. It is looking pretty good. Is is still impossible to mount in a clean homedir?
