### ISSUE TITLE
any tests which pull from unofficall sources should instead pull from us

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3546]
There are a few tests that pull from `dctrud`, for example. These should be migrated to our own hubs and maintained there.

While @dctrud is a great person, we should not force him to keep our tests working and in shape ;)

**Comment by dtrudg** [comment]
I've neeeeeearly deleted something relevant by accident at least once, so that's probably wise @jscook2345 :-)

**Comment by dtrudg** [comment]
NB - to save clicking through a bunch of links, the Dockerfiles are at:

https://github.com/dctrud/docker-singularity-userperms
https://github.com/dctrud/docker-aufs-sanity

**Comment by dtrudg** [comment]
Closed these in https://github.com/hpcng/singularity/pull/5358
