### ISSUE TITLE
sudo make install UX issue with go path

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#3547]
## Version of Singularity:

3.2.0

### Expected behavior

If go is required to be in the root PATH (and if the GOPATH needs to be set in that environment) please specify it in the install docs or provide a clear error message. If not, please make sure 'make install' does not throw the following error.

### Actual behavior

go dependency resolver throws an error complaining that go is not in the root's PATH when running 'sudo make install' in the user environment with sudo access, go in the PATH, and GOPATH set as required for the singularity build build.

### Steps to reproduce behavior

See above

**Comment by moskalenko** [comment]
$ sudo make install
[sudo] password for builder: 
which: no go in (/sbin:/bin:/usr/sbin:/usr/bin)
/opt/singularity/src/github.com/sylabs/singularity/makeit/gengodep: line 6: go: command not found
/opt/singularity/src/github.com/sylabs/singularity/makeit/gengodep: line 6: go: command not found

**Comment by jscook2345** [comment]
This should not be happening. I will take look and see about fixing it. Thanks ro the report @moskalenko !
