### ISSUE TITLE
Singularity documentation: please specify defaults for environment variables

### ISSUE THREAD

**Issue by mgjf** [apptainer/singularity#3552]
## Version of Singularity:

3.1, 3.2 documentation on https://www.sylabs.io/guides/3.2/user-guide/

### Expected behavior

It would be nice to have the defaults of environment variables (in particular SINGULARITY_CACHEDIR and SINGULARITY_TMPDIR) documented in places such as
https://www.sylabs.io/guides/3.2/user-guide/appendix.html
or
https://www.sylabs.io/guides/3.2/user-guide/build_env.html

### Actual behavior

Defaults for some variables are not documented, so users need to guess / experiment to find out a) what are the defaults, and b) which directory components Singularity appends to the values of these variables if they are set.

### Steps to reproduce behavior

Take for example the description in [buid_env.html](https://www.sylabs.io/guides/3.2/user-guide/build_env.html#cache-folders): if I set SINGULARITY_CACHEDIR to /my/dir, it is not evident if Singularity will put cache contents into /my/dir/.singularity/cache/{library,oci,oci-tmp} or into /my/dir/{library,oci,oci-tmp}. Similarly for SINGULARITY_TMPDIR. Also, will Singularity try to mkdir -p a missing prefix? Will Singularity use TMPDIR if this is set, but SINGULARITY_TMPDIR is not set?

In [appendix.html](https://www.sylabs.io/guides/3.2/user-guide/appendix.html#singularity-s-environment-variables)  the defaults for these (and some other) variables are also not documented.

**Comment by GodloveD** [comment]
Issue moved to [sylabs/singularity-userdocs #170](https://github.com/sylabs/singularity-userdocs/issues/170) via [**ZenHub**](https://www.zenhub.com/)

**Comment by GodloveD** [comment]
Thanks for the idea @mgjf.  I just moved this issue to the singularity-userdocs repo.  I think it will get more attention there.
