### ISSUE TITLE
Modify recipe without restarting entire build

### ISSUE THREAD

**Issue by vitchyr** [apptainer/singularity#3561]
## Version of Singularity:

2.6.1-dist

### Expected behavior

If I modify a Singularity recipe, I'd like for the build process to work off the the last layer that wasn't modified. Docker supports this, so that you can easily modify the last few lines in a Dockerfile without having to re-run the entire build process. Is there something similar?

I understand that one can [build a singularity image in an interactive way](https://www.sylabs.io/guides/2.6/user-guide/singularity_flow.html#singularity-flow), but is there a way to make the creation of a recipe faster?

### Actual behavior

Singularity restarts the build from scratch.

### Steps to reproduce behavior

1. `sudo singularity build tmp.simg Singularity`
2. Modify last line of `Singularity` file
3.  `sudo singularity build tmp.simg Singularity` --> build starts from scratch

**Comment by GodloveD** [comment]
You can build a Singularity container from an existing container on disk.  So you could build your base container and save it and then modify the def file to build from the existing container to save time while you prototype.  

But since Singularity does not create layers there is really no way to implement this as Docker does.

**Comment by vitchyr** [comment]
> You can build a Singularity container from an existing container on disk.

Is there a reference in the documentation for this? I only see recipe examples building off of docker images.

> But since Singularity does not create layers there is really no way to implement this as Docker does.

I know this would take a while, but are there any plans to support this in the future?

**Comment by GodloveD** [comment]
Heya @vitchyr!  Just out of curiosity, where are you looking at documentation?  There are a few different places around to find info about Singularity and it's cool to know where people are looking.  

[Here](https://www.sylabs.io/guides/2.6/user-guide/appendix.html#build-localimage) is some info about building from a local disk image.  And [here](https://www.sylabs.io/guides/2.6/user-guide/build_a_container.html) is some general info about building that you also might find useful.  

As for supporting this through layers, no there are no plans to implement layers in Singularity.  The singularity image format (SIF) has a lot of advantages over the layered tarball format adopted by most container platforms.  It's one of the main features of Singularity and I don't think there is any desire to change it.  

Please feel free to keep this thread going if you have any more questions or comments.  It's fun to discuss.  😸

**Comment by vitchyr** [comment]
@GodloveD Thanks for the pointers! You're right--the documentation does talk about it. I foolishly skipped to the "Secions" part of [Container Recipes](https://www.sylabs.io/guides/2.6/user-guide/container_recipes.html#sections) and looked at the examples, missing the beginning where they talk about the other Bootstrap mechanisms.

I was also looking at the [Singularity Flow](https://www.sylabs.io/guides/2.6/user-guide/singularity_flow.html) portion, and from there, it got me thinking about whether or not there were more interactive but recipe-centric ways of building containers.

> As for supporting this through layers...

Makes sense! Thanks for confirming this.
