### ISSUE TITLE
Cleanup configuration and defaults

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#357]
The current configuration subsystem is fairly brittle.  Ideas to make it more robust
1.  The "default value" of a parameter is in both the code and the configuration file.  Updates must be applied to both places (we've had cases where this was forgotten).  We could have the defaults in a central place in the code and have the config file be generated from the code.
2.  The defaults and the local configuration are in the same file.  That means any admin with non-standard configuration won't get updates.   A more traditional setup would be to split the two and have an `#include` command of some sort.
3.  Any time we want to read out a config value, we must call `rewind` on the file descriptor.  This is brittle: there's nothing stopping us from forgetting to call the mandatory rewind.  At the minimum, we should move the rewind to be inside the configuration `get_value` call; likely, we should parse everything to a hash table and just use values from the hash.

**Comment by bbockelm** [comment]
@bauerm97 - this is a placeholder ticket for the cleanup we discussed earlier today.

**Comment by bauerm97** [comment]
>  likely, we should parse everything to a hash table and just use values from the hash.

+1 for parsing the entire config file one time, then caching it for quicker access. Currently we have to rewind the file for any parsing, which greatly increases the time it takes for us to parse an arbitrary amount of scattered config options.

**Comment by gmkurtzer** [comment]
I've also been thinking about doing this, it is needed. 

Can you add elaborate on the #include command option?

Btw, rewind outside get_value is necessary for parsing things like multiple 'bind path' entries. We have to make sure that the new parser can handle multiple entries within the hash table.

**Comment by vsoch** [comment]
I'll just add that the (current) configuration file is very well documented :) :clap:

**Comment by bbockelm** [comment]
@gmkurtzer - the `#include` (or similar) is to help with configuration management and deploys.

Basically, I want admins to be able to put all their changes in a separate file.  That way, we are guaranteed that upgrades ship a clean set of defaults.

Right now, at non-trivial sites, I'd expect any updated defaults are a no-op.
