### ISSUE TITLE
FATAL:   a setuid installation is required to join this instance

### ISSUE THREAD

**Issue by asmi10** [apptainer/singularity#3573]
## Version of Singularity:

3.2.0

I have build singularity 3.2 rpm using instruction https://www.sylabs.io/guides/3.2/user-guide/installation.html and installed it on SLES15 host as root user. If in case I create an instance and try to take shell/execute anything with instance then I get below error. I am running all commands as root account.

singularity instance list
INSTANCE NAME    PID      IMAGE
web1             15143    /infrastructure/singularity3.2/UBUNTU/nginx.sif

 singularity -vv shell instance://web1
VERBOSE: Set messagelevel to: 4
VERBOSE: Container runtime
VERBOSE: Check if we are running as setuid
VERBOSE: Spawn stage 1
VERBOSE: Execute stage 1
FATAL:   a setuid installation is required to join this instance
VERBOSE: stage 1 exited with status 255

I have setuid enabled in singularity configuration file, also I do not have nosuid option set on filesystem level.

**Comment by cclerget** [comment]
Hi @asmi10 , looks like `starter-suid` doesn't have setuid bit or setuid bit has no effect, could you paste output with debug enabled : `singularity -d shell instance://web1` to check if setuid workflow works

**Comment by asmi10** [comment]
ls -la /usr/lib/singularity/bin/starter-suid


-rwsr-xr-x 1 root root 11865424 May 16 10:49 /usr/lib/singularity/bin/starter-suid
:~# singularity instance list
INSTANCE NAME    PID      IMAGE
web1             15143    /infrastructure/singularity3.2/UBUNTU/nginx.sif
:~# singularity -d shell instance://web1
VERBOSE [U=0,P=486]        print()                       Set messagelevel to: 5
DEBUG   [U=0,P=486]        init()                        PIPE_EXEC_FD value: 7
VERBOSE [U=0,P=486]        init()                        Container runtime
VERBOSE [U=0,P=486]        is_suid()                     Check if we are running as setuid
DEBUG   [U=0,P=486]        init()                        Overlay seems supported by kernel
DEBUG   [U=0,P=486]        init()                        Read json configuration from pipe
DEBUG   [U=0,P=486]        init()                        Set child signal mask
DEBUG   [U=0,P=486]        init()                        Wait completion of stage1
DEBUG   [U=0,P=492]        set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=492]        init()                        Spawn stage 1
VERBOSE [U=0,P=492]        startup()                     Execute stage 1
DEBUG   [U=0,P=492]        Stage()                       Entering stage 1
FATAL   [U=0,P=492]        Stage()                       a setuid installation is required to join this instance
VERBOSE [U=0,P=486]        init()                        stage 1 exited with status 255

**Comment by cclerget** [comment]
@asmi10 Sorry I thought you run it as user not root. So looks like an issue with the recent security patch. Will submit a fix soon

**Comment by asmi10** [comment]
ok, Thanks. I also assumed so.

**Comment by al3x609** [comment]
I have the same this issue, singularity version master branch 3.2

**Comment by asmi10** [comment]
@cclerget Have the fix been already released for this issue or is it still in progress?

**Comment by cclerget** [comment]
@asmi10 Will submit fix very soon today

EDIT: see #3586
