### ISSUE TITLE
Is there any open source version of sylabs container library available ?

### ISSUE THREAD

**Issue by asmi10** [apptainer/singularity#3580]
## Version of Singularity:
singularity 3.2

I am not sure where can I post such question, so adding it here. I have SIF image prepared with PGP encryption and I am looking for some open source registry solution to host images. I am aware there is sylabs container library for hosting such encrypted image but not sure if sylabs has open source version of it.

**Comment by al3x609** [comment]
Ye,s [singularity hub](https://singularity-hub.org/), a great work of @vsoch

**Comment by asmi10** [comment]
Actually I am looking for open source version of sylabs container library where I can store encrypted and signed images.

**Comment by vsoch** [comment]
You can host your own images using [Singularity Registry Server](https://github.com/singularityhub/sregistry). If the images are signed on your host, they will be signed when you push, of course. The registry doesn't have an endpoint to push keys to, but that could be added given substantial interest (the idea has [come up before](https://github.com/singularityhub/sregistry/issues/169)), and it's open source, so contributions can come in from all fronts!

I can't speak for Sylabs, but I remember them mentioning a self-hosted version of their library is underway. I don't believe this would be open source, but something provided as a service on premise.

**Comment by asmi10** [comment]
Ok, thanks for the feedback. I will give it a try to singularity registry server.

**Comment by rherban** [comment]
At the moment, an on-prem version of the Singularity Container Services (SCS) is being planned, but not as an open-sourced project.  It will be part of our Enterprise offerings.
