### ISSUE TITLE
[python] [docker] has function that is no longer supported for dict?

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#359]
@flx42 I think this error relates to an addition you made:

	Traceback (most recent call last):
	  File "/usr/local/libexec/singularity/python/cli.py", line 280, in <module>
	    main()
	  File "/usr/local/libexec/singularity/python/cli.py", line 218, in main
	    auth=auth)
	  File "/usr/local/libexec/singularity/python/docker/api.py", line 190, in get_manifest
	    auth=auth)
	  File "/usr/local/libexec/singularity/python/docker/api.py", line 77, in get_token
	    if response.code != 401 or not response.headers.has_key("WWW-Authenticate"):
	AttributeError: 'HTTPMessage' object has no attribute 'has_key'

I think [has key was removed](https://docs.python.org/3.1/whatsnew/3.0.html#builtins)?

**Comment by vsoch** [comment]
Just to confirm is python version - switching to 2:

       vanessa@vanessa-ThinkPad-T460s:~/Desktop$ which python
	/home/vanessa/anaconda2/bin/python
	vanessa@vanessa-ThinkPad-T460s:~/Desktop$ singularity run docker://ubuntu:latestCache folder set to /home/vanessa/Desktop/docker
	Downloading layer sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
	Extracting /home/vanessa/Desktop/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
	Downloading layer sha256:8ff6f8a9120c54ae6ebde4bea1a4f2bc8170d4a148f5f81eb731be74a071d71e
	Extracting /home/vanessa/Desktop/docker/sha256:8ff6f8a9120c54ae6ebde4bea1a4f2bc8170d4a148f5f81eb731be74a071d71e.tar.gz
	Downloading layer sha256:cd3d6cd6c0cff04046b5cfc3688e599e56efe9abe35ff59c36fcf469eb289f81
	Extracting /home/vanessa/Desktop/docker/sha256:cd3d6cd6c0cff04046b5cfc3688e599e56efe9abe35ff59c36fcf469eb289f81.tar.gz
	Downloading layer sha256:d1d48771f782fed22e5d31dcb03e8970796ec80c350f3544844b5c4e131b959a
	Extracting /home/vanessa/Desktop/docker/sha256:d1d48771

**Comment by flx42** [comment]
Good catch, thanks!

**Comment by vsoch** [comment]
np! It was very useful to bonk me in the head as a reminder to write some tests... going to work on those today :)
