### ISSUE TITLE
Improve cache management in the context of `DropPrivilege()` and `EnsurePrivilege()`

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3592]
## Version of Singularity:

Master.

### Expected behavior

When implementing unit tests, we should always use either `DropPrivilege()` or `EnsurePrivilege()`, which should provide a clean environment for every tests, including a clean image cache specific to the test.

### Actual behavior

`DropPrivilege()` and `EnsurePrivilege()` create a specific directory in `/tmp` that is used for the execution of a test. Furthermore, that directory is used as location for the image cache. At the moment, that directory is not entirely cleaned at the end a given unit tests and re-used by the next unit test to be executed. Using a directory for a unit test that is not empty increases the risk for failures and decrease the level of control over the execution of the tests.

### Steps to reproduce behavior

First execute `make testall`; then `ls -l /tmp/WithPrivilege` or `ls -l /tmp/WithoutPrivilege`, you can see an image cache from the unit tests.

**Comment by gvallee** [comment]
Since I am working on issue #3525 , I was able to add code to the unit tests to force the creation and use of a clean temporary image cache for each test that was failing, and I can confirm that it solves the failures I could see while running `make testall`.

I think the two questions to be answered are:
1. Do we want to always use the same directories for the unit tests, i.e., `/tmp/WithPrivilege` or `/tmp/WithoutPrivilege`? If so, should we ensure that the entire content of these directories is wiped out after the execution of every single unit tests? If no, do we want to rely on `ioutil.TempDir()` to create a unique temporary directory for each unit test, maybe using a `WithPriv` or `WithoutPriv` prefix to differentiate privileged and unprivileged unit tests?
2. Whichever option we choose in the previous point, do we want to give the option to test developers to create temporary clean image caches, instead of assuming that a cache is provided by default? It would help if unit tests end up using more than one cache.

**Comment by gvallee** [comment]
We should also check with people who worked on `DropPrivilege()` and `EnsurePrivilege()` (@cclerget?) what are the requirements for having predefined directories and reuse them instead of dynamically create these directories.

**Comment by gvallee** [comment]
Comment from @mem during a discussion: may we do not want these two functions to do anything about the cache because their names do not let developers know that it does anything about configuring the testing environment.
So the questions to answer are now:
1/ Should these two functions set anything regarding the test context, e.g., the cache location? If not do we want to have another function that would do that?
2/ How do we ensure that each unit test has its own temporary directory to work with so that there is no conflict when unit tests are running concurrently? (and we had the confirmation that they run concurrently)
2/ How do we want to clean up the environment, including the cache after the execution of a cache?

**Comment by tri-adam** [comment]
Agreed, I don't think these should be setting up anything to do with cache directories. Something like `SetCacheDir`/`CleanCacheDir` within the `test` package that could be used where necessary could be a clear way forward? This would give flexibility for each test to have its own (clean) cache dir. And it has the nice property of documenting the tests that rely on the cache dir.

**Comment by gvallee** [comment]
That works for me, I think it will address all the problems. I will prepare a PR and we can see the details from there.

**Comment by gvallee** [comment]
Something I discovered while working on this: some unit tests start in privileged mode (to simulate `sudo`) and then drop privilege to simulate execution as a non-privilege user. Tests tend to start as a privileged user, create the cache and then drop privileges. Based on this, I think that the correct way to deal with this is to make the cache readable by others.

**Comment by gvallee** [comment]
FYI, the reference to issue #3722 explains, i think, why static directories were initially used: thread-safety. The usage of `t.Run()` in unit tests means that changing the value of `SINGULARITY_CACHEDIR` is unsafe. By using static directories, It is also virtually unsafe to clean the cache.
