### ISSUE TITLE
Remote command flow

### ISSUE THREAD

**Issue by rherban** [apptainer/singularity#3597]
## Version of Singularity:

3.2+

### Expected behavior

- [ ] `singularity push` when not logged in should direct users to `singularity remote login` explicitly.  Currently it says `log in with singularity remote commands`

- [x] `singularity remote login` should use the default endpoint and optionally specify a different endpoint 

- [ ] `singularity remote add` should prompt for token after adding.  

- [x] All of the `singularity remote` help output incorrect lists subcommands, but they should be options.  
Current:   `singularity [global options...] remote <subcommand> login <remote_name>`
Expected: `  singularity [global options...] remote <options> login <remote_name>`

Related: #3540 

EDIT: Turned the list into check boxes to track what's been finished

**Comment by rherban** [comment]
Add global option to tips where appropriate

**Comment by ikaneshiro** [comment]
Note on point 4 to add `[options...]` for subcommands that contain options
