### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by rgov** [apptainer/singularity#3600]
## Version of Singularity:

fead83d0546a3a9f18c82137cee1c1a35a3f5d8d

Running on Ubuntu 18.04.2 with Go version go1.12.5 linux/amd64.

### Expected behavior

When I run the `go get -u -v github.com/golang/dep/cmd/dep` command in the cloned Singularity source directory, it should install the `dep` tool.

### Actual behavior

```
Fetching https://gotest.tools?go-get=1
Fetching https://rsc.io/letsencrypt?go-get=1
https fetch failed: Get https://gotest.tools?go-get=1: dial tcp 216.239.36.21:443: i/o timeout
go: gotest.tools@v2.3.0+incompatible: unrecognized import path "gotest.tools" (https fetch: Get https://gotest.tools?go-get=1: dial tcp 216.239.36.21:443: i/o timeout)
https fetch failed: Get https://rsc.io/letsencrypt?go-get=1: dial tcp 216.239.38.21:443: i/o timeout
go: rsc.io/letsencrypt@v0.0.1: unrecognized import path "rsc.io/letsencrypt" (https fetch: Get https://rsc.io/letsencrypt?go-get=1: dial tcp 216.239.38.21:443: i/o timeout)
go: error loading module requirements
```

When I run the command in another directory, it succeeds.

### Steps to reproduce behavior

Follow directions from [this page](https://www.sylabs.io/guides/3.2/user-guide/quick_start.html#clone-the-singularity-repository).

**Comment by rgov** [comment]
`gotest.tools` seems to be reachable by some networks but not mine, but `rsc.io` seems to be down [globally](https://downforeveryoneorjustme.com/rsc.io). Can these be installed from Github instead?

**Comment by jscook2345** [comment]
The latest version of `singularity` is built with modules, rather than using `dep`. If you just skip that step the installation process should work the same.

Please confirm that is the case and I will see about getting the docs fixed after that.

**Comment by rherban** [comment]
We've removed the `dep` requirement from one portion of the docs, but not the quick-start.  We'll get that taken care of.

**Comment by GodloveD** [comment]
Whoops.  Also the quickstart should remove gopath and stuff.

**Comment by mem** [comment]
The incorrect documentation has been removed, the best I can tell.
