### ISSUE TITLE
Unable to capture output on Singularity Desktop

### ISSUE THREAD

**Issue by chrisburr** [apptainer/singularity#3606]
## Version of Singularity:

Singularity Desktop version 3.2.0-rc2 on macOS

### Expected behavior

```bash
$ singularity run test-image.sif >/dev/null 2>&1
```
(This works as expected on Linux)

### Actual behavior

```bash
$ singularity run python/LbEnv/data/test-image.sif >/dev/null 2>&1                                                                                                                               (my-root)
Running singularity container sucessfully
[    1.239742] reboot: Power down
```

### Steps to reproduce behavior

Using a minimal container built from:
```bash
BootStrap: busybox
MirrorURL: https://www.busybox.net/downloads/binaries/1.26.1-defconfig-multiarch/busybox-x86_64

%runscript
    echo "Running singularity container sucessfully"
```

I don't think this is coming from my setup but if you can't reproduce it I can debug further.

**Comment by jmstover** [comment]
@chrisburr This is a known issue. We're attaching stdin/stdout etc... but for some reason redirects/pipes aren't working. Something along the execution chain is breaking the file descriptor handling, or we're not executing subprocesses correctly to actually handle the redirects correct in Go.

@bauerm97 @mem ... Is it possible that how we're attaching stdin/etc... is breaking the file descriptor handling? Neither redirector or pipes work correctly.

**Comment by chrisburr** [comment]
I'm a little out of my comfort zone here but from my original debugging it looked like singularity was trying to write to the tty of terminal rather than to stdout and stderr. I can make it fail using:

```bash
bash -itx -c 'singularity run python/LbEnv/data/test-image.sif && echo Done' > stdout.log 2> stderr.log
```
After running this `stderr.log` contains:
```bash
+ singularity run test-image.sif
bash: [66338: 2] tcsetattr: Inappropriate ioctl for device

[1]+  Stopped                 singularity run test-image.sif
```
I can also capture the output if I use this from Python:
```python
In [1]: import pexpect

In [2]: output = pexpect.run('singularity run python/LbEnv/data/test-image.sif')

In [3]: output
Out[3]: b'Running singularity container sucessfully with EXAMPLEVAR=\r\n[    1.241324] reboot: Power down\r\n'
```

**Comment by dtrudg** [comment]
Closing as Singularity Desktop currently not maintained.
