### ISSUE TITLE
Unable to start VS Code Portable inside a singularity image because of wrong permissions

### ISSUE THREAD

**Issue by rickstaa** [apptainer/singularity#3609]
## Version of Singularity:
singularity version 3.2.0-rc1.294.g1364a45b8

## Problem description
I am trying to install vs code inside a singularity image. I, unfortunately, haven't been able to do this as I keep running into some permission problems. I first tried to install vs code inside the container using the[ .dep package](https://code.visualstudio.com/Download). However, as inside this container, the *vs code* program doesn't have write permissions to the system *user data* and *data* folders it won't start and gives the following error:

![image](https://user-images.githubusercontent.com/17570430/58323976-d1303d00-7e25-11e9-9da5-5e54b9749f99.png)

To solve this I tried using the portable version as this is explained in the [vscode portable documentation](https://code.visualstudio.com/docs/editor/portable). I install the *VSCode* program using the following commands inside the `%post` section of the recipe file:

```
curl -L "https://go.microsoft.com/fwlink/?LinkId=723968" > vscode-insider.tar.gz
tar --no-same-owner -xvzf vscode-insider.tar.gz
cd ./VSCode-linux-64
mkdir data
chmod g+w
```

However, when I try to start *VSCode* as my main user I get the following error:

![image](https://user-images.githubusercontent.com/17570430/58324231-94b11100-7e26-11e9-9cb9-50177fa74060.png)

I suspected this is caused by the permissions of the *VSCode-linux-64* and *VSCode-linux-64/data* folders which are:

```
drwxr-xr-x   6 root  root      4096 May 24 13:17 VSCode-linux-x64
```

I tried changing the group of this folder to the *dev* group which contains my user and the root user by using the `chgrp -R dev ./VSCode-Linux-x64/data` command. Unfortunately inside the singularity container for the root user the *dev* group doesn't exist. This can be seen by running the `group` command as the root user while being in the singularity container. If I do this I get the following error:

```
groups: cannot find name for group ID 1001
```

This is caused by the fact that inside the container the */etc/group* file doesn't contain the `dev:x:1001:ricks,root` line while outside it does. I tried to create the dev group inside the singularity container by running the `groupadd -g 1001 dev` and `usermod -a -G dev root && usermod -a -G dev ricks` commands. Strangely inside the singularity container my main user account `ricks` doesn't exist for the root user. To overcome this I changed the group of the data file from within my main system by executing the following commands:

```
sudo chgrp -R dev <my_sandbox_folder>
sudo chmod -R g+rwx <my_sandbox_folder>
```

Now the *VSCode-linux-64* and *VSCode-linux-64/data* folders have the following permissions:

```
drwxrwxr-x    6 root  dev       4096 May 24 13:17 VSCode-linux-x64
drwxrwxr-x 2 root dev     4096 May 24 13:17 data
```

Unfortunately when I now try to  run the *Visual code* program I still get the following error:

![image](https://user-images.githubusercontent.com/17570430/58325206-4f421300-7e29-11e9-91ef-0550082d7adf.png)

I searched through the singularity documentation but I could not find the cause of this inconsistency. My question therefore is does anybody know if there is a way to install a program like *Visual code* , which needs write acces to configuration folders, inside a singularity image?

**Permission info:**
```
$ whoami
ricks
$ id
uid=1000(ricks) gid=1000(ricks) groups=1000(ricks),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lpadmin),126(sambashare),1001(dev)
$groups
ricks adm cdrom sudo dip plugdev lpadmin sambashare dev
$ grep "dev" /etc/group
plugdev:x:46:
dev:x:1001:root
plugdev:x:46:ricks
dev:x:1001:ricks
$ ls -l /VSCode-linux-64/bin
-rwxrwxr-x 1 root dev 1624 May 24 07:03 code-insiders
$ ls -l /VSCode-linux-64/data
drwxrwxr-x 4 root dev     4096 May 24 13:36 data
```

## Expected behavior

I expected Visual code to run as it does on my main system.

## Actual behavior

I keep getting write permission errors:

![image](https://user-images.githubusercontent.com/17570430/58325206-4f421300-7e29-11e9-91ef-0550082d7adf.png)

## Steps to reproduce the behavior

1. Install singularity according to [this guide](https://www.sylabs.io/guides/3.2/user-guide/).
2. Build a ubuntu 16.04 singularity image by running the following command:
`sudo singularity build --sandbox ubuntu1604 docker://ubuntu:16.04`
3. When finished run the shell as sudo by using `sudo singularity run --nv --writable ubuntu1604`
4. Download the lates tar.gz and unzip it:
```
curl -L "https://go.microsoft.com/fwlink/?LinkId=723968" > vscode-insider.tar.gz
tar --no-same-owner -xvzf vscode-insider.tar.gz
```
5. Go into the *VSCode-linux-x64* folder.
6. Create a *user-data* and *data* folder as explained in the [vscode portable documentation](https://code.visualstudio.com/docs/editor/portable).
7. Try to run the VSCode program by executing `sh ./bin/code-insiders --verbose`.

### System information
- VSCode Version: 1.34.0
- OS Version: Ubuntu 16.04 (Singularity container)

### Run from outside the container
When I run the `. <MY_CONTAINER>/VSCode-linux-64/bin/code-insiders` command from the main system visual code starts without any problems. The permissions of the *data* folder outside the container are:

`drwxrwxr-x 4 root dev     4096 mei 24 13:36 data`

The **/etc/group** file is as follows:

```
root:x:0:
daemon:x:1:
bin:x:2:
sys:x:3:
adm:x:4:syslog,ricks
tty:x:5:
disk:x:6:
lp:x:7:
mail:x:8:
news:x:9:
uucp:x:10:
man:x:12:
proxy:x:13:
kmem:x:15:
dialout:x:20:
fax:x:21:
voice:x:22:
cdrom:x:24:ricks
floppy:x:25:
tape:x:26:
sudo:x:27:ricks
audio:x:29:pulse
dip:x:30:ricks
www-data:x:33:
backup:x:34:
operator:x:37:
list:x:38:
irc:x:39:
src:x:40:
gnats:x:41:
shadow:x:42:
utmp:x:43:
video:x:44:
sasl:x:45:
plugdev:x:46:ricks
staff:x:50:
games:x:60:
users:x:100:
nogroup:x:65534:
systemd-journal:x:101:
systemd-network:x:102:
systemd-resolve:x:103:
input:x:104:
crontab:x:105:
syslog:x:106:
messagebus:x:107:
netdev:x:108:
mlocate:x:109:
ssl-cert:x:110:
uuidd:x:111:
avahi-autoipd:x:112:
bluetooth:x:113:
rtkit:x:114:
ssh:x:115:
lpadmin:x:116:ricks
whoopsie:x:117:
scanner:x:118:saned
saned:x:119:
pulse:x:120:
pulse-access:x:121:
avahi:x:122:
colord:x:123:
geoclue:x:124:
gdm:x:125:
ricks:x:1000:
sambashare:x:126:ricks
rdma:x:128:
xrdp:x:129:
lightdm:x:130:
nopasswdlogin:x:131:
x2gouser:x:132:
x2goprint:x:133:
docker:x:999:
nvidia-persistenced:x:127:
dev:x:1001:ricks,root
```

### Run from inside the container
When run inside the container I get the earlier explained error message and the following terminal output.

**./VSCode-linux-64/bin/code-insiders --verbose output:**
```
Gtk-Message: Failed to load module "appmenu-gtk-module"
Gtk-Message: Failed to load module "appmenu-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
[31011:0524/134850.683559:ERROR:bus.cc(394)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

The permissions of the *data* folder outside the container are:

`drwxrwxr-x 4 root dev     4096 May 24 13:36 data`

The **/etc/group** file is as follows:

```
root:x:0:
daemon:x:1:
bin:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mail:x:8:
news:x:9:
uucp:x:10:
man:x:12:
proxy:x:13:
kmem:x:15:
dialout:x:20:
fax:x:21:
voice:x:22:
cdrom:x:24:
floppy:x:25:
tape:x:26:
sudo:x:27:
audio:x:29:
dip:x:30:
www-data:x:33:
backup:x:34:
operator:x:37:
list:x:38:
irc:x:39:
src:x:40:
gnats:x:41:
shadow:x:42:
utmp:x:43:
video:x:44:
sasl:x:45:
plugdev:x:46:
staff:x:50:
games:x:60:
users:x:100:
nogroup:x:65534:
systemd-journal:x:101:
systemd-timesync:x:102:
systemd-network:x:103:
systemd-resolve:x:104:
systemd-bus-proxy:x:105:
messagebus:x:106:
scanner:x:107:
colord:x:108:
crontab:x:109:
input:x:110:
ssh:x:111:
adm:x:4:ricks
cdrom:x:24:ricks
sudo:x:27:ricks
dip:x:30:ricks
plugdev:x:46:ricks
lpadmin:x:116:ricks
sambashare:x:126:ricks
ricks:x:1000:ricks
dev:x:1001:ricks
```

There seems to be a difference in the fact that in the root user is not part of the dev group.

## Other things I tried
I tried downloading the (VScode files) and unzipping it while running the container as my main user. Unfortunately this also gives me the permission error while the *VSCode-linux-64/data* folder now has the following permissions: 

`drwxr-xr-x 4 ricks ricks     4096 May 24 14:31 data
drwxr-xr-x 2 ricks ricks 4096 May 24 14:31 data/extensions
drwx------ 6 ricks ricks 4096 May 24 14:31 data/user-data`

**Comment by rherban** [comment]
After some initial testing, there may be a deeper problem here with VScode.  I can reproduce the problem, but I've confirmed that we have read/write to the data directory through Singularity.

Singularity is designed to run as a single user, so file ownerships are a bit of a misnomer inside the image.  You can run it as root with `sudo singularity shell` or it runs as you, but either way there's effectively only a single user.

My test setup:
```
Bootstrap: library
From: debian

%post
	apt-get update && apt-get install -y libxss1 libgtk-3-0 libsecret-1-0 libxkbfile1 gnupg libnss3 libnotify4 libasound2
$ sudo singularity build code.sif vscode.def
<download & untar VScode>
$ singularity shell code.sif
Singularity code.sif:~> VSCode-linux-x64/code-insiders
<same error that you reported>
```

What's interesting is that it's able to write to the `data` directory, as visible below:
```
[rherban@test]:~$ tree VSCode-linux-x64/data/
VSCode-linux-x64/data/
├── extensions
└── user-data
    ├── Backups
    ├── CachedData
    │   └── 5e1f9440d280b0b04cba843df6a0032bf517a2f0
    │       ├── bom-handling-b1716cdee35ff4762811cdcc843d7e96.code
    │       ├── dialog-34d1f7eee309f38a5250515ce6dcdb2b.code
    │       ├── extend-node-07ba1a9859a18c5869c4e0f59e54c27d.code
    │       ├── index-2a8af058d3e45af3b803c37f72a9379d.code
    │       ├── index-df4365cf379486c71562b3dc7304f303.code
    │       ├── main-7d4c18276698f568d0569214f70350a5.code
    │       ├── main.nls-90db9fc49f10cddf806fc31152c6dd1e.code
    │       ├── safer-1a434c00da794394212555f5808d94d1.code
    │       └── streams-e0cd9dcbbe043b48a9f4efe0e37b647f.code
    ├── logs
    │   ├── 20190524T110722
    │   ├── 20190524T111335
    │   ├── 20190524T113408
    │   ├── 20190524T113522
    │   ├── 20190524T124920
    │   └── 20190524T125223
    └── User
        ├── globalStorage
        └── workspaceStorage

15 directories, 9 files
```

**Comment by rickstaa** [comment]
Dear @rherban s a lot for looking into my problem. So the `groups: cannot find name for group ID 1001` error is caused by the fact that singularity is created to work with one user while I changed the group ownership to a group containing two users? I will forward your report to the [vscode issue page](https://github.com/microsoft/vscode/issues/74130).

**Comment by truatpasteurdotfr** [comment]
could you try to run: `singularity run -B /run library://tru/default/c7-visualstudio` or `singularity run -B /ru library://tru/default/debian9-visualstudio` ? omitting the -B /run yields the same errors your mentionned  (bogus non writable ~/.config/Code and ~/.vscode). ymmv.

**Comment by rickstaa** [comment]
@truatpasteurdotfr that indeed solved my problem! I can however not find anything on the -B flag inside the documentation. Can you explain to me what it does?

**Comment by rickstaa** [comment]
@truatpasteurdotfr Ah that indeed solved it. Thanks a lot! Can you maybe explain to me why I need to bind the `/run` directory for visual code to work inside the container? Is the error caused by vs code not having access to some necessary files in that directory? Or does some daemon use that folder? Further this the desired behavior?

**Comment by truatpasteurdotfr** [comment]
I have no idea ( I haven't serach either) why it needs to bind the /run directory, google chrome and brave browser have the same requirements.

**Comment by rickstaa** [comment]
Okay, thanks a lot for helping me! I can now debug the threads of processes inside my singularity image :). I will close the issue since I assume this is a vs code related issue.

**Comment by rickstaa** [comment]
[](url)

**Comment by rherban** [comment]
@rickstaa Correct about the group not found error.  If you look at `/etc/group` within a container, it's a barebones copy and your second group won't exist.
