### ISSUE TITLE
Environment is not inherited in Singularity Desktop

### ISSUE THREAD

**Issue by chrisburr** [apptainer/singularity#3610]
## Version of Singularity:

Singularity Desktop version 3.2.0-rc2 on macOS

### Expected behavior

`EXAMPLEVAR` is propagated to the container

```bash
$ EXAMPLEVAR="Hello world" singularity run test-image.sif
Running singularity container sucessfully with EXAMPLEVAR=Hello world
```
(is the case on Linux)

### Actual behaviour

`EXAMPLEVAR` is not propagated to the container

```bash
$ EXAMPLEVAR="Hello world" singularity run test-image.sif
Running singularity container sucessfully with EXAMPLEVAR=
```

### Steps to reproduce behavior

The container was build with:
```bash
BootStrap: busybox
MirrorURL: https://www.busybox.net/downloads/binaries/1.26.1-defconfig-multiarch/busybox-x86_64

%runscript
    echo "Running singularity container sucessfully with EXAMPLEVAR=$EXAMPLEVAR"
```

**Comment by rherban** [comment]
Environment variables have to be prepended with `SINGULARITY_` to be accessible within the container.

` SINGULARITYENV_HELLO=world singularity exec centos7.img env | grep HELLO`
`HELLO=world`


More info can be found here: 
https://www.sylabs.io/guides/3.2/user-guide/environment_and_metadata.html#environment

**Comment by chrisburr** [comment]
Thanks for the quick reply.

I see now that the `--cleanenv` flag only exists on Linux. It's a little awkward that the behaviour is different between platforms.

**Comment by chrisburr** [comment]
Actually even prefixing with `SINGULARITYENV_` doesn't work so I think this needs to be reopened:

```bash
$ SINGULARITYENV_EXAMPLEVAR="Hello world" singularity run test-image.sif
Running singularity container sucessfully with EXAMPLEVAR=
```

**Comment by rherban** [comment]
Interesting, I'm seeing expected results using Singularity 3.2 on a Debian host.  


```
[rherban@test]:~$ cat busybox.def
BootStrap: busybox
MirrorURL: https://www.busybox.net/downloads/binaries/1.26.1-defconfig-multiarch/busybox-x86_64

%runscript
    echo "Running singularity container sucessfully with EXAMPLEVAR=$EXAMPLEVAR"
[rherban@test]:~$ sudo singularity build test.sif busybox.def
Build target already exists. Do you want to overwrite? [N/y] y
INFO:    Starting build...
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete: test.sif
[rherban@test]:~$ SINGULARITYENV_EXAMPLEVAR="Hello world" singularity run test.sif
Running singularity container sucessfully with EXAMPLEVAR=Hello world
```


Also tested with a debian image from our library with expected results.
```
Bootstrap: library
From: debian

%runscript
    echo "Running singularity container sucessfully with EXAMPLEVAR=$EXAMPLEVAR"
```

**Comment by rherban** [comment]
@jmstover

**Comment by jmstover** [comment]
@chrisburr ... Due to some nuances to how Desktop works under the hood, we're currently limited so what we can pass to containers.  Unfortunately environment variables aren't able to make the cut.

**Comment by dtrudg** [comment]
Closing as Singularity Desktop currently not maintained.
