### ISSUE TITLE
singularity selftest is not available

### ISSUE THREAD

**Issue by chrisburr** [apptainer/singularity#3611]
## Version of Singularity:

singularity version 3.2.0-1.el6

### Expected behavior

`singularity selftest` can be used for ensuring a working installation of singularity is available.

### Actual behavior

The `selftest` subcommand is not available.

### Steps to reproduce behavior

I haven't managed to find anything stating that `selftest` has been intentionally dropped. Is this the case? Or has it just not been implemented yet?

**Comment by GodloveD** [comment]
I think the general consensus is that `selftest` was a pretty lackluster feature in the 2.x series and probably not worth carrying into the 3.x series.  That said, there has been some discussion of trying to implement a more full featured set of checks that tests things like which namespaces are supported.  Tools like `lxc-checkconfig` do things like this already.  Might be good to just start with something like this.

**Comment by jscook2345** [comment]
Closing since @chrisburr gave us the 👍 . Please reopen if you have more quesitons!
