### ISSUE TITLE
Push/Pull commands against OCI Registries (ORAS) returns 401 Unauthorized

### ISSUE THREAD

**Issue by vincentlabonte** [apptainer/singularity#3616]
## Version of Singularity:

Master branch (at time of our build: 5fac9d2bb811c9859f072385ca18243ab4ae2e69). The specific PR with this functionality is #3526.

### Expected behavior

Attempting to leverage the ORAS push/pull functionality in the singularity client. The expected behavior is to push and pull SIF images from OCI registries via the ORAS integration in the singularity client.

`singularity push image.sif oras://<registry>/image:tag`
`singularity pull image.sif oras://<registry>/image:tag`

### Actual behavior

Both push and pull commands are failing with `While pulling image from oci registry: unable to pull from registry: failed to fetch oauth token: unexpected status: 401 Unauthorized`

We've tried using various authentication methods:

* `SINGULARITY_DOCKER_USERNAME`/`SINGULARITY_DOCKER_PASSWORD` env vars
* The above without `SINGULARITY_` prefix
* `--docker-username` and `--docker-password` in the `singularty pull` or `singularity push` command
* `--docker-login` interactive with `singularity pull`

### Steps to reproduce behavior

See expected behavior. Our particular use case is against Azure Container Registry (ACR).

cc @alfpark, @sajayantony, @bauerm97

**Comment by rherban** [comment]
@ikaneshiro @tri-adam

**Comment by ikaneshiro** [comment]
Hey @vincentlabonte, apologies for the latency on handling this issue.

I think I've identified the problem and have a fix in PR #3649. Could you test that out to make sure it works for you?

**Comment by vincentlabonte** [comment]
@ikaneshiro the fix seems to work! I can now pull and push images to Azure Container Registry. Thanks!
