### ISSUE TITLE
CTRL-Z (SIGTSTP) is not respected for GUI inside of container

### ISSUE THREAD

**Issue by robertlugg** [apptainer/singularity#3624]
## Version of Singularity:
3.1.0

### Expected behavior
Starting a container with a GUI running within it.  In the terminal, pressing ctr>-Z should suspend applications.

### Actual behavior

Pressing ctrl-Z and ctrl-C in the terminal display as ^Z and ^C but don't do anything else.  At that point, both the GUI and the terminal are frozen and must be forced to close.

### Steps to reproduce behavior

May be the same as #2223 or #2225.
Unfortunately, it is an internal program which cannot be made available.  I can't confirm if the problem is only with this program or for all GUI programs.

Possible hint:  This appears to happen when running the GUI program using singularity exec ...   If I instead run from within a shell within the container the GUI works fine as do the ctrl-Z and ctrl-C

**Comment by cclerget** [comment]
Hi @robertlugg , can you try with the latest release https://github.com/sylabs/singularity/releases/tag/v3.2.1-rc1 to see if that fixes the issue ?
