### ISSUE TITLE
Newbie networking question

### ISSUE THREAD

**Issue by ashleysommer** [apptainer/singularity#3627]
I'm new to Singularity. I need to port some of my Docker container images to work under Singularity for the new environment I'm deploying into.

The docker-compose version was using Overlay-networking. That doesn't exist in Singularity, so I'm trying to do the same thing with Bridge networking. But I can't seem to get any networking to work. I want to be able to communicate between once container service instance to another container service instance using either Bridge or PTP networking.

## Version of Singularity:

3.2.0

### Expected behavior
Starting a container service instance with `--net` should put the container on a Bridge network with access to the internet and other container instances on the same bridge network.

### Actual behavior
When started with the `--net` argument the container is configured on a Bridge network with no access to the internet and cannot ping any other container instances on that same bridge network.

### Steps to reproduce behavior
```
sudo singularity build test.sif library://alpine:3.6
sudo singularity instance start --writable-tmpfs --net --network bridge --dns 8.8.8.8 test.sif t1
sudo singularity exec instance://t1 ip addr

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if14: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 06:d8:d5:e8:ff:fd brd ff:ff:ff:ff:ff:ff
    inet 10.22.0.36/16 brd 10.22.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::4d8:d5ff:fee8:fffd/64 scope link tentative 
       valid_lft forever preferred_lft forever

sudo singularity exec instance://t1 ping google.com

ping: bad address 'google.com'
```
Adding `--dns` doesnt help:
```
sudo singularity instance start --writable-tmpfs --net --network bridge --dns 8.8.8.8 test.sif t1
sudo singularity exec instance://t1 ping google.com

ping: bad address 'google.com'
```

Without the `--net` it can access the network fine:
```
sudo singularity instance start --writable-tmpfs --net --network bridge --dns 8.8.8.8 test.sif t1
sudo singularity exec instance://t1 ping google.com

PING google.com (172.217.167.78): 56 data bytes
64 bytes from 172.217.167.78: seq=0 ttl=53 time=21.242 ms
64 bytes from 172.217.167.78: seq=1 ttl=53 time=22.125 ms
64 bytes from 172.217.167.78: seq=2 ttl=53 time=22.963 ms
```

**Comment by ashleysommer** [comment]
I ultimately want to be able to do something like this:

```
sudo singularity instance start --writable-tmpfs --hostname mymongo --net --network bridge mongodb.sif mongoinstance
sudo singularity instance start --writable-tmpfs --hostname myinflux --net --network bridge influxdb.sif influxinstance
sudo singularity instance start --writable-tmpfs --hostname myapp --net --network bridge application.sif appinstance

sudo singularity exec instance://appinstance ping mymongo
sudo singularity exec instance://appinstance ping myinflux
```

**Comment by jscook2345** [comment]
@jmstover ping!

**Comment by dtrudg** [comment]
Closing, as this issue is a usage question that has not received input from the community for >90 days.

For issues that are questions r.e. using Singularity, rather than bugs or feature requests, the mailing-list and slack channel are often better venues. Questions to the slack channel and mailing list will be seen by a large number of subscribed users, rather than only those who look inside a particular GitHub issue. Therefore they are encouraged for this type of inquiry.

Slack: https://join.slack.com/t/hpcng/shared_invite/zt-gy0st6mt-ijgUaSvfdeEOhfXXfIstrQ
Mailing List / Google Group: https://groups.google.com/a/lbl.gov/forum/#!forum/singularity
