### ISSUE TITLE
Singularity pull does not cache for docker images from quay.io

### ISSUE THREAD

**Issue by rhpvorderman** [apptainer/singularity#3633]
## Version of Singularity: 

3.1.0

### Expected behavior

Pulling an image from quay.io (for example `docker://quay.io/biocontainers/fastqsplitter:1.0.0--py_0`) will cache said image. Also blobs cached with `singularity pull` should be used by `singularity run`.

### Actual behavior

The image is not cached. Pulling twice will result in downloading twice.
Strangely enough, when using `singularity run` instead of `singularity pull` the image is properly cached. But only for the `run` command. The `pull` command will always pull.
Blobs that are downloaded with `pull` are not used by `run`.

### Steps to reproduce behavior

```
singularity cache clean --all
singularity pull docker://quay.io/biocontainers/fastqsplitter:1.0.0--py_0
singularity pull docker://quay.io/biocontainers/fastqsplitter:1.0.0--py_0
```
Contrast with
```
singularity cache clean --all
singularity run docker://quay.io/biocontainers/fastqsplitter:1.0.0--py_0 bash -c 'exit'
singularity run docker://quay.io/biocontainers/fastqsplitter:1.0.0--py_0 bash -c 'exit'
```
Where the cache is properly used.

Also blobs downloaded by pull are not used by run:
```
singularity cache clean --all
singularity pull docker://quay.io/biocontainers/fastqsplitter:1.0.0--py_0
singularity run docker://quay.io/biocontainers/fastqsplitter:1.0.0--py_0 bash -c 'exit'
```

**Comment by GodloveD** [comment]
Heya @rhpvorderman I think this was already fixed in current master.  Can you confirm?

**Comment by rhpvorderman** [comment]
@GodloveD Yes it works! Should have tested on the latest version. Sorry for that.

 Thanks!

**Comment by GodloveD** [comment]
😅 whew!  Glad to hear it.  Thanks for helping to keep Singularity honest!
