### ISSUE TITLE
%files is getting executed after %setup

### ISSUE THREAD

**Issue by asmi10** [apptainer/singularity#3635]
## Version of Singularity:

3.2.0

Below is the def file
Bootstrap: localimage                                                                               
From:/home/singularityimg/data/linuxset.container/SIF-images/SLES12/sles12.sif                                           
%files
     /home/singularityimg/data/linuxset.container/SIF-images/SLES11/gpg-keys /opt/ 

%post
     ls -la /opt/gpgkeys                                                               

but during build I see below                                                                
INFO:    Starting build...                                                                                                        
INFO:    Copying /home/singularityimg/data/linuxset.container/SIF-images/SLES11/gpg-keys to /tmp/sbuild-619319600/fs/opt          
INFO:    Running post scriptlet                                                                                                   
+ ls -la /opt/gpgkeys
ls: cannot access '/opt/gpgkeys': No such file or directory
FATAL:   post proc: exit status 2                          
FATAL:   While performing build: while running engine: exit status 255

Is this expected behavior? I see there is already a fix prepared: https://github.com/sylabs/singularity/issues/2707 in 3.1RC, but I am using singularity 3.2.  Is this fix not included in 3.2?

**Comment by jmstover** [comment]
Can you change the `%post` to have:

```
ls -la /opt/gpg-keys
```

Your source directory is `SLES11/gpg-keys` ... but you're looking for `/opt/gpgkeys`.

**Comment by asmi10** [comment]
yes, my bad:(
Thanks!

**Comment by asmi10** [comment]
syntax issue in defination file
