### ISSUE TITLE
Failed to get manifest from shub: No response received from singularty hub

### ISSUE THREAD

**Issue by pavankulka** [apptainer/singularity#3643]
## Version of Singularity:

3.0.2

### Expected behavior

Ubuntu sandbox creation on Singularity
 
### Actual behavior

Unable to build a singularity sandbox using the command : singularity build --sandbox  ubuntu/ docker://ubuntu

### Steps to reproduce behavior

I am getting below error

**Comment by vsoch** [comment]
What does this have to do with Singularity Hub?

**Comment by rherban** [comment]
@pavankulka It looks like the error was clipped from this posting.  Can you add it in?

**Comment by rherban** [comment]
Found it, #3642 has the error message.  Will close this issue and continue there.
