### ISSUE TITLE
Releases are tagged as pre-releases

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#3653]
## Version of Singularity:

3.2.0, 3.2.1

### Expected behavior

Parsing the version string for either of the above official releases returns the release version, not a pre-release.

### Actual behavior

Both official releases are (semver) pre-releases.

For example, here is a snippet to install 3.2.0 (you can do the same for 3.2.1):

```
...
cd ${GOPATH}/src/github.com/sylabs && \
wget https://github.com/sylabs/singularity/releases/download/v3.2.0/singularity-3.2.0.tar.gz && \
tar -xzvf singularity-3.2.0.tar.gz && \
cd singularity && \
./mconfig -p /usr/local && \
make -C builddir && \
$SUDO make -C builddir install
```

The version of Singularity installed from the above should be singularity version 3.2.0, but it's not:

```bash
$ singularity --version
singularity version 3.2.0-1
```
The issue is that when we parse with semver, and we want to do something like compare the version we find to the actual version (3, 2, 1) when it should return True, it returns False (as it's flagged as a pre-release): Here is interaction with the version info string from Singularity Python, using the semver library.

```python
from semver import VersionInfo                                          

# Here I can show what a proper version 3.2.0 looks like, note that prelease is None.
VersionInfo(3,2,0)                                                      
VersionInfo(major=3, minor=2, patch=0, prerelease=None, build=None)

# Now I can import the singularity python client, which parses the version info string from Singularity
from spython.main import Client                                         

# Notice how prelease is 1
Client.version_info()                                                   
VersionInfo(major=3, minor=2, patch=0, prerelease='1', build=None)

# And this is because the pre-release variable -1 is there:
print(Client.version_info())                                            
3.2.0-1

# Here is the issue - checking if 3.2.0 is >= 3.2.0 returns False.

Client.version_info() >= VersionInfo(3,2,0)                             
False
```

And here is the culprit - a fresh download of the .tar.gz (for either of these) has a VERSION file that still has the pre-release:

![image](https://user-images.githubusercontent.com/814322/58711986-a433db00-838d-11e9-8e59-1f47ace3f332.png)

**Comment by mem** [comment]
I believe I have fixed this issue with the associated PR.

**Comment by dtrudg** [comment]
This does fix the semver format. The referenced #4558 needs to be addressed, but is not directly this issue.
