### ISSUE TITLE
Singularity bind mount read only file system not allowed

### ISSUE THREAD

**Issue by jeffcbecker** [apptainer/singularity#3654]
## Version of Singularity:

3.2.0

### Expected behavior

/nasa is mounted read-only (verified by /proc/mounts)

$ singularity exec --bind /nasa:/nasa lolcow ls /nasa
/* listing of files/dirs in /nasa */

### Actual behavior

$ singularity exec --bind /nasa:/nasa lolcow ls /nasa
FATAL:   container creation failed: mount ->/nasa error: can't remount /nasa: operation not permitted

Note this works with file systems mounted read/write

### Steps to reproduce behavior

See above

**Comment by cclerget** [comment]
Hi @jeffcbecker , try with `singularity exec --bind /nasa:/nasa:ro lolcow ls /nasa` to force read-only bind mount.

**Comment by jeffcbecker** [comment]
Yes that works. Did I miss it in the documentation?

**Comment by jeffcbecker** [comment]
Found it buried in https://www.sylabs.io/guides/3.2/user-guide/bind_paths_and_mounts.html?highlight=bind%20mount
