### ISSUE TITLE
Integrate utility functions from #3486

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#3657]
We should leverage the utility functions created in #3486 in the current E2E framework.

These utility functions can be found in that PR under:
- `e2e/scripts/common.func`
- `e2e/scripts_builtins/`

The checks within `e2e/scripts/common.func` could be a point to start making our tests easier to read.
For example: checks like `expect-success/failure` and `std*-contains` could be used in the current framework to make the login for running these table driven tests simpler

It appears all of the functions in `e2e/scripts_builtins/` will be useful within the current E2E framework. Some of these functions exists in the current framework to some extent, but should be made general so that they can be used by tests written in the future.

**Comment by mem** [comment]
In one way or another most (all?) of the concepts there have been migrated to the existing E2E tests. I think this issue can be closed. If needed, we can figure out a different way (even if it's a different issue, or an epic) to document whatever is still pending.
