### ISSUE TITLE
[trivial bug] add_http should change http to https

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#366]
Currently, if the url provided is `http`, and the default is to return `https`, the regular expression searches for http and then doesn't change the url. We should check for the specific prefix, and fix if necessary.

**Comment by flx42** [comment]
Err, why? Are you saying `http://example.com` should always be changed to `https://example.com`? 'https' should only be added if the scheme was not specified.

**Comment by flx42** [comment]
Note however that the current approach can't handle the convoluted case of domains actually starting with `http`. For instance try `add_http("httpie.org")`.
Really, we should probably be using something like `urlparse.urlparse("httpie.org", scheme="https")`

**Comment by vsoch** [comment]
I like that idea, +1.

**Comment by vsoch** [comment]
I basically want to say that we need to be sure that (most things) passed to this function return a proper url.

**Comment by vsoch** [comment]
This has been finished. Good work!
