### ISSUE TITLE
Bad "default" values in singularity.conf

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#3669]
## Version of Singularity:

3.1.1 (but seems to be still present in current master)

### Expected behavior

Documented `DEFAULT: ` in config file matches real default. 

### Actual behavior

It is wrong for at least `ROOT DEFAULT CAPABILITIES`. 

### Steps to reproduce behavior

Read config file after installation. 

### More details

As seen in https://github.com/sylabs/singularity/blob/master/pkg/runtime/engines/singularity/config/config.go , the default for `RootDefaultCapabilities` is `full`. 
However, as seen in https://github.com/sylabs/singularity/blob/master/etc/singularity.conf.in , the documentation in `singularity.conf` says:
`# DEFAULT: no`
It would be best to just use:
`# DEFAULT: @ROOT_DEFAULT_CAPABILITIES_DEFAULT@`
in that file to have things correct by design, instead of mixing hardcoding something and using macros for some other options in that file. Otherwise, things will break regularly, as is right now the case with at least `ROOT DEFAULT CAPABILITIES`.

**Comment by olifre** [comment]
I'm also somewhat confused since there is also:
https://github.com/sylabs/singularity/blob/master/pkg/runtime/engines/singularity/config/data/singularity.conf
but that file suffers from the very same bug.

**Comment by cclerget** [comment]
@olifre https://github.com/sylabs/singularity/blob/master/etc/singularity.conf.in is not used anymore and as you noticed https://github.com/sylabs/singularity/blob/master/pkg/runtime/engines/singularity/config/data/singularity.conf is used instead. Will fix that

**Comment by olifre** [comment]
@cclerget Thanks! 
I commented on the PR a second ago ;-).
