### ISSUE TITLE
[bug] get_auth_header does not support python 3

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#367]
Issue with string / bytes?

	In [51]: auth = basic_auth_header(username='vanessa',
	    ...:                          password='pancakes')
	---------------------------------------------------------------------------
	TypeError                                 Traceback (most recent call last)
	<ipython-input-51-7f5674e3db85> in <module>()
	      1 auth = basic_auth_header(username='vanessa',
	----> 2                          password='pancakes')

	/home/vanessa/Documents/Dropbox/Code/singularity/singularity/libexec/python/utils.py in basic_auth_header(username, password)
	    169 
	    170 def basic_auth_header(username, password):
	--> 171     credentials = base64.b64encode("%s:%s" % (username, password))
	    172     auth = {"Authorization": "Basic %s" % credentials}
	    173     return auth

	/home/vanessa/anaconda3/lib/python3.5/base64.py in b64encode(s, altchars)
	     57     """
	     58     # Strip off the trailing newline
	---> 59     encoded = binascii.b2a_base64(s)[:-1]
	     60     if altchars is not None:
	     61         assert len(altchars) == 2, repr(altchars)

	TypeError: a bytes-like object is required, not 'str'

**Comment by flx42** [comment]
That seems verbose, hopefully there is a better way?!

**Comment by vsoch** [comment]
Would love your input :)

**Comment by vsoch** [comment]
Error is fixed.

**Comment by flx42** [comment]
This makes me wonder if Singularity should really try to be compatible with both versions, and maybe we should only support python 3! Is there any excuse to not use Python 3 for a new project in 2016?

But anyway, I guess I would have been more straightforward about the Python 2 vs Python 3 difference, with your code it's not as simple to understand why we need the multiple `isinstance`.
Maybe something like that, works with both versions:
```
import sys
import base64

username = "felix"
password = "secretpassword"
s = "%s:%s" % (username, password)
if sys.version_info[0] >= 3:
    s = bytes(s, 'utf-8')
    credentials = base64.b64encode(s).decode('utf-8')
else:
    credentials = base64.b64encode(s)
auth = {"Authorization": "Basic %s" % credentials}
print(auth["Authorization"])
```

**Comment by vsoch** [comment]
Yes, something like that would work equally well. I wanted to get the fix out asap, because it's (still) important to support both versions. One of the core mantas / values (call them what you like!) is to provide portable environments, meaning that we need to support the version of python (albeit it might be old) on the system. It's pretty easy to maintain 2 and 3 support, so let's do that for now.

**Comment by vsoch** [comment]
and huge thanks for the much prettier function! I'll integrate when I write the rest of the tests, tomorrow likely!
