### ISSUE TITLE
[Regression] /dev/tty missing

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#3670]
## Version of Singularity:

3.1.1

### Expected behavior

`/dev/tty` exists in a container started with `-C` and having `mount devpts = yes` in the configuration. 

### Actual behavior

It's missing. 

### Steps to reproduce behavior

Have  `mount devpts = yes` in the config and start a container wiht `-C`. Programs like `xterm` will fail since `/dev/tty` is missing. 

As a hotfix, running:
```
ln -s /dev/pts/0 /dev/tty
```
inside the container (works as normal user) works fine. 

`/dev/tty` was present just fine in singularity 2.6.1, so this is a regression.

**Comment by olifre** [comment]
That's interesting - it does not always happen. 
An "easy" way to reproduce it is to run singularity without tty but with an sshd inside, and connect to it. That's what an HTCondor interactive job is doing in HTCondor 8.6.x. 
We're then probably jumping over this part:
https://github.com/sylabs/singularity/blob/c3c08c7d0a6f1dd76f8b935bcc05be07815e8997/internal/pkg/runtime/engines/singularity/container_linux.go#L1011
Interestingly, this was different in Singularity 2.6.1.

**Comment by olifre** [comment]
Maybe it would be sufficient to pull this:
https://github.com/sylabs/singularity/blob/c3c08c7d0a6f1dd76f8b935bcc05be07815e8997/internal/pkg/runtime/engines/singularity/container_linux.go#L1052-L1055
outside of the loop? 
It's not a prerequisite to have a tty "outside" to be allowed to have a tty within, since e.g. X11 applications running in an sshd inside the container can make use of a tty even if the environment in which the container was started did not have one.

**Comment by cclerget** [comment]
Hi @olifre , agree that `/dev/tty` should be part of default devices no matter if using terminal or not, will fix that

**Comment by olifre** [comment]
@cclerget Thanks for the quick patch :smile:
