### ISSUE TITLE
how to  setup and configure  singularity on Rocks Cluster Distribution  by Building a roll

### ISSUE THREAD

**Issue by naveen584** [apptainer/singularity#3672]
hello can you please  tell how to  setup and configure  singularity on Rocks Cluster Distribution  by Building a roll.

**Comment by jscook2345** [comment]
@naveen584 

We have several installation documents (the location of which are version dependent), ex: (https://www.sylabs.io/guides/3.2/user-guide/quick_start.html#quick-installation-steps) and (https://github.com/sylabs/singularity/blob/master/INSTALL.md).

Perhaps you could tell us what issues you're having first and we can work from there?

**Comment by mem** [comment]
If you still need help with the installation please ask in the slack channel or mailing list. And please do not hesitate to report other issues.

Thanks!
