### ISSUE TITLE
OpenMPI and singularity

### ISSUE THREAD

**Issue by denisbertini** [apptainer/singularity#3678]
## Version of Singularity:

2.6

### Expected behavior

Work together with openMPI and SLURM as resource manager

### Actual behavior

When initialising MPI with many processes with SLURM i got the following errors comping from PMIX:

[lxbk0553:30428] PMIX ERROR: PMIX TEMPORARILY UNAVAILABLE in file ptl_tcp.c at line 685
[lxbk0553:30428] OPAL ERROR: Unreachable in file pmix2x_client.c at line 109
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)

### Steps to reproduce behavior

Create a image with singularity 2.6 try to run ring.c from openMPI  examples together with SLURM for more than 80 processes.

**Comment by QwertyJack** [comment]
I have tried with Singularity 3.2.0 and openmpi 1.10.x and 2.1.x .
The conclusion is, if the version matches then it works perfectly.
How do you run the job? Mine is something like this:
```bash
# allocate resource
mpirun -np 40 singularity exec <container> <cmd>
```

**Comment by denisbertini** [comment]
Hi
As i said, i run with SLURM. I tried meanwhile with openmpi 2.1.x and it seems to work better but
from time to time the MPI processes are not initialised properly and the job get stuck  without any warnings/errors messages !

**Comment by QwertyJack** [comment]
I also run with slurm, but omit resource allocation.

**Comment by denisbertini** [comment]
Well as i said it works but not stable, i was running many jobs but not all were able to start.
The only difference i see is that you use a newer version of singularity. 
I use singularity 2.6 do you think it is link to singularity version ?
What about support for higher version of openmpi ? v 3.x and v 4.x ?

**Comment by denisbertini** [comment]
can you send me your sbatch script ( without ressource allocation)  that i can compare with mine ?

**Comment by QwertyJack** [comment]
What is used:
- singularity 3.2.0
- openmpi 2.1.2
- container based on centos 7.6 with OPA support and openmpi 2.1.2
- osu-micro-benchmarks compiled by mpicc in the container

```
#!/bin/bash
#SBATCH -o osu-sing-ib.log
#SBATCH -p <partition>
#SBATCH -A <account>
#SBATCH -N 2
#SBATCH --ntasks-per-node=1

srun hostname -s | sort -n >slurm.hosts
~/local/openmpi/bin/mpirun -np 2 -machinefile slurm.hosts ~/local/singularity/bin/singularity exec ~/tmp/c7ib ~/osu-sing-ib/libexec/osu-micro-benchmarks/mpi/one-sided/osu_get_bw
rm slurm.hosts
```

**Comment by QwertyJack** [comment]
Haven't try with newer version of openmpi.
Singularity 3.x is worth a try anyway.

**Comment by gvallee** [comment]
We are in the process of setting periodic testing for MPI and I will include tests with Open MPI 2.1.2. We are also working on better MPI documentation. So hopefully we will have very soon more information to help with this type of problems.

**Comment by mem** [comment]
It sounds like the "fix" to the original issue was to use a newer version of singularity.

If you have further issues to report, please do not hesitate to do so.

Thanks!

**Comment by valmar** [comment]
I am still affected by this exact behavior.

Singularity version: 
 Crreated: singularity version 3.4.1-1.1.fc30
 Run: singularity version 3.4.0-1.el7

MPI version: 3.0.2

**Comment by QwertyJack** [comment]
> I am still affected by this exact behavior.
> 
> Singularity version:
> Crreated: singularity version 3.4.1-1.1.fc30
> Run: singularity version 3.4.0-1.el7
> 
> MPI version: 3.0.2

Try latest singularity.

**Comment by valmar** [comment]
Thanks for the quick answer. I will ask the administrator of our cluster and report here the outcome

**Comment by valmar** [comment]
Ok, our administrator updated to 3.4.1 but I get the same error....

**Comment by valmar** [comment]
Sorry, scratch that! The version of openmpi that was in the repository that I used to build the container was updated, and I did not notice. The version of openmpi in the container now did  not match the version of openmpi on the host. When I corrected that problem, the error disappeared..... 

Sorry for wasting your time!

**Comment by rfoxkendo** [comment]
I this problem  intermittently  with large jobs (e.g. 200 tasks) if I use 
singularity version 3.4.1-1.el7
and OpenMPI 4.0.2

In both the container and the host systems.

**Comment by dtrudg** [comment]
@rfoxkendo - please open a new issue, as this is an old report against an old version of Singularity.

Also please include the error messages (if any), and the topology of your job. I.E. how many containers are you running per node etc. Thanks.
