### ISSUE TITLE
Ability to pass in env vars with --cleanenv

### ISSUE THREAD

**Issue by keiranmraine** [apptainer/singularity#3686]
## Version of Singularity:

3.2.0

### Expected behavior

Ability to specify environment variables when `--cleanenv` in use, similar to docker:

```
--env , -e   Set environment variables
--env-file   Read in a file of environment variables
```

Issues discussed in #3594, #3331, #3510 result in this being required

### Actual behavior

Can't pass in env vars with `--cleanenv`

### Steps to reproduce behavior

Can't see any option for `exec` in docs to allow this.

**Comment by GodloveD** [comment]
Heya @keiranmraine!  Have you tried using the `SINGULARITYENV_` prefix like so:
```
$ export SINGULARITYENV_FOO=bar

$ singularity exec --cleanenv alpine_latest.sif env
SHLVL=1
LD_LIBRARY_PATH=/.singularity.d/libs
HOME=/home/vagrant
PS1=Singularity>
TERM=xterm-256color
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
FOO=bar
LANG=C
SINGULARITY_APPNAME=
SINGULARITY_CONTAINER=/home/vagrant/alpine_latest.sif
PWD=/home/vagrant
SINGULARITY_NAME=alpine_latest.sif
```
This seems to work for me on 3.2.1.  I assume it works on 3.2.0 as well, but I have not tried.  Can you confirm?  Does this provide the functionality you need?

If this is helpful, these docs might have some more info for you.

https://www.sylabs.io/guides/3.2/user-guide/environment_and_metadata.html#environment

**Comment by keiranmraine** [comment]
Ah this is exactly what I was missing, thanks for the quick response
