### ISSUE TITLE
Fuse plugin with --pid can leave many defunct zombie processes

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#3694]
## Version of Singularity:

Master branch including pr #3679 and example fusecmd plugin from #3693.

### Expected behavior

When singularity exec is invoked with --pid, it creates a pid 1 process that inherits all orphan children and it is supposed to wait for them and clean them up -- "reap" them. 

### Actual behavior

Normally this process works, but our cvmfs fuse program deliberately produces many such orphans and I often see many defunct children of the sinit pid 1 process.

### Steps to reproduce behavior

When testing --fusecmd with sshfs as a fuse program, first arrange to run the [attached](https://github.com/sylabs/singularity/files/3263740/double-forks.c.txt) test program which produces 10 orphans, before running sshfs.  I invoke it from a shell script that calls this program first and then sshfs "$@".  

@mem @bauerm97 @cclerget

**Comment by cclerget** [comment]
Fixed by #4076
