### ISSUE TITLE
Removal of sparse, need option to create

### ISSUE THREAD

**Issue by rjeschmi** [apptainer/singularity#370]
With the removal of the default option to create sparse images, it should still be permitted with an option.

**Comment by bbockelm** [comment]
Additionally, we should switch to `fallocate` to allocate and zero out the underlying file if making things dense.  For some Linux filesystems, this is more allocate than explicitly writing data.

**Comment by rajaseelan** [comment]
I just realised this as well, 2.2.1 does not create sparse images anymore.

**Comment by GodloveD** [comment]
Based on the direction we are heading in 2.4 I'm pretty sure we are moving permanently away from supporting sparse images.  I'm pinging @gmkurtzer just to be sure he doesn't think differently but I'm closing this for now.
