### ISSUE TITLE
Unable to source a script when building container

### ISSUE THREAD

**Issue by annaprins** [apptainer/singularity#3704]
## Version of Singularity:

3.2.0

### Expected behavior

I am trying to install an application through the definition file. The last step of installing this application is sourcing a setup script. For some reason, this doesn't happen. 

### Actual behavior

When I try to perform a calculation in the application, it gives me the error that I would get if I hadn't sourced the setup script before trying to do the calculation.

### Steps to reproduce behavior

This is my definition file:

```
Bootstrap: docker
From: centos:7

%files
        /home/g16-B.01-x86_64_legacy-E6L-103X.tar.bz2 /usr/local/g16.tar.bz2

%environment
        export g16root=/usr/local
        export GAUSS_SCRDIR=/tmp

%post
        yum install -y bzip2
        cd /etc
        cp -p group group.bak
        cp -p gshadow gshadow.bak
        groupadd -g 499 gaussian
        cd /usr/local
        tar xvf g16.tar.bz2
        chown -R root:gaussian g16
        chmod -R o-rwx g16

%runscript
        source $g16root/g16/bsd/g16.profile
```

In my understanding, I should now be able to run g16 by running this command:

`singularity exec container_name.sif g16 < test0001.com > test0001.log.linux`

However, I get an error that a variable is not defined that should have been defined when I sourced the g16.profile script.

**Comment by jscook2345** [comment]
@annaprins 

Were you able to figure out your issue?

**Comment by annaprins** [comment]
@jscook2345 Yes! I'm not sure if I'm supposed to delete this or something. This is my first time posting here.

**Comment by GodloveD** [comment]
👋 I just saw this.  What was the solution?  Was it to use something like this?
```
%runscript
        . $g16root/g16/bsd/g16.profile
```

**Comment by jscook2345** [comment]
@annaprins 

Nope, you did the right thing by closing the issue. We just wanted to make sure you got things to work!

Welcome to Github!
