### ISSUE TITLE
Docs: Clarify User-define bind paths

### ISSUE THREAD

**Issue by robertlugg** [apptainer/singularity#3709]
## Version of Singularity:

3.2 User's Guide
Section 7.3: User-defined bind paths

### Actual behavior
"If the system administrator has enabled user control of binds, you will be able to request your own bind paths within your container."

It's possible to incorrectly infer something from the quote above.  The original question I wanted answered was "While inside of a container, is it possible to add additional bindings to host directories".  I believe the correct answer is "No".  However from the phrasing of the quoted text one can read "you will be able to request your own bind paths *within* your container" to mean that it is possible to add bindings to an already running container.

I don't know good wording but perhaps:
"If the system administrator has enabled user control of binds, you will be able to request your own bind paths _for use_ within your container."

**Comment by jscook2345** [comment]
@robertlugg 

I opened an issue in the `sylabs/singularity-userdocs` project. Thanks for the report!
