### ISSUE TITLE
Unable to create container from local .img 

### ISSUE THREAD

**Issue by moonisshah** [apptainer/singularity#3710]
## Version of Singularity: 2.6.0

I am running singularity 2.6.0 on  Ubuntu 18.04.1 LTS

### Expected behavior

I am intending to create a container of my Ubuntu which is installed on a harddisk with two partitions. One partition is for Home and one for root. I created .img for both of the paritions and proceeded to create the container for each .img. For home partition everything was smooth but for root partition it says unsupported file type. I tried to install the latest version of singularity as i read in one of the issues that updating solves the problem. But  i am unable to install the latest version. When i type ./autogen.sh it says no such file or directory. 

Please help :(

Cheers

![finl](https://user-images.githubusercontent.com/18448790/59243927-bf3c0000-8c55-11e9-9591-cb037c1ad46a.png)
![2](https://user-images.githubusercontent.com/18448790/59243995-00341480-8c56-11e9-9a1c-96288e2362f5.png)

**Comment by jscook2345** [comment]
@jmstover ping!

@moonisshah 

The latest version of `singularity` has a different build system and does not include the use of `autogen.sh`.

Install instructions can be found here:

https://github.com/sylabs/singularity/blob/master/INSTALL.md

**Comment by moonisshah** [comment]
`make
/home/moonis/go/src/github.com/sylabs/singularity/makeit/gengodep: 6: /home/moonis/go/src/github.com/sylabs/singularity/makeit/gengodep: go: not found
/home/moonis/go/src/github.com/sylabs/singularity/makeit/gengodep: 6: /home/moonis/go/src/github.com/sylabs/singularity/makeit/gengodep: go: not found
/bin/sh: 1: generate: not found
Makefile:147: recipe for target '/home/moonis/go/src/github.com/sylabs/singularity/internal/pkg/buildcfg/config.go' failed
make: *** [/home/moonis/go/src/github.com/sylabs/singularity/internal/pkg/buildcfg/config.go] Error 127
`



Hi @jscook2345 Thanks  for responding. This is what happens when i am trying to compile singularity .., :(

**Comment by jscook2345** [comment]
@moonisshah 

Do you not `go` installed? It is required to build `singularity`

example:

```
$ which go
/usr/local/bin/go
```

**Comment by rherban** [comment]
@moonisshah Did the instructions we shared help with installing?

Our quickstart guide is available here as well:
https://sylabs.io/guides/3.3/user-guide/quick_start.html

**Comment by mem** [comment]
If you have further details to share, please reopen the issue or submit a new one.

Thanks for taking the time to report this!
