### ISSUE TITLE
False warning when wmem_default buffer size is set to minimum recommended value

### ISSUE THREAD

**Issue by justwheel** [apptainer/singularity#3715]
Hi, I noticed this bug when I was Singularity for the first time. It doesn't get in the way or affect functionality, but it is a little annoying when it appears in stdout each time I interact with an SIF image.

## Version of Singularity:

v3.2.1

### Expected behavior

```bash
$ cat /proc/sys/net/core/wmem_default
65536

$ singularity exec fedora.sif cat /etc/os-release
NAME=Fedora
VERSION="30 (Container Image)"
[…]
```

### Actual behavior

```bash
$ cat /proc/sys/net/core/wmem_default
65536

$ singularity exec fedora.sif cat /etc/os-release
WARNING: current buffer size is 65536, you may encounter some issues
WARNING: the minimum recommended value is 65536, you can adjust this value with:
WARNING: "echo 65536 > /proc/sys/net/core/wmem_default"
NAME=Fedora
VERSION="30 (Container Image)"
[…]
```

### Steps to reproduce behavior

Enter an interactive shell or `exec` into any container. This is a fresh install of Singularity: no prior installs exist. I am using Singularity on RHEL Workstation 7.5.

**Comment by cclerget** [comment]
Hi @jwflory , this is due to a bad check `<=` instead of `<`. Will fix that shortly

**Comment by justwheel** [comment]
Wow, awesome! That was fast.
