### ISSUE TITLE
Bind doesn't work twice

### ISSUE THREAD

**Issue by chrisreidy** [apptainer/singularity#372]
Hi 
I ran bootstrap against a definition with these lines in %Post:
+ /usr/local/bin/mpicc examples/ring_c.c -o /usr/bin/mpi_ring
+ cd /
+ rm -rf /tmp/git
+ mkdir /extra
+ exit 0
+ /usr/local/bin/mpirun --allow-run-as-root /usr/bin/mpi_ring

This is mostly from one of the User Guide and it works fine.
When I make a change to the def file and run bootstrap again I get:
+ /usr/local/bin/mpicc examples/ring_c.c -o /usr/bin/mpi_ring
+ cd /
+ rm -rf /tmp/git
+ mkdir /extra
mkdir: cannot create directory '/extra': File exists
ERROR: Aborting with RETVAL=255

It seems like this should not be a fatal error, or an error at all

Thanks
Chris

**Comment by vsoch** [comment]
By default, the bootstrap will fail with any error in the `%post`. Doing the mkdir command finds that it already exists, which spits out the error. Did you try:

     mkdir -p /extra

I think that should make the directory only if it doesn't exist.

**Comment by chrisreidy** [comment]
Well that was an easy fix.
Thanks Vanessa

**Comment by vsoch** [comment]
Awesome! Glad to help. I'm going to close the issue, ping again if needed!
