### ISSUE TITLE
ext3 persistent overlay only writable by user in certain paths (permission denied)

### ISSUE THREAD

**Issue by justwheel** [apptainer/singularity#3721]
## Version of Singularity:

3.2.1

### Expected behavior

```bash
$ singularity shell --overlay my-overlay some-image.sif

~> touch /etc/hello_world
~> ls /etc/hello_world
/etc/hello_world

~> touch /etc/ssl/hello_world
~> ls /etc/ssl/hello_world
/etc/ssl/hello_world
```

### Actual behavior

```bash
$ singularity shell --overlay my-overlay some-image.sif

~> touch /etc/hello_world
~> ls /etc/hello_world
/etc/hello_world

~> touch /etc/ssl/hello_world
touch: cannot touch '/etc/ssl/hello_world': Permission denied
```

### Steps to reproduce behavior

I was specifically using a Tensorflow nightly image that I built locally with Singularity. Then I created an ext3 FS image and used it locally as an overlay.

```bash
$ singularity build tf-nightly.sif docker://tensorflow/tensorflow:nightly
$ dd if=/dev/zero of=my_overlay bs=1M count=10 && mkfs.ext3 my-overlay
$ singularity shell --overlay my-overlay ./tf-nightly.sif
```

**Comment by cclerget** [comment]
@jwflory When you build image into SIF, all files/directories of container filesystem are owned by root:root. If you want to get rid of that to use an overlay image you will need to build container image as directory instead `singularity build -s tf-nightly.sif docker://tensorflow/tensorflow:nightly`, then you will own container filesystem files/directories

**Comment by justwheel** [comment]
@cclerget I understand now. I think this issue could be resolved with an improvement to the [Bind Paths and Mounts](https://www.sylabs.io/guides/3.2/user-guide/bind_paths_and_mounts.html) documentation page. That's what I was using as my reference prior to filing this issue.

I didn't know about the `--sandbox` flag! This is really cool. However, it doesn't fully address my use case. I need to run a command in the container to modify files in the `/etc/ssl/certs/` path. In this case, I am embedding corporate TLS certificates into an image built off of Docker Hub (Tensorflow in my case). To do that, I pass a directory from the host to `/usr/local/share/ca-certificates/` in the container as a bind path and run `update-ca-certificates` command in the container, which creates symbolic links in `/etc/ssl/certs/`.

My workaround is to run Singularity with the empty overlay as `root` the first time and run `update-ca-certificates`. Then a user could run as non-root with the overlay I created. This solves the TLS certs issue I have today. For my workflow, a user could build an overlay themselves on a local workstation or an admin user could provide an overlay in a shared path, and then they can run images they want without an admin user having to support a specific user's needs.

Does this make sense? I can submit a docs PR since I know Sphinx but I would like guidance on what you think makes sense to include and where to include it.

**Comment by cclerget** [comment]
@jwflory Ok I understand, maybe you could simplify steps by using a definition file with :

```
bootstrap: docker
from: tensorflow/tensorflow:nightly

%setup
    cp /usr/local/share/ca-certificates/corporate.pem $SINGULARITY_ROOTFS/etc/ssl/certs/
```

And build it with `sudo singularity build tf-nightly.sif file.def`

**Comment by justwheel** [comment]
@cclerget I'm not sure this works since `update-ca-certificates` writes changes out in the container to `/etc/ssl/certs/` from certs loaded in at `/usr/local/share/ca-certificates/`. I tried `--bind`ing local certs to `/etc/ssl/certs/` originally, but `update-ca-certificates` must create the symbolic links in `/etc/ssl/certs/` at runtime for this to work (as I understand).

**Comment by cclerget** [comment]
@jwflory well you can do that :
```
bootstrap: docker
from: tensorflow/tensorflow:nightly

%setup
    cp /usr/local/share/ca-certificates/corporate.pem $SINGULARITY_ROOTFS/usr/local/share/ca-certificates/

%post
    update-ca-certificates
```

**Comment by justwheel** [comment]
D'oh. Yes, this does work and meets the TLS certs use case, I didn't pay enough attention in the Def Files docs. Thanks! :+1: 

That said, I still have a use case for non-root users to pull images from Docker Hub and use an ext3 overlay they create to write files into their container. A real-world use case for this might be using an [anaconda container image](https://hub.docker.com/r/continuumio/anaconda) for users to set up a particular set of custom software for an HPC job. The behavior described in the original comment still doesn't make sense to me. Do you think it's a bug or should the documentation be updated to better explain how persistent overlays work with local ext3 FS images?

**Comment by rherban** [comment]
I realize you've got a working solution, but I've been thinking about this a little bit more and while I can't reproduce your exact use-case, I think I understand why it's happening.  Whether or not it's ideal is another question.


If I create an ext3 image same as you, I'm unable to write to `/etc` or `/etc/ssl`
```
[rherban@test]:/tmp$ singularity shell --overlay ext3.img ~/test.sif
Singularity test.sif:/tmp> touch /etc/blah
touch: cannot touch ‘/etc/blah’: Permission denied
Singularity test.sif:/tmp> touch /etc/ssl/blah
touch: cannot touch ‘/etc/ssl/blah’: Permission denied
```
This is because while you have an overlay you can write to, you still don't have permissions on that directory.

Going into the container as root and chown'ing allows you to write as a normal user...see below:
```
[rherban@test]:/tmp$ sudo singularity shell --overlay ext3.img ~/test.sif
Singularity test.sif:/tmp> chmod 777 /bin
Singularity test.sif:/tmp> exit
[rherban@test]:/tmp$ singularity shell --overlay ext3.img ~/test.sif
Singularity test.sif:/tmp> whoami
rherban
Singularity test.sif:/tmp> touch /bin/HELLO
Singularity test.sif:/tmp> exit
```

And running the container without the overlay:
```
[rherban@test]:/tmp$ singularity shell ~/test.sif
Singularity test.sif:/tmp> ls -las /bin/HELLO
ls: cannot access /bin/HELLO: No such file or directory
```

So, is the documentation lacking or should a normal user have write access to the full overlayed filesystem? Are there other security implications from user having full write?
@cclerget @jmstover @cclerget

**Comment by cclerget** [comment]
Resolved
