### ISSUE TITLE
Unit tests cannot rely on the SINGULARITY_CACHEDIR environment variable because of thread safety problems

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3722]
## Version of Singularity:

Master

### Expected behavior

The development team seems to agree that it would be beneficial for unit tests to be able to set and use their own private temporary image cache. An option to implement this would be to create a handle that represents an image cache and use it throughout the unit test(s) as required. In other terms, be able to create a temporary image cache, use it, potentially share it and clean it at the end.

### Actual behavior

Relying on the `SINGULARITY_CACHEDIR` environment variable in unit tests to specify the location of the image cache is not thread safe. As a result, a unit test that would like to change the value of the environment is required either to not be multi-threaded (Go will run unit tests in parallel) or rely only on a handle/object that will describe a given image cache (see #3592).
It seems to be the main reason why unit tests were initially shared a single location as image cache, i.e., `/tmp/WithPrivilege` or `/tmp/WithPrivilege`. As a result, it is also unsafe to clean a cache in the context of a test since it may impact the behavior of a concurrent test relying on the same image cache.

An effect of this problem is that unit tests are *not* supposed to call the Singularity CLI (for instance to pull an image) because the image cache location can only be specified by the unit test through the environment variable and therefore make it safe-unsafe.

### Steps to reproduce behavior

Experienced failures while running the test in `internal/pkg/client/cache` on a SMP Ubuntu machine.

**Comment by cclerget** [comment]
@gvallee If I understood correctly, all tests inside a single `_test.go` are executed sequentially unless `t.Parallel` is explicitly set for a sub-test `t.Run` and `-parallel` flag is passed with a number greater than 1. But multiple `_test.go` files in different packages can be executed in parallel, maybe we could force to run unit test sequentially with `sudo go test -parallel 1 ...` or with `GOMAXPROCS=1` to ensure that only one test file is executed at a time

**Comment by gvallee** [comment]
@cclerget Your comment made me realize that the explanation I gave was partially wrong. The problem is not using `t.Run()` but rather than Go run the individual unit tests in parallel. I updated the issue.

Also, yes your suggestion would be a very decent work-around but maybe we should also come up with a long term solution.
