### ISSUE TITLE
Emit progress information during SIF creation

### ISSUE THREAD

**Issue by mikegray** [apptainer/singularity#3725]
## Version of Singularity:

3.0.3

### Expected behavior

Some progress or update information during the creation of the SIF file.

### Actual behavior

During "Creating SIF file..." step, the console does not produce any visible output for the user - but does create the resulting file eventually.

### Steps to reproduce behavior

I was executing a few “larger” builds through the build service as I am testing a few things and I keep noticing that output freezes (temporarily) during `INFO:    Creating SIF file...`. Is it possible to have some type of useful progress during that step? It appears to take awhile but is dependent on maybe the size of the SIF being created? @ikaneshiro mentioned maybe using the progress provided by `mksquashfs`.

**Comment by ikaneshiro** [comment]
@mikegray We are currently not forwarding stdout of mksquashfs, so it is running silently in the background. I _think_ we can forward that output through `sylog` so that a user can get more or less detail by using normal levels of verbosity e.g. `-d`,`-s`, etc

**Comment by mgroth0** [comment]
Hi, I'm currently running into an issue where my build is seemingly hanging on "INFO: Creating SIF file..." for hours. Eventually, I have to quit the build, because I assume it froze. Builds previously took less than an hour before I switched from singularity 2 to 3. Having extra output here could be helpful.

**Comment by kyriakosschwarz** [comment]
I agree, it is very slow, so at least some output would be nice.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by mgroth0** [comment]
1. Last I checked, this issue has not been fixed. I do not know if its a duplicate.
2. It's relevant to improving the experiencing of building containers. More verbose log output helps you optimize builds and identify problems.
3. @ikaneshiro's proposed solution is to forward `makesquashfs` output when user uses the `-d` or `-s` verbosity switches. I, and I'm sure the rest of the community, would greatly appreciate this!

**Comment by vmiheer** [comment]
I ran into this issue. And it's really frustrating to know especially on clusters.

**Comment by pedroalvesbatista** [comment]
@mikegray We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by urlicht** [comment]
Also have the same problem with "large" builds. It'd be great to get a progress bar or some sort of info on the progress/process. On some builds, it hangs on the `INFO: Creating SIF file...` for a very long time. Eventually I run out of the time on the cluster job, so I haven't tried waiting longer (e.g. over 3 hrs)

**Comment by kmuriki** [comment]
Pending issues from the old repo are moved to the new repo (https://github.com/apptainer/apptainer/issues/1391) and cleaned from the old, retired repo

**Comment by TheoMathurin** [comment]
I also run into cases where builds for large containers (a few GB) seemingly hang at the "INFO:    Creating SIF file..." stage. After a few hours I kill the process as I assume it's stuck. Are there factors that are known or suspected to cause this issue? 

From what I've read, it seems like we can now make it more verbose using `--mksquashfs-args`, but it's not clear to me how this should be used and what are the relevant arguments.

**Comment by DrDaveD** [comment]
This repository is closed.  If you have an issue with a version of singularity >3.8.7 make a new issue at https://github.com/sylabs/singularity, otherwise make a new issue at https://github.com/apptainer/apptainer.   Apptainer now shows progress bars by default when building a SIF file.
