### ISSUE TITLE
Update 3.x documentation to include singularity security approach

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#3727]
## Version of Singularity:

3.x documentation

### Expected behavior

Expect a description of singularity's approach to security

### Actual behavior

It hasn't been ported forward since [2.6](https://www.sylabs.io/guides/2.6/user-guide/introduction.html#security-and-privilege-escalation)

Probably also the general intro from 2.6 should be ported forward.

**Comment by jscook2345** [comment]
This is something that should make it into the user guide at some point, but understanding the model and diagramming / describing it should probably be started off development.

What are some examples of things that should be included?
* Features that are security based (linux security modules)
* Basic admin abilities via configurations (don't fully document config, just say what they can do)

Others?

**Comment by DrDaveD** [comment]
My advice is to not be too perfectionist about it, but to get something out there that's accurate first even if it isn't complete.  Don't let great be the enemy of good.

**Comment by dtrudg** [comment]
This was closed via https://github.com/sylabs/singularity-userdocs/issues/291 - there is content in the admin guide now too. It was adapted and expanded from the referenced 2.x content.
