### ISSUE TITLE
Can't open shell in singularity image

### ISSUE THREAD

**Issue by eliotlyon** [apptainer/singularity#3734]
## Version of Singularity:

v3.2.1

### Expected behavior

`$ singularity shell image.sif` opens a shell in `image.sif`

### Actual behavior

`$ singularity shell image.sif` results in the error
`FATAL:   container creation failed: mount /proc/self/fd/3->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount squashfs filesystem: no such device`

### Steps to reproduce behavior

I built Singularity RPMs this morning on a fully-updated CentOS 7.6, using only default options.
I created an image using this definition file:
```
Bootstrap: scratch

%setup
yum install --assumeyes --releasever=7 --installroot $SINGULARITY_ROOTFS --setopt=override_install_langs=en_US.UTF-8 bash coreutils
rm -r $SINGULARITY_ROOTFS/var/cache/yum
```
On this machine, `singularity shell image.sif` produces a shell as expected.

I then transferred those RPMs and image.sif to an offline Red Hat Enterprise Linux 7.6 machine.  After installing the RPMs, `singularity shell image.sif` produces the error reported above.  I get the same result if I build the image on the offline machine.

I don't see any errors in dmesg or journalctl.

**Comment by jmstover** [comment]
@eliotlyon 
First off... on the machine you're running on, does it have the `loop` module loaded?

Also, it'll need any possible squashfs compression modules loaded. I *think* xz is needed as I believe that's the default compression on mksquashfs.

**Comment by eliotlyon** [comment]
`loop` was loaded.

`squashfs` wasn't, and while investigating that, I discovered our sysadmins had it blacklisted (via `install squashfs /bin/true` in a conf file in `/etc/modprobe.d`).  Apparently the blacklisting is intended to help harden the system.  Commenting out that line for testing purposes caused singularity to begin working.

Thanks for the pointer!
