### ISSUE TITLE
setup of docker registry is not properly teared down when a test fails

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3738]
We setup a docker registry before calling all the tests. However if any of those tests fail, the defer call to tear down the docker registry will not be run and that will leave the docker daemon in an inconsistent state that causes test failures until it is manually cleaned up.

If services like this are required it would be best to setup/teardown on a per-test basis rather than for the entire test suite.

We than probably also need proper per-test and per-suite setup and teardown abilities.

**Comment by jscook2345** [comment]
See also: https://github.com/sylabs/singularity/issues/3701

**Comment by jscook2345** [comment]
Of course when I go to try and fix this I can't reproduce it. :) I also had some intermittent issues with cache directories but I guess we'll see.

**Comment by dtrudg** [comment]
Registry setup was redone, and I don't believe this is an issue now from work during PRO3.5 QA
