### ISSUE TITLE
Commands using oras:// images should use docker credentials

### ISSUE THREAD

**Issue by vincentlabonte** [apptainer/singularity#3739]
## Version of Singularity:

Master b3a1daefbcb4ab40d674b4fa23c3548ef79fc634

### Expected behavior

Commands (pull/push/run/exec) using oras:// images should use docker credentials file (/home/user/.docker/config.json). This behavior is already implemented for docker:// images and is also implemented by the ORAS CLI.

### Actual behavior

Commands (pull/push/run/exec) using oras:// images don't use docker credentials file (/home/user/.docker/config.json).
We need to manually specify SINGULARITY_DOCKER_USERNAME and SINGULARITY_DOCKER_PASSWORD environment variables or --docker-username and --docker-password command arguments.

### Steps to reproduce behavior

```
$ oras pull registry.azurecr.io/image_sif:latest
Error: failed to fetch anonymous token: unexpected status: 401 Unauthorized

$ docker login registry.azurecr.io
Username: username
Password:
WARNING! Your password will be stored unencrypted in /home/user/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded

$ oras pull registry.azurecr.io/image_sif:latest
Pulled registry.azurecr.io/image_sif:latest
Digest: sha256:5ee26e8c4c62e9ec4e9fd051c1f533064342cc953dbcf4d3733b4c31c040d6fc

$ singularity pull docker://registry.azurecr.io/test/image:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:a67ed5adc1103832cff3e0029d541e6abc196ba04c041d5f7ec3c33877547b6f
Skipping fetch of repeat blob sha256:05731e67258c3810870e3cd9a5c062a725f211053a697fb339cc6aa54adfb6a2
Skipping fetch of repeat blob sha256:0bd676f788345ec66b7ac2d6e4b29a9f46beeb55104bfbea3b0847712a0
Copying config sha256:dc480994cb8cc60729342d1995ce8f80bf60332eaef0e8656037827e6457
 2.54 KiB / 2.54 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: /home/user/.singularity/cache/oci-tmp/11b7a8b47f76ae759484866139dfb902187577be0b4793b836e1f9d60733c7c4/image_latest.sif

$ singularity pull oras://registry.azurecr.io/image_sif:latest
FATAL:   While pulling image from oci registry: failed to get checksum for //registry.azurecr.io/image_sif:latest: while resolving reference: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@vincentlabonte Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Singularity repo is now retired as the code base is now moved to Apptainer. We are closing all the old issues under the old Singularity repo. For further assistance please open a new issue under the new Apptainer repo. Thanks for your support.
