### ISSUE TITLE
Cache commands should support oras type images

### ISSUE THREAD

**Issue by vincentlabonte** [apptainer/singularity#3740]
## Version of Singularity:

Master b3a1dae

### Expected behavior

The cache list command should output images of type oras.
The cache clean command should remove cached images of type oras.

### Actual behavior

The `singularity cache list` command only outputs images of type library, oci, shub.
The `singularity cache clean` command only removes cached images of type library, oci, shub.

### Steps to reproduce behavior

```
$ singularity pull -F oras://registry.azurecr.io/image_sif:latest
INFO:    Downloading image with ORAS
INFO:    Pull complete: image_sif_latest.sif

$ singularity cache list
NAME                     DATE CREATED           SIZE             TYPE
There 0 containers using: 0.00 kB, 0 oci blob file(s) using 0.00 kB of space.
Total space used: 0.00 kB

$ singularity cache clean -a

$ singularity pull -F oras://registry.azurecr.io/image_sif:latest
INFO:    Using cached image
INFO:    Pull complete: image_sif_latest.sif
```

**Comment by WestleyK** [comment]
Fixed by https://github.com/sylabs/singularity/pull/3720
