### ISSUE TITLE
Cached image should be used before looking up the registry

### ISSUE THREAD

**Issue by vincentlabonte** [apptainer/singularity#3741]
## Version of Singularity:

Master b3a1dae

### Expected behavior

Cached image should be used before looking up the registry.

### Actual behavior

Retrieving the SHA of the image from the registry and using the cached image corresponding to the SHA.

### Steps to reproduce behavior

Note: `docker://vincentlabo/private` is a private Docker Hub repository. The same behavior can also be observed with oras:// images.  

```
$ docker login

$ singularity exec docker://vincentlabo/private /bin/sh -c "echo hello"
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:a67ed5adc1103832cff3e0029d541e6abc196ba04c041d5f7ec3c33877547b6f
Skipping fetch of repeat blob sha256:05731e67258c3810870e3cd9a5c062a725f211053a697fb339cc6aa54adfb6a2
Skipping fetch of repeat blob sha256:0bd676f788345ec66b7ac2d6e4b29a9f46beeb55104bfbea3b0847712a0
Copying config sha256:dc480994cb8cc60729342d1995ce8f80bf60332eaef0e8656037827e6457
 2.54 KiB / 2.54 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: /home/user/.singularity/cache/oci-tmp/11b7a8b47f76ae759484866139dfb902187577be0b4793b836e1f9d60733c7c4/private_latest.sif
hello

$ singularity cache list
NAME                        DATE CREATED             SIZE                 TYPE
private_latest.sif         2019-06-14 16:22:08    28.00 MB         oci
There 1 containers using: 28.00 MB, 5 oci blob file(s) using 28.86 MB of space.
Total space used: 56.86 MB

$ docker logout

$ singularity exec docker://vincentlabo/private /bin/sh -c "echo hello"
FATAL:   Unable to handle docker://vincentlabo/private uri: failed to get SHA of docker://vincentlabo/private: Error reading manifest latest in docker.io/vincentlabo/private: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

This is mostly a question.

**Comment by ikaneshiro** [comment]
@vincentlabonte This is intentional. We want to make sure we are using the image reflected by the uri at the time the command is run. Since images can change underneath a tag, we need to reach out to the registry to ensure our cached image is what we are looking for. 

If you want to use an image without authenticating with the registry every time I would recommend using `singularity build` to create a local image that's easy to work with

**Comment by vincentlabonte** [comment]
Thanks @ikaneshiro that answers my question! Feel free to close this issue.
