### ISSUE TITLE
error: can't mount overlay filesystem 

### ISSUE THREAD

**Issue by pyc1216** [apptainer/singularity#3743]
## Version of Singularity:

3.2.1-627.gfae3307

### Expected behavior

Activate a container.

### Actual behavior

`FATAL:   container creation failed: mount overlay->/usr/local/var/singularity/mnt/session/final error: can't mount overlay filesystem to /usr/local/var/singularity/mnt/session/final: invalid argument`

### Steps to reproduce behavior

singularity shell lolcow_latest.sif

**Comment by cclerget** [comment]
Hi @pyc1216 , in order to help to determine issue, I would need more details :
- your distribution and kernel version
- output of `singularity -d shell lolcow_latest.sif`
- output of `dmesg`

**Comment by pyc1216** [comment]
> Hi @pyc1216 , in order to help to determine issue, I would need more details :
> 
> * your distribution and kernel version
> * output of `singularity -d shell lolcow_latest.sif`
> * output of `dmesg`

hi @cclerget ，thank you for replying.
- my distribution:
Linux Mint 17.3 Rosa \n \l
- my kernel version:
Linux suzhou 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- output of `singularity -d shell lolcow_latest.sif`
[    ypu@suzhou:singularity] $> singularity -d run library://sylabsed/examples/lolcow
    DEBUG   [U=1008,P=59360]   apiGet()                      apiGet calling https://library.sylabs.io/v1/images/sylabsed/examples/lolcow:latest
    DEBUG   [U=1008,P=59360]   updateCacheSubdir()           Caching directory set to /home/ypu/.singularity/cache/library/sha256.e37e11f101a9db82a08bf63f816219da0d4da0e19f5323761d92731213c9e751
    DEBUG   [U=1008,P=59360]   updateCacheSubdir()           Caching directory set to /home/ypu/.singularity/cache/library
    DEBUG   [U=1008,P=59360]   updateCacheSubdir()           Caching directory set to /home/ypu/.singularity/cache/library/sha256.e37e11f101a9db82a08bf63f816219da0d4da0e19f5323761d92731213c9e751
    DEBUG   [U=1008,P=59360]   updateCacheSubdir()           Caching directory set to /home/ypu/.singularity/cache/library
    VERBOSE [U=0,P=59360]      print()                       Set messagelevel to: 5
    DEBUG   [U=0,P=59360]      init()                        PIPE_EXEC_FD value: 9
    VERBOSE [U=0,P=59360]      init()                        Container runtime
    VERBOSE [U=0,P=59360]      is_suid()                     Check if we are running as setuid
    DEBUG   [U=0,P=59360]      init()                        Overlay seems supported by kernel
    DEBUG   [U=0,P=59360]      init()                        Drop privileges
    DEBUG   [U=1008,P=59360]   init()                        Read json configuration from pipe
    DEBUG   [U=1008,P=59360]   init()                        Set child signal mask
    DEBUG   [U=1008,P=59360]   init()                        Wait completion of stage1
    VERBOSE [U=1008,P=59391]   priv_escalate()               Get root privileges
    DEBUG   [U=0,P=59391]      set_parent_death_signal()     Set parent death signal to 9
    DEBUG   [U=0,P=59391]      prepare_stage()               Entering in stage 1
    DEBUG   [U=1008,P=59391]   set_parent_death_signal()     Set parent death signal to 9
    VERBOSE [U=1008,P=59391]   init()                        Spawn stage 1
    VERBOSE [U=1008,P=59391]   startup()                     Execute stage 1
    DEBUG   [U=1008,P=59391]   Stage()                       Entering stage 1
    DEBUG   [U=1008,P=59391]   Init()                        Entering image format intializer
    DEBUG   [U=1008,P=59391]   Init()                        Check for image format sif
    DEBUG   [U=1008,P=59360]   init()                        Create socketpair for master communication channel
    DEBUG   [U=1008,P=59360]   cleanup_fd()                  Check file descriptor /proc/self/fd/3 pointing to /home/ypu/.singularity/cache/library/sha256.e37e11f101a9db82a08bf63f816219da0d4da0e19f5323761d92731213c9e751/lolcow_latest.sif
    DEBUG   [U=1008,P=59360]   cleanup_fd()                  Check file descriptor /proc/self/fd/4 pointing to anon_inode:[eventpoll]
    DEBUG   [U=1008,P=59360]   cleanup_fd()                  Closing /proc/self/fd/4
    VERBOSE [U=1008,P=59360]   priv_escalate()               Get root privileges
    VERBOSE [U=0,P=59360]      create_namespace()            Create mount namespace
    DEBUG   [U=0,P=59360]      init()                        Create RPC socketpair for communication between stage 2 and RPC server
    DEBUG   [U=0,P=59360]      set_terminal_control()        Pass terminal control to child
    VERBOSE [U=0,P=59360]      init()                        Spawn master process
    DEBUG   [U=0,P=59398]      set_parent_death_signal()     Set parent death signal to 9
    VERBOSE [U=0,P=59398]      create_namespace()            Create mount namespace
    DEBUG   [U=0,P=59398]      set_parent_death_signal()     Set parent death signal to 9
    DEBUG   [U=0,P=59398]      prepare_stage()               Entering in stage 2
    DEBUG   [U=1008,P=59398]   set_parent_death_signal()     Set parent death signal to 9
    VERBOSE [U=0,P=59399]      init()                        Spawn RPC server
    VERBOSE [U=0,P=59399]      startup()                     Serve RPC requests
    VERBOSE [U=1008,P=59360]   startup()                     Execute master process
    DEBUG   [U=1008,P=59360]   setupSessionLayout()          Attempting to use overlayfs (enable overlay = try)
    DEBUG   [U=1008,P=59360]   setupOverlayLayout()          Creating overlay SESSIONDIR layout
    DEBUG   [U=1008,P=59360]   addRootfsMount()              Mount rootfs in read-only mode
    DEBUG   [U=1008,P=59360]   addRootfsMount()              Mounting block [squashfs] image: /home/ypu/.singularity/cache/library/sha256.e37e11f101a9db82a08bf63f816219da0d4da0e19f5323761d92731213c9e751/lolcow_latest.sif
    DEBUG   [U=1008,P=59360]   addKernelMount()              Checking configuration file for 'mount proc'
    DEBUG   [U=1008,P=59360]   addKernelMount()              Adding proc to mount list
    VERBOSE [U=1008,P=59360]   addKernelMount()              Default mount: /proc:/proc
    DEBUG   [U=1008,P=59360]   addKernelMount()              Checking configuration file for 'mount sys'
    DEBUG   [U=1008,P=59360]   addKernelMount()              Adding sysfs to mount list
    VERBOSE [U=1008,P=59360]   addKernelMount()              Default mount: /sys:/sys
    DEBUG   [U=1008,P=59360]   addDevMount()                 Checking configuration file for 'mount dev'
    DEBUG   [U=1008,P=59360]   addDevMount()                 Adding dev to mount list
    VERBOSE [U=1008,P=59360]   addDevMount()                 Default mount: /dev:/dev
    DEBUG   [U=1008,P=59360]   addHostMount()                Not mounting host file systems per configuration
    VERBOSE [U=1008,P=59360]   addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
    VERBOSE [U=1008,P=59360]   addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
    DEBUG   [U=1008,P=59360]   addHomeStagingDir()           Staging home directory (/home/ypu/) at /usr/local/var/singularity/mnt/session/home/ypu
    DEBUG   [U=1008,P=59360]   addHomeMount()                Adding home directory mount [/usr/local/var/singularity/mnt/session/home/ypu:/home/ypu/] to list using layer: overlay
    DEBUG   [U=1008,P=59360]   isLayerEnabled()              Using Layer system: overlay
    DEBUG   [U=1008,P=59360]   addTmpMount()                 Checking for 'mount tmp' in configuration file
    VERBOSE [U=1008,P=59360]   addTmpMount()                 Default mount: /tmp:/tmp
    VERBOSE [U=1008,P=59360]   addTmpMount()                 Default mount: /var/tmp:/var/tmp
    DEBUG   [U=1008,P=59360]   addScratchMount()             Not mounting scratch directory: Not requested
    VERBOSE [U=1008,P=59360]   addCwdMount()                 Default mount: /home/ypu/2-Soft/1-Source/singularity: to the container
    DEBUG   [U=1008,P=59360]   addLibsMount()                Checking for 'user bind control' in configuration file
    DEBUG   [U=1008,P=59360]   addResolvConfMount()          Adding /etc/resolv.conf to mount list
    VERBOSE [U=1008,P=59360]   addResolvConfMount()          Default mount: /etc/resolv.conf:/etc/resolv.conf
    DEBUG   [U=1008,P=59360]   addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
    DEBUG   [U=1008,P=59360]   create()                      Mount all
    DEBUG   [U=1008,P=59360]   mountGeneric()                Mounting tmpfs to /usr/local/var/singularity/mnt/session
    DEBUG   [U=1008,P=59360]   mountImage()                  Mounting loop device /dev/loop0 to /usr/local/var/singularity/mnt/session/rootfs
    DEBUG   [U=1008,P=59360]   mountGeneric()                Mounting overlay to /usr/local/var/singularity/mnt/session/final
    DEBUG   [U=1008,P=59360]   CleanupContainer()            Cleanup container
    FATAL   [U=1008,P=59360]   Master()                      container creation failed: mount overlay->/usr/local/var/singularity/mnt/session/final error: can't mount overlay filesystem to /usr/local/var/singularity/mnt/session/final: invalid argument

- output of dmesg
    [ypu@suzhou:singularity] $> dmesg |tail
    [4526481.875661] overlayfs: missing upperdir or lowerdir or workdir
    [4526481.902962] overlayfs: missing upperdir or lowerdir or workdir
    [4530421.995524] overlayfs: missing upperdir or lowerdir or workdir
    [4530422.047568] overlayfs: missing upperdir or lowerdir or workdir
    [4530539.488620] overlayfs: missing upperdir or lowerdir or workdir
    [4530539.543882] overlayfs: missing upperdir or lowerdir or workdir
    [4530766.443803] overlayfs: missing upperdir or lowerdir or workdir
    [4530766.497368] overlayfs: missing upperdir or lowerdir or workdir
    [4530939.239796] overlayfs: missing upperdir or lowerdir or workdir
    [4530939.295959] overlayfs: missing upperdir or lowerdir or workdir

**Comment by cclerget** [comment]
Can you try with this release https://github.com/sylabs/singularity/releases/tag/v3.2.1 to check if there is a regression with a recent merged feature

**Comment by cclerget** [comment]
@pyc1216 I just realized that debug output show an old `starter` debug line which should not be there with the version `3.2.1-627.gfae3307` you use. I would suggest to recompile it :

```
./mconfig
make -C builddir
sudo make -C builddir install
```

**Comment by pyc1216** [comment]
> @pyc1216 I just realized that debug output show an old `starter` debug line which should not be there with the version `3.2.1-627.gfae3307` you use. I would suggest to recompile it :
> 
> ```
> ./mconfig
> make -C builddir
> sudo make -C builddir install
> ```
@cclerget 


> Can you try with this release https://github.com/sylabs/singularity/releases/tag/v3.2.1 to check if there is a regression with a recent merged feature

@cclerget 
I tried this releases v3.2.1, but it seems the same error. 
- singularity version: 3.2.1-1

- output of `singularity -d shell lolcow_latest.sif`
DEBUG   [U=1008,P=119115]  apiGet()                      apiGet calling https://library.sylabs.io/v1/images/sylabsed/examples/lolcow:latest
DEBUG   [U=1008,P=119115]  updateCacheSubdir()           Caching directory set to /home/ypu/.singularity/cache/library/sha256.e37e11f101a9db82a08bf63f816219da0d4da0e19f5323761d92731213c9e751
DEBUG   [U=1008,P=119115]  updateCacheSubdir()           Caching directory set to /home/ypu/.singularity/cache/library
DEBUG   [U=1008,P=119115]  updateCacheSubdir()           Caching directory set to /home/ypu/.singularity/cache/library/sha256.e37e11f101a9db82a08bf63f816219da0d4da0e19f5323761d92731213c9e751
DEBUG   [U=1008,P=119115]  updateCacheSubdir()           Caching directory set to /home/ypu/.singularity/cache/library
VERBOSE [U=0,P=119115]     print()                       Set messagelevel to: 5
DEBUG   [U=0,P=119115]     init()                        PIPE_EXEC_FD value: 9
VERBOSE [U=0,P=119115]     init()                        Container runtime
VERBOSE [U=0,P=119115]     is_suid()                     Check if we are running as setuid
DEBUG   [U=0,P=119115]     init()                        Overlay seems supported by kernel
DEBUG   [U=0,P=119115]     init()                        Drop privileges
DEBUG   [U=1008,P=119115]  init()                        Read json configuration from pipe
DEBUG   [U=1008,P=119115]  init()                        Set child signal mask
DEBUG   [U=1008,P=119115]  init()                        Wait completion of stage1
VERBOSE [U=1008,P=119142]  priv_escalate()               Get root privileges
DEBUG   [U=0,P=119142]     set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=119142]     prepare_stage()               Entering in stage 1
DEBUG   [U=1008,P=119142]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1008,P=119142]  init()                        Spawn stage 1
VERBOSE [U=1008,P=119142]  startup()                     Execute stage 1
DEBUG   [U=1008,P=119142]  Stage()                       Entering stage 1
DEBUG   [U=1008,P=119142]  Init()                        Entering image format intializer
DEBUG   [U=1008,P=119142]  Init()                        Check for image format sif
DEBUG   [U=1008,P=119115]  init()                        Create socketpair for master communication channel
DEBUG   [U=1008,P=119115]  cleanup_fd()                  Check file descriptor /proc/self/fd/3 pointing to /home/ypu/.singularity/cache/library/sha256.e37e11f101a9db82a08bf63f816219da0d4da0e19f5323761d92731213c9e751/lolcow_latest.sif
DEBUG   [U=1008,P=119115]  cleanup_fd()                  Check file descriptor /proc/self/fd/4 pointing to anon_inode:[eventpoll]
DEBUG   [U=1008,P=119115]  cleanup_fd()                  Closing /proc/self/fd/4
VERBOSE [U=1008,P=119115]  priv_escalate()               Get root privileges
VERBOSE [U=0,P=119115]     create_namespace()            Create mount namespace
DEBUG   [U=0,P=119115]     init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=0,P=119115]     init()                        Spawn master process
DEBUG   [U=0,P=119148]     set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=119148]     create_namespace()            Create mount namespace
DEBUG   [U=0,P=119148]     set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=119148]     prepare_stage()               Entering in stage 2
DEBUG   [U=1008,P=119148]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=119149]     init()                        Spawn RPC server
VERBOSE [U=0,P=119149]     startup()                     Serve RPC requests
VERBOSE [U=1008,P=119115]  startup()                     Execute master process
DEBUG   [U=1008,P=119115]  setupSessionLayout()          Attempting to use overlayfs (enable overlay = try)
DEBUG   [U=1008,P=119115]  setupOverlayLayout()          Creating overlay SESSIONDIR layout
DEBUG   [U=1008,P=119115]  addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=1008,P=119115]  addRootfsMount()              Mounting block [squashfs] image: /home/ypu/.singularity/cache/library/sha256.e37e11f101a9db82a08bf63f816219da0d4da0e19f5323761d92731213c9e751/lolcow_latest.sif
DEBUG   [U=1008,P=119115]  addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=1008,P=119115]  addKernelMount()              Adding proc to mount list
VERBOSE [U=1008,P=119115]  addKernelMount()              Default mount: /proc:/proc
DEBUG   [U=1008,P=119115]  addKernelMount()              Checking configuration file for 'mount sys'
    DEBUG   [U=1008,P=119115]  addKernelMount()              Adding sysfs to mount list
    VERBOSE [U=1008,P=119115]  addKernelMount()              Default mount: /sys:/sys
    DEBUG   [U=1008,P=119115]  addDevMount()                 Checking configuration file for 'mount dev'
    DEBUG   [U=1008,P=119115]  addDevMount()                 Adding dev to mount list
    VERBOSE [U=1008,P=119115]  addDevMount()                 Default mount: /dev:/dev
    DEBUG   [U=1008,P=119115]  addHostMount()                Not mounting host file systems per configuration
    VERBOSE [U=1008,P=119115]  addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
    VERBOSE [U=1008,P=119115]  addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
    DEBUG   [U=1008,P=119115]  addHomeStagingDir()           Staging home directory (/home/ypu/) at /usr/local/var/singularity/mnt/session/home/ypu
    DEBUG   [U=1008,P=119115]  addHomeMount()                Adding home directory mount [/usr/local/var/singularity/mnt/session/home/ypu:/home/ypu/] to list using layer: overlay
    DEBUG   [U=1008,P=119115]  isLayerEnabled()              Using Layer system: overlay
    DEBUG   [U=1008,P=119115]  addTmpMount()                 Checking for 'mount tmp' in configuration file
    VERBOSE [U=1008,P=119115]  addTmpMount()                 Default mount: /tmp:/tmp
    VERBOSE [U=1008,P=119115]  addTmpMount()                 Default mount: /var/tmp:/var/tmp
    DEBUG   [U=1008,P=119115]  addScratchMount()             Not mounting scratch directory: Not requested
    VERBOSE [U=1008,P=119115]  addCwdMount()                 Default mount: /home/ypu/2-Soft/1-Source/singularity: to the container
    DEBUG   [U=1008,P=119115]  addLibsMount()                Checking for 'user bind control' in configuration file
    DEBUG   [U=1008,P=119115]  addResolvConfMount()          Adding /etc/resolv.conf to mount list
    VERBOSE [U=1008,P=119115]  addResolvConfMount()          Default mount: /etc/resolv.conf:/etc/resolv.conf
    DEBUG   [U=1008,P=119115]  addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
    DEBUG   [U=1008,P=119115]  create()                      Mount all
    DEBUG   [U=1008,P=119115]  mountGeneric()                Mounting tmpfs to /usr/local/var/singularity/mnt/session
    DEBUG   [U=1008,P=119115]  mountImage()                  Mounting loop device /dev/loop0 to /usr/local/var/singularity/mnt/session/rootfs
    DEBUG   [U=1008,P=119115]  mountGeneric()                Mounting overlay to /usr/local/var/singularity/mnt/session/final
    DEBUG   [U=1008,P=119115]  CleanupContainer()            Cleanup container
    FATAL   [U=1008,P=119115]  Master()                      container creation failed: mount overlay->/usr/local/var/singularity/mnt/session/final error: can't mount overlay filesystem to /usr/local/var/singularity/mnt/session/final: invalid argument

**Comment by cclerget** [comment]
@pyc1216 Can you try with option `singularity shell --writable-tmpfs lolcow_latest.sif` to check if this is bugged version of overlay in kernel

**Comment by pyc1216** [comment]
@cclerget I have tried this run with this option, error is the same. 

   /usr/local/var/singularity/mnt/session/tmpfs
    DEBUG   [U=1008,P=124614]  mountGeneric()                Mounting overlay to /usr/local/var/singularity/mnt/session/final
    DEBUG   [U=1008,P=124614]  CleanupContainer()            Cleanup container
    FATAL   [U=1008,P=124614]  Master()                      container creation failed: mount overlay->/usr/local/var/singularity/mnt/session/final error: can't mount overlay filesystem to /usr/local/var/singularity/mnt/session/final: invalid argument

but `dmesg` is different, here shows below(I run cmd with`--writable-tmpfs` 3 times) :
    [4590487.023474] overlayfs: missing upperdir or lowerdir or workdir
    [4590487.089507] overlayfs: missing upperdir or lowerdir or workdir
    [4593094.927254] overlayfs: missing upperdir or lowerdir or workdir
    [4593095.040437] overlayfs: missing upperdir or lowerdir or workdir
    [4607011.114241] overlayfs: missing upperdir or lowerdir or workdir
    [4607011.174876] overlayfs: failed to resolve '/usr/local/var/singularity/mnt/session/overlay-lowerdir:/usr/local/var/singularity/mnt/session/rootfs': -2
    [4607062.880801] overlayfs: missing upperdir or lowerdir or workdir
    [4607062.943621] overlayfs: failed to resolve '/usr/local/var/singularity/mnt/session/overlay-lowerdir:/usr/local/var/singularity/mnt/session/rootfs': -2
    [4607118.668521] overlayfs: missing upperdir or lowerdir or workdir
    [4607118.734506] overlayfs: failed to resolve '/usr/local/var/singularity/mnt/session/overlay-lowerdir:/usr/local/var/singularity/mnt/session/rootfs': -2

**Comment by cclerget** [comment]
@pyc1216 Ok I really think this is a kernel issue, early overlay implementations are known to have bugs and you use a rather old kernel. I would recommend to update or install a newer kernel if your distribution has another, or update mint distribution

**Comment by cclerget** [comment]
Or if you can't and as a workaround you can set `enable overlay = no` in `/usr/local/etc/singularity/singularity.conf`

**Comment by pyc1216** [comment]
> Or if you can't and as a workaround you can set `enable overlay = no` in `/usr/local/etc/singularity/singularity.conf`

I think you are right! My server's kernel is really old.
It works after setting `enable overlay = no`.  
Thank you very much! ^_^

**Comment by cclerget** [comment]
Cool :), I'm closing issue, feel free to re-open it if needed
