### ISSUE TITLE
Add option to create a debugging bundle to assist in issue resolution

### ISSUE THREAD

**Issue by phpHavok** [apptainer/singularity#3744]
I think it would be useful if we added an option to the main `singularity` command, which when paired with `-d`, generates a bundle (tar.gz for example) containing at least the following information:

- The output of `uname -a`
- The output of `zcat /proc/config.gz` if the file exists with perhaps a fallback to look under `/boot` for the current kernel config.
- The output of `sysctl -a`
- The output of `singularity version`
- The output of `which singularity`
- The output of `pwd`
- The full recursive listing of the singularity installation root with permissions and ownership displayed.
- The output of `mount`
- The output of `df`

We could ask that this bundle be generated and submitted on relevant issue tickets to assist in developers debugging the issues.

**Comment by jscook2345** [comment]
@ArangoGutierrez and myself have thought about having a command included in each singularity container that could be run to dump valuable information for testing and debugging. 

I think that this list could be a good start to that, but I think the tool might be better as a container inspector rather than something called from inside the container. That way, you could use tools like Facter or ansible, etc maybe?

What do you think?

**Comment by phpHavok** [comment]
That sounds pretty cool @jscook2345 . Do you envision an entirely separate tool or a built-in sub-command to `singularity`?

**Comment by jscook2345** [comment]
I think the `singularity` command is already busy enough as it is ;) There are tools that already exist out there that we could either leverage or model off of.

* Chef has something they use called `ohai`: https://docs.chef.io/ohai.html (maybe others?)
* Puppet has a tool called `facter`: https://puppet.com/docs/facter/3.11/index.html (maybe others?)

I'm not sure what the `ansible` profiling library is, but I would guess there is one.

I'm sure we could build a tool based off these tools or perhaps use these tools ourselves.

**Comment by dtrudg** [comment]
I'm going to close this. In theory it's nice, but it hasn't developed further as an idea - and we would need to spend a fair bit of effort to balance collecting enough that helps us solve weird, complex issues with privacy / disclosure worries. Having watched the flow of issues we get caught up in complex places where automated collection of enough info could easily bring in things people don't want to share.
