### ISSUE TITLE
can't mount image /proc/self/fd/8: failed to find loop device

### ISSUE THREAD

**Issue by bbarker** [apptainer/singularity#3750]
## Version of Singularity:
```
$ singularity --version
singularity version 3.0.
```
Write here.

### Expected behavior

Singularity to start container with a shell

### Actual behavior
```
$ singularity shell -u -C library://sylabsed/examples/lolcow
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   container creation failed: mount error: can't mount image /proc/self/fd/8: failed to find loop device: could not attach image file too loop device: permission denied
```

### Steps to reproduce behavior

As shown, though I'll not that on my system, singularity is not installed as root. Which is why I need `-u`. 

I'm running Linux kernel 4.19.50; I saw #2540 but wasn't sure how that applied.

**Comment by bbarker** [comment]
With singularity 3.0.1 installed via nixpkgs, current status is:

https://github.com/sylabs/singularity/issues/3750

**Comment by jscook2345** [comment]
@bbarker 

re: #2540 - Are you running under a VM? If not, can you give me details about your OS release version? Maybe I can recreate the problem.

**Comment by bbarker** [comment]
@jscook2345 apparently I wasn't thinking clearly, I am running under KVM (via OpenStack), and I had just rebooted the system (but only through the VM). Maybe I should try a hard reboot of some sort?

**Comment by jmstover** [comment]
User namespace doesn't allow a image to be mounted on the loop device. You still need SUID components to do that (or change permissions on /dev/loop* device, or be in the `disk` group [usually that group]).

If you're using the `-u` option, you can run with a `sandbox` image.

So, you should be able to do:
```
singularity build --sandbox lolcow library://sylabsed/examples/lolcow
singularity run -u -C lolcow/
singularity shell -u -C lolcow/
```

**Comment by bbarker** [comment]
Thanks @jmstover , will definitely look into trying that at some point. Sandboxing might be useful for some other applications I have in mind.

I was unable to get `-u` to work on my installation, but looking into that elsewhere for now. I was able to get images running without `-u` (https://github.com/NixOS/nixpkgs/issues/49683), so will close this issue, but comment back if I learn more.
