### ISSUE TITLE
[3.3.0] Document pre-reqs for --fakeroot flag

### ISSUE THREAD

**Issue by justwheel** [apptainer/singularity#3752]
## Version of Singularity:

v3.3.0-rc.1

### Expected behavior

Documentation should explain how to set up a system to build SIF images as a non-root user.

### Actual behavior

Currently a user needs to figure this out for themselves or check if their kernel supports this. Based on discussion in the `#general` Slack channel from today, this differs across Deb/RPM distros (e.g. some kernels ship custom patches for certain compile-time/run-time flags).

### Steps to reproduce behavior

On RHEL 7.5, I needed to do the following:

1. Whitelist my user in `/etc/singularity/singularity.conf`
2. `sudo sysctl -w user.max_user_namespaces=10000` or another integer
3. ~~(probably) Alter `/etc/sub{g,u}id` files as instructed in [this article](https://opensource.com/article/19/2/how-does-rootless-podman-work) for another rootless container implementation~~ ([see below](https://github.com/sylabs/singularity/issues/3752#issuecomment-503728264))

**Comment by jscook2345** [comment]
@cclerget 

Could you describe what is required for the `fakeroot` feature so we can integrate it into the documentation? Thanks!

**Comment by DrDaveD** [comment]
@jwflory You don't need /etc/sub[gu]id for this; whitelisting the user in singularity.conf takes the place of that.

**Comment by justwheel** [comment]
@DrDaveD Thanks for clarifying!

**Comment by rherban** [comment]
Documentation is pending for this, commenting here to make sure they get linked appropriately

sylabs/singularity-userdocs#200

https://github.com/sylabs/singularity-userdocs/blob/51227e712c6233b8e897b96ce369ac85f3951726/fakeroot.rst

**Comment by sushma-4** [comment]
Was fixed with this PR https://github.com/sylabs/singularity-userdocs/pull/200

**Comment by justwheel** [comment]
Thanks for following up! :+1:
