### ISSUE TITLE
Fix .spec file for RPM

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#3756]
During work on RHEL there where some issues with RPM build. We should double check it on RHEL and fix or close this issue.

```
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install golang libseccomp-devel
yum -y install libuuid-devel openssl-devel
yum install rpm-build
tar zxf singularity-3.2.1.tar.gz
cd singularity/
mkdir -p ~/rpmbuild/SOURCES
cp ../singularity-3.2.1.tar.gz ~/rpmbuild/SOURCES/
yum install http://mirror.centos.org/centos/7/os/x86_64/Packages/libseccomp-devel-2.3.1-3.el7.x86_64.rpm
rpmbuild -ba singularity.spec
yum install ~/rpmbuild/RPMS/x86_64/singularity-3.2.1-1.el7.x86_64.rpm
```

Version of Singularity: 3.2.1

**Comment by justwheel** [comment]
@sashayakovtseva Have you tried using the RPM built by @DrDaveD in EPEL or do you need to compile from source?

https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/s/singularity-3.2.1-1.el7.x86_64.rpm

If you already have `epel-release` installed, try `yum install -y singularity`.

**Comment by DrDaveD** [comment]
And what is meant by "some issues"?  The description doesn't show any errors.

**Comment by sashayakovtseva** [comment]
Nevermind, I had a misunderstanding with a RHEL user.
