### ISSUE TITLE
Add whitelist/blacklist option for registries for `singularity build`

### ISSUE THREAD

**Issue by justwheel** [apptainer/singularity#3762]
## Version of Singularity:

v3.3.0-rc.1

### Expected behavior

```bash
$ singularity build some-image.sif docker://project/some-image
ERROR: This registry is disabled. Contact your administrator for more information.

$ singularity build some-image.sif docker://myregistry.io/project/some-image
INFO:    Starting build...
```

### Actual behavior

```bash
$ singularity build some-image.sif docker://project/some-image
INFO:    Starting build...

$ singularity build some-image.sif docker://myregistry.io/project/some-image
INFO:    Starting build...
```

### Steps to reproduce behavior

This isn't reproducible, this is a feature request.

One useful feature is allowing an administrator to whitelist or blacklist remote sources for building images. For example, I may already run a private container registry. For security purposes, I want to limit users to a specific registry or vetted container registries. This gives my users the freedom to use a collection of software approved by me or a third-party without requiring me to closely monitoring what my users are running.

The downside of not having this feature is if users cannot be trusted with containers they pull, an admin user must build images for users and put them in a `bind path` configured in `singularity.conf`.

Does this use case make sense?

**Comment by rherban** [comment]
We have the ability to solve this, but in a slightly different manner than you suggested.  Admins can block execution of containers unless they match a particular key whitelist.  More info can be found here:
https://sylabs.io/guides/3.1/admin-guide/configfiles.html#ecl-toml


Are there still reasons you'd like to block _building_ versus _executing_?

**Comment by justwheel** [comment]
@rherban Interesting. Thanks for the link. This would probably meet our use case. However, it would be nice to use a DNS hostname for a whitelist in case the keys change. I see it as more straightforward to configure this way.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jwflory Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Execution Control List already supported solves the user requirement so closing this stale issue.
