### ISSUE TITLE
sporadic issue with running singularity: loop device: Failed to set loop flags on loop device: resource temporarily unavailable

### ISSUE THREAD

**Issue by bbarker** [apptainer/singularity#3764]
## Version of Singularity:

3.0.1

### Expected behavior

Being able to run singularity without occasionally getting failures. A "timeout" option to singularity might be useful, but perhaps there are some other parameters, like kernel flags or options, that could be tweaked.

### Actual behavior

```
$ singularity exec --containall   -H /tmp/.xsede-job-runner/589b9ed8-c31c-4b41-ae6f-4a7cd32dc9ff /home/ccrs/SING_IMAGES/vsoch-pokemon-master-latest.simg pwd
/tmp/.xsede-job-runner/589b9ed8-c31c-4b41-ae6f-4a7cd32dc9ff

$ singularity exec --containall   -H /tmp/.xsede-job-runner/589b9ed8-c31c-4b41-ae6f-4a7cd32dc9ff /home/ccrs/SING_IMAGES/vsoch-pokemon-master-latest.simg pwd
/tmp/.xsede-job-runner/589b9ed8-c31c-4b41-ae6f-4a7cd32dc9ff

$ singularity exec --containall   -H /tmp/.xsede-job-runner/589b9ed8-c31c-4b41-ae6f-4a7cd32dc9ff /home/ccrs/SING_IMAGES/vsoch-pokemon-master-latest.simg pwd
FATAL:   container creation failed: mount error: can't mount image /proc/self/fd/8: failed to find loop device: Failed to set loop flags on loop device: resource temporarily unavailable
```

### Steps to reproduce behavior

I don't recall seeing this issue in 2.6 but it was very clearly present in 3.0.1, which I just switched to. I also recently updated my kernel and many other system packages, so it isn't definitely the case that it is singularity 2.6 -> 3.0.1 that caused the issue.

**Comment by cclerget** [comment]
Hi @bbarker , running Singularity version < 3.2 is not recommended, 3.0.X have many bugs, 3.1.X versions contains a severe security issue (https://github.com/sylabs/singularity/releases/tag/v3.2.0). I would suggest to install at least 3.2 version, ideally 3.2.1 for now, you can also give a try to 3.3.0-rc1

**Comment by cclerget** [comment]
Closing, feel free to reopen it if needed
