### ISSUE TITLE
Setting locale in container

### ISSUE THREAD

**Issue by AdaZheng98** [apptainer/singularity#3765]
## Version of Singularity:

2.6.0-dist

### Expected behavior
There shouldn't be "no such file or directory" errors setting LC_CTYPE, LC_MESSAGES and LC_ALL.

### Actual behavior

![Selection_121](https://user-images.githubusercontent.com/23128905/59811092-52200e80-92d6-11e9-865b-6d0defd0b19a.png)

### Steps to reproduce behavior

I use "singularity pull docker://yzheng11/idenbench:latest" to pull the image, and use "singularity shell idebench-latest.simg" to run it. I want to use monetdb in the container, so I do: 
"monetdbd create db2"
"monetdbd start db2"
"monetdb create crossfilter"
"monetdb release crossfilter"
^^^ Works fine
"mclient -u monetdb -d crossfilter"
^^^ Gives me the error "error: could not set locale". 
I googled a bit and saw this post: https://www.monetdb.org/bugzilla/show_bug.cgi?id=3501, so I need to get rid of the locale problem. 
Strangely, when I run this image with "docker run -it", monetdb works fine. 

The dockerfile I used to create the image, if it helps:
#Download Ubuntu image
FROM ubuntu:18.04

WORKDIR /app
COPY . /app

#set environment locale
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8     
     

RUN apt-get update
RUN apt-get install -y python3 python3-pip
#install python packages 
RUN pip3 install pandas numpy scipy pymonetdb pandasql
 
#install monetdb
RUN groupadd -r monetdb && \
    useradd -r -g monetdb monetdb
RUN echo "deb http://archive.ubuntu.com/ubuntu bionic main universe" > /etc/apt/sources.list && \
    apt-get update && \
    apt-get upgrade -y && \
    echo "deb http://dev.monetdb.org/downloads/deb/ bionic monetdb" >> /etc/apt/sources.list.d/monetdb.list && \
    echo "deb-src http://dev.monetdb.org/downloads/deb/ bionic monetdb" >> /etc/apt/sources.list.d/monetdb.list && \
    apt-get install wget -y && \
    wget --output-document=- http://dev.monetdb.org/downloads/MonetDB-GPG-KEY | apt-key add - && \
    apt-get update -y && \
    apt-get install -y monetdb5-sql monetdb-client

**Comment by jscook2345** [comment]
@AdaZheng98 

Have you tried this with 3.2.X? I don't have the locale errors you listed, but I am getting an error trying to run one of the commands.

```
Singularity idenbench_latest.sif:/tmp> monetdb create db2
monetdb: cannot find a control socket, use -h and/or -p
```

**Comment by jmstover** [comment]
@AdaZheng98 
Can I see the output of `env | egrep 'LC|LANG'`?  It should be similar to:

```
Singularity idenbench_latest.sif:~/> env | grep 'LC'
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
LC_COLLATE=C
```

**Comment by AdaZheng98** [comment]
@jmstover 
This is the output of env | egrep 'LC|LANG':
Singularity idebench-latest.simg:~> env | egrep 'LC|LANG'
LC_MEASUREMENT=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LANG=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_TIME=en_US.UTF-8

@jscook2345 
I'm afraid I can't upgrade singularity. I'm using singularity on the server and the version is fixed.

**Comment by AdaZheng98** [comment]
@jscook2345 
I've tried this with singularity version 3.2.1-1.el7, but there's still the same locale error.

**Comment by rherban** [comment]
@AdaZheng98 I too am unable to reproduce the error on my test system, but I did come across this page which might be useful:
https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue

In short, it looks like you're trying to use en_us.utf-8 but that's not listed in `locale -a` as a viable option.

**Comment by dtrudg** [comment]
In order to use a locale in the container it must be present. As hinted in the link above, you need to generate locales. To support all possible locales you can do:

```
cp /usr/share/i18n/SUPPORTED /etc/locale.gen
locale-gen
```

... when building a Singularity or Docker container.

In Debian based distros you could also install the `locales-all` package, which provides pre-compiled locales.

If you only need to support specific locales, then you can `locale-gen` them individually.
