### ISSUE TITLE
Instance networking firewall issues

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#3766]
## Version of Singularity:

3.2.1

This is a known issue that @cclerget is working on, and I wanted to document the commands to reproduce it here since Slack messages get lost in some deep bucket of "If you paid us for the service you would see it..."

Specifically, it seems to be the case that on linux machines with Docker installed, (we are hypothesizing) that Docker has done manipulation of the iptables so that a firewall rule prevents different container instances on the same bridge from seeing one another. A simple example to reproduce was provided by @cclerget :+1: 

```bash
sudo singularity instance start --net --network-args="IP=10.22.10.10" docker://alpine A
sudo singularity instance start --net --network-args="IP=10.22.10.11" docker://alpine B
sudo singularity exec instance://A ping 10.22.10.11
sudo singularity exec instance://B ping 10.22.10.10
```

### Expected behavior
The expected behavior for one container to ping another should be a stream of responses (packets sent and then received).

### Actual behavior

However, the actual behavior is that we hang - the message is sent without receipt. 

```bash
sudo singularity exec instance://A ping 10.22.10.11
PING 10.22.10.11 (10.22.10.11): 56 data bytes
```

Note that this is also the case when we stop all docker services,

```bash
$ sudo service docker stop
```
I was also able to generate the same application I was originally testing, but [dumped into one container](https://github.com/singularityhub/singularity-compose-simple) and it functioned as expected.

@cclerget please let me know if/when you would like a tester! My computer is fully infiltrated by the Docker bugs and ready :)

**Comment by cclerget** [comment]
@vsoch I will look today and hopefully submit PR so you could test

**Comment by cclerget** [comment]
@vsoch Ready for testing https://github.com/sylabs/singularity/pull/3771 :)

Be sure to recompile everything with :

```
./mconfig
make -C builddir
sudo make -C builddir
```

**Comment by vsoch** [comment]
On it!

**Comment by rherban** [comment]
Hey @vsoch, just curious if you had time to test this out.

**Comment by vsoch** [comment]
Oh sorry didn't update, I tested it the same day that it was created, I put my notes [here](https://github.com/sylabs/singularity/pull/3771#issuecomment-504414459) in the linked PR. Thanks again @cclerget and thanks @rherban for checking in!

**Comment by rherban** [comment]
Super!  Guess I should have checked the other issue closer.  They're already linked, so this will auto-close.

**Comment by vsoch** [comment]
I love it when that happens <3
