### ISSUE TITLE
make does not necessarily catch all modifications

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3774]
## Version of Singularity:

c5011b8ec498a4abbe2ffd0650ac173f39284936

### Expected behavior

When modifying a Go file and running `make`, the modifications should be detected and the appropriate files recompiled.

### Actual behavior

After modifying a Go file, running `make -C builddir` or `make testall -C builddir` does not seem to pick up the changes. This is especially a problem when testing in the context of developments, since it means that a developer should run `./mconfig && make -C builddir && make testall -C builddir` to make sure the modifications are actually picked up.

### Steps to reproduce behavior

Edit a file by adding a `fmt.Println()` statement, e.g., in `internal/pkg/client/cache/library.go` and then run `make -C builddir`, i get the following output:
```
$ make -C builddir/
make: Entering directory '/home/gvallee/go/src/github.com/sylabs/singularity/builddir'
build flag -mod=vendor only valid when using modules
build flag -mod=vendor only valid when using modules
make: Leaving directory '/home/gvallee/go/src/github.com/sylabs/singularity/builddir'
```
which suggests that the code is not recompiled.

**Comment by dtrudg** [comment]
Edits are now being picked up okay. I can...

> Edit a file by adding a fmt.Println() statement, e.g., in internal/pkg/client/cache/library.go and then run make

and compilation happens again

```
dtrudg@dt-sylabs~/S/G/s/builddir> make
 GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog imgbuild_engine oci_engine singularity_engine fakeroot_engine"
```
