### ISSUE TITLE
cache is clocking re-downloading of images

### ISSUE THREAD

**Issue by sushma-4** [apptainer/singularity#3776]
## Version of Singularity:

3.3.0-rc1

### Expected behavior

If my previous pull was incomplete/interrupted - I should be able to pull again

### Actual behavior

INFO:    Use image from cache (Which was an incomplete download)

### Steps to reproduce behavior

```
$ singularity pull shub://michael-tn/mpi-hello-world:latest
```
While its downloading, interrupt the download
Run the pull command agian, you'll see
```
INFO:    Use image from cache
```

**Comment by jscook2345** [comment]
I think this exposes another shortcoming in that we do not verify downloads via checksums.

**Comment by jscook2345** [comment]
I'm not sure checking signatures would be enough here. I think we need to also use checksums.

**Comment by ikaneshiro** [comment]
Important to note that this is only for `shub` the other transports are using a checksum. I know there is a way to do this, and @WestleyK is working on pulling by an image hash but that still needs some work #3652. So we can improve how our caching works once that is in place

**Comment by jscook2345** [comment]
@ikaneshiro 

Just to be sure I verified that both `library` and `docker` worked. ;)

* When you interrupt a docker layer download, it re-downloads it when you re-pull.
* When you interrupt a library download, it fails saying the cached file sum and the expected sum do not match when you re-pull.

**Comment by ikaneshiro** [comment]
@jscook2345 this will also occur for `oras` aswell, since the sif `sha:256` is stored in the image manifest we do the same thing as we do for library, get the manifest, check the chechsum, then download depending on the outcome of that. 

I also just looked at the issue for shub mentioned above and I think i understand how we can start making forward progress on that :+1:
