### ISSUE TITLE
can sif images be pushed to harbor registry using oras URI

### ISSUE THREAD

**Issue by asmi10** [apptainer/singularity#3778]
## Version of Singularity:

3.3.0-rc.1

I am testing rc: 3.3.0, and trying to push sif images to harbor registry after setting up SINGULARITY_DOCKER_USERNAME & SINGULARITY_DOCKER_PASSWORD. But I get below error. Not sure if I missing something.

singularity push sles11sp4.sif oras://ger-registry.caas.intel.com/hpc/sif:sles11sp4
WARN[0009] encountered unknown type application/vnd.sylabs.sif.config.v1+json; children may not be fetched
WARN[0009] reference for unknown type: application/vnd.sylabs.sif.config.v1+json  digest="sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" mediatype=application/vnd.sylabs.sif.config.v1+json size=0
WARN[0009] encountered unknown type appliciation/vnd.sylabs.sif.layer.tar; children may not be fetched
WARN[0009] reference for unknown type: appliciation/vnd.sylabs.sif.layer.tar  digest="sha256:11a7ccba1139815abd499ffe92c5506935467bd91c5824b21c6aa97d9d72a416" mediatype=appliciation/vnd.sylabs.sif.layer.tar size=1204404224
FATAL:   Unable to push image to oci registry: unable to push: failed commit on ref "manifest-sha256:09e85ce640a714bc9e0de509fea389c518bea264df7b8bae3e43db2710ee1707": unexpected status: 400 Bad Request

Similar error I got via uploading via oras

oras push ger-registry.caas.intel.com/hpc/sif:sles11sp4 sles11sp4.sif:application/vnd.me.sles11sp4
Uploading 11a7ccba1139 sles11sp4.sif
Error: failed commit on ref "manifest-sha256:afe0cd239c4140f5c311df41e729a4b0e64e85d62fd41107b246a292aa194d76": unexpected status: 400 Bad Request

**Comment by jscook2345** [comment]
Each registry that wishes to support singularity and ORAS needs to accept our mime-type. It appears here this registry does not do that. You may need to contact Intel to ask them about supporting it.

@ikaneshiro 

Please correct me if I am wrong here.

**Comment by asmi10** [comment]
yes, I checked. the version of harbor we are using doesn't support singularity image artifact. I see there is plan to include it in harbor/1.9.0.
let's see, Thanks!
