### ISSUE TITLE
Problem with inspect command with singularity `--without-suid` installation

### ISSUE THREAD

**Issue by alazzaro** [apptainer/singularity#3779]
## Version of Singularity:

v3.2.1
v3.3.0-rc.1

### Expected behavior

I do run the command
```
singularity inspect test.sif 
```

### Actual behavior
I got the message:

```
FATAL:   Unable to prossess command: fork/exec /home/alazzaro/Work/containers/singularity/singularity_install_v3.3.0-rc.1/libexec/singularity/bin/starter-suid: no such file or directory: 
```

### Steps to reproduce behavior

- Install on Ubuntu 19.04
- Install singularity rootless: `./mconfig --without-suid --prefix=${SINGULARITY} -c "gcc" -x "g++"`

**Comment by jscook2345** [comment]
I reproduced this on `centos7`:

```
$ singularity inspect busybox_latest.sif
FATAL:   Unable to prossess command: fork/exec /usr/local/singularity/libexec/singularity/bin/starter-suid: no such file or directory:

$ singularity -d inspect busybox_latest.sif
DEBUG   [U=1000,P=31713]   createConfDir()               /home/vagrant/.singularity already exits. Not creating.
DEBUG   [U=1000,P=31713]   func14()                      Inspection of labels selected.
FATAL   [U=1000,P=31713]   getFileContent()              Unable to prossess command: fork/exec /usr/local/singularity/libexec/singularity/bin/starter-suid: no such file or directory:
```

**Comment by GodloveD** [comment]
I'm going to assume this is because the SIF file needs to be mounted to inspect the the file system within and display things for the `inspect` command.  And we can't do that with an un-prived installation.  That is why `allow setuid = no` mode only works with sandboxes.  

I think this is expected behavior tbh.  Going to close, but feel free to ask for it to be re-opened if you disagree.

**Comment by GodloveD** [comment]
Actually, I'm going to reopen this because I think we should be able to convert to a sandbox under the covers.

**Comment by jscook2345** [comment]
Regardless of if it is expected behavior, the error message should reflect what the issue is a little better I think.

**Comment by alazzaro** [comment]
Just to clarify (sorry, I didn't mention in my first post), I use sandbox images (because of suid), so the problem is relevant.
