### ISSUE TITLE
failed to run mpi application inside a container on macOS

### ISSUE THREAD

**Issue by waynezw0618** [apptainer/singularity#3781]
## Version of Singularity:

MacOS alpha
### Expected behavior
no error message

### Actual behavior
I am trying to install singularity directly on my MacBook, since there is an alpha version. 
there are following errors for running an application.
python single_runner.py
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
[(none):01109] opal_ifinit: unable to find network interfaces.
[(none):01109] mca: base: components_open: component if / posix_ipv4 open function failed
[(none):01109] oob_tcp: problems getting address for index 65861792 (kernel index -1)

No network interfaces were found for out-of-band communications. We require
at least one available network for out-of-band messaging.

It looks like orte_init failed for some reason; your parallel process is
likely to abort. There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems. This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

orte_oob_base_select failed
--> Returned value (null) (-43) instead of ORTE_SUCCESS

It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort. There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems. This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

ompi_mpi_init: ompi_rte_init failed
--> Returned "(null)" (-43) instead of "Success" (0)

*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
*** and potentially your MPI job)
[(none):1109] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!

### Steps to reproduce behavior

Write here.

**Comment by waynezw0618** [comment]
It seems related to mpi.
 angularity fenics-and-more.img:~/software/vm/singularity-vm/tests> mpirun -np 2 
[(none):01159] opal_ifinit: unable to find network interfaces.
[(none):01159] mca: base: components_open: component if / posix_ipv4 open function failed
[(none):01159] oob_tcp: problems getting address for index 0 (kernel index -1)
--------------------------------------------------------------------------
No network interfaces were found for out-of-band communications. We require
at least one available network for out-of-band messaging.
--------------------------------------------------------------------------
Singularity fenics-and-more.img:~/software/vm/singularity-vm/tests>

**Comment by rherban** [comment]
We're still working out some kinks with the network stack on Macos and I know @jmstover was working on this recently.  

Thanks for the report and I'll keep this open until we get a better answer to you.

**Comment by waynezw0618** [comment]
Hi rherban
looking forward your solution

**Comment by rherban** [comment]
@waynezw0618 Thanks for your patience and support for Singularity Desktop.  The just-released beta now supports networking.  

You can find more information here: https://medium.com/sylabs/announcing-the-first-beta-release-of-singularity-desktop-for-macos-f427c006aae6

**Comment by rherban** [comment]
I'm going to go ahead and close this issue for now, but please re-open if you still see any issues with networking or open a new issue if you encounter any other problems with the new build.

Thanks again
