### ISSUE TITLE
All images are being converted to sandboxes during shell command

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3787]
## Version of Singularity:

`master` on `centos7`

### Expected behavior

```
$ singularity pull docker://busybox:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build: ...
INFO:    Creating SIF file...
INFO:    Build complete: ...

$ singularity shell busybox_latest.sif
Singularity>
```

### Actual behavior

```
$ singularity pull docker://busybox:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build: ...
INFO:    Creating SIF file...
INFO:    Build complete: ...

$ singularity shell busybox_latest.sif
INFO:    Convert SIF file to sandbox...
Singularity>
```

Note the `Convert SIF file to sandbox...`. I'm not sure why that is occurring. 

### Steps to reproduce behavior

```
$ singularity pull docker://busybox:latest
$ singularity shell busybox_latest.sif
```

@cclerget 

The messages were added back in 3.1.1, but I'm just noticing them now. It appears to be linked to the user namespace features. Is this intended as a part of that new work, because I'm not using the user namespace feature that I know of.

**Comment by GodloveD** [comment]
Do you have suid bit set on the `singularity` binary?  If not, I'm guessing Singularity is falling back to the no suid workflow which necessitates a sandbox.  Pretty nice that the conversion happens automatically for you.

**Comment by jscook2345** [comment]
@GodloveD Yeah must of been leftovers from the bug I was looking at before for `suid`. Closing
