### ISSUE TITLE
Singularity not yelling failure when "mount dev" is undefined in config file

### ISSUE THREAD

**Issue by Nekel-Seyew** [apptainer/singularity#379]
inside of /etc/singularity, there's both singularity.conf and singularity.conf.rpmnew, after installing as an RPM.

**Comment by gmkurtzer** [comment]
Oh, that is normal and proper behavior. The bug I was referring to has to do with Singularity bombing out quietly because `mount dev` is undefined in the config file. It should in fact YELL about it or assume a reasonable default if it is not present.

**Comment by gmkurtzer** [comment]
Closing old issue and it is not a bug with Singularity (rather a nuance of RPM).
