### ISSUE TITLE
capabilities - warning message printed even if group capability is configured

### ISSUE THREAD

**Issue by apnorrie** [apptainer/singularity#3790]
## Version of Singularity:

3.2.0 and later

### Expected behavior

No Warning message as the Capability exists via the group. 

### Actual behavior

root@ibmblade05:~# /opt/singularity-3.2.0/bin/singularity capability add --group users net_raw

root@ibmblade05:~# cat /opt/singularity-3.2.0/etc/singularity/capability.json 
{
	"groups": {
		"users": [
			"CAP_NET_RAW"
		]
	}
}

root@ibmblade05:~# su - anorrie
ibmblade05:/data/home/anorrie> /opt/singularity-3.2.0/bin/singularity run -B /cgv --add-caps net_raw /tmp/g2_singularity_test.db7
**WARNING: not authorized to add capability: CAP_NET_RAW**
anorrie@ibmblade05:~$ ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_req=1 ttl=64 time=0.036 ms
64 bytes from localhost (127.0.0.1): icmp_req=2 ttl=64 time=0.029 ms
^C
--- localhost ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.029/0.032/0.036/0.006 ms

### Steps to reproduce behavior

Configure group capability as root/sudo:
singularity capability add --group users net_raw

Run singularity as regular user (but in group with cap) and add capability:
singularity run --add-caps net_raw ...

Warning is output, but the capability still works as it was add in the Group Capability:
WARNING: not authorized to add capability: CAP_NET_RAW

The problem file is singularity/internal/pkg/runtime/engines/singularity/prepare_linux.go
which prints the warning right after checking the User Capability but before checking the Group Capability

authorizedCaps, unauthorizedCaps := capConfig.CheckUserCaps(pw.Name, caps)
        if len(unauthorizedCaps) > 0 {
                sylog.Warningf("not authorized to add capability: %s", strings.Join(unauthorizedCaps, ","))
        }
        if len(authorizedCaps) > 0 {
                sylog.Debugf("User capabilities %s added", strings.Join(authorizedCaps, ","))
                commonCaps = authorizedCaps
        }

        groups, err := os.Getgroups()
        if err != nil {
                return err
        }

        for _, g := range groups {
                gr, err := user.GetGrGID(uint32(g))
                if err != nil {
                        sylog.Debugf("Ignoring group %d: %s", g, err)
                        continue
                }
                authorizedCaps, _ := capConfig.CheckGroupCaps(gr.Name, caps)
                if len(authorizedCaps) > 0 {
                        sylog.Debugf("%s group capabilities %s added", gr.Name, strings.Join(authorizedCaps, ","))
                        commonCaps = append(commonCaps, authorizedCaps...)
                }
        }

**Comment by jscook2345** [comment]
I reproduced this issues on centos7. Thanks for the report @apnorrie !
