### ISSUE TITLE
Cannot run yum in Centos container

### ISSUE THREAD

**Issue by shwina** [apptainer/singularity#38]
I get the following error:

Could not create lock at /var/run/yum.pid: [Errno 30] Read-only file system: '/var/run/yum.pid'

**Comment by gmkurtzer** [comment]
I may need more information to help you but making several assumptions
(e.g. you are within a RedHat compatible Singularity image, as root) you
may only need to supply the --writable flag to your shell or exec
Singularity command:

$ singularity shell --writable container.img

**Comment by shwina** [comment]
Thanks, that was it! My apologies for overlooking the docs.

**Comment by gmkurtzer** [comment]
No apologies necessary... You didn't ignore the docs, they just haven't
been written yet! lol
