### ISSUE TITLE
Run jupyter with [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by zhcf** [apptainer/singularity#3802]
## Version of Singularity:
singularity version 3.0.1-1.el7

I run jupyter with the singularity image with root, it has the following error, but it works if I runing as a non-root user.
Singularity jupyter.simg:/home/zcf> source activate /home/zcf/test
(/home/zcf/test) Singularity jupyter.simg:/home/zcf> jupyter notebook --no-browser --allow-root --NotebookApp.ip='10.240.208.84' --NotebookApp.port=8888 --NotebookApp.base_url='/jupyter/' --NotebookApp.allow_origin='*'
[I 10:46:50.098 NotebookApp] Serving notebooks from local directory: /home/zcf
[I 10:46:50.098 NotebookApp] The Jupyter Notebook is running at:
[I 10:46:50.098 NotebookApp] http://10.240.208.84:8888/jupyter/?token=d7644553834ae481a78c5189d99835313621e5c8b5d2b2bd
[I 10:46:50.098 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/home/zcf/test/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/home/zcf/test/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/zcf/test/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/zcf/test/lib/python2.7/site-packages/notebook/notebookapp.py", line 1782, in start
    self.write_server_info_file()
  File "/home/zcf/test/lib/python2.7/site-packages/notebook/notebookapp.py", line 1676, in write_server_info_file
    with open(self.info_file, 'w') as f:
IOError: [Errno 30] Read-only file system: u'/run/user/0/jupyter/nbserver-90647.json'

**Comment by zhcf** [comment]
of couse if I bind some host dir to /run, it works, but I don't know why non-root user can work without binding host dir to /run.

**Comment by zhcf** [comment]
find the root cause, should unset XDG_RUNTIME_DIR before running jupyter command in the image for root user. 
[root@head zcf]# singularity shell --nv jupyter.simg 
Singularity jupyter.simg:/home/zcf> echo $XDG_RUNTIME_DIR
/run/user/0
Singularity jupyter.simg:/home/zcf>

[zcf@head ~]$ singularity shell --nv jupyter.simg 
Singularity jupyter.simg:~> echo $XDG_RUNTIME_DIR

Singularity jupyter.simg:~>

Whether this is a singularity bug of build command?

**Comment by cclerget** [comment]
Hi @zhcf , by default Singularity images are read-only, you need to be explicit with command line, if your system support overlay filesystem, you could use `singularity shell --nv --writable-tmpfs jupyter.simg` and it should work without touching `XDG_RUNTIME_DIR`

**Comment by zhcf** [comment]
Hi @cclerget,  I understand that singularity images are read-only, I also need the read only image, I just need to write on the mounted home folder. XDG_RUNTIME_DIR should be empty, then jupyter will not write any files under /run/, it will just write under the home folder.
