### ISSUE TITLE
Docker images being extracted in wrong order

### ISSUE THREAD

**Issue by rjeschmi** [apptainer/singularity#382]
I found that the state of my bootstrapped docker image is inconsistent. All of the files are there, but if the file was changed in different layers, the oldest one seemed to be available.

There are a couple of issues I suppose. First is that fsLayers seems to be stored from child to base. The only official doc I could find was:

https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md

> layers array
> 
> The layer list is ordered starting from the base image (opposite order of schema1).
> 

Which is actually the documentation for schemaversion 2 (and singularity is pulling 1), but it suggests this inversion.

It also might be worthwhile to move to the newer schema version too

**Comment by rjeschmi** [comment]
Also compare the docker pull order to the singularity digest add order:

```
[rob@ottbioinfo python]$ docker pull rjeschmi/easybuild-centos7:3.0.0
3.0.0: Pulling from rjeschmi/easybuild-centos7
08d48e6f1cff: Already exists
a62784d6bd51: Already exists
6b24dc0e5e98: Already exists
6b133709d8d5: Already exists
6ebac0c8a1bb: Already exists
223a2c0531d4: Already exists
3ffadd8cf926: Already exists
336f6e105bc2: Already exists
06e33d905fee: Already exists
2fa2ee5b62e9: Already exists
694658681c8a: Already exists
a236d32b835b: Pull complete
63f2fe429107: Pull complete
ac18bb72f0ea: Pull complete
9163f0d1336e: Pull complete
0b25ca541a8b: Pull complete
fe629c04d114: Pull complete
951040916ca3: Pull complete
f7cf2c8316ae: Pull complete
791118305412: Pull complete
8d6b7c57d3ff: Pull complete
2bccc34703d4: Pull complete
3e62cf0fa9bc: Pull complete
cd1890e69bd6: Pull complete
Digest: sha256:410328ce4ccf5bd05d63ff0ad870e5506cd7e0139883f1c9b1628be41aa765fa
Status: Downloaded newer image for rjeschmi/easybuild-centos7:3.0.0

```

```
INFO:python:Adding digest sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
INFO:python:Adding digest sha256:cd1890e69bd64ae2f7c68fcfd2c44b006fb46efa437c480f5350d335cd4ab771
INFO:python:Adding digest sha256:3e62cf0fa9bc550d2353a23d186416e5a16efbad1932bee99bb9138a480296f9
INFO:python:Adding digest sha256:2bccc34703d47763cca99cb080f262b372c305346853c4096711a4f0da58fc56
INFO:python:Adding digest sha256:8d6b7c57d3ff588a9a993583b8794596cc9e169427b25329130a6584ef3eea6e
INFO:python:Adding digest sha256:7911183054129118d6df59f99fd6681f86ae94cc8cdf23fb318f4009c3b7e489
INFO:python:Adding digest sha256:f7cf2c8316ae754707656c6eaa688e3b0c9ddbeb4b9b98b9a1c2bf1edfb3b2d4
INFO:python:Adding digest sha256:951040916ca34ecc97bbe1dce49294d8bf8828ffa6540dfa1e59ee18307fcdab
INFO:python:Adding digest sha256:fe629c04d1148cd188b4bd869c083ef36caadb6ebc7eb1f0c87c0ea5932130af
INFO:python:Adding digest sha256:0b25ca541a8b3b3128ff8df5d9bb92e2051e907d208d5c2c01b2fea7ce395593
INFO:python:Adding digest sha256:9163f0d1336e9da4e160be470f24e22f5f03a9963c5f67b5c034f5803f94fda2
INFO:python:Adding digest sha256:ac18bb72f0eacaad47a8e1a919db78b9801263266b111110ccdb53cf99e4cadb
INFO:python:Adding digest sha256:63f2fe4291079511a8c24ea2b08a593ffc3826fca0519622f92d2bd3dab517a8
INFO:python:Adding digest sha256:a236d32b835b99c29bfcf801163781f30a35f5907bdbcac0cf3ec5b056e95306
INFO:python:Adding digest sha256:694658681c8a77ad5fd501de74339d8f29a038134164feb5d3755c524510e373
INFO:python:Adding digest sha256:2fa2ee5b62e9ea7da6e434e5cf625b2bf4ad80153b3e73f06f039cb7912d03c7
INFO:python:Adding digest sha256:06e33d905fee3d6293b8fa4012ac5e93942d9b9314f8888be97f59af6ed1b923
INFO:python:Adding digest sha256:336f6e105bc20420026cade0c4cf8d98d9f4123343c5d4eaecca4a977e3133fc
INFO:python:Adding digest sha256:3ffadd8cf926664abc373d20f6a8d3a56600926e00edb671a909e6c3950b361d
INFO:python:Adding digest sha256:223a2c0531d489ad71710e0ddaf4cf66d5cbd1b4aeb7a7840b38001d48b3e203
INFO:python:Adding digest sha256:6ebac0c8a1bb8f2c1ce17b74922611f3f57ccadd9370d8f5e2329972e86cd1f8
INFO:python:Adding digest sha256:6b133709d8d5b59e1e86eaee3963a1bca1980d99d09dfa26d2542a71f5b7bdd6
INFO:python:Adding digest sha256:6b24dc0e5e9867b594d8e2718f9e3efa5ed4556a4203ce965d02c3f8466d297c
INFO:python:Adding digest sha256:a62784d6bd518295fdf6fbf39cffc7ef2a061782805d9900c4e70100f597445a
INFO:python:Adding digest sha256:08d48e6f1cff259389732d35307bb877215fa28867cdaff50c1dbd6e0b993c1f
```

**Comment by vsoch** [comment]
Interesting! I remember changing the api from v1 to [v2 here](https://github.com/singularityware/singularity/blob/master/libexec/python/docker/api.py#L37), so clearly in the case of the image manifest, in the api call v2 != schema 2.

If the Docker pull list is indeed from base to child (meaning `08d48e6f1cff` is the base) then indeed we are extracting in the opposite order, I think the issue might be this added bit that they ask for in the header:

      When pulling images, clients indicate support for this new version of the manifest format by sending the application/vnd.docker.distribution.manifest.v2+json and       

      application/vnd.docker.distribution.manifest.list.v2+json media types in an Accept header when making a request to the manifests endpoint.

So I think the first thing to try is adding those extra headers. fwiw, this looks like a [more recent change](https://github.com/docker/distribution/commit/b82a2efc336bb1c56064ace2bae5963cc4ae0aeb#diff-298c8e761320ff3dde0420467054f000) (22 days) so likely it was working according to their schema when we originally implemented it.

Huge thanks for bringing this up - extracting images in the reverse order is definitely not going to work, haha. I should be able to investigate this fully later today - this morning we have a little get together with the Berkeley folk. Stay tuned!

**Comment by rjeschmi** [comment]
I switched the order that the images were being laid out by changing the layer iteration to a .pop() over the list and it seems to work.

However, I think sending the updated media-type and getting the v2 schema might be a better solution. Maybe the api caller should be abstracted more to make that setable per api endpoint?

**Comment by vsoch** [comment]
You got it! I'll get to this later today, after the days events.

**Comment by vsoch** [comment]
@rjeschmi I started working on this - I've updated the manifest pull for images to return the right list, but now I need to read up on the (new?) version / schema to actually download the blobs (the old one doesn't seem to work with this one). I've already stayed on campus 2 hours longer than I intended working on this, so it probably needs to wait for tomorrow. Sorry :(

**Comment by vsoch** [comment]
[here is the branch](https://github.com/vsoch/singularity/tree/update/docker-registry-api) if you want to take a look, it worked when I was testing, for example, before changing the Accept header the layers were:

Here is the list of layers added when the headers are added:

```bash
INFO:python:Adding digest sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
INFO:python:Adding digest sha256:9332eaf1a55b72fb779d2f249b65855c623c8ce7be83c822b7d80115ef5a3af3
INFO:python:Adding digest sha256:47b5e16c0811b08c1cf3198fa5ac0b920946ac538a0a0030627d19763e2fa212
INFO:python:Adding digest sha256:e931b117db38a05b9d0bbd28ca99a0abe5236a0026d88b3db804f520e59977ec
INFO:python:Adding digest sha256:8f9757b472e7962a4304d4af61630e2cde66129218135b4093a43b9db8942c34
INFO:python:Adding digest sha256:af49a5ceb2a56a8232402f5868cdb13dfdae5d66a62955a73e647e16e9f30a63
```

and then after they were (mostly) flipped around to:
```bash
INFO:python:Adding digest sha256:af49a5ceb2a56a8232402f5868cdb13dfdae5d66a62955a73e647e16e9f30a63
INFO:python:Adding digest sha256:8f9757b472e7962a4304d4af61630e2cde66129218135b4093a43b9db8942c34
INFO:python:Adding digest sha256:e931b117db38a05b9d0bbd28ca99a0abe5236a0026d88b3db804f520e59977ec
INFO:python:Adding digest sha256:47b5e16c0811b08c1cf3198fa5ac0b920946ac538a0a0030627d19763e2fa212
INFO:python:Adding digest sha256:9332eaf1a55b72fb779d2f249b65855c623c8ce7be83c822b7d80115ef5a3af3
```

but then running with exec, which does a temporary bootstrap, it doesn't seem to do much of anything:

```bash
singularity shell docker://ubuntu
Cache folder set to /home/vanessa/.singularity/docker
ERROR: Container does not contain the valid minimum requirement of /bin/sh
ERROR  : Container does not have a valid /bin/sh
ABORT  : Retval = 255
```

It probably needs an hour or two more of debugging, I just don't have it in me.

**Comment by vsoch** [comment]
lol nevermind, I just figured it out!

**Comment by vsoch** [comment]
lol, god I'm so stubborn.
