### ISSUE TITLE
sif info not showing the name of Def file

### ISSUE THREAD

**Issue by sushma-4** [apptainer/singularity#3822]
## Version of Singularity:

3.3.0-rc1

### Expected behavior

``
singularity sif info 1 jupyter.sif (where 1 is the Descriptor ID for Def file)
``
displays no name of the def file used to build the container. IDK if that's what its supposed to output but a ``.`` does not make much sense 

Also, Singularity gives no error when Descriptor IDs not in range are used with the container file

### Actual behavior
```
Descr slot#: 0
  Datatype:  Def.FILE
  ID:        1
  Used:      true
  Groupid:   1
  Link:      NONE
  Fileoff:   32768
  Filelen:   1128
  Ctime:     2018-12-20 16:05:16 +0530 IST
  Mtime:     2018-12-20 16:05:16 +0530 IST
  UID:       0
  Gid:       0
  Name:      .
```

**Comment by ikaneshiro** [comment]
I don't see a need to store the name of the original definition file name within the sif because it will have almost no meaning between hosts and little meaning on the same host. 

@sushma-4 what do mean by your second comment about descriptor IDs? Like for a SIF with 3 partitions and you say `singularity sif info 4`?

**Comment by sushma-4** [comment]
Oh yeah! I understand what you're saying, I just couldn't figure out what the ``Name`` variable was doing there.
Also, that's what I mean in the second comment

**Comment by ikaneshiro** [comment]
Ok wrt the descriptors, it's unclear to me whether listing nothing for a nonexistent descriptor was intentional or not. Can you open an issue in the https://github.com/sylabs/sif repo? The code for `sif/siftool` is actually is external to singularity

**Comment by jscook2345** [comment]
> I don't see a need to store the name of the original definition file name within the sif because it will have almost no meaning between hosts and little meaning on the same host.

@ikaneshiro That's fine, but I don't think having a name of '.' is really all that great either. That makes me think there is a bug. Could it be anything else realisitcaly?
