### ISSUE TITLE
Net directory in Cache not caching anything

### ISSUE THREAD

**Issue by sushma-4** [apptainer/singularity#3827]
## Version of Singularity:

3.3.0-rc1

### Expected behavior

Images pulled with http are cached inside net directory in .singularity/cache or maybe not.. The pulling from ``net://`` is not really documented anywhere so dont know what its caching

### Actual behavior

Directory remains empty

**Comment by jscook2345** [comment]
I've never heard of `net://` @ikaneshiro ?

**Comment by ikaneshiro** [comment]
@jscook2345 @sushma-4  the uri for `net` is `http[s]://` this basically mimics wget to an extent and was added for convenience a while ago. #2346 this is the pr. Looks like caching isnt actually being done for pulls with this transport so we should leave this open to fix that

**Comment by dtrudg** [comment]
Caching is now being done... but in a way that causes nasty clashing issues. Opening a new issue for that.
