### ISSUE TITLE
exec command not working with source

### ISSUE THREAD

**Issue by 0luhancheng0** [apptainer/singularity#3838]
## Version of Singularity:

3.2.1

### Expected behavior

i was trying to install openFOAM by
`singularity pull docker://openfoam/openfoam6-paraview54`
`singularity exec openfoam6-paraview54_latest.sif source /opt/openfoam6/etc/bashrc`
/opt/openfoam6/etc/bashrc is expected to be sourced

### Actual behavior

`/.singularity.d/actions/exec: 9: exec: source: not found`

### Steps to reproduce behavior
`singularity pull docker://openfoam/openfoam6-paraview54`
`singularity exec openfoam6-paraview54_latest.sif source /opt/openfoam6/etc/bashrc`

### other related issue
same problem in #1758 is resolved by run another bash inside the container, but it does not solve my problem
i have tried running 
`sudo singularity exec openfoam6-paraview54_latest.sif /bin/bash 'source /opt/openfoam6/etc/bashrc'`

which generate another error

`/bin/bash: source /opt/openfoam6/etc/bashrc: No such file or directory`

that does not mean file is not there because 
`singularity exec openfoam6-paraview54_latest.sif cat /opt/openfoam6/etc/bashrc`

still working
### potential cause

running 
`sudo singularity exec openfoam6-paraview54_latest.sif head /.singularity.d/actions/exec`

shows that exec is using /bin/sh instead of /bin/bash

Is there any particular reason for singularity to using /bin/sh instead of /bin/bash ? 
And is there any possible fix for this issue? 

Thank you

**Comment by Zohman** [comment]
you can run:
$ singularity exec openfoam6-paraview54_latest.sif bash -c ' source /opt/openfoam6/etc/bashrc'

But as this is non-interactive execution of 'bash', you won't get any variable sourced next time you run 'singularity exec'.
if you do want the source to be relevant execute the next task within that command, like:

$ singularity exec openfoam6-paraview54_latest.sif bash -c 'source /opt/openfoam6/etc/bashrc && echo $WM_PROJECT_DIR'
/opt/openfoam6

**Comment by rherban** [comment]
I'm not sure I understand the use-case for just trying to source a file in an exec.  Sourcing files is typically used to setup your environment variables in preparation for running other commands.  

If you want particular environment variables to always be available within the container, you can use the %environment section of the definition file and hard-code them.

**Comment by 0luhancheng0** [comment]
Thank @Zohman for awesome reply. 

I apologize that I may not fully state my question at the top. My complete question is, how to make a list of environment variable available during both building time and runtime (and I believe @Zohman had a good solution for the second part of the question). 

And for @rherban . There are multiple decision making happening in the env setup script which makes me a bit concerned to hardcode them.

**Comment by rherban** [comment]
Given that information, using an env setup script is a fine solution, as long as you call it similar to how @Zohman suggested: "source  /opt/openfoam6/etc/bashrc && /opt/openfoam/bin/openfoam" so the environment variables will be sourced then the executable called.

**Comment by rherban** [comment]
I'm going to go ahead and close this issue now.  Please feel free to re-open if necessary.

**Comment by AlexisEspinosaGayosso** [comment]
I found that instead of hardcoding the full list of variables, it is better to set up for the source of the bashrc file in the %post section as:
`
%post
echo ". /opt/openfoam6/etc/bashrc" >> $SINGULARITY_ENVIRONMENT
`
This will give you no issues if the bashrc is fully POSIX compatible.

But if there is any "bashism" within the bashrc (or any other definition files you want to load with this method), then the execution (singularity exec) of the container will complain. For avoiding problems with bashisms, then the file to be sourced needs to be fixed to be fully POSIX compatible. Or, this other trick may help:
```
%post
/bin/mv /bin/sh /bin/sh.original
/bin/ln -s /bin/bash /bin/sh
echo ". /opt/openfoam6/etc/bashrc" >> $SINGULARITY_ENVIRONMENT
```
which changes the /bin/sh symlink to bash instead of dash. (As suggested here: https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/Q_nc36Dwj1E)

Then,
```
$ singularity exec openfoam6-paraview54_latest.sif bash -c 'echo $WM_PROJECT_DIR'
```
should work.
