### ISSUE TITLE
Lower privileges when in "shim" mode

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#384]
After a `singularity_fork`, the parent lives on as sort of a "shim" process.   It simply sits around and does signal handling.  See:

https://github.com/singularityware/singularity/blob/master/src/lib/fork.c#L90

Two potential problems (not security issues alone, but might cause a small unrelated issue to escalate):
1.  The `sexec` process is still real UID 0 but effective UID of the invoking user.  If the invoking user came up with a clever (but currently unknown) mechanism to attack the parent `sexec`, they could escalate to root.
2.  There's a _lot_ of code in `sexec` that we don't want executed in this mode.  There's no obvious way to reach it - unless someone corrupts the `sexec` memory.

To lower the risk profile, I would propose we do two things:
* Have the parent `sexec` immediately drop to real UID non-zero.  Use a pipe for communication to prevent the child from proceeding until the parent has finished dropping permissions.  This way, we are guaranteed that end-user code is never executed until _after_ the privileges are completely dropped.
* (Even better) have the parent `exec` to a separate executable that does nothing but handle signals as an unprivileged user.  Once the exec is successful, then the child can proceed.

**Comment by bbockelm** [comment]
Not sure if it's feasible to have the parent `exec` to a separate executable.  In the session dir case, we need to do some cleanup action still.  Probably only applies to the PID namespace case.  I think dropping privileges permanently (and setting `NO_NEW_PRIVS`) is as good as we'll get.

**Comment by gmkurtzer** [comment]
We technically don't need any privileges for the cleanup so (at least in theory) we could exec() the child processes as well.

**Comment by bbockelm** [comment]
Correct.  I just liked the idea better when it was "one generic shim executable" instead of "one shim executable per use case".

I think dropping privileges permanently probably is "good enough" for now.

**Comment by gmkurtzer** [comment]
At present, the cleanup thread is a separate unprivileged binary. Still need to do the same for the `init` process for the PID namespace.

**Comment by GodloveD** [comment]
@bbockelm, @gmkurtzer, and @bauerm97 does the new `instance` support address these issues?  If so, can we close?

**Comment by gmkurtzer** [comment]
Oh, good catch @GodloveD, I think it does! I'm gonna close, but if @bbockelm feels we need more, we can reopen. Thanks!
