### ISSUE TITLE
globbing in %files section

### ISSUE THREAD

**Issue by Zohman** [apptainer/singularity#3841]
Hi,

is it possible to add file copy globbing in %files section like docker ADD directive?

in Dockerfile i could do 
ADD ./myapp-*.deb /tmp/

in singularity definition file it doesn't work and i have to specify like:
Singularity.def - 
%files
  myapp-standard-version-1.0.deb
  myapp-pro-version-1.0.deb

where i want:
Singularity.def - 
%files
  myapp-*.deb

may be related to:
https://github.com/sylabs/singularity/issues/2957

Thanks.

## Version of Singularity:

3.3.0-rc.1

### Expected behavior

$ singularity build --fakeroot myapp.sif Singularity.def 
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob 
...
 2.42 KiB / 2.42 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Copying myapp-standard-version-1.0.deb to /home/user/.singularity/sbuild-788072208/fs/myapp-standard-version-1.0.deb
INFO:    Copying myapp-pro-version-1.0.deb to /home/user/.singularity/sbuild-788072208/fs/myapp-pro-version-1.0.deb
INFO:    Running post scriptlet
...
INFO:    Adding environment to container
INFO:    Creating SIF file...
INFO:    Build complete: myapp.sif

### Actual behavior

$ singularity build --fakeroot myapp.sif Singularity.def 
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob 
...
 2.42 KiB / 2.42 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Copying myapp-*.deb to /home/user/.singularity/sbuild-843142223/fs/myapp-*.deb
FATAL:   container creation failed: unable to copy files to container fs: while copying myapp-*.deb to /home/user/.singularity/sbuild-843142223/fs/myapp-*.deb: exit status 1: /bin/cp: cannot stat 'myapp-*.deb': No such file or directory
FATAL:   While performing build: while running engine: exit status 255

### Steps to reproduce behavior

$ touch myapp-standard-version-1.0.deb myapp-pro-version-1.0.deb

Singularity.def file:
~~
BootStrap: docker
From: ubuntu:18.04

%files
  myapp-*.deb

%post
  ls -la /myapp-*.deb
~~

$ singularity build --fakeroot myapp.sif Singularity.def

**Comment by ikaneshiro** [comment]
Hey @Zohman I just merged #3447 friday which should give support for this. If you have a chance to test this out that would be fantastic!

**Comment by Zohman** [comment]
Works, Thanks.

NOTE: small bug: it doesn't expend the real filename in the container without \<destination\> (default to root(/))
it's been copied to a file name called 'myapp-*.deb'.

bug example - if:

%files
  myapp-*.deb

build.. shell.. and

> ls /
...
'myapp-*.deb'


but works with destination:

%files
  myapp-*.deb **/**

build.. shell.. and

> ls /
...
myapp-standard-version-1.0.deb

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@Zohman @dtrudg Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.
