### ISSUE TITLE
(Windows) Could not install packages due to EnvironmentError

### ISSUE THREAD

**Issue by azzaabdallah** [apptainer/singularity#3843]
## Version of Singularity:

Write here.

### Expected behavior

Install `osmread ` module 

### Actual behavior

I am using Ubuntu to run the code through a virtual env. once I prompt it to install osmread, an error pops up saying: `ERROR: Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted: '/mnt/c/Users/azza.abdallah/Documents/CODE/myenv/lin/python2.7/site-packages/lxml/ElementInclude.py' `

### Steps to reproduce behavior

The command line I am using is `pip install osmread`

The python version I have is 2.7 and the python code I want to run is also using version 2.7

**Comment by jscook2345** [comment]
@azzaabdallah 

I'm confused about the question here. Is this in a container?

**Comment by azzaabdallah** [comment]
@jscook2345 I'm sorry, I don't understand what you mean by "container"? 

I might have posted this question under the wrong topic, I'm quite new to github.

**Comment by rherban** [comment]
Singularity is a container platform which allows you to encapsulate a Linux program into a single image.  Sorry that this was posted to the wrong group, but unfortunately I'm not sure where it would need to go.
