### ISSUE TITLE
Container Build Fails (»Process Capabilities«); LXC Issue?

### ISSUE THREAD

**Issue by AndiH** [apptainer/singularity#3844]
## Version of Singularity:

3.2.1 on ppc64le

### Expected behavior

`sudo singularity build OUT.simg IN.srecipe` actually builds the image.

### Actual behavior

The command fails with

```
Writing manifest to image destination
Storing signatures
ERROR  : Failed to set process capabilities
```

The process hangs afterwards, can be exited with Ctrl+c, but still needs to be killed with `sudo kill -9 PID`.

### Steps to reproduce behavior

The issue is encountered on our POWER8NVL-based HPC system [JURON](https://www.fz-juelich.de/portal/EN/Research/ITBrain/Supercomputer/JULIA_JURON/_node.html), which runs CentOS 7.6.1810.

We just now updated from Singularity 2 to Singularity 3. With Singularity 2 we were and are still able to build images according to the aforementioned build string; the issue is only encountered with Singularity 3.

Running with `--debug build […]` gives the following additional information

```
    DEBUG   [U=0,P=107656]     prepare_stage()               Entering in stage 2
    DEBUG   [U=0,P=107656]     set_parent_death_signal()     Set parent death signal to 9
    VERBOSE [U=0,P=107657]     init()                        Spawn RPC server
--> ERROR   [U=0,P=107656]     prepare_stage()               Failed to set process capabilities <--
    VERBOSE [U=0,P=107647]     startup()                     Execute master process
    VERBOSE [U=0,P=107657]     startup()                     Serve RPC requests
    DEBUG   [U=0,P=107647]     CreateContainer()             Mounting image directory /tmp/sbuild-619227573/fs
```

(Highlighting from me.)

The machine I run the command on actually is a LXC container on CentOS (lxc-1.0.11). When we execute the build command on the raw machine, we do not see the issue and it looks like we can build the container.  
Maybe the problem lies in nested containerism with Singularity 3?

(I imagine the error comes from [`starter.c`:262](https://github.com/sylabs/singularity/blob/master/cmd/starter/c/starter.c#L261-L263), but I have no clue what's going on there…)

**Comment by dtrudg** [comment]
Hi @AndiH do you know what your LXC configuration on the host looks like? Particularly what `lxc.cap.drop` and `lxc.cap.keep` are?

**Comment by AndiH** [comment]
@dctrud: In `usr/share/lxc/config/centos.common.conf` we find the following (and only) references to `lxc.cap.drop` – nothing regarding `lxc.cap.keep`. The file is included in our own config, as it appears.

```
lxc.cap.drop = mac_admin mac_override setfcap
lxc.cap.drop = sys_module sys_nice sys_pacct
lxc.cap.drop = sys_rawio sys_time
```

**Comment by dtrudg** [comment]
I suspect that dropping `setfcap` is likely to be causing this. See https://lists.linuxcontainers.org/pipermail/lxc-users/2016-February/010955.html

**Comment by AndiH** [comment]
Alright. I can not easily try to disable this – and also need to discuss implications with the administrative staff (which could take a while).

I'm coming back once we've discussed (and/or implemented) this! Thanks!

**Comment by rherban** [comment]
@AndiH I'm going to close this issue for now, but please re-open when you're able to test.
