### ISSUE TITLE
Bindmounts not happening when --writable is used with a sandbox container.

### ISSUE THREAD

**Issue by JayjeetAtGithub** [apptainer/singularity#3846]
## Version of Singularity:

Singularity 3.2.0

### Expected behavior

I have a sandbox created with `--sandbox` flag. When i try to execute it with the `--writable` flag and add the bindings `--bind $HOME:/path/to/home`, I expect a bindmount `/path/to/home` to get created inside the sandbox during runtime/executiontime.

### Actual behavior

The bind mount mentioned above doesn't work. No volumes except the `/tmp`, `/var/tmp` etc. gets mounted.

### Steps to reproduce behavior

```
$ sudo singularity exec --bind $HOME:/github/home --writable deb/ ls /
bin  boot  dev	environment  etc  home	lib  lib64  media  mnt	opt  proc  root  run  sbin  singularity  srv  sys  tmp	usr  var
```
No directory `github/`

But without writable flag,

```
$ sudo singularity exec --bind $HOME:/github/home deb/ ls /
bin  boot  dev	environment  etc  github  home	lib  lib64  media  mnt	opt  proc  root  run  sbin  singularity  srv  sys  tmp	usr  var

```
We can see the `github/` path.

**Comment by cclerget** [comment]
Hi @JayjeetAtGithub , this is the expected behavior when using `--writable` flag because there is no overlay involved so Singularity doesn't create non-existent files/directories for you on-the-fly, you need to create it manually in image
