### ISSUE TITLE
Incorrect %files section arg comment handling

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#3848]
## Version of Singularity:

master

### Actual behavior

The image build system currently does not properly handle comments in the arguments of the `%files` section. When building with a definition like:

```
Bootstrap: library
From: alpine


%files
	file1 
	file2

%files #  # from test
	file1
	file2

%files #   #comment
	file1
	file2
```

You get this error: 
```
$ sudo singularity build test.sif files_section_err.def 
Build target already exists. Do you want to overwrite? [N/y] y
INFO:    Starting build...
FATAL:   While performing build: unable to copy files a stage to container fs: stage #comment was not found
```

### Expected behavior

Successful build copying the same pair of files three times.

**Comment by dtrudg** [comment]
Still exists in 3.6
