### ISSUE TITLE
Random container creation failure when starting multiple containers

### ISSUE THREAD

**Issue by sfintz67** [apptainer/singularity#3860]
## Version of Singularity:

2.6.1 and above.
Affected tested versions: 2.6.1, 3.1.1, 3.2.1

### Expected behavior

Be able to start and run several containers in a short period of time on the same machine with the same user

### Actual behavior

Singularity randomly fails with the following message:
FATAL:   container creation failed: mount /proc/self/fd/3->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount squashfs filesystem: invalid argument

dmesg shows also the following error:
[4688405.776500] squashfs: SQUASHFS error: Can't find a SQUASHFS superblock on loop6

### Steps to reproduce behavior

Starting containers sequentially is ok:
sfintz@msy523001:~$ for (( i = 0; i < 10; i++ )); do singularity exec /scr/.container_cache/g2_singularity_1.7.db7 "id"; done
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)

Starting them in the background fails. Notice than even bash exited then:
sfintz@msy523001:~$ for (( i = 0; i < 10; i++ )); do singularity exec /scr/.container_cache/g2_singularity_1.7.db7 "id" & done
[1] 4319
[2] 4320
[3] 4321
[4] 4322
[5] 4323
[6] 4324
[7] 4325
[8] 4326
[9] 4327
[10] 4328
sfintz@msy523001:~$ FATAL:   container creation failed: mount /proc/self/fd/3->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount squashfs filesystem: invalid argument
FATAL:   container creation failed: mount /proc/self/fd/3->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount squashfs filesystem: invalid argument
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
uid=24031(sfintz) gid=100(users) groups=100(users)
exit
msy523001%

**Comment by cclerget** [comment]
Hi @sfintz67, I wasn't able to reproduce this issue with an alpine image, at first possible causes I think of are :
- really big image
- filesystem issue

To check if the issue is related to image size, you can try with alpine image :

```
singularity pull /tmp/test.sif docker://alpine
for i $(seq 1 100); do singularity exec /tmp/test.sif id & done
```

Otherwise since Singularity 3.1, you also had the possibility to share a loop device if you load the same image multiple (typically for MPI), you can enable that in `singularity.conf` by setting `shared loop devices = yes`

**Comment by sfintz67** [comment]
Hi Cclerget,

Thanks for your reply.
I re-ran some tests on several machines running debian9. None of them have any filesystem issue reported.

I also tested it on a lubuntu 19.04 with a completely different user configuration.
singularity --version
singularity version 3.1.0-1
Only default configuration

They are all failing the same way even with the alpine image:
stef@padawan:~$ singularity pull /tmp/test.sif docker://alpine
stef@padawan:~$ for i in $(seq 1 10); do singularity exec /tmp/test.sif id & done
[1] 5981
[2] 5982
[3] 5983
[4] 5984
[5] 5985
[6] 5986
[7] 5987
[8] 5988
[9] 5989
[10] 5992
stef@padawan:~$ uid=1000(stef) gid=1000(stef) groups=4(adm),20(dialout),21(ftp),24(cdrom),25(at),26(tape),27(video),29(audio),30(readproc),44(video),46(plugdev),119(lpadmin),121(scanner),127(sambashare),1000(stef)
uid=1000(stef) gid=1000(stef) groups=4(adm),20(dialout),21(ftp),24(cdrom),25(at),26(tape),27(video),29(audio),30(readproc),44(video),46(plugdev),119(lpadmin),121(scanner),127(sambashare),1000(stef)
uid=1000(stef) gid=1000(stef) groups=4(adm),20(dialout),21(ftp),24(cdrom),25(at),26(tape),27(video),29(audio),30(readproc),44(video),46(plugdev),119(lpadmin),121(scanner),127(sambashare),1000(stef)
uid=1000(stef) gid=1000(stef) groups=4(adm),20(dialout),21(ftp),24(cdrom),25(at),26(tape),27(video),29(audio),30(readproc),44(video),46(plugdev),119(lpadmin),121(scanner),127(sambashare),1000(stef)
uid=1000(stef) gid=1000(stef) groups=4(adm),20(dialout),21(ftp),24(cdrom),25(at),26(tape),27(video),29(audio),30(readproc),44(video),46(plugdev),119(lpadmin),121(scanner),127(sambashare),1000(stef)
uid=1000(stef) gid=1000(stef) groups=4(adm),20(dialout),21(ftp),24(cdrom),25(at),26(tape),27(video),29(audio),30(readproc),44(video),46(plugdev),119(lpadmin),121(scanner),127(sambashare),1000(stef)
uid=1000(stef) gid=1000(stef) groups=4(adm),20(dialout),21(ftp),24(cdrom),25(at),26(tape),27(video),29(audio),30(readproc),44(video),46(plugdev),119(lpadmin),121(scanner),127(sambashare),1000(stef)
FATAL:   container creation failed: mount error: can't mount image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: Failed to set loop flags on loop device: resource temporarily unavailable
uid=1000(stef) gid=1000(stef) groups=4(adm),20(dialout),21(ftp),24(cdrom),25(at),26(tape),27(video),29(audio),30(readproc),44(video),46(plugdev),119(lpadmin),121(scanner),127(sambashare),1000(stef)
uid=1000(stef) gid=1000(stef) groups=4(adm),20(dialout),21(ftp),24(cdrom),25(at),26(tape),27(video),29(audio),30(readproc),44(video),46(plugdev),119(lpadmin),121(scanner),127(sambashare),1000(stef)

Thanks

**Comment by cclerget** [comment]
Can you try by compiling from master branch ? Early versions have issues.

However the error changed when you tested on ubuntu 19.04 and alpine image : `Failed to set loop flags on loop device: resource temporarily unavailable`. What say `dmesg` after that ? that could give some hint from kernel.

**Comment by sfintz67** [comment]
The error messages is:
[  282.524933] loop_set_status: loop1 () has still dirty pages (nrpages=1)
[  284.836950] loop_set_status: loop2 () has still dirty pages (nrpages=1)
[  285.905075] loop_set_status: loop4 () has still dirty pages (nrpages=1)

I installed the latest stable version ie 3.2.1 and can still reproduce the problem.
Yet again the problem appears from time to time

Tried also with singularity-master and the issue is still there.
I had to run 3 times 
for i in $(seq 1 100); do singularity exec /tmp/test.sif id & done
to have again the issue

**Comment by cclerget** [comment]
Ok @sfintz67 , those `dmesg` lines is what I wanted to check, this is a kernel regression introduced in https://lore.kernel.org/linux-block/20190121122503.771813232@linuxfoundation.org/T/ and the original author attempt to fix it and merge it back in upstream here : https://lkml.org/lkml/2019/5/17/787. Not done yet

**Comment by sfintz67** [comment]
Ooh great! That's a kernel bug :-)
By the way, when you said that early versions have issues, what do you mean exactly? Issue with that /dev/loop or anything else?

**Comment by cclerget** [comment]
Yes, there was a race condition issue during loop lookup among many others and not related to loop device. I would recommend 3.2.1 as the minimal version

**Comment by sfintz67** [comment]
Ok great, thanks a lot for your help.
Closing the issue
