### ISSUE TITLE
containers must have metadata

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#387]
If one of the goals of a container is reproducibility, we need a strategy for metadata. For example, docker has a simple `LABEL` field [docs here](https://docs.docker.com/engine/userguide/labels-custom-metadata/) that can be specified in the Dockerfile for a piece of metadata (see an [example file](https://github.com/BioContainers/specs/blob/master/container-specs.md#dockerfile-example) here. Users aren't good about metadata, so this is under-utilized. I haven't investigated this thoroughly, but looking at the docs I would guess that the metadata is stored with the manifest for the image, volume, etc, and not with the layer/image itself. This makes sense given that Docker containers are built from layers, however for Singularity, we have been pretty consistent to focus on maintaining an entire image file, and so my thinking is that it's possibly feasible to have a strategy to also store metadata with the image. (eg, see https://github.com/singularityware/singularity/pull/376).

The metadata about an image, sometimes, is just as important as the image itself. In the example I linked above, this has become a standard to use these labels for BioContainers to carry information about the software inside. As currently implemented, a Docker container converted to Singularity will lose all of this information, and this is not acceptable! Let's fix this.

**Comment by bbockelm** [comment]
Are you thinking something like `.singularity-info` file inside the image?

Actually, given the number of hidden files that are starting to appear inside `/`, maybe we should have a `/.singularity` directory for meta-information?

**Comment by vsoch** [comment]
Yes! This is hugely important. I think we can implement some "hard" structure that gives the user flexibility to define metadata, and a folder that the user knows to put things in is an example of that. A simple .singularity-info folder / file (it comes down to the same issue of having one `.environment` file vs. a folder) 

I think we need something like the following:

- a top level directory that is known to contain singularity metadata / stuffs.  
- probably the environment subdirectory that generates the main environment file would also go in here?
- For permissions, some content should arguably be accessible easily without root, but some other content may be desired to have different permissions. For example, if I'm doing some analysis to compare metadata about containers, or I only care about that, I should be able to spit out those things without root. On the other hand, there may be paths to important libraries (for the environment bits in this folder) that I wouldn't want to change.
- we might even have some way to record history / usage of a container, so the container itself actually carries around its own history and documents itself. 
- a content hash of the container at its birth, etc, so that a user can always check to see if it's the same as it was first made. To go along with that, we might even store the spec file (build file if used) in the container, but that may be too much.

The challenge I think comes down to data structures. it would be really great if we could store some of these things in the header. Probably the ones that we know the size of (content hash?) we could. For others, it comes down to a standard hierarchy of files and folders! I am of the opinion that simpler is better, but allowing for customization by the user. And I think we should anticipate some things to come. For example, right now containers are optimized to hold dependencies, and perform an analysis (or action) by running them and producing some output. But a container would go much further if it knew how to generate a result of a particular data structure, and then serve it. This could probably done via a runscript that takes an argument that tells the container what to do, but I think we could make it easier for the user than that by giving containers an understanding of context. This isn't so different from a container being able to detect what libraries are needed from the host, but it's relevant for web servers and other visual outputs. 

Arguably a custom context is really just a robust runscript that can parse input and set the right environment variables and call the right scripts. But maybe it would be easier, both to generate and use, to allow for this functionality by way of letting the user define multiple runscripts (contexts). For example, I should be able to generate a context called `run-analysis` that hits my main python executable and does some genomics thing. I might also want a particular context linked to the executable for step 2, and then step 2, so running on the command line would be like:

     singularity run analysis.img --context main
     singularity run analysis.img --context step1
     singularity run analysis.img --context step2

when the user is creating the bootstrap it could still look as it does now. Having this:

      %runscript
 
             exec echo "Hello World" "$@"

would have this return:

      singularity run analysis.img Hello Kitty!
     "Hello World Hello Kitty!"

and in the container, the file structure looks as it does now:

      /singularity

But then let's say I have a bunch of different scripts that my container wants to access. I could write a more complicated runscript to parse the input. But I'm a researcher so I'm probably not going to do that, I'm going to do like:

      singularity exec analysis.img /path/to/script1.sh
      singularity exec analysis.img /path/to/script2.sh

but then when I give my container to someone else, they are like "What do I do with this, bruh?"

Now let's pretend I'm allowed to define contexts. It's easier for me to write the build spec, because I just write different runscripts:

      %runscript:main
 
             exec /path/to/script/main.sh "$@"

      %runscript:preprocess
 
             exec /path/to/script/preprocess.sh "$@"

and then the default runscript could either use one of those by default, OR generate the simple usage (equivalent to typing `--help`). So then when the user finds the mysterious container and runs it he sees:

      singularity run analysis.img
      Usage:
           The following contexts are available for this container:

            main  /path/to/script/main.sh
            preprocess  /path/to/script/preprocess.sh

           Specify a context with --context
          

Then the folder structure for this in the container would look like:

      /singularity
      /.singularity
           context/
                 main
                 preprocess

and the naming, docs for that could be more clear. But does the general idea make sense? We want to make containers, and specifically their intended use, more easily exposed. The equivalent to the above could be done for environment variables, and then the user could select what set to include (or not include) with some (user or cluster specified) default. So to add to the above:

      /singularity
      /.singularity
           context/
                 main
                 preprocess
           env/
                 docker
                 nvidia
                 local

Then for metadata, we might have like:

      /singularity
      /.singularity
           context/
                 main
                 preprocess
           env/
                 docker
                 nvidia
                 local
           metadata/

and some agreed upon file / data structure would need to be used for the meta data, and this is where we would write docker labels, history, etc.

**Comment by gmkurtzer** [comment]
@vsoch I this is implemented satisfactorily in the "Development" branch. Please comment if I missed something and need to reopen it.

**Comment by vsoch** [comment]
Nope this came out very good! The --context bit is actually satisfied very well by `%labels` :) Thanks @gmkurtzer !
