### ISSUE TITLE
[Incorrect] Necessity of libseccomp? Headers not provided on RHEL8

### ISSUE THREAD

**Issue by omenos** [apptainer/singularity#3874]
RHEL 8 (which, along with 7.7 adds support for namespaces OOB) does not ship with `libseccomp-devel`. Is `libseccomp` a critical package to Singularity? I'm assuming it is. If it isn't, an extra check in the spec file can be added, otherwise RHEL users shouldn't use RHEL 8 unless they plan on providing the headers themselves. It's in the unsupported category based on documentation released (although `libseccomp` itself is provided):

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#removed-packages_changes-to-packages

**Comment by jscook2345** [comment]
It is an optional dependency I believe, but some functionality will not work if it is not installed. My best guess is that commands which include a libseccomp profile only, but I have not verified that.

I don't have an exact list of that (@cclerget ?) but perhaps we can create one.

**Comment by cclerget** [comment]
Yes it's optional for HPC usage. @jscook2345 Singularity OCI containers relies on seccomp in OCI specification

**Comment by omenos** [comment]
I was incorrect, libseccomp-devel is provided on RHEL 8. However, it is not in the base repositories, it's in the Code Ready repo. Might be best to note that in the setup docs.

Solution:
```bash
sudo subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
```
Associated blog post explaining what this repo is:

https://developers.redhat.com/blog/2018/11/15/introducing-codeready-linux-builder/

**Comment by DrDaveD** [comment]
I found that what's needed on CentOS8 is
```yum --enablerepo=PowerTools install libseccomp-devel```

**Comment by omenos** [comment]
Forgot about this ticket. Yes, The PowerTools repo is the CodeReady Builder repo for CentOS. They couldn't use the name of CodeReady (I think due to trademarks), so there will be a split in naming with those repos between RHEL 8 and CentOS 8.
