### ISSUE TITLE
Reset $HOME with '-c' or 'mount home = no'

### ISSUE THREAD

**Issue by Zohman** [apptainer/singularity#3884]
## Version of Singularity:

3.3.0-rc.1

### Issue Explain

i'm using autofs tool to automount nfs mount-points under /nfs/... which use LDAP queries.

in singularity config i've defined:
bind path = /nfs
to make it available in the container and it works very well.

The issue i'm experiencing is that users homes are under /nfs as well ( /nfs/homes/user )
and i don't want their home to bind to the container **by default**.

trying:
mount home = no

has no effect as /nfs is accessible and 'getent passwd user' return /nfs/homes/user.

the only way i could workaround this was to create a singularity wrapper
with the SINGULARITY_HOME, something like:

/usr/local/bin/singularity:
\---------------------------
#!/bin/bash
\# 
export SINGULARITY_HOME=/tmp
exec /opt/singularity/install/bin/singularity "$@"
\---------------------------

### Enhancement suggestion

do you think it will be possible to define --fakehome that creates a temporary homedir inside the container when accessed by non-root ( with the ability to make it default in config as well )?
using the 'small sessiondir max size' for it?

Second, ( I'm actually wonder how it doesn't implemented until now )
the ability for the admin to set some appendix defaults,
creating default environment variable file to source when singularity start,
file like INSTALL_PREFIX/etc/default/singularity

thanks.

**Comment by rherban** [comment]
@Zohman 

Can you run it with `-d` to give debug output? I edited my config to have `mount home = no` and saw this in the debug output:
```
DEBUG   [U=1000,P=1223]    addHomeMount()                Skipping home dir mounting (per config)
```

Do you have `/nfs` created inside the container?  Bind path requires it to exist in the container already before it will mount.

I'll let @cclerget respond to the fakehome suggestion.

**Comment by Zohman** [comment]
@rherban:
> "Bind path requires it to exist in the container already before it will mount."

i thought i saw that behavior on early versions.. but **no** i don't create the /nfs directory
during build or after.. but i have to say that i do think the current behavior is a good practice,
i want 'bind path' directories created and mounted per config 
unless user override it with -B /tmp:/nfs for example.. (which work)

i can say that another workaround i found working was to set systemd user tmpfs share:
**$ singularity run -B /run/user/\`id -u\`:$HOME simg.sif**

i might be able to tune my wrapper with SINGULARITY_BINDPATH / SINGULARITY_BIND
avoiding -B and SINGULARITY_HOME, need to check..

as for your question, here is the debug output:
`VERBOSE [U=1000,P=20403]addBindsMount()               Found 'bind path' = /nfs, /nfs`
`DEBUG   [U=1000,P=20403]addHomeMount()                Skipping home dir mounting (per config)`

Thanks.

**Comment by rherban** [comment]
I think I'm missing something still.  So when a user shells into a container, right now they won't have their home mounted directly, but will still be able to access their home through /nfs/home/user (since /nfs binding is working as expected).  

Are you trying to block access to their home entirely?

**Comment by Zohman** [comment]
@rherban, yes and no..

$HOME inside the container still return the user home as read from passwd (which is /nfs/homes/user)
now, as /nfs is mounted.. i can reach /nfs/homes/user and the home config become irrelevant as it seems.

blocking access is relevant but not what intended.. i could expect $HOME to be reset
or to have some temporary homedir. ( --fakehome ? )

>user@host003[/localdrive/users/user]$ singularity shell ./simg.sif
Singularity simg.sif:/localdrive/users/user> echo $HOME
**/nfs/homes/user**

if removed from config: ( with `mount home = no` )
`bind path = /nfs`

see below i can't reach homedir, but we would expect $HOME to be reset as well, right?

>user@host003[/localdrive/users/user]$ singularity shell ./simg.sif
Singularity simg.sif:/localdrive/users/user> cd ~
bash: cd: /nfs/homes/user: No such file or directory
Singularity simg.sif:/localdrive/users/user> echo $HOME
**/nfs/homes/user**

**Comment by rherban** [comment]
Ok, I think I'm starting to understand.  It sounds like the big problem here is keeping the `$HOME` environment variable within the container when `mount home = no` in the config or `--contain` is passed in at command line.  Both will block mounting the user's home, but don't reset the env variable  which presents a false sense of reality.  


The wrapper script you mentioned overwrites `$HOME` and leaves them in a writable space (aka /tmp on the host OS), giving the impression of a writable home that isn't the same as the host.  

The main feature request is `--fakehome` which does the same as your wrapper script and provides a writable "$HOME" that isn't the same as the host (which matches your initial request exactly, I just got stuck on the /nfs piece).

The second request is ability to override environment variables at a system level.  

Does that sound right to you?

**Comment by jmstover** [comment]
So ... the HOME value comes from the `/etc/passwd` entry. To change it you could do something like:

```
singularity shell -H /home/user ./simg.sif
```

The `-H` option will change the HOME value for the user. You can also do something like you mentioned, and do:
```
singularity shell -H /run/user/`id -u`:/home/`id -un` ./simg.sif
```

Which will bind `/run/user/#####` to `/home/<user name>` ... and set `/home/<user name>` as the value for `HOME`

*Edit:*
So, you would have in `singularity.conf`:
```
mount home = no
bind path = /nfs
```

That _should_ attempt to *not* mount the users home directory, but still have the full `/nfs` structure available to you.

**Comment by Zohman** [comment]
Thanks for the replies @rherban and @jmstover ,

> **rherban**: Both will block mounting the user's home, but don't reset the env variable which presents a false sense of reality.

yes, exactly.. as i bind /nfs which have many junctions.. such /nfs/projects /nfs/disks ..  etc. 
and also /nfs/homes/...

> **rherban**: The wrapper script you mentioned overwrites $HOME and leaves them in a writable space (aka /tmp on the host OS), giving the impression of a writable home that isn't the same as the host.

yes, /tmp is lesser of two evils at this point, i would appreciate clean temporary homedir
during the container execution run-time. if you ask, this is mostly to avoid ~/.profile ~/.bashrc ~/.csh and
other config files that may get loaded from scripts/tools streamed through the container.

> **rherban**: The main feature request is --fakehome which does the same as your wrapper script and provides a writable "$HOME" that isn't the same as the host (which matches your initial request exactly, I just got stuck on the /nfs piece).

yes indeed, sorry if i was misunderstood. 
also, --fakeroot should set fake/tmp home automatically as it doesn't make sense to bind 
the user home on root namespace i suppose..

> **rherban**: The second request is ability to override environment variables at a system level.

you may tell, i thought about first-in-the-chain with the others that can override it;
` INSTALL_PREFIX/etc/default/singularity` **>** `SINGULARITY_*=XXX` **>** `$ singularity --args`

-----

> **jmstover**: The -H option will change the HOME value for the user.

my goal is not to use arguments, but i didn't know `-H` have both sides,
did some tests with `SINGULARITY_HOME` and it seems that if the host side
doesn't exist singularity creates that fake/temp home as i wanted. ( it's not a bug it's a feature ) :)

**$ export SINGULARITY_HOME="/null:$HOME"**
**$ singularity shell ./simg.sif**
`Singularity simg.sif:~> df $HOME`
`Filesystem      Size  Used Avail Use% Mounted on`
`tmpfs            16384   12  16372   1% /nfs/homes/user`

so for now i'll use it with the wrapper.

----

Thank you!
---

**Comment by rherban** [comment]
You might be able to bind in `/nfs`, then bind `/tmp/homes:/nfs/home` on top of it to completely deny access to their home, if that's useful at all (I haven't tested, but this how filesystem mounts work in Linux).
