### ISSUE TITLE
pulling/running directly into sandbox directories instead of intermediate sif for unprivileged users

### ISSUE THREAD

**Issue by thdesy** [apptainer/singularity#3886]
Follow-up to #2588 by @afortiorama 

## Version of Singularity:

3.2.0-1.el7

### Expected behavior

as unprivileged user (setuid disabled, user namespace enabled) pull/run a Docker container/image from a remote hub directly into a sandbox directory to allow for direct execution.

`singularity pull --sandbox docker://ubuntu`

### Actual behavior / Steps to reproduce behavior
As unprivileged user without setuid but only user-ns,  pulling/running results in two conversions steps

```
> singularity pull docker://ubuntu
INFO:    Starting build...
...
INFO:    Creating SIF file...
INFO:    Build complete: ubuntu_latest.sif

> singularity exec  -u --containall  ubuntu_latest.sif echo "hi"
INFO:    Convert SIF file to sandbox...
...
```

It would improve the workflow, if pulling directly into a sandbox dir instead of a sif image would be possible.

**Comment by Zohman** [comment]
try this:

\> **singularity build --sandbox sandbox_ubuntu/ docker://ubuntu**
INFO:    Starting build...
...
Writing manifest to image destination
Storing signatures
INFO:    Creating sandbox directory...
INFO:    Build complete: sandbox_ubuntu/

\> **singularity exec -u --containall sandbox_ubuntu/ echo "hi"**
hi

**Comment by afortiorama** [comment]
@zohman I'm already doing that. 

As I said in #2588 that is an extra step that in 2.6.1 wasn't needed. Also in 2.6.1 the layers were downloaded once and used. Now even when sandboxing  the layers in the cache are duplicated in a temporary directory which is a waste of space, even if temporary, and walltime. If each job does that it may cause space problems difficult to detect.

**Comment by jscook2345** [comment]
@ikaneshiro @cclerget 

It looks like they would like to improve the flow of creating images and converting them. What do you think?

**Comment by mem** [comment]
Checking with current master, I see this:

```
$ builddir/singularity build --sandbox foo library://alpine
INFO:    Starting build...
INFO:    Downloading library image
INFO:    Creating sandbox directory...
INFO:    Build complete: foo
```

does that satisfy the original request, @thdesy ?

**Comment by afortiorama** [comment]
The SIF image gets created during an exec or a pull not during the build of a sandbox. building a sandbox is a work around to avoid the SIF.

```
singularity exec docker://centos:7 echo 'Hello'
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:d8d02d45731499028db01b6fa35475f91d230628b4e25fab8e3c015594dc3261
 71.92 MiB / 71.92 MiB [====================================================] 3s
Copying config sha256:acab94af64effb1f7481666a37788e7a59465e723f0b0fe0a0f458f3f4856638
 1.05 KiB / 1.05 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
2019/09/28 08:17:06  info unpack layer: sha256:d8d02d45731499028db01b6fa35475f91d230628b4e25fab8e3c015594dc3261
2019/09/28 08:17:06  warn rootless{usr/bin/ping} ignoring (usually) harmless EPERM on setxattr "security.capability"
2019/09/28 08:17:10  warn rootless{usr/sbin/arping} ignoring (usually) harmless EPERM on setxattr "security.capability"
2019/09/28 08:17:10  warn rootless{usr/sbin/clockdiff} ignoring (usually) harmless EPERM on setxattr "security.capability"
INFO:    Creating SIF file...
INFO:    Convert SIF file to sandbox...
Hello
INFO:    Cleaning up image...
```
sif image is left as an artefact together with the blobs. 
```
ls -l .singularity/cache/*/*/*
-rwxr-xr-x 1 aforti aforti 73674752 Sep 28 08:17 .singularity/cache/oci-tmp/307835c385f656ec2e2fec602cf093224173c51119bbebd602c53c3653a3d6eb/centos_7.sif
.singularity/cache/oci/blobs/sha256:
total 73656
-rw-r--r-- 1 aforti aforti      350 Sep 28 08:17 9509e1977c66f76f9e342829ed350d693fd886035a44713da930e6a16ddc4f8b
-rw-r--r-- 1 aforti aforti     1074 Sep 28 08:17 acab94af64effb1f7481666a37788e7a59465e723f0b0fe0a0f458f3f4856638
-rw-r--r-- 1 aforti aforti 75412258 Sep 28 08:17 d8d02d45731499028db01b6fa35475f91d230628b4e25fab8e3c015594dc3261
```
if one tries again it says it builds the sandbox 
```
singularity exec docker://centos:7 echo 'Hello'
INFO:    Convert SIF file to sandbox...
Hello
INFO:    Cleaning up image...
```
but the sandbox is actually another artefact left behind in /tmp 
```
ls -l /tmp/sbuild-419540731
total 4
drwxr-xr-x 4 aforti aforti 4096 Sep 28 08:17 fs
```
I have 3.4.0 installed now so if not the latest pretty much
```
singularity --version
singularity version 3.4.0-1.2.el7
```
as an aside those warnings that now get print out are only 3 in this case but on more complex images are thousands almost every file.
