### ISSUE TITLE
implement simple version of argparse

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#389]
argparse is supported on python 2 (default library) but not RHEL 6. We need to implement a basic argparse - like strategy that does not have argparse as a dependency, but probably (hopefully) more than a strategy that assumes arguments are provided in some specific order (e.g., sys.argv[0]). Since this is a client used only by the bootstrap, it should be pretty reasonable to not have the degree of argument parsing that one would want for a true client.

**Comment by bbockelm** [comment]
Why not use `optparse`?  It's available across all python versions (starting in python 2.3 through current python 3 releases).

It _is_ deprecated in `python3`, but hopefully we can drop RHEL6 support before it is removed from `python3`.

**Comment by vsoch** [comment]
hmm, yeah boo that it's [deprecated](https://docs.python.org/2/library/optparse.html) - we must support python 3! I didn't get a chance to look at this today, but I think we could either go in a direction for something simpler (eg. using sys.argv to get similar functionality without the bells and whistles) or do what we are doing for most python2/3 compatibility issues, trying to first import the favorable, and if that fails, go to a fallback. In this case, the favorite would be argparse, and the fallback would be optparse. This is making the assumption that python 3 isn't available on RHEL6 so we wouldn't hit a #doublefail.

**Comment by vsoch** [comment]
optparse and argparse are also [eerily similar](https://github.com/MartinThoma/matrix-multiplication/commit/7af938c54fd2effee3efe74352b76f01d2e817e5#Python/ikjMultiplication.py)! You could (almost) import one as the other and use them equivalently if it weren't for the `add_option` vs `add_argument`

**Comment by bbockelm** [comment]
Deprecated != gone, right?  We can certainly still use `optparse` for a few more years on both major python versions.  Basically, wait until we can drop RHEL6.

Alternately, the `python-argparse` RPM is available on RHEL6 via EPEL.  That would be a new runtime dependency - but that's kind what `yum` is for.

**Comment by vsoch** [comment]
Good point! I'd be down for using optparse, and then updating in a few years when it goes to it's pythonic grave. :scream: Hopefully RHEL6 will be already spinning in that same neck of the woods... haha. @gmkurtzer does that seem like a good way to go?
