### ISSUE TITLE
building definition file directly to sandbox with --fakeroot fail.

### ISSUE THREAD

**Issue by Zohman** [apptainer/singularity#3892]
## Version of Singularity:

3.3.0-rc.1.142

### Expected behavior

Building sandbox directly from definition file failed,
but if building from the image .sif file created from the def file it succeed.

**$ singularity build --fakeroot simg.sif Singularity.def**
INFO:    Starting build...
...
INFO:    Creating SIF file...
INFO:    Build complete: simg.sif

**$ singularity build --fakeroot --sandbox sandbox_chroot/ simg.sif** 
INFO:    Starting build...
INFO:    Creating sandbox directory...
INFO:    Build complete: sandbox_chroot/

**$ singularity build --fakeroot --sandbox sandbox_chroot/ Singularity.def**
...
FATAL:   While performing build: Sandbox Assemble Failed: exit status 1: mv: cannot access '/tmp/sbuild-928059436/fs/var/cache/apt/archives/partial': Permission denied

would like to build to the sandbox directly from def file and succeed with --fakeroot.

### Actual behavior

$ **singularity -d build --fakeroot --sandbox sandbox_chroot/ Singularity.def** 
DEBUG   [U=12544,P=16855]createConfDir()               /nfs/homes/user/.singularity already exits. Not creating.
DEBUG   [U=12544,P=16855]getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
...
DEBUG   [U=12544,P=16855]bundleCommon()                Created temporary directory for bundle /tmp/sbuild-782313980
INFO    [U=12544,P=16855]Full()                        Starting build...
...
DEBUG   [U=12544,P=16934]Master()                      Child exited with exit status 0
DEBUG   [U=12544,P=16855]Full()                        Inserting Metadata
DEBUG   [U=12544,P=16855]Full()                        Calling assembler
INFO    [U=12544,P=16855]Assemble()                    Creating sandbox directory...
DEBUG   [U=12544,P=16855]Assemble()                    Moving sandbox from /tmp/sbuild-782313980/fs to sandbox_chroot/
DEBUG   [U=12544,P=16855]cleanUp()                     Build bundle(s) cleaned: [/tmp/sbuild-782313980]
**FATAL   [U=12544,P=16855]run()                         While performing build: Sandbox Assemble Failed: exit status 1: mv: cannot access '/tmp/sbuild-782313980/fs/var/cache/apt/archives/partial': Permission denied
mv: cannot access '/tmp/sbuild-782313980/fs/var/lib/apt/lists/partial': Permission denied**

### Steps to reproduce behavior

Singularity.def:
\------------------
BootStrap: docker
From: ubuntu:18.04

%post
  apt-get update
  apt-get -y install lsb-release
\------------------
$ **singularity -d build --fakeroot --sandbox sandbox_chroot/ Singularity.def**

**Comment by Zohman** [comment]
**[SOLVED]** okay, this issue seems persistent.. even though converting the sif to sandbox doing some
container updates and trying to build the .sif again, failed..

**$ singularity build --fakeroot new_simg.sif sandbox_chroot/**
_INFO:    Starting build...
FATAL:   While performing build: packer failed to pack: cp Failed: exit status 1: cp: cannot access 'sandbox_chroot/./var/cache/apt/archives/partial': Permission denied
cp: cannot access 'sandbox_chroot/./var/lib/apt/lists/partial': Permission denied_

Listing var/lib/apt/lists/partial from the host POV showd uid namespace leftovers:

**host** > ls -la sandbox_chroot/./var/lib/apt/lists/
_drwxr-xr-x 2 **4227858531** users 4.0K Jul  9 19:11 auxfiles
-rw-r----- 1 user    users    0 Jul  9 19:11 lock
drwx------ 2 **4227858531** users 4.0K Jul  9 19:14 partial_

**container** > ls -la ./var/lib/apt/lists/
_drwxr-xr-x 2 **_apt** root     4096 Jul  9 16:11 auxfiles
-rw-r----- 1 root root        0 Jul  9 16:11 lock
drwx------ 2 **_apt** root     4096 Jul  9 16:14 partial_

returning to the container with `--fakeroot` and changing the folder owner to `root`
let me build successfully.

`$ singularity shell --fakeroot --writable sandbox_chroot/`
`> chown -R root:root /var/lib/apt /var/cache/apt`
`> exit`
`$ singularity build --fakeroot new_simg.sif sandbox_chroot/`
`INFO:    Starting build...`
`INFO:    Creating SIF file...`
`INFO:    Build complete: news.sif`

## Workaround
The above brought me to play a little with the apt config and to add a pre %post 
in the definition file for my ubuntu/debian builds:

>BootStrap: docker
From: ubuntu:18.04
>
>%post
>**echo 'Dpkg::Post-Invoke {"/bin/chown -R root:root /var/lib/apt /var/cache/apt";};' > /etc/apt/apt.conf.d/singularity-chown**
  apt-get update
  apt-get -y install lsb-release

**$ singularity build --fakeroot --sandbox sandbox_chroot/ Singularity.def**
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:5b7339215d1d5f8e68622d584a224f60339f5bef41dbd74330d081e912f0cddd
Skipping fetch of repeat blob sha256:14ca88e9f6723ce82bc14b241cda8634f6d19677184691d086662641ab96fe68
Skipping fetch of repeat blob sha256:a31c3b1caad473a474d574283741f880e37c708cc06ee620d3e93fa602125ee0
Skipping fetch of repeat blob sha256:b054a26005b7f3b032577f811421fab5ec3b42ce45a4012dfa00cf6ed6191b0f
Copying config sha256:84c9d0762469176a58d9c54375a1e9a4dcdc0045e3e14e191d97bd12cd5b23a1
 2.42 KiB / 2.42 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Running post scriptlet
\+ echo Dpkg::Post-Invoke {"/bin/chown -R root:root /var/lib/apt /var/cache/apt";};
\+ apt-get update
...
INFO:    Creating sandbox directory...
INFO:    Build complete: sandbox_chroot/


That did the trick for me.

**Comment by cclerget** [comment]
Hi @Zohman , I think I understand what happens, job done in CLI part of build is running outside of the fakeroot context, then you got permission denied while build assembler attempt to set permissions/owner based on original files. Will look how to fix that

**Comment by Zohman** [comment]
Hi @cclerget , thanks.

**Comment by cclerget** [comment]
Hey @Zohman , can you give a try to https://github.com/sylabs/singularity/pull/3926 and check if that fix your issue ?

**Comment by Zohman** [comment]
> Hey @Zohman , can you give a try to #3926 and check if that fix your issue ?

looks good, thanks!
