### ISSUE TITLE
GPG & Debootstrap issue in Singularity 3.2.0

### ISSUE THREAD

**Issue by saidamirouche** [apptainer/singularity#3895]
## Version of Singularity:

singularity version 3.2.0

## My Problem with Singularity 3.2.0

Before i install singularity 3.2.0, i had the version 2.6.1 which i edited the debootstrap command line in the file _deffile-driver-debootstrap.sh_  by adding "--no-check-gpg" for the gpg signatures and that worked.

**N.B** The file i edited to add that option is : /usr/lib/x86_64-linux-gnu/singularity/bootstrap-scripts/deffile-driver-debootstrap.sh

But with the lastest version, i wonder how can i add that option to debootstrap ? because the file that i got to change for that doesnt exist in the version 3.2.0 

Best regards 

### Actual behavior
user@dsp:~/images_singularity$ sudo singularity build test_image.img calibre9-eole.def
INFO:    Starting build...
I: Retrieving InRelease 
I: Checking Release signature
E: Release signed by unknown key (key id 4C78260F4C4FA1E0)
FATAL:   While performing build: conveyor failed to get: While debootstrapping: exit status 1

**Comment by ikaneshiro** [comment]
Hey @saidamirouche I think there's two ways to solve your problem.

1. Edit this line to have `--no-check-gpg` https://github.com/sylabs/singularity/blob/master/internal/pkg/build/sources/conveyorPacker_debootstrap.go#L46 and recompile/install singularity with that change.

2. Find the key and add it to the keyring `debootstrap` uses. I _think_ you can use `apt-key` to add it to that keyring but I would need to look into this option more if you run into trouble.

**Comment by saidamirouche** [comment]
Hey thank you for your answer, and i'm sorry for the late answer, actually i did that in the source code of singularity but i would like to do it after installation,  even though i set --prefix in mconfig but im not able to find the directory where "conveyorPacker_debootstrap.go " is installed ,  by default where is it installed please?

Best regards

**Comment by ikaneshiro** [comment]
@saidamirouche `converyorPacker_debootstrap.go` is compiled into the singularity binary at build time. So there is no way to modify it's behavior post instillation in the manner you could with 2.x by modifying the scripts.

**Comment by saidamirouche** [comment]
ah okey, too bad, i would like to edit directly without compiling and installing it again and again after each modification but too bad, i have to do that, Thank you @ikaneshiro  for your explanations

**Comment by ikaneshiro** [comment]
If you are writing your own definition files, another option would be to use a `bootstrap: scratch` and then call `debootstrap` from the `%setup` section to bootstrap the file system with the flags you want. Here are some examples. I haven't this myself but I'm happy to help if you run into issues. Here's some examples that do it for alpine and busybox. Less complicated but its a start https://github.com/sylabs/singularity/tree/master/examples/scratch

**Comment by saidamirouche** [comment]
Thank you @ikaneshiro  i will try to figure out how to make it works, the idea i had was to set a variable _gpgkey_ in singularity.conf  and parse it in the file converyorPacker_debootstrap.go once installed. but i think its impossible since its compiled directly into the singularity binary in the build time.

Again thank you for all the explanations you gave me

**Comment by dtrudg** [comment]
I don't think we need to expose an option here unless this is a broad issue, and we don't won't to encourage bypassing key checks on debootstrap.

@saidamirouche - is there a reason why you cannot do an `apt-key adv --recv-keys --keyserver keyserver.ubuntu.com xxxxxxxxx` on your host (where xxxx is the key id, and you may wish to use a different keyserver).

The release you are using does appear to be signed:

```
E: Release signed by unknown key (key id 4C78260F4C4FA1E0)
```

**Comment by mestia** [comment]
`apt-key` .. will  not help, debootstrap is checking archive keyring.
Alternative solution to rebuilding singularity is to substitute /usr/sbin/debootstrap with a wrapper calling 
`/usr/sbin/debootstrap_orig --no-check-gpg "$@"` or providing alternative keyring  `--keyring` option

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@saidamirouche Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Singularity repo is now retired as the code base is now moved to Apptainer. We are closing all the old issues under the old Singularity repo. For further assistance please open a new issue under the new Apptainer repo. Thanks for your support.
