### ISSUE TITLE
Automate testing with CircleCI orbs

### ISSUE THREAD

**Issue by sushma-4** [apptainer/singularity#3898]
### Expected behavior

Using CircleCI orbs to automate testing and executing (commands/jobs) for our RCs or PRs?

**Comment by jscook2345** [comment]
Automate the generation of RC checklists using the changelog as a template

**Comment by vsoch** [comment]
If you guys are looking at Singularity Orbs, version 1.0.4 is the current recommended:
https://circleci.com/orbs/registry/orb/singularity/singularity?version=1.0.4

I was able to get cache (superficially working) with 1.0.5 in that the install to different subdirectories of Circle's home worked (and untarred without issue) however in actual runtime I'm hitting this issue https://github.com/sylabs/singularity/issues/1290#issuecomment-366002477 and I'm going to need to take version 1.0.5 down for further work. 1.0.4 works great but doesn't use any cache, however when you try to cache in places that aren't circle's home, you'll build the first time okay, and have permissions errors the second time around at extraction. if you guys have any ideas let me know, I'm still fussing around with it and hoping there is something we can do!
