### ISSUE TITLE
'pull' should be using context properly

### ISSUE THREAD

**Issue by WestleyK** [apptainer/singularity#3899]
### Version of Singularity:

```
3.3.0-rc.1.159.g1c07a9c0c
```

### Expected behavior

`context` should be used properly when pulling a container. If the user interupts the pull, Singularity should tell the server to cancel the download possess.

### Actual behavior

Does not exist yet.

<br>

**Comment by mem** [comment]
This is related to #3789, which is introducing a way to clean up an interrupted download, but it's doing that in such a way that is very specific to that case. The solution is to have the signal handler installed earlier in the program, and propagate a cancellation context as appropriate down to the HTTP client.

**Comment by WestleyK** [comment]
@sashayakovtseva, is this fixed by https://github.com/sylabs/singularity/pull/4179?

**Comment by sashayakovtseva** [comment]
No, it is still using TODO
https://github.com/sylabs/singularity/pull/4179/files#diff-1b3e82c021788b1761d186c7b249d2bdR263

**Comment by dtrudg** [comment]
Context is now bubbled down from a CLI top level signal handler with #5216
