### ISSUE TITLE
singularity bootstrap leave many mounts behind (rhel 6.7)

### ISSUE THREAD

**Issue by tin6150** [apptainer/singularity#390]
Greetings!

During my process of learning/testing Singularity, I did many singularity bootstrap.
Now I noticed that I have some 100+ mounts left behind.
I don't observe any negative effect yet.  Maybe the problem doesn't exist in newer OS, but I work in a dinosaur company so old OS it is (which is why we need Singularity!!)

> mount 
/dev on /var/singularity/mnt/final/dev type none (rw,bind)
/dev on /var/singularity/mnt/final/dev type none (rw,bind)
/dev on /var/singularity/mnt/final/dev type none (rw,bind)
proc on /var/singularity/mnt/final/proc type proc (rw)
sysfs on /var/singularity/mnt/final/sys type sysfs (rw)
/dev on /var/singularity/mnt/final/dev type none (rw,bind)
proc on /var/singularity/mnt/final/proc type proc (rw)
sysfs on /var/singularity/mnt/final/sys type sysfs (rw)
...

 > mount | grep sing | wc
    103     618    5867

> rpm -qa | grep release
redhat-release-workstation-6Workstation-6.7.0.3.el6.x86_64

using "singularity shell" to start the container repeatedly does not compound to this mount problem.

**Comment by gmkurtzer** [comment]
That is weird. You are using RedHat6? It should not be leaving any stale mounts around as all mounts exist within process specific NEWNS namespaces. I will spin up my RHEL6 based system and try to replicate. What version are you using? 

In the mean time, can you remove those with `sudo umount ...`? (I just want to make sure they are removable)

Thanks!

**Comment by tin6150** [comment]
You know, maybe they will go away after some longer idle time?
the mount counts has certainly gone down since I filed the bug report an hour ago.
sudo umount works, even though it display some errors

> mount | wc
     67     403    4457
> sudo umount /dev
umount: /var/singularity/mnt/final/dev: not found
> sudo umount /var/singularity/mnt/final/dev
umount: /var/singularity/mnt/final/dev: not found
> sudo umount /var/singularity/mnt/final/sys
umount: /var/singularity/mnt/final/sys: not found

apparently after the above, only one singularity mount was left: 

proc on /var/singularity/mnt/final/proc type proc (rw)

and since it was a workstation, i did probably a crazy thing, but it worked without negative consequence:

> sudo umount proc
umount: /var/singularity/mnt/final/proc: not found
umount: /proc: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))


no more singularity mounts left at this point

it is Red Hat 6.7 workstation, x86_64.

**Comment by gmkurtzer** [comment]
What version of Singularity?

**Comment by tin6150** [comment]
Oh :)
2.2
As in git checkout tags/2.2

**Comment by gmkurtzer** [comment]
Actually, I've been able to reproduce it on bootstrap in master too. I have a feeling it is a false alarm and it is RHEL6 being bad. If you don't mind, rerun the bootstrap command a few times and watch the mount count go up and check it against `/proc/mounts`. You will find that the entries only exist in `/etc/mtab` which is not the list of file systems currently mounted, but really only serves for a state of connivence. 

Tomorrow I will debug why bootstraping is creating an `/etc/mtab` entry.

Thanks!

**Comment by gmkurtzer** [comment]
Heya @tin6150, will you give master 68411dc a try and see if I got it fixed?

Thanks!

**Comment by tin6150** [comment]
awesome, it works indeed!  both mount and /etc/mtab are really clean now.
Thanks @gmkurtzer !

**Comment by gmkurtzer** [comment]
fantastic! Thanks!
