### ISSUE TITLE
singularity image-build: relocation error

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#3917]
## Version of Singularity:

singularity version 3.3.0-rc.1.69.gd94449480

### Expected behavior

```bash
$ sudo singularity build apache.sif Singularity
```
(container builds successfully)

### Actual behavior

Given this recipe:

```bash
Bootstrap: docker
From:httpd:2.4
%startscript
httpd-foreground

%post
echo "HELLO"
```

the build has a weird error:

```bash
$ sudo singularity build apache.sif Singularity 
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:f5d23c7fed465a9eb762fc4c3cccd551a05914aba42492ceb972497db4df38bf
Skipping fetch of repeat blob sha256:b083c5fd185bd3ca1156b8695d8b8952d1741c765efcec28e34b443ef4153833
Skipping fetch of repeat blob sha256:bf5100a89e7815158a8afa82b6dfe3bd78e6761f6cc7b48333ff8eeaffbb2ce4
Skipping fetch of repeat blob sha256:98f47fcaa52fe04baffe4e3018677123529f15e268869314e221af7c254f56b3
Skipping fetch of repeat blob sha256:f78c06068415a50d989b900a3ab223770291ed756a894d7d7f5ab1821f420a7b
Copying config sha256:272370c65fdc6a3c8b87dbf7ed9649e56185f24b55af545234cb9ed925845b41
 5.65 KiB / 5.65 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
singularity image-build: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
FATAL:   While performing build: while running engine: exit status 127
```

It goes away when I remove the `%post` section. But I really would like to add that section! :)

### Steps to reproduce behavior

 1. Save the file above to `Singularity`
 2. sudo singularity build apache.sif Singularity

**Comment by WestleyK** [comment]
Try `httpd:2.4.37`.

**Comment by WestleyK** [comment]
httpd:2.4.37 seems to use a older version of Debian, and does not have this problem. This seems to be the same issue as `ubuntu:18.10` and up.

**Comment by vsoch** [comment]
Holy cow I can't believe that worked! I think software is pretty robust but then I hit something like this... thanks for the quick resolution! I made a quick singularity-compose recipe for it, failed at what I was trying to do (without sudo) but at least it's something to look at :/ 

https://github.com/singularityhub/singularity-compose-examples/tree/master/apache-simple

Closing issue.
