### ISSUE TITLE
Inspection metadata no longer containers container size

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#3932]
Singularity 2.X versions used to provide the container size as part of metadata with the field `org.label-schema.build-size`, and this is no longer done. Is there a reason, or can it be added back? Thanks!

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by vsoch** [comment]
Yes if this is not done the size should be added back.

**Comment by vsoch** [comment]
Don't close stalebot, the contributors to this issue have responded and it's the maintainers that have not.

**Comment by pedroalvesbatista** [comment]
@vsoch Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by vsoch** [comment]
@pedroalvesbatista the inspect command is a singularity command, so you could reproduce. It's not something I can try some workaround to make it work, the image is not built with a label for size as it used to be. Here is an example to show it's still not there!

```bash
$ singularity inspect --json busybox_latest.sif 
{
	"data": {
		"attributes": {
			"labels": {
				"org.label-schema.build-arch": "amd64",
				"org.label-schema.build-date": "Thursday_15_July_2021_18:57:17_MDT",
				"org.label-schema.schema-version": "1.0",
				"org.label-schema.usage.singularity.deffile.bootstrap": "docker",
				"org.label-schema.usage.singularity.deffile.from": "busybox",
				"org.label-schema.usage.singularity.version": "3.6.0-rc.4+579-g32b74d3ac"
			}
		}
	},
	"type": "container"
}
```
This is a pretty straight forward implementation - just calculate the size of the sif and then add to the labels.

**Comment by vsoch** [comment]
Here is an image built from a recipe file from 2.6.1-vault

```bash
$ singularity inspect --json image.simg 
{
    "data": {
        "attributes": {
            "labels": {
                "org.label-schema.usage.singularity.deffile.bootstrap": "docker",
                "org.label-schema.usage.singularity.deffile": "Singularity",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.usage.singularity.deffile.from": "busybox",
                "org.label-schema.build-date": "Thu,_15_Jul_2021_19:01:46_-0600",
                "org.label-schema.usage.singularity.version": "2.6.1-vault/release-2.6.9103f0155",
                "org.label-schema.build-size": "40MB"
            }
        },
        "type": "container"
    }
}
```
Notice the last entry.

**Comment by vsoch** [comment]
Thank you for helping!

**Comment by pedroalvesbatista** [comment]
@vsoch Granted ! After we finish the issues triage, your suggestions will be tested and core maintainers decide how to put this in the next releases. Thankyou.

**Comment by kmuriki** [comment]
Pending issues from the old repo are copied to the new repo (https://github.com/apptainer/apptainer/issues/1392) and cleaned from the old, retired repo.
