### ISSUE TITLE
singularity build --fakeroot error

### ISSUE THREAD

**Issue by jeffcbecker** [apptainer/singularity#3936]
## Version of Singularity:

3.3.0-rc2

### Expected behavior

$ singularity build --fakeroot --sandbox lolcow lolcow.def
# singularity build output for sandbox

### Actual behavior

$ singularity build --fakeroot --sandbox lolcow lolcow.def
ERROR  : Failed to write to GID map: Operation not permitted

### Steps to reproduce behavior

See above.

**Comment by cclerget** [comment]
Hi @jeffcbecker , yes actually singularity doesn't use `newxidmap` binaries. I summarized possible action items here https://github.com/sylabs/singularity/issues/3891#issuecomment-511721512

**Comment by jeffcbecker** [comment]
Will a solution be implemented for the 3.3.0 release?

**Comment by cclerget** [comment]
@jeffcbecker Can you give a try with #3943 and let us know ? Thanks

**Comment by jeffcbecker** [comment]
Should I apply the corresponding commit patch to my 3.2.0-rc2 source tree, or just use top-of-tree of master branch?

**Comment by cclerget** [comment]
Master branch, I don't think patch will work with 3.2.0-rc2 :

```
git checkout -b cclerget-master-fakeroot-subxid master
git pull https://github.com/cclerget/singularity.git master-fakeroot-subxid
```

**Comment by jeffcbecker** [comment]
After building/installing I get:

jcbecker@hfe1 506$ singularity build -f -s lolcow lolcow.def 
FATAL:   could not use fakeroot: could not open /etc/subuid: open /etc/subuid: no such file or directory

What do I need to do (get/set uid/gid are installed)? Thanks

**Comment by jeffcbecker** [comment]
Looks like I need to configure subuid -reading man page now

**Comment by jeffcbecker** [comment]
Can you tell me what I need to put in /etc/subuid? Do I also need something in /etc/subgid?

**Comment by cclerget** [comment]
@jeffcbecker Let's assume that user is `foo`, to allocate a range of 65536 UID/GID you will need to add the following line for user `foo` in both `/etc/subuid` and `/etc/subgid` :

`foo:100000:65536`

You will also need to install the setuid binaries newuidmap/newgidmap, if you are on a RHEL/CentOS 7 system you have to compile/install them yourself :
```
git clone https://github.com/shadow-maint/shadow
cd shadow
./autogen.sh --prefix=/usr --enable-man; make && sudo make -C src install
```

**Comment by jeffcbecker** [comment]
After I created /etc/subuid, and /etc/subgid as you instructed....

$ id
uid=4828(jcbecker) gid=1125(css) groups=1125(css),...
$ singularity build -f -s lolcow lolcow.def 
FATAL:   could not use fakeroot: could not retrieve user with UID 1125: user: unknown userid 1125

Looks like it's mistaking my gid for uid? Do I need to put my group (css) in /etc/subgid?

**Comment by cclerget** [comment]
Ah bug spotted, thanks ! I updated the PR with the fix

**Comment by jeffcbecker** [comment]
I tried the following, and it failed. Should I be doing something else?

$ git pull https://github.com/cclerget/singularity.git master-fakeroot-subxid
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 50 (delta 33), reused 50 (delta 33), pack-reused 0
Unpacking objects: 100% (50/50), done.
From https://github.com/cclerget/singularity
 * branch                master-fakeroot-subxid -> FETCH_HEAD
Auto-merging internal/pkg/runtime/engines/singularity/prepare_linux.go
CONFLICT (content): Merge conflict in internal/pkg/runtime/engines/singularity/prepare_linux.go
Auto-merging internal/pkg/runtime/engines/fakeroot/engine_linux.go
CONFLICT (content): Merge conflict in internal/pkg/runtime/engines/fakeroot/engine_linux.go
Automatic merge failed; fix conflicts and then commit the result.

**Comment by cclerget** [comment]
not a git expert ... I would delete the local branch and re-pull

**Comment by jeffcbecker** [comment]
After re-pull/build/install some progress...

1$ singularity build -f -s lolcow lolcow.def 
newgidmap: write to gid_map failed: Operation not permitted
newuidmap: write to uid_map failed: Operation not permitted
ERROR  : Failed to set GID 0: Invalid argument

**Comment by cclerget** [comment]
At some point you need to authorize newuidmap/newgidmap execution with setuid, looks like the setuid bit is disabled by `nosuid` on partition, you end with the same issue as with singularity and setuid installation. Fakeroot requires privileges at some point to write into the `uid_map` and `gid_map` files in `/proc/pid`, this is the only step which requires privileges and that's not possible otherwise.

**Comment by jeffcbecker** [comment]
Actually, newuidmap/newgidmap are in /bin so suid is allowed. For some reason though, the suid bit is not set on newuidmap/newgidmap. I'll find out if I can set it.

**Comment by jeffcbecker** [comment]
typo - newuidmap/newgidmap are in /usr/bin

**Comment by jeffcbecker** [comment]
Unfortunately, our system administrator says that newuidmap/newgidmap permissions are set by our operating system (SuSE SLES 12) and he is not willing to change them. Also, he was not happy about modifying /etc/subuid, /etc/subgid on a per-user basis.

Do you have any other ideas, or do we have to wait for 3.4?

**Comment by cclerget** [comment]
No ideas, as fakeroot requires privileges for setup, the only possibilities are :
- a Singularity installation with setuid bit set
- install newuidmap/newgidmap with setuid bit set

So it's not possible to fix that without involving a setuid binary at some point

**Comment by cclerget** [comment]
Closing, feel free to re-open it if needed
