### ISSUE TITLE
no space left on /tmp, even when SINGULARITY_TEMPDIR is specified

### ISSUE THREAD

**Issue by marc1uk** [apptainer/singularity#3939]
## Version of Singularity:

singularity version 3.2.1-1.osg34.el7

### Expected behavior

Expect to open a shell, using temporary locations specified.

### Actual behavior

Container creation fails due apparently to a lack of available space in /tmp, which should not be used.

### Steps to reproduce behavior

With a small /tmp and a large image, I suppose:

```
SINGULARITY_TMPDIR=/my/large/loc1 SINGULARITY_TEMPDIR=/my/large/loc1 SINGULARITY_LOCALCACHEDIR=/my/large/loc2 SINGULARITY_CACHEDIR=/my/large/loc3 singularity --debug -vvv shell my_singularity_image.simg 
DEBUG   [U=51132,P=5640]   envStringNSlice()             Set tmpdir Value to: /my/large/loc1 
VERBOSE [U=51132,P=5640]   execStarter()                 User namespace requested, convert image my_singularity_image.simg to sandbox
INFO    [U=51132,P=5640]   execStarter()                 Convert SIF file to sandbox...
DEBUG   [U=51132,P=5640]   Init()                        Entering image format intializer
DEBUG   [U=51132,P=5640]   Init()                        Check for image format sif
FATAL   [U=51132,P=5640]   execStarter()                 while extracting my_singularity_image.simg: root filesystem extraction failed: failed to copy content in staging file: write /tmp/archive-101709114: no space left on device
```

**Comment by cclerget** [comment]
@marc1uk I think this is a typo error, try with `SINGULARITY_TMPDIR` not `SINGULARITY_TEMPDIR`

**Comment by marc1uk** [comment]
If you look closely, I actually set both. :slightly_smiling_face: I've occasionally seen TEMPDIR pop up so thought i'd cover my bases (i don't think all of those are necessary options for running either, but better to be safe, right?)

**Comment by cclerget** [comment]
Oops I missed it :). Ok this is a bug, will fix that, also as a workaround you can use `TMPDIR=/my/large/tmp`

**Comment by marc1uk** [comment]
Thanks @cclerget that would be great, and in the meantime it seems the workaround has also done the trick - at least insofar as I have a new error message now. :slightly_smiling_face: I'll open a new issue for that, and I'll leave you to close this issue as you see fit.
