### ISSUE TITLE
RFE: singularity config command

### ISSUE THREAD

**Issue by cclerget** [apptainer/singularity#3944]
Add a `singularity config` command for admin tasks in order to manage the various Singularity configuration files.

Proposal for:
- `singularity.conf`:
  ```
  singularity config global --set "directive_name" directive_value
  singularity config global --get "directive_name"
  ```

  For multi-values directives in `singularity.conf` like `bind path`:
  ```
  singularity config global --set "bind path" /etc/hosts
  singularity config global --set --remove "bind path" /etc/hosts
  ```

- fakeroot configuration:
  ```
  singularity config fakeroot --add user
  singularity config fakeroot --remove user
  singularity config fakeroot --disable user
  singularity config fakeroot --enable user
  ```

- basic network management:
  ```
  singularity config network --enable network_name
  singularity config network --disable network_name
  singularity config network --list
  singularity config network --list --disabled
  ```

- capability management:
  ```
  singularity capability -> singularity config capability
  ```

**Comment by DrDaveD** [comment]
This did not make it into the 3.4 release so please change the label.

**Comment by mem** [comment]
> This did not make it into the 3.4 release so please change the label.

Lacking a better place to talk about this, this is as good a place as any.

_My_ own understanding of this is that _labels_ identify the release to which this issue applies (other bug trackers will call this "found in version", "applicable version", etc). The _Milestone_ field is where you document the target milestone for resolution. The _Release_ field is where you document the target release for resolution or the release that should include this fix (in case something needs to be backported, for example).

If you think about it, it does not make sense to have the same information duplicated across the milestone field and the labels (likewise for release).

Also note that _milestone_ and _release_ are overlapping concepts but not the same thing.

Now... where's a good place to document this that doesn't sit too far away from the place where it's used? I mean, this could be added to the website somewhere, and nobody would find the information.

**Comment by jeffcbecker** [comment]
Will this be in the next release(3.4.1 perhaps)? When is that?

**Comment by DrDaveD** [comment]
It has not been decided yet but is being discussed in a thread on the new [singularity-devel@lbl.gov](https://groups.google.com/a/lbl.gov/forum/#!forum/singularity-devel) mailing list.

**Comment by jeffcbecker** [comment]
Did this make it into 3.4.1?

**Comment by dtrudg** [comment]
@jeffcbecker - no, this will be targeted for 3.5 - there was a decision not to add a new feature into a patch release.

**Comment by dtrudg** [comment]
`config global` is in from #4623
