### ISSUE TITLE
Cannot create hardlink in unprivileged sandbox build

### ISSUE THREAD

**Issue by marc1uk** [apptainer/singularity#3947]
## Version of Singularity:

singularity version 3.2.1-1.osg34.el7

### Expected behavior

My .sif is expanded into a sandbox directory for use with unprivileged singularity.

### Actual behavior

singularity --debug -vvv build --sandbox ./toolanalysis_beta_sandbox/ /annie/data/containers/toolanalysis_beta_05-07-19.simg
DEBUG   [U=51132,P=6766]   envStringNSlice()             Set tmpdir Value to: /annie/data/stemp
Build target already exists. Do you want to overwrite? [N/y] y
DEBUG   [U=51132,P=6766]   Init()                        Entering image format intializer
DEBUG   [U=51132,P=6766]   Init()                        Check for image format sif
DEBUG   [U=51132,P=6766]   NewBundle()                   Created temporary directory for bundle /annie/data/stemp/sbuild-737788780
INFO    [U=51132,P=6766]   Full()                        Starting build...
DEBUG   [U=51132,P=6766]   Init()                        Entering image format intializer
DEBUG   [U=51132,P=6766]   Init()                        Check for image format sif
DEBUG   [U=51132,P=6766]   GetLocalPacker()              Packing from SIF
DEBUG   [U=51132,P=6766]   Init()                        Entering image format intializer
DEBUG   [U=51132,P=6766]   Init()                        Check for image format sif
DEBUG   [U=51132,P=6766]   Full()                        Inserting Metadata
DEBUG   [U=51132,P=6766]   Full()                        Calling assembler
INFO    [U=51132,P=6766]   Assemble()                    Creating sandbox directory...
DEBUG   [U=51132,P=6766]   Assemble()                    Moving sandbox from /annie/data/stemp/sbuild-737788780/fs to ./toolanalysis_beta_sandbox/
DEBUG   [U=51132,P=6766]   cleanUp()                     Build bundle(s) cleaned: [/annie/data/stemp/sbuild-737788780]
FATAL   [U=51132,P=6766]   run()                         While performing build: Sandbox Assemble Failed: exit status 1: mv: cannot create hard link ‘./toolanalysis_beta_sandbox/usr/lib/gcc/x86_64-redhat-linux/4.8.2/include/stdint-gcc.h’ to ‘./toolanalysis_beta_sandbox/ToolAnalysis/ToolDAQ/configfiles/NeutSensitivityStudy’: Operation not permitted

### Steps to reproduce behavior

Build container with privileged singularity. Distribute to unprivileged host. Try to run.

......

As an aside, I'm trying to figure out the situation with unprivileged singularity use, and am a little confused about the default process. I believe unprivileged singularity can only use sandbox directories. I also believe I should be able to expand these from .sif files (but not .img files - https://github.com/sylabs/singularity/issues/3940), although i'm not certain  - does one need to make the sandbox directory with privileged singularity? The impression I got from https://github.com/sylabs/singularity/issues/2588#issuecomment-459120565 was that this conversion can be done unprivileged and would be done for the user behind the scenes by default when running unprivileged. i.e. singularity shell would just work, rather then the user being required to do a manual 2-stage build then run. Did I get the wrong impression?

**Comment by marc1uk** [comment]
Interestingly, the hardlink it seems to be trying to create:
```
‘./toolanalysis_beta_sandbox/usr/lib/gcc/x86_64-redhat-linux/4.8.2/include/stdint-gcc.h’ to ‘./toolanalysis_beta_sandbox/ToolAnalysis/ToolDAQ/configfiles/NeutSensitivityStudy’
```
isn't something that should exist... NeutSensitivityStudy should not contain a file stdint-gcc.h :confused:

**Comment by rherban** [comment]
@marc1uk do you have the ability to build this sandbox with sudo?  Per the docs, you can create sandboxes unprivileged, but there may be permission issues:
```
If you wanted to create a container within a writable directory (called a sandbox) you can do so with the --sandbox option. It’s possible to create a sandbox without root privileges, but to ensure proper file permissions it is recommended to do so as root.
```

Also, could you test building from the same filesystem with this command:
```
mkdir -p ./tmpbuild
SINGULARITY_TMPDIR=`pwd`/tmpbuild singularity --debug -vvv build --sandbox ./toolanalysis_beta_sandbox/ /annie/data/containers/toolanalysis_beta_05-07-19.simg
```
Moving a hard-linked file should copy if it's going to a different filesystem, but there might be something in the build process that isn't coping well with it.  

You are correct that an unprivileged Singularity (`allow setuid=no`) can only mount a sandbox format, since mounting an image file requires setuid.  Tagging @cclerget for his expertise as well.

**Comment by cclerget** [comment]
For unprivileged run Singularity can also take a SIF or pure squashfs image to unpack it on-the-fly to a temporary sandbox directory.

**Comment by marc1uk** [comment]
Sorry for the delay in replying. I'm merely a user and responses from the system administrators have been fairly slow. Ultimately it seems the user namespaces were not configured correctly, which was leading to the observed problem. After some updates from the sys admins (can't say more about what they were i'm afraid) I can indeed now build a sandbox with unprivileged singularity. 

I've had others, and continue to have problems, with unprivileged use, though, and perhaps one thing that could make the process simpler is more clear error messages? For example, would it be possible for Singularity to check it's privileges before trying to execute a command, and reporte the situation more clearly than via a failure to make a mysterious hardlink?

@rherban thanks for the suggestion, i had previously encountered issues with not enough space on /tmp so was actually already specifying SINGULARITY_TMPDIR (and TMPDIR, in fact - see issue #3939)
