### ISSUE TITLE
document return value of 10

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3955]
While reviewing the e2e pull tests, I noticed the following which @gvallee commented on here:

https://github.com/sylabs/singularity/pull/3942#discussion_r305502821

Could we document the use of the return value `10` somehow or replace it with a enum? I would like it to be easier to understand why the value `10` is returned. ex: Is there a special meaning for this somewhere else I don't know about?

Thanks!

**Comment by WestleyK** [comment]
Closing. https://github.com/sylabs/singularity/pull/4167 is merged.
