### ISSUE TITLE
unit test failure: FAIL: TestGetIDRangePath

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3957]
This was seen on opensuse leap 15.0 while testing another PR. Please let me know if you have an idea to try or need more information. Thanks!

Information about the system:
```
$ uname -a
Linux vagrant-openSUSE-Leap 4.12.14-lp150.12.67-default #1 SMP Tue Jul 9 08:18:26 UTC 2019 (b610084) x86_64 x86_64 x86_64 GNU/Linux
```

```
=== RUN   TestGetIDRangePath
--- FAIL: TestGetIDRangePath (0.00s)
    fakeroot_test.go:37: unexpected error for "temporary file, uid 1 (multiple good)": could not retrieve user with UID 1: user: unknown userid 1
FAIL
coverage: 75.9% of statements
FAIL    github.com/sylabs/singularity/internal/pkg/fakeroot     0.006s
```

**Comment by cclerget** [comment]
@jscook2345 Ok looks like there is no user with ID 1 in `/etc/passwd` by default

**Comment by jscook2345** [comment]
@cclerget That is correct. opensuse 15 did not have an `id` of `1` in `/etc/passwd`. Anything I can supply to help?

**Comment by cclerget** [comment]
@jscook2345 Yes can you paste `/etc/passwd` content, but not sure it will be portable across different OS, so I'm probably good to mock `user.GetPwUID`
