### ISSUE TITLE
Find a good way to deal with command arguments

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3964]
## Version of Singularity:

All

### Expected behavior

We now have a nice package to handle commands but handling arguments is still most of the time problematic. A natural way of handling arguments would be to use slices of strings. Unfortunately, when using slices in the context of commands arguments, we most of the time end up with an empty argument (when displaying the command, one could see two spaces together), which ultimately makes the command to fail.
As a work around, i am currently creating the list of arguments using a string, which i then split to pass the arguments to the command.

### Actual behavior

See above.

### Steps to reproduce behavior

Write here.

**Comment by dtrudg** [comment]
Not clear this is an issue any more, or exactly where it applies. We can open again if it is.
