### ISSUE TITLE
Write unit tests for pkg/util/crypt

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3971]
## Version of Singularity:

All.

### Expected behavior

Have a decent coverage for the `pkg/util/crypt` package.

### Actual behavior

No unit tests.

### Steps to reproduce behavior

N/A.

**Comment by gvallee** [comment]
I am not closing this issue since the unit test include a workaround to pass with CI. See issue #3983 for more details.

**Comment by dtrudg** [comment]
This is now tested in CI since CircleCI supported Ubuntu 20.04 so closing.
