### ISSUE TITLE
Figure out the correct configuration for CI to support encryption unit tests

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3983]
## Version of Singularity:

All.

### Expected behavior

CI should let us run unit tests for encryption/decryption.

### Actual behavior

At the moment, I am facing a lot of problem with the following error message: `--luks2-metadata-size: unknown option`. I included a workaround in the new unit test that is added in PR #3982 (`pkg/util/crypt/crypt_dev_test.go`)

I suspect this is a configuration problem, for instance, we do not have the correct version of `cryptsetup`.

Once we figure out the correct configuration, the workaround in the unit test must be removed.

### Steps to reproduce behavior

N/A.

**Comment by gvallee** [comment]
Based on what we discover here, we may want to update `mconfig` to do extra checks and fail early.

Update on 08/02: @mem had a very good point during the last meeting. In theory, this is *not* a build time check but a run time check. So upgrading `mconfig` will not solve the entire problem but could improve the situation until we find a fix.

**Comment by jscook2345** [comment]
@gvallee 

Our VM build image defaults to a `Ubuntu 14.04` image. We could try and use a `16.04` image instead, but that's about as new as it gets.

You can see we do not have a large choice between VM images: https://circleci.com/docs/2.0/configuration-reference/#available-machine-images

I imagine these tests could run in a docker container over a VM just fine, so perhaps that is an option as well?

**Comment by jscook2345** [comment]
@gvallee 

It looks like the feature was added to `2.1` according to the release notes

https://gitlab.com/cryptsetup/cryptsetup/blob/master/docs/v2.1.0-ReleaseNotes

`xenial64` has 1.6.6 by default. Obviously `trusty64` has an older version

https://packages.ubuntu.com/xenial/cryptsetup

**Comment by jscook2345** [comment]
`cryptsetup` is not part of the backports it appears.

https://packages.ubuntu.com/xenial-backports/allpackages

**Comment by gvallee** [comment]
@jscook2345 Good notes and I have to admit that I am not sure of what are the requirements for the current implementation and future plans. I believe we need input from @schebro in order to precisely know what to do.

**Comment by gvallee** [comment]
This starts to be a blocker, using an empty file passes on the systems I use to run local tests while it fails with one of the configurations Travis is testing:
```
--- FAIL: TestEncrypt (14.47s)
2436    --- FAIL: TestEncrypt/empty_file (14.45s)
2437        crypt_dev_test.go:120: test empty file expected to fail but succeeded
2438FAIL
```

**Comment by gvallee** [comment]
So far I identified the following problems:
- [ ] encrypting an empty file will succeed on some platforms, fail on others. For example, it always succeeds on my systems but fail for some configurations used by Travis
- [ ] encrypting will return the following error (Travis triggers that error): `--luks2-metadata-size: unknown option`
- [ ] encrypting will return the following error (Travis triggers that error): `--type: unknown option`
- [ ] encrypting will return the following error (Travis triggers that error): `Unrecognized metadata device type luks2`

**Comment by schebro** [comment]
> @jscook2345 Good notes and I have to admit that I am not sure of what are the requirements for the current implementation and future plans. I believe we need input from @schebro in order to precisely know what to do.

In the meeting yesterday, it was mentioned that CI is currently at 16.04 Ubuntu, which still doesn'
t have the right version of cryptsetup to support luks2 option. Is it possible to selectively update cryptsetup on CI to 2.1.0, present in Ubuntu Disco?

**Comment by gvallee** [comment]
That is good point which I cannot really answer personally but it does address the fact that the error message is unclear if the wrong version of the package is available. I think that aspect should also be fixed.

**Comment by gvallee** [comment]
fyi, I just checked and CentOS 6 does not officially provide luks2 so even if it is possible to upgrade the package, I think it is also necessary to gracefully fail if it is not available.
Also, I only did a quick search and did not find a package for an upgrade.

**Comment by gvallee** [comment]
@schebro let me try to give a little more details on the graceful failure. A good illustration of the current problem is captured in the unit test: https://github.com/sylabs/singularity/blob/556223448bd428a9ceb024833e6a22d0f7bc7422/pkg/util/crypt/crypt_dev_test.go#L113

To address this, I think a good way would be that `EncryptFileSystem()` to return a pre-defined error showing that the library that is used is incompatible. For example something like:
```
devPath, err := dev.EncryptFilesystem(tt.path, tt.key)
if err != nil && err == IncompatibleLuksVersionErr {
  // the version of luks available on the system is not compatible with the encryption capability
  t.Skip()
}

if tt.shallPass && err != nil {
  // this is an actual error
}
```

This assumes that the code will define a new error and capture when a wrong version of the library is used. To capture when a wrong version of Luks is used, an easy first step is, I think, to move the parsing of the message in case of an error directly into `crypt_dev.go`.

**Comment by gvallee** [comment]
E2E related issues for which a test specific to encryption will be required at some point (all may not need to be addressed right away):
#4079 
#4083 
#4094 
#4097 
#4100

**Comment by dtrudg** [comment]
Now good with the Ubuntu 20.04 CI VM
