### ISSUE TITLE
bashrc doesn't work in ubuntu container

### ISSUE THREAD

**Issue by thw1021** [apptainer/singularity#3992]
## Version of Singularity:

3.3.0

### Problems

When run `sudo singularity shell --writable ubuntu/` to get into ubuntu container, it cannot load the path variables I set in `.bashrc`

### Steps to reproduce behavior
```
singularity pull library://library/default/ubuntu:18.04
sudo singularity build --sandbox ubuntu/ ubuntu_18.04.sif
sudo singularity shell --writable ubuntu/
```
Then I installed some softwares and set path variables in `.bashrc` . I `exit` and run `sudo singularity shell --writable ubuntu/` again, but it doesn't work.
For example, I installed `python3` and set `alias python=python3` in `.bashrc`. When I run `python`, I get 
```
Singularity ubuntu:~> python
bash: python: command not found
```
I did search for the solution, but none worked.

I can run `source ~/.bashrc` to solve this, but it is not convenient and I am not sure whether it could run properly after I build the image.

Any suggestion would be grateful.
Best.

**Comment by cclerget** [comment]
Hi @thw1021 , as you run it with sudo it searches `.bashrc` in `/root` directory inside container, to workaround that you can do : `sudo singularity shell --writable --home $HOME:/root ubuntu`

EDIT: to force load of `.bashrc` you will need to run like this :

`sudo singularity shell --writable --home $HOME:/root --shell /bin/bash ubuntu`

**Comment by thw1021** [comment]
@cclerget 
Thanks for your suggestions. I will try it.

But I felt a little confused. I run it with `sudo` following the [user guide](https://sylabs.io/guides/3.3/user-guide/quick_start.html). I want to install some packages and a software, and then build a image. If there are something wrong with my workflow, please tell me.

**Comment by cclerget** [comment]
@thw1021 Ok I think your best bet is to use definition files to create your image : https://sylabs.io/guides/3.3/user-guide/build_a_container.html#building-containers-from-singularity-definition-files

To avoid the tedious task of doing that manually.

**Comment by thw1021** [comment]
@cclerget 
Yes. Thank you. I am using the definition file.

Here is my definition file.
```
Bootstrap: docker
From: ubuntu:18.04
   
%post
    apt-get -y update
    apt-get -y upgrade
    apt-get -y install python3 python3-pip python-dev git build-essential autoconf openmpi-bin openmpi-common libopenmpi-dev m4 gfortran swig vim
    pip3 install mpi4py numpy scipy matplotlib
    git clone --depth=1 https://github.com/su2code/SU2
    cd SU2
    mkdir SU2_Install
    autoreconf -i
    ./bootstrap
    export CXXFLAGS="-O3 -Wall"
    python3 ./preconfigure.py --enable-autodiff --enable-mpi --with-cc=/usr/bin/mpicc --with-cxx=/usr/bin/mpicxx --prefix=$PWD/SU2_Install
    make -j 4 install
    make clean
    ./configure --prefix=$PWD/SU2_Install --enable-mpi --with-cc=/usr/bin/mpicc --with-cxx=/usr/bin/mpicxx --enable-PY_WRAPPER
    make -j 4 install
    cd ..
    pip3 install tensorforce[tf]
    git clone https://github.com/tensorforce/tensorforce.git
    cd tensorforce/
    git checkout major-revision-final
    pip3 install -e .
  
%runscript
    exec /SU2/bin/$1 $2   
```
When I do it manually, I met an error at the second `make -j 4 install`, which is related with the python environment. As you can see, I want to make python3 as the default python environment in the image, so that I may solve the problem conveniently.

The error happens again when I use the definition file:
```
swig -DHAVE_MPI  -Wall -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I/root/.local/lib/python2.7/site-packages/mpi4py/include -I/usr/local/lib/python2.7/dist-packages/mpi4py/include -I/Library/Python/2.7/site-packages/mpi4py/include -outdir ./ -o SU2_APIPYTHON_wrap.cxx -c++ -python /SU2/SU2_PY/pySU2/pySU2.i 
/SU2/SU2_PY/pySU2/pySU2.i:64: Error: Unable to find 'mpi4py/mpi4py.i'
Makefile:532: recipe for target 'SU2_APIPYTHON_wrap.cxx' failed
make[2]: *** [SU2_APIPYTHON_wrap.cxx] Error 1
make[2]: Leaving directory '/SU2/SU2_PY/pySU2'
Makefile:525: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/SU2/SU2_PY/pySU2'
Makefile:441: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```
Could you give me some suggestions, please ? I think the key is to set python3 as default python environment.

Best.

**Comment by cclerget** [comment]
Have you try to create a symlink from `/usr/bin/python -> /usr/bin/python3` ?

**Comment by thw1021** [comment]
@cclerget 
Do you mean adding `alias python=python3` in the definition file ? (Sorry I am not familiar with that.)
 
I add `alias python=python3` in `.bashrc` when I do it manually. As you can see in my previous comment https://github.com/sylabs/singularity/issues/3992#issue-472631686.  It doesn't work.

**Comment by thw1021** [comment]
@cclerget 
I tried your suggestion https://github.com/sylabs/singularity/issues/3992#issuecomment-515041406. Same error.
```
:~/singularity_su2_tensorforce$ sudo singularity shell --writable --home $HOME:/root ubuntu
Singularity ubuntu:~> cd ../home/
Singularity ubuntu:/home> ls
Anaconda3-2019.03-Linux-x86_64.sh  anaconda3
Singularity ubuntu:/home> python
bash: python: command not found
Singularity ubuntu:/home> exit
exit
```
It seems that the `/root` directory in the container was the `$HOME` directory of the host machine. I thought the container is a independent OS, it should use its own `.bashrc` (I am not sure whether I understand right).

Best.

**Comment by thw1021** [comment]
@cclerget 
Same error even if I add  `alias python=python3` in `%post` section of the definition file. Could you give me some suggestions, please ?

**Comment by thw1021** [comment]
`ln -s /usr/bin/python3 /usr/bin/python` works.

Thanks for your help @cclerget .

But still confused about my previous problems when I did it manually. I think the singularity container as an operating system. So it should work if I add something in `.bashrc`.

**Comment by cclerget** [comment]
@thw1021 Glad it works. I'm closing the issue, feel free to re-open issue if required
