### ISSUE TITLE
key export of an empty keyring creates an empty file

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3993]
## Version of Singularity:

v3.3.0 rc.3

### Expected behavior

```
$ ls pub.asc
ls: cannot access pub.asc: No such file or directory

$ singularity key export ./pub.asc
ERROR:   key export command failed: unable to open local keyring: open /home/vagrant/.singularity/sypgp/pgp-public: no such file or directory

$ ls pub.asc
ls: cannot access pub.asc: No such file or directory
```

### Actual behavior

```
$ ls pub.asc
ls: cannot access pub.asc: No such file or directory

$ singularity key export ./pub.asc
ERROR:   key export command failed: unable to open local keyring: open /home/vagrant/.singularity/sypgp/pgp-public: no such file or directory

$ ls pub.asc
pub.asc
```

- The exported file is empty.
- This does not occur when using the `--secret` flag.

**Comment by jscook2345** [comment]
@WestleyK 

Did a PR for this get merged into master? Is it broken in master?

**Comment by WestleyK** [comment]
Yeah, it looks like master could use a little fixing, the sypgp package has been refactored since 3.3, so the fix will be a little different.

**Comment by WestleyK** [comment]
Closing. This was fixed in master by https://github.com/sylabs/singularity/pull/4073. And not necessary for 3.3.
