### ISSUE TITLE
Clearly define the guidelines about where a package should be.

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3995]
## Version of Singularity:

All.

### Expected behavior

We should have clear guidelines to know where a given package should be places, i.e., in `internal/pkg/` or `pkg/`.

### Actual behavior

So far I have been asked to move packages one way or the other without any consistency; basically only based on who is reviewing PRs. This is not really sustainable and a lot of precious time is wasted since there is no way to anticipate what will be asked.
Based on this it would be extremely beneficial to clearly set some guidelines.

My understanding so far is the following:
- `pkg/` is designed to host all user-facing packages,
- `internal/pkg/` is designed to host all internal, i.e., not user-facing packages.

PR #3979 is a good example: the PR is about a new packages to handle the system configuration file for Singularity, not the user-level configuration file. In fact, normal users should *not* have access to that configuration file. I believe it should be in `internal/pkg`; others argue that it should be with `syfs` which deals with the Singularity files that are specific to a given user in order to keep the code related to all configuration files together.

### Steps to reproduce behavior

N/A.

**Comment by GodloveD** [comment]
afaik, the guiding principal should be thus:

"Do we expect package x to be useful to projects other than Singularity"?  

If the answer is "yes" it should go in `pkg/`.  If the answer is not yes (to include "meh" and "dunno") it should go in `internal/pkg/`.  

That is my understanding but I could be wrong.

**Comment by gvallee** [comment]
@cclerget added on PR #3979 which is a good point for the discussion:
```
The rule is pretty simple here, if the package use buildcfg constants, it's an internal package because it would be unusable as public package otherwise.

An other approach could be to add some get accessor in buildcfg package to have things like buildcfg.GetSingularityConfigFile()
```

**Comment by sashayakovtseva** [comment]
I agree with @GodloveD here.
