### ISSUE TITLE
singularity inspect returns "FATAL:   exit status 255: "

### ISSUE THREAD

**Issue by Flamefire** [apptainer/singularity#3996]
## Version of Singularity:

singularity version 3.2.1-1.el7a

### Expected behavior

Output of container metadata or meaningfull error message

### Actual behavior

Singularity prints `FATAL:   exit status 255: `, nothing more

### Steps to reproduce behavior

Run `singularity inspect <myimage.sif>` on a container.

Happens only for some containers build by users on our HPC cluster. On the same image I get `FATAL:   container creation failed: mount /proc/self/fd/12->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/12: failed to mount squashfs filesystem: invalid argument` so it might be a faulty image. But the non-existing inspect output makes it impossible to help them

**Comment by cclerget** [comment]
Hi @Flamefire , looks like the squashfs image was compressed with a compression algorithm not supported by kernel on your cluster. There is a pending PR #3801 to address issue with unprivileged installation, but will look how to fix this issue in this PR.

**Comment by Flamefire** [comment]
This sounds possible. Is there any way to find out which compression algorithm was used? Then I could check this.

In any way: Major complaint here is the missing error message for the inspect command. Also the other error message could be encapsulated in a more user-friendly message like "unable to mount filesystem from image <name.sif>" if that is where it fails.

**Comment by cclerget** [comment]
@Flamefire Can you give a try with https://github.com/sylabs/singularity/pull/4009 ?

**Comment by Flamefire** [comment]
I checked and nothing changed. Version shown `singularity version 3.3.0-rc.1.437.g16af50289` (after checking out the PR itself and recompiling)

**Comment by Flamefire** [comment]
Continued from https://github.com/sylabs/singularity/pull/4009#discussion_r307701743

- I checked `grep squashfs /proc/filesystems` locally and on the cluster and squashfs is available (although I had a weird failure on the cluster where it wasn't until I logged in again)
- I copied the image to my local machine and got the same failures
- I created an image locally and on cluster, and successfully started both on both machines
- I verified in `singularity -d shell image.sif` that `Mounting block [squashfs] image: /tmp/image.sif`occurs on both machines
- The failed fd (`/proc/self/fd/12`) is listed as `Check file descriptor /proc/self/fd/12 pointing to /tmp/image.sif`

**Comment by Flamefire** [comment]
Alright I probably found a bug in the error reporting:
- https://github.com/sylabs/singularity/blob/c5e243fc45fc5b55f315f7e39255cb95201d4f17/cmd/internal/cli/inspect_linux.go#L318 runs (basically) `singularity exec image.sif cat /.singularity.d/labels.json`
- https://github.com/sylabs/singularity/blob/c5e243fc45fc5b55f315f7e39255cb95201d4f17/cmd/internal/cli/inspect_linux.go#L320 is supposed to print a failure
- However https://github.com/sylabs/singularity/blob/c5e243fc45fc5b55f315f7e39255cb95201d4f17/cmd/internal/cli/inspect_linux.go#L429 already fatals out and `getFileContent` never returns the promised error (in the signature and calling code)
- This results in the very general message `exit status 255: ` (which was improved in master to `Unable to process command: exit status 255: `)
- But no stderr is included

Changing the `Output` call to `CombinedOutput` makes this slightly better: `FATAL:   Unable to process command: exit status 255: FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount squashfs filesystem: invalid argument`

**Comment by cclerget** [comment]
Thanks for the analysis @Flamefire , I flagged this issue to include required fix in #3801. Also will enhance error report when image mount failed in #4009

**Comment by Flamefire** [comment]
Anything else I can check? Could I do something like fschk on the image or so to validate the file format?

**Comment by cclerget** [comment]
Try :

`singularity build -s /tmp/sandbox /image/path`

or in raw mode if the above doesn't work :

`singularity siftool list /image/path`

You should get something like:

```
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-32800               |Def.FILE
2    |1       |NONE    |36864-36959               |JSON.Generic
3    |1       |NONE    |40960-2756608             |FS (Squashfs/*System/amd64)
```

Take FS entry and extract it with dd :

```
dd if=/image/path of=/tmp/crap bs=4096 skip=10
unsquashfs /tmp/crap
```

**Comment by Flamefire** [comment]
Nice tool (3.3+ though)! this helps

```
$ singularity -d build -s /tmp/sandbox ~/tmp.sif 
DEBUG   [U=1000,P=23130]   Init()                        Entering image format intializer
DEBUG   [U=1000,P=23130]   Init()                        Check for image format sif
DEBUG   [U=1000,P=23130]   NewBundle()                   Created temporary directory for bundle /tmp/sbuild-543796861
INFO    [U=1000,P=23130]   Full()                        Starting build...
DEBUG   [U=1000,P=23130]   Init()                        Entering image format intializer
DEBUG   [U=1000,P=23130]   Init()                        Check for image format sif
DEBUG   [U=1000,P=23130]   GetLocalPacker()              Packing from SIF
DEBUG   [U=1000,P=23130]   Init()                        Entering image format intializer
DEBUG   [U=1000,P=23130]   Init()                        Check for image format sif
ERROR   [U=1000,P=23130]   Pack()                        unpackSIF Failed: root filesystem extraction failed: extract command failed: exit status 1
DEBUG   [U=1000,P=23130]   cleanUp()                     Build bundle(s) cleaned: [/tmp/sbuild-543796861]
FATAL   [U=1000,P=23130]   run()                         While performing build: packer failed to pack: root filesystem extraction failed: extract command failed: exit status 1
```

Could use a better error message to, not only "exit status 1", doesn't it?

And 

```
$ unsquashfs /tmp/crap
Parallel unsquashfs: Using 4 processors
Read on filesystem failed because EOF
read_uids_guids: failed to read id index table
FATAL ERROR:failed to uid/gid table
```

Final validation:
```
$ singularity siftool list tmp.sif 
[...]
----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-35054               |Def.FILE
2    |1       |NONE    |36864-37533               |JSON.Generic
3    |1       |NONE    |40960-4762148864          |FS (Squashfs/*System/amd64)

$ls -l tmp.sif
-rwxr-xr-x 1 alex alex 4550950912 Jul 26 09:59 tmp.sif
```

This confirms my suspicion that the image is incomplete (damaged by copy?)

Suggestion: As it is manually possible to check the end SIF position vs the file size, could this be done in singularity?
