### ISSUE TITLE
Singularity cache clean doesn't work

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#4014]
## Version of Singularity:

3.3.0-rc.1.438.gc5e243fc4

### Expected behavior

`singularity cache clean` removes local cache.

### Actual behavior

Cache is not removed.

### Steps to reproduce behavior

```
rm -rf $HOME/.singularity/cache
singularity pull -U library://sashayakovtseva/test/image-server
ls -la $HOME/.singularity/cache/library
singularity cache clean
ls -la $HOME/.singularity/cache/library
```

**Comment by WestleyK** [comment]
This is the expected behavior, the cache does not get cleaned unless the user specifies the `-f` flag. Maybe the `-f` flag should be the default behavior? <- which was voted in slack.

**Comment by sashayakovtseva** [comment]
If that is the default behavior we should not output things like
```
vagrant@node-1:~$ singularity cache clean
Would remove /home/vagrant/.singularity/cache/library
Would remove /home/vagrant/.singularity/cache/oci-tmp
Would remove /home/vagrant/.singularity/cache/shub
Would remove /home/vagrant/.singularity/cache/oci
Would remove /home/vagrant/.singularity/cache/net
Would remove /home/vagrant/.singularity/cache/oras
```

That is *really*  misleading. I like how this is handled in kubectl
```
vagrant@node-1:~$ k delete
error: You must provide one or more resources by argument or filename.
Example resource specifications include:
   '-f rsrc.yaml'
   '--filename=rsrc.json'
   '<resource> <name>'
   '<resource>'
```

**Comment by sashayakovtseva** [comment]
Maybe it is better to add `--dry-run` flag instead of `--force`? And make force the default.
