### ISSUE TITLE
FATAL: container creation failed: mount /tmp failed: invalid argument

### ISSUE THREAD

**Issue by Zohman** [apptainer/singularity#4017]
## Version of Singularity:

3.3.0-rc.1.436

### Actual behavior

Hi, i see some sporadic failures which doesn't make sense, using same version
and host image in HPC, some builds faild with the title, some completed successfully,
also sometimes without any change to the host the same command suddenly works,
can't have point on something unusual but i suspect:

> DEBUG   [U=0,P=1]          Init()                        Entering image format intializer
DEBUG   [U=0,P=1]          Init()                        Check for image format sif
DEBUG   [U=0,P=1]          Init()                        sif format initializer returned: can't read first 2048 bytes: %!s(<nil>)
DEBUG   [U=0,P=1]          Init()                        Check for image format sandbox
DEBUG   [U=0,P=1]          Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=1]          Init()                        Check for image format squashfs
DEBUG   [U=0,P=1]          Init()                        squashfs format initializer returned: can't read first 2048 bytes: %!s(<nil>)
DEBUG   [U=0,P=1]          Init()                        Check for image format ext3
DEBUG   [U=0,P=1]          Init()                        ext3 format initializer returned: can't read first 2048 bytes: %!s(<nil>) <

but you may tell..

\$ **singularity build --disable-cache --fakeroot --sandbox simple_sandbox/ Singularity.def**
INFO:    Starting build...
FATAL:   container creation failed: mount /tmp failed: invalid argument
FATAL:   While performing build: while running engine: exit status 255

## Debug:
host1 \$ **singularity -d build --fakeroot --sandbox simple_sandbox/ Singularity.def**
>DEBUG   [U=1000,P=2689]createConfDir()               /homes/user/.singularity already exits. Not creating.
DEBUG   [U=0,P=1]          createConfDir()               /root/.singularity already exits. Not creating.
DEBUG   [U=0,P=1]          getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci-tmp
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/net
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/shub
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oras
DEBUG   [U=0,P=1]          Init()                        Entering image format intializer
DEBUG   [U=0,P=1]          Init()                        Check for image format sif
DEBUG   [U=0,P=1]          Init()                        sif format initializer returned: can't read first 2048 bytes: %!s(<nil>)
DEBUG   [U=0,P=1]          Init()                        Check for image format sandbox
DEBUG   [U=0,P=1]          Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=1]          Init()                        Check for image format squashfs
DEBUG   [U=0,P=1]          Init()                        squashfs format initializer returned: can't read first 2048 bytes: %!s(<nil>)
DEBUG   [U=0,P=1]          Init()                        Check for image format ext3
DEBUG   [U=0,P=1]          Init()                        ext3 format initializer returned: can't read first 2048 bytes: %!s(<nil>)
DEBUG   [U=0,P=1]          bundleCommon()                Created temporary directory for bundle /tmp/sbuild-186089652
INFO    [U=0,P=1]          Full()                        Starting build...
DEBUG   [U=0,P=1]          Get()                         Reference: ubuntu:18.04
Getting image source signatures
Skipping fetch of repeat blob sha256:7413c47ba209e555018c4be91101d017737f24b0c9d1f65339b97a4da98acb2a
Skipping fetch of repeat blob sha256:0fe7e7cbb2e88617d969efeeb3bd3125f7d309335c736a0525233ec2dc06aee1
Skipping fetch of repeat blob sha256:1d425c98234572d4221a1ac173162c4279f9fdde4726ec22ad3c399f59bb7503
Skipping fetch of repeat blob sha256:344da5c95cecd0f55238ce59b8469ee301056001ece2b769e9691b80f94f9f37
Copying config sha256:5f40de30a14521a4e532d4a73021d2efe54e26309406841f266a4ebf52508528
 2.42 KiB / 2.42 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
DEBUG   [U=0,P=1]          runBuildEngine()              Starting build engine
VERBOSE [U=0,P=37]         print()                       Set messagelevel to: 5
VERBOSE [U=0,P=37]         init()                        Starter initialization
DEBUG   [U=0,P=37]         get_pipe_exec_fd()            PIPE_EXEC_FD value: 7
VERBOSE [U=0,P=37]         is_suid()                     Check if we are running as setuid
DEBUG   [U=0,P=37]         init()                        Read engine configuration
DEBUG   [U=0,P=37]         init()                        Wait completion of stage1
DEBUG   [U=0,P=38]         set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=38]         init()                        Spawn stage 1
DEBUG   [U=0,P=38]         startup()                     imgbuild runtime engine selected
VERBOSE [U=0,P=38]         startup()                     Execute stage 1
DEBUG   [U=0,P=38]         StageOne()                    Entering stage 1
VERBOSE [U=0,P=37]         wait_child()                  stage 1 exited with status 0
DEBUG   [U=0,P=37]         cleanup_fd()                  Close file descriptor 4
DEBUG   [U=0,P=37]         init()                        Set child signal mask
DEBUG   [U=0,P=37]         init()                        Create socketpair for master communication channel
DEBUG   [U=0,P=37]         init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=0,P=37]         priv_escalate()               Get root privileges
VERBOSE [U=0,P=37]         priv_escalate()               Change filesystem uid to 0
VERBOSE [U=0,P=37]         init()                        Spawn master process
DEBUG   [U=0,P=45]         set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=45]         create_namespace()            Create mount namespace
VERBOSE [U=0,P=37]         enter_namespace()             Entering in mount namespace
DEBUG   [U=0,P=37]         enter_namespace()             Opening namespace file ns/mnt
VERBOSE [U=0,P=45]         create_namespace()            Create mount namespace
DEBUG   [U=0,P=46]         set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=46]         init()                        Spawn RPC server
DEBUG   [U=0,P=37]         startup()                     imgbuild runtime engine selected
VERBOSE [U=0,P=37]         startup()                     Execute master process
DEBUG   [U=0,P=46]         startup()                     imgbuild runtime engine selected
VERBOSE [U=0,P=46]         startup()                     Serve RPC requests
DEBUG   [U=0,P=37]         CreateContainer()             Mounting image directory /tmp/sbuild-186089652/fs
DEBUG   [U=0,P=37]         CreateContainer()             Mounting /tmp at /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session/tmp
FATAL   [U=0,P=37]         Master()                      container creation failed: mount /tmp failed: invalid argument
DEBUG   [U=0,P=1]          cleanUp()                     Build bundle(s) cleaned: [/tmp/sbuild-186089652]
FATAL   [U=0,P=1]          run()                         While performing build: while running engine: exit status 255<

### Expected behavior

working on other host:

host2 \$ **singularity -d build --fakeroot --sandbox simple_sandbox/ Singularity.def**
>DEBUG   [U=1000,P=5672]createConfDir()               /homes/user/.singularity already exits. Not creating.
DEBUG   [U=0,P=1]          createConfDir()               /root/.singularity already exits. Not creating.
DEBUG   [U=0,P=1]          getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci-tmp
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/net
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/shub
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oras
DEBUG   [U=0,P=1]          Init()                        Entering image format intializer
DEBUG   [U=0,P=1]          bundleCommon()                Created temporary directory for bundle /tmp/sbuild-157757059
INFO    [U=0,P=1]          Full()                        Starting build...
DEBUG   [U=0,P=1]          Get()                         Reference: ubuntu:18.04
Getting image source signatures
Skipping fetch of repeat blob sha256:7413c47ba209e555018c4be91101d017737f24b0c9d1f65339b97a4da98acb2a
Skipping fetch of repeat blob sha256:0fe7e7cbb2e88617d969efeeb3bd3125f7d309335c736a0525233ec2dc06aee1
Skipping fetch of repeat blob sha256:1d425c98234572d4221a1ac173162c4279f9fdde4726ec22ad3c399f59bb7503
Skipping fetch of repeat blob sha256:344da5c95cecd0f55238ce59b8469ee301056001ece2b769e9691b80f94f9f37
Copying config sha256:5f40de30a14521a4e532d4a73021d2efe54e26309406841f266a4ebf52508528
 2.42 KiB / 2.42 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
DEBUG   [U=0,P=1]          runBuildEngine()              Starting build engine
VERBOSE [U=0,P=26]         print()                       Set messagelevel to: 5
VERBOSE [U=0,P=26]         init()                        Starter initialization
DEBUG   [U=0,P=26]         get_pipe_exec_fd()            PIPE_EXEC_FD value: 7
VERBOSE [U=0,P=26]         is_suid()                     Check if we are running as setuid
DEBUG   [U=0,P=26]         init()                        Read engine configuration
DEBUG   [U=0,P=26]         init()                        Wait completion of stage1
DEBUG   [U=0,P=27]         set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=27]         init()                        Spawn stage 1
DEBUG   [U=0,P=27]         startup()                     imgbuild runtime engine selected
VERBOSE [U=0,P=27]         startup()                     Execute stage 1
DEBUG   [U=0,P=27]         StageOne()                    Entering stage 1
VERBOSE [U=0,P=26]         wait_child()                  stage 1 exited with status 0
DEBUG   [U=0,P=26]         cleanup_fd()                  Close file descriptor 4
DEBUG   [U=0,P=26]         init()                        Set child signal mask
DEBUG   [U=0,P=26]         init()                        Create socketpair for master communication channel
DEBUG   [U=0,P=26]         init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=0,P=26]         priv_escalate()               Get root privileges
VERBOSE [U=0,P=26]         priv_escalate()               Change filesystem uid to 0
VERBOSE [U=0,P=26]         init()                        Spawn master process
DEBUG   [U=0,P=34]         set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=34]         create_namespace()            Create mount namespace
VERBOSE [U=0,P=26]         enter_namespace()             Entering in mount namespace
DEBUG   [U=0,P=26]         enter_namespace()             Opening namespace file ns/mnt
VERBOSE [U=0,P=34]         create_namespace()            Create mount namespace
DEBUG   [U=0,P=35]         set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=35]         init()                        Spawn RPC server
DEBUG   [U=0,P=26]         startup()                     imgbuild runtime engine selected
VERBOSE [U=0,P=26]         startup()                     Execute master process
DEBUG   [U=0,P=26]         CreateContainer()             Mounting image directory /tmp/sbuild-157757059/fs
DEBUG   [U=0,P=35]         startup()                     imgbuild runtime engine selected
VERBOSE [U=0,P=35]         startup()                     Serve RPC requests
DEBUG   [U=0,P=26]         CreateContainer()             Mounting /tmp at /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session/tmp
DEBUG   [U=0,P=26]         CreateContainer()             Mounting /var/tmp at /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session/var/tmp
DEBUG   [U=0,P=26]         CreateContainer()             Copying files from host
DEBUG   [U=0,P=26]         CreateContainer()             Mounting /proc at /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session/proc
DEBUG   [U=0,P=26]         CreateContainer()             Mounting /sys at /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session/sys
DEBUG   [U=0,P=26]         CreateContainer()             Mounting /dev at /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session/dev
DEBUG   [U=0,P=26]         CreateContainer()             Mounting /etc/resolv.conf at /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session/etc/resolv.conf
DEBUG   [U=0,P=26]         CreateContainer()             Mounting /etc/hosts at /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session/etc/hosts
DEBUG   [U=0,P=26]         CreateContainer()             Chdir into /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session
DEBUG   [U=0,P=26]         CreateContainer()             Set RPC mount propagation flag to PRIVATE
DEBUG   [U=0,P=26]         CreateContainer()             Chroot into /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session
DEBUG   [U=0,P=35]         Chroot()                      Change current directory to /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session
DEBUG   [U=0,P=35]         Chroot()                      Hold reference to host / directory
DEBUG   [U=0,P=35]         Chroot()                      Called pivot_root on /opt/singularity/v3.3.0-rc.1-436-gfdf86b4/var/singularity/mnt/session
DEBUG   [U=0,P=35]         Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=35]         Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=35]         Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=35]         Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=0,P=26]         CreateContainer()             Chdir into / to avoid errors
VERBOSE [U=0,P=34]         wait_child()                  rpc server exited with status 0
DEBUG   [U=0,P=34]         apply_container_privileges()  Set user ID to 0
DEBUG   [U=0,P=34]         set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=34]         startup()                     imgbuild runtime engine selected
VERBOSE [U=0,P=34]         startup()                     Execute stage 2
DEBUG   [U=0,P=34]         StageTwo()                    Entering stage 2
VERBOSE [U=0,P=34]         SetContainerEnv()             Not forwarding SINGULARITY_ROOTFS from user to container environment
VERBOSE [U=0,P=34]         SetContainerEnv()             Not forwarding SINGULARITY_ENVIRONMENT from user to container environment
VERBOSE [U=0,P=34]         SetContainerEnv()             HOME = /root
INFO    [U=0,P=34]         runScriptSection()            Running post scriptlet
\+ apt update
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]           
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]        
Get:6 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [727 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [591 kB]      
Get:9 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [5436 B]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [4172 B]
Get:11 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1248 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [7235 B]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [10.8 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [901 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [3930 B]
Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2496 B]
Fetched 16.9 MB in 3s (6286 kB/s)                         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
DEBUG   [U=0,P=26]         Master()                      Child exited with exit status 0
DEBUG   [U=0,P=1]          Full()                        Inserting Metadata
DEBUG   [U=0,P=1]          Full()                        Calling assembler
INFO    [U=0,P=1]          Assemble()                    Creating sandbox directory...
DEBUG   [U=0,P=1]          Assemble()                    Moving sandbox from /tmp/sbuild-157757059/fs to simple_sandbox/
INFO    [U=0,P=1]          Full()                        Build complete: simple_sandbox/
DEBUG   [U=0,P=1]          cleanUp()                     Build bundle(s) cleaned: [/tmp/sbuild-157757059]<

### Steps to reproduce behavior ( at least on my end)
Singularity.def file:
`Bootstrap: docker`
`From: ubuntu:18.04`

`%post`
`  apt update`

$ singularity build --fakeroot --sandbox simple_sandbox/ Singularity.def

**Comment by Zohman** [comment]
key to note:

* after a reboot the problematic host was able to build it successfully..
but its coming back from time to time, can't tell the root cause.
i thought it may relate to user space, but when it happen the error is consistent to all users.

* if using root/sudo it always work.

**Comment by cclerget** [comment]
Hi @Zohman , is there a bind mount done in `/tmp` after some time ?

**Comment by cclerget** [comment]
@Zohman If you can give a try with https://github.com/sylabs/singularity/pull/4036 ? that would be great

**Comment by Zohman** [comment]
> Hi @Zohman , is there a bind mount done in `/tmp` after some time ?

not something i'm aware.. could be background service?

> @Zohman If you can give a try with #4036 ? that would be great

yes, applied that and now its working, hopefully for good, thanks. :)

**Comment by cclerget** [comment]
> not something i'm aware.. could be background service?

No idea but it's weird, now you confirmed it worked, this error was returned because there was a submount in `/tmp`

**Comment by Zohman** [comment]
> > not something i'm aware.. could be background service?
> 
> No idea but it's weird, now you confirmed it worked, this error was returned because there was a submount in `/tmp`

now that you mention it, i do have FUSE mounts from xrdp service inside **/tmp/.xrdp/**


`drwxrwsrwx  3 xrdp     xrdp   4096 Jul 28 11:37 .`
`drwxrwxrwt 18 root     root   4096 Jul 30 20:33 ..`
`d?????????  ? ?        ?         ?            ? user_xrdp_rd`
`-rw-------  1 user xrdp 135272 Jul 30 16:59 xrdp-chansrv.10.log`

\----------

`├─/tmp                                /dev/mapper/vg-tmp                                  ext4              rw,nosuid,nodev,relatime,data=ordered`
`  └─/tmp/.xrdp/user_xrdp_rd       xrdp-chansrv                                        fuse.xrdp-chansrv rw,nosuid,nodev,relatime,user_id=1000,group_id=2000`
