### ISSUE TITLE
Permission problem when building sandbox

### ISSUE THREAD

**Issue by jeffcbecker** [apptainer/singularity#4018]
## Version of Singularity:

3.3.0-rc4

### Expected behavior

$ singularity build --fakeroot --sandbox lolcow lolcow.def
$ # regular build output

### Actual behavior

After building the container, and trying to create sandbox, get several messages of the form:
mv: failed to preserve ownership for 'lolcow': Operation not permitted

### Steps to reproduce behavior

see above

**Comment by jeffcbecker** [comment]
Note the following builds correctly:

$ $ singularity build --fakeroot --sandbox lolcow/ library://sylabs-jms/testing/lolcow

**Comment by jscook2345** [comment]
@jeffcbecker 

What's in the definition file you're using, if you can share? This has been working for me during my testing of the RCs.

**Comment by jeffcbecker** [comment]
$ cat lolcow.def 
BootStrap: library
From: ubuntu:16.04

%post
    apt-get -y update
    apt-get -y install fortune cowsay lolcat

%environment
    export LC_ALL=C
    export PATH=/usr/games:$PATH

%runscript
    fortune | cowsay | lolcat

%labels
    Author GodloveD

**Comment by jeffcbecker** [comment]
More info:
Despite the mv error messages, the container works some..

$ singularity exec -w lolcow-new cowsay "It works!"
 ___________
< It works! >
 -----------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

But the following doesn't work:
$ singularity shell -w -f lolcow-new
Singularity lolcow-new:~> whoami
root
Singularity lolcow-new:~> apt-get update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease                        
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease                
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists... Done                     
W: chown to _apt:root of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
W: Can't drop privileges for downloading as file '/var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

Note this does work on the lolcow sandbox I created from library://sylabs-jms/testing/lolcow above

**Comment by jscook2345** [comment]
@jeffcbecker 

Does your issue look like the following, which should be fixed?

https://github.com/sylabs/singularity/issues/3892

If not, can you please supply the full debug output using:

`singularity --debug build ...` with your above definition file?

**Comment by jscook2345** [comment]
@jeffcbecker 

On the plus side, it looks like you helped us find a test case for an intermittent issue as well!

https://github.com/sylabs/singularity/issues/4038

Thanks so much! :)

**Comment by jeffcbecker** [comment]
@jscook2345 

Yes this issue is similar to #3892. If you want, I can send my debug output.

**Comment by rherban** [comment]
Since this appears to be fixed in #3892, I'm going to close this issue.  Happy to reopen if need be.

**Comment by jscook2345** [comment]
@jeffcbecker 

This appears to be fixed in `master`, so I will make sure this is fixed in 3.3.1 as well.

**Comment by jeffcbecker** [comment]
@jscook2345 

Thanks. I look forward to trying it out.
