### ISSUE TITLE
Check to see if token is valid before guiding the user through a new remote login

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#4020]
## Version of Singularity:

3.3.0-rc.1.436.gfdf86b487

### Problem

Running `singularity remote login` twice in a row produces exactly the same interactive workflow.  Through experimentation, I see that the token in the `remote.yaml` file is overwritten by the second call, but it's not clear to the user that the first token is being replaced by the second.  Maybe the second token will be added along with the first?  Maybe nothing will happen if a valid token already exists?  Maybe the two tokens will be appended to one another and everything will break?  Who knows??

### Solution

When the user executes `singularity remote login` Singularity should perform the following actions in order.  

1. Check to see if a token already exists in `remote.yaml`.  If it does **not** exist, then proceed with the interactive workflow as normal.  If a token **does** exist proceed to step 2. 
2. Check to see if the token is valid.  If it is **not** valid simply warn the user that you found a token but it's not valid for the remote and will be overwritten by the new token.  Then proceed with the interactive workflow as normal.  If the token **is** valid proceed to step 3.
3. Tell the user that they already have a valid token and ask them if they want to replace it with a different one (`[y/N]` prompt).  Of course if the user says `N` (or just hits enter) then terminate the workflow.  If the user answers `y`, then proceed with the workflow as normal.

**Comment by dtrudg** [comment]
The situation is now worse than described in `Problem` above. If you run `singularity remote login` when you are already logged in you will see:

```
11:03 AM $ singularity remote login
INFO:    Access Token Verified!
INFO:    Token stored in /home/dave/.singularity/remote.yaml
```

... the existing token is just checked, and rewritten to the file. This is not what a user would expect.
