### ISSUE TITLE
fails to map network port

### ISSUE THREAD

**Issue by mike-dubman** [apptainer/singularity#4028]
## Version of Singularity:

3.3.0-rc.3

### Expected behavior
```
sudo singularity instance start --net --network-args "portmap=8070:8080/tcp" --network-args "portmap=50000:50000/tcp" --writable-tmpfs $(APPNAME).sif $(APPNAME)
```
fails with

```
ERROR:   container cleanup failed: no instance found with name test
FATAL:   container creation failed: error while setting network arguments: can't convert host port '50000': strconv.ParseInt: parsing "50000": value out of range
```

changing 50000 to 8088 works.

### Actual behavior

works fine with docker when passing to the docker ```-p 50000:50000```

### Steps to reproduce behavior

```
sudo singularity instance start --net --network-args "portmap=8070:8080/tcp" --network-args "portmap=50000:50000/tcp" --writable-tmpfs $(APPNAME).sif $(APPNAME)
```

**Comment by jmstover** [comment]
@cclerget ... The `ParseInt()` call above is passing `16` as the bit size. This is a `int16` (not a `uint16`), so the max value ends up being 32767

Should change to `ParseUint()`, or change that from `16` to `32`. Changing to `ParseUint()` would be best IMO... since port numbers are a uint16.

```
FATAL:   container creation failed: can't convert host port '32768': strconv.ParseInt: parsing "32768": value out of range
```

**Comment by jmstover** [comment]
@mike-dubman ... PR #4029 should fix the issue you're seeing.
