### ISSUE TITLE
Have bash completion for exec of docker://-style URLs

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#403]
@vsoch asked about bash completion; I thought this would be a nifty little improvement that would demonstrate how to interact with the bash completion.

Basically, I think if we do something along these lines:
```
singularity exec docker://centos:<tab><tab>
```
then bash should lookup a listing of container labels under the `centos` account.  Basically, we'd need to write a script to do the query - and have it invoked by the bash completion script.

**Comment by vsoch** [comment]
I'd definitely down! The last time I checked, the endpoint that has the registry serve a catalog wasn't available, but I'll take a look again and see if that's changed. I could definitely make one for shub, although first I'd want to add a few more essential features... *gurgles back underwater...* heh

**Comment by vsoch** [comment]
oh just kidding, this is totally possible because we just need tags! I was thinking you wanted to search for repo_names as well. Yes I am totally down.

**Comment by gmkurtzer** [comment]
Whoa, being able to do tab completion on the Docker URI would be insanely sweet!

**Comment by dtrudg** [comment]
Closing - this has been stale for nearly four years without comment, so looks unlikely to be a strong need.
