### ISSUE TITLE
Test Port Assignment with --network-args

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#4032]
See PR #4029 and Issue #4028 

A test should be written that hits lower unpriv port (1024-5000), and then a larger port (just above 32767) just to be sure that a regression on PR #4029 doesn’t happen.

Test a constant failure using port 65540 as that's greater than uint16 max

```
# Succeed
sudo singularity instance start --net --network-args "portmap=4000:4000/tcp" --writable-tmpfs ./alpine.sif a
# Succeed
sudo singularity instance start --net --network-args "portmap=32770:32770/tcp" --writable-tmpfs ./alpine.sif a
# Fail
sudo singularity instance start --net --network-args "portmap=65540:65540/tcp" --writable-tmpfs ./alpine.sif a
```

**Comment by GodloveD** [comment]
Do you want to add that to your #4029 PR?

**Comment by jscook2345** [comment]
@GodloveD He added some unit-like tests in his PR. This is to evaluate if we need to add some e2e-like tests for this as well. Since he's not familiar with e2e I asked him to assign it to me.

**Comment by cclerget** [comment]
Covered by #4029
