### ISSUE TITLE
root permission on singularity.conf not sufficient

### ISSUE THREAD

**Issue by rsettlage** [apptainer/singularity#4044]
## Version of Singularity:
3.2.1 and 3.3.0-rc.4

### Expected behavior

chown root:root singularity.conf allows elevated privs

### Actual behavior

needed other root owned files, did not narrow it down to which ones

### Steps to reproduce behavior

Install Singularity as user, singularity shell to some container needing elevated privs (I was using docker://rocker/verse), get this error:
ERROR  : Can't open /proc/self/auxv: Permission denied

Repeat above after chown'ing singularity.conf and get same error

Repeat above after chown -R singularity_install_base_dir and see error go away.  May be an issue with needing to update the docs??

**Comment by rherban** [comment]
There are a number of permissions that need to be set for Singularity to run effectively, but an authoritative list is going to come from the Makefile or spec file (https://github.com/sylabs/singularity/blob/master/dist/rpm/singularity.spec.in).

I don't know of a list in our documentation detailing the permissions, but I'd suggest installing it with `./mconfig --prefix=/opt/singularity` and doing a normal `make && make install` rather than trying to do it by hand.

**Comment by jmstover** [comment]
> Install Singularity as user

You need to build with the `--without-suid` flag to `mconfig`. This will also force user namespace, so you need a kernel/system that supports user namespace.

Also, sandbox images are currently the only supported format for a non-suid workflow, as we need root privs to mount an image on a `/dev/loop` device.

**Comment by rsettlage** [comment]
Hi, yes, I basically did install it as suggested.  I am wanting to install this as a module on our system so that versioning will not require full sysadmin support:
```
module load go

VER=3.3.0

git clone https://github.com/sylabs/singularity.git
mv singularity singularity-$VER
cd singularity-$VER
git checkout v$VER-rc.4
./mconfig --prefix="%{INSTALL_DIR}"
make -C builddir
make -C builddir install DESTDIR="$RPM_BUILD_ROOT"
```

Ending there, I get the error listed above.  When I chown the singularity.conf file, the error persists.  When I then chown the entire install dir, it goes away.

**Comment by rsettlage** [comment]
I suppose I am not understanding this statement in the docs which is leading to my question: `When running in a privileged mode, the configuration file MUST be owned by root and thus the system administrator always has the final control.`

Again, what I am wanting to do is install Singularity as a module for general use.  Ideally, given internet access, users will be able to pull and build.  On compute nodes, users should be able to run.

**Comment by jscook2345** [comment]
@rsettlage 

With a regular install of `singularity`, that uses `set uid`, users can:
- Pull
- Run
- Build `sandboxes` only

If you want users to be able to build more than `sandboxes`, you can have them use the `--fakeroot` option. That's described in the user manual here:

https://sylabs.io/guides/3.3/user-guide/fakeroot.html

If you do not want your install of `singularity` to use `set uid`, you need to use the `--without-suid` option when you run `./mconfig`.

Does that help?
