### ISSUE TITLE
Overlay image corruption with multiple writable instances on same SIF

### ISSUE THREAD

**Issue by zao** [apptainer/singularity#4048]
## Version of Singularity:

3.3.0-rc4

### Expected behavior

Some sort of diagnostic or safeguard around mounting images multiple times.

### Actual behavior

I put an ext3 overlay filesystem into a `.sif` file and started two writable instances with `shell` and `exec`. I installed some software as root in one while the other one was active, `dmesg` spews warnings about deleted inodes and the filesystem is pretty much busted.

I'm guessing that it might be technically safe if all mounts are read-only.

### Steps to reproduce behavior

Reproduction steps approximate, reconstructing from history.

I'm not sure if this is how one is supposed to make an persistent overlay image at all, as it's quite underdocumented but this approach got it appearing to work for single instances.

Build image:
```bash
singularity pull docker://fedora:30
truncate -s 150G data.ext3
mkfs.ext3 data.ext3
singularity sif add --datatype 4 --groupid 1 --partarch 2 --partfs 2 --parttype 4 fedora_30.sif data.ext3
```

Concurrently - launch two instance and install a bunch of software from repos in the superuser one while building software in the other one.
```bash
singularity shell -e -w fedora_30.sif
sudo singularity shell -e -w fedora_30.sif
```

`blkid` on the host sees two loop devices, both appearing to be the image:
```
/dev/loop2: TYPE="squashfs"
/dev/loop3: UUID="0c055153-8bd5-4896-a96d-395289e91883" TYPE="ext3"
/dev/loop4: TYPE="squashfs"
/dev/loop5: UUID="0c055153-8bd5-4896-a96d-395289e91883" TYPE="ext3"
```

**Comment by zao** [comment]
The legitimate use cases I can see is "many readers" or "one writer", any other mix would be great if there was some locking or other exclusion mechanism (via SIF fields?) that would protect the user from themselves.

I realize in retrospect that what I did was extremely silly of course, but I was used to it working from having sandbox images before.

**Comment by cclerget** [comment]
Hi @zao , "advisory record locking" seems the way to go there but I expect weird/obscure issues with lock approach on shared/distributed filesystems, will submit an experimental PR for that

**Comment by cclerget** [comment]
@zao if you can give it a try https://github.com/sylabs/singularity/pull/4069

**Comment by zao** [comment]
With #4069 I have the following results:

Attempting to mount twice writable with two instances results in the following error message for the second instance:
`FATAL:   can't open /hp/zao/slask/sing-parts.sif for writing, already open by another process`

Mounting twice read-only works fine and lets me into the container on both instances.

Mounting writable first and then also read-only in another instance fails with the following message for the second instance:
`FATAL:   container creation failed: mount /proc/self/fd/3->/opt/singularity-pr4069/var/singularity/mnt/session/overlay-images/0 error: can't mount image /proc/self/fd/3: failed to mount ext3 filesystem: read-only file system`

Mounting read-only first and then also writable in another instance **unexpectedly succeeds**, which might surprise the read-only instance with changes to the filesystem.

**Comment by zao** [comment]
By the way, I have not tested whether this locking works on a cluster filesystem, just ZFS at home.

**Comment by cclerget** [comment]
@zao I updated the PR and addressed issues you encountered during testing. That would be great if you had a chance to give it another try. Thanks !

**Comment by zao** [comment]
@cclerget With the refreshed #4069 PR, all four scenarios work as I expect.
Read+Write, Write+Read, Write+Write => expected failure.
Read+Read => expected success.

I had a spurious fault when trying to run a read-only session while another was in progress but have not been able to reproduce it again:
`FATAL:   container creation failed: mount /proc/self/fd/3->/opt/singularity-pr4069b/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: failed to set loop flags on loop device: resource temporarily unavailable`

**Comment by cclerget** [comment]
Thanks for the feedbacks @zao  ! This error is unfortunately related to a regression introduced in loop kernel code few month ago see https://github.com/sylabs/singularity/issues/3860#issuecomment-509148497, the only workaround is to downgrade to a previous kernel version (or try an upgrade is they included the patch)
