### ISSUE TITLE
Improve error message when MirrorURL is incorrect

### ISSUE THREAD

**Issue by robertlugg** [apptainer/singularity#4056]
## Version of Singularity:
`3.1.0-rc2` (not confirmed on more recent version)

### Expected behavior

Given a recipe with an invalid MirrorURL such as:
```
Bootstrap: yum
# OSVersion: 7  #works
OSVersion: 7.1.1810  # fails
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum
```
, an error is generated which is hard to understand.  The request is to improve the error message.  Ideally substitute in the values for OSVERSION and basearch in the error message.

### Actual behavior

```
Failed to synchronize cache for repo 'base', ignoring this repo.
Error: Unable to find a match: /etc/redhat-release coreutils yum
FATAL:   While performing build: conveyor failed to get: While bootstrapping: exit status 1
```

### Steps to reproduce behavior

Build the above recipe.  The Actual behavior message will appear.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@robertlugg Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by robertlugg** [comment]
I haven't installed a recent version of Singularity in a while, so I'm not sure...it would need to be confirmed.

This request is to improve Singularity when the user makes a mistake.  Their recipe is invalid.  However, a great system will have clear, actionable messages to the user.  The current error message nowhere mentioned "OSVersion", which is the source of the problem.

**Comment by kmuriki** [comment]
Singularity repo is now retired as the code base is now moved to Apptainer. We are closing all the old issues under the old Singularity repo. For further assistance please open a new issue under the new Apptainer repo. Thanks for your support.
