### ISSUE TITLE
Add e2e tests for various singularity.conf values

### ISSUE THREAD

**Issue by cclerget** [apptainer/singularity#4061]
Add a test for each configuration directives in `singularity.conf`

**Comment by jscook2345** [comment]
I would start this as a checklist, and create issues for individual directives so other people can help you work through this (especially on ones that are more time consuming). Having one example to model after, however, would be good.

**Comment by cclerget** [comment]
@jscook2345 Ideally I would like to first implement https://github.com/sylabs/singularity/issues/3944 and proceed with tests after so it should be pretty easy to write tests
