### ISSUE TITLE
Add option to only cache image on a pull

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#4074]
I'm thinking of an option like `singularity pull --cache-only ...` that will allow a user to cache an image without needing to have it copied to a final location. This can be useful for multiple reasons, one being ensuring an image is cached before running a batch job that uses a particular image URI.

**Comment by GodloveD** [comment]
This has come up before, and I don't want to discourage it, but I don't see the use case.  For instance, in the case above, the user could just pull the container to a shared location (like `/tmp`) and then ensure that jobs run using `/tmp/foo` or something.  I'm not really sure how this simplifies the workflow.

**Comment by sashayakovtseva** [comment]
Agree with @GodloveD

**Comment by dtrudg** [comment]
Given the discussion on caching and race conditions that we can't escape on shared filesystems, I think we want to encourage pulling to a local file as a separate step.

If the image referred to by `docker://alpine` was to change between `singularity pull --cache-only` and `singularity run` then `singularity run` would go and pull the new version into the case and could fail with cache race conditions.

Given the recent discussions I'm also minded to close this. Do you have further thoughts @ikaneshiro ?

**Comment by ikaneshiro** [comment]
Nope, this makes sense to close to me.
