### ISSUE TITLE
[E2E] Implement test for all positive cases to improve coverage

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4078]
## Version of Singularity:

All.

### Expected behavior

All commands that are expected to succeed should be tested by the E2E framework.
The goal is to have a 100% coverage reported by the `cmd/docs/cmds` tool.

### Actual behavior

The following commands need to have a test (see separate issues for details):
- [ ] singularity build
- [x] singularity buildcfg
- [x] singularity cache
- [ ] singularity capability
- [ ] singularity exec
- [x] singularity help
- [ ] singularity inspect
- [ ] singularity instance
- [ ] singularity key
- [ ] singularity oci
- [ ] singularity plugin
- [ ] singularity pull
- [ ] singularity push
- [ ] singularity remote
- [ ] singularity run
- [ ] singularity run-help
- [ ] singularity search
- [ ] singularity shell
- [ ] singularity sif
- [ ] singularity sign
- [ ] singularity test
- [x] singularity verify
- [x] singularity version

### Steps to reproduce behavior

To get a report about coverage:
`cmd/docs/cmds -coverage -v`

**Comment by dtrudg** [comment]
Closing - this master issue is stale as commands have changed since it was opened and coverage was first examined, so it'd need a re-do to be accurate.

The sub-issues can be revised without re-doing from scratch.
