### ISSUE TITLE
[E2E] Improve coverage for build command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4079]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078 

### Actual behavior

- [ ] singularity build --arch
- [ ] singularity build --builder
- [ ] singularity build --detached
- [ ] singularity build --disable-cache
- [ ] singularity build --docker-login
- [ ] singularity build --docker-password
- [ ] singularity build --docker-username
- [ ] singularity build --encryption-key
- [ ] singularity build --fakeroot
- [ ] singularity build --json
- [ ] singularity build --library
- [ ] singularity build --no-cleanup
- [ ] singularity build --no-cleanup
- [ ] singularity build --nohttps
- [ ] singularity build --notest
- [ ] singularity build --remote
- [ ] singularity build --section
- [ ] singularity build --tmpdir
- [ ] singularity build --update

### Steps to reproduce behavior

N/A.

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
