### ISSUE TITLE
[E2E] Improve coverage for exec command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4083]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [ ] singularity exec --add-caps
- [ ] singularity exec --allow-setuid
- [ ] singularity exec --apply-cgroups
- [ ] singularity exec --cleanenv
- [ ] singularity exec --containall
- [ ] singularity exec --containlibs
- [ ] singularity exec --disable-cache
- [ ] singularity exec --dns
- [ ] singularity exec --docker-login
- [ ] singularity exec --docker-password
- [ ] singularity exec --docker-username
- [ ] singularity exec --drop-caps
- [ ] singularity exec --encryption-key
- [ ] singularity exec --fakeroot
- [ ] singularity exec --fusemount
- [ ] singularity exec --hostname
- [ ] singularity exec --ipc
- [ ] singularity exec --keep-privs
- [ ] singularity exec --net
- [ ] singularity exec --network
- [ ] singularity exec --network-args
- [ ] singularity exec --no-init
- [ ] singularity exec --no-nv
- [ ] singularity exec --no-privs
- [ ] singularity exec --nohttps
- [ ] singularity exec --nonet
- [ ] singularity exec --nv
- [ ] singularity exec --pid
- [ ] singularity exec --scratch
- [ ] singularity exec --security
- [ ] singularity exec --tmpdir
- [ ] singularity exec --uts
- [ ] singularity exec --vm
- [ ] singularity exec --vm-cpu
- [ ] singularity exec --vm-err
- [ ] singularity exec --vm-ip
- [ ] singularity exec --vm-ram
- [ ] singularity exec --writable
- [ ] singularity exec --writable-tmpfs

### Steps to reproduce behavior

N/A.

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
