### ISSUE TITLE
[E2E] Improve coverage for inspect command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4085]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [ ] singularity inspect --app
- [ ] singularity inspect --deffile
- [ ] singularity inspect --helpfile

### Steps to reproduce behavior

N/A.

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
