### ISSUE TITLE
[E2E] Improve coverage for instance command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4086]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [ ] singularity instance list --user
- [ ] singularity instance start --add-caps
- [ ] singularity instance start --allow-setuid
- [ ] singularity instance start --apply-cgroups
- [ ] singularity instance start --bind
- [ ] singularity instance start --boot
- [ ] singularity instance start --cleanenv
- [ ] singularity instance start --contain
- [ ] singularity instance start --containall
- [ ] singularity instance start --containlibs
- [ ] singularity instance start --disable-cache
- [ ] singularity instance start --dns
- [ ] singularity instance start --docker-login
- [ ] singularity instance start --docker-password
- [ ] singularity instance start --docker-username
- [ ] singularity instance start --drop-caps
- [ ] singularity instance start --fakeroot
- [ ] singularity instance start --fusemount
- [ ] singularity instance start --home
- [ ] singularity instance start --ipc
- [ ] singularity instance start --keep-privs
- [ ] singularity instance start --net
- [ ] singularity instance start --network
- [ ] singularity instance start --network-args
- [ ] singularity instance start --no-home
- [ ] singularity instance start --no-init
- [ ] singularity instance start --no-nv
- [ ] singularity instance start --no-privs
- [ ] singularity instance start --nohttps
- [ ] singularity instance start --nv
- [ ] singularity instance start --overlay
- [ ] singularity instance start --pid
- [ ] singularity instance start --scratch
- [ ] singularity instance start --security
- [ ] singularity instance start --tmpdir
- [ ] singularity instance start --userns
- [ ] singularity instance start --uts
- [ ] singularity instance start --workdir
- [ ] singularity instance start --writable
- [ ] singularity instance start --writable-tmpfs
- [ ] singularity instance stop --force
- [ ] singularity instance stop --signal
- [ ] singularity instance stop --timeout
- [ ] singularity instance stop --user

### Steps to reproduce behavior

N/A.

**Comment by gvallee** [comment]
Investigate why no encryption option is showing up (after #4241 and #4242 are merged).

**Comment by sashayakovtseva** [comment]
After #4320 is merged, also:

- [ ] singularity instance list <glob>
- [ ] singularity instance start --pid-file

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
