### ISSUE TITLE
[E2E] Improve coverage for key command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4087]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [x] singularity key export --armor
- [x] singularity key export --help
- [x] singularity key export --secret
- [x] singularity key import --help
- [x] singularity key list --help
- [x] singularity key list --secret
- [x] singularity key newpair --help
- [ ] singularity key newpair --new-password (pending https://github.com/sylabs/singularity/pull/4405)
- [x] singularity key newpair --bit-length (included in PR #4207)
- [x] singularity key pull --help
- [ ] singularity key pull --url
- [x] singularity key push --help
- [ ] singularity key push --url
- [x] singularity key remove --help
- [x] singularity key search --help
- [x] singularity key search --url
- [ ] singularity key search --long-list (included in PR #4121)

### Steps to reproduce behavior

N/A.

**Comment by gvallee** [comment]
I executed a coverage test on 2019/08/29 and `key pull --help`, `key push --help` and `key remove --help` are not reported as covered while tests are supposed to be present. This needs further investigation.

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
