### ISSUE TITLE
[E2E] Improve coverage for oci command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4088]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [x] singularity oci attach --help
- [ ] singularity oci create --bundle
- [ ] singularity oci create --empty-process
- [x] singularity oci create --help
- [ ] singularity oci create --log-format
- [ ] singularity oci create --log-path
- [ ] singularity oci create --pid-file
- [ ] singularity oci create --sync-socket
- [x] singularity oci delete --help
- [x] singularity oci exec --help
- [ ] singularity oci kill --force
- [x] singularity oci kill --help
- [ ] singularity oci kill --signal
- [ ] singularity oci kill --timeout
- [x] singularity oci mount --help
- [x] singularity oci pause --help
- [x] singularity oci resume --help
- [ ] singularity oci run --bundle
- [x] singularity oci run --help
- [ ] singularity oci run --log-format
- [ ] singularity oci run --log-path
- [ ] singularity oci run --pid-file
- [ ] singularity oci run --sync-socket
- [x] singularity oci start --help
- [ ] singularity oci state --help
- [ ] singularity oci state --sync-socket
- [x] singularity oci umount --help
- [ ] singularity oci update --from-file
- [x] singularity oci update --help

### Steps to reproduce behavior

N/A.

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
