### ISSUE TITLE
[E2E] Improve coverage for plugin command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4090]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [ ] singularity plugin compile --help
- [ ] singularity plugin compile --out
- [ ] singularity plugin disable --help
- [ ] singularity plugin enable --help
- [ ] singularity plugin inspect --help
- [ ] singularity plugin install --help
- [ ] singularity plugin install --name
- [ ] singularity plugin list --help
- [ ] singularity plugin uninstall --help

### Steps to reproduce behavior

N/A.

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
