### ISSUE TITLE
[E2E] Improve coverage for pull command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4091]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [ ] singularity pull --arch
- [x] singularity pull --disable-cache
- [ ] singularity pull --docker-login
- [ ] singularity pull --docker-password
- [ ] singularity pull --docker-username
- [ ] singularity pull --name
- [ ] singularity pull --no-cleanup
- [ ] singularity pull --nohttps
- [ ] singularity pull --tmpdir

### Steps to reproduce behavior

N/A.

**Comment by gvallee** [comment]
I need to fix #3987 first for that so I can check that the image is actually not cached during the pull.

**Comment by gvallee** [comment]
And I believe it will be better to first merge #3997 as it includes a new structure to define the context of a test that could be used to store the location of the image cache.

**Comment by gvallee** [comment]
I am working on the test for the `--disable-cache` option.

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
