### ISSUE TITLE
[E2E] Improve coverage for remote command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4093]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [ ] singularity remote add --global
- [x] singularity remote add --help
- [ ] singularity remote add --no-login
- [ ] singularity remote add --tokenfile
- [x] singularity remote list --help
- [x] singularity remote login --help
- [ ] singularity remote login --tokenfile
- [ ] singularity remote remove --global
- [x] singularity remote remove --help
- [x] singularity remote status --help
- [ ] singularity remote use --global
- [x] singularity remote use --help

### Steps to reproduce behavior

N/A.

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
