### ISSUE TITLE
[E2E] Improve coverage for run command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4094]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [ ] singularity run --add-caps
- [ ] singularity run --allow-setuid
- [ ] singularity run --apply-cgroups
- [ ] singularity run --cleanenv
- [ ] singularity run --contain
- [ ] singularity run --containall
- [ ] singularity run --containlibs
- [ ] singularity run --disable-cache
- [ ] singularity run --dns
- [ ] singularity run --docker-login
- [ ] singularity run --docker-password
- [ ] singularity run --docker-username
- [ ] singularity run --drop-caps
- [ ] singularity run --fakeroot
- [ ] singularity run --fusemount
- [ ] singularity run --home
- [ ] singularity run --hostname
- [ ] singularity run --ipc
- [ ] singularity run --keep-privs
- [ ] singularity run --net
- [ ] singularity run --network
- [ ] singularity run --network-args
- [ ] singularity run --no-home
- [ ] singularity run --no-init
- [ ] singularity run --no-nv
- [ ] singularity run --no-privs
- [ ] singularity run --nohttps
- [ ] singularity run --nonet
- [ ] singularity run --nv
- [ ] singularity run --overlay
- [ ] singularity run --pid
- [ ] singularity run --pwd
- [ ] singularity run --scratch
- [ ] singularity run --security
- [ ] singularity run --tmpdir
- [ ] singularity run --userns
- [ ] singularity run --uts
- [ ] singularity run --vm
- [ ] singularity run --vm-cpu
- [ ] singularity run --vm-err
- [ ] singularity run --vm-ram
- [ ] singularity run --workdir
- [ ] singularity run --writable
- [ ] singularity run --writable-tmpfs

### Steps to reproduce behavior

N/A.

**Comment by gvallee** [comment]
Also add a test for the following use cases since it is a problem that is important for some users and it currently seems to fail (from PR #4198):
```
$ mkdir /tmp/cache

$ export SINGULARITY_CACHEDIR=/tmp/cache

$ singularity run library://godlovedc/funny/lolcow
INFO:    Downloading library image
 _________________________________________
/ Let us endeavor so to live that when we \
| come to die even the undertaker will be |
| sorry.                                  |
|                                         |
| -- Mark Twain, "Pudd'nhead Wilson's     |
\ Calendar"                               /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

$ chmod 555 /tmp/cache

$ singularity run library://godlovedc/funny/lolcow
INFO:    Downloading library image
FATAL:   Unable to handle library://godlovedc/funny/lolcow uri: unable to download image: error opening file  for writing: open : no such file or directory
```

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
