### ISSUE TITLE
[E2E] Improve coverage for shell command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4097]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [ ] singularity shell --add-caps
- [ ] singularity shell --allow-setuid
- [ ] singularity shell --app
- [ ] singularity shell --apply-cgroups
- [ ] singularity shell --bind
- [ ] singularity shell --cleanenv
- [ ] singularity shell --contain
- [ ] singularity shell --containall
- [ ] singularity shell --containlibs
- [ ] singularity shell --disable-cache
- [ ] singularity shell --dns
- [ ] singularity shell --docker-login
- [ ] singularity shell --docker-password
- [ ] singularity shell --docker-username
- [ ] singularity shell --drop-caps
- [ ] singularity shell --passphrase
- [ ] singularity shell --pem-path
- [ ] singularity shell --fakeroot
- [ ] singularity shell --fusemount
- [ ] singularity shell --home
- [ ] singularity shell --hostname
- [ ] singularity shell --ipc
- [ ] singularity shell --keep-privs
- [ ] singularity shell --net
- [ ] singularity shell --network
- [ ] singularity shell --network-args
- [ ] singularity shell --no-home
- [ ] singularity shell --no-init
- [ ] singularity shell --no-nv
- [ ] singularity shell --no-privs
- [ ] singularity shell --nohttps
- [ ] singularity shell --nonet
- [ ] singularity shell --nv
- [ ] singularity shell --overlay
- [ ] singularity shell --pid
- [ ] singularity shell --pwd
- [ ] singularity shell --scratch
- [ ] singularity shell --security
- [ ] singularity shell --shell
- [ ] singularity shell --syos
- [ ] singularity shell --tmpdir
- [ ] singularity shell --userns
- [ ] singularity shell --uts
- [ ] singularity shell --vm
- [ ] singularity shell --vm-cpu
- [ ] singularity shell --vm-err
- [ ] singularity shell --vm-ram
- [ ] singularity shell --workdir
- [ ] singularity shell --writable
- [ ] singularity shell --writable-tmpfs

### Steps to reproduce behavior

N/A.

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
