### ISSUE TITLE
[E2E] Improve coverage for sif command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4098]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [ ] singularity sif add --alignment
- [ ] singularity sif add --datatype
- [ ] singularity sif add --filename
- [ ] singularity sif add --groupid
- [ ] singularity sif add --help
- [ ] singularity sif add --link
- [ ] singularity sif add --partarch
- [ ] singularity sif add --partfs
- [ ] singularity sif add --parttype
- [ ] singularity sif add --signentity
- [ ] singularity sif add --signhash
- [ ] singularity sif del --help
- [ ] singularity sif dump --help
- [ ] singularity sif header --help
- [ ] singularity sif info --help
- [ ] singularity sif list --help
- [ ] singularity sif new --help
- [ ] singularity sif setprim --help

### Steps to reproduce behavior

N/A.

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
