### ISSUE TITLE
installation issue on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by kellyrowland** [apptainer/singularity#41]
```
krowland@WARP-Drive:~/singularity$ sh ./autogen.sh 
+ autoreconf -i
configure.ac:32: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
+ [ -z  ]
+ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

This seems to be fixed by removing the `AC_PROG_LIBTOOL` line in `configure.ac`. I can PR that change in; I'm not sure if it requires more investigation.

**Comment by gmkurtzer** [comment]
If you do a "make maintainer-clean" with the unmodified configure.ac and run:

$ autoreconf -i -f

Does that work?

**Comment by kellyrowland** [comment]
With the most recent changes, I was able to run the autogen script with no issue. Thanks!

**Comment by soichih** [comment]
I just tried to install singularity on RHEL7 machine and I am getting a similar error message.

```
$ ./autogen.sh 
+autoreconf -i -f
configure.ac:32: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
+'[' -z '' ']'
+./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

I've installed shtool RPM, but still the same error. What must I do?

**\* Update ***

I tried the latest version from git and now I am seeing a slightly different error message.

```
$ ./autogen.sh 
+autoreconf -i -f
configure.ac:35: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:39: error: possibly undefined macro: AC_ENABLE_SHARED
autoreconf: /usr/bin/autoconf failed with exit status: 1

```

**Comment by bbockelm** [comment]
Hi Soichi,

The libtool macros are provided by the `libtool` RPM on RHEL7: can you verify you have that installed?

Brian

**Comment by soichih** [comment]
No, it was not installed, and after installing it I was able to compile it!

Thanks!
