### ISSUE TITLE
[E2E] Improve coverage for test command

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4100]
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [ ] singularity test --add-caps
- [ ] singularity test --allow-setuid
- [ ] singularity test --app
- [ ] singularity test --apply-cgroups
- [ ] singularity test --bind
- [ ] singularity test --cleanenv
- [ ] singularity test --contain
- [ ] singularity test --containall
- [ ] singularity test --containlibs
- [ ] singularity test --disable-cache
- [ ] singularity test --dns
- [ ] singularity test --docker-login
- [ ] singularity test --docker-password
- [ ] singularity test --docker-username
- [ ] singularity test --drop-caps
- [ ] singularity test --fakeroot
- [ ] singularity test --fusemount
- [ ] singularity test --home
- [ ] singularity test --hostname
- [ ] singularity test --ipc
- [ ] singularity test --keep-privs
- [ ] singularity test --net
- [ ] singularity test --network
- [ ] singularity test --network-args
- [ ] singularity test --no-home
- [ ] singularity test --no-init
- [ ] singularity test --no-nv
- [ ] singularity test --no-privs
- [ ] singularity test --nohttps
- [ ] singularity test --nonet
- [ ] singularity test --nv
- [ ] singularity test --overlay
- [ ] singularity test --pid
- [ ] singularity test --pwd
- [ ] singularity test --scratch
- [ ] singularity test --security
- [ ] singularity test --tmpdir
- [ ] singularity test --userns
- [ ] singularity test --uts
- [ ] singularity test --vm
- [ ] singularity test --vm-cpu
- [ ] singularity test --vm-err
- [ ] singularity test --vm-ram
- [ ] singularity test --workdir
- [ ] singularity test --writable
- [ ] singularity test --writable-tmpfs

### Steps to reproduce behavior

N/A.

**Comment by dtrudg** [comment]
Closing. These "[E2E] Improve Coverage" issues have not been maintained, and are out of date with respect to test improvements, and new flags / arguments.

#5830 is a task to remove redundancy from unit/integration <-> e2e and will revisit e2e coverage to an extent.
