### ISSUE TITLE
fake kernel version inside the container?

### ISSUE THREAD

**Issue by Zohman** [apptainer/singularity#4109]
Hi,

I have some problem pretty often with commercial tools that fail inside SLES11 / RHEL7 
containers due to non-supported kernel version where they check `uname -r` which return the
host kernel version and not the container OS old "known" kernel version.

A workaround i found working is to create a wrapper over the uname tool with a small regex
to manipulate its output.

Although i guess those tools heavily tested for their kernel requirement,
i know the kernel have a very strict policy to always maintain backward-compatibility
so i'm curious if possible to enable such feature natively in singularity as it help the "mobility"
such that if a user request **lower** kernel version than the actual host **higher** kernel
singularity will be able to fake it inside the container.

**Comment by cclerget** [comment]
Hi @Zohman , IMO this workaround must be added during image build time, if you are going to build an image with a proprietary/commercial software relying on a very kernel specific version, adding the workaround in definition file by swapping `uname` with your own seems the way to go and by doing that at image build time you also keep mobility as anywhere users will run the image `uname` will report the expected kernel version without involving another CLI option on Singularity side.
