### ISSUE TITLE
Reuse interrupt cleanup

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#4113]
Duplicates:
- https://github.com/sylabs/singularity/tree/master/cmd/internal/cli/pull.go:210
- https://github.com/sylabs/singularity/tree/master/internal/app/singularity/interrupt_cleanup.go:18 which is used in https://github.com/sylabs/singularity/tree/master/internal/app/singularity/pull.go:83

**Comment by dtrudg** [comment]
Has been tidied in cache rework.
