### ISSUE TITLE
Should the pulled unsigned image be removed? 

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#4114]

**Comment by WestleyK** [comment]
Do you mean to remove the cached image? Like https://github.com/sylabs/singularity/issues/3406?

**Comment by sashayakovtseva** [comment]
No, the image is actually pulled into a target location, and even when verification fails, it is left there.

**Comment by WestleyK** [comment]
Ohh, I get it. That would then force the users to use the `--allow-unsigned` if they want that container.

Yeah, thats definitely worth discussing, I'm open to that!

**Comment by sashayakovtseva** [comment]
IMO image should be removed both from dest and cache

**Comment by sashayakovtseva** [comment]
Closing due to #4124 and #4167
