### ISSUE TITLE
'signing' package should be non-interactive 

### ISSUE THREAD

**Issue by WestleyK** [apptainer/singularity#4116]
The `signing` package should be non-interactive.

Related to: https://github.com/sylabs/singularity/issues/4043

**Comment by sashayakovtseva** [comment]
I thought we agreed that I will fix that with #4043, didn't we?

**Comment by sashayakovtseva** [comment]
Duplicate of #4110

**Comment by WestleyK** [comment]
Right, I first thought it would be better to split it in two PRs, one for removing all the interactive code, and the other for improvements to the API, the `IsSigned()` etc...

I will unassigned everyone else from #4043 and assign you, so no one else will take your issues :smile:

**Comment by WestleyK** [comment]
Btw, #4110 is for the sypgp package, and this issue is for the signing package, very related, but still different packages.

**Comment by sashayakovtseva** [comment]
Oops, you are right :)

**Comment by dtrudg** [comment]
This was all refactored in the 3.6.0 sign/verify rework. The signing package no longer exists.
