### ISSUE TITLE
Inconsistent handling of configuration file paths

### ISSUE THREAD

**Issue by mem** [apptainer/singularity#4117]
## Version of Singularity:

3.3 (2a39c1fba60303bd40b5b8d3358e7290739431a8)

### Expected behavior

All the configuration files are handled in the same way.

### Actual behavior

Some paths to configuration files are recorded at build time and some are computed dynamically at runtime. Obtaining those paths is handled in different ways, too.

### Steps to reproduce behavior

Requires examining source code.

**Comment by gvallee** [comment]
This is ignoring #3995
