### ISSUE TITLE
3.3.0 adds hidden requirement of a writable home directory

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#4150]
## Version of Singularity:

3.3.0

### Expected behavior

To be able to continue to run singularity from an account without a writable home directory, as in previous versions.

### Actual behavior

If there's no home directory, first get an error like this:
```
FATAL: Error attempting to create /grid_home/cmsprod/.singularity: mkdir /grid_home/cmsprod/.singularity: no such file or directory
```

That was due to pr #3661 from @godloved.  That's easily worked around, by changing the fatal error into a debug message.  However, then there's another error:
```
FATAL:   failed to create an image cache handle: failed initializing caching directory: couldn't create cache directory /grid_home/cmsprod/.singularity/cache: mkdir /grid_home/cmsprod: permission denied
```
That is due to pr #3758 from @gvallee, and that is much more difficult to get around.  Making an image cache handle now seems to be very deeply embedded in the process beginning in actions.go.  However, there should fundamentally be no need to make an image cache when the image is a sandbox like we in the grid community almost always use.  I wouldn't think there would be a need with a .sif file either for that matter.

### Steps to reproduce behavior

Use an account that has no home directory or that is owned by someone else so there is no write access, and try to exec an image.

Attn:  @singularity-maintainers
This is a showstopper for me to get 3.3.0 released in EPEL.  I need a patch.

**Comment by gvallee** [comment]
Did you try to use the `SINGULARITY_DISABLE_CACHE` environment variable to disable the cache (set it to 1)?

**Comment by DrDaveD** [comment]
I wasn't aware of it.  It sounds like it could be a workaround, but I don't think it could be used as a permanent solution because we can't change every script that invokes singularity, and I wouldn't know when to set it in a singularity patch in such a way that it doesn't always disable the cache.

**Comment by gvallee** [comment]
@DrDaveD I am missing background here so I do not know how to help. I thought that Singularity always assumed that the image cache was active by default. It sounds like I was wrong. I am personally open to have a look at the sandbox case if I can have more details (just the error message is not enough). 

BTW, I found a problem with `SINGULARITY_DISABLE_CACHE` (issue #4189); and I added a test to make sure that the environment variable is correctly tested (PR #4188).

I see a few options here:
- We could also have a Singularity system configuration option to disable image caching on a given system. 
- We can update the cache mechanism to implicitly disable itself if the location where it is supposed to be created is not writable. This option would be very easy to implement once I am done with issue #4189

**Comment by DrDaveD** [comment]
@gvallee In version 3.2.1, you could use a sandbox image and run with an account that had no home directory, and it would succeed even though caching would work when you do something like pull an image from docker from an account that does have a home directory.   That's the behavior that we need to see preserved because on the science grids we always use sandbox images, and many system administrators deliberately do not create the home directories for the accounts that jobs are run from through batch queues.  They do that for security reasons, so the jobs cannot leave any customization behind or do something like manipulate $HOME/.ssh settings.   On the other hand the same distribution of singularity is used by other people that do have accounts with home directories and need to use the caching.

I'm not sure what more details I need to give you.  In an account that has a home directory, create a sandbox with `singularity build --sandbox centos7-sandbox docker://centos:7`, then from another account that has no home directory, try to do`singularity exec centos7-sandbox bash`.  The first command should show cached docker layers with `singularity cache list --all`, and the second command should work too, but instead with 3.3.0 it fails with the error shown above.  There's also no good reason why running a .sif image should require a home directory.

Does that make it any clearer?

**Comment by gvallee** [comment]
@DrDaveD yes it does help a lot, thanks! I have a solution in mind, I will write the code, create a PR, ask for you feedback and see if what I am about to do is acceptable to make it in.
I am also writing tests as I go to capture the requirements and make sure we won't break it in the future.

**Comment by gvallee** [comment]
@DrDaveD @GodloveD @jscook2345 @WestleyK PR #4198 is an implementation of what I have in mind that fixes the problem from a cache management point of view. But it makes assumptions about the semantics associated to image caches so please have a look (I tried to have a good description on the PR).

I also would like an approval from the 4 of you since it touches the default behavior of the image cache, as well as capturing and enforcing the requirements I came up with through an e2e test. Thanks!

**Comment by DrDaveD** [comment]
@gvallee Ok this is fixed in the master branch, can you please make a backport PR for the release-3.3 branch?

Even if 3.4.0 is ready soon, it may introduce new instabilities which would mean there will be value in having a 3.3.1.
