### ISSUE TITLE
singularity should not print color escapes to logs

### ISSUE THREAD

**Issue by EvanTheB** [apptainer/singularity#4161]
## Version of Singularity:

singularity --version
singularity version 3.0.2-1.el7.centos

### Expected behavior

when output is a tty, color printing is great. When output is anything else, singularity should not be printing terminal escape sequences. 

See programs like grep; --color[=WHEN] WHEN=never,always,auto default=auto.

This is almost certainly part of whatever colorise library you are using. 

### Actual behavior

singularity logs are full of garbage characters that make log parsing harder.

### Steps to reproduce behavior

```
$ singularity exec --bind fake:fake ./image echo test > stdout 2> stderr
$ less stderr
>garbage
```

**Comment by dtrudg** [comment]
Noting there is work ongoing here: https://github.com/sylabs/singularity/pull/2841

**Comment by EvanTheB** [comment]
It beggars belief that there is not a standard go logging library with normal colorise functionality. NIH?

**Comment by dtrudg** [comment]
@EvanTheB - I'm pretty confident this is not an not-invented-here issue. I'm less familiar than others with this area of the code, but I recall that there was a need to implement custom logging to retain the format / behavior of the older `2.x` Singularity C code base when migrating to Go for 3.0, and this is why there is a `sylog` here.
