### ISSUE TITLE
Consider warning if a filename is specified without pem:// for encryption keys

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4175]
## Version of Singularity:

master f0cd4b48

### Expected behavior

If a user mistakenly specifies a bare filename e.g. `mykey.pem` instead of `pem:///..../mykey.pem` in `SINGULARITY_ENCRYPTION_KEY` it should be clear to them the encryption was performed with the string `mykey.pem` used as a passhprase, not as a key file.

Something along the lines of...

```
WARNING - encrypting with a passphrase. If you intended to use a key file, prefix with pem://
```

### Actual behavior

If the `pem:///....` prefix is missed for `SINGULARITY_ENCRYPTION_KEY`, the intended filename is instead used as a passphrase to encrypt the container, and there is no warning/info that a passphrase is being used.

A user may try to verify the encryption by testing a `singularity run` with the same bare filename for `SINGULARITY_ENCRYPTION_KEY` - which will pass. This makes it fairly easy for an oversight to result in a container encrypted with a potentially weak passphrase to be circulated, rather than the intention of a strong keyfile based encryption.

### Steps to reproduce behavior

````
06:08 PM $ sudo SINGULARITY_ENCRYPTION_KEY=pair1_rsa.pub singularity build test.sif docker://alpine
[sudo] password for dave: 
Build target already exists. Do you want to overwrite? [N/y] y
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:0503825856099e6adb39c8297af09547f69684b7016b7f3680ed801aa310baaa
Copying config sha256:4fa153a82426ad308e69dde53d77abb1bbfb9d069bdfbdd7db50f615bd92d7ae
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: test.sif
```

**Comment by ikaneshiro** [comment]
Fixed by #4271 as there is now separate env vars and flags for keys and passphrases
