### ISSUE TITLE
Introduce a new env var for PK password

### ISSUE THREAD

**Issue by pisarukv** [apptainer/singularity#4186]
[Decrypt function](https://github.com/sylabs/singularity/blob/e24bc128e83eed75cfb23f116612654887444fd9/pkg/sypgp/sypgp.go#L518) expects a password to be entered from a user into stdin. It makes usage of singularity in automation scripts a bit difficult. [An example ](https://github.com/sylabs/wlm-operator/blob/af2d367b7080c95ea47b05cdcc86b44e77122064/.circleci/config.yml#L114) of hacks we need to push a sif into a library. 
I propose to introduce a new env var `SINGULARITY_PK_PASS` and check it inside [Decrypt function](https://github.com/sylabs/singularity/blob/e24bc128e83eed75cfb23f116612654887444fd9/pkg/sypgp/sypgp.go#L518) if env is presented, use it instead of asking a user to enter the pass.

**Comment by GodloveD** [comment]
@cali4888 is this still a problem?  In 3.4.0-rc.1 we check for the `SINGULARITY_ENCRYPTION_PASSPHRASE ` env var.  Does that do what you are looking for?

**Comment by pisarukv** [comment]
Seems like yes.
