### ISSUE TITLE
An image with mismatched checksum should be removed

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#4187]
Currently if an image will be pulled during man-in-the-middle attack we won't remove it, but simply display an error. I wonder whether we should remove that potentially viral image or this behavior is intended?

See [this line](https://github.com/sylabs/singularity/blob/master/internal/app/singularity/pull.go#L87).

**Comment by WestleyK** [comment]
Yes, this ~is~ _was_ the behavior added by https://github.com/sylabs/singularity/pull/3789. But those changes got lost in master (not for oras thought)... I will make a new PR adding back those changes.

**Comment by WestleyK** [comment]
@sashayakovtseva, Unless you just want to add those changes back through your PR https://github.com/sylabs/singularity/pull/4179?

**Comment by sashayakovtseva** [comment]
We don't want want to mix issues in a single PR, will make a separate one.

@WestleyK why you put release 3.4 label? Is it decided already to be there? 
Is it a bug?

**Comment by WestleyK** [comment]
> @WestleyK why you put release 3.4 label? Is it decided already to be there?

It should be. This is a _small_ fix and can easily make it into 3.4. Maybe not quite a bug, but defiantly should not be missed.

**Comment by sashayakovtseva** [comment]
okay, feel free to take this one :)
