### ISSUE TITLE
Encrypted Build Should Fail Early Without Root

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#4199]
## Version of Singularity:

`3.3.0-679.gc28fbdc63`

### Expected behavior

Building an encrypted container should fail early/obvious if not run as `root`.

```sh
$ SINGULARITY_ENCRYPTION_KEY=blah singularity build out.sif recipe.txt
FATAL:   You must be the root user to build an encrypted image.
```

### Actual behavior

Building an encrypted container without `root` doesn't necessarily fail until after the image is built, and the error message is unclear.

```sh
$ SINGULARITY_ENCRYPTION_KEY=blah singularity build out.sif in.sif
INFO:    Starting build...
INFO:    Creating SIF file...
FATAL:   While performing build: unable to encrypt filesystem at /tmp/sbuild-963107791/squashfs-436370547: failed to attach image /tmp/crypt-217953590: no loop devices available
```

### Steps to reproduce behavior

Grab an arbitrary SIF:

```sh
singularity pull in.sif alpine:latest
```
Attempt to encrypt it without `root`:

```sh
SINGULARITY_ENCRYPTION_KEY=blah singularity build out.sif in.sif
```

**Comment by WestleyK** [comment]
This seems to be fixed in 3.4. Reopen if not...
