### ISSUE TITLE
Running Encrypted Image without Key Material Should Fail in an Obvious Way

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#4200]
## Version of Singularity:

`3.3.0-679.gc28fbdc63`

### Expected behavior

Attempting to run an encrypted container without corresponding key material configured should fail in an obvious way:

```sh
$ singularity run out.sif
This image is encrypted, but you haven't supplied any key material.
```

### Actual behavior

Attempting to run an encrypted container without corresponding key material configured gives you a fairly opaque error message: 

```sh
$ singularity run out.sif
FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: unable to decrypt the file system: cryptsetup open failed: : <nil>
```

### Steps to reproduce behavior

Build an encrypted SIF:

```sh
sudo SINGULARITY_ENCRYPTION_KEY=blah singularity build out.sif library://alpine
```

Run it without key material set:

```sh
unset SINGULARITY_ENCRYPTION_KEY
singularity run out.sif
```

**Comment by pisarukv** [comment]
Already fixed in 3.4.0+
