### ISSUE TITLE
Is it possible to change ~/.singularity directory?

### ISSUE THREAD

**Issue by tashrifbillah** [apptainer/singularity#4202]
### Version of Singularity:

3.2.1-1.1.el7

### Actual behavior

> singularity pull library://tbillah/collection/fsl_tbss:0.0.0
```
INFO:    Downloading library image
 395.29 MiB / 4.96 GiB [===>-----------------------------------------------]   7.78% 8.55 MiB/s 08m54sFATAL:   
unable to Download Image: write /home/tb571/.singularity/cache/library
/sha256.58f1981b3b0830d2079f7f5310879cfe4fa3660db27d70df970bd22f7fec242c
/fsl_tbss_0.0.0.sif: no space left on device
```

I am working on a cluster environment and I know I don't have much space in my home directory. So, is there a way to change `~/.singularity` directory so the image is cached somewhere else during pulling?

I have already tried specifying an output file, yet the image is always being written in the cache directory during downloading:

> singularity pull /dev/fsl_tbss library://tbillah/collection/fsl_tbss:0.0.0

**Comment by tashrifbillah** [comment]
Doing an intensive search of the issues with various keywords, I found the following:

https://github.com/sylabs/singularity/issues/1052

Working on that, if successful, I shall close this issue.

**Comment by WestleyK** [comment]
@tashrifbillah, you could also try `--disable-cache`, like: `singularity pull --disable-cache library://tbillah/collection/fsl_tbss:0.0.0`. Using this flag, Singularity will write the image directly to the output file, without trying to cache it.

**Comment by tashrifbillah** [comment]
@WestleyK 

> you could also try `--disable-cache`, like: `singularity pull --disable-cache library://tbillah/collection/fsl_tbss:0.0.0`.

I just tried, but it appears that `--disable-cache` flag is absent. Try `singularity pull --help`.

**Comment by WestleyK** [comment]
@tashrifbillah, by bad, I forget your using 3.2, which does not have `--disable-cache`...
