### ISSUE TITLE
Singularity cannot build some official Docker Hub Ubuntu tags

### ISSUE THREAD

**Issue by kofalt** [apptainer/singularity#4203]
## Version of Singularity:

```
$ singularity --version
singularity version 3.3.0-1
```

### Expected behavior

The instructions for [Building containers from Singularity definition files](https://sylabs.io/guides/3.3/user-guide/build_a_container.html#building-containers-from-singularity-definition-files) should work with your average, official Ubuntu image off the Docker Hub.

### Actual behavior

Going off the list of [docker.io/ubuntu](https://hub.docker.com/_/ubuntu) top tags, there are mixed results:

| Tag    | Result   |
| ------ | -------- |
| 16.04  | Works    |
| 18.04  | Works    |
| 18.10  | Works    |
| 19.04  | **Failed** |
| 19.10  | **Failed** |
| latest | Works _(today, anyway)_    |

The failed tags result in this error before the post actions can be taken:

```
Storing signatures
singularity image-build: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
FATAL:   While performing build: while running engine: exit status 127
```

This seems very similar to the problem in #3917 but it is not clear to me how to more permanently resolve the issue.

### Steps to reproduce behavior

Using the following simple definition file:

```
Bootstrap: docker
From: ubuntu:19.10

%post
    apt update
    apt install -y python3

%environment
    export LANG=C.UTF-8
    export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

%runscript
   python3 --version
```

Run this command, editing the second line to try each tag in the table above:

```
singularity build result.sif reproduce.def

singularity run result.sif

rm -f result.sif
```

**Comment by cclerget** [comment]
@GodloveD I changed milestone to 3.3.1 as it was introduced in 3.3 release and it could be a blocker for many users
