### ISSUE TITLE
Fatal failure when running with no home directory

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4208]
All this has been reported with 3.3.0.

While trying to dig into the details of issue #4150, @DrDaveD was able to get a trace of a very reproducible failure in his configuration (see issue #4150 and PR #4198 for more details.

```
Ok by putting in debug statements including PrintStack() I found that "newfstatat" above is from line 250 of [this commit](https://github.com/sylabs/singularity/pull/3970/commits/40331a5b11185c1ed5a5e14305fdd8007a5f81c6#diff-60769b7cff9e6dae88716c3eab49b80fR250).  And shouldn't line 251 be statting m.rootPath + ovDir and setting path to that value?
```

_Originally posted by @DrDaveD in https://github.com/sylabs/singularity/pull/4198#issuecomment-521419132_

**Comment by gvallee** [comment]
I will try to reproduce the problem and see if we can write a test to capture these problems.

**Comment by gvallee** [comment]
To simplify the discussion, the link to the line identified as creating the problem is:
https://github.com/sylabs/singularity/pull/3970/commits/40331a5b11185c1ed5a5e14305fdd8007a5f81c6#diff-60769b7cff9e6dae88716c3eab49b80fR250

**Comment by cclerget** [comment]
@GodloveD As it's related to #4150 and it's a blocker as stated by @DrDaveD in https://github.com/sylabs/singularity/pull/4198#issuecomment-521419132, I changed milestone to 3.3.1

**Comment by GodloveD** [comment]
Heya @cclerget I switched it back to 3.4.0 milestone.  I'd like to keep it there for now just to make sure that we get everything that is needed into 3.4 before release.  We can switch it back to 3.3.1 for cherry-pick after it gets merged.  But we may not even do the point release now.  Seems like 3.4 will probably be ready before.
