### ISSUE TITLE
minimum requirement of /bin/sh

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#421]
While doing a 

` Docker export [ContainerName] | sudo singularity import /here/I/save/stuff/container.img`

It trow this error 

> ERROR: Container does not contain the valid minimum requirement of /bin/sh

I think if we the line 
```
 if [ ! -L "$SINGULARITY_ROOTFS/bin/sh" -a ! -x "$SINGULARITY_ROOTFS/bin/sh" ]; then
    message ERROR "Container does not contain the valid minimum requirement of /bin/sh\n"
```

Can be changed for 

```
 if [ ! -L "$SINGULARITY_ROOTFS/bin/sh" -a ! -x "$SINGULARITY_ROOTFS/bin/bash" ]; "
```

I would thake out the error

**Comment by vsoch** [comment]
Is there a particular reason you don't use the docker uri? Eg:

      sudo singularity import container.img docker://container:latest

**Comment by ArangoGutierrez** [comment]
It still trows the ERROR, because it is calling the 
>/usr/local/libexec/singularity/bootstrap/modules-v2/postbootstrap.sh

**Comment by gmkurtzer** [comment]
Hi @ArangoGutierrez, can you check to see if this is still an error in the current development branch?

Thanks!

**Comment by ArangoGutierrez** [comment]
Tested on the Development branch.
Closing the issue.
