### ISSUE TITLE
Finish up ROCm integration

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#4214]
@bauerm97 started integration with `ROCm` here: https://github.com/bauerm97/singularity/tree/ROCm-local-patch

It appears this work just needs to be looked over, brought up to date with a recent master, and reviewed.

**Comment by SimeonEhrig** [comment]
Is it still planned to finish this work? We would be happy about the function because we started with the delivery of our software via container and support different processor types (x86, Power, Nvidia GPU, AMD GPU).

**Comment by dtrudg** [comment]
Hello - I am taking on getting this merged into the `master` branch this week. Hope to have it available to use from there by the end of the week.

**Comment by SimeonEhrig** [comment]
Sounds like a plan :-)

**Comment by dtrudg** [comment]
If anyone here is able to test out the #4619 PR that would be much appreciated. Use `--rocm` to enable the ROCm support with the library binding. Thanks.

**Comment by SimeonEhrig** [comment]
I have two different systems for testing. I will try it the next few days.

**Comment by SimeonEhrig** [comment]
It works with the first system. I haven't tested it on the second system yet.

**Comment by dtrudg** [comment]
@SimeonEhrig - that's great to hear. Thanks for testing.

**Comment by SimeonEhrig** [comment]
The second system also works. It is a cleanly installed Linux Mint 19.2 with an Intel Skylake processor and a Vega 64. The requirements for ROCm are similar to CUDA. In addition to the correct singularity version, a compute driver is required on the host system. The instructions for the ROCk driver can be found [here](https://rocm-documentation.readthedocs.io/en/latest/Installation_Guide/Installation-Guide.html#ubuntu-support-installing-from-a-debian-repository).

**Comment by dtrudg** [comment]
Thanks @SimeonEhrig - I have tested on Ubuntu 18.04, and Debian 10 using the ROCm 2.9 packages with the dkms package (Ubuntu 18.04), and the buster-backport 5.2 kernel (Debian 10) for the driver.
