### ISSUE TITLE
pulling a public docker image requires auth

### ISSUE THREAD

**Issue by satra** [apptainer/singularity#4224]
## Version of Singularity:

$ singularity --version
singularity version 3.3.0

### Expected behavior

should be able to pull a public docker image without auth

### Actual behavior

$ export SINGULARITY_CACHEDIR=/dev/shm/$(whoami)
$ singularity pull docker://neuronets/kwyk:latest-cpu
WARN[0000] "/run/user/48529" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/48529: no such file or directory: Trying to pull image in the event that it is a public image. 
FATAL:   While making image from oci registry: failed to get checksum for docker://neuronets/kwyk:latest-cpu: unable to retrieve auth token: invalid username/password

the command works if i add `--docker-login` and actually login, but should not have to. 

more detailed output:

```
$ singularity --debug pull docker://neuronets/kwyk:latest-cpu
DEBUG   [U=48529,P=45152]  createConfDir()               /home/satra/.singularity already exits. Not creating.
DEBUG   [U=48529,P=45152]  updateCacheSubdir()           Caching directory set to /dev/shm/satra/cache/library
DEBUG   [U=48529,P=45152]  updateCacheSubdir()           Caching directory set to /dev/shm/satra/cache/oci-tmp
DEBUG   [U=48529,P=45152]  updateCacheSubdir()           Caching directory set to /dev/shm/satra/cache/oci
DEBUG   [U=48529,P=45152]  updateCacheSubdir()           Caching directory set to /dev/shm/satra/cache/net
DEBUG   [U=48529,P=45152]  updateCacheSubdir()           Caching directory set to /dev/shm/satra/cache/shub
DEBUG   [U=48529,P=45152]  updateCacheSubdir()           Caching directory set to /dev/shm/satra/cache/oras
DEBUG   [U=48529,P=45152]  parseURI()                    Parsing docker://neuronets/kwyk:latest-cpu into reference
WARN[0000] "/run/user/48529" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/48529: no such file or directory: Trying to pull image in the event that it is a public image. 
FATAL   [U=48529,P=45152]  pullRun()                     While making image from oci registry: failed to get checksum for docker://neuronets/kwyk:latest-cpu: unable to retrieve auth token: invalid username/password
```

**Comment by satra** [comment]
the issue was with my `.docker` folder.

**Comment by satra** [comment]
however, i don't see why or how singularity reads that folder. and perhaps if it does, the message could be improved for the end user.

**Comment by jscook2345** [comment]
@ikaneshiro 

@WestleyK 

Could we improve the warning / error here? Thanks!

**Comment by alaindomissy** [comment]
What was the issue with the .docker folder, and how did you fix it ? Thanks!

**Comment by satra** [comment]
@alaindomissy - i believe it was storing credentials. i simply nuked it, as i did not have a need for any docker credentials any more.

**Comment by dtrudg** [comment]
Singularity reads this folder as it uses the library: https://github.com/containers/image to ensure OCI/docker sources are handled correctly. This library is looking for docker's `~/.docker/config.json` which would contain credentials setup using `docker login`.

https://github.com/containers/image/blob/8ad47b442feae0a21bff51a6058227fa1e45bb41/docs/containers-transports.5.md#dockerdocker-reference

The error is declared in that library like this...
```
	ErrUnauthorizedForCredentials = errors.New("unable to retrieve auth token: invalid username/password")
```
... so we could check for it and provide a more complete explanation in the Singularity error message.

**Comment by uduse** [comment]
I am having the same problem. When I pull a docker image on GitHub packages with `singularity pull --docker-login` and manually type my username and GitHub token, singularity version 3.4.2 works fine, while singularity version 3.5.3-1.el7 gives me this error:

```
FATAL:   While pulling image from oci registry: failed to get checksum for
 //docker.pkg.github.com/uduse/katago/katago:mmcts-bias-utility-discount: while resolving reference: failed to do request: 
Head https://docker.pkg.github.com/v2/uduse/katago/katago/manifests/mmcts-bias-utility-discount: dial tcp 140.82.114.34:443: connect: connection refused
```

**Comment by dtrudg** [comment]
@uduse - please open a new issue as this one is against an older version of singularity than you are using and it's not the same issue - the original report is r.e. pulling an images that does not need `--docker-login` 

Please provide debug output with the `singularity -d` option to help diagnose.
