### ISSUE TITLE
INSTALL SUID should check that effective user is actually root

### ISSUE THREAD

**Issue by michaelkarlcoleman** [apptainer/singularity#4227]
## Version of Singularity:

3.3.0

### Expected behavior

If mistakenly using `make install` instead of `sudo make install` and setuid install is enabled, fail with a diagnostic.

### Actual behavior

It installs the setuid binary setuid to my build user, which is worse than useless.

### Steps to reproduce behavior

omit sudo

**Comment by michaelkarlcoleman** [comment]
Also, simply re-running with `sudo make install` does not appear to fix the ownership of the config files that have to be owned by root.

**Comment by sashayakovtseva** [comment]
@michaelkarlcoleman `make install` attempts to install singularity in `/usr/local/bin` by default. I wonder how are you able to install there without `sudo`.
Did you change default installation location?

**Comment by michaelkarlcoleman** [comment]
We're in an HPC environment and use Lmod to manage software, which means that we install pretty much everything into custom paths.  (This is likely true for a lot of Singularity users.)

**Comment by sashayakovtseva** [comment]
Got it, will work on fixing this issue.

**Comment by jscook2345** [comment]
@sashayakovtseva Can you add me (@jscook2345 ) as a reviewer when you have a PR ready? Thanks!

**Comment by michaelkarlcoleman** [comment]
On a related note, whatever you can easily do to reduce the window where "sudo root" is needed and/or be more chatty about what is being done with the root privilege would be welcome.  For example, it seems like I've seen patterns like this for some projects in the past:
```
make &&
make install &&
sudo make install-root
```

Thanks for your help!
