### ISSUE TITLE
Bootstrap should not be case sensitive

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#423]
This works:

      BootStrap: docker
      From: mongo:latest

but this doesn't:

      Bootstrap: docker
      From: mongo:latest

output:

      $ sudo singularity bootstrap tmp.img Singularity 
      ERROR  : Bootstrap definition file does not contain required Bootstrap: option
      ERROR  : Something went wrong during build module: Device or resource busy. 
      ERROR  : Container does not have a valid /bin/sh
      ABORT  : Retval = 255

I'm used to (not) having any kind of camel case for most things, so this will trip a lot of users up, methinks.

**Comment by gmkurtzer** [comment]
In progress already, see #416. Great minds.. :)

**Comment by bauerm97** [comment]
Fixed via #416 and closed.
