### ISSUE TITLE
Update mconfig to match go version in installation documentation

### ISSUE THREAD

**Issue by poidag-zz** [apptainer/singularity#4234]
## Version of Singularity:

Latest master

### Expected behavior

Following the installation guide 

### Actual behavior

Failure to compile. Expecting wrong version of golang

### Steps to reproduce behavior

Follow https://github.com/pickledrick/singularity/blob/master/INSTALL.md

**Comment by sashayakovtseva** [comment]
Should be reopened when reproduced, see #4235
