### ISSUE TITLE
Unable to launch multi_pyspin GUI error FATAL:  image targets amd64, cannot run on arm64  

### ISSUE THREAD

**Issue by lab1104** [apptainer/singularity#4239]
## Version of Singularity:
 3.3.0-736.g2e524b566

### Expected behavior:
my OS is Ubuntu18.04 aarch64.
Spinnaker version I am using is: spinnaker-1.23.0.27-arm64
Spinnaker_python: spinnaker_python-1.23.0.27-cp36-cp36m-linux_aarch64
I have successfully installed Singularity on my machine. but when I am executing command :+1: ./multi_pyspin.simg

Getting error:
FATAL:   image targets amd64, cannot run on arm64
Please advice

**Comment by GodloveD** [comment]
It sounds like the container that you are trying to run is built for a different architecture than your CPU.  This one seems to work:
```
$ singularity run docker://justinblaber/multi_pyspin
```
You might want to run it with the `--containall` flag or in a VM for safety until you have a good sense of what it is doing.

**Comment by lab1104** [comment]
I followed the following steps for insallation: 
1. sudo sh -c 'echo 16000 > /sys/module/usbcore/parameters/usbfs_memory_mb'
2.Installed dependencies:
 $ sudo apt-get update && sudo apt-get install -y \
    build-essential \
    libssl-dev \
    uuid-dev \
    libgpgme11-dev \
    squashfs-tools \
    libseccomp-dev \
    pkg-config
3. Installed Go
4. installed Singularity
5. compile Singularity:
./mconfig && \
    make -C ./builddir && \
    sudo make -C ./builddir install
6. $ ./mconfig --prefix=/opt/singularity
7. source basch completion file: . /usr/local/etc/bash_completion.d/singularity
8. Download singularity image:
mkdir -p ~/multi_pyspin
cd ~/multi_pyspin
singularity pull --name multi_pyspin.simg shub://justinblaber/multi_pyspin
9. run singularity image: ./multi_pyspin.simg
Expected: GUI should open
Error: image targets amd64, cannot run on arm64

@GodloveD : Also tried singularity run docker://justinblaber/multi_pyspin but same error.
please suggest.
Thanks

**Comment by GodloveD** [comment]
Oh, sorry.  I thought you were trying to run an arm container on amd64 arch.  Looks like it is the opposite.  You are trying to run and amd64 container on arm arch.  Is this what you are trying to do?  In this case, you will need to rebuild the container on a system with the correct arch.  Looks like the original author used docker to build and then just converted to Singularity.  I would translate their docker file into a def file (manually), pull from an arm base image and build on the arm host.  I know that's a lot, but it's about the best option you've got I think.  

Here's a [link to the dockerfile](https://hub.docker.com/r/justinblaber/multi_pyspin/dockerfile).  Maybe you could convince @justinblaber to help you out on this.  If you provide the hardware and he provides the def file, you could both get an arm version of multi_pyspin out of the deal!

**Comment by lab1104** [comment]
Thanks for the Help.
I am new to all this stuff. Could anyone can help me with step to step installation of Singularity. Is thr anyone who has installed it for Arm64.
Please help

**Comment by dtrudg** [comment]
@lab1104 - your Singularity install here is fine, you've done that okay. The issue is that the shub / docker images you are pulling are for AMD64 only, so they can't run on an ARM64 machine. As mentioned above you would have to start with a container built for AMD64 - maybe contacting the developer to see if they can help out with that.
