### ISSUE TITLE
Require -e flag to build encrypted containers

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#4241]
As the title says. This will make it clear that the build command is created an encrypted container. If we pick up env vars for for keys/passphrases, and this flag is not specified, we should give some kind of warning. Something that is not completely clear to me is if we should have this be required for `exec/shell/run` or if we should just act on envvars and other flags for those commands

**Comment by GodloveD** [comment]
>Something that is not completely clear to me is if we should have this be required for exec/shell/run or if we should just act on envvars and other flags for those commands
Singularity could probably just check for the existence of the appropriate SIF block to determine whether or not a container is encrypted.  In the case that it is encrypted it could try to get a passphrase or PEM file from the location, or a PEM file env var, or a passphrase env var in that order.  What do you think?

**Comment by ikaneshiro** [comment]
@GodloveD I agree with this flow. I think adding a flag for runtime decryption would be cumbersome and out of character with out current UI. 

Note: We should be sure to add `Info` output or something so indicate to users that we detected an encrypted container.
