### ISSUE TITLE
Separate handling of encryption inputs based on type

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#4242]
We should change from the current handling of `SINGULARITY_ENCRYPTION_KEY` that allows for both key file paths and passphrases to be specified in the same variable. 

This should be split into:
- `SINGULARITY_ENCRYPTION_PASSPHRASE` and `--passphrase`(that creates an interactive prompt) for encryption using a passphrase.
- `SINGULARITY_ENCRYPTION_PEM_PATH`/`--pem-path` for encryption using a public/private rsa key pair in the `pem` format.

**Comment by GodloveD** [comment]
I think that if either of these flags are set, (but not if the env vars are set) it should also implicitly set the `--encrypt/-e` option (#4241).

**Comment by GodloveD** [comment]
Also bear in mind that this will deprecate the `pem:///` prefix that is currently needed for a pem file.

**Comment by ikaneshiro** [comment]
Just to be precise here and avoid confusion in the future. It will _remove_ the `pem://` prefix. Since it's not something that has made it into a release of singularity we dont need to do the deprecation process on it.

**Comment by GodloveD** [comment]
Yes.  Excellent point @ikaneshiro.
