### ISSUE TITLE
Add singularity-devel google group

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#4252]
As discussed in today's Singularity developers' meeting, the singularity@lbl.gov google group should be in a more appropriate organization and we would like to additionally have a separate developers' email group.

**Comment by DrDaveD** [comment]
The first question is, what should be the domain that the group will be in?  The default is "googlegroups.com", is that sufficient?  Otherwise someone will need to set up a connection from their domain to the group.  The only existing relevant domain that I can think of sylabs.io;  I think that's the only practical alternative unless someone is willing to purchase another domain for this purpose, and I don't see that happening.  singularity@googlegroups.com already exists and appears to have only spam in it.  We could use singularity-discuss@googlegroups.com and singularity-devel@googlegroups.com.

@vsoch what do you think?  Anybody at Sylabs?

**Comment by vsoch** [comment]
For the domain, I don't see any issue with using googlegroups.com - that would be a good open source / community choice. I don't see any issue with it unless Sylabs has an Enterprise Google Suite that you would want to deploy it there. 

For the actual user group, I wouldn't try to do some kind of migration - there is huge amounts of knowledge / history in the lbl group (almost 700 members and about 1000 topics) and I don't see any imminent need to make a new one to replace it. For the development group, singularity-devel would work. It's too bad singularity@googlegroups.com is taken - but it's not surprising, Singularity is a fairly well known term :)

**Comment by DrDaveD** [comment]
Hopefully the old group singularity@lbl.gov group would stay there with its archives but we could have the email forwarded to the new group.  We would automatically subscribe everyone from the old group to the new one.

**Comment by vsoch** [comment]
I don’t think that’s a good idea, but others can comment.  Just thinking of all the places that the list is linked (that would then need to be changed, and if the previous list still exist it would just be confusing and people would likely still use it) and then signing people up to a new list without their consent, and then having two places to search when you’re looking for something...  if there was a compelling reason maybe there would be enough support to do it, but it just seems like it would add a lot of unnecessary confusion.

Making a dev list I am in full support of -  The need is there, and it doesn’t break anything that currently exists.  Could you please share your reasons for wanting to do an overhaul of the currently working list, and if you think the rationale is good enough,  how you would deal with the challenges outlined above?

**Comment by DrDaveD** [comment]
Reasons for wanting to overhaul:
1. lbl.gov has very little connection to singularity anymore and it doesn't make a whole lot of sense for it to be there.  It's certainly not a place where someone might go looking for it.  It may also be unsustainable, if the administrators at LBL suddenly decide they want to stop supporting it.
2. It's very messy to have two very related groups in two different organizations.  I think that if we don't move singularity@lbl.gov at this time, I'd rather ask a current LBL admin that's presumably still friendly to singularity to add a singularity-devel@lbl.gov, so the lists can stay together.

Having old archives elsewhere may be confusing for a while but eventually people will lose interest in them.  As for consent, we could send a message out to the old list informing people of what we'll be doing, and asking them to notify us if they want to opt out of the new list.  I can't imagine many people objecting.

**Comment by vsoch** [comment]
Ha, there's actually already a developer category (looks like it wasn't used) https://groups.google.com/forum/#!categories/singularityware/developer

Greg is still the owner - he shouldn't have any issue editing it in whatever way he wants. I can also offer to try making changes for whatever I'm allowed (adding other managers, etc.) Just let me know!

**Comment by vsoch** [comment]
And if you abandon ship and go for a new list, that works too... but I am very afraid for you, haha. Godspeed! :ship:

**Comment by DrDaveD** [comment]
Yeah but the singularityware name has been left in the dust, nothing uses it anymore.  Also, I joined the group and it appears to require you to get all messages from two different "topics" user and developer and as far as I'm concerned that negates the reason for having a separate developer group.

**Comment by vsoch** [comment]
Thanks for letting me know - I wasn't aware singularityware was gone and deprecated.

**Comment by DrDaveD** [comment]
Can we have any feedback on this from @singularity-maintainers

**Comment by GodloveD** [comment]
Just read through the thread.  I agree with @vsoch that it will be a great deal of upheaval for minimal benefit to migrate the google group from lbl domain.  We actually had a big discussion on this 1.5 to 2 years ago if memory serves.  V was involved and I think we were worried about losing all of the data from the existing group.  lbl has not signaled any desire to abandon this afaik, so I don't see much of a point.  

I agree that a devs Google Group could be useful.  But I also understand the difficulty associated with 2 different domain names.  

At the same time, we've sort of intentionally made everything everything when it comes to coms right?  Although a bunch of different channels exist on Slack, we encourage folks to post in general so that others may be exposed to content that they would normally ignore.  Is it all that bad?  Can devs just post in the existing group?  Not sure the advantage outweighs the drawbacks.

**Comment by DrDaveD** [comment]
The big problem with slack, if most people are like me, is that I do not have the time to watch everything going on in all the channels.  I only look if somebody alerts me in particular.  If discussions happen by named threads on a mailing list, I can look at them later if they interest me and not miss important discussions.  The problem with using the general mailing list is that there are a whole lot more people on that list and I think developers tend to avoid it.  Also in particular I'd like to send calendar invitations to the monthly meetings on a mailing list without requiring a bunch of people to decline them every month.

So @GodloveD if you don't want to move singularity@lbl.gov, what do you think about adding singularity-devel@lbl.gov?

**Comment by GodloveD** [comment]
>So @GodloveD if you don't want to move singularity@lbl.gov, what do you think about adding singularity-devel@lbl.gov?

Sounds like the best alternative from where I'm sitting.  What say you @vsoch ?

**Comment by vsoch** [comment]
You'd need to ask @gmkurtzer to reach out to old friends to create it, or maybe he still can?

**Comment by DrDaveD** [comment]
The request to create singularity-devel@lbl.gov has been submitted, we'll see if it gets approved.

**Comment by DrDaveD** [comment]
The [singularity-devel@lbl.gov](https://groups.google.com/a/lbl.gov/forum/#!forum/singularity-devel) google group has been created.
