### ISSUE TITLE
singularity shell --fakeroot leaves file permission problem

### ISSUE THREAD

**Issue by biocyberman** [apptainer/singularity#4263]
This is rather an inherent problem of fakeroot, but I hope Singularity can do something smart about this. 

## Version of Singularity:

singularity version 3.3.0

### Expected behavior
ownership of files and directories should be mapped back to the USER who starts the container

### Actual behavior
```
INFO:    Cleaning up image...
ERROR:   failed to delete container image /tmp/rootfs-569592909: unlinkat /tmp/rootfs-569592909/home/testsub/.bash_logout: permission denied
```

### Steps to reproduce behavior

- start a container in shell mode with fake root: `singularity shell --fakeroot library://ubuntu`
- create a new user, say with username `testsub` inside the container with useradd command. 
- create a test directory, say `testdir` under fakeroot's home, and set permission: `chmod 777 testdir`. This is to ensure it is writetable to user `testsub`.
- switch to `testsub` user and cd into `testdir`. 
- create some test file there, for example `touch testfilebytestsub`.
- exit the container
- observe two things: `testfilebytestsub` under `testdir`  has user id and group id that are different from the current users; and files under `/home/testsub` which is actually under container's temporary directory also have the same ownerships as `testfilebytessub`. That means the HOSTUSER can't cleanup files without sudo/admin right.

**Comment by biocyberman** [comment]
I was thinking that I might solve the problem by setting something like this in `/etc/sub{uid,gid}`:
`foo:1000:1` where 1000 is user id of the HOST user, and range  is 1. But it does not work:

`FATAL:   could not use fakeroot: entry for user `myhostuser` found in /etc/subuid at line 4 but all with a range count different from 65536`

**Comment by treydock** [comment]
I ran into this same issue trying to use `run` subcommand. Steps to reproduce issue I saw:

```
$ cat centos7-demo.def 
BootStrap: docker
From: centos:7

%post
    yum -y update
    yum -y install epel-release
    yum -y install fortune-mod cowsay

%runscript
    fortune | cowsay

$ sudo singularity build ${TMPDIR}/centos7-demo.img centos7-demo.def

$ singularity run --fakeroot ${TMPDIR}/centos7-demo.img
```

Error:

```
ERROR:   failed to delete container image /tmp/pbstmp.7586470/rootfs-924869204: remove /tmp/pbstmp.7586470/rootfs-924869204/root/.bash_logout: permission denied
```

Permissions:

```
$ ls -la /tmp/pbstmp.7586470/rootfs-924869204
total 0
drwxr-xr-x 4 tdockendorf PZS0708  29 Aug 21 14:56 .
drwx------ 3 tdockendorf PZS0708  30 Aug 21 14:56 ..
dr-xr-x--- 3 tdockendorf PZS0708 126 Dec 12  2018 root
drwxr-xr-x 7 tdockendorf PZS0708  66 Aug 21 14:56 usr
```

**Comment by biocyberman** [comment]
@treydock Your problem might be simpler. Your user is still the owner of the files and directory. It is the wrong permission on this directory that prevent the cleaning up:
`/tmp/pbstmp.7586470/rootfs-924869204/root`. If you `ls -lah /tmp/pbstmp.7586470/rootfs-924869204/root` or the similar directory when you re-run, you will see the permission is `dr-xr-x---`. That means yourself do not have write permission, hence can not delete.

**Comment by cclerget** [comment]
Hi @biocyberman , will look at what can be done to cleanup those temporary files

**Comment by treydock** [comment]
@biocyberman Even if the permissions are wrong, I didn't set them. I built an image from docker and tried to run it. I didn't mess with permissions so I would assume the permissions issue is something specific to singularity. If I use just a plain `run` using the docker container the issue doesn't occur, only happens if I build a singularity image it seems.
