### ISSUE TITLE
we do not correctly catch stderr in the context of e2e command execution failures

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4280]
## Version of Singularity:

master.

### Expected behavior

When a command fails in the context of E2E, we may want to check the text that goes to stderr. Right now, for the `build` command of encrypted containers, that is not the case. It is not known at the moment if the problem only occurs for that command.

### Actual behavior

For the build command for encrypted container introduced in #4259, when the command fails due an incompatible version of `cryptsetup`, both stdout and stderr are empty. It is not clear if the bug is from `e2e`, `sylog` or something else.

### Steps to reproduce behavior

The test included to the e2e test for the build command (PR #4259). The expected behavior is commented out; the actual behavior active.

**Comment by WestleyK** [comment]
I was wandering about this (if not capturing stderr was intentional. _looks like not_) :+1:
