### ISSUE TITLE
'pull' dose not respect umask

### ISSUE THREAD

**Issue by WestleyK** [apptainer/singularity#4281]
## Version of Singularity:

```
3.3
```

### Expected behavior

umask should be honored when pulling a image.

### Actual behavior

Does not honor umask, output image permission will be 777.

 - Related to: https://github.com/sylabs/singularity/pull/4179

### Steps to reproduce behavior

```
$ singularity pull alpine
```

**Comment by sashayakovtseva** [comment]
So the issue is not in umask but in incorrect permissions set to the resulting SIF.
Good catch 👍
