### ISSUE TITLE
Expose environment variables for remote tokens

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#4299]
Currently there is no real way to login to a remote using an environment variable. Previously `SYLABS_TOKEN` was used, but that variable is over written in the typical use case for remotes. This makes a need for a new variable that will enable workflows that handle secrets through the environment.

CC: @ArangoGutierrez

**Comment by ArangoGutierrez** [comment]
I can't say how much this is needed for those planning on using the Builder and Library on their CI/CD pipes.

**Comment by dtrudg** [comment]
We haven't had a further ask for this, and it's possible to `echo $MYTOKEN | singularity login` in a workflow which we indeed do ourselves. I'm going to close this unless it is raised again. Feel free to re-open @ikaneshiro if you think it's a strong need.
