### ISSUE TITLE
Invalid offset calculation for some SquashFS images

### ISSUE THREAD

**Issue by oschulz** [apptainer/singularity#430]
I ran into trouble with a SquashFS image a few days ago that contained `0x0a`-byte within it's first 64 bytes. Singularity detected it and calculated an (incorrect) image offset, so mounting of the image failed.

I guess image offset might best be fixed to zero for SquashFS images.

**Comment by oschulz** [comment]
Proposed fix: #431

**Comment by gmkurtzer** [comment]
Got it, thank you! :D
