### ISSUE TITLE
Error pulling docker image after installing Singularity Desktop for Mac OS (Beta Release)

### ISSUE THREAD

**Issue by lnnrtwttkhn** [apptainer/singularity#4301]
## Version of Singularity:

I downloaded Singularity Desktop for macOS (Beta Release v0.1) [here](https://sylabs.io/singularity-desktop-macos/). I typed `singularity` in the command window to verify that the installation was successful. Everything seemed okay.

**System specification:**
* macOS Sierra, Version 10.12.6

### Expected behavior

I wanted to pull a publicly available docker image from Docker Hub using `singularity pull docker://nipy/heudiconv:latest`. I expected that the container would be pulled from docker and build as a singularity image on my local computer.

### Actual behavior

I received the following error message:
```bash
FATAL:   While making image from oci registry: while building SIF from layers: packer failed to pack: while unpacking tmpfs: unpack: error extracting layer: link /var/folders/d8/k32s9rs5507c1986nj3w8585n28cb5/T/sbuild-778585099/fs/opt/miniconda-latest/pkgs/ncurses-6.1-he6710b0_1/share/terminfo/N/NCR260VT300WPP /var/folders/d8/k32s9rs5507c1986nj3w8585n28cb5/T/sbuild-778585099/fs/opt/miniconda-latest/share/terminfo/N/NCR260VT300WPP: too many levels of symbolic links
```

Full error message / feedback

```bash
lip-osx-003854:Desktop wittkuhn$ singularity pull docker://nipy/heudiconv:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:c5e155d5a1d130a7f8a3e24cee0d9e1349bff13f90ec6a941478e558fde53c14
 43.24 MiB / 43.24 MiB [====================================================] 3s
Copying blob sha256:cac7dc6e33fc9f46fe99ad9e53f00913293d31060252c32f5459d924eaffcc21
 6.26 MiB / 6.26 MiB [======================================================] 0s
Copying blob sha256:3ee83ea42187a699eeb264cf3b140c9470f6b1f5d3306e9e1f2bdb5648ac48eb
 3.08 KiB / 3.08 KiB [======================================================] 0s
Copying blob sha256:dca27ec73bffb38dbe54e71d9e34b6d7823c9acad0ec6b59d4cc1a074cab267f
 244 B / 244 B [============================================================] 0s
Copying blob sha256:347ee56d6afe9c53bcee7dc7c3ad42a2b9ac37c9b291df28118af7b08985e2e2
 284.83 KiB / 284.83 KiB [==================================================] 0s
Copying blob sha256:a1399bcfada04be23c83b852401be8d97d4af5342da91fc0d76f0a504f287205
 13.73 MiB / 13.73 MiB [====================================================] 1s
Copying blob sha256:04d61e4ae950cb7667c7bfdc5946b7db18f3b5ffd5d3a3671585b1d188b973d2
 98.78 MiB / 98.78 MiB [====================================================] 8s
Copying blob sha256:d6c162e8035f42250035dfc058fb2f3564abeabf3c733910095ab52b53530523
 66.24 MiB / 66.24 MiB [====================================================] 4s
Copying blob sha256:7d1cb8830d82e301401c3044d8ed4858c96e30e588b8d28397193ed024469e13
 326.71 KiB / 326.71 KiB [==================================================] 0s
Copying blob sha256:967f37354587438c5f222251d60b406acb4b2a7c25ef4b8d6dca34afae700978
 191.66 MiB / 191.66 MiB [=================================================] 10s
Copying blob sha256:94308ba568182396382335ad29de06e911c0f21cf1649c11fab2290dd45bd799
 482 B / 482 B [============================================================] 0s
Copying config sha256:6781f9645f6212f20b341438d702a876df95ce77f8e128649c746eec1070c954
 9.15 KiB / 9.15 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
FATAL:   While making image from oci registry: while building SIF from layers: packer failed to pack: while unpacking tmpfs: unpack: error extracting layer: link /var/folders/d8/k32s9rs5507c1986nj3w8585n28cb5/T/sbuild-778585099/fs/opt/miniconda-latest/pkgs/ncurses-6.1-he6710b0_1/share/terminfo/N/NCR260VT300WPP /var/folders/d8/k32s9rs5507c1986nj3w8585n28cb5/T/sbuild-778585099/fs/opt/miniconda-latest/share/terminfo/N/NCR260VT300WPP: too many levels of symbolic links
```

### Steps to reproduce behavior

* Optional: Run on macOS Sierra, Version 10.12.6
1. Download Singularity Desktop for macOS (Beta Release v0.1) [here](https://sylabs.io/singularity-desktop-macos/)
1. Try `singularity pull docker://nipy/heudiconv:latest`

**Comment by GodloveD** [comment]
I'm able to reproduce this bug though I will also note that the error is specific to mac.  Wonder if it has anything to do with the different image handling introduced in the umoci PR by @ikaneshiro?  (Although I doubt it because I was also unable to replicate this bug with 3.1).  

As a temporary workaround, you can download the latest tag of this container from the [container library](https://cloud.sylabs.io/library/_container/5d66b9a37c33a87c6fa6a9d2) like so:
```
$ singularity pull library://godlovedc/heudiconv/heudiconv
```
I didn't sign this image because I just pulled it from Docker and I have no idea what is in it.  😸

**Comment by jmstover** [comment]
So ... after some debugging here ... The file `NCR260VT300WPP` is a *hard* link.

It appears that to actually create a hard link on macOS you need to do some uhh... special hoop jumping and hand waving. The file system "supports" it, they've just made it interesting to actually use.

For cases like these, I would recommend using the remote builder if you can. We can, sort of, build on macOS directly, but generally as long as the stars align and there isn't anything much special happening.

**Comment by jmstover** [comment]
I'm going to close this as there isn't any way we can work around this specific issue unfortunately.  You can try using the remote builder from the cloud services with:

```
singularity build --remote heudiconv.sif docker://nipy/heudiconv:latest
```

**Comment by pitosalas** [comment]
Same problem over here, in this case with this command, on MacOS:

$ singularity --remote  pull --name ros-kinetic-desktop-full.simg docker://osrf/ros:kinetic-desktop-full

**Comment by jmstover** [comment]
@pitosalas 
Try:
```
singularity build --remote --name ros-kinetic-desktop-full.simg docker://osrf/ros:kinetic-desktop-full
```

I _think_ you need to be logged into the cloud services. @dctrud ... Need to have a valid token to do a remote build yes?

There's a difference in handling between `pull` and `build`.

**Comment by pandyark** [comment]
I am having the same issue while pulling the nf-core rna-seq pipeline image. Is there any solution to this problem?

**Comment by mosoriob** [comment]
The same problem here using conda.
https://github.com/mintproject/dame_cli/issues/50
