### ISSUE TITLE
Labels should show what architecture the image is

### ISSUE THREAD

**Issue by WestleyK** [apptainer/singularity#4310]
## Version of Singularity:

```
v3.3
```

### Expected behavior

There should be a label the shows what architecture the container is.

```
$ singularity inspect foo.sif
...
org.label-schema.image-arch: "amd64"
...
```

This is only useful when the metadata is stored in its own partition. Otherwise, you can only inspect the image if the image, and the host are the same architecture.

### Actual behavior

Does not exist yet...

### Steps to reproduce behavior

Write here.

**Comment by dtrudg** [comment]
Implemented as `build-arch` in #5624

**Comment by qhaas** [comment]
If one [uses qemu + binfmt_misc](https://ownyourbits.com/2018/06/27/running-and-building-arm-docker-containers-in-x86/) to build the image for an architecture other than the host, it still shows the hosts architecture in `org.label-schema.build-arch`; not sure if this is expected behavior.  Consider...
```
$ uname -m
x86_64
$ singularity --version
singularity version 3.7.0
$ cat ppc64le-centos7.def
Bootstrap: docker
From: ppc64le/centos:7
$ singularity build --fakeroot ppc64le-centos7.sif ppc64le-centos7.def
...
$ singularity inspect ppc64le-centos7.sif 
org.label-schema.build-arch: amd64
org.label-schema.build-date: Tuesday_5_January_2021_12:56:39_EST
org.label-schema.schema-version: 1.0
org.label-schema.usage.singularity.deffile.bootstrap: docker
org.label-schema.usage.singularity.deffile.from: ppc64le/centos:7
org.label-schema.usage.singularity.version: 3.7.0
$ singularity exec -e -C ppc64le-centos7.sif lscpu
Architecture:          ppc64le
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
...
Vendor ID:             GenuineIntel
...
Model name:            Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
```

**Comment by dtrudg** [comment]
@qhaas - that's not unexpected, due to the way we retrieve the architecture from Go. Could you open another new issue about this specific concern? It's unlikely to be a high priority but we ideally should think about how to fix it.
