### ISSUE TITLE
Is there a way to see the sdtout/stderr of the instance?

### ISSUE THREAD

**Issue by pddg** [apptainer/singularity#4311]
## Version of Singularity:

```
$ singularity --version
singularity version 3.3.0
```

### Expected behavior

The SIF has below `startscript`.

```
%startscript
    echo "Hello world!"
```

The output of instance is showed like `docker logs`.

```
$ singularity instance start image.sif instance_name
INFO:    instance started successfully
$ singularity instance logs instance_name
Hello world!
```

### Actual behavior

There is no way to see the logs of the instance except using redirection of stdout/stderr to the file.

```
$ singularity instance start image.sif instance_name
INFO:    instance started successfully
# There is no way to see the output
```

It is difficult to debug an instance of Singularity because of the missing output of stdout/err.

I found out similar issue #1115, however, It seems that there is no any progress after it was issued.

There is many user of Singularity working with Docker image, I think. Converting Docker image to SIF is a great work. However, in the context of Docker, output logs to stdout is a usual way of logging. So the users are confused to the way of logging. 

Now, Singularity does not support to convert `CMD` and `ENTRYPOINT` section of Docker image to `startscript` of the instance, and creating definition file and defining the start script is needed（ #1929 ）. The users can add the trick to logging when they implement it. But, writing definition file to just redirect stdout/err to the log file is not efficient way after implementing the issue #1929. I strongly hope that the command to show the stdout/err of instance or issue #1115 (and issue #1929 ) will be implemented.

**Comment by dtrudg** [comment]
Hi @pddg 

With current Singularity the instance stdout and stderr logs can be found in files under `~/.singularity/instances/logs/<hostname>/<user>/`

I agree that a command that expose this like `docker logs` is what people coming across to Singularity are likely to expect.

R.E. `CMD` and `ENTRYPOINT` handling - with Singularity 3.x this is performed for `runscript` and should work as expected. If you examine `.singularity.d/runscript` you'll see references to `OCI_CMD` and `OCI_ENTRYPOINT`. Issue #1929 isn't specific to `startscript` (and appears to be out of date given the above), but you are correct that we don't create a `startscript` from `CMD` and `ENTRYPOINT`.

**Comment by GodloveD** [comment]
Holler if any more info is needed @pddg and I will re-open.

**Comment by pddg** [comment]
@dctrud 
Thanks for your response. 

I have some questions.

> With current Singularity the instance stdout and stderr logs can be found in files under ~/.singularity/instances/logs/<hostname>/<user>/

What is `hostname` here? Is it an instance name of the Singularity instance?

> R.E. CMD and ENTRYPOINT handling - with Singularity 3.x this is performed for runscript and should work as expected. If you examine .singularity.d/runscript you'll see references to OCI_CMD and OCI_ENTRYPOINT. Issue #1929 isn't specific to startscript (and appears to be out of date given the above), but you are correct that we don't create a startscript from CMD and ENTRYPOINT.

This may deviate from the main point of this issue…… `runsctript` performs well, I see. However, I need to run some commands in the background like `docker run -d`. `singularity instance start` can not pass any command to the instance. Define `startscript` is needed by writing the Singularity definition file. Isn't it inconvenient?

@GodloveD 
That is all I want to hear now.

**Comment by dtrudg** [comment]
Sorry for the slow reply - I lost track of this issue, apologies.

>> With current Singularity the instance stdout and stderr logs can be found in files under ~/.singularity/instances/logs///

> What is hostname here? Is it an instance name of the Singularity instance?

hostname is the name of the local system, that you'd get from running the `hostname` command. This is so instances with the same name running on different nodes that share a home directory won't clash.

My hostname is 'piran.randomroad.net', and I'm going to run an instance called 'bob'...

```
dave@piran~> singularity instance start docker://nginx bob
```

My logs are at....

```
dave@piran~> ls ~/.singularity/instances/logs/piran.randomroad.net/dave/
bob.err  bob.out
```

> singularity instance start can not pass any command to the instance. Define startscript is needed by writing the Singularity definition file. Isn't it inconvenient?

If you create a startscript that does....

```
exec "$@"
```

... the you can run anything you want in the instance by passing it as an argument, e.g.

```
singularity instance start image.sig bob date
```

... would then run `date` in an instance called `bob` which is using the `image.sif` container image.
