### ISSUE TITLE
On %post fails, still create an image I can shell into

### ISSUE THREAD

**Issue by robertlugg** [apptainer/singularity#4318]
## Version of Singularity:
3.1.0-rc2
### Expected behavior
When %post fails, still create an image which I can access the shell.
Name the image whatever it was named followed by _build_fail
If you do implement this, I suggest an optional enable from the command line as I'm sure many people like that Singularity fails on an invalid build.
### Actual behavior
I am very bad at writing shell scripts.  Almost always I have some problem in my %post that causes the build to fail (which I'm glad it does).  However, its hard and slow to fix my error.  I try to build a container a few times before I get it correct.

I thought it would be nice if you could somehow build the container in the current state.  I could then shell into it and manually paste in the remaining lines in %post to confirm that they work.

### Steps to reproduce behavior

Create a %post with a sh invalid command, then try to build it.

**Comment by jmstover** [comment]
A normal SIF image is read-only. The core part is immutable, once created (squashfs image).

For this, it seems like you would want to use a `sandbox` image for initial planning/testing. So, you could do something like:

```
$ sudo singularity build --sandbox centos docker://centos:latest
  [ ... ]
$ sudo singularity shell --writable centos/
  [ This puts you into the CentOS sandbox, where you can test the %post commands, etc... ]
```
Once you have the commands you need to run down from the `--sandbox` testing, you can transfer them over to a definition file `%post` section. 

The `%post` section, is ran after the `From` image is pulled down. So, if you had:
```
Bootstrap: docker
From: centos:latest
```

Then the equivalent prior to `%post` in a sandbox would be: 
```
singularity build --sandbox centos docker://centos:latest
```

**Comment by robertlugg** [comment]
@jmstover, that is good advice.  The particular problem I ran into was that I had a container working fine.  I then tried to rebuild the image with newer python package versions.  Various python packages updated and 'pip' couldn't figure out how to get the correct version of the dependencies.  It took me several runs before getting rid of all the problems.  I should have realized after the first failure, exited early in %post and then do as you suggest.  I was running with --sandbox, however, if there is a %post error, apparently everything is removed.  "it would be nice" if I could have had a sandbox that was correct up to the point where the %post failed so I could continue on.

This was annoying but may be a fairly infrequent problem.  I'll close this issue assuming as much.  Thank you for the advice.

**Comment by jmstover** [comment]
When you do a build, there's the `--no-cleanup` flag. This _should_ leave the rootfs under the `sbuild-XXXXXXX` directory available for you to look over. But it is only on that one build, not a continuation... but it's a state you can at least look at.
