### ISSUE TITLE
getent info truncated

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#4323]
## Version of Singularity:

3.x

### Expected behavior

getent passwd for a user calling a container should match the record outside of the container.

### Actual behavior

gecos is truncated, so only Full Name is available, but not the email.

### Steps to reproduce behavior

python -c 'import pwd,os; user=os.getenv("USER"); print(pwd.getpwnam(user))'
outside
vs
singularity exec <IMAGE> python -c 'import pwd,os; user=os.getenv("USER"); print(pwd.getpwnam(user))'
inside the container. See the pw_gecos field.

**Comment by jscook2345** [comment]
I saw in oss slack that @cclerget said the following:

```
looks like it's truncated by Go : https://golang.org/src/os/user/lookup_unix.go line 130 (edited) 
```

**Comment by sashayakovtseva** [comment]
As far as I looked into this, that is not Go `os/user` package issue, because they [document](https://golang.org/pkg/os/user/#User) this as the intended behavior. Basically, the `User` structure does not contain `gecos` filed, but a `Name` rather, which is, as @moskalenko said, the first entry of `gecos`.

To fix this we should probably switch to a different package or parse `/etc/passwd` ourselves. 
Suggestions?

**Comment by sashayakovtseva** [comment]
As discussed with @cclerget we need to call C directly for this.

**Comment by sashayakovtseva** [comment]
Steps to reproduce:
1. Make sure you are running as a user who has a comma separated gecos in `/etc/passwd`, e.g. user 1000 from the example below:

```
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/bin/false
vagrant:x:1000:1000:Sasha Yakovtseva, sasha@sylabs.io:/home/vagrant:/bin/bash
ubuntu:x:1001:1001:Ubuntu:/home/ubuntu:/bin/bash
```

2. On host output is full:
```
$ python -c 'import pwd,os; user=os.getenv("USER"); print(pwd.getpwnam(user))'
pwd.struct_passwd(pw_name='vagrant', pw_passwd='x', pw_uid=1000, pw_gid=1000, pw_gecos='Sasha Yakovtseva, sasha@sylabs.io', pw_dir='/home/vagrant', pw_shell='/bin/bash')
```

3. In Singularity gecos is truncated:
```
$ singularity pull library://dppereyra/default/python:3.6.8-debian
$ singularity exec python_3.6.8-debian.sif  python -c 'import pwd,os; user=os.getenv("USER"); print(pwd.getpwnam(user))'
pwd.struct_passwd(pw_name='vagrant', pw_passwd='x', pw_uid=1000, pw_gid=1000, pw_gecos='Sasha Yakovtseva', pw_dir='/home/vagrant', pw_shell='/bin/sh')
```
