### ISSUE TITLE
Unable to install based on official admin guide

### ISSUE THREAD

**Issue by joshuaganger** [apptainer/singularity#4324]
## Version of Singularity:

3.3.0

### Expected behavior

Expected to be able to install based on provided official instructions

### Actual behavior

error: Failed build dependencies:
        golang is needed by singularity-3.3.0-1.el7.x86_64

### Steps to reproduce behavior

New install of CentOS7.  Followed the commands from here: https://sylabs.io/guides/3.2/admin-guide/admin_quickstart.html#installation

 ```
sudo yum -y update && sudo yum -y install \
    wget \
    rpm-build \
    git \
    gcc \
    libuuid-devel \
    openssl-devel \
    libseccomp-devel \
    squashfs-tools
```
```
export VERSION=3.3.0  # this is the singularity version, change as you need

wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz && \
    rpmbuild -tb singularity-${VERSION}.tar.gz && \
    sudo rpm --install -vh ~/rpmbuild/RPMS/x86_64/singularity-${VERSION}-1.el7.x86_64.rpm && \
    rm -rf ~/rpmbuild singularity-${VERSION}*.tar.gz

```

The guide says: 

> Go and all other build dependencies will be downloaded automatically just to build the RPM, and will then be automatically removed.

But the build fails with:

> error: Failed build dependencies:
>         golang is needed by singularity-3.3.0-1.el7.x86_64

I have also installed Go separately following the instructions from that project and successfully built their hello world project.

**Comment by joshuaganger** [comment]
Oops, this is a duplicate of #2562 from January.  That one remains unresolved it appears.

**Comment by jmstover** [comment]
Hi @joshuaganger ... 
I just put in this PR to hopefully update it:
https://github.com/sylabs/singularity-admindocs/pull/47

I had _thought_ it was already, but looks like it was just the `INSTALL.md` instructions that were changed.
