### ISSUE TITLE
can't stop instances spawned via slurm

### ISSUE THREAD

**Issue by biocyberman** [apptainer/singularity#4332]
## Version of Singularity:

3.3.0

### Expected behavior

singularity instance stop <instancename> should stop the instance, and clean up the list.

### Actual behavior

after the `stop` command, `singularity instance list` still shows the instance in the output

### Steps to reproduce behavior

1. allocate job: salloc --time=3:00:00
2. create an instance with slurms srun: `srun singularity instance start library://alpine:latest test`
3. check instance exist in compute node: srun singularity instances list
4. try stopping it: srun singularity instance stop test
5. List again, and see "test" instance is still there.  
6. Try starting another instance with the same name, this fails: `srun singularity instance start library://alpine:latest test`
FATAL:   instance test already exists
7. Shell into the 'existing' instance fails: `srun singularity shell instance://test`
FATAL:   could not open proc directory /proc/61292: no such file or directory

**Comment by biocyberman** [comment]
A workaround for now:
remove folder for the instance at `~/.singularity/instances/sing/<nodename>/<username>/<instancename>`

Get into interactive job shell first and then start an instance:
```
salloc --gres=gpu:1 --time 4:00:00 srun --pty bash -i 
singularity instance start library://alpine:latest test
```

This works as expected.

Another observation:
User doesn't need to have 'fakeroot' (/etc/{subuid,subgid} in in the compute node order to run `singularity <command> --fakeroot`. This may be how slurm works. But it may also presents some thing unexpected to singularity instances (i.e. environment variables, devices, mount points, etc). Just my 2c speculation.

I understand that `instances` are meant to be used as services, and daemons, therefore may not be in the same line of thoughts with `slurm`, which controls rather short lived processes. However, I can use instances with slurm to run services/daemons for a predetermined amount of time and resources.  So it is still worth improving :)

**Comment by cclerget** [comment]
@biocyberman #4372 should fix the issue
