### ISSUE TITLE
Add singularity config fakeroot command

### ISSUE THREAD

**Issue by cclerget** [apptainer/singularity#4345]
This is part of #3944. In order to ease management of fakeroot allowed users, we will introduce a command `singularity config fakeroot` in order to add/remove/disable users with :

```
singularity config fakeroot --add user
singularity config fakeroot --remove user
singularity config fakeroot --disable user
singularity config fakeroot --enable user
```

Those commands will automatically take care of user mappings allocation to minimize mistakes (UID/GID overlapping) which could be introduced by doing that manually

**Comment by DrDaveD** [comment]
This did not make it into the 3.4 release so please change the label and milestone.
