### ISSUE TITLE
install doesn't seem to work non-interactively

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#436]
I stumbled on this issue when re-generating [our packer build](https://github.com/singularityware/singularity-builder). Basically, when run non-interactively the install fails (config.log is attached). I think it comes down to some difference with regard to the environment / namespaces when a user is logged in vs. not. I tried making the script header executed by `sh` and `bash`, and also sourcing the `bashrc` and `profile` of the user, which did not make a difference. The core error seems to be:

      ac_nonexistent.h: No such file or directory

The strange thing is that this exact build, using the packer builder, worked a few months ago. So either there was a change in the Singularity install dependencies / headers, or something on Google Cloud that we could never measure. If we are not able to fix this error, the most logical solution would be to have an install via some package manager (eg, apt-get install ...) and I know this is hard to maintain. The workaround that I've come up with for now is generating an image manually, installing singularity, and then bringing down the instance (but not deleting the disk) and generating an image from the disk. This image is then used to generate the builders for Singularity Hub, and we would need to (manually) make a new one with the same procedure for each major release of Singularity, or find another way to use an automated builder that let's us run scripts via the login shell. 
[config_log.txt](https://github.com/singularityware/singularity/files/681649/config_log.txt)

I bring this up because I know several groups expressed interest in having the (programmatic) ability to reproduce their own registry / singularity hub, and I'm trying to minimize any and all manual steps to do that.

**Comment by jmstover** [comment]
See this post:
http://lists.gnu.org/archive/html/autoconf/2011-03/msg00009.html

That *may* not be the exact same part, but there's also errors in the log like:
```
  gcc: error: unrecognized command line option '-V'
  gcc: fatal error: no input files
```

Does the configure script look for the namespaces to include support for? 

```
conftest.c: In function 'main':
conftest.c:36:9: error: 'CLONE_PID' undeclared (first use in this function)
 unshare(CLONE_PID);
```

**Comment by gmkurtzer** [comment]
the log shows that it exited success:

```
configure: exit 0
```

@jmstover: CLONE_PID is the legacy process namespace name, it is now CLONE_NEWPID. The configure script looks for both to figure out which one it should use (so that is expected).

**Comment by jmstover** [comment]
@gmkurtzer Cool. Figured it was probably something like that. My amazing lack of recent system programming is showing through wonderfully!

**Comment by gmkurtzer** [comment]
@vsoch Any progress on this?

**Comment by vsoch** [comment]
No, I never figured it out, only a workaround. I make the builders manually, and then save the image. It's strange because it worked before with Packer, but figuring out what changed over 2 months might be impossible. We will only run into trouble when others might want to deploy their own builders to different clouds (which Packer is amazing at) and we don't have a solution to provide.

**Comment by gmkurtzer** [comment]
What is the status on this, can it be closed?

**Comment by vsoch** [comment]
yeah we can close, I'll make another issue if I run into this again. The workaround I'm using is just generating the images (manually) in advance. It's not such a huge deal because I do it twice (for two size images) per release!
