### ISSUE TITLE
Unhelpful error when trying to use --fakeroot

### ISSUE THREAD

**Issue by mem** [apptainer/singularity#4361]
## Version of Singularity:

47181b69bee9557a8d5dbe91398fb91e68a55bde

### Expected behavior

```
$ singularity build --fakeroot ...
```

produces an error that allows the user to figure out what the problem is.

### Actual behavior

```
$ singularity build --fakeroot ...
ERROR  : Failed to create container namespaces
```

### Steps to reproduce behavior

```
$ singularity build --fakeroot ...
ERROR  : Failed to create container namespaces
```

In this case, the host is running Debian 10 (buster). By default it has `kernel.unprivileged_userns_clone=0` which causes the clone call with the CLONE_USERNS flag to fail. Other distributions use the same or different mechanisms to allow unprivileged users to use this call.

Singularity should at least provide a hint as to what's going wrong and maybe even point to a documentation webpage specifying the possible fixes.

This is related but not the same as #3936 and maybe also related to #3927 (but not the same).

**Comment by mem** [comment]
On Debian this is fixed by:

```
echo 1 > /proc/sys/kernel/unprivileged_userns_clone
```

**Comment by mjm455** [comment]
I'm getting this error with Singularity 3.4.0 and 3.4.1 on a variety of CentOS servers running 7.2, 7.4 and 7.5 and each of them have namespaces turned on.  Do you know why this could be for CentOS and how to fix it?

**Comment by dtrudg** [comment]
On CentOS / RHEL there is a boot parameter, and then a sysctl parameter for the max number of user namespaces (which may default to 0) so you can do the following:

```
grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"
sudo echo "user.max_user_namespaces=15000" >> /etc/sysctl.conf
```

then reboot

**Comment by mjm455** [comment]
Thanks for the quick response.  I ran that command (but before you added the second line, however I already have user.max_user_namespaces=1024 in the sysctl.conf file) and I get the following error:

singularity build --fakeroot centos.sif centos.def
ERROR   :   Failed to create mount namespace: Operation not permitted.

My centos.def file contains the following:
BootStrap: docker
From: docker://centos.latest

%post
echo "HELLO"

I ran "singularity config fakeroot --add me" so it knows of my name.

UPDATE:
I ran this on a second system that has CentOS 7.5 and I set namespaces=15000 this time and it worked.  I also changed the def file to use From: centos:latest at the top of it.

Not sure why my other system is still giving me the issue of not being able to mount namespace though.

**Comment by mjm455** [comment]
Is this a kernel issue that I'm having between Centos 7.2 vs 7.5 for why I'm getting the error " Failed to create mount namespace: Operation not permitted."  ?

**Comment by dtrudg** [comment]
It looks like 7.2 should be okay, per: https://goyalankit.com/blog/user-namespace-in-red-hat-enterprise-linux-7-dot-2

What's your reported Kernel from `uname -a` and what's your `/proc/cmdline`? - do you see the `user_namespace.enable=1` which should be inserted by the 

```
grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"
````

... and reboot?

AFAIK the enabling of user-namespace stuff is something that has changed during the life of CentOS / RHEL7 releases - with regard to experimental / supported status, and how to activate it.

**Comment by tbugfinder** [comment]
@mjm455 
I had to apply `grubby --args="namespace.unpriv_enable=1" --update-kernel="$(grubby --default-kernel)"` in addtion to user_namespace.enable (RHEL 7.4/CentOS 7.4).

**Comment by matmu** [comment]
This helped for me on CentOS 7.7:
```bash
# From 7.4, kernel support is included but must be enabled with:
echo 10000 > /proc/sys/user/max_user_namespaces
```
