### ISSUE TITLE
Do not overwrite tmpDir from various flags

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#4377]
Currently the same global var is updated from various flags:
- actionTmpDirFlag
- buildTmpdirFlag
- pullTmpdirFlag

That should be omitted to prevent weird behavior when flag is set, but overriden by default value (possibly this happened [here](https://github.com/sylabs/singularity/issues/3024#issuecomment-526563358), not sure).

**Comment by sashayakovtseva** [comment]
Okay, since flags are registered for different commands, they are unlikely to affect each other. Closing until reproduced.

**Comment by sashayakovtseva** [comment]
Managed to reproduce: 

1. Apply patch
```
diff --git a/cmd/internal/cli/build.go b/cmd/internal/cli/build.go
index 0fe77af8b..8760c91cd 100644
--- a/cmd/internal/cli/build.go
+++ b/cmd/internal/cli/build.go
@@ -165,7 +165,7 @@ var buildLibraryFlag = cmdline.Flag{
 var buildTmpdirFlag = cmdline.Flag{
        ID:           "buildTmpdirFlag",
        Value:        &tmpDir,
-       DefaultValue: "",
+       DefaultValue: "/home/vagrant/test-tmp",
        Name:         "tmpdir",
        Usage:        "specify a temporary directory to use for build",
        EnvKeys:      []string{"TMPDIR"},
diff --git a/cmd/internal/cli/build_linux.go b/cmd/internal/cli/build_linux.go
index e968fa70c..3b6b3a6bf 100644
--- a/cmd/internal/cli/build_linux.go
+++ b/cmd/internal/cli/build_linux.go
@@ -99,6 +99,8 @@ func fakerootExec(cmdArgs []string) {
 }
 
 func run(cmd *cobra.Command, args []string) {
+       sylog.Infof("Temp  dir: %s", tmpDir)
+
        buildFormat := "sif"
        if sandbox {
                buildFormat = "sandbox"
```

2. Try to build. This should use home directory from the patch:
```
$ singularity -d build alpine.sif docker://alpine:3.10
```

**Comment by dtrudg** [comment]
This isn't really a bug AFAICT. In #3024 the issue was the env var not being carried into the sudo environment. The patch to reproduce here isn't really valid... as you can't get the proposed bug when `DefaultValue=""`
