### ISSUE TITLE
Issues with Go 1.13

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#4378]
## Version of Singularity:

`3.4.0-128.g9250bec41` (current `master` when issue is filed.)

### Expected behavior

Singularity should be compatible with Go v1.13.

### Actual behavior

Singularity is not currently compatible with Go v1.13. For example:

```sh
$ make -C builddir/ vendor
make: Entering directory '/home/adam/go/src/github.com/sylabs/singularity/builddir'
 VENDOR
go: github.com/sylabs/scs-key-client@v0.3.0-0.20190509220229-bce3b050c4ec: invalid pseudo-version: version before v0.3.0 would have negative patch number
Makefile:560: recipe for target 'vendor' failed
make: *** [vendor] Error 1
make: Leaving directory '/home/adam/go/src/github.com/sylabs/singularity/builddir'
```

The source of the issue appears to be that the version of the `github.com/sylabs/scs-key-client` package in `go.mod` and `go.sum` is not valid. Go 1.13 added version validation ([ref](https://golang.org/doc/go1.13#modules)).

External projects using Go v1.13 that import `github.com/sylabs/singularity` will also experience this issue. It manifests itself similarly:

```sh
go: github.com/sylabs/singularity@v0.0.0-20190731162714-49ec4f26125f requires
	github.com/sylabs/scs-key-client@v0.3.0-0.20190509220229-bce3b050c4ec: invalid pseudo-version: version before v0.3.0 would have negative patch number
```

### Steps to reproduce behavior

Run `make -C builddir/ vendor` with Go v1.13 installed, or import the `github.com/sylabs/singularity` module from a project using Go v1.13.

**Comment by tri-adam** [comment]
As a workaround for external projects importing `github.com/sylabs/singularity`, add a `replace` directive to your `go.mod`:

```
replace github.com/sylabs/scs-key-client v0.3.0-0.20190509220229-bce3b050c4ec => github.com/sylabs/scs-key-client v0.3.1-0.20190509220229-bce3b050c4ec
```

**Comment by mem** [comment]
Strange, I've been building with 1.13 RC1 exactly for this reason.

https://dev.azure.com/Sylabs/singularity/_build/results?buildId=20&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c7d0fcb4-3a10-5b26-dfea-e879a93fc2ab&l=19

Note in those logs that this is still using a GOPATH (even if `GO111MODULE` is `on`). It's not clear from the output you have provided that this is the case here.

I'll update the container and try again.

**Comment by tri-adam** [comment]
Using `GOPATH` (as per https://github.com/sylabs/singularity/blob/v3.4.0/INSTALL.md#clone-the-repo). `GO111MODULE` is not set.

I suspect the reason your CI is succeeding is because Singularity's `Makefile` is setting `-mod=vendor`. Thus, `go.mod` is ignored.

**Comment by mem** [comment]
`GO111MODULE=on` causes modules to be used even if the code is inside `GOPATH`. I mentioned `GOPATH` so that it didn't get overlooked, because it's not needed (you can build singularity outside `GOPATH`) but it's nevertheless used in that process.

`-mod=vendor` is there so that the code from the modules is obtained from the vendor directory and not the network. The CI process still checks that the vendored code is tidy, though (that the code in vendor matches what's specified in go.mod, etc).

Now I'm confused what the original issue is talking about...

**Comment by tri-adam** [comment]
Right, I'm familiar with `GO111MODULE` and `GOPATH`. And Singularity's use of `-mod=vendor`.

The issue is that Go v1.13 adds version validation to entries in `go.mod`. This is not exercised when doing a `make` since `-mod=vendor` is used. There are two cases where you can see the issue:

- Run a `go` or `make` command that utilizing `go.mod`. I used `make vendor` as an example.
- Import Singularity from an external project that uses Go v1.13.
