### ISSUE TITLE
Concurrent run of singularity failing

### ISSUE THREAD

**Issue by YPatois** [apptainer/singularity#4385]
## Version of Singularity: 
2.6.1-dist
Host OS: Scientific Linux release 6.10 (Carbon)
Client OS: CentOS Linux release 7.6.1810 (Core) 
Note: the image is a sandbox directory and hosted through NFS, and it seems to be important.

### Expected behavior
Starting two instances of singularity that would run at same time.

### Actual behavior
The second instance fails with 
ERROR  : Could not read /var/singularity/mnt/final/etc/passwd: Not a directory
ERROR  : Failed copying template passwd file to tmpdir: Not a directory
ABORT  : Retval = 255

### Steps to reproduce behavior
Host an image over a read-only NFS system.
My def is close to:
Bootstrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/

and build like:
singularity build --sandbox ...

Run one instance:
$ singularity exec /nfs/centosimage sleep 10 &
before the first stops, run a second:
$ singularity exec /nfs/centosimage sleep 10 &
ERROR  : Could not read /var/singularity/mnt/final/etc/passwd: Not a directory
ERROR  : Failed copying template passwd file to tmpdir: Not a directory
ABORT  : Retval = 255

Is there something known about that?

Thanks.

Yannick

**Comment by cclerget** [comment]
Hi @YPatois , is automount is configured for `/nfs` ?

**Comment by YPatois** [comment]
Hi,
Yes, it's an automounted NFS system, using regular auto.fs mechanism.
Does it matters?
Thanks.

**Comment by YPatois** [comment]
Hi,

I tried various "autofs bug path = " stuff, without any success yet...

**Comment by cclerget** [comment]
@YPatois I suggest to give a try with version 3.4.0 and see if the issue is fixed with this version, for your information we don't make any addition/bug fixes for v2 releases.

Maybe give a try with  `mount slave = no` in `singularity.conf`. The `Not a directory` error on open file  call is really weird

**Comment by YPatois** [comment]
Hi,
Thanks for your advices. I added the "mount slave = no" in the conf, and upgraded to latest 3.4.1.
Now it works, the error has just changed to a warning:
 WARNING: underlay of /etc/localtime required more than 50 (81) bind mounts

$ singularity exec= /nfs/centosimage sleep 10&
WARNING: underlay of /etc/localtime required more than 50 (81) bind mounts
$ singularity exec= /nfs/centosimage sleep 10&
WARNING: underlay of /etc/localtime required more than 50 (81) bind mounts
WARNING: failed to open passwd file in container: open /var/singularity/mnt/session/rootfs/etc/passwd: not a directory
WARNING: failed to open group file in container: open /var/singularity/mnt/session/rootfs/etc/group: not a directory

Note: is the configuration entry "container dir = " still valid? Seems it's not taken into account.

Despite of the warning, it seems to run. 
Thanks.

**Comment by cclerget** [comment]
Hi @YPatois , you always get `/etc/passwd: not a directory` warning which is confusing, I don't know if it's related to your NFS server configuration or something else. Does it only happen when container image is in a local directory like `/tmp` ? What if you try with local :

```
singularity build -s /tmp/sandbox docker://alpine
singularity exec /tmp/sandbox sleep 10 &
singularity exec /tmp/sandbox sleep 10 &
```

**Comment by dtrudg** [comment]
I'm going to close this issue as we haven't had a follow-up for a few months.

Please feel free to re-open if you are able to provide information about the NFS vs local runs as above. Thanks.
