### ISSUE TITLE
Build fails without "--without-suid" when installing as a normal user instead of just throwing a warning

### ISSUE THREAD

**Issue by bne86** [apptainer/singularity#4388]
## Version of Singularity:

3.4.0

### Expected behavior

Compile Singularity as normal user, throw a warning that setuid was not able to be set on the **starter-suid** file.

### Actual behavior

**make install** fails

### Steps to reproduce behavior

Always when compiling.

In our HPC environment we are using easybuild for providing Singularity.
The installation is done as a normal user, afterwards in a manual step the setuid permissions are set.

Version 3.2.1 worked as expected, but when we now try to compile version 3.4.0 we have issues with the build process. I expect this was added via https://github.com/sylabs/singularity/commit/228bbdefd9b14367da4e7dfbe49169f5e323b12f#diff-96161a24d3be43f45fa5e92297d28f79, because the build process is exiting and does not copy additional files, so we are lost with a half singularity installation within the build directory.

Do you see a way to support installations without sudo permissions that do not fail but instead just show a warning?

**Comment by cclerget** [comment]
Hi @bne86 , as RPM packaging suffers from the same issue and current check is skipped if  `RPM_BUILD_ROOT` environment variable is present, you can try to set `RPM_BUILD_ROOT=/dev/null` via `preinstallopts` or something else allowing to pass an environment variable.

**Comment by bne86** [comment]
Thanks for the pointer and sorry for the noise! Worked well.

**Comment by cclerget** [comment]
Glad it worked :)
