### ISSUE TITLE
Dump all accessed files

### ISSUE THREAD

**Issue by rodwalker** [apptainer/singularity#4404]
In order to build fat images, with everything needed to run a particular workload, it would be useful to run the workload in singularity and create a list of all the unique files accessed. Is that something singularity can help with?
The fat images are required to run on HPC where cvmfs is not available. Currently ATLAS build such images by trial and error. This should help automate the procedure.

Cheers,
Rod.

**Comment by dtrudg** [comment]
I'm afraid Singularity doesn't provide support for this at present. It is something that has been mentioned in passing a few times, but it's not on the roadmap to the best of my knowledge right now.

I'd be inclined to try out using `auditctl` to add rules to track `Open`
