### ISSUE TITLE
build fails as cluster (SGE) job

### ISSUE THREAD

**Issue by MarkBergman-cbica** [apptainer/singularity#4416]
## Version of Singularity:

 3.2.1-1.1.el7

### Example command

singularity --verbose --debug build lolcow.sif docker://godlovedc/lolcow

### Expected behavior

SIF file is built.

### Actual behavior
DEBUG   [U=25139,P=31963]  NewBundle()                   Created temporary directory for bundle /scratch/bergmama/sbuild-487259768
INFO    [U=25139,P=31963]  Full()                        Starting build...
DEBUG   [U=25139,P=31963]  Get()                         Reference: godlovedc/lolcow
DEBUG   [U=25139,P=31963]  cleanUp()                     Build bundle(s) cleaned: [/scratch/bergmama/sbuild-487259768]
FATAL   [U=25139,P=31963]  run()                         While performing build: conveyor failed to get: error getting username and password: error reading JSON file "/run/user/0/containers/auth.json": error unmarshaling JSON at "/run/user/0/containers/auth.json": unexpected end of JSON input

**Comment by MarkBergman-cbica** [comment]
The SGE job:

```
#! /bin/bash
env | sort | grep XDG

singularity --verbose --debug build lolcow.sif docker://godlovedc/lolcow
```
Produces the output:

```
XDG_DATA_DIRS=/root/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/run/user/0
XDG_SESSION_ID=102766
DEBUG   [U=25139,P=425806] NewBundle()                   Created temporary directory for bundle /scratch/bergmama/sbuild-848056026
INFO    [U=25139,P=425806] Full()                        Starting build...
DEBUG   [U=25139,P=425806] Get()                         Reference: godlovedc/lolcow
DEBUG   [U=25139,P=425806] cleanUp()                     Build bundle(s) cleaned: [/scratch/bergmama/sbuild-848056026]
FATAL   [U=25139,P=425806] run()                         While performing build: conveyor failed to get: error getting username and password: error reading JSON file "/run/user/0/containers/auth.json": error unmarshaling JSON at "/run/user/0/containers/auth.json": unexpected end of JSON input
```

**Comment by MarkBergman-cbica** [comment]
Work-around:
```
#! /bin/bash
XDG_RUNTIME_DIR=/run/user/`id -u` ; export XDG_RUNTIME_DIR
singularity --verbose --debug build lolcow.sif docker://godlovedc/lolcow
```

**Comment by jmstover** [comment]
@MarkBergman-cbica ... When you do the build, are you doing it as root?

**Comment by MarkBergman-cbica** [comment]
Nope -- the build is being done as an unprivileged user.

**Comment by jmstover** [comment]
But ... the variable from your `env | sort | grep XDG`  ... are for the root user.
```
XDG_RUNTIME_DIR=/run/user/0
```
Is SGE setting these in it's run environment and passing them?

In your workaround, you're setting `XDG_RUNTIME_DIR` to what is _should_ be for your user, not trying to use an incorrect location.

**Comment by MarkBergman-cbica** [comment]
Hmmm...probably...but not explicitly or deliberately, but I can't imagine it would be set anywhere else. This is the first time we've ever seen anything run as a batch job that references XDG* in any way, so it's not something we've considered before.

**Comment by ikaneshiro** [comment]
@MarkBergman-cbica What are the permissions on `/run/user/0/containers/auth.json`? Can you `cat` it as the user you are trying to run the build as?

I have seen this unexpected end of json input before when it actually failed to read from the file: https://github.com/sylabs/singularity/issues/2314

**Comment by MarkBergman-cbica** [comment]
> @MarkBergman-cbica What are the permissions on `/run/user/0/containers/auth.json`? Can you `cat` it as the user you are trying to run the build as?
> 
> I have seen this unexpected end of json input before when it actually failed to read from the file: #2314

I have no idea of the permissions... /run/user/0 is owned by root and has permission 700, so the 'containers' directory and auth.json probably weren't created....or they were removed when the singularity command failed.

**Comment by dtrudg** [comment]
Hi folks - please see also here... https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/X6Q-IsNQh-k

This is related to `containers/image` looking for that `auth.json` if `$XDG_RUNTIME_DIR` is set.... that `auth.json` is related to podman.

I'm not clear this is a Singularity issue... not sure why SGE would be setting things up like this. I would not expect `/run/user/0` to be pointed to from a non-root session.

**Comment by dtrudg** [comment]
I'm going to close this unless there is follow-up. This is an environment, rather than singularity issue, as `XDG_RUNTIME_DIR=/run/user/0` is being set for a root RUNTIME_DIR when the actual run is as a normal user.
