### ISSUE TITLE
Container exec fails without --fakeroot: cannot mount squashfs filesystem

### ISSUE THREAD

**Issue by james-ault-nnl** [apptainer/singularity#4418]
## Version of Singularity:  

3.4.0  
Built as RPM from release tarball and installed on all clients
singularity.conf as distributed in tarball

Environment info:
CentOS 7.6 Kernel version: 3.10.0-957.el7.x86_64
Kernel Parameter: namespace.unpriv_enable=1      Added to grub.cfg on all clients
Squashfs tools installed on all clients:  squashfs-tools-4.3-0.21.gitaae0aff4.el7.x86_64
Added to /etc/sysctl.d/77-containers.conf:
    # enable user name spaces for docker and singularity
	user.max_user_namespaces=16384

### Expected behavior

% singularity build basic.sif basic.def 
(image builds successfully)
% singularity exec basic.sif echo "hello world"
hello world

### Actual behavior

% singularity build basic.sif basic.def 
(image builds successfully)
% singularity exec basic.sif echo "hello world"
FATAL: container creation failed: mount /proc/self/fd/3->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: squashfs filesystem seems not enabled and/or supported by your kernel

### Steps to reproduce behavior

Build Singularity 3.4.0 as RPM on CentOS 7.6 with GA Kernel
% singularity build basic.sif basic.def 
% singularity exec basic.sif echo "hello world"

NOTE: Seems very similar to Issue [3928](https://github.com/sylabs/singularity/issues/3928).
[basic.def.txt](https://github.com/sylabs/singularity/files/3602697/basic.def.txt)

**Comment by james-ault-nnl** [comment]
I think these other issues may be related: Issue [4404](https://github.com/sylabs/singularity/issues/4044) and [1357](https://github.com/sylabs/singularity/issues/1357)

**Comment by cclerget** [comment]
Hi @james-ault-nnl , this error is returned when squashfs is not configured or loaded via module by the kernel. You can quickly check that with `grep squashfs /proc/filesystems` to see if there is a squashfs entry, you can also check squashfs is configured in the kernel configuration with `grep SQUASHFS /boot/config-$(uname -r)`

**Comment by james-ault-nnl** [comment]
Thank you.  I found an entry in /etc/modprobe.d that was disabling squashfs.  After removing that entry, the singularity exec command is working as desired.
