### ISSUE TITLE
unable to complete tutorial on CentOS6.7 w/ version 2.2

### ISSUE THREAD

**Issue by lordzappo** [apptainer/singularity#442]
```
charris@u36 ~/code/singularity>sudo `which singularity` create --size 4000 tensorflow.img
Creating a new image with a maximum size of 4000MiB...
Executing image create helper
Formatting image with ext3 file system
Done.
charris@u36 ~/code/singularity>sudo `which singularity` import tensorflow.img docker://tensorflow/tensorflow:latest
tensorflow/tensorflow:latest
Error getting tags using url https://registry-1.docker.io/v2/tensorflow/tensorflow/tags/list
Bootstrap initialization
No bootstrap definition passed, updating container
Executing Prebootstrap module
Executing Postbootstrap module
ERROR: Container does not contain the valid minimum requirement of /bin/sh
```
Interestingly, the next step is the box goes completely unresponsive, and I lose the ssh i typed the above in, and am unable to ssh in via another console for a minute or two.  Then the box comes back as if nothing happened.

Is this a mis-configuration or mis-installation, a known issue that has been fixed in master, or a previously unknown unknown?

Thanks! I appreciate your time and assistance.

**Comment by lordzappo** [comment]
A thought-- does this expect the docker service to be running? I cannot execute "docker pull" on this machine because the service is not running, even though docker is installed.

**Comment by jmstover** [comment]
@vsoch Did 2.2 have an auth bug in it for the Docker registry... I remember seeing some talk of some auth issues at one point. The logs here have:

`Error getting tags using url https://registry-1.docker.io/v2/tensorflow/tensorflow/tags/list`

I'm guessing that's either no route to the registry-1.docker.io site, or it's returning unauthorized.

-J

**Comment by vsoch** [comment]
Yes the fact that it's using `registry-1.docker.io` is an indication of an old verison of singularity that had this bug. Could you please update to master and try again?

**Comment by vsoch** [comment]
@lordzappo to answer your question - there is no dependency on the docker engine for the docker uri to work. It uses the registry, which is just posting calls to various web addresses to return json dumps! :hankey:

**Comment by lordzappo** [comment]
Thanks, I will close for now as it will take me a day or two to get the sysadmins to update and try again.
