### ISSUE TITLE
allow disabling the new "make install as root" check

### ISSUE THREAD

**Issue by odoublewen** [apptainer/singularity#4429]
[`build_runtime_suid.mk`](https://github.com/sylabs/singularity/blob/b94a931eb8f095b266e368be07fa3d274d440f77/mlocal/frags/build_runtime_suid.mk#L14-L17) changed between v3.3.0 and v3.4.0, due to issue #4227, which was addressed by #4262.

I use [Spack](https://spack.readthedocs.io/en/latest/), whose raison d'etre (HPC with environment modules) is exactly like @michaelkarlcoleman described in #4227:
> We're in an HPC environment and use Lmod to manage software, which means that we install pretty much everything into custom paths. (This is likely true for a lot of Singularity users.)

Spack users also commonly do scripted installs, of suites of software, installed automatically and reproducibly from source.  All without root.  (Spack generally handles root requiring steps (like this) with post-hoc scripts.)

I was recently [helping to package](https://github.com/spack/spack/pull/12785) Singularity v3.4.0, and in order to get it to work, we now have to [patch](https://github.com/spack/spack/blob/cb3dc206dc04047d634ea902af2dc6be815baf65/var/spack/repos/builtin/packages/singularity/singularity_v3.4.0_remove_root_check.patch) the file `build_runtime_suid.mk` to remove this check.

I'd argue the "exit 1 if not root" check creates new problems in use cases like the one I describe.   Perhaps consider adding a flag to the configure step, to turn off this check?  That would allow projects like Spack to more elegantly install the software.

**Comment by jmstover** [comment]
@cclerget ... does the `--without-suid` mconfig flag do anything to the code paths? It doesn't appear to as 2.x did... 

@odoublewen ... I _think_ with 3.x you would just need to build with the `--without-suid` flag, and the only suid component to setup would be to copy the `$libexecdir/singularity/bin/starter` binary to `$libexecdir/singularity/bin/starter-suid` and set the permissions correctly on it.

I'm pretty sure that's all that is needed.

**Comment by michaelkarlcoleman** [comment]
@jmstover IIRC, making `starter-suid` setuid root is not sufficient.  That executable checks the ownership and/or permissions of other files, and those have to be owned by root as well (I think).

I like the idea of having a `make install` and `make install-root` to separate these concerns.  Another possibility would be to have a `fix-setuid-permissions` script dumped somewhere.  Those who install without root could then just run this script (as root) if they wanted to graduate to a setuid-root install.

For those of us wielding root on large clusters, the simpler the "as root" part can be, the better.  If it's really just two or three standard Unix commands, it'd be very nice to separate that out to make things crystal clear, for auditing and security purposes.

**Comment by jmstover** [comment]
@michaelkarlcoleman ... The `starter-suid` binary should be the only suid component. I know the following files need to be owned by root:
```
$sysconfdir/singularity/singularity.conf
$sysconfdir/singularity/capability.json
$sysconfdir/singularity/ecl.toml
```
But it looks like there needs to be more done than just copying the binary. There's a slightly different Go build command on the `starter-suid` binary, so if that's missing (when using the `--without-suid` flag), then singularity will run an image ... by creating a sandbox, then running from that.

So, it's unfortunately not as easy as I was hoping. :/

**Comment by jmstover** [comment]
Check PR #4434 ... It should not error as a normal user and print a message the permissions are incorrect. You basically should just need to do the following after building as a normal user:

```
sudo chown root:root $libexecdir/singularity/bin/starter-suid
sudo chmod 4755 $libexecdir/singularity/bin/starter-suid
sudo chown root $sysconfdir/singularity/singularity.conf
sudo chown root $sysconfdir/singularity/capability.json
sudo chown root $sysconfdir/singularity/ecl.toml
```
I personally, would change ownership of everything under `$sysconfdir/singularity` to `root:root` ... but I believe the above should be the bare minimum needed.

**Comment by hartzell** [comment]
@michaelkarlcoleman , @jmstover @odoublewen @adamjstewart -- for what it's worth, Spack builds just such a script, using [this python snippet](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/singularity/package.py#L127-L139) to populate [this j2 template](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/singularity/spack_perms_fix.sh.j2).

Do either of you know if/when this change might get picked back into the 3.4.x branch?  We just got surprised by the fact that the 3.4.1 release still needs to be patched to keep from bombing out.
