### ISSUE TITLE
data race in e2e testing

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#4441]
## Version of Singularity:

I noticed a lot of the merges to master e2e tests have been failing with no one really looking into them.

I found the following showed a data race at the very end that should be looked into:

https://circleci.com/gh/sylabs/singularity/34429

**Comment by dtrudg** [comment]
This was with go-expect use in the e2e tests rather than Singularity and has now been eliminated with further progress on the e2e tests.
