### ISSUE TITLE
GetSignEntities() leaves open memory-mapped file on error

### ISSUE THREAD

**Issue by EmmEff** [apptainer/singularity#4442]
## Version of Singularity:

3.4.0

### Expected behavior

Container file handle is closed when `GetSignEntities()` fails on invalid SIF file, for example.

### Actual behavior

File handle is left open.

### Steps to reproduce behavior

Call `GetSignEntities()` on an invalid/malformed SIF file

**Comment by dtrudg** [comment]
This was closed by https://github.com/sylabs/singularity/pull/4443 I believe. @EmmEff - let me know if I'm wrong :-)
