### ISSUE TITLE
Create singularity container to run on GPU cluster

### ISSUE THREAD

**Issue by oguitart** [apptainer/singularity#4475]
Hello,

We  would like to use our singularity images ina share GPU cluster but the owners say is not possible:

**_Singularity only allows to run
images from the same architechture they were created from, and to modify
images 'sudo' is needed. That makes it impossible to customize power images_**

What would be your approach for these kind of issues? Maybe you know other institutions that are using singularity in their GPU clusters. How do they manage to make it work?
Thanks,

oriol

**Comment by dtrudg** [comment]
Hello @oguitart - if you need to run containers on a POWER cluster then I'm afraid that they will have to be build on a POWER system. However, with the newest versions of Singularity there is now a `--fakeroot` feature which means (depending on features being enabled in the OS, and configured), builds can be possible without sudo. What version of Singularity is being used on the cluster, and do you know what operating system it runs?

**Comment by oguitart** [comment]
Thank you for your answer. Below the information required. Let me know if you think it is feasible.


The OS version in power9 is:

NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"

And the latest version of singulrity available in the cluster is 3.2.0 (singularity/3.2.0).

**Comment by dtrudg** [comment]
`--fakeroot` should work on that system - but you need singularity 3.3 or above and the administrator would need to set...  `/proc/sys/user/max_user_namespaces` to a non zero value, and configure `/etc/subuid` and `/etc/subgid` for accounts that need to use `--fakeroot`

**Comment by dtrudg** [comment]
I'm going to close this. Note we now have more information about setting up and using fakeroot in the 3.5 userdocs and admindocs

https://sylabs.io/guides/3.5/user-guide/fakeroot.html
https://sylabs.io/guides/3.5/admin-guide/user_namespace.html
