### ISSUE TITLE
Horovod container does not work with LSF

### ISSUE THREAD

**Issue by ashwinidr3** [apptainer/singularity#4481]
### Version of Singularity:

singularity version 3.2.1-1.1.el7

### Expected behavior

run horovod on GPU- 
the container runs fine without LSF when used with mpirun on multiple nodes. but when the same command is used in the LSF script it gives ORTE error. 

The LSF runs fine for other jobs and also with singularity  for one node without mpirun.  
but when used with MPI it fails.I have tried to run with different versions of openmpi and impi and also tried installing openmpi in my home directory . nothing seems to work. is there any settings for singularity to run on multiple nodes?

mpirun -np 2 -H n1:1,n2:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib singularity run --nv horovod/ python /examples/keras_mnist_advanced.py - works fine (without LSF)

Please suggest.

### Actual behavior

Job Fails with ORTE error

### Steps to reproduce behavior

Submit job with LSF

#!/bin/sh
#BSUB -q default.q
#BSUB -n 2
#BSUB -R span[hosts=1]
#BSUB -eo horvod_err.%J
#BSUB -oo horovod_out.%J
#BSUB -W 400:00
#BSUB -R "select[gpu]"
mpirun -np 2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib singularity run --nv horovod/ python /examples/keras_mnist_advanced.py

### Environment?

CUDA version inside container 9.* on host CUDA 10.1 , OPENMPI 3.1.2 in container , same on host.

#### OS distribution and version:

rhel  x86
```
[horovod.docx](https://github.com/sylabs/singularity/files/3629655/horovod.docx)

$ cat /etc/os-release 

rhel 7.6


#### go version:

```
$ go version

```

#### How did you install Singularity

Not aware. it was Pre-installed

**Comment by jmstover** [comment]
Can you attach the `err` and `out` files? And also paste the ORTE error you're getting.

The `mpirun` command you have in the job script looks fine (though... no infiniband?). I have to assume that `mpirun` knows how to get the host list from LSF...

**Comment by ashwinidr3** [comment]
Please find the error file attached
we use OPA
mpirun gets the host list from LSF. i can see the GPU hosts assigned when i
run bjobs -w
PS: The error attched says /scratch read-only. but i do have read and write
permission

**Comment by ashwinidr3** [comment]
This issue is resolved. I had to bind the scratch to the the container.
however. since we use Omni path in our environment and it gives
libfabric.so.1 not found warning when i run the container. if it isnt too
much trouble could u please tell what all to be installed and configured to
run horovod application on omnipath from container?

**Comment by jmstover** [comment]
@ashwinidr3 
IIRC, `libfabric` is from OFED. When I got Singularity installed on a Omni Path cluster, I needed to have the same IntelOPA-Basic package installed inside the container as was installed on the host for interoperability.

So if `IntelOPA-Basic.RHEL75-x86_64.10.9.3.1.1.tgz` is what was on the host, then that same thing was in the container. A basic `%post` section I used at the time was:

```
    echo "Installing OPA dependencies"
    yum -q -y install perl which pciutils tcsh bc expect tcl
    yum -q -y install infinipath-psm sysfsutils papi
    yum -q -y install numactl-libs rdma-core libibumad libibverbs opensm-libs libuuid-devel libgfortran libgomp librdmacm elfutils-libelf-devel

    echo "Installing IntelOPA-Basic.RHEL72-x86_64.10.4.2.0.7"
    cd /tmp
    tar xzf IntelOPA-Basic.RHEL72-x86_64.10.4.2.0.7.tgz
    cd IntelOPA-Basic.RHEL72-x86_64.10.4.2.0.7
    ./INSTALL -n --user-space -G --without-depcheck
    cd /tmp
    /bin/rm -rf IntelOPA-Basic.RHEL72-x86_64.10.4.2.0.7/
```
