### ISSUE TITLE
instance won

### ISSUE THREAD

**Issue by Rhinogradentia** [apptainer/singularity#4483]
### Version of Singularity:

Write your Singularity version here.

### Expected behavior

What did you expect to see when you do...?

### Actual behavior

What actually happend? Why was it incorrect?

### Steps to reproduce behavior

Please fill out as much information as possible.

### Environment?

Please add infomation about your environment.

#### OS distribution and version:

```
$ cat /etc/os-release 

```

#### go version:

```
$ go version

```

#### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

**Comment by dtrudg** [comment]
See #4484
