### ISSUE TITLE
Root dir / belongs to root when using --overlay and a SIF image

### ISSUE THREAD

**Issue by marcodelapierre** [apptainer/singularity#4485]
### Version of Singularity:

Singularity 3.3.0

### Expected behaviour

I would like to be able to use a ext3 file system image as persistent overlay without root privileges. So crucially I'd need the root dir / to be writable by the current user (this is possible when using `--writable-tmpfs` to get an ephemeral writable fs).

### Actual behaviour

When using `--overlay` the root dir is owned by root, not the current user

### Steps to reproduce behaviour

```
$ dd if=/dev/zero of=my_overlay bs=1M count=500 &&     mkfs.ext3 my_overlay
$ singularity pull docker://ubuntu:18.04
$ singularity exec --overlay my_overlay ubuntu_18.04.sif ls -ld /
drwxr-xr-x 1 root root 1024 Sep 19 01:18 /
```

Please fill out as much information as possible.

### Environment?

Nothing relevant I reckon

#### OS distribution and version:

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

#### go version:

```
$ go version
go version go1.12.9 linux/amd64
```

#### How did you install Singularity

Compiled from source following sylabs docs

**Comment by cclerget** [comment]
Hi @marcodelapierre, you can use `-d` of `mkfs.ext3` for this purpose :

```
mkdir -p /tmp/overlay/upper
dd if=/dev/zero of=my_overlay bs=1M count=500
mkfs.ext3 -d /tmp/overlay my_overlay && rm -rf /tmp/overlay
```

**Comment by marcodelapierre** [comment]
does the job, many thanks for that!
