### ISSUE TITLE
Using Singularity on multinode infrastructure

### ISSUE THREAD

**Issue by mahmoodn** [apptainer/singularity#4486]
I would like to know how Singularity is used in HPC and multinode environments? Should I install singularity on all nodes? Then how to aggregate resources?
Will a user be able to boot his application image, e.g. Matlab with no care about free node selection? Or he has to find a free node and call his program image?

I appreciate if you guide me to the right direction.

**Comment by robertlugg** [comment]
An easy way would be to install singularity on the local disk of each node.  Singularity doesn't do any sort of machine provisioning, so you would have to ssh to a free node.  Your users should use ssh, UGE/SGE/LSF to get a node.  Or it should be possible to use Kubernetes although I have no experience with that.  To install, you must have root/install privileges.  To build containers also you need root privileges.  But to run the containers, you do not.  I know others can answer your question more definitively.

**Comment by rherban** [comment]
@robertlugg is spot on.  Singularity is expected to be available on each compute node and jobs should be scheduled with a job scheduler like Slurm, PBSPro, LSF, etc.  Once the job has been assigned to a compute node, their job script will specify what applications to run (including Singularity).

**Comment by mahmoodn** [comment]
OK thank you very much. I have plan to test that. I will have more questions later.
