### ISSUE TITLE
Bind host /tmp during bootstrap

### ISSUE THREAD

**Issue by PauloSouza7** [apptainer/singularity#449]
To build some apps we need a lot of temporary space to compile sources.
For example OpenCV takes more than 4GB.
It will be great to have access to host /tmp during bootstrap process
Also, can you make `/tmp/` the current dir of bootstrap instead of `/`

**Comment by bauerm97** [comment]
What version of Singularity (version number or commit) are you running on? In our current master branch (after 2.2) we have added a new bootstrapping process which should be mounting the `/tmp/` directory for access during all bootstrap scripts.

**Comment by PauloSouza7** [comment]
Hi,

I'm using the stable 2.2 from download page. I'll test the git master. 

How about making /tmp the current directory for bootstrap instead of / ?

Sure I can cd /tmp on the first line but I think if /tmp is the default directory it will avoid people downloading and keeping temp files on /

Thanks,
Paulo.

**Comment by gmkurtzer** [comment]
This feature has been added in [development e9ba16c].
