### ISSUE TITLE
--pwd /dir uses host dir

### ISSUE THREAD

**Issue by afortiorama** [apptainer/singularity#4498]
### Version of Singularity:

3.2.1

### Expected behavior

singularity exec --pwd /data -B $PWD:/data /home/aforti/test/docker_centos_7/image ls /data

I expect singularity to create /data with overlay or underlay, bind it to $PWD and change directory to /data in the container after that even when the directory /data exists on the host and not in the image.

/home/aforti/test/docker_centos_7/image is a sandbox build from a docker centos image.

### Actual behavior

If the directory /data exists on the host singularity seems to bind that to /data on the command line instead of binding /data to $PWD in the container. As a result the I/O doesn't happen and the following command lines don't work. **i.e. if the directory exists on the host it changes directory before binding** and the following happens

singularity exec --pwd /srv -B /home/aforti/test:/srv   /home/aforti/test/docker_centos_7/image touch /srv/pippo
touch: cannot touch ‘/srv/pippo’: Read-only file system

singularity exec --pwd /srv -B /home/aforti/test:/srv   /home/aforti/test/docker_centos_7/image /srv/_runcontainer.sh
/.singularity.d/actions/exec: line 9: /srv/_runcontainer.sh: No such file or directory

### Steps to reproduce behavior

This happens if a directory with the same name exists on the host and I use --pwd /data if i remove it this option or the directory doesn't exist on the host there is no problem. The directory is created and bound correctly.

singularity exec -B /home/aforti/test:/srv   /home/aforti/test/docker_centos_7/image touch /srv/pippo; ls -l $PWD/pippo
-rw-r--r-- 1 aforti aforti 0 Sep 20 17:03 /home/aforti/test/pippo
### Environment?

Not relevant

#### OS distribution and version:

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

#### go version:

not installed

#### How did you install Singularity

rpm from EPEL

**Comment by jmstover** [comment]
This is fixed in (at least) Singularity 3.4.0 from PR #4250
