### ISSUE TITLE
hostname obfuscation

### ISSUE THREAD

**Issue by PauloSouza7** [apptainer/singularity#450]
Do not expose the real hostname inside the container.

**Comment by GodloveD** [comment]
@PauloSouza7 and @gmkurtzer looks like this was left out of the 2.3 release.  Also missed the 2.4 release.  Is this really something we want to do?

**Comment by gmkurtzer** [comment]
This will be part of the next release with the UTS namespace integration. :)

**Comment by jscook2345** [comment]
This was implemented with the `--hostname` option. I think that is what was needed. Please comment if you have any questions or would like to discuss this more!
