### ISSUE TITLE
update Kubernetes docs to say that Singularity is an option

### ISSUE THREAD

**Issue by robertlugg** [apptainer/singularity#4503]
Request:
Edit or request an edit to this page:
https://kubernetes.io/docs/concepts/overview/components/

consider this text and modify to also reference and link Singularity.
```
Container Runtime
The container runtime is the software that is responsible for running containers.

Kubernetes supports several container runtimes: Docker, containerd, cri-o, rktlet and any implementation of the Kubernetes CRI (Container Runtime Interface).
```
I would do it myself, but I don't have the confidence until I've actually tried it!

**Comment by dtrudg** [comment]
Noting that we are currently listed on the linked page "https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/container-runtime-interface.md"
