### ISSUE TITLE
Truncated display of commands containing superior sign in the %post phase

### ISSUE THREAD

**Issue by blaiseli** [apptainer/singularity#4510]
In the `%post` a definition file, I include a command that echoes something and redirects it to a file using `>`:

```
$ cat test_echo.def 
Bootstrap:docker
From:alpine

%post
    echo "test" > test.txt
    cat test.txt
```

Only the `echo "test"` part is displayed during the build. The output of the `cat` part shows that the command did occur correctly, though.

### Version of Singularity:

```
$ singularity --version
singularity version 3.4.0-1
```

### Expected behavior

During the build, I expect to see the following commands displayed:
```
+ echo test > test.txt
+ cat test.txt
```

### Actual behavior

```
$ sudo singularity build test_echo.sif test_echo.def 
[sudo] password for bli: 
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:9d48c3bd43c520dc2784e868a780e976b207cbf493eaff8c6596eb871cbd9609
Copying config sha256:1f97f0559cbddbff6c872039e93f18c1abdc279cbe82e0eb40258c28f4c30bfd
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
2019/09/23 12:33:36  info unpack layer: sha256:9d48c3bd43c520dc2784e868a780e976b207cbf493eaff8c6596eb871cbd9609
INFO:    Running post scriptlet
+ echo test
+ cat test.txt
test
INFO:    Creating SIF file...
INFO:    Build complete: test_echo.sif
```

As you can see, the display is truncated: the `>` and what comes after are not visible.

#### OS distribution and version:

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

#### go version:

```
$ go version
go version go1.13 linux/amd64
```

#### How did you install Singularity

I think I followed the steps described here:

https://sylabs.io/guides/3.4/user-guide/quick_start.html#quick-installation-steps

**Comment by dtrudg** [comment]
This truncation of the redirection is a normal feature of the bash shell where `bash -x` or `set -x` is used to echo commands... e.g.

```
dave@piran:~
09:37 AM $ set -x
dave@piran:~
09:37 AM $ echo bob
+ echo bob
bob
dave@piran:~
09:37 AM $ echo bob > test.txt
+ echo bob
dave@piran:~
```

Since Singularity is using `set -x` to echo the commands from the build script here (and is not running each command inidividually), I'm not certain this can be addressed.

**Comment by jmstover** [comment]
Yeah, this is bash behavior. The only clue for the redirect is that you don't see output like:
```
+ echo test
test
+ cat test.txt
test
```
But instead see:
```
+ echo test
+ cat test.txt
test
```
Technically, the `> test.txt` isn't part of the command being executed, but is telling bash to change the `stdout` file descriptor.

**Comment by dtrudg** [comment]
Closing - this is not something we can easily address with the architecture of running a complete script in a single shell session, rather than a line-by-line %post block.
