### ISSUE TITLE
fakeroot uid/gid mapping length fixed to insufficient 65536 (with subuid/subgid).

### ISSUE THREAD

**Issue by pontus** [apptainer/singularity#4512]
### Version of Singularity:

```
3.4.1-1.el7
```

### Expected behavior

Expectation is 
```
$ singularity build --fakeroot /tmp/test.sifj test_galaxy.def
```
when run by `pontusf` on a host with 

```
$ cat /etc/subuid 
pontusf:10000000:4000000
$ cat /etc/subgid
pontusf:10000000:4000000
$ 
```
should build with fakeroot.

### Actual behavior

Build dies with error

```
FATAL:   could not use fakeroot: entries for user pontusf found in /etc/subuid but all with a range count different from 65536         
```
I can see valid reasons for enforcing a minimum mapping length to protect users from themselves, but no valid reasons for enforcing an upper limit assuming (excluding cases that would overflow a uid_t).

### Steps to reproduce this behavior

Set up a subgid/subuid file for the user running singularity with a mapping length other than 65536.

### What OS/distro are you running

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

Custom rpms built from source.

### Use case motivation

We run with a somewhat "sparse" user and group space where in addition to system and administrative uids/gids (that are low), we use ranges close to 10 000 and 40 000-50 000 that have been grandfathered in.

Newer uid/gids will use values close to 4 000 000 (for uids/groups tied to users), 3 000 000 for project-related groups and 5 000 000 for a few other groups.

For us to be comfortable with using fakeroot, we'd need the mapping to cover all "reasonable" uids/gids (at least 6 000 000 with the uid/gid space we use today).

**Comment by cclerget** [comment]
Hi @pontus , just to be sure we are on the same page, are you asking a range > 65536 to be used only by an administrator ? Or that each users you register to use fakeroot to have a large range ?

**Comment by pontus** [comment]
I'm not sure I understand this question correctly - we do need large ranges for all users.

We are unlikely to use the singularity config command (as per issue 3944) but rather generate subuid/subgid files as we see fit (and it's quite likely we decided to use a common range for all users [where all those uids/gids should be considered analogue to "nobody"]  although I don't see that should matter).

Please feel free to probe more if that was unclear.

**Comment by cclerget** [comment]
Got it ! Have you considered the security implication of doing that ? As all files/directories created using `fakeroot` with UID/GID != 0 will be shared by all users if those files/directories are located in a path accessible by users also able to take the same UID/GID in `fakeroot` context.

**Comment by pontus** [comment]
Yep, we are well aware of the implications (and not happy with it as we'd ideally would want to offer access to "private" files), but with the current state of user name space support, we feel this is the best we can do and it does enable a few important use cases.

**Comment by cclerget** [comment]
@pontus Large range will be allowed by #4551

**Comment by pontus** [comment]
Great, thanks a lot!
