### ISSUE TITLE
build error cryptsetup-bin. 

### ISSUE THREAD

**Issue by gitavk** [apptainer/singularity#4520]
### Version of Singularity:

```
$ singularity version
3.4.1-1
```

### Expected behavior
No errors on run `make` 

### Actual behavior
get error about absent package `cryptsetup-bin`
`apt install cryptsetup-bin` to fix it.

### Steps to reproduce this behavior

Install debian 10 from network iso with only `standard system utilities`
Start to install singularity by the [quick_start](https://sylabs.io/guides/3.4/user-guide/quick_start.html)
But in the [installation](https://sylabs.io/guides/3.4/user-guide/installation.html) the record about `cryptsetup-bin` exists.

### What OS/distro are you running

```
$ cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
### How did you install Singularity
the process installation was from source.

**Comment by jmstover** [comment]
There's a couple recent PR's that remove the error behavior with `cryptsetup`... 

#4434 and #4436
