### ISSUE TITLE
sandbox build with -u option not working

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4526]
**This is one issue taken from https://github.com/sylabs/singularity/issues/4517**

This issue was reported in the comment from @DrDaveD - and is separate from the first author's problems

### Version of Singularity:

What version of Singularity are you using? Run:

```
3.4.0-1.2
```

### Expected behavior

Can successfully build a sandbox using the ~non-privileged user-namespace~ `-u` option:

*Note - `-u` is for `update` not `userns` when used on `build`*

`singularity build -u --sandbox centos7-sandbox docker://centos:7`

### Actual behavior

Fails with:

```
INFO:    Starting build...
INFO:    Building into existing container: /cloud/login/dwd/scratch/centos7-sandbox
FATAL:   While performing build: failed to retrieve path for /cloud/login/dwd/scratch/centos7-sandbox: lstat /cloud/login/dwd/scratch/centos7-sandbox: no such file or directory
```

### Steps to reproduce this behavior

See above

**Comment by dtrudg** [comment]
Hi @DrDaveD  - I'm going to ask @cclerget if he can look at this one. It appears to be completely separate from the other 2 issues I've split out of #4517 as it can be reproduced without using centos7 as the docker image, but other things too:

```
08:13 PM $ singularity build -u --sandbox u_sandbox docker://debian
INFO:    Starting build...
INFO:    Building into existing container: u_sandbox
FATAL:   While performing build: failed to retrieve path for u_sandbox: lstat /home/dave/u_sandbox: no such file or directory
```

**Comment by dtrudg** [comment]
Noting here also that there was confusion (possibly mainly myself) as `-u` is `userns` elsewhere, but is used for `update` on build.

**Comment by DrDaveD** [comment]
@dctrud I was also confused and thought `-u` was `--userns` for build.  I have now repeated the test with #4522 while setting `allow setuid = no`  in `/etc/singularity/singularity.conf` and that works ok.
