### ISSUE TITLE
"singularity keys newpair" is looking for key service URI instead of generating it locally 

### ISSUE THREAD

**Issue by asmi10** [apptainer/singularity#4530]
3.4.0

What version of Singularity are you using? Run:

musxtestvm006:/nfs/imu/ # singularity version
3.4.0

What did you expect to see when you do...?

bash-4.4# singularity version
3.0.1-1.g1a1464f8
bash-4.4# singularity keys newpair
Enter your name (e.g., John Doe) :

What actually happend? Why was it incorrect?

musxtestvm006:/nfs/imu/disks/sregistry/sregistry # singularity key newpair
FATAL:   Unable to get key service URI: error making request to server: Get https://cloud.sylabs.io/assets/config/config.prod.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

It is looking for key service URI, I think it should create keys locally.
It works fine till singularity version 3.0. From singularity version 3.2 onwards I see this behavior. Is this expected? If yes, then why it is added? Currently I am using sregistry for storing my images and we do not have any keystore endpoint added there.
I think user should have independence to manage keys locally or in keystore endpoint of registry.

**Comment by WestleyK** [comment]
This is semi-expected; by default, `newpair` will try to connect to the remote keystore, and offer to upload your key (via interactive or `--push=true/false`). However, it should not try to connect to the keystore unless you specify you want your public key pushed.

Your keys are all managed locally, you can view your keys by `singularity key list`. All keys are generated locally, Singularity will only offer to push your public keys, (or you can push it manually with `singularity key push <fingerprint>`).
