### ISSUE TITLE
Building --without-suid fails at run time

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#4537]
### Version of Singularity:

What version of Singularity are you using?

3.4.0

### Expected behavior

What did you expect to see when you do...?

After building with `mconfig --without-suid`   I expect `singularity exec` to work successfully as an unprivileged user.

### Actual behavior

What actually happened? Why was it incorrect?

```
FATAL:   /cvmfs/oasis.opensciencegrid.org/mis/singularity/x86_64/3.4.0-1.1/libexec/singularity/bin/starter-suid not found, please check your installation
```
A workaround is to set `allow setuid = no` in `builddir/singularity.conf` after compile and before install, but that shouldn't be necessary.

**Comment by cclerget** [comment]
Fixed by #4540
