### ISSUE TITLE
Cannot reuse orerlay

### ISSUE THREAD

**Issue by gavlooth** [apptainer/singularity#4539]
### Version of Singularity:

```
3.4.1-318.g675295a8a
```
This also persist in  every other version i tried, icluded 3.3.0 3.4.0

### Expected behavior
enter an overlay container when using the shell command
 sudo singularity shell --overlay ubuntu ubuntu_latest.sif 

### Actual behavior
The command works perfectly the first time.
Trying to reuse the overlay throws: 

FATAL:   container creation failed: mount overlay->/usr/local/var/singularity/mnt/session/final error: while mounting overlay: can't mount overlay filesystem to /usr/local/var/singularity/mnt/session/final: stale NFS file handle

### Steps to reproduce this behavior
On latest arch linux install latest singularity from the oficial repository
create an overlay for ubuntu_latest  and try to use it. First time should go ok, second fails

### What OS/distro are you running

```
  Operating System: Arch Linux
  Kernel: Linux 5.3.1-arch1-1-ARCH
  Architecture: x86-64

```
### How did you install Singularity
Compiled from head, also tried tag releases

**Comment by cclerget** [comment]
Hi @Gavlooth , what is the overlay format ext3 image or sandbox ?

**Comment by gavlooth** [comment]
@cclerget sorry for the late response, is ext3

**Comment by gavlooth** [comment]
That is, i thinks so, since i didnt include any --sandbox flags anyware. Might it be the problem there ?

**Comment by gavlooth** [comment]
Maybe it would help to add the command here
sudo singularity shell --overlay arangoDB /mnt/Data/.singularity/ubuntu_latest.sif
where arangoDB is either a folder or an ext3 formated empty file of ~10gb and ubuntu_latest.sif is the 
latest ubuntu image as per singularity manual.

**Comment by cclerget** [comment]
With `--overlay` you can pass a sandbox directory (root only), an ext3 image or a squashfs image (root and user).

Ok, so when mounting an ext3 image in R/W mode like overlay does there is some information written in ext3 image which could explain `stale NFS file handle` error during second run, because first run mounted the ext3 image and write few informations (like updating the ext3 last mount field) and the second run get `stale NFS file handle` because of the first mount.

In general using the same ext3 image (with R/W mode) by multiple singularity processes is not going to work, expect many image corruption. Even using a sandbox as overlay by multiple singularity instances will result in unexpected behavior (don't expect that each instances share the files).

Additionally in master branch (#4069) there is a lock mechanism to prevent this kind of use because it's not safe at all due to multiple image corruption.

So the recommended practice in your case would be to use a dedicated overlay ext3 image (or sandbox) for each instances you are going to execute.

```
sudo mkdir /tmp/ov1 /tmp/ov2
sudo singularity exec -o /tmp/ov1 image &
sudo singularity exec -o /tmp/ov2 image &
```

Hope that helps

**Comment by gavlooth** [comment]
@cclerget If you cannot remount an overlay image, with changes from previous mounts then what is the point of an overlay
I mean, the information here https://sylabs.io/guides/3.4/user-guide/persistent_overlays.html is missleading, or do i miss something ?
I managed to do something akin to what the entry in the user guide mentions (that is create an overlay to introduce persistent changes) by combining the linux overlayfs and sandbox.

**Comment by cclerget** [comment]
@Gavlooth Sorry I didn't read original issue correctly, I thought you ran two singularity processes at the same time with the same overlay image.
Regarding the NFS error :

> The error, ESTALE, was originally introduced to handle the situation where a file handle, which NFS uses to uniquely identify a file on the server, no longer refers to a valid file on the server. This can happen when the file is removed on the server, either by an application on the server, some other client accessing the server, or sometimes even by another mounted file system from the same client. 

We may fall in :
> sometimes even by another mounted file system from the same client.

Are you using NFSv4 or v3 ? Also can you paste the NFS server export line regarding the mount where the overlay image is stored ?

You can check if the loop device is released or not with `sudo losetup -a -l` when you got this error, if you see line pointing to the overlay file that means there is a pending process holding reference to overlay image. If there is nothing try to run `sync /path/to/ext3/overlay/image` to flush data on NFS server.

**Comment by gavlooth** [comment]
I am not familiar with nfs, so I am not sure how to respond to the first statement. 
As for loop devices, it definitely unmounts when i exit the cell.
This is  when i mount :
NAME        SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                          DIO LOG-SEC
/dev/loop1          0      0         1  0 /mnt/Data/.dropbox                                   0     512
/dev/loop2  161189888  36864         1  1 /home/heefoo/.local/share/singularity/arangoDB.sif   0     512
/dev/loop0          0      0         1  1 /var/lib/snapd/snaps/core_7713.snap                  0     512
/dev/loop3 1073741824      0         1  0 /home/heefoo/.local/share/singularity/test           0     512

And this is after 

NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                           DIO LOG-SEC
/dev/loop1         0      0         1  0 /mnt/Data/.dropbox                    0     512
/dev/loop0         0      0         1  1 /var/lib/snapd/snaps/core_7713.snap   0     512

sync doesnt real do anything, the error persists until i re-format the file

**Comment by gavlooth** [comment]
The command i used  to mount the continer was sudo singularity shell --overlay test arangoDB.sif     
Where arangoDB.sif    is the latest ubuntu with arangodb installed. test is a file of 1G created with fallocate

**Comment by gavlooth** [comment]
@cclerget ?

**Comment by cclerget** [comment]
@Gavlooth Looks like you `fsid=` could solve that with your NFS exports https://lxadm.com/Stale_NFS_handle

**Comment by gavlooth** [comment]
@cclerget thanks i will try it out and let you know

**Comment by gavlooth** [comment]
I am not sure how to configure overlay to use the fsid option. The documentation does not provide details

**Comment by cclerget** [comment]
This is an option to put in you export line defined in  `/etc/exports` on your NFS server

**Comment by gavlooth** [comment]
I tried something like ~/singularity/test-dir *(rw,sync,insecure,no_root_squash,no_subtree_check,fsid=0)

**Comment by gavlooth** [comment]
but it doesn seem to work

**Comment by cclerget** [comment]
I would avoid to use `~` in export, try something like :

```
/tmp *(rw,insecure,no_root_squash,no_subtree_check,fsid=0)
```

**Comment by gavlooth** [comment]
Still, i get the same complain

**Comment by gavlooth** [comment]
By the way using sandbox on an overlay folder have works

**Comment by gavlooth** [comment]
like setting up an overlay folder and then sandboxing

**Comment by gavlooth** [comment]
This has worked before with a writeable container : sudo mount -t overlay -o lowerdir=./arangoDB,upperdir=./upper,workdir=./work overlay ./overlay-t

**Comment by cclerget** [comment]
does the following works :

```
cd /your/nfs/share
sudo dd if=/dev/zero of=overlay.img bs=1M count=64
sudo mkfs.ext3 overlay.img
loop=`sudo losetup -f overlay.img`
sudo /tmp/mount_test
for i in `seq 1 2`; do
    sudo mount -t ext3 $loop /mnt
    mkdir -f /mnt/upper /mnt/work
    sudo unshare -m mount -t overlay -o lowerdir=/,upperdir=/mnt/upper,workdir=/mnt/work /tmp/mount_test
    sudo umount /mnt
done
```

Also please paste `dmesg` command output if there is overlay kernel message

**Comment by gavlooth** [comment]
I am not sure that i understand, but  losetup -f overlay.img doesnt return anything, hence the mount command complains that it cannot find the folder in /etc/fstab 
however grepping dmesg for overlay bloats the screen : 

[  340.730500] overlayfs: failed to verify origin (/overlay-lowerdir, ino=86124, err=-116)
[  340.730512] overlayfs: failed to verify upper root origin
[  882.531649] overlayfs: upperdir is in-use as upperdir/workdir of another mount, mount with '-o index=off' to override exclusive upperdir protection.
[  892.603382] overlayfs: failed to verify origin (/overlay-lowerdir, ino=41671, err=-116)
[  892.603385] overlayfs: failed to verify upper root origin
[14607.171845] overlayfs: failed to verify origin (/overlay-lowerdir, ino=353133, err=-116)
[14607.171846] overlayfs: failed to verify upper root origin
[14647.845339] overlayfs: failed to verify origin (/overlay-lowerdir, ino=364894, err=-116)
[14647.845342] overlayfs: failed to verify upper root origin
[15040.802463] overlayfs: failed to verify origin (/overlay-lowerdir, ino=360933, err=-116)
[15040.802465] overlayfs: failed to verify upper root origin
[15595.361911] overlayfs: failed to verify origin (/overlay-lowerdir, ino=378251, err=-116)
[15595.361914] overlayfs: failed to verify upper root origin
[15644.802137] overlayfs: failed to verify origin (/overlay-lowerdir, ino=367345, err=-116)
[15644.802141] overlayfs: failed to verify upper root origin
[15977.664360] overlayfs: failed to verify origin (/overlay-lowerdir, ino=382236, err=-116)
[15977.664364] overlayfs: failed to verify upper root origin
[16114.594190] overlayfs: failed to verify origin (/overlay-lowerdir, ino=396405, err=-116)
[16114.594193] overlayfs: failed to verify upper root origin
[16158.274500] overlayfs: failed to verify origin (/overlay-lowerdir, ino=391437, err=-116)
[16158.274505] overlayfs: failed to verify upper root origin

**Comment by gavlooth** [comment]
i can mount the file with -o loop option although

**Comment by gavlooth** [comment]
and i got mount: /tmp/mount_test: mount(2) system call failed: Stale file handle.

**Comment by gavlooth** [comment]
I didn't use /mnt of course, i have staff mounted there, so i did 
 sudo mount -o loop overlay.img mnt                        
and then 
created /tmp/mount_test
and then
 sudo unshare -m mount -t overlay -o lowerdir=/,upperdir=./mnt/upper,workdir=./mnt/work /tmp/mount_test 
Of course all these with the export options, we discassed before

**Comment by cclerget** [comment]
`dmesg` gave useful information, here the explanation from overlay kernel documentation :

> With the "inodes index" feature, on the first time mount, an NFS file
handle of the lower layer root directory, along with the UUID of the lower
filesystem, are encoded and stored in the "trusted.overlay.origin" extended
attribute on the upper layer root directory.  On subsequent mount attempts,
the lower root directory file handle and lower filesystem UUID are compared
to the stored origin in upper root directory.  On failure to verify the
lower root origin, mount will fail with ESTALE.  An overlayfs mount with
"inodes index" enabled will fail with EOPNOTSUPP if the lower filesystem
does not support NFS export, lower filesystem does not have a valid UUID or
if the upper filesystem does not support extended attributes.

Just to confirm can you also paste output of `grep OVERLAY /boot/config-$(uname -r)`

**Comment by gavlooth** [comment]
Sorry, I dont follow /boot/config-5.3.4-arch1-1-ARC doesn't exist. What file do you want me to grep ?

**Comment by gavlooth** [comment]
There doesnt seem to be anything that matches an overlay string under /boot/ folder

**Comment by Gavlooth** [comment]
If you want the info on overlay fs module in the kernel: 

filename:       /lib/modules/5.3.4-arch1-1-ARCH/kernel/fs/overlayfs/overlay.ko.xz
alias:          fs-overlay
license:        GPL
description:    Overlay filesystem
author:         Miklos Szeredi <miklos@szeredi.hu>
srcversion:     BC41CE7BF55CB3EAAAC1FB3
depends:        
retpoline:      Y
intree:         Y
name:           overlay
vermagic:       5.3.4-arch1-1-ARCH SMP preempt mod_unload 
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        3F:B7:4F:DD:C0:CA:35:DC:B5:D5:AC:A7:FA:B6:D5:AC:4A:8D:AB:A7
sig_hashalgo:   sha512
signature:      8B:82:9A:4D:F1:C8:4A:6B:8A:88:DF:0D:41:D3:DC:77:30:4A:9A:97:
		D0:A1:3F:CC:07:40:16:74:3E:CB:F1:7C:CC:01:0F:BB:C0:3C:3A:C8:
		48:D3:66:43:BC:C5:38:42:CB:42:EB:4D:D1:4F:3B:6B:90:AB:2A:47:
		42:B7:77:D6:76:B8:DF:79:C4:90:2F:2B:6C:A3:78:FB:16:98:E8:EE:
		5A:69:22:27:49:A8:F3:5A:BE:9B:5B:01:B4:28:21:06:6F:A4:0A:BA:
		70:AC:2B:4A:15:7E:A7:1F:5D:BF:EA:97:C2:40:4D:61:6C:5A:E2:2F:
		EF:BA:19:DF:5F:5E:CA:58:EB:28:E8:D6:E8:87:2E:88:6C:74:D9:89:
		66:C5:92:C1:22:8E:75:EE:D6:7E:13:62:04:53:4A:E7:02:D8:2A:3A:
		77:BC:2D:29:27:0E:22:0B:7E:24:8E:4F:FB:3E:92:71:D4:F3:50:B4:
		C5:5D:76:8C:71:48:F9:44:1C:8E:B5:B5:B3:F1:B1:3B:5C:BC:23:DE:
		51:2C:A6:82:AC:7D:C3:72:FE:FB:83:FF:32:B9:24:61:87:F1:AD:40:
		BC:21:13:5A:67:C9:F0:C6:F1:E4:7C:6B:F1:3C:BF:9F:6C:EA:1F:E1:
		53:49:4E:EC:36:48:94:C1:48:BB:02:67:7D:0C:F6:43:BA:48:AD:90:
		BF:3B:B8:5B:23:FB:6A:BF:71:CF:93:EE:CC:EB:FE:A2:2C:B8:95:92:
		83:0C:10:82:0F:C4:70:4C:06:4F:D0:5F:D4:EC:D1:B7:D2:9D:0E:25:
		7B:DB:B6:8B:1E:72:2F:14:B2:02:5C:87:81:66:AC:BA:90:82:C2:5B:
		B9:67:07:F5:F8:05:87:43:F3:20:90:AD:E7:3B:37:BD:69:B8:4D:01:
		8E:92:F5:06:17:8B:30:B0:DD:70:D3:B5:2C:6D:08:1A:27:E5:4C:5D:
		71:5C:FA:C9:C5:15:0E:16:89:42:51:2F:27:A8:D1:8D:23:49:88:36:
		8B:1F:B5:ED:2B:26:A8:94:20:63:0D:31:1E:67:AC:19:8F:8E:AD:DB:
		B3:92:10:69:14:DD:B9:AD:2A:41:69:DA:0C:B7:EE:56:A4:44:79:EA:
		17:6B:98:2C:4B:45:5C:6C:7B:44:47:66:94:C2:5A:7A:FF:12:BF:EC:
		16:A3:D2:81:59:E9:01:01:1C:35:15:DD:AD:7D:24:1C:31:7A:8C:6C:
		91:98:CF:95:57:5C:BA:49:94:8B:60:6C:F5:E9:9E:CB:E1:9F:67:9A:
		02:7D:B1:B8:50:03:F5:03:85:CB:90:D8:B7:41:18:19:55:69:C5:56:
		30:08:F8:C7:B5:26:95:70:D2:87:8E:1E
parm:           check_copy_up:Obsolete; does nothing
parm:           redirect_max:Maximum length of absolute redirect xattr value (ushort)
parm:           redirect_dir:Default to on or off for the redirect_dir feature (bool)
parm:           redirect_always_follow:Follow redirects even if redirect_dir feature is turned off (bool)
parm:           index:Default to on or off for the inodes index feature (bool)
parm:           nfs_export:Default to on or off for the NFS export feature (bool)
parm:           xino_auto:Auto enable xino feature (bool)
parm:           metacopy:Default to on or off for the metadata only copy up feature (bool)

**Comment by gavlooth** [comment]
This is the modprob overlay: 
filename:       /lib/modules/5.3.4-arch1-1-ARCH/kernel/fs/overlayfs/overlay.ko.xz
alias:          fs-overlay
license:        GPL
description:    Overlay filesystem
author:         Miklos Szeredi <miklos@szeredi.hu>
srcversion:     BC41CE7BF55CB3EAAAC1FB3
depends:        
retpoline:      Y
intree:         Y
name:           overlay
vermagic:       5.3.4-arch1-1-ARCH SMP preempt mod_unload 
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        
sig_hashalgo:   sha512
 parm:           check_copy_up:Obsolete; does nothing                                                                                                                                                            
 43 parm:           redirect_max:Maximum length of absolute redirect xattr value (ushort)                                                                                                                           
 44 parm:           redirect_dir:Default to on or off for the redirect_dir feature (bool)                                                                                                                           
 45 parm:           redirect_always_follow:Follow redirects even if redirect_dir feature is turned off (bool)                                                                                                       
 46 parm:           index:Default to on or off for the inodes index feature (bool)                                                                                                                                  
 47 parm:           nfs_export:Default to on or off for the NFS export feature (bool)                                                                                                                               
 48 parm:           xino_auto:Auto enable xino feature (bool)                                                                                                                                                       
 49 parm:           metacopy:Default to on or off for the metadata only copy up feature (bool)

**Comment by cclerget** [comment]
It was to see if `CONFIG_OVERLAY_FS_INDEX` was set because when set overlay automatically set `index=on`, and I was able to reproduce the issue by forcing overlay option `index=on` in Singularity.

So basically the fix would be to add `index=off` when Singularity mount the overlay, but according to the documentation there is another case where `stale NFS file handle` could be returned when `metacopy=on`.

Work on the fix

**Comment by cclerget** [comment]
@Gavlooth Can you give a try to fix #4603 and let me know if that fix the issue. Thanks !

**Comment by gavlooth** [comment]
Sure, i will do and tell you the results

**Comment by gavlooth** [comment]
@cclerget  It works, i can now remount the overlay file

**Comment by gavlooth** [comment]
I think you can close the issue
