### ISSUE TITLE
Crash when using Python multiprocessing.pool

### ISSUE THREAD

**Issue by fmorency** [apptainer/singularity#455]
[python_multiprocessing_singularity_crash.zip](https://github.com/singularityware/singularity/files/709294/python_multiprocessing_singularity_crash.zip)

Python 2.7.6
Ubuntu 14.04
Singularity 2.2

Create a new image using the attached files. Open a singularity shell, `cd /` and `python multi.py`. The script will crash with an `OSError` exception.

The `multi.py` script comes from https://docs.python.org/2/library/multiprocessing.html#using-a-pool-of-workers

**Comment by vsoch** [comment]
trying this out now!

**Comment by vsoch** [comment]
ok, so I can't reproduce the error, but I think I might know the issue. When you cd into the image, I think you are (possibly) still using the python on your (local machine) path. For example, when I do `which python` after cd-ing  into my image, I see:

      Singularity.multi.img> $ which python
      /home/vanessa/anaconda3/bin/python

So inside the image you would want to call the python path directly:

	Singularity.multi.img> $ /usr/bin/python multi.py
	[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
	0
	1
	4
	9
	25
	16
	36
	49
	64
	81
	400
	11559
	[11558, 11561, 11560, 11559]
	We lacked patience and got a multiprocessing.TimeoutError

So to do this in the spec as a runscript, for example, you would do something like:

	Bootstrap:docker
	From:python:2.7

	%runscript

	      exec /usr/bin/python "$@"

and then run from outside the container (being sure you are using the python inside) like:

      ./multi.img multi.py

and without the multi.py, you go right into python. Take a look at the above, give it a try, and let me know if it solves the issue!

**Comment by fmorency** [comment]
The `python` executable on this computer is located in `/usr/bin/python`. When I shell into the image and `which python`, it returns `/usr/bin/python` and the crash occurs even if a prepend the path. @vsoch, does `/usr/bin/python` exists the computer you tested on?

**Comment by vsoch** [comment]
The image you are bootstrapping, ubuntu 14.04, doesn't seem to have it:


        singularity shell docker://ubuntu:14.04

blablabla download make image... shell...

	Singularity.ubuntu:14.04> which python
	Singularity.ubuntu:14.04> which python3
	/usr/bin/python3
	Singularity.ubuntu:14.04> ls /usr/bin/py*
	/usr/bin/py3clean     /usr/bin/pydoc3	     /usr/bin/python3
	/usr/bin/py3compile   /usr/bin/pydoc3.4      /usr/bin/python3.4
	/usr/bin/py3versions  /usr/bin/pygettext3    /usr/bin/python3.4m
	/usr/bin/pybuild      /usr/bin/pygettext3.4  /usr/bin/python3m

So I think the /usr/bin/python you are using is on your local path. I would try the spec I made about (with python inside) to see if that fixes the issue.

**Comment by fmorency** [comment]
I tried the spec and still have the crash. Just to make sure, I tried creating, bootstrapping and running the image on an Ubuntu14.04 base OS and I still have the crash. What base OS and what Singularity version are you running @vsoch?

**Comment by fmorency** [comment]
After investigating with @sbutcher, it seems to crash on Ubuntu (14.04) + Ubuntu (14.04) and Ubuntu (14.04) + CentOS (7). He could reproduce the crash.

**Comment by fmorency** [comment]
I found an old docker issue [1] about `/dev/shm` not being mounted. After mounting it manually inside the container, the attached script executes correctly.

  [1]: https://github.com/docker/docker/issues/1683

**Comment by fmorency** [comment]
It would seems that `/dev/shm` is a symlink to `/run/shm` on Ubuntu 14.04. Adding `bind path = /run` to `singularity.conf` fixes the issue.

**Comment by gmkurtzer** [comment]
What is the current status of this?

**Comment by fmorency** [comment]
Solved using fix above!

**Comment by vsoch** [comment]
Awesome! I'm going to close then. Is it just me, or in the time I flew from E --> W Github changed their default font back to something that looks like Ubuntu? :scream:
