### ISSUE TITLE
docker-daemon:// builder does not clean up all of its tempfiles.

### ISSUE THREAD

**Issue by robertu94** [apptainer/singularity#4560]
### Version of Singularity:

What version of Singularity are you using? 
```
$ singularity version
3.4.0-1
```

```
$docker version
docker version
Password: 
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.12.9
 Git commit:        039a7df
 Built:             Tue Sep 24 13:23:49 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.9
  Git commit:       039a7df
  Built:            Tue Sep 24 13:23:15 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
### Expected behavior

What did you expect to see when you do...?

When you build an image using the `docker-daemon://` builder it should at a minimum temp files created by this process should be cleaned up by `singularity cache clean` or a similar command, but I can't seem to find one.  Preferably it would just get cleaned up when the build finishes without an additional command

### Actual behavior

What actually happend? Why was it incorrect?

`singularity build $img docker-daemon://$docker_container_name` leave a potentially large file(s) in `/var/tmp/docker-tar-${some_hash}` 

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

build any container using the `docker-daemon://` builder

### What OS/distro are you running

```
$ cat /etc/os-release 
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

### How did you install Singularity

Installed from source using an [ebuild that I wrote](https://bugs.gentoo.org/694048) since the upstream one hasn't been updated in a while.  I'm trying to get it merged.

**Comment by dtrudg** [comment]
The `docker-tar-` file is created by the `containers/image` library rather than singularity itself:

https://github.com/containers/image/blob/9f348257042f51f35b8226b5fbb14d0bfe84468e/docker/tarfile/src.go#L77

There is a deferred cleanup.. but we need to see why that doesn't seem to be working:

https://github.com/containers/image/blob/9f348257042f51f35b8226b5fbb14d0bfe84468e/docker/tarfile/src.go#L86

**Comment by flaviut** [comment]
That only cleans up the file in the case that there's an error in opening it.

To delete the file after it is done being used, the `Source`'s `Close()` must be called: https://github.com/containers/image/blob/9f348257042f51f35b8226b5fbb14d0bfe84468e/docker/tarfile/src.go#L265-L270

**Comment by dtrudg** [comment]
Ahh - thanks @flaviut  - I'd missed that. That's an easy fix. Cheers.

**Comment by dtrudg** [comment]
Actually - looking further, this isn't something to call from our code.

We are using `Copy.Image` which takes `ImageRef`, not `Source`. Within `Copy.Image` there is a deferred `Close()` of the raw source:

https://github.com/containers/image/blob/9f348257042f51f35b8226b5fbb14d0bfe84468e/copy/copy.go#L156
