### ISSUE TITLE
Cannot unmarshal number into Go value of type client.ShubAPIResponse

### ISSUE THREAD

**Issue by sarusso** [apptainer/singularity#4563]
### Version of Singularity:

```
3.4.1-1
```

### Expected behavior

When I build and image I expect it to be successfully built or to receive a meaningful error message.

### Actual behavior

The building process fails with an error message that is not meaningful at all: "Cannot unmarshal number into Go value of type client.ShubAPIResponse".

Full (debug) output:

```
DEBUG   [U=0,P=1]          createConfDir()               Created /root/.singularity
DEBUG   [U=0,P=1]          getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /root/.singularity/cache
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /root/.singularity/cache/library
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /root/.singularity/cache/oci-tmp
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci-tmp
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /root/.singularity/cache/oci
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /root/.singularity/cache/net
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/net
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /root/.singularity/cache/shub
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/shub
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /root/.singularity/cache/oras
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oras
DEBUG   [U=0,P=1]          Init()                        Image format detection
DEBUG   [U=0,P=1]          Init()                        Check for sandbox image format
DEBUG   [U=0,P=1]          Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=1]          Init()                        Check for sif image format
DEBUG   [U=0,P=1]          Init()                        sif format initializer returned: can't read first 2048 bytes: %!s(<nil>)
DEBUG   [U=0,P=1]          Init()                        Check for squashfs image format
DEBUG   [U=0,P=1]          Init()                        squashfs format initializer returned: can't read first 2048 bytes: %!s(<nil>)
DEBUG   [U=0,P=1]          Init()                        Check for ext3 image format
DEBUG   [U=0,P=1]          Init()                        ext3 format initializer returned: can't read first 2048 bytes: %!s(<nil>)
DEBUG   [U=0,P=1]          bundleCommon()                Created temporary directory for bundle /tmp/sbuild-612380154
DEBUG   [U=0,P=1]          ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=0,P=1]          ensureGzipComp()              Gzip compression by default ensured
INFO    [U=0,P=1]          Full()                        Starting build...
DEBUG   [U=0,P=1]          Get()                         Getting container from Shub
DEBUG   [U=0,P=1]          GetManifest()                 shub request: https://singularity-hub.org/api/container/singularityhub/ubuntu:latest
DEBUG   [U=0,P=1]          GetManifest()                 200 OK response received, beginning manifest download
DEBUG   [U=0,P=1]          GetManifest()                 manifest image name: 
DEBUG   [U=0,P=1]          cleanUp()                     Build bundle(s) cleaned: [/tmp/sbuild-612380154]
FATAL   [U=0,P=1]          run()                         While performing build: conveyor failed to get: failed to get manifest for: shub://singularityhub/ubuntu: json: cannot unmarshal number into Go value of type client.ShubAPIResponse
```

### Steps to reproduce this behavior

```
$ git clone https://github.com/singularityhub/singularity-docker.git
$ cd singularity-docker/
$ git checkout v3.4.1
$ docker build . -t singularity-2ea5ad5
$ echo "Bootstrap: shub" > testimage.def
$ echo "From: singularityhub/ubuntu" >> testimage.def
$ docker run --privileged -v $PWD:/data -ti singularity-2ea5ad5 --debug  build /data/testimage.simg /data/testimage.def
```

### What OS/distro are you running

```
MacOS 10.11.6 (15G22010)
Docker for Mac Version 17.06.1-ce-mac24 (18950), Channel: stable (54dc09c3e3)
```

### How did you install Singularity

See section "Steps to reproduce this behavior" above.

**Comment by dtrudg** [comment]
Hi @sarusso - the shub service is not replying with the format of response that Singularity expects. It seems to be returning just the number `400` which looks like an HTTP bad request error code. It may be that the rate limits that were put in place on shub have been exceeded - but I'm not certain.

Singularity hub is run by @vsoch - V, are you able to provide any info on this?

**Comment by vsoch** [comment]
Well, there is no image called `singularityhub/ubuntu` - that might be the first issue. I'd leave as is, but try changing the deffile to be:

```
Bootstrap: docker
From: ubuntu:18.04
```

**Comment by vsoch** [comment]
You also don't need to build the bases yourself, unless you are changing something up. https://quay.io/repository/singularity/singularity?tab=tags

**Comment by sarusso** [comment]
Thank you @dctrud and @vsoch!

That image name is from https://singularity.lbl.gov/quickstart (I know that the doc is now on https://sylabs.io but hey, that come up with Google as first result when searching for a demo recipe..).

I suspected that there must have been something wrong in an http response somewhere and that there was probably no image "singularityhub/ubuntu" anymore (same for "vsoch/hello-world" I guess?), but I had no idea how to check, thanks for confirming this.

So I changed in:

```
Bootstrap: library
From: debian:9
```

...and I was able to build my image. 

However, it took me quite a while to figure out what the problem was as the error message really does not say much, and I thought it was nice to let you devs to know about the issue I experienced (the error reporting, I mean).

p.s. I am experimenting a bit at the moment so I need to build the bases by myself :)

**Comment by vsoch** [comment]
okay no worries! Yes the quickstart is definitely a few years old - I've re-designed Singularity Hub 3 times since then, and @dctrud is right we've had to place a lot more rate and general access limits (there was a bit of abuse of pulling this summer). 

`vsoch/hello-world` does in fact exist, but since the Sylabs folks (and others I suspect) use it for testing, it's hit it's weekly pull limit:

```python
container = Container.objects.get(name="vsoch/hello-world")

container.get_count
# 50

container.get_limit
# 50
```

If everyone did simple pull of the binary and then use, we wouldn't have issues with the limits (for most containers). For testing frameworks, you tend to see many pulls per run, so the limit gets hit fairly fast. I left it completely limit free as long as I could, but unfortunately had to do this to protect the longevity of the service.

**Comment by dtrudg** [comment]
(off-topic)
Hi @vsoch - we're actually `t.Skip("Skipping tests that access singularity hub")`still at present.
We use `shub://ikaneshiro/singularityhub:latest` if those tests are running. We need to reach out to you about how to enable this without getting hit with rate limiting at some point soon. We would definitely be over 50 per week, as there are multiple tests, that run multiple times from different CI configs each time CI is triggered.

**Comment by vsoch** [comment]
@dctrud I want to loop in @ArangoGutierrez here - we discussed some time ago a solution for this - adding user tokens to Singularity Hub, so that you could (via an authenticated request) minimally increase the rate limit (akin to how GitHub does it's API). I'm definitely willing to implement this if it would be a solution to this issue.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
