### ISSUE TITLE
Run a container with --without-suid on Singularity 3.4.1

### ISSUE THREAD

**Issue by alazzaro** [apptainer/singularity#4575]
### Expected behavior

It should run out-of-the-box with

`singularity run my_image/`

(note that I'm using a sandbox image)

### Actual behavior

```
singularity run dbcsr_phase2_fakeroot.imgdir/
ERROR  : Failed to set effective UID to 0
```

What actually happend? Why was it incorrect?

With 3.1 and 3.2 it works.
For 3.4.1 I have to specify `-u` to get it to work, i.e.

```
singularity run -u my_image
```

I wonder if this is expected or it should still run out-of-the-box without explicitly set `-u`.

### Steps to reproduce this behavior

Just install Singularity with `--without-suid` and run a sandbox image.

### What OS/distro are you running

Ubuntu 19.04

### How did you install Singularity

git clone https://github.com/sylabs/singularity.git
cd singularity
git checkout v3.4.1
./mconfig --prefix=/opt/singularity_install --without-suid
make -C ./builddir
make -C ./builddir install

**Comment by cclerget** [comment]
Hi @alazzaro , it was fixed by #4540 and will be included in 3.4.2, but you can already grab changes merged in release-3.4 branch. I'm closing the issue as already fixed
