### ISSUE TITLE
[Regression] Unable to pull SLC6 from DockerHub: packer failed to pack: while unpacking tmpfs: unpack layer: unpack entry: .: apply hdr metadata: restore xattr metadata: saw forbidden xattr "security.selinux":

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#4578]
### Version of Singularity:

```
singularity version 3.4.1-1.1.el7
```

It worked fine with `3.2.1-1.1.el7`, so that's a regression. 

### Expected behavior

Using `SL6.def` containing the following:
```
BootStrap: docker
From: cern/slc6-base:latest
```
I'd expect this:
```
$ singularity build foo.sif SL6.def
```
to work. 

### Actual behavior

```
$ singularity build foo.sif SL6.def 
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:5fb95acba89baff8fc06e9f83ac042b15437a69b1c8cb494846ced8f95e35080
Copying config sha256:b0486bbac8a1e7810ca22fd74038374a4320629b70cb7c431e1bcbf6eaebe94d
 375 B / 375 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
2019/10/04 15:55:43  info unpack layer: sha256:5fb95acba89baff8fc06e9f83ac042b15437a69b1c8cb494846ced8f95e35080
FATAL:   While performing build: packer failed to pack: while unpacking tmpfs: unpack layer: unpack entry: .: apply hdr metadata: restore xattr metadata: saw forbidden xattr "security.selinux": .
```

### What OS/distro are you running

```
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core) 
Release:        7.7.1908
Codename:       Core
```

### How did you install Singularity

EPEL

**Comment by dtrudg** [comment]
I don't believe this will be fixed by what is already in `release-3.4` for the upcoming `3.4.2`. Need to investigate further.

**Comment by dtrudg** [comment]
Confirmed this replicates on current `release-3.4` on my Debian host.

**Comment by dtrudg** [comment]
So this is a nasty one to deal with. The `umoci` library we are using now to more faithfully extract docker layers will set permissions, xattrs more faithfully than the previous `image-tools` library. When umoci is used to create a layer tar it will ignore "security.selinux" xattrs, which are host specific:

https://github.com/openSUSE/umoci/blob/4fc9627cfc26f9e2a2af67662cb1e3381d4580f6/oci/layer/tar_generate.go#L40

When extracting a layer tar, umoci isn't expecting to see an "security.selinux" xattrs - and if there is one in the tar that is a modification of what's already on disk, it will error out:

https://github.com/openSUSE/umoci/blob/4fc9627cfc26f9e2a2af67662cb1e3381d4580f6/oci/layer/tar_extract.go#L160

There is some background in this issue: https://github.com/openSUSE/umoci/issues/235 - we appear to be seeing something that isn't fixed by the referenced PR or 0.4.2 release.

@olifre - do you know how this CERN SLC6 docker image is created?

**Comment by olifre** [comment]
@dctrud Thanks for the background! Sadly, I do neither know how exactly the image is built, nor could I make out an immediate contact person... 
@DrDaveD Do you happen to know who provides the SLC6 docker images, by chance?

**Comment by olifre** [comment]
@dctrud: I _guess_ this is the actual source:
https://gitlab.cern.ch/linuxsupport/slc6-base
Seems to be build via Koji using a Kickstart file.

**Comment by dtrudg** [comment]
I guess they maybe are using an old koji/imagefactory? The Red Hat imagefactory docker plugin code in the upstream repo (koji will be using imagefactory to create the tar) shows that they do not include xattrs because of selinux issues:

https://github.com/redhat-imaging/imagefactory/commit/8c61f3e2c494771a23f2649360c3f6528fbcfe73

**Comment by olifre** [comment]
That's not unlikely. I can access the Koji build status page via the CERN network, but can't make out any version anywhere, sadly. It's at least RHEL 7 based, though, since they use RHEL7 Kickstart syntax. 
I doubt upgrading the central CERN Koji instance would be a quick solution, and arguably, it would be best to not depend on specifics of the image generation, but handle existing selinux xattrs gracefully. That's probably an umoci issue, then?

**Comment by dtrudg** [comment]
I can raise this on the umoci GitHub repo - but I suspect it will probably be kicked back from there, since the upstream imagefactory build tool explicitly has a note around excluding them. We can see though. I'm afraid this is unlikely to be into a `3.4.2` as we have things that are probably hitting more users we need to get out there before we'd be able to do to and from on this to see where a fix will fit.

**Comment by dtrudg** [comment]
I just had a thought r.e. a workaround. If you can use `--fakeroot` for the build it will work, as umoci rootless extractions are just plain ignoring the xattr.

```
dave@piran~/4578> singularity build --fakeroot foo.sif SL6.def
Build target already exists. Do you want to overwrite? [N/y] y
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:5fb95acba89baff8fc06e9f83ac042b15437a69b1c8cb494846ced8f95e35080
 76.61 MiB / 76.61 MiB [====================================================] 6s
Copying config sha256:b0486bbac8a1e7810ca22fd74038374a4320629b70cb7c431e1bcbf6eaebe94d
 375 B / 375 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
2019/10/04 11:25:16  info unpack layer: sha256:5fb95acba89baff8fc06e9f83ac042b15437a69b1c8cb494846ced8f95e35080
...

2019/10/04 11:25:18  warn rootless{etc/.pwd.lock} ignoring forbidden xattr: "security.selinux"
2019/10/04 11:25:18  warn rootless{etc/group} ignoring forbidden xattr: "security.selinux"
INFO:    Creating SIF file...
INFO:    Build complete: foo.sif
```

**Comment by olifre** [comment]
> I can raise this on the umoci GitHub repo - but I suspect it will probably be kicked back from there, since the upstream imagefactory build tool explicitly has a note around excluding them.

That would be good. I understand the upstream imagefactory is adapted, but since umoci should be a general tool, it should handle "everything" sensible in my opinion. But let's see how it goes. 



> I'm afraid this is unlikely to be into a `3.4.2` as we have things that are probably hitting more users we need to get out there before we'd be able to do to and from on this to see where a fix will fit.

I understand, we are also hit by other regressions which are already fixed in `release-3.4`, so we are in any case looking forward to 3.4.2. However, SLC6 not working as a base may hinder us from upgrading.

**Comment by olifre** [comment]
> If you can use `--fakeroot` for the build it will work, as umoci rootless extractions are just plain ignoring the xattr.

Nice! That's a good find. I'll give that a go. I still think raising an umoci issue is best, but if fakeroot works, this should be fine as a workaround for now.

**Comment by olifre** [comment]
@dctrud Did you already open an umoci issue? If so, I'd love to follow along :wink:.

**Comment by dtrudg** [comment]
Hi @olifre - sorry, not yet... some other things came up that seemed at least tangentially related and I'm trying to get it all straight in my head so I don't go into there with something incoherent :-)

I think I now have 2 issues to open on the umoci repo... am going to sleep on my notes from today and then definitely do it tomorrow morning(!)

**Comment by dtrudg** [comment]
Hi @olifre - I've reported upstream and have also opened PR #4624 for testing / verification of a possible fix on this (and #4593).

If you are able to test PR #4624 and verify it fixes the issue for you that would be much appreciated!

**Comment by olifre** [comment]
@dctrud Many thanks, that's much appreciated!
I'm currently travelling so I can not test easily. I might squeeze it in tomorrow, if not, testing will have to wait until the weekend or latest next week when I am back.

**Comment by olifre** [comment]
@dctrud Unexpectedly, I managed to do the test right now, cutting back a bit on sleep :wink:. 
It now seems to work as expected! I get a ton of these:
```
2019/10/17 01:39:20  warn xatt{etc/modprobe.d/anaconda.conf} ignoring forbidden xattr: "security.selinux"
2019/10/17 01:39:20  warn xatt{etc/modprobe.d/dist.conf} ignoring forbidden xattr: "security.selinux"
2019/10/17 01:39:20  warn xatt{etc/modprobe.d/dist-oss.conf} ignoring forbidden xattr: "security.selinux"
2019/10/17 01:39:20  warn xatt{etc/mtab} ignoring forbidden xattr: "security.selinux"
2019/10/17 01:39:20  warn xatt{etc/gcrypt} ignoring forbidden xattr: "security.selinux"
```
but these are of course expected with the patch you developed. 
Thanks!

**Comment by dtrudg** [comment]
This change is being upstreamed in https://github.com/openSUSE/umoci/pull/304

We will unfortunately need a `v0.4.2+singularity` fork (at least temporarily) with the patches, due to conflicts between the newer `image-spec` that newer umoci brings in vs CNI things and more :-( see #4209

**Comment by olifre** [comment]
@dctrud Nice, thanks for the effort, good to see this go upstream! 
At least the fork is likely temporarily then :smile:
