### ISSUE TITLE
support for restricting image locations

### ISSUE THREAD

**Issue by boegel** [apptainer/singularity#458]
We have some concern on the location where (large) container images are being served from, due to the potential increased load that would cause on e.g., NFS-mounted filesystems (especially w.r.t. MPI jobs leveraging Singularity containers).

To mitigate that, we would like to hardcode a restriction for the image location into the `singularity` command somehow (preferably leaving no option to dance around this for the user).

The only way to make this a hard restriction is probably to patch the code where the image is now being read, and to include an (optional) check with a regex on the absolute path to the image (after resolving symlinks)?

Is that something that would be a general interest?

**Comment by alvarosimon** [comment]
maybe it could be included as a new `singularity.conf` optional variable like:

> allow image path = /home
> allow image path = /mnt/nfs

or something like that? singularity will only use the images located from these paths.

**Comment by gmkurtzer** [comment]
I mentioned in the Slack, but figured it might be better here... How about writing a simple case statement inside of `$sysconfdir/singularity/init` that evaluates the container's path and bombs out if it doesn't match.

**Comment by boegel** [comment]
@gmkurtzer I guess that's worth looking into.

How easy would it be for users to figure out how to circumvent that?

**Comment by gmkurtzer** [comment]
Haha, depends on the user.

But considering user driven IO is not a Singularity specific problem, I am hesitant to making it a global/required feature. I think a nice warning message and exit from the system administrators on invocation should be a reasonable deterrent. If not, I'm also happy to help you develop a patch you can apply to your site (but I strongly think the first method is best).

**Comment by boegel** [comment]
OK, thanks for the feedback, I understand your reluctance in making this an actual feature.

We (well, @alvarosimon ;-)) will look into your `init` suggestion, and get back to you on this.

**Comment by alvarosimon** [comment]
@gmkurtzer so do you suggest something like this, for example:
```

DIR=$1
if [[ $DIR =~ /home/.+/singularity_images/ ]]; then
        echo "valid image path" 
    else
        echo "not valid image path"
        exit
fi
```
I took a look which singularity variables are set during `/etc/singularity/init`  execution, I got this:

> SINGULARITY_libexecdir=/usr/local/libexec
> SINGULARITY_COMMAND=shell
> SINGULARITY_localstatedir=/usr/local/var
> SINGULARITY_sysconfdir=/etc

maybe it could be a good idea also to set `SINGULARITY_image`    to include the image name with the absolute path, what do you think?

**Comment by bbockelm** [comment]
Have you looked into the feature that blocks user-managed images?  That would allow you to only allow the images created by the sysadmin.  Or is that too restrictive for this use case?

**Comment by boegel** [comment]
@bbockelm that sounds too restrictive... In fact, we'd like to stay way from providing images ourselves, but have some control of where users are putting images (for live use), to avoid them trashing our (no-scratch) filesystems.

**Comment by bbockelm** [comment]
Greg and I were talking about allowing a customization point for processing images.  It would allow sites to implement their own handlers for URLs (i.e., if you have a custom way to process `https://`).

I wasn't thinking about using this for banning things, but would that apply here?

**Comment by boegel** [comment]
I guess, if you consider local filepaths to be a URL. ;)

**Comment by gmkurtzer** [comment]
@boegel Ohh, I thought for sure SINGULARITY_IMAGE was already being set, but you are right, they are not.

The code at lines 38-43 should really be moved to line 154 for the shell, exec, run and test cli/*.exec functions:

https://github.com/singularityware/singularity/blob/master/libexec/cli/shell.exec#L38

**Comment by alvarosimon** [comment]
@gmkurtzer ah yes that works, thanks :-). 
do you agree about this change to get `${SINGULARITY_IMAGE}` from init script? should we open a PR to change that?

**Comment by gmkurtzer** [comment]
Hi @alvarosimon, yep, PR's are always welcomed!

With that said, I committed a slight modification to the *exec cli scripts that change the time that `$sysconfdir/singularity/init` gets sourced after `${SINGULARITY_IMAGE:-}` has been defined:

https://github.com/singularityware/singularity/commit/6db7ad698b880e1f75395c1cfaf2bc490bebd8a2

Is more then that necessary?

note: the lib-refactor branch will end up being merged into the development branch which will end up being the foundation of the 2.3 general release.

**Comment by alvarosimon** [comment]
@gmkurtzer yes that's perfect 👍 
Now we can gather `$SINGULARITY_IMAGE`  from `init` script and expand the path with `realpath` for each image.

Thanks!

**Comment by alvarosimon** [comment]
@gmkurtzer this is also another proposal and it is also related with this ticket. Right now is trivial for the user to bypass any restriction regarding the environment or image location located at `init`  script, just typing:
```
$ export SINGULARITY_COMMAND=shell
$ export SINGULARITY_IMAGE=/home/user/centos7.img 
$ /usr/libexec/singularity/sexec
```
it would be possible to enforce init script environment from `sexec-suid`   or `sexec`  ?

**Comment by gmkurtzer** [comment]
You are right, it is trivial to bypass this... But I haven't been convinced yet that limiting the image location should be implemented generally because this is a user/usage issue and thus not limited to Singularity (e.g. what is stopping them from any computational IO on substandard paths?). So I see that using the `init` driver is simply a way to "recommend" appropriate use rather then enforce it.

I am of course open to be challenged on any of this. If you feel as though Singularity should support limiting images to a particular path natively, share your argument and perspective, I am open to it. It is a very easy feature to implement internally.

**Comment by alvarosimon** [comment]
@gmkurtzer yes I see your point of view, for the moment we can use `init`  script and we can try to change `singularity.conf` by our own to implement this kind of restrictions... I'm not sure if more sites are interested on this (probably not :-))

**Comment by gmkurtzer** [comment]
You know... I've been thinking about this. And it is such an easy feature to add and not use, it kinda makes sense for me just to create a module for that so nobody is hacking around with it in init. lol

**Comment by boegel** [comment]
@gmkurtzer :+1:

**Comment by alvarosimon** [comment]
@gmkurtzer great! thanks a lot for that 😄

**Comment by gmkurtzer** [comment]
Done. :)

Configuration looks like this:
```
# LIMIT CONTAINER PATHS: [STRING]
# DEFAULT: NULL
# Only allow containers to be used that are located within an allowed path
# prefix. If this configuration is undefined (commented or set to NULL),
# containers will be allowed to run from anywhere on the file system. This
# feature only applies when Singularity is running in SUID mode and the user is
# non-root.
#limit container paths = /scratch, /tmp, /global
```

This is currently in the lib-refactor branch. As soon as that stabilizes more it will end up in development branch, at which point upon release of 2.3, it will end up in master. Please close the issue if this looks satisfactory.

Thanks!

**Comment by alvarosimon** [comment]
@gmkurtzer awesome! I think @boegel should close this issue 😄

**Comment by boegel** [comment]
@gmkurtzer I couldn't really tell from the commit whether or not any symlink is the image path is being fully resolved?

Also, what we currently do is actually *blacklist* path location, rather than whitelist, which is easier since we're mostly trying to avoid that people use images that are located on an NFS-mounted location (of which there are only a few). To whitelist, we need to list `/scratch`, `/tmp`, `/dev/shm`, `/local`, `/var/tmp`, ... so it becomes a bit messier.

Not a big issue of course, we'll use whatever ends up in mainline (although the question about resolving symlinks is important since otherwise the requirement is trivial to bypass).

**Comment by gmkurtzer** [comment]
Yes, it is resolving the full path based on the file descriptor:

```bash
$ grep '^limit container paths' /etc/singularity/singularity.conf 
limit container paths = /scratch, /global, /home
$ ln -s /tmp/ubuntu.img .
$ singularity shell ubuntu.img 
ERROR  : Singularity image is not in an allowed configured path
ABORT  : Retval = 255
```

I think a whitelist (while I agree could be messier), is also more functional.. For example, the root user can say, only allow people to use/run containers in a particular directory that only has write access to a particular group of users (who then become the maintainers of the various containers). And I would prefer not to have both a white and a black list.

Thanks!

**Comment by gmkurtzer** [comment]
Closing this issue. If any problems become apparent, let me know and I will reopen.

**Comment by tashrifbillah** [comment]
Hi guys, I just wanted to point out a reason for which I ran into this issue:

```vim
[tb176@compute-a-16-170 ~]$ singularity shell py3.sif
FATAL:   singularity image is not in an allowed configured path
```

Somebody in my cluster put this line in the `/etc/singularity/singularity.conf` :

> 175 limit container paths = /n/app/singularity/containers, /n/groups/lsp/mcmicro/singularity

**Comment by dtrudg** [comment]
@tashrifbillah - yes, this is by design for sites that want to limit execution of containers on their system. Ideally sites who set this will inform users by documentation etc. so that they can anticipate issues / workarounds that might be needed for software using Singularity.
