### ISSUE TITLE
3.4.1 warnings about xattr should be turned off

### ISSUE THREAD

**Issue by afortiorama** [apptainer/singularity#4586]
### Version of Singularity:

```
singularity version 3.4.1-1.2.el7
```
### Expected behavior

I expect singularity to be silent if I use the -s flag and to print a minor number of warning without. In 3.2.1 with -s it executes and returns
```
-bash-4.2$ /cvmfs/atlas.cern.ch/repo/containers/sw/singularity/testing/x86_64-el7/3.2.1/bin/singularity -s build --sandbox /home/aforti/docker_atlas_analysisbase/image docker://atlas/analysisbase
-bash-4.2$ 
```

### Actual behavior

when building centos images singularity prints out an enormous level of warnings about ignoring xattr on files. It is only 3 on the basic OS image (which is already annoying) but with more complex  images I have >12k warnings polluting the stdout. This should really be hidden behind debugging and even there I'm afraid it is polluting, maybe not for a dev, but certainly for an admin. 

### Steps to reproduce this behavior
```
export SINGULARITY_CACHEDIR=docker_atlas_analysisbase/cache
export SINGULARITY_TMPDIR=docker_atlas_analysisbase
export SINGULARITY_DISABLE_CACHE=true

singularity -s build --sandbox /home/aforti/docker_atlas_analysisbase/image docker://atlas/analysisbase > 3.4.1-test.sing.silent.txt
```
I've attached the output of this command
[3.4.1-test.sing.silent.txt](https://github.com/sylabs/singularity/files/3701702/3.4.1-test.sing.silent.txt)

### What OS/distro are you running

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

rpm from epel-testing

**Comment by dtrudg** [comment]
We now use the https://github.com/openSUSE/umoci library to deal with OCI tarballs. The `xattr` related messages there are at the warning log level, so this is not currently trivial to hide.

In this case the warnings are regarding selinux xattrs. The general consensus is that docker layers should not be created with them. E.g. umoci will filter them out when creating a docker tar.gz

A related issue was raised on an Scientific Linux docker base image - which contains selinux labels. Upstream CentOS/RHEL docker images do not - the build process used explicitly filters them out. See https://github.com/sylabs/singularity/issues/4578

**Comment by afortiorama** [comment]
I think I've seen selinux errors too, but that is not the point. That amount of warning makes output files completely useless it should be possible to turn them off.

**Comment by dtrudg** [comment]
I'm afraid It's not possible for us to turn this off trivially right now in a way that wouldn't run the risk of hiding other important warnings. I'm going to raise an issue around #4578 with on the umoci repo, and can mention this too - but I suspect the upstream opinion might be that OCI layers should not contain `selinux` xattts, so the warnings are valid. This will need some thought and discussion.

**Comment by DrDaveD** [comment]
@dctrud I put a proposed fix in #4592.

**Comment by dtrudg** [comment]
Thanks - to clarify, the difficulty isn't necessarily with the `--silent` bit - we can do that by setting errors only on the apex logger used by umoci, as shown in #4592 

The issue that makes this difficult is wanting to hide or otherwise classify the `selinux` xattr warnings, while still enabling other umoci warnings / info etc levels to show as appropriate to the Singularity log level. We can't really do that without modifying the umoci code.

**Comment by afortiorama** [comment]
> Thanks - to clarify, the difficulty isn't necessarily with the --silent bit 

this is already a step forward. But the umoci people should put this a debug level. Many images will not comply with the decisions taken in OCI recently. Even the centos:7 official image has 3 warnings. And that's a skeleton OS.

**Comment by dtrudg** [comment]
As mentioned, I'll open an issue on the umoci repo, but the general feeling there seems to be that they should be replicating the content of a layer exactly when extracting it, and anything that cannot be replicated is warned. 

The PR #4592 which will silence the warnings for `-s / --silent` will be merged for the 3.4.2 release.

**Comment by afortiorama** [comment]
> The PR #4592 which will silence the warnings for -s / --silent will be merged for the 3.4.2 release.

Thanks

**Comment by dtrudg** [comment]
The change has also been cherry-picked into the master branch rather than waiting to merge from the final 3.4.2 release, so as not to cause issue with the upcoming change to Go 1.13 `go.mod` etc.

**Comment by dtrudg** [comment]
Since we now have `-s` working, and we are in alignment with the `umoci` warnings I'm going to close this. We are losing information in the extraction here, so I'm not really going to argue that `umoci` should set these to debug when it is a tool that aims for faithful extraction of layers.

If there are strong opinions about this I'd encourage users to make a case on the `openSUSE/umoci` issues page - as the volume of warnings will affect standalone users of umoci as well as Singularity.
