### ISSUE TITLE
Sandbox build failure in master branch -- packer failed to pack

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#4593]
### Version of Singularity:

The current master branch.

### Expected behavior

Sandbox builds from docker work as before, including with the umoci in releases 3.4.1.

### Actual behavior

Sandbox build dies with
```
FATAL:   While performing build: packer failed to pack: while unpacking tmpfs: unpack layer: unpack entry: anaconda-post.log: get dirHdr.Xattrs: unpriv.llistxattr: operation not supported
```

Similar error message to #4578, but that's a build from scratch and also affects 3.4.1.

### Steps to reproduce this behavior

```
$ singularity build --sandbox ~/scratch/centos7-sandbox docker://centos:7
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:d8d02d45731499028db01b6fa35475f91d230628b4e25fab8e3c015594dc3261
Copying config sha256:acab94af64effb1f7481666a37788e7a59465e723f0b0fe0a0f458f3f4856638
 1.05 KiB / 1.05 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
2019/10/08 16:00:14  info unpack layer: sha256:d8d02d45731499028db01b6fa35475f91d230628b4e25fab8e3c015594dc3261
FATAL:   While performing build: packer failed to pack: while unpacking tmpfs: unpack layer: unpack entry: anaconda-post.log: get dirHdr.Xattrs: unpriv.llistxattr: operation not supported
```

### What OS/distro are you running

```
NAME="Scientific Linux"
VERSION="7.7 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.7"
PRETTY_NAME="Scientific Linux 7.7 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.7:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
```

### How did you install Singularity

Compiled from master branch

**Comment by dtrudg** [comment]
I believe that this is currently expected on master. Master does not include the permission mangling code that is slated for 3.4.2. Because master builds direct to the final sandbox location, rather than using an `mv` we want to handle the permission issue in a much more targeted manner so that permissions in our containers are more faithful to the OCI layers.

**Comment by dtrudg** [comment]
What filesystem is your home dir under @DrDaveD ?

**Comment by dtrudg** [comment]
Noting that on ext4 home filesystem on a Debian host that I get a success on current master:

```
dave@piran~> singularity build --sandbox ~/scratch/centos7-sandbox docker://centos:7
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:d8d02d45731499028db01b6fa35475f91d230628b4e25fab8e3c015594dc3261
Copying config sha256:acab94af64effb1f7481666a37788e7a59465e723f0b0fe0a0f458f3f4856638
 1.05 KiB / 1.05 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
2019/10/08 16:17:46  info unpack layer: sha256:d8d02d45731499028db01b6fa35475f91d230628b4e25fab8e3c015594dc3261
2019/10/08 16:17:46  warn rootless{usr/bin/ping} ignoring (usually) harmless EPERM on setxattr "security.capability"
2019/10/08 16:17:47  warn rootless{usr/sbin/arping} ignoring (usually) harmless EPERM on setxattr "security.capability"
2019/10/08 16:17:47  warn rootless{usr/sbin/clockdiff} ignoring (usually) harmless EPERM on setxattr "security.capability"
INFO:    Creating sandbox directory...
INFO:    Build complete: /home/dave/scratch/centos7-sandbox
```

**Comment by DrDaveD** [comment]
My home filesystem is NFS

**Comment by dtrudg** [comment]
This works on  3.4.x generally as umoci will unpack to `/tmp` (if TEMPDIR isn't set otherwise) which usually supports xattrs, then will mv that to the final location. The `mv` won't break when the test doesn't support xattrs.

In master we are not extracting a sandbox to tmp and moving, but extracting it straight to the final destination.

I had thought this was covered for us by https://github.com/openSUSE/umoci/commit/88e46ad602e28cb6844a389e41a25e3d1c4c3b13 but need to work out where it is falling through.

**Comment by dtrudg** [comment]
Hi @DrDaveD - I've opened an issue in the upstream umoci repo around this issue, as well as a PR for their consideration.

Would you be able to try out the draft PR https://github.com/sylabs/singularity/pull/4624 here - which uses a personal fork of umoci for testing a fix?

Many thanks!

**Comment by DrDaveD** [comment]
I can try next week, on vacation this week.

**Comment by dtrudg** [comment]
This change is being upstreamed in https://github.com/openSUSE/umoci/pull/304

We will unfortunately need a `v0.4.2+singularity` fork (at least temporarily) with the patches, due to conflicts between the newer `image-spec` that newer umoci brings in vs CNI things and more :-( see #4209

**Comment by dtrudg** [comment]
I'm going to reopen this for now - until DrDave can 100% confirm it's a fix for him after vacation.

I have tested locally by using an fs with `noxattr` but further confirmation will be great to have.

**Comment by DrDaveD** [comment]
With the current master branch I no longer see the error listed in this issue.  I do see a zillion new warnings about `ignoring ENOTSUP`, so I killed it and re-ran with -s and it completed successfully.

**Comment by dtrudg** [comment]
@DrDaveD - I'm afraid those zillion warnings are currently expected. We are on a fork of `umoci` right now, so in theory we could patch to a lower log level - but we want to get back to upstream. I think we are not going to be successful asking them to be < warn there.... but I can ask.

**Comment by dtrudg** [comment]
actually @DrDaveD - how about I propose in `umoci` that only the first ENOTSUP is raised as a warning? As it's unlikely a filesystem will suddenly change it's mind about supporting extended attributes midway in an extraction. Maybe that's a reasonable compromise between our use, and any opinion upstream that a failure to replicate the tar content faithfully requiring a warning?

**Comment by DrDaveD** [comment]
That's reasonable.  Perhaps that could also apply to other similar warnings that appear many times.

**Comment by dtrudg** [comment]
Will tackle as #4662
