### ISSUE TITLE
Prevent creation of .singularity in user's $HOME directory

### ISSUE THREAD

**Issue by eds-slim** [apptainer/singularity#4596]
Hi,
I'm trying to run Singularity containers on a Centos HPC. Due to the setup of the cluster, batch jobs have no write permission in my $HOME directory.

This causes problems, as even `singularity help` tries to create a `.singularity` folder in my $HOME directory.

Setting `SINGULARITYENV_DISABLE_CACHE=1` or pointing `SINGULARITYENV_CACHEDIR` and `SINGULARITYENV_TMPCACHEDIR` to some other location does not have an effect. Maybe the issue is not cache-related because according to https://github.com/sylabs/singularity/issues/716#issuecomment-305885393 these setting should at least point the cache away from the home directory.

Is it possibly to invoke `singularity` without dreating any files in the user's $HOME directory?

**Comment by jscook2345** [comment]
I feel like this was just addressed recently but I can't recall.

**Comment by dtrudg** [comment]
This should be addressed in 3.4.x by https://github.com/sylabs/singularity/pull/4226 and some follow-ups.

@eds-slim - what version of Singularity are you using?

**Comment by eds-slim** [comment]
@dctrud @jscook2345 
On the cluster, we run
`bash-4.2$ singularity version
3.3.0-1`

on my local testing machine
`eds@Ixion:~$ singularity version
3.4.0-rc.1`,
same problem on both.
Is it already possible to install a version where this is addressed? Thanks!

**Comment by eds-slim** [comment]
Problem has been solved in 3.4.2-rc.1. Thanks.
