### ISSUE TITLE
remote centos7 yum build fails

### ISSUE THREAD

**Issue by skluth** [apptainer/singularity#4615]
### Version of Singularity:

What version of Singularity are you using? Run:

$ singularity version
bf5853e-dirty

skluth@pcatlas63:~/Downloads/singularity$ less VERSION 
3.4.1-1

### Expected behavior

The def file specifies a centos7 build based on yum, from the examples 
singularity/examples/centos/Singularity

### Actual behavior

What actually happend? Why was it incorrect?

skluth@pcatlas63:/mnt/scratch/skluth/container$ $HOME/Downloads/singularity/install/bin/singularity build --remote centos7-yum.sif /home/iwsatlas1/skluth/Downloads/singularity/examples/centos/Singularity 
INFO:    Remote "default" added.
INFO:    Authenticating with remote: default
INFO:    API Key Verified!
INFO:    Remote "default" now in use.
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: neither yum nor dnf in path
FATAL:   While performing build: build image size <= 0

### Steps to reproduce this behavior

Run the above (failing) command.

### What OS/distro are you running

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

From source tar.gz after compiling go1.11

**Comment by jscook2345** [comment]
Hello @skluth !

If the definition file requires `yum`, you will need to install `yum` on your `ubuntu` system so that the `singularity` can bootstrap your container image.

Let me know if you have further questions.

Thanks!

**Comment by skluth** [comment]
Hi, I forgot to say, I built singularity in user mode w/o suid capability (because I am user only, no root/sudo access). So installing yum on my ubuntu workstation is not possible either. The docs are not very detailed about the remote build process, I naively thought that simply the whole def file goes to your build service, the remote build service has everything needed for all possible def file variations and runs the build for me.

**Comment by dtrudg** [comment]
Since this is a remote build the local configuration isn't the issue here. The build process is running on the cloud service.

@EmmEff - can you advise if it's intended that the remote builder should / would support `yum` bootstrap?

**Comment by blancha** [comment]
I have the same issue running the build on RemoteFinder directly.
Any fixes available?

Build:
Bootstrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum

Error message:
INFO:    API Key Verified!
INFO:    Remote "default" now in use.
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: neither yum nor dnf in path

Thanks.

**Comment by EmmEff** [comment]
This issue should now be resolved on `cloud.sylabs.io`
