### ISSUE TITLE
What's the Right Way to get write access to the system files of a container on a system where you don't have root?

### ISSUE THREAD

**Issue by adamnovak** [apptainer/singularity#4617]
### Version of Singularity:
```
$ singularity version
3.3.0-1.el7
```
### Expected behavior

I'm porting a Docker-based workflow to Singularity. The Docker-based workflow does things like, for example, install R packages under `/usr/local` within the `docker://rocker/tidyverse:3.5.1` container.

I'm porting it to Singularity because I need it to be able to run on a machine where I don't have root access (EDIT: nor do I have the ability to use fakeroot). I don't need root access to run `docker://rocker/tidyverse:3.5.1` via Singularity, or to save it to a .sif file. I also don't need root access to invoke a container based on the image or a .sif file made from it with the `--writeable-tmpfs` flag, which makes `/` not a read-only filesystem. I get a `/` which is owned by me and writable.

But when I am in the container I am me, not root, and the root filesystem of the container *under* `/` is still all root-owned. I need to be able to actually write to the root of the container in practice, not just in theory if I had the permissions.

How can I tell Singularity to change root-owned files to be owned by my user when starting the container, in addition to `/`? Or is there a way to process the .sif file, which I own, without root, to change the ownership of the files it contains? Do I have to develop my own tooling to bust open the .sif, modify the squashfs file inside to change the ownership of everything, and repack it? Or is there some other way to be able to write inside the container?

### Actual behavior

When starting the container, the directories under it are owned by root, and I have no way to change their ownership or to become root in order to write to them.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

```
singularity build test.sif docker://rocker/tidyverse:3.5.1
ls -lah test.sif
# -rwxr-xr-x 1 anovak giuser 631M Oct 14 12:19 test.sif
singularity shell --writable-tmpfs test.sif
touch /test
# works
touch /usr/test
# touch: cannot touch '/usr/test': Permission denied
```

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

Singularity was installed by our local system administrators, probably from an RPM.

**Comment by cclerget** [comment]
Hi @adamnovak , you can use a sandbox directory :

```
singularity build -s test_sandbox docker://rocker/tidyverse:3.5.1
singularity shell -w test_sandbox
```

Do everything you need in the image and rebuild a SIF with:

```
singularity build test.sif test_sandbox
```

**Comment by adamnovak** [comment]
OK, I have tried this @cclerget, and the setup you recommend still doesn't do what I want.

When running the container out of the `test_sandbox` sandbox, I do indeed own all the files and I can `touch /usr/test` and have it take. All is well; the container is in the state I want.

But when I pack it up into `test.sif` and run `singularity shell --writable-tmpfs test.sif`, everything under `/` is again owned by root and I can't touch it.

My problem isn't that I need to do some preparation of the container that modifies system files; the workflow I am trying to run wants system files to be modifiable at workflow execution time. On the other hand, it seems like I am supposed to be backing my workflow's execution with .sif files and not sandbox directories.

Is there a way to build a .sif from the sandbox directory that doesn't (re)chown all the files to root, and that preserves the exact ownership and permissions I see when running from the sandbox directory? If not, I suppose I can just run everything out of sandbox directories, and never use .sif files...

**Comment by cclerget** [comment]
@adamnovak Unfortunately with actual workflow it's not possible to own files/directories during squashfs packing because of option `-all-root` passed to `mksquashfs` command. As a workaround you may set `0777` permissions on directories where you need write permissions

**Comment by adamnovak** [comment]
OK, so it looks like the Right Way is "run from a sandbox directory, or chmod 777 the whole filesystem via a sandbox directory intermediate".

I think that addresses the issue, although it would be useful for Singularity to have a way to turn off `-all-root` when building the squashfs, or (even better) a way to view root-owned files as actually user-owned when mounting the image.

**Comment by adamnovak** [comment]
Hey @cclerget, if I run a container from a sandbox as opposed to a .sif file, is `--writable-tmpfs` sufficient to prevent modifications to the container's files from affecting the sandbox (and thus other containers started from the same sandbox)? Or are sandboxes always mutable, while squashfs/.sif images, if you happen to have write permissions, are always modified via overlay?
