### ISSUE TITLE
Formatting (whitespace and newlines) altered when using `%runscript`

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#463]
Consider this simple definition file `some.def`.  It uses the `%runscript` section to create a `/singularity` file for displaying help and passing options/arguments into a container.
```
BootStrap: debootstrap
OSVersion: trusty
MirrorURL: http://us.archive.ubuntu.com/ubuntu/

%runscript
#!/bin/bash

function usage() {
    cat <<EOF
NAME
    some.img
SYNOPSIS
    some.img [help]
DESCRIPTION
    Singularity container to do stuff!
EOF
}

arg="${1:-none}"
case "$arg" in
    none) usage; exit 1;;
    help) usage; exit 0;;
    # just try to execute it then
    *)    $@;;
esac
```
Use it to create a `some.img` like so:
```
$ sudo singularity create -F some.img && sudo singularity bootstrap some.img some.def
```
Now in Singularity 2.2 the container displays help like this:
```
$ ./some.img help
NAME
    some.img
SYNOPSIS
    some.img [help]
DESCRIPTION
    Singularity container to do stuff!
```
But if you bootstrap the same container with the master branch and then try the same command, you get this:
```
$ ./some.img help
/singularity: 4: /singularity: Syntax error: "(" unexpected
```
And here is what `/singularity` looks like in that container:
```
$ singularity exec some.img cat /singularity

#!/bin/bash

function usage() {
cat <<EOF
NAME
some.img
SYNOPSIS
some.img [help]
DESCRIPTION
Singularity container to do stuff!
EOF
}

arg="${1:-none}"
case "$arg" in
none) usage; exit 1;;
help) usage; exit 0;;
# just try to execute it then
*)    $@;;
esac
```
Note that a newline was added at the top rendering the shebang moot, so the script tries to execute with `/bin/sh` instead and apparently can't handle the switch/case statement.  Even if it did work, we also lost all of the leading whitespace from the original so our help message would be hard to read.

**Comment by gmkurtzer** [comment]
I think this is fixed in the "development" branch. Can you confirm?

Thanks!

**Comment by GodloveD** [comment]
Tested and confirmed.  Feel free to close!

Also, `singularity create` seems damn fast now.  Awesome!

**Comment by vsoch** [comment]
:tada:

**Comment by gmkurtzer** [comment]
Wahooo! And.... `singularity create` can run as non-root now! :D

**Comment by GodloveD** [comment]
Oh that is super cool. Rewriting the web page is going to be a big project.

**Comment by vsoch** [comment]
haha, you mean the docs? I just realized this. Don't worry @GodloveD - we got it! @gmkurtzer, just give me maybe a day or two's notice before you release 2.3 so I can have the docs ready to go!

**Comment by GodloveD** [comment]
Cool. I'm happy to help too. No need to keep it all to yourself. :-)

**Comment by vsoch** [comment]
thanks :)
