### ISSUE TITLE
Reminder - return to upstream umoci when possible

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4631]
This is a reminder tech-debt tracking issue.

We need to return to the upstream umoci, and abandon the fork used from https://github.com/sylabs/singularity/pull/4624 when:

1. It is possible to reconcile the conflicts that bringing in umoci 0.4.4 causes due to its updated dependencies. See #4209 
2. The patches merged upstream as of https://github.com/openSUSE/umoci/commit/a2e72a14734bef79652748e41b4ee15252cf681f are in a tagged release of umoci.

**Comment by hollowec** [comment]
Hi @dctrud,
On some of our systems, /tmp is a symlink to /home/tmp.  This causes an issue with the current version of umoci (0.4.3) required by Singularity (3.5.2) when attempting to run Docker containers:
```
$ singularity shell docker://centos:7
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob ab5ef0e58194 done
Copying config 0a7908e1b9 done
Writing manifest to image destination
Storing signatures
FATAL:   Unable to handle docker://centos:7 uri: unable to build: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: set initial root time: lutimes: open parent directory: open /tmp: too many levels of symbolic links
```
For now I've resolved the problem by setting SINGULARITY_TMPDIR to /home/tmp on these machines.  However, looking at the code, it's possible this PR which was incorporated in 0.4.4 may resolve this issue:
openSUSE/umoci#283

Do you have any update on when you'll be able to move to newer version of umoci?

Thanks.

**Comment by dtrudg** [comment]
Hi @hollowec - 2 issues here...

1) There's another small change I had to make to umoci that I need to look at upstreaming. I'm not 100% on it being accepted.

2) The bigger issue is that we can't go to umoci 0.4.4 now due to the dependencies it brings in. `umoci` and the various `containerd/xxx` `containers/xxx` `opencontainers/xxxx` packages we use in Singularity have a tight web of dependencies. Moving them individually isn't possible due to changes around seccomp and container spec stuff for RDMA...

https://github.com/sylabs/singularity/pull/4209#issuecomment-521670988

We do have to address this in quite a big effort, to try and drag all of the dependencies up in sync with eachother. This is something I plan to attempt to tackle, or at least scope, shortly.

**Comment by hollowec** [comment]
OK, thanks @dctrud !

**Comment by dtrudg** [comment]
#4981 returned us to upstream umoci and we are on v0.4.5 in the master branch that will become Singularity 3.6

There is a slight regression from 3.5 regarding repeated warnings, that has been up-streamed. If a new release of umoci happens before Singularity 3.6 we can use it. If not we will go back to our own fork, but updated to be off of upstrea, v0.4.5

I believe this should address your issue @hollowec

**Comment by hollowec** [comment]
Thanks @dctrud , I've verified the updates to the master branch resolve the /tmp symlink issue!
