### ISSUE TITLE
Plugin Compile Fails when Plugin is Installed

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#4638]
### Version of Singularity:

What version of Singularity are you using? Run:

```sh
$ singularity version
3.4.2-rc.1+477-g53ed0f10f
```

### Expected behavior

Running `singularity plugin compile` when a plugin with the same name is installed should succeed.

### Actual behavior

Running `singularity plugin compile` when a plugin with the same name is installed fails:

```sh
$ singularity plugin compile examples/plugins/cli-plugin/
$ sudo singularity plugin install examples/plugins/cli-plugin/cli-plugin.sif 
$ singularity plugin list
ENABLED  NAME
    yes  sylabs.io/cli-plugin
$ singularity plugin compile examples/plugins/cli-plugin/
FATAL:   Plugin compile failed with error: while generating plugin manifest: plugin.Open("/home/adam/src/singularity/examples/plugins/cli-plugin/plugin"): plugin already loaded
```

### Steps to reproduce this behavior

As above.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

From source.

**Comment by sashayakovtseva** [comment]
The problem is that we load plugin to fetch embedded manifest. Not sure, but we might need to store manifest as a separate file to prevent this error.
