### ISSUE TITLE
Please update vendored "containers/(image|storage)"

### ISSUE THREAD

**Issue by onlyjob** [apptainer/singularity#4648]
Latest release of Singilarity (3.4.2) vendors fairly old [containers/storage](https://github.com/containers/storage/releases) and [containers/image](https://github.com/containers/image/releases) libraries:

  * https://github.com/sylabs/singularity/blob/v3.4.2/vendor/modules.txt#L84
  * https://github.com/sylabs/singularity/blob/v3.4.2/vendor/modules.txt#L107

Upstream uses proper semantic releases so please make sure to vendor those libraries only by their release tags.

Thanks.

**Comment by dtrudg** [comment]
@onlyjob - this is not necessarily simple due to the the complex web of dependencies of other OCI related libraries singularity is using. We can look at these, but there are various libraries that Singularity uses that must be brought in from a commit hash rather than tagged version due to conflicts otherwise.

**Comment by onlyjob** [comment]
> this is not necessarily simple due to the the complex web of dependencies of other OCI related libraries singularity is using.

It is about the right way to do things (i.e. best practice) which is not always easy or simple yet _necessary_...

Thank you.

**Comment by dtrudg** [comment]
@onlyjob best practice is definitely to be strived for, but it is not always necessary in the short term, especially if there is a big effort required for little impact, while other priorities that impact users more directly are in play.

@mem has been kindly looking at these libraries in a PR - but for future requests of this type, please try to give a specific reason (if any) for the request that we can use to prioritize. I am guessing this is related to Debian packaging of dependencies from your GitHub history? but we'd be grateful for specifics.

Thanks!

**Comment by onlyjob** [comment]
Thanks, @dctrud. Yes, we've got container's "image" and "storage" libraries packaged (not the latest releases yet) but Singularity FTBFS with currently packaged "image" because it is ahead of vendored "image" in Singularity. 
I reckon for good dependency hygiene it would be nice to update Singularity vendoring, sooner or later.

Arguably keeping dependencies up to date is not a "little impact", IMHO. I don't know what specific reason could be given for updating obsolete revision of vendored dependency. It is just have to be done sooner or later. I'm not asking to prioritise. ;)

Thanks.

**Comment by onlyjob** [comment]
Thanks, @mem. Much appreciated.

**Comment by onlyjob** [comment]
Actually it would be nice to move containers/image ahead a bit further to v4 or v5. Shall I open a new ticket for this?
