### ISSUE TITLE
Bootstrap Arch Linux, `Could not resolve host` or `fg: no job control`

### ISSUE THREAD

**Issue by chiroptical** [apptainer/singularity#465]
I am using the following Arch Linux bootstrap definition (based on the example) with Singularity Release 2.2:

```
DistType "arch"

Bootstrap

# Set time zone
RunCmd ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime

# Fix locale
RunCmd echo 'en_US.UTF-8 UTF-8' > $SINGULARITY_ROOTFS/etc/locale.gen
RunCmd locale-gen

# Mirror list
RunCmd echo 'Server = http://mirror.cs.pitt.edu/archlinux/$repo/os/$arch' > $SINGULARITY_ROOTFS/etc/pacman.d/mirrorlist
RunCmd echo 'Server = http://mirrors.rit.edu/archlinux/$repo/os/$arch' >> $SINGULARITY_ROOTFS/etc/pacman.d/mirrorlist
RunCmd echo 'Server = http://mirror.es.its.nyu.edu/archlinux/$repo/os/$arch' >> $SINGULARITY_ROOTFS/etc/pacman.d/mirrorlist
RunCmd echo 'Server = http://mirrors.rutgers.edu/archlinux/$repo/os/$arch' >> $SINGULARITY_ROOTFS/etc/pacman.d/mirrorlist

# Get git
RunCmd pacman -Syy
```

Yields: `Could not resolve host <hosts listed above>`

If I try to add:

```
%post
    pacman -Syy
```

Yields: `fg: no job control`

If I shell into the image, I can run `pacman -Syy` no problem. Any thoughts? I am trying to put together a `tensorflow-gpu` container for a user, as well as learn a bit more about Singularity.

**Comment by vsoch** [comment]
I'm pretty sure that definition is old, and `RunCmd` is no longer in use. Maybe try putting those into different blocks for `%setup` and `%post` instead? Where setup is intended to be the pre-bootstrap stuff, and %post for after.

**Comment by chiroptical** [comment]
Anytime I use a `%<something>`, I get: `fg: no job control`.

**Comment by vsoch** [comment]
Ok, how about share your entire bootstrap file, and we will start from there! :L)

**Comment by chiroptical** [comment]
I modified, based on your suggestion, to:

```
DistType "arch"

Bootstrap

%setup
    # Set time zone
    ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime

    # Fix locale
    echo 'en_US.UTF-8 UTF-8' > $SINGULARITY_ROOTFS/etc/locale.gen
    locale-gen

    # Mirror list
    echo 'Server = http://mirror.cs.pitt.edu/archlinux/$repo/os/$arch' > $SINGULARITY_ROOTFS/etc/pacman.d/mirrorlist
    echo 'Server = http://mirrors.rit.edu/archlinux/$repo/os/$arch' >> $SINGULARITY_ROOTFS/etc/pacman.d/mirrorlist
    echo 'Server = http://mirror.es.its.nyu.edu/archlinux/$repo/os/$arch' >> $SINGULARITY_ROOTFS/etc/pacman.d/mirrorlist
    echo 'Server = http://mirrors.rutgers.edu/archlinux/$repo/os/$arch' >> $SINGULARITY_ROOTFS/etc/pacman.d/mirrorlist

    # Get git
    pacman -Syy

Cleanup
```

Yields: `./arch.def: line 5: fg: no job control`

**Comment by chiroptical** [comment]
I should also mention I am provisioning from an Arch Linux host.

**Comment by vsoch** [comment]
Yeah I have ubuntu, so I'm not sure if I have the dependencies! Any reason you can't just do:

      sudo singularity create arch.img

Then the `Singularity` file looks like this:

	Bootstrap: docker
	From: base/archlinux

	%setup
	    # Set time zone
	    ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime

	    # Fix locale
	    echo 'en_US.UTF-8 UTF-8' > $SINGULARITY_ROOTFS/etc/locale.gen
	    locale-gen

	%post

	    # Get git
	    pacman -Syy

For me it seems to run ok:

	vanessa@vanessa-ThinkPad-T460s:~/Desktop$ sudo singularity bootstrap arch.img Singularity 
	Cache folder set to /home/vanessa/.singularity/docker
	Extracting /home/vanessa/.singularity/docker/sha256:80ab3605368435aecb35af5cafa332aa4c04a12e0aceec02d052a36ffcbf5e51.tar.gz
	Extracting /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
	Generating locales (this might take a while)...
	  en_AG.UTF-8... done
	  en_AU.UTF-8... done
	  en_BW.UTF-8... done
	  en_CA.UTF-8... done
	  en_DK.UTF-8... done
	  en_GB.UTF-8... done
	  en_HK.UTF-8... done
	  en_IE.UTF-8... done
	  en_IN.UTF-8... done
	  en_NG.UTF-8... done
	  en_NZ.UTF-8... done
	  en_PH.UTF-8... done
	  en_SG.UTF-8... done
	  en_US.UTF-8... done
	  en_ZA.UTF-8... done
	  en_ZM.UTF-8... done
	  en_ZW.UTF-8... done
	Generation complete.
	:: Synchronizing package databases...
	 core                     123.5 KiB  1113K/s 00:00 [######################] 100%
	 extra                   1691.6 KiB  4.59M/s 00:00 [######################] 100%
	 community                  3.7 MiB  5.70M/s 00:01 [######################] 100%
	No test code provided in this container
	vanessa@vanessa-ThinkPad-T460s:~/Desktop$ ./arch.img 
	No Singularity runscript found, executing /bin/sh
	Singularity.arch.img> 

If you want to make tweaks off of that, you can then customize the `%post` and `%setup`, or use a different tag for archlinux? You can see how the image was created by [looking at it on Docker Hub](https://hub.docker.com/r/base/archlinux/). 

Maybe that's helpful? Seems like if someone has already figured out how to dump arch linux into an image, might as well start using those layers than from scratch! If you want to do from scratch via Singularity, we might need others to chime in as well.

**Comment by chiroptical** [comment]
I had to get the latest source code because someone fixed a Python 2/3 issue in `libexec/python/utils.py`, but afterwards it was smooth sailing. I am new to this container stuff, which is why I wanted to start from scratch. It's the Arch way. If I finish the tensorflow-gpu install would that be of general interest? I can submit a pull request updating `example/arch.def` too.

**Comment by vsoch** [comment]
ah ok! Yes it would be hugely of interest! I think the better place to share your spec would be on [singularity-hub](https://www.singularity-hub.org) so people can just grab and use the image, and get the spec equally the same, and it would definitely still be ok to add the contribution to the contrib folder in examples.

**Comment by chiroptical** [comment]
Great! I will close this and make the contributions after I do some testing.

**Comment by vsoch** [comment]
Awesome, thank you @barrymoo !

**Comment by chiroptical** [comment]
I was able to run this locally, but I am having some issues after I migrate to our cluster.

Running: `singularity -d shell arch.img > issue.txt 2>&1`
Towards the bottom:

```
DEBUG   [U=152336,P=26281] privilege.c:355:singularity_priv_drop_perm(): Confirming we have correct GID
DEBUG   [U=152336,P=26281] privilege.c:361:singularity_priv_drop_perm(): Confirming we have correct UID
DEBUG   [U=152336,P=26281] privilege.c:369:singularity_priv_drop_perm(): Setting NO_NEW_PRIVS to prevent future privilege escalations.
VERBOSE [U=152336,P=26288] fork.c:157:singularity_fork()              : Hello from child process
DEBUG   [U=152336,P=26288] fork.c:160:singularity_fork()              : Closing watchdog write pipe
ERROR   [U=152336,P=26281] privilege.c:371:singularity_priv_drop_perm(): Could not set NO_NEW_PRIVS safeguard: Invalid argument
ABORT   [U=152336,P=26281] privilege.c:372:singularity_priv_drop_perm(): Retval = 255
ERROR   [U=152336,P=26288] fork.c:105:wait_for_go_ahead()             : Parent closed write pipe unexpectedly.
ABORT   [U=152336,P=26288] fork.c:106:wait_for_go_ahead()             : Retval = 255
```

Does this mean anything to you? I can add more of the debugging output if you need it.

**Comment by chiroptical** [comment]
If I run as root, it works. On RHEL 6.6.
