### ISSUE TITLE
FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: Failed to set loop flags on loop device: resource temporarily unavailable

### ISSUE THREAD

**Issue by anderspitman** [apptainer/singularity#4652]
### Version of Singularity:

```
3.3.0-1
```

### Expected behavior

Able to spawn many singularity commands simultaneously.

### Actual behavior

When launching a lot (~50) of singularity processes at the same time, I more often than not get the error above from some of the containers.

### Steps to reproduce this behavior

Launch many singularity containers, running commands that take ~10 seconds each to complete.

### What OS/distro are you running

```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

Release tarball `singularity-3.3.0.tar.gz`

**Comment by anderspitman** [comment]
I've seen several other issues that have similar errors, but the core issue isn't obvious to me after reading through them.

**Comment by dtrudg** [comment]
This should be fixed in 3.4.1 and newer. Relatively recent kernels can raise a temporary failure and the loop setup must be retried. If you can try with the latest `3.4.2` and let us know if there are any remaining issues that would be much appreciated.

* Handles temporary EAGAIN failures when setting up loop devices on recent kernels

**Comment by anderspitman** [comment]
@dctrud I just ran a few tests on `3.4.2` and it appears to be working. Thanks for the quick turnaround!

**Comment by desimuser1** [comment]
i have this error 
"FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: no loop devices available"
salome meca was running properly, but this happened

**Comment by DrDaveD** [comment]
That's a different error.  I suggest searching in https://github.com/apptainer/apptainer and if that isn't helpful, create a new issue.

**Comment by desimuser1** [comment]
once i restarted the system, it worked out

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
