### ISSUE TITLE
Provide `vendor/` in make dist tarball on master branch

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4664]
### Version of Singularity:

What version of Singularity are you using? Run:

```
master
```

### Expected behavior

A `vendor/` directory is included in the tarball output of `make dist` so that there is a source distribution that can be built without pulling go modules from the internet.

### Actual behavior

`vendor/` does not exist in the `make dist` tarball.

### Steps to reproduce this behavior

```
./mconfig
cd builddir && make dist
```

**Comment by jmstover** [comment]
Has `vendor/` been removed from `git`?  If so why? We need to be able to build w/o network access... So, we need to provide all our dependencies.

**Comment by dtrudg** [comment]
> Has `vendor/` been removed from `git`? If so why? We need to be able to build w/o network access... So, we need to provide all our dependencies.

Yes - vendor was removed in master shortly after the move to Go 1.13. This issue is to address builds for distros etc. without network access via `make dist` tarballs including a `vendor/`

This is not necessarily super trivial as @mem has to look into making mconfig work with a `vendor/` for the tarball build - but use the GOPROXY otherwise.

**Comment by dtrudg** [comment]
@jmstover - this is the PR that removed `vendor/` on master: https://github.com/sylabs/singularity/pull/4620

**Comment by DrDaveD** [comment]
Please make sure that the vendor directory in the tarball has directories writable by the user so the files can be easily deleted by the user, unlike the files in the go modcache.
