### ISSUE TITLE
Request - tarball naming should not include release

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4668]
Opened to capture a request from @DrDaveD that was discussed in slack.

### Version of Singularity:

```
master
```

### Expected behavior

Request is that a tarball from `make dist` should not include the release portion of `VERSION` set via `mconfig -V`.

E.g.

```
./mconfig -V 9.9.9:1.2.3
make -C builddir dist
```

should give a tarball named `singularity-9.9.9.tar.gz`

### Actual behavior

```
./mconfig -V 9.9.9:1.2.3
make -C builddir dist
```
gives a tarball named `singularity-9.9.9:1.2.3.tar.gz`

### Discussion

In #4661 the ability to set an RPM version via `mconfig -V xxxx` was restored, after prior changes that introduced handling semver properly which brought in the `get-version` script.

At this point it is understood that the current state of `master` generates rpm files that are named as expected through a `make rpm`.

@DrDaveD has strongly requested that name of the tarball from `make dist`, which is an intermediate step in `make rpm`, should not include the release portion of the `-V` version - i.e. it should not include anything after a `:` - it should only include the `9.9.9` or `9.9.9-rc.1` portion.

The reasoning for this request is that it is usual for rpms to be built from a tarball that only contains the upstream version in its name, not the release added by packaging. If the release is included in the tarball this will result in multiple tarballs and rpmbuild directories being created during local work, which have to be cleaned up manually.

Some members of the Sylabs team (chiefly @dctrud and @mem) are of the opinion that having the release version included in the tarball name via `make dist / make rpm` *is* beneficial as:

- If we are building from pristine upstream source, not having a release number in the tar is expected - and is satisfied by our GitHub release tarballs.
- Distro packages, such as in EPEL, are expected to use a modified `.spec` file that is curated in a distro repo, not the `singularity.spec` in our upstream source tarballs. The build there would be via `rpmbuild` and not `make rpm` - so the issue of an intermediate tarball name does not exist.
- When `make rpm` is run on a source tree with local changes, an intermediate non-pristine tarball is created, and if this does not include release / git commit info it cannot easily be distinguished from a pristine upstream release tarball.
- A release number change would presumably be associated with a change to the source or `.spec` patches etc. If the intermediate tarball name does not reflect the release number it is not trivial to match a tarball to the set of changes included.
- Not all sites will build rpms immediately to install a locally modified version of Singularity. They may build from a source tarball created via `make dist`, could distribute it internally, or even to others. `make dist` is used in the `make rpm` process - but the purpose of the tarball is more than an upstream for `make rpm`.
- Any change that makes it harder to precisely identify the origin of the version of Singularity a user is experiencing an issue with, e.g. is it pristine upstream / EPEL / built from a modified tarball could cause an increased burden of support.

**Comment by mem** [comment]
Note that this mostly applies when using the -V flag to mconfig, which allows the user to completely override the version number that singularity reports.

But it _also_ applies to the case when that flag is _not_ used, as the version number is constructed from the most recent tag (v3.4.2) plus a description of the changes on top (+123-fedcab, where fedcab is the short sha1 of the current commit). This creates, correctly IMO, a tarball name that includes that info, too, as that tarball _is not_ 3.4.2.

**Comment by DrDaveD** [comment]
@mem No, those extra pieces (e.g. +123-fedcab) are include in the Version portion, not in the Release portion after the colon.  We're only talking about the Release portion.

**Comment by mem** [comment]
@DrDaveD in this case it's semantically the same thing, because for what we can support out of the repository, without touching the .spec file in any way, that would be version 3.4.2 (v3.4.2) plus a bunch of modifications (123-fedcab) and the corresponding source code is not represented anywhere other than that tarball with that name.

**Comment by tcooper** [comment]
@DrDaveD... is this the RPM I'm _supposed_ to get with 3.5.0-rc.1?

```
$ rpm -qip singularity-3.5.0~rc.1-1.el7.x86_64.rpm
Name        : singularity                  Relocations: (not relocatable)
Version     : 3.5.0~rc.1                        Vendor: (none)
Release     : 1.el7                         Build Date: Tue 29 Oct 2019 07:08:12 PM PDT
Install Date: (not installed)               Build Host: singularity-rpmbuilder.example.com
Group       : Unspecified                   Source RPM: singularity-3.5.0~rc.1-1.el7.src.rpm
Size        : 102252343                        License: BSD-3-Clause-LBNL
Signature   : (none)
URL         : https://www.sylabs.io/singularity/
Summary     : Application and environment virtualization
Description :
Singularity provides functionality to make portable
containers that can be used across host environments.
```

Note the `~` in Name.

I have to admit... I got a little lost trying to figure out what you guys have been debating.

**Comment by DrDaveD** [comment]
Yes, the hyphen gets translated to tilde for rpms, because rpm treats things after the hyphen as being older than nothing.  That's the same as what semantic versioning does with hyphens, but rpm treats hyphens as something different: the separator between version and release.

**Comment by jmstover** [comment]
I'm pretty sure it was taken into account... but for the older RPM, it still uses the old naming where it doesn't support the `~` differently yes? Otherwise it looks like it's going to just be reading the "Version" of `3.5.0~rc.1` in straight up ascii order. So `3.5.0~rc.1` > `3.5.0`

**Comment by DrDaveD** [comment]
I tested on el6, that even though it is an older version of rpm that preceded the tilde support, it still treated the tilde as older.  Redhat must have backported that patch.

**Comment by tcooper** [comment]
OK... I think I finally clued in.

This...

```shell
$ echo -e "3.5.0-rc.1\n3.5.0~rc.1\n3.5.0" | sort -d
3.5.0
3.5.0~rc.1
3.5.0-rc.1
```

...compared to this...

```shell
$ echo -e "3.5.0-rc.1\n3.5.0~rc.1\n3.5.0" | sort -V
3.5.0~rc.1
3.5.0
3.5.0-rc.1
```

**Comment by dtrudg** [comment]
Hello everyone. Up until now on the tarball issue my preference has been for this 'intermediate' tarball to include the release/commit info mainly along philosophical lines about always being able to identify the version of the code built from a Git tree easily. I now have specific practical reasons to ask that this behavior is maintained.

This request is slightly sensitive, as it's from a use case I have on the commercial side of Sylabs, regarding Singularity Pro. I'm conscious that I'm now asking for behavior in OSS to make something easier in Pro - but I believe the benefits may be applicable to people building OSS a lot.

*Also* - I'm going to avoid making a call on this issue... as I don't want to be overriding community feedback with just a Pro need.

- Sylabs puts together releases of Singularity Pro - our LTS distributions of Singularity for people who need them. I'm currently handling parts of this process.
- We want to keep close (but with extra backports) to Singularity OSS - which includes hopefully not customizing the build system a great deal.
- In Pro we issue new releases from time to time. With the old method of a tarball not containing the release, it's a really manual and error-prone exercise to ensure that the `singularity-<version>.tar.gz` intermediate tarballs between releases are not mixed up. They *are* different per release, as these are not pristine unmodified source - but have changes and the name doesn't reflect that, so we must not get them mixed up as they are moved out to build machines to build our RPMs and run tests etc. and archived to have an independent history from the Git tree.
- Starting to look at the next Pro we begin to work with the OSS base that'll become the next release. Working from the tree here it is already apparent to me that having these intermediate tarballs with more complete version-release information removes manual steps across builds that have to be carefully followed so there is no mix up, and we trivially have a nice history of all the tarballs we have built rpms from throughout dev / QA / release.

This main open source repo of Singularity is tagged in a way that our pristine OSS release tarballs will always be named only `singularity-<version>.tar.gz` without a release number. As far as I can see this is the main thing we need to ensure for distro packaging that uses their own `.spec` or `debian` files - and wouldn't use the `.spec` in our tree.

Release numbering in intermediate non-pristine tarballs used to build rpms has benefits for me personally.

**Comment by dtrudg** [comment]
Ahh - my above is essentially the same reasoning articulated by @gmkurtzer at https://groups.google.com/a/lbl.gov/forum/#!topic/singularity-devel/x4N8Dy_W8uE

**Comment by DrDaveD** [comment]
@dctrud Why not just archive source rpms instead of tarballs?

**Comment by dtrudg** [comment]
@DrDaveD - In this case the `rpmbuild` has been initiated against the tarball - so I prefer to keep it. I just like having all the steps in the chain.

**Comment by dtrudg** [comment]
I'm going to close this. @gmkurtzer weighed in here https://groups.google.com/a/lbl.gov/d/msg/singularity-devel/x4N8Dy_W8uE/0tGVG7hIAwAJ and the majority opinion seems to have been in favor of keeping the release information on non-pristine upstream tarballs.
