### ISSUE TITLE
`-H` to override home dir does not work on MacOS

### ISSUE THREAD

**Issue by daviehh** [apptainer/singularity#4670]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```

```
3.3.0-rc.1.658.g7427b73f1.dirty
```

### Expected behavior

What did you expect to see when you do...?

Able to use the `-H` switch to map some folder `foo` on the host as the instance's home directory with e.g. `singularity shell`

### Actual behavior

 
What actually happend? Why was it incorrect?

`singularity shell -H /path/to/foo image.sif` still mounts the host's home directory and not `/path/to/foo`

Quickly glancing through, may be hard-coded?
https://github.com/sylabs/singularity/blob/bf06a977afd4b8db7d3ac19d450a8b47b413f73d/cmd/internal/cli/startvm_darwin.go#L115

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

`singularity shell -H /path/to/foo some_image.sif`

then `ls` in `~`

### What OS/distro are you running

macos 10.15 (19A602)

**Comment by dtrudg** [comment]
Hi @daviehh - yes, it looks like there is a TODO just above the source line there. I'm afraid the Mac version is a beta - so bear with us.

**Comment by dtrudg** [comment]
Closing as Singularity Desktop currently not maintained.
