### ISSUE TITLE
cannot install on ubuntu

### ISSUE THREAD

**Issue by chekanov** [apptainer/singularity#4681]
Is any simple way to install on ubuntu? According to the web page with installation, I have to use

```
git clone https://github.com/singularityware/singularity.git
$ cd singularity
$ ./autogen.sh
$ ./configure --prefix=/usr/local --sysconfdir=/etc
```

But there is no "autogen.sh" in this directory. 

 I understood, the  other method includes installing "go'. I would like to avoid this since it is not included in the ubuntu repo for v 19.10.

best, Sergei

**Comment by dtrudg** [comment]
Hello @chekanov - those instructions are for old versions of Singularity 2.x - Singularity was rewritten in Go, so I'm afraid Go is required for any 3.x version. We strongly recommend using 3.x as many improvements have been made since 2.x.

Go should be available in Ubuntu 19.10 via `apt install golang-1.12` or `apt install golang-1.13`.

**Comment by chekanov** [comment]
Ok, thanks! Unfortunately ubuntu 19.10 has only golang-1.12, which is not higher enough version to install the singularity master branch. The https://singularity.lbl.gov/install-linux still points to version 2.5 (much  simpler to install than version 3.X)

**Comment by dtrudg** [comment]
Hi @chekanov - please not that the pages at lbl.gov are old, and will not be updated. As the banner at the top of those pages notes, documentation has moved to https://www.sylabs.io/docs/

Ubuntu 19.10 does have Go 1.13 available in the `universe` repo - I'm currently typing on a laptop running 19.10 here, and was able to install it 

```
dave@lappy~> sudo apt install golang-1.13
[sudo] password for dave: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  golang-1.13-doc golang-1.13-go golang-1.13-src
Suggested packages:
  bzr | brz mercurial subversion
The following NEW packages will be installed:
  golang-1.13 golang-1.13-doc golang-1.13-go golang-1.13-src
0 upgraded, 4 newly installed, 0 to remove and 2 not upgraded.
Need to get 62.7 MB of archives.
After this operation, 322 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
...
dave@lappy~> go version
go version go1.13 linux/amd64
```

Also note that it's quite straightforward to install Go from binaries, as described in the INSTALL.md in the Git repo.

Our current stable version `3.4.2` will build with Go 1.12 without issues, and you can get that from the releases page, or `git checkout v3.4.2` in the git repo.

**Comment by chekanov** [comment]
Oh, I had to reinstall ubuntu from 19.04 to 19.10.. This singularity 3 became very demanding.

**Comment by dtrudg** [comment]
Apologies - I thought from the above comments you had 19.10 already.

Note that the instructions in the `INSTALL.md` will work well if they are just copied and pasted on Ubuntu, including downloading a new Go from the official binary releases. I use them regularly on Ubuntu 18.04 and other distributions.
