### ISSUE TITLE
OpenBSD support?

### ISSUE THREAD

**Issue by jungle-boogie** [apptainer/singularity#4682]
Hi All,

Thanks for `singularity`! I heard about this project on FLOSS weekly last week:
https://twit.tv/shows/floss-weekly/episodes/552

I'd like to try out `singularity` on OpenBSD, my very preferred OS. Do you think there's any chance of it working? `go` is supported and at version 1.13. Does there need to be a certain filesystem or Linux compatibility to use `singularity`?

**Comment by dtrudg** [comment]
Hi @jungle-boogie, glad to hear you came across Singularity via floss weekly! 

I'm afraid Singularity is dependent on Linux namespaces, which to the best of my knowledge are not supported on BSDs. There are some other things too, but that's a fundamental area. I'm afraid that BSDs are not a target for us at present.

**Comment by jungle-boogie** [comment]
HI @dctrud,

I had a feeling some linux internals were needed for Singularity to work.

keep up the great work and thanks for making free software.
