### ISSUE TITLE
--remote options does not allow to build with %files

### ISSUE THREAD

**Issue by oliviermattelaer** [apptainer/singularity#4685]
### Version of Singularity:

What version of Singularity are you using? Run:
singularity version 3.4.1-1.2.el7

If I run 
singularity build --remote test.sif test.def
if fails if I have a section like this one in the definition files:

%files
    test.cc /opt/test-mpi.c

### Expected behavior

I expect the file to be upload to the cloud and include in the container.

### Actual behavior

INFO:    Copying test.cc to /tmp/sbuild-505239507/fs/opt/test-mpi.c
FATAL:   container creation failed: unable to copy files to container fs: while copying [test.cc] to /tmp/sbuild-505239507/fs/opt/test-mpi.c: exit status 1: /bin/cp: cannot stat 'test.cc': No such file or directory

### What OS/distro are you running

centos-7

### How did you install Singularity

via yum

**Comment by dtrudg** [comment]
This is a duplicate of #4455 - closing this issue.
