### ISSUE TITLE
3.4.2: FTBFS on "mips64el": undefined: syscall.SIGSTKFLT

### ISSUE THREAD

**Issue by onlyjob** [apptainer/singularity#4689]
Singularity 3.4.2 FTBFS on _mips64el_ as follows:

    ../internal/pkg/util/signal/signal_linux.go:31:15: undefined: syscall.SIGSTKFLT

(See [full build log](https://buildd.debian.org/status/fetch.php?pkg=singularity-container&arch=mips64el&ver=3.4.2%2Bds2-3&stamp=1572657253&raw=0))

The problem looks similar to https://github.com/moby/moby/issues/37300.

**Comment by dtrudg** [comment]
We don't actively support MIPS, and do not have any MIPS machines (to my knowledge) available to test Singularity. A PR would be welcome if you have a machine available to run the test suite on, and confirm there aren't other issues.

**Comment by onlyjob** [comment]
I'm not sure if I could do that but it should be trivial to adapt https://github.com/moby/moby/pull/37491/files

**Comment by dtrudg** [comment]
@onlyjob - yeah, the fix looks fairly simple but I'm afraid we lack the ability right now to easily run the test suite on MIPS, and aren't aware of anyone asking for MIPS support or using Singularity on MIPS in production, so I'm afraid this is unlikely to be a priority for the core team of developers.

Given limited resource we are more concerned with Arm and POWER as non-amd64 architectures as Singularity does have production use for those.

**Comment by cclerget** [comment]
Since it doesn't harm to handle this case even if we are not sure the rest will work correctly, PR #4693 should fix the build error.

**Comment by onlyjob** [comment]
Thank you.
