### ISSUE TITLE
HostOS Stack size limit not honored inside the container

### ISSUE THREAD

**Issue by sfintz67** [apptainer/singularity#4701]
### Version of Singularity:

What version of Singularity are you using? Run:

3.2.1

### Expected behavior

Have the same stack size limit inside and outside the container

### Actual behavior

The stack size limit is resetted to the default value of 8192

### Steps to reproduce this behavior

singularity pull myalpine docker://alpine
singularity pull mydebian docker://debian

ulimit -a | grep stack
stack size              (kbytes, -s) unlimited

singularity shell myalpine 
Singularity> ulimit -a | grep stack
-s: stack size (kb)                8192

singularity shell mydebian
Singularity> ulimit -a | grep stack
stack size              (kbytes, -s) 8192

### What OS/distro are you running

debian9

### How did you install Singularity

Compiled from source

**Comment by cclerget** [comment]
Hi @sfintz67 , when using setuid binary this value is set to its default value by the kernel for security reasons. Will look at the fix. Thanks !

**Comment by sfintz67** [comment]
Thanks cclerget. Currently i'm resseting the limit (to unlimited) inside the runscript but it would be great if the same limit could be set automagically.
Thanks
