### ISSUE TITLE
libarchive headers

### ISSUE THREAD

**Issue by Lcornet** [apptainer/singularity#4711]
### Version of Singularity: 2.6.1

What version of Singularity are you using? Run:2.6.1

```
$ singularity version
2.6.1

```

hecking archive.h usability... no
checking archive.h presence... no
checking for archive.h... no
configure: error: Unable to find the libarchive headers, need package libarchive-devel (libarchive-dev on Debian/Ubuntu)

### Expected behavior

Install

### Actual behavior

checking archive.h usability... no
checking archive.h presence... no
checking for archive.h... no
configure: error: Unable to find the libarchive headers, need package libarchive-devel (libarchive-dev on Debian/Ubuntu)

### What OS/distro are you running

```
$ cat /etc/os-release


NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
### How did you install Singularity

git clone https://github.com/sylabs/singularity.git
cd singularity
git fetch --all
git checkout 2.6.1
./autogen.sh
./configure --prefix=/usr/local

**Comment by dtrudg** [comment]
Hello @Lcornet - the Open Source `2.x` versions of Singularity are no longer maintained, so there will be no change to this behaviour. You will need to `yum install libarchive-devel` or `apt-get install libarchive-dev` to install distributions libarchive headers, or otherwise make them available.
