### ISSUE TITLE
Hardware acceleration in nested containers using Nvidia GPUs

### ISSUE THREAD

**Issue by emiftari** [apptainer/singularity#4717]
### Version of Singularity:

```
3.4.0-1

```
### Expected behavior
I would like to start nested containers and have hardware acceleration in the innermost container without having to include the Nvidia libs and binaries in it. To be able to start a second container inside the first one I use the ```--fakeroot``` option.
I thought of two approaches to do this.
1. Install the matching Nvidia libs and binaries inside the image used for the first container and then use ```--nv``` when starting the second.
2. Use the ```--nv``` option twice. The first time when starting the first container and then again when starting the second container inside the first.

### Actual behavior
Approach 1.
The first step is just ``` singularity shell --fakeroot image1.sif```, which works just fine. image1.sif has the right Nvidia libs and binaries and the same Singularity version as outside. Now I use ``` singularity shell --nv image2.sif``` which returns
```
INFO:    Convert SIF file to sandbox...
WARNING: underlay of /etc/localtime required more than 50 (67) bind mounts
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (199) bind mounts
```
Inside of the second container I start ```glmark2``` which randomly somtimes works and has hardware acceleration or returns:
```
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```
Exiting out of the second container and shelling again into it sometimes works but I simply do not understand this behavior.
---
Approach 2.
I shell into the first container which does not include the Nvidia libs using
``` singularity shell --fakeroot --nv first_image.sif```
Output:
```
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (337) bind mounts
```
This is what I get when I shell into the second container using ```--nv```

```
WARNING: Could not find any NVIDIA libraries on this host!
WARNING: You may need to edit /usr/local/etc/singularity/nvliblist.conf
WARNING: skipping mount of /etc/localtime: no such file or directory
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (337) bind mounts
Singularity secnd_image.sif:/home/[...]/singularity_images>
```
The Nvidia libs cannot be found and ```glxinfo | grep rendering``` returns
```
ibGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Error: couldn't find RGB GLX visual or fbconfig

```
I would prefer this approach as it omits the need for the Nvidia libs inside the outer image. Do i need to change something in nvliblist.conf of the outer image?
### Steps to reproduce this behavior

1. You need one image with the matching Nvidia libs + Singularity and one application image. Shell into the first with the options ```--fakeroot````and from there into the application with ```--nv```. Start the application that needs hardware acceleration.

2. Like in (1.) only now you do not need the Nvidia libs inside of the first one and include the the ```--nv``` option when starting the first container.

### What OS/distro are you running

```
NAME="Linux Mint"
VERSION="19.2 (Tina)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.2"
VERSION_ID="19.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tina
UBUNTU_CODENAME=bionic


```

### How did you install Singularity

From source following the user guide instructions.

**Comment by dtrudg** [comment]
Hello - could you give us some more information about the use-case for this? 

Do you need an effective `root` account in the second container for your app, hence using the `--fakeroot`, or is this just something you have found gets you most of the way where running as a user with the user namespace `-u` does not?

**Comment by emiftari** [comment]
I need to be able to run a singularity image inside of another one, which works with ```--fakeroot```. If I use ```-u``` I get:
```
ERROR  : Failed to set effective UID to 0
```
The reason I need this setup is to decouple some common applications we have in many of our images. At the moment we include for example a remote desktop tool in our images and our drivers for Nvidia GPUs. If possible, we would like to put them into an image that is used as outer image and start single application images through this one. This works fine but breaks when trying to get hardware acceleration.

**Comment by dtrudg** [comment]
Okay - this would need a bit of work to support. Once libs are bound in to the outer container they reside under `/.singularity.d/libs` and are find by applications run in the container via `LD_LIBRARY_PATH`. The code for `--nv` is using the `nvidia-container-cli` tool, or looking for things in `nvliblist.conf` that are in the system `ld.so.conf` paths.

An inner container run with `--nv` would have to find the libraries and bind mount them again.

I don't think this is likely to be a high-priority task for the core team at the moment, but we can discuss. As always, we welcome PRs.

**Comment by emiftari** [comment]
I updated my Nvidia driver version from ```390.116``` to ```430.26``` and up until now didn't experience any issues with approach 1. Nonetheless approach 2 would be a lot more convenient to maintain, especially in an HPC environment. I will stick to approach 1 for the time being.

Huge thanks to you @dctrud for the awesome support and keep up the great work.

**Comment by emiftari** [comment]
Binding the libs you mentioned though ```-B /.singularity.d/libs``` and using ```-nv``` for starting the outer and inner container works. This means i can omit the Nvidia libs inside of my outer container image. This Task can be closed as both approaches work.
