### ISSUE TITLE
Misleading 'symlinks' var / comment on #4704

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4718]
### Version of Singularity:

What version of Singularity are you using? Run:

```
PR #4704
```

### Issue

Apologies. Missed something on the review of #4704 which is a little confusing, and could be clarified in future.

`walkSymRelative` takes a `maxLinks` parameter, but internally is incrementing a var `symlinks` on each iteration. The limit really is on all links (path parts) not just symlinks.

https://github.com/sylabs/singularity/pull/4704/files#diff-0aa0fa200b1f783467e9cdf682ebc142R142

In `EvalRelative` the comment infers a max of 40 symlinks, where it is actually a max path depth of 40, per the above.

https://github.com/sylabs/singularity/pull/4704/files#diff-0aa0fa200b1f783467e9cdf682ebc142R246

**Comment by cclerget** [comment]
@dctrud No `symlinks` is only incremented when there is a symlink in the path since it's called after `os.Readlink` only when it succeeds

**Comment by dtrudg** [comment]
@cclerget - okay, sorry about that. I didn't realize readlink raised error on a non-symlink.

Apologies!
