### ISSUE TITLE
Allow Modules Environment to be available with `shell` subcommand

### ISSUE THREAD

**Issue by milljm** [apptainer/singularity#4722]
### Version of Singularity:

```
$ singularity version
3.4.1-1.2.el7
```
### Expected behavior

```
singularity shell Ubuntu-18.sif

Singularity Ubuntu-18.sif #> module avail
<a list of modules is displayed>
```

A way to have [modules environment](http://modules.sourceforge.net/) **automatically** available within the container. I'd also entertain the idea of using LMOD instead of modules if anyone here knows if that works.

A quick note: Modules is enabled by sourcing what-ever-shell environment you want and they support; sh, bash, zsh, tcsh, ksh, etc. But it does so by exporting functions (except with sh of course, which is limited to the same instance it was sourced in).

### Actual behavior

```
module command not found
```

### What OS/distro are you running

```
$ cat /etc/os-release
Ubuntu 18.04
```

### How did you install Singularity
Via github.com releases.

The only way I am able to allow modules to become available within shell environments, is to either hack `etc/singularity/actions/shell` to use bash instead of sh, or to instruct/train my users to source the modules system _after_ they have entered into the shell environment. Modules works by exporting function calls. So I understand why this does not work in sh.

Does anyone have a way around this? I would rather not hack the action files. Also, is there a reason why I should _not_ be swapping /bin/sh for /bin/bash in the action files? Security risks with functions in containers maybe? 

Thanks in advance!

**Comment by dtrudg** [comment]
@milljm - `/bin/sh` is used in those scripts as it's going to be present in all distributions. In some cases it is `bash`, in some it is `dash`, in some it might be `busybox`. We can't presume anything other than a POSIX `/bin/sh` though.

Others might chime in here with suggestions, and I'll hopefully get some time to think, or take a look back here tomorrow - but can I ask for now exactly how you are intending to use modules?

Are you looking to make:

- host system modules available for use in the container?
- have a completely separate system of modules installed in the container?

**Comment by milljm** [comment]
Thank you for your response, and apologies for the delayed response. I have been ill for the past couple of days.

> @milljm - /bin/sh is used in those scripts as it's going to be present in all distributions. In some cases it is bash, in some it is dash, in some it might be busybox. We can't presume anything other than a POSIX /bin/sh though.

Interesting! It sounds like it might be possible to instruct Singularity what shell we want? Possibly during configure time? I have not studied the ./configure --help output. So, I will take a look after I finish with this post.

I (we) use Singularity mostly for [regression testing](https://civet.inl.gov). My developers want a way to test their code using different aspects of a compiler stack (be it a combination of LLVM 8,9 or GCC 8,9, with PETSc 3.10.5 or 3.11.4) against their code. In order to keep environments sane, we use modules. This is easy to do without Singularity of course. But the real gem of, and why I use Singularity, is that I have many different stacks being made available across several different arches (in other words, I make extensive use of SINGULARITY_BINDPATH [labeled as SBP thereafter]). The containers themselves are as vanilla as I can make them, so when we do come across errors, **they are as reproducible as possible**. And when there are no errors, it is easy to create a redistributable package based on a vanilla instance of linux.

To add to your question because I think it will be more clear (pardon the great wall of text):

Are you looking to make:

- host system modules available for use in the container?
- have a completely separate system of modules installed in the container?
- have a completely separate system of modules installed outside the container? <-- this one, as the container itself does not have modules installed, and yet I am producing modules strictly for use with this container.

How I do it: contents of my (hacked /bin/sh to /bin/bash) /.singularity.d/env/99-startup-environment.sh file:
```
#!/bin/bash
if [ -d /opt/scripts.d ]; then
    cd /opt/scripts.d
    for script in `ls *.sh`; do
        if [ -f "$script" ]; then
           . "$script"
        fi
    done
fi
```
I also need to apply a shebang hack to actions/shell, as mentioned in the origin post.

I then perform some SBP exports to the appropriate /opt/scripts.d path. The scripts contained therein do the actual sourcing command to the module system (which is also being made available dynamically via SBP).

This way, when users enter into a singularity container, they have access to modules in the same manor as if they logged into a host machine having system modules available. The only difference here of course, is that we are leveraging the power and flexibility of running different arches of linux on one host machine.

...after writing all that, I may have a clearer, more generic way of explaining why we do this: My job is to build compiler stacks. Their job is to build stuff, _using_ those compiler stacks. And while the changes to compiler stacks always races ahead of actual development, the developers need access to both.

We do not want to create a container for every possible combination of course, so you can imagine the mile-long value of SBP. It is complex enough that it warranted the creation of a front-end in fact.

As a side note, the work we are doing caught the attention of our local HPC department; They want to employ it on their cluster(s) as means to provide any linux distro with any combination of stacks a user may want/need while on their nodes. ...this necessary "hack" came up. Hence the post :)

**Comment by dtrudg** [comment]
Hi @milljm - will get back to you some more in a bit, but for now:

> Interesting! It sounds like it might be possible to instruct Singularity what shell we want? Possibly during configure time? I have not studied the ./configure --help output. So, I will take a look after I finish with this post.

I'm afraid not - when I was referring to dash, busybox etc. I meant these things are symlinked to `/bin/sh` under different distributions. We always use `/bin/sh` which may invoke one of the others in a (hopefully) POSIX sh compatible manner.

> The only difference here of course, is that we are leveraging the power and flexibility of running different arches of linux on one host machine.

Do you mean different CPU architectures here.... or testing for amd64 on different distributions, e.g. RHEL6, 7 , Debian 9, 10?

**Comment by dtrudg** [comment]
Actually we do have a `-s` option to shell...

```
singularity shell -s /bin/bash
```

Is this sufficient, or you really need to set the default?

**Comment by milljm** [comment]
> The only difference here of course, is that we are leveraging the power and flexibility of running different arches of linux on one host machine.

> Do you mean different CPU architectures here.... or testing for amd64 on different distributions, e.g. RHEL6, 7 , Debian 9, 10?

I used the wrong word here... I meant 'different' distributions, running on the same host machine.

> Actually we do have a -s option to shell...
> 
> singularity shell -s /bin/bash
> Is this sufficient, or you really need to set the default?

Drats... sorry no dice. While cryptic, the error is thus (and no change from the origin error):

```bash
[lemhi0501][~]> singularity shell -s /bin/bash /apps/moose/moosebuild/containers/Ubuntu-16.simg
/.singularity.d/actions/shell: 7: .: 00-moose_environment.sh: not found
```
Although stated, it is not a 'file not found' issue. The issue is one of the files being sourced (00-moose_environment.sh), contains code to export a function, and then this error pops up.

**Comment by milljm** [comment]
Hmmm I would like to add, that Ubuntu.simg is of old Singularity 2.6 days. I can try to build a container using 3.x, and report back.

[Edit] if it helps
```
[lemhi0501][~]> singularity --version
singularity version 3.4.1-1.2.el7
```

**Comment by mem** [comment]
@milljm out of curiosity, to understand the problem better and maybe suggest a better solution...

Since your goal is reproducibility, why don't you provide a container with the toolchain you want to use set up properly? For example:

    singularity exec env-llvm-8+petsc-3.10.5.sif whatever command

in that way you know that the toolchain and libraries are set up correctly, and whatever change in behavior occurs, comes from changes to the program you are testing.

Is the problem that the number of combinations you have to test is too large? If yes, you have to deal with that anyways, don't you?

You could set up base containers (for example, one for llvm 8, one for PETSc 3.10.5, etc) and the have those available in a known location, and have a .def file that builds a larger container on demand (by using multiple FROM lines pointing to the local smaller containers).

**Comment by milljm** [comment]
@mem, it would be too difficult, unfortunately, to create the number of containers necessary to facilitate the combinations our team tests against. Although, your singularity-foo is probably superior to my own, there may be a better way to do what we are trying to accomplish.

What we are accomplishing now (with a hack of /bin/sh>/bin/bash for two files), is a way to test all combinations using one vanilla container (with minimally installed packages). Upon successful tests of both [redistribution builder](https://civet.inl.gov/repo/112/) and [moose](https://civet.inl.gov/repo/1/), we release **[edit] and build within that container**, what we call a [moose-environment](https://mooseframework.inl.gov/getting_started/index.html) package that can be installed on said linux distribution (for end-users). Apologies for including our entire regression testing system into this post. But I feel allowing you to see it in action may provide a visual idea on just how many different combinations there are.

Building containers on demand is an interesting idea. If not only to solve my bash issue, but... just because. I'll look into that.

**Comment by mem** [comment]
I suspect I understand what you are after.

I would create a container with all the stuff you want in it (llvm, gcc, PETSc, etc) and move the logic that switches environments from the host to the container. This is actually the part that I'm having a hard time picturing. Looking at your matrix I can see multiple distributions, and I see that in a couple of cases you add "GCC" to the label. I assume the others are running LLVM? Or are those runs running multiple builds (like one with LLVM, one with GCC, etc)? I would pass a single environment variable on the singularity command line that a driver script could use to set up the environment inside the container as appropriate, either by calling it directly or specifying it as the "application" to run (see the "run" command).

Also note that singularity performs a little bit of magic: it looks at the SHELL variable in the host and if the specified program is available in the container image, it uses that, otherwise it falls back to /bin/sh.

Also look at `/.singularity.d/actions/run`. For the "run" command you can have a runscript, and that is exec'ed, not source'd, so while that script uses /bin/sh, your runscript could use something else.

And lastly, this is a bit of a hack, but note that if /bin/sh is a symlink to /bin/bash, _most_ scripts will behave as if running with bash, not just a POSIX shell. This is usually considered a bug (google "bashisms") but in your case it seems that it's what you actually want.

**Comment by milljm** [comment]
> I would create a container with all the stuff you want in it (llvm, gcc, PETSc, etc) and move the logic that switches environments from the host to the container. 

I _could_ do that... But unfortunately the processing time it would take to create that many containers on the fly would be problematic (as well as the issue of requiring root privileges during Continuous Integration). Much easier in my opinion to control what toolchain is available using SINGULARITY_BINDPATH; A single static vanilla container, instanced with the proper bind paths is quick and filesystem conservative.

I want to re-iterate my original use-case, as I think we are close to a solution:
Everything is working fine... up to sourcing a file controlled by `/.singularity.d/env/99-startup-environment.sh`. I am using that built-in, in an attempt to initialize Modules for my end-users who wish to invoke Singularity **interactively** (something I may not have been clear about) to debug issues discovered via our Continuous Integration system.

Modules can be initialized if I hack two files: the host's, `/etc/singularity/action/shell`, and the container's `/.singularity.d/env/99-startup-environment.sh` file's shebang lines.

As you say, there is already some magic involved determining which shell environment to use. But I think in this case, these lines are hard-coded (they are shebang lines after all). So back to my second question, is it safe to 'hack' the shebang, without any detrimental security side effects.?. Would you all agree? I only _think_ it is a security risk, because in past versions, action/shell was controlled via the container, and not the host machine. Now, `/.singularity.d/action/shell` seems to be ignored in the container, in favor of what is set in the host's `/etc/singularity/action/shell` script.

Thanks again for your responses!

**Comment by milljm** [comment]
Please disregard much of my last few posts. After building a container _using_ Singularity 3.4.1, I get no errors, but also no Modules environment. I will investigate and post my success/failures.

To be clear, I was using the latest version of Singularity to run containers built by an old version of Singularity (2.6).

**Comment by milljm** [comment]
Okay, as expected:

```
/.singularity.d/actions/shell: 66: export: Illegal option -f
```
The error is certainly not as cryptic as before (file not found). But unfortunately, same results.

Modifying this file, (while present, and looks like it is coming from inside the container)... has no effect on the outcome. However, modifying etc/singularity/actions/shell located on the host machine does, and when specifying bash instead of sh, allows me to source and initialize modules while using the `shell` subcommand.

**Comment by al3x609** [comment]
@milljm You don't need to create a singularity container full of packages, you want to:
1. on the base host, load an lmod environment, consider exported env variables.
2. run the container without clean env flag -e
3. Mount the directory where you have the lmod directory installed and the software required by the latter.

or, 3 and run the lmod script inside the container, in my case
/opt/ohpc/admin/lmod/lmod/init/bash

**Comment by cclerget** [comment]
I'm going to close this one. Feel free to ping to reopen it.
@milljm note that could have a definition file (tested with v3) :

```
bootstrap: docker
from: ubuntu:18.04

%environment
    action=`basename $0`
    if [ "$action" = "shell" ]; then
        export MODULEPATH=
        export SINGULARITY_SHELL=/bin/bash
        set -- "--norc" "-l"
    fi

%post
    apt-get update
    apt-get install -y environment-modules tcl

%runscript
    export MODULEPATH=
    exec /bin/bash --norc -l
```

Ensuring that `shell` and `run` command load modules environment automatically without altering actions script.
