### ISSUE TITLE
Figure out what inspect means in a workflow without setuid

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4724]
### Version of Singularity:

All.

### Expected behavior

We should have a way to access the metadata of an image even in the context of a workflow without setuid.

### Actual behavior

```
$ singularity inspect ./lolcow_latest.sif 
WARNING: No metadata partition, searching in container...
FATAL:   Unable to process command: while running /home/gvallee/install/singularity_master/libexec/singularity/bin/starter-suid: exit status 1: ERROR  : Failed to set effective UID to 0
```

### Steps to reproduce this behavior

In a context of a workflow without setuid, create an image with metadata and try to use the `inspect` command on the image. It will return an unclear error message.

### What OS/distro are you running

All.

### How did you install Singularity

Any method

**Comment by gvallee** [comment]
@cclerget would `fakeroot` be an option here? Something like `singularity inspect --faeroot <myimage>`

**Comment by dtrudg** [comment]
AFAIK `--fakeroot` does not help here, as it's on the host we need root to do the mount. My gut feeling is that `inspect` should extract to a sandbox via an unprivileged `unsquashfs` , and then inspect the meta data within the sandbox.

**Comment by cclerget** [comment]
@gvallee As @dctrud mentioned, there was a PR doing the squashfs extraction for unprivileged installation (https://github.com/sylabs/singularity/pull/3801), but the problem is that unprivileged installation can only inspect squashfs/SIF image not ext3 images and the same limitation apply for shell/exec commands
