### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by soichih** [apptainer/singularity#4725]
I am using singularity 3.4.2 on Indiana University Bigred3 cluster.

It looks like our cluster node doesn't have ca-certificate package installed (yet) and when singularity tries to download a container from dockerhub, it runs into the following error.

```
$ singularity exec -e docker://python python --version
FATAL:   Unable to handle docker://python uri: failed to get SHA of docker://python: pinging docker registry returned: Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority
```

Are there equivalent singularity options for `--insecure-registry` for Docker? Can I instruct singularity to skip the CA test? Our sys admin says they can install the ca-certificates next month, but I'd like to get things moving before it.

**Comment by dtrudg** [comment]
Hi - as we are using `containers/image` as the library behind this, you should be able to instruct it to use a registry insecurely via configuration file detailed here:

https://github.com/containers/image/blob/master/docs/containers-registries.conf.5.md

**Comment by dtrudg** [comment]
Note that an issue was just fixed with insecure overrides in `registries.conf` via this PR: https://github.com/sylabs/singularity/pull/5179

If you are able to try this from the `master` branch and still have problems, please let us know.
