### ISSUE TITLE
Could not set NO_NEW_PRIVS safeguard: Invalid argument

### ISSUE THREAD

**Issue by chiroptical** [apptainer/singularity#473]
I was able to run my container locally, but I am having some issues after I migrate to another system. Built container on Arch, trying to run on RHEL 6.6. Built from same git commit on both systems.

Running: `singularity -d shell arch.img > issue.txt 2>&1`
Towards the bottom:

```
DEBUG   [U=152336,P=26281] privilege.c:355:singularity_priv_drop_perm(): Confirming we have correct GID
DEBUG   [U=152336,P=26281] privilege.c:361:singularity_priv_drop_perm(): Confirming we have correct UID
DEBUG   [U=152336,P=26281] privilege.c:369:singularity_priv_drop_perm(): Setting NO_NEW_PRIVS to prevent future privilege escalations.
VERBOSE [U=152336,P=26288] fork.c:157:singularity_fork()              : Hello from child process
DEBUG   [U=152336,P=26288] fork.c:160:singularity_fork()              : Closing watchdog write pipe
ERROR   [U=152336,P=26281] privilege.c:371:singularity_priv_drop_perm(): Could not set NO_NEW_PRIVS safeguard: Invalid argument
ABORT   [U=152336,P=26281] privilege.c:372:singularity_priv_drop_perm(): Retval = 255
ERROR   [U=152336,P=26288] fork.c:105:wait_for_go_ahead()             : Parent closed write pipe unexpectedly.
ABORT   [U=152336,P=26288] fork.c:106:wait_for_go_ahead()             : Retval = 255
```

Does this mean anything to you? I can add more of the debugging output if you need it.

**Comment by bbockelm** [comment]
Hi,

`NO_NEW_PRIVS` was not backported until later in the RHEL6 series - I think either 6.7 or 6.8.

Where was singularity compiled?  Typically, this feature will be disabled if it's not in the kernel headers at compile time.  Is it possible it was compiled on a head node running RHEL6.8 and failing on the worker nodes running RHEL6.6?

This is definitely a problem with the runtime; should have nothing to do with the container you put together.

Brian

**Comment by chiroptical** [comment]
I compiled and ran Singularity on:

```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.6 (Santiago)
$ uname -r
2.6.32-358.23.2.el6.x86_64
```

I should have RHEL 6.7 instance to test on tomorrow. Thanks Brian!

**Comment by gmkurtzer** [comment]
Heya. I just wanted to circle back to this and ask if you can also test against the "development" branch?

Thanks!
