### ISSUE TITLE
Time out Xenial

### ISSUE THREAD

**Issue by Lcornet** [apptainer/singularity#4733]
### Expected behavior

Build container with debootstrap and Xenial

### Actual behavior

Creation crash due to time out

0 upgraded, 308 newly installed, 0 to remove and 0 not upgraded.
Need to get 152 MB of archives.
After this operation, 600 MB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libatm1 amd64 1:2.5.1-1.5 [24.2 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libmnl0 amd64 1.0.3-5 [12.0 kB]
Err:2 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libmnl0 amd64 1.0.3-5                                                
  Connection timed out [IP: 91.189.91.14 80]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libgdbm3 amd64 1.8.3-13.1 [16.9 kB]                                  
Err:3 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libgdbm3 amd64 1.8.3-13.1                                            
  Connection timed out [IP: 91.189.91.14 80]
Get:4 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libxau6 amd64 1:1.0.8-1 [8376 B]
0% [4 libxau6 8376 B/8376 B 100%] %]

### Steps to reproduce this behavior

BootStrap: debootstrap  #Create of Virgin Linux
OSVersion: xenial  #Choose the Xenial version of Linux, 16.04
MirrorURL: http://us.archive.ubuntu.com/ubuntu/  #Source to download

%post
    #Update part
    sed -i 's/$/ universe/' /etc/apt/sources.list
    apt-get update && apt-get install -y netcat
    #permission part
    chmod -R 777 /opt #chmod775 can be enough
    chmod -R 777 /root #chmod775 can be enough
    #r and git
    apt-get install -y r-base-core

sudo singularity build --force test.img test.def

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

https://sylabs.io/guides/3.0/user-guide/installation.html

**Comment by dtrudg** [comment]
This is not an issue with Singularity itself - one of the ubuntu mirrors seems to have been having an issue, or there is a connectivity issue from your site to it.

If you hit this issue you can use another mirror from this list: https://launchpad.net/ubuntu/+archivemirrors

**Comment by dtrudg** [comment]
Closing this as there hasn't been any follow up. Please feel free to reopen if you feel there as issue in Singularity. Thanks.
