### ISSUE TITLE
Running Juypyter notebook within OSX

### ISSUE THREAD

**Issue by gwong-astro** [apptainer/singularity#4738]
### Expected behavior

Within OSX, run singularity, then Jupyter notebook and then access the notebook via browser from the given URLs.

### Actual behavior

After running the jupyter notebook command, I am unable to access the notebook via browser.  Also one of the urls provided is incorrect.
```
http://(none):8888/?token=dc6ce2958b3dc3f782df4b79a46ad05d5a148adcfaaa7ac9
```

Would this be related to singularity environment variables not being transferred in macOS (#4476 and #4368)?

### What OS/distro are you running

```
OSX 10.14.6

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

**Comment by dtrudg** [comment]
Will have to look into this further - but there is some relevant information here: https://github.com/sylabs/singularity/issues/4364

I don't believe it's related to env vars.

**Comment by dtrudg** [comment]
Closing as Singularity Desktop currently not maintained.
