### ISSUE TITLE
ERROR  : Failed to resolve path to /home/user/miniconda3/var/singularity/mnt/container: No such file or directory ABORT  : Retval = 255

### ISSUE THREAD

**Issue by andrewmlynn** [apptainer/singularity#4739]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```
2.6.0

### Expected behavior

What did you expect to see when you do...?

### Actual behavior

What actually happend? Why was it incorrect?

ERROR  : Failed to resolve path to /home/user/miniconda3/var/singularity/mnt/container: No such file or directory
ABORT  : Retval = 255

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release


```
NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.04"
VERSION_ID="19.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
conda install -c conda-forge singularity

**Comment by dtrudg** [comment]
@lynngroup - what is your username / home dir on this system? Singularity cannot be relocated after it is built, so in this case it needs to be under exactly `/home/user/miniconda3/` - is this the case for you?
