### ISSUE TITLE
Building/installing singluarity via AWS ec2 launch script : mconfig fails to find "go"

### ISSUE THREAD

**Issue by nyue** [apptainer/singularity#4751]
### Version of Singularity:

3.5.0

### Expected behavior

I expect that if golang is installed, the compiler is found

### Actual behavior
```
Nov 18 02:39:17 ip-172-31-7-48 cloud-init[1858]: + go version
Nov 18 02:39:17 ip-172-31-7-48 cloud-init[1858]: go version go1.13.4 linux/amd64
```
```
Nov 18 02:39:22 ip-172-31-7-48 cloud-init[1858]: + ./mconfig -v
Nov 18 02:39:22 ip-172-31-7-48 cloud-init[1858]: Configuring for project `singularity' with languages: C, Golang
Nov 18 02:39:22 ip-172-31-7-48 cloud-init[1858]: => running pre-basechecks project specific checks ...
Nov 18 02:39:22 ip-172-31-7-48 cloud-init[1858]: => running base system checks ...
Nov 18 02:39:22 ip-172-31-7-48 cloud-init[1858]:  checking: host C compiler... cc
Nov 18 02:39:22 ip-172-31-7-48 cloud-init[1858]:  checking: host C++ compiler... c++
Nov 18 02:39:23 ip-172-31-7-48 cloud-init[1858]:  checking: host Go compiler (at least version 1.13)... not found!
Nov 18 02:39:23 ip-172-31-7-48 cloud-init[1858]: mconfig: could not complete configuration
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

Ubuntu 18.04 on AWS EC2

### How did you install Singularity
```
#!/bin/sh                                                                                                                                                     
set -e -x
add-apt-repository -y ppa:longsleep/golang-backports
apt-get -y update
apt-get install -y \
    golang-go
go version
apt-get install -y \
    build-essential \
    libssl-dev \
    uuid-dev \
    libgpgme11-dev \
    squashfs-tools \
    libseccomp-dev \
    pkg-config \
    git \
    cryptsetup
export VERSION=3.5.0
cd /tmp
curl -L -O https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
tar -xzf singularity-${VERSION}.tar.gz
cd singularity
./mconfig -v
make -C builddir
make -C builddir install
```

**Comment by cclerget** [comment]
Hi @nyue , `./mconfig` search go binary based on `PATH` but on ubuntu generally golang binary is installed in `/usr/lib/go-1.XX` and create a symlink `/usr/lib/go -> /usr/lib/go-1.XX`, as this is not a "standard" path location you will need to add `/usr/lib/go/bin` manually to your `PATH`. Also see https://github.com/golang/go/wiki/Ubuntu.

**Comment by Vincent-wq** [comment]
> Hi @nyue , `./mconfig` search go binary based on `PATH` but on ubuntu generally golang binary is installed in `/usr/lib/go-1.XX` and create a symlink `/usr/lib/go -> /usr/lib/go-1.XX`, as this is not a "standard" path location you will need to add `/usr/lib/go/bin` manually to your `PATH`. Also see https://github.com/golang/go/wiki/Ubuntu.

Hi, I have tried to install from the 3.5.0 man on a 18.04 ubuntu, tried to install go 1.1.2 and 1.1.3, they can be installed correctly, with go version showing the right version, however, I did not see /usr/lib/go-1.xx, if install go as nyue did, just install using apt install golang, then I ahve go-1.1.3, but even if I created the soft link go <- go-1.13, but the problem persists.
After this, I got the same problem even when installing singularity 3.4.1.

**Comment by nyue** [comment]
I have also tried appending /usr/lib/go/bin to $PATH but the problem still exists.

**Comment by Amir-Arsalan** [comment]
@cclerget Same issue here:

![image](https://user-images.githubusercontent.com/6061721/69079859-e7037100-0a08-11ea-8e84-70426c6c9a13.png)

**Comment by Vincent-wq** [comment]
> Hi @nyue , `./mconfig` search go binary based on `PATH` but on ubuntu generally golang binary is installed in `/usr/lib/go-1.XX` and create a symlink `/usr/lib/go -> /usr/lib/go-1.XX`, as this is not a "standard" path location you will need to add `/usr/lib/go/bin` manually to your `PATH`. Also see https://github.com/golang/go/wiki/Ubuntu.

Hi, I just figure out that it might be a problem of multiple installation, for my case, I simply do the following:
1. rm -rf /usr/local/go 
remove go programs
2. rm -rf /usr/lib/go go-1.13
remove the other installation from apt
3. rm -rf go
remove the go work directory;
4. export VERSION=1.13 OS=linux ARCH=amd64 && \
    wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
    sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz && \
    rm go$VERSION.$OS-$ARCH.tar.gz
download 1.13 go
5. nothing to do here, preserve the path I have put in .bashrc
6. cd builddir
then make
7. sudo make 
It works for me.

**Comment by nyue** [comment]
The following works for my use case (ansible+ec2+user_data) fully automated build.

The user_data script is as follows, to work around the mconfig issues

I'll close this for now, someone with deeper knowledge of mconfig may be able to figure out why it only runs as non-root user in the above scenario.

```
#!/bin/bash
set -e -x
apt-get -y update
apt-get install -y \
    build-essential \
    libssl-dev \
    uuid-dev \
    libgpgme11-dev \
    squashfs-tools \
    libseccomp-dev \
    pkg-config \
    git \
    cryptsetup
cd /tmp
curl -L -O https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
tar -xf go1.13.4.linux-amd64.tar.gz
mv go /usr/local/
# Build must be done as non-root, otherwise, mconfig will fail to find "go"
su - ubuntu -c "cd /tmp && export PATH=/usr/local/go/bin:$PATH && curl -L -O https://github.com/sylabs/singularity/releases/download/v3.5.0/singularity-3.5.0.tar.gz && tar -xzf singularity-3.5.0.tar.gz && cd singularity && ./mconfig && make -C builddir && sudo make -C builddir install"
```

**Comment by Amir-Arsalan** [comment]
@Vincent-wq Thanks! This worked for me. 

@cclerget I would recommend adding some instructions for upgrading Singularity to the documents.

**Comment by MuhsinFatih** [comment]
@nyue 's answer worked for me.
I think installation should be either by apt package or by using an .sh file or some sort like nyue's solution to simplify things. Official 3.5 installation guide calls compiling the source code "quick installation steps". In what parallel universe is installing dependencies by hand and compiling source code the "quick" installation?

**Comment by sknigh** [comment]
This isn't fixed, I am seeing this behavior in Spack builds. Spack installs go 1.13 in a user directory, and adds that directory to PATH. I have verified that the PATH is in the environment, but mconfig fails to find it. I am getting the above error with Singularity 3.5.2 and 3.4.1.

**Comment by jmstover** [comment]
@sknigh From the Singularity source directory, can you run:
```
env GO111MODULE=off go run mlocal/checks/version.go go1.13
```
One thing to try (though you _shouldn't_ need to) is run:
```
sed -i.bak "s|^\(hstgo=\).*|\1$(command -v go)|" mconfig
```

That will explicitly set the `hstgo` variable to the full path of the go binary, and that will be called in `basechecks.chk`

**Comment by sknigh** [comment]
Thanks for the help @jmstover. Initially I couldn't get the first suggestion to work at all, so I removed apt-installed Go 1.10 and 1.11. That didn't fix so I cleared GOROOT. After that the build system started working with my Spack-installed Go 1.13 without any changes to Singularity's build system.
