### ISSUE TITLE
Underlay failure when cwd in a /tmp subdirectory

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#4755]
### Version of Singularity:

3.5.0-1.el7

### Expected behavior

singularity execs a container no matter the current working directory

### Actual behavior

If the cwd is a subdirectory of /tmp and the container image has a file in /tmp, singularity exec fails with
```
FATAL:   container creation failed: mount /var/singularity/mnt/session/rootfs/tmp/anaconda-post.log->/var/singularity/mnt/session/underlay/tmp/anaconda-post.log error: while mounting /var/singularity/mnt/session/rootfs/tmp/anaconda-post.log: destination /var/singularity/mnt/session/underlay/tmp/anaconda-post.log doesn't exist in container
```

### Steps to reproduce this behavior

```
$ mkdir /tmp/tstdir
$ cd /tmp/tstdir
$ singularity exec docker://centos:6 id
```

### What OS/distro are you running

By default on centos6, and on centos7 when either setuid or overlay set to no.

### How did you install Singularity

yum --enablerepo=epel-testing install singularity

**Comment by DrDaveD** [comment]
This is an important issue for us because it broke an OSG automated test.

**Comment by dtrudg** [comment]
Hi @DrDaveD - we will certainly try and get something sorted for a timely 3.5.1.

However, this is a lower priority than e.g. the btrfs issue (which causes blanket failure), as it should be possible to workaround by by changing the cwd if I understand correctly.

**Comment by cclerget** [comment]
@DrDaveD Can you confirm #4759 ? Thanks !

**Comment by DrDaveD** [comment]
@cclerget Yes, that fix works well for me.
