### ISSUE TITLE
Can't build singularity for epel8 because of golang-1.13 requirement

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#4756]
### Version of Singularity:

3.5.0

### Expected behavior

Ability to be built for epel8

### Actual behavior

Build dies because golang-1.13 is not available.  The epel golang provider says in this [ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1772221) he is not allowed to build it for epel8.

**Comment by dtrudg** [comment]
Let's discuss in the developer meeting tomorrow before having more comment here.

**Comment by dtrudg** [comment]
It appears that go 1.13 might end up as a go-toolset for RHEL8 soon. Trying to find out about this, as it would solve the problem I think.

**Comment by dtrudg** [comment]
This was discussed in the community development meeting today.

@DrDaveD is going to patch out the `-trimpath` and Go 1.13 requirement to build an EPEL8 package with the Go 1.11.6 that is available there. This package will not be able to work correctly with any plugins.

It is hoped that a Go 1.13 toolset will appear for RHEL8 soon, making this a temporary issue.

**Comment by dtrudg** [comment]
Marked as a wontfix for us, as this is going to be handled in distro packaging, and not in the Singularity tree.

The distro patch to build for RHEL8 / CentOS8 in #4769 that is mentioned here will not be merged here, and will break plugin functionality.
