### ISSUE TITLE
Odd exit behavior when building PETSc within Singularity recipe

### ISSUE THREAD

**Issue by milljm** [apptainer/singularity#4757]
### Version of Singularity:

3.5.0

### Expected behavior

Container is built with everything included in %post operation.

### Actual behavior

Container is built with only having partially completed the %post operation.

### Steps to reproduce this behavior

Here is my recipe. Note, I added an '-->' to denote where the %post operation appears to exit.

```
BootStrap: yum
OSVersion: 8
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/BaseOS/$basearch/os
Include: yum

%environment
    RELEASE="CentOS 8"
    export RELEASE

%post
    yum -y groupinstall "Development Tools"
    yum config-manager --set-enabled PowerTools
    yum -y install gcc-gfortran mpich-devel python36-devel cmake rsync
    PATH=/usr/lib64/mpich/bin:$PATH

    # Create python -> python3 symlink
    cd /bin
    ln -s python3.6 python
    ln -s python3-config python-config

    #### Install PETSc ####
    export PETSC_VERSION=3.11.4
    export TMP_LOC=`mktemp -d /tmp/petsc.XXXX`
    cd ${TMP_LOC}
    curl -L -O http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-${PETSC_VERSION}.tar.gz
    tar -xf petsc-${PETSC_VERSION}.tar.gz
    cd petsc-${PETSC_VERSION}

--> ./configure --prefix=/opt/petsc-${PETSC_VERSION} --download-fblaslapack=1 PETSC_ARCH=linux
    echo "I never make it here. Container is built... No errors."
    make PETSC_DIR=`pwd` PETSC_ARCH=linux all
    make PETSC_DIR=`pwd` PETSC_ARCH=linux install

    #### Build foo ####
    make
    make install
```

My singularity build command:
`sudo singularity build /containers/CentOS.sif CentOS-petsc`

### What OS/distro are you running

CentOS 8

### How did you install Singularity

From source; eg `git clone, git checkout v3.5.0`, using go 1.13.3.

### Additional Thoughts
I've built many things from source with no issues within %post. So I know this is more a PETSc issue _somehow_ rather than a Singularity one. Perhaps python is to blame (PETSc configure is a python script). I figured I would post, as what I am assuming can only be an exit code of 0 due to Singularity continuing and building the sif image, yet ignores additional commands. Here is an excerpt of what I am seeing with the above recipe:

```pre
+ tar -xf petsc-3.11.4.tar.gz
+ cd petsc-3.11.4
+ ./configure --prefix=/opt/petsc-3.11.4 --download-fblaslapack=1
...
...
<trimmed>
...
...
  shared libraries: enabled
  Memory alignment: 16
xxx=========================================================================xxx
 Configure stage complete. Now build PETSc libraries with (gnumake build):
   make PETSC_DIR=/tmp/petsc.s2rY/petsc-3.11.4 PETSC_ARCH=arch-linux-c-debug all
xxx=========================================================================xxx
INFO:    Adding environment to container                                                                                                 
INFO:    Creating SIF file...
INFO:    Build complete: /containers/CentOS.sif
```

If it helps, I originally ran into this error with Singularity 3.4.1. And thus, upgraded to 3.5.0 in an attempt to solve the issue.

**Comment by cclerget** [comment]
Hi @milljm , the build process pass the section script over stdin (it's done like that for version 2/3 of Singularity) and it looks like `configure` read stdin and consume the remaining bytes of the "piped" script so everything after the `configure` is somehow truncated for the default shell here `bash` when it attempt to read the next line from stdin it get an EOF and exit normally, the command below prevent `configure` to read stdin and the post section is executed correctly :

```
./configure --prefix=/opt/petsc-${PETSC_VERSION} --download-fblaslapack=1 PETSC_ARCH=linux 0>/dev/null
```

This behavior depends of the shell used, there is no issue with `busybox` or `dash` but it could occur with larger post section. A user reported a similar behavior mentioning that the post script was truncated and that by reducing the size he was able to execute the section correctly.

Anyway it's something to fix in Singularity to avoid those issues.

**Comment by milljm** [comment]
@cclerget Thank you for the explanation and work-around!
