### ISSUE TITLE
disable/enable encryption features in configuration (e.g. sys admins of a shared system)

### ISSUE THREAD

**Issue by marcodelapierre** [apptainer/singularity#4758]
Hi,
from the perspective of systems administrators of an HPC centre,
it would really be handy to be able to control the ability of users to run encrypted containers.

This is one of the main reasons that is currently holding me from upgrading singularity to a version later than 3.3.0 on a shared system.

I have seen #4588 and #4506, but these don't really get to the point as far as I am concerned.

Any perspective on this?

Thanks,
Marco

**Comment by dtrudg** [comment]
Hi Marco. A config option to disable encryption support isn't something we'd thought of. I wonder if you could give some more information r.e. what is the concern, or why there is a specific need to prevent execution of encrypted containers?

Thanks.

**Comment by marcodelapierre** [comment]
Hi David, thanks for getting back so promptly. 

At this stage, the concern is about potential workflows where a user of a shared public facility (such as an HPC centre) downloads and runs an encrypted container image whose content violates some of the facility policies. System administrators would have a very hard time in capturing this behaviour.
If it's true that in principle this can occur also with precompiled binaries, the ease of deploying large, elaborated software stacks inside a container increases the size of this potential issue.

My view is that it would be good to give sys administrators the faculty of deciding on whether the feature can be used or not in their facility. This would be in line, say, with the current options in the config file to allow containers to be run only from certain directory paths. This can still be used as an extreme way of controlling what users of a shared facility are running. However, I think that a fine grained control on features, such as running encrypted images, would give more freedom of configuration to sys admins.

Cheers, Marco

**Comment by dtrudg** [comment]
hi @marcodelapierre - could you take a look at the linked PR #4761 and let us know if that meets your need? Cheers.

**Comment by marcodelapierre** [comment]
This is exactly what I was talking about, many thanks for tackling this so quickly!
