### ISSUE TITLE
Fail to link a shared library to my program, but no error message during compile and link

### ISSUE THREAD

**Issue by hewanbing** [apptainer/singularity#4764]
### Version of Singularity:

3.5.0+33-g7b10707

### Expected behavior

What did you expect to see when you do...?
I want compile my c++ code ，and then link it with a shared library

### Actual behavior

There is not any error during compile and link
But when I check the links by “ldd -r“
The shared library I linked is not shown, but lots of undefined symbols.

### Steps to reproduce this behavior

1. build my local SIF from  library://sylabs-jms/testing/lolcow
2. within the container
    apt update
    install cmake 3.16
    install root6.18
    source thisroot.sh

3. compile my code

c++ -O2 -Wall -fPIC -pthread -std=c++11 -m64 -I/usr/local/include -I/*** -w -c myCode.cxx

4. link myCode with a given shared library

c++ -O2 -m64 -L/*** -L/usr/local/lib -lGui -lCore -lotherLibsFromROOT -g -L. -lSharedLib(this is a prepared lib)  myCode.o myCodeDict.o -shared -o libMyCode.so

5. check the links of libMyCode.so

ldd -r libMyCode.so

there is not any lib from root , and libSharedLib(my  prepared lib).
show:
        linux-vdso.so.1 =>  (0x00007ffe10974000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6dbea3d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6dbe827000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6dbe60a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6dbe240000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6dbdf37000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6dbefc4000)
       ****and lots of undefined symbol***

BTW, The same codes work well in a general ubuntu16 

### What OS/distro are you running

NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

### How did you install Singularity

source

**Comment by cclerget** [comment]
Hi @hewanbing , it looks like an issue with `LD_LIBRARY_PATH` not correctly set to point to the directory where other library dependencies are, this is not a Singularity issue just a misconfiguration of your build environment.

**Comment by hewanbing** [comment]
Hi @cclerget . I checked my  LD_LIBRARY_PATH, which is correct. When I switch to a CentOS, all the undefined symbols disappear.  It is not an issue of Singularity. There must be something wrong with my Ubuntu settings, and I still can not figure it out
