### ISSUE TITLE
Singularity start-up failure at extreme scale; LDAP requests overwhelming network infrastructure

### ISSUE THREAD

**Issue by masalim2** [apptainer/singularity#4767]
### Version of Singularity:

```
$ singularity version
3.2.1-1
```

### Expected behavior

We are attempting to strong-scale a quantum chemistry simulation code inside a Singularity container on the Argonne LCF's Theta supercomputer (a Cray XC40).  While the code inside the container links to an internal Intel MPI, we are able to swap in the Cray MPICH ABI-compatible libraries at runtime to scale on the Cray Aries network.  

This is our generic wrapper for running a Singularity container, using the LD_LIBRARY_PATH trick to swap-in host Cray MPICH at runtime:
```
#!/bin/bash
# singularity-run-theta.sh

module swap cray-mpich cray-mpich-abi
export LD_LIBRARY_PATH=/opt/cray/wlm_detect/default/lib64:$CRAY_LD_LIBRARY_PATH:$LD_LIBRARY_PATH
export SINGULARITYENV_LD_LIBRARY_PATH=/opt/cray/wlm_detect/default/lib64:$CRAY_LD_LIBRARY_PATH:$LD_LIBRARY_PATH

sleep $(($RANDOM % 30))
singularity run -B /opt/cray -B /etc/alternatives $@
```

The container is invoked like this:
```

aprun -n 8192 -N 64 singularity-run-theta /path/to/container <args>
```

Running our simulation on a fixed problem size scales beautifully up to 512 nodes * 64 ranks/node (32768 singularity run processes) (nearly 100% strong scaling efficiency).

We *expect* that running at 1024 nodes should work as well:

```
$ aprun -n65536 -N64 ...
```

### Actual behavior

When we attempt to run with 65,536 ranks, the application inside the container fails to start; I see these errors coming from many ranks:

```
user: lookup userid 33180: connection refused
FATAL:   user: unknown userid 33180
```

followed by MPI Init errors, presumably from the ranks that are left hanging:
```
Tue Nov 19 18:57:52 2019: [PE_59072]:inet_connect:inet_connect: connect failed after 301 attempts
20 Tue Nov 19 18:57:52 2019: [PE_59072]:_pmi_inet_setup:inet_connect failed
19 Tue Nov 19 18:57:52 2019: [PE_59072]:_pmi_init:_pmi_inet_setup (full) returned -1
15 [Tue Nov 19 18:57:52 2019] [c1-1c2s12n0] Fatal error in MPI_Init: Other MPI error, error stack:
14 MPIR_Init_thread(537):
13 MPID_Init(246).......: channel initialization failed
12 MPID_Init(647).......:  PMI2 init failed: 1
```

We learned that this behavior is not due to Singularity *per se* -- the large number of `getuid()`, `getpwuid()` and similar calls that are invoked in the SetUID flow are hammering our supercomputer's LDAP service and causing denial of service.   The issue has been described like this:

"The apparent LDAP limitation, as we may have mentioned before, is not a result of limitations in LDAP itself, but is a result of the network configuration provided to ALCF by Cray in Theta. The RSIP network translation layer is not compatible with a large number of concurrent network connections from the compute environment outbound to any management infrastructure.

Any time you increase the number of outbound connections from the compute nodes (ie, to anything that is not a compute node or a mom node), you increase the change of encountering this issue, or potentially triggering this issue for someone else.

Our networking team is investigating potential replacement hardware to replace the Cray-provided networking.  Any replacement of the RSIP will require significant effort, and I do not have an ETA for that work."

----

Have other folks experienced this issue when trying to scale-up MPI Singularity applications? Clearly, there is a problem on our side  that will hopefully be resolved in a longer time frame.  We have attempted to use random sleeps (see wrapper script above) and LD_PRELOADing a dummy `getpwuid()` to avoid this issue, but the SetUID flow seems to hit LDAP too much in spite of our efforts.   If there are any best practices we are missing or suggestions to mitigate the issue from the Singularity startup side, we would be very grateful in the mean time!

### Steps to reproduce this behavior

Since this is a network infrastructure issue on our supercomputer, it is not easily reproducible outside of attempting to scale to 65,536 MPI ranks on 1024 nodes on Theta at Argonne LCF:

```
$ aprun -n65536 -N64 singularity run ... 
```

### What OS/distro are you running

Running on Argonne's Theta Cray XC40.  Both MOM nodes (where jobs are launched with "aprun") and compute nodes have the following OS:

```
$ cat /etc/os-release
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"
```

### How did you install Singularity

Not sure -- Installed by ALCF sys admins.

**Comment by frankwillmore** [comment]
Our singularity was built as an RPM and installed to the Cray image. The .spec file used to build it is here:
```# 
# Copyright (c) 2017-2018, SyLabs, Inc. All rights reserved.
# Copyright (c) 2017, SingularityWare, LLC. All rights reserved.
#
# Copyright (c) 2015-2017, Gregory M. Kurtzer. All rights reserved.
# 
# Copyright (c) 2016, The Regents of the University of California, through
# Lawrence Berkeley National Laboratory (subject to receipt of any required
# approvals from the U.S. Dept. of Energy).  All rights reserved.
# 
# This software is licensed under a customized 3-clause BSD license.  Please
# consult LICENSE file distributed with the sources of this project regarding
# your rights to use or distribute this software.
# 
# NOTICE.  This Software was developed under funding from the U.S. Department of
# Energy and the U.S. Government consequently retains certain rights. As such,
# the U.S. Government has been granted for itself and others acting on its
# behalf a paid-up, nonexclusive, irrevocable, worldwide license in the Software
# to reproduce, distribute copies to the public, prepare derivative works, and
# perform publicly and display publicly, and to permit other to do so. 
# 
# 

%define singgopath src/github.com/sylabs/singularity

# Disable debugsource packages; otherwise it ends up with an empty %files
#   file in debugsourcefiles.list on Fedora
%undefine _debugsource_packages

Summary: Application and environment virtualization
Name: singularity
Version: 3.2.1
Release: 1%{?dist}
# https://spdx.org/licenses/BSD-3-Clause-LBNL.html
License: BSD-3-Clause-LBNL
URL: https://www.sylabs.io/singularity/
Source: %{name}-%{version}.tar.gz
ExclusiveOS: linux
%if "%{_target_vendor}" == "suse"
%if "%{sles_version}" != "11"
#BuildRequires: go
%endif
%else
BuildRequires: golang
%endif
BuildRequires: git
BuildRequires: gcc
BuildRequires: make
BuildRequires: libuuid-devel
BuildRequires: openssl-devel
%if ! 0%{?el6}
%if "%{sles_version}" != "11"
#BuildRequires: libseccomp-devel
%endif
%endif
%if "%{_target_vendor}" == "suse"
Requires: squashfs
%else
Requires: squashfs-tools
%endif

# there's no golang for ppc64, just ppc64le
ExcludeArch: ppc64

Provides: %{name}-runtime
Obsoletes: %{name}-runtime

%description
Singularity provides functionality to make portable
containers that can be used across host environments.

%if "1" != "1"
%debug_package
%endif

%prep
# Create our build root
rm -rf %{name}-%{version}
mkdir %{name}-%{version}

%build
cd %{name}-%{version}

mkdir -p gopath/%{singgopath}
tar -C "gopath/src/github.com/sylabs/" -xf "%SOURCE0"

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH
cd $GOPATH/%{singgopath}
go version
# Not all of these parameters currently have an effect, but they might be
#  used someday.  They are the same parameters as in the configure macro.
./mconfig -V %{version}-%{release} \
        --prefix=%{_prefix} \
        --exec-prefix=%{_exec_prefix} \
        --bindir=%{_bindir} \
        --sbindir=%{_sbindir} \
        --sysconfdir=%{_sysconfdir} \
        --datadir=%{_datadir} \
        --includedir=%{_includedir} \
        --libdir=%{_libdir} \
        --libexecdir=%{_libexecdir} \
        --localstatedir=%{_localstatedir} \
        --sharedstatedir=%{_sharedstatedir} \
        --mandir=%{_mandir} \
        --infodir=%{_infodir}

#cd builddir
#make old_config=
make -C builddir DESTDIR=RPM_BUILD_ROOT

mkdir -p $RPM_BUILD_ROOT%{_mandir}/man1
make -C builddir DESTDIR=$RPM_BUILD_ROOT install man

%install
cd %{name}-%{version}

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH
cd $GOPATH/%{singgopath}/builddir

mkdir -p $RPM_BUILD_ROOT%{_mandir}/man1
#make -C builddir DESTDIR=$RPM_BUILD_ROOT man
chmod 644 $RPM_BUILD_ROOT%{_sysconfdir}/singularity/actions/*

%files
%attr(4755, root, root) %{_libexecdir}/singularity/bin/starter-suid
%{_bindir}/*
%dir %{_libexecdir}/singularity
%{_libexecdir}/singularity/bin/starter
%{_libexecdir}/singularity/cni/*
%dir %{_sysconfdir}/singularity
%config(noreplace) %{_sysconfdir}/singularity/*
%attr(755, root, root) %{_sysconfdir}/singularity/actions/exec
%attr(755, root, root) %{_sysconfdir}/singularity/actions/run
%attr(755, root, root) %{_sysconfdir}/singularity/actions/shell
%attr(755, root, root) %{_sysconfdir}/singularity/actions/start
%attr(755, root, root) %{_sysconfdir}/singularity/actions/test
%dir %{_sysconfdir}/bash_completion.d
%{_sysconfdir}/bash_completion.d/*
%dir %{_localstatedir}/singularity
%dir %{_localstatedir}/singularity/mnt
%dir %{_localstatedir}/singularity/mnt/session
# XXX: Not great since we can't control this location...
%{_mandir}/man1/*


%changelog
```

**Comment by frankwillmore** [comment]
The working theory is that the failure is occurring because singularity is effectively DOS-ing our LDAP. I put together a simulator to test this, but we don't want to run while in production because it may affect other jobs. 

https://github.com/frankwillmore/getpwuid_dos

**Comment by dtrudg** [comment]
There are likely relatively few things that can be done here. It is important that Singularity checks user information around some operations. It is also going to e.g. create in-container `passwd` files containing the calling user/group information, which requires these lookups. 

I don't believe we make a huge number of calls in each Singularity process, but there will be many if a lot of instances are being started. I'd anticipate strategies such as using a node-local cache via `sssd` or `nscd` etc. or other propagation to the node might be a mitigation

I'll try and trace how many `getpwuid` calls there are - but I don't think it's excessive for what we need to do.

@gmkurtzer and @gvallee have participated in some discussion on slack, and may wish to comment here.

**Comment by gmkurtzer** [comment]
Singularity does in fact run a bunch of `getpw*()` library calls which will absolutely exacerbate the scalability issues with LDAP. I'm not sure how much more caching we can do of user credentials in Singularity.

In Warewulf, we saw this scalability issue (ages ago), and it was handled by having the "master node" pull the allowed user information from LDAP, caching it, and sending it out as files to all of the compute nodes. This alleviates LDAP completely for the compute nodes.

There might be another option if you are using munge on the compute nodes (Slurm generally requires this). I don't remember the specifics, but I thought you can tweak your nsswitch.conf to use Munge for local credential look ups instead of relying on LDAP. I maybe mis-remembering here, so let me know if I'm off base please.

**Comment by masalim2** [comment]
Thanks for the feedback guys, this is very helpful.  I passed on to our internal ALCF support channel these 3 possible mitigation strategies (rootless+LD_PRELOAD hack, node-local cache, one node fetch & proxy getpw* results).    Hopefully one of them pans out because we are eager to show some results of scaling Singularity to the whole system.

**Comment by al3x609** [comment]
@masalim2 , there is some approach that you can try: 

> the problem here is the overhead to get user info from LDAP server

a) replace LDAP client utilities with a [sssd](https://docs.pagure.org/SSSD.sssd/)  daemon per node, and configure it for a better performance response with an ldap cache.

b) for MPI, consider bootstrap MPI processes with pmix over pmi2, and reconfigure the workload manager for work with that.

c) for LDAP: 
-  prepare  your setup with [LDAP multi mirror mode](http://www.openldap.org/doc/admin24/replication.html#MirrorMode).
- use a MDB database backend.
- reconfigure ldap membership with dynamic groups overlay.
- migrate from slapd.conf to cn=config over ldap3 protocol.

**Comment by frankwillmore** [comment]
> There might be another option if you are using munge on the compute nodes (Slurm generally requires this). I don't remember the specifics, but I thought you can tweak your nsswitch.conf to use Munge for local credential look ups instead of relying on LDAP. I maybe mis-remembering here, so let me know if I'm off base please.

@gmkurtzer, do you remember the setting for this? On cori, I see entries for 
```
passwd:     slurm compat sss
group:     slurm compat sss
``` 
Is slurm a proxy for munge in this instance? On theta, it's 
```
passwd:    files sss
group:     files sss
```

**Comment by gmkurtzer** [comment]
@frankwillmore, nope, it's been ages since I've done it. I'd have to go back to the docs and start over from scratch. Sorry, I'm not of more help.

**Comment by dtrudg** [comment]
Just wanted to check if you were able to mitigate this in the end, using Munge or similar?

**Comment by frankwillmore** [comment]
We're running a no-op container in stages to invoke the needed caching in sssd.
