### ISSUE TITLE
impossible to not pass the environment

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#477]
As pointed in https://github.com/singularityware/singularity/issues/476#issuecomment-276697117, it seems that ATM there is no option to execute in the container without passing entire environment inside.  As such it forbids reproducible execution since outside environment might differ across hosts or even withing the same host (e.g. interfering with `modules`, `virtualenv` and whatnot) thus affecting inside-the-container execution.  I will refrain from suggesting any solution on "how" since you might know a better strategy  ;-)

**Comment by chrisgorgo** [comment]
This might be a duplicate of https://github.com/singularityware/singularity/issues/445

**Comment by yarikoptic** [comment]
it definitely is -- thank you @chrisfilo
