### ISSUE TITLE
singularity static builds

### ISSUE THREAD

**Issue by katakombi** [apptainer/singularity#4775]
Hi,
 this is a feature request: Would it be feasible to offer singularity releases as static builds?
This would allow to use all no-setuid functionality right away.

thx Stefan

**Comment by cclerget** [comment]
Hi @katakombi , no there is two limitations preventing us from doing that :

1. we recently introduced plugin so we rely on `dlopen` from the C library which make it impossible for us to compile Singularity as static binary
2. we need to use NSS to get user information as Singularity mostly run in environment based on NSS with centralized user database (eg: LDAP), and by compiling Singularity as static we will lose NSS support preventing Singularity to run correctly in those environments

**Comment by katakombi** [comment]
Thanks for the prompt reply, @cclerget ! 
So in a case where I do not use plugins and no NSS I should be able to build a static binary myself. 

This is what I've been using:
```
./mconfig -S --without-suid --prefix=$HOME/singularity
```

To what extent you think this would be portable across Linux systems (major Distros)?
And what is the exact difference between '-S' and '-s' ?

**Comment by cclerget** [comment]
@katakombi `mconfig` has been initially created for C projects, as Singularity use Go the `-S` and `-s` options are just noop with `mconfig`, it won't generate static binary at all. You will need to dig into `mlocal/frags` to inject options required for that.

We couldn't help you in this quest as it's not intended to be supported by us, you will have to figure that out by yourself if that's really what you want/need. Regarding the portability it mostly depends of the kernel API.

I'm closing the issue and labeling it as `wontfix`
