### ISSUE TITLE
Singularity macOS beta stalls when running run or shell

### ISSUE THREAD

**Issue by nick-youngblut** [apptainer/singularity#4795]
I just installed Singularity Desktop MacOS v0.1, and when I try running `singularity run <SIF-file, or docker-path>` or `singularity shell <SIF-file>`, the command just freezes, and I can't cancel it. It also seems to mess with my VPN (Cisco AnyConnect Secure Mobility Client). 

OS version: 10.14.6

**Comment by jmstover** [comment]
Can you show me the output of `singularity version` ?

Also, the output of:
```
singularity -d run [image]
```

For example:
```
singularity -d run docker://godlovedc/lolcow
```

**Edit:**
> It also seems to mess with my VPN (Cisco AnyConnect Secure Mobility Client).

That's _possible_ ... We're just using xhyve which is hooking into Apples vmnet.Framework. So, it's feasible that if you're connected to a VPN when it creates the device for the hypervisor, that it messes with the routing table in a bad way. :/

**Comment by nick-youngblut** [comment]
Singularity version: 3.3.0-rc.1.658.g7427b73f1.dirty

I restarted my laptop, and that seems to have fixed the issue. `singularity run docker://godlovedc/lolcow`, `singularity run lolcow_latest.sif`, and `singularity shell lolcow_latest.sif` seem to all be working correctly now

**Comment by jmstover** [comment]
Sounds good. Let us know if you run into any more issues.
