### ISSUE TITLE
Underlay broken when bind target is non-relative symlink

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#4797]
### Version of Singularity:

3.5.0 and the current release-3.5 branch

### Expected behavior

singularity works with 'set overlay = no'

### Actual behavior

Running with a singularity image such as lolcow.simg results in no /usr/bin in the image, even with no bind mounts requested.

### Steps to reproduce this behavior

```
$ sudo singularity build /tmp/lolcow.simg docker://godlovedc/lolcow
# set 'enable overlay = no' in /etc/singularity/singularity.conf
# alternatively use singularity run -u option for unprivileged
$ singularity run /tmp/lolcow.simg
WARNING: underlay of /etc/localtime required more than 50 (97) bind mounts
/bin/sh: 1: fortune: not found
/bin/sh: 1: cowsay: not found
/bin/sh: 1: lolcat: not found
$ singularity exec /tmp/lolcow.simg ls -F /usr
WARNING: underlay of /etc/localtime required more than 50 (97) bind mounts
share/
```

### What OS/distro are you running

CentOS 7.7

### How did you install Singularity

from epel-testing and from source

**Comment by DrDaveD** [comment]
When run unprivileged, it converts to sandbox and still fails to have most things in /usr.  It works with an existing sandbox image and `singularity exec -u docker://centos bash`.  It seems to be something to do with the lolcow image.

**Comment by DrDaveD** [comment]
Oh it's probably the fact that the lolcow image has /etc/localtime as a symlink to a full path and the centos image has it as a relative path:
```
$ singularity exec /tmp/lolcow.simg ls -l /etc/localtime
lrwxrwxrwx. 1 root root 27 Sep 15  2017 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC
$ singularity exec docker://centos ls -l /etc/localtime
lrwxrwxrwx. 1 root root 25 Sep 27 12:13 /etc/localtime -> ../usr/share/zoneinfo/UTC
```

**Comment by DrDaveD** [comment]
It appears to be all Debian or Ubuntu-based images that are affected.

**Comment by cclerget** [comment]
@DrDaveD Can you confirm for #4800 ? Thanks !

**Comment by DrDaveD** [comment]
@cclerget Yes it does solve the problem in my testing.  Thanks!
