### ISSUE TITLE
Relocatable RPM (or instructions)

### ISSUE THREAD

**Issue by rpwagner** [apptainer/singularity#48]
Hey,

I'd like specify the prefix when building an RPM or have the RPM be relocatable. Even if this was just an "edit here" example that would be sufficient.

Thanks

**Comment by gmkurtzer** [comment]
I don't think I've ever done a relocatable RPM before, and I'm not sure that will work appropriately for Singularity as there are paths which are compiled into the application workflow. The paths can be overriden by standard configuration arguments, but I am pretty sure that changing the installed paths will break Singularity.

Thoughts?

**Comment by rpwagner** [comment]
It doesn't need to be a relocatable RPM in our case, I'd just like to be able to specify the install location that will be used. When compiling from source you've got the classic `./configure --prefix=` option builtin. If there was some way to get that argument into the RPM build process that would be fine, even if it meant editing the spec file. I tried a bit last night and failed so I thought I'd ask.

**Comment by gmkurtzer** [comment]
Ahhh, try adding the appropriate --define args to the rpmbuild command... For example:

`rpmbuild -ta --define="_prefix /opt/singularity" --define "_sysconfdir /opt/singularity/etc" singularity-2.0.tar.gz`

**Comment by rpwagner** [comment]
Almost perfect! The `%doc` files still end up in `/usr/share/singularity-*`. I tried adding `--define="_docdir /opt/singularity/share"` but no luck.

**Comment by gmkurtzer** [comment]
Ahh, try this:

`--define "_defaultdocdir /opt/singularity/share"`

**Comment by rpwagner** [comment]
Boom! Done! Lovely. Thanks for the help and for including a spec file to begin with.

**Comment by gmkurtzer** [comment]
Wahoo! I will make the appropriate documentation changes on the webpage. Thanks!
