### ISSUE TITLE
Problem with ubuntu deboostrap and ubuntu keyring

### ISSUE THREAD

**Issue by sysmso** [apptainer/singularity#480]
Hi
I try to create a container with singularity 2.2 and ubuntu xenial, but deboostrap fails :

```
[ssysmso@laptop singularity]$ cat tensor.def 

DistType "debian"
MirrorURL "http://us.archive.ubuntu.com/ubuntu/"
OSVersion "xenial"
  
Setup
Bootstrap

InstallPkgs python wget
RunCmd /bin/sh <<EOF
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
ln -s /usr/local/bin/pip /usr/bin/pip
pip install pymultinest
EOF

Cleanup
[ssysmso@laptop singularity]$ sudo singularity create --size 2048 tensor.img
Creating a new image with a maximum size of 2048MiB...
Executing image create helper
Formatting image with ext3 file system
Done.
[ssysmso@laptop singularity]$ sudo singularity bootstrap tensor.img tensor.def 
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
[...]
Processing triggers for ca-certificates (20160104ubuntu1) ...
/var/lib/dpkg/info/ca-certificates.postinst: 154: /var/lib/dpkg/info/ca-certificates.postinst: update-ca-certificates: not found
dpkg: error processing package ca-certificates (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 ca-certificates
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Thanks for your help

**Comment by vsoch** [comment]
Hey @sysmso! This looks like a pretty old bootstrap spec.... where did you find it? Give this one a go: https://github.com/singularityware/singularity/blob/master/examples/ubuntu.def

**Comment by sysmso** [comment]
Ok, i was using old def, i didn't notice the spec have changed. Sorry for this, it's working with the example you gave me.

**Comment by vsoch** [comment]
Great! I'll close the issue - please reopen if something else comes up.

**Comment by sysmso** [comment]
Sorry for re-opening but you have a link on your tutorial page which lead to that syntax : http://singularity.lbl.gov/building-ubuntu-rhel-host

My mistake come from here.

**Comment by vsoch** [comment]
At the top it says the recipe is intended for version 2.1.2, but you are right that it's an old post! I will chat with @gmkurtzer about if we should remove these, or better, just post a link to a page for a newer one.
