### ISSUE TITLE
Sourcing container .bashrc

### ISSUE THREAD

**Issue by maarcyk** [apptainer/singularity#4808]
### Version of Singularity: 

What version of Singularity are you using? Run:

```
$ singularity version
v3.4.2-1
```

### Expected behavior

When I go into a container:     
sudo singularity shell -w centos7.6/

I want to have local .bashrc to be automatically loaded

### Actual behavior

When I go into the container, the .bashrc is not loaded

### Steps to reproduce this behavior

Instead, I have to load it separately:    
```
Singularity centos7.6:~> pwd
/root
Singularity centos7.6:~> source .bashrc 
root@marek-xps:~# 
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic



```

### How did you install Singularity

singularity build --sandbox centos7.6 docker://centos:7

**Comment by cclerget** [comment]
Hi @maarcyk , by default if the container has `/bin/sh -> bash`, Singularity shell prevent bash from loading `.bashrc` with `--norc`, if you want to load it you need to execute singularity shell with `-s` :

```
singularity shell -s /bin/bash docker://centos:7
```

**Comment by maarcyk** [comment]
Thanks, it works!

**Comment by cclerget** [comment]
Great !

**Comment by ikitayama** [comment]
I did pass the -s option with `/bin/bash` but the PATH env variable is still different from the host one.

**Comment by ikitayama** [comment]
Ooops I take it back. It does.
