### ISSUE TITLE
Command name of $$ during the evaluation of %environment 

### ISSUE THREAD

**Issue by alalazo** [apptainer/singularity#4809]
### Version of Singularity:
```
$ singularity version
3.5.0-rc.2
```

### Expected behavior

When a singularity container starts it sources a few files:

- `/.singularity.d/env/90-environment.sh`
- `/.singularity.d/env/91-environment.sh`

to setup the environment. I expect to see no visible changes in the output of `ps`  when executed as part of the setup procedure above or immediately after the shell is given to the user i.e. after a command like:
```console
$ singularity shell <image.sif>
```
for any process that exists in both contexts.

### Actual behavior

The actual behavior is that the process `$$` during the environment sourcing seems to change its name between the setup and the moment the shell is given to user. 

### Steps to reproduce this behavior

The behavior can be reproduced using the following definition file:
```
Bootstrap: library
From: ubuntu:18.04
%environment
    ps -p $$
```
Building an image from that and running it:
```console
$ sudo singularity build ubuntu.sif ubuntu.def
INFO:    Starting build...
INFO:    Adding environment to container
INFO:    Creating SIF file...
INFO:    Build complete: ubuntu.sif

$ singularity shell ubuntu.sif
PID TTY          TIME CMD
23041 pts/1    00:00:00 shell
Singularity> ps   
  PID TTY          TIME CMD
 6102 pts/1    00:00:00 bash
23027 pts/1    00:00:00 starter-suid
23041 pts/1    00:00:00 bash
23067 pts/1    00:00:00 ps
```
we see that process 23041 changed name in between the two `ps` execution. In particular, the name when sourcing environment files refers always to the Singularity subcommand used to start the image i.e. it would have been `exec` is we gave `singularity exec ubuntu.sif ...` as a command.

For a bit of context, this behavior has been reported in the community Slack and was causing issues when sourcing Spack's `setup-env.sh` script in the `%environment` section of the definition file since Spack tries to identify the current shell using the following command:
```
ps -p $$ | tail -n 1 | awk '{print $4}' | sed 's/^-//' | xargs basename
```
if other more specific methods already failed.

Also, I tagged this as a bug but I'm not really sure it is one rather than just a lack of a couple of lines of documentation.

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

Manually from release tarballs

**Comment by cclerget** [comment]
Hey @alalazo , I consider this as a spack bug rather. Spack rely on `/proc/$$/comm` which can be faked easily, why not calling `basename $(readlink /proc/$$/exe)` instead which should point to the current shell in use ? And have a switch for the supported shell like :

```
exe=$(readlink /proc/$$/exe)
sh=$(basename $exe)
case ${sh} in 
  bash) echo $sh ;;
  zsh) echo $sh ;;
  csh) echo $sh;;
  tcsh) echo $sh;;
  ksh) echo $sh;;
  *) echo "sh" ;;
esac
```

I don't see anything wrong to use "sh" if there is no matching shell and the spack script would cover all possible shell that `modulecmd` support.

**Comment by alalazo** [comment]
@cclerget Fair enough, as I said:

> Also, I tagged this as a bug but I'm not really sure it is one

Just wanted to report the behavior. Feel free to close the issue if you think there's nothing to be fixed here. Also, thanks for the suggestion.

**Comment by cclerget** [comment]
@alalazo Yes I will close it because the spack script really need fix, in this example :

```
cat > /tmp/test.sh <<EOF
#!/bin/sh
ps -p $$ | tail -n 1 | awk '{print $4}' | sed 's/^-//' | xargs basename
EOF
chmod +x /tmp/test.sh
```

Output unexpected result if the script is run directly like Singularity does :
```
/tmp/test.sh
test.sh
```

And the expected result if run through shell :
```
bash /tmp/test.sh
bash
```

As it's common to execute script directly, spack script need to handle this case.

**Comment by alalazo** [comment]
> As it's common to execute script directly, spack script need to handle this case.

That snippet doesn't come from a script with a shebang, it's an init file that is meant to be sourced. In any case, if we can harden it we should do it.
