### ISSUE TITLE
Caching of extracted layers for docker images

### ISSUE THREAD

**Issue by pforai** [apptainer/singularity#482]
Hey guys,

We're setting $SINGULARITY_CACHEDIR to some shared file system to cache downloads of docker:// resources.  What works fine is that the downloads are cached, but the extractions still happen. Now doing this a couple hundred times is generating quite some load on the shared file system. Is there a way to cache the downloads and the extractions?

We're currently not creating Singularity images from docker images yet. I guess that this would solve the problem as well.

thanks!
P

**Comment by vsoch** [comment]
This makes a lot of sense, and another user expressed a similar desire (to cache the entire image for docker). This comes down to the "whole image" vs "layers" approach - as long as we are needing to dump layers into images, and given that we are likely using the same layers across different images (eg, ubuntu:14.04 layers are likely common across a lot of images) this would explain the rationatle for caching --> extraction every time. On the other hand, if the users are using the same images, it would be nice to not extract every time!

@gmkurtzer is this something that is coming for the next release? In the meantime, what you can do for a workaround is have your users generate their entire images before use, either using Singularity Hub or transferring via FTP. The singularity hub cache IS for the entire image, and if you do something like:

    singularity run image.img input 1...

where image.img was created from docker:// using import or a bootstrap, you won't have to extract layers again. Likely your users are doing:

    singularity run docker://...
    singularity exec docker://...

so the cache layers are extracted to tmp each time.

**Comment by pforai** [comment]
@vsoch Thanks for the clarification that is exactly what my users are doing. Is the Singularity Hub already available for use? I would of course tell them to use Singularity Hub in addition to Docker Hub so that they're not extracting all day long. 

best,
p

**Comment by vsoch** [comment]
Yes! Singularity-hub.org

**Comment by gmkurtzer** [comment]
This is PR fixed at this time?

Note: You can import, as a user, from Docker Hub directly into a singularity container with the "development" branch (pre-2.3 release).

**Comment by vsoch** [comment]
If they use Singularity Hub or Docker Hub and pull layers/images that way, and set a shared cache, the redundancy should be resolved. What we don't have is an implementation for a shared/common cache intended for local image sans a registry (akin to a module system). Is this something there would be use/interest in developing? It would come done to a quasi "local" registry that is a shared cache folder, and images would need to be hashed by a content hash (not a unique generated ID at bootstrap which would always be different).

**Comment by gmkurtzer** [comment]
I agree that we should have a better mechanism for a global shared or private cache. Perhaps we should make that a new RFE issue?

From what I can see in the image-handler.sh, `$SINGULARITY_CACHEDIR` is being handled properly for both Docker and SHub URIs. Additionally, the downloads are being cached by the Python backend, so I believe this issue can be closed.

@pforai, can you confirm please?

Thanks!

**Comment by pforai** [comment]
Go ahead and close, running 2.3.1 and all is well.
