### ISSUE TITLE
Build doesn't process %appinstall in correct order in 3.x

### ISSUE THREAD

**Issue by codeaster** [apptainer/singularity#4820]
### Version of Singularity:

```
$ singularity --version
2.6.0-HEAD.579c415
```
and
```
$ singularity --version
singularity version 3.2.1
```

### Expected behavior

Consider this definition file with 2 apps:
```
Bootstrap: docker
From: ubuntu:18.04

%appinstall hdf5
echo "installing hdf5..."
echo "hdf5 installed" > done.hdf5

%appinstall med
echo "installing med..."
cp /scif/apps/hdf5/done.hdf5 done.med
```

I expect that ordering is respected: build hdf5 and then, if there is no error, med.

### Actual behavior

Using `singularity 2.6` the order is always respected.
Not with `singularity 3.2` (I also tried by manually compiling 3.4.2: same problem).

### Steps to reproduce this behavior

- Step 1 : build the definition above: OK for both 2.6 & 3.2

- Step 2 : add an error in hdf5 build. For example, redirect to `zzz/done.hdf5`. The error is raised: OK for both.

- Step 3: revert to the original recipe: OK in 2.6 (builds hdf5 and then med). NOOK (or KO) in 3.2, it builds med first, does not re-build hdf5 ?!

The archive [issue_singularity2.6vs3.2.tar.gz](https://github.com/sylabs/singularity/files/3917035/issue_singularity2.6vs3.2.tar.gz) contains log files (with `--debug`) for each step and each version.

### OS/distro used

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Singularity installation

I manually compiled Singularity 2.6 last year.
Singularity 3.2 has been recently packaged by our IT.
Same problem with 3.4.2 manually built today.

Thanks in advance to read this issue.
MC

**Comment by dtrudg** [comment]
Hello. I'm afraid that fixes are only considered against the latest open-source release of Singularity. Given that this is a complex problem, and there have been build system changes since 3.2, please could you provide the debug output against Singularity 3.5.0 (or the 3.5.1-rc.2 release candidate). 

Thanks.

**Comment by codeaster** [comment]
Thanks for reading this issue!

I did more tests with several versions.
Sometimes it passed with few builds, now I run up to 15 times while there is no error.

Here the results:
```
$ ./check.sh 
usage: check.sh VERSION
  Build a simple image. 'app2' depends on build of 'app1'.

  Use /home/G79848/tools/singularity-VERSION/bin/singularity

  Execute up to 15 builds: OK, ERROR, ...
      OK means that the image should be built.
      ERROR means that the image should NOT be built because 'app1' build fails.

$ for vers in 2.6.0 3.4.2 3.5.0-rc.2 3.5.0 3.5.1-rc.2; do ./check.sh $vers; done
checking version 2.6.0 ............... -> 15 builds
checking version 3.4.2 E.E -> 3 builds
checking version 3.5.0-rc.2 ..E -> 3 builds
checking version 3.5.0 ......E -> 7 builds
checking version 3.5.1-rc.2 E.E -> 3 builds
```

[check.txt](https://github.com/sylabs/singularity/files/3922480/check.txt)
(renamed for attachment policy)

Thanks

MC

**Comment by dtrudg** [comment]
Confirmed - apps need to be in an ordered data type to be processed in sequence, but are in a Map: https://github.com/sylabs/singularity/blob/e4d837e586fffa2ac00d714740facbb5ce91355b/internal/pkg/build/apps/apps.go#L115

**Comment by dtrudg** [comment]
Having looked at this some more... in the SCIF specification document, the information for the recipe parser states that:

>A parser of a recipe should be able to read chunks of text and return a data structure that includes a dictionary of app settings, each indexed by the app name, and the next level having sections, each a list of the commands from the file.

We are doing this - parsing recipes into a Go map type, which does not preserve order from population->iteration. A Python dictionary would not guarantee this either.

@vsoch - are you able to clarify, provide any input on this? If a singularity definition file lists many `%appinstall xxxx` sections, is there a guarantee within the SCIF spec that they should be processed in order.

The nature of independent apps in a container would suggest that maybe we shouldn't rely on order, and being able to use output of one `%appinstall` in the next `%appinstall` - but in practice that is what @codeaster was relying on, as it was the implementation behavior in Singularity 2.x

**Comment by vsoch** [comment]
Yeah! You are correct that I don't specify that in the description, but for the Python implementation we do take order into account with an OrderedDict, [imported here](https://github.com/vsoch/scif/blob/master/scif/main/parser.py#L20) and [used here](https://github.com/vsoch/scif/blob/master/scif/main/parser.py#L78) as we add sections, their content is also added as ordered dictionaries. And although it's not relevant for every container, it should be the case that the user has some confidence that the order of installs will go accordingly to the order specified in the file.

**Comment by vsoch** [comment]
I'll add that detail to the specification - it's one of those "in my head" things that wasn't written down.

**Comment by dtrudg** [comment]
Having looked at this it's not a simple fix of preserving order in the SCIF app handling code only - non-ordered maps are used further up.

I'll ask @ikaneshiro if he is able to look at this when he has some time. Because it will involve changes to the build code and careful regression testing this is almost certainly not going to make it to 3.5.2

**Comment by vsoch** [comment]
No worries @dctrud, some future version is good too :)

**Comment by dtrudg** [comment]
@codeaster @vsoch - there is a proposed fix for this in PR #5190 - if you are able to try it out that'd be great, but I have verified it on the exact example given here.

**Comment by vsoch** [comment]
I tested, but you force pushed towards the end so I can't even be sure what was changed. https://github.com/sylabs/singularity/pull/5190#issuecomment-610610980 I'm happy to review but please next time ping me to do so when you are no longer actively working on it. Thank you!

**Comment by dtrudg** [comment]
Per the PR - sorry for the push... I was done, but then I noted that I hadn't added 1 line to run the end-to-end test that was created and tested locally manually - that is all. Nothing else has changed.

Thanks for taking the time to look at this.

**Comment by vsoch** [comment]
okay perfecto! My review should still be good then :) @codeaster can you take the final look to make sure it's fixed as you'd expect?

**Comment by codeaster** [comment]
It seems me that it now works exactly as I expected!
Thanks @dctrud & @vsoch
