### ISSUE TITLE
Please update vendored "containers/image"

### ISSUE THREAD

**Issue by onlyjob** [apptainer/singularity#4824]
It would be nice to upgrade `containers/image` to v4 or v5. Thanks.

**Comment by dtrudg** [comment]
Hello - this will be considered for master and a future 3.6. Unless there are security issues we probably won't bump major versions of libraries like this within the 3.5.x series.

**Comment by dtrudg** [comment]
Going to try to tackle this now, given there is a major bump of deps today.

**Comment by dtrudg** [comment]
@onlyjob - done... we are tracking the latest now from `master` . Cheers.
