### ISSUE TITLE
Nicer error / build warnings for failing fakeroot builds without seccomp

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4828]
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.5.0
```

### Expected behavior

If singularity is built without libseccomp available then `./mconfig` warns e.g. yum bootstraps with fakeroot won't work.

If a yum fakeroot bootstrap is attempted on singularity without seccomp support then an error is given that makes sense to the user.

### Actual behavior

mconfig output is subtle - there is no explicit warning that no seccomp = things not working.

A yum bootstrap on singularity without seccomp support gives a generic "operation not permitted error"

See #4826

**Comment by cclerget** [comment]
@dctrud I will take this one. Thanks for the reminder !
