### ISSUE TITLE
how to upgrade "singularity version 3.0.3-1" to "version 3.5" or other new versions?

### ISSUE THREAD

**Issue by zzygyx9119** [apptainer/singularity#4834]
Dear All,

I installed  singularity version "3.0.3-1"  (singularity-3.0-ubuntu-bionic64 ) on my MacBook Pro (macOS catalina) using brew installation (first installed Virtuebox and Vagrant). The command I used is: "export VM=sylabs/singularity-3.0-ubuntu-bionic64". Now, how can I upgrade it to version 3.5 or other newer versions? Thank you!

Best,

Jeff

**Comment by dtrudg** [comment]
Hello. The vagrant box is a virtual machine with a standard Ubuntu Linux installation, that has had a specific version of Singularity pre-installed. To update you can either:

- Start from scratch, selecting a new vagrant box from: https://app.vagrantup.com/sylabs and following the instructions there e.g. 
```
vagrant init sylabs/singularity-3.4-ubuntu-bionic64
vagrant up
```

- Follow the instructions in the `INSTALL.md` file inside the Singularity repository to obtain and install the latest version in your existing VM.

*Note* - I am preparing the 3.5.1 Vagrant box as I write this. It will be available at https://app.vagrantup.com/sylabs  shortly.

**Comment by dtrudg** [comment]
3.5 boxes are now posted at: https://app.vagrantup.com/sylabs

**Comment by zzygyx9119** [comment]
Hi David,

Thank you!

Jeff
