### ISSUE TITLE
vagrant virtualbox issues

### ISSUE THREAD

**Issue by satra** [apptainer/singularity#484]
i'm running into issues where my vagrant virtualbox machine will not let me do consecutive operations on a singularity image. between each operation i need to do `exit; vagrant halt; vagrant up; vagrant ssh`

previously i thought this was a lustre issue, but i'm now using `/dev/shm` mounted using tmpfs, so i can't directly connect this pattern to lustre.

host platform details:
CentOS 7.2 3.10.0-229.el7.x86_64

```
$ vagrant version
Installed Version: 1.8.1
Latest Version: 1.9.1
```

```
$ vboxmanage --version
5.0.26r108824
```

operation details:

all operations are taking place in `/dev/shm/satra` (a la on tmpfs)
and inside vagrant `/vagrant` is a synced folder so i can create a large enough image while using a small vagrant box.

on vagrant host
```
vagrant up
vagrant ssh -c "/bin/sh /vagrant/install_singularity.sh"
vagrant ssh
```

inside vagrant box
```bash
$ cd /vagrant
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ls
install_singularity.sh  Singularity  Vagrantfile
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo singularity create -s 2048 tflow_om.img
Creating a new image with a maximum size of 2048MiB...
Executing image create helper
Formatting image with ext3 file system
Done.
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo singularity bootstrap tflow_om.img Singularity  
ERROR  : Failed to mount image in (read/write): Invalid argument
ABORT  : Retval = 255
```

if i do `exit; vagrant halt; vagrant up; vagrant ssh` and redo the above command succeeds. but immediately after success i cannot do:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo singularity shell -w tflow_om.img 
ERROR  : Container does not have a valid /bin/sh
ABORT  : Retval = 255
```

i need to again repeat `exit; vagrant halt; vagrant up; vagrant ssh`

**Comment by vsoch** [comment]
Could `/dev` be the issue? It's a pretty controlled place when it comes to working with singularity [example 1](https://github.com/singularityware/singularity/blob/56e9aaccd2052195f76aa9a86566baba3a16f1a9/libexec/bootstrap/modules-v1/debian.sh#L60) and extracting docker layers [example 2](https://github.com/singularityware/singularity/blob/ecfe4c83a0343d4141f0a316dad29f997cd14e56/libexec/python/utils.py#L365). If it's failing to mount the image, it might be related to mount stuffs.

Oh! Could you do the above error and add `--debug` so we can see verbose output? I think that would be very helpful!

**Comment by truatpasteurdotfr** [comment]
are you sure that you have enough space in /vagrant inside your VM? You mentionned 
"sync" as in "vagrant rsync" or as a shared space between your host and VM?

**Comment by satra** [comment]
@truatpasteurdotfr - yes - since i can actually create the box inside it without this error as long as the path is not a synced folder.

**Comment by satra** [comment]
@vsoch - `/dev` is unlikely to be the issue - the example points to `$SINGULARITY_ROOTFS/dev/*` not `/dev/*` .  i will check a few more things later today and post back here together with debug info.

**Comment by dtrudg** [comment]
Hi, am closing this issue as am unable to replicate on a new vagrant VM install of Singularity. Please let us know if it's still an issue.
