### ISSUE TITLE
Installing into $HOME/.local and other $HOME/.xyz (e.g. .cargo, etc.)

### ISSUE THREAD

**Issue by radoye** [apptainer/singularity#4842]
This is a question/request for instructions.

### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.0
```

### Expected behavior

I want to install rust using [rustup](https://rustup.rs/). Typically it puts Cargo into `$HOME/.cargo`. 
During the installation one is supposed to source some shell scripts and run software installed in `$HOME/.xyz`. 

I'm not sure what's the recommendation/best practice when putting such things into the container.

### Actual behavior

Typically calling into `$HOME/???` fails during build. 

### Steps to reproduce this behavior

```
%post
  [...]
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  source $HOME/.cargo/env
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

### How did you install Singularity

I installed from a release.

**Comment by cclerget** [comment]
Hi @radoye , you can set `RUSTUP_HOME` and `CARGO_HOME` to modify the install destination, so to create the container with rust you could have this definition file :

```
bootstrap: docker
from: ubuntu

%environment
   export RUSTUP_HOME=/opt/rust
   export CARGO_HOME=/opt/rust
   . /opt/rust/env

%post
   apt-get update
   apt-get install -y curl
   mkdir /opt/rust
   export RUSTUP_HOME=/opt/rust
   export CARGO_HOME=/opt/rust
   curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
   . /opt/rust/env
```

Note: the environment section allow to source `/opt/rust/env` and set `RUSTUP_HOME`/`CARGO_HOME` each time you will use the container image with `shell/exec/run` commands.

**Comment by radoye** [comment]
@cclerget Thanks for the quick update. To confirm, one **should not** install things into `$HOME` when building Singularity containers?

**Comment by cclerget** [comment]
@radoye Yes it's generally not recommended to install software in $HOME with containers and especially with Singularity image where the runtime mount the host user home directory on top of the one in the image.

**Comment by cclerget** [comment]
Closing the issue. Feel free to ask for re-open it if necessary. Thanks !
