### ISSUE TITLE
idea: file-based image repository/registry?

### ISSUE THREAD

**Issue by biocyberman** [apptainer/singularity#4849]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.0

```

Note: This request is related to this one over here: https://github.com/sylabs/singularity/issues/4844

Firstly, my apology if this idea or the similar has been discussed before. I anticipate that this idea may take some effort to implement, but the benefits are great.

I've tried setting up `sregistry` in an attempt to simplify and improve user-experience for a multi-user experience. It is, however, not a straight forward process to set up such a registry and auto-build process with the help of `drone`. Have you ever tried that? Therefore, I am proposing following simple solution with multi-user HPC environment use case in mind: file-based central registry. 

## Workflow
1. Write definition file: User writes a `.def` file, and run `singularity build --fakeroot ...`  to build an image 
2. Parse definition file: Singularity parses the `.def` file, encode each action into a signature, form a set of actions for the whole `.def` file, while ignore none essential parts (i.e. comments, `%label`, etc.). Base images versions and packages versions may be taken into account. In addition to the set of actions, an [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) may be generated and saved with the image for later use (e.g. comparing images). The whole `.def` file can also be optionally saved in the image file for inspections and comparing images. 
3. Query registry database: Singularity `check` and `add` if missing the image signature against a `singularity` owned file at located at the location defined in `singularity.conf` (e.g. `<IMAGES_ROOTDIR>/regristry.db`). The `check` step should suggests identical or highly similar images based on the signatures and full `.def` file. If `check` returns empty, then set `add_new` flag for use in the next step. An entry in `regirstry.db` file can be something like: `<image_file_name> <image_signature> <build_date> <build_user> <image_permission> <team_name>`

4. User decides to use the existing images if it exists, or build a new one if `add_new` flag is set.  
5. Build image:  If `add_new` flag is set, singularity `build` an images from `.def` if necessary. Singularity then `add` the signature to `registry.db` and image to `<IMAGES_ROOTDIR>` if `build` succeeds.  
6. Overtime, users should be able to query for existing images by search keywords in metadata saved in the image files (e.g. definition file, keywords, base images, include package names, etc). Best case scenario: users can use the images right away, without downloading or building them. Worst case scenario: users have to build an image like they are doing now.
7. Use images: User can either user the images directly, for example: `singularity run localreg://[builduser/]tensorflow:2-py3` or use them in another definition file. 
 
## Possible pitfalls
1. Users build and push sensitive data. Solution: Well, this may happens to all solutions, including the existing `sregistry`. Users should be educated about this.
2. Singularity miscalculates image matches. Solution: Step 2 and 3 above should be implemented in a robust way. [container-diff ](https://github.com/GoogleContainerTools/container-diff) may be a good starting point. 
3. Users misjudge the similarity of images and use them incorrectly. Answer: This applies to singularity and docker images in the existing registry solutions as well.
4. The database file and image files are broken. Solution: Users can only interact with the registry via `singularity`.  General good practices should also be used.

## Benefits:
1. Zero setup for admins and end users
2. High performance thanks to locally stored images.
3. Secure (minimal network traffic)
4. Reproducible: Metadata stored in the image can be extraced to inspect and recreate the image.
5. Save disk spaces, and build time - singularity build takes quite long time comparing to Docker build. 
6. Sharing images among team members is easy

**Comment by dtrudg** [comment]
Hi @biocyberman,

This is a nice idea, but it's probably a bit out of scope for the core run time as it would add a great deal of complexity. It's the type of thing that would likely be addressed via a separate project, perhaps using a plugin to Singularity, or with a PR to singularity to provide a `localreg` endpoint that can call the API/CLI of that project.

I'm afraid it's also not something that the Sylabs core team is likely to work on, as we have a commercial on-premise Singularity Enterprise product that includes a container library which is focused on these types of use cases.

sregistry and the other singularityhub related components are maintained independently by a separate organization, but with some support in the main singularity runtime. This may be the appropriate kind of approach for the type of solution you are suggesting.

**Comment by biocyberman** [comment]
Thank you for your reply @dctrud 
> This is a nice idea, but it's probably a bit out of scope for the core run time as it would add a great deal of complexity.It's the type of thing that would likely be addressed via a separate project, perhaps using a plugin to Singularity, or with a PR to singularity to provide a `localreg` endpoint that can call the API/CLI of that project.

I anticipated the complexity of this major feature. A plugin would be appropriate design. In addition, there would be a clever hack with `shub://local/[team]/<user>/<imagename>:<tag>`

> 
> I'm afraid it's also not something that the Sylabs core team is likely to work on, as we have a commercial on-premise Singularity Enterprise product that includes a container library which is focused on these types of use cases.
> 

I will try and recommend buying the plugin or existing solutions which offer this feature. However, from what I read about SingularityPRO, the self-hosted registry maybe there, but not the local file-based registry.

> sregistry and the other singularityhub related components are maintained independently by a separate organization, but with some support in the main singularity runtime. This may be the appropriate kind of approach for the type of solution you are suggesting.

The loosely coupling of `singularity` and `sregistry` has a drawbacks. The core+plugins model works better. My time budget currently does not allow me to work on implementing this feature. Nonetheless, it will make things easier if the core team update SIF file format to handle metadata and image comparison as described.

**Comment by dtrudg** [comment]
I'm going to close this issue as it's agreed above that this wouldn't be a core feature of Singularity in the foreseeable future. If you do have time to work on this, and you want to pursue...

> it will make things easier if the core team update SIF file format to handle metadata and image comparison as described.

... then issues describing the anticipated need in detail (exactly what type of metadata / examples / format ideas), or PRs would be a welcome way to proceed.

Thanks!
