### ISSUE TITLE
bootstrap: should cut comments first in From

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#485]
Currently, if the user bootstraps an image an has a comment after the name:

      Bootstrap: docker
      From: tensorflow/tensorflow:awesome-version  # like omgtacos

The bootstrap looks for a newline for the tag, and parses the comment as the image version. This gets passed incorrectly to the python and as a result, the "latest" version is incorrectly used.

The workaround for now is to not have comments on the same line as the `From`

      Bootstrap: docker
      # like omgtacos
      From: tensorflow/tensorflow:awesome-version

but it should be reasonable for the user to have comments on the same line - and they should be parsed / snipped off before extracting the tag, to be passed on. This will currently affect both docker and singularity hub, passing of tags. Thanks @satra for finding this bug!

**Comment by gmkurtzer** [comment]
This should be fixed in "development" branch. Please reopen if you find it is not. Thanks!
