### ISSUE TITLE
problem making singularity 3.1.0

### ISSUE THREAD

**Issue by Phylloxera** [apptainer/singularity#4858]
### Version of Singularity:
3.1.0
### Expected behavior
Normal Make
### Actual behavior
make: Entering directory '/home/aaron/singularity/builddir'
 GO singularity
    [+] GO_TAGS "containers_image_openpgp apparmor selinux seccomp"
../cmd/singularity/cli.go:9:2: cannot find package "github.com/sylabs/singularity/cmd/internal/cli" in any of:
        /usr/local/go/src/github.com/sylabs/singularity/cmd/internal/cli (from $GOROOT)
        /home/aaron/go/src/github.com/sylabs/singularity/cmd/internal/cli (from $GOPATH)
../cmd/singularity/cli.go:10:2: cannot find package "github.com/sylabs/singularity/internal/pkg/buildcfg" in any of:
        /usr/local/go/src/github.com/sylabs/singularity/internal/pkg/buildcfg (from $GOROOT)
        /home/aaron/go/src/github.com/sylabs/singularity/internal/pkg/buildcfg (from $GOPATH)
../cmd/singularity/cli.go:11:2: cannot find package "github.com/sylabs/singularity/internal/pkg/sylog" in any of:
        /usr/local/go/src/github.com/sylabs/singularity/internal/pkg/sylog (from $GOROOT)
        /home/aaron/go/src/github.com/sylabs/singularity/internal/pkg/sylog (from $GOPATH)
../cmd/singularity/cli.go:12:2: cannot find package "github.com/sylabs/singularity/internal/pkg/util/goversion" in any of:
        /usr/local/go/src/github.com/sylabs/singularity/internal/pkg/util/goversion (from $GOROOT)
        /home/aaron/go/src/github.com/sylabs/singularity/internal/pkg/util/goversion (from $GOPATH)
../cmd/singularity/cli.go:13:2: cannot find package "github.com/sylabs/singularity/pkg/util/user-agent" in any of:
        /usr/local/go/src/github.com/sylabs/singularity/pkg/util/user-agent (from $GOROOT)
        /home/aaron/go/src/github.com/sylabs/singularity/pkg/util/user-agent (from $GOPATH)
Makefile:149: recipe for target 'singularity' failed
make: *** [singularity] Error 1
make: Leaving directory '/home/aaron/singularity/builddir'
### Steps to reproduce this behavior
May not be reproducible...
### What OS/distro are you running
Ubuntu 18.0.4 (a hyper-v guest inside a windows host)
### How did you install Singularity
```
sudo apt update
sudo apt-get install -y \
    build-essential \
    libssl-dev \
    uuid-dev \
    libgpgme11-dev \
    squashfs-tools \
    libseccomp-dev \
    wget \
    pkg-config \
    git \
    cryptsetup
wget https://dl.google.com/go/go1.12.2.linux-amd64.tar.gz
sudo tar -C /usr/local -xzvf go1.12.2.linux-amd64.tar.gz
rm go1.12.2.linux-amd64.tar.gz
echo 'export PATH=/usr/local/go/bin:$PATH' >> ~/.bashrc
source ~/.bashrc
wget https://github.com/sylabs/singularity/releases/download/v3.1.0/singularity-3.1.0.tar.gz
tar -xzf singularity-3.1.0.tar.gz
cd singularity
./mconfig && make -C builddir && sudo make -C builddir install
```
ALSO TRIED WITH GO 12 & 13.5. ALSO TRIED WITH `sudo apt upgrade` PRIOR TO MAKE
GO FOLDER REMOVED AND ~/.bashrc FILE CLEARED BETWEEN GO INSTALLS.

**Comment by dtrudg** [comment]
Singularity 3.1 is an older version that must be extracted into the `GOPATH` to install correctly. This is a requirement for Go prior to the introduction of Go modules.

Please follow the INSTALL instructions for the 3.1 branch:

https://github.com/sylabs/singularity/blob/vault/release-3.1/INSTALL.md
