### ISSUE TITLE
Does singularity allow pulling from multiple repos?

### ISSUE THREAD

**Issue by skatragadda-nygc** [apptainer/singularity#4859]
### Version of Singularity:

What version of Singularity are you using? 

3.5.0/3.4.2

How to handle auth for multiple registries using singularity? 
eg registries: gcr.io, gcr.io(private), docker hub, docker hub private 

For now I can only think of above. I would think we might have more. I am doing the environment variable export which works with private gcr but then it won't let me import from docker hub/gcr public registries. 

 ```
singularity pull docker://ubuntu
FATAL:   While making image from oci registry: failed to get checksum for docker://ubuntu: unable to retrieve auth token: invalid username/password
```

**Comment by dtrudg** [comment]
The environment variable is a 'hard' request to authorize to a docker/oci registry, so things will then fail against other repositories.

The library we use to communicate with registries (`containers/image`) supports reading docker's config file for per-registry authentication. We should add some documentation about this, but you can see an example in the documentation for the Skopeo tool that uses the same library:

https://github.com/containers/skopeo#private-registries-with-authentication

**Comment by skatragadda-nygc** [comment]
Hi @dctrud 

Any documentation on how we can make public/private images work seamlessly without environment variables? 

We are using singularity in our cromwell config. We require to pull from both public and private repositories.
