### ISSUE TITLE
3.5.0 never uses .docker/config.json for authentication

### ISSUE THREAD

**Issue by skatragadda-nygc** [apptainer/singularity#4860]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.0
```

### Expected behavior

What did you expect to see when you do...?
gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
cat keyfile.json | docker login -u _json_key --password-stdin https://gcr.io

singularity should be able to pull images from gcr.io

### Actual behavior

What actually happend? Why was it incorrect?

singularity pull docker://gcr.io/private/image failed to pull image

DEBUG   [U=uid,P=pid]   parseURI()                    Parsing docker://gcr.io/private/image into reference
FATAL   [U=uid,P=pid]   pullRun()                     While making image from oci registry: failed to get checksum for docker://gcr.io/private/image: Error reading manifest v2 in gcr.io/private/image: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
You can do a gcr auth as shown above and try singularity pull

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

rpm I guess

btw above steps work with 3.4.2

**Comment by dtrudg** [comment]
I believe this may have been introduced in this change in 3.5.0:

https://github.com/sylabs/singularity/commit/90aa485dc68e433dd69dc409333cfe80554038b2#diff-2e67ecac6fc39e145477633d1ce1fe8dR311

In `containers/image`,  `docker.json` is used if the incoming `dockerAuthConfig` pointer is nil ... but here we will be giving a non-nil pointer to a `dockerAuthConfig` with default empty members.

https://github.com/containers/image/blob/21244c96ad792ef415068dc1bc1ab82dffb68dc3/pkg/docker/config/config.go#L79
