### ISSUE TITLE
--fakeroot and --overlay doesn't seem to work together

### ISSUE THREAD

**Issue by akesandgren** [apptainer/singularity#4867]
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.4.2

```

### Expected behavior

Create an ext3 overlay, run without fakeroot
```
singularity shell  --overlay overlay.ext3 sif-image
mount | head -n 1
overlay on / type overlay (rw,nodev,relatime,lowerdir=/var/lib/singularity/mnt/session/overlay-lowerdir:/var/lib/singularity/mnt/session/rootfs,upperdir=/var/lib/singularity/mnt/session/overlay-images/0/upper,workdir=/var/lib/singularity/mnt/session/overlay-images/0/work)
```

/-fs writeable

### Actual behavior

What actually happend? Why was it incorrect?
```
singularity shell --fakeroot --overlay overlay.ext3 sif-image
mount | head -n 1
tmpfs on / type tmpfs (ro,relatime,size=16384k,uid=yyyy,gid=xxxx)
```

/-fs not writable

This makes apt-get install fail since it (for some reason) tries to do, for instance, rmdir /bin.dpkg-tmp.

### What OS/distro are you running

```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by cclerget** [comment]
Hi @akesandgren , yes `--fakeroot` (more generally user namespace) can't use overlay mount on almost all distributions (except Ubuntu afaik). For now I suggest to use only sandbox images with `--fakeroot` then you could use `--writable` to make `apt-get` work with.

**Comment by akesandgren** [comment]
Ok, this is Ubuntu Bionic though, (with a Ubuntu Xenial container) so it should work?

And from the overlay section in the docco:
"For security reasons, you must be root to use a bare directory as an overlay. ext3 file system images can be used as overlays without root privileges."

So I can't really do what I want...

**Comment by cclerget** [comment]
@akesandgren Sorry what I mean is that Singularity doesn't handle this even on Ubuntu to be consistent across distributions. There is another limitation, fakeroot can't actually mount single file image via loop devices so loading an ext3 overlay image is not possible.

**Comment by cclerget** [comment]
For information @akesandgren , in next coming release 3.6 (around May) you could use sandbox directory overlay via plugin :

```
singularity plugin compile -o /tmp/plugin.sif examples/plugins/ubuntu-userns-overlay-plugin
sudo singularity plugin install /tmp/plugin.sif
mkdir /tmp/overlay
singularity shell -f -o /tmp/overlay docker://ubuntu
```

Note: it allows only sandbox directory as overlay with user namespace workflow, ext3/squashfs images are still not supported with user namespaces.

I'm closing the issue, feel to re-open it for further discussions
