### ISSUE TITLE
Pull/Build docker -> error handling tar header: (null)

### ISSUE THREAD

**Issue by Firedrops** [apptainer/singularity#4868]
### Expected behavior

Successful pull/build

### Actual behavior

```
...
Exploding layer: sha256:db58467d7309a4b16197aa8c681f3368f2e4d4cde6b2257b67ac57195c2b13c7.tar.gz
Exploding layer: sha256:312aac6b1b5edf16bfd6aef1bda2de3f155ffdc468920043e3c6b17899165927.tar.gz
WARNING: Warning handling tar header: (null)
ERROR  : Error handling tar header: (null)
ABORT  : Retval = 255
Cleaning up...
```

### Steps to reproduce this behavior

same error from both methods:
```singularity pull docker://dockersubtest/qimr_mtb:slim```
```singularity build qimr_slim docker://dockersubtest/qimr_mtb:slim```

the dockerfile itself: https://github.com/Firedrops/qimr_mtb/blob/master/Slim/Dockerfile

### What OS/distro are you running

Ubuntu 18.04 in VirtualBox, Windows 10 host.

### How did you install Singularity

```
git clone https://github.com/singularityware/singularity.git
cd singularity
./autogen.sh
./configure --prefix=/usr/local --sysconfdir=/etc
make
sudo make install
```

A similar problem was encountered before by the [mindboggle team](https://github.com/sylabs/singularity/issues/1967), which seems to have been an issue in their Dockerfile, but I'm not sure how to troubleshoot mine.

**Comment by cclerget** [comment]
Hi @Firedrops , I would suggest to give a try with a more recent version of Singularity : https://github.com/sylabs/singularity/releases/tag/v3.5.1. We don't support 2.X OSS versions anymore.

**Comment by dtrudg** [comment]
Can confirm this image is handled okay on `3.5.2`

`singularity pull docker://dockersubtest/qimr_mtb:slim`

Note that it's very very large. You may also want to check that you aren't running out of space during the download somewhere, leading to corrupt tar files that cause the extraction error.
