### ISSUE TITLE
Building Singularity Desktop for macOS

### ISSUE THREAD

**Issue by chrisburr** [apptainer/singularity#4872]
I'm currently updating [conda-forge's singularity package](https://github.com/conda-forge/singularity-feedstock) and thought I could add macOS support at the same time.

I managed to get it working provided I copied `libexec/singularity/vm/{initramfs_amd64.gz,syos-kernel-amd64,xhyve}` from a pre-exisiting installation of the v0.1 beta. (I also needed https://github.com/chrisburr/singularity/commit/5a9859b0b20ba846086b0aaf3f2d02044489cff0 to hackily fix compatibility with the singularity client inside the image from v0.1.)

At this stage I have a few questions:

1. Is it possible to obtain the SyOS VM image from anywhere other than the official Singularity Desktop release?
2. Is the source for the provided `xhyve` binary available anywhere or is it a private fork? I didn't find mention of it on https://sylabs.io/desktop-oss-software and the [`machyve/xhyve`](https://github.com/machyve/xhyve) repository used by homebrew is missing support for `virtio-9p`.
3. Most importantly, is it possible to legally distribute the macOS version of singularity? The [EULA](https://repo.sylabs.io/desktop/Singularity_Desktop_SYOS_EULA.pdf) suggests it might not be?

**Comment by dtrudg** [comment]
Hi Chris,

Generally, packaging Desktop for a package manager like conda would be a challenge, as I'm not sure they support including binaries that need privilege (such as xhyve does to start a VM)?

> 1. Is it possible to obtain the SyOS VM image from anywhere other than the official Singularity Desktop release?

At present, no. I'm afraid the SyOS image is not available other than in the release. Also please note when re-purposing those files that the release is currently a beta version, that doesn't get quite the same stability / security attention as the main Singularity 

> 2. Is the source for the provided `xhyve` binary available anywhere or is it a private fork? I didn't find mention of it on https://sylabs.io/desktop-oss-software and the [`machyve/xhyve`](https://github.com/machyve/xhyve) repository used by homebrew is missing support for `virtio-9p`.

I will check on this, to see if with have something missing / overlooked on that page.

> 3. Most importantly, is it possible to legally distribute the macOS version of singularity? The [EULA](https://repo.sylabs.io/desktop/Singularity_Desktop_SYOS_EULA.pdf) suggests it might not be?

I'm going to leave this for hopefully someone else to comment... or I'll get clarification and respond if that doesn't happen :-)

**Comment by chrisburr** [comment]
Thanks for the quick response @dctrud!

> Generally, packaging Desktop for a package manager like conda would be a challenge, as I'm not sure they support including binaries that need privilege (such as xhyve does to start a VM)?

According to the README `xhyve` runs entirely in userspace. I've tested this locally but it's not a clean setup so it's possible I'm accidentally leaking more privileges that I intend to.

**Comment by dtrudg** [comment]
@chrisburr - I believe that networking needs setuid on `xhyve` - avoiding this through OSX entitlements is problematic for things not being notarized & shipped through the app store: https://forums.developer.apple.com/thread/116870

**Comment by chrisburr** [comment]
Ah yes, I see now that further down the README it mentions that.

It's unfortunate but being unsigned isn't necessarily a problem for me as my interest is in having singularity available as a dependency of other conda-forge packages that wouldn't depend on any of the networking features.

If needed it would also be possible to just repackage the official macOS binaries into a conda package provided the licence permits it.

**Comment by jmstover** [comment]
@chrisburr 

The xhyve repo is a clone of a different one, not machyve/xhyve ... See:  https://github.com/sylabs/xhyve

It's using git submodules...

> Most importantly, is it possible to legally distribute the macOS version of singularity? The EULA suggests it might not be?

Sort of ... You can distribute the Sigularity code/xhyve all you want. It's the binary initramfs where we don't have that under a permissive license. The software we're using for the initramfs can be found at:
  https://sylabs.io/desktop-oss-software

But that's not saying how it's built and put together or what's being ran when we cut over to it.

**Comment by jmstover** [comment]
@chrisburr 
> hackily fix compatibility with the singularity client 

Right... that's actually needed. It creates a field like:  `[hostname]:[user]:[uid]:[gid]`

This gets passed along. Once we start up the initramfs we grab that value and set the hostname, etc... That _should_ work in:
https://repo.sylabs.io/desktop/singularity-desktop-beta-v0.1.dmg

If it doesn't then something didn't get updated along the chain somewhere... :/

-J
