### ISSUE TITLE
ext3 persistent overlay uid/gid limited to 65535

### ISSUE THREAD

**Issue by nathanweeks** [apptainer/singularity#4878]
When using an ext3 file system image overlay, the uid/gid of the "/" directory appears to be taken from the lower-order 16 bits of the uid/gid of the user that created the overlay upperdir, potentially causing a "permission denied" error for newly-created files/directories that otherwise would be writable in the overlay if the UID of the user is > 65535. 

This behavior is reproducible on our CentOS 7.6.1810 cluster, as well as in a CentOS 8 Docker container (and several other OS containers that I've tried):  

### Version of Singularity:

In the CentOS 8 Docker container as demonstrated below:
```
# singularity version
3.4.1-1.2.el8
```

On our CentOS 7.7 cluster:
```
$ singularity version
3.5.2-1.el7
```

### Expected behavior

```
$ id 
uid=2147483647(testuser) gid=2147483647(testgroup) groups=2147483647(testgroup)
$ mkdir -p overlay/upper
$ truncate -s 1G overlay.img
$ mkfs.ext3 -d overlay overlay.img
$ singularity pull docker://centos:8
$ singularity exec --overlay overlay2.img centos_8.sif ls -l /foo
$ singularity exec --overlay overlay.img ls -ld /
drwxr-xr-x 1 testuser testgroup 4096 Dec 18 18:46 /
$ singularity exec --overlay overlay.img centos_8.sif touch /foo
$ singularity exec --overlay overlay.img centos_8.sif ls -l /foo
-rw-r--r-- 1 testuser testgroup 0 Dec 18 18:50 /foo
```

### Actual behavior

```
...
$ singularity exec --overlay overlay.img ls -ld /
drwxr-xr-x 1 65535 65535 4096 Dec 18 18:46 /
$ singularity exec --overlay overlay.img centos_8.sif touch /foo
touch: cannot touch '/foo': Permission denied
```

However, if the upperdir is given o+rwx permission to allow any user to create new files, then newly-created files do have the correct UID/GID:

```
$ mkdir -p -m 777 overlay2/upper
$ ls -ld overlay2/upper
drwxrwxrwx 2 testuser testgroup 4096 Dec 18 18:49 overlay2/upper
$ truncate -s 1G overlay2.img
$ mkfs.ext3 -d overlay2 overlay2.img
$ singularity exec --overlay overlay2.img centos_8.sif ls -ld /
drwxrwxrwx 1 65535 65535 4096 Dec 18 18:49 /
$ singularity exec --overlay overlay2.img centos_8.sif touch /foo
$ singularity exec --overlay overlay2.img centos_8.sif ls -l /foo
-rw-r--r-- 1 testuser testgroup 0 Dec 18 18:50 /foo
```

### Steps to reproduce this behavior

An environment in which to execute the above commands can be reproduced in a CentOS 8 Docker container using (currently) singularity 3.4.1 from the EPEL repo:

```
$ docker run --privileged -it --rm centos:8
# yum install e2fsprogs
# yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
# yum install singularity
# groupadd -g $((0x7FFFFFFF)) testgroup
# useradd -u $((0x7FFFFFFF)) -g testgroup testuser
# su - testuser
$
...
```

### What OS/distro are you running

In the above container:

```
# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by cclerget** [comment]
@nathanweeks Looks like `uid16` is set during mkfs (probably set as a default mount option in `/etc/mke2fs.conf`), you can check by running `tune2fs -l overlay.img |grep uid16` and disable it with `tune2fs -o ^uid16 overlay.img`

**Comment by dtrudg** [comment]
To demonstrate that this is from `mkfs` and not `singularity` we can mount loopback to the host directly...

```
root@piran:/tmp# sudo mount -t ext3 -o loop overlay2.img /mnt
root@piran:/tmp# ls -lah /mnt
total 28K
drwxr-xr-x  4 root  root  4.0K Dec 18 13:59 .
drwxr-xr-x 22 root  root  4.0K Dec  8 18:33 ..
drwx------  2 root  root   16K Dec 18 13:59 lost+found
drwxrwxrwx  2 65535 65535 4.0K Dec 18 13:59 upper
```

**Comment by nathanweeks** [comment]
@dctrud & @cclerget : thank you for the explanation! Unfortunately, `tune2fs -o ^uid16 overlay.img` does not appear to resolve the issue. `tune2fs -l` does not provide any hints pertaining to uid16, nor does /etc/mkfs.ext3 have anything to say:

```
$ docker run -it --rm --privileged centos:8
# yum install e2fsprogs
...
# groupadd -g $((0x7FFFFFFF)) testgroup
# useradd -u $((0x7FFFFFFF)) -g testgroup testuser
# su - testuser
$ id 
uid=2147483647(testuser) gid=2147483647(testgroup) groups=2147483647(testgroup)
$ truncate -s 1G overlay.img
$ mkdir -p overlay/upper
$ mkfs.ext3 -d overlay overlay.img
mke2fs 1.44.3 (10-July-2018)
...
$ grep -i uid /etc/mke2fs.conf 
$ tune2fs -l overlay.img | grep uid
Reserved blocks uid:      0 (user root)
$ tune2fs -o ^uid16 overlay.img
tune2fs 1.44.3 (10-July-2018)
$ singularity exec --overlay overlay.img centos_8.sif ls -ld /
drwxr-xr-x 1 65535 65535 4096 Dec 18 20:44 /
$ logout
# mount -t ext3 -o loop /home/testuser/overlay.img /mnt
[root@3632e40ed9be /]# ls -l /mnt
total 20
drwx------ 2 root  root  16384 Dec 18 20:44 lost+found
drwxr-xr-x 2 65535 65535  4096 Dec 18 20:44 upper
# umount /mnt
```

**Comment by dtrudg** [comment]
I don't see an obvious workaround other than creating an empty ext3 format file, loopback mounting it, and creating entries then.

Everything works after the filesystem is created. It seems just that mke2fs can't create entries with uid/gid >65535 via the `-d` option.

```
dave@piran/mnt> mount | grep overlay
/tmp/overlay2.img on /mnt type ext3 (rw,relatime)
dave@piran/mnt> ls -lah /mnt
total 28K
drwxr-xr-x  4 root  root  4.0K Dec 18 13:59 ./
drwxr-xr-x 22 root  root  4.0K Dec 18 15:37 ../
drwx------  2 root  root   16K Dec 18 13:59 lost+found/
drwxrwxrwx  2 65535 65535 4.0K Dec 18 13:59 upper/
dave@piran/mnt> sudo chown testuser.testgroup /mnt/upper
dave@piran/mnt> ls -lah /mnt
total 28K
drwxr-xr-x  4 root     root      4.0K Dec 18 13:59 ./
drwxr-xr-x 22 root     root      4.0K Dec 18 15:37 ../
drwx------  2 root     root       16K Dec 18 13:59 lost+found/
drwxrwxrwx  2 testuser testgroup 4.0K Dec 18 13:59 upper/
```

**Comment by nathanweeks** [comment]
An unprivileged user on an HPC cluster will probably lack sufficient privileges to implement that workaround. I submitted an issue to the e2fsprogs GitHub issue tracker; in the meantime, it seems that creating the upperdir with wide open permissions (`mkdir -m 777`) may be the only "portable" solution?

I think it would be worth documenting an approach for creating unprivileged-user-writable persistent overlay file system images in the [Singularity User Guide](https://sylabs.io/guides/3.5/user-guide/persistent_overlays.html), as well as any limitations/caveats. In any HPC context, they're [especially useful](https://pawseysc.github.io/sc19-containers/04-writable-containers/index.html) for mitigating the performance impact on a parallel file system of single-node applications that create many small files.

**Comment by dtrudg** [comment]
I'm adding some detail to the docs here: https://github.com/sylabs/singularity-userdocs/pull/297/files

Feedback, or any further suggested changes via PR would be very welcome on the singularity-userdocs repository.
