### ISSUE TITLE
Singualrity Sandbox doesn't work in Red Hat 7.7 (Maipo) Error: FATAL:   exec /.singularity.d/actions/shell failed: stale NFS file handle

### ISSUE THREAD

**Issue by lxwgcool** [apptainer/singularity#4879]
### Version of Singularity:

What version of Singularity are you using? Run:

```
Singularity v3.1 and Singularity v3.5.1

xil14026admin@gpu10:~/Test/singularity$ singularity --version
singularity version 3.1.0
```

### Expected behavior
Enter into the shell of singularity contianer

### Actual behavior
Report error: FATAL:   exec /.singularity.d/actions/shell failed: stale NFS file handle

### Steps to reproduce this behavior
1: Create any singularity container by using sandbox 
2: Try to enter into the shell, for example:
xil14026admin@gpu10:~/Test/singularity/testing$ singularity shell ./empty3.1.ssd/
FATAL:   exec /.singularity.d/actions/shell failed: stale NFS file handle

### What OS/distro are you running

```
xil14026admin@gpu10:~/Test/singularity/testing$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.7 (Maipo)

```

### How did you install Singularity
Follow the instruction from singularity website, and installed it in our cluster as a module file

### Additional information
1: It works well in Red Hat Enterprise Linux Server release 6.7 (Santiago)
2: I only get this problem in Red Hat Enterprise Linux Server release 7.7 (Maipo)
3: The image container works well in both redhat 6.7 and redhat 7.7

**Comment by dtrudg** [comment]
@lxwgcool  - this will depend a bit on the exact setup of the NFS filesystem here. Are you using an auto mounter?

Debug output from `singularity -d ....` and `mount` on the host system would be useful to try and diagnose this.

Please also test with `3.5.2` if possible.

**Comment by lxwgcool** [comment]
Thanks so much for your reply @dctrud 
I just tried "singularity -d" and the error I get is as same as what I got before, please check the output below: 

DEBUG   [U=0,P=197446]     Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=1074482630,P=197424]create()                      Chdir into / to avoid errors
VERBOSE [U=1074482630,P=197445]startup()                     Execute stage 2
DEBUG   [U=1074482630,P=197445]Stage()                       Entering stage 2
**FATAL   [U=1074482630,P=197445]Stage()                       exec /.singularity.d/actions/shell failed: stale NFS file handle**
DEBUG   [U=1074482630,P=197424]CleanupContainer()            Cleanup container
DEBUG   [U=1074482630,P=197424]Master()                      Child exited with exit status 255

In addition, I forgot mention one thing: we are using singularity in our HPC cluster. We use GPFS in our cluster rather than NFS. 

I have spent several days to solve this stale NFS file handle issue, however, no luck. Thank so much for your help.

**Comment by dtrudg** [comment]
@lxwgcool - could you post the output of `mount` also please, from where you run Singularity?

Thanks!

**Comment by cclerget** [comment]
@lxwgcool Based on the error, Singularity is installed on NFS partition because `/.singularity.d/actions` is a bind mount done by Singularity during container setup, the source directory is located at :

`ls -la $(singularity buildcfg|grep SYSCONFDIR|cut -d "=" -f2)/singularity/actions`

which should point to NFS partition in your case. You could also check by executing it directly without singularity to see if you get the stale NFS file handle error :

`$(singularity buildcfg|grep SYSCONFDIR|cut -d "=" -f2)/singularity/actions/shell`

**Comment by extinctpotato** [comment]
I've seen this error message before. Running `echo N | sudo tee /sys/module/overlay/parameters/index` usually resolved the issue.

**Comment by lxwgcool** [comment]
@extinctpotato  I just back to office. Thank you so much for your suggestion. I tried it, however, no luck. The error still persists. Please check the screenshot below:
![Screenshot from 2020-01-02 12-45-33](https://user-images.githubusercontent.com/11053933/71682470-cf384000-2d5d-11ea-8f7d-f608296dfb86.png)

BTW, we run singularity in our HPC cluster, and the all the nodes are managed by IBM GPFS.
Please help
Thank you so much

**Comment by lxwgcool** [comment]
@extinctpotato Here is the updated index file: 
![Screenshot from 2020-01-02 12-48-52](https://user-images.githubusercontent.com/11053933/71682617-3fdf5c80-2d5e-11ea-8d5d-45b396970b62.png)

**Comment by extinctpotato** [comment]
So this is not what I thought. Unfortunately I can't be of further help; this appears to be a slightly different issue, unrelated to the overlay indexing.

Seeing the output of `mount` might come in handy.

**Comment by dtrudg** [comment]
> @lxwgcool - could you post the output of `mount` also please, from where you run Singularity?

We need to see what filesystems are in use here, and what mount options there are. Things differ significantly between RHEL6 and 7 so unfortunately knowing it works on RHEL6 doesn't give much to go on.

**Comment by lxwgcool** [comment]
@dctrud  Hi, Thank you so much for your reply. 
Here is the mount output of gpfs: 
![Screenshot from 2020-01-02 13-52-19](https://user-images.githubusercontent.com/11053933/71685753-3f978f00-2d67-11ea-9f24-58cba3971b1d.png)

Here is the full message of mount output
![Screenshot from 2020-01-02 13-52-44](https://user-images.githubusercontent.com/11053933/71685777-4f16d800-2d67-11ea-983e-318b0d5cbedd.png)

Thanks so much for your help

**Comment by dtrudg** [comment]
If `/apps2` is a symlink onto a GPFS filesystem please ensure you have installed singularity with `--localstatedir` pointing to a non-GPFS location:

https://sylabs.io/guides/3.2/admin-guide/admin_quickstart.html#setting-localstatedir

It is likely here that the GPFS filesystem doesn't properly support being used as the mount location for the overlay session directories. This may work on RHEL6 as overlay is not used there.

You may also wish to try `3.5.2` if you haven't already as there are some fixes there related to filesystems and paths containing symlinks.

Other than this, we would need debug output of Singularity (run `singularity -d shell ...`) to pin the issue down further.

**Comment by lxwgcool** [comment]
@dctrud Hi, Dave, Thank you so much for your reply. Yes, you are right, /apps2 is a symlink. In order to solve the issue of symlink, I manually copied singularity from "apps2" to local "/user" directory. Please check the screenshot below:
![Screenshot from 2020-01-02 15-34-20](https://user-images.githubusercontent.com/11053933/71691698-06b2e680-2d76-11ea-86bd-dbcb80b1cabf.png)
![Screenshot from 2020-01-02 15-34-53](https://user-images.githubusercontent.com/11053933/71691729-14686c00-2d76-11ea-83de-7854d4d62cc7.png)

I also compiled the singularity v3.5.2. However, I still get the same error, please check the screenshot below:
![Screenshot from 2020-01-02 15-42-40](https://user-images.githubusercontent.com/11053933/71691893-8771e280-2d76-11ea-99c1-b0f4e3208fcb.png)

I really appreciate if you can give me any comments on this issue.
Best
Xin

**Comment by dtrudg** [comment]
Hi @lxwgcool - Did you build `3.5.2` straight to `/usr` or copy it there from `/apps2`? Paths are compiled into singularity so I'm afraid it's not enough to copy it to `/usr` - it will still go and use some things on `/apps2` if it was built to and originally installed for `/apps2`

You will need to rebuild it and install with `--prefix` set to to `/usr/...` to test running singularity off of GPFS.

The next thing we need for debugging is the output of your `singularity shell ...` command, but with the debug `-d` option, so run `singularity -d ...`. This will be long, so you'll need to copy and paste, or upload a file somewhere rather than screenshot.

**Comment by lxwgcool** [comment]
@dctrud  Hi Dave, Thanks for your prompt reply. Yes, I copied singularity from /apps2 to /usr directly. Thanks for your mention. I just recompiled singularity from source code by using "--prefix=/usr/singularity/3.5.2". However, the issue still persists. Here is the output of all debug info, Please check the message below:

>>>>>>>>>>>>>>>>>>>>>>>
[root@gpu10 bin]# pwd
/usr/singularity/3.5.2/bin
[root@gpu10 bin]# ./singularity --version
singularity version 3.5.2
[root@gpu10 bin]# ./singularity -d shell /apps2/singularity/general/general_python3
DEBUG   [U=0,P=54465]      persistentPreRunE()           Singularity version: 3.5.2
DEBUG   [U=0,P=54465]      handleConfDir()               /root/.singularity already exists. Not creating.
DEBUG   [U=0,P=54465]      getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=0,P=54465]      updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library
DEBUG   [U=0,P=54465]      updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci-tmp
DEBUG   [U=0,P=54465]      updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci
DEBUG   [U=0,P=54465]      updateCacheSubdir()           Caching directory set to /root/.singularity/cache/net
DEBUG   [U=0,P=54465]      updateCacheSubdir()           Caching directory set to /root/.singularity/cache/shub
DEBUG   [U=0,P=54465]      updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oras
DEBUG   [U=0,P=54465]      execStarter()                 Checking for encrypted system partition
DEBUG   [U=0,P=54465]      Init()                        Image format detection
DEBUG   [U=0,P=54465]      Init()                        Check for sandbox image format
DEBUG   [U=0,P=54465]      Init()                        sandbox image format detected
VERBOSE [U=0,P=54465]      SetContainerEnv()             HOME=/root
DEBUG   [U=0,P=54465]      init()                        Use starter binary /usr/singularity/3.5.2/libexec/singularity/bin/starter
VERBOSE [U=0,P=54465]      print()                       Set messagelevel to: 5
VERBOSE [U=0,P=54465]      init()                        Starter initialization
DEBUG   [U=0,P=54465]      load_overlay_module()         Trying to load overlay kernel module
DEBUG   [U=0,P=54465]      load_overlay_module()         Overlay seems supported by the kernel
DEBUG   [U=0,P=54465]      get_pipe_exec_fd()            PIPE_EXEC_FD value: 7
VERBOSE [U=0,P=54465]      is_suid()                     Check if we are running as setuid
DEBUG   [U=0,P=54465]      init()                        Read engine configuration
DEBUG   [U=0,P=54465]      init()                        Wait completion of stage1
DEBUG   [U=0,P=54476]      set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=54476]      init()                        Spawn stage 1
DEBUG   [U=0,P=54476]      startup()                     singularity runtime engine selected
VERBOSE [U=0,P=54476]      startup()                     Execute stage 1
DEBUG   [U=0,P=54476]      StageOne()                    Entering stage 1
DEBUG   [U=0,P=54476]      prepareRootCaps()             Root full capabilities
DEBUG   [U=0,P=54476]      prepareAutofs()               Found "/proc/sys/fs/binfmt_misc" as autofs mount point
DEBUG   [U=0,P=54476]      prepareAutofs()               Found "/misc" as autofs mount point
DEBUG   [U=0,P=54476]      prepareAutofs()               Found "/net" as autofs mount point
DEBUG   [U=0,P=54476]      prepareAutofs()               Found "/home" as autofs mount point
DEBUG   [U=0,P=54476]      prepareAutofs()               Found "/shared" as autofs mount point
DEBUG   [U=0,P=54476]      prepareAutofs()               Could not keep file descriptor for bind path /etc/localtime: no mount point
DEBUG   [U=0,P=54476]      prepareAutofs()               Could not keep file descriptor for bind path /etc/hosts: no mount point
DEBUG   [U=0,P=54476]      prepareAutofs()               Could not keep file descriptor for home directory /root: no mount point
DEBUG   [U=0,P=54476]      prepareAutofs()               Could not keep file descriptor for current working directory /usr/singularity/3.5.2/bin: no mount point
DEBUG   [U=0,P=54476]      Init()                        Image format detection
DEBUG   [U=0,P=54476]      Init()                        Check for sandbox image format
DEBUG   [U=0,P=54476]      Init()                        sandbox image format detected
DEBUG   [U=0,P=54476]      setSessionLayer()             Overlay seems supported and allowed by kernel
DEBUG   [U=0,P=54476]      setSessionLayer()             Attempting to use overlayfs (enable overlay = try)
VERBOSE [U=0,P=54465]      wait_child()                  stage 1 exited with status 0
DEBUG   [U=0,P=54465]      init()                        Applying stage 1 working directory
DEBUG   [U=0,P=54465]      cleanup_fd()                  Close file descriptor 4
DEBUG   [U=0,P=54465]      init()                        Set child signal mask
DEBUG   [U=0,P=54465]      init()                        Create socketpair for master communication channel
DEBUG   [U=0,P=54465]      init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=0,P=54465]      priv_escalate()               Get root privileges
VERBOSE [U=0,P=54465]      priv_escalate()               Change filesystem uid to 0
VERBOSE [U=0,P=54465]      init()                        Spawn master process
DEBUG   [U=0,P=54483]      set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=54483]      create_namespace()            Create mount namespace
VERBOSE [U=0,P=54465]      enter_namespace()             Entering in mount namespace
DEBUG   [U=0,P=54465]      enter_namespace()             Opening namespace file ns/mnt
DEBUG   [U=0,P=54465]      setns()                       Using syscall() wrapped __NR_setns
VERBOSE [U=0,P=54483]      create_namespace()            Create mount namespace
DEBUG   [U=0,P=54484]      set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=54484]      init()                        Spawn RPC server
DEBUG   [U=0,P=54465]      startup()                     singularity runtime engine selected
VERBOSE [U=0,P=54465]      startup()                     Execute master process
DEBUG   [U=0,P=54484]      startup()                     singularity runtime engine selected
DEBUG   [U=0,P=54465]      setupSessionLayout()          Using Layer system: overlay
VERBOSE [U=0,P=54484]      startup()                     Serve RPC requests
DEBUG   [U=0,P=54465]      setupOverlayLayout()          Creating overlay SESSIONDIR layout
DEBUG   [U=0,P=54465]      addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=0,P=54465]      addRootfsMount()              Image type is 4098
DEBUG   [U=0,P=54465]      addRootfsMount()              Mounting directory rootfs: /apps2/singularity/general/general_python3
DEBUG   [U=0,P=54465]      addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=0,P=54465]      addKernelMount()              Adding proc to mount list
VERBOSE [U=0,P=54465]      addKernelMount()              Default mount: /proc:/proc
DEBUG   [U=0,P=54465]      addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=0,P=54465]      addKernelMount()              Adding sysfs to mount list
VERBOSE [U=0,P=54465]      addKernelMount()              Default mount: /sys:/sys
DEBUG   [U=0,P=54465]      addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=0,P=54465]      addDevMount()                 Adding dev to mount list
VERBOSE [U=0,P=54465]      addDevMount()                 Default mount: /dev:/dev
DEBUG   [U=0,P=54465]      addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=0,P=54465]      addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=0,P=54465]      addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=0,P=54465]      addHomeStagingDir()           Staging home directory (/root) at /usr/singularity/3.5.2/var/singularity/mnt/session/root
DEBUG   [U=0,P=54465]      addHomeMount()                Adding home directory mount [/usr/singularity/3.5.2/var/singularity/mnt/session/root:/root] to list using layer: overlay
DEBUG   [U=0,P=54465]      addTmpMount()                 Checking for 'mount tmp' in configuration file
VERBOSE [U=0,P=54465]      addTmpMount()                 Default mount: /tmp:/tmp
VERBOSE [U=0,P=54465]      addTmpMount()                 Default mount: /var/tmp:/var/tmp
DEBUG   [U=0,P=54465]      addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=0,P=54465]      addCwdMount()                 Using /usr/singularity/3.5.2/bin as current working directory
VERBOSE [U=0,P=54465]      addCwdMount()                 Default mount: /usr/singularity/3.5.2/bin: to the container
DEBUG   [U=0,P=54465]      addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=0,P=54465]      addFilesMount()               Checking for 'user bind control' in configuration file
DEBUG   [U=0,P=54465]      addResolvConfMount()          Adding /etc/resolv.conf to mount list
VERBOSE [U=0,P=54465]      addResolvConfMount()          Default mount: /etc/resolv.conf:/etc/resolv.conf
DEBUG   [U=0,P=54465]      addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=0,P=54465]      create()                      Mount all
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting tmpfs to /usr/singularity/3.5.2/var/singularity/mnt/session
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /apps2/singularity/general/general_python3 to /usr/singularity/3.5.2/var/singularity/mnt/session/rootfs
DEBUG   [U=0,P=54465]      mountGeneric()                Remounting /usr/singularity/3.5.2/var/singularity/mnt/session/rootfs
DEBUG   [U=0,P=54465]      mountGeneric()                Remounting /usr/singularity/3.5.2/var/singularity/mnt/session/rootfs
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting overlay to /usr/singularity/3.5.2/var/singularity/mnt/session/final
DEBUG   [U=0,P=54465]      setPropagationMount()         Set RPC mount propagation flag to SLAVE
VERBOSE [U=0,P=54465]      addIdentityMount()            Not updating passwd/group files, running as root!
DEBUG   [U=0,P=54465]      mountGeneric()                Remounting /usr/singularity/3.5.2/var/singularity/mnt/session/final
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /dev to /usr/singularity/3.5.2/var/singularity/mnt/session/final/dev
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /etc/localtime to /usr/singularity/3.5.2/var/singularity/mnt/session/final/usr/share/zoneinfo/Universal
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /etc/hosts to /usr/singularity/3.5.2/var/singularity/mnt/session/final/etc/hosts
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /usr/singularity/3.5.2/etc/singularity/actions to /usr/singularity/3.5.2/var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=0,P=54465]      mountGeneric()                Remounting /usr/singularity/3.5.2/var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /proc to /usr/singularity/3.5.2/var/singularity/mnt/session/final/proc
DEBUG   [U=0,P=54465]      mountGeneric()                Remounting /usr/singularity/3.5.2/var/singularity/mnt/session/final/proc
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting sysfs to /usr/singularity/3.5.2/var/singularity/mnt/session/final/sys
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /root to /usr/singularity/3.5.2/var/singularity/mnt/session/root
DEBUG   [U=0,P=54465]      mountGeneric()                Remounting /usr/singularity/3.5.2/var/singularity/mnt/session/root
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /usr/singularity/3.5.2/var/singularity/mnt/session/root to /usr/singularity/3.5.2/var/singularity/mnt/session/final/root
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /tmp to /usr/singularity/3.5.2/var/singularity/mnt/session/final/tmp
DEBUG   [U=0,P=54465]      mountGeneric()                Remounting /usr/singularity/3.5.2/var/singularity/mnt/session/final/tmp
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /var/tmp to /usr/singularity/3.5.2/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=0,P=54465]      mountGeneric()                Remounting /usr/singularity/3.5.2/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /usr/singularity/3.5.2/bin to /usr/singularity/3.5.2/var/singularity/mnt/session/final/usr/singularity/3.5.2/bin
DEBUG   [U=0,P=54465]      mountGeneric()                Remounting /usr/singularity/3.5.2/var/singularity/mnt/session/final/usr/singularity/3.5.2/bin
DEBUG   [U=0,P=54465]      mountGeneric()                Mounting /usr/singularity/3.5.2/var/singularity/mnt/session/etc/resolv.conf to /usr/singularity/3.5.2/var/singularity/mnt/session/final/etc/resolv.conf
DEBUG   [U=0,P=54465]      create()                      Chroot into /usr/singularity/3.5.2/var/singularity/mnt/session/final
DEBUG   [U=0,P=54484]      Chroot()                      Hold reference to host / directory
DEBUG   [U=0,P=54484]      Chroot()                      Called pivot_root on /usr/singularity/3.5.2/var/singularity/mnt/session/final
DEBUG   [U=0,P=54484]      Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=54484]      Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=54484]      Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=54484]      Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=0,P=54465]      create()                      Chdir into / to avoid errors
VERBOSE [U=0,P=54483]      wait_child()                  rpc server exited with status 0
DEBUG   [U=0,P=54483]      apply_container_privileges()  Set user ID to 0
DEBUG   [U=0,P=54483]      set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=54483]      startup()                     singularity runtime engine selected
VERBOSE [U=0,P=54483]      startup()                     Execute stage 2
DEBUG   [U=0,P=54483]      StageTwo()                    Entering stage 2
FATAL   [U=0,P=54483]      StageTwo()                    failed to open /bin/sh for inspection: read /bin/sh: stale NFS file handle
DEBUG   [U=0,P=54465]      startContainer()              stage 2 process reported an error, waiting status
DEBUG   [U=0,P=54465]      Master()                      Child exited with exit status 255
[root@gpu10 bin]# 
<<<<<<<<<<<<<<<<<<<<<<

Thank you so much for your help
Best
Xin

**Comment by dtrudg** [comment]
Thanks for the debug and mount output. Hopefully @cclerget can take a look and think about this tomorrow.

**Comment by lxwgcool** [comment]
@dctrud  No problem Dave. Please take your time. Thanks so much for all your efforts. 
Best
Xin

**Comment by cclerget** [comment]
@lxwgcool In order to identify if the issue come from overlay, first try by forcing a run without overlay with :

```
/usr/singularity/3.5.2/bin/singularity shell -w /apps2/singularity/general/general_python3
```

If it works, please paste output of `tail -n +1 /sys/module/overlay/parameters/*`

If it doesn't work, just try to read and/or execute a binary in `/apps2/singularity/general/general_python3/bin` outside of singularity by example

```
vi /apps2/singularity/general/general_python3/bin/ls
vi /apps2/singularity/general/general_python3/bin/bash
```

and ensure the issue doesn't come from GPFS by looking at GPFS logs, also `dmesg` may give some hints in this case.

**Comment by lxwgcool** [comment]
@dctrud @cclerget Hi Dave, Good news. It works! Thank you so much for your help. 
Here is the output of tail: 
![Screenshot from 2020-01-06 12-00-42](https://user-images.githubusercontent.com/11053933/71834099-6104bd80-307c-11ea-9491-37b0d65b3e34.png)

Please let me know if there is anything I can to debug it.

**Comment by cclerget** [comment]
@lxwgcool Please send `dmesg` output after triggering error by running

```
/usr/singularity/3.5.2/bin/singularity shell /apps2/singularity/general/general_python3
```

That could help to catch potential overlay/GPFS error and give some pointers

**Comment by lxwgcool** [comment]
@cclerget Hi, there is no error. I can enter into the shell of singularity container successfully after using the option "-w". Please check the attachment file for dmesg output.

[dmesg.log.01.06.2020.txt](https://github.com/sylabs/singularity/files/4027138/dmesg.log.01.06.2020.txt)

**Comment by cclerget** [comment]
@lxwgcool Sorry bad copy paste, I mean without `-w` and look if `dmesg` show an error related to overlay or GPFS just after running the command

**Comment by lxwgcool** [comment]
@cclerget Sorry for my misunderstanding. Here is the dmesg output without using ''-w". Please check the attachment. 
[dmesg.log.01.06.2020.no.w.txt](https://github.com/sylabs/singularity/files/4027200/dmesg.log.01.06.2020.no.w.txt)

**Comment by cclerget** [comment]
@lxwgcool As a workaround until we figured out what's wrong with GPFS/overlay, you can set `enable overlay = no` in `singularity.conf` to disable overlay without having to pass `-w`

**Comment by lxwgcool** [comment]
@cclerget @dctrud Hi, I made some additional testings about using singularity from the auto-mount folder / local folder. Please check the screenshot below:
![Screenshot from 2020-01-06 14-30-42](https://user-images.githubusercontent.com/11053933/71843105-235e5f80-3091-11ea-9f9d-29e2d85f23af.png)

Conclusion: 
1: v3.5.2 and v3.5.1 give me the error, "ERROR  : Failed to set effective UID to 0", when I try to use singularity from the gpfs auto-mounted folder.
2: v3.5.2 works fine if I use it from local
3: v3.1 works fine from the gpfs auto-mounted folder.

It seems that v3.1 could tolerate more unexpected cases.

**Comment by dtrudg** [comment]
@lxwgcool - where you installed `3.5.2` and `3.5.1` on GPFS, can you look at the files in the `libexec/singularity/bin` directory? Does your `starter-suid` have setuid (an `s` visible in the permissions)?

```
dave@piran:/opt/singularity-dev/libexec/singularity/bin
02:09 PM $ ls -lah
total 33M
drwxr-xr-x 2 root root 4.0K Jan  3 17:46 .
drwxr-xr-x 4 root root 4.0K Jan  3 17:46 ..
-rwxr-xr-x 1 root root  17M Jan  3 17:46 starter
-rwsr-xr-x 1 root root  16M Jan  3 17:46 starter-suid
```

Is it the same as for the `3.1` that works?

**Comment by lxwgcool** [comment]
@dctrud  Hi, I just made a bunch of testing. v3.5.1 and v3.1 come with the default special permission "s" for "starter-suid". However, v3.5.2 does not come with this special permissions. I just use "chmod u+s" added permission "s" into the file file "starter-suid". I also find another important thing: in order to avoid some unexpected errors, we need change the owner to root. 

Here is my previous setting for different versions of singularity:
![Screenshot from 2020-01-06 16-28-33](https://user-images.githubusercontent.com/11053933/71850142-9c65b300-30a1-11ea-8880-453484dbb207.png)

Here is the modified setting for different versions of singularity:
![Screenshot from 2020-01-06 16-29-18](https://user-images.githubusercontent.com/11053933/71850181-b30c0a00-30a1-11ea-8013-d41aa76c4c35.png)

After adding the special permission "s" and change the owner of the singularity installation folder manually, all of these versions, including v3.5.1, v3.5.2 and v3.1, work fine form the auto-mount folder.

Thank you so much for our suggestion.
Best
Xin

**Comment by dtrudg** [comment]
:+1: glad we found out the issue there.

When you install singularity, the expectation is that the `make install` will be run as a `sudo make install` so that the setuid root is in place on starter-suid. If you need to install without root, you must use the `--without-suid` option to `mconfig`.

We'll improve documentation around this shortly.
