### ISSUE TITLE
[Proposal] Include syslog support

### ISSUE THREAD

**Issue by alvarosimon** [apptainer/singularity#488]
This is just a proposal to include a logger mechanism to get log info from Singularity. We have included a workaround within `init`    script with something like this:

`/usr/bin/logger -t singularity "user=$USER image=$IMAGE_PATH jobid=${PBS_JOBID:-} cmd=$SINGULARITY_COMMAND"`

but it would be nice to implement this by default in Singularity, also with several verbosity levels.

**Comment by vsoch** [comment]
Like an official singularity log for the admin to set up? That seems like it should be reasonable to do, we already have levels of verbosity set up based on `SINGULARITY_MESSAGELEVEL` in the main and python code.  Is the idea that this is one level up from error/debug log, it just gets usage? What does the JOBID map onto?

**Comment by alvarosimon** [comment]
@vsoch yes something like that, the idea is to put those logs into our syslog system to be processed by logstash and elasticsearch to create nice charts in Kibana. Our logger command is just an example, in our case `PBS_JOBID`   variable is provided by our torque batch system when the singularity command is executed within a PBS job script.

**Comment by gmkurtzer** [comment]
Singularity does syslog() currently... Granted in librefactor, I believe I need to add some of those features back in, but in 2.2* it should be working. I'm happy to change how it is logging, or what it is logging though!

**Comment by boegel** [comment]
@gmkurtzer The main thing we are looking for is which `singularity` commands get run, using which image, by whom, where (hostname) & when. Being able to add additional info/env vars (like the site-specific `$PBS_JOBID`) would be nice too.

**Comment by alvarosimon** [comment]
@gmkurtzer ah ok, I have to take a look again because I can't see any message from singularity in our syslog (we were using 2.2 version). Maybe this requires an extra `singularity.conf`  section to setup the logs properly, maybe something like:

```
# Setup logs verbosity
# 0 = ERROR, 1 = WARNING, 2 = INFO, 3 = DEBUG
log verbosity = 3

# log system
#  defines the logging system:
#      file         to log in the singularity.log file
#      syslog    to use the syslog facilities
#      std          to use the default log stream (stderr)
log system = syslog
```

**Comment by martbhell** [comment]
In addition to @boegel's comments I would be interested to know also about containers and rundirs (which I can't extract now in the init script with ${SINGULARITY_CONTAINER:-} for some reason)

**Comment by gmkurtzer** [comment]
Hi @martbhell 

Can you elaborate on that?

Thanks!

**Comment by martbhell** [comment]
I'm assuming it's because the init script runs before those variables are set.

**Comment by vsoch** [comment]
Not sure if this is related, but we could easily add to our logger to write to some log file in the container, so at least we'd have a log for its generation. I'm thinking you are looking for a log for when it's running? I'll think about this too :) Although I'm sure @gmkurtzer already knows the answer!

**Comment by martbhell** [comment]
Yep. I'd like to track who runs what :)

**Comment by gmkurtzer** [comment]
@vsoch We can't write to the containers, as we don't mount them read-write unless specifically requested.

@martbhell Actually, the `${sysconfdir}/singularity/init` is run at the right time, but the name of the variable you want to use is `${SINGULARITY_IMAGE}`. However, I would agree that "CONTAINER" makes more sense, but it is presently called "IMAGE" because of legacy reasons.

BTW, I just added a `singularity_message(LOG, ....)` that describes the command running:

```
Apr  7 15:42:18 gmkdev2 Singularity: action (U=1000,P=12688)> USER=gmk, IMAGE='centos_docker', COMMAND='shell'
Apr  7 15:44:17 gmkdev2 Singularity: action (U=1000,P=14158)> USER=gmk, IMAGE='centos_docker', COMMAND='shell'
Apr  7 15:44:30 gmkdev2 Singularity: action-suid (U=1000,P=14217)> USER=gmk, IMAGE='centos_docker', COMMAND='shell'
```

And all errors are always syslogged:

```
Apr  7 15:41:13 gmkdev2 Singularity: action-suid (U=0,P=11941)> User info is not available
Apr  7 15:41:13 gmkdev2 Singularity: action-suid (U=0,P=11941)> Retval = 255
```

**Comment by martbhell** [comment]
@gmkurtzer nice!  Could you point me to the documentation for how to configure syslog logging? ( I'm currently on 2.2.99 )

**Comment by vsoch** [comment]
Can you just cat --> grep the syslog file? Eg:

```bash
vanessa@som-ctp:~$ cat /var/log/syslog | grep Singularity
Apr  7 22:37:57 som-ctp Singularity: action-suid (U=1002,P=22665)> Could not open image ubuntu: No such file or directory
Apr  7 22:37:57 som-ctp Singularity: action-suid (U=1002,P=22665)> Retval = 255
Apr  7 23:21:38 som-ctp Singularity: action-suid (U=1002,P=25686)> No valid /bin/sh in container
Apr  7 23:21:38 som-ctp Singularity: action-suid (U=1002,P=25686)> Retval = 255
Apr  7 23:21:54 som-ctp Singularity: action-suid (U=1002,P=25781)> USER=vanessa, IMAGE='ubuntu.img', COMMAND='run'
Apr  8 05:42:52 som-ctp Singularity: action-suid (U=1002,P=2377)> USER=vanessa, IMAGE='ubuntu:latest', COMMAND='run'
```

**Comment by gmkurtzer** [comment]
@martbhell as @vsoch mentioned, it should be working already. Note that on RHEL based distributions the default syslog location is `/var/log/messages`.

**Comment by martbhell** [comment]
Okay I'll check it out on Monday @gmkurtzer . I don't recall seeing it there though so I thought I had to configure something.

**Comment by gmkurtzer** [comment]
Singularity is logging to LOCAL0, so it might be possible that your syslog.conf isn't persisting those?

Have a good weekend!

**Comment by martbhell** [comment]
Sorry for delay here.

This is on a CentOS7 machine with this kind of rsyslog.conf:
<pre>
$ grep -v -e ^# -e ^$ /etc/rsyslog.conf |head
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
$WorkDirectory /var/lib/rsyslog
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
*.*                                                /var/log/local0.log

[snip]
</pre>

All the logs are written to local0.log, including if I run "logger -p local0.info -t test test"

If I run this: "singularity exec -B /scratch:/mnt docker://ubuntu:latest env"

then nothing is written to syslog (nor is it in the "journalctl -xef" output either).

**Comment by gmkurtzer** [comment]
Hi @martbhell, can you confirm which branch of GitHub you are testing? If it is master, can you retest with 'development'?

Thanks!

**Comment by martbhell** [comment]
@gmkurtzer I most likely used master. I'll try with devel

**Comment by dtrudg** [comment]
Closing this - on Singularity 2.4 series I am seeing syslog entries on a CentOS7 machine.

Please feel-free to reopen if you still have this issue. Thanks.
