### ISSUE TITLE
Lib-refactor: update Python/Docker integration

### ISSUE THREAD

**Issue by gmkurtzer** [apptainer/singularity#489]
@vsoch This is what I was thinking for the changes for the Python side...

In a nutshell, I am thinking of a change to take an option (perhaps something like `--layerfile`) which will change the current behavior such that it doesn't explode the tarball layers automatically, but instead writes them to a file. This will enable me to wrap that code and make it compatible with the unprivileged import code and potentially change how we are doing the layer decompression currently (both for docker and shub). One potential workflow could be:

* check if --layerfile=/path/to/file is defined, if so:
* obtain an exclusive flock() on layerfile
* do everything that happens now, but if --layerfile is defined, don't explode the tarballs
* Write all of the layers disk locations in order to the layerfile

I think it will be called from shell code as follows:

```
if /usr/libexec/singularity/python/cli.py --layerfile=$sessiondir/file ......; then
    for i in `cat $sessiondir/file`; do
        cat $i | /usr/libexec/singularity/bin/import container.img
    done
else
    echo FAILED
fi
```

**Comment by vsoch** [comment]
perfecto! I'm on it. I'm going to restructure some of the client code as well to make it a little tidier.

**Comment by gmkurtzer** [comment]
Fantastic, thank you!

Do you have any ideas to do something similar with shub? Or maybe we do this just for Docker layers?

**Comment by vsoch** [comment]
yes, we can write the singularity image path into the layerfile, and then you can handle it accordingly, which means something like `gzip -d -f /path/to/compressed/image`. 

Also, right now we are requiring passing the argument as --shub or --docker, and I think what would be cleaner is to specify --image and then provide the entire uri (eg, shub:// or docker://) and then I'll parse that. What do you think?

**Comment by gmkurtzer** [comment]
I love the idea of having the python code parse it and figure it out automatically. I don't like using the name `--image` just because that to me means an image file. How does `--container` or `--containeruri` sound instead?

**Comment by vsoch** [comment]
`--container` !

**Comment by vsoch** [comment]
Hey @gmkurtzer! 

I added some example "executable one liners" for docker and shub to (possibly) be closer to what you had in mind, re our discussion on slack. For example, the following scripts would replace using the client (`python/cli.py`). All variables are passed via environment exports, and run with an exec:

[docker/add.py](https://github.com/vsoch/singularity/blob/lib-refactor/libexec/python/docker/add.py)
[docker/import.py](https://github.com/vsoch/singularity/blob/lib-refactor/libexec/python/docker/import.py)

and then for example [run as follows](https://github.com/vsoch/singularity/blob/lib-refactor/libexec/bootstrap-scripts/driver-docker.sh#L95):

      eval $SINGULARITY_libexecdir/singularity/python/docker/import.py

That would be for import, and the equivalent (with add) that doesn't actually untar, but just writes to some `SINGULARITY_METADATA_FILE` would be called equivalently. For each, if you look in the header of the script, I write out the environment variables that are relevant.

For Singularity Hub, so far [we just have a pull](https://github.com/vsoch/singularity/blob/lib-refactor/libexec/python/shub/pull.py):

      eval $SINGULARITY_libexecdir/singularity/python/shub/pull.py

Is this (sort of) what you were getting at? It basically unwraps the argument parser into a simpler script that expects a particular set of environment variables. It is more in line with the way (I think) the C functions are set up. There is redundancy of code, and I'm sure all those "pythonic or death" folk out there will not approve, but it's very straight forward in terms of finding something and calling it.

If you like this gist, we can get rid of the cli.py and replace with these. And add whatever other "API-esque" calls you would want. Seriously, give me a list, and it's done.

Should probably get some sleep now, lol.

**Comment by vsoch** [comment]
oh and warning - not yet tested! I'll get your feedback, make fixes and write new tests, and then will give the go for looking over / review, etc.

**Comment by gmkurtzer** [comment]
This is done, thanks V! Closing.
