### ISSUE TITLE
Fatal error when building a remote singularity container

### ISSUE THREAD

**Issue by RaphaelBecquart** [apptainer/singularity#4893]
### Expected behavior

Build a container in the cloud from a recipe file: 
`singularity build --remote test.img ubuntu.def`

### Actual behavior

Here is the persistent error message I get when attempting to build:
`build (5dfcd6841ed3c209a02e1e05) cancelled due to unavailable arch (386)
FATAL:   While performing build: build image size <= 0
`
Note: I do have an access token.

### Steps to reproduce this behavior

To reproduce: use this recipe file:

`
bootstrap: docker
from: ubuntu:18.04

%post
	apt-get -y update
	apt-get -y install python3.6

%files

%runscript

	echo "hello world from ubuntu container!"  
`

### What OS/distro are you running
Ubuntu 16.04.6 LTS

**Comment by dtrudg** [comment]
Hello. This `cancelled due to unavailable arch (386)` suggests you are probably building from a machine running a 32-bit Linux. I'm afraid the remote build in the cloud only supports builds for 64-bit Linux (amd64)

**Comment by RaphaelBecquart** [comment]
Hello. My machine is actually running a 64-bit Linux

**Comment by dtrudg** [comment]
What's the output of `go env | grep GOARCH`?

If it says `amd64` you should be okay here. If it says `386` then you have the 32-bit version of Go installed on a 64-bit machine, and need to install the 64-bit version.

**Comment by RaphaelBecquart** [comment]
You were right! Thanks and I'll install the 64 bit version
