### ISSUE TITLE
Support multiple MirrorURL entries in the image definition file

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#49]
For a richer bootstrap please support multiple MirrorURL entries in the image def file.

**Comment by gmkurtzer** [comment]
Please test [master d077169] when you have a chance... MultipleURL's should now work. :)

Thank you for your patience!

**Comment by gmkurtzer** [comment]
I am closing this, but if for any reason it doesn't work please let me know and I will reopen.

Thanks!
