### ISSUE TITLE
Memory using build

### ISSUE THREAD

**Issue by Lcornet** [apptainer/singularity#4917]
### Version of Singularity: 3.0.3

What version of Singularity are you using? Run:

```
$ singularity version

```

### Expected behavior

What did you expect to see when you do...?
Take no disk space when build fail.
sudo singularity build --sandbox centos.img centos.def

### Actual behavior

What actually happend? Why was it incorrect?
Singularity take around 1 Gb space when it crash and I can't locate any files created.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
sudo singularity build --sandbox  and kill the process when image is loaded.

### What OS/distro are you running

```
$ cat /etc/os-release

AME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"```


### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
https://sylabs.io/guides/3.0/user-guide/installation.html

**Comment by jmstover** [comment]
Look in `/tmp/.sbuild-*` ... Singularity starts building in a temp location, and moves the structure over. It _should_ clean up on failure though... There's a `--no-cleanup` option to keep files around.

You may be seeing the docker cache structure?

**Comment by Lcornet** [comment]
Thanks

Indeed, delete build-* free a lot of space.

**Comment by dtrudg** [comment]
@Lcornet - note that 3.0.3 is pretty old now. I know that some cleanup issues have been fixed since then.
