### ISSUE TITLE
Singularity fails to mount cephfs with kernel driver. no parent mount point found

### ISSUE THREAD

**Issue by juztas** [apptainer/singularity#4918]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.2-1.1.el7
```

### Expected behavior

What did you expect to see when you do...?
Singularity fails to start with `no parent mount point found` if we use CEPH Kernel driver [1][2].  Once I have changed to use  CEPH Fuse Client [3] or [4], it works. 
```
bin/singularity --debug exec --home /wntmp/condor/execute/dir_37905/glide_0hLVwO/:/srv --bind /mnt/hadoop --bind /storage --bind /cvmfs --pwd /srv --contain --ipc --pid /cvmfs/singularity.opensciencegrid.org/cmssw/cms:rhel6 bash
```

```
[1]
$ df -h | grep storage
10.3.11.157:6789,10.3.16.147:6789,10.3.11.198:6789,10.3.10.12:6789,10.3.13.102:6789,10.3.16.148:6789:/  114T   56T   58T  49% /storage

[2] /etc/fstab # Failing one
10.3.11.157:6789,10.3.16.147:6789,10.3.11.198:6789,10.3.10.12:6789,10.3.13.102:6789,10.3.16.148:6789:/	/storage	ceph	name=admin,secretfile=/etc/ceph/client.key,_netdev	0	2
[3] /etc/fstab # Successful one
none    /storage  fuse.ceph ceph.id=admin,ceph.conf=/etc/ceph/ceph.conf,_netdev  0 2
[4] /etc/fstab # Successful one
10.3.11.157:6789,10.3.16.147:6789,10.3.11.198:6789,10.3.10.12:6789,10.3.13.102:6789,10.3.16.148:6789:/ /storage fuse.ceph ceph.id=admin,ceph.conf=/etc/ceph/ceph.conf,_netdev  0 2
```

### Actual behavior

What actually happend? Why was it incorrect?
```
$ cat sing_star_output | grep storage
DEBUG   [U=0,P=37021]      prepareAutofs()               Could not keep file descriptor for user bind path /storage: no mount point
DEBUG   [U=0,P=37010]      addUserbindsMount()           Adding /storage to mount list
DEBUG   [U=0,P=37010]      mountGeneric()                Mounting /var/singularity/mnt/session/rootfs/storage to /var/singularity/mnt/session/underlay/storage
FATAL   [U=0,P=37010]      Master()                      container creation failed: mount /storage->/storage error: while mounting /storage: while getting mount flags for /storage: while searching parent mount point entry for /storage: no parent mount point found
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
Latest singularity and cephfs.
```
$ yum list installed | grep ceph
ceph-common.x86_64                   2:13.2.6-0.el7                    @Ceph
ceph-fuse.x86_64                     2:13.2.6-0.el7                    @Ceph
libcephfs2.x86_64                    2:13.2.6-0.el7                    @Ceph
python-cephfs.x86_64                 2:13.2.6-0.el7                    @Ceph
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
`yum install singularity`

**Comment by jmstover** [comment]
I think this is the difference between fuse, and the standard cephfs ... IIRC, cephfs does some, non-standard stuff to make it work they way they wanted distributed.

@cclerget I think this would be similar to BTRFS where there was a virtual device on a subvolume. Ceph did some weird stuff when mounting a volume directly...  It has been a few years since I messed with it, but I do know that it had some weird behavior when you mounted Cephfs directly instead of a NFS mount, etc...

**Comment by dtrudg** [comment]
Likely ceph needs to be added to the existing list of `overlay` and `btrfs` to be handles specially here:

https://github.com/sylabs/singularity/blob/974607a4fbe7288cc2cb73a8fb7688260d58881d/pkg/util/fs/proc/proc.go#L121

@juztas - you may want to try changing that line to:

```
if entry.FSType == "btrfs" || entry.FSType == "overlay" || entry.FSType == "ceph" { 
```

Could you also provide the output of `cat /proc/self/mountinfo` on the host with the `ceph` mount?

**Comment by DrDaveD** [comment]
That line of code is that way in the release-3.5 branch, not in the 3.5.2 tag.  I am making a scratch epel rpm build for @juztas with this change and will post here with a link when it is ready.

**Comment by DrDaveD** [comment]
Here is the [rpm version 3.5.2-1.1.1](https://kojipkgs.fedoraproject.org//work/tasks/5844/39945844/singularity-3.5.2-1.1.1.el7.x86_64.rpm).  In addition to @dctrud's suggested change, it includes PRs #4880 and #4881 beyond tag 3.5.2.

**Comment by juztas** [comment]
Hi,

I tested https://kojipkgs.fedoraproject.org//work/tasks/5844/39945844/singularity-3.5.2-1.1.1.el7.x86_64.rpm and it works. Thanks!

**Comment by dtrudg** [comment]
Thanks @juztas and @DrDaveD  - PR #4922 has the small patch.
