### ISSUE TITLE
Availability of GPU Direct RDMA support with Singularity?

### ISSUE THREAD

**Issue by jon-chuang** [apptainer/singularity#4921]
### Version of Singularity: 3.4.0-1.2.el7
Running a Keras application with Horovod

`mpirun -npernode $mpi_tasks_per_node -np $np -x NCCL_DEBUG=INFO -x NCCL_IB_DISABLE=0 -x HOROVOD_MPI_THREADS_DISABLE=1 -x NCCL_SOCKET_IFNAME=^virbr0,lo -x LD_LIBRARY_PATH -x PATH --mca mtl ^mxm --mca pml ob1 --mca btl self,openib --mca btl_openib_want_cuda_gdr 1 $application $options`

### Expected behavior
e.g.
`NCCL INFO Ring 00 : 7[7000] -> 8[4000] [send] via NET/IB/0/GDRDMA`

### Actual behavior

`NCCL INFO Ring 00 : 7[7000] -> 8[4000] [send] via NET/IB/0`

### What OS/distro are you running
I am using Ubuntu 18.04 docker container on rhel7

**Comment by jmstover** [comment]
The only thing I can remember about this is there was a `nvidia_peer_mem` service (or similar) that needed to be ran on the Host. So, the RHEL7 host in this case. 

But I hardly messed with this... I don't recall if there was a socket that needed to be passed through, or if it loaded a kernel module... or what. :/

**Comment by jon-chuang** [comment]
I see. I did not mention that I have `nv_peer_mem` installed on both the host and the container. I am not sure what kind of configuration needs to be done in terms of starting the `nv_peer_mem` service.

**Comment by dtrudg** [comment]
Hi @jon-chuang - there may be some hints here, where the same issue was hit with docker containers: https://github.com/Mellanox/nv_peer_memory/issues/41#issuecomment-396028860

Note that `nv_peer_mem` should only be on the host.

**Comment by jon-chuang** [comment]
Hi @dctrud 
I got the same behaviour regardless of whether nv_peer_mem is installed on the host only or also in the container. 
The above issue applies to docker, but not to singularity. It is recommended (for instance in this report: https://www.dellemc.com/tr-tr/collaterals/unauth/technical-guides-support-information/products/storage/h17354-dl-architecture-guide.pdf, section 3.1) to run singularity containers with the ncessary Infiniband drivers installed in the container. I am not sure if this means nv_peer_mem too. 
I am unable to run docker on my cluster.

**Comment by dtrudg** [comment]
`nv_peer_mem` definitely needs to be on the host. It's a kernel module, and the scripts etc only control loading / removal of that kernel module. If you do an `lsmod` on the host can you verify it is loaded there?

If it is loaded on the host, verified by `lsmod`, what do you get from `nvidia-smi topo -m` both inside and outside a container, and if you do a diff of `ofed_info` inside / outside is there anything significant that appears?

This might be a good topic to raise on the mailing list here: https://groups.google.com/a/lbl.gov/forum/#!forum/singularity as it'd be seen by additional helpful HPC folk may have some insight.

**Comment by dtrudg** [comment]
@jon-chuang - to follow up on this, can you do...

> If it is loaded on the host, verified by lsmod, what do you get from nvidia-smi topo -m both inside and outside a container, and if you do a diff of ofed_info inside / outside is there anything significant that appears?

... that's what we'd need to suggest anything else to look at.

**Comment by dtrudg** [comment]
Closing this as there has been no follow-up. Please feel free to re-open with the information requested.

**Comment by samcmill** [comment]
3.4.0 had a very nasty bug where PID namespaces were enabled by default.  This prevents NCCL from working.

**Comment by dtrudg** [comment]
@samcmill - this comment suggests that's not the case (pid namespace prevents it working) now: https://github.com/NVIDIA/nccl/pull/248#issuecomment-524109437

Was there a particular range of nccl versions or driver versions affected? Am interested in case this comes up in other valid cases (not the 3.4.0 bug) that involve a pid namespace. Thanks.

_Edit:_ actually... maybe not. I'm not clear in that PR thread if it only means that if you enforce the host PID namespace things will work properly when they weren't before.

**Comment by dctrud** [comment]
Ahh... I skipped over the fact that it got into 2.5.6 of NCCL somehow. :+1:
