### ISSUE TITLE
RFE for listing containers from a Library 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [apptainer/singularity#4927]
I am using singularity 3.4.2 and as far as i can check the ``singularity search`` is only capable of searching containers across a library. It does not solve the problem of getting a listing of all containers  in a library. 

What i would like to do is get all the containers from the library ``https://library.sylabs.io/library/shahzebsiddiqui/easybuild`` hosted in sylabs. The path to my container library is https://cloud.sylabs.io/library/shahzebsiddiqui/easybuild/

```
$ singularity search --library "https://library.sylabs.io/library/shahzebsiddiqui/easybuild" binutils
No users found for 'binutils'
No collections found for 'binutils'
Found 1 containers for 'binutils'
        library://shahzebsiddiqui/easybuild/binutils
                Tags: 2.28
```

I tried to do a search by passing ``*`` and that didnt work.

```
c455-053[knl](797)$ singularity search  --library "https://library.sylabs.io/library/shahzebsiddiqui/easybuild" *
Error for command "search": accepts 1 arg(s), received 2

Usage:
  singularity [global options...] search [search options...] <search_query>

Run 'singularity search --help' for more detailed usage information.
```

I anticipate maybe have some feature like ``singularity query`` that combines the feature of ``singularity search`` and add more capability. So basically rename ``search`` to ``query``.

**List all collection for current user**
``singularity query collection``

**List all collection for another user**
``singularity query collection --name=<uid>``

**List all containers from a library**
``singularity query list --library="https://library.sylabs.io/library/shahzebsiddiqui/easybuild"``

**List binutils and anaconda3 container from a library**
``singularity query list  --library="https://library.sylabs.io/library/shahzebsiddiqui/easybuild" name=binutils,anaconda3``

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by shahzebsiddiqui** [comment]
this task can be closed i realize this is feature was added to singularity https://singularity.hpcng.org/user-docs/master/cli/singularity_search.html?highlight=singularity%20search
