### ISSUE TITLE
No Mac support for overlay or writable

### ISSUE THREAD

**Issue by rherban** [apptainer/singularity#4929]
### Version of Singularity:
3.3.0-rc.1.658.g7427b73f1.dirty (singularity desktop for mac, beta .1)

### Expected behavior

What did you expect to see when you do...?
be able to use overlay or writable images

### Actual behavior

What actually happend? Why was it incorrect?

```
randys-mbp:~ rherban$ sudo singularity shell --overlay sandbox/ centos_latest.sif
Error for command "shell": unknown flag: --overlay
```

```
randys-mbp:~ rherban$ sudo singularity shell --writable centos_latest.sif
Password:
Error for command "shell": unknown flag: --writable
```

**Comment by dtrudg** [comment]
Closing as Singularity Desktop currently not maintained.
