### ISSUE TITLE
Undefined symbol: singularity_config_init

### ISSUE THREAD

**Issue by pditommaso** [apptainer/singularity#493]
I've just updated Singularity to latest version (from the master `6007d3a1`). However as soon asI try to execute a container I get the following error message: 

```
/usr/local/libexec/singularity/sexec: symbol lookup error: /usr/local/libexec/singularity/sexec: undefined symbol: singularity_config_init
```

These are my sys info 

```
$ cat /etc/issue.net 
Ubuntu 16.04.1 LTS

$ uname -a
Linux my-host-name 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gmkurtzer** [comment]
Can you confirm that Singularity was installed into a fresh new directory? It looks like old library or files are in there causing an issue. Try with a --prefix=/something/random or removing all old bits and let me know!

Thanks!

**Comment by pditommaso** [comment]
I've tried both (`sudo rm -rf  /usr/local/libexec/singularity` and installed in a fresh new dir) but I'm still getting the same issue.

**Comment by vsoch** [comment]
Did you remove the library (.so) files as well? eg:

      ls /usr/local/lib/singularity/
      libsingularity.a   libsingularity.so    libsingularity.so.1.0.0
      libsingularity.la  libsingularity.so.1

**Comment by pditommaso** [comment]
Just tried the following: 
```
sudo rm -rf /usr/local/lib/singularity/
sudo rm -rf /usr/local/libexec/singularity/
sudo rm -rf /usr/local/bin/singularity 
sudo rm -rf /usr/local/bin/run-singularity 
```

No way.

**Comment by vsoch** [comment]
No way? Is that good or bad? I'm in suspense!

**Comment by jmstover** [comment]
@pditommaso Does it show up if you run:
`objdump -TC /path/to/libsingularity.so.1.0.0 | grep -i 'singularity_config_init'`

It actually doesn't in mine, but I'm not getting that error either. Mine was built from the 2.2.1 tag.

Is your LD_LIBRARY_PATH setup to include the /usr/local/lib* dirs?

**Comment by vsoch** [comment]
It's definitely not an elegant uninstall, if that is what you are saying, haha.

**Comment by pditommaso** [comment]
I mean, the same issue.

**Comment by pditommaso** [comment]
```
$ objdump -TC /path/to/libsingularity.so.1.0.0 | grep -i 'singularity_config_init'
objdump: '/path/to/libsingularity.so.1.0.0': No such file
```

I don't have any `LD_LIBRARY_PATH` variable defined.

**Comment by vsoch** [comment]
Did you do `/path/to/libsingularity.so` or did you replace with the path?

**Comment by pditommaso** [comment]
Facepalm moment :)

```
$ objdump -TC /usr/local/lib/singularity/libsingularity.so.1.0.0 | grep -i 'singularity_config_init'
000000000000a060 g    DF .text	000000000000006d  Base        singularity_config_init
```

**Comment by jmstover** [comment]
So ... does doing:
`export LD_LIBRARY_PATH=/usr/local/lib/singularity:${LD_LIBRARY_PATH}`
`singularity exec [img] date`

Change anything?

**Comment by gmkurtzer** [comment]
Hi @pditommaso, can you do an ldd on /usr/local/libexec/singularity/sexec please?

**Comment by pditommaso** [comment]
Nope 

```
$ echo $LD_LIBRARY_PATH
/usr/local/lib/singularity
$ singularity shell <img>
/usr/local/libexec/singularity/sexec: symbol lookup error: /usr/local/libexec/singularity/sexec: undefined symbol: singularity_config_init
```

**Comment by pditommaso** [comment]
```
$ ldd /usr/local/libexec/singularity/sexec
	linux-vdso.so.1 =>  (0x00007fffd3bfd000)
	libsingularity.so.1 => /usr/local/lib/libsingularity.so.1 (0x00007f31f0fd8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f31f0bf3000)
	/home/pditommaso/.linuxbrew/lib/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00005589091fb000)
```

**Comment by gmkurtzer** [comment]
Whoa, I never seen that it was possible to remap the linker library itself! Cool and scary!

The only time I have seen that is when an older library is getting linked instead of the one it was compiled against... Orrrrr.... There is a code error. But I just rebuilt the master branch, and I can not seem to replicate this error.

<thinking.....>

**Comment by jmstover** [comment]
Hrmm... Can you try preloading libsingularity.so.1 ?

`LD_PRELOAD=/usr/local/lib/singularity/libsingularity.so.1 singularity exec [img] date`

Just curious if trying to force a preload could change it...

**Comment by pditommaso** [comment]
Yes! It works in this way.

**Comment by jmstover** [comment]
Hrmm... if that works then my guess would be it would have something to do with the linuxbrew wrapper. I wonder ... What if you did:

`mkdir -p ${HOME}/.linuxbrew/usr/local/lib/singularity`
`ln -sf /usr/local/lib/singularity/libsingularity.so.1 ${HOME}/.linuxbrew/usr/local/lib/singularity/libsingularity.so.1`

Basically... dump a symlink in the ${HOME}/.linuxbrew structure to the outside library. Then try running without the LD_PRELOAD and see if that changes anything. No idea if that would help... but with how it's doing some wrapping I'm wondering if the loading is running into issues.

**Comment by pditommaso** [comment]
No. This does not solve the problem.

**Comment by gmkurtzer** [comment]
I am not familiar with Linuxbrew or how/why it is affecting the linker. Can you disable it temporarily and see if that helps?

**Comment by pditommaso** [comment]
I've completely deleted Linuxbrew and recompiled Singularity .. still the same issue. 

```
$ ldd /usr/local/libexec/singularity/sexec
	linux-vdso.so.1 =>  (0x00007ffd109e7000)
	libsingularity.so.1 => /usr/local/lib/libsingularity.so.1 (0x00007fb7b0ab9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb7b06d5000)
	/lib64/ld-linux-x86-64.so.2 (0x000055d09ebb2000)

$ singularity exec singularity-scientific-example.img date
/usr/local/libexec/singularity/sexec: symbol lookup error: /usr/local/libexec/singularity/sexec: undefined symbol: singularity_config_init

$ LD_PRELOAD=/usr/local/lib/singularity/libsingularity.so.1 singularity exec singularity-scientific-example.img date
Fri Feb 24 13:31:03 UTC 2017
```

**Comment by gmkurtzer** [comment]
Are you getting this on any other systems? I can't replicate. :(

Can you try the 'development' branch?

**Comment by pditommaso** [comment]
Fixed in the development branch! ✌️

**Comment by gmkurtzer** [comment]
WAHOO! Thanks @pditommaso, I am closing this!
