### ISSUE TITLE
configure: error: Unable to find the libarchive headers, need package libarchive-devel (libarchive-dev on Debian/Ubuntu) 

### ISSUE THREAD

**Issue by rpauly** [apptainer/singularity#4933]
### Version of Singularity:

What version of Singularity are you using? Run:
singularity 2.6.1
```
$ singularity version

```

### Expected behavior

What did you expect to see when you do...?

### Actual behavior

What actually happened? Why was it incorrect?
configure: error: Unable to find the libarchive headers, need package libarchive-devel (libarchive-dev on Debian/Ubuntu) 

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.7"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Oracle Linux Server 7.7"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:7:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.7
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.7


```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
wget https://github.com/sylabs/singularity/releases/download/2.6.1/singularity-2.6.1.tar.gz

**Comment by dtrudg** [comment]
You would need to install the package `libarchive-devel` using `yum install  libarchive-devel` to build this version of Singularity on Oracle Linux.

Please note that the open-source 2.x series of Singularity is no longer developed or supported.
