### ISSUE TITLE
Build killed singularity hub on time limit just before completion

### ISSUE THREAD

**Issue by Sparrow0hawk** [apptainer/singularity#4934]
I'm trying to provide my singularity container to singularity hub but it takes almost the entire 2 h to fully build leading to it getting killed just before completion https://singularity-hub.org/containers/11958/log

Is there anyway this build can be partially extended to a 3 h limit?

**Comment by dtrudg** [comment]
Hi @Sparrow0hawk - Singularity Hub is a separate project. We can handle issues with the Singularity command line interacting with it here, but for issues or questions about the service itself, please could you post to the Singularity Hub project at the issue tracker below:

https://github.com/singularityhub/singularityhub.github.io/issues

Thanks.

**Comment by jonathanhyunmoon** [comment]
Hi @Sparrow0hawk, were you able to resolve your issue?

**Comment by Sparrow0hawk** [comment]
No I didn't resolve this in the end and just directly shared the outputted .sif file.
