### ISSUE TITLE
apps subcommand no longer exists

### ISSUE THREAD

**Issue by Xophmeister** [apptainer/singularity#4937]
### Version of Singularity: 

What version of Singularity are you using? Run:

```
$ singularity version

```

```
3.3.0
```

### Expected behavior

`apps` is no longer a valid subcommand. I expect to see a list of apps in a given image when running:

    singularity apps my_image.simg

...per the [documentation](https://sylabs.io/guides/3.3/user-guide/cli/singularity_apps.html), which worked as described in previous versions. I note that, from 3.4.0, `singularity apps` has been removed from the documentation.

### Actual behavior

Singularity responds with the usage text and a non-zero exit code. I expected to get a list of apps that exist within my image.

### Steps to reproduce this behavior

Run:

    singularity apps my_image.simg

...on an image containing multiple apps.

### What OS/distro are you running

```
$ cat /etc/os-release


```

```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

It is installed as a managed service on our compute farm.

**Comment by jmstover** [comment]
@Xophmeister 
That was moved to the `inspect` command. Try instead:
```
singularity inspect --list-apps my_image.simg
```
