### ISSUE TITLE
Wrong group ownership when installing singularity in directories with setgid.

### ISSUE THREAD

**Issue by damianam** [apptainer/singularity#4940]
### Version of Singularity:

```
3.5.2
```

### Expected behavior

Following `make install`, using a prefix directory that belongs to `$USER:any_non_primary_group`, and that has _setgid,_ I expect all directories and files installed under that prefix to have the same group ownership.

### Actual behavior

Some directories have _setgid_ and some doesn't:

Correct ownership (respect _setgid_):
```
$ find $PREFIX -type d -perm /2000
$PREFIX
$PREFIX/libexec
$PREFIX/libexec/singularity
$PREFIX/etc
$PREFIX/var
$PREFIX/var/singularity
$PREFIX/var/singularity/mnt
```

Incorrect ownership (_setgid_ not respected):
```
find $PREFIX -type d -not -perm /2000
$PREFIX/bin
$PREFIX/libexec/singularity/bin
$PREFIX/libexec/singularity/cni
$PREFIX/etc/bash_completion.d
$PREFIX/etc/singularity
$PREFIX/etc/singularity/seccomp-profiles
$PREFIX/etc/singularity/cgroups
$PREFIX/etc/singularity/actions
$PREFIX/etc/singularity/network
$PREFIX/var/singularity/mnt/session
```

As a result, the files and directories under the directories with wrong group ownership have also wrong group ownership.

The culprit is the use of `install -d` to create those destination directories. Assuming that `/directory_with_setgid` exists, has _setgid_ and belongs to a group different than the primary group of the current process, `install -d /directory_with_setgid/subdirectory/singularity/bin` will create the `/directory_with_setgid/subdirectory` and `/directory_with_setgid/subdirectory/singularity` paths with _setgid_ and the right group ownership, but will create `/directory_with_setgid/subdirectory/singularity/bin` without _setgit_ and correct group ownership. Any file/directory created there afterwards will have wrong group ownership. That's probably one of the reasons why autoconf uses `mkdir -p` by default, instead of `install -d`.

### Steps to reproduce this behavior

1. Create a directory with a group ownership different than the current process primary group
2. Set _setgid_ on that directory with `chmod +s`
3. Install from source using that directory as prefix
4. Check the group ownership of all files/directories installed

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

From source, using a custom EasyBuild recipe.

**Comment by cclerget** [comment]
Hi @damianam , #4942 should fix that, if you can give it a try and confirm it works for you ? Thanks !
