### ISSUE TITLE
build: failed to make environment dirs

### ISSUE THREAD

**Issue by hollowec** [apptainer/singularity#4943]
### Version of Singularity:

```
version 3.5.2-1.1.el7
```

Some Docker container images do not enable user write permission on /, which causes Singularity to fail to insert the /.singularity.d directotory into the image during the SIF conversion/build process.  One such container is CERN's CC7 base image:
```
$ singularity shell docker://gitlab-registry.cern.ch/linuxsupport/cc7-base:latest
ERROR:   build: failed to make environment dirs: mkdir /home/tmp/rootfs-f985df87-3624-11ea-a275-0cc47afd3556/.singularity.d: permission denied
FATAL:   Unable to handle docker://gitlab-registry.cern.ch/linuxsupport/cc7-base:latest uri: unable to build: packer failed to pack: while inserting base environment: build: failed to make environment dirs: mkdir /home/tmp/rootfs-f985df87-3624-11ea-a275-0cc47afd3556/.singularity.d: permission denied

I've reproduced the problem with both the EPEL 3.5.2 RPM on SL7, and via the 3.5.2 source on Fedora 31.

**Comment by dtrudg** [comment]
@hollowec - what's the Dockerfile giving rise to this container? `/` not being `755` strikes me as very unusual.

**Comment by hollowec** [comment]
Hi @dctrud, I believe CERN IT is using Koji to build, without using a Dockerfile directly:
https://gitlab.cern.ch/linuxsupport/cc7-base

**Comment by jmstover** [comment]
@dctrud ... I've unfortunately seen it a few times. Generally they're expecting you to be running as root, so the non-write access gets ignored since well ... you're root. 

I have a CentOS server here that the `/` permissions are `0555` ... But of course, as root you can still make a directory like `mkdir -p /lala` with no error.

Should it be this way ... No. Is it? *sigh*

**Comment by dtrudg** [comment]
@hollowec - okay thanks for the info. We had to workaround some oddness out of CERN Koji builds of Scientific Linux containers before with (host specific) selinux xattrs being incorrectly included in the built container. On looking into that It appeared the Koji build system used by CERN was older than the versions used for Fedora and CentOS builds which have corrected, different behavior building docker containers.

@jmstover - yes, this probably warrants the workaround.
