### ISSUE TITLE
unable to add remote end point

### ISSUE THREAD

**Issue by ashwinidr3** [apptainer/singularity#4949]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

3.4


<!-- please include command-line output in a code block -->

### Expected behavior

singularity remote add test domain-name
INFO:    Remote "test" added.
INFO:    Authenticating with remote: test
Generate an API Key at https://domain-name/auth/tokens, and paste here:
API Key:
expected to accept the api key 

### Actual behavior

singularity remote add test domain-name
INFO:    Remote "test" added.
INFO:    Authenticating with remote: test
Generate an API Key at https://domain-name/auth/tokens, and paste here:
API Key:
FATAL:   while verifying token: while getting token service uri: error response from server: 404

I get this error inspite of pasting the correct token

<!-- if this is a feature request, you can ignore this next part -->



How can others reproduce this issue/problem?

singularity remote add test domain-name
INFO:    Remote "test" added.
INFO:    Authenticating with remote: test
Generate an API Key at https://domain-name/auth/tokens, and paste here:
API Key:

### What OS/distro are you running

$ cat /etc/os-release

RHEL 7.7 - VM
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

part of rhel repositories

**Comment by dtrudg** [comment]
@ashwinidr3 - what is your remote endpoint here? This should work with the Sylabs Cloud service (cloud.sylabs.io), and for any Sylabs customer with an on-premise Singularity Enterprise installation. If you have access to the latter, you may wish to email support@sylabs.io directly.

**Comment by ashwinidr3** [comment]
I have sregistry configured on my machine. Does it support sregistry ?

**Comment by dtrudg** [comment]
@ashwinidr3 - sregistry is not supported as a remote. The remote functionality is for using Sylabs cloud services (library + builder + keystore) or the commercial Singularity enterprise.

Singularity 3.x supports pull/push using `shub://` URLs which I believe should work with sregistry.
