### ISSUE TITLE
HOME=/ and nobody user problem

### ISSUE THREAD

**Issue by rynge** [apptainer/singularity#495]
Hello,

While running singularity on a distributed system, one of my jobs ended up on running under user "nobody" on a RHEL 7 system. This was expected, but Singularity fails because the home dir is set to /.

singularity --debug exec --bind /cvmfs --bind $PWD:/srv --pwd /srv --scratch /var/tmp --scratch /tmp --containall /cvmfs/singularity.opensciencegrid.org/rynge/osgvo:el6 echo "Hello World"
ERROR  : Could not identify basedir for home directory path: /

I was considering changing https://github.com/singularityware/singularity/blob/master/src/util/file.c#L405 to return '/' as a basedir to '/', but was not sure if such a change would lead to problems somewhere else.

A minor point is that the exit code for that error is 0.

One thing I did try was setting the home directory of "nobody" to /var/lib/nobody, and created the dir. I then get:

WARNING: Could not bind scratch directory into container /tmp/.singularity-session-99.48.356/scratch/tmp: No such file or directory
ABORT  : Retval = 255

This is a little bit weird as if I use SINGULARITY_NOSESSIONCLEANUP=1 I can see that directory existing. Is there maybe something else special with the nobody user?

I will attach debug logs for these two - please let me know if you want me to try something.

[singularity-nobody.txt](https://github.com/singularityware/singularity/files/783674/singularity-nobody.txt)

[singularity-nobody-with-home.txt](https://github.com/singularityware/singularity/files/783676/singularity-nobody-with-home.txt)

**Comment by jmstover** [comment]
Hi Mats,

  Yeah, it looks like util/file.c is returning NULL for basedir() there.
I'm wondering if setting it to '/' by default wouldn't work, and if there's
an actual directory given, then return what gets parsed out. Or a check
wherever bassdir() is being called from for a NULL return and then setting
it to '/'.

-J

**Comment by rynge** [comment]
I tried both those approaches, but both end up in problem 2 above:

WARNING: Could not bind scratch directory into container /tmp/.singularity-session-99.48.356/scratch/tmp: No such file or directory

However, this is different from setting the home dir to /var/lib/nobody. If I just use / as the basedir, the directory path above is wrong - the directory is created under home.tmp:

$ ls -l /tmp/.singularity-session-99.48.356/home.tmp/
drwxr-x--- 3 nobody nobody 16 Feb 17 08:37 scratch

**Comment by rynge** [comment]
After playing a little bit more with this, I think it is better to return early from singularity_mount_home(), lilke:

[nobody-slash-homedir.txt](https://github.com/singularityware/singularity/files/785253/nobody-slash-homedir.txt)

This seems to work for the cases I tried, but it would be good to have somebody who knows the home.c code to look it over.

**Comment by DrDaveD** [comment]
Hi Mats,

Are you running a released singularity version or one compiled from source?  The master branch has an additional feature from PR #251 that I contributed and is not yet released, which allows you to control the home directory inside the container separately from the source path.   This isn't the solution for the problem you report, but it would probably at least give you a workaround.

Dave Dykstra

**Comment by rynge** [comment]
I tried both the released version and master. If it is the SINGULARITY_HOME env variable you are referring to, I tried it a little bit but then got distracted. The current workaround we are using with 2.2.1 is changing the home directory for the nobody user to a non-existent directory (/usr1/nobody in this case).

I tried with a non-existent home directory under /var, but that hits the second problem I mentioned above:

WARNING: Could not bind scratch directory into container /tmp/.singularity-session-99.48.356/scratch/tmp: No such file or directory
ABORT : Retval = 255

**Comment by DrDaveD** [comment]
I'm referring to the extended syntax for the -H/--home option.  You're right though that it can also be set in $SINGULARITY_HOME (internally the -H/--home option sets this) but the new functionality is that it can have a colon in it and have separate paths for outside and inside the container.

**Comment by rynge** [comment]
I tried again, and found a problem in util.c if you don't use the colon:

    if ( ( homedir = envar_path("SINGULARITY_HOME") ) != NULL ) {
        char *colon = strchr(homedir, ':');
        if ( colon != NULL ) {
            homedir = colon + 1;
            singularity_message(VERBOSE2, "Set the home directory (via envar) to: %s\n", homedir);
            return homedir;
        }
    }

That should probably be:

    if ( ( homedir = envar_path("SINGULARITY_HOME") ) != NULL ) {
        char *colon = strchr(homedir, ':');
        if ( colon != NULL ) {
            homedir = colon + 1;
        }
        singularity_message(VERBOSE2, "Set the home directory (via envar) to: %s\n", homedir);
        return homedir;
    }

**Comment by DrDaveD** [comment]
No, that's intentional.  If there's no colon, then the -H option (and therefore $SINGULARITY_HOME) only sets the source of the home directory outside the container like the 2.2 -H option does.  The get_homedir() function then falls through and looks up the home directory from the passwd file.

**Comment by rynge** [comment]
Thanks Dave - I now have a workaround for this problem using your colon mapping. The trick is to use --home $SRC:$DST which matches -- bind $SRC:$DST. When those two match, the directory has already been mounted and we will not reach the problematic part of trying to mount the home directory.

I think a fix should still go in to handle the cases of home=/ or a non-existent home directory.

**Comment by DrDaveD** [comment]
Mats, a correction: I just discovered that the functionality from this feature was included in singularity 2.2.1.  Just the commit you were looking at is there, but not the rest of pr #251.  Follow the discussion there if you're interested.

> The trick is to use --home $SRC:$DST which matches -- bind $SRC:$DST.

Ah but then you get a warning message, correct?  "WARNING: Not mounting requested bind point (already mounted in container)".  Can you leave out the --bind $SRC:DST and just use --home $SRC:$DST?

**Comment by gmkurtzer** [comment]
Hi @rynge,

In the 'development' branch, I think this is fixed but if you can test, that would be fantastic.

Thanks!

**Comment by rynge** [comment]
Hi @gmkurtzer 

Something else probably broke in development branch. I see a lot of errors like:

$ /ccg/software/singularity/development/bin/singularity exec --home $PWD:/srv --pwd /srv --scratch /var/tmp --scratch /tmp /tmp/OSGVO-EL7-latest.img echo "Hello World"
ERROR  : Could not write /var/lib/singularity/mnt/final/passwd: Permission denied
ERROR  : Failed copying template passwd file to tmpdir: Permission denied
ABORT  : Retval = 255

**Comment by gmkurtzer** [comment]
Uh-oh. We just made some more change to the development (unlreated, but good to have). Can you update and send me the --debug output including the full command that you are testing with?

Thanks!

**Comment by rynge** [comment]
Thank you for spending time on this issue. I have attached the log for the command:

singularity --debug exec --home $PWD:/srv --pwd /srv --scratch /var/tmp --scratch /tmp /tmp/OSGVO-EL7-latest.img echo "Hello World"

[singularity-home-2.txt](https://github.com/singularityware/singularity/files/874417/singularity-home-2.txt)

**Comment by gmkurtzer** [comment]
Hi @rynge,

I think I tracked it down and fixed in the latest development branch. Can you give that a whirl and let me know?

Thanks!

**Comment by rynge** [comment]
Things works for my regular user, but user nobody, with HOME=/ still has the basedir problem described when I opened the ticket:

singularity exec --bind $PWD:/srv --pwd /srv /tmp/OSGVO-EL7-latest.img echo "Hello World"
ERROR  : Could not identify basedir for home directory path: /
ABORT  : Retval = 255

It does work if I use --home instead of --bind in the above command.

Full debug log:

[singularity-home-3.txt](https://github.com/singularityware/singularity/files/880659/singularity-home-3.txt)

**Comment by gmkurtzer** [comment]
I came up with a workaround which avoids mounting the home directory if it is not owned by the calling user. That seems like a reasonable assumption to make and works for this particular issue.

Check it out and let me know what you think. Thanks!

Greg

**Comment by rynge** [comment]
That fixed the issue. I tried with my regular user, and user nobody, and it works as expected.

Thank you @gmkurtzer !

**Comment by gmkurtzer** [comment]
Fantastic, thanks for confirming @rynge! I'm closing the issue... I love closing issues. haha.
