### ISSUE TITLE
turn off SECBIT_NO_SETUID_FIXUP

### ISSUE THREAD

**Issue by nzasch** [apptainer/singularity#4951]
Hi

is there a way to turn off SECBIT_NO_SETUID_FIXUP setting at runtime?

thanks
nzasch

### Version of Singularity: 3.4.1

singularity exec /tmp/test.sif capsh --print

### Expected behavior

Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)

### Actual behavior

Securebits: 014/0xc/4'b1100
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: yes (locked)
 secure-keep-caps: no (unlocked)

### What OS/distro are you running

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

**Comment by cclerget** [comment]
Hi @nzasch , this issue has been fixed in 3.5.1, you can try the latest release https://github.com/sylabs/singularity/releases/tag/v3.5.2. Closing the issue as already fixed.
