### ISSUE TITLE
Singularity 3.5 can no longer use squashfs files with --overlay

### ISSUE THREAD

**Issue by prioux** [apptainer/singularity#4956]
### Version of Singularity:

3.5.2-1.el7

### Expected behavior

Start the container with the squashfs filesystem specified by `--overlay` visible in it.

This worked with Singularity 3.2 to 3.4. Fails in 3.5.

### Actual behavior

Singularity complains with an error message:

```
FATAL:   failed to open overlay image data.squashfs: could not set image writable: squashfs is a read-only filesystem
```
### Steps to reproduce this behavior

1- Create a simple squashfs filesystem in a file:

```
mksquashfs somedatadirectory data.squashfs
```
2- Try to overlay it with any container of your choice:

```
singularity shell --overlay=data.squashfs imag.simg
```

### What OS/distro are you running

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
```

### How did you install Singularity

With the package manager.

**Comment by cclerget** [comment]
Hi @prioux , it actually requires to explicitly set `:ro` option like this :

```
singularity shell --overlay=data.squashfs:ro imag.simg
```

Will look at to restore the previous behavior without the mandatory option.

**Comment by prioux** [comment]
@cclerget Ah thanks. Yes, I would really appreciate having the simpler behavior that doesn't require the `:ro`, given that SquashFS filesystems are never writable anyway, and you're already detecting the filesystem type for each `--overlay` option. It's particularly advantageous for automatic systems where several `--overlay=` options are added by an external script, and we get a mix of ext3 and SquashFS files in there.

**Comment by prioux** [comment]
Oh merci @cclerget!
