### ISSUE TITLE
Incorrect installation instructions.

### ISSUE THREAD

**Issue by royfrancis** [apptainer/singularity#4966]
The instructions here do not work for Ubuntu 18.04:
https://singularity.lbl.gov/install-linux
https://sylabs.io/guides/3.5/user-guide/quick_start.html

This works:
https://github.com/sylabs/singularity/blob/master/INSTALL.md

**Comment by dtrudg** [comment]
Hello.

The https://singularity.lbl.gov/install-linux link is outdated per the banner on that page. It is no longer updated.

If there is an issue with the user-guide, please could you report it at: https://github.com/sylabs/singularity-userdocs/issues

Detail of the exact problem you see would be appreciated.

I am going to close this issue, as the `INSTALL.md` which is in this repository was reported working.
