### ISSUE TITLE
[Proposal] build spec section for %environment

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#497]
In case we haven't logged this proper, I want to propose again having an `%environment` section in the build spec.  The reason is because I've seen people wanting to include environment exports many times in their files, and it usually looks something like:

      echo "export PATH=/poodles/and/bits:$PATH" >> /environment

and the issue is that, if they don't do a leading carriage return, the container spits out an error when you try to interact with it. I'm undecided about If we should add this section as saved metadata or not. If we add it, the resulting file could optionally be written at the highest priority in the `.env` folder under the main metadata folder. However, this might run into conflicts. We could also just add the section to /environment at the time of generation and discard, which might be cleaner.

**Comment by gmkurtzer** [comment]
Thanks for this, great idea and we will get it into the lib-refactor branch ASAP!

**Comment by gmkurtzer** [comment]
Done :)

**Comment by vsoch** [comment]
This is the greatest PR! I have something extremely cool I did with it to show very soon :)
