### ISSUE TITLE
Unfriendly error message when pushing to invalid library path

### ISSUE THREAD

**Issue by EmmEff** [apptainer/singularity#4970]
### Version of Singularity:

v3.5.2

### Expected behavior

Proper error message indicating the library path is invalid.

### Actual behavior

What actually happened? Why was it incorrect?

```sh
wedge  singularity singularity push -U ~/delme.sif library://emmeff/default/alpine/not/valid
WARNING: Skipping container verifying
FATAL:   Unable to push image to library: error decoding entity: json: cannot unmarshal array into Go struct field EntityResponse.data of type client.Entity
wedge  singularity
```

### Steps to reproduce this behavior

As above.

**Comment by EmmEff** [comment]
Related to https://github.com/sylabs/scs-library-client/issues/68

**Comment by dtrudg** [comment]
Closed by 5044

**Comment by nathanjmorton** [comment]
This error can result from putting the filename in the library upload path.

Wrong way:
`$ singularity push image.sif library://username/default/project/image:tag`
Right way:
`$ singularity push image.sif library://username/default/project`

It will upload as image:sha256.something in the cloud project folder so your pull command would be 
`$ singularity pull library://username/default/image:sha256.something`
as opposed to
`$ singularity pull library://username/default/image:tag`

There is probably a way to remedy this. I just got started with the docs.
