### ISSUE TITLE
User shell isn't the same inside the image than on host!

### ISSUE THREAD

**Issue by kamedodji** [apptainer/singularity#4984]
### Version of Singularity:

```
$ singularity version
3.2.1
```

### Expected behavior

same user shell within the container than on the host

### Actual behavior

User shell in the container isn't the same than on the host

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

Host :
```
$ egrep "config passwd"  /usr/local/etc/singularity/singularity.conf
config passwd = yes`

$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Jan 27 21:33 /bin/sh -> dash

$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```
Container : CentOS 7, 8

```
admin@localhost:~$  getent passwd admin
admin:x:1000:1000:Admin User:/home/admin:/bin/bash

admin@localhost:~$  singularity shell centos8.0.sif
Singularity centos8.0:~> ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Jan 27 21:33 /bin/sh -> bash
Singularity centos8.0:~> getent passwd admin
admin:x:1000:1000:Admin User:/home/admin:/bin/sh


### How did you install Singularity

Source

**Comment by dtrudg** [comment]
@kamedodji - this is the expected behaviour. The shell executable to be run must be present inside the container. We can't be sure if a specific shell executable will be available in a container - `/bin/sh` is the lowest common denominator we can rely on due to the POSIX spec. In different containers `/bin/sh` may be a symlink to `dash` `bash` or something else, depending on the distribution in that container.

It's not possible to carry over the user shell from the host with any kind of certainty. E.g. if a user has `zsh` or `fish` set on the host, those are very unlikely to be available in most containers. `/bin/sh` is the most reliable and compatible thing to use here.

**Comment by kamedodji** [comment]
> @kamedodji - this is the expected behaviour. The shell executable to be run must be present inside the container. We can't be sure if a specific shell executable will be available in a container - `/bin/sh` is the lowest common denominator we can rely on due to the POSIX spec. In different containers `/bin/sh` may be a symlink to `dash` `bash` or something else, depending on the distribution in that container.
> 
> It's not possible to carry over the user shell from the host with any kind of certainty. E.g. if a user has `zsh` or `fish` set on the host, those are very unlikely to be available in most containers. `/bin/sh` is the most reliable and compatible thing to use here.

Thx @dctrud !

**Comment by kamedodji** [comment]
Last question @dctrud about this feature : have i a way to force singularity to conserve user shell,
as i'm sure that the target shell exist in the container ?

**Comment by cclerget** [comment]
@kamedodji There is no such way to force that but came to the question: what is your use case for this requirement ?

**Comment by kamedodji** [comment]
> @kamedodji There is no such way to force that but came to the question: what is your use case for this requirement ?

Hello @cclerget! We use SLURM client like `salloc` inside the container for a particular use case (we don't want to use `srun singularity exec <image>`)
The issue is that, `/bin/sh`, despite is a link to `/bin/bash`, failed to  `posix mode`.
And as we use many non posix compliant, particularly `bash process substitution`...

**Comment by cclerget** [comment]
@kamedodji I don't really understand why while `/bin/sh` pointing to `/bin/bash`, it doesn't work. One thing you can try once entered in the container is :

```
tmp=`mktemp` && sed 's/:\/bin\/sh/:\/bin\/bash/' /etc/passwd > $tmp && cat $tmp > /etc/passwd; rm $tmp
```

To check if it solves issue

**Comment by dtrudg** [comment]
@kamedodji - you can force the shell on a `singularity shell` command with the `-s` option...

```
singularity shell -s /bin/bash
```

Also, you could create a `%runscript` in your container which does an `exec` of `/bin/bash` and then `singularity run` would drop you into `/bin/bash` too.

**Comment by kamedodji** [comment]
> @kamedodji I don't really understand why while `/bin/sh` pointing to `/bin/bash`, it doesn't work. 
> One thing you can try once entered in the container is :
It's due to bellow functionality of `bash` :
```
If you have /bin/sh as a link to bash, then bash will not behave the same when called as /bin/sh as 
it does when called as /bin/bash. When called as sh, it will limit itself to mostly POSIX-compliance 
plus a limited set of extensions.
```
Look for `Invoked with name sh` in https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html, for instance...
> 
> ```
> tmp=`mktemp` && sed 's/:\/bin\/sh/:\/bin\/bash/' /etc/passwd > $tmp && cat $tmp > /etc/passwd; rm $tmp
> ```
> 
> To check if solves issue
It's work fine. I discover that i can modify `/etc/passwd` as unprivileged user. Cool ;-) !

**Comment by cclerget** [comment]
@kamedodji Thanks for the clarification. For information using a recent release of Singularity like 3.5.X  should fix your issue as shell part is copied from host user database and not forced to `/bin/sh` anymore.

**Comment by kamedodji** [comment]
> @kamedodji Thanks for the clarification. For information using a recent release of Singularity like 3.5.X should fix your issue as shell part is copied from host user database and not forced to `/bin/sh` anymore.

Ah perfect. It's a really a good news...

**Comment by kamedodji** [comment]
> @kamedodji - you can force the shell on a `singularity shell` command with the `-s` option...
> 
> ```
> singularity shell -s /bin/bash
> ```
> 
> Also, you could create a `%runscript` in your container which does an `exec` of `/bin/bash` and then `singularity run` would drop you into `/bin/bash` too.

Yep @dctrud , it's what i do. But the issue is later when i raised `salloc` command which issue another shell, user one by default...
Thanks a lot for your help

**Comment by dtrudg** [comment]
@kamedodji - you can also do `salloc /bin/bash` or set `SallocDefaultCommand` in the `slurm.conf` in the container (if you are running slurm from an install in your container).

> The command may be any program the user wishes. Some typical commands are xterm, a shell script containing srun commands, and srun (see the EXAMPLES section). If no command is specified, then the value of SallocDefaultCommand in slurm.conf is used. If SallocDefaultCommand is not set, then salloc runs the user's default shell.

**Comment by kamedodji** [comment]
> @kamedodji - you can also do `salloc /bin/bash` or set `SallocDefaultCommand` in the `slurm.conf` in the container (if you are running slurm from an install in your container).
> 
> > The command may be any program the user wishes. Some typical commands are xterm, a shell script containing srun commands, and srun (see the EXAMPLES section). If no command is specified, then the value of SallocDefaultCommand in slurm.conf is used. If SallocDefaultCommand is not set, then salloc runs the user's default shell.

right @dctrud , but we want to keep the same configuration than the physical host.

So, the workaround of @cclerget work fine for me and i'll planned to migrate to `3.5.x`...
