### ISSUE TITLE
Support ENTRYPOINT exec form?

### ISSUE THREAD

**Issue by hisplan** [apptainer/singularity#499]
Hi,

I'm using `singularity import xyz.img docker://abc` to convert a Docker image into a Singularity image. I'm wondering if Docker's *ENTRYPOINT exec form* is supported (e.g. `ENTRYPOINT ["python", "test.py"]`)

**Comment by vsoch** [comment]
The entrypoint is parsed by default, and only CMD is used if you add the argument to IncludeCmd: yes. With the current implementation there may be an issue with having the ENTRYPOINT or CMD represented as a string - as a workaround you might want to do:

        ENTRYPOINT /usr/bin/python test.py

in the Dockerfile, or instead just override it in the Singularity runscript section:

```bash
Bootstrap: docker
From: myrepo/image

%runscript
   exec /usr/local/bin/python /path/to/test.py "$@"
```

In the soon-coming 2.3 release, this issue with parsing the list of commands will be fixed. Also note that I have included full paths to the executable (python) and script test.py. Singularity doesn't have the same understanding of the WORKDIR like Docker, so it doesn't assume that wherever the docker image left off with WORKDIR will be the present working directory when you call the container.

**Comment by hisplan** [comment]
Could you please clarify this again?

> there may be an issue with having the ENTRYPOINT or CMD represented as a string.

String or JSON array?

**Comment by gmkurtzer** [comment]
Hi @hisplan,

Yes. Docker's entrypoint (or CMD depending on which/or is defined) will be converted into the Singualrity runscript in the upcoming 2.3 version (currently in the 'development' branch).

However, it won't work with import but it will work with bootstrap. With the development branch, you can do the following as a bootstrap shortcut which will work as you expect:

```bash
$ sudo singularity bootstrap xyz.img docker://abc
```

If that answers your question and feature request, please let us know and close the issue.

Thanks!
Greg

**Comment by vsoch** [comment]
Hi @hisplan - I wanted to clarify that a Dockerfile can have an entrypoint / cmd that looks something like this:

      ["/bin/bash","entrypoint.sh"]

or like this:

      "/bin/bash entrypoint.sh"

and for Singularity 2.2, the first version might lead to a bug, but the second would work. For Singularity 2.3, both will work!

**Comment by vsoch** [comment]
So given that you are using 2.2, if you have an entrypoint that is akin to a list (the first of the above) my recommendation would be to define your functionality in the `%runscript` as I showed above.

**Comment by vsoch** [comment]
just testing this out - for the image I tested it looks like we have a bug that adds a newline given a list, eg:

```bash
Singularity tmp.img> cat /.singularity/runscript
#!/bin/sh

exec python
/code/pefinder/cli.py "$@"
```

Just looking into this - it appears that the function to read the config returns a newline:

```bash
In [5]: configs = get_configs(manifest,commands)
INFO:python:Found Docker command (Entrypoint) python
/code/pefinder/cli.py
INFO:python:Found Docker command (Cmd) None

In [6]: configs
Out[6]: {'Cmd': None, 'Entrypoint': u'python\n/code/pefinder/cli.py'}
```

and this is because, for some configs, it is preferable to separate by newline:

```bash
    # Standard is to include commands like ['/bin/sh']
    if isinstance(cmd,list):
        cmd = "\n".join(cmd)
    logger.info("Found Docker command (%s) %s",spec,cmd)
    return cmd
```

so the fix is to make the separator variable! It will return this:

```bash
configs
Out[13]: {'Cmd': None, 'Entrypoint': u'python /code/pefinder/cli.py'}
```

added to current PR!

**Comment by gmkurtzer** [comment]
Which PR?

**Comment by vsoch** [comment]
The one you merged a bit erarlier that had the optparse/argparse fix.

**Comment by gmkurtzer** [comment]
Ahh, cool! You rock! Is this issue closable then?

**Comment by vsoch** [comment]
yes this issue should be resolved and closable, unless @hisplan has anything to comment!

**Comment by gmkurtzer** [comment]
I will close. @hisplan, if you find any issues with it, please comment and I will reopen.

Thanks!

**Comment by hisplan** [comment]
Hi guys, I'm only using the stable version 2.2.1, is this fix already included in the official release or is this going to be included in >2.2.1?

**Comment by hisplan** [comment]
Also, is there a way to override entrypoint like in Docker by specifying `docker run --entrypoint`?

**Comment by vsoch** [comment]
The fix is in development branch. Entrypoint is used by default and you can specify a runscript section in your bootstrap file to overwrite it. Are you looking for more of a command line flag to specify a runscript command?

**Comment by hisplan** [comment]
Was looking for a command-line flag just like Docker's `--entrypoint`. I have two executables inside a container and I want to choose one at runtime. It would be great if I could do something like: `singularity run --entrypoint xyz tool.img`

**Comment by vsoch** [comment]
oh, if you want to do that, then you should use `exec` eg

```bash
singularity exec container.img /path/to/script.sh arg1
```

**Comment by hisplan** [comment]
I'm aware of the exec command, but my use case is I have a default main tool which is specified in %runscript, and I'd like to give users an option to override this. Correct me if I'm wrong, but I don't think exec let me do this.

**Comment by vsoch** [comment]
When you define the runscript, this sets the containers default behavior when you do:

```bash
singularity run mycontainer.img
```

This is the use case when you could define the bootstrap runscript to override Docker `ENTRYPOINT` and `CMD`. For your use case, you want to send a custom command to the container to run, at run time, and this is where you would want to use exec. Exec will let you override whatever is specified in runscript, and send whatever command you want to the container. So you can do whatever you like!

```bash
singularity exec container.img echo "Hello World!"
singularity exec container.img ls /
singularity exec container.img /usr/bin/python runme.py
```
If your use case is not met by the above, could you please give a specific example and I can help walk through the command?

**Comment by gmkurtzer** [comment]
You can also define in your %runscript what you want it to do via a shell `case` argument on `$1`.

**Comment by vsoch** [comment]
Yes, a runscript that handles a custom use case is another way to support a custom command to `singularity run` !

**Comment by hisplan** [comment]
I see. I thought `singularity exec` was more like `docker exec`, but I guess not.

**Comment by vsoch** [comment]
docker exec assumes a running container, singularity exec does not. I think that might be the main difference?

**Comment by hisplan** [comment]
I believe so. That's why I didn't even consider "singularity exec" and look for --entrypoint alike for "singularity run"

**Comment by vsoch** [comment]
ok, great! Does exec meet your need then? I'll be sure to be clear about this in the updated docs.

**Comment by hisplan** [comment]
I have a user-facing program that always calls "singularity run" for different images, so I'd have to see if I want to make an exception and use "singularirty exec" just for this image or keep using "singularity run" but use case statement inside %runscript. But one of them should work. Thanks!

**Comment by vsoch** [comment]
ok great! Please post again if you want to run anything by.
