### ISSUE TITLE
Singularity 3.5.x no longer logs actions

### ISSUE THREAD

**Issue by bne86** [apptainer/singularity#4992]
Hi,
this is a clone of #2267, because it gets no comment after 15 months of open-ness.

We plan do bring Singularity to our HPC clusters, but we would like to get information about who uses containers and which kind of images are used. With the Singularity 2 behaviour this would be perfectly fine, Singularity 3 seems to be a step back with respect to logging.

It would be great to get some feedback on whether this feature is on the list.

**Comment by cclerget** [comment]
Hi @bne86 , in the current master you could find a plugin example doing that :
https://github.com/sylabs/singularity/tree/master/examples/plugins/log-plugin

To test it from a fresh master :

```
singularity plugin compile examples/plugins/log-plugin
sudo singularity plugin install examples/plugins/log-plugin/log-plugin.sif
```

There is few reasons why it's better suited for integration as plugin and not in core :
- Singularity can be nested and may not be able to reach syslog socket
- Users doesn't need those logs
- Log customization

**Comment by bne86** [comment]
Hi @cclerget,
I can confirm that it works as expected, thank you very much for the pointer and the implementation!

**Comment by cclerget** [comment]
Closing, feel free to re-open if you have any questions
