### ISSUE TITLE
Different behavior when creating --writable container with 3.2.1 vs 3.5.2

### ISSUE THREAD

**Issue by touala** [apptainer/singularity#4995]
I'm trying to release a software through Singularity Hub and Docker Hub. I made all the development using an older Singularity version (3.2.1) but wanted to check the most recent version to make sure it would be compatible (3.5.2). However, my image don't behave the same way depending on the version. I have identify three issues:
1. I cannot create a writable container with 3.5.2 with the same image.
2. With 3.5.2, the CWD is trying to be mounted.
3. I end up with different environment variables (e.g. `PS1="${debian_chroot:+($debian_chroot)}\u@\h:\w\$"` with 3.2.1 vs `PS1=""` with 3.5.2.). I defined aliases and other environment variable within a `.bashrc` file in my `$HOME` but it's not read when the shell is started in the container with 3.5.2 but works with 3.2.1.

I found an issue with similar warning message for 3.5.2 and nvidia drivers but I'm not sure if they are related (https://github.com/sylabs/singularity/issues/4945).

### Version of Singularity:
I made all my development with 3.2.1 and trying to use the image with the newer 3.5.2.

### Expected behavior
It's not the exact image I work with but it reproduce the behavior.

```sh
singularity pull --name mycontainer_3.2.1.sif shub://touala/meme # 400MiB
singularity build --sandbox mycontainer_3.2.1 mycontainer_3.2.1.sif 
#INFO:    Starting build...
#INFO:    Creating sandbox directory...
#INFO:    Build complete: mycontainer_3.2.1
singularity shell --pwd /home/meme -e -s /bin/bash --writable mycontainer_3.2.1
# touala@host:~
```

### Actual behavior

```sh
singularity pull --name mycontainer_3.5.2.sif shub://touala/meme # 400MiB
singularity build --sandbox mycontainer_3.5.2 mycontainer_3.5.2.sif
#INFO:    Starting build...
#INFO:    Creating sandbox directory...
#INFO:    Build complete: mycontainer_3.5.2
singularity shell --pwd /home/meme -e -s /bin/bash --writable mycontainer_3.5.2
#WARNING: By using --writable, Singularity can't create /hpc destination automatically without overlay or underlay
#FATAL:   container creation failed: mount /hpc/packages/minerva-centos7/singularity/3.5.2/var/singularity/mnt/session/hpc->/hpc error: while mounting /hpc/packages/minerva-centos7/singularity/3.5.2/var/singularity/mnt/session/hpc: destination /hpc doesn't exist in container
```
I can avoid this issue with that but another warning appears and the environment issue is till here:
```sh
mkdir mycontainer_3.5.2/hpc
singularity shell --pwd /home/meme -e -s /bin/bash --writable mycontainer_3.5.2
#WARNING: Skipping mount /sc/orga/scratch/touala [cwd]: /sc/orga/scratch/touala doesn't exist in container
#Singularity>
```
And not using `--writable` also avoid the issue but the environment issue is till here::
```sh
singularity build mycontainer_3.5.2_default mycontainer_3.5.2.sif
#INFO:    Starting build...
#INFO:    Creating SIF file...
#INFO:    Build complete: mycontainer_3.5.2_default
singularity shell --pwd /home/meme -e -s /bin/bash mycontainer_3.5.2_default
```

### Steps to reproduce this behavior

See above examples.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
```sh
$ uname -srm
Linux 3.10.0-957.el7.x86_64 x86_64
```

### How did you install Singularity

It was install by our HPC staff, I would guess from source.

### Additional information
The configuration is similar for both version `singularity.conf`:
```
max loop devices = 128
allow setuid = yes
allow pid ns = no
config passwd = yes
config group = yes
config resolv_conf = yes
mount proc = yes
mount sys = yes
mount dev = yes
mount devpts = no
mount home = yes
mount tmp = yes
mount hostfs = no
#bind path = /etc/localtime
bind path = /etc/hosts
user bind control = yes
enable overlay = try
enable underlay = yes
mount slave = yes
sessiondir max size = 16
allow container squashfs = yes
allow container extfs = yes
allow container dir = yes
always use nv = no
root default capabilities = full
memory fs type = tmpfs
```
Execution with debugging enable (`-d`), [debug_result.txt](https://github.com/sylabs/singularity/files/4131733/debug_result.txt):
```sh
singularity -d shell -e -s /bin/bash -w mycontainer_3.5.2
```
This is the recipe I used in shub://touala/meme :
```sh
Bootstrap: docker
From: rocker/r-ver:3.5.3

%files
    postInstall /
    
%post
    # Install basic dependencies
    apt-get update && apt-get install -y --no-install-recommends \
    "vim" \
    "git" \
    "wget" \
    "bzip2" \
    "parallel" \
    "python" \
    "ghostscript" \
    "libcurl4-openssl-dev" \
    "libssl-dev" \
    "libxml2-dev" \
    "libxslt1-dev" \
    "zlib1g-dev" \
    "libncurses5-dev" \
    "libncursesw5-dev" \
    "libexpat1-dev" \
    "libjson-perl" \
    "libhtml-tree-perl" \
    "libbz2-dev" \
    "liblzma-dev" \
    "openmpi-bin" \
    "libopenmpi-dev" \
    "openssh-client" \
    "openssh-server" \
    "libibverbs-dev" \
    && rm -rf /var/lib/apt/lists/*

    mkdir /home/meme
    bash /postInstall

    # Define working directory
    cd /home/meme

    # Create folders for analysis
    mkdir /home/meme/analysis
    mkdir /home/meme/dataset

%environment
    export HOME=/home/meme
```

**Comment by cclerget** [comment]
Hi @touala , indeed with 3.2.1 when home directory destination (or a parent directory) is not present in container image, it's just silently ignored. In the meantime there was complains about Singularity not returning error about impossible bind in container and executing in container with unintended behavior.

Now based on your issue the flag `--no-home` is what you need to have the same behavior as with 3.2.1 and without having to create directory inside the image.

**Comment by touala** [comment]
Hello @cclerget, thank you very much for your rapid response. 

Adding `--no-home` resolve the fatal error but I still have inconsistency regarding the `.bashrc` file. For example, the aliases declared in the `.bashrc` are loaded but the prompt is not changes while `export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]meme:\[\033[33;1m\]\w\[\033[m\]$ "` is also in the `.bashrc`. See below (I updated the registry to create the `.bashrc`). Do you have an idea of what is the issue (it's working as I intend it with 3.2.1)?

Before:
```sh
singularity shell --pwd /home/meme -e -s /bin/bash --writable mycontainer_3.5.2
#WARNING: By using --writable, Singularity can't create /hpc destination automatically without overlay or underlay
#FATAL:   container creation failed: mount /hpc/packages/minerva-centos7/singularity/3.5.2/var/singularity/mnt/session/hpc->/hpc error: while mounting /hpc/packages/minerva-centos7/singularity/3.5.2/var/singularity/mnt/session/hpc: destination /hpc doesn't exist in container
```

After:
```sh
singularity shell --pwd /home/meme --no-home -e -s /bin/bash --writable mycontainer_3.5.2
#WARNING: Skipping mount /sc/orga/scratch/touraa01 [cwd]: /sc/orga/scratch/touraa01 doesn't exist in container
#Singularity> 
source .bashrc
#touala@meme:~$
```

Content of .bashrc:
```sh
alias ls="ls --color=auto"
alias ll="ls -hla"
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]meme:\[\033[33;1m\]\w\[\033[m\]$ "
export OMPI_MCA_btl_base_warn_component_unused=0
```

**Comment by dtrudg** [comment]
Hi @touala - the prompt is forced, from PR https://github.com/sylabs/singularity/pull/4616

This is an intended behaviour, as with many standard host prompts it's not otherwise clear when you are in the container. https://github.com/sylabs/singularity/issues/2721

**Comment by touala** [comment]
Hello @dctrud & @cclerget. Thanks again for your response.

Is there a way to avoid the `[cwd]` warning?

Regarding the prompt, I found the solution proposed by @GodloveD in https://github.com/sylabs/singularity/issues/2721#issuecomment-481842703 more appealing than the current one. Overwriting the prompt defined by the image's creator make the `shell` feature less practical, especially because the current path isn't in the forced prompt. Are there other elements entering in consideration for your decision that I missed? I think that having a non-default option to remove the forced prompt (BTW `-s /bin/bash` is already needed for the `.bashrc` to be read) or lightly altering the prompt defined by the creator (e.g. from `Singularity> ` to `S>touala@meme:~$ ` or as with 3.2.1 `Singularity mycontainer_3.2.1:/>`) or even a message in terminal (e.g. `Starting...`) would be better when using `shell`. But I see the concern when using `run` which behavior can be different between images.

Thanks again for your help.

**Comment by cclerget** [comment]
> Is there a way to avoid the [cwd] warning?

You can use `-s` before command : `singularity -s shell ...`

> Overwriting the prompt defined by the image's creator make the shell feature less practical, especially because the current path isn't in the forced prompt

You can perfectly provide your own prompt and force bash for `shell` command if that's really what you want, so your definition file will look like :

```
Bootstrap: docker
From: rocker/r-ver:3.5.3

%files
    postInstall /
    
%post
    # Install basic dependencies
    apt-get update && apt-get install -y --no-install-recommends \
    "vim" \
    "git" \
    "wget" \
    "bzip2" \
    "parallel" \
    "python" \
    "ghostscript" \
    "libcurl4-openssl-dev" \
    "libssl-dev" \
    "libxml2-dev" \
    "libxslt1-dev" \
    "zlib1g-dev" \
    "libncurses5-dev" \
    "libncursesw5-dev" \
    "libexpat1-dev" \
    "libjson-perl" \
    "libhtml-tree-perl" \
    "libbz2-dev" \
    "liblzma-dev" \
    "openmpi-bin" \
    "libopenmpi-dev" \
    "openssh-client" \
    "openssh-server" \
    "libibverbs-dev" \
    && rm -rf /var/lib/apt/lists/*

    mkdir /home/meme
    bash /postInstall

    # Define working directory
    cd /home/meme

    # Create folders for analysis
    mkdir /home/meme/analysis
    mkdir /home/meme/dataset

    cat > /.singularity.d/env/99-custom.sh <<EOF
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]meme:\[\033[33;1m\]\w\[\033[m\]$ "
SINGULARITY_SHELL=/bin/bash
EOF

%environment
    export HOME=/home/meme
```

Note that `/.singularity.d/env/99-custom.sh` must come after `99-base.sh` by alphabetical order because `99-base.sh` also force prompt to `Singularity>` and `SINGULARITY_SHELL=/bin/bash` will force to use `bash` for `shell` command.

**Comment by touala** [comment]
Thanks. I didn't realized that I could define default environmental variable this way. I suppose you would have mention it already but does `-s`, `--pwd /home/meme`, `--no-home` and `-e` could also be defined by default in the definition file? Maybe with `SINGULARITY_PWD` `SINGULARITY_NO_HOME`, and `SINGULARITY_CLEANENV`?

I already found that I can avoid using `SINGULARITY_SHELL=/bin/bash` and `--pwd /home/meme` by running `singularity run --no-home -w mycontainer_3.5.2` with this in the definition file:
```sh
%runscript
    cd /home/meme
    exec /bin/bash
```
Can other option be avoided too?

**Comment by cclerget** [comment]
> Can other option be avoided too?

No it works only with `SINGULARITY_SHELL` others are handled before that the container script is executed.

If you want to clear environment you can always execute in the runscript :

`exec env -i PS1=${PS1} /bin/bash`

**Comment by touala** [comment]
Thanks again for all those tips and tricks.
