### ISSUE TITLE
Sylabs Cloud commands to sign container wrong

### ISSUE THREAD

**Issue by mbhall88** [apptainer/singularity#4996]
### Version of Singularity:

```
$ singularity version
3.5.2
```

### Expected behaviour

Whilst on the sylabs website I clicked the button on one of my new containers to sign it. It popped up a screen that shows the commands to run from the command line in order to do this. However, the pull and push commands are incorrect. 

The pull command shown on the website is

```sh
singularity pull library://mbhall88/default/guppy-cpu:3.4.5 guppy-cpu3.4.5.sif 
```
However, the docs show that the container name has to come _before_ the URI

```sh
$ singularity pull --help
<snip>
Usage:
  singularity pull [pull options...] [output file] <URI>
<snip>
```

Therefore, the correct command would be

```sh
singularity pull guppy-cpu3.4.5.sif  library://mbhall88/default/guppy-cpu:3.4.5
```

The push command shown on the website is

```sh
singularity push guppy-cpu3.4.5.sif --library library://mbhall88/default/guppy-cpu:3.4.5
```

However, the `--library` flag must come before the container and contain a string to a library registry (which is sylabs by default anyway). It seems the `--library` flag is not even needed here.

```
$ singularity pull --help
<snip>
Usage:
  singularity push [push options...] <image> <URI>

Description:
  The 'push' command allows you to upload a SIF container to a given
  URI.  Supported URIs include:

  library:
      library://user/collection/container[:tag]

  oras:
      oras://registry/namespace/repo:tag


  NOTE: It's always good practice to sign your containers before
  pushing them to the library. An auth token is required to push to the library,
  so you may need to configure it first with 'singularity remote'.

Options:
  -U, --allow-unsigned   do not require a signed container
  -h, --help             help for push
      --library string   the library to push to (default
                         "https://library.sylabs.io")
<snip>
```

The correct command would be

```sh
singularity push guppy-cpu3.4.5.sif library://mbhall88/default/guppy-cpu:3.4.5
```

### How did you install Singularity

Source

**Comment by dtrudg** [comment]
@mbhall88 - these issues will be addressed soon. We are in the midst of going through and fixing these inconsistencies on the cloud site.

**Comment by dtrudg** [comment]
Closing - this will be fixed via an update to the cloud site.

Also please note that following the move of Singularity to hpcng, Sylabs product issues should be reported to support@sylabs.io
