### ISSUE TITLE
Mount does not change directory to the directory mounted

### ISSUE THREAD

**Issue by remyd1** [apptainer/singularity#500]
Hi,

This is not really a bug, nor a true feature request, but I do not think it is normal.

When using `singularity mount`, the prompt is changing, but you are still in your previous directory.

```bash
[root@cluster ~]# singularity mount ~remy/singularity_images/blast_apt.img                                      
Mounted image '/home/remy/singularity_images/blast_apt.img' into '/var/lib/singularity/mnt/final'
Starting /bin/sh... To unmount, exit this shell.
/home/remy/singularity_images/blast_apt.img:/var/lib/singularity/mnt/final> pwd
/root
/home/remy/singularity_images/blast_apt.img:/var/lib/singularity/mnt/final> cd /var/lib/singularity/mnt/final
/home/remy/singularity_images/blast_apt.img:/var/lib/singularity/mnt/final> vim environment 
```

The prompt indicates `/var/lib/singularity/mnt/final` as the current working directory, but in fact, we are in the directory from where we launched the `mount` command.

This is the same behaviour as the `shell` sub-command, but for mount, and considering the prompt value, I think it would be normal to change directory into the newly mounted directory, that is to say `/var/lib/singularity/mnt/final`.

Remy

**Comment by gmkurtzer** [comment]
In the 'development' branch, mount is handled in two different ways depending on if you are calling it as root, or as a non-privileged user.

If you call it as root, it no longer spawns a shell, but runs just like the mount(1) command. If you call it as a user, it will run the mount within the mount namespace, and thus will spawn a shell (and change the prompt):

```bash
$ singularity mount /tmp/test.img /mnt                                                                                                                                                                   
test.img is mounted at: /mnt

Spawning a new shell in this namespace, to unmount, exit shell
Singularity> pwd
/home/gmk/git/singularity/src
Singularity> ls /mnt
bin  dev  docker.def  environment  etc  home  lib  linuxrc  lost+found  media  mnt  proc  root  run  sbin  singularity  srv  sys  tmp  usr  var
Singularity> 
```

I can only do the chdir() when running as a user (as when calling it as root exits like the standard mount command does). Considering that, do you still want a call to chdir() when running as a user?

Thanks!

**Comment by remyd1** [comment]
Hi Greg,

Indeed, I think it would be more appropriate. Otherwise, the prompt should have a value which indicates the current directory.

Best regards,
Rémy

**Comment by gmkurtzer** [comment]
Hi @remyd1,

Notice in my snippet above... The prompt doesn't display a value showing where the mount is. It only changes to show that you are in Singularity.

Do you still feel we should do the chdir()? I am thinking that may violate the rule of least astonishment. Thoughts?

**Comment by vsoch** [comment]
I'm not sure if this is related, but I sometimes get weird functionality where I shell into an image, and the `$PWD` has a bunch of question mark looking things. I'll paste it here the next time I run into it.

**Comment by gmkurtzer** [comment]
😨

**Comment by gmkurtzer** [comment]
@remyd1 tag, your it!

**Comment by remyd1** [comment]
Hi @gmk,

Yes, I still think that the mount as single user should chdir() to the value indicated by the prompt, but you are the boss ;)

I think other opinions would be interesting for that proposal.

Best regards,
Rémy

**Comment by gmkurtzer** [comment]
@remyd1 Oh, I would agree with that, but if you notice above, the prompt shows no directory or mount point in the development branch anymore. Is your vote to still chdir()?

The other option, which I prefer, is to add the `\W` to the prompt, so instead it shows the current working directory. Thoughts?

**Comment by remyd1** [comment]
Hi @gmk. Ok for that 2nd option. ☺

Rémy

**Comment by gmkurtzer** [comment]
Done :)

```bash
$ singularity mount /tmp/test.img /mnt
test.img is mounted at: /mnt

Spawning a new shell in this namespace, to unmount, exit shell
Singularity: ~/git/singularity> 
```

**Comment by remyd1** [comment]
Thanks  ! :+1:
