### ISSUE TITLE
Instances don't share host ipc namespace

### ISSUE THREAD

**Issue by alanpeixinho** [apptainer/singularity#5000]
### Version of Singularity: 3.5.2

When creating a singularity instance and joining it

```
readlink /proc/*/task/*/ns/ipc | sort -u (outside container)
singularity instance start docker://ubuntu ubuntu 
singularity shell instance://ubuntu
singularityshel > readlink /proc/*/task/*/ns/ipc | sort -u (inside container)
```

The IPC shared memory differs from host.
Meanwhile, when i run a shell without an instance, the ipc is properly shared.
```
readlink /proc/*/task/*/ns/ipc | sort -u (outside container)
singularity shell docker://ubuntu
readlink /proc/*/task/*/ns/ipc | sort -u (inside container)
```
Here the ipc is the same.
Is it expected to have a different behaviour when using singularity instances?

### What OS/distro are you running

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"

### How did you install Singularity

Singularity built from source.

**Comment by cclerget** [comment]
Hi @alanpeixinho , this is expected as an instance creates its own IPC namespace so when you shell into the instance you join the instance IPC namespace, not the host one.

**Comment by dtrudg** [comment]
@cclerget - I'm going to suggest we have a `--help` bug here, as `--help` for `--instance` still lists the `-i / --ipc` option, suggesting that it doesn't happen by default.

**Comment by cclerget** [comment]
Right and also same for `--pid`

**Comment by alanpeixinho** [comment]
@cclerget  Thank you for clarifying, but is there an option to not isolate IPC when creating an instance?
