### ISSUE TITLE
Add a forced cleanup argument

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#501]
Is there a --force-cleanup or similar argument? I've a situation with a researcher who wants to run from thousands to millions of simulations using a Windows binary via WINE installed under Singularity for a binary-only tool that has no Linux equivalent. Unfortunately,  at the end of every run singularity produces the following error
ERROR  : Could not remove session directory /tmp/.singularity-session-10567.2575366.144116899955873505: Device or resource busy
/tmp/.singularity-session-10567.2575366.144116899955873505

That directory has 20kb worth of empty files and directories, which will not really scale to millions of runs. I think that some  wineserver processes are still lingering when the executable exits leading to a wedged SG namespace and the error. Since I know that the application has exited I'd be happy to tell singularity to kill everything in the namespace, unmount, and clean up the directories.

Singularity debug log doesn't appear to be very detailed in this regard.

DEBUG   [U=1005,P=26307]   sessiondir.c:118:singularity_sessiondir_init(): Cleanup thread waiting on child...
DEBUG   [U=1005,P=26307]   sessiondir.c:123:singularity_sessiondir_init(): Checking to see if we are the last process running in this sessiondir
VERBOSE [U=1005,P=26307]   sessiondir.c:125:singularity_sessiondir_init(): Cleaning sessiondir: /tmp/.singularity-session-1005.2575366.144116899955873505
DEBUG   [U=1005,P=26307]   util/file.c:267:s_rmdir()                  : Removing directory: /tmp/.singularity-session-1005.2575366.144116899955873505
ERROR   [U=1005,P=26307]   sessiondir.c:127:singularity_sessiondir_init(): Could not remove session directory /tmp/.singularity-session-1005.2575366.144116899955873505: Device or resource busy

The home directory is NFS-mounted. That's one of the remaining artifacts afaiks:

$ find /tmp/.singularity-session-1005.2575366.144116899955873505
/tmp/.singularity-session-1005.2575366.144116899955873505
/tmp/.singularity-session-1005.2575366.144116899955873505/home
/tmp/.singularity-session-1005.2575366.144116899955873505/home/me
/tmp/.singularity-session-1005.2575366.144116899955873505/passwd
/tmp/.singularity-session-1005.2575366.144116899955873505/image_loop_dev
/tmp/.singularity-session-1005.2575366.144116899955873505/group

**Comment by bbockelm** [comment]
I'm not sure what the `--force` option would do - Linux is not allowing singularity to delete these files.

Is it possible to move the session dir to `/dev/shm`?  Maybe move `/tmp` to `/tmpfs`?

**Comment by moskalenko** [comment]
I wonder if singularity keeps a process table and can SIGKILL all processes in the container namespace before the directory cleanup to avoid the above situation.

**Comment by gmkurtzer** [comment]
Hi @moskalenko,

I can't do any more of a force then I am already doing without privileged escalation. Unfortunately, I don't see a clear fix for this until after 2.3 is released and we have the equiv of an 'init' process running within a PID namespace.

Greg
