### ISSUE TITLE
Set SINGULARITY_ENVIRONMENT at least when entering shell

### ISSUE THREAD

**Issue by robertlugg** [apptainer/singularity#5017]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.3.0-1
```
### Expected behavior

I want to incrementally build a container by first building in a sandbox, then entering shell of the sandbox, and finally "cut-and-paste" from my recipe directly in the command line to get things working properly.  The problem is `SINGULARITY_ENVIRONMENT` isn't defined so I can't do something like:
```
NOW=`date`
echo "export NOW=\"${NOW}\"" >> $SINGULARITY_ENVIRONMENT
```

### Actual behavior

SINGULARITY_ENVIRONMENT isn't set when running in 'shell'

### What OS/distro are you running

```
$ cat /etc/redhat-release 
CentOS release 6.10 (Final)

```

### How did you install Singularity
from source.

**Comment by cclerget** [comment]
@robertlugg Will be probably fixed in next 3.6.0 release

**Comment by cclerget** [comment]
@robertlugg Just thinking that you can provide it yourself by adding in `%post` section:

```
%post
    echo "export SINGULARITY_ENVIRONMENT=$SINGULARITY_ENVIRONMENT" >> $SINGULARITY_ENVIRONMENT
```

**Comment by robertlugg** [comment]
That's a good point.  making it a default behavior would be a nice-to-have.
