### ISSUE TITLE
MAC OSX Beta Version Fails to run image

### ISSUE THREAD

**Issue by tvern23** [apptainer/singularity#5026]
### Version of Singularity:

What version of Singularity are you using?

```
3.3.0-rc.1.658.g7427b73f1.dirty

```

When go to run or shell a singularity container, build on a Linux system and runs fine on multiple linux distros and singularity versions

singularity shell mycontainger.simg

FATAL:   container creation failed: mount /proc/self/fd/3->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount ext3 filesystem: invalid argument
[    4.104213] reboot: Power down

same thing with "run" instead of "shell"

Container was built locally from recipe on a linux machine. 

### What OS/distro are you running

MAC OSX 10.13.6

### How did you install Singularity

Using the .dmg for the Mac osx beta

**Comment by dtrudg** [comment]
Closing as Singularity Desktop currently not maintained.
