### ISSUE TITLE
Exporting a --sandbox container

### ISSUE THREAD

**Issue by NikosDelijohn** [apptainer/singularity#5029]
### Version of Singularity: 3.5.2

Is it possible to export a --sandbox container to another machine? If so, how? I can move an non-sandbox image to another machine but the thing is that I wish for a writable file system.

**Comment by dtrudg** [comment]
A sandbox container is just a directory. You can copy it to another machine using `scp` `rsync` or similar.

A non-sandbox image (SIF file) is a single file. You can copy that single file to any other machine but it is not writable. To have a writable filesystem when using a SIF file container you need to use `--writable-tmpfs` if you *do not* want changes to be saved, or setup a 'persistent overlay' if you *do* want changes to be saved:

https://sylabs.io/guides/3.5/user-guide/persistent_overlays.html
