### ISSUE TITLE
Can't run singularity on OS X

### ISSUE THREAD

**Issue by poquirion** [apptainer/singularity#5030]
Running any shell, exec, or run command will return, but nothing happens. No error, noting...

```
$ singularity -v shell docker://alpine
$ # I am not in the container...
```
I tried it on a variety of images (local .sif and dockerhub) with the same results.

I am wondering if my OS X version is not just to old.

### Version of Singularity:

3.3.0-rc.1.658.g7427b73f1.dirty

### What OS/distro are you running

OS X Yosemite
10.10.5
```
$ uname -a 
Darwin MacBook-Air-de-Calcul.local 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64
```

### How did you install Singularity

Installed the released .pkg from github

**Comment by dtrudg** [comment]
10.10 is quite old I'm afraid. As this is not a supported version of OS X it's not something we can really look into. If you run `singularity -d shell ....` the `-d` option may give further hint.

**Comment by poquirion** [comment]
here is what I got: 
```
[...]
DEBUG   [U=505,P=78042]    startVM()                     About to launch VM using: [/usr/local/libexec/singularity/vm/xhyve -A -m 1024 -c 1 -s 0:0,hostbridge -s 31,lpc -l com1,stdio -s 3,virtio-net -s 4:0,virtio-9p,home=/Users/poq -s 2:0,ahci-hd,/Users/poq/.singularity/cache/oci-tmp/ab00606a42621fb68f2ed6ad3c88be54397f981a7b70a79db3d1172b11c4367d/alpine_latest.sif -f kexec,/usr/local/libexec//singularity/vm/syos-kernel-amd64,/usr/local/libexec//singularity/vm/initramfs_amd64.gz,console=ttyS0 quiet root=/dev/ram0 loglevel=0 sing_img_name=alpine_latest.sif sing_user=poq:505:20 sing_cwd=/Users/poq singularity_action=exec ipv4=dhcp msglvl=5 singularity_arguments="ls" singularity_binds="|home:/Users/poq"]
dyld: lazy symbol binding failed: Symbol not found: _os_unfair_lock_lock
  Referenced from: /usr/local/libexec/singularity/vm/xhyve
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _os_unfair_lock_lock
  Referenced from: /usr/local/libexec/singularity/vm/xhyve
  Expected in: /usr/lib/libSystem.B.dylib

DEBUG   [U=505,P=78042]    startVM()                     Hypervisor exit code: signal: trace/BPT trap
DEBUG   [U=505,P=78042]    startVM()                     Process exited with non-zero return code: -1
```

**Comment by poquirion** [comment]
It seems that  _os_unfair_lock_lock was introduces in OS X sierra 10.12.

**Comment by dtrudg** [comment]
Yeah - I'm afraid this means `xhyve` hypervisor used by singularity on OSX is not supported by 10.10.

**Comment by poquirion** [comment]
it seems that xhyve can be compiles to work with older OS X versions (https://github.com/machyve/xhyve/issues/137). Is there a branch where I can try to compile singularity on my MAC and try to make it work?

**Comment by jmstover** [comment]
@poquirion The clone being used can be found here: https://github.com/sylabs/xhyve

It's based off of jceel/xhyve for the 9p support

-J

**Comment by poquirion** [comment]
I can make it work. Here is what I did.

Installed the the singularity v0.1 beta release with the help of the .dmg file

Compiled xhyve and copied it to where singularity expect it:
```
git clone https://github.com/sylabs/xhyve
cd xhyve
git submodule update --init --recursive
MACOSX_DEPLOYMENT_TARGET=10.10 make
sudo cp build/xhyve   /usr/local/libexec/singularity/vm/xhyve
```

Singularity now seems to be working without any problems.

**Comment by dtrudg** [comment]
@poquirion - understood - glad you got it working. This isn't something we will support ourselves as 10.10 is unsupported by Apple, and we don't have a way to test it.
