### ISSUE TITLE
Is there a way to start process mentioned in runscript or startscript with pid 1 during container stratup

### ISSUE THREAD

**Issue by asmi10** [apptainer/singularity#5032]
### Version of Singularity:

3.5.2

```
$ singularity version
3.5.2


### Expected behavior
I would like to start process mentioned in runscript or startscript with pid 1, is there a way I can achieve this during container startup? 

### Actual behavior

If I start singularity container with --no-init option it starts first process ( /bin/sh /.singularity.d/runscript ). If I use instance then first process with id 1 is sinit..

singularity run -B /sys/fs/cgroup:/sys/fs/cgroup --writable-tmpfs --pid --no-init --net --network macvlan centos2.sif centos -c "/bin/bash"
logger: socket /dev/log: Connection refused
Singularity> systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected architecture x86-64.
Unit tmp.mount is bound to inactive unit dev-sda10.device. Stopping, too.
systemd-journal-flush.service: main process exited, code=exited, status=1/FAILURE
Unit systemd-journal-flush.service entered failed state.
systemd-journal-flush.service failed.
systemd-update-utmp.service: main process exited, code=exited, status=1/FAILURE
Unit systemd-update-utmp.service entered failed state.
systemd-update-utmp.service failed.
Startup finished in 2month 4w 2d 7h 59min 1.204s (kernel) + 780ms (userspace) = 2month 4w 2d 7h 59min 1.985s.

Singularity> 
Singularity> ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.6  0.0 113200  2688 pts/0    S    15:21   0:00 /bin/sh /.singularity.d/runscript centos -c /bin/bash
root        15  6.8  0.0  43080  4832 ?        Ss   15:21   0:00 /usr/lib/systemd/systemd --system --unit=basic.target
root        16  0.0  0.0 115460  3388 pts/0    S    15:21   0:00 /bin/bash
root        30  0.6  0.0  39096  7060 ?        Ss   15:21   0:00 /usr/lib/systemd/systemd-journald
root        36  4.0  0.0  43084  3376 ?        Ss   15:21   0:00 /usr/lib/systemd/systemd-udevd
root      1096  0.0  0.0 155384  3836 pts/0    R+   15:21   0:00 ps aux




<!-- if this is a feature request, you can ignore this next part -->

### Steps to reproduce this behavior

How can others reproduce this issue/problem?


### What OS/distro are you running

```
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

**Comment by cclerget** [comment]
Hi @asmi10 , if you are specifying `--pid --no-init` there is probably something wrong in your runscript and it must contain `exec /sbin/init` instead of simply `/sbin/init`, using `exec` execute the command in place of the current process (with the same PID) while the second form spawn a child process and wait the execution finish.

There is also `singularity instance start --boot ...` which allow to start an instance by invoking `/sbin/init` directly and take care of adding few options to not conflict with host. But just figured out a bug https://github.com/sylabs/singularity/issues/5033, so it may not help you while not fixed.

**Comment by asmi10** [comment]
No, it doesn't work.. if I use "exec /sbin/init" then I get below mesg.
I also tried to run systemd directly: "exec /usr/lib/systemd/systemd --system --unit=basic.target &" but didn't get it running with pid 1.

singularity run -B /sys/fs/cgroup:/sys/fs/cgroup --writable-tmpfs --pid --no-init --net --network macvlan centos2.sif 
Singularity> Couldn't find an alternative telinit implementation to spawn.

Singularity> ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.6  0.0 113200  2688 pts/0    S    21:47   0:00 /bin/sh /.singularity.d/runscript
root        16  0.0  0.0 115460  3388 pts/0    S    21:47   0:00 /bin/bash
root        18  0.0  0.0 155384  3836 pts/0    R+   21:47   0:00 ps aux
Singularity> exit

**Comment by cclerget** [comment]
Could you give the definition file you used to build the image ?

**Comment by asmi10** [comment]
This one is with systemd
Bootstrap: localimage
From: /infrastructure/sng-img/centos.sif

%post
    yum -y update
    yum -y install net-tools iputils systemd openssh*

%files
    service.sh /service.sh


%runscript
    exec /usr/lib/systemd/systemd --system --unit=basic.target &
    /bin/bash

Below is the o/p if I run container.
Singularity> ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.6  0.0 113200  2688 pts/0    S    15:21   0:00 /bin/sh /.singularity.d/runscript centos -c /bin/bash
root        15  6.8  0.0  43080  4832 ?        Ss   15:21   0:00 /usr/lib/systemd/systemd --system --unit=basic.target
root        16  0.0  0.0 115460  3388 pts/0    S    15:21   0:00 /bin/bash
root        30  0.6  0.0  39096  7060 ?        Ss   15:21   0:00 /usr/lib/systemd/systemd-journald
root        36  4.0  0.0  43084  3376 ?        Ss   15:21   0:00 /usr/lib/systemd/systemd-udevd
root      1096  0.0  0.0 155384  3836 pts/0    R+   15:21   0:00 ps aux

**Comment by cclerget** [comment]
@asmi10 It can't work if you use `&` because you end by spawning a child process, just do :

```
%runscript
   exec /usr/lib/systemd/systemd --system --unit=basic.target
```

Now that the fix for instance started with `--boot` is merged in https://github.com/sylabs/singularity/releases/tag/v3.5.3-rc.1, I would recommend to give it a try with this release and use `instance start --boot` to make things easier for you, additionally you would be able to spawn a shell inside the instance instead of finding a way to spawn a shell like you did by running `/bin/bash` in runscript and screw up the start of systemd.

So you should be able to start systemd and access instance with :

```
sudo singularity instance start --boot --writable-tmpfs --net --network macvlan centos.sif systemd
sudo singularity shell instance://systemd
```

**Comment by cclerget** [comment]
@asmi10 Can we close it ?

**Comment by dtrudg** [comment]
Closing as there has been no follow up.
