### ISSUE TITLE
ERROR: 'Bootstrap' type not supported: docker

### ISSUE THREAD

**Issue by ianferreira** [apptainer/singularity#5036]
Version: 2.5.2
Platform: 
Linux JetsonCluster4 4.9.140-tegra #1 SMP PREEMPT Mon Dec 9 22:47:42 PST 2019 aarch64 aarch64 aarch64 GNU/Linux

def recipe:
BootStrap: docker
From: busybox:latest   # This is a comment

%runscript
    echo "This is what happens when you run the container..."

%post
    echo "Hello from inside the container"
    echo "Install additional software here"

Command:
singularity build armhf.sif demo.def

Error:
Using container recipe deffile: /nfs_share/demo.def
Sanitizing environment
Adding base Singularity environment to container
ERROR: 'Bootstrap' type not supported: docker
Cleaning up...

**Comment by cclerget** [comment]
Hi @ianferreira , first guess would be to try with header like :

```
Bootstrap: docker
From: arm64v8/busybox
```

I don't remember if v2 support architecture detection when bootstrapping from docker.
I would also suggest to use v3 release instead which support this transparently as v2 doesn't receive any fixes/support.

**Comment by ianferreira** [comment]
@cclerget  yes sorry I tried arm images also. For some reason it can't get past the bootstrap error. Will try 3.x
Btw, do you have updated installation instructions? I tried building but seem to be missing files referenced in the example. Thanks!

**Comment by dtrudg** [comment]
There is an `INSTALL.md` file in the repository, and detailed installation instructions are also found in our documentation at: https://sylabs.io/guides/3.5/admin-guide/installation.html
