### ISSUE TITLE
[bootstrap] needed additions

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#504]
For version 2.3, we should add the following sections to the bootstrap build file:

## environment
Right now, the user has to do some hacks to have variables exported to the environment. We see this in `%post`:

      echo "export BLAH=BLOOP" >> /environment

With the new metadata folder at `/.singularity/env` and the expectation to write user bootstrap environment to `/.singularity/env/99-bootstrap.sh` we want to make this section as easy as the following:

      %environment
      export BLAH=BLOOP
      
Is it meaningful that the user could choose to export or not export?
  
## files
Right now, getting files into a container means cloning a github repo, or having to copy them from the host in `%setup` to `SINGULARITY_ROOTFS`.  Whaaaaat! This is pretty bad usability. Instead, we should have a `%files`section that handles this elegantly. If the path doesn't exist, we mkdir -p it for them. I will provide several examples. 

    %files

    # 1. For these top two, the file should be copied to the folder with the same name
    /home/vanessa/furbies.o /usr/local/lib
    /home/vanessa/furbies.o /usr/local/lib/

    # 2. The file is copied and renamed
    /home/vanessa/furbies.o /usr/local/lib/furbylib.o

    # 3. All files are copied, with same functionality as 1. (eg, --force or not)
   /home/vanessa/* /usr/local/lib
   /home/vanessa/* /usr/local/lib/

Given that a path already exists, we give a warning and skip it, or allow the user to force a copy. Given existence, we also need to check for if something is a folder vs. a file. If we don't do this, we can't be sure if a user wants to write a file called "lib" or put "furbies.o" into the folder lib. So here is the logic:

 - Check if the "to" path exists. 
     - case 1: the path exists, and it's a folder. Check if the equivalently named file exists in the folder. If it doesn't, copy into folder. if it does, issue a warning and don't copy. We may want to allow the user to issue some kind of --force argument after the file, in the case that they do want to overwrite what is there.
     - case 2: the path exists, and it's a file.  Issue the same warning and default to skip, or check for --force.
     - case 3: the path does not exist. We assume the user wants a file, and we copy the file.

For 3., given a * to indicate some kind of regular expression, the TO location MUST be a folder.

## labels
Right now, we finally have support for metadata in our `/.singularity/labels` folder! (my dreams are all coming true!) Thus, we would want something similar, like:

      %labels
      MAINTAINER vsochat@stanford.edu
      VERSION 1.0

and I don't think we've talked about this yet, but it should be a key/value sort of deal. Right now we are writing metadata as txt or json files (I think?) to the labels folder, and we should chat about if some more key --> value data structure would work better to be more easily maintainable for distinct things.

**Comment by gmkurtzer** [comment]
This should be done now. Closing. But let me know if it needs reopening!

Thanks!
