### ISSUE TITLE
Advice for `rsync`ing sandbox directory?

### ISSUE THREAD

**Issue by vitchyr** [apptainer/singularity#5051]
Is there a recommended way to rsync the sandbox directories to another server? I notice that there are a number of skipped non-regular files and permission denied errors. Interestingly, I seem to be able to run my jobs without these missing files.

I know this might not be very specific to singularity, but I figured I'd ask in case this becomes a problem down the line for me or anyone else.

Thank you!

### Version of Singularity:

```
$ singularity version
3.5.3
```

### Expected behavior
Can easily `rsync` directory with `-ar` option.

### Actual behavior

When trying to run `rsync -arv singularity_directory user@host:path` I get a bunch of errors like so:
```
skipping non-regular file "dev/tty1"
skipping non-regular file "dev/tty2"
skipping non-regular file "dev/tty3"
skipping non-regular file "dev/tty4"
skipping non-regular file "dev/tty5"
skipping non-regular file "dev/tty6"
skipping non-regular file "dev/tty7"
```
as well as a number of permission errors
```
rsync: send_files failed to open "/singularity_directory/var/log/btmp": Permission denied (13)
```

### Steps to reproduce this behavior

Try rsyncing a generated sandbox directory.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

### How did you install Singularity
Source

**Comment by cclerget** [comment]
Hi @vitchyr , if you try to sync a sandbox which wasn't created by you or created by the root user, expect those errors, if you are not the owner or user (for devices) use the exclude options like :

`rsync -arv --no-perms --no-devices ...`

I'm going to close the issue as not related to Singularity
