### ISSUE TITLE
symlink behavior of multi-stage builds

### ISSUE THREAD

**Issue by samcmill** [apptainer/singularity#5059]
### Version of Singularity:

3.5.3

### Expected behavior

A common use case for commercial software is to allow a subset of the software to be redistributed.  A `REDIST` directory that collects the redistributable software is typical.

```
bootstrap: library
from: alpine
stage: one

%post
    mkdir -p /usr/local/mypackage/lib /usr/local/mypackage/REDIST
    touch /usr/local/mypackage/lib/libmine.so.1
    ln -s ../lib/libmine.so.1 /usr/local/mypackage/REDIST/libmine.so.1

bootstrap: library
from: alpine
stage: two

%files from one
    /usr/local/mypackage/REDIST /usr/local/mypackage/lib
```

The desired behavior would be for `/usr/local/mypackage/lib/libmine.so.1` to be a valid file in the final image.

### Actual behavior

When built using 3.5.3:
```
$ singularity exec example.sif ls -l /usr/local/mypackage/lib
total 1
lrwxrwxrwx    1 root     root            19 Feb 25 10:51 libmine.so.1 -> ../lib/libmine.so.1
```

The symlink does not resolve to a valid file.

When built using 3.2.1:
```
root@f89f5c110111:/# singularity exec example.sif ls -l /usr/local/mypackage/lib
total 1
-rw-rw-r--    1 root     root             0 Feb 25 16:53 libmine.so.1
```

The behavior was changed by #4873 in response to #4583.  

Can a flag or option be added to control the symlink follow behavior when building multi-stage images?

**Comment by dtrudg** [comment]
We did have a bit of discussion around symlinks with libraries - and one of the major reasons to change to copying the symlink as-is in multi-stage builds was that commonly with libraries you want to have a single versioned `.so` with links to it, and not duplicate the library many times by resolving the link when copying lib directories into a later stage:

```
lrwxrwxrwx. 1 root root   15 Dec 10 23:17 libX11.so.6 -> libX11.so.6.3.0*
-rwxr-xr-x. 1 root root 1.3M Dec 10 23:17 libX11.so.6.3.0*
```

In the case of a `REDIST` where relative symlinks are going to be relocated in the final stage, I'd personally prefer that was written into the recipe by a `cp` that follows symlinks with `-L` or similar. I don't think it should be an option to the `singularity build` command as then a successful build is dependent on options as well as the recipe file.

@ikaneshiro and @alalazo might want to comment here though - it's something we could certainly expose as the copying function takes a boolean to control behavior. I'm just concerned about how to avoid making builds less reproducible with options or adding complexity to the `%from` line.

It would help if you can provide some explicit examples of software / recipes that do this - so we can consider the impact of putting a workaround in the recipe, vs adding to Singularity.

Thanks!

**Comment by dtrudg** [comment]
To clarify my `cp -L` comment... this would give a recipe something like...

```
bootstrap: library
from: alpine
stage: one

%post
    mkdir -p /usr/local/mypackage/lib /usr/local/mypackage/REDIST
    touch /usr/local/mypackage/lib/libmine.so.1
    ln -s ../lib/libmine.so.1 /usr/local/mypackage/REDIST/libmine.so.1
   
    # create resolved REDIST by following links
    cp -RL /usr/local/mypackage/REDIST /usr/local/mypackage/RRDIST

bootstrap: library
from: alpine
stage: two

%files from one
    /usr/local/mypackage/RREDIST /usr/local/mypackage/lib
```

**Comment by samcmill** [comment]
The `cp -L` "trick" won't work for my [use case](https://github.com/NVIDIA/hpc-container-maker).  A user recipe may or may not be multi-stage and I don't think it's wise to always resolve the symlinks in the first stage if there is no second stage.

I believe there are 2 valid use cases, one where the symlinks are not resolved and one where they are.  Unfortunately the change in #4873 switched the default behavior without including a method to obtain the previous default behavior.  Worse, it has created a situation where multi-stage container builds are inconsistent (and broken) depending on the version of Singularity used.

**Comment by dtrudg** [comment]
Hello,

> The `cp -L` "trick" won't work for my [use case](https://github.com/NVIDIA/hpc-container-maker). A user recipe may or may not be multi-stage and I don't think it's wise to always resolve the symlinks in the first stage if there is no second stage.

Please could you provide an example of a specific piece of software that is creating a `REDIST` like this, and preferably an example of the definition file that is output by the container maker which will then be built with Singularity?

If I understand correctly the container maker produces Docker or Singularity output. If I use an equivalent multi-stage `Dockerfile` to the singularity def we are considering...

```
FROM alpine:latest
RUN mkdir -p /usr/local/mypackage/lib /usr/local/mypackage/REDIST && \
    touch /usr/local/mypackage/lib/libmine.so.1 && \
    ln -s ../lib/libmine.so.1 /usr/local/mypackage/REDIST/libmine.so.1

FROM alpine:latest
COPY --from=0 /usr/local/mypackage/REDIST /usr/local/mypackage/lib
```

Then it appears Docker will copy the symlink like Singularity now does, leaving a broken relative link:

```
dtrudg@dt-sylabs~/G/multi> docker run -it test:latest
/ # cd /usr/local/mypackage/lib/
/usr/local/mypackage/lib # ls
libmine.so.1
/usr/local/mypackage/lib # ls -lah
total 8K
drwxr-xr-x    2 root     root        4.0K Feb 25 22:29 .
drwxr-xr-x    3 root     root        4.0K Feb 25 22:29 ..
lrwxrwxrwx    1 root     root          19 Feb 25 22:29 libmine.so.1 -> ../lib/libmine.so.1
```

Is this something you handle in a different way for Docker? I'd like to understand a little bit more about the use-case here before we decide on how/if to expose an option.

> I believe there are 2 valid use cases, one where the symlinks are not resolved and one where they are. Unfortunately the change in #4873 switched the default behavior without including a method to obtain the previous default behavior. Worse, it has created a situation where multi-stage container builds are inconsistent (and broken) depending on the version of Singularity used.

Certainly the behavior was changed, but this was done to fix a situation for some other container builders (e.g. Spack) where multi-stage container builds were previously broken, and issues with duplication of library files that should be symlinked etc. It's regrettable to have to change behavior but it was called out in the release notes, and we were genuinely unaware of how multi-stage build may depend on resolving links, especially given the Docker behavior which would generally be expected.

**Comment by samcmill** [comment]
The PGI compiler is an example that demonstrates this use case (see below for a Singularity definition file).

In Docker one can use the following to resolve the symlink:
```
COPY --from=0 /usr/local/mypackage/REDIST/*.so* /usr/local/mypackage/lib/
```

```
# NOTE: this definition file depends on features only available in
# Singularity 3.2 and later.
BootStrap: docker
From: ubuntu:16.04
Stage: build
%post
    . /.singularity.d/env/10-docker*.sh

# PGI compiler version 19.10
%post
    apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        g++ \
        gcc \
        libnuma1 \
        perl \
        wget
    rm -rf /var/lib/apt/lists/*
%post
    cd /
    mkdir -p /var/tmp && wget -q -nc --no-check-certificate -O /var/tmp/pgi-community-linux-x64-latest.tar.gz --referer https://www.pgroup.com/products/community.htm?utm_source=hpccm\&utm_medium=wgt\&utm_campaign=CE\&nvid=nv-int-14-39155 -P /var/tmp https://www.pgroup.com/support/downloader.php?file=pgi-community-linux-x64
    mkdir -p /var/tmp/pgi && tar -x -f /var/tmp/pgi-community-linux-x64-latest.tar.gz -C /var/tmp/pgi -z
    cd /var/tmp/pgi && PGI_ACCEPT_EULA=accept PGI_INSTALL_DIR=/opt/pgi PGI_INSTALL_MPI=false PGI_INSTALL_NVIDIA=true PGI_MPI_GPU_SUPPORT=false PGI_SILENT=true ./install
    echo "variable LIBRARY_PATH is environment(LIBRARY_PATH);" >> /opt/pgi/linux86-64/19.10/bin/siterc
    echo "variable library_path is default(\$if(\$LIBRARY_PATH,\$foreach(ll,\$replace(\$LIBRARY_PATH,":",), -L\$ll)));" >> /opt/pgi/linux86-64/19.10/bin/siterc
    echo "append LDLIBARGS=\$library_path;" >> /opt/pgi/linux86-64/19.10/bin/siterc
    ln -sf /usr/lib/x86_64-linux-gnu/libnuma.so.1 /opt/pgi/linux86-64/19.10/lib/libnuma.so
    ln -sf /usr/lib/x86_64-linux-gnu/libnuma.so.1 /opt/pgi/linux86-64/19.10/lib/libnuma.so.1
    rm -rf /var/tmp/pgi-community-linux-x64-latest.tar.gz /var/tmp/pgi
%environment
    export LD_LIBRARY_PATH=/opt/pgi/linux86-64/19.10/lib:$LD_LIBRARY_PATH
    export PATH=/opt/pgi/linux86-64/19.10/bin:$PATH
%post
    export LD_LIBRARY_PATH=/opt/pgi/linux86-64/19.10/lib:$LD_LIBRARY_PATH
    export PATH=/opt/pgi/linux86-64/19.10/bin:$PATH

BootStrap: docker
From: ubuntu:16.04
%post
    . /.singularity.d/env/10-docker*.sh

# PGI compiler
%post
    apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libnuma1
    rm -rf /var/lib/apt/lists/*
%files from build
    /opt/pgi/linux86-64-llvm/19.10/REDIST/*.so* /opt/pgi/linux86-64/19.10/lib/
%post
    cd /
    ln -sf /usr/lib/x86_64-linux-gnu/libnuma.so.1 /opt/pgi/linux86-64/19.10/lib/libnuma.so
    ln -sf /usr/lib/x86_64-linux-gnu/libnuma.so.1 /opt/pgi/linux86-64/19.10/lib/libnuma.so.1
%environment
    export LD_LIBRARY_PATH=/opt/pgi/linux86-64/19.10/lib:$LD_LIBRARY_PATH
%post
    export LD_LIBRARY_PATH=/opt/pgi/linux86-64/19.10/lib:$LD_LIBRARY_PATH
```

**Comment by dtrudg** [comment]
> The PGI compiler is an example that demonstrates this use case (see below for a Singularity definition file).
> 
> In Docker one can use the following to resolve the symlink:
> 
> ```
> COPY --from=0 /usr/local/mypackage/REDIST/*.so* /usr/local/mypackage/lib/
> ```

Okay - this should be possible to make happen in Singularity also as this is the `-H` behavior of `cp` after the shell expands the wildcards. That would both make our multi-stage act like Docker, and avoid adding additional build command options or `%from` markup. We can look into this. It's clearer to me now seeing the..

```
%files from build
    /opt/pgi/linux86-64-llvm/19.10/REDIST/*.so* /opt/pgi/linux86-64/19.10/lib/
```

... in the provided recipe with the `*.so*` on it.

I don't see any real issue in having this behavior for 3.6 in May, and potentially another 3.5.x bugfix release - no date has been determined for that yet.

**Comment by dtrudg** [comment]
Hi @samcmill - could you confirm if #5063 satisfies your needs by following the same behaviour as Docker? Thanks.

**Comment by dtrudg** [comment]
PR was +1'd by reported. Merged to master.
