### ISSUE TITLE
random squashsfs errors - on beegfs

### ISSUE THREAD

**Issue by timeu** [apptainer/singularity#5061]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
singularity version 3.4.1-4.2.ohpc.1.3.9

```

We have one user of our HPC system that report hat 3/1000 singularity jobs fail with random errors on some of the nodes:

```
error while loading shared libraries: /opt/conda/envs/aradeepopsis/bin/../lib/./libopenjp2.so.7: cannot read file data: Input/output error
```
or 
```
/bin/bash: error while loading shared libraries: /lib/x86_64-linux-gnu/libtinfo.so.6: cannot read file data: Input/output error
```

On the node where the job failed,  we can see following errors in `/var/log/messages` and `dmesg`: 

```
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: zlib_inflate error, data probably corrupt
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: squashfs_read_data failed to read block 0x2f474cd7
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: Unable to read data cache entry [2f474cd7]
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: Unable to read page, block 2f474cd7, size f745
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: Unable to read data cache entry [2f474cd7]
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: Unable to read page, block 2f474cd7, size f745
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: Unable to read data cache entry [2f474cd7]
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: Unable to read page, block 2f474cd7, size f745
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: Unable to read data cache entry [2f474cd7]
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: Unable to read page, block 2f474cd7, size f745
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: Unable to read data cache entry [2f474cd7]
Feb 25 00:38:45 clip-c2-21 kernel: SQUASHFS error: Unable to read page, block 2f474cd7, size f745
```
Interestingly some of the jobs on the same node that fail, work sometimes.  

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by dtrudg** [comment]
What does the job file look like? Are you doing a `singularity pull` or `singularity build` to get a SIF image and then running from that - or is the user trying to do e.g. `singularity run docker://xxxxx` for many parallel processes?

The issue may be seen if the machine is under extreme memory pressure - check that the jobs running are not consuming too much RAM. (these dmesg messages were noted in OpenBMC which uses squashfs and had memory pressure issues - https://github.com/openbmc/openbmc/issues/236)

The SQUASHFS errors you see in dmesg might be expected if a machine has a hardware issue with RAM, or storage. They are commonly reported for live images of Linux where there is a RAM or storage issue.

It's unlikely that there is an issue particular to Singularity's code here, as the errors are coming only from the Squashfs implementation in the Kernel.

**Comment by timeu** [comment]
@dctrud: The user uses `singularity exec` on a singularity image that is stored on a beegfs storage. 
Inside he runs a nextflow container which uses a conda environment. 
When moving the singularity image from the beegfs storage to a NFS mounted storage, it seems to work and no errors are thrown.

**Comment by dtrudg** [comment]
> @dctrud: The user uses `singularity exec` on a singularity image that is stored on a beegfs storage.
> Inside he runs a nextflow container which uses a conda environment.
> When moving the singularity image from the beegfs storage to a NFS mounted storage, it seems to work and no errors are thrown.

I'm afraid this indicates an issue between squashfs usage and beegfs storage, which is potentially specific to the OS / beegfs versions you have and may be difficult to track down. I don't have access to beegfs and would suggest you contact your vendor about the problem, or use the beegfs group (https://groups.google.com/forum/#!forum/fhgfs-user) or support email.

**Comment by dtrudg** [comment]
This is almost certainly a kernel squashfs <-> beegfs issue and is not something caused, or that can be addressed in Singularity, since we simply mount squashfs images using normal kernel functionality.
