### ISSUE TITLE
Cannot run docker hub images from a non-priviledged user

### ISSUE THREAD

**Issue by fviale** [apptainer/singularity#5068]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version
singularity version 3.5.2+ds1
```

### Expected behavior

From a priviledged user

```
root@trydev:~# singularity exec docker://busybox echo "hello world"
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob bdbbaa22dec6 done
Copying config b075e856be done
Writing manifest to image destination
Storing signatures
2020/02/26 23:57:39  info unpack layer: sha256:bdbbaa22dec6b7fe23106d2c1b1f43d9598cd8fc33706cc27c1d938ecd5bffc7
INFO:    Creating SIF file...
hello world
```
From a non-privieldged user. I expect to have the same result.

### Actual behavior

This is what happens when running the same command from a non sudoer user
```
$ singularity exec docker://busybox echo "hello world"
FATAL:   Unable to handle docker://busybox uri: failed to get SHA of docker://busybox: error getting username and password: error reading JSON file "/run/containers/1003/auth.json": open /run/containers/1003/auth.json: permission denied
```
This happens for all images pulled from docker hub, it does not happen with an image pulled from singularity library

```
$ singularity exec library://library/default/alpine echo "hello world"
hello world
```

### Steps to reproduce this behavior

Both singularity and docker are installed on the same machine, I don't know if it is related.

The issue can be reproduced by trying to pull or execute docker hub images from a non-priviledged user.

### What OS/distro are you running

```
root@trydev:~#  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

### How did you install Singularity

using the debian package singularity-container
https://packages.debian.org/sid/singularity-container
and aptitude
```
apt install singularity-container_3.5.2+ds1-1_amd64.deb
```
Default configuration is used.

**Comment by dtrudg** [comment]
The error indicates that the `containers/image` library we use to interact with docker registries is attempting to be able to deal with a file that would be in the user `$XDG_RUNTIME_DIR`, but it can't access/check for what it wants to get at there.

A couple of scenarios here:

Do you have a `$HOME/.docker/config.json` in the home directory for the user 1003 or has that user used a tool like podman and done a `podman login`?

Is the value of `$XDG_RUNTIME_DIR`  correct for the user - i.e. does ownership match `id`.

Are you trying to run Singularity inside another container environment (you say docker is on the machine)... or is it directly on a host or VM? Inside a container that bind mounts `/run` from the host would cause this issue.

**Comment by fviale** [comment]
@dctrud thanks for the answer

There is no `$HOME/.docker/config.json` for user 1003.

podman is indeed installed on the same machine (we are using this machine to test various container frameworks). This user has run in the past podman commands to run containers (e.g. podman run), but not specifically podman login.
Would removing podman from this machine solve the issue?

We are not running singularity from another container but from the host.

The value of `$XDG_RUNTIME_DIR` after su-ing to user 1003 is empty, is this correct? Note: X-windows is not installed on this server.

**Comment by fviale** [comment]
I removed podman from the machine using apt-remove podman, but it did not fix the issue.
`/run/containers` seems to be created by singularity 3.5 (as I cannot find this folder in other similar machines using singularity 2.6 and podman).
This folder has the following permissions (I believe it is expected):
```
 ls -la /run/containers
total 0
drwx------  3 root root  60 Feb 25 16:54 .
drwxr-xr-x 33 root root 980 Feb 26 23:38 ..
drwx------  6 root root 120 Feb 25 16:54 storage
```

**Comment by fviale** [comment]
After installing singularity 3.5 to a fresh environment where podman has never been installed or used, the issue I mention does not appear at first, and I am able to run a singularity container from docker hub using a standard shell.

When I try to do the same through a chain of processes where impersonation takes place a similar issue appear but with a different error message

The chain of process is the following

````
cperUser  9544  9.2  3.5 7833916 290336 ?      Sl   02:48   1:21 /home/cperUser/opt/proactive/scheduling/jre/bin/java -Dproactive.home=/home/cperUser/opt/proactive/scheduling -Djava.security.policy=/home/cpe
cperUser 10368  0.0  0.0  12832  3060 ?        S    03:02   0:00  \_ /bin/bash /home/cperUser/opt/proactive/scheduling/dist/scripts/processbuilder/linux/launch.sh SQHZ8PPLE5J1GA1 /home/cperUser/opt/proactive
cperUser 10376  0.0  0.0  12832  3192 ?        S    03:02   0:00      \_ /bin/bash ./user_step.sh SQHZ8PPLE5J1GA1 /tmp/tmp.40u8oGgG70 /tmp/tmp.nQ7JOs7ggZ /tmp/PA_JVM1127776786/local__demo-nodes_activeeon_com
cperUser 10394  0.0  0.0  25404  1992 ?        Sl   03:02   0:00          \_ ./suer64 viale ./command_step.sh SQHZ8PPLE5J1GA1 /tmp/tmp.40u8oGgG70 /tmp/tmp.nQ7JOs7ggZ /tmp/PA_JVM1127776786/local__demo-nodes_a
root     10395  0.1  0.0  62996  3712 pts/1    Ss   03:02   0:00              \_ /bin/su viale
viale    10397  0.0  0.0   4628   804 pts/1    S    03:02   0:00                  \_ sh
viale    10398  0.0  0.0  12832  3140 pts/1    S+   03:02   0:00                      \_ /bin/bash ./command_step.sh SQHZ8PPLE5J1GA1 /tmp/tmp.40u8oGgG70 /tmp/tmp.nQ7JOs7ggZ /tmp/PA_JVM1127776786/local__demo-
viale    10401 32.5  1.4 5105528 117456 pts/1  Sl+  03:02   0:06                          \_ SQHZ8PPLE5J1GA1 -cp .:/home/cperUser/opt/proactive/scheduling/dist/lib:/home/cperUser/opt/proactive/scheduling/dis
viale    10434  0.0  0.0  12836  2940 pts/1    S+   03:02   0:00                              \_ bash /tmp/jsr223nativeshell-7077465980408365926.bash
viale    10435  0.0  0.0   7420   768 pts/1    S+   03:02   0:00                                  \_ singularity exec docker://busybox echo "hello"
````
The error message appearing in the output is (sorry for the characters issues):
` [31mFATAL: [0m Unable to handle docker://busybox uri: failed to get SHA of docker://busybox: error getting username and password: error reading JSON file "/run/user/1001/containers/auth.json": open /run/user/1001/containers/auth.json: permission denied`
userid 1001 corresponds to "cperUser" and userid 1002 to "viale"

**Comment by dtrudg** [comment]
@fviale - thanks for all of the information here.

In that latest error output it is trying to access a `/run/user/1001` which is for `cperUser` not the active `viale` so the permission denied is expected.

`XDG_RUNTIME_DIR` will generally be set on non X systems for login sessions. When you are changing to a different user it doesn't appear to be getting set/reset and the `containers/image` library we use to handle docker things is trying to work in a runtime dir that is not for the current user.

Looking on my system...

```
# Login as 1000 and check XDG_RUNTIME_DIR
dave@ythel:~
08:51 AM $ id
uid=1000(dave) gid=1000(dave) groups=1000(dave),10(wheel) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
dave@ythel:~
08:51 AM $ env | grep XDG_RUNTIME_DIR
XDG_RUNTIME_DIR=/run/user/1000

# Now su to root - RUNTIME_DIR still set for 1000... anything created will be owned by root
# leading to permission issues later
root@ythel:/home/dave
08:53 AM $ id
uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
root@ythel:/home/dave
08:53 AM $ env | grep XDG_RUNTIME_DIR
XDG_RUNTIME_DIR=/run/user/1000
```

Now - if  the `/run/user/1001/containers/` doesn't already exist, but I use `singularity run docker://..`  it will be created with incorrect root permissions and user `1001` would later hit a permission denied error.

```
# Go to another user 1000 - runtime dir is still set for user 1000
root@ythel:/home/dave
08:53 AM $ su slurm
slurm@ythel:/home/dave
08:53 AM $ id
uid=1001(slurm) gid=1001(slurm) groups=1001(slurm) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
slurm@ythel:/home/dave
08:53 AM $ env | grep XDG_RUNTIME_DIR
XDG_RUNTIME_DIR=/run/user/1000
```

The `XDG_RUNTIME_DIR` will be wiped if I `su - ` instead of straight `su`...

```
dave@ythel:~
08:56 AM $ su -
Password: 
[root@ythel ~]# id
uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[root@ythel ~]# env | grep XDG_RUNTIME_DIR
[root@ythel ~]# su - slurm
[slurm@ythel ~]$ id
uid=1001(slurm) gid=1001(slurm) groups=1001(slurm) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[slurm@ythel ~]$ env | grep XDG_RUNTIME_DIR
```
Without  `XDG_RUNTIME_DIR` set then `containers/image` is going to try and work under `/run/containers/...`  instead of `/run/user/xxx/containers` and if this is created as root with tight permissions then other users will have problems later on if their `XDG_RUNTIME_DIR` is not set.

This issue on the `containers/image` library GitHub repo is relevant: https://github.com/containers/image/issues/514#issuecomment-428625279

Essentially it is important that `XDG_RUNTIME_DIR` is set to a user-writable location. If it is not set / incorrect then it is likely that permission denied issues will result immediately, or later on. The variable must be set properly 

Because `XDG_RUNTIME_DIR` is generally a system managed env var it's not something we really want to override in Singularity. Because the higher-level issue occurs in the `containers/image` library we use for Docker handling rather than in Singularity it's also not trivial to implement a workaround at that point.

I'll have a think on this some more.

**Comment by dtrudg** [comment]
Another complexity here - if you run `podman` or similar after `su` or `sudo` you could also end up creating the directories with incorrect permissions... so even if we work around somehow in Singularity then use of other tools could cause the problem again. This is really something we probably need to talk about with the `containers/image` folks, but they may simply require that `XDG_RUNTIME_DIR` is set correctly in the environment, and not wish to handle any case where it is not.

**Comment by fviale** [comment]
@dctrud the workaround you suggested to set XDG_RUNTIME_DIR=/run/user/$UID is working very well.

I can set export XDG_RUNTIME_DIR=/run/user/$UID in the chain of impersonation I shown above to make sure it is correctly set before calling singularity.

As you mention it is generally set by the system, but the way I used sudo su - (for manual testing) or through our chain of impersonation messed up this variable. So it's totally acceptable that we correct this from our side. It does not seem to be an issue with singularity. But this discussion may help other people encountering this problem. The variable could eventually be mentioned in the troubleshooting section of singularity documentation.

**Comment by dtrudg** [comment]
Glad to know the workaround is suitable for you.

> The variable could eventually be mentioned in the troubleshooting section of singularity documentation.

I'll open an issue on the singularity-userdocs repository for this and close this issue (though it'll be found by search as you mention for people who hit the issue).

Cheers,

**Comment by dtrudg** [comment]
Will be addressed by docs - see: https://github.com/sylabs/singularity-userdocs/issues/315
