### ISSUE TITLE
Home directory symlink path, current directory, and bind mount issues

### ISSUE THREAD

**Issue by bcnwvr** [apptainer/singularity#5069]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3
```

### Expected behavior

Our home directory path in /etc/passwd is a symlink in an automounted directory pointing to a path in another automounted directory.  This allows thousands of user accounts to be referenced via a common logical path through a small disk partition.  When I start up Singularity, I explicitly bind mount all the automount points on the host into the container.

I'm running with the default configuration and start up from my home directory.
Up to Singularity 3.5.0-rc.1, this has not been a problem.

```
% su - link
-sh-4.2$ whoami
link
-sh-4.2$ grep link /etc/passwd
link::54321:99:Hero of Hyrule:/linkdir/link:/bin/sh
-sh-4.2$ pwd
/linkdir/link
-sh-4.2$ ls -l /linkdir/link
lrwxrwxrwx 1 root root 13 Feb 26 12:04 /linkdir/link -> /realdir/link
-sh-4.2$ /bin/pwd
/realdir/link
```
```
-sh-4.2$ /opt/singularity-3.5.0-rc.1/bin/singularity exec -B /linkdir,/realdir docker://centos:7 sh
Singularity> pwd
/linkdir/link
Singularity> ls -l /linkdir/link
lrwxrwxrwx 1 root root 13 Feb 26 12:04 /linkdir/link -> /realdir/link
Singularity> /bin/pwd
/realdir/link
```

### Actual behavior

This stopped working with be55176ef438ddf677006105e68cf7ca3a72aa50.

```
-sh-4.2$ /opt/singularity-3.5.0-rc.2/bin/singularity exec -B /linkdir,/realdir docker://centos:7 sh
FATAL:   container creation failed: mount /var/singularity/mnt/session/linkdir/link->/linkdir/link error: while mounting /var/singularity/mnt/session/linkdir/link: destination /linkdir/link doesn't exist in container
```
```
-sh-4.2$ /opt/singularity-3.5.2/bin/singularity exec -B /linkdir,/realdir docker://centos:7 sh
FATAL:   container creation failed: mount /var/singularity/mnt/session/linkdir/link->/linkdir/link error: while mounting /var/singularity/mnt/session/linkdir/link: destination /linkdir/link doesn't exist in container
```

9f2dd32f721afd17a5d002af3e954be038e2c1b0 now avoids the FATAL, but still produces a WARNING which doesn't seem to apply in this case.  Is there anything that can be done to suppress the warning or tune the check so this case does not trigger the warning?

```
-sh-4.2$ /opt/singularity-3.5.3/bin/singularity exec -B /linkdir,/realdir docker://centos:7 sh
WARNING: Bind mount '/linkdir/link => /linkdir/link' overlaps container CWD /linkdir/link, may not be available
Singularity> pwd
/linkdir/link
Singularity> ls -l /linkdir/link
lrwxrwxrwx 1 root root 13 Feb 26 12:04 /linkdir/link -> /realdir/link
Singularity> /bin/pwd
/realdir/link
```

### Steps to reproduce this behavior

```
% sudo -i
# echo 'link::54321:99:Hero of Hyrule:/linkdir/link:/bin/sh' >> /etc/passwd
# mkdir -p /realdir/link
# chown link:nobody /realdir/link
# mkdir /linkdir
# ln -s /realdir/link /linkdir
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

Built from source tarball.

**Comment by cclerget** [comment]
Hi @bcnwvr ,

> Is there anything that can be done to suppress the warning or tune the check so this case does not trigger the warning?

You can suppress warning with `-s`/`--silent` option like this:  `singularity -s shell ...`

**Comment by bcnwvr** [comment]
Hi @cclerget .

Thanks for the pointer.  That does shut up the message.  But I'm worried that other problem conditions may crop up that I won't be aware of since all warnings will be suppressed.

I played around some more and found that the warnings will still show up even without the extra explicit bind mount options.  I was focusing on that option in the test cases since that was how I triggered the errors in the previous versions.  The home directory bind mount still comes from the default configuration.

```
-sh-4.2$ cd /linkdir
-sh-4.2$ /opt/singularity-3.5.3-test/bin/singularity shell docker://centos:7
Singularity> exit
```
```
-sh-4.2$ cd /linkdir/link
-sh-4.2$ /opt/singularity-3.5.3-test/bin/singularity shell docker://centos:7
WARNING: Bind mount '/linkdir/link => /linkdir/link' overlaps container CWD /linkdir/link, may not be available
Singularity> exit
```
```
-sh-4.2$ cd /linkdir/link/tmp
-sh-4.2$ /opt/singularity-3.5.3-test/bin/singularity shell docker://centos:7
WARNING: Bind mount '/linkdir/link => /linkdir/link' overlaps container CWD /linkdir/link/tmp, may not be available
Singularity> exit
```

It seems this warning is only triggered if the current working directory (GetCwd()) is within the mount point.  Does this warning still apply if a host path is bound unchanged to the same path within the container?  In that case, wouldn't the CWD mount inside the container match whatever has been bound from the host from the previous mount?

**Comment by cclerget** [comment]
@bcnwvr Singularity actually handle the creation of bind mount destination directories/files automatically in the container so there is various places where things could go badly when symlinks enter in the game, this warning was introduced by https://github.com/sylabs/singularity/pull/4881 to avoid a recursion during the container setup but there no warranty that CWD is setup correctly explaining this warning, additionally Singularity does its best to respect PWD path set outside the container once inside and that make the task difficult with symlinks.

I understand it's annoying but in the meantime those warnings may be useful and help debugging when things doesn't work as expected.

**Comment by bcnwvr** [comment]
Hi @cclerget .

I played around with the reproducer block in #4881 and finally got it working.  The singularity command was confusing because it fails with only one argument, but adding true as a second argument lets it do its job.  The test path also off by a directory (should be /data/test/foo/test instead of /data/test/foo/data/test).

With this, I see that 3.5.2 creates the extra directory and symlink and 3.5.3 refuses to do so.
However, if I remove the symlink components and run with 3.5.3, a container directory (instead of a symlink) gets created in the same place without the user explicitly doing anything.  This is not good, is it?

```
...
cd /data/test/container && singularity exec -B /data/test/foo:/data docker://alpine true
ls -F /data/test/foo/test
container/
```

While I was trying to figure out your test case, I was making changes and noticed something.  When CWD is not in the container, as in cases 1 and 2 below, the user gets kicked back to $HOME.  In the warning, it is not clear what "may not be available" applies to.  Moving the comma before the CWD path can help.

```
WARNING: Bind mount '%s => %s' overlaps container CWD, %s may not be available
```

In cases 3 and 4 below, Singularity is able to successfully start up the user in his or her CWD because the path is replicated inside the container.  Case 3 is contrived because even though the path matches, the contents are not guaranteed to be the same since a different path from the host was mapped into the container, but for case 4, the CWD inside the container should exist since the host directory is mapped into the same location inside the container.  In this case, I don't think there needs to be a warning.

setup
```
% sudo -i
# mkdir -p /data/test/container /data/test/foo
# ln -s /data /sdata
# cd /sdata/test/container
# pwd -L
/sdata/test/container
# pwd -P
/data/test/container
# singularity version
3.5.3
```

case 1
```
# singularity exec -B /sdata/test/foo:/sdata docker://alpine sh -c 'pwd; find /sdata'
WARNING: Bind mount '/sdata/test/foo => /sdata' overlaps container CWD /sdata/test/container, may not be available
/root
/sdata
```

case 2
```
# mkdir /data/test/foo/test
# singularity exec -B /sdata/test/foo:/sdata docker://alpine sh -c 'pwd; find /sdata'
WARNING: Bind mount '/sdata/test/foo => /sdata' overlaps container CWD /sdata/test/container, may not be available
/root
/sdata
/sdata/test
```

case 3
```
# mkdir /data/test/foo/test/container
# singularity exec -B /sdata/test/foo:/sdata docker://alpine sh -c 'pwd; find /sdata'
WARNING: Bind mount '/sdata/test/foo => /sdata' overlaps container CWD /sdata/test/container, may not be available
/sdata/test/container
/sdata
/sdata/test
/sdata/test/container
```

case 4
```
# singularity exec -B /sdata docker://alpine sh -c 'pwd; find /sdata'
WARNING: Bind mount '/sdata => /sdata' overlaps container CWD /sdata/test/container, may not be available
/sdata/test/container
/sdata
/sdata/test
/sdata/test/container
/sdata/test/foo
/sdata/test/foo/test
/sdata/test/foo/test/container
```

**Comment by cclerget** [comment]
@bcnwvr Thanks for the feedbacks and details, I will look into these cases once I get a chance
