### ISSUE TITLE
link to "installation guide" is broken

### ISSUE THREAD

**Issue by slowkow** [apptainer/singularity#5078]
I'm trying to install singularity.

I found the INSTALL.md file.

I clicked the link for "installation guide":

https://github.com/sylabs/singularity/blob/2c4f7953d6a253723f5262a1368a172b843ec4fe/INSTALL.md#L7

But it is broken:

```
404
Page not found :(

The requested page could not be found.
```

**Comment by dtrudg** [comment]
Apologies, and thank you for reporting. PR #5080 has been opened to correct this.
