### ISSUE TITLE
Ability to disable "mount hostfs" in command line

### ISSUE THREAD

**Issue by kvnull** [apptainer/singularity#5081]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3-1.1.fc31
```

### Expected behavior

On a machine with multiple users, some users need mount hostfs on, some need it off. 

Since a security policy may require it off, but probably won't require it on, please implement --no-hostfs as a command line option.

### Actual behavior

This can only be set in /etc/singularity/singularity.conf which means disturbing the sysadmin.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME=Fedora
VERSION="31 (Thirty One)"
```

### How did you install Singularity

From the Fedora repository.

**Comment by dtrudg** [comment]
This sounds reasonable :+1:
