### ISSUE TITLE
Do we have a tool like a ‘DockerClient’？

### ISSUE THREAD

**Issue by xuecangqiuye** [apptainer/singularity#5082]
What version of Singularity are you using? 
3.5.2

DockerClientis a toolkit for java to call Docker function。
Do we have same tools?

**Comment by cclerget** [comment]
Hi @XueCangQiuYe , there is no such tool for Singularity because we don't use a client/server architecture so we don't have API for that purpose.

**Comment by xuecangqiuye** [comment]
@cclerget Thank you so much
