### ISSUE TITLE
[lib-refactor][configure prefix] singularity no such file or directory

### ISSUE THREAD

**Issue by remyd1** [apptainer/singularity#509]
Hi,

When I try to set another directory than /usr/local with:

```
./configure --prefix=/some/path
```

 in the branch **lib-refactor**, I get:
```
singularity ...
-bash: /usr/local/bin/singularity: No such file or directory
```

Adding a symbolic link named `/usr/local/bin/singularity` to the right binary resolves that issue.

Rémy

**Comment by vsoch** [comment]
Did you completely remove the old version first?

**Comment by gmkurtzer** [comment]
I think the error that you are referring to is actually a bash PATH bug. I've seen it before when building binaries in different locations and moving/deleting prior ones. Does it go away if you open a new shell?

**Comment by jmstover** [comment]
@gmkurtzer I don't think it's a "bug" per-say, but that the command is still in the hash lookup table.

When this happens, if you run the 'hash' built-in, it probably shows singularity at the /usr/local/bin/ location. Try running:

```
$ hash -d singularity
$ singularity -v  (I think for version??)
```

That should re-read the path, and find it at the new location as long as it's in your path.

**Comment by remyd1** [comment]
I think you were right. After purging and reinstalling everything, it works normally.
