### ISSUE TITLE
Issue running docker image after building with --sandbox

### ISSUE THREAD

**Issue by wir963** [apptainer/singularity#5092]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version

singularity version 3.5.3
```

### Expected behavior

I would like to be able to build and run the given docker container with read/write privileges.

### Actual behavior

I am able top build the image but when I try to run the image, I get an error
```
FATAL:   failed to open /bin/sh for inspection: read /bin/sh: stale NFS file handle
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

```
$ singularity build --sandbox polysolver_4 docker://sachet/polysolver:v4
$ singularity run -B <local_path>:/home/test_docker polysolver_4 bash /home/polysolver/scripts/shell_call_hla_type_test /home/polysolver/test/test.bam Unknown 1 hg19 STDFQ 0 /home/test_docker
```

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

### How did you install Singularity

I am working on a cluster where Singularity is already installed. 

### Other Things I've Tried

```
$ singularity run -B <local_path>:/home/test_docker docker://sachet/polysolver:v4 bash /home/polysolver/scripts/shell_call_hla_type_test /home/polysolver/test/test.bam Unknown 1 hg19 STDFQ 0 /home/test_docker

...
java.io.IOException: Read-only file system
```

```
$ singularity run --writable-tmpfs -B <local_path>:/home/test_docker docker://sachet/polysolver:v4 bash /home/polysolver/scripts/shell_call_hla_type_test /home/polysolver/test/test.bam Unknown 1 hg19 STDFQ 0 /home/test_docker

...
java.io.IOException: No space left on device
```

**Comment by cclerget** [comment]
Hi @wir963 , regarding the error `FATAL:   failed to open /bin/sh for inspection: read /bin/sh: stale NFS file handle`, I don't think there is much that can be done at Singularity level for that, I would suggest to store sandbox image on another filesystem.

Additionally `docker://sachet/polysolver:v4` is attempting to write in the image and fail with `java.io.IOException: No space left on device`, I didn't find the dockerfile associated to this image to understand why/where it write, are you able to provide the dockerfile for this image ?

**Comment by dtrudg** [comment]
Closing as there has been no follow-up. Please feel free to reopen with the requested information.
