### ISSUE TITLE
Add start/stop for holding namespace open

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#51]
8:08 <gmk> what that needs is a feature I've been thinking about
18:09 <gmk> which holds open the namespace
18:10 <gmk> usage would be a bit different
18:10 <gmk> it would have to include a "start" and "stop"
18:10 <gmk> which will be in addition to the shell/run/exec options
18:11 <gmk> so when you "start" the container, it will launch a daemon process which will hold open the namespace.
18:11 <gmk> then all subsequent commands will join into that existing container

**Comment by gmkurtzer** [comment]
I have this prototyped and working in the master branch:

$ singularity start /tmp/Demo-1.img 
$ singularity shell /tmp/Demo-1.img 
Singularity/Demo-1.img> ps -ef
UID         PID   PPID  C STIME TTY          TIME CMD
gmk           1      0  0 12:51 ?        00:00:00 /usr/libexec/singularity/sexec
gmk           2      0  0 12:51 pts/4    00:00:00 /bin/bash --norc --noprofile
gmk           3      2  0 12:51 pts/4    00:00:00 ps -ef
Singularity/Demo-1.img> exit
$ singularity stop /tmp/Demo-1.img 

If you have a chance to play with it and find a bug, please open another issue.

Thanks!
