### ISSUE TITLE
configure does not check to see if python is installed

### ISSUE THREAD

**Issue by satra** [apptainer/singularity#510]
i was on a vanilla ubuntu system without python and configure didn't check that python was missing, but then make failed.

on librefactor branch.

**Comment by vsoch** [comment]
I think I figured out how to add this - @gmkurtzer I can add this to my next PR. Something like:

      AC_CHECK_PROG(PYTHON_CHECK,python,yes)
      if test x"$PYTHON_CHECK" != x"yes" ; then
            AC_MSG_ERROR([Please install python before installing.])
      fi

I just tested it looking for executable "pizza" and it seemed to work:

      checking for overlayfs... yes  
      checking for pizza... no
      configure: error: Please install python before installing.

and when changed to python, it found it.

      checking for setns... yes
      checking for overlayfs... yes
      checking for python... yes
      checking --with-slurm... no

Ubuntu without python @satra !! No, it cannot be!!

**Comment by vsoch** [comment]
I forgot to mention it, but this was fixed here https://github.com/singularityware/singularity/pull/517 and will be closable / added in 2.3!
