### ISSUE TITLE
How to overcome the no signature found error message?

### ISSUE THREAD

**Issue by cmartinotti** [apptainer/singularity#5101]
### Version of Singularity:

singularity version 3.5.3

### OUTPUT
FATAL:   no signatures found for system partition

### Expected behavior

I want to run a container downloaded from dockerhub, it's a GROMACS5.1.4 patched with plumed container, namely this one:
https://hub.docker.com/layers/cmartinotti/gromacs_plumed/5.1.4-2.4.4/images/sha256-b04af81e8fa6a06ff3d48a16c03bca0ac1252e66271ab52c9743dccff84091d2?context=explore

### Actual behavior
Not working

### What OS/distro are you running

CentOS Linux 8

### How did you install Singularity
It comes as a module installed in the supercomputer I'm trying to use, which is GADI

**Comment by cclerget** [comment]
Hi @cmartinotti , please provide all the steps about how you get this error along with the debug output when you run the container.

**Comment by truatpasteurdotfr** [comment]
https://opus.nci.org.au/display/Help/Gadi+Software+Catalogue is listed plumed as installed

works for me:
```
docker pull cmartinotti/gromacs_plumed:5.1.4-2.4.4
```

and
```
$ singularity build a.sif docker://cmartinotti/gromacs_plumed:5.1.4-2.4.4
INFO:    Starting build...
Getting image source signatures
Copying blob 4ccdce43d1e0 done
Copying blob c95f13c88d92 done
Copying blob 82656eee95ad done
...
2020/03/10 11:48:31  info unpack layer: sha256:5698eacf1a087a35e72d6acbb4fce675cb4eb5346c925fe7a2df513099d5cc97
INFO:    Creating SIF file...
INFO:    Build complete: a.sif

```

**Comment by cmartinotti** [comment]
The problem for me is when I try to run it. I run : 
singularity build a.sif docker://cmartinotti/gromacs_plumed:5.1.4-2.4.4 
 WARNING: 'nodev' mount option set on /scratch/xu1, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob 4ccdce43d1e0 skipped: already exists
Copying blob c95f13c88d92 skipped: already exists
Copying blob 82656eee95ad skipped: already exists
Copying blob 78ff727be57a skipped: already exists
Copying blob 448bb314afa5 skipped: already exists
Copying blob f8258f5e8433 skipped: already exists
Copying blob c3c8f449100f skipped: already exists
Copying blob eb305edac094 skipped: already exists
Copying blob 1fed624a6288 skipped: already exists
Copying blob d226a89bd42d skipped: already exists
Copying blob 24c2fe8a03d6 skipped: already exists
Copying blob 804b12cb3484 skipped: already exists
Copying blob 83b54dfb5707 skipped: already exists
Copying blob 72a7d45b18d8 skipped: already exists
Copying blob 4d09fd6017ed skipped: already exists
Copying blob 3633d11e16a7 skipped: already exists
Copying blob 705a4349980d skipped: already exists
Copying blob 9b924811ad0b skipped: already exists
Copying blob c6af8147bb4e skipped: already exists
Copying blob a2b41382c724 skipped: already exists
Copying blob dca0bb6a2a77 skipped: already exists
Copying blob 012595e97282 skipped: already exists
Copying blob 5698eacf1a08 skipped: already exists
Copying config 732feb8aae done
Writing manifest to image destination
Storing signatures
2020/03/16 14:10:40  info unpack layer: sha256:4ccdce43d1e00fd03ac5438d39e731c16db3dfcf03c68390884b8e8c814221ca
2020/03/16 14:10:41  warn rootless{dev/full} creating empty file in place of device 1:7
2020/03/16 14:10:41  warn rootless{dev/null} creating empty file in place of device 1:3
2020/03/16 14:10:41  warn rootless{dev/ptmx} creating empty file in place of device 5:2
2020/03/16 14:10:41  warn rootless{dev/random} creating empty file in place of device 1:8
2020/03/16 14:10:41  warn rootless{dev/tty} creating empty file in place of device 5:0
2020/03/16 14:10:41  warn rootless{dev/urandom} creating empty file in place of device 1:9
2020/03/16 14:10:41  warn rootless{dev/zero} creating empty file in place of device 1:5
2020/03/16 14:10:42  warn xattr{etc/gshadow} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2020/03/16 14:10:42  warn xattr{/scratch/xu1/cmi573/tmp/rootfs-ad45a0c9-6733-11ea-a3a6-200003dbfe80/etc/gshadow} destination filesystem does not support xattrs, further warnings will be suppressed
2020/03/16 14:11:39  info unpack layer: sha256:c95f13c88d926e6181e0594f76953a14ab80ce002fc6dbc968084a7e18aaafe9
2020/03/16 14:11:39  info unpack layer: sha256:82656eee95ad054e0aa75486e7c55b7666c26abbd9bf19373dd349f6e172ce9d
2020/03/16 14:11:39  info unpack layer: sha256:78ff727be57a68299558bb40b737669ca5cb9a8db948411d852ec809c14e7a1f
2020/03/16 14:11:39  info unpack layer: sha256:448bb314afa553bfb1578121328bbe92d2b5ca0f411967e7a0a200f672ade92f
2020/03/16 14:11:39  info unpack layer: sha256:f8258f5e84331bd9259519c8f6e84674bfa73cfbee83a66f215576af0b49f7e2
2020/03/16 14:11:39  info unpack layer: sha256:c3c8f449100f4367a9b890a0d401eec7c951d7836c2ffce16c31ffbaee2d9abe
2020/03/16 14:12:47  warn xattr{usr/local/lib/python2.7} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2020/03/16 14:12:47  warn xattr{/scratch/xu1/cmi573/tmp/rootfs-ad45a0c9-6733-11ea-a3a6-200003dbfe80/usr/local/lib/python2.7} destination filesystem does not support xattrs, further warnings will be suppressed
2020/03/16 14:13:53  info unpack layer: sha256:eb305edac0944b07575dbc1c1e4d34fd9009ee4f7331d7e71e3cefb2435cc837
2020/03/16 14:13:53  info unpack layer: sha256:1fed624a6288777d6a7ccd3f80a8f23b664d3b8703158d31b8c13f7a06bafc78
2020/03/16 14:13:53  warn xattr{tmp/mpich-build/mpich-3.1.4} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2020/03/16 14:13:53  warn xattr{/scratch/xu1/cmi573/tmp/rootfs-ad45a0c9-6733-11ea-a3a6-200003dbfe80/tmp/mpich-build/mpich-3.1.4} destination filesystem does not support xattrs, further warnings will be suppressed
2020/03/16 14:16:33  info unpack layer: sha256:d226a89bd42d793a2e1a59fe68eeb38101d4f049583388f1580af580917c619b
2020/03/16 14:16:33  info unpack layer: sha256:24c2fe8a03d6f2a10ca903446d5e4e9b3057e7cae9eab33cb81500762b634f0c
2020/03/16 14:16:33  info unpack layer: sha256:804b12cb3484d5b605c761825763e15b5e74faf3531db2359f6a6b12479619cb
2020/03/16 14:16:33  info unpack layer: sha256:83b54dfb5707a54febb2972766452c122f27053383e2a9fb9dc9515b7ba73ccf
2020/03/16 14:16:33  info unpack layer: sha256:72a7d45b18d8ef9294de636bec29924726bb3bd2f1a2d75a2d61f084f08c77ed
2020/03/16 14:16:33  warn xattr{usr/local/lib/python2.7} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2020/03/16 14:16:33  warn xattr{/scratch/xu1/cmi573/tmp/rootfs-ad45a0c9-6733-11ea-a3a6-200003dbfe80/usr/local/lib/python2.7} destination filesystem does not support xattrs, further warnings will be suppressed
2020/03/16 14:16:34  info unpack layer: sha256:4d09fd6017edcfa8a7f80ecec2c0542cda9022ef7b161fad8fe058a3235a86b8
2020/03/16 14:16:34  info unpack layer: sha256:3633d11e16a7dbbf88e542645d8a99128c3ac13af88e58bffc1ae2305bd8b5d3
2020/03/16 14:16:34  info unpack layer: sha256:705a4349980d0b770a41f14cd090b4a1fa218628248f630fb2c2dc4bc349b7a6
2020/03/16 14:16:34  warn xattr{tmp/osu-benchmark-build/osu-micro-benchmarks-5.4.2} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2020/03/16 14:16:34  warn xattr{/scratch/xu1/cmi573/tmp/rootfs-ad45a0c9-6733-11ea-a3a6-200003dbfe80/tmp/osu-benchmark-build/osu-micro-benchmarks-5.4.2} destination filesystem does not support xattrs, further warnings will be suppressed
2020/03/16 14:16:38  info unpack layer: sha256:9b924811ad0b88d65f316d619400d980abbc5a4310b69060681bba78305b9242
2020/03/16 14:17:00  info unpack layer: sha256:c6af8147bb4e20c7d67f3b386afc1864937e6cd8961e11955c1e9568cb461bc4
2020/03/16 14:17:00  info unpack layer: sha256:a2b41382c72490418d58d02798dbe7bcb77b42b0ebd33ad5e99d913b8caef87d
2020/03/16 14:17:00  info unpack layer: sha256:dca0bb6a2a77262432245bd1bb511d19a6df87749b6eebb2e3ac62823fdde55d
2020/03/16 14:17:00  info unpack layer: sha256:012595e97282b4471bb851ff51539337555af6f608a4713336f51a49a239268b
2020/03/16 14:17:00  info unpack layer: sha256:5698eacf1a087a35e72d6acbb4fce675cb4eb5346c925fe7a2df513099d5cc97
2020/03/16 14:17:53  warn xattr{var/cache/apt/archives/partial} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2020/03/16 14:17:53  warn xattr{/scratch/xu1/cmi573/tmp/rootfs-ad45a0c9-6733-11ea-a3a6-200003dbfe80/var/cache/apt/archives/partial} destination filesystem does not support xattrs, further warnings will be suppressed
INFO:    Creating SIF file...
INFO:    Build complete: a.sif

But then if I run singularity run a.sif with:
 
singularity run a.sif

it outputs : 

FATAL:   no signatures found for system partition

**Comment by cclerget** [comment]
@cmartinotti Please paste debug output for command `singularity --debug run a.sif`

**Comment by cmartinotti** [comment]
@cclerget  This is the output of the command you requested: 
DEBUG   [U=11100,P=26296]  persistentPreRunE()           Singularity version: 3.5.3
DEBUG   [U=11100,P=26296]  handleConfDir()               /home/573/cmi573/.singularity already exists. Not creating.
DEBUG   [U=11100,P=26296]  getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=11100,P=26296]  updateCacheSubdir()           Caching directory set to /home/573/cmi573/.singularity/cache/library
DEBUG   [U=11100,P=26296]  updateCacheSubdir()           Caching directory set to /home/573/cmi573/.singularity/cache/oci-tmp
DEBUG   [U=11100,P=26296]  updateCacheSubdir()           Caching directory set to /home/573/cmi573/.singularity/cache/oci
DEBUG   [U=11100,P=26296]  updateCacheSubdir()           Caching directory set to /home/573/cmi573/.singularity/cache/net
DEBUG   [U=11100,P=26296]  updateCacheSubdir()           Caching directory set to /home/573/cmi573/.singularity/cache/shub
DEBUG   [U=11100,P=26296]  updateCacheSubdir()           Caching directory set to /home/573/cmi573/.singularity/cache/oras
DEBUG   [U=11100,P=26296]  execStarter()                 Checking for encrypted system partition
DEBUG   [U=11100,P=26296]  Init()                        Image format detection
DEBUG   [U=11100,P=26296]  Init()                        Check for sandbox image format
DEBUG   [U=11100,P=26296]  Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=11100,P=26296]  Init()                        Check for sif image format
DEBUG   [U=11100,P=26296]  Init()                        sif image format detected
VERBOSE [U=11100,P=26296]  SetContainerEnv()             HOME=/home/573/cmi573
DEBUG   [U=11100,P=26296]  init()                        Use starter binary /opt/singularity/3.5.3/libexec/singularity/bin/starter-suid
VERBOSE [U=0,P=26296]      print()                       Set messagelevel to: 5
VERBOSE [U=0,P=26296]      init()                        Starter initialization
DEBUG   [U=0,P=26296]      load_overlay_module()         Trying to load overlay kernel module
DEBUG   [U=0,P=26296]      load_overlay_module()         Overlay seems supported by the kernel
DEBUG   [U=0,P=26296]      get_pipe_exec_fd()            PIPE_EXEC_FD value: 9
VERBOSE [U=0,P=26296]      is_suid()                     Check if we are running as setuid
VERBOSE [U=0,P=26296]      priv_drop()                   Drop root privileges
DEBUG   [U=11100,P=26296]  init()                        Read engine configuration
DEBUG   [U=11100,P=26296]  init()                        Wait completion of stage1
VERBOSE [U=11100,P=26307]  priv_drop()                   Drop root privileges permanently
DEBUG   [U=11100,P=26307]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=11100,P=26307]  init()                        Spawn stage 1
DEBUG   [U=11100,P=26307]  startup()                     singularity runtime engine selected
VERBOSE [U=11100,P=26307]  startup()                     Execute stage 1
DEBUG   [U=11100,P=26307]  StageOne()                    Entering stage 1
DEBUG   [U=11100,P=26307]  prepareAutofs()               Found "/proc/sys/fs/binfmt_misc" as autofs mount point
DEBUG   [U=11100,P=26307]  prepareAutofs()               Could not keep file descriptor for bind path /etc/localtime: no mount point
DEBUG   [U=11100,P=26307]  prepareAutofs()               Could not keep file descriptor for bind path /etc/hosts: no mount point
DEBUG   [U=11100,P=26307]  prepareAutofs()               Could not keep file descriptor for bind path /scratch: no mount point
DEBUG   [U=11100,P=26307]  prepareAutofs()               Could not keep file descriptor for bind path /g: no mount point
DEBUG   [U=11100,P=26307]  prepareAutofs()               Could not keep file descriptor for bind path /home: no mount point
DEBUG   [U=11100,P=26307]  prepareAutofs()               Could not keep file descriptor for bind path /apps: no mount point
DEBUG   [U=11100,P=26307]  prepareAutofs()               Could not keep file descriptor for home directory /home/573/cmi573: no mount point
DEBUG   [U=11100,P=26307]  prepareAutofs()               Could not keep file descriptor for current working directory /scratch/xu1/cmi573: no mount point
DEBUG   [U=11100,P=26307]  Init()                        Image format detection
DEBUG   [U=11100,P=26307]  Init()                        Check for sandbox image format
DEBUG   [U=11100,P=26307]  Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=11100,P=26307]  Init()                        Check for sif image format
DEBUG   [U=11100,P=26307]  Init()                        sif image format detected
DEBUG   [U=11100,P=26307]  setSessionLayer()             Overlay seems supported and allowed by kernel
DEBUG   [U=11100,P=26307]  setSessionLayer()             Attempting to use overlayfs (enable overlay = try)
FATAL   [U=11100,P=26307]  StageOne()                    no signatures found for system partition
VERBOSE [U=11100,P=26296]  wait_child()                  stage 1 exited with status 255

**Comment by cclerget** [comment]
@cmartinotti Ok looks like ECL is enabled on this cluster, you can quickly check `activated` value in the file `/opt/singularity/3.5.3/etc/singularity/ecl.toml`.
I invite you to reach out admins and ask them the procedure to run your own image if they authorize it.

If ECL is enabled, you couldn't skip it as it allow admins to restrict singularity usage to signed images or to a specific location.
