### ISSUE TITLE
no response received from singularity hub

### ISSUE THREAD

**Issue by tikk3r** [apptainer/singularity#5102]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
Laptop: singularity version 3.5.2-1.1.fc31
Computer 1: singularity version 3.2.1-1.1.el7
Computer 2: singularity version 3.4.2-1.1.el7
```

### Expected behavior

Attempting to pull my container from singularity hub with
```
singularity pull shub://tikk3r/lofar-grid-hpccloud:lofar_sksp@2002c0a6d1445d8d9b519edd3a05f25e2009e974
```
should start downloading the container. All of the above mentioned computers worked fine in the past.

### Actual behavior

The above command fails on my laptop and computer 1 with the following error:
```
INFO:    Downloading shub image
FATAL:   While pulling shub image: no response received from singularity hub
```

On computer 2 it does indeed start the download.

See also https://github.com/singularityhub/singularityhub.github.io/issues/205

### Steps to reproduce this behavior

Run the above pull command. However, it seems to work for some users, so I'm now wondering if it's something host related perhaps.

### What OS/distro are you running

```
$ cat /etc/os-release
Laptop: Fedora 31
Computer 1: RHEL 7.7
Computer 2: CentOS 7

```

### How did you install Singularity

On my laptop, using `dnf install singularity`. Unknown on the computer 1 and computer 2, as those are clusters managed by their respective IT departments.

**Comment by cclerget** [comment]
Hi @tikk3r , I can download it without any issues, are you behind a proxy ?

**Comment by tikk3r** [comment]
Not as far as I am aware. `$http_proxy` and `$https_proxy` are both empty. I have tried both my institute's local network and eduroam, both networks give that error.

**Comment by cclerget** [comment]
Are you able to pull an image from docker :

```
singularity pull docker://hello-world
```

**Comment by tikk3r** [comment]
That seems to work fine:
```
INFO:    Converting OCI blobs to SIF format
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob 1b930d010525 done
Copying config a1c2dc0436 done
Writing manifest to image destination
Storing signatures
2020/03/10 11:42:26  info unpack layer: sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced
INFO:    Creating SIF file...
INFO:    Build complete: hello-world_latest.sif
```

**Comment by cclerget** [comment]
Weird, @vsoch are you sure it's not related to shub download (or IP connection) quota ? I remember we were forced to disable all our shub tests for this reason. So far the client code responsible to pull image from shub hasn't changed since 2018, so I doubt it's a bug in Singularity.

**Comment by vsoch** [comment]
The pull of the container works fine for me, the get limit is nowhere reached, and the only detail that seems suspicious is the user having two different versions of Singularity, and on different hosts.

**Comment by cclerget** [comment]
@vsoch Ok thanks !

@tikk3r I would suggest to reach out your IT department for that issue, looks like a network issue on your side.

**Comment by tikk3r** [comment]
Sorry for not getting back to this. It seems to have resolved itself automatically, as now it works again, so I'm guessing an update of something in the system fixed it, but I couldn't nail down the exact cause.
