### ISSUE TITLE
Error "cannot execute binary file" with singularity run

### ISSUE THREAD

**Issue by matmu** [apptainer/singularity#5105]
### Version of Singularity
```
$ singularity version
2.6.1-dist
```

### Expected behavior
Directory listing

### Actual behavior
```
/bin/ls: /bin/ls: cannot execute binary file
```

### Steps to reproduce this behavior
Singularity image is based on this Docker image: https://hub.docker.com/r/matmu/nanopore
```
singularity build nanopore.simg shub://matmu/nanopore
singularity run nanopore.simg ls
```

### What OS/distro are you running

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by jmstover** [comment]
Are the architectures the same? i.e. Both the host and container x86_64, or power8, etc... 

That's usually when I've ran across that error, when the architecture is different.

**Comment by matmu** [comment]
I just saw, that the following warning/error occurs when building the image on our cluster (image file is still created):
```
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building Singularity image...
Error trying to change mode +x
: Input/output error
```

It has something to do with priveileges? If I run it on my own server (Singularity version 3.5), it works fine.

**Comment by jmstover** [comment]
Are you building on a NFS mount that has `noexec` set? I don't know if that prevents chmod ... but I know you can't execute a binary if that's the case.

**Comment by matmu** [comment]
> Are the architectures the same? i.e. Both the host and container x86_64, or power8, etc...
> 
> That's usually when I've ran across that error, when the architecture is different.

Architecture on our cluster: 
```
uname -a
Linux node06 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux
```

Architecture on my private server: 
```
uname -a
Linux 17906.server.net 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by matmu** [comment]
> Are you building on a NFS mount that has `noexec` set? I don't know if that prevents chmod ... but I know you can't execute a binary if that's the case.

I am still trying to find out about that. I built the image again on a local partition and the error 
```
Error trying to change mode +x
: Input/output error
```
disappeared. However, I still get
```
/bin/ls: /bin/ls: cannot execute binary file
```

**Comment by dtrudg** [comment]
@matmu  - can you indicate the filesystem you are building on, and give output of `mount` where you are seeing these errors?

**Comment by matmu** [comment]
> @matmu - can you indicate the filesystem you are building on, and give output of `mount` where you are seeing these errors?

Output of `mount` for filesystem `/dev/sda2`:
```
/dev/sda2 on /scratch type xfs (rw,relatime,attr2,inode64,noquota)
```

**Comment by dtrudg** [comment]
The `/bin/ls: /bin/ls: cannot execute binary file` appears to be because the `/.singularity.d/runscript` file in this container won't handle it . Running `singularity exec ls` will work:

```
singularity exec nanopore.simg ls
...
```

The runscript is doing:

```
exec "/bin/bash" "$@"
```

... so `singularity run ls` is calling `exec /bin/bash ls` which is not valid, as `ls` is a binary and not a bash script. If you try `bash ls` on your host you'd see that same issue:

```
dave@piran~> bash ls
/bin/ls: /bin/ls: cannot execute binary file
```
This is not really a Singularity problem. You can use `singularity exec ....` with the container. If you want to use run you'd have to feed the `ls` to the `-c` option of bash:

```
singularity run nanopore.simg -c ls
```
