### ISSUE TITLE
ubuntu-16.04 apt failed with fakeroot

### ISSUE THREAD

**Issue by Shenggan** [apptainer/singularity#5106]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3
```

### Expected behavior

`apt install gcc` should work in container when use fakeroot.

### Actual behavior

`apt install gcc` failed when use fakeroot.

```
Processing triggers for libc-bin (2.23-0ubuntu11) ...
dpkg (subprocess): cannot set security execution context for maintainer script: Invalid argument
dpkg: error processing package libc-bin (--unpack):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/libgmp10_2%3a6.1.0+dfsg-2_amd64.deb
 /var/cache/apt/archives/gcc_4%3a5.3.1-1ubuntu1_amd64.deb
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Steps to reproduce this behavior

```
$ singularity build --sandbox ./ubuntu-16 docker://ubuntu:16.04
$ singularity shell --writable --fakeroot ./ubuntu-16
Singularity> apt update
Singularity> apt install -y gcc
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

I installed Singularity from source.

**Comment by dtrudg** [comment]
What filesystem is the sandbox directory on? Some filesystems such as GPFS etc. do not support user namespaced operations.

**Comment by cclerget** [comment]
Looks like a selinux issue due to a missing `dpkg_script_t` context : https://bugzilla.redhat.com/show_bug.cgi?id=1614295, and it seems it won't be fixed as apt is not part of RH project.

**Comment by Shenggan** [comment]
Thanks @dctrud @cclerget. When I set selinux disabled. The apt issue will not appear anymore. So I think this issue just as @cclerget described.

**Comment by cclerget** [comment]
Closing the issue as not fixable at Singularity level.
