### ISSUE TITLE
singularity -q run prints stuff to STDOUT that doesn't come from the internal job.

### ISSUE THREAD

**Issue by alanhoyle** [apptainer/singularity#512]
Some tools take their input from STDIN or write their output to STDOUT.  singularity run, even with the '-q' option specified adds additional text output to STDOUT which causes chained commands to break.  We can't use 

For an example from my field (bioinformatics), we often use samtools to filter and view BAM and SAM files and pipe the outputs from one command to the input of the next command.  Singularity (freshly installed from github) adds 4+ lines to the beginning of the output, even when invoked with the '-q' quiet flag.  

Two suggestions, I would suggest implementing both:

1. write the singularity-generated output `Cache folder set..., etc` to STDERR instead of STDOUT
1. have '-q' suppress the singularity-generated output wherever it's supposed to go.  

Compare NATIVE `samtools view` output:  

> $ samtools view -H sample.bam |head
@HD	VN:1.4	SO:coordinate
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
@SQ	SN:chr6	LN:171115067
@SQ	SN:chr7	LN:159138663
@SQ	SN:chr8	LN:146364022
@SQ	SN:chr9	LN:141213431

with `singularity run samtools view` output:  

>$ singularity -q run shub://researchapps/samtools view -H sample.bam |head 
Cache folder set to /home/alanh/.singularity/shub
Found image researchapps/samtools:master
Downloading image... 68f8f61a41788baaffeea6d19fd8b2369b7a1cfc.img.gz
('Decompressing', u'/home/alanh/.singularity/shub/68f8f61a41788baaffeea6d19fd8b2369b7a1cfc.img.gz')
@HD	VN:1.4	SO:coordinate
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
$

Note that 10 lines are printed in both cases, but in the `singularity run` case, the first four lines are singularity output, not samtools output.

**Comment by gmkurtzer** [comment]
Good point! The python components are not honoring the SINGULARITY_MESSAGELEVEL.

Tag: @vsoch 

Are you using the master github branch, or development or lib-refactor?

Thanks!

**Comment by alanhoyle** [comment]
Master github.

**Comment by alanhoyle** [comment]
Just sent in a pull request that used `sys.stderr.write ()` instead of `print()` but still doesn't respect SINGULARITY_MESSAGELEVEL.  Partial fix....

**Comment by dtrudg** [comment]
This was fixed via #514 and #553. Please reopen if any remaining issue. Thanks,
