### ISSUE TITLE
Support for dynamic label values

### ISSUE THREAD

**Issue by tsnowlan** [apptainer/singularity#5120]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
singularity version 3.5.2
```

#### Context

The key-value pairs in `%labels` don't support dynamic values. We want to store the versions of various installed packages without having to hard code them in the definition file. Currently we writing directly to `/.singularity.d/sources.json`. When `%labels` is parsed, any existing file is loaded before applying the new labels.

#### Question

Is this a supported method of writing dynamic labels? Or is this likely to change in a future release?

**Comment by dtrudg** [comment]
At present there isn't a method to do this. We've had similar requests in the past, but it'd be great to know a little more about how you envisage this being possible? E.g. would you prefer something like carrying over labels from the environment in the `%post` block - or for the `%labels` section to allow retrieving label values by running a command in the built container?

We have a long-term goal to move away from having metadata in the root filesystem of the container, storing it in descriptors of SIF files instead where possible. The transition there will involve us thinking a lot about meta-data handling, so detailed use-cases etc. are very welcome.

**Comment by tsnowlan** [comment]
Our use case for the labels is primarily reproducibility. We use singularity images in several steps of our clinical diagnostics pipeline and keep an audit log of which images were used to analyze a given sample. We do this to always be able to reproduce the output of the pipeline for a given sample, and also know what versions of different packages were used in the event of a serious programmatic error.

Since the software packages are managed internal to an image and we use several images (and will be using more as time goes on), having a single command to see what is in any image independent of programming language or config location/syntax would greatly simplify things. Being able to set these dynamically, whether in `%post` or `%labels`, also helps reduce places for human error to occur by having fewer hard coded values that must be changed.

As far as where it's done... static values in `%labels` and the dynamic ones written in `%post` seems simple and practical. Writing json from the shell is a bit cumbersome though. Maybe something similar to `%environment`, where you `echo "SomeKey $SomeVar" >> $SINGULARITY_LABELS`. I'm not sure how the metadata would be written into the SIF descriptors, but the content of `%labels` and `$SINGULARITY_LABELS` could be treated as a temporary file and just be used to write the metadata to the descriptors instead of included as a file in `/.singularity.d`.

**Comment by cclerget** [comment]
@tsnowlan @dctrud Like adding build variables to have something like :

```
bootstrap: docker
from: alpine:${VERSION:-"3.9.0"}

%labels
	a.label.version ${VERSION:-"3.9.0"}
```

And build image with :

```
singularity build --var VERSION=3.7.0 /tmp/var.sif /tmp/var.def
```

**Comment by tsnowlan** [comment]
Personally less a fan of that method, just because I do all my customizations in `%post` and don't necessarily have the values available outside the container. That is, admittedly, specific to my workflow and something that could be reworked if needed.

I do really like the option of using a variable in the `bootstrap`/`from` lines though.
