### ISSUE TITLE
build:: add bind-mount and cli specifications as default in def file

### ISSUE THREAD

**Issue by adriansev** [apptainer/singularity#5121]
### Version of Singularity:
What version of Singularity are you using? Run:
```
3.5.3-1.1.el7
```

Am am trying to include in definition file the bind mount specifications.
I tried to setup in %environment section the variable SINGULARITY_BINDPATH
see https://github.com/adriansev/singularity-def/blob/master/el7alice.def
i do not know if the binding took place but fusemount option like in 
https://cvmfs.readthedocs.io/en/stable/cpt-configure.html#sct-premount
does not work ...
So, does anyone have any idea how --fusemount should work and if i can include it as default in the definition file?
Thank you!

**Comment by dtrudg** [comment]
Bind mounts cannot be included in a definition file. This has been requested before, but there are concerns that it makes containers that are tied to a system. E.g. if a container always bind mounts a directory `/data` from the host and writes into it, then if run on a system that uses `/data` for a different purpose it may be surprising to the user to have things written out there by the container.

I'll mark this as something for additional discussion.

Previous discussion at: https://github.com/sylabs/singularity/issues/2412

**Comment by adriansev** [comment]
Well, yes indeed, but this is the case for any software that have default locations... such an image could/would have a help that would describe the default locations used and how to change them.    
Moreover, the potential misuse or bad usage of a feature was never a reason for the lack of the feature IMHO... anyway, thanks, i will look to insert the image in a shell script.
