### ISSUE TITLE
future singularity runs fail if the download or Decompress steps are interrupted.

### ISSUE THREAD

**Issue by alanhoyle** [apptainer/singularity#513]
If the user kills the singularity process with either an external "kill" or hitting ctrl-c at the command line during the singularity run process, future attempts to run the same image fail.

The user has to manually delete the file from the cache in order to attempt the run again.  

To fix, we need a better checkpointing system.  I would suggest using a temporary filename/filepath and moving/renaming the .img into place as the last step, instead of using the final filenames during the intermediate steps (download and expanding).  

Below is an example, I pressed ctrl-c during the "Downloading image" step.  

> $ singularity -q run shub://researchapps/samtools
Cache folder set to /home/alanh/.singularity/shub
Found image researchapps/samtools:master
Downloading image... 68f8f61a41788baaffeea6d19fd8b2369b7a1cfc.img.gz
^CTraceback (most recent call last):
  File "/usr/local/libexec/singularity/python/cli.py", line 290, in <module>
    main()
  File "/usr/local/libexec/singularity/python/cli.py", line 148, in main
    run(args)
  File "/usr/local/libexec/singularity/python/cli.py", line 187, in run
    download_folder=cache_base)
  File "/usr/local/libexec/singularity/python/shub/api.py", line 123, in download_image
    image_file = api_get(url,stream=image_file)
  File "/usr/local/libexec/singularity/python/utils.py", line 164, in api_get
    chunk = response.read(chunk_size)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
cat: /tmp/singularity-container_dir.1QyRquTg/researchapps/samtools/SINGULARITY_RUNDIR: No such file or directory
cat: /tmp/singularity-container_dir.1QyRquTg/researchapps/samtools/SINGULARITY_IMAGE: No such file or directory
chmod: cannot access '': No such file or directory
ERROR  : Container not found: 
ABORT  : Retval = 255
$ singularity -q run shub://researchapps/samtools
Cache folder set to /home/alanh/.singularity/shub
Image already exists at /home/alanh/.singularity/shub/68f8f61a41788baaffeea6d19fd8b2369b7a1cfc.img.gz, skipping download.
ERROR  : File is not a valid Singularity image, aborting...
ABORT  : Retval = 255

**Comment by gmkurtzer** [comment]
Hello. Are you testing from the master GitHub branch?

Tag: @vsoch

**Comment by vsoch** [comment]
Ah! we have that check for docker, but not for singularity. Great point - I will add this.

**Comment by alanhoyle** [comment]
I'm running the master GitHub branch.  Thanks for the quick confirmation.

**Comment by gmkurtzer** [comment]
Hi @alanhoyle, I just merged lib-refactor into 'development'. Can you test that branch and see if the issue still exists?

Thanks!

**Comment by vsoch** [comment]
@alanhoyle +1 - could you test again with development? This looks like it should be fixed up :)

**Comment by dtrudg** [comment]
Closing as we believe this is fixed. Let us know if you have any issues with current Singularity. Thanks!
