### ISSUE TITLE
HowTo: Check existence in cache and download if missing

### ISSUE THREAD

**Issue by adriansev** [apptainer/singularity#5149]
### Version of Singularity:
`3.5.3-1.1.fc31`

### Expected behavior
check if cached

### Actual behavior
singularity cache list
There are 1 container file(s) using 234.22 MB and 0 oci blob file(s) using 0.00 kB of space
Total space used: 234.22 MB

There is no way to check if container is already present
How can i check if the container is already present?
Can i do directly run shub://  and if not in cache, can i trust that it will be downloaded automatically in cache and then used from cache?

### What OS/distro are you running
f31, centos7

### How did you install Singularity
fedora repository, epel

**Comment by dtrudg** [comment]
The `-v` option lists content, and the `-T` option can be used to limit to cache entries of a certain type:

```
dave@piran~/S/G/singularity> singularity cache list -v -T shub
NAME                     DATE CREATED           SIZE             TYPE
hello-world_latest.sif   2020-03-25 08:44:36    62.65 MB         shub

There are 1 container file(s) using 62.65 MB of space
Total space used: 62.65 MB
```

There are some limited situations in the 3.5.x codebase where an image may not be cached if `run` directly. It will still run though. These are addressed in our `master` branch with a cache rewrite that will be part of the next Singularity `3.6` release.

**Comment by adriansev** [comment]
@dctrud thanks for answer! i did not expect the -v to apply to list.   
Is there any way to assure that is cached? Could something like the following work and is valid?:   
1. take the the name of container, replace `:` with `_` and add `.sif` and see if it is in cache   
2. if not, do a pull and then delete the local file
3. now it should be in cache, i can use with shub and the cached data will be used   

Thank you!

**Comment by dtrudg** [comment]
Generally you cannot ensure something remote, that may change at any time, is cached. A new version of the shub image could be pushed, and for docker a tag may be moved to a different image. You'd have to use a specific immutable hash to refer to the remote resource.

If you need to always use a specific version that you need to be local then you should `pull` and run the local .sif file directly.

Caching is also not 100% concurrency safe across a cluster. It will be much better in 3.6 than 3.5, but it will only be safe on a filesystem that supports atomic rename - pull is recommended for that  reason too.

**Comment by adriansev** [comment]
@dctrud ok, i see, thanks a lot for info! and yes, indeed, even if the image is read only i was planning to access it concurrently from a shared cache
