### ISSUE TITLE
Singularity and local repository/hub

### ISSUE THREAD

**Issue by davidhrbac** [apptainer/singularity#515]
We have internal docker hub running on `hub.it4i.cz:5000`. So I am able to run docker like this:

```console
sudo docker run -i -t --rm hub.it4i.cz:5000/test-cont-3.2 /bin/bash
```

How can I directly use this hub with singularity? Something like:
```console
export SINGULARITY_DOCKER_REGISTRY='--registry hub.it4i.cz:5000'
singularity shell docker://test-cont-3.2
```

Is there a solution?

**Comment by vsoch** [comment]
hey @davidhrbac ! See if this approach (using a Bootstrap file) works first:

https://github.com/singularityware/singularity/issues/429

If you use the current master, the trick would be to try doing as you did,exporting `SINGULARITY_DOCKER REGISTRY` and using `--debug` to verify this has been done, and you probably have seen this is where we determine that, although we did get the variable primarily from the Boostrap file and the `DOCKER_USERNAME` and `DOCKER_PASSWORD` were intended to be found in the environment.

https://github.com/singularityware/singularity/blob/b3a80f7268edbe5ee67dcc445bca5a2ffe0350ac/libexec/bootstrap/modules-v2/build-docker.sh#L77

If so, I would next try using the `lib-refactor` branch and including the full registry name in the uri, like:

`registry/namespace/image:tag`

For both these approaches, if you are running into trouble please share the debug output so we can help the best that we can! I have to do some airporty things this morning but I'll be back to help maybe later afternoon!

**Comment by davidhrbac** [comment]
@vsoch #429 solution works for me. I've got 2.2.1., running  `--debug` does not give me `DOCKER_*` envs. Maybe they were introduced after 2.2.1? Will try to play with master.

**Comment by gmkurtzer** [comment]
@davidhrbac Can you play with the "development" branch instead? That is where all of the latest awesomeness now lives!

Thanks!

**Comment by gmkurtzer** [comment]
@vsoch Can you confirm if @davidhrbac's bug is fixed in the "development" branch? Thanks!

**Comment by vsoch** [comment]
@davidhrbac are you able to test the development branch with your local registry? Or hook me up so I can test it out? heh.

**Comment by davidhrbac** [comment]
cc @hra0031

**Comment by davidhrbac** [comment]
@vsoch we have successfully tested development branch. @hra0031 has created PR to allow custom port. We had to create a sub-folder for Singularity to parse the URL.  So we are able to pull with the devel version like this:

```console
singularity shell docker://hub.it4i.cz:5000/sub-fodler/test-cont-3.2
```

Sub-folder should be included because of URL parsing after line https://github.com/singularityware/singularity/blob/development/libexec/python/shell.py#L88

**Comment by vsoch** [comment]
Excellent! If I am able to test (I'm on an airplane now!) We should be able to get the PR merged soon. This is great work, thank you for adding this functionality!

**Comment by gmkurtzer** [comment]
This has been resolved, correct?

**Comment by vsoch** [comment]
yep you finally merged it after I poked and threw latkes at you for three days! lol

**Comment by davidhrbac** [comment]
@vsoch thanks!

**Comment by gmkurtzer** [comment]
Only 3 days @vsoch? Haha...

Thanks everyone!
