### ISSUE TITLE
verify base image in a def file

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#5150]
When building a container, I'd like to be able to do a `singularity verify` and then bomb out if the base container is untrusted.  Here is an extremely ugly and brittle way to do it in a def file:
```
Bootstrap: library
From: alpine:sha256.63259fd0a2acb88bb652702c08c1460b071df51149ff85dc88db5034532a14a0

%pre
    # this is going to delete your cache to make sure you are getting a minty
    # fresh image from the library
    rm -rf  /root/.singularity/cache/library

%setup
    # insert the fingerprint here
    KEY_FP=8883491F4268F173C6E5DC49EDECE4F3F38D871E
    MESSG="Data integrity verified"
    singularity verify /root/.singularity/cache/library/sha256*/* | \
        grep -q $KEY_FP
    singularity verify /root/.singularity/cache/library/sha256*/* | \
        grep -q "$MESSG"

%post
    echo "build here"
```
It works.  But it makes the baby Jesus cry.  👶 ✝️ 😢 

In the long term, it would be great if this functionality were built into Singularity.  Maybe a new keyword in the def file called `Fingerprint:`.
```
Bootstrap: library
From: my_signed_container
Fingerprint: 8883491F4268F173C6E5DC49EDECE4F3F38D871E
```
^Importantly this would cause the build to fail if the container was unsigned **OR** if it was signed but had an incorrect fingerprint.  

In the near term it would just be nice to have an env var or something available at build time that would point to the location of the downloaded SIF file so I could dispense with deleting the cache and whatnot.  

**BONUS:**
It would be cool if the `verify` command had a `--fingerprint` option and if verify would just return a 0 or 1 exit code if the fingerprint does or doesn't match.  Something like this:
```
$ singularity verify --fingerprint GOODPRINT123 my.sif

$ echo $?
0

$ singularity verify --fingerprint BADPRINT321 my.sif

$ echo $?
1
```

**Comment by dtrudg** [comment]
Have looked at this in conjunction with our roadmap, and it generally fits best in a tranche of work planned for 3.7 which will touch other portions of signing, verification code.

**Comment by dtrudg** [comment]
~Can implement using the ECL `shouldRun` with an ECL whitelist config passed that is generated from the `Fingerprint: xxxx` build header. The ECL code is well tested and re-use avoids duplication of code.~
