### ISSUE TITLE
Best Practices? Setting PATH for use within container on exec

### ISSUE THREAD

**Issue by ckeeling** [apptainer/singularity#5152]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.1
```

### Expected behavior

What did you expect to see when you do...?

I have created a definition file based on Bootstrap: docker From: ubuntu:disco that includes in %post an installation of a program at /usr/local/bin/program_directory/program_name

sudo singularity build container.simg container.recipe
builds without problems, but I would expect if I have the path set right:

singularity exec container.simg program_name --version
Version #0.0

### Actual behavior

What actually happened? Why was it incorrect?
singularity exec container.simg program_name --version
/.singularity.d/actions/exec: 21: exec: program_name: not found

But,
singularity exec container.simg /usr/local/bin/program_directory/program_name --version
Version #0.0

Of course I need to set the PATH to include this location, but what is the right way?

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

I have been trying various ways to set the PATH in the container within %post or %environment, but I haven't got it to work yet.  What is the proper way to do this seemingly easy task?

e.g. 

in %post as described in the 3.5 docs [here](https://sylabs.io/guides/3.5/user-guide/environment_and_metadata.html#)
RUN_PATH="/usr/local/bin/program_directory:$PATH"
echo 'export PATH=$RUN_PATH' >>$SINGULARITY_ENVIRONMENT

or 
%environment
	    PATH=$RUN_PATH
	    export PATH

Neither of these have worked for me. What is the correct way?

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

[Vagrant, via sylabs/singularity-3.5-ubuntu-bionic64 version 20191206.0.0](https://app.vagrantup.com/sylabs/boxes/singularity-3.5-ubuntu-bionic64)

**Comment by cclerget** [comment]
During build the `%environment` section is just copied into a file after execution of `%post` section, so it can't be used by `%post` and conversely which that both sections doesn't/can't share environment variables.
I would suggest in your case to have `%environment` like this:

```
%environment
     export PATH="/usr/local/bin/program_directory:$PATH"
```

If you want/need to add from `%post` section you can do it like this :
```
%post
     echo 'export PATH="/usr/local/bin/program_directory:\$PATH"' >> $SINGULARITY_ENVIRONMENT
```

Note the escape `\$PATH` to evaluate PATH during container run and not during build process

**Comment by ckeeling** [comment]
Thank you @cclerget 

Your suggestion for using %environment worked. I did not realize that the variable $RUN_PATH defined in %post would not be shared in %environment. Is this explained somewhere in the docs that I missed?

However, your suggestion for using %post did not. 

```
%post
     echo 'export PATH="/usr/local/bin/subread-2.0.0-Linux-x86_64/bin:\$PATH"' >> $SINGULARITY_ENVIRONMENT
```

In fact, the environment created didn't even allow simple commands to be found in the container. 

```
singularity exec container.simg ls
/.singularity.d/actions/exec: 21: exec: ls: not found
```

Even trying the following failed for this image:

```
singularity inspect container.simg
WARNING: No metadata partition, searching in container...
FATAL:   Could not inspect container: unable to process command: exit status 127: error output:
/bin/sh: 1: wc: not found
/bin/sh: 1: cat: not found

singularity inspect --environment Tuxedo_RNAseq.simg
FATAL:   Could not inspect container: unable to process command: exit status 127: error output:
/bin/sh: 1: wc: not found
/bin/sh: 1: cat: not found
/bin/sh: 1: wc: not found
/bin/sh: 1: cat: not found
```

I simplified my question to ask here, but I was using RUN_PATH in %post to incrementally add to the PATH for each of several programs I was installing in turn, with the plan to export this at the end. How would you go about this? I.e.

```
%post
        RUN_PATH="/usr/local/bin/program_1_directory"
        ...
        RUN_PATH="/usr/local/bin/program_2_directory:$RUN_PATH"
       ...
        RUN_PATH="/usr/local/bin/program_3_directory:$RUN_PATH"
       ...
	echo 'export PATH="$RUN_PATH:\$PATH"' >> $SINGULARITY_ENVIRONMENT
```

**Comment by cclerget** [comment]
> Is this explained somewhere in the docs that I missed?

Yes it is : https://sylabs.io/guides/3.5/user-guide/definition_files.html#environment

My mistake with quotes, so for `%post` it should be without `\` escape, giving :

```
%post
     echo 'export PATH="/usr/local/bin/subread-2.0.0-Linux-x86_64/bin:$PATH"' >> $SINGULARITY_ENVIRONMENT
```

**Comment by ckeeling** [comment]
Thank you @cclerget, this now works in ```%post``` as well, and I figured out how to do what I wanted with multiple programs.

```
%post
        RUN_PATH="/usr/local/bin/program_1_directory"
        ...
        RUN_PATH="/usr/local/bin/program_2_directory:$RUN_PATH"
        ...
        RUN_PATH="/usr/local/bin/program_3_directory:$RUN_PATH"
        ...
	EXPORT_PATH="export PATH=$RUN_PATH:\$PATH"
	echo $EXPORT_PATH >> $SINGULARITY_ENVIRONMENT
```

Although it is a moot point in my case because my build OS and my container OS are both Ubuntu and would have identical default paths, I think you suggested that $PATH as used without the ```\```  is expanded from the build OS, and thus creating the export text with EXPORT_PATH line properly passes "$PATH" as is to $SINGULARITY_ENVIRONMENT for expansion when the container is run.
