### ISSUE TITLE
fusemount :: cannot run program error

### ISSUE THREAD

**Issue by adriansev** [apptainer/singularity#5153]
### Error content
```
WARNING [U=1000,P=1]       runFuseDriver()               cannot run program [cvmfs2 alice.cern.ch /dev/fd/5]: exit status 1
FATAL   [U=1000,P=1]       StageTwo()                    exit status 1
```

### Version of Singularity:
3.5.3-1.1.fc31

### Expected behavior
`singularity run --fusemount "container:cvmfs2 alice.cern.ch /cvmfs/alice.cern.ch" shub://adriansev/el7cvmfs.sing`
to mount the required directory

### Actual behavior
so, it used to work with a native singularity container (bootstrap:yum) but for certain reasons i had to create docker containers with the actual packages content and then create the singularity container based on those. the relevant links :
https://github.com/adriansev/el7cvmfs.dock
https://hub.docker.com/repository/docker/adriansevcenco/el7cvmfs
and then customized to singularity:
https://github.com/adriansev/el7cvmfs.sing
https://singularity-hub.org/collections/4203

### Steps to reproduce this behavior
`singularity -d run --fusemount "container:cvmfs2 alice.cern.ch /cvmfs/alice.cern.ch" shub://adriansev/el7cvmfs.sing`

### What OS/distro are you running
fedora 31 (but it's not a problem as it used to work with a singularity native container)

### How did you install Singularity
from repository

**Comment by adriansev** [comment]
for the reproducibility this needs also 
```
export SINGULARITY_BINDPATH="${CACHE}:/var/lib/cvmfs"
export SINGULARITY_SCRATCHDIR="/var/run/cvmfs"
``` 
where CACHE should point to a directory in $HOME
and the old working singularity native container is [this](http://asevcenc.web.cern.ch/asevcenc/singularity/el7cvmfs)

**Comment by DrDaveD** [comment]
Adrian, as I had suggested to you earlier, the way to debug an error from cvmfs2 is to make a script surrounding the cvmfs2 command that can save error output from it.  For example:
```
#!/bin/bash
exec >/tmp/cvmfs2-debug-$1.out 2>&1
exec /usr/bin/cvmfs2 -o debug "$@"
```
and then use that instead of cvmfs2 in the --fusemount option.  If the script is in your home directory, it will already be bindmounted into the container.  In this case the error is
```
Debug: using library /usr/lib64/libcvmfs_fuse3_stub.so
CernVM-FS: pre-mounted on file descriptor 7
required configuration repository directory does not exist: /cvmfs/config-egi.egi.eu/etc/cvmfs
```
which is easily fixed by first having the option
```
--fusemount "container:cvmfs2 config-egi.egi.eu /cvmfs/config-egi.egi.eu"
```

**Comment by adriansev** [comment]
Thanks a lot for help! yes, sorry, i forgot about the cvmfs debugging, i was too focused on the containers issues that i completely ruled out the cvmfs problem. (and in fact if was a container problem with the recursive copy of a directory in %files section).
Thanks a lot!
