### ISSUE TITLE
container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session /rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: could not attach  image file to loop device: no loop devices available

### ISSUE THREAD

**Issue by KuanyuPhy** [apptainer/singularity#5154]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
VERSION=3.5.2 
```

### Expected behavior

What did you expect to see when you do...?
I want to exec singularity image

### Actual behavior

What actually happend? Why was it incorrect?
When I want to exec singularity image I have this error :
```
WARNING: failed to set O_CLOEXEC flags on image
WARNING: failed to set O_CLOEXEC flags on image
FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session
/rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: could not attach
 image file to loop device: no loop devices available
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
Install singularity like this :
I follow this website
https://github.com/syuvivida/VHEPP/tree/master/sergei_ana
```
bash
export VERSION=3.5.2 
wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz 
tar -xzf singularity-${VERSION}.tar.gz
cd singularity
./mconfig && make -C builddir && sudo make -C builddir install
```
and download image with this command :
```
wget http://atlaswww.hep.anl.gov/hepsim/soft/centos7hepsim.img
```
and try to exec like this :
```
singularity exec centos7hepsim.img bash -l
```
### What OS/distro are you running

```
windows subsystem for linux
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

```

**Comment by cclerget** [comment]
@KuanyuPhy Are you using WSL1 or WSL2 ?

**Comment by KuanyuPhy** [comment]
Thanks for your reply
I'm using WSL1

**Comment by cclerget** [comment]
WSL1 doesn't meet requirements to run container solution, WSL2 is required and for Singularity you have to use https://docs.microsoft.com/fr-fr/windows/wsl/release-notes#build-18945 as the minimal version for squashfs support and it should work.

Closing the issue as not a Singularity issue.
