### ISSUE TITLE
Cannot bind mount from /dev/shm 

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#5157]
### Version of Singularity:

3.5.3-1.1.el7

### Expected behavior

To be able to bind mount from a path under /dev/shm.

### Actual behavior

It gives a warning that /dev is already mounted and does not do the mount.

### Steps to reproduce this behavior

```
$ mkdir -p /dev/shm/dist/test
$ singularity run -B /dev/shm/dist:/dist docker://centos ls /dist
WARNING: Skipping /dev/shm/dist bind mount: /dev is already mounted
ls: cannot access /dist: No such file or directory
```

A workaround is to make a symlink to the desired /dev/shm path:
```
$ ln -s /dev/shm/dist shmdist
$ singularity run -B $PWD/shmdist:/dist docker://centos ls /dist
test
```

### What OS/distro are you running

CentOS7

### How did you install Singularity

From EPEL.

**Comment by cclerget** [comment]
@DrDaveD If you can give a try to #5162 ? Thanks !

**Comment by DrDaveD** [comment]
Yes, that fixes the problem.  Thank you very  much.
