### ISSUE TITLE
container startup uses unprivileged user namespace even though setuid flow is enabled

### ISSUE THREAD

**Issue by asmi10** [apptainer/singularity#5158]
### Version of Singularity:

singularity version
3.5.2

### Actual behavior
I have setuid flow enabled in singularity configuration and singularity is installed as root account.
> grep -i setuid /etc/singularity/singularity.conf
# ALLOW SETUID: [BOOL]
# Should we allow users to utilize the setuid program flow within Singularity?
allow setuid = yes

But container startup as a user always uses unprivileged installation and creates username space. I see this issue with SLES12SP2, it works fine with SLES15. Looks like some distribution/kernel issue?

Kernel version for SLES12SP2: 4.4.121-92.104-default
Kernel version for SLES15: 4.12.14-23-default
> singularity --debug run sles11sp4_batch.sif date
DEBUG   [U=1157,P=17107]persistentPreRunE()           Singularity version: 3.5.2
DEBUG   [U=1157,P=17107]handleConfDir()               /home/athapliy/.singularity already exists. Not creating.
DEBUG   [U=1157,P=17107]handleRemoteConf()            Ensuring file permission of 0600 on /home/athapliy/.singularity/remote.yaml
DEBUG   [U=1157,P=17107]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/library
DEBUG   [U=1157,P=17107]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/oci-tmp
DEBUG   [U=1157,P=17107]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/oci
DEBUG   [U=1157,P=17107]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/net
DEBUG   [U=1157,P=17107]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/shub
DEBUG   [U=1157,P=17107]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/oras
DEBUG   [U=1157,P=17107]execStarter()                 Checking for encrypted system partition
DEBUG   [U=1157,P=17107]Init()                        Image format detection
DEBUG   [U=1157,P=17107]Init()                        Check for sandbox image format
DEBUG   [U=1157,P=17107]Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=1157,P=17107]Init()                        Check for sif image format
DEBUG   [U=1157,P=17107]Init()                        sif image format detected
VERBOSE [U=1157,P=17107]execStarter()                 Unprivileged installation: using user namespace
VERBOSE [U=1157,P=17107]SetContainerEnv()             Not forwarding SINGULARITY_CACHEDIR from user to container environment
VERBOSE [U=1157,P=17107]SetContainerEnv()             HOME=/home/athapliy
VERBOSE [U=1157,P=17107]execStarter()                 User namespace requested, convert image sles11sp4_batch.sif to sandbox
INFO    [U=1157,P=17107]execStarter()                 Convert SIF file to sandbox...
DEBUG   [U=1157,P=17107]Init()                        Image format detection
DEBUG   [U=1157,P=17107]Init()                        Check for sandbox image format
DEBUG   [U=1157,P=17107]Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=1157,P=17107]Init()                        Check for sif image format
DEBUG   [U=1157,P=17107]Init()                        sif image format detected
DEBUG   [U=1157,P=17107]init()                        Use starter binary /usr/intel/pkgs/singularity/3.5.2/libexec/singularity/bin/starter
VERBOSE [U=1157,P=17107]  print()                       Set messagelevel to: 5

### What OS/distro are you running

```
$ cat /etc/os-release

cat /etc/os-release
NAME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp2"

**Comment by cclerget** [comment]
@asmi10 The line `VERBOSE [U=1157,P=17107]execStarter() Unprivileged installation: using user namespace` is telling that Singularity has been compiled with `./mconfig --without-suid`, this installation even if done as root force unprivileged use Singularity only without setuid binary being installed, therefore `allow setuid = yes` has no effect for unprivileged installation.

**Comment by asmi10** [comment]
No, singularity is not compiled with option: --without-suid. Below is the compile command I used, strangely I see this issue only with SLES12. It works fine with ubuntu16 & SLES15.
./mconfig &&     make -C ./builddir &&     make -C ./builddir install
checking: libuuid+headers... yes
 checking: libseccomp+headers... yes
 checking: cryptsetup... yes
=> generating fragments ...
=> building Makefile ...
=> generating singularity.spec ...
=> project singularity setup with :
    - host arch: x86_64
    - host wordsize: 64-bit
    - host C compiler: cc
    - host Go compiler: /usr/local/go/bin/go
    - host system: unix
      ---
    - target arch: x86_64
    - target wordsize: 64-bit
    - target C compiler: cc
      ---
    - config profile: release
      ---
    - SUID install: yes
    - Network plugins: yes
      ---
    - verbose: no
      ---
    - cryptsetup: /sbin/cryptsetup
      ---
    - version: 3.5.2

**Comment by jmstover** [comment]
@asmi10 What is the output of:
```
 $ ls -l $(singularity buildcfg | grep ^LIBEXEC | cut -f 2 -d '=')/singularity/bin/
```
In theory, the `starter-suid` binary should exist and have the correct permissions.

_*Edit:*_
Also if you still have it... What is:
```
grep 'SINGULARITY_SUID_INSTALL' builddir/config.h
```

**Comment by cclerget** [comment]
@asmi10 From code taken in 3.5.2: https://github.com/sylabs/singularity/blob/180ecff2a4b3a035ea8b964d18cc5fdeb0d4432e/cmd/internal/cli/actions_linux.go#L481-L485

You can see that the only way of showing `Unprivileged installation: using user namespace` verbose message like you pasted in your first post is to not request `-u` flag, be a user and run Singularity with an unprivileged installation :
- `buildcfg.SINGULARITY_SUID_INSTALL = 0`: unprivileged installation (when specifying `--without-suid`)
- `buildcfg.SINGULARITY_SUID_INSTALL = 1`: privileged installation (this is the default without specifying `--without-suid`)

This variable is hardcoded and set at build time by `./mconfig`

**Comment by asmi10** [comment]
hello!

Thanks for the feedback! it happened due to conflicts between multiple singularity installation. I realized later that someone has installed singularity without SUID flow under nfs path which was only getting mounted on sles12 hosts and this installation was conflicting with local host installation I did.
This issue can be closed now. Sorry for any inconvenience.

Thanks,
Asmita
