### ISSUE TITLE
Unclear error about argument in namespace creation

### ISSUE THREAD

**Issue by stefanches7** [apptainer/singularity#5160]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
d5eaf8a+dirty
```

I run a Nextflow pipeline executed using singularity.  In a very simple task (which is just a Bash script, see below) Singularity apparently fails to run in the Sandbox mode.

### Expected behavior
Verbose error of what's happened and where exactly (Singularity, Nextflow?)

### Actual behavior
```
Error executing process > 'fasta_validation_wf:input_suffix_check (1)'Caused by:
  Process `fasta_validation_wf:input_suffix_check (1)` terminated with an error exit status (1)
Command executed:  case "all_contigs.fa" in
      *.gz) 
          zcat all_contigs.fa > all_contigs.fa
          ;;
      *.fna)
          cp all_contigs.fa all_contigs.fa
          ;;
      *.fasta)
          cp all_contigs.fa all_contigs.fa
          ;;
      *.fa)
          ;;
      *)
          echo "file format not supported...what the phage...(.fa .fasta .fna .gz is supported)"
          exit 1
  esac  # tr whitespace at the end of lines
  sed 's/[[:blank:]]*$//' -i all_contigs.fa
  # remove ' and "
  tr -d "'"  < all_contigs.fa | tr -d '"' | tr -d "[]" > tmp.file && mv tmp.file all_contigs.fa
  # replace ( ) | . , / and whitespace with _
  sed 's#[()|.,/ ]#_#g' -i all_contigs.fa
  # remove empty lines
  sed '/^$/d' -i all_contigs.faCommand exit status:
  1Command output:
  (empty)Command error:
  INFO:    Convert SIF file to sandbox...
  ERROR  : Failed to create user namespace: Invalid argument
  ```

### Steps to reproduce this behavior
Launch `https://github.com/replikation/What_the_Phage/tree/slurm` with `-profile slurm` flag

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Scientific Linux"
VERSION="7.7 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.7"
PRETTY_NAME="Scientific Linux 7.7 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.7:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

```

### How did you install Singularity
**Conda installation** in a custom Conda environment

**Comment by jmstover** [comment]
So... Why is `input_suffix_check` from:
https://github.com/replikation/What_the_Phage/blob/master/modules/input_suffix_check.nf

being executed? I know nothing about NF ... so this is foreign to me, but... what is that actually doing? It appears as if it's trying to execute that script directly ... not from a file.

**Comment by cclerget** [comment]
@stefanches7 `ERROR  : Failed to create user namespace: Invalid argument` means that user namespaces are not enabled on this machine. Here the instructions to enable user namespace https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_containers/index#user_namespaces_options

**Comment by stefanches7** [comment]
@jmstover yes, it appears to be a Bash-script. Should also be that way, I suppose.

**Comment by stefanches7** [comment]
@cclerget thank you! That seems to work for my user. However, not when I launch SLURM. Do you maybe know something about the issue?

**Comment by cclerget** [comment]
@stefanches7 What's the error ?

**Comment by stefanches7** [comment]
@cclerget just the same as before (i.e., `Failed to create user namespace: Invalid argument`). The only difference is that I run SLURM (prepend `srun` to the previously used command)

**Comment by cclerget** [comment]
@stefanches7 Ok so it run on a node where user namespaces are not enabled, you need to enable user namespaces on all SLURM nodes

**Comment by stefanches7** [comment]
@cclerget thank you! Exactly that is the case.

**Comment by stefanches7** [comment]
The issue is still actual. I see e.g. "Failed to create a user namespace: Creation of user namespaces is not allowed" here as something much more suitable and solving many future questions
