### ISSUE TITLE
Have buildcfg command also show behavior modifiers that are stored

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#5161]
The `buildcfg` command currently outputs the configuration settings (`PREFIX`, `SESSIONIDIR`, etc...).

It would be good to also output any stored variables that can modify behavior. For example:  `buildcfg.SINGULARITY_SUID_INSTALL`

**Comment by cclerget** [comment]
I agree and adding an extra argument to get variable value like this :

`singularity buildcfg SESSIONDIR` to avoid commands chain `singularity buildcfg | grep SESSIONDIR | cut -d '=' -f2`
