### ISSUE TITLE
/dev/loop0 permission denied after installing singularity as root

### ISSUE THREAD

**Issue by randyg3000** [apptainer/singularity#5163]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```
`2.6.1-HEAD.9103f01`

### Expected behavior

singularity should execute

y should execute w/o error

### Actual behavior

>singularity exec --home $HOME:/home/$USER basic.simg cat /etc/alpine-release
ERROR: Could not create /dev/loop0: Permission denied
ABORT: Retval = 255

### Steps to reproduce this behavior
singularity exec --home $HOME:/home/$USER basic.simg cat /etc/alpine-release

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
```

### How did you install Singularity

The installation instructions we used are attached. Singularity was installed as root.

[portal-libarchive-3.4.0.txt](https://github.com/sylabs/singularity/files/4417829/portal-libarchive-3.4.0.txt)
[portal-singularity-2.6.1.txt](https://github.com/sylabs/singularity/files/4417830/portal-singularity-2.6.1.txt)

**Comment by cclerget** [comment]
@randyg3000 Did you checked that setuid bit is set correctly on `*-suid` files ?

Looking at the execution, there is chance that recursive `chmod -R a+rX` reset the setuid bit set previously :

```
echo -e "\nNow become root and install with: \n"
echo -e "    cd ${INSTALL}/singularity ; make install 2>&1 | tee log.make-install \n"
echo -e "    cd ${INSTALL}/libexec/singularity/bin ; chmod 4755 start-suid action-suid mount-suid \n"
echo -e "    cd ${INSTALL} ; chmod -R a+rX etc bin libexec include lib share \n"
echo -e "    cd ${INSTALL} ; chmod a+rX . \n"
echo -e "    chown -Rh root:singular ${INSTALL} \n"
echo -e "(Check the above.)"
```

EDIT: Changing owner may also reset setuid bit. Try by putting `chmod 4755 ...` line after `chown -Rh root:singular`

**Comment by randyg3000** [comment]
this appears to be the case, permissions were wrong with suid
Thanks very much for the support!
