### ISSUE TITLE
Add sanity check to build args to prevent erasing home directory

### ISSUE THREAD

**Issue by eriksjolund** [apptainer/singularity#5166]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
singularity version 3.5.3
```

### Expected behavior

What did you expect to see when you do...?

(I'm writing this on behalf of someone else)

```
$ cd
$ pwd
/home/myuser
$ sudo /opt/singularity3/bin/singularity build --sandbox /home/myuser/ docker://somestring/tensorflow1.14.0-gpu-py3
Build target already exists. Do you want to overwrite? [N/y] y
```

(The string `docker://somestring/tensorflow1.14.0-gpu-py3)` is somewhat modified
to add some anonymity. I guess the information is not needed for this feature request)

### Actual behavior

What actually happend? Why was it incorrect?

Home directory was deleted.

Maybe singularity could add some extra sanity checks?

* Idea 1 : For the case that the `--sandbox` directory is non-empty, maybe the build should only
be allowed if the contents in the directory resemble a container file system.

* Idea 2: Check for the $HOME environment variable and check that the `--sandbox` directory
is not the same path.

* Idea 3: Check for the existence of .bashrc in the sandbox dir.

* Idea 4: Reformulate the question so that it is extra clear what will happen.
Instead of "Do you want to overwrite? [N/y]" 
it could be "Do you want to first erase all files and directories under /home/myuser? [N/y]"

----------

Just some extra information, explaining why `sudo` was used (if you wonder):

Quote from:
https://sylabs.io/guides/3.5/user-guide/build_a_container.html#creating-writable-sandbox-directories
_It’s possible to create a sandbox without root privileges, but to ensure proper file permissions it is recommended to do so as root._

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

From source code.

**Comment by cclerget** [comment]
@eriksjolund Let's assume it could happen with other sensible directories, so ideas 2 and 3 couldn't prevent that. We could improve the question for sure to something like :

`/home/myuser will be erased during the build process. Do you want to continue ?`

Taking idea 1, we could just look at `.singularity.d/runscript` file presence when the directory is non-empty, if not present, the build process is aborted and user is invited to check this directory first and use `--force` if he really want to overwrite it.
