### ISSUE TITLE
non-sudo user runtime error( failed to create thread )

### ISSUE THREAD

**Issue by kihangyoun** [apptainer/singularity#5167]
singularity version : 3.5.3

### Problem

In the process of running the sif image, it works well when tested with the root user, but when executed in the user account, the following error occurs.

FATAL [U = 20004, P = 394794] execStarter () while extracting met_8.1.sif: root filesystem extraction failed: extract command failed: FATAL ERROR: Failed to create thread

### Expected behavior

DEBUG   [U=0,P=390524]     persistentPreRunE()           Singularity version: 3.5.3
DEBUG   [U=0,P=390524]     handleConfDir()               /root/.singularity already exists. Not creating.
DEBUG   [U=0,P=390524]     setValue()                    Updated flag 'tmpdir' value to: /d2/data/lenovo/khyun/AA/025_Singularity
DEBUG   [U=0,P=390524]     getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=0,P=390524]     updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library
DEBUG   [U=0,P=390524]     updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci-tmp
DEBUG   [U=0,P=390524]     updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci
DEBUG   [U=0,P=390524]     updateCacheSubdir()           Caching directory set to /root/.singularity/cache/net
DEBUG   [U=0,P=390524]     updateCacheSubdir()           Caching directory set to /root/.singularity/cache/shub
DEBUG   [U=0,P=390524]     updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oras
DEBUG   [U=0,P=390524]     execStarter()                 Checking for encrypted system partition
DEBUG   [U=0,P=390524]     Init()                        Image format detection
DEBUG   [U=0,P=390524]     Init()                        Check for sandbox image format
DEBUG   [U=0,P=390524]     Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=390524]     Init()                        Check for sif image format
DEBUG   [U=0,P=390524]     Init()                        sif image format detected
VERBOSE [U=0,P=390524]     SetContainerEnv()             Not forwarding SINGULARITY_TMPDIR from user to container environment
VERBOSE [U=0,P=390524]     SetContainerEnv()             Not forwarding SINGULARITY_MKSQUSHFS_MAX_CPUS from user to container environment
VERBOSE [U=0,P=390524]     SetContainerEnv()             Not forwarding SINGULARITY_UNSQUSHFS_MAX_CPUS from user to container environment
VERBOSE [U=0,P=390524]     SetContainerEnv()             HOME=/root
DEBUG   [U=0,P=390524]     init()                        Use starter binary /opt/kma/kma_lib/apps/singularity/3.5.3_nosuid/libexec/singularity/bin/starter
VERBOSE [U=0,P=390524]     print()                       Set messagelevel to: 5
VERBOSE [U=0,P=390524]     init()                        Starter initialization
DEBUG   [U=0,P=390524]     get_pipe_exec_fd()            PIPE_EXEC_FD value: 8
VERBOSE [U=0,P=390524]     is_suid()                     Check if we are running as setuid
DEBUG   [U=0,P=390524]     init()                        Read engine configuration
DEBUG   [U=0,P=390524]     init()                        Wait completion of stage1
DEBUG   [U=0,P=390579]     set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=390579]     init()                        Spawn stage 1
DEBUG   [U=0,P=390579]     startup()                     singularity runtime engine selected
VERBOSE [U=0,P=390579]     startup()                     Execute stage 1
DEBUG   [U=0,P=390579]     StageOne()                    Entering stage 1
DEBUG   [U=0,P=390579]     prepareRootCaps()             Root full capabilities

### Actual behavior

DEBUG   [U=20004,P=394794] persistentPreRunE()           Singularity version: 3.5.3
DEBUG   [U=20004,P=394794] handleConfDir()               /d2/home/lenovo/khyun/.singularity already exists. Not creating.
DEBUG   [U=20004,P=394794] setValue()                    Updated flag 'tmpdir' value to: /d2/data/lenovo/khyun/AA/025_Singularity
DEBUG   [U=20004,P=394794] getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=20004,P=394794] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/library
DEBUG   [U=20004,P=394794] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/oci-tmp
DEBUG   [U=20004,P=394794] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/oci
DEBUG   [U=20004,P=394794] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/net
DEBUG   [U=20004,P=394794] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/shub
DEBUG   [U=20004,P=394794] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/oras
VERBOSE [U=20004,P=394794] execStarter()                 Unprivileged installation: using user namespace
DEBUG   [U=20004,P=394794] execStarter()                 Checking for encrypted system partition
DEBUG   [U=20004,P=394794] Init()                        Image format detection
DEBUG   [U=20004,P=394794] Init()                        Check for sandbox image format
DEBUG   [U=20004,P=394794] Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=20004,P=394794] Init()                        Check for sif image format
DEBUG   [U=20004,P=394794] Init()                        sif image format detected
VERBOSE [U=20004,P=394794] SetContainerEnv()             Not forwarding SINGULARITY_TMPDIR from user to container environment
VERBOSE [U=20004,P=394794] SetContainerEnv()             Not forwarding SINGULARITY_MKSQUSHFS_MAX_CPUS from user to container environment
VERBOSE [U=20004,P=394794] SetContainerEnv()             Not forwarding SINGULARITY_UNSQUSHFS_MAX_CPUS from user to container environment
VERBOSE [U=20004,P=394794] SetContainerEnv()             HOME=/d2/home/lenovo/khyun
VERBOSE [U=20004,P=394794] execStarter()                 User namespace requested, convert image met_8.1.sif to sandbox
INFO    [U=20004,P=394794] execStarter()                 Convert SIF file to sandbox...
DEBUG   [U=20004,P=394794] Init()                        Image format detection
DEBUG   [U=20004,P=394794] Init()                        Check for sandbox image format
DEBUG   [U=20004,P=394794] Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=20004,P=394794] Init()                        Check for sif image format
DEBUG   [U=20004,P=394794] Init()                        sif image format detected
**FATAL   [U=20004,P=394794] execStarter()                 while extracting met_8.1.sif: root filesystem extraction failed: extract command failed: FATAL ERROR:Failed to create thread**

### What OS/distro are you running

os version: CentOS Linux 7.6.1810

### How did you install Singularity
Source
 - go 1.1.3
 - squashfs 4.4

List of things that happened in the singularity installation
1) During installation, "runtime / cgo: pthread_create_failed: Resource temporarily unavailable" occured, then installed with root account
2) After installation, "ERROR: Failed to set effective UID to 0" occurred, then --without-suid, --without-network options were added
3) After installation, "FATAL: while extracting met_8.1sif: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found" occured, then copy mksquashfs, unsquashfs to /usr/local/bin
4) Failed to create thread error when executed in user account

After writing down the task list, it seems that in step 1, the pthread error was caused by an execution error without being resolved. Can you tell me how to solve this?

**Comment by cclerget** [comment]
@kihangyoun There is a user process limit set on this machine, first check that the value returned by `ulimit -u` is not too low. Also check if the limit came from cgroups with :

`cat /sys/fs/cgroup/pids$(cat /proc/self/cgroup|grep "pids:"|cut -d ':' -f3)/pids.max`

If it returns `max` it means the limit is applied at user limit level and can be adjusted either in `/etc/security/limits.conf`, you can also look at systemd default value in `/etc/systemd/system.conf` if `DefaultLimitNPROC` is set.

If `ulimit -u` is high enough and cgroups `pids.max` return `max`, it could be the machine reaching the max number of processes, look at `cat /proc/sys/kernel/pid_max` value or maybe reached the max number of threads : `cat /proc/sys/kernel/threads-max`

**Comment by kihangyoun** [comment]
@cclerget 
First of all, thank you for your kind answer. 

As I checked a user process limit that you said, `ulimit -u` is 300 and `pids.current`(there is no pids.max) is 3025. 
But I can't sure that 300 and 3025 is high enough to run singularity and extract SIF. 

Please let me know how many process should I use is.

Kihang

**Comment by cclerget** [comment]
`300` is pretty low as processes/threads are considered, since Singularity uses Go which is multi-threaded by nature (uses 7/8 threads on average) and Singularity can also execute other multi-threaded program like `mksquashfs`/`unsquashfs`, something like between `512` and `1024` should be good but lower it is less you could execute singularity instances/per user so that's up to you regarding the usage/requirements.

**Comment by kihangyoun** [comment]
@cclerget 
Thank you for your answer.

More than 300 processes cannot be used with HPC system policies.
In this case, is there any way to use less than 300 limits?
(In a strict sense, I know this is not a Singularity issue (an issue that includes go/squashfs)).

And what I can't do with the limit 300 means I'm using 300 cpus in using that image?

**Comment by cclerget** [comment]
It also depends of the number processes/threads your account is already executing on this node,
check with `ps -uxH|wc -l`

If you are connecting on this node via ssh and just run Singularity, you shouldn't reach this limit, however `mksquashfs`/`unsquashfs` are known to use the maximum number of cpu core available, so if this node has a number of physical CPU core like 64/96 with hyperthreading enabled you may hit 300 under some conditions, by example if you are not connecting via ssh but via a graphic session which already spawned many processes to setup your session.

**Comment by kihangyoun** [comment]
@cclerget 
Thank you for your help.

I will update the current progress.
First of all, I thought the unsquashfs command is a problem then I was trying to add -p option to unsquashfs command.
I modified the code "/pkg/image/unpacker/squashfs.go" in the Singularity installation source codes.
I changed it as follows , so it's going well without any problems.

`Existing: args := []string{"-f", "-d", dest, filename}`
`Change: args := []string{**"-p","4"**,"-f", "-d", dest, filename}`

And another error occurs, and I'll tell you this part.

> Create socketpair for master communication channel
> Create RPC socketpair for communication between stage 2 and RPC server
> Create user namespace
> Create user namespace
> Failed to create user namespace: Invaild argument

I was googling to "Failed to create user namespace: Invaild argument" error and found these posts in this forum. But I think the codes that the post recommend to modify are already fixed(e2e/config/config.go, Singularity 3.5.3).

https://github.com/sylabs/singularity/issues/4883
https://github.com/sylabs/singularity/issues/4913

Please let me know how to fix or debug this problem.
Thank you.

**Comment by cclerget** [comment]
@kihangyoun You need to enable user namespaces, here the instructions https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_containers/index#user_namespaces_options

**Comment by kyuyoung-choi** [comment]
@cclerget Thank you for the response. Is there a way to make it run without enabling user namespaces? Reason to ask this is that it seems hard to get sysadmin's support.

**Comment by kihangyoun** [comment]
Hi @cclerget, @dctrud 
As you said, I want to enable user namespaces but I am using CentOS 7.6.
The instructions you recommended is for RetHat and I don't have docker (/etc/sysconfig/docker).
Please let me know more detail for CentOS.
Thank you all

**Comment by dtrudg** [comment]
CentOS is a derivative / re-build from source of Red Hat Enterprise Linux. Instructions for RHEL do apply for CentOS also.

This is what is needed:

```
# grubby --args="namespace.unpriv_enable=1" \
   --update-kernel=/boot/vmlinuz-3.10.0-693.el7.x86_64

Add a value to the user.max_user_namespaces kernel tuneable so it is set permanently as follows:

# echo "user.max_user_namespaces=15076" >> /etc/sysctl.conf
```

... but the `update-kernel` entry needs to be set appropriately for the kernel in use on the system.

@kyuyoung-choi - if Singularity is installed in unprivileged mode, without setuid, then user namespace is a requirement. We cannot work around this I am afraid.
