### ISSUE TITLE
Bind mount of /dev/shm/xxx fails with mount dev = minimal

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5170]
NB - this is a very specific low priority issue, transferred from a review comment on #5162 

### Version of Singularity:

What version of Singularity are you using? Run:

```
master
```

### Actual behavior

On master with PR #5162 applied.....

If I set mount dev to minimal and try to explictly bind in something from host /dev/shm then it doesn't work.

```
09:54 AM $ sudo singularity config global --get "mount dev"
minimal

dave@piran:~/Sylabs/Git/singularity
09:54 AM $ mkdir -p /dev/shm/bob

dave@piran:~/Sylabs/Git/singularity
09:54 AM $ singularity run -B /dev/shm/bob docker://ubuntu
INFO:    Using cached SIF image
FATAL:   container creation failed: mount /dev/shm/bob->/usr/local/var/singularity/mnt/se
```

### What OS/distro are you running

```
Fedora 31
```

### How did you install Singularity

Built from source

**Comment by dctrud** [comment]
Interesting issue...

We are picking up the Bind as a dev mount, not a bind mount... so it fails...

```
DEBUG   [U=1000,P=9055]    addSessionDevAt()             Mounting device /dev/shm/bob at /usr/local/var/singularity/mnt/session/dev/shm/bob
```

**Comment by dtrudg** [comment]
Having gone through the code for a few hours this morning it's apparent this would require significant changes to fix. We would need to recognise a `/dev/shm/xxx` bind mount, and provide a special path for the destination to be created within the `/dev/shm` `tmpfs` when were are operating under `--contain`. There's no clear way to do this that I can see. Our destination directory is created in the overlay/underlay but it's then masked by the bare tmpfs mounted over `/dev/shm`

Since this has not been raised as an issue, and binding *in* to `/dev/shm/xxx` is likely extremely unusual, I think we should drop this until it is apparent as a blocker for some use case.

Marking this as a wontfix. *but* if anyone hits this as a blocker in a workflow, please feel free to reopen.

@cclerget - happy with this as a wontfix?
