### ISSUE TITLE
http_proxy variable with authentication does'nt work building SIF 

### ISSUE THREAD

**Issue by tbouissou** [apptainer/singularity#5171]
### Version of Singularity:

```
3.5.3
```

### Expected behavior
Setting environment variable to use singularity building behinds a corporate proxy should be handle even if proxy need an authentication.    

### Actual behavior

We set http_proxy to  use Singularity behind our corporate proxy that requires authentication as follow:
````
export http_proxy="http//username:password@proxy.fqdn:port"
`````
Bootsrap failed while building with this message
````
INFO:    Starting build...
INFO:    Skipping GPG Key Import
http://mirror.centos.org/centos-6/6/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 407 - Proxy Authentication Required

````
Password used included some special characters $ or ! for exemple
We have try to replace special character with hexa (! replaced by %21 for instance) but doen't work neither so we think about an issue with proxy requiring authentication 

### Steps to reproduce this behavior

We believe that issue occurs behind proxy requiring authentication .

### What OS/distro are you running

```
CentOS Linux release 7.6.1810 (Core)

```

### How did you install Singularity

Installation from sources.

**Comment by dtrudg** [comment]
Hi @tbouissou - I've done this in the past without any issue. How are you running the build?

If you `sudo singularity build` you must set the proxy env var inside the sudo environment... you can't `export` it and then `sudo singularity build`

**Comment by dtrudg** [comment]
Also note you have a colon missing here:

```
export http_proxy="http//username:password@proxy.fqdn:port"
```

`http://`

**Comment by tbouissou** [comment]
Hello,
Problem occurs when we try to build image with root account or with user account thanks to username space in rootless mode.

Envoyé depuis mon mobile Huawei

-------- Message original --------
Objet : Re: [sylabs/singularity] http_proxy variable with authentication does'nt work building SIF (#5171)
De : David Trudgian
À : sylabs/singularity
Cc : BOUISSOU Thomas ,Mention


Hi @tbouissou<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftbouissou&data=02%7C01%7Cthomas.bouissou%40axians.com%7C8f57fb4fba934e04ed2e08d7d7e5ebff%7Ccae7d06108f340dd80c33c0b8889224a%7C0%7C0%7C637215254817241165&sdata=fZIB%2BwrxdHY77ZnpvgcjKsa7ImbcqDM6ntrekZI3CKw%3D&reserved=0> - I've done this in the past without any issue. How are you running the build?

If you sudo singularity build you must set the proxy env var inside the sudo environment... you can't export it and then sudo singularity build

**Comment by dtrudg** [comment]
Can you provide the exact `export` and `singularity build` commands you are running please?

You should censor the address, of course, if that's important.

**Comment by dtrudg** [comment]
I am able to get this working without issue, setting `http_proxy` inside the `sudo` environment:

```
dave@piran~> sudo http_proxy=http://proxy:123@localhost:3128 singularity build centos.def Sylabs/Git/singularity/examples/centos/Singularity
Build target 'centos.def' is a definition file that will be overwritten. Do you still want to overwrite? [N/y]y
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
INFO:    Skipping GPG Key Import
warning: Generating 18 missing index(es), please wait...
INFO:    Adding owner write permission to build path: /tmp/rootfs-5725e892-75f4-11ea-b2fd-e0d55e6c2d0d
INFO:    Running post scriptlet
+ echo 'Hello from inside the container'
Hello from inside the container
+ yum -y install vim-minimal
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: mirrors.raystedman.org
 * extras: repo.ialab.dsu.edu
 * updates: repos.dfw.quadranet.com
base                                                                                       | 3.6 kB  00:00:00     
extras                                                                                     | 2.9 kB  00:00:00     
updates                                                                                    | 2.9 kB  00:00:00     
(1/4): base/7/x86_64/group_gz                                                              | 165 kB  00:00:00     
(2/4): extras/7/x86_64/primary_db                                                          | 165 kB  00:00:00     
^C/4): updates/7/x86_64/primary_db         39% [============-                   ] 6.8 MB/s | 5.6 MB  00:00:01 ETA 
...
```
... and it fails as expected with the wrong password...

```
dave@piran~> sudo http_proxy=http://proxy:wrong@localhost:3128 singularity build centos.def Sylabs/Git/singularity/examples/centos/Singularity
Build target 'centos.def' is a definition file that will be overwritten. Do you still want to overwrite? [N/y]y
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
INFO:    Skipping GPG Key Import
Errors during downloading metadata for repository 'base':
  - Status code: 407 for http://mirror.centos.org/centos-7/7/os/x86_64/repodata/repomd.xml (IP: ::1)
Error: Failed to download metadata for repo 'base': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
FATAL:   While performing build: conveyor failed to get: while bootstrapping: exit status 1
```

**Comment by tbouissou** [comment]
First i set my http_proxy var in my shell environment and test it with wget 
````
[bouisst@node543 scratch]$ wget www.google.com
--2020-04-06 07:09:45--  http://www.google.com/
Resolving www.google.com (www.google.com)... 172.217.19.132, 2a00:1450:4006:80a::2004
Connecting to www.google.com (www.google.com)|172.217.19.132|:80...
failed: Connection timed out.
Connecting to www.google.com (www.google.com)|2a00:1450:4006:80a::2004|:80... failed: Address family not supported by protocol.
[bouisst@node543 scratch]$
[bouisst@node543 scratch]$ export http_proxy='http://user:password@proxy-surf.loc.xxx:8050'
[bouisst@node543 scratch]$ wget www.google.com
--2020-04-06 07:15:22--  http://www.google.com/
Resolving proxy-surf.loc.xxx (proxy-surf.loc.xxx)... xxx.xxx.xxx.xxx
Connecting to proxy-surf.loc.xxx (proxy-surf.loc.xxx)|xxx.xxx.xxx.xxx|:8050... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

    [ <=>                                                                                                                    ] 13,455      --.-K/s   in 0.003s

2020-04-06 07:15:22 (4.04 MB/s) - ‘index.html’ saved [13455]
````
http_proxy is correctly set but when I try to build image, then :
````
[bouisst@node543 scratch]$ singularity build -f test.sif /softs/rh7/singularity/templates/centos6.8_http_ext.def
INFO:    Starting build...
INFO:    Skipping GPG Key Import
http://mirror.centos.org/centos-6/6/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 407 - Proxy Authentication Required
Trying other mirror.


 One of the configured repositories failed (Linux 6 - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=base ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable base
        or
            subscription-manager repos --disable=base

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=base.skip_if_unavailable=true

failure: repodata/repomd.xml from base: [Errno 256] No more mirrors to try.
http://mirror.centos.org/centos-6/6/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 407 - Proxy Authentication Required
FATAL:   While performing build: conveyor failed to get: while bootstrapping: exit status 1
````

**Comment by tbouissou** [comment]
Could you please tell me what command is used by **yum bootstarp** method to get rpm ?

**Comment by cclerget** [comment]
@tbouissou Try with `export all_proxy='http://user:password@proxy-surf.loc.xxx:8050'`, looks like there is an issue in the way http_proxy is handled, the code set `proxy=${http_proxy}` in `yum.conf` but yum requires to put username/password separately with `proxy_username=` and `proxy_password`.

**Comment by tbouissou** [comment]
Same things happen when exporting with ``all_proxy``.
I have also try to export directly ``proxy_username`` and ``proxy_password`` but this variable seems to be ignore while boostrapping with yum, I guess that singularity doesn't handle this variable anyway.

Note that, there is no problem using ``export http_proxy='http://user:password@myproxy:port'`` variable during section ``%post``
The issues occurs only during bootstrap.

**Comment by cclerget** [comment]
> Note that, there is no problem using export http_proxy='http://user:password@myproxy:port' 

@tbouissou Yes I understood the issue, just in case did you remove exported `http_proxy` from current environment before trying with all_proxy because keeping http_proxy will set bad proxy parameters ?

```
cat > build.sh <<EOF
#!/bin/sh
unset http_proxy
export all_proxy='http://user:password@myproxy:port'
singularity build -f test.sif examples/centos/Singularity
EOF
```

**Comment by tbouissou** [comment]
You right, my  ``http_proxy`` was still set in my environment.
``unset http_proxy`` then export ``all_proxy`` get me build an image using yum from a MirrorURL behind my corporate proxy.

Thank you for the your tips.
