### ISSUE TITLE
singularity 3.5.2 error - runscript syntax error "(" unexpected

### ISSUE THREAD

**Issue by tamuanand** [apptainer/singularity#5174]
### Version of Singularity:
What version of Singularity are you using? Run:
```
$ singularity version
3.5.2+419-gcd7cb38e3
```
I  am trying to create a Singularity container image starting from the official continuumio miniconda container on Docker Hub and install some bioinformatics tools. 

**_I am doing this with the below def file called rnaseq.def_**

```
BootStrap: docker
From: continuumio/miniconda:latest
IncludeCmd: yes

%post
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# this will install all necessary packages and prepare the container
    apt-get -y update
    export PATH=/opt/conda/bin:$PATH
    conda update --all
    conda install  --yes -c bioconda \
        multiqc fastqc nextflow bbmap salmon \
        fastp
    conda clean --index-cache --tarballs --packages --yes
    mkdir /data /resources

%runscript
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# this text code will run whenever the container
# is called as an executable or with `singularity run`
function usage() {
    cat <<EOF
NAME
    rnaseq - rnaseq pipeline tools 0.1
SYNOPSIS
    rnaseq tool [tool options]
    rnaseq list
    rnaseq help
DESCRIPTION
    Singularity container with tools to build rnaseq pipeline.
EOF
}

function tools() {
    echo "conda: $(which conda)"
    echo "---------------------------------------------------------------"
    conda list
    echo "---------------------------------------------------------------"
}

arg="${1:-none}"

case "$arg" in
    none) usage; exit 1;;
    help) usage; exit 0;;
    list) tools; exit 0;;
    # just try to execute it then
    *)    $@;;
esac

%environment
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# This sets global environment variables for anything run within the container
export PATH="/opt/conda/bin:/usr/local/bin:/usr/bin:/bin:"
unset CONDA_DEFAULT_ENV
export ANACONDA_HOME=/opt/conda

```
Everything gets built correctly with no errors - shown below are the last few lines upon build using the command line **`sudo singularity build rnaseq rnaseq.def`**

```
+ mkdir /data /resources
INFO:    Adding environment to container
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete: rnaseq
```

### Expected behavior
When I run this on command line like below, it should give me the version number of the tool 

```
singularity run ./rnaseq nextflow -v
```
### Actual behavior
It gives me an error message when I try to run anything from the container - the same error crops up on any of the tools I installed. 
```
/.singularity.d/runscript: 6: /.singularity.d/runscript: Syntax error: "(" unexpected
```

![image](https://user-images.githubusercontent.com/8467214/78469847-bb043600-76f2-11ea-9cbf-cc5f0b69cad2.png)

**_What actually happend? Why was it incorrect?_**
I am able to invoke a Singularity shell and run the same command within the shell for all the tools. Everything outputs as expected 

![image](https://user-images.githubusercontent.com/8467214/78469977-b55b2000-76f3-11ea-8c60-0727d07b6e99.png)

### Steps to reproduce this behavior

How can others reproduce this issue/problem? - By following the above steps, one can reproduce the issue

### What OS/distro are you running
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

### How did you install Singularity
```
git clone https://github.com/sylabs/singularity.git && cd singularity
./mconf
cd builddir
make
sudo make install
```

Thanks in advance,

**Comment by cclerget** [comment]
@tamuanand Use syntax `name()` instead of `function name()` for shell functions, the latter is less portable. By default runscript use `/bin/sh` as default shell and IIRC conda image use busybox shell, so you need to write posix shell compatible script in `%runscript`/`%startscript`/`%test` build sections.

Also note that it's better to use `exec` to execute the final container process to avoid surprise with signal handling so :

 `*)    $@;;`

is becoming

`*)    exec "$@" ;;`

**Comment by tamuanand** [comment]
Hi @cclerget 

Thanks for your response. I will try out your suggestions and get back,

My recipe (posted in the original message) is from this NIH example - https://hpc.nih.gov/apps/singularity.html  (**_note; that is a long article, hence do a Cntrl+F for continuumio_**)  - I guess that NIH article was written sometime in 2016 and Singularity might have evolved since then.

**Comment by tamuanand** [comment]
Thanks for all the help @cclerget  I was able to use your suggestions and fix it.
