### ISSUE TITLE
What is the difference between .sif and .simg?

### ISSUE THREAD

**Issue by xuecangqiuye** [apptainer/singularity#5178]
In the 'user-guide.pdf'(page 19), only one place use  '.simg'
```sudo singularity build lolcow.simg library://sylabs-jms/testing/lolcow```
But '.sif'are used more frequently.
So what is the difference between .sif and .simg?

**Comment by xuecangqiuye** [comment]
So how do I tell if a file with .sif is a real image file without exec it?

**Comment by cclerget** [comment]
@XueCangQiuYe `.simg` was often referred in Singularity v2 for squashfs images when SIF format didn't exist, SIF image encapsulate squashfs image as container filesystem along with other data.
Now if you want to check if it's a SIF image without exec you can use `singularity sif list /image/path`, if it's not a SIF image it will return error `invalid SIF file`.

Regarding extension there is no convention, but based on documentation and Singularity versions we have :
- no extension for sandbox images
- `.img` extension for ext3 images
- `.simg` extension for squashfs images
- `.sif` extension for SIF images

**Comment by XueCangQiuYe** [comment]
Thank you for your prompt reply. I get it now.
If i use `docker save -o myimage.tar myimage` to get myimage.tar(docekr image tar file), how can I convert myimage.tar to myimage.sif? 
Use dockerfile? Is there any other way?

**Comment by xuecangqiuye** [comment]
> @XueCangQiuYe `.simg` was often referred in Singularity v2 for squashfs images when SIF format didn't exist, SIF image encapsulate squashfs image as container filesystem along with other data.
> Now if you want to check if it's a SIF image without exec you can use `singularity sif list /image/path`, if it's not a SIF image it will return error `invalid SIF file`.
> 
> Regarding extension there is no convention, but based on documentation and Singularity versions we have :
> 
> * no extension for sandbox images
> * `.img` extension for ext3 images
> * `.simg` extension for squashfs images
> * `.sif` extension for SIF images

Thank you for your prompt reply. I get it now.
If i use docker save -o myimage.tar myimage to get myimage.tar(docekr image tar file), how can I convert myimage.tar to myimage.sif?
Use dockerfile? Is there any other way?

**Comment by cclerget** [comment]
Yes you can use `singularity build image.sif docker-archive:myimage.tar` to convert it to SIF

**Comment by dtrudg** [comment]
I've opened https://github.com/sylabs/singularity-userdocs/issues/317 to correct the `.simg` to `.sif` in the documentation repository to avoid further confusion there. Thanks.
