### ISSUE TITLE
Check for setuid on the destination during configure

### ISSUE THREAD

**Issue by akkornel** [apptainer/singularity#518]
Hello!

I am running into an interesting issue with Singularity: On Ubuntu 16.10 (yakkety), when Singularity is installed to a location that has setuid disabled, then even though the entire configure/build/install process happens without errors, I got the "The feature you are requesting requires privilege you do not have." error.

You can see the problem using this asciicast: https://asciinema.org/a/6s00ibvci1qpu8ytvm02afks9

The system where I recorded the asciicast is running ZFS as the root, and suggested setup has you create individual ZFS home directory volumes with setuid disabled, for security (see https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.10-Root-on-ZFS).  As soon as I re-allowed suid, things worked.

Is it possible for `./configure` to check if the installation prefix has suid disabled, and then fail the configure process?  My suggested workaround would then be for a user to re-run `./configure` with `--disable-suid`.

**Comment by vsoch** [comment]
Hi Karl! suid is required for some of Singularity core features. You are allowed to disable it, but you will lose these features. I suggest that you install using the command detailed in the docs. http://singularity.lbl.gov/install-linux

**Comment by vsoch** [comment]
@akkornel do you have other questions? If you have resolved this issue feel free to close.

**Comment by akkornel** [comment]
Hi Vanessa!  I did use `sudo make install`, but the problem was the partition where I installed the software was mounted "nosuid", which meant even if the executable was suid, the kernel acted as if it wasn't.

This would be able to detect in code (by checking the mountpoint options), or it could be mentioned in the installation docs, but I guess it's not a big enough issue, so I'll go ahead and close.

**Comment by gmkurtzer** [comment]
Hi @akkornel,

I believe it is mentioned in the installation docs, but perhaps not clear enough. If you can point us to where it could be elaborated on (or better yet, the docs are all in a public github repo), we would be happy to help and clarify.

Also, you are right, that we could detect in the code on the mount point options, but it is a bit kludgy to iterate through getcwd() looking for mount point matches on initialization. I will keep this in the back of my head, and if get more issues with the same, I will see if we can come up with a reasonable solution.

Thanks!
Greg

**Comment by akkornel** [comment]
Thanks much @gmkurtzer!  I found what happened: I went straight to the install page at http://singularity.lbl.gov/install-linux, and totally missed the warning that appears at http://singularity.lbl.gov/admin-guide.

And yeah, iterating over the path would be really annoying.  I looked at libmount, and although it helps, it doesn't really do what's needed here.

Personally, I would be OK with process of elimination:

• IF unable to use root permissions…
• AND suid is enabled in configuration…
• AND the executable is owned by root…
• AND the executable has the suid bit set…
• THEN it's probably a block at the filesystem-level.

Or you could blame it on SELinux 8-)

**Comment by gmkurtzer** [comment]
Hi @akkornel, I added a check and appropriate warning to the development branch. Can you test by installing it to a file system mounted with `nosuid` and see if that is clearer?

Thank you!
