### ISSUE TITLE
Singularity unable to open container message

### ISSUE THREAD

**Issue by tamuanand** [apptainer/singularity#5183]
### Version of Singularity: 
3.5.3 Remote builder (where I copy paste a recipe and build) 

I used the https://cloud.sylabs.io/builder tool to build my container - the container got built successfully.  This is the page - https://cloud.sylabs.io/library/_container/5e8af943290c48bae339266b

### Expected behavior

I then did a singularity pull to get the container to my linux box

[singularity pull --arch amd64 library://tamu_anand/default/antismash:latest](url)

The container image gets downloaded -

1. I am able to see the help text and all that I had put in there when building it.
2.  I am able to ```singularity shell container``` and get inside the container, All required software is there and the databases too

### Actual behavior

When I try running a job, it fails  with message 
FATAL:   could not open image <path>/antismash_analysis.sif: failed to retrieve path for <path>/antismash_analysis.sif: 
lstat <path>/antismash_analysis.sif: no such file or directory

```
singularity exec antismash_analysis.sif antismash -c 6 --cb-general --cb-knownclusters --cb-subclusters --asf --fullhmmer --pfam2go --smcog-trees --genefinding-tool prodigal --skip-zip-file -v -d --logfile log_Y16952.log --output-dir check_output_Y16952 Y16952.fa
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

1. Download this fasta file - https://www.ncbi.nlm.nih.gov/nuccore/Y16952.3/?report=fasta 
2. Use singularity pull to download the container and execute the above command line on 

### What OS/distro are you running
```
$ cat /etc/os-release
Centos Linux 7

```
### How did you install Singularity
git clone from github

Not sure why the above error is coming when I "singularity pull a container" from something I built on the remote builder site

Interestingly, I also built the very same container on a EC2 instance and then did a scp into my Linux machine. When I try running jobs with this, everything works OK and as expected.

Thanks in advance,

**Comment by dtrudg** [comment]
Are you sure you pulled them image to `antismash_analysis.sif`? The default filename for the pull would be `antismash_latest.sif`

If I use `antismash_latest.sif`...

```
dave@piran~> singularity exec antismash_analysis.sif antismash -c 6 --cb-general --cb-knownclusters --cb-subclusters --asf --fullhmmer --pfam2go --smcog-trees --genefinding-tool prodigal --skip-zip-file -v -d --logfile log_Y16952.log --output-dir check_output_Y16952 Y16952.fa
FATAL:   could not open image /home/dave/antismash_analysis.sif: failed to retrieve path for /home/dave/antismash_analysis.sif: lstat /home/dave/antismash_analysis.sif: no such file or directory
dave@piran~> singularity exec antismash_latest.sif antismash -c 6 --cb-general --cb-knownclusters --cb-subclusters --asf --fullhmmer --pfam2go --smcog-trees --genefinding-tool prodigal --skip-zip-file -v -d --logfile log_Y16952.log --output-dir check_output_Y16952 Y16952.fa
/opt/conda/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
usage: antismash [-h] [options ..] sequence
antismash: error: Input file does not exist: Y16952.fa
```

If I pull to that, but run with the wrong filename then I get what you see

```
dave@piran~> singularity exec antismash_analysis.sif antismash -c 6 --cb-general --cb-knownclusters --cb-subclusters --asf --fullhmmer --pfam2go --smcog-trees --genefinding-tool prodigal --skip-zip-file -v -d --logfile log_Y16952.log --output-dir check_output_Y16952 Y16952.fa
FATAL:   could not open image /home/dave/antismash_analysis.sif: failed to retrieve path for /home/dave/antismash_analysis.sif: lstat /home/dave/antismash_analysis.sif: no such file or directory

```

**Comment by tamuanand** [comment]
Hi @dctrud 

Thanks for your response. I am  a newbie to Singularity as well as the remote builder

 I used this below (screenshot) to do my singularity pull - this was the exact command I used

``` 
singularity pull library://tamu_anand/default/antismash
```

![image](https://user-images.githubusercontent.com/8467214/78621377-71c9f880-7850-11ea-85b5-f2123584152c.png)


Are you suggesting I should have done

```
singularity pull library://tamu_anand/default/antismash_latest
```

**Comment by dtrudg** [comment]
> Are you suggesting I should have done
> 
> ```
> singularity pull library://tamu_anand/default/antismash_latest
> ```

No... if you `singularity pull library://tamu_anand/default/antismash` then it will pull the latest tag by default, and the file it downloads to will be `antismash_latest.sif` - so you would need to `singularity exec antismash_latest.sif ...`

It looked like instead you were doing a `singularity exec antismash_analysis.sif ...` which would be the wrong filename if you used the pull command above.

The error you are getting is the error we'd see if the wrong filename was used.

**Comment by tamuanand** [comment]
Thanks @dctrud 

I realize my mistake - I will close this
