### ISSUE TITLE
Bash prompt forced to `Singularity>`

### ISSUE THREAD

**Issue by vpenso** [apptainer/singularity#5185]
### Version of Singularity:

What version of Singularity are you using?

```
$ singularity version
3.5.2-1.1.el7
```

### Behavior

Singularity modifies the Bash prompt to `Singularity>`.

**Is it possible to prevent or disable this feature?**

Note: With Zsh a custom user defined prompt works as expected.

### Steps to reproduce this behavior

```bash
$ cat debian.def
Bootstrap: docker
From: debian
%post
apt update -y
apt install -y zsh
$ singularity build --fakeroot debian.sif debian.def
$ singularity shell debian.sif
Singularity> exit
# Bash with altered user prompt
$ singularity shell -s /bin/zsh debian.sif
# Zsh with user defined prompt
```

**Comment by cclerget** [comment]
@vpenso As bash is very often the default shell for user account, it's handled specifically to avoid confusion and made quick distinction between host shell prompt and container shell prompt, by not forcing shell prompt we end up with :

```
user@hostname:~$ # host shell
user@hostname:~$ singularity shell docker://ubuntu
user@hostname:~$ # container shell
user@hostname:~$ exit
user@hostname:~$ singularity run docker://ubuntu
user@hostname:~$ # container shell
```

Note that environment handling will change in 3.6 (release in May) where you could define a custom prompt by adding in your `$HOME/.bashrc` :

```
export SINGULARITYENV_PS1="Singularity:\w> "
```

**Comment by vpenso** [comment]
@cclerget This is exactly the point of my question in this issue. 

**Is it possible to prevent Singularity from messing around with the prompt at all!**

Following your example above: I would like to keep the `user@hostname` (original) prompt. I understand the rational behind the implementation:   

> it's handled specifically to avoid confusion and made quick distinction between host shell prompt and container shell prompt

However, more advanced user do not necessarily want this. Even if this is the default behavior, there should be a way to disable this. Either with an environment variable or a command line option.

**Comment by cclerget** [comment]
@vpenso Well there is no easy way to change it for 3.5 and below, however you could do something like this :

```
singularity exec docker://busybox cp /.singularity.d/env/99-base.sh $HOME/.singularity/99-base.sh
echo 'PS1="${SHELL_PROMPT:$PS1}" >> $HOME/.singularity/99-base.sh
echo 'export SINGULARITY_BINDPATH="$HOME/.singularity/99-base.sh:/.singularity.d/env/99-base.sh:ro"' >> ~/.bashrc
echo 'export SINGULARITYENV_SHELL_PROMPT="$PS1" >> ~/.bashrc
source ~/.bashrc
singularity shell docker://busybox
```

> However, more advanced user do not necessarily want this. Even if this is the default behavior, there should be a way to disable this. Either with an environment variable or a command line option.

It will be possible in 3.6 with `SINGULARITYENV_PS1` environment variable or with `--env` option via `--env PS1="$PS1"`

**Comment by cclerget** [comment]
Closing the issue as solved in next coming 3.6 release

**Comment by agilly** [comment]
Sorry if this is obvious, but with the new behaviour, how would I set `SINGULARITYENV_PS1` so that it uses `$SINGULARITY_NAME` from the container? I understand the point of this change, but I also think forcing the `PS1` to something static in this way is quite a bruteforce approach that's going to complicate things for a lot of users.

**Comment by nikhilweee** [comment]
@agilly What works for me right now is to escape any variable that you want to be evaluated inside the container.
```bash
SINGULARITYENV_PS1="\${$SINGULARITY_NAME}"
```
Notice the `\` used before the `$` to prevent parameter expansion.
