### ISSUE TITLE
How can I correctly call Singularity packaged inside docker

### ISSUE THREAD

**Issue by tamuanand** [apptainer/singularity#5191]
Hi

My request might be weird and my approach too ;)

I am packaging singularity inside docker and trying to call singularity using the docker run command.

One might wonder  - why this approach? Reasoning below and what I have tried so far:

1. I want to use the Nextflow workflow management tool with AWS Batch. This requires a docker container and hence I am packaging singularity inside docker

2. I have been able to successfully package singularity inside docker and I can check the singularity version by the `docker run` command
```
# my docker image is singularity:3.5.3
docker run -it --rm singularity:3.5.3 version
3.5.3
```

My last 2 lines in the Dockerfile used to package singularity are
```
WORKDIR /work
ENTRYPOINT ["/usr/local/singularity/bin/singularity"]
```

3. **_I can also successfully inspect_** the recipe/def file that I had used to build the Singularity container on the remote builder site   https://cloud.sylabs.io/builder tool  and this was mentioned in my post https://github.com/sylabs/singularity/issues/5183

```
singularity pull library://tamu_anand/default/antismash
docker run -it --rm  -v  $(pwd):/work  singularity:3.5.3 inspect -d antismash_latest.sif
```

4. When I try to do a `singularity exec antismash_latest.sif antismash --help`  from docker run like above, I get the error (see screenshot attached too) 

```
docker run -it --rm  -v  $(pwd):/work  singularity:3.5.3 exec antismash_latest.sif antismash --help
INFO:    Convert SIF file to sandbox...
ERROR  : Failed to create user namespace: Operation not permitted
```
![image](https://user-images.githubusercontent.com/8467214/78715337-43e5c200-78eb-11ea-82ae-188cf69f7896.png)

Other details:

- I am doing the above on a EC2 machine and I am root

- the EC2 machine has a different singularity version (not that it matters as regards what I want to achieve) - 3.5.2+419-gcd7cb38e3
![image](https://user-images.githubusercontent.com/8467214/78715813-edc54e80-78eb-11ea-9e4d-467f8577fe7a.png)

- the successful docker packaged singularity is 3.5.3
![image](https://user-images.githubusercontent.com/8467214/78716108-5f9d9800-78ec-11ea-899e-a08942a8b316.png)

**Comment by cclerget** [comment]
@tamuanand You need to run docker instance with `--privileged` to execute Singularity correctly inside it. I'm closing the issue as not a Singularity issue, also please prefer the Singularity mailing list https://groups.google.com/a/lbl.gov/forum/#!forum/singularity for questions and to get more attention from community. Reserve github issues when you encounter bugs within Singularity.
