### ISSUE TITLE
openMPI-Singularity container  SLURM-PMIx error 

### ISSUE THREAD

**Issue by denisbertini** [apptainer/singularity#5195]
### Version of Singularity:

What version of Singularity are you using? Run
```
$ singularity version 
version 3.5.2-1.1.el7

```
$ OpenMPI 3.1 (Host/Container)

### Expected behavior
SLURM launch MPI processes within the container without errors

On Host system:
>> yum info slurm-ohpc | egrep -i '^release|^version'
Version     : 18.08.8
Release     : 4.1.ohpc.1.3.8.1
>>> yum info pmix-ohpc | egrep -i '^release|^version'
Version     : 2.2.2
Release     : 9.1.ohpc.1.3.7

Same version within the container

### Actual behavior

What actually happend? Why was it incorrect?
Within initialisation phase,  i got PMIx error linked to GDS/dstore component  
'''
[lxbk0609:07143] PMIX ERROR: ERROR in file gds_dstore.c at line 1244
[lxbk0609:07143] PMIX ERROR: OUT-OF-RESOURCE in file gds_dstore.c at line 1017
[lxbk0609:07143] PMIX ERROR: OUT-OF-RESOURCE in file gds_dstore.c at line 2234
'''
Switching to GDS/hash component it  works without errors.
The component GDS/dstore has been introduced recently in PMIx and use shared memory segment for job info and topology.  
Is shared memory based  GDS/dstore PMIx component supported with Singularity?

**Comment by cclerget** [comment]
> Is shared memory based GDS/dstore PMIx component supported with Singularity?

It depends on how you execute Singularity, what's the command you executed ?

Also by referring to function https://github.com/openpmix/openpmix/blob/v2.1/src/mca/gds/ds12/gds_dstore.c#L1206, it looks like the computed path for the shared memory segment may not be available within the container, seems to be not in `/tmp` or `/dev/shm` (unless you used `--contain` with singularity), so that's something to determine and in the worst case you will probably need to bind the parent directory where those data are stored within the container

**Comment by denisbertini** [comment]
Hi
we used  the SLURM command srun and the execution is
'''
Singularity exec \
        --bind /etc/slurm,/var/run/munge \
        --bind /cvmfs \
   $SINGULARITY_CONTAINERS/$container_image /bin/bash
'''
Now the PMIx path you quoted  which is not /tmp or /dev/shm, could one set it as environment 
variable ? Is it PMIX_PATH_MAX from the code ?
What is the command --contain and how to use it ?




Is it the path

**Comment by cclerget** [comment]
@denisbertini Could you output value of environment variables :
- `PMIX_DSTPATH`
- `PMIX_SERVER_TMPDIR`
Instead of running singularity, just execute `env`?

And another question: are you running `srun` with `--mpi=pmix_v2` ?

**Comment by denisbertini** [comment]
@cclerget 
I used srun --mpi=pmix_v2 (default)
Now the environment variables are not set on the host system, should it be set?

**Comment by denisbertini** [comment]
trying to set this variables on the host 
PMIX_DSTPATH -> /dev/shm
did not help

**Comment by cclerget** [comment]
You should see some `PMIX_` environment variables, can you try with
`srun --mpi=pmix_v2 /usr/bin/env | grep PMIX`

**Comment by denisbertini** [comment]
Here the output from the container:
```
Singularity> srun --mpi=pmix_v2 /usr/bin/env | grep PMIX
slurmstepd: error: couldn't chdir to `/u/dbertini': No such file or directory: going to /tmp instead
SLURM_PMIX_MAPPING_SERV=(vector,(0,1,1))
PMIX_NAMESPACE=slurm.pmix.1458536.0
PMIX_RANK=0
PMIX_SERVER_URI2=pmix-server.76738;tcp4://127.0.0.1:42599
PMIX_SERVER_URI21=pmix-server.76738;tcp4://127.0.0.1:42599
PMIX_SERVER_URI=pmix-server:76738:/tmp/pmix-76738
PMIX_SERVER_URI2USOCK=pmix-server:76738:/tmp/pmix-76738
PMIX_SECURITY_MODE=native,none
PMIX_PTL_MODULE=tcp,usock
PMIX_BFROP_BUFFER_TYPE=PMIX_BFROP_BUFFER_NON_DESC
PMIX_GDS_MODULE=ds21,ds12,hash
PMIX_SERVER_TMPDIR=/var/spool/slurm/d/pmix.1458536.0/
PMIX_SYSTEM_TMPDIR=/tmp
PMIX_DSTORE_21_BASE_PATH=/var/spool/slurm/d/pmix.1458536.0//pmix_dstor_ds21_76738
PMIX_DSTORE_ESH_BASE_PATH=/var/spool/slurm/d/pmix.1458536.0//pmix_dstor_ds12_76738
```

**Comment by denisbertini** [comment]
an this is the output from the Host ( different srun ):
```
centos> srun --mpi=pmix_v2 /usr/bin/env | grep PMIX
slurmstepd: error: couldn't chdir to `/u/dbertini': No such file or directory: going to /tmp instead
SLURM_PMIX_MAPPING_SERV=(vector,(0,1,1))
PMIX_NAMESPACE=slurm.pmix.1458564.0
PMIX_RANK=0
PMIX_SERVER_URI2=pmix-server.52539;tcp4://127.0.0.1:52827
PMIX_SERVER_URI21=pmix-server.52539;tcp4://127.0.0.1:52827
PMIX_SERVER_URI=pmix-server:52539:/tmp/pmix-52539
PMIX_SERVER_URI2USOCK=pmix-server:52539:/tmp/pmix-52539
PMIX_SECURITY_MODE=native,none
PMIX_PTL_MODULE=tcp,usock
PMIX_BFROP_BUFFER_TYPE=PMIX_BFROP_BUFFER_NON_DESC
PMIX_GDS_MODULE=ds21,ds12,hash
PMIX_SERVER_TMPDIR=/var/spool/slurm/d/pmix.1458564.0/
PMIX_SYSTEM_TMPDIR=/tmp
PMIX_DSTORE_21_BASE_PATH=/var/spool/slurm/d/pmix.1458564.0//pmix_dstor_ds21_52539
PMIX_DSTORE_ESH_BASE_PATH=/var/spool/slurm/d/pmix.1458564.0//pmix_dstor_ds12_52539

```
I can see that on GDS modle ds12, ds21, and hash are activated 
and that dstore path used .var/spool/slurm in both cases ...

**Comment by cclerget** [comment]
@denisbertini Ok let's try to run Singularity by adding `/var/spool/slurm` into container with `--bind /var/spool/slurm`

**Comment by denisbertini** [comment]
It seems to work without PMIx errors messages this time, 
@cclerget thanks, look it was just a missing directory path in the container
