### ISSUE TITLE
invalid section specified: files

### ISSUE THREAD

**Issue by edocorallo** [apptainer/singularity#5196]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.4.2-1.1.el7
```

### Expected behavior

What did you expect to see when you do...?
Expected to be able to use %files section and complete the build

### Actual behavior

What actually happend? Why was it incorrect?
```
-bash-4.2$ singularity build -f test.sif test.def
FATAL:   Unable to build from test.def: while parsing definition: test.def: invalid section(s) specified: files	
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
Made a .def file as follow:
```
BootStrap: docker
From: ubuntu:18.04

%files
      	/path/to/file
```
(path/to/file is actually a valid path, i swear)
### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
Singularity was not installed by me, if necessary i can try to get informations

**Comment by cclerget** [comment]
@edocorallounibo Check it's not a unicode character issue or formatting issue if the file was edited under Windows. Delete line `%files` and rewrite it

**Comment by edocorallo** [comment]
Thank you for the rapid response.
I rewrote the line and now it works.
I'm also sorry for the dumbness of the problem, have a nice day and thank you again for your work.
