### ISSUE TITLE
singularity container startup is slow from cache

### ISSUE THREAD

**Issue by asmi10** [apptainer/singularity#5197]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ /usr/bin/singularity version
3.5.3-1
### Expected behavior

If I start singularity container using below cmd, it hangs for 7-8 seconds after below line and then starts up the container, if I do strace for this command then I find there are read system calls for file /tmp/singularity/athapliy/cache/library/sha256.5d3602080ed7a543f13c5df9b3bad3c7c619fcb3e366855db7de95817ffba45d/sles11sp4_batch.sif for approx 8 seconds. It doesn't look like if it is validating the content of cached image, it just reads it.
athapliy@:~> /usr/bin/singularity --debug run -p library://linuxset/sles11sp4:batch
DEBUG   [U=11571123,P=5749]persistentPreRunE()           Singularity version: 3.5.3-1
DEBUG   [U=11571123,P=5749]handleConfDir()               /nfs/pdx/home/athapliy/.singularity already exists. Not creating.
DEBUG   [U=11571123,P=5749]handleRemoteConf()            Ensuring file permission of 0600 on /nfs/pdx/home/athapliy/.singularity/remote.yaml
DEBUG   [U=11571123,P=5749]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/library
DEBUG   [U=11571123,P=5749]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/oci-tmp
DEBUG   [U=11571123,P=5749]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/oci
DEBUG   [U=11571123,P=5749]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/net
DEBUG   [U=11571123,P=5749]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/shub
DEBUG   [U=11571123,P=5749]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/oras
DEBUG   [U=11571123,P=5749]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/library/sha256.5d3602080ed7a543f13c5df9b3bad3c7c619fcb3e366855db7de95817ffba45d
DEBUG   [U=11571123,P=5749]updateCacheSubdir()           Caching directory set to /tmp/singularity/athapliy/cache/library/sha256.5d3602080ed7a543f13c5df9b3bad3c7c619fcb3e366855db7de95817ffba45d



### Actual behavior
If I start container directly from image then it doesn't hang and works fine.
/usr/bin/singularity run /tmp/singularity/athapliy/cache/library/sha256.5d3602080ed7a543f13c5df9b3bad3c7c619fcb3e366855db7de95817ffba45d/sles11sp4_batch.sif date
Thu Apr  9 02:39:42 PDT 2020

**Comment by cclerget** [comment]
@asmi10 When running from URI and even if the image is already cached, it connect to internet and check on cloud.sylabs.io if a more recent version of the image exists and in this case download/cache/use it in place of the previous cached image, so the slow start is explained by the communication and check with the cloud library service.

**Comment by asmi10** [comment]
I understand if there is any difference in image then it should download which would defiantly take some time. In below case I updated image in library and traced the singularity run command

here at 07:57:54 download started
[pid 15743] 07:57:54 write(2</tmp/image_chg.txt>, "\33[34mINFO    \33[0m[U=11571123,P=1"..., 93INFO    [U=11571123,P=15732]handleLibrary()               Downloading library image
 <unfinished ...>
[pid 15733] 07:57:54 <... nanosleep resumed> NULL) = 0
[pid 15743] 07:57:54 <... write resumed> ) = 93
[pid 15733] 07:57:54 nanosleep({0, 20000},  <unfinished ...>
[pid 15741] 07:59:48 write(9</tmp/singularity/athapliy/cache/library/sha256.98af0f4cac4d071175bc4f87daa845086c4cfad197a7b8592e56fc12eee0b63e/sles11_4.sif>, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 12541) =
 12541
and at 07:59:48 download gets completed which is ok.
[pid 15741] 07:59:48 close(9</tmp/singularity/athapliy/cache/library/sha256.98af0f4cac4d071175bc4f87daa845086c4cfad197a7b8592e56fc12eee0b63e/sles11_4.sif>) = 0

But the container gets started at 07:59:55, there is 7 sec delay after image download. In strace I see 
 this time is used for reading the sif file, why it is reading sif file? this is not the case if I directly give sif image path and start the container.

**Comment by dtrudg** [comment]
@asmi10 - in the code, when the download is complete I believe that we read over the entire file to compute the content hash, and compare with what the library says that should be - verifying the correct bits reached the disk.

If you run straight out of the cached SIF file then this read of the file & hash computation does not happen.

What size is the container image and what is the filesystem in use here? 7 seconds is quite a long time.

**Comment by dtrudg** [comment]
Closing as no follow-up information was provided. Please don't hesitate to re-open if you can provide requested information.
