### ISSUE TITLE
Prepheader taking excessive amount of time

### ISSUE THREAD

**Issue by nmoran** [apptainer/singularity#5198]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
2.6.0-dist
```

### Expected behavior

What did you expect to see when you do...?

Expected singularity to build an image from a docker container in a timely fashion. Using

```
singularity build cosmiq.simg docker://nmoranichec/cosmiq_sn6_baseline:master
```

### Actual behavior

What actually happend? Why was it incorrect?

Image was created successfully but took more than 4 hours (left overnight so do not know exact time). 
Downloading and exploding of layers was relatively fast but was stuck on `Building Singularity image...`. 

Looking at running processes, can see that it's the `prepheader` part that's slowing things down to a crawl which seems excessive for a reasonably modest 6.1GB image. This delay is making the use of singularity unfeasible for this use case. 

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Run the following command with singularity 2.6.0

```
singularity build cosmiq.simg docker://nmoranichec/cosmiq_sn6_baseline:master
```

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

Via centos package manager

**Comment by cclerget** [comment]
@nmoran FYI Singularity v2 doesn't receive fix and is not supported anymore. You can try with latest release of Singularity https://github.com/sylabs/singularity/releases/tag/v3.5.3 which doesn't have this issue by design.
Here the installation instruction https://github.com/sylabs/singularity/blob/v3.5.3/INSTALL.md

Regarding `prepheader`, it is using a combination of `mmap`/`memmove` to prepend a shebang string to the image, so it's possible that your machine doesn't have enough memory for the size of the image as it stores the whole image in memory due to `memmove` call leading to swapping a lot explaining why it's slow.

**Comment by nmoran** [comment]
@cclerget Thanks for your rapid response in relation to this issue. Version 3.5.3 is also installed and I have tried with version 3.5.3 and it is much quicker to build the image, however I cannot run any images due to the following error

```
FATAL:   container creation failed: unable to parse singularity.conf file: open /.../singularity/3.5.3/etc/singularity/singularity.conf: no such file or directory
```

despite the `singularity.conf` file being present at the specified path. This appears to be related to this  issue https://github.com/sylabs/singularity/issues/4774 which I don’t fully understand and do not think I can change as I do not have admin access to the machine.

> Regarding prepheader, it is using a combination of mmap/memmove to prepend a shebang string to the image, so it's possible that your machine doesn't have enough memory for the size of the image as it stores the whole image in memory due to memmove call leading to swapping a lot explaining why it's slow.

The machine I am using has 118GB of memory and does not have any swap space. The majority of the memory is free and the image file is just over 6GB so do not think swapping is the reason. The image file was originally on a network filesystem so was wondering if memory mapping from there could be a factor. 

I was wondering if it might be possible to skip this stage and maybe it's still possible to use the image, but just not as an executable image?

**Comment by cclerget** [comment]
@nmoran Yes looks like your are encountering the same issue as in #4774. You can notify admin about this issue by pointing them to #4774 thread, if they use a diskless setup for nodes then there is chance that they are not using `switch_root` to switch from the init ramdisk to the node root filesystem.

> I was wondering if it might be possible to skip this stage and maybe it's still possible to use the image, but just not as an executable image?

You can do it in two steps, first by creating a sandbox directory and by manually creating image :

```
singularity build -s cosmiq-sandbox docker://nmoranichec/cosmiq_sn6_baseline:master
mksquashfs cosmiq-sandbox/ cosmiq.simg -all-root -noappend
```

**Comment by nmoran** [comment]
@cclerget thanks again for the quick response and advice. I'll follow up with admins to work through issues with version 3.5.3.
