### ISSUE TITLE
Bad mount overlaps container CWD error, when CWD is symlink

### ISSUE THREAD

**Issue by MikeCTZA** [apptainer/singularity#5200]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3
```

### Expected behavior

What did you expect to see when you do...?

A normal container shell when we enter the container when CWD is a symlink

```mike@slwrk-401:~/idiahome$ singularity shell /idia/software/containers/casa-6.simg
Singularity>
```

### Actual behavior
```
mike@slwrk-104:~/idiahome$ singularity shell /idia/software/containers/casa-6.simg
WARNING: Bind mount '/users/mike => /users/mike' overlaps container CWD /users/mike/idiahome, may not be available
Singularity>
```
What actually happend? Why was it incorrect?

There is a bind mount error displayed.  This was OK in 3.5.2 (and it is in the .2 release notes), we then upgraded a few nodes to 3.5.3 for another fix (to mount off our cephfs vs patching the source manually) and observed this happening, so it feels like a possible regression.  Feels similar / related to issue 5069.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Create a symlink (ln -s /idia/users/mike/ idiahome) in my case
cd into the symlink you created (cd idiahome)
singularity shell (into any container elsewhere)

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

Built from source with instructions on your documentation page.

**Comment by cclerget** [comment]
@MikeCTZA It was fixed by #5114 and will be available in coming 3.6 release (around May). If you feel adventurous you can apply patch from #5114

**Comment by MikeCTZA** [comment]
Many thanks for the prompt feedback, we are happy to stick with our 3.5.2 deployment for now, I'll roll the few boxes that I tested on .3 back to .2 for now and we'll wait for 3.6 for the final fix.

**Comment by cclerget** [comment]
Ok, closing the issue
