### ISSUE TITLE
Running SUID binnaries as normal user in container (whihout fakeroot)

### ISSUE THREAD

**Issue by tbouissou** [apptainer/singularity#5201]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3

```

### Expected behavior

We wish to run as normal user an SUID binaries bind in our container.
This binaries open a system network port  under 1024. 

### Actual behavior

We got an permissions denied.

### Steps to reproduce this behavior

Run the container binding the SUID binary and try to use it.

### What OS/distro are you running

```
$cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

```

### How did you install Singularity

Singularity was installaed form sources.

**Comment by jmstover** [comment]
You cannot do this normally. Singularity uses `NO_NEW_PRIVS` to block priviledge escalation.

I believe you would need to give the user the `CAP_SETUID` capability... but that comes with its own security issues. 

@dctrud @cclerget ... I missing anything here?

**Comment by tbouissou** [comment]
We have try to use CAP_SETUID but it doesn't allow us to run suid binary inside container.
Maybe because this binary need to open a privilege network port (under 1024).


Envoyé depuis mon mobile Huawei

-------- Message original --------
Objet : Re: [sylabs/singularity] Running SUID binnaries as normal user in container (whihout fakeroot) (#5201)
De : Jason Stover
À : sylabs/singularity
Cc : BOUISSOU Thomas ,Author


You cannot do this normally. Singularity uses NO_NEW_PRIVS to block priviledge escalation.

I believe you would need to give the user the CAP_SETUID capability... but that comes with its own security issues.

@dctrud<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdctrud&data=02%7C01%7Cthomas.bouissou%40axians.com%7Cb252ab8d07ef4fa2164a08d7dc9bfa82%7Ccae7d06108f340dd80c33c0b8889224a%7C0%7C0%7C637220434785536821&sdata=rbIQ9Lg8x1P6zkJ0T%2BFeLaW%2FqrrxZqS35ClV4wrei6k%3D&reserved=0> @cclerget<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcclerget&data=02%7C01%7Cthomas.bouissou%40axians.com%7Cb252ab8d07ef4fa2164a08d7dc9bfa82%7Ccae7d06108f340dd80c33c0b8889224a%7C0%7C0%7C637220434785546815&sdata=bTwZz2X8plBomageRLOCMA%2F1TsxWYVYtzuE7ultemb0%3D&reserved=0> ... I missing anything here?

**Comment by jmstover** [comment]
If it's just about the privileged port you can try adding the `CAP_NET_BIND_SERVICE` capability.

**Comment by tbouissou** [comment]
Jason this capability works fine.
 Thanks you very much.

**Comment by GloktarFR** [comment]
Is there a way to use a SUID binary that is bind inside the container without requiring any CAPS ?
In fact, setting CAP_NET_BIND_SERVICE gives the user too much privileges, as any binary executed from inside the container will be allowed to open a port < 1024.

The goal would be to execute this SUID binary inside the container (binding it with -B), as a regular user (i.e. without fakeroot), exactly the same way that the user would execute it outside the container directly on the host.

In case you wonder, this is related to the possibility to submit PBS Pro jobs within a container.
Indeed, PBSPro uses a pbs_iff binary which opens a port < 1024.

**Comment by jmstover** [comment]
The container process is ran under `NO_NEW_PRIVS` ... so, you can't elevate you privileges here by default. Opening up the capabilities isn't an exact solution since it gives the container process the capability, which as you've noticed gives any process ran the capability since we need to assign it to the container process... which feeds down.
