### ISSUE TITLE
Singularity Desktop hangs forever on Mac Os X 10.13.6 

### ISSUE THREAD

**Issue by Trophime** [apptainer/singularity#5202]
Hi,
I'm trying to run latest singularity desktop (3.3.0-rc.1.658.g7427b73f1.dirty)
on an old Mac (iMac2010 intel i3 AtiRadeon HD) running Os X 10.13.6

Running the command line to test singularity hangs forever:
```
singularity -d run lolcow_latest.sif
DEBUG   [U=501,P=5185]     createConfDir()               /Users/christophe/.singularity already exists. Not creating.
DEBUG   [U=501,P=5185]     getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=501,P=5185]     updateCacheSubdir()           Caching directory set to /Users/christophe/.singularity/cache/library
DEBUG   [U=501,P=5185]     updateCacheSubdir()           Caching directory set to /Users/christophe/.singularity/cache/oci-tmp
DEBUG   [U=501,P=5185]     updateCacheSubdir()           Caching directory set to /Users/christophe/.singularity/cache/oci
DEBUG   [U=501,P=5185]     updateCacheSubdir()           Caching directory set to /Users/christophe/.singularity/cache/net
DEBUG   [U=501,P=5185]     updateCacheSubdir()           Caching directory set to /Users/christophe/.singularity/cache/shub
DEBUG   [U=501,P=5185]     updateCacheSubdir()           Caching directory set to /Users/christophe/.singularity/cache/oras
DEBUG   [U=501,P=5185]     getHypervisorArgs()           PCI: 4:0,virtio-9p,home=/Users/christophe
DEBUG   [U=501,P=5185]     getHypervisorArgs()           Check for sandbox image
DEBUG   [U=501,P=5185]     startVM()                     About to launch VM using: [/usr/local/libexec/singularity/vm/xhyve -A -m 1024 -c 1 -s 0:0,hostbridge -s 31,lpc -l com1,stdio -s 3,virtio-net -s 4:0,virtio-9p,home=/Users/christophe -s 2:0,ahci-hd,lolcow_latest.sif -f kexec,/usr/local/libexec//singularity/vm/syos-kernel-amd64,/usr/local/libexec//singularity/vm/initramfs_amd64.gz,console=ttyS0 quiet root=/dev/ram0 loglevel=0 sing_img_name=lolcow_latest.sif sing_user=christophe:501:20 sing_cwd=/Users/christophe singularity_action=run ipv4=dhcp msglvl=5 singularity_arguments="" singularity_binds="|home:/Users/christophe"]
rdmsr to register 0x140 on vcpu 0
                                 rdmsr to register 0x34 on vcpu 0
                                                                 IP Address: xxx.yyy.zzz.ccc
```

Note: I have installed Docker and VirtualBox on this machine. Docker is not running when I test singularity

**Comment by dtrudg** [comment]
Hi @Trophime - was Singularity Desktop installed onto 10.13.6, or was the machine updated to 10.13.6 after Singularity Desktop was installed? Thanks.

**Comment by Trophime** [comment]
The machine was updated to 10.13.6 then I installed Singularity Desktop.
I have also checked that my CPU support xhyve.

**Comment by arnaudbore** [comment]
Same for MacOS 10.14.6.

**Comment by jmstover** [comment]
When the xhyve binary is built with xcode, set is:
```
MACOSX_DEPLOYMENT_TARGET = 10.10
```

xcode can cause so many headaches though... And building the normal `./configure && make` route doesn't explicitly set anything. So... it's possible that there's a default value that the `clang` compiler is using.

@dctrud ... In the xhyve repo you can try seting in the Makefile `MACOSX_DEPLOYMENT_TARGET = 10.10` ... That _should_ set 10.10 as the oldest runnable version. I can't find what the clang compiler defaults to if it isn't set, so I'm just going to guess that they may default to whatever the build host is... which probably would have been a 10.15.x host.

*Edit:*
_But_ ... if it's outputing ... 
```
IP Address: xxx.yyy.zzz.ccc
```
Then xhyve is starting up and it would be hanging either trying to start the container, or during the container run... 

@Trophime ... Can you run:
```
singularity shell --syos lolcow_latest.sif
```
Then, once you're in the xhyve shell (`/ #` prompt), run:
```
singularity -d run /dev/sda
```

**Comment by dtrudg** [comment]
@jmstover  - I've previously verified it works on `10.12` so `10.13` and `10.14` should not be too old here. Our constraint on older versions of OSX/MacOS is `_os_unfair_lock_lock` in the compiled xhyve, and that was introduced in 10.12.

We will take a look into this further when possible. Note that Singularity Desktop for Mac is currently a beta release, and I'm afraid that fixes / support will be on a slower cycle than for Singularity on Linux while this is the case.

**Comment by dtrudg** [comment]
> Same for MacOS 10.14.6.

@arnaudbore - what is the hardware you are running on, and has Singularity Desktop never worked for you, or stopped working after an upgrade etc.

**Comment by jmstover** [comment]
As I mentined ... if they're getting the `IP Address` output there, then xhyve is starting up... That's output from the initramfs `/init` script just before it tries running singularity internally.

So, it looks like the call to xhyve is working fine... and that it's hanging somewhere on the singularity run inside the hypervisor.

-J

**Comment by dtrudg** [comment]
Closing as Singularity Desktop currently not maintained.
