### ISSUE TITLE
--fakeroot mounts home directory even if --contain is given

### ISSUE THREAD

**Issue by sloretz** [apptainer/singularity#5211]
### Version of Singularity:

```
$ singularity version
3.5.2
```

### Expected behavior

I expect none of the content of my home directory to be available inside the container when using the `--contain` option.

### Actual behavior

When both `--fakeroot` and `--contain` are given the content of my home directory is available in `/root`

### Steps to reproduce this behavior

```
$ singularity exec --contain  library://sylabsed/examples/lolcow sh -c 'ls | wc -l'
0
$ singularity exec --fakeroot --contain  library://sylabsed/examples/lolcow sh -c 'ls | wc -l'
INFO:    Convert SIF file to sandbox...
29
INFO:    Cleaning up image...
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

Source

### Additional info

If I understand correctly, it looks like the `--fakeroot` option automatically sets a custom home path to mount to `/root`.

https://github.com/sylabs/singularity/blob/4c5c507688906834799deb980a68089f57d8360c/cmd/internal/cli/actions_linux.go#L413-L416

That causes `addHomeStagingDir` to add the home directory even if `--contain` was given.
https://github.com/sylabs/singularity/blob/4c5c507688906834799deb980a68089f57d8360c/internal/pkg/runtime/engine/singularity/container_linux.go#L1582

I'm pretty sure `--fakeroot` + `--contain` mounting the home directory is a bug. The code also seems to suggest `--home` is intentionally respected even if `--contain` is given. I would have expected the opposite. I would have thought `--contain` would always take precedence, even going as far as it being an error if `--contain` and `--home` are both given.

**Comment by ivhacks** [comment]
I am having the same issue. This behavior is unintuitive and problematic.

**Comment by dtrudg** [comment]
> I'm pretty sure --fakeroot + --contain mounting the home directory is a bug. 

Agreed on this I think. We'll look into getting this sorted.

> The code also seems to suggest --home is intentionally respected even if --contain is given. I would have expected the opposite. I would have thought --contain would always take precedence, even going as far as it being an error if --contain and --home are both given.

The existing behaviour makes sense to me. There are potential reasons to use `--contain` and `--home` together. `--home` allows binding in a different (non default) directory as `$HOME` inside the container, and it's possible someone may wish to do this while still getting the minimal `/dev` and separate `/tmp` that `--contain` brings.
