### ISSUE TITLE
Containers do not inherit user umask into running process

### ISSUE THREAD

**Issue by Markus92** [apptainer/singularity#5214]
Singularity version 3.5.3, running on Ubuntu 18.04LTS with go 1.13.8; Installed from source (I can give detailed instructions if necessary).

When creating a directory, default permissions are different inside and outside the container. The used container is a basic debian container one additional package installed.

See below for example:
```
mark@turing:/BIP/_Mark$ mkdir test_outside
mark@turing:/BIP/_Mark$ singularity exec /containers/elastix.sif mkdir test_inside
mark@turing:/BIP/_Mark$ ls -lh | grep test
drwxr-xr-x  2 mark BIP    0 Apr 16 11:41 test_inside
drwxrwx---  2 mark BIP    0 Apr 16 11:40 test_outside
```

Further investigation shows that the umask inside and outside the container environment is different: outside I explicitly set it to 007, inside it is 022.

Unfortunately for my users this is a bit confusing, as they did not expect this different behavior.

### Expected/actual behavior
Expected: Container inherits umask from the outside world.

Actual: umask is set to 022 inside container.

I saw some discussion about this in #1465 with the suggestion to open a new issue, so here it is :)

Edit: I saw some workaround involving changing the environment scripts inside the containers, but I'd like to avoid this if possible.

**Comment by dtrudg** [comment]
Hi @Markus92 - I've opened a PR #5618 to address this. By default if you `singularity run/shell/exec....` the contained process will start with the host umask. A `--no-umask` flag is newly added to go back to the prior behavior of not propagating the umask and fixing it to `0022`.

On the PR thread I have commented that I only did this for actions that are *not* running under fakeroot. 

> my reasoning for not restoring the umask in the fakeroot engine, was that when you start a container as the fake root user you are explicitly not trying to act in the same way as your normal user account on the host system. You are becoming a 'different user' at least in the container view. Therefore, a standard 0022 umask makes more sense.

I'd be interested if you have an opinion on whether or not fakeroot should propagate the user umask too. Also if people in the #1465 such as @DrDaveD @thiell @gnguy have an opinion on this. Thanks!

_edit_ here's the scenario I'm thinking of with fakeroot.... Imagine I have a umask of 0027 outside on the host. I am 'fake root' in a writable sandbox, and I start creating things in e.g /usr/local/bin in my container that I'm going to let other people use later on. If my umask is 0027 in the container that may cause issues.

**Comment by dtrudg** [comment]
Reopening this one as though the PR has been merged there are some questions about behaviour under fakeroot above.

If there is comment on this we can easily make the umask behaviour the same under fakeroot as well.

**Comment by Markus92** [comment]
Thanks for the mention @dctrud and even more thanks for merging in this change!

For my usage I'd consider fakeroot a more advanced use-case that's not commonly used: my users are explicitly told to only use it when installing new packages in a sandbox as it might lead to unexpected behavior otherwise. The proposed behavior, having --fakeroot override the umask behavior, thus makes perfect sense also for the issues you mention. Great catch :)

**Comment by dtrudg** [comment]
Okay, some positive feedback here so I'll close the issue for the present.
