### ISSUE TITLE
Appending fails for shared files (macOS beta)

### ISSUE THREAD

**Issue by TimmWetzel** [apptainer/singularity#5215]
### Version of Singularity:

Singularity Desktop for macOS (Beta Release v0.1)

```
$ singularity version
3.3.0-rc.1.658.g7427b73f1.dirty
```

### Expected behavior

```
$ singularity shell --bind /private/tmp:/shared alpine-2020-03-30.sif 
Singularity> echo foo >>/tmp/file
Singularity> echo foo >>/tmp/file
```

Creating and appending to a file on a rootfs works.

### Actual behavior

```
$ singularity shell --bind /private/tmp:/shared alpine-2020-03-30.sif 
Singularity> echo foo >>/shared/file
Singularity> echo foo >>/shared/file
/bin/sh: can't create /shared/file: Operation not permitted
```

On a shared filesystem (9p), creating a file works, but appending fails.

### Steps to reproduce this behavior

See above for a minimal example with a basic container image. I actually noticed the problem during tests with nipype-based neuroimaging containers where log files were not properly written.

### What OS/distro are you running

macOS 10.14.6

```
$ uname -a
Darwin <redacted> 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64
```

### How did you install Singularity

Singularity Desktop for macOS (Beta Release v0.1), standard installer package.

**Comment by MaxvdKolk** [comment]
Currently running into this issue. Is there any known solution/workaround?

**Comment by dtrudg** [comment]
There is no work around at this time. Please also see the statement regarding Singularity Desktop:

https://sylabs.io/singularity-desktop-macos/

> 

> Please Note - Singularity Desktop for macOS is a Beta release, and has not been updated for compatibility with the new SIF signature format in Singularity 3.6.0.

> Sylabs™ is currently engaging with the community to plot a course for the future of the Mac version of Singularity. In the meantime, please be aware that the release has not received recent security and bug fixes, and should be used at your own risk.

**Comment by MaxvdKolk** [comment]
OK, clear. While unfortunate, it is understandable. It would be great to see improved Singularity support for macOS in the future!

**Comment by bjarthur** [comment]
:(
