### ISSUE TITLE
Singularity fails when run using user nobody

### ISSUE THREAD

**Issue by afortiorama** [apptainer/singularity#5228]
### Version of Singularity:

The problem is with any version, but I tested using 3.2.1 and 3.5.3

What version of Singularity are you using? Run:

```
3.5.3 and 3.2.1
```
### Expected behavior

What did you expect to see when you do...?

The container to run. 

What actually happend? Why was it incorrect?
At sites that use nobody to run the jobs on their batch system the  container fails with this error

```
Container execution failed with errors. Error code: 255
FATAL:  container creation failed: failed to add / as session directory: / already exists in layout
```
the problem is that nobody has / as home directory

### Steps to reproduce this behavior

cd /tmp
sudo -u nobody singularity shell library://alpine

### What OS/distro are you running

```
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

rpm

**Comment by dtrudg** [comment]
Hi @afortiorama  - the home dir for nobody is generally `/` so there is a conflict here mounting nobody's `$HOME` into the container... as mounting in `/` from the host will override everything in the container. As a workaround for now, you can use `--no-home`:

```
dave@piran/d/shm> getent passwd nobody
nobody:x:65534:65534:Kernel Overflow User:/:/sbin/nologin

dave@piran/d/shm> sudo -u nobody singularity shell --no-home library://alpine
INFO:    Downloading library image to tmp cache: /tmp/sbuild-tmp-cache-338443828
INFO:    Downloading library image
2.6MiB / 2.6MiB [==============================================================================] 100 % 7.5 MiB/s 0s
Singularity> 
```

**Comment by dtrudg** [comment]
Fix to avoid needing `--no-home` is merged to master and will be in the forthcoming 3.6.0 release.
