### ISSUE TITLE
When remote building a from an ubuntu docker image I cannot install more packages 

### ISSUE THREAD

**Issue by halloleo** [apptainer/singularity#5234]
I am remote building a SIF image (beacuse I am on a Mac) with the follwoing command line:

singularity build remote mycalibre.sif mycalibre.def

In the def file I use a docker library as the base.  The minimal def file looks like this:

```
Bootstrap: docker
From: linuxserver/calibre

%post
    apt-get install -y cowsay
```

After gathering the blobs and unpacking the layers the command errors out on the `apt-get install -y cowsay` line with "*E: Unable to locate package cowsay*". This happens not only with `cowsay` but with other packages like `okular` as well. (However when building without installing anything through `apt-get` the image builds fine.)

Why can't anything be installed into the image? I tried to add the _universe_ repo with `add-apt-repository universe` in the def file, but then I get a `add-apt-repository: not found` message.

### Environment:

Version of Singularity: 3.3.0 installed from dmg.
Mac OS: High Sierra

**Comment by dtrudg** [comment]
To use `add-apt-repository` you will need to first install the package `software-properties-common`. Containers are generally much lighter weight than a normal desktop installation of a Linux distro, so you will often find that things you expect to be there are not present by default.

Do a:

```
apt-get install -y software-properties-common
add-apt-repository universe
apt-get update
```

.. before you try to install cowsay.

**Comment by halloleo** [comment]
It needed 

    apt-get update

_before_ the `apt-get install -y software-properties-common` but then it worked brilliantly.

You know your stuff! Thanks a lot. :-)
