### ISSUE TITLE
Failed to create user namespace

### ISSUE THREAD

**Issue by davidjha** [apptainer/singularity#5240]
I've had no issues running our container as .sif on a university cluster. It seems that I am only able to run sandboxed containers now, since setsuid has been disabled. I can't seem to run our container, or any container on the cluster. It seems that .simg or containers ran as sandboxes should be allowed, however we're getting: ` Failed to create user namespace: Invalid argument when running sand-boxed containers.`
The system admins have said that perhaps a kernel install broke, and also have tried reinstalling singularity. The error has remained the same when trying to shell/run/exec a sand-boxed container: `Failed to create user namespace: Invalid argument`

### Version of Singularity:
```
$ singularity version
3.3.0 with setuid=no
or
3.5.2 unprivileged installation
```

### Expected behavior

singularity shell --userns container.simg/  Enter into shell for the container image.

### Actual behavior
singularity -d shell --userns container.simg

DEBUG   [U=1224408480,P=20036]createConfDir()               /home/dha5/.singularity already exits. Not creating.
DEBUG   [U=1224408480,P=20036]getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=1224408480,P=20036]updateCacheSubdir()           Caching directory set to /home/dha5/.singularity/cache/library
DEBUG   [U=1224408480,P=20036]updateCacheSubdir()           Caching directory set to /home/dha5/.singularity/cache/oci-tmp
DEBUG   [U=1224408480,P=20036]updateCacheSubdir()           Caching directory set to /home/dha5/.singularity/cache/oci
DEBUG   [U=1224408480,P=20036]updateCacheSubdir()           Caching directory set to /home/dha5/.singularity/cache/net
DEBUG   [U=1224408480,P=20036]updateCacheSubdir()           Caching directory set to /home/dha5/.singularity/cache/shub
DEBUG   [U=1224408480,P=20036]updateCacheSubdir()           Caching directory set to /home/dha5/.singularity/cache/oras
DEBUG   [U=1224408480,P=20036]execStarter()                 Use starter binary /cm/shared/apps/singularity/3.3.0/libexec/singularity/bin/starter
VERBOSE [U=1224408480,P=20036]SetContainerEnv()             HOME = /home/dha5
VERBOSE [U=1224408480,P=20036]  print()                       Set messagelevel to: 5
VERBOSE [U=1224408480,P=20036]  init()                        Starter initialization
DEBUG   [U=1224408480,P=20036]  get_pipe_exec_fd()            PIPE_EXEC_FD value: 7
VERBOSE [U=1224408480,P=20036]  is_suid()                     Check if we are running as setuid
DEBUG   [U=1224408480,P=20036]  init()                        Read engine configuration
DEBUG   [U=1224408480,P=20036]  init()                        Wait completion of stage1
DEBUG   [U=1224408480,P=20048]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1224408480,P=20048]  init()                        Spawn stage 1
VERBOSE [U=1224408480,P=20048]startup()                     Execute stage 1
DEBUG   [U=1224408480,P=20048]StageOne()                    Entering stage 1
DEBUG   [U=1224408480,P=20048]prepareFd()                   Open file descriptor for /data
DEBUG   [U=1224408480,P=20048]prepareFd()                   Open file descriptor for /cm
DEBUG   [U=1224408480,P=20048]prepareFd()                   Open file descriptor for /scratch
DEBUG   [U=1224408480,P=20048]Init()                        Entering image format intializer
DEBUG   [U=1224408480,P=20048]Init()                        Check for image format sif
DEBUG   [U=1224408480,P=20048]Init()                        sif format initializer returns: not a SIF file image
DEBUG   [U=1224408480,P=20048]Init()                        Check for image format sandbox
VERBOSE [U=1224408480,P=20036]  wait_child()                  stage 1 exited with status 0
DEBUG   [U=1224408480,P=20036]  init()                        Applying stage 1 working directory
DEBUG   [U=1224408480,P=20036]  cleanup_fd()                  Close file descriptor 4
DEBUG   [U=1224408480,P=20036]  init()                        Set child signal mask
DEBUG   [U=1224408480,P=20036]  init()                        Create socketpair for master communication channel
DEBUG   [U=1224408480,P=20036]  init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=1224408480,P=20036]  user_namespace_init()         Create user namespace
VERBOSE [U=1224408480,P=20036]  create_namespace()            Create user namespace
ERROR   [U=1224408480,P=20036]  init()                       Failed to create user namespace: Invalid argument

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

`singularity shell --userns container.simg` with setuid=no

### What OS/distro are you running

```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"

```
### How did you install Singularity

Pre-installed singularity 3.3.0 with setsuid to no.
Installed unprivileged 3.5.2 via https://sylabs.io/guides/3.5/admin-guide/installation.html#install-nonsetuid

I get the same error with both singularity 3.3.0 (pre-installed) and an unprivileged (non-root) installation of singularity 3.5.2.

**Comment by dtrudg** [comment]
If `setuid` has been disabled then unprivileged user namespace support is required, as unprivileged user namespaces are needed to then setup the mount namespace etc. that are required for a container to run.

On RHEL 7 this must be configured - and is documented by distributions, e.g. the Red Hat user guide, e.g.:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_containers/index#user_namespaces_options

```
 Add the namespace.unpriv_enable=1 option to the kernel (vmlinuz*) command line. To do this, use the grubby command as follows (replacing the exact version of vmlinuz with the one on your system):

# grubby --args="namespace.unpriv_enable=1" \
   --update-kernel=/boot/vmlinuz-3.10.0-693.el7.x86_64

Add a value to the user.max_user_namespaces kernel tuneable so it is set permanently as follows:

# echo "user.max_user_namespaces=15076" >> /etc/sysctl.conf
```

See also our admin documentation:

https://sylabs.io/guides/3.5/admin-guide/user_namespace.html

**Comment by davidjha** [comment]
Okay, Thank you. Issue was resolved.
