### ISSUE TITLE
Cannot remove key from keystore, cannot push a new one

### ISSUE THREAD

**Issue by gipert** [apptainer/singularity#5243]
### Expected behavior

1. Remove key from *remote* (cloud.sylabs.io) keystore
2. Push new key to keystore

### Actual behavior

1. I couldn't find a way to remote the key from the website or command line
2. If I try to push a new key:
```console
$ singularity key push <fingerprint>
ERROR:   push failed: key server did not accept PGP key: entity <fingerprint> does not contain identity with email 'pertoldi@pd.infn.it' (400 Bad Request)
```

Am I missing something?

### Steps to reproduce this behavior

Push a key to the keystore, then try to push a new one from command line or try to delete the exsisting.

### What OS/distro are you running

```console
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

RPM

**Comment by dtrudg** [comment]
@gipert - For the key you are pushing... does the email entered when creating the key match the email on your cloud.sylabs.io account? These are required to match when pushing to the keystore so that a user cannot push up a key that claims to be from someone else.

The error message is, agreed, not very clear here.

**Comment by gipert** [comment]
Aaaaah, I see. I usually log in with my GitHub account, I just checked my GitHub settings. There I have pertoldi@pd.infn.it as the *public* address, but also luigi.pertoldi@hotmail.it as the *primary* address. I guess it took the first one when creating an account. Good to know, I would had been happier with the other one but I can live with it. Thanks!

**Comment by gipert** [comment]
I would still be happy to remove the old one though, as I've lost the private key...

**Comment by dtrudg** [comment]
@EmmEff - are you able to comment r.e. possibility of / plans for key removal? Cheers.

**Comment by EmmEff** [comment]
At the present time, there is no mechanism to delete keys using `singularity keys`. Please email the fingerprint of the key you'd like to remove to support@sylabs.io and we will remove it for you.

**Comment by aaszodi** [comment]
This has caught me unawares as well.

> At the present time, there is no mechanism to delete keys using `singularity keys`. Please email the fingerprint of the key you'd like to remove to [support@sylabs.io](mailto:support@sylabs.io) and we will remove it for you.

A bit cumbersome, one would think. And the problems don't end here. Let me note a slightly off-topic issue:

I asked support why I cannot get an account without going through an authentication provider such as Github or Google. I was told that "we don’t maintain a credentials database, this responsibility delegated to identity providers".

This attitude keeps biting other people, such as Mr Vallee of ARM. He wrote in  [his blog entry on using Singularity on ARM64 platforms](https://community.arm.com/arm-community-blogs/b/high-performance-computing-blog/posts/signed-singularity-base-container-images-for-arm64):

> the current cloud service provided by Sylabs only supports a limited set of authentication methods that do not let me use my professional email address. 

I think the time has come that Sylabs rethink their policy of managing user identities and their cryptographic keys.
