### ISSUE TITLE
Connection Closed Error

### ISSUE THREAD

**Issue by kihangyoun** [apptainer/singularity#5244]
**singularity version : 3.5.3**

**Problem**
As @cclerget informed in https://github.com/sylabs/singularity/issues/5167#issuecomment-610330683, I wanted to try to change the configuration related to user namespace. But I could not change the option of master node but could change the options of compute node.
But when I tried to run image in remote server, the error message "Connection to remote001 closed by remote host" occur. The stage I met error is even the stage I alreay could to pass in master node.
Please let me know how to resolve the problem.

DEBUG   [U=20004,P=54831]  persistentPreRunE()           Singularity version: 3.5.3
DEBUG   [U=20004,P=54831]  handleConfDir()               /d2/home/lenovo/khyun/.singularity already exists. Not creating.
DEBUG   [U=20004,P=54831]  setValue()                    Updated flag 'tmpdir' value to: /d2/data/lenovo/khyun/AA/025_Singularity
DEBUG   [U=20004,P=54831]  getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=20004,P=54831]  updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/library
DEBUG   [U=20004,P=54831]  updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/oci-tmp
DEBUG   [U=20004,P=54831]  updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/oci
DEBUG   [U=20004,P=54831]  updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/net
DEBUG   [U=20004,P=54831]  updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/shub
DEBUG   [U=20004,P=54831]  updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/oras
VERBOSE [U=20004,P=54831]  execStarter()                 Unprivileged installation: using user namespace
DEBUG   [U=20004,P=54831]  execStarter()                 Checking for encrypted system partition
DEBUG   [U=20004,P=54831]  Init()                        Image format detection
DEBUG   [U=20004,P=54831]  Init()                        Check for sandbox image format
DEBUG   [U=20004,P=54831]  Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=20004,P=54831]  Init()                        Check for sif image format
DEBUG   [U=20004,P=54831]  Init()                        sif image format detected
VERBOSE [U=20004,P=54831]  SetContainerEnv()             Not forwarding SINGULARITY_TMPDIR from user to container environment
VERBOSE [U=20004,P=54831]  SetContainerEnv()             HOME=/d2/home/lenovo/khyun
VERBOSE [U=20004,P=54831]  execStarter()                 User namespace requested, convert image met_8.1.sif to sandbox
INFO    [U=20004,P=54831]  execStarter()                 Convert SIF file to sandbox...
DEBUG   [U=20004,P=54831]  Init()                        Image format detection
DEBUG   [U=20004,P=54831]  Init()                        Check for sandbox image format
DEBUG   [U=20004,P=54831]  Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=20004,P=54831]  Init()                        Check for sif image format
DEBUG   [U=20004,P=54831]  Init()                        sif image format detected
**Connection to duru0426 closed by remote host.
Connection to duru0426 closed.**

**Actual behavior**

DEBUG   [U=20004,P=104780] persistentPreRunE()           Singularity version: 3.5.3
DEBUG   [U=20004,P=104780] handleConfDir()               /d2/home/lenovo/khyun/.singularity already exists. Not creating.
DEBUG   [U=20004,P=104780] setValue()                    Updated flag 'tmpdir' value to: /d2/data/lenovo/khyun/AA/025_Singularity
DEBUG   [U=20004,P=104780] getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=20004,P=104780] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/library
DEBUG   [U=20004,P=104780] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/oci-tmp
DEBUG   [U=20004,P=104780] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/oci
DEBUG   [U=20004,P=104780] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/net
DEBUG   [U=20004,P=104780] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/shub
DEBUG   [U=20004,P=104780] updateCacheSubdir()           Caching directory set to /d2/home/lenovo/khyun/.singularity/cache/oras
VERBOSE [U=20004,P=104780] execStarter()                 Unprivileged installation: using user namespace
DEBUG   [U=20004,P=104780] execStarter()                 Checking for encrypted system partition
DEBUG   [U=20004,P=104780] Init()                        Image format detection
DEBUG   [U=20004,P=104780] Init()                        Check for sandbox image format
DEBUG   [U=20004,P=104780] Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=20004,P=104780] Init()                        Check for sif image format
DEBUG   [U=20004,P=104780] Init()                        sif image format detected
VERBOSE [U=20004,P=104780] SetContainerEnv()             Not forwarding SINGULARITY_TMPDIR from user to container environment
VERBOSE [U=20004,P=104780] SetContainerEnv()             HOME=/d2/home/lenovo/khyun
VERBOSE [U=20004,P=104780] execStarter()                 User namespace requested, convert image met_8.1.sif to sandbox
INFO    [U=20004,P=104780] execStarter()                 Convert SIF file to sandbox...
DEBUG   [U=20004,P=104780] Init()                        Image format detection
DEBUG   [U=20004,P=104780] Init()                        Check for sandbox image format
DEBUG   [U=20004,P=104780] Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=20004,P=104780] Init()                        Check for sif image format
DEBUG   [U=20004,P=104780] Init()                        sif image format detected
**DEBUG   [U=20004,P=104780] init()                        Use starter binary /opt/kma/kma_lib/apps/singularity/3.5.3_u/libexec/singularity/bin/starter
VERBOSE [U=20004,P=104780]  print()                       Set messagelevel to: 5
VERBOSE [U=20004,P=104780]  init()                        Starter initialization**
DEBUG   [U=20004,P=104780]  get_pipe_exec_fd()            PIPE_EXEC_FD value: 9
VERBOSE [U=20004,P=104780]  is_suid()                     Check if we are running as setuid
DEBUG   [U=20004,P=104780]  init()                        Read engine configuration
DEBUG   [U=20004,P=104780]  init()                        Wait completion of stage1
DEBUG   [U=20004,P=104820]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=20004,P=104820]  init()                        Spawn stage 1
DEBUG   [U=20004,P=104820] startup()                     singularity runtime engine selected
VERBOSE [U=20004,P=104820] startup()                     Execute stage 1
DEBUG   [U=20004,P=104820] StageOne()                    Entering stage 1
DEBUG   [U=20004,P=104820] prepareAutofs()               Found "/proc/sys/fs/binfmt_misc" as autofs mount point
DEBUG   [U=20004,P=104820] prepareAutofs()               Could not keep file descriptor for bind path /etc/localtime: no mount point
DEBUG   [U=20004,P=104820] prepareAutofs()               Could not keep file descriptor for bind path /etc/hosts: no mount point
DEBUG   [U=20004,P=104820] prepareAutofs()               Could not keep file descriptor for home directory /d2/home/lenovo/khyun: no mount point
DEBUG   [U=20004,P=104820] prepareAutofs()               Could not keep file descriptor for current working directory /d2/data/lenovo/khyun/AA/025_Singularity: no mount point
DEBUG   [U=20004,P=104820] Init()                        Image format detection
DEBUG   [U=20004,P=104820] Init()                        Check for sandbox image format
DEBUG   [U=20004,P=104820] Init()                        sandbox image format detected
DEBUG   [U=20004,P=104820] setSessionLayer()             Using underlay layer: user namespace requested
VERBOSE [U=20004,P=104780]  wait_child()                  stage 1 exited with status 0
DEBUG   [U=20004,P=104780]  init()                        Applying stage 1 working directory
DEBUG   [U=20004,P=104780]  cleanup_fd()                  Close file descriptor 4
DEBUG   [U=20004,P=104780]  cleanup_fd()                  Close file descriptor 6
DEBUG   [U=20004,P=104780]  cleanup_fd()                  Close file descriptor 7
DEBUG   [U=20004,P=104780]  init()                        Set child signal mask
DEBUG   [U=20004,P=104780]  init()                        Create socketpair for master communication channel
DEBUG   [U=20004,P=104780]  init()                        Create RPC socketpair for communication between stage 2 and RPC server
**VERBOSE [U=20004,P=104780]  user_namespace_init()         Create user namespace
VERBOSE [U=20004,P=104780]  create_namespace()            Create user namespace
ERROR   [U=20004,P=104780]  init()                        Failed to create user namespace: Invalid argument**

**What OS/distro are you running**
os version: CentOS Linux 7.6.1810

**How did you install Singularity**
Source
    go 1.1.3
    squashfs 4.4

**Comment by dtrudg** [comment]
Hello @kihangyoun - how are you connecting to your compute node here, and what is the full singularity command that you are running?

If you are running under a job scheduler, and there are limits of some kind imposed by the administrators or system then perhaps you are hitting a limit as the container is extracted? Singularity won't directly close the connection - but it will use RAM and CPU, and disk space in the extraction process - maybe one of these is exceeding some limit causing your job to be cancelled and connection closed.

If you are using a scheduler like Slurm / PBS etc on a cluster then try to use the tools (like `sacct` on Slurm) to check why the job ended.

**Comment by kihangyoun** [comment]
Hi @dctrud -
My full singularity command is below.
/${singularity_path}/bin/singularity -d run {image_name}.sif --userns

I am not running under a job scheduler, I am running singularity after access remote compute node by ssh command. By the way, I am using an IBM LSF scheduler.

I am going to find out the limits of compute node with SE team.
Let me ask one more question, How can I check the amount of resources in extraction process?
(I'd like to ask the SE team how much I should raise the limit.)

++
@dctrud 
I modified the limit of max user processes (ulimit -u) 4096 to 3093307, then the problem is fixed.

**Comment by dtrudg** [comment]
> I modified the limit of max user processes (ulimit -u) 4096 to 3093307, then the problem is fixed.

Glad to hear this.
