### ISSUE TITLE
Build based on docker image fails if TMPDIR set to a symlink

### ISSUE THREAD

**Issue by paulraines68** [apptainer/singularity#5248]
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.5.2-1.el7

```

### Expected behavior

singularity build run to completing with successful SIF file image

### Actual behavior

Build died with:

```
FATAL:   While performing build: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: set initial root time: lutimes: open parent directory: open /scratch: too many levels of symbolic links
```

Singularity should not care if TMPDIR points to a symlink as long as what it points to is a valid
writable directory for it to use

### Steps to reproduce this behavior

1. Have a /scratch symlink set to underlying real /scratch (in our case /home/scratch)
2. Set TMPDIR=/scratch
3. Run a singularity build

After setting TMPDIR=/home/scratch the build works fine

### What OS/distro are you running

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"



```

### How did you install Singularity

RPM build from distribution download using "rpmbuild -tb singularity-3.5.2.tar.gz"

**Comment by dtrudg** [comment]
This is a duplicate of the comment at: https://github.com/sylabs/singularity/issues/4631#issuecomment-577774540

This is fixed in the master branch by updating the library (umoci) that we are using to extract docker/oci layers.

Will be present in the forthcoming `3.6.0` release.
