### ISSUE TITLE
Unable to Delete Failed Builds

### ISSUE THREAD

**Issue by jlevy44** [apptainer/singularity#5252]
I've been trying to debug my own singularity build, and have been testing out a number of remote builds. For some reason, I am getting this error:
```
FATAL:   Unable to push image to library: request did not succeed: Upload would exceed quota
```
Which I believe can be circumvented by deleting old images from https://cloud.sylabs.io/builder. For some reason, I am unable to remove these images. What should I do in this case? Thanks!

**Comment by EmmEff** [comment]
@jlevy44 we have identified a bug in the accounting of deleting remote builds. For now, we have manually adjusted your account quota usage, which should allow new builds to proceed. Thank you for the feedback.

**Comment by jlevy44** [comment]
Thank you very much.

**Comment by ottino8** [comment]
I am experiencing the same a similar issue, I am not able to delete any build (completed or failed), username: ottino8
