### ISSUE TITLE
Failure building 3.6.0~rc.1 for epel8

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#5256]
### Version of Singularity:

3.6.0~rc.1

### Expected behavior

Expect to be able to build an rpm after applying a patch based on #4769 to make it compile with the golang-1.12 now available on centos8.  

### Actual behavior

The build fails with the following error:
```
GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
/bin/sh: github.com/sylabs/singularity@v0.0.0 /home/dwd/work/RPMBUILD/BUILD/singularity-3.6.0~rc.1/gopath/src/github.com/sylabs/singularity=>github.com/sylabs/singularity@v0.0.0: No such file or directory
make: *** [Makefile:171: singularity] Error 1
```

### Steps to reproduce this behavior

Apply this [patch](https://github.com/sylabs/singularity/files/4548346/4769.patch.txt) based on #4769 through this modified [singularity.spec](https://github.com/sylabs/singularity/files/4548359/singularity.spec.txt) and build an rpm.

Alternatively, download the [src rpm](https://kojipkgs.fedoraproject.org//work/tasks/6185/43886185/singularity-3.6.0%7Erc.1-1.1.el7.src.rpm) successfully made in an epel7 scratch build which includes the patch when built on el8, and attempt to rebuild with rpmbuild --rebuild.

### What OS/distro are you running

CentOS 8.1.1911

**Comment by dtrudg** [comment]
Since RHEL 8.2 has been released, and provides go 1.13 in the application streams, go 1.13 will make its way to CentOS 8.2.

Not sure exactly what we can do here until then, but we'll have a look back around later in the RC period.

**Comment by DrDaveD** [comment]
Actually I believe it has something to do with the patch, because I was just doing another build on el6 based on the source rpm and accidentally applied the patch even though it is golang-1.13, and I got the same error.

**Comment by DrDaveD** [comment]
After a discussion with @dctrud and @gmkurtzer we decided to not try to work around this problem.  Instead we will delay the epel8 build until CentOS 8.2 is released and installed on the epel8 build machine so we can have golang-1.13.  People that want 3.6.0 for a RHEL8-derived distro will in the meantime be advised to either compile from source with a locally installed golang-1.13, install the epel7 rpm which works on epel8, or use the cvmfs installation which works on all current RHEL and Debian based distros.
