### ISSUE TITLE
Building lolcow from definition files does not work when recipe file is created using visual studio code

### ISSUE THREAD

**Issue by rickstaa** [apptainer/singularity#5260]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
singularity version 3.5.2
```
### Actual behaviour

What actually happened? Why was it incorrect?

When trying to build the lolcow container from a definition file (according to the [documentation](https://sylabs.io/guides/3.5/user-guide/build_a_container.html))in ubuntu 28.04 with go version go1.14.2 linux/amd64 I get the following error:

```
FATAL:   Unable to build from lolcow.def: while parsing definition: lolcow.def: failed to parse def file header: invalid header keyword found: ﻿bootstrap
```

### Expected behaviour

What did you expect to see when you do...?

The containers should build without a problem.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

1. Create the lolcow def file:

```
Bootstrap: docker
From: ubuntu:16.04

%post
    apt-get -y update
    apt-get -y install fortune cowsay lolcat

%environment
    export LC_ALL=C
    export PATH=/usr/games:$PATH

%runscript
    fortune | cowsay | lolcat
```

2. Try to build the container using `sudo singularity build lolcow.sif lolcow.def
`.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

I installed it according to the documentation (Install from release):

```
export VERSION=3.5.2 && # adjust this as necessary \
    wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz && \
    tar -xzf singularity-${VERSION}.tar.gz && \
    cd singularity
```

**Comment by dtrudg** [comment]
We aren't aware of any issue building like this on Ubuntu 20.04, so we'll need to dig a bit further here.

How did you create the def file? Is there a chance any special / invisible characters could be in there?

Please provide the full debug output running with the `-d` option, i.e. `sudo singularity build lolcow.sif lolcow.def`

**Comment by rickstaa** [comment]
@dctrud Thanks for the speedy response. I created the def file using [visual studio code insiders](https://code.visualstudio.com/insiders/). I think it indeed was a hidden Unicode char that is not displayed correctly in vscode. I created the def file in vim, and now it seems to work.

**Comment by rickstaa** [comment]
**Update for future reference** 

I think something goes wrong when vscode creates a def file as this issue does not happen when I create a file using `touch lolcow.def` and then paste the code using vs code. @dctrud I updated the issue title to better represent the problem.
