### ISSUE TITLE
Singularity does not install via hombrew cask on macOS 10.15.4

### ISSUE THREAD

**Issue by kaneplusplus** [apptainer/singularity#5264]
### Version of Singularity:

```
$ singularity version
1.8.6,6156 of Cask
```

### Expected behavior

Singularity was installed using homebrew via:

```
> brew cask install singularity
==> Downloading https://bitbucket.org/SingularityViewer/singularityviewer/downlo
Already downloaded: /Users/mike/Library/Caches/Homebrew/downloads/5b7afc5619530b70346bb87dbb33c8d52bb1574f5c4147c51f03e2b9a98c408d--Singularity_1_8_6_6156.dmg
==> Verifying SHA-256 checksum for Cask 'singularity'.
==> Uninstalling Cask singularity
==> Backing App 'Singularity.app' up to '/usr/local/Caskroom/singularity/1.8.6,6
==> Removing App '/Applications/Singularity.app'.
==> Purging files for version 1.8.6,6156 of Cask singularity
==> Installing Cask singularity
==> Moving App 'Singularity.app' to '/Applications/Singularity.app'.
🍺  singularity was successfully installed!
```

When I open the Singularity.app application I get an error window saying:

"Singularity.app" needs to be updated.

The developer of this app needs to update it to work with this version of macOS. Contact the developer for more information.

### What OS/distro are you running?

macOS Catalina 10.15.4 (19E287)

### How did you install Singularity?

Singularity was install using homebrew cask.

**Comment by jmstover** [comment]
This "Singularity" is a SecondLife viewer... See:
https://bitbucket.org/SingularityViewer/singularityviewer/src/master/

**Comment by dtrudg** [comment]
The homebrew cask mentioned here is *not* for this project - `sylabs/singularity`

It is installing something called singularity viewer from www.singularityviewer.org

Singularity Desktop (the container runtime packaged for MacOS) is not available through homebrew.
