### ISSUE TITLE
Singularity hangs on ctrl-Z from terminal and ignores other signals with effect sent via kill

### ISSUE THREAD

**Issue by bcnwvr** [apptainer/singularity#5266]
### Version of Singularity:

What version of Singularity are you using?

Singularity 3.6.0 Release Candidate 2

### Expected behavior

What did you expect to see when you do...?

```
term1$ /opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
INFO:    Using cached SIF image
^Z
[1]+  Stopped(SIGSTOP)        /opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
term1$
```

### Actual behavior

What actually happend? Why was it incorrect?

Session hangs and cannot be killed from the same terminal.
```
term1$ /opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
INFO:    Using cached SIF image
^Z^C^\
```

The runtime parent ignores the following signals, and possibly more:
<pre>
term2$ kill -INT <i>Singularity runtime parent</i>
term2$ kill -QUIT <i>Singularity runtime parent</i>
term2$ kill -TERM <i>Singularity runtime parent</i>
term2$ kill -TSTP <i>Singularity runtime parent</i>
term2$ kill -USR1 <i>Singularity runtime parent</i>
term2$ kill -USR2 <i>Singularity runtime parent</i>
</pre>

**Other things to note:**

The runtime parent responds to ctrl-C:
```
term1$ /opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
INFO:    Using cached SIF image
^C
term1$
```
The runtime parent responds to ctrl-\\:
```
term1$ /opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
INFO:    Using cached SIF image
^\Quit
term1$
```
The runtime parent responds to SIGSTOP:
<pre>
term1$ /opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
INFO:    Using cached SIF image
term2$ kill -STOP <i>Singularity runtime parent</i>

[1]+  Stopped(SIGSTOP)        /opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
term1$
</pre>
Sending SIGSTOP after ctrl-Z seems to reset the state:
<pre>
term1$ /opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
INFO:    Using cached SIF image
^Z
term2$ kill -STOP <i>Singularity runtime parent</i>
[1]+  Stopped(SIGSTOP)        /opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
term1$ fg
/opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
^C
term1$
</pre>
However, ctrl-C sent after ctrl-Z seems to be queued:
<pre>
term1$ /opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
INFO:    Using cached SIF image
^Z^C
term2$ kill -STOP <i>Singularity runtime parent</i>
[1]+  Stopped(SIGSTOP)        /opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60
term1$ fg
/opt/singularity-3.6.0-rc.2/bin/singularity exec docker://busybox sleep 60

term1$ jobs
term1$
</pre>

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Examples above should be self explanatory.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

Source

**Comment by dtrudg** [comment]
Hi @bcnwvr - was singularity installed with default configuration options here? What was your `mconfig` command and has `singularity.conf` been modified at all?

I am unable to replicate at present. As you can see below, Ctrl-Z works as expected for me:

```
dave@piran:~/Sylabs/Git/singularity
10:53 AM $ singularity version
3.6.0-rc.2
dave@piran:~/Sylabs/Git/singularity
10:53 AM $ singularity exec docker://busybox sleep 60
^Z
[1]+  Stopped                 singularity exec docker://busybox sleep 60

```

Can you provide the install information, plus output with the `-d` debug flag? Thanks!

**Comment by bcnwvr** [comment]
Hi @dctrud.

I normally build Singularity within a CentOS 6.6 container to avoid contaminating the host and so the same binary can be used on a CentOS 7 host.  For this query, I've built in a 6.6 container on a 6.6 host and in a 7 container on a 7.3 host and then copied over the installation onto the host directories.  In both cases, I see the hang.

I ran **./mconfig --prefix=/opt/singularity-3.6.0-rc.2** and then built, installed, and then transferred the installation to the host via /tmp .  I did not modify the .singularity.conf file.

I saw #2225 which looks like it might have addressed this problem, but could not figure out where the code went in the current base.

<pre>
term1# /opt/singularity-3.6.0-rc.2/bin/singularity -d exec docker://busybox sleep 60
DEBUG   [U=0,P=3931]       persistentPreRun()            Singularity version: 3.6.0-rc.2
DEBUG   [U=0,P=3931]       persistentPreRun()            Parsing configuration file /opt/singularity-3.6.0-rc.2/etc/singularity/singularity.conf
DEBUG   [U=0,P=3931]       handleConfDir()               /root/.singularity already exists. Not creating.
DEBUG   [U=0,P=3931]       getCacheParentDir()           environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=0,P=3931]       parseURI()                    Parsing docker://busybox into reference
INFO    [U=0,P=3931]       pull()                        Using cached SIF image
DEBUG   [U=0,P=3931]       execStarter()                 Checking for encrypted system partition
DEBUG   [U=0,P=3931]       Init()                        Image format detection
DEBUG   [U=0,P=3931]       Init()                        Check for sandbox image format
DEBUG   [U=0,P=3931]       Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=3931]       Init()                        Check for sif image format
DEBUG   [U=0,P=3931]       Init()                        sif image format detected
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding XDG_SESSION_ID environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding GUESTFISH_INIT environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding HOSTNAME environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding SHELL environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding TERM environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding HISTSIZE environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding QTDIR environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding QTINC environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding QT_GRAPHICSSYSTEM_CHECKED environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding USER environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding LS_COLORS environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding SUDO_USER environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding SUDO_UID environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding USERNAME environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding GUESTFISH_PS1 environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding MAIL environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding PWD environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding LANG environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding KDEDIRS environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding GUESTFISH_OUTPUT environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding SSH_ASKPASS environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding HISTCONTROL environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding SHLVL environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding SUDO_COMMAND environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding LOGNAME environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding QTLIB environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding CVS_RSH environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding XDG_DATA_DIRS environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding LESSOPEN environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding SUDO_GID environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding DISPLAY environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding QT_PLUGIN_PATH environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding GUESTFISH_RESTORE environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding _ environment variable
DEBUG   [U=0,P=3931]       SetContainerEnv()             Forwarding USER_PATH environment variable
VERBOSE [U=0,P=3931]       SetContainerEnv()             Setting HOME=/root
VERBOSE [U=0,P=3931]       SetContainerEnv()             Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG   [U=0,P=3931]       init()                        Use starter binary /opt/singularity-3.6.0-rc.2/libexec/singularity/bin/starter
VERBOSE [U=0,P=3931]       print()                       Set messagelevel to: 5
VERBOSE [U=0,P=3931]       init()                        Starter initialization
DEBUG   [U=0,P=3931]       load_overlay_module()         Trying to load overlay kernel module
DEBUG   [U=0,P=3931]       load_overlay_module()         Overlay seems supported by the kernel
DEBUG   [U=0,P=3931]       get_pipe_exec_fd()            PIPE_EXEC_FD value: 8
VERBOSE [U=0,P=3931]       is_suid()                     Check if we are running as setuid
DEBUG   [U=0,P=3931]       init()                        Read engine configuration
DEBUG   [U=0,P=3931]       init()                        Wait completion of stage1
DEBUG   [U=0,P=3956]       set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=3956]       init()                        Spawn stage 1
DEBUG   [U=0,P=3956]       startup()                     singularity runtime engine selected
VERBOSE [U=0,P=3956]       startup()                     Execute stage 1
DEBUG   [U=0,P=3956]       StageOne()                    Entering stage 1
DEBUG   [U=0,P=3956]       prepareRootCaps()             Root full capabilities
DEBUG   [U=0,P=3956]       prepareAutofs()               Found "/proc/sys/fs/binfmt_misc" as autofs mount point
DEBUG   [U=0,P=3956]       prepareAutofs()               Found "/depotbld" as autofs mount point
DEBUG   [U=0,P=3956]       prepareAutofs()               Found "/remote" as autofs mount point
DEBUG   [U=0,P=3956]       prepareAutofs()               Found "/slowfs" as autofs mount point
DEBUG   [U=0,P=3956]       prepareAutofs()               Found "/global" as autofs mount point
DEBUG   [U=0,P=3956]       prepareAutofs()               Found "/nacbkp" as autofs mount point
DEBUG   [U=0,P=3956]       prepareAutofs()               Found "/fs" as autofs mount point
DEBUG   [U=0,P=3956]       prepareAutofs()               Found "/usr/local" as autofs mount point
DEBUG   [U=0,P=3956]       prepareAutofs()               Found "/u" as autofs mount point
DEBUG   [U=0,P=3956]       prepareAutofs()               Found "/depot" as autofs mount point
DEBUG   [U=0,P=3956]       keepAutofsMount()             Open file descriptor for /usr/share/zoneinfo/America/Los_Angeles
DEBUG   [U=0,P=3956]       prepareAutofs()               Could not keep file descriptor for bind path /etc/hosts: no mount point
DEBUG   [U=0,P=3956]       prepareAutofs()               Could not keep file descriptor for home directory /root: no mount point
DEBUG   [U=0,P=3956]       prepareAutofs()               Could not keep file descriptor for current working directory /root: no mount point
DEBUG   [U=0,P=3956]       Init()                        Image format detection
DEBUG   [U=0,P=3956]       Init()                        Check for sandbox image format
DEBUG   [U=0,P=3956]       Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=3956]       Init()                        Check for sif image format
DEBUG   [U=0,P=3956]       Init()                        sif image format detected
DEBUG   [U=0,P=3956]       setSessionLayer()             Overlay seems supported and allowed by kernel
DEBUG   [U=0,P=3956]       setSessionLayer()             Attempting to use overlayfs (enable overlay = try)
VERBOSE [U=0,P=3931]       wait_child()                  stage 1 exited with status 0
DEBUG   [U=0,P=3931]       cleanup_fd()                  Close file descriptor 4
DEBUG   [U=0,P=3931]       cleanup_fd()                  Close file descriptor 5
DEBUG   [U=0,P=3931]       cleanup_fd()                  Close file descriptor 6
DEBUG   [U=0,P=3931]       init()                        Set child signal mask
DEBUG   [U=0,P=3931]       init()                        Create socketpair for master communication channel
DEBUG   [U=0,P=3931]       init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=0,P=3931]       init()                        Spawn master process
DEBUG   [U=0,P=3962]       set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=3962]       create_namespace()            Create mount namespace
VERBOSE [U=0,P=3931]       enter_namespace()             Entering in mount namespace
DEBUG   [U=0,P=3931]       enter_namespace()             Opening namespace file ns/mnt
VERBOSE [U=0,P=3962]       create_namespace()            Create mount namespace
VERBOSE [U=0,P=3963]       init()                        Spawn RPC server
DEBUG   [U=0,P=3931]       startup()                     singularity runtime engine selected
VERBOSE [U=0,P=3931]       startup()                     Execute master process
DEBUG   [U=0,P=3963]       startup()                     singularity runtime engine selected
VERBOSE [U=0,P=3963]       startup()                     Serve RPC requests
DEBUG   [U=0,P=3931]       setupSessionLayout()          Using Layer system: overlay
DEBUG   [U=0,P=3931]       setupOverlayLayout()          Creating overlay SESSIONDIR layout
DEBUG   [U=0,P=3931]       addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=0,P=3931]       addRootfsMount()              Image type is 4096
DEBUG   [U=0,P=3931]       addRootfsMount()              Mounting block [squashfs] image: /root/.singularity/cache/oci-tmp/a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12
DEBUG   [U=0,P=3931]       addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=0,P=3931]       addKernelMount()              Adding proc to mount list
VERBOSE [U=0,P=3931]       addKernelMount()              Default mount: /proc:/proc
DEBUG   [U=0,P=3931]       addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=0,P=3931]       addKernelMount()              Adding sysfs to mount list
VERBOSE [U=0,P=3931]       addKernelMount()              Default mount: /sys:/sys
DEBUG   [U=0,P=3931]       addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=0,P=3931]       addDevMount()                 Adding dev to mount list
VERBOSE [U=0,P=3931]       addDevMount()                 Default mount: /dev:/dev
DEBUG   [U=0,P=3931]       addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=0,P=3931]       addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=0,P=3931]       addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=0,P=3931]       addHomeStagingDir()           Staging home directory (/root) at /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/root
DEBUG   [U=0,P=3931]       addHomeMount()                Adding home directory mount [/opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/root:/root] to list using layer: overlay
DEBUG   [U=0,P=3931]       addTmpMount()                 Checking for 'mount tmp' in configuration file
VERBOSE [U=0,P=3931]       addTmpMount()                 Default mount: /tmp:/tmp
VERBOSE [U=0,P=3931]       addTmpMount()                 Default mount: /var/tmp:/var/tmp
DEBUG   [U=0,P=3931]       addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=0,P=3931]       addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=0,P=3931]       addFilesMount()               Checking for 'user bind control' in configuration file
DEBUG   [U=0,P=3931]       addResolvConfMount()          Adding /etc/resolv.conf to mount list
VERBOSE [U=0,P=3931]       addResolvConfMount()          Default mount: /etc/resolv.conf:/etc/resolv.conf
DEBUG   [U=0,P=3931]       addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=0,P=3931]       create()                      Mount all
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting tmpfs to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session
DEBUG   [U=0,P=3931]       mountImage()                  Mounting loop device /dev/loop3 to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/rootfs of type squashfs
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting overlay to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final
DEBUG   [U=0,P=3931]       mountGeneric()                Remounting /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final
DEBUG   [U=0,P=3931]       setPropagationMount()         Set RPC mount propagation flag to SLAVE
VERBOSE [U=0,P=3931]       addIdentityMount()            Not updating passwd/group files, running as root!
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting /dev to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/dev
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting /etc/localtime to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/etc/localtime
DEBUG   [U=0,P=3931]       mountGeneric()                Remounting /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/etc/localtime
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting /etc/hosts to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/etc/hosts
DEBUG   [U=0,P=3931]       mountGeneric()                Remounting /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/etc/hosts
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting /proc to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/proc
DEBUG   [U=0,P=3931]       mountGeneric()                Remounting /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/proc
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting sysfs to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/sys
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting /root to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/root
DEBUG   [U=0,P=3931]       mountGeneric()                Remounting /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/root
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/root to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/root
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting /tmp to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/tmp
DEBUG   [U=0,P=3931]       mountGeneric()                Remounting /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/tmp
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting /var/tmp to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=0,P=3931]       mountGeneric()                Remounting /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=0,P=3931]       mountGeneric()                Mounting /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/etc/resolv.conf to /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final/etc/resolv.conf
DEBUG   [U=0,P=3931]       addCwdMount()                 Using /root as current working directory
VERBOSE [U=0,P=3931]       addCwdMount()                 /root found within container
DEBUG   [U=0,P=3931]       create()                      Chroot into /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final
DEBUG   [U=0,P=3963]       Chroot()                      Hold reference to host / directory
DEBUG   [U=0,P=3963]       Chroot()                      Called pivot_root on /opt/singularity-3.6.0-rc.2/var/singularity/mnt/session/final
DEBUG   [U=0,P=3963]       Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=3963]       Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=3963]       Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=3963]       Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=0,P=3931]       create()                      Chdir into / to avoid errors
VERBOSE [U=0,P=3962]       wait_child()                  rpc server exited with status 0
DEBUG   [U=0,P=3962]       apply_privileges()            Set user ID to 0
DEBUG   [U=0,P=3962]       set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=3962]       startup()                     singularity runtime engine selected
VERBOSE [U=0,P=3962]       startup()                     Execute stage 2
DEBUG   [U=0,P=3962]       StageTwo()                    Entering stage 2
DEBUG   [U=0,P=3962]       sylogBuiltin()                Sourcing /.singularity.d/env/01-base.sh
DEBUG   [U=0,P=3962]       sylogBuiltin()                Sourcing /.singularity.d/env/10-docker2singularity.sh
DEBUG   [U=0,P=3962]       sylogBuiltin()                Sourcing /.singularity.d/env/90-environment.sh
DEBUG   [U=0,P=3962]       sylogBuiltin()                Sourcing /.singularity.d/env/94-appsbase.sh
DEBUG   [U=0,P=3962]       sylogBuiltin()                Sourcing /.singularity.d/env/95-apps.sh
DEBUG   [U=0,P=3962]       sylogBuiltin()                Sourcing /.singularity.d/env/99-base.sh
DEBUG   [U=0,P=3962]       sylogBuiltin()                Sourcing /.singularity.d/env/99-runtimevars.sh
DEBUG   [U=0,P=3962]       sylogBuiltin()                Running action command exec
DEBUG   [U=0,P=3931]       PostStartProcess()            Post start process
^Z^C
term2# kill -STOP <i>Singularity runtime parent</i>
[1]+  Stopped                 /opt/singularity-3.6.0-rc.2/bin/singularity -d exec docker://busybox sleep 60
term1# fg
/opt/singularity-3.6.0-rc.2/bin/singularity -d exec docker://busybox sleep 60
DEBUG   [U=0,P=3931]       Master()                      Child exited due to signal 2

term1# 
</pre>
