### ISSUE TITLE
Cannot get latest version: module contains a go.mod file, so module path should be github.com/sylabs/singularity/v3

### ISSUE THREAD

**Issue by KateGo520** [apptainer/singularity#5268]
## Background
The `github.com/hpcng/singularity` uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release version is `v3`. And it’s module path is `"github.com/hpcng/singularity"`, instead of `"github.com/hpcng/singularity/v3"`. It must comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules
> To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of _example.com/m_ must instead use module path _example.com/m/v2_.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

## Steps to Reproduce
GO111MODULE=on, run `go get` targeting any version >= v3.2.0 of the `hpcng/singularity`:
```
$ go get github.com/hpcng/singularity@v3.5.3
go: finding github.com/hpcng/singularity v3.5.3
go: finding github.com/hpcng/singularity v3.5.3
go get github.com/hpcng/singularity@v3.5.3: github.com/hpcng/singularity@v3.5.3: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
```
SO anyone using Go modules will not be able to easily use any newer version of `hpcng/singularity`.

### 1. Kill the go.mod files, rolling back to GOPATH.
This would push them back to not being managed by Go modules (instead of incorrectly using Go modules).
Ensure compatibility for downstream module-aware projects and module-unaware projects projects

I see these dependencies in your go.mod file, which need modle awareness. So you'd better not use third-party tools(such as: Dep, glide, govendor…).
```
github.com/containers/image/v5 v5.5.1
github.com/vbauerster/mpb/v4 v4.12.2
```
You also need to update the import path to:
```
import github.com/containers/image/…
import github.com/vbauerster/mpb/…
```

### 2. Fix module path to strictly follow SIV rules.
Patch the `go.mod` file to declare the module path as `github.com/hpcng/singularity/v3` as [per the specs](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). And adjust all internal imports.
The downstream projects might be negatively affected in their building if they are module-unaware (Go versions older than 1.9.7 and 1.10.3; Or use third-party dependency management tools, such as: Dep, glide,govendor…).

If you don't want to break the above repos. This method can provides better backwards-compatibility.
Release a v2 or higher module through the major subdirectory strategy: Create a new v3 `subdirectory` (github.com/hpcng/singularity/v3) and place a new go.mod file in that subdirectory. The `module path` must end with `/v3`. Copy or move the code into the v3 subdirectory. Update `import statements` within the module to also use `/v3` (import "github.com/hpcng/singularity/v3/…"). Tag the release with `v3.x.y`.

### 3.  Suggest your downstream module users use hash instead of a version tag.
If the standard rule of go modules conflicts with your development mode. Or not intended to be used as a library and does not make any guarantees about the API. So you can’t comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. 
Regardless, since it's against one of the design choices of Go, it'll be a bit of a hack. Instead of `go get github.com/hpcng/singularity@version-tag`, module users need to use this following way to get the `hpcng/singularity`:
   (1) Search for the `tag` you want (in browser)
   (2) Get the `commit hash` for the `tag` you want
   (3) Run `go get github.com/hpcng/singularity@commit-hash`
   (4) Edit the go.mod file to put a comment about which version you actually used
This will make it difficult for module users to get and upgrade `hpcng/singularity`.

## Summary
You can make a choice to fix DM issues by balancing your own development schedules/mode against the affects on the downstream projects.

For this issue, `Solution 2` can maximize your benefits and with minimal impacts to your downstream projects the ecosystem. 

## References
* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by dtrudg** [comment]
Hi. This is a known issue that is in several of our minds. It's an unfortunate consequence of the fact that:

- 3.x is the first major version of Singularity in Go. A previous 2.x version that was not written in go exists. There's nothing earlier in go... Ideally from a go standpoint we'd be a `v1` for go and have avoided this issue in our dep -> modules transition. 

- Singularity as a project has a versioning scheme that is not semver compliant. The major version number has been related to compatibility of the container image format - and not API compatibility per semver. We don't want to break away from this scheme to semver except at point that is appropriate and clear to our users expectations under the current scheme. Changing the meanings of our version numbers would also be something done in consultation with the community in time - not as a quick implementation of the possibilities presented above.

- We moved to go modules from dep at point where an increment in major version number was not appropriate in our (non semver compatible) scheme.

We generally appreciate the clarity that the opinionated nature of go module versioning brings, and intend to work to comply with the requirements at a point which will not be disruptive to our user base. We believe Singularity is rarely imported into go projects, but the application is used by a large number of people who are used to the current meaning of the major version.

**Comment by dtrudg** [comment]
Note... if anyone needs to `go get` singularity while we are in this admittedly broken state with regard to the go module requirements you can get the appropriate release branch, which will be followed by `go get` to the commit at HEAD of the branch... e.g.:

```
dave@piran~/m> go get -u github.com/sylabs/singularity@release-3.5
go: downloading github.com/sylabs/singularity v0.0.0-20200214171539-8d88457d9bde
go: github.com/sylabs/singularity release-3.5 => v0.0.0-20200214171539-8d88457d9bde
```

Also note that as above, Singularity does not follow semver versioning wrt the API. We have a version number that is dictated by compatibility of container image usage through the `singularity` CLI at present, so there are no guarantees around API.

**Comment by KateGo520** [comment]
@dctrud  Thank you for your reply.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
