### ISSUE TITLE
Bootstrap from an image

### ISSUE THREAD

**Issue by DeepHorizons** [apptainer/singularity#527]
Is there any plan to allow bootstrapping from another image? This would allow system maintainers to create base images that people can use that would already have some software installed or system settings configured.

For example, I could have a base image `base.img` created with the following definition file:
```bash
# base.def
BootStrap: debootstrap
OSVersion: xenial
MirrorURL: http://us.archive.ubuntu.com/ubuntu/

%post
    apt-get -y update
    # Everyone needs python!
    apt-get -y install python3 python3-pip
```
Then I could use this as the starting point in another definition file
```bash
# my_image.def
BootStrap: image
ImageName: base.img

%post
    # Install my package
    pip3 install my-package
```

The children images should still need to have an image created, it should not use an overlay file system. This keeps each image as a self contained system. If you need to update the base image, the children also need to be re-built.

**Comment by truatpasteurdotfr** [comment]
Makefile:
```
my_image.img:base.img 
    cp base.img my_image.img
    sudo singularity exec -w my_image.img bash -c 'pip3 install my-package; ...'
```
otoh :P

**Comment by gmkurtzer** [comment]
Hi @DeepHorizons,

This is already supported, but differently then you mentioned. You can "re-bootstrap" an existing image and just don't include a "Bootstrap: " tag in any subsequent bootstrap definition files. For example:

```bash
$ singularity create /tmp/centos.img
$ sudo singularity bootstrap /tmp/centos.img examples/centos.def
$ cp /tmp/centos.img /tmp/my-centos.img
$ sudo singularity bootstrap /tmp/mycentos.img ~/overlay.def
```

If that satisfies your requirement, please close the issue. Thanks!

**Comment by DeepHorizons** [comment]
If I don't include a `Bootstrap:` tag, then I get the following error
```
ERROR  : Bootstrap definition file does not contain required Bootstrap: option
ERROR  : Something went wrong during build module: No such file or directory. 
```

In addition, the `/environment` file seems to be overwritten.

**Comment by gmkurtzer** [comment]
Hi @DeepHorizons,

Apologies. This is an issue we have in the master branch. It is not a problem either in the 2.x branch or the development branch. Since you are using master, I would suggest you try the development branch instead.

We will have the master branch issues resolved soon as possible!

Greg
