### ISSUE TITLE
Allow environment variables in %files section of def file

### ISSUE THREAD

**Issue by cassiersg** [apptainer/singularity#5270]
### Version of Singularity:

```
3.5.2+ds1
```

### Expected behavior

When need to copy files to an image, I can add the following to the def file:
```
%setup
    cp ${FILE_TO_COPY} ${SINGULARITY_ROOTFS}/new_file
```
This works well.

I would expect the following to be equivalent:
```
%files
    ${FILE_TO_COPY} /new_file
```

### Actual behavior

The second def file snippet produces an error, the environment variable is apparently empty. (see below for full error).

### Steps to reproduce this behavior

setup.def
```
Bootstrap: library
From: debian:10
%setup
    cp ${FILE_TO_COPY} ${SINGULARITY_ROOTFS}/new_file
```
files.def
```
Bootstrap: library
From: debian:10
%files
    ${FILE_TO_COPY} /new_file
```

```
$ echo "from foo" > foo
$ FILE_TO_COPY=foo singularity build --fakeroot setup.sif setup.def
INFO:    Starting build...
INFO:    Running setup scriptlet
+ cp foo /tmp/rootfs-fcfc6d92-8d1f-11ea-8e50-00163e318261/new_file
INFO:    Creating SIF file...
INFO:    Build complete: setup.sif
$ singularity exec setup.sif cat /new_file
from foo
$ FILE_TO_COPY=foo singularity build --fakeroot files.sif files.def
INFO:    Starting build...
INFO:    Copying ${FILE_TO_COPY} to /tmp/rootfs-2725c19f-8d20-11ea-bc1b-00163e318261/new_file
FATAL:   container creation failed: unable to copy files to container fs: while copying [] to /tmp/rootfs-2725c19f-8d20-11ea-bc1b-00163e318261/new_file: exit status 1: /bin/cp: missing destination file operand after '/tmp/rootfs-2725c19f-8d20-11ea-bc1b-00163e318261/new_file'
Try '/bin/cp --help' for more information.
FATAL:   While performing build: while running engine: while running /usr/lib/x86_64-linux-gnu/singularity/bin/starter: exit status 255
```

### What OS/distro are you running

Host: Debian buster

### How did you install Singularity

apt

**Comment by dtrudg** [comment]
Hi @cassiersg - We've been on the fence about using host environment variables in definition files in the past, but we will consider this going forward.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
