### ISSUE TITLE
add rpmprefix as option to mconfig (v3.6.0rc2 build)

### ISSUE THREAD

**Issue by tbugfinder** [apptainer/singularity#5281]
Hello,

I'd like to build RPMs setting a specific prefix.
IMHO, it would make sense to expose RPMPREFIX into `mconfig` so that I don't have to manually edit `builddir/Makefile`.

https://github.com/sylabs/singularity/blob/882f50e9228266a9e211ac8375ade8ba2654f86f/mconfig#L61

I might do it wrong though :-) 

Thanks & Best

**Comment by dtrudg** [comment]
`mconfig` will be called within the `rpmbuild` process. In the `singularity.spec` file the call to `mconfig` is setup to use the standard rpm macros.

If you `make dist` then you can `rpmbuild` against the resulting archive, and you can override macros such as `_prefix` with the `--define` option to `rpmbuild`.
