### ISSUE TITLE
 Ubuntu 20.04: no installation candidate

### ISSUE THREAD

**Issue by rolivella** [apptainer/singularity#5282]
I'm just trying to install Singularity on Ubuntu 20.04 but I can't: 

`sudo apt-get install singularity-container`
 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package singularity-container is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

Ubuntu distribution info: 

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
Thanks!

**Comment by dtrudg** [comment]
Hello. I'm afraid that we don't package the open-source for distributions directly. A distribution package maintainer would do this.

In Debian a renewed effort around packaging Singularity means that 3.5.2 is available in the testing repository, but that would take time to propagate down to a new Debian stable, and Debian derived distributions like Ubuntu.

**Comment by rkouznetsov** [comment]
I hope it will be of help to someone. The .deb from Debian sid works in my Ubuntu 20.04 like a charm (after installing some dependencies from the Ubuntu repos):

```
wget http://ftp.fi.debian.org/debian/pool/main/s/singularity-container/singularity-container_3.5.2+ds1-1_amd64.deb
sudo dpkg -i singularity-container/singularity-container_3.5.2+ds1-1_amd64.deb
```
