### ISSUE TITLE
/environment not sourced when containers built with latest development branch run in 2.2.1

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#529]
Consider the following definition file called `test.def`
```
BootStrap: docker
From: busybox:latest

%post
    echo "" >> /environment
    echo 'export BASE="this is rogue two."' >> environment
```
Let's use it to create an image called `test.img`
```
$ singularity create -F test.img && sudo singularity bootstrap test.img test.def
Initializing Singularity image subsystem
Opening image file: test.img
Creating 768MiB image
[...snip...]
```
This works. (And is lightning fast.  Awesome.)  Now to test with development branch.
```
ubuntu@ip-172-31-11-26:~$ singularity shell test.img
Singularity: Invoking an interactive shell within container...

Singularity test.img> echo $BASE
this is rogue two.
```
Awesome.  Now let's try in 2.2.1
```
$ singularity shell test.img
Singularity: Invoking an interactive shell within container...

~ $ echo $BASE

~ $ printenv | grep BASE
~ $ 
```
Doesn't seem to be working.  Doesn't look like `/environment` was not sourced at all because the prompt is `~ $`.

Let's try to manually source.
```
~ $ source /environment
Singularity test.img> echo $BASE
this is rogue two.
``` 
wurkz.  But not good for `exec` or `run` commands.

**Comment by gmkurtzer** [comment]
Hi @GodloveD,

So just to clarify... the image created with the development branch is not working on Singularity 2.2* as you would expect. If so I think I know why that is.

Greg

**Comment by gmkurtzer** [comment]
Hi @GodloveD,

I was able to replicate and I pushed a fix. Can you test [development a2df7c0]?

Thanks!

**Comment by chrisgorgo** [comment]
Good catch! Backward compatibility of containers created across various
versions of Singularity is very important (well until 3.0). Maybe there
should be some tests for that?

**Comment by gmkurtzer** [comment]
I agree @chrisfilo, but hard to test without building/installing two different versions of Singularity side by side. Hopefully this shouldn't be an ongoing issue, but having a test would certainly be useful. Thoughts?

**Comment by GodloveD** [comment]
Tested  https://github.com/singularityware/singularity/commit/a2df7c02018be107bc3a61267281ab152528f8c2 and I can verify that it is now working as expected.  Thanks!  Feel free to close.  

Also, I like @chrisfilo 's idea!  And yes I think it would necessitate installing 2 versions of Singularity side by side.  But that shouldn't be too hard right?  I'm not an travis/unit testing expert, but I think I could work on this a bit.

**Comment by gmkurtzer** [comment]
Thanks, and I will look into the legacy testing.
