### ISSUE TITLE
3.6.0 File-System Binding Limits

### ISSUE THREAD

**Issue by marshall-adrian** [apptainer/singularity#5291]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.6.0-RC2
```

### Expected behavior
I am just curious if I was to bind around 20-30 file systems or more would this degrade performance or have any other negative consequences that I should be aware of?

### What OS/distro are you running

```
$ cat /etc/os-release
Ubuntu 16.04

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
Source

**Comment by jmstover** [comment]
I think kernel 4.[something] the limit is 100K mounts.  At 20-30 you shouldn't even notice it. You can get hundreds of mounts if you have automounter doing stuff on servers (i.e. homes being "automounted" in on login server... Ugh).

**Comment by dtrudg** [comment]
100K per mount namespace - so each container (in a separate mount namespace) counts separately.

https://github.com/torvalds/linux/commit/d29216842a85
