### ISSUE TITLE
Power9 build failed

### ISSUE THREAD

**Issue by Mon-ius** [apptainer/singularity#5292]
I am currently working on IBM power9. I cannot build the --writeable image with sanbox because I am not the root. However, when I use the https://cloud.sylabs.io/builder to build from my .def file. The output image is X86_64 which cannot be used on power9.

**Comment by Mon-ius** [comment]
When I tried to build the image. 
`singularity build --remote test test.def`
build (5ebdc96990b784c737d0aa6f) cancelled due to unavailable arch (ppc64le)

**Comment by dtrudg** [comment]
> unavailable arch (ppc64le)

The free cloud service does not support builds on POWER. Only for amd64.

**Comment by Mon-ius** [comment]
Do u provide the payment cloud service for POWER?

**Comment by dtrudg** [comment]
Hello. The cloud service is provided by [Sylabs](https://sylabs.io). As this repository is within a community organization for the open-source project we ask that you contact us directly with any questions.
