### ISSUE TITLE
If you call sync in a container does it trigger a sync in the host system?

### ISSUE THREAD

**Issue by vladdoster** [apptainer/singularity#5296]
### Version of Singularity:

What version of Singularity are you using? Run:

```
[vlad@callisto ~]$ singularity --version
singularity version 3.5.3
```

### Expected behavior

What did you expect to see when you do...?
If no volumes are mounted the syscall would not be propagated up to the container host which would sync all users buffers?

### Actual behavior

What actually happend? Why was it incorrect?
The container executed `sync` syscall which started flushing data for all users on cluster.

### Steps to reproduce this behavior
Using [GATK](https://gatk.broadinstitute.org/hc/en-us) it seems that if the software calls the `sync` syscall that it is the propogated up and executed by the host (cluster node)? 

1. If we were running this on a HPC, would it need to flush data for all users on the cluster? Is there some way to avoid this?

2. Does `singularity` call sync when killing a container? 

I see that you can limit syscalls but it seems that it might hurt software running if it can not use a certain syscall.

If this is the case, would be be better off have a `singularity` only slurm queue?

Apologies if this a bad question, but trying to better understanding of Singularity internals. 

How can others reproduce this issue/problem?
N/A

### What OS/distro are you running
```
[vlad@callisto ~]$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
### How did you install Singularity
`source`

**Comment by dtrudg** [comment]
Containers are using the same kernel as the host, so there isn't really propagation of syscalls - they directly reach the kernel. If you want to block something, then you would need to impose a filter on the contained process.

Even on other container runtimes that impose seccomp profiles by default, the don't generally filter the `sync, syncfs, fsync, and fdatasync ` calls which are what are happening when you invoke `sync`.

https://www.gnu.org/software/coreutils/manual/html_node/sync-invocation.html#sync-invocation
https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile
https://github.com/moby/moby/blob/master/profiles/seccomp/default.json

**Comment by vladdoster** [comment]
> Containers are using the same kernel as the host, so there isn't really propagation of syscalls - they directly reach the kernel. If you want to block something, then you would need to impose a filter on the contained process.
> 
> Even on other container runtimes that impose seccomp profiles by default, the don't generally filter the `sync, syncfs, fsync, and fdatasync ` calls which are what are happening when you invoke `sync`.
> 
> https://www.gnu.org/software/coreutils/manual/html_node/sync-invocation.html#sync-invocation
> https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile
> https://github.com/moby/moby/blob/master/profiles/seccomp/default.json

Thank you for the response @dctrud ! Very helpful.

So when you tear down a container how does it ensure the in memory runtime dumps everything out to disk? This question might be a bit vague so no worries if not able to answer.

**Comment by dtrudg** [comment]
Hi @vladdoster. Processes running in a container are just like other processes - how and when they write data to disk is not any different.

There isn't any more 'state' in memory than if you are running things outside of a container.

For general discussions / questions about containers, rather than specific issues with singularity. I'd recommend using the mailing list or slack channel. More people will see your questions, and there is likely to be a more complete discussion.

Google Group / Mailing List: https://groups.google.com/a/lbl.gov/forum/??sdf%7Csort:date#!forum/singularity
Slack: https://bit.ly/2m0g3lX
