### ISSUE TITLE
Non-sudo user runtime error(Failed to CleanupContainer)

### ISSUE THREAD

**Issue by kihangyoun** [apptainer/singularity#5298]
**What OS/distro are you running**

OS version: CentOS Linux 7.6.1810
singularity version : 3.5.3

**Problem**

In the process of running the sif image, it works well when tested with the root user, but when executed in the user account, the following error occurs in CleanupContainer steps.
I would like to know the way I remove the container image that I used.

DEBUG   [U=20004,P=15473]  apply_container_privileges()  Set user ID to 20004
DEBUG   [U=20004,P=15473]  set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=20004,P=15473]  startup()                     singularity runtime engine selected
VERBOSE [U=20004,P=15473]  startup()                     Execute stage 2
DEBUG   [U=20004,P=15473]  StageTwo()                    Entering stage 2
DEBUG   [U=20004,P=15396]  PostStartProcess()            Post start process
Singularity> ... Command Windows ...
Singularity> exit
VERBOSE [U=20004,P=15396]  CleanupContainer()            Removing image ${PWD}/rootfs-239994430
INFO    [U=20004,P=15396]  CleanupContainer()            Cleaning up image...
_**ERROR   [U=20004,P=15396]  CleanupContainer()            failed to delete container image ${PWD}/rootfs-239994430: unlinkat ${PWD}/rootfs-239994430/root/.tcshrc: permission denied**_
DEBUG   [U=20004,P=15396]  Master()                      Child exited with exit status 2

**Others**

_I would like to perform Singularity at once by running Singularity without interactive use.
Because instead of directly accessing the compute nodes, it's to throw the work with a job scheduler.
Ex) singularity -d run image.sif "commands; exit"
Could you recommend which documents to refer to check on this grammar?_
The way I wanted is below(It is so simple, sorry;)
**singularity exec image.sif sh script.sh**

Thank you in advance.
Best Regards,
Kihang

**Comment by kihangyoun** [comment]
https://github.com/hpcng/singularity/issues/4263
I think it's a permission issue like @treydock in the thread above. After changing the permission of a folder that was not deleted in the command window, it was deleted without problems. 
Now the question is how can I change the permission while doing the cleanup that is done at the end of singularity.

**Comment by dtrudg** [comment]
Are you able to provide information about the container you are running here - the full singularity command you are running, and debug output from `singularity -d ...` please?

Thanks

**Comment by kihangyoun** [comment]
Hi dctrud,
Thank you for your interest.

1) Build options
./mconfig --prefix=$idir --without-suid --without-network

2) Command
export PWD=`pwd`
SINGULARITY_TMPDIR=$PWD TMPDIR=$PWD singularity -dv exec met_8.1.sif sh script.sh

3) Scipt.sh
ls -l /usr/local/bin
ls -l /usr/local/lib

3) Result
Currently Loaded Modulefiles:
  1) go/1.13             2) squashfs/4.4        3) singularity/3.5.3
DEBUG   [U=20004,P=188776] persistentPreRunE()           Singularity version: 3.5.3
DEBUG   [U=20004,P=188776] handleConfDir()               /Home_Directory/.singularity already exists. Not creating.
DEBUG   [U=20004,P=188776] setValue()                    Updated flag 'tmpdir' value to: /My_Directory
DEBUG   [U=20004,P=188776] getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=20004,P=188776] updateCacheSubdir()           Caching directory set to /Home_Directory/.singularity/cache/library
DEBUG   [U=20004,P=188776] updateCacheSubdir()           Caching directory set to /Home_Directory/.singularity/cache/oci-tmp
DEBUG   [U=20004,P=188776] updateCacheSubdir()           Caching directory set to /Home_Directory/.singularity/cache/oci
DEBUG   [U=20004,P=188776] updateCacheSubdir()           Caching directory set to /Home_Directory/.singularity/cache/net
DEBUG   [U=20004,P=188776] updateCacheSubdir()           Caching directory set to /Home_Directory/.singularity/cache/shub
DEBUG   [U=20004,P=188776] updateCacheSubdir()           Caching directory set to /Home_Directory/.singularity/cache/oras
VERBOSE [U=20004,P=188776] execStarter()                 Unprivileged installation: using user namespace
DEBUG   [U=20004,P=188776] execStarter()                 Checking for encrypted system partition
DEBUG   [U=20004,P=188776] Init()                        Image format detection
DEBUG   [U=20004,P=188776] Init()                        Check for sandbox image format
DEBUG   [U=20004,P=188776] Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=20004,P=188776] Init()                        Check for sif image format
DEBUG   [U=20004,P=188776] Init()                        sif image format detected
VERBOSE [U=20004,P=188776] SetContainerEnv()             Not forwarding SINGULARITY_TMPDIR from user to container environment
VERBOSE [U=20004,P=188776] SetContainerEnv()             HOME=/Home_Directory
VERBOSE [U=20004,P=188776] execStarter()                 User namespace requested, convert image met_8.1.sif to sandbox
INFO    [U=20004,P=188776] execStarter()                 Convert SIF file to sandbox...
DEBUG   [U=20004,P=188776] Init()                        Image format detection
DEBUG   [U=20004,P=188776] Init()                        Check for sandbox image format
DEBUG   [U=20004,P=188776] Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=20004,P=188776] Init()                        Check for sif image format
DEBUG   [U=20004,P=188776] Init()                        sif image format detected
DEBUG   [U=20004,P=188776] init()                        Use starter binary /Singularity_Directory/libexec/singularity/bin/starter
VERBOSE [U=20004,P=188776]  print()                       Set messagelevel to: 5
VERBOSE [U=20004,P=188776]  init()                        Starter initialization
DEBUG   [U=20004,P=188776]  get_pipe_exec_fd()            PIPE_EXEC_FD value: 9
VERBOSE [U=20004,P=188776]  is_suid()                     Check if we are running as setuid
DEBUG   [U=20004,P=188776]  init()                        Read engine configuration
DEBUG   [U=20004,P=188776]  init()                        Wait completion of stage1
DEBUG   [U=20004,P=188894]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=20004,P=188894]  init()                        Spawn stage 1
DEBUG   [U=20004,P=188894] startup()                     singularity runtime engine selected
VERBOSE [U=20004,P=188894] startup()                     Execute stage 1
DEBUG   [U=20004,P=188894] StageOne()                    Entering stage 1
DEBUG   [U=20004,P=188894] prepareAutofs()               Found "/proc/sys/fs/binfmt_misc" as autofs mount point
DEBUG   [U=20004,P=188894] prepareAutofs()               Could not keep file descriptor for bind path /etc/localtime: no mount point
DEBUG   [U=20004,P=188894] prepareAutofs()               Could not keep file descriptor for bind path /etc/hosts: no mount point
DEBUG   [U=20004,P=188894] prepareAutofs()               Could not keep file descriptor for home directory /Home_Directory: no mount point
DEBUG   [U=20004,P=188894] prepareAutofs()               Could not keep file descriptor for current working directory /My_Directory: no mount point
DEBUG   [U=20004,P=188894] Init()                        Image format detection
DEBUG   [U=20004,P=188894] Init()                        Check for sandbox image format
DEBUG   [U=20004,P=188894] Init()                        sandbox image format detected
DEBUG   [U=20004,P=188894] setSessionLayer()             Using underlay layer: user namespace requested
VERBOSE [U=20004,P=188776]  wait_child()                  stage 1 exited with status 0
DEBUG   [U=20004,P=188776]  init()                        Applying stage 1 working directory
DEBUG   [U=20004,P=188776]  cleanup_fd()                  Close file descriptor 4
DEBUG   [U=20004,P=188776]  cleanup_fd()                  Close file descriptor 6
DEBUG   [U=20004,P=188776]  cleanup_fd()                  Close file descriptor 7
DEBUG   [U=20004,P=188776]  init()                        Set child signal mask
DEBUG   [U=20004,P=188776]  init()                        Create socketpair for master communication channel
DEBUG   [U=20004,P=188776]  init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=20004,P=188776]  user_namespace_init()         Create user namespace
VERBOSE [U=20004,P=188776]  create_namespace()            Create user namespace
VERBOSE [U=65534,P=188776]  init()                        Spawn master process
DEBUG   [U=65534,P=188776]  setup_userns_mappings()       Write deny to setgroups file
DEBUG   [U=65534,P=188776]  setup_userns_mappings()       Write to GID map
DEBUG   [U=65534,P=188776]  setup_userns_mappings()       Write to UID map
DEBUG   [U=20004,P=188901]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=20004,P=188901]  create_namespace()            Create mount namespace
VERBOSE [U=20004,P=188776]  enter_namespace()             Entering in mount namespace
DEBUG   [U=20004,P=188776]  enter_namespace()             Opening namespace file ns/mnt
DEBUG   [U=20004,P=188776]  setns()                       Using syscall() wrapped __NR_setns
VERBOSE [U=20004,P=188901]  create_namespace()            Create mount namespace
DEBUG   [U=20004,P=188902]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=20004,P=188902]  init()                        Spawn RPC server
DEBUG   [U=20004,P=188902] startup()                     singularity runtime engine selected
VERBOSE [U=20004,P=188902] startup()                     Serve RPC requests
DEBUG   [U=20004,P=188776] startup()                     singularity runtime engine selected
VERBOSE [U=20004,P=188776] startup()                     Execute master process
DEBUG   [U=20004,P=188776] setupSessionLayout()          Using Layer system: underlay
DEBUG   [U=20004,P=188776] setupUnderlayLayout()         Creating underlay SESSIONDIR layout
DEBUG   [U=20004,P=188776] addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=20004,P=188776] addRootfsMount()              Image type is 4098
DEBUG   [U=20004,P=188776] addRootfsMount()              Mounting directory rootfs: /My_Directory/rootfs-264903556
DEBUG   [U=20004,P=188776] addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=20004,P=188776] addKernelMount()              Adding proc to mount list
VERBOSE [U=20004,P=188776] addKernelMount()              Default mount: /proc:/proc
DEBUG   [U=20004,P=188776] addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=20004,P=188776] addKernelMount()              Adding sysfs to mount list
VERBOSE [U=20004,P=188776] addKernelMount()              Default mount: /sys:/sys
DEBUG   [U=20004,P=188776] addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=20004,P=188776] addDevMount()                 Adding dev to mount list
VERBOSE [U=20004,P=188776] addDevMount()                 Default mount: /dev:/dev
DEBUG   [U=20004,P=188776] addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=20004,P=188776] addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=20004,P=188776] addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=20004,P=188776] addHomeStagingDir()           Staging home directory (/Home_Directory) at /Singularity_Directory/var/singularity/mnt/session/Home_Directory
DEBUG   [U=20004,P=188776] addHomeMount()                Adding home directory mount [/Singularity_Directory/var/singularity/mnt/session/Home_Directory:/Home_Directory] to list using layer: underlay
DEBUG   [U=20004,P=188776] addTmpMount()                 Checking for 'mount tmp' in configuration file
VERBOSE [U=20004,P=188776] addTmpMount()                 Default mount: /tmp:/tmp
VERBOSE [U=20004,P=188776] addTmpMount()                 Default mount: /var/tmp:/var/tmp
DEBUG   [U=20004,P=188776] addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=20004,P=188776] addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=20004,P=188776] addFilesMount()               Checking for 'user bind control' in configuration file
DEBUG   [U=20004,P=188776] addResolvConfMount()          Adding /etc/resolv.conf to mount list
VERBOSE [U=20004,P=188776] addResolvConfMount()          Default mount: /etc/resolv.conf:/etc/resolv.conf
DEBUG   [U=20004,P=188776] addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=20004,P=188776] addCwdMount()                 Using /My_Directory as current working directory
VERBOSE [U=20004,P=188776] addCwdMount()                 Default mount: /My_Directory: to the container
DEBUG   [U=20004,P=188776] create()                      Mount all
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting tmpfs to /Singularity_Directory/var/singularity/mnt/session
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /My_Directory/rootfs-264903556 to /Singularity_Directory/var/singularity/mnt/session/rootfs
DEBUG   [U=20004,P=188776] mountGeneric()                Remounting /Singularity_Directory/var/singularity/mnt/session/rootfs
DEBUG   [U=20004,P=188776] mountGeneric()                Remounting /Singularity_Directory/var/singularity/mnt/session/rootfs
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/.singularity.d to /Singularity_Directory/var/singularity/mnt/session/underlay/.singularity.d
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/anaconda-post.log to /Singularity_Directory/var/singularity/mnt/session/underlay/anaconda-post.log
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/dev to /Singularity_Directory/var/singularity/mnt/session/underlay/dev
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/etc to /Singularity_Directory/var/singularity/mnt/session/underlay/etc
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/home to /Singularity_Directory/var/singularity/mnt/session/underlay/home
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/media to /Singularity_Directory/var/singularity/mnt/session/underlay/media
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/met to /Singularity_Directory/var/singularity/mnt/session/underlay/met
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/mnt to /Singularity_Directory/var/singularity/mnt/session/underlay/mnt
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/opt to /Singularity_Directory/var/singularity/mnt/session/underlay/opt
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/proc to /Singularity_Directory/var/singularity/mnt/session/underlay/proc
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/root to /Singularity_Directory/var/singularity/mnt/session/underlay/root
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/run to /Singularity_Directory/var/singularity/mnt/session/underlay/run
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/srv to /Singularity_Directory/var/singularity/mnt/session/underlay/srv
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/sys to /Singularity_Directory/var/singularity/mnt/session/underlay/sys
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/tmp to /Singularity_Directory/var/singularity/mnt/session/underlay/tmp
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/usr to /Singularity_Directory/var/singularity/mnt/session/underlay/usr
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/rootfs/var to /Singularity_Directory/var/singularity/mnt/session/underlay/var
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/underlay to /Singularity_Directory/var/singularity/mnt/session/final
DEBUG   [U=20004,P=188776] mountGeneric()                Remounting /Singularity_Directory/var/singularity/mnt/session/final
DEBUG   [U=20004,P=188776] setPropagationMount()         Set RPC mount propagation flag to SLAVE
VERBOSE [U=20004,P=188776] Passwd()                      Checking for template passwd file: /Singularity_Directory/var/singularity/mnt/session/rootfs/etc/passwd
VERBOSE [U=20004,P=188776] Passwd()                      Creating passwd content
VERBOSE [U=20004,P=188776] Passwd()                      Creating template passwd file and appending user data: /Singularity_Directory/var/singularity/mnt/session/rootfs/etc/passwd
DEBUG   [U=20004,P=188776] addIdentityMount()            Adding /etc/passwd to mount list
VERBOSE [U=20004,P=188776] addIdentityMount()            Default mount: /etc/passwd:/etc/passwd
VERBOSE [U=20004,P=188776] Group()                       Checking for template group file: /Singularity_Directory/var/singularity/mnt/session/rootfs/etc/group
VERBOSE [U=20004,P=188776] Group()                       Creating group content
DEBUG   [U=20004,P=188776] addIdentityMount()            Adding /etc/group to mount list
VERBOSE [U=20004,P=188776] addIdentityMount()            Default mount: /etc/group:/etc/group
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /dev to /Singularity_Directory/var/singularity/mnt/session/final/dev
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /etc/localtime to /Singularity_Directory/var/singularity/mnt/session/final/usr/share/zoneinfo/UTC
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /etc/hosts to /Singularity_Directory/var/singularity/mnt/session/final/etc/hosts
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/actions to /Singularity_Directory/var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=20004,P=188776] mountGeneric()                Remounting /Singularity_Directory/var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /proc to /Singularity_Directory/var/singularity/mnt/session/final/proc
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /sys to /Singularity_Directory/var/singularity/mnt/session/final/sys
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Home_Directory to /Singularity_Directory/var/singularity/mnt/session/Home_Directory
DEBUG   [U=20004,P=188776] mountGeneric()                Remounting /Singularity_Directory/var/singularity/mnt/session/Home_Directory
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/Home_Directory to /Singularity_Directory/var/singularity/mnt/session/final/Home_Directory
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /tmp to /Singularity_Directory/var/singularity/mnt/session/final/tmp
DEBUG   [U=20004,P=188776] mountGeneric()                Remounting /Singularity_Directory/var/singularity/mnt/session/final/tmp
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /var/tmp to /Singularity_Directory/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=20004,P=188776] mountGeneric()                Remounting /Singularity_Directory/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /My_Directory to /Singularity_Directory/var/singularity/mnt/session/final/My_Directory
DEBUG   [U=20004,P=188776] mountGeneric()                Remounting /Singularity_Directory/var/singularity/mnt/session/final/My_Directory
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/etc/resolv.conf to /Singularity_Directory/var/singularity/mnt/session/final/etc/resolv.conf
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/etc/passwd to /Singularity_Directory/var/singularity/mnt/session/final/etc/passwd
DEBUG   [U=20004,P=188776] mountGeneric()                Mounting /Singularity_Directory/var/singularity/mnt/session/etc/group to /Singularity_Directory/var/singularity/mnt/session/final/etc/group
DEBUG   [U=20004,P=188776] create()                      Chroot into /Singularity_Directory/var/singularity/mnt/session/final
DEBUG   [U=20004,P=188902] Chroot()                      Hold reference to host / directory
DEBUG   [U=20004,P=188902] Chroot()                      Called pivot_root on /Singularity_Directory/var/singularity/mnt/session/final
DEBUG   [U=20004,P=188902] Chroot()                      Change current directory to host / directory
DEBUG   [U=20004,P=188902] Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=20004,P=188902] Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=20004,P=188902] Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=20004,P=188776] create()                      Chdir into / to avoid errors
VERBOSE [U=20004,P=188901]  wait_child()                  rpc server exited with status 0
DEBUG   [U=20004,P=188901]  apply_container_privileges()  Set user ID to 20004
DEBUG   [U=20004,P=188901]  set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=20004,P=188901] startup()                     singularity runtime engine selected
VERBOSE [U=20004,P=188901] startup()                     Execute stage 2
DEBUG   [U=20004,P=188901] StageTwo()                    Entering stage 2
DEBUG   [U=20004,P=188776] PostStartProcess()            Post start process
total 233473
-rwxr-xr-x 1 khyun lenovo 11900608 Mar  4 18:25 ascii2nc
...
-rwxr-xr-x 1 khyun lenovo 10412448 Mar  4 18:25 wwmca_regrid
total 4100
-rw-r--r-- 1 khyun lenovo 1624782 Mar  4 18:13 libnetcdf.a
...
drwxr-xr-x 2 khyun lenovo    4096 Mar  4 18:14 pkgconfig
VERBOSE [U=20004,P=188776] CleanupContainer()            Removing image /My_Directory/rootfs-264903556
INFO    [U=20004,P=188776] CleanupContainer()            Cleaning up image...
ERROR   [U=20004,P=188776] CleanupContainer()            failed to delete container image /My_Directory/rootfs-264903556: unlinkat /My_Directory/rootfs-264903556/root/.tcshrc: permission denied
DEBUG   [U=20004,P=188776] Master()                      Child exited with exit status 0


Please let me know if you have any suggestions or comments.

**Comment by kihangyoun** [comment]
Hi @dctrud,

I'll explain the problem in more detail.
The directory named "~/rootfs-264903556/" is created during the running phase has two folders "usr" and "root".
As I said, they don't have permission to Owner's write.
After writing permission(chmod -R 755 ./rootfs*), it will be erased without problem.
If I reset the permissions at the end of the script executed by exec, it works.
It is not clear if this is a singularity issue or an image own issue.

Thank you in advance

**Comment by dtrudg** [comment]
Singularity is trying to be as faithful as possible to the permissions in the image now. With `singularity build` we added a `--fix-perms` option when we stopped modifying the permissions from the image. See https://github.com/hpcng/singularity/issues/4671

Clearly we are hitting the issue when a temporary sandbox is being created where singularity actions `run / exec / shell` are being used in an unprivileged installation.

We have a function that exists to do deletion of a dir with the chmod..... we just need to make sure it gets used in this path. This counts as a Singularity bug.

Thanks for the info on this!

**Comment by dtrudg** [comment]
Notes..

Looks like a single line fix.

In `internal/pkg/runtime/engine/singularity/cleanup_linux.go` line 53 - need to use our `fs.ForceRemoveAll(image)` instead of `os.RemoveAll(image)`

**Comment by kihangyoun** [comment]
Hi @dctrud,

In the version 3.5.3, I think there aren't any fs funtions.
As I changed cleanup_linux.go as you mentioned, there are compile error as follows.

../internal/pkg/runtime/engine/singularity/cleanup_linux.go:54:10: undefined: fs

**Comment by kihangyoun** [comment]
Hi @dctrud,

In the version 3.5.3, I think there aren't any fs funtions.
As I changed cleanup_linux.go as you mentioned, there are compile error as follows.

../internal/pkg/runtime/engine/singularity/cleanup_linux.go:54:10: undefined: fs

**Comment by vanderwb** [comment]
@dctrud I see that this issue is closed, but it seems that it was never actually resolved in 3.6.0 despite that version being the milestone.

We have run into this error when using a few containers created in Docker that lack user-write permissions on the root directory. Since they are created in Docker, the "--fix-perms" flag for the build subcommand is not a solution. I took the 3.6.2 source and implemented the fix suggested above in cleanup_linux.go and it resolved the problem. This fix works for our site but obviously it means these containers will produce the error on other sites that have not done so, so it would be nice to have it in the official code base. I could provide a pull request if desired, but it is only a two-line fix.

**Comment by dtrudg** [comment]
@vanderwb - ahh - this got lost track of when the reporting user closed the issue, so it showed up closed on the milestone. I'll make the change as a PR with a regression test.

**Comment by dtrudg** [comment]
@vanderwb - do you have a reproducer on Singularity 3.6... I ask as you are explicitly mentioning missing write perms in the root dir... and I've just tried this and can't cause an error. We had this fix in 3.6.0 which should have dealt with missing write perms on container root dir at build time: #4958 - and coming from docker there is an implicit build happening unless the image was cached... or you are running it out of a SIF created some time ago?

**Comment by vanderwb** [comment]
@dctrud - I have submitted this on behalf of a colleague, so I do not have all of the details of the creation of the container. He says that he saved the Docker image as SIF and then running it as such each time with the implicit build. I can provide the SIF file if useful; please let me know what additional information you need.

**Comment by dtrudg** [comment]
If you can share the SIF file through some means that would be great. Thanks.

**Comment by vanderwb** [comment]
Sure. I've created a Globus shared collection with the SIF file and a short README. The endpoint is called "vanderwb-docker-sif". Let me know if you prefer a different distribution method.

**Comment by dtrudg** [comment]
@vanderwb - retrieved the files. Thanks. Will look into it soon.

**Comment by Phhere** [comment]
Any update on this?

**Comment by dtrudg** [comment]
@Phhere - please indicate if you are seeing the same issue exactly, what Singularity version, and what command / image causes it.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by vanderwb** [comment]
It does not appear that the issue has been fixed, at least for the reproducer I provided. It can be worked around using the fix permissions flag at build time, but the code suggestion made by @dtrudg on May 21, 2020 would still valuable when you are presented with a container with unfixed permissions.

**Comment by DrDaveD** [comment]
Continued at apptainer/apptainer#246
