### ISSUE TITLE
How to change singularity build *** docker URL to my private docker URL?

### ISSUE THREAD

**Issue by xuecangqiuye** [apptainer/singularity#5299]
```
$ singularity version
3.5.2
```
Hello,
I have a private docker hub, when i use `singularity bulid tensorflow-1.14.sif docker://tensorflow/tensorflow:1.14-py3`, singulairty pull `sif` from docker hub.
But, i want pull `sif` from my private docker hub.
For example, I use `docker pull 181.31.28.42/tensorflow:1.14.0` to pull docker image from my private docker hub, `181.31.28.42` is my private docker hub, and i want use `singularity bulid tensorflow-1.14.0.sif` from my my private docker hub.
What should i do?
Thanks!

**Comment by dtrudg** [comment]
Please see the documentation here: https://sylabs.io/guides/3.5/user-guide/singularity_and_docker.html#making-use-of-private-images-from-private-registries


```
singularity build tensorflow,sif docker://181.31.28.42/tensorflow:1.14.0
```

**Comment by xuecangqiuye** [comment]
> Please see the documentation here: https://sylabs.io/guides/3.5/user-guide/singularity_and_docker.html#making-use-of-private-images-from-private-registries
> 
> ```
> singularity build tensorflow,sif docker://181.31.28.42/tensorflow:1.14.0
> ```

Thanks a lot!
