### ISSUE TITLE
Creating image fails on Oracle Linux UEK4 kernel

### ISSUE THREAD

**Issue by mzachh** [apptainer/singularity#530]
Hi,

Singularity looks very, very interesting to me and I am at the moment evaluating it.

However it seems Singularity 2.2.1 does not work on the Oracle Linux [UEK4](http://www.oracle.com/technetwork/server-storage/linux/technologies/uek-overview-2043074.html) kernel, which we use on our cluster.

For example:

```
# singularity create test.img
Creating a new image with a maximum size of 768MiB...
Executing image create helper
Formatting image with ext3 file system
Warning: could not erase sector 2: Attempt to write block to filesystem resulted in short write
Warning: could not read block 0: Attempt to read block from filesystem resulted in short read
Warning: could not erase sector 0: Attempt to write block to filesystem resulted in short write

Warning, had trouble writing out superblocks.Done.
```

```
# tail /var/log/messages
Mar 22 10:52:26 localhost kernel: lo_rw_aio_complete:454:ERROR:-22 received. Device loop0 MAJOR:7 MINOR:0
Mar 22 10:52:26 localhost kernel: blk_update_request: I/O error, dev loop0, sector 262144
Mar 22 10:52:26 localhost kernel: lo_rw_aio_complete:454:ERROR:-22 received. Device loop0 MAJOR:7 MINOR:0
Mar 22 10:52:26 localhost kernel: blk_update_request: I/O error, dev loop0, sector 0
Mar 22 10:52:26 localhost kernel: Buffer I/O error on dev loop0, logical block 0, async page read
Mar 22 10:52:26 localhost kernel: lo_rw_aio_complete:454:ERROR:-22 received. Device loop0 MAJOR:7 MINOR:0
Mar 22 10:52:26 localhost kernel: blk_update_request: I/O error, dev loop0, sector 8
Mar 22 10:52:26 localhost kernel: Buffer I/O error on dev loop0, logical block 1, lost async page write
Mar 22 10:52:26 localhost kernel: lo_rw_aio_complete:454:ERROR:-22 received. Device loop0 MAJOR:7 MINOR:0
Mar 22 10:52:26 localhost kernel: blk_update_request: I/O error, dev loop0, sector 16
Mar 22 10:52:26 localhost kernel: Buffer I/O error on dev loop0, logical block 2, lost async page write
Mar 22 10:52:26 localhost kernel: Buffer I/O error on dev loop0, logical block 3, lost async page write
Mar 22 10:52:26 localhost kernel: Buffer I/O error on dev loop0, logical block 4, lost async page write
Mar 22 10:52:26 localhost kernel: Buffer I/O error on dev loop0, logical block 5, lost async page write
Mar 22 10:52:26 localhost kernel: Buffer I/O error on dev loop0, logical block 6, lost async page write
```

It looks like it is not possible to loop-mount an image with an variable offset. UEK comes with an own loop driver, which offers higher performance and uses async I/O. But it seems it can not deal with variable offsets, the offset need to be aligned with disk sector sizes (512, 4096).

As quick test I hard coded the return value to 512 in singularity_image_offset() which seems to fix the issue on the UEK4 kernel.

In my opinion this is a bug in the UEK kernel and I will talk with the UEK developers about fixing this, but this will take time.

Do you see a quicker solution to support the UEK kernel? Could you imagine to align the image-offset to the sector size and waste a few bytes in the image. Maybe there are other good reasons to do it.

**Comment by gmkurtzer** [comment]
So (if I am understanding correctly), you harded coded an offset, and that worked? That means that you are still using an offset in the loop driver, correct?

Can you send me the debug output of create?

```
singularity --debug create test.img
```

**Comment by mzachh** [comment]
See:

`
DEBUG   [U=0,P=24738]      image-util.c:98:singularity_image_offset() : Returning UEK fixed offset (added)
DEBUG   [U=0,P=24738]      image-util.c:99:singularity_image_offset() : Returning image_offset(image_fp) = 512
`

[create-debug.txt](https://github.com/singularityware/singularity/files/871862/create-debug.txt)

**Comment by gmkurtzer** [comment]
I'm not sure I follow... Singularity properly figured out the offset of the image file:
```
VERBOSE [U=0,P=24738]      image-util.c:62:singularity_image_check()  : File is a valid Singularity image
VERBOSE [U=0,P=24738]      image-util.c:82:singularity_image_offset() : Calculating image offset
VERBOSE [U=0,P=24738]      image-util.c:91:singularity_image_offset() : Found image at an offset of 31 bytes
```

But then you hard coded a return:
```
DEBUG   [U=0,P=24738]      image-util.c:98:singularity_image_offset() : Returning UEK fixed offset
DEBUG   [U=0,P=24738]      image-util.c:99:singularity_image_offset() : Returning image_offset(image_fp) = 512
```

This will still cause the loop device to use a variable offset, within Singuarity, just that the offset is a fixed amount (512).

What we should figure out is what loop features are supported via their loop driver. for example, is LO_FLAGS_AUTOCLEAR also supported as a flag (Singularity relies on that heavily). is loop_info64.lo_offset supported at all? Hrmm...

Do they have any documentation you can point me to?

**Comment by jscook2345** [comment]
@mzachh Any word on using Singularity with your system? If you still need assistance please update this issue. Thanks!

**Comment by mzachh** [comment]
We are currently not actively using Singularity.
Feel free to close the issue, as the bug is in UEK.
