### ISSUE TITLE
Regression: error building image with --fakeroot

### ISSUE THREAD

**Issue by LaHaine** [apptainer/singularity#5305]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```
`3.6.0~rc.3-1.el7`

### Expected behavior
It should build an image

### Actual behavior
```
There is an error message:
% singularity build --fakeroot -s test/ sl77.def
ERROR  : Requesting capability set 0x0000003fffffffff while permitted capability set is 0x0000001fffffffff
```

### Steps to reproduce this behavior
Try to build an image from a receipt file: 

# What OS/distro are you running

```
$ cat /etc/os-release


```
```
NAME="Scientific Linux"
VERSION="7.7 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.7"
PRETTY_NAME="Scientific Linux 7.7 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.7:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"

```
### How did you install Singularity
rpm built from source

This didn't produce an error in rc.2, but it regressed in rc.3.

**Comment by dtrudg** [comment]
@LaHaine - thanks for the report. The PR https://github.com/hpcng/singularity/pull/5269 introduced some changes to *respect* available caps better, but we may have some kind of issue related to it.

Could you provide output running with `singularity -d ...`?

This isn't coming up in our tests etc. which do definitely run fakeroot builds - so we'll need a little more information from the Debug logs to work it out. `3.6.0-rc.3` adds some more capabilities debug output, so hopefully that's all we'll need.

**Comment by LaHaine** [comment]
OK, here's the log of `singularity -d build --fakeroot  -s test/ sl77.def  &> singularity-log.txt`
[singularity-log.txt](https://github.com/hpcng/singularity/files/4651241/singularity-log.txt)
