### ISSUE TITLE
INSTALL.md apt-get dependencies incomplete.

### ISSUE THREAD

**Issue by gdevenyi** [apptainer/singularity#5306]
Compare INSTALL.md to https://sylabs.io/guides/3.5/user-guide/quick_start.html#quick-installation-steps

**Comment by dtrudg** [comment]
The INSTALL.md has been cut-down for dependencies no longer needed. This will be reflected in the 3.6 docs at release.

See e.g.: https://github.com/hpcng/singularity/commit/2c4f7953d6a253723f5262a1368a172b843ec4fe#diff-7d442b7eb49f5fc377f51e74b291cfc1

**Comment by gdevenyi** [comment]
My bad, assuming the github INTSALL.md would correspond to the release file instructions.

**Comment by dtrudg** [comment]
@gdevenyi - the default branch on github is `master` which is in development. The `release-3.x` branches should have `INSTALL.md` content that matches with the docs for the corresponding version.

It's a little confusing, agreed.

**Comment by gdevenyi** [comment]
Totally understand, lots of ways to run a project with git branches.
