### ISSUE TITLE
[proposal] docker pull

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#531]
since we now can create and import without sudo, it follows naturally that users would want to do this with one command. Since "pull" is akin to "get this image from somewhere cloudy and put it here" I think "pull" would map nicely to a docker uri as follows, where:

      docker pull meatball.img docker://awesome

would basically map to

      singularity create meatball.img && singularity import meatball.img docker://awesome

on the back end, singularity would first generate the image, and then issue the import (non sudo) function to python, which would return layers,and dump them in. Thoughts?

**Comment by chrisgorgo** [comment]
+1!

**Comment by gmkurtzer** [comment]
I just knew that @chrisfilo would support this idea! lol

@vsoch and I are trying to figure out how to approximate the size of the container to create.

**Comment by chrisgorgo** [comment]
I love you beautiful people :)

**Comment by vsoch** [comment]
The second version of the docker manifest DOES have sizes with the layers (along with nixing all the other stuffs we need, lol) but if that is consistent, we could use it.

**Comment by vsoch** [comment]
we <3 you too, @chrisfilo !

**Comment by ArangoGutierrez** [comment]
Closing this issue due after 2.3 release `singularity pull` does all the work, with having to create and then import from a docker URI
```bash
[Eduardo@Highwind tmp]$ singularity pull shub://vsoch/singularity-images
Progress |===================================| 100.0% 
Done. Container is at: /tmp/vsoch-singularity-images-master-latest.simg
[Eduardo@Highwind ~]$ ls /tmp/
vsoch-singularity-images-master-latest.simg
```
> Feel free to re-open any time

**Comment by vsoch** [comment]
haha I remember fighting for this! Yes!! :muscle:
