### ISSUE TITLE
%test fails in a fakeroot image build

### ISSUE THREAD

**Issue by LaHaine** [apptainer/singularity#5315]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```
```
3.6.0~rc.3.1-1.el7
```

### Expected behavior
building a image file
### Actual behavior
```
INFO:    Adding environment to container
INFO:    Adding runscript
INFO:    Adding testscript
INFO:    Running testscript
FATAL:   container creation failed: mount overlay->/var/singularity/mnt/session/final error: while mounting overlay: can't mount overlay filesystem to /var/singularity/mnt/session/final: operation not permitted
FATAL:   While performing build: failed to execute %test script: exit status 255
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Use lolcow.def from the documentation and append this %test section:
```
%test
    echo "space left:"
    df -h
```
Then run ```singularity build --fakeroot lolcow.sif lolcow.def```. It works without the %test section and fails with the section.

### What OS/distro are you running

```
$ cat /etc/os-release


```
```
NAME="Scientific Linux"
VERSION="7.7 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.7"
PRETTY_NAME="Scientific Linux 7.7 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.7:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
```

### How did you install Singularity

rpm build from source of 3.6.0 rc.3 with the patch from pr #5313 applied.

**Comment by LaHaine** [comment]
This is a regression from 3.5.3 where the same command ran fine.

**Comment by dtrudg** [comment]
Please could you provide debug output of  `singularity -d build ..`  and also indicate what file systems are in use on your host machine?

**Comment by LaHaine** [comment]
[singularity-log.txt](https://github.com/hpcng/singularity/files/4684491/singularity-log.txt)
It is all XFS, but the very same command on the same file system is fine with singularity 3.5.3.

**Comment by dtrudg** [comment]
Guessing that this is related to the change from the separate build engine to standard engine for build. Any thought r.e. obvious places to look @cclerget before I start digging?

**Comment by dtrudg** [comment]
Confirmed same on Fedora 32.

```
Bootstrap: docker
From: ubuntu:latest

%test
    echo "space left:"
    df -h
```


```
INFO:    Starting build...
Getting image source signatures
Copying blob d51af753c3d3 done  
Copying blob fc878cd0a91c done  
Copying blob 6154df8ff988 done  
Copying blob fee5db0ff82f done  
Copying config 95c3f3755f done  
Writing manifest to image destination
Storing signatures
2020/05/27 08:37:23  info unpack layer: sha256:d51af753c3d3a984351448ec0f85ddafc580680fd6dfce9f4b09fdb367ee1e3e
2020/05/27 08:37:24  info unpack layer: sha256:fc878cd0a91c7bece56f668b2c79a19d94dd5471dae41fe5a7e14b4ae65251f6
2020/05/27 08:37:24  info unpack layer: sha256:6154df8ff9882934dc5bf265b8b85a3aeadba06387447ffa440f7af7f32b0e1d
2020/05/27 08:37:24  info unpack layer: sha256:fee5db0ff82f7aa5ace63497df4802bbadf8f2779ed3e1858605b791dc449425
INFO:    Adding testscript
INFO:    Running testscript
FATAL:   container creation failed: mount overlay->/usr/local/var/singularity/mnt/sessions/final error: while mounting overlay: can't mount overlay filesystem to /usr/local/var/singularity/mnt/sessions/final: operation not permitted
FATAL:   While performing build: failed to execute %test script: exit status 255
```

**Comment by cclerget** [comment]
@dctrud During preparation of session layer it doesn't detect it is currently running inside a user namespace, need to be fixed at `setSessionLayer` in `internal/pkg/runtime/engine/singularity/prepare_linux.go` right after the check of user namespace by calling `namespaces.IsInsideUserNamespace(os.Getpid())` to automatically fallback to underlay in this case
