### ISSUE TITLE
How to capture stdout / stderr from container on Mac

### ISSUE THREAD

**Issue by illusional** [apptainer/singularity#5316]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
singularity version 3.3.0-rc.1.658.g7427b73f1.dirty
```

### Expected behavior

I'm using Python to run a command inside a container, and I want to capture the stderr of the help text that gets returned. 

### Actual behavior

However `check_output` returns an empty string, and the output of the container is still logged to the console. Running the equivalent command in shell also doesn't work either.

### Steps to reproduce this behavior

Bash:

The following Python is basically what I'm trying to do

```
import subprocess
cmd = ["singularity", "exec", "docker://quay.io/biocontainers/kallisto:0.46.2--h4f7b962_1", "kallisto", "index"]
output = (subprocess.check_output(cmd, stderr=subprocess.STDOUT)
    .decode("utf-8")
    .rstrip())
print("OUTPUT:\n" + str(output))
```

Similar with bash, but nothing is in `test.txt`, and I still have output on the console.

```bash
{ "singularity" "exec" "docker://quay.io/biocontainers/kallisto:0.46.2--h4f7b962_1" "kallisto" "index"; } 2>&1 > test.txt
```

### What OS/distro are you running

MacOS 10.14.6 (Mojave)

### How did you install Singularity

https://sylabs.io/singularity-desktop-macos/

**Comment by jmstover** [comment]
On the Mac we're doing (`cmd/internal/cli/startvm.go`):
```
    cmd.Stdin = os.Stdin
    cmd.Stdout = os.Stdout
    if VMErr || debug {
        cmd.Stderr = os.Stderr
    }
```

So, for `stderr`, that is attached if you use the `--vm-err` or the `-d` flag.

I did see that redirection on Mac didn't _always_ work right. But from what's being done it should work I would think. :/

@dctrud @cclerget either of you see anything in the Mac redirect that's off? We're getting the output to the screen, but once you add a redirect into the equation, all bets are off. For example on Mac:

```
singularity exec myimg.sif ls -l > myout
```

Generally gives you an empty `myout` file... 

I don't know if this is a mixture of the Host Singularity + Hypervisor + Hypervisor Singularity not playing nice together.

**Comment by dtrudg** [comment]
@jmstover I (temporarily) don't currently have a Mac - so will have to come back to this.

**Comment by illusional** [comment]
Thanks for the reply @jmstover, I tested these two things and unfortunately neither captured the tool's help text, but I got the following logs:

Just standard `singularity exec --vm-error [...]` I got the following in stderr:

```
rdmsr to register 0x140 on vcpu 0
rdmsr to register 0x64e on vcpu 0
rdmsr to register 0x34 on vcpu 0
```

Adding `-d` to give: `singularity -d exec --vm-error [...]` I get:

```
DEBUG   [U=268212191,P=2087]createConfDir()               /Users/franklinmichael/.singularity already exists. Not creating.
DEBUG   [U=268212191,P=2087]getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=268212191,P=2087]updateCacheSubdir()           Caching directory set to /Users/franklinmichael/.singularity/cache/library
DEBUG   [U=268212191,P=2087]updateCacheSubdir()           Caching directory set to /Users/franklinmichael/.singularity/cache/oci-tmp
DEBUG   [U=268212191,P=2087]updateCacheSubdir()           Caching directory set to /Users/franklinmichael/.singularity/cache/oci
DEBUG   [U=268212191,P=2087]updateCacheSubdir()           Caching directory set to /Users/franklinmichael/.singularity/cache/net
DEBUG   [U=268212191,P=2087]updateCacheSubdir()           Caching directory set to /Users/franklinmichael/.singularity/cache/shub
DEBUG   [U=268212191,P=2087]updateCacheSubdir()           Caching directory set to /Users/franklinmichael/.singularity/cache/oras
DEBUG   [U=268212191,P=2087]parseURI()                    Parsing docker://quay.io/biocontainers/kallisto:0.46.2--h4f7b962_1 into reference
DEBUG   [U=268212191,P=2087]updateCacheSubdir()           Caching directory set to /Users/franklinmichael/.singularity/cache/oci-tmp/39e957cf7ece74136a369f5c4b39634add8e27d15df96f6ba423e889aa323427
DEBUG   [U=268212191,P=2087]updateCacheSubdir()           Caching directory set to /Users/franklinmichael/.singularity/cache/oci-tmp/39e957cf7ece74136a369f5c4b39634add8e27d15df96f6ba423e889aa323427
DEBUG   [U=268212191,P=2087]getHypervisorArgs()           PCI: 4:0,virtio-9p,home=/Users/franklinmichael
DEBUG   [U=268212191,P=2087]getHypervisorArgs()           Check for sandbox image
DEBUG   [U=268212191,P=2087]startVM()                     About to launch VM using: [/usr/local/libexec/singularity/vm/xhyve -A -m 1024 -c 1 -s 0:0,hostbridge -s 31,lpc -l com1,stdio -s 3,virtio-net -s 4:0,virtio-9p,home=/Users/franklinmichael -s 2:0,ahci-hd,/Users/franklinmichael/.singularity/cache/oci-tmp/39e957cf7ece74136a369f5c4b39634add8e27d15df96f6ba423e889aa323427/kallisto_0.46.2--h4f7b962_1.sif -f kexec,/usr/local/libexec//singularity/vm/syos-kernel-amd64,/usr/local/libexec//singularity/vm/initramfs_amd64.gz,console=ttyS0 quiet root=/dev/ram0 loglevel=0 sing_img_name=kallisto_0.46.2--h4f7b962_1.sif sing_user=franklinmichael:268212191:1677682026 sing_cwd=/Users/franklinmichael/Desktop/tmp singularity_action=exec ipv4=dhcp msglvl=5 singularity_arguments="kallisto index -h" singularity_binds="|home:/Users/franklinmichael"]
rdmsr to register 0x140 on vcpu 0
rdmsr to register 0x64e on vcpu 0
rdmsr to register 0x34 on vcpu 0
DEBUG   [U=268212191,P=2087]startVM()                     Hypervisor exit code: exit status 1
DEBUG   [U=268212191,P=2087]startVM()                     Process exited with non-zero return code: 1
```

**Comment by sligocki** [comment]
I'm also seeing this issue on Mac. A simple example:
```
$ singularity exec ~/my.sif date > temp.out 2> temp.err
Tue 22 Sep 2020 08:50:48 PM UTC
[    1.305098] reboot: Power down

$ ll temp*
-rw-r--r--  1 sl929  11103514  0 Sep 22 16:50 temp.err
-rw-r--r--  1 sl929  11103514  0 Sep 22 16:50 temp.out
```

So it appears that singularity is bypassing the shell stdout/stderr. Maybe it's writing directly to the TTY??

On Linux this works as expected:
```
$ singularity exec ~/my.sif date > temp.out 2> temp.err

$ ll temp.*
-rw-r--r-- 1 sligocki ebz3a5p  0 Sep 22 16:53 temp.err
-rw-r--r-- 1 sligocki ebz3a5p 32 Sep 22 16:53 temp.out
```

**Comment by dtrudg** [comment]
This is a known limitation. On the mac there is a host -> VM boundary and the stdout/stderr redirection is not working as expected.

Please also note that Singularity Desktop for mac is not under active development at present. It is an old version missing recent fixes.

See: https://sylabs.io/singularity-desktop-macos/

>Please Note - Singularity Desktop for macOS is a Beta release, and has not been updated for compatibility with the new SIF signature format in Singularity 3.6.0.

> Sylabs™ is currently engaging with the community to plot a course for the future of the Mac version of Singularity. In the meantime, please be aware that the release has not received recent security and bug fixes, and should be used at your own risk.

If you have any interest in being involved in helping Singularity for Mac become a community maintained project, please let us know.

**Comment by dtrudg** [comment]
Closing as Singularity Desktop currently not maintained.
