### ISSUE TITLE
OMPI variable doesn't work for --bind option

### ISSUE THREAD

**Issue by sihara** [apptainer/singularity#5317]
### Version of Singularity: 3.5.3

What version of Singularity are you using? Run:

```
$ singularity version 
3.5.3
```

### Expected behavior
```
[user1@ec01 ~]$ mkdir /home/user1/0
[user1@ec01 ~]$ mkdir /home/user1/1
[user1@ec01 ~]$ touch /home/user1/0/0.txt
[user1@ec01 ~]$ touch /home/user1/1/1.txt
[user1@ec01 ~]$ mpirun -np 2 singularity exec --bind /home/$USER/$OMPI_COMM_WORLD_RANK:/mnt /tmp/centos8.sif ls -l /mnt
```
RANK0 would print /mnt/0.txt and RANK1 prints /mnt/1.txt.
Any missing here or any alternative ways to do this? 

### Actual behavior

However, OMPI_COMM_WORLD_RANK is ignored.
```
[user1@ec01 ~]$ mpirun -np 2 singularity exec --bind /home/$USER/$OMPI_COMM_WORLD_RANK:/mnt /tmp/centos8.sif ls -l /mnt
total 8
drwxr-xr-x 2 user1 users 4096 May 26 11:47 0
drwxr-xr-x 2 user1 users 4096 May 26 11:47 1
total 8
drwxr-xr-x 2 user1 users 4096 May 26 11:47 0
drwxr-xr-x 2 user1 users 4096 May 26 11:47 1
```

### Steps to reproduce this behavior
```
[user1@ec01 ~]$ mpirun -np 2 singularity exec --bind /home/$USER/$OMPI_COMM_WORLD_RANK:/mnt /tmp/centos8.sif ls -l /mnt
total 8
drwxr-xr-x 2 user1 users 4096 May 26 11:47 0
drwxr-xr-x 2 user1 users 4096 May 26 11:47 1
total 8
drwxr-xr-x 2 user1 users 4096 May 26 11:47 0
drwxr-xr-x 2 user1 users 4096 May 26 11:47 1
```
variable 'USER' works, but variable comes from openmpi (e.g. OMPI_COMM_WORLD_RANK or other OMPI_XXX )doesn't work.

### What OS/distro are you running

```
[user1@ec01 ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

### How did you install Singularity
```
# ./mconfig
# make -C ./builddir/ 
# make -C ./builddir/ install
```

**Comment by sihara** [comment]
'export OMPI_COMM_WORLD_RANK' works, but i woudn't set 'export OMPI_COMM_WORLD_RANK' before mpirun. it would be nice if there is any alternative idea to pass OMPI variable to bind option.

**Comment by sihara** [comment]
I found a quick workaround below.
```
[user1@ec01 ~]$ cat singularity.sh 
#!/bin/sh

export OMPI_COMM_WORLD_RANK
singularity exec --bind /home/$USER/${OMPI_COMM_WORLD_RANK}:/mnt $*

[user1@ec01 ~]$ mpirun -np 2 singularity.sh /tmp/centos8.sif ls /mnt/
0.txt
1.txt
````
At least it works and solved what I wanted.  Also, this was able to pass OMPI_COMM_WORLD_RANK to --bind option.
I'm sure whether if this is best way, but if there are any ideas or better way, all suggestions or advices are welcome.

**Comment by dtrudg** [comment]
@sihara - the reason this doesn't work on a straight `mpirun` command line is that the variable is expanded by the shell at the point in time that command is run:

```
[user1@ec01 ~]$ mpirun -np 2 singularity exec --bind /home/$USER/$OMPI_COMM_WORLD_RANK:/mnt /tmp/centos8.sif ls -l /mnt
```

Here the value of `$OMPI_COMM_WORLD_RANK` is taken at the point you press enter to run this command... and *not*  later while it it is running under `mpirun`.

Using a wrapper script as you are in the latest comment is one good way to do it - as your `$OMPI_COMM_WORLD_RANK` is then evaluated when that wrapper script is called by `mpirun`.

Another thing you could do is to wrap it all in one command that invokes a shell...

```
mpirun -np 2 sh -c 'singularity exec --bind /home/$USER/$OMPI_COMM_WORLD_RANK:/mnt /tmp/centos8.sif ls -l /mnt'
```

This makes mpirun start a shell, passing the command in single quotes. The single quotes prevent the variables being expanded at the time you press `enter` to run the `mpirun` command.

Another example of how single quotes work like this...

```
# With double quotes or no quotes ${PWD} is evaluated immediately in the parent shell
dtrudg-sylabs@piran:~
09:26 AM $ sh -c "cd / && echo ${PWD} && cd"
/home/dtrudg-sylabs

# With single quotes ${PWD} is evaluated in the sub shell we are running
dtrudg-sylabs@piran:~
09:27 AM $ sh -c 'cd / && echo ${PWD} && cd'
/

```
