### ISSUE TITLE
Unable to check Go compiler 

### ISSUE THREAD

**Issue by rishikakumar05** [apptainer/singularity#5320]
### Version of Singularity: 3.3.0 on Ubuntu 16.04LTS 

similar issue: https://github.com/hpcng/singularity/issues/4765

I have completely removed and reinstalled go 3 times. I do not know what to do. 

### Expected behavior

What did you expect to see when you do...?

Expected Go to be installed properly using: https://golang.org/doc/install?download=go1.14.3.linux-amd64.tar.gz

Expected singularity to then be installed using:
https://golang.org/doc/install?download=go1.14.3.linux-amd64.tar.gz

This is not working. 

### Actual behavior

What actually happened? Why was it incorrect?

$sudo ./mconfig -v
Configuring for project `singularity' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version go1.11)... not found!
mconfig: could not complete configuration

$go version
go version go1.14.2 linux/amd64

$env GO111MODULE=off go run mlocal/checks/version.go go1.14
Found Go release tag go1.14.

$go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/chroma/.cache/go-build"
GOENV="/home/chroma/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/chroma/Desktop/go/Projects"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build341934285=/tmp/go-build -gno-record-gcc-switches"

**Comment by dtrudg** [comment]
> `$ sudo ./mconfig -v`

Your go installation is not on `PATH` when you run through `sudo`. `sudo` will have a limited `PATH` depending on what distribution you are using / how `secure_path` is set in `/etc/sudoers`.

You do not need to run `mconfig` with `sudo`. Only the final `make -C builddir install` step requires sudo.

```
$ ./mconfig -v
$ make -C builddir
$ sudo make -C builddir install
```

This should work on newer versions of Singularity. If you are building an older version, that does not carry the location of `go` into the `make install` step properly, then you will need to ensure that the location of `go` is on your `PATH` inside of a `sudo` environment.

**Comment by rishikakumar05** [comment]
Thanks! I deleted the PPO python 3.6 and this worked fine!
