### ISSUE TITLE
--tmpdir error

### ISSUE THREAD

**Issue by neurominer-git** [apptainer/singularity#5327]
### Version of Singularity:

```
$ singularity version
3.5.3-1.1.el7

```

### Expected behavior

Given this simple .def file

```
BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
UpdateURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/updates/$basearch/
Include: yum

%labels
	Author Jimit.Doshi@pennmedicine.upenn.edu
	Version v1.0.0

%help
	This container contains all dependencies required for running the 
	CBICA pipeline.

%setup

%post
	NOW=`env TZ=America/New_York date`
	echo "export NOW=\"${NOW}\"" >> $SINGULARITY_ENVIRONMENT

%runscript
	echo -e "\nContainer was created: $NOW"
	echo -e "Arguments received: $*\n"
	exec "$@"

%environment

%post
	yum -y install hostname

```

When running `singularity --debug build --disable-cache --tmpdir /volume/PHENOM/MUSE/tmpdir test2.sif test.def` singularity should use the specified --tmpdir. 

### Actual behavior

It does not create the directories within the tmpdir (see below)

We cannot use the /tmp because we don't have enough space. I have made sure that the tmpdir specified has rwx `0 drwxrwsrwx+ 2 root    g_project   10 May 29 22:22 tmpdir/` and am running as root. Because of the NFS mounted file system I am using I have also tried as root and as a user with --fakeroot .  

```
DEBUG   [U=0,P=13024]      persistentPreRunE()           Singularity version: 3.5.3-1.1.el7
DEBUG   [U=0,P=13024]      handleConfDir()               /root/.singularity already exists. Not creating.
DEBUG   [U=0,P=13024]      Init()                        Image format detection
DEBUG   [U=0,P=13024]      Init()                        Check for sandbox image format
DEBUG   [U=0,P=13024]      Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=13024]      Init()                        Check for sif image format
DEBUG   [U=0,P=13024]      Init()                        sif format initializer returned: can't read first 2048 bytes: <nil>
DEBUG   [U=0,P=13024]      Init()                        Check for squashfs image format
DEBUG   [U=0,P=13024]      Init()                        squashfs format initializer returned: can't read first 2048 bytes: <nil>
DEBUG   [U=0,P=13024]      Init()                        Check for ext3 image format
DEBUG   [U=0,P=13024]      Init()                        ext3 format initializer returned: can't read first 2048 bytes: <nil>
DEBUG   [U=0,P=13024]      newBundle()                   Created temporary directory "/volume/PHENOM/MUSE/tmpdir/bundle-temp-248444285" for the bundle
DEBUG   [U=0,P=13024]      newBundle()                   Created directory "/volume/PHENOM/MUSE/tmpdir/rootfs-8a2103b7-a1e8-11ea-8a2b-52540031c1d4" for the bundle
DEBUG   [U=0,P=13024]      ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=0,P=13024]      ensureGzipComp()              Gzip compression by default ensured
INFO    [U=0,P=13024]      Full()                        Starting build...
DEBUG   [U=0,P=13024]      Get()                         Found yum at: /usr/bin/yum
DEBUG   [U=0,P=13024]      cleanUp()                     Cleaning up "/volume/PHENOM/MUSE/tmpdir/rootfs-8a2103b7-a1e8-11ea-8a2b-52540031c1d4" and "/volume/PHENOM/MUSE/tmpdir/bundle-temp-248444285"
FATAL   [U=0,P=13024]      runBuildLocal()               While performing build: conveyor failed to get: while generating yum config: while creating /volume/PHENOM/MUSE/tmpdir/rootfs-8a2103b7-a1e8-11ea-8a2b-52540031c1d4/etc: mkdir /volume/PHENOM/MUSE/tmpdir/rootfs-8a2103b7-a1e8-11ea-8a2b-52540031c1d4/etc: no such file or directory
``` 

### Steps to reproduce this behavior

Build the above .def and specify a --tmpdir .  

### What OS/distro are you running

```
$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)

```

### How did you install Singularity

From rpm using the directions

**Comment by dtrudg** [comment]
From the debug output, the `--tmpdir` option is working correctly, as the error occurs when trying to create a directory at that location:

```
mkdir /volume/PHENOM/MUSE/tmpdir/rootfs-8a2103b7-a1e8-11ea-8a2b-52540031c1d4/etc: no such file or directory
```

Note that *unless* your NFS mount is with `no_root_squash` then this won't generally work, as `singularity build` run as root will be squashed down to the `nobody` user.

Also, NFS isn't aware of the (sub)uid/gid mappings that are used by `--fakeroot` so this can lead to other issues.

For further thoughts we'd need some more information:

- How exactly is your NFS share exported and mounted (export / mount options).
- If you sudo to root can you do what singularity is trying and failing to do? `mkdir /volume/PHENOM/MUSE/tmpdir/rootfs-8a2103b7-a1e8-11ea-8a2b-52540031c1d4/etc`
- Please provide the complete debug output for both  sudo / fakeroot runs, indicating which debug comes from which.

**Comment by neurominer-git** [comment]
Thanks very much for replying so quickly and for this info! It now makes sense to me why it is not working in both cases of using root user and also `--fakeroot`. 

We didn't want to use the `no_root_squash` option due to security concerns, so I tested a number of things. I settled on using a non-mounted directory on another server. It could be good for people to know that even if you use a non-NFS mount then you may experience other mount-related id problems, like this one related to a Cent OS7 rpm: 
```
Error unpacking rpm package 2:shadow-utils-4.6.5.el7.x86_64
error: unpacking of archive failed on file /usr/bin/newgidmap;5ed21dc0: cpio: cap_set_file
```
