### ISSUE TITLE
Linking ssh-agent into a container (possible feature request)

### ISSUE THREAD

**Issue by mkgvt** [apptainer/singularity#5328]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3
```

### Expected behavior

What did you expect to see when you do...?

I am looking for a way to link a SSH agent on the host into the singularity build process so that files can be copied from a remote host using scp or git clone using the credential in the agent. The work around is to download the files before running the build but it would be convenient to do it within as it reduces the number of steps one has to remember.

### Actual behavior

What actually happend? Why was it incorrect?

Haven't been able to find any documentation on how to do it. Perhaps the capability doesn't exist. If so, then you can consider this a feature request.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

Don't know. It was installed by the system administrator.

**Comment by dtrudg** [comment]
Hello - this isn't really an issue with Singularity, rather a question about creating a definition file, so would be more appropriate to bring up in the Slack channel or on the mailing list. More people will see it there, and you may find someone who has already tried this.

https://sylabs.io/resources/community

The `ssh-agent` works by creating a socket in `/tmp` by default, and that host `/tmp` is available within a build - so you should be able to gain access to it if you can set env vars etc. correctly.
