### ISSUE TITLE
Segmentation fault using a docker image

### ISSUE THREAD

**Issue by pveber** [apptainer/singularity#533]
After a source install of the current `master` branch, I run
```
$ singularity shell docker://pveber/meme:4.11.2
```
and obtain a segmentation fault:
```
Extracting /home/pveber/.singularity/docker/sha256:350d6c5dc558d36eb6073d50906db6be1c00bde1e2426738197e2174c177bbae.tar.gz
Singularity: Invoking an interactive shell within container...

Erreur de segmentation
```
The image causing the error is available on docker hub, so the above line can be tested to check whether the bug is reproducible. It's my first time using singularity, sorry if I missed something obvious.

**Comment by vsoch** [comment]
hey @pveber ! Could you try the development branch? I just tried using development, and it seems to work ok:

```bash
b6be1c00bde1e2426738197e2174c177bbae.tar.gz
No Docker CMD or ENTRYPOINT found, skipping runscript generation.
Singularity: Invoking an interactive shell within container...

Singularity meme:4.11.2> 
```

**Comment by vsoch** [comment]
If you still get the error, please run with `--debug` and share the full output so we can figure out what is causing the segmentation default  (which looks much more beautiful in French, btw!).

**Comment by gmkurtzer** [comment]
Apologies about the state of the current master branch. We are committed to resolving it as soon as possible. As @vsoch mentioned, please try the development branch and let us know.

Thanks!

**Comment by pveber** [comment]
hello @vsoch and @gmkurtzer, the seg fault doesn't show up with the development branch. Merci beaucoup !

**Comment by gmkurtzer** [comment]
Fantastic, thanks for testing!

**Comment by vsoch** [comment]
boocoo!
