### ISSUE TITLE
Default PS1 missing in 3.6.0 if run through a bash script and no .singularity.d in image

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#5340]
### Version of Singularity:

What version of Singularity are you using?

3.6.0~rc.4-1.el7

### Expected behavior

I expect to see a prompt whenever singularity invokes an interactive bash.

### Actual behavior

Whenever a bash script is run, PS1 gets set to empty.  If a bash script invokes singularity, and singularity invokes an interactive bash using a container sandbox image that has no .singularity.d (as many of our containers currently do because we read them with docker tools), then there is no prompt string.  3.5.3 put in a default PS1 of "Singularity> ".

### Steps to reproduce this behavior

```
singularity build --fix-perms --sandbox centos7-sandbox docker://centos:7
rm -rf centos7-sandbox/.singularity.d
(echo '#!/bin/bash'; echo 'singularity "$@"') >dosing
chmod +x dosing
./dosing exec centos7-sandbox bash
```

### What OS/distro are you running

CentOS 7.8

### How did you install Singularity

From the EPEL scratch build

I am working around the problem by doing `export PS1="${PS1:-Singularity> }"` in my singularity bash script wrapper.

**Comment by dctrud** [comment]
Doesn't appear to need the `dosing` script - I can replicate directly calling Singularity.

```
02:18 PM $ singularity run centos7-sandbox-full/
Singularity> exit

dave@dev-fedora:~
02:18 PM $ singularity run centos7-sandbox
INFO:    No runscript found in container, executing /bin/sh
dave@dev-fedora:~
02:18 PM $ exit
```
