### ISSUE TITLE
Data patition access problem  in singularity contains

### ISSUE THREAD

**Issue by qianglchina** [apptainer/singularity#5344]
### Version of Singularity:

Singularity 3.6.0-rc.4 ( build install )
Redhat 6.9 x64

I tried to add a data patition to a sif image:

truncate -s 1G data.ext3
mkfs.ext3 data.ext3
singularity sif add --datatype 4 --groupid 1 --partarch 2 --partfs 2 --parttype 3  cowsay_1.sif data.ext3

```
[root@rh6 workspace]# singularity sif list cowsay_1.sif
Container id: ec3df922-f8fb-45d8-a551-682c98242a95
Created on:   2020-06-05 14:55:29 -0400 EDT
Modified on:  2020-06-05 18:53:36 -0400 EDT
----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-33271               |Def.FILE
2    |1       |NONE    |36864-36961               |JSON.Generic
3    |1       |NONE    |40960-67768320            |FS (Squashfs/*System/amd64)
4    |1       |NONE    |67768320-1141510144       |FS (Ext3/Data/amd64)

```
 However I could not find ext3 data patition and mount point in container: 
```
[root@rh6 workspace]# singularity exec  cowsay_1.sif  bash
Singularity> blkid
/dev/loop0: TYPE="squashfs"
/dev/loop1: TYPE="squashfs"
/dev/loop2: TYPE="squashfs"
/dev/loop3: TYPE="squashfs"
/dev/loop4: TYPE="squashfs"
/dev/sdb1: UUID="TJfINe-ae8d-6okM-P2xP-Qicw-iK5F-rY1ojM" TYPE="LVM2_member" PARTLABEL="primary" PARTUUID="62ceb834-304c-4b5a-ab63-3fd189432da9"
/dev/sda1: UUID="59df2781-bf89-453c-ba18-689cadd0be60" TYPE="ext4" PARTUUID="00046fa1-01"
/dev/sda2: UUID="LcJkXG-H7zb-fEYc-hfG0-m97T-d1cm-INECKc" TYPE="LVM2_member" PARTUUID="00046fa1-02"
/dev/mapper/vg_rh6-lv_root: UUID="63194cb4-8a1b-4c3d-ab8e-39c54bc792af" TYPE="ext4"
/dev/mapper/vg_rh6-lv_swap: UUID="5c11e60c-e3e7-4420-a6d7-13ad99e60dda" TYPE="swap"

```
So how I can access the data patition in singularity container?
By the way, I can access the data patition from other sif by "-- bind", a new feature of 3.6 version.

**Comment by dtrudg** [comment]
> Redhat 6.9 x64

Overlay is not supported on RedHat 6.9, so a persistent overlay partition (which you have created here) will not work. This is documented in the install guide requirements.

> OverlayFS mounts - (minimum kernel >=3.18) Required for full flexiblity in bind mounts to containers, and to support persistent overlays for writable containers.

See: https://sylabs.io/guides/3.5/admin-guide/installation.html#system-requirements

Using `--bind` from another SIF file the alternative underlay can be used, but this is not possible for the whole container overlay embedded in a SIF file.

**Comment by qianglchina** [comment]
singularity sif add --datatype 4 --groupid 1 --partarch 2 --partfs 2 **--parttype 3** cowsay_1.sif data.ext3

 **--parttype 3** means that it's a Data partion type,not a overlay partion type.

In fact, I tried overlay parttype, and it works fine. I have upgraded linux kernel to 4.4.210 ( I forgot mention that before, sorry...)

How to mount Data type partion of SIF in container?

**Comment by dctrud** [comment]
@qianglchina

**Comment by dtrudg** [comment]
Sorry, I missed the data `parttype` after reading RHEL6.

@cclerget - is there a method for mounting from the container SIF via the new image mount functions?

**Comment by cclerget** [comment]
@qianglchina You can mount from SIF like this :

```
singularity sif new /tmp/data.sif
singularity sif add --datatype 4 --groupid 1 --partarch 2 --partfs 2 --parttype 3 /tmp/data.sif data.ext3
singularity shell -B /tmp/data.sif:/data:image-src=/ cowsay_1.sif
```

Actually you couldn't use the same SIF file both as data and as container image because locking mechanism is preventing that (that's something to fix for a next release). So it works but only in a separate file.

**Comment by qianglchina** [comment]
I see. 
Thanks a lot.  You can close this issue.
