### ISSUE TITLE
Cannot run singularity sandbox container with inaccessible home directory

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#5350]
### Version of Singularity:

What version of Singularity are you using? 

It happens on 3.5.3 and on 3.6.0~rc.4

### Expected behavior

I expect to be able to execute a sandbox image without a working home directory, because it should not have to do any caching.

### Actual behavior

It works when the home directory is missing or is only non-writable, but if the the user has no access permission to the home directory or one of its parent directories, it fails with an error
```
FATAL:   Failed to create an image cache handle: failed to get first existing parent of cache directory: stat /scratch/noperm/dwdtest/.singularity: permission denied
```

### Steps to reproduce this behavior

Change the owner of a home directory to root and make it mode 700, then try to exec a sandbox image within an account of that home directory.

### What OS/distro are you running

CentOS 7.8

### How did you install Singularity

From EPEL.

**Comment by dtrudg** [comment]
@DrDaveD - I can give a partial fix for this... but not a total one at this point.

If we permit a non-accessible home in our cache code then it's okay for non docker/OCI pulls and builds.

Unfortunately if you are building from a docker source, the `containers/image` library goes off to look for the docker config.json in your home directory. When it does that it only handles a non existing file - not a home dir perm error too.

```
[noperms@dev-fedora tmp]$ singularity build -s test docker://alpine
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: error getting username and password: error reading JSON file "/home/noperms/.docker/config.json": open /home/noperms/.docker/config.json: permission denied
```

https://github.com/containers/image/blob/22129f19a77890293540e67843f28860f5a77895/pkg/docker/config/config.go#L289

The code that ultimately using `readJSONFile` is called internally in the flow of creating a new docker client in `containers/image` so I don't think it's something we can work around easily. Would need further investigation and probably opening an issue upstream.

Is having things working *except* for docker/OCI pulls any use to you?

**Comment by DrDaveD** [comment]
Yes that would be very helpful.  The problem is when we execute a sandbox (out of cvmfs).  I'm not surprised that a docker pull requires a home directory for the cache.

**Comment by dtrudg** [comment]
Okay - #5519 should be a fix... I'll mark it ready for review when it passes CI tests.

**Comment by dtrudg** [comment]
#5519 is merged.
