### ISSUE TITLE
Singularity overlay error with concurrent writes to ext3 image

### ISSUE THREAD

**Issue by brettChapman** [apptainer/singularity#5351]
Hi

I'm currently running Singularity 3.5.3 on Ubuntu 20.04 LTS. I installed Singularity from GitHub and compiled from source. I'm running Slurm to manage jobs across my compute nodes.

I'm trying to run Cactus based on the SBATCH script from the following page: https://informatics.fas.harvard.edu/cactus-on-the-fasrc-cluster.html

I have a cluster of 3 nodes and I have a ext3 image I'm trying to write to from each node. The /data directory is shared across all nodes and mounted on the master node.

The error I get is as follows:

srun -n 24 singularity exec --cleanenv --no-home --overlay jobStore.img --bind /data/scratch/cactus-120/tmp:/tmp /data/cactus_builds/cactus_latest.sif cactus --root Anc0 --workDir=/cactus/workDir --binariesMode local /cactus/jobStore wildBarley.txt wildBarley.hal
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
FATAL:   error while locking ext3 overlay partition from /data/jobStore.img: can't open /data/jobStore.img for writing, currently in use by another process
srun: error: node-1: tasks 0-4,6-7: Exited with exit code 255
srun: error: node-2: tasks 8-15: Exited with exit code 255
srun: error: node-3: tasks 16-23: Exited with exit code 255

Is it possible to perform multiple writes from different processes to the same ext3 image using Singularity? If not, is there a possible workaround solution? I have already tried to use a directory instead of an ext3 image, but Singularity complains that the filesystem is NFS.

For reference I have submitted the same issue to the Cactus repo: https://github.com/ComparativeGenomicsToolkit/cactus/issues/261

Thank you for any help you can provide.

**Comment by dtrudg** [comment]
Filesystems such as ext3 can only be mounted and written to from one location. There isn't a workaround to this really. The kernel code for local filesystems is not designed to support this.

R.E. NFS - When using an overlay, the location that new data is written to becomes the `upperdir` of an overlay filesystem mount. NFS *can* be used as the base `lowerdir` of an overlay, but it cannot be used us the `upperdir` for an overlay, unfortunately, which is why Singularity complains about this. Among other things NFS does not have nice guarantees of atomic operations, cache consistency etc.

**Comment by nathanweeks** [comment]
Hi @brettChapman , in the example script we explicitly use `#SBATCH --nodes=1` to run on a single node, both for ext3 file system consistency reasons that @dctrud  mentioned, as well as the cactus developers no longer recommend using toil with SLURM (or any other HPC batch scheduler):
https://github.com/ComparativeGenomicsToolkit/cactus#system-requirements
> IMPORTANT: It is highly recommend that one not run Cactus using the Toil Grid Engine-like batch systems (GridEngine, HTCondor, LSF, SLURM, or Torque). Cactus creates a very large number of small jobs, which can overwhelm these systems.

Which has been our experience as well... Hence, we recommend running it on a single node (preferably one with lots of processor cores) in isolation (`--binariesMode local`) entirely within a singularity container (with `--cleanenv --no-home` to reduce the likelihood that the host software environment causes unexpected interactions with the container software environment) using a singularity persistent overlay, as toil creates/accesses/deletes lots of little files during execution (which can cause performance issues on a parallel file system like Lustre).

We don't have extensive experience with this setup yet, but it seems to work OK for the most part.

**Comment by dtrudg** [comment]
Thanks for adding information here @nathanweeks 

@brettChapman - as this is application related, it's best discussed in a Cactus specific location, rather than in a Singularity issue. I'll close this issue, but if you hit any Singularity problems then let us know.

**Comment by brettChapman** [comment]
Hi @nathanweeks 

Thanks for your input.

Unfortunately I don't have access to a single node big enough. I have already tried on the single biggest node we have access to, which is 16 cores and 64GB RAM. My Cactus run fails due to a limited number of cores. Hence why I'm attempting to use multiple nodes in a cluster. There is a possibility we may get access to a large compute node at a super computing centre here with 6TB RAM later in the year, but getting access requires jumping through a lot of hoops, and justification for the compute resources requested (which is difficult to predict just what resources Cactus needs - I'm looking at aligning many large 5 Gbps plant genomes), plus we can't wait that long to generate results. Please let me know if you have any suggestions for workarounds, using Cactus or some other tool. Thanks.

**Comment by nathanweeks** [comment]
Hi @brettChapman , I haven't tried running Cactus on a node with only 64 GB of memory (which is really inadequate for computational biology). Given the [memory requirements of cactus](https://github.com/ComparativeGenomicsToolkit/cactus#system-requirements), I suspect finding a cluster with larger-memory nodes (e.g., at another institution) in the meantime could be the most expedient approach.

**Comment by brettChapman** [comment]
Hi @nathanweeks, thanks for your input. At the moment the small cluster I have access to is all there is. Access to anything else other than from the Pawsey Supercomputing centre here is mostly out of my hands. Getting access to larger compute resources at Pawsey is akin to applying for a government funded grant and is quite competitive. 

I've managed to work around the problem by splitting the genome up per chromosome and submitting a job per chromosome per node. I'm managing to get the Cactus runs to complete. Since I'm looking at different varieties of the same species, I don't see any problem with aligning on a chromosome by chromosome basis. I'm currently looking at 3 genomes, but I imagine if I were to scale up to more genomes, I'll probably start hitting some resource limitations.

I'm planning to covert the HAL files to VG afterwards. VG has an option to merge the VG files. Fingers crossed it works ok. I've read that merging VG files will work as long as each file has the same root, so it may be possible to merge multiple different runs/genomes, as long as the root genome is present in each.
