### ISSUE TITLE
Singularity exec command stops without error message

### ISSUE THREAD

**Issue by Grelot** [apptainer/singularity#5355]
### Version of Singularity:

singularity version 3.6.0-rc.3

```
nohup singularity exec --bind /media/superdisk/:/media/superdisk/ /media/superdisk/utils/conteneurs/obitools.simg illuminapairedend -r /media/superdisk/edna/donnees/ngs/LaPerouse/200323_SN234_A_L001_AIMI-215_R2.fastq.gz /media/superdisk/edna/donnees/ngs/LaPerouse/200323_SN234_A_L001_AIMI-215_R1.fastq.gz --score-min=40 > test.fastq 2> test.log &
```

### Expected behavior

This command must generate a file called `test.fastq` with an excepted size of 13 GB

### Actual behavior

The command stop without error message and generates a file of size 2 GB instead of 13 GB. I notice that the end of the file is an incomplete line so the job get really interrupted.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

I tried on 2 different computers and with different files (they are huge files) and the same bug is happening again.

This problem is not reproductible with tiny files (it works perfectly in such cases)

I have to mention that i'm running a lot of others job at the same time in parallel using snakemake on the same machine so i don't know how a computer behave when numerous singularity run are launched at the same time. In that case snakemake interrupts the whole workflow but don't return any error message.

### What OS/distro are you running

```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

From source code following instruction on github

**Comment by dtrudg** [comment]
This is very unlikely to be an issue with Singularity itself. By the time that the process is running and producing output, Singularity has gotten out of the way - it isn't monitoring or interrupting the process.

What is the filesystem you are writing to? Some older filesystems did have a limit of 2GB per file - and the `/media/superdisk` suggests you might be using removable storage?

**Comment by Grelot** [comment]
I'm writting on a removable storage :

```
  File: "/media/superdisk/"
    ID: 81ece1a77452d273 Namelen: 255     Type: ext2/ext3
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 4863670574 Free: 889933592  Available: 645772774
Inodes: Total: 305197056  Free: 304188232
```

Also sometimes the command within singularity works and write a file beyond 2GB

**Comment by dtrudg** [comment]
Okay, I really don't believe there is a Singularity issue here, as Singularity shouldn't impact file I/O in any way. 

Check the output of `dmesg` for anything relating to the storage.

I would suggest (1) running on different file systems. If that still fails (2) run outside of a container to confirm Singularity is not involved before inquiring with the software project about the issue.

Also run in the foreground with the nohup and redirection and see if anything different happens.

**Comment by dtrudg** [comment]
Closing as there has been no further follow-up.
