### ISSUE TITLE
passing environement variables at runtime

### ISSUE THREAD

**Issue by mybigman** [apptainer/singularity#5364]
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.5.3-1.1.fc33

```

### Expected behavior
To see my passed environment variable

### Actual behavior
Not passed

### Steps to reproduce this behavior
```
> cat alpine.def 
BootStrap: docker
From: alpine

> sudo singularity build alpine.sif alpine.def

> SINGULARITYENV_HELLO="WORLD" singularity instance start alpine.sif alpine
> singularity shell alpine.sif
> env | grep -i hello

no result
```

### What OS/distro are you running

```
NAME=Fedora
VERSION="32 (Server Edition)"
```

### How did you install Singularity
via dnf (repository)

**Comment by dtrudg** [comment]
In this case the `HELLO` env var is being provided to the `startscript` for the container that is run when `instance start` is used.

When you run `singularity shell alpine.sif` you are running a completely separate version of the container.

Use `SINGULARITYENV_HELLO="WORLD" singularity shell alpine.sif` if you just want a standalone shell with that env var set.

**Comment by mybigman** [comment]
@dctrud so what happens when I stop the container then restart the container. Are those environment variables lost?

How does another user come along and view what environment variables were set during the initial instance start?

thanks.

**Comment by dtrudg** [comment]
Singularity doesn't really work in the same was as Docker / OCI runtimes in this respect. It's a daemon-less runtime that originated in HPC batch environments, so it does not use the same concept of container state that Docker has. A container is either `run/shell/exec`'d in the foreground or `instance start`ed in the background, but state does not persist after the container exits, or an instance is stopped.

> @dctrud so what happens when I stop the container then restart the container. Are those environment variables lost?

Yes - if you `instance start` then later `instance stop`, the stop makes the container disappear, and a subsequent `start` is a new container. There is no state kept for an instance that has been stopped.

> How does another user come along and view what environment variables were set during the initial instance start?

Instances are specific to a particular user, so another user cannot interact with them. The environment variable set when you do an `instance start` only applys to the `startscript` the container runs on `instance start`. Other interactions such as `singularity shell instance://test` do not inherit them. See also #5353 

If you are looking for something closer to the semantics of docker then singularity has an `oci` command group. In this mode there is the concept of separately creating / running / stopping / deleting containers. See: https://sylabs.io/guides/3.5/user-guide/oci_runtime.html

**Comment by mybigman** [comment]
@dctrud thanks mate, its appreciated... its much clearer now.
