### ISSUE TITLE
Singularity Mac Desktop cannot be installed (Catalina 10.15.5)

### ISSUE THREAD

**Issue by chrisjsewell** [apptainer/singularity#5365]
![Screenshot 2020-06-14 at 21 15 32](https://user-images.githubusercontent.com/2997570/84603167-38cb8700-ae84-11ea-8ebc-9439b7cc7b92.png)

**Comment by dtrudg** [comment]
This is a common issue for Mac applications distributed outside of the app store.

Singularity Desktop is currently a beta, and is not something that can currently be packaged and notarized/signed in a way which will prevent these warnings, so you will have to follow the procedure outlined here: https://www.webnots.com/how-to-open-blocked-apps-with-apple-cant-check-it-for-malicious-software-warning/
