### ISSUE TITLE
error: failed switching to "user" when install a image

### ISSUE THREAD

**Issue by CryoSky** [apptainer/singularity#5375]
### Version of Singularity:

What version of Singularity are you using? Run:

singularity version 3.5.3-1.el7

Running code:
```
singularity build proq3.sif docker://nanjiang/proq3
singularity run proq3.sif
```

### Expected behavior

Successfully install an image.

### Actual behavior

Starting with UID : 1000
useradd: Permission denied.
useradd: cannot lock /etc/passwd; try again later.
chown: invalid user: ‘user:user’
error: failed switching to "user": get supplementary groups Unable to find user user

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
I don't know.

### What OS/distro are you running

NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

**Comment by dtrudg** [comment]
The default security model of Singularity is such that when you run a container you are the same user inside that container as you are outside of the container. You cannot change user, so docker containers that attempt to add users and rely on making use of them will not work correctly. You may have some additional luck by using the `--fakeroot` flag. If your system is able to support this it will run the container as a 'fake root' user that can change to other effective user IDs in a safely mapped user namespace.

However, note also that when you run a container the container filesystem is read-only, and files inside it cannot be modified without `--writable-tmpfs` / `--writable` on a sandbox build / using an overlay.

Further, looking at the container, it also places a lot of content in locations under `/home` that will be masked by Singularity's default mount of `$HOME` into the container.

I'm afraid that this container is one of those that is unlikely to work easily under Singularity. We have guidance around docker container compatibility here: https://sylabs.io/guides/3.5/user-guide/singularity_and_docker.html#best-practices

**Comment by CryoSky** [comment]
Many thanks. Finally, I gave up and downloaded the source code from elsewhere to use.
