### ISSUE TITLE
Perlbrew install

### ISSUE THREAD

**Issue by Lcornet** [apptainer/singularity#5386]
### Expected behavior

I constructed a sandbox image with perlbrew, who works as expected but I have en error when running out of sandbox.

    BootStrap: library
    From: omatt/default/mpi:3.1.1

    %files
        test.cc /opt/test-mpi.c

    %environment
        export PERLBREW_ROOT=/root/perl5/perlbrew
        export export PATH=$PATH:/root/perl5/perlbrew/bin
        source /root/perl5/perlbrew/etc/bashrc

    %post
        #Update part
        #permission part
        chmod -R 777 /opt #chmod775 can be enough
        chmod -R 777 /root #chmod775 can be enough
        #modules
        yum install -y git
        yum install -y automake autoconf
        yum install -y make
        yum install -y zlib-devel
        yum install -y bzip2-devel
        yum install -y xz-devel
        yum install -y zip unzip
        yum install -y gcc gcc-c++ make
        yum install -y epel-release
        yum install -y cmake3
        ln -s /usr/bin/cmake3 /usr/bin/cmake
        yum install -y rsync
        yum install -y https://repo.ius.io/ius-release-el7.rpm
        yum install -y python36u
        yum install -y wget
        yum install -y epel-release
        yum install -y boost boost-thread boost-devel
        yum install -y perl-CPAN
        #yum install -y cpanminus
        yum install -y patch
        #perlbrew
        wget -O - http://install.perlbrew.pl | bash
        source ~/perl5/perlbrew/etc/bashrc
        perlbrew init
        perlbrew --notest --verbose install perl-5.26.3 --yes
        perlbrew install-cpanm --yes
        perlbrew switch perl-5.26.3
        #BMC
        cpanm LWP::Simple --force
        cpanm Bio::MUST::Core

    %runscript
        echo "This container contains : "

    %help
        This is a container for 

    %labels
        Author Luc Cornet
        Version v0.0.1    

I need perlbrew to install for a specific perl package.

    $ sudo singularity build --sandbox test-full.img/ test.def
    $ sudo singularity shell --writable test-full.img
      Singularity test-full.img:~> ali2fasta.pl
        Missing required argument:
	      <infiles>

It works in sandbox/shell mode. But I have the following error in exec mode.

### Actual behavior

    $ sudo singularity build test-cl.img test.def
    $ singularity exec test-cl.img ls
      /.singularity.d/env/90-environment.sh: line 23: /root/perl5/perlbrew/etc/bashrc: No such file or director

What did i miss ?

### What OS/distro are you running

Linux 18.04 (ubuntu)

### How did you install Singularity

from https://sylabs.io/guides/3.0/user-guide/installation.html

**Comment by dtrudg** [comment]
Singularity `3.0.3` is very old and unsupported. I'm not sure whether there were any issues related to files being placed in `/root` during a build there - but please check with a current version - `3.5.3` is the latest.

Generally you should avoid putting anything in a container in `/root` or `/home` - even if you chmod them to open up access this could be problematic depending on how the container is run. Are you sure when you run `sudo singularity shell` that it it is not picking up an `ali2fasta.pl` from your host system?

I would advise placing perlbrew under `/opt` or elsewhere, not under `/root`

**Comment by dtrudg** [comment]
Closing as no further follow-up received.
