### ISSUE TITLE
Very long start time (>10 mins) on Singularity 3.6.0-rc.4 when CWD contains large (>100,000) files

### ISSUE THREAD

**Issue by novosirj** [apptainer/singularity#5389]
### Version of Singularity:

What version of Singularity are you using? Run:

```
[root@node081 ~]# singularity --version
singularity version 3.6.0-rc.4
```

### Expected behavior

Container starts, runs application in a relatively short period of time -- a few seconds, something like that.

### Actual behavior

Container starts, but there's a longer and longer start time. `starter-suid` is running and is often in a `D` state. I could not have told you this before running `strace`, but it appears to be related to doing some operation on every single file in the directory. See attached output. 

### Steps to reproduce this behavior

I'm not certain, but I suspect:

1) Create a directory with >100,000 files (or some number lower than that -- has been getting worse over time).
2) Do `singularity exec whatever.img command` with CWD as the same directory that contains the image and the large number of files and see if `starter-suid` works for a long period of time before running whatever command. I'll try this to verify, I just have to wait for a job to complete.

### What OS/distro are you running

```
[root@node081 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

Compiled from source via this script:

```
#!/bin/sh

module purge
module list

# From Singularity documentation:
# Go is a bit finicky about where things are placed. Here is the correct way to build Singularity from source.
#
# $ mkdir -p $GOPATH/src/github.com/sylabs
# $ cd $GOPATH/src/github.com/sylabs
# $ git clone https://github.com/sylabs/singularity.git
# $ cd singularity
#
# However, to do this using singularity-3.0.3.tar.gz, instead of using git, do "tar xf singularity-3.0.3.tar.gz".
#
# Also, "make test" step requires singularity to be in the $PATH, however sudo will clear it out of $PATH. First, set a symlink
# somewhere in the $PATH to the target location (eg. ln -s /opt/sw/packages/gcc-4_8/singularity/3.0.3/bin/singularity /usr/bin/singularity).
# This is kludgey and there's probably a better way.
#       = novosirj, 20190215

export VERSION=1.13.12 OS=linux ARCH=amd64 && \
    wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz -O /scratch/novosirj/install-files/go$VERSION.$OS-$ARCH.tar.gz && \
    mkdir /mnt/scratch/novosirj/go-$VERSION && tar -C /mnt/scratch/novosirj/go-$VERSION -xzf /scratch/novosirj/install-files/go$VERSION.$OS-$ARCH.tar.gz

export GOPATH="/mnt/scratch/novosirj/go-$VERSION/go"
export PATH=${PATH}:${GOPATH}/bin

export VERSION=3.6.0-rc.4 && # adjust this as necessary \
    wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz -O /scratch/novosirj/install-files/singularity-${VERSION}.tar.gz && \
    mkdir -p /mnt/scratch/novosirj/singularity-$VERSION; cd /mnt/scratch/novosirj/singularity-$VERSION
    tar -xzf /scratch/novosirj/install-files/singularity-${VERSION}.tar.gz && \
    cd singularity

./mconfig --prefix=/opt/sw/packages/gcc-4_8/singularity/${VERSION} \
        --localstatedir=/var \
        && cd builddir ; make -j32 && sudo -E make install && sudo ln -s /opt/sw/packages/gcc-4_8/singularity/${VERSION}/bin/singularity /usr/bin/singularity && make test && sudo rm -f /usr/bin/singularity
```

**Comment by novosirj** [comment]
[strace-f-p_starter-suid.out.gz](https://github.com/hpcng/singularity/files/4807006/strace-f-p_starter-suid.out.gz)

**Comment by novosirj** [comment]
Should also mention that the CWD in this case is on GPFS; not sure if it makes any difference.

**Comment by novosirj** [comment]
The FAH_array.12258154_1.log is the SLURM job logfile, which contains the output of `singularity -d`. The `strace...` file contains an `strace -f -p` of the `starter-suid` process from the same job. I didn't get it from the beginning, and I trimmed past ~4 million lines when it just started to repeat, presumably after the job started. 

[FAH_array.12258154_1.log](https://github.com/hpcng/singularity/files/4810170/FAH_array.12258154_1.log)
[strace-f-p_8501-20200620-1.out.gz](https://github.com/hpcng/singularity/files/4810171/strace-f-p_8501-20200620-1.out.gz)

**Comment by dtrudg** [comment]
> Should also mention that the CWD in this case is on GPFS; not sure if it makes any difference.

Stat over huge number of files would be expected to take a long time on GPFS, as that's over the network for each stat.

I note from the logs you are using underlay here too, not overlay - may be related. Will have to look into this one in depth.

**Comment by novosirj** [comment]
FYI, believe this started between 3.6.0-rc.1 and 3.6.0-rc.2.

**Comment by dtrudg** [comment]
Yup - this is a nasty regression when CWD contains a lot of files... thanks for finding it @novosirj - it doesn't really show much when using a typical local dev environment with fast SSD etc.

It isn't related to underlay either - happens with overlay enabled.

In a directory with 100,000 files...

```
# 3.5.3
$ singularity -d exec docker://busybox true & sudo strace -o v353 -f -p $(pgrep singularity)

$ grep -c fstat v353
381

# 3.6.0-rc.4
$ grep -c fstat v360rc4 
344683
```

**Comment by novosirj** [comment]
Seems to be present in all of 3.6.0, or at least back as early as 3.6.0-rc.1. I apparently just didn't have the condition that made it visible at that time.

**Comment by novosirj** [comment]
I'll test this out.

**Comment by novosirj** [comment]
Certainly seems to behave better; I tried your test case above and the strace seems to run for a really long time, but a test case of my own shows a big difference:

```
[novosirj@perceval1 FAH]$ which singularity
/opt/sw/packages/gcc-4_8/singularity/3.6.0-rc.4-PR5394/bin/singularity
[novosirj@perceval1 FAH]$ time singularity exec folding@home-7.6.13.sif date
Tue Jun 23 19:14:15 EDT 2020

real    0m0.377s
user    0m0.072s
sys     0m0.136s

[novosirj@perceval1 FAH]$ which singularity
/opt/sw/packages/gcc-4_8/singularity/3.6.0-rc.4/bin/singularity
[novosirj@perceval1 FAH]$ time singularity exec folding@home-7.6.13.sif date                                                                             Tue Jun 23 19:18:31 EDT 2020

real    0m35.455s
user    0m2.807s
sys     0m11.804s
```
