### ISSUE TITLE
How can I get singularity container on Ubantu 20.04

### ISSUE THREAD

**Issue by chaitanyadgore** [apptainer/singularity#5390]
I tried following command in terminal I tried this
$ sudo apt-get install singularity-container
I am facing the following error
E: package 'singularity-container' has no installation candidate
I m going to use it for Robot operating system

**Comment by dtrudg** [comment]
Singularity is not packaged for Ubuntu 20.04 to my knowledge. You would need to build it from source. Take a look at the `INSTALL.md` file or the guide here: https://sylabs.io/guides/3.5/admin-guide/installation.html

**Comment by amelvill-umich** [comment]
There's still no [official package](https://packages.ubuntu.com/search?keywords=singularity), but this site has it: https://neuro.debian.net/install_pkg.html?p=singularity-container

**Comment by DraTeots** [comment]
Beware https://neuro.debian.net has singularity 2.6 (today we have 3.8-rc2) which may not read newer images. 

P.S. It is SHAME to singularity to have a great product but have such a complex way of installation instruction.

**Comment by DrDaveD** [comment]
The person who had volunteered to package singularity-3.8 for Debian lost interest.  I believe that Debian was requiring separate packaging for all dependent go packages, and it was too much effort for him.  It would be great if someone else would take it up.

**Comment by qhaas** [comment]
**Luckily** for those not wanting to compile from source, most of the binaries in the (well maintained) EPEL EL8 singularity 3.8.x rpm are static linked, so it is one of the cleaner conversions using [alien](https://wiki.debian.org/Alien):
```
$ grep PRETTY_NAME /etc/os-release 
PRETTY_NAME="Ubuntu 20.04.2 LTS"
$ alien --version
alien version 8.95
# WARNING:  singularity version numbers subject to change, browse the yum repo to get up-to-date URL
wget https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/s/singularity-3.8.0-1.el8.x86_64.rpm
$ sudo alien -d singularity-3.8.0-1.el8.x86_64.rpm
...
$ sudo apt-get install ./singularity_3.8.0-2_amd64.deb
...
$ singularity --version
singularity version 3.8.0-1.el8
$ singularity pull cuda.sif docker://nvidia/cuda:11.0.3-base-ubuntu20.04
...
$ singularity exec --nv -e cuda.sif nvidia-smi -L
GPU 0: Tesla V100-PCIE-32GB (UUID: GPU-0a55d110-f8ea-4209-baa7-0e5675c7e832)
```

**Comment by DrDaveD** [comment]
That's good to know, thanks.  Meanwhile in #6038 Debian packaging was resurrected before the release of singularity-3.8.0, so it may be relatively easy to adapt that for Ubuntu.  Nobody is building them and making downloadable packages publicly available though as far as I know.

**Comment by boegel** [comment]
@DrDaveD Maybe the procedure using `alien` should be added to the Singularity user documentation?

I've been looking for instructions on how to easily install Singularity on Ubuntu several times, and I was very happy when I found @qhaas' comment...
