### ISSUE TITLE
Filesystem extraction fails because of certain packages, no way to pass command line options to unsquashfs

### ISSUE THREAD

**Issue by ivhacks** [apptainer/singularity#5399]
### Version of Singularity: 3.6.0 rc2

```
$ singularity version
3.6.0-rc.2+46-g971f9116b
```

### Actual behavior
I created a container that has libgstreamer installed. When I run
```singularity shell --fakeroot container.sif```
The following error is given:
```
FATAL:   while extracting container-fakeroot.sif: root filesystem extraction failed: extract command failed: 
write_xattr: could not write xattr security.capability for file /tmp/rootfs-319557469/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-ptp-helper because you're not superuser!

write_xattr: to avoid this error message, either specify -user-xattrs, -no-xattrs, or run as superuser!
```
I'm guessing there's other software besides gstreamer that will cause this issue, this is just the example that I stumbled upon.

Note that the container works properly *without* `--fakeroot`, with or without `sudo`.

The error recommends using `-user-xattrs` or `-no-xattrs` to solve the problem, but they can't be placed in the `singularity shell` command, and there doesn't seem to be an equivalent.

### Expected behavior
Optimally, Singularity would handle this situation in such a way that it's completely hidden from the user. Running `singularity shell` would just drop you at the shell like it's supposed to. Due to inexperience, I don't know if this is technically possible or practical. The next best solution would be for Singularity to display an error that clearly specifies what has to be added to the shell command for it to work.

### Steps to reproduce this behavior
Create a recipe file with the following contents:
```
BootStrap: debootstrap
OSVersion: focal
MirrorURL: http://us.archive.ubuntu.com/ubuntu/

%post
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libgstreamer1.0-0
 ```
Run `singularity build --fakeroot container.sif recipe`
Then `singularity shell --fakeroot container.sif`

### OS/distro
Ubuntu 20.04 LTS (Focal Fossa)

### How did you install Singularity
From source, using the guide detailed here: https://sylabs.io/guides/3.5/admin-guide/installation.html#installation-on-linux
In order to get an unrelated bugfix, I used `master` instead of a specific release. The build was done on June 6, 2020. As far as I know, being 21 days out of date shouldn't affect this issue, but I can try on a more recent build if necessary. 

@dctrud recommended that I create this issue, tagging him to let him know it's up

**Comment by dtrudg** [comment]
`unsquashfs` should use options to avoid failing on xattrs we can't extract in unpriv operation:

```
	-no[-xattrs]		don't extract xattrs in file system
	-x[attrs]		extract xattrs in file system (default)
	-u[ser-xattrs]		only extract user xattrs in file system.
				Enables extracting xattrs
```

**Comment by dtrudg** [comment]
Unfortunately this is more complicated. We have to consider the old unsquashfs on RHEL6 that does not have these options.

Not present on RHEL6. Present on RHEL7+
Present on Ubuntu 16.04+

**Comment by dtrudg** [comment]
@Jousboxx - are you able to test with PR #5518 ? This should be a fix for the issue.

**Comment by ivhacks** [comment]
This does indeed fix the problem!
