### ISSUE TITLE
bootstrap problems on SL6.7

### ISSUE THREAD

**Issue by sebastian-luna-valero** [apptainer/singularity#54]
Hello,

I am using singularity v2.0 and I had the following errors when bootstraping the examples:

```
[root@test singularity]# singularity bootstrap /tmp/container.img examples/centos.def
Setting RELEASE=7
Loaded plugins: refresh-packagekit, security
Setting up Install Process
os-base                                                                                        | 3.6 kB     00:00
Not using downloaded repomd.xml because it is older than what we have:
  Current   : Fri Feb 12 16:54:21 2016
  Downloaded: Wed Dec  9 22:35:45 2015
Error: xz compression not available

[root@test singularity]# singularity bootstrap /tmp/container.img examples/scientific.def
Setting RELEASE=7
Loaded plugins: refresh-packagekit, security
Setting up Install Process
os-base                                                                                        | 3.7 kB     00:00
Error: xz compression not available

[root@test singularity]# singularity bootstrap /tmp/container.img examples/debian.def
ERROR: debootstrap is not in PATH... Perhaps 'apt-get install' it?

[root@test singularity]# singularity bootstrap /tmp/container.img examples/ubuntu.def
ERROR: debootstrap is not in PATH... Perhaps 'apt-get install' it?
```

Is there something that I am doing wrong?

Thanks,
Sebastian.

**Comment by truatpasteurdotfr** [comment]
hi,
- you need 'debootstrap' from the EPEL repository to bootstrap de debian container :)
- bootstraping a CentOS-7 container from a CentOS-6 machine works for me, but it will not work from a CentOS-5 machine due to rpm versions changes
  -> "Error: xz compression not available" hints that you are using a old rpm version.

Tru

**Comment by gmkurtzer** [comment]
I wonder if there is a predictive way to anticipate the first two failures... Any ideas Tru?

**Comment by sebastian-luna-valero** [comment]
Many thanks!

After doing:

```
yum install epel-release
yum install libtool debootstrap xz
```

Debian, Ubuntu and CentOS images are bootstrapped correctly. However, I am still getting:

```
Error: xz compression not available
```

for Scientific Linux.

I am running this on a VM with a minimal install of SL6.7, please let me know if you need any more information.

Best regards,
Sebastian.

**Comment by gmkurtzer** [comment]
I have a feeling it might be a loosely defined build requirement of RPM, and this is just a difference in how RPM was built on Centos Vs. Scientific. I am checking with Connie (maintainer of SL) and will report back.

**Comment by gmkurtzer** [comment]
I haven't heard back from Connie (yet)... At this point I am pretty sure this is an SL issue, and will close this issue as it doesn't seem to be an issue with Singularity. Feel free to comment and let me know if this issue needs to be reopened.

Thanks!
