### ISSUE TITLE
SINGULARITY_APPEND_VARIABLE_NAME does not work with  singularity 3.5.3 

### ISSUE THREAD

**Issue by smarocchi** [apptainer/singularity#5403]
### Version of Singularity:

What version of Singularity are you using? Run:

3.5.3
$ singularity version
[smarocc1@r033c01s05 openmpi311_centos_TEST]$ singularity --version
singularity version 3.5.3

I am just trying to run your mpi example

Bootstrap: docker
From: ubuntu:latest

%files
    mpitest.c /opt

%environment
    export OMPI_DIR=/opt/ompi
    export SINGULARITY_OMPI_DIR=$OMPI_DIR
    export SINGULARITYENV_APPEND_PATH=$OMPI_DIR/bin
    export SINGULAIRTYENV_APPEND_LD_LIBRARY_PATH=$OMPI_DIR/lib

......

### Expected behavior

I was expecting to see updated variables 

PATH 

LD_LIBRARY_PATH

What did you expect to see when you do...?

### Actual behavior

[smarocchi@NSMAROCCH204664 ubuntu_openmpi311_Singularity]$ singularity shell openmpi311_ubuntu_original.sif 

Singularity> echo $LD_LIBRARY_PATH
/.singularity.d/libs

Singularity> echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

What actually happend? Why was it incorrect?

They did not updated the variables correctly 

### Steps to reproduce this behavior

1) build a container

2) run echo $NAME_VARIABLES inside the container

How can others reproduce this issue/problem?

### What OS/distro are you running

cat /etc/redhat-release 
CentOS Linux release 8.2.2004 (Core)

### How did you install Singularity

yum

Write here how you installed Singularity. Eg. RPM, source.

RPM

**Comment by dtrudg** [comment]
The example is incorrect - we need to address this in the documentation.

Generally SINGULARITYENV_xxx is for use on the host to force-set something into the container. It shouldn't be used in `%environment` sections as variable `xxx` should be set directly there.

**Comment by bjarthur** [comment]
setting env vars with SINGULARITYENV_xxx also doesn't work with OS X still, right?  will it ever?

i saw mention of engaging the community w.r.t. OS X support. where is that discussion happening?

thanks!

**Comment by dtrudg** [comment]
@bjarthur - I understand that this not straightforward with the current architecture of the OSX code, and I'm afraid there isn't any work planned at present to address it.

We (as in Sylabs) have brought the Mac topic up on the Sigularity mailing list - particularly asking the new HPCng organization if there might be interest in the existing code possibly finding a home there as one option. I'm afraid we haven't had a response to that. The monthly developer calls would also be a good place for anyone interested in a discussion, but it hasn't come up with the audience in those to date.

The mailing list thread is here: https://groups.google.com/a/lbl.gov/g/singularity/c/MSsOy6TkkQY

The developer list, with announcements of monthly calls is at: https://groups.google.com/a/lbl.gov/g/singularity-devel

**Comment by dtrudg** [comment]
The initial issue with the incorrect MPI example is being corrected in docs via: https://github.com/hpcng/singularity-userdocs/pull/377
