### ISSUE TITLE
Unable to pull from docker://cern/cc7-base

### ISSUE THREAD

**Issue by jiafulow** [apptainer/singularity#5405]
### Version of Singularity:

```
$ singularity version

SingularityPRO version 3.5-1.el7
```

### Expected behavior

I would like to use the CentOS7 docker image provided by CERN. I tried the following but it did not work:

```
singularity pull docker://cern/cc7-base
```

When I tried the same with docker://busybox, it worked on this machine:

```
singularity pull docker://busybox
```

### Actual behavior

The output:

```
$ singularity pull docker://cern/cc7-base

INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:715da9c432e8415c4783891546166a0ebdc8ae89c9d792a5b840146a23b7eca7
Copying config sha256:19695b30c7f7a2f9f1451f3a3bc68f12aa65de03a48e693f0aafb29534a3b482
Writing manifest to image destination
Storing signatures
2020/06/30 00:49:33  info unpack layer: sha256:715da9c432e8415c4783891546166a0ebdc8ae89c9d792a5b840146a23b7eca7
... a bunch of warnings ...
ERROR:   build: failed to make environment dirs: mkdir /tmp/rootfs-15419d31-ba8d-11ea-b8db-008cfac91f10/.singularity.d: permission denied
FATAL:   While making image from oci registry: while building SIF from layers: packer failed to pack: while inserting base environment: build: failed to make environment dirs: mkdir /tmp/rootfs-15419d31-ba8d-11ea-b8db-008cfac91f10/.singularity.d: permission denied
```

It seems like there is a permission issue?

### Steps to reproduce this behavior

I simply called `singularity pull`:

```
singularity pull docker://cern/cc7-base
```

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
```

### How did you install Singularity

I'm not sure, because this is on a university machine (HiPerGator).

**Comment by dtrudg** [comment]
Hi @jiafulow - please note that SingularityPRO issues should generally be filed with Sylabs via support@sylabs.io. Could you open a ticket with use there, or ask your administrators to?

I will follow up on the issue here also with respect to the open-source version shortly.

**Comment by dtrudg** [comment]
A fix is in place for the upcoming open-source 3.6.0 version - see https://github.com/hpcng/singularity/pull/4958

As mentioned, please contact us via support@sylabs.io r.e. addressing this in SingularityPRO.

**Comment by jiafulow** [comment]
@dctrud Thanks for the reply! I didn't know that Singularity and SingularityPRO are different, I'll open a ticket with Sylabs as you suggested. It seems #4958 indeed fixes the issue, I'm sorry I didn't see that before opening this issue.
