### ISSUE TITLE
deadlink in INSTALL.md

### ISSUE THREAD

**Issue by antotorov** [apptainer/singularity#5411]
Hello

the link to https://sylabs.io/guides/3.6/admin-guide/installation.html, found on https://github.com/hpcng/singularity/blob/v3.6.0-rc.5/INSTALL.md, is dead.

Best
AR

**Comment by dtrudg** [comment]
Hello - 3.6.0 is still a release candidate and documentation has not been published yet, It will be made available when 3.6.0 final release is made.

We are aware of the issue of dead-links during this period. We will be working to auto-build the latest documentation, and switch our links to a `latest` location for the development version / release candidates in future.
