### ISSUE TITLE
Should be able to tell if label is inherited

### ISSUE THREAD

**Issue by rdenham** [apptainer/singularity#5413]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3
```

### Expected behavior

When building an image and inspecting the labels, you should be able to tell whether the label was set in the build or inherited from the bootstrap image

### Actual behavior

No indication that the label was set in the most recent build, or was inherited from the parent image set in the Bootstrap section.

It would be nice to be able to check the labels of an image to see information about that container. The example in the documentation uses `Version v0.0.1` as an example. But you can't tell if that label was set in the build, or was inherited from an image that was used as the basis of the current build.

This means that using labels to check the version of the container is potentially misleading, as it doesn't necessarily apply to the image you are inspecting.

### Steps to reproduce this behavior
Here is an example:

The first definition file `test1.def`

```
Bootstrap: docker
From: busybox

%labels
  Version v0.0.1
```
building and inspecting:

```
sudo singularity build test1.sif test1.def
 singularity inspect test1.sif

WARNING: No SIF metadata partition, searching in container...
Version: v0.0.1
org.label-schema.build-date: Friday_3_July_2020_10:43:46_AEST
org.label-schema.schema-version: 1.0
org.label-schema.usage.singularity.deffile.bootstrap: docker
org.label-schema.usage.singularity.deffile.from: busybox
org.label-schema.usage.singularity.version: 3.2.1
```

Now an update using a new definition file (`test2.def`)

```
Bootstrap: localimage 
From: test1.sif

%labels
  NotAVersion v0.0.2
```

```
sudo singularity build test2.sif test2.def

singularity inspect test2.sif
WARNING: No SIF metadata partition, searching in container...
NotAVersion: v0.0.2
Version: v0.0.1
org.label-schema.build-date: Friday_3_July_2020_10:45:19_AEST
org.label-schema.schema-version: 1.0
org.label-schema.usage.singularity.deffile.bootstrap: localimage
org.label-schema.usage.singularity.deffile.from: test1.sif
org.label-schema.usage.singularity.version: 3.2.1
```
If you were to check for the Version label in `test2.sif` its the same as in `test1.sif`, so could be misleading.

Our workaround is to also look at the def file and see if the label was set there, but this is awkward.
It would be good if you could tell that the label was inherited and not set in the most recent build.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

```

### How did you install Singularity

 source.

**Comment by dtrudg** [comment]
Within the label-schema that Singularity is using there isn't a great way to indicate this at present.

We are open to any thoughts on the issue that would not result in backward incompatibility etc.

**Comment by olechnwin** [comment]
Another vote for this. I'm also hoping there is a way to change the version when building from local image.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by rdenham** [comment]
Note that this issue isn't restricted to singularity, it is an issue for users of docker as well:

For example, [this stack exchange conversation](https://stackoverflow.com/questions/50978051/how-do-i-unset-a-docker-image-label). Essentially, since labels aren't cleared when you build a new container based on an existing one (in both Docker and singularity), then it is difficult to know what metadata is relevant to the current image, and what has come along from previous build steps.
