### ISSUE TITLE
Failed to mount squashfs filesystem: invalid argument

### ISSUE THREAD

**Issue by astrojhgu** [apptainer/singularity#5414]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version 
3.2.1
```

### Expected behavior

What did you expect to see when you do...?
Normally start a shell

### Actual behavior

What actually happend? Why was it incorrect?
failed to run and report the message
```
container creation failed: mount /proc/self/fd/3->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount squashfs filesystem: invalid argument
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
singularity -d shell <any sif file>

### What OS/distro are you running

```
$ cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="20.03.2447.afa9ca61924 (Markhor)"
VERSION_CODENAME=markhor
VERSION_ID="20.03.2447.afa9ca61924"
PRETTY_NAME="NixOS 20.03 (Markhor)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
write nix config file 
```
programs.singularity.enable = true;
```
The complete debug message output is in the attached debug.txt

[debug.txt](https://github.com/hpcng/singularity/files/4879254/debug.txt)

**Comment by dtrudg** [comment]
This issue is due to a mount option passed, which is not ignored on newer kernels and leads to an error.

Please use Singularity 3.5.3 to address this issue.
