### ISSUE TITLE
Can't build singularity: makeFile error

### ISSUE THREAD

**Issue by ImaneEF** [apptainer/singularity#5415]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3

```

### Expected behavior

What did you expect to see when you do...?

I am following the steps on this site: https://sylabs.io/guides/3.5/user-guide/quick_start.html.

Every step worked.

But when I wanted to build singularity, it didn't install.

### Actual behavior

What actually happend? Why was it incorrect?

I got this error.

```
[guest@localhost singularity]$ make -C builddir
make: Entering directory '/home/guest/singularity/builddir'
build github.com/containers/image/v5/types: cannot load github.com/containers/image/v5/types: open /home/guest/singularity/vendor/github.com/containers/image/v5/types: no such file or directory
 GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog imgbuild_engine oci_engine singularity_engine fakeroot_engine apparmor selinux"
build github.com/containers/image/v5/types: cannot load github.com/containers/image/v5/types: open /home/guest/singularity/vendor/github.com/containers/image/v5/types: no such file or directory
make: *** [Makefile:157: singularity] Error 1
make: Leaving directory '/home/guest/singularity/builddir'
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

They can follow the steps on this website: https://sylabs.io/guides/3.5/user-guide/quick_start.html.

### What OS/distro are you running

I am using Fedora 28 in a Virtual Machine. And I am also working in a conda environment.

### How did you install Singularity
See website: https://sylabs.io/guides/3.5/user-guide/quick_start.html.

**Comment by dtrudg** [comment]
Which version of Go are you using? Did you install Go from Fedora repos or from a binary download per the instructions?

Also - what do you have loaded in your conda environment?

Thanks.

**Comment by ImaneEF** [comment]
Hello dctrud!

Thank you!

I am using Go=1.13. And I installed from a binary download per the instructions as on the website.

In my conda environment I have also other tools loaded, a lot (Docker, certain tools for spatial transcriptomics, R). But the error speaks mostly of Go, so I assumed it would have to do with this?

If you could help, thank you!

**Comment by dtrudg** [comment]
Are you able to try with 3.6.1? There were a couple of tweaks to the build that possible clear some issues up.

**Comment by Lyn16** [comment]
Hi, I got a similar problem, and i am using GO=1.13 and Singularity=3.6.3
The error message for me is:

> make: Entering directory '/home/lyn/singularity/builddir'
 GEN GO DEP /home/lyn/singularity/builddir/starter.d
 GEN GO DEP /home/lyn/singularity/builddir/singularity.d
 GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
make: *** [Makefile:172: singularity] Error 1
make: Leaving directory '/home/lyn/singularity/builddir'

**Comment by dtrudg** [comment]
> Hi, I got a similar problem, and i am using GO=1.13 and Singularity=3.6.3
> The error message for me is:

> > [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
> > /usr/local/go/pkg/tool/linux_amd64/link: signal: killed

This is something different - the link process was running but was killed for some reason. Do you have memory / CPU limits on your system? Was there an error visible in the output of `dmesg` etc?

**Comment by Lyn16** [comment]
> > Hi, I got a similar problem, and i am using GO=1.13 and Singularity=3.6.3
> > The error message for me is:
> 
> > > [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
> > > /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
> 
> This is something different - the link process was running but was killed for some reason. Do you have memory / CPU limits on your system? Was there an error visible in the output of `dmesg` etc?

Yeah, you are right. I am actually installing singularity on a virtual machine. The problem is solved as I turn up the limit for base memory. Thanks a lot!!!

**Comment by dtrudg** [comment]
No follow-up from original reporter. Please re-open if you have further information with a current version of Singularity.
