### ISSUE TITLE
:rw not a valid bind option

### ISSUE THREAD

**Issue by bcosc** [apptainer/singularity#5416]
### Version of Singularity:

singularity version 3.5.2+301-gaa8ef04-dirty

`singularity exec --contain --pid --ipc --home /nethome/bcosca/tests/singularity/tmp:/home --bind /nethome/bcosca/tests/singularity/tmp:/tmp:rw --pwd /pwd /nfs/home/bcosca/tests/singularity/ubuntu.sif echo foo > /nethome/bcosca/tests/singularity/tmp/foo.txt`

### Expected behavior

What did you expect to see when you do...?

Create the file /nethome/bcosca/tests/singularity/tmp/foo.txt

### Actual behavior

What actually happend? Why was it incorrect?

I got an error:

FATAL:   while parsing bind path: while getting bind path: rw is not a valid bind option

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Run `singularity exec` with --bind and :rw as the mount option.

### What OS/distro are you running

CentOS Linux 7 (Core)

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

I did not personally install.

I'm aware that :rw is the default mount option, but I'm running this using cwltool, which automatically adds the :rw mount option.

**Comment by davidchristiany** [comment]
Same issue when I run singularity exec with Galaxy, it automaticly add an ":rw" at the end causing the error.
`while parsing bind path: while getting bind path: rw is not a valid bind option`
I use singularity 3.6.0

**Comment by pontus** [comment]
`singularity shell --help` specifically mentions `rw` for binding, so this may be somewhat confusing for users.

**Comment by bernt-matthias** [comment]
> Same issue when I run singularity exec with Galaxy, it automaticly add an ":rw" at the end causing the error.
> `while parsing bind path: while getting bind path: rw is not a valid bind option`
> I use singularity 3.6.0

@davidchristiany did you solve this for Galaxy .. I started working on a solution for Galaxy https://github.com/galaxyproject/galaxy/pull/10625 .. which would be to omit the default value
