### ISSUE TITLE
Python namespace collision on Cray XC40 SMW for `make dist`

### ISSUE THREAD

**Issue by fearful-symmetry** [apptainer/singularity#542]
So, `make dist` will run the script `configure_transform.py` script, which does this:

```
sys.path.append('../libexec/python')

from utils import (
    get_fullpath,
    read_file,
    write_file
)
```
On a cray XC40 SMW, `utils` aready exists:
```
>>> import utils
>>> help(utils)

NAME
    utils

FILE
    /opt/cray/install-support/3.3.2568-2.8/utils/__init__.py
```

Obviously, this results in an import error:

```
Traceback (most recent call last):
  File "./configure_transform.py", line 8, in <module>
    from utils import (
ImportError: cannot import name get_fullpath
```

We developed a temporary workaround by adding `sys.path.remove('/opt/cray/install-support/3.3.2568-2.8'` but this is obviously not a good long-term solution; path.insert() may work as well, to put `../libexec/python` at the beginning of the path.

**Comment by vsoch** [comment]
How nuts! This should be relatively easy to fix by renaming the module. I'll do this right away and then we will be able to test. Do you know/predict/see any other name conflicts?

**Comment by vsoch** [comment]
ok, I'm renaming to `sutils.py` (singularity utils) please poke me if there is a potential sutils conflict! I know about psutil, shutil, and (now) utils, and google searching I didn't find any obvious system packages called sutils.

**Comment by fearful-symmetry** [comment]
@vsoch Cray's packages add things from all over to `$PYTHONPATH` so it's a tad hard to anticipate weird edge cases. However, aside from that, the build process completed without issues.

**Comment by vsoch** [comment]
That's... cray cray :)

The change will still be good to fix this conflict - I'll let you know when it's ready for testing.

**Comment by vsoch** [comment]
Hi @dpjensen we've changed the name of utils - would you mind testing again with latest development branch?

**Comment by fearful-symmetry** [comment]
@vsoch pulled down the dev branch, `make dist` and building completed without problems.

**Comment by vsoch** [comment]
Awesome! Thanks for checking, closing issue.
