### ISSUE TITLE
v3.6.0 doesn't recreate environment of old images

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#5426]
### Version of Singularity:

3.6.0

### Expected behavior

Consider the following image created using an old version of Singularity that pre-dates the `/.singularity.d` directory structure.

```
$ singularity exec mytest.img cat /environment
# Define any environment init code here

if test -z "$SINGULARITY_INIT"; then
    PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/ctf/bin
    PS1="CTF> $PS1"
    export CTF_DIR=/opt/ctf
    SINGULARITY_INIT=1
    export PATH PS1 SINGULARITY_INIT
fi
export DEBUG_ENVLOADED=1
```
Watch how v3.5.3 handles this old image:

```
$ singularity --version
singularity version 3.5.3

$ singularity exec mytest.img env | grep -e '^PATH'
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/ctf/bin

```
This is correct.

### Actual behavior

Now see how v3.6.0 handles this image:

```
$ singularity --version
singularity version 3.6.0

$ singularity exec mytest.img env | grep -e '^PATH'
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
Note the incorrect `PATH`

### Steps to reproduce this behavior

Find (or create) an image with a version of Singularity that pre-dates the `/.singularity.d` directory structure.  Edit the PATH in the def file, and run it with 3.6.0

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

### How did you install Singularity

source build (from release tarball)

**Comment by dtrudg** [comment]
This would appear to be a regression of https://github.com/hpcng/singularity/issues/2233 for images created with singularity 2.2

**Comment by GodloveD** [comment]
It's kindof a show stopper preventing us from upgrading since we have over 130 apps installed as singularity containers and quite a few of them are old.

**Comment by dtrudg** [comment]
Per @cclerget you can try...

```diff
diff --git a/internal/pkg/util/fs/files/action_scripts.go b/internal/pkg/util/fs/files/action_scripts.go
index 39dfaec35..050edf0a3 100644
--- a/internal/pkg/util/fs/files/action_scripts.go
+++ b/internal/pkg/util/fs/files/action_scripts.go
@@ -107,7 +107,6 @@ else
     # this is for old images built with Singularity version prior to 2.3
     if test -f "/environment"; then
         source "/environment"
-        unset PATH
         export PATH="$(fixpath)"
     fi
     source "/.inject-singularity-env.sh"
```

**Comment by dtrudg** [comment]
Diff above will be worked into a PR with a regression test for 3.6.1

In the mean time, for anyone hitting this issue with 3.6.0 the single line patch (removing `unset PATH` in `action_scripts.go` should fix.

**Comment by GodloveD** [comment]
Thanks @dctrud and @cclerget .  Looking forward to reviewing the PR.
