### ISSUE TITLE
can't use writable overlays, "hook function for tag prelayer error"

### ISSUE THREAD

**Issue by marc1uk** [apptainer/singularity#5430]
### Version of Singularity:
```
$ singularity version
3.6.0-rc.5-dirty
```

### Expected behavior
```
mkdir -p overlay/upper
dd if=/dev/zero of=overlay.img bs=1M count=50 && mkfs.ext3 -d overlay overlay.img
singularity shell --overlay overlay.img alpine_testing.img
```
At which point i expect to obtain a singularity shell, with changes stored in the overlay.img.

### Actual behavior
Trying to start the container unprivileged fails:
```
singularity shell --overlay overlay.img alpine_testing.sif 
FATAL:   container creation failed: hook function for tag prelayer returns error: failed to create /home/marc/LinuxSystemFiles/Singularity/singularity-3.6.0-rc.5/var/singularity/mnt/session/overlay-images/0/work directory: mkdir /home/marc/LinuxSystemFiles/Singularity/singularity-3.6.0-rc.5/var/singularity/mnt/session/overlay-images/0/work: permission denied
```
note `/home/marc/LinuxSystemFiles/Singularity/singularity-3.6.0-rc.5/var/singularity/mnt/session` exists and is owned by root, made during installation.

If i first start the container as root:
`sudo /home/marc/LinuxSystemFiles/Singularity/singularity-3.6.0-rc.5/bin/singularity shell --overlay overlay.img alpine_testing.img`, it works, and I can write to `/` as expected.
Moreover after exiting the container, subsequent unprivileged invocations **also** work - the above error is not present - BUT attempting to write to the container `/` returns `read-only filesystem`.

What's especially strange is that I tried this yesterday and it seemed to work. Sometimes. I could always start a container, but sometimes attempting to `echo "kitty" > /kitty` would work, and other times it would return `read-only filesystem`, or `permission denied`. Removing the overlay and re-creating it seemed to clear the problem... but not today.
I have also tried removing and re-installing singularity, with no change.

### Steps to reproduce this behavior
Above... maybe?

### What OS/distro are you running
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
```

### How did you install Singularity
Built from source, as shown above in a non-system location:
```
export VERSION=3.6.0-rc.5 && ./mconfig --prefix=/home/marc/LinuxSystemFiles/Singularity/singularity-3.6.0-rc.5 && \
make -C builddir
sudo make -C builddir install
```

**Comment by dtrudg** [comment]
This was noted in Slack earlier today. As a workaround please add a `work` directory to your overlay and you should then be able to use the overlay image successfully, i.e.:

```
mkdir -p overlay/upper overlay/work
dd if=/dev/zero of=overlay.img bs=1M count=50 && mkfs.ext3 -d overlay overlay.img
singularity shell --overlay overlay.img alpine_testing.img
```

**Comment by marc1uk** [comment]
Thanks dctrud, that seems to do the trick. :D 
On a related issue, though, I've noticed that while I can now write to the root directory, I still need escalated privileges to install new packages in my overlay for testing. I would've expected that the ability to write to `/` would enable these sorts of actions? Is there another way of doing this that doesn't require `sudo` from the host?

**Comment by dtrudg** [comment]
@marc1uk - this is expected as package managers want to set ownership of things to root, and run things as root. For operations that need to run under a `root` account like package managers, you can user the `--fakeroot` functionality if your system supports unprivileged user namespaces and subuid/gid maps.

See: https://sylabs.io/guides/3.6/user-guide/fakeroot.html and https://sylabs.io/guides/3.6/admin-guide/user_namespace.html

**Comment by dtrudg** [comment]
The resolution for this will be to update the documentation, note in changelog, and ensure singularity issues a better error message.

The cause is that the RPC server is now operating with a limited set of capabilities. It's better to require that `work` is created with `upper` than open the capabilities up further than necessary.

**Comment by marc1uk** [comment]
This looks perfect, thanks for the reference drtrud. Unfortunately I've had some difficulties when giving it a go:
1. when running `singularity shell --fakeroot --overlay myoverlay.img container.sif` it prints:
`INFO:    Convert SIF file to sandbox...`
... for a large container (which i typically work with) i would prefer it not be converted to a sandbox?
2. After this completes, I do appear to be dropped into a shell as user `root`, but if I try to do `echo "kitty" > /kitty`, I get `/bin/sh: can't create /rootkitty: Read-only file system`
3. After exiting from the container, it prints:
`INFO:    Cleaning up image...`
suggesting the sandbox created in step 1 is destroyed. Would these changes not be persistently stored to my overlay?

**Comment by marc1uk** [comment]
Thanks for the reference dctrud, but I wonder if this quite gives the functionality I was hoping for. When I try running `singularity shell --fakeroot --overlay overlay.img my_image.sif` I get: shown
`INFO:    Convert SIF file to sandbox...`
after which trying to run `echo "kitty" > /kitty` returns `/bin/sh: can't create /kitty: Read-only file system`.

Reading through the pages you linked has left me a bit confused. It seems as though `fakeroot` uses user namespaces, but the section on user namespaces lists several restrictions, including:
>All containers must be run from sandbox directories. SIF images are extracted to a sandbox directory on the fly...

and

>Filesystem image, and SIF-embedded persistent overlays cannot be used.

which ties up with my observation above, and seems to suggest that fakeroot can only be used with sandboxes, not with persistent overlays. Is that correct?

**Comment by dtrudg** [comment]
@marc1uk - whoops, sorry. Yes, when running with `--fakeroot` here you are going through the 'unprivileged user namespace' flow in Singularity which will extract the container to a sandbox, as mounting directly from the SIF file (and from an overlay image file) needs real root level privilege.

You can `singularity build -s mysandbox my_image.sif` to generate a sandbox that will persist changes. Then use the `singularity shell --fakeroot --writable mysandbox` to make changes in the sandbox. When you are done, you can build back into a SIF with `singularity build my_new_image.sif my_sandbox`

This doesn't involve on overlay... but is how you can create a modified image without root privilege.

**Comment by marc1uk** [comment]
OK, many thanks for the clarifications

**Comment by ptempier** [comment]
Necromancing this as i just had the issue.
can the workaround be added to the doc ?

For me its  a side issue that the default fs created by apptainer itself only allows 65k files
Hence the need to make one separatly

**Comment by DrDaveD** [comment]
This repository is closed.  If `singularity --version` shows singularity-ce, please make a new issue at https://github.com/sylabs/singularity, otherwise make a new issue at https://github.com/apptainer/apptainer.
