### ISSUE TITLE
FATAL:   while opening capability config file: open /opt/go/src/github.com/sylabs/singularity/builddir/etc/singularity/capability.json: no such file or directory

### ISSUE THREAD

**Issue by akshayMpatel** [apptainer/singularity#5432]
### Version of Singularity:
3.5.3

### What OS/distro are you running
centos7 

### How did you install Singularity
rpm 

### Expected behavior
to run normally 

### Actual behavior
error message:

`FATAL:   while opening capability config file: open /opt/go/src/github.com/sylabs/singularity/builddir/etc/singularity/capability.json: no such file or directory`

### Steps to reproduce this behavior

as non-root with a root-installed singularity:

built container remotely with :
`singularity build --remote centos7_cat12-standalone.simg centos7_cat12-standalone.def
`
can run it without any user related flags on local machine as `my_user@machine1`
with :
```
singularity run \
--cleanenv \
--bind ~/singularity/cat12 \
centos7_cat12-standalone.simg \
-b ~/singularity/cat12/batch_file.txt \
~/singularity/cat12/data/file.nii 
```

then tried to run container within the `qlogin` interactive environment on our HPC as `my_user@machine2` with same command

**Comment by dtrudg** [comment]
Please could you provide the exact detail of how this rpm packages was built? Is it self-built or is it installed from EPEL? `rpm -qa | grep singularity`

The path `/opt/go/src/github.com/sylabs/singularity/builddir/etc/singularity/capability.json` suggests that a prefix was not set correctly for the install location - where is singularity actually installed, i.e. output of `which singularity`

**Comment by akshayMpatel** [comment]
yes indeed the problem was that the machine used for qlogin pointed to the old install of singularity not installed with rpm.  so we fixed that.  sorry for the confusion.
