### ISSUE TITLE
Singularity build: "Failed to create thread" in mksquashfs

### ISSUE THREAD

**Issue by dstndstn** [apptainer/singularity#5434]
### Version of Singularity:

singularity version 3.6.0-rc.4+70-gb15629c3d

### Expected behavior

```
$ ./builddir/singularity -v -d build /tmp/lolcow.sif docker://godlovedc/lolcow
DEBUG   [U=70558,P=18743]  persistentPreRun()            Singularity version: 3.6.0-rc.4+70-gb15629c3d
DEBUG   [U=70558,P=18743]  persistentPreRun()            Parsing configuration file /cm/shared/apps/singularity/3.6.0/etc/singularity/singularity.conf
DEBUG   [U=70558,P=18743]  handleConfDir()               /home/dlang/.singularity already exists. Not creating.
DEBUG   [U=70558,P=18743]  getCacheParentDir()           environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=70558,P=18743]  newBundle()                   Created temporary directory "/tmp/bundle-temp-611022516" for the bundle
DEBUG   [U=70558,P=18743]  newBundle()                   Created directory "/tmp/rootfs-681eac16-c7a8-11ea-ba9e-000af7d3f980" for the bundle
DEBUG   [U=70558,P=18743]  ensureGzipComp()              Ensuring gzip compression for mksquashfs
FATAL   [U=70558,P=18743]  runBuildLocal()               Unable to create build: while ensuring correct compression algorithm: while creating squashfs: create command failed: exit status 1: FATAL ERROR:Failed to create thread
```

This is on the head node of our cluster.  If I run on a compute node, however, it works!

Head and compute nodes are nearly the same hardware, but the head node has a 4 GB limit on the memory address space used.

Lowering the ulimit on the compute node, it works with 17 GB and doesn't work with 16 GB.... doesn't that seem like a LOT?

eg,

```
ulimit -v 17000000
./builddir/singularity build -F /tmp/lolcow.sif docker://godlovedc/lolcow
```

works, but
```
ulimit -v 16000000
./builddir/singularity build -F /tmp/lolcow.sif docker://godlovedc/lolcow
```
fails with
```
INFO:    Creating SIF file...
FATAL:   While performing build: while creating squashfs: create command failed: exit status 1:
FATAL ERROR: Out of memory (cache_alloc)
```

whereas it fails much earlier with
```
$ ulimit -v 8000000
$ ./builddir/singularity build -F /tmp/lolcow.sif docker://godlovedc/lolcow
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
FATAL:   Unable to create build: while ensuring correct compression algorithm: while creating squashfs: create command failed: exit status 1: FATAL ERROR:Failed to create thread
FATAL ERROR: Out of memory (cache_alloc)
```

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 381172
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 381172
virtual memory          (kbytes, -v) 4000000
file locks                      (-x) unlimited
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

### How did you install Singularity

From source.

**Comment by dtrudg** [comment]
Singularity uses `mksquashfs` to create image files, and that tool aggressively uses CPU and RAM by default to parallelize compression of fs images. What it does is generally appropriate on single-user systems, but not on large shared systems.

In 3.6.0 you can set some limits for it in `singularity.conf` with new options. This should be in the CHANGELOG but it looks like we may have inadvertently lost it in a merge.

```
# MKSQUASHFS PROCS: [UINT]
# DEFAULT: 0 (All CPUs)
# This allows the administrator to specify the number of CPUs for mksquashfs
# to use when building an image.  The fewer processors the longer it takes.
# To enable it to use all available CPU's set this to 0.
# mksquashfs procs = 0
mksquashfs procs = 0

# MKSQUASHFS MEM: [STRING]
# DEFAULT: Unlimited
# This allows the administrator to set the maximum amount of memory for mkswapfs
# to use when building an image.  e.g. 1G for 1gb or 500M for 500mb. Restricting memory
# can have a major impact on the time it takes mksquashfs to create the image.
# NOTE: This fuctionality did not exist in squashfs-tools prior to version 4.3
# If using an earlier version you should not set this.
# mksquashfs mem = 1G
```

**Comment by dstndstn** [comment]
(note that the MEM part says "mkswapfs" in one place -- presumably that's supposed to be "mksquashfs")

**Comment by dstndstn** [comment]
Thank you very much for pointing it out!  However, doesn't seem to help:

```
$ /cm/shared/apps/singularity/3.6.0/bin/singularity -v -d build /tmp/lolcow.sif docker://godlovedc/lolcow
DEBUG   [U=70558,P=32406]  persistentPreRun()            Singularity version: 3.6.0
DEBUG   [U=70558,P=32406]  persistentPreRun()            Parsing configuration file /cm/shared/apps/singularity/3.6.0/etc/singularity/singularity.conf
DEBUG   [U=70558,P=32406]  handleConfDir()               /home/dlang/.singularity already exists. Not creating.
DEBUG   [U=70558,P=32406]  getCacheParentDir()           environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=70558,P=32406]  newBundle()                   Created temporary directory "/tmp/bundle-temp-815544628" for the bundle
DEBUG   [U=70558,P=32406]  newBundle()                   Created directory "/tmp/rootfs-61489b4f-c7b7-11ea-8821-000af7d3f980" for the bundle
DEBUG   [U=70558,P=32406]  ensureGzipComp()              Ensuring gzip compression for mksquashfs
FATAL   [U=70558,P=32406]  runBuildLocal()               Unable to create build: while ensuring correct compression algorithm: while creating squashfs: create command failed: exit status 1: FATAL ERROR:Failed to create thread
```

```
$ grep mksquashfs /cm/shared/apps/singularity/3.6.0/etc/singularity/singularity.conf
# This allows the administrator to specify the location for mksquashfs if it is not
# mksquashfs path =
# This allows the administrator to specify the number of CPUs for mksquashfs
# mksquashfs procs = 0
mksquashfs procs = 1
# can have a major impact on the time it takes mksquashfs to create the image.
mksquashfs mem = 1G
```

where squashfs-tools is

```
$ mksquashfs -version
mksquashfs version 4.3-git (2014/06/09)
```

Any further hints?
Thanks!

**Comment by dtrudg** [comment]
It looks like `mksquashfs` is going to allocate >4GB of virtual mem on the large mem host, regardless of how much actual memory it is going to use, or is requested to use with `-mem`

I have an 80GB host here, and running manually under these conditions (not through Singularity) It will fail even with a minimum `-mem 16M`....

```
$ ulimit -v 4000000

$ mksquashfs sandbox squash -mem 16M
FATAL ERROR:Failed to create thread
```

If I take the ulimit off then I can see that when running `$ mksquashfs sandbox squash -mem 16M` it is indeed claiming a 10.3g VIRT memory allocation... but the RES shows it's not using that.

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 946632 dave      20   0   10.3g  44380   2632 T   0.0   0.1   0:24.58 mksquashfs
```

If I run within a smaller VM with 4GB RAM I'm seeing  much smaller VIRT allocation of around 1.8GB

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 2022 dave      20   0 1912268  29708   2344 T   0.0   0.8   0:13.86 mksquashfs
```

There isn't really anything we can do about this, as Singularity is calling out to the OS provided `mksquashfs` and we don't have any way of influencing its behavior other than with the `-mem` and `-cpu` flags.

**Comment by dstndstn** [comment]
If I'm understanding the code correctly, the `ensureGzipComp` function is NOT passing the -mem and -processor limits to mksquashfs, and that is where it's failing for me -- it crashes when singularity is "while ensuring correct compression algorithm"

**Comment by dtrudg** [comment]
@dstndstn - thanks - that is an issue to fix, we should be passing the args there too, and we'll fix that.

There is still a bit of nasty behavior for ulimit cases because of the behavior I showed when I ran `mksquashfs` manually while passing the `-mem` flag - where mem ulitmately doesn't control vmem usage.

```
$ ulimit -v 4000000

$ mksquashfs sandbox squash -mem 16M
FATAL ERROR:Failed to create thread
```

Adding `-processors 1` does actually bring us down so that it works withing the ulimit in this case - but it's a pretty blunt instrument, making things rather slow.

Fixing `ensureGzipComp` will give that blunt instrument for this case though. Thanks for looking through  this and sorry I glossed over it!

**Comment by dstndstn** [comment]
Hi,

Thanks for this, but it doesn't work -- I think you missed the first call to mksquashfs, here
https://github.com/hpcng/singularity/blob/master/internal/pkg/build/build.go#L244

When I run it in strace, with the squashfs entries added to my config file, I still see

execve("/usr/bin/mksquashfs", ["/usr/bin/mksquashfs", "/tmp/bundle-temp-895619362/squashfs-gzip-comp-test-src518496281", "/tmp/bundle-temp-895619362/squashfs-gzip-comp-test-127708324", "-noappend"], [/* 59 vars */] <unfinished ...>

and it fails with the same

FATAL   [U=70558,P=26919]  runBuildLocal()               Unable to create build: while ensuring correct compression algorithm: while creating squashfs: create command failed: exit status 1: FATAL ERROR:Failed to create thread

**Comment by dstndstn** [comment]
I can send a PR if you like

**Comment by dtrudg** [comment]
I'll fix this today... sorry for not doing so well on this one, and we missed it through review too. Will be taken care of.

**Comment by dstndstn** [comment]
No problem, I'm super impressed with the fast turn-around!  (And I just tested by creating a wrapper script ~/bin/mksquashfs that always adds the -mem and -processors command-line args -- I should have thought of that earlier! -- and it completed!)  So I'm optimistic that this change will result in a successful build in this highly constrained environment!  Thanks again!

**Comment by dstndstn** [comment]
I confirm that this works for me!  Thank you kindly!
