### ISSUE TITLE
Add --silent option for disabling print statements

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#544]
We currently have different levels to control logging of errors, however this doesn't map cleanly to print statements that we (usually) want to show "no matter what." For example, if a user wants to run a container and pipe the result somewhere, this breaks (see issue example here https://github.com/singularityware/singularity/pull/514). Thus, we should add a `--silent` option that triggers a boolean variable to not print any extraenous things. This is different (I think) from --quiet, which doesn't totally disable absolutely every print statement (specifically those not tied to the [bot.logger](https://github.com/singularityware/singularity/blob/development/libexec/python/logman.py) dude.)

**Comment by gmkurtzer** [comment]
I think the comment I wrote at https://github.com/singularityware/singularity/pull/514#issuecomment-290925032 may have bee better suited here.

I do not agree with a `--silent` option that has a different code pathway then how we are currently doing messaging throughout the rest of the code.

On the other hand, using the existing messaging interface, I could see `--silent` simply making the `SINGULARITY_MESSAGELEVEL` a negative number such that even warnings/errors aren't printed.

**Comment by vsoch** [comment]
@gmkurtzer the difference would be totally aesthetic - given that the logger is used instead of print, it would be like:

```bash
INFO:python:Found image vsoch/singularity-images
INFO:python:Decompressing image...
```

vs. just having a printed statement:

```bash
Found image vsoch/singularity-images
Decompressing image...
```

What about if we used the logger level to determine the print statement? Like:

```
if logger.level > 0:
    print("Decompressing image...")
```

That way we have the control done by same logging function and levels, but the user experience isn't "debuggy" Thoughts?

**Comment by gmkurtzer** [comment]
That is a good question. Im not sure as I don't have enough experience with how the python logging/messaging is done. I leave it in your best judgement, but if possible, at some point I think it would be good if it works the same as the C and shell code (if it already does then awesome!). :)

Thanks!

**Comment by vsoch** [comment]
This issue will close when #553 is merged.
