### ISSUE TITLE
support for rinse as a bootstrap agent for red hat and opensuse variants

### ISSUE THREAD

**Issue by 0xaf1f** [apptainer/singularity#545]
I just wanted to make this suggestion. `rinse` is analogous to `debootstrap` and might be worth supporting as a singularity boostrap agent for rpm-based distributions.

https://anonscm.debian.org/cgit/collab-maint/rinse.git/tree/README

**Comment by gmkurtzer** [comment]
This is a great idea! Are you interested in taking a stab at this and helping us out? If so, you will find the bootstrap drivers are basically shell scripts and pretty easy to follow. please work in the development GitHub branch, and let us know if you have any questions (here or in Slack).

If not, I think it is a good idea, and will take a look at it as time permits.

Thanks!

**Comment by 0xaf1f** [comment]
Sure, I think I can give it a go.

**Comment by dtrudg** [comment]
Hello. As this issue hasn't generated any other requests for rinse support I'm going to close it. Pleas feel free to reopen if you wish, and any PRs are always appreciated.
