### ISSUE TITLE
`rootfs` directories not being cleaned up

### ISSUE THREAD

**Issue by wood-chris** [apptainer/singularity#5450]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3
```
(this is a system I'm just a user on, I've raised a ticket to update it to 3.6.1)

### Expected behavior

the `rootfs-*` directory is cleaned up / removed when a container exits

### Actual behavior

It doesn't, but seemingly only intermittently

### Steps to reproduce this behavior

if I run `ls -ltr`, I see things like

```
-rw-------  1 chrishpc hpcgroup 328904704 Jul 21 17:38 archive-058669191
drwx------ 25 chrishpc hpcgroup      4096 Jul 21 17:39 rootfs-216397256
-rw-------  1 chrishpc hpcgroup 328904704 Jul 21 18:15 archive-836816612
drwx------ 25 chrishpc hpcgroup      4096 Jul 21 18:16 rootfs-300312409
-rw-------  1 chrishpc hpcgroup 328904704 Jul 21 18:17 archive-087142136
drwx------ 16 chrishpc hpcgroup      4096 Jul 21 18:17 rootfs-959916221
-rw-------  1 chrishpc hpcgroup 328904704 Jul 21 20:07 archive-267786980
drwx------ 25 chrishpc hpcgroup      4096 Jul 21 20:08 rootfs-338084697
```

note that some of these are more than 6 hours old. I've just run the container again, and there is no new `rootfs-*` directory

These have been generated from an mpirun:

```
mpirun -n 2 --mca btl_vader_single_copy_mechanism none singularity exec -B /etc/libibverbs.d --pwd $HOME/containers/data/input myimg.sif /opt/model/bin/model
```

(The model runs do complete successfully.)

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"

```

### How did you install Singularity

Unknown - it's a system I'm a user on.

However, I do know the following which might be interesting:

 - it was installed with `allow setuid = no` (so containers get run as sandboxes)
 - /tmp is _really_ small, so we set tmp variables as:

```
$ export SINGULARITY_TMPDIR=$PWD
$ export TMPDIR=$PWD
```

note that I'm in a subdirectory of $HOME when I run my container - someone else realised that if you're in $HOME, Singularity seems to get into a horrible recursion about trying to mount $HOME when its own tmp variable it's mounting into is also $HOME (presumably unless you use `-c`)... 

 - this is on slurm - but there is nothing else in the job script apart from job request info

**Comment by wood-chris** [comment]
Just to also add I see this in Singularity 3.6.1 too

**Comment by dtrudg** [comment]
Noting from Slack conversation
>ChrisW - when you run without setuid the SIF file cannot be mounted, so it is extracted to a temporary directory. There is a cleanup that should run to remove these at the end of container execution. If it is not running or finishing on jobs that are cancelled/interrupted then scheduler timeouts are something to look at, i.e. the delta between SIGTERM and SIGKILL being sent by the scheduler etc.
8:41
The best thing to do on the issue would be to run singularity with the -d flag (singularity -d ...) and provide those log messages. Also anything that shows up in stdout/stderr output from the job from SLURM.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by wood-chris** [comment]
I see this had the #needsinvestigation tag added - I'm not sure if DaveD got round to looking in more detail. Let me know if there's any more info I can provide
