### ISSUE TITLE
Instance auto restart

### ISSUE THREAD

**Issue by anderspitman** [apptainer/singularity#5451]
### Version of Singularity:
```
3.5.2
```

Does singularity have any concept of automatically restarting when the container returns a nonzero code? This would be similar to Docker's "restart policy": https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy

This is useful for things like web apps which can crash but you want them to restart immediately and use the logs for debugging.

**Comment by dtrudg** [comment]
Singularity does not have this as we don't have a supervising daemon to co-ordinate this. The design is intentionally daemon-less.

What we advise is to run Singularity containers under the supervision of systemd or similar. See e.g. https://sylabs.io/guides/3.6/user-guide/running_services.html#system-integration-pid-files

**Comment by anderspitman** [comment]
That makes sense. So it must just store some simple flat files for keeping track of running instances?

**Comment by dtrudg** [comment]
Yes - there are files stored under `~/.singularity/instances`.... 

```
dave@piran~/.s/instances> pwd
/home/dave/.singularity/instances
dave@piran~/.s/instances> tree .
.
├── logs
│   └── piran.home.randomroad.net
│       └── dave
│           ├── tests.err
│           └── tests.out
└── sing
    └── piran.home.randomroad.net
        └── dave
            └── tests
                └── tests.json

7 directories, 3 files
```

**Comment by anderspitman** [comment]
Nice, I'm a big fan of the simple design.
