### ISSUE TITLE
singularity pull error

### ISSUE THREAD

**Issue by kimchitsigai** [apptainer/singularity#5453]
### Version of Singularity:

3.6.0

### Steps to reproduce this behavior

`singularity --debug pull tensorflow_latest.sif docker://tensorflow/tensorflow:latest`

### Expected behavior

tensorflow_latest.sif sucessfully created

### Actual behavior

> DEBUG   [U=300328,P=35436] persistentPreRun()            Singularity version: 3.6.0
DEBUG   [U=300328,P=35436] persistentPreRun()            Parsing configuration file /singularity/singularity-3.6.0-se/etc/singularity/singularity.conf
DEBUG   [U=300328,P=35436] handleConfDir()               /home/kimchitsigai/.singularity already exists. Not creating.
DEBUG   [U=300328,P=35436] parseURI()                    Parsing docker://tensorflow/tensorflow:latest into reference
INFO    [U=300328,P=35436] pull()                        Converting OCI blobs to SIF format
DEBUG   [U=300328,P=35436] newBundle()                   Created temporary directory "/tmp/bundle-temp-069197213" for the bundle
DEBUG   [U=300328,P=35436] newBundle()                   Created directory "/tmp/rootfs-623979d2-ccc0-11ea-9a99-08f1ea8fac60" for the bundle
DEBUG   [U=300328,P=35436] ensureGzipComp()              Ensuring gzip compression for mksquashfs
FATAL   [U=300328,P=35436] pullRun()                     While making image from oci registry: error fetching image to cache: while building SIF from layers: unable to create new build: while ensuring correct compression algorithm: while creating squashfs: create command failed: exit status 1: FATAL ERROR:Failed to create thread

### What OS/distro are you running

>$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"
 

### How did you install Singularity

Singularity was compiled and installed by root with setuid_enabled.

### Remarks

Other commands like:
`singularity build --sandbox tensorflow_sandbox/ docker://tensorflow/tensorflow:latest`
and
singularity shell, singularity exec work correctly.

### singularity.conf

>allow setuid = yes
max loop devices = 256
allow pid ns = yes
config passwd = yes
config group = yes
config resolv_conf = yes
mount proc = yes
mount sys = yes
mount dev = yes
mount devpts = yes
mount home = yes
mount tmp = yes
mount hostfs = no
bind path = /etc/localtime
bind path = /etc/hosts
user bind control = yes
enable fusemount = yes
enable overlay = try
enable underlay = yes
mount slave = yes
sessiondir max size = 16
allow container squashfs = yes
allow container extfs = yes
allow container dir = yes
allow container encrypted = yes
always use nv = no
always use rocm = no
root default capabilities = full
memory fs type = tmpfs
mksquashfs procs = 4
mksquashfs mem = 40G
shared loop devices = no
image driver =

**Comment by dtrudg** [comment]
This is fixed in `3.6.1`  - You will need to use `3.6.1` as a bug meant that in `3.6.0` the mksquashfs procs and mem limits were not applied to all `mksquashfs` calls.

See #5434

**Comment by ZhaoxuanZhu** [comment]
> This is fixed in `3.6.1` - You will need to use `3.6.1` as a bug meant that in `3.6.0` the mksquashfs procs and mem limits were not applied to all `mksquashfs` calls.
> 
> See #5434

I am running `singularity version 3.7.0-1.el7` and still got the almost identical fatal error. I am fairly new to container stuff. Is this primarily related to the size of the image?

**Comment by dtrudg** [comment]
@ZhaoxuanZhu - does your system impose process or memory limits on sessions? If so Singularity must be configured by setting the appropriate values in `singularity.conf`.
