### ISSUE TITLE
Singularity 3.6.0rc5+ requires CAP_IPC_LOCK for all containers?

### ISSUE THREAD

**Issue by jthiltges** [apptainer/singularity#5458]
We run Singularity jobs inside Docker containers. We noticed failures after updating to 3.6.0-1.el7 (from EPEL):

```
ERROR  : Requesting capability set 0x00000000082440c0 while permitted capability set is 0x00000000a82c25fb
FATAL:   container creation failed: mount tmpfs->/var/singularity/mnt/session error: while mounting tmpfs: can't mount tmpfs filesystem to /var/singularity/mnt/session: write unix @->@: write: broken pipe
INFO  Singularity at /usr/bin/singularity failed 
```

This followed back to #5362 which added an `CAP_IPC_LOCK` requirement.

We resolved the Docker issue by updating the container config to include `--cap-add=IPC_LOCK`.

Is `CAP_IPC_LOCK` planned to be a requirement for all containers, or encrypted only?

**Comment by dtrudg** [comment]
IPC_LOCK is only needed for encrypted containers, but the portion of code that sets privilege and caps for the RPC server would have to be modified to add logic to exclude the IPC_LOCK if there is no encrypted container in use.

I don't think we have any plans to do this, as we are trying to keep those caps/priv handling sections as simple as possible, and singularity in docker (at least without `--privileged`) is considered a bit of a niche case use generally. We'd definitely consider a PR though, or any documentation suggestions to clear things up.

**Comment by jthiltges** [comment]
That makes sense. Thank you very much for the info.
