### ISSUE TITLE
How to make container directories within /home/ visible even when mounting user's $HOME?

### ISSUE THREAD

**Issue by marc1uk** [apptainer/singularity#5460]
### Version of Singularity:
```
$ singularity version
3.6.0-rc.5-dirty
```
### Issue
I'm creating a singularity container to replicate a system setup in which other users' home directories are read-accessible - which includes having some software placed in `/home/softwarename`.
While creating a sandbox (as the `root` user) I created these directories, but now find that when I shell into the container as a non-root user the directories are not visible.

### Expected behavior
```
singularity shell --writable sandbox/
ls `/home/`
```
I would expect to see my own $HOME (`/home/$USER`) as well as those created within the container (`/home/softwarename`). 

### Actual behavior
Instead I see only my own home - unless I use either `sudo` to start the container, or else the `--no-home` option, but then my host files aren't accessible (which is undesirable).
I could see that should there be a clash between the user's home directory and one in the container, this could cause problems, but is there a way to achieve this?

### What OS/distro are you running
```
$ cat /etc/os-release
"Debian GNU/Linux 9 (stretch)"
```

### How did you install Singularity
From source.

**Comment by jmstover** [comment]
IIRC this happens because of how the mounts work. If you need something from the container /home, you may want to use the `-H` option to set a temporary home for your user in the container. Something like:

```
$ mkdir -p sandbox/tmphome
$ /usr/local/singularity/3.5.3/bin/singularity shell -H ${HOME}:/tmphome --writable ubuntu/
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount /home/jason/tmp/sing [cwd]: /home/jason/tmp/sing doesn't exist in container
Singularity> echo $HOME  
/tmphome
Singularity> pwd
/tmphome
Singularity> ls -l /home/
total 0
drwxr-xr-x 1 root root 0 Jul 28 16:02 containeru1
drwxr-xr-x 1 root root 0 Jul 28 16:02 containeru2
Singularity> 
```

This should set `HOME` in the container to the value of `/tmphome` for your user.

When you use `--writable` ... it can't automatically create the mountpoint to you need to be sure it already exists in the container.

**Comment by marc1uk** [comment]
ok, thanks jmstover, i guess that seems like a reasonable solution.
