### ISSUE TITLE
--writable-tmpfs fails on Fedora 32 (5.7 kernel?)

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5461]
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.6.1
```

### Actual behavior

On my Fedora 32 system `--writable-tmpfs` is now failing....

```
dave@piran~> singularity shell --writable-tmpfs docker://alpine
INFO:    Using cached SIF image
FATAL:   container creation failed: mount overlay->/usr/local/var/singularity/mnt/session/final error: while mounting overlay: can't mount overlay filesystem to /usr/local/var/singularity/mnt/session/final: permission denied
```

Wiping out all trace of the singularity install and starting afresh doesn't fix it - so there isn't anything strange with my session dir causing this.

It appears to be possibly kernel version related as I'm sure it worked before - and it continues to work on a different Fedora 32 machine still running a slightly older kernel.

Fails: 5.7.9-200.fc32.x86_64 #1 SMP Fri Jul 17 16:23:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Works: 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### What OS/distro are you running

```
Fedora 32
5.7.9-200.fc32.x86_64 #1 SMP Fri Jul 17 16:23:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### How did you install Singularity

3.6.1 source

**Comment by dtrudg** [comment]
Confirmed this is a kernel related issue. Booted this machine back into the 5.6.6-300 and it still works:

```
dave@piran~> uname -a
Linux piran.home.randomroad.net 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
dave@piran~> singularity shell --writable-tmpfs docker://alpine
INFO:    Using cached SIF image
Singularity>
```

Something between `5.6.6` and `5.7.9` is causing an issue with the overlay mount for `--writable-tmpfs`.

**Comment by cclerget** [comment]
@dctrud Could you give a try to #5463 when you get a chance ?

**Comment by dtrudg** [comment]
```
dave@piran~> uname -a
Linux piran.home.randomroad.net 5.7.10-201.fc32.x86_64 #1 SMP Thu Jul 23 00:58:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
dave@piran~> singularity version
3.6.1+4-g5417e6b82
dave@piran~> singularity shell --writable-tmpfs test.sif
Singularity>
```

@cclerget  Working here. I'll try to get to a proper PR review soon. Cheers!
