### ISSUE TITLE
container insists on trying (and failing) to bind /etc/localtime even when --containall is passed

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#5465]
There exists a container [here](https://hub.docker.com/layers/afni/afni_cmake_build/AFNI_20.2.06/images/sha256-a9920bfa3234aad31d6c3a5eb9ce26ec8139d2dadb53ea6e14926f081aee300e?context=explore) in which `/etc/localtime` is a symlink pointing to the **directory** `/usr/share/zoneinfo`.  

There exists a cluster in which `/etc/localtime` is a symlink pointing to the **file** `/usr/share/zoneinfo/America/Denver`.  

There exists a container platform that sensibly refuses to bind mount a file on to a directory:
```
$ singularity shell afni_cmake_build_latest.sif
FATAL:   container creation failed: mount /etc/localtime->/etc/localtime error: while mounting /etc/localtime: could not mount /etc/localtime: not a directory
```

In v3.5, the `--containall` flag would prevent Singularity from trying (and failing) to perform this unattainable feat.  But the 3.6 version of Singularity perseveres in spite of the `--containall` flag.
```
$ singularity --version
singularity version 3.6.1

$ singularity shell --containall afni_cmake_build_latest.sif
FATAL:   container creation failed: mount /etc/localtime->/etc/localtime error: while mounting /etc/localtime: could not mount /etc/localtime: not a directory
```

And now there exists a user who has no way to run a bunch of containers.  😢 

Can someone help?

**Comment by cclerget** [comment]
Here the true story ;-),

The issue is lying in afni docker image build instead, `/etc/localtime` should point to a file not a directory.

According to https://github.com/afni/afni/pull/195 :

```
RUN TZ=Europe/Minsk \
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

`TZ` here is set for the spawned `ln` process therefore is not evaluated for the current line that's why the image create a `/etc/localtime` symlink pointing to `/usr/share/zoneinfo/`

To fix that, an export is required :

```
RUN export TZ=Europe/Minsk && \
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

**Comment by leej3** [comment]
Thanks @cclerget. I just thought the breakage was the fact that I was writing to that file in the first place, which I just assumed was bad practice. I had missed that nuance of the effect of not exporting the variable and how that was causing me trouble.  That's a gotcha I will bear in mind for future. I have only recently started to make an effort to make the image compatible with rootless singularity execution so I'm not too worried about the past offending images. If the change in `--containall` behavior for v3.6.1 is intended then that sounds good to me.

**Comment by cclerget** [comment]
@leej3 Cool ! Yes this is the expected behavior with changes from https://github.com/hpcng/singularity/pull/4926 to fix this old issue #1707, so `/etc/hosts` and `/etc/localtime` are always mounted no matter the configuration and options, since the code rely on the type of the mount point source where `hosts` and `localtime` are files, Singularity attempted to mount a file to a directory.

**Comment by leej3** [comment]
Makes sense. Thanks. And thanks for the help with my woes @GodloveD!

**Comment by GodloveD** [comment]
It makes total sense that `/etc/localtime` should be bind mounted into the container regardless of the settings.  In a case like this though I wonder why this should be a fatal error and not just a warning.  The user may not care if `/etc/localtime` is correct for their application.  Why not just warn and carry on with life?

**Comment by dtrudg** [comment]
Agreed that this isn't really a FATAL issue for a container... would be nice if we can have it as a warning _if_ it's straightforward to do so. Having not looked yet, I'm guessing the logic may tied up with the staging / mount of other things like resolv.conf, passwd... which are more FATAL if they don't happen.

**Comment by dtrudg** [comment]
Turns out this is a little involved to be able to mark a bind mount as something that is allowed to fail. I'm working up a proposal for a strategy that I will ask for comment on as a draft PR.
