### ISSUE TITLE
Pull FATAL Error from docker as "Failed to create thread"

### ISSUE THREAD

**Issue by ajkotobi** [apptainer/singularity#5469]
### Version of Singularity:

What version of Singularity are you using? Run:

```
Singularity version: 3.5.3

```

### Expected behavior

What did you expect to see when you do...? 

Pull image from docker hub by 

`singularity -d pull docker://bvlc/caffe:cpu`

### Actual behavior

What actually happend? Why was it incorrect?

Is it related to [issue 5453](https://github.com/hpcng/singularity/issues/5453)

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

```
singularity -d pull docker://bvlc/caffe:cpu

DEBUG   [U=12417,P=25228]  persistentPreRunE()           Singularity version: 3.5.3
DEBUG   [U=12417,P=25228]  handleConfDir()               /pf/b/b324017/.singularity already exists. Not creating.
DEBUG   [U=12417,P=25228]  parseURI()                    Parsing docker://bvlc/caffe:cpu into reference
DEBUG   [U=12417,P=25228]  newBundle()                   Created temporary directory "/tmp/bundle-temp-062743103" for the bundle
DEBUG   [U=12417,P=25228]  newBundle()                   Created directory "/tmp/rootfs-60f35b52-d58f-11ea-8b50-0cc47a6c2f16" for the bundle
DEBUG   [U=12417,P=25228]  ensureGzipComp()              Ensuring gzip compression for mksquashfs
FATAL   [U=12417,P=25228]  pullRun()                     While making image from oci registry: while building SIF from layers: unable to create new build: while ensuring correct compression algorithm: while creating squashfs: create command failed: exit status 1: FATAL ERROR: Out of memory (frag_thrd)
FATAL ERROR:Failed to create thread

```

### What OS/distro are you running

```
$ cat /etc/os-release

LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Red Hat Enterprise Linux Server release 6.10 (Santiago)
Red Hat Enterprise Linux Server release 6.10 (Santiago)

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

SPACK package manager which is from source

**Comment by dtrudg** [comment]
This is already addressed in Singularity 3.6.1

If you have limited RAM (via ulimit or similar), or you have a lot of cores without large amounts of RAM, then the default behavior of mksquashfs which Singularity calls to create SIF images can exhaust memory.

You will need to update to 3.6.1 and use the mksquashfs options in `singularity.conf` to limit the memory usage of mksquashfs. Note that in RHEL 6.10 the version of mksquashfs is very old, and you may only be able to limit CPU usage (which limits RAM usage indirectly).
