### ISSUE TITLE
Bind locations persist outside of container

### ISSUE THREAD

**Issue by jaredslosberg** [apptainer/singularity#5473]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.6.0
```

### Expected behavior

In order to create a singularity shell with access to appropriate directories, I called a singularity shell with bind. The bind should only exist within the container.

### Actual behavior

After exiting the singularity shell, the tmp directory (which was bound to a directory on my computer) still existed, and removing it with 

``` 
rm -r tmp
```

removed the tmp directory as well as the the /existing-directory bound to it.

### Steps to reproduce this behavior

```
singularity shell --bind /scratch,/existing-directory:/scratch/tmp_within_container container_image.sif
```
I bound scratch, and bound a separate existing directory to a tmp directory (which previously did not exist) within scratch. 

I exited the container, and "tmp_within_container" was an existing directory that persisted on my machine. Removing it, as above, removed my /existing-directory to which it was bound.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

### How did you install Singularity

I am a user on a lab-wide server. I can get info it is necessary.

**Comment by dtrudg** [comment]
~I'm not able to replicate this with a default config. Nothing remains on the host when exiting the container:~

_edit - wasn't correct as jmstover pointed out... please see comment further below_

```
dave@piran~> ls scratch existing-directory
existing-directory:

scratch:

dave@piran~> singularity shell --bind /home/dave/scratch,/home/dave/existing-directory:/scratch/tmp_within_container docker://alpine
INFO:    Using cached SIF image
Singularity> exit

dave@piran~> ls scratch existing-directory
existing-directory:

scratch:
```


Could you send debug output with `singularity -d ....` so that we can see if your installation is using underlay or is unprivileged etc.?

What are the filesystems in use here?

**Comment by jmstover** [comment]
@dctrud ... Not exactly the same thing... can you make a `/scratch` on your system and bind mount in as `/scratch` in the container? Then have your other directory mounted as:  `/scratch/tmp_within_container` ... 

Without more info it half looks like `/scratch` in the container is being unmounted, but `/scratch/tmp_in_container` was still bind mounted.

**Comment by dtrudg** [comment]
:facepalm: yep, let's try this again....

```
04:42 PM $ ls -l /scratch existing-directory
existing-directory:
total 0

/scratch:
total 0

04:42 PM $ singularity shell --bind /scratch,/home/dave/existing-directory:/scratch/tmp_within_container docker://alpine
INFO:    Using cached SIF image
Singularity> ls /scratch/
tmp_within_container
Singularity> exit

04:42 PM $ ls -l /scratch existing-directory
existing-directory:
total 0

/scratch:
total 4
drwxr-xr-x. 2 dave dave 4096 Aug  4 16:42 tmp_within_container/

04:42 PM $ rm -r /scratch/tmp_within_container/

04:42 PM $ ls -l /scratch existing-directory
existing-directory:
total 0

/scratch:
total 0
```

So... `tmp_within_container` is created under `/scratch` as expected as it's needed to bind `existing-directory` there. But if I remove it it does not take away `existing-directory`.... the bind is not in force once I've exited the container.

I think we need the `singularity -d ...` debug information from @jslosbe1 still

**Comment by jaredslosberg** [comment]
Though I was able to repeat at the time of posting, I can't seem to reproduce to provide the debug info. I will keep an eye out for it. Apologies!

**Comment by dtrudg** [comment]
@jslosbe1 - thanks I'll close this but please reopen if you come across it.
