### ISSUE TITLE
apt-get upgrade requires superuser privilige in singularity 3.5.3

### ISSUE THREAD

**Issue by s0r2637** [apptainer/singularity#5474]
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.5.3

```

<
singularity build -s ubuntu_latest docker://ubuntu:latest
singularity shell --writable ubuntu_latest/
apt-get update -y
apt-get upgrade -y
>
Expected behavior:
Successful upgrades to the Ubuntu OS

Actual behavior:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  base-files libseccomp2 libsystemd0 libudev1
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 453 kB of archives.
After this operation, 3072 B of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 base-files amd64 11ubuntu5.1 [60.1 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libsystemd0 amd64 245.4-4ubuntu3.2 [271 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libudev1 amd64 245.4-4ubuntu3.2 [78.9 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libseccomp2 amd64 2.4.3-1ubuntu3.20.04.3 [42.4 kB]
Fetched 453 kB in 1s (747 kB/s)       
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
debconf: delaying package configuration, since apt-utils is not installed
dpkg: error: requested operation requires superuser privilege
E: Sub-process /usr/bin/dpkg returned an error code (2)

Requiring super-user previlige

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"


```

### How did you install Singularity

I don't know.  it was installed by the HPC admin.

**Comment by dtrudg** [comment]
This is expected. Package managers like `apt` need to work as `root`. You will need to either run singularity as root, or use the `--fakeroot` option if your system is configured to allow this. See https://sylabs.io/guides/3.6/user-guide/fakeroot.html
