### ISSUE TITLE
In v3.6 current working directory in home is not bound if --no-home is used

### ISSUE THREAD

**Issue by luator** [apptainer/singularity#5478]
### Version of Singularity:

    3.6.1

### Expected behavior

When running a container with `--no-home` directly in the home directory, I expect that my home directory is bound in the container despite the `--no-home` as it is the current working directory.

It is described like this in `singularity shell -h`:

>       --no-home                do NOT mount users home directory if home
>                                is not the current working directory

Also in previous versions of Singularity this was the case (tested with 3.5.3).

### Actual behavior

Home is not bound.  Inside the container, the initial pwd is `/`.

The same happens when calling it from any subdirectory of my home.

### Steps to reproduce this behavior

    $ cd ~
    $ singularity shell --no-home foobar.sif
    Singularity> ls

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


```

### How did you install Singularity

From source

**Comment by dtrudg** [comment]
This is a consequence of the changes to `CWD` handling in `3.6.0` which mean we don't handle the `CWD` if the mount point isn't in the container already.

This means the behaviour is expected, and the help message is wrong. Could you confirm @cclerget

**Comment by cclerget** [comment]
I think this is a typo, should be :

```
  --no-home                do NOT mount users home directory if /home
                           is not the current working directory
```

Because if the CWD is `/home` all user home directories will be mounted
