### ISSUE TITLE
obsolete executables

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#55]
Are ftrace and ftype still required?  They are still built, but I think they are obsolete.  (ftrace prevents building on non-x86 architectures.)

**Comment by gmkurtzer** [comment]
I was hoping to use ftrace again to create a default definition file by figuring out what packages and files are needed by an application/workflow (which is why it is still there).

**Comment by gmkurtzer** [comment]
I have disabled ftrace from being built in [master 23f6380]. Will reenable when I'm ready to use it.

**Comment by loveshack** [comment]
You wrote: 

> I was hoping to use ftrace again to create a default definition file
> by figuring out what packages and files are needed by an
> application/workflow.

Ah, sorry.  It would probably help getting it into distributions if the
x86 restriction was widened.  I can solicit Fedora ppc and arm expertise
when appropriate.

**Comment by gmkurtzer** [comment]
That is a good point, but ftrace is pretty easy to port. I'm aware that IBM did some work porting it to Power just recently (granted, I haven't gotten their patch yet), but it should be pretty straight forward... For when I do decide to use it again.

Thanks!
