### ISSUE TITLE
Running multiple instances of image results in neither finishing

### ISSUE THREAD

**Issue by hopoffbaby** [apptainer/singularity#5503]
### Version of Singularity: 
```
> singularity --version
singularity version 3.6.1-1.el7

```

### Expected behavior

I have a self contained MATLAB benchmark. When running a single instance of the image using:
```
singularity run --writable-tmpfs -C /tmp/qdls.sif
```
The simulation runs to completion without issue.

Running 2+ instances of this image should work without issue.

### Actual behavior

When running 2+ instances of the same image the behaviour is unstable. Sometimes both will hang, other times 1 will hang. This means that I cannot run multiple instances of this image via a job scheduler. I have tried setting the work dir to individual directories. I have tried writing to locations other than /tmp. To get this to run at all I had to set sessiondir max size = 2000 as it seems the default transient FS size is 16MB, unless I am completely misreading this?

### Steps to reproduce this behavior

Build image using this recipe file:

```
Bootstrap: docker
From: hpc-p-prf-nx3:18080/polaris/mcr:7.R2017b-1.1

%files
./run_QDLS.sh /home/appuser/sim/
./ChannelListDLS.csv /input/

%post
yum install -y curl
curl -u prf:password http://hpc-p-prf-nx3/repository/prf-storage/singularity/qdls/benchmark/QDLS_5.9.0.29_dev -o /home/appuser/sim/QDLS
curl -u prf:password http://hpc-p-prf-nx3/repository/prf-storage/singularity/qdls/benchmark/YearTest_v1_5.9.0.29__R728.tar -o /input/YearTest_v1_5.9.0.29__R728.tar
cd /input 
tar -xzvf YearTest_v1_5.9.0.29__R728.tar
rm -fv YearTest_v1_5.9.0.29__R728.tar
chmod -R 777 /input
chmod -R 777 /home/appuser

%environment
export MCR_CACHE_ROOT=/scratch

%runscript
mkdir -m 777 /scratch 
mkdir -p /vdg-software/DLS/Validation/5.9.0.29__R728/YearTest_v1/Control/ExampleW11_ATM
mkdir -p /vdg-software/DLS/Validation/5.9.0.29__R728/YearTest_v1/Output/ExampleW11_ATM
mkdir -p /vdg-software/DLS/Validation/5.9.0.29__R728/YearTest_v1/PostProcessed/ExampleW11_ATM

mkdir -p /vdg-software/DLS/Validation/5.9.0.29__R728/YearTest_v1/Control/ExampleW11_STM
mkdir -p /vdg-software/DLS/Validation/5.9.0.29__R728/YearTest_v1/Output/ExampleW11_STM
mkdir -p /vdg-software/DLS/Validation/5.9.0.29__R728/YearTest_v1/PostProcessed/ExampleW11_STM

mkdir -p /vdg-software/DLS/CodeSource/Builds/DLS/

cd /vdg-software/DLS/Validation/5.9.0.29__R728/YearTest_v1

ln -s /input/Control/ExampleW11_ATM/ExampleW11_ATM_0001.importer Control/ExampleW11_ATM/ExampleW11_ATM_0001.importer
ln -s /input/Control/ExampleW11_ATM/ExampleW11_ATM_0001.json Control/ExampleW11_ATM/ExampleW11_ATM_0001.json

ln -s /input/Control/ExampleW11_STM/ExampleW11_STM_0001.importer Control/ExampleW11_STM/ExampleW11_STM_0001.importer
ln -s /input/Control/ExampleW11_STM/ExampleW11_STM_0001.json Control/ExampleW11_STM/ExampleW11_STM_0001.json

ln -s /input/Files Files

cd /vdg-software/DLS/CodeSource/Builds/DLS/
ln -s /input/ChannelListDLS.csv ChannelListDLS.csv

#eval /home/appuser/sim/run_QDLS.sh /opt/MATLAB/MATLAB_Runtime/v93 /vdg-software/DLS/Validation/5.9.0.29__R728/YearTest_v1/Control/ExampleW11_ATM/ExampleW11_ATM_0001.importer "$@"
eval /home/appuser/sim/run_QDLS.sh /opt/MATLAB/MATLAB_Runtime/v93 /vdg-software/DLS/Validation/5.9.0.29__R728/YearTest_v1/Control/ExampleW11_STM/ExampleW11_STM_0001.importer "$@"
```

I have to do all the symlinking because the filesystem is read-only in anything that is created as part of the %post step (on another point, is there a way to prevent this so it works more like docker, such that all the storage is transient at runtime).

### What OS/distro are you running

```
> cat /etc/*release*
CentOS Linux release 7.7.1908 (Core)
Derived from Red Hat Enterprise Linux 7.7 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.7.1908 (Core)
CentOS Linux release 7.7.1908 (Core)
cpe:/o:centos:centos:7

```

### How did you install Singularity

Via RPM

**Comment by hopoffbaby** [comment]
Interestingly it also seems like most of the time, when I kill one of the containers that is hung, it immediately triggers a segmentation fault in the other container.

**Comment by hopoffbaby** [comment]
I received this message when running the containers in debug mode, soon before the container hangs:

DEBUG   [U=1334,P=1]       StartProcess()                Received signal child exited

**Comment by dtrudg** [comment]
Does the MATLAB code use the parallel toolbox? The fact that runs block each other, and killing one container causes a segfault in the other suggests that maybe they are trying to use network comms on the same port or something similar.

**Comment by hopoffbaby** [comment]
> Does the MATLAB code use the parallel toolbox? The fact that runs block each other, and killing one container causes a segfault in the other suggests that maybe they are trying to use network comms on the same port or something similar.

Potentially. Unfortunately the bofins who wrote it are unavailable. Is there a way I can remove it's access to the external network similar to docker. So there are no Comms unless I expose a port. 

Also messing around with debug mode I notice that quite often it hands on a startprocess line

**Comment by dtrudg** [comment]
Yes - try `--net --network none` to give the container a localhost network only. See:

https://sylabs.io/guides/3.6/user-guide/networking.html#net

There's also a small chance MATLAB is looking at the system process list to work out stuff... and you can separate that for the container with the `--pid` option. I would suggest trying `--pid` before the net stuff.

**Comment by hopoffbaby** [comment]
Hi @dctrud 

I have already tried the --pid option but that doesnt seem to help. I'll try with the options you suggest and report back.

My current run command now is:

singularity -d run --writable-tmpfs -C --pid --net --network none qdls.sif

Cheers

**Comment by hopoffbaby** [comment]
@dctrud 

You, my friend, are a genius! That works great now, both multiple instances on a node and 1000's of instances via a scheduler. I had been convinced that the problem was related to the filesystem and hadn't even considered network conflicts.

Out of interest, do you have any suggestions on debugging I can do to narrow down exactly what network comms were occurring here to cause the problem.

Thanks,
Neil.

**Comment by dtrudg** [comment]
Heh - not a genius - but I was previously an HPC admin at a site with lots of MATLAB usage.

I'd suggest using `netstat -l -p --protocol=inet,inet6` when you are running one instance without `--net` to see if it is grabbing ports to listen on.

**Comment by hopoffbaby** [comment]
Ok I'll try that out when I'm back in the office. So happy to have it working, I spent 2 days scratching my head as to what was going on here. Nearly accepted allowing people to be part of the docker group and throw security out the window.

Have a virtual beer 🍻!!

Don't suppose you know much about the writable-tmpfs? It seems that stuff written here is using memory instead of disk space? Is there a config to control that as running the cluster fully loaded with matlab is quite tight on memory, without each contain adding the mcrcache to memory too.

Thanks
