### ISSUE TITLE
Singularity tries to enforce 700 permissions to ~/.singularity even with SINGULARITY_CACHEDIR set

### ISSUE THREAD

**Issue by khurtado** [apptainer/singularity#5517]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.6.0-1.el7

```

### Expected behavior

If `SINGULARITY_CACHEDIR` is set, singularity doesn't even try to enforce any permissions to the default directory `~/.singularity`, because it should not be used at all. 

### Actual behavior
Singularity tries does create $SINGULARITY_CACHEDIR, but it tries to enforce 700 permissions to both `SINGULARITY_CACHEDIR` and `~/.singularity`.
This is a problem whtn `~/.singularity` is not writable. We have this situation when running singularity via condor jobs that by default point HOME to an AFS path, where we don't have the proper AFS tokens to write to `~/.singularity` 

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
```
$ export SINGULARITY_CACHEDIR=/tmp/.singularity_$USER
$ singularity shell /afs/crc.nd.edu/x86_64_linux/s/singularity/images/pytorch-1.7.sif
WARNING: Couldn't enforce permission 0700 on /home/khurtado/.singularity: chmod /home/khurtado/.singularity: operation not permitted
FATAL:   could not open image /afs/crc.nd.edu/x86_64_linux/s/singularity/images/pytorch-1.7.sif: failed to retrieve path for /afs/crc.nd.edu/x86_64_linux/s/singularity/images/pytorch-1.7.sif: lstat /afs: no such file or directory
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

```

rpm -qa | grep singularity
singularity-3.6.0-1.el7.x86_64
https://github.com/hpcng/singularity/releases/tag/v3.6.0
```

**Comment by dtrudg** [comment]
The permission enforcement isn't a hard fail, it's just spitting a warning here.
 
```
WARNING: Couldn't enforce permission 0700 on /home/khurtado/.singularity: chmod /home/khurtado/.singularity: operation not permitted
```

This fatal error shouldn't be related to that at all. There is no involvement of cache etc. here.

```
FATAL:   could not open image /afs/crc.nd.edu/x86_64_linux/s/singularity/images/pytorch-1.7.sif: failed to retrieve path for /afs/crc.nd.edu/x86_64_linux/s/singularity/images/pytorch-1.7.sif: lstat /afs: no such file or directory
```

Since it's an `lstat on /afs` that if failing there is likely some kind of afs specific issue going on here. Please could you try with `3.6.1` and post debug output with `singularity -d ...` and also output of `mount`. Thanks.

**Comment by khurtado** [comment]
Hi @dctrud ,

Ahh, I actually made a mistake while testing this. I was on the wrong shell session, on a machine without afs. If I simply copy the image to a location that can be read, I indeed only see a warning. 

```
$ singularity shell /tmp/pytorch-1.7.sif
WARNING: Couldn't enforce permission 0700 on /home/khurtado/.singularity: chmod /home/khurtado/.singularity: operation not permitted
Singularity> exit
exit
```

I will therefore close this issue. Thank you and sorry for the noise.
