### ISSUE TITLE
Cross compilation for aarch64

### ISSUE THREAD

**Issue by AdamOlech** [apptainer/singularity#5525]
I'd like to build Singularity from sources for the **aarch64** architecture in buildroot, but I am at loss on how to do that. I will try to  briefly describe the steps that I have already undertaken which unfortunately did not yield a successful result.

To be clear, I am trying to build the **3.5.3** version. This is by no means necessary - I'll be happy to build another version if I have to.

For starters, I needed to disable kernel capability checks. There's no point in checking host kernel capabilities if I am building for another target -  I am aware of the targets capabilities so this is safe.

I am using the following command to **configure** the build: `./mconfig --prefix=/usr -C $(TARGET_CC) -X $(TARGET_CC) `, where `TARGET_CC` is the path to Buildroot's GCC cross-compiler.

...and this command to actually perform the build: `GOARCH=arm64 CC_FOR_linux_arm64=$(TARGET_CC) CC=$(TARGET_CC) CGO_ENABLED=1 make -C ./builddir`

Because of the fact that some Go code is compiled during the build and is needed to perform the build itself I had to patch `mlocal/frags/build_scripts.mk` so that host code is **not** being built by Buildroot's toolchain: `$(V) env -u CC_FOR_${GOARCH} -u GOARCH -u CC $(GO) run $(GO_MODFLAGS) $(SOURCEDIR)/scripts/expand-env.go < $< > $@`

I am unfortunately getting this error: `collect2: fatal error: cannot find 'ld'`. That's because there's no such thing in Buildroot's fakeroot. We need to use `aarch64-buildroot-linux-gnu-ld`. That's okay though, these are Buildroot quirks that I need to work around (but what I would need is the ability to set all the paths to binaries needed to perform the build - currently `mconfig` doesn't seem to expose this functionality, although I realize this should be a simple task).

Now that I've (hopefully) painted the picture of what I am trying to accomplish I'd like to ask if there's anything that I'm missing on. Is there something that I should know? Maybe I am approaching this from a wrong angle?

Any help or guidance would be most appreciated.

**Comment by dtrudg** [comment]
Closing this issue as it is a usage question that has been posted for 90 days and is not active.

For usage questions you are encouraged to use the Slack channel and/or mailing list which have a community of users present who will see and often kindly answer queries.

We close stale usage questions in order that the issues tracker can focus on problems that are bugs in Singularity, and feature requests.

**Comment by Metatron2k2** [comment]
Hi Adam,
sadly I am facing similar issues and was wondering if you ever got this resolved.  If yes, would you mind sharing your findings?

**Comment by AdamOlech** [comment]
@Metatron2k2, yes, we've managed to come up with a rather ugly workaround by patching some buildsystem-related files. You can find the patches in our Buildroot fork in the [apptainer package](https://github.com/antmicro/buildroot/tree/2021.02.2-antmicro-main/package/apptainer) (you should be looking at the patches series 0002-0008). Do note that the patches should be applied on top of version `1.1.5`, however they should work for newer releases as well. 

For instructions on how to actually build Apptainer using a cross-compiler, you can refer to the [package recipe](https://github.com/antmicro/buildroot/blob/2021.02.2-antmicro-main/package/apptainer/apptainer.mk) -- notably you should be looking at the sections `APPTAINER_CONFIGURE_CMDS` and `APPTAINER_BUILD_CMDS`.

Keep in mind that we only tested this when cross-compiling for `aarch64` on `x86_64`.

**Comment by Metatron2k2** [comment]
Hi Adam!
Thanks for your help. I am buildin with yocto, but I am quite sure i can integrate your patches and settings here too
