### ISSUE TITLE
Issue with sudo path when requiring sudo with singularity/singularity-compose

### ISSUE THREAD

**Issue by serbinsh** [apptainer/singularity#5538]
I had included this issue in this thread but wanted to move the last part here: https://github.com/singularityhub/singularity-compose-simple/issues/1

### Version of Singularity: 3.6.2

What version of Singularity are you using? Run:

```
$ singularity version
3.6.2
```

### Expected behavior

What did you expect to see when you do...?
singularity-compose build

### Actual behavior

What actually happend? Why was it incorrect?
required sudo and when provided sudo pass, root could not find singularity on the $PATH. I updated root .bashrc as

. /data/software/singularity/3.6.2/etc/bash_completion.d/singularity

Which is where singularity is installed; shared cluster resource

To fix this I had to run 
visudo

and edit

Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/data/software/singularity/3.6.2/bin

The singularity-compose worked (because root could find singularity on the $PATH).  I suspect this is user error and i have missed a step in setting up the singularity module, etc

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release
[sserbin@modex jupyter-simple]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

**Comment by dtrudg** [comment]
Hi @serbinsh - this is expected. `sudo` sets a default safe value of PATH, and you need to manually edit it include any non-standard `PATH` due to a non-standard install location of `singularity`.

`singularity-compose` could probably work out the absolute path of singularity as the normal user, and use that absolute path in any `sudo` call it needs to make. I'm not clear though if it is doing the `sudo` call, or if you are running singularity-compose as root, after sudo.

This isn't something that is fixable in Singularity.

**Comment by serbinsh** [comment]
OK.  For reference I am not doing sudo singularity-compose, its calling/using sudo, I think, because its setting up web services.  In any event I think my work around is fine for me.  Thanks for getting back to me!
