### ISSUE TITLE
The error occurred at singularity installed on step make with url connected

### ISSUE THREAD

**Issue by honghh2018** [apptainer/singularity#5539]
Hi @all,
      Thanks to develop the great tools for different node platform analysis with grid calculate.
       I follow your installation instrument to setup the sugularity sparked error when it reach step 'make' got error as connect with
       internet.
       So, how to solve this internet connect issue when install the singularity. because i really confirm the internet access were good.  
![image](https://user-images.githubusercontent.com/41668708/91692356-d5581800-eb9b-11ea-808a-7555492e3ccf.png)
the error showing below,
![image](https://user-images.githubusercontent.com/41668708/91693655-f3267c80-eb9d-11ea-86ab-56f521f90066.png)

        Finally, how can i fix this problem?
        Best,
         hanhuihong

**Comment by dtrudg** [comment]
Duplicate of: https://github.com/hpcng/singularity/issues/5543
