### ISSUE TITLE
bash shell from environment scripts not exported with Singularity 3.6

### ISSUE THREAD

**Issue by thdesy** [apptainer/singularity#5541]
### Version of Singularity:

What version of Singularity are you using? Run:

  singularity version 3.6.1-1.el7
on
  3.10.0-1127.8.2.el7.x86_64

### Expected behavior

functions that are defined in environment scripts under /singularity.d/env/ or in the action scripts /.singularity.d/actions/  or .singularity.d/*script should be exported into the container shell when exported with 'export -f'

e.g.,

```
> cat .singularity.d/env/99-debug.sh

!/bin/bash
#set -euo pipefail
# IFS=$'\n\t'

function testfnc {
    echo "Lorem Ipsum"
}
export -f testfnc

echo "============================="
echo "in 99-debug.sh"
env
echo "-----"
echo "shell: ${SHELL}"
echo "-----"
echo "whatami: $0"
echo "-----"
echo "cat $0 :"
cat $0 
echo "-----"

```

### Actual behavior

functions defined and exported in 
  /singularity.d/env/
  /.singularity.d/actions/
  /.singularity.d/*script
are not exported into the container instance. E.g., while starting a shell into a container, the export of the example env/fcn script above throws a

`declare: invalid option "-f"`

The behaviour appears only with Singularity version 3.6

After downgrading to 
  3.5.3-1.1
the function got exported into the shell.

* initially, /bin/sh is symlinked in the container to /bin/bash - to avoid interference from bash running in a sh compatibility modus, all shebangs in /.singularity.d/actions/shell and /.singularity.d/env/* got changed to '/bin/bash' (problem persists)

* additional obersvation: echo statements in 
  /.singularity.d/actions/shell
are not printed

### Steps to reproduce this behavior

* update from 3.5 to 3.6

* define/add functions to an environment script in /.singularity/env or ro the shell or other action script and export it in the same script via 'export -f fcnname'

* add echo statements to the shell script  

* run/shell into the container with Singularity 3.6.*
  `singularity shell --cleanenv --contain  /path/to/container/sandbox.d`

* functions are not exported and an error 'declare: invalid option "-f" ' is thrown, no echos strings are printed. 

* optionally: change all /bin/sh in the scripts under /.singularity.d to /bin/bash to exclude bash's sh-compatibility mode (does not change the behaviour)

* afterwards within an shell session, I can as user than execute/source the action shell script or the env scripts successfully and they behave as expected and export/print/... their content.

### What OS/distro are you running

behaviour is the same for Singularity v3.6.* on
  CentOS release 6.10 (Final)
  CentOS Linux release 7.8.2003 (Core)
  Fedora release 32 (Thirty Two)

## How did you install Singularity

CentOS: epel
Fedora: build script on source

**Comment by dtrudg** [comment]
This looks like an unanticipated outcome from the changes in 3.6 to environment handling, and the use of an embedded shell interpreter for some tasks (introduced to support minimal containers with no shell in them). Generally the assumption has been that use  of `%environment` and `.singularity.d/env` scripts will be posix sh compatible, as that's all we can assume given `/bin/sh` is across different containerized distros. The use of bash-isms didn't come up during the discussion for these changes or the 3.6 release-candidate period, so was not tackled explicitly.

@cclerget - can you confirm this is the situation? I don't believe there is an easy way around this?

As an aside, please note that the `actions/` scripts are not really intended to be modified by the user. They are defined in the runtime codebase to implement the runtime behavior necessary for a specific version of Singularity. Though they are added to a container on build (primarily for compatibility reasons), those copies may not be used when a container is run. Singularity may bind in its current set of action scripts, or in future handle actions completely differently.

**Comment by cclerget** [comment]
@thdesy Yes, this is due to the new shell interpreter not supporting function export, it supports most of bash syntax but builtins lack of some real bash features. It's also surprising that bash posix mode support import/export of shell functions.

You can workaround this issue with something like :

```
bootstrap: docker
from: ubuntu

%environment
    action="${0##*/}"
    file="/debug"

    case "${action}" in
    shell)
        if [ "${SINGULARITY_SHELL:-}" = "/bin/bash" ]; then
            set -- --noprofile --rcfile $file
        elif test -z "${SINGULARITY_SHELL:-}"; then
            export SINGULARITY_SHELL=/bin/bash
            set -- --noprofile --rcfile $file
        fi
        ;;
    exec)
        export BASH_ENV="$file"
        set -- /bin/bash --noprofile --norc -c "exec $@"
        ;;
    run)
        set -- /bin/bash --noprofile --rcfile $file
    esac

%post
    cat > /debug <<EOF
#set -euo pipefail

function testfnc {
    echo "Lorem Ipsum"
}
export -f testfnc

echo "============================="
echo "in debug.sh"
env
echo "-----"
echo "shell: \${SHELL}"
echo "-----"
echo "whatami: \$0"
echo "-----"
EOF
```

**Comment by thdesy** [comment]
Hi @cclerget - many thanks for having a look! I will try the workaround :)
