### ISSUE TITLE
how can i using the singularity on centos7 sge platform 

### ISSUE THREAD

**Issue by honghh2018** [apptainer/singularity#5543]
Hi @all,
     I already install the singularity and create the sif file ,but i can not running the singularity on another node.
     On my case, i can not throw the mission into node1 using singularity? if i do that , the mission disppear soon without any warning but not runing.
    Any advice would be appreciated.
    Best,
     hanhuihong

**Comment by honghh2018** [comment]
Hi @All,
    how to  build singularity at my own hand instead of using yum install singularity to install? 
    Build the singularity on step 'make' just alway failed to connect to internet or url .  
    how can i fix this issue to GEN GO DEP step, it failed completely at most of time.
![image](https://user-images.githubusercontent.com/41668708/92322373-71ce5e80-f063-11ea-920b-7137e8d8c519.png)

    any advice would be appreciated.
    Regards,
    hanhuihong

**Comment by dtrudg** [comment]
Your computer is unable to connect to the Go proxy service hosted by Google.

If you are in china, then it may have been blocked. See: https://github.com/goproxy/goproxy.cn

You may also disable the proxy attempts: https://golang.org/doc/go1.13#tools

```
go env -w GOPROXY=direct
go env -w GOSUMDB=off
```
