### ISSUE TITLE
combine mount contents

### ISSUE THREAD

**Issue by DevinBayly** [apptainer/singularity#5551]
### Version of Singularity:

```
singularity version 3.6.0-1.el7
```
### Expected behavior
I'd like `/etc/X11` to not be completely overwritten by contents from the container's `/etc` because I need both of their contents to correctly configure vglrun to work with programs installed in the singularity environment.

### Actual behavior

with no `-B` mounting the entire directory of `/etc` is replaced, and with binding I retain `/etc/X11` but lose all the specific contents from the container.

### What OS/distro are you running

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


```

### How did you install Singularity
Not sure, the infrastructure team handled that.

**Comment by dtrudg** [comment]
This isn't currently possible, as a bind mount mount by definition replaces the fs tree below the mount point.

It would require using an approach such as an overlay filesystem mount with a lower dir of the container `/etc/X11`, and and upper dir of the host `/etc/X11`. 

There may be some kind of way to do it by experimenting with:

- User namespace, fakeroot
- Bind mount the host `/etc/X11` into the container at a different location e.g. `/host/X11`
- Use `fuse-overlayfs` in the container to construct the overlay

It's definitely a little involved to line all of the pieces up.

I would advise, for now, identifying the specific files you need to bind in from the host, and binding each one explicitly from host into the container.

Generally I haven't seen issues needing bind-in of things for VirtualGL. Do you have a specific setup that requires some custom configuration?

**Comment by DevinBayly** [comment]
Thanks for all this info! You brought up something that I think might be the direction I proceed
> I would advise, for now, identifying the specific files you need to bind in from the host, and binding each one explicitly from host into the container.

does the `-B` flag work this way? I thought I could only use it with directories? If its a different process to bind specific files could you give me an example?

> Generally I haven't seen issues needing bind-in of things for VirtualGL. Do you have a specific setup that requires some custom configuration?

I'm trying to use vglrun with xpra inside of singularity, and there's a couple of places I've seen some instructions, but yes I think custom configuration is required. The xpra website https://xpra.org/trac/wiki/Usage/OpenGL#VirtualGLsetup , and especially  https://xpra.org/trac/wiki/Xdummy/#DriverConflictslibGL explains that you need to  make the `/etc/X11/xorg.conf` file with the `nvidia-xconfig` command. This has already been done on the HPC, but we lose this file, or `xorg.conf.d` in my case, upon entering the singularity instance. It's also possible I'll have a tougher scenario to work out where I'll have to follow the instructions here https://virtualgl.org/Documentation/HeadlessNV, and pass the gpu info when I run `nvidia-xconfig`. 

Hopefully I just have to bind the specific `xorg.conf.d` file and then `vglrun` will behave properly.

**Comment by dtrudg** [comment]
To bind a single file... it's just the same syntax as for a directory, e.g.

```
dave@ythel:~
04:49 PM $ echo "HELLO" > myfile

dave@ythel:~
04:49 PM $ singularity run -B myfile:/etc/myfile docker://alpine
INFO:    Using cached SIF image
Singularity> cat /etc/myfile
HELLO
```

**Comment by DevinBayly** [comment]
Excellent, sorry for delay, this will certainly take care of my needs. Thanks so much.
