### ISSUE TITLE
source: open /.singularity.d/env/01-base.sh: operation not permitted

### ISSUE THREAD

**Issue by JoKalliauer** [apptainer/singularity#5552]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.6.0

```

### Expected behavior

```
$ singularity exec --bind /opt/abaqus ~/imgs/sing/abaqus-centos-7.img /opt/abaqus/CAE/2019/linux_a64/code/bin/ABQLauncher cae -mesa
Abaqus License Manager checked out the following license:
"cae" from Flexnet server l1.zserv.tuwien.ac.at
<12 out of 15 licenses remain available>.
```

### Actual behavior

```
$ singularity shell ~/imgs/sing/abaqus-centos-7.img
source: open /.singularity.d/env/01-base.sh: operation not permitted
source: open /.singularity.d/env/10-docker2singularity.sh: operation not permitted
source: open /.singularity.d/env/90-environment.sh: operation not permitted
source: open /.singularity.d/env/94-appsbase.sh: operation not permitted
source: open /.singularity.d/env/95-apps.sh: operation not permitted
source: open /.singularity.d/env/99-base.sh: operation not permitted
FATAL:   failed to open /bin/sh for inspection: failed to open elf binary /bin/sh: open /bin/sh: operation not permitted
```

### Steps to reproduce this behavior
The *.def-file: https://github.com/JoKalliauer/abaqus-centos-7-singularity/blob/master/abaqus-centos-7.def
```
BootStrap: docker
From: centos:7

OSVersion: 7

MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/

Include: yum

%files
    assets/2018/ /abqbuild/
    assets/VirtualGL.repo /etc/yum.repos.d
    assets/VirtualGL.key /abqbuild/
    assets/graphicsConfig.env.ext /abqbuild/

%setup
    mkdir -p ${SINGULARITY_ROOTFS}/iso-unpacked/
    mkdir -p ${SINGULARITY_ROOTFS}/cfgs/
    cp assets/VirtualGL.repo ${SINGULARITY_ROOTFS}/etc/yum.repos.d
    cp assets/UserIntentions_DOC.xml ${SINGULARITY_ROOTFS}/cfgs/
    cp assets/simulation-services-UserIntentions_CODE.xml ${SINGULARITY_ROOTFS}/cfgs/
    cp assets/cae-UserIntentions_CODE.xml ${SINGULARITY_ROOTFS}/cfgs/
    cp assets/UserIntentions_CAA_Additional.xml ${SINGULARITY_ROOTFS}/cfgs/

%post
    cd /iso-unpacked/
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    yum install -y VirtualGL glx-utils 
    yum install -y ksh redhat-lsb-core perl VirtualGL libjpeg-turbo
    yum clean all && rm -rf /var/cache/yum

    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    until yum makecache -y --disablerepo='*' --enablerepo='VirtualGL'; do :;done
    yum install -y ksh redhat-lsb-core perl VirtualGL libjpeg-turbo which gcc-gfortran vim gcc-c++ glibc.i686
    yum clean all && rm -rf /var/cache/yum

    mkdir /calc

%environment
    export PATH=/opt/abaqus/Commands:/opt/abaqus/2017/Commands:$PATH

%runscript
    vglrun abaqus cae -mesa

%labels
Maintainer jordan@fsm.tu-darmstadt.de
Version v0.2
```

 see https://github.com/JoKalliauer/abaqus-centos-7-singularity
```bash
mkdir -p ~/imgs/sing
rm -f ~/imgs/sing/abaqus-centos-7.img
git clone https://github.com/JoKalliauer/abaqus-centos-7-singularity.git
cd ./abaqus-centos-7-singularity
sudo singularity build ~/imgs/sing/abaqus-centos-7.img ./abaqus-centos-7.def 

singularity exec --bind /opt/abaqus ~/imgs/sing/abaqus-centos-7.img vglrun /opt/abaqus/CAE/2019/linux_a64/code/bin/ABQLauncher cae -mesa
```
more details see https://github.com/JoKalliauer/abaqus-centos-7-singularity

### What OS/distro are you running

```
$ cat /etc/os-release
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

```

### How did you install Singularity
 see https://github.com/JoKalliauer/abaqus-centos-7-singularity
```bash
sudo rm -r /usr/local/go
wget https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz #https://golang.org/doc/install
sudo tar -C /usr/local -xzf go1.15.1.linux-amd64.tar.gz
echo 'export PATH=/usr/local/go/bin:$PATH' >> ~/.bashrc && source ~/.bashrc

export VERSION=3.6.0 && # adjust this as necessary
wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz &&     tar -xzf singularity-${VERSION}.tar.gz &&     cd singularity
cd ..
cd singularity/
./mconfig &&     make -C ./builddir &&     sudo make -C ./builddir install
which singularity
singularity --version
cd ..


mkdir -p ~/imgs/sing
rm -f ~/imgs/sing/abaqus-centos-7.img
git clone https://github.com/JoKalliauer/abaqus-centos-7-singularity.git
cd ./abaqus-centos-7-singularity
#For Ubuntu 20.04 you need singularity 3.5.3 or newer
sudo singularity build ~/imgs/sing/abaqus-centos-7.img ./abaqus-centos-7.def 

singularity exec --bind /opt/abaqus ~/imgs/sing/abaqus-centos-7.img vglrun /opt/abaqus/CAE/2019/linux_a64/code/bin/ABQLauncher cae -mesa
```

more details see https://github.com/JoKalliauer/abaqus-centos-7-singularity

**Comment by dtrudg** [comment]
This appears to be a duplicate of an issue reported on the mailing list, related to using a very recent kernel in Fedora 32. It occurs on Linux 5.8, but not 5.7:

https://groups.google.com/a/lbl.gov/g/singularity/c/Nl3n33QLEKk/m/VTO8zMGYCAAJ

That issue has been fixed by a related change in Singularity 3.6.2 - please update, and things should work as expected. If they don't - let us know.

**Comment by JoKalliauer** [comment]
@dctrud : Thanks that fixed the problem, you have an awesome support. (Three issues all of them fixed immediately.)

Why I'm not closing this issue:
I had a similar Problem that Ubuntu 20.04 needed 3.5.3 or newer, see your post: https://github.com/hpcng/singularity/issues/5482#issuecomment-669960217

You write in the imho newest documentation: https://sylabs.io/guides/3.6/user-guide/quick_start.html#quick-installation-steps
```
export VERSION=3.6.0 && # adjust this as necessary \
    wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz && \
    tar -xzf singularity-${VERSION}.tar.gz && \
    cd singularity
```
would it be possible to make something like `export VERSION=3.6.latest` (as a redirect/symlink) or even better `export VERSION=latest`?

I think the second `VERSION=latest` might be difficult to update, since you have different documentations for different versions, but the first option `export VERSION=3.6.latest` should be quite easy?

**Comment by dtrudg** [comment]
Unfortunately it wouldn't be super easy to do it like that (have a `.latest` release), and would probably give a confusing experience on GitHub.

The tarball link in the install docs comes from GitHub's release system, where a tag on the git repository can become a published release of a specific version, and we then generate and attach the release tarball on it.

The expectation for tags on Git repos is that they don't really move around. If we had a `3.6.latest` tag and moved it around we'd likely end up having to delete and re-create the GitHub release entries for the `.latest` and reattach tarballs etc. in a way that is error prone.

It would also break our DOI references in Zenodo - as that expects GitHub release versions to be set in stone, things that are unique and can be archived. Other 3rd parties may also have automation that consider GitHub releases to be a static thing too.

Ultimately the best solution here is to fix the docs deployment. It's still a bit manual for us to update and push the docs up on the web. We will be working toward making the build and deployment of the docs drive by CI, and then we can change the version number in the docs trivially easily on a new release.
