### ISSUE TITLE
Easy install

### ISSUE THREAD

**Issue by JoKalliauer** [apptainer/singularity#5554]
### Version of Singularity:

always the newest version mentioned in https://raw.githubusercontent.com/hpcng/singularity/master/CHANGELOG.md

### Expected behavior

```bash
sudo install.sh
```
with install.sh from https://github.com/JoKalliauer/singularity/commit/0a7341aedd675f471f5ef2cf40badfcfa9348ef6

### Actual behavior
```bash

if [ -f "/etc/debian_version" ]; then
 sudo apt-get update && sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev wget pkg-config git cryptsetup
fi
if [ "$(grep -Ei 'fedora|redhat' /etc/*release)" ]; then
 sudo dnf update && sudo dnf install -y squashfs-tools wget pkg-config git cryptsetup gcc-go golang-bin
fi

rm -r /usr/local/go
wget https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz #https://golang.org/doc/install
sudo tar -C /usr/local -xzf go1.15.1.linux-amd64.tar.gz
echo 'export PATH=/usr/local/go/bin:$PATH' >> ~/.bashrc && source ~/.bashrc

wget https://raw.githubusercontent.com/hpcng/singularity/master/CHANGELOG.md
pid=$(grep "^# v" ./CHANGELOG.md)
export VERSION=${pid:3:5}

wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
tar -xzf singularity-${VERSION}.tar.gz
cd singularity/
./mconfig
make -C ./builddir
sudo make -C ./builddir install
which singularity
singularity --version
cd ..
```

### Steps to reproduce this behavior

Ask someone unfamiliar to singularity to install the singularity, without telling that the documentation is outdated and installs and old version. 
On Fedroa 32 the person will fail see #5552 , because installing an old version, because the newest available documentation is for 3.6.0.
On Ubuntu 20.04 the person will most likely fail see #5482, because Google shows as a first result https://singularity.lbl.gov/install-linux  which installs 2.5.2

### What OS/distro are you running

an average user should be able to install it on Ubuntu and Fedora

### How did you install Singularity
too complicated to explain

**Comment by dtrudg** [comment]
As mentioned on the PR... https://github.com/hpcng/singularity/pull/5555#pullrequestreview-482843832

We are going to work to make sure the user-guides / admin-guides you find at sylabs.io on the web are trivial to build/deploy with *every* release so the install instructions are up to date always.

We make efforts to ensure the `INSTALL.md`in our repo, which is the first reference to install instructions for people hitting the repo `README.md`, is kept up to date. However we could probably improve it with a note r.e. situations where `master` 

R.E:
> because Google shows as a first result https://singularity.lbl.gov/install-linux which installs 2.5.2

Unfortunately we can't do anything about the content of the LBL site. The project began life within LBL, but we no longer have any control over that location. The banner "Documentation is now hosted at https://www.sylabs.io/docs/" was added, and hopefully attracts most people's attention.
