### ISSUE TITLE
why the singularity can not be set locale ?

### ISSUE THREAD

**Issue by honghh2018** [apptainer/singularity#5556]
Hi @developers,
     The singularity container built by centos8 from docker://centos:latest using --sandbox. Nevertheless, the locale error occurred most of time when install perl or R or python on the container.
     And had any work around way to fix it. even though i look for many way to set the locale on internet, it still be not worked.
     Is it a bug on singularity? 
     The install perl showing warning below,
     
![image](https://user-images.githubusercontent.com/41668708/92381170-f04aff00-f13c-11ea-85fc-b576f354f1c3.png)
     The R showing the locale warning,
      
![image](https://user-images.githubusercontent.com/41668708/92381216-022ca200-f13d-11ea-80cf-3d85e6649e35.png)
     And i try to fix this problem, but the localectl no work on singularity. the error showing below.

![image](https://user-images.githubusercontent.com/41668708/92381086-c691d800-f13c-11ea-9a18-6ffddefe21e6.png)
The host locale showing below,
![image](https://user-images.githubusercontent.com/41668708/92384284-656d0300-f142-11ea-8153-6496151c3a75.png)

     Hope help.
     Best,
     hanhuihong

**Comment by dtrudg** [comment]
This is not a Singularity issue - the locale you have set on your system is not available in the centos container image that you are using. From reading around I believe that to ensure small docker images CentOS strip out some locales.

Try to run a `yum reinstall -y glibc-common` in the container, which should restore all locales.

**Comment by qhaas** [comment]
> believe that to ensure small docker images CentOS strip out some locales

Worse still... the CentOS 8 Docker image [defaults to a locale that is not installed](https://github.com/CentOS/sig-cloud-instance-images/issues/154).
