### ISSUE TITLE
Jupyter Notebook In Singularity Container

### ISSUE THREAD

**Issue by o0stsou0o** [apptainer/singularity#5557]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version 
3.2.0-1.el7.centos

```

### Expected behavior

Hoping to get jupyter notebook with gpu from the lab cluster up on my local browser.  

A classmate told me that I am missing a couple of steps and was wondering if anybody here could aid?    
 

### Actual behavior

nothing comes up on my browser.
I'm getting:
channel 2: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused

after I ssh with port forwarding the jupyter notebook port.  

I've been told that after step 2, I am supposed to note the ip/hostname.  Then after step 6, outside srun but inside the host I am supposed to ssh into the recorded hostname and port forward the jupyter notebook port.  Does anybody know if this is correct?  If so, would you know how to do this?  
 

### Steps to reproduce this behavior

Steps are numbered.  
1. tmux  
2. srun -p gpu -N1 --cpus-per-task=6 --gres=gpu:1 --mem=20000 --time=4-0:00:00 --pty bash 
3. I shell into my container singularity shell --writable-tmpfs --nv name.sif  .  

I've been told to use:
4. ![image](https://user-images.githubusercontent.com/23566009/92187229-35162380-ee27-11ea-90d8-7f7f0e86cf30.png)

followed by the usual:
5. jupyter notebook --no-browser --port=8000

It gives me a nice readout that tells me:
[I 13:30:07.293 NotebookApp] Serving notebooks from local directory: /home/stsou
[I 13:30:07.293 NotebookApp] The Jupyter Notebook is running at:
[I 13:30:07.293 NotebookApp] http://localhost:8000/
[I 13:30:07.293 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

Then I ssh in another tab with:
6. ssh -N -L 7800:localhost:7800 joeblog@school.edu
When I log in, it hangs.  

7. I go to my browser and enter: localhost:7800   

### What OS/distro are you running

We are running on a CentOS Linux distribution.  

```
$ cat /etc/os-release

CentOS Linux release 7.6.1810 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.6.1810 (Core)
CentOS Linux release 7.6.1810 (Core)


```

### How did you install Singularity
Unfortunately I'm not sure of how singularity was installed.  I can ask if that is specificity is needed though.  

Please let me know if anybody could provide any input?  It goes without saying that it would be greatly appreciated.

**Comment by robertlugg** [comment]
I'm guessing that this is the problem and solution.
https://stackoverflow.com/q/42848130/2184122
...change your --ip to 0.0.0.0 to allow remote connections.

I also see your port numbers are different.  jupyter is running on 8000, so I think your ssh line should be 8000 and not 7800:
```
ssh -N -L 8000:localhost:8000 joeblog@school.edu
```
Then go to localhost:8000

Actually, start up a browser *on the same machine* as your jupyter server to see if you can access there.

**Comment by dtrudg** [comment]
Closing, as this issue is a usage question that has not had follow up for >90 days.

For issues that are questions r.e. using Singularity, rather than bugs or feature requests, the mailing-list and slack channel are often better venues. Questions to the slack channel and mailing list will be seen by a large number of subscribed users, rather than only those who look inside a particular GitHub issue. Therefore they are encouraged for this type of inquiry.

Slack: See https://hpcng.org/ for invite (bottom of page)
Mailing List / Google Group: https://groups.google.com/a/lbl.gov/forum/#!forum/singularity

**Comment by o0stsou0o** [comment]
Thanks.  I figured it out anyways.
