### ISSUE TITLE
What should I do if I don't want to use the root privileges but need to limit the memory usage of singularity container?

### ISSUE THREAD

**Issue by DechinPhy** [apptainer/singularity#5559]
### Version of Singularity: 3.6.1
![image](https://user-images.githubusercontent.com/42831382/92551215-0e754400-f290-11ea-9d46-ce6c23fe953e.png)

**Comment by dtrudg** [comment]
There is no straightforward way to do this without cgroups, which requires root privilege to establish the limits.

The `ulimit` command allows setting user limits, but the `-m` option for resident memory size does not work on modern Linux.

The `ulimit -v` option will limit virtual memory usage - but as many programs allocate a lot more virtual memory than they use physical RAM, this is not a practical way to control true memory usage.

If you use a job scheduler to run Singularity inside batch jobs you may be able to use its functionality to limit memory usage. That depends on the scheduler in use, and its configuration on your system.

**Comment by DechinPhy** [comment]
@dctrud What about the I/O bps limit? Is this configuration also need cgroups?

**Comment by dtrudg** [comment]
> @dctrud What about the I/O bps limit? Is this configuration also need cgroups?

Yes, cgroups is required. The best you can do in userspace is probably `ionice` which just sets a priority, not limits.
