### ISSUE TITLE
Support layered containers

### ISSUE THREAD

**Issue by robertlugg** [apptainer/singularity#5572]
### Version of Singularity:

```
3.1.0
```

### Expected behavior

I want a better way to generate and support many similar containers.  Already I know I can start with a base container.  This request is to improve Singularity to better match my goals.  They are:

1. I want to have a base container which will contain generic parts of other containers, such as the base OS, system tools, site-specific tools, etc.  This base container will seldom be used by end users, but instead be referenced by other containers.  This part of the request is likely satisfied by the existing system.
2. I want to have many smaller containers which are specific to a certain use, such as providing gvim, kate, jupyter notebook, etc. 
 These containers will have links to other containers, including the base container described.  I want them to each reference one or more base containers.  For instance, I might have separate containers for different versions of gvim or separate containers for gvim vs kate, etc.
3.  perfect dependency tracking.  A firm goal of many is to have a repeatable environment.  There is a risk of version mis-match.  Therefore, each container built should have a global-unique signature.  The singularity recipe will reference the container by global-unique signature.  If Singularity cannot find any base containers, it will not run.

### Use cases
1.  TensorFlow releases new versions every few weeks.  It is often unnecessary to update the entire container.  Instead it should be possible to only update TensorFlow and reference some base container.

2.  I want to make available 3 different text editors.  I want to be able to update any without affecting the others.  I want this process to be quick.  I don't want to consume unnecessary disk space with redundant container materials.  I want to be able to build and deploy without root access assuming that the added files don't require additional access.  I want to be able to have meta packages which, for instance, reference the most recent version of all text editors.  I want a flexible search not dependant on filename similar to PATH or LD_LIBRARY_PATH to find referenced containers.  I want that search to be certain that it finds the correct container (ie by a global ID,etc)

So, the idea is to be able to "reference" versus "import".  I want one container to be able to reference another instead of starting with that base container and then writing out a new container with both the base container and additions included.

### Actual behavior

A container may be built from a base container.  This results in a new container which contains both the base container as well as any additional %post operations defined in recipe file.  Singularity does support overlays but they are insufficient for what I'm attempting.

What actually happened? Why was it incorrect?
Currently, it functions as it should.  This enhancement request is to better support specific use cases.

### What OS/distro are you running

```
CentOS 7
```

### How did you install Singularity

Built from source

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
