### ISSUE TITLE
Container overlay not working with mpi

### ISSUE THREAD

**Issue by KubaVymola** [apptainer/singularity#5577]
Singularity version 3.6.2

### Expected behavior

```
$ mpirun singularity exec -B /apps:/apps -o overlay.img lmod-container hostname
compute-node-1
compute-node-2
etc...
```

Note: /apps is directory with intel mpi installation (for the bind model of mpi execution; would not be needed if there was mpi installed in the container)

### Actual behavior

```
$ mpirun singularity exec -B /apps:/apps -o overlay.img lmod-container hostname
FATAL:   while loading overlay images: failed to open overlay image overlay.img: while locking ext3 partition from /path/to/overlay/overlay.img: can't open /path/to/overlay/overlay.img for writing, currently in use by another process
```

### Steps to reproduce this behavior

For me, this has happened every time when I tried to run the container with mpirun and with some overlay. The container that I am using has lmod installed and expects intel mpi module to be bound into the container at runtime (it is using the bind model for mpi execution as referred in Singularity documentation here: https://sylabs.io/guides/3.4/user-guide/mpi.html#bind-model). 

The one thing that I am not sure about is the accessibility of the intel mpi binary at the time of startup of the container. The corresponding environmental variables for intel binaries and libraries are being set in the container by loading the module for the target binary (some scientific software in this case) just before that target binary is executed. Though, I was able to reproduce the exact same problem with OpenMPI installed into the container from source and using the hybrid model for mpi execution, so I am assuming, that this does not play any significant role (this OpenMPI container be easily executed with mpirun to run the hostname command which then gives correct node names, but it fails to run even with dummy overlay - gives the exact same error output).

Is there something crucial that I am missing? I though, maybe there would be some flag to make the overlay read-only and prevent the locking, but I have not found anything like that. Also, none of the issues here on Github mentions anything similar to my problem.

### What OS/distro are you running

```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
```

### How did you install Singularity

This is running on cluster, but I believe that Singularity there was installed manually from source. I can reproduce this behavior on my local machine, where I am running Ubuntu 20.04 and where I have installed Singularity from source.

I am also able to reproduce this issue on another cluster with CentOS 7 installed.

**Comment by dtrudg** [comment]
This isn't well documented, but overlay can take `:ro` like a bind mount...

```
singularity shell --overlay overlay.img:ro docker://alpine
```

And that should accomplish what you need here.
