### ISSUE TITLE
Inconsistent behavior with different users

### ISSUE THREAD

**Issue by drneavin** [apptainer/singularity#5578]
### Version of Singularity:

Singularity version: 3.0.2-1.el7.centos

### Expected behavior

We have noticed some functions working fine with a singularity bucket for one user but not another user (on the same cluster with the same image). 

One example is that when we try to copy files from within the singularity bucket to the local computer. The command is:
```
singularity exec --bind "/path/to/directory/to/bind,/path/to/second/directory/to/bind:/mnt" /path/to/image.sif cp /path/in/singularity/image/to/filename /path/to/second/directory/to/bind/
```

We expect that the file in the singularity image should be copied to the directory indicated (`/path/to/second/directory/to/bind/`). 

### Actual behavior

When I run this, it does just that - copies the file to the expected directory. When my coworker runs this it does not, it results in an error:

```
cp: cannot create regular file '/path/on/local/to/directory/': No such file or directory
```

So for some reason, it is trying to force the copy to have the name of the directory, not  copying into the directory. However, when `-rf` to recursively copy the files from the singularity directory to the local directory is included as below, it works fine and if we specify the name of the file in the destination, it works fine as well:

With `-rf`
```
singularity exec --bind "/path/to/directory/to/bind,/path/to/second/directory/to/bind:/mnt" /path/to/image.sif cp -rf /path/in/singularity/image/to/filename /path/to/second/directory/to/bind/
```

With file name:
```
singularity exec --bind "/path/to/directory/to/bind,/path/to/second/directory/to/bind:/mnt" /path/to/image.sif cp -rf /path/in/singularity/image/to/filename /path/to/second/directory/to/bind/filename
```

Further, we tested whether somehow the local version of cp was being used but running the same commands with a local file without singularity work fine so it doesn't seem to be an issue with the local version of cp:
```
cp /path/to/filename /path/to/directory/
```
```
cp -rf /path/to/filename /path/to/directory/
```

### Steps to reproduce this behavior

The image being used can be obtained from
```
singularity pull shub://sc-eQTLgen-consortium/WG1-pipeline-QC:wgpipeline
```

### What OS/distro are you running

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

Installed on a cluster - did not do myself as it was done by the cluster administrator.

Would love some feedback as to what might be going on here and I'm happy to provide further details and info, please let me know if anything is unclear.

**Comment by dtrudg** [comment]
Hello, I'm afraid that `Singularity version: 3.0.2-1.el7.centos` is very old now, and does not receive bug fixes etc.

Please could you check whether you see the same behavior under a current version of Singularty (3.6.3 is the latest).

**Comment by drneavin** [comment]
Thanks for the recommendation @dctrud, we have since tested on 3.6.0-1.el7 which is implemented on one node of our cluster and receive the same issue. This issue seems to be true of many bash commands but the image works for both myself and my colleague with non-bash commands (python and R scripts are fine). Any recommendations or additional information we can provide?

**Comment by dtrudg** [comment]
Are you able to provide a complete reproducer we can run on a system (e.g. including setting up the local directories, and binding them)? That would help look into this further.

**Comment by drneavin** [comment]
Hi @dtrudg, we were able to sort this out - seemed it was a combination of multiple different issues. Thanks for your help!
