### ISSUE TITLE
Cannot run post scriptlet when using /bin/sh is a symlink (busybox)

### ISSUE THREAD

**Issue by hcraT** [apptainer/singularity#558]
Hi,
when I try to use a boootstrap post script in an image based on alpine that have `/bin/sh` symlinked to `/bin/busybox`.

The error is this:
```
ERROR: Could not run post scriptlet, /bin/sh not found in container
```

I've digged a bit and pinned down the problem due to [line 203 in postbootstrap.sh](https://github.com/singularityware/singularity/blob/master/libexec/bootstrap/modules-v2/postbootstrap.sh#L203):
```
if [ -x "$SINGULARITY_ROOTFS/bin/sh" ]; then
```

If the line could be changed to:
```
if [ -x "$SINGULARITY_ROOTFS/bin/sh" -o -L "$SINGULARITY_ROOTFS/bin/sh" ]; then
```
this could be fixed.

For the record I was able to correctly bootstrap the image anyway with this script:
```
Bootstrap: docker
From: alpine:3.5

%setup
rm $SINGULARITY_ROOTFS/bin/sh
cat > "$SINGULARITY_ROOTFS/bin/sh" << EOF
#!/bin/busybox sh
exec /bin/busybox sh "\$@"
EOF
chmod 0755 "$SINGULARITY_ROOTFS/bin/sh"

%post
echo "hello world"
```

**Comment by gmkurtzer** [comment]
hi @hcraT,

What version of Singularity are you testing with?

Thanks!

**Comment by hcraT** [comment]
Hi @gmkurtzer,
the version is 2.2.1

**Comment by gmkurtzer** [comment]
Can you test with the development github branch? I think this is fixed, but I would feel better with your confirmation.

Thanks!

**Comment by hcraT** [comment]
Hi @gmkurtzer,
I've tested the development version and it works ok.

Thanks!

**Comment by gmkurtzer** [comment]
Excellent, thanks for letting me know!
