### ISSUE TITLE
singularity in docker not works.

### ISSUE THREAD

**Issue by openbioinfo** [apptainer/singularity#5581]
### Version of Singularity:

What version of Singularity are you using? Run:

```
v3.4.0

```

### Expected behavior

docker run -ti --rm -v $PWD:$PWD -w $PWD singularityware/singularity:v3.4.0-slim  exec alpine.simg echo

What did you expect to see when you do...?

### Actual behavior

What actually happend? Why was it incorrect?

ERROR  : Failed to create container namespaces

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

centos-7

```
$ cat /etc/os-release


```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

using docker.

**Comment by dtrudg** [comment]
This is expected. Running Singularity in docker is similar to running docker nested in docker. Singularity needs to have privileges to create namespaces, perform mounts, etc. which are restricted by default in docker. You must run docker with `--privileged` or allow specific capabilities that match what you are going to do with Singularity.

**Comment by dtrudg** [comment]
I would generally advise that you will have most success with singularity in docker if you build singularity without setuid support, but note that this does affect some functionality: https://sylabs.io/guides/3.6/admin-guide/installation.html#unprivileged-non-setuid-installation
