### ISSUE TITLE
Seccomp settings not worked

### ISSUE THREAD

**Issue by DechinPhy** [apptainer/singularity#5591]
### Version of Singularity:

3.6.3

I use the `json` setting file from [Moby](https://github.com/moby/moby/blob/master/profiles/seccomp/default.json).

But when I run `singularity shell --security seccomp:/home/default.json centos.sif`, I can still run `kill` and `chmod` commands in singularity shell

**Comment by dtrudg** [comment]
@DechinPhy - the default file from the link explicitly *allows* use of the listed syscalls, including `kill` and `chmod`.

```
	"syscalls": [
		{
			"names": [
...
				"chmod",
...
				"kill",
			],
			"action": "SCMP_ACT_ALLOW",
			"args": [],
			"comment": "",
			"includes": {},
```

... so it is expected you can still run `kill` or `chmod` using this policy file. It contains the defaults for Docker/moby - where you can kill and chmod in a container by default.

To restrict calls using this policy file as a starting point you would need to remove them from the allowed list. Note also that you may need to remove multiple call names, beyond what migh seem necessary. A chmod operation may be performed via `chmod` `fchmod` `fchmodat` calls... so you need to disallow all of those, not just `chmod`. A lot of syscalls have variants working on e.g. file pointers, or 'at' a location etc.

**Behaviour with default.json**

```
dave@ythel~/seccomp> singularity shell --security seccomp:/home/dave/seccomp/default.json docker://centos
INFO:    Using cached SIF image
Singularity> chmod 444 bob
# It worked
```

**My changes to default.json**

```diff
dave@ythel~/seccomp> diff default.json modified.json
65d64
< 				"chmod",
103,104d101
< 				"fchmod",
< 				"fchmodat",
815d811
< 
```

**Behaviour with modified.json**

```
dave@ythel~/seccomp> singularity shell --security seccomp:/home/dave/seccomp/modified.json docker://centos
INFO:    Using cached SIF image
Singularity> chmod 444 bob 
chmod: changing permissions of 'bob': Operation not permitted
# It was refused
```

... the seccomp enforcement is working as I would expect.

**Also, please note** that if you do discover something that is a genuine security issue, or you are unsure of, it is better reported privately according to our security policy, which is at: https://sylabs.io/security-policy and linked / mentioned on each release note. Thanks!

**Comment by DechinPhy** [comment]
@dctrud Thank you for that. It is confused when I using the `_KILL` or `_ERRNO` it does not works. But the `_ALLOW` command seems works.
