### ISSUE TITLE
Different versions of same container when using different users

### ISSUE THREAD

**Issue by s1st** [apptainer/singularity#5592]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

3.5.2+ds1
```

### Expected behavior

What did you expect to see when you do...?

I tried to run a container from the nvidia-ngc respository which is pytorch 20.03.
As a user with in groups `docker, sudo` the following command
```
singularity shell --nv docker://nvcr.io/nvidia/pytorch:20.03-py3
python
from torch.utils.collect_env import main; main()
```
gives the following output:
```
Collecting environment information...
PyTorch version: 1.5.0a0+8f84ded
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 418.126.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.3.2
[pip] numpy==1.18.1
[pip] pytorch-transformers==1.1.0
[pip] pytorch3d==0.2.5
[pip] torch==1.5.0a0+8f84ded
[pip] torchtext==0.4.0
[pip] torchvision==0.6.0a0
[conda] Could not collect
```
### Actual behavior

What actually happend? Why was it incorrect?
When I run the same command as a user without these priviledges, I get the following output:
```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 418.126.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.3.2
[pip] numpy==1.17.4
[pip] pytorch-transformers==1.1.0
[pip] torch==1.4.0
[pip] torchtext==0.4.0
[pip] torchvision==0.6.0a0
```
With the difference in CUDA 10.2 and 10.1, pytorch 1.5 and 1.4 and numpy 1.18 and 1.17.
How can that happen based on the user?
What can I do to let the unprivileged user have the same container as the privileged user?

I also cleaned caches and retried, same behavior.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Two users, one with and one without `sudo, docker` rights.
Run the command
```
singularity shell --nv docker://nvcr.io/nvidia/pytorch:20.03-py3
python
from torch.utils.collect_env import main; main()
```
with each of the users. Compare the outcome.

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
Downloaded the .deb here:
http://ftp.de.debian.org/debian/pool/main/s/singularity-container/singularity-container_3.5.2+ds1-1_amd64.deb

and installed it via:
`sudo dpkg -i singularity-container_3.5.2+ds1-1_amd64.deb`

**Comment by dtrudg** [comment]
You are probably leaking python modules from outside of the container into the container. This happens as Singularity mounts $HOME by default. If a user has python 3.6 modules installed in their $HOME outside of the container, then they will be seen by python in the container.

Use the `--contain` flag to avoid this and get reproducible behavior.

**Comment by s1st** [comment]
Thank you very much for that insight and the quick response. That solved the issue!
