### ISSUE TITLE
Building sandboxes fails on NTFS external drive

### ISSUE THREAD

**Issue by drewpolasky** [apptainer/singularity#5594]
### Version of Singularity:
3.6.3

### Expected behavior
building from a recipe works either with or without --sandbox flag

### Actual behavior
When building with the --sandbox flag with the recipe and build location on an external hard drive, it fails with the message:
```
Reading package lists... Done
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/binary-amd64/Packages  Could not change permissions for temporary file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_main_binary-amd64_Packages.lz4.lPnK6j - fchmod (1: Operation not permitted)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/main/binary-amd64/Packages  Could not change permissions for temporary file /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages.lz4.8wF52a - fchmod (1: Operation not permitted)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/Packages  Could not change permissions for temporary file /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages.lz4.6mtFUe - fchmod (1: Operation not permitted)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/main/binary-amd64/Packages  Could not change permissions for temporary file /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-backports_main_binary-amd64_Packages.lz4.EcN6DH - fchmod (1: Operation not permitted)
E: Some index files failed to download. They have been ignored, or old ones used instead.
FATAL:   While performing build: while running engine: exit status 100
```

When building on my external hard drive, which is NTFS. Running the same command on the built in hard drive runs fine. Running the command without --sandbox works fine as well. 

### Steps to reproduce this behavior
`sudo singularity build --sandbox example.simg example.rec` on an NTFS external hard drive. I haven't tried it on any other external hard drive formats. 

Using this example recipe: 
```
BootStrap: docker
From: ubuntu:16.04

%runscript

%files

%post
    apt-get -y update
    apt-get install -y sudo vim build-essential git cmake wget zip unzip python-dev python-pip
```

### What OS/distro are you running
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity
source

**Comment by dtrudg** [comment]
This is expected. When building a sandbox the rootfs is constructed directly at the location specified. When this is an NTFS drive that location does not support some file permissions / constructs that a Linux root filesystem requires.

When you build without `--sandbox` then the rootfs is constructed at your `TMPDIR` before it is packed into a SIF file at the final location. Your `TMPDIR` is probably a local Linux file system so you do not hit these issues.

Expect problems when you are working with a drive formatted for a Windows or Mac, which cannot support all native file system functionality expected by Linux applications, especially those that operate at a low level such as Singularity.
