### ISSUE TITLE
afs home does not exist in container

### ISSUE THREAD

**Issue by traylenator** [apptainer/singularity#5612]
### Version of Singularity:

What version of Singularity are you using? Run: singularity-3.6.3-1.el7.x86_64  (observed on 3.6.2 also)

```
/usr/bin/singularity run  docker://alpine:latest hostname
```
### Expected behavior

Run hostname inside the image.

### Actual behavior
```
FATAL:   container creation failed: mount /afs/cern.ch/user/s/someone->/var/singularity/mnt/session/afs/cern.ch/user/s/someone error: while mounting /afs/cern.ch/user/s/straylen: destination /var/singularity/mnt/session/afs/cern.ch/user/s/someone doesn't exist in container
```

Note this is only consistent per node. Out of 100 nodes I have this currently only on   4 CentOS 7 nodes.
I believe fresh nodes are allways good and then at some point the break.
(Later today I will reboot of those four to see if that changes to the situation, may learn something)

### Steps to reproduce this behavior
Reproducing is going to be hard for sure - that is very much accepted. 
Install a lot of AFS enabled home directory machines, some appear to go bad after a while.

However what should aid reproduction is all CERN credentials have public access to these machines.
On 14th October the broken machines were lxplus706.cern.ch, lxplus717.cern.ch,
lxplus722.cern.ch, lxplus753.cern.ch.

I have looked for patterns with these machines:
  * kernel versions
  * free space
  * free memory
I have not found any property yet that is not well represented on other working machines.

### What OS/distro are you running

CentoOS 7 up to date.

### How did you install Singularity
EPEL 7 release.

#### More Comments
Mounting home  outside of /afs is fine. e.g.

```
/usr/bin/singularity run -H /tmp/someone docker://alpine:latest hostname
```

During the failure mode nothing is produced in `dmesg`, `journald` or `audit.log`.

[Debug Log](https://github.com/hpcng/singularity/files/5376689/88dd4104.txt)

**Comment by traylenator** [comment]
This read similar to https://github.com/hpcng/singularity/issues/2453

**Comment by traylenator** [comment]
One extra piece of information , rebooting a broken node does fix a node.

**Comment by traylenator** [comment]
This is surprising and may give a clue.

While

```
/usr/bin/singularity shell  docker://alpine:latest
```
fails the following

```
/usr/bin/singularity shell --no-home --bind /afs:/afs docker://alpine:latest
```

is okay and I can browse my AFS home directory once there. 
Is there some additional checks on an explicitly labeled home directory?

The more precise:

```
/usr/bin/singularity shell --no-home --bind /afs/cern.ch/user/s/someone:/afs/cern.ch/user/s/someone docker://alpine:latest
```

fails however, the shortest path that is successful is

```
/usr/bin/singularity shell --no-home --bind /afs/cern.ch:/afs/cern.ch docker://alpine:latest
```

**Comment by traylenator** [comment]
Getting somewhere.

So on the failing even a simple bind mount fails.

```
mkdir /tmp/mnt
mount -o bind /afs/cern.ch/user/s/someone /tmp/mnt
mount: mount(2) failed: No such file or directory
```
and strace shows

```
mount("/afs/cern.ch/user/s/someone", "/tmp/mnt", 0x55e3e8e41f40, MS_MGC_VAL|MS_BIND, NULL) = -1 ENOENT (No such file or directory)
```

So now this is certainly nothing to do with singularity.

Looking with afs experts will update this when we have something but for sure if you want to close anyway fine by me.

**Comment by dtrudg** [comment]
@traylenator - thanks for digging through that and isolating it down to an afs issue. Happy to leave this open for now as any further info may be useful for other afs users.
