### ISSUE TITLE
RFE: ECL configuration commands

### ISSUE THREAD

**Issue by cclerget** [apptainer/singularity#5613]
Since 3.6.0 release with the introduction of security fix related to signature check, ECL now requires that all users manually import signer key in their local keyring making ECL experience less convenient for both users and administrators.
Since ECL has nothing to do with user keyrings and shouldn't use it for security reasons, it would make sense to provide a mechanism allowing administrators to manage ECL keyring and at the same time ECL configuration by introducing a new set of commands in `singularity config`:

* To enable/disable ECL

```
singularity config ecl enable
singularity config ecl disable
singularity config ecl status
```

* To add/update/list/remove ECL execution group

```
singularity config ecl add --dir /path --mode [whilelist|whitestrict|blacklist] --keys [keylist] <group_name>
singularity config ecl update [--dir /path] [--mode <mode>] --add-keys [keylist] --remove-keys [keylist] <group_name>
singularity config ecl list
singularity config ecl remove <group_name>
```

* To manage ECL keyring

```
singularity config ecl import-key <public-key-path>
singularity config ecl pull-key [--url <url>] <fingerprint>
singularity config ecl list-key
singularity config ecl remove-key <fingerprint>
```

**Comment by dtrudg** [comment]
Hi @cclerget - couple of initial thoughts on this.

1) I don't think there needs to be an ecl specific keyring. It could be instead a `global` keyring managed with the existing `key` commands for consistency. Sysadmins could import keys into this to allow a `verify` to work for all users in the absence of any internet connectivity etc.

2) I'm not sure that providing a `config ecl` interface to add/edit rules is necessary. Given the flexibility of the ECL rules it's probably easier to understand in the TOML format rather than a CLI with a large number of flags.

> Since ECL has nothing to do with user keyrings and shouldn't use it for security reasons

This *shouldn't* really be the case for security reasons - it's more a convenience issue to have a global keyring? If we are restricting to a full specific key fingerprint (not just anything in a user keyring), and the key algorithms are sound, then it doesn't matter where the public key was obtained from.

**Comment by tri-adam** [comment]
Thanks @cclerget, I agree it would be a good quality of life change to have the ability for an administrator expose one or more keys for use cases such as ECL.

> 1. I don't think there needs to be an ecl specific keyring. It could be instead a `global` keyring managed with the existing `key` commands for consistency. Sysadmins could import keys into this to allow a `verify` to work for all users in the absence of any internet connectivity etc.

Totally agree with this. It also reduces the number of commands that deal with keys, which makes it easier to understand as a user.

To achieve the goal here, perhaps an administrator could do something like:

```
sudo singularity key pull --global 8883491F4268F173C6E5DC49EDECE4F3F38D871E
sudo singularity key import --global pub.asc
```

And then users/administrators could inspect:

```
singularity key list --global
```

> > Since ECL has nothing to do with user keyrings and shouldn't use it for security reasons
> 
> This _shouldn't_ really be the case for security reasons - it's more a convenience issue to have a global keyring? If we are restricting to a full specific key fingerprint (not just anything in a user keyring), and the key algorithms are sound, then it doesn't matter where the public key was obtained from.

Agreed, a cryptographically sound key with the correct fingerprint (and perhaps endorsed by others you trust) is the basis of PGP security. The source of the key itself is not relevant from a security perspective. This is a quality of life improvement, not a security improvement.

**Comment by cclerget** [comment]
Thanks for your feedbacks @dctrud @tri-adam !

We can mix both by just removing key commands from `ecl` and as you suggested delegate that to `key` with `--global`.
I still think `ecl` command could be useful :
- to give some visibility for ECL feature
- to ensure consistency between ECL configuration and global keyring (eg: when adding/updating a key fingerprint for ECL the command would check if the key is present and fail if not, forcing admin to import the key in the global keyring with guidance)
- to ease scripting (add both keys and ecl group with singularity command)

We would also need to add the "global" keyring as part of `verify`, right now we have `[LOCAL]`, `[REMOTE]` and we would just add `[GLOBAL]`.

Regarding "security reasons" statement, it's just based on untrusted content parsed from sensible code, so "security practices" would be more appropriate.
