### ISSUE TITLE
singularity version issue with the running the container images

### ISSUE THREAD

**Issue by nilover** [apptainer/singularity#5629]
​Hi,

I am totally new in the singularity.
I have moved my container folder from one server to another server.
I have two different versions of singularity in those servers.

S1: The server where I built the container with singularity, singularity version: 3.5.3-1.1.el7
S2: The server where I copied the same container folder, but this server already has the newest singularity, singularity version: 3.6.3-1.el7

When I am running the QuNex container image in S1, I immediately could see the QuNex.

singularity run qunex_suite-0_50_02.sif 
--> unsetting all environment variables: PATH MATLABPATH PYTHONPATH QUNEXVer TOOLS QUNEXREPO QUNEXPATH TemplateFolder FSL_FIXDIR FREESURFERDIR FREESURFER_HOME FREESURFER_SCHEDULER FreeSurferSchedulerDIR WORKBENCHDIR DCMNIIDIR DICMNIIDIR MATLABDIR MATLABBINDIR OCTAVEDIR OCTAVEPKGDIR OCTAVEBINDIR RDIR HCPWBDIR AFNIDIR PYLIBDIR FSLDIR FSLGPUDIR PALMDIR QUNEXMCOMMAND HCPPIPEDIR CARET7DIR GRADUNWARPDIR HCPPIPEDIR_Templates HCPPIPEDIR_Bin HCPPIPEDIR_Config HCPPIPEDIR_PreFS HCPPIPEDIR_FS HCPPIPEDIR_PostFS HCPPIPEDIR_fMRISurf HCPPIPEDIR_fMRIVol HCPPIPEDIR_tfMRI HCPPIPEDIR_dMRI HCPPIPEDIR_dMRITract HCPPIPEDIR_Global HCPPIPEDIR_tfMRIAnalysis MSMBin HCPPIPEDIR_dMRITracFull HCPPIPEDIR_dMRILegacy AutoPtxFolder FSLGPUBinary EDDYCUDADIR USEOCTAVE QUNEXENV CONDADIR MSMBINDIR MSMCONFIGDIR R_LIBS FSL_FIX_CIFTIRW

 Loading Quantitative Neuroimaging Environment & ToolboX (Qu|Nex) Version: v0.50.02 
 
 Logged in as User: XXX                                                    
 Node info: XXX                                                  
 OS: RedHat Linux #1 SMP Tue Mar 17 23:49:17 UTC 2020                                                 
 
 
        ██████\                  ║      ██\   ██\                     
       ██  __██\                 ║      ███\  ██ |                    
       ██ /  ██ |██\   ██\       ║      ████\ ██ | ██████\ ██\   ██\  
       ██ |  ██ |██ |  ██ |      ║      ██ ██\██ |██  __██\\██\ ██  | 
       ██ |  ██ |██ |  ██ |      ║      ██ \████ |████████ |\████  /  
       ██ ██\██ |██ |  ██ |      ║      ██ |\███ |██   ____|██  ██<   
       \██████ / \██████  |      ║      ██ | \██ |\███████\██  /\██\  
        \___███\  \______/       ║      \__|  \__| \_______\__/  \__| 
            \___|                ║                                    
 
                       DEVELOPED & MAINTAINED BY:  
 
                            Anticevic Lab                                     
                       MBLab led by Grega Repovs                              
 
                      COPYRIGHT & LICENSE NOTICE:                             
 

But when I was running the same command on the S2 cluster, it immediately opened the command prompt.

singularity run qunex_suite-0_50_02.sif 
-------- freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c --------
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /statgen/riya/software/freesurfer
FSFAST_HOME       /statgen/riya/software/freesurfer/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /statgen/riya/software/freesurfer/subjects
MNI_DIR           /statgen/riya/software/freesurfer/mni
**Singularity>**

Do you think installing the same older version of singularity will solve the above issue? 
How can I fix the problem in the S2 server without reinstalling the older version of singularity?

Any direction regarding this will be helpful for me. I am really stuck.

Thank you.

**Comment by dtrudg** [comment]
Environment handling changed slightly in 3.6.0 but we have not seen this type of issue before.

Are you able to share the container? It is difficult to see what is happening without looking at the container in these cases.

**Comment by ztamayo** [comment]
If you need QuNex specific help, feel free to reach out to me at zailyn.tamayo@yale.edu. We have a site qunex.yale.edu and we also have a forum where people can post issues -- forum.qunex.yale.edu. Thanks.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
