### ISSUE TITLE
'enable fusemount = no' configuration option breaks all exec/run/shell

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#5631]
### Version of Singularity:

3.6.4-1.el7 (also at least 3.6.3, and probably whole 3.6.x series)

### Expected behavior

When setting 'enable fusemount = no' in /etc/singularity/singularity.conf, I expect it to only complain when using the --fusemount option.

### Actual behavior

Executing any container/command without --fusemount complains with an error
```
FATAL:   fusemount disabled by configuration 'enable fusemount = no'
```

### Steps to reproduce this behavior

Edit singularity.conf to set 'enable fusemount = no' and run
```
singularity run library://alpine
```

### What OS/distro are you running

CentOS 7.8

### How did you install Singularity

epel

@cclerget @dctrud

**Comment by dtrudg** [comment]
@DrDaveD - before I start to look at this.... do you have any plugins installed? The function raising this is annoatated...

```
// openDevFuse is a helper function that opens /dev/fuse once for each
// plugin that wants to mount a FUSE filesystem.
func openDevFuse(e *EngineOperations, starterConfig *starter.Config) (bool, error) {
```

**Comment by dtrudg** [comment]
Never mind... I see the fix for this. Sorry for the noise.
