### ISSUE TITLE
Singularity build with definition files fails under proxy, although singularity pull successes.

### ISSUE THREAD

**Issue by suzuki-shm** [apptainer/singularity#5636]
### Overview
When I tried `singularity build env.sif env.def` commands, it failed with following error. It suggested that network connection has been blocked by my proxy environment.

```
$ sudo singularity build env.sif env.def
INFO:    Starting build...
INFO:    Running pre scriptlet
+ export HTTP_PROXY=PROXY_URL
+ export HTTPS_PROXY=PROXY_URL
FATAL:   While performing build: conveyor failed to get: error pinging docker registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp SOME_IP_ADRESS:443: i/o timeout
```

Here is the definition of `env.def`
```
Bootstrap: docker
From:ubuntu:latest

%pre
    export HTTP_PROXY="PROXY_URL"
    export HTTPS_PROXY="PROXY_URL"

%setup
    export HTTP_PROXY="PROXY_URL"
    export HTTPS_PROXY="PROXY_URL"

%environment
    export HTTP_PROXY="PROXY_URL"
    export HTTPS_PROXY="PROXY_URL"
    export PATH=/hoge/hoge:$PATH

%post
    export HTTP_PROXY="PROXY_URL"
    export HTTPS_PROXY="PROXY_URL"
    apt update
    apt install vim
```

However, when I run `singularity pull docker://ubuntu:latest`, it succeeded.

```
$ singularity pull docker://ubuntu:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob d72e567cc804 done
Copying blob 0f3630e5ff08 done
Copying blob b6a83d81d1f4 done
Copying config bbea2a0436 done
Writing manifest to image destination
Storing signatures
2020/10/20 17:24:18  info unpack layer: sha256:d72e567cc804d0b637182ba23f8b9ffe101e753a39bf52cd4db6b89eb089f13b
2020/10/20 17:24:19  info unpack layer: sha256:0f3630e5ff08d73b6ec0e22736a5c8d2d666e7b568c16f6a4ffadf8c21b9b1ad
2020/10/20 17:24:19  info unpack layer: sha256:b6a83d81d1f4f942d37e1f17195d9c519969ed3040fc3e444740b884e44dec33
INFO:    Creating SIF file...
```

In the both running time, I set the proxy URL in my `.bash_profile`

```
export HTTP_PROXY="PROXY_URL"
export HTTPS_PROXY="PROXY_URL"
```

### Version of Singularity:
```
$ singularity version
3.6.4
```

### Expected behavior

Successful container builds without errors (especially the successful download of images from DockerHub)

### Actual behavior

Fail to access to DockerHub. This may be due to the proxy setting inheritance failure.

```
FATAL:   While performing build: conveyor failed to get: error pinging docker registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp SOME_IP_ADRESS:443: i/o timeout
```

### Steps to reproduce this behavior

Please try to run the above command.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Singularity

I installed Singularity from tar.gz compressed release.

**Comment by dtrudg** [comment]
When you have environment variables in a shell session they will not automatically be available to processes running under `sudo`, as `sudo` resets the environment. Although you have set the proxy in your definition file sections these are not used for the initial pull of the base docker container. The def file sections run after this has been retrieved, or in the case of `%pre` run in a separate shell session that does not impact the docker pull.

Try using `sudo -E singularity build ...` if your sudo configuration allows environment to be passed through via `-E`

Otherwise you can set an env var inside sudo, but before the singularity command, i.e. 
```
sudo HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTPS_PROXY} singularity build ...
```

**Comment by suzuki-shm** [comment]
@dctrud 

I'm appreciated your answer. Both methods have resolved my problem.
After studying your answer, I noticed that the answer is in [the official documentation](https://sylabs.io/guides/3.6/user-guide/build_env.html). Despite my lack of research, thank you for your kind response!
