### ISSUE TITLE
Not Able to build or run singularity images after installation in Virtualbox ubuntu

### ISSUE THREAD

**Issue by akash2826** [apptainer/singularity#5640]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ 3.0.3

```

### Expected behavior

build container 

### Actual behavior
FATAL:   container creation failed: mount error: can't mount image /proc/self/fd/10: failed to find loop device: could not attach image file too loop device: permission denied

What actually happend? Why was it incorrect?
No Idea

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
installation from singularity website && below command
singularity shell -u -C library://sylabsed/examples/lolcow

### What OS/distro are you running
ubuntu on virtualbox 

```
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
source

**Comment by dtrudg** [comment]
Hello,

Singularity 3.0.3 is very old and is not longer supported. Please try a current 3.6.4 version. If you experience the same issue please provide information about how the Vagrant box was created, how singularity was installed etc.

Note that pre-created vagrant boxes with up-to-date Singularity are available here: https://app.vagrantup.com/sylabs

**Comment by dtrudg** [comment]
No further information with current singularity provided. Closing. Please feel free to re-open or create a new issue if this replicates on current Singularity.
