### ISSUE TITLE
e2e-test : INSTANCE : One instance is found and becomes FAIL.

### ISSUE THREAD

**Issue by TomohiroAkashi** [apptainer/singularity#5642]
### Version of Singularity:

What version of Singularity are you using? Run:

```
# singularity --version
singularity version 3.6.3+93-g97131ec28
```

### Expected behavior

What did you expect to see when you do...?
When booting an instance of the singularity, even if you use the --boot option, the boot succeeds.

### Actual behavior

What actually happend? Why was it incorrect?
One instance is found and becomes FAIL.
```
--- FAIL: TestE2E/PAR/INSTANCE/issue_5033 (56.11s)
                singularitycmd.go:664: Running command "/usr/local/bin/singularity instance start --boot /tmp/stest.616427764/test.sif b4a99866-0367-4b79-8e65-dadf9c69bb56"
                singularitycmd.go:664: Running command "/usr/local/bin/singularity exec instance://b4a99866-0367-4b79-8e65-dadf9c69bb56 /bin/true"
                singularitycmd.go:664: Running command "/usr/local/bin/singularity instance stop b4a99866-0367-4b79-8e65-dadf9c69bb56"
                singularitycmd.go:664: Running command "/usr/local/bin/singularity instance list --json b4a99866-0367-4b79-8e65-dadf9c69bb56"
                instance_utils.go:99: 1 instance "b4a99866-0367-4b79-8e65-dadf9c69bb56" found, expected 0
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

1.Install the singukarity
$ cd $(go env GOPATH)/src/github.com/sylabs
$ git clone https://github.com/sylabs/singularity.git
$ cd singularity
$ git checkout v3.6.3
$ ./mconfig
$ cd builddir
$ make

2.Modifiy the /e2e/e2e.go file.
```
func RunE2ETests(t *testing.T) {
        os.Setenv("http_proxy", "http://xxx:xxx@xxx:8080")
        os.Setenv("https_proxy", "http://xxx:xxx@xxx:8080")
        t.Log("Running E2E tests for Singularity")
        Run(t)
```

3. Start the e2e-test
$ cd singularity
$ SINGULARITY_E2E=1 make -C builddir e2e-test

### What OS/distro are you running

```
#  cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"```


### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
Refer to the above(Steps to reproduce this behavior).

**Comment by dtrudg** [comment]
The end-to-end tests are not designed to support a proxy at this time. If you wish to see proxy support please open a feature request issue for this. We would also gladly consider a PR that adds proxy support.

Because you have modified the e2e code to set proxy environment in a way that is not supported we don't consider this as a bug at this point.
