### ISSUE TITLE
e2e-test : issue_5172 : Set the proxy, but "connection refused" is displayed.

### ISSUE THREAD

**Issue by TomohiroAkashi** [apptainer/singularity#5643]
### Version of Singularity:

What version of Singularity are you using? Run:

```
# singularity --version
singularity version 3.6.3+93-g97131ec28
```

### Expected behavior

What did you expect to see when you do...?

I execute the "issue_5172" in e2e-test and I thought it would pass.
I can communicate with the external network through GW,
but I get the following error. It may be I selected a bad way to build the environment,
but I don't know where to check, so I will post it.

### Actual behavior

What actually happend? Why was it incorrect?
Actually follow error happend.
```
--- FAIL: TestE2E/PAR/BUILD/issue_5172 (105.09s)
singularitycmd.go:664: Running command "/usr/local/bin/singularity build --sandbox /tmp/stest.846983857/issue-5172 docker://localhost:5000/my-busybox"
singularitycmd.go:664:
"/usr/local/bin/singularity build --sandbox /tmp/stest.846983857/issue-5172 docker://localhost:5000/my-busybox" output:
INFO: Starting build...
FATAL: While performing build: conveyor failed to get: error pinging docker registry localhost:5000: Get http://localhost:5000/v2/: dial tcp [::1]:5000: connect: connection refused
            singularitycmd.go:664: got 255 as exit code and was expecting 0: exit status 255
                waiting for command "/usr/local/bin/singularity build --sandbox /tmp/stest.846983857/issue-5172 docker://localhost:5000/my-busybox"
                github.com/sylabs/singularity/e2e/internal/e2e.TestEnv.RunSingularity.func1
                	github.com/sylabs/singularity@/e2e/internal/e2e/singularitycmd.go:639
                github.com/sylabs/singularity/e2e/internal/e2e.TestEnv.RunSingularity.func2
                	github.com/sylabs/singularity@/e2e/internal/e2e/singularitycmd.go:664
                runtime.goexit
                	runtime/asm_arm64.s:1128
            singularitycmd.go:664: Running command "/usr/local/bin/singularity pull /tmp/stest.846983857/issue-5172 docker://localhost:5000/my-busybox"
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

1. Install the singukarity
$ cd $(go env GOPATH)/src/github.com/sylabs
$ git clone https://github.com/sylabs/singularity.git
$ cd singularity
$ git checkout v3.6.3
$ ./mconfig
$ cd builddir
$ make
$ make install

2. Modifiy the /e2e/e2e.go file.
```
vim e2e/e2e.go
func RunE2ETests(t *testing.T) {
  os.Setenv("http_proxy", "http://xxx:xxx@xxx:8080")
  os.Setenv("https_proxy", "http://xxx:xxx@xxx:8080")
  t.Log("Running E2E tests for Singularity")
  Run(t)
```

3. Start the e2e-test
$ cd singularity
$ SINGULARITY_E2E=1 make -C builddir e2e-test

### What OS/distro are you running

```
#  cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
Refer to the above(Steps to reproduce this behavior).

**Comment by dtrudg** [comment]
The end-to-end tests are not designed to support a proxy at this time. If you wish to see proxy support please open a feature request issue for this. We would also gladly consider a PR that adds proxy support.

Because you have modified the e2e code to set proxy environment in a way that is not supported we don't consider this as a bug at this point.
