### ISSUE TITLE
e2e-tests will need to be modified so that the proxy environment is set.

### ISSUE THREAD

**Issue by TomokiUemoto** [apptainer/singularity#5651]
### Version of Singularity:

```
$ singularity version
singularity version 3.6.3
```

### Expected behavior

E2e-test passes even in Proxy environment.

### Actual behavior

This issue is about support for e2e testing in a proxy environment.

When the system-wide HTTP_PROXY environment variable was set outside the test code, about 95 tests failed.
<pre>
  $ export HTTP_PROXY=http://xxxx:xxxx@rep.proxy.nic.com:xxxx
  $ export HTTPS_PROXY=http://xxxx:xxxx@rep.proxy.nic.com:xxxx
  $ SINGULARITY_E2E=1 make -C builddir e2e-test > singularity_e2e-test.external.log
</pre>
  Please refer to the attached singularity_e2e-test.external.log for details.

When the HTTP_PROXY environment variable was set inside the test code, fail decreased 90.
<pre>  
$ git diff
  diff --git a/e2e/e2e.go b/e2e/e2e.go
  index ca5072cd2..413134808 100644
  --- a/e2e/e2e.go
  +++ b/e2e/e2e.go
  @@ -7,10 +7,14 @@ package e2e

   import (
          "testing"
  +       "os"
   )

   // RunE2ETests is the main func to trigger the test suite.
   func RunE2ETests(t *testing.T) {
  +       // Set the system-wide proxy IP to the http(s)_proxy environment variable.
  +       os.Setenv("http_proxy", "http://id:pass@rep.proxy.nic.com:port")
  +       os.Setenv("https_proxy", "http://id:pass@rep.proxy.nic.com:port")
          t.Log("Running E2E tests for Singularity")
          Run(t)
   }
  $
</pre>
<pre>
  $ SINGULARITY_E2E=1 make -C builddir e2e-test > singularity_e2e-test.internal.log
</pre>
  Please refer to the attached singularity_e2e-test.internal.log for details.

The following 5 cases are still FAIL, but I don't know why.
<pre>
  TestE2E/PAR/ENV/environment_manipulation
  TestE2E/PAR/ACTIONS/shell/ShellHostname
  TestE2E/PAR/DOCKER/registry
  TestE2E/PAR/INSTANCE/issue_5033
  TestE2E/PAR/BUILD/issue_5172
</pre>
[singularity_e2e-test.external.log](https://github.com/hpcng/singularity/files/5427492/singularity_e2e-test.external.log)
[singularity_e2e-test.internal.log](https://github.com/hpcng/singularity/files/5427493/singularity_e2e-test.internal.log)

P.S.
The test to access oras registry fails because we do not have an oracle account.

### Steps to reproduce this behavior

Run e2e-test on Proxy required system.
$ git clone https://github.com/sylabs/singularity.git
$ cd singularity
$ git checkout v3.6.3
$ ./mconfig
$ cd builddir
$ make
$ cd ../
$ export HTTP_PROXY=http://xxxx:xxxx@rep.proxy.nic.com:xxxx
$ export HTTPS_PROXY=http://xxxx:xxxx@rep.proxy.nic.com:xxxx
$ SINGULARITY_E2E=1 make -C builddir e2e-test
 

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"

```

### How did you install Singularity
<pre>
$ git clone https://github.com/sylabs/singularity.git
$ cd singularity
$ git checkout v3.6.3
$ ./mconfig
$ cd builddir
$ make
# make install
</pre>

**Comment by dtrudg** [comment]
@TomokiUemoto - #5662 is believed to fix this with a proxy setup for testing. If it doesn't work in your proxy environment please let us know what fails.
