### ISSUE TITLE
How to build a singularity image that only allowed to run a specified command?

### ISSUE THREAD

**Issue by Keenan-Tang** [apptainer/singularity#5663]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity 3.6.4

```

### Expected behavior

What did you expect to see when you do...?
How to build a singularity image that only allowed to run a specified command, and other commands are not allowed to be executed. I think this is a good way to protect my own source code.

**Comment by dtrudg** [comment]
This is not really possible with Singularity or containers in general. Although we could add a simple restriction that would stop certain actions through the Singularity command line it would be very easy to bypass. To run a container a user must be able to access the files in the container. It is straightforward to export/copy things out to access them.

If you need to protect source code in a container, it needs to be done in the same way as if the code is on a host system, e.g. with compilation, obfuscation tooling, etc.

**Comment by Keenan-Tang** [comment]
Thanks for your reply.
