### ISSUE TITLE
LD_LIBRARY_PATH with libs overlapping unsquashfs system libs causes failure

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5666]
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.6.4

```

### Actual behavior

Singularity has a number of checks / workarounds so that things are done on filesystems that support overlay etc. when needed or sensible errors/warnings are produced. It appears that `3.6.4` which wraps `unsquashfs` for security reasons may have impacted this.

See: https://groups.google.com/a/lbl.gov/g/singularity/c/D0TA3H5jNw0

```
Hi,

In 3.6.4 the following now fails, at least on my Centos7.6 box:

  $ singularity pull docker://python:latest
  $ singularity build --sandbox sandbox python_latest.sif

with the error message:

  ERROR:   unpackSIF failed: root filesystem extraction failed: extract command failed: WARNING: passwd file doesn't exist in container, not updating
  ...

Is there a workaround?
```

```
I get the same issue when the build is running on a network file system (GPFS). Setting the environment SINGULARITY_TMPDIR to point to a local disk works for me.
```

**Comment by nolta** [comment]
Here's the full output with the `-d` flag:

```
$ singularity pull docker://python:latest
INFO:    Using cached SIF image
$ singularity -d build --sandbox sandbox python_latest.sif
DEBUG   [U=3000178,P=128410]persistentPreRun()            Singularity version: 3.6.4-1.el7
DEBUG   [U=3000178,P=128410]persistentPreRun()            Parsing configuration file /etc/singularity/singularity.conf
DEBUG   [U=3000178,P=128410]handleConfDir()               /home/s/scinet/nolta/.singularity already exists. Not creating.
DEBUG   [U=3000178,P=128410]getCacheParentDir()           environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=3000178,P=128410]Init()                        Image format detection
DEBUG   [U=3000178,P=128410]Init()                        Check for sandbox image format
DEBUG   [U=3000178,P=128410]Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=3000178,P=128410]Init()                        Check for sif image format
DEBUG   [U=3000178,P=128410]Init()                        sif image format detected
DEBUG   [U=3000178,P=128410]Init()                        Image format detection
DEBUG   [U=3000178,P=128410]Init()                        Check for sandbox image format
DEBUG   [U=3000178,P=128410]Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=3000178,P=128410]Init()                        Check for sif image format
DEBUG   [U=3000178,P=128410]Init()                        sif image format detected
DEBUG   [U=3000178,P=128410]newBundle()                   Created temporary directory "/tmp/bundle-temp-289466819" for the bundle
DEBUG   [U=3000178,P=128410]newBundle()                   Created directory "/dev/shm/nolta/build-temp-268092148/rootfs" for the bundle
INFO    [U=3000178,P=128410]Full()                        Starting build...
DEBUG   [U=3000178,P=128410]Init()                        Image format detection
DEBUG   [U=3000178,P=128410]Init()                        Check for sandbox image format
DEBUG   [U=3000178,P=128410]Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=3000178,P=128410]Init()                        Check for sif image format
DEBUG   [U=3000178,P=128410]Init()                        sif image format detected
DEBUG   [U=3000178,P=128410]GetLocalPacker()              Packing from SIF
DEBUG   [U=3000178,P=128410]extract()                     Rootless extraction. Trying -user-xattrs for unsquashfs
ERROR   [U=3000178,P=128410]Pack()                        unpackSIF failed: root filesystem extraction failed: extract command failed: WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/usr/sbin/unsquashfs: error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory
: exit status 127
DEBUG   [U=3000178,P=128410]cleanUp()                     Cleaning up "/dev/shm/nolta/build-temp-268092148/rootfs" and "/tmp/bundle-temp-289466819"
FATAL   [U=3000178,P=128410]runBuildLocal()               While performing build: packer failed to pack: root filesystem extraction failed: extract command failed: WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/usr/sbin/unsquashfs: error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory
: exit status 127
```

**Comment by dtrudg** [comment]
In this case your `/tmp` appears to be pointing to a `/dev/shm` `tmpfs` filesystem. I'd expect a workaround for now to be to point `SINGULARITY_TMPDIR` at a location that is a local physically backed filesystem - i.e. ext4/xfs/btrfs etc should work.

The issue might occur if `TMPDIR` is pointing to a `tmpfs` or a network (GPFS / lustre / BeeGFS etc.) filesystem. We need to look into it more in order to make things work as they did in previous versions, prior to wrapping `unsquashfs` for security reasons.

**Comment by nolta** [comment]
Unfortunately, this is on a supercomputer, and there is no local storage. GPFS & tmpfs are the only options.

Why does local physical storage work, but not tmpfs?

**Comment by dtrudg** [comment]
Generally....

In various situations container runtimes makes use of kernel features such as overlay mounts, user namespace, uid/gid mapping, xattrs etc. that are not fully supported by all filesystems. Common local filesystems like `ext4/xfs/btrfs` usually work reliably always because support of these kernel features starts there (they are the most common fs). Network file systems have a server which is not aware of all the state on the local host... and this means some things are not supported on network filesystems. `tmpfs`-es are in the middle ground. They should work, but are relatively commonly set with mount options that cause failures in some circumstances, don't support xattrs etc.

In this case...

Because `unsquashfs`, used to extract .sif container images, doesn't sanitize paths (https://github.com/hpcng/singularity/security/advisories/GHSA-7gcp-w6ww-2xv9) we now run it within a container-like sandbox for security, using singularity itself. 

Some part of that `unsquashfs` containment is not working, as the library needed by `unsquashfs` is not being bound in. I'm not certain on the exact cause of it not working with `tmpfs` yet... and actually it could still be not related to the that filesystem.

What would be useful is a bit more information about the mounts on your system. Clusters without local storage vary quite a bit in setup. If you can provide the output of `mount` that would be very useful to construct a reproducer environment.

Also, what is the Linux distro, kernel version, and where is `libgcc_s.so.1` on your host? Do you have overlays etc. in play to present a read-write `/` over a read-only image or network base etc.?

**Comment by nolta** [comment]
```
$ mount | grep /dev/shm
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)

$ ldconfig -p | grep libgcc_s
	libgcc_s.so.1 (libc6,x86-64) => /lib64/libgcc_s.so.1

$ mount | grep rootfs
rootfs on / type tmpfs (rw,relatime,mode=755)
```

**Comment by nolta** [comment]
```
$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)

$ uname -a
Linux tds01.scinet.local 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dtrudg** [comment]
@nolta - thanks, this is going to take a little while to dig into.

@cclerget - any thoughts off the top of your head on this one? The other GPFS related failure reported on the mailing list that was successfully worked around with TMPDIR I do understand.

**Comment by nolta** [comment]
I should also mention that this worked with singularity v3.6.3.

**Comment by cclerget** [comment]
@nolta Could you paste output of `ldd $(which unsquashfs)` ?

**Comment by dtrudg** [comment]
> I should also mention that this worked with singularity v3.6.3.

Yup - it's expected that this would work with 3.6.3. It's related to how the security fix in 3.6.4 works.

One question - in another part of the code that does library resolution (nvidia support) - we had an issue from a ComputeCanada cluster where Nix was in use and Singularity was finding a nix `ldd` etc. Do you happen to be using a setup similar to that at all?

I've been chatting to @cclerget and we think this one may not be an fs issue at all.

What do you get for...

```
which singularity
which unsquashfs
which ldd
````

**Comment by nolta** [comment]
```
$ which singularity unsquashfs ldd 
/usr/bin/singularity
/usr/sbin/unsquashfs
/usr/bin/ldd

$ ldd $(which unsquashfs)
	linux-vdso.so.1 =>  (0x00007ffe40f94000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9cf7c4d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9cf794b000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f9cf7735000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f9cf750f000)
	liblzo2.so.2 => /lib64/liblzo2.so.2 (0x00007f9cf72ee000)
	libgcc_s.so.1 => /scinet/niagara/software/2019b/core/lib64/libgcc_s.so.1 (0x00007f9cf70d7000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9cf6d0a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9cf7e69000)
```
This is a ComputeCanada system, but it's not using the Nix stack of the other clusters.

Looks like this has something to do with our local software stack, as this works:
```
$ ( unset LD_LIBRARY_PATH; singularity build --sandbox sandbox python_latest.sif )
INFO:    Starting build...
INFO:    Creating sandbox directory...
INFO:    Build complete: sandbox
```

**Comment by cclerget** [comment]
Ok that was my guess, fix will be easy

**Comment by dtrudg** [comment]
@nolta - are you able to verify #5669 is a fix? Should be working as far as we can tell.

**Comment by nolta** [comment]
Yes, it appears to fix this.
