### ISSUE TITLE
Is expand functioning?

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#567]
I made need to update my version (something I can't do as I have something actively running that would be bad to lose) but with a quick test, expand doesn't seem to be working - isn't this an old file that we don't have anymore, or it is located elsewhere?

```bash
sudo singularity expand ubuntu.img 
Expanding existing image with a size of 512MiB...
/usr/local/libexec/singularity/cli/expand.exec: line 94: /usr/local/libexec/singularity/bin/simage: No such file or directory
```

**Comment by gmkurtzer** [comment]
Ahh, good catch. Adding that to my list!

**Comment by gmkurtzer** [comment]
I think this is fixed, but I rushed through it. Will test and write a test for it tomorrow.

**Comment by vsoch** [comment]
ok! Still super speedy!

**Comment by gmkurtzer** [comment]
Done. Will you test and close if it looks good?

Thanks!

**Comment by vsoch** [comment]
yep !!

**Comment by vsoch** [comment]
I mean I'll test it - I can't confirm it looks good yet, lol.

**Comment by vsoch** [comment]
:boom:

**Comment by vsoch** [comment]
ok first test, creating an image, not importing anything, expanding without --size

```bash
 singularity expand ubuntu.img 
Initializing Singularity image subsystem
Opening image file: ubuntu.img
Expanding image by 768MiB
Binding image to loop
Checking file system
e2fsck 1.42.13 (17-May-2015)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/dev/loop0: 11/49152 files (0.0% non-contiguous), 7387/196608 blocks
Resizing file system
resize2fs 1.42.13 (17-May-2015)
Resizing the filesystem on /dev/loop0 to 393216 (4k) blocks.
The filesystem on /dev/loop0 is now 393216 (4k) blocks long.

Image is done: ubuntu.img
```

importing...
running...
works!

Ok next I tested different derivations of creating and importing, then resizing. There are a few bugs to look at:

- the help says the default expand is 512, but it looks like it's 768MiB
- when I add `--size` or `-s` it totally ignores me! I wanted a super fat image, and it just got a little fatter:

```bash
vanessa@som-ctp:/tmp$ singularity expand -s 4000 ubuntu.img 
Initializing Singularity image subsystem
Opening image file: ubuntu.img
Expanding image by 768MiB
Binding image to loop
Checking file system
e2fsck 1.42.13 (17-May-2015)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/dev/loop0: 8055/344064 files (4.9% non-contiguous), 62443/1376256 blocks
Resizing file system
resize2fs 1.42.13 (17-May-2015)
Resizing the filesystem on /dev/loop0 to 1572864 (4k) blocks.
The filesystem on /dev/loop0 is now 1572864 (4k) blocks long.
```

What am I going to eat for Thanksgiving dinner now?!

**Comment by gmkurtzer** [comment]
Oh gosh... sorry about that, and good catches! Fixed! Can you test again?

**Comment by vsoch** [comment]
ok looks good! One thing I noticed too - didn't we used to have command line completion for commands line import, bootstrap - it doesn't seem to be working for me!

**Comment by gmkurtzer** [comment]
We do have a bash_completion script, what isn't working?

**Comment by vsoch** [comment]
oh lord, @bbockelm you wrote that right? [here is the hairball](https://github.com/singularityware/singularity/blob/development/etc/bash_completion.d/singularity)

**Comment by gmkurtzer** [comment]
Haha, actually... It is one of the nicest completion scripts that I've seen!

**Comment by vsoch** [comment]
This is fixed. We can address the bash completion in another issue (I will open)
