### ISSUE TITLE
Singularity vmx_init: processor does not support desired secondary processor-based controls

### ISSUE THREAD

**Issue by ayoungs** [apptainer/singularity#5672]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```
3.3.0-rc.1.658.g7427b73f1.dirty

singularity run lolcow.simg  
### Expected behavior

What did you expect to see when you do...?

Expected either a command prompt or bash

### Actual behavior

What actually happend? Why was it incorrect?

vmx_init: processor does not support desired secondary processor-based controls

### Steps to reproduce this behavior

Use this simple Singularity recipe
Bootstrap: docker
From: ubuntu:18.04

%post
    apt-get -y update
    

%environment
    export LC_ALL=C
    export PATH=/usr/games:$PATH

How can others reproduce this issue/problem?

singularity build --remote lolcow.simg Singularity

singularity run --vm-err lolcow.simg
vmx_set_ctlreg: cap_field: 2 bit: 14 unspecified don't care
vmx_init: processor does not support desired secondary processor-based controls
Unable to create VM (22)

### What OS/distro are you running

```
$ cat /etc/os-release


```
Darwin XXXXX-Mac-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 24 21:21:05 PDT 2020; root:xnu-7195.50.3.201.1~1/RELEASE_X86_64 x86_64

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

Installed on Mac Pro via download from Singularity website.

**Comment by dtrudg** [comment]
Per the message on the Sylabs site, Singularity is not currently supported on Mac. The beta Desktop release is available as-is without fixes,

>Please Note - Singularity Desktop for macOS is a Beta release, and has not been updated for compatibility with the new SIF signature format in Singularity 3.6.0.

>Sylabs™ is currently engaging with the community to plot a course for the future of the Mac version of Singularity. In the meantime, please be aware that the release has not received recent security and bug fixes, and should be used at your own risk.

Root cause may be related to the OS X / macOS version and the VM software that Singularity Desktop on Mac used: https://github.com/machyve/xhyve/issues/10
