### ISSUE TITLE
rhel6 kernel panic

### ISSUE THREAD

**Issue by robbinslewis** [apptainer/singularity#5681]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.6.4

```

### Expected behavior

What did you expect to see when you do...?

### Actual behavior

We have recently starting to experience kernel panics on our rhel6.10 HPC cluster. RedHat support has analyzed the crash dump and believes that "starter-suid" is triggering a bug "due to NULL pointer dereference in the function nlmclnt_setlockargs()." Specifically with "loop devices which have the backing file under nfs mount"
Apparently this bug is fixed in Rhel7. (commit 9a1b6bf818e74bb7aabaecb59492b739f2f4d742) but upgrading the compute nodes is not a minor undertaking.

Is this bug something that was likely triggered in 3.6.4 or is it possibly related to an individual image?

I've included the full crash analysis below, it's lengthy, but hopefully helps explain the issue.

crash> sys
      KERNEL: /cores/retrace/repos/kernel/x86_64/usr/lib/debug/lib/modules/2.6.32-754.35.1.el6.x86_64/vmlinux
    DUMPFILE: /cores/retrace/tasks/932519426/crash/vmcore  [PARTIAL DUMP]
        CPUS: 64
        DATE: Fri Oct 30 12:00:49 EDT 2020
      UPTIME: 00:28:11
LOAD AVERAGE: 1.53, 0.57, 0.37
       TASKS: 1651
    NODENAME: c34b01
     RELEASE: 2.6.32-754.35.1.el6.x86_64
     VERSION: #1 SMP Wed Sep 16 06:48:01 EDT 2020
     MACHINE: x86_64  (2499 Mhz)
      MEMORY: 512 GB
       PANIC: "BUG: unable to handle kernel NULL pointer dereference at 0000000000000008"

crash> set -p
    PID: 25137
COMMAND: "starter-suid"
   TASK: ffff8810077d8040  [THREAD_INFO: ffff8810076ec000]
    CPU: 0
  STATE: TASK_RUNNING (PANIC)

crash> bt
PID: 25137  TASK: ffff8810077d8040  CPU: 0   COMMAND: "starter-suid"
 #0 [ffff8810076ef450] machine_kexec at ffffffff8104179b
 #1 [ffff8810076ef4b0] crash_kexec at ffffffff810d7a52
 #2 [ffff8810076ef580] oops_end at ffffffff81560310
 #3 [ffff8810076ef5b0] no_context at ffffffff8105578b
 #4 [ffff8810076ef600] __bad_area_nosemaphore at ffffffff81055a15
 #5 [ffff8810076ef650] bad_area_nosemaphore at ffffffff81055ae3
 #6 [ffff8810076ef660] __do_page_fault at ffffffff810561fc
 #7 [ffff8810076ef780] do_page_fault at ffffffff815622ce
 #8 [ffff8810076ef7b0] page_fault at ffffffff8155f265
    [exception RIP: nlmclnt_setlockargs+124]
    RIP: ffffffffa08b081c  RSP: ffff8810076ef868  RFLAGS: 00010296
    RAX: ffff8810077d8040  RBX: ffff880fd23f0c00  RCX: 0000000000000000
    RDX: 0000000000000000  RSI: 000000000000004a  RDI: ffff880fd23f0f34
    RBP: ffff8810076ef878   R8: ffff880fd21eeb80   R9: 0000000000000000
    R10: 0000000000000073  R11: 0000000000000000  R12: ffff8810076ef998
    R13: ffff8810076ef998  R14: ffff884fdacb5bb0  R15: ffff884fdacb5a00
    ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
 #9 [ffff8810076ef880] nlmclnt_proc at ffffffffa08b13d6 [lockd]
#10 [ffff8810076ef8e0] nfs3_proc_lock at ffffffffa08e79e8 [nfs]
#11 [ffff8810076ef8f0] do_unlk at ffffffffa08d2c58 [nfs]
#12 [ffff8810076ef940] nfs_flock at ffffffffa08d2e56 [nfs]
#13 [ffff8810076ef970] locks_remove_flock at ffffffff811f5379
#14 [ffff8810076efa70] __fput at ffffffff811a46a0
#15 [ffff8810076efac0] fput at ffffffff811a4815
#16 [ffff8810076efad0] loop_clr_fd at ffffffff813a3cff
#17 [ffff8810076efb10] lo_release at ffffffff813a457a <--- trying to release loop device
#18 [ffff8810076efb30] __blkdev_put at ffffffff811e13e9
#19 [ffff8810076efb80] blkdev_put at ffffffff811e1410
#20 [ffff8810076efb90] close_bdev_exclusive at ffffffff811e14ac
#21 [ffff8810076efbb0] kill_block_super at ffffffff811a52d4
#22 [ffff8810076efbd0] deactivate_super at ffffffff811a5a9f <---- Trying to deactivate the superblock (possible umount)
#23 [ffff8810076efbf0] mntput_no_expire at ffffffff811c5f1f
#24 [ffff8810076efc20] release_mounts at ffffffff811c6669
#25 [ffff8810076efc50] put_mnt_ns at ffffffff811c6718
#26 [ffff8810076efc90] free_nsproxy at ffffffff810b1c8f
#27 [ffff8810076efcb0] switch_task_namespaces at ffffffff810b1d50
#28 [ffff8810076efce0] exit_task_namespaces at ffffffff810b1d70
#29 [ffff8810076efcf0] do_exit at ffffffff81087194
#30 [ffff8810076efd70] do_group_exit at ffffffff810875f8
#31 [ffff8810076efda0] get_signal_to_deliver at ffffffff8109d576
#32 [ffff8810076efe40] do_signal at ffffffff8100a375
#33 [ffff8810076eff30] do_notify_resume at ffffffff8100ac60
#34 [ffff8810076eff50] int_signal at ffffffff8156672f
    RIP: 000056118dfc7bf3  RSP: 00002b768a0a5ce8  RFLAGS: 00000286
    RAX: fffffffffffffe00  RBX: 000000c00003e700  RCX: ffffffffffffffff
    RDX: 0000000000000000  RSI: 0000000000000080  RDI: 000000c00003e848
    RBP: 00002b768a0a5d30   R8: 0000000000000000   R9: 0000000000000000
    R10: 0000000000000000  R11: 0000000000000286  R12: 0000000000000000
    R13: 0000000000000001  R14: 000000c00006e3c0  R15: 0000000000000000
    ORIG_RAX: 00000000000000ca  CS: 0033  SS: 002b

crash> dis -rl ffffffffa08b081c | tail
0xffffffffa08b07fc <nlmclnt_setlockargs+92>:    mov    $0x4a,%esi
/usr/src/debug/kernel-2.6.32-754.35.1.el6/linux-2.6.32-754.35.1.el6.x86_64/fs/lockd/clntproc.c: 130
0xffffffffa08b0801 <nlmclnt_setlockargs+97>:    mov    %ax,0x4(%rdi)
/usr/src/debug/kernel-2.6.32-754.35.1.el6/linux-2.6.32-754.35.1.el6.x86_64/fs/lockd/clntproc.c: 132
0xffffffffa08b0805 <nlmclnt_setlockargs+101>:   lea    0x334(%rbx),%rdi
/usr/src/debug/kernel-2.6.32-754.35.1.el6/linux-2.6.32-754.35.1.el6.x86_64/arch/x86/include/asm/current.h: 14
0xffffffffa08b080c <nlmclnt_setlockargs+108>:   mov    %gs:0xfc00,%rax
/usr/src/debug/kernel-2.6.32-754.35.1.el6/linux-2.6.32-754.35.1.el6.x86_64/fs/lockd/clntproc.c: 131 <----
0xffffffffa08b0815 <nlmclnt_setlockargs+117>:   mov    0x760(%rax),%rdx
0xffffffffa08b081c <nlmclnt_setlockargs+124>:   mov    0x8(%rdx),%rdx <---

RDX: 0000000000000000

crash> px (0x0000000000000000 + 0x8)
$4 = 0x8 <---

Same as panic string:

crash> sys | grep -i panic
       PANIC: "BUG: unable to handle kernel NULL pointer dereference at 0000000000000008"

We crash in below function at line 131:

124 static void nlmclnt_setlockargs(struct nlm_rqst *req, struct file_lock *fl)
125 {
126         struct nlm_args *argp = &req->a_args;
127         struct nlm_lock *lock = &argp->lock;
128
129         nlmclnt_next_cookie(&argp->cookie);
130         memcpy(&lock->fh, NFS_FH(fl->fl_file->f_path.dentry->d_inode), sizeof(struct nfs_fh));
131         lock->caller  = utsname()->nodename; <-------
132         lock->oh.data = req->a_owner;
133         lock->oh.len  = snprintf(req->a_owner, sizeof(req->a_owner), "%u@%s",
134                                 (unsigned int)fl->fl_u.nfs_fl.owner->pid,
135                                 utsname()->nodename);
136         lock->svid = fl->fl_u.nfs_fl.owner->pid;
137         lock->fl.fl_start = fl->fl_start;
138         lock->fl.fl_end = fl->fl_end;
139         lock->fl.fl_type = fl->fl_type;
140 }

crash> nfs_flock
nfs_flock = $5 =
 {int (struct file *, int, struct file_lock *)} 0xffffffffa08d2da0 <nfs_flock>

crash> struct file.f_path 0xffff880fd221d080
  f_path = {
    mnt = 0xffff885009ce8980,
    dentry = 0xffff880e6505cc80
  }

crash> files -d 0xffff880e6505cc80
     DENTRY           INODE           SUPERBLK     TYPE PATH
ffff880e6505cc80 ffff880e6501ecb8 ffff884f81891c00 REG  singularity/UMMS-Biocore-singularitysc-master-latest.simg

crash> mount | grep -e SUPER -e ffff884f81891c00
    VFSMOUNT         SUPERBLK     TYPE   DEVNAME   DIRNAME
ffff885009ce8980 ffff884f81891c00 nfs    umassmghpcc.umassrc.org:/ifs/xdata/project/umw_biocore /project/umw_biocore

From log I can see just before crash loop devices were mounted:

loop: module loaded
EXT3-fs (loop0): mounted filesystem with ordered data mode
EXT3-fs (loop1): mounted filesystem with ordered data mode

crash> loop_clr_fd
loop_clr_fd = $18 =
 {int (struct loop_device *, struct block_device *)} 0xffffffff813a3b30 <loop_clr_fd>

Cannot find the backing file as the device is unmounted.

crash> struct loop_device.lo_disk,lo_backing_file,lo_file_name,lo_device 0xffff884008a12000
  lo_disk = 0xffff881006f2d000
  lo_backing_file = 0x0
  lo_file_name = "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  lo_device = 0x0

It was loop1:

crash> close_bdev_exclusive
close_bdev_exclusive = $20 =
 {void (struct block_device *, fmode_t)} 0xffffffff811e1480 <close_bdev_exclusive>

crash> struct block_device.bd_disk 0xffff88100951ca40
  bd_disk = 0xffff881006f2d000

crash> gendisk.major,first_minor,disk_name 0xffff881006f2d000
  major = 7
  first_minor = 1
  disk_name = "loop1\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"

crash> mntput_no_expire
mntput_no_expire = $21 =
 {void (struct vfsmount *)} 0xffffffff811c5e60 <mntput_no_expire>

crash> vfsmount.mnt_mountpoint,mnt_root,mnt_sb 0xffff880fd23dc8c0
  mnt_mountpoint = 0xffff880e6532aa80
  mnt_root = 0xffff880e6532aa80
  mnt_sb = 0xffff88100092a800

crash> struct vfsmount.mnt_devname 0xffff880fd23dc8c0
  mnt_devname = 0xffff880e6140d720 "/dev/loop1"

crash> struct super_block.s_id,s_type 0xffff88100092a800
  s_id = "loop1"
  s_type = 0xffffffffa09a4a40 <ext3_fs_type>

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

source

**Comment by dtrudg** [comment]
Because RHEL6 reaches end of maintenance stage at the end of this month, Singularity won't be making further efforts to support it past this time. As we are now working on a 3.7.0 release I'm afraid it is unlikely that there is time to look into RHEL6 bug related issues for the remaining 30 days.

The changes from 3.6-3 -> 3.6-4 are primarily related to handling a security issue in unsquashfs, and I would not expect them to result in this bug being triggered more often by simply running image file containers.

Given that Red Hat have stated this is a bug in RHEL6 (not Singularity), and the bug is 'Specifically with "loop devices which have the backing file under nfs mount' then moving images off of NFS onto local or other storage to run should fix the issue. Note that you can restrict the directories from which images have been executed in `singularity.conf` so that users cannot run from the NFS location, to avoid crashes.
