### ISSUE TITLE
Singlularity build failing in Ubuntu 20.04 (VM Win10 Host)

### ISSUE THREAD

**Issue by mvfbbk** [apptainer/singularity#5686]
### Version of Singularity: 

What version of Singularity are you using? 3.6.4

./mconfig && make -C builddir && sudo make -C builddir install

### Expected behavior

I expect singularity to complete installation

### Actual behavior

make: *** No rule to make target '/home/mat/Downloads/singularity/builddir/cni/dhcp', needed by '/usr/local/libexec/singularity/cni/dhcp'. Stop.
make: Leaving directory '/home/mat/Downloads/singularity/builddir'

### Steps to reproduce this behavior

Unknown

### What OS/distro are you running

Oracle VM Virtualbox 6.1.16 
Host:
Windows10 

Guest:
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### How did you install Singularity

Cloned the GitHub repository and followed instructions on https://sylabs.io/guides/3.6/user-guide/quick_start.html#quick-installation-steps

**Comment by srinivamd** [comment]
Seeing this on Ubuntu18 as well with singularity 3.7.1 build from tar ball. Any fix/workaround?

**Comment by dtrudg** [comment]
Haven't been able to reproduce this. I regularly build in Ubuntu 20.04 and 18.04 VMs without issue. We would need a bit more detail about what's going on. A full listing of what you get when running `./mconfig` etc. might be useful.

**Comment by srinivamd** [comment]
I think the issue happens when `make install` is run without running `make` first. I am able to build it now by running `make` first.

**Comment by dtrudg** [comment]
@srinivamd - in the original comment you wrote...

```
./mconfig && make -C builddir && sudo make -C builddir install
```

so this should have been running make first. Was it ommitted by mistake?

**Comment by srinivamd** [comment]
> ./mconfig && make -C builddir && sudo make -C builddir install
> ```
> so this should have been running make first. Was it ommitted by mistake?
@dtrudg that was not my comment.
I will try to reproduce the fail and update as I'm not certain what I did to get around the fail to get it working.

**Comment by dtrudg** [comment]
🤦 sorry... I didn't catch you weren't the original poster. My mistake! Your GitHub icons are very similar and I must have just glanced at them :-)

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
