### ISSUE TITLE
[development] "allow setuid = no" doesn't drop privileges

### ISSUE THREAD

**Issue by flx42** [apptainer/singularity#569]
With 5f5e3bc92f3d0aba07c060089585d4bb27da4cef  (development branch) and a small change in the default configuration file:
```diff
-#define ALLOW_SETUID_DEFAULT 1
+#define ALLOW_SETUID_DEFAULT 0
```
Compiled with `./autogen.sh && ./configure && make -j && sudo make install`.

Launching a container doesn't work (log shorten to highlight the interesting parts):
```
$ singularity -vvv shell docker://ubuntu:16.04
[...]
VERBOSE: Running SUID program workflow
VERBOSE: Checking program has appropriate permissions
VERBOSE: Checking configuration file is properly owned by root
VERBOSE: Checking if singularity.conf allows us to run as suid
VERBOSE: Invoking non-SUID program flow: /usr/local/libexec/singularity/bin/action
VERBOSE: Set messagelevel to: 4
VERBOSE: Initialize configuration file: /usr/local/etc/singularity/singularity.conf
VERBOSE: Got config key allow setuid = 'no'
[...]
VERBOSE: Running NON-SUID program workflow
[...]
VERBOSE: Invoking the user namespace
ERROR  : Failed to write to UID map /proc/3433/uid_map: Operation not permitted
ABORT  : Retval = 255
```
The SUID Singularity binary is calling the non-SUID binary.
I found that the effective UID is 0 before the `unshare(CLONE_NEWUSER)`, so probably the SUID program didn't drop privileges before calling the non-SUID program.

Then, my guess is that it fails because you are trying to set a mapping with a UID (1000) that is different from the parent user namespace UID (0), and we probably don't have CAP_SETUID, from man user_namespaces:
```
The data written to uid_map (gid_map) must consist of a
single line that maps the writing process's effective user
ID (group ID) in the parent user namespace to a user ID
(group ID) in the user namespace.
```

Note that the following works:
```
SINGULARITY_NOSUID=1 singularity shell docker://ubuntu:16.04
```
In this case, the `shell.exec` script dispatches immediately to the non-SUID binary. It's quite unfortunate that we have two different code paths for essentially the same option.

**Comment by gmkurtzer** [comment]
Great catch, thanks for letting me know. This is now fixed in 'development' branch, please confirm and close if so.

Thanks again!

**Comment by vsoch** [comment]
@flx42 ! How did you make that colorful? It's so pretty.

**Comment by flx42** [comment]
@vsoch https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

In this case:
\```diff
[...]
\```

**Comment by vsoch** [comment]
```diff
-THIS
+IS
-AWESOME
+!!!
```
Thanks!

**Comment by flx42** [comment]
Fixed, closing!
