### ISSUE TITLE
RFE distributing container images

### ISSUE THREAD

**Issue by truatpasteurdotfr** [apptainer/singularity#57]
Hi,
- provide the container.def allong with the container.img
- naming: dot release and dot release with updates as of YYYY-MM-DD rolloed in?
  example CentOS-6.8-GA.img and CentOS-6.8-2016-06-07.img
- tar -CjSf container.tbz2 container.img container.def
- one needs to preserver the "sparse" file state, bzip2/gzip don't, but tar does!, otherwise expanding a compressed container.img yields a non sparse file, (possible workaroud is to cp --sparse=always expanded-non-sparse.img expanded-sparse-converted.img, but ymmv).

Cheers

**Comment by gmkurtzer** [comment]
Good catch on using tar! I will try and get to this ASAP today.

**Comment by gmkurtzer** [comment]
@truatpasteurdotfr Check out:

https://github.com/gmkurtzer/singularity-images

I am closing this issue but we should continue from that repository.

Thanks!
