### ISSUE TITLE
Overlay filesystem encryption when container is encrypted

### ISSUE THREAD

**Issue by tensoralex** [apptainer/singularity#5714]
Question: It is not clear from the documentation if new data (which is being written as a result of installing new software inside the container) to an ext3 overlay filesystem will be encrypted (when the container was built with encryption)?

### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```

```
3.6.4
```

### Expected behavior

What did you expect to see when you do...?

```
Data in overlay filesystem is being encrypted when a container is built with --encrypt flag.
```

### Actual behavior

```
Unknown.
```

```
sudo singularity sif list mycontainer.sif

----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-33507               |Def.FILE
2    |1       |NONE    |36864-39244               |JSON.Generic
3    |1       |NONE    |40960-5643051008          |FS (Encrypted squashfs/*System/amd64)
4    |1       |NONE    |5643051008-42343211008    |FS (Ext3/Overlay/amd64)
```

What actually happend? Why was it incorrect?

```
Not clear if data is being encrypted on the overlay filesystem when the container is built with the encryption option.
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

```
# Init an ovarlay volume
dd if=/dev/zero of=overlay.img bs=1M count=35000 && mkfs.ext3 overlay.img

# Build encrypted container from definiton
sudo singularity build --passphrase --encrypt  mycontainer.sif ubuntu.def

# Embed an overlay volume inside sif image
sudo singularity siftool add --datatype 4 --partfs 2 --parttype 4 --partarch 2 --groupid 1 mycontainer.sif overlay.img

# Enter container shell and write a new file
sudo singularity shell --nv --passphrase --writable mycontainer.sif mycontainer.sif

df -hP

Filesystem      Size  Used Avail Use% Mounted on
overlay          34G   49M   32G   1% /
udev             32G     0   32G   0% /dev
tmpfs            32G     0   32G   0% /dev/shm

echo "test" > /opt/testfile.txt
cat /opt/testfile.txt
test

# Check sif file
sudo singularity sif list mycontainer.sif


----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-33507               |Def.FILE
2    |1       |NONE    |36864-39244               |JSON.Generic
3    |1       |NONE    |40960-5643051008          |FS (Encrypted squashfs/*System/amd64)
4    |1       |NONE    |5643051008-42343211008    |FS (Ext3/Overlay/amd64)
```

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

```
Installed from source
```

**Comment by dtrudg** [comment]
The data in the overlay is not encrypted. We will add a note to the docs, and encryption of overlays is a good enhancement for the future.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by nihilee** [comment]
> The data in the overlay is not encrypted. We will add a note to the docs, and encryption of overlays is a good enhancement for the future.

Is there any preogress until 2022....

**Comment by DrDaveD** [comment]
No, nobody has worked on that.

Is it important to someone?  Someone who is depending on both encryption and the overlay image in the SIF file?  What is the use case?

**Comment by tensoralex** [comment]
If I produce an encrypted container with an embedded overlay image in it's SIF file, I would naturally want image contents to be encrypted as well. 

I work around it with LUKS encryption at the build time, but it is painful, and requires to have separate keys or passwords for the container and embedded image.

**Comment by ettaka** [comment]
This is an important point. Any progress on it?
@tensoralex could you elaborate on how you encrypt your data when using singularity?

**Comment by DrDaveD** [comment]
This repository is no longer active.  If someone still wants this feature, make a new SingularityCE or Apptainer issue, referring back to this one.
