### ISSUE TITLE
Question: Expand the size of the partition for --writable-tmpfs

### ISSUE THREAD

**Issue by tomeichlersmith** [apptainer/singularity#5718]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.6.4-1.el7
```

### Expected behavior

I would like to run [this docker container](https://hub.docker.com/repository/docker/tomeichlersmith/mg-dark-brem) built from [this build context](https://github.com/tomeichlersmith/mg-dark-brem/tree/main/docker). On my local system (with docker) I am able to run this container which generates a rather large file of simulated data. On a batch system that I have access to (with singularity), I would also like to run this same container to generate the same large file of simulated data.

### Actual behavior

When I run this container using
```
singularity run --no-home --writable-tmpfs --bind $(pwd) docker://tomeichlersmith/mg-dark-brem:edge --out $(pwd) -v
```
I eventually run out of space on the tmpfs that the container is using to "work" on generating the simulated data.  When I enter the container, I can mimic the entrypoint script and see the tmpfs filling up.
```
$ singularity shell --writable-tmpfs --no-home tomeichlersmith_mg-dark-brem_edge.sif
Singularity> cd /madgraph/
Singularity> df -h
Filesystem                       Size  Used Avail Use% Mounted on
overlay                           16M   12K   16M   1% /
devtmpfs                          24G     0   24G   0% /dev
tmpfs                             24G  120K   24G   1% /dev/shm
/dev/mapper/VolGroup00-LogVol00   57G  6.9G   48G  13% /etc/hosts
/dev/mapper/VolGroup00-LogVol06   30G  687M   28G   3% /tmp
/dev/mapper/VolGroup00-LogVol02   59G  3.5G   53G   7% /var/tmp
tmpfs                             16M   12K   16M   1% /etc/group
Singularity> ./bin/generate_events 0 TEST
<long output from simulation program>
Singularity> df -h
Filesystem                       Size  Used Avail Use% Mounted on
overlay                           16M   16M  484K  98% /
devtmpfs                          24G     0   24G   0% /dev
tmpfs                             24G  120K   24G   1% /dev/shm
/dev/mapper/VolGroup00-LogVol00   57G  6.9G   48G  13% /etc/hosts
/dev/mapper/VolGroup00-LogVol06   30G  687M   28G   3% /tmp
/dev/mapper/VolGroup00-LogVol02   59G  3.5G   53G   7% /var/tmp
tmpfs                             16M   16M  484K  98% /etc/group
```
**In an ideal world, I would be able to somehow expand the size of the tmpfs partition within the container so that the program can finish without complication.**

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
```
singularity run --no-home --writable-tmpfs --bind $(pwd) docker://tomeichlersmith/mg-dark-brem:edge --out $(pwd) -v
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity
_Unknown_: Came installed on this batch system that I am using.

**Comment by tashrifbillah** [comment]
Hi @tomeichlersmith , I am having the same issue. Did you find a solution for this?

This is the intriguing line in `df -h` for non-root users:

> tmpfs                             16M   12K   16M   1% /etc/group

Which is different for root user:
```
Filesystem               Size  Used Avail Use% Mounted on
overlay                   63G  2.3G   61G   4% /
devtmpfs                  63G     0   63G   0% /dev
tmpfs                     63G     0   63G   0% /dev/shm
/dev/mapper/centos-root   50G   30G   21G  59% /tmp
tmpfs                     63G  2.3G   61G   4% /etc/resolv.conf
```

**Comment by tashrifbillah** [comment]
Here is my comment that should solve it:

https://github.com/hpcng/singularity/issues/798#issuecomment-753531382

**Comment by tomeichlersmith** [comment]
Thank you for the extra information. I unfortunately do not have access to the `singularity.conf` file, but I was able to find another work-around simply by doing my work inside of a scratch directory mounted to the container. Not ideal, but it works!

**Comment by tashrifbillah** [comment]
You are right, most users won't have access to `singularity.conf`. I agree with you, that is another way of solving write accessibility to a read-only SIF image.

**Comment by jjacobson95** [comment]
This would be a very useful addition to add to singularity build or a def file.  [tashrifbillah](https://github.com/tashrifbillah) is right, many users can't modify their singularity.conf file (I'm working on a HPC).

**Comment by DrDaveD** [comment]
If you would like to see this addressed in a future release of apptainer please submit your feature request to https://github.com/apptainer/apptainer/issues.  I don't know if it will be accepted because of the impact on RAM that the user might not understand, but the discussion should be there.  There may also be other options using bind mounts like the issue creator here ended up using.

**Comment by DrDaveD** [comment]
Actually I think it might make more sense to add a `--writable-scratch` option that creates scratch space on disk rather than in memory.

**Comment by DrDaveD** [comment]
Continued in apptainer/apptainer#1313
