### ISSUE TITLE
singularity fakeroot and TMPDIR on AWS's EFS filesystems

### ISSUE THREAD

**Issue by steveheistand** [apptainer/singularity#5724]
Using version 3.6.4. 
Singularity is built from source.

When trying to build a new sif file as a user its failing when SINGULARITY_TMPDIR is pointing to an EFS filesystem in AWS.

Running on amzn linux2 base OS image.
user has been added and enabled to use fakeroot via the singularity config fakeroot command

singularity -d build --fakeroot new.sif new.def 
DEBUG   [U=1821,P=11663]   persistentPreRun()            Singularity version: 3.6.4
DEBUG   [U=1821,P=11663]   persistentPreRun()            Parsing configuration file /usr/local/etc/singularity/singularity.conf
DEBUG   [U=1821,P=11663]   handleConfDir()               Created /u/sheistan/.singularity
DEBUG   [U=1821,P=11663]   setValue()                    Updated flag 'tmpdir' value to: /nobackup/sheistan
DEBUG   [U=1821,P=11663]   init()                        Use starter binary /usr/local/libexec/singularity/bin/starter-suid
VERBOSE [U=0,P=11663]      print()                       Set messagelevel to: 5
VERBOSE [U=0,P=11663]      init()                        Starter initialization
DEBUG   [U=0,P=11663]      get_pipe_exec_fd()            PIPE_EXEC_FD value: 8
VERBOSE [U=0,P=11663]      is_suid()                     Check if we are running as setuid
VERBOSE [U=0,P=11663]      priv_drop()                   Drop root privileges
DEBUG   [U=1821,P=11663]   init()                        Read engine configuration
DEBUG   [U=1821,P=11663]   init()                        Wait completion of stage1
VERBOSE [U=1821,P=11671]   priv_drop()                   Drop root privileges permanently
DEBUG   [U=1821,P=11671]   set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1821,P=11671]   init()                        Spawn stage 1
DEBUG   [U=1821,P=11671]   startup()                     fakeroot runtime engine selected
VERBOSE [U=1821,P=11671]   startup()                     Execute stage 1
DEBUG   [U=1821,P=11671]   StageOne()                    Entering stage 1
VERBOSE [U=1821,P=11663]   wait_child()                  stage 1 exited with status 0
DEBUG   [U=1821,P=11663]   cleanup_fd()                  Close file descriptor 4
DEBUG   [U=1821,P=11663]   cleanup_fd()                  Close file descriptor 5
DEBUG   [U=1821,P=11663]   cleanup_fd()                  Close file descriptor 6
DEBUG   [U=1821,P=11663]   init()                        Set child signal mask
DEBUG   [U=1821,P=11663]   init()                        Create socketpair for master communication channel
DEBUG   [U=1821,P=11663]   init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=1821,P=11663]   user_namespace_init()         Create user namespace
VERBOSE [U=1821,P=11663]   pid_namespace_init()          Create pid namespace
VERBOSE [U=1821,P=11663]   init()                        Spawn master process
VERBOSE [U=1821,P=11663]   priv_escalate()               Get root privileges
DEBUG   [U=0,P=11663]      setup_userns_mappings()       Write allow to setgroups file
DEBUG   [U=0,P=11663]      setup_userns_mappings()       Write to GID map
DEBUG   [U=0,P=11663]      setup_userns_mappings()       Write to UID map
DEBUG   [U=0,P=1]          set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=11663]      set_master_privileges()       Set master privileges
DEBUG   [U=0,P=11663]      apply_privileges()            Effective capabilities:   0x00000000000000c0
DEBUG   [U=0,P=11663]      apply_privileges()            Permitted capabilities:   0x0000003fffffffff
DEBUG   [U=0,P=11663]      apply_privileges()            Bounding capabilities:    0x0000003fffffffff
DEBUG   [U=0,P=11663]      apply_privileges()            Inheritable capabilities: 0x0000003fffffffff
DEBUG   [U=0,P=11663]      apply_privileges()            Ambient capabilities:     0x0000000000000000
DEBUG   [U=0,P=11663]      apply_privileges()            Set user ID to 1821
VERBOSE [U=0,P=1]          create_namespace()            Create mount namespace
DEBUG   [U=0,P=2]          set_rpc_privileges()          Set RPC privileges
DEBUG   [U=0,P=2]          apply_privileges()            Effective capabilities:   0x0000000000200000
DEBUG   [U=0,P=2]          apply_privileges()            Permitted capabilities:   0x0000003fffffffff
DEBUG   [U=0,P=2]          apply_privileges()            Bounding capabilities:    0x0000000008204000
DEBUG   [U=0,P=2]          apply_privileges()            Inheritable capabilities: 0x0000000000000000
DEBUG   [U=0,P=2]          apply_privileges()            Ambient capabilities:     0x0000000000000000
DEBUG   [U=0,P=2]          apply_privileges()            Set user ID to 0
DEBUG   [U=0,P=2]          set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=2]          init()                        Spawn RPC server
DEBUG   [U=1821,P=11663]   startup()                     fakeroot runtime engine selected
VERBOSE [U=1821,P=11663]   startup()                     Execute master process
DEBUG   [U=0,P=2]          startup()                     fakeroot runtime engine selected
VERBOSE [U=0,P=2]          startup()                     Serve RPC requests
VERBOSE [U=0,P=1]          wait_child()                  rpc server exited with status 0
DEBUG   [U=0,P=1]          init()                        Set container privileges
DEBUG   [U=0,P=1]          apply_privileges()            Effective capabilities:   0x0000003fffffffff
DEBUG   [U=0,P=1]          apply_privileges()            Permitted capabilities:   0x0000003fffffffff
DEBUG   [U=0,P=1]          apply_privileges()            Bounding capabilities:    0x0000003fffffffff
DEBUG   [U=0,P=1]          apply_privileges()            Inheritable capabilities: 0x0000003fffffffff
DEBUG   [U=0,P=1]          apply_privileges()            Ambient capabilities:     0x0000003fffffffff
DEBUG   [U=0,P=1]          apply_privileges()            Set main group ID to 0
DEBUG   [U=0,P=1]          apply_privileges()            Set 1 additional group IDs
DEBUG   [U=0,P=1]          apply_privileges()            Set user ID to 0
DEBUG   [U=0,P=1]          set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=1]          startup()                     fakeroot runtime engine selected
VERBOSE [U=0,P=1]          startup()                     Execute stage 2
DEBUG   [U=0,P=1]          StageTwo()                    Entering stage 2
DEBUG   [U=0,P=1]          persistentPreRun()            Singularity version: 3.6.4
DEBUG   [U=0,P=1]          persistentPreRun()            Parsing configuration file /usr/local/etc/singularity/singularity.conf
DEBUG   [U=0,P=1]          handleConfDir()               /root/.singularity already exists. Not creating.
DEBUG   [U=0,P=1]          setValue()                    Updated flag 'tmpdir' value to: /nobackup/sheistan
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache/library
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache/oci-tmp
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache/shub
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache/oras
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache/net
DEBUG   [U=0,P=1]          Init()                        Image format detection
DEBUG   [U=0,P=1]          Init()                        Check for sandbox image format
DEBUG   [U=0,P=1]          Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=1]          Init()                        Check for sif image format
DEBUG   [U=0,P=1]          Init()                        sif format initializer returned: can't read first 2048 bytes: <nil>
DEBUG   [U=0,P=1]          Init()                        Check for squashfs image format
DEBUG   [U=0,P=1]          Init()                        squashfs format initializer returned: can't read first 2048 bytes: <nil>
DEBUG   [U=0,P=1]          Init()                        Check for ext3 image format
DEBUG   [U=0,P=1]          Init()                        ext3 format initializer returned: can't read first 2048 bytes: <nil>
DEBUG   [U=0,P=1]          newBundle()                   Created temporary directory "/nobackup/sheistan/bundle-temp-063350162" for the bundle
DEBUG   [U=0,P=1]          newBundle()                   Created directory "/nobackup/sheistan/build-temp-857390399/rootfs" for the bundle
DEBUG   [U=0,P=1]          ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=0,P=1]          ensureGzipComp()              Gzip compression by default ensured
INFO    [U=0,P=1]          Full()                        Starting build...
DEBUG   [U=0,P=1]          Get()                         Getting container from Library
DEBUG   [U=0,P=1]          cleanUp()                     Cleaning up "/nobackup/sheistan/build-temp-857390399/rootfs" and "/nobackup/sheistan/bundle-temp-063350162"
FATAL   [U=0,P=1]          runBuildLocal()               While performing build: conveyor failed to get: while inserting base environment: build: failed to stat rootPath: stat /nobackup/sheistan/build-temp-857390399/rootfs: no such file or directory
DEBUG   [U=1821,P=11663]   Master()                      Child exited with exit status 255

pointing at /tmp for TMPDIR allows this to work fine.

DEBUG   [U=1821,P=10932]   persistentPreRun()            Singularity version: 3.6.4
DEBUG   [U=1821,P=10932]   persistentPreRun()            Parsing configuration file /usr/local/etc/singularity/singularity.conf
DEBUG   [U=1821,P=10932]   handleConfDir()               /u/sheistan/.singularity already exists. Not creating.
DEBUG   [U=1821,P=10932]   setValue()                    Updated flag 'tmpdir' value to: /tmp
DEBUG   [U=1821,P=10932]   init()                        Use starter binary /usr/local/libexec/singularity/bin/starter-suid
VERBOSE [U=0,P=10932]      print()                       Set messagelevel to: 5
VERBOSE [U=0,P=10932]      init()                        Starter initialization
DEBUG   [U=0,P=10932]      get_pipe_exec_fd()            PIPE_EXEC_FD value: 8
VERBOSE [U=0,P=10932]      is_suid()                     Check if we are running as setuid
VERBOSE [U=0,P=10932]      priv_drop()                   Drop root privileges
DEBUG   [U=1821,P=10932]   init()                        Read engine configuration
DEBUG   [U=1821,P=10932]   init()                        Wait completion of stage1
VERBOSE [U=1821,P=10939]   priv_drop()                   Drop root privileges permanently
DEBUG   [U=1821,P=10939]   set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1821,P=10939]   init()                        Spawn stage 1
DEBUG   [U=1821,P=10939]   startup()                     fakeroot runtime engine selected
VERBOSE [U=1821,P=10939]   startup()                     Execute stage 1
DEBUG   [U=1821,P=10939]   StageOne()                    Entering stage 1
VERBOSE [U=1821,P=10932]   wait_child()                  stage 1 exited with status 0
DEBUG   [U=1821,P=10932]   cleanup_fd()                  Close file descriptor 4
DEBUG   [U=1821,P=10932]   cleanup_fd()                  Close file descriptor 5
DEBUG   [U=1821,P=10932]   cleanup_fd()                  Close file descriptor 6
DEBUG   [U=1821,P=10932]   init()                        Set child signal mask
DEBUG   [U=1821,P=10932]   init()                        Create socketpair for master communication channel
DEBUG   [U=1821,P=10932]   init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=1821,P=10932]   user_namespace_init()         Create user namespace
VERBOSE [U=1821,P=10932]   pid_namespace_init()          Create pid namespace
VERBOSE [U=1821,P=10932]   init()                        Spawn master process
VERBOSE [U=1821,P=10932]   priv_escalate()               Get root privileges
DEBUG   [U=0,P=10932]      setup_userns_mappings()       Write allow to setgroups file
DEBUG   [U=0,P=10932]      setup_userns_mappings()       Write to GID map
DEBUG   [U=0,P=10932]      setup_userns_mappings()       Write to UID map
DEBUG   [U=0,P=1]          set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=10932]      set_master_privileges()       Set master privileges
DEBUG   [U=0,P=10932]      apply_privileges()            Effective capabilities:   0x00000000000000c0
DEBUG   [U=0,P=10932]      apply_privileges()            Permitted capabilities:   0x0000003fffffffff
DEBUG   [U=0,P=10932]      apply_privileges()            Bounding capabilities:    0x0000003fffffffff
DEBUG   [U=0,P=10932]      apply_privileges()            Inheritable capabilities: 0x0000003fffffffff
DEBUG   [U=0,P=10932]      apply_privileges()            Ambient capabilities:     0x0000000000000000
DEBUG   [U=0,P=10932]      apply_privileges()            Set user ID to 1821
VERBOSE [U=0,P=1]          create_namespace()            Create mount namespace
DEBUG   [U=0,P=2]          set_rpc_privileges()          Set RPC privileges
DEBUG   [U=0,P=2]          apply_privileges()            Effective capabilities:   0x0000000000200000
DEBUG   [U=0,P=2]          apply_privileges()            Permitted capabilities:   0x0000003fffffffff
DEBUG   [U=0,P=2]          apply_privileges()            Bounding capabilities:    0x0000000008204000
DEBUG   [U=0,P=2]          apply_privileges()            Inheritable capabilities: 0x0000000000000000
DEBUG   [U=0,P=2]          apply_privileges()            Ambient capabilities:     0x0000000000000000
DEBUG   [U=0,P=2]          apply_privileges()            Set user ID to 0
DEBUG   [U=0,P=2]          set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=2]          init()                        Spawn RPC server
DEBUG   [U=1821,P=10932]   startup()                     fakeroot runtime engine selected
VERBOSE [U=1821,P=10932]   startup()                     Execute master process
DEBUG   [U=0,P=2]          startup()                     fakeroot runtime engine selected
VERBOSE [U=0,P=2]          startup()                     Serve RPC requests
VERBOSE [U=0,P=1]          wait_child()                  rpc server exited with status 0
DEBUG   [U=0,P=1]          init()                        Set container privileges
DEBUG   [U=0,P=1]          apply_privileges()            Effective capabilities:   0x0000003fffffffff
DEBUG   [U=0,P=1]          apply_privileges()            Permitted capabilities:   0x0000003fffffffff
DEBUG   [U=0,P=1]          apply_privileges()            Bounding capabilities:    0x0000003fffffffff
DEBUG   [U=0,P=1]          apply_privileges()            Inheritable capabilities: 0x0000003fffffffff
DEBUG   [U=0,P=1]          apply_privileges()            Ambient capabilities:     0x0000003fffffffff
DEBUG   [U=0,P=1]          apply_privileges()            Set main group ID to 0
DEBUG   [U=0,P=1]          apply_privileges()            Set 1 additional group IDs
DEBUG   [U=0,P=1]          apply_privileges()            Set user ID to 0
DEBUG   [U=0,P=1]          set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=1]          startup()                     fakeroot runtime engine selected
VERBOSE [U=0,P=1]          startup()                     Execute stage 2
DEBUG   [U=0,P=1]          StageTwo()                    Entering stage 2
DEBUG   [U=0,P=1]          persistentPreRun()            Singularity version: 3.6.4
DEBUG   [U=0,P=1]          persistentPreRun()            Parsing configuration file /usr/local/etc/singularity/singularity.conf
DEBUG   [U=0,P=1]          handleConfDir()               /root/.singularity already exists. Not creating.
DEBUG   [U=0,P=1]          setValue()                    Updated flag 'tmpdir' value to: /tmp
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache/library
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache/oci-tmp
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache/shub
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache/oras
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /nobackup/sheistan/.singularity/cache/cache/net
DEBUG   [U=0,P=1]          Init()                        Image format detection
DEBUG   [U=0,P=1]          Init()                        Check for sandbox image format
DEBUG   [U=0,P=1]          Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=1]          Init()                        Check for sif image format
DEBUG   [U=0,P=1]          Init()                        sif format initializer returned: can't read first 2048 bytes: <nil>
DEBUG   [U=0,P=1]          Init()                        Check for squashfs image format
DEBUG   [U=0,P=1]          Init()                        squashfs format initializer returned: can't read first 2048 bytes: <nil>
DEBUG   [U=0,P=1]          Init()                        Check for ext3 image format
DEBUG   [U=0,P=1]          Init()                        ext3 format initializer returned: can't read first 2048 bytes: <nil>
DEBUG   [U=0,P=1]          newBundle()                   Created temporary directory "/tmp/bundle-temp-763287638" for the bundle
DEBUG   [U=0,P=1]          newBundle()                   Created directory "/tmp/build-temp-153812499/rootfs" for the bundle
DEBUG   [U=0,P=1]          ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=0,P=1]          ensureGzipComp()              Gzip compression by default ensured
INFO    [U=0,P=1]          Full()                        Starting build...
DEBUG   [U=0,P=1]          Get()                         Getting container from Library
DEBUG   [U=0,P=1]          Get()                         LibraryURL: https://library.sylabs.io
... continues on fine.

**Comment by dtrudg** [comment]
This is expected:

> Amazon Elastic File System (Amazon EFS) provides a simple, scalable, fully managed elastic NFS file system

From our documentation:

https://sylabs.io/guides/3.6/admin-guide/installation.html#nfs

> NFS filesystems support overlay mounts as a lowerdir only, and do not support user-namespace (sub)uid/gid mapping.
> - Containers run from SIF files located on an NFS filesystem do not have restrictions.
> - You cannot use --overlay mynfsdir/ to overlay a directory onto a container when the overlay (upperdir) directory is on an NFS filesystem.
> - When using --fakeroot to build or run a container, your TMPDIR / SINGULARITY_TMPDIR should not be set to an NFS location.
> - You should not run a sandbox container with --fakeroot from an NFS location.

**Comment by steveheistand** [comment]
Interesting. did this used to work? on maybe v3.5?  I had really thought this was working a while ago.
Im fine with it not working now if that is the expected behavior. I will tweak things on my end to account for this.
thanks
steve

**Comment by dtrudg** [comment]
@steveheistand - `--fakeroot` builds have never reliably worked on NFS and other network filesystems, as the FS servers don't have any knowledge of the subuid/gid mapping that is employed in the user namespace on the host. They only see incoming uids/gids that they believe shouldn't have access to the user's files.

You may, however, have gotten lucky in the past if your build _only_ did things as (fake)root. root in the userns will map to the real user's own uid, so NFS etc. knows about that. As soon as it does something as a different user (e.g. `apt` tries to create some files as `wwwdata` or similar) you'll hit problems.

Changes to the build process do mean that above you hit the underlying cause earlier now, but we never really considered it to be working or supported before. It just happened to work for a very limited number of builds.

**Comment by dtrudg** [comment]
Noting here for additional context, in case others come across this issue, that this is a general issue for rootless builders / runtimes. Unfortunately it's not something we can really work around and it's related to the interaction between local kernel and remote filesystems.

 e.g. for buildah there is the troubleshooting note: https://github.com/containers/buildah/blob/master/troubleshooting.md#5-rootless-buildah-bud-fails-eperm-on-nfs

**Comment by steveheistand** [comment]
thanks for the info.
Im happy with closing the issue.
