### ISSUE TITLE
How to properly create a recipe for building a container?

### ISSUE THREAD

**Issue by bahadirbasaran** [apptainer/singularity#5726]
Hi!

I am a super rookie in Singularity and currently lost in the documentation. I have to work on a cluster to which I do not have sudo access, as you may guess. They obliged me to create a Singularity Container image, to pass it into the cluster and to use it in this way. Inside this container, I need to install some frameworks, libraries such as PyTorch, NumPy, libboost-all-dev and etc.

The cluster: CentOS 7.6 OpenHPC 1.3.8.1
My system: Ubuntu 20.04

Can you help me to create a Singularity Recipe in terms of the information above? I am terribly lost right now.

**Comment by dtrudg** [comment]
Please use the mailing list/google group and/or slack channel for these types of questions about using Singularity. They will be seen by a broader audience there, and the request is not really an issue or feature request in the singularity code, which is the main purpose of issue tracking here.

Thank you.

Join the HPCng slack (#singularity channel) - https://join.slack.com/t/hpcng/shared_invite/zt-gy0st6mt-ijgUaSvfdeEOhfXXfIstrQ

Google Group/Mailing list - https://groups.google.com/a/lbl.gov/g/singularity

**Comment by bahadirbasaran** [comment]
I’ve thought there wouldn’t be a problem to ask since there is a “question” tag. Thank you for leading me to the proper way!

**Comment by dtrudg** [comment]
@bahadirbasaran It's not a big problem - most of the things with `question` labels are more specific to a certain function of singularity itself, and we just generally want to guide people with broader usage questions to places where there are more community users looking, who can provide advice.

At some point we will update our issue templates to point things out better. Sorry for any misunderstanding.

**Comment by bahadirbasaran** [comment]
@dctrud You are totally right. I am switching to the Slack group to ask my question. As you've said, it is better in this way. Again, thank you again for guiding me.
