### ISSUE TITLE
Question: how to check and change the working directory while doing singularity exec ...?

### ISSUE THREAD

**Issue by Danissss** [apptainer/singularity#5730]
### Version of Singularity:
What version of Singularity are you using? Run:

```
$ singularity version
singularity version 3.3.0-rc.1.658.g7427b73f1.dirty
```

### Command-line output in a code block
```
singularity exec singluarity_con_latest.sif pwd
```
### Expected behavior

```
/singluarity_con
```

It should give me the current working directory inside the container.

### Actual behavior

```
/Users/danis/Desktop/singularity_con/web
```
It gives me the current working directory of my host.

### What OS/distro are you running

```
MacOS Catalina 10.15.7
```

### How did you install Singularity
Install through this link: https://sylabs.io/singularity-desktop-macos/

If I need to change working directory, how do I do it? 

Thanks!

**Comment by jmstover** [comment]
```
$ singularity exec singluarity_con_latest.sif pwd
/Users/danis/Desktop/singularity_con/web
```

The output you're getting looks correct. Because we're dealing with a couple layers what happens is that we take our working directory on the Mac host and that gets passed to the hypervisor as the Working Directory.  For example, I would get... 

```
Jasons-MacBook-Pro:~ jason$ pwd
/Users/jason
Jasons-MacBook-Pro:~ jason$ singularity exec ~/lolcow.sif pwd
/Users/jason
Jasons-MacBook-Pro:~ jason$ cd /tmp
Jasons-MacBook-Pro:tmp jason$ singularity exec ~/lolcow.sif pwd
/tmp
```

In the container runscript, you can change directories if you need to, use `exec` to run a script, etc... But by default for `exec` and `shell` it's going to just pass what the host working directory is for the working directory to start in.

**Comment by Danissss** [comment]
Hi @jmstover, thanks for the help.

Is runscript is same as `*.def` script?
```
Bootstrap: docker
Registry: http://localhost:5000
Namespace:
From: singularity_con:latest

%runscript
    cd /my_desired_directory
    bundle exec rake task:task
```

I think MacOS doesn't allow build the singularity from `*.def`.
```
FATAL:   Only remote builds are supported on this platform
```

I guess I need to build it on other system.

Is that possible to run exec to change the directory or even just check directory?

```
singularity exec singluarity_con_latest.sif ... (some magic command to run pwd inside container)
```

Thank you!

**Comment by jmstover** [comment]
The *.def file looks about right for the `%runscript` section. And yeah, on Mac's it really limited on what you can do.

The easiest thing would be to write a small script that was like (and chmod 755 it):

```
#!/bin/sh

cd /my_desired_directory
bundle exec rake task:task
```

Then run:   `singularity exec singularity_con_latest.sif ~/my_script.sh`

The `%runscript` section would be executed if you were to do:

`singularity run singularity_con_latest.sif`

**Comment by Danissss** [comment]
Thank you
The script works
