### ISSUE TITLE
Failed to upload artifact to insecure registry

### ISSUE THREAD

**Issue by dioguerra** [apptainer/singularity#5734]
### INFO

```
$ singularity version
3.7.0
```

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### PROBLEM

I switched singularity version to 3.7.0 because it had the extra 'insecure' parameter that promissed to support  self signed certificates. But this didnt work.
https://sylabs.io/guides/3.7/user-guide/cli/singularity_remote_login.html
To authenticate i did:

```
$ singularity remote login --insecure --username dtomasgu --password REDACTED  docker://registry-staging.domain.foo
INFO:    Token stored in /home/dtomasgu/.singularity/remote.yaml

$ cat /home/dtomasgu/.singularity/remote.yaml
Active: SylabsCloud
Remotes:
  SylabsCloud:
    URI: cloud.sylabs.io
    System: true
    Exclusive: false
Credentials:
- URI: oras://registry-staging.domain.foo
  Insecure: true
```
but then when pushing the image, it still complains and does not work:

```
$singularity push alpine_latest.sif oras://registry-staging.domain.foo/dtomasgu/alpine:latest
FATAL:   Unable to push image to oci registry: unable to push: failed to do request: Head "https://registry-staging.domain.foo/v2/dtomasgu/alpine/blobs/sha256:252b263fa3bab01d0c49c1b20e11fc58494b67c23b246d3f3cdd4f8c0d3ef47e": x509: certificate signed by unknown authority
```

### How did you install Singularity

Downloaded the tarball and installed with
`./mconfig &&     make -C ./builddir &&     sudo make -C ./builddir install`

**Comment by dtrudg** [comment]
@cclerget - are you able to advise on this?

**Comment by malkam03** [comment]
I'm getting the same issue here. Any news on this @dtrudg, @cclerget?

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by middlestone** [comment]
I'm getting this issue too using 3.8.7 @dtrudg @cclerget

**Comment by DrDaveD** [comment]
This repository is no longer active.  If `singularity --version` says singularity-ce, then please open a new issue at https://github.com/sylabs/singularity, otherwise please open a new issue at https://github.com/apptainer/apptainer.
