### ISSUE TITLE
Ways of setting default CPU/memory limitation on containers?

### ISSUE THREAD

**Issue by rogerwwww** [apptainer/singularity#5743]
### Version of Singularity:
```
3.5.2
```

### Expected behavior

I am a cluster admin and I would like to limit the resources (CPU/memory) a user can consume when running singularity containers.  I am expecting a way of enforcing CPU/memory limits for all containers by default.

### Actual behavior

However, [the instructions](https://sylabs.io/guides/3.5/admin-guide/configfiles.html#cgroups-toml) of setting ``cgroups.toml`` seems to only work with containers started by ``root`` and only work with ``--apply-cgroups`` argument. I am expecting a way of enforcing CPU/memory limits for all users without explicitly setting ``--apply-cgroups``.

### What OS/distro are you running

```
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

### How did you install Singularity

Installed from source

**Comment by dtrudg** [comment]
> I am expecting a way of enforcing CPU/memory limits for all users without explicitly setting --apply-cgroups.

This requirement is something that would usually be enforced at a higher level on a cluster, by enforcing cgroups settings on the system or in a batch scheduler. The justification for this approach is that running an application in a Singularity container is generally not different that running any other process to which generic limits should apply on the system, outside of a container.

Singularity does not currently support enforcing a default admin defined cgroups configuration for user-run containers. This would be technically possible in the setuid mode of execution, but it's not currently implemented, and is not a current goal. If it is a popular feature request that others are interested in it might be considered, and PR contributions for consideration are always welcome to the open-source project.

**Comment by rogerwwww** [comment]
Got it. Thanks a lot for your suggestions!
