### ISSUE TITLE
namespace disabled

### ISSUE THREAD

**Issue by masen1991** [apptainer/singularity#5748]
### Version of Singularity:

```
-bash-4.2$ singularity version
3.7.0


```

### Expected behavior

singularity run --userns ubuntu_latest.sif

### Actual behavior

INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting ubuntu_latest.sif: root filesystem extraction failed: extract command failed: ERROR  : Failed to create user namespace: user namespace disabled
: exit status 1

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


```

### How did you install Singularity

source

i see https://github.com/hpcng/singularity/issues/5240,but i don't know how to change .
so ,do i neet to be root to change namespaces? do any change in /etc/sysctl.conf file may cause any problem to the service?
as i am  still not a root ,so do i must contact admin to make this chang? can you tell some detail to enable namespaces?
especially is it a danger move to the system?because maybe i need to convince the Administor to help me to enable namespaces~~~

**Comment by YichaoOU** [comment]
is it solved?
