### ISSUE TITLE
Conda within singularity and problem with .bashrc

### ISSUE THREAD

**Issue by rahul-yadav-supra** [apptainer/singularity#5752]
### Version of Singularity:

**Singularity Version = 2.6.1**

What version of Singularity are you using? Run:

###### Currently I am using the singularity 2.6.1 version.</br></br>
```
$ singularity version

```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

#### I am using Ubuntu for creating my container that is being pulled from docker hub (_*ubuntu:18.04*_). 
```
$ cat /etc/os-release


```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

```
git clone https://github.com/singularityware/singularity.git
cd singularity
./autogen.sh
./configure --prefix=/usr/local
make
sudo make install

```

**Comment by dtrudg** [comment]
Closing this issue as it is a usage question that has been posted for 90 days and is not active.

For usage questions you are encouraged to use the Slack channel and/or mailing list which have a community of users present who will see and often kindly answer queries.

We close stale usage questions in order that the issues tracker can focus on problems that are bugs in Singularity, and feature requests.
