### ISSUE TITLE
Unclear warnings with Singularity 3.7.0 on image build

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#5754]
Trying to build an image with Singularity 3.7.0, I get some new, unintelligible warnings. Here's one with debugging on:
```
WARNING [U=0,P=24424]      parseTokenSection()           etc/profile.d/05-helpful_env.sh /etc/profile.d/05-helpful_env.sh : [etc/profile.d/05-helpful_env.sh /etc/profile.d/05-helpful_env.sh]
```
However, the files are still being copied fine:
```
INFO    [U=0,P=24424]      copyFiles()                   Copying etc/profile.d/05-helpful_env.sh to /tmp/build-temp-204701940/rootfs/etc/profile.d/05-helpful_env.sh
```
My definition file contains:
```
%files
etc/profile.d/05-helpful_env.sh /etc/profile.d/05-helpful_env.sh
```

This warning seems to be generated here:
https://github.com/hpcng/singularity/blob/4c182a9dc8f9e9593fbd76c3925594a5618678eb/pkg/build/types/parser/deffile.go#L166

What does the warning try to warn about?

**Comment by dtrudg** [comment]
This appears to be some ad-hoc debugging code that should have been removed, but was missed in merge and review. Apologies.

**Comment by olifre** [comment]
Thanks for the explanation! Then at least I know there is no actual issue and am looking forward to 3.7.1 :+1: .

**Comment by olifre** [comment]
Thanks! :+1:
