### ISSUE TITLE
Couldn't determine user account information in slurm compute node

### ISSUE THREAD

**Issue by fMeow** [apptainer/singularity#5757]
### Version of Singularity:

```
$ singularity version
3.7.0-1.el8
```

### Behavior

I am setting up singularity to be used only on slurm compute node. 

When I try to run singularity with srun as a normal user, it always yields a complaint that userid is unknown.

```
$ srun singularity
WARNING: Could not lookup the current user's information: user: unknown userid 551
FATAL:   Couldn't determine user account information: user: unknown userid 551
```

I only set up users in the head node in slurm, and the slurm cluster is working without issue.

Is there anyway to get singularity working without syncing the /etc/passwd and /etc/group across all nodes?

### Steps to reproduce this behavior

Setup two nodes. One configured as slurm head node and all the users and groups are created here. The other as compute node, and with only system related user like munge or slurm.

Use srun to get shell from the compute node, and run singularity:

```
$ srun  --pty bash

bash-4.4$ singularity
WARNING: Could not lookup the current user's information: user: unknown userid 551
FATAL:   Couldn't determine user account information: user: unknown userid 551
bash-4.4$ whoami
whoami: cannot find name for user ID 551
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

### How did you install Singularity

By centos package manager: `yum install singularity`.

**Comment by dtrudg** [comment]
Hello @fMeow - Singularity needs to retrieve user information such as the home directory, full group membership etc. The error you are getting shows that this is not possible on the node where Singularity is running. If `whoami` does not work, then Singularity will not work. The node configuration will need to be modified so that the user information for UID `551` can be retrieved on that node.
