### ISSUE TITLE
FATAL:   permission denied

### ISSUE THREAD

**Issue by mapsacosta** [apptainer/singularity#5767]
### Version of Singularity:

What version of Singularity are you using?:

```
Singularity version: 3.7.0

```

### Expected behavior

Container would start normally

### Actual behavior

Container would not start claiming a FATAL error on Stage two, permission denied (No details on why/where does the "Permission denied" comes from so, no clue how to debug this.:

```
VERBOSE: Unprivileged installation: using user namespace
VERBOSE: Setting HOME=XYZ
VERBOSE: Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VERBOSE: User namespace requested, convert image Some_image.sif to sandbox
INFO:    Converting SIF file to temporary sandbox...
VERBOSE: Set messagelevel to: 4
VERBOSE: Starter initialization
VERBOSE: Check if we are running as setuid
VERBOSE: Spawn stage 1
VERBOSE: Execute stage 1
VERBOSE: stage 1 exited with status 0
VERBOSE: Create user namespace
VERBOSE: Create user namespace
VERBOSE: Create pid namespace
VERBOSE: Spawn master process
VERBOSE: Create ipc namespace
VERBOSE: Create mount namespace
VERBOSE: Entering in mount namespace
VERBOSE: Create mount namespace
VERBOSE: Spawn RPC server
VERBOSE: Execute master process
VERBOSE: Default mount: /proc:/proc
VERBOSE: Default mount: /sys:/sys
VERBOSE: Default mount: /dev:/dev
VERBOSE: Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE: Found 'bind path' = /etc/hosts, /etc/hosts
VERBOSE: Default mount: /tmp:/tmp
VERBOSE: Default mount: /var/tmp:/var/tmp
VERBOSE: Default mount: /etc/resolv.conf:/etc/resolv.conf
VERBOSE: Serve RPC requests
VERBOSE: Checking for template passwd file: ********/singularity/x86_64/3.7.0/var/singularity/mnt/session/rootfs/etc/passwd
VERBOSE: Creating passwd content
VERBOSE: Creating template passwd file and appending user data: *********/singularity/x86_64/3.7.0/var/singularity/mnt/session/rootfs/etc/passwd
VERBOSE: Default mount: /etc/passwd:/etc/passwd
VERBOSE: Checking for template group file: *********/singularity/x86_64/3.7.0/var/singularity/mnt/session/rootfs/etc/group
VERBOSE: Creating group content
VERBOSE: Default mount: /etc/group:/etc/group
VERBOSE: ****/job_area/14661 found within container
VERBOSE: rpc server exited with status 0
VERBOSE: Execute stage 2
FATAL:   permission denied
VERBOSE: Removing image tempDir /tmp/rootfs-320821706
INFO:    Cleaning up image...
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
This seems to be a very specific case. Image is located in Lustre shared storage. The singularity exec command runs inside an HPC worker node, mounts a subdir on the same lustre storage and other local directories (all owned by the same uid/gid in the container)

### What OS/distro are you running

```
LSB Version:	n/a
Distributor ID:	SUSE
Description:	SUSE Linux Enterprise Server 15 SP1
Release:	15.1
Codename:	n/a

```

### How did you install Singularity
Not a sysadmin on this system

**Comment by dtrudg** [comment]
Please provide the full debug level output with the `-d` flag to the singularity command, and give the exact full `singularity ...` command you are using. Also given the specific case is related to lustre mounts and combinations of binds the output of `cat /proc/self/mountinfo` on the HPC node would also be useful.

If you are censoring paths with `*******` we will need to see enough of the path that it's clear what filesystem each path lies on.

**Comment by mapsacosta** [comment]
This is the full command, and I've attached debug output with the right paths.

```singularity exec --pid --ipc --contain --env EXEC_DIR=${EXEC_DIR} --bind /etc/hosts --bind /projects/HighLumin --bind /cvmfs --bind ${EXEC_DIR} --home ${BASE} /lus/[..]/shared_containers/worker_chirp_mn.sif ./launcher.py
```
[fulldebug.txt](https://github.com/hpcng/singularity/files/5716826/fulldebug.txt)

Thanks!

**Comment by dtrudg** [comment]
@mapsacosta - did you find a solution? this was closed as I was looking at the debug information that was removed.

**Comment by marc-rigter** [comment]
I'm having the same issue as this with Singularity 3.9. Any updates on how to resolve this?

DEBUG   [U=0,P=93322]      persistentPreRun()            Singularity version: 3.9.1+72-ga7f5e3aa7
DEBUG   [U=0,P=93322]      persistentPreRun()            Parsing configuration file /usr/local/etc/singularity/singularity.conf
DEBUG   [U=0,P=93322]      handleConfDir()               /root/.singularity already exists. Not creating.
DEBUG   [U=0,P=93322]      execStarter()                 Saving umask 0022 for propagation into container
DEBUG   [U=0,P=93322]      execStarter()                 Checking for encrypted system partition
DEBUG   [U=0,P=93322]      Init()                        Image format detection
DEBUG   [U=0,P=93322]      Init()                        Check for sandbox image format
DEBUG   [U=0,P=93322]      Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=93322]      Init()                        Check for sif image format
DEBUG   [U=0,P=93322]      Init()                        sif image format detected
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding COLORTERM environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding LANGUAGE environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding XAUTHORITY environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding LANG environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding LS_COLORS environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding TERM environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding DISPLAY environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding MAIL environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding LOGNAME environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding USER environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding SHELL environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding SUDO_COMMAND environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding SUDO_USER environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding SUDO_UID environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding SUDO_GID environment variable
DEBUG   [U=0,P=93322]      SetContainerEnv()             Forwarding USER_PATH environment variable
VERBOSE [U=0,P=93322]      SetContainerEnv()             Setting HOME=/root
VERBOSE [U=0,P=93322]      SetContainerEnv()             Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG   [U=0,P=93322]      init()                        Use starter binary /usr/local/libexec/singularity/bin/starter
DEBUG   [U=0,P=93322]      Exec()                        Setting GOGC=off for starter
VERBOSE [U=0,P=93322]      print()                       Set messagelevel to: 5
VERBOSE [U=0,P=93322]      init()                        Starter initialization
DEBUG   [U=0,P=93322]      load_overlay_module()         Trying to load overlay kernel module
DEBUG   [U=0,P=93322]      load_overlay_module()         Overlay seems supported by the kernel
VERBOSE [U=0,P=93322]      is_suid()                     Check if we are running as setuid
DEBUG   [U=0,P=93322]      read_engine_config()          Read engine configuration
DEBUG   [U=0,P=93322]      cleanenv()                    Clearing env var LOAD_OVERLAY_MODULE=1
DEBUG   [U=0,P=93322]      cleanenv()                    Keeping env var SINGULARITY_MESSAGELEVEL=5
DEBUG   [U=0,P=93322]      cleanenv()                    Clearing env var ENGINE_CONFIG1={"engineName":"singularity","containerID":"","engineConfig":{"jsonConfig":{"bindpath":[{"source":"/home/marcrigter/github/mopo","destination":"/home/mopo","options":null}],"unixSocketPair":[0,0],"image":"/home/marcrigter/github/mopo/singularity/mopo.sif","homedir":"/root","homeDest":"/root","network":"bridge","cwd":"/home/marcrigter/github/mopo/singularity","configurationFile":"/usr/local/etc/singularity/singularity.conf","restoreUmask":true,"umask":18},"ociCo(TRUNCATED...)DEBUG   [U=0,P=93322]      cleanenv()                    Clearing env var ENGINE_CONFIG_CHUNKS=1
DEBUG   [U=0,P=93322]      cleanenv()                    Keeping env var GOGC=off
DEBUG   [U=0,P=93322]      init()                        Wait completion of stage1
DEBUG   [U=0,P=93335]      set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=93335]      init()                        Spawn stage 1
DEBUG   [U=0,P=93335]      startup()                     singularity runtime engine selected
VERBOSE [U=0,P=93335]      startup()                     Execute stage 1
DEBUG   [U=0,P=93335]      StageOne()                    Entering stage 1
DEBUG   [U=0,P=93335]      prepareRootCaps()             Root full capabilities
DEBUG   [U=0,P=93335]      prepareAutofs()               Found "/proc/sys/fs/binfmt_misc" as autofs mount point
DEBUG   [U=0,P=93335]      prepareAutofs()               Could not keep file descriptor for user bind path /home/marcrigter/github/mopo: no mount point
DEBUG   [U=0,P=93335]      prepareAutofs()               Could not keep file descriptor for bind path /etc/localtime: no mount point
DEBUG   [U=0,P=93335]      prepareAutofs()               Could not keep file descriptor for bind path /etc/hosts: no mount point
DEBUG   [U=0,P=93335]      prepareAutofs()               Could not keep file descriptor for home directory /root: no mount point
DEBUG   [U=0,P=93335]      prepareAutofs()               Could not keep file descriptor for current working directory /home/marcrigter/github/mopo/singularity: no mount point
DEBUG   [U=0,P=93335]      Init()                        Image format detection
DEBUG   [U=0,P=93335]      Init()                        Check for sandbox image format
DEBUG   [U=0,P=93335]      Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=93335]      Init()                        Check for sif image format
DEBUG   [U=0,P=93335]      Init()                        sif image format detected
DEBUG   [U=0,P=93335]      setSessionLayer()             Overlay seems supported and allowed by kernel
DEBUG   [U=0,P=93335]      setSessionLayer()             Attempting to use overlayfs (enable overlay = try)
VERBOSE [U=0,P=93322]      wait_child()                  stage 1 exited with status 0
DEBUG   [U=0,P=93322]      cleanup_fd()                  Setting FD_CLOEXEC on starter fd 3
DEBUG   [U=0,P=93322]      cleanup_fd()                  Close file descriptor 4
DEBUG   [U=0,P=93322]      cleanup_fd()                  Close file descriptor 5
DEBUG   [U=0,P=93322]      cleanup_fd()                  Close file descriptor 6
DEBUG   [U=0,P=93322]      init()                        Set child signal mask
DEBUG   [U=0,P=93322]      init()                        Create socketpair for master communication channel
DEBUG   [U=0,P=93322]      init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=0,P=93322]      init()                        Spawn master process
DEBUG   [U=0,P=93341]      set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=93341]      create_namespace()            Create mount namespace
VERBOSE [U=0,P=93322]      enter_namespace()             Entering in mount namespace
DEBUG   [U=0,P=93322]      enter_namespace()             Opening namespace file ns/mnt
VERBOSE [U=0,P=93341]      create_namespace()            Create mount namespace
VERBOSE [U=0,P=93342]      init()                        Spawn RPC server
DEBUG   [U=0,P=93342]      startup()                     singularity runtime engine selected
VERBOSE [U=0,P=93342]      startup()                     Serve RPC requests
DEBUG   [U=0,P=93322]      startup()                     singularity runtime engine selected
VERBOSE [U=0,P=93322]      startup()                     Execute master process
DEBUG   [U=0,P=93322]      setupSessionLayout()          Using Layer system: overlay
DEBUG   [U=0,P=93322]      setupOverlayLayout()          Creating overlay SESSIONDIR layout
DEBUG   [U=0,P=93322]      addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=0,P=93322]      addRootfsMount()              Image type is 4096
DEBUG   [U=0,P=93322]      addRootfsMount()              Mounting block [squashfs] image: /home/marcrigter/github/mopo/singularity/mopo.sif
DEBUG   [U=0,P=93322]      addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=0,P=93322]      addKernelMount()              Adding proc to mount list
VERBOSE [U=0,P=93322]      addKernelMount()              Default mount: /proc:/proc
DEBUG   [U=0,P=93322]      addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=0,P=93322]      addKernelMount()              Adding sysfs to mount list
VERBOSE [U=0,P=93322]      addKernelMount()              Default mount: /sys:/sys
DEBUG   [U=0,P=93322]      addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=0,P=93322]      addDevMount()                 Adding dev to mount list
VERBOSE [U=0,P=93322]      addDevMount()                 Default mount: /dev:/dev
DEBUG   [U=0,P=93322]      addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=0,P=93322]      addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=0,P=93322]      addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=0,P=93322]      addHomeStagingDir()           Staging home directory (/root) at /usr/local/var/singularity/mnt/session/root
DEBUG   [U=0,P=93322]      addHomeMount()                Adding home directory mount [/usr/local/var/singularity/mnt/session/root:/root] to list using layer: overlay
DEBUG   [U=0,P=93322]      addUserbindsMount()           Adding /home/marcrigter/github/mopo to mount list
DEBUG   [U=0,P=93322]      addTmpMount()                 Checking for 'mount tmp' in configuration file
VERBOSE [U=0,P=93322]      addTmpMount()                 Default mount: /tmp:/tmp
VERBOSE [U=0,P=93322]      addTmpMount()                 Default mount: /var/tmp:/var/tmp
DEBUG   [U=0,P=93322]      addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=0,P=93322]      addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=0,P=93322]      addFilesMount()               Checking for 'user bind control' in configuration file
DEBUG   [U=0,P=93322]      addResolvConfMount()          Adding /etc/resolv.conf to mount list
VERBOSE [U=0,P=93322]      addResolvConfMount()          Default mount: /etc/resolv.conf:/etc/resolv.conf
DEBUG   [U=0,P=93322]      addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=0,P=93322]      create()                      Mount all
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting tmpfs to /usr/local/var/singularity/mnt/session
DEBUG   [U=0,P=93322]      mountImage()                  Mounting loop device /dev/loop20 to /usr/local/var/singularity/mnt/session/rootfs of type squashfs
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting overlay to /usr/local/var/singularity/mnt/session/final
DEBUG   [U=0,P=93322]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final
DEBUG   [U=0,P=93322]      setPropagationMount()         Set RPC mount propagation flag to SLAVE
VERBOSE [U=0,P=93322]      addIdentityMount()            Not updating passwd/group files, running as root!
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting /dev to /usr/local/var/singularity/mnt/session/final/dev
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting /etc/localtime to /usr/local/var/singularity/mnt/session/final/usr/share/zoneinfo/Etc/UTC
DEBUG   [U=0,P=93322]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/usr/share/zoneinfo/Etc/UTC
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting /etc/hosts to /usr/local/var/singularity/mnt/session/final/etc/hosts
DEBUG   [U=0,P=93322]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/etc/hosts
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting /proc to /usr/local/var/singularity/mnt/session/final/proc
DEBUG   [U=0,P=93322]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/proc
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting sysfs to /usr/local/var/singularity/mnt/session/final/sys
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting /root to /usr/local/var/singularity/mnt/session/root
DEBUG   [U=0,P=93322]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/root
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting /usr/local/var/singularity/mnt/session/root to /usr/local/var/singularity/mnt/session/final/root
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting /tmp to /usr/local/var/singularity/mnt/session/final/tmp
DEBUG   [U=0,P=93322]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/tmp
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting /var/tmp to /usr/local/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=0,P=93322]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting /usr/local/var/singularity/mnt/session/etc/resolv.conf to /usr/local/var/singularity/mnt/session/final/etc/resolv.conf
DEBUG   [U=0,P=93322]      mountGeneric()                Mounting /home/marcrigter/github/mopo to /usr/local/var/singularity/mnt/session/final/home/mopo
DEBUG   [U=0,P=93322]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/home/mopo
DEBUG   [U=0,P=93322]      addCwdMount()                 Using /home/marcrigter/github/mopo/singularity as current working directory
VERBOSE [U=0,P=93322]      addCwdMount()                 Not mounting CWD, /home/marcrigter/github/mopo/singularity doesn't exist within container
VERBOSE [U=0,P=93322]      addCwdMount()                 Not mounting CWD, while getting /home/marcrigter/github/mopo/singularity information: stat /usr/local/var/singularity/mnt/session/final/home/marcrigter/github/mopo/singularity: no such file or directory
DEBUG   [U=0,P=93322]      create()                      Chroot into /usr/local/var/singularity/mnt/session/final
DEBUG   [U=0,P=93342]      Chroot()                      Hold reference to host / directory
DEBUG   [U=0,P=93342]      Chroot()                      Called pivot_root on /usr/local/var/singularity/mnt/session/final
DEBUG   [U=0,P=93342]      Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=93342]      Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=93342]      Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=93342]      Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=0,P=93322]      create()                      Chdir into / to avoid errors
VERBOSE [U=0,P=93341]      wait_child()                  rpc server exited with status 0
DEBUG   [U=0,P=93341]      init()                        Set container privileges
DEBUG   [U=0,P=93341]      apply_privileges()            Effective capabilities:   0x0000003fffffffff
DEBUG   [U=0,P=93341]      apply_privileges()            Permitted capabilities:   0x0000003fffffffff
DEBUG   [U=0,P=93341]      apply_privileges()            Bounding capabilities:    0x0000003fffffffff
DEBUG   [U=0,P=93341]      apply_privileges()            Inheritable capabilities: 0x0000003fffffffff
DEBUG   [U=0,P=93341]      apply_privileges()            Ambient capabilities:     0x0000003fffffffff
DEBUG   [U=0,P=93341]      apply_privileges()            Set user ID to 0
DEBUG   [U=0,P=93341]      set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=93341]      startup()                     singularity runtime engine selected
VERBOSE [U=0,P=93341]      startup()                     Execute stage 2
DEBUG   [U=0,P=93341]      StageTwo()                    Entering stage 2
DEBUG   [U=0,P=93341]      StartProcess()                Setting umask in container to 0022
DEBUG   [U=0,P=93341]      sylogBuiltin()                Sourcing /.singularity.d/env/01-base.sh
DEBUG   [U=0,P=93341]      sylogBuiltin()                Sourcing /.singularity.d/env/10-docker2singularity.sh
DEBUG   [U=0,P=93341]      sylogBuiltin()                Sourcing /.singularity.d/env/90-environment.sh
DEBUG   [U=0,P=93341]      sylogBuiltin()                Sourcing /.singularity.d/env/91-environment.sh
DEBUG   [U=0,P=93341]      sylogBuiltin()                Sourcing /.singularity.d/env/94-appsbase.sh
DEBUG   [U=0,P=93341]      sylogBuiltin()                Sourcing /.singularity.d/env/95-apps.sh
DEBUG   [U=0,P=93341]      sylogBuiltin()                Sourcing /.singularity.d/env/99-base.sh
DEBUG   [U=0,P=93341]      sylogBuiltin()                Sourcing /.singularity.d/env/99-runtimevars.sh
DEBUG   [U=0,P=93341]      sylogBuiltin()                Running action command exec
FATAL   [U=0,P=93341]      StageTwo()                    permission denied
DEBUG   [U=0,P=93322]      startContainer()              stage 2 process reported an error, waiting status
DEBUG   [U=0,P=93322]      Master()                      Child exited with exit status 255

**Comment by DrDaveD** [comment]
Since you are using a 3.9 version it must be singularity-ce.  Please report the problem to https://github.com/sylabs/singularity.

**Comment by marc-rigter** [comment]
Hi Dave. I just tried version 3.7.3 and I get the same issue. Any suggestions? I'll also try reporting the problem to the other repo as suggested.

**Comment by marc-rigter** [comment]
The issue for me was that the script that I was trying to run was not executable. Fixed by running chmod +x

**Comment by diyism** [comment]
I got the same error with singularity 3.8.3:
```
$ sing shell --no-home --bind /root:/home/root --fakeroot --writable /content/alpine
FATAL:   container creation failed: hook function for tag sessiondir returns error: while mounting /usr/local/var/singularity/mnt/session/mountinfo to /proc/self/mountinfo: permission denied
```
