### ISSUE TITLE
Rejecting valid $TERM strings which contain a hyphen

### ISSUE THREAD

**Issue by akkornel** [apptainer/singularity#577]
It seems that the latest dev. Singularity is rejecting $TERM values which include a hyphen.

This is happening in the `development` branch.  I'm at commit 167857d5983aad17b84269666c8e48d255903d67.

Here's the verbose output from a bootstrap:

```
akkornel@blargh-yakkety-typical:~/workflow$ singularity -vv bootstrap image.img bootstrap.def
increasing verbosity level (3)
Exec'ing: /usr/local/libexec/singularity/cli/bootstrap.exec image.imgVERBOSE: Set messagelevel to: 3
VERBOSE: Checking input from environment: 'LANG'
VERBOSE: Obtained input from environment 'LANG' = 'en_US.UTF-8'
VERBOSE: Checking input from environment: 'TERM'
ERROR  : Illegal input character '-' in: 'TERM=xterm-256color'
ABORT  : Retval = 255
```

I don't think the details of the bootstrap script matters here, because it never gets to the point of parsing the bootstrap script.

Looking on a stock Ubuntu 16.10 system, I see 22 different terminal types which include a hyphen character:

```
akkornel@blargh-yakkety-typical:~/workflow$ ls /lib/terminfo/* | grep \-
cons25-debian
Eterm-color
mach-bold
mach-color
mach-gnu
mach-gnu-color
rxvt-basic
rxvt-m
rxvt-unicode
screen-256color
screen-256color-bce
screen-bce
screen-s
screen-w
xterm-256color
xterm-color
xterm-debian
xterm-mono
xterm-r5
xterm-r6
xterm-vt220
xterm-xfree86
```

In my case, the terminal type I'm using is `xterm-256color`.  This is the default that I got from an Ubuntu 16.10 Desktop installation.

**Comment by akkornel** [comment]
I've confirmed that this problem did not exist as of 68be6fec37ce05e0881b366ed89f1cc5cfbbfe16 (the merge of my branch a while ago).  So, this is a regression.

I've done a `git bisect` between 167857d5983aad17b84269666c8e48d255903d67 (the current head of the `development` branch) and 68be6fec37ce05e0881b366ed89f1cc5cfbbfe16 has narrowed things down to commit 0b697a3c6a41cbf1e42a048f9846ca0b97348c61.

If I understand the code correctly, `$TERM` is now being used in C code, but without allowing the hyphen character?

**Comment by vsoch** [comment]
This looks like a quick fix - @gmkurtzer manages the C code so he will be able to look at it when he's back at the computer. For now, try using a different. `$TERM`.

**Comment by akkornel** [comment]
@vsoch I just submitted a pull request that appears to fix this issue for me!

**Comment by vsoch** [comment]
awesome thanks @akkornel !

**Comment by gmkurtzer** [comment]
Just merged, thanks @akkornel!
