### ISSUE TITLE
PATH breaks because of com.nvidia.cuda.version

### ISSUE THREAD

**Issue by karkirowle** [apptainer/singularity#5772]
### Version of Singularity:

singularity version 3.6.4-1.el7

### Expected behavior

Python interpeter to open by python.

### Actual behavior

Upon start I have:
source: /.singularity.d/env/10-docker2singularity.sh:12:8: invalid var name

which is due to the lines in

export com.nvidia.cuda.version="${com.nvidia.cuda.version:-"10.1.243"}"
export com.nvidia.volumes.needed="${com.nvidia.volumes.needed:-"nvidia_driver"}"

I'm not sure what com.nvidia.cuda.version is, i.e $com.nvidia.cuda.version is not really appreciated by the CL, and I couldn't find anything about it after a quick Googling.

I will check with other images, but I'm pretty sure  /.singularity.d/env/10-docker2singularity.sh breaks it, which is not in the original docker image.

### Steps to reproduce this behavior

singularity pull --dir /tudelft.net/staff-bulk/ewi/insy/SpeechLab/bhalpern/singularity_images --disable-cache docker://jindongwang/espnet
(cp the produced tmp cache then to your loc)
singularity run -nv --home /tudelft.net/staff-bulk/ewi/insy/SpeechLab/bhalpern/singularity_home sbuild-tmp-cache-918238764
python --version

### What OS/distro are you running

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="OpenShift Enterprise"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"

### How did you install Singularity

Installed by sysadmin.

**Comment by dtrudg** [comment]
These names with periods `com.nvidia.cuda.version` are valid environment variable names, but not valid for the shell `export` command, as they are not valid shell identifiers.

Docker works as it sets the environment directly from Go code, while singularity uses an environment script where docker image env vars are set via `export` statements in the `10-docker2singularity.sh` shell script that is created during translation of the docker image to singularity form.

I don't think there is an easy workaround for this... we could change or delete the env var names, but this would likely mean the image doesn't work as expected. For now you would have to use a different docker image, or modify the existing one.

We'll have a think about it.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
