### ISSUE TITLE
Build image using 3.7.0 for 2.6.0

### ISSUE THREAD

**Issue by twoertwein** [apptainer/singularity#5776]
### Version of Singularity:

```
$ singularity version
singularity version 3.7.0-1.fc33
```

### Usage question

Is it possible to build a compressed image (without `--sandboxe`) that is run on singularity 2.6.0 (on centos) using singularity 3.7.0 (on fedora 33) to build the image? I tried

```
sudo singularity  build test.sqsh test.recipe
```

but the old singularity says it is an invalid container. I assumed that both version support squashfs?

My current approach is to have a singularity 3.x image with an old ubuntu that contains singularity 2.x. I then build a singularity image within the old ubuntu image.

**Comment by dtrudg** [comment]
There isn't a way built in to singularity 3.x to do this. Singularity 3.x can run version 2.x squashfs images , but when you build with 3.7.0 it is creating a SIF format image. The SIF format is not understood by Singularity 2.x

Your workaround of using 2.x where needed is appropriate, but note that Singularity 2.x is not supported and does not receive any bugfix or security updates. We would strongly advise moving to Singularity 3.x completely.
