### ISSUE TITLE
/usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by AndrewYRevell** [apptainer/singularity#5779]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```
Singularity version: 2.5.2-dist

### Expected behavior

Cannot pull docker container
![image](https://user-images.githubusercontent.com/43831513/103689259-0f2d9680-4f61-11eb-899a-72ae5a6da922.png)

![image](https://user-images.githubusercontent.com/43831513/103689444-5156d800-4f61-11eb-89d3-9980347ced35.png)

![image](https://user-images.githubusercontent.com/43831513/103689815-ce824d00-4f61-11eb-9fcf-21b1b9e3d754.png)

### Actual behavior

What actually happend? Why was it incorrect?

I get a python error

### What OS/distro are you running

```
$ cat /etc/os-release


```
![image](https://user-images.githubusercontent.com/43831513/103689300-1fde0c80-4f61-11eb-8b76-30a4c1a02969.png)

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

I follwed this: 
VERSION=2.5.2
wget https://github.com/singularityware/singularity/releases/download/$VERSION/singularity-$VERSION.tar.gz
tar xvf singularity-$VERSION.tar.gz
cd singularity-$VERSION
./configure --prefix=/usr/local
make
sudo make install

**Comment by dtrudg** [comment]
Singularity 2.x is no longer supported. It hasn't received any fixes for a long time, and was never tested on distributions as new as Ubuntu 20.04.

Please update to a current 3.7 version of Singularity. See the up-to-date docs:

https://sylabs.io/docs/
https://github.com/hpcng/singularity/blob/master/INSTALL.md
