### ISSUE TITLE
[feedback] should we save build log in metadata folder?

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#578]
If a container is a reproducible and historical thing, arguably we would want it to carry around it's history. This would also remove the burden of having to keep it somewhere from sys admins. We could have a metadata folder and different log files like:

```bash
/.singularity.d/logs
             01-build.log
             10-docker-[timestamp].log
```

where `01-build.log` is from the creation of the image / bootstrap, and then any subsequent imports are written with the prefix being the import type, followed by timestamp. Then a user could simply cat contents in this folder to see the history of a build, import, etc.

**Comment by gmkurtzer** [comment]
Hrmm.... I could throw the bootstrap deffile in there too actually!

**Comment by gmkurtzer** [comment]
I have included the bootstrap definition file in the container at `/.singularity.d/deffile`, but I'm not sure I like that name. Thoughts?

**Comment by vsoch** [comment]
@gmkurtzer please call it `Singularity`. This is the name that I've used for all across Singularity Hub, in many conversations / threads with users, in the paper, and with our docs.

**Comment by gmkurtzer** [comment]
I thought of that, but it might be confusing `/.singularity.d/Singularity` with `/singularity` and `/.singularity/runscript`. If you feel it won't be confusing, we can use that, or we can move it to `/.singularity.d/bootstrap/Singularity` or something?

**Comment by vsoch** [comment]
+1 on having bootstrap

**Comment by gmkurtzer** [comment]
You got it! :)

**Comment by ArangoGutierrez** [comment]
Closing thanks to PR
 - Update the deffile location in contianer (ref: #578)

**Comment by vsoch** [comment]
@ArangoGutierrez for all the issues that are (currently handled by) python relevant, it would be good to have a master list of ideas for the hackathon when the Go code is written!

**Comment by ArangoGutierrez** [comment]
Should we create an issue like...don't know
 - [Hackaton] List of ideas 

so people can put their ideas there .

**Comment by vsoch** [comment]
I would be specific like [Hackathon] GoLang Client
