### ISSUE TITLE
Pull images from Docker Hub through a caching mirror

### ISSUE THREAD

**Issue by adamnovak** [apptainer/singularity#5780]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3
```

### Expected behavior

When I run `singularity pull out.sif docker://ubuntu`, I want it to check an environment variable or system-level config file for a Docker Hub mirror registry to pull from instead of Docker Hub.

This is important because, with the new Docker Hub rate limits, it's necessary to consolidate and cache pulls from our CI infrastructure. We repeatedly run Singularity inside of empty, fresh containers, and we have to pull down all the images we need for every test.

### Actual behavior

Instead, as far as I can tell, there's no way to configure Singularity to use a pull-through caching mirror, and it always goes straight to Docker Hub and uses up my precious image pulls.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Singularity

I don't actually remember; mine ended up in `/opt/singularity/bin/singularity`.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by adamnovak** [comment]
This is still a thing we want for running Singularity on our infrastructure. Right now we're having to hackily wrap the commands and rewrite the image specs to point at our cache. If Singularity grew support for registry mirror configuration from its environment, we could remove that hackery from our code.

**Comment by adamnovak** [comment]
We still need this so we can remove our wrapper hack.

**Comment by kmuriki** [comment]
Pending issues from the old repo are copied to the new repo (https://github.com/apptainer/apptainer/issues/1389) and cleaned from the old, retired repo.
