### ISSUE TITLE
Can't get Singularity to use $SINGULARITY_TMPDIR

### ISSUE THREAD

**Issue by p-b-j** [apptainer/singularity#5791]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.7.0
```

### Expected behavior

Attempting to build a large image, so I need to set `$SINGULARITY_TMPDIR` to use something other than `/tmp` (via [this documentation](https://sylabs.io/guides/3.7/user-guide/build_env.html#temporary-folders)). I also attempted to set `$TMPDIR` based on other related posts that I had read.

```
$ mkdir singularity_tmpdir
$ SINGULARITY_TMPDIR=$PWD/singularity_tmpdir
$ TMPDIR=$PWD/singularity_tmpdir
# Tried both of the following commands
$ singularity build --fakeroot census_das.sif census_das.def
$ sudo singularity build census_das.sif census_das.def
```

Expected them to build successfully and to use the specified directory for temporary storage.

### Actual behavior

Still receive original error message of not having enough space on device, `/tmp` is still being used for temporary storage.
```
$ singularity build --fakeroot census_das.sif census_das.def
WARNING: census2020-das-e2e /das_decennial : [census2020-das-e2e /das_decennial]
WARNING: das_files /das_files : [das_files /das_files]
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob 7a0437f04f83 [--------------------------------------] 0.0b / 0.0b
Copying config 8dd57e171a done  
Writing manifest to image destination
Storing signatures
2021/01/11 12:06:06  info unpack layer: sha256:7a0437f04f83f084b7ed68ad9c4a4947e12fc4e1b006b38129bac89114ec3621
INFO:    Copying census2020-das-e2e to /tmp/build-temp-178614459/rootfs/das_decennial
INFO:    Copying das_files to /tmp/build-temp-178614459/rootfs/das_files
INFO:    Creating SIF file...
FATAL:   While performing build: while creating squashfs: create command failed: exit status 1: 
Write failed because No space left on device

FATAL ERROR:Failed
```

Full debug output [here](https://gist.github.com/p-b-j/768547076433333c5a344ee96942edc2).

Also tried to use the -E option as suggested by [this documentation](https://sylabs.io/guides/3.7/user-guide/build_env.html#temporary-folders) but the -E option no longer exists.

```
$ sudo singularity build -E census_das.sif census_das.def
Error for command "build": unknown shorthand flag: 'E' in -E
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
1) Attempt to build a singularity image from a definition file. This image should be larger than what can be stored in the default temporary storage location.
2) Attempt to change the default temporary storage location by modifying the environment variable `$SINGULARITY_TMPDIR`
3) Attempt to build the singularity image from the definition file again.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

From this AUR: https://aur.archlinux.org/packages/singularity-container/
```
$ git clone https://aur.archlinux.org/singularity-container.git
$ cd singularity-container
$ makepkg -si
```

**Comment by dtrudg** [comment]
The `-E` option is for sudo, i.e. `sudo -E singularity build ...` - it instructs sudo to use the environment variables that were set by the user outside of the sudo context.

If you are still having trouble when using `sudo -E` please show the output of `env | grep TMP` and the debug output from running with `sudo -E singularity -d ...`

**Comment by p-b-j** [comment]
Welp my brain definitely wasn't working on this one. Thanks for the -E clarification, turns out the other issue was related to not properly updating my environment with the variable (wasn't using `export` which `env | grep TMP` helped me diagnose). I'll close this issue, apologies for taking your time, thanks for the help!

Edit: works running with both `sudo -E` and `--fakeroot`.

**Comment by DavideBrex** [comment]
> The `-E` option is for sudo, i.e. `sudo -E singularity build ...` - it instructs sudo to use the environment variables that were set by the user outside of the sudo context.
> 
> If you are still having trouble when using `sudo -E` please show the output of `env | grep TMP` and the debug output from running with `sudo -E singularity -d ...`

I have encountered a similar issue as p-b-j.
Although I set  SINGULARITY_TMPDIR and I use the -E option singularity still uses my local machine RAM.
This is the output of `env | grep TMP` :

`SINGULARITY_TMPDIR=/media/davidebrex/data_storage/singularity_temp_folder/`

(singularity-ce version 3.8.0)

Thank you!
Davide

**Comment by benpietras** [comment]
Hi,

arch user also.

Needed

export SINGULARITY_TMPDIR=

not just

SINGULARITY_TMPDIR=

and 

sudo -E
