### ISSUE TITLE
an account pull docker image hangs on "Getting image source signature"

### ISSUE THREAD

**Issue by ryao-mdanderson** [apptainer/singularity#5792]
### Version of Singularity:

singularity version 3.5.2

### Expected behavior

What did you expect to see when you do...?
Today, as account ryao-mda logged in a redhat 7.4 server, then sudo /bin/su - ris_hpc_apps account, the following are executed as account ris_hpc_apps 

### Actual behavior
$ singularity cache clean --force
$ singularity --debug pull docker://ubuntu
DEBUG   [U=1944426582,P=29550]persistentPreRunE()           Singularity version: 3.5.2
DEBUG   [U=1944426582,P=29550]handleConfDir()               /home/ris_hpc_apps/.singularity already exists. Not creating.
DEBUG   [U=1944426582,P=29550]handleRemoteConf()            Ensuring file permission of 0600 on /home/ris_hpc_apps/.singularity/remote.yaml
DEBUG   [U=1944426582,P=29550]getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=1944426582,P=29550]initCacheDir()                Creating cache directory: /home/ris_hpc_apps/.singularity/cache/library
DEBUG   [U=1944426582,P=29550]updateCacheSubdir()           Caching directory set to /home/ris_hpc_apps/.singularity/cache/library
DEBUG   [U=1944426582,P=29550]initCacheDir()                Creating cache directory: /home/ris_hpc_apps/.singularity/cache/oci-tmp
DEBUG   [U=1944426582,P=29550]updateCacheSubdir()           Caching directory set to /home/ris_hpc_apps/.singularity/cache/oci-tmp
DEBUG   [U=1944426582,P=29550]initCacheDir()                Creating cache directory: /home/ris_hpc_apps/.singularity/cache/oci
DEBUG   [U=1944426582,P=29550]updateCacheSubdir()           Caching directory set to /home/ris_hpc_apps/.singularity/cache/oci
DEBUG   [U=1944426582,P=29550]initCacheDir()                Creating cache directory: /home/ris_hpc_apps/.singularity/cache/net
DEBUG   [U=1944426582,P=29550]updateCacheSubdir()           Caching directory set to /home/ris_hpc_apps/.singularity/cache/net
DEBUG   [U=1944426582,P=29550]initCacheDir()                Creating cache directory: /home/ris_hpc_apps/.singularity/cache/shub
DEBUG   [U=1944426582,P=29550]updateCacheSubdir()           Caching directory set to /home/ris_hpc_apps/.singularity/cache/shub
DEBUG   [U=1944426582,P=29550]initCacheDir()                Creating cache directory: /home/ris_hpc_apps/.singularity/cache/oras
DEBUG   [U=1944426582,P=29550]updateCacheSubdir()           Caching directory set to /home/ris_hpc_apps/.singularity/cache/oras
DEBUG   [U=1944426582,P=29550]parseURI()                    Parsing docker://ubuntu into reference
DEBUG   [U=1944426582,P=29550]initCacheDir()                Creating cache directory: /home/ris_hpc_apps/.singularity/cache/oci-tmp/c95a8e48bf88e9849f3e0f723d9f49fa12c5a00cfc6e60d2bc99d87555295e4c
DEBUG   [U=1944426582,P=29550]updateCacheSubdir()           Caching directory set to /home/ris_hpc_apps/.singularity/cache/oci-tmp/c95a8e48bf88e9849f3e0f723d9f49fa12c5a00cfc6e60d2bc99d87555295e4c
DEBUG   [U=1944426582,P=29550]updateCacheSubdir()           Caching directory set to /home/ris_hpc_apps/.singularity/cache/oci-tmp/c95a8e48bf88e9849f3e0f723d9f49fa12c5a00cfc6e60d2bc99d87555295e4c
INFO    [U=1944426582,P=29550]OciPull()                     Converting OCI blobs to SIF format
DEBUG   [U=1944426582,P=29550]newBundle()                   Created temporary directory "/tmp/bundle-temp-877166451" for the bundle
DEBUG   [U=1944426582,P=29550]newBundle()                   Created directory "/tmp/rootfs-2c760407-545a-11eb-a7eb-3ca82a14822c" for the bundle
DEBUG   [U=1944426582,P=29550]ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=1944426582,P=29550]ensureGzipComp()              Gzip compression by default ensured
INFO    [U=1944426582,P=29550]Full()                        Starting build...
DEBUG   [U=1944426582,P=29550]Get()                         Reference: ubuntu
Getting image source signatures

 it hangs on "Getting image source signatures".

However, as a regular user account, myself (i.e. as ryao), I can use the same command to pull the image successfully. 

### Steps to reproduce this behavior
$ singularity cache clean --force
$ singularity --debug pull docker://ubuntu

### What OS/distro are you running

RHEL 7.4

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
wget https://github.com/sylabs/singularity/releases/download/v3.5.2/singularity-3.5.2.tar.gz
used INSTALL.md inside tar ball, section Compiling Singularity

**Comment by dtrudg** [comment]
Do you have a proxy server in use (`env | grep -i proxy`) ? If so make sure proxy environment variables are set in the account that is not working.

**Comment by ryao-mdanderson** [comment]
Thank you for your reply! I don't have a proxy server in use. I think the problem is related to the account on the server, other accounts can do singularity pull docker://<image> without an issue. But why this account does not work, it is subtle.

**Comment by dtrudg** [comment]
Check also if you have anything configured in `$HOME/.docker` - singularity will honor any docker configuration / logins etc. there.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by soichih** [comment]
I am running into this issue also. Has anyone come up with a way to fix this?

```
$ singularity --debug exec -e docker://brainlife/freesurfer recon-all -v

DEBUG   [U=1589653,P=2989184]persistentPreRun()            Singularity version: 3.7.2
DEBUG   [U=1589653,P=2989184]persistentPreRun()            Parsing configuration file /N/soft/rhel8/singularity/3.7.2/etc/singularity/singularity.conf
DEBUG   [U=1589653,P=2989184]handleConfDir()               /N/u/brlife/Quartz/.singularity already exists. Not creating.
DEBUG   [U=1589653,P=2989184]setValue()                    Updated flag 'bind' value to: [/N/project/brainlife,/N/project/plab,/N/scratch/brlife,/N/slate/brlife]
DEBUG   [U=1589653,P=2989184]setValue()                    Updated flag 'docker-password' value to: gobrainlife
DEBUG   [U=1589653,P=2989184]setValue()                    Updated flag 'docker-username' value to: brainlife4
DEBUG   [U=1589653,P=2989184]parseURI()                    Parsing docker://brainlife/freesurfer into reference
INFO    [U=1589653,P=2989184]pull()                        Converting OCI blobs to SIF format
DEBUG   [U=1589653,P=2989184]newBundle()                   Created temporary directory "/tmp/bundle-temp-195468079" for the bundle
DEBUG   [U=1589653,P=2989184]newBundle()                   Created directory "/tmp/build-temp-447956240/rootfs" for the bundle
DEBUG   [U=1589653,P=2989184]ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=1589653,P=2989184]ensureGzipComp()              Gzip compression by default ensured
INFO    [U=1589653,P=2989184]Full()                        Starting build...
DEBUG   [U=1589653,P=2989184]Get()                         Reference: brainlife/freesurfer
Getting image source signatures
panic: invalid page type: 38: 10

goroutine 90 [running]:
go.etcd.io/bbolt.(*Cursor).search(0xc000287478, 0xc00047f8e0, 0x6, 0x8, 0x26)
	go.etcd.io/bbolt@v1.3.5/cursor.go:250 +0x345
go.etcd.io/bbolt.(*Cursor).seek(0xc000287478, 0xc00047f8e0, 0x6, 0x8, 0x10000c00047f8c0, 0xc0004d3000, 0x0, 0xc000287480, 0x55c54d272d2b, 0xd0, ...)
	go.etcd.io/bbolt@v1.3.5/cursor.go:159 +0x7f
go.etcd.io/bbolt.(*Bucket).CreateBucket(0xc000170500, 0xc00047f8e0, 0x6, 0x8, 0xc00047f8e0, 0x55c54de117c1, 0x6)
	go.etcd.io/bbolt@v1.3.5/bucket.go:167 +0xf6
go.etcd.io/bbolt.(*Bucket).CreateBucketIfNotExists(0xc000170500, 0xc00047f8e0, 0x6, 0x8, 0x6, 0x8, 0x0)
	go.etcd.io/bbolt@v1.3.5/bucket.go:201 +0x52
github.com/containers/image/v5/pkg/blobinfocache/boltdb.(*cache).RecordKnownLocation.func1(0xc00010e0e0, 0xc000392801, 0xc00010e0e0)
	github.com/containers/image/v5@v5.10.5/pkg/blobinfocache/boltdb/boltdb.go:262 +0x134
go.etcd.io/bbolt.(*DB).Update(0xc0003d2000, 0xc000287770, 0x0, 0x0)
	go.etcd.io/bbolt@v1.3.5/db.go:694 +0x93
github.com/containers/image/v5/pkg/blobinfocache/boltdb.(*cache).update(0xc000553840, 0xc000287770, 0x0, 0x0)
	github.com/containers/image/v5@v5.10.5/pkg/blobinfocache/boltdb/boltdb.go:148 +0x13c
github.com/containers/image/v5/pkg/blobinfocache/boltdb.(*cache).RecordKnownLocation(0xc000553840, 0x55c54e432160, 0x55c54eb0c6e8, 0xc0002a9020, 0x9, 0xc0002b5310, 0x47, 0xc000392880, 0x1e)
	github.com/containers/image/v5@v5.10.5/pkg/blobinfocache/boltdb/boltdb.go:257 +0xcf
github.com/containers/image/v5/docker.(*dockerImageSource).GetBlob(0xc0003c6cd0, 0x55c54e437138, 0xc000040130, 0xc0002b5310, 0x47, 0x47e9237, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/containers/image/v5@v5.10.5/docker/docker_image_src.go:295 +0x3b3
github.com/containers/image/v5/copy.(*imageCopier).copyLayer(0xc00024b7d0, 0x55c54e437138, 0xc000040130, 0xc0002b5310, 0x47, 0x47e9237, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/containers/image/v5@v5.10.5/copy/copy.go:1136 +0x1ca
github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func1(0x0, 0xc0002b5310, 0x47, 0x47e9237, 0x0, 0x0, 0x0, 0x0, 0xc0003a76c0, 0x31, ...)
	github.com/containers/image/v5@v5.10.5/copy/copy.go:848 +0x47a
created by github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func2
	github.com/containers/image/v5@v5.10.5/copy/copy.go:885 +0x24c

```

**Comment by DrDaveD** [comment]
@soichih It's not clear to me that's the same issue.  Is it still happening?  It doesn't happen for me.  I suggest making a new issue.

**Comment by DrDaveD** [comment]
Oh, and you reported the same issue before in #5329 and was given a fix.  The fix has also been added to the [documentation](https://apptainer.org/user-docs/master/build_env.html#boltdb-corruption-errors).  Thanks to @dtrudg to pointing this out to me.

**Comment by ryao-mdanderson** [comment]
@dtrudg Hello, I just realized that this ticket has been closed. I reviewed it and #5329, my issue is different from @DrDaveD had. My command is a regular singularity pull (use both 3.5.2 and 3.7.0), but stuck on "Getting image source signatures". There are no informative message after this line. I wonder if there is a similar ticket address this?  Thank you very much.

**Comment by DrDaveD** [comment]
If this issue is still happening please create a new one in https://github.com/apptainer/apptainer, referring back to this one.
