### ISSUE TITLE
Provide docker login credentials for bootstrap in definition file?

### ISSUE THREAD

**Issue by ast0815** [apptainer/singularity#5793]
### Version of Singularity:

```
$ singularity version
3.7.0-1.el7
```

### The issue

I think it should be possible to specify the docker login credentials for a docker bootstrap in the definition file directly, rather than by using the `--docker-login` command line argument or the respective environment variables.
My use case is that I want to build a container on Singularity Hub, but the docker registry providing the image I am basing my container on requires a login.
As far as I could find out, I cannot set environment variables for the Singularity Hub build.

I am looking for work arounds (e.g. start with a "scratch" bootstrap and somehow use a `%setup` script to pull the container from the docker registry, but so far I was not able to pull it off.

**Comment by dtrudg** [comment]
I think we are pretty strongly against having credentials added to a definition file. The risk of exposure is too great. Singularity stores the definition file used as metadata in the built image... then anyone would have access to your credentials...

```
$ singularity inspect -d lolcow_latest.sif
bootstrap: library
from: ubuntu:16.04

%environment
    export LC_ALL=C
    export PATH=/usr/games:$PATH

%runscript
    fortune | cowsay | lolcat

%post
    apt-get -y update
    apt-get -y install fortune cowsay lolcat
```

There needs to be a way to pass credentials to a builder, like Singularity Hub, by separate means. Most CI systems have the concept of secrets for this.
