### ISSUE TITLE
Update to centos 7.9 and beegfs 7.2 leads to node crash when running sandbox

### ISSUE THREAD

**Issue by mshaikh786** [apptainer/singularity#5794]
### Version of Singularity:
What version of Singularity are you using? Run:

```
$ singularity version
3.5.3
```

### Expected behavior

What did you expect to see when you do...?
When singularity container is run (or exec) from a sandbox directory located on NFS filesystem (/home of our HPC cluster), the container runs fine, with no issue. When the sandbox is located in a directory on beegfs, the whole node, along with all the processes, crash. 

### Actual behavior

What actually happend? Why was it incorrect?
On BeegFS a sandbox image fails to create a container. The node instantly crashes and needs to be rebooted. 

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
```
singularity build --sandbox deepvariant docker://google/deepvariant:latest
singularity exec deepvariant /opt/deepvariant/bin/run_deepvariant --help
```
The second command crash the compute node instantly.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


$ beegfs-ctl --help | grep Version
Version: 7.2

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
RPM

**Comment by dzieko** [comment]
With centos 7.7 and beegfs 7.1.5 it was working fine.
 
With centos 7.9 and beegfs 7.2 the machine locks up completely.
We will try to provide console traceback tomorrow.
Some details are below. 

```
# uname -r
3.10.0-1160.6.1.el7.x86_64

# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

# lscpu
[...]
Model name:            Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
[...]

```

**Comment by dzieko** [comment]
Console logs attached.

[console_logs.txt](https://github.com/hpcng/singularity/files/5836743/console_logs.txt)

**Comment by dtrudg** [comment]
> With centos 7.7 and beegfs 7.1.5 it was working fine.

> With centos 7.9 and beegfs 7.2 the machine locks up completely.
We will try to provide console traceback tomorrow.
Some details are below.

Please seek support from beegfs in the first instance, as the issue is something that has come up with a version change to beegfs and CentOS / the kernel. Nothing Singularity does should be able to crash a node through filesystem manipulation, to the best of my knowledge.

I'm unable to see the console logs - it delivers an HTML page with a link to a slack post in a workspace I cannot access.

**Comment by dzieko** [comment]
console log attached again.

[console_logs2.txt](https://github.com/hpcng/singularity/files/5837660/console_logs2.txt)

snippet for google search:

```
[2966930.713730] BUG: unable to handle kernel paging request at 0000000040850c00
[2966930.721195] IP: [<ffffffffc0551ab2>] ovl_cache_free+0x12/0x60 [overlay]
[2966930.728198] PGD 0
[2966930.730595] Oops: 0000 [#1] SMP
[2966930.734311] Modules linked in: overlay(T) beegfs(OE)

[2966930.863652] CPU: 1 PID: 151805 Comm: starter-suid Tainted: P           OE  ------------ T 3.10.0-1160.6.1.el7.x86_64 #1

[2966930.988302] Call Trace:
[2966930.991147]  [<ffffffffc0551db0>] ovl_dir_cache_free+0x20/0x30 [overlay]
[2966930.998245]  [<ffffffffc0548326>] ovl_destroy_inode+0x36/0x50 [overlay]
[2966931.005259]  [<ffffffff8266c0ab>] destroy_inode+0x3b/0x60

[2966931.220802] Kernel panic - not syncing: Fatal exception
[2966931.233475] Kernel Offset: 0x1400000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[2966931.294561] ------------[ cut here ]------------
[2966931.299582] WARNING: CPU: 1 PID: 151805 at arch/x86/kernel/smp.c:127 native_smp_send_reschedule+0x65/0x70

[2966931.439594] CPU: 1 PID: 151805 Comm: starter-suid Tainted: P      D    OE  ------------ T 3.10.0-1160.6.1.el7.x86_64 #1

```

**Comment by dtrudg** [comment]
> [2966930.713730] BUG: unable to handle kernel paging request at 0000000040850c00
> [2966930.721195] IP: [<ffffffffc0551ab2>] ovl_cache_free+0x12/0x60 [overlay]

It appears there is a bad interaction between BeeGFS and the kernel's overlay filesystem that Singularity uses. This does not appear to be a problem with Singularity itself.

The operations that Singularity has called should not be able to lead to a system crash.

This will need to be raised to BeeGFS support and / or your Linux vendor.
