### ISSUE TITLE
"Error copying image out of cache: copy_file_range: resource temporarily unavailable" with specific image

### ISSUE THREAD

**Issue by Shellfishgene** [apptainer/singularity#5796]
### Version of Singularity:

What version of Singularity are you using? 

```
3.6.4
```

What did you expect to see when you do...?
`singularity pull https://depot.galaxyproject.org/singularity/star:2.6.1d--0`
Pull an image.

What actually happend? Why was it incorrect?

There is below error.
```
$ singularity pull https://depot.galaxyproject.org/singularity/star:2.6.1d--0
INFO:    Downloading network image
8.9MiB / 8.9MiB [==============================================================================] 100 % 380.4 KiB/s 0s
FATAL:   While making image from oci registry: error copying image out of cache: could not copy file: write tmp-copy-689365014: copy_file_range: resource temporarily unavailable
```
This seems to be specific to this image, as others from the same source work fine. 
I tried clearing the cache before running `pull`, which does not help.

However using the `--disable-cache` option makes it work.

The image is downloaded to the `.singularity/cache/net/` directory as `8fb029aa7c5bf3762456a860f4159d755629183b5cb100b2b39c36d563b36b8e` and seems to work as expected.

The same issue occurs when getting a similar image from another source:
```
singularity pull docker://quay.io/biocontainers/star:2.7.7a--0
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
```
singularity pull https://depot.galaxyproject.org/singularity/star:2.6.1d--0
```

### What OS/distro are you running

```
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
```

### How did you install Singularity
Not sure, admins installed it.

**Comment by dtrudg** [comment]
What version of Go was used to build Singularity, and is your $HOME on NFS?

These are imporant to troubleshooting as there was a bug in early Go 1.15.1 with copy_file_range on NFS or older kernels.

**Comment by Shellfishgene** [comment]
Singularity was built in Go 1.15.2 and $HOME is on IBM Spectrum Scale (aka GPFS).
The problem does not appear with Singularity 3.5.2, same Go version and file system.

**Comment by dtrudg** [comment]
Can you provide information about the Spectrum Scale version, kernel version etc? I haven't been able to reproduce this on the parallel filesystems I have access to for testing.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
