### ISSUE TITLE
/.singularity.d/env/10-docker2singularity.sh: line 5: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by stevekm** [apptainer/singularity#5802]
I am getting a weird error message when I try to run this container with Singularity; https://dockstore.org/containers/registry.hub.docker.com/weischenfeldt/bric-embl_delly_workflow:2.0.2_ppcg?tab=info

Not sure if this is an issue with Singularity, or just with that container.

### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.3.0-dirty.el7.centos
```

### Expected behavior

No weird error messages

### Actual behavior

A weird error message is given.

### Steps to reproduce this behavior

You can see the error message here;

```
$ singularity exec docker://weischenfeldt/bric-embl_delly_workflow:2.0.2_ppcg /services/weischenfeldt_lab/software/delly/0.6.6/delly --help
/.singularity.d/env/10-docker2singularity.sh: line 5: syntax error near unexpected token `('
/.singularity.d/env/10-docker2singularity.sh: line 5: `export BASH_FUNC_module()=${BASH_FUNC_module():-"() { eval \\`/usr/bin/modulecmd bash \\$*\\`; }"}'
```

You can also see the error message plus contents of the file in question here;

```
$ singularity exec --cleanenv weischenfeldt.bric-embl_delly_workflow.2.0.2_ppcg.sif cat -n /.singularity.d/env/10-docker2singularity.sh
/.singularity.d/env/10-docker2singularity.sh: line 5: syntax error near unexpected token `('
/.singularity.d/env/10-docker2singularity.sh: line 5: `export BASH_FUNC_module()=${BASH_FUNC_module():-"() { eval \\`/usr/bin/modulecmd bash \\$*\\`; }"}'
     1  #!/bin/sh
     2  export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
     3  export MODULEPATH=${MODULEPATH:-"/services/weischenfeldt_lab/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles"}
     4  export MODULESHOME=${MODULESHOME:-"/usr/share/Modules"}
     5  export BASH_FUNC_module()=${BASH_FUNC_module():-"() { eval \\`/usr/bin/modulecmd bash \\$*\\`; }"}
     6  export IS_IN_DOCKER=${IS_IN_DOCKER:-"1"}

```

Maybe its using the wrong shell function syntax for `BASH_FUNC_module`??

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -srviop
Linux 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 GNU/Linux

```

### How did you install Singularity

I did not install it so I am not sure.

**Comment by dtrudg** [comment]
A base container Dockerfile contains this:

```
ENV BASH_FUNC_module() "() { eval `/usr/bin/modulecmd bash $*`; }"
```

https://bitbucket.org/weischenfeldt/computerome_weischenfeldt_docker/src/b9461731b33ee68779a8a49bffc29872620a6bea/Dockerfile#lines-82

This is an export of a bash function, not a 'standard' environment variable. Docker sets environment differently than Singularity. Singularity uses a shell to source the environment, and the bash function name is not valid for export in the shell.

This container will not be compatible with Singularity. A preferred approach would be to source the module command's setup script at container runtime, not to export the bash function directly.
