### ISSUE TITLE
Singularity in Docker without --privileged?

### ISSUE THREAD

**Issue by anderspitman** [apptainer/singularity#5806]
This is a general question not for any specific version.

I'm trying to run singularity containers inside a Docker container, but getting the error:

```
ERROR  : Failed to create user namespace: Operation not permitted
```

It works if I run docker with --privileged. However, I don't think that's an option on the target system.

Is there any way to run singularity in a less privileged mode that doesn't require namespaces? I'm primarily using singularity for packaging dependencies (kind of like a glorified AppImage), so I'm not too concerned about losing security or other features at the singularity level.

**Comment by rptaylor** [comment]
On CentOS7 you may find some progress by using sysctl to increase user.max_user_namespaces to a positive number.
On CentOS8 user namespaces are enabled by default and should work.  But either way I think additional issues will be encountered.

I would also like to figure out how to run singularity inside an unprivileged container (k8s pod).

**Comment by dtrudg** [comment]
Singularity either requires a privileged set-uid install, or a user namespace to operate. Mounts and mount namespace creation etc. cannot happen without one of these.

To run in docker you will need to permit user namespace creation.

**Comment by DrDaveD** [comment]
See point 3 in the [OSG instructions for unprivileged singularity](https://opensciencegrid.org/docs/worker-node/install-singularity/#enabling-unprivileged-singularity).  I copy it hear for the record:

If docker is being used to run jobs, the following options are recommended to allow unprivileged singularity to run (it does not need `--privileged` or any added capabilities):
```
--security-opt seccomp=unconfined --security-opt systempaths=unconfined
```

`--security-opt seccomp=unconfined` enables unshare to be called (which is needed to create namespaces), and `--security-opt systempaths=unconfined` allows /proc to be mounted in an unprivileged process namespace (as done by singularity exec -p). `--security-opt systempaths=unconfined` requires Docker 19.03 or later. The options are secure as long as the system administrator controls the images and does not allow user code to run as root, and are generally more secure than adding capabilities. If at this point no setuid programs needs to be run within the container, adding the following option will add security by preventing any privilege escalation (singularity uses the same feature on its containers):
```
--security-opt no-new-privileges
```

In addition, the following option is recommended for allowing unprivileged fuse mounts on kernels that support that (RHEL >= 7.8):
```
--device=/dev/fuse
```
