### ISSUE TITLE
Should we have a `list` command for image orchestration

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#581]
why don' t we put all the .img on one folder. and a command like 
``singularity list``  or ``singularity images``

For now it could be something really raw.

Putting all the .img on one folder by default, so when we do 
`` singularity create myimage.img ``

it goes to the default `$IMAGE_PATH` 

and a command 
``singularity images``

would be something like
`` ls -rthl $IMAGE_PATH``

Where we can see who own each image, creation date, size.

**Comment by vsoch** [comment]
How would you propose to implement this?

**Comment by ArangoGutierrez** [comment]
I think it could be set in the singularity.conf file

```bash
# CONTAINER_CREATE DIR: [STRING]
# DEFAULT: /var/lib/singularity/img/
# This path specifies the location to use when creating the container.
container_create dir = /var/lib/singularity/img/
```
Then

And a command 
``singularity images``

Would be something like e.g
`` ls -l /var/lib/singularity/img/``

Also CONTAINER_CREATE DIR can set to an nfs in order to configure a local registry.

**Comment by gmkurtzer** [comment]
We have the ability (in development branch) to limit the path to which containers can be executed, but not list from those paths. That wouldn't be so hard to add though, but I'm not sure yet that I am convinced. ;)

**Comment by vsoch** [comment]
This has been implemented for instances, so I'm going to close here. Also, for @ArangoGutierrez purpose you can use the singularity registry (sregistry) to serve and organize your images, and guess what, it has a list command too :)

https://singularityhub.github.io/sregistry/client.html#list
