### ISSUE TITLE
stale NFS file handle

### ISSUE THREAD

**Issue by soichih** [apptainer/singularity#5810]
Hello. 

I am using SingularityPRO version 3.5-4.el7 on UCSD Comet HPC cluster.

I *occastionally* run into the following error message.
```
[34mINFO:   [0m Converting OCI blobs to SIF format
[34mINFO:   [0m Starting build...
Getting image source signatures
Copying blob sha256:5667fdb72017d1fb364744ca1abf7b6f3bbe9c98c3786f294a461c2866db69ab
...
Copying blob sha256:79c3875b675d44a5150010d52fe69c8e6adbd350287881cb17392045977192e3
Copying config sha256:855ca8e3cb27b56f73bd879f8ebc5e702ca31885b95d97cfbbd5c680bdb33d9d
Writing manifest to image destination
Storing signatures
[31mFATAL:  [0m Unable to handle docker://brainlife/mcr:r2019a uri: unable to build: conveyor failed to get: Error writing blob: read /home/hayashis/.singularity/cache/oci/blobs/sha256/a246aede5303a36a2d9e31a2fa4bf1aed07845df360ef3fe4f54ac94db4b6094: stale NFS file handle
```

I am using comet's home directory to store `.singularity` directory (by default) which is using NFS mounted home volume

```
hayashis@comet-ln2:~ 1 df .
Filesystem                                      1K-blocks     Used   Available Use% Mounted on
comet-nfs-32-4:/export/nfs-32-4/home/hayashis 16598971520 58120064 16540851456   1% /home/hayashis
```

Is there any issue with singularity using NFS mounted home directory for .singularity? Should I switch to lustre file system (/oasis/scratch) maybe?

**Comment by dtrudg** [comment]
Hi @soichih 

> I am using SingularityPRO version 3.5-4.el7 

The comet administrators can raise a ticket with us via support@sylabs.io if there is an issue with SingularityPRO. This open-source project provides community support for the latest open-source version of Singularity.

**Comment by soichih** [comment]
Great. Thanks! I will forward this to help@xsede.org.
