### ISSUE TITLE
Singularity exec stops working when command line args are too long

### ISSUE THREAD

**Issue by stevekm** [apptainer/singularity#5815]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.3.0-dirty.el7.centos

```

### Expected behavior

It should not stop working

### Actual behavior

When the command line arguments used to start singularity become too large, weird errors start occuring.

We stumbled upon this due to using [Toil](https://github.com/DataBiosphere/toil) with Singularity on data analysis workflows that require thousands of input files in a single workflow step.

### Steps to reproduce this behavior

Here is an example of where I isolated and reproduced the behavior.

Setup:

- make a bunch of files in a directory and save a listing of all the files' full paths

```
mkdir input_dir_with_a_long_name
for i in $(seq 1 1 5000); do touch input_dir_with_a_long_name/$i; done
find input_dir_with_a_long_name/ -type f -exec readlink -f {} \; > input_files.txt

# looks like this;
# $ head input_files.txt
# /work/steve/projects/singularity_debug/input_dir_with_a_long_name/705
# /work/steve/projects/singularity_debug/input_dir_with_a_long_name/338
# /work/steve/projects/singularity_debug/input_dir_with_a_long_name/630
# /work/steve/projects/singularity_debug/input_dir_with_a_long_name/263

```

- use a simple script to create a huge argument list for `singularity` based on these files; this mimic's Toil's behavior & command line execution with Singularity when using a lot of input files in a workflow step

```
#!/bin/bash
module load singularity/3.3.0
[ ! -e "ubuntu_latest.sif" ] && singularity pull docker://ubuntu:latest || :
# This works fine
args=$(head -1500 input_files.txt | sed -e 's|^|--bind |g'   )
# 131669

# Doesnt work;
# args=$(head -1520 input_files.txt | sed -e 's|^|--bind |g'   )
# FATAL:   json configuration too big 131337 > 131071
# 132927

# Doesnt work;
# args=$(head -1600 input_files.txt | sed -e 's|^|--bind |g'   )
# FATAL:   failed to initialize runtime: engine "" is not found
# 139922

# Doesnt work;
# args=$(head -5000 input_files.txt | sed -e 's|^|--bind |g'   )
# hangs indefinitely
# 438893

set -x
singularity exec \
$args \
ubuntu_latest.sif \
echo ">>> hello" ; echo $?;
set +x
echo $args | wc -c
```

As described in the code above, an arg list up to ~131669 characters works fine. At ~132927, `singularity` starts reporting errors such as `FATAL:   json configuration too big 131337 > 131071`. At ~139922 characters, it starts giving errors `FATAL:   failed to initialize runtime: engine "" is not found`. By 438893 characters, I am not seeing any error messages reported at all, `singularity` instead just stalls out indefinitely; I can see the process in `htop` with 0 CPU activity, so far it seems we've left it running like this up to 6 hours with no response or activity from the Singularity process.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -srviop
Linux 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 GNU/Linux


```

**Comment by dtrudg** [comment]
This is addressed in the latest versions of Singularity. You will need to upgrade to the current 3.7.1. In 3.7.0 a different method of passing engine configuration was introduced that allows much larger environment etc.

**Comment by dtrudg** [comment]
See also: https://github.com/hpcng/singularity/issues/5057
