### ISSUE TITLE
/etc/resolv.conf bind mount spontaneously vanishes

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#5818]
### Versions:
```
$ singularity version
3.7.1-1.el7
$ uname -r
3.10.0-1160.11.1.el7.x86_64
```

### Expected behavior

`/etc/resolv.conf` bind mount should persist for the full container lifetime, i.e. `findmnt -P` in the container should continue to return:
```
$ findmnt -P | grep resolv
TARGET="/etc/resolv.conf" SOURCE="tmpfs[/etc/resolv.conf]" FSTYPE="tmpfs" OPTIONS="rw,nosuid,relatime,seclabel,size=16384k,uid=67803,gid=513"
```

Important configuration parts:
```
allow setuid = yes
config resolv_conf = yes
enable overlay = no
enable underlay = yes
```

### Actual behavior

The mount suddenly vanishes during container runtime. Attaching from outside, with the PID of `sinit` being `16642`, reveals:
```
# findmnt -N 16642 -p
ACTION     TARGET           SOURCE                  FSTYPE OPTIONS
umount     /etc/resolv.conf tmpfs[/etc/resolv.conf] tmpfs  rw,nosuid,relatime,seclabel,size=16384k,uid=67803,gid=513
```
Since the containers we use usually come with an empty `/etc/resolv.conf`, name resolution breaks down. 

### Steps to reproduce this behavior

That's the problematic point. I could not yet trace down the actual cause. I can quite reliably reproduce it using ICC (the Intel C compiler) in version 2020.3.275, compiling with high {{-jN}} value, using a network license. One time, it showed up exactly in-sync when pressing `Ctrl+C`, but that does not seem to always be the case. 
I could not (yet) reproduce reliably with another payload, so likely multithreading / multiprocess with network activity and name resolution (in this case, of a license server) is needed. Suggestions on what I could try to ease reproduction are very welcome. 

### What OS/distro are you running

```
CentOS 7
(for kernel version, see above)
```

### How did you install Singularity

EPEL 7

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by olifre** [comment]
It's not a duplicate, but a still existing issue which needs investigation to determine the cause. Hence, tagged `NeedsInvestigation`. 
Since it causes full network connection loss, it's certainly relevant.

**Comment by carterpeel** [comment]
@olifre
Hello,

There is a chance that the system is cleaning up `/tmp` prematurely if you are an unprivileged user, removing the `rootfs` image and in turn wiping out `/etc/resolv.conf`. 

Since I was unable to reproduce this, could you try to set the environment variable `TMPDIR` to a location other than `/tmp`? (if you're unprivileged, maybe just `TMPDIR=/home/user/singularitytmp/`)

**Comment by olifre** [comment]
> There is a chance that the system is cleaning up `/tmp` prematurely if you are an unprivileged user, removing the `rootfs` image and in turn wiping out `/etc/resolv.conf`.

This only applies for `rootfs` images extracted to `/tmp`, correct? 
The issue was observed with sandbox / extracted images living on a read-only FUSE file system (`cvmfs`). No data is placed into `tmp` by Singularity (at least, I don't think so). Starting Singularity in verbose mode (indeed, as unprivileged user) reveals:
```
VERBOSE: Default mount: /etc/resolv.conf:/etc/resolv.conf
```
which I would interpret as the `/etc/resolv.conf` being taken from the host, not from `/tmp`, I also don't find any files in `/tmp` before the issue appears.

**Comment by DrDaveD** [comment]
That scenario using underlay does use a temporary space for the bind mounts but it is a tmpfs so there should be nothing in /tmp.  Maybe you could reproduce with a make -j test job that does lots of curls and sleeps?  I don't think we'll be able to make any progress without a reproducer.

**Comment by olifre** [comment]
> That scenario using underlay does use a temporary space for the bind mounts but it is a tmpfs so there should be nothing in /tmp.

That's exactly what I thought, so I was confused as on why the system would clean parts of that up. 



> Maybe you could reproduce with a make -j test job that does lots of curls and sleeps? I don't think we'll be able to make any progress without a reproducer.

I will try. Meanwhile, since the original report was almost half a year ago, we've been using an in-container `resolv.conf` as a fallback to hide this issue. 

We are now running `3.10.0-1160.31.1.el7.x86_64` and Singularity 3.8.0, and while I have tried my original reproducer (compiling in many threads with the Intel C compiler), I have been unable to trigger it even once so far. When I did my original report, it could be triggered in seconds. This could also mean it was a kernel issue which was fixed in the meantime. 

I'll still spend some more time the next days to try to reproduce this before giving up.

**Comment by olifre** [comment]
> I'll still spend some more time the next days to try to reproduce this before giving up.

I've now spend quite some time with various conditions (e.g. heavily loaded machine, barely loaded machine, using different numbers of parallel `icc`` processes, filling up memory, filling up `tmpfs` in the container) and indeed can not reproduce this anymore using an up-to-date CentOS 7 kernel and software stack with various different containers. 
So my feeling is that this was indeed an external issue. 

In the unlikely case I see this again, I'll reopen the issue, but let's close it for now and hope it never comes back...
