### ISSUE TITLE
Issue while performing singularity build: conveyor failed to get: error pinging docker registry localhost:5000

### ISSUE THREAD

**Issue by Afia-Anjum** [apptainer/singularity#5819]
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.7.1
```

### Command 
```
sudo singularity build --sandbox --nohttps /tmp/singularity_container docker://localhost:5000/singularity_container 
```

### Expected behavior

Should build the singularity container from local docker registry

### Actual behavior

```
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: error pinging docker registry localhost:5000: Get "http://localhost:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused
```

How can others reproduce this issue/problem?

### What OS/distro are you running
Windows Ubuntu Subsystem
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


```

### How did you install Singularity

```
# download singularity from https://github.com/hpcng/singularity/releases
export VERSION=3.7.0 && # adjust this as necessary \
    wget https://github.com/hpcng/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz && \
    tar -xzf singularity-${VERSION}.tar.gz && \
    cd singularity

$ ./mconfig && \
    make -C builddir && \
    sudo make -C builddir install
```

**Comment by dtrudg** [comment]
> Get "http://localhost:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused

The error shows that Singularity is trying to contact the correct URI, but the connection is refused. Check your docker registry configuration etc.

**Comment by CassandreHeritier** [comment]
> > Get "http://localhost:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused
> 
> The error shows that Singularity is trying to contact the correct URI, but the connection is refused. Check your docker registry configuration etc.

Hello everyone, I have the same issue but impossible for me to find the right configuration to use docker. How to configure the docker registry to solve this problem (docker authentication I think) ? Thanks.
