### ISSUE TITLE
"singularity exec --nv" did not work in Nvidia Jetson nano 2gb

### ISSUE THREAD

**Issue by jdongca2003** [apptainer/singularity#5837]
### Version of Singularity:

What version of Singularity are you using? Run:
3.7.1

OS: 
nvidia Jetson nano 2gb

jdong@jdong-desktop:/etc$ more os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"

  L4T R32.5 
jdong@jdong-desktop:/etc$ more /etc/nv_tegra_release
# R32 (release), REVISION: 5.0, GCID: 25531747, BOARD: t210ref, EABI: aarch64, DATE: Fri Jan 15 22:55:35 UTC 2021

How can I install singularity 3.7.1?
https://sylabs.io/guides/3.7/admin-guide/installation.html#installation-on-linux
(for ubuntu)
go : 1.14.12 (arm64)

### Expected behavior

What did you expect to see when you do...?
use singularity to pull l4t pytorch docker image to sif image.

singularity pull l4t-pytorch_r32.5.0-pth1.7-py3.sif docker://nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3

After *.sif is ready, I run

singularity exec --nv l4t-pytorch_r32.5.0-pth1.7-py3.sif  bash

### Actual behavior

What actually happend? Why was it incorrect?
I got error message "
jdong@jdong-desktop:~/development/install_singularity$ singularity exec --nv l4t-pytorch_r32.5.0-pth1.7-py3.sif bash
INFO:    Could not find any nv files on this host!

That means that GPU cannot be found.

jdong@jdong-desktop:~/development/install_singularity$ singularity exec --nv l4t-pytorch_r32.5.0-pth1.7-py3.sif python3
INFO:    Could not find any nv files on this host!
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 189, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 142, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.10: cannot open shared object file: No such file or directory

Once inside image, 
Singularity> ls -la /usr/local/cuda/lib64/stubs
total 1290
drwxr-xr-x 2 root root    411 Dec  4 16:33 .
drwxr-xr-x 3 root root     76 Dec  4 16:33 ..
-rw-r--r-- 1 root root  29464 Dec  4 16:25 libcuda.so
-rw-r--r-- 1 root root   9288 Dec  4 16:25 libcufft.so
-rw-r--r-- 1 root root   9288 Dec  4 16:25 libcufftw.so
-rw-r--r-- 1 root root   5192 Dec  4 16:25 libcurand.so
-rw-r--r-- 1 root root  70728 Dec  4 16:25 libcusolver.so
-rw-r--r-- 1 root root  50248 Dec  4 16:25 libcusparse.so
-rw-r--r-- 1 root root   5192 Dec  4 16:25 libnppc.so
-rw-r--r-- 1 root root 156744 Dec  4 16:25 libnppial.so
-rw-r--r-- 1 root root  91208 Dec  4 16:25 libnppicc.so
-rw-r--r-- 1 root root   9288 Dec  4 16:25 libnppicom.so
-rw-r--r-- 1 root root 123976 Dec  4 16:25 libnppidei.so
-rw-r--r-- 1 root root 169032 Dec  4 16:25 libnppif.so
-rw-r--r-- 1 root root  62536 Dec  4 16:25 libnppig.so
-rw-r--r-- 1 root root  29768 Dec  4 16:25 libnppim.so
-rw-r--r-- 1 root root 283720 Dec  4 16:25 libnppist.so
-rw-r--r-- 1 root root   5192 Dec  4 16:25 libnppisu.so
-rw-r--r-- 1 root root  37960 Dec  4 16:25 libnppitc.so
-rw-r--r-- 1 root root 148552 Dec  4 16:25 libnpps.so
-rw-r--r-- 1 root root   9288 Dec  4 16:25 libnvgraph.so
-rw-r--r-- 1 root root   5192 Dec  4 16:25 libnvrtc.so

But jdong@jdong-desktop:~$ which nvidia-container-cli
/usr/bin/nvidia-container-cli

jdong@jdong-desktop:~$ nvidia-container-cli list
/usr/lib/aarch64-linux-gnu/tegra/libcuda.so.1.1
/usr/lib/aarch64-linux-gnu/tegra/libnvidia-ptxjitcompiler.so.440.18
/usr/lib/aarch64-linux-gnu/tegra/libnvidia-fatbinaryloader.so.440.18
/usr/lib/aarch64-linux-gnu/tegra/libnvidia-eglcore.so.32.5.0
/usr/lib/aarch64-linux-gnu/tegra/libnvidia-glcore.so.32.5.0
/usr/lib/aarch64-linux-gnu/tegra/libnvidia-tls.so.32.5.0
/usr/lib/aarch64-linux-gnu/tegra/libnvidia-glsi.so.32.5.0
/usr/lib/aarch64-linux-gnu/tegra/libGLX_nvidia.so.0
/usr/lib/aarch64-linux-gnu/tegra-egl/libEGL_nvidia.so.0
/usr/lib/aarch64-linux-gnu/tegra-egl/libGLESv2_nvidia.so.2
/usr/lib/aarch64-linux-gnu/tegra-egl/libGLESv1_CM_nvidia.so.1

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
1) Flash L4T R32.5 image into Jetson nano 2gb development kit
2) Follow instructions on https://sylabs.io/guides/3.7/admin-guide/installation.html#installation-on-linux
    (ubuntu)
     go version: 1-14.12, arm64
     singularity version: 3.7.1
3) Pull l4t pytorch image
     singularity pull l4t-pytorch_r32.5.0-pth1.7-py3.sif docker://nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3
4) singularity exec --nv  l4t-pytorch_r32.5.0-pth1.7-py3.sif bash

### What OS/distro are you running

```
$ cat /etc/os-release

jdong@jdong-desktop:~/development/install_singularity$ more /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
Compile from source.

Follow instructions on https://sylabs.io/guides/3.7/admin-guide/installation.html#installation-on-linux
    (ubuntu)
     go version: 1-14.12, arm64
     singularity version: 3.7.1

sudo apt-get update && sudo apt-get install -y \
    build-essential \
    uuid-dev \
    libgpgme-dev \
    squashfs-tools \
    libseccomp-dev \
    wget \
    pkg-config \
    git \
    cryptsetup-bin

export VERSION=1.14.12 OS=linux ARCH=arm64 && \
    wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
    sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz

in .bash_profile add
export GOPATH=${HOME}/go
export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin

export VERSION=3.7.1 && \
    wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz && \
    tar -xzf singularity-${VERSION}.tar.gz && \
    cd singularity

./mconfig && \
   make -C ./builddir
   sudo make -C ./builddir install

**Comment by dtrudg** [comment]
This is going to be difficult to troubleshoot without access to a Jetson nano to install the jetson software stack on. As a first step, however, please could you provide the debug output of attempting to run the container. Add the `-d` flag to your `singularity` command, i.e.

```
singularity -d exec --nv l4t-pytorch_r32.5.0-pth1.7-py3.sif bash
```

**Comment by dtrudg** [comment]
No follow up, so closing as we don't have access to a Jetson nano to debug ourselves. Please feel free to reopen if you have further information.
