### ISSUE TITLE
Openfoam example fails to install

### ISSUE THREAD

**Issue by rherban** [apptainer/singularity#584]
Host OS: CentOS Linux release 7.1.1503
Container OS: Ubuntu 14.04
Singularity: singularity-2.2.1-0.1.el7.centos.x86_64
Using definition from: https://github.com/singularityware/singularity/blob/master/examples/contrib/ubuntu-openfoam.def

Apt fails to download openfoam due to missing package:

`Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libgpg-error0 amd64 1.12-0.2ubuntu1 [10.9 kB]
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
ERROR: Aborting with RETVAL=255`

Adding the package `apt-transport-https` to the def file allows it to build properly.

**Comment by gmkurtzer** [comment]
Fixed, thank you! :)
