### ISSUE TITLE
Is there a way to specify %runscript to use /bin/bash?

### ISSUE THREAD

**Issue by crotoc** [apptainer/singularity#5843]
Thanks for the great tool for saving me huge amount of time. Appreciate your great efforts to make it better!

I have a question about how to let %runscript use /bin/bash, please see the following. I have intensively searched for several days but haven't found a way to achieve this in definition file. I only get this done to build a sandbox first and then modify the shebang mannually. Please tell me if there is a way to do this. Thanks!

### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```

3.7.0+53-gb0d6e8d03

### Expected behavior

What did you expect to see when you do...?

I want to use /bin/bash for %runscript, so that I can activate a conda env when using **singularity run**

### Actual behavior

What actually happend? Why was it incorrect?

I put %runscript -c /bin/bash in my definition file and it shows the shebang of "#!/bin/sh -c /bin/bash".  When I use **singularity run**, it throws a error that  "/bin/sh: 0: Illegal option - "

![image](https://user-images.githubusercontent.com/12446554/108765553-8a4f0a00-7519-11eb-9587-a44395320919.png)

As a workaround, I manually change shebang to "#!/bin/bash", the conda env can be loaded correctly. 

![image](https://user-images.githubusercontent.com/12446554/108765666-b23e6d80-7519-11eb-950b-d555e917d817.png)

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Definition file saved in test.singularity
```
File Edit Options Buffers Tools YASnippet Help                                                                                                                                                
Bootstrap: docker
From: ubuntu:20.04

%files

%environment
    export LC_ALL=C
    export PATH=/usr/opt/miniconda3/bin/:$PATH

%post
   apt update

%runscript -c /bin/bash
  if [ -f "/usr/opt/miniconda3/etc/profile.d/conda.sh" ];then
      echo "source conda.sh"
      source /usr/opt/miniconda3/etc/profile.d/conda.sh
  fi

  if [ -d "/mylib/condaEnv/ldsc" ];then
     echo "loading conda ldsc ..."
     source activate /mylib/condaEnv/ldsc
  fi

  exec "$@"
```

Build a sandbox

```
singularity build --fakeroot --sandbox test test.singularity

```

Run
```
singularity run  -e --bind /home/ test/
/bin/sh: 0: Illegal option -
```

### What OS/distro are you running

```
$ cat /etc/os-release
ubuntu 20.04

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
source

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by luator** [comment]
Can this be reopened?  I'm having the same issue with Singularity 3.8.3 and I assume that the desire to use bash in runscript is a rather common issue.

I find this especially confusing as `%post -c /bin/bash` is working to use bash in the `%post` section but the same does not work for `%runscript`.  Here is a more minimal example:

```
Bootstrap: library
From: ubuntu:20.04

%post -c /bin/bash
    echo "echo hello" > /script.sh
    source /script.sh

%runscript -c /bin/bash
    source /script.sh
```

Without `-c /bin/bash` in the post section this would fail because `source` does not exist in `sh`.  However, when running the image, instead of the expected "hello" output, I get "/bin/sh: 0: Illegal option - ".

**Comment by DrDaveD** [comment]
I'm not sure the answer to your question, but is using "." instead of "source" another workaround you could use?

**Comment by crotoc** [comment]
If my memory is right, . does not work as well. Thanks for the suggestion!

**Comment by luator** [comment]
Thanks for re-opening!

> I'm not sure the answer to your question, but is using "." instead of "source" another workaround you could use?

It is not about `source` specifically, I'm just using it as an indicator here whether bash or sh is used.  You could replace it with any other bash-specific feature that does not exist in sh.

**Comment by DrDaveD** [comment]
Ok, in that case, how about using one of the sh mechanisms for invoking another program, e.g. a HERE document as a workaround:
```
Bootstrap: library
From: ubuntu:20.04

%post
    echo "echo hello" > /script.sh

%runscript
    exec /bin/bash <<'!EOF!'
    source /script.sh
!EOF!
```

**Comment by luator** [comment]
This would work but to me it looks more like a workaround than a proper solution.  I think it would be much cleaner if there was an official option to overwrite the shebang of the runscript (especially, since this is already possible for `%post`).

**Comment by DrDaveD** [comment]
As a cross reference, a recipe for setting up conda in %runscript is in #5075

**Comment by kmuriki** [comment]
Singularity repo is now retired as the code base is now moved to Apptainer. We are closing all the old issues under the old Singularity repo. For further assistance please open a new issue under the new Apptainer repo. Thanks for your support.
