### ISSUE TITLE
Singularity 3.7.1 does not correctly bind CWD

### ISSUE THREAD

**Issue by huston-rogers** [apptainer/singularity#5846]
### Expected behavior

What did you expect to see when you do...?
```
$ pwd
/work/datasets/path/to/my/data/
$ singularity exec lolcow.sif pwd
/work/datasets/path/to/my/data/
```
### Actual behavior
```
$ pwd
/work/datasets/path/to/my/data/
$ singularity exec lolcow.sif pwd
/home/<MyUsername>/
```
### Extra Behavior example:
```
$ pwd
/work/datasets/path/to/my/data/
$ singularity exec lolcow.sif pwd
/home/<MyUsername>
$ singularity exec lolcow.sif env | grep PWD
OLDPWD=/home/<MyUsername>
PWD=/home/<MyUsername>
$ singularity exec lolcow.sif echo $PWD
/work/datasets/path/to/my/data/
```
### What actually happend? Why was it incorrect?

I would expect singularity to bind /work/datasets/path/to/my/data, as that's the folder we run from. That was the behavior in Singularity 3.5.2 (Last version installed).

More detailed example of incorrectness:
singularity exec <path/to/container> <command for container> <input for command> fails because it cannot find the input for the command. But in singularity 3.5.2, it has no issue finding the input for the command. 

My config is the same for both singularity versions. If I change
```mount hostfs = no```
to
```mount hostfs = yes```
in singularity 3.7.1, it works as it did in 3.5.2. Is this intentional? Did I overlook something in a changelog?

### Steps to reproduce this behavior

cd to a non-home directory, then execute "singularity exec myimg.sif pwd" and it will print your home directory, when it should print the current working directory

### What OS/distro are you running

```CentOS Linux release 7.8.2003 (Core)```

### How did you install Singularity

Singularity build from source. Notes from installation:

```
## tar -xzf singularity-3.7.1.tar.gz && \
## cd singularity
## ./mconfig --prefix=/apps/singularity-3/singularity-3.7.1 && \
## make -C ./builddir && \
## make -C ./builddir install
## chown root:root /apps/singularity-3/singularity/3.7.1
## chown o+rX /apps/singularity-3/singularity-3.7.1
## chmod 4755 /apps/singularity-3/singularity-3.7.1/libexec/singularity/bin/starter-suid
```

**Comment by dtrudg** [comment]
This behavior changed in 3.6.0. Singularity has reverted to the 2.x behavior, where CWD is not bound explicitly, but may be present through a HOME or other bind.

> Restored the CWD mount behaviour of v2, implying that CWD path is not recreated inside container and any symlinks in the CWD path are not resolved anymore to determine the destination path inside container.

https://github.com/hpcng/singularity/blob/master/CHANGELOG.md#changed-defaults--behaviours-1

I probably agree here that the change log message could have been more explicit about the effect of this. Apologies.

The reversion to the 2.x behavior was due to irreconcilable bugs related to handling symlinks and overlapping binds in the CWD paths. Different approaches were tried in the 3.x series, but there wasn't a solution for all situations. Reverting to the 2.x behavior provides consistency, though it is less convenient.

**Comment by huston-rogers** [comment]
Follow-up with some background:

I'm providing software via containers through lmod, by creating shell functions that are added to the environment by loading a module. i.e.

```$module load command```
adds to environment:
```set_shell_function("command",'singularity exec /apps/singularity-3/container.sif command $@','singularity exec /apps/singularity-3/container.sif command $*')```

And then our users have the software availble as a shell function. i.e. they can say 
```command --option input.ext --option2```

There's two ways to fix the issue where the current working directory isn't accessible, as best I can tell. 
1. set mount_hostfs=yes. I don't think this is the correct solution. I don't think I want the whole fs to be remounted and visible to the container.
2. Add binds to my shell function, and force a syntax change for my end users, as described below.

add --bind $PWD:/mnt/ to the exec command, and have users add "/mnt/" to the beginning of any input files they need to pass.

My Change:
```set_shell_function("command",'singularity exec --bind $PWD:/mnt /apps/singularity-3/container.sif command $@','singularity exec --bind $PWD:/mnt/ /apps/singularity-3/container.sif command $*')```

End user change:
```command --option input.ext --option2```
To this:
```command --option /mnt/input.ext --option2```

is Option 2 the "most" correct way to keep the functionality we want? I appreciate the clarification.

**Comment by huston-rogers** [comment]
Option 2.a: --bind $PWD:$PWD does what I want, but i think that's explicitly the issue that was patched with failing to resolve CWD sometimes.

**Comment by dtrudg** [comment]
Option 2a is fine if it works on your system. Issues only occur with some complex symlinked paths and overlapping binds.
