### ISSUE TITLE
Singularity instance documentation unclear

### ISSUE THREAD

**Issue by tsnowlan** [apptainer/singularity#5849]
### Version of Singularity:

```
$ singularity version
3.7.1
```

### Example

```
$ singularity instance start -e --env SOME_VAR=some_val my_image.sif my_instance
INFO:    instance started successfully
$ singularity exec -e instance://my_instance env | grep SOME
$
```

### Expected behavior

Environment variable set at instance start would be available to `singularity shell` and `singularity exec` commands run within it

### Actual behavior

Environment variables set at `instance start` are not persisted to `singularity exec|shell` commands run on that instance. This seems to be by design (ref: #5353), but is not mentioned anywhere in the documentation on instances or environment.

For people moving from Docker to Singularity, `singularity instance start` can be seen as a `docker run` equivalent. Variables set at `docker run` _are_ persisted to later `docker exec` calls on the same container, so it's a reasonable (if incorrect) assumption that the same would be true for singularity instances. Having the actual behavior stated in the docs would be really helpful.

**Comment by dtrudg** [comment]
Thank you for the comment here. Please raise documentation issues at: https://github.com/hpcng/singularity-userdocs
