### ISSUE TITLE
failure to respect tags when pulling from shub

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#5853]
### Version of Singularity:

```
$ singularity --version
singularity version 3.7.1
```

### Expected behavior

When you pull 2 containers from shub with different tags you should end up with 2 different containers.  

### Actual behavior

When you pull 2 containers from shub with 2 different tags, the second container just uses the cache.  Then you end up with 2 identical containers with different names.  You can use the `--disable-cache` option to the `pull` as a workaround.

### Steps to reproduce this behavior

```
$ singularity pull shub://bballew/NGS_singularity_recipes:samtools_1-9
INFO:    Downloading shub image
260.7MiB / 260.7MiB [==============================================================================] 100 % 90.4 MiB/s 0s

$ singularity pull shub://bballew/NGS_singularity_recipes:delly_0-8-1
INFO:    Use cached image

$ ls -la
total 536016
drwxr-xr-x  2 user user      4096 Mar  1 12:55 .
drwxr-xr-x 13 user user      4096 Mar  1 12:53 ..
-rwxr-xr-x  1 user user 273350687 Mar  1 12:55 NGS_singularity_recipes_delly_0-8-1.sif
-rwxr-xr-x  1 user user 273350687 Mar  1 12:54 NGS_singularity_recipes_samtools_1-9.sif
```
The last command shows that both images are the same size even though they should not be. 
```
$ rm NGS_singularity_recipes_delly_0-8-1.sif

$ singularity pull --disable-cache shub://bballew/NGS_singularity_recipes:delly_0-8-1
INFO:    Downloading shub image
320.0MiB / 320.0MiB [==============================================================================] 100 % 99.0 MiB/s 0s

$ ls -la
total 597028
drwxr-xr-x  2 user user      4096 Mar  1 12:56 .
drwxr-xr-x 13 user user      4096 Mar  1 12:53 ..
-rwxr-xr-x  1 user user 335581215 Mar  1 12:56 NGS_singularity_recipes_delly_0-8-1.sif
-rwxr-xr-x  1 user user 273350687 Mar  1 12:54 NGS_singularity_recipes_samtools_1-9.sif
```
Now the 2 images are sized appropriately

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux cn0952 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### How did you install Singularity

Singularity was installed from source.

**Comment by dtrudg** [comment]
We are sending a request to get the manifest with the tag:

https://github.com/hpcng/singularity/blob/f793481d0f32c85883201d0c65492869a437333d/internal/pkg/client/shub/api.go#L63

The cache is keyed off the Commit entry from the returned manifest - `manifest.Commit`

https://github.com/hpcng/singularity/blob/f793481d0f32c85883201d0c65492869a437333d/internal/pkg/client/shub/pull.go#L151

I would think that this would be unique for different containers. If it's not, we need to use something else, definitely.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
