### ISSUE TITLE
Issue with Singularity Verify

### ISSUE THREAD

**Issue by ross-chaudhry** [apptainer/singularity#5854]
### Version of Singularity:
```
$ singularity --version
singularity version 3.7.1
```

### Expected behavior
I want to show author and other verification information from a pulled container sourced from `library`.

### Actual behavior
Verification fails on both `singularity pull` and `singularity verify`.

### Steps to reproduce this behavior
From a fresh directory, download the latest ubuntu image from library:
```
$ singularity pull --disable-cache ubuntu_latest.sif library://ubuntu:latest
INFO:    Downloading library image
26.8MiB / 26.8MiB [==================================================================] 100 % 2.5 MiB/s 0s
WARNING: integrity: signature not found for object group 1
WARNING: Skipping container verification
```
(Note that verification fails here too.) Then following the [sign and verify instructions](https://sylabs.io/guides/3.7/user-guide/signNverify.html), verify:
```
$ singularity verify ubuntu_latest.sif 
Verifying image: ubuntu_latest.sif
FATAL:   Failed to verify container: integrity: signature not found for object group 1
```

I have a valid remote access token:
```
$ singularity remote list
Cloud Services Endpoints
========================

NAME         URI              ACTIVE  GLOBAL  EXCLUSIVE
SylabsCloud  cloud.sylabs.io  YES     YES     NO

Keyservers
==========

URI                     GLOBAL  INSECURE  ORDER
https://keys.sylabs.io  YES     NO        1*

* Active cloud services keyserver
```
I have tried adding the `--legacy-insecure` option. I have also tried other images (`alpine`, `lolcow`). I included `--disable-cache` to make sure no previous image was being used somehow, but the result is the same either way.

How can I get the container to verify? What does `signature not found for object group 1` mean?

### What OS/distro are you running

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity
From source on my workstation with root access, following the 3.7 instructions. It's working for building and running containers, so I believe I have installed it correctly.

**Comment by dtrudg** [comment]
This container is not signed. There was no signature found, so no verification can be performed.

**Comment by ross-chaudhry** [comment]
Thanks for the response. Are any of the containers from the library signed, then? Based on the documentation for 3.7 (https://sylabs.io/guides/3.7/user-guide/signNverify.html), they should be:

> you can verify containers that you pull from the library
> ...
> `Container verified: alpine_latest.sif`
> ...
> In this example you can see that Sylabs Admin has signed the container.

However, all of the latest standard distributions that I've tried are not signed, including Ubuntu, CentOS, and Alpine. Are there plans to address this?

**Comment by dtrudg** [comment]
There are many containers that have been signed by users before being pushed to the library.

I'll ask internally about the standard images. Generally for questions regarding the content of the cloud.sylabs.io services support@sylabs.io would be a better contact point, as they are run by Sylabs and are not part of the open source HPCng project.

I'll open a docs issue to ensure the verify is against a container that is guaranteed to be signed also.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by ross-chaudhry** [comment]
Yes, this issue is still outstanding. I have sent an email to support@sylabs.io and have not received any reply, and the response here so far only indicates that the issue is being looked into.

For me, resolution would be either (1) standard containers from sylabs begin to be signed as is currently intended/documented, or (2) update the documentation to reflect that they are not signed and an explain for why signing is not occurring.
