### ISSUE TITLE
Separate Singularity syslogs

### ISSUE THREAD

**Issue by kees-closed** [apptainer/singularity#5855]
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.7.1-1.el7_9
```

### Expected behavior

I want to separate the syslog events that happen inside a Singularity container.

When I have:
```
BootStrap: library
From: ubuntu:20.04

%post
    apt-get update
    apt-get -y install cron
```

And run `singularity build --fakeroot test.sif Singularity.def`

In `/var/log/secure.log` logs appear that happen inside the container.

Old documentation states that `local0` is used for logs: https://singularity.lbl.gov/docs-config#logging

But when I add this line as early as possible in the rsyslog lines: `if $syslogfacility-text == 'local0' then /var/log/singularity-container.log`

Nothing shows up in that singularity-container.log file. Only after I run `logger -p local0.info -t test test`.

So that `local0` is not used anymore by Singularity?

How can I separate the container logs from the host itself?

### What OS/distro are you running

```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```

### How did you install Singularity

Installed the singularity-3.7.1-1.el7_9.x86_64 RPM.

**Comment by dtrudg** [comment]
Singularity 3.x does not log to syslog unless a plugin is used. The documentation refers to the old version.

Also note that there is a difference between Singularity itself logging (this would be messages about setting up and starting a container), and logs from applications running in the container. If you want applications running in a container to log to a different location they must be configured to do so. Singularity cannot directly control their logging. The `/dev/log` socket is bound into the container, and will be used by applications by default.

**Comment by kees-closed** [comment]
> Singularity 3.x does not log to syslog unless a plugin is used

Which plugin exactly?

> Also note that there is a difference between Singularity itself logging (this would be messages about setting up and starting a container), and logs from applications running in the container

I'm indeed referring to the build of the container. At the moment the post-scripts logs of package installs (e.g. creating a group) is logged on the container host, e.g. /var/log/secure. This is confusing for log monitoring. Because those events did not take place on that host.

So specifically the question comes down to, how can I prevent any logs from the container to show up on the container host? Specifically the log events during the container build.

**Comment by dtrudg** [comment]
> > Singularity 3.x does not log to syslog unless a plugin is used
> 
> Which plugin exactly?

See the `examples/plugins/log-plugin` directory in the repository.

> > Also note that there is a difference between Singularity itself logging (this would be messages about setting up and starting a container), and logs from applications running in the container
> 
> I'm indeed referring to the build of the container. At the moment the post-scripts logs of package installs (e.g. creating a group) is logged on the container host, e.g. /var/log/secure. This is confusing for log monitoring. Because those events did not take place on that host.
> 
> So specifically the question comes down to, how can I prevent any logs from the container to show up on the container host? Specifically the log events during the container build.

There isn't any built-in way to do this through Singularity options. This will be specific to the distribution / actions you are performing. Software often accepts environment variables to disable syslog logging, and these would be a good place to start.

On my Fedora system I do not see syslog/journal entries from builds, as under the systemd-journald setup, the host's `/dev/log` is a symlink to a socket that will not present in the container fs. 

It may be possible to `mount --bind /dev/null /dev/log` to block the log device/socket in your `%post` block. I have not tried this, though.

**Comment by kees-closed** [comment]
> Software often accepts environment variables to disable syslog logging

Thanks for your reply. Do you have more info on this? I couldn't find any info about this so far. It would be great if Singularity could be configured to launch with an environment variable that disables syslog. But I cannot find this variable. The software indeed must respect such a variable, if Singularity doesn't do that, then it won't work. I'm sure it's not a global thing, otherwise `sudo` can be abused with that environment variable and nothing would appear in the syslog.

**Comment by dtrudg** [comment]
Correct, there is no one variable - different applications have their own variables to disable logging to syslog, and as you point out some like sudo won't allow it at all, so there's no one thing Singularity can set.

A more general approach would require Singularity builds to be more isolated from the host, particularly handling of `/dev/log`. We might consider a PR contribution for this.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
