### ISSUE TITLE
FATAL ERROR - a shared library is likely missing in the image

### ISSUE THREAD

**Issue by karim7878** [apptainer/singularity#5860]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3
```

### Expected behavior
I would like to run a container

### Actual behavior

What actually happend? Why was it incorrect?

Verification fails on both ```singularity test``` and ```singularity exec```

### Steps to reproduce this behavior
```

singularity test ***.img
FATAL:   exec /.singularity.d/actions/test failed: a shared library is likely missing in the image
```

### What OS/distro are you running

```
$ cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

### How did you install Singularity

From source

**Comment by dtrudg** [comment]
Please:

- Test with a current version of Singularity (3.7)
- Describe what is in the image / provide the definitions that was used to build it
- Provide debug output with `-d` i.e. `singularity -d test myimage.sif`

**Comment by dtrudg** [comment]
No follow up, so closing. Please feel free to reopen if you can replicate on Singularity 3.7 and can provide the information requested above.
