### ISSUE TITLE
Creating a SIF out of a really long DEF file

### ISSUE THREAD

**Issue by verilog15** [apptainer/singularity#5862]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```

> 3.7.1-1

### Expected behavior

I'm trying to create a SIF out of a DEF file by running the following command:
```
singularity --debug build output.sif output.dif
```
It should create a SIF file.

### Actual behavior

The output:
```
DEBUG   [U=0,P=68]         persistentPreRun()            Singularity version: 3.7.1-1
DEBUG   [U=0,P=68]         persistentPreRun()            Parsing configuration file /etc/singularity/singularity.conf
DEBUG   [U=0,P=68]         handleConfDir()               /root/.singularity already exists. Not creating.
DEBUG   [U=0,P=68]         Init()                        Image format detection
DEBUG   [U=0,P=68]         Init()                        Check for sandbox image format
DEBUG   [U=0,P=68]         Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=68]         Init()                        Check for sif image format
DEBUG   [U=0,P=68]         Init()                        sif format initializer returned: SIF magic not found
DEBUG   [U=0,P=68]         Init()                        Check for squashfs image format
DEBUG   [U=0,P=68]         Init()                        squashfs format initializer returned: while parsing squashfs super block: not a valid squashfs image
DEBUG   [U=0,P=68]         Init()                        Check for ext3 image format
DEBUG   [U=0,P=68]         Init()                        ext3 format initializer returned: file is not a valid ext3 image
FATAL   [U=0,P=68]         runBuildLocal()               Unable to build from output.dif: while parsing definition: output.dif: bufio.Scanner: token too long
````

### Steps to reproduce this behavior

Create a def file like this:
```
Bootstrap: docker
From:  <ADD FROM>

%setup

%files

%environment

%post

zypper -n in -l <ADD-PACKAGES>

%labels
pathsA = [
    pathA1
    pathA2
    pathA3
    ...
]

pathsB = [
    pathB1
    pathB2
    pathB3
    ...
]

pathsC = [
    pathC1
    pathC2
    pathC3
    ...
]
```
The file is really long (3381 lines in total). `pathsB` and `pathsC` are really long and this is why I'm getting the error.

Why Singularity can't handle with long files?

### What OS/distro are you running

Linux SUSE SLES12

**Comment by dtrudg** [comment]
How big exactly are your PATHx labels here and what is the use-case? The number of lines shouldn't be an issue - it's the size of an individual token. If you can share a representative file that would be useful.

The scanner error is as the default `MaxScanTokenSize = 64 * 1024` in Go gives us a 64K limit per token.

I'd like to know a bit more in case increasing the token size here might cause problems downstream.

**Comment by dtrudg** [comment]
Leaving open, but we can't progress this without an idea of sensible bounds fot eh token size, as above.

**Comment by verilog15** [comment]
Hi @dtrudg, We are localizing the area in order to make the tools work inside Singularity. We configure all the links, copy the files and create the directories. Big tools would require about 200K chars (which is about only 2500 lines).  Is it possible to explain why Singularity has a token limit? I think Singularity should allow to customize `MaxScanTokenSize`.

**Comment by dtrudg** [comment]
> Is it possible to explain why Singularity has a token limit? I think Singularity should allow to customize `MaxScanTokenSize`.

The `MaxScanTokenSize`, if it is the issue, is a default set in the Go standard library. Each customization needs consideration w.r.t. possible effects, and tests written against it - so we don't want to unnecessarily add customization unless its specifically required. We want to ensure we can understand what the reasonably required range is, and make sure everything works within that range.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
