### ISSUE TITLE
upgrading from 3.4.2 to 3.5.1 works on Kernel 5.8, but breaks charset of GUI apps

### ISSUE THREAD

**Issue by pguillem** [apptainer/singularity#5864]
**### Version of Singularity:**
3.5.1 and 3.4.2

**What version of Singularity are you using? Run:**
3.5.1

**What did you expect to see when you do...?**

We use singularity containers to run old 2012 apps on top of newer kernels.

We had working containers using 3.4.2, but then we upgraded to kernel 5.8 earlier this week and it could not mount the squashfs anymore due to the parameter -ro problem. This was fixed on 3.5.1 (Fix #4801)

3.5.1 is able to launch my containers. But the charset in the application looks scrambled. 

In simpler words, the app GUI within the container is launching properly, but all the labels look like squares instead of characters. (SEE ATTACHED IMAGE).

Perhaps my poor knowledge of singularity is missing something?. Are we supposed to edit/alter older containers somehow after we upgrade to 3.5.1?

**### Steps to reproduce this behavior**
Open a container (hosting a GUI application) created in 3.4.2 but using newer 3.5.1.

**### What OS/distro are you running**

Ubuntu focal (20.04.1)
Kernel 5.8.0-41

**### How did you install Singularity**
From source. Exactly as explained in the installation guide.

![problem_singularity](https://user-images.githubusercontent.com/1541205/110340971-23a61200-802a-11eb-8d40-e8abf12bd949.jpg)

**Comment by dtrudg** [comment]
We'd need to know what environment variables are set, and ideally access to an example container and/or definition file to reproduce the issue and investigate.

Also please try to reproduce with current Singularity 3.7.x. We only address bugs in the current open source version and 3.5.1 is 2 minor versions back at this point, and subject to security issues fixed in later versions.

**Comment by pguillem** [comment]
Thanks. I will try with 3.7.x and report back the results

**Comment by dtrudg** [comment]
Closing as no follow-up >30 days. Please feel free to re-open if you are able to provide the information requested above. Thanks.
