### ISSUE TITLE
DNS resolution failure with --fakeroot --net, successful network connectivity

### ISSUE THREAD

**Issue by briveramelo** [apptainer/singularity#5866]
### Version of Singularity:

```
$ singularity version
3.7.1
```

### Expected behavior
Containers should resolve hostnames like google.com

I expect my app to resolve external domains fine. A surface-level ping test goes most of the way, like so
```
singularity pull alpine.sif library://alpine:latest
singularity instance start -f --net alpine.sif alp
singularity exec instance://alp ping -c 1 google.com

PING google.com (172.217.11.78): 56 data bytes
64 bytes from 172.217.11.78: icmp_seq=0 ttl=115 time=25.846 ms

--- google.com ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 25.846/25.846/25.846/0.000 ms
```

### Actual behavior

The output, instead looks like this
```
ping: bad address 'google.com'
```

### Steps to reproduce this behavior

1. add your user to the fakeroot config
```
sudo singularity config fakeroot --add <user>
```
2. Update your fakeroot network config: `40_fakeroot.conflist`
```
{
    "cniVersion": "0.4.0",
    "name": "fakeroot",
    "plugins": [
        {
            "type": "bridge",
            "bridge": "sbr0",
            "isGateway": true,
            "ipMasq": true,
            "ipam": {
                "type": "host-local",
                "subnet": "10.22.0.0/16",
                "routes": [
                    { "dst": "0.0.0.0/0" }
                ]
            }
        },
        {
            "type": "firewall"
        },
        {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
        }
    ]
}
```
3. Run a surface-level test
```
singularity pull alpine.sif library://alpine:latest
singularity instance start -f --net alpine.sif alp
singularity exec instance://alp ping -c 1 google.com
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

### How did you install Singularity

System admin did the install, I don't know more.

### Other Context

Here are the other tests I've tried, including:

1. Can I ping google from the host? Yes

2. Can I ping my containers from the host? Yes

3. Does direct IP ping from the containers work? Yes. ie
`singularity exec instance://alp ping -c 1 8.8.8.8`

4. Can I communicate from one container to another in the fakeroot network? Yes. ie

```
singularity instance start -f --net --network-args="IP=10.22.0.2" alpine.sif alp2
singularity instance start -f --net --network-args="IP=10.22.0.3" alpine.sif alp3
singularity exec instance://alp2 ping -c 1 10.22.0.3
```

5. Does editing the container /etc/hosts file work? Yes and no. The surface-level test will pass, ie:
```
singularity instance start -f --net alpine.sif alp
singularity shell instance://alp
Singularity > echo -e "172.217.11.78\tgoogle.com" >> /etc/hosts
Singularity > ping -c 1 google.com
```
My application-specific code, however, will continue failing with dns resolution. Each of my 4 apps appear to neglect these mappings, and they all use different base images.

6. Does editing the container /etc/resolv.conf file work? No
Adding `nameserver 8.8.8.8` or replacing all of the contents in this file with that same line has no impact

**Comment by briveramelo** [comment]
7. Will replacing the fakeroot network plugin type from "bridge" to "ipvlan" fix this? No. These two types appear to work the same for me

**Comment by cclerget** [comment]
Hi @briveramelo , have you try to inject a DNS when running singularity with `--dns 1.1.1.1`

Generally when using network namespace on a systemd driven system,the nameserver injected in the container is 
`nameserver 127.0.0.53` which obviously won't work within a network namespace.

If the `--dns` option doesn't work you can also try `-B /run/systemd/resolve/resolv.conf:/etc/resolv.conf` which should contains the DNS used inside your network.

Anyway this is something to fix at Singularity level when running on a systemd driven system to avoid the above workarounds

**Comment by briveramelo** [comment]
I forgot to mention that I had already tried the --dns route, and I did again just now with that nameserver address to be sure, but it does not work. (8)

I also do not have the directory /run/systemd/resolve, so there is no resolv.conf file there (9). I do have a file at /etc/resolv.conf, which I can see is being bound to the container. The IPs here look like I would expect (ie: no loopback / local network addresses). 

Would seeing the debug output of the start command help?

**Comment by cclerget** [comment]
Is firewall enabled ? if yes what if you disable it ?
Looks like there is some filtering somewhere if ping pass but DNS requests not

**Comment by briveramelo** [comment]
Great question. Yes. There are some firewall rules enabled.

I do not have access to disable the firewall, though I do have a temporary sudoers entry for modifying the firewall configuration.

Hopefully I can try this out tomorrow. It sounds worth exploring

**Comment by briveramelo** [comment]
While waiting for a response, I found [this post](https://superuser.com/questions/1397662/ho-to-route-one-subnet-to-another-using-firewalld-centos-7). I ran these commands, retested the ping and it worked

```
sudo firewall-cmd --add-masquerade --zone=public --permanent
sudo firewall-cmd --reload
```

And after testing my application-specific code, I see that it is also working.

One for the books.

**Comment by dtrudg** [comment]
Ahh - see also https://github.com/hpcng/singularity/issues/5840
