### ISSUE TITLE
Compilation warning on setfsuid(uid) in starter.c

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#5874]
### Version of Singularity:

3.7.2

### Expected behavior

Warning-free compilation

### Actual behavior

This compilation warning:

```
In file included from ../cmd/starter/main_linux.go:12:0:
../cmd/starter/c/starter.c: In function 'priv_escalate':
../cmd/starter/c/starter.c:123:17: warning: ignoring return value of 'setfsuid', declared with attribute warn_unused_result [-Wunused-result]
         setfsuid(uid);
                 ^
```

It's odd because this is the only warning I see, I don't remember noticing it before, but this code hasn't changed in two years.

### Steps to reproduce this behavior

build on centos7

### What OS/distro are you running

centos7

### How did you install Singularity

Building from source with mconfig options `--without-suid --without-seccomp`.

**Comment by dtrudg** [comment]
@DrDaveD - it's known that specific versions of gcc raise this warning.... not all versions. 

It's a call that has a pretty useless return....

```
RETURN VALUE
       On both success and failure, this call returns the previous filesystem user ID of the caller.
```

**Comment by DrDaveD** [comment]
Yeah so the warning should be able to be removed with a `(void)` cast.

**Comment by dtrudg** [comment]
Maybe.. looking around (qemu mailing list and some others) apparently there are some situations where the ignore of the return check is more aggressive. We might put in an empty `if(x) { }` to be safe.

Interestingly it looks like this warning came in around Fedora 17... but it doesn't happen in current Fedora :-)

**Comment by michaelkarlcoleman** [comment]
The man page I looked at (https://linux.die.net/man/2/setfsuid) is a bit confusing, as it seems to indicate that either the current fsuid or -1 could be returned on error.  In any case, it seems like a bad idea to ignore the return value unless the effectiveness of the call is truly irrelevant.

"On success, the previous value of fsuid is returned. On error, the current value of fsuid is returned. ... When glibc determines that the argument is not a valid user ID, it will return -1 and set errno to EINVAL without attempting the system call."

**Comment by dtrudg** [comment]
> The man page I looked at (https://linux.die.net/man/2/setfsuid) is a bit confusing, as it seems to indicate that either the current fsuid or -1 could be returned on error. In any case, it seems like a bad idea to ignore the return value unless the effectiveness of the call is truly irrelevant.
> 
> "On success, the previous value of fsuid is returned. On error, the current value of fsuid is returned. ... When glibc determines that the argument is not a valid user ID, it will return -1 and set errno to EINVAL without attempting the system call."

Yes it's a bit confusing. In the code we do this:

```
        setfsuid(uid);
        if ( setfsuid(uid) != uid ) {
            fatalf("Failed to set filesystem uid to %d\n", uid);
        }
```

If the first call was successful the second call is an effective no-op and will return 'the previous value of fsuid' which is `uid` as was set by the first call... so we verify we did get to `uid` and anything else is a a fatal error.

NB - the die.net manpage doesn't match what `man 2 setfsuid` gives from current man pages on an up-to-date Linux system, which is:

```
RETURN VALUE
       On  both success and failure, this call returns the previous filesystem
       user ID of the caller.
```

But with the caveat that...

```
   C library/kernel differences
       In glibc 2.15 and earlier, when the wrapper for this system call determines that the argument can't be passed to the
       kernel without integer truncation (because the kernel is old and does not support 32-bit user IDs), it  will  return
       -1 and set errno to EINVAL without attempting the system call.
```

I'm now at glibc 2.33 on this machine so the above doesn't apply.

**Comment by michaelkarlcoleman** [comment]
Have to admit, I'm not spotting the advantage of calling twice, but as long as errors are being checked, I'm happy.

**Comment by dtrudg** [comment]
(Sorry - somehow I edited last comment instead of replying originally)

Just writing the following out here so I can try and get down to some succinct clear commentary in the code to clarify when the return is checked, as this isn't obvious.

> RETURN VALUE
       On  both success and failure, this call returns the previous filesystem
       user ID of the caller.
      
Consider...

Previous uid = 100
We want to set uid = 1000

If the first call to setfsuid(1000) fails it returns the previous uid (100). If it succeeds it also returns the previous uid (100). The return of -1 is only for glibc < 2.15 which is no longer in use. So - we can't tell from the return code if it succeeded or failed.

If the first call succeeded our current fsuid is now 1000. We call setfsuid again and it'll return 1000 (the value prior to the second call)... so we know it worked. 

If the first setfsuid call failed our current fsuid is still 100 - we call setfsuid again at it'll return 100 (the value prior to the second call)... so we know it failed.

Maybe instead reference the `BUGS` section in up-to-date man pages which explicitly states the need to call twice:

```
BUGS
       No error indications of any kind are returned to the caller, and the fact that both successful  and  unsuc‐
       cessful calls return the same value makes it impossible to directly determine whether the call succeeded or
       failed.  Instead, the caller must resort to looking at the return value from a further call such  as  setf‐
       suid(-1)  (which  will  always  fail),  in order to determine if a preceding call to setfsuid() changed the
       filesystem user ID.
```

**Comment by michaelkarlcoleman** [comment]
@dtrudg You're clearly all over this.  Kind of surprised that the kernel/libc interface is such a mess, but there it is.

For completeness, you could do the cast-to-void thing and maybe add a comment describing the mess, but that'd be a bonus.
