### ISSUE TITLE
Singularity remote build fails on host

### ISSUE THREAD

**Issue by dmey** [apptainer/singularity#5877]
Not sure if this is the right place to post this but I am having issue with the remote build service (https://cloud.sylabs.io) since yesterday. Request a standard remote build job returns

```
Post "http://exiled-chipmunk-token-service:5052/v1/token/new": dial tcp: lookup exiled-chipmunk-token-service on 172.20.0.10:53: no such hostFATAL:   While performing build: build image size <= 0
```
running on singularity version 3.5.3. Any ideas if this is being taken care or who to speak to?

**Comment by dtrudg** [comment]
Hi @dmey - certainly there is something wrong here and we are looking into it.

Note that the cloud.sylabs.io offering is separate from the open source Singularity project. Please report issues to support@sylabs.io - thanks!

**Comment by dtrudg** [comment]
@dmey - the issue has been addressed. Please let us know at support@sylabs.io if you have any further problems.
