### ISSUE TITLE
Build-temp not cleaned up when cancelling build during pacstrap phase

### ISSUE THREAD

**Issue by LukeLR** [apptainer/singularity#5878]
### Expected behavior

When cancelling a build of an "arch" bootstrapped image during first initialization (`pacstrap` phase) using Ctrl+C, the `build-temp`-directory in `/tmp` should get removed.

### Actual behavior

After pressing Ctrl+C, the console is flooded with messages like:

```
Error setting permissions to remove /tmp/build-temp-195703658/rootfs/proc/288385/task/288385/fd: chmod /tmp/build-temp-195703658/rootfs/proc/288385/task/288385/fd: operation not permitted
```

`rm -rf /tmp/build-temp-*` fails with similar messages.

### Steps to reproduce this behavior

- Create a new container with `bootstrap: arch` using `singularity build`
- Cancel the build immediately

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

### How did you install Singularity

Using `pacman` (Arch Linux package manager)

**Comment by dtrudg** [comment]
Please could you provide full output from running Singularity with the `-d` debug flag so that we are able to see where this is occurring, and exactly what binds are happening etc.

`singularity -d build ....`

It seems as though when pacstrap is killed here a /proc remains mounted - some manual cleanup may be necessary that isn't for debootstrap etc.

Arch Linux is generally not a heavily tested host platform given the usual deployment targets of Singularity, so any PR contributions towards a fix would be extremely welcome.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by dmacguigan** [comment]
Hello, was there ever a solution to this issue? I have encountered the same problem, although I am working on Ubuntu.
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
Here is the debug output
```
$ sudo singularity -d build --sandbox test genome-annotation.def 
DEBUG   [U=0,P=1802723]    persistentPreRun()            Singularity version: 3.11.1
DEBUG   [U=0,P=1802723]    persistentPreRun()            Parsing configuration file /usr/local/etc/singularity/singularity.conf
DEBUG   [U=0,P=1802723]    handleConfDir()               /root/.singularity already exists. Not creating.
DEBUG   [U=0,P=1802723]    Init()                        Image format detection
DEBUG   [U=0,P=1802723]    Init()                        Check for sandbox image format
DEBUG   [U=0,P=1802723]    Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=1802723]    Init()                        Check for sif image format
DEBUG   [U=0,P=1802723]    Init()                        sif format initializer returned: SIF magic not found
DEBUG   [U=0,P=1802723]    Init()                        Check for squashfs image format
DEBUG   [U=0,P=1802723]    Init()                        squashfs format initializer returned: while parsing squashfs super block: not a valid squashfs image
DEBUG   [U=0,P=1802723]    Init()                        Check for ext3 image format
DEBUG   [U=0,P=1802723]    Init()                        ext3 format initializer returned: file is not a valid ext3 image
DEBUG   [U=0,P=1802723]    getCacheParentDir()           environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=0,P=1802723]    Init()                        Image format detection
DEBUG   [U=0,P=1802723]    Init()                        Check for sandbox image format
DEBUG   [U=0,P=1802723]    Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=1802723]    Init()                        Check for sif image format
DEBUG   [U=0,P=1802723]    Init()                        sif format initializer returned: SIF magic not found
DEBUG   [U=0,P=1802723]    Init()                        Check for squashfs image format
DEBUG   [U=0,P=1802723]    Init()                        squashfs format initializer returned: while parsing squashfs super block: not a valid squashfs image
DEBUG   [U=0,P=1802723]    Init()                        Check for ext3 image format
DEBUG   [U=0,P=1802723]    Init()                        ext3 format initializer returned: file is not a valid ext3 image
DEBUG   [U=0,P=1802723]    newBundle()                   Created temporary directory "/tmp/bundle-temp-3804993407" for the bundle
DEBUG   [U=0,P=1802723]    newBundle()                   Created directory "/home/krablab/Documents/MacGuigan_data/genome-annotation/build-temp-1348135171/rootfs" for the bundle
INFO    [U=0,P=1802723]    Full()                        Starting build...
DEBUG   [U=0,P=1802723]    findOnPath()                  Found "debootstrap" at "/usr/sbin/debootstrap"
DEBUG   [U=0,P=1802723]    Get()                         
	Debootstrap Path: /usr/sbin/debootstrap
	Includes: apt(default),
	Detected Arch: amd64
	OSVersion: jammy
	MirrorURL: http://us.archive.ubuntu.com/ubuntu/
```

When I attempt to cancel the build with Ctrl+C, I get a ton of error messages like this:

```
ERROR   [U=0,P=1802723]    func1()                       Error setting permissions to remove /home/krablab/Documents/MacGuigan_data/genome-annotation/build-temp-1348135171/rootfs/sys/kernel/security: chmod /home/krablab/Documents/MacGuigan_data/genome-annotation/build-temp-1348135171/rootfs/sys/kernel/security: operation not permitted
ERROR   [U=0,P=1802723]    func1()                       Error setting permissions to remove /home/krablab/Documents/MacGuigan_data/genome-annotation/build-temp-1348135171/rootfs/sys/kernel/tracing: chmod /home/krablab/Documents/MacGuigan_data/genome-annotation/build-temp-1348135171/rootfs/sys/kernel/tracing: operation not permitted
ERROR   [U=0,P=1802723]    ForceRemoveAll()              18874 errors were encountered when setting permissions to remove bundle
ERROR   [U=0,P=1802723]    cleanUp()                     Could not remove bundle: could not remove "/home/krablab/Documents/MacGuigan_data/genome-annotation/build-temp-1348135171": unlinkat /home/krablab/Documents/MacGuigan_data/genome-annotation/build-temp-1348135171/rootfs/sys/kernel/notes: operation not permitted
```

**Comment by DrDaveD** [comment]
This repository is closed.  Since you are using version 3.11.1 you must be using singularity-ce so please make a new issue in https://github.com/sylabs/singularity.

**Comment by stela2502** [comment]
Hi you. We have the same issue here. build-temp-<id> folder can not be removed.
The folder has a drwx--- root root ACL but not even a sudo rm -Rf <folder> does clear it out.
Access denied.
So then we tried as real root user using sudo su. Becoming root worked, but removing the folder did not - same error.
Do you have any idea of why that could have happened?

We'll try to restart the computer showing the issues. Possibly a process has not shut down correctly?

**Comment by DrDaveD** [comment]
This repository is closed.  If the output of `singularity --version` says singularity-ce then please submit a new issue to https://github.com/sylabs/singularity, otherwise submit a new issue to https://github.com/apptainer/apptainer.

**Comment by stela2502** [comment]
Yes - I had read that before - and as it is actually apptainer we use as command it is clearly an issue that should be discussed here. Especially as google already indexed this place and therefore others could also see the results. I currently have no access to the other computer and therefore can not update on the matter.
But given the fact that the same error that has bugged a year ago still persists in rare occasions should make you think about it. At least recommend e.g. a restart of the computer here. I can not prove it helped as we forgot about that yesterday.

**Comment by DrDaveD** [comment]
Then please create a new issue at https://github.com/apptainer/apptainer.  This repository is closed.
