### ISSUE TITLE
Singularity remote config in play for other commands

### ISSUE THREAD

**Issue by rkalyanapurdue** [apptainer/singularity#5882]
### Version of Singularity: 

What version of Singularity are you using? Run:

```
$ singularity version

```
```
singularity version 3.6.2-1.el7
```

### Expected behavior

What did you expect to see when you do...?

We have our own Singularity registry at www.registry.geoedf.org. For one of our applications, we would like to share a remote config file among all users, and hence I am trying to set up one single Singularity remote config file in a shared read-only location (i.e., not $HOME/.singularity/remote.yaml for each user). For testing purposes, I wanted to try $HOME/remote.yaml instead of the default location. 

I see that you can use the _-c path_ option for all Singularity _remote_ commands and was able to successfully set the _active_ remote endpoint I wanted to use via the following (after copying remote.yaml from .singularity to the top-level home dir): 

```
singularity remote -c $HOME/remote.yaml add geoedf www.registry.geoedf.org
singularity remote -c $HOME/remote.yaml use geoedf
``` 

I now expected other Singularity commands (pull, push, etc.) to use this now active remote endpoint; however this does not seem to be the case.

### Actual behavior

What actually happend? Why was it incorrect?

For instance, when I try:

```
singularity remote pull library://geoedfproject/framework/workflowutils:latest
```

I get the following error:

```
FATAL:   While pulling library image: error fetching image: image does not exist in the library: geoedfproject/framework/workflowutils:latest (amd64)
```

This works fine if I use the default remote config file at $HOME/.singularity. 

Am I incorrect in assuming that overriding the remote config file would take effect on other Singularity commands as well?

Appreciate any insight or feedback on this!

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release


```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

**Comment by dtrudg** [comment]
Using `-c` with the remote command only applies for the specific command you are running. Doing a `remote -c xxx use xxxx` will set the remote active in the specified config file, but `pull` etc. won't use that config file. This is a little bit odd... maybe @cclerget or @ikaneshiro can give an idea on why `-c` exists? We probably use it for test purposes... and maybe it shouldn't be a public option if that's the only purpose?

What you probably need to do here is configure a global remote, that is accessible to users system-wide.

```
sudo singularity remote add --global ...
```

Take a look at: https://sylabs.io/guides/3.7/admin-guide/configfiles.html#remote-yaml

**Comment by rkalyanapurdue** [comment]
Thanks so much for the pointer to global remote, David! that seems to work for my needs!

Keeping the thread open just for the confirmation on the intent behind remote -c

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
