### ISSUE TITLE
Sending SIGINT to the container leaves behind orphaned processes on the host

### ISSUE THREAD

**Issue by lgorenstein** [apptainer/singularity#5884]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.6.4-1.el7
```

### Expected behavior

After a `singularity run` exits, no leftover processes should stay on the host.  No extraneous `--pid` should be necessary to prevent them.

### Actual behavior

Sometimes if the container run is interrupted (e.g. Ctrl-C'd), it leaves behind some of this processes (mpiexec.hydra, or python, etc). Adding a `--pid` flags prevents this, but this workaround feels like an unnecessary extra.  Behavior observed in several NGC containers and [reported](https://github.com/NVIDIA/ngc-container-environment-modules/issues/4) to the NGC Container Modules repository, but this looks more like a Singularity issue.

### Steps to reproduce this behavior

Using one of the [RAPIDS AI NGC containers](https://ngc.nvidia.com/catalog/containers/nvidia:rapidsai:rapidsai) as an example:

```
$ singularity pull docker://nvcr.io/nvidia/rapidsai/rapidsai:0.17-cuda11.0-runtime-ubuntu18.04
INFO:    Converting OCI blobs to SIF format
.....

$ env TINI_SUBREAPER=1 \
   singularity run --nv rapidsai_0.17-cuda11.0-runtime-ubuntu18.04.sif \
     jupyter notebook --ip 0.0.0.0 --no-browser --notebook-dir /rapids/notebooks
   .... Jupyter starts ....
   .... Open the browser, use the notebook, everything's great ....
```

At this point if I hit Ctrl-C, everything shuts down as expected and I get my prompt back.
But there are ghosts left behind:
```
$ ps uxww | grep '[c]onda'
lev      231537  0.3  0.0 2675556 78552 pts/104 S    17:05   0:02 /opt/conda/envs/rapids/bin/python3.7 /opt/conda/envs/rapids/bin/jupyter-lab --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token=
```

Starting the container with `..... run --nv --pid ......` fixes the problem and eliminates ghost processes.  But ideally the `--pid` should not be necessary, should it?

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

Installed from an RPM.

**Comment by dtrudg** [comment]
I haven't been able to replicate this across a few quick runs with Singularity 3.7.1 on my system - please could you check with that latest version.

Also, what is the reasoning here for `env TINI_SUBREAPER=1` ? If tini is being used, is it set to kill the whole process group?

https://github.com/krallin/tini#process-group-killing

**Comment by lgorenstein** [comment]
Checking with 3.7.1 might be a bit difficult (this is on an HPC cluster where updates are slow).

The reason for `TINI_SUBREAPER=1` was to faithfully reproduce the environment inside an NGC Container Module (as I have reported the same problem to the module maintainer).  From poking into `/singularity` inside the container, doesn't look that tini is started with '-g' by default.  However, the leftover processes stay behind even when I start the container with `env TINI_SUBREAPER=1 TINI_KILL_PROCESS_GROUP=1` to force the group-killing behavior.

**Comment by dtrudg** [comment]
Okay - wasn't looking properly. I can replicate it, even bypassing tini and just execing the `/opt/docker/bin/entrypoint` script without any args...

```
05:41 PM $ singularity exec rapidsai_0.17-cuda11.0-runtime-ubuntu18.04.sif /opt/docker/bin/entrypoint
A JupyterLab server has been started!
To access it, visit http://localhost:8888 on your host machine.
Ensure the following arguments were added to "docker run" to expose the JupyterLab server to your host machine:
      -p 8888:8888 -p 8787:8787 -p 8786:8786
Make local folders visible by bind mounting to /rapids/notebooks/host

05:41 PM $ ps
    PID TTY          TIME CMD
 183591 pts/0    00:00:00 bash
 187370 pts/0    00:00:00 jupyter-lab
 187373 pts/0    00:00:00 node
 187379 pts/0    00:00:00 ps
```

Diving deeper that entrypoint is calling an entrypoint_source script...

```
5:42 PM $ singularity exec rapidsai_0.17-cuda11.0-runtime-ubuntu18.04.sif cat /opt/docker/bin/entrypoint_source
#!/bin/bash

# Run Jupyter in foreground if $JUPYTER_FG is set
if [[ "${JUPYTER_FG}" == "true" ]]; then
   jupyter-lab --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token=''
   exit 0
else
   nohup jupyter-lab --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token='' > /dev/null 2>&1 &

   echo "A JupyterLab server has been started!"
   echo "To access it, visit http://localhost:8888 on your host machine."
   echo 'Ensure the following arguments were added to "docker run" to expose the JupyterLab server to your host machine:
      -p 8888:8888 -p 8787:8787 -p 8786:8786'
   echo "Make local folders visible by bind mounting to /rapids/notebooks/host"
fi
```

By default that is starting the jupyter-lab with nohup and in the background. When Singularity is not using `--pid` it is in the host pid namespace... the container processes are not directly off of a singularity controlled pid 1, and the nohup'd background process is not going to get killed.

I don't really see a way around this, as the container seems to be going out of its way to run a jupyter-lab that is detached from things that would kill it.

**Comment by lgorenstein** [comment]
Yep, makes total sense.  Thank you David!

**Comment by dtrudg** [comment]
@lgorenstein - I'm going to close this one as I don't think there is anything to do on our side here. Please feel free to re-open if there's anything further to mention here though. Thanks!
