### ISSUE TITLE
Ignore failed mount

### ISSUE THREAD

**Issue by mbhall88** [apptainer/singularity#5887]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.7.0
```

### Expected behavior

When trying to bind a path that doesn't exist, it would be great to be able to pass a flag that says to ignore errors caused by the mount source not existing. i.e. something like

```
singularity exec --ignore-mount-fail -B /doesnt/exist <img> <cmd>
```

This is of particular interest to me as I have some snakemake pipelines that use singularity to execute a variety of jobs. Some jobs are run on GPU compute nodes, where cuda is available, but not so on some others.

### Actual behavior

At the moment you get something like the following

```
WARNING: skipping mount of /usr/local/cuda: stat /usr/local/cuda: no such file or directory
FATAL:   container creation failed: mount /usr/local/cuda->/usr/local/cuda error: while mounting /usr/local/cuda: mount source /usr/local/cuda doesn't exist
```

**Comment by dtrudg** [comment]
Singularity previously ignored more failing bind mounts, but there was a conscious change to the current behavior, that anything explicitly requested should fail if not present. Therefore this is unlikely to be a priority for feature work.

A workaround I've seen in workflows (admittedly nextflow, not snakemake) is to test for a directory existence before executing Singularity.... though I'm not sure this is possible in all ways workflow managers execute singularity.

We might consider a PR that did something like add an option e.g. `/doesn/exist:nofail` on a per-mount basis. A broad flag like `--ignore-mount-fail` isn't something I'd personally support as it infers ignoring all failures, even of system mounts that are required for proper container functionality.

Tagging @cclerget for any comment here.

**Comment by mbhall88** [comment]
> A workaround I've seen in workflows (admittedly nextflow, not snakemake) is to test for a directory existence before executing Singularity.... though I'm not sure this is possible in all ways workflow managers execute singularity.

Yeah, ideally snakemake would allow setting singularity binds on a per-rule basis, this is a [current feature request](https://github.com/snakemake/snakemake/issues/262) there, but has been open for a long time.

It makes sense for the per-mount option you mentioned. Wouldn't this prevent specifying the location of the mount in the container though (at least in the example you gave)?

**Comment by dtrudg** [comment]
Sorry, it'd be something like `/src:/dst:nofail` much as for read-only you can do `-B /tmp:/bob:ro` now.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by mbhall88** [comment]
I would say option 2 or 3 I guess
