### ISSUE TITLE
Is it possible to run an instance command as a background process without output redirection?

### ISSUE THREAD

**Issue by briveramelo** [apptainer/singularity#5891]
## Is it possible to run an instance command as a background process without output redirection?

 - [ X ] I found the documentation at https://singularityhub.github.io/singularity-cli/
 - [ X ] The documentation does not answer my question

The user-guide suggests something like this:
`nohup npm start > /dev/null 2>&1 < /dev/null &`
[https://sylabs.io/guides/3.7/user-guide/running_services.html](https://sylabs.io/guides/3.7/user-guide/running_services.html)
 
This works fine for me when I'm just running a single container instance, and it even works fine when I'm running one container after another as with a db and web server. The problem I encounter with this approach is that I'm running it through singularity-compose: [https://github.com/singularityhub/singularity-compose/issues/43](https://github.com/singularityhub/singularity-compose/issues/43) 
 
As you might imagine, there are some issues with programmatically parsing command line redirects and applying them to the previous command appropriately.

If this is possible through the singularity cli, is it an option I can pass? If there is such an option or an alternate, there may be an easy way to integrate this option with singularity-compose. 

If not, there's a bit of work needed to run multiple containers in succession on the singularity-compose side of things

**Comment by dtrudg** [comment]
I'm not familiar with how `singularity-compose` works, but when running in an instance the `nohup` and input direction shouldn't be required if the program expects to be run as a service in the foreground. `singularity instance start` will start the `%startscript` and redirect output and error to log files. It won't block, but will exit immediately.

We need to revisit the guide... there may be a specific reasons to nohup and redirect for this particular example app, but generally it should not be required. E.g. if you `singularity instance start` the nginx example it will start, and be detached, it will not block. There is no need to nohup, background, or redirect on the nginx process.

**Comment by briveramelo** [comment]
I just tested that out and it worked as you described.

Part of the confusion with this approach for me came from the fact that I'm starting with docker images and rebuilding them as .sif images. In this conversion process, the generated runscript handles the docker entrypoint / commands, but the startscript is left as an empty shell script with just a shebang '!/bin/bash'. In order for me to take advantage of this implicit backgrounding, I must
1. Know that backgrounding occurs for the startscript
2. Copy the contents of the runscript to the startscript or otherwise update the startscript to run my intended commands

It may help to 
1. add some documentation for point 1 and 
2. expose some build options for docker images which allow setting the startscript or runscript to hold the entrypoint/commands.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by briveramelo** [comment]
1. To my knowledge, this has not been addressed
2. I believe this is still relevant to the current state, yes
3. Yes
