### ISSUE TITLE
Mac: setting hostname

### ISSUE THREAD

**Issue by philrasch** [apptainer/singularity#5894]
I want to be able to set the hostname, either at the command line, or in the definition file.  I can do this when running singularity on a linux box, but my tests fail when using the same sif file on a mac. I am aware the mac software is a beta release, so I am posting the issue thinking it is a bug, and I know it may not be fixed quickly.

Anyway, the test is to create a container built with this definition file (simple.def)
```
Bootstrap: library
From: ubuntu:18.04

%post
    hostname test
    echo "test" > /etc/hostname
```
The intention is to set the hostname to "test" when the container is started like this
```singularity shell simple.sif```

The failure is demonstrated by executing the following commands for **test#1**

```
Singularity simple.sif:~> hostname
(none)
Singularity simple.sif:~> cat /etc/hostname
test
```
Alternately, starting the shell this way for **test#2**
```singularity shell --hostname xxx simple.sif```

Might be expected to set the hostname to xxx, but the result is the same. I am aware that the --hostname argument is not accepted for the mac version of singularity, but it might also be useful to test when the problems are being addressed.

### Version of Singularity:

What version of Singularity are you using? Run:

On the mac
```
$ singularity version
3.3.0-rc.1.658.g7427b73f1.dirty
```

### Expected behavior

test#1 should return the string "test" when the command `hostname` is executed

test#2 should return the string "xxx" when the command `hostname` is executed

### Actual behavior

**test#1** returned the string "(none)" when the command `hostname` is executed

**test#2** returned the string "(none)" when the command `hostname` is executed

What actually happend? Why was it incorrect?

### Steps to reproduce this behavior

I think I have described the steps, but please let me know if I messed up

How can others reproduce this issue/problem?

Create the container,  run the commands in test#1 and test#2
### What OS/distro are you running

MacOS 10.14.6

```
$ cat /etc/os-release
sif file created on ubuntu 20.04

```

### How did you install Singularity
Singularity installed from DMG file on MacOS
Singularity 3.7.2 from github source on ubuntu

**Comment by dtrudg** [comment]
The Mac version is currently unmaintained, per the notice on the Sylabs website:

>Please Note - Singularity Desktop for macOS is a Beta release, and has not been updated for compatibility with the new SIF signature format in Singularity 3.6.0.

>Sylabs™ is currently engaging with the community to plot a course for the future of the Mac version of Singularity. In the meantime, please be aware that the release has not received recent security and bug fixes, and should be used at your own risk.

At this time it is not expected that it will be updated.

**Comment by dtrudg** [comment]
See also this thread: https://groups.google.com/a/lbl.gov/g/singularity/c/MSsOy6TkkQY

**Comment by philrasch** [comment]
Thanks Dave. I am sorry that a path forward wasn't obvious or easy, and I hope hpcng are interested.  It might be worthwhile to update your page for the mac download to communicate this newer situation. The statements on the current page might lead some of us to feel more optimistic than we should be about singularity as a long term solution for the mac.
