### ISSUE TITLE
libexec/singularity/functions: line 73: syntax error: unexpected redirection (running singularity on alpine linux)

### ISSUE THREAD

**Issue by truatpasteurdotfr** [apptainer/singularity#59]
> alpine:~/singularity$ sudo singularity bootstrap a.img examples/debian.def 
> /usr/local/libexec/singularity/bootstrap.sh: /usr/local/libexec/singularity/functions: line 73: syntax error: unexpected redirection
> 
> alpine:~/singularity$ sed -n 69,78p /usr/local/libexec/singularity/functions
> get_key_from_conf() {
>     KEY="$1"
>     FILE="$2"
>     if OUT=`egrep -i "^$KEY:\s*" $FILE`; then
>         head -n 1 <<< "$OUT" | sed -e "s@^$KEY:\s*@@i"
>         return 0
>     fi
>     return 1
> }

alpine linux provides debootstrap, hence my test of bootstrap.

**Comment by gmkurtzer** [comment]
I am assuming that Alpine's Busybox sh/bash doesn't support <<<, but I used it to avoid using echo. hrmmmmmmm... Do me a favor, try to do this and let me know if it works:

$ git revert --no-commit a333cd59

**Comment by truatpasteurdotfr** [comment]
puzzled:
`[tru-alpine-3.4-x86_64 singularity]$ sed -n -e 73p /usr/local/libexec/singularity/functions`
`echo "$OUT" | head -n 1 | sed -e "s@^$KEY:\s*@@i"`

`[tru-alpine-3.4-x86_64 singularity]$  sudo singularity bootstrap a.img examples/debian.def 
/usr/local/libexec/singularity/bootstrap.sh: /usr/local/libexec/singularity/functions: line 1: syntax error: unexpected redirection`

**Comment by gmkurtzer** [comment]
What is at line 1 of functions?

**Comment by truatpasteurdotfr** [comment]
just #!/bin/bash

there is another <<< on line 209 of libexec/functions

**Comment by truatpasteurdotfr** [comment]
that was it:
209 ->  for o in `echo "$1"| sed 's/^-//' | sed 's/./-& /g'`; do

**Comment by gmkurtzer** [comment]
Ahh, excellent find. Can you send me a PR for both the revert and this fix?

Thank you!

**Comment by gmkurtzer** [comment]
@truatpasteurdotfr Can you also check to see if this is still an issue?

Thanks!

**Comment by truatpasteurdotfr** [comment]
yes, it is still bombing on alpine:

alpine:~/singularity$ sudo singularity bootstrap a.img examples/debian.def 
/usr/local/libexec/singularity/bootstrap.sh: /usr/local/libexec/singularity/functions: line 1: syntax error: unexpected redirection
alpine:~/singularity$ grep -n -- <<< /usr/local/libexec/singularity/functions 
209:                for o in `sed 's/^-//' <<< "$1" | sed 's/./-& /g'`; do

fixed:
alpine:~/singularity$ sed -n 209p /usr/local/libexec/singularity/functions
                for o in `echo "$1"| sed 's/^-//' | sed 's/./-& /g'`; do

**Comment by gmkurtzer** [comment]
Committed in master d0b5157.

Thanks!

**Comment by gmkurtzer** [comment]
@truatpasteurdotfr _poke_

**Comment by gmkurtzer** [comment]
@truatpasteurdotfr I am going to close this, but if necessary I will reopen upon followup comment.

Thanks!
