### ISSUE TITLE
no space left on device when creating SIF file

### ISSUE THREAD

**Issue by lifan18** [apptainer/singularity#5901]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.7.0
```

`singularity build trinityrna.sif docker://trinityrnaseq/trinityrnaseq`

### Expected behavior

What did you expect to see when you do...?
I expect to create SIF successfully.

### Actual behavior

What actually happend? Why was it incorrect?

`FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: while creating SIF: while creating container: writing data object for SIF file: copying data object file to SIF file: write /large_file/vagrant/.singularity/cache/oci-tmp/tmp_160406455: no space left on device`

failed to create SIF file

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
`singularity build trinityrna.sif docker://trinityrnaseq/trinityrnaseq` by vagrant on MacOS

In the visual machine, I was following the default settings, 

`$HOME/.singularity/cache/library
$HOME/.singularity/cache/oci
$HOME/.singularity/cache/oci-tmp`

it occurred this fatal error, then I guess it because the home directory has no much memory for user. So I specified those path to root directory by export SINGULARITY_CACHEDIR=/large_file and so on. However, this fatal error also occurred. 

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

on MacOS
`export VM=sylabs/singularity-3.5-ubuntu-bionic64 && \
    vagrant init $VM && \
    vagrant up && \
    vagrant ssh`

**Comment by dtrudg** [comment]
It seems to be writing to the correct place, as stated in the error message.

```
write /large_file/vagrant/.singularity/cache/oci-tmp/tmp_160406455: no space left on device
```

The vagrant image does not have a separate `$HOME` and the virtual disk is probably not large enough to build very large images in, and trinity is multiple GBs. You would need to increase the size of the disk in the image.

See: https://www.vagrantup.com/docs/disks/usage

**Comment by lifan18** [comment]
Hi,

Good day! Thank you for your answer. It saved my day. Although I have resized the disk from 20GB to 50Gb using this command `config.vm.disk :disk, size: "50GB", primary: true`, it still reported the same error below.

`INFO:    Creating SIF file...
FATAL:   While performing build: while creating SIF: while creating container: writing data object for SIF file: copying data object file to SIF file: write /fan_large/trinityrna.sif: no space left on device`

The viItualBox Manager shows 50GB, but it still cannot write over 20GB.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/44634495/113720188-f6c84600-9720-11eb-838d-88e3c9906e5f.png">

With Best Regards,

Fan

**Comment by lifan18** [comment]
Hi Sir, Good morning! 

FYR, I put the disk information here. Whatever I resized it to 50GB or 70GB, the disk actually cannot over 20GB.


```
vagrant@vagrant:~$ df -h
Filesystem                    Size  Used Avail Use% Mounted on
udev                          464M     0  464M   0% /dev
tmpfs                          99M  532K   99M   1% /run
/dev/mapper/vagrant--vg-root   19G  2.3G   16G  13% /
tmpfs                         493M     0  493M   0% /dev/shm
tmpfs                         5.0M     0  5.0M   0% /run/lock
tmpfs                         493M     0  493M   0% /sys/fs/cgroup
vagrant                       234G  145G   90G  62% /vagrant
tmpfs                          99M     0   99M   0% /run/user/900
```

Thank you very much!

Best

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
