### ISSUE TITLE
O_PATH undeclared using Centos6

### ISSUE THREAD

**Issue by chrisreidy** [apptainer/singularity#5910]
Is there a workaround for Centos 6.10 to update to Singularity 3.7.3?

### Version of Singularity:

What version of Singularity are you using? Run:

currently 3.6.4 
$ singularity version
upgrading to 3.7.3

unshare.c: In function ‘try_bindfd’:
unshare.c:196:23: error: ‘O_PATH’ undeclared (first use in this function)
  ret = open(template, O_PATH | O_CLOEXEC);

### Expected behavior

What did you expect to see when you do...?
Well it appears the kernel we have, 
kernel-2.6.32-754.35.1.el6.x86_64
is too old for O_PATH
We are upgrading this cluster in a few months, but really do not want to run without singularity until then

### Actual behavior

What actually happened? Why was it incorrect?

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release
CentOS release 6.10 (Final)

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
Source

**Comment by dtrudg** [comment]
CentOS 6 went out of support on 2020-11-30. We don't support building or using Singularity on it since that date, and newer versions of Singularity should be expected to use features unavailable in the old kernel.

**Comment by chrisreidy** [comment]
Understood.
