### ISSUE TITLE
Install Does Not Work on Linux

### ISSUE THREAD

**Issue by radiantone** [apptainer/singularity#5912]
Following the instructions here https://sylabs.io/guides/3.0/user-guide/installation.html

darren@phoenix:~$ go get -u github.com/golang/dep/cmd/dep
# github.com/golang/dep/gps
go/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:103:21: cannot use sv (type *semver.Version) as type semver.Version in field value
go/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:122:16: invalid type assertion: c.(semver.Version) (non-interface type *semver.Constraints on left)
go/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:149:4: undefined: semver.Constraint
darren@phoenix:~$ go get -d github.com/sylabs/singularity
darren@phoenix:~$ ls singularity
ls: cannot access 'singularity': No such file or directory
darren@phoenix:~$ 

Doesn't install anything.

**Comment by dtrudg** [comment]
The 3.0 instructions are for a very old version. See updated instructions for the 3.7 series.

https://sylabs.io/guides/3.7/user-guide/quick_start.html#quick-installation-steps
