### ISSUE TITLE
How to execute a binary inside the build file (sif) which depends on files next to it?

### ISSUE THREAD

**Issue by Eisbrenner** [apptainer/singularity#5920]
### Version of Singularity:

```
$ singularity version
3.0.3-1
```

### My question

I like to have a container (not sure about the terminology yet) which runs a compiled fortran code using locally provided settings and save output to the host system.

I have a working example with Docker, however, on  the HPC system Singularity provided (for good reasons); but I struggle to understand how things are organized within Singularity.

I have a compiled version of the fortran code in `my.sif` build from `my.def`. Inside, located at `${SINGULARITY_ROOTFS}/MyRepo`, I have the executable `runfile` binary to run the fortran code.

Now, when I try
```
singularity run my.sif -c "${SINGULARITY_ROOTFS}/MyRepo/runfile"
```
I get back errors since the `runfile` binary can't find it's dependencies, which are located at `${SINGULARITY_ROOTFS}/MyRepo` too.

I obviously missed a part in the docs here, but I had no luck so far to find the missing piece.

Also, from this point onward, I have not seen how actually extract the output of the code to the host system?

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

Using the [guide for mac](https://sylabs.io/guides/3.0/user-guide/installation.html#mac) to install it into a VM.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by Eisbrenner** [comment]
Yes I'd still like to get some input on this. I've abandoned Singularity again, since I haven't found an answer to this.

**Comment by Eisbrenner** [comment]
I think the mounting points documentation is insufficient, or there might even be a bug on how especially PWD is mounted. Either way, a working way around this is to disable automatic mounting and set all mounts on your own.

**Comment by DrDaveD** [comment]
First of all, please try using a more recent version of singularity.  singularity-3.0 was very early after the rewrite in go and had a lot of problems.  The current version is 3.8.0. 

Secondly, I don't fully understand your question but it sounds to me like you might just need to use more -B options to bind in the files you need from outside the container into it.
