### ISSUE TITLE
allowing user-bind paths that include colon in their names

### ISSUE THREAD

**Issue by arozenfe** [apptainer/singularity#5923]
### Version of Singularity:

```
$ singularity version
3.7.1-1
```

### Problem

Singularity cannot bind mount files or directory that include colon in their names. Currently singularity always identifies colons as delimiters.

We need some way to escape special characters like colon from the file/directory name we want to mount, in both the source and the destination.

### Steps to reproduce this behavior
```
$ ls -l /tmp/some:file
-rw-r--r-- 1 root root 0 Apr 12 07:00 /tmp/some:file

$ singularity exec -B /tmp/some:file image.sif /bin/bash
FATAL:   container creation failed: unable to add /tmp/some to mount list: destination must be an absolute path

$ singularity exec -B '/tmp/some\:file' image.sif /bin/bash
FATAL:   container creation failed: unable to add /tmp/some\ to mount list: destination must be an absolute path

$ singularity exec -B '/tmp/some\:file:/tmp/destfile' image.sif /bin/bash
FATAL:   while parsing bind path: while getting bind path: /tmp/destfile is not a valid bind option

```
We tried to add backslash and quotes in different combinations, but nothing worked.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by carterpeel** [comment]
Hi Arozenfe, 

with the current state of how Singularity handles bind paths, `:` is used as a delimiter.

I can attempt to change the regex that parses bind paths to allow for `:` following an "ignore the next character" verb, but that might cause problems for some.  

When you run `singularity exec -B /tmp/some:file image.sif /bin/bash`, it's interpreting that as "**/tmp/some --> file**". 
This will not work as `file` is not an absolute path, and `/tmp/some` does not exist.

**Comment by josefwells** [comment]
I'll note that docker solves this with a verbose --mount option:
https://github.com/moby/moby/issues/8604

As someone that lives in both worlds, it is nice when the approaches are at least similar.

You could probably use --fusemount and some kind of magic, but my preference is to advise people to not use colons in paths  :)
