### ISSUE TITLE
Singularity Built From NGC Base Yields "unable to find libcuda.so.1"

### ISSUE THREAD

**Issue by cupdike** [apptainer/singularity#5935]
```
$ singularity --version
singularity version 3.5.3
```
### Expected behavior
After building a sif off of a docker NGC base, cuda driver files should remain intact as they were on the docker image.
### Actual behavior
The cudu driver files are 0 bytes on the singularity image:

```
# Docker
$ srun --pty docker run -it --rm native_horovod_ray2 bash -c 'ls -al /usr/lib/x86_64-linux-gnu/libcuda.so*'
lrwxrwxrwx 1 root root       12 Apr 14 17:37 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       20 Apr 14 17:37 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.455.45.01
-rw-r--r-- 1 root root 16331696 Dec 27 19:02 /usr/lib/x86_64-linux-gnu/libcuda.so.418.181.07
-rwxr-xr-x 1 root root 21070200 Nov  5 23:13 /usr/lib/x86_64-linux-gnu/libcuda.so.455.45.01

# Singularity
$ singularity run native_horray2.sif bash -c 'ls -alL /usr/lib/x86_64-linux-gnu/libcuda.so*'
-rwxr-xr-x 1 root root 0 Apr 14 17:37 /usr/lib/x86_64-linux-gnu/libcuda.so
-rwxr-xr-x 1 root root 0 Apr 14 17:37 /usr/lib/x86_64-linux-gnu/libcuda.so.1
-rw-r--r-- 1 root root 0 Apr 14 17:37 /usr/lib/x86_64-linux-gnu/libcuda.so.418.181.07
-rwxr-xr-x 1 root root 0 Apr 14 17:37 /usr/lib/x86_64-linux-gnu/libcuda.so.455.45.01
```

### Steps to reproduce this behavior
```
cat Dockerfile
FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
CMD nvidia-smi

# TensorFlow version is tightly coupled to CUDA and cuDNN so it should be selected carefully
ENV TENSORFLOW_VERSION=2.3.2
ENV PYTORCH_VERSION=1.6.0
ENV TORCHVISION_VERSION=0.7.0
ENV CUDNN_VERSION=7.6.5.32-1+cuda10.1
ENV NCCL_VERSION=2.7.8-1+cuda10.1
ENV MXNET_VERSION=1.6.0.post0

ENV PYSPARK_PACKAGE=pyspark==2.4.7
ENV SPARK_PACKAGE=spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz

# Python 3.7 is supported by Ubuntu Bionic out of the box
ARG python=3.7
ENV PYTHON_VERSION=${python}

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        build-essential \
        cmake \
        g++-7 \
        git \
        curl \
        vim \
        wget \
        ca-certificates \
        libcudnn7=${CUDNN_VERSION} \
        libnccl2=${NCCL_VERSION} \
        libnccl-dev=${NCCL_VERSION} \
        libjpeg-dev \
        libpng-dev \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-dev \
        python${PYTHON_VERSION}-distutils \
        librdmacm1 \
        libibverbs1 \
        ibverbs-providers

RUN ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

# Install TensorFlow, Keras, PyTorch and MXNet
RUN pip install future typing packaging
RUN pip install tensorflow==${TENSORFLOW_VERSION} \
                keras \
                h5py

RUN PYTAGS=$(python -c "from packaging import tags; tag = list(tags.sys_tags())[0]; print(f'{tag.interpreter}-{tag.abi}')") && \
    pip install https://download.pytorch.org/whl/cu101/torch-${PYTORCH_VERSION}%2Bcu101-${PYTAGS}-linux_x86_64.whl \
        https://download.pytorch.org/whl/cu101/torchvision-${TORCHVISION_VERSION}%2Bcu101-${PYTAGS}-linux_x86_64.whl
RUN pip install mxnet-cu101==${MXNET_VERSION}

# Install Spark stand-alone cluster.
RUN wget --progress=dot:giga https://archive.apache.org/dist/spark/${SPARK_PACKAGE} -O - | tar -xzC /tmp; \
    archive=$(basename "${SPARK_PACKAGE}") bash -c "mv -v /tmp/\${archive/%.tgz/} /spark"

# Install PySpark.
RUN apt-get update -qq && apt install -y openjdk-8-jdk-headless
RUN pip install ${PYSPARK_PACKAGE}

# Install Open MPI
RUN mkdir /tmp/openmpi && \
    cd /tmp/openmpi && \
    wget https://www.open-mpi.org/software/ompi/v4.0/downloads/openmpi-4.0.0.tar.gz && \
    tar zxf openmpi-4.0.0.tar.gz && \
    cd openmpi-4.0.0 && \
    ./configure --enable-orterun-prefix-by-default && \
    make -j $(nproc) all && \
    make install && \
    ldconfig && \
    rm -rf /tmp/openmpi

RUN pip install ray

# Install Horovod, temporarily using CUDA stubs
RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MXNET=1 \
         pip install --no-cache-dir horovod[all-frameworks] && \
    ldconfig

# Install OpenSSH for MPI to communicate between containers
RUN apt-get install -y --no-install-recommends openssh-client openssh-server && \
    mkdir -p /var/run/sshd

# Allow OpenSSH to talk to containers without asking for confirmation
RUN cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

# Download examples
RUN apt-get install -y --no-install-recommends subversion && \
    svn checkout https://github.com/horovod/horovod/trunk/examples && \
    rm -rf /examples/.svn

WORKDIR "/examples"
```
docker build . --rm=false --tag native_horovod_ray2
singularity build native_horray2.sif native_horray2/
singularity build --sandbox native_horray2 docker-archive://native_horray2.tar
docker run -it --rm native_horovod_ray2 bash -c 'ls -al /usr/lib/x86_64-linux-gnu/libcuda.so*'
singularity run native_horray2.sif bash -c 'ls -alL /usr/lib/x86_64-linux-gnu/libcuda.so*'

### What OS/distro are you running
RHEL 7.9

### How did you install Singularity
From source using ansible, https://github.com/abims-sbr/ansible-singularity/blob/master/tasks/main.yml

**Comment by dtrudg** [comment]
I don't think there's any issue with Singularity here.

The docker base image `nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04` probably doesn't actually contain these basic low-level libcuda libraries.

The *real* libcuda libraries are mounted into the docker container at runtime, from the host... this is done by the NVIDIA container runtime when you are using Docker (and it has been configured to use the NVIDIA runtime). They have to be mounted in so that they match the host system's kernel driver version etc. If you looked at the container under docker on a non-GPU enabled system, that doesn't use the NVIDIA container runtime, you are likely to see the same as Singularity shows.

Singularity has a slightly different approach to handling NVIDIA CUDA. Its `--nv` option will bind the the required libraries under`/.singularity.d` and set the `LD_LIBRARY_PATH` appropriately.

You need to use the `--nv` option to run CUDA containers under Singularity. Please try `singularity run --nv ...`, and disregard what you see in `/usr/lib/x86_64-linux-gnu/libcuda.so*`. If the container works with `--nv` you are good to go... it's just a bit different to how docker with the NVIDIA container runtime sets things up.

**Comment by dtrudg** [comment]
See also: https://sylabs.io/guides/3.7/user-guide/gpu.html

**Comment by cupdike** [comment]
Yep, it's not a Singularity issue.  What I'm seeing doing a simple matmult using tensorflow is that singluarity works using the GPUs whether or not the `--nv` flag is provided--it's just that you get some apparently ignorable errors/warnings.  Apparently the framework I'm using is having issues with the GPUs.  Thanks!

**Comment by cupdike** [comment]
So I've instrumented things further and have clarified the issue.  If I do a simple GPU test in the __main__ part of the script, it runs as expected using the GPU.  But the __main__ starts another process using a callback defined in this same script.  If I repeat the GPU test in that callback, it fails there.

Is there something I can do to get the other process to run with the needed settings (like what --nv effectively does)?

**Comment by dtrudg** [comment]
> So I've instrumented things further and have clarified the issue. If I do a simple GPU test in the **main** part of the script, it runs as expected using the GPU. But the **main** starts another process using a callback defined in this same script. If I repeat the GPU test in that callback, it fails there.

This is when running with `--nv`? Any subprocess will need to be able to see the `LD_LIBRARY_PATH` environment variable. If the subprocess is called with a 'clean' environment it won't work.

**Comment by cupdike** [comment]
Yes, this is with the --nv.

`srun -u --nodes=1 --ntasks=1 --gres gpu:1 singularity run --nv ~/horovodDocker/native_horray2.sif python horray_mnist.py --address server1:6379`

Bu the library path doesn't seem to be the issue.  I just verified that LD_LIBRARY_PATH is the same in the main and in the subprocess and that the expected .singularity.d directory looks the same too:
```
LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
ls /.singularity.d: ['Singularity', 'actions', 'env', 'labels.json', 'libs', 'runscript', 'startscript']
```
Any ideas on other things I might check?

**Comment by cupdike** [comment]
I have positively identified a difference between the main and worker subprocesses.  The following are present on the filesystem when launched from the main process (but not present on the filesystem of the subprocesses):

```
 /usr/lib/x86_64-linux-gnu/:
lrwxrwxrwx  1 root root        29 Mar 15 18:13 libcudnn.so -> /etc/alternatives/libcudnn_so
lrwxrwxrwx  1 root root        32 Mar 15 18:13 libcudnn_static.a -> /etc/alternatives/libcudnn_stlib
-rw-r--r--  1 root root 403829728 Oct 27  2019 libcudnn_static_v7.a

Singularity> ls -al /etc/alternatives/libcud*
lrwxrwxrwx 1 root root 40 Mar 15 18:13 /etc/alternatives/libcudnn -> /usr/include/x86_64-linux-gnu/cudnn_v7.h
lrwxrwxrwx 1 root root 39 Mar 15 18:13 /etc/alternatives/libcudnn_so -> /usr/lib/x86_64-linux-gnu/libcudnn.so.7
lrwxrwxrwx 1 root root 46 Mar 15 18:13 /etc/alternatives/libcudnn_stlib -> /usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
```
@dtrudg Any thoughts on what the root cause or fix would be?  I can manually make these changes but I'm hoping there is a more fundamental fix.  Thanks...

**Comment by dtrudg** [comment]
I'm confused now to be honest what the difference is between the main process and the sub-process... but I don't think Singularity is doing anything strange here.

If the filesystem is different in a sub-process then it isn't just a straight sub-process launch.... but is maybe running in a different (possibly nested) container, or a separate Slurm task altogether? Is the sub-process launch calling Singularity or calling Slurm to srun itself etc?

`libcudnn` is *not* one of the basic low-level driver related CUDA libraries that Singularity would bind in from the host - it's something that should be installed in the container (as you have), and is then there as needed for anything running inside that container.

There is a lot of stuff to unpack here:

1. The `LD_LIBRARY_PATH` you mentioned has a `/usr/local/nvidia/lib` entry...
2. But...this is different from the libraries you are showing under `/usr/lib/x86_64-linux-gnu/` which are directed through `/etc/alternatives`
3. If the filesystem is different in the subprocess then it's not a simple execution in the same container, and we need to know exactly how it works to understand what is going on there.

**Comment by cupdike** [comment]
The main creates a RayExecutor which creates the worker process(es).  It does not use srun for that, and it is not aware of Singularity, but I don't know the details beyond that.
```
    ray.init(address=args.address, _redis_password=args.redis_password)
    settings = RayExecutor.create_settings(timeout_s=30)
    executor = RayExecutor(settings, num_hosts=1, num_slots=1, use_gpu=True, cpus_per_slot=4)
    executor.start()
    executor.run(train, kwargs=dict(num_epochs=5))
```
https://github.com/horovod/horovod/blob/master/horovod/ray/runner.py#L248

I'm looking at `/usr/lib/x86_64-linux-gnu` since that where the CUDA errors suggest it expects things:
```
(pid=37915) 2021-04-16 17:41:17.541528: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
(pid=37915) 2021-04-16 17:41:17.541546: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
```

There is no `/usr/local/nvidia` directory available in the container.

I'll try putting those links in manually and see what happens...

**Comment by cupdike** [comment]
@dtrudg  Am I wrong to expect that two runs of the same Singularity sif should have the same files present on the read-only overlay part of the file system?  Viz:

```
# Plain Singularity => libcudnn_static_v7.a is a true file
Singularity> ls -al /usr/lib/x86_64-linux-gnu/libcudnn*
lrwxrwxrwx 1 root root        29 Mar 15 18:13 /usr/lib/x86_64-linux-gnu/libcudnn.so -> /etc/alternatives/libcudnn_so
lrwxrwxrwx 1 root root        17 Oct 27  2019 /usr/lib/x86_64-linux-gnu/libcudnn.so.7 -> libcudnn.so.7.6.5
-rw-r--r-- 1 root root 428711256 Oct 27  2019 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
lrwxrwxrwx 1 root root        32 Mar 15 18:13 /usr/lib/x86_64-linux-gnu/libcudnn_static.a -> /etc/alternatives/libcudnn_stlib
-rw-r--r-- 1 root root 403829728 Oct 27  2019 /usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Singularity> touch  /usr/lib/x86_64-linux-gnu/test.txt
touch: cannot touch '/usr/lib/x86_64-linux-gnu/test.txt': Read-only file system

# Worker Subprocess ==> libcudnn_static_v7.a is not present
In [13]: ls -al /usr/lib/x86_64-linux-gnu/libcudnn*
lrwxrwxrwx 1 root root        17 Oct 27  2019 /usr/lib/x86_64-linux-gnu/libcudnn.so.7 -> libcudnn.so.7.6.5
-rw-r--r-- 1 root root 428711256 Oct 27  2019 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

In [14]: !touch  /usr/lib/x86_64-linux-gnu/test.txt
touch: cannot touch '/usr/lib/x86_64-linux-gnu/test.txt': Read-only file system
```

**Comment by dtrudg** [comment]
Certainly the files should be present the same if they are in the SIF rootfs and it is run twice. This isn't an overlay though, it's the base layer of the container filesystem.

What is key to know is *exactly* how the second subprocess is being run, what the command line is, what the environment variables are. Without that information we can't really diagnose this further. It sounds a lot like the subprocess is doing something odd that is running a nested container or otherwise impacting the container fs. Singularity should not do anything like that itself. It's not something we can really look at separately from the program you are running here.

**Comment by cupdike** [comment]
The worker process command and environment are below.

I notice that the mounts inside the main and subprocess are also different.  Curiously, the main provides `/.singularity.d/libs` but the subprocess provides `/.singularity.d/actions`.  Also, the main has an nvidia socket mounted:

```
# Main process
In [1]: !df -h
Filesystem                                     Size  Used Avail Use% Mounted on
overlay                                         16M   32K   16M   1% /
devtmpfs                                        47G     0   47G   0% /dev
tmpfs                                           47G  432K   47G   1% /dev/shm
/dev/mapper/rhel-root                          222G   91G  131G  41% /tmp
tmpfs                                           16M   32K   16M   1% /.singularity.d/libs
tmpfs                                           47G  107M   47G   1% /run/nvidia-persistenced/socket

# Worker subprocess
In [56]: !df -h
Filesystem                                     Size  Used Avail Use% Mounted on
overlay                                         16M   32K   16M   1% /
devtmpfs                                        47G     0   47G   0% /dev
tmpfs                                           47G  432K   47G   1% /dev/shm
/dev/mapper/rhel-root                          222G   91G  131G  41% /tmp
tmpfs                                           16M   32K   16M   1% /.singularity.d/actions
```

Here's the worker process command:
```
In [53]: !strings /proc/117909/cmdline
ray::BaseHorovodWorker.execute()
```
Here's the worker process env:
```
BASH_ENV=/usr/share/lmod/lmod/init/bash
CLICOLOR=1
CONDA_DEFAULT_ENV=base
CONDA_EXE=/opt/cloudera/parcels/Anaconda-5.3.1/bin/conda
CONDA_PREFIX=/opt/cloudera/parcels/Anaconda-5.3.1
CONDA_PROMPT_MODIFIER=(base) 
CONDA_PYTHON_EXE=/opt/cloudera/parcels/Anaconda-5.3.1/bin/python
CONDA_SHLVL=1
CUDA_PKG_VERSION=10-1=10.1.243-1
CUDA_VERSION=10.1.243
CUDA_VISIBLE_DEVICES=0
CUDNN_VERSION=7.6.5.32-1+cuda10.1
GIT_PAGER=cat
GOPATH=/opt/go/packages
GOROOT=/opt/go/1.14.4
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/home/user1
HOROVOD_CONTROLLER=gloo
HOROVOD_CPU_OPERATIONS=gloo
HOROVOD_CROSS_RANK=0
HOROVOD_CROSS_SIZE=1
HOROVOD_GLOO_IFACE=lo
HOROVOD_GLOO_RENDEZVOUS_ADDR=30.30.30.30
HOROVOD_GLOO_RENDEZVOUS_PORT=45627
HOROVOD_HOSTNAME=server1
HOROVOD_LOCAL_RANK=0
HOROVOD_LOCAL_SIZE=1
HOROVOD_RANK=0
HOROVOD_SIZE=1
HOSTNAME=headnode
JAVA_HOME=/usr/java/default
KRB5CCNAME=FILE:/tmp/krb5cc_20017810_o8znXx
LANG=en_US.UTF-8
LC_CTYPE=C.UTF-8
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
LMOD_CMD=/usr/share/lmod/lmod/libexec/lmod
LMOD_COLORIZE=yes
LMOD_DIR=/usr/share/lmod/lmod/libexec
LMOD_FULL_SETTARG_SUPPORT=no
LMOD_PKG=/usr/share/lmod/lmod
LMOD_PREPEND_BLOCK=normal
LMOD_ROOT=/usr/share/lmod
LMOD_SETTARG_CMD=:
LMOD_SETTARG_FULL_SUPPORT=no
LMOD_VERSION=8.2.7
LMOD_arch=x86_64
LMOD_sys=Linux
MANPATH=/usr/share/lmod/lmod/share/man:
MODULEPATH=/sw/modules/all:/sw/hpc-sdk/modulefiles
MODULEPATH_ROOT=/sw/modules
MODULESHOME=/usr/share/lmod/lmod
MPLBACKEND=module://ipykernel.pylab.backend_inline
MXNET_VERSION=1.6.0.post0
NCCL_SOCKET_IFNAME=lo
NCCL_VERSION=2.7.8-1+cuda10.1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_REQUIRE_CUDA=cuda>=10.1 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 brand=tesla,driver>=418,driver<419
NVIDIA_VISIBLE_DEVICES=all
OMP_NUM_THREADS=1
PAGER=cat
PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PLAT=linux-x86_64
PMIX_BFROP_BUFFER_TYPE=PMIX_BFROP_BUFFER_NON_DESC
PMIX_GDS_MODULE=hash
PMIX_NAMESPACE=slurm.pmix.790.0
PMIX_PTL_MODULE=tcp
PMIX_RANK=0
PMIX_SECURITY_MODE=none
PMIX_SERVER_TMPDIR=/var/spool/slurm/d/pmix.790.0/
PMIX_SERVER_URI21=pmix-server.166914;tcp4://127.0.0.1:50060
PMIX_SERVER_URI2=pmix-server.166914;tcp4://127.0.0.1:50060
PMIX_SYSTEM_TMPDIR=/var/empty
PROMPT_COMMAND=PS1="Singularity> "; unset PROMPT_COMMAND
PWD=/home/user1/slurm/HorRayMnist
PYSPARK_PACKAGE=pyspark==2.4.7
PYTHON_VERSION=3.7
PYTORCH_VERSION=1.6.0
RAY_JOB_ID=20000000
SHELL=/bin/bash
SHLVL=3
SINGULARITY_APPNAME=
SINGULARITY_CONTAINER=/home/user1/horovodDocker/native_horray.sif
SINGULARITY_NAME=native_horray.sif
SLURMD_NODENAME=server1
SLURM_CLUSTER_NAME=deepops
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=12
SLURM_CPUS_PER_TASK=12
SLURM_CPU_BIND=quiet,mask_cpu:0x000555000555
SLURM_CPU_BIND_LIST=0x000555000555
SLURM_CPU_BIND_TYPE=mask_cpu:
SLURM_CPU_BIND_VERBOSE=quiet
SLURM_GTIDS=0
SLURM_JOBID=790
SLURM_JOB_CPUS_PER_NODE=12
SLURM_JOB_GID=20017810
SLURM_JOB_ID=790
SLURM_JOB_NAME=singularity
SLURM_JOB_NODELIST=server1
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=batch
SLURM_JOB_QOS=normal
SLURM_JOB_UID=20017810
SLURM_JOB_USER=user1	
SLURM_LAUNCH_NODE_IPADDR=30.30.30.30
SLURM_LOCALID=0
SLURM_MPI_TYPE=pmix
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=server1
SLURM_NPROCS=1
SLURM_NTASKS=1
SLURM_PMIX_MAPPING_SERV=(vector,(0,1,1))
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SRUN_COMM_HOST=headnode
SLURM_SRUN_COMM_PORT=43341
SLURM_STEPID=0
SLURM_STEP_ID=0
SLURM_STEP_LAUNCHER_PORT=43341
SLURM_STEP_NODELIST=server1
SLURM_STEP_NUM_NODES=1
SLURM_STEP_NUM_TASKS=1
SLURM_STEP_TASKS_PER_NODE=1
SLURM_SUBMIT_DIR=/home/user1/slurm/HorRayMnist
SLURM_SUBMIT_HOST=server1
SLURM_TASKS_PER_NODE=1
SLURM_TASK_PID=166924
SLURM_TOPOLOGY_ADDR=server1
SLURM_TOPOLOGY_ADDR_PATTERN=node
SLURM_UMASK=0002
SLURM_WORKING_CLUSTER=cluster1:server1:6817:8960:109
SPARK_PACKAGE=spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz
SRUN_DEBUG=3
TENSORFLOW_VERSION=2.3.2
TERM=xterm-color
TF2_BEHAVIOR=1
TMPDIR=/tmp
TMUX=/tmp/tmux-20017810/default,8366,0
TMUX_PANE=%6
TORCHVISION_VERSION=0.7.0
USER=user1
USER_PATH=/home/user1/bin:/usr/java/default/bin:/usr/local/cuda/bin:/opt/cloudera/parcels/Anaconda-5.3.1/bin:/opt/cloudera/parcels/Anaconda-5.3.1/condabin:/home/user1/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/opt/go/1.14.4/bin:/opt/go/packages/bin:/usr/local/sbin:/usr/sbin:/opt/go/1.14.4/bin:/opt/go/packages/bin:/home/user1/.local/bin:/home/user1/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
XDG_DATA_DIRS=/home/user1/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/run/user/20017810
XDG_SESSION_ID=924
```

**Comment by dtrudg** [comment]
I'm afraid I'm still not clear from this how the worker process is launched. The filesystem signs suggest it is a separate launch of the same container, but without the `--nv` option.... or even a different container.

Generally with Singularity we've seen horovod being used with MPI, but not Spark (which seems to be included here)... and I'm not clear if the complexity is somehow a result of that. I'm suspicious of having to pass options such as `--address server1:6379` when running, as within an MPI job the communication between workers etc. should generally not be dependent on a fixed address.

I don't think there is a problem with Singularity here, more that the worker launch isn't happening in a way that calls the Singularity container with `--nv` properly. The filesystem being different suggests it's a different container launch.

I'm afraid I'd suggest taking this to a horovod support / discussion area, which is more familiar with the various ways horovod jobs are executed.

**Comment by cupdike** [comment]
I did take it to the Ray Slack channel.  Since tf.config.experimental.list_physical_devices('GPU') doesn't return the GPU, outside of Ray, they don't consider it a Ray problem.  As mentioned, Ray is not aware of the use of Singularity.   I don't think I can provide Ray the context it would need to launch the appropriately configured process.  Guess I've fallen inside the donut hole between Singularity and Ray.  But at this point I agree that it's more on the Ray side.  Thanks for the insights...
