### ISSUE TITLE
[Release Request]Update the version in neuro.debian.net into latest 3.7.3

### ISSUE THREAD

**Issue by diyism** [apptainer/singularity#5943]
The singularity version in neuro.debian.net is too old: 2.6.1
$ wget -O- http://neuro.debian.net/lists/sid.us-ca.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
$ apt update
$ apt install singularity-container
$ /usr/bin/singularity --version
2.6.1-dist

How to urge them to update the repo to include latest singularity 3.7.3?

**Comment by dtrudg** [comment]
Please use contact information on the neuro debian pages. We do not package singularity for distributions ourselves.

**Comment by dtrudg** [comment]
See http://neuro.debian.net/about.html#chap-contacts
