### ISSUE TITLE
singularity ARM64 build Erro

### ISSUE THREAD

**Issue by xspython** [apptainer/singularity#5945]
$ ./mconfig --prefix=/usr/local/singularity
$ cd builddir
$ make 
GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
# github.com/containers/storage/pkg/unshare
In file included from /usr/include/aarch64-linux-gnu/sys/syscall.h:31:0,
                 from unshare.c:7:
unshare.c: In function 'copy_self_proc_exe':
unshare.c:236:17: error: '__NR_memfd_create' undeclared (first use in this function)
  mmfd = syscall(SYS_memfd_create, exename, (long) MFD_ALLOW_SEALING | MFD_CLOEXEC);
                 ^
unshare.c:236:17: note: each undeclared identifier is reported only once for each function it appears in
Makefile:175: recipe for target 'singularity' failed
make: *** [singularity] Error 2

kernel version  3.14.57
ARM64

**Comment by dtrudg** [comment]
> kernel version 3.14.57
> ARM64

This is a very old kernel (Nov 2015 https://lwn.net/Articles/663867/). Likely you will need to update your kernel and system headers. The error comes from a library that Singularity is using, and we aren't easily able to change it.

Singularity for ARM64 is known to build on RHEL7 / RHEL8 / SUSE 15, and Ubuntu 18.04 & 20.04.
