### ISSUE TITLE
Feature to overlay to specific directory

### ISSUE THREAD

**Issue by ebetica** [apptainer/singularity#5952]
### Version of Singularity:

What version of Singularity are you using? 3.7.2

`singularity exec --nv --overlay ~/data.sqsh:/path/in/container image.sif ls /path/in/container`

### Expected behavior

I would like to see the contents of `data.sqsh` in `/path/in/container`

### Actual behavior

`data.sqsh` is mounted to `/`. Does the feature to place the overlay at an arbitrary directory exist?

**Comment by dtrudg** [comment]
You can bind mount from an image to a specified location in 3.6 and above. See:

https://sylabs.io/guides/3.7/user-guide/bind_paths_and_mounts.html#image-mounts

**Comment by ebetica** [comment]
Thanks! This works!
