### ISSUE TITLE
Undefined buildcfg variables when compiling Singularity

### ISSUE THREAD

**Issue by xspython** [apptainer/singularity#5958]
$ version  singularity-3.5.1-rc.2

I am trying to install Singularity on an Ubuntu 18.04 machine following the instructions here: https://github.com/hpcng/singularity/blob/master/INSTALL.md

I am trying to install Singularity on an Ubuntu 18.04 machine following the instructions here: https://github.com/hpcng/singularity/blob/master/INSTALL.md

The machine is behind a proxy, and I found that I need to set https_proxy to "http://..." (without the 's') before running make so that it can go past the

GEN GO DEP /home/adeline/go/src/github.com/sylabs/singularity/builddir/starter.d
GEN GO DEP /home/adeline/go/src/github.com/sylabs/singularity/builddir/singularity.d
lines. I don't know if this proxy issue is related to the problem I hit now. make now stops with this output:

GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
# github.com/sylabs/singularity/internal/pkg/util/bin
../internal/pkg/util/bin/bin.go:37:14: undefined: buildcfg.SINGULARITY_CONF_FILE
../internal/pkg/util/bin/bin.go:53:5: undefined: buildcfg.CRYPTSETUP_PATH
../internal/pkg/util/bin/bin.go:70:6: undefined: buildcfg.CRYPTSETUP_PATH
../internal/pkg/util/bin/bin.go:74:10: undefined: buildcfg.CRYPTSETUP_PATH
# github.com/sylabs/singularity/internal/pkg/util/fs/squashfs
../internal/pkg/util/fs/squashfs/squashfs.go:25:17: undefined: buildcfg.SINGULARITY_CONF_FILE
# github.com/sylabs/singularity/pkg/util/loop
../pkg/util/loop/loop_singularity.go:17:17: undefined: buildcfg.SINGULARITY_CONF_FILE
# github.com/sylabs/singularity/internal/pkg/util/starter
../internal/pkg/util/starter/starter.go:59:27: undefined: buildcfg.LIBEXECDIR
../internal/pkg/util/starter/starter.go:62:26: undefined: buildcfg.LIBEXECDIR
../internal/pkg/util/starter/starter.go:118:25: undefined: buildcfg.LIBEXECDIR
../internal/pkg/util/starter/starter_linux.go:31:26: undefined: buildcfg.ENGINE_CONFIG_ENV
../internal/pkg/util/starter/starter_linux.go:32:26: undefined: buildcfg.ENGINE_CONFIG_CHUNK_ENV
../internal/pkg/util/starter/starter_linux.go:54:12: undefined: buildcfg.MAX_ENGINE_CONFIG_CHUNK
../internal/pkg/util/starter/starter_linux.go:55:20: undefined: buildcfg.MAX_CHUNK_SIZE
../internal/pkg/util/starter/starter_linux.go:66:10: undefined: buildcfg.MAX_ENGINE_CONFIG_CHUNK
../internal/pkg/util/starter/starter_linux.go:67:64: undefined: buildcfg.MAX_ENGINE_CONFIG_SIZE
# github.com/sylabs/singularity/internal/pkg/plugin
../internal/pkg/plugin/create.go:98:23: undefined: buildcfg.SOURCEDIR
../internal/pkg/plugin/create.go:100:96: undefined: buildcfg.SOURCEDIR
../internal/pkg/plugin/create.go:106:23: undefined: buildcfg.SOURCEDIR
../internal/pkg/plugin/meta.go:26:12: undefined: buildcfg.PLUGIN_ROOTDIR
../internal/pkg/plugin/module.go:151:33: undefined: buildcfg.SOURCEDIR
# github.com/sylabs/singularity/pkg/image/unpacker
../pkg/image/unpacker/squashfs_singularity.go:233:36: undefined: buildcfg.BINDIR
# github.com/sylabs/singularity/internal/pkg/remote
../internal/pkg/remote/remote.go:47:38: undefined: buildcfg.SYSCONFDIR
Makefile:178: recipe for target 'singularity' failed
make: *** [singularity] Error 2
All dependencies seem to be installed, and the version of go is 1.16.3.

Any idea of what may be going wrong, and how to get Singularity to compile on this machine

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by ncu-walker** [comment]
Hi, I met the same error. Have you solved it?

**Comment by DrDaveD** [comment]
Apparently not.  The report was on an old version of singularity at this point.  I suggest you submit a new issue with your particulars.

**Comment by HusBunia** [comment]
Hi, I also met the same problem. Have you installed it successful?

**Comment by DrDaveD** [comment]
Again, please submit a new apptainer issue with your particulars.  I don't think the previous person ever did.
