### ISSUE TITLE
[development] unset TERM with "singularity shell" and SINGULARITY_CLEANENV

### ISSUE THREAD

**Issue by flx42** [apptainer/singularity#596]
```
$ singularity shell --cleanenv docker://centos:7
Singularity centos:7:/tmp> top
TERM environment variable not set.
```
Same with `--containall`.

Setting to "xterm" might be a good default option, maybe in the `shell` bootstrap script?

**Comment by ArangoGutierrez** [comment]
I get this when doing it on my pc.
Last pull from repo : today
```bash
[eduardo@sephiroth ~]$ singularity shell --cleanenv docker://centos:7
Docker image path: index.docker.io/library/centos:7
Cache folder set to /home/eduardo/.singularity/docker
Importing: base Singularity environment
Exploding layer: sha256:93857f76ae30d903bbdad13fbf7fad95ce1c0b52b7d5644651e01c6c7a906312.tar.gz
Exploding layer: sha256:9326ff949485e53c2403126b5422ad659cb2176bddbc511461da81c10703a50c.tar.gz
Singularity: Invoking an interactive shell within container...

Singularity centos:7:/home/eduardo> exit
```
with `--containall`
```bash
[eduardo@sephiroth ~]$ singularity shell --containall docker://centos:7
Docker image path: index.docker.io/library/centos:7
Cache folder set to /home/eduardo/.singularity/docker
Importing: base Singularity environment
Exploding layer: sha256:93857f76ae30d903bbdad13fbf7fad95ce1c0b52b7d5644651e01c6c7a906312.tar.gz
Exploding layer: sha256:9326ff949485e53c2403126b5422ad659cb2176bddbc511461da81c10703a50c.tar.gz
Singularity: Invoking an interactive shell within container...

Singularity centos:7:/home/eduardo> exit
```

**Comment by flx42** [comment]
@ArangoGutierrez what is your point?

**Comment by gmkurtzer** [comment]
Hi @flx42, can you retest please?

Thanks!

**Comment by flx42** [comment]
I'm not a big fan of b82b48ee211ecefd5135954887ad631d45a261c5 to be honest. Having exceptions kinda of defeat the purpose of `--containall`.
And `TERM` should probably only be set for `singularity shell`.

**Comment by gmkurtzer** [comment]
I would argue that `TERM` should be available in all of the actions (e.g. singularity exec/run might also do something, anything, requiring TERM). 

We could change this such that it only happens for the actions, but in the end, some bits of the environment are always going to be somewhat representative and needed by the calling shell.

If you feel strongly, I can do this elsewhere.

**Comment by flx42** [comment]
I don't feel strongly about it, but I feel it would be nice to have the opinion of someone else here.

**Comment by gmkurtzer** [comment]
I decided to do it in the singularity_runtime_environment()... Will update shortly (Internet is taking a break right now pfft...). 

Thanks!

**Comment by vsoch** [comment]
If this were any other variable, then to stay true to  `--containall` and `--cleanenv` we would not include `TERM`. But @flx42 original example with shell is an obvious case when this is pretty stupid to do. It would be highly annoying to have to add this as a custom variable to containers just to use these commands. Here are the use cases I see:

## Case 1: User just wants to contain, or clean environment
Probably the user isn't going to think much about `TERM`, and it's going to be annoying and confusing to have the error message (as @flx42 showed above). This is one of those things that is just expect it to work, and users don't have a lot of preference for. 

## Case 2: User has preference for term
A user that **would** have preference would go out of his/her way to define the variable with the image. In this case, whether or not we define it wouldn't matter, the container's would take preference.

The first decision I'm thinking about is the above - should we include `TERM` at all? Based on what I said above, I think yes. The second question is, to what extent? So then we have a few options. 

- include `TERM` in a subset of commands for `--containenv`/`--containall`, meaning shell would work, maybe exec wouldn't. 
- include `TERM` in all commands for `--containenv`/`--containall`.

There is complete certainty of needing it for shell, and more uncertainty about the rest. But we do know there are edge cases when it would be needed, and then not defined. On the other hand, having it defined probably wouldn't hurt. It's also easier to do it consistently across commands than have a bunch of custom logic. So my final opinion is to include it, and include with all actions as one of those "special singularity" variables. If we find some use case that we didn't anticipate here where this is a bad idea, then we can step back and include under some conditions.

**Comment by flx42** [comment]
> A user that would have preference would go out of his/her way to define the variable with the image.

I agree with that.

FYI, Docker only adds this environment variable when `--tty/-t` is set:
```
$ docker run -t centos:7 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=207e7c90e20d
TERM=xterm
HOME=/root

$ docker run centos:7 env                                                                                                                                                  
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                                                                                 
HOSTNAME=1649c7566c70                                                                                                                                                             
HOME=/root
```

**Comment by vsoch** [comment]
hmm maybe we could have an equivalent command for terminal (the same `--tty/t`) so it's familiar, and it is sort of a weird one. @gmkurtzer would this blow up your head? lol

**Comment by gmkurtzer** [comment]
It is actually very easy to do it with `-t/--tty` thanks to `SINGULARITYENV_` in the shell wrappers. I'm happy to do that too, but I think a reasonable default `TERM` should be used.

**Comment by flx42** [comment]
`docker run -t` would be equivalent to `singularity shell`, so I'm not sure what you are suggesting.

**Comment by gmkurtzer** [comment]
Let me just confirm to make sure I am getting the requested logic correctly:

1. When `--cleanenv`, `--contain` or `--containall` is passed, discard all environment variables unconditionally.
2. Assume some sane defaults, for example`TERM` and `LANG` both need to be defined to some reasonable setting for a lot of programs to work (perhaps `xterm-color` and `C` respectively?).
3. Add a `-t/--tty` option that takes the current environment setting for `TERM` (if defined) and pass that into the container.

It is my vote, considering that `TERM` and `LANG` are generally considered required to always take one of not both of them from the users current environment on the host. I could see setting `LANG=C` as a general rule something smart to do, but where that happens is up for discussion. Another option is to make that part of `/etc/singularity/init`, such that the default behavior is easily modifiable, and that people can always override it in their own `~/.singularity-init` files.

Greg

**Comment by flx42** [comment]
> When --cleanenv, --contain or --containall is passed, discard all environment variables unconditionally.

Yes, that's fine for me.

> Assume some sane defaults, for exampleTERM and LANG both need to be defined to some reasonable setting for a lot of programs to work (perhaps xterm-color and C respectively?).

Again, I think `TERM` should only be set for `singularity shell`.
`LANG` probably doesn't need to be set, it should default to the POSIX locale. Is there a bug with that?

> Add a -t/--tty option that takes the current environment setting for TERM (if defined) and pass that into the container.

I don't think there is a strong use case for this option. For me `-t/-tty` is simply equivalent to `singularity shell`. `docker run -t` doesn't use the host `TERM` variable, it always use `xterm`.
If you want to use your host `TERM` variable, don't use any `contain` option with `singularity shell`.

**Comment by vsoch** [comment]
- +1 on discard all environment variables unconditionally when --contain or --cleanenv are passed
 - Question on `TERM` - what are the drawbacks of having it defined? What would be the reason to have it only for shell? If a user's custom `TERM` is specified for the container, it would take preference, and I think there is more likely a chance that not having it defined would lead to a bug, but I'm not sure.
- I think we can avoid the `-t/-tty` option only given that we set `TERM`

**Comment by ArangoGutierrez** [comment]
There was a bug reported on #594 about not having the LANG env. 
So i think the LANG env may go as @gmkurtzer propose.

**Comment by gmkurtzer** [comment]
OK, I just want/need to reiterate... option 1 would end up discarding all environment variables unconditionally *except for* ones that are necessary for appropriate functions (so far `TERM` and `LANG` have been identified). Then the question becomes, what do we set those to. The options that I see are:

1. We set them static hard coded defaults via the C source code
2. We set them via changeable defaults via `/etc/singularity/init` or a user's environment variables (my preference)
3. We use what is currently defined in the user's shell (I was proposing only doing this when the `-t/--tty` option is used)

@flx42 I don't want to have different environmental configurations for the different actions as `TERM` and `LANG` can be necessary for programs weather they are executed via `shell` or `exec` or `run`.

For bootstrapping (as @ArangoGutierrez eluded to), we end up setting `LANG=C` to ensure that builds function appropriately. I see no reason not to continue with that here. I think the right solution is setting `SINGULARITYENV_LANG=C` in `/etc/singularity/init` (which will transpose to `LANG=C` inside the containers even if `--cleanenv` et. al. are passed) and using the same `TERM` as always defined by the environment. `TERM` would probably be best set in the same manner as `LANG` in `/etc/singularity/init`).

**Comment by flx42** [comment]
> Question on TERM - what are the drawbacks of having it defined? What would be the reason to have it only for shell?

It boils down to the question of whether `singularity exec docker://ubuntu:14.04 top` ultimately makes sense?
I feel `singularity exec` can be used in a scenario where no TTY is allocated, therefore setting `TERM` might actually cause bugs since we're basically lying ;).
Compare:
```
$ ssh -t localhost env | grep TERM
TERM=xterm
$ ssh -t localhost top
[works fine]

$ ssh -T localhost env | grep TERM 
$ # no match
$ ssh -T localhost top
TERM environment variable not set.
```
At least with option `3.`, we won't have this issue.

**Comment by flx42** [comment]
... But actually, using `3.` for `LANG` seems suspicious for reproducibility reasons.
So maybe `TERM` should take the host value if it's set. And `LANG` should be hardcoded to `C`?

**Comment by gmkurtzer** [comment]
I agree. :)

**Comment by vsoch** [comment]
ah, so beautiful, yes I agree too. I think we are likely to hit edge cases when something might break, in which case we can re-visit this discussion. The solution stated above by @flx42 sounds like it will work for the large majority.

**Comment by gmkurtzer** [comment]
Done. :)

**Comment by qhaas** [comment]
> I think we are likely to hit edge cases when something might break, in which case we can re-visit this discussion.

```
$ echo $TERM
xterm-256color
$ screen -v
Screen version 4.06.02 (GNU) 23-Oct-17
$ singularity --version
singularity version 3.7.0-1.el8
$ echo $TERM
screen.xterm-256color
$ singularity pull centos7.sif docker://centos:7
...
$ singularity exec -e centos7.sif printenv | grep TERM
TERM=screen.xterm-256color
$ singularity shell -e centos7.sif
Singularity> echo $TERM
screen.xterm-256color
Singularity> vi foo                                   
E437: terminal capability "cm" required
(garbled output ensues)
Singularity> TERM=xterm vi foo
(works like a charm)
```
Note, when not using `screen`, or if one uses `--env TERM=xterm` when launching singuarlity, the terminal / vi behaves as expected.
