### ISSUE TITLE
Request For Comment: Introducing CLA

### ISSUE THREAD

**Issue by gmkurtzer** [apptainer/singularity#5960]
We have seen many open source projects require that all contributors agree to a "Contributors License Agreement" (CLA) before accepting any contributions. The primary motivation for this is to ensure that open source projects and contributions remain freely available. Here are several example CLAs adopted by other well known open source projects:

* https://github.com/kubernetes/community/blob/master/CLA.md
* https://fedoraproject.org/wiki/Legal:Licenses/CLA
* https://github.com/open-mpi/ompi/wiki/Administrative-rules#contributors-declaration
* https://www.mpich.org/static/docs/cla/mpich-cla-individual-2016-11-25.pdf / https://www.mpich.org/static/docs/cla/mpich-cla-corporate-limited-2016-11-25.pdf
* https://slurm.schedmd.com/contributor.html
* https://github.com/openhpc/ohpc/wiki/Contributions

As you can see, there is reasonable precedent for CLAs and many organizations that support and contribute to Singularity already have experience with them due to the aforementioned projects.

The HPCng Board, and myself as the project lead of Singularity, would like to ensure that Singularity and its community is protected to use the software. We are proposing a CLA template that we feel does this (below). It is by far simpler than many of the aforementioned examples with the exceptions of OpenHPC and OpenMPI which are derivatives of https://developercertificate.org/ and lacking some appropriate protections (e.g. license retractions, patent restrictions, and employment relationship).

At our last Singularity development meeting, I asked for a review of our proposed CLA with the developer's legal teams and please provide a formal redlined response if there are any concerns within 30 days (by May 20th). GitHub provides a mechanism to enact click-through CLAs which I feel would be the lowest barrier of entry.

Again, the goal of this CLA is to provide assurance that Singularity can and will always remain open source and freely available.

https://docs.google.com/document/d/1uaREO0Fke9rND6abjZtMf4ASou0Zaejtv4Yix7I3O8c/edit

Greg

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by remram44** [comment]
Note that the Apache-2.0 license already includes this text:

> 2. Grant of Copyright License. Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in Source or Object form.

**Comment by DrDaveD** [comment]
> Note that the Apache-2.0 license already includes this text:
> 
> > 1. Grant of Copyright License. Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in Source or Object form.

That's not quite enough though because although it covers copyright, it does not cover intellectual property such as patents.

**Comment by remram44** [comment]
If that is the intention you might want to mention patents specifically. There doesn't seem to be a strong consensus on whether they are part of intellectual property rights (but IANAL).

**Comment by DrDaveD** [comment]
> If that is the intention you might want to mention patents specifically. There doesn't seem to be a strong consensus on whether they are part of intellectual property rights (but IANAL).

I thought they pretty much were the definition of intellectual property.  [Wikipedia](https://en.wikipedia.org/wiki/Intellectual_property) just lists it at one of the top four.

**Comment by remram44** [comment]
I quoted the wrong part of the Apache-2.0 license :flushed: my bad. The CLA part of the license is paragraph 5:

> 5. Submission of Contributions. Unless You explicitly state otherwise, any Contribution intentionally submitted for inclusion in the Work by You to the Licensor shall be under the terms and conditions of this License, without any additional terms or conditions.
> Notwithstanding the above, nothing herein shall supersede or modify the terms of any separate license agreement you may have executed with Licensor regarding such Contributions.

So it makes explicit that contributions come with a "grant of copyright license" (paragraph 2) and "grant of patent license" (paragraph 3).

Re: wikipedia, the article states that "some countries recognize more [types] than others" and puts patents among "the most well-known types". If you're happy with this and/or operate only in a USA context, of course that's fine with me too. I did not understand this from a cursory scan of your CLA but then again the Apache license does mention patents explicitly already.

**Comment by DrDaveD** [comment]
Sure enough, paragraph 3 is already very explicit about patents, and paragraph 5 covers contributions.  So I'm not sure what the CLA adds.

**Comment by DrDaveD** [comment]
Oh, but singularity has a BSD license, not an Apache license, and that's not going to change.

**Comment by DrDaveD** [comment]
Superceded by the Developer Certificate of Origin in Apptainer.
