### ISSUE TITLE
Not detecting GPU / CUDA

### ISSUE THREAD

**Issue by AlexKurek** [apptainer/singularity#5966]
### Version of Singularity:

3.7.2

### Expected behavior

When I run:
` nvidia-smi`
Im getting:

```
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+= =================|
|   0  NVIDIA GeForce ...  Off  | 00000000:03:00.0 Off |                  N/A |
| 38%   30C    P8     7W / 130W |     16MiB /  5943MiB |      0%      Default |
```
So GPU seems to be avalilable in the system. Then Im proceeding like described here:
https://sylabs.io/guides/3.7/user-guide/gpu.html#example-tensorflow-gpu
to verify if there is an access to GPU from Singulairty.
```
singularity pull docker://tensorflow/tensorflow:latest-gpu
singularity run --nv tensorflow_latest-gpu.sif
```
```
Singularity> python
>>> from tensorflow.python.client import device_lib
```
> 2021-04-29 09:49:41.815827: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0

(I don't really need TensorFlow. I'm using a custom rare scientific software, but there I'm getting the same error.)

### Actual behavior
```
>>> print(device_lib.list_local_devices())
```

> 2021-04-29 09:51:42.829115: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
> 2021-04-29 09:51:42.830670: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
> 2021-04-29 09:51:42.858960: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
> 2021-04-29 09:51:42.859037: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: lof5
> 2021-04-29 09:51:42.859095: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: lof5
> 2021-04-29 09:51:42.859216: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: Invalid argument: expected %d.%d, %d.%d.%d, or %d.%d.%d.%d form for driver version; got "1"
> 2021-04-29 09:51:42.859304: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 465.19.1
> [name: "/device:CPU:0"
> device_type: "CPU"
> memory_limit: 268435456
> locality {
> }
> incarnation: 1578950152897563820

### Steps to reproduce this behavior
Commands pasted above or:
https://sylabs.io/guides/3.7/user-guide/gpu.html#example-tensorflow-gpu

### What OS/distro are you running
Ubuntu 18.04.5

### How did you install Singularity
Source

**Comment by dtrudg** [comment]
Please see: https://github.com/hpcng/singularity/issues/1441 - it is likely the the `nvidia_uvm` kernel module was not loaded on your host before singularity was run.

**Comment by AlexKurek** [comment]
> Please see: #1441 - it is likely the the `nvidia_uvm` kernel module was not loaded on your host before singularity was run.

I did:
`sudo modprobe nvidia-uvm`
and still getting this error in tensorflow_latest-gpu.sif.
And on my specialized custom software it says:
> CUDA Error at /opt/IDG/build/src/idg-lib/src/CUDA/common/CU.cpp:47 in function cuInit(flags): unknown error

**Comment by dtrudg** [comment]
Can you verify that you can run a CUDA program on the host, prior to trying in the container? e.g. the simple `matrixMul` or `deviceQuery` program from the CUDA samples will do.

**Comment by AlexKurek** [comment]
Yes, they are both working fine. Also CUDA in Numba ( http://numba.pydata.org/ ) seems to be working.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by BlakeGFitch** [comment]
I ran into a similar problem in an OpenHPC cluster environment: Centos 3.10.0-1160.24.1.el7.x86_64 , singularity version 3.4.1-4.2.ohpc.1.3.9.  What is written up here feels more like a work-around than an answer. But maybe a web search will bring someone here and save them some time.

I reproduced the problem on another machine:  5.4.0-72-generic #80~18.04.1-Ubuntu , singularity version 3.7.0


The general problem:
```
>>> import torch
>>> torch.cuda.is_available()
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370172916/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
False
```

The quick test (taken from https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py). Look for "Is CUDA available: True" in the output. Failure mode: "Is CUDA available: False"
```
singularity exec --nv cpilab_latest.sif python collect_env.py
```

Fixes
On the Ubuntu machine, 
```
sudo apt --purge remove '*nvidia*'
sudo apt install nvidia-driver-465
```
On the OpenHPC CentOS 7 cluster machines, life has not been so simple. The nodes do a stateless PXE boot managed by Warewulf. Installing Nvidia drivers in the chroots hasn't worked. The drivers are instead installed by a script using an Nvidia 'cuda_*_linux.run' file on each boot. Below is the version of that script that makes torch in singularity containers happy. Note that a singularity run must be done as root -- after that other UIDs work. (Maybe there's a better way?)
```
>cat /opt/ohpc/admin/images/centos7-gpu/etc/rc.d/InstallGpuDriver.sh
echo "*** START NVIDIA INSTALL ***"
cd ~
sh /ptmp/root/current-gpu-node-nvidia-stuff/cuda_11.3.1_465.19.01_linux.run --silent 

# This seems to be needed even after the above install
modprobe nvidia_uvm

# We need one run as root, then other uids work (perhaps this is in place of a reboot?)
export SINGULARITY_BIN=/opt/ohpc/pub/libs/singularity/3.4.1/bin
export SINGULARITY_DIR=/opt/ohpc/pub/libs/singularity/3.4.1
export CUDA_VISIBLE_DEVICES=0
/opt/ohpc/pub/libs/singularity/3.4.1/bin/singularity exec -B /ptmp/root/current-gpu-node-nvidia-stuff/ --nv /ptmp/root/current-gpu-node-nvidia-stuff/cpilab_latest.sif python /ptmp/root/current-gpu-node-nvidia-stuff/collect_env.py

echo "export PATH=/usr/local/cuda/bin:$PATH" >>.bashrc
echo "export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH" >>.bashrc
source .bashrc
nvcc --version
nvidia-smi
echo "*** END NVIDIA INSTALL ***"

```


References:
```
https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py
https://github.com/pytorch/pytorch/issues/47038
https://discuss.pytorch.org/t/cuda-error-while-checking-cuda-in-system/104003
https://discuss.pytorch.org/t/pytorch-suddenyl-stops-recognising-gpu/93384   # suggest modprobe nvida_uvm
google search on related "triggered internally at /pytorch/c10/cuda/cudafunctions.cpp:109"
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
https://discuss.pytorch.org/t/no-process-using-gpu-but-cuda-error-all-cuda-capable-devices-are-busy-or-unavailable/102623
https://www.tensorflow.org/install/docker   # to get another container to try the gpu with -- failed as well at first
```
