### ISSUE TITLE
/tmp/rootfs-*

### ISSUE THREAD

**Issue by xspython** [apptainer/singularity#5967]
$ singularity version

3.7.3

If I run the image. SIF, I find that the directory of rootfs - * will be generated in  /tmp/ Can I put this directory in another directory? Similar to home directory

**Comment by dtrudg** [comment]
You can set the environment variable `SINGULARITY_TMPDIR` or `TMPDIR`. See the documentation here:

https://sylabs.io/guides/3.7/user-guide/build_env.html#sec-temporaryfolders (this is about build, but applies also to running containers when you are in user namespace mode or there is another reason Singularity cannot run directly from a SIF file and must extract the container before running it.)
