### ISSUE TITLE
mconfig fails due to package version test

### ISSUE THREAD

**Issue by ghost** [apptainer/singularity#5970]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version 
$ singularity version
3.7.3

```

### Expected behavior

What did you expect to see when you do...?
New to this but expect mconfig to do configuration, thus ready for make and make install?

### Actual behavior

What actually happend? Why was it incorrect?

When I try to run mconfig on Ubuntu 20.04, always get error message, ""Failed to get package version. Abort."   When I comment out this section of code in mconfig, it configures, makes and installs fine, at least appears to.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
comment out this code in mconfig
`
# if test -z "${package_version}" ; then
# 	echo "Failed to get package version. Abort."
# 	exit 1
# fi
`

### What OS/distro are you running

```
$ cat /etc/os-release


```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

singularity-3.7.3.tar.gz

**Comment by ikaneshiro** [comment]
Hi @jimmaas, can you check to make sure the directory you extracted from the tarball contains a `VERSION` file with the correct version? Parsing this file is how `mconfig` is intended to find the version when building from a release tarball

**Comment by ghost** [comment]
Thanks @ikaneshiro , I did check previously,  and again just now, and yes it exists and it seems to have the correct version in it!  Thx. J

`singularity$ cat VERSION 
3.7.3
`

**Comment by ikaneshiro** [comment]
Hmm. What does running `git rev-parse --show-toplevel` in your extracted directory output? If you extracted the tarball within a git repository, our version detection script will try to fetch version information from it and potentially cause this error

**Comment by ghost** [comment]
Originally I just dowloaded the whole tar.gz file (not via git), and then think I did tar -xzvf.  Is some of this incorrect?

This is what I get, just changed name to *'s:

`
singularity$ git rev-parse --show-toplevel
/home/*******/Downloads
`

**Comment by ikaneshiro** [comment]
Extracting the tarball the way you did is correct. From that output it looks like there's a `.git` directory within your Downloads folder, so to test lets try extracting the tarball somewhere that doesn't have a `.git` in any of the parent directories. Maybe `/tmp`

**Comment by ghost** [comment]
Hmmm, did what you said, created new directory outside git repo ... copied across the tar.gz file, tar -xzvf'd it .... went into /singularity and ./mconfig works fine!  
`   - verbose: no
      ---
    - cryptsetup: /sbin/cryptsetup
      ---
    - version: 3.7.3
=> /home/*****/singtest/singularity/builddir/Makefile ready, try:
   $ cd /home/*****/singtest/singularity/builddir
   $ make
`
ran make and it seems to work
`
CNI PLUGIN portmap
 CNI PLUGIN tuning
 GO clean -cache
 GO cmd/starter/c/starter
 GO cmd/starter/c/starter-suid
    [+] GO_TAGS "containers_image_openpgp sylog singularity_engine fakeroot_engine apparmor selinux seccomp"
 GEN /home/*****/singtest/singularity/scripts/go-test
`
Well spotted, but I think it might catch people out in future?  So I guess this has to be done by pulling git repo, or downloading tar.gz file from a not git directory ?    Thx. J

**Comment by ikaneshiro** [comment]
Fantastic. I suspect this will be rare for people to run into as they usually wont have a `.git` directory in a parent to where they are extracting and building from a tarball, but if others continue to run across this problem, we can either improve our admin docs with a warning about this issue or change the behavior for our script.

I'm going to close this issue, but feel free to reopen if you feel something else should be done.
