### ISSUE TITLE
v3.7.3 fails to find config in custom location

### ISSUE THREAD

**Issue by ciaron** [apptainer/singularity#5971]
Version 3.7.3 installed to a custom location fails to find `singularity.conf` in that location. This happens whether or not `--sysconfdir` is specified at build time.

v3.7.2 does find the config files.

### Version of Singularity:

What version of Singularity are you using? Run:

```
3.7.3
```

### Expected behavior

Run `singularity` on command line

### Actual behavior

```
FATAL:   Couldn't not parse configuration file /usr/local/etc/singularity/singularity.conf: open /usr/local/etc/singularity/singularity.conf: no such file or directory
```

### Steps to reproduce this behavior

Install version 3.7.3 from sources as per Admin Guide.
The failure does not occur with `v3.7.2`:

```
$ singularity -h # v3.7.3
...
  -c, --config string   specify a configuration file (for root or
                        unprivileged installation only) (default
                        "/usr/local/etc/singularity/singularity.conf")
...

```

```
$ singularity -h # v3.7.2
...
  -c, --config string   specify a configuration file (for root or
                        unprivileged installation only) (default
                        "/tmp/opt/singularity/etc/singularity/singularity.conf")
...

```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"


```

### How did you install Singularity

As root, as per Admin Guide for installing from sources:
```
./mconfig --prefix=/tmp/opt/singularity --localstatedir=/var
cd builddir
make 
make install
```

**Comment by ikaneshiro** [comment]
@ciaron I am unable to replicate this when running `mconfig` with the parameters you specified. Can you include the output of `/tmp/opt/singularity/bin/singularity buildcfg`?


The parameters generated on my system are in line with expected behavior
```
$ /tmp/opt/singularity/bin/singularity buildcfg
PACKAGE_NAME=singularity
PACKAGE_VERSION=3.7.3
BUILDDIR=/home/ian/devel/src/singularity/builddir
PREFIX=/tmp/opt/singularity
EXECPREFIX=/tmp/opt/singularity
BINDIR=/tmp/opt/singularity/bin
SBINDIR=/tmp/opt/singularity/sbin
LIBEXECDIR=/tmp/opt/singularity/libexec
DATAROOTDIR=/tmp/opt/singularity/share
DATADIR=/tmp/opt/singularity/share
SYSCONFDIR=/tmp/opt/singularity/etc
SHAREDSTATEDIR=/tmp/opt/singularity/com
LOCALSTATEDIR=/var
RUNSTATEDIR=/var/run
INCLUDEDIR=/tmp/opt/singularity/include
DOCDIR=/tmp/opt/singularity/share/doc/singularity
INFODIR=/tmp/opt/singularity/share/info
LIBDIR=/tmp/opt/singularity/lib
LOCALEDIR=/tmp/opt/singularity/share/locale
MANDIR=/tmp/opt/singularity/share/man
SINGULARITY_CONFDIR=/tmp/opt/singularity/etc/singularity
SESSIONDIR=/var/singularity/mnt/session
PLUGIN_ROOTDIR=/tmp/opt/singularity/libexec/singularity/plugin
SINGULARITY_CONF_FILE=/tmp/opt/singularity/etc/singularity/singularity.conf
SINGULARITY_SUID_INSTALL=1
```

**Comment by ciaron** [comment]
@ikaneshiro I don't even get that far:

```
$ /tmp/opt/singularity/bin/singularity buildcfg
FATAL:   Couldn't not parse configuration file /usr/local/etc/singularity/singularity.conf: open /usr/local/etc/singularity/singularity.conf: no such file or directory
```
It's odd, using exactly the same build process with v3.7.2, I get output like yours and a working build.

**Comment by ciaron** [comment]
I solved it by deleting the source tree and starting from scratch. I had done an initial `mconfig` step without `--prefix` so I guess some old setting wasn't getting cleared with `make clean`.

Edit: for anyone else coming here, I thought that deleting `builddir` was enough to start a clean build, but it's not - best to unpack the .tar.gz again.

Sorry for the noise.

**Comment by ikaneshiro** [comment]
Not a problem. Glad it's resolved :+1:
