### ISSUE TITLE
enh - let version reflect git short hash when configuring from a git repo

### ISSUE THREAD

**Issue by satra** [apptainer/singularity#599]
it would be nice if the git hash was injected via configure when the existing folder from which configure is run is a git repo of singularity.

**Comment by jmstover** [comment]
@satra Are you meaning only when you do a ./configure from within a structure containing a .git/ directory? Or even from tarballs built from a given git source?

I've done similar by creating a .gitversion file during the autogen.sh run and using that during ./configure and replacing with that value... would a similar setup be close enough?

**Comment by satra** [comment]
@jmstover - i think that would work - this is mostly to ensure that people don't submit issues saying we are using version 2.2.99 when using dev branches. and also allows us to run git bisect a little more optimally.

**Comment by gmkurtzer** [comment]
Something like this:

```bash
$ singularity --version
2.2.99 (development.a9313ce)
```

Where else do you want to see it?

**Comment by satra** [comment]
@gmkurtzer - just there, but did you compile it in some special way?

i compiled dev branch just this morning and installed it and it says 2.2.99 without the development txt.

**Comment by gmkurtzer** [comment]
I haven't committed/pushed this change yet. Wanted to know if that was what you were hoping for. :)

**Comment by satra** [comment]
@gmkurtzer - ah in that case could we do it like git describe :)

```
# git describe
2.2-1122-g03a88e9
```

and if the 1122 is too complicated, i would be completely fine with just:

```
2.2-branchname-g03a88e9
```

**Comment by gmkurtzer** [comment]
Pushed, will you test the development branch now?

Thanks!

**Comment by satra** [comment]
woohoo!
```
$ singularity --version
2.2.99 (development/324d1d3)
```
