### ISSUE TITLE
CentOS-5 issues (echo/runtime)

### ISSUE THREAD

**Issue by truatpasteurdotfr** [apptainer/singularity#6]
```
[tru@sillage singularity]$ cat find.sspec
Name: find
Exec: /usr/bin/find
```

echo does not look right ;)

```
[tru@sillage singularity]$ singularity build find.sspec
\e[0;39mBuilding: find
\e[0;39m\e[0;39mChecking paths...
\e[0;39m\e[0;39mChecking writable...
\e[0;39m\e[0;39mEvaluating: %packages
\e[0;39m\e[0;39mCreating template configs
\e[0;39m\e[0;39m  /etc/nsswitch.conf
\e[0;39m\e[0;39m  /etc/resolv.conf
\e[0;39m\e[0;39m  /etc/hosts
\e[0;39m\e[0;39mEvaluating: hard requirements
\e[0;39m\e[0;39mInstalling file: /bin/sh
\e[0;39m\e[0;39mEvaluating: %exec
\e[0;39m\e[0;39mInstalling file: /usr/bin/find
\e[0;39m\e[0;39mEvaluating: %files
\e[0;39m\e[0;39mInvoking dependency check
\e[0;39m\e[0;39mInstalling file: /lib64/libselinux.so.1
\e[0;39m\e[0;39mInstalling file: /lib64/libc.so.6
\e[0;39m\e[0;39mInstalling file: /lib64/libdl.so.2
\e[0;39m\e[0;39mInstalling file: /lib64/libsepol.so.1
\e[0;39m\e[0;39mInstalling file: /lib64/ld-linux-x86-64.so.2
\e[0;39m\e[0;39mInstalling file: /lib64/libtermcap.so.2
\e[0;39m\e[0;39mInstalling file: /lib64/libnss_files.so.2
\e[0;39m\e[0;39mInstalling file: /lib64/libnss_dns.so.2
\e[0;39m\e[0;39mInstalling file: /lib64/libresolv.so.2
\e[0;39m\e[0;39mIncluding SAPPFILE
\e[0;39m\e[0;39mCalculating container size
\e[0;39m\e[0;39mCalculating checksums
\e[0;39m\e[0;39mWriting metadata
\e[0;39mdirname: extra operand `./lib64/libresolv.so.2'
Try `dirname --help' for more information.
\e[0;39mBuilding primary singularity exec driver
\e[0;39m\e[0;39mBuilding singularity test runscript
\e[0;39m\e[0;39mBuilding singularity main runscript
\e[0;39m\e[0;39mRunning %test...
\e[0;39m\e[0;39mCleaning up unpackaged files
\e[0;39m\e[0;39mCreating output SAPP container
\e[0;39m\e[0;39mWROTE: find.sapp
```

runtime:

```
[tru@sillage singularity]$ ./find.sapp 
ERROR: Could not stat /home/tru/.sapp-cache/./find/c!
/usr/libexec/singularity/run.exec: line 79: /home/tru/.sapp-cache/./find/c/pids: No such file or directory
sed: can't read /home/tru/.sapp-cache/./find/c/pids: No such file or directory

[tru@sillage singularity]$ singularity run find
ERROR: Could not stat /home/tru/.sapp-cache/find/c!
/usr/libexec/singularity/run.exec: line 79: /home/tru/.sapp-cache/find/c/pids: No such file or directory
sed: can't read /home/tru/.sapp-cache/find/c/pids: No such file or directory

[tru@sillage singularity]$ find /home/tru/.sapp-cache/ -ls
486539395    0 drwxr-xr-x   3 tru      Bis            17 Nov 30 12:38 /home/tru/.sapp-cache/
499539116    0 drwxr-xr-x   2 tru      Bis            16 Nov 30 12:38 /home/tru/.sapp-cache/find
499539121    4 -rw-r--r--   1 tru      Bis            33 Nov 30 12:38 /home/tru/.sapp-cache/find/sum

```

**Comment by gmkurtzer** [comment]
Hrmm, quite odd. I did change the call to echo to reference /bin/echo to avoid shell internal, but that version should take the color bits just fine. Does this work properly on Centos-6?

Regarding the runtime (and the error during build), that might be fixed by some of the LD_LIBRARY_PATH fixups I made/making. Interesting, it seems like 'dirname' only takes one argument on centos5?

**Comment by truatpasteurdotfr** [comment]
On Mon, Nov 30, 2015 at 07:13:16AM -0800, Gregory M. Kurtzer wrote:

> Hrmm, quite odd. I did change the call to echo to reference /bin/echo
> to avoid shell internal, but that version should take the color bits
> just fine. Does this work properly on Centos-6?
> I don't have colored output in my gnome-terminal but maybe it's my
> setup. Nevertherless, if I '| cat -tve' it does dosplay the escape
> characters:

CentOS-6
[tru@hp-elite840g1-1 singularity]$ singularity build find.sspec
Building: find
Checking paths...
Checking writable...
Evaluating: %packages
Creating template configs
  /etc/nsswitch.conf
  /etc/resolv.conf
  /etc/hosts
Evaluating: hard requirements
Installing file: /bin/sh
Evaluating: %exec
Installing file: /bin/find
Evaluating: %files
Invoking dependency check
Installing file: /lib64/librt.so.1
Installing file: /lib64/libm.so.6
Installing file: /lib64/libselinux.so.1
Installing file: /lib64/libc.so.6
Installing file: /lib64/libpthread.so.0
Installing file: /lib64/ld-linux-x86-64.so.2
Installing file: /lib64/libdl.so.2
Installing file: /lib64/libtinfo.so.5
Installing file: /lib64/libnss_files.so.2
Installing file: /lib64/libnss_dns.so.2
Installing file: /lib64/libresolv.so.2
Including SAPPFILE
Calculating container size
Calculating checksums
Writing metadata
Building primary singularity exec driver
Building singularity test runscript
Building singularity main runscript
Running %test...
Cleaning up unpackaged files
Creating output SAPP container
WROTE: find.sapp

[tru@hp-elite840g1-1 singularity]$ singularity build find.sspec | cat -tve
^[[0;39mBuilding: find$
^[[0;39m^[[0;39mChecking paths...$
^[[0;39m^[[0;39mChecking writable...$
^[[0;39m^[[0;39mEvaluating: %packages$
^[[0;39m^[[0;39mCreating template configs$
^[[0;39m^[[0;39m  /etc/nsswitch.conf$
^[[0;39m^[[0;39m  /etc/resolv.conf$
^[[0;39m^[[0;39m  /etc/hosts$
^[[0;39m^[[0;39mEvaluating: hard requirements$
^[[0;39m^[[0;39mInstalling file: /bin/sh$
^[[0;39m^[[0;39mEvaluating: %exec$
^[[0;39m^[[0;39mInstalling file: /bin/find$
^[[0;39m^[[0;39mEvaluating: %files$
^[[0;39m^[[0;39mInvoking dependency check$
^[[0;39m^[[0;39mInstalling file: /lib64/librt.so.1$
^[[0;39m^[[0;39mInstalling file: /lib64/libm.so.6$
^[[0;39m^[[0;39mInstalling file: /lib64/libselinux.so.1$
^[[0;39m^[[0;39mInstalling file: /lib64/libc.so.6$
^[[0;39m^[[0;39mInstalling file: /lib64/libpthread.so.0$
^[[0;39m^[[0;39mInstalling file: /lib64/ld-linux-x86-64.so.2$
^[[0;39m^[[0;39mInstalling file: /lib64/libdl.so.2$
^[[0;39m^[[0;39mInstalling file: /lib64/libtinfo.so.5$
^[[0;39m^[[0;39mInstalling file: /lib64/libnss_files.so.2$
^[[0;39m^[[0;39mInstalling file: /lib64/libnss_dns.so.2$
^[[0;39m^[[0;39mInstalling file: /lib64/libresolv.so.2$
^[[0;39m^[[0;39mIncluding SAPPFILE$
^[[0;39m^[[0;39mCalculating container size$
^[[0;39m^[[0;39mCalculating checksums$
^[[0;39m^[[0;39mWriting metadata$
^[[0;39m^[[0;39mBuilding primary singularity exec driver$
^[[0;39m^[[0;39mBuilding singularity test runscript$
^[[0;39m^[[0;39mBuilding singularity main runscript$
^[[0;39m^[[0;39mRunning %test...$
^[[0;39m^[[0;39mCleaning up unpackaged files$
^[[0;39m^[[0;39mCreating output SAPP container$
^[[0;39m^[[0;39mWROTE: find.sapp$
^[[0;39m[tru@hp-elite840g1-1 singularity]$ 

> Regarding the runtime (and the error during build), that might be
> fixed by some of the LD_LIBRARY_PATH fixups I made/making.
> Interesting, it seems like 'dirname' only takes one argument on
> centos5?

CentOS-5:

tru@sillage singularity]$ singularity build find.sspec 
\e[0;39mBuilding: find
\e[0;39m\e[0;39mChecking paths...
\e[0;39m\e[0;39mChecking writable...
\e[0;39m\e[0;39mEvaluating: %packages
\e[0;39m\e[0;39mCreating template configs
\e[0;39m\e[0;39m  /etc/nsswitch.conf
\e[0;39m\e[0;39m  /etc/resolv.conf
\e[0;39m\e[0;39m  /etc/hosts
\e[0;39m\e[0;39mEvaluating: hard requirements
\e[0;39m\e[0;39mInstalling file: /bin/sh
\e[0;39m\e[0;39mEvaluating: %exec
\e[0;39m\e[0;39mInstalling file: /usr/bin/find
\e[0;39m\e[0;39mEvaluating: %files
\e[0;39m\e[0;39mInvoking dependency check
\e[0;39m\e[0;39mInstalling file: /lib64/libselinux.so.1
\e[0;39m\e[0;39mInstalling file: /lib64/libc.so.6
\e[0;39m\e[0;39mInstalling file: /lib64/libdl.so.2
\e[0;39m\e[0;39mInstalling file: /lib64/libsepol.so.1
\e[0;39m\e[0;39mInstalling file: /lib64/ld-linux-x86-64.so.2
\e[0;39m\e[0;39mInstalling file: /lib64/libtermcap.so.2
\e[0;39m\e[0;39mInstalling file: /lib64/libnss_files.so.2
\e[0;39m\e[0;39mInstalling file: /lib64/libnss_dns.so.2
\e[0;39m\e[0;39mInstalling file: /lib64/libresolv.so.2
\e[0;39m\e[0;39mIncluding SAPPFILE
\e[0;39m\e[0;39mCalculating container size
\e[0;39m\e[0;39mCalculating checksums
\e[0;39m\e[0;39mWriting metadata
\e[0;39m\e[0;39mBuilding primary singularity exec driver
\e[0;39m\e[0;39mBuilding singularity test runscript
\e[0;39m\e[0;39mBuilding singularity main runscript
\e[0;39m\e[0;39mRunning %test...
\e[0;39m\e[0;39mCleaning up unpackaged files
\e[0;39m\e[0;39mCreating output SAPP container
\e[0;39m\e[0;39mWROTE: find.sapp
\e[0;39m[tru@sillage singularity]$ singularity build find.sspec | cat -tve
\e[0;39mBuilding: find$
\e[0;39m\e[0;39mChecking paths...$
\e[0;39m\e[0;39mChecking writable...$
\e[0;39m\e[0;39mEvaluating: %packages$
\e[0;39m\e[0;39mCreating template configs$
\e[0;39m\e[0;39m  /etc/nsswitch.conf$
\e[0;39m\e[0;39m  /etc/resolv.conf$
\e[0;39m\e[0;39m  /etc/hosts$
\e[0;39m\e[0;39mEvaluating: hard requirements$
\e[0;39m\e[0;39mInstalling file: /bin/sh$
\e[0;39m\e[0;39mEvaluating: %exec$
\e[0;39m\e[0;39mInstalling file: /usr/bin/find$
\e[0;39m\e[0;39mEvaluating: %files$
\e[0;39m\e[0;39mInvoking dependency check$
\e[0;39m\e[0;39mInstalling file: /lib64/libselinux.so.1$
\e[0;39m\e[0;39mInstalling file: /lib64/libc.so.6$
\e[0;39m\e[0;39mInstalling file: /lib64/libdl.so.2$
\e[0;39m\e[0;39mInstalling file: /lib64/libsepol.so.1$
\e[0;39m\e[0;39mInstalling file: /lib64/ld-linux-x86-64.so.2$
\e[0;39m\e[0;39mInstalling file: /lib64/libtermcap.so.2$
\e[0;39m\e[0;39mInstalling file: /lib64/libnss_files.so.2$
\e[0;39m\e[0;39mInstalling file: /lib64/libnss_dns.so.2$
\e[0;39m\e[0;39mInstalling file: /lib64/libresolv.so.2$
\e[0;39m\e[0;39mIncluding SAPPFILE$
\e[0;39m\e[0;39mCalculating container size$
\e[0;39m\e[0;39mCalculating checksums$
\e[0;39m\e[0;39mWriting metadata$
\e[0;39m\e[0;39mBuilding primary singularity exec driver$
\e[0;39m\e[0;39mBuilding singularity test runscript$
\e[0;39m\e[0;39mBuilding singularity main runscript$
\e[0;39m\e[0;39mRunning %test...$
\e[0;39m\e[0;39mCleaning up unpackaged files$
\e[0;39m\e[0;39mCreating output SAPP container$
\e[0;39m\e[0;39mWROTE: find.sapp$

[tru@sillage singularity]$ ./find.sapp 
/usr/libexec/singularity/mods/sappdir_explode: line 47: stdbuf: command
not found

gunzip: stdin: not in gzip format
cpio: premature end of archive
\e[0;31mERROR: SAPP directory not found

-> stdbuf from coreutils-8.4-37.el6_7.3.x86_64 is not available on CentOS-5
(coreutils-5.97-34.el5_8.1.x86_64)

Cheers,

Tru

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gmkurtzer/singularity/issues/6#issuecomment-160657098

## 

Dr Tru Huynh          | http://www.pasteur.fr/research/bis  
mailto:tru@pasteur.fr | tel/fax +33 1 45 68 87 37/19
Institut Pasteur, 25-28 rue du Docteur Roux, 75724 Paris CEDEX 15 France

**Comment by gmkurtzer** [comment]
I am still thinking about how best to do the color management. Also, I think I'll remove the stdbuff command then (or at some point write my own version to include). This means that the specgen command will most likely need to run to completion to properly populate the specfile (e.g. can't ctrl-c it).

Thanks!

**Comment by gmkurtzer** [comment]
On your Centos 5 system, can you use tput to change color? Can you test this?

$ red=`tput setaf 1`
$ normal=`tput sgr0`
$ /bin/echo -e "${red}hi${normal}"

Thanks!

**Comment by truatpasteurdotfr** [comment]
On Mon, Nov 30, 2015 at 10:17:32AM -0800, Gregory M. Kurtzer wrote:

> On your Centos 5 system, can you use tput to change color? Can you test this?
> 
> $ red=`tput setaf 1`
> $ normal=`tput sgr0`
> $ /bin/echo -e "${red}hi${normal}"
> I get a 'hi' in red a the begining of the line, the following lines are
> not colored.
> $ /bin/echo -e "${red}hi${normal} there"
> hi there
> hi is red
> there is printed in green (my default font color).

Work fine on both CentOS-5 6 and 7.

:D

Cheers

Tru

## 

Dr Tru Huynh          | http://www.pasteur.fr/research/bis  
mailto:tru@pasteur.fr | tel/fax +33 1 45 68 87 37/19
Institut Pasteur, 25-28 rue du Docteur Roux, 75724 Paris CEDEX 15 France

**Comment by gmkurtzer** [comment]
Awesome, that is how we will do it then! I'll update the code and let you know when it's ready. Thanks!

**Comment by gmkurtzer** [comment]
Hiya Tru,

I updated the code to use tput, can you test it?

Thank you!

**Comment by truatpasteurdotfr** [comment]
yes, that works :P on all 3 centos versions
