### ISSUE TITLE
Verify that the dependencies for 3.8.0 are all up to date

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#6009]
Before the final 3.8.0 release is cut, we should make sure that all the dependencies are up to date, especially looking for any security fixes in dependencies.

**Comment by DrDaveD** [comment]
These are the differences I see between hpcng release-3.8 branch go.mod and the [sylabs released 3.8.0 go.mod](https://raw.githubusercontent.com/sylabs/singularity/v3.8.0/go.mod), after adjusting for branch name differences:
```
6a7
> 	github.com/Microsoft/go-winio v0.5.0 // indirect
15,16c16,17
< 	github.com/containerd/cgroups v0.0.0-20210114181951-8a68de567b68
< 	github.com/containerd/containerd v1.5.0-beta.4
---
> 	github.com/containerd/cgroups v1.0.1
> 	github.com/containerd/containerd v1.5.2
20,21c21
< 	github.com/deislabs/oras v0.11.1
< 	github.com/fatih/color v1.11.0
---
> 	github.com/fatih/color v1.12.0
26c26
< 	github.com/golang/protobuf v1.5.2 // indirect
---
> 	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
29c29
< 	github.com/hpcng/sif v1.2.2
---
> 	github.com/hpcng/sif v1.2.3
33a34
> 	github.com/opencontainers/runc v1.0.0-rc94 // indirect
37a39
> 	github.com/oras-project/oras-go v0.1.0
57c59,62
< 	golang.org/x/crypto v0.0.0-20210322153248-0c34fe9e7dc2
---
> 	go.opencensus.io v0.23.0 // indirect
> 	golang.org/x/crypto v0.0.0-20210503195802-e9a32991a82e
> 	golang.org/x/net v0.0.0-20210510120150-4163338589ed // indirect
> 	golang.org/x/sync v0.0.0-20210220032951-036812b2e83c // indirect
58a64,65
> 	google.golang.org/genproto v0.0.0-20210510173355-fb37daa5cd7a // indirect
> 	google.golang.org/grpc v1.37.0 // indirect
```

**Comment by DrDaveD** [comment]
These are addressed in #5988, #5998 (already merged in master), and in Sylabs PRs [#22](https://github.com/sylabs/singularity/pull/22), [#30](https://github.com/sylabs/singularity/pull/30).  The golang/x/crypto was also updated as part of Sylabs PR [#11](https://github.com/sylabs/singularity/pull/11) which updated sif to 1.2.2.  @ikaneshiro @cclerget do you think we should include any of those in 3.8.0?  The biggest number of changes was in Sylabs 30.

**Comment by ikaneshiro** [comment]
I think we need to have a stance on what can be changed between an RC and a release without cutting a new RC. 

Do you feel dependencies are low enough risk to do so? 

The purpose of the RCs has been to allow everyone to test the release exactly as it will be and report issues before it comes out to avoid a quick patch release. That feedback has diminished over time to the point where we usually don't hear reports of issues on RCs, so I am OK with updating all dependencies that don't require significant code changes.

**Comment by DrDaveD** [comment]
I do think they are low enough risk.  What I don't know is if it is worth it.  Anyway I will go ahead and make a PR against the master branch, and then we can decide.

**Comment by DrDaveD** [comment]
The equivalent of sylabs pr 30 is #6013 and pr 22 (w/ golang/x/crypto update from 11) is #6018.

**Comment by pedroalvesbatista** [comment]
> The equivalent of sylabs pr 30 is #6013 and pr 22 (w/ golang/x/crypto update from 11) is #6018.

Are you already checking this one ? If not, I can take it.

**Comment by DrDaveD** [comment]
These are all merged, closing.
