### ISSUE TITLE
[development] owner issue after "singularity copy"

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#601]
# A `Permission denied` when calling a bin after copy command
```bash
$ singularity --version
$    2.2.99
```
After 

```bash
$ sudo singularity copy myimage.img the.sh /usr/bin/
```
when calling it
```bash
$ singularity exec myimage.img the.sh
$ /bin/sh: /usr/bin/the.sh: Permission denied
```
In host 
```bash
$ ls -l
$ -rwx--x--x. 1 eduardo root    282 Jan 30 11:34 the.sh
```
Inside the container 
```bash
$ singularity shell myimage.img
$ singularity-shell-> ls /usr/bin/
$ -rwx--x--x. 1 root root    282 Jan 30 11:34 the.sh
```

thoughts?

**Comment by vsoch** [comment]
A possible workaround, and I agree this should work off the bat!

```
vanessa@som-ctp:~$ chmod 775 script.sh
vanessa@som-ctp:~$ sudo chown root script.sh
vanessa@som-ctp:~$ sudo singularity copy rosdep.img -p script.sh /bin
vanessa@som-ctp:~$ singularity exec rosdep.img ls -l /bin/script.sh
-rwxrwxr-x 1 root vanessa 11 Apr 13 16:07 /bin/script.sh
vanessa@som-ctp:~$ singularity exec rosdep.img /bin/script.sh
Hello
```
You can also skip `chmod` and `chown` and just use -p, and then `ls -l` would show `vanessa vanessa`

**Comment by gmkurtzer** [comment]
That is an interesting problem, and I'm open to suggestions. Basically, singularity is wrapping the default behavior of the `cp` program, and that is the expected behavior of `cp`. There are two options:

1. Document proper usage of `singularity copy` such that it should incude an option like: `singularity copy myimage.img -p script.sh /usr/bin/script.sh`
2. Include some various common options to the `cp` command by default (e.g. `-p`).

Note that in both cases, this means the default behavior of `cp -p`will also copy the file's owner/group, which we also may not want.

Thoughts?

**Comment by ArangoGutierrez** [comment]
Well for 1:
 - Documentation is always important so yes to this point.
for 2 : 
 - add to the `-h|--help` some common options to help the users, if they don't know the native commands for cp.

**Comment by vsoch** [comment]
I think generally we should discourage users copying stuff into containers after creation - there is no record of it and it's not reproducible. Given that using `%files` works without a hitch, I think copy should be more of "use at your own risk." And in this case, we will provide ample documentation about the options that should be used to do the copy (eg -p).

**Comment by vsoch** [comment]
I'm updating the docs now.

**Comment by ArangoGutierrez** [comment]
+1 on
" "use at your own risk." And in this case, we will provide ample documentation about the options that should be used to do the copy (eg -p)."

**Comment by vsoch** [comment]
This is pretty interesting, actually doing a mount with sudo and then using -p preserves everything! I'll show you in a second.

**Comment by vsoch** [comment]
https://github.com/singularityware/singularityware.github.io/blob/docs/2.3/pages/docs/user-docs/docs-content.md#mount

**Comment by vsoch** [comment]
@ArangoGutierrez is this issue resolved for you?

**Comment by ArangoGutierrez** [comment]
Sure @vsoch 
Closing issue #601
