### ISSUE TITLE
Update linter to version 1.41.0

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#6023]
Update golangci-lint the way Sylabs did in their [pr 41](https://github.com/sylabs/singularity/pull/41).

**Comment by pedroalvesbatista** [comment]
For doing this, is necessary put hands on code in golangci-lit, or just the normal flow we've being done until now ?

**Comment by DrDaveD** [comment]
Just do it the way that Sylabs did it, and test to make sure it works in a branch against hpcng/singularity:master

**Comment by DrDaveD** [comment]
Oh, but yes, testing will involve getting golangci-lint, but that is retrieved automatically.  You can test with `make -C builddir check`.
