### ISSUE TITLE
Update go version in ci to 1.16.4

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#6024]
Update go in ci builds to version 1.16.4 the way that Sylabs did in their [pr 45](https://github.com/sylabs/singularity/pull/45) before their version 3.8.0.  @ikaneshiro @cclerget do you think we should we put this in our 3.8.0 or wait until later?

**Comment by DrDaveD** [comment]
For now I'm going to add it to 3.8.0 milestone so we don't forget it.

**Comment by DrDaveD** [comment]
INSTALL.md already refers to go version 1.16.4 so if we don't do this we should reduce the number recommended there.

**Comment by Kunzol** [comment]
**Reminder:** Debian Bullseye and Debian Sid have Go version 1.15 included. 

If you really plan to get this in a official Debian Repository, a requirement of Go version 1.16 might get a "show-stopper".

As Debian Buster-Backports is build on Debian Bullseye, it means for users of Debian Buster, they really have to build Go from source.

**Comment by Kunzol** [comment]
**Reminder:** Ubuntu Hirsute (21.04) is the first Ubuntu with Go version 1.16 (1.16.4?), which is not LTS. 

The first Ubuntu LTS with Go version >= 1.16 is most probably Ubuntu 22.04.

**Comment by DrDaveD** [comment]
This only involves changing the version used in the CI system, not the required version.  The minimum required version is set in mconfig as 1.13.  So it should be fine.  I'm pretty sure the CI system downloads its golang anyway so it can use any version.  CentOS 7 has a similar limitation as Debian, the current version there is 1.15.5.

**Comment by ikaneshiro** [comment]
Going up to `1.16.x` in CI makes sense, I would leave this as tracking for `3.8.0` for now and discuss what we have in the milestone during the community meeting. We need to pick a date for a release and determine what should/shouldn't be included based on that since this isn't a breaking issue for the release.

**Comment by DrDaveD** [comment]
I was hoping to have a 3.8.0-rc.3 or 3.8.0 ready by the time of the community meeting Tuesday.  In any case since you agree it's good to do I'll go ahead and make a PR for it.
