### ISSUE TITLE
Log plugin image value is almost useless

### ISSUE THREAD

**Issue by treydock** [apptainer/singularity#6032]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.7.1
```

### Expected behavior

I would expect this:

```
singularity run library://lolcow
```

To produce this log message when the log plugin is enabled:

```
UID=0 IMAGE=library://lolcow COMMAND=run
```

If someone could point me in the direction of where to look at referencing the actual image used with `run` command I'd be happy to open a pull request.  Right now it seems that `cfg.GetImage()` is not entirely useful if it's going to reference the extracted cache image.

### Actual behavior

```
UID=0 IMAGE=/root/.singularity/cache/library/sha256.9b0dafaadb1cd1d14e4fbad23798730a938bafb9e6ad5f86e00ffb5b4541e576 COMMAND=run
```

### Steps to reproduce this behavior

Install Singularity and install the plugin from `examples/plugins/log-plugin`, then run a singularity container using something like `library://`.

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

### How did you install Singularity

I installed from source inside a docker container to test out log plugin.

**Comment by DrDaveD** [comment]
@cclerget could correct me if I'm wrong, but I believe that plugin is just an example of how to use the plugin API and not really intended to be useful.   If you want to use the plugin system and find something lacking in the API, a pull request adding a new API call is likely to be accepted as long as it is safe.

**Comment by treydock** [comment]
I think the log plugin, even if an example, could be extremely useful to get back Singularity 2.x behavior of having good logging of which containers are getting used.  I think the API just needs some minor tweaks to store the original image arguments in the engine config struct. I fiddled with all sorts of ways to get the data without API changes and none worked so I think the API change is only possible way to make the example log plugin more useful.
