### ISSUE TITLE
install singularity with a trouble

### ISSUE THREAD

**Issue by yzyupup** [apptainer/singularity#6041]
[root@localhost builddir]# make
 GEN GO DEP /src/github.com/hpcng/singularity/builddir/starter.d
go: github.com/AdamKorcz/go-fuzz-headers@v0.0.0-20210319161527-f761c2329661: Get "https://proxy.golang.org/github.com/%21adam%21korcz/go-fuzz-headers/@v/v0.0.0-20210319161527-f761c2329661.mod": dial tcp 172.217.24.17:443: i/o timeout
 GEN GO DEP /src/github.com/hpcng/singularity/builddir/singularity.d
go: github.com/AdamKorcz/go-fuzz-headers@v0.0.0-20210319161527-f761c2329661: Get "https://proxy.golang.org/github.com/%21adam%21korcz/go-fuzz-headers/@v/v0.0.0-20210319161527-f761c2329661.mod": dial tcp 172.217.24.17:443: i/o timeout
 GEN /src/github.com/hpcng/singularity/scripts/go-generate
go: github.com/AdamKorcz/go-fuzz-headers@v0.0.0-20210319161527-f761c2329661: Get "https://proxy.golang.org/github.com/%21adam%21korcz/go-fuzz-headers/@v/v0.0.0-20210319161527-f761c2329661.mod": dial tcp 172.217.24.17:443: i/o timeout
make: *** [/src/github.com/hpcng/singularity/scripts/go-generate] Error 1

According to your previous prompt, I have directed the go server to GOPROXY := https://goproxy.cn,direct. But I still have the same problem
could you help me ,thanks!
![b26a63972cf57d7aeae3dc3dc1d7a04](https://user-images.githubusercontent.com/54492151/122051781-8d973a00-ce17-11eb-8c1f-cc7bbc2f555c.png)

**Comment by DrDaveD** [comment]
It doesn't appear to be trying https://goproxy.cn.  Did you export GOPROXY?  Here is [more information](https://arslan.io/2019/08/02/why-you-should-use-a-go-module-proxy/) about GOPROXY.

**Comment by yzyupup** [comment]
> It doesn't appear to be trying https://goproxy.cn. Did you export GOPROXY? Here is [more information](https://arslan.io/2019/08/02/why-you-should-use-a-go-module-proxy/) about GOPROXY.

ok，fine. I tried again and it worked. Thank you very much!
