### ISSUE TITLE
Create a container failed

### ISSUE THREAD

**Issue by yzyupup** [apptainer/singularity#6045]
I want to create a container named nd_env but failed, could you give me some advice, thanks!
![7775dbb05b8372d2f70321ecc0896d6](https://user-images.githubusercontent.com/54492151/122205908-5ab27c00-ced3-11eb-9065-3ba57557c282.png)

**Comment by ikaneshiro** [comment]
Hi @yzyupup, how did you install `squashfs` tooling on your system? If you installed it through a package manager, it should have installed all dependencies as well. 

It looks like `unsquashfs` can't find a library it needs to decompress data (libz.so.1). Idk what distrobution you are running on, but you can try `apt-get install zlib1g-dev` for Ubuntu and `yum install zlib-devel` for rpm based systems

**Comment by yzyupup** [comment]
> 嗨@yzyupup，你是如何`squashfs`在你的系统上安装工具的？如果您通过包管理器安装它，它应该也安装了所有依赖项。
> 
> 似乎`unsquashfs`找不到解压缩数据所需的库（libz.so.1）。知道你正在运行什么发行版，但你可以尝试`apt-get install zlib1g-dev`使用 Ubuntu 和`yum install zlib-devel`基于 rpm 的系统

**Comment by yzyupup** [comment]
> Hi @yzyupup, how did you install `squashfs` tooling on your system? If you installed it through a package manager, it should have installed all dependencies as well.
> 
> It looks like `unsquashfs` can't find a library it needs to decompress data (libz.so.1). Idk what distrobution you are running on, but you can try `apt-get install zlib1g-dev` for Ubuntu and `yum install zlib-devel` for rpm based systems

thanks for your help .  My system is centos7, and the system shows that zlib-devel has been installed。
<img width="1259" alt="526dd21e5dcb6fbb41b865b699ae86f" src="https://user-images.githubusercontent.com/54492151/122242690-1edcde00-cef6-11eb-8be1-bb6fd9b08e5d.png">

**Comment by yzyupup** [comment]
> squashfs
Thanks for your help, I tried to install squashfs again and it succeeded this time.
