### ISSUE TITLE
Lets add pointers to the Community Meetings in the Readme file

### ISSUE THREAD

**Issue by kmuriki** [apptainer/singularity#6060]
As we resumed the Singularity Community meetings, Should we put a pointer to the community meetings minutes in the README file.md as done in [Sylabs PR #97](https://github.com/sylabs/singularity/pull/97)

**Comment by DrDaveD** [comment]
No, I don't think that's necessary.  We don't have a "community" github repository like they do.  We've got a Help page which links people to the mailing list and the slack, and we post links to the meeting minutes there.
