### ISSUE TITLE
Replacing UUID Module

### ISSUE THREAD

**Issue by kmuriki** [apptainer/singularity#6063]
@ikaneshiro Sylabs PR 111(https://github.com/sylabs/singularity/pull/111) also looks applicable to us. Could you confirm to pull the commits ? I can do the work. Thanks.

**Comment by DrDaveD** [comment]
I think we're going to want that.

**Comment by ikaneshiro** [comment]
@kmuriki Yes this is something we should pull in

**Comment by DrDaveD** [comment]
Fixed in #6094
