### ISSUE TITLE
bash syntax error at end of yum bootstrap 

### ISSUE THREAD

**Issue by akkornel** [apptainer/singularity#607]
Yo!

This happened during a yum bootstrap:

```
/usr/local/libexec/singularity/bootstrap-scripts/post.sh: eval: line 57: syntax error near unexpected token `('
/usr/local/libexec/singularity/bootstrap-scripts/post.sh: eval: line 57: `/usr/local/libexec/singularity/python/helpers/json/add.py -f --key SINGULARITY_BOOTSTRAP_VERSION --value 2.2.99 (development/388c86b) --file /var/lib/singularity/mnt/source/.singularity.d/labels.json'
```

Here's the basic bootstrap file I'm using: https://gist.github.com/akkornel/b9cd992af449f0573285f1187aabfd9d

Here's the problem appearing, right at the end of the bootstrap: https://asciinema.org/a/113783

My Git working copy is current to 388c86b3f612c64845aa479877f495c8fc183ea3.

**Comment by akkornel** [comment]
Oh, I see now.  Because the version number for non-releases now has spaces, bash is trying to parse them.

Grrrrr.

**Comment by vsoch** [comment]
@satra lol

**Comment by vsoch** [comment]
you're in trouble now!!

**Comment by satra** [comment]
@vsoch, @gmkurtzer  - perhaps we should just use semantic versioning `2.2.99-dev.g388c86b`

**Comment by akkornel** [comment]
@satra The problem is actually bigger than just the version: The current bash script does not do any escaping, so this issue could easily appear some other way.

I also like the current non-release version number, as it makes it so much easier to see where it came from (since it includes the local branch name).

My suggestion is, leave the version number the way it is, and update the bash script to properly escape things when needed (such as when doing `eval`s).

I'm working on a pull to do exactly that.

**Comment by vsoch** [comment]
ok this sounds good too.

**Comment by satra** [comment]
@akkornel - sounds good. #608 doesn't change the information - just the style of displaying that information, which imo is a bit cleaner. 

feel free to close the pull request if the style doesn't need to change.

**Comment by akkornel** [comment]
OK, my PR is in and going through CI.  Note that my PR (#609) doesn't conflict with #608; that PR could still go in, but now the discussion is changed to "What version format should be used?" instead of "What version format doesn't break things?"!

**Comment by gmkurtzer** [comment]
I've merged @satra's PR, is this still an issue on the latest development branch? Thanks!

**Comment by akkornel** [comment]
Nope, it's OK now.
