### ISSUE TITLE
without sudo can not use pytorch

### ISSUE THREAD

**Issue by VincentWPJ** [apptainer/singularity#6074]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version
singularity-ce version 3.8.0-rc.1+145-gc85a93c
```

### Expected behavior

What did you expect to see when you do...?
I build a image(ubuntu20.04 with gcc9.3.0) in my own machine, and want to run python script with pytorch.  everything is good when I use "sudo singularity shell" to start a container, but if I just use "singularity shell" to start it , it can not work.

### Actual behavior

What actually happend? Why was it incorrect?
when I use "singularity shell" run python script, I will get the error :"ImportError: libtinfo.so.5: cannot open shared object file: No such file or directory"

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
in local machine:
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial


in container:
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal



```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

**Comment by kmuriki** [comment]
Singularity repo is now retired as the code base is now moved to Apptainer. We are closing all the old issues under the old Singularity repo. For further assistance please open a new issue under the new Apptainer repo. Thanks for your support.
