### ISSUE TITLE
 allow for fakeroot subuid/subgid mappings shorter than 65536 IDs

### ISSUE THREAD

**Issue by thdesy** [apptainer/singularity#6082]
### Version of Singularity:

`3.7.3-1.el7`

### Expected behavior

Running singularity with a limited range of `subuid`/`subgid` for `fakeroot`.
We would like to enable `fakeroot` for our users. But we would like to keep the mapped IDs constraint and consistent with our campus-wide uid policy to avoid potential clashes.  To do so, we reserved a blcok of UIDs in our ID namespace to be used only for such dynamic, container-flavoured mappings, that are not to be used for other purposes or actual users. Since the block is currently limited in its range (100k), we can allocate only a limited sub-block of IDs to each others.

```
> head  -n4 /etc/subuid
# Managed by Puppet (subuid)
# Do NOT edit, changes will be overwritten!
foouser:23000000:100
bazuser:23000100:100
...
```

```
> head  -n4 /etc/subdid
# Managed by Puppet (subuid)
# Do NOT edit, changes will be overwritten!
foouser:23000000:100
bazuser:23000100:100
...
```

### Actual behavior

Singularity requires a block with at least 2^16 IDs for a user

```
>  singularity build --fakeroot --sandbox testbuild.d  Singularity
FATAL:   could not use fakeroot: mapping entries for user foouser found in /etc/subuid but all with a range count lower than 65536
```

Since we assume, that users will need during container builds or runs of their analyses containers only a few UIDs, it would be nice, if an admin could allow for smaller sub-ID ranges.

**Comment by DrDaveD** [comment]
Hi Thomas.  I reopened #5932 instead so it keeps the history.  I think the time for stalebot is going to be lengthened from 60 days, that's awfully short.
