### ISSUE TITLE
Warnings: [Bootstrap Image Could Not Be Verified] && [Skipping Mount]

### ISSUE THREAD

**Issue by zalhadda** [apptainer/singularity#6085]
### Version of Singularity:

**What version of Singularity are you using? Run:**

```
$ singularity --version
singularity-ce version 3.8.1

```

### Expected behavior

**What did you expect to see when you do...?**

I was expecting to be able to build a singularity image that would allow me to access the files on the host system to install a software.

### Actual behavior

**What actually happened? Why was it incorrect?**

I received two warnings when building with regards to the bootstrap image:

```
sudo singularity build --sandbox ubuntu/ library://ubuntu
Build target 'ubuntu' already exists and will be deleted during the build process. Do you want to continue? [N/y] y
INFO:    Starting build...
INFO:    Using cached image
INFO:    Verifying bootstrap image /root/.singularity/cache/library/sha256.02ee8bf9dc335c244f8af97b901c5f62506e687ed54a8adc940d5996266dd344
WARNING: integrity: signature not found for object group 1
WARNING: Bootstrap image could not be verified, but build will continue.
INFO:    Creating sandbox directory...
INFO:    Build complete: ubuntu/
```

And an inability to mount when accessing the shell:
```
sudo singularity shell --writable ubuntu/
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
```

And I'm unable to access any files in the $HOME directory of the user (with root permissions).

### Steps to reproduce this behavior

**How can others reproduce this issue/problem?**
- Build a singularity container with sudo with library://ubuntu.
- Attempt to access the singularity shell with --writable.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Singularity

**Write here how you installed Singularity. Eg. RPM, source.**
I downloaded singularity from a release as per the documentation instructions over [here](https://sylabs.io/guides/3.5/user-guide/quick_start.html#download-singularity-from-a-release).

**Comment by zalhadda** [comment]
I want to add that following the same commands as per the document to build lolcow (seen [here](https://sylabs.io/guides/3.8/user-guide/build_a_container.html)), results in the same errors.

**Comment by DrDaveD** [comment]
Since this is for singularity-ce, please instead submit an issue to https://github.com/sylabs/singularity.
