### ISSUE TITLE
Invalid path for --pwd is ignored instead of producing an error

### ISSUE THREAD

**Issue by mlell** [apptainer/singularity#6086]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version
singularity version 3.8.0-1.el7
```

### Expected behavior

When I specify the `--pwd` command to `singularity exec`, I expect that the working directory is set to that location. When the location does not exist, I expect an error, in the same way that `cd` behaves (and any similar function in all interpreted programming languages I know, `setwd()` in R, `os.chdir()` in Python, ...)

### Actual behavior

If the path to `--pwd`  does not exist inside the container, it defaults to `$HOME`. I can not imagine a situation where this default would be useful if I give `--pwd` explicitly. Also this might lead to files being overwritten by accident if singularity for example was called by a script which assumes that the working directory is set successfully because there was no error by singularity.

### Steps to reproduce this behavior
```
singularity pull library://default/alpine
singularity exec --pwd /etc alpine_latest.sif
# /etc
singularity exec --pwd /no/such/path alpine_latest.sif
# /home/user
```

### What OS/distro are you running
centos-release-7-9.2009.1.el7.centos.x86_64

### How did you install Singularity

Via `yum`.

**Comment by DrDaveD** [comment]
I agree this is bad behavior.  @cclerget do you agree?
