### ISSUE TITLE
Vagrant memory customization does not work

### ISSUE THREAD

**Issue by BoudSTER** [apptainer/singularity#6140]
### Version of Singularity:

singularity version 3.0.3-1

### Expected behavior

Creation SIF complete

### Actual behavior

Error
OSError(12, 'Cannot allocate memory')

### Explanation 

I'm trying to increase the size of my vagrant virtual machine allowing me to build singularity without much success... I searched on internet and applied scrupulously different config but nothing makes. Here is my Vagrant file :

``` 
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "sylabs/singularity-3.0-ubuntu-bionic64"

  ... (comment code)

config.vm.provider "virtualbox" do |v|
  v.memory = 2048
  v.cpus = 2
end
end

``` 

But unfortunately it remains on the basic configuration ...

Thanking you in advance for the time you can give me.

BoudSTER

**Comment by DrDaveD** [comment]
The one you chose is terribly old, please try a more [recent one](https://app.vagrantup.com/boxes/search?order=desc&page=1&provider=&q=singularity&sort=created&utf8=%E2%9C%93).  

If you're still having problems please close this and submit an issue to https://github.com/sylabs/singularity because Sylabs maintains those images.

**Comment by BoudSTER** [comment]
It's work thank you ! 

BoudSTER
