### ISSUE TITLE
No Loop Devices Error when using a large number of MPI processes

### ISSUE THREAD

**Issue by georgiastuart** [apptainer/singularity#6141]
### Version of Singularity:

```
3.7.2-3.el7
```

### Problem Setup

I am attempting to run a singularity container with a large number of MPI processes (56 per node) on the Frontera supercomputer. This problem is similar or identical to #3928 , which was marked resolved in v3.5 with PR #4549. 

The command I'm using to run the job is:

```
ibrun singularity exec --bind $SCRATCH:$SCRATCH <singularity image> python <python script>
```

On the system, SHARED LOOP DEVICES is enabled and MAX LOOP DEVICES is set to 512. 

### Expected behavior

I expect MPI to launch 56 processes running singularity. 

### Actual behavior

I get the following error:

```
FATAL:   container creation failed: mount /proc/self/fd/6->/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/6: failed to find loop device: could not attach image file to loop device: no loop devices available
```

This error does not seem to happen all the time and happens less with fewer processes. 

### Steps to reproduce this behavior

Run singularity through a large number of MPI processes. 

### What OS/distro are you running

```
CentOS Linux 7
```

**Comment by DrDaveD** [comment]
I assigned this to Cedric, but he's still on vacation so it could take a while.  You might want to also report it to sylabs/singularity.

**Comment by georgiastuart** [comment]
Thanks! I'll report it on the sylabs repo as well.

**Comment by gmkurtzer** [comment]
Hi @georgiastuart,

Can you post the `--debug` output of this issue please?

Thank you!
Greg

**Comment by georgiastuart** [comment]
Here's the debug info! https://gist.github.com/georgiastuart/3172483873ab002728497e0f8d4e721f

**Comment by gmkurtzer** [comment]
Hi @georgiastuart, thank you.

I don't think this caught all of the debug output as it didn't even get to the loop device setups. If there is just too much output, please grep through the log output for `loop` and forward just those results.

Also, if you can count how many loop devices are already setup with the command `ls -l /dev/loop* | wc -l`

**Comment by georgiastuart** [comment]
@gmkurtzer sorry about that! It looks like the gist was too long to display, but if you view the [raw file](https://gist.githubusercontent.com/georgiastuart/3172483873ab002728497e0f8d4e721f/raw/cd6f352c327dfc325d3ab6e07e97d087c2f7de5d/singularity_debug.out) you can see the loop device lines. Regardless, I've isolated the [loop lines here](https://gist.github.com/georgiastuart/a90469758837d071f59ea35805d2e8f9).

`ls -l /dev/loop* | wc -l` returns 1.

**Comment by cclerget** [comment]
@georgiastuart What's the value returned by  `cat /sys/module/loop/parameters/max_loop` on those nodes ?

**Comment by georgiastuart** [comment]
@cclerget sorry for the delay. That file does not exist on Frontera. I contacted support and confirmed that it is not elsewhere. On Stampede 2, where I do not have this issue, `cat /sys/module/loop/parameters/max_loop` returns 0.
