### ISSUE TITLE
Unit tests, Integration tests failing

### ISSUE THREAD

**Issue by ahkumar** [apptainer/singularity#6147]
### Version of Singularity: singularity-ce version 3.8.2

```
$ cat /etc/os-release
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

### How did you install Singularity

Installed in from the source release

Errors that I see:
[ builddir]$ make unit-test
....
....
....
coverage: 94.4% of statements
ok      github.com/sylabs/singularity/pkg/util/sysctl   0.057s  coverage: 94.4% of statements
=== RUN   TestCreateSocket
--- PASS: TestCreateSocket (0.00s)
PASS
coverage: 83.3% of statements
ok      github.com/sylabs/singularity/pkg/util/unix     0.066s  coverage: 83.3% of statements
=== RUN   TestSingularityVersion
--- PASS: TestSingularityVersion (0.00s)
PASS
coverage: 88.9% of statements
ok      github.com/sylabs/singularity/pkg/util/user-agent       0.055s  coverage: 88.9% of statements
?       github.com/sylabs/singularity/scripts   [no test files]
FAIL
make: *** [unit-test] Error 2
 [ builddir]$ make integration-test
 TEST sudo go test [integration]
=== RUN   TestGetAllNetworkConfigList
--- PASS: TestGetAllNetworkConfigList (0.01s)
=== RUN   TestNewSetup
--- PASS: TestNewSetup (0.02s)
=== RUN   TestAddDelNetworks
    network_linux_test.go:599: unexpected failure for "TestPingIP": exit status 1
    network_linux_test.go:609: signal: killed
    network_linux_test.go:599: unexpected failure for "TestPingRandomIP": exit status 1
    network_linux_test.go:609: signal: killed
    network_linux_test.go:599: unexpected failure for "TestHTTPPortmap": dial tcp :31080: connect: connection timed out
    network_linux_test.go:609: signal: killed
    network_linux_test.go:599: unexpected failure for "TestPingIPRange": exit status 1
    network_linux_test.go:609: signal: killed
--- FAIL: TestAddDelNetworks (160.03s)
FAIL
coverage: 70.8% of statements
FAIL    github.com/sylabs/singularity/pkg/network       160.155s
FAIL
make: *** [integration-test] Error 1

Any idea how can I debug this to see what is going on? Do i need to do anything special to for tcp :31080 to ensure tests succeed? 

Regards,
Amit

**Comment by DrDaveD** [comment]
Amit: Since your issue was with singularity-ce, please close this issue and submit instead to https://github.com/sylabs/singularity.

**Comment by gmkurtzer** [comment]
@ahkumar,

We would be happy to help you debug with the official version of Singularity (which is hosted here in HPCng) but can not help with the commercially controlled Singularity fork being maintained by Sylabs as the projects differ.

If you find that you are having issues with the official version of Singularity, please feel free to reopen this issue.

Warmest regards,
Greg
