### ISSUE TITLE
I get the different env by singularity exec  and singularity instance start.

### ISSUE THREAD

**Issue by xigyou** [apptainer/singularity#6168]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version
singularity version 3.8.0
```

### Expected behavior

What did you expect to see when you do...?
singularity exec --cleanenv --no-home --contain library://ubuntu env

![image](https://user-images.githubusercontent.com/8529190/132173134-76d5d0ce-274d-468a-a71d-2cc256caf2f7.png)

### Actual behavior

What actually happend? Why was it incorrect?
singularity instance start --cleanenv --no-home --contain library://ubuntu top
 
singularity exec instance://top env 

![image](https://user-images.githubusercontent.com/8529190/132173065-ee7ad7ae-8890-4d68-b543-efda08eb9369.png)

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

https://singularity.hpcng.org/admin-docs/3.8/installation.html

**Comment by cclerget** [comment]
Hi @xigyou, `--cleanenv` is a per process option, so `exec instance://...` without `--cleanenv` would show your current environment, if you want to clean it for the execution of a process within an instance, you need to specify
`singularity exec --cleanenv instance://...`

**Comment by xigyou** [comment]
> Hi @xigyou, `--cleanenv` is a per process option, so `exec instance://...` without `--cleanenv` would show your current environment, if you want to clean it for the execution of a process within an instance, you need to specify
> `singularity exec --cleanenv instance://...`

Thank you very very much!  
It works.
now the env is the same.
singularity instance start --no-home --contain library://ubuntu top
singularity exec --cleanenv instance://top env

VS
singularity exec --cleanenv --no-home --contain library://ubuntu env

Thank you again.
