### ISSUE TITLE
root filesystem extraction failed: could not extract squashfs data, unsquashfs not found

### ISSUE THREAD

**Issue by showers14** [apptainer/singularity#6177]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version

singularity-ce version 3.8.1


<!-- please include command-line output in a code block -->

### Expected behavior

What did you expect to see when you do...?

For further documentation and support, consult the main webpage
(https://www.cog-genomics.org/plink/1.9 ) and/or the mailing list
(https://groups.google.com/d/forum/plink2-users ).

### Actual behavior

What actually happend? Why was it incorrect?

INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting hello.sif: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found


<!-- if this is a feature request, you can ignore this next part -->

### Steps to reproduce this behavior

How can others reproduce this issue/problem?


### What OS/distro are you running

```
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

Unprivileged (non-setuid) Installation

**Comment by DrDaveD** [comment]
Please report singularity-ce problems to https://github.com/sylabs/singularity.

**Comment by kw-cn** [comment]
I would like to ask if you have solved this problem, which I am also encountering now

**Comment by DrDaveD** [comment]
This repository is closed.  If you're having a problem, please submit a new issue.  If `singularity --version` says `singularity-ce`, report it at https://github.com/sylabs/singularity, otherwise report it at `https://github.com/apptainer/apptainer`.
