### ISSUE TITLE
Not save env variable

### ISSUE THREAD

**Issue by sazearte** [apptainer/singularity#618]
Hello, when i'm in the contener image, i can change env variable:
```
foo=bar
echo $foo
bar

```
and i can save my conf in the file /etc/environnement or /root/.bashrc or /etc/bashrc
and redeploy my conf with
`source /etc/environnement`

but when exit singulirty and re-open my variable is lost... why ?
can i save or change my env variable in the singularity image ?

**Comment by vsoch** [comment]
Hey @sazearte ! If you want to add variables to your environment, for the development branch you should do this in the environment section of your bootstrap specification file:

```
%environment
foo bar
```

or if you are changing a live container (not recommended practice, it's not reproducible!) you would want to add the variable into `/environment` at the root of the container and one of the files in `/.singularity.d/env/` (likely 10-docker.sh).

**Comment by vsoch** [comment]
If you are editing a (current master) container, then you would just want to add it to the `/environment` file, also at the root of the container.

**Comment by sazearte** [comment]
a ok,
I did not understand what was /environment
I believed that it was /etc/environement file, not /environment

thanks for your explication, it's works now !
