### ISSUE TITLE
make normal UP button inside shell

### ISSUE THREAD

**Issue by antonkulaga** [apptainer/singularity#621]
Whe I shell into the container by
```
singularity shell foo.img
```
and try to run the previous command by pressing "Up" button, I get:
```
 ^[[A
```
Instead of the previous command. This is super annoying, is it possible to fix it?
Just in case, I am running singularity from latest Linux Mint

**Comment by vsoch** [comment]
I am having trouble reproducing this (because I've had the same error for a long time) but I think it has to do with your `$SHELL` variable, specifically this happened for me on ubuntu when I wasn't using bash. What do you have for `$SHELL` both inside and outside the container and does it change when you start the container with `/bin/bash` instead?

**Comment by gmkurtzer** [comment]
What version of singualrity are you using @antonkulaga? 

The development branch should automatically use `/bin/bash` if it is available, where previous versions just always called `/bin/sh`.

**Comment by antonkulaga** [comment]
Here is what I did to get the bug:
```bash
sudo singularity create --size 4000 sra.img
sudo singularity import sra.img docker://itsjeffreyy/sratoolkit
singularity shell sra.img
Singularity.sra.img> ls 
Singularity.sra.img> ^[[A #when I push "up arrow"
```
I use the version from the website, 2.2.1

**Comment by vsoch** [comment]
Could you try the development branch? We handle the shell differently now! I used to have this bug too and haven't seen it in a while.

**Comment by vsoch** [comment]
hey @antonkulaga do you still have this issue? Could you try with Singularity 2.4 (master is release) or development and see if it is still the case?

**Comment by dtrudg** [comment]
Closing this as it is believed fixed, and ticket has not been updated. Please let us know if you still have this issue. Thanks!
