### ISSUE TITLE
mentioning googlegroup/gitter/slack/whatever in readme

### ISSUE THREAD

**Issue by antonkulaga** [apptainer/singularity#622]
Gitter chats and mailing lists are often useful to facilitate the discussions inside the commonity. In case of gitter it is super-easy to make it and add the badge to the repo

**Comment by vsoch** [comment]
Hey @antonkulaga  - are you suggesting Gitter in place of slack? We don't currently have a paid plan, so most of the conversation on slack is (soon) lost given the number o users that we have.  I haven't looked at Gitter in a long bit - is it unlimited for free, for history too?

**Comment by gmkurtzer** [comment]
I craeted a community ages ago, before we moved it to its own organization. So I just created one for SingularityWare at https://gitter.im/singularityware if anyone wants to test.

**Comment by vsoch** [comment]
I think it's safe to close this - I don't think we are going to use Gitter anytime soon, unless it gets significantly better. Sorry @antonkulaga :(
