### ISSUE TITLE
make singularity calling cmdline available from within container

### ISSUE THREAD

**Issue by katakombi** [apptainer/singularity#625]
In order to spawn nested container calls on neighbour nodes via ssh I'd like to have the entire cmdline available from within the container process, e.g. `singularity exec -B /mnt/share /home/user/containers/Ubuntu.sapp`

By now there is a certain amount of information inside a container process telling about how the container process got invoked, namely

- SINGULARITY_libexecdir=/usr/lib/x86_64-linux-gnu
- SINGULARITY_localstatedir=/var
- SINGULARITY_sysconfdir=/etc
- SINGULARITY_INIT=1
- SINGULARITY_CONTAINER=e.g. Ubuntu.sapp
- SINGULARITY_IMAGE=e.g. Ubuntu.sapp

but not sufficient for e.g. custom binds passed via the `-B` parameter.
In my case it would be enough to make the entire call available using one variable.

See also: https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/2_BuEkMb6aI

**Comment by gmkurtzer** [comment]
Hi @katakombi, what if there was a single variable, perhaps something like `SINGULARITYCMD=...` which has the full command. The bigger problem in either case is related to quoting of variables. Do you have any thoughts on how to solve that?

Thanks!

**Comment by katakombi** [comment]
Hi Greg,

 something like a `SINGULARITYCMD` env var would be sufficient in my case. What do you mean by problems with quoting? Can you give a few examples of what you have in mind there?

thanks

**Comment by gmkurtzer** [comment]
Hi @katakombi,

The quoting becomes a big issue actually if you ever have to pass variables that might have a space, or a necessary quote, or escape characters within it. For example, if the original command is something like:

```
$ test() { echo "$*"; }
$ test yum groupinstall "Development Tools"
yum groupinstall Development Tools
```

You can see how the quoting was lost in the response. So if I were to capture that in a single string variable that could be easily passed, I would also loose the quotes. For many commands this will work fine, but when things get quoted, unexpected results/failures will surface.

The appropriate way to deal with this is arrays, but that can't be easily obtained or passed via a Bourne environment variable.

**Comment by katakombi** [comment]
Oh yes, of course, now I understand!
I wasn't thinking of that just because I am mainly interested in the singularity command line (without the exec part) but ofc quotes could appear even inside singularity arguments (e.g. dirs with spaces etc)

I see the following possibilities:
- Agree on using just one type of quotes (' or ") then this should work
- Write a substitution function (using ' " \\) which maintains the structure of the command. Is it even possible? I do not really know and would have to try it...
- Do not use an env var but dump the command in a container log file e.g. /tmp/var/log/singularity.log

kind regards

**Comment by vsoch** [comment]
hey @katakombi - this seems like a use case for some kind of workflow management that can handle the arguments and processing of commands, is that what you are getting at? The simplest way of going about this would be to have each container perform one small, modular task, and thus any running of it would envoke the task. custom arguments get tricky, but maybe you could do something like have the container expect inputs (and arguments?) to be specified in some log/folder where the call is from. Could you provide a concrete example for what you are wanting to do? I think a workflow management solution might be a way to go... for which [there are many!](https://github.com/pditommaso/awesome-pipeline)

**Comment by katakombi** [comment]
Hi @vsoch, thanks for your thoughts. However, my case is somewhat different: 

My app containers are ready and can be used on a single node.
But I want to invoke multinode `mpirun` jobs.
This is just doable from within containers because they use OpenMPI versions 1.xx (no hybrid MPI). Mpirun uses ssh to invoke the processes on neighbour nodes so I wrapped SSH to call from
`ssh $HOSTNAME "$MPIRUN_ARGS"`
to
`ssh $HOSTNAME "singularity exec $SINGULARITY_IMAGE $MPIRUN_ARGS"`

This seems to work just fine until the point I want to pass a bind directory in the invoking call.
I need the bind directories information to make it available to the neighbour nodes or else jobs die :(
I didn't want to ask for making just the -B directories available as env vars because it is not too general. I reckoned it is better to have the entire cmdline. 

edit: thanks for the link it's worth studying...

@gmkurtzer seems like there are a few possibilities to get the quotes into an envvar e.g. the `printq` approach: http://stackoverflow.com/questions/6306386/how-can-i-escape-an-arbitrary-string-for-use-as-a-command-line-argument-in-bash

**Comment by vsoch** [comment]
can you take a local script and direct it to the neighbor node with stdin?

**Comment by vsoch** [comment]
like 

```
cat scripty.sh
singularity exec $SINGULARITY_IMAGE $MPIRUN_ARGS
```
then just do:

```
ssh $HOSTNAME < scripty.sh
```

apologies for being an ignoramus about this, I've never actually done anything with MPI :)

**Comment by katakombi** [comment]
I guess you even could. It probably required more caution to integrate this in MPI though.
Why are you asking?
In either case I do not know the `-B` arguments of the running container process and cannot reconstruct the singularity exec call on the remote host. 

Update: I guess my lengthy explanation has led you in a wrong direction. I have no troubles to construct the remote call except that I want to pass the singularity exec options (such as -B /custom/path) dynamically to the remote nodes. In order to do so I need this information inside the container.

**Comment by katakombi** [comment]
Hi @gmkurtzer  and @vsoch ,

 I have a suggestion: instead of having the entire cmdline it would be sufficient for now to have just a list of bind dirs e.g. `SINGULARITY_BINDDIRS="/home:/opt/software:/scratch:/lustre"`
That would be probably much easier and straightforward to do, right?

**Comment by gmkurtzer** [comment]
At the moment (in the development branch) all variables are generally being wiped clean that are prefixed with `SINGULARITY_` including `SINGULARITY_BINDDIRS`. If you want to ensure that that variable (or any others) are transposed down into the container, you can do so by editing `/etc/singularity/init` and doing something like:

```
SINGULARITYENV_SINGULARITY_BINDDIRS="$SINGULARITY_BINDDIRS"`
export SINGULARITYENV_SINGULARITY_BINDDIRS
```

Hope that helps!

**Comment by serious-steve** [comment]
Thanks @gmkurtzer @vsoch,

  that is what I do now in `/etc/singularity/init` : 

```
SINGULARITY_BINDDIRS=`grep '^[ ]*bind path[ ]*=' /etc/singularity/singularity.conf| sed 's/.*=[ ]*\(.*\)/\1::/' | tr -d '\n'`
SINGULARITY_COMMANDLINE="$*"
export SINGULARITY_COMMANDLINE SINGULARITY_BINDDIRS

```
yielding
```
singularity exec -B /lustre /nfs/home1/CiTAR/Plurality/mksapp/images/Gaussian.sapp-2017-04-24-13-20.img /bin/bash

echo $SINGULARITY_BINDDIRS
/nfs::/scratch::/etc/hosts::/etc/ssh::/var/spool/torque::/home::

echo $SINGULARITY_COMMANDLINE
-B /lustre /nfs/home1/CiTAR/Plurality/mksapp/images/Gaussian.sapp-2017-04-24-13-20.img /bin/bash
```

This enables me to reconstruct the total binds. You can close this issue :)

**Comment by vsoch** [comment]
awesome, thanks @c1t4r closing!
