### ISSUE TITLE
Test parallel processing of download / fix permissions

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#631]
I have to be careful about using the term "parallel" because it could refer to different processes, threading, and intertwined with some concurrency. For this first case I'm going to test serial vs. multiprocessing, because that seems like the most common way to go about it.

**Comment by vsoch** [comment]
ok! So I got only about 1/2 done the implementation, but I tested this out:

http://www.vanessasaur.us/rawr/2017/multiprocess/

and it does look like there is marginal speed up for using multiprocessing. This was also tested on a dinky instance (read the post for details!) The challenge is going to be to integrate the progress bar into this framework. I have some ideas, but am still debugging a bit. What I'd like to do is implement a base working case, and then have it tested in a few different places (eg, more CPU!) to see how big of a difference it can make. If we decide to implement this:

- we will need to be sure the progress bar is still useful, likely it won't have the same granularity
- possibly we want to split the changing of permissions into two different things, so we can again have more processes working on it, and give the user better updates
- I noticed cool behavior that I did optimally (on my weeny instance) with an odd number of pools. If it's the case that the number of pools needs to be optimzied per the cluster, we either need to:
  - figure out the optimum at runtime
  - give the admin a configuration value (with a reasonable default) and instructions / tool for determining an optimal

or something like that. More on this later!! Learning about this stuff is wicked cool :)

**Comment by ArangoGutierrez** [comment]
Do you have any test scrypt to run? or simply any ``` singularity import ``` can be used as a test. 
I enjoy doing parallel stuff ( mostly on C/C++ , with OpenMP or the threads lib)

**Comment by vsoch** [comment]
yes please test the current PR for this on different machines (with varying CPU) and compare the PR branch to development. Any shell command should work, and up to you how to time! Thanks!

**Comment by vsoch** [comment]
oh yeah, I did this too.
