### ISSUE TITLE
ERROR  : Could not virtualize file system namespace: Operation not permitted

### ISSUE THREAD

**Issue by chrisgorgo** [apptainer/singularity#632]
Running on CentOS 6 using root and af9551859655ca37f04e621a24f7d6614c3c5a8d version of Singularity (development HEAD at the time of writing).

```
[root@f00125c69849 /]# singularity run docker://ubuntu
Docker image path: index.docker.io/library/ubuntu:latest
Cache folder set to /root/.singularity/docker
[1/5] Download |===================================| 100.0% layer c627
[1/5] Prepare  |===================================| 100.0% layer c627
[2/5] Download |===================================| 100.0% layer d4fc
[2/5] Prepare  |===================================| 100.0% layer d4fc
[3/5] Download |===================================| 100.0% layer c912
[3/5] Prepare  |===================================| 100.0% layer c912
[4/5] Download |===================================| 100.0% layer 0062
[4/5] Prepare  |===================================| 100.0% layer 0062
[5/5] Download |===================================| 100.0% layer b33f
[5/5] Prepare  |===================================| 100.0% layer b33f
Importing: base Singularity environment
Exploding layer: sha256:c62795f78da9ad31d9669cb4feb4e8fba995a299a0b2bd0f05b10fdc05b1f35e.tar.gz
Exploding layer: sha256:d4fceeeb758e5103c39daf44c73404bf476ef6fd6b7a9a11e2260fcc1797c806.tar.gz
Exploding layer: sha256:5c9125a401ae0cf5a5b4128633e7a4e84230d3eb4c541c661618a70e5d29aeff.tar.gz
Exploding layer: sha256:0062f774e9942f61d13928855ab8111adc27def6f41bd6f7902c329ec836882b.tar.gz
Exploding layer: sha256:6b33fd031facf4d7dd97afeea8a93260c2f15c3e795eeccd8969198a3d52678d.tar.gz
Exploding layer: sha256:fe44851d529f465f9aa107b32351c8a0a722fc0619a2a7c22b058084fac068a4.tar.gz
Singularity: action-suid (U=0,P=31)> Could not virtualize file system namespace: Operation not permitted

ERROR  : Could not virtualize file system namespace: Operation not permitted
Singularity: action-suid (U=0,P=31)> Retval = 255

ABORT  : Retval = 255
[root@f00125c69849 /]# Singularity: singularity: cleanupd (U=0,P=80)> Failed removing file: /tmp/.singularity-runtime.eL6PzXJ2/container/ubuntu/root

Singularity: singularity: cleanupd (U=0,P=80)> Could not remove directory /tmp/.singularity-runtime.eL6PzXJ2: Directory not empty

Singularity: singularity: cleanupd (U=0,P=80)> Retval = 255
```

**Comment by vsoch** [comment]
hey @chrisfilo ! I'm guessing you are running this inside Docker, did you check the things from [this post](https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/e9mlDuzKowc)? Specifically:

 - confirm running with `--privileged` via inspect
 - adding `--cap-add=SYS_ADMIN `
 - could be related to https://github.com/moby/moby/issues/2918
 
It would be good to see this run from via a non-Docker centos 6 to confirm it's Docker related, although I'm not sure who has those lying around :) Could you also please provide the complete `--debug` output, to anticipate the above needing further investigating?

**Comment by chrisgorgo** [comment]
`--privileged` solved the problem. Thanks!

**Comment by stevekm** [comment]
Adding `--privileged` only works with `docker run`; it does not work with `docker build`. How do you build a Docker container with the Singularity images pre-built inside? It gives the same error listed here, currently.

**Comment by leozitor** [comment]
is there any way of running singularity without --privileged? I am asking because i would like to deploy on docker swarm, but docker swarm doesn´t  allow use of --privileged

**Comment by DrDaveD** [comment]
This repository is closed.  If `singularity --version` shows `singularity-ce`, please ask in a [Singularity CE forum](https://sylabs.io/singularity/#community) otherwise ask in an [Apptainer forum](https://apptainer.org/help).
