### ISSUE TITLE
ERROR Cannot untar layer

### ISSUE THREAD

**Issue by chrisgorgo** [apptainer/singularity#633]
`singularity run docker://ubuntu` worked but:

```
[root@8357ee35d5f7 /]# singularity run docker://poldracklab/mriqc:0.9.3
Docker image path: index.docker.io/poldracklab/mriqc:0.9.3
Cache folder set to /root/.singularity/docker
[1/24] Download |===================================| 100.0% layer 3ed9
ERROR Cannot untar layer /root/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz.TxY6kY, was there a problem with download?
```

I've tried without the tag with the same effect. This is the development branch running inside docker.

**Comment by vsoch** [comment]
The error is because there is an archive (or maybe more than one, it quits at the first) that is empty:

![image](https://cloud.githubusercontent.com/assets/814322/25326903/f43f7438-2886-11e7-8d3a-13d73e59a02d.png)

any ideas? Here is the layer:

```
DEBUG GET (stream) https://index.docker.io/v2/poldracklab/mriqc/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
[1/24] Download |===================================| 100.0% layer 3ed9
DEBUG Download of raw file (pre permissions fix) is /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz._Q66UL
VERBOSE Fixing permission for /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz._Q66UL
```

and it triggers this bug:

```
Traceback (most recent call last):
  File "/usr/local/libexec/singularity/python/import.py", line 107, in <module>
    main()
  File "/usr/local/libexec/singularity/python/import.py", line 83, in main
    layerfile=LAYERFILE)
  File "/usr/local/libexec/singularity/python/docker/main.py", line 104, in IMPORT
    prefix=prefix)
  File "/usr/local/libexec/singularity/python/docker/api.py", line 280, in get_layer
    prefix=prefix)
  File "/usr/local/libexec/singularity/python/sutils.py", line 329, in change_tar_permissions
    bot.show_progress(ii,count,length=35,prefix=prefix,suffix=suffix)
  File "/usr/local/libexec/singularity/python/message.py", line 173, in show_progress
    percent = 100 * (iteration / float(total))
ZeroDivisionError: float division by zero
```

I can add a workaround to check if this total is 0, but I'd like to figure out why it's empty in the first place. It could be a bad download, or something on the Docker side, and the closer we can get to the root, the better. No pun intended. :)

**Comment by vsoch** [comment]
Could be something like this: https://github.com/moby/moby/issues/20917#issuecomment-191901912 can look more into tomorrow. Err today. Whatever.

**Comment by chrisgorgo** [comment]
Here's the dockerfile used to create this image: https://github.com/poldracklab/mriqc/blob/master/Dockerfile
Here's layer analysis:
https://microbadger.com/images/poldracklab/mriqc

I guess the ENVs are causing a problem?

**Comment by vsoch** [comment]
I think so. I'm testing a quick fix for this, will PR after I've looked over a few more things.
