### ISSUE TITLE
SELinux Support?

### ISSUE THREAD

**Issue by ifelsefi** [apptainer/singularity#637]
Hello

I am new to singularity and was wondering if you have any guides on using it with SELinux in an HPC environment?

Thanks
Doug

**Comment by gmkurtzer** [comment]
Hi @JusticeForMikeBrown 

I don't play much with selinux, but I can say that on my development Centos system, I have selinux both enabled and in enforcing targeted mode. Have you found an issue or are you doing recon?

Thanks!

**Comment by ifelsefi** [comment]
Recon only!

**Comment by gmkurtzer** [comment]
Ahh, cool. I "think" it should work just fine, but I haven't tested or even played with MLS mode. If you do get around to testing, will you report back on this issue?

Thanks!
