### ISSUE TITLE
Bootstrapping a container from a Fedora 25 host

### ISSUE THREAD

**Issue by ShadowAce** [apptainer/singularity#638]
I have installed singularity via the standard repo (version 2.0) on a Fedora 25 VM

I have create a container using the recommended method:

sudo singularity create container.img

I have created a centos.def file as I saw in an exmaple video by gmkurtzer:
```
RELEASE=7

DistType "redhat"
MirrorURL "http://mirror.centos.org/centos-${RELEASE}/${RELEASE}/os/\$basearch/"

Setup
Bootstrap

InstallPkgs yum vim-minimal python procps-ng

Cleanup
```

However, when I run the bootstrap command:

sudo singularity bootstrap container.img centos.def

I get the following error message:

```
Redirecting to '/usr/bin/dnf --noplugins -c /mnt//etc/bootstrap-yum.conf --tolerant --installroot /mnt -y install /etc/redhat-release coreutils' (see 'man yum2dnf')

No such command: --tolerant. Please use /usr/bin/dnf --help
It could be a DNF plugin command, but loading of plugins is currently disabled.

```
Am I doing something wrong?  Does singularity not yet support dnf on the host?

**Comment by ArangoGutierrez** [comment]
Hi did someone say Fedora?
I have a Fedora 24 Host, with the standard repo (master branch) (Installed Today 25 April)
This would be the .def file that you need
First create the container:

```bash
sudo singularity create /SomePath/Centos7.img
```
Paste this on a .def using your favorite text editor

```bash
BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum

%post

yum install -y vim-minimal python procps-ng
```

Then run the bootstrap process

```bash
sudo singularity bootstrap /Somepath/Centos7.img Centos7.def
```

It worked on my Fedora 24 host. It should work on Fed 25.

Here you can find more info about the bootstrap process on the standard repo ([master branch](https://github.com/singularityware/singularity))
> [Bootstrap-Docs](http://singularity.lbl.gov/docs-bootstrap)

**Comment by gmkurtzer** [comment]
Hi @ShadowAce,

Depending on what version of Singularity you are using, you will see different results as the bootstrap definition syntax that I gave as an example in some previous videos has been superseded with a much more flexible definition file syntax (as @ArangoGutierrez demonstrated and as the current documentation suggests).

Hope that helps, and sorry for the confusion.

**Comment by ShadowAce** [comment]
Thanks, guys!! 

I have got version 2.2.99 up and running.  One thing I noticed, though--On Fedora (and maybe on RH systems in general), the executable gets installed into /usr/local/bin which is not in root's PATH.  Easy enough to fix, but maybe it should be mentioned in the docs.

This will be great to use!  I look forward to installing it on our HPC cluster.

**Comment by gmkurtzer** [comment]
Oh, on RedHat and Fedora (RPM) based systems, I'd recommend building an RPM. The process is pretty simple:

```
$ ./autogen.sh
$ ./configure
$ make dist
$ rpmbuild -ta singularity-*.tar.gz
```

And then install the RPMs onto your base system via the normal means.

Hope that helps!

Greg
