### ISSUE TITLE
packaging warnings

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#64]
The following warnings are issued by checks required for Fedora review, but I _think_ they're not real issues.  Could confirm that, and maybe consider either inserting an initgroups and chdir to pacify the check or adding comments about them?  (That isn't actually necessary for the review, providing the warning is deemed spurious.)

```
$ rpmlint -I missing-call-to-chdir-with-chroot -I missing-call-to-setgroups-before-setuid
missing-call-to-chdir-with-chroot:
This executable appears to call chroot without using chdir to change the
current directory. This is likely an error and permits an attacker to break
out of the chroot by using fchdir. While that's not always a security issue,
this has to be checked.

missing-call-to-setgroups-before-setuid:
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.
```

[POS36-C is https://www.securecoding.cert.org/confluence/display/c/POS36-C.+Observe+correct+revocation+order+while+relinquishing+privileges]

**Comment by gmkurtzer** [comment]
I added a kludge for the first with [master a6f11f1], and hopefully the second is fixed with [master bf8cfdc].

Can you retest?

**Comment by opoplawski** [comment]
Looks like the warnings are gone with latest master.

**Comment by gmkurtzer** [comment]
Fantastic, thank you!

**Comment by loveshack** [comment]
> Looks like the warnings are gone with latest master.

I back-ported the change as a patch for 2.0 and the chroot warning
didn't go away under rawhide fedora-review.  However, neither warning
appears even without the patch in el6 using a build of the same version
of rpmlint; I was trying to figure out why.  (The test appears to be for
chdir "near" chroot.)

I thought chdir was supposed to precede chroot, though.  Is chdir("/")
afterwards definitely equivalent?

**Comment by gmkurtzer** [comment]
I was thinking as well that the test must be looking "near" the chroot, or more specifically following it. Additionally (to answer your question), the call to chdir("/") must be following the chroot to ensure that the file descriptor to your current directory is in fact within the chroot. 

I am reopening this until we get a thumbs up from everyone.

Thanks!

**Comment by opoplawski** [comment]
FWIW - Test runs objdump -d on the binary, looks for call/callq chroot@plt and then looks for chdir@plt up to 2 calls away on either side of the chroot call.

On my EL7 compiled version of master I see:

```
    2989:       e8 c2 ee ff ff          callq  1850 <chroot@plt>
    298e:       85 c0                   test   %eax,%eax
    2990:       0f 88 1e 03 00 00       js     2cb4 <seteuid@plt+0xff4>
    2996:       48 8d 3d 8e 3e 00 00    lea    0x3e8e(%rip),%rdi        # 682b <seteuid@plt+0x4b6b>
    299d:       e8 5e ef ff ff          callq  1900 <chdir@plt>
```

So it immediately follows.

**Comment by gmkurtzer** [comment]
Ahh, I didn't know any of that. Thank you @opoplawski!

**Comment by loveshack** [comment]
You wrote: 

> FWIW - Test runs objdump -d on the binary, looks for call/callq
> chroot@plt and then looks for chdir@plt up to 2 calls away on either
> side of the chroot call.

Yes, I just hadn't got round to debugging the false negative on el6 and
false positive on rawhide.  Apologies I didn't make it clear the issue
didn't need re-opening; the false positive is clearly an rpmlint issue.
