### ISSUE TITLE
running from home path vs system path

### ISSUE THREAD

**Issue by ketancmaheshwari** [apptainer/singularity#644]
Running an image using the singularity executable from my $HOME works while using the same executable installed on an arbitrary system path does not work. The error is file not found.

```
[login1 singularity-Tensorflow]$ which singularity
/ihome/install/singularity/bin/singularity
[login1 singularity-Tensorflow]$ singularity exec ubuntu_tensorflow_GPU.img python test.py
python: can't open file 'test.py': [Errno 2] No such file or directory

```
Following works:

```
[login1 singularity-Tensorflow]$ ~/singularity-install/bin/singularity exec ubuntu_tensorflow_GPU.img python test.py
2017-04-27 17:51:40.045086: W tensorflow/core/platform/cpu_feature_guard.cc:45] ...
...
...

```

I checked that my home directory is mounted and available in the image. The `test.py` file is located in the directory from where the image is invoked in both cases. This problem is preventing us from making singularity available to the larger user base. Any suggestions?

**Comment by gmkurtzer** [comment]
Singularity is very specific when it comes to the path of the configuration file, so each of those installations will most likely be using different configs. It also seems that "test.py" is in your current directory, so I would suggest that there is a difference between the two installations and/or configurations.

This doesn't seem like a Singularity error or issue, so I'm closing the issue (perhaps it deserves further discussion on the Google Group)?

Hope that helps!

Greg

**Comment by xihajun** [comment]
Could try this probably?
`singularity exec --no-home --bind /hostpath/test.py:/mnt/test.py work.sif  python3.9 /mnt/test.py`
