### ISSUE TITLE
`locale` configuration copied into container

### ISSUE THREAD

**Issue by nordmoen** [apptainer/singularity#645]
I have encountered yet another problem on the way to simulate my robot. This time around it seems as if some of my system configuration has been copied into the container, overwriting the docker configuration.

The problem is that launching [`gzserver`](http://gazebosim.org/) inside a container results in an error being thrown:
```bash
Singularity dyret_map.img:~> gzserver
No protocol specified
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)
```

Tracking this down lead to the discovery that inside the container the `locale` is set to the same thing as outside without installing the necessary languages.

Inside my container executing `locale`:
```bash
Singularity dyret_map.img:~> locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=nb_NO.UTF-8
LC_TIME=nb_NO.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nb_NO.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nb_NO.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=nb_NO.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
Then executing `locale -a` inside the container shows that the above languages (`nb_NO.UTF-8`) are not installed
```bash
Singularity dyret_map.img:~> locale -a
C
C.UTF-8
en_US.utf8
POSIX
```

It seems to me that the configuration has been copied from my host computer into the container. To replicate this I created this small `C++` program:
```cpp
#include <iostream>
#include <locale>

// test_locale.cpp

int main() {
        auto loc = std::locale("nb_NO.UTF-8");
        std::cout.imbue(loc);
        std::cout << "Hello 'C' world!\n";
}
```
Which when compiled (`g++ -std=c++11 test_locale.cpp`) works on my host computer, but fails inside a Singularity container.

```bash
Running post scriptlet
+ cd /workspace
+ g++ -lboost_date_time -std=c++11 test_locale.cpp
Running test scriptlet
+ cd /workspace
+ ./a.out
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)
ERROR: Aborting with RETVAL=255
```

**Comment by vsoch** [comment]
Have you tried the `--contain` and `--containall` commands to isolate your host from the container? If you just want to isolate environment vars, try `--cleanenv`. Note - these are runtime variables, not anything you specify in a bootstrap definition. Eg:

```
singularity shell --contain muffin.img
```

**Comment by nordmoen** [comment]
Again, sorry for the delay, Norwegian holidays...

Edit:
Silly me, used wrong container with code that would definitely fail. With my original image `--cleanenv` worked like a charm

**Comment by nordmoen** [comment]
To elaborate, I tried to debug in the same way as above.

For `--contain` I get this `locale` configuration:
```bash
Singularity locale.img:~> locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=nb_NO.UTF-8
LC_TIME=nb_NO.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nb_NO.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nb_NO.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=nb_NO.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

For `--containall` and `--cleanenv`:
```bash
Singularity locale.img:~> locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
In all of them I get the following from `locale -a`:
```bash
Singularity locale.img:~/Repos/singularity_images/locale> locale -a
C
C.UTF-8
en_US.utf8
POSIX
```
I don't know if `locale` is case-sensitive, but that could be the problem?

**Comment by vsoch** [comment]
ok cool, is this issue resolved then? And happy holidays!! I hope we get some more over here soon too :)

**Comment by nordmoen** [comment]
Resolving issue 💯
