### ISSUE TITLE
Add ability to skip tests when bootstrapping image

### ISSUE THREAD

**Issue by DeepHorizons** [apptainer/singularity#647]
I'm building singularity images using an automated build system. The build system does not mimic the production system which the containers will be run on, in particular we are adding in support for GPUs. Because of this, the tests that I write for the images are meant to be run on production system, and fail on the build system.

Is there a way to not run tests when bootstrapping an image? There was something like this in #305 but was never fleshed out.

**Comment by gmkurtzer** [comment]
Hiya @DeepHorizons,

We too have been working on GPU support and you can check it out in the 'development' branch with the `--nv` option.

Would it work to have a separate %buildtest and %runtest?

Greg

**Comment by DeepHorizons** [comment]
Hey @gmkurtzer 

Neat option! I'll check that out when I get the chance. Anything in the docs on how it works / debugging?

`%buildtest` and `%runtest` don't exactly fit my use case. I don't know of any test that I could run on my GPU images that would not require a GPU. I still run the tests on the cluster with a GPU, I just don't need to run the tests when building. The main reason behind this is for better error reporting. If I could suppress the tests when building, I could have better error logging on the build process. Instead I have to have everything ignoring errors and looking through the logs manually.

**Comment by gmkurtzer** [comment]
Hiya! Nope, no documentation on it yet as it was just introduced for testing. 

Optionally suppressing the tests during build would be an easy addition, I'll add it. 

Greg

**Comment by gmkurtzer** [comment]
Singularity development branch now supports the ability to skip the `%test` during `bootstrap` with the `--notest` option.

**Comment by dtrudg** [comment]
Closing this. `--notest` is an option to `singularity build` in 2.4.x
