### ISSUE TITLE
Add compression support for .img format

### ISSUE THREAD

**Issue by DeepHorizons** [apptainer/singularity#649]
While there is already a discussion on minimizing the image size in #470, another idea to reduce the size would be compression. A fast compression method such as LZ4 could be used to allow on the fly decoding. With initial tests images are often reduced to less than 50% of their original size.

**Comment by gmkurtzer** [comment]
Support for compressed images via SquashFS does already exist. Would that meet the use-case?

Btw, on the fly decompression can not work with the default Singularity image in the format it stands now.

**Comment by ArangoGutierrez** [comment]
@DeepHorizons with the new SquashFS, is your feature request satisfied?

**Comment by DeepHorizons** [comment]
Yep, files are small and everything looks good!
