### ISSUE TITLE
No usable temporary directory found

### ISSUE THREAD

**Issue by sebastian-luna-valero** [apptainer/singularity#65]
Hello,

On SL6.7, when I do `yum install` within a CentOS 7 image I get:

```
--> Finished Dependency Resolution

[Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp']

```

Any ideas?

Many thanks,
Sebastian.

PS: I am using the code at master

**Comment by gmkurtzer** [comment]
What version of singularity are you using?

**Comment by sebastian-luna-valero** [comment]
I did:

```
git clone -b master https://github.com/gmkurtzer/singularity.git
```

**Comment by gmkurtzer** [comment]
Can you check the /etc/singularity/singularity.conf file and see if it is present and has the following entries:

bind path = /tmp
bind path = /var/tmp

I recently changed how binds work within Singularity, and I hope I didn't break anything.

Thanks!

**Comment by sebastian-luna-valero** [comment]
Many thanks!

Yes, singularity.conf contains those lines but I have installed singularity on a custom folder location. Is that a problem? How can I configure singularity to look for the configuration files if they are not in the standard location?

Best regards,
Sebastian.

**Comment by gmkurtzer** [comment]
Ahh, good point. The sexec binary should be built with the proper path to the config but perhaps there is a bug. 

Can you send me the configure args you used to build singularity?

Thanks!

**Comment by sebastian-luna-valero** [comment]
Sure:

```
./configure --prefix=~/singularity/install
```

Best regards,
Sebastian

**Comment by gmkurtzer** [comment]
I will test as soon as I get into office. Thanks!

**Comment by gmkurtzer** [comment]
Hi @sebastian-luna-valero, I am not able to replicate this. Here is what I did... Can you compare to your procedure please:

```
$ git pull
$ ./autogen.sh
$ ./configure --prefix=/home/gmk/singularity/install
$ make
$ sudo make install
$ sudo /home/gmk/singularity/install/bin/singularity shell -w /tmp/Centos-7.img
Singularity/Centos-7.img> yum install bc
...
Installed:
  bc.x86_64 0:1.06.95-13.el7                                                                                                                                                                  

Complete!
Singularity/Centos-7.img> 
```

**Comment by sebastian-luna-valero** [comment]
Hello,

I was repeating these steps:

```
cd /ifs/apps/system/src/singularity-latest/
git pull
./autogen.sh 
./configure --prefix=/ifs/apps/system/singularity-latest
make
```

and then:

```
Making all in src
make[1]: Entering directory `/ifs/apps/system/src/singularity-latest/src'
make  all-am
make[2]: Entering directory `/ifs/apps/system/src/singularity-latest/src'
/bin/sh ../libtool --tag=CC   --mode=link gcc -Wall -g -O2   -o sexec sexec-sexec.o sexec-util.o sexec-loop-control.o sexec-mounts.o sexec-container_files.o sexec-file.o sexec-image.o sexec-config_parser.o sexec-container_actions.o sexec-privilege.o  
libtool: link: gcc -Wall -g -O2 -o sexec sexec-sexec.o sexec-util.o sexec-loop-control.o sexec-mounts.o sexec-container_files.o sexec-file.o sexec-image.o sexec-config_parser.o sexec-container_actions.o sexec-privilege.o 
sexec-sexec.o: In function `main':
/ifs/apps/system/src/singularity-latest/src/sexec.c:719: undefined reference to `setns'
/ifs/apps/system/src/singularity-latest/src/sexec.c:732: undefined reference to `setns'
collect2: ld returned 1 exit status
make[2]: *** [sexec] Error 1
make[2]: Leaving directory `/ifs/apps/system/src/singularity-latest/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/ifs/apps/system/src/singularity-latest/src'
make: *** [all-recursive] Error 1
```

**Comment by gmkurtzer** [comment]
Can you do a make clean, and then make again?

**Comment by sebastian-luna-valero** [comment]
Thanks, but still:

```
/bin/sh ../libtool --tag=CC   --mode=link gcc -Wall -g -O2   -o sexec sexec-sexec.o sexec-util.o sexec-loop-control.o sexec-mounts.o sexec-container_files.o sexec-file.o sexec-image.o sexec-config_parser.o sexec-container_actions.o sexec-privilege.o  
libtool: link: gcc -Wall -g -O2 -o sexec sexec-sexec.o sexec-util.o sexec-loop-control.o sexec-mounts.o sexec-container_files.o sexec-file.o sexec-image.o sexec-config_parser.o sexec-container_actions.o sexec-privilege.o 
sexec-sexec.o: In function `main':
/ifs/apps/system/src/singularity-latest/src/sexec.c:719: undefined reference to `setns'
/ifs/apps/system/src/singularity-latest/src/sexec.c:732: undefined reference to `setns'
collect2: ld returned 1 exit status
make[2]: *** [sexec] Error 1
make[2]: Leaving directory `/ifs/apps/system/src/singularity-latest/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/ifs/apps/system/src/singularity-latest/src'
make: *** [all-recursive] Error 1
```

**Comment by gmkurtzer** [comment]
What host OS are you building on? I just tried with SL6, and it worked fine. Just to be sure, can you try a new clone? <shrug>

**Comment by sebastian-luna-valero** [comment]
Indeed, SL6.7

I will give it another go tomorrow ;)

**Comment by truatpasteurdotfr** [comment]
on CentOS-6.8:
$ grep -r setns /usr/include/
/usr/include/bits/syscall.h:#define SYS_setns __NR_setns
/usr/include/asm/unistd_64.h:#define __NR_setns             308
/usr/include/asm/unistd_64.h:__SYSCALL(__NR_setns, sys_setns)
/usr/include/asm/unistd_32.h:#define __NR_setns     346
/usr/include/asm-generic/unistd.h:#define __NR_setns 268
/usr/include/asm-generic/unistd.h:__SYSCALL(__NR_setns, sys_setns)

$ grep -rl setns /usr/include/| xargs rpm -qf| sort -u  
glibc-headers-2.12-1.192.el6.x86_64
kernel-headers-2.6.32-642.1.1.el6.x86_64

are you missing some package to build singularity?

**Comment by gmkurtzer** [comment]
Ya know, I don't mind making the setns inclusion conditional if the support is present but it strikes me as very weird that we can't replicate this. I think I will make it conditional today anyway because as I search around, setns is a fairly new feature and I want singularity to be portable to older Linuxes. I'll reply once I get setns required bits conditionalized.

**Comment by gmkurtzer** [comment]
@sebastian-luna-valero will you please retest commit 33b28c4? I added conditional bits for setns.

**Comment by sebastian-luna-valero** [comment]
Thanks!

Still:

```
/bin/sh ../libtool --tag=CC   --mode=link gcc -Wall -g -O2   -o sexec sexec-sexec.o sexec-util.o sexec-loop-control.o sexec-mounts.o sexec-container_files.o sexec-file.o sexec-image.o sexec-config_parser.o sexec-container_actions.o sexec-privilege.o  
libtool: link: gcc -Wall -g -O2 -o sexec sexec-sexec.o sexec-util.o sexec-loop-control.o sexec-mounts.o sexec-container_files.o sexec-file.o sexec-image.o sexec-config_parser.o sexec-container_actions.o sexec-privilege.o 
sexec-sexec.o: In function `main':
/ifs/apps/system/src/singularity-latest/src/sexec.c:727: undefined reference to `setns'
/ifs/apps/system/src/singularity-latest/src/sexec.c:740: undefined reference to `setns'
collect2: ld returned 1 exit status
make[2]: *** [sexec] Error 1
make[2]: Leaving directory `/ifs/apps/system/src/singularity-latest/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/ifs/apps/system/src/singularity-latest/src'
make: *** [all-recursive] Error 1
```

I hope I am not doing something silly and wasting your time!

I can see that undefined reference to `setns' is coming from a different line on sexec.c

Moreover:

```
$ grep -r setns /usr/include/
/usr/include/asm-generic/unistd.h:#define __NR_setns 268
/usr/include/asm-generic/unistd.h:__SYSCALL(__NR_setns, sys_setns)
/usr/include/asm/unistd_32.h:#define __NR_setns     346
/usr/include/asm/unistd_64.h:#define __NR_setns             308
/usr/include/asm/unistd_64.h:__SYSCALL(__NR_setns, sys_setns)
/usr/include/bits/syscall.h:#define SYS_setns __NR_setns

$ grep -rl setns /usr/include/| xargs rpm -qf| sort -u
glibc-headers-2.12-1.166.el6_7.7.x86_64
kernel-headers-2.6.32-573.26.1.el6.x86_64
```

**Comment by gmkurtzer** [comment]
I am very confused by this... Are you sure you are pulling from the master branch? Can you attach the ./autogen.sh and ./configure output?

Thanks!

**Comment by gmkurtzer** [comment]
I think I figured this out actually! Please check [master fc24bb4]...

Thanks!

**Comment by sebastian-luna-valero** [comment]
Brilliant, all solved now with the latest master!
