### ISSUE TITLE
singularity inspect

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#651]
If our singularity metadata folder is hidden, and if we aren't (yet) having support for a header proper, we should consider providing a simple command line utility for the user to (minimally) access some of the containers metadata. For example, docker inspect reveals the equivalent of it's configuration (and it's json, which isn't great for parsing in bash, but is still possible and of course works great with most programming languages). Here I can see it while running the docker container, ubuntu:

```
 docker inspect ubuntu
[
    {
        "Id": "sha256:f7b3f317ec734a73deca91b34c2b1e3dd7454650da9c8ef3047d29a873865178",
        "RepoTags": [
            "ubuntu:latest"
        ],
        "RepoDigests": [
            "ubuntu@sha256:f3a61450ae43896c4332bda5e78b453f4a93179045f20c8181043b26b5e79028"
        ],
        "Parent": "",
        "Comment": "",

...
etc
```

Right now, just by running a command to cat the labels, I can see some basic stuff about a singularity container:

```
 singularity exec ubuntu.img cat /.singularity.d/labels.json
{
    "SINGULARITY_DEFFILE_BOOTSTRAP": "docker",
    "SINGULARITY_DEFFILE": "Singularity",
    "SINGULARITY_DEFFILE_FROM": "ubuntu:latest",
    "SINGULARITY_BOOTSTRAP_VERSION": "2.2.99"
}
```

and why not have that be:

```
 singularity inspect ubuntu.img labels
{
    "SINGULARITY_DEFFILE_BOOTSTRAP": "docker",
    "SINGULARITY_DEFFILE": "Singularity",
    "SINGULARITY_DEFFILE_FROM": "ubuntu:latest",
    "SINGULARITY_BOOTSTRAP_VERSION": "2.2.99"
}
```

so, given that we will eventually want to interact with containers in this manner (eg integration with external tools) and we want it to not have to be known that labels (or other stuffs) are "hiding" in this hidden folder, we should provide easy access to these things via some kind of `inspect`. We could even use singularity to bootstrap Docker's API and serve their metadata without needing to pull the layers (eg you could inspect a Docker image and return a specific field, the size, number of layers, etc., and this is useful so you know how to best generate your singularity spec that bootstraps a Docker image. Thoughts?

**Comment by gmkurtzer** [comment]
Something like this?

```
$ singularity -q exec docker://centos cat /.singularity.d/labels.json
{"build-date": "20170406", "vendor": "CentOS", "name": "CentOS Base Image", "license": "GPLv2"}gmk@gmkdev2:~/git/singularity$ 
```

**Comment by vsoch** [comment]
yes exactly! We would start with labels, but probably eventually want to expose more about the containers configuration, etc.

**Comment by vsoch** [comment]
hey @gmkurtzer I just gave `inspect` a go:

https://asciinema.org/a/121620?speed=2

I made the default to show the runscript to support all oldest versions of Singularity, but the user can also ask for `--labels`. Should we add in a command to show some subset of environment too?

**Comment by vsoch** [comment]
ahh this was great :) Inspect FTW!!
