### ISSUE TITLE
ImportError: cannot import name get_fullpath

### ISSUE THREAD

**Issue by lheck** [apptainer/singularity#656]
Dear singularity team, I am trying to build singularity and get 
./configure_transform.py --defaults ../src/lib/config_defaults.h --infile singularity.conf.in --outfile singularity.conf
Traceback (most recent call last):
  File "./configure_transform.py", line 8, in <module>
    from utils import (
ImportError: cannot import name get_fullpath
make[1]: *** [singularity.conf] Error 1

I found a similar link on this page. It looked that this specific problem only appeared under #542 with dpjensen commenting. 

As I only now downloaded singularity from github, should the problem not have been solved in there?
Where can I go from here?

**Comment by lheck** [comment]
I should mention: we have a linux system and in our python installation we have utils packages installed using pip.

**Comment by vsoch** [comment]
hey @lheck ! This error was a name conflict, for a package called "utils" that does not have our functions. Could you please try installation with the development branch? We've fixed this by renaming utils to sutils. Let us know if this resolves the issue!

**Comment by lheck** [comment]
How do I get the development branch?

**Comment by ArangoGutierrez** [comment]
HI @lheck on your prefered folder. just run

```bash
git clone -b development https://github.com/singularityware/singularity.git 
```
Or you can try with the [Singularity-Builder](https://github.com/singularityware/singularity-builder) repo.

**Comment by vsoch** [comment]
in an already existing repo:

```
git checkout -b development
git pull origin development
```
or clone fresh

```
git checkout -b development https://github.com/singularityware/singularity.git
```

then cd singularity and do the same install. You can check with:

```
singularity --version
```
which should be something like 2.99 followed by the commit id.

**Comment by vsoch** [comment]
hey @lheck, this has long been fixed, so I'm going to close the issue. If you need help, please re-open! Thanks for using Singularity! :)
