### ISSUE TITLE
Files missing in release archive

### ISSUE THREAD

**Issue by cclerget** [apptainer/singularity#657]
Hello,

There is something wrong with generation of release archive.

After compiling and installing latest release 2.2.1 from release archive:
https://github.com/singularityware/singularity/releases/download/2.2.1/singularity-2.2.1.tar.gz
or
https://github.com/singularityware/singularity/archive/2.2.1.tar.gz
the resulting binary come without pull command.

By comparing archive content and git repository, it appear that libexec/cli/pull.* files are missing, for all versions

**Comment by vsoch** [comment]
hey @cclerget! pull wasn't added until a later version of 2.2, so your best bet will be to use development branch. You could also try one of the security releases for 2.2, although I'm not totally sure when it was added.

**Comment by cclerget** [comment]
Oh my bad, sorry ! I thought it was introduced in 2.2 release

**Comment by vsoch** [comment]
haha, np! I think at that time we were still having conversations like "oh, releases! yeah we should have those... Github tags? Oh yeah that will make it work!" :)
