### ISSUE TITLE
[feature request] Option to run only parts of the bootstrapping process. 

### ISSUE THREAD

**Issue by georghildebrand** [apptainer/singularity#658]
Hi here, i am fascinated by singularity. In the last weeks i started playing around with it a little and it works quite nice on our HPC system. One nice feature to have would be, if you could add a functionality to allow running the different bootstrapping stages separately. 

Example: 
when doing
>singularity bootstrap image.img imagedef.def

it would help to if one could run %post, %setup, bootstrap separately.

**Comment by gmkurtzer** [comment]
Hi there. In development d541fb954e282fc91993c9b14f0c074755f462d5, I have added the feature to do:

```bash
$ sudo singularity bootstrap --section post container.img bootstrap.def
```

Let me know if you have any questions or issues with it.

Thanks!

**Comment by vsoch** [comment]
hey is there any reason the --section command couldn't specify some additional sections of post? For example, let's say you have a tensorflow definition file, and there are different installation dependencies, depending on the cluster. You could either have different `%post` sections and specify to activate one (and not the other) or some ability to specify subsections of `%post` and then choose which to build (and the variable/choice would be recorded in the labels, etc.

**Comment by georghildebrand** [comment]
That's indeed a good idea. E.g.. In our cluster some GPU servers have
different driver versions. In that case such a system would help to only
rebuild the driver. But it could make the def file look more complicated.

I think if the bootstrap is not repeated over and over again it's already a
big win.

Will test it tomorrow! Thanks for your excellent work!

Am 10.05.2017 20:26 schrieb "Vanessa Sochat" <notifications@github.com>:

hey is there any reason the --section command couldn't specify some
additional sections of post? For example, let's say you have a tensorflow
definition file, and there are different installation dependencies,
depending on the cluster. You could either have different %post sections
and specify to activate one (and not the other) or some ability to specify
subsections of %post and then choose which to build (and the
variable/choice would be recorded in the labels, etc.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/singularityware/singularity/issues/658#issuecomment-300571712>,
or mute the thread

**Comment by gmkurtzer** [comment]
I like that idea, but won't get it into 2.3 before the release. I will keep it here for the 2.4 development which will start as soon as 2.3 hits master.

Thanks!
