### ISSUE TITLE
Using development branch on Singularity Hub

### ISSUE THREAD

**Issue by belledon** [apptainer/singularity#659]
Hey @vsoch ,

I was trying to build a container from a docker container and ran into an old issue with file names being too long when using `2.2.1`. I was pressed for time so I didn't think to save the output (I'd be happy to recreate it over the weekend). However, I remember that bug was fixed in the `librefractor` branch (which I'm assuming is now `development`). Cloning and doing a local build from the `development` branch worked without a hitch. I was wondering if it would be easy on your end to include the singularity branch in build options of Singularity Hub? Sorry if this is a repost/ not practical.

(Forgot to include the container)
The container was from `singularity pull shub://851`. 
The working bootstrap is in `singularity pull shub://853`

**Comment by vsoch** [comment]
hey @belledon ! I could definitely generate a custom development image for a workaround for now, although my hope was to be able to provide versioned (eg 2.3) images to not have any "quasi finished" ones up there. Hey @gmkurtzer how close realistically are we to 2.3 release?

**Comment by belledon** [comment]
@vsoch , 
 It makes sense to shy away from "quasi-finished" versions! I have all I need on my end. Just figured it may serve some use in controlled settings.

**Comment by vsoch** [comment]
yeah I understand completely! There are some exciting updates / changes to singularity hub, and it's infrastructure coming in the next few months - still figuring out some details and then we will be able to move forward with the work! Minimally, when 2.3 is out I will update the builders quickly for the new version.

**Comment by belledon** [comment]
Hey @vsoch ,

Just tried it with 2.3 and received a similar error. This was during some variable exports when preparing to install nvidia drivers. 

```
DEBUG [U=0,P=2186] bootdef_parser.c:202:singularity_bootdef_section_get(): Reading line: PATH=$NV_DRIVER_PATH:\$PATH
ERROR [U=0,P=2186] util/util.c:159:strjoin() : Overly-long string encountered.
ABORT [U=0,P=2186] util/util.c:160:strjoin() : Retval = 255
```

From the def file in https://github.com/belledon/chainer_sing/blob/master/Singularity
The container has ID 1050

The build succeeds on my local system with version `2.2.99-development.g0ea6d4e`

**Comment by vsoch** [comment]
hey @belledon ! The builders are now updated. It looks like your collection builder is still set to singularity 2.2.1:

```python
>>> builder.spec
{ 'builder_name': 'singularity-builder-2-2-1-50gb',
  'bucket_name': 'singularity-hub-regional',
  'environment': 'gce'}
```

I am hesitant about changing user preferences for builders, but you can do this on your own by clicking on the EDIT BUILDER button in your collection:

![image](https://cloud.githubusercontent.com/assets/814322/26707615/13a3e4ac-4714-11e7-9c83-fe41378c7eba.png)

and then selecting the 2-3-50gb builder:

![image](https://cloud.githubusercontent.com/assets/814322/26707652/4f695bac-4714-11e7-8bcf-ff3d4fe073d8.png)

Actually, I probably need to make very clear instructions to do this - people will assume (with older collections, that is) that it would be changed automatically (and it's not). Do you want to test changing it, and then push again to redo the build? There were bugs in the builders and I had to just redo them, so it will be a good test. We can close the issue only after confirming the entire process goes smoothly (without the overly long string error!) And I will get on making the "how to change your builder" docs asap!

**Comment by belledon** [comment]
Hey @vsoch ,

Thanks for the response! I ran into a memory error but that was my bad. Quick question, is there anyway to tell the build to remake a branch? I've been just commiting some null change on the def file each time.

**Comment by vsoch** [comment]
I haven't added any sort of "push to rebuild" button because I want each one to be associated with a unique commit - so for now your only option is to make a trivial change and commit again. I realize this is silly, so I'm definitely thinking about a reasonable solution. It would mean cleaning up the first (and not messing that up) so I need to think it over.

**Comment by belledon** [comment]
I think it makes sense from a backend  point of view. 

Unfortunately I ran into this error. 

```
Running test scriptlet
Finalizing Singularity container
/tmp/tmpw95c4ays/image
DEBUG:shub_builder:Built image: /tmp/tmpw95c4ays/b340d5cb482e863b562e3999a975c4c5
INFO:shub_builder:Final time of build 195 seconds.
INFO:shub_builder:Singularity 2.3-master.gf737013 being used.
Traceback (most recent call last):
File "", line 1, in 
File "/usr/local/lib/python3.5/dist-packages/singularity/build/google.py", line 245, in run_build
params=params)
File "/usr/local/lib/python3.5/dist-packages/singularity/build/main.py", line 191, in run_build
old_version=old_version)
File "/usr/local/lib/python3.5/dist-packages/singularity/package.py", line 160, in package
file_obj,tar = get_memory_tar(image_path)
File "/usr/local/lib/python3.5/dist-packages/singularity/reproduce.py", line 513, in get_memory_tar
byte_array = cli.export(image_path)
File "/usr/local/lib/python3.5/dist-packages/singularity/cli.py", line 220, in export
output = self.run_command(cmd,sudo=sudo)
File "/usr/local/lib/python3.5/dist-packages/singularity/cli.py", line 81, in run_command
output = run_command(cmd,suppress=suppress) # suppress doesn't make difference here
File "/usr/local/lib/python3.5/dist-packages/singularity/utils.py", line 113, in run_command
output, err = process.communicate()
File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
stdout, stderr = self._communicate(input, endtime, timeout)
File "/usr/lib/python3.5/subprocess.py", line 1745, in _communicate
stdout = b''.join(stdout)
MemoryError
```

ID is 1056

**Comment by vsoch** [comment]
ah interesting, I know the reason for this. The old method created a tar in a sort of hacky way, and this new way is more elegant (it does it in memory) but it looks to be not a good solution given that your container is massive. I unfortunately won't have a quick solution for this soon, but let me poke around and see what I can do. I think this would be a good one for me to test manually, but probably tomorrow. Sorry for the delay - just too much to do!

**Comment by vsoch** [comment]
would you mind closing the issue here, and opening again with the error above on the singularityhub issues board? https://github.com/singularityhub/singularityhub.github.io/issues This is actually an issue with singularity-python, but used via the hub :)

**Comment by belledon** [comment]
Will do!

**Comment by vsoch** [comment]
Thanks! And hey, we got that "overly long string" issue fixed! That's progress, if you ask me, haha.

**Comment by belledon** [comment]
Yes it is!! =)
