### ISSUE TITLE
compiling singularity on RHEL 5

### ISSUE THREAD

**Issue by Amjadhpc** [apptainer/singularity#660]
Hello,
We have  an HPC system that is still running on RHEL 5 for legacy reasons. 
We have kernel   2.6.18-164.el5 , glibc-2.5.42 and gcc-4.1.2 .

I would like to know if someone has been able to compile and install singularity on  RHEL 5. ?
I tried compiling 2.2.1 version and ran into errors regarding  'O_CLOEXEC'  .
O_CLOEXEC is not supported on glibc 2.5.42

Thanks

**Comment by gmkurtzer** [comment]
Hi @Amjadhpc,

What version of Singularity are you testing? You may have to go back and use Singularity v2.1.

Greg

**Comment by Amjadhpc** [comment]
Hi @gmkurtzer 

I  am using Singularity v 2.0 . 
When i try to create centos 7 image  using RHEL 5.4 , i get segfault on image bind . It fails to bind
Attaching the output of singularity create /tmp/centos7.img command

[out.docx](https://github.com/singularityware/singularity/files/1000524/out.docx)

**Comment by gmkurtzer** [comment]
Can you try to update to Singularity v2.1 or v2.2.1? We have dropped support in Singularity for RHEL5 in the development branch (soon to become 2.3), and it may have also had some incompatibilities in 2.2.1.

Thanks!

**Comment by Amjadhpc** [comment]
I tried v 2.1 . but hitting rpm errors while bootstraping

s**ingularity bootstrap /tmp/centos7.img centos.def (The def file is used from examples directory).**

 when i try to bootstrap it gives me Rpm_check_debug vs depsolve errors.  I am using a local repo of Centos 7 instead of Centos 7 Mirror  (Thanks to  Wannacry cyber attack , my organization blocked yum ):) Not sure if this is the issue
The short summary of  errors is as follows

Transaction Summary
========================================================================================================================================
Install    109 Package(s)
Update       0 Package(s)
Remove       0 Package(s)
 
Total download size: 58 M
Downloading Packages:
----------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                   1.6 GB/s |  58 MB     00:00
Running rpm_check_debug
ERROR with rpm_check_debug vs depsolve:
rpmlib(FileDigests) is needed by pygpgme-0.3-9.el7.x86_64
rpmlib(PayloadIsXz) is needed by pygpgme-0.3-9.el7.x86_64
rpmlib(FileDigests) is needed by bzip2-libs-1.0.6-12.el7.x86_64
rpmlib(PayloadIsXz) is needed by bzip2-libs-1.0.6-12.el7.x86_64

Complete!
(1, [u'Please report this error in http://yum.baseurl.org/report'])

**Comment by gmkurtzer** [comment]
I can't replicate this easily right now, but if anyone else can, that would be helpful!

Thanks!

**Comment by truatpasteurdotfr** [comment]
- CentOS-5 is now EOL'ed, as you know.
- CentOS-5 rpm can not handle CentOS-7 rpms.
- Even if you could bootstrap a CentOS-7 container, you would faild trying to run it on CentOS-5...
```
[tru@sillage singularity]$ ./Centos-7+yum.img
WARNING: No Singularity runscript found, launching 'shell'
FATAL: kernel too old
```
- CentOS-5 can only run singularity 2.1.2 afaik (so no docker import etc...)

**Comment by truatpasteurdotfr** [comment]
and you can't run a Singularity 2.2 CentOS-7 container created on CentOS-7 on CentOS-5 using singularity 2.1.2 (although you can run the singularity busybox toy model created on Singularity 2.2 on CentOS-7 on the CentOS-5 with singularity 2.1.2)

**Comment by truatpasteurdotfr** [comment]
on the bright side you still can run a singularity-2.2 CentOS-6 container on CentOS-5 with singularity 2.1.2
```
Singularity.s22-c6.img> uname -a
Linux sillage.xxx  2.6.18-416.el5 #1 SMP Fri Oct 28 11:52:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Singularity.s22-c6.img> rpm -q glibc
glibc-2.12-1.209.el6_9.1.x86_64
```

**Comment by dtrudg** [comment]
Closing this ticket. As noted above end of life for CentOS 5 was March 31st 2017

**Comment by vsoch** [comment]
:skull:

**Comment by vsoch** [comment]
:ghost: reincarnation!

**Comment by vsoch** [comment]
just kidding :)
