### ISSUE TITLE
singularity shell of tar.gz images

### ISSUE THREAD

**Issue by tobigithub** [apptainer/singularity#661]
Not sure if bug or feature request, running tar.gz images does not work, however singularity says its uncompressing the tar.gz container and trying to run it. Also changing permissions to read/write (other) does not help. Maybe caching issue of expanded image?

Reason for compression: smaller files, faster handling on network or USB sticks etc.
Example:

````
# bootstrapped ubuntu image runs fine (131 MByte)
vm@ubuntu:~/git/singularity$ singularity shell images/ubuntu-14-desktop
Singularity: Invoking an interactive shell within container...
Singularity.ubuntu-14-desktop> $ exit

# now compress to tar.gz (2.1 MB) // File shrank by 2147483679 bytes; padding with zeros
vm@ubuntu:~/git/singularity$ tar -czvf images/ubuntu-14-desktop.tar.gz   images/ubuntu-14-desktop 
images/ubuntu-14-desktop

# singularity shell with tar.gz singularity image does not run
vm@ubuntu:~/git/singularity$ 
vm@ubuntu:~/git/singularity$ singularity shell images/ubuntu-14-desktop.tar.gz
Opening gzip compressed archive, stand by...
ERROR  : Container does not have a valid /bin/sh
ABORT  : Retval = 255
vm@ubuntu:~/git/singularity$ 
````
Tobias

**Comment by jmstover** [comment]
I haven't done a tgz image yet... but when you made it, you made the tarball with the `images/ubuntu-14-desktop` path.

I'm not sure when it extracts it, if it expects it to be with the root as the extract point. What happens if you create the tarball like:

```
cd images/ubuntu-14-desktop
tar -czvf ../ubuntu-14-desktop.tar.gz .
```
Do you still get the same error?

**Comment by tobigithub** [comment]
@jmstover My naming convention for the image file was wrong, It is not a directory but really an image file. But the issue persists. Thanks for checking .

````
# singularity image of bootstrapped ubuntu14 works fine
vm@ubuntu:~/git/singularity$ singularity shell images/ubuntu-14-desktop.img 
Singularity: Invoking an interactive shell within container...

Singularity.ubuntu-14-desktop.img> $ exit
vm@ubuntu:~/git/singularity$ 


# compressing the image file
vm@ubuntu:~/git/singularity$ tar -czvf images/ubuntu-14-desktop.tar.gz   images/ubuntu-14-desktop.img 
images/ubuntu-14-desktop.img
vm@ubuntu:~/git/singularity$ 

# starting the singularity shell with the tar.gz image file
vm@ubuntu:~/git/singularity$ singularity shell images/ubuntu-14-desktop.tar.gz
Opening gzip compressed archive, stand by...
ERROR  : Container does not have a valid /bin/sh
ABORT  : Retval = 255
vm@ubuntu:~/git/singularity$ 
````

**Comment by vsoch** [comment]
The command I've typically used to compress images is:

```
gzip -c -9 image.img > image.img.gz
```

and to decompress:

```
gzip -d -f image.img.gz
```

I'm not sure about .tar.gz, but I would recommend the above.

**Comment by tobigithub** [comment]
@vsoch: Tnx, uncompressing the file with the archive manager and the running it again is fine,
But I want to run the compressed archive directly.   I think its not related to a compression error, but maybe incompatible format or other issues, or its not implemented yet. In case of tar.gz the archive is somehow handled, for *.gz only it can not handle it, because the container is not found. 

````
# singularity image of bootstrapped ubuntu14 works fine
vm@ubuntu:~/git/singularity$ singularity shell images/ubuntu-14-desktop.img 
Singularity: Invoking an interactive shell within container...

Singularity.ubuntu-14-desktop.img> $ exit
vm@ubuntu:~/git/singularity$ 

# compressing with gzip only
vm@ubuntu:~/git/singularity$ gzip -c -9 images/ubuntu-14-desktop.img > images/ubuntu-14-desktop.img.gz
vm@ubuntu:~/git/singularity$ 

# using gzip only the container is not found
vm@ubuntu:~/git/singularity$ singularity shell ubuntu-14-desktop.img.gz
ERROR  : Container not found: ubuntu-14-desktop.img.gz
ABORT  : Retval = 255
````

**Comment by vsoch** [comment]
Could you try that last one with --debug?

**Comment by vsoch** [comment]
It might be that it's decompressing in a temp folder, but forgetting to rename based on the tweaked extension, or not implemented. I remember way back for some older version (or at least I think) it would decompress before using the image. I also remember that @gmkurtzer and I were chatting about .tar.gz specifically, and reasons for not using it for images.

**Comment by tobigithub** [comment]
@vsoch, indeed the image is extracted to 
"/tmp/singularity-rundir.UPaAzka0/ubuntu-14-desktop.tar.gz/images" so maybe its not picking it up,
Looking quickly through the sources the tar.gz files are handled in **image-handler.sh**. So maybe there is an issue. Btw, I was not able to invoke the --debug option.


````
    *.tgz|*.tar.gz)
        NAME=`basename "$SINGULARITY_IMAGE"`
        if [ -z "${SINGULARITY_CACHEDIR:-}" ]; then
            SINGULARITY_CACHEDIR="/tmp"
        fi
        if [ ! -d "$SINGULARITY_CACHEDIR" ]; then
            message ERROR "Cache directory does not exist: $SINGULARITY_CACHEDIR\n"
            ABORT 1
        fi
        if ! SINGULARITY_TMPDIR=`mktemp -d $SINGULARITY_CACHEDIR/singularity-rundir.XXXXXXXX`; then
            message ERROR "Failed to create tmpdir\n"
            ABORT 255
        fi

        CONTAINER_DIR="$SINGULARITY_TMPDIR/$NAME"
        if ! mkdir -p "$CONTAINER_DIR"; then
            message ERROR "Could not create cache directory: $CONTAINER_DIR\n"
            ABORT 255
        fi

        message 1 "Opening gzip compressed archive, stand by...\n"
        # this almost always gives permission errors, so ignore them when
        # this almost always gives permission errors, so ignore them when
        # running as a user.
        tar -C "$CONTAINER_DIR" -xzf "$SINGULARITY_IMAGE" 2>/dev/null

        chmod -R +w "$CONTAINER_DIR"

        SINGULARITY_IMAGE="$CONTAINER_DIR"
        SINGULARITY_RUNDIR="$SINGULARITY_TMPDIR"
        export SINGULARITY_RUNDIR SINGULARITY_IMAGE
    ;;
````

**Comment by vsoch** [comment]
ah ok, I think I see the underlying issue - it's past midnight and I need to go to sleep, but I can definitely help with this later today! TLDR - we want to trace the variable for referencing the image, and if we decompress, make sure the name changes accordingly. We should check with @gmkurtzer about this too, it may be that there is a good reason for not supporting running .tar.gz directly. More later! gnite!

**Comment by vsoch** [comment]
It looks like it's reading the header:

```
DEBUG   [U=1000,P=12157]   singularity_image_check()                 First line of image(fd=5): c��Xubuntu.img
```
and expecting it to be squashfs

```
DEBUG   [U=1000,P=12157]   singularity_image_mount_squashfs_check()  Image does not appear to be of type '.sqsh': ubuntu.img.gz
```
I'm thinking this is no longer supported, but we should check with @gmkurtzer. I think the fix would be to do the decompression before checking the image, unless it's no longer to be supported, in which case we want it to fail. @gmkurtzer is giving a talk today so I would expect some delay, unless he is bored and waiting around and find the issue, haha.

**Comment by gmkurtzer** [comment]
This is working fine for me with the development branch. One of the important factors to creating the tarball is to make sure that there are no child directories created. For example:

```
$ tar cvzf /tmp/container.tar.gz .
```
Would work where:
```
$ tar cvzf /tmp/container.tar.gz relative_path_to_contianer
```
Would not.

I think this is what @jmstover was referring to earlier. 

Thanks!

**Comment by tobigithub** [comment]
Mmmh, does not work for me, at least not under ubuntu14. 

````
# singularity version
vm@ubuntu:~$ singularity --version
2.2.99

# create image in /tmp
vm@ubuntu:~/git/singularity$ sudo singularity create --size 2048 /tmp/ubuntu14.img
Creating a new image with a maximum size of 2048MiB...
Executing image create helper
Formatting image with ext3 file system
Done.

#show image file exists (2 GB)
vm@ubuntu:~/git/singularity$ ls -l /tmp/ubuntu14.img 
-rwxr-xr-x 1 root root 2147483679 May 13 17:35 /tmp/ubuntu14.img

# bootstrapping it
vm@ubuntu:~/git/singularity$ sudo singularity bootstrap /tmp/ubuntu14.img examples/ubuntu.def
...snip ... snip lots of text
Processing triggers for libc-bin (2.19-0ubuntu6) ...
No test code provided in this container

#show the file size of the bootstrapped container
vm@ubuntu:~/git/singularity$ ls -l /tmp/ubuntu14.img 
-rwxr-xr-x 1 root root 2147483679 May 13 17:42 /tmp/ubuntu14.img
vm@ubuntu:~/git/singularity$ 

#invoke singularity shell (working)
vm@ubuntu:~/git/singularity$ singularity shell /tmp/ubuntu14.img 
Singularity: Invoking an interactive shell within container...

Singularity.ubuntu14.img> $ whoami
vm
Singularity.ubuntu14.img> $ uname -r
3.19.0-25-generic
Singularity.ubuntu14.img> $ exit
vm@ubuntu:~/git/singularity$ 

# now compressing it, according to proposed solution (no child dir)
vm@ubuntu:~/git/singularity$ tar cvzf /tmp/ubuntu14.img  .
tar (child): /tmp/ubuntu14.img: Cannot open: Permission denied
tar (child): Error is not recoverable: exiting now
./
./LICENSE
./README.md
vm@ubuntu:~/git/singularity$ 

# because img is root (permission wise) use sudo
sudo tar cvzf /tmp/ubuntu14.img  .
... snip ... snip lots of text
./docs/README.md
./compile
./Makefile.am
./AUTHORS
vm@ubuntu:~/git/singularity$ 

#image is now compressed to 7.4 MB (0.3%)
vm@ubuntu:~/git/singularity$ ls -l /tmp/ubuntu14.img 
-rwxr-xr-x 1 root root 7492172 May 13 17:51 /tmp/ubuntu14.img
vm@ubuntu:~/git/singularity$ 

# now start shell with compressed file
vm@ubuntu:~/git/singularity$ singularity shell /tmp/ubuntu14.img
ERROR  : File is not a valid Singularity image, aborting...
ABORT  : Retval = 255
vm@ubuntu:~/git/singularity$ 

# start with sudo
vm@ubuntu:~/git/singularity$ sudo singularity shell /tmp/ubuntu14.img
sudo: unable to resolve host ubuntu
ERROR  : File is not a valid Singularity image, aborting...
ABORT  : Retval = 255

# magically restore image (2.1 GB)

# change write permissions for group and others
chmod g+w /tmp/ubuntu14.img 
chmod o+w /tmp/ubuntu14.img 

# now the permissions changed
vm@ubuntu:~/git/singularity$ ls -l /tmp/ubuntu14.img 
-rwxrwxrwx 1 vm vm 2147483679 May 13 17:42 /tmp/ubuntu14.img

# now tar again according to proposed solution
tar cvzf /tmp/ubuntu14.img . 
....snip .... snip lots of text
./compile
./Makefile.am
./AUTHORS
vm@ubuntu:~/git/singularity$ 

# file has now user permissions and is compressed to 7MB
vm@ubuntu:~/git/singularity$ ls -l /tmp/ubuntu14.img
-rwxrwxrwx 1 vm vm 7492172 May 13 18:09 /tmp/ubuntu14.img
vm@ubuntu:~/git/singularity$ 

# start shell (does not work)
vm@ubuntu:~/git/singularity$ singularity shell /tmp/ubuntu14.img
ERROR  : File is not a valid Singularity image, aborting...
ABORT  : Retval = 255
vm@ubuntu:~/git/singularity$ 

# sudo start shell 
vm@ubuntu:~/git/singularity$ sudo singularity shell /tmp/ubuntu14.img
sudo: unable to resolve host ubuntu
ERROR  : File is not a valid Singularity image, aborting...
ABORT  : Retval = 255
vm@ubuntu:~/git/singularity$ 

`````
actually I am currently unable expand the file back (unless I use an archive manager)
````
# file size stays 7 MB compressed instead of 2BGyte
vm@ubuntu:~/git/singularity$ sudo tar -czf /tmp/ubuntu14.img .
sudo: unable to resolve host ubuntu
vm@ubuntu:~/git/singularity$ sudo tar -xzf /tmp/ubuntu14.img .
sudo: unable to resolve host ubuntu
vm@ubuntu:~/git/singularity$ ls -l /tmp/ubuntu14.img
-rwxrwxrwx 1 vm vm 7492172 May 13 18:33 /tmp/ubuntu14.img
vm@ubuntu:~/git/singularity$ 
````

**Comment by vsoch** [comment]
I don't think you are using development branch. When you do version you should see the commit:

```
singularity --version
2.2.99-development.g945c6ee
```

**Comment by vsoch** [comment]
To install from development:

```
git clone -b development https://www.github.com/singularityware/singularity.git
cd singularity
./autogen.sh
./configure --prefix=/usr/local
make
sudo make install
```

**Comment by jmstover** [comment]
Hi Tobias,

  > vm@ubuntu:~/git/singularity$ tar cvzf /tmp/ubuntu14.img .

You're creating a tar of the Singularity code base there, and not a rootfs
an OS install.... The directory you are in when you run that tar command,
should be equivalent to the / directory of an OS install.

So, you'll have a structure like:

some_dir/
bin/
lib/
lib64/
etc/
var/
[...]

You'll change to 'some_dir', and then run the command: tar czvf
/tmp/something.img .

The file should be a tar of an OS structure...

-J

**Comment by tobigithub** [comment]
Hi,
now under CentOS 6.5. BTW many of the installations on the LBL wiki do not work out of the box
due to permission settings, for example a user can install centos into a virtual machine, but is not
part of the sudoer group. Many commands on the WIKI fail without deeper LINUX knowledge.
So here all commands are executed as su (bad I know, just from a clean desktop vm install)

````

# create image works
[root@localhost singularity]# singularity create --size 2048 /tmp/Centos-7.img
 
# bootstrap the image works
[root@localhost singularity]# singularity bootstrap /tmp/Centos-7.img examples/centos.def
 
# running singularity works
[root@localhost singularity]# singularity shell /tmp/Centos-7.img
 
# compressing file from 2 GB to 7 MB works
[root@localhost singularity]# tar cvzf /tmp/Centos-7.img . 
 
# show the compressed image works
[root@localhost singularity]# ls -l /tmp/Centos-7.img
-rwxr-xr-x. 1 root root 6612516 May 13 20:10 /tmp/Centos-7.img
[root@localhost singularity]#
 
# starting the image does not work
[root@localhost singularity]# singularity shell /tmp/Centos-7.img
ERROR  : File is not a valid Singularity image, aborting...
ABORT  : Retval = 255
[root@localhost singularity]# singularity create --size 2048 /tmp/Centos-7.img
````
I think many of the examples need to be tested on a clean install from an ISO (like I did with UBUNTU and CentOS) and then without any additional modifications the commands should be shown in the WIKI. For example in this case the image file is just compressed without *.tar.gz extension, so the singularity script might not catch that.

The original question was how to execute a singularity shell with a compressed (tar.gz) image file.

**Comment by jmstover** [comment]
Hi Tobias,

> # compressing file from 2 GB to 7 MB works
> [root@localhost singularity]# tar cvzf /tmp/Centos-7.img .

In the above, you're overwriting Centos-7.img file, not compressing it. The
'-c' option to tar is _create_. So, you're creating a new file named
'Centos-7.img' with the contents of your current working directory (the '.'
used).

So... I don't think that's doing what you're thinking it's doing.

-J

**Comment by vsoch** [comment]
hey Tobias, are you treating the `.img` extension as a compressed image? Singularity uses the extension to determine the file type [see here](https://github.com/singularityware/singularity/blob/development/libexec/image-handler.sh#L225) so if you are giving a `.img` that isn't actually one, I would suspect something might go wrong. If you try the above with the image extension properly specified, do you still get the error?

**Comment by vsoch** [comment]
Yes +1 @jmstover... something is off that a command to create in a compressed file doesn't result in an extension that indicates it has been compressed.

**Comment by tobigithub** [comment]
@jmstover  

> You're creating a tar of the Singularity code base there, and not a rootfs
> an OS install.... The directory you are in when you run that tar command,
> should be equivalent to the / directory of an OS install.

Thank  you Jason, OK. I am not a LINUX expert, what would be the appropriate commands to create an image file, make it bootable, compress it and execute it?

**Comment by vsoch** [comment]
Can't you just do:

```
gzip -c -9 container.img > container.img.gz
```

**Comment by tobigithub** [comment]
@vsoch 

> hey Tobias, are you treating the .img extension as a compressed image? Singularity uses the extension to determine the file type see here so if you are giving a .img that isn't actually one, I would suspect something might go wrong. If you try the above with the image extension properly specified, do you still get the error?

Hi Vanessa,
yes indeed, that may be an issue, btw I pulled the singularity development version for CentOS, but had really troubles to run it as a simple user with sudo.  So I ended up running everything as root. Also I renamed the compressed Centos-7.img to Centos-7.img.tar.gz and tried to execute it, still same error.

I would like to know the 4 commands to create an image, make it bootable, then compress it and run a singularity shell of the compressed file.

**Comment by vsoch** [comment]
Yeah I just tried this out and I think there is a bug - the image should decompress before it is attempted to run or mount, and this is what was done with 2.2 (the images being built on Singularity hub have essentially this flow). Here is what we essentially do on Singularity hub (but using bootstrap):

```
singularity create parsnip.img
singularity import parsnip.img docker://ubuntu
gzip -c -9 parsnip.img > parsnip.img.gz
```

and for sanity check, I also tried an image generation that does bootstrap (which would require sudo as the above does not:

```
singularity create tempo.img
sudo singularity bootstrap tempo.img Singularity
 gzip -c -9 tempo.img > tempo.img.gz
```
(the contents of the `Singularity` file are doing a bootstrap docker with ubuntu, and nothing else:

in both of these cases I reproduced your error:

```
 singularity shell tempo.img.gz 
ERROR  : Failed to mount image in (read only): Invalid argument
ABORT  : Retval = 255
vanessa@vanessa-ThinkPad-T4
```

I also tried with using sudo to create the image:

```
sudo singularity create tempo.img
sudo singularity bootstrap tempo.img Singularity
 gzip -c -9 tempo.img > tempo.img.gz
```

and the same error. In the case of the (old) version 2.2, this same thing *does* work - the image is generated as above and then decompressed at runtime, for example

```
 singularity pull shub://vsoch/hello-world
Done. Container is at: ./vsoch-hello-world-master.img
vanessa@vanessa-ThinkPad-T450s:~/Desktop$ singularity shell vsoch-hello-world-master.img 
Singularity: Invoking an interactive shell within container...

$
```

but it doesn't look like we are doing that step in the current version, it checks for directory, squashfs, no go:

```
VERBOSE [U=1000,P=2826]    singularity_image_mount()                 Checking what kind of image we are mounting
DEBUG   [U=1000,P=2826]    singularity_image_mount_squashfs_check()  Image does not appear to be of type '.sqsh': parsnip.img.gz
DEBUG   [U=1000,P=2826]    singularity_image_mount_dir_check()       Checking if image is a directory
VERBOSE [U=1000,P=2826]    singularity_image_mount_dir_check()       Source path is not a directory: parsnip.img.gz
VERBOSE [U=1000,P=2826]    singularity_image_mount()                 Attempting to mount as singularity image
DEBUG   [U=1000,P=2826]    singularity_registry_get()                Returning NULL on 'WRITABLE'
DEBUG   [U=1000,P=2826]    singularity_priv_escalate()               Temporarily escalating privileges (U=1000)
DEBUG   [U=0,P=2826]       singularity_priv_escalate()               Clearing supplementary GIDs.
VERBOSE [U=0,P=2826]       singularity_image_mount_image_mount()     Mounting /dev/loop2 in read/only to: /var/lib/singularity/mnt/source
ERROR   [U=0,P=2826]       singularity_image_mount_image_mount()     Failed to mount image in (read only): Invalid argument
```

and not sure if this is relevant, but the permissions are also different:

```
ls -l parsnip.img*Done. Container is at: ./vsoch-hello-world-master.img
vanessa@vanessa-ThinkPad-T450s:~/Desktop$ singularity shell vsoch-hello-world-master.img 
Singularity: Invoking an interactive shell within container...


-rwxr-xr-x 1 vanessa vanessa 805306400 May 13 21:06 parsnip.img
-rw-rw-r-- 1 vanessa vanessa  46841333 May 13 21:07 parsnip.img.gz
```

@gmkurtzer is it possible that the check for the file type / extension was not carried forward with the changes you made for 2.3? Either it's the case that the singularity (shub) endpoint/client is handling decompression before trying to use the image (which it does) and this was never supported, or it was supported and now is no longer working.

**Comment by vsoch** [comment]
and @tobigithub this probably isn't what you want, but you can still pass around images that are .tar.gz, and then decompress (unfortunately yourself) before running. eg:

```
singularity create parsnip.img
singularity import parsnip.img docker://ubuntu
gzip -c -9 parsnip.img > parsnip.img.gz
rm parsnip.img
gzip -d -f parsnip.img.gz # produces parsnip.img
singularity shell parsnip.img
Singularity: Invoking an interactive shell within container...

Singularity tempo.img:~/Desktop
```

**Comment by dtrudg** [comment]
Hi @tobigithub - since Singularity is now using squashfs by default to create compressed images, I'm not certain whether anything on this issue is still relevant to you? If you are good with the workflow on the latest 2.4 release of Singularity may we close this? Thanks.

**Comment by tobigithub** [comment]
@dctrud 
I think that solves the issue.
Thank you!
