### ISSUE TITLE
make install fails if root shell is not bash

### ISSUE THREAD

**Issue by truatpasteurdotfr** [apptainer/singularity#67]
Hi

just run into this and it took me some time to find out why my 'sudo make install' did not chmod 4755 libexec/sexec.

alpine linux root shell is /bin/sh
voidlinux root shell is /bin/ash

[tru@voidmusl ~]$ cat Makefile 
issue:
    @echo $$SHELL
    @if test "$$UID" = "0"; then \
        echo " root"; \
    else \
        echo " non root"; \
    fi
    @echo "$$UID"

[tru@voidmusl ~]$ make
/bin/bash
 non root

[tru@voidmusl ~]$ sudo make
/bin/sh
 non root

alpine:~$ make
/bin/bash
 non root

alpine:~$ sudo make
/bin/ash
 non root

test is a builtin and UID is not defined in these shells

replace the UID test by USER test ?
"$$UID" = "0"
"$$USER" = "root"

**Comment by gmkurtzer** [comment]
I did it a little bit different just incase we are in another shell that doesn't even offer $USER. Please test 493e319 whenever you get a chance.

Thanks!

**Comment by truatpasteurdotfr** [comment]
works for me :+1: alpine/voidlinux and voidlinux musl
