### ISSUE TITLE
(How to) Access local file during bootstrap?

### ISSUE THREAD

**Issue by nielsaka** [apptainer/singularity#674]
Hi, I hope this is the right place to ask this question.

I would like to use a local file on the host system to install something inside the container during the bootstrap process. However, I am having difficulties finding the file. I am not sure which parts of the host system are accessible during bootstrap. I gathered `/tmp/` is, but is the working directory of the bootstrap definition file or the directory where I run `singularity bootstrap` from as well?

As a workaround, I currently have a script that creates the container, bootstraps it and then runs

`sudo singularity exec --writable -B $PWD:/home/my_dir container.img command`

where `command` will do the installation using the files in the current working directory and `/home/my_dir` has been created in the container during bootstrapping.

It would be nicer, though, to have it mentioned in the bootstrap definition file and having it all take place during bootstrapping. I couldn't find anything in this regard in the documentation or in other issues. I am happy to be pointed at right place to look, though, of course.

Thanks!

**Comment by nielsaka** [comment]
Or, to put it differently, is it best practice to copy all the required local files to the host system's `/tmp/` before bootstrapping and then `cd /tmp/` during bootstrap?

**Comment by vsoch** [comment]
hey @nielsaka ! Yes we definitely need to have the docs updated - I am working on those for 2.3 now (with details about your question) and will post soon. The short answer is that for 2.3 (development branch) you can add files during bootstrap in a `%fies` section, eg:

```
%files
/path/on/host/file /path/in/container/file
```

This will use your standard copy (`cp`) command so the same general `<source>` and `<destination>` applies. For the older Singularity, you will need to copy files from the host to the variable `$SINGULARITY_ROOTFS` in the `%setup` section.

**Comment by vsoch** [comment]
just worked on the docs for bootstrap for 2.3, do you want to [check them out here](https://github.com/singularityware/singularityware.github.io/blob/docs/2.3/pages/docs/user-docs/docs-bootstrap-image.md#bootstrapping-a-container) and let me know if anything is unclear or should be better hashed out? Thank you!

**Comment by nielsaka** [comment]
Thanks for the feedback! I checked the documentation, installed the development version and tried the `%files` section. The files were copied, but only after the `%post` section had been executed. So installing a local package this way didn't work out. I resorted to using `%section` and copying files and folders to `/tmp/`.
Also, since `cp` is mentioned I thought at first I could use options, such as `-R /folder/on/host /folder/in/container/`, but that is not supported apparently.

 One minor thing regarding the docs, the local `href`s don't work (but that might be due to viewing the file on github?) and in the [environment docs](https://github.com/singularityware/singularityware.github.io/blob/docs/2.3/pages/docs/user-docs/docs-environment-metadata.md#environment) I was only able to make `VARIABLE_NAME=VARIABLE_VALUE` work, not `VARIABLE_NAME VARIABLE_VALUE`.

(and btw, thank you for this amazing project!)

**Comment by gmkurtzer** [comment]
Hi @nielsaka,

Hrmm, you bring up an interesting point regarding the order of things. It seems we can either create a `%files-pre` (or something like that) section that will copy files before running `%post`, or you can use the `%setup` section as that runs from your current directory and then install into the path located at `$SINGULARITY_ROOTFS`.

You mentioned that you "resorted to using `%section` and copying folders to `/tmp/`". Can you elaborate on what you did there?

BTW, you are right about the environment, good catch!

Thanks!

**Comment by vsoch** [comment]
@gmkurtzer - I would advocate for %files-setup so it's clear that it corresponds to setup. And then we would support `%files` as we do now, moving files after boostrap (because it's more likely the location where they are being moved to doesn't exist). Given that we support `%files-setup`, we should also support `%files-post`, because if I stumbled on a spec file and saw:

```
%files-setup

%post

%files-post
```

that would make a lot of sense to me, whereas this should work:

```
%files-setup

%post

%files
```

although it is less clear. And the current spec we have now is also still reasonable, but it should default to be `%files-post`

```
%files
# happens after bootstrap
```

And even if a user does something like this, we would still want it to work, and `%files` and `%files-post` should be treated equally:

```
%files
bla bla

%files-post
bla2 bla2
```

This is probably why Docker has taken a line by line approach (well along with the layers thing) - it gives the user more control over order of operations. I sort of like the way we do it, because we don't want to have to parse the %post section line by line looking for something like %file.

**Comment by vsoch** [comment]
And now that I'm thinking of it, I sort of like `%files-pre` a bit better (it's shorter) and better sandwiches the `%post` section , so I'll leave the specific name up to you.

**Comment by vsoch** [comment]
and @nielsaka thanks for the kind words!! I will fix those docs immediately!

**Comment by gmkurtzer** [comment]
And actually, in 2.4, I am planning on changing `%post` to something that makes more sense as to what it is actually doing... Perhaps something like `%install` or `%build` or something. `%post` is misleading in that what is it coming after? Who knows? I used to know, but we added more things that come after, so post isn't really post anymore. Very confusing. lol

**Comment by vsoch** [comment]
I agree, `%install` would be more specific. Build sort of gets at the entire process that the user is running, so I think I like `%install`, but no promises that my opinion won't change on this. Given that `%post` is likely to change, it probably makes sense to make the files commands general to be "before build/setup/post/install/whatever" happens, and then "after" so I would advocate for either `%files-pre` and `%files-post`, unless we plan to add some different paradigm for which pre and post doesn't make sense, in which case we should talk about other ways that a user could add a file (at a specific point) in the build/install process).

**Comment by vsoch** [comment]
hey @nielsaka did you have any more questions for this issue? Are there any points we overlooked or forgot to help with?

**Comment by nielsaka** [comment]
Hey, thanks, no, I haven't got any more questions at the moment. 

To answer @gmkurtzer from 19th May, what I now do ist the following. The bootstrap def file looks like this (more or less)


```
BootStrap: debootstrap
OSVersion: jessie
MirrorURL: http://ftp.de.debian.org/debian/

%setup
    cp -R code/package /tmp/

%runscript
    make

%files
    # will only be copied after %post is run

%post
    export LC_ALL=C
    ...
    Rscript -e 'install.packages("/tmp/package/", repos = NULL)'
```
During `%setup` a local package that lies in my local project folder under `code/package/` is copied to `/tmp/`. I like the ability to copy the whole directory using `cp -R`. My understanding is that in sections like `%file`, I would have to zip/tar it first(?) Using `/tmp/` as a location to transfer files to the container seemed the easiest way out. Finally, the very last line installs the package which is written in R.

**Comment by nielsaka** [comment]
I like the discussion above. Something like `%files-pre`, `%install`, `%files-post` would make sense to me as a user.

**Comment by vsoch** [comment]
hey @nielsaka- why are you running make for the runscript as opposed to handling it during the build? Is the container itself intended to be an on demand compiler or is the make for the packages you are providing within it? If you can give me a sense of what you want the final thing to do, I can try to help with the Singularity file above.

**Comment by nielsaka** [comment]
I use the container to run a bunch of scripts that execute statistical simulations, create graphs and tables and then build a paper with the results included. All this is managed by the `makefile`, so in principle the results are reproducible without the singularity container. But some dependencies are not necessarily available at my local HPC cluster and taking care of the computing environment adds another layer of reproducibility (which I guess I don't need to tell you about...), so singularity is great for that. 

I thought just having `make` and letting all the computations happen from within the container would be sufficient. I suppose that could be called an on demand compiler. After having managed to install the local package, it now also works like a charm :)

The separate `makefile` also has the nice effect that simulations that haven't changed don't need to be rerun when building the paper.

**Comment by fmorency** [comment]
+1 for the `%pre-files` feature. I need to copy files from host to container and manipulate them in the `%post` section

**Comment by gmkurtzer** [comment]
I'm wondering... Does anybody see any drawback to making the %files section simply run before %post (or whatever we end up renaming it too)? That seems cleaner, and I don't see any drawbacks.

**Comment by fmorency** [comment]
I agree with what @gmkurtzer is proposing. +1

**Comment by gmkurtzer** [comment]
There, implemented in [development 6755b2f]. Testing requested. :)

**Comment by mkandes** [comment]
I was just trying the %files option assuming that it occurred prior to %post (in v2.2). I'm glad I found this thread.

**Comment by dtrudg** [comment]
Closing this, as it's fixed in merged PRs. Please let us know if there are any further issues. Thanks!
