### ISSUE TITLE
singularity.spec %description is outdated

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#676]
The %description in singularity.spec talks about building the smallest most minimal possible containers, but that's not much like the current description of what singularity is (on the [website](http://singularity.lbl.gov)).

**Comment by vsoch** [comment]
yeah I'll put in a change for a PR, right now it reads:
```
%description
Singularity provides functionality to build the smallest most minimal
possible containers, and running those containers as single application
environments.
```
and I think what it's (sort of) getting at is a desire of modularity for function of containers.

**Comment by vsoch** [comment]
How about like:

```
%description
Singularity provides functionality to make portable
containers that can be used across host environments.
```

**Comment by gmkurtzer** [comment]
Where do we have that documented? That was in Singualrity v1.x, but I don't have %description doing anything anymore.

**Comment by vsoch** [comment]
I already changed this in my little development PR - it's in the singularity.spec.init file --> https://github.com/singularityware/singularity/pull/677/files#diff-b3fb1fb02c192e0be6fee00045236e40

**Comment by dtrudg** [comment]
Closing as PR #677 was merged
