### ISSUE TITLE
Running cached Docker Hub images can be slow

### ISSUE THREAD

**Issue by chrisgorgo** [apptainer/singularity#678]
```
[newuser@de835965be28 ~]$ time singularity run docker://poldracklab/mriqc:0.9.3
Docker image path: index.docker.io/poldracklab/mriqc:0.9.3
Cache folder set to /home/newuser/.singularity/docker
Creating container runtime...
Singularity: action-suid (U=500,P=70247)> USER=newuser, IMAGE='mriqc:0.9.3', COMMAND='run'

usage: mriqc [-h] [-v]
             [--participant_label [PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]]
             [-m [{T1w,bold,T2w} [{T1w,bold,T2w} ...]]] [-s SESSION_ID]
             [-r RUN_ID] [--nthreads NTHREADS] [--n_procs N_PROCS]
             [--mem_gb MEM_GB] [--write-graph] [--dry-run]
             [--use-plugin USE_PLUGIN] [--ica] [--testing] [--profile]
             [--hmc-afni] [--hmc-fsl] [-f] [--fft-spikes-detector]
             [-w WORK_DIR] [--report-dir REPORT_DIR] [--verbose-reports]
             [--ants-nthreads ANTS_NTHREADS] [--ants-settings ANTS_SETTINGS]
             [--deoblique] [--despike] [--start-idx START_IDX]
             [--stop-idx STOP_IDX] [--correct-slice-timing]
             bids_dir output_dir {participant,group} [{participant,group} ...]
mriqc: error: the following arguments are required: bids_dir, output_dir, analysis_level

real    2m33.440s
user    1m3.050s
sys     0m35.140s
```
The same command works almost instantaneous when using Docker. I wonder if some time can be saved by  saving the tarred layers with all of the file permission changed instead of performing the file permission changes each time an image is being run.

**Comment by vsoch** [comment]
The images with permissions changed are saved to the cache, and we do both download and changes with multirprocessing. Was this the first time you ran it?

**Comment by vsoch** [comment]
If you are running this from within a docker image, maybe you can try to set the `SINGULARITY_CACHE` directory to be something shared on the host (and mounted on the container) so that new images that are spawned find the already existing layers. We pick this up as a [variable in the environment!](https://github.com/singularityware/singularity/blob/development/libexec/python/defaults.py#L107)

**Comment by gmkurtzer** [comment]
In theory yes, but if we kept all of the docker layers expanded it would quickly take over everything. Plus, the exploded files that comprise the runtime container must exist on a local file system ends up ruling out any place in $HOME.

If you want it to be faster, you should create a Singularity image out of the docker container and run via the image. The docker action integration is mostly used as a parlor trick or for one time test/usage as it doesn't create persistent containers (and thus after each use they are cleaned).

**Comment by vsoch** [comment]
I (think?) @chrisfilo is either running the singularity image from within a Docker container (and the Singularity image is bootstrapping a docker image) to support running it on his workstation (Windows?) or it's the case he is running these jobs en masse (maybe also in Docker) and given bringing up a new Docker image, doesn't want to have to download/change permissions every single time? But if the second were true.. then probably he could run docker and doesn't need Singularity... ok I'm going to go remove my brain from this loopy matrix now... ! :)

**Comment by chrisgorgo** [comment]
Thanks for your feedback:
1) This was the third time this command was executed. First one was slower (download), the second one had roughly the same runtime as the third time.
2) I think cache is being reused since redownloading does not seem to happen.
3) This is being run inside Docker (on windows using Hyper-V), all three executions were done inside the same docker container instance to preserve cache.
4) I don't think storing cache on a mounted volume would help. Quite the opposite - docker host/container transfer times would slow it down.

If it's just the docker layers being exploded that is happening when I do subsequent `singularity run` I'm not sure how can this be made faster without sacrificing too much space.

What is the command for creating singularity image directly from Docker Hub? Is the documentation for 2.3 up somewhere?

**Comment by vsoch** [comment]
you would do:

```
singularity pull docker://bids/mriqc
```

and that should create and import into `bids-mriqc.img`

**Comment by vsoch** [comment]
and for docs... [wish granted!](https://github.com/singularityware/singularityware.github.io/blob/docs/2.3/pages/docs/user-docs/docs-pull.md)

**Comment by dtrudg** [comment]
Closing, as docs have been added. Let us know if any further issues. Thanks!
