### ISSUE TITLE
singularity pull: incorrect image size

### ISSUE THREAD

**Issue by chrisgorgo** [apptainer/singularity#679]
```
[newuser@2204cd237e7a ~]$ singularity pull docker://poldracklab/fmriprep:0.4.3
Initializing Singularity image subsystem
Opening image file: fmriprep-0.4.3.img
Creating 768MiB image
Binding image to loop
Creating file system within image
done
Image is done: fmriprep-0.4.3.img
Docker image path: index.docker.io/poldracklab/fmriprep:0.4.3
```
This is followed by lots of "no space left on device" errors due to too small initial .img file - this docker image is over 10Gb in size.

PS This image has been created with Docker >1.9.1 so it should have the relevant metadata.

**Comment by vsoch** [comment]
hey @chrisfilo ! Just testing this now, I still see a version 1 manifest:

```
from docker.api import *
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /home/vanessa/.singularity
VERBOSE2 SINGULARITY_ENVBASE found as None/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as None/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as /home/vanessa/Documents/Dropbox/Code/singularity/singularity/libexec/python
VERBOSE2 SHUB_NAMEBYHASH not defined (None)
VERBOSE2 SHUB_NAMEBYCOMMIT not defined (None)
VERBOSE2 SHUB_CONTAINERNAME not defined (None)
VERBOSE2 SINGULARITY_CONTENTS found as None/.singularity.d/.layers
VERBOSE2 SINGULARITY_PYTHREADS found as 9

client = DockerApiConnection(image='poldracklab/fmriprep:0.4.3')
manifest = client.get_manifest()
DEBUG Headers found: Content-Type,Accept
VERBOSE Registry: index.docker.io
VERBOSE Namespace: poldracklab
VERBOSE Repo Name: fmriprep
VERBOSE Repo Tag: 0.4.3
VERBOSE Version: None
VERBOSE Obtaining tags: https://index.docker.io/v2/poldracklab/fmriprep/tags/list
DEBUG GET https://index.docker.io/v2/poldracklab/fmriprep/tags/list
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?service=registry.docker.io&expires_in=9000&scope=repository:poldracklab/fmriprep:pull
DEBUG Headers found: Content-Type,Authorization,Accept
manifest['schemaVersion']
1
```
as an example, here is the same function to an image with a version 2 manifest:

```
client=DockerApiConnection(image='ubuntu:latest')
DEBUG Headers found: Content-Type,Accept
VERBOSE Registry: index.docker.io
VERBOSE Namespace: library
VERBOSE Repo Name: ubuntu
VERBOSE Repo Tag: latest
VERBOSE Version: None
VERBOSE Obtaining tags: https://index.docker.io/v2/library/ubuntu/tags/list
DEBUG GET https://index.docker.io/v2/library/ubuntu/tags/list
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?service=registry.docker.io&expires_in=9000&scope=repository:library/ubuntu:pull
clDEBUG Headers found: Content-Type,Authorization,Accept
eit
In [8]: manifest=client.get_manifest()
VERBOSE Obtaining manifest: https://index.docker.io/v2/library/ubuntu/manifests/latest
DEBUG GET https://index.docker.io/v2/library/ubuntu/manifests/latest

manifest.keys()
dict_keys(['schemaVersion', 'layers', 'mediaType', 'config'])

manifest['schemaVersion']
2
```
let me know if you want me to try any other images!

**Comment by gmkurtzer** [comment]
BTW, I just added a warning message when it can't obtain the size as expected. I'm thinking of just bombing out with a suitable error message as that is better then a failed pull/import.

You know... I still don't like the `pull` for docker images! <seals lips>

**Comment by vsoch** [comment]
@chrisfilo has a more rare use case, at least in the scientific community, of actually doing tests and continuous integration for building images (most just build from Github --> Docker Hub). An image of this latter kind will be built with the version 2.0 spec (Chris limitation is something to do with needing to build with a docker that works on Circle) so I would think that this estimation would work for most images. So in this case, it comes down to whether we want to take a chance at estimating size (and given how big these images get, we would likely get it wrong) or just abort. I think it would be a safer thing to assume that, given that we can't estimate the size, we would probably get it wrong, and abort.  However, the user should be able to get around this by giving the command a size. For example, in this case we would do like:

```
singularity pull docker://fatty/donutsareyummy
WARNING: Cannot detect size from version 1.0 manifest.
ERROR: Aborting creation and import of docker layers. Please use version 2.0 manifest or specify image size.
```

and then the user can either build the image to have a version 2.0 manifest, or do this:

```
singularity pull --size 10000000 docker://fatty/donutsareyummy
Image created fatty-donutsareyummy.img
./fatty-donutsareyummy.img
NOMNOMNOM !!
```

**Comment by chrisgorgo** [comment]
Do you know which Docker version I need to use to create V2 manifest? Or is
it a distinction between images pushed to Docker Hub vs images built on
Docker Hub.

Building images on CI has some serious advantages: you version your images
with tags and make sure you only push an image to Docker Hub if the tests
pass. We have 20-30 images built this way. It would be good to figure out a
way for this to work.

**Comment by vsoch** [comment]
I haven't had personal experience working with building and pushing Docker images on Circle, so I was just going from their docs. I was going off of the docs that I posted in [this issue](https://github.com/poldracklab/mriqc/issues/499), specifically here: https://docs.docker.com/registry/compatibility/#registry-v23 it says

>> Manifest Push with Docker 1.9 and Older
The Docker Engine will construct a Schema 1 manifest which the registry will persist to disk.
When the manifest is pulled by digest or tag with any docker version, a Schema 1 manifest will be returned.

I would try shelling into a circle build, and seeing if you are able to verify that the image is built with Docker 1.10 or later, and then view the manifest on the instance (before pushing). Then you can at least check that the issue is with the build on circle, and it's not some transfer error (and the hub is returning old data).

**Comment by chrisgorgo** [comment]
I switched to docker 1.10 in the latest release, but the size is still estimated incorrectly:

```
[newuser@a55dc27d5a87 ~]$ singularity pull docker://poldracklab/fmriprep:0.4.4
Initializing Singularity image subsystem
Opening image file: fmriprep-0.4.4.img
Creating 768MiB image
Binding image to loop
Creating file system within image
done
Image is done: fmriprep-0.4.4.img
Docker image path: index.docker.io/poldracklab/fmriprep:0.4.4
Cache folder set to /home/newuser/.singularity/docker
```
Are there other strategies for estimating image size we could explore? Maybe a sum of the size of all layers?

**Comment by vsoch** [comment]
Hey @chrisfilo - I'm sorry you are having trouble, I have never built images with circle so I'm not sure how to advise, but I can give you the method I use to check the manifest. Here is what you want to do:

https://asciinema.org/a/121684?speed=3

the instructions for copy paste are in the comments there, and I'll include them here as well:

You can use singularity python functions to check your manifest. First download it

      git clone -b development https://www.github.com/singularityware/singularity.git
      cd singularity/libexec/python
      
From the singularity/libexec/python folder do:

      ipython
      from docker.api import *
      client = DockerApiConnection(image="poldracklab/fmriprep:0.4.4") 
      manifest = client.get_manifest()

      # Then look at the version 
      manifest['schemaVersion']

      # if you want to force version 1.0
      manifest = client.get_manifest(old_version=True)

There are definitely ways that we could get the size of the layers automatically, but we need a solution that is quick, meaning it really has to come from the manifest. We are taking an approach that, in due time, **most** images will support (eg, version 1 manifests will likely not endure forever) and it's reasonable that, in the short term, the user that has a version 1 can supply a `--size`. I hope this is also reasonable to you - I can tell you that it took a lot of convincing to get the docker pull command to begin with, so might be good to not push the boundary on what you are insisting come with it. At least without some break :)
