### ISSUE TITLE
bc is a dependency of pull.exe (when pulling from Docker Hub) 

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#680]
When trying top pull an image from Docker Hub I get the following error.
```bash
ubuntu@ip-172-31-0-48:~$ singularity pull docker://tensorflow/tensorflow
/usr/local/libexec/singularity/cli/pull.exec: line 144: bc: command not found
ERROR  : Could not convert container size to integer
ABORT  : Retval = 255
```
Installing `bc` fixes the error.  But this could easily trip people up.

**Comment by vsoch** [comment]
let me give a go at handling this in python, one sec

**Comment by gmkurtzer** [comment]
Oh, that's an interesting idea, but I should be able to do this in native shell without spawning out another process. Do you have this done, if so can I check out the commit?

Thanks!

**Comment by vsoch** [comment]
Did you see my development branch? Yes I implemented it. see the link above!

**Comment by vsoch** [comment]
I'm not sure what you mean by being able to do this in native shell - you would always need to get an image's manifest with stuff that would be hard to do in shell, so unless you want to completely re-implement the python stuff in shell, I don't see how you could do it all in native shell... :/

**Comment by gmkurtzer** [comment]
Ahhhh, nevermind. I see how you are doing it now. Sorry, I was totally off on that!

**Comment by GodloveD** [comment]
So this is totally fixed now!  Awesome!
