### ISSUE TITLE
singularity supported uris discussion

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#681]
@GodloveD brought up a good issue, that our old docs showed examples of imports that don't seem to work:

```
    $ gunzip -c debian.tar.gz | singularity import /tmp/Debian
    $ singularity import /tmp/Debian.img debian.tar.gz
    $ singularity import /tmp/Debian.img file://debian.tar.gz
    $ singularity import /tmp/Debian.img http://foo.com/debian.tar.gz
    $ singularity import /tmp/Debian.img docker://ubuntu:latest

```

we should have discussion about what kinds of uri's we want supported for imports vs. images themselves, and if having file:// is really necessary. For the meantime, I removed the lines from the above that we are sure do not work.

**Comment by gmkurtzer** [comment]
Oh, yeah... I think I broke some of those. Great catch!

I will take care of these before the release in the shell code (`import.exec`)... That is, unless someone else wants to take a stab at it?

Thanks!

**Comment by GodloveD** [comment]
Looks like the help doc is now aligned with the function.  Is there a burning need to support html for `import`?  If not, I would just suggest closing this.

**Comment by vsoch** [comment]
I'm not sure anymore which types are supported - our publication lists the following:

![image](https://cloud.githubusercontent.com/assets/814322/26532884/3fe22dd0-43c2-11e7-8cda-4e85afc556c3.png)

I think we need to be consistent and support these. @gmkurtzer can you review your plan for which are / will continue to be supported?

**Comment by gmkurtzer** [comment]
Are these for imports, or direct container actions (run, shell, test, exec, etc..)?

**Comment by vsoch** [comment]
The table for the paper above is for the supported container formats. So I think it follows that we should be able to have containers in that format. But for this particular issue, what we also need to clarify is which of the above are supported for import. We can't have in our docs (and singularity --help) that a format is supported that isn't /. no longer is, yo! :P

**Comment by vsoch** [comment]
...yo https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Yoyo.gif/200px-Yoyo.gif

**Comment by gmkurtzer** [comment]
Well, the format is supported for all of the action commands, but import specifically takes a strict format to convert it to the container image format (e.g. it also can't take a directory or a cpio in that it only supports tar).

**Comment by vsoch** [comment]
ok, let's just double check the import docs then provided via the singularity --help.

**Comment by GodloveD** [comment]
Right now it only lists docker as a supported URI.  shub should work too right?

**Comment by vsoch** [comment]
Not for import I don't think - @gmkurtzer that is correct? We currently don't have support to import an image into another image. That sounds messy.

**Comment by gmkurtzer** [comment]
Nope, we don't have to support import'ing an image into an image. It is messy, but it can be done pretty easily by exporting and then importing.

**Comment by vsoch** [comment]
okay, I think we are good then. Thanks everyone!
