### ISSUE TITLE
shell command not working with .tar.gz

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#683]
According to `singularity help shell` a user should be able to shell into a `.tar.gz` archive.  But this doesn't seem to be working (using an example image from [`docker://godlovedc/lolcow`](https://hub.docker.com/r/godlovedc/lolcow/)).
```
$ tar czvf lolcow.img.tar.gz lolcow.img
lolcow.img

$ singularity shell lolcow.img.tar.gz
Opening gzip compressed archive, stand by...
ERROR  : No valid /bin/sh in container
ABORT  : Retval = 255

$ singularity exec lolcow.img ls /bin/sh
/bin/sh
```

**Comment by vsoch** [comment]
I think this is because a `.img.tar.gz` != `.tar.gz` let me mess around with some things and see if I can make this work.

**Comment by vsoch** [comment]
Do you know if we are still using image_handler.sh?

**Comment by vsoch** [comment]
my inclination was to edit there, but I don't see any evidence that file is actually being called... so I'll just leave this for @gmkurtzer to fix up.

**Comment by gmkurtzer** [comment]
We could be more specific about the format of tar.gz that would be expected in the help file... Is this clearer:

```
    *.tar*              Tar archives are exploded to a temporary directory and
                        run within that directory (and cleaned up after). The
                        contents of the archive is a root file system with root
                        being in the current directory. Compression suffixes as 
                        '.gz' and '.bz2' are supported.
```

**Comment by vsoch** [comment]
Are we going to support .img.tar.gz too?

**Comment by gmkurtzer** [comment]
I don't have a plan to. an archive of a single file and then compression of that image seems a bit like overkill. ;)

**Comment by vsoch** [comment]
okay, then the above is perfecto. The example @GodloveD gave shouldn't work. And I added functions in singularity python to do this, so with that next release we can direct users to that.

**Comment by GodloveD** [comment]
Thanks for the clarification.  Closing.
