### ISSUE TITLE
singularity exec -e seems broken

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#684]
According to `singularity help exec` the `-e` option should clean the environment.  It seems to work with the `shell` command:
```
$ export BASE='This is Rogue II'

$ singularity shell -e lolcow.img
Singularity: Invoking an interactive shell within container...

Singularity lolcow.img:~> echo $BASE

Singularity lolcow.img:~>
```
Perfect.  But when I try the same thing with the `exec` command:
```
$ singularity exec -e lolcow.img echo $BASE
This is Rogue II
```

**Comment by dexter2cz** [comment]
@GodloveD Your variable is expanded before singularity exec is executed, so you are actually calling:
`singularity exec -e lolcow.img echo This is Rogue II`

Try this:
```
$ export BASE="A cow says moo moo"
$ singularity exec deb.img bash -c "echo $BASE"
A cow says moo moo

$ singularity exec deb.img bash -c "echo \$BASE"
A cow says moo moo

$ singularity exec -e deb.img bash -c "echo \$BASE"

```

**Comment by vsoch** [comment]
oh my gosh, the cow didn't say anything at all!! :scream:

**Comment by GodloveD** [comment]
Of course!  How silly of me.  Thanks for setting me straight.  Closing.

**Comment by gmkurtzer** [comment]
Haha, I am literally LOL'ing right now. Seriously, outloud. People are going to think I'm weird.

Thanks everyone!
