### ISSUE TITLE
add --nv to exec and --run documentation

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#686]
The output of `help singularity shell` contains this helpful line:
```
 -n/--nv             Enable experimental Nvidia support
```
The same option works with `exec` and `run` so this line should appear in `singularity help exec` and `singularity help run` as well.

**Comment by vsoch** [comment]
are you using the most up to date development? I already see the above in the help for those!

**Comment by GodloveD** [comment]
I must have been out of date.  Thanks!  closing!
