### ISSUE TITLE
Overlay error with SUSE

### ISSUE THREAD

**Issue by crbaird** [apptainer/singularity#687]
Hi - 
   I'm having a bit of trouble running dev-branch containers under SLES. Bootstrap completes without issue, but exec'ing fails with "Could not mount Singularity overlay: No such device". Turning off overlay works just fine. I would like to submit a pull request to enable bootstrapping with zypper for both SLE and openSUSE, but I don't want to step on PR #475 's toes. Debug output follows, and any help would be appreciated.

Thanks,
Reese

`sms007:/home/ohpc-test/tests/runtimes/singularity # singularity -d exec /tmp/${DISTRO}.img 'echo 2+2 |bc'
Enabling debugging
Ending argument loop
Singularity version: 2.2.99-dist
Exec'ing: /usr/lib/singularity/cli/exec.exec
Evaluating args: '/tmp/opensuse.img echo 2+2 |bc'
VERBOSE [U=0,P=22985]      message_init()                            Set messagelevel to: 5
VERBOSE [U=0,P=22985]      singularity_config_parse()                Initialize configuration file: /etc/singularity/singularity.conf
DEBUG   [U=0,P=22985]      singularity_config_parse()                Starting parse of configuration file /etc/singularity/singularity.conf
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key allow setuid = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key max loop devices = '256'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key allow pid ns = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key config passwd = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key config group = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key config resolv_conf = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key mount proc = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key mount sys = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key mount dev = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key mount home = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key mount tmp = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key mount hostfs = 'no'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key bind path = '/etc/hosts'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key user bind control = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key enable overlay = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key mount slave = 'yes'
VERBOSE [U=0,P=22985]      singularity_config_parse()                Got config key sessiondir max size = '16'
DEBUG   [U=0,P=22985]      singularity_config_parse()                Finished parsing configuration file '/etc/singularity/singularity.conf'
VERBOSE [U=0,P=22985]      singularity_registry_init()               Initializing Singularity Registry
VERBOSE [U=0,P=22985]      singularity_registry_set()                Adding value to registry: 'LIBEXECDIR' = '/usr/lib'
DEBUG   [U=0,P=22985]      singularity_registry_set()                Returning singularity_registry_set(libexecdir, /usr/lib) = 0
VERBOSE [U=0,P=22985]      singularity_registry_set()                Adding value to registry: 'COMMAND' = 'exec'
DEBUG   [U=0,P=22985]      singularity_registry_set()                Returning singularity_registry_set(COMMAND, exec) = 0
VERBOSE [U=0,P=22985]      singularity_registry_set()                Adding value to registry: 'MESSAGELEVEL' = '5'
DEBUG   [U=0,P=22985]      singularity_registry_set()                Returning singularity_registry_set(MESSAGELEVEL, 5) = 0
VERBOSE [U=0,P=22985]      singularity_registry_set()                Adding value to registry: 'VERSION' = '2.2.99-dist'
DEBUG   [U=0,P=22985]      singularity_registry_set()                Returning singularity_registry_set(version, 2.2.99-dist) = 0
VERBOSE [U=0,P=22985]      singularity_registry_set()                Adding value to registry: 'LOCALSTATEDIR' = '/var'
DEBUG   [U=0,P=22985]      singularity_registry_set()                Returning singularity_registry_set(localstatedir, /var) = 0
VERBOSE [U=0,P=22985]      singularity_registry_set()                Adding value to registry: 'SYSCONFDIR' = '/etc'
DEBUG   [U=0,P=22985]      singularity_registry_set()                Returning singularity_registry_set(sysconfdir, /etc) = 0
VERBOSE [U=0,P=22985]      singularity_registry_set()                Adding value to registry: 'BINDIR' = '/usr/bin'
DEBUG   [U=0,P=22985]      singularity_registry_set()                Returning singularity_registry_set(bindir, /usr/bin) = 0
VERBOSE [U=0,P=22985]      singularity_registry_set()                Adding value to registry: 'IMAGE' = '/tmp/opensuse.img'
DEBUG   [U=0,P=22985]      singularity_registry_set()                Returning singularity_registry_set(IMAGE, /tmp/opensuse.img) = 0
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'HOME'
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'TARGET_UID'
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'TARGET_GID'
DEBUG   [U=0,P=22985]      singularity_priv_init()                   Initializing user info
DEBUG   [U=0,P=22985]      singularity_priv_init()                   Set the calling user's username to: root
DEBUG   [U=0,P=22985]      singularity_priv_init()                   Marking uinfo structure as ready
DEBUG   [U=0,P=22985]      singularity_priv_init()                   Obtaining home directory
VERBOSE [U=0,P=22985]      singularity_priv_init()                   Set home (via getpwuid()) to: /root
VERBOSE [U=0,P=22985]      singularity_suid_init()                   Running SUID program workflow
VERBOSE [U=0,P=22985]      singularity_suid_init()                   Checking program has appropriate permissions
VERBOSE [U=0,P=22985]      singularity_suid_init()                   Checking configuration file is properly owned by root
VERBOSE [U=0,P=22985]      singularity_suid_init()                   Checking if singularity.conf allows us to run as suid
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(allow setuid, yes)
DEBUG   [U=0,P=22985]      singularity_config_get_value_impl()       Returning configuration value allow setuid='yes'
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Return singularity_config_get_bool(allow setuid, yes) = 1
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'NOSUID'
VERBOSE [U=0,P=22985]      singularity_priv_userns()                 Invoking the user namespace
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(allow user ns, yes)
DEBUG   [U=0,P=22985]      singularity_config_get_value_impl()       No configuration entry found for 'allow user ns'; returning default value 'yes'
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Return singularity_config_get_bool(allow user ns, yes) = 1
VERBOSE [U=0,P=22985]      singularity_priv_userns()                 Not virtualizing USER namespace: running as root
DEBUG   [U=0,P=22985]      singularity_priv_userns()                 Returning singularity_priv_init(void)
DEBUG   [U=0,P=22985]      singularity_priv_drop()                   Running as root, not changing privileges
DEBUG   [U=0,P=22985]      singularity_runtime_ns()                  Calling: _singularity_runtime_ns_pid()
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(allow pid ns, yes)
DEBUG   [U=0,P=22985]      singularity_config_get_value_impl()       Returning configuration value allow pid ns='yes'
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Return singularity_config_get_bool(allow pid ns, yes) = 1
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'UNSHARE_PID'
VERBOSE [U=0,P=22985]      singularity_runtime_ns_pid()              Not virtualizing PID namespace on user request
DEBUG   [U=0,P=22985]      singularity_runtime_ns()                  Calling: _singularity_runtime_ns_ipc()
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(allow ipc ns, yes)
DEBUG   [U=0,P=22985]      singularity_config_get_value_impl()       No configuration entry found for 'allow ipc ns'; returning default value 'yes'
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Return singularity_config_get_bool(allow ipc ns, yes) = 1
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'UNSHARE_IPC'
VERBOSE [U=0,P=22985]      singularity_runtime_ns_ipc()              Not virtualizing IPC namespace on user request
DEBUG   [U=0,P=22985]      singularity_runtime_ns()                  Calling: _singularity_runtime_ns_mnt()
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(mount slave, yes)
DEBUG   [U=0,P=22985]      singularity_config_get_value_impl()       Returning configuration value mount slave='yes'
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Return singularity_config_get_bool(mount slave, yes) = 1
DEBUG   [U=0,P=22985]      singularity_priv_escalate()               Running as root, not changing privileges
DEBUG   [U=0,P=22985]      singularity_runtime_ns_mnt()              Virtualizing FS namespace
DEBUG   [U=0,P=22985]      singularity_runtime_ns_mnt()              Virtualizing mount namespace
DEBUG   [U=0,P=22985]      singularity_runtime_ns_mnt()              Making mounts slave
DEBUG   [U=0,P=22985]      singularity_priv_drop()                   Running as root, not changing privileges
DEBUG   [U=0,P=22985]      singularity_sessiondir()                  Setting sessiondir
VERBOSE [U=0,P=22985]      singularity_sessiondir()                  Using session directory: /var/singularity/mnt/session
DEBUG   [U=0,P=22985]      singularity_sessiondir()                  Checking for session directory: /var/singularity/mnt/session
DEBUG   [U=0,P=22985]      singularity_sessiondir()                  Obtaining the default sessiondir size
DEBUG   [U=0,P=22985]      singularity_config_get_value_impl()       Returning configuration value sessiondir max size='16'
DEBUG   [U=0,P=22985]      singularity_sessiondir()                  Converted sessiondir size to: 16
DEBUG   [U=0,P=22985]      singularity_sessiondir()                  Creating the sessiondir size mount option length
DEBUG   [U=0,P=22985]      singularity_sessiondir()                  Got size length of: 9
DEBUG   [U=0,P=22985]      singularity_sessiondir()                  Creating the sessiondir size mount option string
DEBUG   [U=0,P=22985]      singularity_sessiondir()                  Checking to make sure the string was allocated correctly
DEBUG   [U=0,P=22985]      singularity_priv_escalate()               Running as root, not changing privileges
DEBUG   [U=0,P=22985]      singularity_sessiondir()                  Mounting sessiondir tmpfs: /var/singularity/mnt/session
DEBUG   [U=0,P=22985]      singularity_priv_drop()                   Running as root, not changing privileges
VERBOSE [U=0,P=22985]      singularity_registry_set()                Adding value to registry: 'SESSIONDIR' = '/var/singularity/mnt/session'
DEBUG   [U=0,P=22985]      singularity_registry_set()                Returning singularity_registry_set(SESSIONDIR, /var/singularity/mnt/session) = 0
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'CLEANUPDIR'
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'NOSESSIONCLEANUP'
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'NOCLEANUP'
DEBUG   [U=0,P=22985]      singularity_cleanupd()                    Not running a cleanup thread, no 'SINGULARITY_CLEANUPDIR' defined
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning value from registry: 'IMAGE' = '/tmp/opensuse.img'
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'WRITABLE'
DEBUG   [U=0,P=22985]      singularity_config_get_value_impl()       No configuration entry found for 'limit container owners'; returning default value 'NULL'
DEBUG   [U=0,P=22985]      singularity_config_get_value_impl()       No configuration entry found for 'limit container paths'; returning default value 'NULL'
DEBUG   [U=0,P=22985]      singularity_image_open()                  Opening file descriptor to image: /tmp/opensuse.img
VERBOSE [U=0,P=22985]      singularity_image_check()                 Checking that file pointer is a Singularity image
DEBUG   [U=0,P=22985]      singularity_image_check()                 First line of image(fd=4): #!/usr/bin/env run-singularity

DEBUG   [U=0,P=22985]      singularity_image_check()                 Checking if first line matches key
VERBOSE [U=0,P=22985]      singularity_image_check()                 File is a valid Singularity image
DEBUG   [U=0,P=22985]      singularity_config_get_value_impl()       Returning configuration value max loop devices='256'
DEBUG   [U=0,P=22985]      singularity_image_bind()                  Entered singularity_image_bind()
DEBUG   [U=0,P=22985]      singularity_image_bind()                  Converting max_loop_devs_string to int: '256'
DEBUG   [U=0,P=22985]      singularity_image_bind()                  Converted max_loop_devs_string to int: '256' -> 256
DEBUG   [U=0,P=22985]      singularity_image_bind()                  Checking if this image has been properly opened
DEBUG   [U=0,P=22985]      singularity_image_bind()                  Checking if image is valid file
DEBUG   [U=0,P=22985]      singularity_image_bind()                  Checking if image is already bound to a loop device
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'WRITABLE'
DEBUG   [U=0,P=22985]      singularity_image_bind()                  Setting loopdev open to: O_RDONLY
DEBUG   [U=0,P=22985]      singularity_image_bind()                  Setting LO_FLAGS_AUTOCLEAR
DEBUG   [U=0,P=22985]      singularity_image_bind()                  Calculating image offset
VERBOSE [U=0,P=22985]      singularity_image_check()                 Checking that file pointer is a Singularity image
DEBUG   [U=0,P=22985]      singularity_image_check()                 First line of image(fd=4): #!/usr/bin/env run-singularity

DEBUG   [U=0,P=22985]      singularity_image_check()                 Checking if first line matches key
VERBOSE [U=0,P=22985]      singularity_image_check()                 File is a valid Singularity image
VERBOSE [U=0,P=22985]      singularity_image_offset()                Calculating image offset
VERBOSE [U=0,P=22985]      singularity_image_offset()                Found image at an offset of 31 bytes
DEBUG   [U=0,P=22985]      singularity_image_offset()                Returning image_offset(image_fp) = 31
DEBUG   [U=0,P=22985]      singularity_priv_escalate()               Running as root, not changing privileges
DEBUG   [U=0,P=22985]      singularity_image_bind()                  Finding next available loop device...
VERBOSE [U=0,P=22985]      singularity_image_bind()                  Found available loop device: /dev/loop0
DEBUG   [U=0,P=22985]      singularity_image_bind()                  Setting loop device flags
DEBUG   [U=0,P=22985]      singularity_priv_drop()                   Running as root, not changing privileges
VERBOSE [U=0,P=22985]      singularity_image_bind()                  Using loop device: /dev/loop0
VERBOSE [U=0,P=22985]      singularity_runtime_rootfs()              Set container directory to: /var/singularity/mnt/container
DEBUG   [U=0,P=22985]      singularity_runtime_rootfs()              Checking for container directory
DEBUG   [U=0,P=22985]      singularity_runtime_rootfs()              Returning container_directory: /var/singularity/mnt/container
DEBUG   [U=0,P=22985]      chk_mode()                                Checking exact mode (40755) on: /var/singularity/mnt/container
DEBUG   [U=0,P=22985]      chk_mode()                                Found appropriate mode on file: /var/singularity/mnt/container
VERBOSE [U=0,P=22985]      singularity_image_mount()                 Checking what kind of image we are mounting
DEBUG   [U=0,P=22985]      singularity_image_mount_squashfs_check()  Image does not appear to be of type '.sqsh': /tmp/opensuse.img
DEBUG   [U=0,P=22985]      singularity_image_mount_dir_check()       Checking if image is a directory
VERBOSE [U=0,P=22985]      singularity_image_mount_dir_check()       Source path is not a directory: /tmp/opensuse.img
VERBOSE [U=0,P=22985]      singularity_image_mount()                 Attempting to mount as singularity image
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'WRITABLE'
DEBUG   [U=0,P=22985]      singularity_priv_escalate()               Running as root, not changing privileges
VERBOSE [U=0,P=22985]      singularity_image_mount_image_mount()     Mounting /dev/loop0 in read/only to: /var/singularity/mnt/container
DEBUG   [U=0,P=22985]      singularity_priv_drop()                   Running as root, not changing privileges
DEBUG   [U=0,P=22985]      singularity_runtime_rootfs()              Returning container_directory: /var/singularity/mnt/container
DEBUG   [U=0,P=22985]      action_ready()                            Checking if container is valid at: /var/singularity/mnt/container
DEBUG   [U=0,P=22985]      singularity_runtime_rootfs()              Returning container_directory: /var/singularity/mnt/container
DEBUG   [U=0,P=22985]      singularity_runtime_overlayfs()           Checking if overlayfs should be used
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(enable overlay, yes)
DEBUG   [U=0,P=22985]      singularity_config_get_value_impl()       Returning configuration value enable overlay='yes'
DEBUG   [U=0,P=22985]      singularity_config_get_bool_char_impl()   Return singularity_config_get_bool(enable overlay, yes) = 1
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'DISABLE_OVERLAYFS'
DEBUG   [U=0,P=22985]      singularity_registry_get()                Returning NULL on 'WRITABLE'
DEBUG   [U=0,P=22985]      singularity_runtime_overlayfs()           OverlayFS enabled by host build
DEBUG   [U=0,P=22985]      singularity_runtime_overlayfs()           Setting up overlay mount options
DEBUG   [U=0,P=22985]      singularity_runtime_overlayfs()           Checking for existance of overlay directory: /var/singularity/mnt/overlay
DEBUG   [U=0,P=22985]      singularity_priv_escalate()               Running as root, not changing privileges
DEBUG   [U=0,P=22985]      singularity_runtime_overlayfs()           Mounting overlay tmpfs: /var/singularity/mnt/overlay
DEBUG   [U=0,P=22985]      singularity_runtime_overlayfs()           Creating upper overlay directory: /var/singularity/mnt/overlay/upper
DEBUG   [U=0,P=22985]      s_mkpath()                                Creating directory: /var/singularity/mnt/overlay/upper
DEBUG   [U=0,P=22985]      singularity_runtime_overlayfs()           Creating overlay work directory: /var/singularity/mnt/overlay/work
DEBUG   [U=0,P=22985]      s_mkpath()                                Creating directory: /var/singularity/mnt/overlay/work
DEBUG   [U=0,P=22985]      singularity_runtime_overlayfs()           Creating overlay_final directory: /var/singularity/mnt/overlay/final
DEBUG   [U=0,P=22985]      s_mkpath()                                Creating directory: /var/singularity/mnt/overlay/final
VERBOSE [U=0,P=22985]      singularity_runtime_overlayfs()           Mounting overlay with options: lowerdir=/var/singularity/mnt/container,upperdir=/var/singularity/mnt/overlay/upper,workdir=/var/singularity/mnt/overlay/work
ERROR   [U=0,P=22985]      singularity_runtime_overlayfs()           Could not mount Singularity overlay: No such device
ABORT   [U=0,P=22985]      singularity_runtime_overlayfs()           Retval = 255`

**Comment by vsoch** [comment]
hey @crbaird! I'm not familiar with zypper or why the overlayfs might be causing an issue, but it looks like https://github.com/singularityware/singularity/pull/475 is from January, so I think it would be great if you can contribute to add support for openSUSE and SLE - maybe we can bring @FlyElephant-M31 into discussion and you guys can collaborate for the feature?

**Comment by crbaird** [comment]
Thanks @vsoch. Zypper is SUSE's yum. I've submitted PR #688  for your consideration. Please let me know how I can help further.

**Comment by gmkurtzer** [comment]
Yeah, this just doesn't seem to be supported in SLES. I spoke with @craiggardner and he mentioned this is due to security precaution by SuSE. We are still working through this, and we might come with a better solution, but, this won't be an immediate fix. For the time being, overlayfs is an unsupported feature on SLES.

**Comment by craiggardner** [comment]
@cbaird, I'm certainly not a kernel expert, and I've only been looking into this issue superficially so far.  But as long as you're using SLES12 (any of the releases, from SP0 to SP2), you're using kernel 4.4 that should allow for the overlayfs.  But SLES provides overlayfs as a kernel module.  Possibly the simple solution to this particular problem is to load the kmodule.  I'll lurk some more, see if I can give you more info.  In the mean time, would you please let me know which SLES or openSUSE release you're using?

**Comment by crbaird** [comment]
Thanks for looking, @craiggardner. We're building Leap 42.2 containers under SLE SP2 hosts. The issue seems to be related to the fact that our hosts are themselves running stateless warewulf images. Adding overlay to warewulf's bootstrap.conf seems to be getting us further. So we may be able to blame @gmkurtzer after all.

**Comment by gmkurtzer** [comment]
Haha, nice try @crbaird, but those are just the defaults and are configurables! lol

Glad it sounds like it is working out! WAHOO!

**Comment by dtrudg** [comment]
Closing this as believe it's been resolved with host config. Let us know if remaining issues on current Singularity. Thanks!
