### ISSUE TITLE
convert img to tar.gz archive

### ISSUE THREAD

**Issue by huitre39** [apptainer/singularity#698]
Hello, last week i view that i can use singularity with tar.gz who contains root file system.
My question is, can i convert img disk image to tar.gz archive ?

**Comment by gmkurtzer** [comment]
Yes, you can use tar.gz files that contain a root file system, but it is not very efficient as it must be splat out to the file system before it can be used. But to answer your question, yes, you can convert a disk image to a tarball by using a command like:

```
$ singularity export container.img > container.tar
```
