### ISSUE TITLE
issue with having .sapp-cache in home directory in NFS context

### ISSUE THREAD

**Issue by paciorek** [apptainer/singularity#7]
Just a note in case this hadn't come up as something you might address at some point. 

I'm trying singularity on an Ubuntu 14.04 machine on which my home directory is NFS-mounted. I'm getting this error:
paciorek@smeagol:/tmp> ./echo.sapp 
ERROR: Could not bind mount /accounts/gen/vis/paciorek/.sapp-cache/./echo/c/dev

Channeling a conversation about this with Ryan Lovett - it seems that the issue is that root can't do the bind mount because it can access a user's home directory on an NFS client.

**Comment by gmkurtzer** [comment]
Very interesting case I didn't think of! Of course, I would have hit this shortly as we implement it on our HPC resources, but let me brainstorm on this.

Do you know if it is possible to mount proc on top of an NFS mount?

Thanks!

**Comment by truatpasteurdotfr** [comment]
my NFS v3 might be less restrictive: works for me (CentOS-6 x86_64 client)

**Comment by paciorek** [comment]
Ryan Lovett here in Stats said:
It is possible to mount proc onto a directory on an NFS volume if the mounting user has permission on the directory. For example I made /var/nitedump/proc and mounted proc from one of our NFS client machines onto it, but couldn't do the same for ~arbitrary_user/proc.

**Comment by gmkurtzer** [comment]
Hi Chris,

Something that Ryan said made me curious: ".. if the mounting user has permission on the directory ..". Are you mounting/exporting your home directories with squash-root enabled? If so, this may have an issue with Singularity as it has some privilege escalation bits to implement the physical containerization, the bind mount to dev and full mount of proc.

BTW, tell Ryan I said hi. LOL

Thanks!

**Comment by ryanlovett** [comment]
Bypassing the ChrisMQ... :)

Yes, we've got squash root. Would it be possible to use a local cache dir instead, e.g. /var/cache/sapp/$USER ? With /var/cache/sapp 0711 and /var/cache/sapp/$USER as whatever you need.

Actually, a run-time dir would be more appropriate since cache dirs are supposedly disposable. So /var/run/user/$USER/sapp/ or maybe XDG_RUNTIME_DIR.

**Comment by gmkurtzer** [comment]
Hi Ryan,

Yes I can make the sapp-cache directory configurable, but it is beneficial to have it in the user's home directory such that it can be used across nodes. For example, with the latest version (as of like an hour or so ago), if you execute a SAPP file directly, it will invoke a different code pathway which will cause Singularity to use a temporary dir (in /tmp) for the container environment. It would be fairly easy to make that configurable.

I am wondering if root squash is what the root cause of the NFS problem. Do you have other mount options? What is your take?

Thanks!

**Comment by ryanlovett** [comment]
root squash is definitely the cause of this problem. I don't want to disable it unless there is some other way of limiting client root access to user data. We're on NFSv3.

So some of the sapp cache data is relevant to the user on any node and some (whatever is getting bind mounted) is only relevant to the user on a specific node? If so can it be separated into home and machine specific locations (is that what your recent changes have done)? Or does each node need access to the other's data?

**Comment by gmkurtzer** [comment]
I just committed a solution to allow someone to custom configure their cache directory using the environment variable SINGULARITY_CACHEDIR. While this will work around the problem, as you eluded to it creates another if someone wishes to run parallel apps or run their apps on a different node within a shared home directory context.

Also, I added another bit of logic to do an additional stat() as root to see if the file system is still accessible, and if not dump a more appropriate error message.

I think the ticket can be closed now, but I'd like to see if the above two changes work for @paciorek.

On a side note, while root_squash may make it slightly more difficult for an attacker to traverse an NFS file system, it surely doesn't make it secure. Root could always create any number of users with matching UID's as that already on the file system and still get to any data they wish.

**Comment by paciorek** [comment]
Here's what I am getting now. Some success some failure...

First, my complete install workflow:
git clone -b master --single-branch
https://github.com/gmkurtzer/singularity.git
cd singularity
export SINGULARITY_CACHEDIR=/tmp/paciorek
sh ./autogen.sh
./configure --prefix=/usr/local
make
sudo make install
sudo make install-perms

# now test it:

$ cd /tmp
$ singularity build echo.sspec
$ ./echo.sapp blah
mktemp: failed to create directory via template
‘/tmp/paciorek/tmp/.sapprun-3189.XXXXXXXXX’: No such file or directory
SAPPDIR not given

$ singularity install /tmp/echo.sapp
Installing: /tmp/echo.sapp
$ singularity run echo blah
ERROR: 'echo' is not installed
$ singularity list
/usr/local/libexec/singularity/list.exec: 35: shift: can't shift that many

$ singularity install echo.sapp
Installing: echo.sapp
$ singularity run echo blah
blah
$ singularity list
/usr/local/libexec/singularity/list.exec: 35: shift: can't shift that many

**Comment by ryanlovett** [comment]
> On a side note, while root_squash may make it slightly more difficult for an attacker to traverse an NFS file system, it surely doesn't make it secure. Root could always create any number of users with matching UID's as that already on the file system and still get to any data they wish.

Yes, or just su. So _just_ slightly more difficult. root_squash is more effective in preventing sysadmins from making mistakes. A kerberized environment wouldn't allow this sort of thing, but then I think it'd get in your way too. (though I've no experience with krb+nfsv4)

**Comment by gmkurtzer** [comment]
@paciorek I made some changes that I think will fix this, but I haven't finished testing (because @bernardl is coercing me to goto our group holiday lunch). If you want to test,.. go for it, I think it will work now. With that said, I will test more when I return.

**Comment by gmkurtzer** [comment]
I cleaned a lot of stuff up, no doubt I created more bugs as I was solving them... But in any case, the latest commit will hopefully do good things.

**Comment by paciorek** [comment]
Things look good for me now. The following all worked:

paciorek@xxxxx:/tmp> ./echo.sapp blah
blah
paciorek@xxxxx:/tmp> singularity install /tmp/echo.sapp
Installing: /tmp/echo.sapp
paciorek@xxxxx:/tmp> singularity run echo blah
blah
paciorek@xxxxx:/tmp> singularity list
CONTAINER NAME         SIZE (k) SUMMARY
echo                       2568
paciorek@xxxxx:/tmp> singularity delete echo
Deleted container cache: echo
Removing previous SAPP container cache
paciorek@xxxxx:/tmp> singularity install echo.sapp
Installing: echo.sapp
paciorek@xxxxx:/tmp> singularity run echo blah
blah

**Comment by gmkurtzer** [comment]
Excellent, thanks Chris! I am going to close this issue, but feel free to reopen if it comes up again.

Thanks!
