### ISSUE TITLE
Old version on debian package

### ISSUE THREAD

**Issue by BaronPampa** [apptainer/singularity#702]
## Version of Singularity:

2.3

### Expected behavior

deb package with name: singularity-container_2.3_amd64.deb

### Actual behavior

singularity-container_2.2-1_amd64.deb

### Steps to reproduce behavior

$>tar xfv singularity-2.3.tar.gz
$> cd singularity-2.3/
$> fakeroot dpkg-buildpackage -b -us -uc

**Comment by vsoch** [comment]
This is largely my fault for having 2.3 represented in the docs - I took the assumption / hope that someone would update the package and then it would be correct :) I think with a PR for the debian distribution this will be fixed?

**Comment by yarikoptic** [comment]
well -- I am maintaining debian packaging "outside" of this repo... 
http://git.debian.org/?p=collab-maint/singularity-container.git  is the repo... and 2.3-1 is about to come out (yet to resolve few leftovers ;) )

**Comment by dtrudg** [comment]
Closing this as it's related to the 2.3 series - we are now on 2.4.x
