### ISSUE TITLE
Error if container directory is setgid

### ISSUE THREAD

**Issue by kcgthb** [apptainer/singularity#707]
## Description 
When Singularity is installed in a SETGID directory, permissions check fail in `singularity_image_mount()` and attempt to fix the permission fail too. 

## Version of Singularity:

2.3

### Expected behavior

No error :)

### Actual behavior

`Bad permission mode (should be 0755) on: <install_dir>/var/singularity/mnt/container`

### Steps to reproduce behavior

Install Singularity in a SETGID directory:
```
$ chmod g+s /share/singularity
$ configure --prefix=/share/singularity
$ sudo make install
$ stat -c "%a %n" /share/singularityvar/singularity/mnt/container
2755 /share/singularity/var/singularity/mnt/container
```
Run:
```
$ singularity --debug shell container.img
[...]
VERBOSE [U=215845,P=76501] singularity_runtime_rootfs()              Set container directory to: /share/singularity/var/singularity/mnt/container
DEBUG   [U=215845,P=76501] singularity_runtime_rootfs()              Checking for container directory
DEBUG   [U=215845,P=76501] singularity_runtime_rootfs()              Returning container_directory: /share/singularity/var/singularity/mnt/container
DEBUG   [U=215845,P=76501] chk_mode()                                Checking exact mode (40755) on: /share/singularity/var/singularity/mnt/container
VERBOSE [U=215845,P=76501] chk_mode()                                Found wrong permission on file /share/singularity/var/singularity/mnt/container: 40755 != 42755
DEBUG   [U=215845,P=76501] singularity_image_mount()                 fixing bad permissions on /share/singularity/var/singularity/mnt/container
DEBUG   [U=215845,P=76501] singularity_priv_escalate()               Temporarily escalating privileges (U=215845)
DEBUG   [U=0,P=76501]      singularity_priv_escalate()               Clearing supplementary GIDs.
DEBUG   [U=0,P=76501]      singularity_priv_drop()                   Dropping privileges to UID=215845, GID=32264 (11 supplementary GIDs)
DEBUG   [U=0,P=76501]      singularity_priv_drop()                   Restoring supplementary groups
DEBUG   [U=215845,P=76501] singularity_priv_drop()                   Confirming we have correct UID/GID
ERROR   [U=215845,P=76501] singularity_image_mount()                 Bad permission mode (should be 0755) on: /share/singularity/var/singularity/mnt/container
ABORT   [U=215845,P=76501] singularity_image_mount()                 Retval = 255
```
`chk_mode()` returns an error because of the SETGID bit. I'm not sure what's required here, security-wise. Is it necessary that this directory has the SETUID and SETGID bits not set? Or could the permissions check be relaxed to ignore those bits? 

If it's important that they are not set, then the mechanism to fix the permissions in `singularity_image_mount()` should be improved. Currently, it does a [`chmod 0755`](https://github.com/singularityware/singularity/blob/master/src/lib/image/mount/mount.c#L61) on the directory, which will *not* clear the SETUID/SETGID bits.

From `man 1 chmod`:
> SETUID AND SETGID BITS
[...]
       you can set (but not clear) the bits with a numeric mode

It looks like if they actually need to be cleared, the SETUID/SETGID bits need to be explicitely unset.

## Summary

Do SETUID/SETGID need to be absent from the container directory (`var/singularity/mnt/container`)?
1. if not, the `chk_mode()` check could be less strict and ignore them,
2. if so, they should probably be explicitly unset in `singularity_image_mount()` or possibly even better in the `install` target of the Makefile (the directory is created with `install -d -m 0755`, which also does *not* unset SETUID/SETGID bits).

**Comment by gmkurtzer** [comment]
I am thinking that a reasonable behavior would be just to check if the permissions are at least 755, such that 2755 would still be allowed. Do you concur?

**Comment by kcgthb** [comment]
Fine by me. If there's no specific reason to make sure that this directory is *not* SETUID/SETGID, then yes, checking for 755 should be sufficient.

**Comment by bauerm97** [comment]
Closing since #723 fixes this.
