### ISSUE TITLE
building erlang fails

### ISSUE THREAD

**Issue by ityonemo** [apptainer/singularity#710]
## Version of Singularity:

2.2.99 (development branch)

### Expected behavior

Erlang should build.  Works fine if you comment out the make command and execute make when in shell --writable

### Actual behavior

There seems to be a failure where it fails to identify the build directory, makefile errors out, and terminates the build process.

### Steps to reproduce behavior

def file:
https://gist.github.com/ityonemo/2b50d3297e499f16ef5e9cdfd7e75386

cd /var/buildzone/otp
make 

Builds correctly.

uncomment the make command, and it fails.

**Comment by vsoch** [comment]
hey @ityonemo do you get this error with the current master (which is now the old development?) I notice in your gist that there is a reference to do something with a /LICENSE, but do you put that file there? You would need a %files section with something like

```
%files
/path/on/host/LICENSE /LICENSE
```
but it looks like you are removing it, so maybe you do not :) 

I would guess mot of your issues revolve around not putting files in the image that you think are there - could you 

 - test this with files correctly added,
 - use the current master
 - include the entire build spec in the gist?

Thanks!

**Comment by vsoch** [comment]
Also note that files are copied after %post, so if you want to add them before %post you need to do that in %setup, eg:

```
%setup 
cp /path/on/host/LICENSE $SINGULARITY_ROOTFS/LICENSE
```
This uses the copy (cp) command, so the same wild cards / `man cp` rules apply.

**Comment by ityonemo** [comment]
the license statement is a holdover from the .def file I cloned to make this, I am not sure that it will make a difference, but I will try to do the same without the license section.

**Comment by ityonemo** [comment]
switching to the current master makes it work!  Thanks.  I didn't notice the change in master
