### ISSUE TITLE
singularity mpi multinode error

### ISSUE THREAD

**Issue by huitre39** [apptainer/singularity#713]
## Version of Singularity:

2.2.1

### Expected behavior

Run my program without error

### Actual behavior

Host of my machine is not found, if i run mpirun in singularity image. Without it's work

### Steps to reproduce behavior

mpirun -np 20 -v singularity exec --writable /root/singularity/myimage.img /root/app/myprogram

Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(805)...................: fail failed
MPID_Init(1831).........................: channel initialization failed
MPIDI_CH3_Init(147).....................: fail failed
MPID_nem_tcp_post_init(645).............: fail failed
MPID_nem_tcp_connect(1122)..............: fail failed
MPID_nem_tcp_get_addr_port_from_bc(1346): Missing ifname or invalid host/port description in business card

if i run mpirun (or mpiexec) in my contenair i have this error, without singularity :
mpirun -np 20 -v /root/app/myprogram

it's work perfectly in my cluster.

**Comment by vsoch** [comment]
hey @huitre39 are you able to try this with 2.3?

**Comment by kma** [comment]
Hi,

I guess this is mpich implementation of MPI. I think singularity supports only OpenMPI 2.1.x version.

**Comment by gmkurtzer** [comment]
Hi,

@kma, Singularity should support MPICH and the other MPIs just fine in hybrid mode as long as versions are compatible inside and outside the container. Actually OpenMPI ended up being the hardest to get working properly and is a bit temperamental.

@huitre39, can you check the `/etc/hosts` file from within the container and confirm that there is an appropriate entry for the IP addresses of the hosts in your multi-node job. By default this file should be shared from the host into the container.

Hope that helps!

Greg

**Comment by dtrudg** [comment]
Closing this as it was raised against Singularity 2.2 and there has been no further feedback. Please feel free to re-open if you are having problems with the latest version of Singularity. Thanks!
