### ISSUE TITLE
Singularity not preventing unmounts of mounted image directory

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#714]
## Version of Singularity:

2.3

### Expected behavior

If the image that singularity runs is a directory, I expect to not be able to unmount the filesystem that the directory is in while singularity is running (without some kind of forcing option)

### Actual behavior

Singularity does not hold any references to the filesystem, so the filesystem can be unmounted.  The only references are inside the container, and at least on el7.3 that is not enough to be noticed outside the container.  I had reported this earlier in pr #626, but when I tested the development branch at the time there was a file descriptor left open, but now in the singularity-2.3 release the behavior is back the way it was in singularity-2.2.1.

### Steps to reproduce behavior

On EL7.3, assuming an existing singularity image file I call 'centos7.img', make a loopback filesystem, mount it, and use it:
```
dd if=/dev/zero of=centos7.ext3 bs=1G count=1
sudo losetup /dev/loop0 centos7.ext3
sudo mkfs -t ext3 -m 1 -v /dev/loop0
sudo mkdir -p /mnt/loop0
sudo mount /dev/loop0 /mnt/loop0
singularity export centos7.img | (cd /mnt/loop0 && sudo tar xf -)
singularity exec --containall /mnt/loop0 bash
```
Then in another window while singularity is running, umount /mnt/loop0.

It can be worked around by first doing 'cd /mnt/loop0' before running singularity exec (or inside singularity), or by having singularity open a file descriptor to the image directory and leaving it open.

This example of course is for reproducing, but in reality we experience the problem with automounted cvmfs; the automounter doesn't realize the filesystem is still in use, and unmounts it.

**Comment by gmkurtzer** [comment]
Does omitting the `--containall` flag change the behavior?

**Comment by DrDaveD** [comment]
No, the behavior is the same without --containall.  Can you reproduce it?

**Comment by DrDaveD** [comment]
I see the same behavior on an EL6 host as well.

**Comment by gmkurtzer** [comment]
Singularity currently does open a file descriptor to the image directory:

```
DEBUG   [U=1000,P=25681]   singularity_image_open()                  Opening file descriptor to image: /mnt/loop0/
```
But I had added the FD_CLOEXEC option to that file descriptor. I just updated the development branch, will you retest?

Thanks!

**Comment by DrDaveD** [comment]
Yes, that did it.  Thanks!

Maybe it would be a good idea to put a comment in the code to say why FD_CLOEXEC is deliberately not being set, in case someone later again thinks that it should.

**Comment by DrDaveD** [comment]
Can this get into singularity-2.3.1?  I don't see it in the master branch that I just built.

**Comment by DrDaveD** [comment]
too late

**Comment by gmkurtzer** [comment]
Apologies, I am on email overload right now and missed this one.

I did however just add it to master, so it will be in either 2.3.2, or 2.4, whichever gets released first.

Thanks!

**Comment by DrDaveD** [comment]
ok, good to know

**Comment by jscook2345** [comment]
This looks to be resolved. @DrDaveD Please open a new issue or comment here if this is not the case. Thanks!

**Comment by DrDaveD** [comment]
I confirm the issue is fixed in singularity-3
