### ISSUE TITLE
AWESOME JOB!

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#718]
was about to whine a lot while by mistake trying to use apparently an outdated devel build... so many fixes got into 2.3 -- just great! thank you everyone, please close at your will

:+1: 
:+1: 
:+1: 
:+1: 
:+1:

**Comment by vsoch** [comment]
I think I want to leave this open just a little longer, to feel the warm sunshine from all those :+1: ! I'll add in some snacks:

:taco: :taco: :ice_cream: :ice_cream: :shallow_pan_of_food: :shallow_pan_of_food: :cookie: :cookie: :ramen: :ramen: :rice: :rice: :rice_ball: :rice_ball: :rice_cracker: :rice_cracker: :candy: :candy: :milk_glass: :milk_glass: :cake: :cake: :fish_cake: :fish_cake: :hamburger: :hamburger: :avocado: :avocado: :avocado: :avocado: :avocado: :avocado: :avocado:

**Comment by gmkurtzer** [comment]
WAHOOOO! Thanks @yarikoptic! BTW, apologies for forgetting (yet again) for forgetting to let you know about the upcoming release. But, at least I did annotate the tag! ;)

<baby steps> lol

**Comment by vsoch** [comment]
is this reminder something that we need to do for every release? If so I can possibly help with this :)

**Comment by gmkurtzer** [comment]
Yes. I think we should have a 'devel' or a 'prerelease' email list, where we give everyone the heads up and emphasis the coming release such that distribution packagers can all be notified and releases can be coordinated.

I really wish we had a great email list solution... :(

**Comment by vsoch** [comment]
They are out there, you just gotta pay for them! Or use the one that I found that is free... but I don't think you liked it. :/

**Comment by gmkurtzer** [comment]
Yeah, groups.io I think was also free, but that one didn't seem perfect either. Maybe I'm just so old school that I compare everything to the awesomeness that was Mailman. ;)

**Comment by yarikoptic** [comment]
just add a team "Maintainers" here, and then post a new issue prior to release addressing the team -- here would be your "mailing list" ;)

**Comment by yarikoptic** [comment]
we did something like that for fail2ban, further segmenting into OSes etc: https://github.com/orgs/fail2ban/teams , comes handy at times to address specific ppl

**Comment by vsoch** [comment]
oh that's a great idea!

**Comment by gmkurtzer** [comment]
Yep! Those are the only kind of ideas @yarikoptic has. ;)

**Comment by vsoch** [comment]
okay I added both of you, let me know who else (or just add them at willy nilly!)

...if only everything in the world were as awesome as Github :)

**Comment by yarikoptic** [comment]
@singularityware/singularity-maintainers  alarm alarm
That was a test ;-)

**Comment by vsoch** [comment]
As happy as this issue makes me, there is a time that everyone knows, when all of the issues must close, the time is now because it's Fall, and we will never get to them all!

**Comment by yarikoptic** [comment]
Fair enough! Although the "issue" is still outstanding ;-)

**Comment by GodloveD** [comment]
![87be47290fcc3fa02dc0d6fae882c5c96dff7ff1301e8bc81a4e3fb8d1c171fe](https://user-images.githubusercontent.com/7672924/31713715-29f57452-b3cd-11e7-9244-f6648d9a3768.jpg)
