### ISSUE TITLE
reduce img or convert img to gz archive ?

### ISSUE THREAD

**Issue by huitre39** [apptainer/singularity#728]
## Version of Singularity:

2.3

### Expected behavior

I want to reduce my disk or convert my disk to gz archive

### Steps to reproduce behavior

Hello i have problem, i want to reduce size of my disk, can i make it ?
or can i export my disk to rootfs image (gz archive) ?
i see that singularity can open the archives for example alpine linux : (Minimal root filesystem. For use in containers. and minimal chroots)
https://alpinelinux.org/downloads/
https://nl.alpinelinux.org/alpine/v3.6/releases/x86_64/alpine-minirootfs-3.6.1-x86_64.tar.gz

can i convert my img to gz archive ("root filesystem") ?

thank's for advance

**Comment by vsoch** [comment]
Hey @huitre39 try

```
gzip -c -9 container.img > container.img.gz
```
to compress your image, and to decompress

```
gzip -d -f container.img.gz
```
I think you will have to decompress before using.

**Comment by huitre39** [comment]
but i want use this compressed image (without decompress before)

**Comment by gmkurtzer** [comment]
@huitre39,

Maybe this is what you are looking to do:

```
$ singularity export container.img | gzip -c -9 > container.tar.gz
```
But you should know, that is not a great way to run containers because they always must be splat out to the local file system to run.

**Comment by vsoch** [comment]
hey @huitre39 - with singularity 2.4 you can build (by default) a squashfs image. It's a compressed file type, and is on par with gzip 9. Try this:

```
sudo singularity build ubuntu.simg docker://ubuntu
```

I'm going to close the issue, please reopen if you need help!
