### ISSUE TITLE
Singularity exec module not working

### ISSUE THREAD

**Issue by renganxu** [apptainer/singularity#729]
## Version of Singularity:
2.3

### Expected behavior
After executing the command:
singularity exec -s /bin/bash -w test.img module list

the expected output should be (no modules loaded yet but at least has some output):
Currently Loaded Modulefiles:

It's also not working for other module commands such as "module load"
There is no issue if I use "singularity shell ..." and then execute "module list" inside the container.

### Actual behavior
the actual output is:
/.singularity.d/actions/exec: line 8: exec: module: not found

### Steps to reproduce behavior
singularity create test.img
singularity bootstrap test.img rhel.def
singularity exec -s /bin/bash -w test.img yum install environment-modules
singularity exec -s /bin/bash -w test.img module list

**Comment by dexter2cz** [comment]
Hello,
module is a shell function, that si declared by sourcing /etc/profile (/etc/profile.d/modules.sh -> /usr/share/Modules/init/$shell). Try something like this:

$ singularity exec -s /bin/bash -w test.img bash -c "source /usr/share/Modules/init/bash; module list"

No Modulefiles Currently Loaded.

**Comment by renganxu** [comment]
@dexter2cz Thanks. your solution works.

**Comment by dtrudg** [comment]
Closing this issue as it looks like it was solved following the suggested solution. Please let us know if you have any further issues. Thanks to @dexter2cz !
