### ISSUE TITLE
Rewrite non-standard home directory path for easy docker imports on system without PR_SET_NO_NEW_PRIVS

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#730]
Singularity 2.3

We are running singularity on a system with 

- User home directories under /home2
- A kernel that doesn't have neccessary PR_SET_NO_NEW_PRIVS support for user bind

Most of our users are interested in importing docker containers to try out new deep learning apps etc. Since there is no /home2 in these containers the home dir mount will fail. Using `-H /home2/me:/home/me` also fails due to no PR_SET_NO_NEW_PRIVS support.

Is there any chance that there could be some kind of option to rewrite home directories when added to the container /etc/passwd?

At present we are asking users to do something like...

```
Singularity tensorflow_cpu.img:~> export HOME="/tmp/${USER}-fakehome"
Singularity tensorflow_cpu.img:~> mkdir "$HOME/"
```

... which works, but is a bit messy. Understand if this is not a priority given common PR_SET_NO_NEW_PRIVS support in most-used kernels. We will actually only have this issue until we upgrade our cluster later in the year.

Many thanks for this great software.

**Comment by gmkurtzer** [comment]
Hi @dctrud,

You could possibly do this within the `%environment` bootstrap section and make it a scriptlet that virtualizes the home directory from within the container. We can't do it safely outside if `SET_NO_NEW_PRIVS` is not available on the host.

Hope that helps!
Greg

**Comment by dtrudg** [comment]
Thanks for the pointer - will close this and try that!
