### ISSUE TITLE
Definition of Services - Feature for 2.4

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#735]
Given that we want to eventually work up our way to "orchestration of containers" (akin to docker-compose) using Singularity containers, the logical steps to that are that we need 1) a container to spit out it's metadata / bits (and we've accomplished the start of this with `inspect`) but now we 2) need to define and expose services more cleanly. Part 3) will be orchestration of those two things, but likely that will be for a later time.

The example I will give is a simple web server, as we had a recent issue in the user list with regard to an apache2 daemon still running when the container stopped. Right now, the way to go about using a container to run a service is to have a runscript that ends in something like:

```
exec service apache2 start
```
and then the user would run the container:

```
singularity run apache2.img
```

to execute this command. Depending on the addition (or absence) of the `--pid` or `-p` argument, we can get a few outcomes with this call.

1. Not having the argument means that the server will still be running, as a daemon, for example, you could shell into another container without it, start apache, and then in a different window on the host see

```
ps -fC apache2
UID        PID  PPID  C STIME TTY          TIME CMD
root     25943  5463  0 17:07 ?        00:00:00 /usr/sbin/apache2 -k start
www-data 25945 25943  0 17:07 ?        00:00:00 /usr/sbin/apache2 -k start
www-data 25947 25943  0 17:07 ?        00:00:00 /usr/sbin/apache2 -k start
```

Then exiting the container (or if you did exec, just exec-ing the command to start apache). You wouldn't see these processes go away.

2. Having the argument (I think) would create a new PID namespace, and exit (or a quick exec) would not leave the processes on the container. A few important points to address:

### Should running a container start a service?
There isn't any official rule, but I don't like the idea of a container run being linked to starting a service that might potentially hang around when the user (thinks) it's finished. This is an unwelcome surprise. The answer to "should running a container start a service." is no.

### Container Services
Thus, we need to make an easy, transparent way for makers to define services, and for users to user them. With this we should strongly advocate to not include starting/stopping of services as part of the runscript, unless the service is specifically started and stopped during the duration of the runtime. An easy solution, and one that would fit into a (later) need to have not only services, but orchestration of them, is adding a `%services` section to the build definition.

#### Defining a service
The user would define a service like:

```
[ action ] [ service name ] [ command ]
```

where `action` is either start / stop / restart (or any of the standard allowable ones you generally use), `service name` is a single string to identify it (eg from the command line), and this would be defined by the user), and the `command` is the controller of the service. For example

```
%services
start apache2 service apache2 start
stop apache2 service apache2-stop
```
 
So from outside the container, let's say I had a bunch of services and I wanted to stop them all, I'd do:

```
singularity start ubuntu.img
```
If I wanted just apache

```
singularity start ubuntu.img apache2
```

and what that would essentially do is start and stop the services provided by the container. What singularity would need to do internally is keep a simple pid for each running service, somewhere writable for the user and accessible by singularity, and then add and remove the file as needed. If the service stops automatically or before the user asks for a stop, the pid should be removed and there shouldn't be a bug that the container thinks it's running, but it's not. The container would spit out a friendly warning when the user asks to stop a service that isn't running. 

### Container Services... more than services?
The really cool part of this workflow is that it would be flexible to things that aren't technically services, but the container maker could specify them to be. For example, take a look at this (from some scientific container)

```
%services
start analysis-pipeline /usr/bin/python /code/start.py
start brain-reg /usr/bin/python /code/registration.py
```
For the above, notice that I haven't even defined any "stop" commands, although arguably the container could by default, if no stop exists, find all active pids that have been generated (for the above it would be for python) and just kill them. This also introduces an idea that I'm not sure others will like/hate - having the ability to start a container as a service, meaning something is running via some background process.

### Orchestration
Ultimately, we want something that would make it really easy for a user (using Singularity) to give a container different contexts (something I brought up a long time ago.) A context is a description of actions (defined by services provided within or between containers). It might also include custom mounts or sourcing environment variables, anything that could be done by issuing the start command. For example, a user could do something like:

1. Run a service to listen for PUT of data to my container (which is a web endpoint)
2. When data is received, get it, and stop the service (the container is being used now for an analysis)
    -  When this happens, spawn another listening container to wait for the next. Or keep listening, and start a different service (container?) to process the data.
3. Start container with service that gives it context to run some analysis pipeline. Services might be chained, or maybe with different (independent) data components run by different works.

Probably some of the above belongs better in some management pipeline (yes there are many!) but the important note is that having these services defined and exposed, along with inspect for other metadata, are the two essential pieces for making singularity containers better talk to the world around them. Thoughts?

**Comment by vsoch** [comment]
comment from @gmkurtzer on list:

>> Also there was just a meeting that I had with some other developers trying to think about how to deal with this (and similar) use cases directly. I think it is going to look like:

```
$ singularity start container.img
$ singularity status container.img
SINIT process active
$ singularity shell container.img
Joining existing SINIT namespaces...

$ singularity stop container.img
Killing all processes running under SINIT
```

>> Basically, once you have started a container process, any subsequent action commands (shell, exec, run, etc..) that you invoke on that container will always join the existing namespace. This means that you will be able to run daemon processes as you would expect and come back to it and kill it afterwords. Where it is going to get really tricky is systemd because something like `service httpd start` is actually going to connect to the systemd process, so we will need to make sure that systemd is running properly first.

Anyway, that is what we are currently thinking.

**Comment by vsoch** [comment]
comment from @bauerm97 also on list:

>> Singularity is, in its current state, not capable of properly dealing with daemons (and to a broader point, PID namespaces in general) running in the container. We are currently fleshing out a solution to this and have begun working on possible implementations. The current proposed solution is to implement an optional start/stop feature, which will properly handle the PID namespace by spawning an “s-init” process inside the PID namespace which will exist as PID 1. “singularity stop” will instruct the “s-init” process inside the PID namespace to terminate, which will cause the kernel to reap the remaining process inside the PID namespace. Daemon processes spawned inside the PID namespace will no longer linger after the main singularity process is terminated. Let me know if this will be sufficient for your use cases!

**Comment by bauerm97** [comment]
@vsoch Just to reiterate what I stated on the mailing list, this is currently in active development and I should have a prototype of this line of execution ready for a first round of testing in a few days time!

**Comment by vsoch** [comment]
you're a bad@ss @bauerm97 ! It must be because you are liking CA so much? I'm sorry I missed you (yesterday was it?) I had (and still have) some yuck-sickness and I don't even have a voice!

**Comment by ArangoGutierrez** [comment]
#### +1 on this issue!
#

Following the logical steps proposed by @vsoch. 
> 2) need to define and expose services more cleanly. 
> 3) will be orchestration 

I think that the idea of @cclerget of having a status storage 
``` bash
/var/run/singularity/{image-name}.{uid}.{pid}
```
is important for those steps.   Since the orchestration service will need to tell every service exposed from singularity images, a global status storage is a must.
This status storage can be also a JSON file as the `inspect` command, and will expose something like
```json
[
    {
"Singularity Version": "",
"Image": {"Def_file_from": "", "Image_name": "", "Created_date": "",".img_path": ""},
"uid": "",
"Singularity_global": { },
"Singularity_command_options": { },
"Container_Command": {"Command": "","Args": ""},
"State": {"Status": "", "Running": "","Restarting": "", "Pid": "", "ExitCode": "", "Error": "","StartedAt": "", "FinishedAt": "" }
    }
]
```

But also the `inspect` must contain a basic of 
```json
[
    {
"Version": "",
"Def_file_from": "",
"Image_name": "",
"Created": "",
"uid_who_created_the_img": "",
"Path": "",
"Has_Runscript": "",
"Env": ""
    }
] 
```
This is just me thinking on @v's step #3 Container orchestration.

**Comment by vsoch** [comment]
@ArangoGutierrez take a look at the current inspect, it already has many of the features that you are showing. Why would the inspect for an image be in a list as opposed to a single formatted json response? With the above, the user would have to do:

```
result = response.json()
version = result[0]["Version"]
```
to access the `Version`, for example, and the user would expect to do:

```
result = response.json()
version = result["Version"]
```
The field suggestions for the services are good, and coincide with what Docker uses. The various fields, names, and statuses themselves do need to be a bit standardized, and the format of the json for services too. Take a look at [the json api](http://jsonapi.org/format/) if you are interested in learning more about this. For now I wouldn't worry about the actual format of how the services are obtained via inspect (this is pretty straight forward given standards), but rather the implementation of the services / start /stop to begin with. Thanks for your thoughts!

**Comment by ArangoGutierrez** [comment]
@v thanks. I was just making my point, but you are right on the json format, but just don't loose from the main idea. To have a global status storage.  I'm studying the Kubernetes, in order to work around a future integration with Singularity, and that is a key feature. so the Kubelet component will report container node status to the api-server.

**Comment by vsoch** [comment]
@ArangoGutierrez that's a great idea! Each container in a pod is supported by way of adding a folder to here --> https://github.com/kubernetes/kubernetes/tree/master/cluster so for example, Singularity support would be writing the necessary code bits for that. If you are interested in this you should go for it! The work / PR would be to the kubernetes repo, which is open source, and they have very clear instructions for how to go about it. And it looks like their docs say that particular folder isn't accepting new types, and you should start here --> https://github.com/kubernetes/kube-deploy  Have fun!! It sounds like a great project.

**Comment by ArangoGutierrez** [comment]
Yep!.
They have now a [kubernetes-incubator](https://github.com/kubernetes-incubator) , this is where the PR should go first.
But first we must be sure to support some minimal functionalities. that is why this issue post is so important.

Right now I made it to deploy what they call  [jobs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) . 

I'll keep you informed!

**Comment by vsoch** [comment]
awesome! Yes please do.

**Comment by bauerm97** [comment]
@ArangoGutierrez Hi, do you have any more information regarding what you're trying to do with integrating Singularity into Kubernetes? We've been investigating this internally for several weeks and are looking for people that know what they're doing to help us out. We should sync up and communicate what the goal is on both ends of the pipeline. Please reach out to me by email at michael.bauer@rstor.io so we can collaborate on the development!!

@gmkurtzer

**Comment by vsoch** [comment]
@bauerm97 so glad to hear about this effort! Keep me in the loop?

**Comment by benepo** [comment]
+1 for Kubernetes and S3-compliant object storage integration

**Comment by vsoch** [comment]
ping @ArangoGutierrez it's been a while since you posted this (June!)? Any updates?

**Comment by benepo** [comment]
Perhaps a smaller, intermediary goal would be to get Singularity working on HashiCorp Nomad

**Comment by ArangoGutierrez** [comment]
Hi! in deed I started a mini-project (before 2.4 release) and it was painful without instances, now I'm re-starting that project. (it's been a long and hard semester at my campus so I was/am... kind of afk)

 - The first step will be to build a proper Go-client for singularity in order to have a better integration with the commercial orchestration frameworks (Kubernetes, Nomad, Mesos) which are all written in go.
 - Once this Client is in beta, it would be easier (not easy) to integrate with kubernetes, following the steps of [CRI-O](http://cri-o.io/),  who use [runc](https://github.com/opencontainers/runc) for the container runtime  and [CNI](https://github.com/containernetworking/cni) as the network layer.

PS: @benepo you could take a look to the repo [Singularity-On-Nomad](https://github.com/ArangoGutierrez/Singularity-on-Nomad)

**Comment by ArangoGutierrez** [comment]
For those interested on helping here is the repo for the go client:
 - [Go-Client](https://github.com/ArangoGutierrez/singularity-go)

Which will allow us to build a better integration with the commercial orchestration frameworks (Kubernetes, Nomad, Mesos) which are all written in go.

**Comment by ps-account** [comment]
Just checking, a lot has happened since this issue was posted. Are services already implemented? (this is one of the first google results to show up)

**Comment by ps-account** [comment]
*bump* can this at least be considered as an enhancement to end up somewhere on a roadmap, e.g .for 3.1?

**Comment by jscook2345** [comment]
@rdwrt We have an `instance` subcommand that treats containers like services. Is this what you're referring to?

`singularity help instance` gives the following output with links to our user docs currently:

<pre>
$ singularity help instance
Manage containers running in the background

    Usage:
      singularity instance <subcommand>

Description:
  Instances allow you to run containers as background processes. This can be
  useful for running services such as web servers or databases.

Options:
  -h, --help   help for instance

Available Commands:
  list        List all running and named Singularity instances
  start       Start a named instance of the given container image
  stop        Stop a named instance of a given container image

Examples:
  All group commands have their own help output:

  $ singularity help instance start
  $ singularity instance start --help


For additional help or support, please visit https://www.sylabs.io/docs/
</pre>

**Comment by bauerm97** [comment]
@benepo:
>Perhaps a smaller, intermediary goal would be to get Singularity working on HashiCorp Nomad

Done, @ArangoGutierrez has written a Nomad integration plugin.

@benepo:
>+1 for Kubernetes and S3-compliant object storage integration

Done, [sylabs/singularity-cri](https://github.com/sylabs/singularity-cri)

@rdwrt:
>Just checking, a lot has happened since this issue was posted. Are services already implemented? (this is one of the first google results to show up)

Done, check out `singularity instance` command, `singularity oci` command, [sylabs/singularity-cri](https://github.com/sylabs/singularity-cri), etc...

@vsoch:
>so glad to hear about this effort! Keep me in the loop?

As you know, `singularity instance` command is now implemented :)


@vsoch @benepo @rdwrt if any of you would like to extend the current state of services integrated into Singularity, let's open up a new issue and tackle the extension there. For now, closing this issue as complete finally!

**Comment by vsoch** [comment]
@bauerm97 I'd be interested to talk about what it would take to make a "singularity-compose" equivalent. I know you guys have your eyes set of Kubernetes, but there are many use cases of wanting to link together a few containers that would be really useful.
