### ISSUE TITLE
Singularity as a module on a HPC cluster with NFS and root-squash

### ISSUE THREAD

**Issue by abdulrahmanazab** [apptainer/singularity#736]
## Version of Singularity:

2.2.1

### Expected behavior

singularity shell <image-name>
...> 
### Actual behavior
ERROR  : The feature you are requesting requires privilege you do not have
ABORT  : Retval = 255
### Steps to reproduce behavior
You have a cluster of multiple nodes. Shared NFS file system with root-squash. Install singularity as a module 'sudo make install' as the root of the NFS file-system (from one of the admin nodes). Now try to run 'singularity shell' from one of the compute nodes, it produces that error. 

This is somehow obvious because the NFS root is not the same as the root on the compute nodes. Is there any ideas to solve this other than installing singularity using 'sudo make install' on each single compute node. We would like a solution to install it as a shared module other than individual installation on compute nodes.

**Comment by gmkurtzer** [comment]
Running Singularity from an NFS location with the root_squash option will always fail. There are two fixes, the first one you mentioned (to install via source or RPM/DEB onto all of the compute nodes directly), or you remove the root_squash option (which honestly doesn't really offer much in the terms of security).

**Comment by abdulrahmanazab** [comment]
Ok thanks for the answer. We installed it now using the RPM on our 500 nodes. I guess you can close this issue unless you are planning to provide an alternative in the future ;)
Also I think it would be useful to write something about this in the documentation because there will be similar cases.

**Comment by gmkurtzer** [comment]
Good thinking to document the issues with installation over NFS and/or network file systems. I'll take a stab at it (in my free time, which maybe a bit) but if someone has an opportunity before I get to it, it would be greatly appreciated.

Thanks!

**Comment by jscook2345** [comment]
This looks like it is resolved. If not, please comment and we'll work from there. Thanks!
