### ISSUE TITLE
problems with Debian bootstrap

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#74]
I'll try to look into this at some stage, but I'm unable to bootstrap a stable or testing Debian system directly with v 2.0 on an el6 system if it installs the Java runtime, at least.  I see these messages followed by a bunch more and several package installation failures at the end. 

```
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)
Moving old data out of the way

Creating config file /etc/gconf/2/path with new version
Failed to read /proc/cmdline. Ignoring: No such file or directory
X11 connection rejected because of wrong authentication.
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Failed to read /proc/cmdline. Ignoring: No such file or directory
[ ok ] Setting up X socket directories... /tmp/.X11-unix /tmp/.ICE-unix.
the java command requires a mounted proc fs (/proc).
dpkg: error processing package openjdk-7-jre-headless:amd64 (--configure):
 subprocess installed post-installation script returned error exit status 1
```

Shelling into the result and running apt-get install -f does seem to sort it out, though.

There are also non-fatal complaints about the locale en_GB.utf8.

**Comment by gmkurtzer** [comment]
Hrmm... At this point, I am not mounting /proc, /sys or /dev from within a container. I am wondering if that should be changed for this case. Does your bootstrap definition file install these other programs (e.g. Java) via the InstallPkgs keyword (and after Bootstrap)?

Where/when did you get warnings/errors about the locale?

**Comment by gmkurtzer** [comment]
BTW, regarding the warnings abut your locale, it may have something to do with:

```
    if [ -n "$LANG" ]; then
        if eval "chroot '$SINGULARITY_BUILD_ROOT' /bin/sh -c 'locale-gen $LANG'" 2>/dev/null; then
            mkdir -p "$SINGULARITY_BUILD_ROOT/etc/default/" >/dev/null 2>&1
            echo "LANG=$LANG" > "$SINGULARITY_BUILD_ROOT/etc/default/locale"
        fi
    fi

```

Which is in libexec/mods/linux_build_debian.smod

Let me know if something there is causing it.

**Comment by gmkurtzer** [comment]
As far as the kernel mounts during bootstrap'ing, please test [master 1c3b1c5].

Thanks!

**Comment by loveshack** [comment]
You wrote: 

> Hrmm... At this point, I am not mounting /proc, /sys or /dev from
> within a container. I am wondering if that should be changed for this
> case.

For what it's worth, when I chroot into an el6 stateless root image to
make changes I bind mount /proc, /sys, and /dev/pts.  I think they're
all necessary for one reason or another.

> Does your bootstrap definition file install these other programs
> (e.g. Java) via the InstallPkgs keyword (and after Bootstrap)?

Yes.

> Where/when did you get warnings/errors about the locale?

In various places, specifically from perl as far as I remember.  I'll
reproduce it when I get a chance, but it's probably just noise.

**Comment by gmkurtzer** [comment]
I just realized that the --bind is not recursive to mounts within the top level bind, so I changed to use `--rbind` in [master 0ecdc7b].

**Comment by gmkurtzer** [comment]
Closing ticket, but please comment and let me know if this is still an issue.

Thanks!
