### ISSUE TITLE
singularity exec git not working

### ISSUE THREAD

**Issue by renganxu** [apptainer/singularity#741]
## Version of Singularity:
2.3

### Expected behavior
After I run the command:
singularity exec -s /bin/bash -B $PWD:/mnt -w test.img git clone https://github.com/NVIDIA/caffe.git /mnt/caffe

The expected output is:

Cloning into '/mnt/caffe'...
remote: Counting objects: 27858, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 27858 (delta 25), reused 19 (delta 19), pack-reused 27820
Receiving objects: 100% (27858/27858), 39.95 MiB | 5.43 MiB/s, done.
Resolving deltas: 100% (17917/17917), done.
Checking connectivity... done.

### Actual behavior

Cloning into '/mnt/caffe'...
remote: Counting objects: 27858, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 27858 (delta 25), reused 19 (delta 19), pack-reused 27820
Receiving objects: 100% (27858/27858), 39.95 MiB | 5.88 MiB/s, done.
Resolving deltas: 100% (17917/17917), done.
**fatal: unable to look up current user in the passwd file: no such user
Unexpected end of command stream**

Because of the error, the repo clone failed. The clone is successful if I use "git clone" inside the container.

### Steps to reproduce behavior
singularity create --size 4096 test.img
singularity bootstrap test.img rhel.def
singularity exec -B $PWD:/mnt -w test.img yum -y groupinstall "Development Tools"
singularity exec -s /bin/bash -B $PWD:/mnt -w test.img git clone https://github.com/NVIDIA/caffe.git /mnt/caffe

**Comment by gmkurtzer** [comment]
Hello @hfutxrg,

I ran through your reproducer, but it is working for me. I had to make some minor changes (e.g. `sudo singularity bootstrap test.img docker://centos:latest`, and prefix the `yum` singularty line with `sudo` but the rest worked as expected). Were you running as root for all of the above commands?

What is inside the passwd file inside that container?
```
$ singularity exec test.img cat /etc/passwd
```
Is it normal, and does your user name exist there?

**Comment by renganxu** [comment]
Hi @gmkurtzer, thanks for the quick reply. 

Yes I ran all commands as root.
The output of the command 
```
$ singularity exec test.img cat /etc/passwd" 
```
is
```
systemd-bus-proxy:x:999:997:systemd Bus Proxy:/:/sbin/nologin
systemd-network:x:998:996:systemd Network Management:/:/sbin/nologin
dbus:x:81:81:System message bus:/:/sbin/nologin
tss:x:59:59:Account used by the trousers package to sandbox the tcsd daemon:/dev/null:/sbin/nologin
```

**Comment by gmkurtzer** [comment]
That is it?! The only things in the password file? That passwd file is broke... Can you try to recreate and bootstrap the container?

**Comment by renganxu** [comment]
@gmkurtzer Yes that's it. I tried to recreate and bootstrap the container many times, and the passwd file is empty. The current singularity version I am using is 2.3. But git works and the passwd file is normal if created and bootstrapped with Singularity 2.2.99. So probably there is some bug in the released version 2.3.

**Comment by renganxu** [comment]
Hi @gmkurtzer, just let you know that I just cloned a copy from the latest singularity git repo and it works. But the released version does not work.

**Comment by gmkurtzer** [comment]
Excellent! The fix (not zero'ing out the passwd/group files on every bootstrap loop) will be included in the next release.
