### ISSUE TITLE
Update security admin guide for Singularity 2.3

### ISSUE THREAD

**Issue by tcooper** [apptainer/singularity#742]
## Version of Singularity:

2.3

### Expected behavior

Security admin guide should be up to date.

### Actual behavior

Security admin guide is not up to date.

### Steps to reproduce behavior

- Browse to http://singularity.lbl.gov/docs-security
- Read the security admin guide
- Note references to `$PREFIX/libexec/singularity/sexec-suid`
- `$PREFIX/libexec/singularity/sexec-suid` does not exist in version 2.3
- Examine files in `$PREFIX/libexec/singularity` to find...

```
$ find $PREFIX/libexec/singularity -perm -4000
$PREFIX/libexec/singularity/bin/import-suid
$PREFIX/libexec/singularity/bin/mount-suid
$PREFIX/libexec/singularity/bin/action-suid
$PREFIX/libexec/singularity/bin/create-suid
$PREFIX/libexec/singularity/bin/expand-suid
$PREFIX/libexec/singularity/bin/copy-suid
```

 Please update the security admin guide to reference the new suid binaries.

Also, it would be helpful to expand this guide to explain the purpose of each suid binary. For example, for basic operations, `singularity create ...`, `singularity import ...`, `singularity shell ...` and `singularity exec ...` only the following binaries need the suid bit set...

```
$ find $PREFIX/libexec/singularity -perm -4000
$PREFIX/libexec/singularity/bin/import-suid
$PREFIX/libexec/singularity/bin/action-suid
$PREFIX/libexec/singularity/bin/create-suid
```

Disabling other suid binaries may be preferable to managing the `LIMIT CONTAINER OWNERS` option in the `$PREFIX/etc/singularity/singularity.conf` file.

**Comment by vsoch** [comment]
+1 on this issue, I was just bothering @gmkurtzer this week about some of those exact files!

@gmkurtzer if you want to write up the descriptions, I can update the page and figure out the new binary locations, etc.

**Comment by gmkurtzer** [comment]
Heya @tcooper, great catches.

@vsoch, awesome thanks! I will do this at my first opportunity (already getting late today).  I will post the updates here (unless you want to create another issue on the pages repo?).

**Comment by vsoch** [comment]
that's funny, do you know why your find lists create, action, and import twice? Mine I get just these:

```
find /usr/local/libexec/singularity/ -perm -4000
/usr/local/libexec/singularity/bin/create-suid
/usr/local/libexec/singularity/bin/copy-suid
/usr/local/libexec/singularity/bin/action-suid
/usr/local/libexec/singularity/bin/mount-suid
/usr/local/libexec/singularity/bin/import-suid
/usr/local/libexec/singularity/bin/export-suid
/usr/local/libexec/singularity/bin/expand-suid
```
I think your computer has ghosties in it.

**Comment by vsoch** [comment]
I'm already starting work on the page, so if you post here I'll see it and forward along the copy paste, lol

**Comment by tcooper** [comment]
Careless copy/paste from my dev system... sorry. There are only one of each of these.

**Comment by vsoch** [comment]
hey @tcooper ! This might still need the magic touch of @gmkurtzer , but I gave an early pass at updating to addres this specific issue. Take a look --> http://singularity.lbl.gov/docs-security and let us know what you'd like further explained, etc.

**Comment by tcooper** [comment]
Thanks for the additional detail...very much improved! I'll probably add a step in our Rocks roll-build process to check `singularity.spec.in` for the `#SUID programs` and trigger a warning if the list changes between versions. I'll let you guys close the issue when you're satisfied you've completed the updates.

**Comment by vsoch** [comment]
@gmkurtzer I'll leave this to you when you take a look at my final changes. Who knows what I snuck in there...

Thanks for the issue @tcooper ! Let us know what other holes are in the docs - I don't have many years experience as any kind of HPC admin so I don't have a great sense of the thought process that one would go through, and likely this is reflected via some important stuffs missing in the docs.

**Comment by gmkurtzer** [comment]
It looks great to me, thanks @vsoch and @tcooper! :)
