### ISSUE TITLE
child rw mounts gets overwritten by parent ro mounts

### ISSUE THREAD

**Issue by bgruening** [apptainer/singularity#743]
## Version of Singularity:

```
singularity --version
2.3-master.g044a991b
```

### Expected behavior

If I mount two folder that are nested like
`-B /home/bag/temp:/home/bag/temp:ro` and `-B /home/bag/temp/foobar:/home/bag/foobar:rw`
the parent `ro` folder takes precedence over the child `rw` mount. This prevents fine grained user-mounts.

### Actual behavior

Ability to write into any mount that is labelled as `rw`.

### Steps to reproduce behavior

 ```
singularity exec -B /home/bag/temp:/home/bag/temp:ro -B /home/bag/temp/foobar:/home/bag/foobar:rw  singularity_import/samtools:1.4.1--0 touch /home/bag/temp/foobar/file.txt
touch: /home/bag/temp/foobar/file.txt: Read-only file system
```

**Comment by gmkurtzer** [comment]
Hi @bgruening,

The problem actually has to do with ordering, and the current ordering is non-intuitive. What is happening is that Singularity first mounted `/home/bag/temp/foobar` as read-write and then it mounted `/home/bag/temp` as read-only. If you change the ordering I bet you it would work. To make things more intuitive, I will change the ordering.

Does that seem reasonable?

**Comment by bgruening** [comment]
@gmkurtzer  tried this as well, but odering does not seem to be the problem.

```
 singularity exec -B /home/bag/temp/foobar:/home/bag/foobar:rw -B /home/bag/temp:/home/bag/temp:ro singularity_import/samtools:1.4.1--0 touch /home/bag/temp/foobar/file.txt 
 
WARNING: Bind file destination does not exist in container: /usr/local/var/singularity/mnt/overlay/final/etc/resolv.conf
touch: /home/bag/temp/foobar/file.txt: Read-only file system

```

**Comment by gmkurtzer** [comment]
I think you have a typo "-B /home/bag/temp/foobar:/home/bag/foobar:rw" (missing the `temp/` directory in the dest path.

BTW, you can take a shortcut of just supplying `-B /home/bag/temp/foobar` in that if dest == source, it is assumed.

**Comment by bgruening** [comment]
@gmkurtzer true! In this case it seems to be the ordering will do the trick! Any estimation of a new release with this fix.

**Comment by gmkurtzer** [comment]
Yep, it will be in the next point release (2.3.1) which is coming soon!

**Comment by gmkurtzer** [comment]
I am closing the issue. Let me know if it needs to be reopened. Thanks! :)

**Comment by bgruening** [comment]
Thanks!
