### ISSUE TITLE
--quite is not working

### ISSUE THREAD

**Issue by bgruening** [apptainer/singularity#744]
## Version of Singularity:
```
singularity --version
2.3-master.g044a991b
```

### Expected behavior

Suppress warnings during execution.

### Actual behavior

I get:
```
singularity --quiet exec  singularity_import/samtools:1.4.1--0 ls -l
WARNING: Bind file destination does not exist in container: /usr/local/var/singularity/mnt/overlay/final/etc/resolv.conf
```

### Steps to reproduce behavior

```
singularity --quiet exec  singularity_import/samtools:1.4.1--0 ls -l
```

**Comment by gmkurtzer** [comment]
Heya @bgruening,

I typically consider --quiet to suppress normal output, not warnings or errors as their presence describes a misalignment between the expected/requested behavior and what is possible. I would tend to feel that warnings (and of course errors) are printed with --quiet.

With that said, I would be open to supporting a --silent option, that won't even print warnings or errors. Any other opinions?

**Comment by bgruening** [comment]
Hi @gmkurtzer!

Maybe we can make `--silent` take arguments like pythons logging module is doing. warn/error and so on? I think there are use-cases where you want to omit warnings but see errors.

Just a little bit of background, I try to create a [conda](https://conda.io/docs/using/) package for Singularity (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/singularity/meta.yaml) and in Conda you don't know where your package ends up. it is relocatable and a user can install it.
When I do this, Singularity obviously was not able to set everything up under `/usr/local/var/singularity/`.

I found that Singularity is working quite well with this setup, but the warnings are annoying. 
Btw. why does `/usr/local/var/singularity/mnt/overlay/final/etc/resolv.conf` needs to be in the container?

Thanks!

**Comment by gmkurtzer** [comment]
Heya @bgruening,

Ahhh, I follow what you are doing with Conda now, excellent idea!

I would suggest that we move some of these issues into milestones for the 2.4 release such that Singularity can be relocated easier.

Now to your point, Singularity utilizes a numeric message level scheme where each message specifies a numeric level. What gets printed depends on if a message's level is less then the requested level with warnings and errors being negative numbers, and increases in verbosity/debugging is positive numbers. By default, the messagelevel is 1. `--quiet` sets the message level to 0. We can have `--silent` which sets it to -1.

Does that make sense?

**Comment by bgruening** [comment]
Ah nice! But this means that the above warning is getting a message level of `-1` because it is printed even if `--quite` is specified. I guess in my use case it is ok to see `errors`, but not vital warnings I would like to omit. 

Your proposed `--silent` seems good, but I guess we need to revise the attached message levels as well, correct?

**Comment by gmkurtzer** [comment]
Ok, I just updated master with some relevant changes including the `--silent` option.

BTW, I really should have reminded myself about the message levels... WARNINGs are -2, so --silent has to set messagelevel to -3. Anyway, fixed now, sorry for the misinformation.

Greg

**Comment by bgruening** [comment]
Great, thanks a lot!
