### ISSUE TITLE
Singularity static binary

### ISSUE THREAD

**Issue by bgruening** [apptainer/singularity#745]
For CI environments it would be very handy to offer static binaries, like Docker is doing.

I have seen a few locations where Singularity assumes some directories under `/usr/local/var/` which seems problematic during runtime.

Anyone know if this is currently possible?

**Comment by vsoch** [comment]
Would a traditional install not suit your needs on a CI environment? If the issue is install time, you could take advantage of caching, for example [on circle](https://circleci.com/docs/1.0/how-cache-works/) or [on travis](https://docs.travis-ci.com/user/caching/). If this doesn't meet your need, could you point me to something about what Docker is doing so I can learn more?

**Comment by bgruening** [comment]
@vsoch have a look at this: https://docs.docker.com/engine/installation/binaries/#install-static-binaries
Just downloading a binary is way faster than compiling and you don't need the build libraries and tools.

**Comment by vsoch** [comment]
oh that's pretty neat! Although I have no idea how to do it - would it come down to providing a dump of executables that could be extracted (with root) to the standard `/usr/local`? The tricker part is the config file, I suppose if we want it for CI we could just use the default settings.

This might be easy to do (and maintain) if we use the same CI places to build (and then save the executables). @gmkurtzer what are your thoughts, would this work for Singularity? Or is there other stuffs that wouldn't be "dumpable" that we need to account for?

**Comment by jmstover** [comment]
@bgruening Are you talking of a static compile of singularity? I mean, I think the locations under `/usr/local/var` are because of the compile options... i.e. `$prefix/var` as `--localstatedir` wasn't specified.

Static versions are already build of libsingularity-{image,runtime} ... so I'm guessing just having a static target in the Makefiles that builds with `-static` would probably get close to what you're wanting...

**Comment by bgruening** [comment]
@jmstover yes I'm taking about a static compile option. But with such a binary hard coding a path like `--localstatedir` can be problematic. Can `--localstatedir` not be setup during runtime?

**Comment by jmstover** [comment]
@bgruening I _think_ there may be a `SINGULARITY_*` variable that may control that... I'm not sure which though. @gmkurtzer ... is that the default for `SINGULARITY_CACHEDIR`?

**Comment by gmkurtzer** [comment]
Hi everyone,

**static, single file build**: There are multiple reasons why Docker can release a single binary file where it is not feasible with Singularity. In theory, if we convert all of the shell code and Python code to C, we probably could, but I don't like this idea for a multitude of reasons. Additionally Docker is written in Go which facilitates this.

**static compilation**: This is possible, but I would prefer binary packaging (e.g. RPM/DEB).

**localstatedir**: Jason is correct, this is set during compilation time, and it is designed to be immutable as where it is must be on the local file system (e.g. not over NFS), and thus should be defined by the system administrator. While this could be a configurable option, it is not something that needs any modification or touching, and these directories are created by the installer (vs. configured where the admin will have to modify the host system afterwords).

Hope that helps.

**Comment by bgruening** [comment]
__static compilation__: Binary packaging is what I want to use (Conda), but this pkg-manager does not have root privileges. 

__localstatedir__: the problem is when I take a package managers, like Conda where I ship binary files and the package manager does not have root privileges. So I can get Singularity to the users computer, but I have no way to say please use /tmp/ or /home/user/tmp/ instead. Even worse, Singularity is assuming some directory under `/usr/var` which was not created and refuses to work. Even with root privileges it is not creating the the missing directories.

I think especially when Singularity tries more and more to run without root, this would be a nice feature to get Singularity easily and run containers purely in user-space.

**Comment by gmkurtzer** [comment]
Hi @bgruening,

It is going to be a long time coming before Singularity can effectively run without root permissions. That may nullify the necessity for users to be installing it, at least for the near-mid future.

Regarding the localstatedir, this is statically compiled in for security, and can be changed with the configure option `--localstatedir=...`. There is no way for this to be runtime configured in the current version, but I suppose it would/could be possible to make this option exist in the configuration file instead. But again, functionality would be pretty limited depending on the host operating system's capability.

Hope that helps!

**Comment by ghost** [comment]
Do really cheap hacks like "hex editing" work somehow to change --localstatedir?

**Comment by bauerm97** [comment]
Closing due to no longer being pertinent. Please open a new issue if you feel we still have something to fix in 3.x. Thanks
