### ISSUE TITLE
autogen.sh missing, referenced in INSTALL.md

### ISSUE THREAD

**Issue by lugh9** [apptainer/singularity#746]
## Version of Singularity:

2.3

### Expected behavior

either include autogen.sh or remove reference from INSTALL.md

### Actual behavior

INSTALL.md references an installation component not included in distribution package

### Steps to reproduce behavior

tar xzfv singularity-2.3.tar.gz
cd singularity-2.3
./autogen.sh
-bash: ./autogen.sh: No such file or directory

**Comment by vsoch** [comment]
This is definitely a bug - is this the .tar.gz from the tagged repo, or another download location? The autogen.sh is included in master branch, so it (should) be included in the .tar.gz.

@gmkurtzer I just downloaded the most recent .tar.gz, and it is indeed not there. Did you do anything special / different so it wouldn't be included? Is the install intended to be done in a different way (not using this file?) If so, could you post here and I'll update the docs (and we will need to address this issue by also updating the INSTALL.md)

**Comment by gmkurtzer** [comment]
Actually, this is the correct behavior for released tarballs (`autogen.sh` not being present). The purpose of autogen is to create the `configure` script and all of the `Makefile.in`s.

We need to update the INSTALL.md to reflect the difference when pulling a developer source tree Vs. a release source tree.

**Comment by gmkurtzer** [comment]
Comments on [development 1bd6d5a]?

**Comment by vsoch** [comment]
thanks @gmkurtzer ! And it looks like we do have those steps in the website doc instructions too.

**Comment by gmkurtzer** [comment]
This is fixed and merged at this point, so I'm gonna close this issue. Thanks everyone!
