### ISSUE TITLE
Singularity Ignores Umask when Creating Images

### ISSUE THREAD

**Issue by Saford91** [apptainer/singularity#748]
### Expected behavior

I expect files Singularity creates to use the current umask.

For example:

```
# umask 0077
# singularity create container.img
...
# ls -l container.img
-rwx------ 1 steve steve  805306400 Jun 12 16:36 container.img
```

### Actual behavior

Singularity creates the container as if the umask is set to 0022.

```
# umask 0077
# singularity create container.img
...
# ls -l container.img
-rwxr-xr-x 1 steve steve  805306400 Jun 12 16:52 container.img
```

### Steps to reproduce behavior

Set umask to 0077
Create container file

**Comment by gmkurtzer** [comment]
Will you retest with [master a1c228e]?

Thanks!

**Comment by Saford91** [comment]
The latest build works as expected.

```
$ umask 0077
$ singularity create container.img
...
$ ls -l container.img
-rwx------. 1 steve steve 805306400 Jun 19 08:59 container.img
```

Thanks!
