### ISSUE TITLE
reveals too much python in "incorrect" (?) invocation of singularity pull

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#751]
## Version of Singularity:

2.3 (debian)

### Expected behavior

expected pull to succeed and me get an image

### Actual behavior

```shell
$> singularity pull shub://repronim/niceman                 
Traceback (most recent call last):         
  File "/usr/lib/x86_64-linux-gnu/singularity/python/pull.py", line 74, in <module>
    main()
  File "/usr/lib/x86_64-linux-gnu/singularity/python/pull.py", line 66, in main
    layerfile=LAYERFILE)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/shub/main.py", line 79, in PULL
    image_name = get_image_name(manifest)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/shub/api.py", line 169, in get_image_name
    image_name = "%s-%s.%s" %(manifest['name'].replace('/','-'),
```

ha -- and to make it work -- need to be precise in casing: ```singularity pull shub://ReproNim/niceman
``` worked... I guess I got spoiled by github not carrying about the case?

**Comment by vsoch** [comment]
I think it's correct that the capitalization needs to be specific in this case, because it's the uri for an image. Do you consider this a bug?

**Comment by yarikoptic** [comment]
not really -- just a bit unexpected since github is ignoring it...   I was primarily whining that spitting a full traceback is suboptimal here -- some message like "an image blah/bloo was not found.  Note that URI is case sensitive" would be sufficient and much more user friendly ;)

**Comment by vsoch** [comment]
oh yeah, totally agree - that's pretty ugly.

**Comment by vsoch** [comment]
ah, I actually had a catch, I was just catching the wrong thing :) I should be able to fix this!

**Comment by dtrudg** [comment]
Closing - this is fixed. Checking on 2.4.5 gives:

```
09:37 AM $ singularity pull shub://repronim/niceman  
ERROR Cannot find image. Is your capitalization correct?
```
