### ISSUE TITLE
if extraction of pulled image fails -- leaves it compressed

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#752]
## Version of Singularity:

2.3

### Expected behavior

extract

### Actual behavior

if previous extraction failed (out of space), next pull says just that we have it already and that is it

### Steps to reproduce behavior

send me a bigger SSD, and I will send you mine at the capacity limit ;)

```shell
$> singularity pull shub://ReproNim/niceman
Progress |===================================| 100.0% 

gzip: ./ReproNim-niceman-master.img: No space left on device
ERROR: pulling container failed!

# Now I freed up some space!

$> singularity pull shub://ReproNim/niceman
Done. Container is at: ./ReproNim-niceman-master.img.gz

$> ls -lta
total 2485336
drwx--S--- 2 yoh yoh       4096 Jun 13 16:33 ./
-rwx------ 1 yoh yoh 2077159438 Jun 13 16:32 ReproNim-niceman-master.img.gz*
...

$> ./ReproNim-niceman-master.img.gz 
zsh: exec format error: ./ReproNim-niceman-master.img.gz

$> gunzip ReproNim-niceman-master.img.gz 

hopa:~/repronim/containers/singularity
$> ./ReproNim-niceman-master.img 

```

**Comment by vsoch** [comment]
hey @yarikoptic I just added to the current PR (for your other issue!) to modify how this extraction is done. Given that there is a non return code of 0 (indicating some error) we clean up the intermediate files (which should be the image, etc.) Could you give it a test on your tiny hard drive if you get the chance?

https://github.com/singularityware/singularity/pull/753

I'd test it, but you know, my hard drive is WAYY too big.

**Comment by yarikoptic** [comment]
here is a snippet to make a drive as small as you like and to demonstrate original issue so you could try replicating on your box... I am trying to stay away from deploying outside of the packaged version since forgotten local install already caused us some pains in the past ;)

```shell
hopa:/tmp
$> d=/tmp/tmpdrive; im=shub://vsoch/singularity-hello-world; mkdir -p $d; sudo mount -t tmpfs -o size=70024k tmpfs $d; df -h $d; cd $d; singularity pull $im; sudo mount -o remount,size=1024m $d; singularity pull $im; ./singularity-hello-world-master.img; ls -l; builtin cd /tmp/; sudo umount $d         
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            69M     0   69M   0% /tmp/tmpdrive
Progress |===================================| 100.0% 

gzip: ./vsoch-singularity-hello-world-master.img: No space left on device
ERROR: pulling container failed!
Done. Container is at: ./vsoch-singularity-hello-world-master.img.gz
zsh: no such file or directory: ./singularity-hello-world-master.img
total 50392
-rwx------ 1 yoh yoh 51599774 Jun 19 10:17 vsoch-singularity-hello-world-master.img.gz*

```
