### ISSUE TITLE
SINGULARITYENV_PATH is hardcoded in 2.3

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#754]
## Version of Singularity:

2.3.0 

### Expected behavior

Expect to be able to use SINGULARITYENV_PATH to set the PATH inside a container

### Actual behavior

Only a combination of the hardcoded SINGULARITYENV_PATH in the etc/init and whatever is set in user's ~/.bashrc is used as the $PATH inside a container

### Steps to reproduce behavior

Set SINGULARITYENV_PATH in your environment and modify it in your ~/.bashrc. Observe the result to be as described in Actual behavior above.

**Comment by gmkurtzer** [comment]
Heya @moskalenko! Thanks for the PR. Can we close this now?

**Comment by moskalenko** [comment]
Sure, thanks for merging my PR.
