### ISSUE TITLE
Fails to bind/mount a non existing dir in container

### ISSUE THREAD

**Issue by osallou** [apptainer/singularity#756]
## Version of Singularity:

2.3-dist

### Expected behavior

Have in conf user bind control and enable overlay to yes

Expect to mount a local directory in container even if it does not exists in container

I am on CentOS 6.7

### Actual behavior

as options are set as per doc explained, user should be able to mount a non existant directory in container.

### Steps to reproduce behavior

    ./singularity/bin/singularity   shell -B /omaha-beach/xx:/opt/xx  centos-latest.img

**Comment by vsoch** [comment]
hey @osallou ! Could you please provide output with `--debug`? The above seems to work ok for me:

```
 singularity   shell -B /home/vanessa/Desktop:/opt/xx  centos-latest.img 
Singularity: Invoking an interactive shell within container...

Singularity centos-latest.img:~> ls /opt
xx
```
(I apologize I know that's the worst message "hey it works for me!" but with debug we can start to figure out what is going on

**Comment by GodloveD** [comment]
I think that `enable overlay = yes` requires that Singularity be running on a host that implements an overlay file system.  I don't think this is available in RHEL 6/CentOS 6.  I believe it makes it's first appearance in RHEL 7/CentOS 7.  Can anyone else verify?

**Comment by osallou** [comment]
could indeed by centos6 related , but many clusters/hpc do not have recent OS... :-(

**Comment by thiell** [comment]
I just ran into the same issue on a RHEL6.9-based cluster. overlayfs is actually supported in RHEL 7.1 as a [tech preview](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.1_Release_Notes/chap-Red_Hat_Enterprise_Linux-7.1_Release_Notes-File_Systems.html) only, so while it could work on a RHEL/CentOS 7-based host, it won't with a standard CentOS/RHEL 6 kernel, doh. Is there another way to do custom bind if files don't exist in the container?

**Comment by dtrudg** [comment]
Closing this - as noted overlay is not present on CentOS/RHEL6. If you need to bind into a container you will need to add the directory bind point to the container by building a new image, with `mkdir` in `%post` to add the required directories.
