### ISSUE TITLE
Too many levels of symbolic links

### ISSUE THREAD

**Issue by fmorency** [apptainer/singularity#757]
## Version of Singularity:

2.3

### Expected behavior

Using the singularity container while the image is on a network share mounter using autofs should work. This used to work with 2.2.1

### Actual behavior

Sometime, the container usage fails with error "Too many level of symbolic links" with the path pointing to the `.img` file. 

### Steps to reproduce behavior

On our end, this happens when we run our Nextflow processing pipeline on our SLURM mini-cluster and the image is on our SMB network share mounted using autofs. I know that Slack users gshamov and maswan both had the issue when using an automounter on Lustre/NFS. Here's an excerpt of the Slack discussion:

```
gshamov [2:10 PM] 
We have /sbb filestystem that is Lustre, that gets automounted per user as /global/scratch/user. When I bind both with -B and try to access /global/scratch/user I get " Too many levels of symbolic links" error.

maswan [2:41 PM] 
ugh, we've just been fighting that
we ended up with static nfs mounts
we think the kernel gets all confused at the point where autofs tries to unmount an "idle" filesystem that only has bind mounts and then gets all confused for future access to the filesystem, or something
worked fine for some filesystems, horribly for others
etc

fmorency [2:46 PM] 
I sometime see that error with autofs + cifs (smb3)
Still not sure what's the cause

maswan [2:48 PM] 
yeah, me neither
``` 

The automounter works fine when accessing the mounts from the terminal before/after the error. I'm not sure how to debug this and any help would be appreciated.

**Comment by gmkurtzer** [comment]
Can you find a simple reproducer?

**Comment by fmorency** [comment]
I will try to make one. I will ask gshamov and maswan if they can help with this.

**Comment by fmorency** [comment]
I found a way to replicate the issue. I am not sure all the steps/details are required here, but this is how I could reproduce the issue:

Network share
  Samba 4.5.10 (CIFS) share from FreeNAS. I think the problem should also occur with any type of network share that make use of an automounter. We make use of Kerberos for authentification and we use some fancy mount options that, I think, are not relevant to this issue.


Host: Ubuntu 14.04
```
$ sudo apt-get install autofs
$ cd /
$ sudo mkdir test
```

Edit the file `/etc/auto.master` and add at the end of the file

  `/test   /etc/auto.test --ghost --timeout=60`

Edit the file `/etc/auto.test` and add

`testing  -fstype=cifs,sec=krb5,user=$USER,cruid=$UID,multiuser,nounix,mfsymlinks,resilienthandles,vers=3.0 ://hostname/path`

As I said previously, I don't think all those mount options are necessary to reproduce this issue.

Restart the `autofs` service using `sudo service autofs restart`

You should now see a folder `testing` inside `/test`. 

Create a dummy (Trusty-based) container file `image.img` using Singularity 2.3 and place it on the network share in `/test/testing`. Open a `shell` inside the container using

```
$ cd /
$ singularity shell /test/testing/image.img
```

Exit the shell and wait until the 60 seconds automounter timeout expires. Try to open a shell again using

```
$ singularity shell /test/testing/image.img
```

You will get the error 

```
ERROR  : Could not open image test/testing/image.img: Too many levels of symbolic links
ABORT  : Retval = 255
```

If you try to open a shell again, it should work as expected. You can repeat this shell/timeout thing and get the error every next shell.

**Comment by fmorency** [comment]
A bit more on this.

The issue seems to be caused by autofs + kernel namespace [1]. Disabling the autofs `umount` using `--timeout=0` works as a workaround.

[1]: https://www.spinics.net/lists/autofs/msg01158.htm

**Comment by DrDaveD** [comment]
I have seen this also on Redhat EL6, attempting to automount a cvmfs filesystem.  It seems to be a fundamental limitation of the 2.6 series kernel.  It does not happen on Redhat EL7.  It fails the same way for me on all versions of singularity.

**Comment by fmorency** [comment]
FWIW, I have this issue with kernel 4.4.

**Comment by sbutcher** [comment]
I experienced this on a Centos7.3 with 3.10.0-514.16.1.el7.x86_64. singularity is loaded as a module from /share/apps which is an autofs mount from a gpfs share.
When this occurred, i had successfully run a few container jobs on a node, and then one failed. Upon seeing this symbolic links error, ssh'ing into the machine, i could no longer view /share/apps, (and modules could no longer be loaded), hence this would affect more than just the container, but anyone whose jobs attempted to run on this machine.
didn't previously see this with 2.2

**Comment by gmkurtzer** [comment]
This is a shot in the dark, but by any chance, does changing `mount slave = yes` to "no" have any effect?

I'm sorry I can't be of more help, I haven't used the automounter for over 15 years! lol

Greg

**Comment by sbutcher** [comment]
We have worked around the issue with timeout=0 in our autofs.conf on the compute nodes.
I've seen the issue with docker too. maybe because singularity execs itself out of the proceedings. maybe not a bug/issue with singularity but a "feature" that manifests in default autofs configs. might be worth a documentation note about it somewhere though.

**Comment by intentions** [comment]
I'm seeing the same problem in 2.3.1 on kernel 3.10.

I can start some simple containers without issue, but a user running large numbers of containers has gummed up the nfs mount on may of my nodes with this problem.

I tried setting the timeout for autofs to 0, but that did not fix it on nodes that were already having the problem.

**Comment by Perif** [comment]
We are facing the same issue on version 2.3.1 on kernel 3.10 (Centos 7.2) with autofs on a GPFS volume. From our admins it seems that restarting autofs clear this issue but it still persists after some time. Their belief is that autofs is unmounting the filesystem while Singularity tries to access it. Also, Singularity is installed on this GPFS volume but images are loaded from other mounts (Lustre for example). 

May not be fully related but a similar issue had been raised in an older kernel version (see https://bugzilla.redhat.com/show_bug.cgi?id=868985). Our autofs version is : autofs-5.0.7-54.el7.x86_64

We did not run in this issue with other software.

**Comment by gmkurtzer** [comment]
I wonder if it would help if we were to `open()` the file system directories and persist a file descriptor when we do a bind mount on any location such that there is an active file descriptor on that location....

**Comment by sbutcher** [comment]
I think docker may have implemented a workaround for this, but I don't know
the full details

**Comment by gmkurtzer** [comment]
Is this happening on userbinds or configured binds (E.g. -B ..., or static via configuration file)? (or maybe both)?

Does this happen anywhere else?

**Comment by gmkurtzer** [comment]
I committed a quick test to see if we can convince the automounter that a bind is still in use by persisting a file descriptor to it. Can you test the latest development branch?

Thanks!

**Comment by fmorency** [comment]
@gmkurtzer  I tested the latest development branch and the fix seems to screw the mount after the timeout expires. I can't access it and need to restart autofs to get it to work again.

**Comment by gmkurtzer** [comment]
Wow, that is very weird.... I only opened a file descriptor to the mount point! I will remove that "fix", and thanks for checking!

**Comment by DrDaveD** [comment]
Note that the current unreleased branch of singularity already holds an FD on the running image to prevent autofs unmounts of the filesystem the image is in. Details are in issue #714.

**Comment by Perif** [comment]
Thanks, we'll be testing once our systems are back up (maintenance)!

**Comment by gmkurtzer** [comment]
@DrDaveD Yep, I was trying to solve it for bind paths and user binds. Unfortunately not quite that easy. lol

**Comment by dtrudg** [comment]
Hi @fmorency - this issue was reported against Singularity 2.3. We're now on the 2.4 series and there have been merged fixed (see above) related to autofs. Could you confirm if the issue is present in the latest 2.4 series? If not I'll close the issue. Thanks!

**Comment by fmorency** [comment]
Hey @dctrud - sorry for the late reply. I just tested using the procedure I wrote on [1] with Singularity v2.4.5 and Ubuntu 16.04 host/container kernel 4.13.0-36-generic and the issue seems resolved. I will update our cluster to remove the `--timeout=0` workaround and see how it goes next week.

[1]: https://github.com/singularityware/singularity/issues/757#issuecomment-308852005

**Comment by fmorency** [comment]
Hi @dctrud - I've been running jobs inside Singularity containers on our cluster using autofs `--timeout=60` and everything is fine so far. I think you can close this issue and I'll open a new one if anything comes up. Thanks.

**Comment by dtrudg** [comment]
@fmorency - thank you for the follow up. Am glad this is working for you. Cheers!

**Comment by zffocussss** [comment]
> Hi @dctrud - I've been running jobs inside Singularity containers on our cluster using autofs `--timeout=60` and everything is fine so far. I think you can close this issue and I'll open a new one if anything comes up. Thanks.

hi @fmorency  I am facing this errors when using docker-compose + autonfs
