### ISSUE TITLE
Lack of username causes singularity to abort

### ISSUE THREAD

**Issue by AdamSimpson** [apptainer/singularity#760]
## Version of Singularity:

2.3

### Expected behavior

On systems where usernames are not resolvable( through getpwuid(getuid()) ) singularity should still function.

### Actual behavior

Singularity fails obtaining user information and aborts. This is the case on Titan here at the OLCF where the compute nodes don't have access to LDAP. This previously worked in version 2.2.

### Steps to reproduce behavior
Run singularity on a system where getpwuid(getuid()) returns NULL, as below:

$ aprun singularity -vvv shell Ubuntu.img 
Increasing verbosity level (4)
Singularity version: 2.3-dist
Exec'ing: /usr/lib64/singularity/cli/shell.exec
Evaluating args: 'UbuntuOMPI.img'
VERBOSE: Set messagelevel to: 4
VERBOSE: Initialize configuration file: /etc/singularity/singularity.conf
VERBOSE: Got config key allow setuid = 'yes'
VERBOSE: Got config key allow pid ns = 'yes'
VERBOSE: Got config key allow user image = 'yes'
VERBOSE: Got config key protected image mode = 'none'
VERBOSE: Got config key enable overlay = 'yes'
VERBOSE: Got config key config passwd = 'no'
VERBOSE: Got config key config group = 'yes'
VERBOSE: Got config key config resolv_conf = 'yes'
VERBOSE: Got config key mount proc = 'yes'
VERBOSE: Got config key mount sys = 'yes'
VERBOSE: Got config key mount dev = 'yes'
VERBOSE: Got config key mount home = 'no'
VERBOSE: Got config key mount tmp = 'yes'
VERBOSE: Got config key mount hostfs = 'no'
VERBOSE: Got config key bind path = '/etc/hosts'
VERBOSE: Got config key bind path = '/opt/cray'
VERBOSE: Got config key bind path = '/var/spool/alps'
VERBOSE: Got config key bind path = '/var/opt/cray'
VERBOSE: Got config key bind path = '/lustre/atlas'
VERBOSE: Got config key bind path = '/lustre/atlas1'
VERBOSE: Got config key bind path = '/lustre/atlas2'
VERBOSE: Got config key user bind control = 'yes'
VERBOSE: Got config key mount slave = 'yes'
VERBOSE: Got config key container dir = '/var/lib/singularity/mnt'
VERBOSE: Got config key singularity user = 'singularity'
VERBOSE: Initializing Singularity Registry
VERBOSE: Adding value to registry: 'LIBEXECDIR' = '/usr/lib64'
VERBOSE: Adding value to registry: 'COMMAND' = 'shell'
VERBOSE: Adding value to registry: 'MESSAGELEVEL' = '4'
VERBOSE: Adding value to registry: 'VERSION' = '2.3-dist'
VERBOSE: Adding value to registry: 'LOCALSTATEDIR' = '/var'
VERBOSE: Adding value to registry: 'SYSCONFDIR' = '/etc'
VERBOSE: Adding value to registry: 'BINDIR' = '/usr/bin'
VERBOSE: Adding value to registry: 'IMAGE' = 'Ubuntu.img'
ERROR  : Failed obtaining user information for uid: 5059
ABORT  : Retval = 255
Application 1528005 exit codes: 255
Application 1528005 resources: utime ~0s, stime ~0s, Rss ~3952, inblocks ~141, outblocks ~12

**Comment by gmkurtzer** [comment]
Hi @AdamSimpson, 

This worked previously in 2.2.1? There are a number of user bits of information that we need to obtain from the password database (e.g. home directory, username, etc..). About the best I could offer is to return a NULL username which will only break some things, and NULL for home directory which would only break the 'mount home' feature. Is that acceptable?

Greg

**Comment by AdamSimpson** [comment]
Hi Greg,
I should have mentioned we disable mounting home in singularity.conf so I believe the previous logic in 2.2.1 was to short circuit the username check. If it could be set to NULL and not abort that would be great.

**Comment by gmkurtzer** [comment]
So just to confirm you also must be setting `config passwd` and `config group` to no in the config, is that accurate?

**Comment by gmkurtzer** [comment]
BTW, I updated the master branch, will you test when you have a moment?

Thanks!

**Comment by AdamSimpson** [comment]
That's right, we disabled a few of the settings to get it working. I'm at ISC this week but will test it as soon as I can. Thanks for the quick fix!

**Comment by AdamSimpson** [comment]
Thanks, this appears to be working now.

**Comment by vsoch** [comment]
Great! Closing issue.
