### ISSUE TITLE
SINGULARITY_DISABLE_CACHE and SINGULARITY_CACHEDIR ignored during bootstrap

### ISSUE THREAD

**Issue by AdamSimpson** [apptainer/singularity#761]
## Version of Singularity:

2.3

### Expected behavior

SINGULARITY_DISABLE_CACHE and SINGULARITY_CACHEDIR are honored during bootstrap.

### Actual behavior

SINGULARITY_DISABLE_CACHE and SINGULARITY_CACHEDIR appear to be ignored during bootstrap and the default /root/.singularity directory is used regardless.

### Steps to reproduce behavior

$ export SINGULARITY_CACHEDIR=/tmp
$ export SINGULARITY_DISABLE_CACHE=True
$ sudo -E singularity -vvv bootstrap test.img gpu.def 
Increasing verbosity level (4)
Singularity version: 2.3-dist
Exec'ing: /usr/local/libexec/singularity/cli/bootstrap.exec
VERBOSE: Set messagelevel to: 4
VERBOSE: Initialize configuration file: /usr/local/etc/singularity/singularity.conf
VERBOSE: Got config key allow setuid = 'yes'
VERBOSE: Got config key max loop devices = '256'
VERBOSE: Got config key allow pid ns = 'yes'
VERBOSE: Got config key config passwd = 'yes'
VERBOSE: Got config key config group = 'yes'
VERBOSE: Got config key config resolv_conf = 'yes'
VERBOSE: Got config key mount proc = 'yes'
VERBOSE: Got config key mount sys = 'yes'
VERBOSE: Got config key mount dev = 'yes'
VERBOSE: Got config key mount home = 'yes'
VERBOSE: Got config key mount tmp = 'yes'
VERBOSE: Got config key mount hostfs = 'no'
VERBOSE: Got config key bind path = '/etc/localtime'
VERBOSE: Got config key bind path = '/etc/hosts'
VERBOSE: Got config key user bind control = 'yes'
VERBOSE: Got config key enable overlay = 'yes'
VERBOSE: Got config key mount slave = 'yes'
VERBOSE: Got config key sessiondir max size = '16'
VERBOSE: Initializing Singularity Registry
VERBOSE: Adding value to registry: 'COMMAND' = 'bootstrap'
VERBOSE: Adding value to registry: 'SYSCONFDIR' = '/usr/local/etc'
VERBOSE: Adding value to registry: 'BUILDDEF' = 'gpu.def'
VERBOSE: Adding value to registry: 'DISABLE_CACHE' = 'True'
VERBOSE: Adding value to registry: 'WRITABLE' = '1'
VERBOSE: Adding value to registry: 'VERSION' = '2.3-dist'
VERBOSE: Adding value to registry: 'CACHEDIR' = '/tmp'
VERBOSE: Adding value to registry: 'IMAGE' = 'test.img'
VERBOSE: Adding value to registry: 'MESSAGELEVEL' = '4'
VERBOSE: Adding value to registry: 'BINDIR' = '/usr/local/bin'
VERBOSE: Adding value to registry: 'LOCALSTATEDIR' = '/usr/local/var'
VERBOSE: Adding value to registry: 'LIBEXECDIR' = '/usr/local/libexec'
VERBOSE: Set home (via getpwuid()) to: /root
INFO   : Sanitizing environment
VERBOSE: Adding value to registry: 'WRITABLE' = '1'
VERBOSE: Checking that file pointer is a Singularity image
VERBOSE: File is a valid Singularity image
VERBOSE: Calculating image offset
VERBOSE: Found image at an offset of 31 bytes
VERBOSE: Found available loop device: /dev/loop0
VERBOSE: Using loop device: /dev/loop0
VERBOSE: Set container directory to: /usr/local/var/singularity/mnt/container
VERBOSE: Checking what kind of image we are mounting
VERBOSE: Source path is not a directory: test.img
VERBOSE: Attempting to mount as singularity image
VERBOSE: Mounting /dev/loop0 in read/write to: /usr/local/var/singularity/mnt/container
INFO   : Building from bootstrap definition recipe
VERBOSE: Got bootstrap definition key/val 'BootStrap' = 'docker'
VERBOSE: Adding value to registry: 'DRIVER' = 'docker'
VERBOSE: Got bootstrap definition key/val 'From' = 'ubuntu:xenial'
VERBOSE: Set messagelevel to: 4
Adding base Singularity environment to container
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS found as /usr/local/var/singularity/mnt/container
VERBOSE2 SINGULARITY_METADATA_FOLDER found as /usr/local/var/singularity/mnt/container/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /root/.singularity

**Comment by vsoch** [comment]
I think there are two possibilities - either @gmkurtzer is setting it to over-ride what the python finds (eg, note that the C portion has `CACHEDIR`. Or the variable is somehow being unset / not exported properly for the python to find. @gmkurtzer thoughts?

**Comment by gmkurtzer** [comment]
Yep, you are right @vsoch, Singularity was masking the `SINGULARITY_CACHEDIR`. This is fixed in master, can you test @AdamSimpson? THANKS!

**Comment by vsoch** [comment]
That C, always picking on the python modules! Thanks for the fix @gmkurtzer!

**Comment by gmkurtzer** [comment]
lol, hopefully it fixes it! <crosses fingers>

**Comment by AdamSimpson** [comment]
Thanks, `SINGULARITY_CACHEDIR` looks to be honored with 2.3.1 release.

**Comment by vsoch** [comment]
Two at once!! Great to hear again, and closing this one too.
