### ISSUE TITLE
Building of debian package fails

### ISSUE THREAD

**Issue by niktur** [apptainer/singularity#763]
## Version of Singularity:

2.3 latest master.

### Expected behavior

Build debian package according to the instalation instruction on singularity home page:
fakeroot dpkg-buildpackage -b -us -uc

### Actual behavior.

Failed during building

### Steps to reproduce behavior

fakeroot dpkg-buildpackage -b -us -uc
...
   dh_auto_build
        make -j1
make[1]: Entering directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity'
Making all in bin
make[2]: Entering directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity/bin'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity/bin'
Making all in etc
make[2]: Entering directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity/etc'
./configure_transform.py --defaults ../src/util/config_defaults.h --infile singularity.conf.in --outfile singularity.conf
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /root/.singularity
Traceback (most recent call last):
  File "./configure_transform.py", line 30, in <module>
    from sutils import (
  File "../libexec/python/sutils.py", line 25, in <module>
    from defaults import (
  File "../libexec/python/defaults.py", line 110, in <module>
    os.mkdir(SINGULARITY_CACHE)
OSError: [Errno 13] Permission denied: '/root/.singularity'
Makefile:538: recipe for target 'singularity.conf' failed
make[2]: *** [singularity.conf] Error 1
make[2]: Leaving directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity/etc'
Makefile:401: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity'
dh_auto_build: make -j1 returned exit code 2
debian/rules:7: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

Building as
    dpkg-buildpackage -rfakeroot -b -us -uc
or even
    dpkg-buildpackage -b -us -uc
because dpkg-buildpackage invoke fakeroot by default if the  command is present (see man for dpkg-buildpackage) works fine:
...
   dh_auto_build
        make -j1
make[1]: Entering directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity'
Making all in bin
make[2]: Entering directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity/bin'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity/bin'
Making all in etc
make[2]: Entering directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity/etc'
./configure_transform.py --defaults ../src/util/config_defaults.h --infile singularity.conf.in --outfile singularity.conf
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /home/niktur/.singularity
VERBOSE2 SINGULARITY_ENVIRONMENT found as None/.singularity.d/environment
VERBOSE2 SINGULARITY_RUNSCRIPT found as None/singularity
VERBOSE2 SINGULARITY_TESTFILE found as None/.singularity.d/test
VERBOSE2 SINGULARITY_DEFFILE found as None/.singularity.d/Singularity
VERBOSE2 SINGULARITY_ENVBASE found as None/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as None/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as /home/niktur/SINGULARITY/source/git/18.06.2017/singularity/etc
VERBOSE2 SHUB_NAMEBYHASH not defined (None)
VERBOSE2 SHUB_NAMEBYCOMMIT not defined (None)
VERBOSE2 SHUB_CONTAINERNAME not defined (None)
VERBOSE2 SINGULARITY_CONTENTS found as None/.singularity.d/.layers
VERBOSE2 SINGULARITY_PYTHREADS found as 9

*** STARTING PYTHON CONFIGURATION HELPER ****
VERBOSE3 Reading file /home/niktur/SINGULARITY/source/git/18.06.2017/singularity/src/util/config_defaults.h with mode r.
VERBOSE3 Reading file /home/niktur/SINGULARITY/source/git/18.06.2017/singularity/etc/singularity.conf.in with mode r.
VERBOSE2 Writing file singularity.conf.tmp with mode w.
*** FINISHED PYTHON CONFIGURATION HELPER ****
make[2]: Leaving directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity/etc'
Making all in libexec
make[2]: Entering directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity/libexec'
Making all in bootstrap-scripts
make[3]: Entering directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity/libexec/bootstrap-scripts'
Making all in environment
make[4]: Entering directory '/home/niktur/SINGULARITY/source/git/18.06.2017/singularity/libexec/bootstrap-scripts/environment'
install -d -m 0755 newroot/.singularity.d
install -d -m 0755 newroot/.singularity.d/env
install -d -m 0755 newroot/.singularity.d/actions
install -d -m 0755 newroot/.singularity.d/libs
install -d -m 0755 newroot/dev
install -d -m 0755 newroot/etc
install -d -m 0755 newroot/home
install -d -m 0755 newroot/proc
install -d -m 0755 newroot/root
install -d -m 0755 newroot/sys
install -d -m 0755 newroot/tmp
install -d -m 0755 newroot/var
install -d -m 0755 newroot/var/tmp
install -m 0755 /dev/null newroot/etc/hosts
install -m 0755 /dev/null newroot/etc/resolv.conf
install -m 0755 runscript newroot/.singularity.d/
install -m 0755 exec newroot/.singularity.d/actions/
install -m 0755 run newroot/.singularity.d/actions/
install -m 0755 shell newroot/.singularity.d/actions/
install -m 0755 test newroot/.singularity.d/actions/
install -m 0755 01-base.sh newroot/.singularity.d/env/
install -m 0755 90-environment.sh newroot/.singularity.d/env/
install -m 0755 99-base.sh newroot/.singularity.d/env/
ln -sf env/90-environment.sh newroot/.singularity.d/environment
ln -sf .singularity.d/runscript newroot/singularity
ln -sf .singularity.d/actions/exec newroot/.exec
ln -sf .singularity.d/actions/run newroot/.run
ln -sf .singularity.d/actions/shell newroot/.shell
ln -sf .singularity.d/actions/test newroot/.shell
cd newroot; tar czf ../environment.tar . --owner=0 --group=0
rm -rf newroot
...

**Comment by gmkurtzer** [comment]
@niktur, thanks for letting us know!

@vsoch, do we need to do the `os.mkdir(SINGULARITY_CACHE)` at https://github.com/singularityware/singularity/blob/master/libexec/python/defaults.py#L110? We shouldn't create the cache directory until we need to (this is getting called indirectly from `etc/configure_transform.py`.

Thanks!

**Comment by vsoch** [comment]
huh, have we seen this error before? It's a one time thing, so it would be easiest to disable the cache by exporting that environment variable (goes to tmp) unless there is some other way to detect this step?

**Comment by gmkurtzer** [comment]
Yes, I agree that we can work around it, but I don't think we should create the cache parent directory just because we resolved where the cache would be *iff* we were to use it. I think it makes more sense to create the directories only when they are necessary.

Thoughts?

**Comment by vsoch** [comment]
I agree, but how would the trigger work to create / not create? If the user disables cache, then we still need to have files put somewhere. We could have a more global `SINGULARITY_INSTALL` environment variable that would just skip the defaults entirely.

**Comment by gmkurtzer** [comment]
Can't we just not create the ~/.singularity at that step? Just remove those 2 lines. When we need to write/cache a file, we can check and create the directories then.

**Comment by vsoch** [comment]
the environment variables are loaded (triggering the creation) when you import the defaults file. An easier workaround would be to use simple functions that don't rely on importing that, so the installation scripts are kept isolated from the runtime. Does that make sense?

**Comment by vsoch** [comment]
The reason it happens is this import:

```
from sutils import (
    get_fullpath,
    read_file,
    write_file
)
```
so we could just have those functions defined, simply, within the same file to not need to do that.

**Comment by vsoch** [comment]
if you tell me where to PR I can do this quickly!

**Comment by gmkurtzer** [comment]
Oh, it isn't worth even submitting a PR. I removed those lines, and ran through the tests. It seems the necessary cache directories are indeed being created on demand (including the parents) so I'll go ahead and commit that and if you see an issue with it, we can revert or fix as needed.

Thanks!

**Comment by vsoch** [comment]
so... how is the cache created now?

**Comment by vsoch** [comment]
ok, just checked on this! We are ok because I do [create the folders](https://github.com/singularityware/singularity/blob/cc8bfb2dc0024c9ca1d3f47d54e56cbe504774dd/libexec/python/sutils.py#L266) (if not existing) in the function to get the cache. I thought there was a specific reason I created it on init, and I suppose we will figure that out if a bug is triggered later, heh. I think it might just be good :)

@gmkurtzer one thing I noticed, when I was compiling the version above, I saw this warning several times:

```
util/util.c: In function ‘envclean’:
util/util.c:342:9: warning: ‘tok’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         unsetenv(key);
         ^
```

I don't remember it being there before - thanks to the logger it now prints in purple for me :)

**Comment by gmkurtzer** [comment]
Ahh, nice catch! Fixed and thanks!

**Comment by dtrudg** [comment]
@vsoch - looks like this one was fixed. Okay to close?

**Comment by dtrudg** [comment]
Closing - please don't hesitate to reopen if needed.
