### ISSUE TITLE
Binding a directory during bootstrap

### ISSUE THREAD

**Issue by DeepHorizons** [apptainer/singularity#766]
Is there a way to bind directories during the bootstrap process (Or allow the --nv option)? I'm trying to build some packages that need to link against some drivers and it would be nice to not bake in drivers.

**Comment by GodloveD** [comment]
Heya @DeepHorizons sorry for the long delay.  I just happened to be commenting on #915 and then I saw this issue too.  

As I said in that thread, you can bind host directories into the container at bootstrap time in the `%setup` section like so:
```
%setup
    mount --no-mtab --rbind "/host/dir" "$SINGULARITY_ROOTFS/container/dir"
```
Hope that helps and is not (as my Dad used to say) "a day late and a dollar short".

**Comment by dtrudg** [comment]
Hi @DeepHorizons - did @GodloveD's suggestion solve your issue? If so is it okay to close this issue? If not, let us know if you need more assistance.

**Comment by bauerm97** [comment]
Closing, if you would like to propose a new feature to transparently support this then please open a new issue and tag it as `FeatureRequest`
