### ISSUE TITLE
When does %files run in bootstrap?

### ISSUE THREAD

**Issue by lyon-fnal** [apptainer/singularity#769]
## Version of Singularity:

2.3

### Expected behavior

Files in the `%files` section get copied before `%post` runs.

### Actual behavior

Files in `%files` are not copied in time for `%post`. Commands in `%post` that are expecting those files fail with file not found. 

### Comments

The documentation (http://singularity.lbl.gov/bootstrap-image) doesn't say when files in `%files` get copied. I was assuming it was early in the bootstrap process (e.g. after `%setup` but before `%post`). It looks like it's after `%post`. Can the documentation be updated to make this clear -- or better, can the behavior change to run as suggested here? That way I won't need to do these copies within `%setup`. Thanks!

**Comment by vsoch** [comment]
hey @lyon-fnal ! The files actually get copied after, and we are totally on the same page that this needs fixing, I think this is an easy milestone for 2.4. See the [issue here](https://github.com/singularityware/singularity/issues/674) for our previous discussion. As a workaround, you can create a `%setup` section and in it copy files from your host to `$SINGULARITY_ROOTFS`. Give that a go for now, and we will keep this open and add to 2.4 milestone!

**Comment by vsoch** [comment]
oh, and sure thing I can update the docs :)

**Comment by vsoch** [comment]
okey doke, I fixed it in three places (the page you referenced, content, and quickstart). Let me know if it looks good! http://singularity.lbl.gov/bootstrap-image#files

**Comment by lyon-fnal** [comment]
Awesome! Thanks for the super-quick response and for updating the documentation (looks great). Sorry I didn't see #674 . That issue is the right place to continue. Thanks again! -- Adam

**Comment by vsoch** [comment]
:smile:
