### ISSUE TITLE
bootstrap of fedora fails on el6

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#77]
The change to maybe use dnf instead of yum has broken bootstrapping of fedora on el6, which now fails like this:

```
++ Bootstrap
++ eval 'dnf --noplugins -c /mnt//etc/bootstrap-yum.conf --tolerant --installroot /mnt -y install /etc/redhat-release coreutils '
+++ dnf --noplugins -c /mnt//etc/bootstrap-yum.conf --tolerant --installroot /mnt -y install /etc/redhat-release coreutils
Config error: Read-only file system: '/var/log/dnf.log'
++ exit 1
```

I'm confused and haven't debugged it yet, but will back out part of the change.  Just recording it here to be fixed properly.

**Comment by gmkurtzer** [comment]
What version of Singularity are you using? It still seems to be using the old mount point /mnt instead of /var/singularity/mnt. I think I already fixed a bug where the singularity container's /var was ending up as read only... But... not during Bootstrap. Just to be sure can you try two things...
1. Upgrade or confirm that you are running the latest from the master branch.
2. Try to do the same command by hand:

```
$ sudo singularity mount container.img /mnt
# dnf --noplugins -c /mnt//etc/bootstrap-yum.conf --tolerant --installroot /mnt -y install /etc/redhat-release coreutils
```

**Comment by loveshack** [comment]
You wrote: 

> What version of Singularity are you using?

Oops, sorry, 2.0, yes.

> It still seems to be using
> the old mount point /mnt instead of /var/singularity/mnt. I think I
> already fixed a bug where the singularity container's /var was ending
> up as read only... But... not during Bootstrap. Just to be sure can
> you try two things...

Any idea which change fixed it?

> 1. Upgrade or confirm that you are running the latest from the master branch.

OK, I'll try with master when I get a chance.

> 1. Try to do the same command by hand:
> 
> ```
> $ sudo singularity mount container.img /mnt
> # dnf --noplugins -c /mnt//etc/bootstrap-yum.conf --tolerant
> --installroot /mnt -y install /etc/redhat-release coreutils
> ```

It won't work because dnf isn't on the host.  That's one of the things
puzzling me!

**Comment by gmkurtzer** [comment]
@loveshack Can you check to see if [master 018cfab] fixes this?

Thanks!

**Comment by gmkurtzer** [comment]
@loveshack ping!

**Comment by loveshack** [comment]
I think the dnf problem will have been due to having a "dnf" directory
in the directory I was using for testing and that should have been fixed
by my singularity_which (?) fix.

**Comment by gmkurtzer** [comment]
Ok, cool. I will close this issue then and cross fingers that it is indeed resolved. If you see any further issues, feel free to comment on this thread or open another issue.

Thanks!
