### ISSUE TITLE
add interpreter check on runscript during bootstrap

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#772]
If the user has provided a runscript with an interpreter specified, we shouldn't have !#/bin/sh also at the top. For example this:

```
Bootstrap: docker
From: centos:7

%runscript
#!/usr/bin/env python
print('hello')
```

should not return this:

```
singularity inspect -r centos.img 
#!/bin/sh 
#!/usr/bin/env python
print('hello')
```

but instead this:

```
singularity inspect -r centos.img 
#!/usr/bin/env python
print('hello')
```

**Comment by vsoch** [comment]
and I'll add this note here too - if it's the case that it has to be /bin/sh, the workaround would be having the shell execute the script (with the correct interpreter)

```
%post
...
mkdir /code
 
%runscript
exec /opt/anaconda3/python /code/run.py
 
%files
run.py /code/run.py
```

**Comment by dtrudg** [comment]
In the current `master` this is working as requested:

```
04:16 PM $ singularity version
3.5.2+266-gd3586d1de

04:15 PM $ singularity inspect -r centos.sif 
#!/usr/bin/env python

print('hello')
```
