### ISSUE TITLE
Singularity-Hub container cannot be pulled. Naming issue?

### ISSUE THREAD

**Issue by katakombi** [apptainer/singularity#778]
## Version of Singularity: 

2.3.1

### Expected behavior

Run 
singularity pull shub://katakombi/multinode_sshwrapper

DL container

### Actual behavior
singularity -v pull shub://katakombi/multinode_sshwrapper
Increasing verbosity level (2)
Singularity version: 2.3.1-dist
Exec'ing: /usr/lib/x86_64-linux-gnu/singularity/cli/pull.exec
ERROR Error downloading None. Do you have permission to write to /home/stefan?

### Steps to reproduce behavior

See above.
Container seems fine, you can get it via
singularity pull shub://1508

**Comment by vsoch** [comment]
hey @katakombi ! I just tried this out, and I can't reproduce the error:

```
singularity pull shub://katakombi/multinode_sshwrapper
Progress |===================================| 100.0% 
Done. Container is at: ./katakombi-multinode_sshwrapper-master.img
vanessa@vanessa-ThinkPad-T460s:~/Desktop$ ./katakombi-multinode_sshwrapper-master.img 
### Setting up shell environment ...
```
(and yes, I made the mistake of running it and out spat some MPI stuffs, I panicked and control-C'd, haha). Could you please add the entire `--debug` output for your command so I can take a look?

**Comment by katakombi** [comment]
Hi Vanessa,

 this is weird! Now the issue seems to have gone...
I guess it was a temporary issue, or a black out of mine.
However, I tried the pull from two different hosts independently and received the same error.

PS: nothing evil should happen, the default run just executes an mpi-threaded single node run of gromacs inside your containers /tmp dir :)

Well... since it is gone, and I have no clue how to reproduce the error, I assume you can close the issue...

**Comment by vsoch** [comment]
for sanity check, how about we try again tomorrow? And what does the container do /how do I use it? Now that it's on my desktop, I think I'd like to play with it :)

**Comment by katakombi** [comment]
Hi vanessa,

The container maintains its own MPI is meant to be used on a multi node system operating via keyless SSH login. For that a SSH wrapper script is included to invoke the neighbour node MPI threads. Actually I plan to submit this for your contest ;)

There's a description of the container and how to use it:
https://github.com/katakombi/multinode_sshwrapper
It would be nice if singularity hub could transparently pull the README.md or point to it as container description :)

Ok, lets test tomorrow again...

**Comment by serious-steve** [comment]
Hi vanessa, 

 I see no troubles any longer. Maybe just close the issue.
And BTW: the container had some bugs now it should work according to the README.md
You will need a multi host system with keyless SSH on two nodes that have singularity installed.

**Comment by vsoch** [comment]
Woot! Alright closing issue - here is the link to the page with the form if you need it https://containers-ftw.github.io/competitions/2017/pearc.html. Can't wait to play around with it!

And with regard for the README - we can link to it from shub via the Github repo, but it's not as clear or direct as having it right there! If you can imagine some "containers-ftw" site (that would eventually exist) that can let you select (and display the README and details for a repo) automatically, that's the kind of thing I'd like to make :) But likely after singularity-hub and the registry are mostly done. Closing issue!
