### ISSUE TITLE
Adding arch support

### ISSUE THREAD

**Issue by remyd1** [apptainer/singularity#780]
## Version of Singularity:

Any

### Expected behavior

To be able to `debootstrap` any _arm_ image with the singularity bootstrap script.

### Actual behavior

It fails, by searching an arch which does not exist (eg: armv7).

### Steps to reproduce behavior

Try to Bootstrap a raspian image on a raspberry PI.
This [PR](https://github.com/singularityware/singularity/pull/768) fixes this issue.

**Comment by gmkurtzer** [comment]
Referenced PR has been merged into development branch. Thank you!

**Comment by dtrudg** [comment]
Closing this as the referenced PR was merged - let us know if any further issues. Thanks!
