### ISSUE TITLE
Adding `-V` option to export all env var to the container

### ISSUE THREAD

**Issue by remyd1** [apptainer/singularity#786]
Hi

This is not a bug but a feature request.

It would be great to add a way to export all environment variables from the local session on host to the running container like the `-V` option in SGE/qsub.
It is already possible to export an env var with `SINGULARITYENV_[...] singularity ...`
With a simple for loop, it is possible to parse all env vars and then concatenate all these vars before launching singularity but is is a bit complicated for a basic user.

Best regards
Rémy

**Comment by dtrudg** [comment]
I don't believe this is necessary (any more?). Here's a diff for the environment between host and container for me on 3.6.4:

```diff
dave@ythel~/G/singularity> diff container host
15d14
< LD_LIBRARY_PATH=/.singularity.d/libs
21,23c20,21
< PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
< PROMPT_COMMAND=PS1="Singularity> "; unset PROMPT_COMMAND
< PS1=Singularity> 
---
> PATH=/home/dave/go/bin:/opt/go/bin:/home/dave/bin:/home/dave/.local/bin:/home/dave/.dotfiles/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/pkg/bin:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin:/home/dave/.npm-packages/bin
> PWD=/home/dave/Git_hpcng/singularity
30,33d27
< SINGULARITY_COMMAND=run
< SINGULARITY_CONTAINER=/home/dave/.singularity/cache/oci-tmp/185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
< SINGULARITY_ENVIRONMENT=/.singularity.d/env/91-environment.sh
< SINGULARITY_NAME=185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
38d31
< USER_PATH=/home/dave/go/bin:/opt/go/bin:/home/dave/bin:/home/dave/.local/bin:/home/dave/.dotfiles/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/pkg/bin:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin:/home/dave/.npm-packages/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
```

Almost everything from the host enters the container.  It's essentially just `PATH` `PS1` `LD_LIBRARY_PATH` that differ.
