### ISSUE TITLE
CI not properly testing SLURM plugin

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#787]
## Version of Singularity:

Potentially all versions of Singularity?

### Expected behavior

Build fails if SLURM plugin isn't building

### Actual behavior

Build doesn't fail if SLURM plugin isn't building. See #701, #783. This should have been caught before the update to 2.3 if our CI was catching this errors.

To fix, we could add a SLURM test into /tests/ directory.

**Comment by dtrudg** [comment]
Closing this - plugin not now included. See #1231
