### ISSUE TITLE
Ensure Singularity respects TMPDIR variable or allow Docker image cache to be specified in cfg file

### ISSUE THREAD

**Issue by willfurnass** [apptainer/singularity#791]
## Version of Singularity: 

2.3.1

### Desired behavior

I'd like if if 

    TMPDIR=/scratch singularity run docker://debian:latest

results in the Docker image layers being written to `/scratch/.singularity-runtime.???/`

### Actual behavior

Docker image layers written to `/tmp/.singularity-runtime.???/`

On our HPC cluster nodes `/scratch` is much larger than `/tmp` so we'd like to be able to customise where Singularity temporarily stores Docker images.

**Comment by gmkurtzer** [comment]
This may not be something you want on a network scratch share, so things may break. Additionally, this will require a lot of small file IO which may not be good for a scratch file system.

I would recommend to import from docker and put into a Singularity image instead. That is more optimal for shared file systems and a better utilization of resources.

With that said, I'm not disagreeing with your request. It can/should be supported.

**Comment by vsoch** [comment]
Is this not customizable based on `SINGULARITY_CACHEDIR` ? Do you mean the root of the image itself, or the docker layers?

**Comment by gmkurtzer** [comment]
Actually, good call @vsoch, I forgot about that. You can influence where things get cached locally via `SINGULARITY_LOCALCACHEDIR`.

**Comment by vsoch** [comment]
and for just the docker python bits, you can use `SINGULARITY_CACHEDIR`. If that doesn't work there is an override from the calling function that would be a bug we should look into. Here is where the setting is found (and other variants you can use to disable and use tmp, etc.) https://github.com/singularityware/singularity/blob/adf5259ac94d7b213c649f073dcda32459b0c8b7/libexec/python/defaults.py#L107

**Comment by brianv0** [comment]
Hi, I'd like to propose some default behaviors:

1. If `~/.singularity` does not exist, _do not try to create it_. Trying to create ~/.singularity assumes that the user can write to their home directory. This might not be the case, e.g. running in a batch system on a production account or in the grid with a home directory in afs or something. Similarly, if it is afs or something, it's quite easy to blow out your allocation with a large container

2. If `~/.singularity` does not exist, by default, cache downloaded images (e.g. `shub://`) to a well-defined location in /tmp (`/tmp/singularity_u$(id -u)`) Similar to the scheme grid stuff uses to store proxy credentials (like `/tmp/x509up_u$(id -u)`) or:


```
cachedir = os.path.join(tempfile.gettempdir(), "singularity_u{}".format(os.getuid()))  # geteuid?
os.mkdir(cachedir, 0o700)
```

More succinctly: don't use ~/.singularity as the default cache location (and don't try to create it), use a tempdir. For places where `tempfile.gettempdir()` might not be desirable, maybe make this configurable in some way for sys admins?

**Comment by gmkurtzer** [comment]
Hi @brianv0,

I do agree with your second point because it allows the operating system management of `/tmp` to clean stale files, as opposed to subjecting them to bitrot in a hidden file within the user's home directory.

Greg

**Comment by dtrudg** [comment]
I don't believe this issue is relevant now, as with 3.x we have an explicitly managed cache (by default in home directory) where docker layers will be pulled. If you have a concern about the functionality in the latest version of Singularity please could you open a new issue? Many thanks!
