### ISSUE TITLE
Mounting an image is failed

### ISSUE THREAD

**Issue by yangyang-zhang** [apptainer/singularity#792]
## Version of Singularity:
The version is 2.3.1

### Expected behavior
$ singularity mount container.img /tmp/container/
container.img is mounted at: /tmp/container/
Spawning a new shell in this namespace, to unmount, exit shell
Singularity: \w> df
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/loop0       1531760      1172   1451948   1% /tmp/container
Singularity: \w> cd /tmp/container
Singularity: \w> ls -a
.  ..  lost+found

### Actual behavior
[root@slave2 ~]# singularity mount container.img /tmp/container/
ERROR  : Exec failed: /tmp/container/: Permission denied
ABORT  : Retval = 255

### Steps to reproduce behavior
[root@slave2 ~]# singularity bootstrap container.img  singularity-2.3.1/examples/ubuntu/Singularity
[root@slave2 ~]# chmod -R 777 /tmp

**Comment by gmkurtzer** [comment]
Can you please check your version of Singularity, that is not the output of 2.3.1 and the options have changed. This is what you should see:

```
$ singularity --version
2.3.1-master.gd7dcaf5
gmk@gmkdev2:~$ singularity mount container.img /tmp/container/
ERROR  : Exec failed: /tmp/container/: Permission denied
ABORT  : Retval = 255
gmk@gmkdev2:~$ singularity mount container.img
container.img is mounted at: /usr/local/var/singularity/mnt/container

Singularity> ls -l /usr/local/var/singularity/mnt/container
total 92
...
```

**Comment by yangyang-zhang** [comment]
you are right，according to the  link is http://singularity.lbl.gov/image-content   ， i have a question，
how should  i change the default mount directory ?

**Comment by dtrudg** [comment]
Hello @yangyang-zhang - the mount location is controlled by the to `--localstatedir` setting for `./configure` when Singularity is built - see https://singularity.lbl.gov/install-linux#prefix-in-special-places
