### ISSUE TITLE
Bootstrap: Mistyped Image Error Message

### ISSUE THREAD

**Issue by ax3l** [apptainer/singularity#794]
Hi there,

I just got stuck on an unclear error message while bootstrapping a singularity image from a dockerhub image.

## Version of Singularity:

$ singularity --version
2.3.1-dist

on Debian testing

### Expected behavior

Bootstrap from a non-existing docker image of an existing dockerhub account:
```
Bootstrap: docker
From: ax3l/typoseverywhereaaahhhaaands
```

should fail with a clear error message that the base docker image does not exist.

### Actual behavior

When bootstraping a singularity image from docker(hub) and mistyping the image name, the error should be more precise then throwing

```
ERROR Improperly formed manifest, layers or fsLayers must be present
```

([origin source code](https://github.com/singularityware/singularity/blob/master/libexec/python/docker/api.py))

### Steps to reproduce behavior

```bash
$ singularity create myImage.img

$ echo "Bootstrap: docker
From: ax3l/typoseverywhereaaahhhaaands" > Singularity

$ sudo singularity bootstrap myImage.img Singularity 
Sanitizing environment
Building from bootstrap definition recipe
Adding base Singularity environment to container
Docker image path: index.docker.io/ax3l/typoseverywhereaaahhhaaands:latest
ERROR Improperly formed manifest, layers or fsLayers must be present
```

**Comment by vsoch** [comment]
could you show me a link to the image on docker hub?

**Comment by ax3l** [comment]
@vsoch sorry, can't link an image since this issue is about the error message that singularity creates if *no image* is found for an *existing* dockerhub user :)

if a user did a typo like this, singularity does not say "image not found" but the confusing message above :)

Just type this into a bash:
```bash
singularity create myImage.img

echo "Bootstrap: docker
From: ax3l/typoseverywhereaaahhhaaands" > Singularity

sudo singularity bootstrap myImage.img Singularity 
```

(`typoseverywhereaaahhhaaands` is the *non-existing* docker image and `ax3l` is the *existing* dockerhub user)

**Comment by vsoch** [comment]
oh haha, /bonk yes I understand :) I agree we should have a different error message if the image doesn't exist, versus an (actual) properly formatted manifest. I'll put in a fix to this later today!

**Comment by vsoch** [comment]
ok so it looks like the root of the error (when it first triggers) is obtaining the manifest: docker reports the non existing image as needing authentication:

```
DEBUG Headers found: Content-Type,Authorization,Accept
DEBUG Http Error with code 401
ERROR UNAUTHORIZED: authentication required
```
What I can do is add a message to the user to check the name of the image, because it could also be confusing to just say it's unauthorized. Would that be reasonable?

**Comment by ax3l** [comment]
yes sounds great!

they probably report it as authentication error because it *could* be a private image (but they don't want people to check on return type if a private repo exists). Github does it the same way, but always gives a more reasonable 404 :D
