### ISSUE TITLE
`/environment` not honored in Singularity 2.3

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#799]
## Version of Singularity:

2.3.1

### Expected behavior

`/environment` file should be honored

### Actual behavior

`/environment` file is not honored

### Steps to reproduce behavior

Consider the following definition file:
```
BootStrap: docker
From: ubuntu:latest   # This is a comment

%post
    echo "export FOO=bar" > /environment
```
If you use it to `create` and `bootstrap` a file in Singularity 2.2.1 and then execute the following command you can see the env var `FOO`
```
$ singularity exec some.img printenv | grep FOO
FOO=bar
```
But if you do the same thing in 2.3.1...
```
$ singularity exec some.img printenv | grep FOO
```
No `FOO`!  😢

**Comment by vsoch** [comment]
@GodloveD fixed this loooong ago!
