### ISSUE TITLE
Can Singularity fully encapsulate X11?

### ISSUE THREAD

**Issue by aday00** [apptainer/singularity#804]
Dear Singularity gurus,

Thanks for the Singularity tool, it's very useful, and we're trying to move away from Docker.  Can Singularity fully encapsulate X11?

I have an X application with automated button clicks etc.  A Docker instance runs its own X11 independent of other Dockers, and each Docker instance does this:
```
export DISPLAY=:0.0
Xvfb $DISPLAY -pixdepths 32 -screen 0 1280x1024x24
startxfce4 &
...
```

That works fine with Docker, but with Singularity I get this error:
`/usr/bin/startxfce4: X server already running on display :0.0`

It seems like Singularity isn't fully encapsulating X, so multiple Singularity instances on the same compute node collide in X.  It would be better to not use X at all, automating button clicks is not a good way to go, but this gets a one-off data preprocessing step done with unmodified external code.

Thanks for your consideration,
-A

**Comment by vsoch** [comment]
I might be totally wrong about this, but my instinct is that singularity would share the same display as the host, so the error message is saying that it's already running! What you could try is to remove opening the new displays (and having them share, which may work for your application) or if you want to isolate, try running the container with `--containall` For example, here is standard shell:

```
$ singularity shell ubuntu.img
Singularity ubuntu:~> echo $DISPLAY
:0
Singularity ubuntu:~> exit
exit
```
Note that it's the same  on my host. And here is with containall:
```
singularity shell --containall ubuntu.img
Singularity: Invoking an interactive shell within container...

Singularity ubuntu:~> echo $DISPLAY

Singularity ubuntu:~> 
```
Notice the second is empty! So maybe one of those tricks will work?

**Comment by gmkurtzer** [comment]
Yes, as @vsoch mentioned, X11 should be supported in it's default running configuration. I am going to close this, but if you find any issues, please comment and we can reopen it. Thanks!
