### ISSUE TITLE
Failed to sudo make install in cluster

### ISSUE THREAD

**Issue by MZreal** [apptainer/singularity#806]
I used the commands below to install singularity on one node in a cluster
git clone https://github.com/singularityware/singularity.git
cd singularity
./autogen.sh
./configure --prefix=/usr/local
make
sudo make install

In the last command "sudo make install" it returned
Making install in bin
/bin/sh: line 20 : cd: bin: Not a directory
make: *** [install-recursive] Error 1

But I can install singularity using these commands in my own desktop.

**Comment by vsoch** [comment]
Hey @MZreal. Do you have sudo permissions on your cluster?

**Comment by MZreal** [comment]
Hi @vsoch, I have sudo permission only on the node that I want to install  singularity.
I don't have sudo on the whole cluster (the other nodes).

**Comment by GodloveD** [comment]
Are you trying to install on a network file system?  Perhaps one that has root perms disabled?

**Comment by vsoch** [comment]
Naively looking at the error, it looks like it thinks bin is something else (not a directory). Do you have anything in your `.bashrc` or startup profile that edits what "bin" equates to?

**Comment by dtrudg** [comment]
Closing this as the has been no follow-up. Please don't hesititate to reopen if you still have a problem using Singularity 2.4.x
