### ISSUE TITLE
Problem of installing OFED in Singularity

### ISSUE THREAD

**Issue by renganxu** [apptainer/singularity#809]
I am trying to use Singularity to run a program on our cluster where all nodes are connected by EDR Infiniband. All nodes in our cluster have RHEL 7.2 OS. But for some reason, the program could not run successfully on RHEL, so I want to create a Singularity container with Ubuntu 16.04 OS and run the program on Ubuntu with Singularity.
 
The issue right now is that I cannot install Mellanox OFED driver in the Singularity container. Because the output of "uname -a" still shows RHEL kernel within the container, OFED package could not detect Ubuntu OS, so it cannot install successfully.

## Version of Singularity:

2.3.1

### Expected behavior

We should be able to install Mellanox OFED driver successfully.

### Actual behavior

When I install OFED within container, it has the following messages:
 
This program will install the MLNX_OFED_LINUX package on your machine.
Note that all other Mellanox, OEM, OFED, or Distribution IB packages will be removed.
Do you want to continue?[y/N]:y
 
Checking SW Requirements...
 
One or more required packages for installing MLNX_OFED are missing.
/lib/modules/3.10.0-327.el7.x86_64/build/scripts is required for the Installation.
Attempting to install the following missing packages:
**linux-headers-3.10.0-327.el7.x86_64**
Failed command: apt-get install -y linux-headers-3.10.0-327.el7.x86_64

### Steps to reproduce behavior

singularity create ubuntu-test.img
singularity bootstrap ubuntu-test.img ubuntu.def
singularity exec -w ubuntu-test.img apt-get install build-essential
singularity shell -w ubuntu-test.img
Singularity ubuntu-test.img > apt-get install lsb-release
Singularity ubuntu-test.img > wget http://www.mellanox.com/downloads/ofed/MLNX_OFED-3.3-1.0.4.0/MLNX_OFED_LINUX-3.3-1.0.4.0-ubuntu16.04-x86_64.tgz
Singularity ubuntu-test.img > tar xzfv MLNX_OFED_LINUX-3.3-1.0.4.0-ubuntu16.04-x86_64.tgz
Singularity ubuntu-test.img > cd MLNX_OFED_LINUX-3.3-1.0.4.0-ubuntu16.04-x86_64
Singularity ubuntu-test.img > ./mlnxofedinstall

Regards,
Rengan

**Comment by jmstover** [comment]
It should be something like `./mlnxofedinstall -k [Kernel Version]`
So... `./mlnxofedinstall -k 3.10.16-123.10.9_abc`

Just put in the kernel version of what version you want to install against instead of using `uname -r`

-J

**Comment by renganxu** [comment]
@jmstover I installed Ubuntu kernel 4.10.0-26 and then use the command
`./mlnxofedinstall -k 4.10.0-26 -s /usr/src/linux-headers-4.10.0-26/`

but it still failed. The output is:
Checking SW Requirements...
Removing old packages...
Installing new packages
Installing ofed-scripts-3.3...
Installing mlnx-ofed-kernel-utils-3.3...
Installing mlnx-ofed-kernel-dkms-3.3...

Error: mlnx-ofed-kernel-dkms installation failed!
Collecting debug info...
See:
        /tmp/OFED.2916.logs/mlnx-ofed-kernel-dkms.debinstall.log
Removing newly installed packages...

In the log file, the output is:
1 /usr/bin/dpkg -i --force-confnew --force-confmiss /cm/shared/scratch/rengan/container/Ubuntu_Caffe2/MLNX_OFED_LINUX-3.3-1.0.4.0-ubuntu16.04-x86_64/DEBS/mlnx-ofed-kernel-dkms_    3.3-OFED.3.3.1.0.4.1.gcd30181_all.deb
  2 Selecting previously unselected package mlnx-ofed-kernel-dkms.
  3 (Reading database ... 41227 files and directories currently installed.)
  4 Preparing to unpack .../mlnx-ofed-kernel-dkms_3.3-OFED.3.3.1.0.4.1.gcd30181_all.deb ...
  5 Unpacking mlnx-ofed-kernel-dkms (3.3-OFED.3.3.1.0.4.1.gcd30181) ...
  6 Setting up mlnx-ofed-kernel-dkms (3.3-OFED.3.3.1.0.4.1.gcd30181) ...
  7 Loading new mlnx-ofed-kernel-3.3 DKMS files...
  8 First Installation: checking all kernels...
  9 dpkg: warning: version '*-*' has bad syntax: version number does not start with digit
 10 ** It is likely that 3.10.0-327.el7.x86_64 belongs to a chroot's host **
 11 Building for architecture x86_64
 12
 13
 14
 15 ---------------- START OF DEBUG INFO -------------------
 16 Install command: ./mlnxofedinstall -k 4.10.0-26 -s /usr/src/linux-headers-4.10.0-26/
 17
 18 Vars dump:
 19 - ofedlogs: /tmp/OFED.184609.logs
 20 - MLNX_OFED_LINUX_VERSION: 3.3-1.0.4.0
 21 - MLNX_OFED_ARCH: x86_64
 22 - MLNX_OFED_DISTRO: ubuntu16.04
 23 - distro: ubuntu16.04
 24 - arch: x86_64
 25 - kernel: 4.10.0-26
 26 - config: /tmp/ofed.conf
 27 - update_firmware: 1
 28
 29 Setup info:
 30
 31 - uname -r: 3.10.0-327.el7.x86_64
 32
 33 - uname -m: x86_64
 34
 35 - lsb_release -a: No LSB modules are available.
 36 Distributor ID: Ubuntu
 37 Description:    Ubuntu 16.04.2 LTS
 38 Release:        16.04
 39 Codename:       xenial
 40
 41 - cat /etc/issue: Ubuntu 16.04.2 LTS \n \l
 42
 43
 44 - cat /proc/version: Linux version 3.10.0-327.el7.x86_64 (mockbuild@x86-034.build.eng.bos.redhat.com) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Oct 29     17:29:29 EDT 2015
......

It seems OFED still thinks the current kernel is RHEL kernel, but Ubuntu kernel. If the container OS is different from host OS, have you successfully installed OFED driver? 

Regards,
Rengan

**Comment by renganxu** [comment]
Hi @gmkurtzer @vsoch , do you have any solutions to my post?

**Comment by vsoch** [comment]
Is the issue building the container on a RHEL host? Is there any reason you can't build it elsewhere?

**Comment by renganxu** [comment]
Yes this is the issue of building Ubuntu container on RHEL host. I didn't try other hosts because all nodes in my cluster are RHEL OS.

**Comment by vsoch** [comment]
Is there any reason you need to build it on the cluster if you are having this issue? Can you build somewhere else and move / use on the cluster?

**Comment by renganxu** [comment]
Good point. I will try to find an Ubuntu host and build the container there, and then try to use on the cluster. Thanks for the suggestion.

**Comment by vsoch** [comment]
sure thing! Let's start with that, and if it doesn't work, we can think of a way to better isolate from the host. It should be the case, given using Singularity, that you can build on any host and then use on your cluster.

**Comment by dtrudg** [comment]
Hi @hfutxrg - were you able to resolve your OFED issues - if so can we close this issue? If not - please let us know if you need further assistance. Thanks.

**Comment by dtrudg** [comment]
Hi all - I'm going to close this issue as there was no reply since 2018. If you still have an issue on the latest version of Singularity please feel free to re-open or start a new issue. Thanks!
