### ISSUE TITLE
RFE: provide bash command completion

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#81]
Perhaps someone can do it before I find time.

**Comment by gmkurtzer** [comment]
Good thinking! I'm not familiar with Bash completion so I'll label this as
"help wanted" when I get to a computer.

## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by gmkurtzer** [comment]
This has been done. Closing legacy ticket.
