### ISSUE TITLE
Updating SLRUM plugin to v2.3.1 Singularity API

### ISSUE THREAD

**Issue by votavap** [apptainer/singularity#811]
## Version of Singularity:

2.3.1

### Expected behavior

Running integration with SLURM, such as:
`srun --singularity-image=<image> [ params ]`

### Actual behavior
While the plugin loads ok, at runtime, it can't resolve some of the symbols that are referenced in the shared library and exists with:

`slurmstepd: [17.0]: symbol lookup error: /usr/local/lib/slurm/singularity.so: undefined symbol: singularity_rootfs_init`

There seem to be number of calls within src/slurm/singularity.c that reference functions that were changed in v2.3 of Singularity and as a result can't be resolved at runtime through the shared libraries.

### Steps to reproduce behavior

- Build Singularity with --with-slurm option
- Try to run any singularity image with SLURM:
`srun --singularity-image=<image> [ params ]`

Tested with Singularity 2.3.1 (devel) and SLURM 17.02.6

**Comment by jscook2345** [comment]
@votavap 

Sounds like this was already fixed and merged. Thanks!
