### ISSUE TITLE
Local container cache

### ISSUE THREAD

**Issue by bjlittle** [apptainer/singularity#812]
Hi Singularity devs!

Singularity it pretty awesome, so thank you.

I have a pretty simple question (rather than an issue), so I thought I'd chance my luck by asking it here ... if there is a better forum to do that in, then please advise.

Is there a way in which it is possible to reference a container image without giving an explicit/relative path, or having the image in the current directory i.e.

`> singularity run container.img`

This is opposed to doing:

`> singularity run /this/is/the/absolute/path/to/my/container.img`

or

`> singularity run ../../container.img`

The use case is specifically for a production controlled environment on a HPC, where the singularity container images are in a *known* place. The HPC in question does not have access to external registries such as shub, dockerhub, http, https etc. The images would be deployed by a sys admin to a *known* directory by some means. This is a convenience that allows the users to reference *known* controlled production images, but not have to be explicit about where those images are i.e. singularity has the ability to do a fall back image lookup in a known registered local directory, say controlled by a specific environment variable or an entry in the singularity configuration file.

Clearly, if the image cannot be located, then it's an exception.

Would you see this as having any value to the community, other than for my particular use case?

Many thanks in advance.

**Comment by vsoch** [comment]
hey @bjlittle! The short answer is no, containers in the cache are only supported for singularity hub and docker layers. This exact functionality will be supported by the singularity registry (under development. For now, what about a workaround where you use modules to load images for users and manage paths?

**Comment by GodloveD** [comment]
+1 what @vsoch said.  Singularity containers are executables, so if you put them on the `$PATH` you should be able to access them from wherever. 

But what if you want to run some specific executable within a container and don't what to rely on a runscript?  One way you can do this is with a wrapper.  In fact you can write a very simple (only a few lines), generic wrapper script that will expose any executables inside the container to the outside environment.  Check out [lolcow-installer](https://github.com/GodloveD/lolcow-installer) for a silly example of how to make this happen.  I have installed many apps within containers in a production environment using this strategy.  And the end result is that user's run programs and never even realize they are containerized!

**Comment by bjlittle** [comment]
Thanks for the prompt responses! :beers: 

I think I've got enough to move forward, there are a couple of options to explore here.
