### ISSUE TITLE
Problem to get images from a non secure local registry.

### ISSUE THREAD

**Issue by GhisF** [apptainer/singularity#814]
## Version of Singularity:

2.3.1

### Expected behavior

I would like to use a Docker image stored on a non secure local Docker registry.
I expect to be able to provide an image name including the connection type
 `From: [http://]registry/namespace/repo:tag `

### Actual behavior

By default Singularity try to access to the local registry with a secure connection.
Adding a explicit http[s]:// before the image name, it is interpreted as a part of the image name and not as a protocol.

### Steps to reproduce behavior

if I use only the image name in the definition file
```From: localhost:5000/biocontainers/gatk:latest```

The log of the bootstrap process is:
```
VERBOSE2 SINGULARITY_CONTAINER found as docker://localhost:5000/biocontainers/gatk:latest
...
VERBOSE Docker image: localhost:5000/biocontainers/gatk:latest
...
VERBOSE Obtaining tags: https://localhost:5000/v2/biocontainers/gatk/tags/list
```

if we use an name with an explicit http:// in the definition file  (same with https://)
```From: http://localhost:5000/biocontainers/gatk:latest```

The log of the bootstrap process is:
```
VERBOSE2 SINGULARITY_CONTAINER found as docker://http://localhost:5000/biocontainers/gatk:latest
...
VERBOSE Docker image: http://localhost:5000/biocontainers/gatk:latest
...
VERBOSE Obtaining tags: https://index.docker.io/v2/library/http/tags/list
```

**Comment by vsoch** [comment]
hey @GhisF ! This was fixed - you can run the command with the variable `SINGULARITY_NOHTTPS` exported and it will use http. I'm going to close, please re-open if you have an issue!
