### ISSUE TITLE
documentation metacharacters are confusing

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#82]
It's confusing for the documentation to use (...) and [...] instead of the Unix-conventional [...] and <...> (or all-caps instead of <...>).  I don't remember seeing that convention elsewhere.

**Comment by gmkurtzer** [comment]
That is interesting, I've never really noticed the convention. If I am
understanding correctly, [...] is used for mandatorys  and <...> is used
for optionals?


## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by loveshack** [comment]
It's the other way round.  For instance

```
USAGE: singularity (options) help [command name]
```

in Unix man conventions might be

```
USAGE: singularity [options...] help <command name>
```

or, better, _commandname_ -- see man(1).  Some man pages (and GNU Info format) might use COMMAND-NAME for replacements.  I'd expect any of those to be widely recognized.

**Comment by gmkurtzer** [comment]
This motivated me not only to fix the metacharacters as you pointed out, but also refactor the help outputs which I have been meaning to do. Please check [master 39ff286].

Thanks!
