### ISSUE TITLE
[CHECKS]  checks need testing for CI

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#824]
Recently we added the basic architecture for checks, meaning a linting / filtering of an image on demand or bootstrap (see https://github.com/singularityware/singularity/pull/789). We now, in addition to specific checks (https://github.com/singularityware/singularity/issues/818), need general tests for the addition. Help wanted!

**Comment by dtrudg** [comment]
Per info on #825 checks are not part of singularity 3.x so there is currently not a need for CI.

**Comment by vsoch** [comment]
omg I opened this issue in 2017. Checks were never implemented, but it's still a pretty cool idea! But I might be a little biased :)
