### ISSUE TITLE
[CHECKS] add more checks!

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#825]
Inspiration from these sources

https://hackerone.com/ibb-python
https://internetbugbounty.org/

We would want (generally) tags that check security (for different OS) along with docker specific bugs. We will also eventually have checks for a particular file system structure, but those will come later.

**Comment by rabdill** [comment]
Could anyone point me toward where [checks](https://github.com/singularityware/singularity/pull/789) migrated to, if they still exist? The docs say to [look at check.sh](https://github.com/singularityware/singularity-userdocs/blame/2836b83a2348a058d3bf3961482d7a62c13be847/container_checks.rst#L76), but that file was [removed](https://github.com/singularityware/singularity/commit/4edd796233045f625c0d887d6511248bc214e99d#diff-e6a06432733b50931049727e254c0bd1) after release 2.6.0 and now I can't find where the new source might be.

I was going to submit a PR to fix the docs to point at the 2.6.0 version, but I realized it might still be around somewhere. Thanks.

**Comment by vsoch** [comment]
RIP checks, one of the many contributions I made that is being erased....

no idea, sorry friend.

**Comment by GodloveD** [comment]
I asked around a while ago on Slack if anyone was using checks and I just got silence.  So, unless there is some interest (maybe you can say there is) I don't think there is a plan to port them over to 3.0.

(Also note that master is 3.0 development.  checks still exist in 2.6.  Have a look at the 2.6.0 tag.)

@vsoch would you have any interest in helping to port this and other features (apps) over to 3.0?

**Comment by vsoch** [comment]
yes ! :heart:

**Comment by GodloveD** [comment]
Awesome!  Can use all the help we can get!  PR away!

**Comment by vsoch** [comment]
Can you point me to developer docs to get started? I did a PR a long time ago for Singularity Hub, but I still would need to figure out how to develop. I think I had suggested a Docker container but that wasn't liked, so I would rather start with your suggested development environment.

**Comment by GodloveD** [comment]
@bauerm97 are you able to point v in the right direction?

**Comment by bauerm97** [comment]
@vsoch Sure! The best place to initially look will be the `INSTALL.md` file. It should provide pretty decent instructions on how to get `golang` installed on your system, as well as where you need to clone the singularity repository.  Also it'll walk you through building singularity 3.0 using `mconfig`

As far as I understand checks, we'll need to add some new commands (`src/cmd/singularity/cli`) to actually run the checks. Also we'll need to add some stuff to the build command (I think, right??). If so, you'll want to talk with @ikaneshiro on where to interject there. He's driving the image build effort right now.

As far as apps go, I think @oddodaoddo had said he would be investigating porting apps to 3.0. He's trying to start getting into contributing to Singularity, so maybe you two could collaborate together on the Singularity slack channel on getting those features developed? I can provide as much development guidance as needed to help you guys understand the new code tree structure.

Also, sorry that it appears we haven't yet put some of those features you developed back into Singularity 3.0. Our intention was to develop out the core container runtime first and then start making sure that we get everything from the 2.x series implemented again. We're starting to get to the point where we can go back to 2.x and make sure we're hitting everything (check out the test porting PR's that @tri-adam has been working on and merging). We definitely want all of your work in 3.0 :)

**Comment by GodloveD** [comment]
Thanks @bauerm97!

**Comment by vsoch** [comment]
Cool thanks guys! I have definitely missed this github fun banter :) I think a good start would be to create developer docs, proper! Akin to https://github.com/singularityware/singularity-userdocs but something like `singularity-devdocs`. I would like to do this first, and @bauerm97 I'll use the good resources that you sent along. Does that seem like a good start? Do you like the name ok? --> https://github.com/singularityware/singularity-devdocs

**Comment by rabdill** [comment]
I'd also be glad to chip in, for what it's worth—I enjoyed working with Golang at a previous job, and I was initially looking for the checks because I wanted to add more.

**Comment by bauerm97** [comment]
@rabdill feel free to ping me on the Singularity slack channel (`mibauer`) and I can help point you (or really anybody that wants to contribute) to the right place.

@vsoch To be honest, I'm not sure we want a `singularityware/singularity-devdocs` repo right now. Pretty soon we'll be able to start generating a level of developer documentation using `go doc`, which should be able to guide developers in understanding what different functions and packages are responsible for. At some point, maybe there should just be a top-level `CONTRIBUTING.md` file in the `singularityware/singularity` repository which can contain a bit of generic info about different systems, who maintains what, the PR/review process, etc... Maybe once we have a ton of information it will make sense to move into its own repo?

**Comment by dtrudg** [comment]
Closing. If a checks infrastructure is a PR contribution to Singularity (perhaps a plugin) obviously this can/should be reopened.
