### ISSUE TITLE
can't bootstrap centos6 image on fedora 23

### ISSUE THREAD

**Issue by wresch** [apptainer/singularity#83]
Hi - 
I may be missing something basic but i thought i should be able to bootstrap a centos image on fedora. I build singularity from source based on the 2.x branch:

``` bash
cd singularity
git log -1
```

```
commit 240222d82bcac0359757952116c2823139860437
Author: Gregory M. Kurtzer <gmkurtzer@lbl.gov>
Date:   Wed Jun 1 07:12:38 2016 -0700
```

``` bash
git status
```

```
On branch 2.x
Your branch is up-to-date with 'origin/2.x'.
nothing to commit, working directory clean
```

I am on fedora 23:

``` bash
cat etc/redhat-release 
```

```
Fedora release 23 (Twenty Three)
```

and the build went without any problems.

I create a centos definition file and a image

``` bash
cat > centos6.def
DistType "redhat"
RELEASE=6
MirrorURL "http://mirror.centos.org/centos-${RELEASE}/${RELEASE}/os/\$basearch/"

Setup
Bootstrap

#InstallPkgs procps-ng vim-minimal

Cleanup
EOF

sudo singularity create centos6.img
```

```
Creating a sparse image with a maximum size of 1024MB...
Formatting image (/sbin/mkfs.ext4)
Done. Image can be found at: centos6.img
```

``` bash
sudo singularity -d -v bootstrap centos6.img centos6.def
```

```
[...snip...]
++ mkdir -p /mnt
+++ dirname /etc/bootstrap-yum.conf
++ YUM_CONF_DIRNAME=/etc
++ mkdir -m 0755 -p /mnt//etc
++ echo '[main]'
++ echo 'cachedir=/var/cache/yum/$basearch/$releasever'
++ echo keepcache=0
++ echo debuglevel=2
++ echo logfile=/var/log/yum.log
++ echo exactarch=1
++ echo obsoletes=1
++ echo gpgcheck=0
++ echo plugins=1
++ echo reposdir=0
++ echo ''
++ echo '[os-base]'
++ echo 'name=Linux $releasever - $basearch'
++ echo 'baseurl=http://mirror.centos.org/centos-6/6/os/$basearch/'
++ echo enabled=1
++ echo gpgcheck=0
++ return 0
++ Bootstrap
++ eval '/bin/yum -c /mnt//etc/bootstrap-yum.conf --tolerant --installroot /mnt -y install fedora-release redhat-release coreutils '
+++ /bin/yum -c /mnt//etc/bootstrap-yum.conf --tolerant --installroot /mnt -y install fedora-release redhat-release coreutils
Yum command has been deprecated, redirecting to '/usr/bin/dnf -c /mnt//etc/bootstrap-yum.conf --tolerant --installroot /mnt -y install fedora-release redhat-release coreutils'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'
```

So it uses yum which redirects to dnf, which does not understant the --tolerant option?

**Comment by gmkurtzer** [comment]
This looks related to issue #77

**Comment by gmkurtzer** [comment]
And pull request #76

**Comment by loveshack** [comment]
Yes, on --tolerant.  There's a change in the mess under pull request #76.  (Maybe I should start again on that fork.)  I'm still somewhat unclear what's going on, particularly with the release version on el6.
I've been working the other way round, though, hosted on el6.

**Comment by gmkurtzer** [comment]
I just accepted that PR, from the overview it looked fine but I'll
investigate further when I get to computer.

Thanks!

## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by loveshack** [comment]
You wrote: 

> I just accepted that PR, from the overview it looked fine but I'll
> investigate further when I get to computer.
> 
> Thanks!

OK, I'll junk that fork and start again.  The gh-pages branch is
definitely messed up.  I detest git.

**Comment by gmkurtzer** [comment]
@loveshack I took a look at your patch, it looked fine but I consolidated the "tolerant" bits and generalized the install command.

@wresch Can you test [master 018cfab]?

**Comment by wresch** [comment]
after recompile - success:

```
$sudo singularity -d -v bootstrap centos6.img centos6.def
[...snip...]
Complete!
```

``` bash
$ singularity shell centos6.img
Singularity/centos6.img> cat /etc/redhat-release 
CentOS release 6.8 (Final)
```

Thanks for the quick response! I'll be checking singularity out in the next couple of days. Looks really interesting.

**Comment by gmkurtzer** [comment]
Fantastic! Thanks to @loveshack for spotting and implementing the fix!
