### ISSUE TITLE
[ CINSTANCE ] feedback

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#830]
Omg I'm so excited about this! This is an issue board to post feedback for the daemon, so we can put stuff in one place while testing it out! I'll try to break things into topics as best as I can. 

## Starting the daemon
First, I was able to start a daemon ok - I had some weird issue with a singularity executable in `/usr/bin` (and I'm not sure how it got there...) but likely is me doing something stupid along the way, so let's assume it's not related to this! Here is the part of my script that creates the daemon, upon registry init:

```
singularity start /usr/local/libexec/sregistry/singularity.registry services
/usr/local/libexec/sregistry/singularity.registry  [66306.8915744]  Daemons:
     Daemon PID:   6272
     Daemon Name:  services
```
Note - the caller of the script was sudo, but I'm wondering if it makes a difference for a user vs. sudo to call singularity start?

I think it would be good to have some kind of feedback that the daemon was started, because I saw a little mounty icon on my sidebar (something ubuntu does) but there wasn't output in the terminal. 

## A Likely use case
I don't have idea about how we could (or even would want to) change this, but here is what I think will be  a common use case for service type daemons - to check if it's running, and only continue if it is:

```
    if singularity list | grep "Daemon Name:  services"; then
        "Registry services daemon is already running."
    else
        singularity start "$SINGULARITY_REGISTRY_MANAGER" services
    fi
```
It's pretty easy to do with grep, but do you think we should make it easier for the user? Something like:

```
singularity list services
6272
```
and it would return the PID or nothing (if services doesn't exist).

## Having trouble with bind
To get to the file I need (outside the image) I needed to do a bind, and I was able to figure out a workaround (calling something already in the image) but I'll leave this general question here - 
are binds allowed / still working when we join? The issue is that if I'm executing a command to the image, it needs to be to run a script that is either already in the image, or bound to it. In this case, these "helper / database" scripts for my application (that sometimes need write) are stored in the installation directory (/usr/local/libexec) and so we need the bind. Is the idea that this is default behavior because the start script must already be in the image (and not bound from outside) and instead of doing a `--join` at some point I can just define a `%startscript` in the bootstrap recipe?

**Comment by vsoch** [comment]
eee! Nevermind the last one, I just added it to the code base already installed in the image. Daemon!!

```
Registry services daemon is already running.
server started, status code 0
worker started, status code 0
```
Also, those print lines are all from my scripts - we should have something added to the daemon so he announces himself!

**Comment by GodloveD** [comment]
I like your `list` suggestion.  What about making a whole new command to do that and naming that command `status` to more better mirror daemon usage?

**Comment by vsoch** [comment]
+1 on status, because I anticipate list should be for applications installed in the image. @bauerm97 what do you think? If services need a separate list/status command, then we would want list to be something like listd (and regular list for applications). If not, we could just use status. But it's not totally obvious for status to return a pid, so I sort of like some derivation of list better :)

**Comment by GodloveD** [comment]
I actually think that `list` is good for what it is doing now (listing running containers).  But if you want info about a specific container's status I thought that `status` would be a better command.

**Comment by vsoch** [comment]
@GodloveD what about listing applications then? I find list more intuitive for showing contents of a folder, and a container's intended software/apps seems like it matches to that thing for a container, eg 

filesystem contents : list as container apps: list

**Comment by GodloveD** [comment]
Why not make that part of the `inspect` suite?  `inspect` is for metadata and that is metadata no?

**Comment by bauerm97** [comment]
First of all, +1 for giving the user feedback that the daemon is started when using `singularity start`. I will add that in, this is a quick fix. As far as the idea to only start if the daemon isn't running, that's already how start works. If you attempt to do `singularity start <image name> <daemon name that already exists>` it will tell you that the daemon already exists.

As far as bind mounts go, the mount should be done at start. Every process that runs inside of the set of namespaces should always have the same view as each other. Therefore, actions such as bind, etc... need to be done at start.

**Comment by vsoch** [comment]
@bauerm97 yes the "already exists" works great! I think it might have exited (causing my running function to exit) so I wanted to catch that first, and print a message to the user.

ohhh I see - let me try that.

**Comment by vsoch** [comment]
stupid question - should one of these kill commands work?

```
$ pkill 6272
singularity list /usr/local/libexec/sregistry/singularity.registry
/usr/local/libexec/sregistry/singularity.registry  [66306.8915744]  Daemons:
     Daemon PID:   6272
     Daemon Name:  services

$ kill 6272
singularity list /usr/local/libexec/sregistry/singularity.registry
/usr/local/libexec/sregistry/singularity.registry  [66306.8915744]  Daemons:
     Daemon PID:   6272
     Daemon Name:  services
```

After I have brought my daemon to life, how do I... destroy him? :)

**Comment by vsoch** [comment]
I also tried issuing those to the container with exec

**Comment by bauerm97** [comment]
So right now, only signal 9 will actually kill the daemon (this is due to how signals are handled in the kernel when mixed with namespaces). This will change going forward where there will be different signals caught and handled by the sinit process, but for now this is true. Singularity stop is the accepted way to stop a container. So in this case you would do `singularity stop /usr/local/libexec/sregistry/singularity.registry services` and the daemon will stop itself. If for some reason you don't want to use `singularity stop`, `kill -n 9 $PID` will stop the container namespace and everything running inside of it, however this is not recommended.

**Comment by bauerm97** [comment]
What do you mean by "I think it might have exited (causing my running function to exit)"? The daemon should never just shut down if you haven't ran a `singularity stop`

**Comment by vsoch** [comment]
oh not the daemon, I mean the thing controlling it, like

```
run thing 1
run thing 2
start daemon EXIT
no thing 3!
```

vs

```
run thing 1
run thing 2
if daemon not running:
    start daemon SUCCESS
run thing 3!
```

**Comment by vsoch** [comment]
oh I didn't know that was implemented - it works!!

```
singularity stop /usr/local/libexec/sregistry/singularity.registry services
Sending SIGKILL to 6272
```

**Comment by vsoch** [comment]
okay I'm having a bit of strange functionality - basically I try starting and joining, it tells me there was error, but then the daemon is running:

```
sudo sregistry status
Registry services daemon is not running.

$ sudo sregistry start
ERROR  : Unable to join daemon: services daemon does not exist
ABORT  : Retval = 255

$ sudo sregistry status
     Daemon Name:  services
Registry services daemon is running.
```

**Comment by vsoch** [comment]
ahhh I know what it is - the daemon is associated with the user! so these two things are different:

```
# as vanessa
sregistry list
$ singularity list

# as sudo
$ sudo singularity list
/usr/local/libexec/sregistry/singularity.registry  [66306.8915744]  Daemons:
     Daemon PID:   8603
     Daemon Name:  services
```

**Comment by vsoch** [comment]
here is the behavior I'm seeing: https://asciinema.org/a/130598?speed=2

**Comment by bauerm97** [comment]
@vsoch Can you link what this sregistry script is? I need to see what commands the script is running to help troubleshoot the behavior.

**Comment by vsoch** [comment]
oh sure! The section that you want is actually here: https://github.com/singularityhub/singularity-registry/blob/master/helpers/cli/sregistry.ctrl#L67 Let me know if you have questions and what not!

**Comment by bauerm97** [comment]
@vsoch Thanks! First of all, take out the --bind option in your exec line with --join. Bind mounting is done only at start. You should not even be able to use --join and --bind at the same time (this should actually error out what you're trying to do here). Try that first and see what happens

**Comment by vsoch** [comment]
I'm confused - so if I have different use cases of needing different binds (eg the service needs to be running, and sometimes I exec commands to it with different binds) they would have to all be defined at start?

**Comment by bauerm97** [comment]
Yes. Different use cases which need a different view of their environment should be kept separate. `singularity start` creates one view of the environment. If you need a different view, you should use `singularity start` again with different parameters.

**Comment by vsoch** [comment]
what if I need the same service to be consistently running under different environments? Eg:

 - initializing the registry - we mount all folders to add data and run migrations on the database.
 - building: we need communication with the server to receive / submit finished jobs, and the mount point for the building and storage is variable and could arguably change every time.

**Comment by vsoch** [comment]
Think of it like a webserver. There might be a lot going on with regard to how the application is connecting to external things, submitting and receiving requests, but you don't deploy a different server for every one, or ever time you need to change a detail. It has to be constantly running to listen for finished jobs (from some worker) and then be able to mount where the finished thing is.

**Comment by vsoch** [comment]
holy cow! @gmkurtzer just said one thing - that what we are calling a "daemon" is an instance, and it totally clicked! I get it!! ahh :)

**Comment by vsoch** [comment]
ah ha! I got the other bug worked out too - we need a slight delay between start and --join. If you call them too quickly it looks like the container hasn't had time to start. @bauerm97 I would maybe add a small delay after all calls to start, because anyone that writes this into a script (a start followed by join) is going to hit this bug, it basically said that it didn't exist (when it did) and then it was created anyway, haha. Here is what it looks like so far:

https://asciinema.org/a/130639?speed=3

**Comment by vsoch** [comment]
here is better example https://asciinema.org/a/130640?speed=3

**Comment by vsoch** [comment]
ah! And one more thing on my mind before heading out for today - this container instance creation, in that it is creating instances and more suited for "developer" types, fits very nicely into more of a language API / script than a bash command. For example, consider the following:

```
from singularity.cli import Client
client = Client()
image = client.pull("shub://vsoch/hello-world")

instance = client.create_instance(image)

instance.start()
Starting instance...

instance.status
$ Container image vsoch-hello-world daemon
Daemon PID: 123

instance.stop()
Stopping instance...
```

It feels very natural to have an object to start and stop, vs. figuring it out via grep. Other than me wrapping the commands with singularity-python (the client module above is from there) can we expose this in another way?

**Comment by vsoch** [comment]
and actually, in the above, the `create_instance` is technically the "start" as we have it now, and the `instance.start()` is the join. I think this feels maybe more natural than start followed by join?

**Comment by GodloveD** [comment]
I agree with @vsoch that the `start` command is being wrongly conflated with a daemon process.  `start` really doesn't have anything to do with starting a daemon.  It is just starting a place that a daemon can run.  I think the `singularity start help` doc should be changed to read something like this:
```
Start a named PID namespace in the background from a given container image.
```

**Comment by bauerm97** [comment]
@godloved I agree as well. Greg and I spoke about this yesterday in the office and we realized that the confusion was arising because of the name that I gave to what we're doing. The original reason I named the branch feature-daemon was because this change is intended to provide support for daemons (services) instead of jobs.

After a lot of discussion, we think it might just be best to call these instances of a container. For example, the start help documentation would instead say something like `Start a named instance of the specified container image`. Now that's definitely open to change, but it seems like that phrasing helped clear up some confusion for Vanessa, so maybe that's good enough.

**Comment by vsoch** [comment]
seriously, I saw rainbows!

**Comment by vsoch** [comment]
Also I want to get started on some docs / write up for the many new stuffs we are working on. What do you like better - a docs/2.4 branch (like we did before) or some "under development" section so users that install from development can read easily? I suppose they could also just look at the 2.4 branch on github, so  maybe that is best.

**Comment by GodloveD** [comment]
I dig the development idea for the docs!

**Comment by gmkurtzer** [comment]
Instance is the word of the day! Sorry for the confusions on overloaded terms like "daemon".

**Comment by vsoch** [comment]
hey guys! I just added docs for 2.4, here:

https://github.com/singularityware/singularityware.github.io/tree/docs/2.4

Specifically, here is for instances:

https://github.com/singularityware/singularityware.github.io/blob/docs/2.4/pages/docs/user-docs/docs-instances.md

I am proposing that we rename the current "start" action to be "clone" because it coincides with creation of the instance. Then the current --join argument should correspond with start. Take a look at the link above for example usage, and how I explained it. And please edit the crap out of that! I hope I could just get you started! :)

**Comment by bauerm97** [comment]
#839 I submitted a PR. Again, we can change more as we go along but this is I think a good foundation

**Comment by dtrudg** [comment]
I believe we are good to close this, given the topics discussed here got into 2.4. Thanks!
