### ISSUE TITLE
Mount hostfs bind mounts /boot

### ISSUE THREAD

**Issue by Saford91** [apptainer/singularity#832]
## Version of Singularity: 2.3.1

When configured with 'mount hostfs = true', containers bind mount /boot. This behavior is consistent with the 'mount hostfs' description: "Probe for all mounted file systems that are mounted on the host, and bind those into the container" This is not done with other local mounts on the hosts, e.g. /var and /var/log. It seems that Singularity ignores these.

Depending on what's installed into the mounted container, this can clobber your boot configuration.

### Expected behavior

I expect Singularity to ignore /boot when bind mounting file systems. I don't see the use in mounting standard system directories like /boot into a container

### Actual behavior

Singularity bind mounts /boot into the container while ignoring other standard directories like /var and /var/log.

### Steps to reproduce behavior

Install Singularity 2.3.1.
Configure 'mount hostfs = yes' in singularity conf file
Open a shell into a container
Observe your local machines /boot file system mounted inside your container.

**Comment by vsoch** [comment]
what if we had this as an equivalent setting?

```
# MOUNT BOOT: [BOOL]
# DEFAULT: yes
# Should we automatically bind mount /boot within the container?
mount boot = yes
```
and then that would override the mount hostfs. Just curious, do you see any issue / problem, or even use case for binding to boot? It's one of those folders, at least in the context of images, I just forget that  it's there :P Although I have mount hostfs as no, so the folder is always empty for me.

What about advocation for being more conservative - turning off all binds and then specifying the ones you need? (versus turning all on and then trying to remove the ones you don't)

**Comment by Saford91** [comment]
I don't see a use for mounting /boot into a container. Ignoring boot seems like what most users will want, and those who need to mount it could specify it as a bind point. Similar to what singularity does with the /var file system, silently ignoring boot seems acceptable.

Disabling mount hostfs and having users specify what bind points they want would circumvent this issue, but I'd like to make the use of Singularity on my systems as simple as possible.

**Comment by vsoch** [comment]
hey @Saford91 - I just put in a PR for doing this. https://github.com/singularityware/singularity/pull/838 @gmkurtzer is a bit busy but he will get around to reviewing, and we will (soon) likely have a solution to your issue.

**Comment by vsoch** [comment]
hey @Saford91 this has been merged into development. Could you please test? ty!

**Comment by vsoch** [comment]
This was fixed, please let us know if you have issue with the development branch. Thanks!

**Comment by Saford91** [comment]
@vsoch Just tested with a78190c84c07daa3b399aa7efe5b1ae476ee331a, /boot is no longer mounted with mount hostfs enabled. Thanks!

**Comment by vsoch** [comment]
awesome! Thanks for testing :0)
