### ISSUE TITLE
Support for bootstrapping from a local image (feature request)

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#833]
## Version of Singularity:

2.3

### Suggested behavior

It would be nice to be able to have one or a few images saved on your local machine that could be used as templates for bootstrapping images, in the same way that we are currently using Docker Hub containers as templates for bootstrapping.  You can already do this if you like, but it is not very clean.  I propose officially supporting this by creating a new bootstrap driver called local image.  I've already written the code to do this and will submit a pull request shortly.

**Comment by vsoch** [comment]
This will be possible with apps! See https://github.com/singularityware/singularity/pull/826

**Comment by vsoch** [comment]
oh I am reading the end now - awesome! Can't wait to see it.

**Comment by vsoch** [comment]
could we hook the shub endpoint in as well? So it would be the same flow but first pull the shub image. How are you handling merging metadata?

**Comment by GodloveD** [comment]
You are reading my mind @vsoch!  shub is the next thing I want to work on.  

Actually I didn't think about the meta-data.  It's probably getting clobbered by the second bootstrap right now.  I'll have to have a look and see.  I'm going to go ahead and post the PR in a few minutes and then maybe we can talk more about it.

**Comment by vsoch** [comment]
yes we can't add something to the software that encourages bad practice for reproducibility. The clobbering must be resolved in some fashion!

**Comment by shahzebsiddiqui** [comment]
can we get shub bootstrap option in singularity. 

Currently it is not supported
```
[root@amrndhl1295 ~]# singularity bootstrap /dev/shm/test.img test.def 
Sanitizing environment
Building from bootstrap definition recipe
Adding base Singularity environment to container
ERROR: 'Bootstrap' type not supported: shub

[root@amrndhl1295 ~]# cat test.def 
BootStrap: shub
From: shahzebsiddiqui/singularity-examples:singularity-2.3.1

%post



```

**Comment by vsoch** [comment]
the singularity fairies are working on this as you speak :)

**Comment by GodloveD** [comment]
https://yt3.ggpht.com/-zvlOt3MimBY/AAAAAAAAAAI/AAAAAAAAAAA/KtdVvraKp1Y/s900-c-k-no-mo-rj-c0xffffff/photo.jpg

**Comment by vsoch** [comment]
how did you know!

**Comment by GodloveD** [comment]
This is all finished as far as I know.  So I'm going to close now.  Re-open if necessary.  Thanks!
