### ISSUE TITLE
Update source files with appropriate header

### ISSUE THREAD

**Issue by gmkurtzer** [apptainer/singularity#844]
I need help to update all of the source file headers to make sure they have the standard project header:

```
Copyright (c) 2017, SingularityWare, LLC. All rights reserved.

See the COPYRIGHT.md file at the top-level directory of this distribution and at
https://github.com/singularityware/singularity/blob/master/COPYRIGHT.md.

This file is part of the Singularity Linux container project. It is subject to the license
terms in the LICENSE.md file found in the top-level directory of this distribution and
at https://github.com/singularityware/singularity/blob/master/LICENSE.md. No part
of Singularity, including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE.md file.
```

If there are any other copyright entries, they should be retained as given and listed after the SingularityWare copyright. For any files that include an LBNL/DOE/UC Regents copyright, those files will need to also include the following:

```
This file also contains content that is covered under the LBNL/DOE/UC modified
3-clause BSD license and is subject to the license terms in the LICENSE-LBNL.md
file found in the top-level directory of this distribution and at
https://github.com/singularityware/singularity/blob/master/LICENSE-LBNL.md.
```

Credit goes to: http://www.softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html

**Comment by vsoch** [comment]
I dig this kind of massive and repetitive work, I'm so down lol.

**Comment by gmkurtzer** [comment]
Haha, you rock, thank you!

Before we move on this, I'd like to keep this open for a bit and see if anybody has any comments or further ideas on the default header content.

**Comment by vsoch** [comment]
haha, well I already did about half of them for my current PR, but I will be happy to fix up with suggestions :)

**Comment by dtrudg** [comment]
Closing as the header above is now out of date. See #1311

**Comment by vsoch** [comment]
It also was done I think, and the issue just wasn't closed :)
