### ISSUE TITLE
still problems with debian bootstrap

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#85]
[I can't re-open #74.]

Debian bootstrap gets further now, but still fails with the trunk from yesterday (on an el6 host).
I have this .def as a cut-down example.

```
DistType "debian"
MirrorURL "http://ftp.uk.debian.org/debian/"
OSVersion "stable"
Setup
Bootstrap
InstallPkgs default-jre
Cleanup
```

Bootstrap fails like this at the end:

```
Processing triggers for ca-certificates (20141019+deb8u1) ...
mktemp: failed to create file via template '/tmp/singularity-bootstrap.uvsuHkm/ca-certificates.crt.tmp.XXXXXX': No such file or directory
dpkg: error processing package ca-certificates (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 ca-certificates
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

With v2.0 it additionally has

```
ERROR: Could not clear loop device
ERROR: Failed to detach loop device: /dev/loop3
```

and I'm left with loop devices in use that I can't get rid of.  Any idea what might have fixed that?

**Comment by gmkurtzer** [comment]
On Thursday, June 23, 2016, Dave Love notifications@github.com wrote:

> [I can't re-open #74 https://github.com/gmkurtzer/singularity/issues/74
> .]
> 
> Debian bootstrap gets further now, but still fails with the trunk from
> yesterday (on an el6 host).
> I have this .def as a cut-down example.
> 
> DistType "debian"
> MirrorURL "http://ftp.uk.debian.org/debian/"
> OSVersion "stable"
> Setup
> Bootstrap
> InstallPkgs default-jre
> Cleanup
> 
> Bootstrap fails like this at the end:
> 
>  I will try to replicate with that definition when I get into work.
> 
> With v2.0 it additionally has
> 
> ERROR: Could not clear loop device
> ERROR: Failed to detach loop device: /dev/loop3
> 
> and I'm left with loop devices in use that I can't get rid of. Any idea
> what might have fixed that?
> 
> You can't get rid of them? What does losetup -a return? And losetup -d
> /dev/loop3? If not, then I would guess that the mount namespace is being
> held open by a mount or process that is still running. Possibly from the
> failed install?

There were a bunch of fixes I put in place for loop devices in 2.1/master.

## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by gmkurtzer** [comment]
I have been trying to replicate the bootstrap error, but so far unable. It isn't working for me, but it also isn't failing like yours is. It did however work if I shell'ed into the container, and ran the apt-get install from there. <shrugs>

I am inclined to leave this for now and come back to it at a later time or with someone that has more Debian hacking experience then me.

**Comment by gmkurtzer** [comment]
I ended up still hacking on this a bit more, and realized (after I actually read the error you sent) that the problem was that I was using TMPDIR to store the local bootstrap temporary directory location. Surprisingly enough (sarcasm), TMPDIR is a commonly used envar, and some of the dpkg configure scripts were also using it and not overwriting it. So... I changed Singularity to use SINGULARITY_TMPDIR instead. It is getting further for me, but now getting an error on what appears to look like a selinux issue:

```
dpkg (subprocess): cannot set security execution context for maintainer script: Invalid argument
dpkg: error processing package man-db (--unpack):

```

But interestingly enough, if I shell --writable into the container, I am able to install properly. I may try to unshare() the FS and FILES namespaces and see if selinux settles down.

**Comment by loveshack** [comment]
You wrote: 

> On Thursday, June 23, 2016, Dave Love notifications@github.com wrote:
> 
> > [I can't re-open #74 https://github.com/gmkurtzer/singularity/issues/74
> > .]
> > 
> > Debian bootstrap gets further now, but still fails with the trunk from
> > yesterday (on an el6 host).
> > I have this .def as a cut-down example.
> > 
> > DistType "debian"
> > MirrorURL "http://ftp.uk.debian.org/debian/"
> > OSVersion "stable"
> > Setup
> > Bootstrap
> > InstallPkgs default-jre
> > Cleanup
> > 
> > Bootstrap fails like this at the end:
> > 
> >  I will try to replicate with that definition when I get into work.
> > 
> > With v2.0 it additionally has
> > 
> > ERROR: Could not clear loop device
> > ERROR: Failed to detach loop device: /dev/loop3
> > 
> > and I'm left with loop devices in use that I can't get rid of. Any idea
> > what might have fixed that?
> > 
> > You can't get rid of them? What does losetup -a return?

```
# losetup -a
/dev/loop0: [fd00]:662797 (/dev/loop0)
/dev/loop1: [fd00]:662798 (/dev/loop1)
/dev/loop2: [fd02]:85 (), offset 31
/dev/loop3: [fd02]:278 (), offset 31
```

> And losetup -d /dev/loop3?

```
# losetup -d /dev/loop1
loop: can't delete device /dev/loop1: Device or resource busy
```

That's the same error associated with "Could not clear loop device" from
singularity.

> If not, then I would guess that the mount namespace is being
> held open by a mount or process that is still running. Possibly from the
> failed install?

It seems only to be referenced by a kernel thread if I understand
ps/proc right.

> There were a bunch of fixes I put in place for loop devices in 2.1/master.

I can't see what's relevant, and would have to do some serious
debugging/understanding which will have to wait.  Unfortunately I think
this makes the fedora package unreleasable.

**Comment by gmkurtzer** [comment]
There is for sure at least one process still running within the container.
I was not able to replicate this on my system, are you running this on
Fedora?

It might help for me to also separate out the PID namespace for
bootstrapping. I will add that today and if you can retest that would be
great.

BTW, I did make some changes yesterday to the bootstrap code, did any of
that help?

The fixes I put in place are specific for older distributions not being
able to clear loop devices and you are right, not relevant here.

On Friday, June 24, 2016, Dave Love notifications@github.com wrote:

> You wrote:
> 
> > On Thursday, June 23, 2016, Dave Love <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > > [I can't re-open #74 <
> > > https://github.com/gmkurtzer/singularity/issues/74>
> > > .]
> > > 
> > > Debian bootstrap gets further now, but still fails with the trunk from
> > > yesterday (on an el6 host).
> > > I have this .def as a cut-down example.
> > > 
> > > DistType "debian"
> > > MirrorURL "http://ftp.uk.debian.org/debian/"
> > > OSVersion "stable"
> > > Setup
> > > Bootstrap
> > > InstallPkgs default-jre
> > > Cleanup
> > > 
> > > Bootstrap fails like this at the end:
> > > 
> > > I will try to replicate with that definition when I get into work.
> > > 
> > > With v2.0 it additionally has
> > > 
> > > ERROR: Could not clear loop device
> > > ERROR: Failed to detach loop device: /dev/loop3
> > > 
> > > and I'm left with loop devices in use that I can't get rid of. Any idea
> > > what might have fixed that?
> > > 
> > > You can't get rid of them? What does losetup -a return?
> 
> ```
> # losetup -a
> /dev/loop0: [fd00]:662797 (/dev/loop0)
> /dev/loop1: [fd00]:662798 (/dev/loop1)
> /dev/loop2: [fd02]:85 (), offset 31
> /dev/loop3: [fd02]:278 (), offset 31
> ```
> 
> > And losetup -d /dev/loop3?
> 
> ```
> # losetup -d /dev/loop1
> loop: can't delete device /dev/loop1: Device or resource busy
> ```
> 
> That's the same error associated with "Could not clear loop device" from
> singularity.
> 
> > If not, then I would guess that the mount namespace is being
> > held open by a mount or process that is still running. Possibly from the
> > failed install?
> 
> It seems only to be referenced by a kernel thread if I understand
> ps/proc right.
> 
> > There were a bunch of fixes I put in place for loop devices in
> > 2.1/master.
> 
> I can't see what's relevant, and would have to do some serious
> debugging/understanding which will have to wait. Unfortunately I think
> this makes the fedora package unreleasable.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/gmkurtzer/singularity/issues/85#issuecomment-228326399,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANVkxaMDkqBKQJPK3WA8A0lGmqMQtGcxks5qO8TDgaJpZM4I8ywi
> .

## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by gmkurtzer** [comment]
A little bit more info on this... If you do a basic bootstrap and then shell into the container and `apt-get install default-jre`, it works just fine for me. But if I do it from the bootstrap, I am getting security issue warnings. I am going to continue debugging this, but I'm not sure why it is having an issue on bootstrap rather then running within a proper shell.

**Comment by gmkurtzer** [comment]
OK, your definition file is working for me now... Can you retest against [master a5305b7] and let me know?

**Comment by truatpasteurdotfr** [comment]
it does not work for me (c7 hosted, freshly git pulled):

```
Setting up openjdk-7-jre-headless:i386 (7u101-2.6.6-2~deb8u1) ...
the java command requires a mounted proc fs (/proc).
dpkg: error processing package openjdk-7-jre-headless:i386 (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up ca-certificates-java (20140324) ...
the keytool command requires a mounted proc fs (/proc).
dpkg: error processing package ca-certificates-java (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of openjdk-7-jre:i386:
 openjdk-7-jre:i386 depends on openjdk-7-jre-headless (= 7u101-2.6.6-2~deb8u1); however:
  Package openjdk-7-jre-headless:i386 is not configured yet.

dpkg: error processing package openjdk-7-jre:i386 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of default-jre:
 default-jre depends on openjdk-7-jre (>= 7~u3-2.1.1); however:
  Package openjdk-7-jre:i386 is not configured yet.

dpkg: error processing package default-jre (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for systemd (215-17+deb8u4) ...
Processing triggers for ca-certificates (20141019+deb8u1) ...
mktemp: failed to create file via template '/tmp/singularity-bootstrap.j357p46/ca-certificates.crt.tmp.XXXXXX': No such file or directory
dpkg: error processing package ca-certificates (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for sgml-base (1.26+nmu4) ...
Errors were encountered while processing:
 openjdk-7-jre-headless:i386
 ca-certificates-java
 openjdk-7-jre:i386
 default-jre
 ca-certificates
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by truatpasteurdotfr** [comment]
If I comment out the line:
#InstallPkgs default-jre
bootstrap finished but I can't install default-jre.

```
[tru@hpe840g1-1 singularity]$ sudo singularity shell -w singularity-issue-85.img
Singularity/singularity-issue-85.img> apt-get -y install default-jre
Reading package lists... Done
Building dependency tree... Done
The following extra packages will be installed:
  ca-certificates ca-certificates-java dbus dbus-x11 default-jre-headless file fontconfig fontconfig-config fonts-dejavu-core fonts-dejavu-extra gconf-service gconf2
  gconf2-common gnome-mime-data hicolor-icon-theme java-common krb5-locales libalgorithm-c3-perl libarchive-extract-perl libasound2 libasound2-data libasyncns0
  libatk-wrapper-java libatk-wrapper-java-jni libatk1.0-0 libatk1.0-data libavahi-client3 libavahi-common-data libavahi-common3 libavahi-glib1 libbonobo2-0
  libbonobo2-common libbsd0 libcairo2 libcanberra0 libcap-ng0 libcgi-fast-perl libcgi-pm-perl libclass-c3-perl libclass-c3-xs-perl libcpan-meta-perl libcups2
  libdata-optlist-perl libdata-section-perl libdatrie1 libdbus-1-3 libdbus-glib-1-2 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2 libelf1 libexpat1
  libfcgi-perl libflac8 libfontconfig1 libfreetype6 libgconf-2-4 libgconf2-4 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgif4 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libglib2.0-0 libglib2.0-data libgnome-2-0 libgnome2-0 libgnome2-bin libgnome2-common libgnomevfs2-0 libgnomevfs2-common libgnomevfs2-extra
  libgraphite2-3 libgssapi-krb5-2 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libharfbuzz0b libice6 libjasper1 libjbig0 libjpeg62-turbo libk5crypto3 libkeyutils1
  libkrb5-3 libkrb5support0 liblcms2-2 libldap-2.4-2 libllvm3.5 liblog-message-perl liblog-message-simple-perl libltdl7 libmagic1 libmodule-build-perl
  libmodule-pluggable-perl libmodule-signature-perl libmro-compat-perl libnspr4 libnss3 libogg0 liborbit-2-0 libpackage-constants-perl libpango-1.0-0
  libpangocairo-1.0-0 libpangoft2-1.0-0 libparams-util-perl libpciaccess0 libpcsclite1 libpixman-1-0 libpng12-0 libpod-latex-perl libpod-readme-perl libpulse0
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib libregexp-common-perl libsasl2-2 libsasl2-modules libsasl2-modules-db libsctp1 libsm6 libsndfile1
  libsoftware-license-perl libsqlite3-0 libsub-exporter-perl libsub-install-perl libtdb1 libterm-ui-perl libtext-soundex-perl libtext-template-perl libthai-data
  libthai0 libtiff5 libtxc-dxtn-s2tc0 libvorbis0a libvorbisenc2 libvorbisfile3 libwrap0 libx11-6 libx11-data libx11-xcb1 libxau6 libxcb-dri2-0 libxcb-dri3-0
  libxcb-glx0 libxcb-present0 libxcb-render0 libxcb-shm0 libxcb-sync1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6 libxinerama1
  libxml2 libxrandr2 libxrender1 libxshmfence1 libxtst6 libxxf86vm1 lksctp-tools mime-support openjdk-7-jre openjdk-7-jre-headless openssl perl perl-modules psmisc
  python python-minimal python2.7 python2.7-minimal rename sgml-base shared-mime-info tcpd tzdata-java ucf x11-common xdg-user-dirs xml-core
Suggested packages:
  gconf-defaults-service equivs libasound2-plugins alsa-utils libbonobo2-bin libcanberra-gtk0 libcanberra-pulse cups-common desktop-base libgnomevfs2-bin krb5-doc
  krb5-user librsvg2-common gvfs libjasper-runtime liblcms2-utils pciutils pcscd pulseaudio libsasl2-modules-otp libsasl2-modules-ldap libsasl2-modules-sql
  libsasl2-modules-gssapi-mit libsasl2-modules-gssapi-heimdal icedtea-7-plugin icedtea-7-jre-jamvm libnss-mdns sun-java6-fonts fonts-ipafont-gothic
  fonts-ipafont-mincho ttf-wqy-microhei ttf-wqy-zenhei fonts-indic perl-doc libterm-readline-gnu-perl libterm-readline-perl-perl make libb-lint-perl
  libcpanplus-dist-build-perl libcpanplus-perl libfile-checktree-perl libobject-accessor-perl python-doc python-tk python2.7-doc binutils binfmt-support sgml-base-doc
  debhelper
Recommended packages:
  libarchive-tar-perl
The following NEW packages will be installed:
  ca-certificates ca-certificates-java dbus dbus-x11 default-jre default-jre-headless file fontconfig fontconfig-config fonts-dejavu-core fonts-dejavu-extra
  gconf-service gconf2 gconf2-common gnome-mime-data hicolor-icon-theme java-common krb5-locales libalgorithm-c3-perl libarchive-extract-perl libasound2
  libasound2-data libasyncns0 libatk-wrapper-java libatk-wrapper-java-jni libatk1.0-0 libatk1.0-data libavahi-client3 libavahi-common-data libavahi-common3
  libavahi-glib1 libbonobo2-0 libbonobo2-common libbsd0 libcairo2 libcanberra0 libcap-ng0 libcgi-fast-perl libcgi-pm-perl libclass-c3-perl libclass-c3-xs-perl
  libcpan-meta-perl libcups2 libdata-optlist-perl libdata-section-perl libdatrie1 libdbus-1-3 libdbus-glib-1-2 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2
  libedit2 libelf1 libexpat1 libfcgi-perl libflac8 libfontconfig1 libfreetype6 libgconf-2-4 libgconf2-4 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgif4
  libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglib2.0-0 libglib2.0-data libgnome-2-0 libgnome2-0 libgnome2-bin libgnome2-common libgnomevfs2-0 libgnomevfs2-common
  libgnomevfs2-extra libgraphite2-3 libgssapi-krb5-2 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libharfbuzz0b libice6 libjasper1 libjbig0 libjpeg62-turbo libk5crypto3
  libkeyutils1 libkrb5-3 libkrb5support0 liblcms2-2 libldap-2.4-2 libllvm3.5 liblog-message-perl liblog-message-simple-perl libltdl7 libmagic1 libmodule-build-perl
  libmodule-pluggable-perl libmodule-signature-perl libmro-compat-perl libnspr4 libnss3 libogg0 liborbit-2-0 libpackage-constants-perl libpango-1.0-0
  libpangocairo-1.0-0 libpangoft2-1.0-0 libparams-util-perl libpciaccess0 libpcsclite1 libpixman-1-0 libpng12-0 libpod-latex-perl libpod-readme-perl libpulse0
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib libregexp-common-perl libsasl2-2 libsasl2-modules libsasl2-modules-db libsctp1 libsm6 libsndfile1
  libsoftware-license-perl libsqlite3-0 libsub-exporter-perl libsub-install-perl libtdb1 libterm-ui-perl libtext-soundex-perl libtext-template-perl libthai-data
  libthai0 libtiff5 libtxc-dxtn-s2tc0 libvorbis0a libvorbisenc2 libvorbisfile3 libwrap0 libx11-6 libx11-data libx11-xcb1 libxau6 libxcb-dri2-0 libxcb-dri3-0
  libxcb-glx0 libxcb-present0 libxcb-render0 libxcb-shm0 libxcb-sync1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6 libxinerama1
  libxml2 libxrandr2 libxrender1 libxshmfence1 libxtst6 libxxf86vm1 lksctp-tools mime-support openjdk-7-jre openjdk-7-jre-headless openssl perl perl-modules psmisc
  python python-minimal python2.7 python2.7-minimal rename sgml-base shared-mime-info tcpd tzdata-java ucf x11-common xdg-user-dirs xml-core
0 upgraded, 190 newly installed, 0 to remove and 0 not upgraded.
Need to get 106 MB of archives.
After this operation, 300 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libbsd0 libedit2 libkeyutils1 libkrb5support0 libk5crypto3 libkrb5-3 libgssapi-krb5-2 libsasl2-modules-db libsasl2-2 libldap-2.4-2 libmagic1 libsqlite3-0 libwrap0
  libxml2 perl-modules perl libpython2.7-minimal python2.7-minimal python-minimal mime-support libexpat1 libpython2.7-stdlib python2.7 libpython-stdlib python
  libpng12-0 libfreetype6 ucf fonts-dejavu-core fontconfig-config libfontconfig1 fontconfig libasound2-data libasound2 libasyncns0 libglib2.0-0 libatk1.0-data
  libatk1.0-0 libpixman-1-0 libxau6 libxdmcp6 libxcb1 libx11-data libx11-6 libxcb-render0 libxcb-shm0 libxext6 libxrender1 libcairo2 libjpeg62-turbo libjasper1
  libjbig0 libtiff5 libgdk-pixbuf2.0-common libgdk-pixbuf2.0-0 libgtk2.0-common libavahi-common-data libavahi-common3 libdbus-1-3 libavahi-client3 libcups2
  libthai-data libdatrie1 libthai0 libpango-1.0-0 libgraphite2-3 libharfbuzz0b libpangoft2-1.0-0 libpangocairo-1.0-0 libxcomposite1 libxfixes3 libxcursor1 libxdamage1
  libxi6 libxinerama1 libxrandr2 shared-mime-info libgtk2.0-0 libatk-wrapper-java libatk-wrapper-java-jni libavahi-glib1 libbonobo2-common liborbit-2-0 libbonobo2-0
  libltdl7 libogg0 libtdb1 libvorbis0a libvorbisfile3 libcanberra0 libcap-ng0 libdbus-glib-1-2 libdrm2 libpciaccess0 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libelf1 libflac8 gconf2-common libgconf-2-4 libgif4 libllvm3.5 libgl1-mesa-dri libglapi-mesa libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-sync1 libxshmfence1 libxxf86vm1 libgl1-mesa-glx gconf-service psmisc dbus dbus-x11 gconf2 gnome-mime-data libgnomevfs2-common libgnomevfs2-0 libgnome2-common
  libgnome-2-0 x11-common libice6 liblcms2-2 libnspr4 libnss3 libpcsclite1 libsm6 libvorbisenc2 libsndfile1 libxtst6 libpulse0 libsctp1 openssl ca-certificates
  java-common default-jre-headless ca-certificates-java tzdata-java openjdk-7-jre-headless sgml-base libtxc-dxtn-s2tc0 file krb5-locales openjdk-7-jre default-jre
  fonts-dejavu-extra hicolor-icon-theme libalgorithm-c3-perl libarchive-extract-perl libcgi-pm-perl libfcgi-perl libcgi-fast-perl libclass-c3-perl libclass-c3-xs-perl
  libcpan-meta-perl libparams-util-perl libsub-install-perl libdata-optlist-perl libmro-compat-perl libsub-exporter-perl libdata-section-perl libgconf2-4
  libglib2.0-data libgnome2-bin libgnome2-0 libgnomevfs2-extra libgtk2.0-bin liblog-message-perl liblog-message-simple-perl libmodule-build-perl
  libmodule-pluggable-perl libmodule-signature-perl libpackage-constants-perl libpod-latex-perl libregexp-common-perl libpod-readme-perl libsasl2-modules
  libtext-template-perl libsoftware-license-perl libterm-ui-perl libtext-soundex-perl lksctp-tools rename tcpd xdg-user-dirs xml-core
E: There are problems and -y was used without --force-yes
Singularity/singularity-issue-85.img> 

```

**Comment by truatpasteurdotfr** [comment]
debootstrap-1.0.80-1.el7.noarch from epel does not provides the debian keys to check the installation packages... debootstrap on alpine requires debian-archive-keyring which provides them.

```
Setting up openjdk-7-jre-headless:amd64 (7u101-2.6.6-2~deb8u1) ...
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/orbd to provide /usr/bin/orbd (orbd) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/servertool to provide /usr/bin/servertool (servertool) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/tnameserv to provide /usr/bin/tnameserv (tnameserv) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00006faa7bf77000, 2555904, 1) failed; error='Operation not permitted' (errno=1)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 2555904 bytes for committing reserved memory.
# An error report file with more information is saved as:
# //hs_err_pid19760.log
ignoring dump failure
Setting up ca-certificates-java (20140324) ...
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x000072436d000000, 2555904, 1) failed; error='Operation not permitted' (errno=1)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 2555904 bytes for committing reserved memory.
# An error report file with more information is saved as:
# //hs_err_pid19782.log
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007308649e0000, 2555904, 1) failed; error='Operation not permitted' (errno=1)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 2555904 bytes for committing reserved memory.
# An error report file with more information is saved as:
# //hs_err_pid19786.log
done.
Setting up openjdk-7-jre:amd64 (7u101-2.6.6-2~deb8u1) ...
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/policytool to provide /usr/bin/policytool (policytool) in auto mode
Setting up default-jre (2:1.7-52) ...
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for systemd (215-17+deb8u4) ...
Processing triggers for ca-certificates (20141019+deb8u1) ...
Updating certificates in /etc/ssl/certs... 174 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00006c3557f77000, 2555904, 1) failed; error='Operation not permitted' (errno=1)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 2555904 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /etc/ssl/certs/hs_err_pid21401.log
E: /etc/ca-certificates/update.d/jks-keystore exited with code 1.
done.
Processing triggers for sgml-base (1.26+nmu4) ...
+ apt-get clean
```

**Comment by gmkurtzer** [comment]
I just retested the current master branch, and /proc is mounted. Also, your first example/failure is referencing Singularity's session directory in the install log:

```
mktemp: failed to create file via template '/tmp/singularity-bootstrap.j357p46/ca-certificates.crt.tmp.XXXXXX': No such file or directory
```

I am pretty sure you did not test the current Git master because I fixed this several days ago. Can you verify?

I added 'debian-archive-keyring' to the --include list for the bootstrap command, please check [master 564b3a5] and see if that helps.

**Comment by loveshack** [comment]
For what it's worth, adding apt and debian-archive-keyring is redundant,
at least with Debian jessie.  If you want the keys initially, they need
to be on the host, don't they?

Could someone confirm one way or the other?   I have a change which
conflicts with this one, which I'll hold off for now.

By the way, there's a missing dependency for Fedora debootstrap, at
least in epel6, which can bite in a minimal root.  It involves xz
support and a fix is currently in -testing if you need it.

**Comment by gmkurtzer** [comment]
Agreed that they should be redundant... But does it hurt to specify them for edge cases?

I think in the Fedora definition file, we may want to include "xz" in the Bootstrap line, or we can add it in the linix_build_redhat.smod file itself if it won't cause a problem going back as old as Centos5 (we have --tolerant, so it should be fine for YUM, but what about DNF?).

**Comment by truatpasteurdotfr** [comment]
/usr/share/keyrings/debian-archive-keyring.gpg is needed by the host epel provided debootstrap-1.0.80-1.el7.noarch on CentOS-7.
If I provided /usr/share/keyrings/debian-archive-keyring.gpg from a jessie installation, there is no message during the singularity bootstrap.

```
[tru@hpe840g1-1 singularity]$ git log|head -9
commit ad26f9859e068dc9b6ffa453ef768d3e0a839636
Merge: 9dbc20b f81e5df
Author: Gregory M. Kurtzer <gmkurtzer@users.noreply.github.com>
Date:   Tue Jun 28 18:49:57 2016 -0700

    Merge pull request #101 from jmstover/master

    Make _rev in spec file changable
...
```

the debootstrap (without InstallPkgs) fails today with:

```

[singularity-issue-85.txt](https://github.com/gmkurtzer/singularity/files/340111/singularity-issue-85.txt)

```

**Comment by truatpasteurdotfr** [comment]
btw, debian-archive-keyring does not exist on ubuntu, so adding the debian-archive-keyring in the debian mod file breaks the ubuntu bootstrap :P

**Comment by gmkurtzer** [comment]
@truatpasteurdotfr, should be fixed in [master 34e445c].

**Comment by loveshack** [comment]
Tru Huynh notifications@github.com writes:

> btw, debian-archive-keyring does not exist on ubuntu, to adding the
> debian-archive-keyring in the debian mod file breaks the ubuntu
> bootstrap :P

For what it's worth, it's in 14.04's universe, but apt depends on the
appropriate keyring as far as I can see.

**Comment by loveshack** [comment]
You wrote: 

> Agreed that they should be redundant... But does it hurt to specify
> them for edge cases?

Not if they're actually needed in some circumstances, though it might
help to conditionalize those to serve as confusion-avoiding documentation.

> I think in the Fedora definition file, we may want to include "xz" in
> the Bootstrap line, or we can add it in the linix_build_redhat.smod

Why?

> file itself if it won't cause a problem going back as old as Centos5
> (we have --tolerant, so it should be fine for YUM, but what about
> DNF?).

xz is in epel5 if you really need it.

**Comment by gmkurtzer** [comment]
I went back through the conversation, and I can't identify that hasn't been addressed. Maybe I am missing something? Can someone articulate what is needed to close this issue?

Thanks!

**Comment by gmkurtzer** [comment]
Closing the issue for now. If it needs to be reopened, comment on it, and I will do so.

Thanks!
