### ISSUE TITLE
Using Private Singularity Hub/Registry

### ISSUE THREAD

**Issue by pforai** [apptainer/singularity#851]
Hi all,
We're using Singularity in production quite some while and are pretty happy with it. For docker based workflows we've deployed a private registry for our internal users. We'd like to do the same with Singularity. Is there an on premises deployable version of SingularityHub or what other options are there (if any all).

Thanks!
P

**Comment by vsoch** [comment]
The answer is yes, a private registry for institutions is under way. I have the "user registry" almost finished, and next am working on the builders for the institution version. Would you be able to share with me your different use cases / desires for the registry? How do you see your registry "builder" working - is it a Vagrant VM? A submission to a slurm/sge job? Do you see sharing any images publicly? And finally, would a web UI be useful to you? I've been developing primarily terminal views for working with / managing the registry, so all of this feedback would be helpful.

**Comment by AdamSimpson** [comment]
@vsoch I'll jump in and say our primary need for this is to facilitate users building non x86 containers. As for how it's implimented i'll leave that up to the experts :)

**Comment by shahzebsiddiqui** [comment]
@vsoch @gmkurtzer We also are looking for a private registry, we are thinking of hosting our singularity images in JFrog Artifactory. I am not sure how this will work, currently Artifactory can host docker repo so I suspect there should be some sort of integration with Singularity. We would want users to be able to pull images from our Artifactory Server using singularity pull

**Comment by pforai** [comment]
+1 on the Artifactory support!

**Comment by vsoch** [comment]
I am almost done with the singularity registry, so I do hope you don't step on my toes. That said, if you want to roll your own thing, I can't stop you from stepping.

**Comment by vsoch** [comment]
hey everyone - in case you didn't read/see in the lists, the Singularity Registry (beta) was finished last week and is ready for feedback and testing! Please post further issues, etc. there. Looking forward to feedback!

github.com/singularityhub/sregistry

**Comment by docwarren** [comment]
+1 for artifactory support.
