### ISSUE TITLE
NO_NEW_PRIVS shouldn't be required for CONTAINLIBS

### ISSUE THREAD

**Issue by AdamSimpson** [apptainer/singularity#859]
## Version of Singularity:

master branch, in particular commit https://github.com/singularityware/singularity/commit/a68ae6447cdf6d964e28b4e7ba8830f7c6f20243
### Expected behavior

`--nv`, and in general `CONTAINLIBS`, should work as long as the required libraries are visible to the container.

### Actual behavior

`--nv` doesn't work if `NO_NEW_PRIVS` isn't supported due to `_singularity_runtime_files_libs()` preforming a `NO_NEW_PRIVS` checks. I don't believe this is appropriate though because the required host libraries may have been made visible through mounting in `singularity.conf` .

### Steps to reproduce behavior

`singularity exec --nv ...` on a machine without `NO_NEW_PRIVS` support.

**Comment by GodloveD** [comment]
I *think* this is because root privs are needed to create all of the lib files within the container at runtime for binding.  If the host libs are mounted using the `singularity.conf` wouldn't you need an overlay file system?  Or stubs of all the libs already in the container?

**Comment by AdamSimpson** [comment]
@GodloveD you may very well be correct, in which case this isn't actually an issue at all :)

**Comment by dtrudg** [comment]
Closing this, as we have now dropped support for kernels without PR_SET_NO_NEW_PRIVS
