### ISSUE TITLE
EFS pull hanging

### ISSUE THREAD

**Issue by KevinSayers** [apptainer/singularity#861]
## Version of Singularity:

Singularity version: 2.3.1-dist

### Expected behavior
Using Singularity pull on either dockerhub or singularity hub should pull the image to an AWS EFS mount.

### Actual behavior

Singularity pull will correctly pull a singularity hub container onto an EFS mount. When doing a pull from dockerhub it hangs after the below message. 

```
INFO    [U=1001,P=18018]   main()                                    Creating 880MiB image
VERBOSE [U=1001,P=18018]   singularity_image_create()                Writing image header
VERBOSE [U=1001,P=18018]   singularity_image_create()                Growing image to 880MB
```
If I do a shell as below, it works fine. 
```
singularity shell docker://sayerskt/samtools
```

### Steps to reproduce behavior

singularity pull a dockerhub container to an EFS mount.

**Comment by vsoch** [comment]
This is likely because the pull folder is wrong. I have a PR in to fix this that @gmkurtzer just needs to review.

**Comment by dtrudg** [comment]
Hi @KevinSayers - I'm closing this issue as it is believed fixed by merged PRs. Please feel free to reopen if you hit the issue on Singularity 2.4 Thank you!
