### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by Thaerious** [apptainer/singularity#864]
Hello,

I am attempting to define a custom environment variable in the definition file as per http://singularity.lbl.gov/docs-environment-metadata.  I'm not too sure if I'm misunderstanding how it works, but the environment variable doesn't seem to be set when I run "singularity exec".  I'm using java just as a test.

Regards,
-Ed

## Version of Singularity:
2.3.1-master.g6602bd8

### Expected behavior
$> singularity exec -e ubuntu.img env | grep JAVA_HOME
JAVA_HOME=/usr/java/jre1.8.0_144

### Actual behavior
No output (environment variable not set).
However...
If I set a java home before running the command it works.

export SINGULARITYENV_JAVA_HOME=x
$> singularity exec -e ubuntu.img env | grep JAVA_HOME
JAVA_HOME=/usr/java/jre1.8.0_144

### Steps to reproduce behavior
commands:
sudo singularity create --size 1000 ubuntu.img
sudo singularity bootstrap ubuntu.img definition

"definition" file:
Bootstrap:docker
From:ubuntu:latest

%environment
JAVA_HOME=/usr/java/jre1.8.0_144

%setup
cp jre-8u144-linux-x64.tar.gz $SINGULARITY_ROOTFS

%post
mkdir /usr/java
cd /usr/java
mv /jre-8u144-linux-x64.tar.gz .
tar zxf /usr/java/jre-8u144-linux-x64.tar.gz
rm jre-8u144-linux-x64.tar.gz

**Comment by AdamSimpson** [comment]
Edit: Oops it doesn't appear to be fixed in development either.

It looks like the variable has to have been previously defined before `/.singularity.d/env/90-environment.sh ` is sourced for the value to persist, I'm not sure what's causing that.

```
$ JAVA_HOME=/foo/bar singularity exec ubuntu.img env | grep JAVA_HOME
JAVA_HOME=/usr/java/jre1.8.0_144

$ singularity exec ubuntu.img env | grep JAVA_HOME

$ JAVA_HOME=/foo/bar singularity exec -e ubuntu.img env | grep JAVA_HOME
```

**Comment by GodloveD** [comment]
I think you have an error in your bootstrap script.  It should be:

%environment
export JAVA_HOME=/usr/java/jre1.8.0_144

**Comment by Thaerious** [comment]
It now works, thank you.  I didn't treat the definition file like I would a shell script, the doc is a little ambiguous in that respect.  It just says:

%environment
VARIABLE_NAME=VARIABLE_VALUE

Thanks,
-Ed

**Comment by vsoch** [comment]
Apologies about that! I just updated the docs.

**Comment by vsoch** [comment]
Hey everyone I think we resolved this? Feel free to re-open if needed.
