### ISSUE TITLE
Q: could I have singularity image with 32bit image userland?

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#870]
I wondered if I could specify alternative architecture for debootstrap driver, but seems not:
```shell
ARCH=`uname -m`

if [ "$ARCH" == "x86_64" ]; then
    ARCH=amd64 
elif [ "$ARCH" == "ppc64le" ]; then
    ARCH=ppc64el
elif [ "$ARCH" == "aarch64" ]; then
    ARCH=arm64
fi
```
but in general -- wouldn't 32bit image userland be runnable?  I can use 32bit userland chroots no problem.

**Comment by cclerget** [comment]
@yarikoptic If you take the development branch, you could specify ARCH, otherwise you can fake uname for your version like this :

`uname() { echo "i386"; unset uname; }; export -f uname`

**Comment by yarikoptic** [comment]
thanks! Arch setting worked out beautifully for me
