### ISSUE TITLE
mpirun example fails

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#88]
As reported on the list, the mpirun example from http://singularity.lbl.gov/#hpc fails for me.  It's en el6 host with a recent trunk singularity and any of OMPI 1.6 (our native one), 1.8, or 1.10.  I used a cut-and-paste from the example (fixed for non-ascii).  The ranks all fail with:

```
    ompi_mpi_init: ompi_rte_init failed
    --> Returned "(null)" (-43) instead of "Success" (0)
```

**Comment by rhc54** [comment]
that is correct - you need the OMPI master, or release 2.1 once that occurs (probably this fall?)

**Comment by gmkurtzer** [comment]
Thanks for the clarification Ralph!

**Comment by loveshack** [comment]
This needs to be clarified in the documentation, especially as that
wasn't what I understood before, though I didn't see how it could work.

It could use explanation of what the integration does too.

**Comment by gmkurtzer** [comment]
I agree and will update/clarify the documentation. Reopening issue as a reminder to do that.

**Comment by loveshack** [comment]
Maybe note that it will work with compatible MPIs (including older OMPI) inside and outside the container, at least with no pid namespacing. 

Is there some way to use the container's mpirun to start the container MPI processes?  I've forgotten what went wrong when I tried.

**Comment by gmkurtzer** [comment]
It is possible to use the container's mpirun to start the contained MPI process... BUT..... Then each container has to have ssh and sshd with sshd's running within the container (or having the scheduler automatically spawn the orted processes within the container). Starting the MPI process from within the container increases complexities significantly without gaining an equal amount... As a matter of fact, I don't think it gains anything, and may even loose more then it gains. -- This will make a good FAQ as well.

I added some verbiage on the HPC page at the bottom noting the OMPI version used.

**Comment by gmkurtzer** [comment]
BTW, I added an FAQ about the mpirun inside/outside container. Thanks!
