### ISSUE TITLE
obscure message when unable to download image

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#880]
## Version of Singularity:

2.3.1

### Expected behavior

more meaningful message (e.g. that image is not (yet) available or smth like that)

### Actual behavior

originally reported in  https://github.com/singularityhub/singularityhub.github.io/issues/48#issuecomment-323472478

### Steps to reproduce behavior

pull an image which is currently (re)building:
```shell
$> singularity pull --commit shub://yarikoptic/neurodebian-singularity-temp 09c87db52810d6ebbf071420c628aa3eaf184a35
ERROR Error downloading None. Do you have permission to write to /tmp?
2 11245 ->1.....................................:Fri 18 Aug 2017 06:12:38 PM EDT:.
hopa:/tmp
$> touch 1
```

**Comment by jscook2345** [comment]
This appears to be fixed in at least 3.X. Thanks for the report @yarikoptic !
