### ISSUE TITLE
unprivileged singularity code is not relocatable

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#887]
## Version of Singularity:

2.3.1 and current development branch

### Expected behavior

For unprivileged installations of singularity it would be helpful for the code to be easily relocatable.  There is a "prefix" setting at the beginning of bin/singularity and I would expect the code to be able to be relocated by changing that value.

### Actual behavior

Changing "prefix" appears to affect the script portions of singularity but not the binary portions.  The first error is 
```
/home/dwd/singularity-reloc/libexec/singularity/bin/action: error while loading shared libraries: libsingularity-image.so.1: cannot open shared object file: No such file or directory
```
I can get past that by setting 
```
LD_LIBRARY_PATH=$HOME/singularity-reloc/lib/singularity
```
but then it fails with
```
ERROR  : Specified configuration file /home/dwd/singularity/etc/singularity/singularity.conf does not appear to be a normal file.
ERROR  : Could not open configuration file /home/dwd/singularity/etc/singularity/singularity.conf: No such file or directory
ERROR  : Called singularity_config_get_value on uninitialized config subsystem
```
and I see that the code has a compiled-in value SYSCONFDIR that is not affected by the SINGULARITY_*dir environment variables exported by the singularity script indicating the runtime directories.  Clearly the suid programs can't honor the environment variables, but the non-suid ones could.

### Steps to reproduce behavior

Compile singularity with "./configure --prefix $HOME/singularity" and "make install" on a system that supports unprivileged singularity.  Edit the prefix in $HOME/singularity/bin/singularity to a new path and move $HOME/singularity to that new path.

**Comment by cclerget** [comment]
Hi @DrDaveD, for security reasons, SUID programs don't honor environment variables like LD_LIBRARY_PATH, LD_PRELOAD, so it's a normal behaviour

Relocatable installation seems difficult because there is many hardcoded path (SYSCONFDIR, LIBEXECDIR, path to configuration file). In C code these value are not environment variables but preprocessor defines so impossible to change.

**Comment by DrDaveD** [comment]
@cclerget Yes I know that SUID programs need the fixed path, as I said.  It does not seem difficult to me to introduce, however, because the #define paths could be replaced by a function call, macro, or variable that has the value of the fixed path in the -suid programs or the corresponding environment variable in the non-suid programs.

**Comment by cclerget** [comment]
@DrDaveD does the steps ./configure && make && make install as normal user is not sufficient for your needs ?

**Comment by DrDaveD** [comment]
Correct, it is not sufficient.  I want to be able to relocate binaries after install so I can compile on one machine and send a tarball of the install directory to many other machines on a grid which will have different temporary paths they can work in.

**Comment by cclerget** [comment]
You don't have access to a common /tmp or /var/tmp directory on every nodes ?

If it can help you, I made something similar for a zero conf/deploy script by statically compiling singularity, just compile it on node with the older kernel if grid nodes have different kernel version

For pure static binaries :
`LDFLAGS="-static -Wl,-Bstatic -lc -no-pie" CFLAGS="-static -Wl,-Bstatic -lc -static-libgcc -no-pie" CPPFLAGS="-static -Wl,-Bstatic -lc -static-libgcc -no-pie" ./configure --enable-static --prefix=/tmp/sing-static`

and deploy on /tmp/sing-static on every nodes

**Comment by DrDaveD** [comment]
Yes there is /tmp and /var/tmp but grid jobs are given their own scratch space they're supposed to work in.  Common software is used by different projects and they can't all write to the same path in /tmp.

**Comment by gmkurtzer** [comment]
Oh, it is good to know that unprivileged Singularity is being used, but to make it easily relocatable would take a fair amount of diversion from the shared code path that relies on static locations for security.

**Comment by DrDaveD** [comment]
@gmkurtzer I don't think it should take very much of a diversion.  Just replace the #define with a function call or macro that does the current behavior for suid binaries and looks up the environment variable for the non-suid binary.  I'll make a PR if you'll consider it.
