### ISSUE TITLE
[./autogen.sh] is not processed properly

### ISSUE THREAD

**Issue by jgrzebyta** [apptainer/singularity#888]
## Version of Singularity:

Branch `development` at commit 4d70c3c72f40b8efadc429b38993ef6e34ee7f33

### Expected behavior

Genarate `configure` with all expected files.

### Actual behavior

On ubuntu machine `./autogen.sh` bash interpreter is not recognised in DOS formatted file:

```
/bin/sh^M: bad interpreter: No such file or directory
```

### Steps to reproduce behavior

```
./autogen.sh
```

**Comment by cclerget** [comment]
@jgrzebyta `dos2unix autogen.sh` should correct your problem. Can't reproduce, did your edit the file after cloning repo ?

**Comment by jgrzebyta** [comment]
On 23 August 2017 at 17:02, cclerget <notifications@github.com> wrote:

> @jgrzebyta <https://github.com/jgrzebyta> dos2unix autogen.sh should
> correct your problem.
>
That fixed problem. But another issue appeared:

```
jacek@XXXXXXXXX:~/Projects/singularity$ ./autogen.sh
+autoreconf -i -f
' is already registered with AC_CONFIG_FILES.
../../lib/autoconf/status.m4:288: AC_CONFIG_FILES is expanded from...
configure.ac:343: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

```

Probably some additional libraries are needed. in another ubuntu machine
both autogen is started correctly and compilation goes well.

Can't reproduce, did your edit the file after cloning repo ?
>
No I did not change the file.

**Comment by cclerget** [comment]
missing packages, require following packages : `apt-get install automake autoconf libtool`

**Comment by vsoch** [comment]
+1 - see the top of the script I use for the Singularity Hub builder for a list of (possibly needed) additional dependencies! https://github.com/singularityware/singularity-python/blob/master/singularity/build/scripts/singularity-build-latest.sh

**Comment by jgrzebyta** [comment]
@cclerget @vsoch I did both things and did not help.

**Comment by vsoch** [comment]
Are you on windows? Or "ubuntu running on windows" ? This error:

```
is already registered with AC_CONFIG_FILES.
```
seems to be related to those `^M` characters. I would either do dos2unix for ALL files, or start again with a fresh clone - possibly away from where the files could get corrupt like that?

**Comment by jgrzebyta** [comment]
@vsoch I in Ubuntu installed directly on HD not in any VM. I guess dos2unix should be done on all files. I have no idea why it was not problem on another machine with the same OS.

**Comment by dtrudg** [comment]
Closing this issue as have not been able to reproduce with current Singularity. Please let us know if any issue persists for you. Thanks!
