### ISSUE TITLE
bootstrap fails for xfs image

### ISSUE THREAD

**Issue by surfr326** [apptainer/singularity#89]
**Host**: CentOS 7.2 minimal virtual machine with xfs filesystem
**Singularity 2.1** (current master branch as of 6/23)

**Definition file**:
DistType "redhat"
MirrorURL "http://my.local.repo.path/"

Setup
Bootstrap

InstallPkgs yum vi

Cleanup

**Create the image**:
singularity create -f xfs centos.img
Creating a sparse image with a maximum size of 1024MB...
Formatting image (/sbin/mkfs.xfs)
Done. Image can be found at: centos.img

**Bootstrap output**:
singularity -d bootstrap centos.img centos.def
enabling debugging
ending argument loop
- true
- case $1 in
- break
- '[' -z centos.img ']'
- '[' 0 '!=' 0 ']'
- IMAGE=centos.img
- DEFINITION=centos.def
- shift
- shift
- '[' '!' -f centos.img ']'
- '[' '!' -f centos.def ']'
- SINGULARITY_libexecdir=/usr/libexec
- SINGULARITY_BUILD_ROOT=/var/singularity/mnt
- export SINGULARITY_libexecdir SINGULARITY_BUILD_ROOT
- '[' '!' -d /var/singularity/mnt ']'
- exec /usr/libexec/singularity/image-mount centos.img /var/singularity/mnt /usr/libexec/singularity/bootstrap.sh centos.def
  ERROR: Failed to mount (rw) '/dev/loop0' at '/var/singularity/mnt': Invalid argument
  ABORT: exiting...

It works fine with ext3 or ext4.

Thanks guys!
-Danny

**Comment by gmkurtzer** [comment]
Oh yeah, that is expected... Sorta. At the moment, I am just trying to mount the image as ext3/4. I'm curious if it makes sense to try some additional formats... OR... limit the fstypes that 'create' can create.

Thoughts?

**Comment by surfr326** [comment]
I think limiting what create -f will accept as an argument makes sense, and throw an appropriate error indicating if a format is not supported.

**Comment by gmkurtzer** [comment]
This check for ext3/4 has been added to the create command in master 5ce53ac.

Thanks!
