### ISSUE TITLE
too many symbolic links

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#890]
posting for a user:

I am trying to run fmriprep<https://readthedocs.org/projects/fmriprep/> using Singularity on Sherlock and getting the "Too many levels of symbolic links" error. Not sure why? any help!

The container runs just fine on the entry node, but when submitted as a job using sbatch, the job fails quickly with the following error:

```
ERROR : There was an error binding the path /share/PI: Too many levels of symbolic links 
ABORT : Retval = 255
```

Here are more details about the job etc.

1. Tried a couple of times, job IDs 16941871 and 16941659 
2. Version of the poldracklab/fmriprep image [made today] - poldracklab_fmriprep_latest-2017-08-12-b143b2240628.img 
3. Running data in Scratch space at Sherlock, using the following command

```
singularity run -B /scratch/PI/saggar/BIDS-bidskit:/data:ro -B /scratch/PI/saggar/BIDS-bidskit-output:/out poldracklab_fmriprep_latest-2017-08-12-b143b2240628.img /data /out/out participant --participant-label 10s1 --use-aroma --skull-strip-ants --no-freesurfer --no-submm-recon
```

**Comment by AdamSimpson** [comment]
Is /share/PI autofs mounted? If it is I see the same behavior unless I first cause a mount on the host. To get around that issue I have a singularity wrapper script that does an ls on the autofs mounted directories before involking the real singularity binary as a quick and dirty workaround.

There are a few open and closed issues related to this but recently @cclerget  confirmed this is a kernel issue here: https://github.com/singularityware/singularity/issues/347 .

The good news is that it looks like a workaround may be in place although I haven't tested it yet: https://github.com/singularityware/singularity/pull/877

Edit: I tested the latest development branch and used the autofs bug config options and all is well, great job!

**Comment by vsoch** [comment]
yes it is, and this is exactly the issue! @manishsaggar would you like to try some of the workarounds?

**Comment by dtrudg** [comment]
Closing this as autofs workarounds were previously merged and we haven't had further report of issues on this ticket. Please let us know if any outstanding issues. There are other autofs tickets related still open, and we'd like to identify the specific cases with issues remaining, so if this one isn't working it'd be great to reopen here. Thanks!
