### ISSUE TITLE
compile fails on centos6 with undefined reference to setns

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#896]
## Version of Singularity:

current development branch

### Expected behavior

compile succeeds

### Actual behavior

compile fails with this error message:
```
lib/runtime/.libs/libsingularity-runtime.so: undefined reference to `setns'
```

### Steps to reproduce behavior

After including pr #895, uncomment the centos6 matrix entry in .travis.yml and look at the travis build output.  Here's an [example failed build](https://travis-ci.org/DrDaveD/singularity/jobs/268429197).

**Comment by dtrudg** [comment]
Closing as this issue was fixed with merged PR #902 - let us know if there are any outstanding problems. Thanks!
