### ISSUE TITLE
Error while creating image as non-root user

### ISSUE THREAD

**Issue by mohanasudhan** [apptainer/singularity#900]
I used spack to load singularity and here is the command i used to create image

singularity -vvvv create test.img
Increasing verbosity level (5)
Ending argument loop
Singularity version: 2.3.1-dist
Exec'ing: /home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/libexec/singularity/cli/create.exec
VERBOSE [U=1000,P=117581]  message_init()                            Set messagelevel to: 5
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Initialize configuration file: /home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/etc/singularity/singularity.conf
DEBUG   [U=1000,P=117581]  singularity_config_parse()                Starting parse of configuration file /home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/etc/singularity/singularity.conf
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key allow setuid = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key max loop devices = '256'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key allow pid ns = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key config passwd = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key config group = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key config resolv_conf = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key mount proc = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key mount sys = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key mount dev = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key mount home = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key mount tmp = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key mount hostfs = 'no'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key bind path = '/etc/localtime'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key bind path = '/etc/hosts'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key user bind control = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key enable overlay = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key mount slave = 'yes'
VERBOSE [U=1000,P=117581]  singularity_config_parse()                Got config key sessiondir max size = '16'
DEBUG   [U=1000,P=117581]  singularity_config_parse()                Finished parsing configuration file '/home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/etc/singularity/singularity.conf'
VERBOSE [U=1000,P=117581]  singularity_registry_init()               Initializing Singularity Registry
VERBOSE [U=1000,P=117581]  singularity_registry_set()                Adding value to registry: 'WRITABLE' = '1'
DEBUG   [U=1000,P=117581]  singularity_registry_set()                Returning singularity_registry_set(WRITABLE, 1) = 0
VERBOSE [U=1000,P=117581]  singularity_registry_set()                Adding value to registry: 'LIBEXECDIR' = '/home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/libexec'
DEBUG   [U=1000,P=117581]  singularity_registry_set()                Returning singularity_registry_set(libexecdir, /home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/libexec) = 0
VERBOSE [U=1000,P=117581]  singularity_registry_set()                Adding value to registry: 'COMMAND' = 'create'
DEBUG   [U=1000,P=117581]  singularity_registry_set()                Returning singularity_registry_set(COMMAND, create) = 0
VERBOSE [U=1000,P=117581]  singularity_registry_set()                Adding value to registry: 'MESSAGELEVEL' = '5'
DEBUG   [U=1000,P=117581]  singularity_registry_set()                Returning singularity_registry_set(MESSAGELEVEL, 5) = 0
VERBOSE [U=1000,P=117581]  singularity_registry_set()                Adding value to registry: 'VERSION' = '2.3.1-dist'
DEBUG   [U=1000,P=117581]  singularity_registry_set()                Returning singularity_registry_set(version, 2.3.1-dist) = 0
VERBOSE [U=1000,P=117581]  singularity_registry_set()                Adding value to registry: 'LOCALSTATEDIR' = '/home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/var'
DEBUG   [U=1000,P=117581]  singularity_registry_set()                Returning singularity_registry_set(localstatedir, /home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/var) = 0
VERBOSE [U=1000,P=117581]  singularity_registry_set()                Adding value to registry: 'SYSCONFDIR' = '/home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/etc'
DEBUG   [U=1000,P=117581]  singularity_registry_set()                Returning singularity_registry_set(sysconfdir, /home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/etc) = 0
VERBOSE [U=1000,P=117581]  singularity_registry_set()                Adding value to registry: 'BINDIR' = '/home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/bin'
DEBUG   [U=1000,P=117581]  singularity_registry_set()                Returning singularity_registry_set(bindir, /home/ubuntu/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/singularity-2.3.1-vzcfj5vl52au7yoc5v7ceuzbjwid4ba3/bin) = 0
VERBOSE [U=1000,P=117581]  singularity_registry_set()                Adding value to registry: 'IMAGE' = 'test.img'
DEBUG   [U=1000,P=117581]  singularity_registry_set()                Returning singularity_registry_set(IMAGE, test.img) = 0
DEBUG   [U=1000,P=117581]  singularity_registry_get()                Returning NULL on 'HOME'
DEBUG   [U=1000,P=117581]  singularity_registry_get()                Returning NULL on 'TARGET_UID'
DEBUG   [U=1000,P=117581]  singularity_registry_get()                Returning NULL on 'TARGET_GID'
DEBUG   [U=1000,P=117581]  singularity_priv_init()                   Initializing user info
DEBUG   [U=1000,P=117581]  singularity_priv_init()                   Set the calling user's username to: ubuntu
DEBUG   [U=1000,P=117581]  singularity_priv_init()                   Marking uinfo structure as ready
DEBUG   [U=1000,P=117581]  singularity_priv_init()                   Obtaining home directory
VERBOSE [U=1000,P=117581]  singularity_priv_init()                   Set home (via getpwuid()) to: /home/ubuntu
VERBOSE [U=1000,P=117581]  singularity_suid_init()                   Running NON-SUID program workflow
DEBUG   [U=1000,P=117581]  singularity_suid_init()                   Checking program has appropriate permissions
VERBOSE [U=1000,P=117581]  singularity_priv_drop()                   Could not restore EUID to 0: Operation not permitted (errno=1).
DEBUG   [U=1000,P=117581]  singularity_priv_drop()                   Dropping privileges to UID=1000, GID=1000 (12 supplementary GIDs)
DEBUG   [U=1000,P=117581]  singularity_priv_drop()                   Restoring supplementary groups
DEBUG   [U=1000,P=117581]  singularity_priv_drop()                   Confirming we have correct UID/GID
DEBUG   [U=1000,P=117581]  singularity_registry_get()                Returning NULL on 'IMAGESIZE'
INFO    [U=1000,P=117581]  main()                                    Initializing Singularity image subsystem
DEBUG   [U=1000,P=117581]  singularity_registry_get()                Returning value from registry: 'IMAGE' = 'test.img'
INFO    [U=1000,P=117581]  main()                                    Opening image file: test.img
DEBUG   [U=1000,P=117581]  singularity_config_get_value_impl()       No configuration entry found for 'limit container owners'; returning default value 'NULL'
DEBUG   [U=1000,P=117581]  singularity_config_get_value_impl()       No configuration entry found for 'limit container paths'; returning default value 'NULL'
DEBUG   [U=1000,P=117581]  singularity_image_open()                  Opening file descriptor to image: test.img
DEBUG   [U=1000,P=117581]  singularity_suid_enabled()                Executable is not root owned
INFO    [U=1000,P=117581]  main()                                    Creating 768MiB image
VERBOSE [U=1000,P=117581]  singularity_image_create()                Writing image header
VERBOSE [U=1000,P=117581]  singularity_image_create()                Growing image to 768MB
INFO    [U=1000,P=117581]  main()                                    Binding image to loop
DEBUG   [U=1000,P=117581]  singularity_config_get_value_impl()       Returning configuration value max loop devices='256'
DEBUG   [U=1000,P=117581]  singularity_image_bind()                  Entered singularity_image_bind()
DEBUG   [U=1000,P=117581]  singularity_image_bind()                  Converting max_loop_devs_string to int: '256'
DEBUG   [U=1000,P=117581]  singularity_image_bind()                  Converted max_loop_devs_string to int: '256' -> 256
DEBUG   [U=1000,P=117581]  singularity_image_bind()                  Checking if this image has been properly opened
DEBUG   [U=1000,P=117581]  singularity_image_bind()                  Checking if image is valid file
DEBUG   [U=1000,P=117581]  singularity_image_bind()                  Checking if image is already bound to a loop device
DEBUG   [U=1000,P=117581]  singularity_registry_get()                Returning value from registry: 'WRITABLE' = '1'
DEBUG   [U=1000,P=117581]  singularity_image_bind()                  Setting loopdev open to: O_RDWR
DEBUG   [U=1000,P=117581]  singularity_image_bind()                  Setting LO_FLAGS_AUTOCLEAR
DEBUG   [U=1000,P=117581]  singularity_image_bind()                  Calculating image offset
VERBOSE [U=1000,P=117581]  singularity_image_check()                 Checking what kind of image we are mounting
VERBOSE [U=1000,P=117581]  singularity_image_check_image()           Checking that file pointer is a Singularity image
DEBUG   [U=1000,P=117581]  singularity_image_check_image()           First line of image(fd=4): #!/usr/bin/env run-singularity

DEBUG   [U=1000,P=117581]  singularity_image_check_image()           Checking if first line matches key
VERBOSE [U=1000,P=117581]  singularity_image_check_image()           File is a valid Singularity image
VERBOSE [U=1000,P=117581]  singularity_image_offset()                Calculating image offset
VERBOSE [U=1000,P=117581]  singularity_image_offset()                Found image at an offset of 31 bytes
DEBUG   [U=1000,P=117581]  singularity_image_offset()                Returning image_offset(image_fp) = 31
DEBUG   [U=1000,P=117581]  singularity_priv_escalate()               Temporarily escalating privileges (U=1000)
ERROR   [U=1000,P=117581]  singularity_priv_escalate()               The feature you are requesting requires privilege you do not have
ABORT   [U=1000,P=117581]  singularity_priv_escalate()               Retval = 255

**Comment by AdamSimpson** [comment]
Root is required at install time so that the singularity setuid executables work correctly, which spack doesn't handle correctly. This issue is being tracked here https://github.com/LLNL/spack/issues/4432 . In the meantime you'll want to install singularity outside of spack.

**Comment by mohanasudhan** [comment]
Thanks, Ya installing outside of spack works for me. closing the issue as its tracked in spack end.
