### ISSUE TITLE
If singularity is built in a chroot on el6, it fails at startup with an overlay failure

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#909]
## Version of Singularity:

2.3.1

### Expected behavior

Don't attempt to use overlayfs on an el6 which does not support it.

### Actual behavior

It gets an error:
```
ERROR  : Could not mount Singularity overlay: No such device
ABORT  : Retval = 255
```

### Steps to reproduce behavior

Build singularity under a chroot system such as koji.  Then configure discovers overlayfs as "maybe".  It then defines SINGULARITY_OVERLAYFS so it always tries it, although it does not set OVERLAY_FS=1 so it doesn't does try to test it in test.sh.

**Comment by DrDaveD** [comment]
I don't know yet what the solution is.  Perhaps configure should have a command line option to select it, and singularity.spec should set the value off for el6 and on otherwise.  Or perhaps configure should look in /proc/modules for the 'overlay' module if it can't find modules.dep, but then the build machine has to have the overlay module pre-loaded, not just present.

**Comment by DrDaveD** [comment]
I don't know yet what the solution is.  Perhaps configure should have a command line option to select it, and singularity.spec should set the value off for el6 and on otherwise.  Or perhaps configure should look in /proc/modules for the 'overlay' module if it can't find modules.dep, but then the build machine has to have the overlay module pre-loaded, not just present.

**Comment by DrDaveD** [comment]
The Open Science Grid koji build machine is el6 and runs both el6 and el7 builds under different chroot images.  So the whole approach of looking in modules.dep or /proc/modules for a driver can't work there.  Pr #912 makes it do a runtime check instead, and continue without an error if overlay is not available.

**Comment by dtrudg** [comment]
Closing this as PR #912 was merged. Please let us know if any remaining problems. Thanks!
