### ISSUE TITLE
singularity fails to write docker images on ~/.singularity/docker

### ISSUE THREAD

**Issue by soichih** [apptainer/singularity#910]
## Version of Singularity:

2.3.1-dist

### Expected behavior

It should allow me to run singularity with following command

```
$ singularity run docker://brainlife/life
```

### Actual behavior

I get following error message.

```
$ singularity run docker://brainlife/life
Docker image path: index.docker.io/brainlife/life:latest
Cache folder set to /home/hayashis/.singularity/docker
[1/6] ||----------------------------------|   0.0% ERROR Error downloading https://index.docker.io/v2/brainlife/life/blobs/sha256:5b3aa5c7f165af2de4f39b60e35b79a1a54778dbbf6e8a250da1fdd8fe3238c2. Do you have permission to write to /home/hayashis/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/brainlife/life/blobs/sha256:a887527709f12e206035df27174be037a18619847e525d4b73096938b924999a. Do you have permission to write to /home/hayashis/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/brainlife/life/blobs/sha256:8a898e9d2dc436ef3298149ec53de3fd41ee36d26c40c9020689ef1aed7927a8. Do you have permission to write to /home/hayashis/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/brainlife/life/blobs/sha256:37e3fac068362b0889e1753ff784da853f4e807dc5addc77e1050b5eb1292360. Do you have permission to write to /home/hayashis/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/brainlife/life/blobs/sha256:d787be73d1b1f4692995f4537c30faa943e5ed12d886c992fb99918b7df4c22e. Do you have permission to write to /home/hayashis/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/brainlife/life/blobs/sha256:7b52546cd236a36eb13b804a53738936f7b091743f9688794339cc815be52e97. Do you have permission to write to /home/hayashis/.singularity/docker?

```

### Steps to reproduce behavior

I have access to ~/singularity/docker, and I can read/write to it. However, my /home directory is a mounted cifs volume on Azure. Following is how I am mounted /home

```
//brainlife.file.core.windows.net/slurm1-home /home cifs vers=2.1,username=brainlife,password=mypass==,dir_mode=0750,file_mode=0750,uid=hayashis,gid=hayashis,serverino 0 0
```

Is it not possible to use home directory that is Azure File (cifs) mount point?

**Comment by soichih** [comment]
Update..

I found that cifs(smb) doesn't support ":" (colon) as part of file name

> A filename cannot contain any of the following characters: \ / : * ? " < > |

When singularity tries to write the docker layer to ~/.singularity/docker, it uses docker image ID that contains "sha256:" as file names so it fails to write.

> sha256:a887527709f12e206035df27174be037a18619847e525d4b73096938b924999a.tar.gz

I was able to patch the singularity python scripts to replace ":" with ".", but I am not sure if singularity is planning on supporting cifs, or if there is a better way to handle this.  Should I submit a PR?

**Comment by vsoch** [comment]
oh that's very interesting - just curious, do you have Docker on that machine (or similar) and how do they handle the naming issue? It would be good to find out what Docker does and follow suit!

**Comment by soichih** [comment]
I just tested Docker by pointing its root path to /home/docker (/home is where the SMB/cifs volume is mounted) and ran into following error message.

```
docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
d5c6f90da05d: Extracting [==================================================>]  47.26MB/47.26MB
1300883d87d5: Download complete 
c220aa3cfc1b: Download complete 
2e9398f099dc: Download complete 
dc27a084064f: Download complete 
failed to register layer: Error processing tar file(exit status 1): symlink hostname /bin/dnsdomainname: operation not supported
```

I normally use default docker root path (/var/lib/docker) with standard file systems (ext4, xfs, etc..) so I don't expect to run into this issue with Docker. Since singularity has to use user's home directory to store container image, I believe singularity should be able to support shared home directories such as SMB/cifs - or at least allow user to override the ~/.singularity path?

**Comment by vsoch** [comment]
Are you able to just set the cache to be elsewhere? Eg set `SINGULARITY_CACHEDIR=/tmp` (or on some filesystem that would allow the `:`)

**Comment by soichih** [comment]
Yes, that will work - although the cache won't be shared across all nodes on my cluster.  But for now I can live with that.

If ":" is the only issue, though, can it be updated to use other character to store the cache so that it will work on shared SMB3 file system? I can send a PR for this.

**Comment by vsoch** [comment]
The problem with `.` is that if the file is ever parsed to separate some extension, the entire end will be considered the extension. @gmkurtzer what are your thoughts on this? I think it would be possible and easy to provide an option to change the names, but I wouldn't want it to be default. The problem is that the cache figures out the layers missing based on the name, so there can easily be a mismatch given that the trigger is on and then off (for whatever reason).

**Comment by dtrudg** [comment]
':' is no longer used in cache directories in the latest Singularity, so this should be fixed.
