### ISSUE TITLE
Get Singularity updates in EPEL

### ISSUE THREAD

**Issue by brianv0** [apptainer/singularity#914]
## Version of Singularity:

2.2.1

### Expected behavior

Get 2.3.1 in EPEL

### Actual behavior

Only 2.2.1 is in EPEL

The current version of Singularity in EPEL is 2.2.1. I'd really like to/need to get 2.3.1 in there because it has a few things that work much better for us, with the additional issue that I need it installed in a few datacenters, neither of which want to install by source.

We're having a hard time making contact with the package maintainer, with several attempts over the last few months. I believe @bbockelm was requesting admin access to be able to maintain the package, without response as well.

There is a (relatively slow) process to go through if the maintainer is unresponsive, but I'm not sure what the implications are:
https://fedoraproject.org/wiki/Policy_for_nonresponsive_package_maintainers#Outline

I'd imagine I'm not the only person having this issue, so I thought I'd bring it up here to see what others thought about it, or to see if anybody has contact with the current maintainer, whom I believe is Dave Love at the University of Manchester.

**Comment by DrDaveD** [comment]
If it is any help: because of the non-responsiveness of the EPEL maintainer, the Open Science Grid is scheduled to release singularity-2.3.1 to their [osg yum repository](https://opensciencegrid.github.io/docs/common/yum/) on September 12, including a split between singularity and singularity-runtime packages as was done on EPEL.  At the moment it is in osg-testing.

**Comment by brianv0** [comment]
@DrDaveD : I think that might be fine for my purposes, I'll have to ask the system admins, thanks.

**Comment by jakirkham** [comment]
Think this should be closed, right? Seems like this is already in the EPEL.

**Comment by DrDaveD** [comment]
Indeed, I have updated singularity in EPEL.  This can be closed (but I don't have permission to do it).

**Comment by brianv0** [comment]
Okay great, thanks!
