### ISSUE TITLE
import docker image Error

### ISSUE THREAD

**Issue by yangyang-zhang** [apptainer/singularity#918]
[root@hpcst test]# singularity --version
2.3.1-dist
[root@hpcst test]# docker save ubuntu:latest > ubuntu.tar
[root@hpcst test]# singularity create ubuntu.img
Initializing Singularity image subsystem
Opening image file: ubuntu.img
Creating 768MiB image
Binding image to loop
Creating file system within image
Image is done: ubuntu.img
[root@hpcst test]# ls 
ubuntu.img  ubuntu.tar
[root@hpcst test]# cat ubuntu.tar  | singularity import ubuntu.img 
/usr/bin/tar: manifest.json: implausibly old time stamp 1969-12-31 19:00:00
/usr/bin/tar: repositories: implausibly old time stamp 1969-12-31 19:00:00
[root@hpcst test]# cat ubuntu.tar  | singularity import ubuntu.img --warning=no-timestamp
[root@hpcst test]# singularity shell -w ubuntu.img 
ERROR  : No valid /bin/sh in container
ABORT  : Retval = 255

I don't know why import image error,help me

**Comment by yangyang-zhang** [comment]
Add one point , docker ubuntu image is official image

**Comment by zhcf** [comment]
same problem,

docker --version
Docker version 17.05.0-ce, build 89658be

**Comment by vsoch** [comment]
I'm not sure where you read to do:

```
docker save ubuntu:latest > ubuntu.tar
```

but that's not a supported way to import from docker. Try:

```
singularity pull docker://ubuntu
```

or

```
singularity create ubuntu.img
singularity import ubuntu.img docker://ubuntu
```

**Comment by zhcf** [comment]
[root@localhost ~]# singularity import --help
USAGE: singularity [...] import <container path> [import from URI]

Import takes a URI and will populate a container with the contents of
the URI. If no URI is given, import will expect an incoming tar pipe.

The size of the container you need to create to import a complete system
may be significantly larger than the size of the tar file/stream due to
overheads of the container filesystem.

SUPPORTED URIs:

    docker:     Pull an image from the Docker repository

EXAMPLES:

    Once you have created the base image template:

    $ singularity create /tmp/Debian.img

    You can then import:

    $ gunzip -c debian.tar.gz | singularity import /tmp/Debian.img
    $ singularity import /tmp/Debian.img docker://ubuntu:latest

For additional help, please visit our public documentation pages which are
found at:

    http://singularity.lbl.gov/

**Comment by zhcf** [comment]
@vsoch, we met this issue because our node is in the cluster, it can not access the public network, so we want to save the docke image as a tar, then import the tar in the singularity. And we see that this is supported in the import manual.

**Comment by zhcf** [comment]
@vsoch, btw, we use mirror for downloading the docker image since index.docker.io can not be access sometime and with limited speed in China.

Anyway, from my view, if singularity just allow importing image from the  index.docker.io, it is not good enough, it should also allow importing from the local file.

**Comment by AdamSimpson** [comment]
Perhaps this is a different issue but newer DockerHub images do not seem to work at all. The ubuntu images got updated last night and now they no longer work, other newly uploaded images fail as well:

$ singularity pull --size 1000 docker://ubuntu
Initializing Singularity image subsystem
Opening image file: ubuntu.img
Creating 1000MiB image
Binding image to loop
Creating file system within image
Image is done: ./ubuntu.img
Docker image path: index.docker.io/library/ubuntu:latest
ERROR Improperly formed manifest, layers or fsLayers must be present

I am not familiar with Docker but I can preform a "docker pull ubuntu" just fine.

**Comment by vsoch** [comment]
yeah we just fixed this on development - basically now the image can return a "list of manifests" so the "layers" and (actually the list of "digests") are one layer down.

```
{'manifests': [{'digest': 'sha256:b82b5740006c1ab823596d2c07f081084ecdb32fd258072707b99f52a3cb8692',
   'mediaType': 'application/vnd.docker.distribution.manifest.v2+json',
   'platform': {'architecture': 'amd64', 'os': 'linux'},
   'size': 527},
  {'digest': 'sha256:9142d97ef280a7953cf1a85716de49a24cc1dd62776352afad67e635331ff77a',
   'mediaType': 'application/vnd.docker.distribution.manifest.v2+json',
   'platform': {'architecture': 'arm', 'os': 'linux', 'variant': 'v5'},
   'size': 527},
  {'digest': 'sha256:b5dbad4bdb4444d919294afe49a095c23e86782f98cdf0aa286198ddb814b50b',
   'mediaType': 'application/vnd.docker.distribution.manifest.v2+json',
   'platform': {'architecture': 'arm', 'os': 'linux', 'variant': 'v6'},
   'size': 527},
  {'digest': 'sha256:a8fe0549cac196f439de3bf2b57af14f7cd4e59915ccd524428f588628a4ef31',
   'mediaType': 'application/vnd.docker.distribution.manifest.v2+json',
   'platform': {'architecture': 'arm', 'os': 'linux', 'variant': 'v7'},
   'size': 527},
  {'digest': 'sha256:dc472a59fb006797aa2a6bfb54cc9c57959bb0a6d11fadaa608df8c16dea39cf',
   'mediaType': 'application/vnd.docker.distribution.manifest.v2+json',
   'platform': {'architecture': 'arm64', 'os': 'linux', 'variant': 'v8'},
   'size': 527},
  {'digest': 'sha256:9a33b9909e56b0a2092a65fb1b79ef6717fa160b1f084476b860418780e8d53b',
   'mediaType': 'application/vnd.docker.distribution.manifest.v2+json',
   'platform': {'architecture': '386', 'os': 'linux'},
   'size': 527},
  {'digest': 'sha256:59117d7c016fba6ede7f87991204bd672a1dca444102de66db632383507ed90b',
   'mediaType': 'application/vnd.docker.distribution.manifest.v2+json',
   'platform': {'architecture': 'ppc64le', 'os': 'linux'},
   'size': 528},
  {'digest': 'sha256:e5aa1b0a24620228b75382997a0977f609b3ca3a95533dafdef84c74cc8df642',
   'mediaType': 'application/vnd.docker.distribution.manifest.v2+json',
   'platform': {'architecture': 's390x', 'os': 'linux'},
   'size': 528}],
 'mediaType': 'application/vnd.docker.distribution.manifest.list.v2+json',
 'schemaVersion': 2}

```
In the future when we care about architecture, we'd want to parse that and get a specific manifest. For now, we ask for the older version (that has fsLayers) and use that. Did you try this on development? This might be something that needs to go in as a "quick fix" for all images soon. @gmkurtzer what do you think?

**Comment by GodloveD** [comment]
Docker changed their manifest in the last release.  Vanessa has already
created a hotfix PR to development.

https://github.com/singularityware/singularity/pull/922

But it doesn't look like it has made it's way to master yet.  I'm talking
to Greg about this.

**Comment by vsoch** [comment]
ok thanks @GodloveD !

**Comment by GodloveD** [comment]
Or you can talk to him too @vsoch.  Our messages crossed.  😄

**Comment by AdamSimpson** [comment]
Thanks! I was quite confused this morning when all my builds were failing.

**Comment by vsoch** [comment]
This should be all fixed - please re-open if needed.
