### ISSUE TITLE
Whether singularity has the plan to support importing the docker image from the docker private registry 

### ISSUE THREAD

**Issue by zhcf** [apptainer/singularity#920]
## Version of Singularity:

2.3.1

### Expected behavior

Whether there is a way to support importing the docker image from the docker private registry?

**Comment by vsoch** [comment]
You can already do this. http://singularity.lbl.gov/docs-docker#authentication-in-the-environment

**Comment by zhcf** [comment]
The problem is: I write my registry url in the singularity pull command, singularity does not pull from my registry, **still trying from the index.docker.io**

[root@localhost docker]# singularity import test.img docker://registry.docker-cn.com/centos
Docker image path: **index.docker.io/registry.docker-cn.com**/centos:latest
ERROR Improperly formed manifest, layers or fsLayers must be present
[root@localhost docker]# singularity import test.img docker://127.0.0.1:5000/centos
Docker image path: **index.docker.io/127.0.0.1:5000**/centos:latest

**Comment by vsoch** [comment]
It looks like it's parsing the registry name, try giving it a tag to see if that works:

```
singularity import test.img docker://registry.docker-cn.com/centos:latest
```
The issue about the manifest is a global bug for all because of a recent change to the docker manifests, we are working on a fix now.

**Comment by hisplan** [comment]
I have a similar issue. I have a local docker registry running at localhost:5000. I have something like below in `Singularity` file, and with Singularity v2.2.1 this successfully imported the docker image from the local registry, and generated a Singularity image.

```
Bootstrap: docker
From: /pipeline-htstools:0.1.1
Registry: http://localhost:5000
```

However, the same bootstrap file no longer works with v2.3.x. It throws this error:

```
*** STARTING DOCKER IMPORT PYTHON  ****
DEBUG Docker layers and (env,labels,runscript) will be written to: /tmp/.singularity-layers.IIOrhSqg
VERBOSE2 SINGULARITY_DOCKER_USERNAME not defined (None)
VERBOSE2 SINGULARITY_DOCKER_PASSWORD found
DEBUG Starting Docker IMPORT, includes environment, runscript, and metadata.
VERBOSE Docker image: /pipeline-htstools:0.1.1
VERBOSE2 Specified Docker CMD as %runscript.
DEBUG Headers found: Content-Type,Accept
VERBOSE Registry: index.docker.io
VERBOSE Namespace:
VERBOSE Repo Name: pipeline-htstools
VERBOSE Repo Tag: 0.1.1
VERBOSE Version: None
ERROR  found empty, check uri! Exiting.
```

Is this a known bug or has the syntax been slightly changed??

**Comment by vsoch** [comment]
I would try including the registry as part of the uri in the From.

**Comment by hisplan** [comment]
Could you be little more specific? I removed the Registry line and tried a few different From lines, but none worked. :-(

**Comment by vsoch** [comment]
Try:

```
Bootstrap: docker
From: http://localhost:5000/<reponame>/pipeline-htstools:0.1.1
```
If you don't have a reponame, I would try pushing with one (eg repo/pipeline-histools).

**Comment by hisplan** [comment]
Still doesn't work. It prepends docker:// and keeps trying to do something with the official docker registry.

```
VERBOSE2 SINGULARITY_CONTAINER found as docker://http://localhost:5000/roslin/pipeline-htstools:0.1.1
DEBUG Found uri docker://
DEBUG
*** STARTING DOCKER IMPORT PYTHON  ****
DEBUG Docker layers and (env,labels,runscript) will be written to: /tmp/.singularity-layers.waGzYDVC
VERBOSE2 SINGULARITY_DOCKER_USERNAME not defined (None)
VERBOSE2 SINGULARITY_DOCKER_PASSWORD found
DEBUG Starting Docker IMPORT, includes environment, runscript, and metadata.
VERBOSE Docker image: http://localhost:5000/roslin/pipeline-htstools:0.1.1
VERBOSE2 Specified Docker CMD as %runscript.
DEBUG Headers found: Content-Type,Accept
VERBOSE Registry: index.docker.io
VERBOSE Namespace: library
VERBOSE Repo Name: http
VERBOSE Repo Tag: latest
VERBOSE Version: None
VERBOSE Obtaining tags: https://index.docker.io/v2/library/http/tags/list
DEBUG GET https://index.docker.io/v2/library/http/tags/list
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?service=registry.docker.io&expires_in=9000&scope=repository:library/http:pull
DEBUG Headers found: Content-Type,Authorization,Accept
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?service=registry.docker.io&expires_in=9000&scope=repository:library/http:pull"
DEBUG Headers found: Content-Type,Authorization,Accept
Docker image path: index.docker.io/library/http:latest
VERBOSE Obtaining manifest: https://index.docker.io/v2/library/http/manifests/latest
DEBUG GET https://index.docker.io/v2/library/http/manifests/latest
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?service=registry.docker.io&expires_in=9000&scope=repository:library/http:pull"
DEBUG Headers found: Content-Type,Authorization,Accept
DEBUG Http Error with code 401
ERROR Improperly formed manifest, layers or fsLayers must be present
```

Here's my new Singularity:

```
Bootstrap: docker
From: http://localhost:5000/roslin/pipeline-htstools:0.1.1
```

**Comment by vsoch** [comment]
What version of singularity? Could you please try development branch and report back with the debug output?

**Comment by hisplan** [comment]
```
$ singularity --version
2.3-dist
```

**Comment by hisplan** [comment]
I tried all 2.3.x release tags FYI.

**Comment by vsoch** [comment]
please try development. There were a lot of issues and changes with local registry, and a last edit may have caused error even in development! It would be helpful if you could test this for your use case.

**Comment by hisplan** [comment]
Didn't work with dev either.

```
Sanitizing environment
Adding base Singularity environment to container
Docker image path: index.docker.io/library/http:latest
ERROR UNAUTHORIZED: authentication required
ERROR Check existence, naming, and permissions
```

```
$ singularity --version
2.3.9-development.gfadad26
```

Our team has been relatively satisfied with 2.2.1 in the production environment. The only reason we tried 2.3.x was because of this issue: https://github.com/singularityware/singularity/issues/988

**Comment by vsoch** [comment]
Are you able to give me steps to recreate your registry, the build recipe, or access to it so I can define this for you? It's definitely a uri parsing issue.

**Comment by gmkurtzer** [comment]
Heya guys, I'd like to identify and possibly fix this bug before the release of 2.4 (should happen very soon now). @hisplan Do you have a reproducer that we can use to test?

Thanks!

**Comment by bauerm97** [comment]
@vsoch I think we should introduce a better solution to using custom registries than just trying to parse a `docker://blah.io/blah/blah` URI. Why not introduce a way for users to be explicit about what registry they want to use. For instance `singularity pull --registry quay.io docker://user/container` for a pull, or in a bootstrap the ability to be very specific as well:

```
Bootstrap: docker
Registry: http://localhost:5000/
From: roslin/pipeline-htstools:0.1.1
```

or

```
Bootstrap: docker
Registry: http://localhost:5000/
Namespace: roslin
From: pipeline-htstools:0.1.1
```

The more explicit we allow the user to be about their container the better. I'm not sure why it's not working as expected, even in development branch, but I'll take a look as well

**Comment by vsoch** [comment]
I would advocate for the version in the deffile, so it's preserved with the image. I think we did use to have that as an argument before - and possible removed? We could also expose via the environment, eg change the lines here:

https://github.com/singularityware/singularity/blob/development/libexec/python/defaults.py#L116

**Comment by gmkurtzer** [comment]
Can we retest this using the feature that @bauerm97 requested and @vsoch implemented in #1018?

Thanks!

**Comment by lordzappo** [comment]
@vsoch do you need us to test?  @hisplan was on my team until recently, so even though he started this issue, I will finish.

**Comment by vsoch** [comment]
If you need the utility, then yes definitely! If not no worries, it's a very niche / edge use case.

**Comment by dtrudg** [comment]
Closing this, as believe it is addressed by changes mentioned above, and further things that were added to the 2.4.x releases of Singularity. If you still have issues on latest Singularity, please let us know. Thanks!
