### ISSUE TITLE
For 2-step image build: bootstrap method doing nothing?

### ISSUE THREAD

**Issue by weidendo** [apptainer/singularity#929]
## Version of Singularity: 2.3.1

We want to do an image build in two steps: the first one has network access,
and can prepare a base image for a 2nd step when network access is not
available.

I think what is needed is a bootstrap method doing "nothing".

### Expected behavior

Wishlist item: provide support for "bootstrap: none" module.

### Actual behavior

Not supported.

### Steps to reproduce behavior

By adding an empty script "build-none.sh" into libexec/singularity/bootstrap/modules-v2
of the singularity installation, it was working as expected. It would be nice if singularity
provides this by default. Or am I missing a similar feature?

**Comment by cclerget** [comment]
@weidendo Did you try boostrap --nobase option for second step ?

**Comment by GodloveD** [comment]
@cclerget is right.  That is one way to do it.   You can also use docker to create a base image and build it on Docker Hub.  Then when you are ready to build you second image from the base image just use `Bootstrap: docker` in the definition file.  

In the upcoming version of Singularity (2.4) you will also be able to bootstrap from an image saved on your local device using the `Bootstrap: localimage` keyword/value.  And you will also be able to build from Docker Hub using the `Bootstrap: shub` keyword/value.  We are trying to get that release out by the end of the month.  Those methods are preferred over the `--nobase` option because both the original definition file (used to create the base image) and the 2nd definition file (used to create the final image) will be saved in the metadata.  In fact, ALL of the definition files used to create the final image will be saved in sequence, so in theory your image should still be completely reproducible when you bootstrap from another image.

**Comment by vsoch** [comment]
@GodloveD could we support bootstrap "none" too? (To just point to nobase. It seems like an intuitive thing to try, and we can just have it evoke the same pathway.

**Comment by GodloveD** [comment]
@vsoch using the new `build` command (which is both `create` and `bootstrap` with a ton of new functionality) you can just omit the header altogether.  For instance, let's say I have these 2 definition files.  The first is called Singularity and the second is called Singularity2
```
BootStrap: docker
From: godlovedc/lolcow
```
```
%post
    echo "post the thing"
%test
    echo "test the thing"
```
I can run them in sequence like so.  Note the `--exists` option in the second command. 
```
david@rubbish:~$ sudo singularity build foo Singularity
Using container recipe deffile: Singularity
Sanitizing environment
Adding base Singularity environment to container
Docker image path: index.docker.io/godlovedc/lolcow:latest
Cache folder set to /root/.singularity/docker
Exploding layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding layer: sha256:3b865e05deff69ce48df1a1b083f0ce64d6cd0b94870191020f230c4beeea3e3.tar.gz
Exploding layer: sha256:73b3859b1e43f3ff32f10055951a568a9ad5ab6dc4ab61818b117b6912088f3d.tar.gz
Exploding layer: sha256:1f88dc826b144c661a8d1d08561e1ff3711f527042955505e9f3e563bdb2281f.tar.gz
Exploding layer: sha256:2b61829b0db5f4033ff48cbf3495271c8410c76e6396b56f15a79c3f7b5b7845.tar.gz
Exploding layer: sha256:6960dc1aba1816652969986284410927a5d942bf8042e077a3ebc8d1c58bb432.tar.gz
Exploding layer: sha256:bd97b43c27e332fc4e00edf827bbc26369ad375187ce6eee91c616ad275884b1.tar.gz
Exploding layer: sha256:c422544c3664ff84adf62a5dcebfd358e2a01503a29b4d9f5e91c32ca6a8954d.tar.gz
Finalizing Singularity container
Calculating final size for metadata...Running checks
Building Singularity image...
Cleaning up...
Singularity container built: foo

david@rubbish:~$ sudo singularity build --exists foo Singularity2
Building into existing container: foo
Using container recipe deffile: Singularity2
Sanitizing environment
Adding base Singularity environment to container
Running post scriptlet
+ echo post the thing
post the thing
Running test scriptlet
+ echo test the thing
test the thing
Found an existing definition file
Adding a bootstrap_history directory
Finalizing Singularity container
Calculating final size for metadata...Running checks
Building Singularity image...
Cleaning up...
Singularity container built: foo

david@rubbish:~$ singularity exec foo cowsay "And Bob's your uncle!"
 _______________________
< And Bob's your uncle! >
 -----------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

**Comment by weidendo** [comment]
Thanks for all the hints!

@cclerget Yes, option "--nobase" sounds fine for now. For some reason I did not expect this to be a flag..

@GodloveD: I need the 2nd step to work without network access, so starting on Docker does not work, but "Bootstrap: localimage" sounds exactly what I want.
