### ISSUE TITLE
/bin/tar: Unexpected EOF in archive when importing docker

### ISSUE THREAD

**Issue by justinblaber** [apptainer/singularity#931]
## Version of Singularity:

bf5853e Bump release version

### Actual behavior

Trying to import a docker image:

singularity import Multi_Atlas_v2_1_0.img docker://vuiiscci/vuiiscci:Multi_Atlas_v2_1_0

Docker image path: index.docker.io/vuiiscci/vuiiscci:Multi_Atlas_v2_1_0
Cache folder set to /home-nfs/masi-shared-home/home/local/VANDERBILT/blaberj/.singularity/docker
Importing: base Singularity environment
Importing: /home-nfs/masi-shared-home/home/local/VANDERBILT/blaberj/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Importing: /home-nfs/masi-shared-home/home/local/VANDERBILT/blaberj/.singularity/docker/sha256:2acdebee684f1bc34e92f898da48d2b905ff5933499fd109c3d58dad9b363416.tar.gz

gzip: /home-nfs/masi-shared-home/home/local/VANDERBILT/blaberj/.singularity/docker/sha256:2acdebee684f1bc34e92f898da48d2b905ff5933499fd109c3d58dad9b363416.tar.gz: unexpected end of file
/bin/tar: Unexpected EOF in archive
/bin/tar: Unexpected EOF in archive
/bin/tar: Error is not recoverable: exiting now
ERROR  : Tar did not return successful

The docker runs fine on my system. I've tried this and the same thing happens on both master and the development branch.

**Comment by vsoch** [comment]
Could you show me a link to the Dockerfile? This looks sort of similar to when Docker was giving us a layer (size 0) for an ENV variable, but we've made a lot of changes so it might be something else.

**Comment by justinblaber** [comment]
This is the entire docker file:

---
```
# Use centos 6 base image
FROM centos:6

# Install xvfb-run, MATLAB MCR, set up INPUTS and OUTPUTS directories, etc...
# Note that java is required for gui to run with MATLAB
RUN yum -y install java-1.7.0-openjdk libgomp wget unzip zip xorg-x11-server-Xvfb ghostscript && \
    mkdir /tmp/matlab_mcr && \
    cd /tmp/matlab_mcr/ && \
    wget https://www.mathworks.com/supportfiles/MCR_Runtime/R2013a/MCR_R2013a_glnxa64_installer.zip && \
    unzip MCR_R2013a_glnxa64_installer.zip && \
    ./install -agreeToLicense yes -mode silent && \
    rm -rf /tmp/matlab_mcr && \
    mkdir /INPUTS && \
    mkdir /OUTPUTS && \ 
    mkdir /code

# Copy multi atlas script 
ADD Multi_Atlas_v2_1_0 /code

# Copy binaries and atlases used in multi-atlas pipeline; for some reason absolute paths dont work
ADD scratch /scratch

# Set environment for MATLAB MCR
ENV LD_LIBRARY_PATH /usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/bin/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/java/jre/glnxa64/jre/lib/amd64/server:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/java/jre/glnxa64/jre/lib/amd64:/usr/lib64

ENV XAPPLRESDIR /usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/X11/app-defaults
```
---

Thanks!!

**Comment by vsoch** [comment]
Where does the ADD come from? The build fails for me:

```
 ---> 0eb1fc11c9f0
Removing intermediate container f8461bd36bbc
Step 3/6 : ADD Multi_Atlas_v2_1_0 /code
ADD failed: stat /var/lib/docker/tmp/docker-builder101591858/Multi_Atlas_v2_1_0: no such file or directory

```

**Comment by justinblaber** [comment]
Thats a compiled matlab script, so basically just an executable Im adding to the image. The images are on a private dockerhub repo. Would it be easier to add you as a collaborator or temporarily change the password? I think it will be a pain for you to build it.

**Comment by justinblaber** [comment]
Also another docker image we have with a similar docker file worked just fine with singularity. I have also just tested both docker images and they work fine.

**Comment by vsoch** [comment]
yeah that's a great idea! If you are able to give me a good way to debug / look into the issue, that gives the most promise for figuring it out. Also, could you clarify how they work fine with singularity? So pulling from the docker registry doesn't work, but some other method does?

**Comment by justinblaber** [comment]
Do you have a dockerhub user account? I'll add you as a collaborator. Also, the dockers are quite large (~10 gigs). Sorry about that.

And also, currently the dockerhub repo has two dockers which are two different medical image processing pipelines I've containerized (I plan to add more soon). They both work on my system and run to completion. One of the tags, `MaCRUISE_v3_1_0`, I can import to singularity without issue. The other `Multi_Atlas_v2_1_0`, returns an error when I try to import it to singularity with:

`singularity import Multi_Atlas_v2_1_0.img docker://vuiiscci/vuiiscci:Multi_Atlas_v2_1_0`

We'd like to run these on a cluster so we need singularity.

Thanks!!!

EDIT: If it helps, my docker version: `Docker version 17.06.1-ce, build 874a737`

**Comment by vsoch** [comment]
yep I'm username "vanessa"

**Comment by justinblaber** [comment]
I just added you. Let me know if you can pull. Also, the docker images contain some licensed medical imaging data so please don't distribute please. Thanks again.

**Comment by vsoch** [comment]
This works fine for me, I just pulled the image:

```
singularity pull docker://vuiiscci/vuiiscci:Multi_Atlas_v2_1_0
Initializing Singularity image subsystem
Opening image file: vuiiscci-Multi_Atlas_v2_1_0.img
Creating 32872MiB image
Binding image to loop
Creating file system within image
Image is done: ./vuiiscci-Multi_Atlas_v2_1_0.img
Docker image path: index.docker.io/vuiiscci/vuiiscci:Multi_Atlas_v2_1_0
Cache folder set to /home/vanessa/.singularity/docker
Importing: base Singularity environment
Importing: /home/vanessa/.singularity/docker/sha256:cd3b990dbbea1a8de88713ad75b277692a0d5ffe428c342b53d12d6b82f10494.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:75e0971142765beb3f69b5b398d8d24cbedfbf1e4279b6c17b03f0dc9d91aa9e.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:5ccc33640ea4dd7b64a7277d6054eaaa267fed98cc665cf1f47e71b4650195b3.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:2acdebee684f1bc34e92f898da48d2b905ff5933499fd109c3d58dad9b363416.tar.gz
Importing: /home/vanessa/.singularity/metadata/sha256:f75f8c04a1e587bf42f0e37541c90f46c33a0e6fb24c1b66d129db54c212dd78.tar.gz
Done. Container is at: ./vuiiscci-Multi_Atlas_v2_1_0.img

./vuiiscci-Multi_Atlas_v2_1_0.img 
ls /
bin   code  environment  home    lib    lost+found  mnt  OUTPUTS  root  scratch  singularity  sys  usr
boot  dev   etc          INPUTS  lib64  media       opt  proc     sbin  selinux  srv          tmp  var
ls /code/
Multi_Atlas_v2_1_0
```
Did you try pull?

**Comment by justinblaber** [comment]
Trying this now

**Comment by justinblaber** [comment]
```
blaberj@masi-24:/share4/blaberj/singularity/Multi_Atlas_v2_1_0$ singularity pull docker://vuiiscci/vuiiscci:Multi_Atlas_v2_1_0
Initializing Singularity image subsystem
Opening image file: vuiiscci-Multi_Atlas_v2_1_0.img
Creating 32872MiB image
Binding image to loop
Creating file system within image
Image is done: vuiiscci-Multi_Atlas_v2_1_0.img
Docker image path: index.docker.io/vuiiscci/vuiiscci:Multi_Atlas_v2_1_0
Cache folder set to /home-nfs/masi-shared-home/home/local/VANDERBILT/blaberj/.singularity/docker
Importing: base Singularity environment
Importing: /home-nfs/masi-shared-home/home/local/VANDERBILT/blaberj/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Importing: /home-nfs/masi-shared-home/home/local/VANDERBILT/blaberj/.singularity/docker/sha256:2acdebee684f1bc34e92f898da48d2b905ff5933499fd109c3d58dad9b363416.tar.gz

gzip: /home-nfs/masi-shared-home/home/local/VANDERBILT/blaberj/.singularity/docker/sha256:2acdebee684f1bc34e92f898da48d2b905ff5933499fd109c3d58dad9b363416.tar.gz: unexpected end of file
/bin/tar: Unexpected EOF in archive
/bin/tar: Unexpected EOF in archive
/bin/tar: Error is not recoverable: exiting now
ERROR  : Tar did not return successful
```

Arggg.

I'm gonna try some different things out.

**Comment by vsoch** [comment]
Off the top of my head, here are some main differences, and factors that might be at play:

 - do you have enough filesystem space to download and dump?
 - Do you have any of the previous layers cached? If there was some layer, and the file somehow "finished" but is corrupt because you contol C, maybe it triggers that error. I would try removing your user (and root's) cache ($HOME/.singularity/ and /root/.singularity
 - what version of tar and OS are you using?  I have:

```
tar (GNU tar) 1.28
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
```

Did you look at that archive and it's corrupt? I found the same tar.gz on my machine (6.2 GB!) and was able to open it (very slowly, lol). It has the scratch folder in it. If all else fails, maybe you can package that into fewer pieces - that is a big thing to be moving around, and compressed!

And as a way fall back - maybe this task can be accomplished without using matlab entirely. It's not open source (requires a license) and it's a PITA to share any of your images (and I say this after much frustration in early grad school when I used it).

**Comment by justinblaber** [comment]
Your second point is what I think it might be. I've set `SINGULARITY_CACHEDIR` to `/tmp/.singularity`. My home directory is actually an NFS mount while `tmp` is a local harddrive which I thought may have been an issue, but maybe it's just cached stuff from a previously failed attempt. I'll report back in a little bit.

**Comment by justinblaber** [comment]
Argg ok, another problem. I "successfully" imported a singularity image in that the import completed without erroring out.

The next problem I'm facing is that the image data inside the singularity image are now corrupt (and hence the container fails). There are niftis inside the docker/singularity image:

```
[root@9b56dbd0d575 /]# cd /scratch/mcr/full-multi-atlas/MNI/
[root@9b56dbd0d575 MNI]# ls
average305_t1_tal_lin_headmask.nii.gz  average305_t1_tal_lin.nii.gz  average305_t1_tal_lin_mask.nii.gz
```

If I copy these into a folder from the docker they open fine in fslview or with fslhd. If I copy these from a singularity container then fsl contains they are corrupt. 

Whats strange is they appear to be the same size:

```
[root@012681405f48 MNI]# ls -l
total 4964
-rwxrwxrwx 1 root root   19447 Aug 30 18:43 average305_t1_tal_lin_headmask.nii.gz
-rwxrwxrwx 1 root root   77250 Aug 30 18:43 average305_t1_tal_lin_mask.nii.gz
-rwxrwxrwx 1 root root 4975205 Aug 30 18:43 average305_t1_tal_lin.nii.gz
-rwxrwxrwx 1 root root     676 Aug 30 18:43 COPYING
-rwxrwxrwx 1 root root    1437 Aug 30 18:43 README
```

```
Singularity Multi_Atlas_v2_1_0.img:/scratch/mcr/full-multi-atlas/MNI> ls -l
total 4980
-rwxrwxrwx 1 root root   19447 Aug 30 13:43 average305_t1_tal_lin_headmask.nii.gz
-rwxrwxrwx 1 root root   77250 Aug 30 13:43 average305_t1_tal_lin_mask.nii.gz
-rwxrwxrwx 1 root root 4975205 Aug 30 13:43 average305_t1_tal_lin.nii.gz
-rwxrwxrwx 1 root root     676 Aug 30 13:43 COPYING
-rwxrwxrwx 1 root root    1437 Aug 30 13:43 README
```
Thoughts? 

EDIT:

```
> blaberj@masi-24:/share4/blaberj/singularity/Multi_Atlas_v2_1_0/OUTPUTS$ head -n1 average305_t1_tal_lin_docker.nii.gz 
> �4TRaverage305_t1_tal_lin.nii��	���=�
>                                              �Ɣ�c�TAL������%v�����7Đ��AHK)���xk�NS�N��[��֦9bH(Z�ych�}>W}��y~�:�����~&�}����5��:�������c^�N'���;��;=�N�t�x�׸��ox�{_�����4������w����a�������s���}ڧ����p�O��O��O�k������=�A��Ox��=�	��n7~z�w{�|�>��Ox��+7�����ӍO�������=��/�{�z�W��&������N�ߧ����/~�[<�������>�����W���C^��g��QO�ɇ��+��V������ܾ񷿻}����\������S�z���~��R;�������cu���{[}9��󻮕�g�����6>���)x=u�ݒ<r{i�A�r
>                  ���}�k�A�������bl�=��Xx-�d�M�*���|��ߒ}�c:�v�m�n����q�s-N.��}��X�1��������9i��{������j����S֛{��,8e��U<O}o��+��5�8�Gyo�}�K|�&n��������ڻ����^��x�����J��?�:��AW8���8|�C��k����?�{O�������w��X;f_ؒ�O����Z9�Zq{{��\��;{�x�����W}����_��+��ީx�l1�1�a�����2G+�i~^=j�w��\<���=]�̭d���[�U�Hw�ݯ��>�����������m�A���)����-�֦��A��_�j���W���S���߹�V�y[���Hݏi��Wx�������&�����W~�
```

```
> blaberj@masi-24:/share4/blaberj/singularity/Multi_Atlas_v2_1_0/OUTPUTS$ head -n1 average305_t1_tal_lin_singularity.nii.gz 
> Z?\?^?`?a?b?e?h?i?l?n?q?s?u?w?x?y?{?}??�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?@@@	@
> @@@@@@@@!@"@#@%@&@(@+@-@/@0@2@4@6@8@9@=@@@D@F@J@K@N@O@Q@T@U@V@X@Z@[@\@^@_@b@e@g@i@j@l@n@p@r@t@v@w@y@{@}@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@AAAA
> 
```

**Comment by vsoch** [comment]
So just to confirm - the files from the docker layer that is  saved as `.tar.gz` are ok, but the files extracted into the image (from that same `.tar.gz` are corrupt?

**Comment by justinblaber** [comment]
They appear to be fine in the docker. If I run:

`sudo docker run -it -v /share4/blaberj/singularity/Multi_Atlas_v2_1_0/OUTPUTS:/OUTPUTS vuiiscci/vuiiscci:Multi_Atlas_v2_1_0` 

The files are fine. If I run (using the imported singularity image):

singularity shell -B /share4/blaberj/singularity/Multi_Atlas_v2_1_0/INPUTS:/INPUTS -B /share4/blaberj/singularity/Multi_Atlas_v2_1_0/OUTPUTS:/OUTPUTS Multi_Atlas_v2_1_0.img

The files look corrupt (although they appear to be the exact same size...). Are you suggesting that I should untar the following:

```
blaberj@masi-24:/tmp/test/.singularity/docker$ ls
sha256:2acdebee684f1bc34e92f898da48d2b905ff5933499fd109c3d58dad9b363416.tar.gz
sha256:5ccc33640ea4dd7b64a7277d6054eaaa267fed98cc665cf1f47e71b4650195b3.tar.gz
sha256:75e0971142765beb3f69b5b398d8d24cbedfbf1e4279b6c17b03f0dc9d91aa9e.tar.gz
sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
sha256:cd3b990dbbea1a8de88713ad75b277692a0d5ffe428c342b53d12d6b82f10494.tar.gz
```

And then inspect the files in here?

**Comment by vsoch** [comment]
yes. The software if I remember was in the first one, the 2ac (scratch). The first round of debugging should see if that file is corrupt.

**Comment by justinblaber** [comment]
If I untar manually the file is fine:

`tar -xvzf 2acdebee684f1bc34e92f898da48d2b905ff5933499fd109c3d58dad9b363416.tar.gz`

I had to remove the `sha:` cause `tar` was complaining, but:

```
blaberj@masi-24:/tmp/test/.singularity/docker/scratch/mcr/full-multi-atlas/MNI$ fslhd average305_t1_tal_lin.nii.gz
filename       average305_t1_tal_lin.nii.gz

sizeof_hdr     348
data_type      FLOAT32
dim0           3
dim1           172
dim2           220
...
```

```
blaberj@masi-24:/tmp/test/.singularity/docker/scratch/mcr/full-multi-atlas/MNI$ diff average305_t1_tal_lin.nii.gz /share4/blaberj/singularity/Multi_Atlas_v2_1_0/OUTPUTS/average305_t1_tal_lin_docker.nii.gz 
```

```
blaberj@masi-24:/tmp/test/.singularity/docker/scratch/mcr/full-multi-atlas/MNI$ diff average305_t1_tal_lin.nii.gz /share4/blaberj/singularity/Multi_Atlas_v2_1_0/OUTPUTS/average305_t1_tal_lin_singularity.nii.gz
Binary files average305_t1_tal_lin.nii.gz and /share4/blaberj/singularity/Multi_Atlas_v2_1_0/OUTPUTS/average305_t1_tal_lin_singularity.nii.gz differ
```

`average305_t1_tal_lin_docker.nii.gz` is the file I copied from the docker container to the mounted `OUTPUTS` directory and `average305_t1_tal_lin_singularity.nii.gz` is the same file I copied out of the singularity container. 

Also, thanks so much for the help and assistance...

**Comment by vsoch** [comment]
We are getting close! This tells us that obtaining the file isn't the issue, but dumping into the image. Could you give a go at trying out the specific command that we use? Note that we exclude /dev and some other things, and perhaps that's the issue. [Here is the command](https://github.com/singularityware/singularity/blob/development/libexec/bootstrap-scripts/deffile-driver-docker.sh#L64). And maybe try the following:

 - first try it on your local machine, does the error reproduce?
 - if not, create a base OS big enough for it, and do the same in the image.

**Comment by justinblaber** [comment]
I think this is some weird permissions issue. I rebuilt the singularity images by moving the files off a network share (where everything was configured to have root ownership - probably not configured the best way) to a local drive and it built fine. Very strange but for now I'll probably say this is resolved. If I run into this again I'll ping. 

Thanks for all your help!!!

**Comment by vsoch** [comment]
awesome! Glad to hear this is fixed up. Closing issue.
