### ISSUE TITLE
singularity can not import image from local tar file.

### ISSUE THREAD

**Issue by zhcf** [apptainer/singularity#933]
## Version of Singularity:
2.3.2

[root@testcomputenode01 opt]# docker save consol/centos-xfce-vnc >tmp.tar
[root@testcomputenode01 opt]# cat tmp.tar| singularity import test.img
/usr/bin/tar: manifest.json: implausibly old time stamp 1970-01-01 08:00:00
/usr/bin/tar: repositories: implausibly old time stamp 1970-01-01 08:00:00

**Comment by vsoch** [comment]
We don't advocate for import of an image using the output of what docker puts in a tmp.tar - I'm not actually sure how it differs from the API we use. As for the content, it is likely the result of the docker export, and so it would be more appropriate to post there. Doing a google search, this is a common issue with tar. I would suggest trying to see if it's an issue with your export using docker, vs. singularity. Try pushing that image to docker hub and then importing with singularity docker:// uri, and see if the same error results.

**Comment by dtrudg** [comment]
Closing this - as .@vsoch mentions above the preferred procedure is to build a singularity image from a docker regsistry uri. If you are using Singularity 2.4 the general process to stand up a docker private registry and do this is:

```
# Start a docker registry
$ docker run -d -p 5000:5000 --restart=always --name registry registry:2
# Push local docker container to it
$ docker tag alpine localhost:5000/alpine
$ docker push localhost:5000/alpine
# Create def file for singularity like this..
# (add your modifications)
Bootstrap: docker
Registry: http://localhost:5000
Namespace:
From: alpine:latest
# Build singularity container
$ sudo SINGULARITY_NOHTTPS=1 singularity build alpine.simg def
```
