### ISSUE TITLE
"singularity build" under docker with an image definition file prints "Unknown image format/type"

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#940]
## Version of Singularity:

Current development branch

### Expected behavior

'singularity build' should not print extraneous messages.

### Actual behavior

When running 'make test' under docker (from a centos7 host with a centos7 image) I noticed that the 29-instance.sh test prints `Singularity: image-type (U=0,P=26630)> Unknown image format/type: ../examples/busybox/Singularity` even though it doesn't do any other harm.  I dug into the code and found that /usr/libexec/singularity/cli/build.exec was using the 'is_image' function from /usr/libexec/singularity/functions, and that runs /usr/libexec/singularity/bin/image-type which prints the message even though stdout & stderr are directed to /dev/null.   The is_image function is expected to fail on an image definition file, but the problem is that it is printing the extraneous message. With strace I found that it was opening and writing to "/dev/console" after discovering that "/dev/log" was missing.  This is because the image-type program prints an ERROR message, and singularity_message() calls syslog() on any message that is less than or equal to LOG level.

### Steps to reproduce behavior

1. Start an interactive docker process in a singularity source directory, e.g.
```
sudo docker run --privileged --rm=true -v `pwd`:/build:rw -it centos:7
```
2. After installing singularity, for example by doing
```
cd /build; .travis/rpmbuild_test 6
```
then try
```
singularity build /tmp/test-container examples/busybox/Singularity
```
and you should see the output.

**Comment by vsoch** [comment]
is there still an issue here? I always get into trouble when I use docker with --privileged so I am hesitant to try and reproduce. What is the use case, just curious?

**Comment by DrDaveD** [comment]
What kind of trouble?  It changes ownership of files to root?  I suggest doing it in a /tmp scratch directory:
```
mkdir /tmp/singtest
cd /tmp/singtest
git clone https://github.com/singularityware/singularity.git
cd singularity
git checkout -b development origin/development
sudo docker run --privileged --rm=true -v `pwd`:/build:rw -it centos:7
cd /build; .travis/rpmbuild_test 6
yum -y install which  # because of issue #1078
singularity build /tmp/test-container examples/busybox/Singularity
```
Yes, it still prints out the extraneous error.

The use case is the unit tests running in the travis builds for centos 6 & 7, which run under docker.  I don't know who else runs into it, I was just reporting a problem I noticed in the unit test.

**Comment by dtrudg** [comment]
Closing this as it has not been updated for 2 years, and relates to Singularity 2.x. Please do open an issue if a similar concern is found for 3.x
