### ISSUE TITLE
Unbound variable error while sourcing the environment during the build process

### ISSUE THREAD

**Issue by fmorency** [apptainer/singularity#941]
## Version of Singularity:

2.3.9-development.gad1efde

### Expected behavior

Be able to `export FOO=/bar:$FOO` in the `%environment` section even if `FOO` is undefined. This behaviour is working on 2.3

### Actual behavior

An `unbound variable` error is raised during the build process if the variable is undefined

### Steps to reproduce behavior

Add `export FOO=/bar:$FOO` in the `%environment` section and `singularity build` the image

### Notes

After chatting with @vsoch and @GodloveD on Slack, we came to the conclusion that `set -u` should be disabled (`set +u`) in the section of the code where the environment is sourced.

**Comment by vsoch** [comment]
We no longer source during build, so this shouldn't be an issue. Closing.
