### ISSUE TITLE
Situations where the overlay option does not work

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#943]
## Version of Singularity:

2.3.1 and the development branch

### Expected behavior

With the overlay option enabled, I expect to be able to bind the directories to any directory that is not in the image.

### Actual behavior

If you don't use the --home option and the base of your home directory's path is not in the image, when the overlay option is enabled singularity will normally create the home directory path for you, but with the --contain option it gets an error: `ERROR  : Base home directory does not exist within the container` (which is the same error as with overlay disabled).   If however you specify the --home option, even with the default value of --home $HOME (or with a target of any non-existent directory in the image), it works, but only if the base of the target directory does *not* exist in the image.

If the base directory of the target of a bind path *does* exist in the image, regardless of whether or not --contain is used, if you attempt to use --home to bind to a subdirectory of the base path that does not exist, singularity gives the error `ERROR  : Could not create directory within container ...: Operation not supported`.  If you attempt to do the same with --bind it instead gives a warning and continues: `WARNING: Skipping user bind, could not create bind point ...: Operation not supported`.   Those are the errors with the current development branch; with singularity-2.3.1 the same error/warning messages happen but they're `No such file or directory` instead of `Operation not supported`.

I did this testing on RHEL7.  We don't really use overlay (and it won't ever work with unprivileged singularity) so it's not very important to me, but I thought I should document it.  I was testing for pr #912, but that pr did not cause the behavior to change.

### Steps to reproduce behavior

For the first error, have a default home directory that does not have its base path in your image, and use --contain.

For the second error, simply attempt to use --bind or --home to bind to a subdirectory of a directory that exists in the image, for example /srv/something or /home/something.

**Comment by geonmo** [comment]
I used 2.3.1-dist version on SLC6. The same problem has occurred.

**Comment by DrDaveD** [comment]
@geonmo overlayfs is not supported on EL6 variants at all unless you run a non-standard kernel.  Depending on how the binary was built, you either need to set 'enable overlay = no' in singularity.conf or singularity won't attempt to use it.  In the opensciencegrid distribution we had to set 'enable overlay = no' on EL6 because it couldn't determine whether or not overlayfs was available at build time.  I made pr #912 so future versions will silently ignore a missing overlayfs at run time.

**Comment by gmkurtzer** [comment]
I can not reproduce this in the 2.4 beta release branch. Closing, but if it is indeed still an issue, please comment so I can reopen. Thanks!

**Comment by DrDaveD** [comment]
@gmkurtzer Yes both of the problems still exist at least on EL7.

**Comment by DrDaveD** [comment]
I mean in the current development branch

**Comment by gmkurtzer** [comment]
Sorry about that, reopening issue. In Slack, a reproducer was discussed.

**Comment by DrDaveD** [comment]
Ok, so the second problem, with --bind, only happens when the base image is a cvmfs directory.  I think that's a limitation with Redhat's implementation of overlayfs.  It does not happen if the image is a file or a directory on the local disk.  I don't think there's anything to be done about it.

The first problem, with --contain and a home directory that does not have a base in the image, does still happen for me even with an image file or an image directory on local disk.

**Comment by gmkurtzer** [comment]
@DrDaveD Can you retest with the latest push to development? Thanks!

**Comment by DrDaveD** [comment]
@gmkurtzer Ok I retested and confirm that my default home directory now works with overlay, even though its base directory is not in the image.

I still see the other failures, but only if the base image is a directory in cvmfs, so you probably don't need to worry about it.  I do want to take back what I said about Redhat not supporting cvmfs as a base directory, however, because that is in fact used routinely on cvmfs repository publishing servers.  It was a feature that began working well in Redhat 7.3.  The restriction that I was misremembering was on the scratch space, the filesystem that's on top; that has to be only certain filesystem types: ext3, ext4, or xfs with ftype=1.  So I don't understand why it isn't working in singularity; the root filesystem (including /tmp and /var) is ext4.

The debug output when attempting to make a home directory with -H $HOME:/home/dwd (where /home exists in the image) is:
```
VERBOSE [U=0,P=26680]      singularity_runtime_mount_home()          Mounting home directory source into session directory: /cloud/login/dwd -> /var/singularity/mnt/session/home/dwd
DEBUG   [U=0,P=26680]      singularity_priv_drop()                   Dropping privileges to UID=3382, GID=9996 (2 supplementary GIDs)
DEBUG   [U=0,P=26680]      singularity_priv_drop()                   Restoring supplementary groups
DEBUG   [U=3382,P=26680]   singularity_priv_drop()                   Confirming we have correct UID/GID
DEBUG   [U=3382,P=26680]   singularity_runtime_mount_home()          Checking if overlay is enabled
DEBUG   [U=3382,P=26680]   singularity_registry_get()                Returning value from registry: 'OVERLAYFS_ENABLED' = '1'
DEBUG   [U=3382,P=26680]   singularity_runtime_mount_home()          Staging home directory
DEBUG   [U=3382,P=26680]   singularity_priv_escalate()               Temporarily escalating privileges (U=3382)
DEBUG   [U=0,P=26680]      singularity_priv_escalate()               Clearing supplementary GIDs.
DEBUG   [U=0,P=26680]      singularity_runtime_mount_home()          Creating home directory within container: /var/singularity/mnt/session/home/dwd
DEBUG   [U=0,P=26680]      s_mkpath()                                Creating directory: /var/singularity/mnt/final/home/dwd
DEBUG   [U=0,P=26680]      s_mkpath()                                Opps, could not create directory /var/singularity/mnt/final/home/dwd: (95) Operation not supported
ERROR   [U=0,P=26680]      singularity_runtime_mount_home()          Failed creating home directory in container /var/singularity/mnt/session/home/dwd: Operation not supported
ABORT   [U=0,P=26680]      singularity_runtime_mount_home()          Retval = 255
```

and when instead doing -B /tmp/bnddir:/srv/dir it is:
```
DEBUG   [U=3382,P=26630]   singularity_runtime_mount_userbinds()     Found bind: /tmp/bnddir -> container:/srv/dir
DEBUG   [U=3382,P=26630]   singularity_runtime_mount_userbinds()     Checking if bind point is already mounted: /srv/dir
DEBUG   [U=3382,P=26630]   check_mounted()                           Opening /proc/mounts
DEBUG   [U=3382,P=26630]   singularity_registry_get()                Returning value from registry: 'OVERLAYFS_ENABLED' = '1'
VERBOSE [U=3382,P=26630]   singularity_runtime_mount_userbinds()     Creating bind directory on overlay file system: /srv/dir
DEBUG   [U=3382,P=26630]   s_mkpath()                                Creating directory: /var/singularity/mnt/final/srv/dir
DEBUG   [U=3382,P=26630]   s_mkpath()                                Opps, could not create directory /var/singularity/mnt/final/srv/dir: (13) Permission denied
DEBUG   [U=3382,P=26630]   singularity_priv_escalate()               Temporarily escalating privileges (U=3382)
DEBUG   [U=0,P=26630]      singularity_priv_escalate()               Clearing supplementary GIDs.
VERBOSE [U=0,P=26630]      singularity_runtime_mount_userbinds()     Retrying with privileges to create bind directory on overlay file system: /srv/dir
DEBUG   [U=0,P=26630]      s_mkpath()                                Creating directory: /var/singularity/mnt/final/srv/dir
DEBUG   [U=0,P=26630]      s_mkpath()                                Opps, could not create directory /var/singularity/mnt/final/srv/dir: (95) Operation not supported
DEBUG   [U=0,P=26630]      singularity_priv_drop()                   Dropping privileges to UID=3382, GID=9996 (2 supplementary GIDs)
DEBUG   [U=0,P=26630]      singularity_priv_drop()                   Restoring supplementary groups
DEBUG   [U=3382,P=26630]   singularity_priv_drop()                   Confirming we have correct UID/GID
WARNING [U=3382,P=26630]   singularity_runtime_mount_userbinds()     Skipping user bind, could not create bind point /srv/dir: Operation not supported
```

**Comment by gmkurtzer** [comment]
Heya, @DrDaveD!

Can you test [development ddaa939]?

**Comment by DrDaveD** [comment]
I tested it.  Merging development alone didn't change anything, but when I did cherry-pick of that commit & rebuilt then -H $HOME:/home/dwd still failed but with a different error message:
```
ERROR  : Failed to mount staged home base: /var/singularity/mnt/session/home/dwd -> /var/singularity/mnt/final/home/dwd: No such file or directory
```
With the verbose & debugging enabled I see it got a little bit further before failing:
```
DEBUG   [U=3382,P=1]       singularity_runtime_mount_home()          Staging home directory
DEBUG   [U=3382,P=1]       singularity_priv_escalate()               Temporarily escalating privileges (U=3382)
DEBUG   [U=0,P=1]          singularity_priv_escalate()               Clearing supplementary GIDs.
DEBUG   [U=0,P=1]          singularity_runtime_mount_home()          Creating home directory within container: /var/singularity/mnt/session/home/dwd
DEBUG   [U=0,P=1]          s_mkpath()                                Directory exists, returning '0': /var/singularity/mnt/session/home/dwd
VERBOSE [U=0,P=1]          singularity_runtime_mount_home()          Mounting staged home directory to container: /var/singularity/mnt/session/home/dwd -> /var/singularity/mnt/final/home/dwd
ERROR   [U=0,P=1]          singularity_runtime_mount_home()          Failed to mount staged home base: /var/singularity/mnt/session/home/dwd -> /var/singularity/mnt/final/home/dwd: No such file or directory
```

**Comment by DrDaveD** [comment]
Also, that "Minor bug/typo fix" breaks the case of my default home directory, with the base not in the image.  I think the typos were in the debug & error messages, not the code.

**Comment by DrDaveD** [comment]
[This patch](https://github.com/singularityware/singularity/files/1372876/home.c.patch.txt) makes both cases work.  What do you think about it?

**Comment by DrDaveD** [comment]
Come to think of it, my patch would probably not work properly if there were other things under the base directory in the container; it would hide them.

**Comment by DrDaveD** [comment]
I tried to reproduce the behavior outside of a namespace with a manual mount command, and was unable.  I had no problem with creating subdirectories inside of directories coming from cvmfs.  I think it is somehow an interaction between namespaces, overlayfs, and cvmfs.  It's not a very high priority to figure out because we don't want to rely on the singularity overlay feature anyway.

**Comment by gmkurtzer** [comment]
Yeah, I'm having a hard time identifying what the root cause of the problem is. Can you attach a bit more debugging info (maybe the previous 25 lines)?

Thanks!

**Comment by DrDaveD** [comment]
I attach [the whole trace](https://github.com/singularityware/singularity/files/1373211/sing-debug.out.txt) although I doubt it will help.  This time I'm running with a
[patch](https://github.com/singularityware/singularity/files/1373233/home.c.new.patch.txt) that just fixes the debug messages, the opposite of ddaa939.

**Comment by olifre** [comment]
I also observe this. Running with `strace` also does not really give much more info:
```
stat("/var/singularity/mnt/final/var/spool/usr", 0x7ffe95bb4570) = -1 ENOENT (No such file or directory)
geteuid()                               = 0
write(2, "DEBUG   [U=0,P=23365]      singu"..., 130DEBUG   [U=0,P=23365]      singularity_registry_get()                Returning value from registry: 'OVERLAYFS_ENABLED' = '1'
) = 130
geteuid()                               = 0
write(2, "VERBOSE [U=0,P=23365]      singu"..., 136VERBOSE [U=0,P=23365]      singularity_runtime_mount_userbinds()     Creating bind directory on overlay file system: /var/spool/usr
) = 136
stat("/var/singularity/mnt/final/var/spool/usr", 0x7ffe95bb4520) = -1 ENOENT (No such file or directory)
stat("/var/singularity/mnt/final/var/spool", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
geteuid()                               = 0
write(2, "DEBUG   [U=0,P=23365]      s_mkp"..., 134DEBUG   [U=0,P=23365]      s_mkpath()                                Creating directory: /var/singularity/mnt/final/var/spool/usr
) = 134
umask(0)                                = 022
mkdir("/var/singularity/mnt/final/var/spool/usr", 0755) = -1 EOPNOTSUPP (Operation not supported)
umask(022)                              = 0
geteuid()                               = 0
write(2, "DEBUG   [U=0,P=23365]      s_mkp"..., 177DEBUG   [U=0,P=23365]      s_mkpath()                                Opps, could not create directory /var/singularity/mnt/final/var/spool/usr: (95) Operation not supported
```

**Comment by jblomer** [comment]
If it only occurs on cvmfs, perhaps the cvmfs debug log (``CVMFS_DEBUGLOG=/tmp/cvmfs.log``) can help.  I'm happy to take a look at a cvmfs trace.

**Comment by olifre** [comment]
@jblomer Here's what I see in a cvmfs debug log (using a cvmfs 2.3.5 client) directy after starting singularity, triggering this issue:
```
(cvmfs) cvmfs_readlink on inode: 1904    [10-26-2017 17:42:38 CEST]
(lru) lookup inode --> dirent: 1904 (hit)    [10-26-2017 17:42:38 CEST]
(cvmfs) cvmfs_readlink on inode: 1904    [10-26-2017 17:42:38 CEST]
(lru) lookup inode --> dirent: 1904 (hit)    [10-26-2017 17:42:38 CEST]
(cvmfs) cvmfs_readlink on inode: 1904    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> dirent: 1904 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_opendir on inode: 1903    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> path: 1903 (hit)    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> dirent: 1903 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_opendir on inode: 1903, path /.images/c4/5dbb2167953c62100dc3974d4909c79b4bc7248ccea86e788663bedba6ea82    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: ., inode 1903    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 06cd6f18a7ccfff70aca8f2f9c5d2ba4 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: .., inode 595    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 983cf1df6c0ebe58aef52d3e839d0eef (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: opt, inode 1982    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 06f3b4dcc164bd37cfe711a620c0a743 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: srv, inode 1983    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 8679dcc733a7511d1af9157f6ad588ef (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: media, inode 1984    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: d8761cc25a2bc5fc9180ecc9a730571a (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: proc, inode 1985    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: d511a0323a117102020ee3c4704dd464 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: lib64, inode 1986    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 2b6b75021ff6dde6de73c659963cd5ae (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: lib, inode 2097    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 54447ef55db4b4886ffe7c41e0d9c86e (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: home, inode 2114    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 18a477202334a0235814968273e6c40f (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: etc, inode 2115    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: aad18707533231ded18013f953bc9401 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: .cvmfscatalog, inode 2653    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: cd77361b7dcc1ccf4c45641e3359f205 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: tmp, inode 3975    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 2a67b2fa908136511db86607fa738a8f (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: mnt, inode 3980    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 24c39c5847740444577dbdb948ec94d5 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: selinux, inode 3981    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: a5983dcc533d21d125aa787065025293 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: lost+found, inode 3982    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 3b52a6f06f919a1bcecd9e5243d2a4bb (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: sbin, inode 3983    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 0f7f63a8d698d8670e39556cade3288e (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: sys, inode 4116    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: b60e3a669f87bc87d18d6d6d1497037c (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: bin, inode 4117    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: b472f21923b7a969a669a40791fc9f84 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: dev, inode 4224    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: d9e519b4bf5fec4ae5b3b7d8f9cd343c (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: boot, inode 4225    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 3462dab2ca08de00e2e8a1ae161c4d0d (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: cvmfs, inode 4228    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 7cd2df223f6419477840d57a0e8f409a (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: var, inode 4229    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: e1d46ea2224553b20e75badd2150d1d1 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: usr, inode 8364    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 490bdba2151ae6a8682eb5d71d4cb389 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: cgroup, inode 26724    [10-26-2017 17:42:39 CEST]
(lru) lookup md5 --> dirent: 98ae800149469b5bed051958b6baac93 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) Add to listing: root, inode 26726    [10-26-2017 17:42:39 CEST]
(cvmfs) linking directory handle 3 to dir inode: 1903    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_readlink on inode: 4217    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> dirent: 4217 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_statfs on inode: 1903    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_getxattr on inode: 1985 for xattr: trusted.overlay.redirect    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> dirent: 1985 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_getxattr on inode: 4116 for xattr: trusted.overlay.redirect    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> dirent: 4116 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_getxattr on inode: 4224 for xattr: trusted.overlay.redirect    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> dirent: 4224 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_getxattr on inode: 2114 for xattr: trusted.overlay.redirect    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> dirent: 2114 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_listxattr on inode: 2114, size 0 [hide xattrs 0]    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> dirent: 2114 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_listxattr on inode: 2114, size 337 [hide xattrs 0]    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> dirent: 2114 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_getxattr on inode: 2114 for xattr: user.pid    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> dirent: 2114 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_getxattr on inode: 2114 for xattr: user.pid    [10-26-2017 17:42:39 CEST]
(lru) lookup inode --> dirent: 2114 (hit)    [10-26-2017 17:42:39 CEST]
(cvmfs) cvmfs_releasedir on inode 1903, handle 3    [10-26-2017 17:42:39 CEST]
```
Let me know if the full log or extra information is needed. 

EDIT: For this test, I also used the public `/cvmfs/singularity.opensciencegrid.org/opensciencegrid/osg-wn:3.3-el6/` container, with Singularity 2.4, and both SUID and overlayfs active.

**Comment by jblomer** [comment]
Yes, please send me the full log.  I hope to stumble across some error, this tail of commands seemed to work ok.

**Comment by olifre** [comment]
> Yes, please send me the full log. I hope to stumble across some error, this tail of commands seemed to work ok.

Ok, here you go:
https://gist.github.com/olifre/904f9bdc40598b65a3956a806bbe45ba
This includes:
- Startup (I just restarted `autofs` after enabling the debug log).
- Mounting the OSG repo. 
- Whatever Singularity does to CVMFS.
- I stopped `autofs` directly after I got the error from Singularity. So you will also see the "shutdown", but not much more.

In addition, my kernel tells me during that:
```
[90582.072694] overlayfs: fs on '/var/lib/singularity/mnt/container' does not support file handles, falling back to index=off.
```
This is since I am using a 4.13 kernel already and have `CONFIG_OVERLAY_FS_INDEX=y` set which allows overlayfs to support hardlinks (c.f. https://cateee.net/lkddb/web-lkddb/OVERLAY_FS_INDEX.html ). I guess `cvmfs_server` could make good use of that. 
Since I observe the same with older kernels, and also @DrDaveD is surely using an older kernel, this is likely completely unrelated to this client issue.

**Comment by jblomer** [comment]
Hm, it seems that singularity gets confused by the ``user.pid`` extended attribute exposed by cvmfs.  This attribute is used to query the PID of the cvmfs fuse process.

If cvmfs is mounted with ``CVMFS_HIDE_MAGIC_XATTRS=yes`` it works for me.

**Comment by olifre** [comment]
> If cvmfs is mounted with CVMFS_HIDE_MAGIC_XATTRS=yes it works for me.

Very interesting! I can confirm that here. 
So it seems this is a Singularity bug that needs fixing...

**Comment by afortiorama** [comment]
Hello, is there any news on the solution of this bug?

**Comment by bbockelm** [comment]
@jblomer - would it be possible to suppress extended attributes on places _not_ in the root catalog?  I.e., `user.pid` and friends only live on the repository root.

I suspect OverlayFS is choking on the logical equivalent of `attr -ql` on the image directory.

It would be nice to figure out a simple shell-based reproducer!

**Comment by jblomer** [comment]
@bbockelm technically that's doable, but I'd really like to do this only as a last resort because we might break user scripts.  Also, after chroot a sub directory might be the only possible way to still query cvmfs extended attributes. I think we should first understand the root cause of the issue.

**Comment by DrDaveD** [comment]
I have made a [CVMFS ticket](https://sft.its.cern.ch/jira/browse/CVM-1434) to track a possible solution at the cvmfs level.

**Comment by DrDaveD** [comment]
@gmkurtzer: @jblomer found that the root cause was because the upper layer in the overlay that singularity creates is tmpfs, and it does not handle extended attributes.  Any time a lower layer directory has an extended attribute and a bind mount is attempted onto it, overlayfs attempts to copy the attribute from the lower layer to the upper layer and fails because the upper layer will not accept it.  I don't think there's a solution at the CVMFS level, but singularity could be changed to use /tmp or /var/tmp for the upper layer instead of tmpfs.  I'm pretty sure that earlier versions did that. 

If you like, I could try to make a reproducer with an ext3/ext4 lower layer, and open a separate issue.

**Comment by olifre** [comment]
@DrDaveD Many thanks for sharing these findings!
Just a comment:

> but singularity could be changed to use /tmp or /var/tmp for the upper layer instead of tmpfs.

Some machines in the wild may have a `tmpfs` mounted at `/tmp/` or even `/var/tmp` (e.g. I have `zram` there, which however can do xattrs), so while this would fix it for the majority, I think a more complete fix would also check that the FS supports `xattrs and show an error / warning if not.

**Comment by DrDaveD** [comment]
Pr #1638 is a workaround for this.

**Comment by DrDaveD** [comment]
Closing this issue, as the remaining problem is now described in issue #1797
