### ISSUE TITLE
shell option is not being recognized

### ISSUE THREAD

**Issue by satra** [apptainer/singularity#947]
## Version of Singularity:

```
$ singularity --version
2.3.2-dist
```

### Expected behavior

should have given bash shell inside the container

### Actual behavior

```
$ singularity shell --shell /bin/bash /dev/shm/satra/singularityhub-debian-master.img
Singularity: Invoking an interactive shell within container...

ERROR: Shell does not exist in container: /usr/local/bin/tcsh
ERROR: Using /bin/sh instead...
Singularity.singularityhub-debian-master.img>
```

### Steps to reproduce behavior

don't know if this behavior replicates on all systems.

**Comment by vsoch** [comment]
What is your environment `SHELL` and `SINGULARITY_SHELL`?

**Comment by satra** [comment]
```
$ echo $SHELL
/usr/local/bin/tcsh
$ echo $SINGULARITY_SHELL

```

but given that i'm explicitly giving `--shell` it should not care about my environment shell

**Comment by vsoch** [comment]
can you try:

```
SHELL=/bin/bash singularity shell  /dev/shm/satra/singularityhub-debian-master.img
```
It's almost the same thing, just moving over the command to the left :) And without the two dashes and space? TWO extra characters!

**Comment by satra** [comment]
that works.

**Comment by satra** [comment]
i think several variables (HOME, SHELL) are being reinterpreted by singularity even when overridden on the command line.

**Comment by vsoch** [comment]
@satra this is an old image, it doesn't even have the .singularity.d metadata folder. If you look at the call to `.shell` at the base of the image, it's acting as you would expect:

```
cat /.shell 
#!/bin/sh
. /environment
if test -n "$SHELL" -a -x "$SHELL"; then
    exec "$SHELL" "$@"
else
    echo "ERROR: Shell does not exist in container: $SHELL" 1>&2
    echo "ERROR: Using /bin/sh instead..." 1>&2
fi
if test -x /bin/sh; then
    SHELL=/bin/sh
    export SHELL
    exec /bin/sh "$@"
else
    echo "ERROR: /bin/sh does not exist in container" 1>&2
fi
```
The ability to specify shell with --shell wasn't added I don't think until after that, and we added the standard of pre-pending `SINGULARITY_` to environment variables. So if you want the `--shell` to work, use an image that was built after. Or if you want this image, use `SHELL=` before.

**Comment by satra** [comment]
ah - better error messages would be nice :)

i thought i would just pull from singularity hub because the docker pull is currently borked (as posted on slack).

**Comment by satra** [comment]
closing this issue, but i leave it to you if this indeed is a solvable feedback issue.

**Comment by vsoch** [comment]
The problem is that the error messages / checks at this point are generated inside the image. I'll definitely think about this though, for future issues it might make sense to have a "warning, this image was generated with version X and you are running Y."
