### ISSUE TITLE
Create directories while running your job inside container

### ISSUE THREAD

**Issue by saeedizadi** [apptainer/singularity#953]
## Version of Singularity:

Last version

### Expected behavior

I want to create a container and want to run my job in it while using a cluster. On the cluster I do not have sudo access so I cannot write files or create directories on the container. 
### Actual behavior

I cannot create folders in the container while I'm launching my job on a cister
### Steps to reproduce behavior

Write here.

**Comment by vsoch** [comment]
You need to write to a location that is bound to the host, and thus writable from the container.

```
singularity exec --bind /path/on/host:/path/in/container container.img run_job.sh
```
Note that by default the container will bind your user home and temporary directories, unless the admin of your cluster has modified this.

**Comment by dtrudg** [comment]
Closing this ticket, as answer was provided. Let us know if you have any other issues. Thanks!
