### ISSUE TITLE
Development  is hard and crappy with build

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#958]
I will set the scene. I'm developing a container, it has a lot of installs and waiting time, and the entire thing takes about 30 minutes. I am using 2.4, so I am using build instead of bootstrap, and I am building from a recipe, so I need sudo. 

## How it used to work (pre 2.4)
First, Here is how the old way used to work:

```
singularity create --size 6000 dev.img
sudo singularity bootstrap dev.img Singularity

<stuff happens>
<something is buggy>
EXIT 255
```
This is ok, because we are in post, and I can shell in, and interactively finish building and testing each command:

```
sudo singularity shell --writable dev.img

<fix things, finish build>
exit # exit from image
```

Then, I can remove the image, and build it from scratch, and 9/10 it builds without a hitch because I've tested everything. Importantly, I don't lose any time from the first error, because I am able to pick up **without starting from the beginning**

## How it's going to be (2.4+)

Okay, so we now have `build` instead of bootstrap, that seems ok. I can build with `--writable` in case I want to make changes if it messes up. Let's build:

```
sudo singularity build analysis.img Singularity

<building stuff, 15 minutes later>
ERROR EXIT 255
```
and there is no container. I have nothing to shell into with `--writable`, and no way to debug. That's fine, I can try out this "sandbox" (puts on rubber boots and recedes to being 3 year old, finger ready to go straight into nose). I am patient, this is probably what I should have done:

```
sudo singularity build --writable --sandbox scif.img Singularity
WARNING: You should only run this command within a root-owned directory
```

Well *E*&^% my entire home is where my life sits, and what am I going to do, arbitrarily make permissions weird and move things around to get this to work? That sounds like a disaster This is not a solution. Maybe I can try without sudo?

```
singularity build  --sandbox scif.img Singularity
WARNING: Building sandbox as non-root will result in wrong file permissions
Using container recipe deffile: Singularity
ERROR: You must be the root user to build from a definition file
```
Great, it almost lets me do it... but just kidding! This is my worst nightmare, Singularity is useless for development without some non trivial hacks. I want to:

 - build from a definition file
 - not need a "root owned" locatoin
 - not lose all the time of building if there is an error (aka, let me shell into my broken image and do what developers do.. debug it!)

**Comment by GodloveD** [comment]
So... much... drama... 🙀 😜 

lol

@gmkurtzer can correct me if I am wrong, but I'm pretty sure that the warning you encountered is just a courtesy to try to help prevent you from overwriting a user's directory.  You can override it with `--force`.  Try something like this:
```
$ sudo ~/sing-dev/bin/singularity build --force --sandbox ubuntu ~/versioned/singularity/examples/ubuntu/Singularity

$ sudo ~/sing-dev/bin/singularity shell --writable ubuntu

$ apt-get -y update

$ apt-get -y install vim

$ exit

$ sudo ~/sing-dev/bin/singularity build ubuntuNvim.img ubuntu

$ ~/sing-dev/bin/singularity shell ubuntuNvim.img

$ which vim
/usr/bin/vim
```
Does this usage suit your needs?  

Also, I a going to add `-s|--sandbox|--development` to the .exec file just for you.  😉

**Comment by vsoch** [comment]
Could you elaborate on why a sandbox could possibly over write my directory? That sounds like something evil Docker would do :)

HUGE +1 for --dev or --devel or --development. I would even say rid of sandbox entirely before it is introduced at all!

If force is the solution, it still seems a bit unnatural (e.g. a lot of args) to need to put just for a standard workflow. Before I'd do

          sudo singularity bootstrap <container> <spec>

and now I have to do

          sudo singularity build --force --devel --writable?? <container <spec>

I see that writable is used after, but doesn't it follow logically if I do development I want it? If anything, a development image should always be writable and give error if used in a different context. It's pretty long and kind of confusing how each of those flags really changes things.

**Comment by gmkurtzer** [comment]
The sandbox directory ownership is just a warning such that you don't use your `sudo` powers to create root owned files within your personal home directory, but again, it is just a warning. 

I have some ideas as well on how to make things a bit more logical from your comments.

Oh, and I would prefer the name of sandbox then be renamed to `--directory|--dir` or something like that. Not `--development`.

note: Sandbox is a commonly used name for this sort of thing so I think it should be kept as well.

**Comment by vsoch** [comment]
looking forward to see updates on this! Let me know if I can help.

**Comment by gmkurtzer** [comment]
@vsoch Can you confirm we are now at a thumbs up on this? Thanks!

**Comment by vsoch** [comment]
hehe yes, the changes are just what we needed! Closing.
