### ISSUE TITLE
instance.start opts need to be clarified 

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#969]
## Version of Singularity:

2.3.9-development.g60c0a75

### Expected behavior

All options will make sense and work as expected.

### Actual behavior
The following options should be changed:

`--cleanenv` should be removed and made default behavior. `shell` can introduce env vars into running instance when called without `--cleanenv` (or should)
`--pwd` (should be removed) 
`--overalay` should be added

**Comment by gmkurtzer** [comment]
I think everything in this issue has been resolved. Can you confirm @bauerm97 and @GodloveD?

Thanks!

**Comment by GodloveD** [comment]
@bauerm97 and @gmkurtzer I can confirmed that this is working as expected.  Closing.
