### ISSUE TITLE
Running writable image has permissions error

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#972]
When creating a writable image with build, when I try to run to test it without sudo, I get many permissions errors, eg:

```
singularity run --app mapping --bind data:/scif/data carrierseq.img
Indexing reference genome...
[bwa_index] Pack FASTA... [bns_fasta2bntseq] fail to open file '/scif/apps/reference/lambda_ecoli.fa.pac' : Permission denied
```

Is it the case that I can test / develop as sudo, but I can't test actual running of the image? I could do this before with bootstrap.

**Comment by gmkurtzer** [comment]
How does that file open try to open the file (e.g. writable)?
