### ISSUE TITLE
image.export missing -f option

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#985]
## Version of Singularity:

2.4 (on cclerget branch / current PR)

### Expected behavior

```
singularity image.export -f image.tar container.simg

```
### Actual behavior

```
singularity image.export -f exporty.tar 3308c2c40dd404eb87da892ba0aea32a 
tar: Refusing to write archive contents to terminal (missing -f option?)
tar: Error is not recoverable: exiting now
```

### Steps to reproduce behavior

export something!

**Comment by gmkurtzer** [comment]
Oh, at the moment we have a bit of a confusion in the docs about this. I was thinking we wouldn't be supporting -f anymore (as a simple shell redirect will suffice), but while the option is no longer detailed in the help output, it is in the examples.

We either need to remove it from the examples (my preference), or re-add the -f functionality. To that point, is a -f necessary?

**Comment by vsoch** [comment]
I think so- the two use cases are export to pipe, or file. I use both, and so i'd vote to nix -f and keep --file

**Comment by gmkurtzer** [comment]
Oh, sorry for the confusion, -f and --file are the same, both reference a file instead of pipe. Do you still feel the need to keep the -f/--file option, or can we nix it?

**Comment by vsoch** [comment]
Yes, if only because using pipe from other wrappers (eg singularity python) is much harder. Without --file, instead of a more stable subprocess command I need to do an os.system (and this only gives met the return code) and hope it turns out ok :) With subprocess I can get back more information about the output and error code.

For -f vs --file, I would remove -f because it can be confused with force. But keep --file

**Comment by gmkurtzer** [comment]
This should be fixed now. I've re-added support for both file both via an option and a second argument. Let me know if it is broked.
