### ISSUE TITLE
 Segmentation fault in postbootstrap.sh

### ISSUE THREAD

**Issue by hisplan** [apptainer/singularity#988]
## Version of Singularity:

2.2.1

### Expected behavior

Should successfully build an image.

### Actual behavior

Throws an exception and dies.

```
Executing Postbootstrap module
+ cp /vagrant/build/scripts/settings-container.sh /var/singularity/mnt/final/tmp
/usr/local/libexec/singularity/bootstrap/modules-v2/postbootstrap.sh: line 219: 22339 Done                    singularity_section_get "post" "$SINGULARITY_BUILDDEF"
     22340 Segmentation fault      (core dumped) | chroot "$SINGULARITY_ROOTFS" /bin/sh -e -x $ARGS
ERROR: Aborting with RETVAL=255
```

### Steps to reproduce behavior

Worked fine for months until I installed:

```
$ sudo apt-get install -y zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev
```

The image that I'm building also has these libraries installed. With Docker, everything is still fine. When trying to convert this docker image to Singularity image, it fails with the above error message.

**Comment by hisplan** [comment]
If Singularity is truly containerizing, isolating, I don't understand why before and after doing `sudo apt-get install -y zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev` on the host matters...

**Comment by vsoch** [comment]
hmm that's a good question. How can you say for sure that was the change? Have you tried development branch?

**Comment by hisplan** [comment]
Our #1 goal is reproducibility. We do not make images manually. Everything is scripted, automated. And we do all these operations inside a vagrant box which is also programatically created.

I'm pretty sure that's the only four libs added to the vagrant box, but I can retry before/after again.

Yes, I have tried dev branch - didn't work. As briefly mentioned in the issue #920, our team is relatively satisfied with 2.2.1 in the production environment. The only reason we tried 2.3.x and dev branch was because of this strange issue.

**Comment by gmkurtzer** [comment]
Can this be tested again with the 2.4 beta that we are about to release? It would be great to squash this bug before the next release!

The 2.4 beta is currently in the development branch in github.

Thanks!

**Comment by gmkurtzer** [comment]
@hisplan Can you also send us the output of `dmesg` when this bug is triggered? Maybe that will yield a hint as to the source of the error. Thanks!

**Comment by yhcote** [comment]
Does it add to the kernel logs (dmesg command to query) when you get the
segmentation fault ?

On Wed, Oct 4, 2017 at 9:06 AM, Gregory M. Kurtzer <notifications@github.com

**Comment by gmkurtzer** [comment]
More recent kernels do, yes.

**Comment by dtrudg** [comment]
Closing as no update for 2 years, and we are now supporting Singularity 3.x, which uses a different build system. Please feel free to open an issue if you experience this problem on Singularity 3.x
