### ISSUE TITLE
space not being freed from disk after deleting a container

### ISSUE THREAD

**Issue by cokelaer** [apptainer/singularity#992]
## Version of Singularity:

2.3.1-dist

### Expected behavior

When deleting an image, space disk should be freed. 

### Actual behavior

does not free disk space. This does not seem to be systematic.

### Steps to reproduce behavior

This may not be systematic. Could be linked to large images? HEre, the issue happened with a large container size (5.8Gb) filled with at least 4.5Gb of data and software.

```
 singularity create -size 5800 test.img
 sudo singularity bootstrap test.img Singularity 
 rm test.img
 ```
When typing **df** my disk is full ... despite deleting the 5.8Gb file. 
I have to reboot, in which case, the 5.8Gb are freed for real.

**Comment by cokelaer** [comment]
FYI, the HOME/.singularity is almost empty so the issue is not there.

I've seen this issue that may be useful but could find any solutions yet : https://github.com/singularityware/singularity/issues/471

**Comment by vsoch** [comment]
just for sanity check - you are clearing `/root//.singularity` and don't have any environment variables set to disable the cache or change it? Could you run the above command with --debug and share the output?

**Comment by cokelaer** [comment]
Sorry, which "above command" are you speaking about ?

**Comment by vsoch** [comment]
```
sudo singularity bootstrap test.img Singularity 
```

**Comment by cokelaer** [comment]
Here are the out and err files created by these commands
```
singularity create --size 5800 sequana.img
sudo singularity bootstrap  sequana.img Singularity --debug 1>out.txt 2>err.txt
```
Note that I renamed Singularity into Singularity.txt to be able to post it in this issue.

[out.txt](https://github.com/singularityware/singularity/files/1348765/out.txt)
[err.txt](https://github.com/singularityware/singularity/files/1348766/err.txt)
[Singularity.txt](https://github.com/singularityware/singularity/files/1348768/Singularity.txt)

**Comment by vsoch** [comment]
the debug should go between the "singularity" and "bootstrap"
```
sudo singularity --debug bootstrap  sequana.img Singularity 1>out.txt 2>err.txt
```

**Comment by vsoch** [comment]
oh, and I think a lot of your pains would be reduced if you used the docker image of debian. Instead of:

```
BootStrap: debootstrap
DistType "debian"
MirrorURL: http://us.archive.ubuntu.com/ubuntu/
OSVersion: xenial
```
just do:
```
BootStrap: docker
From: debian
```
or for xenial
```
BootStrap: docker
From: ubuntu:xenial
```

The issues with debootstrap is that there is some library that needs to be consistent with the host (rpm?) and it leads to many errors that just go away when you use the one that is already built (and dumped in layers via docker).

**Comment by cokelaer** [comment]
Okay, I re-run the creation of the container with the correct command and here below are the log files


```
singularity create --size 5800 sequana.img
sudo singularity --debug bootstrap  sequana.img Singularity  1>out.txt 2>err.txt
```

[out.txt](https://github.com/singularityware/singularity/files/1350041/out.txt)
[err.txt](https://github.com/singularityware/singularity/files/1350042/err.txt)

**Comment by cokelaer** [comment]
I deleted the file and the behaviour is as expected (space is freed). 

Here is another possible hint. The problem occured several times now. When the last problem occured, it happened that the creation of the container failed because I filled my hard disk to 100% . This may have caused the issue.

**Comment by gmkurtzer** [comment]
The kernel will not free the space if there is still a file descriptor or mount referencing that file. I would bet that is what is going on. If it is convenient for you, can you upgrade to our beta release in the development branch and see if it is fixed there? (note, use the build command instead of create and bootstrap).

Thanks!

**Comment by cokelaer** [comment]
@gmkurtzer @vsoch 

I am closing this issue. I am now using the version 2.4.0 and I have not seen any such issue anymore. 
thanks for the different feedbacks

**Comment by vsoch** [comment]
woohoo great!
