### ISSUE TITLE
2.4 development/alpine linux autoreconf warning

### ISSUE THREAD

**Issue by truatpasteurdotfr** [apptainer/singularity#993]
## Version of Singularity:
git development version
commit 83ceb6c414fca644e5140fb897aac530fd63050f

### Expected behavior

no error from autoreconf

### Actual behavior

  Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3936.

### Steps to reproduce behavior

  $ git clone https://github.com/singularityware/singularity.git
Cloning into 'singularity'...
remote: Counting objects: 25160, done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 25160 (delta 110), reused 118 (delta 65), pack-reused 24972
Receiving objects: 100% (25160/25160), 4.58 MiB | 8.20 MiB/s, done.
Resolving deltas: 100% (18400/18400), done.
  $ cd singularity/
  $ git checkout development
Branch development set up to track remote branch development from origin.
Switched to a new branch 'development'
  $ sh ./autogen.sh
+autoreconf -i -f
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3936.
configure.ac:34: installing './compile'
configure.ac:9: installing './config.guess'
configure.ac:9: installing './config.sub'
configure.ac:30: installing './install-sh'
configure.ac:30: installing './missing'
src/Makefile.am: installing './depcomp'

**Comment by truatpasteurdotfr** [comment]
```
alpine:~/git/singularity$ apk version libtool automake autoconf
Installed:                                Available:
libtool-2.4.6-r1                        = 2.4.6-r1 
automake-1.15-r0                        = 1.15-r0 
autoconf-2.69-r0                        = 2.69-r0 
alpine:~/git/singularity$ 
```

**Comment by gmkurtzer** [comment]
Hrmm... do you have any idea where this is coming from?

**Comment by truatpasteurdotfr** [comment]
https://unix.stackexchange.com/questions/238539/automake-error-unescaped-left-brace-in-regex-is-deprecated  is hinting a perl version issue (perl-5.24.1-r2 on the alpine box)

**Comment by gmkurtzer** [comment]
Ahh, whew! So there is a perl / autogen misalignment in Alpine?

**Comment by truatpasteurdotfr** [comment]
http://gnu-automake.7480.n7.nabble.com/bug-23602-Unescaped-left-brace-in-regex-is-deprecated-passed-through-in-regex-td22201.html suggest that it is FIXED in automake 1.15.1

**Comment by truatpasteurdotfr** [comment]
https://git.alpinelinux.org/cgit/aports/commit/?id=c43bfe9a1948ccd0d8e04a03858b6092f50ec0cc automake 1.151.1 + patch
```
--  $text =~ s/\${([^ \t=:+{}]+)}/substitute_ac_subst_variables_worker ($1)/ge;
-+  $text =~ s/\$[{]([^ \t=:+{}]+)}/substitute_ac_subst_variables_worker ($1)/ge;
```

I have manually patch automake 1.15 with ^^ and that fixes the error. :D 

-> closing as no need fixing

**Comment by gmkurtzer** [comment]
Ewww, patching automake is not fun, great job on that!
